Qt 4.8: QBuiltInMimes Class Reference
QBuiltInMimes Class Reference
Public Functions
bool canConvertFromMime (const FORMATETC &formatetc, const QMimeData *mimeData) const
Returns true if the converter can convert from the mimeData to the format specified in formatetc.
bool canConvertToMime (const QString &mimeType, IDataObject *pDataObj) const
Returns true if the converter can convert to the mimeType from the available formats in pDataObj.
bool convertFromMime (const FORMATETC &formatetc, const QMimeData *mimeData, STGMEDIUM *pmedium) const
Convert the mimeData to the format specified in formatetc.
QVariant convertToMime (const QString &mime, IDataObject *pDataObj, QVariant::Type preferredType) const
Returns a QVariant containing the converted data for mimeType from pDataObj.
QVector< FORMATETC > formatsForMime (const QString &mimeType, const QMimeData *mimeData) const
Returns a QVector of FORMATETC structures representing the different windows clipboard formats that can be provided for the mimeType from the mimeData.
QString mimeForFormat (const FORMATETC &formatetc) const
Returns the mime type that will be created form the format specified in formatetc, or an empty string if this converter does not support formatetc.
QBuiltInMimes ()
Public Functions inherited from QWindowsMime
QWindowsMime ()
Constructs a new conversion object, adding it to the globally accessed list of available converters.
virtual ~QWindowsMime ()
Destroys a conversion object, removing it from the global list of available converters.
Properties
QMap< int, QString > inFormats
QMap< int, QString > outFormats
Additional Inherited Members
Static Public Functions inherited from QWindowsMime
static int registerMimeType (const QString &mime)
Registers the MIME type mime, and returns an ID number identifying the format on Windows.
Detailed Description
Definition at line 1035 of file qmime_win.cpp.
Constructors and Destructors
QBuiltInMimes()
QBuiltInMimes::QBuiltInMimes ()
Definition at line 1055 of file qmime_win.cpp.
 : QWindowsMime()
 {
     outFormats.insert(QWindowsMime::registerMimeType(QLatin1String("application/x-color")), QLatin1String("application/x-color"));
     inFormats.insert(QWindowsMime::registerMimeType(QLatin1String("application/x-color")), QLatin1String("application/x-color"));
 }
Functions
canConvertFromMime()
bool QBuiltInMimes::canConvertFromMime (const FORMATETC & formatetc, const QMimeData * mimeData) const virtual
Returns true if the converter can convert from the mimeData to the format specified in formatetc.
All subclasses must reimplement this pure virtual function.
Implements QWindowsMime.
Definition at line 1062 of file qmime_win.cpp.
Referenced by convertFromMime(), and QLastResortMimes::convertFromMime().
 {
     // really check
     return formatetc.tymed & TYMED_HGLOBAL
         && outFormats.contains(formatetc.cfFormat)
         && mimeData->formats().contains(outFormats.value(formatetc.cfFormat));
 }
canConvertToMime()
bool QBuiltInMimes::canConvertToMime (const QString & mimeType, IDataObject * pDataObj) const virtual
Returns true if the converter can convert to the mimeType from the available formats in pDataObj.
All subclasses must reimplement this pure virtual function.
Implements QWindowsMime.
Definition at line 1125 of file qmime_win.cpp.
Referenced by convertToMime(), and QLastResortMimes::convertToMime().
 {
     return (!inFormats.keys(mimeType).isEmpty())
         && canGetData(inFormats.key(mimeType), pDataObj);
 }
convertFromMime()
bool QBuiltInMimes::convertFromMime (const FORMATETC & formatetc, const QMimeData * mimeData, STGMEDIUM * pmedium) const virtual
Convert the mimeData to the format specified in formatetc.
The converted data should then be placed in pmedium structure.
Return true if the conversion was successful.
All subclasses must reimplement this pure virtual function.
Implements QWindowsMime.
Definition at line 1070 of file qmime_win.cpp.
 {
     if (canConvertFromMime(formatetc, mimeData)) {
         QByteArray data;
         if (outFormats.value(getCf(formatetc)) == QLatin1String("text/html")) {
             // text/html is in wide chars on windows (compatible with mozillia)
             QString html = mimeData->html();
             // same code as in the text converter up above
             const QChar *u = html.unicode();
             QString res;
             const int s = html.length();
             int maxsize = s + s/40 + 3;
             res.resize(maxsize);
             int ri = 0;
             bool cr = false;
             for (int i=0; i < s; ++i) {
                 if (*u == QLatin1Char('\r'))
                     cr = true;
                 else {
                     if (*u == QLatin1Char('\n') && !cr)
                         res[ri++] = QLatin1Char('\r');
                     cr = false;
                 }
                 res[ri++] = *u;
                 if (ri+3 >= maxsize) {
                     maxsize += maxsize/4;
                     res.resize(maxsize);
                 }
                 ++u;
             }
             res.truncate(ri);
             const int byteLength = res.length() * sizeof(ushort);
             QByteArray r(byteLength + 2, '\0');
             memcpy(r.data(), res.unicode(), byteLength);
             r[byteLength] = 0;
             r[byteLength+1] = 0;
             data = r;
         } else {
 #ifndef QT_NO_DRAGANDDROP
             data = QInternalMimeData::renderDataHelper(outFormats.value(getCf(formatetc)), mimeData);
 #endif //QT_NO_DRAGANDDROP
         }
         return setData(data, pmedium);
     }
     return false;
 }
convertToMime()
QVariant QBuiltInMimes::convertToMime (const QString & mimeType, IDataObject * pDataObj, QVariant::Type preferredType) const virtual
Returns a QVariant containing the converted data for mimeType from pDataObj.
If possible the QVariant should be of the preferredType to avoid needless conversions.
All subclasses must reimplement this pure virtual function.
Implements QWindowsMime.
Definition at line 1131 of file qmime_win.cpp.
 {
     QVariant val;
     if (canConvertToMime(mimeType, pDataObj)) {
         QByteArray data = getData(inFormats.key(mimeType), pDataObj);
         if (!data.isEmpty()) {
 #ifdef QMIME_DEBUG
             qDebug("QBuiltInMimes::convertToMime()");
 #endif
             if (mimeType == QLatin1String("text/html") && preferredType == QVariant::String) {
                 // text/html is in wide chars on windows (compatible with Mozilla)
                 val = QString::fromWCharArray((const wchar_t *)data.data());
             } else {
                 val = data; // it should be enough to return the data and let QMimeData do the rest.
             }
         }
     }
     return val;
 }
formatsForMime()
QVector< FORMATETC > QBuiltInMimes::formatsForMime (const QString & mimeType, const QMimeData * mimeData) const virtual
Returns a QVector of FORMATETC structures representing the different windows clipboard formats that can be provided for the mimeType from the mimeData.
All subclasses must reimplement this pure virtual function.
Implements QWindowsMime.
Definition at line 1117 of file qmime_win.cpp.
 {
     QVector<FORMATETC> formatetcs;
     if (!outFormats.keys(mimeType).isEmpty() && mimeData->formats().contains(mimeType))
         formatetcs += setCf(outFormats.key(mimeType));
     return formatetcs;
 }
mimeForFormat()
QString QBuiltInMimes::mimeForFormat (const FORMATETC & formatetc) const virtual
Returns the mime type that will be created form the format specified in formatetc, or an empty string if this converter does not support formatetc.
All subclasses must reimplement this pure virtual function.
Implements QWindowsMime.
Definition at line 1151 of file qmime_win.cpp.
 {
     return inFormats.value(getCf(formatetc));
 }
Properties
inFormats
QMap<int, QString> QBuiltInMimes::inFormats private
Definition at line 1052 of file qmime_win.cpp.
Referenced by canConvertToMime(), convertToMime(), mimeForFormat(), and QBuiltInMimes().
outFormats
QMap<int, QString> QBuiltInMimes::outFormats private
Definition at line 1051 of file qmime_win.cpp.
Referenced by canConvertFromMime(), convertFromMime(), formatsForMime(), and QBuiltInMimes().
The documentation for this class was generated from the following file:
/src/gui/kernel/qmime_win.cpp