Qt 4.8: QScreenDriverFactory Class Reference
QScreenDriverFactory Class Reference
The QScreenDriverFactory class creates screen drivers in Qt for Embedded Linux.
#include <qscreendriverfactory_qws.h>
Static Public Functions
static QScreen * create (const QString &, int)
static QStringList keys ()
Returns the list of valid keys, i.e.
Detailed Description
The QScreenDriverFactory class creates screen drivers in Qt for Embedded Linux.
Note that this class is only available in Qt for Embedded Linux.
QScreenDriverFactory is used to detect and instantiate the available screen drivers, allowing Qt for Embedded Linux to load the preferred driver into the server application at runtime. The create() function returns a QScreen object representing the screen driver identified by a given key. The valid keys (i.e. the supported drivers) can be retrieved using the keys() function.
Qt for Embedded Linux provides several built-in screen drivers. In addition, custom screen drivers can be added using Qt's plugin mechanism, i.e. by subclassing the QScreen class and creating a screen driver plugin (QScreenDriverPlugin). See the Qt for Embedded Linux Display Management{display management} documentation for details.
See also
QScreen, QScreenDriverPlugin
Definition at line 56 of file qscreendriverfactory_qws.h.
Functions
create()
static QScreen* QScreenDriverFactory::create (const QString & , int) static
Referenced by qt_get_screen().
keys()
QStringList QScreenDriverFactory::keys () static
Returns the list of valid keys, i.e.
the available screen drivers.
See also
create()
Definition at line 163 of file qscreendriverfactory_qws.cpp.
Referenced by QVNCScreen::connect(), QTransformedScreen::connect(), and qt_get_screen().
 {
     QStringList list;
 #if defined(Q_OS_QNX) && !defined(QT_NO_QWS_QNX)
     list << QLatin1String("QNX");
 #endif
 #if defined(Q_OS_INTEGRITY) && !defined(QT_NO_QWS_INTEGRITY)
     list << QLatin1String("INTEGRITYFB");
 #endif
 #ifndef QT_NO_QWS_QVFB
     list << QLatin1String("QVFb");
 #endif
 #ifndef QT_NO_QWS_LINUXFB
     list << QLatin1String("LinuxFb");
 #endif
 #ifndef QT_NO_QWS_TRANSFORMED
     list << QLatin1String("Transformed");
 #endif
 #ifndef QT_NO_QWS_VNC
     list << QLatin1String("VNC");
 #endif
 #ifndef QT_NO_QWS_MULTISCREEN
     list << QLatin1String("Multi");
 #endif
 #if !defined(Q_OS_WIN32) || defined(QT_MAKEDLL)
 #ifndef QT_NO_LIBRARY
     QStringList plugins = loader()->keys();
     for (int i = 0; i < plugins.size(); ++i) {
 # ifdef QT_NO_QWS_QVFB
         // give QVFb top priority for autodetection
         if (plugins.at(i) == QLatin1String("QVFb"))
             list.prepend(plugins.at(i));
         else
 # endif
         if (!list.contains(plugins.at(i)))
             list += plugins.at(i);
     }
 #endif //QT_NO_LIBRARY
 #endif //QT_MAKEDLL
     return list;
 }
The documentation for this class was generated from the following files:
/src/gui/embedded/qscreendriverfactory_qws.h
/src/gui/embedded/qscreendriverfactory_qws.cpp