Qt 4.8: QXmlResultItems Class Reference
QXmlResultItems Class Reference
The QXmlResultItems class iterates through the results of evaluating an XQuery in QXmlQuery.
#include <qxmlresultitems.h>
Public Functions
QXmlItem current () const
Returns the current item.
bool hasError () const
If an error occurred during evaluation of the query, true is returned.
QXmlItem next ()
Returns the next result in the sequence produced by lazy evaluation of the associated query.
QXmlResultItems ()
Constructs an instance of QXmlResultItems.
virtual ~QXmlResultItems ()
Destroys this instance of QXmlResultItems.
Properties
QScopedPointer< QXmlResultItemsPrivate > d_ptr
Friends
class QXmlQuery
Detailed Description
The QXmlResultItems class iterates through the results of evaluating an XQuery in QXmlQuery.
Note
This class or function is reentrant.
Since
4.4
QXmlResultItems presents the evaluation of an associated query as a sequence of QXmlItems. The sequence is traversed by repeatedly calling next(), which actually produces the sequence by lazy evaluation of the query.
QXmlQuery query;
query.setQuery("<e/>, 1, 'two'");
QXmlResultItems result;
if (query.isValid()) {
    query.evaluateTo(&result);
    QXmlItem item(result.next());
    while (!item.isNull()) {
        // use item
        item = result.next();
    }
    if (result.hasError())
        /* Runtime error! */;
}
An effect of letting next() produce the sequence by lazy evaluation is that a query error can occur on any call to next(). If an error occurs, both next() and current() will return the null QXmlItem, and hasError() will return true.
QXmlResultItems can be thought of as an "iterator" that traverses the sequence of query results once, in the forward direction. Each call to next() advances the iterator to the next QXmlItem in the sequence and returns it, and current() always returns the QXmlItem that next() returned the last time it was called.
Note
When using the QXmlResultItems overload of QXmlQuery::evaluateTo() to execute a query, it is advisable to create a new instance of this class for each new set of results rather than reusing an old instance.
See also
QXmlItem::isNode(), QXmlItem::isAtomicValue(), QXmlNodeModelIndex
Definition at line 57 of file qxmlresultitems.h.
Constructors and Destructors
QXmlResultItems()
QXmlResultItems::QXmlResultItems ()
Constructs an instance of QXmlResultItems.
Definition at line 86 of file qxmlresultitems.cpp.
                                  : d_ptr(new QXmlResultItemsPrivate())
 {
 }
~QXmlResultItems()
QXmlResultItems::~QXmlResultItems () virtual
Destroys this instance of QXmlResultItems.
Definition at line 93 of file qxmlresultitems.cpp.
 {
 }
Functions
current()
QXmlItem QXmlResultItems::current () const
Returns the current item.
The current item is the last item that was produced and returned by next().
Returns a null QXmlItem if there is no associated QXmlQuery.
Definition at line 131 of file qxmlresultitems.cpp.
 {
     Q_D(const QXmlResultItems);
     if(d->hasError)
         return QXmlItem();
     else
         return d->current;
 }
hasError()
bool QXmlResultItems::hasError () const
If an error occurred during evaluation of the query, true is returned.
Returns false if query evaluation has been done.
Definition at line 148 of file qxmlresultitems.cpp.
 {
     Q_D(const QXmlResultItems);
     return d->hasError;
 }
next()
QXmlItem QXmlResultItems::next ()
Returns the next result in the sequence produced by lazy evaluation of the associated query.
When the returned QXmlItem is null, either the evaluation terminated normally without producing another result, or an error occurred. Call hasError() to determine whether the null item was caused by normal termination or by an error.
Returns a null QXmlItem if there is no associated QXmlQuery.
Definition at line 106 of file qxmlresultitems.cpp.
Referenced by QDeclarativeXmlQueryEngine::doQueryJob(), QDeclarativeXmlQueryEngine::doSubQueryJob(), and QDeclarativeXmlQueryEngine::getValuesOfKeyRoles().
 {
     Q_D(QXmlResultItems);
     if(d->hasError)
         return QXmlItem();
     try
     {
         d->current = QPatternist::Item::toPublic(d->iterator->next());
         return d->current;
     }
     catch(const QPatternist::Exception)
     {
         d->current = QXmlItem();
         d->hasError = true;
         return QXmlItem();
     }
 }
Friends and Related Functions
QXmlQuery
friend class QXmlQuery friend
Definition at line 68 of file qxmlresultitems.h.
Properties
d_ptr
QScopedPointer<QXmlResultItemsPrivate> QXmlResultItems::d_ptr private
Definition at line 70 of file qxmlresultitems.h.
Referenced by QXmlQuery::evaluateTo().
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qxmlresultitems.h
/src/xmlpatterns/api/qxmlresultitems.cpp