Qt 4.8: QDeclarativeVisualDataModel Class Reference
QDeclarativeVisualDataModel Class Reference
#include <qdeclarativevisualitemmodel_p.h>
Signals
void createdPackage (int index, QDeclarativePackage *package)
void destroyingPackage (QDeclarativePackage *package)
void rootIndexChanged ()
Signals inherited from QDeclarativeVisualModel
void countChanged ()
void createdItem (int index, QDeclarativeItem *item)
void destroyingItem (QDeclarativeItem *item)
void itemsChanged (int index, int count)
void itemsInserted (int index, int count)
void itemsMoved (int from, int to, int count)
void itemsRemoved (int index, int count)
void modelReset ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void completeItem ()
bool completePending () const
int count () const
QDeclarativeComponent * delegate () const
int indexOf (QDeclarativeItem *item, QObject *objectContext) const
bool isValid () const
QDeclarativeItem * item (int index, bool complete=true)
QDeclarativeItem * item (int index, const QByteArray &, bool complete=true)
QVariant model () const
Q_INVOKABLE QVariant modelIndex (int idx) const
Q_INVOKABLE QVariant parentModelIndex () const
QString part () const
QObject * parts ()
QDeclarativeVisualDataModel ()
QDeclarativeVisualDataModel (QDeclarativeContext *, QObject *parent=0)
ReleaseFlags release (QDeclarativeItem *item)
QVariant rootIndex () const
void setDelegate (QDeclarativeComponent *)
void setModel (const QVariant &)
void setPart (const QString &)
void setRootIndex (const QVariant &root)
virtual void setWatchedRoles (QList< QByteArray > roles)
virtual QString stringValue (int index, const QString &role)
virtual ~QDeclarativeVisualDataModel ()
Public Functions inherited from QDeclarativeVisualModel
virtual ~QDeclarativeVisualModel ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void _q_createdPackage (int index, QDeclarativePackage *package)
void _q_dataChanged (const QModelIndex &, const QModelIndex &)
void _q_destroyingPackage (QDeclarativePackage *package)
void _q_itemsChanged (int, int, const QList< int > &)
void _q_itemsInserted (int index, int count)
void _q_itemsMoved (int from, int to, int count)
void _q_itemsRemoved (int index, int count)
void _q_layoutChanged ()
void _q_modelReset ()
void _q_rowsInserted (const QModelIndex &, int, int)
void _q_rowsMoved (const QModelIndex &, int, int, const QModelIndex &, int)
void _q_rowsRemoved (const QModelIndex &, int, int)
Properties
QDeclarativeComponent * delegate
QVariant model
QString part
QObject * parts
QVariant rootIndex
Additional Inherited Members
Public Types inherited from QDeclarativeVisualModel
enum ReleaseFlag { Referenced = 0x01, Destroyed = 0x02 }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QDeclarativeVisualModel
QDeclarativeVisualModel (QObjectPrivate &dd, QObject *parent=0)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 141 of file qdeclarativevisualitemmodel_p.h.
Constructors and Destructors
QDeclarativeVisualDataModel() [1/2]
QDeclarativeVisualDataModel::QDeclarativeVisualDataModel ()
Definition at line 673 of file qdeclarativevisualitemmodel.cpp.
 : QDeclarativeVisualModel(*(new QDeclarativeVisualDataModelPrivate(0)))
 {
 }
QDeclarativeVisualDataModel() [2/2]
QDeclarativeVisualDataModel::QDeclarativeVisualDataModel (QDeclarativeContext * ctxt, QObject * parent = 0)
Definition at line 678 of file qdeclarativevisualitemmodel.cpp.
 : QDeclarativeVisualModel(*(new QDeclarativeVisualDataModelPrivate(ctxt)), parent)
 {
 }
~QDeclarativeVisualDataModel()
QDeclarativeVisualDataModel::~QDeclarativeVisualDataModel () virtual
Definition at line 683 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     if (d->m_listAccessor)
         delete d->m_listAccessor;
     if (d->m_delegateDataType)
         d->m_delegateDataType->release();
 }
Functions
_q_createdPackage
void QDeclarativeVisualDataModel::_q_createdPackage (int index, QDeclarativePackage * package) private slot
Definition at line 1440 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     emit createdItem(index, qobject_cast<QDeclarativeItem*>(package->part(d->m_part)));
 }
_q_dataChanged
void QDeclarativeVisualDataModel::_q_dataChanged (const QModelIndex & begin, const QModelIndex & end) private slot
Definition at line 1417 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     if (begin.parent() == d->m_root)
         _q_itemsChanged(begin.row(), end.row() - begin.row() + 1, d->m_roles);
 }
_q_destroyingPackage
void QDeclarativeVisualDataModel::_q_destroyingPackage (QDeclarativePackage * package) private slot
Definition at line 1446 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     emit destroyingItem(qobject_cast<QDeclarativeItem*>(package->part(d->m_part)));
 }
_q_itemsChanged
void QDeclarativeVisualDataModel::_q_itemsChanged (int index, int count, const QList< int > & roles) private slot
Definition at line 1225 of file qdeclarativevisualitemmodel.cpp.
Referenced by _q_dataChanged(), _q_layoutChanged(), and setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     bool changed = false;
     if (!d->watchedRoles.isEmpty() && d->watchedRoleIds.isEmpty()) {
         foreach (QByteArray r, d->watchedRoles) {
             if (d->m_roleNames.contains(r))
                 d->watchedRoleIds << d->m_roleNames.value(r);
         }
     }
     for (QHash<int,QDeclarativeVisualDataModelPrivate::ObjectRef>::ConstIterator iter = d->m_cache.begin();
         iter != d->m_cache.end(); ++iter) {
         const int idx = iter.key();
         if (idx >= index && idx < index+count) {
             QDeclarativeVisualDataModelPrivate::ObjectRef objRef = *iter;
             QDeclarativeVisualDataModelData *data = d->data(objRef.obj);
             for (int roleIdx = 0; roleIdx < roles.count(); ++roleIdx) {
                 int role = roles.at(roleIdx);
                 if (!changed && !d->watchedRoleIds.isEmpty() && d->watchedRoleIds.contains(role))
                     changed = true;
                 int propId = data->propForRole(role);
                 if (propId != -1) {
                     if (data->hasValue(propId)) {
                         if (d->m_listModelInterface) {
                             data->setValue(propId, d->m_listModelInterface->data(idx, role));
                         } else if (d->m_abstractItemModel) {
                             QModelIndex index = d->m_abstractItemModel->index(idx, 0, d->m_root);
                             data->setValue(propId, d->m_abstractItemModel->data(index, role));
                         }
                     }
                 } else {
                     QString roleName;
                     if (d->m_listModelInterface)
                         roleName = d->m_listModelInterface->toString(role);
                     else if (d->m_abstractItemModel)
                         roleName = QString::fromUtf8(d->m_abstractItemModel->roleNames().value(role));
                     qmlInfo(this) << "Changing role not present in item: " << roleName;
                 }
             }
             if (d->m_roles.count() == 1) {
                 // Handle the modelData role we add if there is just one role.
                 int propId = data->modelDataPropertyId();
                 if (data->hasValue(propId)) {
                     int role = d->m_roles.at(0);
                     if (d->m_listModelInterface) {
                         data->setValue(propId, d->m_listModelInterface->data(idx, role));
                     } else if (d->m_abstractItemModel) {
                         QModelIndex index = d->m_abstractItemModel->index(idx, 0, d->m_root);
                         data->setValue(propId, d->m_abstractItemModel->data(index, role));
                     }
                 }
             }
         }
     }
     if (changed)
         emit itemsChanged(index, count);
 }
_q_itemsInserted
void QDeclarativeVisualDataModel::_q_itemsInserted (int index, int count) private slot
Definition at line 1286 of file qdeclarativevisualitemmodel.cpp.
Referenced by _q_rowsInserted(), _q_rowsMoved(), and setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     if (!count)
         return;
     // XXX - highly inefficient
     QHash<int,QDeclarativeVisualDataModelPrivate::ObjectRef> items;
     for (QHash<int,QDeclarativeVisualDataModelPrivate::ObjectRef>::Iterator iter = d->m_cache.begin();
         iter != d->m_cache.end(); ) {
         if (iter.key() >= index) {
             QDeclarativeVisualDataModelPrivate::ObjectRef objRef = *iter;
             int index = iter.key() + count;
             iter = d->m_cache.erase(iter);
             items.insert(index, objRef);
             QDeclarativeVisualDataModelData *data = d->data(objRef.obj);
             data->setIndex(index);
         } else {
             ++iter;
         }
     }
     d->m_cache.unite(items);
     emit itemsInserted(index, count);
     emit countChanged();
 }
_q_itemsMoved
void QDeclarativeVisualDataModel::_q_itemsMoved (int from, int to, int count) private slot
Definition at line 1347 of file qdeclarativevisualitemmodel.cpp.
Referenced by _q_rowsMoved(), and setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     // XXX - highly inefficient
     QHash<int,QDeclarativeVisualDataModelPrivate::ObjectRef> items;
     for (QHash<int,QDeclarativeVisualDataModelPrivate::ObjectRef>::Iterator iter = d->m_cache.begin();
         iter != d->m_cache.end(); ) {
         if (iter.key() >= from && iter.key() < from + count) {
             QDeclarativeVisualDataModelPrivate::ObjectRef objRef = *iter;
             int index = iter.key() - from + to;
             iter = d->m_cache.erase(iter);
             items.insert(index, objRef);
             QDeclarativeVisualDataModelData *data = d->data(objRef.obj);
             data->setIndex(index);
         } else {
             ++iter;
         }
     }
     for (QHash<int,QDeclarativeVisualDataModelPrivate::ObjectRef>::Iterator iter = d->m_cache.begin();
         iter != d->m_cache.end(); ) {
         int diff = from > to ? count : -count;
         if (iter.key() >= qMin(from,to) && iter.key() < qMax(from+count,to+count)) {
             QDeclarativeVisualDataModelPrivate::ObjectRef objRef = *iter;
             int index = iter.key() + diff;
             iter = d->m_cache.erase(iter);
             items.insert(index, objRef);
             QDeclarativeVisualDataModelData *data = d->data(objRef.obj);
             data->setIndex(index);
         } else {
             ++iter;
         }
     }
     d->m_cache.unite(items);
     emit itemsMoved(from, to, count);
 }
_q_itemsRemoved
void QDeclarativeVisualDataModel::_q_itemsRemoved (int index, int count) private slot
Definition at line 1315 of file qdeclarativevisualitemmodel.cpp.
Referenced by _q_rowsMoved(), _q_rowsRemoved(), and setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     if (!count)
         return;
     // XXX - highly inefficient
     QHash<int, QDeclarativeVisualDataModelPrivate::ObjectRef> items;
     for (QHash<int, QDeclarativeVisualDataModelPrivate::ObjectRef>::Iterator iter = d->m_cache.begin();
         iter != d->m_cache.end(); ) {
         if (iter.key() >= index && iter.key() < index + count) {
             QDeclarativeVisualDataModelPrivate::ObjectRef objRef = *iter;
             iter = d->m_cache.erase(iter);
             items.insertMulti(-1, objRef); //XXX perhaps better to maintain separately
             QDeclarativeVisualDataModelData *data = d->data(objRef.obj);
             data->setIndex(-1);
         } else if (iter.key() >= index + count) {
             QDeclarativeVisualDataModelPrivate::ObjectRef objRef = *iter;
             int index = iter.key() - count;
             iter = d->m_cache.erase(iter);
             items.insert(index, objRef);
             QDeclarativeVisualDataModelData *data = d->data(objRef.obj);
             data->setIndex(index);
         } else {
             ++iter;
         }
     }
     d->m_cache.unite(items);
     emit itemsRemoved(index, count);
     emit countChanged();
 }
_q_layoutChanged
void QDeclarativeVisualDataModel::_q_layoutChanged () private slot
Definition at line 1424 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     _q_itemsChanged(0, count(), d->m_roles);
 }
_q_modelReset
void QDeclarativeVisualDataModel::_q_modelReset () private slot
Definition at line 1430 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     d->m_root = QModelIndex();
     emit modelReset();
     emit rootIndexChanged();
     if (d->m_abstractItemModel && d->m_abstractItemModel->canFetchMore(d->m_root))
         d->m_abstractItemModel->fetchMore(d->m_root);
 }
_q_rowsInserted
void QDeclarativeVisualDataModel::_q_rowsInserted (const QModelIndex & parent, int begin, int end) private slot
Definition at line 1390 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     if (parent == d->m_root)
         _q_itemsInserted(begin, end - begin + 1);
 }
_q_rowsMoved
void QDeclarativeVisualDataModel::_q_rowsMoved (const QModelIndex & sourceParent, int sourceStart, int sourceEnd, const QModelIndex & destinationParent, int destinationRow) private slot
Definition at line 1404 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     const int count = sourceEnd - sourceStart + 1;
     if (destinationParent == d->m_root && sourceParent == d->m_root) {
         _q_itemsMoved(sourceStart, sourceStart > destinationRow ? destinationRow : destinationRow-count, count);
     } else if (sourceParent == d->m_root) {
         _q_itemsRemoved(sourceStart, count);
     } else if (destinationParent == d->m_root) {
         _q_itemsInserted(destinationRow, count);
     }
 }
_q_rowsRemoved
void QDeclarativeVisualDataModel::_q_rowsRemoved (const QModelIndex & parent, int begin, int end) private slot
Definition at line 1397 of file qdeclarativevisualitemmodel.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeVisualDataModel);
     if (parent == d->m_root)
         _q_itemsRemoved(begin, end - begin + 1);
 }
completeItem()
void QDeclarativeVisualDataModel::completeItem () virtual
Implements QDeclarativeVisualModel.
Definition at line 1148 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     if (d->m_visualItemModel) {
         d->m_visualItemModel->completeItem();
         return;
     }
     d->m_delegate->completeCreate();
     d->m_completePending = false;
 }
completePending()
bool QDeclarativeVisualDataModel::completePending () const virtual
Implements QDeclarativeVisualModel.
Definition at line 1140 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(const QDeclarativeVisualDataModel);
     if (d->m_visualItemModel)
         return d->m_visualItemModel->completePending();
     return d->m_completePending;
 }
count()
int QDeclarativeVisualDataModel::count () const virtual
Implements QDeclarativeVisualModel.
Definition at line 969 of file qdeclarativevisualitemmodel.cpp.
Referenced by _q_itemsInserted(), _q_itemsMoved(), _q_itemsRemoved(), _q_layoutChanged(), _q_rowsMoved(), and QDeclarativeVisualDataModelPrivate::modelCount().
 {
     Q_D(const QDeclarativeVisualDataModel);
     if (d->m_visualItemModel)
         return d->m_visualItemModel->count();
     if (!d->m_delegate)
         return 0;
     return d->modelCount();
 }
createdPackage
void QDeclarativeVisualDataModel::createdPackage (int index, QDeclarativePackage * package) signal
Referenced by item(), and setModel().
delegate()
QDeclarativeComponent* QDeclarativeVisualDataModel::delegate () const
Referenced by setDelegate(), and setModel().
destroyingPackage
void QDeclarativeVisualDataModel::destroyingPackage (QDeclarativePackage * package) signal
Referenced by release(), and setModel().
indexOf()
int QDeclarativeVisualDataModel::indexOf (QDeclarativeItem * item, QObject * objectContext) const virtual
Implements QDeclarativeVisualModel.
Definition at line 1211 of file qdeclarativevisualitemmodel.cpp.
 {
     QVariant val = QDeclarativeEngine::contextForObject(item)->contextProperty(QLatin1String("index"));
         return val.toInt();
     return -1;
 }
isValid()
bool QDeclarativeVisualDataModel::isValid () const inline virtual
Implements QDeclarativeVisualModel.
Definition at line 173 of file qdeclarativevisualitemmodel_p.h.
 { return delegate() != 0; }
item() [1/2]
QDeclarativeItem * QDeclarativeVisualDataModel::item (int index, bool complete = true) virtual
Implements QDeclarativeVisualModel.
Definition at line 979 of file qdeclarativevisualitemmodel.cpp.
Referenced by item(), and release().
 {
     Q_D(QDeclarativeVisualDataModel);
     if (d->m_visualItemModel)
         return d->m_visualItemModel->item(index, d->m_part.toUtf8(), complete);
     return item(index, QByteArray(), complete);
 }
item() [2/2]
QDeclarativeItem * QDeclarativeVisualDataModel::item (int index, const QByteArray & viewId, bool complete = true)
Definition at line 1071 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     if (d->m_visualItemModel)
         return d->m_visualItemModel->item(index, viewId, complete);
     if (d->modelCount() <= 0 || !d->m_delegate)
         return 0;
     QObject *nobj = d->m_cache.getItem(index);
     bool needComplete = false;
     if (!nobj) {
         QDeclarativeContext *ccontext = d->m_context;
         if (!ccontext) ccontext = qmlContext(this);
         QDeclarativeContext *ctxt = new QDeclarativeContext(ccontext);
         QDeclarativeVisualDataModelData *data = new QDeclarativeVisualDataModelData(index, this);
         if ((!d->m_listModelInterface || !d->m_abstractItemModel) && d->m_listAccessor
             && d->m_listAccessor->type() == QDeclarativeListAccessor::ListProperty) {
             QDeclarativeContext *objCtxt = ctxt;
             objCtxt->setContextObject(d->m_listAccessor->at(index).value<QObject*>());
             ctxt = new QDeclarativeContext(ctxt);
             QDeclarative_setParent_noEvent(objCtxt, ctxt);
         }
         ctxt->setContextProperty(QLatin1String("model"), data);
         ctxt->setContextObject(data);
         d->m_completePending = false;
         nobj = d->m_delegate->beginCreate(ctxt);
         if (complete) {
             d->m_delegate->completeCreate();
         } else {
             d->m_completePending = true;
             needComplete = true;
         }
         if (nobj) {
             QDeclarative_setParent_noEvent(ctxt, nobj);
             QDeclarative_setParent_noEvent(data, nobj);
             d->m_cache.insertItem(index, nobj);
             if (QDeclarativePackage *package = qobject_cast<QDeclarativePackage *>(nobj))
                 emit createdPackage(index, package);
         } else {
             delete data;
             delete ctxt;
             qmlInfo(this, d->m_delegate->errors()) << "Error creating delegate";
         }
     }
     QDeclarativeItem *item = qobject_cast<QDeclarativeItem *>(nobj);
     if (!item) {
         QDeclarativePackage *package = qobject_cast<QDeclarativePackage *>(nobj);
         if (package) {
             QObject *o = package->part(QString::fromUtf8(viewId));
             item = qobject_cast<QDeclarativeItem *>(o);
             if (item)
                 d->m_packaged.insertMulti(item, package);
         }
     }
     if (!item) {
         if (needComplete)
             d->m_delegate->completeCreate();
         d->m_cache.releaseItem(nobj);
         if (!d->m_delegateValidated) {
             qmlInfo(d->m_delegate) << QDeclarativeVisualDataModel::tr("Delegate component must be Item type.");
             d->m_delegateValidated = true;
         }
     }
     if (d->modelCount()-1 == index && d->m_abstractItemModel && d->m_abstractItemModel->canFetchMore(d->m_root))
         d->m_abstractItemModel->fetchMore(d->m_root);
     return item;
 }
model()
QVariant QDeclarativeVisualDataModel::model () const
Referenced by setModel(), and ~QDeclarativeVisualDataModel().
modelIndex()
QVariant QDeclarativeVisualDataModel::modelIndex (int idx) const
Definition at line 926 of file qdeclarativevisualitemmodel.cpp.
Referenced by setRootIndex().
 {
     Q_D(const QDeclarativeVisualDataModel);
     if (d->m_abstractItemModel)
         return QVariant::fromValue(d->m_abstractItemModel->index(idx, 0, d->m_root));
     return QVariant::fromValue(QModelIndex());
 }
parentModelIndex()
QVariant QDeclarativeVisualDataModel::parentModelIndex () const
Definition at line 949 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(const QDeclarativeVisualDataModel);
     if (d->m_abstractItemModel)
         return QVariant::fromValue(d->m_abstractItemModel->parent(d->m_root));
     return QVariant::fromValue(QModelIndex());
 }
part()
QString QDeclarativeVisualDataModel::part () const
Referenced by parentModelIndex(), and setPart().
parts()
QObject* QDeclarativeVisualDataModel::parts ()
Referenced by release().
release()
QDeclarativeVisualDataModel::ReleaseFlags QDeclarativeVisualDataModel::release (QDeclarativeItem * item) virtual
Implements QDeclarativeVisualModel.
Definition at line 990 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     if (d->m_visualItemModel)
         return d->m_visualItemModel->release(item);
     ReleaseFlags stat = 0;
     QObject *obj = item;
     bool inPackage = false;
     QHash<QObject*,QDeclarativePackage*>::iterator it = d->m_packaged.find(item);
     if (it != d->m_packaged.end()) {
         QDeclarativePackage *package = *it;
         d->m_packaged.erase(it);
         if (d->m_packaged.contains(item))
             stat |= Referenced;
         inPackage = true;
         obj = package; // fall through and delete
     }
     if (d->m_cache.releaseItem(obj)) {
         // Remove any bindings to avoid warnings due to parent change.
         QObjectPrivate *p = QObjectPrivate::get(obj);
         Q_ASSERT(p->declarativeData);
         QDeclarativeData *d = static_cast<QDeclarativeData*>(p->declarativeData);
         if (d->ownContext && d->context)
             d->context->clearContext();
         if (inPackage) {
             emit destroyingPackage(qobject_cast<QDeclarativePackage*>(obj));
         } else {
             if (item->scene())
                 item->scene()->removeItem(item);
         }
         stat |= Destroyed;
         obj->deleteLater();
     } else if (!inPackage) {
         stat |= Referenced;
     }
     return stat;
 }
rootIndex()
QVariant QDeclarativeVisualDataModel::rootIndex () const
Referenced by setDelegate().
rootIndexChanged
void QDeclarativeVisualDataModel::rootIndexChanged () signal
Referenced by _q_modelReset(), and setRootIndex().
setDelegate()
void QDeclarativeVisualDataModel::setDelegate (QDeclarativeComponent * delegate)
Definition at line 836 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     bool wasValid = d->m_delegate != 0;
     d->m_delegate = delegate;
     d->m_delegateValidated = false;
     if (!wasValid && d->modelCount() && d->m_delegate) {
         emit itemsInserted(0, d->modelCount());
         emit countChanged();
     }
     if (wasValid && !d->m_delegate && d->modelCount()) {
         emit itemsRemoved(0, d->modelCount());
         emit countChanged();
     }
 }
setModel()
void QDeclarativeVisualDataModel::setModel (const QVariant & model)
Definition at line 714 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelPartsMetaObject::initialValue().
 {
     Q_D(QDeclarativeVisualDataModel);
     delete d->m_listAccessor;
     d->m_listAccessor = 0;
     d->m_modelVariant = model;
     if (d->m_listModelInterface) {
         // Assume caller has released all items.
         QObject::disconnect(d->m_listModelInterface, SIGNAL(itemsChanged(int,int,QList<int>)),
                 this, SLOT(_q_itemsChanged(int,int,QList<int>)));
         QObject::disconnect(d->m_listModelInterface, SIGNAL(itemsInserted(int,int)),
                 this, SLOT(_q_itemsInserted(int,int)));
         QObject::disconnect(d->m_listModelInterface, SIGNAL(itemsRemoved(int,int)),
                 this, SLOT(_q_itemsRemoved(int,int)));
         QObject::disconnect(d->m_listModelInterface, SIGNAL(itemsMoved(int,int,int)),
                 this, SLOT(_q_itemsMoved(int,int,int)));
         d->m_listModelInterface = 0;
     } else if (d->m_abstractItemModel) {
         QObject::disconnect(d->m_abstractItemModel, SIGNAL(rowsInserted(QModelIndex,int,int)),
                             this, SLOT(_q_rowsInserted(QModelIndex,int,int)));
         QObject::disconnect(d->m_abstractItemModel, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                             this, SLOT(_q_rowsRemoved(QModelIndex,int,int)));
         QObject::disconnect(d->m_abstractItemModel, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
                             this, SLOT(_q_dataChanged(QModelIndex,QModelIndex)));
         QObject::disconnect(d->m_abstractItemModel, SIGNAL(rowsMoved(QModelIndex,int,int,QModelIndex,int)),
                             this, SLOT(_q_rowsMoved(QModelIndex,int,int,QModelIndex,int)));
         QObject::disconnect(d->m_abstractItemModel, SIGNAL(modelReset()), this, SLOT(_q_modelReset()));
         QObject::disconnect(d->m_abstractItemModel, SIGNAL(layoutChanged()), this, SLOT(_q_layoutChanged()));
         d->m_abstractItemModel = 0;
     } else if (d->m_visualItemModel) {
         QObject::disconnect(d->m_visualItemModel, SIGNAL(itemsInserted(int,int)),
                          this, SIGNAL(itemsInserted(int,int)));
         QObject::disconnect(d->m_visualItemModel, SIGNAL(itemsRemoved(int,int)),
                          this, SIGNAL(itemsRemoved(int,int)));
         QObject::disconnect(d->m_visualItemModel, SIGNAL(itemsMoved(int,int,int)),
                          this, SIGNAL(itemsMoved(int,int,int)));
         QObject::disconnect(d->m_visualItemModel, SIGNAL(createdPackage(int,QDeclarativePackage*)),
                          this, SLOT(_q_createdPackage(int,QDeclarativePackage*)));
         QObject::disconnect(d->m_visualItemModel, SIGNAL(destroyingPackage(QDeclarativePackage*)),
                          this, SLOT(_q_destroyingPackage(QDeclarativePackage*)));
         d->m_visualItemModel = 0;
     }
     d->m_roles.clear();
     d->m_roleNames.clear();
     if (d->m_delegateDataType)
         d->m_delegateDataType->release();
     d->m_metaDataCreated = 0;
     d->m_metaDataCacheable = false;
     d->m_delegateDataType = new VDMDelegateDataType(&QDeclarativeVisualDataModelData::staticMetaObject, d->m_context?d->m_context->engine():qmlEngine(this));
     QObject *object = qvariant_cast<QObject *>(model);
     if (object && (d->m_listModelInterface = qobject_cast<QListModelInterface *>(object))) {
         QObject::connect(d->m_listModelInterface, SIGNAL(itemsChanged(int,int,QList<int>)),
                          this, SLOT(_q_itemsChanged(int,int,QList<int>)));
         QObject::connect(d->m_listModelInterface, SIGNAL(itemsInserted(int,int)),
                          this, SLOT(_q_itemsInserted(int,int)));
         QObject::connect(d->m_listModelInterface, SIGNAL(itemsRemoved(int,int)),
                          this, SLOT(_q_itemsRemoved(int,int)));
         QObject::connect(d->m_listModelInterface, SIGNAL(itemsMoved(int,int,int)),
                          this, SLOT(_q_itemsMoved(int,int,int)));
         d->m_metaDataCacheable = true;
         if (d->m_delegate && d->m_listModelInterface->count())
             emit itemsInserted(0, d->m_listModelInterface->count());
         return;
     } else if (object && (d->m_abstractItemModel = qobject_cast<QAbstractItemModel *>(object))) {
         QObject::connect(d->m_abstractItemModel, SIGNAL(rowsInserted(QModelIndex,int,int)),
                             this, SLOT(_q_rowsInserted(QModelIndex,int,int)));
         QObject::connect(d->m_abstractItemModel, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                             this, SLOT(_q_rowsRemoved(QModelIndex,int,int)));
         QObject::connect(d->m_abstractItemModel, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
                             this, SLOT(_q_dataChanged(QModelIndex,QModelIndex)));
         QObject::connect(d->m_abstractItemModel, SIGNAL(rowsMoved(QModelIndex,int,int,QModelIndex,int)),
                             this, SLOT(_q_rowsMoved(QModelIndex,int,int,QModelIndex,int)));
         QObject::connect(d->m_abstractItemModel, SIGNAL(modelReset()), this, SLOT(_q_modelReset()));
         QObject::connect(d->m_abstractItemModel, SIGNAL(layoutChanged()), this, SLOT(_q_layoutChanged()));
         d->m_metaDataCacheable = true;
         if (d->m_abstractItemModel->canFetchMore(d->m_root))
             d->m_abstractItemModel->fetchMore(d->m_root);
         return;
     }
     if ((d->m_visualItemModel = qvariant_cast<QDeclarativeVisualDataModel *>(model))) {
         QObject::connect(d->m_visualItemModel, SIGNAL(itemsInserted(int,int)),
                          this, SIGNAL(itemsInserted(int,int)));
         QObject::connect(d->m_visualItemModel, SIGNAL(itemsRemoved(int,int)),
                          this, SIGNAL(itemsRemoved(int,int)));
         QObject::connect(d->m_visualItemModel, SIGNAL(itemsMoved(int,int,int)),
                          this, SIGNAL(itemsMoved(int,int,int)));
         QObject::connect(d->m_visualItemModel, SIGNAL(createdPackage(int,QDeclarativePackage*)),
                          this, SLOT(_q_createdPackage(int,QDeclarativePackage*)));
         QObject::connect(d->m_visualItemModel, SIGNAL(destroyingPackage(QDeclarativePackage*)),
                          this, SLOT(_q_destroyingPackage(QDeclarativePackage*)));
         return;
     }
     d->m_listAccessor = new QDeclarativeListAccessor;
     d->m_listAccessor->setList(model, d->m_context?d->m_context->engine():qmlEngine(this));
     if (d->m_listAccessor->type() != QDeclarativeListAccessor::ListProperty)
         d->m_metaDataCacheable = true;
     if (d->m_delegate && d->modelCount()) {
         emit itemsInserted(0, d->modelCount());
         emit countChanged();
     }
 }
setPart()
void QDeclarativeVisualDataModel::setPart (const QString & part)
Definition at line 963 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelPartsMetaObject::initialValue().
 {
     Q_D(QDeclarativeVisualDataModel);
     d->m_part = part;
 }
setRootIndex()
void QDeclarativeVisualDataModel::setRootIndex (const QVariant & root)
Definition at line 890 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     QModelIndex modelIndex = qvariant_cast<QModelIndex>(root);
     if (d->m_root != modelIndex) {
         int oldCount = d->modelCount();
         d->m_root = modelIndex;
         if (d->m_abstractItemModel && d->m_abstractItemModel->canFetchMore(modelIndex))
             d->m_abstractItemModel->fetchMore(modelIndex);
         int newCount = d->modelCount();
         if (d->m_delegate && oldCount)
             emit itemsRemoved(0, oldCount);
         if (d->m_delegate && newCount)
             emit itemsInserted(0, newCount);
         if (newCount != oldCount)
             emit countChanged();
         emit rootIndexChanged();
     }
 }
setWatchedRoles()
void QDeclarativeVisualDataModel::setWatchedRoles (QList< QByteArray > roles) virtual
Implements QDeclarativeVisualModel.
Definition at line 1218 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     d->watchedRoles = roles;
     d->watchedRoleIds.clear();
 }
stringValue()
QString QDeclarativeVisualDataModel::stringValue (int index, const QString & role) virtual
Implements QDeclarativeVisualModel.
Definition at line 1160 of file qdeclarativevisualitemmodel.cpp.
 {
     Q_D(QDeclarativeVisualDataModel);
     if (d->m_visualItemModel)
         return d->m_visualItemModel->stringValue(index, name);
     if ((!d->m_listModelInterface || !d->m_abstractItemModel) && d->m_listAccessor) {
         if (QObject *object = d->m_listAccessor->at(index).value<QObject*>())
             return object->property(name.toUtf8()).toString();
     }
     if ((!d->m_listModelInterface && !d->m_abstractItemModel) || !d->m_delegate)
         return QString();
     QString val;
     QObject *data = 0;
     bool tempData = false;
     if (QObject *nobj = d->m_cache.item(index))
         data = d->data(nobj);
     if (!data) {
         data = new QDeclarativeVisualDataModelData(index, this);
         tempData = true;
     }
     QDeclarativeData *ddata = QDeclarativeData::get(data);
     if (ddata && ddata->propertyCache) {
         QDeclarativePropertyCache::Data *prop = ddata->propertyCache->property(name);
         if (prop) {
             if (prop->propType == QVariant::String) {
                 void *args[] = { &val, 0 };
                 QMetaObject::metacall(data, QMetaObject::ReadProperty, prop->coreIndex, args);
             } else if (prop->propType == qMetaTypeId<QVariant>()) {
                 QVariant v;
                 void *args[] = { &v, 0 };
                 QMetaObject::metacall(data, QMetaObject::ReadProperty, prop->coreIndex, args);
                 val = v.toString();
             }
         } else {
             val = data->property(name.toUtf8()).toString();
         }
     } else {
         val = data->property(name.toUtf8()).toString();
     }
     if (tempData)
         delete data;
     return val;
 }
Properties
delegate
QDeclarativeComponent * QDeclarativeVisualDataModel::delegate private
Definition at line 147 of file qdeclarativevisualitemmodel_p.h.
model
QVariant QDeclarativeVisualDataModel::model private
Definition at line 146 of file qdeclarativevisualitemmodel_p.h.
part
QString QDeclarativeVisualDataModel::part private
Definition at line 148 of file qdeclarativevisualitemmodel_p.h.
parts
QObject * QDeclarativeVisualDataModel::parts private
Definition at line 149 of file qdeclarativevisualitemmodel_p.h.
rootIndex
QVariant QDeclarativeVisualDataModel::rootIndex private
Definition at line 150 of file qdeclarativevisualitemmodel_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativevisualitemmodel_p.h
/src/declarative/graphicsitems/qdeclarativevisualitemmodel.cpp