Qt 4.8: QConicalGradient Class Reference
QConicalGradient Class Reference
The QConicalGradient class is used in combination with QBrush to specify a conical gradient brush.
#include <qbrush.h>
Public Functions
qreal angle () const
Returns the start angle of the conical gradient in logical coordinates.
QPointF center () const
Returns the center of the conical gradient in logical coordinates.
QConicalGradient ()
Constructs a conical with center at (0, 0) starting the interpolation at angle 0.
QConicalGradient (const QPointF &center, qreal startAngle)
Constructs a conical gradient with the given center, starting the interpolation at the given angle.
QConicalGradient (qreal cx, qreal cy, qreal startAngle)
Constructs a conical gradient with the given center (cx, cy), starting the interpolation at the given angle.
void setAngle (qreal angle)
Sets angle to be the start angle for this conical gradient in logical coordinates.
void setCenter (const QPointF &center)
Sets the center of this conical gradient in logical coordinates to center.
void setCenter (qreal x, qreal y)
Sets the center of this conical gradient in logical coordinates to (x, y).
Public Functions inherited from QGradient
CoordinateMode coordinateMode () const
Returns the coordinate mode of this gradient.
InterpolationMode interpolationMode () const
Returns the interpolation mode of this gradient.
bool operator!= (const QGradient &other) const
Returns true if the gradient is the same as the other gradient specified; otherwise returns false.
bool operator== (const QGradient &gradient) const
Returns true if the gradient is the same as the other gradient specified; otherwise returns false.
bool operator== (const QGradient &gradient)
QGradient ()
void setColorAt (qreal pos, const QColor &color)
Creates a stop point at the given position with the given color.
void setCoordinateMode (CoordinateMode mode)
Sets the coordinate mode of this gradient to mode.
void setInterpolationMode (InterpolationMode mode)
Sets the interpolation mode of this gradient to mode.
void setSpread (Spread spread)
Specifies the spread method that should be used for this gradient.
void setStops (const QGradientStops &stops)
Replaces the current set of stop points with the given stopPoints.
Spread spread () const
Returns the spread method use by this gradient.
QGradientStops stops () const
Returns the stop points for this gradient.
Type type () const
Returns the type of gradient.
Additional Inherited Members
Public Types inherited from QGradient
enum CoordinateMode { LogicalMode, StretchToDeviceMode, ObjectBoundingMode }
This enum specifies how gradient coordinates map to the paint device on which the gradient is used.
enum InterpolationMode { ColorInterpolation, ComponentInterpolation }
enum Spread { PadSpread, ReflectSpread, RepeatSpread }
Specifies how the area outside the gradient area should be filled.
enum Type { LinearGradient, RadialGradient, ConicalGradient, NoGradient }
Specifies the type of gradient.
Related Functions inherited from QGradient
QGradientStop
Typedef for QPair<qreal , QColor>.
QGradientStops
Typedef for QVector<QGradientStop>.
Detailed Description
The QConicalGradient class is used in combination with QBrush to specify a conical gradient brush.
Conical gradients interpolate interpolate colors counter-clockwise around a center point.
The colors in a gradient is defined using stop points of the QGradientStop type, i.e. a position and a color. Use the QGradient::setColorAt() or the QGradient::setStops() function to define the stop points. It is the gradient's complete set of stop points that describes how the gradient area should be filled. If no stop points have been specified, a gradient of black at 0 to white at 1 is used.
In addition to the functions inherited from QGradient, the QConicalGradient class provides the angle() and center() functions returning the start angle and center of the gradient.
Note that the setSpread() function has no effect for conical gradients. The reason is that the conical gradient is closed by definition, i.e. the conical gradient fills the entire circle from 0 - 360 degrees, while the boundary of a radial or a linear gradient can be specified through its radius or final stop points, respectively.
See also
QLinearGradient, QRadialGradient, {demos/gradients}{The Gradients Demo}
Definition at line 329 of file qbrush.h.
Constructors and Destructors
QConicalGradient() [1/3]
QConicalGradient::QConicalGradient ()
Constructs a conical with center at (0, 0) starting the interpolation at angle 0.
See also
QGradient::setColorAt(), setCenter(), setAngle()
Definition at line 2374 of file qbrush.cpp.
 {
     m_type = ConicalGradient;
     m_spread = PadSpread;
     m_data.conical.cx = 0;
     m_data.conical.cy = 0;
     m_data.conical.angle = 0;
 }
QConicalGradient() [2/3]
QConicalGradient::QConicalGradient (const QPointF & center, qreal angle)
Constructs a conical gradient with the given center, starting the interpolation at the given angle.
The angle must be specified in degrees between 0 and 360.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 2339 of file qbrush.cpp.
 {
     m_type = ConicalGradient;
     m_spread = PadSpread;
     m_data.conical.cx = center.x();
     m_data.conical.cy = center.y();
     m_data.conical.angle = angle;
 }
QConicalGradient() [3/3]
QConicalGradient::QConicalGradient (qreal cx, qreal cy, qreal angle)
Constructs a conical gradient with the given center (cx, cy), starting the interpolation at the given angle.
The angle must be specified in degrees between 0 and 360.
See also
QGradient::setColorAt(), QGradient::setStops()
Definition at line 2357 of file qbrush.cpp.
 {
     m_type = ConicalGradient;
     m_spread = PadSpread;
     m_data.conical.cx = cx;
     m_data.conical.cy = cy;
     m_data.conical.angle = angle;
 }
Functions
angle()
qreal QConicalGradient::angle () const
Returns the start angle of the conical gradient in logical coordinates.
See also
stops()
Definition at line 2433 of file qbrush.cpp.
Referenced by QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushUniforms(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     Q_ASSERT(m_type == ConicalGradient);
     return m_data.conical.angle;
 }
center()
QPointF QConicalGradient::center () const
Returns the center of the conical gradient in logical coordinates.
See also
stops()
Definition at line 2391 of file qbrush.cpp.
Referenced by QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushUniforms(), and QOpenGLPaintEnginePrivate::updateGradient().
 {
     Q_ASSERT(m_type == ConicalGradient);
     return QPointF(m_data.conical.cx, m_data.conical.cy);
 }
setAngle()
void QConicalGradient::setAngle (qreal angle)
Sets angle to be the start angle for this conical gradient in logical coordinates.
Since
4.2
See also
angle()
Definition at line 2452 of file qbrush.cpp.
 {
     Q_ASSERT(m_type == ConicalGradient);
     m_data.conical.angle = angle;
 }
setCenter() [1/2]
void QConicalGradient::setCenter (const QPointF & center)
Sets the center of this conical gradient in logical coordinates to center.
See also
center()
Definition at line 2419 of file qbrush.cpp.
 {
     Q_ASSERT(m_type == ConicalGradient);
     m_data.conical.cx = center.x();
     m_data.conical.cy = center.y();
 }
setCenter() [2/2]
void QConicalGradient::setCenter (qreal x, qreal y) inline
Sets the center of this conical gradient in logical coordinates to (x, y).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
center()
Definition at line 338 of file qbrush.h.
Referenced by setCenter().
 { setCenter(QPointF(x, y)); }
The documentation for this class was generated from the following files:
/src/gui/painting/qbrush.h
/src/gui/painting/qbrush.cpp