Qt 4.8: QEglFSScreen Class Reference
QEglFSScreen Class Reference
#include <qeglfsscreen.h>
Public Functions
int depth () const
Reimplement in subclass to return current depth of the screen.
QImage::Format format () const
Reimplement in subclass to return the image format which corresponds to the screen format.
QRect geometry () const
Reimplement in subclass to return the pixel geometry of the screen.
QPlatformGLContext * platformContext () const
QEglFSScreen (EGLNativeDisplayType display)
~QEglFSScreen ()
Public Functions inherited from QPlatformScreen
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
virtual QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
virtual void setDirty (const QRect &)
virtual QWidget * topLevelAt (const QPoint &point) const
Return the given top level widget for a given position.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
void createAndSetPlatformContext () const
void createAndSetPlatformContext ()
Properties
int m_depth
EGLDisplay m_dpy
QImage::Format m_format
QRect m_geometry
QPlatformGLContext * m_platformContext
EGLSurface m_surface
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QPlatformScreen
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 55 of file qeglfsscreen.h.
Constructors and Destructors
QEglFSScreen()
QEglFSScreen::QEglFSScreen (EGLNativeDisplayType display)
Definition at line 89 of file qeglfsscreen.cpp.
     : m_depth(32)
     , m_format(QImage::Format_Invalid)
     , m_platformContext(0)
     , m_surface(0)
 {
 #ifdef QEGL_EXTRA_DEBUG
     qWarning("QEglScreen %p\n", this);
 #endif
     EGLint major, minor;
 #ifdef QEGL_EXTRA_DEBUG
     EGLint index;
 #endif
     if (!eglBindAPI(EGL_OPENGL_ES_API)) {
         qWarning("Could not bind GL_ES API\n");
         qFatal("EGL error");
     }
     m_dpy = eglGetDisplay(display);
     if (m_dpy == EGL_NO_DISPLAY) {
         qWarning("Could not open egl display\n");
         qFatal("EGL error");
     }
     qWarning("Opened display %p\n", m_dpy);
     if (!eglInitialize(m_dpy, &major, &minor)) {
         qWarning("Could not initialize egl display\n");
         qFatal("EGL error");
     }
     qWarning("Initialized display %d %d\n", major, minor);
     int swapInterval = 1;
     QByteArray swapIntervalString = qgetenv("QT_QPA_EGLFS_SWAPINTERVAL");
     if (!swapIntervalString.isEmpty()) {
         bool ok;
         swapInterval = swapIntervalString.toInt(&ok);
         if (!ok)
             swapInterval = 1;
     }
     eglSwapInterval(m_dpy, swapInterval);
 }
~QEglFSScreen()
QEglFSScreen::~QEglFSScreen () inline
Definition at line 59 of file qeglfsscreen.h.
 {}
Functions
createAndSetPlatformContext() [1/2]
void QEglFSScreen::createAndSetPlatformContext () const private
Definition at line 133 of file qeglfsscreen.cpp.
Referenced by format(), geometry(), platformContext(), and ~QEglFSScreen().
{
     const_cast<QEglFSScreen *>(this)->createAndSetPlatformContext();
 }
createAndSetPlatformContext() [2/2]
void QEglFSScreen::createAndSetPlatformContext () private
Definition at line 137 of file qeglfsscreen.cpp.
 {
     QPlatformWindowFormat platformFormat = QPlatformWindowFormat::defaultFormat();
     platformFormat.setWindowApi(QPlatformWindowFormat::OpenGL);
     QByteArray depthString = qgetenv("QT_QPA_EGLFS_DEPTH");
     if (depthString.toInt() == 16) {
         platformFormat.setDepth(16);
         platformFormat.setRedBufferSize(5);
         platformFormat.setGreenBufferSize(6);
         platformFormat.setBlueBufferSize(5);
         m_depth = 16;
         m_format = QImage::Format_RGB16;
     } else {
         platformFormat.setDepth(32);
         platformFormat.setRedBufferSize(8);
         platformFormat.setGreenBufferSize(8);
         platformFormat.setBlueBufferSize(8);
         m_depth = 32;
         m_format = QImage::Format_RGB32;
     }
     if (!qgetenv("QT_QPA_EGLFS_MULTISAMPLE").isEmpty()) {
         platformFormat.setSampleBuffers(true);
     }
     EGLConfig config = q_configFromQPlatformWindowFormat(m_dpy, platformFormat);
     EGLNativeWindowType eglWindow = 0;
 #ifdef Q_OPENKODE
     if (kdInitializeNV() == KD_ENOTINITIALIZED) {
         qFatal("Did not manage to initialize openkode");
     }
     KDWindow *window = kdCreateWindow(m_dpy,config,0);
     kdRealizeWindow(window,&eglWindow);
 #endif
     m_surface = eglCreateWindowSurface(m_dpy, config, eglWindow, NULL);
     if (m_surface == EGL_NO_SURFACE) {
         qWarning("Could not create the egl surface: error = 0x%x\n", eglGetError());
         eglTerminate(m_dpy);
         qFatal("EGL error");
     }
     //    qWarning("Created surface %dx%d\n", w, h);
 #ifdef QEGL_EXTRA_DEBUG
     qWarning("Configuration %d matches requirements\n", (int)config);
     for (index = 0; attrs[index].attr != -1; ++index) {
         EGLint value;
         if (eglGetConfigAttrib(m_dpy, config, attrs[index].attr, &value)) {
             qWarning("\t%s: %d\n", attrs[index].name, (int)value);
         }
     }
     qWarning("\n");
 #endif
     EGLint temp;
     EGLint attribList[32];
     temp = 0;
     attribList[temp++] = EGL_CONTEXT_CLIENT_VERSION;
     attribList[temp++] = 2; // GLES version 2
     attribList[temp++] = EGL_NONE;
     QEGLPlatformContext *platformContext = new QEGLPlatformContext(m_dpy,config,attribList,m_surface,EGL_OPENGL_ES_API);
     m_platformContext = platformContext;
     EGLint w,h;                    // screen size detection
     eglQuerySurface(m_dpy, m_surface, EGL_WIDTH, &w);
     eglQuerySurface(m_dpy, m_surface, EGL_HEIGHT, &h);
     m_geometry = QRect(0,0,w,h);
 }
depth()
int QEglFSScreen::depth () const virtual
Reimplement in subclass to return current depth of the screen.
Implements QPlatformScreen.
Definition at line 224 of file qeglfsscreen.cpp.
Referenced by ~QEglFSScreen().
 {
     return m_depth;
 }
format()
QImage::Format QEglFSScreen::format () const virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implements QPlatformScreen.
Definition at line 229 of file qeglfsscreen.cpp.
Referenced by ~QEglFSScreen().
 {
     if (m_format == QImage::Format_Invalid)
         createAndSetPlatformContext();
     return m_format;
 }
geometry()
QRect QEglFSScreen::geometry () const virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implements QPlatformScreen.
Definition at line 216 of file qeglfsscreen.cpp.
Referenced by QEglFSPaintDevice::size(), and ~QEglFSScreen().
 {
     if (m_geometry.isNull()) {
         createAndSetPlatformContext();
     }
     return m_geometry;
 }
platformContext()
QPlatformGLContext * QEglFSScreen::platformContext () const
Definition at line 235 of file qeglfsscreen.cpp.
Referenced by QEglFSPaintDevice::context(), createAndSetPlatformContext(), QEglFSWindow::glContext(), and ~QEglFSScreen().
 {
     if (!m_platformContext) {
         QEglFSScreen *that = const_cast<QEglFSScreen *>(this);
         that->createAndSetPlatformContext();
     }
     return m_platformContext;
 }
Properties
m_depth
int QEglFSScreen::m_depth private
Definition at line 72 of file qeglfsscreen.h.
Referenced by createAndSetPlatformContext(), and depth().
m_dpy
EGLDisplay QEglFSScreen::m_dpy private
Definition at line 75 of file qeglfsscreen.h.
Referenced by createAndSetPlatformContext(), and QEglFSScreen().
m_format
QImage::Format QEglFSScreen::m_format private
Definition at line 73 of file qeglfsscreen.h.
Referenced by createAndSetPlatformContext(), and format().
m_geometry
QRect QEglFSScreen::m_geometry private
Definition at line 71 of file qeglfsscreen.h.
Referenced by createAndSetPlatformContext(), and geometry().
m_platformContext
QPlatformGLContext* QEglFSScreen::m_platformContext private
Definition at line 74 of file qeglfsscreen.h.
Referenced by createAndSetPlatformContext(), and platformContext().
m_surface
EGLSurface QEglFSScreen::m_surface private
Definition at line 76 of file qeglfsscreen.h.
Referenced by createAndSetPlatformContext().
The documentation for this class was generated from the following files:
/src/plugins/platforms/eglfs/qeglfsscreen.h
/src/plugins/platforms/eglfs/qeglfsscreen.cpp