Qt 4.8: QBBEngine Class Reference
QBBEngine Class Reference
#include <qbbengine.h>
Public Functions
QNetworkConfigurationManager::Capabilities capabilities () const
void connectToId (const QString &id)
QNetworkSessionPrivate * createSessionBackend ()
QNetworkConfigurationPrivatePointer defaultConfiguration ()
void disconnectFromId (const QString &id)
QString getInterfaceFromId (const QString &id)
bool hasIdentifier (const QString &id)
Q_INVOKABLE void initialize ()
QBBEngine (QObject *parent=0)
Q_INVOKABLE void requestUpdate ()
bool requiresPolling () const
QNetworkSession::State sessionStateForId (const QString &id)
~QBBEngine ()
Public Functions inherited from QBearerEngineImpl
virtual quint64 bytesReceived (const QString &)
virtual quint64 bytesWritten (const QString &)
QBearerEngineImpl (QObject *parent=0)
virtual quint64 startTime (const QString &)
~QBearerEngineImpl ()
Public Functions inherited from QBearerEngine
bool configurationsInUse () const
QBearerEngine (QObject *parent=0)
virtual ~QBearerEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void removeConfiguration (const QString &id)
void updateConfiguration (const char *interface)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void doRequestUpdate ()
Private Functions
void filterEvent (bps_event_t *event)
Static Private Functions
static bool filterEvent (void *message)
Properties
QHash< QString, QString > configurationInterface
bool initialized
QMutex pollingMutex
bool pollingRequired
QAbstractEventDispatcher::EventFilter previousEventFilter
Additional Inherited Members
Public Types inherited from QBearerEngineImpl
enum ConnectionError { InterfaceLookupError = 0, ConnectError, OperationNotSupported, DisconnectionError }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QBearerEngineImpl
void connectionError (const QString &id, QBearerEngineImpl::ConnectionError error)
Signals inherited from QBearerEngine
void configurationAdded (QNetworkConfigurationPrivatePointer config)
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void configurationRemoved (QNetworkConfigurationPrivatePointer config)
void updateCompleted ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QBearerEngine
QHash< QString, QNetworkConfigurationPrivatePointer > accessPointConfigurations
QMutex mutex
QHash< QString, QNetworkConfigurationPrivatePointer > snapConfigurations
QHash< QString, QNetworkConfigurationPrivatePointer > userChoiceConfigurations
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 58 of file qbbengine.h.
Constructors and Destructors
QBBEngine()
QBBEngine::QBBEngine (QObject * parent = 0) explicit
Definition at line 124 of file qbbengine.cpp.
                                     :
     QBearerEngineImpl(parent),
     previousEventFilter(0),
     pollingRequired(false),
     initialized(false)
 {
 }
~QBBEngine()
QBBEngine::~QBBEngine ()
Definition at line 132 of file qbbengine.cpp.
 {
     QAbstractEventDispatcher::instance()->setEventFilter(previousEventFilter);
 }
Functions
capabilities()
QNetworkConfigurationManager::Capabilities QBBEngine::capabilities () const virtual
Implements QBearerEngine.
Definition at line 250 of file qbbengine.cpp.
 {
     return QNetworkConfigurationManager::ForcedRoaming;
 }
connectToId()
void QBBEngine::connectToId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 152 of file qbbengine.cpp.
 {
     Q_EMIT connectionError(id, OperationNotSupported);
 }
createSessionBackend()
QNetworkSessionPrivate * QBBEngine::createSessionBackend () virtual
Implements QBearerEngine.
Definition at line 255 of file qbbengine.cpp.
 {
     return new QNetworkSessionPrivateImpl;
 }
defaultConfiguration()
QNetworkConfigurationPrivatePointer QBBEngine::defaultConfiguration () virtual
Implements QBearerEngine.
Definition at line 260 of file qbbengine.cpp.
 {
     char *interface = 0;
     if (netstatus_get_default_interface(&interface) != BPS_SUCCESS)
         return QNetworkConfigurationPrivatePointer();
     if (!interface)
         return QNetworkConfigurationPrivatePointer();
     const QScopedPointer<char, NetstatusInterfaceCleanupHelper> holder(interface);
     const QString id = idForName(QString::fromLatin1(interface));
     const QMutexLocker locker(&mutex);
     if (accessPointConfigurations.contains(id)) {
         qBearerDebug() << Q_FUNC_INFO << "found default interface:" << id;
         return accessPointConfigurations.value(id);
     }
     return QNetworkConfigurationPrivatePointer();
 }
disconnectFromId()
void QBBEngine::disconnectFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 157 of file qbbengine.cpp.
 {
     Q_EMIT connectionError(id, OperationNotSupported);
 }
doRequestUpdate
void QBBEngine::doRequestUpdate () private slot
Definition at line 189 of file qbbengine.cpp.
Referenced by filterEvent(), initialize(), requestUpdate(), and updateConfiguration().
 {
     qBearerDebug() << Q_FUNC_INFO << "entered method";
     netstatus_interface_list_t interfaceList;
     if ((netstatus_get_interfaces(&interfaceList)) != BPS_SUCCESS) {
         qBearerDebug() << Q_FUNC_INFO << "cannot retrieve interface list";
         return;
     }
     const QScopedPointer<netstatus_interface_list_t,
           NetstatusInterfaceListCleanupHelper> holder(&interfaceList);
     QSet<QString> currentConfigurations;
     for (int i = 0; i < interfaceList.num_interfaces; i++) {
         const char *interface = interfaceList.interfaces[i];
         qBearerDebug() << Q_FUNC_INFO << "discovered interface" << interface;
         updateConfiguration(interface);
         currentConfigurations << idForName(QString::fromLatin1(interface));
     }
     QMutexLocker locker(&mutex);
     const QStringList keys = accessPointConfigurations.uniqueKeys();
     locker.unlock();
     Q_FOREACH (const QString &id, keys) {
         if (!currentConfigurations.contains(id))
             removeConfiguration(id);
     }
     Q_EMIT updateCompleted();
 }
filterEvent() [1/2]
bool QBBEngine::filterEvent (void * message) static private
Definition at line 292 of file qbbengine.cpp.
Referenced by initialize().
 {
     bps_event_t * const event = static_cast<bps_event_t *>(message);
     Q_ASSERT(event);
     QBBEngine *self = instanceStorage()->localData()->instance;
     Q_ASSERT(self);
     if (bps_event_get_domain(event) == netstatus_get_domain())
         self->filterEvent(event);
     if (self->previousEventFilter)
         return self->previousEventFilter(message);
     return false;
 }
filterEvent() [2/2]
void QBBEngine::filterEvent (bps_event_t * event) private
Definition at line 311 of file qbbengine.cpp.
 {
     Q_UNUSED(event);
     qBearerDebug() << Q_FUNC_INFO << "got update request.";
     doRequestUpdate();
 }
getInterfaceFromId()
QString QBBEngine::getInterfaceFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 138 of file qbbengine.cpp.
 {
     const QMutexLocker locker(&mutex);
     return configurationInterface.value(id);
 }
hasIdentifier()
bool QBBEngine::hasIdentifier (const QString & id) virtual
Implements QBearerEngine.
Definition at line 145 of file qbbengine.cpp.
 {
     const QMutexLocker locker(&mutex);
     return configurationInterface.contains(id);
 }
initialize()
void QBBEngine::initialize ()
Definition at line 162 of file qbbengine.cpp.
 {
     if (initialized) {
         qWarning() << Q_FUNC_INFO << "called, but instance already initialized.";
         return;
     }
     instanceStorage()->setLocalData(new EngineInstanceHolder(this));
     if (netstatus_request_events(0) != BPS_SUCCESS) {
         qWarning() << Q_FUNC_INFO << "cannot register for network events. Polling enabled.";
         const QMutexLocker locker(&pollingMutex);
         pollingRequired = true;
     } else {
         previousEventFilter =
             QAbstractEventDispatcher::instance()->setEventFilter(filterEvent);
     }
     doRequestUpdate();
 }
removeConfiguration()
void QBBEngine::removeConfiguration (const QString & id) protected
Definition at line 420 of file qbbengine.cpp.
Referenced by doRequestUpdate().
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr =
         accessPointConfigurations.take(id);
     configurationInterface.remove(ptr->id);
     locker.unlock();
     Q_EMIT configurationRemoved(ptr);
 }
requestUpdate()
void QBBEngine::requestUpdate ()
Definition at line 184 of file qbbengine.cpp.
 {
     doRequestUpdate();
 }
requiresPolling()
bool QBBEngine::requiresPolling () const virtual
Reimplemented from QBearerEngine.
Definition at line 285 of file qbbengine.cpp.
 {
     const QMutexLocker locker(&pollingMutex);
     return pollingRequired;
 }
sessionStateForId()
QNetworkSession::State QBBEngine::sessionStateForId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 229 of file qbbengine.cpp.
 {
     const QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (!ptr || !ptr->isValid)
         return QNetworkSession::Invalid;
     if ((ptr->state & QNetworkConfiguration::Active) == QNetworkConfiguration::Active)
         return QNetworkSession::Connected;
     else if ((ptr->state & QNetworkConfiguration::Discovered) == QNetworkConfiguration::Discovered)
         return QNetworkSession::Disconnected;
     else if ((ptr->state & QNetworkConfiguration::Defined) == QNetworkConfiguration::Defined)
         return QNetworkSession::NotAvailable;
     else if ((ptr->state & QNetworkConfiguration::Undefined) == QNetworkConfiguration::Undefined)
         return QNetworkSession::NotAvailable;
     return QNetworkSession::Invalid;
 }
updateConfiguration()
void QBBEngine::updateConfiguration (const char * interface) protected
Definition at line 320 of file qbbengine.cpp.
Referenced by doRequestUpdate().
 {
     netstatus_interface_details_t *details = 0;
     if (netstatus_get_interface_details(interface, &details) != BPS_SUCCESS) {
         qBearerDebug() << Q_FUNC_INFO << "cannot retrieve details for interface" << interface;
         return;
     }
     const QString name = QString::fromLatin1(netstatus_interface_get_name(details));
     const QString id = idForName(name);
     const netstatus_interface_type_t type = netstatus_interface_get_type(details);
     const netstatus_ip_status_t ipStatus = netstatus_interface_get_ip_status(details);
     netstatus_free_interface_details(&details);
     QNetworkConfiguration::StateFlags state = QNetworkConfiguration::Defined;
     if (ipStatus == NETSTATUS_IP_STATUS_OK)
         state |= QNetworkConfiguration::Active;
     QMutexLocker locker(&mutex);
     if (accessPointConfigurations.contains(id)) {
         QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
         bool changed = false;
         QMutexLocker ptrLocker(&ptr->mutex);
         if (!ptr->isValid) {
             ptr->isValid = true;
             changed = true;
         }
         if (ptr->name != name) {
             ptr->name = name;
             changed = true;
         }
         if (ptr->id != id) {
             ptr->id = id;
             changed = true;
         }
         if (ptr->state != state) {
             ptr->state = state;
             changed = true;
         }
         const netstatus_ip_status_t oldIpStatus = ptr->oldIpStatus;
         ptr->oldIpStatus = ipStatus;
         ptrLocker.unlock();
         locker.unlock();
         if (changed) {
             qBearerDebug() << Q_FUNC_INFO << "configuration changed:" << interface;
             Q_EMIT configurationChanged(ptr);
         } else {
             // maybe Wifi has changed but gateway not yet ready etc.
             qBearerDebug() << Q_FUNC_INFO << "configuration has not changed.";
             if (oldIpStatus != ipStatus) { // if IP status changed
                 if (ipStatus != NETSTATUS_IP_STATUS_OK
                         && ipStatus != NETSTATUS_IP_STATUS_ERROR_NOT_UP
                         && ipStatus != NETSTATUS_IP_STATUS_ERROR_NOT_CONFIGURED) {
                     // work around race condition in netstatus API by just checking
                     // again in 300 ms
                     QTimer::singleShot(300, this, SLOT(doRequestUpdate()));
                 }
             }
         }
         return;
     }
     QNetworkConfigurationPrivatePointer ptr(new QNetworkConfigurationPrivate);
     ptr->name = name;
     ptr->isValid = true;
     ptr->id = id;
     ptr->state = state;
     ptr->type = QNetworkConfiguration::InternetAccessPoint;
     ptr->bearerType = interfaceType(type);
     accessPointConfigurations.insert(id, ptr);
     configurationInterface.insert(id, name);
     locker.unlock();
     qBearerDebug() << Q_FUNC_INFO << "configuration added:" << interface;
     Q_EMIT configurationAdded(ptr);
 }
Properties
configurationInterface
QHash<QString, QString> QBBEngine::configurationInterface private
Definition at line 97 of file qbbengine.h.
Referenced by getInterfaceFromId(), hasIdentifier(), removeConfiguration(), and updateConfiguration().
initialized
bool QBBEngine::initialized private
Definition at line 104 of file qbbengine.h.
Referenced by initialize().
pollingMutex
QMutex QBBEngine::pollingMutex mutable private
Definition at line 101 of file qbbengine.h.
Referenced by initialize(), and requiresPolling().
pollingRequired
bool QBBEngine::pollingRequired private
Definition at line 103 of file qbbengine.h.
Referenced by initialize(), and requiresPolling().
previousEventFilter
QAbstractEventDispatcher::EventFilter QBBEngine::previousEventFilter private
Definition at line 99 of file qbbengine.h.
Referenced by initialize(), and ~QBBEngine().
The documentation for this class was generated from the following files:
/src/plugins/bearer/blackberry/qbbengine.h
/src/plugins/bearer/blackberry/qbbengine.cpp