Qt 4.8: QDeclarativeBindingCompiler Class Reference
QDeclarativeBindingCompiler Class Reference
#include <qdeclarativecompiledbindings_p.h>
Classes
struct Expression
Public Functions
int compile (const Expression &, QDeclarativeEnginePrivate *)
bool isValid () const
QByteArray program () const
QDeclarativeBindingCompiler ()
~QDeclarativeBindingCompiler ()
Static Public Functions
static void dump (const QByteArray &)
Properties
QDeclarativeBindingCompilerPrivate * d
Detailed Description
Definition at line 64 of file qdeclarativecompiledbindings_p.h.
Constructors and Destructors
QDeclarativeBindingCompiler()
QDeclarativeBindingCompiler::QDeclarativeBindingCompiler ()
Definition at line 2837 of file qdeclarativecompiledbindings.cpp.
 : d(new QDeclarativeBindingCompilerPrivate)
 {
 }
~QDeclarativeBindingCompiler()
QDeclarativeBindingCompiler::~QDeclarativeBindingCompiler ()
Definition at line 2842 of file qdeclarativecompiledbindings.cpp.
 {
     delete d; d = 0;
 }
Functions
compile()
int QDeclarativeBindingCompiler::compile (const Expression & expression, QDeclarativeEnginePrivate * engine)
Definition at line 2858 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiler::completeComponentBuild().
 {
     if (!expression.expression.asAST()) return false;
     if (!qmlExperimental() && expression.property->isValueTypeSubProperty)
         return -1;
     if (qmlDisableOptimizer())
         return -1;
     d->context = expression.context;
     d->component = expression.component;
     d->destination = expression.property;
     d->ids = expression.ids;
     d->imports = expression.imports;
     d->engine = engine;
     if (d->compile(expression.expression.asAST())) {
         return d->commitCompile();
     } else {
         return -1;
     }
 }
dump()
void QDeclarativeBindingCompiler::dump (const QByteArray & programData) static
Definition at line 1695 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiler::completeComponentBuild().
 {
     const Program *program = (const Program *)programData.constData();
     qWarning() << "Program.bindings:" << program->bindings;
     qWarning() << "Program.dataLength:" << program->dataLength;
     qWarning() << "Program.subscriptions:" << program->subscriptions;
     qWarning() << "Program.indentifiers:" << program->identifiers;
     int count = program->instructionCount;
     const Instr *instr = program->instructions();
     while (count--) {
         dumpInstruction(instr);
         ++instr;
     }
 }
isValid()
bool QDeclarativeBindingCompiler::isValid () const
Definition at line 2850 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiler::completeComponentBuild(), and program().
 {
     return !d->committed.bytecode.isEmpty();
 }
program()
QByteArray QDeclarativeBindingCompiler::program () const
Definition at line 2918 of file qdeclarativecompiledbindings.cpp.
Referenced by QDeclarativeCompiler::completeComponentBuild().
 {
     QByteArray programData;
     if (isValid()) {
         Program prog;
         prog.bindings = d->committed.count();
         QVector<Instr> bytecode;
         Instr skip;
         skip.common.type = Instr::Skip;
         skip.skip.reg = -1;
         for (int ii = 0; ii < d->committed.count(); ++ii) {
             skip.skip.count = d->committed.count() - ii - 1;
             skip.skip.count+= d->committed.offsets.at(ii);
             bytecode << skip;
         }
         bytecode << d->committed.bytecode;
         QByteArray data = d->committed.data;
         while (data.count() % 4) data.append('\0');
         prog.signalTableOffset = data.count();
         data += d->buildSignalTable();
         while (data.count() % 4) data.append('\0');
         prog.exceptionDataOffset = data.count();
         data += d->buildExceptionData();
         prog.dataLength = 4 * ((data.size() + 3) / 4);
         prog.subscriptions = d->committed.subscriptionIds.count();
         prog.identifiers = d->committed.registeredStrings.count();
         prog.instructionCount = bytecode.count();
         prog.compiled = false;
         int size = sizeof(Program) + bytecode.count() * sizeof(Instr);
         size += prog.dataLength;
         programData.resize(size);
         memcpy(programData.data(), &prog, sizeof(Program));
         if (prog.dataLength)
             memcpy((char *)((Program *)programData.data())->data(), data.constData(),
                    data.size());
         memcpy((char *)((Program *)programData.data())->instructions(), bytecode.constData(),
                bytecode.count() * sizeof(Instr));
     }
     return programData;
 }
Properties
d
QDeclarativeBindingCompilerPrivate* QDeclarativeBindingCompiler::d private
Definition at line 91 of file qdeclarativecompiledbindings_p.h.
Referenced by compile(), isValid(), program(), and ~QDeclarativeBindingCompiler().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecompiledbindings_p.h
/src/declarative/qml/qdeclarativecompiledbindings.cpp