Qt 4.8: QScreen Class Reference
QScreen Class Reference abstract
The QScreen class is a base class for screen drivers in Qt for Embedded Linux.
#include <qscreen_qws.h>
Public Types
enum ClassId {
LinuxFBClass, TransformedClass, VNCClass, MultiClass,
VFbClass, DirectFBClass, SvgalibClass, ProxyClass,
GLClass, IntfbClass, CustomClass = 1024
}
This enum defines the class identifiers for the known screen subclasses.
enum PixelType { NormalPixel, BGRPixel }
This enum describes the pixel storage format of the screen, i.
Public Functions
virtual int alloc (unsigned int, unsigned int, unsigned int)
Returns the index in the screen's palette which is the closest match to the given RGB value (red, green, blue).
uchar * base () const
Returns a pointer to the beginning of the framebuffer.
virtual void blank (bool on)
Prevents the screen driver form displaying any content on the screen.
virtual void blit (const QImage &img, const QPoint &topLeft, const QRegion &region)
Copies the given region in the given image to the point specified by topLeft using device coordinates.
void blit (QWSWindow *bs, const QRegion &clip)
virtual uchar * cache (int)
ClassId classId () const
Returns the class identifier for the screen object.
QRgb * clut ()
Returns a pointer to the screen's color lookup table (i.
int colorCount ()
Returns the number of entries in the screen's color lookup table (i.
virtual bool connect (const QString &displaySpec)=0
This function is called by every Qt for Embedded Linux application on startup, and must be implemented to map in the framebuffer and the accelerated drivers that the graphics card control registers.
virtual QWSWindowSurface * createSurface (QWidget *widget) const
Creates and returns a new window surface for the given widget.
virtual QWSWindowSurface * createSurface (const QString &key) const
Creates and returns a new window surface matching the given key.
int depth () const
Returns the depth of the framebuffer, in bits per pixel.
int deviceHeight () const
Returns the full height of the framebuffer device in pixels.
int deviceWidth () const
Returns the physical width of the framebuffer device in pixels.
virtual void disconnect ()=0
This function is called by every Qt for Embedded Linux application before exiting, and must be implemented to unmap the framebuffer.
virtual void exposeRegion (QRegion r, int changing)
This function is called by the Qt for Embedded Linux server whenever a screen update is required.
QGraphicsSystem * graphicsSystem () const
virtual void haltUpdates ()
int height () const
Returns the logical height of the framebuffer in pixels.
virtual bool initDevice ()=0
This function is called by the Qt for Embedded Linux server to initialize the framebuffer.
virtual bool isInterlaced () const
Returns true if the display is interlaced (i.
virtual bool isTransformed () const
Returns true if the screen is transformed (for instance, rotated 90 degrees); otherwise returns false.
int linestep () const
Returns the length of each scanline of the framebuffer in bytes.
virtual QSize mapFromDevice (const QSize &) const
Maps the given size from the framebuffer coordinate system to the coordinate space used by the application.
virtual QPoint mapFromDevice (const QPoint &, const QSize &) const
Maps the given point from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QRect mapFromDevice (const QRect &, const QSize &) const
Maps the given rectangle from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QImage mapFromDevice (const QImage &) const
Maps the given image from the framebuffer coordinate system to the coordinate space used by the application.
virtual QRegion mapFromDevice (const QRegion &, const QSize &) const
Maps the given region from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QSize mapToDevice (const QSize &) const
Maps the given size from the coordinate space used by the application to the framebuffer coordinate system.
virtual QPoint mapToDevice (const QPoint &, const QSize &) const
Maps the given point from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual QRect mapToDevice (const QRect &, const QSize &) const
Maps the given rectangle from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual QImage mapToDevice (const QImage &) const
Maps the given image from the coordinate space used by the application to the framebuffer coordinate system.
virtual QRegion mapToDevice (const QRegion &, const QSize &) const
Maps the given region from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual int memoryNeeded (const QString &)
QT_DEPRECATED int numCols ()
QPoint offset () const
Returns the logical offset of the screen, i.
virtual bool onCard (const unsigned char *) const
Returns true if the specified buffer is within the graphics card's memory; otherwise returns false (i.e.
virtual bool onCard (const unsigned char *, ulong &out_offset) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.If the specified buffer is within the graphics card's memory, this function stores the offset from the start of graphics card memory (in bytes), in the location specified by the offset parameter.
int physicalHeight () const
Returns the physical height of the screen in millimeters.
int physicalWidth () const
Returns the physical width of the screen in millimeters.
QImage::Format pixelFormat () const
Returns the pixel format of the screen, or QImage::Format_Invalid if the pixel format is not a supported image format.
PixelType pixelType () const
Returns the pixel storage format of the screen.
QPixmapDataFactory * pixmapDataFactory () const
virtual int pixmapDepth () const
Returns the preferred depth for pixmaps, in bits per pixel.
virtual int pixmapLinestepAlignment ()
Returns the value (in bits) to which individual scanlines of pixmaps held in the graphics card's memory, should be aligned.
virtual int pixmapOffsetAlignment ()
Returns the value (in bits) to which the start address of pixmaps held in the graphics card's memory, should be aligned.
QScreen (int display_id, ClassId classId)
Constructs a new screen driver.
QScreen (int display_id)
Constructs a new screen driver.
virtual QRegion region () const
Returns the region covered by this screen driver.
virtual void restore ()
Restores the previously saved state of the graphics card.
virtual void resumeUpdates ()
virtual void save ()
Saves the current state of the graphics card.
int screenSize () const
Returns the size of the screen in bytes.
virtual void set (unsigned int, unsigned int, unsigned int, unsigned int)
virtual void setDirty (const QRect &)
Marks the given rectangle as dirty.
virtual void setMode (int, int, int)=0
Implement this function to reset the framebuffer's resolution (width and height) and bit depth.
void setOffset (const QPoint &p)
virtual int sharedRamSize (void *)
virtual void shutdownDevice ()
This function is called by the Qt for Embedded Linux server before it calls the disconnect() function when exiting.
virtual void solidFill (const QColor &color, const QRegion &region)
Fills the given region of the screen with the specified color.
int subScreenIndexAt (const QPoint &p) const
Returns the index of the subscreen at the given position; returns -1 if no screen is found.
virtual QList< QScreen * > subScreens () const
virtual bool supportsDepth (int) const
Returns true if the screen supports the specified color depth; otherwise returns false.
int totalSize () const
Returns the size of the available graphics card memory (including the screen) in bytes.
virtual int transformOrientation () const
Returns the current rotation as an integer value.
virtual void uncache (uchar *)
int width () const
Returns the logical width of the framebuffer in pixels.
virtual ~QScreen ()
Destroys this screen driver.
Static Public Functions
static QScreen * instance ()
Returns a pointer to the application's QScreen instance.
Protected Functions
void setGraphicsSystem (QGraphicsSystem *system)
void setPixelFormat (QImage::Format format)
Sets the screen's pixel format to format.
void setPixmapDataFactory (QPixmapDataFactory *factory)
Protected Variables
int d
the pixel depth
uchar * data
points to the first visible pixel in the frame buffer.
int dh
the device height
int displayId
int dw
the device width
QPoolEntry * entries
int * entryp
bool grayscale
the gray scale screen mode flag
int h
the logical height of the screen.
unsigned int * lowest
int lstep
the number of bytes representing a line in the frame buffer.
int mapsize
the total number of bytes in the frame buffer
int physHeight
the physical height of the screen in millimeters.
int physWidth
the physical width of the screen in millimeters.
PixelType pixeltype
set to BGRPixel
QRgb screenclut [256]
the color table
int screencols
the number of entries in the color table
int size
the number of bytes in the visible region of the frame buffer
int w
the logical width of the screen.
Static Protected Variables
static ClearCacheFunc clearCacheFunc = 0
Private Functions
void compose (int level, const QRegion &exposed, QRegion &blend, QImage **blendbuffer, int changing_level)
bool frameBufferLittleEndian () const
void paintBackground (const QRegion &)
void setFrameBufferLittleEndian (bool littleEndian)
Static Private Functions
static bool isWidgetPaintOnScreen (const QWidget *w)
Properties
QScreenPrivate * d_ptr
Friends
class QIntfbScreen
class QLinuxFbScreen
class QProxyScreen
class QQnxScreen
void qt_blit_setup (QScreen *screen, const QImage &image, const QPoint &topLeft, const QRegion &region)
void qt_solidFill_setup (QScreen *, const QColor &, const QRegion &)
class QVFbScreen
class QVNCScreen
class QWSOnScreenSurface
class QWSServer
class QWSServerPrivate
Related Functions
(Note that these are not member functions.)
void setTransformation (int transformation, int screenNo)
Here it is.
Detailed Description
The QScreen class is a base class for screen drivers in Qt for Embedded Linux.
Note that this class is only available in Qt for Embedded Linux.
Qt for Embedded Linux provides ready-made drivers for several screen protocols, see the Qt for Embedded Linux Display Management{display management} documentation for details. Custom screen drivers can be implemented by subclassing the QScreen class and creating a screen driver plugin (derived from QScreenDriverPlugin). The default implementation of the QScreenDriverFactory class will automatically detect the plugin, and load the driver into the server application at run-time using Qt's How to Create Qt Plugins.
When rendering, the default behavior is for each client to render its widgets as well as its decorations into memory, while the server copies the memory content to the device's framebuffer using the screen driver. See the Qt for Embedded Linux Architecture overview for details (note that it is possible for the clients to manipulate and control the underlying hardware directly as well).
Starting with Qt 4.2, it is also possible to add an accelerated graphics driver to take advantage of available hardware resources. See the Adding an Accelerated Graphics Driver to Qt for Embedded Linux documentation for details.
Framebuffer Management
When a Qt for Embedded Linux application starts running, it calls the screen driver's connect() function to map the framebuffer and the accelerated drivers that the graphics card control registers. The connect() function should then read out the parameters of the framebuffer and use them as required to set this class's protected variables.
The initDevice() function can be reimplemented to initialize the graphics card. Note, however, that connect() is called before the initDevice() function, so, for some hardware configurations, some of the initialization that would normally be done in the initDevice() function might have to be done in the connect() function.
Likewise, just before a Qt for Embedded Linux application exits, it calls the screen driver's disconnect() function. The server application will in addition call the shutdownDevice() function before it calls disconnect(). Note that the default implementation of the shutdownDevice() function only hides the mouse cursor.
QScreen also provides the save() and restore() functions, making it possible to save and restore the state of the graphics card. Note that the default implementations do nothing. Hardware screen drivers should reimplement these functions to save (and restore) its registers, enabling switching between virtual consoles.
In addition, you can use the base() function to retrieve a pointer to the beginning of the framebuffer, and the region() function to retrieve the framebuffer's region. Use the onCard() function to determine whether the framebuffer is within the graphics card's memory, and the totalSize() function to determine the size of the available graphics card memory (including the screen). Finally, you can use the offset() function to retrieve the offset between the framebuffer's coordinates and the application's coordinate system.
Palette Management
QScreen provides several functions to retrieve information about the color palette: The clut() function returns a pointer to the color lookup table (i.e. its color palette). Use the colorCount() function to determine the number of entries in this table, and the alloc() function to retrieve the palette index of the color that is the closest match to a given RGB value.
To determine if the screen driver supports a given color depth, use the supportsDepth() function that returns true of the specified depth is supported.
Drawing on Screen
When a screen update is required, the Qt for Embedded Linux server runs through all the top-level windows that intersect with the region that is about to be updated, and ensures that the associated clients have updated their memory buffer. Then the server calls the exposeRegion() function that composes the window surfaces and copies the content of memory to screen by calling the blit() and solidFill() functions.
The blit() function copies a given region in a given image to a specified point using device coordinates, while the solidFill() function fills the given region of the screen with the specified color. Note that normally there is no need to call either of these functions explicitly.
In addition, QScreen provides the blank() function that can be reimplemented to prevent any contents from being displayed on the screen, and the setDirty() function that can be reimplemented to indicate that a given rectangle of the screen has been altered. Note that the default implementations of these functions do nothing.
Reimplement the mapFromDevice() and mapToDevice() functions to map objects from the framebuffer coordinate system to the coordinate space used by the application, and vice versa. Be aware that the default implementations simply return the given objects as they are.
Properties
Property Functions
Size
The size of the screen can be retrieved using the screenSize() function. The size is returned in bytes.
The framebuffer's logical width and height can be retrieved using width() and height(), respectively. These functions return values are given in pixels. Alternatively, the physicalWidth() and physicalHeight() function returns the same metrics in millimeters. QScreen also provides the deviceWidth() and deviceHeight() functions returning the physical width and height of the device in pixels. Note that the latter metrics can differ from the ones used if the display is centered within the framebuffer.
Resolution
Reimplement the setMode() function to be able to set the framebuffer to a new resolution (width and height) and bit depth.
The current depth of the framebuffer can be always be retrieved using the depth() function. Use the pixmapDepth() function to obtain the preferred depth for pixmaps.
Pixmap Alignment
Use the pixmapOffsetAlignment() function to retrieve the value to which the start address of pixmaps held in the graphics card's memory, should be aligned.
Use the pixmapLinestepAlignment() to retrieve the value to which the {individual scanlines} of pixmaps should be aligned.
Image Display
The isInterlaced() function tells whether the screen is displaying images progressively, and the isTransformed() function whether it is rotated. The transformOrientation() function can be reimplemented to return the current rotation.
Scanlines
Use the linestep() function to retrieve the length of each scanline of the framebuffer.
Pixel Type
The pixelType() function returns the screen's pixel storage format as described by the PixelType enum.
Subclassing and Initial Values
You need to set the following members when implementing a subclass of QScreen:
Member Initial Value
QScreen::data A pointer to the framebuffer if possible; 0 otherwise.
QScreen::lstep The number of bytes between each scanline in the framebuffer.
QScreen::w The logical screen width in pixels.
QScreen::h The logical screen height in pixels.
QScreen::dw The real screen width in pixels.
QScreen::dh The real screen height in pixels.
QScreen::d The number of bits per pixel.
QScreen::physWidth The screen width in millimeters.
QScreen::physHeight The screen height in millimeters.
The logical screen values are the same as the real screen values unless the screen is transformed in some way; e.g., rotated.
See also the Accelerated Graphics Driver Example for an example that shows how to initialize these values.
See also
QScreenDriverPlugin, QScreenDriverFactory, {Qt for Embedded Linux Display Management}
Definition at line 191 of file qscreen_qws.h.
Enumerations
ClassId
enum QScreen::ClassId
This enum defines the class identifiers for the known screen subclasses.
LinuxFBClass QLinuxFBScreen
TransformedClass QTransformedScreen
VNCClass QVNCScreen
MultiClass QMultiScreen
VFbClass QVFbScreen
DirectFBClass QDirectFBScreen
SvgalibClass QSvgalibScreen
ProxyClass QProxyScreen
GLClass QGLScreen
IntfbClass QIntfbScreen
CustomClass Unknown QScreen subclass
See also
classId()
Enumerator
LinuxFBClass
TransformedClass
VNCClass
MultiClass
VFbClass
DirectFBClass
SvgalibClass
ProxyClass
GLClass
IntfbClass
CustomClass
Definition at line 194 of file qscreen_qws.h.
                  { LinuxFBClass, TransformedClass, VNCClass, MultiClass,
                    VFbClass, DirectFBClass, SvgalibClass, ProxyClass,
                    GLClass, IntfbClass, CustomClass = 1024 };
PixelType
enum QScreen::PixelType
This enum describes the pixel storage format of the screen, i.
e. the order of the red (R), green (G) and blue (B) components of a pixel.
NormalPixel Red-green-blue (RGB)
BGRPixel Blue-green-red (BGR)
See also
pixelType()
Enumerator
NormalPixel
BGRPixel
Definition at line 220 of file qscreen_qws.h.
 { NormalPixel, BGRPixel };
Constructors and Destructors
QScreen() [1/2]
QScreen::QScreen (int display_id, ClassId classId)
Constructs a new screen driver.
Since
4.4
The display_id identifies the Qt for Embedded Linux server to connect to. The classId specifies the class identifier.
Definition at line 2163 of file qscreen_qws.cpp.
     : screencols(0), data(0), entries(0), entryp(0), lowest(0),
       w(0), lstep(0), h(0), d(1), pixeltype(NormalPixel), grayscale(false),
       dw(0), dh(0), size(0), mapsize(0), displayId(display_id),
       physWidth(0), physHeight(0), d_ptr(new QScreenPrivate(this, classId))
 {
     clearCacheFunc = 0;
 }
QScreen() [2/2]
QScreen::QScreen (int displayId) explicit
Constructs a new screen driver.
The displayId identifies the Qt for Embedded Linux server to connect to.
Definition at line 2172 of file qscreen_qws.cpp.
     : screencols(0), data(0), entries(0), entryp(0), lowest(0),
       w(0), lstep(0), h(0), d(1), pixeltype(NormalPixel), grayscale(false),
       dw(0), dh(0), size(0), mapsize(0), displayId(display_id),
       physWidth(0), physHeight(0), d_ptr(new QScreenPrivate(this))
 {
     clearCacheFunc = 0;
 }
~QScreen()
QScreen::~QScreen () virtual
Destroys this screen driver.
Definition at line 2185 of file qscreen_qws.cpp.
 {
     delete d_ptr;
 }
Functions
alloc()
int QScreen::alloc (unsigned int red, unsigned int green, unsigned int blue) virtual
Returns the index in the screen's palette which is the closest match to the given RGB value (red, green, blue).
Note that this function only apply in paletted modes like 8-bit, i.e. in modes where only the palette indexes (and not the actual color values) are stored in memory.
See also
clut(), colorCount()
Definition at line 2255 of file qscreen_qws.cpp.
 {
     int ret = 0;
     if (d == 8) {
         if (grayscale)
             return qGray(r, g, b);
         // First we look to see if we match a default color
         const int pos = (r + 25) / 51 * 36 + (g + 25) / 51 * 6 + (b + 25) / 51;
         if (pos < screencols && screenclut[pos] == qRgb(r, g, b)) {
             return pos;
         }
         // search for nearest color
         unsigned int mindiff = 0xffffffff;
         unsigned int diff;
         int dr,dg,db;
         for (int loopc = 0; loopc < screencols; ++loopc) {
             dr = qRed(screenclut[loopc]) - r;
             dg = qGreen(screenclut[loopc]) - g;
             db = qBlue(screenclut[loopc]) - b;
             diff = dr*dr + dg*dg + db*db;
             if (diff < mindiff) {
                 ret = loopc;
                 if (!diff)
                     break;
                 mindiff = diff;
             }
         }
     } else if (d == 4) {
         ret = qGray(r, g, b) >> 4;
     } else if (d == 1) {
         ret = qGray(r, g, b) >= 128;
     } else {
         qFatal("cannot alloc %dbpp color", d);
     }
     return ret;
 }
base()
uchar * QScreen::base () const inline
Returns a pointer to the beginning of the framebuffer.
See also
onCard(), region(), totalSize()
Definition at line 235 of file qscreen_qws.h.
Referenced by QWSOnScreenSurface::attachToScreen(), blit180(), blit270(), blit90(), blit_template(), QProxyScreen::configure(), createSurface(), QDirectPainter::frameBuffer(), QWSDisplay::frameBuffer(), getPrimaryScreen(), QVFbScreen::physicalSize(), QWSDirectPainterSurface::QWSDirectPainterSurface(), QVNCDirtyMapOptimized< T >::setDirty(), and solidFill_template().
 { return data; }
blank()
void QScreen::blank (bool on) virtual
Prevents the screen driver form displaying any content on the screen.
Note that the default implementation does nothing.
Reimplement this function to prevent the screen driver from displaying any contents on the screen if on is true; otherwise the contents is expected to be shown.
See also
blit()
Reimplemented in QDirectFBScreen, QProxyScreen, QLinuxFbScreen, QMultiScreen, QVFbScreen, QIntfbScreen, QQnxScreen, and EGLNullWSScreen.
Definition at line 2329 of file qscreen_qws.cpp.
Referenced by QWSServerPrivate::_q_screenSaverSleep(), QWSServerPrivate::_q_screenSaverWake(), QMultiScreen::blank(), QProxyScreen::blank(), and QWSServer::setScreenSaverIntervals().
 {
 }
blit() [1/2]
void QScreen::blit (const QImage & image, const QPoint & topLeft, const QRegion & region) virtual
Copies the given region in the given image to the point specified by topLeft using device coordinates.
This function is called from the exposeRegion() function; it is not intended to be called explicitly.
Reimplement this function to make use of Adding an Accelerated Graphics Driver to Qt for Embedded Linux{accelerated hardware}. Note that this function must be reimplemented if the framebuffer format is not supported by Qt for Embedded Linux (See the Qt for Embedded Linux Display Management{Display Management} documentation for more details).
See also
exposeRegion(), solidFill(), blank()
Reimplemented in QProxyScreen, QMultiScreen, QTransformedScreen, PvrEglScreen, and QAhiScreen.
Definition at line 2640 of file qscreen_qws.cpp.
Referenced by PvrEglScreen::blit(), QMultiScreen::blit(), QProxyScreen::blit(), blit(), compose(), exposeRegion(), QWSWindowSurface::flush(), and paintBackground().
 {
     const QRect bound = (region() & QRect(topLeft, img.size())).boundingRect();
     QWSDisplay::grab();
     d_ptr->blit(this, img, topLeft - offset(),
             (reg & bound).translated(-topLeft));
     QWSDisplay::ungrab();
 }
blit() [2/2]
void QScreen::blit (QWSWindow * win, const QRegion & clip)
Warning
This function is not part of the public interface.
Definition at line 2681 of file qscreen_qws.cpp.
 {
     QWSWindowSurface *surface = win->windowSurface();
     if (!surface)
         return;
     const QImage &img = surface->image();
     if (img.isNull())
         return;
     const QRegion rgn = clip & win->paintedRegion();
     if (rgn.isEmpty())
         return;
     surface->lock();
     blit(img, win->requestedRegion().boundingRect().topLeft(), rgn);
     surface->unlock();
 }
cache()
uchar * QScreen::cache (int) inline virtual
Warning
This function is not part of the public interface.
This function is used to store pixmaps in graphics memory for the use of the accelerated drivers. See QLinuxFbScreen (where the caching is implemented) for more information.
Reimplemented in QLinuxFbScreen.
Definition at line 237 of file qscreen_qws.h.
 { return 0; }
classId()
QScreen::ClassId QScreen::classId () const
Returns the class identifier for the screen object.
Since
4.4
Definition at line 3551 of file qscreen_qws.cpp.
Referenced by glScreenForDevice(), parentScreen(), screenForDevice(), QApplicationPrivate::setScreenTransformation(), and PvrEglScreen::transformation().
 {
     return static_cast<ClassId>(d_ptr->classId);
 }
clut()
QScreen::clut () inline
Returns a pointer to the screen's color lookup table (i.
e. its color palette).
Note that this function only apply in paletted modes like 8-bit, i.e. in modes where only the palette indexes (and not the actual color values) are stored in memory.
See also
alloc(), depth(), colorCount()
Definition at line 245 of file qscreen_qws.h.
Referenced by QVNCServer::convertPixels(), and qt_conv16ToRgb().
 { return screenclut; }
colorCount()
int QScreen::colorCount () inline
Returns the number of entries in the screen's color lookup table (i.
Since
4.6
e. its color palette). A pointer to the color table can be retrieved using the clut() function.
See also
clut(), alloc()
Definition at line 249 of file qscreen_qws.h.
Referenced by effectiveState().
 { return screencols; }
compose()
void QScreen::compose (int level, const QRegion & exposed, QRegion & blend, QImage ** blendbuffer, int changing_level) private
Definition at line 2828 of file qscreen_qws.cpp.
Referenced by exposeRegion().
 {
     QRect exposed_bounds = exposed.boundingRect();
     QWSWindow *win = 0;
     do {
         win = qwsServer->clientWindows().value(level); // null is background
         ++level;
     } while (win && !win->paintedRegion().boundingRect().intersects(exposed_bounds));
     QWSWindowSurface *surface = (win ? win->windowSurface() : 0);
     bool above_changing = level <= changing_level; // 0 is topmost
     QRegion exposedBelow = exposed;
     bool opaque = true;
     if (win) {
         opaque = win->isOpaque() || !surface->isBuffered();
         if (opaque) {
             exposedBelow -= win->paintedRegion();
             if (above_changing || !surface->isBuffered())
                 blend -= exposed & win->paintedRegion();
         } else {
             blend += exposed & win->paintedRegion();
         }
     }
     if (win && !exposedBelow.isEmpty()) {
         compose(level, exposedBelow, blend, blendbuffer, changing_level);
     } else {
         QSize blendSize = blend.boundingRect().size();
         if (!blendSize.isNull()) {
             *blendbuffer = new QImage(blendSize, d_ptr->preferredImageFormat());
         }
     }
     const QRegion blitRegion = exposed - blend;
     if (!win)
         paintBackground(blitRegion);
     else if (!above_changing && surface->isBuffered())
         blit(win, blitRegion);
     QRegion blendRegion = exposed & blend;
     if (win)
         blendRegion &= win->paintedRegion();
     if (!blendRegion.isEmpty()) {
         QPoint off = blend.boundingRect().topLeft();
         QRasterBuffer rb;
         rb.prepare(*blendbuffer);
         QSpanData spanData;
         spanData.init(&rb, 0);
         if (!win) {
             const QImage::Format format = (*blendbuffer)->format();
             switch (format) {
             case QImage::Format_ARGB32_Premultiplied:
             case QImage::Format_ARGB32:
             case QImage::Format_ARGB8565_Premultiplied:
             case QImage::Format_ARGB8555_Premultiplied:
             case QImage::Format_ARGB6666_Premultiplied:
             case QImage::Format_ARGB4444_Premultiplied:
                 spanData.rasterBuffer->compositionMode = QPainter::CompositionMode_Source;
                 break;
             default:
                 break;
             }
             spanData.setup(qwsServer->backgroundBrush(), 256, QPainter::CompositionMode_Source);
             spanData.dx = off.x();
             spanData.dy = off.y();
         } else if (!surface->isBuffered()) {
                 return;
         } else {
             const QImage &img = surface->image();
             QPoint winoff = off - win->requestedRegion().boundingRect().topLeft();
             // convert win->opacity() from scale [0..255] to [0..256]
             int const_alpha = win->opacity();
             const_alpha += (const_alpha >> 7);
             spanData.type = QSpanData::Texture;
             spanData.initTexture(&img, const_alpha);
             spanData.dx = winoff.x();
             spanData.dy = winoff.y();
         }
         if (!spanData.blend)
             return;
         if (surface)
             surface->lock();
         const QVector<QRect> rects = blendRegion.rects();
         const int nspans = 256;
         QT_FT_Span spans[nspans];
         for (int i = 0; i < rects.size(); ++i) {
             int y = rects.at(i).y() - off.y();
             int ye = y + rects.at(i).height();
             int x = rects.at(i).x() - off.x();
             int len = rects.at(i).width();
             while (y < ye) {
                 int n = qMin(nspans, ye - y);
                 int i = 0;
                 while (i < n) {
                     spans[i].x = x;
                     spans[i].len = len;
                     spans[i].y = y + i;
                     spans[i].coverage = 255;
                     ++i;
                 }
                 spanData.blend(n, spans, &spanData);
                 y += n;
             }
         }
         if (surface)
             surface->unlock();
     }
 }
connect()
bool QScreen::connect (const QString & displaySpec) pure virtual
This function is called by every Qt for Embedded Linux application on startup, and must be implemented to map in the framebuffer and the accelerated drivers that the graphics card control registers.
Note that connect must be called before the initDevice() function.
Ensure that true is returned if a connection to the screen device is made. Otherwise, return false. Upon making the connection, the function should read out the parameters of the framebuffer and use them as required to set this class's protected variables.
The displaySpec argument is passed by the QWS_DISPLAY environment variable or the -display command line parameter, and has the following syntax:
[screen driver][:driver specific options][:display number]
For example, to use the mach64 driver on fb1 as display 2:
Mach64:/dev/fb1:2
See Qt for Embedded Linux Display Management for more details.
See also
disconnect(), initDevice(), {Running Qt for Embedded Linux Applications}
Implemented in QDirectFBScreen, QProxyScreen, QLinuxFbScreen, QTransformedScreen, PvrEglScreen, QMultiScreen, QQnxScreen, QVFbScreen, QVNCScreen, QIntfbScreen, QAhiScreen, and EGLNullWSScreen.
Referenced by QWSServer::endDisplayReconfigure(), and qt_get_screen().
createSurface() [1/2]
QWSWindowSurface * QScreen::createSurface (QWidget * widget) const virtual
Creates and returns a new window surface for the given widget.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented in QDirectFBScreen, QProxyScreen, QMultiScreen, PvrEglScreen, and EGLNullWSScreen.
Definition at line 2811 of file qscreen_qws.cpp.
Referenced by EGLNullWSScreen::createSurface(), PvrEglScreen::createSurface(), QMultiScreen::createSurface(), QProxyScreen::createSurface(), QWSWindow::createSurface(), QDirectFBScreen::createSurface(), QWSGraphicsSystem::createWindowSurface(), effectiveState(), and qt_egl_create_surface().
 {
 #ifndef QT_NO_PAINTONSCREEN
     if (isWidgetPaintOnScreen(widget) && base())
         return new QWSOnScreenSurface(widget);
     else
 #endif
     if (QApplication::type() == QApplication::GuiServer)
         return new QWSLocalMemSurface(widget);
 #ifndef QT_NO_QWS_MULTIPROCESS
     else
         return new QWSSharedMemSurface(widget);
 #endif
     return 0;
 }
createSurface() [2/2]
QWSWindowSurface * QScreen::createSurface (const QString & key) const virtual
Creates and returns a new window surface matching the given key.
Since
4.2
The server application will call this function whenever it needs to create a server side representation of a window, e.g. when copying the content of memory to the screen using the screen driver.
Note that this function must be reimplemented when adding an accelerated graphics driver. See the Adding an Accelerated Graphics Driver to Qt for Embedded Linux {Adding an Accelerated Graphics Driver} documentation for details.
See also
{Qt for Embedded Linux Architecture}
Reimplemented in QDirectFBScreen, QProxyScreen, QMultiScreen, PvrEglScreen, and EGLNullWSScreen.
Definition at line 2756 of file qscreen_qws.cpp.
 {
 #ifndef QT_NO_PAINTONSCREEN
     if (key == QLatin1String("OnScreen"))
         return new QWSOnScreenSurface;
     else
 #endif
     if (key == QLatin1String("mem"))
         return new QWSLocalMemSurface;
 #ifndef QT_NO_QWS_MULTIPROCESS
     else if (key == QLatin1String("shm"))
         return new QWSSharedMemSurface;
 #endif
 #ifndef QT_NO_PAINT_DEBUG
     else if (key == QLatin1String("Yellow"))
         return new QWSYellowSurface;
 #endif
 #ifndef QT_NO_DIRECTPAINTER
     else if (key == QLatin1String("DirectPainter"))
         return new QWSDirectPainterSurface;
 #endif
     return 0;
 }
depth()
QScreen::depth () const inline
Returns the depth of the framebuffer, in bits per pixel.
Note that the returned depth is the number of bits each pixel fills rather than the number of significant bits, so 24bpp and 32bpp express the same range of colors (8 bits of red, green and blue).
See also
clut(), pixmapDepth()
Definition at line 229 of file qscreen_qws.h.
Referenced by QWSOnScreenSurface::attachToScreen(), QTransformedScreen::blit(), QProxyScreen::configure(), QVNCScreen::connect(), QMultiScreen::connect(), QDirectFBScreen::connect(), QPixmap::defaultDepth(), QWSDisplay::depth(), QDirectFBScreen::depth(), QDirectFBPixmapData::fill(), QDirectFBPixmapData::fromDataBufferDescription(), QDirectFBPixmapData::fromImage(), QDirectFBPaintDevice::metric(), pixmapDepth(), QWSMemorySurface::preferredImageFormat(), QScreenPrivate::preferredImageFormat(), qt_blit_setup(), qt_solidFill_setup(), QVNCDirtyMap::QVNCDirtyMap(), QDirectFBPixmapData::resize(), QDirectPainter::screenDepth(), and QScreenCursor::set().
 { return d; }
deviceHeight()
QScreen::deviceHeight () const inline
Returns the full height of the framebuffer device in pixels.
Note that the returned height can differ from the height which Qt for Embedded Linux will actually use, that is if the display is centered within the framebuffer.
See also
height(), physicalHeight(), deviceWidth()
Definition at line 234 of file qscreen_qws.h.
Referenced by QProxyScreen::configure(), devS(), QDirectFBPaintDevice::dotsPerMeterY(), QWSServer::endDisplayReconfigure(), QDirectPainter::endPainting(), QDirectPainter::flush(), QWSMouseHandler::limitToScreen(), QWSServerPrivate::openDisplay(), QDirectFBMouseHandlerPrivate::QDirectFBMouseHandlerPrivate(), QQnxMouseHandler::QQnxMouseHandler(), QScreenCursor::QScreenCursor(), QVNCDirtyMap::QVNCDirtyMap(), QVNCServer::readClient(), QTransformedScreen::region(), QDirectPainter::screenHeight(), QWSServer::sendMouseEvent(), QDirectPainter::setRegion(), QDirectPainter::startPainting(), and QRfbRawEncoder::write().
 { return dh; }
deviceWidth()
QScreen::deviceWidth () const inline
Returns the physical width of the framebuffer device in pixels.
Note that the returned width can differ from the width which Qt for Embedded Linux will actually use, that is if the display is centered within the framebuffer.
See also
width(), physicalWidth(), deviceHeight()
Definition at line 233 of file qscreen_qws.h.
Referenced by QProxyScreen::configure(), devS(), QDirectFBPaintDevice::dotsPerMeterX(), QWSServer::endDisplayReconfigure(), QDirectPainter::endPainting(), QDirectPainter::flush(), QWSMouseHandler::limitToScreen(), QWSServerPrivate::openDisplay(), QDirectFBMouseHandlerPrivate::QDirectFBMouseHandlerPrivate(), QQnxMouseHandler::QQnxMouseHandler(), QScreenCursor::QScreenCursor(), QVNCDirtyMap::QVNCDirtyMap(), QVNCServer::readClient(), QTransformedScreen::region(), QDirectPainter::screenWidth(), QWSServer::sendMouseEvent(), QDirectPainter::setRegion(), QDirectPainter::startPainting(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 { return dw; }
disconnect()
QScreen::disconnect () pure virtual
This function is called by every Qt for Embedded Linux application before exiting, and must be implemented to unmap the framebuffer.
Note that a server application will call the shutdownDevice() function prior to this function.
See also
connect(), shutdownDevice(), {Running Qt for Embedded Linux Applications}
Implemented in QDirectFBScreen, QProxyScreen, QLinuxFbScreen, PvrEglScreen, QMultiScreen, QQnxScreen, QVFbScreen, QVNCScreen, QIntfbScreen, QAhiScreen, and EGLNullWSScreen.
Referenced by QWSServer::beginDisplayReconfigure(), QMultiScreen::disconnect(), QProxyScreen::disconnect(), and QWSDisplay::Data::~Data().
exposeRegion()
void QScreen::exposeRegion (QRegion region, int windowIndex) virtual
This function is called by the Qt for Embedded Linux server whenever a screen update is required.
region is the area on the screen that must be updated, and windowIndex is the index into QWSServer::clientWindows() of the window that required the update. QWSWindow::state() gives more information about the cause.
The default implementation composes the affected windows and paints the given region on screen by calling the blit() and solidFill() functions
This function can be reimplemented to perform composition in hardware, or to perform transition effects. For simpler hardware acceleration, or to interface with this is typically done by reimplementing the blit() and solidFill() functions instead.
Note that there is no need to call this function explicitly.
See also
blit(), solidFill(), blank()
Reimplemented in QDirectFBScreen, QProxyScreen, QMultiScreen, QTransformedScreen, QQnxScreen, and EGLNullWSScreen.
Definition at line 2555 of file qscreen_qws.cpp.
Referenced by QQnxScreen::exposeRegion(), QTransformedScreen::exposeRegion(), QMultiScreen::exposeRegion(), QProxyScreen::exposeRegion(), QWSServerPrivate::exposeRegion(), QScreenCursor::hide(), QScreenCursor::move(), QScreenCursor::set(), QWSServer::setBackground(), QLinuxFbScreen::setMode(), and QScreenCursor::show().
 {
     r &= region();
     if (r.isEmpty())
         return;
     int changing = windowIndex;
     // when we have just lowered a window, we have to expose all the windows below where the
     // window used to be.
     if (changing && qwsServer->clientWindows().at(changing)->state() == QWSWindow::Lowering)
         changing = 0;
 #ifdef QTOPIA_PERFTEST
     static enum { PerfTestUnknown, PerfTestOn, PerfTestOff } perfTestState = PerfTestUnknown;
     if(PerfTestUnknown == perfTestState) {
         if(::getenv("QTOPIA_PERFTEST"))
             perfTestState = PerfTestOn;
         else
             perfTestState = PerfTestOff;
     }
     if(PerfTestOn == perfTestState) {
         QWSWindow *changed = qwsServer->clientWindows().at(changing);
         if(!changed->client()->identity().isEmpty())
             qDebug() << "Performance  :  expose_region  :"
                      << changed->client()->identity()
                      << r.boundingRect() << ": "
                      << qPrintable( QTime::currentTime().toString( "h:mm:ss.zzz" ) );
     }
 #endif
     const QRect bounds = r.boundingRect();
     QRegion blendRegion;
     QImage *blendBuffer = 0;
 #ifndef QT_NO_QWS_CURSOR
     if (qt_screencursor && !qt_screencursor->isAccelerated()) {
         blendRegion = r & qt_screencursor->boundingRect();
     }
 #endif
     compose(0, r, blendRegion, &blendBuffer, changing);
     if (blendBuffer && !blendBuffer->isNull()) {
         const QPoint offset = blendRegion.boundingRect().topLeft();
 #ifndef QT_NO_QWS_CURSOR
         if (qt_screencursor && !qt_screencursor->isAccelerated()) {
             const QRect cursorRect = qt_screencursor->boundingRect();
             if (blendRegion.intersects(cursorRect)) {
                 blendCursor(blendBuffer, qt_screencursor->image(),
                             cursorRect.topLeft() - offset);
             }
         }
 #endif // QT_NO_QWS_CURSOR
         blit(*blendBuffer, offset, blendRegion);
         delete blendBuffer;
     }
     if (r.rectCount() == 1) {
         setDirty(r.boundingRect());
     } else {
         const QVector<QRect> rects = r.rects();
         for (int i = 0; i < rects.size(); ++i)
             setDirty(rects.at(i));
     }
 }
frameBufferLittleEndian()
bool QScreen::frameBufferLittleEndian () const private
Definition at line 3322 of file qscreen_qws.cpp.
Referenced by QProxyScreen::configure().
 {
     return d_ptr->fb_is_littleEndian;
 }
graphicsSystem()
QGraphicsSystem * QScreen::graphicsSystem () const
Warning
This function is not part of the public interface.
Since
4.5
Definition at line 3538 of file qscreen_qws.cpp.
Referenced by QApplicationPrivate::graphicsSystem().
 {
     return d_ptr->graphicsSystem;
 }
haltUpdates()
void QScreen::haltUpdates () virtual
Warning
This function is not part of the public interface.
Reimplemented in QProxyScreen, and QMultiScreen.
Definition at line 3271 of file qscreen_qws.cpp.
Referenced by QMultiScreen::haltUpdates(), and QProxyScreen::haltUpdates().
 {
 }
height()
int QScreen::height () const inline
Returns the logical height of the framebuffer in pixels.
See also
deviceHeight(), physicalHeight(), width()
Definition at line 228 of file qscreen_qws.h.
Referenced by QDirectPainter::allocatedRegion(), QWSOnScreenSurface::attachToScreen(), QProxyScreen::configure(), QMultiScreen::connect(), effectiveState(), QWSServer::endDisplayReconfigure(), QWSDisplay::height(), qt_defaultDpiY(), qt_directpainter_embedevent(), qt_directpainter_region(), screenS(), QWSPcMouseHandlerPrivate::sendEvent(), QWSServer::setBackground(), QTransformedScreen::setDirty(), setImageMetrics(), PvrEglWindowSurface::transformRects(), QETWidget::translateMouseEvent(), QWSServerPrivate::update_regions(), and QRfbHextileEncoder< SRC >::write().
 { return h; }
initDevice()
bool QScreen::initDevice () pure virtual
This function is called by the Qt for Embedded Linux server to initialize the framebuffer.
Note that a server application will call the connect() function prior to this function.
Implement this function to make accelerated drivers set up the graphics card. Return true to indicate success and false to indicate failure.
See also
shutdownDevice(), connect()
Implemented in QDirectFBScreen, QProxyScreen, QLinuxFbScreen, PvrEglScreen, QMultiScreen, QAhiScreen, QQnxScreen, QVFbScreen, QVNCScreen, QIntfbScreen, and EGLNullWSScreen.
Referenced by QWSDisplay::Data::init(), QMultiScreen::initDevice(), and QProxyScreen::initDevice().
instance()
static QScreen * QScreen::instance () inline static
Returns a pointer to the application's QScreen instance.
If this screen consists of several subscreens, operations to the returned instance will affect all its subscreens. Use the subscreens() function to retrieve access to a particular subscreen.
See also
subScreens(), subScreenIndexAt()
Definition at line 201 of file qscreen_qws.h.
Referenced by QRasterPixmapData::createPixmapForImage(), QPixmap::defaultDepth(), getPrimaryScreen(), QApplicationPrivate::graphicsSystem(), QPixmapDataFactory::instance(), QDirectFBMouseHandlerPrivate::QDirectFBMouseHandlerPrivate(), QWSDirectPainterSurface::QWSDirectPainterSurface(), QDirectFBMouseHandlerPrivate::readMouseData(), QWSServer::refresh(), QRasterPixmapData::resize(), and setScreenTransformation().
 { return qt_screen; }
isInterlaced()
bool QScreen::isInterlaced () const virtual
Returns true if the display is interlaced (i.
e. is displaying images progressively like a television screen); otherwise returns false.
If the display is interlaced, the drawing is altered to look better.
See also
isTransformed(), linestep()
Reimplemented in QProxyScreen, and QMultiScreen.
Definition at line 3047 of file qscreen_qws.cpp.
Referenced by QMultiScreen::isInterlaced(), and QProxyScreen::isInterlaced().
 {
     return false;//qws_screen_is_interlaced;;
 }
isTransformed()
bool QScreen::isTransformed () const virtual
Returns true if the screen is transformed (for instance, rotated 90 degrees); otherwise returns false.
See also
transformOrientation(), isInterlaced()
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3026 of file qscreen_qws.cpp.
Referenced by QWSServerPrivate::_q_newConnection(), QDirectPainter::allocatedRegion(), QDirectPainter::endPainting(), QQnxScreen::exposeRegion(), QDirectPainter::flush(), QProxyScreen::isTransformed(), qt_directpainter_embedevent(), qt_directpainter_region(), QWSPcMouseHandlerPrivate::sendEvent(), QWSServer::sendMouseEvent(), QQnxScreen::setDirty(), QDirectPainter::setRegion(), and QDirectPainter::startPainting().
 {
     return false;
 }
isWidgetPaintOnScreen()
bool QScreen::isWidgetPaintOnScreen (const QWidget * w) static private
Definition at line 2782 of file qscreen_qws.cpp.
Referenced by createSurface(), and QWSOnScreenSurface::isValid().
 {
     static int doOnScreen = -1;
     if (doOnScreen == -1) {
         const QByteArray env = qgetenv("QT_ONSCREEN_PAINT");
         if (env == "force")
             doOnScreen = 2;
         else
             doOnScreen = (env.toInt() > 0 ? 1 : 0);
     }
     if (doOnScreen == 2) // force
         return true;
     if (doOnScreen == 0 && !w->testAttribute(Qt::WA_PaintOnScreen))
         return false;
     return w->d_func()->isOpaque;
 }
linestep()
QScreen::linestep () const inline
Returns the length of each scanline of the framebuffer in bytes.
See also
isInterlaced()
Definition at line 232 of file qscreen_qws.h.
Referenced by QWSOnScreenSurface::attachToScreen(), blit180(), blit270(), blit90(), blit_template(), QProxyScreen::configure(), QDirectPainter::linestep(), QVFbScreen::physicalSize(), QVNCDirtyMapOptimized< T >::setDirty(), and solidFill_template().
 { return lstep; }
mapFromDevice() [1/5]
QSize QScreen::mapFromDevice (const QSize & size) const virtual
Maps the given size from the framebuffer coordinate system to the coordinate space used by the application.
Note that the default implementation simply returns the given size as it is.
Reimplement this function to use the given device's coordinate system when mapping.
See also
mapToDevice()
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3089 of file qscreen_qws.cpp.
Referenced by QDirectPainter::endPainting(), QDirectPainter::flush(), QProxyScreen::mapFromDevice(), QWSServer::sendMouseEvent(), QDirectPainter::setRegion(), and QDirectPainter::startPainting().
 {
     return s;
 }
mapFromDevice() [2/5]
QPoint QScreen::mapFromDevice (const QPoint & point, const QSize & screenSize) const virtual
Maps the given point from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation simply returns the given point as it is.
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3125 of file qscreen_qws.cpp.
 {
     return p;
 }
mapFromDevice() [3/5]
QRect QScreen::mapFromDevice (const QRect & rectangle, const QSize & screenSize) const virtual
Maps the given rectangle from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation simply returns the given rectangle as it is.
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3161 of file qscreen_qws.cpp.
 {
     return r;
 }
mapFromDevice() [4/5]
QImage QScreen::mapFromDevice (const QImage & image) const virtual
Maps the given image from the framebuffer coordinate system to the coordinate space used by the application.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation simply returns the given image as it is.
Definition at line 3195 of file qscreen_qws.cpp.
 {
     return i;
 }
mapFromDevice() [5/5]
QRegion QScreen::mapFromDevice (const QRegion & region, const QSize & screenSize) const virtual
Maps the given region from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation simply returns the given region as it is.
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3231 of file qscreen_qws.cpp.
 {
     return r;
 }
mapToDevice() [1/5]
QSize QScreen::mapToDevice (const QSize & size) const virtual
Maps the given size from the coordinate space used by the application to the framebuffer coordinate system.
Note that the default implementation simply returns the given size as it is.
Reimplement this function to use the given device's coordinate system when mapping.
See also
mapFromDevice()
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3068 of file qscreen_qws.cpp.
Referenced by QDirectPainter::allocatedRegion(), QProxyScreen::mapToDevice(), qt_directpainter_embedevent(), qt_directpainter_region(), and QWSPcMouseHandlerPrivate::sendEvent().
 {
     return s;
 }
mapToDevice() [2/5]
QPoint QScreen::mapToDevice (const QPoint & point, const QSize & screenSize) const virtual
Maps the given point from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation returns the given point as it is.
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3107 of file qscreen_qws.cpp.
 {
     return p;
 }
mapToDevice() [3/5]
QRect QScreen::mapToDevice (const QRect & rectangle, const QSize & screenSize) const virtual
Maps the given rectangle from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation returns the given rectangle as it is.
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3143 of file qscreen_qws.cpp.
 {
     return r;
 }
mapToDevice() [4/5]
QImage QScreen::mapToDevice (const QImage & image) const virtual
Maps the given image from the coordinate space used by the application to the framebuffer coordinate system.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation returns the given image as it is.
Definition at line 3178 of file qscreen_qws.cpp.
 {
     return i;
 }
mapToDevice() [5/5]
QRegion QScreen::mapToDevice (const QRegion & region, const QSize & screenSize) const virtual
Maps the given region from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the default implementation returns the given region as it is.
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3213 of file qscreen_qws.cpp.
 {
     return r;
 }
memoryNeeded()
int QScreen::memoryNeeded (const QString &) virtual
Warning
This function is not part of the public interface.
Reimplemented in QProxyScreen, and QMultiScreen.
Definition at line 3263 of file qscreen_qws.cpp.
Referenced by QWSDisplay::Data::init(), QMultiScreen::memoryNeeded(), QProxyScreen::memoryNeeded(), and QWSDisplay::Data::reinit().
 {
     return 0;
 }
numCols()
int QScreen::numCols () inline
See also
colorCount()
Definition at line 247 of file qscreen_qws.h.
Referenced by qt_conv16ToRgb().
 { return screencols; }
offset()
QPoint QScreen::offset () const
Returns the logical offset of the screen, i.
Since
4.2
e., the offset between (0,0) in screen coordinates and the application coordinate system.
Definition at line 3311 of file qscreen_qws.cpp.
Referenced by blit(), QProxyScreen::configure(), QMultiScreen::connect(), exposeRegion(), QVNCServer::frameBufferUpdateRequest(), QWSMouseHandler::mouseChanged(), QVNCServer::pointerEvent(), QVFbScreen::setDirty(), solidFill(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     return d_ptr->offset;
 }
onCard() [1/2]
bool QScreen::onCard (const unsigned char * buffer) const virtual
Returns true if the specified buffer is within the graphics card's memory; otherwise returns false (i.e.
if it's in main RAM).
See also
base(), totalSize()
Reimplemented in QProxyScreen, and QMultiScreen.
Definition at line 2402 of file qscreen_qws.cpp.
Referenced by QMultiScreen::onCard(), and QProxyScreen::onCard().
 {
     long t=(unsigned long)p;
     long bmin=(unsigned long)data;
     if (t < bmin)
         return false;
     if(t >= bmin+mapsize)
         return false;
     return true;
 }
onCard() [2/2]
bool QScreen::onCard (const unsigned char * buffer, ulong & out_offset) const virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.If the specified buffer is within the graphics card's memory, this function stores the offset from the start of graphics card memory (in bytes), in the location specified by the offset parameter.
Reimplemented in QProxyScreen, and QMultiScreen.
Definition at line 2423 of file qscreen_qws.cpp.
 {
     long t=(unsigned long)p;
     long bmin=(unsigned long)data;
     if (t < bmin)
         return false;
     long o = t - bmin;
     if (o >= mapsize)
         return false;
     offset = o;
     return true;
 }
paintBackground()
void QScreen::paintBackground (const QRegion & r) private
Definition at line 2943 of file qscreen_qws.cpp.
Referenced by compose().
 {
     const QBrush &bg = qwsServer->backgroundBrush();
     Qt::BrushStyle bs = bg.style();
     if (bs == Qt::NoBrush || r.isEmpty())
         return;
     if (bs == Qt::SolidPattern) {
         solidFill(bg.color(), r);
     } else {
         const QRect br = r.boundingRect();
         QImage img(br.size(), d_ptr->preferredImageFormat());
         QPoint off = br.topLeft();
         QRasterBuffer rb;
         rb.prepare(&img);
         QSpanData spanData;
         spanData.init(&rb, 0);
         spanData.setup(bg, 256, QPainter::CompositionMode_Source);
         spanData.dx = off.x();
         spanData.dy = off.y();
         Q_ASSERT(spanData.blend);
         const QVector<QRect> rects = r.rects();
         const int nspans = 256;
         QT_FT_Span spans[nspans];
         for (int i = 0; i < rects.size(); ++i) {
             int y = rects.at(i).y() - off.y();
             int ye = y + rects.at(i).height();
             int x = rects.at(i).x() - off.x();
             int len = rects.at(i).width();
             while (y < ye) {
                 int n = qMin(nspans, ye - y);
                 int i = 0;
                 while (i < n) {
                     spans[i].x = x;
                     spans[i].len = len;
                     spans[i].y = y + i;
                     spans[i].coverage = 255;
                     ++i;
                 }
                 spanData.blend(n, spans, &spanData);
                 y += n;
             }
         }
         blit(img, br.topLeft(), r);
     }
 }
physicalHeight()
int QScreen::physicalHeight () const inline
Returns the physical height of the screen in millimeters.
Since
4.2
See also
height(), deviceHeight(), physicalWidth()
Definition at line 291 of file qscreen_qws.h.
Referenced by QProxyScreen::configure(), QMultiScreen::connect(), QDirectFBPaintDevice::dotsPerMeterY(), effectiveState(), qt_defaultDpiY(), setImageMetrics(), and QTransformedScreen::setTransformation().
 { return physHeight; } // physical display size in mm
physicalWidth()
int QScreen::physicalWidth () const inline
Returns the physical width of the screen in millimeters.
Since
4.2
See also
width(), deviceWidth(), physicalHeight()
Definition at line 290 of file qscreen_qws.h.
Referenced by QProxyScreen::configure(), QMultiScreen::connect(), QDirectFBPaintDevice::dotsPerMeterX(), effectiveState(), qt_defaultDpiX(), setImageMetrics(), and QTransformedScreen::setTransformation().
 { return physWidth; }   // physical display size in mm
pixelFormat()
QImage::Format QScreen::pixelFormat () const
Returns the pixel format of the screen, or QImage::Format_Invalid if the pixel format is not a supported image format.
Definition at line 2225 of file qscreen_qws.cpp.
Referenced by QWSOnScreenSurface::attachToScreen(), QAhiScreen::blit(), QProxyScreen::configure(), EGLNullWSScreen::connect(), QVNCScreen::connect(), QDirectFBScreen::connect(), QDirectFBPixmapData::copy(), QDirectFBScreenPrivate::createPixmapData(), QRasterPixmapData::createPixmapForImage(), QDirectFBWindowSurface::createWindow(), QDirectFBPixmapData::fromDataBufferDescription(), QDirectFBPixmapData::fromImage(), QDirectFBPaintEnginePrivate::getSurface(), PvrEglWindowSurface::image(), QLinuxFbScreen::initDevice(), QWSMemorySurface::preferredImageFormat(), QDirectFBPixmapData::resize(), QRasterPixmapData::resize(), screenForDevice(), QAhiScreenCursor::set(), QDirectFBWindowSurface::setGeometry(), QAhiScreen::solidFill(), and QVNCClientCursor::write().
 {
     return d_ptr->pixelFormat;
 }
pixelType()
PixelType QScreen::pixelType () const inline
Returns the pixel storage format of the screen.
Definition at line 231 of file qscreen_qws.h.
Referenced by QTransformedScreen::blit(), QProxyScreen::configure(), QVNCServer::convertPixels(), qt_blit_setup(), qt_conv16ToRgb(), and qt_solidFill_setup().
 { return pixeltype; }
pixmapDataFactory()
QPixmapDataFactory * QScreen::pixmapDataFactory () const
Warning
This function is not part of the public interface.
Since
4.4
Definition at line 3520 of file qscreen_qws.cpp.
Referenced by QWSGraphicsSystem::createPixmapData(), and QPixmapDataFactory::instance().
 {
     return d_ptr->pixmapFactory;
 }
pixmapDepth()
int QScreen::pixmapDepth () const virtual
Returns the preferred depth for pixmaps, in bits per pixel.
See also
depth()
Definition at line 3255 of file qscreen_qws.cpp.
Referenced by QWSDisplay::pixmapDepth().
 {
     return depth();
 }
pixmapLinestepAlignment()
int QScreen::pixmapLinestepAlignment () inline virtual
Returns the value (in bits) to which individual scanlines of pixmaps held in the graphics card's memory, should be aligned.
Note that the default implementation returns 64; reimplement this function to override the return value, e.g., when implementing an accelerated driver (see the Adding an Accelerated Graphics Driver to Qt for Embedded Linux documentation for details.
See also
pixmapOffsetAlignment()
Definition at line 214 of file qscreen_qws.h.
 { return 64; }
pixmapOffsetAlignment()
int QScreen::pixmapOffsetAlignment () inline virtual
Returns the value (in bits) to which the start address of pixmaps held in the graphics card's memory, should be aligned.
Note that the default implementation returns 64; reimplement this function to override the return value, e.g., when implementing an accelerated driver (see the Adding an Accelerated Graphics Driver to Qt for Embedded Linux documentation for details).
See also
pixmapLinestepAlignment()
Definition at line 213 of file qscreen_qws.h.
Referenced by QLinuxFbScreen::cache().
 { return 64; }
region()
QRegion QScreen::region () const inline virtual
Returns the region covered by this screen driver.
Since
4.2
See also
base(), screenSize()
Reimplemented in QProxyScreen, QMultiScreen, and QTransformedScreen.
Definition at line 284 of file qscreen_qws.h.
Referenced by QMultiScreen::addSubScreen(), QAhiScreen::blit(), QMultiScreen::blit(), blit(), clearRect(), QMultiScreen::exposeRegion(), QProxyScreen::exposeRegion(), QDirectFBScreen::exposeRegion(), exposeRegion(), QWSServerPrivate::exposeRegion(), QMultiScreenCursor::move(), QProxyScreen::region(), QMultiScreen::removeSubScreen(), QVFbScreen::setDirty(), QMultiScreen::setDirty(), QDirectFBWindowSurface::setGeometry(), setMaxWindowRect(), QWSServer::setMaxWindowRect(), QLinuxFbScreen::setMode(), QApplicationPrivate::setScreenTransformation(), QAhiScreen::solidFill(), QMultiScreen::solidFill(), and subScreenIndexAt().
 { return QRect(offset(), QSize(w, h)); }
restore()
void QScreen::restore () virtual
Restores the previously saved state of the graphics card.
For example, hardware screen drivers should reimplement the save() and restore() functions to save and restore its registers, enabling swintching between virtual consoles.
Note that the default implementation does nothing.
See also
save()
Reimplemented in QProxyScreen, QLinuxFbScreen, QMultiScreen, QVFbScreen, and QIntfbScreen.
Definition at line 2325 of file qscreen_qws.cpp.
Referenced by QWSTtyKbPrivate::handleConsoleSwitch(), QMultiScreen::restore(), and QProxyScreen::restore().
 {
 }
resumeUpdates()
void QScreen::resumeUpdates () virtual
Warning
This function is not part of the public interface.
Reimplemented in QProxyScreen, and QMultiScreen.
Definition at line 3278 of file qscreen_qws.cpp.
Referenced by QMultiScreen::resumeUpdates(), and QProxyScreen::resumeUpdates().
 {
 }
save()
void QScreen::save () virtual
Saves the current state of the graphics card.
For example, hardware screen drivers should reimplement the save() and restore() functions to save and restore its registers, enabling swintching between virtual consoles.
Note that the default implementation does nothing.
See also
restore()
Reimplemented in QProxyScreen, QLinuxFbScreen, QMultiScreen, QVFbScreen, and QIntfbScreen.
Definition at line 2309 of file qscreen_qws.cpp.
Referenced by QWSTtyKbPrivate::handleConsoleSwitch(), QMultiScreen::save(), and QProxyScreen::save().
 {
 }
screenSize()
QScreen::screenSize () const inline
Returns the size of the screen in bytes.
The screen size is always located at the beginning of framebuffer memory, i.e. it can also be retrieved using the base() function.
See also
base(), region()
Definition at line 242 of file qscreen_qws.h.
Referenced by QProxyScreen::configure().
 { return size; }
set()
void QScreen::set (unsigned int , unsigned int , unsigned int , unsigned int) virtual
Warning
This function is not part of the public interface.
Reimplemented in QLinuxFbScreen.
Definition at line 2337 of file qscreen_qws.cpp.
Referenced by QApplication::qwsSetCustomColors().
 {
 }
setDirty()
void QScreen::setDirty (const QRect & rectangle) virtual
Marks the given rectangle as dirty.
Note that the default implementation does nothing; reimplement this function to indicate that the given rectangle has been altered.
Reimplemented in QProxyScreen, QLinuxFbScreen, QMultiScreen, QTransformedScreen, QQnxScreen, QVFbScreen, QIntfbScreen, QVNCScreen, and QVFbScreen.
Definition at line 3010 of file qscreen_qws.cpp.
Referenced by exposeRegion(), QWSWindowSurface::flush(), QMultiScreen::setDirty(), and QProxyScreen::setDirty().
 {
 }
setFrameBufferLittleEndian()
void QScreen::setFrameBufferLittleEndian (bool littleEndian) private
Definition at line 3317 of file qscreen_qws.cpp.
Referenced by QProxyScreen::configure(), QVFbScreen::connect(), QVNCScreen::connect(), QQnxScreen::connect(), QLinuxFbScreen::connect(), and QLinuxFbIntegration::connect().
 {
     d_ptr->fb_is_littleEndian = littleEndian;
 }
setGraphicsSystem()
void QScreen::setGraphicsSystem (QGraphicsSystem * system) protected
Warning
This function is not part of the public interface.
Since
4.5
Definition at line 3529 of file qscreen_qws.cpp.
Referenced by QDirectFBScreen::connect().
 {
     d_ptr->graphicsSystem = system;
 }
setMode()
QScreen::setMode (int width, int height, int depth) pure virtual
Implement this function to reset the framebuffer's resolution (width and height) and bit depth.
After the resolution has been set, existing paint engines will be invalid and the framebuffer should be completely redrawn. In a multiple-process situation, all other applications must be notified to reset their mode and update themselves accordingly.
Implemented in QDirectFBScreen, QProxyScreen, QLinuxFbScreen, PvrEglScreen, QMultiScreen, QVFbScreen, QIntfbScreen, QQnxScreen, QAhiScreen, and EGLNullWSScreen.
Referenced by QProxyScreen::setMode().
setOffset()
void QScreen::setOffset (const QPoint & p)
Warning
This function is not part of the public interface.
Definition at line 3297 of file qscreen_qws.cpp.
Referenced by QProxyScreen::configure(), and QMultiScreen::connect().
 {
     d_ptr->offset = p;
 }
setPixelFormat()
void QScreen::setPixelFormat (QImage::Format format) protected
Sets the screen's pixel format to format.
Definition at line 2233 of file qscreen_qws.cpp.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), PvrEglScreen::connect(), QDirectFBScreen::connect(), and QLinuxFbScreen::setPixelFormat().
 {
     d_ptr->pixelFormat = format;
 }
setPixmapDataFactory()
void QScreen::setPixmapDataFactory (QPixmapDataFactory * factory) protected
Warning
This function is not part of the public interface.
Since
4.4
Definition at line 3505 of file qscreen_qws.cpp.
 {
     static bool shownWarning = false;
     if (!shownWarning) {
         qWarning("QScreen::setPixmapDataFactory() is deprecated - use setGraphicsSystem() instead");
         shownWarning = true;
     }
     d_ptr->pixmapFactory = factory;
 }
sharedRamSize()
int QScreen::sharedRamSize (void *) inline virtual
Warning
This function is not part of the public interface.
Reimplemented in QProxyScreen, QLinuxFbScreen, and QMultiScreen.
Definition at line 215 of file qscreen_qws.h.
Referenced by QWSDisplay::Data::init(), QMultiScreen::sharedRamSize(), and QProxyScreen::sharedRamSize().
 { return 0; }
shutdownDevice()
void QScreen::shutdownDevice () virtual
This function is called by the Qt for Embedded Linux server before it calls the disconnect() function when exiting.
Note that the default implementation only hides the mouse cursor; reimplement this function to do the necessary graphics card specific cleanup.
See also
initDevice(), disconnect()
Reimplemented in QDirectFBScreen, QProxyScreen, QLinuxFbScreen, PvrEglScreen, QMultiScreen, QQnxScreen, QVFbScreen, QAhiScreen, QVNCScreen, QIntfbScreen, and EGLNullWSScreen.
Definition at line 2201 of file qscreen_qws.cpp.
Referenced by QWSServerPrivate::closeDisplay(), QMultiScreen::shutdownDevice(), and QProxyScreen::shutdownDevice().
 {
 #ifndef QT_NO_QWS_CURSOR
     if (qt_screencursor)
         qt_screencursor->hide();
 #endif
 }
solidFill()
void QScreen::solidFill (const QColor & color, const QRegion & region) virtual
Fills the given region of the screen with the specified color.
This function is called from the exposeRegion() function; it is not intended to be called explicitly.
Reimplement this function to make use of Adding an Accelerated Graphics Driver to Qt for Embedded Linux{accelerated hardware}. Note that this function must be reimplemented if the framebuffer format is not supported by Qt for Embedded Linux (See the Qt for Embedded Linux Display Management{Display Management} documentation for more details).
See also
exposeRegion(), blit(), blank()
Reimplemented in QDirectFBScreen, QProxyScreen, QMultiScreen, QTransformedScreen, PvrEglScreen, and QAhiScreen.
Definition at line 2727 of file qscreen_qws.cpp.
Referenced by paintBackground(), PvrEglScreen::solidFill(), QMultiScreen::solidFill(), and QProxyScreen::solidFill().
 {
     QWSDisplay::grab();
     d_ptr->solidFill(this, color,
                      region.translated(-offset()) & QRect(0, 0, dw, dh));
     QWSDisplay::ungrab();
 }
subScreenIndexAt()
int QScreen::subScreenIndexAt (const QPoint & position) const
Returns the index of the subscreen at the given position; returns -1 if no screen is found.
Since
4.2
The index identifies the subscreen in the list of pointers returned by the subScreens() function.
See also
instance(), subScreens()
Definition at line 3343 of file qscreen_qws.cpp.
Referenced by QMultiScreen::createSurface(), and QMultiScreenCursor::move().
 {
     const QList<QScreen*> screens = subScreens();
     const int n = screens.count();
     for (int i = 0; i < n; ++i) {
         if (screens.at(i)->region().contains(p))
             return i;
     }
     return -1;
 }
subScreens()
QList< QScreen * > QScreen::subScreens () const inline virtual
Since
4.2
Returns a list of this screen's subscreens. Use the subScreenIndexAt() function to retrieve the index of a screen at a given position.
Note that if this screen consists of several subscreens, operations to this instance will affect all subscreens by default.
See also
instance(), subScreenIndexAt()
Reimplemented in QProxyScreen, and QMultiScreen.
Definition at line 283 of file qscreen_qws.h.
Referenced by QWSServerPrivate::_q_newConnection(), effectiveState(), getPrimaryScreen(), getScreen(), glScreenForDevice(), isServerProcess(), QMultiScreenCursor::move(), QWSServerPrivate::newMouseHandler(), parentScreen(), qt_defaultDpiX(), qt_defaultDpiY(), QWSDirectPainterSurface::QWSDirectPainterSurface(), screenForDevice(), setMaxWindowRect(), QWSServer::setMaxWindowRect(), QWSOnScreenSurface::setPermanentState(), setScreenTransformation(), subScreenIndexAt(), and QProxyScreen::subScreens().
 { return QList<QScreen*>(); }
supportsDepth()
bool QScreen::supportsDepth (int depth) const virtual
Returns true if the screen supports the specified color depth; otherwise returns false.
See also
clut()
Reimplemented in QProxyScreen, QMultiScreen, and QQnxScreen.
Definition at line 2353 of file qscreen_qws.cpp.
Referenced by QWSDisplay::supportsDepth(), and QProxyScreen::supportsDepth().
 {
     if (false) {
         //Just to simplify the ifdeffery
 #ifdef QT_QWS_DEPTH_1
     } else if(d==1) {
         return true;
 #endif
 #ifdef QT_QWS_DEPTH_4
     } else if(d==4) {
         return true;
 #endif
 #ifdef QT_QWS_DEPTH_8
     } else if(d==8) {
         return true;
 #endif
 #ifdef QT_QWS_DEPTH_16
     } else if(d==16) {
         return true;
 #endif
 #ifdef QT_QWS_DEPTH_15
     } else if (d == 15) {
         return true;
 #endif
 #ifdef QT_QWS_DEPTH_18
     } else if(d==18 || d==19) {
         return true;
 #endif
 #ifdef QT_QWS_DEPTH_24
     } else if(d==24) {
         return true;
 #endif
 #ifdef QT_QWS_DEPTH_32
     } else if(d==32) {
         return true;
 #endif
     }
     return false;
 }
totalSize()
QScreen::totalSize () const inline
Returns the size of the available graphics card memory (including the screen) in bytes.
See also
onCard()
Definition at line 243 of file qscreen_qws.h.
 { return mapsize; }
transformOrientation()
int QScreen::transformOrientation () const virtual
Returns the current rotation as an integer value.
Note that the default implementation returns 0; reimplement this function to override this value.
See also
isTransformed()
Reimplemented in QProxyScreen, and QTransformedScreen.
Definition at line 3250 of file qscreen_qws.cpp.
Referenced by QWSServerPrivate::_q_newConnection(), PvrEglScreen::transformation(), QWSKeyboardHandler::transformDirKey(), and QProxyScreen::transformOrientation().
 {
     return 0;
 }
uncache()
QScreen::uncache (uchar *) inline virtual
Warning
This function is not part of the public interface.
This function is called on pixmap destruction to remove them from graphics card memory.
Reimplemented in QLinuxFbScreen.
Definition at line 238 of file qscreen_qws.h.
 {}
width()
QScreen::width () const inline
Returns the logical width of the framebuffer in pixels.
See also
deviceWidth(), physicalWidth(), height()
Definition at line 227 of file qscreen_qws.h.
Referenced by QDirectPainter::allocatedRegion(), QWSOnScreenSurface::attachToScreen(), QProxyScreen::configure(), QMultiScreen::connect(), effectiveState(), QWSServer::endDisplayReconfigure(), qt_defaultDpiX(), qt_directpainter_embedevent(), qt_directpainter_region(), screenS(), QWSPcMouseHandlerPrivate::sendEvent(), QWSServer::setBackground(), QTransformedScreen::setDirty(), setImageMetrics(), PvrEglWindowSurface::transformRects(), QETWidget::translateMouseEvent(), QWSServerPrivate::update_regions(), and QWSDisplay::width().
 { return w; }
Friends and Related Functions
QIntfbScreen
friend class QIntfbScreen friend
Definition at line 362 of file qscreen_qws.h.
QLinuxFbScreen
friend class QLinuxFbScreen friend
Definition at line 358 of file qscreen_qws.h.
QProxyScreen
friend class QProxyScreen friend
Definition at line 361 of file qscreen_qws.h.
QQnxScreen
friend class QQnxScreen friend
Definition at line 360 of file qscreen_qws.h.
qt_blit_setup
void qt_blit_setup (QScreen * screen, const QImage & image, const QPoint & topLeft, const QRegion & region) friend
Definition at line 1217 of file qscreen_qws.cpp.
 {
     switch (screen->depth()) {
 #ifdef QT_QWS_DEPTH_32
     case 32:
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->blit = blit_32;
         else
             screen->d_ptr->blit = blit_template<qabgr8888, quint32>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_24
     case 24:
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->blit = blit_qrgb888;
         else
             screen->d_ptr->blit = blit_24;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_18
     case 18:
         screen->d_ptr->blit = blit_18;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_16
     case 16:
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
         if (screen->d_ptr->fb_is_littleEndian)
             screen->d_ptr->blit = blit_16_bigToLittleEndian;
         else
 #endif
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->blit = blit_16;
         else
             screen->d_ptr->blit = blit_template<qbgr565, quint16>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_15
     case 15:
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
         if (screen->d_ptr->fb_is_littleEndian)
             screen->d_ptr->blit = blit_15_bigToLittleEndian;
         else
 #endif // Q_BIG_ENDIAN
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->blit = blit_15;
         else
             screen->d_ptr->blit = blit_template<qbgr555, qrgb555>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_12
     case 12:
         screen->d_ptr->blit = blit_12;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_8
     case 8:
         screen->d_ptr->blit = blit_8;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_4
     case 4:
         screen->d_ptr->blit = blit_4;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_1
     case 1:
         screen->d_ptr->blit = blit_1;
         break;
 #endif
     default:
         qFatal("blit_setup(): Screen depth %d not supported!",
                screen->depth());
         screen->d_ptr->blit = 0;
         break;
     }
     screen->d_ptr->blit(screen, image, topLeft, region);
 }
qt_solidFill_setup
void qt_solidFill_setup (QScreen * screen, const QColor & color, const QRegion & region) friend
Definition at line 544 of file qscreen_qws.cpp.
 {
     switch (screen->depth()) {
 #ifdef QT_QWS_DEPTH_32
     case 32:
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->solidFill = solidFill_template<quint32>;
         else
             screen->d_ptr->solidFill = solidFill_template<qabgr8888>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_24
     case 24:
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->solidFill = solidFill_template<qrgb888>;
         else
             screen->d_ptr->solidFill = solidFill_template<quint24>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_18
     case 18:
         screen->d_ptr->solidFill = solidFill_template<quint18>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_16
     case 16:
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->solidFill = solidFill_template<quint16>;
         else
             screen->d_ptr->solidFill = solidFill_template<qbgr565>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_15
     case 15:
         if (screen->pixelType() == QScreen::NormalPixel)
             screen->d_ptr->solidFill = solidFill_template<qrgb555>;
         else
             screen->d_ptr->solidFill = solidFill_template<qbgr555>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_12
     case 12:
         screen->d_ptr->solidFill = solidFill_template<qrgb444>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_8
     case 8:
         screen->d_ptr->solidFill = solidFill_template<quint8>;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_4
     case 4:
         screen->d_ptr->solidFill = solidFill_gray4;
         break;
 #endif
 #ifdef QT_QWS_DEPTH_1
     case 1:
         screen->d_ptr->solidFill = solidFill_mono;
         break;
 #endif
      default:
         qFatal("solidFill_setup(): Screen depth %d not supported!",
                screen->depth());
         screen->d_ptr->solidFill = 0;
         break;
     }
     screen->d_ptr->solidFill(screen, color, region);
 }
QVFbScreen
friend class QVFbScreen friend
Definition at line 359 of file qscreen_qws.h.
QVNCScreen
friend class QVNCScreen friend
Definition at line 357 of file qscreen_qws.h.
QWSOnScreenSurface
friend class QWSOnScreenSurface friend
Definition at line 351 of file qscreen_qws.h.
Referenced by createSurface().
QWSServer
friend class QWSServer friend
Definition at line 342 of file qscreen_qws.h.
QWSServerPrivate
friend class QWSServerPrivate friend
Definition at line 343 of file qscreen_qws.h.
setTransformation()
void setTransformation (int transformation, int screenNo) related
Here it is.
transformation and screenNo
Definition at line 1889 of file qapplication_qws.cpp.
 {
     QWSScreenTransformCommand cmd;
     cmd.setTransformation(screenNo, transformation);
     QWSDisplay::instance()->d->sendCommand(cmd);
 }
Properties
clearCacheFunc
ClearCacheFunc QScreen::clearCacheFunc = 0 static protected
Definition at line 344 of file qscreen_qws.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QLinuxFbScreen::QLinuxFbScreen(), and QScreen().
d
QScreen::d protected
the pixel depth
This is the number of significant bits used to set a pixel color. This variable must be initialized by a subclass.
Definition at line 327 of file qscreen_qws.h.
Referenced by alloc(), QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QVNCScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), QVNCScreen::initDevice(), QVFbScreen::initDevice(), QLinuxFbScreen::QLinuxFbScreen(), QLinuxFbScreen::restore(), QProxyScreen::setMode(), and QLinuxFbScreen::setPixelFormat().
d_ptr
QScreenPrivate* QScreen::d_ptr private
Definition at line 374 of file qscreen_qws.h.
Referenced by blit(), blit_template(), classId(), compose(), frameBufferLittleEndian(), graphicsSystem(), offset(), paintBackground(), pixelFormat(), pixmapDataFactory(), qt_blit_setup(), qt_solidFill_setup(), setFrameBufferLittleEndian(), setGraphicsSystem(), setOffset(), setPixelFormat(), setPixmapDataFactory(), solidFill(), and ~QScreen().
data
QScreen::data protected
points to the first visible pixel in the frame buffer.
You must initialize this variable if you are using the default implementation of non-buffered painting Qt::WA_PaintOnScreen, QPixmap::grabWindow() or QDirectPainter::frameBuffer(). If you initialize this variable, you must also initialize QScreen::size and QScreen::mapsize.
See also
QScreen::size, QScreen::mapsize
Definition at line 311 of file qscreen_qws.h.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), QIntfbScreen::connect(), QVFbScreen::connect(), QQnxScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QDirectFBScreen::connect(), QTransformedScreen::exposeRegion(), onCard(), QIntfbScreen::QIntfbScreen(), QVFbScreen::QVFbScreen(), and QVNCScreenPrivate::~QVNCScreenPrivate().
dh
QScreen::dh protected
the device height
This is the number of pixels in a column of the physical screen. It must be initialized by a subclass. Normally, it should be set to the logical height QScreen::h, but it might be different, e.g., if you are doing rotations in software.
See also
QScreen::h
Definition at line 332 of file qscreen_qws.h.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QVNCScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), QLinuxFbScreen::setDirty(), QProxyScreen::setMode(), QTransformedScreen::setTransformation(), and solidFill().
displayId
int QScreen::displayId protected
Definition at line 337 of file qscreen_qws.h.
Referenced by QVNCScreenPrivate::configure(), QQnxScreen::connect(), QVFbScreen::connect(), QVNCScreen::connect(), QMultiScreen::connect(), QTransformedScreen::connect(), PvrEglScreenSurfaceFunctions::createNativeWindow(), PvrEglScreen::createSurface(), QVNCScreen::initDevice(), and QVFbScreen::initDevice().
dw
QScreen::dw protected
the device width
This is the number of pixels in a row of the physical screen. It must be initialized by a subclass. Normally, it should be set to the logical width QScreen::w, but it might be different, e.g., if you are doing rotations in software.
See also
QScreen::w
Definition at line 331 of file qscreen_qws.h.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QVNCScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), QLinuxFbScreen::setDirty(), QProxyScreen::setMode(), QTransformedScreen::setTransformation(), and solidFill().
entries
QPoolEntry* QScreen::entries protected
Definition at line 320 of file qscreen_qws.h.
Referenced by QLinuxFbScreen::cache(), QLinuxFbScreen::clearCache(), QLinuxFbScreen::delete_entry(), QLinuxFbScreen::deleteEntry(), QLinuxFbScreen::insert_entry(), and QLinuxFbScreen::setupOffScreen().
entryp
int* QScreen::entryp protected
Definition at line 321 of file qscreen_qws.h.
Referenced by QLinuxFbScreen::cache(), QLinuxFbScreen::clearCache(), QLinuxFbScreen::delete_entry(), QLinuxFbScreen::initDevice(), QLinuxFbScreen::insert_entry(), and QLinuxFbScreen::setupOffScreen().
grayscale
QScreen::grayscale protected
the gray scale screen mode flag
Set this variable to true in a subclass, if you are using a grayscale screen mode. e.g., in an 8-bit mode where you don't want to use the palette, but you want to use the grayscales.
Definition at line 329 of file qscreen_qws.h.
Referenced by alloc(), QVFbScreen::connect(), QLinuxFbScreen::connect(), QLinuxFbScreen::createPalette(), QVFbScreen::initDevice(), and QLinuxFbScreen::initDevice().
h
QScreen::h protected
the logical height of the screen.
This variable must be initialized by a subclass.
Definition at line 326 of file qscreen_qws.h.
Referenced by blendCursor(), QTransformedScreen::blit(), QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QVNCScreen::connect(), QVFbScreen::connect(), QQnxScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), QTransformedScreen::mapFromDevice(), QTransformedScreen::mapToDevice(), QProxyScreen::setMode(), QTransformedScreen::setTransformation(), and QTransformedScreen::solidFill().
lowest
unsigned int* QScreen::lowest protected
Definition at line 322 of file qscreen_qws.h.
Referenced by QLinuxFbScreen::cache(), QLinuxFbScreen::delete_entry(), QLinuxFbScreen::initDevice(), QLinuxFbScreen::insert_entry(), and QLinuxFbScreen::setupOffScreen().
lstep
QScreen::lstep protected
the number of bytes representing a line in the frame buffer.
i.e., line step. {data[lstep * 2]} is the address of the first visible pixel in the third line of the frame buffer.
See also
data
Definition at line 325 of file qscreen_qws.h.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), QIntfbScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), and QLinuxFbScreen::QLinuxFbScreen().
mapsize
QScreen::mapsize protected
the total number of bytes in the frame buffer
This is the total number of bytes in the block pointed to by the QScreen::data pointer. You must initialize this variable if you initialize the QScreen::data pointer.
See also
QScreen::data, QScreen::size
Definition at line 335 of file qscreen_qws.h.
Referenced by QVNCScreenPrivate::configure(), QIntfbScreen::connect(), QVFbScreen::connect(), QQnxScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QLinuxFbScreen::disconnect(), QLinuxFbScreen::initDevice(), onCard(), and QLinuxFbScreen::useOffscreen().
physHeight
QScreen::physHeight protected
the physical height of the screen in millimeters.
Currently, this variable is used when calculating the screen DPI, which in turn is used when deciding the actual font size Qt is using.
Definition at line 340 of file qscreen_qws.h.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), and QTransformedScreen::setTransformation().
physWidth
QScreen::physWidth protected
the physical width of the screen in millimeters.
Currently, this variable is used when calculating the screen DPI, which in turn is used when deciding the actual font size Qt is using.
Definition at line 339 of file qscreen_qws.h.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), and QTransformedScreen::setTransformation().
pixeltype
QScreen::pixeltype protected
set to BGRPixel
Set this variable to BGRPixel in a subclass, if the screen pixel format is a BGR type and you have used setPixelFormat() to set the pixel format to the corresponding RGB format. e.g., you have set the pixel format to QImage::Format_RGB555, but your screen really uses BGR, not RGB.
Definition at line 328 of file qscreen_qws.h.
Referenced by QProxyScreen::configure(), QVFbScreen::connect(), QQnxScreen::connect(), and QLinuxFbScreen::setPixelFormat().
screenclut
QScreen::screenclut protected
the color table
Initialize this variable in a subclass using a paletted screen mode, and initialize its partner, QScreen::screencols.
See also
screencols
Definition at line 308 of file qscreen_qws.h.
Referenced by alloc(), QVFbScreen::connect(), QLinuxFbScreen::connect(), QLinuxFbScreen::createPalette(), QVFbScreen::initDevice(), QVNCScreen::initDevice(), QLinuxFbScreen::restore(), and QLinuxFbScreen::set().
screencols
QScreen::screencols protected
the number of entries in the color table
Initialize this variable in a subclass using a paletted screen mode, and initialize its partner, QScreen::screenclut.
See also
screenclut
Definition at line 309 of file qscreen_qws.h.
Referenced by alloc(), QVFbScreen::connect(), QLinuxFbScreen::connect(), QLinuxFbScreen::createPalette(), QVFbScreen::initDevice(), QVNCScreen::initDevice(), QLinuxFbScreen::initDevice(), and QLinuxFbScreen::restore().
size
QScreen::size protected
the number of bytes in the visible region of the frame buffer
This is the number of bytes in the visible part of the block pointed to by the QScreen::data pointer. You must initialize this variable if you initialize the QScreen::data pointer.
See also
QScreen::data, QScreen::mapsize
Definition at line 334 of file qscreen_qws.h.
Referenced by QAhiScreen::configure(), QProxyScreen::configure(), QVNCScreenPrivate::configure(), QIntfbScreen::connect(), QQnxScreen::connect(), QVFbScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), QLinuxFbScreen::delete_entry(), QLinuxFbScreen::initDevice(), QLinuxFbScreen::insert_entry(), isFullUpdate(), QTransformedScreen::mapFromDevice(), QTransformedScreen::mapToDevice(), QVNCScreen::QVNCScreen(), QTransformedScreen::setTransformation(), QLinuxFbScreen::setupOffScreen(), and QLinuxFbScreen::useOffscreen().
w
QScreen::w protected
the logical width of the screen.
This variable must be initialized by a subclass.
Definition at line 324 of file qscreen_qws.h.
Referenced by blendCursor(), QTransformedScreen::blit(), QAhiScreen::configure(), QProxyScreen::configure(), EGLNullWSScreen::connect(), QIntfbScreen::connect(), QVNCScreen::connect(), QVFbScreen::connect(), QQnxScreen::connect(), QMultiScreen::connect(), PvrEglScreen::connect(), QLinuxFbScreen::connect(), QDirectFBScreen::connect(), QTransformedScreen::mapFromDevice(), QTransformedScreen::mapToDevice(), QProxyScreen::setMode(), QTransformedScreen::setTransformation(), and QTransformedScreen::solidFill().
The documentation for this class was generated from the following files:
/src/gui/embedded/qscreen_qws.h
/src/gui/embedded/qscreen_qws.cpp
/src/gui/kernel/qapplication_qws.cpp