Qt 4.8: QContextMenuEvent Class Reference
QContextMenuEvent Class Reference
The QContextMenuEvent class contains parameters that describe a context menu event.
#include <qevent.h>
Public Types
enum Reason { Mouse, Keyboard, Other }
This enum describes the reason why the event was sent.
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Public Functions
const QPoint & globalPos () const
Returns the global position of the mouse pointer at the time of the event.
int globalX () const
Returns the global x position of the mouse pointer at the time of the event.
int globalY () const
Returns the global y position of the mouse pointer at the time of the event.
const QPoint & pos () const
Returns the position of the mouse pointer relative to the widget that received the event.
QContextMenuEvent (Reason reason, const QPoint &pos, const QPoint &globalPos, Qt::KeyboardModifiers modifiers)
Constructs a context menu event object with the accept parameter flag set to false.
QContextMenuEvent (Reason reason, const QPoint &pos, const QPoint &globalPos)
Constructs a context menu event object with the accept parameter flag set to false.
QContextMenuEvent (Reason reason, const QPoint &pos)
Constructs a context menu event object with the accept parameter flag set to false.
Reason reason () const
Returns the reason for this context event.
int x () const
Returns the x position of the mouse pointer, relative to the widget that received the event.
int y () const
Returns the y position of the mouse pointer, relative to the widget that received the event.
~QContextMenuEvent ()
Public Functions inherited from QInputEvent
Qt::KeyboardModifiers modifiers () const
Returns the keyboard modifier flags that existed immediately before the event occurred.
QInputEvent (Type type, Qt::KeyboardModifiers modifiers=Qt::NoModifier)
void setModifiers (Qt::KeyboardModifiers amodifiers)
Sets the keyboard modifiers flags for this event.
~QInputEvent ()
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Protected Variables
QPoint gp
QPoint p
uint reas: 8
Protected Variables inherited from QInputEvent
Qt::KeyboardModifiers modState
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Additional Inherited Members
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Detailed Description
The QContextMenuEvent class contains parameters that describe a context menu event.
Context menu events are sent to widgets when a user performs an action associated with opening a context menu. The actions required to open context menus vary between platforms; for example, on Windows, pressing the menu button or clicking the right mouse button will cause this event to be sent.
When this event occurs it is customary to show a QMenu with a context menu, if this is relevant to the context.
Context menu events contain a special accept flag that indicates whether the receiver accepted the event. If the event handler does not accept the event then, if possible, whatever triggered the event will be handled as a regular input event.
Definition at line 396 of file qevent.h.
Enumerations
Reason
enum QContextMenuEvent::Reason
This enum describes the reason why the event was sent.
Mouse The mouse caused the event to be sent. Normally this means the right mouse button was clicked, but this is platform dependent.
Keyboard The keyboard caused this event to be sent. On Windows, this means the menu button was pressed.
Other The event was sent by some other means (i.e. not by the mouse or keyboard).
Enumerator
Mouse
Keyboard
Other
Definition at line 399 of file qevent.h.
 { Mouse, Keyboard, Other };
Constructors and Destructors
QContextMenuEvent() [1/3]
QContextMenuEvent::QContextMenuEvent (Reason reason, const QPoint & pos, const QPoint & globalPos, Qt::KeyboardModifiers modifiers)
Constructs a context menu event object with the accept parameter flag set to false.
The reason parameter must be QContextMenuEvent::Mouse or QContextMenuEvent::Keyboard.
The pos parameter specifies the mouse position relative to the receiving widget. globalPos is the mouse position in absolute coordinates. The modifiers holds the keyboard modifiers.
Definition at line 1629 of file qevent.cpp.
Referenced by QContextMenuEvent().
     : QInputEvent(ContextMenu, modifiers), p(pos), gp(globalPos), reas(reason)
 {}
QContextMenuEvent() [2/3]
QContextMenuEvent::QContextMenuEvent (Reason reason, const QPoint & pos, const QPoint & globalPos)
Constructs a context menu event object with the accept parameter flag set to false.
The reason parameter must be QContextMenuEvent::Mouse or QContextMenuEvent::Keyboard.
The pos parameter specifies the mouse position relative to the receiving widget. globalPos is the mouse position in absolute coordinates.
Definition at line 1614 of file qevent.cpp.
     : QInputEvent(ContextMenu), p(pos), gp(globalPos), reas(reason)
 {}
QContextMenuEvent() [3/3]
QContextMenuEvent::QContextMenuEvent (Reason reason, const QPoint & pos)
Constructs a context menu event object with the accept parameter flag set to false.
The reason parameter must be QContextMenuEvent::Mouse or QContextMenuEvent::Keyboard.
The pos parameter specifies the mouse position relative to the receiving widget.
The globalPos() is initialized to QCursor::pos(), which may not be appropriate. Use the other constructor to specify the global position explicitly.
Definition at line 1664 of file qevent.cpp.
     : QInputEvent(ContextMenu), p(pos), reas(reason)
 {
     gp = QCursor::pos();
 }
~QContextMenuEvent()
QContextMenuEvent::~QContextMenuEvent ()
Warning
This function is not part of the public interface.
Definition at line 1647 of file qevent.cpp.
 {
 }
Functions
globalPos()
const QPoint & QContextMenuEvent::globalPos () const inline
Returns the global position of the mouse pointer at the time of the event.
See also
x(), y(), pos()
Definition at line 413 of file qevent.h.
Referenced by QmlJSDebugger::ToolBarColorBox::contextMenuEvent(), QScrollBar::contextMenuEvent(), QMessageBoxDetailsText::TextEdit::contextMenuEvent(), QDialog::contextMenuEvent(), QMdiSubWindow::contextMenuEvent(), QAbstractSpinBox::contextMenuEvent(), QLabel::contextMenuEvent(), QMainWindow::contextMenuEvent(), QLineEdit::contextMenuEvent(), QWorkspaceTitleBar::contextMenuEvent(), QMdiAreaTabBar::contextMenuEvent(), QApplication::notify(), and QTextControl::processEvent().
 { return gp; }
globalX()
int QContextMenuEvent::globalX () const inline
Returns the global x position of the mouse pointer at the time of the event.
See also
globalY(), globalPos()
Definition at line 409 of file qevent.h.
 { return gp.x(); }
globalY()
int QContextMenuEvent::globalY () const inline
Returns the global y position of the mouse pointer at the time of the event.
See also
globalX(), globalPos()
Definition at line 410 of file qevent.h.
 { return gp.y(); }
pos()
const QPoint & QContextMenuEvent::pos () const inline
Returns the position of the mouse pointer relative to the widget that received the event.
See also
x(), y(), globalPos()
Definition at line 412 of file qevent.h.
Referenced by QScrollBar::contextMenuEvent(), QDialog::contextMenuEvent(), QMdiSubWindow::contextMenuEvent(), QAbstractSpinBox::contextMenuEvent(), QLabel::contextMenuEvent(), QMainWindow::contextMenuEvent(), QWorkspaceTitleBar::contextMenuEvent(), QMdiAreaTabBar::contextMenuEvent(), QToolBar::event(), QApplication::notify(), and QTextControl::processEvent().
 { return p; }
reason()
QContextMenuEvent::Reason QContextMenuEvent::reason () const inline
Returns the reason for this context event.
Definition at line 415 of file qevent.h.
Referenced by QGraphicsView::contextMenuEvent(), QApplication::notify(), and QContextMenuEvent().
 { return Reason(reas); }
x()
int QContextMenuEvent::x () const inline
Returns the x position of the mouse pointer, relative to the widget that received the event.
See also
y(), pos()
Definition at line 407 of file qevent.h.
 { return p.x(); }
y()
int QContextMenuEvent::y () const inline
Returns the y position of the mouse pointer, relative to the widget that received the event.
See also
x(), pos()
Definition at line 408 of file qevent.h.
 { return p.y(); }
Properties
gp
QPoint QContextMenuEvent::gp protected
Definition at line 425 of file qevent.h.
Referenced by QContextMenuEvent().
p
QPoint QContextMenuEvent::p protected
Definition at line 424 of file qevent.h.
Referenced by QContextMenuEvent().
reas
uint QContextMenuEvent::reas protected
Definition at line 426 of file qevent.h.
Referenced by QContextMenuEvent().
The documentation for this class was generated from the following files:
/src/gui/kernel/qevent.h
/src/gui/kernel/qevent.cpp