Qt 4.8: QGLScreenSurfaceFunctions Class Reference
QGLScreenSurfaceFunctions Class Reference
The QGLScreenSurfaceFunctions class encapsulates the functions for creating native windows and pixmaps for OpenGL ES.
#include <qglscreen_qws.h>
Public Functions
virtual bool createNativeImage (QImage *image, EGLNativePixmapType *native)
Creates a native OpenGLES drawable for directly rendering into image and returns it in native.
virtual bool createNativePixmap (QPixmap *pixmap, EGLNativePixmapType *native)
Creates a native OpenGLES drawable for directly rendering into pixmap and returns it in native.
virtual bool createNativeWindow (QWidget *widget, EGLNativeWindowType *native)
Creates a native OpenGLES drawable for the surface of widget and returns it in native.
Detailed Description
The QGLScreenSurfaceFunctions class encapsulates the functions for creating native windows and pixmaps for OpenGL ES.
Warning
This function is not part of the public interface. This function is under development and subject to change.
Definition at line 81 of file qglscreen_qws.h.
Functions
createNativeImage()
bool QGLScreenSurfaceFunctions::createNativeImage (QImage * image, EGLNativePixmapType * native) virtual
Creates a native OpenGLES drawable for directly rendering into image and returns it in native.
Since
4.4.2
Returns true if the OpenGLES drawable could be created, or false if direct rendering into images is not supported.
This function will be called if the NativeImages option is set on the screen.
See also
createNativeWindow(), createNativePixmap(), QGLScreen::options()
Definition at line 268 of file qglscreen_qws.cpp.
Referenced by qt_egl_create_surface().
 {
     Q_UNUSED(image);
     Q_UNUSED(native);
     return false;
 }
createNativePixmap()
bool QGLScreenSurfaceFunctions::createNativePixmap (QPixmap * pixmap, EGLNativePixmapType * native) virtual
Creates a native OpenGLES drawable for directly rendering into pixmap and returns it in native.
Since
4.4.2
Returns true if the OpenGLES drawable could be created, or false if direct rendering into pixmaps is not supported.
This function will be called if the NativePixmaps option is set on the screen.
See also
createNativeWindow(), createNativeImage(), QGLScreen::options()
Definition at line 245 of file qglscreen_qws.cpp.
Referenced by qt_egl_create_surface().
 {
     Q_UNUSED(pixmap);
     Q_UNUSED(native);
     return false;
 }
createNativeWindow()
bool QGLScreenSurfaceFunctions::createNativeWindow (QWidget * widget, EGLNativeWindowType * native) virtual
Creates a native OpenGLES drawable for the surface of widget and returns it in native.
Since
4.4.2
Returns true if the OpenGLES drawable could be created, or false if windows are not supported.
This function will be called if the NativeWindows option is set on the screen.
See also
createNativePixmap(), createNativeImage(), QGLScreen::options()
Reimplemented in PvrEglScreenSurfaceFunctions.
Definition at line 222 of file qglscreen_qws.cpp.
Referenced by qt_egl_create_surface().
 {
     Q_UNUSED(widget);
     Q_UNUSED(native);
     return false;
 }
The documentation for this class was generated from the following files:
/src/opengl/qglscreen_qws.h
/src/opengl/qglscreen_qws.cpp