Qt 4.8: QPatternist::XsdIdentityConstraint Class Reference
QPatternist::XsdIdentityConstraint Class Reference
XML Schema Processing
Represents a XSD identity constraint object.
#include <qxsdidentityconstraint_p.h>
Public Types
enum Category { Key = 1, KeyReference, Unique }
typedef QList< XsdIdentityConstraint::Ptr > List
typedef QExplicitlySharedDataPointer< XsdIdentityConstraint > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
void addField (const XsdXPathExpression::Ptr &field)
Category category () const
XsdXPathExpression::List fields () const
XsdIdentityConstraint::Ptr referencedKey () const
XsdXPathExpression::Ptr selector () const
void setCategory (Category category)
void setFields (const XsdXPathExpression::List &fields)
void setReferencedKey (const XsdIdentityConstraint::Ptr &key)
void setSelector (const XsdXPathExpression::Ptr &selector)
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
Category m_category
XsdXPathExpression::List m_fields
XsdIdentityConstraint::Ptr m_referencedKey
XsdXPathExpression::Ptr m_selector
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents a XSD identity constraint object.
This class represents the identity constraint object of a XML schema as described here.
It contains information from either a key object, a keyref object or an unique object.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 80 of file qxsdidentityconstraint_p.h.
Typedefs
List
typedef QList<XsdIdentityConstraint::Ptr> QPatternist::XsdIdentityConstraint::List
Definition at line 84 of file qxsdidentityconstraint_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdIdentityConstraint> QPatternist::XsdIdentityConstraint::Ptr
Definition at line 83 of file qxsdidentityconstraint_p.h.
Enumerations
Category
enum QPatternist::XsdIdentityConstraint::Category
Describes the category of the identity constraint.
Enumerator
Key
The constraint is a key constraint.
KeyReference
The constraint is a keyref constraint.
Unique
The constraint is an unique constraint.
Definition at line 89 of file qxsdidentityconstraint_p.h.
             {
                 Key = 1,
                 KeyReference,
                 Unique
             };
Functions
addField()
void XsdIdentityConstraint::addField (const XsdXPathExpression::Ptr & field)
Adds a new field to the identity constraint.
Definition at line 73 of file qxsdidentityconstraint.cpp.
Referenced by QPatternist::XsdSchemaParser::parseField().
 {
     m_fields.append(field);
 }
category()
XsdIdentityConstraint::Category XsdIdentityConstraint::category () const
Returns the category of the identity constraint.
Definition at line 53 of file qxsdidentityconstraint.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveKeyReferences(), setCategory(), and QPatternist::XsdValidatingInstanceReader::validateIdentityConstraint().
 {
     return m_category;
 }
fields()
XsdXPathExpression::List XsdIdentityConstraint::fields () const
Returns all fields of the identity constraint.
Definition at line 78 of file qxsdidentityconstraint.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveKeyReferences(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), and setFields().
 {
     return m_fields;
 }
referencedKey()
XsdIdentityConstraint::Ptr XsdIdentityConstraint::referencedKey () const
Returns the referenced key of the identity constraint or an empty pointer if its type is not KeyReference.
Definition at line 88 of file qxsdidentityconstraint.cpp.
Referenced by setReferencedKey(), and QPatternist::XsdValidatingInstanceReader::validateKeyRefIdentityConstraint().
 {
     return m_referencedKey;
 }
selector()
XsdXPathExpression::Ptr XsdIdentityConstraint::selector () const
Returns the selector of the identity constraint.
Definition at line 63 of file qxsdidentityconstraint.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::selectNodeSets(), and setSelector().
 {
     return m_selector;
 }
setCategory()
void XsdIdentityConstraint::setCategory (Category category)
Sets the category of the identity constraint.
See also
Category
Definition at line 48 of file qxsdidentityconstraint.cpp.
Referenced by QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), and QPatternist::XsdSchemaParser::parseUnique().
 {
     m_category = category;
 }
setFields()
void XsdIdentityConstraint::setFields (const XsdXPathExpression::List & fields)
Sets the fields of the identity constraint.
Each field is a restricted XPath 1.0 expression, that selects a set of nodes.
See also
Definition at line 68 of file qxsdidentityconstraint.cpp.
 {
     m_fields = fields;
 }
setReferencedKey()
void XsdIdentityConstraint::setReferencedKey (const XsdIdentityConstraint::Ptr & key)
Sets the referenced key of the identity constraint.
The key points to a identity constraint of type Key or Unique.
The identity constraint has only a referenced key if its type is KeyReference.
See also
Definition at line 83 of file qxsdidentityconstraint.cpp.
Referenced by QPatternist::XsdSchemaResolver::resolveKeyReferences().
 {
     m_referencedKey = referencedKey;
 }
setSelector()
void XsdIdentityConstraint::setSelector (const XsdXPathExpression::Ptr & selector)
Sets the selector of the identity constraint.
The selector is a restricted XPath 1.0 expression, that selects a set of nodes.
See also
Definition at line 58 of file qxsdidentityconstraint.cpp.
Referenced by QPatternist::XsdSchemaParser::parseSelector().
 {
     m_selector = selector;
 }
Properties
m_category
Category QPatternist::XsdIdentityConstraint::m_category private
Definition at line 162 of file qxsdidentityconstraint_p.h.
Referenced by category(), and setCategory().
m_fields
XsdXPathExpression::List QPatternist::XsdIdentityConstraint::m_fields private
Definition at line 164 of file qxsdidentityconstraint_p.h.
Referenced by addField(), fields(), and setFields().
m_referencedKey
XsdIdentityConstraint::Ptr QPatternist::XsdIdentityConstraint::m_referencedKey private
Definition at line 165 of file qxsdidentityconstraint_p.h.
Referenced by referencedKey(), and setReferencedKey().
m_selector
XsdXPathExpression::Ptr QPatternist::XsdIdentityConstraint::m_selector private
Definition at line 163 of file qxsdidentityconstraint_p.h.
Referenced by selector(), and setSelector().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdidentityconstraint_p.h
/src/xmlpatterns/schema/qxsdidentityconstraint.cpp