Qt 4.8: QGraphicsSystemFactory Class Reference
QGraphicsSystemFactory Class Reference
#include <qgraphicssystemfactory_p.h>
Static Public Functions
static QGraphicsSystem * create (const QString &)
static QStringList keys ()
Returns the list of valid keys, i.e.
Detailed Description
Definition at line 66 of file qgraphicssystemfactory_p.h.
Functions
create()
static QGraphicsSystem* QGraphicsSystemFactory::create (const QString &) static
Referenced by QApplicationPrivate::initialize(), QRuntimeGraphicsSystem::QRuntimeGraphicsSystem(), qt_init(), and QRuntimeGraphicsSystem::setGraphicsSystem().
keys()
QStringList QGraphicsSystemFactory::keys () static
Returns the list of valid keys, i.e.
the keys this factory can create styles for.
See also
create()
Definition at line 108 of file qgraphicssystemfactory.cpp.
 {
 #ifndef QT_NO_LIBRARY
     QStringList list = loader()->keys();
 #else
     QStringList list;
 #endif
     if (!list.contains(QLatin1String("Raster")))
         list << QLatin1String("raster");
     return list;
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qgraphicssystemfactory_p.h
/src/gui/painting/qgraphicssystemfactory.cpp