Qt 4.8: QClipboardWatcher Class Reference
QClipboardWatcher Class Reference
Public Functions
bool empty () const
QStringList formats_sys () const
virtual QStringList formats_sys () const
QByteArray getDataInFormat (Atom fmtatom) const
bool hasFormat_sys (const QString &mimetype) const
virtual bool hasFormat_sys (const QString &mimetype) const
QClipboardWatcher ()
QClipboardWatcher (QClipboard::Mode mode)
QVariant retrieveData_sys (const QString &mimetype, QVariant::Type preferredType) const
QVariant retrieveData_sys (const QString &mimetype, QVariant::Type type) const
~QClipboardWatcher ()
Public Functions inherited from QInternalMimeData
QStringList formats () const
Returns a list of formats supported by the object.
bool hasFormat (const QString &mimeType) const
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
QInternalMimeData ()
~QInternalMimeData ()
Public Functions inherited from QMimeData
void clear ()
Removes all the MIME type and data entries in the object.
QVariant colorData () const
Returns a color if the data stored in the object represents a color (MIME type application/x-color); otherwise returns a null variant.
QByteArray data (const QString &mimetype) const
Returns the data stored in the object in the format described by the MIME type specified by mimeType.
bool hasColor () const
Returns true if the object can return a color (MIME type application/x-color); otherwise returns false.
bool hasHtml () const
Returns true if the object can return HTML (MIME type text/html); otherwise returns false.
bool hasImage () const
Returns true if the object can return an image; otherwise returns false.
bool hasText () const
Returns true if the object can return plain text (MIME type text/plain); otherwise returns false.
bool hasUrls () const
Returns true if the object can return a list of urls; otherwise returns false.
QString html () const
Returns a string if the data stored in the object is HTML (MIME type text/html); otherwise returns an empty string.
QVariant imageData () const
Returns a QVariant storing a QImage if the object can return an image; otherwise returns a null variant.
QMimeData ()
Constructs a new MIME data object with no data in it.
void removeFormat (const QString &mimetype)
Removes the data entry for mimeType in the object.
void setColorData (const QVariant &color)
Sets the color data in the object to the given color.
void setData (const QString &mimetype, const QByteArray &data)
Sets the data associated with the MIME type given by mimeType to the specified data.
void setHtml (const QString &html)
Sets html as the HTML (MIME type text/html) used to represent the data.
void setImageData (const QVariant &image)
Sets the data in the object to the given image.
void setText (const QString &text)
Sets text as the plain text (MIME type text/plain) used to represent the data.
void setUrls (const QList< QUrl > &urls)
Sets the URLs stored in the MIME data object to those specified by urls.
QString text () const
Returns a plain text (MIME type text/plain) representation of the data.
QList< QUrl > urls () const
Returns a list of URLs contained within the MIME data object.
~QMimeData ()
Destroys the MIME data object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
Atom atom
QByteArray format_atoms
QStringList formatList
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QInternalMimeData
static bool canReadData (const QString &mimeType)
static QStringList formatsHelper (const QMimeData *data)
static bool hasFormatHelper (const QString &mimeType, const QMimeData *data)
static QByteArray renderDataHelper (const QString &mimeType, const QMimeData *data)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QInternalMimeData
QVariant retrieveData (const QString &mimeType, QVariant::Type type) const
Returns a variant with the given type containing data for the MIME type specified by mimeType.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 78 of file qclipboard_win.cpp.
Constructors and Destructors
QClipboardWatcher() [1/2]
QClipboardWatcher::QClipboardWatcher () inline
Definition at line 80 of file qclipboard_win.cpp.
Referenced by getDataInFormat(), and setupOwner().
         : QInternalMimeData()
     {
     }
QClipboardWatcher() [2/2]
QClipboardWatcher::QClipboardWatcher (QClipboard::Mode mode)
Definition at line 1169 of file qclipboard_x11.cpp.
     : QInternalMimeData()
 {
     switch (mode) {
     case QClipboard::Selection:
         atom = XA_PRIMARY;
         break;
     case QClipboard::Clipboard:
         atom = ATOM(CLIPBOARD);
         break;
     default:
         qWarning("QClipboardWatcher: Internal error: Unsupported clipboard mode");
         break;
     }
     setupOwner();
 }
~QClipboardWatcher()
QClipboardWatcher::~QClipboardWatcher ()
Definition at line 1189 of file qclipboard_x11.cpp.
Referenced by setupOwner().
 {
     if(selection_watcher == this)
         selection_watcher = 0;
     if(clipboard_watcher == this)
         clipboard_watcher = 0;
 }
Functions
empty()
bool QClipboardWatcher::empty () const
Definition at line 1197 of file qclipboard_x11.cpp.
Referenced by setupOwner().
 {
     Display *dpy = X11->display;
     Window win = XGetSelectionOwner(dpy, atom);
     if(win == requestor->internalWinId()) {
         qWarning("QClipboardWatcher::empty: Internal error: Application owns the selection");
         return true;
     }
     return win == XNone;
 }
formats_sys() [1/2]
QStringList QClipboardWatcher::formats_sys () const virtual
Implements QInternalMimeData.
Definition at line 105 of file qclipboard_win.cpp.
Referenced by empty(), QClipboardWatcher(), and setupOwner().
 {
     QStringList fmts;
     IDataObject * pDataObj = 0;
     if (OleGetClipboard(&pDataObj) != S_OK && !pDataObj) // Sanity
         return QStringList();
     fmts = QWindowsMime::allMimesForFormats(pDataObj);
     pDataObj->Release();
     return fmts;
 }
formats_sys() [2/2]
virtual QStringList QClipboardWatcher::formats_sys () const virtual
Implements QInternalMimeData.
getDataInFormat()
QByteArray QClipboardWatcher::getDataInFormat (Atom fmtatom) const
Definition at line 1274 of file qclipboard_x11.cpp.
Referenced by empty(), and setupOwner().
 {
     QByteArray buf;
     Display *dpy = X11->display;
     requestor->createWinId();
     Window   win = requestor->internalWinId();
     Q_ASSERT(requestor->testAttribute(Qt::WA_WState_Created));
     DEBUG("QClipboardWatcher::getDataInFormat: selection '%s' format '%s'",
           X11->xdndAtomToString(atom).data(), X11->xdndAtomToString(fmtatom).data());
     XSelectInput(dpy, win, NoEventMask); // don't listen for any events
     XDeleteProperty(dpy, win, ATOM(_QT_SELECTION));
     XConvertSelection(dpy, atom, fmtatom, ATOM(_QT_SELECTION), win, X11->time);
     XSync(dpy, false);
     VDEBUG("QClipboardWatcher::getDataInFormat: waiting for SelectionNotify event");
     XEvent xevent;
     if (!X11->clipboardWaitForEvent(win,SelectionNotify,&xevent,clipboard_timeout) ||
          xevent.xselection.property == XNone) {
         DEBUG("QClipboardWatcher::getDataInFormat: format not available");
         return buf;
     }
     VDEBUG("QClipboardWatcher::getDataInFormat: fetching data...");
     Atom   type;
     XSelectInput(dpy, win, PropertyChangeMask);
     if (X11->clipboardReadProperty(win, ATOM(_QT_SELECTION), true, &buf, 0, &type, 0)) {
         if (type == ATOM(INCR)) {
             int nbytes = buf.size() >= 4 ? *((int*)buf.data()) : 0;
             buf = X11->clipboardReadIncrementalProperty(win, ATOM(_QT_SELECTION), nbytes, false);
         }
     }
     XSelectInput(dpy, win, NoEventMask);
     DEBUG("QClipboardWatcher::getDataInFormat: %d bytes received", buf.size());
     return buf;
 }
hasFormat_sys() [1/2]
bool QClipboardWatcher::hasFormat_sys (const QString & mimetype) const virtual
Implements QInternalMimeData.
Definition at line 91 of file qclipboard_win.cpp.
Referenced by empty(), QClipboardWatcher(), and setupOwner().
 {
     IDataObject * pDataObj = 0;
     if (OleGetClipboard(&pDataObj) != S_OK && !pDataObj) // Sanity
         return false;
     bool has = QWindowsMime::converterToMime(mime, pDataObj) != 0;
     pDataObj->Release();
     return has;
 }
hasFormat_sys() [2/2]
virtual bool QClipboardWatcher::hasFormat_sys (const QString & mimetype) const virtual
Implements QInternalMimeData.
retrieveData_sys() [1/2]
QVariant QClipboardWatcher::retrieveData_sys (const QString & mimetype, QVariant::Type preferredType) const virtual
Implements QInternalMimeData.
Definition at line 120 of file qclipboard_win.cpp.
Referenced by empty(), QClipboardWatcher(), and setupOwner().
 {
     QVariant result;
     IDataObject * pDataObj = 0;
     if (OleGetClipboard(&pDataObj) != S_OK && !pDataObj) // Sanity
         return result;
     QWindowsMime *converter = QWindowsMime::converterToMime(mimeType, pDataObj);
     if (converter)
         result = converter->convertToMime(mimeType, pDataObj, type);
     pDataObj->Release();
     return result;
 }
retrieveData_sys() [2/2]
QVariant QClipboardWatcher::retrieveData_sys (const QString & mimetype, QVariant::Type type) const virtual
Implements QInternalMimeData.
Properties
atom
Atom QClipboardWatcher::atom
Definition at line 155 of file qclipboard_x11.cpp.
Referenced by empty(), getDataInFormat(), and QClipboardWatcher().
format_atoms
QByteArray QClipboardWatcher::format_atoms mutable
Definition at line 157 of file qclipboard_x11.cpp.
Referenced by empty().
formatList
QStringList QClipboardWatcher::formatList mutable
Definition at line 156 of file qclipboard_x11.cpp.
Referenced by empty().
The documentation for this class was generated from the following files:
/src/gui/kernel/qclipboard_win.cpp
/src/gui/kernel/qclipboard_x11.cpp