Qt 4.8: QWidgetBackingStoreTracker Class Reference
QWidgetBackingStoreTracker Class Reference
Class which allows tracking of which widgets are using a given backing store.
#include <qwidget_p.h>
Public Functions
void create (QWidget *tlw)
Destroy the contained QWidgetBackingStore, if not null, and clear the list of widgets using the backing store, then create a new QWidgetBackingStore, providing the QWidget.
QWidgetBackingStore * data ()
void destroy ()
Destroy the contained QWidgetBackingStore, if not null, and clear the list of widgets using the backing store.
operator bool () const
QWidgetBackingStore & operator* ()
QWidgetBackingStore * operator-> ()
QWidgetBackingStoreTracker ()
void registerWidget (QWidget *w)
Add the widget to the list of widgets currently using the backing store.
void unregisterWidget (QWidget *w)
Remove the widget from the list of widgets currently using the backing store.
void unregisterWidgetSubtree (QWidget *w)
Recursively remove widget and all of its descendents.
~QWidgetBackingStoreTracker ()
Properties
QWidgetBackingStore * m_ptr
QSet< QWidget * > m_widgets
Detailed Description
Class which allows tracking of which widgets are using a given backing store.
Warning
This function is not part of the public interface.
QWidgetBackingStoreTracker is a thin wrapper around a QWidgetBackingStore pointer, which maintains a list of the QWidgets which are currently using the backing store. This list is modified via the registerWidget and unregisterWidget functions.
Definition at line 118 of file qwidget_p.h.
Constructors and Destructors
QWidgetBackingStoreTracker()
QWidgetBackingStoreTracker::QWidgetBackingStoreTracker ()
Definition at line 198 of file qwidget.cpp.
     :   m_ptr(0)
 {
 }
~QWidgetBackingStoreTracker()
QWidgetBackingStoreTracker::~QWidgetBackingStoreTracker ()
Definition at line 204 of file qwidget.cpp.
 {
     delete m_ptr;
 }
Functions
create()
void QWidgetBackingStoreTracker::create (QWidget * widget)
Destroy the contained QWidgetBackingStore, if not null, and clear the list of widgets using the backing store, then create a new QWidgetBackingStore, providing the QWidget.
Warning
This function is not part of the public interface.
Definition at line 218 of file qwidget.cpp.
 {
     destroy();
     m_ptr = new QWidgetBackingStore(widget);
 }
data()
QWidgetBackingStore* QWidgetBackingStoreTracker::data () inline
Definition at line 132 of file qwidget_p.h.
Referenced by QWidgetPrivate::maybeBackingStore(), QWidgetPrivate::moveRect(), and QWidgetPrivate::scrollRect().
     {
         return m_ptr;
     }
destroy()
void QWidgetBackingStoreTracker::destroy ()
Destroy the contained QWidgetBackingStore, if not null, and clear the list of widgets using the backing store.
Warning
This function is not part of the public interface.
Definition at line 232 of file qwidget.cpp.
Referenced by create().
 {
     delete m_ptr;
     m_ptr = 0;
     m_widgets.clear();
 }
operator bool()
QWidgetBackingStoreTracker::operator bool () const inline
Definition at line 147 of file qwidget_p.h.
     {
         return (0 != m_ptr);
     }
operator*()
QWidgetBackingStore& QWidgetBackingStoreTracker::operator* () inline
Definition at line 142 of file qwidget_p.h.
     {
         return *m_ptr;
     }
operator->()
QWidgetBackingStore* QWidgetBackingStoreTracker::operator-> () inline
Definition at line 137 of file qwidget_p.h.
     {
         return m_ptr;
     }
registerWidget()
void QWidgetBackingStoreTracker::registerWidget (QWidget * w)
Add the widget to the list of widgets currently using the backing store.
Warning
This function is not part of the public interface.
If the widget was already in the list, this function is a no-op.
Definition at line 247 of file qwidget.cpp.
 {
     Q_ASSERT(m_ptr);
     Q_ASSERT(w->internalWinId());
     Q_ASSERT(qt_widget_private(w)->maybeBackingStore() == m_ptr);
     m_widgets.insert(w);
 }
unregisterWidget()
void QWidgetBackingStoreTracker::unregisterWidget (QWidget * w)
Remove the widget from the list of widgets currently using the backing store.
Warning
This function is not part of the public interface.
If the widget was in the list, and removing it causes the list to be empty, the backing store is deleted. If the widget was not in the list, this function is a no-op.
Definition at line 265 of file qwidget.cpp.
Referenced by unregisterWidgetSubtree().
 {
     if (m_widgets.remove(w) && m_widgets.isEmpty()) {
         delete m_ptr;
         m_ptr = 0;
     }
 }
unregisterWidgetSubtree()
void QWidgetBackingStoreTracker::unregisterWidgetSubtree (QWidget * widget)
Recursively remove widget and all of its descendents.
Warning
This function is not part of the public interface.
Definition at line 280 of file qwidget.cpp.
 {
     unregisterWidget(widget);
     foreach (QObject *child, widget->children())
         if (QWidget *childWidget = qobject_cast<QWidget *>(child))
             unregisterWidgetSubtree(childWidget);
 }
Properties
m_ptr
QWidgetBackingStore* QWidgetBackingStoreTracker::m_ptr private
Definition at line 156 of file qwidget_p.h.
Referenced by create(), destroy(), registerWidget(), unregisterWidget(), and ~QWidgetBackingStoreTracker().
m_widgets
QSet<QWidget *> QWidgetBackingStoreTracker::m_widgets private
Definition at line 157 of file qwidget_p.h.
Referenced by destroy(), registerWidget(), and unregisterWidget().
The documentation for this class was generated from the following files:
/src/gui/kernel/qwidget_p.h
/src/gui/kernel/qwidget.cpp