Qt 4.8: QGLOffscreen Class Reference
QGLOffscreen Class Reference
Public Slots
void cleanupGLContextRefs (const QGLContext *context)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void begin ()
void bind ()
QGLContext * context () const
QSize drawableSize () const
void end ()
void initialize ()
bool isBound () const
bool isValid () const
QSize offscreenSize () const
GLuint offscreenTexture () const
QGLOffscreen ()
void release ()
void setDevice (QPaintDevice *pdev)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool isSupported ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Properties
bool activated
bool bound
QGLContext * ctx
QGLPaintDevice * device
bool drawable_fbo
bool initialized
QSize last_failed_size
int mask_dim
QGLFramebufferObject * offscreen
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 235 of file qpaintengine_opengl.cpp.
Constructors and Destructors
QGLOffscreen()
QGLOffscreen::QGLOffscreen () inline
Definition at line 239 of file qpaintengine_opengl.cpp.
         : QObject(),
           offscreen(0),
           ctx(0),
           mask_dim(0),
           activated(false),
           bound(false)
     {
         connect(QGLSignalProxy::instance(),
                 SIGNAL(aboutToDestroyContext(const QGLContext*)),
                 SLOT(cleanupGLContextRefs(const QGLContext*)));
     }
Functions
begin()
void QGLOffscreen::begin ()
Definition at line 316 of file qpaintengine_opengl.cpp.
 {
 #ifndef QT_OPENGL_ES
     initialized = false;
     if (activated)
         initialize();
 #endif
 }
bind()
void QGLOffscreen::bind () inline
Definition at line 397 of file qpaintengine_opengl.cpp.
Referenced by QGLTrapezoidMaskGenerator::drawMask(), and QGLEllipseMaskGenerator::drawMask().
 {
 #ifndef QT_OPENGL_ES
     Q_ASSERT(initialized);
     if (!offscreen || bound)
         return;
     DEBUG_ONCE qDebug() << "QGLOffscreen: binding offscreen";
     offscreen->bind();
     bound = true;
     glViewport(0, 0, offscreenSize().width(), offscreenSize().height());
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     glOrtho(0, offscreenSize().width(), offscreenSize().height(), 0, -999999, 999999);
     glMatrixMode(GL_MODELVIEW);
 #endif
 }
cleanupGLContextRefs
void QGLOffscreen::cleanupGLContextRefs (const QGLContext * context) inline slot
Definition at line 276 of file qpaintengine_opengl.cpp.
{
         if (context == ctx) {
             delete offscreen;
             ctx = 0;
             offscreen = 0;
             mask_dim = 0;
         }
     }
context()
QGLContext * QGLOffscreen::context () const inline
Definition at line 474 of file qpaintengine_opengl.cpp.
Referenced by QGLTrapezoidMaskGenerator::drawMask(), and QGLEllipseMaskGenerator::drawMask().
 {
     return ctx;
 }
drawableSize()
QSize QGLOffscreen::drawableSize () const inline
Definition at line 459 of file qpaintengine_opengl.cpp.
Referenced by QGLEllipseMaskGenerator::drawMask(), and QGLTrapezoidMaskGenerator::screenRect().
 {
     return device->size();
 }
end()
void QGLOffscreen::end ()
Definition at line 369 of file qpaintengine_opengl.cpp.
 {
     if (bound)
         release();
 #ifdef DEBUG_DISPLAY_MASK_TEXTURE
     glReadBuffer(GL_BACK);
     glDrawBuffer(GL_BACK);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glColor4f(1, 1, 1, 1);
     glDisable(GL_DEPTH_TEST);
     glBlendFunc(GL_ONE, GL_ZERO);
     glColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);
     glEnable(GL_TEXTURE_2D);
     glBindTexture(GL_TEXTURE_2D, offscreen->texture());
     glBegin(GL_QUADS);
     glTexCoord2f(0.0, 1.0); glVertex2f(0.0, 0.0);
     glTexCoord2f(1.0, 1.0); glVertex2f(drawable.size().width(), 0.0);
     glTexCoord2f(1.0, 0.0); glVertex2f(drawable.size().width(), drawable.size().height());
     glTexCoord2f(0.0, 0.0); glVertex2f(0.0, drawable.size().height());
     glEnd();
     glBindTexture(GL_TEXTURE_2D, 0);
     glDisable(GL_TEXTURE_2D);
 #endif
 }
initialize()
void QGLOffscreen::initialize () inline
Definition at line 326 of file qpaintengine_opengl.cpp.
 {
 #ifndef QT_OPENGL_ES
     if (initialized)
         return;
     activated = true;
     initialized = true;
     int dim = qMax(2048, static_cast<int>(qt_next_power_of_two(qMax(device->size().width(), device->size().height()))));
     bool shared_context = QGLContext::areSharing(device->context(), ctx);
     bool would_fail = last_failed_size.isValid() &&
                       (device->size().width() >= last_failed_size.width() ||
                        device->size().height() >= last_failed_size.height());
     bool needs_refresh = dim > mask_dim || !shared_context;
     if (needs_refresh && !would_fail) {
         DEBUG_ONCE qDebug() << "QGLOffscreen::initialize(): creating offscreen of size" << dim;
         delete offscreen;
         offscreen = new QGLFramebufferObject(dim, dim, GLenum(GL_TEXTURE_2D));
         mask_dim = dim;
         if (!offscreen->isValid()) {
             qWarning("QGLOffscreen: Invalid offscreen fbo (size %dx%d)", mask_dim, mask_dim);
             delete offscreen;
             offscreen = 0;
             mask_dim = 0;
             last_failed_size = device->size();
         }
     }
     qt_mask_texture_cache()->setOffscreenSize(offscreenSize());
     qt_mask_texture_cache()->setDrawableSize(device->size());
     ctx = device->context();
 #endif
 }
isBound()
bool QGLOffscreen::isBound () const inline
Definition at line 454 of file qpaintengine_opengl.cpp.
 {
     return bound;
 }
isSupported()
bool QGLOffscreen::isSupported () static
Definition at line 479 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEngine::updateRenderHints().
 {
     return (QGLExtensions::glExtensions() & QGLExtensions::FramebufferObject); // for fbo
 }
isValid()
bool QGLOffscreen::isValid () const inline
Definition at line 364 of file qpaintengine_opengl.cpp.
 {
     return offscreen;
 }
offscreenSize()
QSize QGLOffscreen::offscreenSize () const inline
Definition at line 464 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEnginePrivate::drawItem(), QGLTrapezoidMaskGenerator::drawMask(), QGLEllipseMaskGenerator::drawMask(), and QOpenGLPaintEnginePrivate::updateFragmentProgramData().
 {
     return QSize(mask_dim, mask_dim);
 }
offscreenTexture()
GLuint QGLOffscreen::offscreenTexture () const inline
Definition at line 469 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEnginePrivate::composite().
 {
     return offscreen ? offscreen->texture() : 0;
 }
release()
void QGLOffscreen::release () inline
Definition at line 419 of file qpaintengine_opengl.cpp.
Referenced by QOpenGLPaintEnginePrivate::flushDrawQueue().
 {
 #ifndef QT_OPENGL_ES
     if (!offscreen || !bound)
         return;
 #ifdef Q_WS_X11
     // workaround for bug in nvidia driver versions 9x.xx
     if (qt_nvidiaFboNeedsFinish)
         glFinish();
 #endif
     DEBUG_ONCE_STR("QGLOffscreen: releasing offscreen");
     if (drawable_fbo)
         device->ensureActiveTarget(); //###
     else
         offscreen->release();
     QSize sz(device->size());
     glViewport(0, 0, sz.width(), sz.height());
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
 #ifndef QT_OPENGL_ES
     glOrtho(0, sz.width(), sz.height(), 0, -999999, 999999);
 #else
     glOrthof(0, sz.width(), sz.height(), 0, -999999, 999999);
 #endif
     glMatrixMode(GL_MODELVIEW);
     bound = false;
 #endif
 }
setDevice()
void QGLOffscreen::setDevice (QPaintDevice * pdev) inline
Definition at line 303 of file qpaintengine_opengl.cpp.
 {
     if (pdev->devType() == QInternal::OpenGL)
         device = static_cast<QGLPaintDevice*>(pdev);
     else
         device = QGLPaintDevice::getDevice(pdev);
     if (!device)
         return;
     drawable_fbo = (pdev->devType() == QInternal::FramebufferObject);
 }
Properties
activated
bool QGLOffscreen::activated private
Definition at line 297 of file qpaintengine_opengl.cpp.
bound
bool QGLOffscreen::bound private
Definition at line 300 of file qpaintengine_opengl.cpp.
ctx
QGLContext* QGLOffscreen::ctx private
Definition at line 289 of file qpaintengine_opengl.cpp.
device
QGLPaintDevice* QGLOffscreen::device private
Definition at line 286 of file qpaintengine_opengl.cpp.
drawable_fbo
bool QGLOffscreen::drawable_fbo private
Definition at line 295 of file qpaintengine_opengl.cpp.
initialized
bool QGLOffscreen::initialized private
Definition at line 298 of file qpaintengine_opengl.cpp.
last_failed_size
QSize QGLOffscreen::last_failed_size private
Definition at line 293 of file qpaintengine_opengl.cpp.
mask_dim
int QGLOffscreen::mask_dim private
Definition at line 292 of file qpaintengine_opengl.cpp.
offscreen
QGLFramebufferObject* QGLOffscreen::offscreen private
Definition at line 288 of file qpaintengine_opengl.cpp.
The documentation for this class was generated from the following file:
/src/opengl/qpaintengine_opengl.cpp