Qt 4.8: QScriptDebuggerResponse Class Reference
QScriptDebuggerResponse Class Reference
The QScriptDebuggerResponse class represents a front-end's response to a QScriptDebuggerCommand.
#include <qscriptdebuggerresponse_p.h>
Public Types
enum Error {
NoError, InvalidContextIndex, InvalidArgumentIndex, InvalidScriptID,
InvalidBreakpointID, UserError = 1000, MaxUserError = 32767
}
Public Functions
bool async () const
Error error () const
Returns the error code of this response.
bool operator!= (const QScriptDebuggerResponse &other) const
Returns true if this QScriptDebuggerResponse is not equal to the other response, otherwise returns false.
QScriptDebuggerResponse & operator= (const QScriptDebuggerResponse &other)
bool operator== (const QScriptDebuggerResponse &other) const
Returns true if this QScriptDebuggerResponse is equal to the other response, otherwise returns false.
QScriptDebuggerResponse ()
QScriptDebuggerResponse (const QScriptDebuggerResponse &other)
QVariant result () const
Returns the result of this response.
QScriptBreakpointData resultAsBreakpointData () const
QScriptBreakpointMap resultAsBreakpoints () const
QScriptContextInfo resultAsContextInfo () const
int resultAsInt () const
qint64 resultAsLongLong () const
QScriptScriptData resultAsScriptData () const
QScriptScriptMap resultAsScripts () const
QScriptDebuggerValue resultAsScriptValue () const
QScriptDebuggerValueList resultAsScriptValueList () const
QScriptDebuggerValuePropertyList resultAsScriptValuePropertyList () const
QString resultAsString () const
void setAsync (bool async)
void setError (Error error)
Sets the error code of this response.
void setResult (const QVariant &value)
Sets the Result attribute of this response to the given value.
void setResult (int value)
void setResult (const QString &value)
void setResult (const QScriptBreakpointData &data)
void setResult (const QScriptBreakpointMap &breakpoints)
void setResult (const QScriptScriptMap &scripts)
void setResult (const QScriptScriptData &data)
void setResult (const QScriptDebuggerValue &value)
void setResult (const QScriptDebuggerValueList &value)
void setResult (const QScriptDebuggerValuePropertyList &props)
void setResult (const QScriptContextInfo &info)
~QScriptDebuggerResponse ()
Properties
QScopedPointer< QScriptDebuggerResponsePrivate > d_ptr
Friends
Q_AUTOTEST_EXPORT QDataStream & operator<< (QDataStream &, const QScriptDebuggerResponse &)
Writes the given response to the specified stream.
Q_AUTOTEST_EXPORT QDataStream & operator>> (QDataStream &, QScriptDebuggerResponse &)
Reads a QScriptDebuggerResponse from the specified stream into the given response.
Detailed Description
The QScriptDebuggerResponse class represents a front-end's response to a QScriptDebuggerCommand.
Since
4.5
Warning
This function is not part of the public interface.
A response contains an error code and result.
Definition at line 72 of file qscriptdebuggerresponse_p.h.
Enumerations
Error
enum QScriptDebuggerResponse::Error
Enumerator
NoError
InvalidContextIndex
InvalidArgumentIndex
InvalidScriptID
InvalidBreakpointID
UserError
MaxUserError
Definition at line 78 of file qscriptdebuggerresponse_p.h.
                {
         NoError,
         InvalidContextIndex,
         InvalidArgumentIndex,
         InvalidScriptID,
         InvalidBreakpointID,
         UserError = 1000,
         MaxUserError = 32767
     };
Constructors and Destructors
QScriptDebuggerResponse() [1/2]
QScriptDebuggerResponse::QScriptDebuggerResponse ()
Definition at line 94 of file qscriptdebuggerresponse.cpp.
     : d_ptr(new QScriptDebuggerResponsePrivate)
 {
 }
QScriptDebuggerResponse() [2/2]
QScriptDebuggerResponse::QScriptDebuggerResponse (const QScriptDebuggerResponse & other)
Definition at line 99 of file qscriptdebuggerresponse.cpp.
     : d_ptr(new QScriptDebuggerResponsePrivate)
 {
     *d_ptr = *other.d_ptr;
 }
~QScriptDebuggerResponse()
QScriptDebuggerResponse::~QScriptDebuggerResponse ()
Definition at line 105 of file qscriptdebuggerresponse.cpp.
 {
 }
Functions
async()
bool QScriptDebuggerResponse::async () const
Definition at line 279 of file qscriptdebuggerresponse.cpp.
Referenced by debuggerResponseToScriptValue(), QScriptDebuggerPrivate::handleResponse(), and setAsync().
 {
     Q_D(const QScriptDebuggerResponse);
     return d->async;
 }
error()
QScriptDebuggerResponse::Error QScriptDebuggerResponse::error () const
Returns the error code of this response.
Definition at line 118 of file qscriptdebuggerresponse.cpp.
Referenced by debuggerResponseToScriptValue(), QScriptDebuggerPrivate::handleResponse(), operator>>(), and setError().
 {
     Q_D(const QScriptDebuggerResponse);
     return d->error;
 }
operator!=()
bool QScriptDebuggerResponse::operator!= (const QScriptDebuggerResponse & other) const
Returns true if this QScriptDebuggerResponse is not equal to the other response, otherwise returns false.
Definition at line 312 of file qscriptdebuggerresponse.cpp.
 {
     return !(*this == other);
 }
operator=()
QScriptDebuggerResponse & QScriptDebuggerResponse::operator= (const QScriptDebuggerResponse & other)
Definition at line 109 of file qscriptdebuggerresponse.cpp.
 {
     *d_ptr = *other.d_ptr;
     return *this;
 }
operator==()
bool QScriptDebuggerResponse::operator== (const QScriptDebuggerResponse & other) const
Returns true if this QScriptDebuggerResponse is equal to the other response, otherwise returns false.
Definition at line 295 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(const QScriptDebuggerResponse);
     const QScriptDebuggerResponsePrivate *od = other.d_func();
     if (d == od)
         return true;
     if (!d || !od)
         return false;
     return ((d->error == od->error)
             && (d->result == od->result)
             && (d->async == od->async));
 }
result()
QVariant QScriptDebuggerResponse::result () const
Returns the result of this response.
This function is provided for convenience.
Definition at line 137 of file qscriptdebuggerresponse.cpp.
Referenced by debuggerResponseToScriptValue(), QScriptCompleteExpressionJob::handleResponse(), QScriptToolTipJob::handleResponse(), QScriptDebuggerLocalsModelPrivate::isTopLevelNode(), and QScriptDebuggerLocalsModel::sync().
 {
     Q_D(const QScriptDebuggerResponse);
     return d->result;
 }
resultAsBreakpointData()
QScriptBreakpointData QScriptDebuggerResponse::resultAsBreakpointData () const
Definition at line 231 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptBreakpointData>(d->result);
 }
resultAsBreakpoints()
QScriptBreakpointMap QScriptDebuggerResponse::resultAsBreakpoints () const
Definition at line 237 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptBreakpointMap>(d->result);
 }
resultAsContextInfo()
QScriptContextInfo QScriptDebuggerResponse::resultAsContextInfo () const
Definition at line 273 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerPrivate::createLocalsModel().
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptContextInfo>(d->result);
 }
resultAsInt()
int QScriptDebuggerResponse::resultAsInt () const
Definition at line 213 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerPrivate::createLocalsModel(), QScriptDebuggerPrivate::handleResponse(), and QScriptDebuggerLocalsModelPrivate::isTopLevelNode().
 {
     Q_D(const QScriptDebuggerResponse);
     return d->result.toInt();
 }
resultAsLongLong()
qint64 QScriptDebuggerResponse::resultAsLongLong () const
Definition at line 219 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(const QScriptDebuggerResponse);
     return d->result.toLongLong();
 }
resultAsScriptData()
QScriptScriptData QScriptDebuggerResponse::resultAsScriptData () const
Definition at line 249 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerShowLineJob::handleResponse().
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptScriptData>(d->result);
 }
resultAsScripts()
QScriptScriptMap QScriptDebuggerResponse::resultAsScripts () const
Definition at line 243 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptCompleteScriptsJob::handleResponse().
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptScriptMap>(d->result);
 }
resultAsScriptValue()
QScriptDebuggerValue QScriptDebuggerResponse::resultAsScriptValue () const
Definition at line 255 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::addTopLevelObject(), and QScriptDebuggerLocalsModel::init().
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptDebuggerValue>(d->result);
 }
resultAsScriptValueList()
QScriptDebuggerValueList QScriptDebuggerResponse::resultAsScriptValueList () const
Definition at line 261 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::addTopLevelObject(), and QScriptDebuggerLocalsModel::init().
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptDebuggerValueList>(d->result);
 }
resultAsScriptValuePropertyList()
QScriptDebuggerValuePropertyList QScriptDebuggerResponse::resultAsScriptValuePropertyList () const
Definition at line 267 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(const QScriptDebuggerResponse);
     return qvariant_cast<QScriptDebuggerValuePropertyList>(d->result);
 }
resultAsString()
QString QScriptDebuggerResponse::resultAsString () const
Definition at line 225 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(const QScriptDebuggerResponse);
     return d->result.toString();
 }
setAsync()
void QScriptDebuggerResponse::setAsync (bool async)
Definition at line 285 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerResponse);
     d->async = async;
 }
setError()
void QScriptDebuggerResponse::setError (Error error)
Sets the error code of this response.
Definition at line 127 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerResponse);
     d->error = error;
 }
setResult() [1/11]
void QScriptDebuggerResponse::setResult (const QVariant & value)
Sets the Result attribute of this response to the given value.
This function is provided for convenience.
Definition at line 147 of file qscriptdebuggerresponse.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(QScriptDebuggerResponse);
     d->result = value;
 }
setResult() [2/11]
void QScriptDebuggerResponse::setResult (int value)
Definition at line 153 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = value;
 }
setResult() [3/11]
void QScriptDebuggerResponse::setResult (const QString & value)
Definition at line 159 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = value;
 }
setResult() [4/11]
void QScriptDebuggerResponse::setResult (const QScriptBreakpointData & data)
Definition at line 165 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(data);
 }
setResult() [5/11]
void QScriptDebuggerResponse::setResult (const QScriptBreakpointMap & breakpoints)
Definition at line 171 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(breakpoints);
 }
setResult() [6/11]
void QScriptDebuggerResponse::setResult (const QScriptScriptMap & scripts)
Definition at line 177 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(scripts);
 }
setResult() [7/11]
void QScriptDebuggerResponse::setResult (const QScriptScriptData & data)
Definition at line 183 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(data);
 }
setResult() [8/11]
void QScriptDebuggerResponse::setResult (const QScriptDebuggerValue & value)
Definition at line 189 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(value);
 }
setResult() [9/11]
void QScriptDebuggerResponse::setResult (const QScriptDebuggerValueList & value)
Definition at line 195 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(values);
 }
setResult() [10/11]
void QScriptDebuggerResponse::setResult (const QScriptDebuggerValuePropertyList & props)
Definition at line 201 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(props);
 }
setResult() [11/11]
void QScriptDebuggerResponse::setResult (const QScriptContextInfo & info)
Definition at line 207 of file qscriptdebuggerresponse.cpp.
 {
     Q_D(QScriptDebuggerResponse);
     d->result = QVariant::fromValue(info);
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & out, const QScriptDebuggerResponse & response) friend
Writes the given response to the specified stream.
Definition at line 326 of file qscriptdebuggerresponse.cpp.
 {
     const QScriptDebuggerResponsePrivate *d = response.d_ptr.data();
     out << (quint32)d->error;
     out << d->result;
     out << d->async;
     return out;
 }
operator>>
QDataStream & operator>> (QDataStream & in, QScriptDebuggerResponse & response) friend
Reads a QScriptDebuggerResponse from the specified stream into the given response.
Definition at line 345 of file qscriptdebuggerresponse.cpp.
 {
     QScriptDebuggerResponsePrivate *d = response.d_ptr.data();
     quint32 error;
     in >> error;
     d->error = QScriptDebuggerResponse::Error(error);
     in >> d->result;
     in >> d->async;
     return in;
 }
Properties
d_ptr
QScopedPointer<QScriptDebuggerResponsePrivate> QScriptDebuggerResponse::d_ptr private
Definition at line 130 of file qscriptdebuggerresponse_p.h.
Referenced by operator<<(), operator=(), operator>>(), and QScriptDebuggerResponse().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerresponse_p.h
/src/scripttools/debugging/qscriptdebuggerresponse.cpp