Qt 4.8: QMimeSource Class Reference
QMimeSource Class Reference abstract
The QMimeSource class is an abstraction of objects that provided formatted data of a certain MIME type.
#include <qmime.h>
Public Functions
virtual QByteArray encodedData (const char *) const =0
Returns the encoded data of this object in the specified MIME format.
virtual const char * format (int n=0) const =0
Returns the (i - 1)-th supported MIME format, or 0.
virtual bool provides (const char *) const
Returns true if the object can provide the data in format mimeType; otherwise returns false.
virtual ~QMimeSource ()
Destroys the MIME source.
Detailed Description
The QMimeSource class is an abstraction of objects that provided formatted data of a certain MIME type.
The preferred approach to drag and drop is to use QDrag in conjunction with QMimeData. See Drag and Drop for details.
See also
QMimeData, QDrag
Definition at line 53 of file qmime.h.
Constructors and Destructors
~QMimeSource()
QMimeSource::~QMimeSource () virtual
Destroys the MIME source.
Definition at line 65 of file qmime.cpp.
 {
 }
Functions
encodedData()
QByteArray QMimeSource::encodedData (const char * format) const pure virtual
Returns the encoded data of this object in the specified MIME format.
Implemented in QDropEvent, and QMimeDataWrapper.
Referenced by QMimeSourceWrapper::retrieveData().
format()
const char * QMimeSource::format (int n = 0) const pure virtual
Returns the (i - 1)-th supported MIME format, or 0.
Implemented in QDropEvent, and QMimeDataWrapper.
Referenced by QMimeSourceWrapper::formats(), and provides().
provides()
bool QMimeSource::provides (const char * mimeType) const virtual
Returns true if the object can provide the data in format mimeType; otherwise returns false.
If you inherit from QMimeSource, for consistency reasons it is better to implement the more abstract canDecode() functions such as QTextDrag::canDecode() and QImageDrag::canDecode().
Reimplemented in QDropEvent.
Definition at line 90 of file qmime.cpp.
Referenced by QMimeSourceWrapper::hasFormat().
 {
     const char* fmt;
     for (int i=0; (fmt = format(i)); i++) {
         if (!qstricmp(mimeType,fmt))
             return true;
     }
     return false;
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qmime.h
/src/gui/kernel/qmime.cpp