Qt 4.8: QPatternist::ValueFactory Class Reference
QPatternist::ValueFactory Class Reference
XML Schema Processing
Provides fromLexical(), which allows instantiation of atomic values from arbitrary types.
#include <qvaluefactory_p.h>
Static Public Functions
static AtomicValue::Ptr fromLexical (const QString &lexicalValue, const SchemaType::Ptr &type, const ReportContext::Ptr &context, const SourceLocationReflection *const sourceLocationReflection)
Returns an AtomicValue of type type from the lexical space lexicalValue, and raise an error through context if that's impossible.
Detailed Description
Provides fromLexical(), which allows instantiation of atomic values from arbitrary types.
This class wraps the helper class CastingPlatform with a more specific, high-level API.
See also
CastingPlatform
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 75 of file qvaluefactory_p.h.
Functions
fromLexical()
AtomicValue::Ptr ValueFactory::fromLexical (const QString & lexicalValue, const SchemaType::Ptr & type, const ReportContext::Ptr & context, const SourceLocationReflection *const sourceLocationReflection) static
Returns an AtomicValue of type type from the lexical space lexicalValue, and raise an error through context if that's impossible.
ValueFactory does not take ownership of sourceLocationReflection.
Definition at line 91 of file qvaluefactory.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QPatternist::XsdTypeChecker::checkConstrainingFacetsBinary(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDateTime(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDouble(), QPatternist::XsdTypeChecker::checkConstrainingFacetsSignedInteger(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnsignedInteger(), QPatternist::ComparisonFactory::constructAndCompare(), QPatternist::XsdSchemaHelper::constructAndCompare(), and QPatternist::XsdTypeChecker::fromLexical().
 {
     Q_ASSERT(context);
     Q_ASSERT(type);
     Q_ASSERT_X(type->category() == SchemaType::SimpleTypeAtomic, Q_FUNC_INFO,
                "We can only construct for atomic values.");
     return PerformValueConstruction(sourceLocationReflection, type)(AtomicString::fromValue(lexicalValue),
                                                                     type,
                                                                     context);
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qvaluefactory_p.h
/src/xmlpatterns/data/qvaluefactory.cpp