Qt 4.8: QDeclarativeFontLoader Class Reference
QDeclarativeFontLoader Class Reference
#include <qdeclarativefontloader_p.h>
Public Types
enum Status { Null = 0, Ready, Loading, Error }
Signals
void nameChanged ()
void sourceChanged ()
void statusChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QString name () const
QDeclarativeFontLoader (QObject *parent=0)
void setName (const QString &name)
void setSource (const QUrl &url)
QUrl source () const
Status status () const
~QDeclarativeFontLoader ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void updateFontInfo (const QString &, QDeclarativeFontLoader::Status)
Properties
QString name
QUrl source
Status status
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 57 of file qdeclarativefontloader_p.h.
Enumerations
Status
enum QDeclarativeFontLoader::Status
Enumerator
Null
Ready
Loading
Error
Definition at line 68 of file qdeclarativefontloader_p.h.
 { Null = 0, Ready, Loading, Error };
Constructors and Destructors
QDeclarativeFontLoader()
QDeclarativeFontLoader::QDeclarativeFontLoader (QObject * parent = 0)
Definition at line 175 of file qdeclarativefontloader.cpp.
     : QObject(*(new QDeclarativeFontLoaderPrivate), parent)
 {
 }
~QDeclarativeFontLoader()
QDeclarativeFontLoader::~QDeclarativeFontLoader ()
Definition at line 180 of file qdeclarativefontloader.cpp.
 {
 }
Functions
name()
QString QDeclarativeFontLoader::name () const
Referenced by setName(), and updateFontInfo().
nameChanged
void QDeclarativeFontLoader::nameChanged () signal
Referenced by setName(), and updateFontInfo().
setName()
void QDeclarativeFontLoader::setName (const QString & name)
Definition at line 294 of file qdeclarativefontloader.cpp.
 {
     Q_D(QDeclarativeFontLoader);
     if (d->name == name)
         return;
     d->name = name;
     emit nameChanged();
     d->status = Ready;
     emit statusChanged();
 }
setSource()
void QDeclarativeFontLoader::setSource (const QUrl & url)
Definition at line 197 of file qdeclarativefontloader.cpp.
 {
     Q_D(QDeclarativeFontLoader);
     if (url == d->url)
         return;
     d->url = qmlContext(this)->resolvedUrl(url);
     emit sourceChanged();
 #ifndef QT_NO_LOCALFILE_OPTIMIZED_QML
     QString localFile = QDeclarativeEnginePrivate::urlToLocalFileOrQrc(d->url);
     if (!localFile.isEmpty()) {
         if (!d->fonts.contains(d->url)) {
             int id = QFontDatabase::addApplicationFont(localFile);
             if (id != -1) {
                 updateFontInfo(QFontDatabase::applicationFontFamilies(id).at(0), Ready);
                 QDeclarativeFontObject *fo = new QDeclarativeFontObject(id);
                 d->fonts[d->url] = fo;
             } else {
                 updateFontInfo(QString(), Error);
             }
         } else {
             updateFontInfo(QFontDatabase::applicationFontFamilies(d->fonts[d->url]->id).at(0), Ready);
         }
     } else
 #endif
     {
         if (!d->fonts.contains(d->url)) {
             QDeclarativeFontObject *fo = new QDeclarativeFontObject;
             d->fonts[d->url] = fo;
             fo->download(d->url, qmlEngine(this)->networkAccessManager());
             d->status = Loading;
             emit statusChanged();
             QObject::connect(fo, SIGNAL(fontDownloaded(QString,QDeclarativeFontLoader::Status)),
                 this, SLOT(updateFontInfo(QString,QDeclarativeFontLoader::Status)));
         } else {
             QDeclarativeFontObject *fo = d->fonts[d->url];
             if (fo->id == -1) {
                 d->status = Loading;
                 emit statusChanged();
                 QObject::connect(fo, SIGNAL(fontDownloaded(QString,QDeclarativeFontLoader::Status)),
                     this, SLOT(updateFontInfo(QString,QDeclarativeFontLoader::Status)));
             }
             else
                 updateFontInfo(QFontDatabase::applicationFontFamilies(fo->id).at(0), Ready);
         }
     }
 }
source()
QUrl QDeclarativeFontLoader::source () const
Referenced by ~QDeclarativeFontLoader().
sourceChanged
void QDeclarativeFontLoader::sourceChanged () signal
Referenced by setSource().
status()
Status QDeclarativeFontLoader::status () const
Referenced by setName(), and updateFontInfo().
statusChanged
void QDeclarativeFontLoader::statusChanged () signal
Referenced by setName(), setSource(), and updateFontInfo().
updateFontInfo
void QDeclarativeFontLoader::updateFontInfo (const QString & name, QDeclarativeFontLoader::Status status) private slot
Definition at line 245 of file qdeclarativefontloader.cpp.
Referenced by setSource().
 {
     Q_D(QDeclarativeFontLoader);
     if (name != d->name) {
         d->name = name;
         emit nameChanged();
     }
     if (status != d->status) {
         if (status == Error)
             qmlInfo(this) << "Cannot load font: \"" << d->url.toString() << "\"";
         d->status = status;
         emit statusChanged();
     }
 }
Properties
name
QString QDeclarativeFontLoader::name private
Definition at line 64 of file qdeclarativefontloader_p.h.
source
QUrl QDeclarativeFontLoader::source private
Definition at line 63 of file qdeclarativefontloader_p.h.
status
QDeclarativeFontLoader::Status QDeclarativeFontLoader::status private
Definition at line 65 of file qdeclarativefontloader_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativefontloader_p.h
/src/declarative/util/qdeclarativefontloader.cpp