Qt 4.8: QFragmentMap< Fragment > Class Template Reference
QFragmentMap< Fragment > Class Template Reference
#include <qfragmentmap_p.h>
Classes
class ConstIterator
class Iterator
Public Functions
Iterator begin ()
ConstIterator begin () const
void clear ()
Iterator end ()
ConstIterator end () const
uint erase_single (uint f)
Iterator find (int k, uint field=0)
ConstIterator find (int k, uint field=0) const
uint findNode (int k, uint field=0) const
int firstNode () const
Fragment * fragment (uint index)
const Fragment * fragment (uint index) const
uint insert_single (int key, uint length)
bool isEmpty () const
bool isValid (uint n) const
ConstIterator last () const
int length (uint field=0) const
uint next (uint n) const
int numNodes () const
uint position (uint node, uint field=0) const
uint previous (uint n) const
QFragmentMap ()
void setSize (uint node, int new_size, uint field=0)
uint size (uint node, uint field=0) const
~QFragmentMap ()
Private Functions
QFragmentMap & operator= (const QFragmentMap &m)
QFragmentMap (const QFragmentMap &m)
Properties
QFragmentMapData< Fragment > data
Friends
class ConstIterator
class Iterator
Detailed Description
template<class Fragment>
class QFragmentMap< Fragment >
Definition at line 723 of file qfragmentmap_p.h.
Constructors and Destructors
QFragmentMap() [1/2]
template<class Fragment> QFragmentMap< Fragment >::QFragmentMap () inline
Definition at line 801 of file qfragmentmap_p.h.
 {}
~QFragmentMap()
template<class Fragment> QFragmentMap< Fragment >::~QFragmentMap () inline
Definition at line 802 of file qfragmentmap_p.h.
     {
         if (!data.fragments)
             return; // in case of out-of-memory, we won't have fragments
         for (Iterator it = begin(); !it.atEnd(); ++it)
             it.value()->free();
     }
QFragmentMap() [2/2]
template<class Fragment> QFragmentMap< Fragment >::QFragmentMap (const QFragmentMap< Fragment > & m) private
Functions
begin() [1/2]
template<class Fragment> Iterator QFragmentMap< Fragment >::begin () inline
Definition at line 816 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::compressPieceTable(), QTextDocumentPrivate::setLayout(), and QTextOdfWriter::writeAll().
 { return Iterator(this, data.minimum(data.root())); }
begin() [2/2]
template<class Fragment> ConstIterator QFragmentMap< Fragment >::begin () const inline
Definition at line 818 of file qfragmentmap_p.h.
 { return ConstIterator(this, data.minimum(data.root())); }
clear()
template<class Fragment> void QFragmentMap< Fragment >::clear () inline
Definition at line 810 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::clear().
{
         for (Iterator it = begin(); !it.atEnd(); ++it)
             it.value()->free();
         data.init();
     }
end() [1/2]
template<class Fragment> Iterator QFragmentMap< Fragment >::end () inline
Definition at line 817 of file qfragmentmap_p.h.
Referenced by QTextOdfWriter::writeAll().
 { return Iterator(this, 0); }
end() [2/2]
template<class Fragment> ConstIterator QFragmentMap< Fragment >::end () const inline
Definition at line 819 of file qfragmentmap_p.h.
 { return ConstIterator(this, 0); }
erase_single()
template<class Fragment> uint QFragmentMap< Fragment >::erase_single (uint f) inline
Definition at line 842 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::remove_block(), QTextDocumentPrivate::remove_string(), and QTextDocumentPrivate::unite().
     {
       if (f != 0) {
           Fragment *frag = fragment(f);
           Q_ASSERT(frag);
           frag->free();
       }
       return data.erase_single(f);
     }
find() [1/2]
template<class Fragment> Iterator QFragmentMap< Fragment >::find (int k, uint field = 0) inline
Definition at line 827 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::blockCharFormatIndex(), QTextDocumentPrivate::setCharFormat(), and QTextTable::splitCell().
 { return Iterator(this, data.findNode(k, field)); }
find() [2/2]
template<class Fragment> ConstIterator QFragmentMap< Fragment >::find (int k, uint field = 0) const inline
Definition at line 828 of file qfragmentmap_p.h.
 { return ConstIterator(this, data.findNode(k, field)); }
findNode()
template<class Fragment> uint QFragmentMap< Fragment >::findNode (int k, uint field = 0) const inline
Definition at line 830 of file qfragmentmap_p.h.
Referenced by QTextTableCell::begin(), QTextFrame::begin(), QTextCursorPrivate::block(), QTextTableCell::end(), QTextFrame::end(), QTextDocumentLayoutPrivate::frameIteratorForTextPosition(), QTextDocumentPrivate::insert(), QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insert_string(), QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::move(), QTextFrame::iterator::operator++(), QTextFrame::iterator::operator--(), QTextDocumentPrivate::remove_block(), QTextDocumentPrivate::remove_string(), QTextDocumentPrivate::setCharFormat(), QTextDocumentPrivate::split(), and QTextDocumentPrivate::undoRedo().
 { return data.findNode(k, field); }
firstNode()
template<class Fragment> int QFragmentMap< Fragment >::firstNode () const inline
Definition at line 874 of file qfragmentmap_p.h.
Referenced by QTextCursor::charFormat().
 { return data.minimum(data.root()); }
fragment() [1/2]
template<class Fragment> Fragment* QFragmentMap< Fragment >::fragment (uint index) inline
Definition at line 852 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::block(), QTextDocumentPrivate::insert(), QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insert_string(), QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::move(), QFragmentMap< Fragment >::Iterator::operator*(), QFragmentMap< Fragment >::ConstIterator::operator*(), QFragmentMap< Fragment >::Iterator::operator->(), QFragmentMap< Fragment >::ConstIterator::operator->(), QTextDocumentPrivate::remove_block(), QTextDocumentPrivate::remove_string(), QTextDocumentPrivate::split(), QTextDocumentPrivate::undoRedo(), QTextDocumentPrivate::unite(), QFragmentMap< Fragment >::Iterator::value(), and QFragmentMap< Fragment >::ConstIterator::value().
{
         Q_ASSERT(index != 0);
         return data.fragment(index);
     }
fragment() [2/2]
template<class Fragment> const Fragment* QFragmentMap< Fragment >::fragment (uint index) const inline
Definition at line 856 of file qfragmentmap_p.h.
{
         Q_ASSERT(index != 0);
         return data.fragment(index);
     }
insert_single()
template<class Fragment> uint QFragmentMap< Fragment >::insert_single (int key, uint length) inline
Definition at line 832 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insert_string(), and QTextDocumentPrivate::split().
     {
         uint f = data.insert_single(key, length);
         if (f != 0) {
             Fragment *frag = fragment(f);
             Q_ASSERT(frag);
             frag->initialize();
         }
         return f;
     }
isEmpty()
template<class Fragment> bool QFragmentMap< Fragment >::isEmpty () const inline
Definition at line 823 of file qfragmentmap_p.h.
 { return data.head->node_count == 0; }
isValid()
template<class Fragment> bool QFragmentMap< Fragment >::isValid (uint n) const inline
Definition at line 861 of file qfragmentmap_p.h.
 { return data.isValid(n); }
last()
template<class Fragment> ConstIterator QFragmentMap< Fragment >::last () const inline
Definition at line 821 of file qfragmentmap_p.h.
 { return ConstIterator(this, data.maximum(data.root())); }
length()
template<class Fragment> int QFragmentMap< Fragment >::length (uint field = 0) const inline
Definition at line 825 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::clear(), QTextDocumentPrivate::insert(), QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insert_string(), QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::move(), QTextDocumentPrivate::remove_block(), and QTextDocumentPrivate::remove_string().
 { return data.length(field); }
next()
template<class Fragment> uint QFragmentMap< Fragment >::next (uint n) const inline
Definition at line 862 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::move(), QTextFrame::iterator::operator++(), QTextDocumentPrivate::remove_block(), and QTextDocumentPrivate::unite().
 { return data.next(n); }
numNodes()
template<class Fragment> int QFragmentMap< Fragment >::numNodes () const inline
Definition at line 824 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::ensureMaximumBlockCount(), and QTextDocumentPrivate::finishEdit().
 { return data.head->node_count; }
operator=()
template<class Fragment> QFragmentMap& QFragmentMap< Fragment >::operator= (const QFragmentMap< Fragment > & m) private
position()
template<class Fragment> uint QFragmentMap< Fragment >::position (uint node, uint field = 0) const inline
Definition at line 860 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::blockCharFormatIndex(), QTextTable::cellAt(), QTextTableCell::firstPosition(), QTextDocumentLayoutPrivate::frameIteratorForTextPosition(), QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insertBlock(), QTextTableCell::lastPosition(), QTextTable::mergeCells(), QTextDocumentPrivate::move(), QTextFrame::iterator::operator++(), QTextFrame::iterator::operator--(), operator<(), QTextDocumentPrivate::remove_block(), QTextDocumentPrivate::remove_string(), QTextTable::removeColumns(), QTextTable::removeRows(), QTextDocumentPrivate::split(), and QTextTable::splitCell().
 { return data.position(node, field); }
previous()
template<class Fragment> uint QFragmentMap< Fragment >::previous (uint n) const inline
Definition at line 863 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::insert_string(), QTextDocumentPrivate::move(), and QTextFrame::iterator::operator--().
 { return data.previous(n); }
setSize()
template<class Fragment> void QFragmentMap< Fragment >::setSize (uint node, int new_size, uint field = 0) inline
Definition at line 865 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insert_string(), QTextDocumentPrivate::remove_block(), QTextDocumentPrivate::remove_string(), QTextDocumentPrivate::split(), and QTextDocumentPrivate::unite().
         { data.setSize(node, new_size, field);
       if (node != 0 && field == 0) {
           Fragment *frag = fragment(node);
           Q_ASSERT(frag);
           frag->invalidate();
       }
     }
size()
template<class Fragment> uint QFragmentMap< Fragment >::size (uint node, uint field = 0) const inline
Definition at line 864 of file qfragmentmap_p.h.
Referenced by QTextDocumentPrivate::insert_block(), QTextDocumentPrivate::insert_string(), QTextDocumentPrivate::insertBlock(), QTextDocumentPrivate::move(), QTextDocumentPrivate::remove_block(), and QTextDocumentPrivate::remove_string().
 { return data.size(node, field); }
Friends and Related Functions
ConstIterator
template<class Fragment> friend class ConstIterator friend
Definition at line 878 of file qfragmentmap_p.h.
Iterator
template<class Fragment> friend class Iterator friend
Definition at line 877 of file qfragmentmap_p.h.
Properties
data
template<class Fragment> QFragmentMapData<Fragment> QFragmentMap< Fragment >::data private
Definition at line 880 of file qfragmentmap_p.h.
Referenced by QFragmentMap< Fragment >::Iterator::operator++(), QFragmentMap< Fragment >::ConstIterator::operator++(), QFragmentMap< Fragment >::Iterator::operator--(), QFragmentMap< Fragment >::ConstIterator::operator--(), QFragmentMap< Fragment >::Iterator::position(), QFragmentMap< Fragment >::ConstIterator::position(), and QFragmentMap< Fragment >::ConstIterator::size().
The documentation for this class was generated from the following file:
/src/gui/text/qfragmentmap_p.h