Qt 4.8: QBBRootWindow Class Reference
QBBRootWindow Class Reference
#include <qbbrootwindow.h>
Public Functions
void flush () const
QByteArray groupName () const
screen_window_t nativeHandle () const
void post () const
QBBRootWindow (QBBScreen *screen)
void resize (const QSize &size)
void setRotation (int rotation)
~QBBRootWindow ()
Private Functions
void createWindowGroup ()
Properties
QBBScreen * m_screen
screen_window_t m_window
QByteArray m_windowGroupName
Detailed Description
Definition at line 54 of file qbbrootwindow.h.
Constructors and Destructors
QBBRootWindow()
QBBRootWindow::QBBRootWindow (QBBScreen * screen)
Definition at line 57 of file qbbrootwindow.cpp.
     : m_screen(screen),
       m_window(0),
       m_windowGroupName()
 {
 #if defined(QBBROOTWINDOW_DEBUG)
     qDebug() << Q_FUNC_INFO;
 #endif
     // Create one top-level QNX window to act as a container for child windows
     // since navigator only supports one application window
     errno = 0;
     int result = screen_create_window(&m_window, m_screen->nativeContext());
     int val[2];
     if (result != 0) {
         qFatal("QBBRootWindow: failed to create window, errno=%d", errno);
     }
     // Move window to proper display
     errno = 0;
     screen_display_t display = m_screen->nativeDisplay();
     result = screen_set_window_property_pv(m_window, SCREEN_PROPERTY_DISPLAY, (void **)&display);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window display, errno=%d", errno);
     }
     // Make sure window is above navigator but below keyboard if running as root
     // since navigator won't automatically set our z-order in this case
     if (getuid() == 0) {
         errno = 0;
         val[0] = MAGIC_ZORDER_FOR_NO_NAV;
         result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_ZORDER, val);
         if (result != 0) {
             qFatal("QBBRootWindow: failed to set window z-order, errno=%d", errno);
         }
     }
     // Window won't be visible unless it has some buffers so make one dummy buffer that is 1x1
     errno = 0;
     val[0] = SCREEN_USAGE_NATIVE;
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_USAGE, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window buffer usage, errno=%d", errno);
     }
     errno = 0;
     val[0] = m_screen->nativeFormat();
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_FORMAT, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window pixel format, errno=%d", errno);
     }
     errno = 0;
     val[0] = 1;
     val[1] = 1;
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_BUFFER_SIZE, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window buffer size, errno=%d", errno);
     }
     errno = 0;
     result = screen_create_window_buffers(m_window, 1);
     if (result != 0) {
         qFatal("QBB: failed to create window buffer, errno=%d", errno);
     }
     // Window is always the size of the display
     errno = 0;
     QRect geometry = m_screen->geometry();
     val[0] = geometry.width();
     val[1] = geometry.height();
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_SIZE, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window size, errno=%d", errno);
     }
     // Fill the window with solid black
     errno = 0;
     val[0] = 0;
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_COLOR, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window colour, errno=%d", errno);
     }
     // Make the window opaque
     errno = 0;
     val[0] = SCREEN_TRANSPARENCY_NONE;
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_TRANSPARENCY, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window transparency, errno=%d", errno);
     }
     // Set the swap interval to 1
     errno = 0;
     val[0] = 1;
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_SWAP_INTERVAL, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window swap interval, errno=%d", errno);
     }
     // Set viewport size equal to window size but move outside buffer so the fill colour is used exclusively
     errno = 0;
     val[0] = geometry.width();
     val[1] = geometry.height();
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_SOURCE_SIZE, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window source size, errno=%d", errno);
     }
     errno = 0;
     val[0] = 1;
     val[1] = 0;
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_SOURCE_POSITION, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window source position, errno=%d", errno);
     }
     createWindowGroup();
     post();
 }
~QBBRootWindow()
QBBRootWindow::~QBBRootWindow ()
Definition at line 177 of file qbbrootwindow.cpp.
 {
     // Cleanup top-level QNX window
     screen_destroy_window(m_window);
 }
Functions
createWindowGroup()
void QBBRootWindow::createWindowGroup () private
Definition at line 246 of file qbbrootwindow.cpp.
Referenced by groupName(), and QBBRootWindow().
 {
     // Generate a random window group name
     m_windowGroupName = QUuid::createUuid().toString().toAscii();
     // Create window group so child windows can be parented by container window
     errno = 0;
     int result = screen_create_window_group(m_window, m_windowGroupName.constData());
     if (result != 0) {
         qFatal("QBBRootWindow: failed to create app window group, errno=%d", errno);
     }
 }
flush()
void QBBRootWindow::flush () const
Definition at line 203 of file qbbrootwindow.cpp.
Referenced by nativeHandle(), and QBBScreen::setRotation().
 {
 #if defined(QBBROOTWINDOW_DEBUG)
     qDebug() << Q_FUNC_INFO;
 #endif
     // Force immediate display update
     errno = 0;
     int result = screen_flush_context(m_screen->nativeContext(), 0);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to flush context, errno=%d", errno);
     }
 }
groupName()
QByteArray QBBRootWindow::groupName () const inline
Definition at line 69 of file qbbrootwindow.h.
Referenced by QBBNativeInterface::nativeResourceForWidget(), and QBBScreen::windowGroupName().
 { return m_windowGroupName; }
nativeHandle()
screen_window_t QBBRootWindow::nativeHandle () const inline
Definition at line 60 of file qbbrootwindow.h.
 { return m_window; }
post()
void QBBRootWindow::post () const
Definition at line 183 of file qbbrootwindow.cpp.
Referenced by nativeHandle(), QBBScreen::onWindowPost(), and QBBRootWindow().
 {
 #if defined(QBBROOTWINDOW_DEBUG)
     qDebug() << Q_FUNC_INFO;
 #endif
     errno = 0;
     screen_buffer_t buffer;
     int result = screen_get_window_property_pv(m_window, SCREEN_PROPERTY_RENDER_BUFFERS, (void **)&buffer);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to query window buffer, errno=%d", errno);
     }
     errno = 0;
     int dirtyRect[] = {0, 0, 1, 1};
     result = screen_post_window(m_window, buffer, 1, dirtyRect, 0);
     if (result != 0) {
         qFatal("QBB: failed to post window buffer, errno=%d", errno);
     }
 }
resize()
void QBBRootWindow::resize (const QSize & size)
Definition at line 228 of file qbbrootwindow.cpp.
Referenced by nativeHandle(), and QBBScreen::setRotation().
 {
     errno = 0;
     int val[] = {size.width(), size.height()};
     int result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_SIZE, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window size, errno=%d", errno);
     }
     errno = 0;
     result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_SOURCE_SIZE, val);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window source size, errno=%d", errno);
     }
     // NOTE: display will update when child windows relayout and repaint
 }
setRotation()
void QBBRootWindow::setRotation (int rotation)
Definition at line 216 of file qbbrootwindow.cpp.
Referenced by nativeHandle(), and QBBScreen::setRotation().
 {
 #if defined(QBBROOTWINDOW_DEBUG)
     qDebug() << Q_FUNC_INFO << "angle =" << rotation;
 #endif
     errno = 0;
     int result = screen_set_window_property_iv(m_window, SCREEN_PROPERTY_ROTATION, &rotation);
     if (result != 0) {
         qFatal("QBBRootWindow: failed to set window rotation, errno=%d", errno);
     }
 }
Properties
m_screen
QBBScreen* QBBRootWindow::m_screen private
Definition at line 74 of file qbbrootwindow.h.
Referenced by flush(), and QBBRootWindow().
m_window
screen_window_t QBBRootWindow::m_window private
Definition at line 75 of file qbbrootwindow.h.
Referenced by createWindowGroup(), nativeHandle(), post(), QBBRootWindow(), resize(), setRotation(), and ~QBBRootWindow().
m_windowGroupName
QByteArray QBBRootWindow::m_windowGroupName private
Definition at line 76 of file qbbrootwindow.h.
Referenced by createWindowGroup(), and groupName().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbrootwindow.h
/src/plugins/platforms/blackberry/qbbrootwindow.cpp