Qt 4.8: QInputContextFactory Class Reference
QInputContextFactory Class Reference
The QInputContextFactory class creates QInputContext objects.
#include <qinputcontextfactory.h>
Static Public Functions
static QInputContext * create (const QString &key, QObject *parent)
static QString description (const QString &key)
Returns an internationalized brief description of the QInputContext object specified by key.
static QString displayName (const QString &key)
Returns a user friendly internationalized name of the QInputContext object specified by key.
static QStringList keys ()
Returns the list of keys this factory can create input contexts for.
static QStringList languages (const QString &key)
Returns the languages supported by the QInputContext object specified by key.
Detailed Description
The QInputContextFactory class creates QInputContext objects.
The input context factory creates a QInputContext object for a given key with QInputContextFactory::create().
The input contexts are either built-in or dynamically loaded from an input context plugin (see QInputContextPlugin).
keys() returns a list of valid keys. The keys are the names used, for example, to identify and specify input methods for the input method switching mechanism. The names have to be consistent with QInputContext::identifierName(), and may only contain ASCII characters.
A key can be used to retrieve the associated input context's supported languages using languages(). You can retrieve the input context's description using description() and finally you can get a user friendly internationalized name of the QInputContext object specified by the key using displayName().
Copyright (C) 2003-2004 immodule for Qt Project. All rights reserved.
This file is written to contribute to Nokia Corporation and/or its subsidiary(-ies) under their own license. You may use this file under your Qt license. Following description is copied from their original file headers. Contact immod.nosp@m.ule-.nosp@m.qt@fr.nosp@m.eede.nosp@m.sktop.nosp@m..org if any conditions of this licensing are not clear to you.
See also
QInputContext, QInputContextPlugin
Definition at line 72 of file qinputcontextfactory.h.
Functions
create()
static QInputContext* QInputContextFactory::create (const QString & key, QObject * parent) static
Referenced by QMultiInputContext::changeSlave(), QApplication::inputContext(), and QMultiInputContext::QMultiInputContext().
description()
QString QInputContextFactory::description (const QString & key) static
Returns an internationalized brief description of the QInputContext object specified by key.
You can, for example, use this description in a user interface.
See also
keys(), displayName()
Definition at line 333 of file qinputcontextfactory.cpp.
 {
 #if defined(Q_WS_X11) && !defined(QT_NO_XIM)
     if (key == QLatin1String("xim"))
         return QInputContext::tr( "XIM input method" );
 #endif
 #if defined(Q_WS_WIN) && !defined(QT_NO_XIM)
     if (key == QLatin1String("win"))
         return QInputContext::tr( "Windows input method" );
 #endif
 #if defined(Q_WS_MAC)
     if (key == QLatin1String("mac"))
         return QInputContext::tr( "Mac OS X input method" );
 #endif
 #if defined(Q_WS_S60)
     if (key == QLatin1String("coefep"))
         return QInputContext::tr( "S60 FEP input method" );
 #endif
 #if defined(QT_NO_LIBRARY) || defined(QT_NO_SETTINGS)
     Q_UNUSED(key);
 #else
     if (QInputContextFactoryInterface *factory =
         qobject_cast<QInputContextFactoryInterface*>(loader()->instance(key)))
         return factory->description(key);
 #endif // QT_NO_LIBRARY
     return QString();
 }
displayName()
QString QInputContextFactory::displayName (const QString & key) static
Returns a user friendly internationalized name of the QInputContext object specified by key.
You can, for example, use this name in a menu.
See also
keys(), QInputContext::identifierName()
Definition at line 305 of file qinputcontextfactory.cpp.
Referenced by QMultiInputContext::QMultiInputContext().
 {
     QString result;
 #if defined(Q_WS_X11) && !defined(QT_NO_XIM)
     if (key == QLatin1String("xim"))
         return QInputContext::tr( "XIM" );
 #endif
 #ifdef Q_WS_S60
     if (key == QLatin1String("coefep"))
         return QInputContext::tr( "FEP" );
 #endif
 #if defined(QT_NO_LIBRARY) || defined(QT_NO_SETTINGS)
     Q_UNUSED(key);
 #else
     if (QInputContextFactoryInterface *factory =
         qobject_cast<QInputContextFactoryInterface*>(loader()->instance(key)))
         return factory->displayName(key);
 #endif // QT_NO_LIBRARY
     return QString();
 }
keys()
QStringList QInputContextFactory::keys () static
Returns the list of keys this factory can create input contexts for.
The keys are the names used, for example, to identify and specify input methods for the input method switching mechanism. The names have to be consistent with QInputContext::identifierName(), and may only contain ASCII characters.
See also
create(), displayName(), QInputContext::identifierName()
Definition at line 184 of file qinputcontextfactory.cpp.
Referenced by QApplication::inputContext(), QMultiInputContext::QMultiInputContext(), and QApplicationPrivate::x11_apply_settings().
 {
     QStringList result;
 #if defined(Q_WS_X11) && !defined(QT_NO_XIM)
     result << QLatin1String("xim");
 #endif
 #if defined(Q_WS_WIN) && !defined(QT_NO_XIM)
     result << QLatin1String("win");
 #endif
 #if defined(Q_WS_MAC)
     result << QLatin1String("mac");
 #endif
 #if defined(Q_WS_S60)
     result << QLatin1String("coefep");
 #endif
 #ifndef QT_NO_LIBRARY
     result += loader()->keys();
 #endif // QT_NO_LIBRARY
     return result;
 }
languages()
QStringList QInputContextFactory::languages (const QString & key) static
Returns the languages supported by the QInputContext object specified by key.
The languages are expressed as language code (e.g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...). An input context that supports multiple languages can return all supported languages as a QStringList. The name has to be consistent with QInputContext::language().
This information may be used to optimize a user interface.
See also
keys(), QInputContext::language(), QLocale
Definition at line 261 of file qinputcontextfactory.cpp.
 {
     QStringList result;
 #if defined(Q_WS_X11) && !defined(QT_NO_XIM)
     if (key == QLatin1String("xim"))
         return QStringList(QString());
 #endif
 #if defined(Q_WS_WIN)
     if (key == QLatin1String("win"))
         return QStringList(QString());
 #endif
 #if defined(Q_WS_MAC)
     if (key == QLatin1String("mac"))
         return QStringList(QString());
 #endif
 #if defined(Q_WS_S60)
     if (key == QLatin1String("coefep"))
         {
         CAknInputLanguageList *langList = s60LangList();
         int count = langList->Count();
         for (int i = 0; i < count; ++i)
             {
             result.append(QString(qt_symbianLocaleName(langList->At(i)->LanguageCode())));
             }
         delete langList;
         }
 #endif
 #if defined(QT_NO_LIBRARY) || defined(QT_NO_SETTINGS)
     Q_UNUSED(key);
 #else
     if (QInputContextFactoryInterface *factory =
         qobject_cast<QInputContextFactoryInterface*>(loader()->instance(key)))
         result = factory->languages(key);
 #endif // QT_NO_LIBRARY
     return result;
 }
The documentation for this class was generated from the following files:
/src/gui/inputmethod/qinputcontextfactory.h
/src/gui/inputmethod/qinputcontextfactory.cpp