Qt 4.8: QListModel Class Reference
QListModel Class Reference
#include <qlistwidget_p.h>
Public Functions
QListWidgetItem * at (int row) const
void clear ()
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Returns the data stored under the given role for the item referred to by the index.
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
void ensureSorted (int column, Qt::SortOrder order, int start, int end)
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
QModelIndex index (QListWidgetItem *item) const
QModelIndex index (int row, int column=0, const QModelIndex &parent=QModelIndex()) const
Returns the index of the data in row and column with parent.
void insert (int row, QListWidgetItem *item)
void insert (int row, const QStringList &items)
bool insertRows (int row, int count=1, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
QMimeData * internalMimeData () const
void itemChanged (QListWidgetItem *item)
QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
void move (int srcRow, int dstRow)
QListModel (QListWidget *parent)
void remove (QListWidgetItem *item)
bool removeRows (int row, int count=1, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of rows under the given parent.
bool setData (const QModelIndex &index, const QVariant &value, int role)
Sets the role data for the item at index to value.
void sort (int column, Qt::SortOrder order)
Sorts the model by column in the given order.
Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
QListWidgetItem * take (int row)
~QListModel ()
Public Functions inherited from QAbstractListModel
QAbstractListModel (QObject *parent=0)
Constructs an abstract list model with the given parent.
~QAbstractListModel ()
Destroys the abstract list model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the data for the given role and section in the header with the specified orientation.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool itemGreaterThan (const QPair< QListWidgetItem *, int > &left, const QPair< QListWidgetItem *, int > &right)
static bool itemLessThan (const QPair< QListWidgetItem *, int > &left, const QPair< QListWidgetItem *, int > &right)
static QList< QListWidgetItem * >::iterator sortedInsertionIterator (const QList< QListWidgetItem *>::iterator &begin, const QList< QListWidgetItem *>::iterator &end, Qt::SortOrder order, QListWidgetItem *item)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Properties
QModelIndexList cachedIndexes
QList< QListWidgetItem * > items
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractListModel
QAbstractListModel (QAbstractItemModelPrivate &dd, QObject *parent)
Constructs an abstract list model with dd and the given parent.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 80 of file qlistwidget_p.h.
Constructors and Destructors
QListModel()
QListModel::QListModel (QListWidget * parent)
Definition at line 66 of file qlistwidget.cpp.
     : QAbstractListModel(parent)
 {
 }
~QListModel()
QListModel::~QListModel ()
Definition at line 71 of file qlistwidget.cpp.
 {
     clear();
 }
Functions
at()
QListWidgetItem * QListModel::at (int row) const
Definition at line 89 of file qlistwidget.cpp.
Referenced by mimeData().
 {
     return items.value(row);
 }
clear()
void QListModel::clear ()
Definition at line 76 of file qlistwidget.cpp.
Referenced by ~QListModel().
 {
     for (int i = 0; i < items.count(); ++i) {
         if (items.at(i)) {
             items.at(i)->d->theid = -1;
             items.at(i)->view = 0;
             delete items.at(i);
         }
     }
     items.clear();
     reset();
 }
data()
QVariant QListModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Returns the data stored under the given role for the item referred to by the index.
Note
If you do not have a value to return, return an invalid QVariant instead of returning 0.
See also
Qt::ItemDataRole, setData(), headerData()
Implements QAbstractItemModel.
Definition at line 217 of file qlistwidget.cpp.
 {
     if (!index.isValid() || index.row() >= items.count())
         return QVariant();
     return items.at(index.row())->data(role);
 }
dropMimeData()
bool QListModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractListModel.
Definition at line 438 of file qlistwidget.cpp.
Referenced by QListWidget::addItems().
 {
     Q_UNUSED(column);
     QListWidget *view = qobject_cast<QListWidget*>(QObject::parent());
     if (index.isValid())
         row = index.row();
     else if (row == -1)
         row = items.count();
     return view->dropMimeData(row, data, action);
 }
ensureSorted()
void QListModel::ensureSorted (int column, Qt::SortOrder order, int start, int end)
This function assumes that all items in the model except the items that are between (inclusive) start and end are sorted. With these assumptions, this function can ensure that the model is sorted in a much more efficient way than doing a naive 'sort everything'. (provided that the range is relatively small compared to the total number of items)
Definition at line 325 of file qlistwidget.cpp.
 {
     if (column != 0)
         return;
     int count = end - start + 1;
     QVector < QPair<QListWidgetItem*,int> > sorting(count);
     for (int i = 0; i < count; ++i) {
         sorting[i].first = items.at(start + i);
         sorting[i].second = start + i;
     }
     LessThan compare = (order == Qt::AscendingOrder ? &itemLessThan : &itemGreaterThan);
     qSort(sorting.begin(), sorting.end(), compare);
     QModelIndexList oldPersistentIndexes = persistentIndexList();
     QModelIndexList newPersistentIndexes = oldPersistentIndexes;
     QList<QListWidgetItem*> tmp = items;
     QList<QListWidgetItem*>::iterator lit = tmp.begin();
     bool changed = false;
     for (int i = 0; i < count; ++i) {
         int oldRow = sorting.at(i).second;
         QListWidgetItem *item = tmp.takeAt(oldRow);
         lit = sortedInsertionIterator(lit, tmp.end(), order, item);
         int newRow = qMax(lit - tmp.begin(), 0);
         lit = tmp.insert(lit, item);
         if (newRow != oldRow) {
             changed = true;
             for (int j = i + 1; j < count; ++j) {
                 int otherRow = sorting.at(j).second;
                 if (oldRow < otherRow && newRow >= otherRow)
                     --sorting[j].second;
                 else if (oldRow > otherRow && newRow <= otherRow)
                     ++sorting[j].second;
             }
             for (int k = 0; k < newPersistentIndexes.count(); ++k) {
                 QModelIndex pi = newPersistentIndexes.at(k);
                 int oldPersistentRow = pi.row();
                 int newPersistentRow = oldPersistentRow;
                 if (oldPersistentRow == oldRow)
                     newPersistentRow = newRow;
                 else if (oldRow < oldPersistentRow && newRow >= oldPersistentRow)
                     newPersistentRow = oldPersistentRow - 1;
                 else if (oldRow > oldPersistentRow && newRow <= oldPersistentRow)
                     newPersistentRow = oldPersistentRow + 1;
                 if (newPersistentRow != oldPersistentRow)
                     newPersistentIndexes[k] = createIndex(newPersistentRow,
                                                           pi.column(), pi.internalPointer());
             }
         }
     }
     if (changed) {
         emit layoutAboutToBeChanged();
         items = tmp;
         changePersistentIndexList(oldPersistentIndexes, newPersistentIndexes);
         emit layoutChanged();
     }
 }
flags()
Qt::ItemFlags QListModel::flags (const QModelIndex & index) const virtual
Returns the item flags for the given index.
The base class implementation returns a combination of flags that enables the item (ItemIsEnabled) and allows it to be selected (ItemIsSelectable).
See also
Qt::ItemFlags
Reimplemented from QAbstractItemModel.
Definition at line 282 of file qlistwidget.cpp.
Referenced by QListWidget::addItems().
 {
     if (!index.isValid() || index.row() >= items.count() || index.model() != this)
         return Qt::ItemIsDropEnabled; // we allow drops outside the items
     return items.at(index.row())->flags();
 }
index() [1/2]
QModelIndex QListModel::index (QListWidgetItem * item) const
Definition at line 192 of file qlistwidget.cpp.
Referenced by itemChanged().
 {
     if (!item || !item->view || static_cast<const QListModel *>(item->view->model()) != this
         || items.isEmpty())
         return QModelIndex();
     int row;
     const int theid = item->d->theid;
     if (theid >= 0 && theid < items.count() && items.at(theid) == item) {
         row = theid;
     } else { // we need to search for the item
         row = items.lastIndexOf(item);  // lastIndexOf is an optimization in favor of indexOf
         if (row == -1) // not found
             return QModelIndex();
         item->d->theid = row;
     }
     return createIndex(row, 0, item);
 }
index() [2/2]
QModelIndex QListModel::index (int row, int column = 0, const QModelIndex & parent = QModelIndex()) const virtual
Returns the index of the data in row and column with parent.
See also
parent()
Reimplemented from QAbstractListModel.
Definition at line 210 of file qlistwidget.cpp.
 {
     if (hasIndex(row, column, parent))
         return createIndex(row, column, items.at(row));
     return QModelIndex();
 }
insert() [1/2]
void QListModel::insert (int row, QListWidgetItem * item)
Definition at line 107 of file qlistwidget.cpp.
Referenced by insert().
 {
     if (!item)
         return;
     item->view = qobject_cast<QListWidget*>(QObject::parent());
     if (item->view && item->view->isSortingEnabled()) {
         // sorted insertion
         QList<QListWidgetItem*>::iterator it;
         it = sortedInsertionIterator(items.begin(), items.end(),
                                      item->view->sortOrder(), item);
         row = qMax(it - items.begin(), 0);
     } else {
         if (row < 0)
             row = 0;
         else if (row > items.count())
             row = items.count();
     }
     beginInsertRows(QModelIndex(), row, row);
     items.insert(row, item);
     item->d->theid = row;
     endInsertRows();
 }
insert() [2/2]
void QListModel::insert (int row, const QStringList & items)
Definition at line 131 of file qlistwidget.cpp.
 {
     const int count = labels.count();
     if (count <= 0)
         return;
     QListWidget *view = qobject_cast<QListWidget*>(QObject::parent());
     if (view && view->isSortingEnabled()) {
         // sorted insertion
         for (int i = 0; i < count; ++i) {
             QListWidgetItem *item = new QListWidgetItem(labels.at(i));
             insert(row, item);
         }
     } else {
         if (row < 0)
             row = 0;
         else if (row > items.count())
             row = items.count();
         beginInsertRows(QModelIndex(), row, row + count - 1);
         for (int i = 0; i < count; ++i) {
             QListWidgetItem *item = new QListWidgetItem(labels.at(i));
             item->d->theid = row;
             item->view = qobject_cast<QListWidget*>(QObject::parent());
             items.insert(row++, item);
         }
         endInsertRows();
     }
 }
insertRows()
bool QListModel::insertRows (int row, int count = 1, const QModelIndex & parent = QModelIndex()) virtual
On models that support this, inserts count rows into the model before the given row.
Note
The base class implementation of this function does nothing and returns false.
Items in the new row will be children of the item represented by the parent model index.
If row is 0, the rows are prepended to any existing rows in the parent.
If row is rowCount(), the rows are appended to any existing rows in the parent.
If parent has no children, a single column with count rows is inserted.
Returns true if the rows were successfully inserted; otherwise returns false.
If you implement your own model, you can reimplement this function if you want to support insertions. Alternatively, you can provide your own API for altering the data. In either case, you will need to call beginInsertRows() and endInsertRows() to notify other components that the model has changed.
See also
insertColumns(), removeRows(), beginInsertRows(), endInsertRows()
Reimplemented from QAbstractItemModel.
Definition at line 245 of file qlistwidget.cpp.
 {
     if (count < 1 || row < 0 || row > rowCount() || parent.isValid())
         return false;
     beginInsertRows(QModelIndex(), row, row + count - 1);
     QListWidget *view = qobject_cast<QListWidget*>(QObject::parent());
     QListWidgetItem *itm = 0;
     for (int r = row; r < row + count; ++r) {
         itm = new QListWidgetItem;
         itm->view = view;
         itm->d->theid = r;
         items.insert(r, itm);
     }
     endInsertRows();
     return true;
 }
internalMimeData()
QMimeData * QListModel::internalMimeData () const
Definition at line 419 of file qlistwidget.cpp.
 {
     return QAbstractItemModel::mimeData(cachedIndexes);
 }
itemChanged()
void QListModel::itemChanged (QListWidgetItem * item)
Definition at line 407 of file qlistwidget.cpp.
Referenced by QListWidget::addItems().
 {
     QModelIndex idx = index(item);
     emit dataChanged(idx, idx);
 }
itemData()
QMap< int, QVariant > QListModel::itemData (const QModelIndex & index) const virtual
Returns a map with values for all predefined roles in the model for the item at the given index.
Reimplement this function if you want to extend the default behavior of this function to include custom roles in the map.
See also
Qt::ItemDataRole, data()
Reimplemented from QAbstractItemModel.
Definition at line 232 of file qlistwidget.cpp.
 {
     QMap<int, QVariant> roles;
     if (!index.isValid() || index.row() >= items.count())
         return roles;
     QListWidgetItem *itm = items.at(index.row());
     for (int i = 0; i < itm->d->values.count(); ++i) {
         roles.insert(itm->d->values.at(i).role,
                      itm->d->values.at(i).value);
     }
     return roles;
 }
itemGreaterThan()
bool QListModel::itemGreaterThan (const QPair< QListWidgetItem *, int > & left, const QPair< QListWidgetItem *, int > & right) static
Definition at line 391 of file qlistwidget.cpp.
Referenced by ensureSorted(), and sort().
 {
     return (*right.first) < (*left.first);
 }
itemLessThan()
bool QListModel::itemLessThan (const QPair< QListWidgetItem *, int > & left, const QPair< QListWidgetItem *, int > & right) static
Definition at line 385 of file qlistwidget.cpp.
Referenced by ensureSorted(), and sort().
 {
     return (*left.first) < (*right.first);
 }
mimeData()
QMimeData * QListModel::mimeData (const QModelIndexList & indexes) const virtual
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
The formats used to describe the encoded data is obtained from the mimeTypes() function.
If the list of indexes is empty, or there are no supported MIME types, 0 is returned rather than a serialized empty list.
See also
mimeTypes(), dropMimeData()
Reimplemented from QAbstractItemModel.
Definition at line 424 of file qlistwidget.cpp.
Referenced by QListWidget::addItems().
 {
     QList<QListWidgetItem*> itemlist;
     for (int i = 0; i < indexes.count(); ++i)
         itemlist << at(indexes.at(i).row());
     const QListWidget *view = qobject_cast<const QListWidget*>(QObject::parent());
     cachedIndexes = indexes;
     QMimeData *mimeData = view->mimeData(itemlist);
     cachedIndexes.clear();
     return mimeData;
 }
mimeTypes()
QStringList QListModel::mimeTypes () const virtual
Returns a list of MIME types that can be used to describe a list of model indexes.
See also
mimeData()
Reimplemented from QAbstractItemModel.
Definition at line 413 of file qlistwidget.cpp.
Referenced by QListWidget::addItems().
 {
     const QListWidget *view = qobject_cast<const QListWidget*>(QObject::parent());
     return view->mimeTypes();
 }
move()
void QListModel::move (int srcRow, int dstRow)
Definition at line 172 of file qlistwidget.cpp.
 {
     if (srcRow == dstRow
         || srcRow < 0 || srcRow >= items.count()
         || dstRow < 0 || dstRow > items.count())
         return;
     if (!beginMoveRows(QModelIndex(), srcRow, srcRow, QModelIndex(), dstRow))
         return;
     if (srcRow < dstRow)
         --dstRow;
     items.move(srcRow, dstRow);
     endMoveRows();
 }
remove()
void QListModel::remove (QListWidgetItem * item)
Definition at line 94 of file qlistwidget.cpp.
 {
     if (!item)
         return;
     int row = items.indexOf(item); // ### use index(item) - it's faster
     Q_ASSERT(row != -1);
     beginRemoveRows(QModelIndex(), row, row);
     items.at(row)->d->theid = -1;
     items.at(row)->view = 0;
     items.removeAt(row);
     endRemoveRows();
 }
removeRows()
bool QListModel::removeRows (int row, int count = 1, const QModelIndex & parent = QModelIndex()) virtual
On models that support this, removes count rows starting with the given row under parent parent from the model.
Returns true if the rows were successfully removed; otherwise returns false.
The base class implementation does nothing and returns false.
If you implement your own model, you can reimplement this function if you want to support removing. Alternatively, you can provide your own API for altering the data.
See also
removeRow(), removeColumns(), insertColumns(), beginRemoveRows(), endRemoveRows()
Reimplemented from QAbstractItemModel.
Definition at line 265 of file qlistwidget.cpp.
 {
     if (count < 1 || row < 0 || (row + count) > rowCount() || parent.isValid())
         return false;
     beginRemoveRows(QModelIndex(), row, row + count - 1);
     QListWidgetItem *itm = 0;
     for (int r = row; r < row + count; ++r) {
         itm = items.takeAt(row);
         itm->view = 0;
         itm->d->theid = -1;
         delete itm;
     }
     endRemoveRows();
     return true;
 }
rowCount()
int QListModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of rows under the given parent.
When the parent is valid it means that rowCount is returning the number of children of parent.
Note
When implementing a table based model, rowCount() should return 0 when the parent is valid.
See also
columnCount()
Implements QAbstractItemModel.
Definition at line 187 of file qlistwidget.cpp.
Referenced by insertRows(), and removeRows().
 {
     return parent.isValid() ? 0 : items.count();
 }
setData()
bool QListModel::setData (const QModelIndex & index, const QVariant & value, int role) virtual
Sets the role data for the item at index to value.
Returns true if successful; otherwise returns false.
The dataChanged() signal should be emitted if the data was successfully set.
The base class implementation returns false. This function and data() must be reimplemented for editable models.
See also
Qt::ItemDataRole, data(), itemData()
Reimplemented from QAbstractItemModel.
Definition at line 224 of file qlistwidget.cpp.
 {
     if (!index.isValid() || index.row() >= items.count())
         return false;
     items.at(index.row())->setData(role, value);
     return true;
 }
sort()
void QListModel::sort (int column, Qt::SortOrder order) virtual
Sorts the model by column in the given order.
The base class implementation does nothing.
Reimplemented from QAbstractItemModel.
Definition at line 289 of file qlistwidget.cpp.
 {
     if (column != 0)
         return;
     emit layoutAboutToBeChanged();
     QVector < QPair<QListWidgetItem*,int> > sorting(items.count());
     for (int i = 0; i < items.count(); ++i) {
         QListWidgetItem *item = items.at(i);
         sorting[i].first = item;
         sorting[i].second = i;
     }
     LessThan compare = (order == Qt::AscendingOrder ? &itemLessThan : &itemGreaterThan);
     qSort(sorting.begin(), sorting.end(), compare);
     QModelIndexList fromIndexes;
     QModelIndexList toIndexes;
     for (int r = 0; r < sorting.count(); ++r) {
         QListWidgetItem *item = sorting.at(r).first;
         toIndexes.append(createIndex(r, 0, item));
         fromIndexes.append(createIndex(sorting.at(r).second, 0, sorting.at(r).first));
         items[r] = sorting.at(r).first;
     }
     changePersistentIndexList(fromIndexes, toIndexes);
     emit layoutChanged();
 }
sortedInsertionIterator()
QList< QListWidgetItem * >::iterator QListModel::sortedInsertionIterator (const QList< QListWidgetItem *>::iterator & begin, const QList< QListWidgetItem *>::iterator & end, Qt::SortOrder order, QListWidgetItem * item) static
Definition at line 397 of file qlistwidget.cpp.
Referenced by ensureSorted(), and insert().
 {
     if (order == Qt::AscendingOrder)
         return qLowerBound(begin, end, item, QListModelLessThan());
     return qLowerBound(begin, end, item, QListModelGreaterThan());
 }
supportedDropActions()
Qt::DropActions QListModel::supportedDropActions () const virtual
Returns the drop actions supported by this model.
Since
4.2
The default implementation returns Qt::CopyAction. Reimplement this function if you wish to support additional actions. You must also reimplement the dropMimeData() function to handle the additional operations.
See also
dropMimeData(), Qt::DropActions, {Using drag and drop with item views}
Reimplemented from QAbstractItemModel.
Definition at line 451 of file qlistwidget.cpp.
Referenced by QListWidget::addItems().
 {
     const QListWidget *view = qobject_cast<const QListWidget*>(QObject::parent());
     return view->supportedDropActions();
 }
take()
QListWidgetItem * QListModel::take (int row)
Definition at line 159 of file qlistwidget.cpp.
 {
     if (row < 0 || row >= items.count())
         return 0;
     beginRemoveRows(QModelIndex(), row, row);
     items.at(row)->d->theid = -1;
     items.at(row)->view = 0;
     QListWidgetItem *item = items.takeAt(row);
     endRemoveRows();
     return item;
 }
Properties
cachedIndexes
QModelIndexList QListModel::cachedIndexes mutable private
Definition at line 137 of file qlistwidget_p.h.
Referenced by internalMimeData(), and mimeData().
items
QList<QListWidgetItem*> QListModel::items private
Definition at line 134 of file qlistwidget_p.h.
Referenced by QListWidget::addItems(), at(), clear(), data(), dropMimeData(), ensureSorted(), flags(), index(), insert(), insertRows(), itemData(), move(), remove(), removeRows(), rowCount(), setData(), sort(), and take().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qlistwidget_p.h
/src/gui/itemviews/qlistwidget.cpp