Qt 4.8: QTreeWidgetItemIterator Class Reference
QTreeWidgetItemIterator Class Reference
The QTreeWidgetItemIterator class provides a way to iterate over the items in a QTreeWidget instance.
#include <qtreewidgetitemiterator.h>
Public Types
enum IteratorFlag {
All = 0x00000000, Hidden = 0x00000001, NotHidden = 0x00000002, Selected = 0x00000004,
Unselected = 0x00000008, Selectable = 0x00000010, NotSelectable = 0x00000020, DragEnabled = 0x00000040,
DragDisabled = 0x00000080, DropEnabled = 0x00000100, DropDisabled = 0x00000200, HasChildren = 0x00000400,
NoChildren = 0x00000800, Checked = 0x00001000, NotChecked = 0x00002000, Enabled = 0x00004000,
Disabled = 0x00008000, Editable = 0x00010000, NotEditable = 0x00020000, UserFlag = 0x01000000
}
These flags can be passed to a QTreeWidgetItemIterator constructor (OR-ed together if more than one is used), so that the iterator will only iterate over items that match the given flags.
Public Functions
QTreeWidgetItem * operator* () const
Dereference operator.
QTreeWidgetItemIterator & operator++ ()
The prefix ++ operator (++it) advances the iterator to the next matching item and returns a reference to the resulting iterator.
const QTreeWidgetItemIterator operator++ (int)
The postfix ++ operator (it++) advances the iterator to the next matching item and returns an iterator to the previously current item.
QTreeWidgetItemIterator & operator+= (int n)
Makes the iterator go forward by n matching items.
QTreeWidgetItemIterator & operator-- ()
The prefix – operator (–it) advances the iterator to the previous matching item and returns a reference to the resulting iterator.
const QTreeWidgetItemIterator operator-- (int)
The postfix – operator (it–) makes the preceding matching item current and returns an iterator to the previously current item.
QTreeWidgetItemIterator & operator-= (int n)
Makes the iterator go backward by n matching items.
QTreeWidgetItemIterator & operator= (const QTreeWidgetItemIterator &it)
Assignment.
QTreeWidgetItemIterator (const QTreeWidgetItemIterator &it)
Constructs an iterator for the same QTreeWidget as it.
QTreeWidgetItemIterator (QTreeWidget *widget, IteratorFlags flags=All)
Constructs an iterator for the given widget that uses the specified flags to determine which items are found during iteration.
QTreeWidgetItemIterator (QTreeWidgetItem *item, IteratorFlags flags=All)
Constructs an iterator for the given item that uses the specified flags to determine which items are found during iteration.
~QTreeWidgetItemIterator ()
Destroys the iterator.
Private Functions
bool matchesFlags (const QTreeWidgetItem *item) const
Properties
QTreeWidgetItem * current
QScopedPointer< QTreeWidgetItemIteratorPrivate > d_ptr
IteratorFlags flags
Friends
class QTreeModel
Detailed Description
The QTreeWidgetItemIterator class provides a way to iterate over the items in a QTreeWidget instance.
The iterator will walk the items in a pre-order traversal order, thus visiting the parent node before it continues to the child nodes.
For example, the following code examples each item in a tree, checking the text in the first column against a user-specified search string:
    QTreeWidgetItemIterator it(treeWidget);
    while (*it) {
        if ((*it)->text(0) == itemText)
            (*it)->setSelected(true);
        ++it;
    }
It is also possible to filter out certain types of node by passing certain flags to the constructor of QTreeWidgetItemIterator.
See also
QTreeWidget, {Model/View Programming}, QTreeWidgetItem
Definition at line 61 of file qtreewidgetitemiterator.h.
Enumerations
IteratorFlag
enum QTreeWidgetItemIterator::IteratorFlag
These flags can be passed to a QTreeWidgetItemIterator constructor (OR-ed together if more than one is used), so that the iterator will only iterate over items that match the given flags.
All
Hidden
NotHidden
Selected
Unselected
Selectable
NotSelectable
DragEnabled
DragDisabled
DropEnabled
DropDisabled
HasChildren
NoChildren
Checked
NotChecked
Enabled
Disabled
Editable
NotEditable
UserFlag
Enumerator
All
Hidden
NotHidden
Selected
Unselected
Selectable
NotSelectable
DragEnabled
DragDisabled
DropEnabled
DropDisabled
HasChildren
NoChildren
Checked
NotChecked
Enabled
Disabled
Editable
NotEditable
UserFlag
Definition at line 66 of file qtreewidgetitemiterator.h.
                       {
         All           = 0x00000000,
         Hidden        = 0x00000001,
         NotHidden     = 0x00000002,
         Selected      = 0x00000004,
         Unselected    = 0x00000008,
         Selectable    = 0x00000010,
         NotSelectable = 0x00000020,
         DragEnabled   = 0x00000040,
         DragDisabled  = 0x00000080,
         DropEnabled   = 0x00000100,
         DropDisabled  = 0x00000200,
         HasChildren   = 0x00000400,
         NoChildren    = 0x00000800,
         Checked       = 0x00001000,
         NotChecked    = 0x00002000,
         Enabled       = 0x00004000,
         Disabled      = 0x00008000,
         Editable      = 0x00010000,
         NotEditable   = 0x00020000,
         UserFlag      = 0x01000000 // The first flag that can be used by the user.
     };
Constructors and Destructors
QTreeWidgetItemIterator() [1/3]
QTreeWidgetItemIterator::QTreeWidgetItemIterator (const QTreeWidgetItemIterator & it)
Constructs an iterator for the same QTreeWidget as it.
The current iterator item is set to point on the current item of it.
Definition at line 79 of file qtreewidgetitemiterator.cpp.
Referenced by QTreeWidgetItemIteratorPrivate::ensureValidIterator().
     :  d_ptr(new QTreeWidgetItemIteratorPrivate(*(it.d_ptr))),
     current(it.current), flags(it.flags)
 {
     Q_D(QTreeWidgetItemIterator);
     Q_ASSERT(d->m_model);
     d->m_model->iterators.append(this);
 }
QTreeWidgetItemIterator() [2/3]
QTreeWidgetItemIterator::QTreeWidgetItemIterator (QTreeWidget * widget, IteratorFlags flags = All) explicit
Constructs an iterator for the given widget that uses the specified flags to determine which items are found during iteration.
The iterator is set to point to the first top-level item contained in the widget, or the next matching item if the top-level item doesn't match the flags.
See also
QTreeWidgetItemIterator::IteratorFlag
Definition at line 97 of file qtreewidgetitemiterator.cpp.
 : current(0), flags(flags)
 {
     Q_ASSERT(widget);
     QTreeModel *model = qobject_cast<QTreeModel*>(widget->model());
     Q_ASSERT(model);
     d_ptr.reset(new QTreeWidgetItemIteratorPrivate(this, model));
     model->iterators.append(this);
     if (!model->rootItem->children.isEmpty()) current = model->rootItem->child(0);
     if (current && !matchesFlags(current))
         ++(*this);
 }
QTreeWidgetItemIterator() [3/3]
QTreeWidgetItemIterator::QTreeWidgetItemIterator (QTreeWidgetItem * item, IteratorFlags flags = All) explicit
Constructs an iterator for the given item that uses the specified flags to determine which items are found during iteration.
The iterator is set to point to item, or the next matching item if item doesn't match the flags.
See also
QTreeWidgetItemIterator::IteratorFlag
Definition at line 119 of file qtreewidgetitemiterator.cpp.
     : d_ptr(new QTreeWidgetItemIteratorPrivate(
                 this, qobject_cast<QTreeModel*>(item->view->model()))),
       current(item), flags(flags)
 {
     Q_D(QTreeWidgetItemIterator);
     Q_ASSERT(item);
     QTreeModel *model = qobject_cast<QTreeModel*>(item->view->model());
     Q_ASSERT(model);
     model->iterators.append(this);
     // Initialize m_currentIndex and m_parentIndex as it would be if we had traversed from
     // the beginning.
     QTreeWidgetItem *parent = item;
     parent = parent->parent();
     QTreeWidgetItem *root = d->m_model->rootItem;
     d->m_currentIndex = (parent ? parent : root)->indexOfChild(item);
     while (parent) {
         QTreeWidgetItem *itm = parent;
         parent = parent->parent();
         const int index = (parent ? parent : root)->indexOfChild(itm);
         d->m_parentIndex.prepend(index);
     }
     if (current && !matchesFlags(current))
         ++(*this);
 }
~QTreeWidgetItemIterator()
QTreeWidgetItemIterator::~QTreeWidgetItemIterator ()
Destroys the iterator.
Definition at line 152 of file qtreewidgetitemiterator.cpp.
 {
     d_func()->m_model->iterators.removeAll(this);
 }
Functions
matchesFlags()
bool QTreeWidgetItemIterator::matchesFlags (const QTreeWidgetItem * item) const private
Warning
This function is not part of the public interface.
Definition at line 208 of file qtreewidgetitemiterator.cpp.
Referenced by operator++(), operator--(), and QTreeWidgetItemIterator().
 {
     if (!item)
         return false;
     if (flags == All)
         return true;
     {
         Qt::ItemFlags itemFlags = item->flags();
         if ((flags & Selectable) && !(itemFlags & Qt::ItemIsSelectable))
             return false;
         if ((flags & NotSelectable) && (itemFlags & Qt::ItemIsSelectable))
             return false;
         if ((flags & DragEnabled) && !(itemFlags & Qt::ItemIsDragEnabled))
             return false;
         if ((flags & DragDisabled) && (itemFlags & Qt::ItemIsDragEnabled))
             return false;
         if ((flags & DropEnabled) && !(itemFlags & Qt::ItemIsDropEnabled))
             return false;
         if ((flags & DropDisabled) && (itemFlags & Qt::ItemIsDropEnabled))
             return false;
         if ((flags & Enabled) && !(itemFlags & Qt::ItemIsEnabled))
             return false;
         if ((flags & Disabled) && (itemFlags & Qt::ItemIsEnabled))
             return false;
         if ((flags & Editable) && !(itemFlags & Qt::ItemIsEditable))
             return false;
         if ((flags & NotEditable) && (itemFlags & Qt::ItemIsEditable))
             return false;
     }
     if (flags & (Checked|NotChecked)) {
         // ### We only test the check state for column 0
         Qt::CheckState check = item->checkState(0);
         // PartiallyChecked matches as Checked.
         if ((flags & Checked) && (check == Qt::Unchecked))
             return false;
         if ((flags & NotChecked) && (check != Qt::Unchecked))
             return false;
     }
     if ((flags & HasChildren) && !item->childCount())
         return false;
     if ((flags & NoChildren) && item->childCount())
         return false;
     if ((flags & Hidden) && !item->isHidden())
         return false;
     if ((flags & NotHidden) && item->isHidden())
         return false;
     if ((flags & Selected) && !item->isSelected())
         return false;
     if ((flags & Unselected) && item->isSelected())
         return false;
     return true;
 }
operator*()
QTreeWidgetItem * QTreeWidgetItemIterator::operator* () const inline
Dereference operator.
Returns a pointer to the current item.
Definition at line 147 of file qtreewidgetitemiterator.h.
 {
     return current;
 }
operator++() [1/2]
QTreeWidgetItemIterator & QTreeWidgetItemIterator::operator++ ()
The prefix ++ operator (++it) advances the iterator to the next matching item and returns a reference to the resulting iterator.
Sets the current pointer to 0 if the current item is the last matching item.
Definition at line 181 of file qtreewidgetitemiterator.cpp.
 {
     if (current)
         do {
             current = d_func()->next(current);
         } while (current && !matchesFlags(current));
     return *this;
 }
operator++() [2/2]
const QTreeWidgetItemIterator QTreeWidgetItemIterator::operator++ (int) inline
The postfix ++ operator (it++) advances the iterator to the next matching item and returns an iterator to the previously current item.
Definition at line 115 of file qtreewidgetitemiterator.h.
 {
     QTreeWidgetItemIterator it = *this;
     ++(*this);
     return it;
 }
operator+=()
QTreeWidgetItemIterator & QTreeWidgetItemIterator::operator+= (int n) inline
Makes the iterator go forward by n matching items.
(If n is negative, the iterator goes backward.)
If the current item is beyond the last item, the current item pointer is set to 0. Returns the resulting iterator.
Definition at line 129 of file qtreewidgetitemiterator.h.
 {
     if (n < 0)
         return (*this) -= (-n);
     while (current && n--)
         ++(*this);
     return *this;
 }
operator--() [1/2]
QTreeWidgetItemIterator & QTreeWidgetItemIterator::operator-- ()
The prefix – operator (–it) advances the iterator to the previous matching item and returns a reference to the resulting iterator.
Sets the current pointer to 0 if the current item is the first matching item.
Definition at line 196 of file qtreewidgetitemiterator.cpp.
 {
     if (current)
         do {
             current = d_func()->previous(current);
         } while (current && !matchesFlags(current));
     return *this;
 }
operator--() [2/2]
const QTreeWidgetItemIterator QTreeWidgetItemIterator::operator-- (int) inline
The postfix – operator (it–) makes the preceding matching item current and returns an iterator to the previously current item.
Definition at line 122 of file qtreewidgetitemiterator.h.
 {
     QTreeWidgetItemIterator it = *this;
     --(*this);
     return it;
 }
operator-=()
QTreeWidgetItemIterator & QTreeWidgetItemIterator::operator-= (int n) inline
Makes the iterator go backward by n matching items.
(If n is negative, the iterator goes forward.)
If the current item is ahead of the last item, the current item pointer is set to 0. Returns the resulting iterator.
Definition at line 138 of file qtreewidgetitemiterator.h.
 {
     if (n < 0)
         return (*this) += (-n);
     while (current && n--)
         --(*this);
     return *this;
 }
operator=()
QTreeWidgetItemIterator & QTreeWidgetItemIterator::operator= (const QTreeWidgetItemIterator & it)
Assignment.
Makes a copy of it and returns a reference to its iterator.
Definition at line 162 of file qtreewidgetitemiterator.cpp.
 {
     Q_D(QTreeWidgetItemIterator);
     if (d_func()->m_model != it.d_func()->m_model) {
         d_func()->m_model->iterators.removeAll(this);
         it.d_func()->m_model->iterators.append(this);
     }
     current = it.current;
     flags = it.flags;
     d->operator=(*it.d_func());
     return *this;
 }
Friends and Related Functions
QTreeModel
friend class QTreeModel friend
Definition at line 63 of file qtreewidgetitemiterator.h.
Properties
current
QTreeWidgetItem* QTreeWidgetItemIterator::current private
Definition at line 110 of file qtreewidgetitemiterator.h.
Referenced by operator++(), operator--(), operator=(), and QTreeWidgetItemIterator().
d_ptr
QScopedPointer<QTreeWidgetItemIteratorPrivate> QTreeWidgetItemIterator::d_ptr private
Definition at line 109 of file qtreewidgetitemiterator.h.
Referenced by QTreeWidgetItemIterator().
flags
IteratorFlags QTreeWidgetItemIterator::flags private
Definition at line 111 of file qtreewidgetitemiterator.h.
Referenced by matchesFlags(), and operator=().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtreewidgetitemiterator.h
/src/gui/itemviews/qtreewidgetitemiterator.cpp