Qt 4.8: QPushButton Class Reference
QPushButton Class Reference
The QPushButton widget provides a command button.
#include <qpushbutton.h>
Public Slots
void showMenu ()
Shows (pops up) the associated popup menu.
Public Slots inherited from QAbstractButton
void animateClick (int msec=100)
Performs an animated click: the button is pressed immediately, and released msec milliseconds later (the default is 100 ms).
void click ()
Performs a click.
void setChecked (bool)
void setIconSize (const QSize &size)
void toggle ()
Toggles the state of a checkable button.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
bool autoDefault () const
bool isDefault () const
bool isFlat () const
QMenu * menu () const
Returns the button's associated popup menu or 0 if no popup menu has been set.
QSize minimumSizeHint () const
Reimplemented Function
QPushButton (QWidget *parent=0)
Constructs a push button with no text and a parent.
QPushButton (const QString &text, QWidget *parent=0)
Constructs a push button with the parent parent and the text text.
QPushButton (const QIcon &icon, const QString &text, QWidget *parent=0)
Constructs a push button with an icon and a text, and a parent.
void setAutoDefault (bool)
void setDefault (bool)
void setFlat (bool)
void setMenu (QMenu *menu)
Associates the popup menu menu with this push button.
QSize sizeHint () const
Reimplemented Function
~QPushButton ()
Destroys the push button.
Public Functions inherited from QAbstractButton
bool autoExclusive () const
bool autoRepeat () const
int autoRepeatDelay () const
int autoRepeatInterval () const
QButtonGroup * group () const
Returns the group that this button belongs to.
QIcon icon () const
QSize iconSize () const
bool isCheckable () const
bool isChecked () const
bool isDown () const
QAbstractButton (QWidget *parent=0)
Constructs an abstract button with a parent.
void setAutoExclusive (bool)
void setAutoRepeat (bool)
void setAutoRepeatDelay (int)
void setAutoRepeatInterval (int)
void setCheckable (bool)
void setDown (bool)
void setIcon (const QIcon &icon)
void setShortcut (const QKeySequence &key)
void setText (const QString &text)
QKeySequence shortcut () const
QString text () const
~QAbstractButton ()
Destroys the button.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
bool event (QEvent *e)
Reimplemented Function
void focusInEvent (QFocusEvent *)
Reimplemented Function
void focusOutEvent (QFocusEvent *)
Reimplemented Function
bool hitButton (const QPoint &pos) const
Reimplemented Function
void initStyleOption (QStyleOptionButton *option) const
Initialize option with the values from this QPushButton.
void keyPressEvent (QKeyEvent *)
Reimplemented Function
void paintEvent (QPaintEvent *)
Reimplemented Function
QPushButton (QPushButtonPrivate &dd, QWidget *parent=0)
Protected Functions inherited from QAbstractButton
void changeEvent (QEvent *e)
Reimplemented Function
virtual void checkStateSet ()
This virtual handler is called when setChecked() was called, unless it was called from within nextCheckState().
void keyReleaseEvent (QKeyEvent *e)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
void mousePressEvent (QMouseEvent *e)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
virtual void nextCheckState ()
This virtual handler is called when a button is clicked.
QAbstractButton (QAbstractButtonPrivate &dd, QWidget *parent=0)
void timerEvent (QTimerEvent *e)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool autoDefault
whether the push button is an auto default button
bool default
whether the push button is the default button
bool flat
whether the button border is raised
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Signals inherited from QAbstractButton
void clicked (bool checked=false)
This signal is emitted when the button is activated (i.e.
void pressed ()
This signal is emitted when the button is pressed down.
void released ()
This signal is emitted when the button is released.
void toggled (bool checked)
This signal is emitted whenever a checkable button changes its state.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QPushButton widget provides a command button.
The push button, or command button, is perhaps the most commonly used widget in any graphical user interface. Push (click) a button to command the computer to perform some action, or to answer a question. Typical buttons are OK, Apply, Cancel, Close, Yes, No and Help.
A command button is rectangular and typically displays a text label describing its action. A shortcut key can be specified by preceding the preferred character with an ampersand in the text. For example:
QPushButton *button = new QPushButton("&Download", this);
In this example the shortcut is Alt+D. See the QShortcut documentation for details (to display an actual ampersand, use '&&').
Push buttons display a textual label, and optionally a small icon. These can be set using the constructors and changed later using setText() and setIcon(). If the button is disabled the appearance of the text and icon will be manipulated with respect to the GUI style to make the button look "disabled".
A push button emits the signal clicked() when it is activated by the mouse, the Spacebar or by a keyboard shortcut. Connect to this signal to perform the button's action. Push buttons also provide less commonly used signals, for example, pressed() and released().
Command buttons in dialogs are by default auto-default buttons, i.e. they become the default push button automatically when they receive the keyboard input focus. A default button is a push button that is activated when the user presses the Enter or Return key in a dialog. You can change this with setAutoDefault(). Note that auto-default buttons reserve a little extra space which is necessary to draw a default-button indicator. If you do not want this space around your buttons, call setAutoDefault(false).
Being so central, the button widget has grown to accommodate a great many variations in the past decade. The Microsoft style guide now shows about ten different states of Windows push buttons and the text implies that there are dozens more when all the combinations of features are taken into consideration.
The most important modes or states are:
Available or not (grayed out, disabled).
Standard push button, toggling push button or menu button.
On or off (only for toggling push buttons).
Default or normal. The default button in a dialog can generally be "clicked" using the Enter or Return key.
Auto-repeat or not.
Pressed down or not.
As a general rule, use a push button when the application or dialog window performs an action when the user clicks on it (such as Apply, Cancel, Close and Help) and when the widget is supposed to have a wide, rectangular shape with a text label. Small, typically square buttons that change the state of the window rather than performing an action (such as the buttons in the top-right corner of the QFileDialog) are not command buttons, but tool buttons. Qt provides a special class (QToolButton) for these buttons.
If you need toggle behavior (see setCheckable()) or a button that auto-repeats the activation signal when being pushed down like the arrows in a scroll bar (see setAutoRepeat()), a command button is probably not what you want. When in doubt, use a tool button.
A variation of a command button is a menu button. These provide not just one command, but several, since when they are clicked they pop up a menu of options. Use the method setMenu() to associate a popup menu with a push button.
Other classes of buttons are option buttons (see QRadioButton) and check boxes (see QCheckBox).
Screenshot of a Macintosh style push button
A push button shown in the Macintosh Style Widget Gallery{Macintosh widget style}.
Note that when a button's width becomes smaller than 50 or its height becomes smaller than 30, the button's corners are changed from round to square. Use the setMinimumSize() function to prevent this behavior.
Screenshot of a Windows XP style push button
A push button shown in the Windows XP Style Widget Gallery{Windows XP widget style}.
Screenshot of a Plastique style push button
A push button shown in the Plastique Style Widget Gallery{Plastique widget style}.
In Qt, the QAbstractButton base class provides most of the modes and other API, and QPushButton provides GUI logic. See QAbstractButton for more information about the API.
See also
QToolButton, QRadioButton, QCheckBox, {fowler}{GUI Design Handbook: Push Button}
Definition at line 57 of file qpushbutton.h.
Constructors and Destructors
QPushButton() [1/4]
QPushButton::QPushButton (QWidget * parent = 0) explicit
Constructs a push button with no text and a parent.
Definition at line 257 of file qpushbutton.cpp.
Referenced by QPushButtonPrivate::hitButton().
     : QAbstractButton(*new QPushButtonPrivate, parent)
 {
     Q_D(QPushButton);
     d->init();
 }
QPushButton() [2/4]
QPushButton::QPushButton (const QString & text, QWidget * parent = 0) explicit
Constructs a push button with the parent parent and the text text.
Definition at line 269 of file qpushbutton.cpp.
     : QAbstractButton(*new QPushButtonPrivate, parent)
 {
     Q_D(QPushButton);
     setText(text);
     d->init();
 }
QPushButton() [3/4]
QPushButton::QPushButton (const QIcon & icon, const QString & text, QWidget * parent = 0)
Constructs a push button with an icon and a text, and a parent.
Note that you can also pass a QPixmap object as an icon (thanks to the implicit type conversion provided by C++).
Definition at line 285 of file qpushbutton.cpp.
     : QAbstractButton(*new QPushButtonPrivate, parent)
 {
     Q_D(QPushButton);
     setText(text);
     setIcon(icon);
     d->init();
 }
~QPushButton()
QPushButton::~QPushButton ()
Destroys the push button.
Definition at line 306 of file qpushbutton.cpp.
 {
 }
QPushButton() [4/4]
QPushButton::QPushButton (QPushButtonPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 296 of file qpushbutton.cpp.
     : QAbstractButton(dd, parent)
 {
     Q_D(QPushButton);
     d->init();
 }
Functions
autoDefault()
bool QPushButton::autoDefault () const
Referenced by focusInEvent(), focusOutEvent(), initStyleOption(), keyPressEvent(), setAutoDefault(), and sizeHint().
event()
bool QPushButton::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 676 of file qpushbutton.cpp.
Referenced by QCommandLinkButton::event().
 {
     Q_D(QPushButton);
     if (e->type() == QEvent::ParentChange) {
         if (QDialog *dialog = d->dialogParent()) {
             if (d->defaultButton)
                 dialog->d_func()->setMainDefault(this);
         }
     } else if (e->type() == QEvent::StyleChange
 #ifdef Q_WS_MAC
                || e->type() == QEvent::MacSizeChange
 #endif
                ) {
         d->resetLayoutItemMargins();
         updateGeometry();
     } else if (e->type() == QEvent::PolishRequest) {
         updateGeometry();
     }
     return QAbstractButton::event(e);
 }
focusInEvent()
void QPushButton::focusInEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 489 of file qpushbutton.cpp.
 {
     Q_D(QPushButton);
     if (e->reason() != Qt::PopupFocusReason && autoDefault() && !d->defaultButton) {
         d->defaultButton = true;
         QDialog *dlg = qobject_cast<QDialog*>(window());
         if (dlg)
             dlg->d_func()->setDefault(this);
     }
     QAbstractButton::focusInEvent(e);
 }
focusOutEvent()
void QPushButton::focusOutEvent (QFocusEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 504 of file qpushbutton.cpp.
 {
     Q_D(QPushButton);
     if (e->reason() != Qt::PopupFocusReason && autoDefault() && d->defaultButton) {
         QDialog *dlg = qobject_cast<QDialog*>(window());
         if (dlg)
             dlg->d_func()->setDefault(0);
         else
             d->defaultButton = false;
     }
     QAbstractButton::focusOutEvent(e);
 #ifndef QT_NO_MENU
     if (d->menu && d->menu->isVisible())        // restore pressed status
         setDown(true);
 #endif
 }
hitButton()
bool QPushButton::hitButton (const QPoint & pos) const protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 699 of file qpushbutton.cpp.
 {
     QStyleOptionButton opt;
     initStyleOption(&opt);
     if (qt_mac_buttonIsRenderedFlat(this, &opt))
         return QAbstractButton::hitButton(pos);
     // Now that we know we are using the native style, let's proceed.
     Q_D(const QPushButton);
     QPushButtonPrivate *nonConst = const_cast<QPushButtonPrivate *>(d);
     // In OSX buttons are round, which causes the hit method to be special.
     // We cannot simply relay on detecting if something is inside the rect or not,
     // we need to check if it is inside the "rounded area" or not. A point might
     // be inside the rect but not inside the rounded area.
     // Notice this method is only reimplemented for OSX.
     return nonConst->hitButton(pos);
 }
initStyleOption()
void QPushButton::initStyleOption (QStyleOptionButton * option) const protected
Initialize option with the values from this QPushButton.
This method is useful for subclasses when they need a QStyleOptionButton, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom()
Definition at line 329 of file qpushbutton.cpp.
Referenced by hitButton(), QCommandLinkButton::paintEvent(), paintEvent(), and sizeHint().
 {
     if (!option)
         return;
     Q_D(const QPushButton);
     option->initFrom(this);
     option->features = QStyleOptionButton::None;
     if (d->flat)
         option->features |= QStyleOptionButton::Flat;
 #ifndef QT_NO_MENU
     if (d->menu)
         option->features |= QStyleOptionButton::HasMenu;
 #endif
     if (autoDefault() || d->defaultButton)
         option->features |= QStyleOptionButton::AutoDefaultButton;
     if (d->defaultButton)
         option->features |= QStyleOptionButton::DefaultButton;
     if (d->down || d->menuOpen)
         option->state |= QStyle::State_Sunken;
     if (d->checked)
         option->state |= QStyle::State_On;
     if (!d->flat && !d->down)
         option->state |= QStyle::State_Raised;
     option->text = d->text;
     option->icon = d->icon;
     option->iconSize = iconSize();
 }
isDefault()
bool QPushButton::isDefault () const
Definition at line 394 of file qpushbutton.cpp.
Referenced by QDialogButtonBox::event(), QMacStylePrivate::eventFilter(), QDialog::keyPressEvent(), QAccessibleButton::state(), QAccessibleButton::text(), and QMacStylePrivate::timerEvent().
 {
     Q_D(const QPushButton);
     return d->defaultButton;
 }
isFlat()
bool QPushButton::isFlat () const
Definition at line 669 of file qpushbutton.cpp.
 {
     Q_D(const QPushButton);
     return d->flat;
 }
keyPressEvent()
void QPushButton::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 470 of file qpushbutton.cpp.
 {
     Q_D(QPushButton);
     switch (e->key()) {
     case Qt::Key_Enter:
     case Qt::Key_Return:
         if (autoDefault() || d->defaultButton) {
             click();
             break;
         }
         // fall through
     default:
         QAbstractButton::keyPressEvent(e);
     }
 }
menu()
QMenu * QPushButton::menu () const
Returns the button's associated popup menu or 0 if no popup menu has been set.
See also
setMenu()
Definition at line 567 of file qpushbutton.cpp.
Referenced by QPushButtonPrivate::_q_popupPressed(), QPushButtonPrivate::adjustedMenuPosition(), AccessibleFactory::create(), QAccessibleButton::doAction(), setMenu(), sizeHint(), and QAccessibleButton::state().
 {
     Q_D(const QPushButton);
     return d->menu;
 }
minimumSizeHint()
QSize QPushButton::minimumSizeHint () const virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 452 of file qpushbutton.cpp.
paintEvent()
void QPushButton::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Implements QAbstractButton.
Definition at line 460 of file qpushbutton.cpp.
 {
     QStylePainter p(this);
     QStyleOptionButton option;
     initStyleOption(&option);
     p.drawControl(QStyle::CE_PushButton, option);
 }
setAutoDefault()
void QPushButton::setAutoDefault (bool enable)
Definition at line 358 of file qpushbutton.cpp.
Referenced by QWizardPrivate::ensureButton().
 {
     Q_D(QPushButton);
     uint state = enable ? QPushButtonPrivate::On : QPushButtonPrivate::Off;
     if (d->autoDefault != QPushButtonPrivate::Auto && d->autoDefault == state)
         return;
     d->autoDefault = state;
     d->sizeHint = QSize();
     update();
     updateGeometry();
 }
setDefault()
void QPushButton::setDefault (bool enable)
Definition at line 378 of file qpushbutton.cpp.
Referenced by QPrintPropertiesDialog::addItemToOptions(), QDialogButtonBox::event(), QDialogPrivate::hideDefault(), QFontDialogPrivate::init(), QDialogPrivate::setDefault(), QMessageBox::setDefaultButton(), QDialog::setVisible(), and QCoreFuriCuri::timerEvent().
 {
     Q_D(QPushButton);
     if (d->defaultButton == enable)
         return;
     d->defaultButton = enable;
     if (d->defaultButton) {
         if (QDialog *dlg = d->dialogParent())
             dlg->d_func()->setMainDefault(this);
     }
     update();
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::StateChanged);
 #endif
 }
setFlat()
void QPushButton::setFlat (bool flat)
Definition at line 657 of file qpushbutton.cpp.
 {
     Q_D(QPushButton);
     if (d->flat == flat)
         return;
     d->flat = flat;
     d->resetLayoutItemMargins();
     d->sizeHint = QSize();
     update();
     updateGeometry();
 }
setMenu()
void QPushButton::setMenu (QMenu * menu)
Associates the popup menu menu with this push button.
This turns the button into a menu button, which in some styles will produce a small triangle to the right of the button's text.
Ownership of the menu is not transferred to the push button.
Screenshot of a Plastique style push button with popup menu.
Screenshot of a Cleanlooks style push button with popup menu.
Push buttons with popup menus shown in the Plastique Style Widget Gallery{Plastique widget style} (left) and Cleanlooks Style Widget Gallery{Cleanlooks widget style} (right).
See also
menu()
Definition at line 540 of file qpushbutton.cpp.
 {
     Q_D(QPushButton);
     if (menu == d->menu)
         return;
     if (menu && !d->menu) {
         connect(this, SIGNAL(pressed()), this, SLOT(_q_popupPressed()), Qt::UniqueConnection);
     }
     if (d->menu)
         removeAction(d->menu->menuAction());
     d->menu = menu;
     if (d->menu)
         addAction(d->menu->menuAction());
     d->resetLayoutItemMargins();
     d->sizeHint = QSize();
     update();
     updateGeometry();
 }
showMenu
void QPushButton::showMenu () slot
Shows (pops up) the associated popup menu.
If there is no such menu, this function does nothing. This function does not return until the popup menu has been closed by the user.
Definition at line 578 of file qpushbutton.cpp.
Referenced by QAccessibleButton::doAction().
 {
     Q_D(QPushButton);
     if (!d || !d->menu)
         return;
     setDown(true);
     d->_q_popupPressed();
 }
sizeHint()
QSize QPushButton::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 403 of file qpushbutton.cpp.
Referenced by QProgressDialogPrivate::layout(), minimumSizeHint(), and QCommandLinkButton::sizeHint().
 {
     Q_D(const QPushButton);
     if (d->sizeHint.isValid() && d->lastAutoDefault == autoDefault())
         return d->sizeHint;
     d->lastAutoDefault = autoDefault();
     ensurePolished();
     int w = 0, h = 0;
     QStyleOptionButton opt;
     initStyleOption(&opt);
     // calculate contents size...
 #ifndef QT_NO_ICON
     bool showButtonBoxIcons = qobject_cast<QDialogButtonBox*>(parentWidget())
                           && style()->styleHint(QStyle::SH_DialogButtonBox_ButtonsHaveIcons);
     if (!icon().isNull() || showButtonBoxIcons) {
         int ih = opt.iconSize.height();
         int iw = opt.iconSize.width() + 4;
         w += iw;
         h = qMax(h, ih);
     }
 #endif
     QString s(text());
     bool empty = s.isEmpty();
     if (empty)
         s = QString::fromLatin1("XXXX");
     QFontMetrics fm = fontMetrics();
     QSize sz = fm.size(Qt::TextShowMnemonic, s);
     if(!empty || !w)
         w += sz.width();
     if(!empty || !h)
         h = qMax(h, sz.height());
     opt.rect.setSize(QSize(w, h)); // PM_MenuButtonIndicator depends on the height
 #ifndef QT_NO_MENU
     if (menu())
         w += style()->pixelMetric(QStyle::PM_MenuButtonIndicator, &opt, this);
 #endif
     d->sizeHint = (style()->sizeFromContents(QStyle::CT_PushButton, &opt, QSize(w, h), this).
                   expandedTo(QApplication::globalStrut()));
     return d->sizeHint;
 }
Properties
autoDefault
bool QPushButton::autoDefault private
whether the push button is an auto default button
If this property is set to true then the push button is an auto default button.
In some GUI styles a default button is drawn with an extra frame around it, up to 3 pixels or more. Qt automatically keeps this space free around auto-default buttons, i.e. auto-default buttons may have a slightly larger size hint.
This property's default is true for buttons that have a QDialog parent; otherwise it defaults to false.
See the default property for details of how default and auto-default interact.
Definition at line 61 of file qpushbutton.h.
Referenced by QMacStylePrivate::eventFilter(), QDialog::setVisible(), and QMacStylePrivate::timerEvent().
default
QPushButton::default private
whether the push button is the default button
Default and autodefault buttons decide what happens when the user presses enter in a dialog.
A button with this property set to true (i.e., the dialog's default button,) will automatically be pressed when the user presses enter, with one exception: if an autoDefault button currently has focus, the autoDefault button is pressed. When the dialog has autoDefault buttons but no default button, pressing enter will press either the autoDefault button that currently has focus, or if no button has focus, the next autoDefault button in the focus chain.
In a dialog, only one push button at a time can be the default button. This button is then displayed with an additional frame (depending on the GUI style).
The default button behavior is provided only in dialogs. Buttons can always be clicked from the keyboard by pressing Spacebar when the button has focus.
If the default property is set to false on the current default button while the dialog is visible, a new default will automatically be assigned the next time a pushbutton in the dialog receives focus.
This property's default is false.
Definition at line 62 of file qpushbutton.h.
flat
QPushButton::flat private
whether the button border is raised
This property's default is false. If this property is set, most styles will not paint the button background unless the button is being pressed. setAutoFillBackground() can be used to ensure that the background is filled using the QPalette::Button brush.
Definition at line 63 of file qpushbutton.h.
Referenced by setFlat().
The documentation for this class was generated from the following files:
/src/gui/widgets/qpushbutton.h
/src/gui/widgets/qpushbutton.cpp