Qt 4.8: QWSDisplay Class Reference
QWSDisplay Class Reference
The QWSDisplay class provides a display for QWS; it is an internal class.
#include <qwsdisplay_qws.h>
Classes
class Data
Public Functions
void addProperty (int winId, int property)
void convertSelection (int winId, int selectionProperty, const QString &mimeTypes)
void defineCursor (int id, const QBitmap &curs, const QBitmap &mask, int hotX, int hotY)
int depth () const
void destroyCursor (int id)
void destroyRegion (int winId)
bool eventPending () const
void flushCommands ()
uchar * frameBuffer () const
QWSEvent * getEvent ()
bool getProperty (int winId, int property, char *&data, int &len)
void grabKeyboard (QWidget *w, bool grab)
void grabMouse (QWidget *w, bool grab)
int height () const
void moveRegion (int winId, int dx, int dy)
void nameRegion (int winId, const QString &n, const QString &c)
int pixmapDepth () const
void playSoundFile (const QString &)
QWSDisplay ()
void registerChannel (const QString &channel)
void removeProperty (int winId, int property)
void repaintRegion (int winId, int windowFlags, bool opaque, QRegion)
void requestFocus (int winId, bool get)
void requestRegion (int winId, const QString &surfacekey, const QByteArray &surfaceData, const QRegion &region)
void resetIM ()
void selectCursor (QWidget *w, unsigned int id)
void sendFontCommand (int type, const QByteArray &fontName)
void sendIMMouseEvent (int index, bool isPress)
void sendIMResponse (int winId, int property, const QVariant &result)
void sendIMUpdate (int type, int winId, int widgetid)
void sendMessage (const QString &channel, const QString &msg, const QByteArray &data)
void setAltitude (int winId, int altitude, bool fixed=false)
void setCursorPosition (int x, int y)
void setIdentity (const QString &appName)
void setOpacity (int winId, int opacity)
void setProperty (int winId, int property, int mode, const QByteArray &data)
void setProperty (int winId, int property, int mode, const char *data)
void setSelectionOwner (int winId, const QTime &time)
void setWindowCaption (QWidget *w, const QString &)
uchar * sharedRam () const
int sharedRamSize () const
bool supportsDepth (int) const
int takeId ()
QWSQCopMessageEvent * waitForQCopResponse ()
int width () const
int windowAt (const QPoint &)
QList< QWSWindowInfo > windowList ()
~QWSDisplay ()
Static Public Functions
static void grab ()
static void grab (bool write)
static bool grabbed ()
static bool initLock (const QString &filename, bool create=false)
static QWSDisplay * instance ()
static void setRawMouseEventFilter (void(*filter)(QWSMouseEvent *))
static void setTransformation (int transformation, int screenNo=-1)
static void ungrab ()
Properties
Data * d
char * getPropertyData
int getPropertyLen
Static Private Attributes
static QLock * lock = 0
Friends
class Data
class QApplication
class QCopChannel
void qt_app_reinit (const QString &newAppName)
int qt_fork_qapplication ()
class QWSDirectPainterSurface
class QWSEmbedWidget
class QWSEmbedWidgetPrivate
class QWSMemorySurface
class QWSOnScreenSurface
Detailed Description
The QWSDisplay class provides a display for QWS; it is an internal class.
Warning
This function is not part of the public interface.
Definition at line 82 of file qwsdisplay_qws.h.
Constructors and Destructors
QWSDisplay()
QWSDisplay::QWSDisplay ()
Definition at line 1295 of file qapplication_qws.cpp.
 {
     d = new Data(0, qws_single_process);
 }
~QWSDisplay()
QWSDisplay::~QWSDisplay ()
Definition at line 1300 of file qapplication_qws.cpp.
 {
     delete d;
     delete lock;
     lock = 0;
 }
Functions
addProperty()
void QWSDisplay::addProperty (int winId, int property)
Definition at line 1367 of file qapplication_qws.cpp.
Referenced by qwsInitClipboard().
 {
     QWSAddPropertyCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.property = property;
     d->sendCommand(cmd);
 }
convertSelection()
void QWSDisplay::convertSelection (int winId, int selectionProperty, const QString & mimeTypes)
Definition at line 1665 of file qapplication_qws.cpp.
 {
 #ifdef QT_NO_QWS_PROPERTIES
     Q_UNUSED(mimeTypes);
 #else
     // ### we need the atom/property thingy like in X here
     addProperty(winId, QT_QWS_PROPERTY_CONVERTSELECTION);
     setProperty(winId, QT_QWS_PROPERTY_CONVERTSELECTION,
                  int(QWSPropertyManager::PropReplace), mimeTypes.toLatin1());
 #endif
     QWSConvertSelectionCommand cmd;
     cmd.simpleData.requestor = winId;
     cmd.simpleData.selection = selectionProperty;
     cmd.simpleData.mimeTypes = QT_QWS_PROPERTY_CONVERTSELECTION;
     d->sendCommand(cmd);
 }
defineCursor()
void QWSDisplay::defineCursor (int id, const QBitmap & curs, const QBitmap & mask, int hotX, int hotY)
Definition at line 1682 of file qapplication_qws.cpp.
 {
     const QImage cursImg = curs.toImage().convertToFormat(QImage::Format_MonoLSB);
     const QImage maskImg = mask.toImage().convertToFormat(QImage::Format_MonoLSB);
     QWSDefineCursorCommand cmd;
     cmd.simpleData.width = curs.width();
     cmd.simpleData.height = curs.height();
     cmd.simpleData.hotX = hotX;
     cmd.simpleData.hotY = hotY;
     cmd.simpleData.id = id;
     // must copy each scanline since there might be gaps between them
     const int height = curs.height();
     const int width = curs.width();
     const int dst_bpl = (width + 7) / 8;
     int dataLen = dst_bpl * height;
     uchar *data = new uchar[dataLen*2];
     uchar *dst = data;
     int src_bpl = cursImg.bytesPerLine();
     const uchar *cursSrc = cursImg.bits();
     for (int i = 0; i < height; ++i) {
         memcpy(dst, cursSrc + i*src_bpl, dst_bpl);
         dst += dst_bpl;
     }
     src_bpl = maskImg.bytesPerLine();
     const uchar *maskSrc = maskImg.bits();
     for (int i = 0; i < height; ++i) {
         memcpy(dst, maskSrc + i*src_bpl, dst_bpl);
         dst += dst_bpl;
     }
     cmd.setData(reinterpret_cast<char*>(data), dataLen*2);
     delete [] data;
     d->sendCommand(cmd);
 }
depth()
int QWSDisplay::depth () const
Definition at line 1359 of file qapplication_qws.cpp.
 { return qt_screen->depth(); }
destroyCursor()
void QWSDisplay::destroyCursor (int id)
Definition at line 1724 of file qapplication_qws.cpp.
 {
     QWSDefineCursorCommand cmd;
     cmd.simpleData.width = 0;
     cmd.simpleData.height = 0;
     cmd.simpleData.hotX = 0;
     cmd.simpleData.hotY = 0;
     cmd.simpleData.id = id;
     cmd.setData(0, 0);
     d->sendCommand(cmd);
 }
destroyRegion()
void QWSDisplay::destroyRegion (int winId)
Definition at line 1572 of file qapplication_qws.cpp.
Referenced by isServerProcess(), and QWSDirectPainterSurface::~QWSDirectPainterSurface().
 {
     QWSRegionDestroyCommand cmd;
     cmd.simpleData.windowid = winId;
     if (d->directServerConnection()) {
         qwsServer->d_func()->destroy_region(&cmd);
     } else {
         d->sendCommand(cmd);
     }
 }
eventPending()
bool QWSDisplay::eventPending () const
Definition at line 1334 of file qapplication_qws.cpp.
Referenced by QEventDispatcherQWS::hasPendingEvents(), QEventDispatcherQWS::processEvents(), qwsEventSourceCheck(), qwsEventSourceDispatch(), and qwsEventSourcePrepare().
 {
 #ifndef QT_NO_QWS_MULTIPROCESS
     d->flush();
 #endif
     d->fillQueue();
     return d->queueNotEmpty();
 }
flushCommands()
void QWSDisplay::flushCommands ()
Definition at line 1762 of file qapplication_qws.cpp.
Referenced by QCopChannel::flush().
 {
     qt_fbdpy->d->flushCommands();
 }
frameBuffer()
uchar * QWSDisplay::frameBuffer () const
Definition at line 1356 of file qapplication_qws.cpp.
 { return qt_screen->base(); }
getEvent()
QWSEvent * QWSDisplay::getEvent ()
Definition at line 1347 of file qapplication_qws.cpp.
Referenced by QEventDispatcherQWS::processEvents(), and qwsEventSourceDispatch().
 {
     d->fillQueue();
     Q_ASSERT(d->queueNotEmpty());
     QWSEvent* e = d->dequeue();
     return e;
 }
getProperty()
bool QWSDisplay::getProperty (int winId, int property, char *& data, int & len)
Definition at line 1407 of file qapplication_qws.cpp.
 {
     if (d->directServerConnection()) {
         const char *propertyData;
         bool retval = qwsServer->d_func()->get_property(winId, property, propertyData, len);
         if (len <= 0) {
             data = 0;
         } else {
             data = new char[len];
             memcpy(data, propertyData, len) ;
         }
         return retval;
     }
     QWSGetPropertyCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.property = property;
     d->sendCommand(cmd);
     getPropertyLen = -2;
     getPropertyData = 0;
 #ifndef QT_NO_QWS_MULTIPROCESS
     d->waitForPropertyReply();
 #endif
     len = getPropertyLen;
     data = getPropertyData;
     getPropertyLen = -2;
     getPropertyData = 0;
     return len != -1;
 }
grab() [1/2]
void QWSDisplay::grab () static
Definition at line 1312 of file qapplication_qws.cpp.
Referenced by QWSServer::beginDisplayReconfigure(), QTransformedScreen::blit(), QScreen::blit(), QLinuxFbScreen::cache(), QLinuxFbScreen::clearCache(), QLinuxFbScreen::deleteEntry(), QWSWindowSurface::flush(), QDirectPainter::lock(), QWSDirectPainterSurface::lock(), QScreen::solidFill(), QWSServerPrivate::update_regions(), QWSDisplay::Data::waitForRegionEvents(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     lock->lock(QLock::Read);
 }
grab() [2/2]
void QWSDisplay::grab (bool write) static
Definition at line 1317 of file qapplication_qws.cpp.
 {
     lock->lock(write ? QLock::Write : QLock::Read);
 }
grabbed()
bool QWSDisplay::grabbed () static
Definition at line 1307 of file qapplication_qws.cpp.
Referenced by QWSDisplay::Data::waitForRegionEvents().
 {
     return lock->locked();
 }
grabKeyboard()
void QWSDisplay::grabKeyboard (QWidget * w, bool grab)
Definition at line 1831 of file qapplication_qws.cpp.
 {
     QWidget *top = w->window();
     QWSGrabKeyboardCommand cmd;
 #ifdef QT_DEBUG
     memset(cmd.simpleDataPtr, 0, sizeof(cmd.simpleData)); //shut up Valgrind
 #endif
     cmd.simpleData.windowid = top->winId();
     cmd.simpleData.grab = grab;
     d->sendCommand(cmd);
     d->flush();
 }
grabMouse()
void QWSDisplay::grabMouse (QWidget * w, bool grab)
Definition at line 1818 of file qapplication_qws.cpp.
 {
     QWidget *top = w->window();
     QWSGrabMouseCommand cmd;
 #ifdef QT_DEBUG
     memset(cmd.simpleDataPtr, 0, sizeof(cmd.simpleData)); //shut up Valgrind
 #endif
     cmd.simpleData.windowid = top->winId();
     cmd.simpleData.grab = grab;
     d->sendCommand(cmd);
     d->flush();
 }
height()
int QWSDisplay::height () const
Definition at line 1358 of file qapplication_qws.cpp.
 { return qt_screen->height(); }
initLock()
bool QWSDisplay::initLock (const QString & filename, bool create = false) static
Definition at line 1639 of file qapplication_qws.cpp.
Referenced by QWSDisplay::Data::init(), and QWSDisplay::Data::reinit().
 {
     if (!lock) {
         lock = new QLock(filename, 'd', create);
         if (!lock->isValid()) {
             delete lock;
             lock = 0;
             return false;
         }
     }
     return true;
 }
instance()
static QWSDisplay* QWSDisplay::instance () inline static
Definition at line 88 of file qwsdisplay_qws.h.
Referenced by QWSDirectPainterSurface::beginPaint(), effectiveState(), QWSDirectPainterSurface::flush(), QWSDirectPainterSurface::hasPendingRegionEvents(), QWSEmbedWidgetPrivate::resize(), QWSDirectPainterSurface::setRegion(), QScreen::setTransformation(), QWSEmbedWidgetPrivate::updateWindow(), QWSWindowSurface::winId(), QWSDirectPainterSurface::~QWSDirectPainterSurface(), and QWSEmbedWidget::~QWSEmbedWidget().
 { return qt_fbdpy; }
moveRegion()
void QWSDisplay::moveRegion (int winId, int dx, int dy)
Definition at line 1557 of file qapplication_qws.cpp.
Referenced by effectiveState().
 {
     QWSRegionMoveCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.dx = dx;
     cmd.simpleData.dy = dy;
     if (d->directServerConnection()) {
         qwsServer->d_func()->move_region(&cmd);
     } else {
         d->sendSynchronousCommand(cmd);
     }
 //    d->offsetPendingExpose(winId, QPoint(cmd.simpleData.dx, cmd.simpleData.dy));
 }
nameRegion()
void QWSDisplay::nameRegion (int winId, const QString & n, const QString & c)
Definition at line 1499 of file qapplication_qws.cpp.
Referenced by isServerProcess(), QWSDirectPainterSurface::QWSDirectPainterSurface(), QWSYellowSurface::QWSYellowSurface(), and QWSWindowSurface::winId().
 {
     QWSRegionNameCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.setName(n, c);
     if (d->directServerConnection())
         qwsServer->d_func()->name_region(&cmd);
     else
         d->sendCommand(cmd);
 }
pixmapDepth()
int QWSDisplay::pixmapDepth () const
Definition at line 1360 of file qapplication_qws.cpp.
 { return qt_screen->pixmapDepth(); }
playSoundFile()
void QWSDisplay::playSoundFile (const QString & f)
Definition at line 1738 of file qapplication_qws.cpp.
 {
     QWSPlaySoundCommand cmd;
     cmd.setFileName(f);
     d->sendCommand(cmd);
 }
registerChannel()
void QWSDisplay::registerChannel (const QString & channel)
Definition at line 1747 of file qapplication_qws.cpp.
Referenced by QCopChannel::init(), and QCopChannel::reregisterAll().
 {
     QWSQCopRegisterChannelCommand reg;
     reg.setChannel(channel);
     qt_fbdpy->d->sendCommand(reg);
 }
removeProperty()
void QWSDisplay::removeProperty (int winId, int property)
Definition at line 1396 of file qapplication_qws.cpp.
 {
     QWSRemovePropertyCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.property = property;
     d->sendCommand(cmd);
 }
repaintRegion()
void QWSDisplay::repaintRegion (int winId, int windowFlags, bool opaque, QRegion r)
Definition at line 1524 of file qapplication_qws.cpp.
Referenced by QWSWindowSurface::flush(), QWSYellowSurface::flush(), and QWSDirectPainterSurface::flush().
 {
     if (d->directServerConnection()) {
         qwsServer->d_func()->repaint_region(winId, windowFlags, opaque, r);
     } else {
         QVector<QRect> ra = r.rects();
         /*
           for (int i = 0; i < ra.size(); i++) {
           QRect r(ra[i]);
           qDebug("rect: %d %d %d %d", r.x(), r.y(), r.right(), r.bottom());
           }
         */
         QWSRepaintRegionCommand cmd;
     /* XXX QWSRegionCommand is padded out in a compiler dependent way.
        Zeroed out to avoid valgrind reporting uninitialized memory usage.
        */
 #ifdef QT_DEBUG
         memset(cmd.simpleDataPtr, 0, sizeof(cmd.simpleData)); //shut up Valgrind
 #endif
         cmd.simpleData.windowid = winId;
         cmd.simpleData.windowFlags = windowFlags;
         cmd.simpleData.opaque = opaque;
         cmd.simpleData.nrectangles = ra.count();
         cmd.setData(reinterpret_cast<const char *>(ra.constData()),
                     ra.count() * sizeof(QRect), false);
         d->sendSynchronousCommand(cmd);
     }
 }
requestFocus()
void QWSDisplay::requestFocus (int winId, bool get)
Definition at line 1473 of file qapplication_qws.cpp.
Referenced by isServerProcess().
 {
     QWSRequestFocusCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.flag = get;
     if (d->directServerConnection())
         qwsServer->d_func()->request_focus(&cmd);
     else
         d->sendCommand(cmd);
 }
requestRegion()
void QWSDisplay::requestRegion (int winId, const QString & surfacekey, const QByteArray & surfaceData, const QRegion & region)
Definition at line 1510 of file qapplication_qws.cpp.
Referenced by QWSYellowSurface::flush(), QWidget::setAttribute(), QWSWindowSurface::setGeometry(), and QWSDirectPainterSurface::setRegion().
 {
     if (d->directServerConnection()) {
         qwsServer->d_func()->request_region(winId, surfaceKey,
                                             surfaceData, region);
     } else {
         QWSRegionCommand cmd;
         cmd.setData(winId, surfaceKey, surfaceData, region);
         d->sendSynchronousCommand(cmd);
     }
 }
resetIM()
void QWSDisplay::resetIM ()
Definition at line 1615 of file qapplication_qws.cpp.
Referenced by QWSInputContext::reset().
 {
     sendIMUpdate(QWSInputMethod::Reset, -1, -1);
 }
selectCursor()
void QWSDisplay::selectCursor (QWidget * w, unsigned int id)
Definition at line 1795 of file qapplication_qws.cpp.
Referenced by effectiveState(), parseGeometry(), and QApplication::qwsProcessEvent().
 {
     if (cursId != qt_last_cursor)
     {
         QWidget *top = w->window();
         qt_last_cursor = cursId;
         QWSSelectCursorCommand cmd;
         cmd.simpleData.windowid = top->internalWinId();
         cmd.simpleData.id = cursId;
         d->sendCommand(cmd);
         d->flush();
     }
 }
sendFontCommand()
void QWSDisplay::sendFontCommand (int type, const QByteArray & fontName)
Definition at line 1779 of file qapplication_qws.cpp.
Referenced by QFontEngineQPF::QFontEngineQPF(), and QFontEngineQPF::~QFontEngineQPF().
 {
     QWSFontCommand cmd;
     cmd.simpleData.type = type;
     cmd.setFontName(fontName);
     d->sendCommand(cmd);
 }
sendIMMouseEvent()
void QWSDisplay::sendIMMouseEvent (int index, bool isPress)
Definition at line 1620 of file qapplication_qws.cpp.
Referenced by QWSInputContext::mouseHandler().
 {
     QWSIMMouseCommand cmd;
     cmd.simpleData.index = index;
     cmd.simpleData.state = isPress ? QWSServer::MousePress : QWSServer::MouseRelease;
     if (d->directServerConnection()) {
         qwsServer->d_func()->send_im_mouse(&cmd);
     } else {
         d->sendCommand(cmd);
     }
 }
sendIMResponse()
void QWSDisplay::sendIMResponse (int winId, int property, const QVariant & result)
Definition at line 1600 of file qapplication_qws.cpp.
Referenced by QWSInputContext::translateIMQueryEvent().
 {
     QWSIMResponseCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.property = property;
     cmd.setResult(result);
     if (d->directServerConnection()) {
         qwsServer->d_func()->im_response(&cmd);
     } else {
         d->sendCommand(cmd);
     }
 }
sendIMUpdate()
void QWSDisplay::sendIMUpdate (int type, int winId, int widgetid)
Definition at line 1585 of file qapplication_qws.cpp.
Referenced by QWSInputContext::setFocusWidget(), and QWSInputContext::update().
 {
     QWSIMUpdateCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.widgetid = widgetid;
     cmd.simpleData.type = type;
       if (d->directServerConnection()) {
         qwsServer->d_func()->im_update(&cmd);
     } else {
         d->sendCommand(cmd);
     }
 }
sendMessage()
void QWSDisplay::sendMessage (const QString & channel, const QString & msg, const QByteArray & data)
Definition at line 1754 of file qapplication_qws.cpp.
Referenced by QCopChannel::send().
 {
     QWSQCopSendCommand com;
     com.setMessage(channel, msg, data);
     qt_fbdpy->d->sendCommand(com);
 }
setAltitude()
void QWSDisplay::setAltitude (int winId, int altitude, bool fixed = false)
Definition at line 1443 of file qapplication_qws.cpp.
Referenced by effectiveState(), QWSYellowSurface::flush(), isServerProcess(), QDirectPainter::lower(), QWSYellowSurface::QWSYellowSurface(), QDirectPainter::raise(), and QWSWindowSurface::winId().
 {
     QWSChangeAltitudeCommand cmd;
 #ifdef QT_DEBUG
     memset(cmd.simpleDataPtr, 0, sizeof(cmd.simpleData)); //shut up Valgrind
 #endif
     cmd.simpleData.windowid = winId;
     cmd.simpleData.altitude = QWSChangeAltitudeCommand::Altitude(alt);
     cmd.simpleData.fixed = fixed;
     if (d->directServerConnection()) {
         qwsServer->d_func()->set_altitude(&cmd);
     } else {
         d->sendSynchronousCommand(cmd);
     }
 }
setCursorPosition()
void QWSDisplay::setCursorPosition (int x, int y)
Definition at line 1809 of file qapplication_qws.cpp.
 {
     QWSPositionCursorCommand cmd;
     cmd.simpleData.newX = x;
     cmd.simpleData.newY = y;
     d->sendCommand(cmd);
     d->flush();
 }
setIdentity()
void QWSDisplay::setIdentity (const QString & appName)
Definition at line 1484 of file qapplication_qws.cpp.
 {
     QWSIdentifyCommand cmd;
 #ifdef QT_NO_QWS_MULTIPROCESS
     const int id = -1;
 #else
     const int id = QWSDisplay::Data::clientLock ? QWSDisplay::Data::clientLock->id() : -1;
 #endif
     cmd.setId(appName, id);
     if (d->directServerConnection())
         qwsServer->d_func()->set_identity(&cmd);
     else
         d->sendCommand(cmd);
 }
setOpacity()
void QWSDisplay::setOpacity (int winId, int opacity)
Definition at line 1459 of file qapplication_qws.cpp.
Referenced by effectiveState().
 {
     QWSSetOpacityCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.opacity = opacity;
     if (d->directServerConnection()) {
         qwsServer->d_func()->set_opacity(&cmd);
     } else {
         d->sendCommand(cmd);
     }
 }
setProperty() [1/2]
void QWSDisplay::setProperty (int winId, int property, int mode, const QByteArray & data)
Definition at line 1375 of file qapplication_qws.cpp.
 {
     QWSSetPropertyCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.property = property;
     cmd.simpleData.mode = mode;
     cmd.setData(data.constData(), data.size());
     d->sendCommand(cmd);
 }
setProperty() [2/2]
void QWSDisplay::setProperty (int winId, int property, int mode, const char * data)
Definition at line 1385 of file qapplication_qws.cpp.
 {
     QWSSetPropertyCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.property = property;
     cmd.simpleData.mode = mode;
     cmd.setData(data, strlen(data));
     d->sendCommand(cmd);
 }
setRawMouseEventFilter()
void QWSDisplay::setRawMouseEventFilter (void(*)(QWSMouseEvent *) filter) static
Definition at line 1875 of file qapplication_qws.cpp.
 {
     if (qt_fbdpy)
         qt_fbdpy->d->setMouseFilter(filter);
 }
setSelectionOwner()
void QWSDisplay::setSelectionOwner (int winId, const QTime & time)
Definition at line 1654 of file qapplication_qws.cpp.
 {
     QWSSetSelectionOwnerCommand cmd;
     cmd.simpleData.windowid = winId;
     cmd.simpleData.hour = time.hour();
     cmd.simpleData.minute = time.minute();
     cmd.simpleData.sec = time.second();
     cmd.simpleData.ms = time.msec();
     d->sendCommand(cmd);
 }
setTransformation()
static void QWSDisplay::setTransformation (int transformation, int screenNo = -1) static
setWindowCaption()
void QWSDisplay::setWindowCaption (QWidget * w, const QString & c)
Definition at line 1787 of file qapplication_qws.cpp.
Referenced by isServerProcess().
 {
     if (w->isWindow()) {
         nameRegion(w->internalWinId(), w->objectName(), c);
         static_cast<QETWidget *>(w)->repaintDecoration(qApp->desktop()->rect(), true);
     }
 }
sharedRam()
uchar * QWSDisplay::sharedRam () const
Definition at line 1362 of file qapplication_qws.cpp.
 { return d->sharedRam; }
sharedRamSize()
int QWSDisplay::sharedRamSize () const
Definition at line 1363 of file qapplication_qws.cpp.
 { return d->sharedRamSize; }
supportsDepth()
bool QWSDisplay::supportsDepth (int depth) const
Definition at line 1361 of file qapplication_qws.cpp.
 { return qt_screen->supportsDepth(depth); }
takeId()
int QWSDisplay::takeId ()
Definition at line 1634 of file qapplication_qws.cpp.
Referenced by isServerProcess(), and QWSWindowSurface::winId().
 {
     return d->takeId();
 }
ungrab()
void QWSDisplay::ungrab () static
Definition at line 1322 of file qapplication_qws.cpp.
Referenced by QTransformedScreen::blit(), QScreen::blit(), QLinuxFbScreen::cache(), QLinuxFbScreen::clearCache(), QLinuxFbScreen::deleteEntry(), QWSServer::endDisplayReconfigure(), QWSWindowSurface::flush(), QScreen::solidFill(), QDirectPainter::unlock(), QWSDirectPainterSurface::unlock(), QWSServerPrivate::update_regions(), QWSDisplay::Data::waitForRegionEvents(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     lock->unlock();
 }
waitForQCopResponse()
QWSQCopMessageEvent * QWSDisplay::waitForQCopResponse ()
Definition at line 1770 of file qapplication_qws.cpp.
Referenced by QCopChannel::isRegistered().
 {
     qt_fbdpy->d->waitForQCopResponse();
     QWSQCopMessageEvent *e = static_cast<QWSQCopMessageEvent*>(qt_fbdpy->d->dequeue());
     Q_ASSERT(e->type == QWSEvent::QCopMessage);
     return e;
 }
width()
int QWSDisplay::width () const
Definition at line 1357 of file qapplication_qws.cpp.
 { return qt_screen->width(); }
windowAt()
int QWSDisplay::windowAt (const QPoint & p)
Definition at line 1863 of file qapplication_qws.cpp.
Referenced by parseGeometry().
 {
     //### currently only implemented for the server process
     int ret = 0;
     if(d->directServerConnection()) {
         QWSWindow *win = qwsServer->windowAt(p);
         if (win)
             return win->winId();
     }
     return ret;
 }
windowList()
QList< QWSWindowInfo > QWSDisplay::windowList ()
Definition at line 1844 of file qapplication_qws.cpp.
 {
     QList<QWSWindowInfo> ret;
     if(d->directServerConnection()) {
         QList<QWSInternalWindowInfo*> * qin=QWSServer::windowList();
         for (int i = 0; i < qin->count(); ++i) {
             QWSInternalWindowInfo * qwi = qin->at(i);
             QWSWindowInfo tmp;
             tmp.winid = qwi->winid;
             tmp.clientid = qwi->clientid;
             tmp.name = QString(qwi->name);
             ret.append(tmp);
         }
         qDeleteAll(*qin);
         delete qin;
     }
     return ret;
 }
Friends and Related Functions
Data
friend class Data friend
Definition at line 169 of file qwsdisplay_qws.h.
QApplication
friend class QApplication friend
Definition at line 165 of file qwsdisplay_qws.h.
QCopChannel
friend class QCopChannel friend
Definition at line 166 of file qwsdisplay_qws.h.
qt_app_reinit
void qt_app_reinit (const QString & newAppName) friend
Definition at line 690 of file qapplication_qws.cpp.
 {
     qt_fbdpy->d->reinit( newAppName );
 }
qt_fork_qapplication
int qt_fork_qapplication () friend
QWSDirectPainterSurface
friend class QWSDirectPainterSurface friend
Definition at line 175 of file qwsdisplay_qws.h.
QWSEmbedWidget
friend class QWSEmbedWidget friend
Definition at line 167 of file qwsdisplay_qws.h.
QWSEmbedWidgetPrivate
friend class QWSEmbedWidgetPrivate friend
Definition at line 168 of file qwsdisplay_qws.h.
QWSMemorySurface
friend class QWSMemorySurface friend
Definition at line 173 of file qwsdisplay_qws.h.
QWSOnScreenSurface
friend class QWSOnScreenSurface friend
Definition at line 174 of file qwsdisplay_qws.h.
Properties
d
Data* QWSDisplay::d private
Definition at line 171 of file qwsdisplay_qws.h.
Referenced by QWSDirectPainterSurface::beginPaint(), flushCommands(), QWSDirectPainterSurface::hasPendingRegionEvents(), qt_app_reinit(), registerChannel(), QWSEmbedWidgetPrivate::resize(), sendMessage(), setRawMouseEventFilter(), QWSDirectPainterSurface::setRegion(), QScreen::setTransformation(), QWSEmbedWidgetPrivate::updateWindow(), waitForQCopResponse(), and QWSEmbedWidget::~QWSEmbedWidget().
getPropertyData
char* QWSDisplay::getPropertyData private
Definition at line 177 of file qwsdisplay_qws.h.
Referenced by QWSDisplay::Data::fillQueue().
getPropertyLen
int QWSDisplay::getPropertyLen private
Definition at line 176 of file qwsdisplay_qws.h.
Referenced by QWSDisplay::Data::fillQueue(), and QWSDisplay::Data::waitForPropertyReply().
lock
QLock * QWSDisplay::lock = 0 static private
Definition at line 178 of file qwsdisplay_qws.h.
The documentation for this class was generated from the following files:
/src/gui/embedded/qwsdisplay_qws.h
/src/gui/kernel/qapplication_qws.cpp