Qt 4.8: QWindowSystemInterface Class Reference
QWindowSystemInterface Class Reference
#include <qwindowsysteminterface_qpa.h>
Classes
struct TouchPoint
Static Public Functions
static void handleCloseEvent (QWidget *w)
static void handleEnterEvent (QWidget *w)
static void handleExtendedKeyEvent (QWidget *w, QEvent::Type type, int key, Qt::KeyboardModifiers modifiers, quint32 nativeScanCode, quint32 nativeVirtualKey, quint32 nativeModifiers, const QString &text=QString(), bool autorep=false, ushort count=1)
static void handleExtendedKeyEvent (QWidget *w, ulong timestamp, QEvent::Type type, int key, Qt::KeyboardModifiers modifiers, quint32 nativeScanCode, quint32 nativeVirtualKey, quint32 nativeModifiers, const QString &text=QString(), bool autorep=false, ushort count=1)
static void handleGeometryChange (QWidget *w, const QRect &newRect)
static void handleKeyEvent (QWidget *w, QEvent::Type t, int k, Qt::KeyboardModifiers mods, const QString &text=QString(), bool autorep=false, ushort count=1)
static void handleKeyEvent (QWidget *w, ulong timestamp, QEvent::Type t, int k, Qt::KeyboardModifiers mods, const QString &text=QString(), bool autorep=false, ushort count=1)
static void handleLeaveEvent (QWidget *w)
static void handleLocaleChange ()
static void handleMouseEvent (QWidget *w, const QPoint &local, const QPoint &global, Qt::MouseButtons b)
tlw == 0 means that ev is in global coords only
static void handleMouseEvent (QWidget *w, ulong timestamp, const QPoint &local, const QPoint &global, Qt::MouseButtons b)
static void handlePlatformPanelEvent (QWidget *w)
static void handleScreenAvailableGeometryChange (int screenIndex)
static void handleScreenCountChange (int count)
static void handleScreenGeometryChange (int screenIndex)
static void handleTouchEvent (QWidget *w, QEvent::Type type, QTouchEvent::DeviceType devType, const QList< struct TouchPoint > &points)
static void handleTouchEvent (QWidget *w, ulong timestamp, QEvent::Type type, QTouchEvent::DeviceType devType, const QList< struct TouchPoint > &points)
static void handleWheelEvent (QWidget *w, const QPoint &local, const QPoint &global, int d, Qt::Orientation o)
static void handleWheelEvent (QWidget *w, ulong timestamp, const QPoint &local, const QPoint &global, int d, Qt::Orientation o)
static void handleWindowActivated (QWidget *w)
static void handleWindowStateChanged (QWidget *w, Qt::WindowState newState)
Detailed Description
Definition at line 58 of file qwindowsysteminterface_qpa.h.
Functions
handleCloseEvent()
void QWindowSystemInterface::handleCloseEvent (QWidget * w) static
Definition at line 111 of file qwindowsysteminterface_qpa.cpp.
Referenced by QXcbWindow::handleClientMessageEvent(), QBBScreenEventHandler::handleCloseEvent(), and QXlibWindow::handleCloseEvent().
 {
     if (tlw) {
         QWindowSystemInterfacePrivate::CloseEvent *e =
                 new QWindowSystemInterfacePrivate::CloseEvent(tlw);
         QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
     }
 }
handleEnterEvent()
void QWindowSystemInterface::handleEnterEvent (QWidget * w) static
Definition at line 63 of file qwindowsysteminterface_qpa.cpp.
Referenced by QXlibWindow::handleEnterEvent(), QDirectFbInput::handleEnterLeaveEvents(), QXcbWindow::handleEnterNotifyEvent(), QBBScreenEventHandler::handlePointerEvent(), QBBScreenEventHandler::handleTouchEvent(), QBBScreenEventHandler::injectPointerMoveEvent(), and QWaylandInputDevice::inputHandlePointerFocus().
 {
     if (tlw) {
         QWidgetData *data = qt_qwidget_data(tlw);
         if (data->in_destructor)
             return;
         QWindowSystemInterfacePrivate::EnterEvent *e = new QWindowSystemInterfacePrivate::EnterEvent(tlw);
         QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
     }
 }
handleExtendedKeyEvent() [1/2]
void QWindowSystemInterface::handleExtendedKeyEvent (QWidget * w, QEvent::Type type, int key, Qt::KeyboardModifiers modifiers, quint32 nativeScanCode, quint32 nativeVirtualKey, quint32 nativeModifiers, const QString & text = QString(), bool autorep = false, ushort count = 1) static
Definition at line 161 of file qwindowsysteminterface_qpa.cpp.
Referenced by QXlibKeyboard::handleKeyEvent(), QXcbKeyboard::handleKeyEvent(), and QBBScreenEventHandler::injectKeyboardEvent().
 {
     unsigned long time = QWindowSystemInterfacePrivate::eventTime.elapsed();
     handleExtendedKeyEvent(w, time, type, key, modifiers, nativeScanCode, nativeVirtualKey, nativeModifiers,
                            text, autorep, count);
 }
handleExtendedKeyEvent() [2/2]
void QWindowSystemInterface::handleExtendedKeyEvent (QWidget * w, ulong timestamp, QEvent::Type type, int key, Qt::KeyboardModifiers modifiers, quint32 nativeScanCode, quint32 nativeVirtualKey, quint32 nativeModifiers, const QString & text = QString(), bool autorep = false, ushort count = 1) static
Definition at line 172 of file qwindowsysteminterface_qpa.cpp.
 {
     if (tlw) {
         QWidgetData *data = qt_qwidget_data(tlw);
         if (data->in_destructor)
             tlw = 0;
     }
     QWindowSystemInterfacePrivate::KeyEvent * e =
             new QWindowSystemInterfacePrivate::KeyEvent(tlw, timestamp, type, key, modifiers,
                 nativeScanCode, nativeVirtualKey, nativeModifiers, text, autorep, count);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleGeometryChange()
void QWindowSystemInterface::handleGeometryChange (QWidget * w, const QRect & newRect) static
Definition at line 99 of file qwindowsysteminterface_qpa.cpp.
Referenced by QWaylandWindow::configure(), QXcbWindow::handleConfigureNotifyEvent(), QXlibWindow::resizeEvent(), QEglFSWindow::setGeometry(), QVFbWindow::setGeometry(), and QCocoaWindow::windowDidResize().
 {
     if (tlw) {
         QWidgetData *data = qt_qwidget_data(tlw);
         if (data->in_destructor)
             return;
     }
     QWindowSystemInterfacePrivate::GeometryChangeEvent *e = new QWindowSystemInterfacePrivate::GeometryChangeEvent(tlw,newRect);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleKeyEvent() [1/2]
void QWindowSystemInterface::handleKeyEvent (QWidget * w, QEvent::Type t, int k, Qt::KeyboardModifiers mods, const QString & text = QString(), bool autorep = false, ushort count = 1) static
Definition at line 143 of file qwindowsysteminterface_qpa.cpp.
Referenced by buttonChange(), QDirectFbInput::handleKeyEvents(), QWaylandInputDevice::inputHandleKey(), QWSKeyboardHandler::processKeyEvent(), QOpenKODEWindow::processKeyEvents(), QVFbScreenKeyboardHandler::readKeyboardData(), and QBBButtonEventNotifier::updateButtonStates().
{
     unsigned long time = QWindowSystemInterfacePrivate::eventTime.elapsed();
     handleKeyEvent(w, time, t, k, mods, text, autorep, count);
 }
handleKeyEvent() [2/2]
void QWindowSystemInterface::handleKeyEvent (QWidget * w, ulong timestamp, QEvent::Type t, int k, Qt::KeyboardModifiers mods, const QString & text = QString(), bool autorep = false, ushort count = 1) static
Definition at line 148 of file qwindowsysteminterface_qpa.cpp.
 {
     if (tlw) {
         QWidgetData *data = qt_qwidget_data(tlw);
         if (data->in_destructor)
             tlw = 0;
     }
     QWindowSystemInterfacePrivate::KeyEvent * e =
             new QWindowSystemInterfacePrivate::KeyEvent(tlw, timestamp, t, k, mods, text, autorep, count);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleLeaveEvent()
void QWindowSystemInterface::handleLeaveEvent (QWidget * w) static
Definition at line 75 of file qwindowsysteminterface_qpa.cpp.
Referenced by QDirectFbInput::handleEnterLeaveEvents(), QXlibWindow::handleLeaveEvent(), QXcbWindow::handleLeaveNotifyEvent(), QBBScreenEventHandler::handlePointerEvent(), QBBScreenEventHandler::handleTouchEvent(), QBBScreenEventHandler::injectPointerMoveEvent(), and QWaylandInputDevice::inputHandlePointerFocus().
 {
     if (tlw) {
         QWidgetData *data = qt_qwidget_data(tlw);
         if (data->in_destructor)
             return;
     }
     QWindowSystemInterfacePrivate::LeaveEvent *e = new QWindowSystemInterfacePrivate::LeaveEvent(tlw);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleLocaleChange()
void QWindowSystemInterface::handleLocaleChange () static
Definition at line 299 of file qwindowsysteminterface_qpa.cpp.
 {
     QWindowSystemInterfacePrivate::LocaleChangeEvent *e =
             new QWindowSystemInterfacePrivate::LocaleChangeEvent();
     QLocalePrivate::updateSystemPrivate();
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleMouseEvent() [1/2]
void QWindowSystemInterface::handleMouseEvent (QWidget * w, const QPoint & local, const QPoint & global, Qt::MouseButtons b) static
tlw == 0 means that ev is in global coords only
Definition at line 126 of file qwindowsysteminterface_qpa.cpp.
Referenced by buttonChange(), QXcbWindow::handleMouseEvent(), QXlibWindow::handleMouseEvent(), QDirectFbInput::handleMouseEvents(), QBBScreenEventHandler::handlePointerEvent(), QBBScreenEventHandler::handleTouchEvent(), QBBScreenEventHandler::injectPointerMoveEvent(), QWaylandInputDevice::inputHandleButton(), QWaylandInputDevice::inputHandleMotion(), QOpenKODEWindow::processMouseEvents(), QTsLibMouseHandler::readMouseData(), QVFbScreenMouseHandler::readMouseData(), and QLinuxInputMouseHandler::sendMouseEvent().
{
     unsigned long time = QWindowSystemInterfacePrivate::eventTime.elapsed();
     handleMouseEvent(w, time, local, global, b);
 }
handleMouseEvent() [2/2]
void QWindowSystemInterface::handleMouseEvent (QWidget * w, ulong timestamp, const QPoint & local, const QPoint & global, Qt::MouseButtons b) static
Definition at line 131 of file qwindowsysteminterface_qpa.cpp.
 {
     if (tlw) {
         QWidgetData *data = qt_qwidget_data(tlw);
         if (data->in_destructor)
             tlw = 0;
     }
     QWindowSystemInterfacePrivate::MouseEvent * e =
             new QWindowSystemInterfacePrivate::MouseEvent(tlw, timestamp, local, global, b);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handlePlatformPanelEvent()
void QWindowSystemInterface::handlePlatformPanelEvent (QWidget * w) static
Definition at line 308 of file qwindowsysteminterface_qpa.cpp.
Referenced by QBBNavigatorEventHandler::handleSwipeDown().
 {
     QWindowSystemInterfacePrivate::PlatformPanelEvent *e =
             new QWindowSystemInterfacePrivate::PlatformPanelEvent(w);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleScreenAvailableGeometryChange()
void QWindowSystemInterface::handleScreenAvailableGeometryChange (int screenIndex) static
Definition at line 285 of file qwindowsysteminterface_qpa.cpp.
Referenced by QBBScreen::keyboardHeightChanged().
 {
     QWindowSystemInterfacePrivate::ScreenAvailableGeometryEvent *e =
             new QWindowSystemInterfacePrivate::ScreenAvailableGeometryEvent(screenIndex);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleScreenCountChange()
void QWindowSystemInterface::handleScreenCountChange (int count) static
Definition at line 292 of file qwindowsysteminterface_qpa.cpp.
 {
     QWindowSystemInterfacePrivate::ScreenCountEvent *e =
             new QWindowSystemInterfacePrivate::ScreenCountEvent(count);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleScreenGeometryChange()
void QWindowSystemInterface::handleScreenGeometryChange (int screenIndex) static
Definition at line 278 of file qwindowsysteminterface_qpa.cpp.
Referenced by QBBScreen::setRotation().
 {
     QWindowSystemInterfacePrivate::ScreenGeometryEvent *e =
             new QWindowSystemInterfacePrivate::ScreenGeometryEvent(screenIndex);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleTouchEvent() [1/2]
void QWindowSystemInterface::handleTouchEvent (QWidget * w, QEvent::Type type, QTouchEvent::DeviceType devType, const QList< struct TouchPoint > & points) static
Definition at line 240 of file qwindowsysteminterface_qpa.cpp.
Referenced by QBBScreenEventHandler::handleTouchEvent(), and QLinuxInputMouseHandler::readMouseData().
{
     unsigned long time = QWindowSystemInterfacePrivate::eventTime.elapsed();
     handleTouchEvent(w, time, type, devType, points);
 }
handleTouchEvent() [2/2]
void QWindowSystemInterface::handleTouchEvent (QWidget * w, ulong timestamp, QEvent::Type type, QTouchEvent::DeviceType devType, const QList< struct TouchPoint > & points) static
Definition at line 245 of file qwindowsysteminterface_qpa.cpp.
 {
     if (!points.size()) // Touch events must have at least one point
         return;
     QList<QTouchEvent::TouchPoint> touchPoints;
     Qt::TouchPointStates states;
     QTouchEvent::TouchPoint p;
     QList<struct TouchPoint>::const_iterator point = points.constBegin();
     QList<struct TouchPoint>::const_iterator end = points.constEnd();
     while (point != end) {
         p.setId(point->id);
         p.setPressure(point->pressure);
         states |= point->state;
         Qt::TouchPointStates state = point->state;
         if (point->isPrimary) {
             state |= Qt::TouchPointPrimary;
         }
         p.setState(state);
         p.setRect(point->area);
         p.setScreenPos(point->area.center());
         p.setNormalizedPos(point->normalPosition);
         touchPoints.append(p);
         ++point;
     }
     QWindowSystemInterfacePrivate::TouchEvent *e =
             new QWindowSystemInterfacePrivate::TouchEvent(tlw, timestamp, type, devType, touchPoints);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleWheelEvent() [1/2]
void QWindowSystemInterface::handleWheelEvent (QWidget * w, const QPoint & local, const QPoint & global, int d, Qt::Orientation o) static
Definition at line 191 of file qwindowsysteminterface_qpa.cpp.
Referenced by buttonChange(), QXcbWindow::handleButtonPressEvent(), QXlibWindow::handleMouseEvent(), QBBScreenEventHandler::handlePointerEvent(), QDirectFbInput::handleWheelEvent(), and QLinuxInputMouseHandler::readMouseData().
{
     unsigned long time = QWindowSystemInterfacePrivate::eventTime.elapsed();
     handleWheelEvent(w, time, local, global, d, o);
 }
handleWheelEvent() [2/2]
void QWindowSystemInterface::handleWheelEvent (QWidget * w, ulong timestamp, const QPoint & local, const QPoint & global, int d, Qt::Orientation o) static
Definition at line 196 of file qwindowsysteminterface_qpa.cpp.
 {
     if (tlw) {
         QWidgetData *data = qt_qwidget_data(tlw);
         if (data->in_destructor)
             tlw = 0;
     }
     QWindowSystemInterfacePrivate::WheelEvent *e =
             new QWindowSystemInterfacePrivate::WheelEvent(tlw, timestamp, local, global, d, o);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleWindowActivated()
void QWindowSystemInterface::handleWindowActivated (QWidget * w) static
Definition at line 86 of file qwindowsysteminterface_qpa.cpp.
Referenced by QBBScreen::activateWindowGroup(), QBBScreen::deactivateWindowGroup(), QBBWindow::gainedFocus(), QXcbWindow::handleFocusInEvent(), QXlibWindow::handleFocusInEvent(), QXcbWindow::handleFocusOutEvent(), QXlibWindow::handleFocusOutEvent(), QWaylandInputDevice::inputHandleKeyboardFocus(), and QPlatformWindow::requestActivateWindow().
 {
     QWindowSystemInterfacePrivate::ActivatedWindowEvent *e = new QWindowSystemInterfacePrivate::ActivatedWindowEvent(tlw);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
handleWindowStateChanged()
void QWindowSystemInterface::handleWindowStateChanged (QWidget * w, Qt::WindowState newState) static
Definition at line 92 of file qwindowsysteminterface_qpa.cpp.
Referenced by QBBScreen::windowGroupStateChanged().
 {
     QWindowSystemInterfacePrivate::WindowStateChangedEvent *e =
         new QWindowSystemInterfacePrivate::WindowStateChangedEvent(tlw, newState);
     QWindowSystemInterfacePrivate::queueWindowSystemEvent(e);
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qwindowsysteminterface_qpa.h
/src/gui/kernel/qwindowsysteminterface_qpa.cpp