Qt 4.8: QSwipeGesture Class Reference
QSwipeGesture Class Reference
The QSwipeGesture class describes a swipe gesture made by the user.
#include <qgesture.h>
Public Types
enum SwipeDirection {
NoDirection, Left, Right, Up,
Down
}
This enum describes the possible directions for the gesture's motion along the horizontal and vertical axes.
Public Types inherited from QGesture
enum GestureCancelPolicy { CancelNone = 0, CancelAllInContext }
This enum describes how accepting a gesture can cancel other gestures automatically.
Public Functions
SwipeDirection horizontalDirection () const
QSwipeGesture (QObject *parent=0)
void setSwipeAngle (qreal value)
qreal swipeAngle () const
SwipeDirection verticalDirection () const
Public Functions inherited from QGesture
GestureCancelPolicy gestureCancelPolicy () const
Qt::GestureType gestureType () const
bool hasHotSpot () const
QPointF hotSpot () const
QGesture (QObject *parent=0)
Constructs a new gesture object with the given parent.
void setGestureCancelPolicy (GestureCancelPolicy policy)
void setHotSpot (const QPointF &value)
Qt::GestureState state () const
void unsetHotSpot ()
~QGesture ()
Destroys the gesture object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
SwipeDirection horizontalDirection
the horizontal direction of the gesture
qreal swipeAngle
the angle of the motion associated with the gesture
SwipeDirection verticalDirection
the vertical direction of the gesture
Friends
class QSwipeGestureRecognizer
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QGesture
QGesture (QGesturePrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSwipeGesture class describes a swipe gesture made by the user.
Since
4.6
For an overview of gesture handling in Qt and information on using gestures in your applications, see the Gestures Programming document.
See also
QPanGesture, QPinchGesture
Definition at line 207 of file qgesture.h.
Enumerations
SwipeDirection
enum QSwipeGesture::SwipeDirection
This enum describes the possible directions for the gesture's motion along the horizontal and vertical axes.
NoDirection The gesture had no motion associated with it on a particular axis.
Left The gesture involved a horizontal motion to the left.
Right The gesture involved a horizontal motion to the right.
Up The gesture involved an upward vertical motion.
Down The gesture involved a downward vertical motion.
Enumerator
NoDirection
Left
Right
Up
Down
Definition at line 219 of file qgesture.h.
 { NoDirection, Left, Right, Up, Down };
Constructors and Destructors
QSwipeGesture()
QSwipeGesture::QSwipeGesture (QObject * parent = 0)
Warning
This function is not part of the public interface.
Definition at line 761 of file qgesture.cpp.
     : QGesture(*new QSwipeGesturePrivate, parent)
 {
     d_func()->gestureType = Qt::SwipeGesture;
 }
Functions
horizontalDirection()
SwipeDirection QSwipeGesture::horizontalDirection () const
Referenced by QSwipeGesture().
setSwipeAngle()
void QSwipeGesture::setSwipeAngle (qreal value)
Definition at line 794 of file qgesture.cpp.
Referenced by QMacSwipeGestureRecognizer::recognize(), and QMacSwipeGestureRecognizer::reset().
 {
     d_func()->swipeAngle = value;
 }
swipeAngle()
qreal QSwipeGesture::swipeAngle () const
Referenced by QSwipeGesture().
verticalDirection()
SwipeDirection QSwipeGesture::verticalDirection () const
Referenced by QSwipeGesture().
Friends and Related Functions
QSwipeGestureRecognizer
friend class QSwipeGestureRecognizer friend
Definition at line 228 of file qgesture.h.
Properties
horizontalDirection
QSwipeGesture::SwipeDirection QSwipeGesture::horizontalDirection private
the horizontal direction of the gesture
If the gesture has a horizontal component, the horizontal direction is either Left or Right; otherwise, it is NoDirection.
See also
verticalDirection, swipeAngle
Definition at line 213 of file qgesture.h.
swipeAngle
qreal QSwipeGesture::swipeAngle private
the angle of the motion associated with the gesture
If the gesture has either a horizontal or vertical component, the swipe angle describes the angle between the direction of motion and the x-axis as defined using the standard widget Coordinate System{coordinate system}.
See also
horizontalDirection, verticalDirection
Definition at line 215 of file qgesture.h.
verticalDirection
QSwipeGesture::SwipeDirection QSwipeGesture::verticalDirection private
the vertical direction of the gesture
If the gesture has a vertical component, the vertical direction is either Up or Down; otherwise, it is NoDirection.
See also
horizontalDirection, swipeAngle
Definition at line 214 of file qgesture.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qgesture.h
/src/gui/kernel/qgesture.cpp