Qt 4.8: QScriptEdit Class Reference
QScriptEdit Class Reference
#include <qscriptedit_p.h>
Classes
struct BreakpointData
Signals
void breakpointEnableRequest (int lineNumber, bool enable)
void breakpointToggleRequest (int lineNumber, bool on)
Signals inherited from QPlainTextEdit
void blockCountChanged (int newBlockCount)
This signal is emitted whenever the block count changes.
void copyAvailable (bool b)
This signal is emitted when text is selected or de-selected in the text edit.
void cursorPositionChanged ()
This signal is emitted whenever the position of the cursor changed.
void modificationChanged (bool)
This signal is emitted whenever the content of the document changes in a way that affects the modification state.
void redoAvailable (bool b)
This signal is emitted whenever redo operations become available (available is true) or unavailable (available is false).
void selectionChanged ()
This signal is emitted whenever the selection changes.
void textChanged ()
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
void undoAvailable (bool b)
This signal is emitted whenever undo operations become available (available is true) or unavailable (available is false).
void updateRequest (const QRect &rect, int dy)
This signal is emitted when the text document needs an update of the specified rect.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int baseLineNumber () const
int currentLineNumber () const
void deleteBreakpoint (int lineNumber)
int executionLineNumber () const
int extraAreaWidth () const
void gotoLine (int lineNumber)
bool isExecutableLine (int lineNumber) const
QScriptEdit (QWidget *parent=0)
void setBaseLineNumber (int base)
void setBreakpoint (int lineNumber)
void setBreakpointEnabled (int lineNumber, bool enable)
void setExecutableLineNumbers (const QSet< int > &lineNumbers)
void setExecutionLineNumber (int lineNumber, bool error)
~QScriptEdit ()
Public Functions inherited from QPlainTextEdit
QString anchorAt (const QPoint &pos) const
Returns the reference of the anchor at position pos, or an empty string if no anchor exists at that point.
bool backgroundVisible () const
int blockCount () const
bool canPaste () const
Returns whether text can be pasted from the clipboard into the textedit.
bool centerOnScroll () const
QMenu * createStandardContextMenu ()
This function creates the standard context menu which is shown when the user clicks on the line edit with the right mouse button.
QTextCharFormat currentCharFormat () const
Returns the char format that is used when inserting new text.
QTextCursor cursorForPosition (const QPoint &pos) const
returns a QTextCursor at position pos (in viewport coordinates).
QRect cursorRect (const QTextCursor &cursor) const
returns a rectangle (in viewport coordinates) that includes the cursor.
QRect cursorRect () const
returns a rectangle (in viewport coordinates) that includes the cursor of the text edit.
int cursorWidth () const
QTextDocument * document () const
Returns a pointer to the underlying document.
QString documentTitle () const
void ensureCursorVisible ()
Ensures that the cursor is visible by scrolling the text edit if necessary.
QList< QTextEdit::ExtraSelection > extraSelections () const
Returns previously set extra selections.
bool find (const QString &exp, QTextDocument::FindFlags options=0)
Finds the next occurrence of the string, exp, using the given options.
bool isReadOnly () const
bool isUndoRedoEnabled () const
LineWrapMode lineWrapMode () const
virtual QVariant loadResource (int type, const QUrl &name)
Loads the resource specified by the given type and name.
int maximumBlockCount () const
void mergeCurrentCharFormat (const QTextCharFormat &modifier)
Merges the properties specified in modifier into the current character format by calling QTextCursor::mergeCharFormat on the editor's cursor.
void moveCursor (QTextCursor::MoveOperation operation, QTextCursor::MoveMode mode=QTextCursor::MoveAnchor)
Moves the cursor by performing the given operation.
bool overwriteMode () const
void print (QPrinter *printer) const
Convenience function to print the text edit's document to the given printer.
QPlainTextEdit (QWidget *parent=0)
Constructs an empty QPlainTextEdit with parent parent.
QPlainTextEdit (const QString &text, QWidget *parent=0)
Constructs a QPlainTextEdit with parent parent.
void setBackgroundVisible (bool visible)
void setCenterOnScroll (bool enabled)
void setCurrentCharFormat (const QTextCharFormat &format)
Sets the char format that is be used when inserting new text to format by calling QTextCursor::setCharFormat() on the editor's cursor.
void setCursorWidth (int width)
void setDocument (QTextDocument *document)
Makes document the new document of the text editor.
void setDocumentTitle (const QString &title)
void setExtraSelections (const QList< QTextEdit::ExtraSelection > &selections)
This function allows temporarily marking certain regions in the document with a given color, specified as selections.
void setLineWrapMode (LineWrapMode mode)
void setMaximumBlockCount (int maximum)
void setOverwriteMode (bool overwrite)
void setReadOnly (bool ro)
void setTabChangesFocus (bool b)
void setTabStopWidth (int width)
void setTextCursor (const QTextCursor &cursor)
Sets the visible cursor.
void setTextInteractionFlags (Qt::TextInteractionFlags flags)
void setUndoRedoEnabled (bool enable)
void setWordWrapMode (QTextOption::WrapMode policy)
bool tabChangesFocus () const
int tabStopWidth () const
QTextCursor textCursor () const
Returns a copy of the QTextCursor that represents the currently visible cursor.
Qt::TextInteractionFlags textInteractionFlags () const
QString toPlainText () const
Returns the text of the text edit as plain text.
QTextOption::WrapMode wordWrapMode () const
the mode QPlainTextEdit will use when wrapping text by words
virtual ~QPlainTextEdit ()
Destructor.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
bool extraAreaEvent (QEvent *e)
void extraAreaMouseEvent (QMouseEvent *e)
void extraAreaPaintEvent (QPaintEvent *e)
void paintEvent (QPaintEvent *e)
Reimplemented Function
void resizeEvent (QResizeEvent *e)
Reimplemented Function
Protected Functions inherited from QPlainTextEdit
QRectF blockBoundingGeometry (const QTextBlock &block) const
Returns the bounding rectangle of the text block in content coordinates.
QRectF blockBoundingRect (const QTextBlock &block) const
Returns the bounding rectangle of the text block in the block's own coordinates.
virtual bool canInsertFromMimeData (const QMimeData *source) const
This function returns true if the contents of the MIME data object, specified by source, can be decoded and inserted into the document.
virtual void changeEvent (QEvent *e)
Reimplemented Function
QPointF contentOffset () const
Returns the content's origin in viewport coordinates.
virtual void contextMenuEvent (QContextMenuEvent *e)
Shows the standard context menu created with createStandardContextMenu().
virtual QMimeData * createMimeDataFromSelection () const
This function returns a new MIME data object to represent the contents of the text edit's current selection.
virtual void dragEnterEvent (QDragEnterEvent *e)
Reimplemented Function
virtual void dragLeaveEvent (QDragLeaveEvent *e)
Reimplemented Function
virtual void dragMoveEvent (QDragMoveEvent *e)
Reimplemented Function
virtual void dropEvent (QDropEvent *e)
Reimplemented Function
virtual bool event (QEvent *e)
QTextBlock firstVisibleBlock () const
Returns the first visible block.
virtual void focusInEvent (QFocusEvent *e)
Reimplemented Function
virtual bool focusNextPrevChild (bool next)
Reimplemented Function
virtual void focusOutEvent (QFocusEvent *e)
Reimplemented Function
QAbstractTextDocumentLayout::PaintContext getPaintContext () const
Returns the paint context for the viewport(), useful only when reimplementing paintEvent().
virtual void inputMethodEvent (QInputMethodEvent *)
Reimplemented Function
QVariant inputMethodQuery (Qt::InputMethodQuery property) const
This method is only relevant for input widgets.
virtual void insertFromMimeData (const QMimeData *source)
This function inserts the contents of the MIME data object, specified by source, into the text edit at the current cursor position.
virtual void keyPressEvent (QKeyEvent *e)
Reimplemented Function
virtual void keyReleaseEvent (QKeyEvent *e)
Reimplemented Function
virtual void mouseDoubleClickEvent (QMouseEvent *e)
Reimplemented Function
virtual void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
virtual void mousePressEvent (QMouseEvent *e)
Reimplemented Function
virtual void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
QPlainTextEdit (QPlainTextEditPrivate &dd, QWidget *parent)
virtual void scrollContentsBy (int dx, int dy)
em>Reimplemented Function
virtual void showEvent (QShowEvent *)
Reimplemented Function
virtual void timerEvent (QTimerEvent *e)
virtual void wheelEvent (QWheelEvent *e)
Reimplemented Function
Protected Functions inherited from QAbstractScrollArea
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
virtual bool viewportEvent (QEvent *)
The main event handler for the scrolling area (the viewport() widget).
Protected Functions inherited from QFrame
void drawFrame (QPainter *)
em>Reimplemented Function
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Slots
void highlightCurrentLine ()
void updateExtraArea (const QRect &, int)
void updateExtraAreaWidth ()
Private Functions
QTextEdit::ExtraSelection currentExecutionLineSelection () const
QTextEdit::ExtraSelection currentLineSelection () const
void updateExtraSelections ()
Properties
int m_baseLineNumber
QHash< int, BreakpointData > m_breakpoints
QSet< int > m_executableLineNumbers
int m_executionLineNumber
bool m_executionLineNumberHasError
QScriptEditExtraArea * m_extraArea
int m_extraAreaToggleBlockNumber
Friends
class QScriptEditExtraArea
Additional Inherited Members
Public Types inherited from QPlainTextEdit
enum LineWrapMode { NoWrap, WidgetWidth }
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QPlainTextEdit
void appendHtml (const QString &html)
Appends a new paragraph with html to the end of the text edit.
void appendPlainText (const QString &text)
Appends a new paragraph with text to the end of the text edit.
void centerCursor ()
Scrolls the document in order to center the cursor vertically.
void clear ()
Deletes all the text in the text edit.
void copy ()
Copies any selected text to the clipboard.
void cut ()
Copies the selected text to the clipboard and deletes it from the text edit.
void insertPlainText (const QString &text)
Convenience slot that inserts text at the current cursor position.
void paste ()
Pastes the text from the clipboard into the text edit at the current cursor position.
void redo ()
Redoes the last operation.
void selectAll ()
Selects all text.
void setPlainText (const QString &text)
Changes the text of the text edit to the string text.
void undo ()
Undoes the last operation.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 65 of file qscriptedit_p.h.
Constructors and Destructors
QScriptEdit()
QScriptEdit::QScriptEdit (QWidget * parent = 0)
Definition at line 103 of file qscriptedit.cpp.
     : QPlainTextEdit(parent)
 {
     m_baseLineNumber = 1;
     m_executionLineNumber = -1;
     m_extraArea = new QScriptEditExtraArea(this);
     QObject::connect(this, SIGNAL(blockCountChanged(int)),
                      this, SLOT(updateExtraAreaWidth()));
     QObject::connect(this, SIGNAL(updateRequest(QRect,int)),
                      this, SLOT(updateExtraArea(QRect,int)));
     QObject::connect(this, SIGNAL(cursorPositionChanged()),
                      this, SLOT(highlightCurrentLine()));
     updateExtraAreaWidth();
 #ifndef QT_NO_SYNTAXHIGHLIGHTER
     (void) new QScriptSyntaxHighlighter(document());
 #endif
 }
~QScriptEdit()
QScriptEdit::~QScriptEdit ()
Definition at line 125 of file qscriptedit.cpp.
 {
 }
Functions
baseLineNumber()
int QScriptEdit::baseLineNumber () const
Definition at line 129 of file qscriptedit.cpp.
 {
     return m_baseLineNumber;
 }
breakpointEnableRequest
void QScriptEdit::breakpointEnableRequest (int lineNumber, bool enable) signal
Referenced by extraAreaMouseEvent().
breakpointToggleRequest
void QScriptEdit::breakpointToggleRequest (int lineNumber, bool on) signal
Referenced by extraAreaMouseEvent().
currentExecutionLineSelection()
QTextEdit::ExtraSelection QScriptEdit::currentExecutionLineSelection () const private
currentLineNumber()
int QScriptEdit::currentLineNumber () const
Definition at line 169 of file qscriptedit.cpp.
 {
     return textCursor().blockNumber() + m_baseLineNumber;
 }
currentLineSelection()
QTextEdit::ExtraSelection QScriptEdit::currentLineSelection () const private
deleteBreakpoint()
void QScriptEdit::deleteBreakpoint (int lineNumber)
Definition at line 196 of file qscriptedit.cpp.
 {
     m_breakpoints.remove(lineNumber);
     m_extraArea->update();
 }
executionLineNumber()
int QScriptEdit::executionLineNumber () const
Definition at line 140 of file qscriptedit.cpp.
 {
     return m_executionLineNumber;
 }
extraAreaEvent()
bool QScriptEdit::extraAreaEvent (QEvent * e) protected
Definition at line 444 of file qscriptedit.cpp.
 {
     if (e->type() == QEvent::ToolTip) {
         // ### show the breakpoint's condition, if any
         return true;
     }
     return false;
 }
extraAreaMouseEvent()
void QScriptEdit::extraAreaMouseEvent (QMouseEvent * e) protected
Definition at line 371 of file qscriptedit.cpp.
Referenced by QScriptEditExtraArea::mouseMoveEvent(), QScriptEditExtraArea::mousePressEvent(), and QScriptEditExtraArea::mouseReleaseEvent().
 {
     QTextCursor cursor = cursorForPosition(QPoint(0, e->pos().y()));
     cursor.setPosition(cursor.block().position());
     QFontMetrics fm(font());
     int markWidth = fm.lineSpacing();
     if (e->type() == QEvent::MouseMove && e->buttons() == 0) { // mouse tracking
         bool hand = (e->pos().x() <= markWidth);
         int lineNumber = cursor.blockNumber() + m_baseLineNumber;
         hand = hand && isExecutableLine(lineNumber);
 #ifndef QT_NO_CURSOR
         if (hand != (m_extraArea->cursor().shape() == Qt::PointingHandCursor))
             m_extraArea->setCursor(hand ? Qt::PointingHandCursor : Qt::ArrowCursor);
 #endif
     }
     if (e->type() == QEvent::MouseButtonPress) {
         if (e->button() == Qt::LeftButton) {
             int lineNumber = cursor.blockNumber() + m_baseLineNumber;
             bool executable = isExecutableLine(lineNumber);
             if ((e->pos().x() <= markWidth) && executable)
                 m_extraAreaToggleBlockNumber = cursor.blockNumber();
             else
                 m_extraAreaToggleBlockNumber = -1;
         }
     } else if (e->type() == QEvent::MouseButtonRelease) {
         if (e->button() == Qt::LeftButton) {
             if ((m_extraAreaToggleBlockNumber != -1) && (e->pos().x() <= markWidth)) {
                 int lineNumber = m_extraAreaToggleBlockNumber + m_baseLineNumber;
                 bool on = !m_breakpoints.contains(lineNumber);
                 emit breakpointToggleRequest(lineNumber, on);
             }
         } else if (e->button() == Qt::RightButton) {
             int lineNumber = cursor.blockNumber() + m_baseLineNumber;
             if (!isExecutableLine(lineNumber))
                 return;
             bool has = m_breakpoints.contains(lineNumber);
             QMenu *popup = new QMenu();
             QAction *toggleAct = new QAction(tr("Toggle Breakpoint"), popup);
             popup->addAction(toggleAct);
             QAction *disableAct = new QAction(tr("Disable Breakpoint"), popup);
             QAction *enableAct = new QAction(tr("Enable Breakpoint"), popup);
             QWidget *conditionWidget = new QWidget();
             {
                 QHBoxLayout *hbox = new QHBoxLayout(conditionWidget);
                 hbox->addWidget(new QLabel(tr("Breakpoint Condition:")));
                 hbox->addWidget(new QLineEdit());
             }
 //            QWidgetAction *conditionAct = new QWidgetAction(popup);
 //            conditionAct->setDefaultWidget(conditionWidget);
             if (has) {
                 popup->addSeparator();
                 popup->addAction(m_breakpoints[lineNumber].enabled ? disableAct : enableAct);
 //                popup->addAction(conditionAct);
             }
             QAction *ret = popup->exec(e->globalPos());
             if (ret) {
                 if (ret == toggleAct) {
                     emit breakpointToggleRequest(lineNumber, !has);
                 } else if (ret == disableAct) {
                     emit breakpointEnableRequest(lineNumber, false);
                 } else if (ret == enableAct) {
                     emit breakpointEnableRequest(lineNumber, true);
                 }// else if (ret == conditionAct) {
                 //}
             }
             popup->deleteLater();
         }
     }
 }
extraAreaPaintEvent()
void QScriptEdit::extraAreaPaintEvent (QPaintEvent * e) protected
Definition at line 292 of file qscriptedit.cpp.
Referenced by QScriptEditExtraArea::paintEvent().
 {
     QRect rect = e->rect();
     QPalette pal = palette();
     pal.setCurrentColorGroup(QPalette::Active);
     QPainter painter(m_extraArea);
     painter.fillRect(rect, Qt::lightGray);
     const QFontMetrics fm(fontMetrics());
     int markWidth = fm.lineSpacing();
     int extraAreaWidth = m_extraArea->width();
     QLinearGradient gradient(QPointF(extraAreaWidth - 10, 0), QPointF(extraAreaWidth, 0));
     gradient.setColorAt(0, pal.color(QPalette::Background));
     gradient.setColorAt(1, pal.color(QPalette::Base));
     painter.fillRect(rect, gradient);
     QLinearGradient gradient2(QPointF(0, 0), QPointF(markWidth, 0));
     gradient2.setColorAt(0, pal.color(QPalette::Dark));
     gradient2.setColorAt(1, pal.color(QPalette::Background));
     painter.fillRect(rect.intersected(QRect(rect.x(), rect.y(), markWidth, rect.height())), gradient2);
     painter.setPen(QPen(pal.color(QPalette::Background), 2));
     if (isLeftToRight())
         painter.drawLine(rect.x() + extraAreaWidth-1, rect.top(), rect.x() + extraAreaWidth-1, rect.bottom());
     else
         painter.drawLine(rect.x(), rect.top(), rect.x(), rect.bottom());
     painter.setRenderHint(QPainter::Antialiasing);
     QTextBlock block = firstVisibleBlock();
     int blockNumber = block.blockNumber();
     qreal top = blockBoundingGeometry(block).translated(contentOffset()).top();
     qreal bottom = top + blockBoundingRect(block).height();
     QString imagesPath = QString::fromLatin1(":/qt/scripttools/debugging/images");
     QString imageExt;
 // SVGs don't work on all platforms, even when QT_NO_SVG is not defined, so disable SVG usage for now.
 // #ifndef QT_NO_SVG
 #if 0
     imageExt = QString::fromLatin1("svg");
 #else
     imageExt = QString::fromLatin1("png");
 #endif
     while (block.isValid() && top <= rect.bottom()) {
         if (block.isVisible() && bottom >= rect.top()) {
             int lineNumber = blockNumber + m_baseLineNumber;
             if (m_breakpoints.contains(lineNumber)) {
                 int radius = fm.lineSpacing() - 1;
                 QRect r(rect.x(), (int)top, radius, radius);
                 QIcon icon(m_breakpoints[lineNumber].enabled
                            ? QString::fromLatin1("%0/breakpoint.%1").arg(imagesPath).arg(imageExt)
                            : QString::fromLatin1("%0/d_breakpoint.%1").arg(imagesPath).arg(imageExt));
                 icon.paint(&painter, r, Qt::AlignCenter);
             }
             if (m_executionLineNumber == lineNumber) {
                 int radius = fm.lineSpacing() - 1;
                 QRect r(rect.x(), (int)top, radius, radius);
                 QIcon icon(QString::fromLatin1("%0/location.%1").arg(imagesPath).arg(imageExt));
                 icon.paint(&painter, r, Qt::AlignCenter);
             }
             if (!isExecutableLine(lineNumber))
                 painter.setPen(pal.color(QPalette::Mid));
             else
                 painter.setPen(QColor(Qt::darkCyan));
             QString number = QString::number(lineNumber);
             painter.drawText(rect.x() + markWidth, (int)top, rect.x() + extraAreaWidth - markWidth - 4,
                              fm.height(), Qt::AlignRight, number);
         }
         block = block.next();
         top = bottom;
         bottom = top + blockBoundingRect(block).height();
         ++blockNumber;
     }
 }
extraAreaWidth()
int QScriptEdit::extraAreaWidth () const
Definition at line 271 of file qscriptedit.cpp.
Referenced by extraAreaPaintEvent(), resizeEvent(), and updateExtraAreaWidth().
 {
     int space = 0;
     const QFontMetrics fm(fontMetrics());
     int digits = 1;
     int max = qMax(1, blockCount() + m_baseLineNumber);
     while (max >= 10) {
         max /= 10;
         ++digits;
     }
     space += fm.width(QLatin1Char('9')) * digits;
     int markWidth = fm.lineSpacing();
     space += markWidth;
     space += 4;
     return space;
 }
gotoLine()
void QScriptEdit::gotoLine (int lineNumber)
Definition at line 174 of file qscriptedit.cpp.
Referenced by setExecutionLineNumber().
 {
     int blockNumber = lineNumber - m_baseLineNumber;
     const QTextBlock &block = document()->findBlockByNumber(blockNumber);
     if (block.isValid()) {
         setTextCursor(QTextCursor(block));
         centerCursor();
     }
 }
highlightCurrentLine
void QScriptEdit::highlightCurrentLine () private slot
Definition at line 235 of file qscriptedit.cpp.
Referenced by QScriptEdit().
 {
     updateExtraSelections();
 }
isExecutableLine()
bool QScriptEdit::isExecutableLine (int lineNumber) const
Definition at line 159 of file qscriptedit.cpp.
Referenced by extraAreaMouseEvent(), and extraAreaPaintEvent().
 {
 #if 0 // ### enable me once we have information about the script again
     return m_executableLineNumbers.contains(lineNumber);
 #else
     Q_UNUSED(lineNumber);
     return true;
 #endif
 }
paintEvent()
void QScriptEdit::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QPlainTextEdit.
Definition at line 202 of file qscriptedit.cpp.
 {
     QPlainTextEdit::paintEvent(e);
 }
resizeEvent()
void QScriptEdit::resizeEvent (QResizeEvent * e) protected virtual
Reimplemented Function
Reimplemented from QPlainTextEdit.
Definition at line 207 of file qscriptedit.cpp.
 {
     QPlainTextEdit::resizeEvent(e);
     QRect cr = contentsRect();
     int x = isLeftToRight() ? cr.left() : cr.left() + cr.width() - extraAreaWidth();
     m_extraArea->setGeometry(QRect(x, cr.top(), extraAreaWidth(), cr.height()));
 }
setBaseLineNumber()
void QScriptEdit::setBaseLineNumber (int base)
Definition at line 134 of file qscriptedit.cpp.
 {
     m_baseLineNumber = base;
     m_extraArea->update();
 }
setBreakpoint()
void QScriptEdit::setBreakpoint (int lineNumber)
Definition at line 184 of file qscriptedit.cpp.
 {
     m_breakpoints[lineNumber] = BreakpointData();
     m_extraArea->update();
 }
setBreakpointEnabled()
void QScriptEdit::setBreakpointEnabled (int lineNumber, bool enable)
Definition at line 190 of file qscriptedit.cpp.
 {
     m_breakpoints[lineNumber].enabled = enable;
     m_extraArea->update();
 }
setExecutableLineNumbers()
void QScriptEdit::setExecutableLineNumbers (const QSet< int > & lineNumbers)
Definition at line 154 of file qscriptedit.cpp.
 {
     m_executableLineNumbers = lineNumbers;
 }
setExecutionLineNumber()
void QScriptEdit::setExecutionLineNumber (int lineNumber, bool error)
Definition at line 145 of file qscriptedit.cpp.
 {
     m_executionLineNumber = lineNumber;
     m_executionLineNumberHasError = error;
     m_extraArea->update();
     updateExtraSelections();
     gotoLine(lineNumber);
 }
updateExtraArea
void QScriptEdit::updateExtraArea (const QRect & rect, int dy) private slot
Definition at line 224 of file qscriptedit.cpp.
Referenced by QScriptEdit().
 {
     if (dy)
         m_extraArea->scroll(0, dy);
     else
         m_extraArea->update(0, rect.y(), m_extraArea->width(), rect.height());
     if (rect.contains(viewport()->rect()))
         updateExtraAreaWidth();
 }
updateExtraAreaWidth
void QScriptEdit::updateExtraAreaWidth () private slot
Definition at line 216 of file qscriptedit.cpp.
Referenced by QScriptEdit(), and updateExtraArea().
 {
     if (isLeftToRight())
         setViewportMargins(extraAreaWidth(), 0, 0, 0);
     else
         setViewportMargins(0, 0, extraAreaWidth(), 0);
 }
updateExtraSelections()
void QScriptEdit::updateExtraSelections () private
Definition at line 240 of file qscriptedit.cpp.
Referenced by highlightCurrentLine(), and setExecutionLineNumber().
 {
     QList<QTextEdit::ExtraSelection> extraSelections;
     {
         QTextEdit::ExtraSelection selection;
         QColor lineColor = QColor(Qt::yellow).lighter(160);
         selection.format.setBackground(lineColor);
         selection.format.setProperty(QTextFormat::FullWidthSelection, true);
         selection.cursor = textCursor();
         selection.cursor.clearSelection();
         extraSelections.append(selection);
     }
     if (m_executionLineNumber != -1) {
         QTextEdit::ExtraSelection selection;
         QColor lineColor;
         if (m_executionLineNumberHasError)
             lineColor = QColor(Qt::red);
         else
             lineColor = QColor(Qt::green).lighter(160);
         selection.format.setBackground(lineColor);
         selection.format.setProperty(QTextFormat::FullWidthSelection, true);
         int blockNumber = m_executionLineNumber - m_baseLineNumber;
         selection.cursor = QTextCursor(document()->findBlockByNumber(blockNumber));
         selection.cursor.clearSelection();
         extraSelections.append(selection);
     }
     setExtraSelections(extraSelections);
 }
Friends and Related Functions
QScriptEditExtraArea
friend class QScriptEditExtraArea friend
Definition at line 127 of file qscriptedit_p.h.
Referenced by QScriptEdit().
Properties
m_baseLineNumber
int QScriptEdit::m_baseLineNumber private
Definition at line 113 of file qscriptedit_p.h.
Referenced by baseLineNumber(), currentLineNumber(), extraAreaMouseEvent(), extraAreaPaintEvent(), extraAreaWidth(), gotoLine(), QScriptEdit(), setBaseLineNumber(), and updateExtraSelections().
m_breakpoints
QHash<int, BreakpointData> QScriptEdit::m_breakpoints private
Definition at line 123 of file qscriptedit_p.h.
Referenced by deleteBreakpoint(), extraAreaMouseEvent(), extraAreaPaintEvent(), setBreakpoint(), and setBreakpointEnabled().
m_executableLineNumbers
QSet<int> QScriptEdit::m_executableLineNumbers private
Definition at line 115 of file qscriptedit_p.h.
Referenced by isExecutableLine(), and setExecutableLineNumbers().
m_executionLineNumber
int QScriptEdit::m_executionLineNumber private
Definition at line 114 of file qscriptedit_p.h.
Referenced by executionLineNumber(), extraAreaPaintEvent(), QScriptEdit(), setExecutionLineNumber(), and updateExtraSelections().
m_executionLineNumberHasError
bool QScriptEdit::m_executionLineNumberHasError private
Definition at line 116 of file qscriptedit_p.h.
Referenced by setExecutionLineNumber(), and updateExtraSelections().
m_extraArea
QScriptEditExtraArea* QScriptEdit::m_extraArea private
Definition at line 112 of file qscriptedit_p.h.
Referenced by deleteBreakpoint(), extraAreaMouseEvent(), extraAreaPaintEvent(), QScriptEdit(), resizeEvent(), setBaseLineNumber(), setBreakpoint(), setBreakpointEnabled(), setExecutionLineNumber(), and updateExtraArea().
m_extraAreaToggleBlockNumber
int QScriptEdit::m_extraAreaToggleBlockNumber private
Definition at line 117 of file qscriptedit_p.h.
Referenced by extraAreaMouseEvent().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptedit_p.h
/src/scripttools/debugging/qscriptedit.cpp