Qt 4.8: QEventDispatcherUNIX Class Reference
QEventDispatcherUNIX Class Reference
#include <qeventdispatcher_unix_p.h>
Public Functions
void flush ()
Flushes the event queue.
bool hasPendingEvents ()
Returns true if there is an event waiting; otherwise returns false.
void interrupt ()
Interrupts event dispatching; i.
bool processEvents (QEventLoop::ProcessEventsFlags flags)
Processes pending events that match flags until there are no more events to process.
QEventDispatcherUNIX (QObject *parent=0)
QList< TimerInfo > registeredTimers (QObject *object) const
Returns a list of registered timers for object.
void registerSocketNotifier (QSocketNotifier *notifier)
Registers notifier with the event loop.
void registerTimer (int timerId, int interval, QObject *object)
void unregisterSocketNotifier (QSocketNotifier *notifier)
Unregisters notifier from the event dispatcher.
bool unregisterTimer (int timerId)
bool unregisterTimers (QObject *object)
void wakeUp ()
Wakes up the event loop.
~QEventDispatcherUNIX ()
Public Functions inherited from QAbstractEventDispatcher
virtual void closingDown ()
bool filterEvent (void *message)
Sends message through the event filter that was set by setEventFilter().
QAbstractEventDispatcher (QObject *parent=0)
Constructs a new event dispatcher with the given parent.
int registerTimer (int interval, QObject *object)
Registers a timer with the specified interval for the given object.
EventFilter setEventFilter (EventFilter filter)
Replaces the event filter function for this QAbstractEventDispatcher with filter and returns the replaced event filter function.
virtual void startingUp ()
~QAbstractEventDispatcher ()
Destroys the event dispatcher.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
int activateSocketNotifiers ()
int activateTimers ()
QEventDispatcherUNIX (QEventDispatcherUNIXPrivate &dd, QObject *parent=0)
virtual int select (int nfds, fd_set *readfds, fd_set *writefds, fd_set *exceptfds, timeval *timeout)
void setSocketNotifierPending (QSocketNotifier *notifier)
Protected Functions inherited from QAbstractEventDispatcher
QAbstractEventDispatcher (QAbstractEventDispatcherPrivate &, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Types inherited from QAbstractEventDispatcher
typedef bool(* EventFilter) (void *message)
Typedef for a function with the signature.
typedef QPair< int, int > TimerInfo
Typedef for QPair<int, int>.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractEventDispatcher
void aboutToBlock ()
This signal is emitted before the event loop calls a function that could block.
void awake ()
This signal is emitted after the event loop returns from a function that could block.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QAbstractEventDispatcher
static QAbstractEventDispatcher * instance (QThread *thread=0)
Returns a pointer to the event dispatcher object for the specified thread.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 140 of file qeventdispatcher_unix_p.h.
Constructors and Destructors
QEventDispatcherUNIX() [1/2]
QEventDispatcherUNIX::QEventDispatcherUNIX (QObject * parent = 0) explicit
Definition at line 632 of file qeventdispatcher_unix.cpp.
     : QAbstractEventDispatcher(*new QEventDispatcherUNIXPrivate, parent)
 { }
~QEventDispatcherUNIX()
QEventDispatcherUNIX::~QEventDispatcherUNIX ()
Definition at line 640 of file qeventdispatcher_unix.cpp.
 {
     Q_D(QEventDispatcherUNIX);
     d->threadData->eventDispatcher = 0;
 }
QEventDispatcherUNIX() [2/2]
QEventDispatcherUNIX::QEventDispatcherUNIX (QEventDispatcherUNIXPrivate & dd, QObject * parent = 0) protected
Definition at line 636 of file qeventdispatcher_unix.cpp.
     : QAbstractEventDispatcher(dd, parent)
 { }
Functions
activateSocketNotifiers()
int QEventDispatcherUNIX::activateSocketNotifiers () protected
Definition at line 881 of file qeventdispatcher_unix.cpp.
 {
     Q_D(QEventDispatcherUNIX);
     if (d->sn_pending_list.isEmpty())
         return 0;
     // activate entries
     int n_act = 0;
     QEvent event(QEvent::SockAct);
     while (!d->sn_pending_list.isEmpty()) {
         QSockNot *sn = d->sn_pending_list.takeFirst();
         if (FD_ISSET(sn->fd, sn->queue)) {
             FD_CLR(sn->fd, sn->queue);
             QCoreApplication::sendEvent(sn->obj, &event);
             ++n_act;
         }
     }
     return n_act;
 }
activateTimers()
int QEventDispatcherUNIX::activateTimers () protected
Definition at line 874 of file qeventdispatcher_unix.cpp.
Referenced by processEvents().
 {
     Q_ASSERT(thread() == QThread::currentThread());
     Q_D(QEventDispatcherUNIX);
     return d->timerList.activateTimers();
 }
flush()
void QEventDispatcherUNIX::flush () virtual
Flushes the event queue.
This normally returns almost immediately. Does nothing on platforms other than X11.
Implements QAbstractEventDispatcher.
Reimplemented in QEventDispatcherQPA, QEventDispatcherQWS, QEventDispatcherX11, and QEventDispatcherBlackberryQPA.
Definition at line 969 of file qeventdispatcher_unix.cpp.
 { }
hasPendingEvents()
bool QEventDispatcherUNIX::hasPendingEvents () virtual
Returns true if there is an event waiting; otherwise returns false.
Implements QAbstractEventDispatcher.
Reimplemented in QEventDispatcherQPA, QEventDispatcherQWS, QEventDispatcherX11, and QEventDispatcherBlackberryQPA.
Definition at line 947 of file qeventdispatcher_unix.cpp.
Referenced by QEventDispatcherBlackberryQPA::hasPendingEvents().
 {
     extern uint qGlobalPostedEventsCount(); // from qapplication.cpp
     return qGlobalPostedEventsCount();
 }
interrupt()
void QEventDispatcherUNIX::interrupt () virtual
Interrupts event dispatching; i.
e. the event dispatcher will return from processEvents() as soon as possible.
Implements QAbstractEventDispatcher.
Definition at line 962 of file qeventdispatcher_unix.cpp.
 {
     Q_D(QEventDispatcherUNIX);
     d->interrupt = true;
     wakeUp();
 }
processEvents()
bool QEventDispatcherUNIX::processEvents (QEventLoop::ProcessEventsFlags flags) virtual
Processes pending events that match flags until there are no more events to process.
Returns true if an event was processed; otherwise returns false.
This function is especially useful if you have a long running operation and want to show its progress without allowing user input; i.e. by using the QEventLoop::ExcludeUserInputEvents flag.
If the QEventLoop::WaitForMoreEvents flag is set in flags, the behavior of this function is as follows:
If events are available, this function returns after processing them.
If no events are available, this function will wait until more are available and return after processing newly available events.
If the QEventLoop::WaitForMoreEvents flag is not set in flags, and no events are available, this function will return immediately.
Note: This function does not process events continuously; it returns after all available events are processed.
See also
hasPendingEvents()
Implements QAbstractEventDispatcher.
Reimplemented in QEventDispatcherQPA, QEventDispatcherQWS, QEventDispatcherX11, and QEventDispatcherBlackberryQPA.
Definition at line 901 of file qeventdispatcher_unix.cpp.
Referenced by QEventDispatcherBlackberryQPA::processEvents(), QEventDispatcherX11::processEvents(), QEventDispatcherQWS::processEvents(), and QEventDispatcherQPA::processEvents().
 {
     Q_D(QEventDispatcherUNIX);
     d->interrupt = false;
     // we are awake, broadcast it
     emit awake();
     QCoreApplicationPrivate::sendPostedEvents(0, 0, d->threadData);
     int nevents = 0;
     const bool canWait = (d->threadData->canWaitLocked()
                           && !d->interrupt
                           && (flags & QEventLoop::WaitForMoreEvents));
     if (canWait)
         emit aboutToBlock();
     if (!d->interrupt) {
         // return the maximum time we can wait for an event.
         timeval *tm = 0;
         timeval wait_tm = { 0l, 0l };
         if (!(flags & QEventLoop::X11ExcludeTimers)) {
             if (d->timerList.timerWait(wait_tm))
                 tm = &wait_tm;
         }
         if (!canWait) {
             if (!tm)
                 tm = &wait_tm;
             // no time to wait
             tm->tv_sec  = 0l;
             tm->tv_usec = 0l;
         }
         nevents = d->doSelect(flags, tm);
         // activate timers
         if (! (flags & QEventLoop::X11ExcludeTimers)) {
             nevents += activateTimers();
         }
     }
     // return true if we handled events, false otherwise
     return (nevents > 0);
 }
registeredTimers()
QList< QEventDispatcherUNIX::TimerInfo > QEventDispatcherUNIX::registeredTimers (QObject * object) const virtual
Returns a list of registered timers for object.
The timer ID is the first member in each pair; the interval is the second.
Implements QAbstractEventDispatcher.
Definition at line 710 of file qeventdispatcher_unix.cpp.
 {
     if (!object) {
         qWarning("QEventDispatcherUNIX:registeredTimers: invalid argument");
         return QList<TimerInfo>();
     }
     Q_D(const QEventDispatcherUNIX);
     return d->timerList.registeredTimers(object);
 }
registerSocketNotifier()
void QEventDispatcherUNIX::registerSocketNotifier (QSocketNotifier * notifier) virtual
Registers notifier with the event loop.
Subclasses must implement this method to tie a socket notifier into another event loop.
Implements QAbstractEventDispatcher.
Reimplemented in QEventDispatcherQPA.
Definition at line 741 of file qeventdispatcher_unix.cpp.
Referenced by QEventDispatcherBlackberry::registerSocketNotifier(), and QEventDispatcherQPA::registerSocketNotifier().
 {
     Q_ASSERT(notifier);
     int sockfd = notifier->socket();
     int type = notifier->type();
 #ifndef QT_NO_DEBUG
     if (sockfd < 0
         || unsigned(sockfd) >= FD_SETSIZE) {
         qWarning("QSocketNotifier: Internal error");
         return;
     } else if (notifier->thread() != thread()
                || thread() != QThread::currentThread()) {
         qWarning("QSocketNotifier: socket notifiers cannot be enabled from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherUNIX);
     QSockNotType::List &list = d->sn_vec[type].list;
     fd_set *fds  = &d->sn_vec[type].enabled_fds;
     QSockNot *sn;
     sn = new QSockNot;
     sn->obj = notifier;
     sn->fd = sockfd;
     sn->queue = &d->sn_vec[type].pending_fds;
     int i;
     for (i = 0; i < list.size(); ++i) {
         QSockNot *p = list[i];
         if (p->fd < sockfd)
             break;
         if (p->fd == sockfd) {
             static const char *t[] = { "Read", "Write", "Exception" };
             qWarning("QSocketNotifier: Multiple socket notifiers for "
                       "same socket %d and type %s", sockfd, t[type]);
         }
     }
     list.insert(i, sn);
     FD_SET(sockfd, fds);
     d->sn_highest = qMax(d->sn_highest, sockfd);
 }
registerTimer()
void QEventDispatcherUNIX::registerTimer (int timerId, int interval, QObject * obj) virtual
Warning
This function is not part of the public interface.
Implements QAbstractEventDispatcher.
Definition at line 655 of file qeventdispatcher_unix.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (timerId < 1 || interval < 0 || !obj) {
         qWarning("QEventDispatcherUNIX::registerTimer: invalid arguments");
         return;
     } else if (obj->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QObject::startTimer: timers cannot be started from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherUNIX);
     d->timerList.registerTimer(timerId, interval, obj);
 }
select()
int QEventDispatcherUNIX::select (int nfds, fd_set * readfds, fd_set * writefds, fd_set * exceptfds, timeval * timeout) protected virtual
Reimplemented in QEventDispatcherQPA, QEventDispatcherQWS, QEventDispatcherX11, and QEventDispatcherBlackberry.
Definition at line 646 of file qeventdispatcher_unix.cpp.
Referenced by QEventDispatcherQPA::select(), QEventDispatcherX11::select(), and QEventDispatcherQWS::select().
 {
     return qt_safe_select(nfds, readfds, writefds, exceptfds, timeout);
 }
setSocketNotifierPending()
void QEventDispatcherUNIX::setSocketNotifierPending (QSocketNotifier * notifier) protected
Definition at line 831 of file qeventdispatcher_unix.cpp.
 {
     Q_ASSERT(notifier);
     int sockfd = notifier->socket();
     int type = notifier->type();
 #ifndef QT_NO_DEBUG
     if (sockfd < 0
         || unsigned(sockfd) >= FD_SETSIZE) {
         qWarning("QSocketNotifier: Internal error");
         return;
     }
     Q_ASSERT(notifier->thread() == thread() && thread() == QThread::currentThread());
 #endif
     Q_D(QEventDispatcherUNIX);
     QSockNotType::List &list = d->sn_vec[type].list;
     QSockNot *sn = 0;
     int i;
     for (i = 0; i < list.size(); ++i) {
         sn = list[i];
         if(sn->obj == notifier && sn->fd == sockfd)
             break;
     }
     if (i == list.size()) // not found
         return;
     // We choose a random activation order to be more fair under high load.
     // If a constant order is used and a peer early in the list can
     // saturate the IO, it might grab our attention completely.
     // Also, if we're using a straight list, the callback routines may
     // delete other entries from the list before those other entries are
     // processed.
     if (! FD_ISSET(sn->fd, sn->queue)) {
         if (d->sn_pending_list.isEmpty()) {
             d->sn_pending_list.append(sn);
         } else {
             d->sn_pending_list.insert((qrand() & 0xff) %
                                       (d->sn_pending_list.size()+1), sn);
         }
         FD_SET(sn->fd, sn->queue);
     }
 }
unregisterSocketNotifier()
void QEventDispatcherUNIX::unregisterSocketNotifier (QSocketNotifier * notifier) virtual
Unregisters notifier from the event dispatcher.
Subclasses must reimplement this method to tie a socket notifier into another event loop. Reimplementations must call the base implementation.
Implements QAbstractEventDispatcher.
Reimplemented in QEventDispatcherQPA.
Definition at line 785 of file qeventdispatcher_unix.cpp.
Referenced by QEventDispatcherBlackberry::unregisterSocketNotifier(), and QEventDispatcherQPA::unregisterSocketNotifier().
 {
     Q_ASSERT(notifier);
     int sockfd = notifier->socket();
     int type = notifier->type();
 #ifndef QT_NO_DEBUG
     if (sockfd < 0
         || unsigned(sockfd) >= FD_SETSIZE) {
         qWarning("QSocketNotifier: Internal error");
         return;
     } else if (notifier->thread() != thread()
                || thread() != QThread::currentThread()) {
         qWarning("QSocketNotifier: socket notifiers cannot be disabled from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherUNIX);
     QSockNotType::List &list = d->sn_vec[type].list;
     fd_set *fds  =  &d->sn_vec[type].enabled_fds;
     QSockNot *sn = 0;
     int i;
     for (i = 0; i < list.size(); ++i) {
         sn = list[i];
         if(sn->obj == notifier && sn->fd == sockfd)
             break;
     }
     if (i == list.size()) // not found
         return;
     FD_CLR(sockfd, fds);                        // clear fd bit
     FD_CLR(sockfd, sn->queue);
     d->sn_pending_list.removeAll(sn);                // remove from activation list
     list.removeAt(i);                                // remove notifier found above
     delete sn;
     if (d->sn_highest == sockfd) {                // find highest fd
         d->sn_highest = -1;
         for (int i=0; i<3; i++) {
             if (!d->sn_vec[i].list.isEmpty())
                 d->sn_highest = qMax(d->sn_highest,  // list is fd-sorted
                                      d->sn_vec[i].list[0]->fd);
         }
     }
 }
unregisterTimer()
bool QEventDispatcherUNIX::unregisterTimer (int timerId) virtual
Warning
This function is not part of the public interface.
Implements QAbstractEventDispatcher.
Definition at line 674 of file qeventdispatcher_unix.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (timerId < 1) {
         qWarning("QEventDispatcherUNIX::unregisterTimer: invalid argument");
         return false;
     } else if (thread() != QThread::currentThread()) {
         qWarning("QObject::killTimer: timers cannot be stopped from another thread");
         return false;
     }
 #endif
     Q_D(QEventDispatcherUNIX);
     return d->timerList.unregisterTimer(timerId);
 }
unregisterTimers()
bool QEventDispatcherUNIX::unregisterTimers (QObject * object) virtual
Warning
This function is not part of the public interface.
Implements QAbstractEventDispatcher.
Definition at line 693 of file qeventdispatcher_unix.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (!object) {
         qWarning("QEventDispatcherUNIX::unregisterTimers: invalid argument");
         return false;
     } else if (object->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QObject::killTimers: timers cannot be stopped from another thread");
         return false;
     }
 #endif
     Q_D(QEventDispatcherUNIX);
     return d->timerList.unregisterTimers(object);
 }
wakeUp()
void QEventDispatcherUNIX::wakeUp () virtual
Wakes up the event loop.
Note
This class or function is threadsafe.
See also
awake()
Implements QAbstractEventDispatcher.
Definition at line 953 of file qeventdispatcher_unix.cpp.
Referenced by interrupt(), QEventDispatcherQPA::registerSocketNotifier(), and QEventDispatcherQPA::unregisterSocketNotifier().
 {
     Q_D(QEventDispatcherUNIX);
     if (d->wakeUps.testAndSetAcquire(0, 1)) {
         char c = 0;
         qt_safe_write( d->thread_pipe[1], &c, 1 );
     }
 }
The documentation for this class was generated from the following files:
/src/corelib/kernel/qeventdispatcher_unix_p.h
/src/corelib/kernel/qeventdispatcher_unix.cpp