Qt 4.8: QScriptDebuggerConsoleCommand Class Reference
QScriptDebuggerConsoleCommand Class Reference abstract
The QScriptDebuggerConsoleCommand class is the base class of console commands.
#include <qscriptdebuggerconsolecommand_p.h>
Public Functions
virtual QStringList aliases () const
Returns a list of aliases for this command.
virtual QStringList argumentTypes () const
virtual QScriptDebuggerConsoleCommandJob * createJob (const QStringList &arguments, QScriptDebuggerConsole *console, QScriptMessageHandlerInterface *messageHandler, QScriptDebuggerCommandSchedulerInterface *scheduler)=0
Creates a job that will execute this command with the given arguments.
virtual QString group () const =0
Returns the group that this console command belongs to.
virtual QString longDescription () const =0
Returns a detailed description of how to use the command.
virtual QString name () const =0
Returns the name of this console command.
QScriptDebuggerConsoleCommand ()
virtual QStringList seeAlso () const
Returns a list of names of commands that may also be of interest to users of this command.
virtual QString shortDescription () const =0
Returns a short (one line) description of the command.
virtual QStringList subCommands () const
virtual ~QScriptDebuggerConsoleCommand ()
Protected Functions
QScriptDebuggerConsoleCommand (QScriptDebuggerConsoleCommandPrivate &dd)
Protected Variables
QScopedPointer< QScriptDebuggerConsoleCommandPrivate > d_ptr
Detailed Description
The QScriptDebuggerConsoleCommand class is the base class of console commands.
Since
4.5
Warning
This function is not part of the public interface.
See also
QScriptDebuggerConsoleCommandManager
Definition at line 70 of file qscriptdebuggerconsolecommand_p.h.
Constructors and Destructors
QScriptDebuggerConsoleCommand() [1/2]
QScriptDebuggerConsoleCommand::QScriptDebuggerConsoleCommand ()
Definition at line 70 of file qscriptdebuggerconsolecommand.cpp.
     : d_ptr(new QScriptDebuggerConsoleCommandPrivate)
 {
     d_ptr->q_ptr = this;
 }
~QScriptDebuggerConsoleCommand()
QScriptDebuggerConsoleCommand::~QScriptDebuggerConsoleCommand () virtual
Definition at line 76 of file qscriptdebuggerconsolecommand.cpp.
 {
 }
QScriptDebuggerConsoleCommand() [2/2]
QScriptDebuggerConsoleCommand::QScriptDebuggerConsoleCommand (QScriptDebuggerConsoleCommandPrivate & dd) protected
Definition at line 80 of file qscriptdebuggerconsolecommand.cpp.
     : d_ptr(&dd)
 {
     d_ptr->q_ptr = this;
 }
Functions
aliases()
QStringList QScriptDebuggerConsoleCommand::aliases () const virtual
Returns a list of aliases for this command.
Reimplemented in QScriptDebuggerScriptedConsoleCommand.
Definition at line 147 of file qscriptdebuggerconsolecommand.cpp.
Referenced by consoleCommandToScriptValue(), and QScriptDebuggerConsoleCommandManager::findCommand().
 {
     return QStringList();
 }
argumentTypes()
QStringList QScriptDebuggerConsoleCommand::argumentTypes () const virtual
Reimplemented in QScriptDebuggerScriptedConsoleCommand.
Definition at line 152 of file qscriptdebuggerconsolecommand.cpp.
Referenced by QScriptDebuggerConsolePrivate::createJob(), and QScriptCompletionTask::start().
 {
     return QStringList();
 }
createJob()
QScriptDebuggerConsoleCommandJob * QScriptDebuggerConsoleCommand::createJob (const QStringList & arguments, QScriptDebuggerConsole * console, QScriptMessageHandlerInterface * messageHandler, QScriptDebuggerCommandSchedulerInterface * scheduler) pure virtual
Creates a job that will execute this command with the given arguments.
If the command cannot be executed (e.g. because one or more arguments are invalid), a suitable error message should be output to the messageHandler, and 0 should be returned.
Implemented in QScriptDebuggerScriptedConsoleCommand.
Referenced by QScriptDebuggerConsolePrivate::createJob().
group()
QString QScriptDebuggerConsoleCommand::group () const pure virtual
Returns the group that this console command belongs to.
Implemented in QScriptDebuggerScriptedConsoleCommand.
Referenced by QScriptDebuggerConsoleCommandManager::addCommand(), QScriptDebuggerConsoleCommandManager::commands(), QScriptDebuggerConsoleCommandManager::commandsInGroup(), and consoleCommandToScriptValue().
longDescription()
QString QScriptDebuggerConsoleCommand::longDescription () const pure virtual
Returns a detailed description of how to use the command.
Implemented in QScriptDebuggerScriptedConsoleCommand.
Referenced by consoleCommandToScriptValue().
name()
QString QScriptDebuggerConsoleCommand::name () const pure virtual
Returns the name of this console command.
Implemented in QScriptDebuggerScriptedConsoleCommand.
Referenced by QScriptDebuggerConsoleCommandManager::addCommand(), QScriptDebuggerConsoleCommandManager::completions(), consoleCommandToScriptValue(), and QScriptDebuggerConsoleCommandManager::findCommand().
seeAlso()
QStringList QScriptDebuggerConsoleCommand::seeAlso () const virtual
Returns a list of names of commands that may also be of interest to users of this command.
Reimplemented in QScriptDebuggerScriptedConsoleCommand.
Definition at line 139 of file qscriptdebuggerconsolecommand.cpp.
Referenced by consoleCommandToScriptValue().
 {
     return QStringList();
 }
shortDescription()
QString QScriptDebuggerConsoleCommand::shortDescription () const pure virtual
Returns a short (one line) description of the command.
Implemented in QScriptDebuggerScriptedConsoleCommand.
Referenced by consoleCommandToScriptValue().
subCommands()
QStringList QScriptDebuggerConsoleCommand::subCommands () const virtual
Reimplemented in QScriptDebuggerScriptedConsoleCommand.
Definition at line 157 of file qscriptdebuggerconsolecommand.cpp.
Referenced by QScriptCompletionTask::start().
 {
     return QStringList();
 }
Properties
d_ptr
QScopedPointer<QScriptDebuggerConsoleCommandPrivate> QScriptDebuggerConsoleCommand::d_ptr protected
Definition at line 94 of file qscriptdebuggerconsolecommand_p.h.
Referenced by QScriptDebuggerConsoleCommand().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerconsolecommand_p.h
/src/scripttools/debugging/qscriptdebuggerconsolecommand.cpp