Qt 4.8: QFontCache Class Reference
QFontCache Class Reference
#include <qfont_p.h>
Classes
struct Engine
struct Key
Public Types
typedef QMap< Key, Engine > EngineCache
typedef QMap< Key, QFontEngineData * > EngineDataCache
Public Functions
void cleanupPrinterFonts ()
void clear ()
QFontEngine * findEngine (const Key &key)
QFontEngineData * findEngineData (const Key &key) const
void insertEngine (const Key &key, QFontEngine *engine)
void insertEngineData (const Key &key, QFontEngineData *engineData)
QFontCache ()
void removeEngineForFont (const QByteArray &fontName)
~QFontCache ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void cleanup ()
static QFontCache * instance ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
EngineCache engineCache
EngineDataCache engineDataCache
Private Functions
void decreaseCost (uint cost)
void increaseCost (uint cost)
void timerEvent (QTimerEvent *event)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
uint current_timestamp
bool fast
uint max_cost
int timer_id
uint total_cost
Static Private Attributes
static const uint min_cost = 4*1024
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 213 of file qfont_p.h.
Typedefs
EngineCache
typedef QMap<Key,Engine> QFontCache::EngineCache
Definition at line 266 of file qfont_p.h.
EngineDataCache
typedef QMap<Key,QFontEngineData*> QFontCache::EngineDataCache
Definition at line 250 of file qfont_p.h.
Constructors and Destructors
QFontCache()
QFontCache::QFontCache ()
Definition at line 2940 of file qfont.cpp.
     : QObject(), total_cost(0), max_cost(min_cost),
       current_timestamp(0), fast(false), timer_id(-1)
 {
 }
~QFontCache()
QFontCache::~QFontCache ()
Definition at line 2946 of file qfont.cpp.
 {
     clear();
     {
         EngineDataCache::ConstIterator it = engineDataCache.constBegin(),
                                  end = engineDataCache.constEnd();
         while (it != end) {
             if (it.value()->ref == 0)
                 delete it.value();
             else
                 FC_DEBUG("QFontCache::~QFontCache: engineData %p still has refcount %d",
                          it.value(), int(it.value()->ref));
             ++it;
         }
     }
     EngineCache::ConstIterator it = engineCache.constBegin(),
                          end = engineCache.constEnd();
     while (it != end) {
         if (--it.value().data->cache_count == 0) {
             if (it.value().data->ref == 0) {
                 FC_DEBUG("QFontCache::~QFontCache: deleting engine %p key=(%d / %g %g %d %d %d)",
                          it.value().data, it.key().script, it.key().def.pointSize,
                          it.key().def.pixelSize, it.key().def.weight, it.key().def.style,
                          it.key().def.fixedPitch);
                 delete it.value().data;
             } else {
                 FC_DEBUG("QFontCache::~QFontCache: engine = %p still has refcount %d",
                          it.value().data, int(it.value().data->ref));
             }
         }
         ++it;
     }
 }
Functions
cleanup()
void QFontCache::cleanup () static
Definition at line 2927 of file qfont.cpp.
Referenced by QFont::cleanup(), pointSize(), and qt_x11_set_fallback_font_family().
 {
     QThreadStorage<QFontCache *> *cache = 0;
     QT_TRY {
         cache = theFontCache();
     } QT_CATCH (const std::bad_alloc &) {
         // no cache - just ignore
     }
     if (cache && cache->hasLocalData())
         cache->setLocalData(0);
 }
cleanupPrinterFonts()
void QFontCache::cleanupPrinterFonts ()
Definition at line 3123 of file qfont.cpp.
 {
     FC_DEBUG("QFontCache::cleanupPrinterFonts");
     {
         FC_DEBUG("  CLEAN engine data:");
         // clean out all unused engine data
         EngineDataCache::Iterator it = engineDataCache.begin(),
                                  end = engineDataCache.end();
         while (it != end) {
             if (it.key().screen == 0) {
                 ++it;
                 continue;
             }
             if(it.value()->ref != 0) {
                 for(int i = 0; i < QUnicodeTables::ScriptCount; ++i) {
                     if(it.value()->engines[i]) {
                         it.value()->engines[i]->ref.deref();
                         it.value()->engines[i] = 0;
                     }
                 }
                 ++it;
             } else {
                 EngineDataCache::Iterator rem = it++;
                 decreaseCost(sizeof(QFontEngineData));
                 FC_DEBUG("    %p", rem.value());
                 delete rem.value();
                 engineDataCache.erase(rem);
             }
         }
     }
     EngineCache::Iterator it = engineCache.begin(),
                          end = engineCache.end();
     while(it != end) {
         if (it.value().data->ref != 0 || it.key().screen == 0) {
             ++it;
             continue;
         }
         FC_DEBUG("    %p: timestamp %4u hits %2u ref %2d/%2d, type '%s'",
                  it.value().data, it.value().timestamp, it.value().hits,
                  int(it.value().data->ref), it.value().data->cache_count,
                  it.value().data->name());
         if (--it.value().data->cache_count == 0) {
             FC_DEBUG("    DELETE: last occurrence in cache");
             decreaseCost(it.value().data->cache_cost);
             delete it.value().data;
         }
         engineCache.erase(it++);
     }
 }
clear()
void QFontCache::clear ()
Definition at line 2981 of file qfont.cpp.
Referenced by QFontDatabasePrivate::invalidate(), removeEngineForFont(), and ~QFontCache().
 {
     {
         EngineDataCache::Iterator it = engineDataCache.begin(),
                                  end = engineDataCache.end();
         while (it != end) {
             QFontEngineData *data = it.value();
 #if !defined(Q_WS_MAC)
             for (int i = 0; i < QUnicodeTables::ScriptCount; ++i) {
                 if (data->engines[i]) {
                     data->engines[i]->ref.deref();
                     data->engines[i] = 0;
                 }
             }
 #else
             if (data->engine) {
                 data->engine->ref.deref();
                 data->engine = 0;
             }
 #endif
             ++it;
         }
     }
     for (EngineCache::Iterator it = engineCache.begin(), end = engineCache.end();
          it != end; ++it) {
         if (it->data->ref == 0) {
             delete it->data;
             it->data = 0;
         }
     }
     for (EngineCache::Iterator it = engineCache.begin(), end = engineCache.end();
          it != end; ++it) {
         if (it->data && it->data->ref == 0) {
             delete it->data;
             it->data = 0;
         }
     }
     engineCache.clear();
 }
decreaseCost()
void QFontCache::decreaseCost (uint cost) private
Definition at line 3111 of file qfont.cpp.
Referenced by cleanupPrinterFonts(), and timerEvent().
 {
     cost = (cost + 512) / 1024; // cost is stored in kb
     cost = cost > 0 ? cost : 1;
     Q_ASSERT(cost <= total_cost);
     total_cost -= cost;
     FC_DEBUG("  COST: decreased %u kb, total_cost %u kb, max_cost %u kb",
             cost, total_cost, max_cost);
 }
findEngine()
QFontEngine * QFontCache::findEngine (const Key & key)
Definition at line 3054 of file qfont.cpp.
Referenced by QFontDatabase::findFont(), QFontDatabase::load(), QFontEngineMultiFT::loadEngine(), loadSingleEngine(), loadWin(), QFontDatabase::loadXlfd(), and qt_load_font_engine_win().
 {
     EngineCache::Iterator it = engineCache.find(key),
                          end = engineCache.end();
     if (it == end) return 0;
     // found... update the hitcount and timestamp
     it.value().hits++;
     it.value().timestamp = ++current_timestamp;
     FC_DEBUG("QFontCache: found font engine\n"
              "  %p: timestamp %4u hits %3u ref %2d/%2d, type '%s'",
              it.value().data, it.value().timestamp, it.value().hits,
              int(it.value().data->ref), it.value().data->cache_count,
              it.value().data->name());
     return it.value().data;
 }
findEngineData()
QFontEngineData * QFontCache::findEngineData (const Key & key) const
Definition at line 3036 of file qfont.cpp.
Referenced by getEngineData(), QFontDatabase::load(), and registerFont().
 {
     EngineDataCache::ConstIterator it = engineDataCache.find(key),
                                   end = engineDataCache.end();
     if (it == end) return 0;
     // found
     return it.value();
 }
increaseCost()
void QFontCache::increaseCost (uint cost) private
Definition at line 3089 of file qfont.cpp.
Referenced by insertEngine(), and insertEngineData().
 {
     cost = (cost + 512) / 1024; // store cost in kb
     cost = cost > 0 ? cost : 1;
     total_cost += cost;
     FC_DEBUG("  COST: increased %u kb, total_cost %u kb, max_cost %u kb",
             cost, total_cost, max_cost);
     if (total_cost > max_cost) {
         max_cost = total_cost;
         if (timer_id == -1 || ! fast) {
             FC_DEBUG("  TIMER: starting fast timer (%d ms)", fast_timeout);
             if (timer_id != -1) killTimer(timer_id);
             timer_id = startTimer(fast_timeout);
             fast = true;
         }
     }
 }
insertEngine()
void QFontCache::insertEngine (const Key & key, QFontEngine * engine)
Definition at line 3073 of file qfont.cpp.
Referenced by QFontDatabase::load(), QFontEngineMultiFT::loadEngine(), loadSingleEngine(), loadWin(), QFontDatabase::loadXlfd(), and registerFont().
 {
     FC_DEBUG("QFontCache: inserting new engine %p", engine);
     Engine data(engine);
     data.timestamp = ++current_timestamp;
     engineCache.insert(key, data);
     // only increase the cost if this is the first time we insert the engine
     if (engine->cache_count == 0)
         increaseCost(engine->cache_cost);
     ++engine->cache_count;
 }
insertEngineData()
void QFontCache::insertEngineData (const Key & key, QFontEngineData * engineData)
Definition at line 3046 of file qfont.cpp.
Referenced by getEngineData(), QFontDatabase::load(), and registerFont().
 {
     FC_DEBUG("QFontCache: inserting new engine data %p", engineData);
     engineDataCache.insert(key, engineData);
     increaseCost(sizeof(QFontEngineData));
 }
instance()
QFontCache * QFontCache::instance () static
Definition at line 2919 of file qfont.cpp.
Referenced by QFontPrivate::engineForScript(), QFontDatabase::findFont(), getEngineData(), QFontDatabasePrivate::invalidate(), QFontDatabase::load(), QFontEngineMultiFT::loadEngine(), loadSingleEngine(), loadWin(), QFontDatabase::loadXlfd(), qt_load_font_engine_win(), QApplication::qwsProcessEvent(), and registerFont().
 {
     QFontCache *&fontCache = theFontCache()->localData();
     if (!fontCache)
         fontCache = new QFontCache;
     return fontCache;
 }
removeEngineForFont()
void QFontCache::removeEngineForFont (const QByteArray & fontName)
Definition at line 3025 of file qfont.cpp.
Referenced by QApplication::qwsProcessEvent().
 {
     /* This could be optimized but the code becomes much more complex if we want to handle multi
      * font engines and it is probably not worth it. Therefore we just clear the entire font cache.
      */
     Q_UNUSED(_fontName);
     clear();
 }
timerEvent()
void QFontCache::timerEvent (QTimerEvent * event) private virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 3186 of file qfont.cpp.
 {
     FC_DEBUG("QFontCache::timerEvent: performing cache maintenance (timestamp %u)",
               current_timestamp);
     if (total_cost <= max_cost && max_cost <= min_cost) {
         FC_DEBUG("  cache redused sufficiently, stopping timer");
         killTimer(timer_id);
         timer_id = -1;
         fast = false;
         return;
     }
     // go through the cache and count up everything in use
     uint in_use_cost = 0;
     {
         FC_DEBUG("  SWEEP engine data:");
         // make sure the cost of each engine data is at least 1kb
         const uint engine_data_cost =
             sizeof(QFontEngineData) > 1024 ? sizeof(QFontEngineData) : 1024;
         EngineDataCache::ConstIterator it = engineDataCache.constBegin(),
                                       end = engineDataCache.constEnd();
         for (; it != end; ++it) {
 #ifdef QFONTCACHE_DEBUG
             FC_DEBUG("    %p: ref %2d", it.value(), int(it.value()->ref));
 #  if defined(Q_WS_X11) || defined(Q_WS_WIN)
             // print out all engines
             for (int i = 0; i < QUnicodeTables::ScriptCount; ++i) {
                 if (! it.value()->engines[i])
                     continue;
                 FC_DEBUG("      contains %p", it.value()->engines[i]);
             }
 #  endif // Q_WS_X11 || Q_WS_WIN
 #endif // QFONTCACHE_DEBUG
             if (it.value()->ref != 0)
                 in_use_cost += engine_data_cost;
         }
     }
     {
         FC_DEBUG("  SWEEP engine:");
         EngineCache::ConstIterator it = engineCache.constBegin(),
                                   end = engineCache.constEnd();
         for (; it != end; ++it) {
             FC_DEBUG("    %p: timestamp %4u hits %2u ref %2d/%2d, cost %u bytes",
                      it.value().data, it.value().timestamp, it.value().hits,
                      int(it.value().data->ref), it.value().data->cache_count,
                      it.value().data->cache_cost);
             if (it.value().data->ref != 0)
                 in_use_cost += it.value().data->cache_cost / it.value().data->cache_count;
         }
         // attempt to make up for rounding errors
         in_use_cost += engineCache.size();
     }
     in_use_cost = (in_use_cost + 512) / 1024; // cost is stored in kb
     /*
       calculate the new maximum cost for the cache
       NOTE: in_use_cost is *not* correct due to rounding errors in the
       above algorithm.  instead of worrying about getting the
       calculation correct, we are more interested in speed, and use
       in_use_cost as a floor for new_max_cost
     */
     uint new_max_cost = qMax(qMax(max_cost / 2, in_use_cost), min_cost);
     FC_DEBUG("  after sweep, in use %u kb, total %u kb, max %u kb, new max %u kb",
               in_use_cost, total_cost, max_cost, new_max_cost);
     if (new_max_cost == max_cost) {
         if (fast) {
             FC_DEBUG("  cannot shrink cache, slowing timer");
             killTimer(timer_id);
             timer_id = startTimer(slow_timeout);
             fast = false;
         }
         return;
     } else if (! fast) {
         FC_DEBUG("  dropping into passing gear");
         killTimer(timer_id);
         timer_id = startTimer(fast_timeout);
         fast = true;
     }
     max_cost = new_max_cost;
     {
         FC_DEBUG("  CLEAN engine data:");
         // clean out all unused engine data
         EngineDataCache::Iterator it = engineDataCache.begin(),
                                  end = engineDataCache.end();
         while (it != end) {
             if (it.value()->ref != 0) {
                 ++it;
                 continue;
             }
             EngineDataCache::Iterator rem = it++;
             decreaseCost(sizeof(QFontEngineData));
             FC_DEBUG("    %p", rem.value());
             delete rem.value();
             engineDataCache.erase(rem);
         }
     }
     // clean out the engine cache just enough to get below our new max cost
     uint current_cost;
     do {
         current_cost = total_cost;
         EngineCache::Iterator it = engineCache.begin(),
                              end = engineCache.end();
         // determine the oldest and least popular of the unused engines
         uint oldest = ~0u;
         uint least_popular = ~0u;
         for (; it != end; ++it) {
             if (it.value().data->ref != 0)
                 continue;
             if (it.value().timestamp < oldest &&
                  it.value().hits <= least_popular) {
                 oldest = it.value().timestamp;
                 least_popular = it.value().hits;
             }
         }
         FC_DEBUG("    oldest %u least popular %u", oldest, least_popular);
         for (it = engineCache.begin(); it != end; ++it) {
             if (it.value().data->ref == 0 &&
                  it.value().timestamp == oldest &&
                  it.value().hits == least_popular)
                 break;
         }
         if (it != end) {
             FC_DEBUG("    %p: timestamp %4u hits %2u ref %2d/%2d, type '%s'",
                      it.value().data, it.value().timestamp, it.value().hits,
                      int(it.value().data->ref), it.value().data->cache_count,
                      it.value().data->name());
             if (--it.value().data->cache_count == 0) {
                 FC_DEBUG("    DELETE: last occurrence in cache");
                 decreaseCost(it.value().data->cache_cost);
                 delete it.value().data;
             } else {
                 /*
                   this particular font engine is in the cache multiple
                   times...  set current_cost to zero, so that we can
                   keep looping to get rid of all occurrences
                 */
                 current_cost = 0;
             }
             engineCache.erase(it);
         }
     } while (current_cost != total_cost && total_cost > max_cost);
 }
Properties
current_timestamp
uint QFontCache::current_timestamp private
Definition at line 283 of file qfont_p.h.
Referenced by findEngine(), insertEngine(), and timerEvent().
engineCache
EngineCache QFontCache::engineCache
Definition at line 267 of file qfont_p.h.
Referenced by cleanupPrinterFonts(), clear(), findEngine(), insertEngine(), timerEvent(), and ~QFontCache().
engineDataCache
EngineDataCache QFontCache::engineDataCache
Definition at line 251 of file qfont_p.h.
Referenced by cleanupPrinterFonts(), clear(), findEngineData(), insertEngineData(), timerEvent(), and ~QFontCache().
fast
bool QFontCache::fast private
Definition at line 284 of file qfont_p.h.
Referenced by increaseCost(), and timerEvent().
max_cost
uint QFontCache::max_cost private
Definition at line 282 of file qfont_p.h.
Referenced by decreaseCost(), increaseCost(), and timerEvent().
min_cost
const uint QFontCache::min_cost = 4*1024 static private
Definition at line 281 of file qfont_p.h.
Referenced by timerEvent().
timer_id
int QFontCache::timer_id private
Definition at line 285 of file qfont_p.h.
Referenced by increaseCost(), and timerEvent().
total_cost
uint QFontCache::total_cost private
Definition at line 282 of file qfont_p.h.
Referenced by decreaseCost(), increaseCost(), and timerEvent().
The documentation for this class was generated from the following files:
/src/gui/text/qfont_p.h
/src/gui/text/qfont.cpp