Qt 4.8: QTextItem Class Reference
QTextItem Class Reference
The QTextItem class provides all the information required to draw text in a custom paint engine.
#include <qpaintengine.h>
Public Types
enum RenderFlag {
RightToLeft = 0x1, Overline = 0x10, Underline = 0x20, StrikeOut = 0x40,
Dummy = 0xffffffff
}
Public Functions
qreal ascent () const
Corresponds to the ascent of the piece of text that is drawn.
qreal descent () const
Corresponds to the descent of the piece of text that is drawn.
QFont font () const
Returns the font that should be used to draw the text.
RenderFlags renderFlags () const
Returns the render flags used.
QString text () const
Returns the text that should be drawn.
qreal width () const
Specifies the total width of the text to be drawn.
Detailed Description
The QTextItem class provides all the information required to draw text in a custom paint engine.
When you reimplement your own paint engine, you must reimplement QPaintEngine::drawTextItem(), a function that takes a QTextItem as one of its arguments.
Definition at line 68 of file qpaintengine.h.
Enumerations
RenderFlag
enum QTextItem::RenderFlag
RightToLeft Render the text from right to left.
Overline Paint a line above the text.
Underline Paint a line under the text.
StrikeOut Paint a line through the text.
Dummy
Enumerator
RightToLeft
Overline
Underline
StrikeOut
Dummy
Definition at line 70 of file qpaintengine.h.
                     {
         RightToLeft = 0x1,
         Overline = 0x10,
         Underline = 0x20,
         StrikeOut = 0x40,
         Dummy = 0xffffffff
     };
Functions
ascent()
qreal QTextItem::ascent () const
Corresponds to the ascent of the piece of text that is drawn.
Definition at line 104 of file qpaintengine.cpp.
Referenced by QAlphaPaintEngine::drawTextItem(), QPicturePaintEngine::drawTextItem(), QPaintBufferEngine::drawTextItem(), and QTextItemInt::initWithScriptItem().
 {
     const QTextItemInt *ti = static_cast<const QTextItemInt *>(this);
     return ti->ascent.toReal();
 }
descent()
qreal QTextItem::descent () const
Corresponds to the descent of the piece of text that is drawn.
Definition at line 90 of file qpaintengine.cpp.
Referenced by QAlphaPaintEngine::drawTextItem(), QPaintBufferEngine::drawTextItem(), and QTextItemInt::initWithScriptItem().
 {
     const QTextItemInt *ti = static_cast<const QTextItemInt *>(this);
     return ti->descent.toReal();
 }
font()
QFont QTextItem::font () const
Returns the font that should be used to draw the text.
Definition at line 160 of file qpaintengine.cpp.
Referenced by QPicturePaintEngine::drawTextItem(), QVGPaintEngine::drawTextItem(), QSvgPaintEngine::drawTextItem(), QPaintBufferEngine::drawTextItem(), QStaticTextPrivate::get(), QBlittablePixmapData::markRasterOverlay(), QPainterReplayer::process(), and QTextItemInt::QTextItemInt().
 {
     const QTextItemInt *ti = static_cast<const QTextItemInt *>(this);
     return ti->f ? *ti->f : QApplication::font();
 }
renderFlags()
QTextItem::RenderFlags QTextItem::renderFlags () const
Returns the render flags used.
Definition at line 132 of file qpaintengine.cpp.
Referenced by QPicturePaintEngine::drawTextItem(), and QPaintBufferEngine::drawTextItem().
 {
     const QTextItemInt *ti = static_cast<const QTextItemInt *>(this);
     return ti->flags;
 }
text()
QString QTextItem::text () const
Returns the text that should be drawn.
Definition at line 146 of file qpaintengine.cpp.
Referenced by QPaintBuffer::commandDescription(), QDirectFBPaintEngine::drawTextItem(), QPicturePaintEngine::drawTextItem(), QPaintBufferEngine::drawTextItem(), QPainter::drawTextItem(), QBlittablePixmapData::markRasterOverlay(), and QPainterReplayer::process().
 {
     const QTextItemInt *ti = static_cast<const QTextItemInt *>(this);
     return QString(ti->chars, ti->num_chars);
 }
width()
qreal QTextItem::width () const
Specifies the total width of the text to be drawn.
Definition at line 118 of file qpaintengine.cpp.
Referenced by QAlphaPaintEngine::drawTextItem(), QPaintBufferEngine::drawTextItem(), qt_fill_tile(), and glyph_metrics_t::transformed().
 {
     const QTextItemInt *ti = static_cast<const QTextItemInt *>(this);
     return ti->width.toReal();
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine.h
/src/gui/painting/qpaintengine.cpp