Qt 4.8: QMimeDataWrapper Class Reference
QMimeDataWrapper Class Reference
#include <qclipboard_p.h>
Public Functions
QByteArray encodedData (const char *) const
Returns the encoded data of this object in the specified MIME format.
const char * format (int n) const
Returns the (i - 1)-th supported MIME format, or 0.
QMimeDataWrapper ()
Public Functions inherited from QMimeSource
virtual bool provides (const char *) const
Returns true if the object can provide the data in format mimeType; otherwise returns false.
virtual ~QMimeSource ()
Destroys the MIME source.
Public Variables
const QMimeData * data
QList< QByteArray > formats
Detailed Description
Definition at line 64 of file qclipboard_p.h.
Constructors and Destructors
QMimeDataWrapper()
QMimeDataWrapper::QMimeDataWrapper () inline
Definition at line 67 of file qclipboard_p.h.
Referenced by QClipboardPrivate::QClipboardPrivate().
 {}
Functions
encodedData()
QByteArray QMimeDataWrapper::encodedData (const char * format) const virtual
Returns the encoded data of this object in the specified MIME format.
Implements QMimeSource.
Definition at line 670 of file qclipboard.cpp.
Referenced by QMimeDataWrapper().
 {
     if (QLatin1String(format) != QLatin1String("application/x-qt-image")){
         return data->data(QLatin1String(format));
     } else{
         QVariant variant = data->imageData();
         QImage img = qvariant_cast<QImage>(variant);
         QByteArray ba;
         QBuffer buffer(&ba);
         buffer.open(QIODevice::WriteOnly);
         img.save(&buffer, "PNG");
         return ba;
     }
 }
format()
const char * QMimeDataWrapper::format (int n) const virtual
Returns the (i - 1)-th supported MIME format, or 0.
Implements QMimeSource.
Definition at line 658 of file qclipboard.cpp.
Referenced by QMimeDataWrapper().
 {
     if (formats.isEmpty()) {
         QStringList fmts = data->formats();
         for (int i = 0; i < fmts.size(); ++i)
             formats.append(fmts.at(i).toLatin1());
     }
     if (n < 0 || n >= formats.size())
         return 0;
     return formats.at(n).data();
 }
Properties
data
const QMimeData* QMimeDataWrapper::data
Definition at line 73 of file qclipboard_p.h.
formats
QList<QByteArray> QMimeDataWrapper::formats mutable
Definition at line 72 of file qclipboard_p.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qclipboard_p.h
/src/gui/kernel/qclipboard.cpp