Qt 4.8: QEasingCurve Class Reference
QEasingCurve Class Reference
The QEasingCurve class provides easing curves for controlling animation.
#include <qeasingcurve.h>
Public Types
typedef qreal(* EasingFunction) (qreal progress)
This is a typedef for a pointer to a function with the following signature:
enum Type {
Linear, InQuad, OutQuad, InOutQuad,
OutInQuad, InCubic, OutCubic, InOutCubic,
OutInCubic, InQuart, OutQuart, InOutQuart,
OutInQuart, InQuint, OutQuint, InOutQuint,
OutInQuint, InSine, OutSine, InOutSine,
OutInSine, InExpo, OutExpo, InOutExpo,
OutInExpo, InCirc, OutCirc, InOutCirc,
OutInCirc, InElastic, OutElastic, InOutElastic,
OutInElastic, InBack, OutBack, InOutBack,
OutInBack, InBounce, OutBounce, InOutBounce,
OutInBounce, InCurve, OutCurve, SineCurve,
CosineCurve, Custom, NCurveTypes
}
The type of easing curve.
Public Functions
qreal amplitude () const
Returns the amplitude.
EasingFunction customType () const
Returns the function pointer to the custom easing curve.
bool operator!= (const QEasingCurve &other) const
Compare this easing curve with other and returns true if they are not equal.
QEasingCurve & operator= (const QEasingCurve &other)
Copy other.
bool operator== (const QEasingCurve &other) const
Compare this easing curve with other and returns true if they are equal.
qreal overshoot () const
Returns the overshoot.
qreal period () const
Returns the period.
QEasingCurve (Type type=Linear)
Constructs an easing curve of the given type.
QEasingCurve (const QEasingCurve &other)
Construct a copy of other.
void setAmplitude (qreal amplitude)
Sets the amplitude to amplitude.
void setCustomType (EasingFunction func)
Sets a custom easing curve that is defined by the user in the function func.
void setOvershoot (qreal overshoot)
Sets the overshoot to overshoot.
void setPeriod (qreal period)
Sets the period to period.
void setType (Type type)
Sets the type of the easing curve to type.
Type type () const
Returns the type of the easing curve.
qreal valueForProgress (qreal progress) const
Return the effective progress for the easing curve at progress.
~QEasingCurve ()
Destructor.
Properties
QEasingCurvePrivate * d_ptr
Friends
Q_CORE_EXPORT QDebug operator<< (QDebug debug, const QEasingCurve &item)
Q_CORE_EXPORT QDataStream & operator<< (QDataStream &, const QEasingCurve &)
Writes the given easing curve to the given stream and returns a reference to the stream.
Q_CORE_EXPORT QDataStream & operator>> (QDataStream &, QEasingCurve &)
Detailed Description
The QEasingCurve class provides easing curves for controlling animation.
Since
4.6
Easing curves describe a function that controls how the speed of the interpolation between 0 and 1 should be. Easing curves allow transitions from one value to another to appear more natural than a simple constant speed would allow. The QEasingCurve class is usually used in conjunction with the QVariantAnimation and QPropertyAnimation classes but can be used on its own. It is usually used to accelerate the interpolation from zero velocity (ease in) or decelerate to zero velocity (ease out). Ease in and ease out can also be combined in the same easing curve.
To calculate the speed of the interpolation, the easing curve provides the function valueForProgress(), where the progress argument specifies the progress of the interpolation: 0 is the start value of the interpolation, 1 is the end value of the interpolation. The returned value is the effective progress of the interpolation. If the returned value is the same as the input value for all input values the easing curve is a linear curve. This is the default behaviour.
For example,
QEasingCurve easing(QEasingCurve::InOutQuad);
for(qreal t = 0.0; t < 1.0; t+=0.1)
    qWarning() << "Effective progress" << t << " is
               << easing.valueForProgress(t);
will print the effective progress of the interpolation between 0 and 1.
When using a QPropertyAnimation, the associated easing curve will be used to control the progress of the interpolation between startValue and endValue:
QPropertyAnimation animation;
animation.setStartValue(0);
animation.setEndValue(1000);
animation.setDuration(1000);
animation.setEasingCurve(QEasingCurve::InOutQuad);
The ability to set an amplitude, overshoot, or period depends on the QEasingCurve type. Amplitude access is available to curves that behave as springs such as elastic and bounce curves. Changing the amplitude changes the height of the curve. Period access is only available to elastic curves and setting a higher period slows the rate of bounce. Only curves that have "boomerang" behaviors such as the InBack, OutBack, InOutBack, and OutInBack have overshoot settings. These curves will interpolate beyond the end points and return to the end point, acting similar to a boomerang.
The Easing Curves Example contains samples of QEasingCurve types and lets you change the curve settings.
Definition at line 55 of file qeasingcurve.h.
Typedefs
EasingFunction
QEasingCurve::EasingFunction
This is a typedef for a pointer to a function with the following signature:
qreal myEasingFunction(qreal progress);
Definition at line 96 of file qeasingcurve.h.
Enumerations
Type
enum QEasingCurve::Type
The type of easing curve.
Linear
                Easing curve for a linear (t) function:
                velocity is constant.
InQuad
                Easing curve for a quadratic (t^2) function:
                accelerating from zero velocity.
OutQuad
                Easing curve for a quadratic (t^2) function:
                decelerating to zero velocity.
InOutQuad
                Easing curve for a quadratic (t^2) function:
                acceleration until halfway, then deceleration.
OutInQuad
                Easing curve for a quadratic (t^2) function:
                deceleration until halfway, then acceleration.
InCubic
                Easing curve for a cubic (t^3) function:
                accelerating from zero velocity.
OutCubic
                Easing curve for a cubic (t^3) function:
                decelerating to zero velocity.
InOutCubic
                Easing curve for a cubic (t^3) function:
                acceleration until halfway, then deceleration.
OutInCubic
                Easing curve for a cubic (t^3) function:
                deceleration until halfway, then acceleration.
InQuart
                Easing curve for a quartic (t^4) function:
                accelerating from zero velocity.
OutQuart
                Easing curve for a quartic (t^4) function:
                decelerating to zero velocity.
InOutQuart
                Easing curve for a quartic (t^4) function:
                acceleration until halfway, then deceleration.
OutInQuart
                Easing curve for a quartic (t^4) function:
                deceleration until halfway, then acceleration.
InQuint
                Easing curve for a quintic (t^5) easing
                in: accelerating from zero velocity.
OutQuint
                Easing curve for a quintic (t^5) function:
                decelerating to zero velocity.
InOutQuint
                Easing curve for a quintic (t^5) function:
                acceleration until halfway, then deceleration.
OutInQuint
                Easing curve for a quintic (t^5) function:
                deceleration until halfway, then acceleration.
InSine
                Easing curve for a sinusoidal (sin(t)) function:
                accelerating from zero velocity.
OutSine
                Easing curve for a sinusoidal (sin(t)) function:
                decelerating from zero velocity.
InOutSine
                Easing curve for a sinusoidal (sin(t)) function:
                acceleration until halfway, then deceleration.
OutInSine
                Easing curve for a sinusoidal (sin(t)) function:
                deceleration until halfway, then acceleration.
InExpo
                Easing curve for an exponential (2^t) function:
                accelerating from zero velocity.
OutExpo
                Easing curve for an exponential (2^t) function:
                decelerating from zero velocity.
InOutExpo
                Easing curve for an exponential (2^t) function:
                acceleration until halfway, then deceleration.
OutInExpo
                Easing curve for an exponential (2^t) function:
                deceleration until halfway, then acceleration.
InCirc
                Easing curve for a circular (sqrt(1-t^2)) function:
                accelerating from zero velocity.
OutCirc
                Easing curve for a circular (sqrt(1-t^2)) function:
                decelerating from zero velocity.
InOutCirc
                Easing curve for a circular (sqrt(1-t^2)) function:
                acceleration until halfway, then deceleration.
OutInCirc
                Easing curve for a circular (sqrt(1-t^2)) function:
                deceleration until halfway, then acceleration.
InElastic
                Easing curve for an elastic
                (exponentially decaying sine wave) function:
                accelerating from zero velocity.  The peak amplitude
                can be set with the \e amplitude parameter, and the
                period of decay by the \e period parameter.
OutElastic
                Easing curve for an elastic
                (exponentially decaying sine wave) function:
                decelerating from zero velocity.  The peak amplitude
                can be set with the \e amplitude parameter, and the
                period of decay by the \e period parameter.
InOutElastic
                Easing curve for an elastic
                (exponentially decaying sine wave) function:
                acceleration until halfway, then deceleration.
OutInElastic
                Easing curve for an elastic
                (exponentially decaying sine wave) function:
                deceleration until halfway, then acceleration.
InBack
                Easing curve for a back (overshooting
                cubic function: (s+1)*t^3 - s*t^2) easing in:
                accelerating from zero velocity.
OutBack
                Easing curve for a back (overshooting
                cubic function: (s+1)*t^3 - s*t^2) easing out:
                decelerating to zero velocity.
InOutBack
                Easing curve for a back (overshooting
                cubic function: (s+1)*t^3 - s*t^2) easing in/out:
                acceleration until halfway, then deceleration.
OutInBack
                Easing curve for a back (overshooting
                cubic easing: (s+1)*t^3 - s*t^2) easing out/in:
                deceleration until halfway, then acceleration.
InBounce
                Easing curve for a bounce (exponentially
                decaying parabolic bounce) function: accelerating
                from zero velocity.
OutBounce
                Easing curve for a bounce (exponentially
                decaying parabolic bounce) function: decelerating
                from zero velocity.
InOutBounce
                Easing curve for a bounce (exponentially
                decaying parabolic bounce) function easing in/out:
                acceleration until halfway, then deceleration.
OutInBounce
                Easing curve for a bounce (exponentially
                decaying parabolic bounce) function easing out/in:
                deceleration until halfway, then acceleration.
InCurve
OutCurve
SineCurve
CosineCurve
Custom This is returned if the user specified a custom curve type with setCustomType(). Note that you cannot call setType() with this value, but type() can return it.
NCurveTypes
Enumerator
Linear
InQuad
OutQuad
InOutQuad
OutInQuad
InCubic
OutCubic
InOutCubic
OutInCubic
InQuart
OutQuart
InOutQuart
OutInQuart
InQuint
OutQuint
InOutQuint
OutInQuint
InSine
OutSine
InOutSine
OutInSine
InExpo
OutExpo
InOutExpo
OutInExpo
InCirc
OutCirc
InOutCirc
OutInCirc
InElastic
OutElastic
InOutElastic
OutInElastic
InBack
OutBack
InOutBack
OutInBack
InBounce
OutBounce
InOutBounce
OutInBounce
InCurve
OutCurve
SineCurve
CosineCurve
Custom
NCurveTypes
Definition at line 60 of file qeasingcurve.h.
               {
         Linear,
         InQuad, OutQuad, InOutQuad, OutInQuad,
         InCubic, OutCubic, InOutCubic, OutInCubic,
         InQuart, OutQuart, InOutQuart, OutInQuart,
         InQuint, OutQuint, InOutQuint, OutInQuint,
         InSine, OutSine, InOutSine, OutInSine,
         InExpo, OutExpo, InOutExpo, OutInExpo,
         InCirc, OutCirc, InOutCirc, OutInCirc,
         InElastic, OutElastic, InOutElastic, OutInElastic,
         InBack, OutBack, InOutBack, OutInBack,
         InBounce, OutBounce, InOutBounce, OutInBounce,
         InCurve, OutCurve, SineCurve, CosineCurve,
         Custom, NCurveTypes
     };
Constructors and Destructors
QEasingCurve() [1/2]
QEasingCurve::QEasingCurve (Type type = Linear)
Constructs an easing curve of the given type.
Definition at line 615 of file qeasingcurve.cpp.
     : d_ptr(new QEasingCurvePrivate)
 {
     setType(type);
 }
QEasingCurve() [2/2]
QEasingCurve::QEasingCurve (const QEasingCurve & other)
Construct a copy of other.
Definition at line 624 of file qeasingcurve.cpp.
     : d_ptr(new QEasingCurvePrivate)
 {
     // ### non-atomic, requires malloc on shallow copy
     *d_ptr = *other.d_ptr;
     if (other.d_ptr->config)
         d_ptr->config = other.d_ptr->config->copy();
 }
~QEasingCurve()
QEasingCurve::~QEasingCurve ()
Destructor.
Definition at line 637 of file qeasingcurve.cpp.
 {
     delete d_ptr;
 }
Functions
amplitude()
qreal QEasingCurve::amplitude () const
Returns the amplitude.
This is not applicable for all curve types. It is only applicable for bounce and elastic curves (curves of type() QEasingCurve::InBounce, QEasingCurve::OutBounce, QEasingCurve::InOutBounce, QEasingCurve::OutInBounce, QEasingCurve::InElastic, QEasingCurve::OutElastic, QEasingCurve::InOutElastic or QEasingCurve::OutInElastic).
Definition at line 701 of file qeasingcurve.cpp.
Referenced by operator==(), setAmplitude(), and QDeclarativeEasingValueType::setValue().
 {
     return d_ptr->config ? d_ptr->config->_a : qreal(1.0);
 }
customType()
QEasingCurve::EasingFunction QEasingCurve::customType () const
Returns the function pointer to the custom easing curve.
If type() does not return QEasingCurve::Custom, this function will return 0.
Definition at line 847 of file qeasingcurve.cpp.
 {
     return d_ptr->type == Custom ? d_ptr->func : 0;
 }
operator!=()
bool QEasingCurve::operator!= (const QEasingCurve & other) const inline
Compare this easing curve with other and returns true if they are not equal.
It will also compare the properties of a curve.
See also
operator==()
Definition at line 82 of file qeasingcurve.h.
     { return !(this->operator==(other)); }
operator=()
QEasingCurve & QEasingCurve::operator= (const QEasingCurve & other)
Copy other.
Definition at line 645 of file qeasingcurve.cpp.
 {
     // ### non-atomic, requires malloc on shallow copy
     if (d_ptr->config) {
         delete d_ptr->config;
         d_ptr->config = 0;
     }
     *d_ptr = *other.d_ptr;
     if (other.d_ptr->config)
         d_ptr->config = other.d_ptr->config->copy();
     return *this;
 }
operator==()
bool QEasingCurve::operator== (const QEasingCurve & other) const
Compare this easing curve with other and returns true if they are equal.
It will also compare the properties of a curve.
Definition at line 664 of file qeasingcurve.cpp.
 {
     bool res = d_ptr->func == other.d_ptr->func
             && d_ptr->type == other.d_ptr->type;
     if (res) {
         if (d_ptr->config && other.d_ptr->config) {
         // catch the config content
             res = d_ptr->config->operator==(*(other.d_ptr->config));
         } else if (d_ptr->config || other.d_ptr->config) {
         // one one has a config object, which could contain default values
             res = qFuzzyCompare(amplitude(), other.amplitude()) &&
                   qFuzzyCompare(period(), other.period()) &&
                   qFuzzyCompare(overshoot(), other.overshoot());
         }
     }
     return res;
 }
overshoot()
qreal QEasingCurve::overshoot () const
Returns the overshoot.
This is not applicable for all curve types. It is only applicable if type() is QEasingCurve::InBack, QEasingCurve::OutBack, QEasingCurve::InOutBack or QEasingCurve::OutInBack.
Definition at line 749 of file qeasingcurve.cpp.
Referenced by operator==(), setOvershoot(), QEasingCurvePrivate::setType_helper(), and QDeclarativeEasingValueType::setValue().
 {
     return d_ptr->config ? d_ptr->config->_o : qreal(1.70158) ;
 }
period()
qreal QEasingCurve::period () const
Returns the period.
This is not applicable for all curve types. It is only applicable if type() is QEasingCurve::InElastic, QEasingCurve::OutElastic, QEasingCurve::InOutElastic or QEasingCurve::OutInElastic.
Definition at line 725 of file qeasingcurve.cpp.
Referenced by operator==(), setPeriod(), QEasingCurvePrivate::setType_helper(), and QDeclarativeEasingValueType::setValue().
 {
     return d_ptr->config ? d_ptr->config->_p : qreal(0.3);
 }
setAmplitude()
void QEasingCurve::setAmplitude (qreal amplitude)
Sets the amplitude to amplitude.
This will set the amplitude of the bounce or the amplitude of the elastic "spring" effect. The higher the number, the higher the amplitude.
See also
amplitude()
Definition at line 713 of file qeasingcurve.cpp.
Referenced by QDeclarativeEasingValueType::setAmplitude().
 {
     if (!d_ptr->config)
         d_ptr->config = curveToFunctionObject(d_ptr->type);
     d_ptr->config->_a = amplitude;
 }
setCustomType()
void QEasingCurve::setCustomType (EasingFunction func)
Sets a custom easing curve that is defined by the user in the function func.
The signature of the function is qreal myEasingFunction(qreal progress), where progress and the return value is considered to be normalized between 0 and 1. (In some cases the return value can be outside that range) After calling this function type() will return QEasingCurve::Custom. func cannot be zero.
See also
customType()
valueForProgress()
Definition at line 832 of file qeasingcurve.cpp.
 {
     if (!func) {
         qWarning("Function pointer must not be null");
         return;
     }
     d_ptr->func = func;
     d_ptr->setType_helper(Custom);
 }
setOvershoot()
void QEasingCurve::setOvershoot (qreal overshoot)
Sets the overshoot to overshoot.
0 produces no overshoot, and the default value of 1.70158 produces an overshoot of 10 percent.
See also
overshoot()
Definition at line 761 of file qeasingcurve.cpp.
Referenced by QDeclarativeEasingValueType::setOvershoot().
 {
     if (!d_ptr->config)
         d_ptr->config = curveToFunctionObject(d_ptr->type);
     d_ptr->config->_o = overshoot;
 }
setPeriod()
void QEasingCurve::setPeriod (qreal period)
Sets the period to period.
Setting a small period value will give a high frequency of the curve. A large period will give it a small frequency.
See also
period()
Definition at line 737 of file qeasingcurve.cpp.
Referenced by QDeclarativeEasingValueType::setPeriod().
 {
     if (!d_ptr->config)
         d_ptr->config = curveToFunctionObject(d_ptr->type);
     d_ptr->config->_p = period;
 }
setType()
void QEasingCurve::setType (Type type)
Sets the type of the easing curve to type.
Definition at line 809 of file qeasingcurve.cpp.
Referenced by operator>>(), QEasingCurve(), and QDeclarativeEasingValueType::setType().
 {
     if (d_ptr->type == type)
         return;
     if (type < Linear || type >= NCurveTypes - 1) {
         qWarning("QEasingCurve: Invalid curve type %d", type);
         return;
     }
     d_ptr->setType_helper(type);
 }
type()
QEasingCurve::Type QEasingCurve::type () const
Returns the type of the easing curve.
Definition at line 771 of file qeasingcurve.cpp.
Referenced by operator>>(), QEasingCurvePrivate::setType_helper(), QDeclarativeEasingValueType::setValue(), and QDeclarativeTimeLinePrivate::value().
 {
     return d_ptr->type;
 }
valueForProgress()
qreal QEasingCurve::valueForProgress (qreal progress) const
Return the effective progress for the easing curve at progress.
While progress must be between 0 and 1, the returned effective progress can be outside those bounds. For instance, QEasingCurve::InBack will return negative values in the beginning of the function.
Definition at line 858 of file qeasingcurve.cpp.
Referenced by QVariantAnimationPrivate::recalculateCurrentInterval(), and QDeclarativeTimeLinePrivate::value().
 {
     progress = qBound<qreal>(0, progress, 1);
     if (d_ptr->func)
         return d_ptr->func(progress);
     else if (d_ptr->config)
         return d_ptr->config->value(progress);
     else
         return progress;
 }
Friends and Related Functions
operator<< [1/2]
Q_CORE_EXPORT QDebug operator<< (QDebug debug, const QEasingCurve & item) friend
Definition at line 870 of file qeasingcurve.cpp.
 {
     debug << "type:" << item.d_ptr->type
           << "func:" << item.d_ptr->func;
     if (item.d_ptr->config) {
         debug << QString::fromAscii("period:%1").arg(item.d_ptr->config->_p, 0, 'f', 20)
               << QString::fromAscii("amp:%1").arg(item.d_ptr->config->_a, 0, 'f', 20)
               << QString::fromAscii("overshoot:%1").arg(item.d_ptr->config->_o, 0, 'f', 20);
     }
     return debug;
 }
operator<< [2/2]
QDataStream & operator<< (QDataStream & stream, const QEasingCurve & easing) friend
Writes the given easing curve to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 897 of file qeasingcurve.cpp.
 {
     stream << quint8(easing.d_ptr->type);
     stream << quint64(quintptr(easing.d_ptr->func));
     bool hasConfig = easing.d_ptr->config;
     stream << hasConfig;
     if (hasConfig) {
         stream << easing.d_ptr->config->_p;
         stream << easing.d_ptr->config->_a;
         stream << easing.d_ptr->config->_o;
     }
     return stream;
 }
operator>>
Q_CORE_EXPORT QDataStream& operator>> (QDataStream & , QEasingCurve &) friend
Definition at line 925 of file qeasingcurve.cpp.
 {
     QEasingCurve::Type type;
     quint8 int_type;
     stream >> int_type;
     type = static_cast<QEasingCurve::Type>(int_type);
     easing.setType(type);
     quint64 ptr_func;
     stream >> ptr_func;
     easing.d_ptr->func = QEasingCurve::EasingFunction(quintptr(ptr_func));
     bool hasConfig;
     stream >> hasConfig;
     if (hasConfig) {
         QEasingCurveFunction *config = curveToFunctionObject(type);
         stream >> config->_p;
         stream >> config->_a;
         stream >> config->_o;
         easing.d_ptr->config = config;
     }
     return stream;
 }
Properties
d_ptr
QEasingCurvePrivate* QEasingCurve::d_ptr private
Definition at line 102 of file qeasingcurve.h.
Referenced by amplitude(), customType(), operator<<(), operator=(), operator==(), operator>>(), overshoot(), period(), QEasingCurve(), setAmplitude(), setCustomType(), setOvershoot(), setPeriod(), setType(), type(), valueForProgress(), and ~QEasingCurve().
The documentation for this class was generated from the following files:
/src/corelib/tools/qeasingcurve.h
/src/corelib/tools/qeasingcurve.cpp