Qt 4.8: QFastMutex Class Reference
QFastMutex Class Reference
Public Functions
void lock ()
QFastMutex ()
bool tryLock ()
void unlock ()
Properties
QAtomicInt contenders
QSemaphore semaphore
Detailed Description
Definition at line 58 of file qregion_qws.cpp.
Constructors and Destructors
QFastMutex()
QFastMutex::QFastMutex () inline
Definition at line 63 of file qregion_qws.cpp.
         : contenders(0), semaphore(0)
     { }
Functions
lock()
void QFastMutex::lock () inline
Definition at line 66 of file qregion_qws.cpp.
Referenced by qt_allocRegionMemory(), and qt_freeRegionMemory().
     {
         if (contenders.fetchAndAddAcquire(1) != 0) {
             semaphore.acquire();
             contenders.deref();
         }
     }
tryLock()
bool QFastMutex::tryLock () inline
Definition at line 73 of file qregion_qws.cpp.
     {
         return contenders.testAndSetAcquire(0, 1);
     }
unlock()
void QFastMutex::unlock () inline
Definition at line 77 of file qregion_qws.cpp.
Referenced by qt_allocRegionMemory(), and qt_freeRegionMemory().
     {
         if (!contenders.testAndSetRelease(1, 0))
             semaphore.release();
     }
Properties
contenders
QAtomicInt QFastMutex::contenders private
Definition at line 60 of file qregion_qws.cpp.
semaphore
QSemaphore QFastMutex::semaphore private
Definition at line 61 of file qregion_qws.cpp.
The documentation for this class was generated from the following file:
/src/gui/painting/qregion_qws.cpp