Qt 4.8: QTimerInfoList Class Reference
QTimerInfoList Class Reference
#include <qeventdispatcher_unix_p.h>
Public Functions
int activateTimers ()
QTimerInfoList ()
QList< QPair< int, int > > registeredTimers (QObject *object) const
void registerTimer (int timerId, int interval, QObject *object)
void repairTimersIfNeeded ()
void timerInsert (QTimerInfo *)
void timerRepair (const timeval &)
bool timerWait (timeval &)
bool unregisterTimer (int timerId)
bool unregisterTimers (QObject *object)
timeval updateCurrentTime ()
Public Functions inherited from QList< QTimerInfo *>
void append (const QTimerInfo * &t)
Inserts value at the end of the list.
void append (const QList< QTimerInfo * > &t)
Appends the items of the value list to this list.
const QTimerInfo * & at (int i) const
Returns the item at index position i in the list.
QTimerInfo * & back ()
This function is provided for STL compatibility.
const QTimerInfo * & back () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator begin ()
Returns an STL-style iterator pointing to the first item in the list.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void clear ()
Removes all items from the list.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the list.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the list.
QBool contains (const QTimerInfo * &t) const
Returns true if the list contains an occurrence of value; otherwise returns false.
int count (const QTimerInfo * &t) const
Returns the number of occurrences of value in the list.
int count () const
Returns the number of items in the list.
void detach ()
void detachShared ()
This prevents needless mallocs, and makes QList more exception safe in case of cleanup work done in destructors on empty lists.
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the list.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool endsWith (const QTimerInfo * &t) const
Returns true if this list is not empty and its last item is equal to value; otherwise returns false.
iterator erase (iterator pos)
Removes the item associated with the iterator pos from the list, and returns an iterator to the next item in the list (which may be end()).
iterator erase (iterator first, iterator last)
Removes all the items from begin up to (but not including) end.
QTimerInfo * & first ()
Returns a reference to the first item in the list.
const QTimerInfo * & first () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QTimerInfo * & front ()
This function is provided for STL compatibility.
const QTimerInfo * & front () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int indexOf (const QTimerInfo * &t, int from=0) const
Returns the index position of the first occurrence of value in the list, searching forward from index position from.
void insert (int i, const QTimerInfo * &t)
Inserts value at index position i in the list.
iterator insert (iterator before, const QTimerInfo * &t)
Inserts value in front of the item pointed to by the iterator before.
bool isDetached () const
bool isEmpty () const
Returns true if the list contains no items; otherwise returns false.
bool isSharedWith (const QList< QTimerInfo * > &other) const
QTimerInfo * & last ()
Returns a reference to the last item in the list.
const QTimerInfo * & last () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int lastIndexOf (const QTimerInfo * &t, int from=-1) const
Returns the index position of the last occurrence of value in the list, searching backward from index position from.
int length () const
This function is identical to count().
QList< QTimerInfo * > mid (int pos, int length=-1) const
Returns a list whose elements are copied from this list, starting at position pos.
void move (int from, int to)
Moves the item at index position from to index position to.
bool operator!= (const QList< QTimerInfo * > &l) const
Returns true if other is not equal to this list; otherwise returns false.
QList< QTimerInfo * > operator+ (const QList< QTimerInfo * > &l) const
Returns a list that contains all the items in this list followed by all the items in the other list.
QList< QTimerInfo * > & operator+= (const QList< QTimerInfo * > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< QTimerInfo * > & operator+= (const QTimerInfo * &t)
Appends value to the list.
QList< QTimerInfo * > & operator<< (const QList< QTimerInfo * > &l)
Appends the items of the other list to this list and returns a reference to this list.
QList< QTimerInfo * > & operator<< (const QTimerInfo * &t)
Appends value to the list.
QList< QTimerInfo * > & operator= (const QList< QTimerInfo * > &l)
Assigns other to this list and returns a reference to this list.
bool operator== (const QList< QTimerInfo * > &l) const
Returns true if other is equal to this list; otherwise returns false.
const QTimerInfo * & operator[] (int i) const
Same as at().
QTimerInfo * & operator[] (int i)
Returns the item at index position i as a modifiable reference.
void pop_back ()
This function is provided for STL compatibility.
void pop_front ()
This function is provided for STL compatibility.
void prepend (const QTimerInfo * &t)
Inserts value at the beginning of the list.
void push_back (const QTimerInfo * &t)
This function is provided for STL compatibility.
void push_front (const QTimerInfo * &t)
This function is provided for STL compatibility.
QList ()
Constructs an empty list.
QList (const QList< QTimerInfo * > &l)
Constructs a copy of other.
int removeAll (const QTimerInfo * &t)
Removes all occurrences of value in the list and returns the number of entries removed.
void removeAt (int i)
Removes the item at index position i.
void removeFirst ()
Removes the first item in the list.
void removeLast ()
Removes the last item in the list.
bool removeOne (const QTimerInfo * &t)
Removes the first occurrence of value in the list and returns true on success; otherwise returns false.
void replace (int i, const QTimerInfo * &t)
Replaces the item at index position i with value.
void reserve (int size)
Reserve space for alloc elements.
void setSharable (bool sharable)
int size () const
Returns the number of items in the list.
bool startsWith (const QTimerInfo * &t) const
Returns true if this list is not empty and its first item is equal to value; otherwise returns false.
void swap (QList< QTimerInfo * > &other)
Swaps list other with this list.
void swap (int i, int j)
Exchange the item at index position i with the item at index position j.
QTimerInfo * takeAt (int i)
Removes the item at index position i and returns it.
QTimerInfo * takeFirst ()
Removes the first item in the list and returns it.
QTimerInfo * takeLast ()
Removes the last item in the list and returns it.
QSet< QTimerInfo * > toSet () const
Returns a QSet object with the data contained in this QList.
std::list< QTimerInfo * > toStdList () const
Returns a std::list object with the data contained in this QList.
QVector< QTimerInfo * > toVector () const
Returns a QVector object with the data contained in this QList.
QTimerInfo * value (int i) const
Returns the value at index position i in the list.
QTimerInfo * value (int i, const QTimerInfo * &defaultValue) const
If the index i is out of bounds, the function returns defaultValue.
~QList ()
Destroys the list.
Public Variables
timeval currentTime
Public Variables inherited from QList< QTimerInfo *>
QListData::Data * d
QListData p
Properties
QTimerInfo * firstTimerInfo
Additional Inherited Members
Public Types inherited from QList< QTimerInfo *>
typedef const value_type * const_pointer
Typedef for const T *.
typedef const value_type & const_reference
Typedef for const T &.
typedef const_iterator ConstIterator
Qt-style synonym for QList::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QList::iterator.
typedef value_type * pointer
Typedef for T *.
typedef value_type & reference
Typedef for T &.
typedef int size_type
Typedef for int.
typedef QTimerInfo * value_type
Typedef for T.
Static Public Functions inherited from QList< QTimerInfo *>
static QList< QTimerInfo * > fromSet (const QSet< QTimerInfo * > &set)
Returns a QList object with the data contained in set.
static QList< QTimerInfo * > fromStdList (const std::list< QTimerInfo * > &list)
Returns a QList object with the data contained in list.
static QList< QTimerInfo * > fromVector (const QVector< QTimerInfo * > &vector)
Returns a QList object with the data contained in vector.
Related Functions inherited from QList< QTimerInfo *>
QDataStream & operator<< (QDataStream &out, const QList< QTimerInfo * > &list)
Writes the list list to stream out.
QDataStream & operator>> (QDataStream &in, QList< QTimerInfo * > &list)
Reads a list from stream in into list.
Detailed Description
Definition at line 81 of file qeventdispatcher_unix_p.h.
Constructors and Destructors
QTimerInfoList()
QTimerInfoList::QTimerInfoList ()
Definition at line 328 of file qeventdispatcher_unix.cpp.
 {
 #if (_POSIX_MONOTONIC_CLOCK-0 <= 0) && !defined(Q_OS_MAC) && !defined(Q_OS_NACL)
     if (!QElapsedTimer::isMonotonic()) {
         // not using monotonic timers, initialize the timeChanged() machinery
         previousTime = qt_gettime();
         tms unused;
         previousTicks = times(&unused);
         ticksPerSecond = sysconf(_SC_CLK_TCK);
         msPerTick = 1000/ticksPerSecond;
     } else {
         // detected monotonic timers
         previousTime.tv_sec = previousTime.tv_usec = 0;
         previousTicks = 0;
         ticksPerSecond = 0;
         msPerTick = 0;
     }
 #endif
     firstTimerInfo = 0;
 }
Functions
activateTimers()
int QTimerInfoList::activateTimers ()
Definition at line 565 of file qeventdispatcher_unix.cpp.
 {
     if (qt_disable_lowpriority_timers || isEmpty())
         return 0; // nothing to do
     int n_act = 0, maxCount = 0;
     firstTimerInfo = 0;
     timeval currentTime = updateCurrentTime();
     repairTimersIfNeeded();
     // Find out how many timer have expired
     for (QTimerInfoList::const_iterator it = constBegin(); it != constEnd(); ++it) {
         if (currentTime < (*it)->timeout)
             break;
         maxCount++;
     }
     //fire the timers.
     while (maxCount--) {
         if (isEmpty())
             break;
         QTimerInfo *currentTimerInfo = first();
         if (currentTime < currentTimerInfo->timeout)
             break; // no timer has expired
         if (!firstTimerInfo) {
             firstTimerInfo = currentTimerInfo;
         } else if (firstTimerInfo == currentTimerInfo) {
             // avoid sending the same timer multiple times
             break;
         } else if (currentTimerInfo->interval <  firstTimerInfo->interval
                    || currentTimerInfo->interval == firstTimerInfo->interval) {
             firstTimerInfo = currentTimerInfo;
         }
         // remove from list
         removeFirst();
         // determine next timeout time
         currentTimerInfo->timeout += currentTimerInfo->interval;
         if (currentTimerInfo->timeout < currentTime)
             currentTimerInfo->timeout = currentTime + currentTimerInfo->interval;
         // reinsert timer
         timerInsert(currentTimerInfo);
         if (currentTimerInfo->interval.tv_usec > 0 || currentTimerInfo->interval.tv_sec > 0)
             n_act++;
         if (!currentTimerInfo->activateRef) {
             // send event, but don't allow it to recurse
             currentTimerInfo->activateRef = &currentTimerInfo;
             QTimerEvent e(currentTimerInfo->id);
             QCoreApplication::sendEvent(currentTimerInfo->obj, &e);
             if (currentTimerInfo)
                 currentTimerInfo->activateRef = 0;
         }
     }
     firstTimerInfo = 0;
     return n_act;
 }
registeredTimers()
QList< QPair< int, int > > QTimerInfoList::registeredTimers (QObject * object) const
Definition at line 551 of file qeventdispatcher_unix.cpp.
 {
     QList<QPair<int, int> > list;
     for (int i = 0; i < count(); ++i) {
         register const QTimerInfo * const t = at(i);
         if (t->obj == object)
             list << QPair<int, int>(t->id, t->interval.tv_sec * 1000 + t->interval.tv_usec / 1000);
     }
     return list;
 }
registerTimer()
void QTimerInfoList::registerTimer (int timerId, int interval, QObject * object)
Definition at line 487 of file qeventdispatcher_unix.cpp.
 {
     QTimerInfo *t = new QTimerInfo;
     t->id = timerId;
     t->interval.tv_sec  = interval / 1000;
     t->interval.tv_usec = (interval % 1000) * 1000;
     t->timeout = updateCurrentTime() + t->interval;
     t->obj = object;
     t->activateRef = 0;
     timerInsert(t);
 }
repairTimersIfNeeded()
void QTimerInfoList::repairTimersIfNeeded ()
Definition at line 422 of file qeventdispatcher_unix.cpp.
Referenced by updateCurrentTime().
 {
 }
timerInsert()
void QTimerInfoList::timerInsert (QTimerInfo * ti)
Definition at line 431 of file qeventdispatcher_unix.cpp.
 {
     int index = size();
     while (index--) {
         register const QTimerInfo * const t = at(index);
         if (!(ti->timeout < t->timeout))
             break;
     }
     insert(index+1, ti);
 }
timerRepair()
void QTimerInfoList::timerRepair (const timeval & diff)
Definition at line 445 of file qeventdispatcher_unix.cpp.
 {
     // repair all timers
     for (int i = 0; i < size(); ++i) {
         register QTimerInfo *t = at(i);
         t->timeout = t->timeout + diff;
     }
 }
timerWait()
bool QTimerInfoList::timerWait (timeval & tm)
Definition at line 458 of file qeventdispatcher_unix.cpp.
Referenced by timerSourcePrepareHelper().
 {
     timeval currentTime = updateCurrentTime();
     repairTimersIfNeeded();
     // Find first waiting timer not already active
     QTimerInfo *t = 0;
     for (QTimerInfoList::const_iterator it = constBegin(); it != constEnd(); ++it) {
         if (!(*it)->activateRef) {
             t = *it;
             break;
         }
     }
     if (!t)
       return false;
     if (currentTime < t->timeout) {
         // time to wait
         tm = t->timeout - currentTime;
     } else {
         // no time to wait
         tm.tv_sec  = 0;
         tm.tv_usec = 0;
     }
     return true;
 }
unregisterTimer()
bool QTimerInfoList::unregisterTimer (int timerId)
Definition at line 500 of file qeventdispatcher_unix.cpp.
 {
     // set timer inactive
     for (int i = 0; i < count(); ++i) {
         register QTimerInfo *t = at(i);
         if (t->id == timerId) {
             // found it
             removeAt(i);
             if (t == firstTimerInfo)
                 firstTimerInfo = 0;
             if (t->activateRef)
                 *(t->activateRef) = 0;
             // release the timer id
             if (!QObjectPrivate::get(t->obj)->inThreadChangeEvent)
                 QAbstractEventDispatcherPrivate::releaseTimerId(timerId);
             delete t;
             return true;
         }
     }
     // id not found
     return false;
 }
unregisterTimers()
bool QTimerInfoList::unregisterTimers (QObject * object)
Definition at line 525 of file qeventdispatcher_unix.cpp.
 {
     if (isEmpty())
         return false;
     for (int i = 0; i < count(); ++i) {
         register QTimerInfo *t = at(i);
         if (t->obj == object) {
             // object found
             removeAt(i);
             if (t == firstTimerInfo)
                 firstTimerInfo = 0;
             if (t->activateRef)
                 *(t->activateRef) = 0;
             // release the timer id
             if (!QObjectPrivate::get(t->obj)->inThreadChangeEvent)
                 QAbstractEventDispatcherPrivate::releaseTimerId(t->id);
             delete t;
             // move back one so that we don't skip the new current item
             --i;
         }
     }
     return true;
 }
updateCurrentTime()
timeval QTimerInfoList::updateCurrentTime ()
Definition at line 352 of file qeventdispatcher_unix.cpp.
Referenced by QEventDispatcherUNIXPrivate::doSelect(), and timerSourceCheckHelper().
 {
     return (currentTime = qt_gettime());
 }
Properties
currentTime
timeval QTimerInfoList::currentTime
Definition at line 98 of file qeventdispatcher_unix_p.h.
firstTimerInfo
QTimerInfo* QTimerInfoList::firstTimerInfo private
Definition at line 93 of file qeventdispatcher_unix_p.h.
The documentation for this class was generated from the following files:
/src/corelib/kernel/qeventdispatcher_unix_p.h
/src/corelib/kernel/qeventdispatcher_unix.cpp