Qt 4.8: QDeclarativeProperty Class Reference
QDeclarativeProperty Class Reference
The QDeclarativeProperty class abstracts accessing properties on objects created from QML.
#include <qdeclarativeproperty.h>
Public Types
enum PropertyTypeCategory { InvalidCategory, List, Object, Normal }
This enum specifies a category of QML property.
enum Type { Invalid, Property, SignalProperty }
This enum specifies a type of QML property.
Public Functions
bool connectNotifySignal (QObject *dest, const char *slot) const
Connects the property's change notifier signal to the specified slot of the dest object and returns true.
bool connectNotifySignal (QObject *dest, int method) const
Connects the property's change notifier signal to the specified method of the dest object and returns true.
bool hasNotifySignal () const
Returns true if the property has a change notifier signal, otherwise false.
int index () const
Return the Qt metaobject index of the property.
bool isDesignable () const
Returns true if the property is designable, otherwise false.
bool isProperty () const
Returns true if this QDeclarativeProperty represents a regular Qt property.
bool isResettable () const
Returns true if the property is resettable, otherwise false.
bool isSignalProperty () const
Returns true if this QDeclarativeProperty represents a QML signal property.
bool isValid () const
Returns true if the QDeclarativeProperty refers to a valid property, otherwise false.
bool isWritable () const
Returns true if the property is writable, otherwise false.
QMetaMethod method () const
Return the QMetaMethod for this property if it is a SignalProperty, otherwise returns an invalid QMetaMethod.
QString name () const
Return the name of this QML property.
bool needsNotifySignal () const
Returns true if the property needs a change notifier signal for bindings to remain upto date, false otherwise.
QObject * object () const
Returns the QDeclarativeProperty's QObject.
QDeclarativeProperty & operator= (const QDeclarativeProperty &)
Assign other to this QDeclarativeProperty.
bool operator== (const QDeclarativeProperty &) const
Returns true if other and this QDeclarativeProperty represent the same property.
QMetaProperty property () const
Returns the Qt property associated with this QML property.
int propertyType () const
Returns the QVariant type of the property, or QVariant::Invalid if the property has no QVariant type.
PropertyTypeCategory propertyTypeCategory () const
Returns the property category.
const char * propertyTypeName () const
Returns the type name of the property, or 0 if the property has no type name.
QDeclarativeProperty ()
Create an invalid QDeclarativeProperty.
QDeclarativeProperty (QObject *)
Creates a QDeclarativeProperty for the default property of obj.
QDeclarativeProperty (QObject *, QDeclarativeContext *)
Creates a QDeclarativeProperty for the default property of obj using the context ctxt.
QDeclarativeProperty (QObject *, QDeclarativeEngine *)
Creates a QDeclarativeProperty for the default property of obj using the environment for instantiating QML components that is provided by engine.
QDeclarativeProperty (QObject *, const QString &)
Creates a QDeclarativeProperty for the property name of obj.
QDeclarativeProperty (QObject *, const QString &, QDeclarativeContext *)
Creates a QDeclarativeProperty for the property name of obj using the context ctxt.
QDeclarativeProperty (QObject *, const QString &, QDeclarativeEngine *)
Creates a QDeclarativeProperty for the property name of obj using the environment for instantiating QML components that is provided by engine.
QDeclarativeProperty (const QDeclarativeProperty &)
Create a copy of other.
QVariant read () const
Returns the property value.
bool reset () const
Resets the property and returns true if the property is resettable.
Type type () const
Returns the type of the property.
bool write (const QVariant &) const
Sets the property value to value and returns true.
~QDeclarativeProperty ()
Static Public Functions
static QVariant read (QObject *, const QString &)
Return the name property value of object.
static QVariant read (QObject *, const QString &, QDeclarativeContext *)
Return the name property value of object using the context ctxt.
static QVariant read (QObject *, const QString &, QDeclarativeEngine *)
Return the name property value of object using the environment for instantiating QML components that is provided by engine.
static bool write (QObject *, const QString &, const QVariant &)
Writes value to the name property of object.
static bool write (QObject *, const QString &, const QVariant &, QDeclarativeContext *)
Writes value to the name property of object using the context ctxt.
static bool write (QObject *, const QString &, const QVariant &, QDeclarativeEngine *)
Writes value to the name property of object using the environment for instantiating QML components that is provided by engine.
Properties
QDeclarativePropertyPrivate * d
Friends
class QDeclarativePropertyPrivate
Detailed Description
The QDeclarativeProperty class abstracts accessing properties on objects created from QML.
Since
4.7
As QML uses Qt's meta-type system all of the existing QMetaObject classes can be used to introspect and interact with objects created by QML. However, some of the new features provided by QML - such as type safety and attached properties - are most easily used through the QDeclarativeProperty class that simplifies some of their natural complexity.
Unlike QMetaProperty which represents a property on a class type, QDeclarativeProperty encapsulates a property on a specific object instance. To read a property's value, programmers create a QDeclarativeProperty instance and call the read() method. Likewise to write a property value the write() method is used.
For example, for the following QML code:
// MyItem.qml
import QtQuick 1.0
Text { text: "A bit of text" }
The Text object's properties could be accessed using QDeclarativeProperty, like this:
#include <QDeclarativeProperty>
#include <QGraphicsObject>
...
QDeclarativeView view(QUrl::fromLocalFile("MyItem.qml"));
QDeclarativeProperty property(view.rootObject(), "font.pixelSize");
qWarning() << "Current pixel size:" << property.read().toInt();
property.write(24);
qWarning() << "Pixel size should now be 24:" << property.read().toInt();
Definition at line 59 of file qdeclarativeproperty.h.
Enumerations
PropertyTypeCategory
enum QDeclarativeProperty::PropertyTypeCategory
This enum specifies a category of QML property.
InvalidCategory The property is invalid, or is a signal property.
List The property is a QDeclarativeListProperty list property
Object The property is a QObject derived type pointer
Normal The property is a normal value property.
Enumerator
InvalidCategory
List
Object
Normal
Definition at line 62 of file qdeclarativeproperty.h.
{
         InvalidCategory,
         List,
         Object,
         Normal
     };
Type
enum QDeclarativeProperty::Type
This enum specifies a type of QML property.
Invalid The property is invalid.
Property The property is a regular Qt property.
SignalProperty The property is a signal property.
Enumerator
Invalid
Property
SignalProperty
Definition at line 69 of file qdeclarativeproperty.h.
               {
         Invalid,
         Property,
         SignalProperty
     };
Constructors and Destructors
QDeclarativeProperty() [1/8]
QDeclarativeProperty::QDeclarativeProperty ()
Create an invalid QDeclarativeProperty.
Definition at line 111 of file qdeclarativeproperty.cpp.
 : d(0)
 {
 }
~QDeclarativeProperty()
QDeclarativeProperty::~QDeclarativeProperty ()
Warning
This function is not part of the public interface.
Definition at line 117 of file qdeclarativeproperty.cpp.
 {
     if (d)
         d->release();
     d = 0;
 }
QDeclarativeProperty() [2/8]
QDeclarativeProperty::QDeclarativeProperty (QObject * obj)
Creates a QDeclarativeProperty for the default property of obj.
If there is no default property, an invalid QDeclarativeProperty will be created.
Definition at line 128 of file qdeclarativeproperty.cpp.
 : d(new QDeclarativePropertyPrivate)
 {
     d->initDefault(obj);
 }
QDeclarativeProperty() [3/8]
QDeclarativeProperty::QDeclarativeProperty (QObject * obj, QDeclarativeContext * ctxt)
Creates a QDeclarativeProperty for the default property of obj using the context ctxt.
If there is no default property, an invalid QDeclarativeProperty will be created.
Definition at line 140 of file qdeclarativeproperty.cpp.
 : d(new QDeclarativePropertyPrivate)
 {
     d->context = ctxt?QDeclarativeContextData::get(ctxt):0;
     d->engine = ctxt?ctxt->engine():0;
     d->initDefault(obj);
 }
QDeclarativeProperty() [4/8]
QDeclarativeProperty::QDeclarativeProperty (QObject * obj, QDeclarativeEngine * engine)
Creates a QDeclarativeProperty for the default property of obj using the environment for instantiating QML components that is provided by engine.
If there is no default property, an invalid QDeclarativeProperty will be created.
Definition at line 154 of file qdeclarativeproperty.cpp.
   : d(new QDeclarativePropertyPrivate)
 {
     d->context = 0;
     d->engine = engine;
     d->initDefault(obj);
 }
QDeclarativeProperty() [5/8]
QDeclarativeProperty::QDeclarativeProperty (QObject * obj, const QString & name)
Creates a QDeclarativeProperty for the property name of obj.
Definition at line 179 of file qdeclarativeproperty.cpp.
 : d(new QDeclarativePropertyPrivate)
 {
     d->initProperty(obj, name);
     if (!isValid()) d->object = 0;
 }
QDeclarativeProperty() [6/8]
QDeclarativeProperty::QDeclarativeProperty (QObject * obj, const QString & name, QDeclarativeContext * ctxt)
Creates a QDeclarativeProperty for the property name of obj using the context ctxt.
Creating a QDeclarativeProperty without a context will render some properties - like attached properties - inaccessible.
Definition at line 193 of file qdeclarativeproperty.cpp.
 : d(new QDeclarativePropertyPrivate)
 {
     d->context = ctxt?QDeclarativeContextData::get(ctxt):0;
     d->engine = ctxt?ctxt->engine():0;
     d->initProperty(obj, name);
     if (!isValid()) { d->object = 0; d->context = 0; d->engine = 0; }
 }
QDeclarativeProperty() [7/8]
QDeclarativeProperty::QDeclarativeProperty (QObject * obj, const QString & name, QDeclarativeEngine * engine)
Creates a QDeclarativeProperty for the property name of obj using the environment for instantiating QML components that is provided by engine.
Definition at line 207 of file qdeclarativeproperty.cpp.
 : d(new QDeclarativePropertyPrivate)
 {
     d->context = 0;
     d->engine = engine;
     d->initProperty(obj, name);
     if (!isValid()) { d->object = 0; d->context = 0; d->engine = 0; }
 }
QDeclarativeProperty() [8/8]
QDeclarativeProperty::QDeclarativeProperty (const QDeclarativeProperty & other)
Create a copy of other.
Definition at line 327 of file qdeclarativeproperty.cpp.
 {
     d = other.d;
     if (d)
         d->addref();
 }
Functions
connectNotifySignal() [1/2]
bool QDeclarativeProperty::connectNotifySignal (QObject * dest, const char * slot) const
Connects the property's change notifier signal to the specified slot of the dest object and returns true.
Returns false if this metaproperty does not represent a regular Qt property or if it has no change notifier signal, or if the dest object does not have the specified slot.
Definition at line 1409 of file qdeclarativeproperty.cpp.
 {
     if (!(type() & Property) || !d->object)
         return false;
     QMetaProperty prop = d->object->metaObject()->property(d->core.coreIndex);
     if (prop.hasNotifySignal()) {
         QByteArray signal(QByteArray("2") + prop.notifySignal().signature());
         return QObject::connect(d->object, signal.constData(), dest, slot);
     } else  {
         return false;
     }
 }
connectNotifySignal() [2/2]
bool QDeclarativeProperty::connectNotifySignal (QObject * dest, int method) const
Connects the property's change notifier signal to the specified method of the dest object and returns true.
Returns false if this metaproperty does not represent a regular Qt property or if it has no change notifier signal, or if the dest object does not have the specified method.
Definition at line 1388 of file qdeclarativeproperty.cpp.
 {
     if (!(type() & Property) || !d->object)
         return false;
     QMetaProperty prop = d->object->metaObject()->property(d->core.coreIndex);
     if (prop.hasNotifySignal()) {
         return QDeclarativePropertyPrivate::connect(d->object, prop.notifySignalIndex(), dest, method, Qt::DirectConnection);
     } else {
         return false;
     }
 }
hasNotifySignal()
bool QDeclarativeProperty::hasNotifySignal () const
Returns true if the property has a change notifier signal, otherwise false.
Definition at line 1360 of file qdeclarativeproperty.cpp.
 {
     if (type() & Property && d->object) {
         return d->object->metaObject()->property(d->core.coreIndex).hasNotifySignal();
     }
     return false;
 }
index()
int QDeclarativeProperty::index () const
Return the Qt metaobject index of the property.
Definition at line 1426 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativePropertyPrivate::binding(), QDeclarativePropertyPrivate::setBinding(), QDeclarativePropertyPrivate::setBindingNoEnable(), QDeclarativePropertyPrivate::setSignalExpression(), and QDeclarativePropertyPrivate::signalExpression().
 {
     return d ? d->core.coreIndex : -1;
 }
isDesignable()
bool QDeclarativeProperty::isDesignable () const
Returns true if the property is designable, otherwise false.
Definition at line 543 of file qdeclarativeproperty.cpp.
 {
     if (!d)
         return false;
     if (type() & Property && d->core.isValid() && d->object)
         return d->object->metaObject()->property(d->core.coreIndex).isDesignable();
     else
         return false;
 }
isProperty()
bool QDeclarativeProperty::isProperty () const
Returns true if this QDeclarativeProperty represents a regular Qt property.
Definition at line 486 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativePropertyPrivate::binding(), QDeclarativeEngineDebugService::setBinding(), and QDeclarativePropertyPrivate::setBinding().
 {
     return type() & Property;
 }
isResettable()
bool QDeclarativeProperty::isResettable () const
Returns true if the property is resettable, otherwise false.
Definition at line 556 of file qdeclarativeproperty.cpp.
Referenced by reset(), and QDeclarativeEngineDebugService::resetBinding().
 {
     if (!d)
         return false;
     if (type() & Property && d->core.isValid() && d->object)
         return d->core.flags & QDeclarativePropertyCache::Data::IsResettable;
     else
         return false;
 }
isSignalProperty()
bool QDeclarativeProperty::isSignalProperty () const
Returns true if this QDeclarativeProperty represents a QML signal property.
Definition at line 494 of file qdeclarativeproperty.cpp.
 {
     return type() & SignalProperty;
 }
isValid()
bool QDeclarativeProperty::isValid () const
Returns true if the QDeclarativeProperty refers to a valid property, otherwise false.
Definition at line 570 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativeConnections::connectSignals(), QDeclarativeAbstractAnimationPrivate::createProperty(), QDeclarativePropertyChangesPrivate::property(), QDeclarativeAction::QDeclarativeAction(), QDeclarativeProperty(), QDeclarativeEngineDebugService::setBinding(), QDeclarativePropertyAction::transition(), and QDeclarativePropertyAnimation::transition().
 {
     if (!d)
         return false;
     return type() != Invalid;
 }
isWritable()
bool QDeclarativeProperty::isWritable () const
Returns true if the property is writable, otherwise false.
Definition at line 524 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativeAbstractAnimationPrivate::createProperty(), QDeclarativePropertyChangesPrivate::property(), and QDeclarativePropertyPrivate::write().
 {
     if (!d)
         return false;
     if (!d->object)
         return false;
     if (d->core.flags & QDeclarativePropertyCache::Data::IsQList)           //list
         return true;
     else if (d->core.flags & QDeclarativePropertyCache::Data::IsFunction)   //signal handler
         return false;
     else if (d->core.isValid())                                             //normal property
         return d->core.flags & QDeclarativePropertyCache::Data::IsWritable;
     else
         return false;
 }
method()
QMetaMethod QDeclarativeProperty::method () const
Return the QMetaMethod for this property if it is a SignalProperty, otherwise returns an invalid QMetaMethod.
Definition at line 632 of file qdeclarativeproperty.cpp.
Referenced by connectNotifySignal(), QDeclarativeConnections::connectSignals(), QDeclarativePropertyPrivate::findSignalByName(), QDeclarativePropertyPrivate::initProperty(), and QDeclarativePropertyPrivate::setSignalExpression().
 {
     if (!d)
         return QMetaMethod();
     if (type() & SignalProperty && d->object)
         return d->object->metaObject()->method(d->core.coreIndex);
     else
         return QMetaMethod();
 }
name()
QString QDeclarativeProperty::name () const
Return the name of this QML property.
Definition at line 580 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativeState::apply(), qHash(), QDeclarativeState::removeEntryFromRevertList(), QDeclarativeTransitionManager::transition(), QDeclarativePropertyAction::transition(), and QDeclarativePropertyAnimation::transition().
 {
     if (!d)
         return QString();
     if (!d->isNameCached) {
         // ###
         if (!d->object) {
         } else if (d->isValueType()) {
             QString rv = d->core.name(d->object) + QLatin1Char('.');
             QDeclarativeEnginePrivate *ep = d->engine?QDeclarativeEnginePrivate::get(d->engine):0;
             QDeclarativeValueType *valueType = 0;
             if (ep) valueType = ep->valueTypes[d->core.propType];
             else valueType = QDeclarativeValueTypeFactory::valueType(d->core.propType);
             Q_ASSERT(valueType);
             rv += QString::fromUtf8(valueType->metaObject()->property(d->valueType.valueTypeCoreIdx).name());
             if (!ep) delete valueType;
             d->nameCache = rv;
         } else if (type() & SignalProperty) {
             QString name = QLatin1String("on") + d->core.name(d->object);
             name[2] = name.at(2).toUpper();
             d->nameCache = name;
         } else {
             d->nameCache = d->core.name(d->object);
         }
         d->isNameCached = true;
     }
     return d->nameCache;
 }
needsNotifySignal()
bool QDeclarativeProperty::needsNotifySignal () const
Returns true if the property needs a change notifier signal for bindings to remain upto date, false otherwise.
Some properties, such as attached properties or those whose value never changes, do not require a change notifier.
Definition at line 1375 of file qdeclarativeproperty.cpp.
 {
     return type() & Property && !property().isConstant();
 }
object()
QObject * QDeclarativeProperty::object () const
Returns the QDeclarativeProperty's QObject.
Definition at line 502 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativeState::apply(), QDeclarativePropertyPrivate::findAliasTarget(), qHash(), QDeclarativeState::removeAllEntriesFromRevertList(), QDeclarativeState::removeEntryFromRevertList(), QDeclarativePropertyPrivate::restore(), QDeclarativeTransitionManager::transition(), QDeclarativePropertyAction::transition(), and QDeclarativePropertyAnimation::transition().
 {
     return d ? d->object : 0;
 }
operator=()
QDeclarativeProperty & QDeclarativeProperty::operator= (const QDeclarativeProperty & other)
Assign other to this QDeclarativeProperty.
Definition at line 510 of file qdeclarativeproperty.cpp.
 {
     if (d)
         d->release();
     d = other.d;
     if (d)
         d->addref();
     return *this;
 }
operator==()
bool QDeclarativeProperty::operator== (const QDeclarativeProperty & other) const
Returns true if other and this QDeclarativeProperty represent the same property.
Definition at line 425 of file qdeclarativeproperty.cpp.
 {
     if (!d || !other.d)
         return false;
     // category is intentially omitted here as it is generated
     // from the other members
     return d->object == other.d->object &&
            d->core == other.d->core &&
            d->valueType == other.d->valueType;
 }
property()
QMetaProperty QDeclarativeProperty::property () const
Returns the Qt property associated with this QML property.
Definition at line 618 of file qdeclarativeproperty.cpp.
Referenced by flush_vme_signal(), QDeclarativePropertyPrivate::initProperty(), and needsNotifySignal().
 {
     if (!d)
         return QMetaProperty();
     if (type() & Property && d->core.isValid() && d->object)
         return d->object->metaObject()->property(d->core.coreIndex);
     else
         return QMetaProperty();
 }
propertyType()
int QDeclarativeProperty::propertyType () const
Returns the QVariant type of the property, or QVariant::Invalid if the property has no QVariant type.
Definition at line 440 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativePropertyPrivate::propertyTypeCategory(), QDeclarativeAnimationPropertyUpdater::setValue(), QDeclarativePropertyAction::transition(), QDeclarativePropertyAnimation::transition(), and QDeclarativePropertyPrivate::write().
 {
     return d ? d->propertyType() : int(QVariant::Invalid);
 }
propertyTypeCategory()
QDeclarativeProperty::PropertyTypeCategory QDeclarativeProperty::propertyTypeCategory () const
Returns the property category.
Definition at line 364 of file qdeclarativeproperty.cpp.
 {
     return d ? d->propertyTypeCategory() : InvalidCategory;
 }
propertyTypeName()
const char * QDeclarativeProperty::propertyTypeName () const
Returns the type name of the property, or 0 if the property has no type name.
Definition at line 397 of file qdeclarativeproperty.cpp.
 {
     if (!d)
         return 0;
     if (d->isValueType()) {
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(d->context);
         QDeclarativeValueType *valueType = 0;
         if (ep) valueType = ep->valueTypes[d->core.propType];
         else valueType = QDeclarativeValueTypeFactory::valueType(d->core.propType);
         Q_ASSERT(valueType);
         const char *rv = valueType->metaObject()->property(d->valueType.valueTypeCoreIdx).typeName();
         if (!ep) delete valueType;
         return rv;
     } else if (d->object && type() & Property && d->core.isValid()) {
         return d->object->metaObject()->property(d->core.coreIndex).typeName();
     } else {
         return 0;
     }
 }
read() [1/4]
QVariant QDeclarativeProperty::read () const
Returns the property value.
Definition at line 921 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativeParentChange::actions(), QDeclarativePropertyChanges::changeExpression(), QDeclarativePropertyChanges::changeValue(), QSmoothedAnimation::init(), QDeclarativeAction::QDeclarativeAction(), read(), QDeclarativeEngineDebugService::resetBinding(), QDeclarativeAnimationPropertyUpdater::setValue(), and QDeclarativeTransitionManager::transition().
 {
     if (!d)
         return QVariant();
     if (!d->object)
         return QVariant();
     if (type() & SignalProperty) {
         return QVariant();
     } else if (type() & Property) {
         return d->readValueProperty();
     }
     return QVariant();
 }
read() [2/4]
QVariant QDeclarativeProperty::read (QObject * object, const QString & name) static
Return the name property value of object.
This method is equivalent to:
QDeclarativeProperty p(object, name);
p.read();
Definition at line 947 of file qdeclarativeproperty.cpp.
 {
     QDeclarativeProperty p(object, name);
     return p.read();
 }
read() [3/4]
QVariant QDeclarativeProperty::read (QObject * object, const QString & name, QDeclarativeContext * ctxt) static
Return the name property value of object using the context ctxt.
This method is equivalent to:
QDeclarativeProperty p(object, name, context);
p.read();
Definition at line 963 of file qdeclarativeproperty.cpp.
 {
     QDeclarativeProperty p(object, name, ctxt);
     return p.read();
 }
read() [4/4]
QVariant QDeclarativeProperty::read (QObject * object, const QString & name, QDeclarativeEngine * engine) static
Return the name property value of object using the environment for instantiating QML components that is provided by engine.
This method is equivalent to:
QDeclarativeProperty p(object, name, engine);
p.read();
Definition at line 980 of file qdeclarativeproperty.cpp.
 {
     QDeclarativeProperty p(object, name, engine);
     return p.read();
 }
reset()
bool QDeclarativeProperty::reset () const
Resets the property and returns true if the property is resettable.
If the property is not resettable, nothing happens and false is returned.
Definition at line 1334 of file qdeclarativeproperty.cpp.
 {
     if (isResettable()) {
         void *args[] = { 0 };
         QMetaObject::metacall(d->object, QMetaObject::ResetProperty, d->core.coreIndex, args);
         return true;
     } else {
         return false;
     }
 }
type()
QDeclarativeProperty::Type QDeclarativeProperty::type () const
Returns the type of the property.
Definition at line 478 of file qdeclarativeproperty.cpp.
Referenced by connectNotifySignal(), QDeclarativeConnections::connectSignals(), QDeclarativePropertyChangesPrivate::decode(), hasNotifySignal(), isDesignable(), isProperty(), isResettable(), isSignalProperty(), isValid(), method(), name(), needsNotifySignal(), property(), QDeclarativePropertyChangesPrivate::property(), QDeclarativePropertyPrivate::propertyType(), QDeclarativePropertyPrivate::propertyTypeCategory(), propertyTypeName(), QDeclarativePropertyPrivate::rawMetaObjectForType(), read(), QDeclarativePropertyPrivate::setSignalExpression(), QDeclarativePropertyPrivate::signalExpression(), QDeclarativePropertyPrivate::write(), and QDeclarativePropertyPrivate::writeValueProperty().
 {
     return d ? d->type() : Invalid;
 }
write() [1/4]
bool QDeclarativeProperty::write (const QVariant & value) const
Sets the property value to value and returns true.
Returns false if the property can't be set because the value is the wrong type, for example.
Definition at line 1272 of file qdeclarativeproperty.cpp.
Referenced by QDeclarativeState::addEntriesToRevertList(), QDeclarativeTransitionManager::complete(), QDeclarativeBind::eval(), QDeclarativeState::removeAllEntriesFromRevertList(), QDeclarativeState::removeEntryFromRevertList(), QDeclarativeTransitionManager::transition(), write(), and QDeclarativePropertyPrivate::writeValueProperty().
 {
     return QDeclarativePropertyPrivate::write(*this, value, 0);
 }
write() [2/4]
bool QDeclarativeProperty::write (QObject * object, const QString & name, const QVariant & value) static
Writes value to the name property of object.
This method is equivalent to:
QDeclarativeProperty p(object, name);
p.write(value);
Definition at line 1286 of file qdeclarativeproperty.cpp.
 {
     QDeclarativeProperty p(object, name);
     return p.write(value);
 }
write() [3/4]
bool QDeclarativeProperty::write (QObject * object, const QString & name, const QVariant & value, QDeclarativeContext * ctxt) static
Writes value to the name property of object using the context ctxt.
This method is equivalent to:
QDeclarativeProperty p(object, name, ctxt);
p.write(value);
Definition at line 1302 of file qdeclarativeproperty.cpp.
 {
     QDeclarativeProperty p(object, name, ctxt);
     return p.write(value);
 }
write() [4/4]
bool QDeclarativeProperty::write (QObject * object, const QString & name, const QVariant & value, QDeclarativeEngine * engine) static
Writes value to the name property of object using the environment for instantiating QML components that is provided by engine.
This method is equivalent to:
QDeclarativeProperty p(object, name, engine);
p.write(value);
Definition at line 1322 of file qdeclarativeproperty.cpp.
 {
     QDeclarativeProperty p(object, name, engine);
     return p.write(value);
 }
Friends and Related Functions
QDeclarativePropertyPrivate
friend class QDeclarativePropertyPrivate friend
Definition at line 129 of file qdeclarativeproperty.h.
Referenced by QDeclarativePropertyPrivate::restore().
Properties
d
QDeclarativePropertyPrivate* QDeclarativeProperty::d private
Definition at line 130 of file qdeclarativeproperty.h.
Referenced by QDeclarativePropertyPrivate::binding(), QDeclarativePropertyPrivate::bindingIndex(), connectNotifySignal(), hasNotifySignal(), index(), isDesignable(), isResettable(), isValid(), isWritable(), method(), name(), object(), operator=(), operator==(), property(), propertyType(), propertyTypeCategory(), propertyTypeName(), QDeclarativeProperty(), read(), reset(), QDeclarativePropertyPrivate::restore(), QDeclarativePropertyPrivate::setBinding(), QDeclarativePropertyPrivate::setSignalExpression(), QDeclarativePropertyPrivate::signalExpression(), type(), QDeclarativePropertyPrivate::valueTypeCoreIndex(), QDeclarativePropertyPrivate::write(), and ~QDeclarativeProperty().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeproperty.h
/src/declarative/qml/qdeclarativeproperty.cpp