Qt 4.8: QToolBar Class Reference
QToolBar Class Reference
The QToolBar class provides a movable panel that contains a set of controls.
#include <qtoolbar.h>
Public Slots
void setIconSize (const QSize &iconSize)
void setToolButtonStyle (Qt::ToolButtonStyle toolButtonStyle)
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void actionTriggered (QAction *action)
This signal is emitted when an action in this toolbar is triggered.
void allowedAreasChanged (Qt::ToolBarAreas allowedAreas)
This signal is emitted when the collection of allowed areas for the toolbar is changed.
void iconSizeChanged (const QSize &iconSize)
This signal is emitted when the icon size is changed.
void movableChanged (bool movable)
This signal is emitted when the toolbar becomes movable or fixed.
void orientationChanged (Qt::Orientation orientation)
This signal is emitted when the orientation of the toolbar changes.
void toolButtonStyleChanged (Qt::ToolButtonStyle toolButtonStyle)
This signal is emitted when the tool button style is changed.
void topLevelChanged (bool topLevel)
This signal is emitted when the floating property changes.
void visibilityChanged (bool visible)
This signal is emitted when the toolbar becomes visible (or invisible).
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QAction * actionAt (const QPoint &p) const
Returns the action at point p.
QAction * actionAt (int x, int y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the action at the point x, y.
QRect actionGeometry (QAction *action) const
Returns the geometry of the toolbar item associated with the given action, or an invalid QRect if no matching item is found.
QAction * addAction (const QString &text)
Creates a new action with the given text.
QAction * addAction (const QIcon &icon, const QString &text)
Creates a new action with the given icon and text.
QAction * addAction (const QString &text, const QObject *receiver, const char *member)
Creates a new action with the given text.
QAction * addAction (const QIcon &icon, const QString &text, const QObject *receiver, const char *member)
Creates a new action with the icon icon and text text.
QAction * addSeparator ()
Adds a separator to the end of the toolbar.
QAction * addWidget (QWidget *widget)
Adds the given widget to the toolbar as the toolbar's last item.
Qt::ToolBarAreas allowedAreas () const
areas where the toolbar may be placed
void clear ()
Removes all actions from the toolbar.
QSize iconSize () const
size of icons in the toolbar.
QAction * insertSeparator (QAction *before)
Inserts a separator into the toolbar in front of the toolbar item associated with the before action.
QAction * insertWidget (QAction *before, QWidget *widget)
Inserts the given widget in front of the toolbar item associated with the before action.
bool isAreaAllowed (Qt::ToolBarArea area) const
Returns true if this toolbar is dockable in the given area; otherwise returns false.
bool isFloatable () const
bool isFloating () const
bool isMovable () const
Qt::Orientation orientation () const
orientation of the toolbar
QToolBar (const QString &title, QWidget *parent=0)
Constructs a QToolBar with the given parent.
QToolBar (QWidget *parent=0)
Constructs a QToolBar with the given parent.
void setAllowedAreas (Qt::ToolBarAreas areas)
void setFloatable (bool floatable)
void setMovable (bool movable)
void setOrientation (Qt::Orientation orientation)
QAction * toggleViewAction () const
Returns a checkable action that can be used to show or hide this toolbar.
Qt::ToolButtonStyle toolButtonStyle () const
QWidget * widgetForAction (QAction *action) const
Returns the widget associated with the specified action.
~QToolBar ()
Destroys the toolbar.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
virtual QSize minimumSizeHint () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
virtual QSize sizeHint () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void actionEvent (QActionEvent *event)
Reimplemented Function
void changeEvent (QEvent *event)
Reimplemented Function
void childEvent (QChildEvent *event)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
void initStyleOption (QStyleOptionToolBar *option) const
void paintEvent (QPaintEvent *event)
Reimplemented Function
void resizeEvent (QResizeEvent *event)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool floatable
whether the toolbar can be dragged and dropped as an independent window.
bool floating
whether the toolbar is an independent window.
bool movable
whether the user can move the toolbar within the toolbar area, or between toolbar areas
Qt::ToolButtonStyle toolButtonStyle
the style of toolbar buttons
Friends
class QMainWindow
class QMainWindowLayout
class QToolBarAreaLayout
class QToolBarLayout
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QToolBar class provides a movable panel that contains a set of controls.
Toolbar buttons are added by adding actions, using addAction() or insertAction(). Groups of buttons can be separated using addSeparator() or insertSeparator(). If a toolbar button is not appropriate, a widget can be inserted instead using addWidget() or insertWidget(); examples of suitable widgets are QSpinBox, QDoubleSpinBox, and QComboBox. When a toolbar button is pressed it emits the actionTriggered() signal.
A toolbar can be fixed in place in a particular area (e.g. at the top of the window), or it can be movable (isMovable()) between toolbar areas; see allowedAreas() and isAreaAllowed().
When a toolbar is resized in such a way that it is too small to show all the items it contains, an extension button will appear as the last item in the toolbar. Pressing the extension button will pop up a menu containing the items that does not currently fit in the toolbar.
When a QToolBar is not a child of a QMainWindow, it loses the ability to populate the extension pop up with widgets added to the toolbar using addWidget(). Please use widget actions created by inheriting QWidgetAction and implementing QWidgetAction::createWidget() instead.
See also
QToolButton, QMenu, QAction, {Application Example}
Definition at line 62 of file qtoolbar.h.
Constructors and Destructors
QToolBar() [1/2]
QToolBar::QToolBar (const QString & title, QWidget * parent = 0) explicit
Constructs a QToolBar with the given parent.
The given window title identifies the toolbar and is shown in the context menu provided by QMainWindow.
See also
setWindowTitle()
Definition at line 590 of file qtoolbar.cpp.
     : QWidget(*new QToolBarPrivate, parent, 0)
 {
     Q_D(QToolBar);
     d->init();
     setWindowTitle(title);
 }
QToolBar() [2/2]
QToolBar::QToolBar (QWidget * parent = 0) explicit
Constructs a QToolBar with the given parent.
Definition at line 575 of file qtoolbar.cpp.
     : QWidget(*new QToolBarPrivate, parent, 0)
 {
     Q_D(QToolBar);
     d->init();
 }
~QToolBar()
QToolBar::~QToolBar ()
Destroys the toolbar.
Definition at line 617 of file qtoolbar.cpp.
 {
     // Remove the toolbar button if there is nothing left.
     QMainWindow *mainwindow = qobject_cast<QMainWindow *>(parentWidget());
     if (mainwindow) {
 #ifdef Q_WS_MAC
         QMainWindowLayout *mainwin_layout = qt_mainwindow_layout(mainwindow);
         if (mainwin_layout && mainwin_layout->layoutState.toolBarAreaLayout.isEmpty()
                 && mainwindow->testAttribute(Qt::WA_WState_Created))
             macWindowToolbarShow(mainwindow, false);
 #endif
     }
 }
Functions
actionAt() [1/2]
QAction * QToolBar::actionAt (const QPoint & p) const
Returns the action at point p.
This function returns zero if no action was found.
See also
QWidget::childAt()
Definition at line 1026 of file qtoolbar.cpp.
 {
     Q_D(const QToolBar);
     QWidget *widget = childAt(p);
     int index = d->layout->indexOf(widget);
     if (index == -1)
         return 0;
     QLayoutItem *item = d->layout->itemAt(index);
     return static_cast<QToolBarItem*>(item)->action;
 }
actionAt() [2/2]
QAction * QToolBar::actionAt (int x, int y) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the action at the point x, y.
This function returns zero if no action was found.
Definition at line 175 of file qtoolbar.h.
 { return actionAt(QPoint(ax, ay)); }
actionEvent()
void QToolBar::actionEvent (QActionEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1045 of file qtoolbar.cpp.
 {
     Q_D(QToolBar);
     QAction *action = event->action();
     QWidgetAction *widgetAction = qobject_cast<QWidgetAction *>(action);
     switch (event->type()) {
         case QEvent::ActionAdded: {
             Q_ASSERT_X(widgetAction == 0 || d->layout->indexOf(widgetAction) == -1,
                         "QToolBar", "widgets cannot be inserted multiple times");
             // reparent the action to this toolbar if it has been created
             // using the addAction(text) etc. convenience functions, to
             // preserve Qt 4.1.x behavior. The widget is already
             // reparented to us due to the createWidget call inside
             // createItem()
             if (widgetAction != 0 && widgetAction->d_func()->autoCreated)
                 widgetAction->setParent(this);
             int index = d->layout->count();
             if (event->before()) {
                 index = d->layout->indexOf(event->before());
                 Q_ASSERT_X(index != -1, "QToolBar::insertAction", "internal error");
             }
             d->layout->insertAction(index, action);
             break;
         }
         case QEvent::ActionChanged:
             d->layout->invalidate();
             break;
         case QEvent::ActionRemoved: {
             int index = d->layout->indexOf(action);
             if (index != -1) {
                 delete d->layout->takeAt(index);
             }
             break;
         }
         default:
             Q_ASSERT_X(false, "QToolBar::actionEvent", "internal error");
     }
 }
actionGeometry()
QRect QToolBar::actionGeometry (QAction * action) const
Returns the geometry of the toolbar item associated with the given action, or an invalid QRect if no matching item is found.
Warning
This function is not part of the public interface.
Definition at line 1010 of file qtoolbar.cpp.
 {
     Q_D(const QToolBar);
     int index = d->layout->indexOf(action);
     if (index == -1)
         return QRect();
     return d->layout->itemAt(index)->widget()->geometry();
 }
actionTriggered
void QToolBar::actionTriggered (QAction * action) signal
This signal is emitted when an action in this toolbar is triggered.
This happens when the action's tool button is pressed, or when the action is triggered in some other way outside the tool bar. The parameter holds the triggered action.
addAction() [1/4]
QAction * QToolBar::addAction (const QString & text)
Creates a new action with the given text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This action is added to the end of the toolbar.
Definition at line 868 of file qtoolbar.cpp.
Referenced by addAction(), addSeparator(), addWidget(), QScriptDebugger::createStandardToolBar(), QPrintPreviewDialogPrivate::init(), QmlJSDebugger::QmlToolBar::QmlToolBar(), and QScriptBreakpointsWidget::QScriptBreakpointsWidget().
 {
     QAction *action = new QAction(text, this);
     addAction(action);
     return action;
 }
addAction() [2/4]
QAction * QToolBar::addAction (const QIcon & icon, const QString & text)
Creates a new action with the given icon and text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This action is added to the end of the toolbar.
Definition at line 884 of file qtoolbar.cpp.
 {
     QAction *action = new QAction(icon, text, this);
     addAction(action);
     return action;
 }
addAction() [3/4]
QAction * QToolBar::addAction (const QString & text, const QObject * receiver, const char * member)
Creates a new action with the given text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This action is added to the end of the toolbar. The action's triggered() signal is connected to member in receiver.
Definition at line 902 of file qtoolbar.cpp.
 {
     QAction *action = new QAction(text, this);
     QObject::connect(action, SIGNAL(triggered(bool)), receiver, member);
     addAction(action);
     return action;
 }
addAction() [4/4]
QAction * QToolBar::addAction (const QIcon & icon, const QString & text, const QObject * receiver, const char * member)
Creates a new action with the icon icon and text text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This action is added to the end of the toolbar. The action's triggered() signal is connected to member in receiver.
Definition at line 922 of file qtoolbar.cpp.
 {
     QAction *action = new QAction(icon, text, this);
     QObject::connect(action, SIGNAL(triggered(bool)), receiver, member);
     addAction(action);
     return action;
 }
addSeparator()
QAction * QToolBar::addSeparator ()
Adds a separator to the end of the toolbar.
See also
insertSeparator()
Definition at line 936 of file qtoolbar.cpp.
Referenced by QScriptDebugger::createStandardToolBar(), QPrintPreviewDialogPrivate::init(), and QmlJSDebugger::QmlToolBar::QmlToolBar().
 {
     QAction *action = new QAction(this);
     action->setSeparator(true);
     addAction(action);
     return action;
 }
addWidget()
QAction * QToolBar::addWidget (QWidget * widget)
Adds the given widget to the toolbar as the toolbar's last item.
The toolbar takes ownership of widget.
If you add a QToolButton with this method, the tools bar's Qt::ToolButtonStyle will not be respected.
Note
You should use QAction::setVisible() to change the visibility of the widget. Using QWidget::setVisible(), QWidget::show() and QWidget::hide() does not work.
See also
insertWidget()
Definition at line 973 of file qtoolbar.cpp.
Referenced by QPrintPreviewDialogPrivate::init(), and QmlJSDebugger::QmlToolBar::QmlToolBar().
 {
     QWidgetAction *action = new QWidgetAction(this);
     action->setDefaultWidget(widget);
     action->d_func()->autoCreated = true;
     addAction(action);
     return action;
 }
allowedAreas()
Qt::ToolBarAreas QToolBar::allowedAreas () const
areas where the toolbar may be placed
The default is Qt::AllToolBarAreas.
This property only makes sense if the toolbar is in a QMainWindow.
See also
movable
Definition at line 724 of file qtoolbar.cpp.
 {
     Q_D(const QToolBar);
 #ifdef Q_WS_MAC
     if (QMainWindow *window = qobject_cast<QMainWindow *>(parentWidget())) {
         if (window->unifiedTitleAndToolBarOnMac()) // Don't allow drags to the top (for now).
             return (d->allowedAreas & ~Qt::TopToolBarArea);
     }
 #endif
     return d->allowedAreas;
 }
allowedAreasChanged
void QToolBar::allowedAreasChanged (Qt::ToolBarAreas allowedAreas) signal
This signal is emitted when the collection of allowed areas for the toolbar is changed.
The new areas in which the toolbar can be positioned are specified by allowedAreas.
See also
allowedAreas
Referenced by setAllowedAreas().
changeEvent()
void QToolBar::changeEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1091 of file qtoolbar.cpp.
 {
     Q_D(QToolBar);
     switch (event->type()) {
     case QEvent::WindowTitleChange:
         d->toggleViewAction->setText(windowTitle());
         break;
     case QEvent::StyleChange:
         d->layout->invalidate();
         if (!d->explicitIconSize)
             setIconSize(QSize());
         d->layout->updateMarginAndSpacing();
         break;
     case QEvent::LayoutDirectionChange:
         d->layout->invalidate();
         break;
     default:
         break;
     }
     QWidget::changeEvent(event);
 }
childEvent()
void QToolBar::childEvent (QChildEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1407 of file qtoolbar.cpp.
 {
     QWidget::childEvent(event);
 }
clear()
void QToolBar::clear ()
Removes all actions from the toolbar.
See also
removeAction()
Definition at line 852 of file qtoolbar.cpp.
 {
     QList<QAction *> actions = this->actions();
     for(int i = 0; i < actions.size(); i++)
         removeAction(actions.at(i));
 }
event()
bool QToolBar::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1180 of file qtoolbar.cpp.
 {
     Q_D(QToolBar);
     switch (event->type()) {
     case QEvent::Timer:
         if (d->waitForPopupTimer.timerId() == static_cast<QTimerEvent*>(event)->timerId()) {
             QWidget *w = QApplication::activePopupWidget();
             if (!waitForPopup(this, w)) {
                 d->waitForPopupTimer.stop();
                 if (!this->underMouse())
                     d->layout->setExpanded(false);
             }
         }
         break;
     case QEvent::Hide:
         if (!isHidden())
             break;
         // fallthrough intended
     case QEvent::Show:
         d->toggleViewAction->setChecked(event->type() == QEvent::Show);
         emit visibilityChanged(event->type() == QEvent::Show);
 #if defined(Q_WS_MAC)
         if (toolbarInUnifiedToolBar(this)) {
              // I can static_cast because I did the qobject_cast in the if above, therefore
             // we must have a QMainWindowLayout here.
             QMainWindowLayout *mwLayout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(parentWidget()));
             mwLayout->fixSizeInUnifiedToolbar(this);
             mwLayout->syncUnifiedToolbarVisibility();
         }
 #  if !defined(QT_MAC_USE_COCOA)
         // Fall through
     case QEvent::LayoutRequest: {
         // There's currently no way to invalidate the size and let
         // HIToolbar know about it. This forces a re-check.
         int earlyResult = -1;
         if (QMainWindow *mainWindow = qobject_cast<QMainWindow *>(parentWidget())) {
             bool needUpdate = true;
             if (event->type() == QEvent::LayoutRequest) {
                 QSize oldSizeHint = sizeHint();
                 earlyResult = QWidget::event(event) ? 1 : 0;
                 needUpdate = oldSizeHint != sizeHint();
             }
             if (needUpdate) {
                 OSWindowRef windowRef = qt_mac_window_for(mainWindow);
                 if (toolbarInUnifiedToolBar(this)
                         && macWindowToolbarIsVisible(windowRef))   {
                     DisableScreenUpdates();
                     macWindowToolbarShow(this, false);
                     macWindowToolbarShow(this, true);
                     EnableScreenUpdates();
                 }
             }
             if (earlyResult != -1)
                 return earlyResult;
         }
     }
 #  endif // !QT_MAC_USE_COCOA
 #endif // Q_WS_MAC
         break;
     case QEvent::ParentChange:
         d->layout->checkUsePopupMenu();
 #if defined(Q_WS_MAC)
         if (parentWidget() && parentWidget()->isWindow())
             qt_mac_updateToolBarButtonHint(parentWidget());
 #endif
         break;
     case QEvent::MouseButtonPress: {
         if (d->mousePressEvent(static_cast<QMouseEvent*>(event)))
             return true;
         break;
     }
     case QEvent::MouseButtonRelease:
         if (d->mouseReleaseEvent(static_cast<QMouseEvent*>(event)))
             return true;
         break;
     case QEvent::HoverEnter:
     case QEvent::HoverLeave:
         // there's nothing special to do here and we don't want to update the whole widget
         return true;
     case QEvent::HoverMove: {
 #ifndef QT_NO_CURSOR
         QHoverEvent *e = static_cast<QHoverEvent*>(event);
         QStyleOptionToolBar opt;
         initStyleOption(&opt);
         if (style()->subElementRect(QStyle::SE_ToolBarHandle, &opt, this).contains(e->pos()))
             setCursor(Qt::SizeAllCursor);
         else
             unsetCursor();
 #endif
         break;
     }
     case QEvent::MouseMove:
         if (d->mouseMoveEvent(static_cast<QMouseEvent*>(event)))
             return true;
         break;
 #ifdef Q_WS_WINCE
     case QEvent::ContextMenu:
         {
             QContextMenuEvent* contextMenuEvent = static_cast<QContextMenuEvent*>(event);
             QWidget* child = childAt(contextMenuEvent->pos());
             QAbstractButton* button = qobject_cast<QAbstractButton*>(child);
             if (button)
                 button->setDown(false);
         }
         break;
 #endif
     case QEvent::Leave:
         if (d->state != 0 && d->state->dragging) {
 #ifdef Q_OS_WIN
             // This is a workaround for loosing the mouse on Vista.
             QPoint pos = QCursor::pos();
             QMouseEvent fake(QEvent::MouseMove, mapFromGlobal(pos), pos, Qt::NoButton,
                              QApplication::mouseButtons(), QApplication::keyboardModifiers());
             d->mouseMoveEvent(&fake);
 #endif
         } else {
             if (!d->layout->expanded)
                 break;
             QWidget *w = QApplication::activePopupWidget();
             if (waitForPopup(this, w)) {
                 d->waitForPopupTimer.start(POPUP_TIMER_INTERVAL, this);
                 break;
             }
             d->waitForPopupTimer.stop();
             d->layout->setExpanded(false);
             break;
         }
     default:
         break;
     }
     return QWidget::event(event);
 }
iconSize()
QSize QToolBar::iconSize () const
size of icons in the toolbar.
The default size is determined by the application's style and is derived from the QStyle::PM_ToolBarIconSize pixel metric. It is the maximum size an icon can have. Icons of smaller size will not be scaled up.
Definition at line 785 of file qtoolbar.cpp.
Referenced by QToolBarLayout::createItem(), and setIconSize().
 { Q_D(const QToolBar); return d->iconSize; }
iconSizeChanged
void QToolBar::iconSizeChanged (const QSize & iconSize) signal
This signal is emitted when the icon size is changed.
The iconSize parameter holds the toolbar's new icon size.
See also
iconSize QMainWindow::iconSize
Referenced by setIconSize().
initStyleOption()
void QToolBar::initStyleOption (QStyleOptionToolBar * option) const protected
Warning
This function is not part of the public interface.
Definition at line 1374 of file qtoolbar.cpp.
Referenced by event(), QToolBarLayout::expandedSize(), QToolBarLayout::layoutActions(), paintEvent(), QToolBarLayout::setGeometry(), QToolBarLayout::updateGeomArray(), and QToolBarLayout::updateMarginAndSpacing().
 {
     Q_D(const QToolBar);
     if (!option)
         return;
     option->initFrom(this);
     if (orientation() == Qt::Horizontal)
         option->state |= QStyle::State_Horizontal;
     option->lineWidth = style()->pixelMetric(QStyle::PM_ToolBarFrameWidth, 0, this);
     option->features = d->layout->movable()
                         ? QStyleOptionToolBar::Movable
                         : QStyleOptionToolBar::None;
     // if the tool bar is not in a QMainWindow, this will make the painting right
     option->toolBarArea = Qt::NoToolBarArea;
     // Add more styleoptions if the toolbar has been added to a mainwindow.
     QMainWindow *mainWindow = qobject_cast<QMainWindow *>(parentWidget());
     if (!mainWindow)
         return;
     QMainWindowLayout *layout = qt_mainwindow_layout(mainWindow);
     Q_ASSERT_X(layout != 0, "QToolBar::initStyleOption()",
                "QMainWindow->layout() != QMainWindowLayout");
     layout->getStyleOptionInfo(option, const_cast<QToolBar *>(this));
 }
insertSeparator()
QAction * QToolBar::insertSeparator (QAction * before)
Inserts a separator into the toolbar in front of the toolbar item associated with the before action.
See also
addSeparator()
Definition at line 950 of file qtoolbar.cpp.
 {
     QAction *action = new QAction(this);
     action->setSeparator(true);
     insertAction(before, action);
     return action;
 }
insertWidget()
QAction * QToolBar::insertWidget (QAction * before, QWidget * widget)
Inserts the given widget in front of the toolbar item associated with the before action.
Note: You should use QAction::setVisible() to change the visibility of the widget. Using QWidget::setVisible(), QWidget::show() and QWidget::hide() does not work.
See also
addWidget()
Definition at line 992 of file qtoolbar.cpp.
 {
     QWidgetAction *action = new QWidgetAction(this);
     action->setDefaultWidget(widget);
     action->d_func()->autoCreated = true;
     insertAction(before, action);
     return action;
 }
isAreaAllowed()
bool QToolBar::isAreaAllowed (Qt::ToolBarArea area) const inline
Returns true if this toolbar is dockable in the given area; otherwise returns false.
Definition at line 88 of file qtoolbar.h.
     { return (allowedAreas() & area) == area; }
isFloatable()
bool QToolBar::isFloatable () const
Definition at line 671 of file qtoolbar.cpp.
 {
     Q_D(const QToolBar);
     return d->floatable;
 }
isFloating()
bool QToolBar::isFloating () const
Definition at line 694 of file qtoolbar.cpp.
Referenced by QToolBarLayout::checkUsePopupMenu().
 {
     return isWindow();
 }
isMovable()
bool QToolBar::isMovable () const
Definition at line 656 of file qtoolbar.cpp.
Referenced by QMainWindowLayout::insertIntoMacToolbar(), and QToolBarLayout::movable().
 {
     Q_D(const QToolBar);
     return d->movable;
 }
movableChanged
void QToolBar::movableChanged (bool movable) signal
This signal is emitted when the toolbar becomes movable or fixed.
If the toolbar can be moved, movable is true; otherwise it is false.
See also
movable
Referenced by setMovable().
orientation()
Qt::Orientation QToolBar::orientation () const
orientation of the toolbar
The default is Qt::Horizontal.
This function should not be used when the toolbar is managed by QMainWindow. You can use QMainWindow::addToolBar() or QMainWindow::insertToolBar() if you wish to move a toolbar (that is already added to a main window) to another Qt::ToolBarArea.
Definition at line 769 of file qtoolbar.cpp.
Referenced by QPushButtonPrivate::adjustedMenuPosition(), QToolBarLayout::checkUsePopupMenu(), QToolBarLayout::expandedSize(), QToolBarLayout::expandingDirections(), fixToolBarOrientation(), initStyleOption(), QToolBarLayout::layoutActions(), QToolButtonPrivate::popupTimerDone(), QToolBarLayout::setGeometry(), setOrientation(), and QToolBarLayout::updateGeomArray().
 { Q_D(const QToolBar); return d->orientation; }
orientationChanged
void QToolBar::orientationChanged (Qt::Orientation orientation) signal
This signal is emitted when the orientation of the toolbar changes.
The new orientation is specified by the orientation given.
See also
orientation
Referenced by setOrientation().
paintEvent()
void QToolBar::paintEvent (QPaintEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1114 of file qtoolbar.cpp.
 {
     Q_D(QToolBar);
     QPainter p(this);
     QStyle *style = this->style();
     QStyleOptionToolBar opt;
     initStyleOption(&opt);
     if (d->layout->expanded || d->layout->animating || isWindow()) {
         //if the toolbar is expended, we need to fill the background with the window color
         //because some styles may expects that.
         p.fillRect(opt.rect, palette().background());
         style->drawControl(QStyle::CE_ToolBar, &opt, &p, this);
         style->drawPrimitive(QStyle::PE_FrameMenu, &opt, &p, this);
     } else {
         style->drawControl(QStyle::CE_ToolBar, &opt, &p, this);
     }
     opt.rect = style->subElementRect(QStyle::SE_ToolBarHandle, &opt, this);
     if (opt.rect.isValid())
         style->drawPrimitive(QStyle::PE_IndicatorToolBarHandle, &opt, &p, this);
 }
resizeEvent()
void QToolBar::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1415 of file qtoolbar.cpp.
 {
     QWidget::resizeEvent(event);
 }
setAllowedAreas()
void QToolBar::setAllowedAreas (Qt::ToolBarAreas areas)
Definition at line 714 of file qtoolbar.cpp.
 {
     Q_D(QToolBar);
     areas &= Qt::ToolBarArea_Mask;
     if (areas == d->allowedAreas)
         return;
     d->allowedAreas = areas;
     emit allowedAreasChanged(d->allowedAreas);
 }
setFloatable()
void QToolBar::setFloatable (bool floatable)
Definition at line 677 of file qtoolbar.cpp.
 {
     Q_D(QToolBar);
     d->floatable = floatable;
 }
setIconSize
void QToolBar::setIconSize (const QSize & iconSize) slot
Definition at line 788 of file qtoolbar.cpp.
Referenced by changeEvent().
 {
     Q_D(QToolBar);
     QSize sz = iconSize;
     if (!sz.isValid()) {
         QMainWindow *mw = qobject_cast<QMainWindow *>(parentWidget());
         if (mw && mw->layout()) {
             QLayout *layout = mw->layout();
             int i = 0;
             QLayoutItem *item = 0;
             do {
                 item = layout->itemAt(i++);
                 if (item && (item->widget() == this))
                     sz = mw->iconSize();
             } while (!sz.isValid() && item != 0);
         }
     }
     if (!sz.isValid()) {
         const int metric = style()->pixelMetric(QStyle::PM_ToolBarIconSize, 0, this);
         sz = QSize(metric, metric);
     }
     if (d->iconSize != sz) {
         d->iconSize = sz;
         setMinimumSize(0, 0);
         emit iconSizeChanged(d->iconSize);
     }
     d->explicitIconSize = iconSize.isValid();
     d->layout->invalidate();
 }
setMovable()
void QToolBar::setMovable (bool movable)
Definition at line 646 of file qtoolbar.cpp.
Referenced by QMainWindowLayout::insertIntoMacToolbar(), and QMainWindowLayout::removeFromMacToolbar().
 {
     Q_D(QToolBar);
     if (!movable == !d->movable)
         return;
     d->movable = movable;
     d->layout->invalidate();
     emit movableChanged(d->movable);
 }
setOrientation()
void QToolBar::setOrientation (Qt::Orientation orientation)
Definition at line 750 of file qtoolbar.cpp.
Referenced by fixToolBarOrientation(), QToolBarAreaLayoutInfo::insertToolBar(), and QToolBarAreaLayout::restoreState().
 {
     Q_D(QToolBar);
     if (orientation == d->orientation)
         return;
     d->orientation = orientation;
     if (orientation == Qt::Vertical)
     setSizePolicy(QSizePolicy(QSizePolicy::Fixed, QSizePolicy::Preferred));
     else
     setSizePolicy(QSizePolicy(QSizePolicy::Preferred, QSizePolicy::Fixed));
     d->layout->invalidate();
     d->layout->activate();
     emit orientationChanged(d->orientation);
 }
setToolButtonStyle
void QToolBar::setToolButtonStyle (Qt::ToolButtonStyle toolButtonStyle) slot
Definition at line 836 of file qtoolbar.cpp.
 {
     Q_D(QToolBar);
     d->explicitToolButtonStyle = true;
     if (d->toolButtonStyle == toolButtonStyle)
         return;
     d->toolButtonStyle = toolButtonStyle;
     setMinimumSize(0, 0);
     emit toolButtonStyleChanged(d->toolButtonStyle);
 }
toggleViewAction()
QAction * QToolBar::toggleViewAction () const
Returns a checkable action that can be used to show or hide this toolbar.
The action's text is set to the toolbar's window title.
See also
QAction::text QWidget::windowTitle
Definition at line 1327 of file qtoolbar.cpp.
Referenced by QMainWindow::createPopupMenu().
 { Q_D(const QToolBar); return d->toggleViewAction; }
toolButtonStyle()
Qt::ToolButtonStyle QToolBar::toolButtonStyle () const
Referenced by setIconSize(), and setToolButtonStyle().
toolButtonStyleChanged
void QToolBar::toolButtonStyleChanged (Qt::ToolButtonStyle toolButtonStyle) signal
This signal is emitted when the tool button style is changed.
The toolButtonStyle parameter holds the toolbar's new tool button style.
See also
toolButtonStyle QMainWindow::toolButtonStyle
Referenced by setToolButtonStyle().
topLevelChanged
void QToolBar::topLevelChanged (bool topLevel) signal
This signal is emitted when the floating property changes.
Since
4.6
The topLevel parameter is true if the toolbar is now floating; otherwise it is false.
See also
isWindow()
visibilityChanged
void QToolBar::visibilityChanged (bool visible) signal
This signal is emitted when the toolbar becomes visible (or invisible).
Since
4.7
This happens when the widget is hidden or shown.
Referenced by event().
widgetForAction()
QWidget * QToolBar::widgetForAction (QAction * action) const
Returns the widget associated with the specified action.
Since
4.2
See also
addWidget()
Definition at line 1358 of file qtoolbar.cpp.
Referenced by QPrintPreviewDialogPrivate::init().
 {
     Q_D(const QToolBar);
     int index = d->layout->indexOf(action);
     if (index == -1)
         return 0;
     return d->layout->itemAt(index)->widget();
 }
Friends and Related Functions
QMainWindow
friend class QMainWindow friend
Definition at line 169 of file qtoolbar.h.
QMainWindowLayout
friend class QMainWindowLayout friend
Definition at line 170 of file qtoolbar.h.
QToolBarAreaLayout
friend class QToolBarAreaLayout friend
Definition at line 172 of file qtoolbar.h.
QToolBarLayout
friend class QToolBarLayout friend
Definition at line 171 of file qtoolbar.h.
Properties
floatable
QToolBar::floatable private
whether the toolbar can be dragged and dropped as an independent window.
The default is true.
Definition at line 75 of file qtoolbar.h.
Referenced by setFloatable().
floating
QToolBar::floating private
whether the toolbar is an independent window.
By default, this property is true.
See also
QWidget::isWindow()
Definition at line 74 of file qtoolbar.h.
movable
QToolBar::movable private
whether the user can move the toolbar within the toolbar area, or between toolbar areas
By default, this property is true.
This property only makes sense if the toolbar is in a QMainWindow.
See also
allowedAreas
Definition at line 66 of file qtoolbar.h.
Referenced by setMovable().
toolButtonStyle
Qt::ToolButtonStyle QToolBar::toolButtonStyle private
Initial value:
== 0)
               NOTIFY orientationChanged)
    QSize iconSize
the style of toolbar buttons
This property defines the style of all tool buttons that are added as QAction. Note that if you add a QToolButton with the addWidget() method, it will not get this button style.
The default is Qt::ToolButtonIconOnly.
Definition at line 70 of file qtoolbar.h.
Referenced by QToolBarLayout::createItem().
The documentation for this class was generated from the following files:
/src/gui/widgets/qtoolbar.h
/src/gui/widgets/qtoolbar.cpp