Qt 4.8: QWindowsStyle Class Reference
QWindowsStyle Class Reference
The QWindowsStyle class provides a Microsoft Windows-like look and feel.
#include <qwindowsstyle.h>
Public Functions
void drawComplexControl (ComplexControl cc, const QStyleOptionComplex *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawControl (ControlElement element, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
void drawPrimitive (PrimitiveElement pe, const QStyleOption *opt, QPainter *p, const QWidget *w=0) const
Reimplemented Function
int pixelMetric (PixelMetric pm, const QStyleOption *option=0, const QWidget *widget=0) const
Reimplemented Function
void polish (QApplication *)
Reimplemented Function
void polish (QWidget *)
Reimplemented Function
void polish (QPalette &)
Reimplemented Function
QWindowsStyle ()
Constructs a QWindowsStyle object.
QSize sizeFromContents (ContentsType ct, const QStyleOption *opt, const QSize &contentsSize, const QWidget *widget=0) const
Reimplemented Function
QPixmap standardPixmap (StandardPixmap standardPixmap, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
int styleHint (StyleHint hint, const QStyleOption *opt=0, const QWidget *widget=0, QStyleHintReturn *returnData=0) const
Reimplemented Function
QRect subElementRect (SubElement r, const QStyleOption *opt, const QWidget *widget=0) const
Reimplemented Function
void unpolish (QApplication *)
Reimplemented Function
void unpolish (QWidget *)
Reimplemented Function
~QWindowsStyle ()
Destroys the QWindowsStyle object.
Public Functions inherited from QCommonStyle
QPixmap generatedIconPixmap (QIcon::Mode iconMode, const QPixmap &pixmap, const QStyleOption *opt) const
Reimplemented Function
SubControl hitTestComplexControl (ComplexControl cc, const QStyleOptionComplex *opt, const QPoint &pt, const QWidget *w=0) const
Reimplemented Function
QCommonStyle ()
Constructs a QCommonStyle.
QRect subControlRect (ComplexControl cc, const QStyleOptionComplex *opt, SubControl sc, const QWidget *w=0) const
Reimplemented Function
~QCommonStyle ()
Destroys the style.
Public Functions inherited from QStyle
int combinedLayoutSpacing (QSizePolicy::ControlTypes controls1, QSizePolicy::ControlTypes controls2, Qt::Orientation orientation, QStyleOption *option=0, QWidget *widget=0) const
Returns the spacing that should be used between controls1 and controls2 in a layout.
virtual void drawItemPixmap (QPainter *painter, const QRect &rect, int alignment, const QPixmap &pixmap) const
Draws the given pixmap in the specified rectangle, according to the specified alignment, using the provided painter.
virtual void drawItemText (QPainter *painter, const QRect &rect, int flags, const QPalette &pal, bool enabled, const QString &text, QPalette::ColorRole textRole=QPalette::NoRole) const
Draws the given text in the specified rectangle using the provided painter and palette.
virtual QRect itemPixmapRect (const QRect &r, int flags, const QPixmap &pixmap) const
Returns the area within the given rectangle in which to draw the specified pixmap according to the defined alignment.
virtual QRect itemTextRect (const QFontMetrics &fm, const QRect &r, int flags, bool enabled, const QString &text) const
Returns the area within the given rectangle in which to draw the provided text according to the specified font metrics and alignment.
int layoutSpacing (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
Returns the spacing that should be used between control1 and control2 in a layout.
const QStyle * proxy () const
QStyle ()
Constructs a style object.
QIcon standardIcon (StandardPixmap standardIcon, const QStyleOption *option=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
virtual QPalette standardPalette () const
Returns the style's standard palette.
virtual ~QStyle ()
Destroys the style object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *option, const QWidget *widget=0) const
Protected Slots inherited from QCommonStyle
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Protected Slots inherited from QStyle
int layoutSpacingImplementation (QSizePolicy::ControlType control1, QSizePolicy::ControlType control2, Qt::Orientation orientation, const QStyleOption *option=0, const QWidget *widget=0) const
This slot is called by layoutSpacing() to determine the spacing that should be used between control1 and control2 in a layout.
QIcon standardIconImplementation (StandardPixmap standardIcon, const QStyleOption *opt=0, const QWidget *widget=0) const
Returns an icon for the given standardIcon.
Protected Functions
bool eventFilter (QObject *o, QEvent *e)
Reimplemented Function
QWindowsStyle (QWindowsStylePrivate &dd)
Constructs a QWindowsStyle object.
void timerEvent (QTimerEvent *event)
Reimplemented Function
Protected Functions inherited from QCommonStyle
QCommonStyle (QCommonStylePrivate &dd)
Protected Functions inherited from QStyle
QStyle (QStylePrivate &dd)
Constructs a style object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Properties
void * reserved
Additional Inherited Members
Public Types inherited from QStyle
enum ComplexControl {
CC_SpinBox, CC_ComboBox, CC_ScrollBar, CC_Slider,
CC_ToolButton, CC_TitleBar, CC_Q3ListView, CC_Dial,
CC_GroupBox, CC_MdiControls, CC_CustomBase = 0xf0000000
}
This enum describes the available complex controls.
enum ContentsType {
CT_PushButton, CT_CheckBox, CT_RadioButton, CT_ToolButton,
CT_ComboBox, CT_Splitter, CT_Q3DockWindow, CT_ProgressBar,
CT_MenuItem, CT_MenuBarItem, CT_MenuBar, CT_Menu,
CT_TabBarTab, CT_Slider, CT_ScrollBar, CT_Q3Header,
CT_LineEdit, CT_SpinBox, CT_SizeGrip, CT_TabWidget,
CT_DialogButtons, CT_HeaderSection, CT_GroupBox, CT_MdiControls,
CT_ItemViewItem, CT_CustomBase = 0xf0000000
}
This enum describes the available contents types.
enum ControlElement {
CE_PushButton, CE_PushButtonBevel, CE_PushButtonLabel, CE_CheckBox,
CE_CheckBoxLabel, CE_RadioButton, CE_RadioButtonLabel, CE_TabBarTab,
CE_TabBarTabShape, CE_TabBarTabLabel, CE_ProgressBar, CE_ProgressBarGroove,
CE_ProgressBarContents, CE_ProgressBarLabel, CE_MenuItem, CE_MenuScroller,
CE_MenuVMargin, CE_MenuHMargin, CE_MenuTearoff, CE_MenuEmptyArea,
CE_MenuBarItem, CE_MenuBarEmptyArea, CE_ToolButtonLabel, CE_Header,
CE_HeaderSection, CE_HeaderLabel, CE_Q3DockWindowEmptyArea, CE_ToolBoxTab,
CE_SizeGrip, CE_Splitter, CE_RubberBand, CE_DockWidgetTitle,
CE_ScrollBarAddLine, CE_ScrollBarSubLine, CE_ScrollBarAddPage, CE_ScrollBarSubPage,
CE_ScrollBarSlider, CE_ScrollBarFirst, CE_ScrollBarLast, CE_FocusFrame,
CE_ComboBoxLabel, CE_ToolBar, CE_ToolBoxTabShape, CE_ToolBoxTabLabel,
CE_HeaderEmptyArea, CE_ColumnViewGrip, CE_ItemViewItem, CE_ShapedFrame,
CE_CustomBase = 0xf0000000
}
This enum represents a control element.
enum PixelMetric {
PM_ButtonMargin, PM_ButtonDefaultIndicator, PM_MenuButtonIndicator, PM_ButtonShiftHorizontal,
PM_ButtonShiftVertical, PM_DefaultFrameWidth, PM_SpinBoxFrameWidth, PM_ComboBoxFrameWidth,
PM_MaximumDragDistance, PM_ScrollBarExtent, PM_ScrollBarSliderMin, PM_SliderThickness,
PM_SliderControlThickness, PM_SliderLength, PM_SliderTickmarkOffset, PM_SliderSpaceAvailable,
PM_DockWidgetSeparatorExtent, PM_DockWidgetHandleExtent, PM_DockWidgetFrameWidth, PM_TabBarTabOverlap,
PM_TabBarTabHSpace, PM_TabBarTabVSpace, PM_TabBarBaseHeight, PM_TabBarBaseOverlap,
PM_ProgressBarChunkWidth, PM_SplitterWidth, PM_TitleBarHeight, PM_MenuScrollerHeight,
PM_MenuHMargin, PM_MenuVMargin, PM_MenuPanelWidth, PM_MenuTearoffHeight,
PM_MenuDesktopFrameWidth, PM_MenuBarPanelWidth, PM_MenuBarItemSpacing, PM_MenuBarVMargin,
PM_MenuBarHMargin, PM_IndicatorWidth, PM_IndicatorHeight, PM_ExclusiveIndicatorWidth,
PM_ExclusiveIndicatorHeight, PM_CheckListButtonSize, PM_CheckListControllerSize, PM_DialogButtonsSeparator,
PM_DialogButtonsButtonWidth, PM_DialogButtonsButtonHeight, PM_MdiSubWindowFrameWidth, PM_MDIFrameWidth = PM_MdiSubWindowFrameWidth,
PM_MdiSubWindowMinimizedWidth, PM_MDIMinimizedWidth = PM_MdiSubWindowMinimizedWidth, PM_HeaderMargin, PM_HeaderMarkSize,
PM_HeaderGripMargin, PM_TabBarTabShiftHorizontal, PM_TabBarTabShiftVertical, PM_TabBarScrollButtonWidth,
PM_ToolBarFrameWidth, PM_ToolBarHandleExtent, PM_ToolBarItemSpacing, PM_ToolBarItemMargin,
PM_ToolBarSeparatorExtent, PM_ToolBarExtensionExtent, PM_SpinBoxSliderHeight, PM_DefaultTopLevelMargin,
PM_DefaultChildMargin, PM_DefaultLayoutSpacing, PM_ToolBarIconSize, PM_ListViewIconSize,
PM_IconViewIconSize, PM_SmallIconSize, PM_LargeIconSize, PM_FocusFrameVMargin,
PM_FocusFrameHMargin, PM_ToolTipLabelFrameWidth, PM_CheckBoxLabelSpacing, PM_TabBarIconSize,
PM_SizeGripSize, PM_DockWidgetTitleMargin, PM_MessageBoxIconSize, PM_ButtonIconSize,
PM_DockWidgetTitleBarButtonMargin, PM_RadioButtonLabelSpacing, PM_LayoutLeftMargin, PM_LayoutTopMargin,
PM_LayoutRightMargin, PM_LayoutBottomMargin, PM_LayoutHorizontalSpacing, PM_LayoutVerticalSpacing,
PM_TabBar_ScrollButtonOverlap, PM_TextCursorWidth, PM_TabCloseIndicatorWidth, PM_TabCloseIndicatorHeight,
PM_ScrollView_ScrollBarSpacing, PM_SubMenuOverlap, PM_CustomBase = 0xf0000000
}
This enum describes the various available pixel metrics.
enum PrimitiveElement {
PE_Q3CheckListController, PE_Q3CheckListExclusiveIndicator, PE_Q3CheckListIndicator, PE_Q3DockWindowSeparator,
PE_Q3Separator, PE_Frame, PE_FrameDefaultButton, PE_FrameDockWidget,
PE_FrameFocusRect, PE_FrameGroupBox, PE_FrameLineEdit, PE_FrameMenu,
PE_FrameStatusBar, PE_FrameStatusBarItem = PE_FrameStatusBar, PE_FrameTabWidget, PE_FrameWindow,
PE_FrameButtonBevel, PE_FrameButtonTool, PE_FrameTabBarBase, PE_PanelButtonCommand,
PE_PanelButtonBevel, PE_PanelButtonTool, PE_PanelMenuBar, PE_PanelToolBar,
PE_PanelLineEdit, PE_IndicatorArrowDown, PE_IndicatorArrowLeft, PE_IndicatorArrowRight,
PE_IndicatorArrowUp, PE_IndicatorBranch, PE_IndicatorButtonDropDown, PE_IndicatorViewItemCheck,
PE_IndicatorItemViewItemCheck = PE_IndicatorViewItemCheck, PE_IndicatorCheckBox, PE_IndicatorDockWidgetResizeHandle, PE_IndicatorHeaderArrow,
PE_IndicatorMenuCheckMark, PE_IndicatorProgressChunk, PE_IndicatorRadioButton, PE_IndicatorSpinDown,
PE_IndicatorSpinMinus, PE_IndicatorSpinPlus, PE_IndicatorSpinUp, PE_IndicatorToolBarHandle,
PE_IndicatorToolBarSeparator, PE_PanelTipLabel, PE_IndicatorTabTear, PE_PanelScrollAreaCorner,
PE_Widget, PE_IndicatorColumnViewArrow, PE_IndicatorItemViewItemDrop, PE_PanelItemViewItem,
PE_PanelItemViewRow, PE_PanelStatusBar, PE_IndicatorTabClose, PE_PanelMenu,
PE_CustomBase = 0xf000000
}
This enum describes the various primitive elements.
enum RequestSoftwareInputPanel { RSIP_OnMouseClickAndAlreadyFocused, RSIP_OnMouseClick }
This enum describes under what circumstances a software input panel will be requested by input capable widgets.
enum StandardPixmap {
SP_TitleBarMenuButton, SP_TitleBarMinButton, SP_TitleBarMaxButton, SP_TitleBarCloseButton,
SP_TitleBarNormalButton, SP_TitleBarShadeButton, SP_TitleBarUnshadeButton, SP_TitleBarContextHelpButton,
SP_DockWidgetCloseButton, SP_MessageBoxInformation, SP_MessageBoxWarning, SP_MessageBoxCritical,
SP_MessageBoxQuestion, SP_DesktopIcon, SP_TrashIcon, SP_ComputerIcon,
SP_DriveFDIcon, SP_DriveHDIcon, SP_DriveCDIcon, SP_DriveDVDIcon,
SP_DriveNetIcon, SP_DirOpenIcon, SP_DirClosedIcon, SP_DirLinkIcon,
SP_FileIcon, SP_FileLinkIcon, SP_ToolBarHorizontalExtensionButton, SP_ToolBarVerticalExtensionButton,
SP_FileDialogStart, SP_FileDialogEnd, SP_FileDialogToParent, SP_FileDialogNewFolder,
SP_FileDialogDetailedView, SP_FileDialogInfoView, SP_FileDialogContentsView, SP_FileDialogListView,
SP_FileDialogBack, SP_DirIcon, SP_DialogOkButton, SP_DialogCancelButton,
SP_DialogHelpButton, SP_DialogOpenButton, SP_DialogSaveButton, SP_DialogCloseButton,
SP_DialogApplyButton, SP_DialogResetButton, SP_DialogDiscardButton, SP_DialogYesButton,
SP_DialogNoButton, SP_ArrowUp, SP_ArrowDown, SP_ArrowLeft,
SP_ArrowRight, SP_ArrowBack, SP_ArrowForward, SP_DirHomeIcon,
SP_CommandLink, SP_VistaShield, SP_BrowserReload, SP_BrowserStop,
SP_MediaPlay, SP_MediaStop, SP_MediaPause, SP_MediaSkipForward,
SP_MediaSkipBackward, SP_MediaSeekForward, SP_MediaSeekBackward, SP_MediaVolume,
SP_MediaVolumeMuted, SP_CustomBase = 0xf0000000
}
This enum describes the available standard pixmaps.
enum StateFlag {
State_None = 0x00000000, State_Enabled = 0x00000001, State_Raised = 0x00000002, State_Sunken = 0x00000004,
State_Off = 0x00000008, State_NoChange = 0x00000010, State_On = 0x00000020, State_DownArrow = 0x00000040,
State_Horizontal = 0x00000080, State_HasFocus = 0x00000100, State_Top = 0x00000200, State_Bottom = 0x00000400,
State_FocusAtBorder = 0x00000800, State_AutoRaise = 0x00001000, State_MouseOver = 0x00002000, State_UpArrow = 0x00004000,
State_Selected = 0x00008000, State_Active = 0x00010000, State_Window = 0x00020000, State_Open = 0x00040000,
State_Children = 0x00080000, State_Item = 0x00100000, State_Sibling = 0x00200000, State_Editing = 0x00400000,
State_KeyboardFocusChange = 0x00800000, State_ReadOnly = 0x02000000, State_Small = 0x04000000, State_Mini = 0x08000000
}
This enum describes flags that are used when drawing primitive elements.
enum StyleHint {
SH_EtchDisabledText, SH_DitherDisabledText, SH_ScrollBar_MiddleClickAbsolutePosition, SH_ScrollBar_ScrollWhenPointerLeavesControl,
SH_TabBar_SelectMouseType, SH_TabBar_Alignment, SH_Header_ArrowAlignment, SH_Slider_SnapToValue,
SH_Slider_SloppyKeyEvents, SH_ProgressDialog_CenterCancelButton, SH_ProgressDialog_TextLabelAlignment, SH_PrintDialog_RightAlignButtons,
SH_MainWindow_SpaceBelowMenuBar, SH_FontDialog_SelectAssociatedText, SH_Menu_AllowActiveAndDisabled, SH_Menu_SpaceActivatesItem,
SH_Menu_SubMenuPopupDelay, SH_ScrollView_FrameOnlyAroundContents, SH_MenuBar_AltKeyNavigation, SH_ComboBox_ListMouseTracking,
SH_Menu_MouseTracking, SH_MenuBar_MouseTracking, SH_ItemView_ChangeHighlightOnFocus, SH_Widget_ShareActivation,
SH_Workspace_FillSpaceOnMaximize, SH_ComboBox_Popup, SH_TitleBar_NoBorder, SH_Slider_StopMouseOverSlider,
SH_ScrollBar_StopMouseOverSlider = SH_Slider_StopMouseOverSlider, SH_BlinkCursorWhenTextSelected, SH_RichText_FullWidthSelection, SH_Menu_Scrollable,
SH_GroupBox_TextLabelVerticalAlignment, SH_GroupBox_TextLabelColor, SH_Menu_SloppySubMenus, SH_Table_GridLineColor,
SH_LineEdit_PasswordCharacter, SH_DialogButtons_DefaultButton, SH_ToolBox_SelectedPageTitleBold, SH_TabBar_PreferNoArrows,
SH_ScrollBar_LeftClickAbsolutePosition, SH_Q3ListViewExpand_SelectMouseType, SH_UnderlineShortcut, SH_SpinBox_AnimateButton,
SH_SpinBox_KeyPressAutoRepeatRate, SH_SpinBox_ClickAutoRepeatRate, SH_Menu_FillScreenWithScroll, SH_ToolTipLabel_Opacity,
SH_DrawMenuBarSeparator, SH_TitleBar_ModifyNotification, SH_Button_FocusPolicy, SH_MenuBar_DismissOnSecondClick,
SH_MessageBox_UseBorderForButtonSpacing, SH_TitleBar_AutoRaise, SH_ToolButton_PopupDelay, SH_FocusFrame_Mask,
SH_RubberBand_Mask, SH_WindowFrame_Mask, SH_SpinControls_DisableOnBounds, SH_Dial_BackgroundRole,
SH_ComboBox_LayoutDirection, SH_ItemView_EllipsisLocation, SH_ItemView_ShowDecorationSelected, SH_ItemView_ActivateItemOnSingleClick,
SH_ScrollBar_ContextMenu, SH_ScrollBar_RollBetweenButtons, SH_Slider_AbsoluteSetButtons, SH_Slider_PageSetButtons,
SH_Menu_KeyboardSearch, SH_TabBar_ElideMode, SH_DialogButtonLayout, SH_ComboBox_PopupFrameStyle,
SH_MessageBox_TextInteractionFlags, SH_DialogButtonBox_ButtonsHaveIcons, SH_SpellCheckUnderlineStyle, SH_MessageBox_CenterButtons,
SH_Menu_SelectionWrap, SH_ItemView_MovementWithoutUpdatingSelection, SH_ToolTip_Mask, SH_FocusFrame_AboveWidget,
SH_TextControl_FocusIndicatorTextCharFormat, SH_WizardStyle, SH_ItemView_ArrowKeysNavigateIntoChildren, SH_Menu_Mask,
SH_Menu_FlashTriggeredItem, SH_Menu_FadeOutOnHide, SH_SpinBox_ClickAutoRepeatThreshold, SH_ItemView_PaintAlternatingRowColorsForEmptyArea,
SH_FormLayoutWrapPolicy, SH_TabWidget_DefaultTabPosition, SH_ToolBar_Movable, SH_FormLayoutFieldGrowthPolicy,
SH_FormLayoutFormAlignment, SH_FormLayoutLabelAlignment, SH_ItemView_DrawDelegateFrame, SH_TabBar_CloseButtonPosition,
SH_DockWidget_ButtonsHaveFrame, SH_ToolButtonStyle, SH_RequestSoftwareInputPanel, SH_CustomBase = 0xf0000000
}
This enum describes the available style hints.
enum SubControl {
SC_None = 0x00000000, SC_ScrollBarAddLine = 0x00000001, SC_ScrollBarSubLine = 0x00000002, SC_ScrollBarAddPage = 0x00000004,
SC_ScrollBarSubPage = 0x00000008, SC_ScrollBarFirst = 0x00000010, SC_ScrollBarLast = 0x00000020, SC_ScrollBarSlider = 0x00000040,
SC_ScrollBarGroove = 0x00000080, SC_SpinBoxUp = 0x00000001, SC_SpinBoxDown = 0x00000002, SC_SpinBoxFrame = 0x00000004,
SC_SpinBoxEditField = 0x00000008, SC_ComboBoxFrame = 0x00000001, SC_ComboBoxEditField = 0x00000002, SC_ComboBoxArrow = 0x00000004,
SC_ComboBoxListBoxPopup = 0x00000008, SC_SliderGroove = 0x00000001, SC_SliderHandle = 0x00000002, SC_SliderTickmarks = 0x00000004,
SC_ToolButton = 0x00000001, SC_ToolButtonMenu = 0x00000002, SC_TitleBarSysMenu = 0x00000001, SC_TitleBarMinButton = 0x00000002,
SC_TitleBarMaxButton = 0x00000004, SC_TitleBarCloseButton = 0x00000008, SC_TitleBarNormalButton = 0x00000010, SC_TitleBarShadeButton = 0x00000020,
SC_TitleBarUnshadeButton = 0x00000040, SC_TitleBarContextHelpButton = 0x00000080, SC_TitleBarLabel = 0x00000100, SC_Q3ListView = 0x00000001,
SC_Q3ListViewBranch = 0x00000002, SC_Q3ListViewExpand = 0x00000004, SC_DialGroove = 0x00000001, SC_DialHandle = 0x00000002,
SC_DialTickmarks = 0x00000004, SC_GroupBoxCheckBox = 0x00000001, SC_GroupBoxLabel = 0x00000002, SC_GroupBoxContents = 0x00000004,
SC_GroupBoxFrame = 0x00000008, SC_MdiMinButton = 0x00000001, SC_MdiNormalButton = 0x00000002, SC_MdiCloseButton = 0x00000004,
SC_CustomBase = 0xf0000000, SC_All = 0xffffffff
}
This enum describes the available sub controls.
enum SubElement {
SE_PushButtonContents, SE_PushButtonFocusRect, SE_CheckBoxIndicator, SE_CheckBoxContents,
SE_CheckBoxFocusRect, SE_CheckBoxClickRect, SE_RadioButtonIndicator, SE_RadioButtonContents,
SE_RadioButtonFocusRect, SE_RadioButtonClickRect, SE_ComboBoxFocusRect, SE_SliderFocusRect,
SE_Q3DockWindowHandleRect, SE_ProgressBarGroove, SE_ProgressBarContents, SE_ProgressBarLabel,
SE_DialogButtonAccept, SE_DialogButtonReject, SE_DialogButtonApply, SE_DialogButtonHelp,
SE_DialogButtonAll, SE_DialogButtonAbort, SE_DialogButtonIgnore, SE_DialogButtonRetry,
SE_DialogButtonCustom, SE_ToolBoxTabContents, SE_HeaderLabel, SE_HeaderArrow,
SE_TabWidgetTabBar, SE_TabWidgetTabPane, SE_TabWidgetTabContents, SE_TabWidgetLeftCorner,
SE_TabWidgetRightCorner, SE_ViewItemCheckIndicator, SE_ItemViewItemCheckIndicator = SE_ViewItemCheckIndicator, SE_TabBarTearIndicator,
SE_TreeViewDisclosureItem, SE_LineEditContents, SE_FrameContents, SE_DockWidgetCloseButton,
SE_DockWidgetFloatButton, SE_DockWidgetTitleBarText, SE_DockWidgetIcon, SE_CheckBoxLayoutItem,
SE_ComboBoxLayoutItem, SE_DateTimeEditLayoutItem, SE_DialogButtonBoxLayoutItem, SE_LabelLayoutItem,
SE_ProgressBarLayoutItem, SE_PushButtonLayoutItem, SE_RadioButtonLayoutItem, SE_SliderLayoutItem,
SE_SpinBoxLayoutItem, SE_ToolButtonLayoutItem, SE_FrameLayoutItem, SE_GroupBoxLayoutItem,
SE_TabWidgetLayoutItem, SE_ItemViewItemDecoration, SE_ItemViewItemText, SE_ItemViewItemFocusRect,
SE_TabBarTabLeftButton, SE_TabBarTabRightButton, SE_TabBarTabText, SE_ShapedFrameContents,
SE_ToolBarHandle, SE_CustomBase = 0xf0000000
}
This enum represents a sub-area of a widget.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QStyle
static QRect alignedRect (Qt::LayoutDirection direction, Qt::Alignment alignment, const QSize &size, const QRect &rectangle)
Returns a new rectangle of the specified size that is aligned to the given rectangle according to the specified alignment and direction.
static int sliderPositionFromValue (int min, int max, int val, int space, bool upsideDown=false)
Converts the given logicalValue to a pixel position.
static int sliderValueFromPosition (int min, int max, int pos, int space, bool upsideDown=false)
Converts the given pixel position to a logical value.
static Qt::Alignment visualAlignment (Qt::LayoutDirection direction, Qt::Alignment alignment)
Transforms an alignment of Qt::AlignLeft or Qt::AlignRight without Qt::AlignAbsolute into Qt::AlignLeft or Qt::AlignRight with Qt::AlignAbsolute according to the layout direction.
static QPoint visualPos (Qt::LayoutDirection direction, const QRect &boundingRect, const QPoint &logicalPos)
Returns the given logicalPosition converted to screen coordinates based on the specified direction.
static QRect visualRect (Qt::LayoutDirection direction, const QRect &boundingRect, const QRect &logicalRect)
Returns the given logicalRectangle converted to screen coordinates based on the specified direction.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QWindowsStyle class provides a Microsoft Windows-like look and feel.
This style is Qt's default GUI style on Windows.
See also
QWindowsXPStyle, QMacStyle, QPlastiqueStyle, QCDEStyle, QMotifStyle
Definition at line 57 of file qwindowsstyle.h.
Constructors and Destructors
QWindowsStyle() [1/2]
QWindowsStyle::QWindowsStyle ()
Constructs a QWindowsStyle object.
Definition at line 279 of file qwindowsstyle.cpp.
                              : QCommonStyle(*new QWindowsStylePrivate)
 {
 }
~QWindowsStyle()
QWindowsStyle::~QWindowsStyle ()
Destroys the QWindowsStyle object.
Definition at line 297 of file qwindowsstyle.cpp.
 {
 }
QWindowsStyle() [2/2]
QWindowsStyle::QWindowsStyle (QWindowsStylePrivate & dd) protected
Constructs a QWindowsStyle object.
Warning
This function is not part of the public interface.
Definition at line 291 of file qwindowsstyle.cpp.
                                                      : QCommonStyle(dd)
 {
 }
Functions
drawComplexControl()
void QWindowsStyle::drawComplexControl (ComplexControl cc, const QStyleOptionComplex * opt, QPainter * p, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 2628 of file qwindowsstyle.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), and QMacStyle::drawComplexControl().
 {
     switch (cc) {
 #ifndef QT_NO_SLIDER
     case CC_Slider:
         if (const QStyleOptionSlider *slider = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             int thickness  = proxy()->pixelMetric(PM_SliderControlThickness, slider, widget);
             int len        = proxy()->pixelMetric(PM_SliderLength, slider, widget);
             int ticks = slider->tickPosition;
             QRect groove = proxy()->subControlRect(CC_Slider, slider, SC_SliderGroove, widget);
             QRect handle = proxy()->subControlRect(CC_Slider, slider, SC_SliderHandle, widget);
             if ((slider->subControls & SC_SliderGroove) && groove.isValid()) {
                 int mid = thickness / 2;
                 if (ticks & QSlider::TicksAbove)
                     mid += len / 8;
                 if (ticks & QSlider::TicksBelow)
                     mid -= len / 8;
                 p->setPen(slider->palette.shadow().color());
                 if (slider->orientation == Qt::Horizontal) {
                     qDrawWinPanel(p, groove.x(), groove.y() + mid - 2,
                                    groove.width(), 4, slider->palette, true);
                     p->drawLine(groove.x() + 1, groove.y() + mid - 1,
                                 groove.x() + groove.width() - 3, groove.y() + mid - 1);
                 } else {
                     qDrawWinPanel(p, groove.x() + mid - 2, groove.y(),
                                   4, groove.height(), slider->palette, true);
                     p->drawLine(groove.x() + mid - 1, groove.y() + 1,
                                 groove.x() + mid - 1, groove.y() + groove.height() - 3);
                 }
             }
             if (slider->subControls & SC_SliderTickmarks) {
                 QStyleOptionSlider tmpSlider = *slider;
                 tmpSlider.subControls = SC_SliderTickmarks;
                 QCommonStyle::drawComplexControl(cc, &tmpSlider, p, widget);
             }
             if (slider->subControls & SC_SliderHandle) {
                 // 4444440
                 // 4333310
                 // 4322210
                 // 4322210
                 // 4322210
                 // 4322210
                 // *43210*
                 // **410**
                 // ***0***
                 const QColor c0 = slider->palette.shadow().color();
                 const QColor c1 = slider->palette.dark().color();
                 // const QColor c2 = g.button();
                 const QColor c3 = slider->palette.midlight().color();
                 const QColor c4 = slider->palette.light().color();
                 QBrush handleBrush;
                 if (slider->state & State_Enabled) {
                     handleBrush = slider->palette.color(QPalette::Button);
                 } else {
                     handleBrush = QBrush(slider->palette.color(QPalette::Button),
                                          Qt::Dense4Pattern);
                 }
                 int x = handle.x(), y = handle.y(),
                    wi = handle.width(), he = handle.height();
                 int x1 = x;
                 int x2 = x+wi-1;
                 int y1 = y;
                 int y2 = y+he-1;
                 Qt::Orientation orient = slider->orientation;
                 bool tickAbove = slider->tickPosition == QSlider::TicksAbove;
                 bool tickBelow = slider->tickPosition == QSlider::TicksBelow;
                 if (slider->state & State_HasFocus) {
                     QStyleOptionFocusRect fropt;
                     fropt.QStyleOption::operator=(*slider);
                     fropt.rect = subElementRect(SE_SliderFocusRect, slider, widget);
                     proxy()->drawPrimitive(PE_FrameFocusRect, &fropt, p, widget);
                 }
                 if ((tickAbove && tickBelow) || (!tickAbove && !tickBelow)) {
                     Qt::BGMode oldMode = p->backgroundMode();
                     p->setBackgroundMode(Qt::OpaqueMode);
                     qDrawWinButton(p, QRect(x, y, wi, he), slider->palette, false,
                                    &handleBrush);
                     p->setBackgroundMode(oldMode);
                     return;
                 }
                 QSliderDirection dir;
                 if (orient == Qt::Horizontal)
                     if (tickAbove)
                         dir = SlUp;
                     else
                         dir = SlDown;
                 else
                     if (tickAbove)
                         dir = SlLeft;
                     else
                         dir = SlRight;
                 QPolygon a;
                 int d = 0;
                 switch (dir) {
                 case SlUp:
                     y1 = y1 + wi/2;
                     d =  (wi + 1) / 2 - 1;
                     a.setPoints(5, x1,y1, x1,y2, x2,y2, x2,y1, x1+d,y1-d);
                     break;
                 case SlDown:
                     y2 = y2 - wi/2;
                     d =  (wi + 1) / 2 - 1;
                     a.setPoints(5, x1,y1, x1,y2, x1+d,y2+d, x2,y2, x2,y1);
                     break;
                 case SlLeft:
                     d =  (he + 1) / 2 - 1;
                     x1 = x1 + he/2;
                     a.setPoints(5, x1,y1, x1-d,y1+d, x1,y2, x2,y2, x2,y1);
                     break;
                 case SlRight:
                     d =  (he + 1) / 2 - 1;
                     x2 = x2 - he/2;
                     a.setPoints(5, x1,y1, x1,y2, x2,y2, x2+d,y1+d, x2,y1);
                     break;
                 }
                 QBrush oldBrush = p->brush();
                 p->setPen(Qt::NoPen);
                 p->setBrush(handleBrush);
                 Qt::BGMode oldMode = p->backgroundMode();
                 p->setBackgroundMode(Qt::OpaqueMode);
                 p->drawRect(x1, y1, x2-x1+1, y2-y1+1);
                 p->drawPolygon(a);
                 p->setBrush(oldBrush);
                 p->setBackgroundMode(oldMode);
                 if (dir != SlUp) {
                     p->setPen(c4);
                     p->drawLine(x1, y1, x2, y1);
                     p->setPen(c3);
                     p->drawLine(x1, y1+1, x2, y1+1);
                 }
                 if (dir != SlLeft) {
                     p->setPen(c3);
                     p->drawLine(x1+1, y1+1, x1+1, y2);
                     p->setPen(c4);
                     p->drawLine(x1, y1, x1, y2);
                 }
                 if (dir != SlRight) {
                     p->setPen(c0);
                     p->drawLine(x2, y1, x2, y2);
                     p->setPen(c1);
                     p->drawLine(x2-1, y1+1, x2-1, y2-1);
                 }
                 if (dir != SlDown) {
                     p->setPen(c0);
                     p->drawLine(x1, y2, x2, y2);
                     p->setPen(c1);
                     p->drawLine(x1+1, y2-1, x2-1, y2-1);
                 }
                 switch (dir) {
                 case SlUp:
                     p->setPen(c4);
                     p->drawLine(x1, y1, x1+d, y1-d);
                     p->setPen(c0);
                     d = wi - d - 1;
                     p->drawLine(x2, y1, x2-d, y1-d);
                     d--;
                     p->setPen(c3);
                     p->drawLine(x1+1, y1, x1+1+d, y1-d);
                     p->setPen(c1);
                     p->drawLine(x2-1, y1, x2-1-d, y1-d);
                     break;
                 case SlDown:
                     p->setPen(c4);
                     p->drawLine(x1, y2, x1+d, y2+d);
                     p->setPen(c0);
                     d = wi - d - 1;
                     p->drawLine(x2, y2, x2-d, y2+d);
                     d--;
                     p->setPen(c3);
                     p->drawLine(x1+1, y2, x1+1+d, y2+d);
                     p->setPen(c1);
                     p->drawLine(x2-1, y2, x2-1-d, y2+d);
                     break;
                 case SlLeft:
                     p->setPen(c4);
                     p->drawLine(x1, y1, x1-d, y1+d);
                     p->setPen(c0);
                     d = he - d - 1;
                     p->drawLine(x1, y2, x1-d, y2-d);
                     d--;
                     p->setPen(c3);
                     p->drawLine(x1, y1+1, x1-d, y1+1+d);
                     p->setPen(c1);
                     p->drawLine(x1, y2-1, x1-d, y2-1-d);
                     break;
                 case SlRight:
                     p->setPen(c4);
                     p->drawLine(x2, y1, x2+d, y1+d);
                     p->setPen(c0);
                     d = he - d - 1;
                     p->drawLine(x2, y2, x2+d, y2-d);
                     d--;
                     p->setPen(c3);
                     p->drawLine(x2, y1+1, x2+d, y1+1+d);
                     p->setPen(c1);
                     p->drawLine(x2, y2-1, x2+d, y2-1-d);
                     break;
                 }
             }
         }
         break;
 #endif // QT_NO_SLIDER
 #ifndef QT_NO_SCROLLBAR
     case CC_ScrollBar:
         if (const QStyleOptionSlider *scrollbar = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             QStyleOptionSlider newScrollbar = *scrollbar;
             if (scrollbar->minimum == scrollbar->maximum)
                 newScrollbar.state &= ~State_Enabled; //do not draw the slider.
             QCommonStyle::drawComplexControl(cc, &newScrollbar, p, widget);
         }
         break;
 #endif // QT_NO_SCROLLBAR
 #ifdef QT3_SUPPORT
     case CC_Q3ListView:
         if (const QStyleOptionQ3ListView *lv = qstyleoption_cast<const QStyleOptionQ3ListView *>(opt)) {
             int i;
             if (lv->subControls & SC_Q3ListView)
                 QCommonStyle::drawComplexControl(cc, lv, p, widget);
             if (lv->subControls & (SC_Q3ListViewBranch | SC_Q3ListViewExpand)) {
                 if (lv->items.isEmpty())
                     break;
                 QStyleOptionQ3ListViewItem item = lv->items.at(0);
                 int y = lv->rect.y();
                 int c;
                 int dotoffset = 0;
                 QPolygon dotlines;
                 if ((lv->activeSubControls & SC_All) && (lv->subControls & SC_Q3ListViewExpand)) {
                     c = 2;
                     dotlines.resize(2);
                     dotlines[0] = QPoint(lv->rect.right(), lv->rect.top());
                     dotlines[1] = QPoint(lv->rect.right(), lv->rect.bottom());
                 } else {
                     int linetop = 0, linebot = 0;
                     // each branch needs at most two lines, ie. four end points
                     dotoffset = (item.itemY + item.height - y) % 2;
                     dotlines.resize(item.childCount * 4);
                     c = 0;
                     // skip the stuff above the exposed rectangle
                     for (i = 1; i < lv->items.size(); ++i) {
                         QStyleOptionQ3ListViewItem child = lv->items.at(i);
                         if (child.height + y > 0)
                             break;
                         y += child.totalHeight;
                     }
                     int bx = lv->rect.width() / 2;
                     // paint stuff in the magical area
                     while (i < lv->items.size() && y < lv->rect.height()) {
                         QStyleOptionQ3ListViewItem child = lv->items.at(i);
                         if (child.features & QStyleOptionQ3ListViewItem::Visible) {
                             int lh;
                             if (!(item.features & QStyleOptionQ3ListViewItem::MultiLine))
                                 lh = child.height;
                             else
                                 lh = p->fontMetrics().height() + 2 * lv->itemMargin;
                             lh = qMax(lh, QApplication::globalStrut().height());
                             if (lh % 2 > 0)
                                 ++lh;
                             linebot = y + lh / 2;
                             if (child.features & QStyleOptionQ3ListViewItem::Expandable
                                 || (child.childCount > 0 && child.height > 0)) {
                                 // needs a box
                                 p->setPen(lv->palette.mid().color());
                                 p->drawRect(bx - 4, linebot - 4, 8, 8);
                                 // plus or minus
                                 p->setPen(lv->palette.text().color());
                                 p->drawLine(bx - 2, linebot, bx + 2, linebot);
                                 if (!(child.state & State_Open))
                                     p->drawLine(bx, linebot - 2, bx, linebot + 2);
                                 // dotlinery
                                 p->setPen(lv->palette.mid().color());
                                 dotlines[c++] = QPoint(bx, linetop);
                                 dotlines[c++] = QPoint(bx, linebot - 4);
                                 dotlines[c++] = QPoint(bx + 5, linebot);
                                 dotlines[c++] = QPoint(lv->rect.width(), linebot);
                                 linetop = linebot + 5;
                             } else {
                                 // just dotlinery
                                 dotlines[c++] = QPoint(bx+1, linebot -1);
                                 dotlines[c++] = QPoint(lv->rect.width(), linebot -1);
                             }
                             y += child.totalHeight;
                         }
                         ++i;
                     }
                     // Expand line height to edge of rectangle if there's any
                     // visible child below
                     while (i < lv->items.size() && lv->items.at(i).height <= 0)
                         ++i;
                     if (i < lv->items.size())
                         linebot = lv->rect.height();
                     if (linetop < linebot) {
                         dotlines[c++] = QPoint(bx, linetop);
                         dotlines[c++] = QPoint(bx, linebot);
                     }
                 }
                 p->setPen(lv->palette.text().color());
                 QBitmap *verticalLine = globalVerticalLine();
                 QBitmap *horizontalLine = globalHorizontalLine();
                 static bool isInit = false;
                 if (!isInit) {
                     isInit = true;
                     // make 128*1 and 1*128 bitmaps that can be used for
                     // drawing the right sort of lines.
                     verticalLine->clear();
                     horizontalLine->clear();
                     QPolygon a(64);
                     QPainter p;
                     p.begin(verticalLine);
                     for(i = 0; i < 64; ++i)
                         a.setPoint(i, 0, i * 2 + 1);
                     p.setPen(Qt::color1);
                     p.drawPoints(a);
                     p.end();
                     QApplication::flush();
                     verticalLine->setMask(*verticalLine);
                     p.begin(horizontalLine);
                     for(i = 0; i < 64; ++i)
                         a.setPoint(i, i * 2 + 1, 0);
                     p.setPen(Qt::color1);
                     p.drawPoints(a);
                     p.end();
                     QApplication::flush();
                     horizontalLine->setMask(*horizontalLine);
                 }
                 int line; // index into dotlines
                 if (lv->subControls & SC_Q3ListViewBranch) for(line = 0; line < c; line += 2) {
                     // assumptions here: lines are horizontal or vertical.
                     // lines always start with the numerically lowest
                     // coordinate.
                     // point ... relevant coordinate of current point
                     // end ..... same coordinate of the end of the current line
                     // other ... the other coordinate of the current point/line
                     if (dotlines[line].y() == dotlines[line+1].y()) {
                         int end = dotlines[line + 1].x();
                         int point = dotlines[line].x();
                         int other = dotlines[line].y();
                         while (point < end) {
                             int i = 128;
                             if (i + point > end)
                                 i = end-point;
                             p->drawPixmap(point, other, *horizontalLine, 0, 0, i, 1);
                             point += i;
                         }
                     } else {
                         int end = dotlines[line + 1].y();
                         int point = dotlines[line].y();
                         int other = dotlines[line].x();
                         int pixmapoffset = ((point & 1) != dotoffset) ? 1 : 0;
                         while(point < end) {
                             int i = 128;
                             if (i + point > end)
                                 i = end-point;
                             p->drawPixmap(other, point, *verticalLine, 0, pixmapoffset, 1, i);
                             point += i;
                         }
                     }
                 }
             }
         }
         break;
 #endif // QT3_SUPPORT
 #ifndef QT_NO_COMBOBOX
     case CC_ComboBox:
         if (const QStyleOptionComboBox *cmb = qstyleoption_cast<const QStyleOptionComboBox *>(opt)) {
             QBrush editBrush = cmb->palette.brush(QPalette::Base);
             if ((cmb->subControls & SC_ComboBoxFrame)) {
                 if (cmb->frame) {
                     QPalette shadePal = opt->palette;
                     shadePal.setColor(QPalette::Midlight, shadePal.button().color());
                     qDrawWinPanel(p, opt->rect, shadePal, true, &editBrush);
                 }
                 else {
                     p->fillRect(opt->rect, editBrush);
                 }
             }
             if (cmb->subControls & SC_ComboBoxArrow) {
                 State flags = State_None;
                 QRect ar = proxy()->subControlRect(CC_ComboBox, cmb, SC_ComboBoxArrow, widget);
                 bool sunkenArrow = cmb->activeSubControls == SC_ComboBoxArrow
                                    && cmb->state & State_Sunken;
                 if (sunkenArrow) {
                     p->setPen(cmb->palette.dark().color());
                     p->setBrush(cmb->palette.brush(QPalette::Button));
                     p->drawRect(ar.adjusted(0,0,-1,-1));
                 } else {
                     // Make qDrawWinButton use the right colors for drawing the shade of the button
                     QPalette pal(cmb->palette);
                     pal.setColor(QPalette::Button, cmb->palette.light().color());
                     pal.setColor(QPalette::Light, cmb->palette.button().color());
                     qDrawWinButton(p, ar, pal, false,
                                    &cmb->palette.brush(QPalette::Button));
                 }
                 ar.adjust(2, 2, -2, -2);
                 if (opt->state & State_Enabled)
                     flags |= State_Enabled;
                 if (opt->state & State_HasFocus)
                     flags |= State_HasFocus;
                 if (sunkenArrow)
                     flags |= State_Sunken;
                 QStyleOption arrowOpt(0);
                 arrowOpt.rect = ar.adjusted(1, 1, -1, -1);
                 arrowOpt.palette = cmb->palette;
                 arrowOpt.state = flags;
                 proxy()->drawPrimitive(PE_IndicatorArrowDown, &arrowOpt, p, widget);
             }
             if (cmb->subControls & SC_ComboBoxEditField) {
                 QRect re = proxy()->subControlRect(CC_ComboBox, cmb, SC_ComboBoxEditField, widget);
                 if (cmb->state & State_HasFocus && !cmb->editable)
                     p->fillRect(re.x(), re.y(), re.width(), re.height(),
                                 cmb->palette.brush(QPalette::Highlight));
                 if (cmb->state & State_HasFocus) {
                     p->setPen(cmb->palette.highlightedText().color());
                     p->setBackground(cmb->palette.highlight());
                 } else {
                     p->setPen(cmb->palette.text().color());
                     p->setBackground(cmb->palette.background());
                 }
                 if (cmb->state & State_HasFocus && !cmb->editable) {
                     QStyleOptionFocusRect focus;
                     focus.QStyleOption::operator=(*cmb);
                     focus.rect = subElementRect(SE_ComboBoxFocusRect, cmb, widget);
                     focus.state |= State_FocusAtBorder;
                     focus.backgroundColor = cmb->palette.highlight().color();
                     proxy()->drawPrimitive(PE_FrameFocusRect, &focus, p, widget);
                 }
             }
         }
         break;
 #endif // QT_NO_COMBOBOX
 #ifndef QT_NO_SPINBOX
     case CC_SpinBox:
         if (const QStyleOptionSpinBox *sb = qstyleoption_cast<const QStyleOptionSpinBox *>(opt)) {
             QStyleOptionSpinBox copy = *sb;
             PrimitiveElement pe;
             bool enabled = opt->state & State_Enabled;
             if (sb->frame && (sb->subControls & SC_SpinBoxFrame)) {
                 QBrush editBrush = sb->palette.brush(QPalette::Base);
                 QRect r = proxy()->subControlRect(CC_SpinBox, sb, SC_SpinBoxFrame, widget);
                 QPalette shadePal = sb->palette;
                 shadePal.setColor(QPalette::Midlight, shadePal.button().color());
                 qDrawWinPanel(p, r, shadePal, true, &editBrush);
             }
             QPalette shadePal(opt->palette);
             shadePal.setColor(QPalette::Button, opt->palette.light().color());
             shadePal.setColor(QPalette::Light, opt->palette.button().color());
             if (sb->subControls & SC_SpinBoxUp) {
                 copy.subControls = SC_SpinBoxUp;
                 QPalette pal2 = sb->palette;
                 if (!(sb->stepEnabled & QAbstractSpinBox::StepUpEnabled)) {
                     pal2.setCurrentColorGroup(QPalette::Disabled);
                     copy.state &= ~State_Enabled;
                 }
                 copy.palette = pal2;
                 if (sb->activeSubControls == SC_SpinBoxUp && (sb->state & State_Sunken)) {
                     copy.state |= State_On;
                     copy.state |= State_Sunken;
                 } else {
                     copy.state |= State_Raised;
                     copy.state &= ~State_Sunken;
                 }
                 pe = (sb->buttonSymbols == QAbstractSpinBox::PlusMinus ? PE_IndicatorSpinPlus
                                                                        : PE_IndicatorSpinUp);
                 copy.rect = proxy()->subControlRect(CC_SpinBox, sb, SC_SpinBoxUp, widget);
                 qDrawWinButton(p, copy.rect, shadePal, copy.state & (State_Sunken | State_On),
                                 &copy.palette.brush(QPalette::Button));
                 copy.rect.adjust(4, 1, -5, -1);
                 if ((!enabled || !(sb->stepEnabled & QAbstractSpinBox::StepUpEnabled))
                     && proxy()->styleHint(SH_EtchDisabledText, opt, widget) )
                 {
                     QStyleOptionSpinBox lightCopy = copy;
                     lightCopy.rect.adjust(1, 1, 1, 1);
                     lightCopy.palette.setBrush(QPalette::ButtonText, copy.palette.light());
                     proxy()->drawPrimitive(pe, &lightCopy, p, widget);
                 }
                 proxy()->drawPrimitive(pe, &copy, p, widget);
             }
             if (sb->subControls & SC_SpinBoxDown) {
                 copy.subControls = SC_SpinBoxDown;
                 copy.state = sb->state;
                 QPalette pal2 = sb->palette;
                 if (!(sb->stepEnabled & QAbstractSpinBox::StepDownEnabled)) {
                     pal2.setCurrentColorGroup(QPalette::Disabled);
                     copy.state &= ~State_Enabled;
                 }
                 copy.palette = pal2;
                 if (sb->activeSubControls == SC_SpinBoxDown && (sb->state & State_Sunken)) {
                     copy.state |= State_On;
                     copy.state |= State_Sunken;
                 } else {
                     copy.state |= State_Raised;
                     copy.state &= ~State_Sunken;
                 }
                 pe = (sb->buttonSymbols == QAbstractSpinBox::PlusMinus ? PE_IndicatorSpinMinus
                                                                        : PE_IndicatorSpinDown);
                 copy.rect = proxy()->subControlRect(CC_SpinBox, sb, SC_SpinBoxDown, widget);
                 qDrawWinButton(p, copy.rect, shadePal, copy.state & (State_Sunken | State_On),
                                 &copy.palette.brush(QPalette::Button));
                 copy.rect.adjust(4, 0, -5, -1);
                 if ((!enabled || !(sb->stepEnabled & QAbstractSpinBox::StepDownEnabled))
                     && proxy()->styleHint(SH_EtchDisabledText, opt, widget) )
                 {
                     QStyleOptionSpinBox lightCopy = copy;
                     lightCopy.rect.adjust(1, 1, 1, 1);
                     lightCopy.palette.setBrush(QPalette::ButtonText, copy.palette.light());
                     proxy()->drawPrimitive(pe, &lightCopy, p, widget);
                 }
                 proxy()->drawPrimitive(pe, &copy, p, widget);
             }
         }
         break;
 #endif // QT_NO_SPINBOX
     default:
         QCommonStyle::drawComplexControl(cc, opt, p, widget);
     }
 }
drawControl()
void QWindowsStyle::drawControl (ControlElement element, const QStyleOption * opt, QPainter * p, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 1816 of file qwindowsstyle.cpp.
Referenced by QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QMacStyle::drawControl(), and QStyleSheetStyle::drawControl().
 {
     switch (ce) {
 #ifndef QT_NO_RUBBERBAND
     case CE_RubberBand:
         if (qstyleoption_cast<const QStyleOptionRubberBand *>(opt)) {
             // ### workaround for slow general painter path
             QPixmap tiledPixmap(16, 16);
             QPainter pixmapPainter(&tiledPixmap);
             pixmapPainter.setPen(Qt::NoPen);
             pixmapPainter.setBrush(Qt::Dense4Pattern);
             pixmapPainter.setBackground(Qt::white);
             pixmapPainter.setBackgroundMode(Qt::OpaqueMode);
             pixmapPainter.drawRect(0, 0, tiledPixmap.width(), tiledPixmap.height());
             pixmapPainter.end();
             tiledPixmap = QPixmap::fromImage(tiledPixmap.toImage());
             p->save();
             QRect r = opt->rect;
             QStyleHintReturnMask mask;
             if (proxy()->styleHint(QStyle::SH_RubberBand_Mask, opt, widget, &mask))
                 p->setClipRegion(mask.region);
             p->drawTiledPixmap(r.x(), r.y(), r.width(), r.height(), tiledPixmap);
             p->restore();
             return;
         }
         break;
 #endif // QT_NO_RUBBERBAND
 #if !defined(QT_NO_MENU) && !defined(QT_NO_MAINWINDOW)
     case CE_MenuBarEmptyArea:
         if (widget && qobject_cast<const QMainWindow *>(widget->parentWidget())) {
             p->fillRect(opt->rect, opt->palette.button());
             QPen oldPen = p->pen();
             p->setPen(QPen(opt->palette.dark().color()));
             p->drawLine(opt->rect.bottomLeft(), opt->rect.bottomRight());
             p->setPen(oldPen);
         }
         break;
 #endif
 #ifndef QT_NO_MENU
     case CE_MenuItem:
         if (const QStyleOptionMenuItem *menuitem = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             int x, y, w, h;
             menuitem->rect.getRect(&x, &y, &w, &h);
             int tab = menuitem->tabWidth;
             bool dis = !(menuitem->state & State_Enabled);
             bool checked = menuitem->checkType != QStyleOptionMenuItem::NotCheckable
                             ? menuitem->checked : false;
             bool act = menuitem->state & State_Selected;
             // windows always has a check column, regardless whether we have an icon or not
             int checkcol = qMax<int>(menuitem->maxIconWidth, QWindowsStylePrivate::windowsCheckMarkWidth);
             QBrush fill = menuitem->palette.brush(act ? QPalette::Highlight : QPalette::Button);
             p->fillRect(menuitem->rect.adjusted(0, 0, -1, 0), fill);
             if (menuitem->menuItemType == QStyleOptionMenuItem::Separator){
                 int yoff = y-1 + h / 2;
                 p->setPen(menuitem->palette.dark().color());
                 p->drawLine(x + 2, yoff, x + w - 4, yoff);
                 p->setPen(menuitem->palette.light().color());
                 p->drawLine(x + 2, yoff + 1, x + w - 4, yoff + 1);
                 return;
             }
             QRect vCheckRect = visualRect(opt->direction, menuitem->rect, QRect(menuitem->rect.x(), menuitem->rect.y(), checkcol, menuitem->rect.height()));
             if (!menuitem->icon.isNull() && checked) {
                 if (act) {
                     qDrawShadePanel(p, vCheckRect,
                                     menuitem->palette, true, 1,
                                     &menuitem->palette.brush(QPalette::Button));
                 } else {
                     QBrush fill(menuitem->palette.light().color(), Qt::Dense4Pattern);
                     qDrawShadePanel(p, vCheckRect, menuitem->palette, true, 1, &fill);
                 }
             } else if (!act) {
                 p->fillRect(vCheckRect, menuitem->palette.brush(QPalette::Button));
             }
             // On Windows Style, if we have a checkable item and an icon we
             // draw the icon recessed to indicate an item is checked. If we
             // have no icon, we draw a checkmark instead.
             if (!menuitem->icon.isNull()) {
                 QIcon::Mode mode = dis ? QIcon::Disabled : QIcon::Normal;
                 if (act && !dis)
                     mode = QIcon::Active;
                 QPixmap pixmap;
                 if (checked)
                     pixmap = menuitem->icon.pixmap(proxy()->pixelMetric(PM_SmallIconSize, opt, widget), mode, QIcon::On);
                 else
                     pixmap = menuitem->icon.pixmap(proxy()->pixelMetric(PM_SmallIconSize, opt, widget), mode);
                 int pixw = pixmap.width();
                 int pixh = pixmap.height();
                 if (act && !dis && !checked)
                     qDrawShadePanel(p, vCheckRect,  menuitem->palette, false, 1,
                                     &menuitem->palette.brush(QPalette::Button));
                 QRect pmr(0, 0, pixw, pixh);
                 pmr.moveCenter(vCheckRect.center());
                 p->setPen(menuitem->palette.text().color());
                 p->drawPixmap(pmr.topLeft(), pixmap);
             } else if (checked) {
                 QStyleOptionMenuItem newMi = *menuitem;
                 newMi.state = State_None;
                 if (!dis)
                     newMi.state |= State_Enabled;
                 if (act)
                     newMi.state |= State_On;
                 newMi.rect = visualRect(opt->direction, menuitem->rect, QRect(menuitem->rect.x() + QWindowsStylePrivate::windowsItemFrame,
                                                                               menuitem->rect.y() + QWindowsStylePrivate::windowsItemFrame,
                                                                               checkcol - 2 * QWindowsStylePrivate::windowsItemFrame,
                                                                               menuitem->rect.height() - 2 * QWindowsStylePrivate::windowsItemFrame));
                 proxy()->drawPrimitive(PE_IndicatorMenuCheckMark, &newMi, p, widget);
             }
             p->setPen(act ? menuitem->palette.highlightedText().color() : menuitem->palette.buttonText().color());
             QColor discol;
             if (dis) {
                 discol = menuitem->palette.text().color();
                 p->setPen(discol);
             }
             int xm = int(QWindowsStylePrivate::windowsItemFrame) + checkcol + int(QWindowsStylePrivate::windowsItemHMargin);
             int xpos = menuitem->rect.x() + xm;
             QRect textRect(xpos, y + QWindowsStylePrivate::windowsItemVMargin,
                            w - xm - QWindowsStylePrivate::windowsRightBorder - tab + 1, h - 2 * QWindowsStylePrivate::windowsItemVMargin);
             QRect vTextRect = visualRect(opt->direction, menuitem->rect, textRect);
             QString s = menuitem->text;
             if (!s.isEmpty()) {                     // draw text
                 p->save();
                 int t = s.indexOf(QLatin1Char('\t'));
                 int text_flags = Qt::AlignVCenter | Qt::TextShowMnemonic | Qt::TextDontClip | Qt::TextSingleLine;
                 if (!proxy()->styleHint(SH_UnderlineShortcut, menuitem, widget))
                     text_flags |= Qt::TextHideMnemonic;
                 text_flags |= Qt::AlignLeft;
                 if (t >= 0) {
                     QRect vShortcutRect = visualRect(opt->direction, menuitem->rect,
                         QRect(textRect.topRight(), QPoint(menuitem->rect.right(), textRect.bottom())));
                     if (dis && !act && proxy()->styleHint(SH_EtchDisabledText, opt, widget)) {
                         p->setPen(menuitem->palette.light().color());
                         p->drawText(vShortcutRect.adjusted(1,1,1,1), text_flags, s.mid(t + 1));
                         p->setPen(discol);
                     }
                     p->drawText(vShortcutRect, text_flags, s.mid(t + 1));
                     s = s.left(t);
                 }
                 QFont font = menuitem->font;
                 if (menuitem->menuItemType == QStyleOptionMenuItem::DefaultItem)
                     font.setBold(true);
                 p->setFont(font);
                 if (dis && !act && proxy()->styleHint(SH_EtchDisabledText, opt, widget)) {
                     p->setPen(menuitem->palette.light().color());
                     p->drawText(vTextRect.adjusted(1,1,1,1), text_flags, s.left(t));
                     p->setPen(discol);
                 }
                 p->drawText(vTextRect, text_flags, s.left(t));
                 p->restore();
             }
             if (menuitem->menuItemType == QStyleOptionMenuItem::SubMenu) {// draw sub menu arrow
                 int dim = (h - 2 * QWindowsStylePrivate::windowsItemFrame) / 2;
                 PrimitiveElement arrow;
                 arrow = (opt->direction == Qt::RightToLeft) ? PE_IndicatorArrowLeft : PE_IndicatorArrowRight;
                 xpos = x + w - QWindowsStylePrivate::windowsArrowHMargin - QWindowsStylePrivate::windowsItemFrame - dim;
                 QRect  vSubMenuRect = visualRect(opt->direction, menuitem->rect, QRect(xpos, y + h / 2 - dim / 2, dim, dim));
                 QStyleOptionMenuItem newMI = *menuitem;
                 newMI.rect = vSubMenuRect;
                 newMI.state = dis ? State_None : State_Enabled;
                 if (act)
                     newMI.palette.setColor(QPalette::ButtonText,
                                            newMI.palette.highlightedText().color());
                 proxy()->drawPrimitive(arrow, &newMI, p, widget);
             }
         }
         break;
 #endif // QT_NO_MENU
 #ifndef QT_NO_MENUBAR
     case CE_MenuBarItem:
         if (const QStyleOptionMenuItem *mbi = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             bool active = mbi->state & State_Selected;
             bool hasFocus = mbi->state & State_HasFocus;
             bool down = mbi->state & State_Sunken;
             QStyleOptionMenuItem newMbi = *mbi;
             p->fillRect(mbi->rect, mbi->palette.brush(QPalette::Button));
             if (active || hasFocus) {
                 QBrush b = mbi->palette.brush(QPalette::Button);
                 if (active && down)
                     p->setBrushOrigin(p->brushOrigin() + QPoint(1, 1));
                 if (active && hasFocus)
                     qDrawShadeRect(p, mbi->rect.x(), mbi->rect.y(), mbi->rect.width(),
                                    mbi->rect.height(), mbi->palette, active && down, 1, 0, &b);
                 if (active && down) {
                     newMbi.rect.translate(proxy()->pixelMetric(PM_ButtonShiftHorizontal, mbi, widget),
                                        proxy()->pixelMetric(PM_ButtonShiftVertical, mbi, widget));
                     p->setBrushOrigin(p->brushOrigin() - QPoint(1, 1));
                 }
             }
             QCommonStyle::drawControl(ce, &newMbi, p, widget);
         }
         break;
 #endif // QT_NO_MENUBAR
 #ifndef QT_NO_TABBAR
     case CE_TabBarTabShape:
         if (const QStyleOptionTab *tab = qstyleoption_cast<const QStyleOptionTab *>(opt)) {
             bool rtlHorTabs = (tab->direction == Qt::RightToLeft
                                && (tab->shape == QTabBar::RoundedNorth
                                    || tab->shape == QTabBar::RoundedSouth));
             bool selected = tab->state & State_Selected;
             bool lastTab = ((!rtlHorTabs && tab->position == QStyleOptionTab::End)
                             || (rtlHorTabs
                                 && tab->position == QStyleOptionTab::Beginning));
             bool firstTab = ((!rtlHorTabs
                                && tab->position == QStyleOptionTab::Beginning)
                              || (rtlHorTabs
                                  && tab->position == QStyleOptionTab::End));
             bool onlyOne = tab->position == QStyleOptionTab::OnlyOneTab;
             bool previousSelected =
                 ((!rtlHorTabs
                   && tab->selectedPosition == QStyleOptionTab::PreviousIsSelected)
                 || (rtlHorTabs
                     && tab->selectedPosition == QStyleOptionTab::NextIsSelected));
             bool nextSelected =
                 ((!rtlHorTabs
                   && tab->selectedPosition == QStyleOptionTab::NextIsSelected)
                  || (rtlHorTabs
                      && tab->selectedPosition
                             == QStyleOptionTab::PreviousIsSelected));
             int tabBarAlignment = proxy()->styleHint(SH_TabBar_Alignment, tab, widget);
             bool leftAligned = (!rtlHorTabs && tabBarAlignment == Qt::AlignLeft)
                                 || (rtlHorTabs
                                     && tabBarAlignment == Qt::AlignRight);
             bool rightAligned = (!rtlHorTabs && tabBarAlignment == Qt::AlignRight)
                                  || (rtlHorTabs
                                          && tabBarAlignment == Qt::AlignLeft);
             QColor light = tab->palette.light().color();
             QColor dark = tab->palette.dark().color();
             QColor shadow = tab->palette.shadow().color();
             int borderThinkness = proxy()->pixelMetric(PM_TabBarBaseOverlap, tab, widget);
             if (selected)
                 borderThinkness /= 2;
             QRect r2(opt->rect);
             int x1 = r2.left();
             int x2 = r2.right();
             int y1 = r2.top();
             int y2 = r2.bottom();
             switch (tab->shape) {
             default:
                 QCommonStyle::drawControl(ce, tab, p, widget);
                 break;
             case QTabBar::RoundedNorth: {
                 if (!selected) {
                     y1 += 2;
                     x1 += onlyOne || firstTab ? borderThinkness : 0;
                     x2 -= onlyOne || lastTab ? borderThinkness : 0;
                 }
                 p->fillRect(QRect(x1 + 1, y1 + 1, (x2 - x1) - 1, (y2 - y1) - 2), tab->palette.background());
                 // Delete border
                 if (selected) {
                     p->fillRect(QRect(x1,y2-1,x2-x1,1), tab->palette.background());
                     p->fillRect(QRect(x1,y2,x2-x1,1), tab->palette.background());
                 }
                 // Left
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     p->setPen(light);
                     p->drawLine(x1, y1 + 2, x1, y2 - ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness));
                     p->drawPoint(x1 + 1, y1 + 1);
                 }
                 // Top
                 {
                     int beg = x1 + (previousSelected ? 0 : 2);
                     int end = x2 - (nextSelected ? 0 : 2);
                     p->setPen(light);
                     p->drawLine(beg, y1, end, y1);
                 }
                 // Right
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     p->setPen(shadow);
                     p->drawLine(x2, y1 + 2, x2, y2 - ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness));
                     p->drawPoint(x2 - 1, y1 + 1);
                     p->setPen(dark);
                     p->drawLine(x2 - 1, y1 + 2, x2 - 1, y2 - ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness));
                 }
                 break; }
             case QTabBar::RoundedSouth: {
                 if (!selected) {
                     y2 -= 2;
                     x1 += firstTab ? borderThinkness : 0;
                     x2 -= lastTab ? borderThinkness : 0;
                 }
                 p->fillRect(QRect(x1 + 1, y1 + 2, (x2 - x1) - 1, (y2 - y1) - 1), tab->palette.background());
                 // Delete border
                 if (selected) {
                     p->fillRect(QRect(x1, y1 + 1, (x2 - 1)-x1, 1), tab->palette.background());
                     p->fillRect(QRect(x1, y1, (x2 - 1)-x1, 1), tab->palette.background());
                 }
                 // Left
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     p->setPen(light);
                     p->drawLine(x1, y2 - 2, x1, y1 + ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness));
                     p->drawPoint(x1 + 1, y2 - 1);
                 }
                 // Bottom
                 {
                     int beg = x1 + (previousSelected ? 0 : 2);
                     int end = x2 - (nextSelected ? 0 : 2);
                     p->setPen(shadow);
                     p->drawLine(beg, y2, end, y2);
                     p->setPen(dark);
                     p->drawLine(beg, y2 - 1, end, y2 - 1);
                 }
                 // Right
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     p->setPen(shadow);
                     p->drawLine(x2, y2 - 2, x2, y1 + ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness));
                     p->drawPoint(x2 - 1, y2 - 1);
                     p->setPen(dark);
                     p->drawLine(x2 - 1, y2 - 2, x2 - 1, y1 + ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness));
                 }
                 break; }
             case QTabBar::RoundedWest: {
                 if (!selected) {
                     x1 += 2;
                     y1 += firstTab ? borderThinkness : 0;
                     y2 -= lastTab ? borderThinkness : 0;
                 }
                 p->fillRect(QRect(x1 + 1, y1 + 1, (x2 - x1) - 2, (y2 - y1) - 1), tab->palette.background());
                 // Delete border
                 if (selected) {
                     p->fillRect(QRect(x2 - 1, y1, 1, y2-y1), tab->palette.background());
                     p->fillRect(QRect(x2, y1, 1, y2-y1), tab->palette.background());
                 }
                 // Top
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     p->setPen(light);
                     p->drawLine(x1 + 2, y1, x2 - ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness), y1);
                     p->drawPoint(x1 + 1, y1 + 1);
                 }
                 // Left
                 {
                     int beg = y1 + (previousSelected ? 0 : 2);
                     int end = y2 - (nextSelected ? 0 : 2);
                     p->setPen(light);
                     p->drawLine(x1, beg, x1, end);
                 }
                 // Bottom
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     p->setPen(shadow);
                     p->drawLine(x1 + 3, y2, x2 - ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness), y2);
                     p->drawPoint(x1 + 2, y2 - 1);
                     p->setPen(dark);
                     p->drawLine(x1 + 3, y2 - 1, x2 - ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness), y2 - 1);
                     p->drawPoint(x1 + 1, y2 - 1);
                     p->drawPoint(x1 + 2, y2);
                 }
                 break; }
             case QTabBar::RoundedEast: {
                 if (!selected) {
                     x2 -= 2;
                     y1 += firstTab ? borderThinkness : 0;
                     y2 -= lastTab ? borderThinkness : 0;
                 }
                 p->fillRect(QRect(x1 + 2, y1 + 1, (x2 - x1) - 1, (y2 - y1) - 1), tab->palette.background());
                 // Delete border
                 if (selected) {
                     p->fillRect(QRect(x1 + 1, y1, 1, (y2 - 1)-y1),tab->palette.background());
                     p->fillRect(QRect(x1, y1, 1, (y2-1)-y1), tab->palette.background());
                 }
                 // Top
                 if (firstTab || selected || onlyOne || !previousSelected) {
                     p->setPen(light);
                     p->drawLine(x2 - 2, y1, x1 + ((onlyOne || firstTab) && selected && leftAligned ? 0 : borderThinkness), y1);
                     p->drawPoint(x2 - 1, y1 + 1);
                 }
                 // Right
                 {
                     int beg = y1 + (previousSelected ? 0 : 2);
                     int end = y2 - (nextSelected ? 0 : 2);
                     p->setPen(shadow);
                     p->drawLine(x2, beg, x2, end);
                     p->setPen(dark);
                     p->drawLine(x2 - 1, beg, x2 - 1, end);
                 }
                 // Bottom
                 if (lastTab || selected || onlyOne || !nextSelected) {
                     p->setPen(shadow);
                     p->drawLine(x2 - 2, y2, x1 + ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness), y2);
                     p->drawPoint(x2 - 1, y2 - 1);
                     p->setPen(dark);
                     p->drawLine(x2 - 2, y2 - 1, x1 + ((onlyOne || lastTab) && selected && rightAligned ? 0 : borderThinkness), y2 - 1);
                 }
                 break; }
             }
         }
         break;
 #endif // QT_NO_TABBAR
     case CE_ToolBoxTabShape:
         qDrawShadePanel(p, opt->rect, opt->palette,
                         opt->state & (State_Sunken | State_On), 1,
                         &opt->palette.brush(QPalette::Button));
         break;
 #ifndef QT_NO_SPLITTER
     case CE_Splitter:
         p->eraseRect(opt->rect);
         break;
 #endif // QT_NO_SPLITTER
 #ifndef QT_NO_SCROLLBAR
     case CE_ScrollBarSubLine:
     case CE_ScrollBarAddLine: {
         if ((opt->state & State_Sunken)) {
             p->setPen(opt->palette.dark().color());
             p->setBrush(opt->palette.brush(QPalette::Button));
             p->drawRect(opt->rect.adjusted(0, 0, -1, -1));
         } else {
             QStyleOption buttonOpt = *opt;
             if (!(buttonOpt.state & State_Sunken))
                 buttonOpt.state |= State_Raised;
             QPalette pal(opt->palette);
             pal.setColor(QPalette::Button, opt->palette.light().color());
             pal.setColor(QPalette::Light, opt->palette.button().color());
             qDrawWinButton(p, opt->rect, pal, opt->state & (State_Sunken | State_On),
                            &opt->palette.brush(QPalette::Button));
         }
         PrimitiveElement arrow;
         if (opt->state & State_Horizontal) {
             if (ce == CE_ScrollBarAddLine)
                 arrow = opt->direction == Qt::LeftToRight ? PE_IndicatorArrowRight : PE_IndicatorArrowLeft;
             else
                 arrow = opt->direction == Qt::LeftToRight ? PE_IndicatorArrowLeft : PE_IndicatorArrowRight;
         } else {
             if (ce == CE_ScrollBarAddLine)
                 arrow = PE_IndicatorArrowDown;
             else
                 arrow = PE_IndicatorArrowUp;
         }
         QStyleOption arrowOpt = *opt;
         arrowOpt.rect = opt->rect.adjusted(4, 4, -4, -4);
         proxy()->drawPrimitive(arrow, &arrowOpt, p, widget);
         break; }
     case CE_ScrollBarAddPage:
     case CE_ScrollBarSubPage: {
             QBrush br;
             QBrush bg = p->background();
             Qt::BGMode bg_mode = p->backgroundMode();
             p->setPen(Qt::NoPen);
             p->setBackgroundMode(Qt::OpaqueMode);
             if (opt->state & State_Sunken) {
                 br = QBrush(opt->palette.shadow().color(), Qt::Dense4Pattern);
                 p->setBackground(opt->palette.dark().color());
                 p->setBrush(br);
             } else {
                 QPixmap pm = opt->palette.brush(QPalette::Light).texture();
                 br = !pm.isNull() ? QBrush(pm) : QBrush(opt->palette.light().color(), Qt::Dense4Pattern);
                 p->setBackground(opt->palette.background().color());
                 p->setBrush(br);
             }
             p->drawRect(opt->rect);
             p->setBackground(bg);
             p->setBackgroundMode(bg_mode);
             break; }
     case CE_ScrollBarSlider:
         if (!(opt->state & State_Enabled)) {
             QPixmap pm = opt->palette.brush(QPalette::Light).texture();
             QBrush br = !pm.isNull() ? QBrush(pm) : QBrush(opt->palette.light().color(), Qt::Dense4Pattern);
             p->setPen(Qt::NoPen);
             p->setBrush(br);
             p->setBackgroundMode(Qt::OpaqueMode);
             p->drawRect(opt->rect);
         } else {
             QStyleOptionButton buttonOpt;
             buttonOpt.QStyleOption::operator=(*opt);
             buttonOpt.state = State_Enabled | State_Raised;
             QPalette pal(opt->palette);
             pal.setColor(QPalette::Button, opt->palette.light().color());
             pal.setColor(QPalette::Light, opt->palette.button().color());
             qDrawWinButton(p, opt->rect, pal, false, &opt->palette.brush(QPalette::Button));
         }
         break;
 #endif // QT_NO_SCROLLBAR
     case CE_HeaderSection: {
         QBrush fill;
         if (opt->state & State_On)
             fill = QBrush(opt->palette.light().color(), Qt::Dense4Pattern);
         else
             fill = opt->palette.brush(QPalette::Button);
         if (opt->state & (State_Raised | State_Sunken)) {
             qDrawWinButton(p, opt->rect, opt->palette, opt->state & State_Sunken, &fill);
         } else {
             p->fillRect(opt->rect, fill);
         }
         break; }
 #ifndef QT_NO_TOOLBAR
     case CE_ToolBar:
         if (const QStyleOptionToolBar *toolbar = qstyleoption_cast<const QStyleOptionToolBar *>(opt)) {
             QRect rect = opt->rect;
             bool paintLeftBorder = true;
             bool paintRightBorder = true;
             bool paintBottomBorder = true;
             switch (toolbar->toolBarArea){
             case Qt::BottomToolBarArea :
                 switch(toolbar->positionOfLine){
                 case QStyleOptionToolBar::Beginning:
                 case QStyleOptionToolBar::OnlyOne:
                     paintBottomBorder = false;
                 default:
                     break;
                 }
             case Qt::TopToolBarArea :
                 switch(toolbar->positionWithinLine){
                 case QStyleOptionToolBar::Beginning:
                     paintLeftBorder = false;
                     break;
                 case QStyleOptionToolBar::End:
                     paintRightBorder = false;
                     break;
                 case QStyleOptionToolBar::OnlyOne:
                     paintRightBorder = false;
                     paintLeftBorder = false;
                 default:
                     break;
                 }
                 if(opt->direction == Qt::RightToLeft){ //reverse layout changes the order of Beginning/end
                     bool tmp = paintLeftBorder;
                     paintRightBorder=paintLeftBorder;
                     paintLeftBorder=tmp;
                 }
                 break;
             case Qt::RightToolBarArea :
                 switch (toolbar->positionOfLine){
                 case QStyleOptionToolBar::Beginning:
                 case QStyleOptionToolBar::OnlyOne:
                     paintRightBorder = false;
                     break;
                 default:
                     break;
                 }
                 break;
             case Qt::LeftToolBarArea :
                 switch (toolbar->positionOfLine){
                 case QStyleOptionToolBar::Beginning:
                 case QStyleOptionToolBar::OnlyOne:
                     paintLeftBorder = false;
                     break;
                 default:
                     break;
                 }
                 break;
             default:
                 break;
             }
             //draw top border
             p->setPen(QPen(opt->palette.light().color()));
             p->drawLine(rect.topLeft().x(),
                         rect.topLeft().y(),
                         rect.topRight().x(),
                         rect.topRight().y());
             if (paintLeftBorder){
                 p->setPen(QPen(opt->palette.light().color()));
                 p->drawLine(rect.topLeft().x(),
                             rect.topLeft().y(),
                             rect.bottomLeft().x(),
                             rect.bottomLeft().y());
             }
             if (paintRightBorder){
                 p->setPen(QPen(opt->palette.dark().color()));
                 p->drawLine(rect.topRight().x(),
                             rect.topRight().y(),
                             rect.bottomRight().x(),
                             rect.bottomRight().y());
             }
             if (paintBottomBorder){
                 p->setPen(QPen(opt->palette.dark().color()));
                 p->drawLine(rect.bottomLeft().x(),
                             rect.bottomLeft().y(),
                             rect.bottomRight().x(),
                             rect.bottomRight().y());
             }
         }
         break;
 #endif // QT_NO_TOOLBAR
 #ifndef QT_NO_PROGRESSBAR
     case CE_ProgressBarContents:
         if (const QStyleOptionProgressBar *pb = qstyleoption_cast<const QStyleOptionProgressBar *>(opt)) {
             QRect rect = pb->rect;
             if (!rect.isValid())
                 return;
             bool vertical = false;
             bool inverted = false;
             // Get extra style options if version 2
             const QStyleOptionProgressBarV2 *pb2 = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(opt);
             if (pb2) {
                 vertical = (pb2->orientation == Qt::Vertical);
                 inverted = pb2->invertedAppearance;
             }
             QMatrix m;
             if (vertical) {
                 rect = QRect(rect.y(), rect.x(), rect.height(), rect.width()); // flip width and height
                 m.rotate(90);
                 m.translate(0, -(rect.height() + rect.y()*2));
             }
             QPalette pal2 = pb->palette;
             // Correct the highlight color if it is the same as the background
             if (pal2.highlight() == pal2.background())
                 pal2.setColor(QPalette::Highlight, pb->palette.color(QPalette::Active,
                                                                      QPalette::Highlight));
             bool reverse = ((!vertical && (pb->direction == Qt::RightToLeft)) || vertical);
             if (inverted)
                 reverse = !reverse;
             int w = rect.width();
             if (pb->minimum == 0 && pb->maximum == 0) {
                 Q_D(const QWindowsStyle);
                 const int unit_width = proxy()->pixelMetric(PM_ProgressBarChunkWidth, pb, widget);
                 QStyleOptionProgressBarV2 pbBits = *pb;
                 Q_ASSERT(unit_width >0);
                 pbBits.rect = rect;
                 pbBits.palette = pal2;
                 int chunkCount = w / unit_width + 1;
                 int step = d->animateStep%chunkCount;
                 int chunksInRow = 5;
                 int myY = pbBits.rect.y();
                 int myHeight = pbBits.rect.height();
                 int chunksToDraw = chunksInRow;
                 if(step > chunkCount - 5)chunksToDraw = (chunkCount - step);
                 p->save();
                 p->setClipRect(m.mapRect(QRectF(rect)).toRect());
                 int x0 = reverse ? rect.left() + rect.width() - unit_width*(step) - unit_width  : rect.left() + unit_width * step;
                 int x = 0;
                 for (int i = 0; i < chunksToDraw ; ++i) {
                     pbBits.rect.setRect(x0 + x, myY, unit_width, myHeight);
                     pbBits.rect = m.mapRect(QRectF(pbBits.rect)).toRect();
                     proxy()->drawPrimitive(PE_IndicatorProgressChunk, &pbBits, p, widget);
                     x += reverse ? -unit_width : unit_width;
                 }
                 //Draw wrap-around chunks
                 if( step > chunkCount-5){
                     x0 = reverse ? rect.left() + rect.width() - unit_width : rect.left() ;
                     x = 0;
                     int chunksToDraw = step - (chunkCount - chunksInRow);
                     for (int i = 0; i < chunksToDraw ; ++i) {
                         pbBits.rect.setRect(x0 + x, myY, unit_width, myHeight);
                         pbBits.rect = m.mapRect(QRectF(pbBits.rect)).toRect();
                         proxy()->drawPrimitive(PE_IndicatorProgressChunk, &pbBits, p, widget);
                         x += reverse ? -unit_width : unit_width;
                     }
                 }
                 p->restore(); //restore state
             }
             else {
                 QCommonStyle::drawControl(ce, opt, p, widget);
             }
         }
         break;
 #endif // QT_NO_PROGRESSBAR
 #ifndef QT_NO_DOCKWIDGET
     case CE_DockWidgetTitle:
         if (const QStyleOptionDockWidget *dwOpt = qstyleoption_cast<const QStyleOptionDockWidget *>(opt)) {
             Q_D(const QWindowsStyle);
             const QStyleOptionDockWidgetV2 *v2
                 = qstyleoption_cast<const QStyleOptionDockWidgetV2*>(opt);
             bool verticalTitleBar = v2 == 0 ? false : v2->verticalTitleBar;
             QRect rect = dwOpt->rect;
             QRect r = rect;
             if (verticalTitleBar) {
                 QSize s = r.size();
                 s.transpose();
                 r.setSize(s);
                 p->save();
                 p->translate(r.left(), r.top() + r.width());
                 p->rotate(-90);
                 p->translate(-r.left(), -r.top());
             }
             bool floating = false;
             bool active = dwOpt->state & State_Active;
             QColor inactiveCaptionTextColor = d->inactiveCaptionText;
             if (dwOpt->movable) {
                 QColor left, right;
                 //Titlebar gradient
                 if (widget && widget->isWindow()) {
                     floating = true;
                     if (active) {
                         left = d->activeCaptionColor;
                         right = d->activeGradientCaptionColor;
                     } else {
                         left = d->inactiveCaptionColor;
                         right = d->inactiveGradientCaptionColor;
                     }
                     QBrush fillBrush(left);
                     if (left != right) {
                         QPoint p1(r.x(), r.top() + r.height()/2);
                         QPoint p2(rect.right(), r.top() + r.height()/2);
                         QLinearGradient lg(p1, p2);
                         lg.setColorAt(0, left);
                         lg.setColorAt(1, right);
                         fillBrush = lg;
                     }
                     p->fillRect(r.adjusted(0, 0, 0, -3), fillBrush);
                 }
                 p->setPen(dwOpt->palette.color(QPalette::Light));
                 if (!widget || !widget->isWindow()) {
                     p->drawLine(r.topLeft(), r.topRight());
                     p->setPen(dwOpt->palette.color(QPalette::Dark));
                     p->drawLine(r.bottomLeft(), r.bottomRight());            }
             }
             if (!dwOpt->title.isEmpty()) {
                 QFont oldFont = p->font();
                 if (floating) {
                     QFont font = oldFont;
                     font.setBold(true);
                     p->setFont(font);
                 }
                 QPalette palette = dwOpt->palette;
                 palette.setColor(QPalette::Window, inactiveCaptionTextColor);
                 QRect titleRect = subElementRect(SE_DockWidgetTitleBarText, opt, widget);
                 if (verticalTitleBar) {
                     titleRect = QRect(r.left() + rect.bottom()
                                         - titleRect.bottom(),
                                     r.top() + titleRect.left() - rect.left(),
                                     titleRect.height(), titleRect.width());
                 }
                 proxy()->drawItemText(p, titleRect,
                             Qt::AlignLeft | Qt::AlignVCenter | Qt::TextShowMnemonic, palette,
                             dwOpt->state & State_Enabled, dwOpt->title,
                             floating ? (active ? QPalette::BrightText : QPalette::Window) : QPalette::WindowText);
                 p->setFont(oldFont);
             }
             if (verticalTitleBar)
                 p->restore();
         }
         return;
 #endif // QT_NO_DOCKWIDGET
     default:
         QCommonStyle::drawControl(ce, opt, p, widget);
     }
 }
drawPrimitive()
void QWindowsStyle::drawPrimitive (PrimitiveElement pe, const QStyleOption * opt, QPainter * p, const QWidget * w = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 1253 of file qwindowsstyle.cpp.
Referenced by QWindowsCEStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMacStyle::drawPrimitive(), and QStyleSheetStyle::drawPrimitive().
 {
     // Used to restore across fallthrough cases. Currently only used in PE_IndicatorCheckBox
     bool doRestore = false;
     switch (pe) {
 #ifndef QT_NO_TOOLBAR
   case PE_IndicatorToolBarSeparator:
         {
             QRect rect = opt->rect;
             const int margin = 2;
             QPen oldPen = p->pen();
             if(opt->state & State_Horizontal){
                 const int offset = rect.width()/2;
                 p->setPen(QPen(opt->palette.dark().color()));
                 p->drawLine(rect.bottomLeft().x() + offset,
                             rect.bottomLeft().y() - margin,
                             rect.topLeft().x() + offset,
                             rect.topLeft().y() + margin);
                 p->setPen(QPen(opt->palette.light().color()));
                 p->drawLine(rect.bottomLeft().x() + offset + 1,
                             rect.bottomLeft().y() - margin,
                             rect.topLeft().x() + offset + 1,
                             rect.topLeft().y() + margin);
             }
             else{ //Draw vertical separator
                 const int offset = rect.height()/2;
                 p->setPen(QPen(opt->palette.dark().color()));
                 p->drawLine(rect.topLeft().x() + margin ,
                             rect.topLeft().y() + offset,
                             rect.topRight().x() - margin,
                             rect.topRight().y() + offset);
                 p->setPen(QPen(opt->palette.light().color()));
                 p->drawLine(rect.topLeft().x() + margin ,
                             rect.topLeft().y() + offset + 1,
                             rect.topRight().x() - margin,
                             rect.topRight().y() + offset + 1);
             }
             p->setPen(oldPen);
         }
         break;
     case PE_IndicatorToolBarHandle:
         p->save();
         p->translate(opt->rect.x(), opt->rect.y());
         if (opt->state & State_Horizontal) {
             int x = opt->rect.width() / 2 - 4;
             if (opt->direction == Qt::RightToLeft)
                 x -= 2;
             if (opt->rect.height() > 4) {
                 qDrawShadePanel(p, x, 2, 3, opt->rect.height() - 4,
                                 opt->palette, false, 1, 0);
                 qDrawShadePanel(p, x + 3, 2, 3, opt->rect.height() - 4,
                                 opt->palette, false, 1, 0);
             }
         } else {
             if (opt->rect.width() > 4) {
                 int y = opt->rect.height() / 2 - 4;
                 qDrawShadePanel(p, 2, y, opt->rect.width() - 4, 3,
                                 opt->palette, false, 1, 0);
                 qDrawShadePanel(p, 2, y + 3, opt->rect.width() - 4, 3,
                                 opt->palette, false, 1, 0);
             }
         }
         p->restore();
         break;
 #endif // QT_NO_TOOLBAR
     case PE_FrameButtonTool:
     case PE_PanelButtonTool: {
         QPen oldPen = p->pen();
 #ifndef QT_NO_DOCKWIDGET
         if (w && w->inherits("QDockWidgetTitleButton")) {
            if (const QWidget *dw = w->parentWidget())
                 if (dw->isWindow()){
                     qDrawWinButton(p, opt->rect.adjusted(1, 1, 0, 0), opt->palette, opt->state & (State_Sunken | State_On),
                            &opt->palette.button());
                     return;
                 }
         }
 #endif // QT_NO_DOCKWIDGET
         QBrush fill;
         bool stippled;
         bool panel = (pe == PE_PanelButtonTool);
         if ((!(opt->state & State_Sunken ))
             && (!(opt->state & State_Enabled)
                 || !(opt->state & State_MouseOver && opt->state & State_AutoRaise))
             && (opt->state & State_On)) {
             fill = QBrush(opt->palette.light().color(), Qt::Dense4Pattern);
             stippled = true;
         } else {
             fill = opt->palette.brush(QPalette::Button);
             stippled = false;
         }
         if (opt->state & (State_Raised | State_Sunken | State_On)) {
             if (opt->state & State_AutoRaise) {
                 if(opt->state & (State_Enabled | State_Sunken | State_On)){
                     if (panel)
                         qDrawShadePanel(p, opt->rect, opt->palette,
                                         opt->state & (State_Sunken | State_On), 1, &fill);
                     else
                         qDrawShadeRect(p, opt->rect, opt->palette,
                                        opt->state & (State_Sunken | State_On), 1);
                 }
                 if (stippled) {
                     p->setPen(opt->palette.button().color());
                     p->drawRect(opt->rect.adjusted(1,1,-2,-2));
                 }
             } else {
                 qDrawWinButton(p, opt->rect, opt->palette,
                                opt->state & (State_Sunken | State_On), panel ? &fill : 0);
             }
         } else {
             p->fillRect(opt->rect, fill);
         }
         p->setPen(oldPen);
         break; }
     case PE_PanelButtonCommand:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             QBrush fill;
             State flags = opt->state;
             QPalette pal = opt->palette;
             QRect r = opt->rect;
             if (! (flags & State_Sunken) && (flags & State_On))
                 fill = QBrush(pal.light().color(), Qt::Dense4Pattern);
             else
                 fill = pal.brush(QPalette::Button);
             if (btn->features & QStyleOptionButton::DefaultButton && flags & State_Sunken) {
                 p->setPen(pal.dark().color());
                 p->setBrush(fill);
                 p->drawRect(r.adjusted(0, 0, -1, -1));
             } else if (flags & (State_Raised | State_Sunken | State_On | State_Sunken)) {
                 qDrawWinButton(p, r, pal, flags & (State_Sunken | State_On),
                                &fill);
             } else {
                 p->fillRect(r, fill);
             }
         }
         break;
     case PE_FrameDefaultButton: {
         QPen oldPen = p->pen();
         p->setPen(opt->palette.shadow().color());
         QRect rect = opt->rect;
         rect.adjust(0, 0, -1, -1);
         p->drawRect(rect);
         p->setPen(oldPen);
         break;
     }
     case PE_IndicatorArrowUp:
     case PE_IndicatorArrowDown:
     case PE_IndicatorArrowRight:
     case PE_IndicatorArrowLeft:
         {
             if (opt->rect.width() <= 1 || opt->rect.height() <= 1)
                 break;
             QRect r = opt->rect;
             int size = qMin(r.height(), r.width());
             QPixmap pixmap;
             QString pixmapName = QStyleHelper::uniqueName(QLatin1String("$qt_ia-")
                                                           % QLatin1String(metaObject()->className()), opt, QSize(size, size))
                                  % HexString<uint>(pe);
             if (!QPixmapCache::find(pixmapName, pixmap)) {
                 int border = size/5;
                 int sqsize = 2*(size/2);
                 QImage image(sqsize, sqsize, QImage::Format_ARGB32_Premultiplied);
                 image.fill(0);
                 QPainter imagePainter(&image);
                 QPolygon a;
                 switch (pe) {
                     case PE_IndicatorArrowUp:
                         a.setPoints(3, border, sqsize/2,  sqsize/2, border,  sqsize - border, sqsize/2);
                         break;
                     case PE_IndicatorArrowDown:
                         a.setPoints(3, border, sqsize/2,  sqsize/2, sqsize - border,  sqsize - border, sqsize/2);
                         break;
                     case PE_IndicatorArrowRight:
                         a.setPoints(3, sqsize - border, sqsize/2,  sqsize/2, border,  sqsize/2, sqsize - border);
                         break;
                     case PE_IndicatorArrowLeft:
                         a.setPoints(3, border, sqsize/2,  sqsize/2, border,  sqsize/2, sqsize - border);
                         break;
                     default:
                         break;
                 }
                 int bsx = 0;
                 int bsy = 0;
                 if (opt->state & State_Sunken) {
                     bsx = proxy()->pixelMetric(PM_ButtonShiftHorizontal, opt, w);
                     bsy = proxy()->pixelMetric(PM_ButtonShiftVertical, opt, w);
                 }
                 QRect bounds = a.boundingRect();
                 int sx = sqsize / 2 - bounds.center().x() - 1;
                 int sy = sqsize / 2 - bounds.center().y() - 1;
                 imagePainter.translate(sx + bsx, sy + bsy);
                 imagePainter.setPen(opt->palette.buttonText().color());
                 imagePainter.setBrush(opt->palette.buttonText());
                 if (!(opt->state & State_Enabled)) {
                     imagePainter.translate(1, 1);
                     imagePainter.setBrush(opt->palette.light().color());
                     imagePainter.setPen(opt->palette.light().color());
                     imagePainter.drawPolygon(a);
                     imagePainter.translate(-1, -1);
                     imagePainter.setBrush(opt->palette.mid().color());
                     imagePainter.setPen(opt->palette.mid().color());
                 }
                 imagePainter.drawPolygon(a);
                 imagePainter.end();
                 pixmap = QPixmap::fromImage(image);
                 QPixmapCache::insert(pixmapName, pixmap);
             }
             int xOffset = r.x() + (r.width() - size)/2;
             int yOffset = r.y() + (r.height() - size)/2;
             p->drawPixmap(xOffset, yOffset, pixmap);
         }
         break;
     case PE_IndicatorCheckBox: {
         QBrush fill;
         if (opt->state & State_NoChange)
             fill = QBrush(opt->palette.base().color(), Qt::Dense4Pattern);
         else if (opt->state & State_Sunken)
             fill = opt->palette.button();
         else if (opt->state & State_Enabled)
             fill = opt->palette.base();
         else
             fill = opt->palette.background();
         p->save();
         doRestore = true;
         qDrawWinPanel(p, opt->rect, opt->palette, true, &fill);
         if (opt->state & State_NoChange)
             p->setPen(opt->palette.dark().color());
         else
             p->setPen(opt->palette.text().color());
         } // Fall through!
     case PE_IndicatorViewItemCheck:
     case PE_Q3CheckListIndicator:
         if (!doRestore) {
             p->save();
             doRestore = true;
         }
         if (pe == PE_Q3CheckListIndicator || pe == PE_IndicatorViewItemCheck) {
             const QStyleOptionViewItem *itemViewOpt = qstyleoption_cast<const QStyleOptionViewItem *>(opt);
             p->setPen(itemViewOpt
                       && itemViewOpt->showDecorationSelected
                       && opt->state & State_Selected
                         ? opt->palette.highlightedText().color()
                         : opt->palette.text().color());
             if (opt->state & State_NoChange)
                 p->setBrush(opt->palette.brush(QPalette::Button));
             p->drawRect(opt->rect.x() + 1, opt->rect.y() + 1, 11, 11);
         }
         if (!(opt->state & State_Off)) {
             QLineF lines[7];
             int i, xx, yy;
             xx = opt->rect.x() + 3;
             yy = opt->rect.y() + 5;
             for (i = 0; i < 3; ++i) {
                 lines[i] = QLineF(xx, yy, xx, yy + 2);
                 ++xx;
                 ++yy;
             }
             yy -= 2;
             for (i = 3; i < 7; ++i) {
                 lines[i] = QLineF(xx, yy, xx, yy + 2);
                 ++xx;
                 --yy;
             }
             p->drawLines(lines, 7);
         }
         if (doRestore)
             p->restore();
         break;
     case PE_FrameFocusRect:
         if (const QStyleOptionFocusRect *fropt = qstyleoption_cast<const QStyleOptionFocusRect *>(opt)) {
             //### check for d->alt_down
             if (!(fropt->state & State_KeyboardFocusChange) && !proxy()->styleHint(SH_UnderlineShortcut, opt))
                 return;
             QRect r = opt->rect;
             p->save();
             p->setBackgroundMode(Qt::TransparentMode);
             QColor bg_col = fropt->backgroundColor;
             if (!bg_col.isValid())
                 bg_col = p->background().color();
             // Create an "XOR" color.
             QColor patternCol((bg_col.red() ^ 0xff) & 0xff,
                               (bg_col.green() ^ 0xff) & 0xff,
                               (bg_col.blue() ^ 0xff) & 0xff);
             p->setBrush(QBrush(patternCol, Qt::Dense4Pattern));
             p->setBrushOrigin(r.topLeft());
             p->setPen(Qt::NoPen);
             p->drawRect(r.left(), r.top(), r.width(), 1);    // Top
             p->drawRect(r.left(), r.bottom(), r.width(), 1); // Bottom
             p->drawRect(r.left(), r.top(), 1, r.height());   // Left
             p->drawRect(r.right(), r.top(), 1, r.height());  // Right
             p->restore();
         }
         break;
     case PE_IndicatorRadioButton:
         {
 #define PTSARRLEN(x) sizeof(x)/(sizeof(QPoint))
             static const QPoint pts1[] = {              // dark lines
                 QPoint(1, 9), QPoint(1, 8), QPoint(0, 7), QPoint(0, 4), QPoint(1, 3), QPoint(1, 2),
                 QPoint(2, 1), QPoint(3, 1), QPoint(4, 0), QPoint(7, 0), QPoint(8, 1), QPoint(9, 1)
             };
             static const QPoint pts2[] = {              // black lines
                 QPoint(2, 8), QPoint(1, 7), QPoint(1, 4), QPoint(2, 3), QPoint(2, 2), QPoint(3, 2),
                 QPoint(4, 1), QPoint(7, 1), QPoint(8, 2), QPoint(9, 2)
             };
             static const QPoint pts3[] = {              // background lines
                 QPoint(2, 9), QPoint(3, 9), QPoint(4, 10), QPoint(7, 10), QPoint(8, 9), QPoint(9, 9),
                 QPoint(9, 8), QPoint(10, 7), QPoint(10, 4), QPoint(9, 3)
             };
             static const QPoint pts4[] = {              // white lines
                 QPoint(2, 10), QPoint(3, 10), QPoint(4, 11), QPoint(7, 11), QPoint(8, 10),
                 QPoint(9, 10), QPoint(10, 9), QPoint(10, 8), QPoint(11, 7), QPoint(11, 4),
                 QPoint(10, 3), QPoint(10, 2)
             };
             static const QPoint pts5[] = {              // inner fill
                 QPoint(4, 2), QPoint(7, 2), QPoint(9, 4), QPoint(9, 7), QPoint(7, 9), QPoint(4, 9),
                 QPoint(2, 7), QPoint(2, 4)
             };
             // make sure the indicator is square
             QRect ir = opt->rect;
             if (opt->rect.width() < opt->rect.height()) {
                 ir.setTop(opt->rect.top() + (opt->rect.height() - opt->rect.width()) / 2);
                 ir.setHeight(opt->rect.width());
             } else if (opt->rect.height() < opt->rect.width()) {
                 ir.setLeft(opt->rect.left() + (opt->rect.width() - opt->rect.height()) / 2);
                 ir.setWidth(opt->rect.height());
             }
             p->save();
             bool down = opt->state & State_Sunken;
             bool enabled = opt->state & State_Enabled;
             bool on = opt->state & State_On;
             QPolygon a;
             //center when rect is larger than indicator size
             int xOffset = 0;
             int yOffset = 0;
             int indicatorWidth = proxy()->pixelMetric(PM_ExclusiveIndicatorWidth);
             int indicatorHeight = proxy()->pixelMetric(PM_ExclusiveIndicatorWidth);
             if (ir.width() > indicatorWidth)
                 xOffset += (ir.width() - indicatorWidth)/2;
             if (ir.height() > indicatorHeight)
                 yOffset += (ir.height() - indicatorHeight)/2;
             p->translate(xOffset, yOffset);
             p->translate(ir.x(), ir.y());
             p->setPen(opt->palette.dark().color());
             p->drawPolyline(pts1, PTSARRLEN(pts1));
             p->setPen(opt->palette.shadow().color());
             p->drawPolyline(pts2, PTSARRLEN(pts2));
             p->setPen(opt->palette.midlight().color());
             p->drawPolyline(pts3, PTSARRLEN(pts3));
             p->setPen(opt->palette.light().color());
             p->drawPolyline(pts4, PTSARRLEN(pts4));
             QColor fillColor = (down || !enabled)
                                ? opt->palette.button().color()
                                : opt->palette.base().color();
             p->setPen(fillColor);
             p->setBrush(fillColor) ;
             p->drawPolygon(pts5, PTSARRLEN(pts5));
             p->translate(-ir.x(), -ir.y()); // restore translate
             if (on) {
                 p->setPen(Qt::NoPen);
                 p->setBrush(opt->palette.text());
                 p->drawRect(ir.x() + 5, ir.y() + 4, 2, 4);
                 p->drawRect(ir.x() + 4, ir.y() + 5, 4, 2);
             }
             p->restore();
             break;
         }
 #ifndef QT_NO_FRAME
     case PE_Frame:
     case PE_FrameMenu:
         if (const QStyleOptionFrame *frame = qstyleoption_cast<const QStyleOptionFrame *>(opt)) {
             if (frame->lineWidth == 2 || pe == PE_Frame) {
                 QPalette popupPal = frame->palette;
                 if (pe == PE_FrameMenu) {
                     popupPal.setColor(QPalette::Light, frame->palette.background().color());
                     popupPal.setColor(QPalette::Midlight, frame->palette.light().color());
                 }
                 if (pe == PE_Frame && (frame->state & State_Raised))
                     qDrawWinButton(p, frame->rect, popupPal, frame->state & State_Sunken);
                 else if (pe == PE_Frame && (frame->state & State_Sunken))
                 {
                     popupPal.setColor(QPalette::Midlight, frame->palette.background().color());
                     qDrawWinPanel(p, frame->rect, popupPal, frame->state & State_Sunken);
                 }
                 else
                     qDrawWinPanel(p, frame->rect, popupPal, frame->state & State_Sunken);
             } else {
                 QCommonStyle::drawPrimitive(pe, opt, p, w);
             }
         } else {
             QPalette popupPal = opt->palette;
             popupPal.setColor(QPalette::Light, opt->palette.background().color());
             popupPal.setColor(QPalette::Midlight, opt->palette.light().color());
             qDrawWinPanel(p, opt->rect, popupPal, opt->state & State_Sunken);
         }
         break;
 #endif // QT_NO_FRAME
     case PE_IndicatorBranch: {
         // This is _way_ too similar to the common style.
         static const int decoration_size = 9;
         int mid_h = opt->rect.x() + opt->rect.width() / 2;
         int mid_v = opt->rect.y() + opt->rect.height() / 2;
         int bef_h = mid_h;
         int bef_v = mid_v;
         int aft_h = mid_h;
         int aft_v = mid_v;
         if (opt->state & State_Children) {
             int delta = decoration_size / 2;
             bef_h -= delta;
             bef_v -= delta;
             aft_h += delta;
             aft_v += delta;
             p->drawLine(bef_h + 2, bef_v + 4, bef_h + 6, bef_v + 4);
             if (!(opt->state & State_Open))
                 p->drawLine(bef_h + 4, bef_v + 2, bef_h + 4, bef_v + 6);
             QPen oldPen = p->pen();
             p->setPen(opt->palette.dark().color());
             p->drawRect(bef_h, bef_v, decoration_size - 1, decoration_size - 1);
             p->setPen(oldPen);
         }
         QBrush brush(opt->palette.dark().color(), Qt::Dense4Pattern);
         if (opt->state & State_Item) {
             if (opt->direction == Qt::RightToLeft)
                 p->fillRect(opt->rect.left(), mid_v, bef_h - opt->rect.left(), 1, brush);
             else
                 p->fillRect(aft_h, mid_v, opt->rect.right() - aft_h + 1, 1, brush);
         }
         if (opt->state & State_Sibling)
             p->fillRect(mid_h, aft_v, 1, opt->rect.bottom() - aft_v + 1, brush);
         if (opt->state & (State_Open | State_Children | State_Item | State_Sibling))
             p->fillRect(mid_h, opt->rect.y(), 1, bef_v - opt->rect.y(), brush);
         break; }
     case PE_FrameButtonBevel:
     case PE_PanelButtonBevel: {
         QBrush fill;
         bool panel = pe != PE_FrameButtonBevel;
         p->setBrushOrigin(opt->rect.topLeft());
         if (!(opt->state & State_Sunken) && (opt->state & State_On))
             fill = QBrush(opt->palette.light().color(), Qt::Dense4Pattern);
         else
             fill = opt->palette.brush(QPalette::Button);
         if (opt->state & (State_Raised | State_On | State_Sunken)) {
             qDrawWinButton(p, opt->rect, opt->palette, opt->state & (State_Sunken | State_On),
                            panel ? &fill : 0);
         } else {
             if (panel)
                 p->fillRect(opt->rect, fill);
             else
                 p->drawRect(opt->rect);
         }
         break; }
     case PE_FrameWindow: {
          QPalette popupPal = opt->palette;
          popupPal.setColor(QPalette::Light, opt->palette.background().color());
          popupPal.setColor(QPalette::Midlight, opt->palette.light().color());
          qDrawWinPanel(p, opt->rect, popupPal, opt->state & State_Sunken);
         break; }
 #ifndef QT_NO_DOCKWIDGET
     case PE_IndicatorDockWidgetResizeHandle: {
         QPen oldPen = p->pen();
         p->setPen(opt->palette.light().color());
         if (opt->state & State_Horizontal) {
             p->drawLine(opt->rect.left(),          opt->rect.top(),
                         opt->rect.right(), opt->rect.top());
             p->setPen(opt->palette.dark().color());
             p->drawLine(opt->rect.left(),          opt->rect.bottom() - 1,
                         opt->rect.right(), opt->rect.bottom() - 1);
             p->setPen(opt->palette.shadow().color());
             p->drawLine(opt->rect.left(),          opt->rect.bottom(),
                         opt->rect.right(), opt->rect.bottom());
         } else {
             p->drawLine(opt->rect.left(), opt->rect.top(),
                         opt->rect.left(), opt->rect.bottom());
             p->setPen(opt->palette.dark().color());
             p->drawLine(opt->rect.right() - 1, opt->rect.top(),
                         opt->rect.right() - 1, opt->rect.bottom());
             p->setPen(opt->palette.shadow().color());
             p->drawLine(opt->rect.right(), opt->rect.top(),
                         opt->rect.right(), opt->rect.bottom());
         }
         p->setPen(oldPen);
         break; }
 case PE_FrameDockWidget:
         if (qstyleoption_cast<const QStyleOptionFrame *>(opt)) {
             proxy()->drawPrimitive(QStyle::PE_FrameWindow, opt, p, w);
         }
     break;
 #endif // QT_NO_DOCKWIDGET
     case PE_FrameStatusBarItem:
         qDrawShadePanel(p, opt->rect, opt->palette, true, 1, 0);
         break;
 #ifndef QT_NO_PROGRESSBAR
     case PE_IndicatorProgressChunk:
         {
             bool vertical = false, inverted = false;
             if (const QStyleOptionProgressBarV2 *pb2 = qstyleoption_cast<const QStyleOptionProgressBarV2 *>(opt)) {
                 vertical = (pb2->orientation == Qt::Vertical);
                 inverted = pb2->invertedAppearance;
             }
             int space = 2;
             int chunksize = proxy()->pixelMetric(PM_ProgressBarChunkWidth, opt, w) - space;
             if (!vertical) {
                 if (opt->rect.width() <= chunksize)
                     space = 0;
                 if (inverted)
                     p->fillRect(opt->rect.x() + space, opt->rect.y(), opt->rect.width() - space, opt->rect.height(),
                             opt->palette.brush(QPalette::Highlight));
                 else
                     p->fillRect(opt->rect.x(), opt->rect.y(), opt->rect.width() - space, opt->rect.height(),
                                 opt->palette.brush(QPalette::Highlight));
             } else {
                 if (opt->rect.height() <= chunksize)
                     space = 0;
                 if (inverted)
                     p->fillRect(opt->rect.x(), opt->rect.y(), opt->rect.width(), opt->rect.height() - space,
                             opt->palette.brush(QPalette::Highlight));
                 else
                     p->fillRect(opt->rect.x(), opt->rect.y() + space, opt->rect.width(), opt->rect.height() - space,
                                 opt->palette.brush(QPalette::Highlight));
             }
         }
         break;
 #endif // QT_NO_PROGRESSBAR
     case PE_FrameTabWidget: {
         qDrawWinButton(p, opt->rect, opt->palette, false, 0);
         break;
     }
     default:
         QCommonStyle::drawPrimitive(pe, opt, p, w);
     }
 }
eventFilter()
bool QWindowsStyle::eventFilter (QObject * o, QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 183 of file qwindowsstyle.cpp.
Referenced by QPlastiqueStyle::eventFilter().
 {
     // Records Alt- and Focus events
     if (!o->isWidgetType())
         return QObject::eventFilter(o, e);
     QWidget *widget = qobject_cast<QWidget*>(o);
     Q_D(QWindowsStyle);
     switch(e->type()) {
     case QEvent::KeyPress:
         if (static_cast<QKeyEvent *>(e)->key() == Qt::Key_Alt) {
             widget = widget->window();
             // Alt has been pressed - find all widgets that care
             QList<QWidget *> l = widget->findChildren<QWidget *>();
             for (int pos=0 ; pos < l.size() ;) {
                 QWidget *w = l.at(pos);
                 if (w->isWindow() || !w->isVisible() ||
                     w->style()->styleHint(SH_UnderlineShortcut, 0, w)) {
                     l.removeAt(pos);
                     continue;
                 }
                 pos++;
             }
             // Update states before repainting
             d->seenAlt.append(widget);
             d->alt_down = true;
             // Repaint all relevant widgets
             for (int pos = 0; pos < l.size(); ++pos)
                 l.at(pos)->update();
         }
         break;
     case QEvent::KeyRelease:
         if (static_cast<QKeyEvent*>(e)->key() == Qt::Key_Alt) {
             widget = widget->window();
             // Update state and repaint the menu bars.
             d->alt_down = false;
 #ifndef QT_NO_MENUBAR
             QList<QMenuBar *> l = widget->findChildren<QMenuBar *>();
             for (int i = 0; i < l.size(); ++i)
                 l.at(i)->update();
 #endif
         }
         break;
     case QEvent::Close:
         // Reset widget when closing
         d->seenAlt.removeAll(widget);
         d->seenAlt.removeAll(widget->window());
         break;
 #ifndef QT_NO_PROGRESSBAR
     case QEvent::StyleChange:
     case QEvent::Paint:
     case QEvent::Show:
         if (QProgressBar *bar = qobject_cast<QProgressBar *>(o)) {
             // Animation by timer for progress bars that have their min and
             // max values the same
             if (bar->minimum() == bar->maximum())
                 d->startAnimation(this, bar);
             else
                 d->stopAnimation(this, bar);
         }
         break;
     case QEvent::Destroy:
     case QEvent::Hide:
         // Do static_cast because there is no type info when getting
         // the destroy event. We know that it is a QProgressBar, since
         // we only install a widget event filter for QScrollBars.
         d->stopAnimation(this, static_cast<QProgressBar *>(o));
         break;
 #endif // QT_NO_PROGRESSBAR
     default:
         break;
     }
     return QCommonStyle::eventFilter(o, e);
 }
pixelMetric()
int QWindowsStyle::pixelMetric (PixelMetric pm, const QStyleOption * option = 0, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 380 of file qwindowsstyle.cpp.
Referenced by drawControl(), QCleanlooksStyle::pixelMetric(), QWindowsVistaStyle::pixelMetric(), QWindowsXPStyle::pixelMetric(), QPlastiqueStyle::pixelMetric(), QWindowsCEStyle::pixelMetric(), QWindowsMobileStyle::pixelMetric(), and QMacStyle::pixelMetric().
 {
     int ret;
     switch (pm) {
     case PM_ButtonDefaultIndicator:
     case PM_ButtonShiftHorizontal:
     case PM_ButtonShiftVertical:
     case PM_MenuHMargin:
     case PM_MenuVMargin:
         ret = 1;
         break;
 #ifndef QT_NO_TABBAR
     case PM_TabBarTabShiftHorizontal:
         ret = 0;
         break;
     case PM_TabBarTabShiftVertical:
         ret = 2;
         break;
 #endif
     case PM_MaximumDragDistance:
 #if defined(Q_WS_WIN)
         {
             HDC hdcScreen = GetDC(0);
             int dpi = GetDeviceCaps(hdcScreen, LOGPIXELSX);
             ReleaseDC(0, hdcScreen);
             ret = (int)(dpi * 1.375);
         }
 #else
         ret = 60;
 #endif
         break;
 #ifndef QT_NO_SLIDER
     case PM_SliderLength:
         ret = int(QStyleHelper::dpiScaled(11.));
         break;
         // Returns the number of pixels to use for the business part of the
         // slider (i.e., the non-tickmark portion). The remaining space is shared
         // equally between the tickmark regions.
     case PM_SliderControlThickness:
         if (const QStyleOptionSlider *sl = qstyleoption_cast<const QStyleOptionSlider *>(opt)) {
             int space = (sl->orientation == Qt::Horizontal) ? sl->rect.height() : sl->rect.width();
             int ticks = sl->tickPosition;
             int n = 0;
             if (ticks & QSlider::TicksAbove)
                 ++n;
             if (ticks & QSlider::TicksBelow)
                 ++n;
             if (!n) {
                 ret = space;
                 break;
             }
             int thick = 6;        // Magic constant to get 5 + 16 + 5
             if (ticks != QSlider::TicksBothSides && ticks != QSlider::NoTicks)
                 thick += proxy()->pixelMetric(PM_SliderLength, sl, widget) / 4;
             space -= thick;
             if (space > 0)
                 thick += (space * 2) / (n + 2);
             ret = thick;
         } else {
             ret = 0;
         }
         break;
 #endif // QT_NO_SLIDER
 #ifndef QT_NO_MENU
     case PM_MenuBarHMargin:
         ret = 0;
         break;
     case PM_MenuBarVMargin:
         ret = 0;
         break;
     case PM_MenuBarPanelWidth:
         ret = 0;
         break;
     case PM_SmallIconSize:
         ret = int(QStyleHelper::dpiScaled(16.));
         break;
     case PM_LargeIconSize:
         ret = int(QStyleHelper::dpiScaled(32.));
         break;
     case PM_IconViewIconSize:
         ret = proxy()->pixelMetric(PM_LargeIconSize, opt, widget);
         break;
     case PM_DockWidgetTitleMargin:
         ret = int(QStyleHelper::dpiScaled(2.));
         break;
     case PM_DockWidgetTitleBarButtonMargin:
         ret = int(QStyleHelper::dpiScaled(4.));
         break;
 #if defined(Q_WS_WIN)
     case PM_DockWidgetFrameWidth:
 #if defined(Q_OS_WINCE)
         ret = GetSystemMetrics(SM_CXDLGFRAME);
 #else
         ret = GetSystemMetrics(SM_CXFRAME);
 #endif
         break;
 #else
     case PM_DockWidgetFrameWidth:
         ret = 4;
         break;
 #endif // Q_WS_WIN
     break;
 #endif // QT_NO_MENU
 #if defined(Q_WS_WIN)
     case PM_TitleBarHeight:
 #ifdef QT3_SUPPORT
         // qt3 dockwindow height should be equal to tool windows
         if (widget && widget->inherits("Q3DockWindowTitleBar")) {
             ret = GetSystemMetrics(SM_CYSMCAPTION) - 1;
         } else
 #endif
         if (widget && (widget->windowType() == Qt::Tool)) {
             // MS always use one less than they say
 #if defined(Q_OS_WINCE)
             ret = GetSystemMetrics(SM_CYCAPTION) - 1;
 #else
             ret = GetSystemMetrics(SM_CYSMCAPTION) - 1;
 #endif
         } else {
             ret = GetSystemMetrics(SM_CYCAPTION) - 1;
         }
         break;
     case PM_ScrollBarExtent:
         {
 #ifndef Q_OS_WINCE
             NONCLIENTMETRICS ncm;
             ncm.cbSize = FIELD_OFFSET(NONCLIENTMETRICS, lfMessageFont) + sizeof(LOGFONT);
             if (SystemParametersInfo(SPI_GETNONCLIENTMETRICS, sizeof(NONCLIENTMETRICS), &ncm, 0))
                 ret = qMax(ncm.iScrollHeight, ncm.iScrollWidth);
             else
 #endif
                 ret = QCommonStyle::pixelMetric(pm, opt, widget);
         }
         break;
 #endif // Q_WS_WIN
     case PM_SplitterWidth:
         ret = qMax(4, QApplication::globalStrut().width());
         break;
 #if defined(Q_WS_WIN)
     case PM_MdiSubWindowFrameWidth:
 #if defined(Q_OS_WINCE)
         ret = GetSystemMetrics(SM_CYDLGFRAME);
 #else
         ret = GetSystemMetrics(SM_CYFRAME);
 #endif
         break;
     case PM_TextCursorWidth: {
         DWORD caretWidth = 1;
 #if defined(SPI_GETCARETWIDTH)
         SystemParametersInfo(SPI_GETCARETWIDTH, 0, &caretWidth, 0);
 #endif
         ret = (int)caretWidth;
         break; }
 #endif
     case PM_ToolBarItemMargin:
         ret = 1;
         break;
     case PM_ToolBarItemSpacing:
         ret = 0;
         break;
     case PM_ToolBarHandleExtent:
         ret = int(QStyleHelper::dpiScaled(10.));
         break;
     default:
         ret = QCommonStyle::pixelMetric(pm, opt, widget);
         break;
     }
     return ret;
 }
polish() [1/3]
void QWindowsStyle::polish (QApplication * app) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsVistaStyle, and QWindowsXPStyle.
Definition at line 309 of file qwindowsstyle.cpp.
Referenced by QWindowsXPStyle::polish(), QMacStyle::polish(), QWindowsVistaStyle::polish(), QPlastiqueStyle::polish(), QWindowsMobileStyle::polish(), QWindowsCEStyle::polish(), QCleanlooksStyle::polish(), and QStyleSheetStyle::polish().
 {
     QCommonStyle::polish(app);
     QWindowsStylePrivate *d = const_cast<QWindowsStylePrivate*>(d_func());
     // We only need the overhead when shortcuts are sometimes hidden
     if (!proxy()->styleHint(SH_UnderlineShortcut, 0) && app)
         app->installEventFilter(this);
     d->activeCaptionColor = app->palette().highlight().color();
     d->activeGradientCaptionColor = app->palette().highlight() .color();
     d->inactiveCaptionColor = app->palette().dark().color();
     d->inactiveGradientCaptionColor = app->palette().dark().color();
     d->inactiveCaptionText = app->palette().background().color();
 #if defined(Q_WS_WIN) //fetch native title bar colors
     if(app->desktopSettingsAware()){
         DWORD activeCaption = GetSysColor(COLOR_ACTIVECAPTION);
         DWORD gradientActiveCaption = GetSysColor(COLOR_GRADIENTACTIVECAPTION);
         DWORD inactiveCaption = GetSysColor(COLOR_INACTIVECAPTION);
         DWORD gradientInactiveCaption = GetSysColor(COLOR_GRADIENTINACTIVECAPTION);
         DWORD inactiveCaptionText = GetSysColor(COLOR_INACTIVECAPTIONTEXT);
         d->activeCaptionColor = colorref2qrgb(activeCaption);
         d->activeGradientCaptionColor = colorref2qrgb(gradientActiveCaption);
         d->inactiveCaptionColor = colorref2qrgb(inactiveCaption);
         d->inactiveGradientCaptionColor = colorref2qrgb(gradientInactiveCaption);
         d->inactiveCaptionText = colorref2qrgb(inactiveCaptionText);
     }
 #endif
 }
polish() [2/3]
void QWindowsStyle::polish (QWidget * widget) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsVistaStyle, and QWindowsXPStyle.
Definition at line 347 of file qwindowsstyle.cpp.
 {
     QCommonStyle::polish(widget);
 #ifndef QT_NO_PROGRESSBAR
     if (qobject_cast<QProgressBar *>(widget))
         widget->installEventFilter(this);
 #endif
 }
polish() [3/3]
void QWindowsStyle::polish (QPalette & pal) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsVistaStyle, and QWindowsXPStyle.
Definition at line 372 of file qwindowsstyle.cpp.
 {
     QCommonStyle::polish(pal);
 }
sizeFromContents()
QSize QWindowsStyle::sizeFromContents (ContentsType ct, const QStyleOption * opt, const QSize & contentsSize, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 3187 of file qwindowsstyle.cpp.
Referenced by QWindowsVistaStyle::sizeFromContents(), QPlastiqueStyle::sizeFromContents(), QWindowsMobileStyle::sizeFromContents(), QWindowsCEStyle::sizeFromContents(), QCleanlooksStyle::sizeFromContents(), QWindowsXPStyle::sizeFromContents(), QMacStyle::sizeFromContents(), and QStyleSheetStyle::sizeFromContents().
 {
     QSize sz(csz);
     switch (ct) {
     case CT_PushButton:
         if (const QStyleOptionButton *btn = qstyleoption_cast<const QStyleOptionButton *>(opt)) {
             sz = QCommonStyle::sizeFromContents(ct, opt, csz, widget);
             int w = sz.width(),
                 h = sz.height();
             int defwidth = 0;
             if (btn->features & QStyleOptionButton::AutoDefaultButton)
                 defwidth = 2 * proxy()->pixelMetric(PM_ButtonDefaultIndicator, btn, widget);
             int minwidth = int(QStyleHelper::dpiScaled(75.));
             int minheight = int(QStyleHelper::dpiScaled(23.));
 #ifndef QT_QWS_SMALL_PUSHBUTTON
             if (w < minwidth + defwidth && !btn->text.isEmpty())
                 w = minwidth + defwidth;
             if (h < minheight + defwidth)
                 h = minheight + defwidth;
 #endif
             sz = QSize(w, h);
         }
         break;
 #ifndef QT_NO_MENU
     case CT_MenuItem:
         if (const QStyleOptionMenuItem *mi = qstyleoption_cast<const QStyleOptionMenuItem *>(opt)) {
             int w = sz.width();
             sz = QCommonStyle::sizeFromContents(ct, opt, csz, widget);
             if (mi->menuItemType == QStyleOptionMenuItem::Separator) {
                 sz = QSize(10, QWindowsStylePrivate::windowsSepHeight);
             }
             else if (mi->icon.isNull()) {
                 sz.setHeight(sz.height() - 2);
                 w -= 6;
             }
             if (mi->menuItemType != QStyleOptionMenuItem::Separator && !mi->icon.isNull()) {
                 int iconExtent = proxy()->pixelMetric(PM_SmallIconSize, opt, widget);
                 sz.setHeight(qMax(sz.height(),
                                   mi->icon.actualSize(QSize(iconExtent, iconExtent)).height()
                                   + 2 * QWindowsStylePrivate::windowsItemFrame));
             }
             int maxpmw = mi->maxIconWidth;
             int tabSpacing = 20;
             if (mi->text.contains(QLatin1Char('\t')))
                 w += tabSpacing;
             else if (mi->menuItemType == QStyleOptionMenuItem::SubMenu)
                 w += 2 * QWindowsStylePrivate::windowsArrowHMargin;
             else if (mi->menuItemType == QStyleOptionMenuItem::DefaultItem) {
                 // adjust the font and add the difference in size.
                 // it would be better if the font could be adjusted in the initStyleOption qmenu func!!
                 QFontMetrics fm(mi->font);
                 QFont fontBold = mi->font;
                 fontBold.setBold(true);
                 QFontMetrics fmBold(fontBold);
                 w += fmBold.width(mi->text) - fm.width(mi->text);
             }
             int checkcol = qMax<int>(maxpmw, QWindowsStylePrivate::windowsCheckMarkWidth); // Windows always shows a check column
             w += checkcol;
             w += int(QWindowsStylePrivate::windowsRightBorder) + 10;
             sz.setWidth(w);
         }
         break;
 #endif // QT_NO_MENU
 #ifndef QT_NO_MENUBAR
     case CT_MenuBarItem:
         if (!sz.isEmpty())
             sz += QSize(QWindowsStylePrivate::windowsItemHMargin * 4, QWindowsStylePrivate::windowsItemVMargin * 2);
         break;
 #endif
                 // Otherwise, fall through
     case CT_ToolButton:
         if (qstyleoption_cast<const QStyleOptionToolButton *>(opt))
             return sz += QSize(7, 6);
         // Otherwise, fall through
     default:
         sz = QCommonStyle::sizeFromContents(ct, opt, csz, widget);
     }
     return sz;
 }
standardIconImplementation
QIcon QWindowsStyle::standardIconImplementation (StandardPixmap standardIcon, const QStyleOption * option, const QWidget * widget = 0) const protected slot
Warning
This function is not part of the public interface.
Definition at line 3276 of file qwindowsstyle.cpp.
Referenced by QStyleSheetStyle::deref(), QWindowsXPStyle::standardIconImplementation(), QWindowsVistaStyle::standardIconImplementation(), QPlastiqueStyle::standardIconImplementation(), QCleanlooksStyle::standardIconImplementation(), and QMacStyle::standardIconImplementation().
 {
     QIcon icon;
     QPixmap pixmap;
 #ifdef Q_OS_WIN
     switch (standardIcon) {
     case SP_FileDialogNewFolder:
     {
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(319, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     }
     case SP_DirHomeIcon:
     {
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(235, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     }
     case SP_DirIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(4, size);
             icon.addPixmap(pixmap, QIcon::Normal, QIcon::Off);
             pixmap = loadIconFromShell32(5, size);
             icon.addPixmap(pixmap, QIcon::Normal, QIcon::On);
         }
         break;
     case SP_DirLinkIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             QPixmap link = loadIconFromShell32(30, size);
             pixmap = loadIconFromShell32(4, size);
             if (!pixmap.isNull() && !link.isNull()) {
                 QPainter painter(&pixmap);
                 painter.drawPixmap(0, 0, size, size, link);
                 icon.addPixmap(pixmap, QIcon::Normal, QIcon::Off);
             }
             link = loadIconFromShell32(30, size);
             pixmap = loadIconFromShell32(5, size);
             if (!pixmap.isNull() && !link.isNull()) {
                 QPainter painter(&pixmap);
                 painter.drawPixmap(0, 0, size, size, link);
                 icon.addPixmap(pixmap, QIcon::Normal, QIcon::On);
             }
         }
         break;
     case SP_FileIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(1, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     case SP_ComputerIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(16, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     case SP_DesktopIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(35, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     case SP_DriveCDIcon:
     case SP_DriveDVDIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(12, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     case SP_DriveNetIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(10, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     case SP_DriveHDIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(9, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     case SP_DriveFDIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             pixmap = loadIconFromShell32(7, size);
             icon.addPixmap(pixmap, QIcon::Normal);
         }
         break;
     case SP_FileLinkIcon:
         for (int size = 16 ; size <= 32 ; size += 16) {
             QPixmap link;
             link = loadIconFromShell32(30, size);
             pixmap = loadIconFromShell32(1, size);
             if (!pixmap.isNull() && !link.isNull()) {
                 QPainter painter(&pixmap);
                 painter.drawPixmap(0, 0, size, size, link);
                 icon.addPixmap(pixmap, QIcon::Normal);
             }
         }
         break;
     case SP_VistaShield:
         {
             if (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA
                 && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)
                 && pSHGetStockIconInfo)
             {
                 icon.addPixmap(proxy()->standardPixmap(SP_VistaShield, option, widget)); //fetches small icon
                 QSHSTOCKICONINFO iconInfo; //append large icon
                 memset(&iconInfo, 0, sizeof(iconInfo));
                 iconInfo.cbSize = sizeof(iconInfo);
                 if (pSHGetStockIconInfo(_SIID_SHIELD, _SHGFI_ICON | _SHGFI_LARGEICON, &iconInfo) == S_OK) {
                     icon.addPixmap(QPixmap::fromWinHICON(iconInfo.hIcon));
                     DestroyIcon(iconInfo.hIcon);
                 }
             }
         }
         break;
     default:
         break;
     }
 #endif
     if (icon.isNull())
         icon = QCommonStyle::standardIconImplementation(standardIcon, option, widget);
     return icon;
 }
standardPixmap()
QPixmap QWindowsStyle::standardPixmap (StandardPixmap standardPixmap, const QStyleOption * opt, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 966 of file qwindowsstyle.cpp.
Referenced by standardIconImplementation(), QWindowsVistaStyle::standardPixmap(), QWindowsMobileStyle::standardPixmap(), QPlastiqueStyle::standardPixmap(), QWindowsCEStyle::standardPixmap(), QCleanlooksStyle::standardPixmap(), QWindowsXPStyle::standardPixmap(), and QMacStyle::standardPixmap().
 {
 #if defined(Q_WS_WIN) && !defined(Q_OS_WINCE)
     QPixmap desktopIcon;
     switch(standardPixmap) {
     case SP_DriveCDIcon:
     case SP_DriveDVDIcon:
         {
             desktopIcon = loadIconFromShell32(12, 16);
             break;
         }
     case SP_DriveNetIcon:
         {
             desktopIcon = loadIconFromShell32(10, 16);
             break;
         }
     case SP_DriveHDIcon:
         {
             desktopIcon = loadIconFromShell32(9, 16);
             break;
         }
     case SP_DriveFDIcon:
         {
             desktopIcon = loadIconFromShell32(7, 16);
             break;
         }
     case SP_FileIcon:
         {
             desktopIcon = loadIconFromShell32(1, 16);
             break;
         }
     case SP_FileLinkIcon:
         {
             desktopIcon = loadIconFromShell32(1, 16);
             QPainter painter(&desktopIcon);
             QPixmap link = loadIconFromShell32(30, 16);
             painter.drawPixmap(0, 0, 16, 16, link);
             break;
         }
     case SP_DirLinkIcon:
         {
             desktopIcon = loadIconFromShell32(4, 16);
             QPainter painter(&desktopIcon);
             QPixmap link = loadIconFromShell32(30, 16);
             painter.drawPixmap(0, 0, 16, 16, link);
             break;
         }
     case SP_DirClosedIcon:
         {
             desktopIcon = loadIconFromShell32(4, 16);
             break;
         }
     case SP_DesktopIcon:
         {
             desktopIcon = loadIconFromShell32(35, 16);
             break;
         }
     case SP_ComputerIcon:
         {
             desktopIcon = loadIconFromShell32(16, 16);
             break;
         }
     case SP_DirOpenIcon:
         {
             desktopIcon = loadIconFromShell32(5, 16);
             break;
         }
     case SP_FileDialogNewFolder:
         {
             desktopIcon = loadIconFromShell32(319, 16);
             break;
         }
     case SP_DirHomeIcon:
         {
             desktopIcon = loadIconFromShell32(235, 16);
             break;
         }
     case SP_TrashIcon:
         {
             desktopIcon = loadIconFromShell32(191, 16);
             break;
         }
     case SP_MessageBoxInformation:
         {
             HICON iconHandle = LoadIcon(NULL, IDI_INFORMATION);
             desktopIcon = QPixmap::fromWinHICON( iconHandle );
             DestroyIcon(iconHandle);
             break;
         }
     case SP_MessageBoxWarning:
         {
             HICON iconHandle = LoadIcon(NULL, IDI_WARNING);
             desktopIcon = QPixmap::fromWinHICON( iconHandle );
             DestroyIcon(iconHandle);
             break;
         }
     case SP_MessageBoxCritical:
         {
             HICON iconHandle = LoadIcon(NULL, IDI_ERROR);
             desktopIcon = QPixmap::fromWinHICON( iconHandle );
             DestroyIcon(iconHandle);
             break;
         }
     case SP_MessageBoxQuestion:
         {
             HICON iconHandle = LoadIcon(NULL, IDI_QUESTION);
             desktopIcon = QPixmap::fromWinHICON( iconHandle );
             DestroyIcon(iconHandle);
             break;
         }
     case SP_VistaShield:
         {
             if (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA
                 && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)
                 && pSHGetStockIconInfo)
             {
                 QPixmap pixmap;
                 QSHSTOCKICONINFO iconInfo;
                 memset(&iconInfo, 0, sizeof(iconInfo));
                 iconInfo.cbSize = sizeof(iconInfo);
                 if (pSHGetStockIconInfo(_SIID_SHIELD, _SHGFI_ICON | _SHGFI_SMALLICON, &iconInfo) == S_OK) {
                     pixmap = QPixmap::fromWinHICON(iconInfo.hIcon);
                     DestroyIcon(iconInfo.hIcon);
                     return pixmap;
                 }
             }
         }
         break;
     default:
         break;
     }
     if (!desktopIcon.isNull()) {
         return desktopIcon;
     }
 #endif
 #ifndef QT_NO_IMAGEFORMAT_XPM
     switch (standardPixmap) {
     case SP_TitleBarMenuButton:
         return QPixmap(qt_menu_xpm);
     case SP_TitleBarShadeButton:
         return QPixmap(qt_shade_xpm);
     case SP_TitleBarUnshadeButton:
         return QPixmap(qt_unshade_xpm);
     case SP_TitleBarNormalButton:
         return QPixmap(qt_normalizeup_xpm);
     case SP_TitleBarMinButton:
         return QPixmap(qt_minimize_xpm);
     case SP_TitleBarMaxButton:
         return QPixmap(qt_maximize_xpm);
     case SP_TitleBarCloseButton:
         return QPixmap(qt_close_xpm);
     case SP_TitleBarContextHelpButton:
         return QPixmap(qt_help_xpm);
     case SP_DockWidgetCloseButton:
         return QPixmap(dock_widget_close_xpm);
     case SP_MessageBoxInformation:
         return QPixmap(information_xpm);
     case SP_MessageBoxWarning:
         return QPixmap(warning_xpm);
     case SP_MessageBoxCritical:
         return QPixmap(critical_xpm);
     case SP_MessageBoxQuestion:
         return QPixmap(question_xpm);
     default:
         break;
     }
 #endif //QT_NO_IMAGEFORMAT_XPM
     return QCommonStyle::standardPixmap(standardPixmap, opt, widget);
 }
styleHint()
int QWindowsStyle::styleHint (StyleHint hint, const QStyleOption * opt = 0, const QWidget * widget = 0, QStyleHintReturn * returnData = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 1138 of file qwindowsstyle.cpp.
Referenced by drawComplexControl(), drawControl(), drawPrimitive(), QPlastiqueStyle::styleHint(), QWindowsXPStyle::styleHint(), QCleanlooksStyle::styleHint(), QWindowsCEStyle::styleHint(), QWindowsMobileStyle::styleHint(), and QMacStyle::styleHint().
 {
     int ret = 0;
     switch (hint) {
     case SH_EtchDisabledText:
     case SH_Slider_SnapToValue:
     case SH_PrintDialog_RightAlignButtons:
     case SH_FontDialog_SelectAssociatedText:
     case SH_Menu_AllowActiveAndDisabled:
     case SH_MenuBar_AltKeyNavigation:
     case SH_MenuBar_MouseTracking:
     case SH_Menu_MouseTracking:
     case SH_ComboBox_ListMouseTracking:
     case SH_ScrollBar_StopMouseOverSlider:
     case SH_MainWindow_SpaceBelowMenuBar:
         ret = 1;
         break;
     case SH_ItemView_ShowDecorationSelected:
 #ifndef QT_NO_LISTVIEW
         if (qobject_cast<const QListView*>(widget))
             ret = 1;
 #endif
         break;
     case SH_ItemView_ChangeHighlightOnFocus:
         ret = 1;
         break;
     case SH_ToolBox_SelectedPageTitleBold:
         ret = 0;
         break;
 #if defined(Q_WS_WIN)
     case SH_UnderlineShortcut:
     {
         ret = 1;
         BOOL cues = false;
         SystemParametersInfo(SPI_GETKEYBOARDCUES, 0, &cues, 0);
         ret = int(cues);
         // Do nothing if we always paint underlines
         Q_D(const QWindowsStyle);
         if (!ret && widget && d) {
 #ifndef QT_NO_MENUBAR
             const QMenuBar *menuBar = qobject_cast<const QMenuBar *>(widget);
             if (!menuBar && qobject_cast<const QMenu *>(widget)) {
                 QWidget *w = QApplication::activeWindow();
                 if (w && w != widget)
                     menuBar = w->findChild<QMenuBar *>();
             }
             // If we paint a menu bar draw underlines if is in the keyboardState
             if (menuBar) {
                 if (menuBar->d_func()->keyboardState || d->altDown())
                     ret = 1;
                 // Otherwise draw underlines if the toplevel widget has seen an alt-press
             } else
 #endif // QT_NO_MENUBAR
             if (d->hasSeenAlt(widget)) {
                 ret = 1;
             }
         }
         break;
     }
 #endif
 #ifndef QT_NO_RUBBERBAND
     case SH_RubberBand_Mask:
         if (const QStyleOptionRubberBand *rbOpt = qstyleoption_cast<const QStyleOptionRubberBand *>(opt)) {
             ret = 0;
             if (rbOpt->shape == QRubberBand::Rectangle) {
                 ret = true;
                 if(QStyleHintReturnMask *mask = qstyleoption_cast<QStyleHintReturnMask*>(returnData)) {
                     mask->region = opt->rect;
                     int size = 1;
                     if (widget && widget->isWindow())
                         size = 4;
                     mask->region -= opt->rect.adjusted(size, size, -size, -size);
                 }
             }
         }
         break;
 #endif // QT_NO_RUBBERBAND
     case SH_LineEdit_PasswordCharacter:
         {
 #ifdef Q_WS_WIN
             if (widget && (QSysInfo::WindowsVersion >= QSysInfo::WV_XP && (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based))) {
                 const QFontMetrics &fm = widget->fontMetrics();
                 if (fm.inFont(QChar(0x25CF)))
                     ret = 0x25CF;
                 else if (fm.inFont(QChar(0x2022)))
                     ret = 0x2022;
             }
 #endif
             if (!ret)
                 ret = '*';
         }
         break;
 #ifndef QT_NO_WIZARD
     case SH_WizardStyle:
         ret = QWizard::ModernStyle;
         break;
 #endif
     case SH_ItemView_ArrowKeysNavigateIntoChildren:
         ret = true;
         break;
     case SH_DialogButtonBox_ButtonsHaveIcons:
         ret = 0;
         break;
     default:
         ret = QCommonStyle::styleHint(hint, opt, widget, returnData);
         break;
     }
     return ret;
 }
subElementRect()
QRect QWindowsStyle::subElementRect (SubElement r, const QStyleOption * opt, const QWidget * widget = 0) const virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsXPStyle, and QWindowsVistaStyle.
Definition at line 2588 of file qwindowsstyle.cpp.
Referenced by drawComplexControl(), drawControl(), QWindowsVistaStyle::subElementRect(), QPlastiqueStyle::subElementRect(), QWindowsXPStyle::subElementRect(), QCleanlooksStyle::subElementRect(), QWindowsMobileStyle::subElementRect(), QWindowsCEStyle::subElementRect(), QMacStyle::subElementRect(), and QStyleSheetStyle::subElementRect().
 {
     QRect r;
     switch (sr) {
     case SE_SliderFocusRect:
     case SE_ToolBoxTabContents:
         r = visualRect(opt->direction, opt->rect, opt->rect);
         break;
     case SE_DockWidgetTitleBarText: {
         r = QCommonStyle::subElementRect(sr, opt, w);
         const QStyleOptionDockWidgetV2 *v2
             = qstyleoption_cast<const QStyleOptionDockWidgetV2*>(opt);
         bool verticalTitleBar = v2 == 0 ? false : v2->verticalTitleBar;
         int m = proxy()->pixelMetric(PM_DockWidgetTitleMargin, opt, w);
         if (verticalTitleBar) {
             r.adjust(0, 0, 0, -m);
         } else {
             if (opt->direction == Qt::LeftToRight)
                 r.adjust(m, 0, 0, 0);
             else
                 r.adjust(0, 0, -m, 0);
         }
         break;
     }
     case SE_ProgressBarContents:
         r = QCommonStyle::subElementRect(SE_ProgressBarGroove, opt, w);
         r.adjust(3, 3, -3, -3);
         break;
     default:
         r = QCommonStyle::subElementRect(sr, opt, w);
     }
     return r;
 }
timerEvent()
void QWindowsStyle::timerEvent (QTimerEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 166 of file qwindowsstyle.cpp.
Referenced by QWindowsVistaStyle::event().
 {
 #ifndef QT_NO_PROGRESSBAR
     Q_D(QWindowsStyle);
     if (event->timerId() == d->animateTimer) {
         Q_ASSERT(d->animationFps> 0);
         d->animateStep = d->startTime.elapsed() / (1000 / d->animationFps);
         foreach (QProgressBar *bar, d->animatedProgressBars)
             bar->update();
     }
 #endif // QT_NO_PROGRESSBAR
     event->ignore();
 }
unpolish() [1/2]
void QWindowsStyle::unpolish (QApplication * app) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsVistaStyle, and QWindowsXPStyle.
Definition at line 340 of file qwindowsstyle.cpp.
Referenced by QWindowsXPStyle::unpolish(), QMacStyle::unpolish(), QPlastiqueStyle::unpolish(), QWindowsMobileStyle::unpolish(), QCleanlooksStyle::unpolish(), and QStyleSheetStyle::unpolish().
 {
     QCommonStyle::unpolish(app);
     app->removeEventFilter(this);
 }
unpolish() [2/2]
void QWindowsStyle::unpolish (QWidget * widget) virtual
Reimplemented Function
Reimplemented from QCommonStyle.
Reimplemented in QWindowsVistaStyle, and QWindowsXPStyle.
Definition at line 357 of file qwindowsstyle.cpp.
 {
     QCommonStyle::unpolish(widget);
 #ifndef QT_NO_PROGRESSBAR
     if (QProgressBar *bar=qobject_cast<QProgressBar *>(widget)) {
         Q_D(QWindowsStyle);
         widget->removeEventFilter(this);
         d->stopAnimation(this, bar);
     }
 #endif
 }
Properties
reserved
void* QWindowsStyle::reserved private
Definition at line 102 of file qwindowsstyle.h.
The documentation for this class was generated from the following files:
/src/gui/styles/qwindowsstyle.h
/src/gui/styles/qwindowsstyle.cpp