Qt 4.8: QDeclarativeListModelWorkerAgent Class Reference
QDeclarativeListModelWorkerAgent Class Reference
#include <qdeclarativelistmodelworkeragent_p.h>
Classes
struct Change
struct Data
struct Sync
struct VariantRef
Public Functions
void addref ()
Q_INVOKABLE void append (const QScriptValue &)
Q_INVOKABLE void clear ()
int count () const
Q_INVOKABLE QScriptValue get (int index) const
Q_INVOKABLE void insert (int index, const QScriptValue &)
Q_INVOKABLE void move (int from, int to, int count)
QDeclarativeListModelWorkerAgent (QDeclarativeListModel *)
void release ()
Q_INVOKABLE void remove (int index)
QScriptEngine * scriptEngine () const
Q_INVOKABLE void set (int index, const QScriptValue &)
Q_INVOKABLE void setProperty (int index, const QString &property, const QVariant &value)
void setScriptEngine (QScriptEngine *eng)
Q_INVOKABLE void sync ()
~QDeclarativeListModelWorkerAgent ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void changedData (int index, int count, const QList< int > &roles)
Properties
int count
Data data
QDeclarativeListModel * m_copy
QScriptEngine * m_engine
QDeclarativeListModel * m_orig
QAtomicInt m_ref
QMutex mutex
QWaitCondition syncDone
Friends
class FlatListScriptClass
class QDeclarativeWorkerScriptEnginePrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 72 of file qdeclarativelistmodelworkeragent_p.h.
Constructors and Destructors
QDeclarativeListModelWorkerAgent()
QDeclarativeListModelWorkerAgent::QDeclarativeListModelWorkerAgent (QDeclarativeListModel * model)
Definition at line 85 of file qdeclarativelistmodelworkeragent.cpp.
     : m_engine(0),
       m_ref(1),
       m_orig(model),
       m_copy(new QDeclarativeListModel(model, this))
 {
 }
~QDeclarativeListModelWorkerAgent()
QDeclarativeListModelWorkerAgent::~QDeclarativeListModelWorkerAgent ()
Definition at line 93 of file qdeclarativelistmodelworkeragent.cpp.
 {
 }
Functions
addref()
void QDeclarativeListModelWorkerAgent::addref ()
Definition at line 109 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeListModelWorkerAgent::VariantRef::operator=(), and QDeclarativeListModelWorkerAgent::VariantRef::VariantRef().
 {
     m_ref.ref();
 }
append()
void QDeclarativeListModelWorkerAgent::append (const QScriptValue & value)
Definition at line 143 of file qdeclarativelistmodelworkeragent.cpp.
 {
     int count = m_copy->count();
     m_copy->append(value);
     if (m_copy->count() != count)
         data.insertChange(m_copy->count() - 1, 1);
 }
changedData()
void QDeclarativeListModelWorkerAgent::changedData (int index, int count, const QList< int > & roles) private
Definition at line 201 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by FlatListScriptClass::setProperty().
 {
     data.changedChange(index, count, roles);
 }
clear()
void QDeclarativeListModelWorkerAgent::clear ()
Definition at line 127 of file qdeclarativelistmodelworkeragent.cpp.
 {
     data.clearChange();
     data.removeChange(0, m_copy->count());
     m_copy->clear();
 }
count()
int QDeclarativeListModelWorkerAgent::count () const
Referenced by append(), QDeclarativeListModelWorkerAgent::Data::changedChange(), insert(), QDeclarativeListModelWorkerAgent::Data::insertChange(), QDeclarativeListModelWorkerAgent::Data::moveChange(), release(), remove(), and QDeclarativeListModelWorkerAgent::Data::removeChange().
event()
bool QDeclarativeListModelWorkerAgent::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 206 of file qdeclarativelistmodelworkeragent.cpp.
 {
     if (e->type() == QEvent::User) {
         QMutexLocker locker(&mutex);
         Sync *s = static_cast<Sync *>(e);
         const QList<Change> &changes = s->data.changes;
         if (m_copy) {
             bool cc = m_orig->count() != s->list->count();
             FlatListModel *orig = m_orig->m_flat;
             FlatListModel *copy = s->list->m_flat;
             if (!orig || !copy) {
                 syncDone.wakeAll();
                 return QObject::event(e);
             }
             orig->m_roles = copy->m_roles;
             orig->m_strings = copy->m_strings;
             orig->m_values = copy->m_values;
             // update the orig->m_nodeData list
             for (int ii = 0; ii < changes.count(); ++ii) {
                 const Change &change = changes.at(ii);
                 switch (change.type) {
                 case Change::Inserted:
                     orig->insertedNode(change.index);
                     break;
                 case Change::Removed:
                     orig->removedNode(change.index);
                     break;
                 case Change::Moved:
                     orig->moveNodes(change.index, change.to, change.count);
                     break;
                 case Change::Changed:
                     break;
                 }
             }
             syncDone.wakeAll();
             locker.unlock();
             for (int ii = 0; ii < changes.count(); ++ii) {
                 const Change &change = changes.at(ii);
                 switch (change.type) {
                 case Change::Inserted:
                     emit m_orig->itemsInserted(change.index, change.count);
                     break;
                 case Change::Removed:
                     emit m_orig->itemsRemoved(change.index, change.count);
                     break;
                 case Change::Moved:
                     emit m_orig->itemsMoved(change.index, change.to, change.count);
                     break;
                 case Change::Changed:
                     emit m_orig->itemsChanged(change.index, change.count, change.roles);
                     break;
                 }
             }
             if (cc)
                 emit m_orig->countChanged();
         } else {
             syncDone.wakeAll();
         }
     }
     return QObject::event(e);
 }
get()
QScriptValue QDeclarativeListModelWorkerAgent::get (int index) const
Definition at line 161 of file qdeclarativelistmodelworkeragent.cpp.
 {
     return m_copy->get(index);
 }
insert()
void QDeclarativeListModelWorkerAgent::insert (int index, const QScriptValue & value)
Definition at line 152 of file qdeclarativelistmodelworkeragent.cpp.
 {
     int count = m_copy->count();
     m_copy->insert(index, value);
     if (m_copy->count() != count)
         data.insertChange(index, 1);
 }
move()
void QDeclarativeListModelWorkerAgent::move (int from, int to, int count)
Definition at line 182 of file qdeclarativelistmodelworkeragent.cpp.
 {
     m_copy->move(from, to, count);
     data.moveChange(from, to, count);
 }
release()
void QDeclarativeListModelWorkerAgent::release ()
Definition at line 114 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeListModelWorkerAgent::VariantRef::operator=(), QDeclarativeListModel::~QDeclarativeListModel(), and QDeclarativeListModelWorkerAgent::VariantRef::~VariantRef().
 {
     bool del = !m_ref.deref();
     if (del)
         delete this;
 }
remove()
void QDeclarativeListModelWorkerAgent::remove (int index)
Definition at line 134 of file qdeclarativelistmodelworkeragent.cpp.
 {
     int count = m_copy->count();
     m_copy->remove(index);
     if (m_copy->count() != count)
         data.removeChange(index, 1);
 }
scriptEngine()
QScriptEngine * QDeclarativeListModelWorkerAgent::scriptEngine () const
Definition at line 104 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue().
 {
     return m_engine;
 }
set()
void QDeclarativeListModelWorkerAgent::set (int index, const QScriptValue & value)
Definition at line 166 of file qdeclarativelistmodelworkeragent.cpp.
 {
     QList<int> roles;
     m_copy->set(index, value, &roles);
     if (!roles.isEmpty())
         data.changedChange(index, 1, roles);
 }
setProperty()
void QDeclarativeListModelWorkerAgent::setProperty (int index, const QString & property, const QVariant & value)
Definition at line 174 of file qdeclarativelistmodelworkeragent.cpp.
 {
     QList<int> roles;
     m_copy->setProperty(index, property, value, &roles);
     if (!roles.isEmpty())
         data.changedChange(index, 1, roles);
 }
setScriptEngine()
void QDeclarativeListModelWorkerAgent::setScriptEngine (QScriptEngine * eng)
Definition at line 97 of file qdeclarativelistmodelworkeragent.cpp.
Referenced by QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue().
 {
     m_engine = eng;
     if (m_copy->m_flat)
         m_copy->m_flat->m_scriptEngine = eng;
 }
sync()
void QDeclarativeListModelWorkerAgent::sync ()
Definition at line 188 of file qdeclarativelistmodelworkeragent.cpp.
 {
     Sync *s = new Sync;
     s->data = data;
     s->list = m_copy;
     data.changes.clear();
     mutex.lock();
     QCoreApplication::postEvent(this, s);
     syncDone.wait(&mutex);
     mutex.unlock();
 }
Friends and Related Functions
FlatListScriptClass
friend class FlatListScriptClass friend
Definition at line 119 of file qdeclarativelistmodelworkeragent_p.h.
QDeclarativeWorkerScriptEnginePrivate
friend class QDeclarativeWorkerScriptEnginePrivate friend
Definition at line 118 of file qdeclarativelistmodelworkeragent_p.h.
Properties
count
int QDeclarativeListModelWorkerAgent::count private
Definition at line 75 of file qdeclarativelistmodelworkeragent_p.h.
data
Data QDeclarativeListModelWorkerAgent::data private
Definition at line 139 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by append(), changedData(), clear(), insert(), move(), remove(), set(), setProperty(), and sync().
m_copy
QDeclarativeListModel* QDeclarativeListModelWorkerAgent::m_copy private
Definition at line 151 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by append(), clear(), event(), get(), insert(), move(), release(), remove(), set(), setProperty(), setScriptEngine(), and sync().
m_engine
QScriptEngine* QDeclarativeListModelWorkerAgent::m_engine private
Definition at line 120 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by scriptEngine(), and setScriptEngine().
m_orig
QDeclarativeListModel* QDeclarativeListModelWorkerAgent::m_orig private
Definition at line 150 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by event().
m_ref
QAtomicInt QDeclarativeListModelWorkerAgent::m_ref private
Definition at line 149 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by addref(), and release().
mutex
QMutex QDeclarativeListModelWorkerAgent::mutex private
Definition at line 152 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by event(), and sync().
syncDone
QWaitCondition QDeclarativeListModelWorkerAgent::syncDone private
Definition at line 153 of file qdeclarativelistmodelworkeragent_p.h.
Referenced by event(), and sync().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativelistmodelworkeragent_p.h
/src/declarative/util/qdeclarativelistmodelworkeragent.cpp