Qt 4.8: QXmlStreamWriter Class Reference
QXmlStreamWriter Class Reference
The QXmlStreamWriter class provides an XML writer with a simple streaming API.
#include <qxmlstream.h>
Public Functions
bool autoFormatting () const
This property controls whether or not the stream writer automatically formats the generated XML data.
int autoFormattingIndent () const
the number of spaces or tabs used for indentation when auto-formatting is enabled.
QTextCodec * codec () const
Returns the codec that is currently assigned to the stream.
QIODevice * device () const
Returns the current device associated with the QXmlStreamWriter, or 0 if no device has been assigned.
bool hasError () const
Returns true if the stream failed to write to the underlying device; otherwise returns false.
QXmlStreamWriter ()
Constructs a stream writer.
QXmlStreamWriter (QIODevice *device)
Constructs a stream writer that writes into device;.
QXmlStreamWriter (QByteArray *array)
Constructs a stream writer that writes into array.
QXmlStreamWriter (QString *string)
Constructs a stream writer that writes into string.
void setAutoFormatting (bool)
void setAutoFormattingIndent (int spacesOrTabs)
void setCodec (QTextCodec *codec)
Sets the codec for this stream to codec.
void setCodec (const char *codecName)
Sets the codec for this stream to the QTextCodec for the encoding specified by codecName.
void setDevice (QIODevice *device)
Sets the current device to device.
void writeAttribute (const QString &qualifiedName, const QString &value)
Writes an attribute with qualifiedName and value.
void writeAttribute (const QString &namespaceUri, const QString &name, const QString &value)
Writes an attribute with name and value, prefixed for the specified namespaceUri.
void writeAttribute (const QXmlStreamAttribute &attribute)
Writes the attribute.
void writeAttributes (const QXmlStreamAttributes &attributes)
Writes the attribute vector attributes.
void writeCDATA (const QString &text)
Writes text as CDATA section.
void writeCharacters (const QString &text)
Writes text.
void writeComment (const QString &text)
Writes text as XML comment, where text must not contain the forbidden sequence "--" or end with "-".
void writeCurrentToken (const QXmlStreamReader &reader)
Writes the current state of the reader.
void writeDefaultNamespace (const QString &namespaceUri)
Writes a default namespace declaration for namespaceUri.
void writeDTD (const QString &dtd)
Writes a DTD section.
void writeEmptyElement (const QString &qualifiedName)
Writes an empty element with qualified name qualifiedName.
void writeEmptyElement (const QString &namespaceUri, const QString &name)
Writes an empty element with name, prefixed for the specified namespaceUri.
void writeEndDocument ()
Closes all remaining open start elements and writes a newline.
void writeEndElement ()
Closes the previous start element.
void writeEntityReference (const QString &name)
Writes the entity reference name to the stream, as "&\a{name};".
void writeNamespace (const QString &namespaceUri, const QString &prefix=QString())
Writes a namespace declaration for namespaceUri with prefix.
void writeProcessingInstruction (const QString &target, const QString &data=QString())
Writes an XML processing instruction with target and data, where data must not contain the sequence "?>".
void writeStartDocument ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Writes a document start with XML version number "1.0".
void writeStartDocument (const QString &version)
Writes a document start with the XML version number version.
void writeStartDocument (const QString &version, bool standalone)
Writes a document start with the XML version number version and a standalone attribute standalone.
void writeStartElement (const QString &qualifiedName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Writes a start element with qualifiedName.
void writeStartElement (const QString &namespaceUri, const QString &name)
Writes a start element with name, prefixed for the specified namespaceUri.
void writeTextElement (const QString &qualifiedName, const QString &text)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Writes a text element with qualifiedName and text.
void writeTextElement (const QString &namespaceUri, const QString &name, const QString &text)
Writes a text element with name, prefixed for the specified namespaceUri, and text.
~QXmlStreamWriter ()
Destructor.
Properties
QScopedPointer< QXmlStreamWriterPrivate > d_ptr
Detailed Description
The QXmlStreamWriter class provides an XML writer with a simple streaming API.
Since
4.3
Note
This class or function is reentrant.
QXmlStreamWriter is the counterpart to QXmlStreamReader for writing XML. Like its related class, it operates on a QIODevice specified with setDevice(). The API is simple and straightforward: for every XML token or event you want to write, the writer provides a specialized function.
You start a document with writeStartDocument() and end it with writeEndDocument(). This will implicitly close all remaining open tags.
Element tags are opened with writeStartElement() followed by writeAttribute() or writeAttributes(), element content, and then writeEndElement(). A shorter form writeEmptyElement() can be used to write empty elements, followed by writeAttributes().
Element content consists of either characters, entity references or nested elements. It is written with writeCharacters(), which also takes care of escaping all forbidden characters and character sequences, writeEntityReference(), or subsequent calls to writeStartElement(). A convenience method writeTextElement() can be used for writing terminal elements that contain nothing but text.
The following abridged code snippet shows the basic use of the class to write formatted XML with indentation:
    QXmlStreamWriter stream(&output);
    stream.setAutoFormatting(true);
    stream.writeStartDocument();
...
    stream.writeStartElement("bookmark");
    stream.writeAttribute("href", "http://qt.nokia.com/");
    stream.writeTextElement("title", "Qt Home");
    stream.writeEndElement(); // bookmark
...
    stream.writeEndDocument();
QXmlStreamWriter takes care of prefixing namespaces, all you have to do is specify the namespaceUri when writing elements or attributes. If you must conform to certain prefixes, you can force the writer to use them by declaring the namespaces manually with either writeNamespace() or writeDefaultNamespace(). Alternatively, you can bypass the stream writer's namespace support and use overloaded methods that take a qualified name instead. The namespace http://www.w3.org/XML/1998/namespace is implicit and mapped to the prefix xml.
The stream writer can automatically format the generated XML data by adding line-breaks and indentation to empty sections between elements, making the XML data more readable for humans and easier to work with for most source code management systems. The feature can be turned on with the autoFormatting property, and customized with the autoFormattingIndent property.
Other functions are writeCDATA(), writeComment(), writeProcessingInstruction(), and writeDTD(). Chaining of XML streams is supported with writeCurrentToken().
By default, QXmlStreamWriter encodes XML in UTF-8. Different encodings can be enforced using setCodec().
If an error occurs while writing to the underlying device, hasError() starts returning true and subsequent writes are ignored.
The QXmlStream Bookmarks Example illustrates how to use a stream writer to write an XML bookmark file (XBEL) that was previously read in by a QXmlStreamReader.
Definition at line 416 of file qxmlstream.h.
Constructors and Destructors
QXmlStreamWriter() [1/4]
QXmlStreamWriter::QXmlStreamWriter ()
Constructs a stream writer.
See also
setDevice()
Definition at line 3368 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamWriterPrivate(this))
 {
 }
QXmlStreamWriter() [2/4]
QXmlStreamWriter::QXmlStreamWriter (QIODevice * device)
Constructs a stream writer that writes into device;.
Definition at line 3376 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamWriterPrivate(this))
 {
     Q_D(QXmlStreamWriter);
     d->device = device;
 }
QXmlStreamWriter() [3/4]
QXmlStreamWriter::QXmlStreamWriter (QByteArray * array)
Constructs a stream writer that writes into array.
This is the same as creating an xml writer that operates on a QBuffer device which in turn operates on array.
Definition at line 3387 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamWriterPrivate(this))
 {
     Q_D(QXmlStreamWriter);
     d->device = new QBuffer(array);
     d->device->open(QIODevice::WriteOnly);
     d->deleteDevice = true;
 }
QXmlStreamWriter() [4/4]
QXmlStreamWriter::QXmlStreamWriter (QString * string)
Constructs a stream writer that writes into string.
Definition at line 3399 of file qxmlstream.cpp.
     : d_ptr(new QXmlStreamWriterPrivate(this))
 {
     Q_D(QXmlStreamWriter);
     d->stringDevice = string;
 }
~QXmlStreamWriter()
QXmlStreamWriter::~QXmlStreamWriter ()
Destructor.
Definition at line 3409 of file qxmlstream.cpp.
 {
 }
Functions
autoFormatting()
bool QXmlStreamWriter::autoFormatting () const
This property controls whether or not the stream writer automatically formats the generated XML data.
Since
4.4 the auto-formatting flag of the stream writer
If enabled, the writer automatically adds line-breaks and indentation to empty sections between elements (ignorable whitespace). The main purpose of auto-formatting is to split the data into several lines, and to increase readability for a human reader. The indentation depth can be controlled through the autoFormattingIndent property.
By default, auto-formatting is disabled.
Since
4.4
Returns true if auto formattting is enabled, otherwise false.
Definition at line 3532 of file qxmlstream.cpp.
Referenced by QXmlStreamWriterPrivate::writeStartElement().
 {
     Q_D(const QXmlStreamWriter);
     return d->autoFormatting;
 }
autoFormattingIndent()
int QXmlStreamWriter::autoFormattingIndent () const
the number of spaces or tabs used for indentation when auto-formatting is enabled.
Positive numbers indicate spaces, negative numbers tabs.
Since
4.4
The default indentation is 4.
See also
autoFormatting
Definition at line 3561 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamWriter);
     return d->autoFormattingIndent.count(' ') - d->autoFormattingIndent.count('\t');
 }
codec()
QTextCodec * QXmlStreamWriter::codec () const
Returns the codec that is currently assigned to the stream.
See also
setCodec()
Definition at line 3487 of file qxmlstream.cpp.
Referenced by setCodec().
 {
     Q_D(const QXmlStreamWriter);
     return d->codec;
 }
device()
QIODevice * QXmlStreamWriter::device () const
Returns the current device associated with the QXmlStreamWriter, or 0 if no device has been assigned.
See also
setDevice()
Definition at line 3439 of file qxmlstream.cpp.
Referenced by QXmlStreamWriter(), and setDevice().
 {
     Q_D(const QXmlStreamWriter);
     return d->device;
 }
hasError()
bool QXmlStreamWriter::hasError () const
Returns true if the stream failed to write to the underlying device; otherwise returns false.
Since
4.8
The error status is never reset. Writes happening after the error occurred are ignored, even if the error condition is cleared.
Definition at line 3579 of file qxmlstream.cpp.
 {
     Q_D(const QXmlStreamWriter);
     return d->hasError;
 }
setAutoFormatting()
void QXmlStreamWriter::setAutoFormatting (bool enable)
Since
4.4
Enables auto formatting if enable is true, otherwise disables it.
The default value is false.
Definition at line 3521 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll().
 {
     Q_D(QXmlStreamWriter);
     d->autoFormatting = enable;
 }
setAutoFormattingIndent()
void QXmlStreamWriter::setAutoFormattingIndent (int spacesOrTabs)
Definition at line 3555 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll().
 {
     Q_D(QXmlStreamWriter);
     d->autoFormattingIndent = QByteArray(qAbs(spacesOrTabs), spacesOrTabs >= 0 ? ' ' : '\t');
 }
setCodec() [1/2]
void QXmlStreamWriter::setCodec (QTextCodec * codec)
Sets the codec for this stream to codec.
The codec is used for encoding any data that is written. By default, QXmlStreamWriter uses UTF-8.
The encoding information is stored in the initial xml tag which gets written when you call writeStartDocument(). Call this function before calling writeStartDocument().
See also
codec()
Definition at line 3458 of file qxmlstream.cpp.
Referenced by setCodec(), and QTextOdfWriter::writeAll().
 {
     Q_D(QXmlStreamWriter);
     if (codec) {
         d->codec = codec;
         delete d->encoder;
         d->encoder = codec->makeEncoder(QTextCodec::IgnoreHeader); // no byte order mark for utf8
         d->checkIfASCIICompatibleCodec();
     }
 }
setCodec() [2/2]
void QXmlStreamWriter::setCodec (const char * codecName)
Sets the codec for this stream to the QTextCodec for the encoding specified by codecName.
Common values for codecName include "ISO 8859-1", "UTF-8", and "UTF-16". If the encoding isn't recognized, nothing happens.
See also
QTextCodec::codecForName()
Definition at line 3477 of file qxmlstream.cpp.
 {
     setCodec(QTextCodec::codecForName(codecName));
 }
setDevice()
void QXmlStreamWriter::setDevice (QIODevice * device)
Sets the current device to device.
If you want the stream to write into a QByteArray, you can create a QBuffer device.
See also
device()
Definition at line 3420 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamWriter);
     if (device == d->device)
         return;
     d->stringDevice = 0;
     if (d->deleteDevice) {
         delete d->device;
         d->deleteDevice = false;
     }
     d->device = device;
 }
writeAttribute() [1/3]
void QXmlStreamWriter::writeAttribute (const QString & qualifiedName, const QString & value)
Writes an attribute with qualifiedName and value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function can only be called after writeStartElement() before any content is written, or after writeEmptyElement().
Definition at line 3596 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll(), writeAttribute(), writeAttributes(), QTextOdfWriter::writeBlock(), QTextOdfWriter::writeBlockFormat(), QTextOdfWriter::writeCharacterFormat(), QTextOdfWriter::writeFrame(), QTextOdfWriter::writeFrameFormat(), QTextOdfWriter::writeInlineCharacter(), QTextOdfWriter::writeListFormat(), and QTextOdfWriter::writeTableCellFormat().
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(d->inStartElement);
     Q_ASSERT(qualifiedName.count(QLatin1Char(':')) <= 1);
     d->write(" ");
     d->write(qualifiedName);
     d->write("=\"");
     d->writeEscaped(value, true);
     d->write("\"");
 }
writeAttribute() [2/3]
void QXmlStreamWriter::writeAttribute (const QString & namespaceUri, const QString & name, const QString & value)
Writes an attribute with name and value, prefixed for the specified namespaceUri.
If the namespace has not been declared yet, QXmlStreamWriter will generate a namespace declaration for it.
This function can only be called after writeStartElement() before any content is written, or after writeEmptyElement().
Definition at line 3616 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(d->inStartElement);
     Q_ASSERT(!name.contains(QLatin1Char(':')));
     QXmlStreamWriterPrivate::NamespaceDeclaration &namespaceDeclaration = d->findNamespace(namespaceUri, true, true);
     d->write(" ");
     if (!namespaceDeclaration.prefix.isEmpty()) {
         d->write(namespaceDeclaration.prefix);
         d->write(":");
     }
     d->write(name);
     d->write("=\"");
     d->writeEscaped(value, true);
     d->write("\"");
 }
writeAttribute() [3/3]
void QXmlStreamWriter::writeAttribute (const QXmlStreamAttribute & attribute)
Writes the attribute.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function can only be called after writeStartElement() before any content is written, or after writeEmptyElement().
Definition at line 3644 of file qxmlstream.cpp.
 {
     if (attribute.namespaceUri().isEmpty())
         writeAttribute(attribute.qualifiedName().toString(),
                        attribute.value().toString());
     else
         writeAttribute(attribute.namespaceUri().toString(),
                        attribute.name().toString(),
                        attribute.value().toString());
 }
writeAttributes()
void QXmlStreamWriter::writeAttributes (const QXmlStreamAttributes & attributes)
Writes the attribute vector attributes.
If a namespace referenced in an attribute not been declared yet, QXmlStreamWriter will generate a namespace declaration for it.
This function can only be called after writeStartElement() before any content is written, or after writeEmptyElement().
See also
writeAttribute(), writeNamespace()
Definition at line 3665 of file qxmlstream.cpp.
Referenced by writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(d->inStartElement);
     Q_UNUSED(d);
     for (int i = 0; i < attributes.size(); ++i)
         writeAttribute(attributes.at(i));
 }
writeCDATA()
void QXmlStreamWriter::writeCDATA (const QString & text)
Writes text as CDATA section.
If text contains the forbidden character sequence "]]>", it is split into different CDATA sections.
This function mainly exists for completeness. Normally you should not need use it, because writeCharacters() automatically escapes all non-content characters.
Definition at line 3683 of file qxmlstream.cpp.
Referenced by writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     d->finishStartElement();
     QString copy(text);
     copy.replace(QLatin1String("]]>"), QLatin1String("]]]]><![CDATA[>"));
     d->write("<![CDATA[");
     d->write(copy);
     d->write("]]>");
 }
writeCharacters()
void QXmlStreamWriter::writeCharacters (const QString & text)
Writes text.
The characters "<", "&", and "\"" are escaped as entity references "<", "&, and "&quot;". To avoid the forbidden sequence "]]>", ">" is also escaped as "&gt;".
See also
writeEntityReference()
Definition at line 3701 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeBlock(), writeCurrentToken(), and writeTextElement().
 {
     Q_D(QXmlStreamWriter);
     d->finishStartElement();
     d->writeEscaped(text);
 }
writeComment()
void QXmlStreamWriter::writeComment (const QString & text)
Writes text as XML comment, where text must not contain the forbidden sequence "--" or end with "-".
Note that XML does not provide any way to escape "-" in a comment.
Definition at line 3713 of file qxmlstream.cpp.
Referenced by writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(!text.contains(QLatin1String("--")) && !text.endsWith(QLatin1Char('-')));
     if (!d->finishStartElement(false) && d->autoFormatting)
         d->indent(d->tagStack.size());
     d->write("<!--");
     d->write(text);
     d->write("-->");
     d->inStartElement = d->lastWasStartElement = false;
 }
writeCurrentToken()
void QXmlStreamWriter::writeCurrentToken (const QXmlStreamReader & reader)
Writes the current state of the reader.
All possible valid states are supported.
The purpose of this function is to support chained processing of XML data.
See also
QXmlStreamReader::tokenType()
Definition at line 4071 of file qxmlstream.cpp.
 {
     switch (reader.tokenType()) {
     case QXmlStreamReader::NoToken:
         break;
     case QXmlStreamReader::StartDocument:
         writeStartDocument();
         break;
     case QXmlStreamReader::EndDocument:
         writeEndDocument();
         break;
     case QXmlStreamReader::StartElement: {
         QXmlStreamNamespaceDeclarations namespaceDeclarations = reader.namespaceDeclarations();
         for (int i = 0; i < namespaceDeclarations.size(); ++i) {
             const QXmlStreamNamespaceDeclaration &namespaceDeclaration = namespaceDeclarations.at(i);
             writeNamespace(namespaceDeclaration.namespaceUri().toString(),
                            namespaceDeclaration.prefix().toString());
         }
         writeStartElement(reader.namespaceUri().toString(), reader.name().toString());
         writeAttributes(reader.attributes());
              } break;
     case QXmlStreamReader::EndElement:
         writeEndElement();
         break;
     case QXmlStreamReader::Characters:
         if (reader.isCDATA())
             writeCDATA(reader.text().toString());
         else
             writeCharacters(reader.text().toString());
         break;
     case QXmlStreamReader::Comment:
         writeComment(reader.text().toString());
         break;
     case QXmlStreamReader::DTD:
         writeDTD(reader.text().toString());
         break;
     case QXmlStreamReader::EntityReference:
         writeEntityReference(reader.name().toString());
         break;
     case QXmlStreamReader::ProcessingInstruction:
         writeProcessingInstruction(reader.processingInstructionTarget().toString(),
                                    reader.processingInstructionData().toString());
         break;
     default:
         Q_ASSERT(reader.tokenType() != QXmlStreamReader::Invalid);
         qWarning("QXmlStreamWriter: writeCurrentToken() with invalid state.");
         break;
     }
 }
writeDefaultNamespace()
void QXmlStreamWriter::writeDefaultNamespace (const QString & namespaceUri)
Writes a default namespace declaration for namespaceUri.
If writeStartElement() or writeEmptyElement() was called, the declaration applies to the current element; otherwise it applies to the next child element.
Note that the namespaces http://www.w3.org/XML/1998/namespace (bound to xmlns) and http://www.w3.org/2000/xmlns/ (bound to xml) by definition cannot be declared as default.
Definition at line 3915 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(namespaceUri != QLatin1String("http://www.w3.org/XML/1998/namespace"));
     Q_ASSERT(namespaceUri != QLatin1String("http://www.w3.org/2000/xmlns/"));
     QXmlStreamWriterPrivate::NamespaceDeclaration &namespaceDeclaration = d->namespaceDeclarations.push();
     namespaceDeclaration.prefix.clear();
     namespaceDeclaration.namespaceUri = d->addToStringStorage(namespaceUri);
     if (d->inStartElement)
         d->writeNamespaceDeclaration(namespaceDeclaration);
 }
writeDTD()
void QXmlStreamWriter::writeDTD (const QString & dtd)
Writes a DTD section.
The dtd represents the entire doctypedecl production from the XML 1.0 specification.
Definition at line 3729 of file qxmlstream.cpp.
Referenced by writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     d->finishStartElement();
     if (d->autoFormatting)
         d->write("\n");
     d->write(dtd);
     if (d->autoFormatting)
         d->write("\n");
 }
writeEmptyElement() [1/2]
void QXmlStreamWriter::writeEmptyElement (const QString & qualifiedName)
Writes an empty element with qualified name qualifiedName.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Subsequent calls to writeAttribute() will add attributes to this element.
Definition at line 3749 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeBlock(), QTextOdfWriter::writeBlockFormat(), QTextOdfWriter::writeCharacterFormat(), QTextOdfWriter::writeFrame(), QTextOdfWriter::writeFrameFormat(), QTextOdfWriter::writeListFormat(), and QTextOdfWriter::writeTableCellFormat().
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(qualifiedName.count(QLatin1Char(':')) <= 1);
     d->writeStartElement(QString(), qualifiedName);
     d->inEmptyElement = true;
 }
writeEmptyElement() [2/2]
void QXmlStreamWriter::writeEmptyElement (const QString & namespaceUri, const QString & name)
Writes an empty element with name, prefixed for the specified namespaceUri.
If the namespace has not been declared, QXmlStreamWriter will generate a namespace declaration for it. Subsequent calls to writeAttribute() will add attributes to this element.
See also
writeNamespace()
Definition at line 3765 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(!name.contains(QLatin1Char(':')));
     d->writeStartElement(namespaceUri, name);
     d->inEmptyElement = true;
 }
writeEndDocument()
void QXmlStreamWriter::writeEndDocument ()
Closes all remaining open start elements and writes a newline.
See also
writeStartDocument()
Definition at line 3812 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll(), and writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     while (d->tagStack.size())
         writeEndElement();
     d->write("\n");
 }
writeEndElement()
void QXmlStreamWriter::writeEndElement ()
Closes the previous start element.
See also
writeStartElement()
Definition at line 3825 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll(), QTextOdfWriter::writeBlock(), QTextOdfWriter::writeBlockFormat(), QTextOdfWriter::writeCharacterFormat(), writeCurrentToken(), writeEndDocument(), QTextOdfWriter::writeFormats(), QTextOdfWriter::writeFrame(), QTextOdfWriter::writeFrameFormat(), QTextOdfWriter::writeInlineCharacter(), QTextOdfWriter::writeListFormat(), QTextOdfWriter::writeTableCellFormat(), and writeTextElement().
 {
     Q_D(QXmlStreamWriter);
     if (d->tagStack.isEmpty())
         return;
     // shortcut: if nothing was written, close as empty tag
     if (d->inStartElement && !d->inEmptyElement) {
         d->write("/>");
         d->lastWasStartElement = d->inStartElement = false;
         QXmlStreamWriterPrivate::Tag &tag = d->tagStack_pop();
         d->lastNamespaceDeclaration = tag.namespaceDeclarationsSize;
         return;
     }
     if (!d->finishStartElement(false) && !d->lastWasStartElement && d->autoFormatting)
         d->indent(d->tagStack.size()-1);
     if (d->tagStack.isEmpty())
         return;
     d->lastWasStartElement = false;
     QXmlStreamWriterPrivate::Tag &tag = d->tagStack_pop();
     d->lastNamespaceDeclaration = tag.namespaceDeclarationsSize;
     d->write("</");
     if (!tag.namespaceDeclaration.prefix.isEmpty()) {
         d->write(tag.namespaceDeclaration.prefix);
         d->write(":");
     }
     d->write(tag.name);
     d->write(">");
 }
writeEntityReference()
void QXmlStreamWriter::writeEntityReference (const QString & name)
Writes the entity reference name to the stream, as "&\a{name};".
Definition at line 3861 of file qxmlstream.cpp.
Referenced by writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     d->finishStartElement();
     d->write("&");
     d->write(name);
     d->write(";");
 }
writeNamespace()
void QXmlStreamWriter::writeNamespace (const QString & namespaceUri, const QString & prefix = QString())
Writes a namespace declaration for namespaceUri with prefix.
If prefix is empty, QXmlStreamWriter assigns a unique prefix consisting of the letter 'n' followed by a number.
If writeStartElement() or writeEmptyElement() was called, the declaration applies to the current element; otherwise it applies to the next child element.
Note that the prefix xml is both predefined and reserved for http://www.w3.org/XML/1998/namespace, which in turn cannot be bound to any other prefix. The prefix xmlns and its URI http://www.w3.org/2000/xmlns/ are used for the namespace mechanism itself and thus completely forbidden in declarations.
Definition at line 3886 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll(), and writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(!namespaceUri.isEmpty());
     Q_ASSERT(prefix != QLatin1String("xmlns"));
     if (prefix.isEmpty()) {
         d->findNamespace(namespaceUri, d->inStartElement);
     } else {
         Q_ASSERT(!((prefix == QLatin1String("xml")) ^ (namespaceUri == QLatin1String("http://www.w3.org/XML/1998/namespace"))));
         Q_ASSERT(namespaceUri != QLatin1String("http://www.w3.org/2000/xmlns/"));
         QXmlStreamWriterPrivate::NamespaceDeclaration &namespaceDeclaration = d->namespaceDeclarations.push();
         namespaceDeclaration.prefix = d->addToStringStorage(prefix);
         namespaceDeclaration.namespaceUri = d->addToStringStorage(namespaceUri);
         if (d->inStartElement)
             d->writeNamespaceDeclaration(namespaceDeclaration);
     }
 }
writeProcessingInstruction()
void QXmlStreamWriter::writeProcessingInstruction (const QString & target, const QString & data = QString())
Writes an XML processing instruction with target and data, where data must not contain the sequence "?>".
Definition at line 3932 of file qxmlstream.cpp.
Referenced by writeCurrentToken().
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(!data.contains(QLatin1String("?>")));
     if (!d->finishStartElement(false) && d->autoFormatting)
         d->indent(d->tagStack.size());
     d->write("<?");
     d->write(target);
     if (!data.isNull()) {
         d->write(" ");
         d->write(data);
     }
     d->write("?>");
 }
writeStartDocument() [1/3]
void QXmlStreamWriter::writeStartDocument ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Writes a document start with XML version number "1.0".
This also writes the encoding information.
See also
writeEndDocument(), setCodec()
Since
4.5
Definition at line 3957 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll(), and writeCurrentToken().
 {
     writeStartDocument(QLatin1String("1.0"));
 }
writeStartDocument() [2/3]
void QXmlStreamWriter::writeStartDocument (const QString & version)
Writes a document start with the XML version number version.
See also
writeEndDocument()
Definition at line 3968 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamWriter);
     d->finishStartElement(false);
     d->write("<?xml version=\"");
     d->write(version);
     if (d->device) { // stringDevice does not get any encoding
         d->write("\" encoding=\"");
 #ifdef QT_NO_TEXTCODEC
         d->write("iso-8859-1");
 #else
         d->write(d->codec->name().constData(), d->codec->name().length());
 #endif
     }
     d->write("\"?>");
 }
writeStartDocument() [3/3]
void QXmlStreamWriter::writeStartDocument (const QString & version, bool standalone)
Writes a document start with the XML version number version and a standalone attribute standalone.
See also
writeEndDocument()
Since
4.5
Definition at line 3991 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamWriter);
     d->finishStartElement(false);
     d->write("<?xml version=\"");
     d->write(version);
     if (d->device) { // stringDevice does not get any encoding
         d->write("\" encoding=\"");
 #ifdef QT_NO_TEXTCODEC
         d->write("iso-8859-1");
 #else
         d->write(d->codec->name().constData(), d->codec->name().length());
 #endif
     }
     if (standalone)
         d->write("\" standalone=\"yes\"?>");
     else
         d->write("\" standalone=\"no\"?>");
 }
writeStartElement() [1/2]
void QXmlStreamWriter::writeStartElement (const QString & qualifiedName)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Writes a start element with qualifiedName.
Subsequent calls to writeAttribute() will add attributes to this element.
See also
writeEndElement(), writeEmptyElement()
Definition at line 4019 of file qxmlstream.cpp.
Referenced by QTextOdfWriter::writeAll(), QTextOdfWriter::writeBlock(), QTextOdfWriter::writeBlockFormat(), QTextOdfWriter::writeCharacterFormat(), writeCurrentToken(), QTextOdfWriter::writeFormats(), QTextOdfWriter::writeFrame(), QTextOdfWriter::writeFrameFormat(), QTextOdfWriter::writeInlineCharacter(), QTextOdfWriter::writeListFormat(), QTextOdfWriter::writeTableCellFormat(), and writeTextElement().
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(qualifiedName.count(QLatin1Char(':')) <= 1);
     d->writeStartElement(QString(), qualifiedName);
 }
writeStartElement() [2/2]
void QXmlStreamWriter::writeStartElement (const QString & namespaceUri, const QString & name)
Writes a start element with name, prefixed for the specified namespaceUri.
If the namespace has not been declared yet, QXmlStreamWriter will generate a namespace declaration for it. Subsequent calls to writeAttribute() will add attributes to this element.
See also
writeNamespace(), writeEndElement(), writeEmptyElement()
Definition at line 4035 of file qxmlstream.cpp.
 {
     Q_D(QXmlStreamWriter);
     Q_ASSERT(!name.contains(QLatin1Char(':')));
     d->writeStartElement(namespaceUri, name);
 }
writeTextElement() [1/2]
void QXmlStreamWriter::writeTextElement (const QString & qualifiedName, const QString & text)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. Writes a text element with qualifiedName and text.
This is a convenience function equivalent to:
        writeStartElement(qualifiedName);
        writeCharacters(text);
        writeEndElement();
Definition at line 3782 of file qxmlstream.cpp.
 {
     writeStartElement(qualifiedName);
     writeCharacters(text);
     writeEndElement();
 }
writeTextElement() [2/2]
void QXmlStreamWriter::writeTextElement (const QString & namespaceUri, const QString & name, const QString & text)
Writes a text element with name, prefixed for the specified namespaceUri, and text.
If the namespace has not been declared, QXmlStreamWriter will generate a namespace declaration for it.
This is a convenience function equivalent to:
        writeStartElement(namespaceUri, name);
        writeCharacters(text);
        writeEndElement();
Definition at line 3799 of file qxmlstream.cpp.
 {
     writeStartElement(namespaceUri, name);
     writeCharacters(text);
     writeEndElement();
 }
Properties
d_ptr
QScopedPointer<QXmlStreamWriterPrivate> QXmlStreamWriter::d_ptr private
Definition at line 482 of file qxmlstream.h.
The documentation for this class was generated from the following files:
/src/corelib/xml/qxmlstream.h
/src/corelib/xml/qxmlstream.cpp