Qt 4.8: QObjectPrivate Class Reference
QObjectPrivate Class Reference
#include <qobject_p.h>
Classes
struct Connection
struct ConnectionList
struct ExtraData
struct Sender
Public Types
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Detailed Description
Definition at line 98 of file qobject_p.h.
Typedefs
StaticMetaCallFunction
typedef void(* QObjectPrivate::StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Definition at line 113 of file qobject_p.h.
Constructors and Destructors
QObjectPrivate()
QObjectPrivate::QObjectPrivate (int version = QObjectPrivateVersion)
Definition at line 133 of file qobject.cpp.
     : threadData(0), connectionLists(0), senders(0), currentSender(0), currentChildBeingDeleted(0)
 {
     if (version != QObjectPrivateVersion)
         qFatal("Cannot mix incompatible Qt library (version 0x%x) with this library (version 0x%x)",
                 version, QObjectPrivateVersion);
     // QObjectData initialization
     q_ptr = 0;
     parent = 0;                                 // no parent yet. It is set by setParent()
     isWidget = false;                           // assume not a widget object
     pendTimer = false;                          // no timers yet
     blockSig = false;                           // not blocking signals
     wasDeleted = false;                         // double-delete catcher
     sendChildEvents = true;                     // if we should send ChildInsert and ChildRemove events to parent
     receiveChildEvents = true;
     postedEvents = 0;
     extraData = 0;
     connectedSignals[0] = connectedSignals[1] = 0;
     inThreadChangeEvent = false;
 #ifdef QT_JAMBI_BUILD
     inEventHandler = false;
     deleteWatch = 0;
 #endif
     metaObject = 0;
     hasGuards = false;
 }
~QObjectPrivate()
QObjectPrivate::~QObjectPrivate () virtual
Definition at line 161 of file qobject.cpp.
 {
     if (pendTimer) {
         // unregister pending timers
         if (threadData && threadData->eventDispatcher)
             threadData->eventDispatcher->unregisterTimers(q_ptr);
     }
     if (postedEvents)
         QCoreApplication::removePostedEvents(q_ptr, 0);
     if (threadData)
         threadData->deref();
     delete static_cast<QAbstractDynamicMetaObject*>(metaObject);
 #ifdef QT_JAMBI_BUILD
     if (deleteWatch)
         *deleteWatch = 1;
 #endif
 #ifndef QT_NO_USERDATA
     if (extraData)
         qDeleteAll(extraData->userData);
     delete extraData;
 #endif
 }
Functions
_q_reregisterTimers()
void QObjectPrivate::_q_reregisterTimers (void * pointer)
Definition at line 1571 of file qobject.cpp.
 {
     Q_Q(QObject);
     QList<QPair<int, int> > *timerList = reinterpret_cast<QList<QPair<int, int> > *>(pointer);
     QAbstractEventDispatcher *eventDispatcher = threadData->eventDispatcher;
     for (int i = 0; i < timerList->size(); ++i) {
         const QPair<int, int> &pair = timerList->at(i);
         eventDispatcher->registerTimer(pair.first, pair.second, q);
     }
     delete timerList;
 }
addConnection()
void QObjectPrivate::addConnection (int signal, Connection * c)
Definition at line 330 of file qobject.cpp.
Referenced by QMetaObjectPrivate::connect().
 {
     if (!connectionLists)
         connectionLists = new QObjectConnectionListVector();
     if (signal >= connectionLists->count())
         connectionLists->resize(signal + 1);
     ConnectionList &connectionList = (*connectionLists)[signal];
     if (connectionList.last) {
         connectionList.last->nextConnectionList = c;
     } else {
         connectionList.first = c;
     }
     connectionList.last = c;
     cleanConnectionLists();
 }
cleanConnectionLists()
void QObjectPrivate::cleanConnectionLists ()
Definition at line 348 of file qobject.cpp.
Referenced by addConnection().
 {
     if (connectionLists->dirty && !connectionLists->inUse) {
         // remove broken connections
         for (int signal = -1; signal < connectionLists->count(); ++signal) {
             QObjectPrivate::ConnectionList &connectionList =
                 (*connectionLists)[signal];
             // Set to the last entry in the connection list that was *not*
             // deleted.  This is needed to update the list's last pointer
             // at the end of the cleanup.
             QObjectPrivate::Connection *last = 0;
             QObjectPrivate::Connection **prev = &connectionList.first;
             QObjectPrivate::Connection *c = *prev;
             while (c) {
                 if (c->receiver) {
                     last = c;
                     prev = &c->nextConnectionList;
                     c = *prev;
                 } else {
                     QObjectPrivate::Connection *next = c->nextConnectionList;
                     *prev = next;
                     delete c;
                     c = next;
                 }
             }
             // Correct the connection list's last pointer.
             // As conectionList.last could equal last, this could be a noop
             connectionList.last = last;
         }
         connectionLists->dirty = false;
     }
 }
clearGuards()
void QObjectPrivate::clearGuards (QObject * object) static
Warning
This function is not part of the public interface.
Definition at line 467 of file qobject.cpp.
Referenced by QObject::~QObject(), and QWidget::~QWidget().
 {
     GuardHash *hash = 0;
     QMutex *mutex = 0;
     QT_TRY {
         hash = guardHash();
         mutex = guardHashLock();
     } QT_CATCH(const std::bad_alloc &) {
         // do nothing in case of OOM - code below is safe
     }
     /* check that the hash is empty - otherwise we might detach
        the shared_null hash, which will alloc, which is not nice */
     if (hash && !hash->isEmpty()) {
         QMutexLocker locker(mutex);
         GuardHash::iterator it = hash->find(object);
         const GuardHash::iterator end = hash->end();
         while (it.key() == object && it != end) {
             *it.value() = 0;
             it = hash->erase(it);
         }
     }
 }
connectNotify()
void QObjectPrivate::connectNotify (const char * signal) inline
Definition at line 245 of file qobject_p.h.
Referenced by QDeclarativePropertyPrivate::connect().
 {
     q_ptr->connectNotify(signal);
 }
deleteChildren()
void QObjectPrivate::deleteChildren ()
Definition at line 1957 of file qobject.cpp.
Referenced by QObject::~QObject().
 {
     const bool reallyWasDeleted = wasDeleted;
     wasDeleted = true;
     // delete children objects
     // don't use qDeleteAll as the destructor of the child might
     // delete siblings
     for (int i = 0; i < children.count(); ++i) {
         currentChildBeingDeleted = children.at(i);
         children[i] = 0;
         delete currentChildBeingDeleted;
     }
     children.clear();
     currentChildBeingDeleted = 0;
     wasDeleted = reallyWasDeleted;
 }
disconnectNotify()
void QObjectPrivate::disconnectNotify (const char * signal) inline
Definition at line 250 of file qobject_p.h.
Referenced by QDeclarativeNotifierEndpoint::disconnect().
 {
     q_ptr->disconnectNotify(signal);
 }
get()
static QObjectPrivate* QObjectPrivate::get (QObject * o) inline static
Definition at line 177 of file qobject_p.h.
Referenced by QAbstractScrollAreaPrivate::_q_showOrHideScrollBars(), QDeclarativeGuardImpl::addGuard(), QDeclarativeEnginePrivate::cache(), QInternal::callFunction(), QMetaObject::changeGuard(), QDeclarativeTransitionManager::complete(), QDeclarativePropertyPrivate::connect(), QMetaObjectPrivate::connect(), QDeclarativeEngine::contextForObject(), QDeclarativeCompiledData::TypeReference::createInstance(), QScriptDeclarativeClass::createPersistentIdentifier(), destroy_current_thread_data(), QDeclarativeNotifierEndpoint::disconnect(), QDeclarativeBoundSignal::disconnect(), QMetaObjectPrivate::disconnect(), QScriptDebuggerLocalsItemDelegate::eventFilter(), QEventLoop::exec(), fastHasBinding(), flush_vme_signal(), QDeclarativeContextPrivate::get(), QDeclarativeComponentPrivate::get(), QDeclarativeData::get(), QDeclarativeExpressionPrivate::get(), QDeclarativeVisualDataModelPrivate::get(), QDeclarativeDebugServer::instance(), QDeclarativeMouseAreaPrivate::isDoubleClickConnected(), QDeclarativeMouseAreaPrivate::isPressAndHoldConnected(), QDeclarativeContextData::isValid(), QScriptDeclarativeClass::newObject(), QScriptDeclarativeClass::newObjectValue(), QDeclarativeObjectScriptClass::newQObject(), QDeclarativeContextData::ContextGuard::objectDestroyed(), QDeclarativeValueTypeScriptClass::property(), QDeclarativePrivate::qdeclarativeelement_destructor(), QDeclarativeOpenMetaObject::QDeclarativeOpenMetaObject(), QDeclarativeProxyMetaObject::QDeclarativeProxyMetaObject(), QDeclarativeVMEMetaObject::QDeclarativeVMEMetaObject(), qDeleteInEventHandler(), qt_adopted_thread_watcher_function(), QStateMachinePrivate::registerEventTransition(), QDeclarativeVisualDataModel::release(), QDeclarativeEngineDebugPrivate::remove(), QMetaObject::removeGuard(), QDeclarativeVME::run(), QDeclarativeStateGroupPrivate::setCurrentStateInternal(), QDeclarativeConnectionsParser::setCustomData(), QDeclarativePropertyChangesParser::setCustomData(), QDeclarativeEngineDebugService::setMethodBody(), QAbstractScrollAreaPrivate::setSingleFingerPanEnabled(), QComboBox::showPopup(), QTimerInfoList::unregisterTimer(), QEventDispatcherMac::unregisterTimer(), QEventDispatcherWin32Private::unregisterTimer(), QTimerInfoList::unregisterTimers(), QEventDispatcherMac::unregisterTimers(), and QGraphicsItem::~QGraphicsItem().
{
         return o->d_func();
     }
isSender()
bool QObjectPrivate::isSender (const QObject * receiver, const char * signal) const
Definition at line 275 of file qobject.cpp.
 {
     Q_Q(const QObject);
     int signal_index = signalIndex(signal);
     if (signal_index < 0)
         return false;
     QMutexLocker locker(signalSlotLock(q));
     if (connectionLists) {
         if (signal_index < connectionLists->count()) {
             const QObjectPrivate::Connection *c =
                 connectionLists->at(signal_index).first;
             while (c) {
                 if (c->receiver == receiver)
                     return true;
                 c = c->nextConnectionList;
             }
         }
     }
     return false;
 }
isSignalConnected()
bool QObjectPrivate::isSignalConnected (uint signal_index) const inline
Returns true if the signal with index signal_index from object sender is connected.
Warning
This function is not part of the public interface.
Signals with indices above a certain range are always considered connected (see connectedSignals in QObjectPrivate). If a signal spy is installed, all signals are considered connected.
signal_index must be the index returned by QObjectPrivate::signalIndex;
Definition at line 237 of file qobject_p.h.
Referenced by QGraphicsScenePrivate::_q_emitUpdated(), QDeclarativeMouseAreaPrivate::isDoubleClickConnected(), QDeclarativeMouseAreaPrivate::isPressAndHoldConnected(), QGraphicsItem::prepareGeometryChange(), QVariantAnimationPrivate::setCurrentValueForProgress(), and QObject::~QObject().
 {
     return signal_index >= sizeof(connectedSignals) * 8
         || (connectedSignals[signal_index >> 5] & (1 << (signal_index & 0x1f))
         || qt_signal_spy_callback_set.signal_begin_callback
         || qt_signal_spy_callback_set.signal_end_callback);
 }
moveToThread_helper()
void QObjectPrivate::moveToThread_helper ()
Definition at line 1513 of file qobject.cpp.
Referenced by QObject::moveToThread().
 {
     Q_Q(QObject);
     QEvent e(QEvent::ThreadChange);
     QCoreApplication::sendEvent(q, &e);
     for (int i = 0; i < children.size(); ++i) {
         QObject *child = children.at(i);
         child->d_func()->moveToThread_helper();
     }
 }
receiverList()
QObjectList QObjectPrivate::receiverList (const char * signal) const
Definition at line 298 of file qobject.cpp.
 {
     Q_Q(const QObject);
     QObjectList returnValue;
     int signal_index = signalIndex(signal);
     if (signal_index < 0)
         return returnValue;
     QMutexLocker locker(signalSlotLock(q));
     if (connectionLists) {
         if (signal_index < connectionLists->count()) {
             const QObjectPrivate::Connection *c = connectionLists->at(signal_index).first;
             while (c) {
                 if (c->receiver)
                     returnValue << c->receiver;
                 c = c->nextConnectionList;
             }
         }
     }
     return returnValue;
 }
resetCurrentSender()
void QObjectPrivate::resetCurrentSender (QObject * receiver, Sender * currentSender, Sender * previousSender) inline static
Definition at line 277 of file qobject_p.h.
Referenced by QMetaObject::activate(), QInternal::callFunction(), and QObject::event().
 {
     // ref is set to zero when this object is deleted during the metacall
     if (currentSender->ref == 1)
         receiver->d_func()->currentSender = previousSender;
     // if we've recursed, we need to tell the caller about the objects deletion
     if (previousSender)
         previousSender->ref = currentSender->ref;
 }
senderList()
QObjectList QObjectPrivate::senderList () const
Definition at line 321 of file qobject.cpp.
 {
     QObjectList returnValue;
     QMutexLocker locker(signalSlotLock(q_func()));
     for (Connection *c = senders; c; c = c->next)
         returnValue << c->sender;
     return returnValue;
 }
setCurrentSender()
QObjectPrivate::Sender * QObjectPrivate::setCurrentSender (QObject * receiver, Sender * sender) inline static
Definition at line 269 of file qobject_p.h.
Referenced by QMetaObject::activate(), QInternal::callFunction(), and QObject::event().
 {
     Sender *previousSender = receiver->d_func()->currentSender;
     receiver->d_func()->currentSender = sender;
     return previousSender;
 }
setParent_helper()
void QObjectPrivate::setParent_helper (QObject * o)
Definition at line 1974 of file qobject.cpp.
Referenced by QWidgetPrivate::isBackgroundInherited(), isServerProcess(), q_createNativeChildrenAndSetParent(), QObject::setParent(), QWidgetPrivate::setParent_sys(), and QObject::~QObject().
 {
     Q_Q(QObject);
     if (o == parent)
         return;
     if (parent) {
         QObjectPrivate *parentD = parent->d_func();
         if (parentD->wasDeleted && wasDeleted
             && parentD->currentChildBeingDeleted == q) {
             // don't do anything since QObjectPrivate::deleteChildren() already
             // cleared our entry in parentD->children.
         } else {
             const int index = parentD->children.indexOf(q);
             if (parentD->wasDeleted) {
                 parentD->children[index] = 0;
             } else {
                 parentD->children.removeAt(index);
                 if (sendChildEvents && parentD->receiveChildEvents) {
                     QChildEvent e(QEvent::ChildRemoved, q);
                     QCoreApplication::sendEvent(parent, &e);
                 }
             }
         }
     }
     parent = o;
     if (parent) {
         // object hierarchies are constrained to a single thread
         if (threadData != parent->d_func()->threadData) {
             qWarning("QObject::setParent: Cannot set parent, new parent is in a different thread");
             parent = 0;
             return;
         }
         parent->d_func()->children.append(q);
         if(sendChildEvents && parent->d_func()->receiveChildEvents) {
             if (!isWidget) {
                 QChildEvent e(QEvent::ChildAdded, q);
                 QCoreApplication::sendEvent(parent, &e);
 #ifdef QT3_SUPPORT
                 if (QCoreApplicationPrivate::useQt3Support) {
                     if (parent->d_func()->pendingChildInsertedEvents.isEmpty()) {
                         QCoreApplication::postEvent(parent,
                                                     new QEvent(QEvent::ChildInsertedRequest),
                                                     Qt::HighEventPriority);
                     }
                     parent->d_func()->pendingChildInsertedEvents.append(q);
                 }
 #endif
             }
         }
     }
     if (!wasDeleted && declarativeData)
         QAbstractDeclarativeData::parentChanged(declarativeData, q, o);
 }
setThreadData_helper()
void QObjectPrivate::setThreadData_helper (QThreadData * currentData, QThreadData * targetData)
Definition at line 1524 of file qobject.cpp.
 {
     Q_Q(QObject);
     // move posted events
     int eventsMoved = 0;
     for (int i = 0; i < currentData->postEventList.size(); ++i) {
         const QPostEvent &pe = currentData->postEventList.at(i);
         if (!pe.event)
             continue;
         if (pe.receiver == q) {
             // move this post event to the targetList
             targetData->postEventList.addEvent(pe);
             const_cast<QPostEvent &>(pe).event = 0;
             ++eventsMoved;
         }
     }
     if (eventsMoved > 0 && targetData->eventDispatcher) {
         targetData->canWait = false;
         targetData->eventDispatcher->wakeUp();
     }
     // the current emitting thread shouldn't restore currentSender after calling moveToThread()
     if (currentSender)
         currentSender->ref = 0;
     currentSender = 0;
 #ifdef QT_JAMBI_BUILD
     // the current event thread also shouldn't restore the delete watch
     inEventHandler = false;
     if (deleteWatch)
         *deleteWatch = 1;
     deleteWatch = 0;
 #endif
     // set new thread data
     targetData->ref();
     threadData->deref();
     threadData = targetData;
     for (int i = 0; i < children.size(); ++i) {
         QObject *child = children.at(i);
         child->d_func()->setThreadData_helper(currentData, targetData);
     }
 }
signalIndex()
int QObjectPrivate::signalIndex (const char * signalName) const
Returns the signal index used in the internal connectionLists vector.
Warning
This function is not part of the public interface.
It is different from QMetaObject::indexOfSignal(): indexOfSignal is the same as indexOfMethod while QObjectPrivate::signalIndex is smaller because it doesn't give index to slots.
Definition at line 3719 of file qobject.cpp.
Referenced by QGraphicsScenePrivate::init(), QDeclarativeMouseAreaPrivate::isDoubleClickConnected(), QDeclarativeMouseAreaPrivate::isPressAndHoldConnected(), isSender(), receiverList(), QObject::receivers(), QStateMachinePrivate::registerSignalTransition(), QVariantAnimationPrivate::setCurrentValueForProgress(), and QStateMachinePrivate::unregisterSignalTransition().
 {
     Q_Q(const QObject);
     const QMetaObject *base = q->metaObject();
     int relative_index = QMetaObjectPrivate::indexOfSignalRelative(&base, signalName, false);
     if (relative_index < 0)
         relative_index = QMetaObjectPrivate::indexOfSignalRelative(&base, signalName, true);
     if (relative_index < 0)
         return relative_index;
     relative_index = QMetaObjectPrivate::originalClone(base, relative_index);
     int signalOffset, methodOffset;
     computeOffsets(base, &signalOffset, &methodOffset);
     return relative_index + signalOffset;
 }
signalSignature()
void QObjectPrivate::signalSignature (const QMetaMethod & signal, QVarLengthArray< char > * result) inline static
Definition at line 255 of file qobject_p.h.
Referenced by QDeclarativePropertyPrivate::connect(), QObject::connect(), QDeclarativeNotifierEndpoint::disconnect(), QDeclarativeBoundSignal::disconnect(), and QObject::disconnect().
 {
     Q_ASSERT(result);
     const int signatureLength = qstrlen(signal.signature());
     if (signatureLength == 0) {
         result->append((char)0);
         return;
     }
     result->reserve(signatureLength + 2);
     result->append((char)(QSIGNAL_CODE + '0'));
     result->append(signal.signature(), signatureLength + 1);
 }
Properties
@37
union { ... }
connectedSignals
quint32 QObjectPrivate::connectedSignals[2] mutable
Definition at line 201 of file qobject_p.h.
Referenced by QMetaObjectPrivate::connect(), and QObjectPrivate().
connectionLists
QObjectConnectionListVector* QObjectPrivate::connectionLists
Definition at line 197 of file qobject_p.h.
Referenced by addConnection(), cleanConnectionLists(), QMetaObjectPrivate::connect(), QMetaObjectPrivate::disconnect(), QObject::dumpObjectInfo(), isSender(), receiverList(), QObject::receivers(), and QObject::~QObject().
currentChildBeingDeleted
QObject* QObjectPrivate::currentChildBeingDeleted
Definition at line 213 of file qobject_p.h.
Referenced by setParent_helper().
currentSender
Sender* QObjectPrivate::currentSender
Definition at line 200 of file qobject_p.h.
Referenced by QInternal::callFunction(), QSignalEventGenerator::qt_metacall(), QDBusAdaptorConnector::relaySlot(), QObject::sender(), QObject::senderSignalIndex(), and QObject::~QObject().
declarativeData
QAbstractDeclarativeData* QObjectPrivate::declarativeData
Definition at line 214 of file qobject_p.h.
Referenced by QDeclarativeEngine::contextForObject(), QDeclarativeCompiledData::TypeReference::createInstance(), fastHasBinding(), flush_vme_signal(), QDeclarativeData::get(), QDeclarativePrivate::qdeclarativeelement_destructor(), QDeclarativeVisualDataModel::release(), QDeclarativeVME::run(), QObject::setObjectName(), QGraphicsItem::~QGraphicsItem(), and QObject::~QObject().
eventFilters
QList<QPointer<QObject> > QObjectPrivate::eventFilters
Definition at line 211 of file qobject_p.h.
Referenced by QObject::installEventFilter(), QStateMachinePrivate::registerEventTransition(), and QObject::removeEventFilter().
extraData
ExtraData* QObjectPrivate::extraData
Definition at line 194 of file qobject_p.h.
Referenced by QObject::dynamicPropertyNames(), QObject::property(), QObjectPrivate(), QObject::setProperty(), QObject::setUserData(), QObject::userData(), and ~QObjectPrivate().
objectName
QString QObjectPrivate::objectName
Definition at line 193 of file qobject_p.h.
Referenced by QObject::setObjectName(), and QObjectPrivate::Connection::~Connection().
senders
Connection* QObjectPrivate::senders
Definition at line 199 of file qobject_p.h.
Referenced by QMetaObjectPrivate::connect(), QObject::dumpObjectInfo(), QObject::sender(), senderList(), QObject::senderSignalIndex(), and QObject::~QObject().
sharedRefcount
QAtomicPointer<QtSharedPointer::ExternalRefCountData> QObjectPrivate::sharedRefcount
Definition at line 219 of file qobject_p.h.
Referenced by QObject::~QObject().
threadData
QThreadData* QObjectPrivate::threadData
Definition at line 195 of file qobject_p.h.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QAbstractSocketPrivate::_q_testConnection(), QObject::event(), QAbstractSocketPrivate::initSocketLayer(), QObject::installEventFilter(), QObject::killTimer(), make_widget_eventUPP(), QObject::moveToThread(), QCoreApplication::notifyInternal(), processPostedEvents(), QObject::QObject(), qt_create_commandline(), qt_internal_proc(), QSettings::registerFormat(), QObject::startTimer(), and ~QObjectPrivate().
unused
void* QObjectPrivate::unused
Definition at line 208 of file qobject_p.h.
Referenced by QDesktopWidgetPrivate::init(), QPrintDialogPrivate::openCarbonPrintPanel(), QTimerInfoList::QTimerInfoList(), QApplication::qwsProcessEvent(), and QDateTimeEditPrivate::updateCache().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qobject_p.h
/src/corelib/kernel/qobject.cpp