Qt 4.8: QTestBasicStreamer Class Reference
QTestBasicStreamer Class Reference
#include <qtestbasicstreamer.h>
Public Functions
bool isTtyOutput ()
const QTestLogger * logger () const
virtual void output (QTestElement *element) const
void outputString (const char *msg) const
QTestBasicStreamer ()
void setLogger (const QTestLogger *tstLogger)
void startStreaming ()
void stopStreaming ()
virtual ~QTestBasicStreamer ()
Protected Functions
virtual void formatAfterAttributes (const QTestElement *element, QTestCharBuffer *formatted) const
virtual void formatAttributes (const QTestElement *element, const QTestElementAttribute *attribute, QTestCharBuffer *formatted) const
virtual void formatBeforeAttributes (const QTestElement *element, QTestCharBuffer *formatted) const
virtual void formatEnd (const QTestElement *element, QTestCharBuffer *formatted) const
virtual void formatStart (const QTestElement *element, QTestCharBuffer *formatted) const
virtual void outputElementAttributes (const QTestElement *element, QTestElementAttribute *attribute) const
virtual void outputElements (QTestElement *element, bool isChildElement=false) const
Properties
const QTestLogger * testLogger
Detailed Description
Definition at line 58 of file qtestbasicstreamer.h.
Constructors and Destructors
QTestBasicStreamer()
QTestBasicStreamer::QTestBasicStreamer ()
Definition at line 63 of file qtestbasicstreamer.cpp.
     :testLogger(0)
 {
 }
~QTestBasicStreamer()
QTestBasicStreamer::~QTestBasicStreamer () virtual
Definition at line 68 of file qtestbasicstreamer.cpp.
 {}
Functions
formatAfterAttributes()
void QTestBasicStreamer::formatAfterAttributes (const QTestElement * element, QTestCharBuffer * formatted) const protected virtual
Reimplemented in QTestXunitStreamer.
Definition at line 92 of file qtestbasicstreamer.cpp.
Referenced by outputElements().
 {
     if(!element || !formatted )
         return;
     formatted->data()[0] = '\0';
 }
formatAttributes()
void QTestBasicStreamer::formatAttributes (const QTestElement * element, const QTestElementAttribute * attribute, QTestCharBuffer * formatted) const protected virtual
Reimplemented in QTestXunitStreamer.
Definition at line 99 of file qtestbasicstreamer.cpp.
Referenced by outputElementAttributes().
 {
     if(!attribute || !formatted )
         return;
     formatted->data()[0] = '\0';
 }
formatBeforeAttributes()
void QTestBasicStreamer::formatBeforeAttributes (const QTestElement * element, QTestCharBuffer * formatted) const protected virtual
Reimplemented in QTestLightXmlStreamer, and QTestXmlStreamer.
Definition at line 85 of file qtestbasicstreamer.cpp.
Referenced by QTestXunitStreamer::outputElements(), and outputElements().
 {
     if(!element || !formatted )
         return;
     formatted->data()[0] = '\0';
 }
formatEnd()
void QTestBasicStreamer::formatEnd (const QTestElement * element, QTestCharBuffer * formatted) const protected virtual
Reimplemented in QTestLightXmlStreamer, QTestXmlStreamer, and QTestXunitStreamer.
Definition at line 78 of file qtestbasicstreamer.cpp.
Referenced by outputElements().
 {
     if(!element || !formatted )
         return;
     formatted->data()[0] = '\0';
 }
formatStart()
void QTestBasicStreamer::formatStart (const QTestElement * element, QTestCharBuffer * formatted) const protected virtual
Reimplemented in QTestLightXmlStreamer, QTestXmlStreamer, and QTestXunitStreamer.
Definition at line 71 of file qtestbasicstreamer.cpp.
Referenced by outputElements().
 {
     if(!element || !formatted )
         return;
     formatted->data()[0] = '\0';
 }
isTtyOutput()
bool QTestBasicStreamer::isTtyOutput ()
Definition at line 187 of file qtestbasicstreamer.cpp.
 {
     QTEST_ASSERT(QTest::stream);
 #if defined(Q_OS_WIN) || defined(Q_OS_INTEGRITY)
     return true;
 #else
     static bool ttyoutput = isatty(fileno(QTest::stream));
     return ttyoutput;
 #endif
 }
logger()
const QTestLogger * QTestBasicStreamer::logger () const
Definition at line 213 of file qtestbasicstreamer.cpp.
Referenced by QTestLightXmlStreamer::output(), and QTestXmlStreamer::output().
 {
     return testLogger;
 }
output()
void QTestBasicStreamer::output (QTestElement * element) const virtual
Reimplemented in QTestLightXmlStreamer, QTestXmlStreamer, and QTestXunitStreamer.
Definition at line 106 of file qtestbasicstreamer.cpp.
Referenced by QTestLightXmlStreamer::output(), QTestXunitStreamer::output(), QTestXmlStreamer::output(), and QTestLogger::stopLogging().
 {
     if(!element)
         return;
     outputElements(element);
 }
outputElementAttributes()
void QTestBasicStreamer::outputElementAttributes (const QTestElement * element, QTestElementAttribute * attribute) const protected virtual
Definition at line 149 of file qtestbasicstreamer.cpp.
Referenced by QTestXunitStreamer::outputElements(), and outputElements().
 {
     QTestCharBuffer buf;
     while(attribute){
         formatAttributes(element, attribute, &buf);
         outputString(buf.data());
         attribute = attribute->nextElement();
     }
 }
outputElements()
void QTestBasicStreamer::outputElements (QTestElement * element, bool isChildElement = false) const protected virtual
Reimplemented in QTestXunitStreamer.
Definition at line 114 of file qtestbasicstreamer.cpp.
Referenced by output().
 {
     QTestCharBuffer buf;
     bool hasChildren;
     /*
         Elements are in reverse order of occurrence, so start from the end and work
         our way backwards.
     */
     while (element && element->nextElement()) {
         element = element->nextElement();
     }
     while (element) {
         hasChildren = element->childElements();
         formatStart(element, &buf);
         outputString(buf.data());
         formatBeforeAttributes(element, &buf);
         outputString(buf.data());
         outputElementAttributes(element, element->attributes());
         formatAfterAttributes(element, &buf);
         outputString(buf.data());
         if(hasChildren)
             outputElements(element->childElements(), true);
         formatEnd(element, &buf);
         outputString(buf.data());
         element = element->previousElement();
     }
 }
outputString()
void QTestBasicStreamer::outputString (const char * msg) const
Definition at line 159 of file qtestbasicstreamer.cpp.
Referenced by QTestLightXmlStreamer::output(), QTestXmlStreamer::output(), QTestXunitStreamer::output(), outputElementAttributes(), QTestXunitStreamer::outputElements(), and outputElements().
 {
     QTEST_ASSERT(QTest::stream);
     ::fputs(msg, QTest::stream);
     ::fflush(QTest::stream);
 }
setLogger()
void QTestBasicStreamer::setLogger (const QTestLogger * tstLogger)
Definition at line 208 of file qtestbasicstreamer.cpp.
Referenced by QTestLogger::startLogging().
 {
     testLogger = tstLogger;
 }
startStreaming()
void QTestBasicStreamer::startStreaming ()
Definition at line 167 of file qtestbasicstreamer.cpp.
Referenced by QTestLogger::startLogging().
 {
     QTEST_ASSERT(!QTest::stream);
     const char *out = QTestLog::outputFileName();
     if (!out) {
         QTest::stream = stdout;
         return;
     }
     #if defined(_MSC_VER) && _MSC_VER >= 1400 && !defined(Q_OS_WINCE)
     if (::fopen_s(&QTest::stream, out, "wt")) {
         #else
         QTest::stream = ::fopen(out, "wt");
         if (!QTest::stream) {
             #endif
             printf("Unable to open file for logging: %s", out);
             ::exit(1);
         }
 }
stopStreaming()
void QTestBasicStreamer::stopStreaming ()
Definition at line 199 of file qtestbasicstreamer.cpp.
Referenced by QTestLogger::stopLogging().
 {
     QTEST_ASSERT(QTest::stream);
     if (QTest::stream != stdout)
         fclose(QTest::stream);
     QTest::stream = 0;
 }
Properties
testLogger
const QTestLogger* QTestBasicStreamer::testLogger private
Definition at line 84 of file qtestbasicstreamer.h.
Referenced by logger(), and setLogger().
The documentation for this class was generated from the following files:
/src/testlib/qtestbasicstreamer.h
/src/testlib/qtestbasicstreamer.cpp