Qt 4.8: QRasterBuffer Class Reference
QRasterBuffer Class Reference
#include <qpaintengine_raster_p.h>
Public Functions
uchar * buffer () const
QImage bufferImage () const
int bytesPerLine () const
int bytesPerPixel () const
QImage colorizeBitmap (const QImage &image, const QColor &color)
void flushToARGBImage (QImage *image) const
int height () const
void init ()
QImage::Format prepare (QImage *image)
QImage::Format prepare (QPixmap *pix)
void prepare (QCustomRasterPaintDevice *device)
void prepare (int w, int h)
void prepareBuffer (int w, int h)
QRasterBuffer ()
void resetBuffer (int val=0)
uchar * scanLine (int y)
int width () const
~QRasterBuffer ()
Public Variables
QPainter::CompositionMode compositionMode
QRgb destColor0
QRgb destColor1
DrawHelper * drawHelper
QImage::Format format
bool monoDestinationWithClut
Properties
int bytes_per_line
int bytes_per_pixel
uchar * m_buffer
int m_height
int m_width
Detailed Description
Definition at line 497 of file qpaintengine_raster_p.h.
Constructors and Destructors
QRasterBuffer()
QRasterBuffer::QRasterBuffer () inline
Definition at line 504 of file qpaintengine_raster_p.h.
 : m_width(0), m_height(0), m_buffer(0) { init(); }
~QRasterBuffer()
QRasterBuffer::~QRasterBuffer ()
Definition at line 3915 of file qpaintengine_raster.cpp.
 {
 }
Functions
buffer()
uchar* QRasterBuffer::buffer () const inline
Definition at line 533 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawImage(), qt_rectfill_nonpremul_quint32(), qt_rectfill_template(), and QCosmeticStroker::setup().
 { return m_buffer; }
bufferImage()
QImage QRasterBuffer::bufferImage () const
Definition at line 4506 of file qpaintengine_raster.cpp.
 {
     QImage image(m_width, m_height, QImage::Format_ARGB32_Premultiplied);
     for (int y = 0; y < m_height; ++y) {
         uint *span = (uint *)const_cast<QRasterBuffer *>(this)->scanLine(y);
         for (int x=0; x<m_width; ++x) {
             uint argb = span[x];
             image.setPixel(x, y, argb);
         }
     }
     return image;
 }
bytesPerLine()
int QRasterBuffer::bytesPerLine () const inline
Definition at line 530 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawImage(), qt_alphamapblit_quint16(), qt_alphamapblit_quint32(), qt_alphargbblit_quint32(), qt_bitmapblit_template(), qt_rectfill_nonpremul_quint32(), qt_rectfill_template(), and QCosmeticStroker::setup().
 { return bytes_per_line; }
bytesPerPixel()
int QRasterBuffer::bytesPerPixel () const inline
Definition at line 531 of file qpaintengine_raster_p.h.
 { return bytes_per_pixel; }
colorizeBitmap()
QImage QRasterBuffer::colorizeBitmap (const QImage & image, const QColor & color)
Definition at line 3892 of file qpaintengine_raster.cpp.
Referenced by QRasterPaintEngine::drawPixmap(), and QRasterPaintEngine::drawTiledPixmap().
 {
     Q_ASSERT(image.depth() == 1);
     QImage sourceImage = image.convertToFormat(QImage::Format_MonoLSB);
     QImage dest = QImage(sourceImage.size(), QImage::Format_ARGB32_Premultiplied);
     QRgb fg = PREMUL(color.rgba());
     QRgb bg = 0;
     int height = sourceImage.height();
     int width = sourceImage.width();
     for (int y=0; y<height; ++y) {
         uchar *source = sourceImage.scanLine(y);
         QRgb *target = reinterpret_cast<QRgb *>(dest.scanLine(y));
         if (!source || !target)
             QT_THROW(std::bad_alloc()); // we must have run out of memory
         for (int x=0; x < width; ++x)
             target[x] = (source[x>>3] >> (x&7)) & 1 ? fg : bg;
     }
     return dest;
 }
flushToARGBImage()
void QRasterBuffer::flushToARGBImage (QImage * image) const
Definition at line 4523 of file qpaintengine_raster.cpp.
 {
     int w = qMin(m_width, target->width());
     int h = qMin(m_height, target->height());
     for (int y=0; y<h; ++y) {
         uint *sourceLine = (uint *)const_cast<QRasterBuffer *>(this)->scanLine(y);
         QRgb *dest = (QRgb *) target->scanLine(y);
         for (int x=0; x<w; ++x) {
             QRgb pixel = sourceLine[x];
             int alpha = qAlpha(pixel);
             if (!alpha) {
                 dest[x] = 0;
             } else {
                 dest[x] = (alpha << 24)
                         | ((255*qRed(pixel)/alpha) << 16)
                         | ((255*qGreen(pixel)/alpha) << 8)
                         | ((255*qBlue(pixel)/alpha) << 0);
             }
         }
     }
 }
height()
int QRasterBuffer::height () const inline
Definition at line 529 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::alphaPenBlt(), QRasterPaintEngine::clip(), QRasterPaintEngine::drawBitmap(), fillRect_normalized(), qrasterpaintengine_dirty_clip(), qt_alphamapblit_quint32(), qt_alphargbblit_quint32(), and QRasterPaintEngine::setClipRectInDeviceCoords().
 { return m_height; }
init()
void QRasterBuffer::init ()
Definition at line 3919 of file qpaintengine_raster.cpp.
 {
     compositionMode = QPainter::CompositionMode_SourceOver;
     monoDestinationWithClut = false;
     destColor0 = 0;
     destColor1 = 0;
 }
prepare() [1/4]
QImage::Format QRasterBuffer::prepare (QImage * image)
Definition at line 3927 of file qpaintengine_raster.cpp.
Referenced by blendCursor(), QScreen::compose(), and QScreen::paintBackground().
 {
     m_buffer = (uchar *)image->bits();
     m_width = qMin(QT_RASTER_COORD_LIMIT, image->width());
     m_height = qMin(QT_RASTER_COORD_LIMIT, image->height());
     bytes_per_pixel = image->depth()/8;
     bytes_per_line = image->bytesPerLine();
     format = image->format();
     drawHelper = qDrawHelper + format;
     if (image->depth() == 1 && image->colorTable().size() == 2) {
         monoDestinationWithClut = true;
         destColor0 = PREMUL(image->colorTable()[0]);
         destColor1 = PREMUL(image->colorTable()[1]);
     }
     return format;
 }
prepare() [2/4]
QImage::Format QRasterBuffer::prepare (QPixmap * pix)
prepare() [3/4]
void QRasterBuffer::prepare (QCustomRasterPaintDevice * device)
Definition at line 3953 of file qpaintengine_raster.cpp.
 {
     m_buffer = reinterpret_cast<uchar*>(device->memory());
     m_width = qMin(QT_RASTER_COORD_LIMIT, device->width());
     m_height = qMin(QT_RASTER_COORD_LIMIT, device->height());
     bytes_per_pixel = device->depth() / 8;
     bytes_per_line = device->bytesPerLine();
     format = device->format();
 #ifndef QT_NO_RASTERCALLBACKS
     if (!m_buffer)
         drawHelper = qDrawHelperCallback + format;
     else
 #endif
         drawHelper = qDrawHelper + format;
 }
prepare() [4/4]
void QRasterBuffer::prepare (int w, int h)
prepareBuffer()
void QRasterBuffer::prepareBuffer (int w, int h)
Referenced by QCustomRasterPaintDevice::bytesPerLine().
resetBuffer()
void QRasterBuffer::resetBuffer (int val = 0)
Definition at line 3946 of file qpaintengine_raster.cpp.
 {
     memset(m_buffer, val, m_height*bytes_per_line);
 }
scanLine()
uchar* QRasterBuffer::scanLine (int y) inline
Definition at line 520 of file qpaintengine_raster_p.h.
Referenced by blend_color_argb(), blend_color_rgb16(), blend_tiled_argb(), blend_transformed_argb(), blend_transformed_tiled_argb(), blend_untransformed_argb(), blendColor(), blendTiled(), blendTransformed(), blendTransformedBilinear(), blendTransformedTiled(), blendUntransformed(), destFetch(), destFetchARGB32(), destFetchARGB32P(), destFetchMono(), destFetchMonoLsb(), destFetchRGB16(), destStore(), destStoreARGB32(), destStoreMono(), destStoreMonoLsb(), destStoreRGB16(), qt_alphamapblit_quint16(), qt_alphamapblit_quint32(), qt_alphargbblit_quint32(), qt_bitmapblit_template(), qt_blend_color_argb_x86(), and qt_gradient_quint32().
 { Q_ASSERT(y>=0); Q_ASSERT(y<m_height); return m_buffer + y * bytes_per_line; }
width()
int QRasterBuffer::width () const inline
Definition at line 528 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::alphaPenBlt(), QRasterPaintEngine::drawBitmap(), fillRect_normalized(), and qrasterpaintengine_dirty_clip().
 { return m_width; }
Properties
bytes_per_line
int QRasterBuffer::bytes_per_line private
Definition at line 547 of file qpaintengine_raster_p.h.
bytes_per_pixel
int QRasterBuffer::bytes_per_pixel private
Definition at line 548 of file qpaintengine_raster_p.h.
compositionMode
QPainter::CompositionMode QRasterBuffer::compositionMode
Definition at line 539 of file qpaintengine_raster_p.h.
Referenced by blend_color_rgb16(), blend_transformed_argb(), blend_transformed_tiled_argb(), blendTiled(), blendTransformed(), blendTransformedBilinear(), blendTransformedTiled(), blendUntransformed(), QScreen::compose(), QRasterPaintEngine::drawImage(), fillRect_normalized(), getOperator(), qt_blend_color_argb_x86(), and qt_gradient_quint32().
destColor0
QRgb QRasterBuffer::destColor0
Definition at line 536 of file qpaintengine_raster_p.h.
Referenced by destFetchMono(), destFetchMonoLsb(), destStoreMono(), destStoreMonoLsb(), and findNearestColor().
destColor1
QRgb QRasterBuffer::destColor1
Definition at line 537 of file qpaintengine_raster_p.h.
Referenced by destFetchMono(), destFetchMonoLsb(), destStoreMono(), destStoreMonoLsb(), and findNearestColor().
drawHelper
DrawHelper* QRasterBuffer::drawHelper
Definition at line 541 of file qpaintengine_raster_p.h.
format
QImage::Format QRasterBuffer::format
Definition at line 540 of file qpaintengine_raster_p.h.
Referenced by QRasterPaintEngine::drawImage(), getOperator(), qBlendTexture(), and qBlendTextureCallback().
m_buffer
uchar* QRasterBuffer::m_buffer private
Definition at line 549 of file qpaintengine_raster_p.h.
m_height
int QRasterBuffer::m_height private
Definition at line 546 of file qpaintengine_raster_p.h.
m_width
int QRasterBuffer::m_width private
Definition at line 545 of file qpaintengine_raster_p.h.
monoDestinationWithClut
bool QRasterBuffer::monoDestinationWithClut
Definition at line 535 of file qpaintengine_raster_p.h.
Referenced by destStoreMono(), and destStoreMonoLsb().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine_raster_p.h
/src/gui/painting/qpaintengine_raster.cpp