Qt 4.8: QImagePixmapCleanupHooks Class Reference
QImagePixmapCleanupHooks Class Reference
#include <qimagepixmapcleanuphooks_p.h>
Public Functions
void addImageHook (_qt_image_cleanup_hook_64)
void addPixmapDataDestructionHook (_qt_pixmap_cleanup_hook_pmd)
void addPixmapDataModificationHook (_qt_pixmap_cleanup_hook_pmd)
void removeImageHook (_qt_image_cleanup_hook_64)
void removePixmapDataDestructionHook (_qt_pixmap_cleanup_hook_pmd)
void removePixmapDataModificationHook (_qt_pixmap_cleanup_hook_pmd)
Static Public Functions
static void enableCleanupHooks (const QImage &image)
static void enableCleanupHooks (const QPixmap &pixmap)
static void enableCleanupHooks (QPixmapData *pixmapData)
static void executeImageHooks (qint64 key)
static void executePixmapDataDestructionHooks (QPixmapData *)
static void executePixmapDataModificationHooks (QPixmapData *)
static QImagePixmapCleanupHooks * instance ()
static bool isImageCached (const QImage &image)
static bool isPixmapCached (const QPixmap &pixmap)
Properties
QList< _qt_image_cleanup_hook_64 > imageHooks
QList< _qt_pixmap_cleanup_hook_pmd > pixmapDestructionHooks
QList< _qt_pixmap_cleanup_hook_pmd > pixmapModificationHooks
Detailed Description
Definition at line 66 of file qimagepixmapcleanuphooks_p.h.
Functions
addImageHook()
void QImagePixmapCleanupHooks::addImageHook (_qt_image_cleanup_hook_64 hook)
Definition at line 76 of file qimagepixmapcleanuphooks.cpp.
Referenced by QDirectFBPaintEngine::drawBufferSpan().
 {
     imageHooks.append(hook);
 }
addPixmapDataDestructionHook()
void QImagePixmapCleanupHooks::addPixmapDataDestructionHook (_qt_pixmap_cleanup_hook_pmd hook)
Definition at line 70 of file qimagepixmapcleanuphooks.cpp.
Referenced by QGLBlurTextureCache::insertBlurTextureInfo().
 {
     pixmapDestructionHooks.append(hook);
 }
addPixmapDataModificationHook()
void QImagePixmapCleanupHooks::addPixmapDataModificationHook (_qt_pixmap_cleanup_hook_pmd hook)
Definition at line 65 of file qimagepixmapcleanuphooks.cpp.
Referenced by QGLBlurTextureCache::insertBlurTextureInfo().
 {
     pixmapModificationHooks.append(hook);
 }
enableCleanupHooks() [1/3]
void QImagePixmapCleanupHooks::enableCleanupHooks (const QImage & image) static
Definition at line 146 of file qimagepixmapcleanuphooks.cpp.
Referenced by QGLContextPrivate::bindTextureFromNativePixmap(), QEgl::createSurface(), enableCleanupHooks(), and QGLBlurTextureCache::insertBlurTextureInfo().
 {
     const_cast<QImage &>(image).data_ptr()->is_cached = true;
 }
enableCleanupHooks() [2/3]
void QImagePixmapCleanupHooks::enableCleanupHooks (const QPixmap & pixmap) static
Definition at line 141 of file qimagepixmapcleanuphooks.cpp.
 {
     enableCleanupHooks(const_cast<QPixmap &>(pixmap).data_ptr().data());
 }
enableCleanupHooks() [3/3]
void QImagePixmapCleanupHooks::enableCleanupHooks (QPixmapData * pixmapData) static
Definition at line 136 of file qimagepixmapcleanuphooks.cpp.
 {
     pixmapData->is_cached = true;
 }
executeImageHooks()
void QImagePixmapCleanupHooks::executeImageHooks (qint64 key) static
Definition at line 126 of file qimagepixmapcleanuphooks.cpp.
Referenced by QImage::detach(), and QImageData::~QImageData().
 {
     for (int i = 0; i < qt_image_and_pixmap_cleanup_hooks()->imageHooks.count(); ++i)
         qt_image_and_pixmap_cleanup_hooks()->imageHooks[i](key);
     if (qt_image_cleanup_hook_64)
         qt_image_cleanup_hook_64(key);
 }
executePixmapDataDestructionHooks()
void QImagePixmapCleanupHooks::executePixmapDataDestructionHooks (QPixmapData * pmd) static
Definition at line 111 of file qimagepixmapcleanuphooks.cpp.
Referenced by QPixmapData::~QPixmapData(), and QX11PixmapData::~QX11PixmapData().
 {
     QImagePixmapCleanupHooks *h = qt_image_and_pixmap_cleanup_hooks();
     // the global destructor for the pixmap and image hooks might have
     // been called already if the app is "leaking" global
     // pixmaps/images
     if (!h)
         return;
     for (int i = 0; i < h->pixmapDestructionHooks.count(); ++i)
         h->pixmapDestructionHooks[i](pmd);
     if (qt_pixmap_cleanup_hook_64)
         qt_pixmap_cleanup_hook_64(pmd->cacheKey());
 }
executePixmapDataModificationHooks()
void QImagePixmapCleanupHooks::executePixmapDataModificationHooks (QPixmapData * pmd) static
Definition at line 96 of file qimagepixmapcleanuphooks.cpp.
Referenced by QPixmap::detach().
 {
     QImagePixmapCleanupHooks *h = qt_image_and_pixmap_cleanup_hooks();
     // the global destructor for the pixmap and image hooks might have
     // been called already if the app is "leaking" global
     // pixmaps/images
     if (!h)
         return;
     for (int i = 0; i < h->pixmapModificationHooks.count(); ++i)
         h->pixmapModificationHooks[i](pmd);
     if (qt_pixmap_cleanup_hook_64)
         qt_pixmap_cleanup_hook_64(pmd->cacheKey());
 }
instance()
QImagePixmapCleanupHooks * QImagePixmapCleanupHooks::instance () static
Definition at line 60 of file qimagepixmapcleanuphooks.cpp.
Referenced by QDirectFBPaintEngine::drawBufferSpan(), and QGLBlurTextureCache::insertBlurTextureInfo().
 {
     return qt_image_and_pixmap_cleanup_hooks();
 }
isImageCached()
bool QImagePixmapCleanupHooks::isImageCached (const QImage & image) static
Definition at line 151 of file qimagepixmapcleanuphooks.cpp.
 {
     return const_cast<QImage &>(image).data_ptr()->is_cached;
 }
isPixmapCached()
bool QImagePixmapCleanupHooks::isPixmapCached (const QPixmap & pixmap) static
Definition at line 156 of file qimagepixmapcleanuphooks.cpp.
 {
     return const_cast<QPixmap&>(pixmap).data_ptr().data()->is_cached;
 }
removeImageHook()
void QImagePixmapCleanupHooks::removeImageHook (_qt_image_cleanup_hook_64 hook)
Definition at line 91 of file qimagepixmapcleanuphooks.cpp.
 {
     imageHooks.removeAll(hook);
 }
removePixmapDataDestructionHook()
void QImagePixmapCleanupHooks::removePixmapDataDestructionHook (_qt_pixmap_cleanup_hook_pmd hook)
Definition at line 86 of file qimagepixmapcleanuphooks.cpp.
 {
     pixmapDestructionHooks.removeAll(hook);
 }
removePixmapDataModificationHook()
void QImagePixmapCleanupHooks::removePixmapDataModificationHook (_qt_pixmap_cleanup_hook_pmd hook)
Definition at line 81 of file qimagepixmapcleanuphooks.cpp.
 {
     pixmapModificationHooks.removeAll(hook);
 }
Properties
imageHooks
QList<_qt_image_cleanup_hook_64> QImagePixmapCleanupHooks::imageHooks private
Definition at line 96 of file qimagepixmapcleanuphooks_p.h.
Referenced by addImageHook(), and removeImageHook().
pixmapDestructionHooks
QList<_qt_pixmap_cleanup_hook_pmd> QImagePixmapCleanupHooks::pixmapDestructionHooks private
Definition at line 98 of file qimagepixmapcleanuphooks_p.h.
Referenced by addPixmapDataDestructionHook(), executePixmapDataDestructionHooks(), and removePixmapDataDestructionHook().
pixmapModificationHooks
QList<_qt_pixmap_cleanup_hook_pmd> QImagePixmapCleanupHooks::pixmapModificationHooks private
Definition at line 97 of file qimagepixmapcleanuphooks_p.h.
Referenced by addPixmapDataModificationHook(), executePixmapDataModificationHooks(), and removePixmapDataModificationHook().
The documentation for this class was generated from the following files:
/src/gui/image/qimagepixmapcleanuphooks_p.h
/src/gui/image/qimagepixmapcleanuphooks.cpp