Qt 4.8: QGraphicsAnchorLayout Class Reference
QGraphicsAnchorLayout Class Reference
The QGraphicsAnchorLayout class provides a layout where one can anchor widgets together in Graphics View.
#include <qgraphicsanchorlayout.h>
Public Functions
QGraphicsAnchor * addAnchor (QGraphicsLayoutItem *firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem *secondItem, Qt::AnchorPoint secondEdge)
Creates an anchor between the edge firstEdge of item firstItem and the edge secondEdge of item secondItem.
void addAnchors (QGraphicsLayoutItem *firstItem, QGraphicsLayoutItem *secondItem, Qt::Orientations orientations=Qt::Horizontal|Qt::Vertical)
Anchors two or four edges of firstItem with the corresponding edges of secondItem, so that firstItem has the same size as secondItem in the dimensions specified by orientations.
void addCornerAnchors (QGraphicsLayoutItem *firstItem, Qt::Corner firstCorner, QGraphicsLayoutItem *secondItem, Qt::Corner secondCorner)
Creates two anchors between firstItem and secondItem specified by the corners, firstCorner and secondCorner, where one is for the horizontal edge and another one for the vertical edge.
QGraphicsAnchor * anchor (QGraphicsLayoutItem *firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem *secondItem, Qt::AnchorPoint secondEdge)
Returns the anchor between the anchor points defined by firstItem and firstEdge and secondItem and secondEdge.
int count () const
Reimplemented Function
qreal horizontalSpacing () const
Returns the default horizontal spacing for the anchor layout.
void invalidate ()
Reimplemented Function
QGraphicsLayoutItem * itemAt (int index) const
Reimplemented Function
QGraphicsAnchorLayout (QGraphicsLayoutItem *parent=0)
Constructs a QGraphicsAnchorLayout instance.
void removeAt (int index)
Removes the layout item at index without destroying it.
void setGeometry (const QRectF &rect)
Reimplemented Function
void setHorizontalSpacing (qreal spacing)
Sets the default horizontal spacing for the anchor layout to spacing.
void setSpacing (qreal spacing)
Sets the default horizontal and the default vertical spacing for the anchor layout to spacing.
void setVerticalSpacing (qreal spacing)
Sets the default vertical spacing for the anchor layout to spacing.
qreal verticalSpacing () const
Returns the default vertical spacing for the anchor layout.
virtual ~QGraphicsAnchorLayout ()
Destroys the QGraphicsAnchorLayout object.
Public Functions inherited from QGraphicsLayout
void activate ()
Activates the layout, causing all items in the layout to be immediately rearranged.
void getContentsMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
Reimplemented Function
bool isActivated () const
Returns true if the layout is currently being activated; otherwise, returns false.
QGraphicsLayout (QGraphicsLayoutItem *parent=0)
Contructs a QGraphicsLayout object.
void setContentsMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the contents margins to left, top, right and bottom.
virtual void updateGeometry ()
Reimplemented Function
virtual void widgetEvent (QEvent *e)
This virtual event handler receives all events for the managed widget.
~QGraphicsLayout ()
Destroys the QGraphicsLayout object.
Public Functions inherited from QGraphicsLayoutItem
QRectF contentsRect () const
Returns the contents rect in local coordinates.
QSizeF effectiveSizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Returns the effective size hint for this QGraphicsLayoutItem.
QRectF geometry () const
Returns the item's geometry (e.
QGraphicsItem * graphicsItem () const
Returns the QGraphicsItem that this layout item represents.
bool isLayout () const
Returns true if this QGraphicsLayoutItem is a layout (e.g., is inherited by an object that arranges other QGraphicsLayoutItem objects); otherwise returns false.
qreal maximumHeight () const
Returns the maximum height.
QSizeF maximumSize () const
Returns the maximum size.
qreal maximumWidth () const
Returns the maximum width.
qreal minimumHeight () const
Returns the minimum height.
QSizeF minimumSize () const
Returns the minimum size.
qreal minimumWidth () const
Returns the minimum width.
bool ownedByLayout () const
Returns whether a layout should delete this item in its destructor.
QGraphicsLayoutItem * parentLayoutItem () const
Returns the parent of this QGraphicsLayoutItem, or 0 if there is no parent, or if the parent does not inherit from QGraphicsLayoutItem (QGraphicsLayoutItem is often used through multiple inheritance with QObject-derived classes).
qreal preferredHeight () const
Returns the preferred height.
QSizeF preferredSize () const
Returns the preferred size.
qreal preferredWidth () const
Returns the preferred width.
QGraphicsLayoutItem (QGraphicsLayoutItem *parent=0, bool isLayout=false)
Constructs the QGraphicsLayoutItem object.
void setMaximumHeight (qreal height)
Sets the maximum height to height.
void setMaximumSize (const QSizeF &size)
Sets the maximum size to size.
void setMaximumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMaximumSize(QSizeF(w, h)).
void setMaximumWidth (qreal width)
Sets the maximum width to width.
void setMinimumHeight (qreal height)
Sets the minimum height to height.
void setMinimumSize (const QSizeF &size)
Sets the minimum size to size.
void setMinimumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMinimumSize(QSizeF(w, h)).
void setMinimumWidth (qreal width)
Sets the minimum width to width.
void setParentLayoutItem (QGraphicsLayoutItem *parent)
Sets the parent of this QGraphicsLayoutItem to parent.
void setPreferredHeight (qreal height)
Sets the preferred height to height.
void setPreferredSize (const QSizeF &size)
Sets the preferred size to size.
void setPreferredSize (qreal w, qreal h)
This convenience function is equivalent to calling setPreferredSize(QSizeF(w, h)).
void setPreferredWidth (qreal width)
Sets the preferred width to width.
void setSizePolicy (const QSizePolicy &policy)
Sets the size policy to policy.
void setSizePolicy (QSizePolicy::Policy hPolicy, QSizePolicy::Policy vPolicy, QSizePolicy::ControlType controlType=QSizePolicy::DefaultType)
This function is equivalent to calling setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType)).
QSizePolicy sizePolicy () const
Returns the current size policy.
virtual ~QGraphicsLayoutItem ()
Destroys the QGraphicsLayoutItem object.
Protected Functions
QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Reimplemented Function
Protected Functions inherited from QGraphicsLayout
void addChildLayoutItem (QGraphicsLayoutItem *layoutItem)
This function is a convenience function provided for custom layouts, and will go through all items in the layout and reparent their graphics items to the closest QGraphicsWidget ancestor of the layout.
QGraphicsLayout (QGraphicsLayoutPrivate &, QGraphicsLayoutItem *)
Protected Functions inherited from QGraphicsLayoutItem
QGraphicsLayoutItem (QGraphicsLayoutItemPrivate &dd)
void setGraphicsItem (QGraphicsItem *item)
If the QGraphicsLayoutItem represents a QGraphicsItem, and it wants to take advantage of the automatic reparenting capabilities of QGraphicsLayout it should set this value.
void setOwnedByLayout (bool ownedByLayout)
Sets whether a layout should delete this item in its destructor or not.
Friends
class QGraphicsAnchor
Additional Inherited Members
Static Public Functions inherited from QGraphicsLayout
static bool instantInvalidatePropagation ()
static void setInstantInvalidatePropagation (bool enable)
Protected Variables inherited from QGraphicsLayoutItem
QScopedPointer< QGraphicsLayoutItemPrivate > d_ptr
Detailed Description
The QGraphicsAnchorLayout class provides a layout where one can anchor widgets together in Graphics View.
Since
4.6
The anchor layout allows developers to specify how widgets should be placed relative to each other, and to the layout itself. The specification is made by adding anchors to the layout by calling addAnchor(), addAnchors() or addCornerAnchors().
Existing anchors in the layout can be accessed with the anchor() function. Items that are anchored are automatically added to the layout, and if items are removed, all their anchors will be automatically removed.
{class="float-left"}
Using an anchor layout to align simple colored widgets.
Anchors are always set up between edges of an item, where the "center" is also considered to be an edge. Consider the following example:
    layout->addAnchor(b, Qt::AnchorLeft, a, Qt::AnchorRight);
    layout->addAnchor(b, Qt::AnchorTop, a, Qt::AnchorBottom);
Here, the right edge of item a is anchored to the left edge of item b and the bottom edge of item a is anchored to the top edge of item b, with the result that item b will be placed diagonally to the right and below item b.
The addCornerAnchors() function provides a simpler way of anchoring the corners of two widgets than the two individual calls to addAnchor() shown in the code above. Here, we see how a widget can be anchored to the top-left corner of the enclosing layout:
    layout->addCornerAnchors(a, Qt::TopLeftCorner, layout, Qt::TopLeftCorner);
In cases where anchors are used to match the widths or heights of widgets, it is convenient to use the addAnchors() function. As with the other functions for specifying anchors, it can also be used to anchor a widget to a layout.
Size Hints and Size Policies in an Anchor Layout
QGraphicsAnchorLayout respects each item's size hints and size policies. Note that there are some properties of QSizePolicy that are Known issues{not respected}.
Spacing within an Anchor Layout
The layout may distribute some space between the items. If the spacing has not been explicitly specified, the actual amount of space will usually be 0.
However, if the first edge is the opposite of the second edge (e.g., the right edge of the first widget is anchored to the left edge of the second widget), the size of the anchor will be queried from the style through a pixel metric: QStyle::PM_LayoutHorizontalSpacing for horizontal anchors and QStyle::PM_LayoutVerticalSpacing for vertical anchors.
If the spacing is negative, the items will overlap to some extent.
Known issues There are some features that QGraphicsAnchorLayout currently does not support.
This might change in the future, so avoid using these features if you want to avoid any future regressions in behaviour:
Stretch factors are not respected.
QSizePolicy::ExpandFlag is not respected.
Height for width is not respected.
See also
QGraphicsLinearLayout, QGraphicsGridLayout, QGraphicsLayout
Definition at line 82 of file qgraphicsanchorlayout.h.
Constructors and Destructors
QGraphicsAnchorLayout()
QGraphicsAnchorLayout::QGraphicsAnchorLayout (QGraphicsLayoutItem * parent = 0)
Constructs a QGraphicsAnchorLayout instance.
parent is passed to QGraphicsLayout's constructor.
Definition at line 227 of file qgraphicsanchorlayout.cpp.
     : QGraphicsLayout(*new QGraphicsAnchorLayoutPrivate(), parent)
 {
     Q_D(QGraphicsAnchorLayout);
     d->createLayoutEdges();
 }
~QGraphicsAnchorLayout()
QGraphicsAnchorLayout::~QGraphicsAnchorLayout () virtual
Destroys the QGraphicsAnchorLayout object.
Definition at line 237 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(QGraphicsAnchorLayout);
     for (int i = count() - 1; i >= 0; --i) {
         QGraphicsLayoutItem *item = d->items.at(i);
         removeAt(i);
         if (item) {
             if (item->ownedByLayout())
                 delete item;
         }
     }
     d->removeCenterConstraints(this, QGraphicsAnchorLayoutPrivate::Horizontal);
     d->removeCenterConstraints(this, QGraphicsAnchorLayoutPrivate::Vertical);
     d->deleteLayoutEdges();
     Q_ASSERT(d->itemCenterConstraints[0].isEmpty());
     Q_ASSERT(d->itemCenterConstraints[1].isEmpty());
     Q_ASSERT(d->items.isEmpty());
     Q_ASSERT(d->m_vertexList.isEmpty());
 }
Functions
addAnchor()
QGraphicsAnchor * QGraphicsAnchorLayout::addAnchor (QGraphicsLayoutItem * firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem * secondItem, Qt::AnchorPoint secondEdge)
Creates an anchor between the edge firstEdge of item firstItem and the edge secondEdge of item secondItem.
The spacing of the anchor is picked up from the style. Anchors between a layout edge and an item edge will have a size of 0. If there is already an anchor between the edges, the the new anchor will replace the old one.
firstItem and secondItem are automatically added to the layout if they are not part of the layout. This means that count() can increase by up to 2.
The spacing an anchor will get depends on the type of anchor. For instance, anchors from the Right edge of one item to the Left edge of another (or vice versa) will use the default horizontal spacing. The same behaviour applies to Bottom to Top anchors, (but they will use the default vertical spacing). For all other anchor combinations, the spacing will be 0. All anchoring functions will follow this rule.
The spacing can also be set manually by using QGraphicsAnchor::setSpacing() method.
Calling this function where firstItem or secondItem are ancestors of the layout have undefined behaviour.
See also
addAnchors(), addCornerAnchors()
Definition at line 283 of file qgraphicsanchorlayout.cpp.
Referenced by addAnchors().
 {
     Q_D(QGraphicsAnchorLayout);
     QGraphicsAnchor *a = d->addAnchor(firstItem, firstEdge, secondItem, secondEdge);
     invalidate();
     return a;
 }
addAnchors()
void QGraphicsAnchorLayout::addAnchors (QGraphicsLayoutItem * firstItem, QGraphicsLayoutItem * secondItem, Qt::Orientations orientations = Qt::Horizontal | Qt::Vertical)
Anchors two or four edges of firstItem with the corresponding edges of secondItem, so that firstItem has the same size as secondItem in the dimensions specified by orientations.
For example, the following example anchors the left and right edges of two items to match their widths:
    layout->addAnchor(b, Qt::AnchorLeft, c, Qt::AnchorLeft);
    layout->addAnchor(b, Qt::AnchorRight, c, Qt::AnchorRight);
This can also be achieved using the following line of code:
    layout->addAnchors(b, c, Qt::Horizontal);
See also
addAnchor(), addCornerAnchors()
Definition at line 362 of file qgraphicsanchorlayout.cpp.
 {
     bool ok = true;
     if (orientations & Qt::Horizontal) {
         // Currently, if the first is ok, then the rest of the calls should be ok
         ok = addAnchor(secondItem, Qt::AnchorLeft, firstItem, Qt::AnchorLeft) != 0;
         if (ok)
             addAnchor(firstItem, Qt::AnchorRight, secondItem, Qt::AnchorRight);
     }
     if (orientations & Qt::Vertical && ok) {
         addAnchor(secondItem, Qt::AnchorTop, firstItem, Qt::AnchorTop);
         addAnchor(firstItem, Qt::AnchorBottom, secondItem, Qt::AnchorBottom);
     }
 }
addCornerAnchors()
void QGraphicsAnchorLayout::addCornerAnchors (QGraphicsLayoutItem * firstItem, Qt::Corner firstCorner, QGraphicsLayoutItem * secondItem, Qt::Corner secondCorner)
Creates two anchors between firstItem and secondItem specified by the corners, firstCorner and secondCorner, where one is for the horizontal edge and another one for the vertical edge.
This is a convenience function, since anchoring corners can be expressed as anchoring two edges. For instance:
    layout->addAnchor(a, Qt::AnchorTop, layout, Qt::AnchorTop);
    layout->addAnchor(a, Qt::AnchorLeft, layout, Qt::AnchorLeft);
This can also be achieved with the following line of code:
    layout->addCornerAnchors(a, Qt::TopLeftCorner, layout, Qt::TopLeftCorner);
If there is already an anchor between the edge pairs, it will be replaced by the anchors that this function specifies.
firstItem and secondItem are automatically added to the layout if they are not part of the layout. This means that count() can increase by up to 2.
See also
addAnchor(), addAnchors()
Definition at line 326 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(QGraphicsAnchorLayout);
     // Horizontal anchor
     Qt::AnchorPoint firstEdge = (firstCorner & 1 ? Qt::AnchorRight: Qt::AnchorLeft);
     Qt::AnchorPoint secondEdge = (secondCorner & 1 ? Qt::AnchorRight: Qt::AnchorLeft);
     if (d->addAnchor(firstItem, firstEdge, secondItem, secondEdge)) {
         // Vertical anchor
         firstEdge = (firstCorner & 2 ? Qt::AnchorBottom: Qt::AnchorTop);
         secondEdge = (secondCorner & 2 ? Qt::AnchorBottom: Qt::AnchorTop);
         d->addAnchor(firstItem, firstEdge, secondItem, secondEdge);
         invalidate();
     }
 }
anchor()
QGraphicsAnchor * QGraphicsAnchorLayout::anchor (QGraphicsLayoutItem * firstItem, Qt::AnchorPoint firstEdge, QGraphicsLayoutItem * secondItem, Qt::AnchorPoint secondEdge)
Returns the anchor between the anchor points defined by firstItem and firstEdge and secondItem and secondEdge.
If there is no such anchor, the function will return 0.
Definition at line 297 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(QGraphicsAnchorLayout);
     return d->getAnchor(firstItem, firstEdge, secondItem, secondEdge);
 }
count()
int QGraphicsAnchorLayout::count () const virtual
Reimplemented Function
Implements QGraphicsLayout.
Definition at line 488 of file qgraphicsanchorlayout.cpp.
Referenced by ~QGraphicsAnchorLayout().
 {
     Q_D(const QGraphicsAnchorLayout);
     return d->items.size();
 }
horizontalSpacing()
qreal QGraphicsAnchorLayout::horizontalSpacing () const
Returns the default horizontal spacing for the anchor layout.
See also
verticalSpacing(), setHorizontalSpacing()
Definition at line 429 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(const QGraphicsAnchorLayout);
     return d->styleInfo().defaultSpacing(Qt::Horizontal);
 }
invalidate()
void QGraphicsAnchorLayout::invalidate () virtual
Reimplemented Function
Reimplemented from QGraphicsLayout.
Definition at line 506 of file qgraphicsanchorlayout.cpp.
Referenced by addAnchor(), addCornerAnchors(), removeAt(), setHorizontalSpacing(), setSpacing(), and setVerticalSpacing().
 {
     Q_D(QGraphicsAnchorLayout);
     QGraphicsLayout::invalidate();
     d->calculateGraphCacheDirty = true;
     d->styleInfoDirty = true;
 }
itemAt()
QGraphicsLayoutItem * QGraphicsAnchorLayout::itemAt (int index) const virtual
Reimplemented Function
Implements QGraphicsLayout.
Definition at line 497 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(const QGraphicsAnchorLayout);
     return d->items.value(index);
 }
removeAt()
void QGraphicsAnchorLayout::removeAt (int index) virtual
Removes the layout item at index without destroying it.
Ownership of the item is transferred to the caller.
Removing an item will also remove any of the anchors associated with it.
See also
itemAt(), count()
Implements QGraphicsLayout.
Definition at line 467 of file qgraphicsanchorlayout.cpp.
Referenced by ~QGraphicsAnchorLayout().
 {
     Q_D(QGraphicsAnchorLayout);
     QGraphicsLayoutItem *item = d->items.value(index);
     if (!item)
         return;
     // Removing an item affects both horizontal and vertical graphs
     d->removeCenterConstraints(item, QGraphicsAnchorLayoutPrivate::Horizontal);
     d->removeCenterConstraints(item, QGraphicsAnchorLayoutPrivate::Vertical);
     d->removeAnchors(item);
     d->items.remove(index);
     item->setParentLayoutItem(0);
     invalidate();
 }
setGeometry()
void QGraphicsAnchorLayout::setGeometry (const QRectF & rect) virtual
Reimplemented Function
Reimplemented from QGraphicsLayoutItem.
Definition at line 449 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(QGraphicsAnchorLayout);
     QGraphicsLayout::setGeometry(geom);
     d->calculateVertexPositions(QGraphicsAnchorLayoutPrivate::Horizontal);
     d->calculateVertexPositions(QGraphicsAnchorLayoutPrivate::Vertical);
     d->setItemsGeometries(geom);
 }
setHorizontalSpacing()
void QGraphicsAnchorLayout::setHorizontalSpacing (qreal spacing)
Sets the default horizontal spacing for the anchor layout to spacing.
See also
horizontalSpacing(), setVerticalSpacing(), setSpacing()
Definition at line 384 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(QGraphicsAnchorLayout);
     d->spacings[0] = spacing;
     invalidate();
 }
setSpacing()
void QGraphicsAnchorLayout::setSpacing (qreal spacing)
Sets the default horizontal and the default vertical spacing for the anchor layout to spacing.
If an item is anchored with no spacing associated with the anchor, it will use the default spacing.
QGraphicsAnchorLayout does not support negative spacings. Setting a negative value will unset the previous spacing and make the layout use the spacing provided by the current widget style.
See also
setHorizontalSpacing(), setVerticalSpacing()
Definition at line 416 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(QGraphicsAnchorLayout);
     d->spacings[0] = d->spacings[1] = spacing;
     invalidate();
 }
setVerticalSpacing()
void QGraphicsAnchorLayout::setVerticalSpacing (qreal spacing)
Sets the default vertical spacing for the anchor layout to spacing.
See also
verticalSpacing(), setHorizontalSpacing(), setSpacing()
Definition at line 397 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(QGraphicsAnchorLayout);
     d->spacings[1] = spacing;
     invalidate();
 }
sizeHint()
QSizeF QGraphicsAnchorLayout::sizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const protected virtual
Reimplemented Function
Implements QGraphicsLayoutItem.
Definition at line 517 of file qgraphicsanchorlayout.cpp.
 {
     Q_UNUSED(constraint);
     Q_D(const QGraphicsAnchorLayout);
     // Some setup calculations are delayed until the information is
     // actually needed, avoiding unnecessary recalculations when
     // adding multiple anchors.
     // sizeHint() / effectiveSizeHint() already have a cache
     // mechanism, using invalidate() to force recalculation. However
     // sizeHint() is called three times after invalidation (for max,
     // min and pref), but we just need do our setup once.
     const_cast<QGraphicsAnchorLayoutPrivate *>(d)->calculateGraphs();
     // ### apply constraint!
     QSizeF engineSizeHint(
         d->sizeHints[QGraphicsAnchorLayoutPrivate::Horizontal][which],
         d->sizeHints[QGraphicsAnchorLayoutPrivate::Vertical][which]);
     qreal left, top, right, bottom;
     getContentsMargins(&left, &top, &right, &bottom);
     return engineSizeHint + QSizeF(left + right, top + bottom);
 }
verticalSpacing()
qreal QGraphicsAnchorLayout::verticalSpacing () const
Returns the default vertical spacing for the anchor layout.
See also
horizontalSpacing(), setVerticalSpacing()
Definition at line 440 of file qgraphicsanchorlayout.cpp.
 {
     Q_D(const QGraphicsAnchorLayout);
     return d->styleInfo().defaultSpacing(Qt::Vertical);
 }
Friends and Related Functions
QGraphicsAnchor
friend class QGraphicsAnchor friend
Definition at line 119 of file qgraphicsanchorlayout.h.
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsanchorlayout.h
/src/gui/graphicsview/qgraphicsanchorlayout.cpp