Qt 4.8: QCalendarWidget Class Reference
QCalendarWidget Class Reference
The QCalendarWidget class provides a monthly based calendar widget allowing the user to select a date.
#include <qcalendarwidget.h>
Public Types
enum HorizontalHeaderFormat { NoHorizontalHeader, SingleLetterDayNames, ShortDayNames, LongDayNames }
This enum type defines the various formats the horizontal header can display.
enum SelectionMode { NoSelection, SingleSelection }
This enum describes the types of selection offered to the user for selecting dates in the calendar.
enum VerticalHeaderFormat { NoVerticalHeader, ISOWeekNumbers }
This enum type defines the various formats the vertical header can display.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void setCurrentPage (int year, int month)
Displays the given month of the given year without changing the selected date.
void setDateRange (const QDate &min, const QDate &max)
Defines a date range by setting the minimumDate and maximumDate properties.
void setGridVisible (bool show)
void setNavigationBarVisible (bool visible)
void setSelectedDate (const QDate &date)
void showNextMonth ()
Shows the next month relative to the currently displayed month.
void showNextYear ()
Shows the currently displayed month in the next year relative to the currently displayed year.
void showPreviousMonth ()
Shows the previous month relative to the currently displayed month.
void showPreviousYear ()
Shows the currently displayed month in the previous year relative to the currently displayed year.
void showSelectedDate ()
Shows the month of the selected date.
void showToday ()
Shows the month of the today's date.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void activated (const QDate &date)
This signal is emitted whenever the user presses the Return or Enter key or double-clicks a date in the calendar widget.
void clicked (const QDate &date)
This signal is emitted when a mouse button is clicked.
void currentPageChanged (int year, int month)
This signal is emitted when the currently shown month is changed.
void selectionChanged ()
This signal is emitted when the currently selected date is changed.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int dateEditAcceptDelay () const
QMap< QDate, QTextCharFormat > dateTextFormat () const
Returns a QMap from QDate to QTextCharFormat showing all dates that use a special format that alters their rendering.
QTextCharFormat dateTextFormat (const QDate &date) const
Returns a QTextCharFormat for date.
Qt::DayOfWeek firstDayOfWeek () const
QTextCharFormat headerTextFormat () const
Returns the text char format for rendering the header.
HorizontalHeaderFormat horizontalHeaderFormat () const
bool isDateEditEnabled () const
bool isGridVisible () const
bool isHeaderVisible () const
Use setNavigationBarVisible() instead.
bool isNavigationBarVisible () const
QDate maximumDate () const
QDate minimumDate () const
virtual QSize minimumSizeHint () const
Reimplemented Function
int monthShown () const
Returns the currently displayed month.
QCalendarWidget (QWidget *parent=0)
Constructs a calendar widget with the given parent.
QDate selectedDate () const
SelectionMode selectionMode () const
void setDateEditAcceptDelay (int delay)
void setDateEditEnabled (bool enable)
void setDateTextFormat (const QDate &date, const QTextCharFormat &format)
Sets the format used to render the given date to that specified by format.
void setFirstDayOfWeek (Qt::DayOfWeek dayOfWeek)
void setHeaderTextFormat (const QTextCharFormat &format)
Sets the text char format for rendering the header to format.
void setHeaderVisible (bool show)
Use setNavigationBarVisible() instead.
void setHorizontalHeaderFormat (HorizontalHeaderFormat format)
void setMaximumDate (const QDate &date)
void setMinimumDate (const QDate &date)
void setSelectionMode (SelectionMode mode)
void setVerticalHeaderFormat (VerticalHeaderFormat format)
void setWeekdayTextFormat (Qt::DayOfWeek dayOfWeek, const QTextCharFormat &format)
Sets the text char format for rendering of day in the week dayOfWeek to format.
virtual QSize sizeHint () const
Reimplemented Function
VerticalHeaderFormat verticalHeaderFormat () const
QTextCharFormat weekdayTextFormat (Qt::DayOfWeek dayOfWeek) const
Returns the text char format for rendering of day in the week dayOfWeek.
int yearShown () const
Returns the year of the currently displayed month.
~QCalendarWidget ()
Destroys the calendar widget.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
bool event (QEvent *event)
Reimplemented Function
bool eventFilter (QObject *watched, QEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
virtual void paintCell (QPainter *painter, const QRect &rect, const QDate &date) const
Paints the cell specified by the given date, using the given painter and rect.
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void updateCell (const QDate &date)
Updates the cell specified by the given date unless updates are disabled or the cell is hidden.
void updateCells ()
Updates all visible cells unless updates are disabled.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
int dateEditAcceptDelay
the time an inactive date edit is shown before its contents are accepted
bool dateEditEnabled
whether the date edit popup is enabled
Qt::DayOfWeek firstDayOfWeek
a value identifying the day displayed in the first column.
bool gridVisible
whether the table grid is displayed.
bool headerVisible
whether the navigation bar is shown or not
HorizontalHeaderFormat horizontalHeaderFormat
the format of the horizontal header.
QDate maximumDate
the maximum date of the currently specified date range.
QDate minimumDate
the minimum date of the currently specified date range.
bool navigationBarVisible
whether the navigation bar is shown or not
QDate selectedDate
the currently selected date.
SelectionMode selectionMode
the type of selection the user can make in the calendar
VerticalHeaderFormat verticalHeaderFormat
the format of the vertical header.
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QCalendarWidget class provides a monthly based calendar widget allowing the user to select a date.
Since
4.2
The widget is initialized with the current month and year, but QCalendarWidget provides several public slots to change the year and month that is shown.
By default, today's date is selected, and the user can select a date using both mouse and keyboard. The currently selected date can be retrieved using the selectedDate() function. It is possible to constrain the user selection to a given date range by setting the minimumDate and maximumDate properties. Alternatively, both properties can be set in one go using the setDateRange() convenience slot. Set the selectionMode property to NoSelection to prohibit the user from selecting at all. Note that a date also can be selected programmatically using the setSelectedDate() slot.
The currently displayed month and year can be retrieved using the monthShown() and yearShown() functions, respectively.
A newly created calendar widget uses abbreviated day names, and both Saturdays and Sundays are marked in red. The calendar grid is not visible. The week numbers are displayed, and the first column day is Sunday.
The notation of the days can be altered to a single letter abbreviations ("M" for "Monday") by setting the horizontalHeaderFormat property to QCalendarWidget::SingleLetterDayNames. Setting the same property to QCalendarWidget::LongDayNames makes the header display the complete day names. The week numbers can be removed by setting the verticalHeaderFormat property to QCalendarWidget::NoVerticalHeader. The calendar grid can be turned on by setting the gridVisible property to true using the setGridVisible() function:
QCalendarWidget *calendar;
calendar->setGridVisible(true);
Finally, the day in the first column can be altered using the setFirstDayOfWeek() function.
The QCalendarWidget class also provides three signals, selectionChanged(), activated() and currentPageChanged() making it possible to respond to user interaction.
The rendering of the headers, weekdays or single days can be largely customized by setting QTextCharFormat's for some special weekday, a special date or for the rendering of the headers.
Only a subset of the properties in QTextCharFormat are used by the calendar widget. Currently, the foreground, background and font properties are used to determine the rendering of individual cells in the widget.
See also
QDate, QDateEdit, QTextCharFormat
Definition at line 60 of file qcalendarwidget.h.
Enumerations
HorizontalHeaderFormat
enum QCalendarWidget::HorizontalHeaderFormat
This enum type defines the various formats the horizontal header can display.
SingleLetterDayNames The header displays a single letter abbreviation for day names (e.g. M for Monday).
ShortDayNames The header displays a short abbreviation for day names (e.g. Mon for Monday).
LongDayNames The header displays complete day names (e.g. Monday).
NoHorizontalHeader The header is hidden.
See also
horizontalHeaderFormat(), VerticalHeaderFormat
Enumerator
NoHorizontalHeader
SingleLetterDayNames
ShortDayNames
LongDayNames
Definition at line 81 of file qcalendarwidget.h.
{
         NoHorizontalHeader,
         SingleLetterDayNames,
         ShortDayNames,
         LongDayNames
     };
SelectionMode
enum QCalendarWidget::SelectionMode
This enum describes the types of selection offered to the user for selecting dates in the calendar.
NoSelection Dates cannot be selected.
SingleSelection Single dates can be selected.
See also
selectionMode
Enumerator
NoSelection
SingleSelection
Definition at line 93 of file qcalendarwidget.h.
{
         NoSelection,
         SingleSelection
     };
VerticalHeaderFormat
enum QCalendarWidget::VerticalHeaderFormat
This enum type defines the various formats the vertical header can display.
ISOWeekNumbers The header displays ISO week numbers as described by QDate::weekNumber() .
NoVerticalHeader The header is hidden.
See also
verticalHeaderFormat(), HorizontalHeaderFormat
Enumerator
NoVerticalHeader
ISOWeekNumbers
Definition at line 88 of file qcalendarwidget.h.
{
         NoVerticalHeader,
         ISOWeekNumbers
     };
Constructors and Destructors
QCalendarWidget()
QCalendarWidget::QCalendarWidget (QWidget * parent = 0) explicit
Constructs a calendar widget with the given parent.
The widget is initialized with the current month and year, and the currently selected date is today.
See also
setCurrentPage()
Definition at line 2052 of file qcalendarwidget.cpp.
     : QWidget(*new QCalendarWidgetPrivate, parent, 0)
 {
     Q_D(QCalendarWidget);
     setAutoFillBackground(true);
     setBackgroundRole(QPalette::Window);
     QVBoxLayout *layoutV = new QVBoxLayout(this);
     layoutV->setMargin(0);
     d->m_model = new QCalendarModel(this);
     QTextCharFormat fmt;
     fmt.setForeground(QBrush(Qt::red));
     d->m_model->m_dayFormats.insert(Qt::Saturday, fmt);
     d->m_model->m_dayFormats.insert(Qt::Sunday, fmt);
     d->m_view = new QCalendarView(this);
     d->m_view->setObjectName(QLatin1String("qt_calendar_calendarview"));
     d->m_view->setModel(d->m_model);
     d->m_model->setView(d->m_view);
     d->m_view->setSelectionBehavior(QAbstractItemView::SelectItems);
     d->m_view->setSelectionMode(QAbstractItemView::SingleSelection);
     d->m_view->horizontalHeader()->setResizeMode(QHeaderView::Stretch);
     d->m_view->horizontalHeader()->setClickable(false);
     d->m_view->verticalHeader()->setResizeMode(QHeaderView::Stretch);
     d->m_view->verticalHeader()->setClickable(false);
     d->m_selection = d->m_view->selectionModel();
     d->createNavigationBar(this);
     d->m_view->setFrameStyle(QFrame::NoFrame);
     d->m_delegate = new QCalendarDelegate(d, this);
     d->m_view->setItemDelegate(d->m_delegate);
     d->update();
     d->updateNavigationBar();
     setFocusPolicy(Qt::StrongFocus);
     setFocusProxy(d->m_view);
     setSizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
     connect(d->m_view, SIGNAL(showDate(QDate)),
             this, SLOT(_q_slotShowDate(QDate)));
     connect(d->m_view, SIGNAL(changeDate(QDate,bool)),
             this, SLOT(_q_slotChangeDate(QDate,bool)));
     connect(d->m_view, SIGNAL(clicked(QDate)),
             this, SIGNAL(clicked(QDate)));
     connect(d->m_view, SIGNAL(editingFinished()),
             this, SLOT(_q_editingFinished()));
     connect(d->prevMonth, SIGNAL(clicked(bool)),
             this, SLOT(_q_prevMonthClicked()));
     connect(d->nextMonth, SIGNAL(clicked(bool)),
             this, SLOT(_q_nextMonthClicked()));
     connect(d->yearButton, SIGNAL(clicked(bool)),
             this, SLOT(_q_yearClicked()));
     connect(d->monthMenu, SIGNAL(triggered(QAction*)),
             this, SLOT(_q_monthChanged(QAction*)));
     connect(d->yearEdit, SIGNAL(editingFinished()),
             this, SLOT(_q_yearEditingFinished()));
     layoutV->setMargin(0);
     layoutV->setSpacing(0);
     layoutV->addWidget(d->navBarBackground);
     layoutV->addWidget(d->m_view);
     d->m_navigator = new QCalendarTextNavigator(this);
     setDateEditEnabled(true);
 }
~QCalendarWidget()
QCalendarWidget::~QCalendarWidget ()
Destroys the calendar widget.
Definition at line 2120 of file qcalendarwidget.cpp.
 {
 }
Functions
activated
void QCalendarWidget::activated (const QDate & date) signal
This signal is emitted whenever the user presses the Return or Enter key or double-clicks a date in the calendar widget.
clicked
void QCalendarWidget::clicked (const QDate & date) signal
This signal is emitted when a mouse button is clicked.
The date the mouse was clicked on is specified by date. The signal is only emitted when clicked on a valid date, e.g., dates are not outside the minimumDate() and maximumDate(). If the selection mode is NoSelection, this signal will not be emitted.
Referenced by QCalendarWidget().
currentPageChanged
void QCalendarWidget::currentPageChanged (int year, int month) signal
This signal is emitted when the currently shown month is changed.
The new year and month are passed as parameters.
See also
setCurrentPage()
dateEditAcceptDelay()
int QCalendarWidget::dateEditAcceptDelay () const
Referenced by setDateEditEnabled().
dateTextFormat() [1/2]
QMap< QDate, QTextCharFormat > QCalendarWidget::dateTextFormat () const
Returns a QMap from QDate to QTextCharFormat showing all dates that use a special format that alters their rendering.
Definition at line 2804 of file qcalendarwidget.cpp.
 {
     Q_D(const QCalendarWidget);
     return d->m_model->m_dateFormats;
 }
dateTextFormat() [2/2]
QTextCharFormat QCalendarWidget::dateTextFormat (const QDate & date) const
Returns a QTextCharFormat for date.
The char format can be be empty if the date is not renderd specially.
Definition at line 2814 of file qcalendarwidget.cpp.
 {
     Q_D(const QCalendarWidget);
     return d->m_model->m_dateFormats.value(date);
 }
event()
bool QCalendarWidget::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3074 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     switch (event->type()) {
         case QEvent::LayoutDirectionChange:
             d->updateButtonIcons();
         case QEvent::LocaleChange:
             d->cachedSizeHint = QSize();
             d->updateMonthMenuNames();
             d->updateNavigationBar();
             d->m_view->updateGeometry();
             break;
         case QEvent::FontChange:
         case QEvent::ApplicationFontChange:
             d->cachedSizeHint = QSize();
             d->m_view->updateGeometry();
             break;
         case QEvent::StyleChange:
             d->cachedSizeHint = QSize();
             d->m_view->updateGeometry();
         default:
             break;
     }
     return QWidget::event(event);
 }
eventFilter()
bool QCalendarWidget::eventFilter (QObject * watched, QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 3103 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     if (event->type() == QEvent::MouseButtonPress && d->yearEdit->hasFocus()) {
         QWidget *tlw = window();
         QWidget *widget = static_cast<QWidget*>(watched);
         //as we have a event filter on the whole application we first make sure that the top level widget
         //of both this and the watched widget are the same to decide if we should finish the year edition.
         if (widget->window() == tlw) {
             QPoint mousePos = widget->mapTo(tlw, static_cast<QMouseEvent *>(event)->pos());
             QRect geom = QRect(d->yearEdit->mapTo(tlw, QPoint(0, 0)), d->yearEdit->size());
             if (!geom.contains(mousePos)) {
                 event->accept();
                 d->_q_yearEditingFinished();
                 setFocus();
                 return true;
             }
         }
     }
     return QWidget::eventFilter(watched, event);
 }
firstDayOfWeek()
Qt::DayOfWeek QCalendarWidget::firstDayOfWeek () const
Referenced by setFirstDayOfWeek().
headerTextFormat()
QTextCharFormat QCalendarWidget::headerTextFormat () const
Returns the text char format for rendering the header.
Definition at line 2751 of file qcalendarwidget.cpp.
 {
     Q_D(const QCalendarWidget);
     return d->m_model->m_headerFormat;
 }
horizontalHeaderFormat()
HorizontalHeaderFormat QCalendarWidget::horizontalHeaderFormat () const
Referenced by minimumSizeHint(), and setHorizontalHeaderFormat().
isDateEditEnabled()
bool QCalendarWidget::isDateEditEnabled () const
Definition at line 2857 of file qcalendarwidget.cpp.
Referenced by setDateEditEnabled(), and setSelectionMode().
 {
     Q_D(const QCalendarWidget);
     return d->m_dateEditEnabled;
 }
isGridVisible()
bool QCalendarWidget::isGridVisible () const
Definition at line 2674 of file qcalendarwidget.cpp.
 {
     Q_D(const QCalendarWidget);
     return d->m_view->showGrid();
 }
isHeaderVisible()
bool QCalendarWidget::isHeaderVisible () const
Use setNavigationBarVisible() instead.
Definition at line 3026 of file qcalendarwidget.cpp.
 {
     Q_D(const QCalendarWidget);
     return d->navBarVisible;
 }
isNavigationBarVisible()
bool QCalendarWidget::isNavigationBarVisible () const inline
Definition at line 122 of file qcalendarwidget.h.
Referenced by QAccessibleCalendarWidget::childCount().
 { return isHeaderVisible(); }
keyPressEvent()
void QCalendarWidget::keyPressEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3154 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     if(d->yearEdit->isVisible()&& event->key() == Qt::Key_Escape)
     {
         d->yearEdit->setValue(yearShown());
         d->_q_yearEditingFinished();
         return;
     }
     QWidget::keyPressEvent(event);
 }
maximumDate()
QDate QCalendarWidget::maximumDate () const
Referenced by setMinimumDate().
minimumDate()
QDate QCalendarWidget::minimumDate () const
Referenced by showToday().
minimumSizeHint()
QSize QCalendarWidget::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2135 of file qcalendarwidget.cpp.
Referenced by sizeHint().
 {
     Q_D(const QCalendarWidget);
     if (d->cachedSizeHint.isValid())
         return d->cachedSizeHint;
     ensurePolished();
     int w = 0;
     int h = 0;
     int end = 53;
     int rows = 7;
     int cols = 8;
     const int marginH = (style()->pixelMetric(QStyle::PM_FocusFrameHMargin) + 1) * 2;
     if (horizontalHeaderFormat() == QCalendarWidget::NoHorizontalHeader) {
         rows = 6;
     } else {
         for (int i = 1; i <= 7; i++) {
             QFontMetrics fm(d->m_model->formatForCell(0, i).font());
             w = qMax(w, fm.width(d->m_model->dayName(d->m_model->dayOfWeekForColumn(i))) + marginH);
             h = qMax(h, fm.height());
         }
     }
     if (verticalHeaderFormat() == QCalendarWidget::NoVerticalHeader) {
         cols = 7;
     } else {
         for (int i = 1; i <= 6; i++) {
             QFontMetrics fm(d->m_model->formatForCell(i, 0).font());
             for (int j = 1; j < end; j++)
                 w = qMax(w, fm.width(QString::number(j)) + marginH);
             h = qMax(h, fm.height());
         }
     }
     QFontMetrics fm(d->m_model->formatForCell(1, 1).font());
     for (int i = 1; i <= end; i++) {
         w = qMax(w, fm.width(QString::number(i)) + marginH);
         h = qMax(h, fm.height());
     }
     if (d->m_view->showGrid()) {
         // hardcoded in tableview
         w += 1;
         h += 1;
     }
     w += 1; // default column span
     h = qMax(h, d->m_view->verticalHeader()->minimumSectionSize());
     w = qMax(w, d->m_view->horizontalHeader()->minimumSectionSize());
     //add the size of the header.
     QSize headerSize(0, 0);
     if (d->navBarVisible) {
         int headerH = d->navBarBackground->sizeHint().height();
         int headerW = 0;
         headerW += d->prevMonth->sizeHint().width();
         headerW += d->nextMonth->sizeHint().width();
         QFontMetrics fm = d->monthButton->fontMetrics();
         int monthW = 0;
         for (int i = 1; i < 12; i++) {
             QString monthName = locale().standaloneMonthName(i, QLocale::LongFormat);
             monthW = qMax(monthW, fm.boundingRect(monthName).width());
         }
         const int buttonDecoMargin = d->monthButton->sizeHint().width() - fm.boundingRect(d->monthButton->text()).width();
         headerW += monthW + buttonDecoMargin;
         fm = d->yearButton->fontMetrics();
         headerW += fm.boundingRect(QLatin1String("5555")).width() + buttonDecoMargin;
         headerSize = QSize(headerW, headerH);
     }
     w *= cols;
     w = qMax(headerSize.width(), w);
     h = (h * rows) + headerSize.height();
     d->cachedSizeHint = QSize(w, h);
     return d->cachedSizeHint;
 }
monthShown()
int QCalendarWidget::monthShown () const
Returns the currently displayed month.
Months are numbered from 1 to 12.
See also
yearShown(), setCurrentPage()
Definition at line 2286 of file qcalendarwidget.cpp.
Referenced by showNextMonth(), showNextYear(), showPreviousMonth(), and showPreviousYear().
 {
     Q_D(const QCalendarWidget);
     return d->m_model->m_shownMonth;
 }
mousePressEvent()
void QCalendarWidget::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3128 of file qcalendarwidget.cpp.
 {
     setAttribute(Qt::WA_NoMouseReplay);
     QWidget::mousePressEvent(event);
     setFocus();
 }
paintCell()
void QCalendarWidget::paintCell (QPainter * painter, const QRect & rect, const QDate & date) const protected virtual
Paints the cell specified by the given date, using the given painter and rect.
Definition at line 2224 of file qcalendarwidget.cpp.
 {
     Q_D(const QCalendarWidget);
     d->m_delegate->paintCell(painter, rect, date);
 }
resizeEvent()
void QCalendarWidget::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 3138 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     // XXX Should really use a QWidgetStack for yearEdit and yearButton,
     // XXX here we hide the year edit when the layout is likely to break
     // XXX the manual positioning of the yearEdit over the yearButton.
     if(d->yearEdit->isVisible() && event->size().width() != event->oldSize().width())
         d->_q_yearEditingFinished();
     QWidget::resizeEvent(event);
 }
selectedDate()
QDate QCalendarWidget::selectedDate () const
Referenced by paintCell(), and showSelectedDate().
selectionChanged
void QCalendarWidget::selectionChanged () signal
This signal is emitted when the currently selected date is changed.
The currently selected date can be changed by the user using the mouse or keyboard, or by the programmer using setSelectedDate().
See also
selectedDate()
Referenced by setDateRange(), setMaximumDate(), setMinimumDate(), and setSelectedDate().
selectionMode()
SelectionMode QCalendarWidget::selectionMode () const
Referenced by setDateEditEnabled(), setGridVisible(), and setSelectionMode().
setCurrentPage
void QCalendarWidget::setCurrentPage (int year, int month) slot
Displays the given month of the given year without changing the selected date.
Use the setSelectedDate() function to alter the selected date.
The currently displayed month and year can be retrieved using the monthShown() and yearShown() functions respectively.
See also
yearShown(), monthShown(), showPreviousMonth(), showNextMonth(), showPreviousYear(), showNextYear()
Definition at line 2304 of file qcalendarwidget.cpp.
Referenced by showNextMonth(), showNextYear(), showPreviousMonth(), showPreviousYear(), showSelectedDate(), and showToday().
 {
     Q_D(QCalendarWidget);
     QDate currentDate = d->getCurrentDate();
     int day = currentDate.day();
     int daysInMonths = QDate(year, month, 1).daysInMonth();
     if (day > daysInMonths)
         day = daysInMonths;
     d->showMonth(year, month);
     QDate newDate(year, month, day);
     int row = -1, col = -1;
     d->m_model->cellForDate(newDate, &row, &col);
     if (row != -1 && col != -1) {
         d->m_view->selectionModel()->setCurrentIndex(d->m_model->index(row, col),
                                                   QItemSelectionModel::NoUpdate);
     }
 }
setDateEditAcceptDelay()
void QCalendarWidget::setDateEditAcceptDelay (int delay)
Definition at line 2895 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     d->m_navigator->setDateEditAcceptDelay(delay);
 }
setDateEditEnabled()
void QCalendarWidget::setDateEditEnabled (bool enable)
Definition at line 2863 of file qcalendarwidget.cpp.
Referenced by QCalendarWidget().
 {
     Q_D(QCalendarWidget);
     if (isDateEditEnabled() == enable)
         return;
     d->m_dateEditEnabled = enable;
     d->setNavigatorEnabled(enable && (selectionMode() != QCalendarWidget::NoSelection));
 }
setDateRange
void QCalendarWidget::setDateRange (const QDate & min, const QDate & max) slot
Defines a date range by setting the minimumDate and maximumDate properties.
The date range restricts the user selection, i.e. the user can only select dates within the specified date range. Note that
QCalendarWidget *calendar;
calendar->setDateRange(min, max);
is analogous to
QCalendarWidget *calendar;
calendar->setMinimumDate(min);
calendar->setMaximumDate(max);
If either the min or max parameters are not valid QDate objects, this function does nothing.
See also
setMinimumDate(), setMaximumDate()
Definition at line 2543 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     if (d->m_model->m_minimumDate == min && d->m_model->m_maximumDate == max)
         return;
     if (!min.isValid() || !max.isValid())
         return;
     QDate oldDate = d->m_model->m_date;
     d->m_model->setRange(min, max);
     d->yearEdit->setMinimum(d->m_model->m_minimumDate.year());
     d->yearEdit->setMaximum(d->m_model->m_maximumDate.year());
     d->updateMonthMenu();
     QDate newDate = d->m_model->m_date;
     if (oldDate != newDate) {
         d->update();
         d->showMonth(newDate.year(), newDate.month());
         d->m_navigator->setDate(newDate);
         emit selectionChanged();
     }
 }
setDateTextFormat()
void QCalendarWidget::setDateTextFormat (const QDate & date, const QTextCharFormat & format)
Sets the format used to render the given date to that specified by format.
If date is null, all date formats are cleared.
Definition at line 2825 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     if (date.isNull())
         d->m_model->m_dateFormats.clear();
     else
         d->m_model->m_dateFormats[date] = format;
     d->m_view->viewport()->update();
     d->m_view->updateGeometry();
 }
setFirstDayOfWeek()
void QCalendarWidget::setFirstDayOfWeek (Qt::DayOfWeek dayOfWeek)
Definition at line 2732 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     if ((Qt::DayOfWeek)d->m_model->firstColumnDay() == dayOfWeek)
         return;
     d->m_model->setFirstColumnDay(dayOfWeek);
     d->update();
 }
setGridVisible
void QCalendarWidget::setGridVisible (bool show) slot
Definition at line 2680 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     d->m_view->setShowGrid(show);
     d->cachedSizeHint = QSize();
     d->m_view->viewport()->update();
     d->m_view->updateGeometry();
 }
setHeaderTextFormat()
void QCalendarWidget::setHeaderTextFormat (const QTextCharFormat & format)
Sets the text char format for rendering the header to format.
If you also set a weekday text format, this format's foreground and background color will take precedence over the header's format. The other formatting information will still be decided by the header's format.
Definition at line 2764 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     d->m_model->m_headerFormat = format;
     d->cachedSizeHint = QSize();
     d->m_view->viewport()->update();
     d->m_view->updateGeometry();
 }
setHeaderVisible()
void QCalendarWidget::setHeaderVisible (bool visible)
Use setNavigationBarVisible() instead.
Definition at line 3041 of file qcalendarwidget.cpp.
 {
     setNavigationBarVisible(visible);
 }
setHorizontalHeaderFormat()
void QCalendarWidget::setHorizontalHeaderFormat (QCalendarWidget::HorizontalHeaderFormat format)
Definition at line 2591 of file qcalendarwidget.cpp.
Referenced by QCalendarPopup::verifyCalendarInstance().
 {
     Q_D(QCalendarWidget);
     if (d->m_model->m_horizontalHeaderFormat == format)
         return;
     d->m_model->setHorizontalHeaderFormat(format);
     d->cachedSizeHint = QSize();
     d->m_view->viewport()->update();
     d->m_view->updateGeometry();
 }
setMaximumDate()
void QCalendarWidget::setMaximumDate (const QDate & date)
Definition at line 2505 of file qcalendarwidget.cpp.
Referenced by QCalendarPopup::setDateRange().
 {
     Q_D(QCalendarWidget);
     if (!date.isValid() || d->m_model->m_maximumDate == date)
         return;
     QDate oldDate = d->m_model->m_date;
     d->m_model->setMaximumDate(date);
     d->yearEdit->setMaximum(d->m_model->m_maximumDate.year());
     d->updateMonthMenu();
     QDate newDate = d->m_model->m_date;
     if (oldDate != newDate) {
         d->update();
         d->showMonth(newDate.year(), newDate.month());
         d->m_navigator->setDate(newDate);
         emit selectionChanged();
     }
 }
setMinimumDate()
void QCalendarWidget::setMinimumDate (const QDate & date)
Definition at line 2452 of file qcalendarwidget.cpp.
Referenced by QCalendarPopup::setDateRange().
 {
     Q_D(QCalendarWidget);
     if (!date.isValid() || d->m_model->m_minimumDate == date)
         return;
     QDate oldDate = d->m_model->m_date;
     d->m_model->setMinimumDate(date);
     d->yearEdit->setMinimum(d->m_model->m_minimumDate.year());
     d->updateMonthMenu();
     QDate newDate = d->m_model->m_date;
     if (oldDate != newDate) {
         d->update();
         d->showMonth(newDate.year(), newDate.month());
         d->m_navigator->setDate(newDate);
         emit selectionChanged();
     }
 }
setNavigationBarVisible
void QCalendarWidget::setNavigationBarVisible (bool visible) slot
Definition at line 3062 of file qcalendarwidget.cpp.
Referenced by setHeaderVisible().
 {
     Q_D(QCalendarWidget);
     d->navBarVisible = visible;
     d->cachedSizeHint = QSize();
     d->navBarBackground->setVisible(visible);
     updateGeometry();
 }
setSelectedDate
void QCalendarWidget::setSelectedDate (const QDate & date) slot
Definition at line 2250 of file qcalendarwidget.cpp.
Referenced by QCalendarPopup::setDate().
 {
     Q_D(QCalendarWidget);
     if (d->m_model->m_date == date && date == d->getCurrentDate())
         return;
     if (!date.isValid())
         return;
     d->m_model->setDate(date);
     d->update();
     QDate newDate = d->m_model->m_date;
     d->showMonth(newDate.year(), newDate.month());
     emit selectionChanged();
 }
setSelectionMode()
void QCalendarWidget::setSelectionMode (SelectionMode mode)
Definition at line 2714 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     d->m_view->readOnly = (mode == QCalendarWidget::NoSelection);
     d->setNavigatorEnabled(isDateEditEnabled() && (selectionMode() != QCalendarWidget::NoSelection));
     d->update();
 }
setVerticalHeaderFormat()
void QCalendarWidget::setVerticalHeaderFormat (QCalendarWidget::VerticalHeaderFormat format)
Definition at line 2643 of file qcalendarwidget.cpp.
Referenced by QCalendarPopup::verifyCalendarInstance().
 {
     Q_D(QCalendarWidget);
     bool show = false;
     if (format == QCalendarWidget::ISOWeekNumbers)
         show = true;
     if (d->m_model->weekNumbersShown() == show)
         return;
     d->m_model->setWeekNumbersShown(show);
     d->cachedSizeHint = QSize();
     d->m_view->viewport()->update();
     d->m_view->updateGeometry();
 }
setWeekdayTextFormat()
void QCalendarWidget::setWeekdayTextFormat (Qt::DayOfWeek dayOfWeek, const QTextCharFormat & format)
Sets the text char format for rendering of day in the week dayOfWeek to format.
The format will take precedence over the header format in case of foreground and background color. Other text formatting information is taken from the headers format.
See also
setHeaderTextFormat()
Definition at line 2791 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     d->m_model->m_dayFormats[dayOfWeek] = format;
     d->cachedSizeHint = QSize();
     d->m_view->viewport()->update();
     d->m_view->updateGeometry();
 }
showNextMonth
void QCalendarWidget::showNextMonth () slot
Shows the next month relative to the currently displayed month.
Note that the selected date is not changed.
See also
showPreviousMonth(), setCurrentPage(), setSelectedDate()
Definition at line 2331 of file qcalendarwidget.cpp.
 {
     int year = yearShown();
     int month = monthShown();
     if (month == 12) {
         ++year;
         month = 1;
     } else {
         ++month;
     }
     setCurrentPage(year, month);
 }
showNextYear
void QCalendarWidget::showNextYear () slot
Shows the currently displayed month in the next year relative to the currently displayed year.
Note that the selected date is not changed.
See also
showPreviousYear(), setCurrentPage(), setSelectedDate()
Definition at line 2372 of file qcalendarwidget.cpp.
 {
     int year = yearShown();
     int month = monthShown();
     ++year;
     setCurrentPage(year, month);
 }
showPreviousMonth
void QCalendarWidget::showPreviousMonth () slot
Shows the previous month relative to the currently displayed month.
Note that the selected date is not changed.
See also
showNextMonth(), setCurrentPage(), setSelectedDate()
Definition at line 2351 of file qcalendarwidget.cpp.
 {
     int year = yearShown();
     int month = monthShown();
     if (month == 1) {
         --year;
         month = 12;
     } else {
         --month;
     }
     setCurrentPage(year, month);
 }
showPreviousYear
void QCalendarWidget::showPreviousYear () slot
Shows the currently displayed month in the previous year relative to the currently displayed year.
Note that the selected date is not changed.
See also
showNextYear(), setCurrentPage(), setSelectedDate()
Definition at line 2388 of file qcalendarwidget.cpp.
 {
     int year = yearShown();
     int month = monthShown();
     --year;
     setCurrentPage(year, month);
 }
showSelectedDate
void QCalendarWidget::showSelectedDate () slot
Shows the month of the selected date.
See also
selectedDate(), setCurrentPage()
Definition at line 2401 of file qcalendarwidget.cpp.
 {
     QDate currentDate = selectedDate();
     setCurrentPage(currentDate.year(), currentDate.month());
 }
showToday
void QCalendarWidget::showToday () slot
Shows the month of the today's date.
See also
selectedDate(), setCurrentPage()
Definition at line 2412 of file qcalendarwidget.cpp.
 {
     QDate currentDate = QDate::currentDate();
     setCurrentPage(currentDate.year(), currentDate.month());
 }
sizeHint()
QSize QCalendarWidget::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2127 of file qcalendarwidget.cpp.
 {
     return minimumSizeHint();
 }
updateCell()
void QCalendarWidget::updateCell (const QDate & date) protected
Updates the cell specified by the given date unless updates are disabled or the cell is hidden.
Since
4.4
See also
updateCells(), yearShown(), monthShown()
Definition at line 2912 of file qcalendarwidget.cpp.
 {
     if (!date.isValid()) {
         qWarning("QCalendarWidget::updateCell: Invalid date");
         return;
     }
     if (!isVisible())
         return;
     Q_D(QCalendarWidget);
     int row, column;
     d->m_model->cellForDate(date, &row, &column);
     if (row == -1 || column == -1)
         return;
     QModelIndex modelIndex = d->m_model->index(row, column);
     if (!modelIndex.isValid())
         return;
     d->m_view->viewport()->update(d->m_view->visualRect(modelIndex));
 }
updateCells()
void QCalendarWidget::updateCells () protected
Updates all visible cells unless updates are disabled.
Since
4.4
See also
updateCell()
Definition at line 2945 of file qcalendarwidget.cpp.
 {
     Q_D(QCalendarWidget);
     if (isVisible())
         d->m_view->viewport()->update();
 }
verticalHeaderFormat()
VerticalHeaderFormat QCalendarWidget::verticalHeaderFormat () const
Referenced by minimumSizeHint(), and setHorizontalHeaderFormat().
weekdayTextFormat()
QTextCharFormat QCalendarWidget::weekdayTextFormat (Qt::DayOfWeek dayOfWeek) const
Returns the text char format for rendering of day in the week dayOfWeek.
See also
headerTextFormat()
Definition at line 2778 of file qcalendarwidget.cpp.
 {
     Q_D(const QCalendarWidget);
     return d->m_model->m_dayFormats.value(dayOfWeek);
 }
yearShown()
int QCalendarWidget::yearShown () const
Returns the year of the currently displayed month.
Months are numbered from 1 to 12.
See also
monthShown(), setCurrentPage()
Definition at line 2273 of file qcalendarwidget.cpp.
Referenced by keyPressEvent(), showNextMonth(), showNextYear(), showPreviousMonth(), and showPreviousYear().
 {
     Q_D(const QCalendarWidget);
     return d->m_model->m_shownYear;
 }
Properties
dateEditAcceptDelay
int QCalendarWidget::dateEditAcceptDelay private
the time an inactive date edit is shown before its contents are accepted
Since
4.3
If the calendar widget's date edit is enabled, this property specifies the amount of time (in millseconds) that the date edit remains open after the most recent user input. Once this time has elapsed, the date specified in the date edit is accepted and the popup is closed.
By default, the delay is defined to be 1500 milliseconds (1.5 seconds).
Definition at line 78 of file qcalendarwidget.h.
dateEditEnabled
QCalendarWidget::dateEditEnabled private
whether the date edit popup is enabled
Since
4.3
If this property is enabled, pressing a non-modifier key will cause a date edit to popup if the calendar widget has focus, allowing the user to specify a date in the form specified by the current locale.
By default, this property is enabled.
The date edit is simpler in appearance than QDateEdit, but allows the user to navigate between fields using the left and right cursor keys, increment and decrement individual fields using the up and down cursor keys, and enter values directly using the number keys.
See also
QCalendarWidget::dateEditAcceptDelay
Definition at line 77 of file qcalendarwidget.h.
firstDayOfWeek
Qt::DayOfWeek QCalendarWidget::firstDayOfWeek private
a value identifying the day displayed in the first column.
By default, the day displayed in the first column is Sunday
Definition at line 70 of file qcalendarwidget.h.
gridVisible
QCalendarWidget::gridVisible private
whether the table grid is displayed.
QCalendarWidget *calendar;
calendar->setGridVisible(true);
The default value is false.
Definition at line 71 of file qcalendarwidget.h.
headerVisible
QCalendarWidget::headerVisible private
whether the navigation bar is shown or not
Use navigationBarVisible() instead.
By default, this property is true.
Definition at line 75 of file qcalendarwidget.h.
horizontalHeaderFormat
QCalendarWidget::HorizontalHeaderFormat QCalendarWidget::horizontalHeaderFormat private
the format of the horizontal header.
The default value is QCalendarWidget::ShortDayNames.
Definition at line 73 of file qcalendarwidget.h.
maximumDate
QDate QCalendarWidget::maximumDate private
the maximum date of the currently specified date range.
The user will not be able to select a date which is after the currently set maximum date.
QCalendarWidget *calendar;
calendar->setGridVisible(true);
calendar->setMaximumDate(QDate(2006, 7, 3));
By default, the maximum date is the last day the QDate class can handle.
When setting a maximum date, the minimumDate and selectedDate properties are adjusted if the selection range becomes invalid. If the provided date is not a valid QDate object, the setMaximumDate() function does nothing.
See also
setDateRange()
Definition at line 69 of file qcalendarwidget.h.
minimumDate
QDate QCalendarWidget::minimumDate private
the minimum date of the currently specified date range.
The user will not be able to select a date that is before the currently set minimum date.
QCalendarWidget *calendar;
calendar->setGridVisible(true);
calendar->setMinimumDate(QDate(2006, 6, 19));
By default, the minimum date is the earliest date that the QDate class can handle.
When setting a minimum date, the maximumDate and selectedDate properties are adjusted if the selection range becomes invalid. If the provided date is not a valid QDate object, the setMinimumDate() function does nothing.
See also
setDateRange()
Definition at line 68 of file qcalendarwidget.h.
navigationBarVisible
QCalendarWidget::navigationBarVisible private
whether the navigation bar is shown or not
Since
4.3
When this property is true (the default), the next month, previous month, month selection, year selection controls are shown on top.
When the property is set to false, these controls are hidden.
Definition at line 76 of file qcalendarwidget.h.
selectedDate
QDate QCalendarWidget::selectedDate private
the currently selected date.
The selected date must be within the date range specified by the minimumDate and maximumDate properties. By default, the selected date is the current date.
See also
setDateRange()
Definition at line 67 of file qcalendarwidget.h.
selectionMode
QCalendarWidget::SelectionMode QCalendarWidget::selectionMode private
the type of selection the user can make in the calendar
When this property is set to SingleSelection, the user can select a date within the minimum and maximum allowed dates, using either the mouse or the keyboard.
When the property is set to NoSelection, the user will be unable to select dates, but they can still be selected programmatically. Note that the date that is selected when the property is set to NoSelection will still be the selected date of the calendar.
The default value is SingleSelection.
Definition at line 72 of file qcalendarwidget.h.
verticalHeaderFormat
QCalendarWidget::VerticalHeaderFormat QCalendarWidget::verticalHeaderFormat private
the format of the vertical header.
The default value is QCalendarWidget::ISOWeekNumber.
Definition at line 74 of file qcalendarwidget.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qcalendarwidget.h
/src/gui/widgets/qcalendarwidget.cpp