Qt 4.8: QWidgetItem Class Reference
QWidgetItem Class Reference
The QWidgetItem class is a layout item that represents a widget.
#include <qlayoutitem.h>
Public Functions
Qt::Orientations expandingDirections () const
Reimplemented Function
QRect geometry () const
Reimplemented Function
bool hasHeightForWidth () const
Reimplemented Function
int heightForWidth (int) const
Reimplemented Function
bool isEmpty () const
Returns true if the widget is hidden; otherwise returns false.
QSize maximumSize () const
Reimplemented Function
QSize minimumSize () const
Reimplemented Function
QWidgetItem (QWidget *w)
Creates an item containing the given widget.
void setGeometry (const QRect &)
Reimplemented Function
QSize sizeHint () const
Reimplemented Function
virtual QWidget * widget ()
Returns the widget managed by this item.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual void invalidate ()
Invalidates any cached information in this layout item.
virtual QLayout * layout ()
If this item is a QLayout, it is returned as a QLayout; otherwise 0 is returned.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Protected Variables
QWidget * wid
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Detailed Description
The QWidgetItem class is a layout item that represents a widget.
Normally, you don't need to use this class directly. Qt's built-in layout managers provide the following functions for manipulating widgets in layouts:
Class Functions
QBoxLayout addWidget(), insertWidget(), setStretchFactor()
QGridLayout addWidget()
QStackedLayout addWidget(), insertWidget(), currentWidget(), setCurrentWidget(), widget()
See also
QLayout, QSpacerItem, QLayoutItem::widget()
Definition at line 122 of file qlayoutitem.h.
Constructors and Destructors
QWidgetItem()
QWidgetItem::QWidgetItem (QWidget * w) inline explicit
Creates an item containing the given widget.
Definition at line 127 of file qlayoutitem.h.
 : wid(w) { }
Functions
expandingDirections()
Qt::Orientations QWidgetItem::expandingDirections () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 603 of file qlayoutitem.cpp.
Referenced by QToolBarLayout::updateGeomArray().
 {
     if (isEmpty())
         return Qt::Orientations(0);
     Qt::Orientations e = wid->sizePolicy().expandingDirections();
     /*
       ### Qt 4.0:
       If the layout is expanding, we make the widget expanding, even if
       its own size policy isn't expanding. This behavior should be
       reconsidered.
     */
     if (wid->layout()) {
         if (wid->sizePolicy().horizontalPolicy() & QSizePolicy::GrowFlag
                 && (wid->layout()->expandingDirections() & Qt::Horizontal))
             e |= Qt::Horizontal;
         if (wid->sizePolicy().verticalPolicy() & QSizePolicy::GrowFlag
                 && (wid->layout()->expandingDirections() & Qt::Vertical))
             e |= Qt::Vertical;
     }
     if (align & Qt::AlignHorizontal_Mask)
         e &= ~Qt::Horizontal;
     if (align & Qt::AlignVertical_Mask)
         e &= ~Qt::Vertical;
     return e;
 }
geometry()
QRect QWidgetItem::geometry () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 542 of file qlayoutitem.cpp.
Referenced by QPushButtonPrivate::adjustedMenuPosition().
 {
     return !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect)
            ? toLayoutItemRect(wid->d_func(), wid->geometry())
            : wid->geometry();
 }
hasHeightForWidth()
bool QWidgetItem::hasHeightForWidth () const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 553 of file qlayoutitem.cpp.
 {
     if (isEmpty())
         return false;
     return wid->d_func()->hasHeightForWidth();
 }
heightForWidth()
int QWidgetItem::heightForWidth (int w) const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Reimplemented in QWidgetItemV2.
Definition at line 563 of file qlayoutitem.cpp.
Referenced by QWidgetItemV2::heightForWidth().
 {
     if (isEmpty())
         return -1;
     w = !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect)
       ? fromLayoutItemSize(wid->d_func(), QSize(w, 0)).width()
       : w;
     int hfw;
     if (wid->layout())
         hfw = wid->layout()->totalHeightForWidth(w);
     else
         hfw = wid->heightForWidth(w);
     if (hfw > wid->maximumHeight())
         hfw = wid->maximumHeight();
     if (hfw < wid->minimumHeight())
         hfw = wid->minimumHeight();
     hfw = !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect)
         ? toLayoutItemSize(wid->d_func(), QSize(0, hfw)).height()
         : hfw;
     if (hfw < 0)
         hfw = 0;
     return hfw;
 }
isEmpty()
bool QWidgetItem::isEmpty () const virtual
Returns true if the widget is hidden; otherwise returns false.
See also
QWidget::isHidden()
Implements QLayoutItem.
Reimplemented in QToolBarItem.
Definition at line 718 of file qlayoutitem.cpp.
Referenced by QWidgetItemV2::heightForWidth(), QWidgetItemV2::maximumSize(), QWidgetItemV2::minimumSize(), and QWidgetItemV2::sizeHint().
 {
     return wid->isHidden() || wid->isWindow();
 }
maximumSize()
QSize QWidgetItem::maximumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Reimplemented in QDockWidgetItem, and QWidgetItemV2.
Definition at line 664 of file qlayoutitem.cpp.
Referenced by QMainWindowLayout::fixSizeInUnifiedToolbar(), make_widget_eventUPP(), QWidgetItemV2::maximumSize(), and QToolBarLayout::updateGeomArray().
 {
     if (isEmpty()) {
         return QSize(0, 0);
     } else {
         return !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect)
                ? toLayoutItemSize(wid->d_func(), qSmartMaxSize(this, align))
                : qSmartMaxSize(this, align);
     }
 }
minimumSize()
QSize QWidgetItem::minimumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Reimplemented in QDockWidgetItem, and QWidgetItemV2.
Definition at line 643 of file qlayoutitem.cpp.
Referenced by QMainWindowLayout::fixSizeInUnifiedToolbar(), make_widget_eventUPP(), QWidgetItemV2::minimumSize(), and QToolBarLayout::updateGeomArray().
 {
     if (isEmpty())
         return QSize(0, 0);
     return !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect)
            ? toLayoutItemSize(wid->d_func(), qSmartMinSize(this))
            : qSmartMinSize(this);
 }
setGeometry()
void QWidgetItem::setGeometry (const QRect & rect) virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 474 of file qlayoutitem.cpp.
Referenced by QToolBarLayout::layoutActions().
 {
     if (isEmpty())
         return;
     QRect r = !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect)
             ? fromLayoutItemRect(wid->d_func(), rect)
             : rect;
     const QSize widgetRectSurplus = r.size() - rect.size();
     /*
        For historical reasons, this code is done using widget rect
        coordinates, not layout item rect coordinates. However,
        QWidgetItem's sizeHint(), maximumSize(), and heightForWidth()
        all work in terms of layout item rect coordinates, so we have to
        add or subtract widgetRectSurplus here and there. The code could
        be much simpler if we did everything using layout item rect
        coordinates and did the conversion right before the call to
        QWidget::setGeometry().
      */
     QSize s = r.size().boundedTo(maximumSize() + widgetRectSurplus);
     int x = r.x();
     int y = r.y();
     if (align & (Qt::AlignHorizontal_Mask | Qt::AlignVertical_Mask)) {
         QSize pref(sizeHint());
         QSizePolicy sp = wid->sizePolicy();
         if (sp.horizontalPolicy() == QSizePolicy::Ignored)
             pref.setWidth(wid->sizeHint().expandedTo(wid->minimumSize()).width());
         if (sp.verticalPolicy() == QSizePolicy::Ignored)
             pref.setHeight(wid->sizeHint().expandedTo(wid->minimumSize()).height());
         pref += widgetRectSurplus;
         if (align & Qt::AlignHorizontal_Mask)
             s.setWidth(qMin(s.width(), pref.width()));
         if (align & Qt::AlignVertical_Mask) {
             if (hasHeightForWidth())
                 s.setHeight(qMin(s.height(),
                                  heightForWidth(s.width() - widgetRectSurplus.width())
                                  + widgetRectSurplus.height()));
             else
                 s.setHeight(qMin(s.height(), pref.height()));
         }
     }
     Qt::Alignment alignHoriz = QStyle::visualAlignment(wid->layoutDirection(), align);
     if (alignHoriz & Qt::AlignRight)
         x = x + (r.width() - s.width());
     else if (!(alignHoriz & Qt::AlignLeft))
         x = x + (r.width() - s.width()) / 2;
     if (align & Qt::AlignBottom)
         y = y + (r.height() - s.height());
     else if (!(align & Qt::AlignTop))
         y = y + (r.height() - s.height()) / 2;
     wid->setGeometry(x, y, s.width(), s.height());
 }
sizeHint()
QSize QWidgetItem::sizeHint () const virtual
Reimplemented Function
Implements QLayoutItem.
Reimplemented in QDockWidgetItem, and QWidgetItemV2.
Definition at line 686 of file qlayoutitem.cpp.
Referenced by QToolBarLayout::expandedSize(), QToolBarLayout::layoutActions(), QWidgetItemV2::sizeHint(), QDockWidgetItem::sizeHint(), and QToolBarLayout::updateGeomArray().
 {
     QSize s(0, 0);
     if (!isEmpty()) {
         s = wid->sizeHint().expandedTo(wid->minimumSizeHint());
         s = s.boundedTo(wid->maximumSize())
              .expandedTo(wid->minimumSize());
         s = !wid->testAttribute(Qt::WA_LayoutUsesWidgetRect)
            ? toLayoutItemSize(wid->d_func(), s)
            : s;
         if (wid->sizePolicy().horizontalPolicy() == QSizePolicy::Ignored)
             s.setWidth(0);
         if (wid->sizePolicy().verticalPolicy() == QSizePolicy::Ignored)
             s.setHeight(0);
     }
     return s;
 }
widget()
QWidget * QWidgetItem::widget () virtual
Returns the widget managed by this item.
Reimplemented from QLayoutItem.
Definition at line 385 of file qlayoutitem.cpp.
Referenced by defaultWidgetAction(), QToolBarLayout::layoutActions(), QToolBarLayout::takeAt(), QToolBarLayout::updateGeomArray(), and QToolBarLayout::~QToolBarLayout().
 {
     return wid;
 }
Properties
wid
QWidget* QWidgetItem::wid protected
Definition at line 141 of file qlayoutitem.h.
Referenced by QWidgetItemV2::QWidgetItemV2(), QWidgetItemV2::~QWidgetItemV2(), and QWidgetPrivate::~QWidgetPrivate().
The documentation for this class was generated from the following files:
/src/gui/kernel/qlayoutitem.h
/src/gui/kernel/qlayoutitem.cpp