Qt 4.8: QBasicAtomicPointer< T > Class Template Reference
QBasicAtomicPointer< T > Class Template Reference
#include <qglobal.h>
Public Functions
T * fetchAndAddAcquire (qptrdiff valueToAdd)
T * fetchAndAddOrdered (qptrdiff valueToAdd)
T * fetchAndAddRelaxed (qptrdiff valueToAdd)
T * fetchAndAddRelease (qptrdiff valueToAdd)
T * fetchAndStoreAcquire (T *newValue)
T * fetchAndStoreOrdered (T *newValue)
T * fetchAndStoreRelaxed (T *newValue)
T * fetchAndStoreRelease (T *newValue)
operator T* () const
bool operator! () const
bool operator!= (T *value) const
T * operator-> () const
QBasicAtomicPointer< T > & operator= (T *value)
bool operator== (T *value) const
bool testAndSetAcquire (T *expectedValue, T *newValue)
bool testAndSetOrdered (T *expectedValue, T *newValue)
bool testAndSetRelaxed (T *expectedValue, T *newValue)
bool testAndSetRelease (T *expectedValue, T *newValue)
Static Public Functions
static bool isFetchAndAddNative ()
static bool isFetchAndAddWaitFree ()
static bool isFetchAndStoreNative ()
static bool isFetchAndStoreWaitFree ()
static bool isTestAndSetNative ()
static bool isTestAndSetWaitFree ()
Public Variables
T *volatile _q_value
Detailed Description
template<typename T>
class QBasicAtomicPointer< T >
Definition at line 1935 of file qglobal.h.
Functions
fetchAndAddAcquire()
template<typename T > Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndAddAcquire (qptrdiff valueToAdd)
Definition at line 592 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), connManager(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return reinterpret_cast<T *>(q_atomic_fetch_and_add_acquire_ptr(&_q_value, newValue));
 }
fetchAndAddOrdered()
template<typename T > Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndAddOrdered (qptrdiff valueToAdd)
Definition at line 633 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return fetchAndAddAcquire(valueToAdd);
 }
fetchAndAddRelaxed()
template<typename T > Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndAddRelaxed (qptrdiff valueToAdd)
Definition at line 587 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return reinterpret_cast<T *>(q_atomic_fetch_and_add_ptr(&_q_value, newValue));
 }
fetchAndAddRelease()
template<typename T > Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndAddRelease (qptrdiff valueToAdd)
Definition at line 598 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return reinterpret_cast<T *>(q_atomic_fetch_and_add_release_ptr(&_q_value, newValue));
 }
fetchAndStoreAcquire()
template<typename T> Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndStoreAcquire (T * newValue)
Definition at line 575 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), qt_atomic_tasb(), and qt_removeObject().
 {
     return reinterpret_cast<T *>(q_atomic_fetch_and_store_acquire_ptr(&_q_value, newValue));
 }
fetchAndStoreOrdered()
template<typename T> Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndStoreOrdered (T * newValue)
Definition at line 627 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return fetchAndStoreAcquire(newValue);
 }
fetchAndStoreRelaxed()
template<typename T> Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndStoreRelaxed (T * newValue)
Definition at line 569 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return reinterpret_cast<T *>(q_atomic_set_ptr(&_q_value, newValue));
 }
fetchAndStoreRelease()
template<typename T> Q_INLINE_TEMPLATE T * QBasicAtomicPointer< T >::fetchAndStoreRelease (T * newValue)
Definition at line 581 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), connManager(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return reinterpret_cast<T *>(q_atomic_fetch_and_store_release_ptr(&_q_value, newValue));
 }
isFetchAndAddNative()
template<typename T > Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::isFetchAndAddNative () static
Definition at line 98 of file qatomic_alpha.h.
Referenced by QBasicAtomicPointer< QBrushData >::operator=().
 { return true; }
isFetchAndAddWaitFree()
template<typename T > Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::isFetchAndAddWaitFree () static
Definition at line 101 of file qatomic_alpha.h.
Referenced by QBasicAtomicPointer< QBrushData >::operator=().
 { return false; }
isFetchAndStoreNative()
template<typename T > Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::isFetchAndStoreNative () static
Definition at line 89 of file qatomic_alpha.h.
Referenced by QBasicAtomicPointer< QBrushData >::operator=().
 { return true; }
isFetchAndStoreWaitFree()
template<typename T > Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::isFetchAndStoreWaitFree () static
Definition at line 92 of file qatomic_alpha.h.
Referenced by QBasicAtomicPointer< QBrushData >::operator=().
 { return false; }
isTestAndSetNative()
template<typename T > Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::isTestAndSetNative () static
Definition at line 80 of file qatomic_alpha.h.
Referenced by QBasicAtomicPointer< QBrushData >::operator=().
 { return true; }
isTestAndSetWaitFree()
template<typename T > Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::isTestAndSetWaitFree () static
Definition at line 83 of file qatomic_alpha.h.
Referenced by QBasicAtomicPointer< QBrushData >::operator=().
 { return false; }
operator T*()
template<typename T> QBasicAtomicPointer< T >::operator T* () const inline
Definition at line 167 of file qbasicatomic.h.
     {
         return _q_value;
     }
operator!()
template<typename T> bool QBasicAtomicPointer< T >::operator! () const inline
Definition at line 162 of file qbasicatomic.h.
     {
         return operator==(0);
     }
operator!=()
template<typename T> bool QBasicAtomicPointer< T >::operator!= (T * value) const inline
Definition at line 157 of file qbasicatomic.h.
     {
         return !operator==(value);
     }
operator->()
template<typename T> T* QBasicAtomicPointer< T >::operator-> () const inline
Definition at line 172 of file qbasicatomic.h.
     {
         return _q_value;
     }
operator=()
template<typename T> QBasicAtomicPointer<T>& QBasicAtomicPointer< T >::operator= (T * value) inline
Definition at line 177 of file qbasicatomic.h.
     {
 #ifdef QT_ARCH_PARISC
         this->_q_lock[0] = this->_q_lock[1] = this->_q_lock[2] = this->_q_lock[3] = -1;
 #endif
         _q_value = value;
         return *this;
     }
operator==()
template<typename T> bool QBasicAtomicPointer< T >::operator== (T * value) const inline
Definition at line 152 of file qbasicatomic.h.
Referenced by QBasicAtomicPointer< QBrushData >::operator!(), and QBasicAtomicPointer< QBrushData >::operator!=().
     {
         return _q_value == value;
     }
testAndSetAcquire()
template<typename T> Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::testAndSetAcquire (T * expectedValue, T * newValue)
Definition at line 557 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return q_atomic_test_and_set_acquire_ptr(&_q_value, expectedValue, newValue) != 0;
 }
testAndSetOrdered()
template<typename T> Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::testAndSetOrdered (T * expectedValue, T * newValue)
Definition at line 621 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::operator=(), qt_atomic_tasb(), queued_activate(), and signalSlotLock().
 {
     return testAndSetAcquire(expectedValue, newValue);
 }
testAndSetRelaxed()
template<typename T> Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::testAndSetRelaxed (T * expectedValue, T * newValue)
Definition at line 551 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return q_atomic_test_and_set_ptr(&_q_value, expectedValue, newValue) != 0;
 }
testAndSetRelease()
template<typename T> Q_INLINE_TEMPLATE bool QBasicAtomicPointer< T >::testAndSetRelease (T * expectedValue, T * newValue)
Definition at line 563 of file qatomic_alpha.h.
Referenced by _q_ia64_fetchadd_immediate(), QBasicAtomicPointer< QBrushData >::isFetchAndAddWaitFree(), QBasicAtomicPointer< QBrushData >::operator=(), and qt_atomic_tasb().
 {
     return q_atomic_test_and_set_release_ptr(&_q_value, expectedValue, newValue) != 0;
 }
Properties
_q_value
template<typename T> T* volatile QBasicAtomicPointer< T >::_q_value
Definition at line 148 of file qbasicatomic.h.
Referenced by QBasicAtomicPointer< T >::operator T*(), QBasicAtomicPointer< QBrushData >::operator->(), QBasicAtomicInt::operator=(), and QAtomicPointer< QtSharedPointer::ExternalRefCountData >::QAtomicPointer().
The documentation for this class was generated from the following files:
/src/corelib/global/qglobal.h
/src/corelib/thread/qbasicatomic.h
/src/corelib/arch/qatomic_alpha.h
/src/corelib/arch/qatomic_armv5.h
/src/corelib/arch/qatomic_armv6.h
/src/corelib/arch/qatomic_avr32.h
/src/corelib/arch/qatomic_bfin.h
/src/corelib/arch/qatomic_bootstrap.h
/src/corelib/arch/qatomic_generic.h
/src/corelib/arch/qatomic_i386.h
/src/corelib/arch/qatomic_ia64.h
/src/corelib/arch/qatomic_integrity.h
/src/corelib/arch/qatomic_m68k.h
/src/corelib/arch/qatomic_mips.h
/src/corelib/arch/qatomic_parisc.h
/src/corelib/arch/qatomic_powerpc.h
/src/corelib/arch/qatomic_s390.h
/src/corelib/arch/qatomic_sh.h
/src/corelib/arch/qatomic_sh4a.h
/src/corelib/arch/qatomic_sparc.h
/src/corelib/arch/qatomic_vxworks.h
/src/corelib/arch/qatomic_x86_64.h