Qt 4.8: QMultiMap< Key, T > Class Template Reference
QMultiMap< Key, T > Class Template Reference
The QMultiMap class is a convenience QMap subclass that provides multi-valued maps.
#include <qcontainerfwd.h>
Public Functions
QMap< Key, T >::const_iterator constFind (const Key &key, const T &value) const
Returns an iterator pointing to the item with key key and the value value in the map.
bool contains (const Key &key, const T &value) const
Returns true if the map contains an item with key key and value value; otherwise returns false.
int count (const Key &key, const T &value) const
Returns the number of items with key key and value value.
QMap< Key, T >::iterator find (const Key &key, const T &value)
Returns an iterator pointing to the item with key key and value value in the map.
QMap< Key, T >::const_iterator find (const Key &key, const T &value) const
Returns a const iterator pointing to the item with the given key and value in the map.
QMap< Key, T >::iterator insert (const Key &key, const T &value)
Inserts a new item with the key key and a value of value.
QMultiMap operator+ (const QMultiMap &other) const
Returns a map that contains all the items in this map in addition to all the items in other.
QMultiMap & operator+= (const QMultiMap &other)
Inserts all the items in the other map into this map and returns a reference to this map.
QMultiMap ()
Constructs an empty map.
QMultiMap (const QMap< Key, T > &other)
Constructs a copy of other (which can be a QMap or a QMultiMap).
int remove (const Key &key, const T &value)
Removes all the items that have the key key and the value value from the map.
QMap< Key, T >::iterator replace (const Key &key, const T &value)
Inserts a new item with the key key and a value of value.
void swap (QMultiMap< Key, T > &other)
Swaps map other with this map.
Public Functions inherited from QMap< Key, T >
iterator begin ()
Returns an STL-style iterator pointing to the first item in the map.
const_iterator begin () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void clear ()
Removes all items from the map.
const_iterator constBegin () const
Returns a const STL-style iterator pointing to the first item in the map.
const_iterator constEnd () const
Returns a const STL-style iterator pointing to the imaginary item after the last item in the map.
const_iterator constFind (const Key &key) const
Returns an const iterator pointing to the item with key key in the map.
bool contains (const Key &key) const
Returns true if the map contains an item with key key; otherwise returns false.
int count (const Key &key) const
Returns the number of items associated with key key.
int count () const
Same as size().
void detach ()
Detaches this map from any other maps with which it may share data.
bool empty () const
This function is provided for STL compatibility.
iterator end ()
Returns an STL-style iterator pointing to the imaginary item after the last item in the map.
const_iterator end () const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator erase (iterator it)
Removes the (key, value) pair pointed to by the iterator pos from the map, and returns an iterator to the next item in the map.
iterator find (const Key &key)
Returns an iterator pointing to the item with key key in the map.
const_iterator find (const Key &key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
iterator insert (const Key &key, const T &value)
Inserts a new item with the key key and a value of value.
iterator insertMulti (const Key &key, const T &value)
Inserts a new item with the key key and a value of value.
bool isDetached () const
Returns true if the map's internal data isn't shared with any other map object; otherwise returns false.
bool isEmpty () const
Returns true if the map contains no items; otherwise returns false.
bool isSharedWith (const QMap< Key, T > &other) const
const Key key (const T &value) const
Returns the first key with value value.
const Key key (const T &value, const Key &defaultKey) const
Returns the first key with value value, or defaultKey if the map contains no item with value value.
QList< Key > keys () const
Returns a list containing all the keys in the map in ascending order.
QList< Key > keys (const T &value) const
Returns a list containing all the keys associated with value value in ascending order.
iterator lowerBound (const Key &key)
Returns an iterator pointing to the first item with key key in the map.
const_iterator lowerBound (const Key &key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
bool operator!= (const QMap< Key, T > &other) const
Returns true if other is not equal to this map; otherwise returns false.
QMap< Key, T > & operator= (const QMap< Key, T > &other)
Assigns other to this map and returns a reference to this map.
bool operator== (const QMap< Key, T > &other) const
Returns true if other is equal to this map; otherwise returns false.
T & operator[] (const Key &key)
Returns the value associated with the key key as a modifiable reference.
const T operator[] (const Key &key) const
Same as value().
QMap ()
Constructs an empty map.
QMap (const QMap< Key, T > &other)
Constructs a copy of other.
QMap (const typename std::map< Key, T > &other)
int remove (const Key &key)
Removes all the items that have the key key from the map.
void setInsertInOrder (bool ordered)
void setSharable (bool sharable)
int size () const
Returns the number of (key, value) pairs in the map.
void swap (QMap< Key, T > &other)
Swaps map other with this map.
T take (const Key &key)
Removes the item with the key key from the map and returns the value associated with it.
std::map< Key, T > toStdMap () const
Returns an STL map equivalent to this QMap.
QList< Key > uniqueKeys () const
Returns a list containing all the keys in the map in ascending order.
QMap< Key, T > & unite (const QMap< Key, T > &other)
Inserts all the items in the other map into this map.
iterator upperBound (const Key &key)
Returns an iterator pointing to the item that immediately follows the last item with key key in the map.
const_iterator upperBound (const Key &key) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
const T value (const Key &key) const
Returns the value associated with the key key.
const T value (const Key &key, const T &defaultValue) const
If the map contains no item with key key, the function returns defaultValue.
QList< T > values () const
Returns a list containing all the values in the map, in ascending order of their keys.
QList< T > values (const Key &key) const
Returns a list containing all the values associated with key key, from the most recently inserted to the least recently inserted one.
~QMap ()
Destroys the map.
Private Functions
T & operator[] (const Key &key)
const T operator[] (const Key &key) const
Additional Inherited Members
Public Types inherited from QMap< Key, T >
typedef const_iterator ConstIterator
Qt-style synonym for QMap::const_iterator.
typedef qptrdiff difference_type
Typedef for ptrdiff_t.
typedef iterator Iterator
Qt-style synonym for QMap::iterator.
typedef Key key_type
Typedef for Key.
typedef T mapped_type
Typedef for T.
typedef int size_type
Typedef for int.
Related Functions inherited from QMap< Key, T >
QDataStream & operator<< (QDataStream &out, const QMap< Key, T > &map)
Writes the map map to stream out.
QDataStream & operator>> (QDataStream &in, QMap< Key, T > &map)
Reads a map from stream in into map.
Detailed Description
template<class Key, class T>
class QMultiMap< Key, T >
The QMultiMap class is a convenience QMap subclass that provides multi-valued maps.
Note
This class or function is reentrant.
QMultiMap<Key, T> is one of Qt's generic container classes. It inherits QMap and extends it with a few convenience functions that make it more suitable than QMap for storing multi-valued maps. A multi-valued map is a map that allows multiple values with the same key; QMap normally doesn't allow that, unless you call QMap::insertMulti().
Because QMultiMap inherits QMap, all of QMap's functionality also applies to QMultiMap. For example, you can use isEmpty() to test whether the map is empty, and you can traverse a QMultiMap using QMap's iterator classes (for example, QMapIterator). But in addition, it provides an insert() function that corresponds to QMap::insertMulti(), and a replace() function that corresponds to QMap::insert(). It also provides convenient operator+() and operator+=().
Example:
QMultiMap<QString, int> map1, map2, map3;
map1.insert("plenty", 100);
map1.insert("plenty", 2000);
// map1.size() == 2
map2.insert("plenty", 5000);
// map2.size() == 1
map3 = map1 + map2;
// map3.size() == 3
Unlike QMap, QMultiMap provides no operator[]. Use value() or replace() if you want to access the most recently inserted item with a certain key.
If you want to retrieve all the values for a single key, you can use values(const Key &key), which returns a QList<T>:
QList<int> values = map.values("plenty");
for (int i = 0; i < values.size(); ++i)
    cout << values.at(i) << endl;
The items that share the same key are available from most recently to least recently inserted.
If you prefer the STL-style iterators, you can call find() to get the iterator for the first item with a key and iterate from there:
QMultiMap<QString, int>::iterator i = map.find("plenty");
while (i != map.end() && i.key() == "plenty") {
    cout << i.value() << endl;
    ++i;
}
QMultiMap's key and value data types must be assignable data types. This covers most data types you are likely to encounter, but the compiler won't let you, for example, store a QWidget as a value; instead, store a QWidget *. In addition, QMultiMap's key type must provide operator<(). See the QMap documentation for details.
See also
QMap, QMapIterator, QMutableMapIterator, QMultiHash
Definition at line 59 of file qcontainerfwd.h.
Constructors and Destructors
QMultiMap() [1/2]
template<class Key, class T> QMultiMap< Key, T >::QMultiMap () inline
Constructs an empty map.
Definition at line 976 of file qmap.h.
 {}
QMultiMap() [2/2]
template<class Key, class T> QMultiMap< Key, T >::QMultiMap (const QMap< Key, T > & other) inline
Constructs a copy of other (which can be a QMap or a QMultiMap).
See also
operator=()
Definition at line 977 of file qmap.h.
 : QMap<Key, T>(other) {}
Functions
constFind()
template<class Key, class T> typename QMap< Key, T >::const_iterator QMultiMap< Key, T >::constFind (const Key & key, const T & value) const inline
Returns an iterator pointing to the item with key key and the value value in the map.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
If the map contains no such item, the function returns constEnd().
See also
QMap::constFind()
QMap::constFind()
Definition at line 1040 of file qmap.h.
         { return find(key, value); }
contains()
template<class Key, class T> Q_INLINE_TEMPLATE bool QMultiMap< Key, T >::contains (const Key & key, const T & value) const
Returns true if the map contains an item with key key and value value; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
See also
QMap::contains()
QMap::contains()
Definition at line 1048 of file qmap.h.
Referenced by QGraphicsScenePrivate::filterEvent(), and QGraphicsScenePrivate::removeSceneEventFilter().
 {
     return constFind(key, value) != QMap<Key, T>::constEnd();
 }
count()
template<class Key, class T> Q_INLINE_TEMPLATE int QMultiMap< Key, T >::count (const Key & key, const T & value) const
Returns the number of items with key key and value value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
See also
QMap::count()
QMap::count()
Definition at line 1071 of file qmap.h.
Referenced by QNetworkDiskCache::expire().
 {
     int n = 0;
     typename QMap<Key, T>::const_iterator i(constFind(key));
     typename QMap<Key, T>::const_iterator end(QMap<Key, T>::constEnd());
     while (i != end && !qMapLessThanKey<Key>(key, i.key())) {
         if (i.value() == value)
             ++n;
         ++i;
     }
     return n;
 }
find() [1/2]
template<class Key, class T> typename QMap< Key, T >::iterator QMultiMap< Key, T >::find (const Key & key, const T & value) inline
Returns an iterator pointing to the item with key key and value value in the map.
Since
4.3
If the map contains no such item, the function returns end().
If the map contains multiple items with key key, this function returns an iterator that points to the most recently inserted value.
See also
QMap::find()
Definition at line 1020 of file qmap.h.
{
         typename QMap<Key, T>::iterator i(find(key));
         typename QMap<Key, T>::iterator end(this->end());
         while (i != end && !qMapLessThanKey<Key>(key, i.key())) {
             if (i.value() == value)
                 return i;
             ++i;
         }
         return end;
     }
find() [2/2]
template<class Key, class T> typename QMap< Key, T >::const_iterator QMultiMap< Key, T >::find (const Key & key, const T & value) const inline
Returns a const iterator pointing to the item with the given key and value in the map.
Since
4.3 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the map contains no such item, the function returns end().
If the map contains multiple items with the specified key, this function returns a const iterator that points to the most recently inserted value.
See also
QMap::find()
Definition at line 1030 of file qmap.h.
{
         typename QMap<Key, T>::const_iterator i(constFind(key));
         typename QMap<Key, T>::const_iterator end(QMap<Key, T>::constEnd());
         while (i != end && !qMapLessThanKey<Key>(key, i.key())) {
             if (i.value() == value)
                 return i;
             ++i;
         }
         return end;
     }
insert()
template<class Key, class T> QMultiMap::iterator QMultiMap< Key, T >::insert (const Key & key, const T & value) inline
Inserts a new item with the key key and a value of value.
If there is already an item with the same key in the map, this function will simply create a new one. (This behavior is different from replace(), which overwrites the value of an existing item.)
See also
replace()
Definition at line 982 of file qmap.h.
Referenced by QSslCertificate::alternateSubjectNames(), QNetworkDiskCache::expire(), QGestureManager::filterEvent(), QGraphicsScenePrivate::installSceneEventFilter(), and QDBusXmlParser::interfaces().
     { return QMap<Key, T>::insertMulti(key, value); }
operator+()
template<class Key, class T> QMultiMap QMultiMap< Key, T >::operator+ (const QMultiMap< Key, T > & other) const inline
Returns a map that contains all the items in this map in addition to all the items in other.
If a key is common to both maps, the resulting map will contain the key multiple times.
See also
operator+=()
Definition at line 987 of file qmap.h.
     { QMultiMap result = *this; result += other; return result; }
operator+=()
template<class Key, class T> QMultiMap & QMultiMap< Key, T >::operator+= (const QMultiMap< Key, T > & other) inline
Inserts all the items in the other map into this map and returns a reference to this map.
See also
insert(), operator+()
Definition at line 985 of file qmap.h.
     { this->unite(other); return *this; }
operator[]() [1/2]
template<class Key, class T> T& QMultiMap< Key, T >::operator[] (const Key & key) private
operator[]() [2/2]
template<class Key, class T> const T QMultiMap< Key, T >::operator[] (const Key & key) const private
remove()
template<class Key, class T> Q_INLINE_TEMPLATE int QMultiMap< Key, T >::remove (const Key & key, const T & value)
Removes all the items that have the key key and the value value from the map.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
Returns the number of items removed.
See also
QMap::remove()
QMap::remove()
Definition at line 1054 of file qmap.h.
 {
     int n = 0;
     typename QMap<Key, T>::iterator i(find(key));
     typename QMap<Key, T>::iterator end(QMap<Key, T>::end());
     while (i != end && !qMapLessThanKey<Key>(key, i.key())) {
         if (i.value() == value) {
             i = this->erase(i);
             ++n;
         } else {
             ++i;
         }
     }
     return n;
 }
replace()
template<class Key, class T> QMultiMap::iterator QMultiMap< Key, T >::replace (const Key & key, const T & value) inline
Inserts a new item with the key key and a value of value.
If there is already an item with the key key, that item's value is replaced with value.
If there are multiple items with the key key, the most recently inserted item's value is replaced with value.
See also
insert()
Definition at line 980 of file qmap.h.
     { return QMap<Key, T>::insert(key, value); }
swap()
template<class Key, class T> void QMultiMap< Key, T >::swap (QMultiMap< Key, T > & other) inline
Swaps map other with this map.
Since
4.8
This operation is very fast and never fails.
Definition at line 978 of file qmap.h.
 { QMap<Key, T>::swap(other); }
The documentation for this class was generated from the following files:
/src/corelib/tools/qcontainerfwd.h
/src/corelib/tools/qmap.h
/src/corelib/tools/qmap.cpp