Qt 4.8: QHttpSocketEngine Class Reference
QHttpSocketEngine Class Reference
#include <qhttpsocketengine_p.h>
Public Types
enum HttpState {
None, ConnectSent, Connected, SendAuthentication,
ReadResponseContent
}
Public Types inherited from QAbstractSocketEngine
enum SocketOption {
NonBlockingSocketOption, BroadcastSocketOption, ReceiveBufferSocketOption, SendBufferSocketOption,
AddressReusable, BindExclusively, ReceiveOutOfBandData, LowDelayOption,
KeepAliveOption, MulticastTtlOption, MulticastLoopbackOption
}
Public Slots
void slotSocketBytesWritten ()
void slotSocketConnected ()
void slotSocketDisconnected ()
void slotSocketError (QAbstractSocket::SocketError error)
void slotSocketReadNotification ()
void slotSocketStateChanged (QAbstractSocket::SocketState state)
Public Slots inherited from QAbstractSocketEngine
void connectionNotification ()
void exceptionNotification ()
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
void readNotification ()
void writeNotification ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
int accept ()
bool bind (const QHostAddress &address, quint16 port)
qint64 bytesAvailable () const
qint64 bytesToWrite () const
void close ()
bool connectInternal ()
bool connectToHost (const QHostAddress &address, quint16 port)
bool connectToHostByName (const QString &name, quint16 port)
bool hasPendingDatagrams () const
bool initialize (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol=QAbstractSocket::IPv4Protocol)
bool initialize (int socketDescriptor, QAbstractSocket::SocketState socketState=QAbstractSocket::ConnectedState)
bool isExceptionNotificationEnabled () const
bool isReadNotificationEnabled () const
bool isValid () const
bool isWriteNotificationEnabled () const
bool joinMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &interface)
bool leaveMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &interface)
bool listen ()
QNetworkInterface multicastInterface () const
int option (SocketOption option) const
qint64 pendingDatagramSize () const
QHttpSocketEngine (QObject *parent=0)
qint64 read (char *data, qint64 maxlen)
qint64 readDatagram (char *data, qint64 maxlen, QHostAddress *addr=0, quint16 *port=0)
void setExceptionNotificationEnabled (bool enable)
bool setMulticastInterface (const QNetworkInterface &iface)
bool setOption (SocketOption option, int value)
void setProxy (const QNetworkProxy &networkProxy)
void setReadNotificationEnabled (bool enable)
void setWriteNotificationEnabled (bool enable)
int socketDescriptor () const
bool waitForRead (int msecs=30000, bool *timedOut=0)
bool waitForReadOrWrite (bool *readyToRead, bool *readyToWrite, bool checkRead, bool checkWrite, int msecs=30000, bool *timedOut=0)
bool waitForWrite (int msecs=30000, bool *timedOut=0)
qint64 write (const char *data, qint64 len)
qint64 writeDatagram (const char *data, qint64 len, const QHostAddress &addr, quint16 port)
~QHttpSocketEngine ()
Public Functions inherited from QAbstractSocketEngine
QAbstractSocket::SocketError error () const
QString errorString () const
QHostAddress localAddress () const
quint16 localPort () const
QHostAddress peerAddress () const
quint16 peerPort () const
QAbstractSocket::NetworkLayerProtocol protocol () const
QAbstractSocketEngine (QObject *parent=0)
void setReceiver (QAbstractSocketEngineReceiver *receiver)
QAbstractSocket::SocketType socketType () const
QAbstractSocket::SocketState state () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void emitPendingConnectionNotification ()
void emitPendingReadNotification ()
void emitPendingWriteNotification ()
Private Functions
void emitConnectionNotification ()
void emitReadNotification ()
void emitWriteNotification ()
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QAbstractSocketEngine
static QAbstractSocketEngine * createSocketEngine (QAbstractSocket::SocketType socketType, const QNetworkProxy &, QObject *parent)
static QAbstractSocketEngine * createSocketEngine (int socketDescripter, QObject *parent)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QAbstractSocketEngine
QAbstractSocketEngine (QAbstractSocketEnginePrivate &dd, QObject *parent=0)
void setError (QAbstractSocket::SocketError error, const QString &errorString) const
void setLocalAddress (const QHostAddress &address)
void setLocalPort (quint16 port)
void setPeerAddress (const QHostAddress &address)
void setPeerPort (quint16 port)
void setProtocol (QAbstractSocket::NetworkLayerProtocol protocol)
void setSocketType (QAbstractSocket::SocketType socketType)
void setState (QAbstractSocket::SocketState state)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 68 of file qhttpsocketengine_p.h.
Enumerations
HttpState
enum QHttpSocketEngine::HttpState
Enumerator
None
ConnectSent
Connected
SendAuthentication
ReadResponseContent
Definition at line 72 of file qhttpsocketengine_p.h.
                    {
         None,
         ConnectSent,
         Connected,
         SendAuthentication,
         ReadResponseContent
     };
Constructors and Destructors
QHttpSocketEngine()
QHttpSocketEngine::QHttpSocketEngine (QObject * parent = 0)
Definition at line 57 of file qhttpsocketengine.cpp.
     : QAbstractSocketEngine(*new QHttpSocketEnginePrivate, parent)
 {
 }
~QHttpSocketEngine()
QHttpSocketEngine::~QHttpSocketEngine ()
Definition at line 62 of file qhttpsocketengine.cpp.
 {
 }
Functions
accept()
int QHttpSocketEngine::accept () virtual
Implements QAbstractSocketEngine.
Definition at line 199 of file qhttpsocketengine.cpp.
 {
     return 0;
 }
bind()
bool QHttpSocketEngine::bind (const QHostAddress & address, quint16 port) virtual
Implements QAbstractSocketEngine.
Definition at line 189 of file qhttpsocketengine.cpp.
 {
     return false;
 }
bytesAvailable()
qint64 QHttpSocketEngine::bytesAvailable () const virtual
Implements QAbstractSocketEngine.
Definition at line 214 of file qhttpsocketengine.cpp.
Referenced by connectInternal(), and setReadNotificationEnabled().
 {
     Q_D(const QHttpSocketEngine);
     return d->readBuffer.size() + (d->socket ? d->socket->bytesAvailable() : 0);
 }
bytesToWrite()
qint64 QHttpSocketEngine::bytesToWrite () const virtual
Implements QAbstractSocketEngine.
Definition at line 303 of file qhttpsocketengine.cpp.
 {
     Q_D(const QHttpSocketEngine);
     if (d->socket) {
         return d->socket->bytesToWrite();
     } else {
         return 0;
     }
 }
close()
void QHttpSocketEngine::close () virtual
Implements QAbstractSocketEngine.
Definition at line 204 of file qhttpsocketengine.cpp.
Referenced by read().
 {
     Q_D(QHttpSocketEngine);
     if (d->socket) {
         d->socket->close();
         delete d->socket;
         d->socket = 0;
     }
 }
connectInternal()
bool QHttpSocketEngine::connectInternal ()
Definition at line 135 of file qhttpsocketengine.cpp.
Referenced by connectToHost(), and connectToHostByName().
 {
     Q_D(QHttpSocketEngine);
     d->credentialsSent = false;
     // If the handshake is done, enter ConnectedState state and return true.
     if (d->state == Connected) {
         qWarning("QHttpSocketEngine::connectToHost: called when already connected");
         setState(QAbstractSocket::ConnectedState);
         return true;
     }
     if (d->state == ConnectSent && d->socketState != QAbstractSocket::ConnectedState)
         setState(QAbstractSocket::UnconnectedState);
     // Handshake isn't done. If unconnected, start connecting.
     if (d->state == None && d->socket->state() == QAbstractSocket::UnconnectedState) {
         setState(QAbstractSocket::ConnectingState);
         //limit buffer in internal socket, data is buffered in the external socket under application control
         d->socket->setReadBufferSize(65536);
         d->socket->connectToHost(d->proxy.hostName(), d->proxy.port());
     }
     // If connected (might happen right away, at least for localhost services
     // on some BSD systems), there might already be bytes available.
     if (bytesAvailable())
         slotSocketReadNotification();
     return d->socketState == QAbstractSocket::ConnectedState;
 }
connectToHost()
bool QHttpSocketEngine::connectToHost (const QHostAddress & address, quint16 port) virtual
Implements QAbstractSocketEngine.
Definition at line 167 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     setPeerAddress(address);
     setPeerPort(port);
     d->peerName.clear();
     return connectInternal();
 }
connectToHostByName()
bool QHttpSocketEngine::connectToHostByName (const QString & name, quint16 port) virtual
Implements QAbstractSocketEngine.
Definition at line 178 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     setPeerAddress(QHostAddress());
     setPeerPort(port);
     d->peerName = hostname;
     return connectInternal();
 }
emitConnectionNotification()
void QHttpSocketEngine::emitConnectionNotification () private
Definition at line 795 of file qhttpsocketengine.cpp.
Referenced by slotSocketError(), and slotSocketReadNotification().
 {
     Q_D(QHttpSocketEngine);
     if (!d->connectionNotificationPending) {
         d->connectionNotificationPending = true;
         QMetaObject::invokeMethod(this, "emitPendingConnectionNotification", Qt::QueuedConnection);
     }
 }
emitPendingConnectionNotification
void QHttpSocketEngine::emitPendingConnectionNotification () private slot
Definition at line 765 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     d->connectionNotificationPending = false;
     emit connectionNotification();
 }
emitPendingReadNotification
void QHttpSocketEngine::emitPendingReadNotification () private slot
Definition at line 749 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     d->readNotificationPending = false;
     if (d->readNotificationEnabled)
         emit readNotification();
 }
emitPendingWriteNotification
void QHttpSocketEngine::emitPendingWriteNotification () private slot
Definition at line 757 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     d->writeNotificationPending = false;
     if (d->writeNotificationEnabled)
         emit writeNotification();
 }
emitReadNotification()
void QHttpSocketEngine::emitReadNotification () private
Definition at line 772 of file qhttpsocketengine.cpp.
Referenced by read(), slotSocketError(), and slotSocketReadNotification().
 {
     Q_D(QHttpSocketEngine);
     d->readNotificationActivated = true;
     // if there is a connection notification pending we have to emit the readNotification
     // incase there is connection error. This is only needed for Windows, but it does not
     // hurt in other cases.
     if ((d->readNotificationEnabled && !d->readNotificationPending) || d->connectionNotificationPending) {
         d->readNotificationPending = true;
         QMetaObject::invokeMethod(this, "emitPendingReadNotification", Qt::QueuedConnection);
     }
 }
emitWriteNotification()
void QHttpSocketEngine::emitWriteNotification () private
Definition at line 785 of file qhttpsocketengine.cpp.
Referenced by slotSocketBytesWritten(), and slotSocketReadNotification().
 {
     Q_D(QHttpSocketEngine);
     d->writeNotificationActivated = true;
     if (d->writeNotificationEnabled && !d->writeNotificationPending) {
         d->writeNotificationPending = true;
         QMetaObject::invokeMethod(this, "emitPendingWriteNotification", Qt::QueuedConnection);
     }
 }
hasPendingDatagrams()
bool QHttpSocketEngine::hasPendingDatagrams () const virtual
Implements QAbstractSocketEngine.
Definition at line 292 of file qhttpsocketengine.cpp.
 {
     return false;
 }
initialize() [1/2]
bool QHttpSocketEngine::initialize (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol = QAbstractSocket::IPv4Protocol) virtual
Implements QAbstractSocketEngine.
Definition at line 66 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     if (type != QAbstractSocket::TcpSocket)
         return false;
     setProtocol(protocol);
     setSocketType(type);
     d->socket = new QTcpSocket(this);
 #ifndef QT_NO_BEARERMANAGEMENT
     d->socket->setProperty("_q_networkSession", property("_q_networkSession"));
 #endif
     // Explicitly disable proxying on the proxy socket itself to avoid
     // unwanted recursion.
     d->socket->setProxy(QNetworkProxy::NoProxy);
     // Intercept all the signals.
     connect(d->socket, SIGNAL(connected()),
             this, SLOT(slotSocketConnected()),
             Qt::DirectConnection);
     connect(d->socket, SIGNAL(disconnected()),
             this, SLOT(slotSocketDisconnected()),
             Qt::DirectConnection);
     connect(d->socket, SIGNAL(readyRead()),
             this, SLOT(slotSocketReadNotification()),
             Qt::DirectConnection);
     connect(d->socket, SIGNAL(bytesWritten(qint64)),
             this, SLOT(slotSocketBytesWritten()),
             Qt::DirectConnection);
     connect(d->socket, SIGNAL(error(QAbstractSocket::SocketError)),
             this, SLOT(slotSocketError(QAbstractSocket::SocketError)),
             Qt::DirectConnection);
     connect(d->socket, SIGNAL(stateChanged(QAbstractSocket::SocketState)),
             this, SLOT(slotSocketStateChanged(QAbstractSocket::SocketState)),
             Qt::DirectConnection);
     return true;
 }
initialize() [2/2]
bool QHttpSocketEngine::initialize (int socketDescriptor, QAbstractSocket::SocketState socketState = QAbstractSocket::ConnectedState) virtual
Implements QAbstractSocketEngine.
Definition at line 106 of file qhttpsocketengine.cpp.
 {
     return false;
 }
isExceptionNotificationEnabled()
bool QHttpSocketEngine::isExceptionNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 482 of file qhttpsocketengine.cpp.
 {
     Q_D(const QHttpSocketEngine);
     return d->exceptNotificationEnabled;
 }
isReadNotificationEnabled()
bool QHttpSocketEngine::isReadNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 448 of file qhttpsocketengine.cpp.
 {
     Q_D(const QHttpSocketEngine);
     return d->readNotificationEnabled;
 }
isValid()
bool QHttpSocketEngine::isValid () const virtual
Implements QAbstractSocketEngine.
Definition at line 129 of file qhttpsocketengine.cpp.
 {
     Q_D(const QHttpSocketEngine);
     return d->socket;
 }
isWriteNotificationEnabled()
bool QHttpSocketEngine::isWriteNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 468 of file qhttpsocketengine.cpp.
 {
     Q_D(const QHttpSocketEngine);
     return d->writeNotificationEnabled;
 }
joinMulticastGroup()
bool QHttpSocketEngine::joinMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & interface) virtual
Implements QAbstractSocketEngine.
Definition at line 251 of file qhttpsocketengine.cpp.
 {
     setError(QAbstractSocket::UnsupportedSocketOperationError,
              QLatin1String("Operation on socket is not supported"));
     return false;
 }
leaveMulticastGroup()
bool QHttpSocketEngine::leaveMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & interface) virtual
Implements QAbstractSocketEngine.
Definition at line 259 of file qhttpsocketengine.cpp.
 {
     setError(QAbstractSocket::UnsupportedSocketOperationError,
              QLatin1String("Operation on socket is not supported"));
     return false;
 }
listen()
bool QHttpSocketEngine::listen () virtual
Implements QAbstractSocketEngine.
Definition at line 194 of file qhttpsocketengine.cpp.
 {
     return false;
 }
multicastInterface()
QNetworkInterface QHttpSocketEngine::multicastInterface () const virtual
Implements QAbstractSocketEngine.
Definition at line 267 of file qhttpsocketengine.cpp.
 {
     return QNetworkInterface();
 }
option()
int QHttpSocketEngine::option (SocketOption option) const virtual
Implements QAbstractSocketEngine.
Definition at line 313 of file qhttpsocketengine.cpp.
 {
     Q_D(const QHttpSocketEngine);
     if (d->socket) {
         // convert the enum and call the real socket
         if (option == QAbstractSocketEngine::LowDelayOption)
             return d->socket->socketOption(QAbstractSocket::LowDelayOption).toInt();
         if (option == QAbstractSocketEngine::KeepAliveOption)
             return d->socket->socketOption(QAbstractSocket::KeepAliveOption).toInt();
     }
     return -1;
 }
pendingDatagramSize()
qint64 QHttpSocketEngine::pendingDatagramSize () const virtual
Implements QAbstractSocketEngine.
Definition at line 297 of file qhttpsocketengine.cpp.
 {
     return 0;
 }
read()
qint64 QHttpSocketEngine::read (char * data, qint64 maxlen) virtual
Implements QAbstractSocketEngine.
Definition at line 220 of file qhttpsocketengine.cpp.
Referenced by slotSocketReadNotification().
 {
     Q_D(QHttpSocketEngine);
     qint64 bytesRead = d->socket->read(data, maxlen);
     if (d->socket->state() == QAbstractSocket::UnconnectedState
         && d->socket->bytesAvailable() == 0) {
         emitReadNotification();
     }
     if (bytesRead == -1) {
         // If nothing has been read so far, and the direct socket read
         // failed, return the socket's error. Otherwise, fall through and
         // return as much as we read so far.
         close();
         setError(QAbstractSocket::RemoteHostClosedError,
                  QLatin1String("Remote host closed"));
         setState(QAbstractSocket::UnconnectedState);
         return -1;
     }
     return bytesRead;
 }
readDatagram()
qint64 QHttpSocketEngine::readDatagram (char * data, qint64 maxlen, QHostAddress * addr = 0, quint16 * port = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 280 of file qhttpsocketengine.cpp.
 {
     return 0;
 }
setExceptionNotificationEnabled()
void QHttpSocketEngine::setExceptionNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 488 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     d->exceptNotificationEnabled = enable;
 }
setMulticastInterface()
bool QHttpSocketEngine::setMulticastInterface (const QNetworkInterface & iface) virtual
Implements QAbstractSocketEngine.
Definition at line 272 of file qhttpsocketengine.cpp.
 {
     setError(QAbstractSocket::UnsupportedSocketOperationError,
              QLatin1String("Operation on socket is not supported"));
     return false;
 }
setOption()
bool QHttpSocketEngine::setOption (SocketOption option, int value) virtual
Implements QAbstractSocketEngine.
Definition at line 326 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     if (d->socket) {
         // convert the enum and call the real socket
         if (option == QAbstractSocketEngine::LowDelayOption)
             d->socket->setSocketOption(QAbstractSocket::LowDelayOption, value);
         if (option == QAbstractSocketEngine::KeepAliveOption)
             d->socket->setSocketOption(QAbstractSocket::KeepAliveOption, value);
         return true;
     }
     return false;
 }
setProxy()
void QHttpSocketEngine::setProxy (const QNetworkProxy & networkProxy)
Definition at line 111 of file qhttpsocketengine.cpp.
Referenced by QHttpSocketEngineHandler::createSocketEngine().
 {
     Q_D(QHttpSocketEngine);
     d->proxy = proxy;
     QString user = proxy.user();
     if (!user.isEmpty())
         d->authenticator.setUser(user);
     QString password = proxy.password();
     if (!password.isEmpty())
         d->authenticator.setPassword(password);
 }
setReadNotificationEnabled()
void QHttpSocketEngine::setReadNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 454 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     if (d->readNotificationEnabled == enable)
         return;
     d->readNotificationEnabled = enable;
     if (enable) {
         // Enabling read notification can trigger a notification.
         if (bytesAvailable())
             slotSocketReadNotification();
     }
 }
setWriteNotificationEnabled()
void QHttpSocketEngine::setWriteNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 474 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     d->writeNotificationEnabled = enable;
     if (enable && d->state == Connected && d->socket->state() == QAbstractSocket::ConnectedState)
         QMetaObject::invokeMethod(this, "writeNotification", Qt::QueuedConnection);
 }
slotSocketBytesWritten
void QHttpSocketEngine::slotSocketBytesWritten () slot
Definition at line 704 of file qhttpsocketengine.cpp.
Referenced by initialize().
 {
     Q_D(QHttpSocketEngine);
     if (d->state == Connected && d->writeNotificationEnabled)
         emitWriteNotification();
 }
slotSocketConnected
void QHttpSocketEngine::slotSocketConnected () slot
Definition at line 494 of file qhttpsocketengine.cpp.
Referenced by initialize(), and slotSocketReadNotification().
 {
     Q_D(QHttpSocketEngine);
     // Send the greeting.
     const char method[] = "CONNECT";
     QByteArray peerAddress = d->peerName.isEmpty() ?
                              d->peerAddress.toString().toLatin1() :
                              QUrl::toAce(d->peerName);
     QByteArray path = peerAddress + ':' + QByteArray::number(d->peerPort);
     QByteArray data = method;
     data += " ";
     data += path;
     data += " HTTP/1.1\r\n";
     data += "Proxy-Connection: keep-alive\r\n"
             "User-Agent: ";
     QVariant v = property("_q_user-agent");
     if (v.isValid())
         data += v.toByteArray();
     else
         data += "Mozilla/5.0";
     data += "\r\n"
             "Host: " + peerAddress + "\r\n";
     QAuthenticatorPrivate *priv = QAuthenticatorPrivate::getPrivate(d->authenticator);
     //qDebug() << "slotSocketConnected: priv=" << priv << (priv ? (int)priv->method : -1);
     if (priv && priv->method != QAuthenticatorPrivate::None) {
         d->credentialsSent = true;
         data += "Proxy-Authorization: " + priv->calculateResponse(method, path);
         data += "\r\n";
     }
     data += "\r\n";
 //     qDebug() << ">>>>>>>> sending request" << this;
 //     qDebug() << data;
 //     qDebug() << ">>>>>>>";
     d->socket->write(data);
     d->state = ConnectSent;
 }
slotSocketDisconnected
void QHttpSocketEngine::slotSocketDisconnected () slot
Definition at line 532 of file qhttpsocketengine.cpp.
Referenced by initialize().
 {
 }
slotSocketError
void QHttpSocketEngine::slotSocketError (QAbstractSocket::SocketError error) slot
Definition at line 711 of file qhttpsocketengine.cpp.
Referenced by initialize().
 {
     Q_D(QHttpSocketEngine);
     d->readBuffer.clear();
     if (d->state != Connected) {
         // we are in proxy handshaking stages
         if (error == QAbstractSocket::HostNotFoundError)
             setError(QAbstractSocket::ProxyNotFoundError, tr("Proxy server not found"));
         else if (error == QAbstractSocket::ConnectionRefusedError)
             setError(QAbstractSocket::ProxyConnectionRefusedError, tr("Proxy connection refused"));
         else if (error == QAbstractSocket::SocketTimeoutError)
             setError(QAbstractSocket::ProxyConnectionTimeoutError, tr("Proxy server connection timed out"));
         else if (error == QAbstractSocket::RemoteHostClosedError)
             setError(QAbstractSocket::ProxyConnectionClosedError, tr("Proxy connection closed prematurely"));
         else
             setError(error, d->socket->errorString());
         emitConnectionNotification();
         return;
     }
     // We're connected
     if (error == QAbstractSocket::SocketTimeoutError)
         return;                 // ignore this error
     d->state = None;
     setError(error, d->socket->errorString());
     if (error != QAbstractSocket::RemoteHostClosedError)
         qDebug() << "QHttpSocketEngine::slotSocketError: got weird error =" << error;
     //read notification needs to always be emitted, otherwise the higher layer doesn't get the disconnected signal
     emitReadNotification();
 }
slotSocketReadNotification
void QHttpSocketEngine::slotSocketReadNotification () slot
Definition at line 536 of file qhttpsocketengine.cpp.
Referenced by connectInternal(), initialize(), and setReadNotificationEnabled().
 {
     Q_D(QHttpSocketEngine);
     if (d->state != Connected && d->socket->bytesAvailable() == 0)
         return;
     if (d->state == Connected) {
         // Forward as a read notification.
         if (d->readNotificationEnabled)
             emitReadNotification();
         return;
     }
   readResponseContent:
     if (d->state == ReadResponseContent) {
         char dummybuffer[4096];
         while (d->pendingResponseData) {
             int read = d->socket->read(dummybuffer, qMin(sizeof(dummybuffer), (size_t)d->pendingResponseData));
             if (read >= 0)
                 dummybuffer[read] = 0;
             if (read == 0)
                 return;
             if (read == -1) {
                 d->socket->disconnectFromHost();
                 emitWriteNotification();
                 return;
             }
             d->pendingResponseData -= read;
         }
         if (d->pendingResponseData > 0)
             return;
         d->state = SendAuthentication;
         slotSocketConnected();
         return;
     }
     // Still in handshake mode. Wait until we've got a full response.
     bool done = false;
     do {
         d->readBuffer += d->socket->readLine();
     } while (!(done = d->readBuffer.endsWith("\r\n\r\n")) && d->socket->canReadLine());
     if (!done) {
         // Wait for more.
         return;
     }
     if (!d->readBuffer.startsWith("HTTP/1.")) {
         // protocol error, this isn't HTTP
         d->readBuffer.clear();
         d->socket->close();
         setState(QAbstractSocket::UnconnectedState);
         setError(QAbstractSocket::ProxyProtocolError, tr("Did not receive HTTP response from proxy"));
         emitConnectionNotification();
         return;
     }
     QHttpResponseHeader responseHeader(QString::fromLatin1(d->readBuffer));
     d->readBuffer.clear(); // we parsed the proxy protocol response. from now on direct socket reading will be done
     int statusCode = responseHeader.statusCode();
     QAuthenticatorPrivate *priv = 0;
     if (statusCode == 200) {
         d->state = Connected;
         setLocalAddress(d->socket->localAddress());
         setLocalPort(d->socket->localPort());
         setState(QAbstractSocket::ConnectedState);
         d->authenticator.detach();
         priv = QAuthenticatorPrivate::getPrivate(d->authenticator);
         priv->hasFailed = false;
     } else if (statusCode == 407) {
         if (d->credentialsSent) {
             //407 response again means the provided username/password were invalid.
             d->authenticator = QAuthenticator(); //this is needed otherwise parseHttpResponse won't set the state, and then signal isn't emitted.
             d->authenticator.detach();
             priv = QAuthenticatorPrivate::getPrivate(d->authenticator);
             priv->hasFailed = true;
         }
         else if (d->authenticator.isNull())
             d->authenticator.detach();
         priv = QAuthenticatorPrivate::getPrivate(d->authenticator);
         priv->parseHttpResponse(responseHeader, true);
         if (priv->phase == QAuthenticatorPrivate::Invalid) {
             // problem parsing the reply
             d->socket->close();
             setState(QAbstractSocket::UnconnectedState);
             setError(QAbstractSocket::ProxyProtocolError, tr("Error parsing authentication request from proxy"));
             emitConnectionNotification();
             return;
         }
         bool willClose;
         QString proxyConnectionHeader = responseHeader.value(QLatin1String("Proxy-Connection"));
         // Although most proxies use the unofficial Proxy-Connection header, the Connection header
         // from http spec is also allowed.
         if (proxyConnectionHeader.isEmpty())
             proxyConnectionHeader = responseHeader.value(QLatin1String("Connection"));
         proxyConnectionHeader = proxyConnectionHeader.toLower();
         if (proxyConnectionHeader == QLatin1String("close")) {
             willClose = true;
         } else if (proxyConnectionHeader == QLatin1String("keep-alive")) {
             willClose = false;
         } else {
             // no Proxy-Connection header, so use the default
             // HTTP 1.1's default behaviour is to keep persistent connections
             // HTTP 1.0 or earlier, so we expect the server to close
             willClose = (responseHeader.majorVersion() * 0x100 + responseHeader.minorVersion()) <= 0x0100;
         }
         if (willClose) {
             // the server will disconnect, so let's avoid receiving an error
             // especially since the signal below may trigger a new event loop
             d->socket->disconnectFromHost();
             d->socket->readAll();
         }
         if (priv->phase == QAuthenticatorPrivate::Done)
             emit proxyAuthenticationRequired(d->proxy, &d->authenticator);
         // priv->phase will get reset to QAuthenticatorPrivate::Start if the authenticator got modified in the signal above.
         if (priv->phase == QAuthenticatorPrivate::Done) {
             setError(QAbstractSocket::ProxyAuthenticationRequiredError, tr("Authentication required"));
             d->socket->disconnectFromHost();
         } else {
             // close the connection if it isn't already and reconnect using the chosen authentication method
             d->state = SendAuthentication;
             if (willClose) {
                 d->socket->connectToHost(d->proxy.hostName(), d->proxy.port());
             } else {
                 bool ok;
                 int contentLength = responseHeader.value(QLatin1String("Content-Length")).toInt(&ok);
                 if (ok && contentLength > 0) {
                     d->state = ReadResponseContent;
                     d->pendingResponseData = contentLength;
                     goto readResponseContent;
                 } else {
                     d->state = SendAuthentication;
                     slotSocketConnected();
                 }
             }
             return;
         }
     } else {
         d->socket->close();
         setState(QAbstractSocket::UnconnectedState);
         if (statusCode == 403 || statusCode == 405) {
             // 403 Forbidden
             // 405 Method Not Allowed
             setError(QAbstractSocket::SocketAccessError, tr("Proxy denied connection"));
         } else if (statusCode == 404) {
             // 404 Not Found: host lookup error
             setError(QAbstractSocket::HostNotFoundError, QAbstractSocket::tr("Host not found"));
         } else if (statusCode == 503) {
             // 503 Service Unavailable: Connection Refused
             setError(QAbstractSocket::ConnectionRefusedError, QAbstractSocket::tr("Connection refused"));
         } else {
             // Some other reply
             //qWarning("UNEXPECTED RESPONSE: [%s]", responseHeader.toString().toLatin1().data());
             setError(QAbstractSocket::ProxyProtocolError, tr("Error communicating with HTTP proxy"));
         }
     }
     // The handshake is done; notify that we're connected (or failed to connect)
     emitConnectionNotification();
 }
slotSocketStateChanged
void QHttpSocketEngine::slotSocketStateChanged (QAbstractSocket::SocketState state) slot
Definition at line 744 of file qhttpsocketengine.cpp.
Referenced by initialize().
 {
     Q_UNUSED(state);
 }
socketDescriptor()
int QHttpSocketEngine::socketDescriptor () const virtual
Implements QAbstractSocketEngine.
Definition at line 123 of file qhttpsocketengine.cpp.
 {
     Q_D(const QHttpSocketEngine);
     return d->socket ? d->socket->socketDescriptor() : 0;
 }
waitForRead()
bool QHttpSocketEngine::waitForRead (int msecs = 30000, bool * timedOut = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 353 of file qhttpsocketengine.cpp.
Referenced by waitForReadOrWrite().
 {
     Q_D(const QHttpSocketEngine);
     if (!d->socket || d->socket->state() == QAbstractSocket::UnconnectedState)
         return false;
     QElapsedTimer stopWatch;
     stopWatch.start();
     // Wait for more data if nothing is available.
     if (!d->socket->bytesAvailable()) {
         if (!d->socket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))) {
             if (d->socket->state() == QAbstractSocket::UnconnectedState)
                 return true;
             setError(d->socket->error(), d->socket->errorString());
             if (timedOut && d->socket->error() == QAbstractSocket::SocketTimeoutError)
                 *timedOut = true;
             return false;
         }
     }
     // If we're not connected yet, wait until we are, or until an error
     // occurs.
     while (d->state != Connected && d->socket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))) {
         // Loop while the protocol handshake is taking place.
     }
     // Report any error that may occur.
     if (d->state != Connected) {
         setError(d->socket->error(), d->socket->errorString());
         if (timedOut && d->socket->error() == QAbstractSocket::SocketTimeoutError)
             *timedOut = true;
         return false;
     }
     return true;
 }
waitForReadOrWrite()
bool QHttpSocketEngine::waitForReadOrWrite (bool * readyToRead, bool * readyToWrite, bool checkRead, bool checkWrite, int msecs = 30000, bool * timedOut = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 427 of file qhttpsocketengine.cpp.
 {
     Q_UNUSED(checkRead);
     if (!checkWrite) {
         // Not interested in writing? Then we wait for read notifications.
         bool canRead = waitForRead(msecs, timedOut);
         if (readyToRead)
             *readyToRead = canRead;
         return canRead;
     }
     // Interested in writing? Then we wait for write notifications.
     bool canWrite = waitForWrite(msecs, timedOut);
     if (readyToWrite)
         *readyToWrite = canWrite;
     return canWrite;
 }
waitForWrite()
bool QHttpSocketEngine::waitForWrite (int msecs = 30000, bool * timedOut = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 391 of file qhttpsocketengine.cpp.
Referenced by waitForReadOrWrite().
 {
     Q_D(const QHttpSocketEngine);
     // If we're connected, just forward the call.
     if (d->state == Connected) {
         if (d->socket->bytesToWrite()) {
             if (!d->socket->waitForBytesWritten(msecs)) {
                 if (d->socket->error() == QAbstractSocket::SocketTimeoutError && timedOut)
                     *timedOut = true;
                 return false;
             }
         }
         return true;
     }
     QElapsedTimer stopWatch;
     stopWatch.start();
     // If we're not connected yet, wait until we are, and until bytes have
     // been received (i.e., the socket has connected, we have sent the
     // greeting, and then received the response).
     while (d->state != Connected && d->socket->waitForReadyRead(qt_timeout_value(msecs, stopWatch.elapsed()))) {
         // Loop while the protocol handshake is taking place.
     }
     // Report any error that may occur.
     if (d->state != Connected) {
 //        setError(d->socket->error(), d->socket->errorString());
         if (timedOut && d->socket->error() == QAbstractSocket::SocketTimeoutError)
             *timedOut = true;
     }
     return true;
 }
write()
qint64 QHttpSocketEngine::write (const char * data, qint64 len) virtual
Implements QAbstractSocketEngine.
Definition at line 243 of file qhttpsocketengine.cpp.
 {
     Q_D(QHttpSocketEngine);
     return d->socket->write(data, len);
 }
writeDatagram()
qint64 QHttpSocketEngine::writeDatagram (const char * data, qint64 len, const QHostAddress & addr, quint16 port) virtual
Implements QAbstractSocketEngine.
Definition at line 286 of file qhttpsocketengine.cpp.
 {
     return 0;
 }
The documentation for this class was generated from the following files:
/src/network/socket/qhttpsocketengine_p.h
/src/network/socket/qhttpsocketengine.cpp