Qt 4.8: QTouchEvent::TouchPoint Class Reference
QTouchEvent::TouchPoint Class Reference
The TouchPoint class provides information about a touch point in a QTouchEvent.
#include <qevent.h>
Public Functions
int id () const
Returns the id number of this touch point.
bool isPrimary () const
Returns true if this touch point is the primary touch point.
QPointF lastNormalizedPos () const
Returns the normalized position of this touch point from the previous touch event.
QPointF lastPos () const
Returns the position of this touch point from the previous touch event, relative to the widget or QGraphicsItem that received the event.
QPointF lastScenePos () const
Returns the scene position of this touch point from the previous touch event.
QPointF lastScreenPos () const
Returns the screen position of this touch point from the previous touch event.
QPointF normalizedPos () const
Returns the normalized position of this touch point.
QTouchEvent::TouchPoint & operator= (const QTouchEvent::TouchPoint &other)
QPointF pos () const
Returns the position of this touch point, relative to the widget or QGraphicsItem that received the event.
qreal pressure () const
Returns the pressure of this touch point.
QRectF rect () const
Returns the rect for this touch point, relative to the widget or QGraphicsItem that received the event.
QPointF scenePos () const
Returns the scene position of this touch point.
QRectF sceneRect () const
Returns the rect for this touch point in scene coordinates.
QPointF screenPos () const
Returns the screen position of this touch point.
QRectF screenRect () const
Returns the rect for this touch point in screen coordinates.
void setId (int id)
void setLastNormalizedPos (const QPointF &lastNormalizedPos)
void setLastPos (const QPointF &lastPos)
void setLastScenePos (const QPointF &lastScenePos)
void setLastScreenPos (const QPointF &lastScreenPos)
void setNormalizedPos (const QPointF &normalizedPos)
void setPos (const QPointF &pos)
void setPressure (qreal pressure)
void setRect (const QRectF &rect)
void setScenePos (const QPointF &scenePos)
void setSceneRect (const QRectF &sceneRect)
void setScreenPos (const QPointF &screenPos)
void setScreenRect (const QRectF &screenRect)
void setStartNormalizedPos (const QPointF &startNormalizedPos)
void setStartPos (const QPointF &startPos)
void setStartScenePos (const QPointF &startScenePos)
void setStartScreenPos (const QPointF &startScreenPos)
void setState (Qt::TouchPointStates state)
QPointF startNormalizedPos () const
Returns the normalized starting position of this touch point.
QPointF startPos () const
Returns the starting position of this touch point, relative to the widget or QGraphicsItem that received the event.
QPointF startScenePos () const
Returns the starting scene position of this touch point.
QPointF startScreenPos () const
Returns the starting screen position of this touch point.
Qt::TouchPointState state () const
Returns the current state of this touch point.
TouchPoint (int id=-1)
Constructs a QTouchEvent::TouchPoint for use in a QTouchEvent.
TouchPoint (const QTouchEvent::TouchPoint &other)
Constructs a copy of other.
~TouchPoint ()
Destroys the QTouchEvent::TouchPoint.
Properties
QTouchEventTouchPointPrivate * d
Friends
class QApplication
class QApplicationPrivate
Detailed Description
The TouchPoint class provides information about a touch point in a QTouchEvent.
Since
4.6
Definition at line 744 of file qevent.h.
Constructors and Destructors
TouchPoint() [1/2]
QTouchEvent::TouchPoint::TouchPoint (int id = -1)
Constructs a QTouchEvent::TouchPoint for use in a QTouchEvent.
Warning
This function is not part of the public interface.
Definition at line 4408 of file qevent.cpp.
     : d(new QTouchEventTouchPointPrivate(id))
 { }
TouchPoint() [2/2]
QTouchEvent::TouchPoint::TouchPoint (const QTouchEvent::TouchPoint & other)
Constructs a copy of other.
Warning
This function is not part of the public interface.
Definition at line 4419 of file qevent.cpp.
     : d(other.d)
 {
     d->ref.ref();
 }
~TouchPoint()
QTouchEvent::TouchPoint::~TouchPoint ()
Destroys the QTouchEvent::TouchPoint.
Warning
This function is not part of the public interface.
Definition at line 4432 of file qevent.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
Functions
id()
int QTouchEvent::TouchPoint::id () const
Returns the id number of this touch point.
Id numbers are globally sequential, starting at zero, meaning the first touch point in the application has id 0, the second has id 1, and so on.
Definition at line 4445 of file qevent.cpp.
Referenced by QGraphicsScenePrivate::findClosestTouchPointId(), QApplicationPrivate::findClosestTouchPointId(), QApplication::notify(), QGraphicsScenePrivate::sendTouchBeginEvent(), setId(), QGraphicsScenePrivate::touchEventHandler(), QApplicationPrivate::translateRawTouchEvent(), and QDeclarativePinchArea::updatePinch().
 {
     return d->id;
 }
isPrimary()
bool QTouchEvent::TouchPoint::isPrimary () const
Returns true if this touch point is the primary touch point.
The primary touch point is the point for which the windowing system generates mouse events.
Definition at line 4462 of file qevent.cpp.
Referenced by QWidget::event(), and QApplicationPrivate::translateRawTouchEvent().
 {
     return (d->state & Qt::TouchPointPrimary) != 0;
 }
lastNormalizedPos()
QPointF QTouchEvent::TouchPoint::lastNormalizedPos () const
Returns the normalized position of this touch point from the previous touch event.
The coordinates are normalized to the size of the touch device, i.e. (0,0) is the top-left corner and (1,1) is the bottom-right corner.
See also
normalizedPos(), startNormalizedPos()
Definition at line 4612 of file qevent.cpp.
Referenced by setLastNormalizedPos().
 {
     return d->lastNormalizedPos;
 }
lastPos()
QPointF QTouchEvent::TouchPoint::lastPos () const
Returns the position of this touch point from the previous touch event, relative to the widget or QGraphicsItem that received the event.
See also
pos(), startPos()
Definition at line 4571 of file qevent.cpp.
Referenced by QApplication::notify(), setLastPos(), and QGraphicsViewPrivate::translateTouchEvent().
 {
     return d->lastPos;
 }
lastScenePos()
QPointF QTouchEvent::TouchPoint::lastScenePos () const
Returns the scene position of this touch point from the previous touch event.
The scene position is the position in QGraphicsScene coordinates if the QTouchEvent is handled by a QGraphicsItem::touchEvent() reimplementation, and identical to the screen position for widgets.
See also
scenePos(), startScenePos()
Definition at line 4587 of file qevent.cpp.
Referenced by setLastScenePos(), and QGraphicsScenePrivate::updateTouchPointsForItem().
 {
     return d->lastScenePos;
 }
lastScreenPos()
QPointF QTouchEvent::TouchPoint::lastScreenPos () const
Returns the screen position of this touch point from the previous touch event.
See also
screenPos(), startScreenPos()
Definition at line 4598 of file qevent.cpp.
Referenced by QPinchGestureRecognizer::recognize(), setLastScreenPos(), QApplicationPrivate::translateRawTouchEvent(), and QApplicationPrivate::updateTouchPointsForWidget().
 {
     return d->lastScreenPos;
 }
normalizedPos()
QPointF QTouchEvent::TouchPoint::normalizedPos () const
Returns the normalized position of this touch point.
The coordinates are normalized to the size of the touch device, i.e. (0,0) is the top-left corner and (1,1) is the bottom-right corner.
See also
startNormalizedPos(), lastNormalizedPos(), pos()
Definition at line 4511 of file qevent.cpp.
Referenced by setNormalizedPos(), and QApplicationPrivate::translateRawTouchEvent().
 {
     return d->normalizedPos;
 }
operator=()
QTouchEvent::TouchPoint & QTouchEvent::TouchPoint::operator= (const QTouchEvent::TouchPoint & other)
Warning
This function is not part of the public interface.
Definition at line 4807 of file qevent.cpp.
 {
     other.d->ref.ref();
     if (!d->ref.deref())
         delete d;
     d = other.d;
     return *this;
 }
pos()
QPointF QTouchEvent::TouchPoint::pos () const
Returns the position of this touch point, relative to the widget or QGraphicsItem that received the event.
See also
startPos(), lastPos(), screenPos(), scenePos(), normalizedPos()
Definition at line 4473 of file qevent.cpp.
Referenced by QWidget::event(), QPanGestureRecognizer::recognize(), QTapGestureRecognizer::recognize(), QTapAndHoldGestureRecognizer::recognize(), QApplicationPrivate::translateRawTouchEvent(), and QDeclarativePinchArea::updatePinch().
 {
     return d->rect.center();
 }
pressure()
qreal QTouchEvent::TouchPoint::pressure () const
Returns the pressure of this touch point.
The return value is in the range 0.0 to 1.0.
Definition at line 4657 of file qevent.cpp.
Referenced by setPressure(), and QApplicationPrivate::translateRawTouchEvent().
 {
     return d->pressure;
 }
rect()
QRectF QTouchEvent::TouchPoint::rect () const
Returns the rect for this touch point, relative to the widget or QGraphicsItem that received the event.
The rect is centered around the point returned by pos().
Note
This function returns an empty rect if the device does not report touch point sizes.
Definition at line 4624 of file qevent.cpp.
Referenced by QApplication::notify(), setRect(), and QGraphicsViewPrivate::translateTouchEvent().
 {
     return d->rect;
 }
scenePos()
QPointF QTouchEvent::TouchPoint::scenePos () const
Returns the scene position of this touch point.
The scene position is the position in QGraphicsScene coordinates if the QTouchEvent is handled by a QGraphicsItem::touchEvent() reimplementation, and identical to the screen position for widgets.
See also
startScenePos(), lastScenePos(), pos()
Definition at line 4488 of file qevent.cpp.
Referenced by QGraphicsScenePrivate::findClosestTouchPointId(), QGraphicsScenePrivate::sendTouchBeginEvent(), QGraphicsScenePrivate::touchEventHandler(), and QDeclarativePinchArea::updatePinch().
 {
     return d->sceneRect.center();
 }
sceneRect()
QRectF QTouchEvent::TouchPoint::sceneRect () const
Returns the rect for this touch point in scene coordinates.
Note
This function returns an empty rect if the device does not report touch point sizes.
See also
scenePos(), rect()
Definition at line 4636 of file qevent.cpp.
Referenced by setSceneRect(), and QGraphicsScenePrivate::updateTouchPointsForItem().
 {
     return d->sceneRect;
 }
screenPos()
QPointF QTouchEvent::TouchPoint::screenPos () const
Returns the screen position of this touch point.
See also
startScreenPos(), lastScreenPos(), pos()
Definition at line 4498 of file qevent.cpp.
Referenced by QWidget::event(), QApplicationPrivate::findClosestTouchPointId(), QPinchGestureRecognizer::recognize(), QSwipeGestureRecognizer::recognize(), QTapGestureRecognizer::recognize(), QGraphicsScenePrivate::sendTouchBeginEvent(), QGraphicsScenePrivate::touchEventHandler(), QApplicationPrivate::translateRawTouchEvent(), and QApplicationPrivate::translateTouchEvent().
 {
     return d->screenRect.center();
 }
screenRect()
QRectF QTouchEvent::TouchPoint::screenRect () const
Returns the rect for this touch point in screen coordinates.
Note
This function returns an empty rect if the device does not report touch point sizes.
See also
screenPos(), rect()
Definition at line 4648 of file qevent.cpp.
Referenced by setScreenRect(), QApplicationPrivate::translateRawTouchEvent(), and QApplicationPrivate::updateTouchPointsForWidget().
 {
     return d->screenRect;
 }
setId()
void QTouchEvent::TouchPoint::setId (int id)
Warning
This function is not part of the public interface.
Definition at line 4663 of file qevent.cpp.
Referenced by QWindowSystemInterface::handleTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->id = id;
 }
setLastNormalizedPos()
void QTouchEvent::TouchPoint::setLastNormalizedPos (const QPointF & lastNormalizedPos)
Warning
This function is not part of the public interface.
Definition at line 4767 of file qevent.cpp.
 {
     if (d->ref != 1)
         d = d->detach();
     d->lastNormalizedPos = lastNormalizedPos;
 }
setLastPos()
void QTouchEvent::TouchPoint::setLastPos (const QPointF & lastPos)
Warning
This function is not part of the public interface.
Definition at line 4743 of file qevent.cpp.
Referenced by QGraphicsScenePrivate::updateTouchPointsForItem().
 {
     if (d->ref != 1)
         d = d->detach();
     d->lastPos = lastPos;
 }
setLastScenePos()
void QTouchEvent::TouchPoint::setLastScenePos (const QPointF & lastScenePos)
Warning
This function is not part of the public interface.
Definition at line 4751 of file qevent.cpp.
Referenced by QGraphicsViewPrivate::translateTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->lastScenePos = lastScenePos;
 }
setLastScreenPos()
void QTouchEvent::TouchPoint::setLastScreenPos (const QPointF & lastScreenPos)
Warning
This function is not part of the public interface.
Definition at line 4759 of file qevent.cpp.
 {
     if (d->ref != 1)
         d = d->detach();
     d->lastScreenPos = lastScreenPos;
 }
setNormalizedPos()
void QTouchEvent::TouchPoint::setNormalizedPos (const QPointF & normalizedPos)
Warning
This function is not part of the public interface.
Definition at line 4703 of file qevent.cpp.
Referenced by QWindowSystemInterface::handleTouchEvent(), and QApplicationPrivate::translateTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->normalizedPos = normalizedPos;
 }
setPos()
void QTouchEvent::TouchPoint::setPos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 4679 of file qevent.cpp.
 {
     if (d->ref != 1)
         d = d->detach();
     d->rect.moveCenter(pos);
 }
setPressure()
void QTouchEvent::TouchPoint::setPressure (qreal pressure)
Warning
This function is not part of the public interface.
Definition at line 4799 of file qevent.cpp.
Referenced by QWindowSystemInterface::handleTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->pressure = pressure;
 }
setRect()
void QTouchEvent::TouchPoint::setRect (const QRectF & rect)
Warning
This function is not part of the public interface.
Definition at line 4775 of file qevent.cpp.
Referenced by QWindowSystemInterface::handleTouchEvent(), and QGraphicsScenePrivate::updateTouchPointsForItem().
 {
     if (d->ref != 1)
         d = d->detach();
     d->rect = rect;
 }
setScenePos()
void QTouchEvent::TouchPoint::setScenePos (const QPointF & scenePos)
Warning
This function is not part of the public interface.
Definition at line 4687 of file qevent.cpp.
 {
     if (d->ref != 1)
         d = d->detach();
     d->sceneRect.moveCenter(scenePos);
 }
setSceneRect()
void QTouchEvent::TouchPoint::setSceneRect (const QRectF & sceneRect)
Warning
This function is not part of the public interface.
Definition at line 4783 of file qevent.cpp.
Referenced by QGraphicsViewPrivate::translateTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->sceneRect = sceneRect;
 }
setScreenPos()
void QTouchEvent::TouchPoint::setScreenPos (const QPointF & screenPos)
Warning
This function is not part of the public interface.
Definition at line 4695 of file qevent.cpp.
Referenced by QWindowSystemInterface::handleTouchEvent(), QTest::QTouchEventSequence::move(), QTest::QTouchEventSequence::press(), and QTest::QTouchEventSequence::release().
 {
     if (d->ref != 1)
         d = d->detach();
     d->screenRect.moveCenter(screenPos);
 }
setScreenRect()
void QTouchEvent::TouchPoint::setScreenRect (const QRectF & screenRect)
Warning
This function is not part of the public interface.
Definition at line 4791 of file qevent.cpp.
Referenced by QApplicationPrivate::translateTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->screenRect = screenRect;
 }
setStartNormalizedPos()
void QTouchEvent::TouchPoint::setStartNormalizedPos (const QPointF & startNormalizedPos)
Warning
This function is not part of the public interface.
Definition at line 4735 of file qevent.cpp.
 {
     if (d->ref != 1)
         d = d->detach();
     d->startNormalizedPos = startNormalizedPos;
 }
setStartPos()
void QTouchEvent::TouchPoint::setStartPos (const QPointF & startPos)
Warning
This function is not part of the public interface.
Definition at line 4711 of file qevent.cpp.
Referenced by QGraphicsScenePrivate::updateTouchPointsForItem().
 {
     if (d->ref != 1)
         d = d->detach();
     d->startPos = startPos;
 }
setStartScenePos()
void QTouchEvent::TouchPoint::setStartScenePos (const QPointF & startScenePos)
Warning
This function is not part of the public interface.
Definition at line 4719 of file qevent.cpp.
Referenced by QGraphicsViewPrivate::translateTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->startScenePos = startScenePos;
 }
setStartScreenPos()
void QTouchEvent::TouchPoint::setStartScreenPos (const QPointF & startScreenPos)
Warning
This function is not part of the public interface.
Definition at line 4727 of file qevent.cpp.
 {
     if (d->ref != 1)
         d = d->detach();
     d->startScreenPos = startScreenPos;
 }
setState()
void QTouchEvent::TouchPoint::setState (Qt::TouchPointStates state)
Warning
This function is not part of the public interface.
Definition at line 4671 of file qevent.cpp.
Referenced by QWindowSystemInterface::handleTouchEvent(), QTest::QTouchEventSequence::move(), QTest::QTouchEventSequence::press(), QTest::QTouchEventSequence::release(), QTest::QTouchEventSequence::stationary(), and QApplicationPrivate::translateTouchEvent().
 {
     if (d->ref != 1)
         d = d->detach();
     d->state = state;
 }
startNormalizedPos()
QPointF QTouchEvent::TouchPoint::startNormalizedPos () const
Returns the normalized starting position of this touch point.
The coordinates are normalized to the size of the touch device, i.e. (0,0) is the top-left corner and (1,1) is the bottom-right corner.
See also
normalizedPos(), lastNormalizedPos()
Definition at line 4560 of file qevent.cpp.
Referenced by setStartNormalizedPos(), and QApplicationPrivate::translateRawTouchEvent().
 {
     return d->startNormalizedPos;
 }
startPos()
QPointF QTouchEvent::TouchPoint::startPos () const
Returns the starting position of this touch point, relative to the widget or QGraphicsItem that received the event.
See also
pos(), lastPos()
Definition at line 4522 of file qevent.cpp.
Referenced by QApplication::notify(), QPanGestureRecognizer::recognize(), QTapGestureRecognizer::recognize(), QTapAndHoldGestureRecognizer::recognize(), setStartPos(), QApplicationPrivate::translateRawTouchEvent(), and QGraphicsViewPrivate::translateTouchEvent().
 {
     return d->startPos;
 }
startScenePos()
QPointF QTouchEvent::TouchPoint::startScenePos () const
Returns the starting scene position of this touch point.
The scene position is the position in QGraphicsScene coordinates if the QTouchEvent is handled by a QGraphicsItem::touchEvent() reimplementation, and identical to the screen position for widgets.
See also
scenePos(), lastScenePos()
Definition at line 4537 of file qevent.cpp.
Referenced by setStartScenePos(), and QGraphicsScenePrivate::updateTouchPointsForItem().
 {
     return d->startScenePos;
 }
startScreenPos()
QPointF QTouchEvent::TouchPoint::startScreenPos () const
Returns the starting screen position of this touch point.
See also
screenPos(), lastScreenPos()
Definition at line 4547 of file qevent.cpp.
Referenced by QPanGestureRecognizer::recognize(), QPinchGestureRecognizer::recognize(), QSwipeGestureRecognizer::recognize(), QTapAndHoldGestureRecognizer::recognize(), setStartScreenPos(), QApplicationPrivate::translateRawTouchEvent(), and QApplicationPrivate::updateTouchPointsForWidget().
 {
     return d->startScreenPos;
 }
state()
Qt::TouchPointState QTouchEvent::TouchPoint::state () const
Returns the current state of this touch point.
Definition at line 4453 of file qevent.cpp.
Referenced by QDeclarativePinchArea::event(), QDeclarativePinchArea::sceneEventFilter(), setState(), QGraphicsScenePrivate::touchEventHandler(), QApplicationPrivate::translateRawTouchEvent(), QDeclarativePinchArea::updatePinch(), and QApplicationPrivate::updateTouchPointsForWidget().
 {
     return Qt::TouchPointState(int(d->state) & Qt::TouchPointStateMask);
 }
Friends and Related Functions
QApplication
friend class QApplication friend
Definition at line 801 of file qevent.h.
QApplicationPrivate
friend class QApplicationPrivate friend
Definition at line 802 of file qevent.h.
Properties
d
QTouchEventTouchPointPrivate* QTouchEvent::TouchPoint::d private
Definition at line 800 of file qevent.h.
Referenced by id(), isPrimary(), lastNormalizedPos(), lastPos(), lastScenePos(), lastScreenPos(), normalizedPos(), QApplication::notify(), operator=(), pos(), pressure(), rect(), scenePos(), sceneRect(), screenPos(), screenRect(), setId(), setLastNormalizedPos(), setLastPos(), setLastScenePos(), setLastScreenPos(), setNormalizedPos(), setPos(), setPressure(), setRect(), setScenePos(), setSceneRect(), setScreenPos(), setScreenRect(), setStartNormalizedPos(), setStartPos(), setStartScenePos(), setStartScreenPos(), setState(), startNormalizedPos(), startPos(), startScenePos(), startScreenPos(), state(), TouchPoint(), QApplicationPrivate::translateRawTouchEvent(), QApplicationPrivate::updateTouchPointsForWidget(), and ~TouchPoint().
The documentation for this class was generated from the following files:
/src/gui/kernel/qevent.h
/src/gui/kernel/qevent.cpp