Qt 4.8: QFileDialog Class Reference
QFileDialog Class Reference
The QFileDialog class provides a dialog that allow users to select files or directories.
#include <qfiledialog.h>
Public Types
enum AcceptMode { AcceptOpen, AcceptSave }
enum DialogLabel {
LookIn, FileName, FileType, Accept,
Reject
}
enum FileMode {
AnyFile, ExistingFile, Directory, ExistingFiles,
DirectoryOnly
}
This enum is used to indicate what the user may select in the file dialog; i.
enum Option {
ShowDirsOnly = 0x00000001, DontResolveSymlinks = 0x00000002, DontConfirmOverwrite = 0x00000004, DontUseSheet = 0x00000008,
DontUseNativeDialog = 0x00000010, ReadOnly = 0x00000020, HideNameFilterDetails = 0x00000040, DontUseCustomDirectoryIcons = 0x00000080
}
Some platforms allow the user to set a different icon.
enum ViewMode { Detail, List }
This enum describes the view mode of the file dialog; i.
Public Types inherited from QDialog
enum DialogCode { Rejected, Accepted }
The value returned by a modal dialog.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Signals
void currentChanged (const QString &path)
When the current file changes, this signal is emitted with the new file name as the path parameter.
void directoryEntered (const QString &directory)
This signal is emitted when the user enters a directory.
void fileSelected (const QString &file)
When the selection changes and the dialog is accepted, this signal is emitted with the (possibly empty) selected file.
void filesSelected (const QStringList &files)
When the selection changes and the dialog is accepted, this signal is emitted with the (possibly empty) list of selected files.
void filterSelected (const QString &filter)
This signal is emitted when the user selects a filter.
Signals inherited from QDialog
void accepted ()
This signal is emitted when the dialog has been accepted either by the user or by calling accept() or done() with the QDialog::Accepted argument.
void finished (int result)
This signal is emitted when the dialog's result code has been set, either by the user or by calling done(), accept(), or reject().
void rejected ()
This signal is emitted when the dialog has been rejected either by the user or by calling reject() or done() with the QDialog::Rejected argument.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
AcceptMode acceptMode () const
bool confirmOverwrite () const
QString defaultSuffix () const
QDir directory () const
Returns the directory currently being displayed in the dialog.
FileMode fileMode () const
QDir::Filters filter () const
Returns the filter that is used when displaying files.
QT_DEPRECATED QStringList filters () const
Use nameFilters() instead.
QStringList history () const
Returns the browsing history of the filedialog as a list of paths.
QFileIconProvider * iconProvider () const
Returns the icon provider used by the filedialog.
bool isNameFilterDetailsVisible () const
bool isReadOnly () const
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used to render the items in the views in the filedialog.
QString labelText (DialogLabel label) const
Returns the text shown in the filedialog in the specified label.
QStringList nameFilters () const
Returns the file type filters that are in operation on this file dialog.
void open (QObject *receiver, const char *member)
This function connects one of its signals to the slot specified by receiver and member.
Options options () const
QAbstractProxyModel * proxyModel () const
Returns the proxy model used by the file dialog.
QFileDialog (QWidget *parent, Qt::WindowFlags f)
Constructs a file dialog with the given parent and widget flags.
QFileDialog (QWidget *parent=0, const QString &caption=QString(), const QString &directory=QString(), const QString &filter=QString())
Constructs a file dialog with the given parent and caption that initially displays the contents of the specified directory.
bool resolveSymlinks () const
bool restoreState (const QByteArray &state)
Restores the dialogs's layout, history and current directory to the state specified.
QByteArray saveState () const
Saves the state of the dialog's layout, history and current directory.
QStringList selectedFiles () const
Returns a list of strings containing the absolute paths of the selected files in the dialog.
QT_DEPRECATED QString selectedFilter () const
Use selectedNameFilter() instead.
QString selectedNameFilter () const
Returns the filter that the user selected in the file dialog.
void selectFile (const QString &filename)
Selects the given filename in the file dialog.
QT_DEPRECATED void selectFilter (const QString &filter)
Use selectNameFilter() instead.
void selectNameFilter (const QString &filter)
Sets the current file type filter.
void setAcceptMode (AcceptMode mode)
void setConfirmOverwrite (bool enabled)
void setDefaultSuffix (const QString &suffix)
void setDirectory (const QString &directory)
Sets the file dialog's current directory.
void setDirectory (const QDir &directory)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void setFileMode (FileMode mode)
QT_DEPRECATED void setFilter (const QString &filter)
Use setNameFilter() instead.
void setFilter (QDir::Filters filters)
Sets the filter used by the model to filters.
QT_DEPRECATED void setFilters (const QStringList &filters)
Use setNameFilters() instead.
void setHistory (const QStringList &paths)
Sets the browsing history of the filedialog to contain the given paths.
void setIconProvider (QFileIconProvider *provider)
Sets the icon provider used by the filedialog to the specified provider.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate used to render items in the views in the file dialog to the given delegate.
void setLabelText (DialogLabel label, const QString &text)
Sets the text shown in the filedialog in the specified label.
void setNameFilter (const QString &filter)
void setNameFilterDetailsVisible (bool enabled)
void setNameFilters (const QStringList &filters)
Sets the filters used in the file dialog.
void setOption (Option option, bool on=true)
Sets the given option to be enabled if on is true; otherwise, clears the given option.
void setOptions (Options options)
void setProxyModel (QAbstractProxyModel *model)
Sets the model for the views to the given proxyModel.
void setReadOnly (bool enabled)
void setResolveSymlinks (bool enabled)
void setSidebarUrls (const QList< QUrl > &urls)
Sets the urls that are located in the sidebar.
void setViewMode (ViewMode mode)
void setVisible (bool visible)
Reimplemented Function
QList< QUrl > sidebarUrls () const
bool testOption (Option option) const
Returns true if the given option is enabled; otherwise, returns false.
ViewMode viewMode () const
~QFileDialog ()
Destroys the file dialog.
Public Functions inherited from QDialog
QWidget * extension () const
Returns the dialog's extension or 0 if no extension has been defined.
bool isSizeGripEnabled () const
QSize minimumSizeHint () const
Reimplemented Function
Qt::Orientation orientation () const
Returns the dialog's extension orientation.
QDialog (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a dialog with parent parent.
int result () const
In general returns the modal dialog's result code, Accepted or Rejected.
void setExtension (QWidget *extension)
Sets the widget, extension, to be the dialog's extension, deleting any previous extension.
void setModal (bool modal)
void setOrientation (Qt::Orientation orientation)
If orientation is Qt::Horizontal, the extension will be displayed to the right of the dialog's main area.
void setResult (int r)
Sets the modal dialog's result code to i.
void setSizeGripEnabled (bool)
QSize sizeHint () const
Reimplemented Function
~QDialog ()
Destroys the QDialog, deleting all its children.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static QString getExistingDirectory (QWidget *parent=0, const QString &caption=QString(), const QString &dir=QString(), Options options=ShowDirsOnly)
This is a convenience static function that will return an existing directory selected by the user.
static QString getOpenFileName (QWidget *parent=0, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=0, Options options=0)
This is a convenience static function that returns an existing file selected by the user.
static QStringList getOpenFileNames (QWidget *parent=0, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=0, Options options=0)
This is a convenience static function that will return one or more existing files selected by the user.
static QString getSaveFileName (QWidget *parent=0, const QString &caption=QString(), const QString &dir=QString(), const QString &filter=QString(), QString *selectedFilter=0, Options options=0)
This is a convenience static function that will return a file name selected by the user.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
void accept ()
Reimplemented Function
void changeEvent (QEvent *e)
Reimplemented Function
void done (int result)
Reimplemented Function
QFileDialog (const QFileDialogArgs &args)
Protected Functions inherited from QDialog
void adjustPosition (QWidget *)
void closeEvent (QCloseEvent *)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
Reimplemented Function
QDialog (QDialogPrivate &, QWidget *parent, Qt::WindowFlags f=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
void resizeEvent (QResizeEvent *)
Reimplemented Function
void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
AcceptMode acceptMode
the accept mode of the dialog
bool confirmOverwrite
whether the filedialog should ask before accepting a selected file, when the accept mode is AcceptSave
QString defaultSuffix
suffix added to the filename if no other suffix was specified
FileMode fileMode
the file mode of the dialog
bool nameFilterDetailsVisible
This property holds whether the filter details is shown or not.
Options options
the various options that affect the look and feel of the dialog
bool readOnly
Whether the filedialog is read-only.
bool resolveSymlinks
whether the filedialog should resolve shortcuts
ViewMode viewMode
the way files and directories are displayed in the dialog
Additional Inherited Members
Public Slots inherited from QDialog
int exec ()
Shows the dialog as a modal dialog, blocking until the user closes it.
void open ()
Shows the dialog as a window modal dialog, returning immediately.
virtual void reject ()
Hides the modal dialog and sets the result code to Rejected.
void showExtension (bool)
If showIt is true, the dialog's extension is shown; otherwise the extension is hidden.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QFileDialog class provides a dialog that allow users to select files or directories.
The QFileDialog class enables a user to traverse the file system in order to select one or many files or a directory.
The easiest way to create a QFileDialog is to use the static functions. On Windows, Mac OS X, KDE and GNOME, these static functions will call the native file dialog when possible.
fileName = QFileDialog::getOpenFileName(this,
    tr("Open Image"), "/home/jana", tr("Image Files (*.png *.jpg *.bmp)"));
In the above example, a modal QFileDialog is created using a static function. The dialog initially displays the contents of the "/home/jana" directory, and displays files matching the patterns given in the string "Image Files (*.png *.jpg *.bmp)". The parent of the file dialog is set to this, and the window title is set to "Open Image".
If you want to use multiple filters, separate each one with two semicolons. For example:
"Images (*.png *.xpm *.jpg);;Text files (*.txt);;XML files (*.xml)"
You can create your own QFileDialog without using the static functions. By calling setFileMode(), you can specify what the user must select in the dialog:
QFileDialog dialog(this);
dialog.setFileMode(QFileDialog::AnyFile);
In the above example, the mode of the file dialog is set to AnyFile, meaning that the user can select any file, or even specify a file that doesn't exist. This mode is useful for creating a "Save As" file dialog. Use ExistingFile if the user must select an existing file, or Directory if only a directory may be selected. See the QFileDialog::FileMode enum for the complete list of modes.
The fileMode property contains the mode of operation for the dialog; this indicates what types of objects the user is expected to select. Use setNameFilter() to set the dialog's file filter. For example:
dialog.setNameFilter(tr("Images (*.png *.xpm *.jpg)"));
In the above example, the filter is set to "Images (*.png *.xpm *.jpg)", this means that only files with the extension png, xpm, or jpg will be shown in the QFileDialog. You can apply several filters by using setNameFilters(). Use selectNameFilter() to select one of the filters you've given as the file dialog's default filter.
The file dialog has two view modes: QFileDialog::List and QFileDialog::Detail. QFileDialog::List presents the contents of the current directory as a list of file and directory names. QFileDialog::Detail also displays a list of file and directory names, but provides additional information alongside each name, such as the file size and modification date. Set the mode with setViewMode():
dialog.setViewMode(QFileDialog::Detail);
The last important function you will need to use when creating your own file dialog is selectedFiles().
QStringList fileNames;
if (dialog.exec())
    fileNames = dialog.selectedFiles();
In the above example, a modal file dialog is created and shown. If the user clicked OK, the file they selected is put in fileName.
The dialog's working directory can be set with setDirectory(). Each file in the current directory can be selected using the selectFile() function.
The Standard Dialogs example shows how to use QFileDialog as well as other built-in Qt dialogs.
See also
QDir, QFileInfo, QFile, QPrintDialog, QColorDialog, QFontDialog, {Standard Dialogs Example}, {Application Example}
Definition at line 66 of file qfiledialog.h.
Enumerations
AcceptMode
enum QFileDialog::AcceptMode
AcceptOpen
AcceptSave
Enumerator
AcceptOpen
AcceptSave
Definition at line 84 of file qfiledialog.h.
 { AcceptOpen, AcceptSave };
DialogLabel
enum QFileDialog::DialogLabel
LookIn
FileName
FileType
Accept
Reject
Enumerator
LookIn
FileName
FileType
Accept
Reject
Definition at line 85 of file qfiledialog.h.
 { LookIn, FileName, FileType, Accept, Reject };
FileMode
enum QFileDialog::FileMode
This enum is used to indicate what the user may select in the file dialog; i.
e. what the dialog will return if the user clicks OK.
\arg \b AnyFile        The name of a file, whether it exists or not.
\arg \b ExistingFile   The name of a single existing file.
\arg \b Directory      The name of a directory. Both files and
                      directories are displayed.
\arg \b ExistingFiles  The names of zero or more existing files.
This value is obsolete since Qt 4.5:
\arg \b DirectoryOnly  Use \c Directory and setOption(ShowDirsOnly, true) instead.
\sa setFileMode()
Enumerator
AnyFile
ExistingFile
Directory
ExistingFiles
DirectoryOnly
Definition at line 83 of file qfiledialog.h.
 { AnyFile, ExistingFile, Directory, ExistingFiles, DirectoryOnly };
Option
enum QFileDialog::Option
Some platforms allow the user to set a different icon.
ShowDirsOnly Only show directories in the file dialog. By default both files and directories are shown. (Valid only in the Directory file mode.)
DontResolveSymlinks Don't resolve symlinks in the file dialog. By default symlinks are resolved.
DontConfirmOverwrite Don't ask for confirmation if an existing file is selected. By default confirmation is requested.
DontUseNativeDialog Don't use the native file dialog. By default, the native file dialog is used unless you use a subclass of QFileDialog that contains the Q_OBJECT macro.
ReadOnly Indicates that the model is readonly.
HideNameFilterDetails Indicates if the file name filter details are hidden or not.
DontUseSheet In previous versions of Qt, the static functions would create a sheet by default if the static function was given a parent. This is no longer supported and does nothing in Qt 4.5, The static functions will always be an application modal dialog. If you want to use sheets, use QFileDialog::open() instead.
DontUseCustomDirectoryIcons Always use the default directory icon. Custom icon lookup cause a big performance impact over network or removable drives. Setting this will affect the behavior of the icon provider. This enum value was added in Qt 4.8.6.
Enumerator
ShowDirsOnly
DontResolveSymlinks
DontConfirmOverwrite
DontUseSheet
DontUseNativeDialog
ReadOnly
HideNameFilterDetails
DontUseCustomDirectoryIcons
Definition at line 88 of file qfiledialog.h.
     {
         ShowDirsOnly                = 0x00000001,
         DontResolveSymlinks         = 0x00000002,
         DontConfirmOverwrite        = 0x00000004,
         DontUseSheet                = 0x00000008,
         DontUseNativeDialog         = 0x00000010,
         ReadOnly                    = 0x00000020,
         HideNameFilterDetails       = 0x00000040,
         DontUseCustomDirectoryIcons = 0x00000080
     };
ViewMode
enum QFileDialog::ViewMode
This enum describes the view mode of the file dialog; i.
e. what information about each file will be displayed.
Detail Displays an icon, a name, and details for each item in the directory.
List Displays only an icon and a name for each item in the directory.
See also
setViewMode()
Enumerator
Detail
List
Definition at line 82 of file qfiledialog.h.
 { Detail, List };
Constructors and Destructors
QFileDialog() [1/3]
QFileDialog::QFileDialog (QWidget * parent, Qt::WindowFlags f)
Constructs a file dialog with the given parent and widget flags.
Definition at line 349 of file qfiledialog.cpp.
     : QDialog(*new QFileDialogPrivate, parent, f)
 {
     Q_D(QFileDialog);
     d->init();
     d->lineEdit()->selectAll();
 }
QFileDialog() [2/3]
QFileDialog::QFileDialog (QWidget * parent = 0, const QString & caption = QString(), const QString & directory = QString(), const QString & filter = QString()) explicit
Constructs a file dialog with the given parent and caption that initially displays the contents of the specified directory.
The contents of the directory are filtered before being shown in the dialog, using a semicolon-separated list of filters specified by filter.
Definition at line 364 of file qfiledialog.cpp.
     : QDialog(*new QFileDialogPrivate, parent, 0)
 {
     Q_D(QFileDialog);
     d->init(directory, filter, caption);
     d->lineEdit()->selectAll();
 }
~QFileDialog()
QFileDialog::~QFileDialog ()
Destroys the file dialog.
Definition at line 392 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
 #ifndef QT_NO_SETTINGS
     QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
     settings.beginGroup(QLatin1String("Qt"));
     settings.setValue(QLatin1String("filedialog"), saveState());
 #endif
     d->deleteNativeDialog_sys();
 }
QFileDialog() [3/3]
QFileDialog::QFileDialog (const QFileDialogArgs & args) protected
Warning
This function is not part of the public interface.
Definition at line 378 of file qfiledialog.cpp.
     : QDialog(*new QFileDialogPrivate, args.parent, 0)
 {
     Q_D(QFileDialog);
     d->init(args.directory, args.filter, args.caption);
     setFileMode(args.mode);
     setOptions(args.options);
     selectFile(args.selection);
     d->lineEdit()->selectAll();
 }
Functions
accept()
void QFileDialog::accept () protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 2256 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     QStringList files = selectedFiles();
     if (files.isEmpty())
         return;
     if (d->nativeDialogInUse){
         d->emitFilesSelected(files);
         QDialog::accept();
         return;
     }
     QString lineEditText = d->lineEdit()->text();
     // "hidden feature" type .. and then enter, and it will move up a dir
     // special case for ".."
     if (lineEditText == QLatin1String("..")) {
         d->_q_navigateToParent();
         bool block = d->qFileDialogUi->fileNameEdit->blockSignals(true);
         d->lineEdit()->selectAll();
         d->qFileDialogUi->fileNameEdit->blockSignals(block);
         return;
     }
     switch (d->fileMode) {
     case DirectoryOnly:
     case Directory: {
         QString fn = files.first();
         QFileInfo info(fn);
         if (!info.exists())
             info = QFileInfo(d->getEnvironmentVariable(fn));
         if (!info.exists()) {
 #ifndef QT_NO_MESSAGEBOX
             QString message = tr("%1\nDirectory not found.\nPlease verify the "
                                           "correct directory name was given.");
             QMessageBox::warning(this, windowTitle(), message.arg(info.fileName()));
 #endif // QT_NO_MESSAGEBOX
             return;
         }
         if (info.isDir()) {
             d->emitFilesSelected(files);
             QDialog::accept();
         }
         return;
     }
     case AnyFile: {
         QString fn = files.first();
         QFileInfo info(fn);
         if (info.isDir()) {
             setDirectory(info.absoluteFilePath());
             return;
         }
         if (!info.exists()) {
             int maxNameLength = d->maxNameLength(info.path());
             if (maxNameLength >= 0 && info.fileName().length() > maxNameLength)
                 return;
         }
         // check if we have to ask for permission to overwrite the file
         if (!info.exists() || !confirmOverwrite() || acceptMode() == AcceptOpen) {
             d->emitFilesSelected(QStringList(fn));
             QDialog::accept();
 #ifndef QT_NO_MESSAGEBOX
         } else {
             if (QMessageBox::warning(this, windowTitle(),
                                      tr("%1 already exists.\nDo you want to replace it?")
                                      .arg(info.fileName()),
                                      QMessageBox::Yes | QMessageBox::No, QMessageBox::No)
                     == QMessageBox::Yes) {
                 d->emitFilesSelected(QStringList(fn));
                 QDialog::accept();
             }
 #endif
         }
         return;
     }
     case ExistingFile:
     case ExistingFiles:
         for (int i = 0; i < files.count(); ++i) {
             QFileInfo info(files.at(i));
             if (!info.exists())
                 info = QFileInfo(d->getEnvironmentVariable(files.at(i)));
             if (!info.exists()) {
 #ifndef QT_NO_MESSAGEBOX
                 QString message = tr("%1\nFile not found.\nPlease verify the "
                                      "correct file name was given.");
                 QMessageBox::warning(this, windowTitle(), message.arg(info.fileName()));
 #endif // QT_NO_MESSAGEBOX
                 return;
             }
             if (info.isDir()) {
                 setDirectory(info.absoluteFilePath());
                 d->lineEdit()->clear();
                 return;
             }
         }
         d->emitFilesSelected(files);
         QDialog::accept();
         return;
     }
 }
acceptMode()
AcceptMode QFileDialog::acceptMode () const
Referenced by QFileDialogPrivate::select().
changeEvent()
void QFileDialog::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 544 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     if (e->type() == QEvent::LanguageChange) {
         d->retranslateWindowTitle();
         d->retranslateStrings();
     }
     QDialog::changeEvent(e);
 }
confirmOverwrite()
bool QFileDialog::confirmOverwrite () const
Referenced by setConfirmOverwrite().
currentChanged
void QFileDialog::currentChanged (const QString & path) signal
When the current file changes, this signal is emitted with the new file name as the path parameter.
See also
filesSelected()
defaultSuffix()
QString QFileDialog::defaultSuffix () const
Referenced by setDefaultSuffix().
directory()
QDir QFileDialog::directory () const
Returns the directory currently being displayed in the dialog.
Definition at line 876 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     return QDir(d->nativeDialogInUse ? d->directory_sys() : d->rootPath());
 }
directoryEntered
void QFileDialog::directoryEntered (const QString & directory) signal
This signal is emitted when the user enters a directory.
Since
4.3
done()
void QFileDialog::done (int result) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 2238 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     QDialog::done(result);
     if (d->receiverToDisconnectOnClose) {
         disconnect(this, d->signalToDisconnectOnClose,
                    d->receiverToDisconnectOnClose, d->memberToDisconnectOnClose);
         d->receiverToDisconnectOnClose = 0;
     }
     d->memberToDisconnectOnClose.clear();
     d->signalToDisconnectOnClose.clear();
 }
fileMode()
FileMode QFileDialog::fileMode () const
Referenced by setFileMode().
fileSelected
void QFileDialog::fileSelected (const QString & file) signal
When the selection changes and the dialog is accepted, this signal is emitted with the (possibly empty) selected file.
See also
currentChanged(), QDialog::Accepted
filesSelected
void QFileDialog::filesSelected (const QStringList & selected) signal
When the selection changes and the dialog is accepted, this signal is emitted with the (possibly empty) list of selected files.
See also
currentChanged(), QDialog::Accepted
filter()
QDir::Filters QFileDialog::filter () const
Returns the filter that is used when displaying files.
Since
4.4
See also
setFilter()
Definition at line 1336 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     return d->model->filter();
 }
filters()
QStringList QFileDialog::filters () const
Use nameFilters() instead.
Definition at line 1243 of file qfiledialog.cpp.
 {
     return nameFilters();
 }
filterSelected
void QFileDialog::filterSelected (const QString & filter) signal
This signal is emitted when the user selects a filter.
Since
4.3
getExistingDirectory()
QString QFileDialog::getExistingDirectory (QWidget * parent = 0, const QString & caption = QString(), const QString & dir = QString(), Options options = ShowDirsOnly) static
This is a convenience static function that will return an existing directory selected by the user.
QString dir = QFileDialog::getExistingDirectory(this, tr("Open Directory"),
                                                "/home",
                                                QFileDialog::ShowDirsOnly
                                                | QFileDialog::DontResolveSymlinks);
This function creates a modal file dialog with the given parent widget. If parent is not 0, the dialog will be shown centered over the parent widget.
The dialog's working directory is set to dir, and the caption is set to caption. Either of these may be an empty string in which case the current directory and a default caption will be used respectively.
The options argument holds various options about how to run the dialog, see the QFileDialog::Option enum for more information on the flags you can pass. To ensure a native file dialog, QFileDialog::ShowDirsOnly must be set.
On Windows, Mac OS X and Symbian^3, this static function will use the native file dialog and not a QFileDialog. On Windows CE, if the device has no native file dialog, a QFileDialog will be used.
On Unix/X11, the normal behavior of the file dialog is to resolve and follow symlinks. For example, if /usr/tmp is a symlink to /var/tmp, the file dialog will change to /var/tmp after entering /usr/tmp. If options includes DontResolveSymlinks, the file dialog will treat symlinks as regular directories.
On Windows the dialog will spin a blocking modal event loop that will not dispatch any QTimers, and if parent is not 0 then it will position the dialog just below the parent's title bar.
On Symbian^3 the options parameter is only used to define if the native file dialog is used.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QFileDialog constructors.
See also
getOpenFileName(), getOpenFileNames(), getSaveFileName()
Definition at line 2154 of file qfiledialog.cpp.
 {
     if (qt_filedialog_existing_directory_hook && !(options & DontUseNativeDialog))
         return qt_filedialog_existing_directory_hook(parent, caption, dir, options);
 #if defined(Q_WS_S60)
     if (QSysInfo::s60Version() > QSysInfo::SV_S60_5_0 && !(options & DontUseNativeDialog))
         return qtSymbianGetExistingDirectory(caption, dir);
 #endif
     QFileDialogArgs args;
     args.parent = parent;
     args.caption = caption;
     args.directory = QFileDialogPrivate::workingDirectory(dir);
     args.mode = (options & ShowDirsOnly ? DirectoryOnly : Directory);
     args.options = options;
 #if defined(Q_WS_WIN)
     if (qt_use_native_dialogs && !(args.options & DontUseNativeDialog) && (options & ShowDirsOnly)
 #if defined(Q_WS_WINCE)
         && qt_priv_ptr_valid
 #endif
         ) {
         return qt_win_get_existing_directory(args);
     }
 #endif
     // create a qt dialog
     QFileDialog dialog(args);
     if (dialog.exec() == QDialog::Accepted) {
         return dialog.selectedFiles().value(0);
     }
     return QString();
 }
getOpenFileName()
QString QFileDialog::getOpenFileName (QWidget * parent = 0, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = 0, Options options = 0) static
This is a convenience static function that returns an existing file selected by the user.
If the user presses Cancel, it returns a null string.
QString fileName = QFileDialog::getOpenFileName(this, tr("Open File"),
                                                "/home",
                                                tr("Images (*.png *.xpm *.jpg)"));
The function creates a modal file dialog with the given parent widget. If parent is not 0, the dialog will be shown centered over the parent widget.
The file dialog's working directory will be set to dir. If dir includes a file name, the file will be selected. Only files that match the given filter are shown. The filter selected is set to selectedFilter. The parameters dir, selectedFilter, and filter may be empty strings. If you want multiple filters, separate them with ';;', for example:
"Images (*.png *.xpm *.jpg);;Text files (*.txt);;XML files (*.xml)"
The options argument holds various options about how to run the dialog, see the QFileDialog::Option enum for more information on the flags you can pass.
The dialog's caption is set to caption. If caption is not specified then a default caption will be used.
On Windows, Mac OS X and Symbian^3, this static function will use the native file dialog and not a QFileDialog.
On Windows the dialog will spin a blocking modal event loop that will not dispatch any QTimers, and if parent is not 0 then it will position the dialog just below the parent's title bar.
On Unix/X11, the normal behavior of the file dialog is to resolve and follow symlinks. For example, if /usr/tmp is a symlink to /var/tmp, the file dialog will change to /var/tmp after entering /usr/tmp. If options includes DontResolveSymlinks, the file dialog will treat symlinks as regular directories.
On Symbian^3 the parameter selectedFilter has no meaning and the options parameter is only used to define if the native file dialog is used.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QFileDialog constructors.
See also
getOpenFileNames(), getSaveFileName(), getExistingDirectory()
Definition at line 1884 of file qfiledialog.cpp.
 {
     if (qt_filedialog_open_filename_hook && !(options & DontUseNativeDialog))
         return qt_filedialog_open_filename_hook(parent, caption, dir, filter, selectedFilter, options);
 #if defined(Q_WS_S60)
     if (QSysInfo::s60Version() > QSysInfo::SV_S60_5_0 && !(options & DontUseNativeDialog))
         return qtSymbianGetOpenFileName(caption, dir, filter);
 #endif
     QFileDialogArgs args;
     args.parent = parent;
     args.caption = caption;
     args.directory = QFileDialogPrivate::workingDirectory(dir);
     args.selection = QFileDialogPrivate::initialSelection(dir);
     args.filter = filter;
     args.mode = ExistingFile;
     args.options = options;
 #if defined(Q_WS_WIN)
     if (qt_use_native_dialogs && !(args.options & DontUseNativeDialog)) {
         return qt_win_get_open_file_name(args, &(args.directory), selectedFilter);
     }
 #endif
     // create a qt dialog
     QFileDialog dialog(args);
     if (selectedFilter && !selectedFilter->isEmpty())
         dialog.selectNameFilter(*selectedFilter);
     if (dialog.exec() == QDialog::Accepted) {
         if (selectedFilter)
             *selectedFilter = dialog.selectedFilter();
         return dialog.selectedFiles().value(0);
     }
     return QString();
 }
getOpenFileNames()
QStringList QFileDialog::getOpenFileNames (QWidget * parent = 0, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = 0, Options options = 0) static
This is a convenience static function that will return one or more existing files selected by the user.
QStringList files = QFileDialog::getOpenFileNames(
                        this,
                        "Select one or more files to open",
                        "/home",
                        "Images (*.png *.xpm *.jpg)");
This function creates a modal file dialog with the given parent widget. If parent is not 0, the dialog will be shown centered over the parent widget.
The file dialog's working directory will be set to dir. If dir includes a file name, the file will be selected. The filter is set to filter so that only those files which match the filter are shown. The filter selected is set to selectedFilter. The parameters dir, selectedFilter and filter may be empty strings. If you need multiple filters, separate them with ';;', for instance:
"Images (*.png *.xpm *.jpg);;Text files (*.txt);;XML files (*.xml)"
The dialog's caption is set to caption. If caption is not specified then a default caption will be used.
On Windows, Mac OS X and Symbian^3, this static function will use the native file dialog and not a QFileDialog.
On Windows the dialog will spin a blocking modal event loop that will not dispatch any QTimers, and if parent is not 0 then it will position the dialog just below the parent's title bar.
On Unix/X11, the normal behavior of the file dialog is to resolve and follow symlinks. For example, if /usr/tmp is a symlink to /var/tmp, the file dialog will change to /var/tmp after entering /usr/tmp. The options argument holds various options about how to run the dialog, see the QFileDialog::Option enum for more information on the flags you can pass.
Note
If you want to iterate over the list of files, you should iterate over a copy. For example:
QStringList list = files;
QStringList::Iterator it = list.begin();
while(it != list.end()) {
    myProcessing(*it);
    ++it;
}
On Symbian^3 the parameter selectedFilter has no meaning and the options parameter is only used to define if the native file dialog is used. On Symbian^3, this function can only return a single filename.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QFileDialog constructors.
See also
getOpenFileName(), getSaveFileName(), getExistingDirectory()
Definition at line 1976 of file qfiledialog.cpp.
 {
     if (qt_filedialog_open_filenames_hook && !(options & DontUseNativeDialog))
         return qt_filedialog_open_filenames_hook(parent, caption, dir, filter, selectedFilter, options);
 #if defined(Q_WS_S60)
     if (QSysInfo::s60Version() > QSysInfo::SV_S60_5_0 && !(options & DontUseNativeDialog))
         return qtSymbianGetOpenFileNames(caption, dir, filter);
 #endif
     QFileDialogArgs args;
     args.parent = parent;
     args.caption = caption;
     args.directory = QFileDialogPrivate::workingDirectory(dir);
     args.selection = QFileDialogPrivate::initialSelection(dir);
     args.filter = filter;
     args.mode = ExistingFiles;
     args.options = options;
 #if defined(Q_WS_WIN)
     if (qt_use_native_dialogs && !(args.options & DontUseNativeDialog)) {
         return qt_win_get_open_file_names(args, &(args.directory), selectedFilter);
     }
 #endif
     // create a qt dialog
     QFileDialog dialog(args);
     if (selectedFilter && !selectedFilter->isEmpty())
         dialog.selectNameFilter(*selectedFilter);
     if (dialog.exec() == QDialog::Accepted) {
         if (selectedFilter)
             *selectedFilter = dialog.selectedFilter();
         return dialog.selectedFiles();
     }
     return QStringList();
 }
getSaveFileName()
QString QFileDialog::getSaveFileName (QWidget * parent = 0, const QString & caption = QString(), const QString & dir = QString(), const QString & filter = QString(), QString * selectedFilter = 0, Options options = 0) static
This is a convenience static function that will return a file name selected by the user.
The file does not have to exist.
It creates a modal file dialog with the given parent widget. If parent is not 0, the dialog will be shown centered over the parent widget.
QString fileName = QFileDialog::getSaveFileName(this, tr("Save File"),
                           "/home/jana/untitled.png",
                           tr("Images (*.png *.xpm *.jpg)"));
The file dialog's working directory will be set to dir. If dir includes a file name, the file will be selected. Only files that match the filter are shown. The filter selected is set to selectedFilter. The parameters dir, selectedFilter, and filter may be empty strings. Multiple filters are separated with ';;'. For instance:
"Images (*.png *.xpm *.jpg);;Text files (*.txt);;XML files (*.xml)"
The options argument holds various options about how to run the dialog, see the QFileDialog::Option enum for more information on the flags you can pass.
The default filter can be chosen by setting selectedFilter to the desired value.
The dialog's caption is set to caption. If caption is not specified, a default caption will be used.
On Windows, Mac OS X and Symbian^3, this static function will use the native file dialog and not a QFileDialog.
On Windows the dialog will spin a blocking modal event loop that will not dispatch any QTimers, and if parent is not 0 then it will position the dialog just below the parent's title bar. On Mac OS X, with its native file dialog, the filter argument is ignored.
On Unix/X11, the normal behavior of the file dialog is to resolve and follow symlinks. For example, if /usr/tmp is a symlink to /var/tmp, the file dialog will change to /var/tmp after entering /usr/tmp. If options includes DontResolveSymlinks the file dialog will treat symlinks as regular directories.
On Symbian^3 the parameters filter and selectedFilter have no meaning. The options parameter is only used to define if the native file dialog is used.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QFileDialog constructors.
See also
getOpenFileName(), getOpenFileNames(), getExistingDirectory()
Definition at line 2070 of file qfiledialog.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_btnBrowseClicked(), and QPrintPreviewDialogPrivate::_q_print().
 {
     if (qt_filedialog_save_filename_hook && !(options & DontUseNativeDialog))
         return qt_filedialog_save_filename_hook(parent, caption, dir, filter, selectedFilter, options);
 #if defined(Q_WS_S60)
     if (QSysInfo::s60Version() > QSysInfo::SV_S60_5_0 && !(options & DontUseNativeDialog))
         return qtSymbianGetSaveFileName(caption, dir);
 #endif
     QFileDialogArgs args;
     args.parent = parent;
     args.caption = caption;
     args.directory = QFileDialogPrivate::workingDirectory(dir);
     args.selection = QFileDialogPrivate::initialSelection(dir);
     args.filter = filter;
     args.mode = AnyFile;
     args.options = options;
 #if defined(Q_WS_WIN)
     if (qt_use_native_dialogs && !(args.options & DontUseNativeDialog)) {
         return qt_win_get_save_file_name(args, &(args.directory), selectedFilter);
     }
 #endif
     // create a qt dialog
     QFileDialog dialog(args);
     dialog.setAcceptMode(AcceptSave);
     if (selectedFilter && !selectedFilter->isEmpty())
         dialog.selectNameFilter(*selectedFilter);
     if (dialog.exec() == QDialog::Accepted) {
         if (selectedFilter)
             *selectedFilter = dialog.selectedFilter();
         return dialog.selectedFiles().value(0);
     }
     return QString();
 }
history()
QStringList QFileDialog::history () const
Returns the browsing history of the filedialog as a list of paths.
Definition at line 1668 of file qfiledialog.cpp.
Referenced by restoreState(), and saveState().
 {
     Q_D(const QFileDialog);
     QStringList currentHistory = d->qFileDialogUi->lookInCombo->history();
     //On windows the popup display the "C:\", convert to nativeSeparators
     QString newHistory = QDir::toNativeSeparators(d->rootIndex().data(QFileSystemModel::FilePathRole).toString());
     if (!currentHistory.contains(newHistory))
         currentHistory << newHistory;
     return currentHistory;
 }
iconProvider()
QFileIconProvider * QFileDialog::iconProvider () const
Returns the icon provider used by the filedialog.
Definition at line 1724 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     return d->model->iconProvider();
 }
isNameFilterDetailsVisible()
bool QFileDialog::isNameFilterDetailsVisible () const
Definition at line 1146 of file qfiledialog.cpp.
 {
     return !testOption(HideNameFilterDetails);
 }
isReadOnly()
bool QFileDialog::isReadOnly () const
Definition at line 1567 of file qfiledialog.cpp.
 {
     return testOption(ReadOnly);
 }
itemDelegate()
QAbstractItemDelegate * QFileDialog::itemDelegate () const
Returns the item delegate used to render the items in the views in the filedialog.
Definition at line 1704 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     return d->qFileDialogUi->listView->itemDelegate();
 }
labelText()
QString QFileDialog::labelText (DialogLabel label) const
Returns the text shown in the filedialog in the specified label.
Definition at line 1768 of file qfiledialog.cpp.
 {
     QPushButton *button;
     Q_D(const QFileDialog);
     switch (label) {
     case LookIn:
         return d->qFileDialogUi->lookInLabel->text();
     case FileName:
         return d->qFileDialogUi->fileNameLabel->text();
     case FileType:
         return d->qFileDialogUi->fileTypeLabel->text();
     case Accept:
         if (acceptMode() == AcceptOpen)
             button = d->qFileDialogUi->buttonBox->button(QDialogButtonBox::Open);
         else
             button = d->qFileDialogUi->buttonBox->button(QDialogButtonBox::Save);
         if (button)
             return button->text();
     case Reject:
         button = d->qFileDialogUi->buttonBox->button(QDialogButtonBox::Cancel);
         if (button)
             return button->text();
     }
     return QString();
 }
nameFilters()
QStringList QFileDialog::nameFilters () const
Returns the file type filters that are in operation on this file dialog.
Since
4.4
Definition at line 1229 of file qfiledialog.cpp.
 {
     return d_func()->nameFilters;
 }
open()
void QFileDialog::open (QObject * receiver, const char * member)
This function connects one of its signals to the slot specified by receiver and member.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
The specific signal depends is filesSelected() if fileMode is ExistingFiles and fileSelected() if fileMode is anything else.
The signal will be disconnected from the slot when the dialog is closed.
Definition at line 763 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     const char *signal = (fileMode() == ExistingFiles) ? SIGNAL(filesSelected(QStringList))
                                                        : SIGNAL(fileSelected(QString));
     connect(this, signal, receiver, member);
     d->signalToDisconnectOnClose = signal;
     d->receiverToDisconnectOnClose = receiver;
     d->memberToDisconnectOnClose = member;
     QDialog::open();
 }
options()
Options QFileDialog::options () const
Referenced by setOptions().
proxyModel()
QAbstractProxyModel * QFileDialog::proxyModel () const
Returns the proxy model used by the file dialog.
By default no proxy is set.
See also
setProxyModel()
Definition at line 2617 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     return d->proxyModel;
 }
resolveSymlinks()
bool QFileDialog::resolveSymlinks () const
Referenced by setResolveSymlinks().
restoreState()
bool QFileDialog::restoreState (const QByteArray & state)
Restores the dialogs's layout, history and current directory to the state specified.
Since
4.3
Typically this is used in conjunction with QSettings to restore the size from a past session.
Returns false if there are errors
Definition at line 481 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     int version = 3;
     QByteArray sd = state;
     QDataStream stream(&sd, QIODevice::ReadOnly);
     if (stream.atEnd())
         return false;
     QByteArray splitterState;
     QByteArray headerData;
     QList<QUrl> bookmarks;
     QStringList history;
     QString currentDirectory;
     qint32 marker;
     qint32 v;
     qint32 viewMode;
     stream >> marker;
     stream >> v;
     if (marker != QFileDialogMagic || v != version)
         return false;
     stream >> splitterState
            >> bookmarks
            >> history
            >> currentDirectory
            >> headerData
            >> viewMode;
     if (!d->qFileDialogUi->splitter->restoreState(splitterState))
         return false;
     QList<int> list = d->qFileDialogUi->splitter->sizes();
     if (list.count() >= 2 && list.at(0) == 0 && list.at(1) == 0) {
         for (int i = 0; i < list.count(); ++i)
             list[i] = d->qFileDialogUi->splitter->widget(i)->sizeHint().width();
         d->qFileDialogUi->splitter->setSizes(list);
     }
     d->qFileDialogUi->sidebar->setUrls(bookmarks);
     while (history.count() > 5)
         history.pop_front();
     setHistory(history);
     setDirectory(lastVisitedDir()->isEmpty() ? currentDirectory : *lastVisitedDir());
     QHeaderView *headerView = d->qFileDialogUi->treeView->header();
     if (!headerView->restoreState(headerData))
         return false;
     QList<QAction*> actions = headerView->actions();
     QAbstractItemModel *abstractModel = d->model;
 #ifndef QT_NO_PROXYMODEL
     if (d->proxyModel)
         abstractModel = d->proxyModel;
 #endif
     int total = qMin(abstractModel->columnCount(QModelIndex()), actions.count() + 1);
     for (int i = 1; i < total; ++i)
         actions.at(i - 1)->setChecked(!headerView->isSectionHidden(i));
     setViewMode(ViewMode(viewMode));
     return true;
 }
saveState()
QByteArray QFileDialog::saveState () const
Saves the state of the dialog's layout, history and current directory.
Since
4.3
Typically this is used in conjunction with QSettings to remember the size for a future session. A version number is stored as part of the data.
Definition at line 451 of file qfiledialog.cpp.
Referenced by ~QFileDialog().
 {
     Q_D(const QFileDialog);
     int version = 3;
     QByteArray data;
     QDataStream stream(&data, QIODevice::WriteOnly);
     stream << qint32(QFileDialogMagic);
     stream << qint32(version);
     stream << d->qFileDialogUi->splitter->saveState();
     stream << d->qFileDialogUi->sidebar->urls();
     stream << history();
     stream << *lastVisitedDir();
     stream << d->qFileDialogUi->treeView->header()->saveState();
     stream << qint32(viewMode());
     return data;
 }
selectedFiles()
QStringList QFileDialog::selectedFiles () const
Returns a list of strings containing the absolute paths of the selected files in the dialog.
If no files are selected, or the mode is not ExistingFiles or ExistingFile, selectedFiles() contains the current path in the viewport.
See also
selectedNameFilter(), selectFile()
Definition at line 1052 of file qfiledialog.cpp.
Referenced by getExistingDirectory(), getOpenFileName(), getOpenFileNames(), and getSaveFileName().
 {
     Q_D(const QFileDialog);
     if (d->nativeDialogInUse)
         return d->addDefaultSuffixToFiles(d->selectedFiles_sys());
     QModelIndexList indexes = d->qFileDialogUi->listView->selectionModel()->selectedRows();
     QStringList files;
     for (int i = 0; i < indexes.count(); ++i)
         files.append(indexes.at(i).data(QFileSystemModel::FilePathRole).toString());
     if (files.isEmpty() && !d->lineEdit()->text().isEmpty())
         files = d->typedFiles();
     if (files.isEmpty() && !(d->fileMode == ExistingFile || d->fileMode == ExistingFiles))
         files.append(d->rootIndex().data(QFileSystemModel::FilePathRole).toString());
     return files;
 }
selectedFilter()
QString QFileDialog::selectedFilter () const
Use selectedNameFilter() instead.
Definition at line 1321 of file qfiledialog.cpp.
Referenced by getOpenFileName(), getOpenFileNames(), and getSaveFileName().
 {
     return selectedNameFilter();
 }
selectedNameFilter()
QString QFileDialog::selectedNameFilter () const
Returns the filter that the user selected in the file dialog.
Since
4.4
See also
selectedFiles()
Definition at line 1304 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     if (d->nativeDialogInUse)
         return d->selectedNameFilter_sys();
     return d->qFileDialogUi->fileTypeCombo->currentText();
 }
selectFile()
void QFileDialog::selectFile (const QString & filename)
Selects the given filename in the file dialog.
See also
selectedFiles()
Definition at line 887 of file qfiledialog.cpp.
Referenced by QFileDialog().
 {
     Q_D(QFileDialog);
     if (filename.isEmpty())
         return;
     if (d->nativeDialogInUse){
         d->selectFile_sys(filename);
         return;
     }
     if (!QDir::isRelativePath(filename)) {
         QFileInfo info(filename);
         QString filenamePath = info.absoluteDir().path();
         if (d->model->rootPath() != filenamePath)
             setDirectory(filenamePath);
     }
     QModelIndex index = d->model->index(filename);
     QString file;
     if (!index.isValid()) {
         // save as dialog where we want to input a default value
         QString text = filename;
         if (QFileInfo(filename).isAbsolute()) {
             QString current = d->rootPath();
             text.remove(current);
             if (text.at(0) == QDir::separator()
 #ifdef Q_OS_WIN
                 //On Windows both cases can happen
                 || text.at(0) == QLatin1Char('/')
 #endif
                 )
                 text = text.remove(0,1);
         }
         file = text;
     } else {
         file = index.data().toString();
     }
     d->qFileDialogUi->listView->selectionModel()->clear();
     if (!isVisible() || !d->lineEdit()->hasFocus())
         d->lineEdit()->setText(file);
 }
selectFilter()
void QFileDialog::selectFilter (const QString & filter)
Use selectNameFilter() instead.
Definition at line 1289 of file qfiledialog.cpp.
 {
     selectNameFilter(filter);
 }
selectNameFilter()
void QFileDialog::selectNameFilter (const QString & filter)
Sets the current file type filter.
Since
4.4
Multiple filters can be passed in filter by separating them with semicolons or spaces.
See also
setNameFilter(), setNameFilters(), selectedNameFilter()
Definition at line 1259 of file qfiledialog.cpp.
Referenced by getOpenFileName(), getOpenFileNames(), and getSaveFileName().
 {
     Q_D(QFileDialog);
     if (d->nativeDialogInUse) {
         d->selectNameFilter_sys(filter);
         return;
     }
     int i = -1;
     if (testOption(HideNameFilterDetails)) {
         const QStringList filters = qt_strip_filters(qt_make_filter_list(filter));
         if (!filters.isEmpty())
             i = d->qFileDialogUi->fileTypeCombo->findText(filters.first());
     } else {
         i = d->qFileDialogUi->fileTypeCombo->findText(filter);
     }
     if (i >= 0) {
         d->qFileDialogUi->fileTypeCombo->setCurrentIndex(i);
         d->_q_useNameFilter(d->qFileDialogUi->fileTypeCombo->currentIndex());
     }
 }
setAcceptMode()
void QFileDialog::setAcceptMode (QFileDialog::AcceptMode mode)
Definition at line 1477 of file qfiledialog.cpp.
Referenced by getSaveFileName().
 {
     Q_D(QFileDialog);
     d->acceptMode = mode;
     bool directoryMode = (d->fileMode == Directory || d->fileMode == DirectoryOnly);
     QDialogButtonBox::StandardButton button = (mode == AcceptOpen ? QDialogButtonBox::Open : QDialogButtonBox::Save);
     d->qFileDialogUi->buttonBox->setStandardButtons(button | QDialogButtonBox::Cancel);
     d->qFileDialogUi->buttonBox->button(button)->setEnabled(false);
     d->_q_updateOkButton();
     if (mode == AcceptOpen && directoryMode)
         setLabelText(Accept, tr("&Choose"));
     else
         setLabelText(Accept, (mode == AcceptOpen ? tr("&Open") : tr("&Save")));
     if (mode == AcceptSave) {
         d->qFileDialogUi->lookInCombo->setEditable(false);
     }
     d->retranslateWindowTitle();
 #if defined(Q_WS_MAC)
     d->deleteNativeDialog_sys();
     setAttribute(Qt::WA_DontShowOnScreen, false);
 #endif
 }
setConfirmOverwrite()
void QFileDialog::setConfirmOverwrite (bool enabled)
Definition at line 1608 of file qfiledialog.cpp.
 {
     setOption(DontConfirmOverwrite, !enabled);
 }
setDefaultSuffix()
void QFileDialog::setDefaultSuffix (const QString & suffix)
Definition at line 1630 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     d->defaultSuffix = suffix;
 }
setDirectory() [1/2]
void QFileDialog::setDirectory (const QString & directory)
Sets the file dialog's current directory.
Definition at line 839 of file qfiledialog.cpp.
Referenced by restoreState().
 {
     Q_D(QFileDialog);
     QString newDirectory = directory;
     QFileInfo info(directory);
     //we remove .. and . from the given path if exist
     if (!directory.isEmpty())
         newDirectory = QDir::cleanPath(directory);
     if (!directory.isEmpty() && newDirectory.isEmpty())
         return;
     d->setLastVisitedDirectory(newDirectory);
     if (d->nativeDialogInUse){
         d->setDirectory_sys(newDirectory);
         return;
     }
     if (d->rootPath() == newDirectory)
         return;
     QModelIndex root = d->model->setRootPath(newDirectory);
     d->qFileDialogUi->newFolderButton->setEnabled(d->model->flags(root) & Qt::ItemIsDropEnabled);
     if (root != d->rootIndex()) {
 #ifndef QT_NO_FSCOMPLETER
     if (directory.endsWith(QLatin1Char('/')))
         d->completer->setCompletionPrefix(newDirectory);
     else
         d->completer->setCompletionPrefix(newDirectory + QLatin1Char('/'));
 #endif
         d->setRootIndex(root);
     }
     d->qFileDialogUi->listView->selectionModel()->clear();
 }
setDirectory() [2/2]
void QFileDialog::setDirectory (const QDir & directory) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 320 of file qfiledialog.h.
 { setDirectory(adirectory.absolutePath()); }
setFileMode()
void QFileDialog::setFileMode (QFileDialog::FileMode mode)
Definition at line 1411 of file qfiledialog.cpp.
Referenced by QFileDialog().
 {
     Q_D(QFileDialog);
     d->fileMode = mode;
     d->retranslateWindowTitle();
     // keep ShowDirsOnly option in sync with fileMode (BTW, DirectoryOnly is obsolete)
     setOption(ShowDirsOnly, mode == DirectoryOnly);
     // set selection mode and behavior
     QAbstractItemView::SelectionMode selectionMode;
     if (mode == QFileDialog::ExistingFiles)
         selectionMode = QAbstractItemView::ExtendedSelection;
     else
         selectionMode = QAbstractItemView::SingleSelection;
     d->qFileDialogUi->listView->setSelectionMode(selectionMode);
     d->qFileDialogUi->treeView->setSelectionMode(selectionMode);
     // set filter
     d->model->setFilter(d->filterForMode(filter()));
     // setup file type for directory
     QString buttonText = (d->acceptMode == AcceptOpen ? tr("&Open") : tr("&Save"));
     if (mode == DirectoryOnly || mode == Directory) {
         d->qFileDialogUi->fileTypeCombo->clear();
         d->qFileDialogUi->fileTypeCombo->addItem(tr("Directories"));
         d->qFileDialogUi->fileTypeCombo->setEnabled(false);
         if (!d->fileNameLabelExplicitlySat){
             setLabelText(FileName, tr("Directory:"));
             d->fileNameLabelExplicitlySat = false;
         }
         buttonText = tr("&Choose");
     } else {
         if (!d->fileNameLabelExplicitlySat){
             setLabelText(FileName, tr("File &name:"));
             d->fileNameLabelExplicitlySat = false;
         }
     }
     setLabelText(Accept, buttonText);
     if (d->nativeDialogInUse){
         d->setFilter_sys();
         return;
     }
     d->qFileDialogUi->fileTypeCombo->setEnabled(!testOption(ShowDirsOnly));
     d->_q_updateOkButton();
 }
setFilter() [1/2]
void QFileDialog::setFilter (const QString & filter)
Use setNameFilter() instead.
Definition at line 1121 of file qfiledialog.cpp.
 {
     setNameFilter(filter);
 }
setFilter() [2/2]
void QFileDialog::setFilter (QDir::Filters filters)
Sets the filter used by the model to filters.
Since
4.4
The filter is used to specify the kind of files that should be shown.
See also
filter()
Definition at line 1354 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     d->model->setFilter(filters);
     if (d->nativeDialogInUse){
         d->setFilter_sys();
         return;
     }
     d->showHiddenAction->setChecked((filters & QDir::Hidden));
 }
setFilters()
void QFileDialog::setFilters (const QStringList & filters)
Use setNameFilters() instead.
Definition at line 1215 of file qfiledialog.cpp.
 {
     setNameFilters(filters);
 }
setHistory()
void QFileDialog::setHistory (const QStringList & paths)
Sets the browsing history of the filedialog to contain the given paths.
Definition at line 1646 of file qfiledialog.cpp.
Referenced by restoreState().
 {
     Q_D(QFileDialog);
     d->qFileDialogUi->lookInCombo->setHistory(paths);
 }
setIconProvider()
void QFileDialog::setIconProvider (QFileIconProvider * provider)
Sets the icon provider used by the filedialog to the specified provider.
Definition at line 1713 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     d->model->setIconProvider(provider);
     //It forces the refresh of all entries in the side bar, then we can get new icons
     d->qFileDialogUi->sidebar->setUrls(d->qFileDialogUi->sidebar->urls());
 }
setItemDelegate()
void QFileDialog::setItemDelegate (QAbstractItemDelegate * delegate)
Sets the item delegate used to render items in the views in the file dialog to the given delegate.
Warning
You should not share the same instance of a delegate between views. Doing so can cause incorrect or unintuitive editing behavior since each view connected to a given delegate may receive the QAbstractItemDelegate::closeEditor() signal, and attempt to access, modify or close an editor that has already been closed.
Note that the model used is QFileSystemModel. It has custom item data roles, which is described by the QFileSystemModel::Roles enum. You can use a QFileIconProvider if you only want custom icons.
See also
itemDelegate(), setIconProvider(), QFileSystemModel
Definition at line 1694 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     d->qFileDialogUi->listView->setItemDelegate(delegate);
     d->qFileDialogUi->treeView->setItemDelegate(delegate);
 }
setLabelText()
void QFileDialog::setLabelText (DialogLabel label, const QString & text)
Sets the text shown in the filedialog in the specified label.
Definition at line 1733 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     QPushButton *button;
     switch (label) {
     case LookIn:
         d->qFileDialogUi->lookInLabel->setText(text);
         break;
     case FileName:
         d->qFileDialogUi->fileNameLabel->setText(text);
         d->fileNameLabelExplicitlySat = true;
         break;
     case FileType:
         d->qFileDialogUi->fileTypeLabel->setText(text);
         break;
     case Accept:
         d->acceptLabel = text;
         if (acceptMode() == AcceptOpen)
             button = d->qFileDialogUi->buttonBox->button(QDialogButtonBox::Open);
         else
             button = d->qFileDialogUi->buttonBox->button(QDialogButtonBox::Save);
         if (button)
             button->setText(text);
         break;
     case Reject:
         button = d->qFileDialogUi->buttonBox->button(QDialogButtonBox::Cancel);
         if (button)
             button->setText(text);
         break;
     }
 }
setNameFilter()
void QFileDialog::setNameFilter (const QString & filter)
Since
4.4
Sets the filter used in the file dialog to the given filter.
If filter contains a pair of parentheses containing one or more of anything*something, separated by spaces, then only the text contained in the parentheses is used as the filter. This means that these calls are all equivalent:
dialog.setNameFilter("All C++ files (*.cpp *.cc *.C *.cxx *.c++)");
dialog.setNameFilter("*.cpp *.cc *.C *.cxx *.c++");
See also
setNameFilters()
Definition at line 1108 of file qfiledialog.cpp.
 {
     setNameFilters(qt_make_filter_list(filter));
 }
setNameFilterDetailsVisible()
void QFileDialog::setNameFilterDetailsVisible (bool enabled)
Definition at line 1141 of file qfiledialog.cpp.
 {
     setOption(HideNameFilterDetails, !enabled);
 }
setNameFilters()
void QFileDialog::setNameFilters (const QStringList & filters)
Sets the filters used in the file dialog.
Since
4.4
QStringList filters;
filters << "Image files (*.png *.xpm *.jpg)"
        << "Text files (*.txt)"
        << "Any files (*)";
QFileDialog dialog(this);
dialog.setNameFilters(filters);
dialog.exec();
Definition at line 1180 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     d->defaultFileTypes = (filters == QStringList(QFileDialog::tr("All Files (*)")));
     QStringList cleanedFilters;
     for (int i = 0; i < filters.count(); ++i) {
         cleanedFilters << filters[i].simplified();
     }
     d->nameFilters = cleanedFilters;
     if (d->nativeDialogInUse){
         d->setNameFilters_sys(cleanedFilters);
         return;
     }
     d->qFileDialogUi->fileTypeCombo->clear();
     if (cleanedFilters.isEmpty())
         return;
     if (testOption(HideNameFilterDetails))
         d->qFileDialogUi->fileTypeCombo->addItems(qt_strip_filters(cleanedFilters));
     else
         d->qFileDialogUi->fileTypeCombo->addItems(cleanedFilters);
     d->_q_useNameFilter(0);
 }
setOption()
void QFileDialog::setOption (Option option, bool on = true)
Sets the given option to be enabled if on is true; otherwise, clears the given option.
Since
4.5
See also
options, testOption()
Definition at line 675 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     if (!(d->opts & option) != !on)
         setOptions(d->opts ^ option);
 }
setOptions()
void QFileDialog::setOptions (Options options)
Definition at line 715 of file qfiledialog.cpp.
Referenced by QFileDialog().
 {
     Q_D(QFileDialog);
     Options changed = (options ^ d->opts);
     if (!changed)
         return;
     d->opts = options;
     if (changed & DontResolveSymlinks)
         d->model->setResolveSymlinks(!(options & DontResolveSymlinks));
     if (changed & ReadOnly) {
         bool ro = (options & ReadOnly);
         d->model->setReadOnly(ro);
         d->qFileDialogUi->newFolderButton->setEnabled(!ro);
         d->renameAction->setEnabled(!ro);
         d->deleteAction->setEnabled(!ro);
     }
     if (changed & HideNameFilterDetails)
         setNameFilters(d->nameFilters);
     if (changed & ShowDirsOnly)
         setFilter((options & ShowDirsOnly) ? filter() & ~QDir::Files : filter() | QDir::Files);
     if (changed & DontUseCustomDirectoryIcons)
         iconProvider()->d_ptr->setUseCustomDirectoryIcons(!(options & DontUseCustomDirectoryIcons));
 }
setProxyModel()
void QFileDialog::setProxyModel (QAbstractProxyModel * proxyModel)
Sets the model for the views to the given proxyModel.
Since
4.3
This is useful if you want to modify the underlying model; for example, to add columns, filter data or add drives.
Any existing proxy model will be removed, but not deleted. The file dialog will take ownership of the proxyModel.
See also
proxyModel()
Definition at line 2559 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     if ((!proxyModel && !d->proxyModel)
         || (proxyModel == d->proxyModel))
         return;
     QModelIndex idx = d->rootIndex();
     if (d->proxyModel) {
         disconnect(d->proxyModel, SIGNAL(rowsInserted(QModelIndex,int,int)),
             this, SLOT(_q_rowsInserted(QModelIndex)));
     } else {
         disconnect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
             this, SLOT(_q_rowsInserted(QModelIndex)));
     }
     if (proxyModel != 0) {
         proxyModel->setParent(this);
         d->proxyModel = proxyModel;
         proxyModel->setSourceModel(d->model);
         d->qFileDialogUi->listView->setModel(d->proxyModel);
         d->qFileDialogUi->treeView->setModel(d->proxyModel);
 #ifndef QT_NO_FSCOMPLETER
         d->completer->setModel(d->proxyModel);
         d->completer->proxyModel = d->proxyModel;
 #endif
         connect(d->proxyModel, SIGNAL(rowsInserted(QModelIndex,int,int)),
             this, SLOT(_q_rowsInserted(QModelIndex)));
     } else {
         d->proxyModel = 0;
         d->qFileDialogUi->listView->setModel(d->model);
         d->qFileDialogUi->treeView->setModel(d->model);
 #ifndef QT_NO_FSCOMPLETER
         d->completer->setModel(d->model);
         d->completer->sourceModel = d->model;
         d->completer->proxyModel = 0;
 #endif
         connect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
             this, SLOT(_q_rowsInserted(QModelIndex)));
     }
     QScopedPointer<QItemSelectionModel> selModel(d->qFileDialogUi->treeView->selectionModel());
     d->qFileDialogUi->treeView->setSelectionModel(d->qFileDialogUi->listView->selectionModel());
     d->setRootIndex(idx);
     // reconnect selection
     QItemSelectionModel *selections = d->qFileDialogUi->listView->selectionModel();
     QObject::connect(selections, SIGNAL(selectionChanged(QItemSelection,QItemSelection)),
                      this, SLOT(_q_selectionChanged()));
     QObject::connect(selections, SIGNAL(currentChanged(QModelIndex,QModelIndex)),
                      this, SLOT(_q_currentChanged(QModelIndex)));
 }
setReadOnly()
void QFileDialog::setReadOnly (bool enabled)
Definition at line 1562 of file qfiledialog.cpp.
 {
     setOption(ReadOnly, enabled);
 }
setResolveSymlinks()
void QFileDialog::setResolveSymlinks (bool enabled)
Definition at line 1586 of file qfiledialog.cpp.
 {
     setOption(DontResolveSymlinks, !enabled);
 }
setSidebarUrls()
void QFileDialog::setSidebarUrls (const QList< QUrl > & urls)
Sets the urls that are located in the sidebar.
Since
4.3
For instance:
    QList<QUrl> urls;
    urls << QUrl::fromLocalFile("/home/gvatteka/dev/qt-45")
         << QUrl::fromLocalFile(QDesktopServices::storageLocation(QDesktopServices::MusicLocation));
    QFileDialog dialog;
    dialog.setSidebarUrls(urls);
    dialog.setFileMode(QFileDialog::AnyFile);
    if(dialog.exec()) {
        // ...
    }
The file dialog will then look like this:
See also
sidebarUrls()
Definition at line 420 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     d->qFileDialogUi->sidebar->setUrls(urls);
 }
setViewMode()
void QFileDialog::setViewMode (QFileDialog::ViewMode mode)
Definition at line 1378 of file qfiledialog.cpp.
Referenced by restoreState().
 {
     Q_D(QFileDialog);
     if (mode == Detail)
         d->_q_showDetailsView();
     else
         d->_q_showListView();
 }
setVisible()
void QFileDialog::setVisible (bool visible) virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 780 of file qfiledialog.cpp.
 {
     Q_D(QFileDialog);
     if (visible){
         if (testAttribute(Qt::WA_WState_ExplicitShowHide) && !testAttribute(Qt::WA_WState_Hidden))
             return;
     } else if (testAttribute(Qt::WA_WState_ExplicitShowHide) && testAttribute(Qt::WA_WState_Hidden))
         return;
     if (d->canBeNativeDialog()){
         if (d->setVisible_sys(visible)){
             d->nativeDialogInUse = true;
             // Set WA_DontShowOnScreen so that QDialog::setVisible(visible) below
             // updates the state correctly, but skips showing the non-native version:
             setAttribute(Qt::WA_DontShowOnScreen);
 #ifndef QT_NO_FSCOMPLETER
             //So the completer don't try to complete and therefore to show a popup
             d->completer->setModel(0);
 #endif
         } else {
             d->nativeDialogInUse = false;
             setAttribute(Qt::WA_DontShowOnScreen, false);
 #ifndef QT_NO_FSCOMPLETER
             if (d->proxyModel != 0)
                 d->completer->setModel(d->proxyModel);
             else
                 d->completer->setModel(d->model);
 #endif
         }
     }
     if (!d->nativeDialogInUse)
         d->qFileDialogUi->fileNameEdit->setFocus();
     QDialog::setVisible(visible);
 }
sidebarUrls()
QList< QUrl > QFileDialog::sidebarUrls () const
Since
4.3 Returns a list of urls that are currently in the sidebar
Definition at line 430 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     return d->qFileDialogUi->sidebar->urls();
 }
testOption()
bool QFileDialog::testOption (Option option) const
Returns true if the given option is enabled; otherwise, returns false.
Since
4.5
See also
options, setOption()
Definition at line 693 of file qfiledialog.cpp.
 {
     Q_D(const QFileDialog);
     return (d->opts & option) != 0;
 }
viewMode()
ViewMode QFileDialog::viewMode () const
Referenced by restoreState(), saveState(), and setViewMode().
Properties
acceptMode
QFileDialog::AcceptMode QFileDialog::acceptMode private
the accept mode of the dialog
The action mode defines whether the dialog is for opening or saving files.
By default, this property is set to AcceptOpen.
See also
AcceptMode
Definition at line 73 of file qfiledialog.h.
confirmOverwrite
bool QFileDialog::confirmOverwrite private
whether the filedialog should ask before accepting a selected file, when the accept mode is AcceptSave
Use setOption(DontConfirmOverwrite, !enabled) or !testOption(DontConfirmOverwrite) instead.
Definition at line 76 of file qfiledialog.h.
defaultSuffix
QString QFileDialog::defaultSuffix private
suffix added to the filename if no other suffix was specified
This property specifies a string that will be added to the filename if it has no suffix already. The suffix is typically used to indicate the file type (e.g. "txt" indicates a text file).
Definition at line 77 of file qfiledialog.h.
fileMode
QFileDialog::FileMode QFileDialog::fileMode private
the file mode of the dialog
The file mode defines the number and type of items that the user is expected to select in the dialog.
By default, this property is set to AnyFile.
This function will set the labels for the FileName and QFileDialog::Accept DialogLabel. It is possible to set custom text after the call to setFileMode().
See also
FileMode
Definition at line 72 of file qfiledialog.h.
nameFilterDetailsVisible
QFileDialog::nameFilterDetailsVisible private
This property holds whether the filter details is shown or not.
Since
4.4
When this property is true (the default), the filter details are shown in the combo box. When the property is set to false, these are hidden.
Use setOption(HideNameFilterDetails, !enabled) or !testOption(HideNameFilterDetails).
Definition at line 78 of file qfiledialog.h.
options
QFileDialog::Options QFileDialog::options private
the various options that affect the look and feel of the dialog
Since
4.5
By default, all options are disabled.
Options should be set before showing the dialog. Setting them while the dialog is visible is not guaranteed to have an immediate effect on the dialog (depending on the option and on the platform).
See also
setOption(), testOption()
Definition at line 79 of file qfiledialog.h.
readOnly
QFileDialog::readOnly private
Whether the filedialog is read-only.
If this property is set to false, the file dialog will allow renaming, and deleting of files and directories and creating directories.
Use setOption(ReadOnly, enabled) or testOption(ReadOnly) instead.
Definition at line 74 of file qfiledialog.h.
resolveSymlinks
bool QFileDialog::resolveSymlinks private
whether the filedialog should resolve shortcuts
If this property is set to true, the file dialog will resolve shortcuts or symbolic links.
Use setOption(DontResolveSymlinks, !enabled) or !testOption(DontResolveSymlinks).
Definition at line 75 of file qfiledialog.h.
viewMode
QFileDialog::ViewMode QFileDialog::viewMode private
the way files and directories are displayed in the dialog
By default, the Detail mode is used to display information about files and directories.
See also
ViewMode
Definition at line 71 of file qfiledialog.h.
The documentation for this class was generated from the following files:
/src/gui/dialogs/qfiledialog.h
/src/gui/dialogs/qfiledialog.cpp