Qt 4.8: QPatternist::AccelTreeBuilder< FromDocument > Class Template Reference
QPatternist::AccelTreeBuilder< FromDocument > Class Template Reference
Builds an AccelTree from a stream of XML/Item events received through the NodeBuilder interface.
#include <qacceltree_p.h>
Public Types
enum Feature { NoneFeature, SourceLocationsFeature = 1 }
typedef QExplicitlySharedDataPointer< AccelTreeBuilder > Ptr
Public Types inherited from QPatternist::NodeBuilder
typedef AutoPtr< NodeBuilder > Ptr
Public Types inherited from QPatternist::QAbstractXmlReceiver
typedef QExplicitlySharedDataPointer< QAbstractXmlReceiver > Ptr
Public Functions
AccelTreeBuilder (const QUrl &docURI, const QUrl &baseURI, const NamePool::Ptr &np, ReportContext *const context, Features features=NoneFeature)
virtual const SourceLocationReflection * actualReflection () const
virtual void atomicValue (const QVariant &value)
virtual void attribute (const QXmlName &name, const QStringRef &value)
virtual QAbstractXmlNodeModel::Ptr builtDocument ()
Returns the document that has been built.
AccelTree::Ptr builtDocument () const
virtual void characters (const QStringRef &ch)
virtual void comment (const QString &content)
virtual NodeBuilder::Ptr create (const QUrl &baseURI) const
Creates a copy of this NodeBuilder, that operates independently of this NodeBuilder.
virtual void endDocument ()
virtual void endElement ()
Signals the end of the current element.
virtual void endOfSequence ()
virtual void item (const Item &it)
Sends an Item to this QAbstractXmlReceiver that may be a QXmlNodeModelIndex or an AtomicValue.
virtual void namespaceBinding (const QXmlName &nb)
Signals the presence of the namespace declaration nb.
virtual void processingInstruction (const QXmlName &target, const QString &data)
virtual QSourceLocation sourceLocation () const
virtual void startDocument ()
virtual void startElement (const QXmlName &name)
void startElement (const QXmlName &name, qint64 line, qint64 column)
virtual void startOfSequence ()
virtual void whitespaceOnly (const QStringRef &ch)
Public Functions inherited from QPatternist::NodeBuilder
NodeBuilder ()
Public Functions inherited from QPatternist::QAbstractXmlReceiver
virtual void attribute (const QXmlName name, const QString &value)=0
Signals the presence of an attribute node.
virtual void characters (const QString &value)=0
virtual void processingInstruction (const QXmlName name, const QString &value)=0
QAbstractXmlReceiver ()
virtual void startElement (const QXmlName name)=0
Signals the start of an element by name name.
virtual ~QAbstractXmlReceiver ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QString description () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Private Types
enum Constants { DefaultNodeStackSize = 10, SizeIsEmpty = 0 }
Private Functions
AccelTree::PreNumber currentDepth () const
AccelTree::PreNumber currentParent () const
void startStructure ()
Properties
QStack< AccelTree::PreNumber > m_ancestors
QSet< QString > m_attributeCompress
QString m_characters
ReportContext *const m_context
AccelTree::Ptr m_document
const QUrl m_documentURI
Features m_features
bool m_hasCharacters
bool m_isCharactersCompressed
bool m_isPreviousAtomic
NamePool::Ptr m_namePool
AccelTree::PreNumber m_preNumber
QStack< AccelTree::PreNumber > m_size
AccelTree::PreNumber m_skippedDocumentNodes
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::QAbstractXmlReceiver
void sendAsNode (const Item &outputItem)
Detailed Description
template<bool FromDocument>
class QPatternist::AccelTreeBuilder< FromDocument >
Builds an AccelTree from a stream of XML/Item events received through the NodeBuilder interface.
If FromDocument is true, it is assumed that AccelTreeBuilder is fed events from an XML document, otherwise it is assumed the events are from node constructor expressions.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 69 of file qacceltree_p.h.
Typedefs
Ptr
template<bool FromDocument> typedef QExplicitlySharedDataPointer<AccelTreeBuilder> QPatternist::AccelTreeBuilder< FromDocument >::Ptr
Definition at line 90 of file qacceltreebuilder_p.h.
Enumerations
Constants
template<bool FromDocument> enum QPatternist::AccelTreeBuilder::Constants private
Enumerator
DefaultNodeStackSize
SizeIsEmpty
Definition at line 152 of file qacceltreebuilder_p.h.
         {
             DefaultNodeStackSize = 10,
             SizeIsEmpty = 0
         };
Feature
template<bool FromDocument> enum QPatternist::AccelTreeBuilder::Feature
Describes the memory relevant features the builder shall support.
Enumerator
NoneFeature
No special features are enabled.
SourceLocationsFeature
The accel tree builder will store source locations for each start element.
Definition at line 95 of file qacceltreebuilder_p.h.
         {
             NoneFeature,
             SourceLocationsFeature = 1
         };
Constructors and Destructors
AccelTreeBuilder()
template<bool FromDocument> QPatternist::AccelTreeBuilder< FromDocument >::AccelTreeBuilder (const QUrl & docURI, const QUrl & baseURI, const NamePool::Ptr & np, ReportContext *const context, Features features = NoneFeature)
Parameters
context may be null.
Definition at line 49 of file qacceltreebuilder.cpp.
                                                                     : m_preNumber(-1)
                                                                     , m_isPreviousAtomic(false)
                                                                     , m_hasCharacters(false)
                                                                     , m_isCharactersCompressed(false)
                                                                     , m_namePool(np)
                                                                     , m_document(new AccelTree(docURI, baseURI))
                                                                     , m_skippedDocumentNodes(0)
                                                                     , m_documentURI(docURI)
                                                                     , m_context(context)
                                                                     , m_features(features)
 {
     Q_ASSERT(m_namePool);
     /* TODO Perhaps we can merge m_ancestors and m_size
      * into one, and store a struct for the two instead? */
     m_ancestors.reserve(DefaultNodeStackSize);
     m_ancestors.push(-1);
     m_size.reserve(DefaultNodeStackSize);
     m_size.push(0);
 }
Functions
actualReflection()
template<bool FromDocument> const SourceLocationReflection * QPatternist::AccelTreeBuilder< FromDocument >::actualReflection () const virtual
Implements QPatternist::SourceLocationReflection.
Definition at line 427 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeBuilder< true >::builtDocument().
 {
     return this;
 }
atomicValue()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::atomicValue (const QVariant & value) virtual
Definition at line 393 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeBuilder< true >::builtDocument().
 {
     Q_UNUSED(value);
     // TODO
 }
attribute()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::attribute (const QXmlName & name, const QStringRef & value) virtual
In the case that we're called for doc-available(), m_context is null, and we need to flag somehow that we failed to load this document.
In the case that we're called for doc-available(), m_context is null, and we need to flag somehow that we failed to load this document.
Definition at line 178 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     /* Attributes adds a namespace binding, so lets synthesize one.
      *
      * We optimize by checking whether we have a namespace for which a binding would
      * be generated. Happens relatively rarely. */
     if(name.hasPrefix())
         namespaceBinding(QXmlName(name.namespaceURI(), 0, name.prefix()));
     m_document->basicData.append(AccelTree::BasicNodeData(currentDepth(), currentParent(), QXmlNodeModelIndex::Attribute, 0, name));
     ++m_preNumber;
     ++m_size.top();
     m_isPreviousAtomic = false;
     if(name.namespaceURI() == StandardNamespaces::xml && name.localName() == StandardLocalNames::id)
     {
         const QString normalized(value.toString().simplified());
         if(QXmlUtils::isNCName(normalized))
         {
             const QXmlName::LocalNameCode id = m_namePool->allocateLocalName(normalized);
             const int oldSize = m_document->m_IDs.count();
             m_document->m_IDs.insert(id, currentParent());
             /* We don't run the value through m_attributeCompress here, because
              * the likelyhood of it deing identical to another attribute is
              * very small. */
             m_document->data.insert(m_preNumber, normalized);
             if(oldSize == m_document->m_IDs.count() && m_context) // TODO
             {
                 Q_ASSERT(m_context);
                 m_context->error(QtXmlPatterns::tr("An %1-attribute with value %2 has already been declared.")
                                                    .arg(formatKeyword("xml:id"),
                                                         formatData(normalized)),
                                  FromDocument ? ReportContext::FODC0002 : ReportContext::XQDY0091,
                                  this);
             }
         }
         else if(m_context) // TODO
         {
             Q_ASSERT(m_context);
             /* If we're building from an XML Document(e.g, we're fed from QXmlStreamReader, we raise FODC0002,
              * otherwise XQDY0091. */
             m_context->error(QtXmlPatterns::tr("An %1-attribute must have a "
                                                "valid %2 as value, which %3 isn't.").arg(formatKeyword("xml:id"),
                                                                                          formatType(m_namePool, BuiltinTypes::xsNCName),
                                                                                          formatData(value.toString())),
                              FromDocument ? ReportContext::FODC0002 : ReportContext::XQDY0091,
                              this);
         }
     }
     else
         m_document->data.insert(m_preNumber, *m_attributeCompress.insert(value.toString()));
 }
builtDocument() [1/2]
template<bool FromDocument> QAbstractXmlNodeModel::Ptr QPatternist::AccelTreeBuilder< FromDocument >::builtDocument () virtual
Returns the document that has been built.
If this function is called before any events have been received, the result is undefined.
The top node that was constructed can be retrieved by calling NodeModel::root() on the returned NodeModel.
This function is not const, because some implementations delay the node construction until the node is needed. Also, text nodes are difficult, at best, to construct until one knows that all text content has been received(which a call to this function in a natural way signals).
Implements QPatternist::NodeBuilder.
Definition at line 400 of file qacceltreebuilder.cpp.
 {
     /* Create a text node, if we have received text in some way. */
     startStructure();
     m_document->printStats(m_namePool);
     return m_document;
 }
builtDocument() [2/2]
template<bool FromDocument> AccelTree::Ptr QPatternist::AccelTreeBuilder< FromDocument >::builtDocument () const inline
Definition at line 129 of file qacceltreebuilder_p.h.
         {
             return m_document;
         }
characters()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::characters (const QStringRef & ch) virtual
Definition at line 242 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     /* If a text node constructor appears by itself, a node needs to
      * be created. Therefore, we set m_hasCharacters
      * if we're the only node.
      * However, if the text node appears as a child of a document or element
      * node it is discarded if it's empty.
      */
     if(m_hasCharacters && m_isCharactersCompressed)
     {
         m_characters = CompressedWhitespace::decompress(m_characters);
         m_isCharactersCompressed = false;
     }
     m_characters += ch;
     m_isPreviousAtomic = false;
     m_hasCharacters = !m_characters.isEmpty() || m_preNumber == -1; /* -1 is our start value. */
 }
comment()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::comment (const QString & content) virtual
Implements QPatternist::QAbstractXmlReceiver.
Definition at line 314 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     startStructure();
     m_document->basicData.append(AccelTree::BasicNodeData(currentDepth(), currentParent(), QXmlNodeModelIndex::Comment, 0));
     ++m_preNumber;
     m_document->data.insert(m_preNumber, content);
     ++m_size.top();
 }
create()
template<bool FromDocument> NodeBuilder::Ptr QPatternist::AccelTreeBuilder< FromDocument >::create (const QUrl & baseURI) const virtual
Creates a copy of this NodeBuilder, that operates independently of this NodeBuilder.
The caller owns the returned instance.
Implements QPatternist::NodeBuilder.
Definition at line 410 of file qacceltreebuilder.cpp.
 {
     Q_UNUSED(baseURI);
     return NodeBuilder::Ptr(new AccelTreeBuilder(QUrl(), baseURI, m_namePool, m_context));
 }
currentDepth()
template<bool FromDocument> AccelTree::PreNumber QPatternist::AccelTreeBuilder< FromDocument >::currentDepth () const inline private
Definition at line 142 of file qacceltreebuilder_p.h.
         {
             return m_ancestors.count() -1;
         }
currentParent()
template<bool FromDocument> AccelTree::PreNumber QPatternist::AccelTreeBuilder< FromDocument >::currentParent () const inline private
Definition at line 147 of file qacceltreebuilder_p.h.
         {
             return m_ancestors.isEmpty() ? -1 : m_ancestors.top();
         }
endDocument()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::endDocument () virtual
End of a document node.
Implements QPatternist::QAbstractXmlReceiver.
Definition at line 370 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     if(m_skippedDocumentNodes == 0)
     {
         /* Create text nodes, if we've received any. We do this only if we're the
          * top node because if we're getting this event as being a child of an element,
          * text nodes or atomic values can appear after us, and which must get
          * merged with the previous text.
          *
          * We call startStructure() before we pop the ancestor, such that the text node becomes
          * a child of this document node. */
         startStructure();
         m_document->basicData.first().setSize(m_size.pop());
         m_ancestors.pop();
     }
     else
         --m_skippedDocumentNodes;
     m_isPreviousAtomic = false;
 }
endElement()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::endElement () virtual
Signals the end of the current element.
Implements QPatternist::QAbstractXmlReceiver.
Definition at line 163 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     startStructure();
     const AccelTree::PreNumber index = m_ancestors.pop();
     AccelTree::BasicNodeData &data = m_document->basicData[index];
     /* Sub trees needs to be included in upper trees, so we add the count of this element
      * to our parent. */
     m_size[m_size.count() - 2] += m_size.top();
     data.setSize(m_size.pop());
     m_isPreviousAtomic = false;
 }
endOfSequence()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::endOfSequence () virtual
Definition at line 422 of file qacceltreebuilder.cpp.
 {
 }
item()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::item (const Item & item) virtual
Sends an Item to this QAbstractXmlReceiver that may be a QXmlNodeModelIndex or an AtomicValue.
Implements QPatternist::QAbstractXmlReceiver.
Definition at line 101 of file qacceltreebuilder.cpp.
 {
     Q_ASSERT(it);
     if(it.isAtomicValue())
     {
         if(m_isPreviousAtomic)
         {
             m_characters += QLatin1Char(' ');
             m_characters += it.stringValue();
         }
         else
         {
             m_isPreviousAtomic = true;
             const QString sv(it.stringValue());
             if(!sv.isEmpty())
             {
                 m_characters += sv;
                 m_hasCharacters = true;
             }
         }
     }
     else
         sendAsNode(it);
 }
namespaceBinding()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::namespaceBinding (const QXmlName & nb) virtual
Signals the presence of the namespace declaration nb.
This event is received after startElement(), as opposed to SAX, and before any attribute() events.
Implements QPatternist::QAbstractXmlReceiver.
Definition at line 324 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     /* Note, because attribute() sometimes generate namespaceBinding() calls, this function
      * can be called after attributes, in contrast to what the class documentation says. This is ok,
      * as long as we're not dealing with public API. */
     /* If we've received attributes, it means the element's size have changed and m_preNumber have advanced,
      * so "reverse back" to the actual element. */
     const AccelTree::PreNumber pn = m_preNumber - m_size.top();
     QVector<QXmlName> &nss = m_document->namespaces[pn];
     /* "xml" hasn't been declared for each node, AccelTree::namespaceBindings() adds it, so avoid it
      * such that we don't get duplicates. */
     if(nb.prefix() == StandardPrefixes::xml)
         return;
     /* If we already have the binding, skip it. */
     const int len = nss.count();
     for(int i = 0; i < len; ++i)
     {
         if(nss.at(i).prefix() == nb.prefix())
             return;
     }
     nss.append(nb);
 }
processingInstruction()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::processingInstruction (const QXmlName & target, const QString & data) virtual
Definition at line 297 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     startStructure();
     ++m_preNumber;
     m_document->data.insert(m_preNumber, data);
     m_document->basicData.append(AccelTree::BasicNodeData(currentDepth(),
                                                           currentParent(),
                                                           QXmlNodeModelIndex::ProcessingInstruction,
                                                           0,
                                                           target));
     ++m_size.top();
     m_isPreviousAtomic = false;
 }
sourceLocation()
template<bool FromDocument> QSourceLocation QPatternist::AccelTreeBuilder< FromDocument >::sourceLocation () const virtual
Reimplemented from QPatternist::SourceLocationReflection.
Definition at line 433 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeBuilder< true >::builtDocument().
 {
     if(m_documentURI.isEmpty())
         return QSourceLocation(QUrl(QLatin1String("AnonymousNodeTree")));
     else
         return QSourceLocation(m_documentURI);
 }
startDocument()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::startDocument () virtual
Start of a document node.
Implements QPatternist::QAbstractXmlReceiver.
Definition at line 353 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     /* If we have already received nodes, we can't add a document node. */
     if(m_preNumber == -1) /* -1 is our start value. */
     {
         m_size.push(0);
         m_document->basicData.append(AccelTree::BasicNodeData(0, -1, QXmlNodeModelIndex::Document, -1));
         ++m_preNumber;
         m_ancestors.push(m_preNumber);
     }
     else
         ++m_skippedDocumentNodes;
     m_isPreviousAtomic = false;
 }
startElement() [1/2]
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::startElement (const QXmlName & name) virtual
Definition at line 129 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     startElement(name, 1, 1);
 }
startElement() [2/2]
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::startElement (const QXmlName & name, qint64 line, qint64 column)
Definition at line 135 of file qacceltreebuilder.cpp.
 {
     startStructure();
     AccelTree::BasicNodeData data(currentDepth(), currentParent(), QXmlNodeModelIndex::Element, -1, name);
     m_document->basicData.append(data);
     if (m_features & SourceLocationsFeature)
         m_document->sourcePositions.insert(m_document->maximumPreNumber(), qMakePair(line, column));
     ++m_preNumber;
     m_ancestors.push(m_preNumber);
     ++m_size.top();
     m_size.push(0);
     /* With node constructors, we can receive names for which we have no namespace
      * constructors, such as in the query '<xs:space/>'. Since the 'xs' prefix has no
      * NamespaceConstructor in this case, we synthesize the namespace.
      *
      * In case we're constructing from an XML document we avoid the call because
      * although it's redundant, it's on extra virtual call for each element. */
     if(!FromDocument)
         namespaceBinding(QXmlName(name.namespaceURI(), 0, name.prefix()));
     m_isPreviousAtomic = false;
 }
startOfSequence()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::startOfSequence () virtual
Definition at line 417 of file qacceltreebuilder.cpp.
 {
 }
startStructure()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::startStructure () inline private
Definition at line 76 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeBuilder< true >::builtDocument().
 {
     if(m_hasCharacters)
     {
         /* We create a node even if m_characters is empty.
          * Remember that `text {""}' creates one text node
          * with string value "". */
         ++m_preNumber;
         m_document->basicData.append(AccelTree::BasicNodeData(currentDepth(),
                                                               currentParent(),
                                                               QXmlNodeModelIndex::Text,
                                                               m_isCharactersCompressed ? AccelTree::IsCompressed : 0));
         m_document->data.insert(m_preNumber, m_characters);
         ++m_size.top();
         m_characters.clear(); /* We don't want it added twice. */
         m_hasCharacters = false;
         if(m_isCharactersCompressed)
             m_isCharactersCompressed = false;
     }
 }
whitespaceOnly()
template<bool FromDocument> void QPatternist::AccelTreeBuilder< FromDocument >::whitespaceOnly (const QStringRef & value) virtual
This function may be called instead of characters() if, and only if, value consists only of whitespace.
The caller gurantees that value, is not empty.
By whitespace is meant a sequence of characters that are either spaces, tabs, or the two new line characters, in any order. In other words, the whole of Unicode's whitespace category is not considered whitespace.
However, there's no guarantee or requirement that whitespaceOnly() is called for text nodes containing whitespace only, characters() may be called just as well. This is why the default implementation for whitespaceOnly() calls characters().
See also
characters()
Reimplemented from QPatternist::QAbstractXmlReceiver.
Definition at line 264 of file qacceltreebuilder.cpp.
Referenced by QPatternist::AccelTreeResourceLoader::streamToReceiver().
 {
     Q_ASSERT(!ch.isEmpty());
     Q_ASSERT(ch.toString().trimmed().isEmpty());
     /* This gets problematic due to how QXmlStreamReader works(which
      * is the only one we get whitespaceOnly() events from). Namely, text intermingled
      * with CDATA gets reported as individual Characters events, and
      * QXmlStreamReader::isWhitespace() can return differently for each of those. However,
      * it will occur very rarely, so this workaround of 1) mistakenly compressing 2) decompressing 3)
      * appending, will happen infrequently.
      */
     if(m_hasCharacters)
     {
         if(m_isCharactersCompressed)
         {
             m_characters = CompressedWhitespace::decompress(m_characters);
             m_isCharactersCompressed = false;
         }
         m_characters.append(ch.toString());
     }
     else
     {
         /* We haven't received a text node previously. */
         m_characters = CompressedWhitespace::compress(ch);
         m_isCharactersCompressed = true;
         m_isPreviousAtomic = false;
         m_hasCharacters = true;
     }
 }
Properties
m_ancestors
template<bool FromDocument> QStack<AccelTree::PreNumber> QPatternist::AccelTreeBuilder< FromDocument >::m_ancestors private
Definition at line 169 of file qacceltreebuilder_p.h.
Referenced by QPatternist::AccelTreeBuilder< true >::currentDepth(), and QPatternist::AccelTreeBuilder< true >::currentParent().
m_attributeCompress
template<bool FromDocument> QSet<QString> QPatternist::AccelTreeBuilder< FromDocument >::m_attributeCompress private
All attribute values goes through this set such that we store only one QString for identical attribute values.
Definition at line 182 of file qacceltreebuilder_p.h.
m_characters
template<bool FromDocument> QString QPatternist::AccelTreeBuilder< FromDocument >::m_characters private
Definition at line 166 of file qacceltreebuilder_p.h.
m_context
template<bool FromDocument> ReportContext* const QPatternist::AccelTreeBuilder< FromDocument >::m_context private
We don't store a reference pointer here because then we get a circular reference with GenericDynamicContext, when it stores us as a member.
Definition at line 189 of file qacceltreebuilder_p.h.
m_document
template<bool FromDocument> AccelTree::Ptr QPatternist::AccelTreeBuilder< FromDocument >::m_document private
Definition at line 168 of file qacceltreebuilder_p.h.
Referenced by QPatternist::AccelTreeBuilder< true >::builtDocument().
m_documentURI
template<bool FromDocument> const QUrl QPatternist::AccelTreeBuilder< FromDocument >::m_documentURI private
Definition at line 183 of file qacceltreebuilder_p.h.
m_features
template<bool FromDocument> Features QPatternist::AccelTreeBuilder< FromDocument >::m_features private
Definition at line 191 of file qacceltreebuilder_p.h.
m_hasCharacters
template<bool FromDocument> bool QPatternist::AccelTreeBuilder< FromDocument >::m_hasCharacters private
Definition at line 160 of file qacceltreebuilder_p.h.
m_isCharactersCompressed
template<bool FromDocument> bool QPatternist::AccelTreeBuilder< FromDocument >::m_isCharactersCompressed private
Whether m_characters has been run through CompressedWhitespace::compress().
Definition at line 165 of file qacceltreebuilder_p.h.
m_isPreviousAtomic
template<bool FromDocument> bool QPatternist::AccelTreeBuilder< FromDocument >::m_isPreviousAtomic private
Definition at line 159 of file qacceltreebuilder_p.h.
m_namePool
template<bool FromDocument> NamePool::Ptr QPatternist::AccelTreeBuilder< FromDocument >::m_namePool private
Definition at line 167 of file qacceltreebuilder_p.h.
m_preNumber
template<bool FromDocument> AccelTree::PreNumber QPatternist::AccelTreeBuilder< FromDocument >::m_preNumber private
Definition at line 158 of file qacceltreebuilder_p.h.
m_size
template<bool FromDocument> QStack<AccelTree::PreNumber> QPatternist::AccelTreeBuilder< FromDocument >::m_size private
Definition at line 170 of file qacceltreebuilder_p.h.
m_skippedDocumentNodes
template<bool FromDocument> AccelTree::PreNumber QPatternist::AccelTreeBuilder< FromDocument >::m_skippedDocumentNodes private
If we have already commenced a document, we don't want to add more document nodes. We keep track of them with this counter, which ensures that startDocument() and endDocument() are skipped consistently.
Definition at line 176 of file qacceltreebuilder_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/acceltree/qacceltree_p.h
/src/xmlpatterns/acceltree/qacceltreebuilder_p.h
/src/xmlpatterns/acceltree/qacceltreebuilder.cpp