Qt 4.8: QScriptDebuggerCommandSchedulerFrontend Class Reference
QScriptDebuggerCommandSchedulerFrontend Class Reference
#include <qscriptdebuggercommandschedulerfrontend_p.h>
Public Functions
QScriptDebuggerCommandSchedulerFrontend (QScriptDebuggerCommandSchedulerInterface *scheduler, QScriptDebuggerResponseHandlerInterface *responseHandler)
int scheduleClearExceptions ()
int scheduleContextsCheckpoint ()
int scheduleContinue ()
Instructs the front-end to continue evaluation, and returns a unique identifier associated with this command.
int scheduleDeleteAllBreakpoints ()
int scheduleDeleteBreakpoint (int id)
int scheduleDeleteScriptObjectSnapshot (int id)
int scheduleDeleteScriptValueIterator (int id)
int scheduleEvaluate (int contextIndex, const QString &program, const QString &fileName=QString(), int lineNumber=1)
int scheduleForceReturn (int contextIndex, const QScriptDebuggerValue &value)
int scheduleGetActivationObject (int contextIndex)
int scheduleGetBacktrace ()
int scheduleGetBreakpointData (int id)
int scheduleGetBreakpoints ()
int scheduleGetCompletions (int contextIndex, const QStringList &path)
int scheduleGetContextCount ()
int scheduleGetContextId (int contextIndex)
int scheduleGetContextInfo (int contextIndex)
int scheduleGetContextState (int contextIndex)
int scheduleGetPropertiesByIterator (int id, int count)
int scheduleGetPropertyExpressionValue (int contextIndex, int lineNumber, const QStringList &path)
int scheduleGetScopeChain (int contextIndex)
int scheduleGetScriptData (qint64 id)
int scheduleGetScripts ()
int scheduleGetScriptsDelta ()
int scheduleGetThisObject (int contextIndex)
int scheduleInterrupt ()
Instructs the front-end to break at the next script statement, and returns a unique identifier associated with this command.
int scheduleNewScriptObjectSnapshot ()
int scheduleNewScriptValueIterator (const QScriptDebuggerValue &object)
int scheduleResolveScript (const QString &fileName)
int scheduleRunToLocation (const QString &fileName, int lineNumber)
Instructs the front-end to continue evaluation until the location specified by the given fileName and lineNumber is reached.
int scheduleRunToLocation (qint64 scriptId, int lineNumber)
Instructs the front-end to continue evaluation until the location specified by the given scriptId and lineNumber is reached.
int scheduleScriptObjectSnapshotCapture (int id, const QScriptDebuggerValue &object)
int scheduleScriptsCheckpoint ()
int scheduleScriptValueToString (const QScriptDebuggerValue &value)
int scheduleSetBreakpoint (const QString &fileName, int lineNumber)
int scheduleSetBreakpoint (const QScriptBreakpointData &data)
int scheduleSetBreakpointData (int id, const QScriptBreakpointData &data)
int scheduleSetScriptValueProperty (const QScriptDebuggerValue &object, const QString &name, const QScriptDebuggerValue &value)
int scheduleStepInto (int count=1)
Instructs the front-end to step into the next script statement, and returns a unique identifier associated with this command.
int scheduleStepOut ()
Instructs the front-end to step out of the current script function, and returns a unique identifier associated with this command.
int scheduleStepOver (int count=1)
Instructs the front-end to step over the next script statement, and returns a unique identifier associated with this command.
~QScriptDebuggerCommandSchedulerFrontend ()
Private Functions
int scheduleCommand (const QScriptDebuggerCommand &command)
Properties
QScriptDebuggerResponseHandlerInterface * m_responseHandler
QScriptDebuggerCommandSchedulerInterface * m_scheduler
Detailed Description
Definition at line 68 of file qscriptdebuggercommandschedulerfrontend_p.h.
Constructors and Destructors
QScriptDebuggerCommandSchedulerFrontend()
QScriptDebuggerCommandSchedulerFrontend::QScriptDebuggerCommandSchedulerFrontend (QScriptDebuggerCommandSchedulerInterface * scheduler, QScriptDebuggerResponseHandlerInterface * responseHandler)
Definition at line 48 of file qscriptdebuggercommandschedulerfrontend.cpp.
     : m_scheduler(scheduler), m_responseHandler(responseHandler)
 {
 }
~QScriptDebuggerCommandSchedulerFrontend()
QScriptDebuggerCommandSchedulerFrontend::~QScriptDebuggerCommandSchedulerFrontend ()
Definition at line 55 of file qscriptdebuggercommandschedulerfrontend.cpp.
 {
 }
Functions
scheduleClearExceptions()
int QScriptDebuggerCommandSchedulerFrontend::scheduleClearExceptions ()
Definition at line 300 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleClearExceptions().
 {
     return scheduleCommand(QScriptDebuggerCommand::clearExceptionsCommand());
 }
scheduleCommand()
int QScriptDebuggerCommandSchedulerFrontend::scheduleCommand (const QScriptDebuggerCommand & command) private
Definition at line 59 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by scheduleClearExceptions(), scheduleContextsCheckpoint(), scheduleContinue(), scheduleDeleteAllBreakpoints(), scheduleDeleteBreakpoint(), scheduleDeleteScriptObjectSnapshot(), scheduleDeleteScriptValueIterator(), scheduleEvaluate(), scheduleForceReturn(), scheduleGetActivationObject(), scheduleGetBacktrace(), scheduleGetBreakpointData(), scheduleGetBreakpoints(), scheduleGetCompletions(), scheduleGetContextCount(), scheduleGetContextId(), scheduleGetContextInfo(), scheduleGetContextState(), scheduleGetPropertiesByIterator(), scheduleGetPropertyExpressionValue(), scheduleGetScopeChain(), scheduleGetScriptData(), scheduleGetScripts(), scheduleGetScriptsDelta(), scheduleGetThisObject(), scheduleInterrupt(), scheduleNewScriptObjectSnapshot(), scheduleNewScriptValueIterator(), scheduleResolveScript(), scheduleRunToLocation(), scheduleScriptObjectSnapshotCapture(), scheduleScriptsCheckpoint(), scheduleScriptValueToString(), scheduleSetBreakpoint(), scheduleSetBreakpointData(), scheduleSetScriptValueProperty(), scheduleStepInto(), scheduleStepOut(), and scheduleStepOver().
 {
     return m_scheduler->scheduleCommand(command, m_responseHandler);
 }
scheduleContextsCheckpoint()
int QScriptDebuggerCommandSchedulerFrontend::scheduleContextsCheckpoint ()
Definition at line 249 of file qscriptdebuggercommandschedulerfrontend.cpp.
 {
     return scheduleCommand(QScriptDebuggerCommand::contextsCheckpoint());
 }
scheduleContinue()
int QScriptDebuggerCommandSchedulerFrontend::scheduleContinue ()
Instructs the front-end to continue evaluation, and returns a unique identifier associated with this command.
See also
scheduleBreak()
Definition at line 84 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleContinue().
 {
     return scheduleCommand(QScriptDebuggerCommand::continueCommand());
 }
scheduleDeleteAllBreakpoints()
int QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteAllBreakpoints ()
Definition at line 164 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleDeleteAllBreakpoints().
 {
     return scheduleCommand(QScriptDebuggerCommand::deleteAllBreakpointsCommand());
 }
scheduleDeleteBreakpoint()
int QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteBreakpoint (int id)
Definition at line 159 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleDeleteBreakpoint(), and QScriptBreakpointsModel::setBreakpointData().
 {
     return scheduleCommand(QScriptDebuggerCommand::deleteBreakpointCommand(id));
 }
scheduleDeleteScriptObjectSnapshot()
int QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteScriptObjectSnapshot (int id)
Definition at line 315 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::deleteObjectSnapshots().
 {
     return scheduleCommand(QScriptDebuggerCommand::deleteScriptObjectSnapshotCommand(id));
 }
scheduleDeleteScriptValueIterator()
int QScriptDebuggerCommandSchedulerFrontend::scheduleDeleteScriptValueIterator (int id)
Definition at line 283 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleDeleteScriptValueIterator().
 {
     return scheduleCommand(QScriptDebuggerCommand::deleteScriptValueIteratorCommand(id));
 }
scheduleEvaluate()
int QScriptDebuggerCommandSchedulerFrontend::scheduleEvaluate (int contextIndex, const QString & program, const QString & fileName = QString(), int lineNumber = 1)
Definition at line 265 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::get(), and QScriptDebuggerConsoleGlobalObject::scheduleEvaluate().
 {
     return scheduleCommand(QScriptDebuggerCommand::evaluateCommand(contextIndex, program, fileName, lineNumber));
 }
scheduleForceReturn()
int QScriptDebuggerCommandSchedulerFrontend::scheduleForceReturn (int contextIndex, const QScriptDebuggerValue & value)
Definition at line 144 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerPrivate::debuggerEvent(), and QScriptDebuggerConsoleGlobalObject::scheduleForceReturn().
 {
     return scheduleCommand(QScriptDebuggerCommand::forceReturnCommand(contextIndex, value));
 }
scheduleGetActivationObject()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetActivationObject (int contextIndex)
Definition at line 239 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetActivationObject().
 {
     return scheduleCommand(QScriptDebuggerCommand::getActivationObjectCommand(contextIndex));
 }
scheduleGetBacktrace()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetBacktrace ()
Definition at line 209 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetBacktrace().
 {
     return scheduleCommand(QScriptDebuggerCommand::getBacktraceCommand());
 }
scheduleGetBreakpointData()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetBreakpointData (int id)
Definition at line 174 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetBreakpointData().
 {
     return scheduleCommand(QScriptDebuggerCommand::getBreakpointDataCommand(id));
 }
scheduleGetBreakpoints()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetBreakpoints ()
Definition at line 169 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetBreakpoints().
 {
     return scheduleCommand(QScriptDebuggerCommand::getBreakpointsCommand());
 }
scheduleGetCompletions()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetCompletions (int contextIndex, const QStringList & path)
Definition at line 260 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptCompleteExpressionJob::start().
 {
     return scheduleCommand(QScriptDebuggerCommand::getCompletions(contextIndex, path));
 }
scheduleGetContextCount()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextCount ()
Definition at line 214 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetContextCount().
 {
     return scheduleCommand(QScriptDebuggerCommand::getContextCountCommand());
 }
scheduleGetContextId()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextId (int contextIndex)
Definition at line 229 of file qscriptdebuggercommandschedulerfrontend.cpp.
 {
     return scheduleCommand(QScriptDebuggerCommand::getContextIdCommand(contextIndex));
 }
scheduleGetContextInfo()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextInfo (int contextIndex)
Definition at line 224 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerPrivate::createLocalsModel(), and QScriptDebuggerConsoleGlobalObject::scheduleGetContextInfo().
 {
     return scheduleCommand(QScriptDebuggerCommand::getContextInfoCommand(contextIndex));
 }
scheduleGetContextState()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetContextState (int contextIndex)
Definition at line 219 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerPrivate::createLocalsModel().
 {
     return scheduleCommand(QScriptDebuggerCommand::getContextStateCommand(contextIndex));
 }
scheduleGetPropertiesByIterator()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetPropertiesByIterator (int id, int count)
Definition at line 278 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetPropertiesByIterator().
 {
     return scheduleCommand(QScriptDebuggerCommand::getPropertiesByIteratorCommand(id, count));
 }
scheduleGetPropertyExpressionValue()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetPropertyExpressionValue (int contextIndex, int lineNumber, const QStringList & path)
Definition at line 254 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptToolTipJob::start().
 {
     return scheduleCommand(QScriptDebuggerCommand::getPropertyExpressionValue(contextIndex, lineNumber, path));
 }
scheduleGetScopeChain()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetScopeChain (int contextIndex)
Definition at line 244 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::addTopLevelObject(), and QScriptDebuggerLocalsModel::init().
 {
     return scheduleCommand(QScriptDebuggerCommand::getScopeChainCommand(contextIndex));
 }
scheduleGetScriptData()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetScriptData (qint64 id)
Definition at line 189 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetScriptData(), and QScriptDebuggerShowLineJob::start().
 {
     return scheduleCommand(QScriptDebuggerCommand::getScriptDataCommand(id));
 }
scheduleGetScripts()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetScripts ()
Definition at line 184 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetScripts(), and QScriptCompleteScriptsJob::start().
 {
     return scheduleCommand(QScriptDebuggerCommand::getScriptsCommand());
 }
scheduleGetScriptsDelta()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetScriptsDelta ()
Definition at line 199 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleGetScriptsDelta().
 {
     return scheduleCommand(QScriptDebuggerCommand::getScriptsDeltaCommand());
 }
scheduleGetThisObject()
int QScriptDebuggerCommandSchedulerFrontend::scheduleGetThisObject (int contextIndex)
Definition at line 234 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::addTopLevelObject(), QScriptDebuggerLocalsModel::init(), and QScriptDebuggerConsoleGlobalObject::scheduleGetThisObject().
 {
     return scheduleCommand(QScriptDebuggerCommand::getThisObjectCommand(contextIndex));
 }
scheduleInterrupt()
int QScriptDebuggerCommandSchedulerFrontend::scheduleInterrupt ()
Instructs the front-end to break at the next script statement, and returns a unique identifier associated with this command.
When the next script statement is encountered, the client will be notified, and the front-end will be ready to accept commands.
See also
scheduleContinue()
Definition at line 73 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleInterrupt().
 {
     return scheduleCommand(QScriptDebuggerCommand::interruptCommand());
 }
scheduleNewScriptObjectSnapshot()
int QScriptDebuggerCommandSchedulerFrontend::scheduleNewScriptObjectSnapshot ()
Definition at line 305 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::isTopLevelNode().
 {
     return scheduleCommand(QScriptDebuggerCommand::newScriptObjectSnapshotCommand());
 }
scheduleNewScriptValueIterator()
int QScriptDebuggerCommandSchedulerFrontend::scheduleNewScriptValueIterator (const QScriptDebuggerValue & object)
Definition at line 273 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleNewScriptValueIterator().
 {
     return scheduleCommand(QScriptDebuggerCommand::newScriptValueIteratorCommand(object));
 }
scheduleResolveScript()
int QScriptDebuggerCommandSchedulerFrontend::scheduleResolveScript (const QString & fileName)
Definition at line 204 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleResolveScript().
 {
     return scheduleCommand(QScriptDebuggerCommand::resolveScriptCommand(fileName));
 }
scheduleRunToLocation() [1/2]
int QScriptDebuggerCommandSchedulerFrontend::scheduleRunToLocation (const QString & fileName, int lineNumber)
Instructs the front-end to continue evaluation until the location specified by the given fileName and lineNumber is reached.
Definition at line 130 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerPrivate::_q_runToCursor(), QScriptDebuggerPrivate::_q_runToNewScript(), and QScriptDebuggerConsoleGlobalObject::scheduleRunToLocation().
 {
     return scheduleCommand(QScriptDebuggerCommand::runToLocationCommand(fileName, lineNumber));
 }
scheduleRunToLocation() [2/2]
int QScriptDebuggerCommandSchedulerFrontend::scheduleRunToLocation (qint64 scriptId, int lineNumber)
Instructs the front-end to continue evaluation until the location specified by the given scriptId and lineNumber is reached.
Definition at line 139 of file qscriptdebuggercommandschedulerfrontend.cpp.
 {
     return scheduleCommand(QScriptDebuggerCommand::runToLocationCommand(scriptId, lineNumber));
 }
scheduleScriptObjectSnapshotCapture()
int QScriptDebuggerCommandSchedulerFrontend::scheduleScriptObjectSnapshotCapture (int id, const QScriptDebuggerValue & object)
Definition at line 310 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::isTopLevelNode(), and QScriptDebuggerLocalsModel::sync().
 {
     return scheduleCommand(QScriptDebuggerCommand::scriptObjectSnapshotCaptureCommand(id, object));
 }
scheduleScriptsCheckpoint()
int QScriptDebuggerCommandSchedulerFrontend::scheduleScriptsCheckpoint ()
Definition at line 194 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleScriptsCheckpoint().
 {
     return scheduleCommand(QScriptDebuggerCommand::scriptsCheckpointCommand());
 }
scheduleScriptValueToString()
int QScriptDebuggerCommandSchedulerFrontend::scheduleScriptValueToString (const QScriptDebuggerValue & value)
Definition at line 288 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleScriptValueToString().
 {
     return scheduleCommand(QScriptDebuggerCommand::scriptValueToStringCommand(value));
 }
scheduleSetBreakpoint() [1/2]
int QScriptDebuggerCommandSchedulerFrontend::scheduleSetBreakpoint (const QString & fileName, int lineNumber)
Definition at line 149 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleSetBreakpoint(), and QScriptBreakpointsModel::~QScriptBreakpointsModel().
 {
     return scheduleCommand(QScriptDebuggerCommand::setBreakpointCommand(fileName, lineNumber));
 }
scheduleSetBreakpoint() [2/2]
int QScriptDebuggerCommandSchedulerFrontend::scheduleSetBreakpoint (const QScriptBreakpointData & data)
Definition at line 154 of file qscriptdebuggercommandschedulerfrontend.cpp.
 {
     return scheduleCommand(QScriptDebuggerCommand::setBreakpointCommand(data));
 }
scheduleSetBreakpointData()
int QScriptDebuggerCommandSchedulerFrontend::scheduleSetBreakpointData (int id, const QScriptBreakpointData & data)
Definition at line 179 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleSetBreakpointData(), and QScriptBreakpointsModel::setBreakpoint().
 {
     return scheduleCommand(QScriptDebuggerCommand::setBreakpointDataCommand(id, data));
 }
scheduleSetScriptValueProperty()
int QScriptDebuggerCommandSchedulerFrontend::scheduleSetScriptValueProperty (const QScriptDebuggerValue & object, const QString & name, const QScriptDebuggerValue & value)
Definition at line 293 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerLocalsModelPrivate::get().
 {
     return scheduleCommand(QScriptDebuggerCommand::setScriptValuePropertyCommand(object, name, value));
 }
scheduleStepInto()
int QScriptDebuggerCommandSchedulerFrontend::scheduleStepInto (int count = 1)
Instructs the front-end to step into the next script statement, and returns a unique identifier associated with this command.
Evaluation will automatically be continued, and the client()'s event() function will be called when the statement has been stepped into.
Definition at line 96 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleStepInto().
 {
     return scheduleCommand(QScriptDebuggerCommand::stepIntoCommand(count));
 }
scheduleStepOut()
int QScriptDebuggerCommandSchedulerFrontend::scheduleStepOut ()
Instructs the front-end to step out of the current script function, and returns a unique identifier associated with this command.
Evaluation will automatically be continued, and the client()'s event() function will be called when the script function has been stepped out of.
Definition at line 121 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleStepOut().
 {
     return scheduleCommand(QScriptDebuggerCommand::stepOutCommand());
 }
scheduleStepOver()
int QScriptDebuggerCommandSchedulerFrontend::scheduleStepOver (int count = 1)
Instructs the front-end to step over the next script statement, and returns a unique identifier associated with this command.
Evaluation will automatically be continued, and the client()'s event() function will be called when the statement has been stepped over.
Definition at line 108 of file qscriptdebuggercommandschedulerfrontend.cpp.
Referenced by QScriptDebuggerConsoleGlobalObject::scheduleStepOver().
 {
     return scheduleCommand(QScriptDebuggerCommand::stepOverCommand(count));
 }
Properties
m_responseHandler
QScriptDebuggerResponseHandlerInterface* QScriptDebuggerCommandSchedulerFrontend::m_responseHandler private
Definition at line 141 of file qscriptdebuggercommandschedulerfrontend_p.h.
Referenced by scheduleCommand().
m_scheduler
QScriptDebuggerCommandSchedulerInterface* QScriptDebuggerCommandSchedulerFrontend::m_scheduler private
Definition at line 140 of file qscriptdebuggercommandschedulerfrontend_p.h.
Referenced by scheduleCommand().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggercommandschedulerfrontend_p.h
/src/scripttools/debugging/qscriptdebuggercommandschedulerfrontend.cpp