Qt 4.8: QSystemError Class Reference
QSystemError Class Reference
#include <qsystemerror_p.h>
Public Types
enum ErrorScope { NoError, StandardLibraryError, NativeError }
Public Functions
int error ()
QSystemError (int error, ErrorScope scope)
QSystemError ()
ErrorScope scope ()
QString toString ()
Public Variables
int errorCode
ErrorScope errorScope
Detailed Description
Definition at line 60 of file qsystemerror_p.h.
Enumerations
ErrorScope
enum QSystemError::ErrorScope
Enumerator
NoError
StandardLibraryError
NativeError
Definition at line 63 of file qsystemerror_p.h.
     {
         NoError,
         StandardLibraryError,
         NativeError
     };
Constructors and Destructors
QSystemError() [1/2]
QSystemError::QSystemError (int error, QSystemError::ErrorScope scope) inline
Definition at line 82 of file qsystemerror_p.h.
 : errorCode(error), errorScope(scope)
 {
 }
QSystemError() [2/2]
QSystemError::QSystemError () inline
Definition at line 88 of file qsystemerror_p.h.
 : errorCode(0), errorScope(NoError)
 {
 }
Functions
error()
int QSystemError::error () inline
Definition at line 99 of file qsystemerror_p.h.
 {
     return errorCode;
 }
scope()
QSystemError::ErrorScope QSystemError::scope () inline
Definition at line 94 of file qsystemerror_p.h.
 {
     return errorScope;
 }
toString()
QString QSystemError::toString ()
Definition at line 206 of file qsystemerror.cpp.
Referenced by QFSFileEngine::copy(), QFSFileEngine::link(), QFSFileEnginePrivate::longFileName(), QFSFileEnginePrivate::nativeSize(), QTemporaryFileEngine::open(), QFSFileEngine::remove(), QFSFileEngine::rename(), and QFSFileEngine::setPermissions().
 {
     switch(errorScope) {
     case NativeError:
 #if defined (Q_OS_WIN)
         return windowsErrorString(errorCode);
 #elif defined (Q_OS_SYMBIAN)
         return symbianErrorString(errorCode);
 #else
         //unix: fall through as native and standard library are the same
 #endif
     case StandardLibraryError:
         return standardLibraryErrorString(errorCode);
     default:
         qWarning("invalid error scope");
         //fall through
     case NoError:
         return QLatin1String("No error");
     }
 }
Properties
errorCode
int QSystemError::errorCode
Definition at line 78 of file qsystemerror_p.h.
Referenced by error(), and toString().
errorScope
ErrorScope QSystemError::errorScope
Definition at line 79 of file qsystemerror_p.h.
Referenced by scope(), and toString().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qsystemerror_p.h
/src/corelib/kernel/qsystemerror.cpp