Qt 4.8: QDirectFbIntegration Class Reference
QDirectFbIntegration Class Reference
#include <qdirectfbintegration.h>
Public Functions
QPixmapData * createPixmapData (QPixmapData::PixelType type) const
Factory function for QPixmapData.
QPlatformWindow * createPlatformWindow (QWidget *widget, WId winId=0) const
Factory function for QPlatformWindow.
QWindowSurface * createWindowSurface (QWidget *widget, WId winId) const
Factory function for QWindowSurface.
QPlatformFontDatabase * fontDatabase () const
Accessor for the platform integrations fontdatabase.
void initialize ()
QDirectFbIntegration ()
QList< QPlatformScreen * > screens () const
Accessor function to a list of all the screens on the current system.
~QDirectFbIntegration ()
Public Functions inherited from QPlatformIntegration
virtual QPlatformClipboard * clipboard () const
Accessor for the platform integrations clipboard.
virtual QPlatformEventLoopIntegration * createEventLoopIntegration () const
Factory function for the eventloop integration interface.
virtual QPixmap grabWindow (WId window, int x, int y, int width, int height) const
This function is called when Qt needs to be able to grab the content of a window.
virtual bool hasCapability (Capability cap) const
virtual bool isVirtualDesktop ()
Returns if the current windowing system configuration defines all the screens to be one desktop(virtual desktop), or if each screen is a desktop of its own.
virtual void moveToScreen (QWidget *window, int screen)
This function is called when a QWidget is displayed on screen, or the QWidget is to be displayed on a new screen.
virtual QPlatformNativeInterface * nativeInterface () const
virtual ~QPlatformIntegration ()
Protected Functions
virtual void initializeDirectFB ()
virtual void initializeInput ()
virtual void initializeScreen ()
Protected Variables
QDirectFBPointer< IDirectFB > m_dfb
QScopedPointer< QPlatformFontDatabase > m_fontDb
QScopedPointer< QDirectFbInput > m_input
QScopedPointer< QThread > m_inputRunner
QScopedPointer< QDirectFbScreen > m_primaryScreen
QList< QPlatformScreen * > mScreens
Additional Inherited Members
Public Types inherited from QPlatformIntegration
enum Capability { ThreadedPixmaps = 1, OpenGL = 2 }
Detailed Description
Definition at line 56 of file qdirectfbintegration.h.
Constructors and Destructors
QDirectFbIntegration()
QDirectFbIntegration::QDirectFbIntegration ()
Definition at line 58 of file qdirectfbintegration.cpp.
     : m_fontDb(new QGenericUnixFontDatabase())
 {}
~QDirectFbIntegration()
QDirectFbIntegration::~QDirectFbIntegration ()
Definition at line 104 of file qdirectfbintegration.cpp.
 {
     m_input->stopInputEventLoop();
     m_input->wait();
 }
Functions
createPixmapData()
QPixmapData * QDirectFbIntegration::createPixmapData (QPixmapData::PixelType type) const virtual
Factory function for QPixmapData.
PixelType can be either PixmapType or BitmapType.
See also
QPixmapData
Implements QPlatformIntegration.
Definition at line 110 of file qdirectfbintegration.cpp.
 {
     if (type == QPixmapData::BitmapType)
         return new QRasterPixmapData(type);
     else
         return new QDirectFbBlitterPlatformPixmap;
 }
createPlatformWindow()
QPlatformWindow * QDirectFbIntegration::createPlatformWindow (QWidget * widget, WId winId = 0) const virtual
Factory function for QPlatformWindow.
The widget parameter is a pointer to the top level widget(tlw) which the QPlatformWindow is suppose to be created for. The WId handle is actually never used, but there for future reference. Its purpose is if it is going to be possible to create QPlatformWindows on existing WId.
All tlw has to have a QPlatformWindow, and it will be created when the QPlatformWindow is set to be visible for the first time. If the tlw's window flags are changed, or if the tlw's QPlatformWindowFormat is changed, then the tlw's QPlatformWindow is deleted and a new one is created.
See also
QPlatformWindow, QPlatformWindowFormat
createWindowSurface(QWidget *widget, WId winId) const
Implements QPlatformIntegration.
Definition at line 118 of file qdirectfbintegration.cpp.
 {
     return new QDirectFbWindow(window,m_input.data());
 }
createWindowSurface()
QWindowSurface * QDirectFbIntegration::createWindowSurface (QWidget * widget, WId winId) const virtual
Factory function for QWindowSurface.
The QWidget parameter is a pointer to the top level widget(tlw) the window surface is created for. A QPlatformWindow is always created before the QWindowSurface for tlw where the widget also requires a WindowSurface. It is possible to create top level QWidgets without a QWindowSurface by specifying QPlatformWindowFormat::setWindowSurface(false) for the tlw QPlatformWindowFormat.
See also
QWindowSurface
createPlatformWindow(QWidget *widget, WId winId = 0) const
Implements QPlatformIntegration.
Definition at line 123 of file qdirectfbintegration.cpp.
 {
     return new QDirectFbWindowSurface(window);
 }
fontDatabase()
QPlatformFontDatabase * QDirectFbIntegration::fontDatabase () const virtual
Accessor for the platform integrations fontdatabase.
Default implementation returns a default QPlatformFontDatabase.
See also
QPlatformFontDatabase
Reimplemented from QPlatformIntegration.
Definition at line 128 of file qdirectfbintegration.cpp.
Referenced by screens().
 {
     return m_fontDb.data();
 }
initialize()
void QDirectFbIntegration::initialize ()
Definition at line 62 of file qdirectfbintegration.cpp.
Referenced by QDirectFbIntegrationPlugin::create(), and screens().
 {
     initializeDirectFB();
     initializeScreen();
     initializeInput();
 }
initializeDirectFB()
void QDirectFbIntegration::initializeDirectFB () protected virtual
Definition at line 69 of file qdirectfbintegration.cpp.
Referenced by initialize(), and screens().
 {
     const QStringList args = QCoreApplication::arguments();
     int argc = args.size();
     char **argv = new char*[argc];
     for (int i = 0; i < argc; ++i)
         argv[i] = qstrdup(args.at(i).toLocal8Bit().constData());
     DFBResult result = DirectFBInit(&argc, &argv);
     if (result != DFB_OK) {
         DirectFBError("QDirectFBScreen: error initializing DirectFB",
                       result);
     }
     for (int i = 0; i < argc; ++i)
         delete[] argv[i];
     delete[] argv;
     // This must happen after DirectFBInit.
     m_dfb.reset(QDirectFbConvenience::dfbInterface());
 }
initializeInput()
void QDirectFbIntegration::initializeInput () protected virtual
Definition at line 98 of file qdirectfbintegration.cpp.
Referenced by initialize(), and screens().
 {
     m_input.reset(new QDirectFbInput(m_dfb.data(), m_primaryScreen->dfbLayer()));
     m_input->start();
 }
initializeScreen()
void QDirectFbIntegration::initializeScreen () protected virtual
Definition at line 92 of file qdirectfbintegration.cpp.
Referenced by initialize(), and screens().
 {
     m_primaryScreen.reset(new QDirectFbScreen(0));
     mScreens.append(m_primaryScreen.data());
 }
screens()
QList<QPlatformScreen *> QDirectFbIntegration::screens () const inline virtual
Accessor function to a list of all the screens on the current system.
The screen with the index == 0 is the default/main screen.
Implements QPlatformIntegration.
Definition at line 66 of file qdirectfbintegration.h.
 { return mScreens; }
Properties
m_dfb
QDirectFBPointer<IDirectFB> QDirectFbIntegration::m_dfb protected
Definition at line 79 of file qdirectfbintegration.h.
Referenced by initializeDirectFB(), and initializeInput().
m_fontDb
QScopedPointer<QPlatformFontDatabase> QDirectFbIntegration::m_fontDb protected
Definition at line 83 of file qdirectfbintegration.h.
Referenced by fontDatabase().
m_input
QScopedPointer<QDirectFbInput> QDirectFbIntegration::m_input protected
Definition at line 81 of file qdirectfbintegration.h.
Referenced by createPlatformWindow(), initializeInput(), and ~QDirectFbIntegration().
m_inputRunner
QScopedPointer<QThread> QDirectFbIntegration::m_inputRunner protected
Definition at line 82 of file qdirectfbintegration.h.
m_primaryScreen
QScopedPointer<QDirectFbScreen> QDirectFbIntegration::m_primaryScreen protected
Definition at line 80 of file qdirectfbintegration.h.
Referenced by initializeInput(), and initializeScreen().
mScreens
QList<QPlatformScreen *> QDirectFbIntegration::mScreens protected
Definition at line 78 of file qdirectfbintegration.h.
Referenced by initializeScreen(), and screens().
The documentation for this class was generated from the following files:
/src/plugins/platforms/directfb/qdirectfbintegration.h
/src/plugins/platforms/directfb/qdirectfbintegration.cpp