Qt 4.8: QAccessible Class Reference
QAccessible Class Reference
The QAccessible class provides enums and static functions relating to accessibility.
#include <qaccessible.h>
Public Types
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Static Private Attributes
static RootObjectHandler rootObjectHandler
static UpdateHandler updateHandler
Detailed Description
The QAccessible class provides enums and static functions relating to accessibility.
Accessible applications can be used by people who are not able to use applications by conventional means.
The functions in this class are used for communication between accessible applications (also called AT Servers) and accessibility tools (AT Clients), such as screen readers and braille displays. Clients and servers communicate in the following way:
AT Servers notify the clients about events through calls to the updateAccessibility() function.
AT Clients request information about the objects in the server. The QAccessibleInterface class is the core interface, and encapsulates this information in a pure virtual API. Implementations of the interface are provided by Qt through the queryAccessibleInterface() API.
The communication between servers and clients is initialized by the setRootObject() function. Function pointers can be installed to replace or extend the default behavior of the static functions in QAccessible.
Qt supports Microsoft Active Accessibility (MSAA), Mac OS X Accessibility, and the Unix/X11 AT-SPI standard. Other backends can be supported using QAccessibleBridge.
In addition to QAccessible's static functions, Qt offers one generic interface, QAccessibleInterface, that can be used to wrap all widgets and objects (e.g., QPushButton). This single interface provides all the metadata necessary for the assistive technologies. Qt provides implementations of this interface for its built-in widgets as plugins.
When you develop custom widgets, you can create custom subclasses of QAccessibleInterface and distribute them as plugins (using QAccessiblePlugin) or compile them into the application. Likewise, Qt's predefined accessibility support can be built as plugin (the default) or directly into the Qt library. The main advantage of using plugins is that the accessibility classes are only loaded into memory if they are actually used; they don't slow down the common case where no assistive technology is being used.
Qt also includes two convenience classes, QAccessibleObject and QAccessibleWidget, that inherit from QAccessibleInterface and provide the lowest common denominator of metadata (e.g., widget geometry, window title, basic help text). You can use them as base classes when wrapping your custom QObject or QWidget subclasses.
See also
QAccessibleInterface
Definition at line 64 of file qaccessible.h.
Typedefs
InterfaceFactory
QAccessible::InterfaceFactory
This is a typedef for a pointer to a function with the following signature:
typedef QAccessibleInterface* myFactoryFunction(const QString &key, QObject *);
The function receives a QString and a QObject pointer, where the QString is the key identifying the interface. The QObject is used to pass on to the QAccessibleInterface so that it can hold a reference to it.
If the key and the QObject does not have a corresponding QAccessibleInterface, a null-pointer will be returned.
Installed factories are called by queryAccessibilityInterface() until one provides an interface.
Definition at line 319 of file qaccessible.h.
RootObjectHandler
QAccessible::RootObjectHandler
A function pointer type.
Warning
This function is not part of the public interface.
Use a function with this prototype to install your own root object handler.
The function is called by setRootObject().
Definition at line 321 of file qaccessible.h.
UpdateHandler
QAccessible::UpdateHandler
A function pointer type.
Warning
This function is not part of the public interface.
Use a function with this prototype to install your own update function.
The function is called by updateAccessibility().
Definition at line 320 of file qaccessible.h.
Enumerations
Action
enum QAccessible::Action
This enum describes the possible types of action that can occur.
DefaultAction
Press
SetFocus
Increase
Decrease
Accept
Cancel
Select
ClearSelection
RemoveSelection
ExtendSelection
AddToSelection
FirstStandardAction
LastStandardAction
Enumerator
DefaultAction
Press
FirstStandardAction
SetFocus
Increase
Decrease
Accept
Cancel
Select
ClearSelection
RemoveSelection
ExtendSelection
AddToSelection
LastStandardAction
Definition at line 294 of file qaccessible.h.
                 {
         DefaultAction       = 0,
         Press               = -1,
         FirstStandardAction = Press,
         SetFocus            = -2,
         Increase            = -3,
         Decrease            = -4,
         Accept              = -5,
         Cancel              = -6,
         Select              = -7,
         ClearSelection      = -8,
         RemoveSelection     = -9,
         ExtendSelection     = -10,
         AddToSelection      = -11,
         LastStandardAction  = AddToSelection
     };
Event
enum QAccessible::Event
This enum type defines accessible event types.
AcceleratorChanged The keyboard accelerator for an action has been changed.
ActionChanged An action has been changed.
ActiveDescendantChanged
Alert A system alert (e.g., a message from a QMessageBox)
AttributeChanged
ContextHelpEnd Context help (QWhatsThis) for an object is finished.
ContextHelpStart Context help (QWhatsThis) for an object is initiated.
DefaultActionChanged The default QAccessible::Action for the accessible object has changed.
DescriptionChanged The object's QAccessible::Description changed.
DialogEnd A dialog (QDialog) has been hidden
DialogStart A dialog (QDialog) has been set visible.
DocumentContentChanged The contents of a text document have changed.
DocumentLoadComplete A document has been loaded.
DocumentLoadStopped A document load has been stopped.
DocumentReload A document reload has been initiated.
DragDropEnd A drag and drop operation is about to finished.
DragDropStart A drag and drop operation is about to be initiated.
Focus An object has gained keyboard focus.
ForegroundChanged A window has been activated (i.e., a new window has gained focus on the desktop).
HelpChanged The QAccessible::Help text property of an object has changed.
HyperlinkEndIndexChanged The end position of the display text for a hypertext link has changed.
HyperlinkNumberOfAnchorsChanged The number of anchors in a hypertext link has changed, perhaps because the display text has been split to provide more than one link.
HyperlinkSelectedLinkChanged The link for the selected hypertext link has changed.
HyperlinkStartIndexChanged The start position of the display text for a hypertext link has changed.
HypertextChanged The display text for a hypertext link has changed.
HypertextLinkActivated A hypertext link has been activated, perhaps by being clicked or via a key press.
HypertextLinkSelected A hypertext link has been selected.
HypertextNLinksChanged
LocationChanged An object's location on the screen has changed.
MenuCommand A menu item is triggered.
MenuEnd A menu has been closed (Qt uses PopupMenuEnd for all menus).
MenuStart A menu has been opened on the menubar (Qt uses PopupMenuStart for all menus).
NameChanged The QAccessible::Name property of an object has changed.
ObjectAttributeChanged
ObjectCreated A new object is created.
ObjectDestroyed An object is deleted.
ObjectHide An object is hidden; for example, with QWidget::hide(). Any children the object that is hidden has do not send this event. It is not sent when an object is hidden as it is being obcured by others.
ObjectReorder A layout or item view has added, removed, or moved an object (Qt does not use this event).
ObjectShow An object is displayed; for example, with QWidget::show().
PageChanged
ParentChanged An object's parent object changed.
PopupMenuEnd A pop-up menu has closed.
PopupMenuStart A pop-up menu has opened.
ScrollingEnd A scrollbar scroll operation has ended (the mouse has released the slider handle).
ScrollingStart A scrollbar scroll operation is about to start; this may be caused by a mouse press on the slider handle, for example.
SectionChanged
SelectionAdd An item has been added to the selection in an item view.
SelectionRemove An item has been removed from an item view selection.
Selection The selection has changed in a menu or item view.
SelectionWithin Several changes to a selection has occurred in an item view.
SoundPlayed A sound has been played by an object
StateChanged The QAccessible::State of an object has changed.
TableCaptionChanged A table caption has been changed.
TableColumnDescriptionChanged The description of a table column, typically found in the column's header, has been changed.
TableColumnHeaderChanged A table column header has been changed.
TableModelChanged The model providing data for a table has been changed.
TableRowDescriptionChanged The description of a table row, typically found in the row's header, has been changed.
TableRowHeaderChanged A table row header has been changed.
TableSummaryChanged The summary of a table has been changed.
TextAttributeChanged
TextCaretMoved The caret has moved in an editable widget. The caret represents the cursor position in an editable widget with the input focus.
TextColumnChanged A text column has been changed.
TextInserted Text has been inserted into an editable widget.
TextRemoved Text has been removed from an editable widget.
TextSelectionChanged The selected text has changed in an editable widget.
TextUpdated The text has been update in an editable widget.
ValueChanged The QAccessible::Value of an object has changed.
VisibleDataChanged
The values for this enum are defined to be the same as those defined in the AccessibleEventID.idl File Reference{IAccessible2} and Microsoft Active Accessibility Event Constants{MSAA} specifications.
Enumerator
SoundPlayed
Alert
ForegroundChanged
MenuStart
MenuEnd
PopupMenuStart
PopupMenuEnd
ContextHelpStart
ContextHelpEnd
DragDropStart
DragDropEnd
DialogStart
DialogEnd
ScrollingStart
ScrollingEnd
MenuCommand
ActionChanged
ActiveDescendantChanged
AttributeChanged
DocumentContentChanged
DocumentLoadComplete
DocumentLoadStopped
DocumentReload
HyperlinkEndIndexChanged
HyperlinkNumberOfAnchorsChanged
HyperlinkSelectedLinkChanged
HypertextLinkActivated
HypertextLinkSelected
HyperlinkStartIndexChanged
HypertextChanged
HypertextNLinksChanged
ObjectAttributeChanged
PageChanged
SectionChanged
TableCaptionChanged
TableColumnDescriptionChanged
TableColumnHeaderChanged
TableModelChanged
TableRowDescriptionChanged
TableRowHeaderChanged
TableSummaryChanged
TextAttributeChanged
TextCaretMoved
TextColumnChanged
TextInserted
TextRemoved
TextUpdated
TextSelectionChanged
VisibleDataChanged
ObjectCreated
ObjectDestroyed
ObjectShow
ObjectHide
ObjectReorder
Focus
Selection
SelectionAdd
SelectionRemove
SelectionWithin
StateChanged
LocationChanged
NameChanged
DescriptionChanged
ValueChanged
ParentChanged
HelpChanged
DefaultActionChanged
AcceleratorChanged
Definition at line 67 of file qaccessible.h.
                {
         SoundPlayed          = 0x0001,
         Alert                = 0x0002,
         ForegroundChanged    = 0x0003,
         MenuStart            = 0x0004,
         MenuEnd              = 0x0005,
         PopupMenuStart       = 0x0006,
         PopupMenuEnd         = 0x0007,
         ContextHelpStart     = 0x000C,
         ContextHelpEnd       = 0x000D,
         DragDropStart        = 0x000E,
         DragDropEnd          = 0x000F,
         DialogStart          = 0x0010,
         DialogEnd            = 0x0011,
         ScrollingStart       = 0x0012,
         ScrollingEnd         = 0x0013,
         MenuCommand          = 0x0018,
         // Values from IAccessible2
         ActionChanged                    = 0x0101,
         ActiveDescendantChanged          = 0x0102,
         AttributeChanged                 = 0x0103,
         DocumentContentChanged           = 0x0104,
         DocumentLoadComplete             = 0x0105,
         DocumentLoadStopped              = 0x0106,
         DocumentReload                   = 0x0107,
         HyperlinkEndIndexChanged         = 0x0108,
         HyperlinkNumberOfAnchorsChanged  = 0x0109,
         HyperlinkSelectedLinkChanged     = 0x010A,
         HypertextLinkActivated           = 0x010B,
         HypertextLinkSelected            = 0x010C,
         HyperlinkStartIndexChanged       = 0x010D,
         HypertextChanged                 = 0x010E,
         HypertextNLinksChanged           = 0x010F,
         ObjectAttributeChanged           = 0x0110,
         PageChanged                      = 0x0111,
         SectionChanged                   = 0x0112,
         TableCaptionChanged              = 0x0113,
         TableColumnDescriptionChanged    = 0x0114,
         TableColumnHeaderChanged         = 0x0115,
         TableModelChanged                = 0x0116,
         TableRowDescriptionChanged       = 0x0117,
         TableRowHeaderChanged            = 0x0118,
         TableSummaryChanged              = 0x0119,
         TextAttributeChanged             = 0x011A,
         TextCaretMoved                   = 0x011B,
         // TextChanged = 0x011C, is deprecated in IA2, use TextUpdated
         TextColumnChanged                = 0x011D,
         TextInserted                     = 0x011E,
         TextRemoved                      = 0x011F,
         TextUpdated                      = 0x0120,
         TextSelectionChanged             = 0x0121,
         VisibleDataChanged               = 0x0122,
         ObjectCreated        = 0x8000,
         ObjectDestroyed      = 0x8001,
         ObjectShow           = 0x8002,
         ObjectHide           = 0x8003,
         ObjectReorder        = 0x8004,
         Focus                = 0x8005,
         Selection            = 0x8006,
         SelectionAdd         = 0x8007,
         SelectionRemove      = 0x8008,
         SelectionWithin      = 0x8009,
         StateChanged         = 0x800A,
         LocationChanged      = 0x800B,
         NameChanged          = 0x800C,
         DescriptionChanged   = 0x800D,
         ValueChanged         = 0x800E,
         ParentChanged        = 0x800F,
         HelpChanged          = 0x80A0,
         DefaultActionChanged = 0x80B0,
         AcceleratorChanged   = 0x80C0
     };
Method
enum QAccessible::Method
This enum describes the possible types of methods that can be invoked on an accessible object.
ListSupportedMethods
SetCursorPosition
GetCursorPosition
ForegroundColor
BackgroundColor
See also
QAccessibleInterface::invokeMethod()
Enumerator
ListSupportedMethods
SetCursorPosition
GetCursorPosition
ForegroundColor
BackgroundColor
Definition at line 311 of file qaccessible.h.
                 {
         ListSupportedMethods      = 0,
         SetCursorPosition         = 1,
         GetCursorPosition         = 2,
         ForegroundColor           = 3,
         BackgroundColor           = 4
     };
RelationFlag
enum QAccessible::RelationFlag
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
Unrelated The objects are unrelated.
Self The objects are the same.
Ancestor The first object is a parent of the second object.
Child The first object is a direct child of the second object.
Descendent The first object is an indirect child of the second object.
Sibling The objects are siblings.
Up The first object is above the second object.
Down The first object is below the second object.
Left The first object is left of the second object.
Right The first object is right of the second object.
Covers The first object covers the second object.
Covered The first object is covered by the second object.
FocusChild The first object is the second object's focus child.
Label The first object is the label of the second object.
Labelled The first object is labelled by the second object.
Controller The first object controls the second object.
Controlled The first object is controlled by the second object.
HierarchyMask
GeometryMask
LogicalMask
Implementations of relationTo() return a combination of these flags. Some values are mutually exclusive.
Implementations of navigate() can accept only one distinct value.
Enumerator
Unrelated
Self
Ancestor
Child
Descendent
Sibling
HierarchyMask
Up
Down
Left
Right
Covers
Covered
GeometryMask
FocusChild
Label
Labelled
Controller
Controlled
LogicalMask
Definition at line 268 of file qaccessible.h.
                       {
         Unrelated     = 0x00000000,
         Self          = 0x00000001,
         Ancestor      = 0x00000002,
         Child         = 0x00000004,
         Descendent    = 0x00000008,
         Sibling       = 0x00000010,
         HierarchyMask = 0x000000ff,
         Up            = 0x00000100,
         Down          = 0x00000200,
         Left          = 0x00000400,
         Right         = 0x00000800,
         Covers        = 0x00001000,
         Covered       = 0x00002000,
         GeometryMask  = 0x0000ff00,
         FocusChild    = 0x00010000,
         Label         = 0x00020000,
         Labelled      = 0x00040000,
         Controller    = 0x00080000,
         Controlled    = 0x00100000,
         LogicalMask   = 0x00ff0000
     };
Role
enum QAccessible::Role
This enum defines the role of an accessible object.
The roles are:
AlertMessage An object that is used to alert the user.
Animation An object that displays an animation.
Application The application's main window.
Assistant An object that provids interactive help.
Border An object that represents a border.
ButtonDropDown A button that drops down a list of items.
ButtonDropGrid A button that drops down a grid.
ButtonMenu A button that drops down a menu.
Canvas An object that displays graphics that the user can interact with.
Caret An object that represents the system caret (text cursor).
Cell A cell in a table.
Chart An object that displays a graphical representation of data.
CheckBox An object that represents an option that can be checked or unchecked. Some options provide a "mixed" state, e.g. neither checked nor unchecked.
Client The client area in a window.
Clock A clock displaying time.
Column A column of cells, usually within a table.
ColumnHeader A header for a column of data.
ComboBox A list of choices that the user can select from.
Cursor An object that represents the mouse cursor.
Desktop The object represents the desktop or workspace.
Dial An object that represents a dial or knob.
Dialog A dialog box.
Document A document window, usually in an MDI environment.
EditableText Editable text
Equation An object that represents a mathematical equation.
Graphic A graphic or picture, e.g. an icon.
Grip A grip that the user can drag to change the size of widgets.
Grouping An object that represents a logical grouping of other objects.
HelpBalloon An object that displays help in a separate, short lived window.
HotkeyField A hotkey field that allows the user to enter a key sequence.
Indicator An indicator that represents a current value or item.
LayeredPane An object that can contain layered children, e.g. in a stack.
Link A link to something else.
List A list of items, from which the user can select one or more items.
ListItem An item in a list of items.
MenuBar A menu bar from which menus are opened by the user.
MenuItem An item in a menu or menu bar.
NoRole The object has no role. This usually indicates an invalid object.
PageTab A page tab that the user can select to switch to a different page in a dialog.
PageTabList A list of page tabs.
Pane A generic container.
PopupMenu A menu which lists options that the user can select to perform an action.
ProgressBar The object displays the progress of an operation in progress.
PropertyPage A property page where the user can change options and settings.
PushButton A button.
RadioButton An object that represents an option that is mutually exclusive with other options.
Row A row of cells, usually within a table.
RowHeader A header for a row of data.
ScrollBar A scroll bar, which allows the user to scroll the visible area.
Separator A separator that divides space into logical areas.
Slider A slider that allows the user to select a value within a given range.
Sound An object that represents a sound.
SpinBox A spin box widget that allows the user to enter a value within a given range.
Splitter A splitter distributing available space between its child widgets.
StaticText Static text, such as labels for other widgets.
StatusBar A status bar.
Table A table representing data in a grid of rows and columns.
Terminal A terminal or command line interface.
TitleBar The title bar caption of a window.
ToolBar A tool bar, which groups widgets that the user accesses frequently.
ToolTip A tool tip which provides information about other objects.
Tree A list of items in a tree structure.
TreeItem An item in a tree structure.
UserRole The first value to be used for user defined roles.
Whitespace Blank space between other objects.
Window A top level window.
Enumerator
NoRole
TitleBar
MenuBar
ScrollBar
Grip
Sound
Cursor
Caret
AlertMessage
Window
Client
PopupMenu
MenuItem
ToolTip
Application
Document
Pane
Chart
Dialog
Border
Grouping
Separator
ToolBar
StatusBar
Table
ColumnHeader
RowHeader
Column
Row
Cell
Link
HelpBalloon
Assistant
List
ListItem
Tree
TreeItem
PageTab
PropertyPage
Indicator
Graphic
StaticText
EditableText
PushButton
CheckBox
RadioButton
ComboBox
ProgressBar
Dial
HotkeyField
Slider
SpinBox
Canvas
Animation
Equation
ButtonDropDown
ButtonMenu
ButtonDropGrid
Whitespace
PageTabList
Clock
Splitter
LayeredPane
Terminal
Desktop
UserRole
Definition at line 188 of file qaccessible.h.
               {
         NoRole         = 0x00000000,
         TitleBar       = 0x00000001,
         MenuBar        = 0x00000002,
         ScrollBar      = 0x00000003,
         Grip           = 0x00000004,
         Sound          = 0x00000005,
         Cursor         = 0x00000006,
         Caret          = 0x00000007,
         AlertMessage   = 0x00000008,
         Window         = 0x00000009,
         Client         = 0x0000000A,
         PopupMenu      = 0x0000000B,
         MenuItem       = 0x0000000C,
         ToolTip        = 0x0000000D,
         Application    = 0x0000000E,
         Document       = 0x0000000F,
         Pane           = 0x00000010,
         Chart          = 0x00000011,
         Dialog         = 0x00000012,
         Border         = 0x00000013,
         Grouping       = 0x00000014,
         Separator      = 0x00000015,
         ToolBar        = 0x00000016,
         StatusBar      = 0x00000017,
         Table          = 0x00000018,
         ColumnHeader   = 0x00000019,
         RowHeader      = 0x0000001A,
         Column         = 0x0000001B,
         Row            = 0x0000001C,
         Cell           = 0x0000001D,
         Link           = 0x0000001E,
         HelpBalloon    = 0x0000001F,
         Assistant      = 0x00000020,
         List           = 0x00000021,
         ListItem       = 0x00000022,
         Tree           = 0x00000023,
         TreeItem       = 0x00000024,
         PageTab        = 0x00000025,
         PropertyPage   = 0x00000026,
         Indicator      = 0x00000027,
         Graphic        = 0x00000028,
         StaticText     = 0x00000029,
         EditableText   = 0x0000002A,  // Editable, selectable, etc.
         PushButton     = 0x0000002B,
         CheckBox       = 0x0000002C,
         RadioButton    = 0x0000002D,
         ComboBox       = 0x0000002E,
         // DropList       = 0x0000002F,
         ProgressBar    = 0x00000030,
         Dial           = 0x00000031,
         HotkeyField    = 0x00000032,
         Slider         = 0x00000033,
         SpinBox        = 0x00000034,
         Canvas         = 0x00000035,
         Animation      = 0x00000036,
         Equation       = 0x00000037,
         ButtonDropDown = 0x00000038,
         ButtonMenu     = 0x00000039,
         ButtonDropGrid = 0x0000003A,
         Whitespace     = 0x0000003B,
         PageTabList    = 0x0000003C,
         Clock          = 0x0000003D,
         Splitter       = 0x0000003E,
         // Additional Qt roles where enum value does not map directly to MSAA:
         LayeredPane    = 0x0000003F,
         Terminal       = 0x00000040,
         Desktop        = 0x00000041,
         UserRole       = 0x0000ffff
     };
StateFlag
enum QAccessible::StateFlag
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
The values are:
Animated The object's appearance changes frequently.
Busy The object cannot accept input at the moment.
Checked The object's check box is checked.
Collapsed The object is collapsed, e.g. a closed listview item, or an iconified window.
DefaultButton The object represents the default button in a dialog.
Expanded The object is expandable, and currently the children are visible.
ExtSelectable The object supports extended selection.
Focusable The object can receive focus. Only objects in the active window can receive focus.
Focused The object has keyboard focus.
HasPopup The object opens a popup.
HotTracked The object's appearance is sensitive to the mouse cursor position.
Invisible The object is not visible to the user.
Linked The object is linked to another object, e.g. a hyperlink.
Marqueed The object displays scrolling contents, e.g. a log view.
Mixed The state of the object is not determined, e.g. a tri-state check box that is neither checked nor unchecked.
Modal The object blocks input from other objects.
Movable The object can be moved.
MultiSelectable The object supports multiple selected items.
Normal The normal state.
Offscreen The object is clipped by the visible area. Objects that are off screen are also invisible.
Pressed The object is pressed.
Protected The object is password protected, e.g. a line edit for entering a Password.
ReadOnly The object can usually be edited, but is explicitly set to read-only.
Selectable The object is selectable.
Selected The object is selected.
SelfVoicing The object describes itself through speech or sound.
Sizeable The object can be resized, e.g. top-level windows.
Traversed The object is linked and has been visited.
Unavailable The object is unavailable to the user, e.g. a disabled widget.
Moveable
HasInvokeExtension
Implementations of QAccessibleInterface::state() return a combination of these flags.
Enumerator
Normal
Unavailable
Selected
Focused
Pressed
Checked
Mixed
ReadOnly
HotTracked
DefaultButton
Expanded
Collapsed
Busy
Marqueed
Animated
Invisible
Offscreen
Sizeable
Movable
SelfVoicing
Focusable
Selectable
Linked
Traversed
MultiSelectable
ExtSelectable
Protected
HasPopup
Modal
HasInvokeExtension
Definition at line 143 of file qaccessible.h.
                    {
         Normal          = 0x00000000,
         Unavailable     = 0x00000001,
         Selected        = 0x00000002,
         Focused         = 0x00000004,
         Pressed         = 0x00000008,
         Checked         = 0x00000010,
         Mixed           = 0x00000020,
         ReadOnly        = 0x00000040,
         HotTracked      = 0x00000080,
         DefaultButton   = 0x00000100,
         // #### Qt5 Expandable
         Expanded        = 0x00000200,
         Collapsed       = 0x00000400,
         Busy            = 0x00000800,
         // Floating        = 0x00001000,
         Marqueed        = 0x00002000,
         Animated        = 0x00004000,
         Invisible       = 0x00008000,
         Offscreen       = 0x00010000,
         Sizeable        = 0x00020000,
         Movable         = 0x00040000,
 #ifdef QT3_SUPPORT
         Moveable        = Movable,
 #endif
         SelfVoicing     = 0x00080000,
         Focusable       = 0x00100000,
         Selectable      = 0x00200000,
         Linked          = 0x00400000,
         Traversed       = 0x00800000,
         MultiSelectable = 0x01000000,
         ExtSelectable   = 0x02000000,
         //AlertLow        = 0x04000000,
         //AlertMedium     = 0x08000000,
         //AlertHigh       = 0x10000000, /* reused for HasInvokeExtension */
         Protected       = 0x20000000,
         HasPopup        = 0x40000000,
         Modal           = 0x80000000,
         // #### Qt5 ManagesDescendants
         // #### Qt5 remove HasInvokeExtension
         HasInvokeExtension = 0x10000000 // internal
     };
Text
enum QAccessible::Text
This enum specifies string information that an accessible object returns.
Name The name of the object. This can be used both as an identifier or a short description by accessible clients.
Description A short text describing the object.
Value The value of the object.
Help A longer text giving information about how to use the object.
Accelerator The keyboard shortcut that executes the object's default action.
UserText The first value to be used for user defined text.
Enumerator
Name
Description
Value
Accelerator
UserText
Definition at line 259 of file qaccessible.h.
               {
         Name         = 0,
         Description,
         Value,
         Help,
         Accelerator,
         UserText     = 0x0000ffff
     };
Functions
cleanup()
void QAccessible::cleanup () static
Warning
This function is not part of the public interface.
Definition at line 2359 of file qaccessible_mac.mm.
Referenced by qt_cleanup().
 {
     accessibleHierarchyManager()->reset();
 #ifndef QT_MAC_USE_COCOA
     removeEventhandler(applicationEventHandlerUPP);
     removeEventhandler(objectCreateEventHandlerUPP);
     removeEventhandler(accessibilityEventHandlerUPP);
 #endif
 }
initialize()
void QAccessible::initialize () static
Warning
This function is not part of the public interface.
Definition at line 2339 of file qaccessible_mac.mm.
Referenced by qt_init().
 {
 #ifndef QT_MAC_USE_COCOA
     registerQtAccessibilityHIObjectSubclass();
     installApplicationEventhandler();
 #endif
 }
installFactory()
void QAccessible::installFactory (InterfaceFactory factory) static
Installs the InterfaceFactory factory.
The last factory added is the first one used by queryAccessibleInterface().
Definition at line 553 of file qaccessible.cpp.
 {
     if (!factory)
         return;
     if (!cleanupAdded) {
         qAddPostRoutine(qAccessibleCleanup);
         cleanupAdded = true;
     }
     if (qAccessibleFactories()->contains(factory))
         return;
     qAccessibleFactories()->append(factory);
 }
installRootObjectHandler()
QAccessible::RootObjectHandler QAccessible::installRootObjectHandler (RootObjectHandler handler) static
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
Definition at line 596 of file qaccessible.cpp.
Referenced by QTestAccessibility::QTestAccessibility(), and QTestAccessibility::~QTestAccessibility().
 {
     RootObjectHandler old = rootObjectHandler;
     rootObjectHandler = handler;
     return old;
 }
installUpdateHandler()
QAccessible::UpdateHandler QAccessible::installUpdateHandler (UpdateHandler handler) static
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
Warning
This function is not part of the public interface.
Definition at line 585 of file qaccessible.cpp.
Referenced by QTestAccessibility::QTestAccessibility(), and QTestAccessibility::~QTestAccessibility().
 {
     UpdateHandler old = updateHandler;
     updateHandler = handler;
     return old;
 }
isActive()
bool QAccessible::isActive () static
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
Use this function to prevent potentially expensive notifications via updateAccessibility().
Definition at line 665 of file qaccessible.cpp.
Referenced by QMenuBarPrivate::_q_actionHovered(), QAbstractItemViewPrivate::_q_columnsInserted(), QAbstractItemViewPrivate::_q_columnsRemoved(), QAbstractItemViewPrivate::_q_layoutChanged(), QAbstractItemViewPrivate::_q_rowsInserted(), QAbstractItemViewPrivate::_q_rowsRemoved(), QMenuPrivate::activateAction(), QTableView::currentChanged(), QListView::currentChanged(), QTreeView::currentChanged(), QStatusBar::hideOrShow(), QTreeViewPrivate::insertViewItems(), QTreeViewPrivate::removeViewItems(), QAbstractItemView::reset(), QTableView::selectionChanged(), QListView::selectionChanged(), QTreeView::selectionChanged(), and QTabBar::setCurrentIndex().
 {
     return accessibility_active;
 }
queryAccessibleInterface()
QAccessibleInterface * QAccessible::queryAccessibleInterface (QObject * object) static
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
The function calls all installed factory functions (from most recently installed to least recently installed) until one is found that provides an interface for the class of object. If no factory can provide an accessibility implementation for the class the function loads installed accessibility plugins, and tests if any of the plugins can provide the implementation.
If no implementation for the object's class is available, the function tries to find an implementation for the object's parent class, using the above strategy.
Warning
The caller is responsible for deleting the returned interface after use.
Definition at line 622 of file qaccessible.cpp.
Referenced by QAbstractItemViewPrivate::_q_columnsInserted(), QAbstractItemViewPrivate::_q_columnsRemoved(), QAbstractItemViewPrivate::_q_layoutChanged(), QAbstractItemViewPrivate::_q_rowsInserted(), QAbstractItemViewPrivate::_q_rowsRemoved(), QAccessibleItemView::accessibleAt(), AccessibleElement::AccessibleElement(), applicationEventHandler(), QAccessibleItemView::columnHeader(), QAccessibleWidget::navigate(), QAccessibleTable2::navigate(), QAccessibleAbstractScrollArea::navigate(), QAccessibleMenuItem::navigate(), QAccessibleApplication::navigate(), QAccessibleDisplay::navigate(), QAccessibleWidgetStack::navigate(), QAccessibleStackedWidget::navigate(), QAccessibleTable2Cell::navigate(), QAccessibleToolBox::navigate(), QAccessibleMdiArea::navigate(), QAccessibleMdiSubWindow::navigate(), QAccessibleWorkspace::navigate(), QAccessibleComboBox::navigate(), QAccessibleTable2CornerButton::navigate(), QAccessibleCalendarWidget::navigate(), QAccessibleDockWidget::navigate(), QAccessibleMainWindow::navigate(), QtWndProc(), QAccessibleHierarchyManager::registerInterface(), QAccessibleWidget::relationTo(), QAbstractItemView::reset(), QAccessibleWidget::role(), QAccessibleItemView::rowHeader(), QAccessibleAbstractScrollArea::setText(), QAccessibleAbstractScrollArea::state(), QAccessibleMenuItem::state(), QAccessibleTable2Cell::table(), QAccessibleAbstractScrollArea::text(), and updateAccessibility().
 {
     accessibility_active = true;
     QAccessibleInterface *iface = 0;
     if (!object)
         return 0;
     const QMetaObject *mo = object->metaObject();
     while (mo) {
         const QLatin1String cn(mo->className());
         for (int i = qAccessibleFactories()->count(); i > 0; --i) {
             InterfaceFactory factory = qAccessibleFactories()->at(i - 1);
             iface = factory(cn, object);
             if (iface)
                 return iface;
         }
 #ifndef QT_NO_LIBRARY
         QAccessibleFactoryInterface *factory = qobject_cast<QAccessibleFactoryInterface*>(loader()->instance(cn));
         if (factory) {
             iface = factory->create(cn, object);
             if (iface)
                 return iface;
         }
 #endif
         mo = mo->superClass();
     }
     QWidget *widget = qobject_cast<QWidget*>(object);
     if (widget)
         return new QAccessibleWidget(widget);
     else if (object == qApp)
         return new QAccessibleApplication();
     return 0;
 }
removeFactory()
void QAccessible::removeFactory (InterfaceFactory factory) static
Removes factory from the list of installed InterfaceFactories.
Definition at line 570 of file qaccessible.cpp.
 {
     qAccessibleFactories()->removeAll(factory);
 }
setRootObject()
void QAccessible::setRootObject (QObject * object) static
Sets the root accessible object of this application to object.
All other accessible objects in the application can be reached by the client using object navigation.
You should never need to call this function. Qt sets the QApplication object as the root object immediately before the event loop is entered in QApplication::exec().
Use QAccessible::installRootObjectHandler() to redirect the function call to a customized handler function.
See also
queryAccessibleInterface()
Definition at line 2348 of file qaccessible_mac.mm.
Referenced by QApplication::exec().
 {
     // Call installed root object handler if we have one
     if (rootObjectHandler) {
         rootObjectHandler(object);
         return;
     }
     rootObject = object;
 }
updateAccessibility()
void QAccessible::updateAccessibility (QObject * object, int child, Event reason) static
Notifies accessibility clients about a change in object's accessibility information.
reason specifies the cause of the change, for example, ValueChange when the position of a slider has been changed. child is the (1-based) index of the child element that has changed. When child is 0, the object itself has changed.
Call this function whenever the state of your accessible object or one of its sub-elements has been changed either programmatically (e.g. by calling QLabel::setText()) or by user interaction.
If there are no accessibility tools listening to this event, the performance penalty for calling this function is small, but if determining the parameters of the call is expensive you can test isActive() to avoid unnecessary computations.
Definition at line 2369 of file qaccessible_mac.mm.
Referenced by QMenuBarPrivate::_q_actionHovered(), QAbstractItemViewPrivate::_q_columnsInserted(), QAbstractItemViewPrivate::_q_columnsRemoved(), QPlainTextEditPrivate::_q_cursorPositionChanged(), QComboBoxPrivate::_q_dataChanged(), QComboBoxPrivate::_q_emitCurrentIndexChanged(), QAbstractItemViewPrivate::_q_layoutChanged(), QAbstractItemViewPrivate::_q_rowsInserted(), QAbstractItemViewPrivate::_q_rowsRemoved(), QLineEditPrivate::_q_selectionChanged(), QMenuPrivate::activateAction(), QDragManager::cancel(), QWidget::changeEvent(), QComboBox::clear(), QComboBox::clearEditText(), QWidget::clearFocus(), QTableView::currentChanged(), QListView::currentChanged(), QTreeView::currentChanged(), QDragManager::drag(), QOleDropTarget::Drop(), QLineControl::emitCursorPositionChanged(), QWidgetPrivate::hide_helper(), QWidgetPrivate::hideChildren(), QMenu::hideEvent(), QStatusBar::hideOrShow(), QTreeViewPrivate::insertViewItems(), QLineControl::internalSetText(), QAbstractSpinBox::keyPressEvent(), QMenu::popup(), QWhatsThisPrivate::QWhatsThisPrivate(), QAbstractButtonPrivate::refresh(), QTreeViewPrivate::removeViewItems(), QAbstractItemView::reset(), QTextControlPrivate::selectionChanged(), QTableView::selectionChanged(), QListView::selectionChanged(), QTreeView::selectionChanged(), QWidget::setAccessibleDescription(), QWidget::setAccessibleName(), QGroupBox::setChecked(), QTabBar::setCurrentIndex(), QPushButton::setDefault(), QComboBox::setEditText(), QWidget::setFocus(), QGraphicsScenePrivate::setFocusItemHelper(), QAbstractButton::setText(), QLabel::setText(), QGroupBox::setTitle(), QProgressBar::setValue(), QAbstractSlider::setValue(), QDialog::setVisible(), QWidgetPrivate::show_helper(), QMessageBox::showEvent(), QGraphicsItem::updateMicroFocus(), QWidget::updateMicroFocus(), QAbstractSpinBoxPrivate::updateState(), QWhatsThisPrivate::~QWhatsThisPrivate(), and QWidget::~QWidget().
 {
     // Call installed update handler if we have one.
     if (updateHandler) {
         updateHandler(object, child, reason);
         return;
     }
 #ifndef QT_MAC_USE_COCOA
     // Return if the mac accessibility is not enabled.
     if(!AXAPIEnabled())
         return;
      // Work around crash, disable accessiblity for focus frames.
      if (qstrcmp(object->metaObject()->className(), "QFocusFrame") == 0)
         return;
 //    qDebug() << "updateAccessibility" << object << child << hex << reason;
     if (reason == ObjectShow) {
         QAInterface interface = QAInterface(QAccessible::queryAccessibleInterface(object), child);
         accessibleHierarchyManager()->registerInterface(interface);
     }
     const QAElement element = accessibleHierarchyManager()->lookup(object, child);
     if (element.isValid() == false)
         return;
     CFStringRef notification = 0;
     if(object && object->isWidgetType() && reason == ObjectCreated) {
         notification = CFStringRef(QAXWindowCreatedNotification);
     } else if(reason == ValueChanged) {
         notification = CFStringRef(QAXValueChangedNotification);
     } else if(reason == MenuStart) {
         notification = CFStringRef(QAXMenuOpenedNotification);
     } else if(reason == MenuEnd) {
         notification = CFStringRef(QAXMenuClosedNotification);
     } else if(reason == LocationChanged) {
         notification = CFStringRef(QAXWindowMovedNotification);
     } else if(reason == ObjectShow || reason == ObjectHide ) {
         // When a widget is deleted we get a ObjectHide before the destroyed(QObject *)
         // signal is emitted (which makes sense). However, at this point we are in the
         // middle of the QWidget destructor which means that we have to be careful when
         // using the widget pointer. Since we can't control what the accessibilty interfaces
         // does when navigate() is called below we ignore the hide update in this case.
         // (the widget will be deleted soon anyway.)
         extern QWidgetPrivate * qt_widget_private(QWidget *);
         if (QWidget *widget = qobject_cast<QWidget*>(object)) {
             if (qt_widget_private(widget)->data.in_destructor)
                 return;
             // Check widget parent as well, special case for preventing crash
             // when the viewport() of an abstract scroll area is hidden when
             // the QWidget destructor hides all its children.
             QWidget *parentWidget = widget->parentWidget();
             if (parentWidget && qt_widget_private(parentWidget)->data.in_destructor)
                 return;
         }
         // There is no equivalent Mac notification for ObjectShow/Hide, so we call HIObjectSetAccessibilityIgnored
         // and isItInteresting which will mark the HIObject accociated with the element as ignored if the
         // QAccessible::Invisible state bit is set.
         QAInterface interface = accessibleHierarchyManager()->lookup(element);
         if (interface.isValid()) {
             HIObjectSetAccessibilityIgnored(element.object(), !isItInteresting(interface));
         }
         // If the interface manages its own children, also check if we should ignore those.
         if (isItemView(interface) == false && managesChildren(interface)) {
             for (int i = 1; i <= interface.childCount(); ++i) {
                 QAInterface childInterface = interface.navigate(QAccessible::Child, i);
                 if (childInterface.isValid() && childInterface.isHIView() == false) {
                     const QAElement element = accessibleHierarchyManager()->lookup(childInterface);
                     if (element.isValid()) {
                         HIObjectSetAccessibilityIgnored(element.object(), !isItInteresting(childInterface));
                     }
                 }
             }
         }
     } else if(reason == Focus) {
         if(object && object->isWidgetType()) {
             QWidget *w = static_cast<QWidget*>(object);
             if(w->isWindow())
                 notification = CFStringRef(QAXFocusedWindowChangedNotification);
             else
                 notification = CFStringRef(QAXFocusedUIElementChangedNotification);
         }
     }
     if (!notification)
         return;
     AXNotificationHIObjectNotify(notification, element.object(), element.id());
 #endif
 }
Properties
rootObjectHandler
RootObjectHandler QAccessible::rootObjectHandler static private
Definition at line 338 of file qaccessible.h.
Referenced by installRootObjectHandler().
updateHandler
UpdateHandler QAccessible::updateHandler static private
Definition at line 337 of file qaccessible.h.
Referenced by installUpdateHandler().
The documentation for this class was generated from the following files:
/src/gui/accessible/qaccessible.h
/src/gui/accessible/qaccessible.cpp
/src/gui/accessible/qaccessible_mac.mm
/src/gui/accessible/qaccessible_unix.cpp
/src/gui/accessible/qaccessible_win.cpp