Qt 4.8: QListView Class Reference
QListView Class Reference
The QListView class provides a list or icon view onto a model.
#include <qlistview.h>
Public Types
enum Flow { LeftToRight, TopToBottom }
enum LayoutMode { SinglePass, Batched }
enum Movement { Static, Free, Snap }
enum ResizeMode { Fixed, Adjust }
enum ViewMode { ListMode, IconMode }
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Signals
void indexesMoved (const QModelIndexList &indexes)
This signal is emitted when the specified indexes are moved in the view.
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int batchSize () const
void clearPropertyFlags ()
Clears the QListView-specific property flags.
void doItemsLayout ()
Layout the items according to the flow and wrapping properties.
Flow flow () const
QSize gridSize () const
QModelIndex indexAt (const QPoint &p) const
Reimplemented Function
bool isRowHidden (int row) const
Returns true if the row is hidden; otherwise returns false.
bool isSelectionRectVisible () const
bool isWrapping () const
LayoutMode layoutMode () const
int modelColumn () const
Movement movement () const
QListView (QWidget *parent=0)
Creates a new QListView with the given parent to view a model.
void reset ()
ResizeMode resizeMode () const
void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
Reimplemented Function
void setBatchSize (int batchSize)
void setFlow (Flow flow)
void setGridSize (const QSize &size)
void setLayoutMode (LayoutMode mode)
void setModelColumn (int column)
void setMovement (Movement movement)
void setResizeMode (ResizeMode mode)
void setRootIndex (const QModelIndex &index)
void setRowHidden (int row, bool hide)
If hide is true, the given row will be hidden; otherwise the row will be shown.
void setSelectionRectVisible (bool show)
void setSpacing (int space)
void setUniformItemSizes (bool enable)
void setViewMode (ViewMode mode)
void setWordWrap (bool on)
void setWrapping (bool enable)
int spacing () const
bool uniformItemSizes () const
ViewMode viewMode () const
QRect visualRect (const QModelIndex &index) const
Reimplemented Function
bool wordWrap () const
~QListView ()
Destroys the view.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
virtual void keyboardSearch (const QString &search)
Moves to and selects the item best matching the string search.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
virtual void setModel (QAbstractItemModel *model)
Sets the model for the view to present.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
virtual void setSelectionModel (QItemSelectionModel *selectionModel)
Sets the current selection model to the given selectionModel.
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
virtual int sizeHintForColumn (int column) const
Returns the width size hint for the specified column or -1 if there is no model.
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
virtual int sizeHintForRow (int row) const
Returns the height size hint for the specified row or -1 if there is no model.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
QSize contentsSize () const
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Reimplemented Function
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Reimplemented Function
void dragLeaveEvent (QDragLeaveEvent *e)
Reimplemented Function
void dragMoveEvent (QDragMoveEvent *e)
Reimplemented Function
void dropEvent (QDropEvent *e)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
int horizontalOffset () const
Reimplemented Function
void internalDrag (Qt::DropActions supportedActions)
Called whenever the user starts dragging items and the items are movable, enabling internal dragging and dropping of items.
void internalDrop (QDropEvent *e)
Called whenever items from the view is dropped on the viewport.
bool isIndexHidden (const QModelIndex &index) const
Reimplemented Function
void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
Reimplemented Function
void paintEvent (QPaintEvent *e)
Reimplemented Function
QListView (QListViewPrivate &, QWidget *parent=0)
QRect rectForIndex (const QModelIndex &index) const
Returns the rectangle of the item at position index in the model.
void resizeContents (int width, int height)
Resize the internal contents to width and height and set the scroll bar ranges accordingly.
void resizeEvent (QResizeEvent *e)
Reimplemented Function
void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
Reimplemented Function
void rowsInserted (const QModelIndex &parent, int start, int end)
Reimplemented Function
void scrollContentsBy (int dx, int dy)
Scroll the view contents by dx and dy.
QModelIndexList selectedIndexes () const
Reimplemented Function
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Reimplemented Function
void setPositionForIndex (const QPoint &position, const QModelIndex &index)
Sets the contents position of the item at index in the model to the given position.
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
Reimplemented Function
void startDrag (Qt::DropActions supportedActions)
Reimplemented Function
void timerEvent (QTimerEvent *e)
Reimplemented Function
void updateGeometries ()
Reimplemented Function
int verticalOffset () const
Reimplemented Function
QStyleOptionViewItem viewOptions () const
Reimplemented Function
QRegion visualRegionForSelection (const QItemSelection &selection) const
Since 4.
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
This function is called with the given event when a key event is sent to the widget.
void mouseDoubleClickEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is double clicked inside the widget.
void mousePressEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is pressed while the cursor is inside the widget.
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
State state () const
Returns the item view's state.
void stopAutoScroll ()
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
bool viewportEvent (QEvent *event)
This function is used to handle tool tips, and What's This? mode, if the given event is a QEvent::ToolTip,or a QEvent::WhatsThis.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
int visualIndex (const QModelIndex &index) const
Properties
int batchSize
the number of items laid out in each batch if layoutMode is set to Batched
Flow flow
which direction the items layout should flow.
QSize gridSize
the size of the layout grid
bool isWrapping
whether the items layout should wrap.
LayoutMode layoutMode
determines whether the layout of items should happen immediately or be delayed.
int modelColumn
the column in the model that is visible
Movement movement
whether the items can be moved freely, are snapped to a grid, or cannot be moved at all.
ResizeMode resizeMode
whether the items are laid out again when the view is resized.
bool selectionRectVisible
if the selection rectangle should be visible
int spacing
the space around the items in the layout
bool uniformItemSizes
whether all items in the listview have the same size
ViewMode viewMode
the view mode of the QListView.
bool wordWrap
the item text word-wrapping policy
Friends
class QAccessibleItemView
Additional Inherited Members
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
virtual void selectAll ()
Selects all items in the view.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarAction (int action)
virtual void horizontalScrollbarValueChanged (int value)
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void verticalScrollbarAction (int action)
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QListView class provides a list or icon view onto a model.
A QListView presents items stored in a model, either as a simple non-hierarchical list, or as a collection of icons. This class is used to provide lists and icon views that were previously provided by the QListBox and QIconView classes, but using the more flexible approach provided by Qt's model/view architecture.
The QListView class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
This view does not display horizontal or vertical headers; to display a list of items with a horizontal header, use QTreeView instead.
QListView implements the interfaces defined by the QAbstractItemView class to allow it to display data provided by models derived from the QAbstractItemModel class.
Items in a list view can be displayed using one of two view modes: In ListMode , the items are displayed in the form of a simple list; in IconMode , the list view takes the form of an icon view in which the items are displayed with icons like files in a file manager. By default, the list view is in ListMode . To change the view mode, use the setViewMode() function, and to determine the current view mode, use viewMode().
Items in these views are laid out in the direction specified by the flow() of the list view. The items may be fixed in place, or allowed to move, depending on the view's movement() state.
If the items in the model cannot be completely laid out in the direction of flow, they can be wrapped at the boundary of the view widget; this depends on isWrapping(). This property is useful when the items are being represented by an icon view.
The resizeMode() and layoutMode() govern how and when the items are laid out. Items are spaced according to their spacing(), and can exist within a notional grid of size specified by gridSize(). The items can be rendered as large or small icons depending on their iconSize().
Screenshot of a Windows XP style list view
Screenshot of a Macintosh style table view
Screenshot of a Plastique style table view
A Windows XP Style Widget Gallery{Windows XP style} list view. A Macintosh Style Widget Gallery{Macintosh style} list view. A Plastique Style Widget Gallery{Plastique style} list view.
Improving Performance
It is possible to give the view hints about the data it is handling in order to improve its performance when displaying large numbers of items. One approach that can be taken for views that are intended to display items with equal sizes is to set the uniformItemSizes property to true.
See also
{View Classes}, QTreeView, QTableView, QListWidget
Definition at line 57 of file qlistview.h.
Enumerations
Flow
enum QListView::Flow
LeftToRight The items are laid out in the view from the left to the right.
TopToBottom The items are laid out in the view from the top to the bottom.
Enumerator
LeftToRight
TopToBottom
Definition at line 77 of file qlistview.h.
 { LeftToRight, TopToBottom };
LayoutMode
enum QListView::LayoutMode
SinglePass The items are laid out all at once.
Batched The items are laid out in batches of batchSize items.
See also
batchSize
Enumerator
SinglePass
Batched
Definition at line 79 of file qlistview.h.
 { SinglePass, Batched };
Movement
enum QListView::Movement
Static The items cannot be moved by the user.
Free The items can be moved freely by the user.
Snap The items snap to the specified grid when moved; see setGridSize().
Enumerator
Static
Free
Snap
Definition at line 76 of file qlistview.h.
 { Static, Free, Snap };
ResizeMode
enum QListView::ResizeMode
Fixed The items will only be laid out the first time the view is shown.
Adjust The items will be laid out every time the view is resized.
Enumerator
Fixed
Adjust
Definition at line 78 of file qlistview.h.
 { Fixed, Adjust };
ViewMode
enum QListView::ViewMode
ListMode The items are laid out using TopToBottom flow, with Small size and Static movement
IconMode The items are laid out using LeftToRight flow, with Large size and Free movement
Enumerator
ListMode
IconMode
Definition at line 80 of file qlistview.h.
 { ListMode, IconMode };
Constructors and Destructors
QListView() [1/2]
QListView::QListView (QWidget * parent = 0) explicit
Creates a new QListView with the given parent to view a model.
Use setModel() to set the model.
Definition at line 185 of file qlistview.cpp.
     : QAbstractItemView(*new QListViewPrivate, parent)
 {
     setViewMode(ListMode);
     setSelectionMode(SingleSelection);
     setAttribute(Qt::WA_MacShowFocusRect);
     Q_D(QListView);               // We rely on a qobject_cast for PM_DefaultFrameWidth to change
     d->updateStyledFrameWidths(); // hence we have to force an update now that the object has been constructed
 }
~QListView()
QListView::~QListView ()
Destroys the view.
Definition at line 211 of file qlistview.cpp.
 {
 }
QListView() [2/2]
QListView::QListView (QListViewPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 198 of file qlistview.cpp.
     : QAbstractItemView(dd, parent)
 {
     setViewMode(ListMode);
     setSelectionMode(SingleSelection);
     setAttribute(Qt::WA_MacShowFocusRect);
     Q_D(QListView);               // We rely on a qobject_cast for PM_DefaultFrameWidth to change
     d->updateStyledFrameWidths(); // hence we have to force an update now that the object has been constructed
 }
Functions
batchSize()
int QListView::batchSize () const
Referenced by setBatchSize().
clearPropertyFlags()
void QListView::clearPropertyFlags ()
Clears the QListView-specific property flags.
See viewMode.
Properties inherited from QAbstractItemView are not covered by the property flags. Specifically, dragEnabled and acceptsDrops are computed by QListView when calling setMovement() or setViewMode().
Definition at line 554 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->modeProperties = 0;
 }
contentsSize()
QSize QListView::contentsSize () const protected
Warning
This function is not part of the public interface.
Definition at line 759 of file qlistview.cpp.
Referenced by QComboBoxListView::resizeEvent(), setSelection(), and updateGeometries().
 {
     Q_D(const QListView);
     return d->contentsSize();
 }
currentChanged()
void QListView::currentChanged (const QModelIndex & current, const QModelIndex & previous) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3242 of file qlistview.cpp.
Referenced by QFontListView::currentChanged(), QSidebar::init(), and QSidebar::selectUrl().
 {
 #ifndef QT_NO_ACCESSIBILITY
     if (QAccessible::isActive()) {
         if (current.isValid()) {
             int entry = visualIndex(current) + 1;
 #ifdef Q_WS_X11
             QAccessible::updateAccessibility(this, entry, QAccessible::Focus);
 #else
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::Focus);
 #endif
         }
     }
 #endif
     QAbstractItemView::currentChanged(current, previous);
 }
dataChanged()
void QListView::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 768 of file qlistview.cpp.
 {
     d_func()->commonListView->dataChanged(topLeft, bottomRight);
     QAbstractItemView::dataChanged(topLeft, bottomRight);
 }
doItemsLayout()
void QListView::doItemsLayout () virtual
Layout the items according to the flow and wrapping properties.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 1507 of file qlistview.cpp.
 {
     Q_D(QListView);
     // showing the scroll bars will trigger a resize event,
     // so we set the state to expanding to avoid
     // triggering another layout
     QAbstractItemView::State oldState = state();
     setState(ExpandingState);
     if (d->model->columnCount(d->root) > 0) { // no columns means no contents
         d->resetBatchStartRow();
         if (layoutMode() == SinglePass)
             d->doItemsLayout(d->model->rowCount(d->root)); // layout everything
         else if (!d->batchLayoutTimer.isActive()) {
             if (!d->doItemsLayout(d->batchSize)) // layout is done
                 d->batchLayoutTimer.start(0, this); // do a new batch as fast as possible
         }
     }
     QAbstractItemView::doItemsLayout();
     setState(oldState);        // restoring the oldState
 }
dragLeaveEvent()
void QListView::dragLeaveEvent (QDragLeaveEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 908 of file qlistview.cpp.
 {
     if (!d_func()->commonListView->filterDragLeaveEvent(e))
         QAbstractItemView::dragLeaveEvent(e);
 }
dragMoveEvent()
void QListView::dragMoveEvent (QDragMoveEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 893 of file qlistview.cpp.
 {
     Q_D(QListView);
     if (!d->commonListView->filterDragMoveEvent(e)) {
         if (viewMode() == QListView::ListMode && flow() == QListView::LeftToRight)
             static_cast<QListModeViewBase *>(d->commonListView)->dragMoveEvent(e);
         else
             QAbstractItemView::dragMoveEvent(e);
     }
 }
dropEvent()
void QListView::dropEvent (QDropEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Reimplemented in QListWidget.
Definition at line 917 of file qlistview.cpp.
Referenced by QListWidget::addItems(), and QListWidget::dropEvent().
 {
     if (!d_func()->commonListView->filterDropEvent(e))
         QAbstractItemView::dropEvent(e);
 }
event()
bool QListView::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Reimplemented in QListWidget.
Definition at line 1693 of file qlistview.cpp.
Referenced by QListWidget::addItems(), QSidebar::event(), and QListWidget::event().
 {
     return QAbstractItemView::event(e);
 }
flow()
Flow QListView::flow () const
Referenced by dragMoveEvent(), paintEvent(), and setFlow().
gridSize()
QSize QListView::gridSize () const
Referenced by setGridSize(), and setSelection().
horizontalOffset()
int QListView::horizontalOffset () const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 1127 of file qlistview.cpp.
Referenced by indexAt(), mouseMoveEvent(), paintEvent(), and setSelection().
 {
     return d_func()->commonListView->horizontalOffset();
 }
indexAt()
QModelIndex QListView::indexAt (const QPoint & p) const virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 1112 of file qlistview.cpp.
Referenced by QListWidget::itemAt(), and QSidebar::showContextMenu().
 {
     Q_D(const QListView);
     QRect rect(p.x() + horizontalOffset(), p.y() + verticalOffset(), 1, 1);
     const QVector<QModelIndex> intersectVector = d->intersectingSet(rect);
     QModelIndex index = intersectVector.count() > 0
                         ? intersectVector.last() : QModelIndex();
     if (index.isValid() && visualRect(index).contains(p))
         return index;
     return QModelIndex();
 }
indexesMoved
void QListView::indexesMoved (const QModelIndexList & indexes) signal
This signal is emitted when the specified indexes are moved in the view.
Since
4.2
internalDrag()
void QListView::internalDrag (Qt::DropActions supportedActions) protected
Called whenever the user starts dragging items and the items are movable, enabling internal dragging and dropping of items.
Warning
This function is not part of the public interface.
Definition at line 956 of file qlistview.cpp.
 {
     // ### Qt5: remove that function
     Q_UNUSED(supportedActions);
 }
internalDrop()
void QListView::internalDrop (QDropEvent * event) protected
Called whenever items from the view is dropped on the viewport.
Warning
This function is not part of the public interface.
The event provides additional information.
Definition at line 941 of file qlistview.cpp.
 {
     // ### Qt5: remove that function
     Q_UNUSED(event);
 }
isIndexHidden()
bool QListView::isIndexHidden (const QModelIndex & index) const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 1568 of file qlistview.cpp.
Referenced by selectedIndexes().
 {
     Q_D(const QListView);
     return (d->isHidden(index.row())
             && (index.parent() == d->root)
             && index.column() == d->column);
 }
isRowHidden()
bool QListView::isRowHidden (int row) const
Returns true if the row is hidden; otherwise returns false.
Definition at line 563 of file qlistview.cpp.
Referenced by QListWidget::isItemHidden().
 {
     Q_D(const QListView);
     return d->isHidden(row);
 }
isSelectionRectVisible()
bool QListView::isSelectionRectVisible () const
Definition at line 1684 of file qlistview.cpp.
 {
     Q_D(const QListView);
     return d->isSelectionRectVisible();
 }
isWrapping()
bool QListView::isWrapping () const
Referenced by setWrapping().
layoutMode()
LayoutMode QListView::layoutMode () const
Referenced by doItemsLayout(), and setLayoutMode().
modelColumn()
int QListView::modelColumn () const
Referenced by setModelColumn().
mouseMoveEvent()
void QListView::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 812 of file qlistview.cpp.
 {
     if (!isVisible())
         return;
     Q_D(QListView);
     QAbstractItemView::mouseMoveEvent(e);
     if (state() == DragSelectingState
         && d->showElasticBand
         && d->selectionMode != SingleSelection
         && d->selectionMode != NoSelection) {
         QRect rect(d->pressedPosition, e->pos() + QPoint(horizontalOffset(), verticalOffset()));
         rect = rect.normalized();
         d->viewport->update(d->mapToViewport(rect.united(d->elasticBand)));
         d->elasticBand = rect;
     }
 }
mouseReleaseEvent()
void QListView::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 832 of file qlistview.cpp.
 {
     Q_D(QListView);
     QAbstractItemView::mouseReleaseEvent(e);
     // #### move this implementation into a dynamic class
     if (d->showElasticBand && d->elasticBand.isValid()) {
         d->viewport->update(d->mapToViewport(d->elasticBand));
         d->elasticBand = QRect();
     }
 }
moveCursor()
QModelIndex QListView::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 1143 of file qlistview.cpp.
 {
     Q_D(QListView);
     Q_UNUSED(modifiers);
     QModelIndex current = currentIndex();
     if (!current.isValid()) {
         int rowCount = d->model->rowCount(d->root);
         if (!rowCount)
             return QModelIndex();
         int row = 0;
         while (row < rowCount && d->isHiddenOrDisabled(row))
             ++row;
         if (row >= rowCount)
             return QModelIndex();
         return d->model->index(row, d->column, d->root);
     }
     const QRect initialRect = rectForIndex(current);
     QRect rect = initialRect;
     if (rect.isEmpty()) {
         return d->model->index(0, d->column, d->root);
     }
     if (d->gridSize().isValid()) rect.setSize(d->gridSize());
     QSize contents = d->contentsSize();
     QVector<QModelIndex> intersectVector;
     switch (cursorAction) {
     case MoveLeft:
         while (intersectVector.isEmpty()) {
             rect.translate(-rect.width(), 0);
             if (rect.right() <= 0)
                 return current;
             if (rect.left() < 0)
                 rect.setLeft(0);
             intersectVector = d->intersectingSet(rect);
             d->removeCurrentAndDisabled(&intersectVector, current);
         }
         return d->closestIndex(initialRect, intersectVector);
     case MoveRight:
         while (intersectVector.isEmpty()) {
             rect.translate(rect.width(), 0);
             if (rect.left() >= contents.width())
                 return current;
             if (rect.right() > contents.width())
                 rect.setRight(contents.width());
             intersectVector = d->intersectingSet(rect);
             d->removeCurrentAndDisabled(&intersectVector, current);
         }
         return d->closestIndex(initialRect, intersectVector);
     case MovePageUp:
         // move current by (visibileRowCount - 1) items.
         // rect.translate(0, -rect.height()); will happen in the switch fallthrough for MoveUp.
         rect.moveTop(rect.top() - d->viewport->height() + 2 * rect.height());
         if (rect.top() < rect.height())
             rect.moveTop(rect.height());
     case MovePrevious:
     case MoveUp:
         while (intersectVector.isEmpty()) {
             rect.translate(0, -rect.height());
             if (rect.bottom() <= 0) {
 #ifdef QT_KEYPAD_NAVIGATION
                 if (QApplication::keypadNavigationEnabled()) {
                     int row = d->batchStartRow() - 1;
                     while (row >= 0 && d->isHiddenOrDisabled(row))
                         --row;
                     if (row >= 0)
                         return d->model->index(row, d->column, d->root);
                 }
 #endif
                 return current;
             }
             if (rect.top() < 0)
                 rect.setTop(0);
             intersectVector = d->intersectingSet(rect);
             d->removeCurrentAndDisabled(&intersectVector, current);
         }
         return d->closestIndex(initialRect, intersectVector);
     case MovePageDown:
         // move current by (visibileRowCount - 1) items.
         // rect.translate(0, rect.height()); will happen in the switch fallthrough for MoveDown.
         rect.moveTop(rect.top() + d->viewport->height() - 2 * rect.height());
         if (rect.bottom() > contents.height() - rect.height())
             rect.moveBottom(contents.height() - rect.height());
     case MoveNext:
     case MoveDown:
         while (intersectVector.isEmpty()) {
             rect.translate(0, rect.height());
             if (rect.top() >= contents.height()) {
 #ifdef QT_KEYPAD_NAVIGATION
                 if (QApplication::keypadNavigationEnabled()) {
                     int rowCount = d->model->rowCount(d->root);
                     int row = 0;
                     while (row < rowCount && d->isHiddenOrDisabled(row))
                         ++row;
                     if (row < rowCount)
                         return d->model->index(row, d->column, d->root);
                 }
 #endif
                 return current;
             }
             if (rect.bottom() > contents.height())
                 rect.setBottom(contents.height());
             intersectVector = d->intersectingSet(rect);
             d->removeCurrentAndDisabled(&intersectVector, current);
         }
         return d->closestIndex(initialRect, intersectVector);
     case MoveHome:
         return d->model->index(0, d->column, d->root);
     case MoveEnd:
         return d->model->index(d->batchStartRow() - 1, d->column, d->root);}
     return current;
 }
movement()
Movement QListView::movement () const
Referenced by setMovement().
paintEvent()
void QListView::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QComboBoxListView.
Definition at line 996 of file qlistview.cpp.
Referenced by QComboBoxListView::paintEvent().
 {
     Q_D(QListView);
     if (!d->itemDelegate)
         return;
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     QPainter painter(d->viewport);
     const QVector<QModelIndex> toBeRendered = d->intersectingSet(e->rect().translated(horizontalOffset(), verticalOffset()), false);
     const QModelIndex current = currentIndex();
     const QModelIndex hover = d->hover;
     const QAbstractItemModel *itemModel = d->model;
     const QItemSelectionModel *selections = d->selectionModel;
     const bool focus = (hasFocus() || d->viewport->hasFocus()) && current.isValid();
     const bool alternate = d->alternatingColors;
     const QStyle::State state = option.state;
     const QAbstractItemView::State viewState = this->state();
     const bool enabled = (state & QStyle::State_Enabled) != 0;
     bool alternateBase = false;
     int previousRow = -2; // trigger the alternateBase adjustment on first pass
     int maxSize = (flow() == TopToBottom)
         ? qMax(viewport()->size().width(), d->contentsSize().width()) - 2 * d->spacing()
         : qMax(viewport()->size().height(), d->contentsSize().height()) - 2 * d->spacing();
     QVector<QModelIndex>::const_iterator end = toBeRendered.constEnd();
     for (QVector<QModelIndex>::const_iterator it = toBeRendered.constBegin(); it != end; ++it) {
         Q_ASSERT((*it).isValid());
         option.rect = visualRect(*it);
         if (flow() == TopToBottom)
             option.rect.setWidth(qMin(maxSize, option.rect.width()));
         else
             option.rect.setHeight(qMin(maxSize, option.rect.height()));
         option.state = state;
         if (selections && selections->isSelected(*it))
             option.state |= QStyle::State_Selected;
         if (enabled) {
             QPalette::ColorGroup cg;
             if ((itemModel->flags(*it) & Qt::ItemIsEnabled) == 0) {
                 option.state &= ~QStyle::State_Enabled;
                 cg = QPalette::Disabled;
             } else {
                 cg = QPalette::Normal;
             }
             option.palette.setCurrentColorGroup(cg);
         }
         if (focus && current == *it) {
             option.state |= QStyle::State_HasFocus;
             if (viewState == EditingState)
                 option.state |= QStyle::State_Editing;
         }
         if (*it == hover)
             option.state |= QStyle::State_MouseOver;
         else
             option.state &= ~QStyle::State_MouseOver;
         if (alternate) {
             int row = (*it).row();
             if (row != previousRow + 1) {
                 // adjust alternateBase according to rows in the "gap"
                 if (!d->hiddenRows.isEmpty()) {
                     for (int r = qMax(previousRow + 1, 0); r < row; ++r) {
                         if (!d->isHidden(r))
                             alternateBase = !alternateBase;
                     }
                 } else {
                     alternateBase = (row & 1) != 0;
                 }
             }
             if (alternateBase) {
                 option.features |= QStyleOptionViewItemV2::Alternate;
             } else {
                 option.features &= ~QStyleOptionViewItemV2::Alternate;
             }
             // draw background of the item (only alternate row). rest of the background
             // is provided by the delegate
             QStyle::State oldState = option.state;
             option.state &= ~QStyle::State_Selected;
             style()->drawPrimitive(QStyle::PE_PanelItemViewRow, &option, &painter, this);
             option.state = oldState;
             alternateBase = !alternateBase;
             previousRow = row;
         }
         d->delegateForIndex(*it)->paint(&painter, option, *it);
     }
 #ifndef QT_NO_DRAGANDDROP
     d->commonListView->paintDragDrop(&painter);
 #endif
 #ifndef QT_NO_RUBBERBAND
     // #### move this implementation into a dynamic class
     if (d->showElasticBand && d->elasticBand.isValid()) {
         QStyleOptionRubberBand opt;
         opt.initFrom(this);
         opt.shape = QRubberBand::Rectangle;
         opt.opaque = false;
         opt.rect = d->mapToViewport(d->elasticBand, false).intersected(
             d->viewport->rect().adjusted(-16, -16, 16, 16));
         painter.save();
         style()->drawControl(QStyle::CE_RubberBand, &opt, &painter);
         painter.restore();
     }
 #endif
 }
rectForIndex()
QRect QListView::rectForIndex (const QModelIndex & index) const protected
Returns the rectangle of the item at position index in the model.
The rectangle is in contents coordinates.
See also
visualRect()
Definition at line 1265 of file qlistview.cpp.
Referenced by moveCursor(), setSelection(), and visualRect().
 {
     return d_func()->rectForIndex(index);
 }
reset()
void QListView::reset () virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 704 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->clear();
     d->hiddenRows.clear();
     QAbstractItemView::reset();
 }
resizeContents()
void QListView::resizeContents (int width, int height) protected
Resize the internal contents to width and height and set the scroll bar ranges accordingly.
Warning
This function is not part of the public interface.
Definition at line 750 of file qlistview.cpp.
Referenced by QComboBoxListView::resizeEvent().
 {
     Q_D(QListView);
     d->setContentsSize(width, height);
 }
resizeEvent()
void QListView::resizeEvent (QResizeEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Reimplemented in QComboBoxListView.
Definition at line 862 of file qlistview.cpp.
Referenced by QComboBoxListView::resizeEvent().
 {
     Q_D(QListView);
     if (d->delayedPendingLayout)
         return;
     QSize delta = e->size() - e->oldSize();
     if (delta.isNull())
       return;
     bool listWrap = (d->viewMode == ListMode) && d->wrapItemText;
     bool flowDimensionChanged = (d->flow == LeftToRight && delta.width() != 0)
                                 || (d->flow == TopToBottom && delta.height() != 0);
     // We post a delayed relayout in the following cases :
     // - we're wrapping
     // - the state is NoState, we're adjusting and the size has changed in the flowing direction
     if (listWrap
         || (state() == NoState && d->resizeMode == Adjust && flowDimensionChanged)) {
         d->doDelayedItemsLayout(100); // wait 1/10 sec before starting the layout
     } else {
         QAbstractItemView::resizeEvent(e);
     }
 }
resizeMode()
ResizeMode QListView::resizeMode () const
Referenced by setResizeMode().
rowsAboutToBeRemoved()
void QListView::rowsAboutToBeRemoved (const QModelIndex & parent, int start, int end) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 789 of file qlistview.cpp.
 {
     Q_D(QListView);
     // if the parent is above d->root in the tree, nothing will happen
     QAbstractItemView::rowsAboutToBeRemoved(parent, start, end);
     if (parent == d->root) {
         QSet<QPersistentModelIndex>::iterator it = d->hiddenRows.begin();
         while (it != d->hiddenRows.end()) {
             int hiddenRow = it->row();
             if (hiddenRow >= start && hiddenRow <= end) {
                 it = d->hiddenRows.erase(it);
             } else {
                 ++it;
             }
         }
     }
     d->clear();
     d->doDelayedItemsLayout();
 }
rowsInserted()
void QListView::rowsInserted (const QModelIndex & parent, int start, int end) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 777 of file qlistview.cpp.
 {
     Q_D(QListView);
     // ### be smarter about inserted items
     d->clear();
     d->doDelayedItemsLayout();
     QAbstractItemView::rowsInserted(parent, start, end);
 }
scrollContentsBy()
void QListView::scrollContentsBy (int dx, int dy) protected virtual
Scroll the view contents by dx and dy.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractScrollArea.
Definition at line 734 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->delayedAutoScroll.stop(); // auto scroll was canceled by the user scrolling
     d->commonListView->scrollContentsBy(dx, dy, d->state == QListView::DragSelectingState);
 }
scrollTo()
void QListView::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 597 of file qlistview.cpp.
Referenced by QListWidget::scrollToItem().
 {
     Q_D(QListView);
     if (index.parent() != d->root || index.column() != d->column)
         return;
     const QRect rect = visualRect(index);
     if (hint == EnsureVisible && d->viewport->rect().contains(rect)) {
         d->viewport->update(rect);
         return;
     }
     if (d->flow == QListView::TopToBottom || d->isWrapping()) // vertical
         verticalScrollBar()->setValue(d->verticalScrollToValue(index, rect, hint));
     if (d->flow == QListView::LeftToRight || d->isWrapping()) // horizontal
         horizontalScrollBar()->setValue(d->horizontalScrollToValue(index, rect, hint));
 }
selectedIndexes()
QModelIndexList QListView::selectedIndexes () const protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1482 of file qlistview.cpp.
Referenced by QListWidget::dropEvent().
 {
     Q_D(const QListView);
     if (!d->selectionModel)
         return QModelIndexList();
     QModelIndexList viewSelected = d->selectionModel->selectedIndexes();
     for (int i = 0; i < viewSelected.count(); ++i) {
         const QModelIndex &index = viewSelected.at(i);
         if (!isIndexHidden(index) && index.parent() == d->root && index.column() == d->column)
             ++i;
         else
             viewSelected.removeAt(i);
     }
     return viewSelected;
 }
selectionChanged()
void QListView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 3262 of file qlistview.cpp.
 {
 #ifndef QT_NO_ACCESSIBILITY
     if (QAccessible::isActive()) {
         // ### does not work properly for selection ranges.
         QModelIndex sel = selected.indexes().value(0);
         if (sel.isValid()) {
             int entry = visualIndex(sel) + 1;
 #ifdef Q_WS_X11
             QAccessible::updateAccessibility(this, entry, QAccessible::Selection);
 #else
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::Selection);
 #endif
         }
         QModelIndex desel = deselected.indexes().value(0);
         if (desel.isValid()) {
             int entry = visualIndex(desel) + 1;
 #ifdef Q_WS_X11
             QAccessible::updateAccessibility(this, entry, QAccessible::SelectionRemove);
 #else
             QAccessible::updateAccessibility(viewport(), entry, QAccessible::SelectionRemove);
 #endif
         }
     }
 #endif
     QAbstractItemView::selectionChanged(selected, deselected);
 }
setBatchSize()
void QListView::setBatchSize (int batchSize)
Definition at line 424 of file qlistview.cpp.
 {
     Q_D(QListView);
     if (batchSize <= 0) {
         qWarning("Invalid batchSize (%d)", batchSize);
         return;
     }
     d->batchSize = batchSize;
 }
setFlow()
void QListView::setFlow (Flow flow)
Definition at line 276 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->modeProperties |= uint(QListViewPrivate::Flow);
     d->flow = flow;
     d->doDelayedItemsLayout();
 }
setGridSize()
void QListView::setGridSize (const QSize & size)
Definition at line 458 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->modeProperties |= uint(QListViewPrivate::GridSize);
     d->setGridSize(size);
     d->doDelayedItemsLayout();
 }
setLayoutMode()
void QListView::setLayoutMode (LayoutMode mode)
Definition at line 366 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->layoutMode = mode;
 }
setModelColumn()
void QListView::setModelColumn (int column)
Definition at line 1586 of file qlistview.cpp.
Referenced by QCompleter::popup(), and QComboBox::setModelColumn().
 {
     Q_D(QListView);
     if (column < 0 || column >= d->model->columnCount(d->root))
         return;
     d->column = column;
     d->doDelayedItemsLayout();
 }
setMovement()
void QListView::setMovement (Movement movement)
Definition at line 236 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->modeProperties |= uint(QListViewPrivate::Movement);
     d->movement = movement;
 #ifndef QT_NO_DRAGANDDROP
     bool movable = (movement != Static);
     setDragEnabled(movable);
     d->viewport->setAcceptDrops(movable);
 #endif
     d->doDelayedItemsLayout();
 }
setPositionForIndex()
void QListView::setPositionForIndex (const QPoint & position, const QModelIndex & index) protected
Sets the contents position of the item at index in the model to the given position.
Since
4.1
If the list view's movement mode is Static or its view mode is ListView, this function will have no effect.
Definition at line 1281 of file qlistview.cpp.
 {
     Q_D(QListView);
     if (d->movement == Static
         || !d->isIndexValid(index)
         || index.parent() != d->root
         || index.column() != d->column)
         return;
     d->executePostedLayout();
     d->commonListView->setPositionForIndex(position, index);
 }
setResizeMode()
void QListView::setResizeMode (ResizeMode mode)
Definition at line 337 of file qlistview.cpp.
Referenced by QFileDialogListView::init().
 {
     Q_D(QListView);
     d->modeProperties |= uint(QListViewPrivate::ResizeMode);
     d->resizeMode = mode;
 }
setRootIndex()
void QListView::setRootIndex (const QModelIndex & index) virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 715 of file qlistview.cpp.
Referenced by QColumnView::createColumn().
 {
     Q_D(QListView);
     d->column = qBound(0, d->column, d->model->columnCount(index) - 1);
     QAbstractItemView::setRootIndex(index);
     // sometimes we get an update before reset() is called
     d->clear();
     d->hiddenRows.clear();
 }
setRowHidden()
void QListView::setRowHidden (int row, bool hide)
If hide is true, the given row will be hidden; otherwise the row will be shown.
Definition at line 573 of file qlistview.cpp.
Referenced by QListWidget::setItemHidden().
 {
     Q_D(QListView);
     const bool hidden = d->isHidden(row);
     if (hide && !hidden)
         d->commonListView->appendHiddenRow(row);
     else if (!hide && hidden)
         d->commonListView->removeHiddenRow(row);
     d->doDelayedItemsLayout();
     d->viewport->update();
 }
setSelection()
void QListView::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags command) protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 1297 of file qlistview.cpp.
 {
     Q_D(QListView);
     if (!d->selectionModel)
         return;
     // if we are wrapping, we can only selecte inside the contents rectangle
     int w = qMax(d->contentsSize().width(), d->viewport->width());
     int h = qMax(d->contentsSize().height(), d->viewport->height());
     if (d->wrap && !QRect(0, 0, w, h).intersects(rect))
         return;
     QItemSelection selection;
     if (rect.width() == 1 && rect.height() == 1) {
         const QVector<QModelIndex> intersectVector = d->intersectingSet(rect.translated(horizontalOffset(), verticalOffset()));
         QModelIndex tl;
         if (!intersectVector.isEmpty())
             tl = intersectVector.last(); // special case for mouse press; only select the top item
         if (tl.isValid() && d->isIndexEnabled(tl))
             selection.select(tl, tl);
     } else {
         if (state() == DragSelectingState) { // visual selection mode (rubberband selection)
             selection = d->selection(rect.translated(horizontalOffset(), verticalOffset()));
         } else { // logical selection mode (key and mouse click selection)
             QModelIndex tl, br;
             // get the first item
             const QRect topLeft(rect.left() + horizontalOffset(), rect.top() + verticalOffset(), 1, 1);
             QVector<QModelIndex> intersectVector = d->intersectingSet(topLeft);
             if (!intersectVector.isEmpty())
                 tl = intersectVector.last();
             // get the last item
             const QRect bottomRight(rect.right() + horizontalOffset(), rect.bottom() + verticalOffset(), 1, 1);
             intersectVector = d->intersectingSet(bottomRight);
             if (!intersectVector.isEmpty())
                 br = intersectVector.last();
             // get the ranges
             if (tl.isValid() && br.isValid()
                 && d->isIndexEnabled(tl)
                 && d->isIndexEnabled(br)) {
                 QRect first = rectForIndex(tl);
                 QRect last = rectForIndex(br);
                 QRect middle;
                 if (d->flow == LeftToRight) {
                     QRect &top = first;
                     QRect &bottom = last;
                     // if bottom is above top, swap them
                     if (top.center().y() > bottom.center().y()) {
                         QRect tmp = top;
                         top = bottom;
                         bottom = tmp;
                     }
                     // if the rect are on differnet lines, expand
                     if (top.top() != bottom.top()) {
                         // top rectangle
                         if (isRightToLeft())
                             top.setLeft(0);
                         else
                             top.setRight(contentsSize().width());
                         // bottom rectangle
                         if (isRightToLeft())
                             bottom.setRight(contentsSize().width());
                         else
                             bottom.setLeft(0);
                     } else if (top.left() > bottom.right()) {
                         if (isRightToLeft())
                             bottom.setLeft(top.right());
                         else
                             bottom.setRight(top.left());
                     } else {
                         if (isRightToLeft())
                             top.setLeft(bottom.right());
                         else
                             top.setRight(bottom.left());
                     }
                     // middle rectangle
                     if (top.bottom() < bottom.top()) {
                         if (gridSize().isValid() && !gridSize().isNull())
                             middle.setTop(top.top() + gridSize().height());
                         else
                             middle.setTop(top.bottom() + 1);
                         middle.setLeft(qMin(top.left(), bottom.left()));
                         middle.setBottom(bottom.top() - 1);
                         middle.setRight(qMax(top.right(), bottom.right()));
                     }
                 } else {    // TopToBottom
                     QRect &left = first;
                     QRect &right = last;
                     if (left.center().x() > right.center().x())
                         qSwap(left, right);
                     int ch = contentsSize().height();
                     if (left.left() != right.left()) {
                         // left rectangle
                         if (isRightToLeft())
                             left.setTop(0);
                         else
                             left.setBottom(ch);
                         // top rectangle
                         if (isRightToLeft())
                             right.setBottom(ch);
                         else
                             right.setTop(0);
                         // only set middle if the
                         middle.setTop(0);
                         middle.setBottom(ch);
                         if (gridSize().isValid() && !gridSize().isNull())
                             middle.setLeft(left.left() + gridSize().width());
                         else
                             middle.setLeft(left.right() + 1);
                         middle.setRight(right.left() - 1);
                     } else if (left.bottom() < right.top()) {
                         left.setBottom(right.top() - 1);
                     } else {
                         right.setBottom(left.top() - 1);
                     }
                 }
                 // do the selections
                 QItemSelection topSelection = d->selection(first);
                 QItemSelection middleSelection = d->selection(middle);
                 QItemSelection bottomSelection = d->selection(last);
                 // merge
                 selection.merge(topSelection, QItemSelectionModel::Select);
                 selection.merge(middleSelection, QItemSelectionModel::Select);
                 selection.merge(bottomSelection, QItemSelectionModel::Select);
             }
         }
     }
     d->selectionModel->select(selection, command);
 }
setSelectionRectVisible()
void QListView::setSelectionRectVisible (bool show)
Definition at line 1677 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->modeProperties |= uint(QListViewPrivate::SelectionRectVisible);
     d->setSelectionRectVisible(show);
 }
setSpacing()
void QListView::setSpacing (int space)
Definition at line 397 of file qlistview.cpp.
 {
     Q_D(QListView);
     d->modeProperties |= uint(QListViewPrivate::Spacing);
     d->setSpacing(space);
     d->doDelayedItemsLayout();
 }
setUniformItemSizes()
void QListView::setUniformItemSizes (bool enable)
Definition at line 1615 of file qlistview.cpp.
Referenced by QSidebar::init(), and QFontComboBox::QFontComboBox().
 {
     Q_D(QListView);
     d->uniformItemSizes = enable;
 }
setViewMode()
void QListView::setViewMode (ViewMode mode)
Definition at line 490 of file qlistview.cpp.
Referenced by QListView().
 {
     Q_D(QListView);
     if (d->commonListView && d->viewMode == mode)
         return;
     d->viewMode = mode;
     delete d->commonListView;
     if (mode == ListMode) {
         d->commonListView = new QListModeViewBase(this, d);
         if (!(d->modeProperties & QListViewPrivate::Wrap))
             d->setWrapping(false);
         if (!(d->modeProperties & QListViewPrivate::Spacing))
             d->setSpacing(0);
         if (!(d->modeProperties & QListViewPrivate::GridSize))
             d->setGridSize(QSize());
         if (!(d->modeProperties & QListViewPrivate::Flow))
             d->flow = TopToBottom;
         if (!(d->modeProperties & QListViewPrivate::Movement))
             d->movement = Static;
         if (!(d->modeProperties & QListViewPrivate::ResizeMode))
             d->resizeMode = Fixed;
         if (!(d->modeProperties & QListViewPrivate::SelectionRectVisible))
             d->showElasticBand = false;
     } else {
         d->commonListView = new QIconModeViewBase(this, d);
         if (!(d->modeProperties & QListViewPrivate::Wrap))
             d->setWrapping(true);
         if (!(d->modeProperties & QListViewPrivate::Spacing))
             d->setSpacing(0);
         if (!(d->modeProperties & QListViewPrivate::GridSize))
             d->setGridSize(QSize());
         if (!(d->modeProperties & QListViewPrivate::Flow))
             d->flow = LeftToRight;
         if (!(d->modeProperties & QListViewPrivate::Movement))
             d->movement = Free;
         if (!(d->modeProperties & QListViewPrivate::ResizeMode))
             d->resizeMode = Fixed;
         if (!(d->modeProperties & QListViewPrivate::SelectionRectVisible))
             d->showElasticBand = true;
     }
 #ifndef QT_NO_DRAGANDDROP
     bool movable = (d->movement != Static);
     setDragEnabled(movable);
     setAcceptDrops(movable);
 #endif
     d->clear();
     d->doDelayedItemsLayout();
 }
setWordWrap()
void QListView::setWordWrap (bool on)
Definition at line 1644 of file qlistview.cpp.
 {
     Q_D(QListView);
     if (d->wrapItemText == on)
         return;
     d->wrapItemText = on;
     d->doDelayedItemsLayout();
 }
setWrapping()
void QListView::setWrapping (bool enable)
Definition at line 308 of file qlistview.cpp.
Referenced by QFileDialogListView::init().
 {
     Q_D(QListView);
     d->modeProperties |= uint(QListViewPrivate::Wrap);
     d->setWrapping(enable);
     d->doDelayedItemsLayout();
 }
spacing()
int QListView::spacing () const
Referenced by setSpacing().
startDrag()
void QListView::startDrag (Qt::DropActions supportedActions) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 926 of file qlistview.cpp.
 {
     if (!d_func()->commonListView->filterStartDrag(supportedActions))
         QAbstractItemView::startDrag(supportedActions);
 }
timerEvent()
void QListView::timerEvent (QTimerEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 846 of file qlistview.cpp.
 {
     Q_D(QListView);
     if (e->timerId() == d->batchLayoutTimer.timerId()) {
         if (d->doItemsLayout(d->batchSize)) { // layout is done
             d->batchLayoutTimer.stop();
             updateGeometries();
             d->viewport->update();
         }
     }
     QAbstractItemView::timerEvent(e);
 }
uniformItemSizes()
bool QListView::uniformItemSizes () const
Referenced by setUniformItemSizes().
updateGeometries()
void QListView::updateGeometries () protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1531 of file qlistview.cpp.
Referenced by timerEvent().
 {
     Q_D(QListView);
     if (geometry().isEmpty() || d->model->rowCount(d->root) <= 0 || d->model->columnCount(d->root) <= 0) {
         horizontalScrollBar()->setRange(0, 0);
         verticalScrollBar()->setRange(0, 0);
     } else {
         QModelIndex index = d->model->index(0, d->column, d->root);
         QStyleOptionViewItemV4 option = d->viewOptionsV4();
         QSize step = d->itemSize(option, index);
         d->commonListView->updateHorizontalScrollBar(step);
         d->commonListView->updateVerticalScrollBar(step);
     }
     QAbstractItemView::updateGeometries();
     // if the scroll bars are turned off, we resize the contents to the viewport
     if (d->movement == Static && !d->isWrapping()) {
         d->layoutChildren(); // we need the viewport size to be updated
         if (d->flow == TopToBottom) {
             if (horizontalScrollBarPolicy() == Qt::ScrollBarAlwaysOff) {
                 d->setContentsSize(viewport()->width(), contentsSize().height());
                 horizontalScrollBar()->setRange(0, 0); // we see all the contents anyway
             }
         } else { // LeftToRight
             if (verticalScrollBarPolicy() == Qt::ScrollBarAlwaysOff) {
                 d->setContentsSize(contentsSize().width(), viewport()->height());
                 verticalScrollBar()->setRange(0, 0); // we see all the contents anyway
             }
         }
     }
 }
verticalOffset()
int QListView::verticalOffset () const protected virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 1135 of file qlistview.cpp.
Referenced by indexAt(), mouseMoveEvent(), paintEvent(), and setSelection().
 {
     return d_func()->commonListView->verticalOffset();
 }
viewMode()
ViewMode QListView::viewMode () const
Referenced by dragMoveEvent(), and setViewMode().
viewOptions()
QStyleOptionViewItem QListView::viewOptions () const protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Reimplemented in QComboBoxListView.
Definition at line 967 of file qlistview.cpp.
Referenced by QComboBoxListView::viewOptions().
 {
     Q_D(const QListView);
     QStyleOptionViewItem option = QAbstractItemView::viewOptions();
     if (!d->iconSize.isValid()) { // otherwise it was already set in abstractitemview
         int pm = (d->viewMode == ListMode
                   ? style()->pixelMetric(QStyle::PM_ListViewIconSize, 0, this)
                   : style()->pixelMetric(QStyle::PM_IconViewIconSize, 0, this));
         option.decorationSize = QSize(pm, pm);
     }
     if (d->viewMode == IconMode) {
         option.showDecorationSelected = false;
         option.decorationPosition = QStyleOptionViewItem::Top;
         option.displayAlignment = Qt::AlignCenter;
     } else {
         option.decorationPosition = QStyleOptionViewItem::Left;
     }
     if (d->gridSize().isValid()) {
         option.rect.setSize(d->gridSize());
     }
     return option;
 }
visualIndex()
int QListView::visualIndex (const QModelIndex & index) const private
Definition at line 3291 of file qlistview.cpp.
 {
     Q_D(const QListView);
     d->executePostedLayout();
     QListViewItem itm = d->indexToListViewItem(index);
     int visualIndex = d->commonListView->itemIndex(itm);
     for (int row = 0; row <= index.row() && visualIndex >= 0; row++) {
         if (d->isHidden(row))
             visualIndex--;
     }
     return visualIndex;
 }
visualRect()
QRect QListView::visualRect (const QModelIndex & index) const virtual
Reimplemented Function
Implements QAbstractItemView.
Definition at line 588 of file qlistview.cpp.
Referenced by indexAt(), paintEvent(), scrollTo(), QListWidget::visualItemRect(), and visualRegionForSelection().
 {
     Q_D(const QListView);
     return d->mapToViewport(rectForIndex(index));
 }
visualRegionForSelection()
QRegion QListView::visualRegionForSelection (const QItemSelection & selection) const protected virtual
Since 4.
Reimplemented Function
7, the returned region only contains rectangles intersecting (or included in) the viewport.
Implements QAbstractItemView.
Definition at line 1441 of file qlistview.cpp.
 {
     Q_D(const QListView);
     // ### NOTE: this is a potential bottleneck in non-static mode
     int c = d->column;
     QRegion selectionRegion;
     const QRect &viewportRect = d->viewport->rect();
     for (int i = 0; i < selection.count(); ++i) {
         if (!selection.at(i).isValid())
             continue;
         QModelIndex parent = selection.at(i).topLeft().parent();
         //we only display the children of the root in a listview
         //we're not interested in the other model indexes
         if (parent != d->root)
             continue;
         int t = selection.at(i).topLeft().row();
         int b = selection.at(i).bottomRight().row();
         if (d->viewMode == IconMode || d->isWrapping()) { // in non-static mode, we have to go through all selected items
             for (int r = t; r <= b; ++r) {
                 const QRect &rect = visualRect(d->model->index(r, c, parent));
                 if (viewportRect.intersects(rect))
                     selectionRegion += rect;
             }
         } else { // in static mode, we can optimize a bit
             while (t <= b && d->isHidden(t)) ++t;
             while (b >= t && d->isHidden(b)) --b;
             const QModelIndex top = d->model->index(t, c, parent);
             const QModelIndex bottom = d->model->index(b, c, parent);
             QRect rect(visualRect(top).topLeft(),
                        visualRect(bottom).bottomRight());
             if (viewportRect.intersects(rect))
                 selectionRegion += rect;
         }
     }
     return selectionRegion;
 }
wordWrap()
bool QListView::wordWrap () const
Referenced by setWordWrap().
Friends and Related Functions
QAccessibleItemView
friend class QAccessibleItemView friend
Definition at line 190 of file qlistview.h.
Properties
batchSize
int QListView::batchSize private
the number of items laid out in each batch if layoutMode is set to Batched
The default value is 100.
Since
4.2
Definition at line 71 of file qlistview.h.
flow
QListView::Flow QListView::flow private
which direction the items layout should flow.
If this property is LeftToRight , the items will be laid out left to right. If the isWrapping property is true, the layout will wrap when it reaches the right side of the visible area. If this property is TopToBottom , the items will be laid out from the top of the visible area, wrapping when it reaches the bottom.
Setting this property when the view is visible will cause the items to be laid out again.
By default, this property is set to TopToBottom .
See also
viewMode
Definition at line 62 of file qlistview.h.
gridSize
QSize QListView::gridSize private
the size of the layout grid
This property is the size of the grid in which the items are laid out. The default is an empty size which means that there is no grid and the layout is not done in a grid. Setting this property to a non-empty size switches on the grid layout. (When a grid layout is in force the spacing property is ignored.)
Setting this property when the view is visible will cause the items to be laid out again.
See also
viewMode
Definition at line 67 of file qlistview.h.
isWrapping
bool QListView::isWrapping private
whether the items layout should wrap.
This property holds whether the layout should wrap when there is no more space in the visible area. The point at which the layout wraps depends on the flow property.
Setting this property when the view is visible will cause the items to be laid out again.
By default, this property is false.
See also
viewMode
Definition at line 63 of file qlistview.h.
layoutMode
QListView::LayoutMode QListView::layoutMode private
determines whether the layout of items should happen immediately or be delayed.
This property holds the layout mode for the items. When the mode is SinglePass (the default), the items are laid out all in one go. When the mode is Batched , the items are laid out in batches of batchSize items, while processing events. This makes it possible to instantly view and interact with the visible items while the rest are being laid out.
See also
viewMode
Definition at line 65 of file qlistview.h.
modelColumn
int QListView::modelColumn private
the column in the model that is visible
By default, this property contains 0, indicating that the first column in the model will be shown.
Definition at line 69 of file qlistview.h.
movement
QListView::Movement QListView::movement private
whether the items can be moved freely, are snapped to a grid, or cannot be moved at all.
This property determines how the user can move the items in the view. Static means that the items can't be moved the user. Free means that the user can drag and drop the items to any position in the view. Snap means that the user can drag and drop the items, but only to the positions in a notional grid signified by the gridSize property.
Setting this property when the view is visible will cause the items to be laid out again.
By default, this property is set to Static .
See also
gridSize, resizeMode, viewMode
Definition at line 61 of file qlistview.h.
resizeMode
QListView::ResizeMode QListView::resizeMode private
whether the items are laid out again when the view is resized.
If this property is Adjust , the items will be laid out again when the view is resized. If the value is Fixed , the items will not be laid out when the view is resized.
By default, this property is set to Fixed .
See also
movement, gridSize, viewMode
Definition at line 64 of file qlistview.h.
selectionRectVisible
QListView::selectionRectVisible private
if the selection rectangle should be visible
Since
4.3
If this property is true then the selection rectangle is visible; otherwise it will be hidden.
Note
The selection rectangle will only be visible if the selection mode is in a mode where more than one item can be selected; i.e., it will not draw a selection rectangle if the selection mode is QAbstractItemView::SingleSelection.
By default, this property is false.
Definition at line 73 of file qlistview.h.
spacing
int QListView::spacing private
the space around the items in the layout
This property is the size of the empty space that is padded around an item in the layout.
Setting this property when the view is visible will cause the items to be laid out again.
By default, this property contains a value of 0.
See also
viewMode
Definition at line 66 of file qlistview.h.
Referenced by QComboBoxPrivateContainer::spacing().
uniformItemSizes
bool QListView::uniformItemSizes private
whether all items in the listview have the same size
Since
4.1
This property should only be set to true if it is guaranteed that all items in the view have the same size. This enables the view to do some optimizations for performance purposes.
By default, this property is false.
Definition at line 70 of file qlistview.h.
viewMode
QListView::ViewMode QListView::viewMode private
the view mode of the QListView.
This property will change the other unset properties to conform with the set view mode. QListView-specific properties that have already been set will not be changed, unless clearPropertyFlags() has been called.
Setting the view mode will enable or disable drag and drop based on the selected movement. For ListMode, the default movement is Static (drag and drop disabled); for IconMode, the default movement is Free (drag and drop enabled).
See also
isWrapping, spacing, gridSize, flow, movement, resizeMode
Definition at line 68 of file qlistview.h.
wordWrap
bool QListView::wordWrap private
the item text word-wrapping policy
Since
4.2
If this property is true then the item text is wrapped where necessary at word-breaks; otherwise it is not wrapped at all. This property is false by default.
Please note that even if wrapping is enabled, the cell will not be expanded to make room for the text. It will print ellipsis for text that cannot be shown, according to the view's QAbstractItemView::textElideMode.
Definition at line 72 of file qlistview.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qlistview.h
/src/gui/itemviews/qlistview.cpp