Qt 4.8: QCursor Class Reference
QCursor Class Reference
The QCursor class provides a mouse cursor with an arbitrary shape.
#include <qcursor.h>
Public Functions
const QBitmap * bitmap () const
Returns the cursor bitmap, or 0 if it is one of the standard cursors.
HCURSOR_or_HANDLE handle () const
Returns a platform-specific cursor handle.
QPoint hotSpot () const
Returns the cursor hot spot, or (0, 0) if it is one of the standard cursors.
const QBitmap * mask () const
Returns the cursor bitmap mask, or 0 if it is one of the standard cursors.
operator QVariant () const
Returns the cursor as a QVariant.
QCursor & operator= (const QCursor &cursor)
Assigns c to this cursor and returns a reference to this cursor.
QPixmap pixmap () const
Returns the cursor pixmap.
QCursor ()
Constructs a cursor with the default arrow shape.
QCursor (Qt::CursorShape shape)
Constructs a cursor with the specified shape.
QCursor (const QBitmap &bitmap, const QBitmap &mask, int hotX=-1, int hotY=-1)
Constructs a custom bitmap cursor.
QCursor (const QPixmap &pixmap, int hotX=-1, int hotY=-1)
Constructs a custom pixmap cursor.
QCursor (const QCursor &cursor)
Constructs a copy of the cursor c.
QCursor (HCURSOR cursor)
Constructs a Qt cursor from the given Windows cursor.
QCursor (Qt::HANDLE cursor)
Constructs a Qt cursor from the given handle.
void setShape (Qt::CursorShape newShape)
Sets the cursor to the shape identified by shape.
Qt::CursorShape shape () const
Returns the cursor shape identifier.
~QCursor ()
Destroys the cursor.
Static Public Functions
static QPoint pos ()
Returns the position of the cursor (hot spot) in global screen coordinates.
static void setPos (int x, int y)
Moves the cursor (hot spot) to the global screen position (x, y).
static void setPos (const QPoint &p)
Moves the cursor (hot spot) to the global screen position at point p.
Properties
QCursorData * d
Friends
void * qt_mac_nsCursorForQCursor (const QCursor &c)
void qt_mac_set_cursor (const QCursor *c)
void qt_mac_updateCursorWithWidgetUnderMouse (QWidget *widgetUnderMouse)
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QCursor &cursor)
Writes the cursor to the stream.
QDataStream & operator>> (QDataStream &stream, QCursor &cursor)
Reads the cursor from the stream.
Detailed Description
The QCursor class provides a mouse cursor with an arbitrary shape.
This class is mainly used to create mouse cursors that are associated with particular widgets and to get and set the position of the mouse cursor.
Qt has a number of standard cursor shapes, but you can also make custom cursor shapes based on a QBitmap, a mask and a hotspot.
To associate a cursor with a widget, use QWidget::setCursor(). To associate a cursor with all widgets (normally for a short period of time), use QApplication::setOverrideCursor().
To set a cursor shape use QCursor::setShape() or use the QCursor constructor which takes the shape as argument, or you can use one of the predefined cursors defined in the Qt::CursorShape enum.
If you want to create a cursor with your own bitmap, either use the QCursor constructor which takes a bitmap and a mask or the constructor which takes a pixmap as arguments.
To set or get the position of the mouse cursor use the static methods QCursor::pos() and QCursor::setPos().
Note: It is possible to create a QCursor before QApplication, but it is not useful except as a place-holder for a real QCursor created after QApplication. Attempting to use a QCursor that was created before QApplication will result in a crash.
A Note for X11 Users
On X11, Qt supports the http://www.xfree86.org/4.3.0/Xcursor.3.html Xcursor library, which allows for full color icon themes. The table below shows the cursor name used for each Qt::CursorShape value. If a cursor cannot be found using the name shown below, a standard X11 cursor will be used instead. Note: X11 does not provide appropriate cursors for all possible Qt::CursorShape values. It is possible that some cursors will be taken from the Xcursor theme, while others will use an internal bitmap cursor.
Shape Qt::CursorShape Value Cursor Name Shape Qt::CursorShape Value Cursor Name
Qt::ArrowCursor left_ptr
Qt::SizeVerCursor size_ver
Qt::UpArrowCursor up_arrow
Qt::SizeHorCursor size_hor
Qt::CrossCursor cross
Qt::SizeBDiagCursor size_bdiag
Qt::IBeamCursor ibeam
Qt::SizeFDiagCursor size_fdiag
Qt::WaitCursor wait
Qt::SizeAllCursor size_all
Qt::BusyCursor left_ptr_watch
Qt::SplitVCursor split_v
Qt::ForbiddenCursor forbidden
Qt::SplitHCursor split_h
Qt::PointingHandCursor pointing_hand
Qt::OpenHandCursor openhand
Qt::WhatsThisCursor whats_this
Qt::ClosedHandCursor closedhand
Qt::DragMoveCursor dnd-move or move Qt::DragCopyCursor dnd-copy or copy
Qt::DragLinkCursor dnd-link or link
See also
QWidget, {fowler}{GUI Design Handbook: Cursors}
Definition at line 89 of file qcursor.h.
Constructors and Destructors
QCursor() [1/7]
QCursor::QCursor ()
Constructs a cursor with the default arrow shape.
Definition at line 433 of file qcursor.cpp.
 {
     if (!QCursorData::initialized) {
         if (QApplication::startingUp()) {
             d = 0;
             return;
         }
         QCursorData::initialize();
     }
     QCursorData *c = qt_cursorTable[0];
     c->ref.ref();
     d = c;
 }
QCursor() [2/7]
QCursor::QCursor (Qt::CursorShape shape)
Constructs a cursor with the specified shape.
See Qt::CursorShape for a list of shapes.
See also
setShape()
Definition at line 454 of file qcursor.cpp.
     : d(0)
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     setShape(shape);
 }
QCursor() [3/7]
QCursor::QCursor (const QBitmap & bitmap, const QBitmap & mask, int hotX = -1, int hotY = -1)
Constructs a custom bitmap cursor.
bitmap and mask make up the bitmap. hotX and hotY define the cursor's hot spot.
If hotX is negative, it is set to the bitmap().width()/2. If hotY is negative, it is set to the bitmap().height()/2.
The cursor bitmap (B) and mask (M) bits are combined like this:
B=1 and M=1 gives black.
B=0 and M=1 gives white.
B=0 and M=0 gives transparent.
B=1 and M=0 gives an XOR'd result under Windows, undefined results on all other platforms.
Use the global Qt color Qt::color0 to draw 0-pixels and Qt::color1 to draw 1-pixels in the bitmaps.
Valid cursor sizes depend on the display hardware (or the underlying window system). We recommend using 32 x 32 cursors, because this size is supported on all platforms. Some platforms also support 16 x 16, 48 x 48, and 64 x 64 cursors.
Note
On Windows CE, the cursor size is fixed. If the pixmap is bigger than the system size, it will be scaled.
See also
QBitmap::QBitmap(), QBitmap::setMask()
Definition at line 392 of file qcursor.cpp.
     : d(0)
 {
     d = QCursorData::setBitmap(bitmap, mask, hotX, hotY);
 }
QCursor() [4/7]
QCursor::QCursor (const QPixmap & pixmap, int hotX = -1, int hotY = -1)
Constructs a custom pixmap cursor.
pixmap is the image. It is usual to give it a mask (set using QPixmap::setMask()). hotX and hotY define the cursor's hot spot.
If hotX is negative, it is set to the pixmap().width()/2. If hotY is negative, it is set to the pixmap().height()/2.
Valid cursor sizes depend on the display hardware (or the underlying window system). We recommend using 32 x 32 cursors, because this size is supported on all platforms. Some platforms also support 16 x 16, 48 x 48, and 64 x 64 cursors.
Note
On Windows CE, the cursor size is fixed. If the pixmap is bigger than the system size, it will be scaled.
See also
QPixmap::QPixmap(), QPixmap::setMask()
Definition at line 333 of file qcursor.cpp.
     : d(0)
 {
     QImage img = pixmap.toImage().convertToFormat(QImage::Format_Indexed8, Qt::ThresholdDither|Qt::AvoidDither);
     QBitmap bm = QBitmap::fromImage(img, Qt::ThresholdDither|Qt::AvoidDither);
     QBitmap bmm = pixmap.mask();
     if (!bmm.isNull()) {
         QBitmap nullBm;
         bm.setMask(nullBm);
     }
     else if (!pixmap.mask().isNull()) {
         QImage mimg = pixmap.mask().toImage().convertToFormat(QImage::Format_Indexed8, Qt::ThresholdDither|Qt::AvoidDither);
         bmm = QBitmap::fromImage(mimg, Qt::ThresholdDither|Qt::AvoidDither);
     }
     else {
         bmm = QBitmap(bm.size());
         bmm.fill(Qt::color1);
     }
     d = QCursorData::setBitmap(bm, bmm, hotX, hotY);
     d->pixmap = pixmap;
 }
QCursor() [5/7]
QCursor::QCursor (const QCursor & cursor)
Constructs a copy of the cursor c.
Definition at line 551 of file qcursor.cpp.
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     d = c.d;
     d->ref.ref();
 }
~QCursor()
QCursor::~QCursor ()
Destroys the cursor.
Definition at line 563 of file qcursor.cpp.
 {
     if (d && !d->ref.deref())
         delete d;
 }
QCursor() [6/7]
QCursor::QCursor (HCURSOR cursor)
Constructs a Qt cursor from the given Windows cursor.
Warning
This function is only available on Windows.
See also
handle()
Definition at line 104 of file qcursor_win.cpp.
 {
     d = new QCursorData(Qt::CustomCursor);
     d->hcurs = handle;
 }
QCursor() [7/7]
QCursor::QCursor (Qt::HANDLE handle)
Constructs a Qt cursor from the given handle.
Warning
This function is only available on X11.
See also
handle()
Definition at line 100 of file qcursor_x11.cpp.
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     d = new QCursorData(Qt::CustomCursor);
     d->hcurs = cursor;
 }
Functions
bitmap()
const QBitmap * QCursor::bitmap () const
Returns the cursor bitmap, or 0 if it is one of the standard cursors.
Definition at line 504 of file qcursor.cpp.
Referenced by QXlibCursor::createCursorBitmap(), and operator<<().
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     return d->bm;
 }
handle()
Qt::HANDLE QCursor::handle () const
Returns a platform-specific cursor handle.
The HCURSOR_or_HANDLE type is HCURSOR on Windows and Qt::HANDLE on X11 and Mac OS X. On Qt for Embedded Linux it is an integer.
Warning
Using the value returned by this function is not portable.
Definition at line 301 of file qcursor_mac.mm.
Referenced by QXlibCursor::changeCursor(), effectiveState(), isServerProcess(), parseGeometry(), QGuiEventDispatcherWin32::processEvents(), QCursor(), qJournalRecordProc(), qstring_to_xtp(), qt_grab_cursor(), qt_mac_set_cursor(), qt_try_modal(), qt_win_set_cursor(), qt_x11_enforce_cursor(), QtWndProc(), QApplication::qwsProcessEvent(), and QETWidget::translateMouseEvent().
 {
     if(!QCursorData::initialized)
         QCursorData::initialize();
     if(d->type == QCursorData::TYPE_None)
         d->update();
     return (Qt::HANDLE)d->mId;
 }
hotSpot()
QPoint QCursor::hotSpot () const
Returns the cursor hot spot, or (0, 0) if it is one of the standard cursors.
Definition at line 540 of file qcursor.cpp.
Referenced by QDirectFBCursor::changeCursor(), QPlatformSoftwareCursor::changeCursor(), QXlibCursor::createCursorBitmap(), and operator<<().
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     return QPoint(d->hx, d->hy);
 }
mask()
const QBitmap * QCursor::mask () const
Returns the cursor bitmap mask, or 0 if it is one of the standard cursors.
Definition at line 516 of file qcursor.cpp.
Referenced by QXlibCursor::createCursorBitmap(), and operator<<().
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     return d->bmm;
 }
operator QVariant()
QCursor::operator QVariant () const
Returns the cursor as a QVariant.
Definition at line 590 of file qcursor.cpp.
 {
     return QVariant(QVariant::Cursor, this);
 }
operator=()
QCursor & QCursor::operator= (const QCursor & cursor)
Assigns c to this cursor and returns a reference to this cursor.
Definition at line 575 of file qcursor.cpp.
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     if (c.d)
         c.d->ref.ref();
     if (d && !d->ref.deref())
         delete d;
     d = c.d;
     return *this;
 }
pixmap()
QPixmap QCursor::pixmap () const
Returns the cursor pixmap.
This is only valid if the cursor is a pixmap cursor.
Definition at line 528 of file qcursor.cpp.
Referenced by QDirectFBCursor::changeCursor(), QPlatformSoftwareCursor::changeCursor(), operator<<(), and QCursor().
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     return d->pixmap;
 }
pos()
QPoint QCursor::pos () static
Returns the position of the cursor (hot spot) in global screen coordinates.
You can call QWidget::mapFromGlobal() to translate it to widget coordinates.
See also
setPos(), QWidget::mapFromGlobal(), QWidget::mapToGlobal()
Definition at line 310 of file qcursor_mac.mm.
Referenced by QDialog::adjustPosition(), QGraphicsViewPrivate::centerView(), QApplicationPrivate::dispatchEnterLeave(), QX11Data::dndEnable(), QAbstractItemView::doAutoScroll(), QWidgetResizeHandler::doMove(), QWidgetResizeHandler::doResize(), QTreeView::drawTree(), QShortcut::event(), QDockWidget::event(), QToolBar::event(), findRealWindow(), QSystemTrayIconSys::findTrayGeometry(), QPlatformSoftwareCursor::getCurrentRect(), QApplicationPrivate::globalEventProcessor(), QAbstractItemView::horizontalScrollbarValueChanged(), QColorDialogPrivate::init(), QFontDialogPrivate::init(), QMenu::internalDelayedPopup(), QGraphicsItem::isUnderMouse(), QWidgetResizeHandler::keyPressEvent(), QApplicationPrivate::leaveModal_sys(), QGraphicsScenePrivate::leaveScene(), QWorkspaceTitleBar::paintEvent(), QMenu::popup(), QContextMenuEvent::QContextMenuEvent(), QCursor(), QMouseEvent::QMouseEvent(), qt_keyrelease_scanner(), qt_mac_update_cursor(), qt_qpa_set_cursor(), QtWndProc(), QWhatsThisPrivate::QWhatsThisPrivate(), QWheelEvent::QWheelEvent(), QMacPinchGestureRecognizer::reset(), QApplicationPrivate::sendSyntheticEnterLeave(), QGraphicsItem::setCursor(), QHeaderView::setOffset(), QTextBrowserPrivate::setSource(), QWizard::sizeHint(), QTreeView::timerEvent(), QPlainTextEdit::timerEvent(), QTextEdit::timerEvent(), QGraphicsItem::unsetCursor(), QMessageBoxPrivate::updateSize(), QAbstractItemView::verticalScrollbarValueChanged(), QSystemTrayIconSys::winEvent(), QApplication::x11EventFilter(), QMouseEvent::~QMouseEvent(), and QWheelEvent::~QWheelEvent().
 {
     return flipPoint([NSEvent mouseLocation]).toPoint();
 }
setPos() [1/2]
void QCursor::setPos (int x, int y) static
Moves the cursor (hot spot) to the global screen position (x, y).
You can call QWidget::mapToGlobal() to translate widget coordinates to global screen coordinates.
See also
pos(), QWidget::mapFromGlobal(), QWidget::mapToGlobal()
Definition at line 315 of file qcursor_mac.mm.
Referenced by QBBScreenEventHandler::handleTouchEvent(), QWidgetResizeHandler::keyPressEvent(), QMdiSubWindow::keyPressEvent(), QTest::mouseEvent(), QCursor(), QHeaderView::setOffset(), and QDialog::setVisible().
 {
 #ifdef QT_MAC_USE_COCOA
     CGPoint pos;
     pos.x = x;
     pos.y = y;
     CGEventRef e = CGEventCreateMouseEvent(0, kCGEventMouseMoved, pos, 0);
     CGEventPost(kCGHIDEventTap, e);
     CFRelease(e);
 #else
     CGWarpMouseCursorPosition(CGPointMake(x, y));
     /* I'm not too keen on doing this, but this makes it a lot easier, so I just
        send the event back through the event system and let it get propagated correctly
        ideally this would not really need to be faked --Sam
     */
     QWidget *widget = 0;
     if(QWidget *grb = QWidget::mouseGrabber())
         widget = grb;
     else
         widget = QApplication::widgetAt(QPoint(x, y));
     if(widget) {
         QMouseEvent me(QMouseEvent::MouseMove, widget->mapFromGlobal(QPoint(x, y)), Qt::NoButton,
                        QApplication::mouseButtons(), QApplication::keyboardModifiers());
         qt_sendSpontaneousEvent(widget, &me);
     }
 #endif
 }
setPos() [2/2]
void QCursor::setPos (const QPoint & p) inline static
Moves the cursor (hot spot) to the global screen position at point p.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 115 of file qcursor.h.
Referenced by setPos().
 { setPos(p.x(), p.y()); }
setShape()
void QCursor::setShape (Qt::CursorShape shape)
Sets the cursor to the shape identified by shape.
See Qt::CursorShape for the list of cursor shapes.
See also
shape()
Definition at line 483 of file qcursor.cpp.
Referenced by operator>>(), and QCursor().
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     QCursorData *c = uint(shape) <= Qt::LastCursor ? qt_cursorTable[shape] : 0;
     if (!c)
         c = qt_cursorTable[0];
     c->ref.ref();
     if (!d) {
         d = c;
     } else {
         if (!d->ref.deref())
             delete d;
         d = c;
     }
 }
shape()
Qt::CursorShape QCursor::shape () const
Returns the cursor shape identifier.
The return value is one of the Qt::CursorShape enum values (cast to an int).
See also
setShape()
Definition at line 469 of file qcursor.cpp.
Referenced by QTextBrowserPrivate::_q_highlightLink(), QWaylandCursor::changeCursor(), QXlibCursor::changeCursor(), QDirectFBCursor::changeCursor(), QPlatformSoftwareCursor::changeCursor(), QCursorData::cleanup(), QScriptEdit::extraAreaMouseEvent(), QCursorData::initialize(), QHeaderView::mouseDoubleClickEvent(), operator<<(), QWidget::setCursor(), and setShape().
 {
     if (!QCursorData::initialized)
         QCursorData::initialize();
     return d->cshape;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QCursor & cursor) related
Writes the cursor to the stream.
See also
{Serializing Qt Data Types}
Definition at line 255 of file qcursor.cpp.
 {
     s << (qint16)c.shape();                        // write shape id to stream
     if (c.shape() == Qt::BitmapCursor) {                // bitmap cursor
         bool isPixmap = false;
         if (s.version() >= 7) {
             isPixmap = !c.pixmap().isNull();
             s << isPixmap;
         }
         if (isPixmap)
             s << c.pixmap();
         else
             s << *c.bitmap() << *c.mask();
         s << c.hotSpot();
     }
     return s;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QCursor & cursor) related
Reads the cursor from the stream.
See also
{Serializing Qt Data Types}
Definition at line 285 of file qcursor.cpp.
 {
     qint16 shape;
     s >> shape;                                        // read shape id from stream
     if (shape == Qt::BitmapCursor) {                // read bitmap cursor
         bool isPixmap = false;
         if (s.version() >= 7)
             s >> isPixmap;
         if (isPixmap) {
             QPixmap pm;
             QPoint hot;
             s >> pm >> hot;
             c = QCursor(pm, hot.x(), hot.y());
         } else {
             QBitmap bm, bmm;
             QPoint hot;
             s >> bm >> bmm >> hot;
             c = QCursor(bm, bmm, hot.x(), hot.y());
         }
     } else {
         c.setShape((Qt::CursorShape)shape);                // create cursor with shape
     }
     return s;
 }
qt_mac_nsCursorForQCursor
void* qt_mac_nsCursorForQCursor (const QCursor & c) friend
Definition at line 100 of file qcursor_mac.mm.
 {
     c.d->update();
     return [[static_cast<NSCursor *>(c.d->curs.cp.nscursor) retain] autorelease];
 }
qt_mac_set_cursor
void qt_mac_set_cursor (const QCursor * c) friend
Definition at line 108 of file qcursor_mac.mm.
 {
 #ifdef QT_MAC_USE_COCOA
     QMacCocoaAutoReleasePool pool;
     [static_cast<NSCursor *>(qt_mac_nsCursorForQCursor(*c)) set];
 #else
     if (!c) {
         currentCursor = 0;
         return;
     }
     c->handle(); //force the cursor to get loaded, if it's not
     if(currentCursor && currentCursor->type == QCursorData::TYPE_ThemeCursor
             && currentCursor->curs.tc.anim)
         currentCursor->curs.tc.anim->stop();
     if(c->d->type == QCursorData::TYPE_ImageCursor) {
         [static_cast<NSCursor *>(c->d->curs.cp.nscursor) set];
     } else if(c->d->type == QCursorData::TYPE_ThemeCursor) {
         if(SetAnimatedThemeCursor(c->d->curs.tc.curs, 0) == themeBadCursorIndexErr) {
             SetThemeCursor(c->d->curs.tc.curs);
         } else {
             if(!c->d->curs.tc.anim)
                 c->d->curs.tc.anim = new QMacAnimateCursor;
             c->d->curs.tc.anim->start(c->d->curs.tc.curs);
         }
     }
     currentCursor = c->d;
 #endif
 }
qt_mac_updateCursorWithWidgetUnderMouse
void qt_mac_updateCursorWithWidgetUnderMouse (QWidget * widgetUnderMouse) friend
Definition at line 144 of file qcursor_mac.mm.
 {
     QCursor cursor(Qt::ArrowCursor);
     if (qt_button_down) {
         // The widget that is currently pressed
         // grabs the mouse cursor:
         widgetUnderMouse = qt_button_down;
         qt_button_down_on_prev_call = true;
     } else if (qt_button_down_on_prev_call) {
         // Grab has been released, so do
         // a full check:
         qt_button_down_on_prev_call = false;
         lastWidgetUnderMouse = 0;
         lastMouseCursorWidget = 0;
     }
     if (QApplication::overrideCursor()) {
         cursor = *QApplication::overrideCursor();
     } else if (grabCursor) {
         cursor = *grabCursor;
     } else if (widgetUnderMouse) {
         if (widgetUnderMouse == lastWidgetUnderMouse) {
             // Optimization that should hit when the widget under
             // the mouse does not change as the mouse moves:
             if (lastMouseCursorWidget)
                 cursor = lastMouseCursorWidget->cursor();
         } else {
             QWidget *w = widgetUnderMouse;
             for (; w; w = w->parentWidget()) {
                 if (w->testAttribute(Qt::WA_SetCursor)) {
                     cursor = w->cursor();
                     break;
                 }
                 if (w->isWindow())
                     break;
             }
             // One final check in case we ran out of parents in the loop:
             if (w && !w->testAttribute(Qt::WA_SetCursor))
                 w = 0;
             lastWidgetUnderMouse = widgetUnderMouse;
             lastMouseCursorWidget = w;
         }
     }
 #ifdef QT_MAC_USE_COCOA
     cursor.d->update();
     NSCursor *nsCursor = static_cast<NSCursor *>(cursor.d->curs.cp.nscursor);
     if ([NSCursor currentCursor] != nsCursor) {
         QMacCocoaAutoReleasePool pool;
         [nsCursor set];
     }
 #else
     qt_mac_set_cursor(&cursor);
 #endif
 }
Properties
d
QCursorData* QCursor::d private
Definition at line 141 of file qcursor.h.
Referenced by bitmap(), hotSpot(), mask(), operator=(), pixmap(), QCursor(), qt_mac_nsCursorForQCursor(), qt_mac_set_cursor(), qt_mac_updateCursorWithWidgetUnderMouse(), setShape(), shape(), and ~QCursor().
The documentation for this class was generated from the following files:
/src/gui/kernel/qcursor.h
/src/gui/kernel/qcursor.cpp
/src/gui/kernel/qcursor_mac.mm
/src/gui/kernel/qcursor_qpa.cpp
/src/gui/kernel/qcursor_qws.cpp
/src/gui/kernel/qcursor_win.cpp
/src/gui/kernel/qcursor_x11.cpp