Qt 4.8: QBBNavigatorEventNotifier Class Reference
QBBNavigatorEventNotifier Class Reference
#include <qbbnavigatoreventnotifier.h>
Public Slots
void start ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QBBNavigatorEventNotifier (QBBNavigatorEventHandler *eventHandler, QObject *parent=0)
~QBBNavigatorEventNotifier ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void readData ()
Private Functions
void handleMessage (const QByteArray &msg, const QByteArray &dat, const QByteArray &id)
void parsePPS (const QByteArray &ppsData, QByteArray &msg, QByteArray &dat, QByteArray &id)
void replyPPS (const QByteArray &res, const QByteArray &id, const QByteArray &dat)
Properties
QBBNavigatorEventHandler * mEventHandler
int mFd
QSocketNotifier * mReadNotifier
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 52 of file qbbnavigatoreventnotifier.h.
Constructors and Destructors
QBBNavigatorEventNotifier()
QBBNavigatorEventNotifier::QBBNavigatorEventNotifier (QBBNavigatorEventHandler * eventHandler, QObject * parent = 0) explicit
Definition at line 63 of file qbbnavigatoreventnotifier.cpp.
     : QObject(parent),
       mEventHandler(eventHandler),
       mFd(-1),
       mReadNotifier(0)
 {
 }
~QBBNavigatorEventNotifier()
QBBNavigatorEventNotifier::~QBBNavigatorEventNotifier ()
Definition at line 71 of file qbbnavigatoreventnotifier.cpp.
 {
     delete mReadNotifier;
     if (mFd != -1)
         qt_safe_close(mFd);
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
     qDebug() << "QBB: navigator event notifier stopped";
 #endif
 }
Functions
handleMessage()
void QBBNavigatorEventNotifier::handleMessage (const QByteArray & msg, const QByteArray & dat, const QByteArray & id) private
Definition at line 180 of file qbbnavigatoreventnotifier.cpp.
Referenced by readData().
 {
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
     qDebug() << "PPS: msg=" << msg << ", dat=" << dat << ", id=" << id;
 #endif
     // check message type
     if (msg == "orientationCheck") {
         const bool result = mEventHandler->handleOrientationCheck(dat.toInt());
         replyPPS(msg, id, result ? "true": "false");
     } else if (msg == "orientation") {
         mEventHandler->handleOrientationChange(dat.toInt());
         replyPPS(msg, id, "");
     } else if (msg == "SWIPE_DOWN") {
         mEventHandler->handleSwipeDown();
     } else if (msg == "exit") {
         mEventHandler->handleExit();
     } else if (msg == "windowActive") {
         mEventHandler->handleWindowGroupActivated(dat);
     } else if (msg == "windowInactive") {
         mEventHandler->handleWindowGroupDeactivated(dat);
     }
 }
parsePPS()
void QBBNavigatorEventNotifier::parsePPS (const QByteArray & ppsData, QByteArray & msg, QByteArray & dat, QByteArray & id) private
Definition at line 101 of file qbbnavigatoreventnotifier.cpp.
Referenced by readData().
 {
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
     qDebug() << "PPS: data=" << ppsData;
 #endif
     // tokenize pps data into lines
     QList<QByteArray> lines = ppsData.split('\n');
     // validate pps object
     if (lines.size() == 0 || lines.at(0) != "@control")
         qFatal("QBB: unrecognized pps object, data=%s", ppsData.constData());
     // parse pps object attributes and extract values
     for (int i = 1; i < lines.size(); i++) {
         // tokenize current attribute
         const QByteArray &attr = lines.at(i);
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
         qDebug() << "PPS: attr=" << attr;
 #endif
         int firstColon = attr.indexOf(':');
         if (firstColon == -1) {
             // abort - malformed attribute
             continue;
         }
         int secondColon = attr.indexOf(':', firstColon + 1);
         if (secondColon == -1) {
             // abort - malformed attribute
             continue;
         }
         QByteArray key = attr.left(firstColon);
         QByteArray value = attr.mid(secondColon + 1);
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
         qDebug() << "PPS: key=" << key;
         qDebug() << "PPS: val=" << value;
 #endif
         // save attribute value
         if (key == "msg")
             msg = value;
         else if (key == "dat")
             dat = value;
         else if (key == "id")
             id = value;
         else
             qFatal("QBB: unrecognized pps attribute, attr=%s", key.constData());
     }
 }
readData
void QBBNavigatorEventNotifier::readData () private slot
Definition at line 204 of file qbbnavigatoreventnotifier.cpp.
Referenced by start().
 {
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
     qDebug() << "QBB: reading navigator data";
 #endif
     // allocate buffer for pps data
     char buffer[PPS_BUFFER_SIZE];
     // attempt to read pps data
     errno = 0;
     int bytes = qt_safe_read(mFd, buffer, PPS_BUFFER_SIZE - 1);
     if (bytes == -1)
         qFatal("QBB: failed to read navigator pps, errno=%d", errno);
     // check if pps data was received
     if (bytes > 0) {
         // ensure data is null terminated
         buffer[bytes] = '\0';
         // process received message
         QByteArray ppsData(buffer);
         QByteArray msg;
         QByteArray dat;
         QByteArray id;
         parsePPS(ppsData, msg, dat, id);
         handleMessage(msg, dat, id);
     }
 }
replyPPS()
void QBBNavigatorEventNotifier::replyPPS (const QByteArray & res, const QByteArray & id, const QByteArray & dat) private
Definition at line 156 of file qbbnavigatoreventnotifier.cpp.
Referenced by handleMessage().
 {
     // construct pps message
     QByteArray ppsData = "res::";
     ppsData += res;
     ppsData += "\nid::";
     ppsData += id;
     if (!dat.isEmpty()) {
         ppsData += "\ndat::";
         ppsData += dat;
     }
     ppsData += "\n";
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
     qDebug() << "PPS reply=" << ppsData;
 #endif
     // send pps message to navigator
     errno = 0;
     int bytes = write(mFd, ppsData.constData(), ppsData.size());
     if (bytes == -1)
         qFatal("QBB: failed to write navigator pps, errno=%d", errno);
 }
start
void QBBNavigatorEventNotifier::start () slot
Definition at line 83 of file qbbnavigatoreventnotifier.cpp.
 {
 #if defined(QBBNAVIGATOREVENTNOTIFIER_DEBUG)
     qDebug() << "QBB: navigator event notifier started";
 #endif
     // open connection to navigator
     errno = 0;
     mFd = qt_safe_open(NAV_CONTROL_PATH, O_RDWR);
     if (mFd == -1) {
         qWarning("QBB: failed to open navigator pps, errno=%d", errno);
         return;
     }
     mReadNotifier = new QSocketNotifier(mFd, QSocketNotifier::Read);
     connect(mReadNotifier, SIGNAL(activated(int)), this, SLOT(readData()));
 }
Properties
mEventHandler
QBBNavigatorEventHandler* QBBNavigatorEventNotifier::mEventHandler private
Definition at line 66 of file qbbnavigatoreventnotifier.h.
Referenced by handleMessage().
mFd
int QBBNavigatorEventNotifier::mFd private
Definition at line 67 of file qbbnavigatoreventnotifier.h.
Referenced by readData(), replyPPS(), start(), and ~QBBNavigatorEventNotifier().
mReadNotifier
QSocketNotifier* QBBNavigatorEventNotifier::mReadNotifier private
Definition at line 68 of file qbbnavigatoreventnotifier.h.
Referenced by start(), and ~QBBNavigatorEventNotifier().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbnavigatoreventnotifier.h
/src/plugins/platforms/blackberry/qbbnavigatoreventnotifier.cpp