Qt 4.8: QTimer Class Reference
QTimer Class Reference
The QTimer class provides repetitive and single-shot timers.
#include <qtimer.h>
Public Slots
void start (int msec)
Starts or restarts the timer with a timeout interval of msec milliseconds.
void start ()
void stop ()
Stops the timer.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void timeout ()
This signal is emitted when the timer times out.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int interval () const
bool isActive () const
Returns true if the timer is running (pending); otherwise returns false.
bool isSingleShot () const
QTimer (QObject *parent=0)
Constructs a timer with the given parent.
void setInterval (int msec)
void setSingleShot (bool singleShot)
int timerId () const
Returns the ID of the timer if the timer is running; otherwise returns -1.
~QTimer ()
Destroys the timer.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void singleShot (int msec, QObject *receiver, const char *member)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
void timerEvent (QTimerEvent *)
Reimplemented Function
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Functions
void killTimer (int)
int startTimer (int)
Properties
bool active
This boolean property is true if the timer is running; otherwise false.
int del
int id
int inter
int interval
the timeout interval in milliseconds
uint nulltimer: 1
uint single: 1
bool singleShot
This static function calls a slot after a given time interval.
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTimer class provides repetitive and single-shot timers.
The QTimer class provides a high-level programming interface for timers. To use it, create a QTimer, connect its timeout() signal to the appropriate slots, and call start(). From then on it will emit the timeout() signal at constant intervals.
Example for a one second (1000 millisecond) timer (from the Analog Clock example):
    QTimer *timer = new QTimer(this);
    connect(timer, SIGNAL(timeout()), this, SLOT(update()));
    timer->start(1000);
From then on, the update() slot is called every second.
You can set a timer to time out only once by calling setSingleShot(true). You can also use the static QTimer::singleShot() function to call a slot after a specified interval:
    QTimer::singleShot(200, this, SLOT(updateCaption()));
In multithreaded applications, you can use QTimer in any thread that has an event loop. To start an event loop from a non-GUI thread, use QThread::exec(). Qt uses the timer's thread affinity to determine which thread will emit the QTimer::timeout() signal. Because of this, you must start and stop the timer in its thread; it is not possible to start a timer from another thread.
As a special case, a QTimer with a timeout of 0 will time out as soon as all the events in the window system's event queue have been processed. This can be used to do heavy work while providing a snappy user interface:
    QTimer *timer = new QTimer(this);
    connect(timer, SIGNAL(timeout()), this, SLOT(processOneThing()));
    timer->start();
processOneThing() will from then on be called repeatedly. It should be written in such a way that it always returns quickly (typically after processing one data item) so that Qt can deliver events to widgets and stop the timer as soon as it has done all its work. This is the traditional way of implementing heavy work in GUI applications; multithreading is now becoming available on more and more platforms, and we expect that zero-millisecond QTimers will gradually be replaced by QThread.
Accuracy and Timer Resolution
Timers will never time out earlier than the specified timeout value and they are not guaranteed to time out at the exact value specified. In many situations, they may time out late by a period of time that depends on the accuracy of the system timers.
The accuracy of timers depends on the underlying operating system and hardware. Most platforms support a resolution of 1 millisecond, though the accuracy of the timer will not equal this resolution in many real-world situations.
If Qt is unable to deliver the requested number of timer clicks, it will silently discard some.
Alternatives to QTimer
An alternative to using QTimer is to call QObject::startTimer() for your object and reimplement the QObject::timerEvent() event handler in your class (which must inherit QObject). The disadvantage is that timerEvent() does not support such high-level features as single-shot timers or signals.
Another alternative to using QTimer is to use QBasicTimer. It is typically less cumbersome than using QObject::startTimer() directly. See Timers for an overview of all three approaches.
Some operating systems limit the number of timers that may be used; Qt tries to work around these limitations.
See also
QBasicTimer, QTimerEvent, QObject::timerEvent(), Timers, {Analog Clock Example}, {Wiggly Example}
Definition at line 56 of file qtimer.h.
Constructors and Destructors
QTimer()
QTimer::QTimer (QObject * parent = 0) explicit
Constructs a timer with the given parent.
Definition at line 147 of file qtimer.cpp.
     : QObject(parent), id(INV_TIMER), inter(0), del(0), single(0), nulltimer(0)
 {
 }
~QTimer()
QTimer::~QTimer ()
Destroys the timer.
Definition at line 169 of file qtimer.cpp.
 {
     if (id != INV_TIMER)                        // stop running timer
         stop();
 }
Functions
interval()
int QTimer::interval () const inline
Definition at line 73 of file qtimer.h.
 { return inter; }
isActive()
bool QTimer::isActive () const inline
Returns true if the timer is running (pending); otherwise returns false.
Definition at line 69 of file qtimer.h.
Referenced by Maemo::IcdPrivate::addrinfo(), QIcdEngine::cancelAsyncConfigurationUpdate(), QNetworkSessionPrivateImpl::close(), QSmoothedAnimation::delayedStop(), QComboBoxPrivateContainer::eventFilter(), QSmoothedAnimation::init(), QComboBoxPrivateContainer::mouseReleaseEvent(), QNetworkSessionPrivateImpl::open(), Maemo::IcdPrivate::scan(), QWSServer::screenSaverActive(), QFbScreen::setDirty(), QVNCServer::setDirty(), QNetworkConfigurationManagerPrivate::startPolling(), Maemo::IcdPrivate::state(), QNetworkSessionPrivateImpl::stateChange(), Maemo::IcdPrivate::statistics(), QNetworkSessionPrivateImpl::stop(), and QNetworkSessionPrivateImpl::updateState().
 { return id >= 0; }
isSingleShot()
bool QTimer::isSingleShot () const inline
Definition at line 76 of file qtimer.h.
 { return single; }
killTimer()
void QTimer::killTimer (int) inline private
Definition at line 101 of file qtimer.h.
 {}
setInterval()
void QTimer::setInterval (int msec)
Definition at line 419 of file qtimer.cpp.
Referenced by QFbScreen::QFbScreen(), QSmoothedAnimation::QSmoothedAnimation(), start(), and QNetworkConfigurationManagerPrivate::startPolling().
 {
     inter = msec;
     if (id != INV_TIMER) {                        // create new timer
         QObject::killTimer(id);                        // restart timer
         id = QObject::startTimer(msec);
     }
 }
setSingleShot()
void QTimer::setSingleShot (bool singleShot) inline
Definition at line 108 of file qtimer.h.
Referenced by Maemo::IcdPrivate::addrinfo(), QApplication::alert(), QIcdEngine::ensureDBusConnection(), QHttpPrivate::init(), QVNCServer::init(), QComboBoxPrivateContainer::QComboBoxPrivateContainer(), QFbScreen::QFbScreen(), QPatternist::QIODeviceDelegate::QIODeviceDelegate(), QMoviePrivate::QMoviePrivate(), QSmoothedAnimation::QSmoothedAnimation(), QWSKbPrivate::QWSKbPrivate(), Maemo::IcdPrivate::scan(), start(), QNetworkConfigurationManagerPrivate::startPolling(), Maemo::IcdPrivate::state(), Maemo::IcdPrivate::statistics(), and QApplication::syncX().
 { single = asingleShot; }
singleShot()
static void QTimer::singleShot (int msec, QObject * receiver, const char * member) static
start [1/2]
void QTimer::start (int msec) slot
Starts or restarts the timer with a timeout interval of msec milliseconds.
If the timer is already running, it will be stopped and restarted.
If singleShot is true, the timer will be activated only once.
Definition at line 249 of file qtimer.cpp.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QMoviePrivate::_q_loadNextFrame(), QHttpPrivate::_q_slotConnected(), Maemo::IcdPrivate::addrinfo(), QApplication::alert(), QWSKbPrivate::autoRepeat(), QWSKbPrivate::beginAutoRepeat(), QSmoothedAnimation::delayedStop(), QNetworkSessionPrivateImpl::do_open(), loadDocument(), QVNCServer::newConnection(), QAudioInputPrivate::open(), QAudioOutputPrivate::open(), QProcessPrivate::pipeWriterBytesToWrite(), QPatternist::QIODeviceDelegate::QIODeviceDelegate(), qt_create_commandline(), QIcdEngine::requestUpdate(), QAudioInputPrivate::resume(), QAudioOutputPrivate::resume(), QAlphaWidget::run(), QPollingFileSystemWatcherEngine::run(), QRollEffect::run(), Maemo::IcdPrivate::scan(), QFbScreen::setDirty(), QVNCServer::setDirty(), QtMultimediaInternal::QAudioOutputBuffer::startFillTimer(), QNetworkConfigurationManagerPrivate::startPolling(), Maemo::IcdPrivate::state(), Maemo::IcdPrivate::statistics(), and QApplication::syncX().
 {
     inter = msec;
     start();
 }
start [2/2]
void QTimer::start () slot
Definition at line 231 of file qtimer.cpp.
Referenced by start().
 {
     if (id != INV_TIMER)                        // stop running timer
         stop();
     nulltimer = (!inter && single);
     id = QObject::startTimer(inter);
 }
startTimer()
int QTimer::startTimer (int) inline private
Definition at line 100 of file qtimer.h.
 { return -1;}
stop
void QTimer::stop () slot
Stops the timer.
See also
start()
Definition at line 284 of file qtimer.cpp.
Referenced by QAbstractSocketPrivate::_q_abortConnectionAttempt(), QHttpPrivate::_q_slotReadyRead(), QAbstractSocketPrivate::_q_testConnection(), Maemo::IcdPrivate::addrinfo(), QIcdEngine::cancelAsyncConfigurationUpdate(), QIcdEngine::cleanup(), QAudioInputPrivate::close(), QAudioOutputPrivate::close(), QNetworkSessionPrivateImpl::close(), QWSKbPrivate::endAutoRepeat(), QComboBoxPrivateContainer::eventFilter(), QtMultimediaInternal::QAudioOutputBuffer::fillBuffer(), QSmoothedAnimation::init(), QMoviePrivate::jumpToFrame(), loadDocument(), QNetworkSessionPrivateImpl::open(), QProcessPrivate::pipeWriterBytesToWrite(), QAlphaWidget::render(), QMoviePrivate::reset(), QAbstractSocketPrivate::resetSocketLayer(), Maemo::IcdPrivate::scan(), QRollEffect::scroll(), QWSServer::setScreenSaverIntervals(), start(), Maemo::IcdPrivate::state(), QNetworkSessionPrivateImpl::stateChange(), Maemo::IcdPrivate::statistics(), QNetworkSessionPrivateImpl::stop(), QtMultimediaInternal::QAudioOutputBuffer::stopFillTimer(), QAudioInputPrivate::suspend(), QAudioOutputPrivate::suspend(), timerEvent(), QNetworkSessionPrivateImpl::updateState(), and ~QTimer().
 {
     if (id != INV_TIMER) {
         QObject::killTimer(id);
         id = INV_TIMER;
     }
 }
timeout
void QTimer::timeout () signal
This signal is emitted when the timer times out.
See also
interval, start(), stop()
Referenced by timerEvent().
timerEvent()
void QTimer::timerEvent (QTimerEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 296 of file qtimer.cpp.
 {
     if (e->timerId() == id) {
         if (single)
             stop();
         emit timeout();
     }
 }
timerId()
int QTimer::timerId () const inline
Returns the ID of the timer if the timer is running; otherwise returns -1.
Definition at line 70 of file qtimer.h.
Referenced by start().
 { return id; }
Properties
active
QTimer::active private
This boolean property is true if the timer is running; otherwise false.
Since
4.3
Definition at line 61 of file qtimer.h.
del
int QTimer::del private
Definition at line 103 of file qtimer.h.
id
int QTimer::id private
Definition at line 103 of file qtimer.h.
Referenced by QTimer(), start(), and timerEvent().
inter
int QTimer::inter private
Definition at line 103 of file qtimer.h.
Referenced by start().
interval
QTimer::interval private
the timeout interval in milliseconds
The default value for this property is 0. A QTimer with a timeout interval of 0 will time out as soon as all the events in the window system's event queue have been processed.
Setting the interval of an active timer changes its timerId().
See also
singleShot
Definition at line 60 of file qtimer.h.
nulltimer
uint QTimer::nulltimer private
Definition at line 105 of file qtimer.h.
Referenced by QTimer(), and start().
single
uint QTimer::single private
Definition at line 104 of file qtimer.h.
Referenced by QTimer(), setSingleShot(), start(), and timerEvent().
singleShot
QTimer::singleShot private
This static function calls a slot after a given time interval.
whether the timer is a single-shot timer
Note
This class or function is reentrant.
It is very convenient to use this function because you do not need to bother with a timerEvent or create a local QTimer object.
Example:
#include <QApplication>
#include <QTimer>
int main(int argc, char *argv[])
{
    QApplication app(argc, argv);
    QTimer::singleShot(600000, &app, SLOT(quit()));
    ...
    return app.exec();
}
This sample program automatically terminates after 10 minutes (600,000 milliseconds).
The receiver is the receiving object and the member is the slot. The time interval is msec milliseconds.
See also
start()
A single-shot timer fires only once, non-single-shot timers fire every interval milliseconds.
See also
interval, singleShot()
Definition at line 59 of file qtimer.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QLocalSocketPrivate::_q_notified(), QFtpPrivate::addCommand(), QLocalSocketPrivate::checkPipeState(), QLocalSocketPrivate::checkReadyRead(), QDeclarativeObjectScriptClass::destroy(), QLocalSocketPrivate::destroyPipeHandles(), QWSServerPrivate::disconnectClient(), QLineEdit::event(), QXlibScreen::eventDispatcher(), QWSSoundServerPrivate::feedDevice(), QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QMeeGoGraphicsSystemSwitchHandler::handleMapNotify(), QMenuPrivate::hideMenu(), QComboBox::hidePopup(), QMenuPrivate::hideUpToMenuBar(), QDeferredGraphicsSystemChange::launch(), QColorDialogPrivate::mac_nativeDialogModalHelp(), QFontDialogPrivate::mac_nativeDialogModalHelp(), QFileDialogPrivate::mac_nativeDialogModalHelp(), QNetworkSessionPrivateImpl::open(), QMacWindowFader::performFade(), QDeclarativeXmlListModel::reload(), QMeeGoGraphicsSystemSwitchHandler::removeWidget(), QDeclarativeXmlListModel::requestFinished(), QConnmanEngine::requestUpdate(), QDeclarativeBasePositionerPrivate::schedulePositioning(), QSyntaxHighlighter::setDocument(), QHttpThreadDelegate::startRequestSynchronously(), QCoreFuriCuri::timerEvent(), QSingleShotTimer::timerEvent(), QBBEngine::updateConfiguration(), and QNetworkSession::waitForOpened().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qtimer.h
/src/corelib/kernel/qtimer.cpp