Qt 4.8: QScriptValue Class Reference
QScriptValue Class Reference
The QScriptValue class acts as a container for the Qt Script data types.
#include <qscriptvalue.h>
Public Types
enum PropertyFlag {
ReadOnly = 0x00000001, Undeletable = 0x00000002, SkipInEnumeration = 0x00000004, PropertyGetter = 0x00000008,
PropertySetter = 0x00000010, QObjectMember = 0x00000020, KeepExistingFlags = 0x00000800, UserRange = 0xff000000
}
This enum describes the attributes of a property.
enum ResolveFlag { ResolveLocal = 0x00, ResolvePrototype = 0x01, ResolveScope = 0x02, ResolveFull = ResolvePrototype | ResolveScope }
This enum specifies how to look up a property of an object.
enum SpecialValue { NullValue, UndefinedValue }
This enum is used to specify a single-valued type.
Public Functions
QScriptValue call (const QScriptValue &thisObject=QScriptValue(), const QScriptValueList &args=QScriptValueList())
Calls this QScriptValue as a function, using thisObject as the `this' object in the function call, and passing args as arguments to the function.
QScriptValue call (const QScriptValue &thisObject, const QScriptValue &arguments)
Calls this QScriptValue as a function, using thisObject as the `this' object in the function call, and passing arguments as arguments to the function.
QScriptValue construct (const QScriptValueList &args=QScriptValueList())
Creates a new Object and calls this QScriptValue as a constructor, using the created object as the `this' object and passing args as arguments.
QScriptValue construct (const QScriptValue &arguments)
Creates a new Object and calls this QScriptValue as a constructor, using the created object as the `this' object and passing arguments as arguments.
QScriptValue data () const
Returns the internal data of this QScriptValue object.
QScriptEngine * engine () const
Returns the QScriptEngine that created this QScriptValue, or 0 if this QScriptValue is invalid or the value is not associated with a particular engine.
bool equals (const QScriptValue &other) const
Returns true if this QScriptValue is equal to other, otherwise returns false.
bool instanceOf (const QScriptValue &other) const
Returns true if this QScriptValue is an instance of other; otherwise returns false.
bool isArray () const
Returns true if this QScriptValue is an object of the Array class; otherwise returns false.
bool isBool () const
Returns true if this QScriptValue is of the primitive type Boolean; otherwise returns false.
bool isBoolean () const
Use isBool() instead.
bool isDate () const
Returns true if this QScriptValue is an object of the Date class; otherwise returns false.
bool isError () const
Returns true if this QScriptValue is an object of the Error class; otherwise returns false.
bool isFunction () const
Returns true if this QScriptValue is a function; otherwise returns false.
bool isNull () const
Returns true if this QScriptValue is of the primitive type Null; otherwise returns false.
bool isNumber () const
Returns true if this QScriptValue is of the primitive type Number; otherwise returns false.
bool isObject () const
Returns true if this QScriptValue is of the Object type; otherwise returns false.
bool isQMetaObject () const
Returns true if this QScriptValue is a QMetaObject; otherwise returns false.
bool isQObject () const
Returns true if this QScriptValue is a QObject; otherwise returns false.
bool isRegExp () const
Returns true if this QScriptValue is an object of the RegExp class; otherwise returns false.
bool isString () const
Returns true if this QScriptValue is of the primitive type String; otherwise returns false.
bool isUndefined () const
Returns true if this QScriptValue is of the primitive type Undefined; otherwise returns false.
bool isValid () const
Returns true if this QScriptValue is valid; otherwise returns false.
bool isVariant () const
Returns true if this QScriptValue is a variant value; otherwise returns false.
bool lessThan (const QScriptValue &other) const
Returns true if this QScriptValue is less than other, otherwise returns false.
qint64 objectId () const
Returns the ID of this object, or -1 if this QScriptValue is not an object.
QScriptValue & operator= (const QScriptValue &other)
Assigns the other value to this QScriptValue.
QScriptValue property (const QString &name, const ResolveFlags &mode=ResolvePrototype) const
Returns the value of this QScriptValue's property with the given name, using the given mode to resolve the property.
QScriptValue property (quint32 arrayIndex, const ResolveFlags &mode=ResolvePrototype) const
Returns the property at the given arrayIndex, using the given mode to resolve the property.
QScriptValue property (const QScriptString &name, const ResolveFlags &mode=ResolvePrototype) const
Returns the value of this QScriptValue's property with the given name, using the given mode to resolve the property.
QScriptValue::PropertyFlags propertyFlags (const QString &name, const ResolveFlags &mode=ResolvePrototype) const
Returns the flags of the property with the given name, using the given mode to resolve the property.
QScriptValue::PropertyFlags propertyFlags (const QScriptString &name, const ResolveFlags &mode=ResolvePrototype) const
Returns the flags of the property with the given name, using the given mode to resolve the property.
QScriptValue prototype () const
If this QScriptValue is an object, returns the internal prototype (__proto__ property) of this object; otherwise returns an invalid QScriptValue.
QScriptValue ()
Constructs an invalid QScriptValue.
QScriptValue (const QScriptValue &other)
Constructs a new QScriptValue that is a copy of other.
QScriptValue (QScriptEngine *engine, SpecialValue val)
Constructs a new QScriptValue with the special value and registers it with the script engine.
QScriptValue (QScriptEngine *engine, bool val)
QScriptValue (QScriptEngine *engine, int val)
QScriptValue (QScriptEngine *engine, uint val)
QScriptValue (QScriptEngine *engine, qsreal val)
QScriptValue (QScriptEngine *engine, const QString &val)
QT_ASCII_CAST_WARN_CONSTRUCTOR QScriptValue (QScriptEngine *engine, const char *val)
QScriptValue (SpecialValue value)
Constructs a new QScriptValue with a special value.
QScriptValue (bool value)
Constructs a new QScriptValue with a boolean value.
QScriptValue (int value)
Constructs a new QScriptValue with a number value.
QScriptValue (uint value)
Constructs a new QScriptValue with a number value.
QScriptValue (qsreal value)
Constructs a new QScriptValue with a number value.
QScriptValue (const QString &value)
Constructs a new QScriptValue with a string value.
QScriptValue (const QLatin1String &value)
Constructs a new QScriptValue with a string value.
QT_ASCII_CAST_WARN_CONSTRUCTOR QScriptValue (const char *value)
Constructs a new QScriptValue with a string value.
QScriptValue scope () const
QScriptClass * scriptClass () const
Returns the custom script class that this script object is an instance of, or 0 if the object is not of a custom class.
void setData (const QScriptValue &data)
Sets the internal data of this QScriptValue object.
void setProperty (const QString &name, const QScriptValue &value, const PropertyFlags &flags=KeepExistingFlags)
Sets the value of this QScriptValue's property with the given name to the given value.
void setProperty (quint32 arrayIndex, const QScriptValue &value, const PropertyFlags &flags=KeepExistingFlags)
Sets the property at the given arrayIndex to the given value.
void setProperty (const QScriptString &name, const QScriptValue &value, const PropertyFlags &flags=KeepExistingFlags)
Sets the value of this QScriptValue's property with the given name to the given value.
void setPrototype (const QScriptValue &prototype)
If this QScriptValue is an object, sets the internal prototype (__proto__ property) of this object to be prototype; otherwise does nothing.
void setScope (const QScriptValue &scope)
void setScriptClass (QScriptClass *scriptClass)
Sets the custom script class of this script object to scriptClass.
bool strictlyEquals (const QScriptValue &other) const
Returns true if this QScriptValue is equal to other using strict comparison (no conversion), otherwise returns false.
bool toBool () const
Returns the boolean value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.
bool toBoolean () const
Use toBool() instead.
QDateTime toDateTime () const
Returns a QDateTime representation of this value, in local time.
qint32 toInt32 () const
Returns the signed 32-bit integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.5, "ToInt32".
qsreal toInteger () const
Returns the integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.4, "ToInteger".
qsreal toNumber () const
Returns the number value of this QScriptValue, as defined in ECMA-262 section 9.3, "ToNumber".
QScriptValue toObject () const
This function is obsolete; use QScriptEngine::toObject() instead.
const QMetaObject * toQMetaObject () const
If this QScriptValue is a QMetaObject, returns the QMetaObject pointer that the QScriptValue represents; otherwise, returns 0.
QObject * toQObject () const
If this QScriptValue is a QObject, returns the QObject pointer that the QScriptValue represents; otherwise, returns 0.
QRegExp toRegExp () const
Returns the QRegExp representation of this value.
QString toString () const
Returns the string value of this QScriptValue, as defined in ECMA-262 section 9.8, "ToString".
quint16 toUInt16 () const
Returns the unsigned 16-bit integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.7, "ToUint16".
quint32 toUInt32 () const
Returns the unsigned 32-bit integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.6, "ToUint32".
QVariant toVariant () const
Returns the QVariant value of this QScriptValue, if it can be converted to a QVariant; otherwise returns an invalid QVariant.
~QScriptValue ()
Destroys this QScriptValue.
Private Functions
QScriptValue (void *)
QScriptValue (QScriptEngine *, void *)
QScriptValue (QScriptValuePrivate *)
Properties
QExplicitlySharedDataPointer< QScriptValuePrivate > d_ptr
Friends
class QScriptEnginePrivate
Related Functions
(Note that these are not member functions.)
T qscriptvalue_cast (const QScriptValue &value)
Returns the given value converted to the template type T.
Detailed Description
The QScriptValue class acts as a container for the Qt Script data types.
Since
4.3
QScriptValue supports the types defined in the ECMA-262 standard: The primitive types, which are Undefined, Null, Boolean, Number, and String; and the Object type. Additionally, Qt Script has built-in support for QVariant, QObject and QMetaObject.
For the object-based types (including Date and RegExp), use the newT() functions in QScriptEngine (e.g. QScriptEngine::newObject()) to create a QScriptValue of the desired type. For the primitive types, use one of the QScriptValue constructor overloads.
The methods named isT() (e.g. isBool(), isUndefined()) can be used to test if a value is of a certain type. The methods named toT() (e.g. toBool(), toString()) can be used to convert a QScriptValue to another type. You can also use the generic qscriptvalue_cast() function.
Object values have zero or more properties which are themselves QScriptValues. Use setProperty() to set a property of an object, and call property() to retrieve the value of a property.
QScriptEngine myEngine;
QScriptValue myObject = myEngine.newObject();
QScriptValue myOtherObject = myEngine.newObject();
myObject.setProperty("myChild", myOtherObject);
myObject.setProperty("name", "John Doe");
Each property can have a set of attributes; these are specified as the third (optional) argument to setProperty(). The attributes of a property can be queried by calling the propertyFlags() function. The following code snippet creates a property that cannot be modified by script code:
QScriptValue val(&myEngine, 123);
myObject.setProperty("myReadOnlyProperty", val, QScriptValue::ReadOnly);
If you want to iterate over the properties of a script object, use the QScriptValueIterator class.
Object values have an internal prototype property, which can be accessed with prototype() and setPrototype(). Properties added to a prototype are shared by all objects having that prototype; this is referred to as prototype-based inheritance. In practice, it means that (by default) the property() function will automatically attempt to look up look the property in the prototype() (and in the prototype of the prototype(), and so on), if the object itself does not have the requested property. Note that this prototype-based lookup is not performed by setProperty(); setProperty() will always create the property in the script object itself. For more information, see the QtScript documentation.
Function objects (objects for which isFunction() returns true) can be invoked by calling call(). Constructor functions can be used to construct new objects by calling construct().
Use equals(), strictlyEquals() and lessThan() to compare a QScriptValue to another.
Object values can have custom data associated with them; see the setData() and data() functions. By default, this data is not accessible to scripts; it can be used to store any data you want to associate with the script object. Typically this is used by custom class objects (see QScriptClass) to store a C++ type that contains the "native" object data.
Note that a QScriptValue for which isObject() is true only carries a reference to an actual object; copying the QScriptValue will only copy the object reference, not the object itself. If you want to clone an object (i.e. copy an object's properties to another object), you can do so with the help of a for-in statement in script code, or QScriptValueIterator in C++.
See also
QScriptEngine, QScriptValueIterator
Definition at line 57 of file qscriptvalue.h.
Enumerations
PropertyFlag
enum QScriptValue::PropertyFlag
This enum describes the attributes of a property.
ReadOnly The property is read-only. Attempts by Qt Script code to write to the property will be ignored.
Undeletable Attempts by Qt Script code to delete the property will be ignored.
SkipInEnumeration The property is not to be enumerated by a for-in enumeration.
PropertyGetter The property is defined by a function which will be called to get the property value.
PropertySetter The property is defined by a function which will be called to set the property value.
QObjectMember This flag is used to indicate that an existing property is a QObject member (a property or method).
KeepExistingFlags This value is used to indicate to setProperty() that the property's flags should be left unchanged. If the property doesn't exist, the default flags (0) will be used.
UserRange Flags in this range are not used by Qt Script, and can be used for custom purposes.
Enumerator
ReadOnly
Undeletable
SkipInEnumeration
PropertyGetter
PropertySetter
QObjectMember
KeepExistingFlags
UserRange
Definition at line 69 of file qscriptvalue.h.
                       {
         ReadOnly            = 0x00000001,
         Undeletable         = 0x00000002,
         SkipInEnumeration   = 0x00000004,
         PropertyGetter      = 0x00000008,
         PropertySetter      = 0x00000010,
         QObjectMember       = 0x00000020,
         KeepExistingFlags   = 0x00000800,
         UserRange           = 0xff000000            // Users may use these as they see fit.
     };
ResolveFlag
enum QScriptValue::ResolveFlag
This enum specifies how to look up a property of an object.
ResolveLocal Only check the object's own properties.
ResolvePrototype Check the object's own properties first, then search the prototype chain. This is the default.
ResolveScope Check the object's own properties first, then search the scope chain.
ResolveFull Check the object's own properties first, then search the prototype chain, and finally search the scope chain.
Enumerator
ResolveLocal
ResolvePrototype
ResolveScope
ResolveFull
Definition at line 60 of file qscriptvalue.h.
                      {
         ResolveLocal        = 0x00,
         ResolvePrototype    = 0x01,
         ResolveScope        = 0x02,
         ResolveFull         = ResolvePrototype | ResolveScope
     };
SpecialValue
enum QScriptValue::SpecialValue
This enum is used to specify a single-valued type.
UndefinedValue An undefined value.
NullValue A null value.
Enumerator
NullValue
UndefinedValue
Definition at line 85 of file qscriptvalue.h.
                       {
         NullValue,
         UndefinedValue
     };
Constructors and Destructors
QScriptValue() [1/20]
QScriptValue::QScriptValue ()
Constructs an invalid QScriptValue.
Definition at line 201 of file qscriptvalue.cpp.
Referenced by call(), construct(), data(), property(), prototype(), scope(), and toObject().
     : d_ptr(0)
 {
 }
~QScriptValue()
QScriptValue::~QScriptValue ()
Destroys this QScriptValue.
Definition at line 209 of file qscriptvalue.cpp.
 {
 }
QScriptValue() [2/20]
QScriptValue::QScriptValue (const QScriptValue & other)
Constructs a new QScriptValue that is a copy of other.
Note that if other is an object (i.e., isObject() would return true), then only a reference to the underlying object is copied into the new script value (i.e., the object itself is not copied).
Definition at line 220 of file qscriptvalue.cpp.
     : d_ptr(other.d_ptr)
 {
 }
QScriptValue() [3/20]
QScriptValue::QScriptValue (QScriptEngine * engine, QScriptValue::SpecialValue value)
Constructs a new QScriptValue with the special value and registers it with the script engine.
Definition at line 234 of file qscriptvalue.cpp.
     : d_ptr(new (QScriptEnginePrivate::get(engine))QScriptValuePrivate(QScriptEnginePrivate::get(engine)))
 {
     switch (value) {
     case NullValue:
         d_ptr->initFrom(JSC::jsNull());
         break;
     case UndefinedValue:
         d_ptr->initFrom(JSC::jsUndefined());
         break;
     }
 }
QScriptValue() [4/20]
QScriptValue::QScriptValue (QScriptEngine * engine, bool value)
Constructs a new QScriptValue with the boolean value and registers it with the script engine.
Definition at line 255 of file qscriptvalue.cpp.
     : d_ptr(new (QScriptEnginePrivate::get(engine))QScriptValuePrivate(QScriptEnginePrivate::get(engine)))
 {
     d_ptr->initFrom(JSC::jsBoolean(val));
 }
QScriptValue() [5/20]
QScriptValue::QScriptValue (QScriptEngine * engine, int value)
Constructs a new QScriptValue with the integer value and registers it with the script engine.
Definition at line 268 of file qscriptvalue.cpp.
     : d_ptr(new (QScriptEnginePrivate::get(engine))QScriptValuePrivate(QScriptEnginePrivate::get(engine)))
 {
     if (engine) {
         QScript::APIShim shim(d_ptr->engine);
         JSC::ExecState *exec = d_ptr->engine->currentFrame;
         d_ptr->initFrom(JSC::jsNumber(exec, val));
     } else
         d_ptr->initFrom(val);
 }
QScriptValue() [6/20]
QScriptValue::QScriptValue (QScriptEngine * engine, uint value)
Constructs a new QScriptValue with the unsigned integer value and registers it with the script engine.
Definition at line 286 of file qscriptvalue.cpp.
     : d_ptr(new (QScriptEnginePrivate::get(engine))QScriptValuePrivate(QScriptEnginePrivate::get(engine)))
 {
     if (engine) {
         QScript::APIShim shim(d_ptr->engine);
         JSC::ExecState *exec = d_ptr->engine->currentFrame;
         d_ptr->initFrom(JSC::jsNumber(exec, val));
     } else
         d_ptr->initFrom(val);
 }
QScriptValue() [7/20]
QScriptValue::QScriptValue (QScriptEngine * engine, qsreal value)
Constructs a new QScriptValue with the qsreal value and registers it with the script engine.
Definition at line 304 of file qscriptvalue.cpp.
     : d_ptr(new (QScriptEnginePrivate::get(engine))QScriptValuePrivate(QScriptEnginePrivate::get(engine)))
 {
     if (engine) {
         QScript::APIShim shim(d_ptr->engine);
         JSC::ExecState *exec = d_ptr->engine->currentFrame;
         d_ptr->initFrom(JSC::jsNumber(exec, val));
     } else
         d_ptr->initFrom(val);
 }
QScriptValue() [8/20]
QScriptValue::QScriptValue (QScriptEngine * engine, const QString & value)
Constructs a new QScriptValue with the string value and registers it with the script engine.
Definition at line 322 of file qscriptvalue.cpp.
     : d_ptr(new (QScriptEnginePrivate::get(engine))QScriptValuePrivate(QScriptEnginePrivate::get(engine)))
 {
     if (engine) {
         QScript::APIShim shim(d_ptr->engine);
         JSC::ExecState *exec = d_ptr->engine->currentFrame;
         d_ptr->initFrom(JSC::jsString(exec, val));
     } else {
         d_ptr->initFrom(val);
     }
 }
QScriptValue() [9/20]
QScriptValue::QScriptValue (QScriptEngine * engine, const char * value)
Constructs a new QScriptValue with the string value and registers it with the script engine.
Definition at line 343 of file qscriptvalue.cpp.
     : d_ptr(new (QScriptEnginePrivate::get(engine))QScriptValuePrivate(QScriptEnginePrivate::get(engine)))
 {
     if (engine) {
         QScript::APIShim shim(d_ptr->engine);
         JSC::ExecState *exec = d_ptr->engine->currentFrame;
         d_ptr->initFrom(JSC::jsString(exec, val));
     } else {
         d_ptr->initFrom(QString::fromAscii(val));
     }
 }
QScriptValue() [10/20]
QScriptValue::QScriptValue (SpecialValue value)
Constructs a new QScriptValue with a special value.
Since
4.5
Definition at line 364 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     switch (value) {
     case NullValue:
         d_ptr->initFrom(JSC::jsNull());
         break;
     case UndefinedValue:
         d_ptr->initFrom(JSC::jsUndefined());
         break;
     }
 }
QScriptValue() [11/20]
QScriptValue::QScriptValue (bool value)
Constructs a new QScriptValue with a boolean value.
Since
4.5
Definition at line 385 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     d_ptr->initFrom(JSC::jsBoolean(value));
 }
QScriptValue() [12/20]
QScriptValue::QScriptValue (int value)
Constructs a new QScriptValue with a number value.
Since
4.5
Definition at line 399 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     d_ptr->initFrom(value);
 }
QScriptValue() [13/20]
QScriptValue::QScriptValue (uint value)
Constructs a new QScriptValue with a number value.
Since
4.5
Definition at line 413 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     d_ptr->initFrom(value);
 }
QScriptValue() [14/20]
QScriptValue::QScriptValue (qsreal value)
Constructs a new QScriptValue with a number value.
Since
4.5
Definition at line 427 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     d_ptr->initFrom(value);
 }
QScriptValue() [15/20]
QScriptValue::QScriptValue (const QString & value)
Constructs a new QScriptValue with a string value.
Since
4.5
Definition at line 441 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     d_ptr->initFrom(value);
 }
QScriptValue() [16/20]
QScriptValue::QScriptValue (const QLatin1String & value)
Constructs a new QScriptValue with a string value.
Since
4.5
Definition at line 455 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     d_ptr->initFrom(value);
 }
QScriptValue() [17/20]
QScriptValue::QScriptValue (const char * value)
Constructs a new QScriptValue with a string value.
Since
4.5
Definition at line 471 of file qscriptvalue.cpp.
     : d_ptr(new (/*engine=*/0)QScriptValuePrivate(/*engine=*/0))
 {
     d_ptr->initFrom(QString::fromAscii(value));
 }
QScriptValue() [18/20]
QScriptValue::QScriptValue (void *) private
QScriptValue() [19/20]
QScriptValue::QScriptValue (QScriptEngine * , void *) private
QScriptValue() [20/20]
QScriptValue::QScriptValue (QScriptValuePrivate * d) private
Warning
This function is not part of the public interface.
Definition at line 193 of file qscriptvalue.cpp.
     : d_ptr(d)
 {
 }
Functions
call() [1/2]
QScriptValue QScriptValue::call (const QScriptValue & thisObject = QScriptValue(), const QScriptValueList & args = QScriptValueList())
Calls this QScriptValue as a function, using thisObject as the `this' object in the function call, and passing args as arguments to the function.
Returns the value returned from the function.
If this QScriptValue is not a function, call() does nothing and returns an invalid QScriptValue.
Note that if thisObject is not an object, the global object (see QScriptEngine::globalObject()) will be used as the `this' object.
Calling call() can cause an exception to occur in the script engine; in that case, call() returns the value that was thrown (typically an Error object). You can call QScriptEngine::hasUncaughtException() to determine if an exception occurred.
QScriptEngine engine;
engine.evaluate("function fullName() { return this.firstName + ' ' + this.lastName; }");
engine.evaluate("somePerson = { firstName: 'John', lastName: 'Doe' }");
QScriptValue global = engine.globalObject();
QScriptValue fullName = global.property("fullName");
QScriptValue who = global.property("somePerson");
qDebug() << fullName.call(who).toString(); // "John Doe"
engine.evaluate("function cube(x) { return x * x * x; }");
QScriptValue cube = global.property("cube");
QScriptValueList args;
args << 3;
qDebug() << cube.call(QScriptValue(), args).toNumber(); // 27
See also
construct()
Definition at line 1621 of file qscriptvalue.cpp.
Referenced by QDeclarativeInclude::callback(), QDeclarativeXMLHttpRequest::dispatchCallback(), QDeclarativeQtScriptExpression::eval(), QScriptEngine::importExtension(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeWorkerScriptEnginePrivate::processMessage(), qmlsqldatabase_change_version(), and qmlsqldatabase_open_sync().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     JSC::JSValue callee = d->jscValue;
     JSC::CallData callData;
     JSC::CallType callType = callee.getCallData(callData);
     if (callType == JSC::CallTypeNone)
         return QScriptValue();
     if (QScriptValuePrivate::getEngine(thisObject)
         && (QScriptValuePrivate::getEngine(thisObject) != d->engine)) {
         qWarning("QScriptValue::call() failed: "
                  "cannot call function with thisObject created in "
                  "a different engine");
         return QScriptValue();
     }
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::JSValue jscThisObject = d->engine->scriptValueToJSCValue(thisObject);
     if (!jscThisObject || !jscThisObject.isObject())
         jscThisObject = d->engine->globalObject();
     QVarLengthArray<JSC::JSValue, 8> argsVector(args.size());
     for (int i = 0; i < args.size(); ++i) {
         const QScriptValue &arg = args.at(i);
         if (!arg.isValid()) {
             argsVector[i] = JSC::jsUndefined();
         } else if (QScriptValuePrivate::getEngine(arg)
                    && (QScriptValuePrivate::getEngine(arg) != d->engine)) {
             qWarning("QScriptValue::call() failed: "
                      "cannot call function with argument created in "
                      "a different engine");
             return QScriptValue();
         } else {
             argsVector[i] = d->engine->scriptValueToJSCValue(arg);
         }
     }
     JSC::ArgList jscArgs(argsVector.data(), argsVector.size());
     JSC::JSValue savedException;
     QScriptEnginePrivate::saveException(exec, &savedException);
     JSC::JSValue result = JSC::call(exec, callee, callType, callData, jscThisObject, jscArgs);
     if (exec->hadException()) {
         result = exec->exception();
     } else {
         QScriptEnginePrivate::restoreException(exec, savedException);
     }
     return d->engine->scriptValueFromJSCValue(result);
 }
call() [2/2]
QScriptValue QScriptValue::call (const QScriptValue & thisObject, const QScriptValue & arguments)
Calls this QScriptValue as a function, using thisObject as the `this' object in the function call, and passing arguments as arguments to the function.
Returns the value returned from the function.
If this QScriptValue is not a function, call() does nothing and returns an invalid QScriptValue.
arguments can be an arguments object, an array, null or undefined; any other type will cause a TypeError to be thrown.
Note that if thisObject is not an object, the global object (see QScriptEngine::globalObject()) will be used as the `this' object.
One common usage of this function is to forward native function calls to another function:
QScriptValue myNativeFunction(QScriptContext *ctx, QScriptEngine *)
{
    QScriptValue otherFunction = ...;
    return otherFunction.call(ctx->thisObject(), ctx->argumentsObject());
}
See also
construct(), QScriptContext::argumentsObject()
Definition at line 1699 of file qscriptvalue.cpp.
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     JSC::JSValue callee = d->jscValue;
     JSC::CallData callData;
     JSC::CallType callType = callee.getCallData(callData);
     if (callType == JSC::CallTypeNone)
         return QScriptValue();
     if (QScriptValuePrivate::getEngine(thisObject)
         && (QScriptValuePrivate::getEngine(thisObject) != d->engine)) {
         qWarning("QScriptValue::call() failed: "
                  "cannot call function with thisObject created in "
                  "a different engine");
         return QScriptValue();
     }
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::JSValue jscThisObject = d->engine->scriptValueToJSCValue(thisObject);
     if (!jscThisObject || !jscThisObject.isObject())
         jscThisObject = d->engine->globalObject();
     JSC::JSValue array = d->engine->scriptValueToJSCValue(arguments);
     // copied from runtime/FunctionPrototype.cpp, functionProtoFuncApply()
     JSC::MarkedArgumentBuffer applyArgs;
     if (!array.isUndefinedOrNull()) {
         if (!array.isObject()) {
             return d->engine->scriptValueFromJSCValue(JSC::throwError(exec, JSC::TypeError, "Arguments must be an array"));
         }
         if (JSC::asObject(array)->classInfo() == &JSC::Arguments::info)
             JSC::asArguments(array)->fillArgList(exec, applyArgs);
         else if (JSC::isJSArray(&exec->globalData(), array))
             JSC::asArray(array)->fillArgList(exec, applyArgs);
         else if (JSC::asObject(array)->inherits(&JSC::JSArray::info)) {
             unsigned length = JSC::asArray(array)->get(exec, exec->propertyNames().length).toUInt32(exec);
             for (unsigned i = 0; i < length; ++i)
                 applyArgs.append(JSC::asArray(array)->get(exec, i));
         } else {
             return d->engine->scriptValueFromJSCValue(JSC::throwError(exec, JSC::TypeError, "Arguments must be an array"));
         }
     }
     JSC::JSValue savedException;
     QScriptEnginePrivate::saveException(exec, &savedException);
     JSC::JSValue result = JSC::call(exec, callee, callType, callData, jscThisObject, applyArgs);
     if (exec->hadException()) {
         result = exec->exception();
     } else {
         QScriptEnginePrivate::restoreException(exec, savedException);
     }
     return d->engine->scriptValueFromJSCValue(result);
 }
construct() [1/2]
QScriptValue QScriptValue::construct (const QScriptValueList & args = QScriptValueList())
Creates a new Object and calls this QScriptValue as a constructor, using the created object as the `this' object and passing args as arguments.
If the return value from the constructor call is an object, then that object is returned; otherwise the default constructed object is returned.
If this QScriptValue is not a function, construct() does nothing and returns an invalid QScriptValue.
Calling construct() can cause an exception to occur in the script engine; in that case, construct() returns the value that was thrown (typically an Error object). You can call QScriptEngine::hasUncaughtException() to determine if an exception occurred.
See also
call(), QScriptEngine::newObject()
Definition at line 1775 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     JSC::JSValue callee = d->jscValue;
     JSC::ConstructData constructData;
     JSC::ConstructType constructType = callee.getConstructData(constructData);
     if (constructType == JSC::ConstructTypeNone)
         return QScriptValue();
     JSC::ExecState *exec = d->engine->currentFrame;
     QVarLengthArray<JSC::JSValue, 8> argsVector(args.size());
     for (int i = 0; i < args.size(); ++i) {
         QScriptValue arg = args.at(i);
         if (QScriptValuePrivate::getEngine(arg) != d->engine && QScriptValuePrivate::getEngine(arg)) {
             qWarning("QScriptValue::construct() failed: "
                      "cannot construct function with argument created in "
                      "a different engine");
             return QScriptValue();
         }
         if (!arg.isValid())
             argsVector[i] = JSC::jsUndefined();
         else
             argsVector[i] = d->engine->scriptValueToJSCValue(args.at(i));
     }
     JSC::ArgList jscArgs(argsVector.data(), argsVector.size());
     JSC::JSValue savedException;
     QScriptEnginePrivate::saveException(exec, &savedException);
     JSC::JSValue result;
     JSC::JSObject *newObject = JSC::construct(exec, callee, constructType, constructData, jscArgs);
     if (exec->hadException()) {
         result = exec->exception();
     } else {
         result = newObject;
         QScriptEnginePrivate::restoreException(exec, savedException);
     }
     return d->engine->scriptValueFromJSCValue(result);
 }
construct() [2/2]
QScriptValue QScriptValue::construct (const QScriptValue & arguments)
Creates a new Object and calls this QScriptValue as a constructor, using the created object as the `this' object and passing arguments as arguments.
If the return value from the constructor call is an object, then that object is returned; otherwise the default constructed object is returned.
If this QScriptValue is not a function, construct() does nothing and returns an invalid QScriptValue.
arguments can be an arguments object, an array, null or undefined. Any other type will cause a TypeError to be thrown.
See also
call(), QScriptEngine::newObject(), QScriptContext::argumentsObject()
Definition at line 1834 of file qscriptvalue.cpp.
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     JSC::JSValue callee = d->jscValue;
     JSC::ConstructData constructData;
     JSC::ConstructType constructType = callee.getConstructData(constructData);
     if (constructType == JSC::ConstructTypeNone)
         return QScriptValue();
     JSC::ExecState *exec = d->engine->currentFrame;
     if (QScriptValuePrivate::getEngine(arguments) != d->engine && QScriptValuePrivate::getEngine(arguments)) {
         qWarning("QScriptValue::construct() failed: "
                  "cannot construct function with argument created in "
                  "a different engine");
         return QScriptValue();
     }
     JSC::JSValue array = d->engine->scriptValueToJSCValue(arguments);
     // copied from runtime/FunctionPrototype.cpp, functionProtoFuncApply()
     JSC::MarkedArgumentBuffer applyArgs;
     if (!array.isUndefinedOrNull()) {
         if (!array.isObject()) {
             return d->engine->scriptValueFromJSCValue(JSC::throwError(exec, JSC::TypeError, "Arguments must be an array"));
         }
         if (JSC::asObject(array)->classInfo() == &JSC::Arguments::info)
             JSC::asArguments(array)->fillArgList(exec, applyArgs);
         else if (JSC::isJSArray(&exec->globalData(), array))
             JSC::asArray(array)->fillArgList(exec, applyArgs);
         else if (JSC::asObject(array)->inherits(&JSC::JSArray::info)) {
             unsigned length = JSC::asArray(array)->get(exec, exec->propertyNames().length).toUInt32(exec);
             for (unsigned i = 0; i < length; ++i)
                 applyArgs.append(JSC::asArray(array)->get(exec, i));
         } else {
             return d->engine->scriptValueFromJSCValue(JSC::throwError(exec, JSC::TypeError, "Arguments must be an array"));
         }
     }
     JSC::JSValue savedException;
     QScriptEnginePrivate::saveException(exec, &savedException);
     JSC::JSValue result;
     JSC::JSObject *newObject = JSC::construct(exec, callee, constructType, constructData, applyArgs);
     if (exec->hadException()) {
         result = exec->exception();
     } else {
         result = newObject;
         QScriptEnginePrivate::restoreException(exec, savedException);
     }
     return d->engine->scriptValueFromJSCValue(result);
 }
data()
QScriptValue QScriptValue::data () const
Returns the internal data of this QScriptValue object.
Since
4.4
QtScript uses this property to store the primitive value of Date, String, Number and Boolean objects. For other types of object, custom data may be stored using setData().
Definition at line 2094 of file qscriptvalue.cpp.
Referenced by NamedNodeMap::length(), NodeList::length(), QDeclarativeWorkerScriptEnginePrivate::onMessage(), QScript::FunctionWrapper::proxyCall(), QScript::FunctionWithArgWrapper::proxyCall(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), qmlsqldatabase_item(), qmlxmlhttprequest_abort(), qmlxmlhttprequest_getAllResponseHeaders(), qmlxmlhttprequest_getResponseHeader(), qmlxmlhttprequest_onreadystatechange(), qmlxmlhttprequest_open(), qmlxmlhttprequest_readyState(), qmlxmlhttprequest_responseText(), qmlxmlhttprequest_responseXML(), qmlxmlhttprequest_send(), qmlxmlhttprequest_setRequestHeader(), qmlxmlhttprequest_status(), qmlxmlhttprequest_statusText(), QDeclarativeWorkerScriptEnginePrivate::sendMessage(), QScriptDebuggerBackendPrivate::trace(), and QDeclarativeInclude::worker_include().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     if (d->jscValue.inherits(&QScriptObject::info)) {
         QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(d->jscValue));
         return d->engine->scriptValueFromJSCValue(scriptObject->data());
     } else {
         // ### make hidden property
         return property(QLatin1String("__qt_data__"), QScriptValue::ResolveLocal);
     }
 }
engine()
QScriptEngine * QScriptValue::engine () const
Returns the QScriptEngine that created this QScriptValue, or 0 if this QScriptValue is invalid or the value is not associated with a particular engine.
Definition at line 1892 of file qscriptvalue.cpp.
Referenced by QScriptValueIteratorPrivate::engine(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), QDeclarativeObjectScriptClass::newQObject(), QDeclarativeXMLHttpRequest::printError(), QScriptEngine::qScriptConnect(), QScriptEngine::qScriptDisconnect(), QScriptContext::setActivationObject(), QScriptContext::setThisObject(), and toObject().
 {
     Q_D(const QScriptValue);
     if (!d)
         return 0;
     return QScriptEnginePrivate::get(d->engine);
 }
equals()
bool QScriptValue::equals (const QScriptValue & other) const
Returns true if this QScriptValue is equal to other, otherwise returns false.
The comparison follows the behavior described in ECMA-262 section 11.9.3, "The Abstract Equality Comparison Algorithm".
This function can return true even if the type of this QScriptValue is different from the type of the other value; i.e. the comparison is not strict. For example, comparing the number 9 to the string "9" returns true; comparing an undefined value to a null value returns true; comparing a Number object whose primitive value is 6 to a String object whose primitive value is "6" returns true; and comparing the number 1 to the boolean value true returns true. If you want to perform a comparison without such implicit value conversion, use strictlyEquals().
Note that if this QScriptValue or the other value are objects, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
strictlyEquals(), lessThan()
Definition at line 883 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !other.d_ptr)
         return (d_ptr == other.d_ptr);
     if (QScriptValuePrivate::getEngine(other) && d->engine
         && (QScriptValuePrivate::getEngine(other) != d->engine)) {
         qWarning("QScriptValue::equals: "
                  "cannot compare to a value created in "
                  "a different engine");
         return false;
     }
     if (d->isJSC() && other.d_ptr->isJSC()) {
         QScriptEnginePrivate *eng_p = d->engine;
         if (!eng_p)
             eng_p = other.d_ptr->engine;
         if (eng_p) {
             QScript::APIShim shim(eng_p);
             JSC::ExecState *exec = eng_p->currentFrame;
             JSC::JSValue savedException;
             QScriptEnginePrivate::saveException(exec, &savedException);
             bool result = JSC::JSValue::equal(exec, d->jscValue, other.d_ptr->jscValue);
             QScriptEnginePrivate::restoreException(exec, savedException);
             return result;
         }
     }
     return QScript::Equals(*this, other);
 }
instanceOf()
bool QScriptValue::instanceOf (const QScriptValue & other) const
Returns true if this QScriptValue is an instance of other; otherwise returns false.
This QScriptValue is considered to be an instance of other if other is a function and the value of the prototype property of other is in the prototype chain of this QScriptValue.
Definition at line 662 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject() || !other.isObject())
         return false;
     if (QScriptValuePrivate::getEngine(other) != d->engine) {
         qWarning("QScriptValue::instanceof: "
                  "cannot perform operation on a value created in "
                  "a different engine");
         return false;
     }
     JSC::JSValue jscProto = d->engine->scriptValueToJSCValue(other.property(QLatin1String("prototype")));
     if (!jscProto)
         jscProto = JSC::jsUndefined();
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::JSValue jscOther = d->engine->scriptValueToJSCValue(other);
     return JSC::asObject(jscOther)->hasInstance(exec, d->jscValue, jscProto);
 }
isArray()
bool QScriptValue::isArray () const
Returns true if this QScriptValue is an object of the Array class; otherwise returns false.
See also
QScriptEngine::newArray()
Definition at line 511 of file qscriptvalue.cpp.
Referenced by QDeclarativeListModel::append(), QDeclarativeComponent::createObject(), QDeclarativeComponentPrivate::createObject(), fromScriptValue(), QDeclarativeListModel::insert(), QDeclarativeObjectMethodScriptClass::matchScore(), QDeclarativeObjectMethodScriptClass::property(), qmlsqldatabase_executeSql(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeEnginePrivate::scriptValueToVariant(), QDeclarativeListModel::set(), ModelNode::setListValue(), and ModelNode::setObjectValue().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScriptEnginePrivate::isArray(d->jscValue);
 }
isBool()
bool QScriptValue::isBool () const
Returns true if this QScriptValue is of the primitive type Boolean; otherwise returns false.
Since
4.5
See also
toBool()
Definition at line 1925 of file qscriptvalue.cpp.
Referenced by QScript::Equals(), fromScriptValue(), QScript::IsNumerical(), and QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant().
 {
     Q_D(const QScriptValue);
     return d && d->isJSC() && d->jscValue.isBoolean();
 }
isBoolean()
bool QScriptValue::isBoolean () const
Use isBool() instead.
Definition at line 1908 of file qscriptvalue.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::matchScore(), QScriptDebuggerValue::QScriptDebuggerValue(), and QScript::type().
 {
     Q_D(const QScriptValue);
     return d && d->isJSC() && d->jscValue.isBoolean();
 }
isDate()
bool QScriptValue::isDate () const
Returns true if this QScriptValue is an object of the Date class; otherwise returns false.
See also
QScriptEngine::newDate()
Definition at line 525 of file qscriptvalue.cpp.
Referenced by FlatListModel::addValue(), QDeclarativeEnginePrivate::formatTime(), fromScriptValue(), QDeclarativeObjectMethodScriptClass::matchScore(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), and FlatListScriptClass::setProperty().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScriptEnginePrivate::isDate(d->jscValue);
 }
isError()
bool QScriptValue::isError () const
Returns true if this QScriptValue is an object of the Error class; otherwise returns false.
See also
QScriptContext::throwError()
Definition at line 497 of file qscriptvalue.cpp.
Referenced by QDeclarativeXMLHttpRequest::abort(), QDeclarativeXMLHttpRequest::downloadProgress(), QDeclarativeXMLHttpRequest::error(), QScriptEnginePrivate::evaluateHelper(), QDeclarativeExpressionPrivate::exceptionToError(), QDeclarativeXMLHttpRequest::finished(), fromScriptValue(), QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), QScriptDebuggerAgent::positionChange(), QScriptDebuggerScriptedConsoleCommandJob::start(), and QScriptEngine::uncaughtExceptionBacktrace().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScriptEnginePrivate::isError(d->jscValue);
 }
isFunction()
bool QScriptValue::isFunction () const
Returns true if this QScriptValue is a function; otherwise returns false.
See also
call()
Definition at line 1981 of file qscriptvalue.cpp.
Referenced by expandObject(), fromScriptValue(), QScriptEngine::importExtension(), QDeclarativeInclude::include(), QDeclarativeWorkerScriptEnginePrivate::processMessage(), qmlsqldatabase_change_version(), qmlsqldatabase_open_sync(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeBinding::update(), and QDeclarativeInclude::worker_include().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScript::isFunction(d->jscValue);
 }
isNull()
bool QScriptValue::isNull () const
Returns true if this QScriptValue is of the primitive type Null; otherwise returns false.
See also
QScriptEngine::nullValue()
Definition at line 1995 of file qscriptvalue.cpp.
Referenced by QScript::Equals(), fromScriptValue(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), QDeclarativeObjectMethodScriptClass::matchScore(), QDeclarativeObjectMethodScriptClass::property(), QScriptDebuggerValue::QScriptDebuggerValue(), QDeclarativeObjectScriptClass::setProperty(), QScript::type(), and QDeclarativeBinding::update().
 {
     Q_D(const QScriptValue);
     return d && d->isJSC() && d->jscValue.isNull();
 }
isNumber()
bool QScriptValue::isNumber () const
Returns true if this QScriptValue is of the primitive type Number; otherwise returns false.
See also
toNumber()
Definition at line 1937 of file qscriptvalue.cpp.
Referenced by _q_equal(), QScriptDebuggerBackendPrivate::exception(), QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), fromScriptValue(), QScript::IsNumerical(), QDeclarativeObjectMethodScriptClass::matchScore(), QScriptDebuggerValue::QScriptDebuggerValue(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeObjectScriptClass::setProperty(), and QScript::type().
 {
     Q_D(const QScriptValue);
     if (!d)
         return false;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore:
         return d->jscValue.isNumber();
     case QScriptValuePrivate::Number:
         return true;
     case QScriptValuePrivate::String:
         return false;
     }
     return false;
 }
isObject()
bool QScriptValue::isObject () const
Returns true if this QScriptValue is of the Object type; otherwise returns false.
Note that function values, variant values, and QObject values are objects, so this function returns true for such values.
See also
toObject(), QScriptEngine::newObject()
Definition at line 2022 of file qscriptvalue.cpp.
Referenced by FlatListModel::addValue(), QDeclarativeListModel::append(), QScript::ClassObjectDelegate::construct(), QDeclarativeComponent::createObject(), QDeclarativeComponentPrivate::createObject(), QScript::Equals(), QScriptDebuggerCommandExecutor::execute(), fromScriptValue(), QJSDebuggerAgentPrivate::getLocals(), QDeclarativeListModel::insert(), instanceOf(), QScript::LessThan(), QScriptEngine::newQObject(), QScript::FunctionWrapper::proxyConstruct(), QScript::FunctionWithArgWrapper::proxyConstruct(), qmlsqldatabase_executeSql(), QScriptEngine::qScriptConnect(), QScriptDebuggerValue::QScriptDebuggerValue(), QScriptEngine::qScriptDisconnect(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeListModel::set(), QScriptContext::setActivationObject(), ModelNode::setListValue(), FlatListScriptClass::setProperty(), QScriptContext::setThisObject(), QScript::ToPrimitive(), and QScript::type().
 {
     Q_D(const QScriptValue);
     return d && d->isObject();
 }
isQMetaObject()
bool QScriptValue::isQMetaObject () const
Returns true if this QScriptValue is a QMetaObject; otherwise returns false.
See also
toQMetaObject(), QScriptEngine::newQMetaObject()
Definition at line 2065 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScriptEnginePrivate::isQMetaObject(d->jscValue);
 }
isQObject()
bool QScriptValue::isQObject () const
Returns true if this QScriptValue is a QObject; otherwise returns false.
Note: This function returns true even if the QObject that this QScriptValue wraps has been deleted.
See also
toQObject(), QScriptEngine::newQObject()
Definition at line 2051 of file qscriptvalue.cpp.
Referenced by QScript::Equals(), fromScriptValue(), QDeclarativeObjectMethodScriptClass::matchScore(), QScriptEngine::newQObject(), QDeclarativeObjectMethodScriptClass::property(), and QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScriptEnginePrivate::isQObject(d->jscValue);
 }
isRegExp()
bool QScriptValue::isRegExp () const
Returns true if this QScriptValue is an object of the RegExp class; otherwise returns false.
See also
QScriptEngine::newRegExp()
Definition at line 539 of file qscriptvalue.cpp.
Referenced by FlatListModel::addValue(), fromScriptValue(), QDeclarativeObjectMethodScriptClass::matchScore(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeValueTypeScriptClass::setProperty(), FlatListScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), and QDeclarativeBinding::update().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScriptEnginePrivate::isRegExp(d->jscValue);
 }
isString()
bool QScriptValue::isString () const
Returns true if this QScriptValue is of the primitive type String; otherwise returns false.
See also
toString()
Definition at line 1959 of file qscriptvalue.cpp.
Referenced by QScript::Equals(), QScriptDebuggerBackendPrivate::exception(), QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), fromScriptValue(), QScript::LessThan(), QDeclarativeObjectMethodScriptClass::matchScore(), QScriptDebuggerScriptedConsoleCommand::parse(), QScriptDebuggerValue::QScriptDebuggerValue(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeObjectScriptClass::setProperty(), QScriptContext::toString(), and QScript::type().
 {
     Q_D(const QScriptValue);
     if (!d)
         return false;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore:
         return d->jscValue.isString();
     case QScriptValuePrivate::Number:
         return false;
     case QScriptValuePrivate::String:
         return true;
     }
     return false;
 }
isUndefined()
bool QScriptValue::isUndefined () const
Returns true if this QScriptValue is of the primitive type Undefined; otherwise returns false.
See also
QScriptEngine::undefinedValue()
Definition at line 2007 of file qscriptvalue.cpp.
Referenced by QScriptDebuggerBackend::doPendingEvaluate(), QScript::Equals(), QDeclarativeQtScriptExpression::eval(), fromScriptValue(), QDeclarativeObjectMethodScriptClass::property(), QScriptDebuggerValue::QScriptDebuggerValue(), QDeclarativeObjectScriptClass::setProperty(), QScriptDebuggerBackendPrivate::stepped(), and QScript::type().
 {
     Q_D(const QScriptValue);
     return d && d->isJSC() && d->jscValue.isUndefined();
 }
isValid()
bool QScriptValue::isValid () const
Returns true if this QScriptValue is valid; otherwise returns false.
Definition at line 2077 of file qscriptvalue.cpp.
Referenced by QScript::__setupPackage__(), breakpointDataFromScriptValue(), call(), QDeclarativeInclude::callback(), construct(), QScript::Equals(), QScriptDebuggerCommandExecutor::execute(), QDeclarativeEnginePrivate::getContext(), QScript::ClassObjectDelegate::getOwnPropertyDescriptor(), QScript::ClassObjectDelegate::getOwnPropertySlot(), QDeclarativeEnginePrivate::getUrl(), QDeclarativeInclude::include(), lessThan(), QScriptEngine::newObject(), QScript::FunctionWrapper::proxyCall(), QScriptDebuggerValue::QScriptDebuggerValue(), QDeclarativeObjectScriptClass::queryProperty(), setData(), QDeclarativeObjectScriptClass::setProperty(), setScope(), and QScriptExtensionPlugin::setupPackage().
 {
     Q_D(const QScriptValue);
     return d && (!d->isJSC() || !!d->jscValue);
 }
isVariant()
bool QScriptValue::isVariant () const
Returns true if this QScriptValue is a variant value; otherwise returns false.
See also
toVariant(), QScriptEngine::newVariant()
Definition at line 2034 of file qscriptvalue.cpp.
Referenced by FlatListModel::addValue(), QScript::Equals(), fromScriptValue(), QDeclarativeObjectMethodScriptClass::matchScore(), qscriptvalue_cast(), and FlatListScriptClass::setProperty().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC())
         return false;
     return QScriptEnginePrivate::isVariant(d->jscValue);
 }
lessThan()
bool QScriptValue::lessThan (const QScriptValue & other) const
Returns true if this QScriptValue is less than other, otherwise returns false.
The comparison follows the behavior described in ECMA-262 section 11.8.5, "The Abstract Relational Comparison Algorithm".
Note that if this QScriptValue or the other value are objects, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
equals()
Definition at line 843 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     // no equivalent function in JSC? There's a jsLess() in VM/Machine.cpp
     if (!isValid() || !other.isValid())
         return false;
     if (QScriptValuePrivate::getEngine(other) && d->engine
         && (QScriptValuePrivate::getEngine(other) != d->engine)) {
         qWarning("QScriptValue::lessThan: "
                  "cannot compare to a value created in "
                  "a different engine");
         return false;
     }
     return QScript::LessThan(*this, other);
 }
objectId()
qint64 QScriptValue::objectId () const
Returns the ID of this object, or -1 if this QScriptValue is not an object.
Warning
This function is not part of the public interface.
See also
QScriptEngine::objectById()
Definition at line 2216 of file qscriptvalue.cpp.
Referenced by fromScriptValue(), QJSDebuggerAgentPrivate::getLocals(), and QScriptDebuggerValue::QScriptDebuggerValue().
 {
     return d_ptr?d_ptr->objectId():-1;
 }
operator=()
QScriptValue & QScriptValue::operator= (const QScriptValue & other)
Assigns the other value to this QScriptValue.
Note that if other is an object (isObject() returns true), only a reference to the underlying object will be assigned; the object itself will not be copied.
Definition at line 485 of file qscriptvalue.cpp.
 {
     d_ptr = other.d_ptr;
     return *this;
 }
property() [1/3]
QScriptValue QScriptValue::property (const QString & name, const ResolveFlags & mode = ResolvePrototype) const
Returns the value of this QScriptValue's property with the given name, using the given mode to resolve the property.
If no such property exists, an invalid QScriptValue is returned.
If the property is implemented using a getter function (i.e. has the PropertyGetter flag set), calling property() has side-effects on the script engine, since the getter function will be called (possibly resulting in an uncaught script exception). If an exception occurred, property() returns the value that was thrown (typically an Error object).
See also
setProperty(), propertyFlags(), QScriptValueIterator
Definition at line 1432 of file qscriptvalue.cpp.
Referenced by QScript::__setupPackage__(), QScriptContext::argument(), QScriptDebuggerBackend::attachTo(), breakpointDataFromScriptValue(), QDeclarativeComponentPrivate::createObject(), data(), debuggerScriptValuePropertyFromScriptValue(), QDeclarativeXMLHttpRequest::dispatchCallback(), do_dbus_call(), QScriptDebuggerBackendPrivate::exception(), QScriptEngineAgentPrivate::exceptionThrow(), QDeclarativeExpressionPrivate::exceptionToError(), QScriptDebuggerCommandExecutor::execute(), fromScriptValue(), QScriptEngine::importExtension(), QDeclarativeEnginePrivate::init(), instanceOf(), QScriptDebuggerScriptedConsoleCommand::parse(), QDeclarativeObjectMethodScriptClass::property(), QDBusConnectionConstructor::QDBusConnectionConstructor(), qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlxmlhttprequest_onreadystatechange(), qScriptValueToSequence(), scriptDataFromScriptValue(), scriptValueToMessage(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeEnginePrivate::scriptValueToVariant(), ModelNode::setListValue(), QScriptExtensionPlugin::setupPackage(), QScriptEngine::uncaughtExceptionBacktrace(), and QScriptEngine::uncaughtExceptionLineNumber().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     return d->engine->scriptValueFromJSCValue(d->property(name, mode));
 }
property() [2/3]
QScriptValue QScriptValue::property (quint32 arrayIndex, const ResolveFlags & mode = ResolvePrototype) const
Returns the property at the given arrayIndex, using the given mode to resolve the property.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function is provided for convenience and performance when working with array objects.
If this QScriptValue is not an Array object, this function behaves as if property() was called with the string representation of arrayIndex.
Definition at line 1458 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     return d->engine->scriptValueFromJSCValue(d->property(arrayIndex, mode));
 }
property() [3/3]
QScriptValue QScriptValue::property (const QScriptString & name, const ResolveFlags & mode = ResolvePrototype) const
Returns the value of this QScriptValue's property with the given name, using the given mode to resolve the property.
Since
4.4
This overload of property() is useful when you need to look up the same property repeatedly, since the lookup can be performed faster when the name is represented as an interned string.
See also
QScriptEngine::toStringHandle(), setProperty()
Definition at line 1515 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject() || !QScriptStringPrivate::isValid(name))
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     return d->engine->scriptValueFromJSCValue(d->property(name.d_ptr->identifier, mode));
 }
propertyFlags() [1/2]
QScriptValue::PropertyFlags QScriptValue::propertyFlags (const QString & name, const ResolveFlags & mode = ResolvePrototype) const
Returns the flags of the property with the given name, using the given mode to resolve the property.
See also
property()
Definition at line 1566 of file qscriptvalue.cpp.
Referenced by QScriptClassPropertyIterator::flags().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return 0;
     QScript::APIShim shim(d->engine);
     JSC::ExecState *exec = d->engine->currentFrame;
     return d->propertyFlags(JSC::Identifier(exec, name), mode);
 }
propertyFlags() [2/2]
QScriptValue::PropertyFlags QScriptValue::propertyFlags (const QScriptString & name, const ResolveFlags & mode = ResolvePrototype) const
Returns the flags of the property with the given name, using the given mode to resolve the property.
Since
4.4
See also
property()
Definition at line 1589 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject() || !QScriptStringPrivate::isValid(name))
         return 0;
     return d->propertyFlags(name.d_ptr->identifier, mode);
 }
prototype()
QScriptValue QScriptValue::prototype () const
If this QScriptValue is an object, returns the internal prototype (__proto__ property) of this object; otherwise returns an invalid QScriptValue.
See also
setPrototype(), isObject()
Definition at line 554 of file qscriptvalue.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     return d->engine->scriptValueFromJSCValue(JSC::asObject(d->jscValue)->prototype());
 }
scope()
QScriptValue QScriptValue::scope () const
Warning
This function is not part of the public interface.
Definition at line 616 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isObject())
         return QScriptValue();
     QScript::APIShim shim(d->engine);
     // ### make hidden property
     JSC::JSValue result = d->property("__qt_scope__", QScriptValue::ResolveLocal);
     return d->engine->scriptValueFromJSCValue(result);
 }
scriptClass()
QScriptClass * QScriptValue::scriptClass () const
Returns the custom script class that this script object is an instance of, or 0 if the object is not of a custom class.
Since
4.4
See also
setScriptClass()
Definition at line 2154 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->isJSC() || !d->jscValue.inherits(&QScriptObject::info))
         return 0;
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(d->jscValue));
     QScriptObjectDelegate *delegate = scriptObject->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::ClassObject))
         return 0;
     return static_cast<QScript::ClassObjectDelegate*>(delegate)->scriptClass();
 }
setData()
void QScriptValue::setData (const QScriptValue & data)
Sets the internal data of this QScriptValue object.
Since
4.4
You can use this function to set object-specific data that won't be directly accessible to scripts, but may be retrieved in C++ using the data() function.
See also
QScriptEngine::reportAdditionalMemoryCost()
Definition at line 2121 of file qscriptvalue.cpp.
Referenced by NamedNodeMap::create(), NodeList::create(), QDeclarativeWorkerScriptEnginePrivate::getWorker(), QScriptEngine::newObject(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), qmlsqldatabase_executeSql(), qmlxmlhttprequest_new(), QScriptDebuggerBackend::traceFunction(), QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue(), and QDeclarativeInclude::worker_include().
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return;
     QScript::APIShim shim(d->engine);
     JSC::JSValue other = d->engine->scriptValueToJSCValue(data);
     if (d->jscValue.inherits(&QScriptObject::info)) {
         QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(d->jscValue));
         scriptObject->setData(other);
     } else {
         JSC::ExecState *exec = d->engine->currentFrame;
         JSC::Identifier id = JSC::Identifier(exec, "__qt_data__");
         if (!data.isValid()) {
             JSC::asObject(d->jscValue)->removeDirect(id);
         } else {
             // ### make hidden property
             JSC::asObject(d->jscValue)->putDirect(id, other);
         }
     }
 }
setProperty() [1/3]
void QScriptValue::setProperty (const QString & name, const QScriptValue & value, const PropertyFlags & flags = KeepExistingFlags)
Sets the value of this QScriptValue's property with the given name to the given value.
If this QScriptValue is not an object, this function does nothing.
If this QScriptValue does not already have a property with name name, a new property is created; the given flags then specify how this property may be accessed by script code.
If value is invalid, the property is removed.
If the property is implemented using a setter function (i.e. has the PropertySetter flag set), calling setProperty() has side-effects on the script engine, since the setter function will be called with the given value as argument (possibly resulting in an uncaught script exception).
Note that you cannot specify custom getter or setter functions for built-in properties, such as the length property of Array objects or meta properties of QObject objects.
See also
property()
Definition at line 1399 of file qscriptvalue.cpp.
Referenced by QScript::__setupPackage__(), QScriptDebuggerBackend::attachTo(), breakpointDataToScriptValue(), breakpointMapToScriptValue(), QDeclarativeInclude::callback(), consoleCommandGroupDataToScriptValue(), consoleCommandGroupMapToScriptValue(), consoleCommandToScriptValue(), contextInfoToScriptValue(), QDeclarativeComponentPrivate::createObject(), QDeclarativeEnginePrivate::createQmlObject(), debuggerResponseToScriptValue(), debuggerScriptValuePropertyToScriptValue(), QScriptDebuggerBackend::detach(), QScriptDebuggerCommandExecutor::execute(), QDeclarativeGlobalScriptClass::explicitSetProperty(), QDeclarativeInclude::finished(), QDeclarativeXmlListModel::get(), QDeclarativeWorkerScriptEnginePrivate::getWorker(), QScriptEngine::importExtension(), QDeclarativeInclude::include(), QDeclarativeEnginePrivate::init(), QtDBusScriptPlugin::initialize(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), messageToScriptValue(), QScriptEngine::newFunction(), QScriptDebuggerScriptedConsoleCommand::parse(), QDeclarativeWorkerScriptEnginePrivate::processMessage(), QDeclarativeObjectMethodScriptClass::property(), ModelNodeMetaObject::propertyWritten(), NamedNodeMap::prototype(), NodeList::prototype(), Node::prototype(), Element::prototype(), Attr::prototype(), CharacterData::prototype(), Text::prototype(), Document::prototype(), QDBusConnectionConstructor::QDBusConnectionConstructor(), qDBusErrorToScriptValue(), qDBusReplyToScriptValue(), QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass(), QDeclarativeScriptEngine::QDeclarativeScriptEngine(), qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlsqldatabase_item(), qmlsqldatabase_open_sync(), qmlsqldatabase_transaction_shared(), qmlxmlhttprequest_onreadystatechange(), QScriptDebuggerBackendPrivate::qsassert(), QScriptDBusInterfaceConstructor::QScriptDBusInterfaceConstructor(), QScriptDBusMessageConstructor::QScriptDBusMessageConstructor(), qScriptValueFromSequence(), qt_add_qmlsqldatabase(), qt_add_qmlxmlhttprequest(), QDeclarativeInclude::resultValue(), scriptDataToScriptValue(), scriptMapToScriptValue(), QDeclarativeEnginePrivate::scriptValueFromVariant(), QJSDebuggerAgent::setProperty(), setupDBusInterface(), QScriptExtensionPlugin::setupPackage(), QDeclarativeWorkerScriptEnginePrivate::variantToScriptValue(), and QDeclarativeInclude::worker_include().
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return;
     QScript::APIShim shim(d->engine);
     QScriptEnginePrivate *valueEngine = QScriptValuePrivate::getEngine(value);
     if (valueEngine && (valueEngine != d->engine)) {
         qWarning("QScriptValue::setProperty(%s) failed: "
                  "cannot set value created in a different engine",
                  qPrintable(name));
         return;
     }
     JSC::JSValue jsValue = d->engine->scriptValueToJSCValue(value);
     d->setProperty(name, jsValue, flags);
 }
setProperty() [2/3]
void QScriptValue::setProperty (quint32 arrayIndex, const QScriptValue & value, const PropertyFlags & flags = KeepExistingFlags)
Sets the property at the given arrayIndex to the given value.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function is provided for convenience and performance when working with array objects.
If this QScriptValue is not an Array object, this function behaves as if setProperty() was called with the string representation of arrayIndex.
Definition at line 1483 of file qscriptvalue.cpp.
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return;
     if (QScriptValuePrivate::getEngine(value)
         && (QScriptValuePrivate::getEngine(value) != d->engine)) {
         qWarning("QScriptValue::setProperty() failed: "
                  "cannot set value created in a different engine");
         return;
     }
     QScript::APIShim shim(d->engine);
     JSC::JSValue jsValue = d->engine->scriptValueToJSCValue(value);
     d->setProperty(arrayIndex, jsValue, flags);
 }
setProperty() [3/3]
void QScriptValue::setProperty (const QScriptString & name, const QScriptValue & value, const PropertyFlags & flags = KeepExistingFlags)
Sets the value of this QScriptValue's property with the given name to the given value.
Since
4.4
The given flags specify how this property may be accessed by script code.
This overload of setProperty() is useful when you need to set the same property repeatedly, since the operation can be performed faster when the name is represented as an interned string.
See also
QScriptEngine::toStringHandle()
Definition at line 1541 of file qscriptvalue.cpp.
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject() || !QScriptStringPrivate::isValid(name))
         return;
     QScriptEnginePrivate *valueEngine = QScriptValuePrivate::getEngine(value);
     if (valueEngine && (valueEngine != d->engine)) {
         qWarning("QScriptValue::setProperty(%s) failed: "
                  "cannot set value created in a different engine",
                  qPrintable(name.toString()));
         return;
     }
     QScript::APIShim shim(d->engine);
     JSC::JSValue jsValue = d->engine->scriptValueToJSCValue(value);
     d->setProperty(name.d_ptr->identifier, jsValue, flags);
 }
setPrototype()
void QScriptValue::setPrototype (const QScriptValue & prototype)
If this QScriptValue is an object, sets the internal prototype (__proto__ property) of this object to be prototype; otherwise does nothing.
The internal prototype should not be confused with the public property with name "prototype"; the public prototype is usually only set on functions that act as constructors.
See also
prototype(), isObject()
Definition at line 573 of file qscriptvalue.cpp.
Referenced by NamedNodeMap::create(), NodeList::create(), Node::create(), Document::load(), QScriptEngine::newObject(), Element::prototype(), Attr::prototype(), CharacterData::prototype(), Text::prototype(), CDATA::prototype(), Document::prototype(), and QDBusConnectionConstructor::QDBusConnectionConstructor().
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return;
     JSC::JSValue other = d->engine->scriptValueToJSCValue(prototype);
     if (!other || !(other.isObject() || other.isNull()))
         return;
     if (QScriptValuePrivate::getEngine(prototype)
         && (QScriptValuePrivate::getEngine(prototype) != d->engine)) {
         qWarning("QScriptValue::setPrototype() failed: "
                  "cannot set a prototype created in "
                  "a different engine");
         return;
     }
     JSC::JSObject *thisObject = JSC::asObject(d->jscValue);
     // check for cycle
     JSC::JSValue nextPrototypeValue = other;
     while (nextPrototypeValue && nextPrototypeValue.isObject()) {
         JSC::JSObject *nextPrototype = JSC::asObject(nextPrototypeValue);
         if (nextPrototype == thisObject) {
             qWarning("QScriptValue::setPrototype() failed: cyclic prototype value");
             return;
         }
         nextPrototypeValue = nextPrototype->prototype();
     }
     thisObject->setPrototype(other);
     // Sync the internal Global Object prototype if appropriate.
     if (((thisObject == d->engine->originalGlobalObjectProxy)
          && !d->engine->customGlobalObject())
         || (thisObject == d->engine->customGlobalObject())) {
         d->engine->originalGlobalObject()->setPrototype(other);
     }
 }
setScope()
void QScriptValue::setScope (const QScriptValue & scope)
Warning
This function is not part of the public interface.
Definition at line 630 of file qscriptvalue.cpp.
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return;
     if (scope.isValid() && QScriptValuePrivate::getEngine(scope)
         && (QScriptValuePrivate::getEngine(scope) != d->engine)) {
         qWarning("QScriptValue::setScope() failed: "
                  "cannot set a scope object created in "
                  "a different engine");
         return;
     }
     JSC::JSValue other = d->engine->scriptValueToJSCValue(scope);
     JSC::ExecState *exec = d->engine->currentFrame;
     JSC::Identifier id = JSC::Identifier(exec, "__qt_scope__");
     if (!scope.isValid()) {
         JSC::asObject(d->jscValue)->removeDirect(id);
     } else {
         // ### make hidden property
         JSC::asObject(d->jscValue)->putDirect(id, other);
     }
 }
setScriptClass()
void QScriptValue::setScriptClass (QScriptClass * scriptClass)
Sets the custom script class of this script object to scriptClass.
Since
4.4
This can be used to "promote" a plain script object (e.g. created by the "new" operator in a script, or by QScriptEngine::newObject() in C++) to an object of a custom type.
If scriptClass is 0, the object will be demoted to a plain script object.
See also
scriptClass(), setData()
Definition at line 2182 of file qscriptvalue.cpp.
Referenced by NamedNodeMap::create(), NodeList::create(), QDeclarativeGlobalScriptClass::explicitSetProperty(), and QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass().
 {
     Q_D(QScriptValue);
     if (!d || !d->isObject())
         return;
     if (!d->jscValue.inherits(&QScriptObject::info)) {
         qWarning("QScriptValue::setScriptClass() failed: "
                  "cannot change class of non-QScriptObject");
         return;
     }
     QScriptObject *scriptObject = static_cast<QScriptObject*>(JSC::asObject(d->jscValue));
     if (!scriptClass) {
         scriptObject->setDelegate(0);
     } else {
         QScriptObjectDelegate *delegate = scriptObject->delegate();
         if (!delegate || (delegate->type() != QScriptObjectDelegate::ClassObject)) {
             delegate = new QScript::ClassObjectDelegate(scriptClass);
             scriptObject->setDelegate(delegate);
         }
         static_cast<QScript::ClassObjectDelegate*>(delegate)->setScriptClass(scriptClass);
     }
 }
strictlyEquals()
bool QScriptValue::strictlyEquals (const QScriptValue & other) const
Returns true if this QScriptValue is equal to other using strict comparison (no conversion), otherwise returns false.
The comparison follows the behavior described in ECMA-262 section 11.9.6, "The Strict Equality Comparison Algorithm".
If the type of this QScriptValue is different from the type of the other value, this function returns false. If the types are equal, the result depends on the type, as shown in the following table:
Type Result
Undefined true
Null true
Boolean true if both values are true, false otherwise
Number false if either value is NaN (Not-a-Number); true if values are equal, false otherwise
String true if both values are exactly the same sequence of characters, false otherwise
Object true if both values refer to the same object, false otherwise
See also
equals()
Definition at line 934 of file qscriptvalue.cpp.
Referenced by _q_equal(), and QScript::Equals().
 {
     Q_D(const QScriptValue);
     if (!d || !other.d_ptr)
         return (d_ptr == other.d_ptr);
     if (QScriptValuePrivate::getEngine(other) && d->engine
         && (QScriptValuePrivate::getEngine(other) != d->engine)) {
         qWarning("QScriptValue::strictlyEquals: "
                  "cannot compare to a value created in "
                  "a different engine");
         return false;
     }
     if (d->type != other.d_ptr->type) {
         if (d->type == QScriptValuePrivate::JavaScriptCore) {
             QScriptEnginePrivate *eng_p = d->engine ? d->engine : other.d_ptr->engine;
             if (eng_p)
                 return JSC::JSValue::strictEqual(eng_p->currentFrame, d->jscValue, eng_p->scriptValueToJSCValue(other));
         } else if (other.d_ptr->type == QScriptValuePrivate::JavaScriptCore) {
             QScriptEnginePrivate *eng_p = other.d_ptr->engine ? other.d_ptr->engine : d->engine;
             if (eng_p)
                 return JSC::JSValue::strictEqual(eng_p->currentFrame, eng_p->scriptValueToJSCValue(*this), other.d_ptr->jscValue);
         }
         return false;
     }
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         QScriptEnginePrivate *eng_p = d->engine ? d->engine : other.d_ptr->engine;
         JSC::ExecState *exec = eng_p ? eng_p->currentFrame : 0;
         return JSC::JSValue::strictEqual(exec, d->jscValue, other.d_ptr->jscValue);
     }
     case QScriptValuePrivate::Number:
         return (d->numberValue == other.d_ptr->numberValue);
     case QScriptValuePrivate::String:
         return (d->stringValue == other.d_ptr->stringValue);
     }
     return false;
 }
toBool()
bool QScriptValue::toBool () const
Returns the boolean value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.
Since
4.5
2, "ToBoolean".
Note that if this QScriptValue is an object, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
isBool()
Definition at line 1088 of file qscriptvalue.cpp.
Referenced by QScript::Equals(), QScript::LessThan(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), and QDeclarativeSqlQueryScriptClass::setProperty().
 {
     Q_D(const QScriptValue);
     if (!d)
         return false;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toBool(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toBool(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return QScript::ToBool(d->numberValue);
     case QScriptValuePrivate::String:
         return QScript::ToBool(d->stringValue);
     }
     return false;
 }
toBoolean()
bool QScriptValue::toBoolean () const
Use toBool() instead.
Definition at line 1049 of file qscriptvalue.cpp.
Referenced by breakpointDataFromScriptValue(), QScriptDebuggerAgent::positionChange(), qmlxmlhttprequest_open(), QScriptDebuggerBackendPrivate::qsassert(), QScriptDebuggerValue::QScriptDebuggerValue(), and scriptValueToMessage().
 {
     Q_D(const QScriptValue);
     if (!d)
         return false;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toBool(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toBool(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return QScript::ToBool(d->numberValue);
     case QScriptValuePrivate::String:
         return QScript::ToBool(d->stringValue);
     }
     return false;
 }
toDateTime()
QDateTime QScriptValue::toDateTime () const
Returns a QDateTime representation of this value, in local time.
If this QScriptValue is not a date, or the value of the date is NaN (Not-a-Number), an invalid QDateTime is returned.
See also
isDate()
Definition at line 1313 of file qscriptvalue.cpp.
Referenced by QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), fromScriptValue(), and QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant().
 {
     Q_D(const QScriptValue);
     if (!d || !d->engine)
         return QDateTime();
     QScript::APIShim shim(d->engine);
     return QScriptEnginePrivate::toDateTime(d->engine->currentFrame, d->jscValue);
 }
toInt32()
qint32 QScriptValue::toInt32 () const
Returns the signed 32-bit integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.5, "ToInt32".
Note that if this QScriptValue is an object, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
toNumber(), toUInt32()
Definition at line 1122 of file qscriptvalue.cpp.
Referenced by breakpointDataFromScriptValue(), debuggerScriptValuePropertyFromScriptValue(), QDeclarativeObjectScriptClass::destroy(), QScriptDebuggerBackendPrivate::exception(), QScriptEngineAgentPrivate::exceptionThrow(), QDeclarativeObjectMethodScriptClass::property(), qmlsqldatabase_executeSql(), scriptDataFromScriptValue(), QDeclarativeEnginePrivate::scriptValueToVariant(), ModelNode::setListValue(), QScriptEngine::uncaughtExceptionBacktrace(), and QScriptEngine::uncaughtExceptionLineNumber().
 {
     Q_D(const QScriptValue);
     if (!d)
         return 0;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toInt32(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toInt32(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return QScript::ToInt32(d->numberValue);
     case QScriptValuePrivate::String:
         return QScript::ToInt32(d->stringValue);
     }
     return 0;
 }
toInteger()
qsreal QScriptValue::toInteger () const
Returns the integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.4, "ToInteger".
Note that if this QScriptValue is an object, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
toNumber()
Definition at line 1224 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d)
         return 0;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toInteger(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toInteger(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return QScript::ToInteger(d->numberValue);
     case QScriptValuePrivate::String:
         return QScript::ToInteger(d->stringValue);
     }
     return 0;
 }
toNumber()
qsreal QScriptValue::toNumber () const
Returns the number value of this QScriptValue, as defined in ECMA-262 section 9.3, "ToNumber".
Note that if this QScriptValue is an object, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
isNumber(), toInteger(), toInt32(), toUInt32(), toUInt16()
Definition at line 1019 of file qscriptvalue.cpp.
Referenced by _q_equal(), breakpointDataFromScriptValue(), QDeclarativeEnginePrivate::darker(), QScript::Equals(), QDeclarativeEnginePrivate::hsla(), QScript::LessThan(), QDeclarativeEnginePrivate::lighter(), QDeclarativeEnginePrivate::point(), QDeclarativeObjectMethodScriptClass::property(), qmlsqldatabase_item(), qmlsqldatabase_open_sync(), QScriptDebuggerValue::QScriptDebuggerValue(), QDeclarativeEnginePrivate::rect(), QDeclarativeEnginePrivate::rgba(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeEnginePrivate::size(), and QDeclarativeEnginePrivate::vector3d().
 {
     Q_D(const QScriptValue);
     if (!d)
         return 0;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toNumber(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toNumber(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return d->numberValue;
     case QScriptValuePrivate::String:
         return QScript::ToNumber(d->stringValue);
     }
     return 0;
 }
toObject()
QScriptValue QScriptValue::toObject () const
This function is obsolete; use QScriptEngine::toObject() instead.
Definition at line 1298 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->engine)
         return QScriptValue();
     return engine()->toObject(*this);
 }
toQMetaObject()
const QMetaObject * QScriptValue::toQMetaObject () const
If this QScriptValue is a QMetaObject, returns the QMetaObject pointer that the QScriptValue represents; otherwise, returns 0.
See also
isQMetaObject()
Definition at line 1365 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d || !d->engine)
         return 0;
     QScript::APIShim shim(d->engine);
     return QScriptEnginePrivate::toQMetaObject(d->engine->currentFrame, d->jscValue);
 }
toQObject()
QObject * QScriptValue::toQObject () const
If this QScriptValue is a QObject, returns the QObject pointer that the QScriptValue represents; otherwise, returns 0.
If the QObject that this QScriptValue wraps has been deleted, this function returns 0 (i.e. it is possible for toQObject() to return 0 even when isQObject() returns true).
See also
isQObject()
Definition at line 1350 of file qscriptvalue.cpp.
Referenced by do_dbus_call(), QScript::Equals(), fromScriptValue(), QDeclarativeEnginePrivate::isQtObject(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), QDeclarativeObjectMethodScriptClass::property(), qmlxmlhttprequest_abort(), qmlxmlhttprequest_getAllResponseHeaders(), qmlxmlhttprequest_getResponseHeader(), qmlxmlhttprequest_onreadystatechange(), qmlxmlhttprequest_open(), qmlxmlhttprequest_readyState(), qmlxmlhttprequest_responseText(), qmlxmlhttprequest_responseXML(), qmlxmlhttprequest_send(), qmlxmlhttprequest_setRequestHeader(), qmlxmlhttprequest_status(), qmlxmlhttprequest_statusText(), QScriptDBusInterfaceConstructor::qscript_call(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeEnginePrivate::scriptValueToVariant(), QScriptDebuggerScriptedConsoleCommandJob::start(), QDeclarativeObjectScriptClass::toQObject(), and QDeclarativeObjectScriptClass::tostring().
 {
     Q_D(const QScriptValue);
     if (!d || !d->engine)
         return 0;
     QScript::APIShim shim(d->engine);
     return QScriptEnginePrivate::toQObject(d->engine->currentFrame, d->jscValue);
 }
toRegExp()
QRegExp QScriptValue::toRegExp () const
Returns the QRegExp representation of this value.
If this QScriptValue is not a regular expression, an empty QRegExp is returned.
See also
isRegExp()
Definition at line 1330 of file qscriptvalue.cpp.
Referenced by QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant().
 {
     Q_D(const QScriptValue);
     if (!d || !d->engine)
          return QRegExp();
     QScript::APIShim shim(d->engine);
     return QScriptEnginePrivate::toRegExp(d->engine->currentFrame, d->jscValue);
 }
toString()
QString QScriptValue::toString () const
Returns the string value of this QScriptValue, as defined in ECMA-262 section 9.8, "ToString".
Note that if this QScriptValue is an object, calling this function has side effects on the script engine, since the engine will call the object's toString() function (and possibly valueOf()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
isString()
Definition at line 986 of file qscriptvalue.cpp.
Referenced by QScript::__setupPackage__(), QDeclarativeEnginePrivate::atob(), breakpointDataFromScriptValue(), QDeclarativeEnginePrivate::btoa(), QDeclarativeEnginePrivate::consoleLog(), QDeclarativeEnginePrivate::createComponent(), QScriptDBusMessageConstructor::createErrorReply(), QDeclarativeEnginePrivate::createQmlObject(), debuggerScriptValuePropertyFromScriptValue(), QDeclarativeEnginePrivate::desktopOpenUrl(), do_dbus_call(), QScriptDebuggerBackend::doPendingEvaluate(), QScript::Equals(), QScriptDebuggerBackendPrivate::exception(), QDeclarativeExpressionPrivate::exceptionToError(), QScriptDebuggerCommandExecutor::execute(), QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), fromScriptValue(), QJSDebuggerAgent::functionExit(), QScriptDebuggerScriptedConsoleCommandJob::handleResponse(), QDeclarativeInclude::include(), QDeclarativeExpressionPrivate::init(), QScript::LessThan(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), QDeclarativeEnginePrivate::md5(), QScriptDebuggerScriptedConsoleCommand::parse(), QDeclarativeObjectMethodScriptClass::property(), qmlsqldatabase_change_version(), qmlsqldatabase_executeSql(), qmlsqldatabase_executeSql_readonly(), qmlsqldatabase_open_sync(), qmlxmlhttprequest_getResponseHeader(), qmlxmlhttprequest_open(), qmlxmlhttprequest_send(), qmlxmlhttprequest_setRequestHeader(), QScriptDebuggerBackendPrivate::qsassert(), QScriptDebuggerValue::QScriptDebuggerValue(), QDeclarativeScriptEngine::resolvedUrl(), scriptDataFromScriptValue(), QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant(), QDeclarativeObjectScriptClass::setProperty(), QScriptDebuggerScriptedConsoleCommandJob::start(), QScriptDebuggerBackendPrivate::stepped(), QJSDebuggerAgentPrivate::stopped(), QScriptContext::toString(), QScriptDebuggerBackendPrivate::trace(), QScriptEngine::uncaughtExceptionBacktrace(), and QDeclarativeInclude::worker_include().
 {
     Q_D(const QScriptValue);
     if (!d)
         return QString();
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toString(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toString(0, d->jscValue);
         }    }
     case QScriptValuePrivate::Number:
         return QScript::ToString(d->numberValue);
     case QScriptValuePrivate::String:
         return d->stringValue;
     }
     return QString();
 }
toUInt16()
quint16 QScriptValue::toUInt16 () const
Returns the unsigned 16-bit integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.7, "ToUint16".
Note that if this QScriptValue is an object, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
toNumber()
Definition at line 1190 of file qscriptvalue.cpp.
 {
     Q_D(const QScriptValue);
     if (!d)
         return 0;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toUInt16(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toUInt16(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return QScript::ToUInt16(d->numberValue);
     case QScriptValuePrivate::String:
         return QScript::ToUInt16(d->stringValue);
     }
     return 0;
 }
toUInt32()
quint32 QScriptValue::toUInt32 () const
Returns the unsigned 32-bit integer value of this QScriptValue, using the conversion rules described in ECMA-262 section 9.6, "ToUint32".
Note that if this QScriptValue is an object, calling this function has side effects on the script engine, since the engine will call the object's valueOf() function (and possibly toString()) in an attempt to convert the object to a primitive value (possibly resulting in an uncaught script exception).
See also
toNumber(), toInt32()
Definition at line 1156 of file qscriptvalue.cpp.
Referenced by call(), construct(), QDeclarativeEnginePrivate::formatDate(), QDeclarativeEnginePrivate::formatDateTime(), QDeclarativeEnginePrivate::formatTime(), QDeclarativeObjectMethodScriptClass::property(), qScriptValueToSequence(), and scriptValueToMessage().
 {
     Q_D(const QScriptValue);
     if (!d)
         return 0;
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toUInt32(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toUInt32(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return QScript::ToUInt32(d->numberValue);
     case QScriptValuePrivate::String:
         return QScript::ToUInt32(d->stringValue);
     }
     return 0;
 }
toVariant()
QVariant QScriptValue::toVariant () const
Returns the QVariant value of this QScriptValue, if it can be converted to a QVariant; otherwise returns an invalid QVariant.
The conversion is performed according to the following table:
Input Type Result
Undefined An invalid QVariant.
Null An invalid QVariant.
Boolean A QVariant containing the value of the boolean.
Number A QVariant containing the value of the number.
String A QVariant containing the value of the string.
QVariant Object The result is the QVariant value of the object (no conversion).
QObject Object A QVariant containing a pointer to the QObject.
Date Object A QVariant containing the date value (toDateTime()).
RegExp Object A QVariant containing the regular expression value (toRegExp()).
Array Object The array is converted to a QVariantList. Each element is converted to a QVariant, recursively; cyclic references are not followed.
Object The object is converted to a QVariantMap. Each property is converted to a QVariant, recursively; cyclic references are not followed.
See also
isVariant()
Definition at line 1268 of file qscriptvalue.cpp.
Referenced by FlatListModel::addValue(), QScriptDBusMessageConstructor::createReply(), QDeclarativeEnginePrivate::darker(), do_dbus_call(), QScript::Equals(), QDeclarativeEnginePrivate::formatTime(), QDeclarativeEnginePrivate::lighter(), QDeclarativeObjectMethodScriptClass::matchScore(), QDeclarativeWorkerScriptEnginePrivate::onMessage(), qmlsqldatabase_executeSql(), qscriptvalue_cast(), scriptValueToMessage(), QDeclarativeEnginePrivate::scriptValueToVariant(), QDeclarativeWorkerScriptEnginePrivate::sendMessage(), ModelNode::setListValue(), ModelNode::setObjectValue(), FlatListScriptClass::setProperty(), and QDeclarativeEnginePrivate::tint().
 {
     Q_D(const QScriptValue);
     if (!d)
         return QVariant();
     switch (d->type) {
     case QScriptValuePrivate::JavaScriptCore: {
         if (d->engine) {
             QScript::APIShim shim(d->engine);
             return QScriptEnginePrivate::toVariant(d->engine->currentFrame, d->jscValue);
         } else {
             return QScriptEnginePrivate::toVariant(0, d->jscValue);
         }
     }
     case QScriptValuePrivate::Number:
         return QVariant(d->numberValue);
     case QScriptValuePrivate::String:
         return QVariant(d->stringValue);
     }
     return QVariant();
 }
Friends and Related Functions
QScriptEnginePrivate
friend class QScriptEnginePrivate friend
Definition at line 213 of file qscriptvalue.h.
qscriptvalue_cast()
T qscriptvalue_cast (const QScriptValue & value) related
Returns the given value converted to the template type T.
Since
4.3
See also
qScriptRegisterMetaType(), QScriptEngine::toScriptValue()
Definition at line 344 of file qscriptengine.h.
Referenced by debuggerScriptValuePropertyFromScriptValue(), and qscriptQMetaObjectConstructor().
 {
     T t;
     const int id = qMetaTypeId<T>();
     if (qscriptvalue_cast_helper(value, id, &t))
         return t;
     else if (value.isVariant())
         return qvariant_cast<T>(value.toVariant());
     return T();
 }
Properties
d_ptr
QExplicitlySharedDataPointer<QScriptValuePrivate> QScriptValue::d_ptr private
Definition at line 209 of file qscriptvalue.h.
Referenced by equals(), QScriptValuePrivate::getEngine(), objectId(), operator=(), QScriptValue(), and strictlyEquals().
The documentation for this class was generated from the following files:
/src/script/api/qscriptvalue.h
/src/script/api/qscriptengine.cpp
/src/script/api/qscriptvalue.cpp