Qt 4.8: QPatternist::ColorOutput Class Reference
QPatternist::ColorOutput Class Reference
#include <qcoloroutput_p.h>
Public Types
typedef QFlags< ColorCodeComponent > ColorCode
enum ColorCodeComponent {
BlackForeground = 1 << ForegroundShift, BlueForeground = 2 << ForegroundShift, GreenForeground = 3 << ForegroundShift, CyanForeground = 4 << ForegroundShift,
RedForeground = 5 << ForegroundShift, PurpleForeground = 6 << ForegroundShift, BrownForeground = 7 << ForegroundShift, LightGrayForeground = 8 << ForegroundShift,
DarkGrayForeground = 9 << ForegroundShift, LightBlueForeground = 10 << ForegroundShift, LightGreenForeground = 11 << ForegroundShift, LightCyanForeground = 12 << ForegroundShift,
LightRedForeground = 13 << ForegroundShift, LightPurpleForeground = 14 << ForegroundShift, YellowForeground = 15 << ForegroundShift, WhiteForeground = 16 << ForegroundShift,
BlackBackground = 1 << BackgroundShift, BlueBackground = 2 << BackgroundShift, GreenBackground = 3 << BackgroundShift, CyanBackground = 4 << BackgroundShift,
RedBackground = 5 << BackgroundShift, PurpleBackground = 6 << BackgroundShift, BrownBackground = 7 << BackgroundShift, DefaultColor = 1 << SpecialShift
}
typedef QHash< int, ColorCode > ColorMapping
Public Functions
QString colorify (const QString &message, int color=-1) const
Treats message and colorID identically to write(), but instead of writing message to stderr, it is prepared for being written to stderr, but is then returned.
ColorMapping colorMapping () const
Returns the color mappings in use.
ColorOutput ()
Constructs a ColorOutput instance, ready for use.
void insertMapping (int colorID, const ColorCode colorCode)
Adds a color mapping from colorID to colorCode, for this ColorOutput instance.
void setColorMapping (const ColorMapping &cMapping)
Sets the color mapping to be cMapping.
void write (const QString &message, int color=-1)
Sends message to stderr, using the color looked up in colorMapping() using colorID.
void writeUncolored (const QString &message)
Writes message to stderr as if for instance QTextStream would have been used, and adds a line ending at the end.
~ColorOutput ()
Destructs this ColorOutput instance.
Private Types
enum {
ForegroundShift = 10, BackgroundShift = 20, SpecialShift = 20, ForegroundMask = ((1 << ForegroundShift) - 1) << ForegroundShift,
BackgroundMask = ((1 << BackgroundShift) - 1) << BackgroundShift
}
Properties
ColorOutputPrivate * d
Detailed Description
Definition at line 66 of file qcoloroutput_p.h.
Typedefs
ColorCode
typedef QFlags<ColorCodeComponent> QPatternist::ColorOutput::ColorCode
Definition at line 107 of file qcoloroutput_p.h.
ColorMapping
typedef QHash<int, ColorCode> QPatternist::ColorOutput::ColorMapping
Definition at line 108 of file qcoloroutput_p.h.
Enumerations
anonymous enum
anonymous enum private
Enumerator
ForegroundShift
BackgroundShift
SpecialShift
ForegroundMask
BackgroundMask
Definition at line 68 of file qcoloroutput_p.h.
         {
             ForegroundShift = 10,
             BackgroundShift = 20,
             SpecialShift    = 20,
             ForegroundMask  = ((1 << ForegroundShift) - 1) << ForegroundShift,
             BackgroundMask  = ((1 << BackgroundShift) - 1) << BackgroundShift
         };
ColorCodeComponent
enum QPatternist::ColorOutput::ColorCodeComponent
Enumerator
BlackForeground
BlueForeground
GreenForeground
CyanForeground
RedForeground
PurpleForeground
BrownForeground
LightGrayForeground
DarkGrayForeground
LightBlueForeground
LightGreenForeground
LightCyanForeground
LightRedForeground
LightPurpleForeground
YellowForeground
WhiteForeground
BlackBackground
BlueBackground
GreenBackground
CyanBackground
RedBackground
PurpleBackground
BrownBackground
DefaultColor
Definition at line 78 of file qcoloroutput_p.h.
         {
             BlackForeground         = 1 << ForegroundShift,
             BlueForeground          = 2 << ForegroundShift,
             GreenForeground         = 3 << ForegroundShift,
             CyanForeground          = 4 << ForegroundShift,
             RedForeground           = 5 << ForegroundShift,
             PurpleForeground        = 6 << ForegroundShift,
             BrownForeground         = 7 << ForegroundShift,
             LightGrayForeground     = 8 << ForegroundShift,
             DarkGrayForeground      = 9 << ForegroundShift,
             LightBlueForeground     = 10 << ForegroundShift,
             LightGreenForeground    = 11 << ForegroundShift,
             LightCyanForeground     = 12 << ForegroundShift,
             LightRedForeground      = 13 << ForegroundShift,
             LightPurpleForeground   = 14 << ForegroundShift,
             YellowForeground        = 15 << ForegroundShift,
             WhiteForeground         = 16 << ForegroundShift,
             BlackBackground         = 1 << BackgroundShift,
             BlueBackground          = 2 << BackgroundShift,
             GreenBackground         = 3 << BackgroundShift,
             CyanBackground          = 4 << BackgroundShift,
             RedBackground           = 5 << BackgroundShift,
             PurpleBackground        = 6 << BackgroundShift,
             BrownBackground         = 7 << BackgroundShift,
             DefaultColor            = 1 << SpecialShift
         };
Constructors and Destructors
ColorOutput()
ColorOutput::ColorOutput ()
Constructs a ColorOutput instance, ready for use.
Definition at line 271 of file qcoloroutput.cpp.
                          : d(new ColorOutputPrivate())
 {
 }
~ColorOutput()
ColorOutput::~ColorOutput ()
Destructs this ColorOutput instance.
Definition at line 278 of file qcoloroutput.cpp.
 {
     delete d;
 }
Functions
colorify()
QString ColorOutput::colorify (const QString & message, int colorID = -1) const
Treats message and colorID identically to write(), but instead of writing message to stderr, it is prepared for being written to stderr, but is then returned.
This is useful when the colored string is inserted into a translated string(dividing the string into several small strings prevents proper translation).
Definition at line 319 of file qcoloroutput.cpp.
Referenced by QPatternist::ColoringMessageHandler::colorifyDescription(), QPatternist::ColoringMessageHandler::handleMessage(), and write().
 {
     Q_ASSERT_X(colorID == -1 || d->colorMapping.contains(colorID), Q_FUNC_INFO,
                qPrintable(QString::fromLatin1("There is no color registered by id %1").arg(colorID)));
     Q_ASSERT_X(!message.isEmpty(), Q_FUNC_INFO, "It makes no sense to attempt to print an empty string.");
     if(colorID != -1)
         d->currentColorID = colorID;
     if(d->coloringEnabled && colorID != -1)
     {
         const int color(d->colorMapping.value(colorID));
         /* If DefaultColor is set, we don't want to color it. */
         if(color & DefaultColor)
             return message;
         const int foregroundCode = (int(color) & ForegroundMask) >> ForegroundShift;
         const int backgroundCode = (int(color) & BackgroundMask) >> BackgroundShift;
         QString finalMessage;
         bool closureNeeded = false;
         if(foregroundCode)
         {
             finalMessage.append(ColorOutputPrivate::escapeCode(QLatin1String(ColorOutputPrivate::foregrounds[foregroundCode - 1])));
             closureNeeded = true;
         }
         if(backgroundCode)
         {
             finalMessage.append(ColorOutputPrivate::escapeCode(QLatin1String(ColorOutputPrivate::backgrounds[backgroundCode - 1])));
             closureNeeded = true;
         }
         finalMessage.append(message);
         if(closureNeeded)
         {
             finalMessage.append(QChar(0x1B));
             finalMessage.append(QLatin1String("[0m"));
         }
         return finalMessage;
     }
     else
         return message;
 }
colorMapping()
ColorOutput::ColorMapping ColorOutput::colorMapping () const
Returns the color mappings in use.
See also
setColorMapping(), insertMapping()
Definition at line 263 of file qcoloroutput.cpp.
 {
     return d->colorMapping;
 }
insertMapping()
void ColorOutput::insertMapping (int colorID, const ColorCode colorCode)
Adds a color mapping from colorID to colorCode, for this ColorOutput instance.
This is a convenience function for creating a ColorOutput::ColorMapping instance and calling setColorMapping().
See also
colorMapping(), setColorMapping()
Definition at line 375 of file qcoloroutput.cpp.
Referenced by QPatternist::ColoringMessageHandler::ColoringMessageHandler().
 {
     d->colorMapping.insert(colorID, colorCode);
 }
setColorMapping()
void ColorOutput::setColorMapping (const ColorMapping & cMapping)
Sets the color mapping to be cMapping.
Negative values are disallowed.
See also
colorMapping(), insertMapping()
Definition at line 253 of file qcoloroutput.cpp.
 {
     d->colorMapping = cMapping;
 }
write()
void ColorOutput::write (const QString & message, int colorID = -1)
Sends message to stderr, using the color looked up in colorMapping() using colorID.
If color isn't available in colorMapping(), result and behavior is undefined.
If colorID is 0, which is the default value, the previously used coloring is used. ColorOutput is initialized to not color at all.
If message is empty, effects are undefined.
message will be printed as is. For instance, no line endings will be inserted.
Definition at line 295 of file qcoloroutput.cpp.
 {
     d->write(colorify(message, colorID));
 }
writeUncolored()
void ColorOutput::writeUncolored (const QString & message)
Writes message to stderr as if for instance QTextStream would have been used, and adds a line ending at the end.
This function can be practical to use such that one can use ColorOutput for all forms of writing.
Definition at line 306 of file qcoloroutput.cpp.
Referenced by QPatternist::ColoringMessageHandler::handleMessage().
 {
     d->write(message + QLatin1Char('\n'));
 }
Properties
d
ColorOutputPrivate* QPatternist::ColorOutput::d private
Definition at line 122 of file qcoloroutput_p.h.
Referenced by colorify(), insertMapping(), write(), writeUncolored(), and ~ColorOutput().
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qcoloroutput_p.h
/src/xmlpatterns/api/qcoloroutput.cpp