Qt 4.8: QPPDOptionsModel Class Reference
QPPDOptionsModel Class Reference
Public Functions
int columnCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of columns for the children of the given parent.
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Returns the data stored under the given role for the item referred to by the index.
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the data for the given role and section in the header with the specified orientation.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns the index of the item in the model specified by the given row, column and parent index.
QModelIndex parent (const QModelIndex &index) const
Returns the parent of the model item with the given index.
void parseChoices (QOptionTreeItem *parent)
void parseGroups (QOptionTreeItem *parent)
void parseItems ()
void parseOptions (QOptionTreeItem *parent)
QPPDOptionsModel (QCUPSSupport *cups, QObject *parent=0)
int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of rows under the given parent.
~QPPDOptionsModel ()
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
virtual bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Returns true if parent has any children; otherwise returns false.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the role data for the item at index to value.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts the model by column in the given order.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QCUPSSupport * cups
const ppd_file_t * ppd
QOptionTreeItem * rootItem
Friends
class QPPDOptionsEditor
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 214 of file qprintdialog_unix.cpp.
Constructors and Destructors
QPPDOptionsModel()
QPPDOptionsModel::QPPDOptionsModel (QCUPSSupport * cups, QObject * parent = 0)
Definition at line 1065 of file qprintdialog_unix.cpp.
     : QAbstractItemModel(parent), rootItem(0), cups(c), ppd(c->currentPPD())
 {
     parseItems();
 }
~QPPDOptionsModel()
QPPDOptionsModel::~QPPDOptionsModel ()
Definition at line 1071 of file qprintdialog_unix.cpp.
 {
 }
Functions
columnCount()
int QPPDOptionsModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of columns for the children of the given parent.
In most subclasses, the number of columns is independent of the parent.
For example:
int DomModel::columnCount(const QModelIndex &/*parent*/) const
{
    return 3;
}
Note
When implementing a table based model, columnCount() should return 0 when the parent is valid.
See also
rowCount()
Implements QAbstractItemModel.
Definition at line 1075 of file qprintdialog_unix.cpp.
 {
     return 2;
 }
data()
QVariant QPPDOptionsModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Returns the data stored under the given role for the item referred to by the index.
Note
If you do not have a value to return, return an invalid QVariant instead of returning 0.
See also
Qt::ItemDataRole, setData(), headerData()
Implements QAbstractItemModel.
Definition at line 1094 of file qprintdialog_unix.cpp.
 {
     switch(role) {
         case Qt::FontRole: {
             QOptionTreeItem* itm = reinterpret_cast<QOptionTreeItem*>(index.internalPointer());
             if (itm && itm->type == QOptionTreeItem::Group){
                 QFont font = QApplication::font();
                 font.setBold(true);
                 return QVariant(font);
             }
             return QVariant();
         }
         break;
         case Qt::DisplayRole: {
             QOptionTreeItem* itm;
             if (!index.isValid())
                 itm = rootItem;
             else
                 itm = reinterpret_cast<QOptionTreeItem*>(index.internalPointer());
             if (index.column() == 0)
                 return cups->unicodeString(itm->description);
             else if (itm->type == QOptionTreeItem::Option && itm->selected > -1)
                 return cups->unicodeString(itm->selDescription);
             else
                 return QVariant();
         }
         break;
         default:
             return QVariant();
     }
     if (role != Qt::DisplayRole)
         return QVariant();
 }
flags()
Qt::ItemFlags QPPDOptionsModel::flags (const QModelIndex & index) const virtual
Returns the item flags for the given index.
The base class implementation returns a combination of flags that enables the item (ItemIsEnabled) and allows it to be selected (ItemIsSelectable).
See also
Qt::ItemFlags
Reimplemented from QAbstractItemModel.
Definition at line 1156 of file qprintdialog_unix.cpp.
 {
     if (!index.isValid() || reinterpret_cast<QOptionTreeItem*>(index.internalPointer())->type == QOptionTreeItem::Group)
         return Qt::ItemIsEnabled;
     if (index.column() == 1)
         return Qt::ItemIsEnabled | Qt::ItemIsSelectable | Qt::ItemIsEditable;
     return Qt::ItemIsEnabled | Qt::ItemIsSelectable;
 }
headerData()
QVariant QPPDOptionsModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Returns the data for the given role and section in the header with the specified orientation.
For horizontal headers, the section number corresponds to the column number. Similarly, for vertical headers, the section number corresponds to the row number.
See also
Qt::ItemDataRole, setHeaderData(), QHeaderView
Reimplemented from QAbstractItemModel.
Definition at line 1234 of file qprintdialog_unix.cpp.
 {
     if (role != Qt::DisplayRole)
         return QVariant();
     switch(section){
         case 0:
             return QVariant(QApplication::translate("QPPDOptionsModel", "Name"));
         case 1:
             return QVariant(QApplication::translate("QPPDOptionsModel", "Value"));
         default:
             return QVariant();
     }
 }
index()
QModelIndex QPPDOptionsModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Returns the index of the item in the model specified by the given row, column and parent index.
When reimplementing this function in a subclass, call createIndex() to generate model indexes that other components can use to refer to items in your model.
See also
createIndex()
Implements QAbstractItemModel.
Definition at line 1131 of file qprintdialog_unix.cpp.
Referenced by QPrintPropertiesDialog::selectPrinter().
 {
     QOptionTreeItem* itm;
     if (!parent.isValid())
         itm = rootItem;
     else
         itm = reinterpret_cast<QOptionTreeItem*>(parent.internalPointer());
     return createIndex(row, column, itm->childItems.at(row));
 }
parent()
QModelIndex QPPDOptionsModel::parent (const QModelIndex & index) const virtual
Returns the parent of the model item with the given index.
Warning
This function is not part of the public interface.
If the item has no parent, an invalid QModelIndex is returned.
A common convention used in models that expose tree data structures is that only items in the first column have children. For that case, when reimplementing this function in a subclass the column of the returned QModelIndex would be 0.
When reimplementing this function in a subclass, be careful to avoid calling QModelIndex member functions, such as QModelIndex::parent(), since indexes belonging to your model will simply call your implementation, leading to infinite recursion.
See also
createIndex()
Implements QAbstractItemModel.
Definition at line 1143 of file qprintdialog_unix.cpp.
 {
     if (!index.isValid())
         return QModelIndex();
     QOptionTreeItem* itm = reinterpret_cast<QOptionTreeItem*>(index.internalPointer());
     if (itm->parentItem && itm->parentItem != rootItem)
         return createIndex(itm->parentItem->index, 0, itm->parentItem);
     else
         return QModelIndex();
 }
parseChoices()
void QPPDOptionsModel::parseChoices (QOptionTreeItem * parent)
Definition at line 1216 of file qprintdialog_unix.cpp.
Referenced by parseOptions().
 {
     const ppd_option_t* option = reinterpret_cast<const ppd_option_t*>(parent->ptr);
     bool marked = false;
     for (int i = 0; i < option->num_choices; ++i) {
         QOptionTreeItem* choice = new QOptionTreeItem(QOptionTreeItem::Choice, i, &option->choices[i], option->choices[i].text, parent);
         if (static_cast<int>(option->choices[i].marked) == 1) {
             parent->selected = i;
             parent->selDescription = option->choices[i].text;
             marked = true;
         } else if (!marked && qstrcmp(option->choices[i].choice, option->defchoice) == 0) {
             parent->selected = i;
             parent->selDescription = option->choices[i].text;
         }
         parent->childItems.append(choice);
     }
 }
parseGroups()
void QPPDOptionsModel::parseGroups (QOptionTreeItem * parent)
Definition at line 1177 of file qprintdialog_unix.cpp.
Referenced by parseItems().
 {
     if (parent->type == QOptionTreeItem::Root) {
         const ppd_file_t* ppdFile = reinterpret_cast<const ppd_file_t*>(parent->ptr);
         if (ppdFile) {
             for (int i = 0; i < ppdFile->num_groups; ++i) {
                 QOptionTreeItem* group = new QOptionTreeItem(QOptionTreeItem::Group, i, &ppdFile->groups[i], ppdFile->groups[i].text, parent);
                 parent->childItems.append(group);
                 parseGroups(group); // parse possible subgroups
                 parseOptions(group); // parse options
             }
         }
     } else if (parent->type == QOptionTreeItem::Group) {
         const ppd_group_t* group = reinterpret_cast<const ppd_group_t*>(parent->ptr);
         if (group) {
             for (int i = 0; i < group->num_subgroups; ++i) {
                 QOptionTreeItem* subgroup = new QOptionTreeItem(QOptionTreeItem::Group, i, &group->subgroups[i], group->subgroups[i].text, parent);
                 parent->childItems.append(subgroup);
                 parseGroups(subgroup); // parse possible subgroups
                 parseOptions(subgroup); // parse options
             }
         }
     }
 }
parseItems()
void QPPDOptionsModel::parseItems ()
Definition at line 1167 of file qprintdialog_unix.cpp.
Referenced by QPPDOptionsModel(), and QPrintPropertiesDialog::selectPrinter().
 {
     emit layoutAboutToBeChanged();
     ppd = cups->currentPPD();
     delete rootItem;
     rootItem = new QOptionTreeItem(QOptionTreeItem::Root, 0, ppd, "Root Item", 0);
     parseGroups(rootItem);
     emit layoutChanged();
 }
parseOptions()
void QPPDOptionsModel::parseOptions (QOptionTreeItem * parent)
Definition at line 1206 of file qprintdialog_unix.cpp.
Referenced by parseGroups().
 {
     const ppd_group_t* group = reinterpret_cast<const ppd_group_t*>(parent->ptr);
     for (int i = 0; i < group->num_options; ++i) {
         QOptionTreeItem* opt = new QOptionTreeItem(QOptionTreeItem::Option, i, &group->options[i], group->options[i].text, parent);
         parent->childItems.append(opt);
         parseChoices(opt);
     }
 }
rowCount()
int QPPDOptionsModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of rows under the given parent.
When the parent is valid it means that rowCount is returning the number of children of parent.
Note
When implementing a table based model, rowCount() should return 0 when the parent is valid.
See also
columnCount()
Implements QAbstractItemModel.
Definition at line 1080 of file qprintdialog_unix.cpp.
Referenced by QPrintPropertiesDialog::selectPrinter().
 {
     QOptionTreeItem* itm;
     if (!parent.isValid())
         itm = rootItem;
     else
         itm = reinterpret_cast<QOptionTreeItem*>(parent.internalPointer());
     if (itm->type == QOptionTreeItem::Option)
         return 0;
     return itm->childItems.count();
 }
Friends and Related Functions
QPPDOptionsEditor
friend class QPPDOptionsEditor friend
Definition at line 216 of file qprintdialog_unix.cpp.
Properties
cups
QCUPSSupport* QPPDOptionsModel::cups
Definition at line 230 of file qprintdialog_unix.cpp.
Referenced by data(), parseItems(), QPPDOptionsEditor::setModelData(), and QPrintPropertiesDialog::setupPrinter().
ppd
const ppd_file_t* QPPDOptionsModel::ppd
Definition at line 231 of file qprintdialog_unix.cpp.
Referenced by parseItems().
rootItem
QOptionTreeItem* QPPDOptionsModel::rootItem
Definition at line 229 of file qprintdialog_unix.cpp.
Referenced by data(), index(), parent(), parseItems(), rowCount(), and QPrintPropertiesDialog::setupPrinter().
The documentation for this class was generated from the following file:
/src/gui/dialogs/qprintdialog_unix.cpp