Qt 4.8: QPixmapColorizeFilter Class Reference
QPixmapColorizeFilter Class Reference
The QPixmapColorizeFilter class provides colorizing filtering for pixmaps.
#include <qpixmapfilter_p.h>
Public Functions
QColor color () const
Gets the color of the colorize filter.
void draw (QPainter *painter, const QPointF &dest, const QPixmap &src, const QRectF &srcRect=QRectF()) const
QPixmapColorizeFilter (QObject *parent=0)
Constructs an pixmap colorize filter.
void setColor (const QColor &color)
Sets the color of the colorize filter to the color specified.
void setStrength (qreal strength)
Sets the strength of the colorize filter to strength.
qreal strength () const
Gets the strength of the colorize filter, 1.0 means full colorized while 0.0 equals to no filtering at all.
Public Functions inherited from QPixmapFilter
virtual QRectF boundingRectFor (const QRectF &rect) const
Returns the bounding rectangle that is affected by the pixmap filter if the filter is applied to the specified rect.
FilterType type () const
Returns the type of the filter.
virtual ~QPixmapFilter ()=0
Destroys the pixmap filter.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Types inherited from QPixmapFilter
enum FilterType {
ConvolutionFilter, ColorizeFilter, DropShadowFilter, BlurFilter,
UserFilter = 1024
}
This enum describes the types of filter that can be applied to pixmaps.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QPixmapFilter
QPixmapFilter (QPixmapFilterPrivate &d, FilterType type, QObject *parent)
QPixmapFilter (FilterType type, QObject *parent)
Constructs a default QPixmapFilter with the given type.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPixmapColorizeFilter class provides colorizing filtering for pixmaps.
Since
4.5
A colorize filter gives the pixmap a tint of its color(). The filter first grayscales the pixmap and then converts those to colorized values using QPainter::CompositionMode_Screen with the chosen color. The alpha-channel is not changed.
Example:
QPixmapColorizeFilter *myFilter = new QPixmapColorFilter;
myFilter->setColor(QColor(128, 0, 0));
myFilter->draw(painter, QPoint(0, 0), originalPixmap);
See also
QPainter::CompositionMode
Warning
This function is not part of the public interface.
Definition at line 149 of file qpixmapfilter_p.h.
Constructors and Destructors
QPixmapColorizeFilter()
QPixmapColorizeFilter::QPixmapColorizeFilter (QObject * parent = 0)
Constructs an pixmap colorize filter.
Default color value for colorizing is QColor(0, 0, 192).
Warning
This function is not part of the public interface.
Definition at line 1054 of file qpixmapfilter.cpp.
     : QPixmapFilter(*new QPixmapColorizeFilterPrivate, ColorizeFilter, parent)
 {
     Q_D(QPixmapColorizeFilter);
     d->color = QColor(0, 0, 192);
     d->strength = qreal(1);
     d->opaque = true;
     d->alphaBlend = false;
 }
Functions
color()
QColor QPixmapColorizeFilter::color () const
Gets the color of the colorize filter.
Warning
This function is not part of the public interface.
Definition at line 1069 of file qpixmapfilter.cpp.
Referenced by QVGPixmapColorizeFilter::draw(), and setColor().
 {
     Q_D(const QPixmapColorizeFilter);
     return d->color;
 }
draw()
void QPixmapColorizeFilter::draw (QPainter * painter, const QPointF & dest, const QPixmap & src, const QRectF & srcRect = QRectF()) const virtual
Warning
This function is not part of the public interface.
Implements QPixmapFilter.
Reimplemented in QGLPixmapFilter< QPixmapColorizeFilter >, and QVGPixmapColorizeFilter.
Definition at line 1114 of file qpixmapfilter.cpp.
Referenced by QVGPixmapColorizeFilter::draw(), and draw().
 {
     Q_D(const QPixmapColorizeFilter);
     if (src.isNull())
         return;
     QPixmapFilter *filter = painter->paintEngine() && painter->paintEngine()->isExtended() ?
         static_cast<QPaintEngineEx *>(painter->paintEngine())->pixmapFilter(type(), this) : 0;
     QPixmapColorizeFilter *colorizeFilter = static_cast<QPixmapColorizeFilter*>(filter);
     if (colorizeFilter) {
         colorizeFilter->setColor(d->color);
         colorizeFilter->setStrength(d->strength);
         colorizeFilter->draw(painter, dest, src, srcRect);
         return;
     }
     // falling back to raster implementation
     if (!d->opaque) {
         painter->drawPixmap(dest, src, srcRect);
         return;
     }
     QImage srcImage;
     QImage destImage;
     if (srcRect.isNull()) {
         srcImage = src.toImage();
         srcImage = srcImage.convertToFormat(srcImage.hasAlphaChannel() ? QImage::Format_ARGB32_Premultiplied : QImage::Format_RGB32);
         destImage = QImage(srcImage.size(), srcImage.format());
     } else {
         QRect rect = srcRect.toAlignedRect().intersected(src.rect());
         srcImage = src.copy(rect).toImage();
         srcImage = srcImage.convertToFormat(srcImage.hasAlphaChannel() ? QImage::Format_ARGB32_Premultiplied : QImage::Format_RGB32);
         destImage = QImage(rect.size(), srcImage.format());
     }
     // do colorizing
     QPainter destPainter(&destImage);
     grayscale(srcImage, destImage, srcImage.rect());
     destPainter.setCompositionMode(QPainter::CompositionMode_Screen);
     destPainter.fillRect(srcImage.rect(), d->color);
     destPainter.end();
     if (d->alphaBlend) {
         // alpha blending srcImage and destImage
         QImage buffer = srcImage;
         QPainter bufPainter(&buffer);
         bufPainter.setOpacity(d->strength);
         bufPainter.drawImage(0, 0, destImage);
         bufPainter.end();
         destImage = buffer;
     }
     if (srcImage.hasAlphaChannel())
         destImage.setAlphaChannel(srcImage.alphaChannel());
     painter->drawImage(dest, destImage);
 }
setColor()
void QPixmapColorizeFilter::setColor (const QColor & color)
Sets the color of the colorize filter to the color specified.
Warning
This function is not part of the public interface.
Definition at line 1080 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapColorizeFilter);
     d->color = color;
 }
setStrength()
void QPixmapColorizeFilter::setStrength (qreal strength)
Sets the strength of the colorize filter to strength.
Warning
This function is not part of the public interface.
Definition at line 1103 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapColorizeFilter);
     d->strength = qBound(qreal(0), strength, qreal(1));
     d->opaque = !qFuzzyIsNull(d->strength);
     d->alphaBlend = !qFuzzyIsNull(d->strength - 1);
 }
strength()
qreal QPixmapColorizeFilter::strength () const
Gets the strength of the colorize filter, 1.0 means full colorized while 0.0 equals to no filtering at all.
Warning
This function is not part of the public interface.
Definition at line 1092 of file qpixmapfilter.cpp.
Referenced by QVGPixmapColorizeFilter::draw().
 {
     Q_D(const QPixmapColorizeFilter);
     return d->strength;
 }
The documentation for this class was generated from the following files:
/src/gui/image/qpixmapfilter_p.h
/src/gui/image/qpixmapfilter.cpp