Qt 4.8: QAbstractTextDocumentLayout Class Reference
QAbstractTextDocumentLayout Class Reference abstract
The QAbstractTextDocumentLayout class is an abstract base class used to implement custom layouts for QTextDocuments.
#include <qabstracttextdocumentlayout.h>
Classes
class PaintContext
The QAbstractTextDocumentLayout::PaintContext class is a convenience class defining the parameters used when painting a document's layout.
class Selection
The QAbstractTextDocumentLayout::Selection class is a convenience class defining the parameters of a selection.
Signals
void documentSizeChanged (const QSizeF &newSize)
This signal is emitted when the size of the document layout changes to newSize.
void pageCountChanged (int newPages)
This signal is emitted when the number of pages in the layout changes; newPages is the updated page count.
void update (const QRectF &=QRectF(0., 0., 1000000000., 1000000000.))
This signal is emitted when the rectangle rect has been updated.
void updateBlock (const QTextBlock &block)
This signal is emitted when the specified block has been updated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QString anchorAt (const QPointF &pos) const
Returns the reference of the anchor the given position, or an empty string if no anchor exists at that point.
virtual QRectF blockBoundingRect (const QTextBlock &block) const =0
Returns the bounding rectangle of block.
QTextDocument * document () const
Returns the text document that this layout is operating on.
virtual QSizeF documentSize () const =0
Returns the total size of the document's layout.
virtual void draw (QPainter *painter, const PaintContext &context)=0
Draws the layout with the given painter using the given context.
virtual QRectF frameBoundingRect (QTextFrame *frame) const =0
Returns the bounding rectangle of frame.
QTextObjectInterface * handlerForObject (int objectType) const
Returns a handler for objects of the given objectType.
virtual int hitTest (const QPointF &point, Qt::HitTestAccuracy accuracy) const =0
Returns the cursor postion for the given point with the specified accuracy.
virtual int pageCount () const =0
Returns the number of pages contained in the layout.
QPaintDevice * paintDevice () const
Returns the paint device used to render the document's layout.
QAbstractTextDocumentLayout (QTextDocument *doc)
Creates a new text document layout for the given document.
void registerHandler (int objectType, QObject *component)
Registers the given component as a handler for items of the given objectType.
void setPaintDevice (QPaintDevice *device)
Sets the paint device used for rendering the document's layout to the given device.
~QAbstractTextDocumentLayout ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void documentChanged (int from, int charsRemoved, int charsAdded)=0
This function is called whenever the contents of the document change.
virtual void drawInlineObject (QPainter *painter, const QRectF &rect, QTextInlineObject object, int posInDocument, const QTextFormat &format)
This function is called to draw the inline object, object, with the given painter within the rectangle specified by rect using the specified text format.
QTextCharFormat format (int pos)
Returns the character format that is applicable at the given position.
int formatIndex (int pos)
Returns the index of the format at position pos.
virtual void positionInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat &format)
Lays out the inline object item using the given text format.
QAbstractTextDocumentLayout (QAbstractTextDocumentLayoutPrivate &, QTextDocument *)
virtual void resizeInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat &format)
Sets the size of the inline object item corresponding to the text format.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QTextControl
class QTextDocument
class QTextDocumentPrivate
class QTextEngine
class QTextLayout
class QTextLine
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractTextDocumentLayout class is an abstract base class used to implement custom layouts for QTextDocuments.
Note
This class or function is reentrant.
The standard layout provided by Qt can handle simple word processing including inline images, lists and tables.
Some applications, e.g., a word processor or a DTP application might need more features than the ones provided by Qt's layout engine, in which case you can subclass QAbstractTextDocumentLayout to provide custom layout behavior for your text documents.
An instance of the QAbstractTextDocumentLayout subclass can be installed on a QTextDocument object with the QTextDocument::setDocumentLayout() function.
You can insert custom objects into a QTextDocument; see the QTextObjectInterface class description for details.
See also
QTextObjectInterface
Definition at line 62 of file qabstracttextdocumentlayout.h.
Constructors and Destructors
QAbstractTextDocumentLayout() [1/2]
QAbstractTextDocumentLayout::QAbstractTextDocumentLayout (QTextDocument * doc) explicit
Creates a new text document layout for the given document.
Definition at line 442 of file qabstracttextdocumentlayout.cpp.
     : QObject(*new QAbstractTextDocumentLayoutPrivate, document)
 {
     Q_D(QAbstractTextDocumentLayout);
     d->setDocument(document);
 }
~QAbstractTextDocumentLayout()
QAbstractTextDocumentLayout::~QAbstractTextDocumentLayout ()
Warning
This function is not part of the public interface.
Definition at line 462 of file qabstracttextdocumentlayout.cpp.
 {
 }
QAbstractTextDocumentLayout() [2/2]
QAbstractTextDocumentLayout::QAbstractTextDocumentLayout (QAbstractTextDocumentLayoutPrivate & p, QTextDocument * document) protected
Warning
This function is not part of the public interface.
Definition at line 452 of file qabstracttextdocumentlayout.cpp.
     :QObject(p, document)
 {
     Q_D(QAbstractTextDocumentLayout);
     d->setDocument(document);
 }
Functions
anchorAt()
QString QAbstractTextDocumentLayout::anchorAt (const QPointF & pos) const
Returns the reference of the anchor the given position, or an empty string if no anchor exists at that point.
Definition at line 639 of file qabstracttextdocumentlayout.cpp.
Referenced by QWhatsThat::mouseMoveEvent(), QWhatsThat::mousePressEvent(), and QWhatsThat::mouseReleaseEvent().
 {
     int cursorPos = hitTest(pos, Qt::ExactHit);
     if (cursorPos == -1)
         return QString();
     QTextDocumentPrivate *pieceTable = qobject_cast<const QTextDocument *>(parent())->docHandle();
     QTextDocumentPrivate::FragmentIterator it = pieceTable->find(cursorPos);
     QTextCharFormat fmt = pieceTable->formatCollection()->charFormat(it->format);
     return fmt.anchorHref();
 }
blockBoundingRect()
QRectF QAbstractTextDocumentLayout::blockBoundingRect (const QTextBlock & block) const pure virtual
Returns the bounding rectangle of block.
Implemented in QPlainTextDocumentLayout, and QTextDocumentLayout.
Referenced by QTextCursorPrivate::blockLayout(), and QAccessibleTextEdit::rect().
document()
QTextDocument * QAbstractTextDocumentLayout::document () const
Returns the text document that this layout is operating on.
Definition at line 624 of file qabstracttextdocumentlayout.cpp.
Referenced by QPlainTextDocumentLayout::blockBoundingRect(), QTextEngine::docLayout(), QTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::documentSize(), drawInlineObject(), QPlainTextDocumentLayout::layoutBlock(), QPlainTextDocumentLayout::requestUpdate(), and resizeInlineObject().
 {
     Q_D(const QAbstractTextDocumentLayout);
     return d->document;
 }
documentChanged()
void QAbstractTextDocumentLayout::documentChanged (int position, int charsRemoved, int charsAdded) protected pure virtual
This function is called whenever the contents of the document change.
A change occurs when text is inserted, removed, or a combination of these two. The change is specified by position, charsRemoved, and charsAdded corresponding to the starting character position of the change, the number of characters removed from the document, and the number of characters added.
For example, when inserting the text "Hello" into an empty document, charsRemoved would be 0 and charsAdded would be 5 (the length of the string).
Replacing text is a combination of removing and inserting. For example, if the text "Hello" gets replaced by "Hi", charsRemoved would be 5 and charsAdded would be 2.
For subclasses of QAbstractTextDocumentLayout, this is the central function where a large portion of the work to lay out and position document contents is done.
For example, in a subclass that only arranges blocks of text, an implementation of this function would have to do the following:
Determine the list of changed QTextBlock(s) using the parameters provided.
Each QTextBlock object's corresponding QTextLayout object needs to be processed. You can access the QTextBlock's layout using the QTextBlock::layout() function. This processing should take the document's page size into consideration.
If the total number of pages changed, the pageCountChanged() signal should be emitted.
If the total size changed, the documentSizeChanged() signal should be emitted.
The update() signal should be emitted to schedule a repaint of areas in the layout that require repainting.
See also
QTextLayout
Implemented in QPlainTextDocumentLayout, and QTextDocumentLayout.
Referenced by QTextDocumentPrivate::clear(), QTextDocumentPrivate::finishEdit(), and QTextDocumentPrivate::setLayout().
documentSize()
QSizeF QAbstractTextDocumentLayout::documentSize () const pure virtual
Returns the total size of the document's layout.
This information can be used by display widgets to update their scroll bars correctly.
See also
documentSizeChanged(), QTextDocument::pageSize
Implemented in QPlainTextDocumentLayout, and QTextDocumentLayout.
Referenced by QTextDocument::adjustSize(), documentSize(), QPlainTextEdit::paintEvent(), and QTextEditPrivate::relayoutDocument().
documentSizeChanged
void QAbstractTextDocumentLayout::documentSizeChanged (const QSizeF & newSize) signal
This signal is emitted when the size of the document layout changes to newSize.
Subclasses of QAbstractTextDocumentLayout should emit this signal when the document's entire layout size changes. This signal is useful for widgets that display text documents since it enables them to update their scroll bars correctly.
See also
documentSize()
Referenced by QTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::layoutBlock(), and QTextDocumentLayout::timerEvent().
draw()
void QAbstractTextDocumentLayout::draw (QPainter * painter, const PaintContext & context) pure virtual
Draws the layout with the given painter using the given context.
Implemented in QPlainTextDocumentLayout, and QTextDocumentLayout.
Referenced by QTextDocument::drawContents(), QLabel::paintEvent(), QWhatsThat::paintEvent(), and QStaticTextPrivate::paintText().
drawInlineObject()
void QAbstractTextDocumentLayout::drawInlineObject (QPainter * painter, const QRectF & rect, QTextInlineObject object, int posInDocument, const QTextFormat & format) protected virtual
This function is called to draw the inline object, object, with the given painter within the rectangle specified by rect using the specified text format.
posInDocument specifies the position of the object within the document.
The default implementation calls drawObject() on the object handlers. This function is called only within Qt. Subclasses can reimplement this function to customize the drawing of inline objects.
See also
draw()
Reimplemented in QTextDocumentLayout.
Definition at line 565 of file qabstracttextdocumentlayout.cpp.
Referenced by QTextLine::draw(), and QTextDocumentLayout::drawInlineObject().
 {
     Q_UNUSED(item);
     Q_D(QAbstractTextDocumentLayout);
     QTextCharFormat f = format.toCharFormat();
     Q_ASSERT(f.isValid());
     QTextObjectHandler handler = d->handlers.value(f.objectType());
     if (!handler.component)
         return;
     handler.iface->drawObject(p, rect, document(), posInDocument, format);
 }
format()
QTextCharFormat QAbstractTextDocumentLayout::format (int pos) protected
Returns the character format that is applicable at the given position.
Definition at line 612 of file qabstracttextdocumentlayout.cpp.
 {
     QTextDocumentPrivate *pieceTable = qobject_cast<QTextDocument *>(parent())->docHandle();
     int idx = pieceTable->find(pos).value()->format;
     return pieceTable->formatCollection()->charFormat(idx);
 }
formatIndex()
int QAbstractTextDocumentLayout::formatIndex (int pos) protected
Returns the index of the format at position pos.
Warning
This function is not part of the public interface.
Definition at line 598 of file qabstracttextdocumentlayout.cpp.
 {
     QTextDocumentPrivate *pieceTable = qobject_cast<QTextDocument *>(parent())->docHandle();
     return pieceTable->find(pos).value()->format;
 }
frameBoundingRect()
QRectF QAbstractTextDocumentLayout::frameBoundingRect (QTextFrame * frame) const pure virtual
Returns the bounding rectangle of frame.
Implemented in QPlainTextDocumentLayout, and QTextDocumentLayout.
Referenced by boundingRectOfFloatsInSelection().
handlerForObject()
QTextObjectInterface * QAbstractTextDocumentLayout::handlerForObject (int objectType) const
Returns a handler for objects of the given objectType.
Definition at line 494 of file qabstracttextdocumentlayout.cpp.
 {
     Q_D(const QAbstractTextDocumentLayout);
     QTextObjectHandler handler = d->handlers.value(objectType);
     if (!handler.component)
         return 0;
     return handler.iface;
 }
hitTest()
int QAbstractTextDocumentLayout::hitTest (const QPointF & point, Qt::HitTestAccuracy accuracy) const pure virtual
Returns the cursor postion for the given point with the specified accuracy.
Returns -1 if no valid cursor position was found.
Implemented in QPlainTextDocumentLayout, and QTextDocumentLayout.
Referenced by anchorAt(), and QAccessibleTextWidget::offsetAtPoint().
pageCount()
int QAbstractTextDocumentLayout::pageCount () const pure virtual
Returns the number of pages contained in the layout.
See also
pageCountChanged()
Implemented in QPlainTextDocumentLayout, and QTextDocumentLayout.
Referenced by QTextDocument::pageCount().
pageCountChanged
void QAbstractTextDocumentLayout::pageCountChanged (int newPages) signal
This signal is emitted when the number of pages in the layout changes; newPages is the updated page count.
Subclasses of QAbstractTextDocumentLayout should emit this signal when the number of pages in the layout has changed. Changes to the page count are caused by changes to the layout or the document content itself.
See also
pageCount()
Referenced by QTextDocumentLayout::timerEvent().
paintDevice()
QPaintDevice * QAbstractTextDocumentLayout::paintDevice () const
Returns the paint device used to render the document's layout.
See also
setPaintDevice()
Definition at line 683 of file qabstracttextdocumentlayout.cpp.
Referenced by QTextEngine::calculateTabWidth(), QTextEngine::font(), QTextEngine::fontEngine(), getImageSize(), getPixmapSize(), QTextDocumentLayoutPrivate::scaleToDevice(), and QScriptLine::setDefaultHeight().
 {
     Q_D(const QAbstractTextDocumentLayout);
     return d->paintDevice;
 }
positionInlineObject()
void QAbstractTextDocumentLayout::positionInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat & format) protected virtual
Lays out the inline object item using the given text format.
posInDocument specifies the position of the object within the document.
The default implementation does nothing. This function is called only within Qt. Subclasses can reimplement this function to customize the position of inline objects.
See also
drawInlineObject()
Reimplemented in QTextDocumentLayout.
Definition at line 543 of file qabstracttextdocumentlayout.cpp.
Referenced by QTextLine::layout_helper().
 {
     Q_UNUSED(item);
     Q_UNUSED(posInDocument);
     Q_UNUSED(format);
 }
registerHandler()
void QAbstractTextDocumentLayout::registerHandler (int objectType, QObject * component)
Registers the given component as a handler for items of the given objectType.
Note
registerHandler() has to be called once for each object type. This means that there is only one handler for multiple replacement characters of the same object type.
Definition at line 475 of file qabstracttextdocumentlayout.cpp.
Referenced by QTextDocumentLayout::QTextDocumentLayout().
 {
     Q_D(QAbstractTextDocumentLayout);
     QTextObjectInterface *iface = qobject_cast<QTextObjectInterface *>(component);
     if (!iface)
         return; // ### print error message on terminal?
     connect(component, SIGNAL(destroyed(QObject*)), this, SLOT(_q_handlerDestroyed(QObject*)));
     QTextObjectHandler h;
     h.iface = iface;
     h.component = component;
     d->handlers.insert(formatType, h);
 }
resizeInlineObject()
void QAbstractTextDocumentLayout::resizeInlineObject (QTextInlineObject item, int posInDocument, const QTextFormat & format) protected virtual
Sets the size of the inline object item corresponding to the text format.
posInDocument specifies the position of the object within the document.
The default implementation resizes the item to the size returned by the object handler's intrinsicSize() function. This function is called only within Qt. Subclasses can reimplement this function to customize the resizing of inline objects.
Reimplemented in QTextDocumentLayout.
Definition at line 516 of file qabstracttextdocumentlayout.cpp.
Referenced by QTextEngine::shape().
 {
     Q_D(QAbstractTextDocumentLayout);
     QTextCharFormat f = format.toCharFormat();
     Q_ASSERT(f.isValid());
     QTextObjectHandler handler = d->handlers.value(f.objectType());
     if (!handler.component)
         return;
     QSizeF s = handler.iface->intrinsicSize(document(), posInDocument, format);
     item.setWidth(s.width());
     item.setAscent(s.height() - 1);
     item.setDescent(0);
 }
setPaintDevice()
void QAbstractTextDocumentLayout::setPaintDevice (QPaintDevice * device)
Sets the paint device used for rendering the document's layout to the given device.
See also
paintDevice()
Definition at line 672 of file qabstracttextdocumentlayout.cpp.
Referenced by QTextEditPrivate::init(), and QPlainTextEditPrivate::init().
 {
     Q_D(QAbstractTextDocumentLayout);
     d->paintDevice = device;
 }
update
void QAbstractTextDocumentLayout::update (const QRectF & rect = QRectF(0., 0., 1000000000., 1000000000.)) signal
This signal is emitted when the rectangle rect has been updated.
Subclasses of QAbstractTextDocumentLayout should emit this signal when the layout of the contents change in order to repaint.
Referenced by QTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::documentChanged(), and QPlainTextDocumentLayout::requestUpdate().
updateBlock
void QAbstractTextDocumentLayout::updateBlock (const QTextBlock & block) signal
This signal is emitted when the specified block has been updated.
Since
4.4
Subclasses of QAbstractTextDocumentLayout should emit this signal when the layout of block has changed in order to repaint.
Referenced by QPlainTextDocumentLayout::documentChanged().
Friends and Related Functions
QTextControl
friend class QTextControl friend
Definition at line 125 of file qabstracttextdocumentlayout.h.
QTextDocument
friend class QTextDocument friend
Definition at line 126 of file qabstracttextdocumentlayout.h.
QTextDocumentPrivate
friend class QTextDocumentPrivate friend
Definition at line 127 of file qabstracttextdocumentlayout.h.
QTextEngine
friend class QTextEngine friend
Definition at line 128 of file qabstracttextdocumentlayout.h.
QTextLayout
friend class QTextLayout friend
Definition at line 129 of file qabstracttextdocumentlayout.h.
QTextLine
friend class QTextLine friend
Definition at line 130 of file qabstracttextdocumentlayout.h.
The documentation for this class was generated from the following files:
/src/gui/text/qabstracttextdocumentlayout.h
/src/gui/text/qabstracttextdocumentlayout.cpp