Qt 4.8: QDB2Result Class Reference
QDB2Result Class Reference
#include <qsql_db2.h>
Public Functions
bool exec ()
Executes the query, returning true if successful; otherwise returns false.
QVariant handle () const
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
bool prepare (const QString &query)
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
QDB2Result (const QDB2Driver *dr, const QDB2DriverPrivate *dp)
~QDB2Result ()
Public Functions inherited from QSqlResult
virtual ~QSqlResult ()
Destroys the object and frees any allocated resources.
Protected Functions
QVariant data (int field)
Returns the data for field index in the current row as a QVariant.
bool fetch (int i)
Positions the result to an arbitrary (zero-based) row index.
bool fetchFirst ()
Positions the result to the first record (row 0) in the result.
bool fetchLast ()
Positions the result to the last record (last row) in the result.
bool fetchNext ()
Positions the result to the next available record (row) in the result.
bool isNull (int i)
Returns true if the field at position index in the current row is null; otherwise returns false.
bool nextResult ()
int numRowsAffected ()
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
QSqlRecord record () const
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
bool reset (const QString &query)
Sets the result to use the SQL statement query for subsequent data retrieval.
int size ()
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
void virtual_hook (int id, void *data)
Protected Functions inherited from QSqlResult
void addBindValue (const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the next available position in the current record (row).
int at () const
Returns the current (zero-based) row position of the result.
BindingSyntax bindingSyntax () const
Returns the binding syntax used by prepared queries.
virtual void bindValue (int pos, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to position index in the current record (row).
virtual void bindValue (const QString &placeholder, const QVariant &val, QSql::ParamType type)
Binds the value val of parameter type paramType to the placeholder name in the current record (row).
QSql::ParamType bindValueType (const QString &placeholder) const
Returns the parameter type for the value bound with the given placeholder name.
QSql::ParamType bindValueType (int pos) const
Returns the parameter type for the value bound at position index.
QVariant boundValue (const QString &placeholder) const
Returns the value bound by the given placeholder name in the current record (row).
QVariant boundValue (int pos) const
Returns the value bound at position index in the current record (row).
int boundValueCount () const
Returns the number of bound values in the result.
QString boundValueName (int pos) const
Returns the name of the bound value at position index in the current record (row).
QVector< QVariant > & boundValues () const
Returns a vector of the result's bound values for the current record (row).
void clear ()
Clears the entire result set and releases any associated resources.
void detachFromResultSet ()
const QSqlDriver * driver () const
Returns the driver associated with the result.
bool execBatch (bool arrayBind=false)
Executes a prepared query in batch mode if the driver supports it, otherwise emulates a batch execution using bindValue() and exec().
QString executedQuery () const
Returns the query that was actually executed.
virtual bool fetchPrevious ()
Positions the result to the previous record (row) in the result.
bool hasOutValues () const
Returns true if at least one of the query's bound values is a QSql::Out or a QSql::InOut; otherwise returns false.
bool isActive () const
Returns true if the result has records to be retrieved; otherwise returns false.
bool isForwardOnly () const
Returns true if you can only scroll forward through the result set; otherwise returns false.
bool isSelect () const
Returns true if the current result is from a SELECT statement; otherwise returns false.
bool isValid () const
Returns true if the result is positioned on a valid record (that is, the result is not positioned before the first or after the last record); otherwise returns false.
QSqlError lastError () const
Returns the last error associated with the result.
virtual QVariant lastInsertId () const
Returns the object ID of the most recent inserted row if the database supports it.
QString lastQuery () const
Returns the current SQL query text, or an empty string if there isn't one.
bool nextResult ()
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
QSqlResult (const QSqlDriver *db)
Creates a QSqlResult using database driver db.
virtual bool savePrepare (const QString &sqlquery)
Prepares the given query, using the underlying database functionality where possible.
virtual void setActive (bool a)
This function is provided for derived classes to set the internal active state to active.
virtual void setAt (int at)
This function is provided for derived classes to set the internal (zero-based) row position to index.
virtual void setForwardOnly (bool forward)
Sets forward only mode to forward.
virtual void setLastError (const QSqlError &e)
This function is provided for derived classes to set the last error to error.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy policy)
virtual void setQuery (const QString &query)
Sets the current query for the result to query.
virtual void setSelect (bool s)
This function is provided for derived classes to indicate whether or not the current statement is a SQL SELECT statement.
Properties
QDB2ResultPrivate * d
Additional Inherited Members
Protected Types inherited from QSqlResult
enum BindingSyntax { PositionalBinding, NamedBinding }
This enum type specifies the different syntaxes for specifying placeholders in prepared queries.
enum VirtualHookOperation { BatchOperation, DetachFromResultSet, SetNumericalPrecision, NextResult }
Detailed Description
Definition at line 62 of file qsql_db2.h.
Constructors and Destructors
QDB2Result()
QDB2Result::QDB2Result (const QDB2Driver * dr, const QDB2DriverPrivate * dp)
Definition at line 520 of file qsql_db2.cpp.
     : QSqlResult(dr)
 {
     d = new QDB2ResultPrivate(dp);
 }
~QDB2Result()
QDB2Result::~QDB2Result ()
Definition at line 526 of file qsql_db2.cpp.
 {
     if (d->hStmt) {
         SQLRETURN r = SQLFreeHandle(SQL_HANDLE_STMT, d->hStmt);
         if (r != SQL_SUCCESS)
             qSqlWarning(QLatin1String("QDB2Driver: Unable to free statement handle ")
                         + QString::number(r), d);
     }
     delete d;
 }
Functions
data()
QVariant QDB2Result::data (int index) protected virtual
Returns the data for field index in the current row as a QVariant.
This function is only called if the result is in an active state and is positioned on a valid record and index is non-negative. Derived classes must reimplement this function and return the value of field index, or QVariant() if it cannot be determined.
Implements QSqlResult.
Definition at line 951 of file qsql_db2.cpp.
Referenced by exec(), isNull(), and virtual_hook().
 {
     if (field >= d->recInf.count()) {
         qWarning("QDB2Result::data: column %d out of range", field);
         return QVariant();
     }
     SQLRETURN r = 0;
     SQLINTEGER lengthIndicator = 0;
     bool isNull = false;
     const QSqlField info = d->recInf.field(field);
     if (!info.isValid() || field >= d->valueCache.size())
         return QVariant();
     if (d->valueCache[field])
         return *d->valueCache[field];
     QVariant* v = 0;
     switch (info.type()) {
         case QVariant::LongLong:
             v = new QVariant((qint64) qGetBigIntData(d->hStmt, field, isNull));
             break;
         case QVariant::Int:
             v = new QVariant(qGetIntData(d->hStmt, field, isNull));
             break;
         case QVariant::Date: {
             DATE_STRUCT dbuf;
             r = SQLGetData(d->hStmt,
                             field + 1,
                             SQL_C_DATE,
                             (SQLPOINTER) &dbuf,
                             0,
                             &lengthIndicator);
             if ((r == SQL_SUCCESS || r == SQL_SUCCESS_WITH_INFO) && (lengthIndicator != SQL_NULL_DATA)) {
                 v = new QVariant(QDate(dbuf.year, dbuf.month, dbuf.day));
             } else {
                 v = new QVariant(QDate());
                 isNull = true;
             }
             break; }
         case QVariant::Time: {
             TIME_STRUCT tbuf;
             r = SQLGetData(d->hStmt,
                             field + 1,
                             SQL_C_TIME,
                             (SQLPOINTER) &tbuf,
                             0,
                             &lengthIndicator);
             if ((r == SQL_SUCCESS || r == SQL_SUCCESS_WITH_INFO) && (lengthIndicator != SQL_NULL_DATA)) {
                 v = new QVariant(QTime(tbuf.hour, tbuf.minute, tbuf.second));
             } else {
                 v = new QVariant(QTime());
                 isNull = true;
             }
             break; }
         case QVariant::DateTime: {
             TIMESTAMP_STRUCT dtbuf;
             r = SQLGetData(d->hStmt,
                             field + 1,
                             SQL_C_TIMESTAMP,
                             (SQLPOINTER) &dtbuf,
                             0,
                             &lengthIndicator);
             if ((r == SQL_SUCCESS || r == SQL_SUCCESS_WITH_INFO) && (lengthIndicator != SQL_NULL_DATA)) {
                 v = new QVariant(QDateTime(QDate(dtbuf.year, dtbuf.month, dtbuf.day),
                                              QTime(dtbuf.hour, dtbuf.minute, dtbuf.second, dtbuf.fraction / 1000000)));
             } else {
                 v = new QVariant(QDateTime());
                 isNull = true;
             }
             break; }
         case QVariant::ByteArray:
             v = new QVariant(qGetBinaryData(d->hStmt, field, lengthIndicator, isNull));
             break;
         case QVariant::Double:
             {
             switch(numericalPrecisionPolicy()) {
                 case QSql::LowPrecisionInt32:
                     v = new QVariant(qGetIntData(d->hStmt, field, isNull));
                     break;
                 case QSql::LowPrecisionInt64:
                     v = new QVariant((qint64) qGetBigIntData(d->hStmt, field, isNull));
                     break;
                 case QSql::LowPrecisionDouble:
                     v = new QVariant(qGetDoubleData(d->hStmt, field, isNull));
                     break;
                 case QSql::HighPrecision:
                 default:
                     // length + 1 for the comma
                     v = new QVariant(qGetStringData(d->hStmt, field, info.length() + 1, isNull));
                     break;
             }
             break;
             }
         case QVariant::String:
         default:
             v = new QVariant(qGetStringData(d->hStmt, field, info.length(), isNull));
             break;
     }
     if (isNull)
         *v = QVariant(info.type());
     d->valueCache[field] = v;
     return *v;
 }
exec()
bool QDB2Result::exec () virtual
Executes the query, returning true if successful; otherwise returns false.
See also
prepare()
Reimplemented from QSqlResult.
Definition at line 597 of file qsql_db2.cpp.
 {
     QList<QByteArray> tmpStorage; // holds temporary ptrs
     QVarLengthArray<SQLINTEGER, 32> indicators(boundValues().count());
     memset(indicators.data(), 0, indicators.size() * sizeof(SQLINTEGER));
     setActive(false);
     setAt(QSql::BeforeFirstRow);
     SQLRETURN r;
     d->recInf.clear();
     d->emptyValueCache();
     if (!qMakeStatement(d, isForwardOnly(), false))
         return false;
     QVector<QVariant> &values = boundValues();
     int i;
     for (i = 0; i < values.count(); ++i) {
         // bind parameters - only positional binding allowed
         SQLINTEGER *ind = &indicators[i];
         if (values.at(i).isNull())
             *ind = SQL_NULL_DATA;
         if (bindValueType(i) & QSql::Out)
             values[i].detach();
         switch (values.at(i).type()) {
             case QVariant::Date: {
                 QByteArray ba;
                 ba.resize(sizeof(DATE_STRUCT));
                 DATE_STRUCT *dt = (DATE_STRUCT *)ba.constData();
                 QDate qdt = values.at(i).toDate();
                 dt->year = qdt.year();
                 dt->month = qdt.month();
                 dt->day = qdt.day();
                 r = SQLBindParameter(d->hStmt,
                                      i + 1,
                                      qParamType[(QFlag)(bindValueType(i)) & 3],
                                      SQL_C_DATE,
                                      SQL_DATE,
                                      0,
                                      0,
                                      (void *) dt,
                                      0,
                                      *ind == SQL_NULL_DATA ? ind : NULL);
                 tmpStorage.append(ba);
                 break; }
             case QVariant::Time: {
                 QByteArray ba;
                 ba.resize(sizeof(TIME_STRUCT));
                 TIME_STRUCT *dt = (TIME_STRUCT *)ba.constData();
                 QTime qdt = values.at(i).toTime();
                 dt->hour = qdt.hour();
                 dt->minute = qdt.minute();
                 dt->second = qdt.second();
                 r = SQLBindParameter(d->hStmt,
                                       i + 1,
                                       qParamType[(QFlag)(bindValueType(i)) & 3],
                                       SQL_C_TIME,
                                       SQL_TIME,
                                       0,
                                       0,
                                       (void *) dt,
                                       0,
                                       *ind == SQL_NULL_DATA ? ind : NULL);
                 tmpStorage.append(ba);
                 break; }
             case QVariant::DateTime: {
                 QByteArray ba;
                 ba.resize(sizeof(TIMESTAMP_STRUCT));
                 TIMESTAMP_STRUCT * dt = (TIMESTAMP_STRUCT *)ba.constData();
                 QDateTime qdt = values.at(i).toDateTime();
                 dt->year = qdt.date().year();
                 dt->month = qdt.date().month();
                 dt->day = qdt.date().day();
                 dt->hour = qdt.time().hour();
                 dt->minute = qdt.time().minute();
                 dt->second = qdt.time().second();
                 dt->fraction = qdt.time().msec() * 1000000;
                 r = SQLBindParameter(d->hStmt,
                                       i + 1,
                                       qParamType[(QFlag)(bindValueType(i)) & 3],
                                       SQL_C_TIMESTAMP,
                                       SQL_TIMESTAMP,
                                       0,
                                       0,
                                       (void *) dt,
                                       0,
                                       *ind == SQL_NULL_DATA ? ind : NULL);
                 tmpStorage.append(ba);
                 break; }
             case QVariant::Int:
                 r = SQLBindParameter(d->hStmt,
                                       i + 1,
                                       qParamType[(QFlag)(bindValueType(i)) & 3],
                                       SQL_C_SLONG,
                                       SQL_INTEGER,
                                       0,
                                       0,
                                       (void *)values.at(i).constData(),
                                       0,
                                       *ind == SQL_NULL_DATA ? ind : NULL);
                 break;
             case QVariant::Double:
                 r = SQLBindParameter(d->hStmt,
                                       i + 1,
                                       qParamType[(QFlag)(bindValueType(i)) & 3],
                                       SQL_C_DOUBLE,
                                       SQL_DOUBLE,
                                       0,
                                       0,
                                       (void *)values.at(i).constData(),
                                       0,
                                       *ind == SQL_NULL_DATA ? ind : NULL);
                 break;
             case QVariant::ByteArray: {
                 int len = values.at(i).toByteArray().size();
                 if (*ind != SQL_NULL_DATA)
                     *ind = len;
                 r = SQLBindParameter(d->hStmt,
                                       i + 1,
                                       qParamType[(QFlag)(bindValueType(i)) & 3],
                                       SQL_C_BINARY,
                                       SQL_LONGVARBINARY,
                                       len,
                                       0,
                                       (void *)values.at(i).toByteArray().constData(),
                                       len,
                                       ind);
                 break; }
             case QVariant::String:
             {
                 QString str(values.at(i).toString());
                 if (*ind != SQL_NULL_DATA)
                     *ind = str.length() * sizeof(QChar);
                 if (bindValueType(i) & QSql::Out) {
                     QByteArray ba((char*)str.utf16(), str.capacity() * sizeof(QChar));
                     r = SQLBindParameter(d->hStmt,
                                         i + 1,
                                         qParamType[(QFlag)(bindValueType(i)) & 3],
                                         SQL_C_WCHAR,
                                         SQL_WVARCHAR,
                                         str.length(),
                                         0,
                                         (void *)ba.constData(),
                                         ba.size(),
                                         ind);
                     tmpStorage.append(ba);
                 } else {
                     void *data = (void*)str.utf16();
                     int len = str.length();
                     r = SQLBindParameter(d->hStmt,
                                         i + 1,
                                         qParamType[(QFlag)(bindValueType(i)) & 3],
                                         SQL_C_WCHAR,
                                         SQL_WVARCHAR,
                                         len,
                                         0,
                                         data,
                                         len * sizeof(QChar),
                                         ind);
                 }
                 break;
             }
             default: {
                 QByteArray ba = values.at(i).toString().toAscii();
                 int len = ba.length() + 1;
                 if (*ind != SQL_NULL_DATA)
                     *ind = ba.length();
                 r = SQLBindParameter(d->hStmt,
                                       i + 1,
                                       qParamType[(QFlag)(bindValueType(i)) & 3],
                                       SQL_C_CHAR,
                                       SQL_VARCHAR,
                                       len,
                                       0,
                                       (void *) ba.constData(),
                                       len,
                                       ind);
                 tmpStorage.append(ba);
                 break; }
         }
         if (r != SQL_SUCCESS) {
             qWarning("QDB2Result::exec: unable to bind variable: %s",
                      qDB2Warn(d).toLocal8Bit().constData());
             setLastError(qMakeError(QCoreApplication::translate("QDB2Result",
                                     "Unable to bind variable"), QSqlError::StatementError, d));
             return false;
         }
     }
     r = SQLExecute(d->hStmt);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         qWarning("QDB2Result::exec: Unable to execute statement: %s",
                  qDB2Warn(d).toLocal8Bit().constData());
         setLastError(qMakeError(QCoreApplication::translate("QDB2Result",
                                 "Unable to execute statement"), QSqlError::StatementError, d));
         return false;
     }
     SQLSMALLINT count;
     r = SQLNumResultCols(d->hStmt, &count);
     if (count) {
         setSelect(true);
         for (int i = 0; i < count; ++i) {
             d->recInf.append(qMakeFieldInfo(d, i));
         }
     } else {
         setSelect(false);
     }
     setActive(true);
     d->valueCache.resize(count);
     d->valueCache.fill(NULL);
     //get out parameters
     if (!hasOutValues())
         return true;
     for (i = 0; i < values.count(); ++i) {
         switch (values[i].type()) {
             case QVariant::Date: {
                 DATE_STRUCT ds = *((DATE_STRUCT *)tmpStorage.takeFirst().constData());
                 values[i] = QVariant(QDate(ds.year, ds.month, ds.day));
                 break; }
             case QVariant::Time: {
                 TIME_STRUCT dt = *((TIME_STRUCT *)tmpStorage.takeFirst().constData());
                 values[i] = QVariant(QTime(dt.hour, dt.minute, dt.second));
                 break; }
             case QVariant::DateTime: {
                 TIMESTAMP_STRUCT dt = *((TIMESTAMP_STRUCT *)tmpStorage.takeFirst().constData());
                 values[i] = QVariant(QDateTime(QDate(dt.year, dt.month, dt.day),
                               QTime(dt.hour, dt.minute, dt.second, dt.fraction / 1000000)));
                 break; }
             case QVariant::Int:
             case QVariant::Double:
             case QVariant::ByteArray:
                 break;
             case QVariant::String:
                 if (bindValueType(i) & QSql::Out)
                     values[i] = QString((const QChar *)tmpStorage.takeFirst().constData());
                 break;
             default: {
                 values[i] = QString::fromAscii(tmpStorage.takeFirst().constData());
                 break; }
         }
         if (indicators[i] == SQL_NULL_DATA)
             values[i] = QVariant(values[i].type());
     }
     return true;
 }
fetch()
bool QDB2Result::fetch (int index) protected virtual
Positions the result to an arbitrary (zero-based) row index.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the row index, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
isActive(), fetchFirst(), fetchLast(), fetchNext(), fetchPrevious()
Implements QSqlResult.
Definition at line 848 of file qsql_db2.cpp.
Referenced by fetchLast().
 {
     if (isForwardOnly() && i < at())
         return false;
     if (i == at())
         return true;
     d->clearValueCache();
     int actualIdx = i + 1;
     if (actualIdx <= 0) {
         setAt(QSql::BeforeFirstRow);
         return false;
     }
     SQLRETURN r;
     if (isForwardOnly()) {
         bool ok = true;
         while (ok && i > at())
             ok = fetchNext();
         return ok;
     } else {
         r = SQLFetchScroll(d->hStmt,
                             SQL_FETCH_ABSOLUTE,
                             actualIdx);
     }
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO && r != SQL_NO_DATA) {
         setLastError(qMakeError(QCoreApplication::translate("QDB2Result",
                                 "Unable to fetch record %1").arg(i), QSqlError::StatementError, d));
         return false;
     }
     else if (r == SQL_NO_DATA)
         return false;
     setAt(i);
     return true;
 }
fetchFirst()
bool QDB2Result::fetchFirst () protected virtual
Positions the result to the first record (row 0) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the first record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchLast()
Implements QSqlResult.
Definition at line 899 of file qsql_db2.cpp.
 {
     if (isForwardOnly() && at() != QSql::BeforeFirstRow)
         return false;
     if (isForwardOnly())
         return fetchNext();
     d->clearValueCache();
     SQLRETURN r;
     r = SQLFetchScroll(d->hStmt,
                        SQL_FETCH_FIRST,
                        0);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         if(r!= SQL_NO_DATA)
             setLastError(qMakeError(QCoreApplication::translate("QDB2Result", "Unable to fetch first"),
                                     QSqlError::StatementError, d));
         return false;
     }
     setAt(0);
     return true;
 }
fetchLast()
bool QDB2Result::fetchLast () protected virtual
Positions the result to the last record (last row) in the result.
This function is only called if the result is in an active state. Derived classes must reimplement this function and position the result to the last record, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchFirst()
Implements QSqlResult.
Definition at line 920 of file qsql_db2.cpp.
 {
     d->clearValueCache();
     int i = at();
     if (i == QSql::AfterLastRow) {
         if (isForwardOnly()) {
             return false;
         } else {
             if (!fetch(0))
                 return false;
             i = at();
         }
     }
     while (fetchNext())
         ++i;
     if (i == QSql::BeforeFirstRow) {
         setAt(QSql::AfterLastRow);
         return false;
     }
     if (!isForwardOnly())
         return fetch(i);
     setAt(i);
     return true;
 }
fetchNext()
bool QDB2Result::fetchNext () protected virtual
Positions the result to the next available record (row) in the result.
This function is only called if the result is in an active state. The default implementation calls fetch() with the next index. Derived classes can reimplement this function and position the result to the next record in some other way, and call setAt() with an appropriate value. Return true to indicate success, or false to signify failure.
See also
fetch(), fetchPrevious()
Reimplemented from QSqlResult.
Definition at line 882 of file qsql_db2.cpp.
Referenced by fetch(), fetchFirst(), and fetchLast().
 {
     SQLRETURN r;
     d->clearValueCache();
     r = SQLFetchScroll(d->hStmt,
                        SQL_FETCH_NEXT,
                        0);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         if (r != SQL_NO_DATA)
             setLastError(qMakeError(QCoreApplication::translate("QDB2Result",
                                     "Unable to fetch next"), QSqlError::StatementError, d));
         return false;
     }
     setAt(at() + 1);
     return true;
 }
handle()
QVariant QDB2Result::handle () const virtual
Returns the low-level database handle for this result set wrapped in a QVariant or an invalid QVariant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the result is modified (for example, if you clear it).
The handle can be NULL if the result was not executed yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a sqlite result:
QSqlQuery query = ...
QVariant v = query.result()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3_stmt*")) {
    // v.data() returns a pointer to the handle
    sqlite3_stmt *handle = *static_cast<sqlite3_stmt **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (v.typeName() == "PGresult*") {
    PGresult *handle = *static_cast<PGresult **>(v.data());
    if (handle != 0) ...
}
if (v.typeName() == "MYSQL_STMT*") {
    MYSQL_STMT *handle = *static_cast<MYSQL_STMT **>(v.data());
    if (handle != 0) ...
}
See also
QSqlDriver::handle()
Reimplemented from QSqlResult.
Definition at line 513 of file qsql_db2.cpp.
 {
     return QVariant(qRegisterMetaType<SQLHANDLE>("SQLHANDLE"), &d->hStmt);
 }
isNull()
bool QDB2Result::isNull (int i) protected virtual
Returns true if the field at position index in the current row is null; otherwise returns false.
Implements QSqlResult.
Definition at line 1057 of file qsql_db2.cpp.
Referenced by data().
 {
     if (i >= d->valueCache.size())
         return true;
     if (d->valueCache[i])
         return d->valueCache[i]->isNull();
     return data(i).isNull();
 }
nextResult()
bool QDB2Result::nextResult () protected
Definition at line 1090 of file qsql_db2.cpp.
Referenced by virtual_hook().
 {
     setActive(false);
     setAt(QSql::BeforeFirstRow);
     d->recInf.clear();
     d->emptyValueCache();
     setSelect(false);
     SQLRETURN r = SQLMoreResults(d->hStmt);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         if (r != SQL_NO_DATA) {
             setLastError(qMakeError(QCoreApplication::translate("QODBCResult",
                 "Unable to fetch last"), QSqlError::ConnectionError, d));
         }
         return false;
     }
     SQLSMALLINT fieldCount;
     r = SQLNumResultCols(d->hStmt, &fieldCount);
     setSelect(fieldCount > 0);
     for (int i = 0; i < fieldCount; ++i)
         d->recInf.append(qMakeFieldInfo(d, i));
     d->valueCache.resize(fieldCount);
     d->valueCache.fill(NULL);
     setActive(true);
     return true;
 }
numRowsAffected()
int QDB2Result::numRowsAffected () protected virtual
Returns the number of rows affected by the last query executed, or -1 if it cannot be determined or if the query is a SELECT statement.
See also
size()
Implements QSqlResult.
Definition at line 1067 of file qsql_db2.cpp.
 {
     SQLINTEGER affectedRowCount = 0;
     SQLRETURN r = SQLRowCount(d->hStmt, &affectedRowCount);
     if (r == SQL_SUCCESS || r == SQL_SUCCESS_WITH_INFO)
         return affectedRowCount;
     else
         qSqlWarning(QLatin1String("QDB2Result::numRowsAffected: Unable to count affected rows"), d);
     return -1;
 }
prepare()
bool QDB2Result::prepare (const QString & query) virtual
Prepares the given query for execution; the query will normally use placeholders so that it can be executed repeatedly.
Returns true if the query is prepared successfully; otherwise returns false.
See also
exec()
Reimplemented from QSqlResult.
Definition at line 573 of file qsql_db2.cpp.
 {
     setActive(false);
     setAt(QSql::BeforeFirstRow);
     SQLRETURN r;
     d->recInf.clear();
     d->emptyValueCache();
     if (!qMakeStatement(d, isForwardOnly()))
         return false;
     r = SQLPrepare(d->hStmt,
                     qToTChar(query),
                     (SQLINTEGER) query.length());
     if (r != SQL_SUCCESS) {
         setLastError(qMakeError(QCoreApplication::translate("QDB2Result",
                      "Unable to prepare statement"), QSqlError::StatementError, d));
         return false;
     }
     return true;
 }
record()
QSqlRecord QDB2Result::record () const protected virtual
Returns the current record if the query is active; otherwise returns an empty QSqlRecord.
The default implementation always returns an empty QSqlRecord.
See also
isActive()
Reimplemented from QSqlResult.
Definition at line 1083 of file qsql_db2.cpp.
 {
     if (isActive())
         return d->recInf;
     return QSqlRecord();
 }
reset()
bool QDB2Result::reset (const QString & query) protected virtual
Sets the result to use the SQL statement query for subsequent data retrieval.
Derived classes must reimplement this function and apply the query to the database. This function is only called after the result is set to an inactive state and is positioned before the first record of the new result. Derived classes should return true if the query was successful and ready to be used, or false otherwise.
See also
setQuery()
Implements QSqlResult.
Definition at line 537 of file qsql_db2.cpp.
 {
     setActive(false);
     setAt(QSql::BeforeFirstRow);
     SQLRETURN r;
     d->recInf.clear();
     d->emptyValueCache();
     if (!qMakeStatement(d, isForwardOnly()))
         return false;
     r = SQLExecDirect(d->hStmt,
                        qToTChar(query),
                        (SQLINTEGER) query.length());
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         setLastError(qMakeError(QCoreApplication::translate("QDB2Result",
                                 "Unable to execute statement"), QSqlError::StatementError, d));
         return false;
     }
     SQLSMALLINT count;
     r = SQLNumResultCols(d->hStmt, &count);
     if (count) {
         setSelect(true);
         for (int i = 0; i < count; ++i) {
             d->recInf.append(qMakeFieldInfo(d, i));
         }
     } else {
         setSelect(false);
     }
     d->valueCache.resize(count);
     d->valueCache.fill(NULL);
     setActive(true);
     return true;
 }
size()
int QDB2Result::size () protected virtual
Returns the size of the SELECT result, or -1 if it cannot be determined or if the query is not a SELECT statement.
See also
numRowsAffected()
Implements QSqlResult.
Definition at line 1078 of file qsql_db2.cpp.
 {
     return -1;
 }
virtual_hook()
void QDB2Result::virtual_hook (int id, void * data) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QSqlResult.
Definition at line 1120 of file qsql_db2.cpp.
 {
     switch (id) {
     case QSqlResult::NextResult:
         Q_ASSERT(data);
         *static_cast<bool*>(data) = nextResult();
         break;
     case QSqlResult::DetachFromResultSet:
         if (d->hStmt)
             SQLCloseCursor(d->hStmt);
         break;
     default:
         QSqlResult::virtual_hook(id, data);
     }
 }
Properties
d
QDB2ResultPrivate* QDB2Result::d private
Definition at line 86 of file qsql_db2.h.
Referenced by data(), exec(), fetch(), fetchFirst(), fetchLast(), fetchNext(), isNull(), nextResult(), numRowsAffected(), prepare(), QDB2Result(), record(), reset(), virtual_hook(), and ~QDB2Result().
The documentation for this class was generated from the following files:
/src/sql/drivers/db2/qsql_db2.h
/src/sql/drivers/db2/qsql_db2.cpp