Qt 4.8: QDeclarativeJS::AST::ExpressionNode Class Reference
QDeclarativeJS::AST::ExpressionNode Class Reference abstract
#include <qdeclarativejsast_p.h>
Public Functions
virtual ExpressionNode * expressionCast ()
ExpressionNode ()
virtual SourceLocation firstSourceLocation () const =0
virtual SourceLocation lastSourceLocation () const =0
Public Functions inherited from QDeclarativeJS::AST::Node
void accept (Visitor *visitor)
virtual void accept0 (Visitor *visitor)=0
virtual BinaryExpression * binaryExpressionCast ()
Node ()
virtual Statement * statementCast ()
virtual UiObjectMember * uiObjectMemberCast ()
virtual ~Node ()
Additional Inherited Members
Public Types inherited from QDeclarativeJS::AST::Node
enum Kind {
Kind_Undefined, Kind_ArgumentList, Kind_ArrayLiteral, Kind_ArrayMemberExpression,
Kind_BinaryExpression, Kind_Block, Kind_BreakStatement, Kind_CallExpression,
Kind_CaseBlock, Kind_CaseClause, Kind_CaseClauses, Kind_Catch,
Kind_ConditionalExpression, Kind_ContinueStatement, Kind_DebuggerStatement, Kind_DefaultClause,
Kind_DeleteExpression, Kind_DoWhileStatement, Kind_ElementList, Kind_Elision,
Kind_EmptyStatement, Kind_Expression, Kind_ExpressionStatement, Kind_FalseLiteral,
Kind_FieldMemberExpression, Kind_Finally, Kind_ForEachStatement, Kind_ForStatement,
Kind_FormalParameterList, Kind_FunctionBody, Kind_FunctionDeclaration, Kind_FunctionExpression,
Kind_FunctionSourceElement, Kind_IdentifierExpression, Kind_IdentifierPropertyName, Kind_IfStatement,
Kind_LabelledStatement, Kind_LocalForEachStatement, Kind_LocalForStatement, Kind_NewExpression,
Kind_NewMemberExpression, Kind_NotExpression, Kind_NullExpression, Kind_NumericLiteral,
Kind_NumericLiteralPropertyName, Kind_ObjectLiteral, Kind_PostDecrementExpression, Kind_PostIncrementExpression,
Kind_PreDecrementExpression, Kind_PreIncrementExpression, Kind_Program, Kind_PropertyName,
Kind_PropertyNameAndValueList, Kind_RegExpLiteral, Kind_ReturnStatement, Kind_SourceElement,
Kind_SourceElements, Kind_StatementList, Kind_StatementSourceElement, Kind_StringLiteral,
Kind_StringLiteralPropertyName, Kind_SwitchStatement, Kind_ThisExpression, Kind_ThrowStatement,
Kind_TildeExpression, Kind_TrueLiteral, Kind_TryStatement, Kind_TypeOfExpression,
Kind_UnaryMinusExpression, Kind_UnaryPlusExpression, Kind_VariableDeclaration, Kind_VariableDeclarationList,
Kind_VariableStatement, Kind_VoidExpression, Kind_WhileStatement, Kind_WithStatement,
Kind_NestedExpression, Kind_UiArrayBinding, Kind_UiImport, Kind_UiImportList,
Kind_UiObjectBinding, Kind_UiObjectDefinition, Kind_UiObjectInitializer, Kind_UiObjectMemberList,
Kind_UiArrayMemberList, Kind_UiProgram, Kind_UiParameterList, Kind_UiPublicMember,
Kind_UiQualifiedId, Kind_UiScriptBinding, Kind_UiSourceElement, Kind_UiFormal,
Kind_UiFormalList, Kind_UiSignature
}
Static Public Functions inherited from QDeclarativeJS::AST::Node
static void accept (Node *node, Visitor *visitor)
static void acceptChild (Node *node, Visitor *visitor)
Public Variables inherited from QDeclarativeJS::AST::Node
int kind
Detailed Description
Definition at line 249 of file qdeclarativejsast_p.h.
Constructors and Destructors
ExpressionNode()
QDeclarativeJS::AST::ExpressionNode::ExpressionNode () inline
Definition at line 252 of file qdeclarativejsast_p.h.
 {}
Functions
expressionCast()
ExpressionNode * QDeclarativeJS::AST::ExpressionNode::expressionCast () virtual
Reimplemented from QDeclarativeJS::AST::Node.
Definition at line 84 of file qdeclarativejsast.cpp.
Referenced by QDeclarativeJS::Parser::expression().
 {
     return this;
 }
firstSourceLocation()
virtual SourceLocation QDeclarativeJS::AST::ExpressionNode::firstSourceLocation () const pure virtual
Implemented in QDeclarativeJS::AST::FunctionExpression, QDeclarativeJS::AST::Expression, QDeclarativeJS::AST::ConditionalExpression, QDeclarativeJS::AST::BinaryExpression, QDeclarativeJS::AST::NotExpression, QDeclarativeJS::AST::TildeExpression, QDeclarativeJS::AST::UnaryMinusExpression, QDeclarativeJS::AST::UnaryPlusExpression, QDeclarativeJS::AST::PreDecrementExpression, QDeclarativeJS::AST::PreIncrementExpression, QDeclarativeJS::AST::TypeOfExpression, QDeclarativeJS::AST::VoidExpression, QDeclarativeJS::AST::DeleteExpression, QDeclarativeJS::AST::PostDecrementExpression, QDeclarativeJS::AST::PostIncrementExpression, QDeclarativeJS::AST::CallExpression, QDeclarativeJS::AST::NewExpression, QDeclarativeJS::AST::NewMemberExpression, QDeclarativeJS::AST::FieldMemberExpression, QDeclarativeJS::AST::ArrayMemberExpression, QDeclarativeJS::AST::ObjectLiteral, QDeclarativeJS::AST::ArrayLiteral, QDeclarativeJS::AST::RegExpLiteral, QDeclarativeJS::AST::StringLiteral, QDeclarativeJS::AST::NumericLiteral, QDeclarativeJS::AST::FalseLiteral, QDeclarativeJS::AST::TrueLiteral, QDeclarativeJS::AST::NullExpression, QDeclarativeJS::AST::IdentifierExpression, QDeclarativeJS::AST::ThisExpression, and QDeclarativeJS::AST::NestedExpression.
Referenced by QDeclarativeBindingCompilerPrivate::compile(), QDeclarativeBindingCompilerPrivate::exceptionId(), QDeclarativeJS::AST::FieldMemberExpression::firstSourceLocation(), QDeclarativeJS::AST::CallExpression::firstSourceLocation(), QDeclarativeJS::AST::PostIncrementExpression::firstSourceLocation(), QDeclarativeJS::AST::PostDecrementExpression::firstSourceLocation(), QDeclarativeJS::AST::ConditionalExpression::firstSourceLocation(), QDeclarativeJS::AST::Expression::firstSourceLocation(), QDeclarativeJS::AST::ExpressionStatement::firstSourceLocation(), and QDeclarativeRewrite::RewriteBinding::operator()().
lastSourceLocation()
virtual SourceLocation QDeclarativeJS::AST::ExpressionNode::lastSourceLocation () const pure virtual
Implemented in QDeclarativeJS::AST::FunctionExpression, QDeclarativeJS::AST::Expression, QDeclarativeJS::AST::ConditionalExpression, QDeclarativeJS::AST::BinaryExpression, QDeclarativeJS::AST::NotExpression, QDeclarativeJS::AST::TildeExpression, QDeclarativeJS::AST::UnaryMinusExpression, QDeclarativeJS::AST::UnaryPlusExpression, QDeclarativeJS::AST::PreDecrementExpression, QDeclarativeJS::AST::PreIncrementExpression, QDeclarativeJS::AST::TypeOfExpression, QDeclarativeJS::AST::VoidExpression, QDeclarativeJS::AST::DeleteExpression, QDeclarativeJS::AST::PostDecrementExpression, QDeclarativeJS::AST::PostIncrementExpression, QDeclarativeJS::AST::CallExpression, QDeclarativeJS::AST::NewExpression, QDeclarativeJS::AST::NewMemberExpression, QDeclarativeJS::AST::FieldMemberExpression, QDeclarativeJS::AST::ArrayMemberExpression, QDeclarativeJS::AST::ObjectLiteral, QDeclarativeJS::AST::ArrayLiteral, QDeclarativeJS::AST::RegExpLiteral, QDeclarativeJS::AST::StringLiteral, QDeclarativeJS::AST::NumericLiteral, QDeclarativeJS::AST::FalseLiteral, QDeclarativeJS::AST::TrueLiteral, QDeclarativeJS::AST::NullExpression, QDeclarativeJS::AST::IdentifierExpression, QDeclarativeJS::AST::ThisExpression, and QDeclarativeJS::AST::NestedExpression.
Referenced by QDeclarativeJS::AST::NewExpression::lastSourceLocation(), QDeclarativeJS::AST::DeleteExpression::lastSourceLocation(), QDeclarativeJS::AST::VoidExpression::lastSourceLocation(), QDeclarativeJS::AST::TypeOfExpression::lastSourceLocation(), QDeclarativeJS::AST::PreIncrementExpression::lastSourceLocation(), QDeclarativeJS::AST::PreDecrementExpression::lastSourceLocation(), QDeclarativeJS::AST::UnaryPlusExpression::lastSourceLocation(), QDeclarativeJS::AST::UnaryMinusExpression::lastSourceLocation(), QDeclarativeJS::AST::TildeExpression::lastSourceLocation(), QDeclarativeJS::AST::NotExpression::lastSourceLocation(), QDeclarativeJS::AST::Expression::lastSourceLocation(), QDeclarativeJS::AST::IfStatement::lastSourceLocation(), and QDeclarativeRewrite::RewriteBinding::operator()().
The documentation for this class was generated from the following files:
/src/declarative/qml/parser/qdeclarativejsast_p.h
/src/declarative/qml/parser/qdeclarativejsast.cpp