Qt 4.8: QtConcurrent::internal::ExceptionStore Class Reference
QtConcurrent::internal::ExceptionStore Class Reference
#include <qtconcurrentexception.h>
Public Functions
ExceptionHolder exception ()
bool hasException () const
bool hasThrown () const
void setException (const Exception &e)
void throwPossibleException ()
Public Variables
ExceptionHolder exceptionHolder
Detailed Description
Definition at line 93 of file qtconcurrentexception.h.
Functions
exception()
ExceptionHolder QtConcurrent::internal::ExceptionStore::exception ()
hasException()
bool QtConcurrent::internal::ExceptionStore::hasException () const
hasThrown()
bool QtConcurrent::internal::ExceptionStore::hasThrown () const
setException()
void QtConcurrent::internal::ExceptionStore::setException (const Exception & e)
Referenced by QFutureInterfaceBase::reportException().
throwPossibleException()
void QtConcurrent::internal::ExceptionStore::throwPossibleException ()
Referenced by QFutureInterfaceBase::waitForFinished(), and QFutureInterfaceBase::waitForResult().
Properties
exceptionHolder
ExceptionHolder QtConcurrent::internal::ExceptionStore::exceptionHolder
Definition at line 101 of file qtconcurrentexception.h.
The documentation for this class was generated from the following file:
/src/corelib/concurrent/qtconcurrentexception.h