Qt 4.8: NestedListModel Class Reference
NestedListModel Class Reference
#include <qdeclarativelistmodel_p_p.h>
Public Functions
void checkRoles () const
void clear ()
int count () const
QHash< int, QVariant > data (int index, const QList< int > &roles, bool *hasNested=0) const
QVariant data (int index, int role) const
QScriptValue get (int index) const
bool insert (int index, const QScriptValue &)
void move (int from, int to, int count)
NestedListModel (QDeclarativeListModel *base)
void remove (int index)
QList< int > roles () const
void set (int index, const QScriptValue &, QList< int > *roles)
void setProperty (int index, const QString &property, const QVariant &value, QList< int > *roles)
QString toString (int role) const
QVariant valueForNode (ModelNode *, bool *hasNested=0) const
~NestedListModel ()
Public Variables
ModelNode * _root
QDeclarativeListModel * m_listModel
bool m_ownsRoot
Properties
bool _rolesOk
QStringList roleStrings
Friends
struct ModelNode
Detailed Description
Definition at line 175 of file qdeclarativelistmodel_p_p.h.
Constructors and Destructors
NestedListModel()
NestedListModel::NestedListModel (QDeclarativeListModel * base)
Definition at line 1239 of file qdeclarativelistmodel.cpp.
     : _root(0), m_ownsRoot(false), m_listModel(base), _rolesOk(false)
 {
 }
~NestedListModel()
NestedListModel::~NestedListModel ()
Definition at line 1244 of file qdeclarativelistmodel.cpp.
 {
     if (m_ownsRoot)
         delete _root;
 }
Functions
checkRoles()
void NestedListModel::checkRoles () const
Definition at line 1437 of file qdeclarativelistmodel.cpp.
Referenced by ModelNode::changedProperty(), data(), roles(), and toString().
 {
     if (_rolesOk || !_root)
         return;
     for (int i = 0; i<_root->values.count(); ++i) {
         ModelNode *node = qvariant_cast<ModelNode *>(_root->values.at(i));
         if (node) {
             foreach (const QString &role, node->properties.keys()) {
                 if (!roleStrings.contains(role))
                     roleStrings.append(role);
             }
         }
     }
     _rolesOk = true;
 }
clear()
void NestedListModel::clear ()
Definition at line 1342 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::clear().
 {
     if (_root)
         _root->clear();
 }
count()
int NestedListModel::count () const
Definition at line 1336 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::data(), QDeclarativeListModel::flatten(), get(), set(), and setProperty().
 {
     if (!_root) return 0;
     return _root->values.count();
 }
data() [1/2]
QHash< int, QVariant > NestedListModel::data (int index, const QList< int > & roles, bool * hasNested = 0) const
Definition at line 1290 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::data(), and QDeclarativeListModel::flatten().
 {
     Q_ASSERT(_root && index >= 0 && index < _root->values.count());
     checkRoles();
     QHash<int, QVariant> rv;
     ModelNode *node = qvariant_cast<ModelNode *>(_root->values.at(index));
     if (!node)
         return rv;
     for (int ii = 0; ii < roles.count(); ++ii) {
         const QString &roleString = roleStrings.at(roles.at(ii));
         QHash<QString, ModelNode *>::ConstIterator iter = node->properties.find(roleString);
         if (iter != node->properties.end()) {
             ModelNode *row = *iter;
             rv.insert(roles.at(ii), valueForNode(row, hasNested));
         }
     }
     return rv;
 }
data() [2/2]
QVariant NestedListModel::data (int index, int role) const
Definition at line 1313 of file qdeclarativelistmodel.cpp.
 {
     Q_ASSERT(_root && index >= 0 && index < _root->values.count());
     checkRoles();
     QVariant rv;
     if (roleStrings.count() < role)
         return rv;
     ModelNode *node = qvariant_cast<ModelNode *>(_root->values.at(index));
     if (!node)
         return rv;
     const QString &roleString = roleStrings.at(role);
     QHash<QString, ModelNode *>::ConstIterator iter = node->properties.find(roleString);
     if (iter != node->properties.end()) {
         ModelNode *row = *iter;
         rv = valueForNode(row);
     }
     return rv;
 }
get()
QScriptValue NestedListModel::get (int index) const
Definition at line 1379 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::get().
 {
     QDeclarativeEngine *eng = qmlEngine(m_listModel);
     if (!eng)
         return 0;
     if (index < 0 || index >= count()) {
         QScriptEngine *seng = QDeclarativeEnginePrivate::getScriptEngine(eng);
         if (seng)
             return seng->undefinedValue();
         return 0;
     }
     ModelNode *node = qvariant_cast<ModelNode *>(_root->values.at(index));
     if (!node)
         return 0;
     return QDeclarativeEnginePrivate::qmlScriptObject(node->object(this), eng);
 }
insert()
bool NestedListModel::insert (int index, const QScriptValue & valuemap)
Definition at line 1358 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::insert().
 {
     if (!_root) {
         _root = new ModelNode(this);
         m_ownsRoot = true;
     }
     ModelNode *mn = new ModelNode(this);
     mn->listIndex = index;
     mn->setObjectValue(valuemap);
     _root->values.insert(index,QVariant::fromValue(mn));
     return true;
 }
move()
void NestedListModel::move (int from, int to, int count)
Definition at line 1372 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::move().
 {
     if (!_root)
         return;
     qdeclarativelistmodel_move<QVariantList>(from, to, n, &_root->values);
 }
remove()
void NestedListModel::remove (int index)
Definition at line 1348 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::remove().
 {
     if (!_root)
         return;
     ModelNode *node = qvariant_cast<ModelNode *>(_root->values.at(index));
     _root->values.removeAt(index);
     if (node)
         delete node;
 }
roles()
QList< int > NestedListModel::roles () const
Definition at line 1455 of file qdeclarativelistmodel.cpp.
Referenced by ModelNode::changedProperty(), QDeclarativeListModel::flatten(), and QDeclarativeListModel::roles().
 {
     checkRoles();
     QList<int> rv;
     for (int ii = 0; ii < roleStrings.count(); ++ii)
         rv << ii;
     return rv;
 }
set()
void NestedListModel::set (int index, const QScriptValue & valuemap, QList< int > * roles)
Definition at line 1399 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::set().
 {
     Q_ASSERT(index >=0 && index < count());
     ModelNode *node = qvariant_cast<ModelNode *>(_root->values.at(index));
     bool emitItemsChanged = node->setObjectValue(valuemap);
     if (!emitItemsChanged)
         return;
     QScriptValueIterator it(valuemap);
     while (it.hasNext()) {
         it.next();
         int r = roleStrings.indexOf(it.name());
         if (r < 0) {
             r = roleStrings.count();
             roleStrings << it.name();
         }
         roles->append(r);
     }
 }
setProperty()
void NestedListModel::setProperty (int index, const QString & property, const QVariant & value, QList< int > * roles)
Definition at line 1420 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::setProperty().
 {
     Q_ASSERT(index >=0 && index < count());
     ModelNode *node = qvariant_cast<ModelNode *>(_root->values.at(index));
     bool emitItemsChanged = node->setProperty(property, value);
     if (!emitItemsChanged)
         return;
     int r = roleStrings.indexOf(property);
     if (r < 0) {
         r = roleStrings.count();
         roleStrings << property;
     }
     roles->append(r);
 }
toString()
QString NestedListModel::toString (int role) const
Definition at line 1464 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModel::flatten(), and QDeclarativeListModel::toString().
 {
     checkRoles();
     if (role < roleStrings.count())
         return roleStrings.at(role);
     else
         return QString();
 }
valueForNode()
QVariant NestedListModel::valueForNode (ModelNode * node, bool * hasNested = 0) const
Definition at line 1250 of file qdeclarativelistmodel.cpp.
Referenced by data(), and ModelNode::object().
 {
     QObject *rv = 0;
     if (hasNested)
         *hasNested = false;
     if (node->isArray) {
         // List
         rv = node->model(this);
         if (hasNested)
             *hasNested = true;
     } else {
         if (!node->properties.isEmpty()) {
             // Object
             rv = node->object(this);
         } else if (node->values.count() == 0) {
             // Invalid
             return QVariant();
         } else if (node->values.count() == 1) {
             // Value
             QVariant &var = node->values[0];
             ModelNode *valueNode = qvariant_cast<ModelNode *>(var);
             if (valueNode) {
                 if (!valueNode->properties.isEmpty())
                     rv = valueNode->object(this);
                 else
                     rv = valueNode->model(this);
             } else {
                 return var;
             }
         }
     }
     if (rv) {
         return QVariant::fromValue(rv);
     } else {
         return QVariant();
     }
 }
Friends and Related Functions
ModelNode
friend struct ModelNode friend
Definition at line 204 of file qdeclarativelistmodel_p_p.h.
Referenced by insert().
Properties
_rolesOk
bool NestedListModel::_rolesOk mutable private
Definition at line 206 of file qdeclarativelistmodel_p_p.h.
Referenced by checkRoles().
_root
ModelNode* NestedListModel::_root
Definition at line 199 of file qdeclarativelistmodel_p_p.h.
Referenced by checkRoles(), clear(), count(), data(), get(), insert(), move(), remove(), set(), QDeclarativeListModelParser::setCustomData(), setProperty(), ModelNode::~ModelNode(), and ~NestedListModel().
m_listModel
QDeclarativeListModel* NestedListModel::m_listModel
Definition at line 201 of file qdeclarativelistmodel_p_p.h.
Referenced by ModelNode::changedProperty(), get(), ModelNode::model(), and ModelNode::object().
m_ownsRoot
bool NestedListModel::m_ownsRoot
Definition at line 200 of file qdeclarativelistmodel_p_p.h.
Referenced by insert(), QDeclarativeListModelParser::setCustomData(), and ~NestedListModel().
roleStrings
QStringList NestedListModel::roleStrings mutable private
Definition at line 205 of file qdeclarativelistmodel_p_p.h.
Referenced by ModelNode::changedProperty(), checkRoles(), data(), roles(), set(), setProperty(), and toString().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativelistmodel_p_p.h
/src/declarative/util/qdeclarativelistmodel.cpp