Qt 4.8: QDeclarativeTypeNameCache Class Reference
QDeclarativeTypeNameCache Class Reference
#include <qdeclarativetypenamecache_p.h>
Classes
struct Data
struct RData
Public Functions
void add (const QString &, int)
void add (const QString &, QDeclarativeType *)
void add (const QString &, QDeclarativeTypeNameCache *)
Data * data (const QString &) const
Data * data (const QScriptDeclarativeClass::Identifier &id) const
QDeclarativeTypeNameCache (QDeclarativeEngine *)
virtual ~QDeclarativeTypeNameCache ()
Public Functions inherited from QDeclarativeRefCount
void addref ()
QDeclarativeRefCount ()
void release ()
virtual ~QDeclarativeRefCount ()
Public Functions inherited from QDeclarativeCleanup
QDeclarativeCleanup (QDeclarativeEngine *)
virtual ~QDeclarativeCleanup ()
Protected Functions
virtual void clear ()
Private Types
typedef QHash< QScriptDeclarativeClass::Identifier, RData * > IdentifierCache
typedef QHash< QString, RData * > StringCache
Properties
QDeclarativeEngine * engine
IdentifierCache identifierCache
StringCache stringCache
Detailed Description
Definition at line 65 of file qdeclarativetypenamecache_p.h.
Typedefs
IdentifierCache
typedef QHash<QScriptDeclarativeClass::Identifier, RData *> QDeclarativeTypeNameCache::IdentifierCache private
Definition at line 94 of file qdeclarativetypenamecache_p.h.
StringCache
typedef QHash<QString, RData *> QDeclarativeTypeNameCache::StringCache private
Definition at line 93 of file qdeclarativetypenamecache_p.h.
Constructors and Destructors
QDeclarativeTypeNameCache()
QDeclarativeTypeNameCache::QDeclarativeTypeNameCache (QDeclarativeEngine * e)
Definition at line 48 of file qdeclarativetypenamecache.cpp.
 : QDeclarativeCleanup(e), engine(e)
 {
 }
~QDeclarativeTypeNameCache()
QDeclarativeTypeNameCache::~QDeclarativeTypeNameCache () virtual
Definition at line 53 of file qdeclarativetypenamecache.cpp.
 {
     clear();
 }
Functions
add() [1/3]
void QDeclarativeTypeNameCache::add (const QString & name, int importedScriptIndex)
Definition at line 66 of file qdeclarativetypenamecache.cpp.
Referenced by cacheForNamespace(), QDeclarativeCompiler::compileTree(), and QDeclarativeImports::populateCache().
 {
     if (stringCache.contains(name))
         return;
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     RData *data = new RData;
     // ### Use typename class
     data->identifier = ep->objectClass->createPersistentIdentifier(name);
     data->importedScriptIndex = importedScriptIndex;
     stringCache.insert(name, data);
     identifierCache.insert(data->identifier.identifier, data);
 }
add() [2/3]
void QDeclarativeTypeNameCache::add (const QString & name, QDeclarativeType * type)
Definition at line 81 of file qdeclarativetypenamecache.cpp.
 {
     if (stringCache.contains(name))
         return;
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     RData *data = new RData;
     // ### Use typename class
     data->identifier = ep->objectClass->createPersistentIdentifier(name);
     data->type = type;
     stringCache.insert(name, data);
     identifierCache.insert(data->identifier.identifier, data);
 }
add() [3/3]
void QDeclarativeTypeNameCache::add (const QString & name, QDeclarativeTypeNameCache * typeNamespace)
Definition at line 96 of file qdeclarativetypenamecache.cpp.
 {
     if (stringCache.contains(name))
         return;
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     RData *data = new RData;
     // ### Use typename class
     data->identifier = ep->objectClass->createPersistentIdentifier(name);
     data->typeNamespace = typeNamespace;
     stringCache.insert(name, data);
     identifierCache.insert(data->identifier.identifier, data);
     typeNamespace->addref();
 }
clear()
void QDeclarativeTypeNameCache::clear () protected virtual
Implements QDeclarativeCleanup.
Definition at line 58 of file qdeclarativetypenamecache.cpp.
Referenced by ~QDeclarativeTypeNameCache().
 {
     qDeleteAll(stringCache);
     stringCache.clear();
     identifierCache.clear();
     engine = 0;
 }
data() [1/2]
QDeclarativeTypeNameCache::Data * QDeclarativeTypeNameCache::data (const QString & id) const
Definition at line 112 of file qdeclarativetypenamecache.cpp.
Referenced by add(), QDeclarativePropertyPrivate::initProperty(), QDeclarativeImports::populateCache(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeContextScriptClass::queryProperty(), and QDeclarativeObjectScriptClass::queryProperty().
 {
     return stringCache.value(id);
 }
data() [2/2]
QDeclarativeTypeNameCache::Data * QDeclarativeTypeNameCache::data (const QScriptDeclarativeClass::Identifier & id) const inline
Definition at line 111 of file qdeclarativetypenamecache_p.h.
 {
     return identifierCache.value(id);
 }
Properties
engine
QDeclarativeEngine* QDeclarativeTypeNameCache::engine private
Definition at line 98 of file qdeclarativetypenamecache_p.h.
Referenced by add(), and clear().
identifierCache
IdentifierCache QDeclarativeTypeNameCache::identifierCache private
Definition at line 97 of file qdeclarativetypenamecache_p.h.
Referenced by add(), clear(), and data().
stringCache
StringCache QDeclarativeTypeNameCache::stringCache private
Definition at line 96 of file qdeclarativetypenamecache_p.h.
Referenced by add(), clear(), and data().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativetypenamecache_p.h
/src/declarative/qml/qdeclarativetypenamecache.cpp