Qt 4.8: QHeaderViewPrivate Class Reference
QHeaderViewPrivate Class Reference
#include <qheaderview_p.h>
Classes
struct SectionSpan
Public Types
enum State {
NoState, ResizeSection, MoveSection, SelectSections,
NoClear
}
enum StateVersion { VersionMarker = 0xff }
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Functions
void _q_layoutAboutToBeChanged ()
void _q_layoutChanged ()
This slot is called when the layout is changed.
void _q_sectionsRemoved (const QModelIndex &, int, int)
int adjustedVisualIndex (int visualIndex) const
void cascadingResize (int visual, int newSize)
void clear ()
void clearCascadingSections ()
bool columnIntersectsSelection (int column) const
void createSectionSpan (int start, int end, int size, QHeaderView::ResizeMode mode)
void doDelayedResizeSections ()
void executePostedResize () const
void flipSortIndicator (int section)
QStyleOptionHeader getStyleOption () const
bool hasAutoResizeSections () const
int headerLength () const
int headerSectionCount () const
int headerSectionPosition (int visual) const
QHeaderView::ResizeMode headerSectionResizeMode (int visual) const
int headerSectionSize (int visual) const
int headerVisualIndexAt (int position) const
void initializeIndexMapping () const
void invalidateCachedSizeHint () const
bool isColumnSelected (int column) const
bool isRowSelected (int row) const
bool isSectionSelected (int section) const
bool isVisualIndexHidden (int visual) const
int lastVisibleVisualIndex () const
Returns the last visible (ie.
int logicalIndex (int visualIndex) const
bool modelIsEmpty () const
int modelSectionCount () const
void prepareSectionSelected ()
QHeaderViewPrivate ()
bool read (QDataStream &in)
void removeSectionsFromSpans (int start, int end)
void removeSpans (const QList< int > &spans)
void resizeSections (QHeaderView::ResizeMode globalMode, bool useGlobalMode=false)
Go through and resize all of the sections applying stretchLastSection, manualy stretches, sizes, and useGlobalMode.
void resizeSectionSpan (int visualIndex, int oldSize, int newSize)
bool reverse () const
bool rowIntersectsSelection (int row) const
void saveCascadingSectionSize (int visual, int size)
int sectionHandleAt (int position)
bool sectionIntersectsSelection (int logical) const
bool sectionIsCascadable (int visual) const
int sectionSpanIndex (int visual) const
void setDefaultSectionSize (int size)
void setDefaultValues (Qt::Orientation o)
void setGlobalHeaderResizeMode (QHeaderView::ResizeMode mode)
void setHeaderSectionResizeMode (int visual, QHeaderView::ResizeMode mode)
void setupSectionIndicator (int section, int position)
void setVisualIndexHidden (int visual, bool hidden)
void updateHiddenSections (int logicalFirst, int logicalLast)
void updateSectionIndicator (int section, int position)
int viewSectionSizeHint (int logical) const
int visualIndex (int logicalIndex) const
void write (QDataStream &out) const
Public Functions inherited from QAbstractItemViewPrivate
virtual void _q_columnsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
This slot is called when columns are about to be removed.
virtual void _q_columnsInserted (const QModelIndex &parent, int start, int end)
This slot is called when columns have been inserted.
virtual void _q_columnsRemoved (const QModelIndex &parent, int start, int end)
This slot is called when columns have been removed.
void _q_headerDataChanged ()
virtual void _q_modelDestroyed ()
virtual void _q_rowsInserted (const QModelIndex &parent, int start, int end)
This slot is called when rows have been inserted.
virtual void _q_rowsRemoved (const QModelIndex &parent, int start, int end)
This slot is called when rows have been removed.
void addEditor (const QModelIndex &index, QWidget *editor, bool isStatic)
virtual void adjustViewOptionsForIndex (QStyleOptionViewItemV4 *, const QModelIndex &) const
bool canDecode (QDropEvent *e) const
void checkMouseMove (const QPersistentModelIndex &index)
void checkMouseMove (const QPoint &pos)
void checkPersistentEditorFocus ()
When persistent aeditor gets/loses focus, we need to check and setcorrectly the current index.
void clearOrRemove ()
In DND if something has been moved then this is called.
virtual QPoint contentsOffset () const
QItemSelectionModel::SelectionFlags contiguousSelectionCommand (const QModelIndex &index, const QEvent *event) const
QAbstractItemDelegate * delegateForIndex (const QModelIndex &index) const
int delegateRefCount (const QAbstractItemDelegate *delegate) const
void doDelayedItemsLayout (int delay=0)
void doDelayedReset ()
virtual QItemViewPaintPairs draggablePaintPairs (const QModelIndexList &indexes, QRect *r) const
virtual bool dropOn (QDropEvent *event, int *row, int *col, QModelIndex *index)
If the event hasn't already been accepted, determines the index to drop on.
bool droppingOnItself (QDropEvent *event, const QModelIndex &index)
Return true if this is a move from ourself and index is a child of the selection that is being moved.
QWidget * editor (const QModelIndex &index, const QStyleOptionViewItem &options)
const QEditorInfo & editorForIndex (const QModelIndex &index) const
void executePostedLayout () const
QItemSelectionModel::SelectionFlags extendedSelectionCommand (const QModelIndex &index, const QEvent *event) const
void fetchMore ()
bool hasEditor (const QModelIndex &index) const
QModelIndex indexForEditor (QWidget *editor) const
void init ()
void interruptDelayedItemsLayout () const
bool isAnimating () const
bool isIndexDragEnabled (const QModelIndex &index) const
bool isIndexDropEnabled (const QModelIndex &index) const
bool isIndexEnabled (const QModelIndex &index) const
bool isIndexSelectable (const QModelIndex &index) const
bool isIndexValid (const QModelIndex &index) const
bool isPersistent (const QModelIndex &index) const
QItemSelectionModel::SelectionFlags multiSelectionCommand (const QModelIndex &index, const QEvent *event) const
QPoint offset () const
bool openEditor (const QModelIndex &index, QEvent *event)
void paintDropIndicator (QPainter *painter)
virtual QAbstractItemView::DropIndicatorPosition position (const QPoint &pos, const QRect &rect, const QModelIndex &idx) const
QAbstractItemViewPrivate ()
void releaseEditor (QWidget *editor) const
void removeEditor (QWidget *editor)
QPixmap renderToPixmap (const QModelIndexList &indexes, QRect *r) const
void scrollContentsBy (int dx, int dy)
void scrollDirtyRegion (int dx, int dy)
virtual void selectAll (QItemSelectionModel::SelectionFlags command)
QModelIndexList selectedDraggableIndexes () const
virtual bool selectionAllowed (const QModelIndex &index) const
QItemSelectionModel::SelectionFlags selectionBehaviorFlags () const
bool sendDelegateEvent (const QModelIndex &index, QEvent *event) const
void setDirtyRegion (const QRegion &visualRegion)
void setHoverIndex (const QPersistentModelIndex &index)
bool shouldAutoScroll (const QPoint &pos) const
bool shouldEdit (QAbstractItemView::EditTrigger trigger, const QModelIndex &index) const
bool shouldForwardEvent (QAbstractItemView::EditTrigger trigger, const QEvent *event) const
void startAutoScroll ()
void stopAutoScroll ()
void updateDirtyRegion ()
void updateEditorData (const QModelIndex &topLeft, const QModelIndex &bottomRight)
QStyleOptionViewItemV4 viewOptionsV4 () const
virtual ~QAbstractItemViewPrivate ()
Public Functions inherited from QAbstractScrollAreaPrivate
void _q_hslide (int)
void _q_showOrHideScrollBars ()
void _q_vslide (int)
void init ()
void layoutChildren ()
QAbstractScrollAreaPrivate ()
void replaceScrollBar (QScrollBar *scrollBar, Qt::Orientation orientation)
virtual void scrollBarPolicyChanged (Qt::Orientation, Qt::ScrollBarPolicy)
void setSingleFingerPanEnabled (bool on=true)
bool viewportEvent (QEvent *event)
Public Functions inherited from QFramePrivate
void init ()
QFramePrivate ()
void updateFrameWidth ()
Updated the frameWidth parameter.
void updateStyledFrameWidths ()
Updates the frame widths from the style.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QSize cachedSizeHint
bool cascadingResizing
QHash< int, int > cascadingSectionSize
bool clickableSections
int contentsSections
Qt::Alignment defaultAlignment
int defaultSectionSize
QBasicTimer delayedResize
int firstCascadingSection
int firstPos
QHeaderView::ResizeMode globalResizeMode
QHash< int, int > hiddenSectionSize
bool highlightSelected
int hover
int lastCascadingSection
int lastPos
int lastSectionSize
int length
QVector< int > logicalIndices
int minimumSectionSize
bool movableSections
int offset
Qt::Orientation orientation
int originalSize
QList< QPersistentModelIndex > persistentHiddenSections
int pressed
bool resizeRecursionBlock
int section
int sectionCount
QBitArray sectionHidden
QLabel * sectionIndicator
int sectionIndicatorOffset
QBitArray sectionSelected
QVector< SectionSpan > sectionSpans
Qt::SortOrder sortIndicatorOrder
int sortIndicatorSection
bool sortIndicatorShown
enum QHeaderViewPrivate::State state
bool stretchLastSection
int stretchSections
int target
QVector< int > visualIndices
Public Variables inherited from QAbstractItemViewPrivate
bool alternatingColors
bool autoScroll
int autoScrollCount
int autoScrollMargin
QBasicTimer autoScrollTimer
QMap< int, QPointer< QAbstractItemDelegate > > columnDelegates
QItemSelectionModel::SelectionFlag ctrlDragSelectionFlag
bool currentIndexSet
QWidget * currentlyCommittingEditor
Qt::DropAction defaultDropAction
QBasicTimer delayedAutoScroll
QBasicTimer delayedEditing
bool delayedPendingLayout
QBasicTimer delayedReset
QAbstractItemView::DragDropMode dragDropMode
bool dragEnabled
QAbstractItemView::DropIndicatorPosition dropIndicatorPosition
QRect dropIndicatorRect
QEditorIndexHash editorIndexHash
QAbstractItemView::EditTriggers editTriggers
QPersistentModelIndex enteredIndex
QAbstractItemView::ScrollMode horizontalScrollMode
QPersistentModelIndex hover
QSize iconSize
QIndexEditorHash indexEditorHash
QPointer< QAbstractItemDelegate > itemDelegate
QString keyboardInput
QElapsedTimer keyboardInputTime
QAbstractItemView::EditTrigger lastTrigger
QAbstractItemModel * model
bool moveCursorUpdatedView
bool noSelectionOnMousePress
bool overwrite
QSet< QWidget * > persistent
bool pressedAlreadySelected
QPersistentModelIndex pressedIndex
Qt::KeyboardModifiers pressedModifiers
QPoint pressedPosition
QPersistentModelIndex root
QMap< int, QPointer< QAbstractItemDelegate > > rowDelegates
QPoint scrollDelayOffset
QAbstractItemView::SelectionBehavior selectionBehavior
QAbstractItemView::SelectionMode selectionMode
QPointer< QItemSelectionModel > selectionModel
bool shouldClearStatusTip
bool shouldScrollToCurrentOnShow
bool showDropIndicator
QAbstractItemView::State state
QAbstractItemView::State stateBeforeAnimation
bool tabKeyNavigation
Qt::TextElideMode textElideMode
QRegion updateRegion
QBasicTimer updateTimer
QAbstractItemView::ScrollMode verticalScrollMode
bool viewportEnteredNeeded
bool wrapItemText
Public Variables inherited from QAbstractScrollAreaPrivate
int bottom
QRect cornerPaintingRect
QWidget * cornerWidget
QScrollBar * hbar
Qt::ScrollBarPolicy hbarpolicy
int left
QRect reverseCornerPaintingRect
int right
QAbstractScrollAreaScrollBarContainer * scrollBarContainers [Qt::Vertical+1]
bool singleFingerPanEnabled
int top
QScrollBar * vbar
Qt::ScrollBarPolicy vbarpolicy
QWidget * viewport
QScopedPointer< QObject > viewportFilter
int xoffset
int yoffset
Public Variables inherited from QFramePrivate
short bottomFrameWidth
int frameStyle
short frameWidth
QRect frect
short leftFrameWidth
short lineWidth
short midLineWidth
short rightFrameWidth
short topFrameWidth
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 66 of file qheaderview_p.h.
Enumerations
State
enum QHeaderViewPrivate::State
Enumerator
NoState
ResizeSection
MoveSection
SelectSections
NoClear
Definition at line 238 of file qheaderview_p.h.
 { NoState, ResizeSection, MoveSection, SelectSections, NoClear } state;
StateVersion
enum QHeaderViewPrivate::StateVersion
Enumerator
VersionMarker
Definition at line 71 of file qheaderview_p.h.
 { VersionMarker = 0xff };
Constructors and Destructors
QHeaderViewPrivate()
QHeaderViewPrivate::QHeaderViewPrivate () inline
Definition at line 73 of file qheaderview_p.h.
         : state(NoState),
           offset(0),
           sortIndicatorOrder(Qt::DescendingOrder),
           sortIndicatorSection(0),
           sortIndicatorShown(false),
           lastPos(-1),
           firstPos(-1),
           originalSize(-1),
           section(-1),
           target(-1),
           pressed(-1),
           hover(-1),
           length(0),
           sectionCount(0),
           movableSections(false),
           clickableSections(false),
           highlightSelected(false),
           stretchLastSection(false),
           cascadingResizing(false),
           resizeRecursionBlock(false),
           stretchSections(0),
           contentsSections(0),
           minimumSectionSize(-1),
           lastSectionSize(0),
           sectionIndicatorOffset(0),
           sectionIndicator(0),
           globalResizeMode(QHeaderView::Interactive)
     {}
Functions
_q_layoutAboutToBeChanged()
void QHeaderViewPrivate::_q_layoutAboutToBeChanged ()
Definition at line 1944 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     //if there is no row/column we can't have mapping for columns
     //because no QModelIndex in the model would be valid
     // ### this is far from being bullet-proof and we would need a real system to
     // ### map columns or rows persistently
     if ((orientation == Qt::Horizontal && model->rowCount(root) == 0)
         || model->columnCount(root) == 0)
         return;
     for (int i = 0; i < sectionHidden.count(); ++i)
         if (sectionHidden.testBit(i)) // ### note that we are using column or row 0
             persistentHiddenSections.append(orientation == Qt::Horizontal
                                             ? model->index(0, logicalIndex(i), root)
                                             : model->index(logicalIndex(i), 0, root));
 }
_q_layoutChanged()
void QHeaderViewPrivate::_q_layoutChanged () virtual
This slot is called when the layout is changed.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemViewPrivate.
Definition at line 1961 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     Q_Q(QHeaderView);
     viewport->update();
     if (persistentHiddenSections.isEmpty() || modelIsEmpty()) {
         if (modelSectionCount() != sectionCount)
             q->initializeSections();
         persistentHiddenSections.clear();
         return;
     }
     QBitArray oldSectionHidden = sectionHidden;
     bool sectionCountChanged = false;
     for (int i = 0; i < persistentHiddenSections.count(); ++i) {
         QModelIndex index = persistentHiddenSections.at(i);
         if (index.isValid()) {
             const int logical = (orientation == Qt::Horizontal
                                  ? index.column()
                                  : index.row());
             q->setSectionHidden(logical, true);
             oldSectionHidden.setBit(logical, false);
         } else if (!sectionCountChanged && (modelSectionCount() != sectionCount)) {
             sectionCountChanged = true;
             break;
         }
     }
     persistentHiddenSections.clear();
     for (int i = 0; i < oldSectionHidden.count(); ++i) {
         if (oldSectionHidden.testBit(i))
             q->setSectionHidden(i, false);
     }
     // the number of sections changed; we need to reread the state of the model
     if (sectionCountChanged)
         q->initializeSections();
 }
_q_sectionsRemoved()
void QHeaderViewPrivate::_q_sectionsRemoved (const QModelIndex & parent, int logicalFirst, int logicalLast)
Definition at line 1889 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     Q_Q(QHeaderView);
     if (parent != root)
         return; // we only handle changes in the top level
     if (qMin(logicalFirst, logicalLast) < 0
         || qMax(logicalLast, logicalFirst) >= sectionCount)
         return;
     int oldCount = q->count();
     int changeCount = logicalLast - logicalFirst + 1;
     updateHiddenSections(logicalFirst, logicalLast);
     if (visualIndices.isEmpty() && logicalIndices.isEmpty()) {
         //Q_ASSERT(headerSectionCount() == sectionCount);
         removeSectionsFromSpans(logicalFirst, logicalLast);
     } else {
         for (int l = logicalLast; l >= logicalFirst; --l) {
             int visual = visualIndices.at(l);
             for (int v = 0; v < sectionCount; ++v) {
                 if (v >= logicalIndices.count())
                     continue; // the section doesn't exist
                 if (v > visual) {
                     int logical = logicalIndices.at(v);
                     --(visualIndices[logical]);
                 }
                 if (logicalIndex(v) > l) // no need to move the positions before l
                     --(logicalIndices[v]);
             }
             logicalIndices.remove(visual);
             visualIndices.remove(l);
             //Q_ASSERT(headerSectionCount() == sectionCount);
             removeSectionsFromSpans(visual, visual);
         }
         // ### handle sectionSelection, sectionHidden
     }
     sectionCount -= changeCount;
     // update sorting column
     if (sortIndicatorSection >= logicalFirst) {
         if (sortIndicatorSection <= logicalLast)
             sortIndicatorSection = -1;
         else
             sortIndicatorSection -= changeCount;
     }
     // if we only have the last section (the "end" position) left, the header is empty
     if (sectionCount <= 0)
         clear();
     invalidateCachedSizeHint();
     emit q->sectionCountChanged(oldCount, q->count());
     viewport->update();
 }
adjustedVisualIndex()
int QHeaderViewPrivate::adjustedVisualIndex (int visualIndex) const
Definition at line 3667 of file qheaderview.cpp.
Referenced by sectionSpanIndex().
 {
     if (hiddenSectionSize.count() > 0) {
         int adjustedVisualIndex = visualIndex;
         int currentVisualIndex = 0;
         for (int i = 0; i < sectionSpans.count(); ++i) {
             if (sectionSpans.at(i).size == 0)
                 adjustedVisualIndex += sectionSpans.at(i).count;
             else
                 currentVisualIndex += sectionSpans.at(i).count;
             if (currentVisualIndex >= visualIndex)
                 break;
         }
         visualIndex = adjustedVisualIndex;
     }
     return visualIndex;
 }
cascadingResize()
void QHeaderViewPrivate::cascadingResize (int visual, int newSize)
Definition at line 3443 of file qheaderview.cpp.
Referenced by executePostedResize().
 {
     Q_Q(QHeaderView);
     const int minimumSize = q->minimumSectionSize();
     const int oldSize = headerSectionSize(visual);
     int delta = newSize - oldSize;
     if (delta > 0) { // larger
         bool sectionResized = false;
         // restore old section sizes
         for (int i = firstCascadingSection; i < visual; ++i) {
             if (cascadingSectionSize.contains(i)) {
                 int currentSectionSize = headerSectionSize(i);
                 int originalSectionSize = cascadingSectionSize.value(i);
                 if (currentSectionSize < originalSectionSize) {
                     int newSectionSize = currentSectionSize + delta;
                     resizeSectionSpan(i, currentSectionSize, newSectionSize);
                     if (newSectionSize >= originalSectionSize && false)
                         cascadingSectionSize.remove(i); // the section is now restored
                     sectionResized = true;
                     break;
                 }
             }
         }
         // resize the section
         if (!sectionResized) {
             newSize = qMax(newSize, minimumSize);
             if (oldSize != newSize)
                 resizeSectionSpan(visual, oldSize, newSize);
         }
         // cascade the section size change
         for (int i = visual + 1; i < sectionCount; ++i) {
             if (!sectionIsCascadable(i))
                 continue;
             int currentSectionSize = headerSectionSize(i);
             if (currentSectionSize <= minimumSize)
                 continue;
             int newSectionSize = qMax(currentSectionSize - delta, minimumSize);
             //qDebug() << "### cascading to" << i << newSectionSize - currentSectionSize << delta;
             resizeSectionSpan(i, currentSectionSize, newSectionSize);
             saveCascadingSectionSize(i, currentSectionSize);
             delta = delta - (currentSectionSize - newSectionSize);
             //qDebug() << "new delta" << delta;
             //if (newSectionSize != minimumSize)
             if (delta <= 0)
                 break;
         }
     } else { // smaller
         bool sectionResized = false;
         // restore old section sizes
         for (int i = lastCascadingSection; i > visual; --i) {
             if (!cascadingSectionSize.contains(i))
                 continue;
             int currentSectionSize = headerSectionSize(i);
             int originalSectionSize = cascadingSectionSize.value(i);
             if (currentSectionSize >= originalSectionSize)
                 continue;
             int newSectionSize = currentSectionSize - delta;
             resizeSectionSpan(i, currentSectionSize, newSectionSize);
             if (newSectionSize >= originalSectionSize && false) {
                 //qDebug() << "section" << i << "restored to" << originalSectionSize;
                 cascadingSectionSize.remove(i); // the section is now restored
             }
             sectionResized = true;
             break;
         }
         // resize the section
         resizeSectionSpan(visual, oldSize, qMax(newSize, minimumSize));
         // cascade the section size change
         if (delta < 0 && newSize < minimumSize) {
             for (int i = visual - 1; i >= 0; --i) {
                 if (!sectionIsCascadable(i))
                     continue;
                 int sectionSize = headerSectionSize(i);
                 if (sectionSize <= minimumSize)
                     continue;
                 resizeSectionSpan(i, sectionSize, qMax(sectionSize + delta, minimumSize));
                 saveCascadingSectionSize(i, sectionSize);
                 break;
             }
         }
         // let the next section get the space from the resized section
         if (!sectionResized) {
             for (int i = visual + 1; i < sectionCount; ++i) {
                 if (!sectionIsCascadable(i))
                     continue;
                 int currentSectionSize = headerSectionSize(i);
                 int newSectionSize = qMax(currentSectionSize - delta, minimumSize);
                 resizeSectionSpan(i, currentSectionSize, newSectionSize);
                 break;
             }
         }
     }
     if (hasAutoResizeSections())
         doDelayedResizeSections();
     viewport->update();
 }
clear()
void QHeaderViewPrivate::clear ()
Definition at line 3412 of file qheaderview.cpp.
Referenced by executePostedResize().
 {
     if (state != NoClear) {
     length = 0;
     sectionCount = 0;
     visualIndices.clear();
     logicalIndices.clear();
     sectionSelected.clear();
     sectionHidden.clear();
     hiddenSectionSize.clear();
     sectionSpans.clear();
     invalidateCachedSizeHint();
     }
 }
clearCascadingSections()
void QHeaderViewPrivate::clearCascadingSections () inline
Definition at line 195 of file qheaderview_p.h.
{
         firstCascadingSection = sectionCount;
         lastCascadingSection = 0;
         cascadingSectionSize.clear();
     }
columnIntersectsSelection()
bool QHeaderViewPrivate::columnIntersectsSelection (int column) const inline
Definition at line 120 of file qheaderview_p.h.
Referenced by sectionIntersectsSelection().
{
         return (selectionModel ? selectionModel->columnIntersectsSelection(column, root) : false);
     }
createSectionSpan()
void QHeaderViewPrivate::createSectionSpan (int start, int end, int size, QHeaderView::ResizeMode mode)
Definition at line 3237 of file qheaderview.cpp.
 {
     // ### the code for merging spans does not merge at all opertuneties
     // ### what if the number of sections is reduced ?
     SectionSpan span(size, (end - start) + 1, mode);
     int start_section = 0;
 #ifndef QT_NO_DEBUG
     int initial_section_count = headerSectionCount(); // ### debug code
 #endif
     QList<int> spansToRemove;
     for (int i = 0; i < sectionSpans.count(); ++i) {
         int end_section = start_section + sectionSpans.at(i).count - 1;
         int section_count = sectionSpans.at(i).count;
         if (start <= start_section && end > end_section) {
             // the existing span is entirely coveded by the new span
             spansToRemove.append(i);
         } else if (start < start_section && end >= end_section) {
             // the existing span is entirely coveded by the new span
             spansToRemove.append(i);
         } else if (start == start_section && end == end_section) {
             // the new span is covered by an existin span
             length -= sectionSpans.at(i).size;
             length += size;
             sectionSpans[i].size = size;
             sectionSpans[i].resizeMode = mode;
             // ### check if we can merge the section with any of its neighbours
             removeSpans(spansToRemove);
             Q_ASSERT(initial_section_count == headerSectionCount());
             return;
         } else if (start > start_section && end < end_section) {
             if (sectionSpans.at(i).sectionSize() == span.sectionSize()
                 && sectionSpans.at(i).resizeMode == span.resizeMode) {
                 Q_ASSERT(initial_section_count == headerSectionCount());
                 return;
             }
             // the new span is in the middle of the old span, so we have to split it
             length -= sectionSpans.at(i).size;
             int section_size = sectionSpans.at(i).sectionSize();
 #ifndef QT_NO_DEBUG
             int span_count = sectionSpans.at(i).count;
 #endif
             QHeaderView::ResizeMode span_mode = sectionSpans.at(i).resizeMode;
             // first span
             int first_span_count = start - start_section;
             int first_span_size = section_size * first_span_count;
             sectionSpans[i].count = first_span_count;
             sectionSpans[i].size = first_span_size;
             sectionSpans[i].resizeMode = span_mode;
             length += first_span_size;
             // middle span (the new span)
 #ifndef QT_NO_DEBUG
             int mid_span_count = span.count;
 #endif
             int mid_span_size = span.size;
             sectionSpans.insert(i + 1, span);
             length += mid_span_size;
             // last span
             int last_span_count = end_section - end;
             int last_span_size = section_size * last_span_count;
             sectionSpans.insert(i + 2, SectionSpan(last_span_size, last_span_count, span_mode));
             length += last_span_size;
             Q_ASSERT(span_count == first_span_count + mid_span_count + last_span_count);
             removeSpans(spansToRemove);
             Q_ASSERT(initial_section_count == headerSectionCount());
             return;
         } else if (start > start_section && start <= end_section && end >= end_section) {
             // the new span covers the last part of the existing span
             length -= sectionSpans.at(i).size;
             int removed_count = (end_section - start + 1);
             int span_count = sectionSpans.at(i).count - removed_count;
             int section_size = sectionSpans.at(i).sectionSize();
             int span_size = section_size * span_count;
             sectionSpans[i].count = span_count;
             sectionSpans[i].size = span_size;
             length += span_size;
             if (end == end_section) {
                 sectionSpans.insert(i + 1, span); // insert after
                 length += span.size;
                 removeSpans(spansToRemove);
                 Q_ASSERT(initial_section_count == headerSectionCount());
                 return;
             }
         } else if (end < end_section && end >= start_section && start <= start_section) {
             // the new span covers the first part of the existing span
             length -= sectionSpans.at(i).size;
             int removed_count = (end - start_section + 1);
             int section_size = sectionSpans.at(i).sectionSize();
             int span_count = sectionSpans.at(i).count - removed_count;
             int span_size = section_size * span_count;
             sectionSpans[i].count = span_count;
             sectionSpans[i].size = span_size;
             length += span_size;
             sectionSpans.insert(i, span); // insert before
             length += span.size;
             removeSpans(spansToRemove);
             Q_ASSERT(initial_section_count == headerSectionCount());
             return;
         }
         start_section += section_count;
     }
     // ### adding and removing _ sections_  in addition to spans
     // ### add some more checks here
     if (spansToRemove.isEmpty()) {
         if (!sectionSpans.isEmpty()
             && sectionSpans.last().sectionSize() == span.sectionSize()
             && sectionSpans.last().resizeMode == span.resizeMode) {
             length += span.size;
             int last = sectionSpans.count() - 1;
             sectionSpans[last].count += span.count;
             sectionSpans[last].size += span.size;
             sectionSpans[last].resizeMode = span.resizeMode;
         } else {
             length += span.size;
             sectionSpans.append(span);
         }
     } else {
         removeSpans(spansToRemove);
         length += span.size;
         sectionSpans.insert(spansToRemove.first(), span);
         //Q_ASSERT(initial_section_count == headerSectionCount());
     }
 }
doDelayedResizeSections()
void QHeaderViewPrivate::doDelayedResizeSections () inline
Definition at line 223 of file qheaderview_p.h.
{
         if (!delayedResize.isActive())
             delayedResize.start(0, q_func());
     }
executePostedResize()
void QHeaderViewPrivate::executePostedResize () const inline
Definition at line 228 of file qheaderview_p.h.
{
         if (delayedResize.isActive() && state == NoState) {
             const_cast<QHeaderView*>(q_func())->resizeSections();
         }
     }
flipSortIndicator()
void QHeaderViewPrivate::flipSortIndicator (int section)
Definition at line 3427 of file qheaderview.cpp.
Referenced by executePostedResize().
 {
     Q_Q(QHeaderView);
     Qt::SortOrder sortOrder;
     if (sortIndicatorSection == section) {
         sortOrder = (sortIndicatorOrder == Qt::DescendingOrder) ? Qt::AscendingOrder : Qt::DescendingOrder;
     } else {
         const QVariant value = model->headerData(section, orientation, Qt::InitialSortOrderRole);
         if (value.canConvert(QVariant::Int))
             sortOrder = static_cast<Qt::SortOrder>(value.toInt());
         else
             sortOrder = Qt::AscendingOrder;
     }
     q->setSortIndicator(section, sortOrder);
 }
getStyleOption()
QStyleOptionHeader QHeaderViewPrivate::getStyleOption () const
Referenced by hasAutoResizeSections().
hasAutoResizeSections()
bool QHeaderViewPrivate::hasAutoResizeSections () const inline
Definition at line 173 of file qheaderview_p.h.
{
         return stretchSections || stretchLastSection || contentsSections;
     }
headerLength()
int QHeaderViewPrivate::headerLength () const inline
Definition at line 317 of file qheaderview_p.h.
                                     { // for debugging
         int len = 0;
         for (int i = 0; i < sectionSpans.count(); ++i)
             len += sectionSpans.at(i).size;
         return len;
     }
headerSectionCount()
int QHeaderViewPrivate::headerSectionCount () const inline
Definition at line 310 of file qheaderview_p.h.
                                           { // for debugging
         int count = 0;
         for (int i = 0; i < sectionSpans.count(); ++i)
             count += sectionSpans.at(i).count;
         return count;
     }
headerSectionPosition()
int QHeaderViewPrivate::headerSectionPosition (int visual) const
Definition at line 3597 of file qheaderview.cpp.
Referenced by sectionSpanIndex().
 {
     // ### stupid iteration
     int section_start = 0;
     int span_position = 0;
     const int sectionSpansCount = sectionSpans.count();
     for (int i = 0; i < sectionSpansCount; ++i) {
         const QHeaderViewPrivate::SectionSpan &currentSection = sectionSpans.at(i);
         int section_end = section_start + currentSection.count - 1;
         if (visual >= section_start && visual <= section_end)
             return span_position + (visual - section_start) * currentSection.sectionSize();
         section_start = section_end + 1;
         span_position += currentSection.size;
     }
     return -1;
 }
headerSectionResizeMode()
QHeaderView::ResizeMode QHeaderViewPrivate::headerSectionResizeMode (int visual) const
Definition at line 3642 of file qheaderview.cpp.
Referenced by sectionIsCascadable(), and sectionSpanIndex().
 {
     int span = sectionSpanIndex(visual);
     if (span == -1)
         return globalResizeMode;
     return sectionSpans.at(span).resizeMode;
 }
headerSectionSize()
int QHeaderViewPrivate::headerSectionSize (int visual) const
Definition at line 3582 of file qheaderview.cpp.
Referenced by sectionSpanIndex().
 {
     // ### stupid iteration
     int section_start = 0;
     const int sectionSpansCount = sectionSpans.count();
     for (int i = 0; i < sectionSpansCount; ++i) {
         const QHeaderViewPrivate::SectionSpan &currentSection = sectionSpans.at(i);
         int section_end = section_start + currentSection.count - 1;
         if (visual >= section_start && visual <= section_end)
             return currentSection.sectionSize();
         section_start = section_end + 1;
     }
     return -1;
 }
headerVisualIndexAt()
int QHeaderViewPrivate::headerVisualIndexAt (int position) const
Definition at line 3614 of file qheaderview.cpp.
Referenced by sectionSpanIndex().
 {
     // ### stupid iteration
     int span_start_section = 0;
     int span_position = 0;
     const int sectionSpansCount = sectionSpans.count();
     for (int i = 0; i < sectionSpansCount; ++i) {
         const QHeaderViewPrivate::SectionSpan &currentSection = sectionSpans.at(i);
         int next_span_start_section = span_start_section + currentSection.count;
         int next_span_position = span_position + currentSection.size;
         if (position == span_position && currentSection.size > 0)
             return span_start_section;
         if (position > span_position && position < next_span_position) {
             int position_in_span = position - span_position;
             return span_start_section + (position_in_span / currentSection.sectionSize());
         }
         span_start_section = next_span_start_section;
         span_position = next_span_position;
     }
     return -1;
 }
initializeIndexMapping()
void QHeaderViewPrivate::initializeIndexMapping () const inline
Definition at line 183 of file qheaderview_p.h.
{
         if (visualIndices.count() != sectionCount
             || logicalIndices.count() != sectionCount) {
             visualIndices.resize(sectionCount);
             logicalIndices.resize(sectionCount);
             for (int s = 0; s < sectionCount; ++s) {
                 visualIndices[s] = s;
                 logicalIndices[s] = s;
             }
         }
     }
invalidateCachedSizeHint()
void QHeaderViewPrivate::invalidateCachedSizeHint () const inline
Definition at line 179 of file qheaderview_p.h.
{
         cachedSizeHint = QSize();
     }
isColumnSelected()
bool QHeaderViewPrivate::isColumnSelected (int column) const inline
Definition at line 132 of file qheaderview_p.h.
{
         return (selectionModel ? selectionModel->isColumnSelected(column, root) : false);
     }
isRowSelected()
bool QHeaderViewPrivate::isRowSelected (int row) const inline
Definition at line 128 of file qheaderview_p.h.
{
         return (selectionModel ? selectionModel->isRowSelected(row, root) : false);
     }
isSectionSelected()
bool QHeaderViewPrivate::isSectionSelected (int section) const
Definition at line 3059 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     int i = section * 2;
     if (i < 0 || i >= sectionSelected.count())
         return false;
     if (sectionSelected.testBit(i)) // if the value was cached
         return sectionSelected.testBit(i + 1);
     bool s = false;
     if (orientation == Qt::Horizontal)
         s = isColumnSelected(section);
     else
         s = isRowSelected(section);
     sectionSelected.setBit(i + 1, s); // selection state
     sectionSelected.setBit(i, true); // cache state
     return s;
 }
isVisualIndexHidden()
bool QHeaderViewPrivate::isVisualIndexHidden (int visual) const inline
Definition at line 165 of file qheaderview_p.h.
{
         return !sectionHidden.isEmpty() && sectionHidden.at(visual);
     }
lastVisibleVisualIndex()
int QHeaderViewPrivate::lastVisibleVisualIndex () const
Returns the last visible (ie.
Warning
This function is not part of the public interface. not hidden) visual index
Definition at line 3083 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     Q_Q(const QHeaderView);
     for (int visual = q->count()-1; visual >= 0; --visual) {
         if (!q->isSectionHidden(q->logicalIndex(visual)))
             return visual;
     }
     //default value if no section is actually visible
     return -1;
 }
logicalIndex()
int QHeaderViewPrivate::logicalIndex (int visualIndex) const inline
Definition at line 148 of file qheaderview_p.h.
Referenced by visualIndex().
{
         return logicalIndices.isEmpty() ? visualIndex : logicalIndices.at(visualIndex);
     }
modelIsEmpty()
bool QHeaderViewPrivate::modelIsEmpty () const inline
Definition at line 219 of file qheaderview_p.h.
{
         return (model->rowCount(root) == 0 || model->columnCount(root) == 0);
     }
modelSectionCount()
int QHeaderViewPrivate::modelSectionCount () const inline
Definition at line 213 of file qheaderview_p.h.
{
         return (orientation == Qt::Horizontal
                 ? model->columnCount(root)
                 : model->rowCount(root));
     }
prepareSectionSelected()
void QHeaderViewPrivate::prepareSectionSelected () inline
Definition at line 136 of file qheaderview_p.h.
{
         if (!selectionModel || !selectionModel->hasSelection())
             sectionSelected.clear();
         else if (sectionSelected.count() != sectionCount * 2)
             sectionSelected.fill(false, sectionCount * 2);
         else sectionSelected.fill(false);
     }
read()
bool QHeaderViewPrivate::read (QDataStream & in)
Definition at line 3717 of file qheaderview.cpp.
 {
     int orient, order, align, global;
     in >> orient;
     orientation = (Qt::Orientation)orient;
     in >> order;
     sortIndicatorOrder = (Qt::SortOrder)order;
     in >> sortIndicatorSection;
     in >> sortIndicatorShown;
     in >> visualIndices;
     in >> logicalIndices;
     in >> sectionHidden;
     in >> hiddenSectionSize;
     in >> length;
     in >> sectionCount;
     in >> movableSections;
     in >> clickableSections;
     in >> highlightSelected;
     in >> stretchLastSection;
     in >> cascadingResizing;
     in >> stretchSections;
     in >> contentsSections;
     in >> defaultSectionSize;
     in >> minimumSectionSize;
     in >> align;
     defaultAlignment = Qt::Alignment(align);
     in >> global;
     globalResizeMode = (QHeaderView::ResizeMode)global;
     in >> sectionSpans;
     return true;
 }
removeSectionsFromSpans()
void QHeaderViewPrivate::removeSectionsFromSpans (int start, int end)
Definition at line 3364 of file qheaderview.cpp.
 {
     // remove sections
     int start_section = 0;
     QList<int> spansToRemove;
     for (int i = 0; i < sectionSpans.count(); ++i) {
         int end_section = start_section + sectionSpans.at(i).count - 1;
         int section_size = sectionSpans.at(i).sectionSize();
         int section_count = sectionSpans.at(i).count;
         if (start <= start_section && end >= end_section) {
             // the change covers the entire span
             spansToRemove.append(i);
             if (end == end_section)
                 break;
         } else if (start > start_section && end < end_section) {
             // all the removed sections are inside the span
             int change = (end - start + 1);
             sectionSpans[i].count -= change;
             sectionSpans[i].size = section_size * sectionSpans.at(i).count;
             length -= (change * section_size);
             break;
         } else if (start >= start_section && start <= end_section) {
             // the some of the removed sections are inside the span,at the end
             int change = qMin(end_section - start + 1, end - start + 1);
             sectionSpans[i].count -= change;
             sectionSpans[i].size = section_size * sectionSpans.at(i).count;
             start += change;
             length -= (change * section_size);
             // the change affects several spans
         } else if (end >= start_section && end <= end_section) {
             // the some of the removed sections are inside the span, at the beginning
             int change = qMin((end - start_section + 1), end - start + 1);
             sectionSpans[i].count -= change;
             sectionSpans[i].size = section_size * sectionSpans.at(i).count;
             length -= (change * section_size);
             break;
         }
         start_section += section_count;
     }
     for (int i = spansToRemove.count() - 1; i >= 0; --i) {
         int s = spansToRemove.at(i);
         length -= sectionSpans.at(s).size;
         sectionSpans.remove(s);
         // ### merge remaining spans
     }
 }
removeSpans()
void QHeaderViewPrivate::removeSpans (const QList< int > & spans) inline
Definition at line 324 of file qheaderview_p.h.
{
         for (int i = spans.count() - 1; i >= 0; --i) {
             length -= sectionSpans.at(spans.at(i)).size;
             sectionSpans.remove(spans.at(i));
         }
     }
resizeSections()
void QHeaderViewPrivate::resizeSections (QHeaderView::ResizeMode globalMode, bool useGlobalMode = false)
Go through and resize all of the sections applying stretchLastSection, manualy stretches, sizes, and useGlobalMode.
Warning
This function is not part of the public interface.
The different resize modes are: Interactive - the user decides the size Stretch - take up whatever space is left Fixed - the size is set programmatically outside the header ResizeToContentes - the size is set based on the contents of the row or column in the parent view
The resize mode will not affect the last section if stretchLastSection is true.
Definition at line 3111 of file qheaderview.cpp.
Referenced by executePostedResize(), and QHeaderViewPrivate().
 {
     Q_Q(QHeaderView);
     //stop the timer in case it is delayed
     delayedResize.stop();
     executePostedLayout();
     if (sectionCount == 0)
         return;
     if (resizeRecursionBlock)
         return;
     resizeRecursionBlock = true;
     invalidateCachedSizeHint();
     const int lastVisibleSection = lastVisibleVisualIndex();
     // find stretchLastSection if we have it
     int stretchSection = -1;
     if (stretchLastSection && !useGlobalMode)
         stretchSection = lastVisibleVisualIndex();
     // count up the number of strected sections and how much space left for them
     int lengthToStrech = (orientation == Qt::Horizontal ? viewport->width() : viewport->height());
     int numberOfStretchedSections = 0;
     QList<int> section_sizes;
     for (int i = 0; i < sectionCount; ++i) {
         if (isVisualIndexHidden(i))
             continue;
         QHeaderView::ResizeMode resizeMode;
         if (useGlobalMode && (i != stretchSection))
             resizeMode = globalMode;
         else
             resizeMode = (i == stretchSection ? QHeaderView::Stretch : headerSectionResizeMode(i));
         if (resizeMode == QHeaderView::Stretch) {
             ++numberOfStretchedSections;
             section_sizes.append(headerSectionSize(i));
             continue;
         }
         // because it isn't stretch, determine its width and remove that from lengthToStrech
         int sectionSize = 0;
         if (resizeMode == QHeaderView::Interactive || resizeMode == QHeaderView::Fixed) {
             sectionSize = headerSectionSize(i);
         } else { // resizeMode == QHeaderView::ResizeToContents
             int logicalIndex = q->logicalIndex(i);
             sectionSize = qMax(viewSectionSizeHint(logicalIndex),
                                q->sectionSizeHint(logicalIndex));
         }
         section_sizes.append(sectionSize);
         lengthToStrech -= sectionSize;
     }
     // calculate the new length for all of the stretched sections
     int stretchSectionLength = -1;
     int pixelReminder = 0;
     if (numberOfStretchedSections > 0 && lengthToStrech > 0) { // we have room to stretch in
         int hintLengthForEveryStretchedSection = lengthToStrech / numberOfStretchedSections;
         stretchSectionLength = qMax(hintLengthForEveryStretchedSection, q->minimumSectionSize());
         pixelReminder = lengthToStrech % numberOfStretchedSections;
     }
     int spanStartSection = 0;
     int previousSectionLength = 0;
     QHeaderView::ResizeMode previousSectionResizeMode = QHeaderView::Interactive;
     // resize each section along the total length
     for (int i = 0; i < sectionCount; ++i) {
         int oldSectionLength = headerSectionSize(i);
         int newSectionLength = -1;
         QHeaderView::ResizeMode newSectionResizeMode = headerSectionResizeMode(i);
         if (isVisualIndexHidden(i)) {
             newSectionLength = 0;
         } else {
             QHeaderView::ResizeMode resizeMode;
             if (useGlobalMode)
                 resizeMode = globalMode;
             else
                 resizeMode = (i == stretchSection
                               ? QHeaderView::Stretch
                               : newSectionResizeMode);
             if (resizeMode == QHeaderView::Stretch && stretchSectionLength != -1) {
                 if (i == lastVisibleSection)
                     newSectionLength = qMax(stretchSectionLength, lastSectionSize);
                 else
                     newSectionLength = stretchSectionLength;
                 if (pixelReminder > 0) {
                     newSectionLength += 1;
                     --pixelReminder;
                 }
                 section_sizes.removeFirst();
             } else {
                 newSectionLength = section_sizes.front();
                 section_sizes.removeFirst();
             }
         }
         //Q_ASSERT(newSectionLength > 0);
         if ((previousSectionResizeMode != newSectionResizeMode
             || previousSectionLength != newSectionLength) && i > 0) {
             int spanLength = (i - spanStartSection) * previousSectionLength;
             createSectionSpan(spanStartSection, i - 1, spanLength, previousSectionResizeMode);
             //Q_ASSERT(headerLength() == length);
             spanStartSection = i;
         }
         if (newSectionLength != oldSectionLength)
             emit q->sectionResized(logicalIndex(i), oldSectionLength, newSectionLength);
         previousSectionLength = newSectionLength;
         previousSectionResizeMode = newSectionResizeMode;
     }
     createSectionSpan(spanStartSection, sectionCount - 1,
                       (sectionCount - spanStartSection) * previousSectionLength,
                       previousSectionResizeMode);
     //Q_ASSERT(headerLength() == length);
     resizeRecursionBlock = false;
     viewport->update();
 }
resizeSectionSpan()
void QHeaderViewPrivate::resizeSectionSpan (int visualIndex, int oldSize, int newSize)
Definition at line 3574 of file qheaderview.cpp.
 {
     Q_Q(QHeaderView);
     QHeaderView::ResizeMode mode = headerSectionResizeMode(visualIndex);
     createSectionSpan(visualIndex, visualIndex, newSize, mode);
     emit q->sectionResized(logicalIndex(visualIndex), oldSize, newSize);
 }
reverse()
bool QHeaderViewPrivate::reverse () const inline
Definition at line 144 of file qheaderview_p.h.
{
         return orientation == Qt::Horizontal && q_func()->isRightToLeft();
     }
rowIntersectsSelection()
bool QHeaderViewPrivate::rowIntersectsSelection (int row) const inline
Definition at line 116 of file qheaderview_p.h.
Referenced by sectionIntersectsSelection().
{
         return (selectionModel ? selectionModel->rowIntersectsSelection(row, root) : false);
     }
saveCascadingSectionSize()
void QHeaderViewPrivate::saveCascadingSectionSize (int visual, int size) inline
Definition at line 201 of file qheaderview_p.h.
{
         if (!cascadingSectionSize.contains(visual)) {
             cascadingSectionSize.insert(visual, size);
             firstCascadingSection = qMin(firstCascadingSection, visual);
             lastCascadingSection = qMax(lastCascadingSection, visual);
         }
     }
sectionHandleAt()
int QHeaderViewPrivate::sectionHandleAt (int position)
Definition at line 2961 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     Q_Q(QHeaderView);
     int visual = q->visualIndexAt(position);
     if (visual == -1)
         return -1;
     int log = logicalIndex(visual);
     int pos = q->sectionViewportPosition(log);
     int grip = q->style()->pixelMetric(QStyle::PM_HeaderGripMargin, 0, q);
     bool atLeft = position < pos + grip;
     bool atRight = (position > pos + q->sectionSize(log) - grip);
     if (reverse())
         qSwap(atLeft, atRight);
     if (atLeft) {
         //grip at the beginning of the section
         while(visual > -1) {
             int logical = q->logicalIndex(--visual);
             if (!q->isSectionHidden(logical))
                 return logical;
         }
     } else if (atRight) {
         //grip at the end of the section
         return log;
     }
     return -1;
 }
sectionIntersectsSelection()
bool QHeaderViewPrivate::sectionIntersectsSelection (int logical) const inline
Definition at line 124 of file qheaderview_p.h.
{
         return (orientation == Qt::Horizontal ? columnIntersectsSelection(logical) : rowIntersectsSelection(logical));
     }
sectionIsCascadable()
bool QHeaderViewPrivate::sectionIsCascadable (int visual) const inline
Definition at line 209 of file qheaderview_p.h.
{
         return headerSectionResizeMode(visual) == QHeaderView::Interactive;
     }
sectionSpanIndex()
int QHeaderViewPrivate::sectionSpanIndex (int visual) const inline
Definition at line 331 of file qheaderview_p.h.
{
         int section_start = 0;
         for (int i = 0; i < sectionSpans.count(); ++i) {
             int section_end = section_start + sectionSpans.at(i).count - 1;
             if (visual >= section_start && visual <= section_end)
                 return i;
             section_start = section_end + 1;
         }
         return -1;
     }
setDefaultSectionSize()
void QHeaderViewPrivate::setDefaultSectionSize (int size)
Definition at line 3551 of file qheaderview.cpp.
 {
     Q_Q(QHeaderView);
     defaultSectionSize = size;
     int currentVisualIndex = 0;
     for (int i = 0; i < sectionSpans.count(); ++i) {
         QHeaderViewPrivate::SectionSpan &span = sectionSpans[i];
         if (span.size > 0) {
             //we resize it if it is not hidden (ie size > 0)
             const int newSize = span.count * size;
             if (newSize != span.size) {
                 length += newSize - span.size; //the whole length is changed
                 const int oldSectionSize = span.sectionSize();
                 span.size = span.count * size;
                 for (int i = currentVisualIndex; i < currentVisualIndex + span.count; ++i) {
                     emit q->sectionResized(logicalIndex(i), oldSectionSize, size);
                 }
             }
         }
         currentVisualIndex += span.count;
     }
 }
setDefaultValues()
void QHeaderViewPrivate::setDefaultValues (Qt::Orientation o) inline
Definition at line 156 of file qheaderview_p.h.
{
         orientation = o;
         defaultSectionSize = (o == Qt::Horizontal ? 100
                               : qMax(q_func()->minimumSectionSize(), 30));
         defaultAlignment = (o == Qt::Horizontal
                             ? Qt::Alignment(Qt::AlignCenter)
                             : Qt::AlignLeft|Qt::AlignVCenter);
     }
setGlobalHeaderResizeMode()
void QHeaderViewPrivate::setGlobalHeaderResizeMode (QHeaderView::ResizeMode mode)
Definition at line 3650 of file qheaderview.cpp.
Referenced by sectionSpanIndex().
 {
     globalResizeMode = mode;
     for (int i = 0; i < sectionSpans.count(); ++i)
         sectionSpans[i].resizeMode = mode;
 }
setHeaderSectionResizeMode()
void QHeaderViewPrivate::setHeaderSectionResizeMode (int visual, QHeaderView::ResizeMode mode)
Definition at line 3636 of file qheaderview.cpp.
Referenced by sectionSpanIndex().
 {
     int size = headerSectionSize(visual);
     createSectionSpan(visual, visual, size, mode);
 }
setupSectionIndicator()
void QHeaderViewPrivate::setupSectionIndicator (int section, int position)
Definition at line 2990 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     Q_Q(QHeaderView);
     if (!sectionIndicator) {
         sectionIndicator = new QLabel(viewport);
     }
     int w, h;
     int p = q->sectionViewportPosition(section);
     if (orientation == Qt::Horizontal) {
         w = q->sectionSize(section);
         h = viewport->height();
     } else {
         w = viewport->width();
         h = q->sectionSize(section);
     }
     sectionIndicator->resize(w, h);
     QPixmap pm(w, h);
     pm.fill(QColor(0, 0, 0, 45));
     QRect rect(0, 0, w, h);
     QPainter painter(&pm);
     painter.setOpacity(0.75);
     q->paintSection(&painter, rect, section);
     painter.end();
     sectionIndicator->setPixmap(pm);
     sectionIndicatorOffset = position - qMax(p, 0);
 }
setVisualIndexHidden()
void QHeaderViewPrivate::setVisualIndexHidden (int visual, bool hidden) inline
Definition at line 169 of file qheaderview_p.h.
{
         if (!sectionHidden.isEmpty()) sectionHidden.setBit(visual, hidden);
     }
updateHiddenSections()
void QHeaderViewPrivate::updateHiddenSections (int logicalFirst, int logicalLast)
Definition at line 1860 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     Q_Q(QHeaderView);
     const int changeCount = logicalLast - logicalFirst + 1;
     // remove sections from hiddenSectionSize
     QHash<int, int> newHiddenSectionSize; // from logical index to section size
     for (int i = 0; i < logicalFirst; ++i)
         if (q->isSectionHidden(i))
             newHiddenSectionSize[i] = hiddenSectionSize[i];
     for (int j = logicalLast + 1; j < sectionCount; ++j)
         if (q->isSectionHidden(j))
             newHiddenSectionSize[j - changeCount] = hiddenSectionSize[j];
     hiddenSectionSize = newHiddenSectionSize;
     // remove sections from sectionsHidden
     if (!sectionHidden.isEmpty()) {
         const int newsize = qMin(sectionCount - changeCount, sectionHidden.size());
         QBitArray newSectionHidden(newsize);
         for (int j = 0, k = 0; j < sectionHidden.size(); ++j) {
             const int logical = logicalIndex(j);
             if (logical < logicalFirst || logical > logicalLast) {
                 newSectionHidden[k++] = sectionHidden[j];
             }
         }
         sectionHidden = newSectionHidden;
     }
 }
updateSectionIndicator()
void QHeaderViewPrivate::updateSectionIndicator (int section, int position)
Definition at line 3021 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate().
 {
     if (!sectionIndicator)
         return;
     if (section == -1 || target == -1) {
         sectionIndicator->hide();
         return;
     }
     if (orientation == Qt::Horizontal)
         sectionIndicator->move(position - sectionIndicatorOffset, 0);
     else
         sectionIndicator->move(0, position - sectionIndicatorOffset);
     sectionIndicator->show();
 }
viewSectionSizeHint()
int QHeaderViewPrivate::viewSectionSizeHint (int logical) const
Definition at line 3657 of file qheaderview.cpp.
Referenced by sectionSpanIndex().
 {
     if (QAbstractItemView *view = qobject_cast<QAbstractItemView*>(parent)) {
         return (orientation == Qt::Horizontal
                 ? view->sizeHintForColumn(logical)
                 : view->sizeHintForRow(logical));
     }
     return 0;
 }
visualIndex()
int QHeaderViewPrivate::visualIndex (int logicalIndex) const inline
Definition at line 152 of file qheaderview_p.h.
Referenced by logicalIndex(), and sectionSpanIndex().
{
         return visualIndices.isEmpty() ? logicalIndex : visualIndices.at(logicalIndex);
     }
write()
void QHeaderViewPrivate::write (QDataStream & out) const
Definition at line 3686 of file qheaderview.cpp.
 {
     out << int(orientation);
     out << int(sortIndicatorOrder);
     out << sortIndicatorSection;
     out << sortIndicatorShown;
     out << visualIndices;
     out << logicalIndices;
     out << sectionHidden;
     out << hiddenSectionSize;
     out << length;
     out << sectionCount;
     out << movableSections;
     out << clickableSections;
     out << highlightSelected;
     out << stretchLastSection;
     out << cascadingResizing;
     out << stretchSections;
     out << contentsSections;
     out << defaultSectionSize;
     out << minimumSectionSize;
     out << int(defaultAlignment);
     out << int(globalResizeMode);
     out << sectionSpans;
 }
Properties
cachedSizeHint
QSize QHeaderViewPrivate::cachedSizeHint mutable
Definition at line 252 of file qheaderview_p.h.
Referenced by invalidateCachedSizeHint().
cascadingResizing
bool QHeaderViewPrivate::cascadingResizing
Definition at line 272 of file qheaderview_p.h.
cascadingSectionSize
QHash<int, int> QHeaderViewPrivate::cascadingSectionSize mutable
Definition at line 251 of file qheaderview_p.h.
Referenced by clearCascadingSections(), and saveCascadingSectionSize().
clickableSections
bool QHeaderViewPrivate::clickableSections
Definition at line 269 of file qheaderview_p.h.
contentsSections
int QHeaderViewPrivate::contentsSections
Definition at line 275 of file qheaderview_p.h.
Referenced by hasAutoResizeSections().
defaultAlignment
Qt::Alignment QHeaderViewPrivate::defaultAlignment
Definition at line 280 of file qheaderview_p.h.
Referenced by setDefaultValues().
defaultSectionSize
int QHeaderViewPrivate::defaultSectionSize
Definition at line 276 of file qheaderview_p.h.
Referenced by setDefaultValues().
delayedResize
QBasicTimer QHeaderViewPrivate::delayedResize mutable
Definition at line 253 of file qheaderview_p.h.
Referenced by doDelayedResizeSections(), and executePostedResize().
firstCascadingSection
int QHeaderViewPrivate::firstCascadingSection
Definition at line 255 of file qheaderview_p.h.
Referenced by clearCascadingSections(), and saveCascadingSectionSize().
firstPos
int QHeaderViewPrivate::firstPos
Definition at line 259 of file qheaderview_p.h.
globalResizeMode
QHeaderView::ResizeMode QHeaderViewPrivate::globalResizeMode
Definition at line 282 of file qheaderview_p.h.
hiddenSectionSize
QHash<int, int> QHeaderViewPrivate::hiddenSectionSize mutable
Definition at line 250 of file qheaderview_p.h.
highlightSelected
bool QHeaderViewPrivate::highlightSelected
Definition at line 270 of file qheaderview_p.h.
hover
int QHeaderViewPrivate::hover
Definition at line 264 of file qheaderview_p.h.
lastCascadingSection
int QHeaderViewPrivate::lastCascadingSection
Definition at line 256 of file qheaderview_p.h.
Referenced by clearCascadingSections(), and saveCascadingSectionSize().
lastPos
int QHeaderViewPrivate::lastPos
Definition at line 258 of file qheaderview_p.h.
lastSectionSize
int QHeaderViewPrivate::lastSectionSize
Definition at line 278 of file qheaderview_p.h.
length
int QHeaderViewPrivate::length
Definition at line 266 of file qheaderview_p.h.
logicalIndices
QVector<int> QHeaderViewPrivate::logicalIndices mutable
Definition at line 247 of file qheaderview_p.h.
Referenced by initializeIndexMapping(), and logicalIndex().
minimumSectionSize
int QHeaderViewPrivate::minimumSectionSize
Definition at line 277 of file qheaderview_p.h.
Referenced by setDefaultValues().
movableSections
bool QHeaderViewPrivate::movableSections
Definition at line 268 of file qheaderview_p.h.
offset
int QHeaderViewPrivate::offset
Definition at line 240 of file qheaderview_p.h.
orientation
Qt::Orientation QHeaderViewPrivate::orientation
Definition at line 241 of file qheaderview_p.h.
Referenced by modelSectionCount(), reverse(), sectionIntersectsSelection(), and setDefaultValues().
originalSize
int QHeaderViewPrivate::originalSize
Definition at line 260 of file qheaderview_p.h.
persistentHiddenSections
QList<QPersistentModelIndex> QHeaderViewPrivate::persistentHiddenSections
Definition at line 283 of file qheaderview_p.h.
pressed
int QHeaderViewPrivate::pressed
Definition at line 263 of file qheaderview_p.h.
resizeRecursionBlock
bool QHeaderViewPrivate::resizeRecursionBlock
Definition at line 273 of file qheaderview_p.h.
section
int QHeaderViewPrivate::section
Definition at line 261 of file qheaderview_p.h.
Referenced by QHeaderViewPrivate().
sectionCount
int QHeaderViewPrivate::sectionCount
Definition at line 267 of file qheaderview_p.h.
Referenced by clearCascadingSections(), initializeIndexMapping(), and prepareSectionSelected().
sectionHidden
QBitArray QHeaderViewPrivate::sectionHidden mutable
Definition at line 249 of file qheaderview_p.h.
Referenced by isVisualIndexHidden(), and setVisualIndexHidden().
sectionIndicator
QLabel* QHeaderViewPrivate::sectionIndicator
Definition at line 281 of file qheaderview_p.h.
sectionIndicatorOffset
int QHeaderViewPrivate::sectionIndicatorOffset
Definition at line 279 of file qheaderview_p.h.
sectionSelected
QBitArray QHeaderViewPrivate::sectionSelected mutable
Definition at line 248 of file qheaderview_p.h.
Referenced by prepareSectionSelected().
sectionSpans
QVector<SectionSpan> QHeaderViewPrivate::sectionSpans
Definition at line 303 of file qheaderview_p.h.
sortIndicatorOrder
Qt::SortOrder QHeaderViewPrivate::sortIndicatorOrder
Definition at line 242 of file qheaderview_p.h.
sortIndicatorSection
int QHeaderViewPrivate::sortIndicatorSection
Definition at line 243 of file qheaderview_p.h.
sortIndicatorShown
bool QHeaderViewPrivate::sortIndicatorShown
Definition at line 244 of file qheaderview_p.h.
state
enum QHeaderViewPrivate::State QHeaderViewPrivate::state
Referenced by executePostedResize().
stretchLastSection
bool QHeaderViewPrivate::stretchLastSection
Definition at line 271 of file qheaderview_p.h.
Referenced by hasAutoResizeSections().
stretchSections
int QHeaderViewPrivate::stretchSections
Definition at line 274 of file qheaderview_p.h.
Referenced by hasAutoResizeSections().
target
int QHeaderViewPrivate::target
Definition at line 262 of file qheaderview_p.h.
visualIndices
QVector<int> QHeaderViewPrivate::visualIndices mutable
Definition at line 246 of file qheaderview_p.h.
Referenced by initializeIndexMapping(), and visualIndex().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qheaderview_p.h
/src/gui/itemviews/qheaderview.cpp