Qt 4.8: FAREnforcer Class Reference
FAREnforcer Class Reference
Enforces the False Authentication Rate.
#include <qtransportauth_qws_p.h>
Public Functions
void logAuthAttempt (QDateTime time=QDateTime::currentDateTime())
void reset ()
Static Public Functions
static FAREnforcer * getInstance ()
Private Functions
FAREnforcer ()
FAREnforcer (const FAREnforcer &)
FAREnforcer & operator= (FAREnforcer const &)
Properties
QList< QDateTime > authAttempts
Static Private Attributes
static const QString FARMessage = QLatin1String("FAR_Exceeded")
static const int minute = 60
static const int minutelyRate = 4
static const QString SxeTag = QLatin1String("<SXE Breach>")
Detailed Description
Enforces the False Authentication Rate.
Warning
This function is not part of the public interface. If more than 4 authentications are received per minute the sxemonitor is notified that the FAR has been exceeded
Definition at line 169 of file qtransportauth_qws_p.h.
Constructors and Destructors
FAREnforcer() [1/2]
FAREnforcer::FAREnforcer () private
Definition at line 1518 of file qtransportauth_qws.cpp.
                         :authAttempts()
 {
     QDateTime nullDateTime = QDateTime();
     for (int i = 0; i < minutelyRate; i++ )
         authAttempts << nullDateTime;
 }
FAREnforcer() [2/2]
FAREnforcer::FAREnforcer (const FAREnforcer &) private
Functions
getInstance()
FAREnforcer * FAREnforcer::getInstance () static
Definition at line 1526 of file qtransportauth_qws.cpp.
Referenced by QTransportAuth::authFromMessage().
 {
     static FAREnforcer theInstance;
     return &theInstance;
 }
logAuthAttempt()
void FAREnforcer::logAuthAttempt (QDateTime time = QDateTime::currentDateTime())
Definition at line 1532 of file qtransportauth_qws.cpp.
Referenced by QTransportAuth::authFromMessage().
 {
     QDateTime dt =  authAttempts.takeFirst();
     authAttempts.append( time );
     if ( dt.secsTo( authAttempts.last() ) <= minute )
     {
 #if defined(SXE_DISCOVERY)
         if ( QTransportAuth::getInstance()->isDiscoveryMode() ) {
             static QBasicAtomicInt reported = Q_BASIC_ATOMIC_INITIALIZER(0);
             if ( reported.testAndSetRelaxed(0,1) ) {
 #ifndef QT_NO_TEXTSTREAM
                 QString logFilePath = QTransportAuth::getInstance()->logFilePath();
                 if ( !logFilePath.isEmpty() ) {
                       QFile log( logFilePath );
                     if ( !log.open(QIODevice::WriteOnly | QIODevice::Append) ) {
                         qWarning("Could not write to log in discovery mode: %s",
                                  qPrintable(logFilePath) );
                     } else {
                         QTextStream ts( &log );
                         ts << "\t\tWarning: False Authentication Rate of " <<  minutelyRate << "\n"
                            << "\t\tserver connections/authentications per minute has been exceeded,\n"
                            << "\t\tno further warnings will be issued\n";
                     }
                 }
             }
 #endif
             reset();
             return;
         }
 #endif
         syslog( LOG_ERR | LOG_LOCAL6, "%s %s",
                 qPrintable( FAREnforcer::SxeTag ),
                 qPrintable( FAREnforcer::FARMessage ) );
         reset();
     }
 }
operator=()
FAREnforcer& FAREnforcer::operator= (FAREnforcer const &) private
reset()
void FAREnforcer::reset ()
Definition at line 1570 of file qtransportauth_qws.cpp.
Referenced by logAuthAttempt().
 {
     QDateTime nullDateTime = QDateTime();
     for (int i = 0; i < minutelyRate; i++ )
         authAttempts[i] = nullDateTime;
 }
Properties
authAttempts
QList<QDateTime> FAREnforcer::authAttempts private
Definition at line 188 of file qtransportauth_qws_p.h.
Referenced by FAREnforcer(), logAuthAttempt(), and reset().
FARMessage
const QString FAREnforcer::FARMessage = QLatin1String("FAR_Exceeded") static private
Definition at line 183 of file qtransportauth_qws_p.h.
Referenced by hmac_md5().
minute
const int FAREnforcer::minute = 60 static private
Definition at line 186 of file qtransportauth_qws_p.h.
Referenced by hmac_md5(), and logAuthAttempt().
minutelyRate
const int FAREnforcer::minutelyRate = 4 static private
Definition at line 184 of file qtransportauth_qws_p.h.
Referenced by FAREnforcer(), hmac_md5(), logAuthAttempt(), and reset().
SxeTag
const QString FAREnforcer::SxeTag = QLatin1String("<SXE Breach>") static private
Definition at line 185 of file qtransportauth_qws_p.h.
Referenced by hmac_md5().
The documentation for this class was generated from the following files:
/src/gui/embedded/qtransportauth_qws_p.h
/src/gui/embedded/qtransportauth_qws.cpp