Qt 4.8: QGb18030Codec Class Reference
QGb18030Codec Class Reference
#include <qgb18030codec.h>
Public Functions
QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
QByteArray convertFromUnicode (const QChar *, int, ConverterState *) const
Reimplemented Function
QString convertToUnicode (const char *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
QGb18030Codec ()
Public Functions inherited from QTextCodec
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > _aliases ()
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
Note
This class or function is reentrant.
Warning
This function is not part of the public interface.
Definition at line 54 of file qgb18030codec.h.
Constructors and Destructors
QGb18030Codec()
QGb18030Codec::QGb18030Codec ()
Definition at line 83 of file qgb18030codec.cpp.
 {
 }
Functions
_aliases()
static QList<QByteArray> QGb18030Codec::_aliases () inline static
Definition at line 59 of file qgb18030codec.h.
Referenced by CNTextCodecs::aliases(), aliases(), QGbkCodec::aliases(), QFontGbkCodec::aliases(), QFontGb18030_0Codec::aliases(), and CNTextCodecs::createForName().
 { return QList<QByteArray>(); }
_mibEnum()
static int QGb18030Codec::_mibEnum () inline static
Definition at line 60 of file qgb18030codec.h.
Referenced by QGb2312Codec::_aliases(), QFontGb2312Codec::_aliases(), QFontGbkCodec::_aliases(), QFontGb18030_0Codec::_aliases(), CNTextCodecs::createForMib(), mibEnum(), QGbkCodec::mibEnum(), QGb2312Codec::mibEnum(), QFontGb2312Codec::mibEnum(), QFontGbkCodec::mibEnum(), QFontGb18030_0Codec::mibEnum(), and CNTextCodecs::mibEnums().
 { return 114; }
_name()
static QByteArray QGb18030Codec::_name () inline static
Definition at line 58 of file qgb18030codec.h.
Referenced by CNTextCodecs::createForName(), name(), QGbkCodec::name(), QGb2312Codec::name(), QFontGb2312Codec::name(), QFontGbkCodec::name(), QFontGb18030_0Codec::name(), and CNTextCodecs::names().
 { return "GB18030"; }
aliases()
QList<QByteArray> QGb18030Codec::aliases () const inline virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented from QTextCodec.
Reimplemented in QGbkCodec.
Definition at line 63 of file qgb18030codec.h.
 { return _aliases(); }
convertFromUnicode()
QByteArray QGb18030Codec::convertFromUnicode (const QChar * uc, int len, ConverterState * state) const virtual
Reimplemented Function
Implements QTextCodec.
Reimplemented in QGb2312Codec, and QGbkCodec.
Definition at line 88 of file qgb18030codec.cpp.
Referenced by mibEnum(), QGbkCodec::mibEnum(), QGb2312Codec::mibEnum(), QFontGb2312Codec::mibEnum(), QFontGbkCodec::mibEnum(), and QFontGb18030_0Codec::mibEnum().
 {
     char replacement = '?';
     int high = -1;
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = 0;
         if (state->remainingChars)
             high = state->state_data[0];
     }
     int invalid = 0;
     int rlen = 4 *len + 1;
     QByteArray rstr;
     rstr.resize(rlen);
     uchar* cursor = (uchar*)rstr.data();
     //qDebug("QGb18030Codec::fromUnicode(const QString& uc, int& lenInOut = %d)", lenInOut);
     for (int i = 0; i < len; i++) {
         unsigned short ch = uc[i].unicode();
         int len;
         uchar buf[4];
         if (high >= 0) {
             if (uc[i].isLowSurrogate()) {
                 // valid surrogate pair
                 ++i;
                 uint u = QChar::surrogateToUcs4(high, uc[i].unicode());
                 len = qt_UnicodeToGb18030(u, buf);
                 if (len >= 2) {
                     for (int j=0; j<len; j++)
                         *cursor++ = buf[j];
                 } else {
                     *cursor++ = replacement;
                     ++invalid;
                 }
                 high = -1;
                 continue;
             } else {
                 *cursor++ = replacement;
                 ++invalid;
                 high = -1;
             }
         }
         if (IsLatin(ch)) {
             // ASCII
             *cursor++ = ch;
         } else if (uc[i].isHighSurrogate()) {
             // surrogates area. check for correct encoding
             // we need at least one more character, first the high surrogate, then the low one
             high = ch;
         } else if ((len = qt_UnicodeToGb18030(ch, buf)) >= 2) {
             for (int j=0; j<len; j++)
                 *cursor++ = buf[j];
         } else {
             // Error
             *cursor++ = replacement;
             ++invalid;
         }
     }
     rstr.resize(cursor - (uchar*)rstr.constData());
     if (state) {
         state->invalidChars += invalid;
         state->state_data[0] = high;
         if (high)
             state->remainingChars = 1;
     }
     return rstr;
 }
convertToUnicode()
QString QGb18030Codec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Reimplemented in QGb2312Codec, and QGbkCodec.
Definition at line 159 of file qgb18030codec.cpp.
Referenced by mibEnum(), QGbkCodec::mibEnum(), QGb2312Codec::mibEnum(), QFontGb2312Codec::mibEnum(), QFontGbkCodec::mibEnum(), and QFontGb18030_0Codec::mibEnum().
 {
     uchar buf[4];
     int nbuf = 0;
     ushort replacement = QChar::ReplacementCharacter;
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = QChar::Null;
         nbuf = state->remainingChars;
         buf[0] = (state->state_data[0] >> 24) & 0xff;
         buf[1] = (state->state_data[0] >> 16) & 0xff;
         buf[2] = (state->state_data[0] >>  8) & 0xff;
         buf[3] = (state->state_data[0] >>  0) & 0xff;
     }
     int invalid = 0;
     QString result;
     result.resize(len);
     int unicodeLen = 0;
     ushort *const resultData = reinterpret_cast<ushort*>(result.data());
     //qDebug("QGb18030Decoder::toUnicode(const char* chars, int len = %d)", len);
     for (int i = 0; i < len; i++) {
         uchar ch = chars[i];
         switch (nbuf) {
         case 0:
             if (IsLatin(ch)) {
                 // ASCII
                 resultData[unicodeLen] = ch;
                 ++unicodeLen;
             } else if (Is1stByte(ch)) {
                 // GB18030?
                 buf[0] = ch;
                 nbuf = 1;
             } else {
                 // Invalid
                 resultData[unicodeLen] = replacement;
                 ++unicodeLen;
                 ++invalid;
             }
             break;
         case 1:
             // GB18030 2 bytes
             if (Is2ndByteIn2Bytes(ch)) {
                 buf[1] = ch;
                 int clen = 2;
                 uint u = qt_Gb18030ToUnicode(buf, clen);
                 if (clen == 2) {
                     resultData[unicodeLen] = qValidChar(static_cast<ushort>(u));
                     ++unicodeLen;
                 } else {
                     resultData[unicodeLen] = replacement;
                     ++unicodeLen;
                     ++invalid;
                 }
                 nbuf = 0;
             } else if (Is2ndByteIn4Bytes(ch)) {
                 buf[1] = ch;
                 nbuf = 2;
             } else {
                 // Error
                 resultData[unicodeLen] = replacement;
                 ++unicodeLen;
                 ++invalid;
                 nbuf = 0;
             }
             break;
         case 2:
             // GB18030 3 bytes
             if (Is3rdByte(ch)) {
                 buf[2] = ch;
                 nbuf = 3;
             } else {
                 resultData[unicodeLen] = replacement;
                 ++unicodeLen;
                 ++invalid;
                 nbuf = 0;
             }
             break;
         case 3:
             // GB18030 4 bytes
             if (Is4thByte(ch)) {
                 buf[3] = ch;
                 int clen = 4;
                 uint u = qt_Gb18030ToUnicode(buf, clen);
                 if (clen == 4) {
                     resultData[unicodeLen] = qValidChar(u);
                     ++unicodeLen;
                 } else {
                     resultData[unicodeLen] = replacement;
                     ++unicodeLen;
                     ++invalid;
                 }
             } else {
                 resultData[unicodeLen] = replacement;
                 ++unicodeLen;
                 ++invalid;
             }
             nbuf = 0;
             break;
         }
     }
     result.resize(unicodeLen);
     if (state) {
         state->remainingChars = nbuf;
         state->state_data[0] = (buf[0] << 24) + (buf[1] << 16) + (buf[2] << 8) + buf[3];
         state->invalidChars += invalid;
     }
     return result;
 }
mibEnum()
int QGb18030Codec::mibEnum () const inline virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implements QTextCodec.
Reimplemented in QGb2312Codec, and QGbkCodec.
Definition at line 64 of file qgb18030codec.h.
 { return _mibEnum(); }
name()
QByteArray QGb18030Codec::name () const inline virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implements QTextCodec.
Reimplemented in QGb2312Codec, and QGbkCodec.
Definition at line 62 of file qgb18030codec.h.
 { return _name(); }
The documentation for this class was generated from the following files:
/src/plugins/codecs/cn/qgb18030codec.h
/src/plugins/codecs/cn/qgb18030codec.cpp