Qt 4.8: QSet< T > Class Template Reference
QSet< T > Class Template Reference
#include <qdatastream.h>
Classes
class const_iterator
class iterator
Public Types
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef const_iterator ConstIterator
typedef qptrdiff difference_type
typedef iterator Iterator
typedef T key_type
typedef value_type * pointer
typedef value_type & reference
typedef int size_type
typedef T value_type
Public Functions
iterator begin ()
const_iterator begin () const
int capacity () const
void clear ()
const_iterator constBegin () const
const_iterator constEnd () const
const_iterator constFind (const T &value) const
bool contains (const T &value) const
bool contains (const QSet< T > &set) const
int count () const
void detach ()
bool empty () const
iterator end ()
const_iterator end () const
iterator erase (iterator i)
iterator find (const T &value)
const_iterator find (const T &value) const
const_iterator insert (const T &value)
QSet< T > & intersect (const QSet< T > &other)
bool isDetached () const
bool isEmpty () const
QSet< T > operator & (const QSet< T > &other) const
QSet< T > operator & (const QSet< T > &other)
QSet< T > & operator &= (const QSet< T > &other)
QSet< T > & operator &= (const T &value)
bool operator!= (const QSet< T > &other) const
QSet< T > operator+ (const QSet< T > &other) const
QSet< T > operator+ (const QSet< T > &other)
QSet< T > & operator+= (const QSet< T > &other)
QSet< T > & operator+= (const T &value)
QSet< T > operator- (const QSet< T > &other) const
QSet< T > operator- (const QSet< T > &other)
QSet< T > & operator-= (const QSet< T > &other)
QSet< T > & operator-= (const T &value)
QSet< T > & operator<< (const T &value)
QSet< T > & operator= (const QSet< T > &other)
bool operator== (const QSet< T > &other) const
QSet< T > operator| (const QSet< T > &other) const
QSet< T > operator| (const QSet< T > &other)
QSet< T > & operator|= (const QSet< T > &other)
QSet< T > & operator|= (const T &value)
QSet ()
QSet (const QSet< T > &other)
bool remove (const T &value)
void reserve (int size)
void setSharable (bool sharable)
int size () const
void squeeze ()
QSet< T > & subtract (const QSet< T > &other)
void swap (QSet< T > &other)
QList< T > toList () const
QSet< T > & unite (const QSet< T > &other)
QList< T > values () const
Static Public Functions
static QSet< T > fromList (const QList< T > &list)
Private Types
typedef QHash< T, QHashDummyValue > Hash
Properties
Hash q_hash
Detailed Description
template<class T>
class QSet< T >
Definition at line 65 of file qdatastream.h.
Typedefs
const_pointer
template<class T> typedef const value_type* QSet< T >::const_pointer
Definition at line 193 of file qset.h.
const_reference
template<class T> typedef const value_type& QSet< T >::const_reference
Definition at line 195 of file qset.h.
ConstIterator
template<class T> typedef const_iterator QSet< T >::ConstIterator
Definition at line 177 of file qset.h.
difference_type
template<class T> typedef qptrdiff QSet< T >::difference_type
Definition at line 196 of file qset.h.
Hash
template<class T> typedef QHash<T, QHashDummyValue> QSet< T >::Hash private
Definition at line 56 of file qset.h.
Iterator
template<class T> typedef iterator QSet< T >::Iterator
Definition at line 176 of file qset.h.
key_type
template<class T> typedef T QSet< T >::key_type
Definition at line 190 of file qset.h.
pointer
template<class T> typedef value_type* QSet< T >::pointer
Definition at line 192 of file qset.h.
reference
template<class T> typedef value_type& QSet< T >::reference
Definition at line 194 of file qset.h.
size_type
template<class T> typedef int QSet< T >::size_type
Definition at line 197 of file qset.h.
value_type
template<class T> typedef T QSet< T >::value_type
Definition at line 191 of file qset.h.
Constructors and Destructors
QSet() [1/2]
template<class T> QSet< T >::QSet () inline
Definition at line 59 of file qset.h.
 {}
QSet() [2/2]
template<class T> QSet< T >::QSet (const QSet< T > & other) inline
Definition at line 60 of file qset.h.
 : q_hash(other.q_hash) {}
Functions
begin() [1/2]
template<class T> iterator QSet< T >::begin () inline
Definition at line 166 of file qset.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QDeclarativeBindingCompilerPrivate::buildSignalTable(), QGestureManager::cancelGesturesForChildren(), QGraphicsScenePrivate::cancelGesturesForChildren(), ShaderEffectItem::connectPropertySignals(), GraphPath::constraint(), QDeclarativeOpenMetaObjectType::createProperty(), QGestureManager::deliverEvents(), QMutableSetIterator< T >::operator=(), QDeclarativeOpenMetaObjectType::propertyCreated(), QMutableSetIterator< T >::QMutableSetIterator(), Graph< AnchorVertex, AnchorData >::serializeToDot(), QMutableSetIterator< T >::toFront(), ShaderEffectItem::updateEffectState(), writeVariablesEnum(), and QDirectFBScreenPrivate::~QDirectFBScreenPrivate().
 { return q_hash.begin(); }
begin() [2/2]
template<class T> const_iterator QSet< T >::begin () const inline
Definition at line 167 of file qset.h.
 { return q_hash.begin(); }
capacity()
template<class T> int QSet< T >::capacity () const inline
Definition at line 79 of file qset.h.
 { return q_hash.capacity(); }
clear()
template<class T> void QSet< T >::clear () inline
Definition at line 87 of file qset.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QStateMachinePrivate::_q_start(), QWidgetBackingStoreTracker::destroy(), QScriptEnginePrivate::detachAllRegisteredScriptPrograms(), QDirectFBScreen::disconnect(), QStateMachinePrivate::enterStates(), QGestureManager::filterEventThroughContexts(), QGraphicsSceneBspTreeIndexPrivate::purgeRemovedItems(), QThreadPoolPrivate::reset(), ShaderEffectItem::reset(), QStateMachinePrivate::setError(), and QPatternist::OutputValidator::startElement().
 { q_hash.clear(); }
constBegin()
template<class T> const_iterator QSet< T >::constBegin () const inline
Definition at line 168 of file qset.h.
Referenced by QStateMachinePrivate::addStatesToEnter(), QScriptObjectSnapshot::capture(), QWizardPrivate::cleanupPagesNotInHistory(), QSet< typename TokenLookupClass::NodeName >::contains(), convertFlags(), QScriptEnginePrivate::detachAllRegisteredScriptPrograms(), QStateMachinePrivate::enterStates(), QStateMachinePrivate::exitStates(), QMutableSetIterator< T >::findPrevious(), QStateMachinePrivate::goToState(), QMutableSetIterator< T >::hasPrevious(), QSet< typename TokenLookupClass::NodeName >::intersect(), QStateMachinePrivate::isPreempted(), QStateMachinePrivate::selectTransitions(), QGraphicsAnchorLayoutPrivate::solveMinMax(), QSet< typename TokenLookupClass::NodeName >::subtract(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QSet< typename TokenLookupClass::NodeName >::toList(), QSet< typename TokenLookupClass::NodeName >::unite(), QApplication::~QApplication(), and QGL2PaintEngineExPrivate::~QGL2PaintEngineExPrivate().
 { return q_hash.constBegin(); }
constEnd()
template<class T> const_iterator QSet< T >::constEnd () const inline
Definition at line 171 of file qset.h.
Referenced by QStateMachinePrivate::addStatesToEnter(), QScriptObjectSnapshot::capture(), QWizardPrivate::cleanupPagesNotInHistory(), QSet< typename TokenLookupClass::NodeName >::contains(), convertFlags(), QScriptEnginePrivate::detachAllRegisteredScriptPrograms(), QStateMachinePrivate::enterStates(), QStateMachinePrivate::exitStates(), QMutableSetIterator< T >::findNext(), QStateMachinePrivate::goToState(), QMutableSetIterator< T >::hasNext(), QSet< typename TokenLookupClass::NodeName >::intersect(), QStateMachinePrivate::isPreempted(), QMutableSetIterator< T >::item_exists(), QMutableSetIterator< T >::remove(), QStateMachinePrivate::selectTransitions(), QGraphicsAnchorLayoutPrivate::solveMinMax(), QSet< typename TokenLookupClass::NodeName >::subtract(), QImageWriter::supportedImageFormats(), QImageReader::supportedImageFormats(), QSet< typename TokenLookupClass::NodeName >::toList(), QSet< typename TokenLookupClass::NodeName >::unite(), and QApplication::~QApplication().
 { return q_hash.constEnd(); }
constFind()
template<class T> const_iterator QSet< T >::constFind (const T & value) const inline
Definition at line 184 of file qset.h.
 { return find(value); }
contains() [1/2]
template<class T> bool QSet< T >::contains (const T & value) const inline
Definition at line 91 of file qset.h.
Referenced by QStateMachinePrivate::_q_animationFinished(), QSortFilterProxyModelPrivate::_q_sourceDataChanged(), QDeclarativeTypeLoader::absoluteFilePath(), QMenuPrivate::QMacMenuPrivate::addAction(), QPatternist::XsdIdCache::addId(), QPatternist::XsdSchemaParser::addType(), QStateMachinePrivate::applyProperties(), QPatternist::OutputValidator::attribute(), QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QDirIteratorPrivate::checkAndPushDirectory(), QDeclarativeCompiler::checkDynamicMeta(), QDeclarativeCompiler::checkValidId(), QGraphicsWidget::close(), QSet< typename TokenLookupClass::NodeName >::contains(), containsSet(), QWSServerPrivate::dereferenceFont(), QBBEngine::doRequestUpdate(), QListViewPrivate::draggablePaintPairs(), QStyleSheetStyle::drawPrimitive(), QResourcePrivate::ensureChildren(), QGraphicsScenePrivate::enterModal(), QApplicationPrivate::enterModal(), QStateMachinePrivate::enterStates(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::epsilonClosure(), QPatternist::ElementAvailableFN::evaluateEBV(), QJSDebuggerAgent::expandObjectById(), QSortFilterProxyModelPrivate::filter_changed(), QGestureManager::filterEventThroughContexts(), QGraphicsAnchorLayoutPrivate::findPaths(), QPatternist::XsdSchemaResolver::findPrimitiveType(), QPatternist::XsdSchemaHelper::foundSubstitutionGroupTransitive(), QGraphicsScenePrivate::gestureEventHandler(), QStateMachinePrivate::goToState(), QPatternist::XsdIdCache::hasId(), QDeclarativeImportsPrivate::importExtension(), QDeclarativeImportDatabase::importPlugin(), QSet< typename TokenLookupClass::NodeName >::intersect(), QScriptEdit::isExecutableLine(), QTreeViewPrivate::isIndexExpanded(), QStateMachinePrivate::isInFinalState(), QTreeViewPrivate::isRowHidden(), QHttpHeader::keys(), QApplicationPrivate::leaveModal(), QTextDocumentWithImageResources::loadResource(), matchesType(), QStandardItemModel::mimeData(), QPatternist::XQueryTokenizer::normalizeEOL(), QPatternist::ResourceDelegator::openDocument(), QSet< typename TokenLookupClass::NodeName >::operator&=(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseRedefine(), QDeclarativeXmlQueryEngine::processQuery(), QtPrivate::QStringList_removeDuplicates(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), MetaObjectGenerator::readEnumInfo(), QWSServerPrivate::referenceFont(), QEvent::registerEventType(), QGraphicsSceneBspTree::removeItems(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QPatternist::XsdSchemaResolver::resolveTermReference(), QDomElementPrivate::save(), QItemSelectionModel::selectedColumns(), QTreeWidget::selectedItems(), QItemSelectionModel::selectedRows(), QJSDebuggerAgent::setProperty(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QFileSystemEngine::slowCanonicalized(), QTreeViewPrivate::storeExpanded(), QFontEngineQPA::stringToCMap(), QFontEngineQPF::stringToCMap(), QPatternist::XsdSchemaHelper::substitutionGroupOkTransitive(), QSet< typename TokenLookupClass::NodeName >::subtract(), QDeclarativeSmoothedAnimation::transition(), QStyleSheetStyle::unsetPalette(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QScriptEnginePrivate::variantListFromArray(), QScriptEnginePrivate::variantMapFromObject(), QPatternist::XsdSchemaHelper::wildcardUnion(), wxsTypeMatches(), and QPatternist::yyparse().
 { return q_hash.contains(value); }
contains() [2/2]
template<class T> Q_INLINE_TEMPLATE bool QSet< T >::contains (const QSet< T > & set) const
Definition at line 284 of file qset.h.
 {
     typename QSet<T>::const_iterator i = other.constBegin();
     while (i != other.constEnd()) {
         if (!contains(*i))
             return false;
         ++i;
     }
     return true;
 }
count()
template<class T> int QSet< T >::count () const inline
Definition at line 178 of file qset.h.
Referenced by QThreadPoolPrivate::activeThreadCount(), QPatternist::ElementAvailableFN::allXSLTInstructions(), QGraphicsAnchorLayoutPrivate::calculateTrunk(), QNetworkConfigurationManagerPrivate::configurationAdded(), QPatternist::XSLTTokenizer::createStandardAttributes(), QStandardItemModel::mimeData(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QDeclarativeOpenMetaObjectType::propertyCreated(), QGraphicsAnchorLayoutPrivate::solveMinMax(), and QPatternist::XsdValidatingInstanceReader::validateKeyIdentityConstraint().
 { return q_hash.count(); }
detach()
template<class T> void QSet< T >::detach () inline
Definition at line 83 of file qset.h.
 { q_hash.detach(); }
empty()
template<class T> bool QSet< T >::empty () const inline
Definition at line 199 of file qset.h.
 { return isEmpty(); }
end() [1/2]
template<class T> iterator QSet< T >::end () inline
Definition at line 169 of file qset.h.
Referenced by QDeclarativeBindingCompilerPrivate::buildSignalTable(), QGestureManager::cancelGesturesForChildren(), QGraphicsScenePrivate::cancelGesturesForChildren(), QTreeViewPrivate::collapse(), ShaderEffectItem::connectPropertySignals(), GraphPath::constraint(), QDeclarativeOpenMetaObjectType::createProperty(), QGestureManager::deliverEvents(), QMutableSetIterator< T >::findPrevious(), QStandardItemModel::mimeData(), QMutableSetIterator< T >::operator=(), QMutableSetIterator< T >::QMutableSetIterator(), QMutableSetIterator< T >::remove(), Graph< AnchorVertex, AnchorData >::serializeToDot(), QMutableSetIterator< T >::toBack(), QMutableSetIterator< T >::toFront(), ShaderEffectItem::updateEffectState(), writeVariablesEnum(), and QDirectFBScreenPrivate::~QDirectFBScreenPrivate().
 { return q_hash.end(); }
end() [2/2]
template<class T> const_iterator QSet< T >::end () const inline
Definition at line 170 of file qset.h.
 { return q_hash.end(); }
erase()
template<class T> iterator QSet< T >::erase (iterator i) inline
Definition at line 172 of file qset.h.
Referenced by QGestureManager::cancelGesturesForChildren(), QGraphicsScenePrivate::cancelGesturesForChildren(), QStandardItemModel::mimeData(), and QMutableSetIterator< T >::remove().
         { return q_hash.erase(reinterpret_cast<typename Hash::iterator &>(i)); }
find() [1/2]
template<class T> iterator QSet< T >::find (const T & value) inline
Definition at line 182 of file qset.h.
Referenced by QSet< typename TokenLookupClass::NodeName >::constFind(), and QStandardItemModel::mimeData().
 { return q_hash.find(value); }
find() [2/2]
template<class T> const_iterator QSet< T >::find (const T & value) const inline
Definition at line 183 of file qset.h.
 { return q_hash.find(value); }
fromList()
template<typename T> QSet< T > QSet< T >::fromList (const QList< T > & list) static
Definition at line 319 of file qset.h.
Referenced by QGraphicsAnchorLayoutPrivate::getGraphParts(), main(), and QSet< typename TokenLookupClass::NodeName >::values().
 {
     return list.toSet();
 }
insert()
template<class T> const_iterator QSet< T >::insert (const T & value) inline
Definition at line 179 of file qset.h.
Referenced by QDeclarativeXmlQueryEngine::abort(), QMenuPrivate::QMacMenuPrivate::addAction(), QPatternist::XsdIdCache::addId(), QStateMachinePrivate::addStatesToEnter(), QPatternist::ElementAvailableFN::allXSLTInstructions(), QStateMachinePrivate::applyProperties(), QPatternist::OutputValidator::attribute(), QDeclarativePath::attributes(), QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QScriptObjectSnapshot::capture(), QDeclarativeCompiler::checkDynamicMeta(), QGestureManager::cleanupCachedGestures(), collectAllElements(), QDeclarativePath::componentComplete(), QNetworkConfigurationManagerPrivate::configurationAdded(), QNetworkConfigurationManagerPrivate::configurationChanged(), QPatternist::XSLTTokenizer::createElementDescriptions(), QPatternist::XSLTTokenizer::createStandardAttributes(), QGestureManager::deliverEvents(), dlIterateCallback(), QResourcePrivate::ensureChildren(), QGraphicsScenePrivate::enterModal(), QApplicationPrivate::enterModal(), QStateMachinePrivate::enterStates(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::epsilonClosure(), QScriptDebuggerCommandExecutor::execute(), QStateMachinePrivate::exitStates(), QGraphicsAnchorLayoutPrivate::findPaths(), QPatternist::XsdSchemaResolver::findPrimitiveType(), QPatternist::XsdSchemaHelper::foundSubstitutionGroupTransitive(), QPatternist::XsdSchemaHelper::foundSubstitutionGroupTypeInheritance(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsAnchorLayoutPrivate::identifyFloatItems(), QGraphicsAnchorLayoutPrivate::identifyNonFloatItems_helper(), QDeclarativeImportsPrivate::importExtension(), QDeclarativeImportDatabase::importPlugin(), QHttpHeader::keys(), QApplicationPrivate::leaveModal(), QTextDocumentWithImageResources::loadResource(), ShaderEffectItem::lookThroughShaderCode(), QMacPixmapData::macCreateCGImageRef(), matchesType(), QStandardItemModel::mimeData(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::move(), QPatternist::XQueryTokenizer::nextToken(), QSet< typename TokenLookupClass::NodeName >::operator&=(), QSet< typename TokenLookupClass::NodeName >::operator+=(), QSet< typename TokenLookupClass::NodeName >::operator<<(), QSet< typename TokenLookupClass::NodeName >::operator|=(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseRedefine(), QNetworkConfigurationManagerPrivate::performAsyncConfigurationUpdate(), QStyleSheetStyle::polish(), QNetworkConfigurationManagerPrivate::pollEngines(), QDeclarativeGlobalScriptClass::QDeclarativeGlobalScriptClass(), QDeclarativeOpenMetaObject::QDeclarativeOpenMetaObject(), qmlFilesInDirectory(), QtPrivate::QStringList_removeDuplicates(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), MetaObjectGenerator::readEnumInfo(), QWSServerPrivate::referenceFont(), QEvent::registerEventType(), QGraphicsScenePrivate::registerScenePosItem(), QWidgetBackingStoreTracker::registerWidget(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveSimpleRestrictions(), QPatternist::XsdSchemaResolver::resolveTermReference(), QDomElementPrivate::save(), QTreeWidget::selectedItems(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QStateMachinePrivate::selectTransitions(), QPatternist::XsdSchemaParser::setDocumentURI(), QPatternist::XsdSchemaParser::setupBuiltinTypeNames(), QPatternist::XsdSchemaParserContext::setupElementDescriptions(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), QFileSystemEngine::slowCanonicalized(), QThreadPoolPrivate::startThread(), QTreeViewPrivate::storeExpanded(), QFontEngineQPA::stringToCMap(), QFontEngineQPF::stringToCMap(), QDeclarativeBindingCompilerPrivate::subscription(), QSslSocketPrivate::systemCaCertificates(), QPatternist::XQueryTokenizer::tokenizeStringLiteral(), QList< QPostEvent >::toSet(), QDeclarativeSmoothedAnimation::transition(), QSet< typename TokenLookupClass::NodeName >::unite(), QDockAreaLayoutInfo::usedTabBars(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QScriptEnginePrivate::variantListFromArray(), QScriptEnginePrivate::variantMapFromObject(), Graph< AnchorVertex, AnchorData >::vertices(), wxsTypeMatches(), and QPatternist::yyparse().
         { return static_cast<typename Hash::const_iterator>(q_hash.insert(value,
                                                                           QHashDummyValue())); }
intersect()
template<class T> Q_INLINE_TEMPLATE QSet< T > & QSet< T >::intersect (const QSet< T > & other)
Definition at line 256 of file qset.h.
Referenced by QSet< typename TokenLookupClass::NodeName >::constFind(), QSet< typename TokenLookupClass::NodeName >::operator&=(), QPatternist::XsdSchemaParser::readBlockingConstraintAttribute(), QPatternist::XsdSchemaParser::readDerivationConstraintAttribute(), and QPatternist::XsdSchemaHelper::wildcardIntersection().
 {
     QSet<T> copy1(*this);
     QSet<T> copy2(other);
     typename QSet<T>::const_iterator i = copy1.constEnd();
     while (i != copy1.constBegin()) {
         --i;
         if (!copy2.contains(*i))
             remove(*i);
     }
     return *this;
 }
isDetached()
template<class T> bool QSet< T >::isDetached () const inline
Definition at line 84 of file qset.h.
 { return q_hash.isDetached(); }
isEmpty()
template<class T> bool QSet< T >::isEmpty () const inline
Definition at line 77 of file qset.h.
Referenced by QWSServerPrivate::_q_clientClosed(), QStateMachinePrivate::_q_process(), QGestureManager::cancelGesturesForChildren(), QGraphicsScenePrivate::cancelGesturesForChildren(), QDirIteratorPrivate::checkAndPushDirectory(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QNetworkConfigurationManagerPrivate::configurationChanged(), QNetworkConfigurationManagerPrivate::configurationRemoved(), QGestureManager::deliverEvents(), QSet< typename TokenLookupClass::NodeName >::empty(), QStateMachinePrivate::enterStates(), QGestureManager::filterEventThroughContexts(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsAnchorLayoutPrivate::hasConflicts(), QNetworkConfigurationManagerPrivate::isOnline(), QGraphicsSceneBspTreeIndexPrivate::purgeRemovedItems(), QThreadPoolPrivate::reset(), QDeclarativeBindingCompilerPrivate::subscriptionNeutral(), QThreadPoolPrivate::tryStart(), QWidgetBackingStoreTracker::unregisterWidget(), QNetworkConfigurationManagerPrivate::updateConfigurations(), and QPatternist::XsdValidatingInstanceReader::validateElementSimpleType().
 { return q_hash.isEmpty(); }
operator &() [1/2]
template<class T> QSet<T> QSet< T >::operator& (const QSet< T > & other) const inline
Definition at line 213 of file qset.h.
         { QSet<T> result = *this; result &= other; return result; }
operator &() [2/2]
template<class T> QSet<T> QSet< T >::operator& (const QSet< T > & other) inline
Definition at line 223 of file qset.h.
         { QSet<T> result = *this; result &= other; return result; }
operator &=() [1/2]
template<class T> QSet<T>& QSet< T >::operator&= (const QSet< T > & other) inline
Definition at line 204 of file qset.h.
 { intersect(other); return *this; }
operator &=() [2/2]
template<class T> QSet<T>& QSet< T >::operator&= (const T & value) inline
Definition at line 205 of file qset.h.
         { QSet<T> result; if (contains(value)) result.insert(value); return (*this = result); }
operator!=()
template<class T> bool QSet< T >::operator!= (const QSet< T > & other) const inline
Definition at line 72 of file qset.h.
         { return q_hash != other.q_hash; }
operator+() [1/2]
template<class T> QSet<T> QSet< T >::operator+ (const QSet< T > & other) const inline
Definition at line 215 of file qset.h.
         { QSet<T> result = *this; result += other; return result; }
operator+() [2/2]
template<class T> QSet<T> QSet< T >::operator+ (const QSet< T > & other) inline
Definition at line 225 of file qset.h.
         { QSet<T> result = *this; result += other; return result; }
operator+=() [1/2]
template<class T> QSet<T>& QSet< T >::operator+= (const QSet< T > & other) inline
Definition at line 207 of file qset.h.
 { unite(other); return *this; }
operator+=() [2/2]
template<class T> QSet<T>& QSet< T >::operator+= (const T & value) inline
Definition at line 208 of file qset.h.
 { insert(value); return *this; }
operator-() [1/2]
template<class T> QSet<T> QSet< T >::operator- (const QSet< T > & other) const inline
Definition at line 217 of file qset.h.
         { QSet<T> result = *this; result -= other; return result; }
operator-() [2/2]
template<class T> QSet<T> QSet< T >::operator- (const QSet< T > & other) inline
Definition at line 227 of file qset.h.
         { QSet<T> result = *this; result -= other; return result; }
operator-=() [1/2]
template<class T> QSet<T>& QSet< T >::operator-= (const QSet< T > & other) inline
Definition at line 209 of file qset.h.
 { subtract(other); return *this; }
operator-=() [2/2]
template<class T> QSet<T>& QSet< T >::operator-= (const T & value) inline
Definition at line 210 of file qset.h.
 { remove(value); return *this; }
operator<<()
template<class T> QSet<T>& QSet< T >::operator<< (const T & value) inline
Definition at line 201 of file qset.h.
 { insert(value); return *this; }
operator=()
template<class T> QSet<T>& QSet< T >::operator= (const QSet< T > & other) inline
Definition at line 62 of file qset.h.
Referenced by QSet< typename TokenLookupClass::NodeName >::operator=().
         { q_hash = other.q_hash; return *this; }
operator==()
template<class T> bool QSet< T >::operator== (const QSet< T > & other) const inline
Definition at line 70 of file qset.h.
         { return q_hash == other.q_hash; }
operator|() [1/2]
template<class T> QSet<T> QSet< T >::operator| (const QSet< T > & other) const inline
Definition at line 211 of file qset.h.
         { QSet<T> result = *this; result |= other; return result; }
operator|() [2/2]
template<class T> QSet<T> QSet< T >::operator| (const QSet< T > & other) inline
Definition at line 221 of file qset.h.
         { QSet<T> result = *this; result |= other; return result; }
operator|=() [1/2]
template<class T> QSet<T>& QSet< T >::operator|= (const QSet< T > & other) inline
Definition at line 202 of file qset.h.
 { unite(other); return *this; }
operator|=() [2/2]
template<class T> QSet<T>& QSet< T >::operator|= (const T & value) inline
Definition at line 203 of file qset.h.
 { insert(value); return *this; }
remove()
template<class T> bool QSet< T >::remove (const T & value) inline
Definition at line 89 of file qset.h.
Referenced by QStateMachinePrivate::_q_animationFinished(), QStateMachinePrivate::applyProperties(), QGraphicsScenePrivate::cancelGesturesForChildren(), QWidgetExceptionCleaner::cleanup(), QGestureManager::cleanupCachedGestures(), QX11Data::clipboardReadIncrementalProperty(), QNetworkConfigurationManagerPrivate::configurationChanged(), QNetworkConfigurationManagerPrivate::configurationRemoved(), QWSServerPrivate::dereferenceFont(), QTableViewPrivate::drawAndClipSpans(), QStateMachinePrivate::exitStates(), QGraphicsScenePrivate::gestureEventHandler(), QDeclarativeXmlQueryEngine::processJobs(), QDeclarativeXmlQueryEngine::processQuery(), QClipboardData::QClipboardData(), qt_tablet_init(), QGestureManager::recycle(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsScene::setSelectionArea(), setupOwner(), QGLGlobalShareWidget::shareWidget(), QGraphicsScenePrivate::unregisterScenePosItem(), QWidgetBackingStoreTracker::unregisterWidget(), QStyleSheetStyle::unsetPalette(), QNetworkConfigurationManagerPrivate::updateConfigurations(), QScriptEnginePrivate::variantListFromArray(), QScriptEnginePrivate::variantMapFromObject(), QPatternist::XsdSchemaHelper::wildcardIntersection(), QWindowsXPStylePrivate::winId(), QDeclarativeOpenMetaObject::~QDeclarativeOpenMetaObject(), QMacPixmapData::~QMacPixmapData(), and QWidget::~QWidget().
 { return q_hash.remove(value) != 0; }
reserve()
template<class T > Q_INLINE_TEMPLATE void QSet< T >::reserve (int size) inline
Definition at line 241 of file qset.h.
Referenced by QPatternist::ElementAvailableFN::allXSLTInstructions(), QSet< typename TokenLookupClass::NodeName >::capacity(), QPatternist::XSLTTokenizer::createElementDescriptions(), QPatternist::XSLTTokenizer::createStandardAttributes(), QStandardItemModel::mimeData(), QtPrivate::QStringList_removeDuplicates(), qVectorToSet(), QTreeWidget::selectedItems(), QPatternist::XsdSchemaParser::setupBuiltinTypeNames(), QPatternist::XsdSchemaParserContext::setupElementDescriptions(), QList< QPostEvent >::toSet(), and QPatternist::yyparse().
 { q_hash.reserve(asize); }
setSharable()
template<class T> void QSet< T >::setSharable (bool sharable) inline
Definition at line 85 of file qset.h.
Referenced by QMutableSetIterator< T >::operator=(), QMutableSetIterator< T >::QMutableSetIterator(), and QMutableSetIterator< T >::~QMutableSetIterator().
 { q_hash.setSharable(sharable); }
size()
template<class T> int QSet< T >::size () const inline
Definition at line 75 of file qset.h.
Referenced by QSet< typename TokenLookupClass::NodeName >::capacity(), QGraphicsScenePrivate::removeItemHelper(), QSet< typename TokenLookupClass::NodeName >::toList(), QList< QPostEvent >::toSet(), writeIncludeFile(), and QGL2PaintEngineExPrivate::~QGL2PaintEngineExPrivate().
 { return q_hash.size(); }
squeeze()
template<class T> void QSet< T >::squeeze () inline
Definition at line 81 of file qset.h.
 { q_hash.squeeze(); }
subtract()
template<class T> Q_INLINE_TEMPLATE QSet< T > & QSet< T >::subtract (const QSet< T > & other)
Definition at line 270 of file qset.h.
Referenced by QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QSet< typename TokenLookupClass::NodeName >::constFind(), QSet< typename TokenLookupClass::NodeName >::operator-=(), QDeclarativeBindingCompilerPrivate::subscriptionNeutral(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), and QPatternist::XsdSchemaHelper::wildcardIntersection().
 {
     QSet<T> copy1(*this);
     QSet<T> copy2(other);
     typename QSet<T>::const_iterator i = copy1.constEnd();
     while (i != copy1.constBegin()) {
         --i;
         if (copy2.contains(*i))
             remove(*i);
     }
     return *this;
 }
swap()
template<class T> void QSet< T >::swap (QSet< T > & other) inline
Definition at line 68 of file qset.h.
 { q_hash.swap(other.q_hash); }
toList()
template<typename T > Q_OUTOFLINE_TEMPLATE QList< T > QSet< T >::toList () const
Definition at line 296 of file qset.h.
Referenced by QStateMachinePrivate::_q_process(), QApplication::allWidgets(), QDeclarativePath::attributes(), QScriptEngine::availableExtensions(), QGraphicsAnchorLayoutPrivate::calculateTrunk(), QGraphicsScenePrivate::cancelGesturesForChildren(), QScriptObjectSnapshot::capture(), QPatternist::XsdSchemaChecker::checkConstrainingFacets(), QDeclarativePath::componentComplete(), QListViewPrivate::draggablePaintPairs(), QStateMachinePrivate::enterStates(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::epsilonClosure(), QScriptDebuggerCommandExecutor::execute(), QStateMachinePrivate::exitStates(), QGraphicsScenePrivate::gestureEventHandler(), getVariables(), libraryPathList(), QSet< typename TokenLookupClass::NodeName >::operator-(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), QScriptDebuggerAgent::scriptsDelta(), QSimplex::setConstraints(), QSpanCollection::spansInRect(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QSet< typename TokenLookupClass::NodeName >::values(), and QTextOdfWriter::writeAll().
 {
     QList<T> result;
     result.reserve(size());
     typename QSet<T>::const_iterator i = constBegin();
     while (i != constEnd()) {
         result.append(*i);
         ++i;
     }
     return result;
 }
unite()
template<class T> Q_INLINE_TEMPLATE QSet< T > & QSet< T >::unite (const QSet< T > & other)
Definition at line 244 of file qset.h.
Referenced by collectAllElements(), QSet< typename TokenLookupClass::NodeName >::constFind(), QDeclarativeBindingCompilerPrivate::numberArith(), QSet< typename TokenLookupClass::NodeName >::operator+=(), QSet< typename TokenLookupClass::NodeName >::operator|=(), and QDeclarativeBindingCompilerPrivate::subscriptionNeutral().
 {
     QSet<T> copy(other);
     typename QSet<T>::const_iterator i = copy.constEnd();
     while (i != copy.constBegin()) {
         --i;
         insert(*i);
     }
     return *this;
 }
values()
template<class T> QList<T> QSet< T >::values () const inline
Definition at line 232 of file qset.h.
Referenced by QMdi::MinOverlapPlacer::getCandidatePlacements(), QJSDebuggerAgentPrivate::positionChange(), QPatternist::XsdSchemaHelper::wildcardUnion(), and QItemEditorFactory::~QItemEditorFactory().
 { return toList(); }
Properties
q_hash
template<class T> Hash QSet< T >::q_hash private
Definition at line 237 of file qset.h.
Referenced by QSet< typename TokenLookupClass::NodeName >::begin(), QSet< typename TokenLookupClass::NodeName >::capacity(), QSet< typename TokenLookupClass::NodeName >::clear(), QSet< typename TokenLookupClass::NodeName >::constBegin(), QSet< typename TokenLookupClass::NodeName >::constEnd(), QSet< typename TokenLookupClass::NodeName >::contains(), QSet< typename TokenLookupClass::NodeName >::count(), QSet< typename TokenLookupClass::NodeName >::detach(), QSet< typename TokenLookupClass::NodeName >::end(), QSet< typename TokenLookupClass::NodeName >::erase(), QSet< typename TokenLookupClass::NodeName >::find(), QSet< typename TokenLookupClass::NodeName >::insert(), QSet< typename TokenLookupClass::NodeName >::isDetached(), QSet< typename TokenLookupClass::NodeName >::isEmpty(), QSet< typename TokenLookupClass::NodeName >::operator!=(), QSet< typename TokenLookupClass::NodeName >::operator=(), QSet< typename TokenLookupClass::NodeName >::operator==(), QSet< typename TokenLookupClass::NodeName >::remove(), QSet< typename TokenLookupClass::NodeName >::reserve(), QSet< typename TokenLookupClass::NodeName >::setSharable(), QSet< typename TokenLookupClass::NodeName >::size(), QSet< typename TokenLookupClass::NodeName >::squeeze(), and QSet< typename TokenLookupClass::NodeName >::swap().
The documentation for this class was generated from the following files:
/src/corelib/io/qdatastream.h
/src/corelib/tools/qset.h