Qt 4.8: QHostAddress Class Reference
QHostAddress Class Reference
The QHostAddress class provides an IP address.
#include <qhostaddress.h>
Public Types
enum SpecialAddress {
Null, Broadcast, LocalHost, LocalHostIPv6,
Any, AnyIPv6
}
Public Functions
void clear ()
Sets the host address to 0.0.0.0.
bool isInSubnet (const QHostAddress &subnet, int netmask) const
Returns true if this IP is in the subnet described by the network prefix subnet and netmask netmask.
bool isInSubnet (const QPair< QHostAddress, int > &subnet) const
Returns true if this IP is in the subnet described by subnet.
bool isNull () const
Returns true if this host address is null (INADDR_ANY or in6addr_any).
bool operator!= (const QHostAddress &address) const
Returns true if this host address is not the same as the other address given; otherwise returns false.
bool operator!= (SpecialAddress address) const
Returns true if this host address is not the same as the other address given; otherwise returns false.
QHostAddress & operator= (const QHostAddress &other)
Assigns another host address to this object, and returns a reference to this object.
QHostAddress & operator= (const QString &address)
Assigns the host address address to this object, and returns a reference to this object.
bool operator== (const QHostAddress &address) const
Returns true if this host address is the same as the other address given; otherwise returns false.
bool operator== (SpecialAddress address) const
Returns true if this host address is the same as the other address given; otherwise returns false.
QAbstractSocket::NetworkLayerProtocol protocol () const
Returns the network layer protocol of the host address.
QHostAddress ()
Constructs a host address object with the IP address 0.0.0.0.
QHostAddress (quint32 ip4Addr)
Constructs a host address object with the IPv4 address ip4Addr.
QHostAddress (quint8 *ip6Addr)
Constructs a host address object with the IPv6 address ip6Addr.
QHostAddress (const Q_IPV6ADDR &ip6Addr)
Constructs a host address object with the IPv6 address ip6Addr.
QHostAddress (const sockaddr *sockaddr)
Constructs an IPv4 or IPv6 address using the address specified by the native structure sockaddr.
QHostAddress (const QString &address)
Constructs an IPv4 or IPv6 address based on the string address (e.g., "127.0.0.1").
QHostAddress (const QHostAddress &copy)
Constructs a copy of the given address.
QHostAddress (SpecialAddress address)
Constructs a QHostAddress object for address.
QString scopeId () const
Returns the scope ID of an IPv6 address.
void setAddress (quint32 ip4Addr)
Set the IPv4 address specified by ip4Addr.
void setAddress (quint8 *ip6Addr)
Set the IPv6 address specified by ip6Addr.
void setAddress (const Q_IPV6ADDR &ip6Addr)
Set the IPv6 address specified by ip6Addr.
void setAddress (const sockaddr *sockaddr)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the IPv4 or IPv6 address specified by the native structure sockaddr.
bool setAddress (const QString &address)
Sets the IPv4 or IPv6 address specified by the string representation specified by address (e.
void setScopeId (const QString &id)
Sets the IPv6 scope ID of the address to id.
quint32 toIPv4Address () const
Returns the IPv4 address as a number.
Q_IPV6ADDR toIPv6Address () const
Returns the IPv6 address as a Q_IPV6ADDR structure.
QString toString () const
Returns the address as a string.
~QHostAddress ()
Destroys the host address object.
Static Public Functions
static QPair< QHostAddress, int > parseSubnet (const QString &subnet)
Parses the IP and subnet information contained in subnet and returns the network prefix for that network and its prefix length.
Protected Variables
QScopedPointer< QHostAddressPrivate > d
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QHostAddress &address)
Writes host address address to the stream out and returns a reference to the stream.
QDataStream & operator>> (QDataStream &in, QHostAddress &address)
Reads a host address into address from the stream in and returns a reference to the stream.
Detailed Description
The QHostAddress class provides an IP address.
Attention
Module: QtNetwork
This class holds an IPv4 or IPv6 address in a platform- and protocol-independent manner.
QHostAddress is normally used with the QTcpSocket, QTcpServer, and QUdpSocket to connect to a host or to set up a server.
A host address is set with setAddress(), and retrieved with toIPv4Address(), toIPv6Address(), or toString(). You can check the type with protocol().
Note
Please note that QHostAddress does not do DNS lookups. QHostInfo is needed for that.
The class also supports common predefined addresses: Null , LocalHost , LocalHostIPv6 , Broadcast , and Any .
See also
QHostInfo, QTcpSocket, QTcpServer, QUdpSocket
Definition at line 70 of file qhostaddress.h.
Enumerations
SpecialAddress
enum QHostAddress::SpecialAddress
Null The null address object. Equivalent to QHostAddress().
LocalHost The IPv4 localhost address. Equivalent to QHostAddress("127.0.0.1").
LocalHostIPv6 The IPv6 localhost address. Equivalent to QHostAddress("::1").
Broadcast The IPv4 broadcast address. Equivalent to QHostAddress("255.255.255.255").
Any The IPv4 any-address. Equivalent to QHostAddress("0.0.0.0").
AnyIPv6 The IPv6 any-address. Equivalent to QHostAddress("::").
Enumerator
Null
Broadcast
LocalHost
LocalHostIPv6
Any
AnyIPv6
Definition at line 73 of file qhostaddress.h.
{
         Null,
         Broadcast,
         LocalHost,
         LocalHostIPv6,
         Any,
         AnyIPv6
     };
Constructors and Destructors
QHostAddress() [1/8]
QHostAddress::QHostAddress ()
Constructs a host address object with the IP address 0.0.0.0.
See also
clear()
Definition at line 460 of file qhostaddress.cpp.
Referenced by parseSubnet(), and QHostAddress().
     : d(new QHostAddressPrivate)
 {
 }
QHostAddress() [2/8]
QHostAddress::QHostAddress (quint32 ip4Addr) explicit
Constructs a host address object with the IPv4 address ip4Addr.
Definition at line 468 of file qhostaddress.cpp.
     : d(new QHostAddressPrivate)
 {
     setAddress(ip4Addr);
 }
QHostAddress() [3/8]
QHostAddress::QHostAddress (quint8 * ip6Addr) explicit
Constructs a host address object with the IPv6 address ip6Addr.
ip6Addr must be a 16-byte array in network byte order (big endian).
Definition at line 480 of file qhostaddress.cpp.
     : d(new QHostAddressPrivate)
 {
     setAddress(ip6Addr);
 }
QHostAddress() [4/8]
QHostAddress::QHostAddress (const Q_IPV6ADDR & ip6Addr) explicit
Constructs a host address object with the IPv6 address ip6Addr.
Definition at line 489 of file qhostaddress.cpp.
     : d(new QHostAddressPrivate)
 {
     setAddress(ip6Addr);
 }
QHostAddress() [5/8]
QHostAddress::QHostAddress (const sockaddr * sockaddr) explicit
Constructs an IPv4 or IPv6 address using the address specified by the native structure sockaddr.
See also
setAddress()
QHostAddress() [6/8]
QHostAddress::QHostAddress (const QString & address) explicit
Constructs an IPv4 or IPv6 address based on the string address (e.g., "127.0.0.1").
See also
setAddress()
Definition at line 501 of file qhostaddress.cpp.
     : d(new QHostAddressPrivate)
 {
     d->ipString = address;
     d->isParsed = false;
 }
QHostAddress() [7/8]
QHostAddress::QHostAddress (const QHostAddress & copy)
Constructs a copy of the given address.
Definition at line 530 of file qhostaddress.cpp.
     : d(new QHostAddressPrivate(*address.d.data()))
 {
 }
QHostAddress() [8/8]
QHostAddress::QHostAddress (SpecialAddress address)
Constructs a QHostAddress object for address.
Definition at line 538 of file qhostaddress.cpp.
     : d(new QHostAddressPrivate)
 {
     switch (address) {
     case Null:
         break;
     case Broadcast:
         setAddress(QLatin1String("255.255.255.255"));
         break;
     case LocalHost:
         setAddress(QLatin1String("127.0.0.1"));
         break;
     case LocalHostIPv6:
         setAddress(QLatin1String("::1"));
         break;
     case Any:
         setAddress(QLatin1String("0.0.0.0"));
         break;
     case AnyIPv6:
         setAddress(QLatin1String("::"));
         break;
     }
 }
~QHostAddress()
QHostAddress::~QHostAddress ()
Destroys the host address object.
Definition at line 565 of file qhostaddress.cpp.
 {
 }
Functions
clear()
void QHostAddress::clear ()
Sets the host address to 0.0.0.0.
Definition at line 615 of file qhostaddress.cpp.
Referenced by QNativeSocketEnginePrivate::fetchConnectionParameters(), operator>>(), and setAddress().
 {
     d->clear();
 }
isInSubnet() [1/2]
bool QHostAddress::isInSubnet (const QHostAddress & subnet, int netmask) const
Returns true if this IP is in the subnet described by the network prefix subnet and netmask netmask.
Since
4.5
An IP is considered to belong to a subnet if it is contained between the lowest and the highest address in that subnet. In the case of IP version 4, the lowest address is the network address, while the highest address is the broadcast address.
The subnet argument does not have to be the actual network address (the lowest address in the subnet). It can be any valid IP belonging to that subnet. In particular, if it is equal to the IP address held by this object, this function will always return true (provided the netmask is a valid value).
See also
parseSubnet()
Definition at line 968 of file qhostaddress.cpp.
Referenced by isBypassed(), isHostExcluded(), Maemo::ProxyConfPrivate::isHostExcluded(), and isInSubnet().
 {
     QT_ENSURE_PARSED(this);
     if (subnet.protocol() != d->protocol || netmask < 0)
         return false;
     union {
         quint32 ip;
         quint8 data[4];
     } ip4, net4;
     const quint8 *ip;
     const quint8 *net;
     if (d->protocol == QAbstractSocket::IPv4Protocol) {
         if (netmask > 32)
             netmask = 32;
         ip4.ip = qToBigEndian(d->a);
         net4.ip = qToBigEndian(subnet.d->a);
         ip = ip4.data;
         net = net4.data;
     } else if (d->protocol == QAbstractSocket::IPv6Protocol) {
         if (netmask > 128)
             netmask = 128;
         ip = d->a6.c;
         net = subnet.d->a6.c;
     } else {
         return false;
     }
     if (netmask >= 8 && memcmp(ip, net, netmask / 8) != 0)
         return false;
     if ((netmask & 7) == 0)
         return true;
     // compare the last octet now
     quint8 bytemask = 256 - (1 << (8 - (netmask & 7)));
     quint8 ipbyte = ip[netmask / 8];
     quint8 netbyte = net[netmask / 8];
     return (ipbyte & bytemask) == (netbyte & bytemask);
 }
isInSubnet() [2/2]
bool QHostAddress::isInSubnet (const QPair< QHostAddress, int > & subnet) const
Returns true if this IP is in the subnet described by subnet.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The QHostAddress member of subnet contains the network prefix and the int (second) member contains the netmask (prefix length).
Definition at line 1020 of file qhostaddress.cpp.
 {
     return isInSubnet(subnet.first, subnet.second);
 }
isNull()
bool QHostAddress::isNull () const
Returns true if this host address is null (INADDR_ANY or in6addr_any).
The default constructor creates a null address, and that address is not valid for any host or interface.
Definition at line 904 of file qhostaddress.cpp.
Referenced by interfaceListing(), QSslSocketBackendPrivate::isMatchingHostname(), and operator<<().
 {
     QT_ENSURE_PARSED(this);
     return d->protocol == QAbstractSocket::UnknownNetworkLayerProtocol;
 }
operator!=() [1/2]
bool QHostAddress::operator!= (const QHostAddress & other) const inline
Returns true if this host address is not the same as the other address given; otherwise returns false.
Since
4.2
Definition at line 112 of file qhostaddress.h.
     { return !operator==(address); }
operator!=() [2/2]
bool QHostAddress::operator!= (SpecialAddress address) const inline
Returns true if this host address is not the same as the other address given; otherwise returns false.
Definition at line 114 of file qhostaddress.h.
     { return !operator==(address); }
operator=() [1/2]
QHostAddress & QHostAddress::operator= (const QHostAddress & other)
Assigns another host address to this object, and returns a reference to this object.
Definition at line 573 of file qhostaddress.cpp.
Referenced by QNetmaskAddress::setAddress().
 {
     *d.data() = *address.d.data();
     return *this;
 }
operator=() [2/2]
QHostAddress & QHostAddress::operator= (const QString & address)
Assigns the host address address to this object, and returns a reference to this object.
See also
setAddress()
Definition at line 585 of file qhostaddress.cpp.
 {
     setAddress(address);
     return *this;
 }
operator==() [1/2]
bool QHostAddress::operator== (const QHostAddress & address) const
Returns true if this host address is the same as the other address given; otherwise returns false.
Definition at line 866 of file qhostaddress.cpp.
 {
     QT_ENSURE_PARSED(this);
     QT_ENSURE_PARSED(&other);
     if (d->protocol == QAbstractSocket::IPv4Protocol)
         return other.d->protocol == QAbstractSocket::IPv4Protocol && d->a == other.d->a;
     if (d->protocol == QAbstractSocket::IPv6Protocol) {
         return other.d->protocol == QAbstractSocket::IPv6Protocol
                && memcmp(&d->a6, &other.d->a6, sizeof(Q_IPV6ADDR)) == 0;
     }
     return d->protocol == other.d->protocol;
 }
operator==() [2/2]
bool QHostAddress::operator== (SpecialAddress address) const
Returns true if this host address is the same as the other address given; otherwise returns false.
Definition at line 884 of file qhostaddress.cpp.
 {
     QT_ENSURE_PARSED(this);
     QHostAddress otherAddress(other);
     QT_ENSURE_PARSED(&otherAddress);
     if (d->protocol == QAbstractSocket::IPv4Protocol)
         return otherAddress.d->protocol == QAbstractSocket::IPv4Protocol && d->a == otherAddress.d->a;
     if (d->protocol == QAbstractSocket::IPv6Protocol) {
         return otherAddress.d->protocol == QAbstractSocket::IPv6Protocol
                && memcmp(&d->a6, &otherAddress.d->a6, sizeof(Q_IPV6ADDR)) == 0;
     }
     return int(other) == int(Null);
 }
parseSubnet()
QPair< QHostAddress, int > QHostAddress::parseSubnet (const QString & subnet) static
Parses the IP and subnet information contained in subnet and returns the network prefix for that network and its prefix length.
Since
4.5
The IP address and the netmask must be separated by a slash (/).
This function supports arguments in the form:
123.123.123.123/n where n is any value between 0 and 32
123.123.123.123/255.255.255.255
<ipv6-address>/n where n is any value between 0 and 128
For IP version 4, this function accepts as well missing trailing components (i.e., less than 4 octets, like "192.168.1"), followed or not by a dot. If the netmask is also missing in that case, it is set to the number of octets actually passed (in the example above, it would be 24, for 3 octets).
See also
isInSubnet()
Definition at line 1053 of file qhostaddress.cpp.
Referenced by isBypassed(), isHostExcluded(), and Maemo::ProxyConfPrivate::isHostExcluded().
 {
     // We support subnets in the form:
     //   ddd.ddd.ddd.ddd/nn
     //   ddd.ddd.ddd/nn
     //   ddd.ddd/nn
     //   ddd/nn
     //   ddd.ddd.ddd.
     //   ddd.ddd.ddd
     //   ddd.ddd.
     //   ddd.ddd
     //   ddd.
     //   ddd
     //   <ipv6-address>/nn
     //
     //  where nn can be an IPv4-style netmask for the IPv4 forms
     const QPair<QHostAddress, int> invalid = qMakePair(QHostAddress(), -1);
     if (subnet.isEmpty())
         return invalid;
     int slash = subnet.indexOf(QLatin1Char('/'));
     QString netStr = subnet;
     if (slash != -1)
         netStr.truncate(slash);
     int netmask = -1;
     bool isIpv6 = netStr.contains(QLatin1Char(':'));
     if (slash != -1) {
         // is the netmask given in IP-form or in bit-count form?
         if (!isIpv6 && subnet.indexOf(QLatin1Char('.'), slash + 1) != -1) {
             // IP-style, convert it to bit-count form
             QNetmaskAddress parser;
             if (!parser.setAddress(subnet.mid(slash + 1)))
                 return invalid;
             netmask = parser.prefixLength();
         } else {
             bool ok;
             netmask = subnet.mid(slash + 1).toUInt(&ok);
             if (!ok)
                 return invalid;     // failed to parse the subnet
         }
     }
     if (isIpv6) {
         // looks like it's an IPv6 address
         if (netmask > 128)
             return invalid;     // invalid netmask
         if (netmask < 0)
             netmask = 128;
         QHostAddress net;
         if (!net.setAddress(netStr))
             return invalid;     // failed to parse the IP
         clearBits(net.d->a6.c, netmask, 128);
         return qMakePair(net, netmask);
     }
     if (netmask > 32)
         return invalid;         // invalid netmask
     // parse the address manually
     QStringList parts = netStr.split(QLatin1Char('.'));
     if (parts.isEmpty() || parts.count() > 4)
         return invalid;         // invalid IPv4 address
     if (parts.last().isEmpty())
         parts.removeLast();
     quint32 addr = 0;
     for (int i = 0; i < parts.count(); ++i) {
         bool ok;
         uint byteValue = parts.at(i).toUInt(&ok);
         if (!ok || byteValue > 255)
             return invalid;     // invalid IPv4 address
         addr <<= 8;
         addr += byteValue;
     }
     addr <<= 8 * (4 - parts.count());
     if (netmask == -1) {
         netmask = 8 * parts.count();
     } else if (netmask == 0) {
         // special case here
         // x86's instructions "shr" and "shl" do not operate when
         // their argument is 32, so the code below doesn't work as expected
         addr = 0;
     } else if (netmask != 32) {
         // clear remaining bits
         quint32 mask = quint32(0xffffffff) >> (32 - netmask) << (32 - netmask);
         addr &= mask;
     }
     return qMakePair(QHostAddress(addr), netmask);
 }
protocol()
QAbstractSocket::NetworkLayerProtocol QHostAddress::protocol () const
Returns the network layer protocol of the host address.
Definition at line 713 of file qhostaddress.cpp.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QNativeSocketEngine::bind(), QNativeSocketEngine::connectToHost(), QUdpSocketPrivate::doEnsureInitialized(), QHostInfoAgent::fromName(), interfaceListingWinXP(), isInSubnet(), QTcpServer::listen(), multicastMembershipHelper(), QNativeSocketEnginePrivate::nativeBind(), QNativeSocketEnginePrivate::nativeConnect(), QNativeSocketEnginePrivate::nativeSendDatagram(), QNativeSocketEnginePrivate::nativeSetMulticastInterface(), operator<<(), QHttpNetworkConnectionPrivate::prepareRequest(), qt_socket_setPortAndAddress(), qt_socks5_set_host_address_and_port(), QNetworkAddressEntry::setNetmask(), QNetworkAddressEntry::setPrefixLength(), QFtpPI::startNextCmd(), and translateWSAError().
 {
     QT_ENSURE_PARSED(this);
     return d->protocol;
 }
scopeId()
QString QHostAddress::scopeId () const
Returns the scope ID of an IPv6 address.
Since
4.1
For IPv4 addresses, or if the address does not contain a scope ID, an empty QString is returned.
The IPv6 scope ID specifies the scope of reachability for non-global IPv6 addresses, limiting the area in which the address can be used. All IPv6 addresses are associated with such a reachability scope. The scope ID is used to disambiguate addresses that are not guaranteed to be globally unique.
IPv6 specifies the following four levels of reachability:
Node-local: Addresses that are only used for communicating with services on the same interface (e.g., the loopback interface "::1").
Link-local: Addresses that are local to the network interface (link). There is always one link-local address for each IPv6 interface on your host. Link-local addresses ("fe80...") are generated from the MAC address of the local network adaptor, and are not guaranteed to be unique.
Site-local: Addresses that are local to the site / private network (e.g., the company intranet). Site-local addresses ("fec0...") are usually distributed by the site router, and are not guaranteed to be unique outside of the local site.
Global: For globally routable addresses, such as public servers on the Internet.
When using a link-local or site-local address for IPv6 connections, you must specify the scope ID. The scope ID for a link-local address is usually the same as the interface name (e.g., "eth0", "en1") or number (e.g., "1", "2").
See also
setScopeId()
Definition at line 840 of file qhostaddress.cpp.
Referenced by QNativeSocketEnginePrivate::nativeBind(), QNativeSocketEnginePrivate::nativeConnect(), QNativeSocketEnginePrivate::nativeSendDatagram(), operator<<(), and qt_socket_setPortAndAddress().
 {
     QT_ENSURE_PARSED(this);
     return (d->protocol == QAbstractSocket::IPv6Protocol) ? d->scopeId : QString();
 }
setAddress() [1/5]
void QHostAddress::setAddress (quint32 ip4Addr)
Set the IPv4 address specified by ip4Addr.
Definition at line 623 of file qhostaddress.cpp.
Referenced by addressFromSockaddr(), QAbstractSocket::connectToHostImplementation(), QHostInfoAgent::fromName(), QSslSocketBackendPrivate::initSslContext(), isBypassed(), isHostExcluded(), Maemo::ProxyConfPrivate::isHostExcluded(), operator=(), operator>>(), parseSubnet(), QHttpNetworkConnectionPrivate::prepareRequest(), QGlobalNetworkProxy::proxyForQuery(), QHostAddress(), qt_socket_getPortAndAddress(), qt_socks5_get_host_address_and_port(), QNetmaskAddress::setAddress(), setAddress(), and translateWSAError().
 {
     d->setAddress(ip4Addr);
 }
setAddress() [2/5]
void QHostAddress::setAddress (quint8 * ip6Addr)
Set the IPv6 address specified by ip6Addr.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
ip6Addr must be an array of 16 bytes in network byte order (high-order byte first).
Definition at line 639 of file qhostaddress.cpp.
 {
     d->setAddress(ip6Addr);
 }
setAddress() [3/5]
void QHostAddress::setAddress (const Q_IPV6ADDR & ip6Addr)
Set the IPv6 address specified by ip6Addr.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 652 of file qhostaddress.cpp.
 {
     d->setAddress(ip6Addr);
 }
setAddress() [4/5]
void QHostAddress::setAddress (const sockaddr * sockaddr)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the IPv4 or IPv6 address specified by the native structure sockaddr.
Returns true and sets the address if the address was successfully parsed; otherwise returns false.
setAddress() [5/5]
bool QHostAddress::setAddress (const QString & address)
Sets the IPv4 or IPv6 address specified by the string representation specified by address (e.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
g. "127.0.0.1"). Returns true and sets the address if the address was successfully parsed; otherwise returns false.
Definition at line 668 of file qhostaddress.cpp.
 {
     d->ipString = address;
     return d->parse();
 }
setScopeId()
void QHostAddress::setScopeId (const QString & id)
Sets the IPv6 scope ID of the address to id.
Since
4.1
If the address protocol is not IPv6, this function does nothing.
Definition at line 855 of file qhostaddress.cpp.
Referenced by addressFromSockaddr(), QHostInfoAgent::fromName(), operator>>(), and qt_socket_getPortAndAddress().
 {
     QT_ENSURE_PARSED(this);
     if (d->protocol == QAbstractSocket::IPv6Protocol)
         d->scopeId = id;
 }
toIPv4Address()
quint32 QHostAddress::toIPv4Address () const
Returns the IPv4 address as a number.
For example, if the address is 127.0.0.1, the returned value is 2130706433 (i.e. 0x7f000001).
This value is only valid if the Protocol() is QAbstractSocket::IPv4Protocol.
See also
toString()
Definition at line 704 of file qhostaddress.cpp.
Referenced by QHostInfoAgent::fromName(), multicastMembershipHelper(), QNativeSocketEnginePrivate::nativeBind(), QNativeSocketEnginePrivate::nativeConnect(), QNativeSocketEnginePrivate::nativeSendDatagram(), QNativeSocketEnginePrivate::nativeSetMulticastInterface(), operator<<(), postProcess(), qt_socket_setPortAndAddress(), qt_socks5_set_host_address_and_port(), QFtpPI::startNextCmd(), toString(), and translateWSAError().
 {
     QT_ENSURE_PARSED(this);
     return d->a;
 }
toIPv6Address()
Q_IPV6ADDR QHostAddress::toIPv6Address () const
Returns the IPv6 address as a Q_IPV6ADDR structure.
The structure consists of 16 unsigned characters.
Q_IPV6ADDR addr = hostAddr.toIPv6Address();
// addr contains 16 unsigned characters
for (int i = 0; i < 16; ++i) {
    // process addr[i]
}
This value is only valid if the protocol() is QAbstractSocket::IPv6Protocol.
See also
toString()
Definition at line 730 of file qhostaddress.cpp.
Referenced by QHostInfoAgent::fromName(), multicastMembershipHelper(), QNativeSocketEnginePrivate::nativeBind(), QNativeSocketEnginePrivate::nativeConnect(), QNativeSocketEnginePrivate::nativeSendDatagram(), operator<<(), qt_socket_setPortAndAddress(), qt_socks5_set_host_address_and_port(), and translateWSAError().
 {
     QT_ENSURE_PARSED(this);
     return d->a6;
 }
toString()
QString QHostAddress::toString () const
Returns the address as a string.
For example, if the address is the IPv4 address 127.0.0.1, the returned string is "127.0.0.1". For IPv6 the string format will follow the RFC5952 recommendation.
See also
toIPv4Address()
Definition at line 745 of file qhostaddress.cpp.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QAbstractSocket::connectToHost(), QUdpSocketPrivate::doEnsureInitialized(), QAbstractSocketPrivate::fetchConnectionParameters(), QNativeSocketEnginePrivate::fetchConnectionParameters(), QHostInfoAgent::fromName(), QTcpServer::listen(), multicastMembershipHelper(), QNativeSocketEnginePrivate::nativeBind(), QNativeSocketEnginePrivate::nativeConnect(), QNativeSocketEnginePrivate::nativeReceiveDatagram(), QNativeSocketEnginePrivate::nativeSendDatagram(), operator<<(), QFtpPI::processReply(), qHash(), QFtpPI::startNextCmd(), translateWSAError(), and QUdpSocket::writeDatagram().
 {
     QT_ENSURE_PARSED(this);
     if (d->protocol == QAbstractSocket::IPv4Protocol) {
         quint32 i = toIPv4Address();
         QString s;
         s.sprintf("%d.%d.%d.%d", (i>>24) & 0xff, (i>>16) & 0xff,
                 (i >> 8) & 0xff, i & 0xff);
         return s;
     }
     if (d->protocol == QAbstractSocket::IPv6Protocol) {
         quint16 ugle[8];
         for (int i = 0; i < 8; i++) {
             ugle[i] = (quint16(d->a6[2*i]) << 8) | quint16(d->a6[2*i+1]);
         }
         QString s;
         QString temp;
         bool zeroDetected = false;
         bool zeroShortened = false;
         for (int i = 0; i < 8; i++) {
             if ((ugle[i] != 0) || zeroShortened) {
                 temp.sprintf("%X", ugle[i]);
                 s.append(temp);
                 if (zeroDetected)
                     zeroShortened = true;
             } else {
                 if (!zeroDetected) {
                     if (i<7 && (ugle[i+1] == 0)) {
                         s.append(QLatin1Char(':'));
                         zeroDetected = true;
                     } else {
                         temp.sprintf("%X", ugle[i]);
                         s.append(temp);
                         if (i<7)
                             s.append(QLatin1Char(':'));
                     }
                 }
             }
             if (i<7 && ((ugle[i] != 0) || zeroShortened || (i==0 && zeroDetected)))
                 s.append(QLatin1Char(':'));
         }
         if (!d->scopeId.isEmpty())
             s.append(QLatin1Char('%') + d->scopeId);
         return s;
     }
     return QString();
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & out, const QHostAddress & address) related
Writes host address address to the stream out and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 1176 of file qhostaddress.cpp.
 {
     qint8 prot;
     prot = qint8(address.protocol());
     out << prot;
     switch (address.protocol()) {
     case QAbstractSocket::UnknownNetworkLayerProtocol:
         break;
     case QAbstractSocket::IPv4Protocol:
         out << address.toIPv4Address();
         break;
     case QAbstractSocket::IPv6Protocol:
     {
         Q_IPV6ADDR ipv6 = address.toIPv6Address();
         for (int i = 0; i < 16; ++i)
             out << ipv6[i];
         out << address.scopeId();
     }
         break;
     }
     return out;
 }
operator>>()
QDataStream & operator>> (QDataStream & in, QHostAddress & address) related
Reads a host address into address from the stream in and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 1209 of file qhostaddress.cpp.
 {
     qint8 prot;
     in >> prot;
     switch (QAbstractSocket::NetworkLayerProtocol(prot)) {
     case QAbstractSocket::UnknownNetworkLayerProtocol:
         address.clear();
         break;
     case QAbstractSocket::IPv4Protocol:
     {
         quint32 ipv4;
         in >> ipv4;
         address.setAddress(ipv4);
     }
         break;
     case QAbstractSocket::IPv6Protocol:
     {
         Q_IPV6ADDR ipv6;
         for (int i = 0; i < 16; ++i)
             in >> ipv6[i];
         address.setAddress(ipv6);
         QString scope;
         in >> scope;
         address.setScopeId(scope);
     }
         break;
     default:
         address.clear();
         in.setStatus(QDataStream::ReadCorruptData);
     }
     return in;
 }
Properties
d
QScopedPointer<QHostAddressPrivate> QHostAddress::d protected
Definition at line 134 of file qhostaddress.h.
Referenced by clear(), isInSubnet(), isNull(), operator=(), operator==(), parseSubnet(), protocol(), QHostAddress(), scopeId(), setAddress(), setScopeId(), toIPv4Address(), toIPv6Address(), and toString().
The documentation for this class was generated from the following files:
/src/network/kernel/qhostaddress.h
/src/network/kernel/qhostaddress.cpp