Qt 4.8: QDri2Context Class Reference
QDri2Context Class Reference
#include <qdri2context.h>
Public Functions
void doneCurrent ()
Reimplement in subclass to release current context.
void * eglContext () const
void * getProcAddress (const QString &procName)
Reimplement in subclass to native getProcAddr calls.
void makeCurrent ()
Reimplement in subclass to do makeCurrent on native GL context.
QPlatformWindowFormat platformWindowFormat () const
QWidget has the function qplatformWindowFormat().
QDri2Context (QXcbWindow *window)
void resize (const QSize &size)
void swapBuffers ()
Reimplement in subclass to native swap buffers calls.
~QDri2Context ()
Public Functions inherited from QPlatformGLContext
QPlatformGLContext ()
All subclasses needs to specify the platformWindow.
virtual ~QPlatformGLContext ()
If this is the current context for the thread, doneCurrent is called.
Protected Functions
xcb_dri2_dri2_buffer_t * backBuffer ()
Protected Variables
QScopedPointer< QDri2ContextPrivate > d_ptr
Protected Variables inherited from QPlatformGLContext
QScopedPointer< QPlatformGLContextPrivate > d_ptr
Private Functions
Q_DECLARE_PRIVATE (QDri2Context)
Additional Inherited Members
Static Public Functions inherited from QPlatformGLContext
static const QPlatformGLContext * currentContext ()
Returns the last context which called makeCurrent.
Detailed Description
Definition at line 52 of file qdri2context.h.
Constructors and Destructors
QDri2Context()
QDri2Context::QDri2Context (QXcbWindow * window)
Definition at line 89 of file qdri2context.cpp.
     : d_ptr(new QDri2ContextPrivate(window))
 {
     Q_D(QDri2Context);
     static const EGLint contextAttribs[] = {
             EGL_CONTEXT_CLIENT_VERSION, 2,
             EGL_NONE
     };
     eglBindAPI(EGL_OPENGL_ES_API);
     EGLContext shareContext = EGL_NO_CONTEXT;
     if (window->widget()->platformWindowFormat().sharedGLContext()) {
         QDri2Context *context = static_cast<QDri2Context *>(window->widget()->platformWindowFormat().sharedGLContext());
         shareContext = context->d_func()->eglContext;
     }
     d->eglContext = eglCreateContext(EGL_DISPLAY_FROM_XCB(d->qXcbWindow), NULL,
                                                shareContext, contextAttribs);
     if (d->eglContext == EGL_NO_CONTEXT) {
         qDebug() << "No eglContext!" << eglGetError();
     }
     EGLBoolean makeCurrentSuccess = eglMakeCurrent(EGL_DISPLAY_FROM_XCB(d->qXcbWindow),EGL_NO_SURFACE,EGL_NO_SURFACE,d->eglContext);
     if (!makeCurrentSuccess) {
         qDebug() << "eglMakeCurrent failed!" << eglGetError();
     }
     xcb_dri2_create_drawable (d->xcbConnection(), d->xcbWindow());
     glGenFramebuffers(1,&d->fbo);
     glBindFramebuffer(GL_FRAMEBUFFER,d->fbo);
     glActiveTexture(GL_TEXTURE0);
     glGenRenderbuffers(1, &d->rbo);
     glBindRenderbuffer(GL_RENDERBUFFER, d->rbo);
     glGenRenderbuffers(1,&d->depth);
     glBindRenderbuffer(GL_RENDERBUFFER, d->depth);
     resize(d->qXcbWindow->widget()->geometry().size());
     glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_RENDERBUFFER, d->rbo);
     glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_ATTACHMENT, GL_RENDERER,d->depth);
     glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_STENCIL_ATTACHMENT, GL_RENDERER,d->depth);
     //restore the old current context
     const QPlatformGLContext *currentContext = QPlatformGLContext::currentContext();
     if (currentContext)
         const_cast<QPlatformGLContext*>(currentContext)->makeCurrent();
 }
~QDri2Context()
QDri2Context::~QDri2Context ()
Definition at line 142 of file qdri2context.cpp.
 {
     //cleanup
 }
Functions
backBuffer()
xcb_dri2_dri2_buffer_t * QDri2Context::backBuffer () protected
Definition at line 239 of file qdri2context.cpp.
Referenced by resize().
 {
     Q_D(QDri2Context);
     unsigned int backBufferAttachment = XCB_DRI2_ATTACHMENT_BUFFER_BACK_LEFT;
     xcb_dri2_get_buffers_cookie_t cookie = xcb_dri2_get_buffers_unchecked (d->xcbConnection(),
                                                                            d->xcbWindow(),
                                                                            1, 1, &backBufferAttachment);
     xcb_dri2_get_buffers_reply_t *reply = xcb_dri2_get_buffers_reply (d->xcbConnection(), cookie, NULL);
     if (!reply) {
         qDebug() << "failed to get buffers reply";
         return 0;
     }
     xcb_dri2_dri2_buffer_t *buffers = xcb_dri2_get_buffers_buffers (reply);
     if (!buffers) {
         qDebug() << "failed to get buffers";
         return 0;
     }
     Q_ASSERT(reply->count == 1);
     delete reply;
     return buffers;
 }
doneCurrent()
void QDri2Context::doneCurrent () virtual
Reimplement in subclass to release current context.
Typically this is calling makeCurrent with 0 "surface"
Reimplemented from QPlatformGLContext.
Definition at line 157 of file qdri2context.cpp.
 {
     QPlatformGLContext::doneCurrent();
     Q_D(QDri2Context);
     eglMakeCurrent(EGL_DISPLAY_FROM_XCB(d->qXcbWindow),EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);
 }
eglContext()
void * QDri2Context::eglContext () const
Definition at line 267 of file qdri2context.cpp.
Referenced by QXcbNativeInterface::eglContextForWidget(), and QDri2Context().
 {
     Q_D(const QDri2Context);
     return d->eglContext;
 }
getProcAddress()
void * QDri2Context::getProcAddress (const QString & procName) virtual
Reimplement in subclass to native getProcAddr calls.
Note: its convenient to use qPrintable(const QString &str) to get the const char * pointer
Implements QPlatformGLContext.
Definition at line 191 of file qdri2context.cpp.
 {
     return (void *)eglGetProcAddress(qPrintable(procName));
 }
makeCurrent()
void QDri2Context::makeCurrent () virtual
Reimplement in subclass to do makeCurrent on native GL context.
Reimplemented from QPlatformGLContext.
Definition at line 147 of file qdri2context.cpp.
Referenced by QDri2Context().
 {
     QPlatformGLContext::makeCurrent();
     Q_D(QDri2Context);
     eglMakeCurrent(EGL_DISPLAY_FROM_XCB(d->qXcbWindow),EGL_NO_SURFACE,EGL_NO_SURFACE,d->eglContext);
     glBindFramebuffer(GL_FRAMEBUFFER,d->fbo);
 }
platformWindowFormat()
QPlatformWindowFormat QDri2Context::platformWindowFormat () const virtual
QWidget has the function qplatformWindowFormat().
That function is for the application programmer to request the format of the window and the context that he wants.
Reimplement this function in a subclass to indicate what format the glContext actually has.
Implements QPlatformGLContext.
Definition at line 233 of file qdri2context.cpp.
 {
     Q_D(const QDri2Context);
     return d->windowFormat;
 }
Q_DECLARE_PRIVATE()
QDri2Context::Q_DECLARE_PRIVATE (QDri2Context) private
resize()
void QDri2Context::resize (const QSize & size)
Definition at line 196 of file qdri2context.cpp.
Referenced by QDri2Context().
 {
     Q_D(QDri2Context);
     d->size= size;
     glBindFramebuffer(GL_FRAMEBUFFER,d->fbo);
     xcb_dri2_dri2_buffer_t *backBfr = backBuffer();
     if (d->image) {
         qDebug() << "destroing image";
         eglDestroyImageKHR(EGL_DISPLAY_FROM_XCB(d->qXcbWindow),d->image);
     }
     EGLint imgAttribs[] = {
         EGL_WIDTH,                      d->size.width(),
         EGL_HEIGHT,                     d->size.height(),
         EGL_DRM_BUFFER_STRIDE_MESA,     backBfr->pitch /4,
         EGL_DRM_BUFFER_FORMAT_MESA,     EGL_DRM_BUFFER_FORMAT_ARGB32_MESA,
         EGL_NONE
     };
     d->image = eglCreateImageKHR(EGL_DISPLAY_FROM_XCB(d->qXcbWindow),
                                 EGL_NO_CONTEXT,
                                 EGL_DRM_BUFFER_MESA,
                                 (EGLClientBuffer) backBfr->name,
                                 imgAttribs);
     glBindRenderbuffer(GL_RENDERBUFFER, d->rbo);
     glEGLImageTargetRenderbufferStorageOES(GL_RENDERBUFFER,
                                            d->image);
     glBindRenderbuffer(GL_RENDERBUFFER, d->depth);
     glRenderbufferStorage(GL_RENDERBUFFER,GL_DEPTH24_STENCIL8_OES,d->size.width(), d->size.height());
 }
swapBuffers()
void QDri2Context::swapBuffers () virtual
Reimplement in subclass to native swap buffers calls.
Implements QPlatformGLContext.
Definition at line 164 of file qdri2context.cpp.
 {
     Q_D(QDri2Context);
     xcb_rectangle_t rectangle;
     rectangle.x = 0;
     rectangle.y = 0;
     rectangle.width = d->qXcbWindow->widget()->geometry().width();
     rectangle.height = d->qXcbWindow->widget()->geometry().height();
     xcb_xfixes_region_t xfixesRegion = xcb_generate_id(d->xcbConnection());
     xcb_xfixes_create_region(d->xcbConnection(), xfixesRegion,
                              1, &rectangle);
     xcb_dri2_copy_region_cookie_t cookie = xcb_dri2_copy_region_unchecked(d->xcbConnection(),
                                                                           d->qXcbWindow->window(),
                                                                           xfixesRegion,
                                                                           XCB_DRI2_ATTACHMENT_BUFFER_FRONT_LEFT,
                                                                           XCB_DRI2_ATTACHMENT_BUFFER_BACK_LEFT);
     xcb_dri2_copy_region_reply_t *reply = xcb_dri2_copy_region_reply(d->xcbConnection(),cookie,NULL);
     //cleanup
     delete reply;
     xcb_xfixes_destroy_region(d->xcbConnection(), xfixesRegion);
 }
Properties
d_ptr
QScopedPointer<QDri2ContextPrivate> QDri2Context::d_ptr protected
Definition at line 72 of file qdri2context.h.
The documentation for this class was generated from the following files:
/src/plugins/platforms/xcb/qdri2context.h
/src/plugins/platforms/xcb/qdri2context.cpp