Qt 4.8: QDeclarativeXMLHttpRequest Class Reference
QDeclarativeXMLHttpRequest Class Reference
Public Types
enum State {
Unsent = 0, Opened = 1, HeadersReceived = 2, Loading = 3,
Done = 4
}
Public Functions
QScriptValue abort (QScriptValue *me)
void addHeader (const QString &, const QString &)
bool errorFlag () const
QString header (const QString &name)
QString headers ()
QScriptValue open (QScriptValue *me, const QString &, const QUrl &)
QDeclarativeXMLHttpRequest (QNetworkAccessManager *manager)
const QByteArray & rawResponseBody () const
quint32 readyState () const
bool receivedXml () const
int replyStatus () const
QString replyStatusText () const
QString responseBody ()
QScriptValue send (QScriptValue *me, const QByteArray &)
bool sendFlag () const
virtual ~QDeclarativeXMLHttpRequest ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Types
typedef QPair< QByteArray, QByteArray > HeaderPair
typedef QList< HeaderPair > HeadersList
Private Slots
void downloadProgress (qint64)
void error (QNetworkReply::NetworkError)
void finished ()
Private Functions
void destroyNetwork ()
QScriptValue dispatchCallback (QScriptValue *me)
void fillHeadersList ()
QTextCodec * findTextCodec () const
QNetworkAccessManager * networkAccessManager ()
void printError (const QScriptValue &)
void readEncoding ()
void requestFromUrl (const QUrl &url)
Properties
QByteArray m_charset
QByteArray m_data
bool m_errorFlag
bool m_gotXml
HeadersList m_headersList
QScriptValue m_me
QString m_method
QByteArray m_mime
QNetworkAccessManager * m_nam
QDeclarativeGuard< QNetworkReply > m_network
int m_redirectCount
QNetworkRequest m_request
QByteArray m_responseEntityBody
bool m_sendFlag
State m_state
int m_status
QString m_statusText
QTextCodec * m_textCodec
QUrl m_url
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 945 of file qdeclarativexmlhttprequest.cpp.
Typedefs
HeaderPair
typedef QPair<QByteArray, QByteArray> QDeclarativeXMLHttpRequest::HeaderPair private
Definition at line 990 of file qdeclarativexmlhttprequest.cpp.
HeadersList
typedef QList<HeaderPair> QDeclarativeXMLHttpRequest::HeadersList private
Definition at line 991 of file qdeclarativexmlhttprequest.cpp.
Enumerations
State
enum QDeclarativeXMLHttpRequest::State
Enumerator
Unsent
Opened
HeadersReceived
Loading
Done
Definition at line 949 of file qdeclarativexmlhttprequest.cpp.
                { Unsent = 0,
                  Opened = 1, HeadersReceived = 2,
                  Loading = 3, Done = 4 };
Constructors and Destructors
QDeclarativeXMLHttpRequest()
QDeclarativeXMLHttpRequest::QDeclarativeXMLHttpRequest (QNetworkAccessManager * manager)
Definition at line 1019 of file qdeclarativexmlhttprequest.cpp.
 : m_state(Unsent), m_errorFlag(false), m_sendFlag(false),
   m_redirectCount(0), m_gotXml(false), m_textCodec(0), m_network(0), m_nam(manager)
 {
 }
~QDeclarativeXMLHttpRequest()
QDeclarativeXMLHttpRequest::~QDeclarativeXMLHttpRequest () virtual
Definition at line 1025 of file qdeclarativexmlhttprequest.cpp.
 {
     destroyNetwork();
 }
Functions
abort()
QScriptValue QDeclarativeXMLHttpRequest::abort (QScriptValue * me)
Definition at line 1190 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_abort().
 {
     destroyNetwork();
     m_responseEntityBody = QByteArray();
     m_errorFlag = true;
     m_request = QNetworkRequest();
     if (!(m_state == Unsent ||
           (m_state == Opened && !m_sendFlag) ||
           m_state == Done)) {
         m_state = Done;
         m_sendFlag = false;
         QScriptValue cbv = dispatchCallback(me);
         if (cbv.isError()) return cbv;
     }
     m_state = Unsent;
     return QScriptValue();
 }
addHeader()
void QDeclarativeXMLHttpRequest::addHeader (const QString & name, const QString & value)
Definition at line 1067 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_setRequestHeader().
 {
     QByteArray utfname = name.toUtf8();
     if (m_request.hasRawHeader(utfname)) {
         m_request.setRawHeader(utfname, m_request.rawHeader(utfname) + ',' + value.toUtf8());
     } else {
         m_request.setRawHeader(utfname, value.toUtf8());
     }
 }
destroyNetwork()
void QDeclarativeXMLHttpRequest::destroyNetwork () private
Definition at line 1413 of file qdeclarativexmlhttprequest.cpp.
Referenced by abort(), error(), finished(), open(), and ~QDeclarativeXMLHttpRequest().
 {
     if (m_network) {
         m_network->disconnect();
         m_network->deleteLater();
         m_network = 0;
     }
 }
dispatchCallback()
QScriptValue QDeclarativeXMLHttpRequest::dispatchCallback (QScriptValue * me) private
Definition at line 1400 of file qdeclarativexmlhttprequest.cpp.
Referenced by abort(), downloadProgress(), error(), finished(), and open().
 {
     QScriptValue v = me->property(QLatin1String("callback"));
     return v.call();
 }
downloadProgress
void QDeclarativeXMLHttpRequest::downloadProgress (qint64 bytes) private slot
Definition at line 1211 of file qdeclarativexmlhttprequest.cpp.
Referenced by requestFromUrl().
 {
     Q_UNUSED(bytes)
     m_status =
         m_network->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
     m_statusText =
         QString::fromUtf8(m_network->attribute(QNetworkRequest::HttpReasonPhraseAttribute).toByteArray());
     // ### We assume if this is called the headers are now available
     if (m_state < HeadersReceived) {
         m_state = HeadersReceived;
         fillHeadersList ();
         QScriptValue cbv = dispatchCallback(&m_me);
         if (cbv.isError()) printError(cbv);
     }
     bool wasEmpty = m_responseEntityBody.isEmpty();
     m_responseEntityBody.append(m_network->readAll());
     if (wasEmpty && !m_responseEntityBody.isEmpty()) {
         m_state = Loading;
         QScriptValue cbv = dispatchCallback(&m_me);
         if (cbv.isError()) printError(cbv);
     }
 }
error
void QDeclarativeXMLHttpRequest::error (QNetworkReply::NetworkError error) private slot
Definition at line 1236 of file qdeclarativexmlhttprequest.cpp.
Referenced by printError(), and requestFromUrl().
 {
     Q_UNUSED(error)
     m_status =
         m_network->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
     m_statusText =
         QString::fromUtf8(m_network->attribute(QNetworkRequest::HttpReasonPhraseAttribute).toByteArray());
     m_responseEntityBody = QByteArray();
     m_request = QNetworkRequest();
     m_data.clear();
     destroyNetwork();
     if (error == QNetworkReply::ContentAccessDenied ||
         error == QNetworkReply::ContentOperationNotPermittedError ||
         error == QNetworkReply::ContentNotFoundError ||
         error == QNetworkReply::AuthenticationRequiredError ||
         error == QNetworkReply::ContentReSendError) {
         m_state = Loading;
         QScriptValue cbv = dispatchCallback(&m_me);
         if (cbv.isError()) printError(cbv);
     } else {
         m_errorFlag = true;
     }
     m_state = Done;
     QScriptValue cbv = dispatchCallback(&m_me);
     if (cbv.isError()) printError(cbv);
 }
errorFlag()
bool QDeclarativeXMLHttpRequest::errorFlag () const
Definition at line 1035 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_status(), and qmlxmlhttprequest_statusText().
 {
     return m_errorFlag;
 }
fillHeadersList()
void QDeclarativeXMLHttpRequest::fillHeadersList () private
Definition at line 1102 of file qdeclarativexmlhttprequest.cpp.
Referenced by downloadProgress(), and finished().
 {
     QList<QByteArray> headerList = m_network->rawHeaderList();
     m_headersList.clear();
     foreach (const QByteArray &header, headerList) {
         HeaderPair pair (header.toLower(), m_network->rawHeader(header));
         if (pair.first == "set-cookie" ||
             pair.first == "set-cookie2")
             continue;
         m_headersList << pair;
     }
 }
findTextCodec()
QTextCodec * QDeclarativeXMLHttpRequest::findTextCodec () const private
Definition at line 1357 of file qdeclarativexmlhttprequest.cpp.
Referenced by responseBody().
 {
     QTextCodec *codec = 0;
     if (!m_charset.isEmpty())
         codec = QTextCodec::codecForName(m_charset);
     if (!codec && m_gotXml) {
         QXmlStreamReader reader(m_responseEntityBody);
         reader.readNext();
         codec = QTextCodec::codecForName(reader.documentEncoding().toString().toUtf8());
     }
     if (!codec && m_mime == "text/html")
         codec = QTextCodec::codecForHtml(m_responseEntityBody, 0);
     if (!codec)
         codec = QTextCodec::codecForUtfText(m_responseEntityBody, 0);
     if (!codec)
         codec = QTextCodec::codecForName("UTF-8");
     return codec;
 }
finished
void QDeclarativeXMLHttpRequest::finished () private slot
Definition at line 1268 of file qdeclarativexmlhttprequest.cpp.
Referenced by requestFromUrl().
 {
     m_redirectCount++;
     if (m_redirectCount < XMLHTTPREQUEST_MAXIMUM_REDIRECT_RECURSION) {
         QVariant redirect = m_network->attribute(QNetworkRequest::RedirectionTargetAttribute);
         if (redirect.isValid()) {
             QUrl url = m_network->url().resolved(redirect.toUrl());
             if (url.scheme().toLower() != QLatin1String("file")) {
                 // See http://www.ietf.org/rfc/rfc2616.txt, section 10.3.4 "303 See Other":
                 // Result of 303 redirection should be a new "GET" request.
                 const QVariant code = m_network->attribute(QNetworkRequest::HttpStatusCodeAttribute);
                 if (code.isValid() && code.toInt() == 303 && m_method != QLatin1String("GET"))
                     m_method = QLatin1String("GET");
                 destroyNetwork();
                 requestFromUrl(url);
                 return;
             }
         }
     }
     m_status =
         m_network->attribute(QNetworkRequest::HttpStatusCodeAttribute).toInt();
     m_statusText =
         QString::fromUtf8(m_network->attribute(QNetworkRequest::HttpReasonPhraseAttribute).toByteArray());
     if (m_state < HeadersReceived) {
         m_state = HeadersReceived;
         fillHeadersList ();
         QScriptValue cbv = dispatchCallback(&m_me);
         if (cbv.isError()) printError(cbv);
     }
     m_responseEntityBody.append(m_network->readAll());
     readEncoding();
     if (xhrDump()) {
         qWarning().nospace() << "XMLHttpRequest: RESPONSE " << qPrintable(m_url.toString());
         if (!m_responseEntityBody.isEmpty()) {
             qWarning().nospace() << "                "
                                  << qPrintable(QString::fromUtf8(m_responseEntityBody));
         }
     }
     m_data.clear();
     destroyNetwork();
     if (m_state < Loading) {
         m_state = Loading;
         QScriptValue cbv = dispatchCallback(&m_me);
         if (cbv.isError()) printError(cbv);
     }
     m_state = Done;
     QScriptValue cbv = dispatchCallback(&m_me);
     if (cbv.isError()) printError(cbv);
     m_me = QScriptValue();
 }
header()
QString QDeclarativeXMLHttpRequest::header (const QString & name)
Definition at line 1078 of file qdeclarativexmlhttprequest.cpp.
Referenced by fillHeadersList(), headers(), qmlxmlhttprequest_getResponseHeader(), and readEncoding().
 {
     QByteArray utfname = name.toLower().toUtf8();
     foreach (const HeaderPair &header, m_headersList) {
         if (header.first == utfname)
             return QString::fromUtf8(header.second);
     }
     return QString();
 }
headers()
QString QDeclarativeXMLHttpRequest::headers ()
Definition at line 1089 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_getAllResponseHeaders().
 {
     QString ret;
     foreach (const HeaderPair &header, m_headersList) {
         if (ret.length())
             ret.append(QLatin1String("\r\n"));
         ret = ret % QString::fromUtf8(header.first) % QLatin1String(": ")
                 % QString::fromUtf8(header.second);
     }
     return ret;
 }
networkAccessManager()
QNetworkAccessManager* QDeclarativeXMLHttpRequest::networkAccessManager () inline private
Definition at line 1016 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_new(), and requestFromUrl().
 { return m_nam; }
open()
QScriptValue QDeclarativeXMLHttpRequest::open (QScriptValue * me, const QString & method, const QUrl & url)
Definition at line 1055 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_open().
 {
     destroyNetwork();
     m_sendFlag = false;
     m_errorFlag = false;
     m_responseEntityBody = QByteArray();
     m_method = method;
     m_url = url;
     m_state = Opened;
     return dispatchCallback(me);
 }
printError()
void QDeclarativeXMLHttpRequest::printError (const QScriptValue & sv) private
Definition at line 1406 of file qdeclarativexmlhttprequest.cpp.
Referenced by downloadProgress(), error(), and finished().
 {
     QDeclarativeError error;
     QDeclarativeExpressionPrivate::exceptionToError(sv.engine(), error);
     QDeclarativeEnginePrivate::warning(QDeclarativeEnginePrivate::get(sv.engine()), error);
 }
rawResponseBody()
const QByteArray & QDeclarativeXMLHttpRequest::rawResponseBody () const
Definition at line 1395 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_responseXML().
 {
     return m_responseEntityBody;
 }
readEncoding()
void QDeclarativeXMLHttpRequest::readEncoding () private
Definition at line 1326 of file qdeclarativexmlhttprequest.cpp.
Referenced by finished().
 {
     foreach (const HeaderPair &header, m_headersList) {
         if (header.first == "content-type") {
             int separatorIdx = header.second.indexOf(';');
             if (separatorIdx == -1) {
                 m_mime == header.second;
             } else {
                 m_mime = header.second.mid(0, separatorIdx);
                 int charsetIdx = header.second.indexOf("charset=");
                 if (charsetIdx != -1) {
                     charsetIdx += 8;
                     separatorIdx = header.second.indexOf(';', charsetIdx);
                     m_charset = header.second.mid(charsetIdx, separatorIdx >= 0 ? separatorIdx : header.second.length());
                 }
             }
             break;
         }
     }
     if (m_mime.isEmpty() || m_mime == "text/xml" || m_mime == "application/xml" || m_mime.endsWith("+xml"))
         m_gotXml = true;
 }
readyState()
quint32 QDeclarativeXMLHttpRequest::readyState () const
Definition at line 1040 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_getAllResponseHeaders(), qmlxmlhttprequest_getResponseHeader(), qmlxmlhttprequest_readyState(), qmlxmlhttprequest_responseText(), qmlxmlhttprequest_responseXML(), qmlxmlhttprequest_send(), qmlxmlhttprequest_setRequestHeader(), qmlxmlhttprequest_status(), and qmlxmlhttprequest_statusText().
 {
     return m_state;
 }
receivedXml()
bool QDeclarativeXMLHttpRequest::receivedXml () const
Definition at line 1350 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_responseXML().
 {
     return m_gotXml;
 }
replyStatus()
int QDeclarativeXMLHttpRequest::replyStatus () const
Definition at line 1045 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_status().
 {
     return m_status;
 }
replyStatusText()
QString QDeclarativeXMLHttpRequest::replyStatusText () const
Definition at line 1050 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_statusText().
 {
     return m_statusText;
 }
requestFromUrl()
void QDeclarativeXMLHttpRequest::requestFromUrl (const QUrl & url) private
Definition at line 1117 of file qdeclarativexmlhttprequest.cpp.
Referenced by finished(), and send().
 {
     QNetworkRequest request = m_request;
     request.setUrl(url);
     if(m_method == QLatin1String("POST") ||
        m_method == QLatin1String("PUT")) {
         QVariant var = request.header(QNetworkRequest::ContentTypeHeader);
         if (var.isValid()) {
             QString str = var.toString();
             int charsetIdx = str.indexOf(QLatin1String("charset="));
             if (charsetIdx == -1) {
                 // No charset - append
                 if (!str.isEmpty()) str.append(QLatin1Char(';'));
                 str.append(QLatin1String("charset=UTF-8"));
             } else {
                 charsetIdx += 8;
                 int n = 0;
                 int semiColon = str.indexOf(QLatin1Char(';'), charsetIdx);
                 if (semiColon == -1) {
                     n = str.length() - charsetIdx;
                 } else {
                     n = semiColon - charsetIdx;
                 }
                 str.replace(charsetIdx, n, QLatin1String("UTF-8"));
             }
             request.setHeader(QNetworkRequest::ContentTypeHeader, str);
         } else {
             request.setHeader(QNetworkRequest::ContentTypeHeader,
                               QLatin1String("text/plain;charset=UTF-8"));
         }
     }
     if (xhrDump()) {
         qWarning().nospace() << "XMLHttpRequest: " << qPrintable(m_method) << " " << qPrintable(url.toString());
         if (!m_data.isEmpty()) {
             qWarning().nospace() << "                "
                                  << qPrintable(QString::fromUtf8(m_data));
         }
     }
     if (m_method == QLatin1String("GET"))
         m_network = networkAccessManager()->get(request);
     else if (m_method == QLatin1String("HEAD"))
         m_network = networkAccessManager()->head(request);
     else if(m_method == QLatin1String("POST"))
         m_network = networkAccessManager()->post(request, m_data);
     else if(m_method == QLatin1String("PUT"))
         m_network = networkAccessManager()->put(request, m_data);
     else if (m_method == QLatin1String("DELETE"))
         m_network = networkAccessManager()->deleteResource(request);
     QObject::connect(m_network, SIGNAL(downloadProgress(qint64,qint64)),
                      this, SLOT(downloadProgress(qint64)));
     QObject::connect(m_network, SIGNAL(error(QNetworkReply::NetworkError)),
                      this, SLOT(error(QNetworkReply::NetworkError)));
     QObject::connect(m_network, SIGNAL(finished()),
                      this, SLOT(finished()));
 }
responseBody()
QString QDeclarativeXMLHttpRequest::responseBody ()
Definition at line 1383 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_responseText().
 {
 #ifndef QT_NO_TEXTCODEC
     if (!m_textCodec)
         m_textCodec = findTextCodec();
     if (m_textCodec)
         return m_textCodec->toUnicode(m_responseEntityBody);
 #endif
     return QString::fromUtf8(m_responseEntityBody);
 }
send()
QScriptValue QDeclarativeXMLHttpRequest::send (QScriptValue * me, const QByteArray & data)
Definition at line 1177 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_send().
 {
     m_errorFlag = false;
     m_sendFlag = true;
     m_redirectCount = 0;
     m_data = data;
     m_me = *me;
     requestFromUrl(m_url);
     return QScriptValue();
 }
sendFlag()
bool QDeclarativeXMLHttpRequest::sendFlag () const
Definition at line 1030 of file qdeclarativexmlhttprequest.cpp.
Referenced by qmlxmlhttprequest_send(), and qmlxmlhttprequest_setRequestHeader().
 {
     return m_sendFlag;
 }
Properties
m_charset
QByteArray QDeclarativeXMLHttpRequest::m_charset private
Definition at line 997 of file qdeclarativexmlhttprequest.cpp.
Referenced by findTextCodec(), and readEncoding().
m_data
QByteArray QDeclarativeXMLHttpRequest::m_data private
Definition at line 987 of file qdeclarativexmlhttprequest.cpp.
Referenced by error(), finished(), requestFromUrl(), and send().
m_errorFlag
bool QDeclarativeXMLHttpRequest::m_errorFlag private
Definition at line 982 of file qdeclarativexmlhttprequest.cpp.
Referenced by abort(), error(), errorFlag(), open(), and send().
m_gotXml
bool QDeclarativeXMLHttpRequest::m_gotXml private
Definition at line 995 of file qdeclarativexmlhttprequest.cpp.
Referenced by findTextCodec(), readEncoding(), and receivedXml().
m_headersList
HeadersList QDeclarativeXMLHttpRequest::m_headersList private
Definition at line 992 of file qdeclarativexmlhttprequest.cpp.
Referenced by fillHeadersList(), header(), headers(), and readEncoding().
m_me
QScriptValue QDeclarativeXMLHttpRequest::m_me private
Definition at line 1004 of file qdeclarativexmlhttprequest.cpp.
Referenced by downloadProgress(), error(), finished(), and send().
m_method
QString QDeclarativeXMLHttpRequest::m_method private
Definition at line 984 of file qdeclarativexmlhttprequest.cpp.
Referenced by finished(), open(), and requestFromUrl().
m_mime
QByteArray QDeclarativeXMLHttpRequest::m_mime private
Definition at line 996 of file qdeclarativexmlhttprequest.cpp.
Referenced by findTextCodec(), and readEncoding().
m_nam
QNetworkAccessManager* QDeclarativeXMLHttpRequest::m_nam private
Definition at line 1015 of file qdeclarativexmlhttprequest.cpp.
m_network
QDeclarativeGuard<QNetworkReply> QDeclarativeXMLHttpRequest::m_network private
Definition at line 1012 of file qdeclarativexmlhttprequest.cpp.
Referenced by destroyNetwork(), downloadProgress(), error(), fillHeadersList(), finished(), and requestFromUrl().
m_redirectCount
int QDeclarativeXMLHttpRequest::m_redirectCount private
Definition at line 988 of file qdeclarativexmlhttprequest.cpp.
Referenced by finished(), and send().
m_request
QNetworkRequest QDeclarativeXMLHttpRequest::m_request private
Definition at line 1011 of file qdeclarativexmlhttprequest.cpp.
Referenced by abort(), addHeader(), error(), and requestFromUrl().
m_responseEntityBody
QByteArray QDeclarativeXMLHttpRequest::m_responseEntityBody private
Definition at line 986 of file qdeclarativexmlhttprequest.cpp.
Referenced by abort(), downloadProgress(), error(), findTextCodec(), finished(), open(), rawResponseBody(), and responseBody().
m_sendFlag
bool QDeclarativeXMLHttpRequest::m_sendFlag private
Definition at line 983 of file qdeclarativexmlhttprequest.cpp.
Referenced by abort(), open(), send(), and sendFlag().
m_state
State QDeclarativeXMLHttpRequest::m_state private
Definition at line 981 of file qdeclarativexmlhttprequest.cpp.
Referenced by abort(), downloadProgress(), error(), finished(), open(), and readyState().
m_status
int QDeclarativeXMLHttpRequest::m_status private
Definition at line 1009 of file qdeclarativexmlhttprequest.cpp.
Referenced by downloadProgress(), error(), finished(), and replyStatus().
m_statusText
QString QDeclarativeXMLHttpRequest::m_statusText private
Definition at line 1010 of file qdeclarativexmlhttprequest.cpp.
Referenced by downloadProgress(), error(), finished(), and replyStatusText().
m_textCodec
QTextCodec* QDeclarativeXMLHttpRequest::m_textCodec private
Definition at line 998 of file qdeclarativexmlhttprequest.cpp.
Referenced by responseBody().
m_url
QUrl QDeclarativeXMLHttpRequest::m_url private
Definition at line 985 of file qdeclarativexmlhttprequest.cpp.
Referenced by finished(), open(), and send().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativexmlhttprequest.cpp