Qt 4.8: QAbstractFileEngineIterator Class Reference
QAbstractFileEngineIterator Class Reference abstract
The QAbstractFileEngineIterator class provides an iterator interface for custom file engines.
#include <qabstractfileengine.h>
Public Functions
virtual QFileInfo currentFileInfo () const
The virtual function returns a QFileInfo for the current directory entry.
virtual QString currentFileName () const =0
This pure virtual function returns the name of the current directory entry, excluding the path.
QString currentFilePath () const
Returns the path to the current directory entry.
QDir::Filters filters () const
Returns the entry filters for this iterator.
virtual bool hasNext () const =0
This pure virtual function returns true if there is at least one more entry in the current directory (i.
QStringList nameFilters () const
Returns the name filters for this iterator.
virtual QString next ()=0
This pure virtual function advances the iterator to the next directory entry, and returns the file path to the current entry.
QString path () const
Returns the path for this iterator.
QAbstractFileEngineIterator (QDir::Filters filters, const QStringList &nameFilters)
Constructs a QAbstractFileEngineIterator, using the entry filters filters, and wildcard name filters nameFilters.
virtual ~QAbstractFileEngineIterator ()
Destroys the QAbstractFileEngineIterator.
Protected Types
enum EntryInfoType
This enum describes the different types of information that can be requested through the QAbstractFileEngineIterator::entryInfo() function.
Protected Functions
virtual QVariant entryInfo (EntryInfoType type) const
Returns the entry info type for this iterator's current directory entry as a QVariant.
Private Functions
void setPath (const QString &path)
Sets the iterator path to path.
Properties
QScopedPointer< QAbstractFileEngineIteratorPrivate > d
Friends
class QDirIterator
class QDirIteratorPrivate
Detailed Description
The QAbstractFileEngineIterator class provides an iterator interface for custom file engines.
Since
4.3
If all you want is to iterate over entries in a directory, see QDirIterator instead. This class is only for custom file engine authors.
QAbstractFileEngineIterator is a unidirectional single-use virtual iterator that plugs into QDirIterator, providing transparent proxy iteration for custom file engines.
You can subclass QAbstractFileEngineIterator to provide an iterator when writing your own file engine. To plug the iterator into your file system, you simply return an instance of this subclass from a reimplementation of QAbstractFileEngine::beginEntryList().
Example:
QAbstractFileEngineIterator *
CustomFileEngine::beginEntryList(QDir::Filters filters, const QStringList &filterNames)
{
    return new CustomFileEngineIterator(filters, filterNames);
}
QAbstractFileEngineIterator is associated with a path, name filters, and entry filters. The path is the directory that the iterator lists entries in. The name filters and entry filters are provided for file engines that can optimize directory listing at the iterator level (e.g., network file systems that need to minimize network traffic), but they can also be ignored by the iterator subclass; QAbstractFileEngineIterator already provides the required filtering logics in the matchesFilters() function. You can call dirName() to get the directory name, nameFilters() to get a stringlist of name filters, and filters() to get the entry filters.
The pure virtual function hasNext() returns true if the current directory has at least one more entry (i.e., the directory name is valid and accessible, and we have not reached the end of the entry list), and false otherwise. Reimplement next() to seek to the next entry.
The pure virtual function currentFileName() returns the name of the current entry without advancing the iterator. The currentFilePath() function is provided for convenience; it returns the full path of the current entry.
Here is an example of how to implement an iterator that returns each of three fixed entries in sequence.
class CustomIterator : public QAbstractFileEngineIterator
{
public:
    CustomIterator(const QStringList &nameFilters, QDir::Filters filters)
        : QAbstractFileEngineIterator(nameFilters, filters), index(0)
    {
        // In a real iterator, these entries are fetched from the
        // file system based on the value of path().
        entries << "entry1" << "entry2" << "entry3";
    }
    bool hasNext() const
    {
        return index < entries.size() - 1;
    }
    QString next()
    {
       if (!hasNext())
           return QString();
       ++index;
       return currentFilePath();
    }
    QString currentFileName()
    {
        return entries.at(index);
    }
private:
    QStringList entries;
    int index;
};
Note: QAbstractFileEngineIterator does not deal with QDir::IteratorFlags; it simply returns entries for a single directory.
See also
QDirIterator
Definition at line 214 of file qabstractfileengine.h.
Enumerations
EntryInfoType
enum QAbstractFileEngineIterator::EntryInfoType protected
This enum describes the different types of information that can be requested through the QAbstractFileEngineIterator::entryInfo() function.
Warning
This function is not part of the public interface.
Definition at line 232 of file qabstractfileengine.h.
{
     };
Constructors and Destructors
QAbstractFileEngineIterator()
QAbstractFileEngineIterator::QAbstractFileEngineIterator (QDir::Filters filters, const QStringList & nameFilters)
Constructs a QAbstractFileEngineIterator, using the entry filters filters, and wildcard name filters nameFilters.
Definition at line 926 of file qabstractfileengine.cpp.
     : d(new QAbstractFileEngineIteratorPrivate)
 {
     d->nameFilters = nameFilters;
     d->filters = filters;
 }
~QAbstractFileEngineIterator()
QAbstractFileEngineIterator::~QAbstractFileEngineIterator () virtual
Destroys the QAbstractFileEngineIterator.
See also
QDirIterator
Definition at line 939 of file qabstractfileengine.cpp.
 {
 }
Functions
currentFileInfo()
QFileInfo QAbstractFileEngineIterator::currentFileInfo () const virtual
The virtual function returns a QFileInfo for the current directory entry.
This function is provided for convenience. It can also be slightly faster than creating a QFileInfo object yourself, as the object returned by this function might contain cached information that QFileInfo otherwise would have to access through the file engine.
See also
currentFileName()
Reimplemented in QFSFileEngineIterator.
Definition at line 1029 of file qabstractfileengine.cpp.
Referenced by QDirIteratorPrivate::advance().
 {
     QString path = currentFilePath();
     if (d->fileInfo.filePath() != path)
         d->fileInfo.setFile(path);
     // return a shallow copy
     return d->fileInfo;
 }
currentFileName()
QString QAbstractFileEngineIterator::currentFileName () const pure virtual
This pure virtual function returns the name of the current directory entry, excluding the path.
See also
currentFilePath()
Implemented in QFSFileEngineIterator, and QResourceFileEngineIterator.
Referenced by QDirIteratorPrivate::advance(), and currentFilePath().
currentFilePath()
QString QAbstractFileEngineIterator::currentFilePath () const
Returns the path to the current directory entry.
It's the same as prepending path() to the return value of currentFileName().
See also
currentFileName()
Definition at line 1006 of file qabstractfileengine.cpp.
Referenced by currentFileInfo(), QResourceFileEngineIterator::next(), and QFSFileEngineIterator::next().
 {
     QString name = currentFileName();
     if (!name.isNull()) {
         QString tmp = path();
         if (!tmp.isEmpty()) {
             if (!tmp.endsWith(QLatin1Char('/')))
                 tmp.append(QLatin1Char('/'));
             name.prepend(tmp);
         }
     }
     return name;
 }
entryInfo()
QVariant QAbstractFileEngineIterator::entryInfo (EntryInfoType type) const protected virtual
Returns the entry info type for this iterator's current directory entry as a QVariant.
Warning
This function is not part of the public interface.
If type is undefined for this entry, a null QVariant is returned.
See also
QAbstractFileEngine::beginEntryList(), QDir::beginEntryList()
Definition at line 1051 of file qabstractfileengine.cpp.
 {
     Q_UNUSED(type)
     return QVariant();
 }
filters()
QDir::Filters QAbstractFileEngineIterator::filters () const
Returns the entry filters for this iterator.
See also
QDir::filter(), nameFilters(), path()
Definition at line 983 of file qabstractfileengine.cpp.
Referenced by QFSFileEngineIterator::hasNext(), and QAbstractFileEngineIterator().
 {
     return d->filters;
 }
hasNext()
bool QAbstractFileEngineIterator::hasNext () const pure virtual
This pure virtual function returns true if there is at least one more entry in the current directory (i.
e., the iterator path is valid and accessible, and the iterator has not reached the end of the entry list).
See also
QDirIterator::hasNext()
Implemented in QFSFileEngineIterator, and QResourceFileEngineIterator.
Referenced by QDirIteratorPrivate::advance().
nameFilters()
QStringList QAbstractFileEngineIterator::nameFilters () const
Returns the name filters for this iterator.
See also
QDir::nameFilters(), filters(), path()
Definition at line 973 of file qabstractfileengine.cpp.
Referenced by QFSFileEngineIterator::hasNext(), and QAbstractFileEngineIterator().
 {
     return d->nameFilters;
 }
next()
QString QAbstractFileEngineIterator::next () pure virtual
This pure virtual function advances the iterator to the next directory entry, and returns the file path to the current entry.
This function can optionally make use of nameFilters() and filters() to optimize its performance.
Reimplement this function in a subclass to advance the iterator.
See also
QDirIterator::next()
Implemented in QFSFileEngineIterator, and QResourceFileEngineIterator.
Referenced by QDirIteratorPrivate::advance().
path()
QString QAbstractFileEngineIterator::path () const
Returns the path for this iterator.
QDirIterator is responsible for assigning this path; it cannot change during the iterator's lifetime.
See also
nameFilters(), filters()
Definition at line 949 of file qabstractfileengine.cpp.
Referenced by currentFileInfo(), currentFilePath(), QResourceFileEngineIterator::hasNext(), QFSFileEngineIterator::hasNext(), and setPath().
 {
     return d->path;
 }
setPath()
void QAbstractFileEngineIterator::setPath (const QString & path) private
Sets the iterator path to path.
Warning
This function is not part of the public interface.
This function is called from within QDirIterator.
Definition at line 963 of file qabstractfileengine.cpp.
Referenced by QDirIteratorPrivate::pushDirectory().
 {
     d->path = path;
 }
Friends and Related Functions
QDirIterator
friend class QDirIterator friend
Definition at line 238 of file qabstractfileengine.h.
QDirIteratorPrivate
friend class QDirIteratorPrivate friend
Definition at line 239 of file qabstractfileengine.h.
Properties
d
QScopedPointer<QAbstractFileEngineIteratorPrivate> QAbstractFileEngineIterator::d private
Definition at line 241 of file qabstractfileengine.h.
Referenced by currentFileInfo(), QAbstractFileEngine::error(), QAbstractFileEngine::errorString(), filters(), nameFilters(), path(), QAbstractFileEngineIterator(), QAbstractFileEngine::setError(), and setPath().
The documentation for this class was generated from the following files:
/src/corelib/io/qabstractfileengine.h
/src/corelib/io/qabstractfileengine.cpp