Qt 4.8: QBrush Class Reference
QBrush Class Reference
The QBrush class defines the fill pattern of shapes drawn by QPainter.
#include <qbrush.h>
Public Types
typedef QScopedPointer< QBrushData, QBrushDataPointerDeleter > DataPtr
Public Functions
const QColor & color () const
Returns the brush color.
DataPtr & data_ptr ()
const QGradient * gradient () const
Returns the gradient describing this brush.
bool isDetached () const
bool isOpaque () const
Returns true if the brush is fully opaque otherwise false.
const QMatrix & matrix () const
Returns the current transformation matrix for the brush.
operator QVariant () const
Returns the brush as a QVariant.
bool operator!= (const QBrush &b) const
Returns true if the brush is different from the given brush; otherwise returns false.
QBrush & operator= (const QBrush &brush)
Assigns the given brush to this brush and returns a reference to this brush.
bool operator== (const QBrush &b) const
Returns true if the brush is equal to the given brush; otherwise returns false.
QBrush ()
Constructs a default black brush with the style Qt::NoBrush (i.e.
QBrush (Qt::BrushStyle bs)
Constructs a black brush with the given style.
QBrush (const QColor &color, Qt::BrushStyle bs=Qt::SolidPattern)
Constructs a brush with the given color and style.
QBrush (Qt::GlobalColor color, Qt::BrushStyle bs=Qt::SolidPattern)
Constructs a brush with the given color and style.
QBrush (const QColor &color, const QPixmap &pixmap)
Constructs a brush with the given color and the custom pattern stored in pixmap.
QBrush (Qt::GlobalColor color, const QPixmap &pixmap)
Constructs a brush with the given color and the custom pattern stored in pixmap.
QBrush (const QPixmap &pixmap)
Constructs a brush with a black color and a texture set to the given pixmap.
QBrush (const QImage &image)
Constructs a brush with a black color and a texture set to the given image.
QBrush (const QBrush &brush)
Constructs a copy of other.
QBrush (const QGradient &gradient)
Constructs a brush based on the given gradient.
void setColor (const QColor &color)
Sets the brush color to the given color.
void setColor (Qt::GlobalColor color)
Sets the brush color to the given color.
void setMatrix (const QMatrix &mat)
Sets matrix as an explicit transformation matrix on the current brush.
void setStyle (Qt::BrushStyle)
Sets the brush style to style.
void setTexture (const QPixmap &pixmap)
Sets the brush pixmap to pixmap.
void setTextureImage (const QImage &image)
Sets the brush image to image.
void setTransform (const QTransform &)
Sets matrix as an explicit transformation matrix on the current brush.
Qt::BrushStyle style () const
Returns the brush style.
void swap (QBrush &other)
Swaps brush other with this brush.
QPixmap texture () const
Returns the custom brush pattern, or a null pixmap if no custom brush pattern has been set.
QImage textureImage () const
Returns the custom brush pattern, or a null image if no custom brush pattern has been set.
QTransform transform () const
Returns the current transformation matrix for the brush.
~QBrush ()
Destroys the brush.
Private Functions
void cleanUp (QBrushData *x)
void detach (Qt::BrushStyle newStyle)
void init (const QColor &color, Qt::BrushStyle bs)
Initializes the brush.
Properties
QScopedPointer< QBrushData, QBrushDataPointerDeleter > d
Friends
bool Q_GUI_EXPORT qHasPixmapTexture (const QBrush &brush)
class QPainter
class QRasterPaintEngine
class QRasterPaintEnginePrivate
struct QSpanData
class QX11PaintEngine
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QBrush &brush)
Writes the given brush to the given stream and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QBrush &brush)
Reads the given brush from the given stream and returns a reference to the stream.
Detailed Description
The QBrush class defines the fill pattern of shapes drawn by QPainter.
A brush has a style, a color, a gradient and a texture.
The brush style() defines the fill pattern using the Qt::BrushStyle enum. The default brush style is Qt::NoBrush (depending on how you construct a brush). This style tells the painter to not fill shapes. The standard style for filling is Qt::SolidPattern. The style can be set when the brush is created using the appropriate constructor, and in addition the setStyle() function provides means for altering the style once the brush is constructed.
Brush Styles
The brush color() defines the color of the fill pattern. The color can either be one of Qt's predefined colors, Qt::GlobalColor, or any other custom QColor. The currently set color can be retrieved and altered using the color() and setColor() functions, respectively.
The gradient() defines the gradient fill used when the current style is either Qt::LinearGradientPattern, Qt::RadialGradientPattern or Qt::ConicalGradientPattern. Gradient brushes are created by giving a QGradient as a constructor argument when creating the QBrush. Qt provides three different gradients: QLinearGradient, QConicalGradient, and QRadialGradient
all of which inherit QGradient.
    QRadialGradient gradient(50, 50, 50, 50, 50);
    gradient.setColorAt(0, QColor::fromRgbF(0, 1, 0, 1));
    gradient.setColorAt(1, QColor::fromRgbF(0, 0, 0, 0));
    QBrush brush(gradient);
The texture() defines the pixmap used when the current style is Qt::TexturePattern. You can create a brush with a texture by providing the pixmap when the brush is created or by using setTexture().
Note that applying setTexture() makes style() == Qt::TexturePattern, regardless of previous style settings. Also, calling setColor() will not make a difference if the style is a gradient. The same is the case if the style is Qt::TexturePattern style unless the current texture is a QBitmap.
The isOpaque() function returns true if the brush is fully opaque otherwise false. A brush is considered opaque if:
The alpha component of the color() is 255.
Its texture() does not have an alpha channel and is not a QBitmap.
The colors in the gradient() all have an alpha component that is 255.
Outlines
To specify the style and color of lines and outlines, use the QPainter's QPen{pen} combined with Qt::PenStyle and Qt::GlobalColor:
QPainter painter(this);
painter.setBrush(Qt::cyan);
painter.setPen(Qt::darkCyan);
painter.drawRect(0, 0, 100,100);
painter.setBrush(Qt::NoBrush);
painter.setPen(Qt::darkGreen);
painter.drawRect(40, 40, 100, 100);
Note that, by default, QPainter renders the outline (using the currently set pen) when drawing shapes. Use Qt::NoPen{painter.setPen(Qt::NoPen)} to disable this behavior.
For more information about painting in general, see the Paint System.
See also
Qt::BrushStyle, QPainter, QColor
Definition at line 76 of file qbrush.h.
Typedefs
DataPtr
QBrush::DataPtr
Warning
This function is not part of the public interface.
Definition at line 151 of file qbrush.h.
Constructors and Destructors
QBrush() [1/10]
QBrush::QBrush ()
Constructs a default black brush with the style Qt::NoBrush (i.e.
this brush will not fill shapes).
Definition at line 426 of file qbrush.cpp.
Referenced by operator>>().
     : d(nullBrushInstance())
 {
     Q_ASSERT(d);
     d->ref.ref();
 }
QBrush() [2/10]
QBrush::QBrush (Qt::BrushStyle style)
Constructs a black brush with the given style.
See also
setStyle()
Definition at line 466 of file qbrush.cpp.
 {
     if (qbrush_check_type(style))
         init(Qt::black, style);
     else {
         d.reset(nullBrushInstance());
         d->ref.ref();
     }
 }
QBrush() [3/10]
QBrush::QBrush (const QColor & color, Qt::BrushStyle style = Qt::SolidPattern)
Constructs a brush with the given color and style.
See also
setColor(), setStyle()
Definition at line 482 of file qbrush.cpp.
 {
     if (qbrush_check_type(style))
         init(color, style);
     else {
         d.reset(nullBrushInstance());
         d->ref.ref();
     }
 }
QBrush() [4/10]
QBrush::QBrush (Qt::GlobalColor color, Qt::BrushStyle style = Qt::SolidPattern)
Constructs a brush with the given color and style.
See also
setColor(), setStyle()
Definition at line 502 of file qbrush.cpp.
 {
     if (qbrush_check_type(style))
         init(color, style);
     else {
         d.reset(nullBrushInstance());
         d->ref.ref();
     }
 }
QBrush() [5/10]
QBrush::QBrush (const QColor & color, const QPixmap & pixmap)
Constructs a brush with the given color and the custom pattern stored in pixmap.
The style is set to Qt::TexturePattern. The color will only have an effect for QBitmaps.
See also
setColor(), setPixmap()
Definition at line 522 of file qbrush.cpp.
 {
     init(color, Qt::TexturePattern);
     setTexture(pixmap);
 }
QBrush() [6/10]
QBrush::QBrush (Qt::GlobalColor color, const QPixmap & pixmap)
Constructs a brush with the given color and the custom pattern stored in pixmap.
The style is set to Qt::TexturePattern. The color will only have an effect for QBitmaps.
See also
setColor(), setPixmap()
Definition at line 538 of file qbrush.cpp.
 {
     init(color, Qt::TexturePattern);
     setTexture(pixmap);
 }
QBrush() [7/10]
QBrush::QBrush (const QPixmap & pixmap)
Constructs a brush with a black color and a texture set to the given pixmap.
The style is set to Qt::TexturePattern.
See also
setTexture()
Definition at line 440 of file qbrush.cpp.
 {
     init(Qt::black, Qt::TexturePattern);
     setTexture(pixmap);
 }
QBrush() [8/10]
QBrush::QBrush (const QImage & image)
Constructs a brush with a black color and a texture set to the given image.
The style is set to Qt::TexturePattern.
See also
setTextureImage()
Definition at line 454 of file qbrush.cpp.
 {
     init(Qt::black, Qt::TexturePattern);
     setTextureImage(image);
 }
QBrush() [9/10]
QBrush::QBrush (const QBrush & brush)
Constructs a copy of other.
Definition at line 548 of file qbrush.cpp.
     : d(other.d.data())
 {
     d->ref.ref();
 }
QBrush() [10/10]
QBrush::QBrush (const QGradient & gradient)
Constructs a brush based on the given gradient.
The brush style is set to the corresponding gradient style (either Qt::LinearGradientPattern, Qt::RadialGradientPattern or Qt::ConicalGradientPattern).
Definition at line 561 of file qbrush.cpp.
 {
     Q_ASSERT_X(gradient.type() != QGradient::NoGradient, "QBrush::QBrush",
                "QGradient should not be used directly, use the linear, radial\n"
                "or conical gradients instead");
     const Qt::BrushStyle enum_table[] = {
         Qt::LinearGradientPattern,
         Qt::RadialGradientPattern,
         Qt::ConicalGradientPattern
     };
     init(QColor(), enum_table[gradient.type()]);
     QGradientBrushData *grad = static_cast<QGradientBrushData *>(d.data());
     grad->gradient = gradient;
 }
~QBrush()
QBrush::~QBrush ()
Destroys the brush.
Definition at line 582 of file qbrush.cpp.
 {
 }
Functions
cleanUp()
void QBrush::cleanUp (QBrushData * x) private
Definition at line 586 of file qbrush.cpp.
 {
     QBrushDataPointerDeleter::deleteData(x);
 }
color()
const QColor & QBrush::color () const inline
Returns the brush color.
See also
setColor()
Definition at line 183 of file qbrush.h.
Referenced by QTextEditPrivate::_q_currentCharFormatChanged(), QPdfEnginePrivate::addBrushPattern(), QAccessibleTextWidget::attributes(), QRenderRule::configurePalette(), QCalendarModel::data(), QTextLine::draw(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QCommonStyle::drawComplexControl(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QWindowsStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QMotifStyle::drawComplexControl(), QStyleSheetStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QCommonStyle::drawControl(), QWindowsVistaStyle::drawControl(), QWindowsMobileStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QMacStyle::drawControl(), QStyleSheetStyle::drawControl(), QStyleHelper::drawDial(), QWindowsCEStyle::drawItemText(), QStyle::drawItemText(), QPainterPrivate::drawOpaqueBackground(), QWindowsMobileStylePrivate::drawPanelItemViewSelected(), QWindowsCEStyle::drawPrimitive(), QCommonStyle::drawPrimitive(), QWindowsVistaStyle::drawPrimitive(), QWindowsMobileStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QCDEStyle::drawPrimitive(), QWindowsXPStyle::drawPrimitive(), QWindowsStyle::drawPrimitive(), QGtkStyle::drawPrimitive(), QMotifStyle::drawPrimitive(), QMacStyle::drawPrimitive(), QDirectFBPaintEngine::drawRects(), QWindowsMobileStylePrivate::drawScrollbarGroove(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), QLCDNumberPrivate::drawSegment(), QWindowsMobileStylePrivate::drawTabBarTab(), QWin32PrintEngine::drawTextItem(), QWindowsCEStylePrivate::drawWinCEButton(), QWindowsCEStylePrivate::drawWinCEPanel(), QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitCharFormatStyle(), QTextHtmlExporter::emitFrameStyle(), QVGCompositionHelper::fillBackground(), QX11PaintEnginePrivate::fillPolygon_dev(), QDirectFBPaintEngine::fillRect(), QVGPaintEngine::fillRect(), QPainter::fillRect(), QOpenGLPaintEnginePrivate::flushDrawQueue(), QWindowsMobileStyle::generatedIconPixmap(), getPatternFill(), hash(), QTextControlPrivate::inputMethodEvent(), make_widget_eventUPP(), QWidgetPrivate::mapFromGlobal(), operator<<(), operator>>(), QScreen::paintBackground(), QDecorationWindows::paintButton(), QCommandLinkButton::paintEvent(), QLabel::paintEvent(), QLineEdit::paintEvent(), QWizardHeader::paintEvent(), QColorLuminancePicker::paintEvent(), QmlJSDebugger::ColorPickerTool::pickColor(), QWindowsStyle::polish(), QWindowsXPStyle::polish(), QWindowsVistaStyle::polish(), QWindowsMobileStyle::polish(), QCleanlooksStyle::polish(), QLineControl::processInputMethodEvent(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QSvgPaintEngine::qbrushToSvg(), qDrawEdge(), qDrawPlainRect(), qDrawRoundedCorners(), qDrawShadeLine(), qDrawShadePanel(), qDrawShadeRect(), qDrawWinButton(), qDrawWinPanel(), qt_cleanlooks_draw_mdibutton(), qt_graphicsItem_highlightSelected(), qt_mac_display_change_callbk(), qt_plastique_draw_handle(), qt_plastique_drawFrame(), qt_plastique_drawShadedPanel(), qt_set_windows_color_resources(), QPainter::setBackground(), QVGPaintEnginePrivate::setBrush(), QPainter::setBrush(), QPalette::setColorGroup(), QOpenGLPaintEnginePrivate::setGradientOps(), QPdfBaseEngine::setPen(), QSpanData::setup(), QInputContext::standardFormat(), QCleanlooksStyle::standardPalette(), QGtkStyle::standardPalette(), QWindowsMobileStyle::standardPixmap(), QCleanlooksStyle::styleHint(), QStyleSheetStyle::styleHint(), QPicturePaintEngine::updateBackground(), QX11PaintEngine::updateBrush(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QPainterPrivate::updateEmulationSpecifier(), QWin32PrintEngine::updateState(), QTextOdfWriter::writeBlockFormat(), and QTextOdfWriter::writeCharacterFormat().
 { return d->color; }
data_ptr()
DataPtr & QBrush::data_ptr () inline
Warning
This function is not part of the public interface.
Definition at line 152 of file qbrush.h.
 { return d; }
detach()
void QBrush::detach (Qt::BrushStyle newStyle) private
Definition at line 592 of file qbrush.cpp.
Referenced by setColor(), setStyle(), setTexture(), setTextureImage(), and setTransform().
 {
     if (newStyle == d->style && d->ref == 1)
         return;
     QScopedPointer<QBrushData> x;
     switch(newStyle) {
     case Qt::TexturePattern: {
         QTexturedBrushData *tbd = new QTexturedBrushData;
         if (d->style == Qt::TexturePattern) {
             QTexturedBrushData *data = static_cast<QTexturedBrushData *>(d.data());
             if (data->m_has_pixmap_texture)
                 tbd->setPixmap(data->pixmap());
             else
                 tbd->setImage(data->image());
         }
         x.reset(tbd);
         break;
         }
     case Qt::LinearGradientPattern:
     case Qt::RadialGradientPattern:
     case Qt::ConicalGradientPattern:
         x.reset(new QGradientBrushData);
         static_cast<QGradientBrushData *>(x.data())->gradient =
             static_cast<QGradientBrushData *>(d.data())->gradient;
         break;
     default:
         x.reset(new QBrushData);
         break;
     }
     x->ref = 1;
     x->style = newStyle;
     x->color = d->color;
     x->transform = d->transform;
     d.reset(x.take());
 }
gradient()
const QGradient * QBrush::gradient () const
Returns the gradient describing this brush.
Definition at line 871 of file qbrush.cpp.
Referenced by cgColorForQColor(), QPainterPrivate::checkEmulation(), coordinateMode(), detach(), QPlastiqueStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), QCleanlooksStyle::drawPrimitive(), QEmulationPaintEngine::drawTextItem(), QCoreGraphicsPaintEngine::drawTextItem(), QEmulationPaintEngine::fill(), fillBackground(), QPainter::fillPath(), QPainter::fillRect(), fillRegion(), isOpaque(), needsResolving(), operator<<(), QBrush(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), QSvgPaintEngine::qbrushToSvg(), qMapBrushToRect(), qt_isExtendedRadialGradient(), rasterFallbackWarn(), QVGPaintEnginePrivate::setBrush(), QSpanData::setup(), stretchGradientToUserSpace(), QEmulationPaintEngine::stroke(), QPainter::strokePath(), QCoreGraphicsPaintEngine::updateBrush(), QGL2PaintEngineExPrivate::updateBrushTexture(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QOpenGLPaintEnginePrivate::updateGradient(), and QPdfEnginePrivate::~QPdfEnginePrivate().
 {
     if (d->style == Qt::LinearGradientPattern
         || d->style == Qt::RadialGradientPattern
         || d->style == Qt::ConicalGradientPattern) {
         return &static_cast<const QGradientBrushData *>(d.data())->gradient;
     }
     return 0;
 }
init()
void QBrush::init (const QColor & color, Qt::BrushStyle style) private
Initializes the brush.
Warning
This function is not part of the public interface.
Definition at line 396 of file qbrush.cpp.
Referenced by QBrush().
 {
     switch(style) {
     case Qt::NoBrush:
         d.reset(nullBrushInstance());
         d->ref.ref();
         if (d->color != color) setColor(color);
         return;
     case Qt::TexturePattern:
         d.reset(new QTexturedBrushData);
         break;
     case Qt::LinearGradientPattern:
     case Qt::RadialGradientPattern:
     case Qt::ConicalGradientPattern:
         d.reset(new QGradientBrushData);
         break;
     default:
         d.reset(new QBrushData);
         break;
     }
     d->ref = 1;
     d->style = style;
     d->color = color;
 }
isDetached()
bool QBrush::isDetached () const inline
Warning
This function is not part of the public interface.
Definition at line 186 of file qbrush.h.
 { return d->ref == 1; }
isOpaque()
bool QBrush::isOpaque () const
Returns true if the brush is fully opaque otherwise false.
A brush is considered opaque if:
The alpha component of the color() is 255.
Its texture() does not have an alpha channel and is not a QBitmap.
The colors in the gradient() all have an alpha component that is 255.
It is an extended radial gradient.
Definition at line 910 of file qbrush.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), QPaintEngineEx::drawPoints(), QGL2PaintEngineExPrivate::fill(), QVGPaintEngine::fillRect(), QWidgetPrivate::init(), QWidgetPrivate::isBackgroundInherited(), QWidgetPrivate::mapFromGlobal(), QWidgetPrivate::paintBackground(), QGraphicsView::paintEvent(), QMdiArea::setBackground(), QPdfBaseEngine::setPen(), QSpanData::setup(), QGL2PaintEngineExPrivate::stroke(), QX11PaintEngine::updateBrush(), QPainterPrivate::updateEmulationSpecifier(), QDirectFBWindowSurface::updateIsOpaque(), QWidgetPrivate::updateIsOpaque(), QAlphaPaintEngine::updateState(), QPdfBaseEngine::updateState(), and QPdfEnginePrivate::~QPdfEnginePrivate().
 {
     bool opaqueColor = d->color.alpha() == 255;
     // Test awfully simple case first
     if (d->style == Qt::SolidPattern)
         return opaqueColor;
     if (qt_isExtendedRadialGradient(*this))
         return false;
     if (d->style == Qt::LinearGradientPattern
         || d->style == Qt::RadialGradientPattern
         || d->style == Qt::ConicalGradientPattern) {
         QGradientStops stops = gradient()->stops();
         for (int i=0; i<stops.size(); ++i)
             if (stops.at(i).second.alpha() != 255)
                 return false;
         return true;
     } else if (d->style == Qt::TexturePattern) {
         return qHasPixmapTexture(*this)
             ? !texture().hasAlphaChannel() && !texture().isQBitmap()
             : !textureImage().hasAlphaChannel();
     }
     return false;
 }
matrix()
const QMatrix & QBrush::matrix () const inline
Returns the current transformation matrix for the brush.
Since
4.2
See also
setMatrix()
Definition at line 184 of file qbrush.h.
Referenced by setTransform().
 { return d->transform.toAffine(); }
operator QVariant()
QBrush::operator QVariant () const
Returns the brush as a QVariant.
Definition at line 665 of file qbrush.cpp.
 {
     return QVariant(QVariant::Brush, this);
 }
operator!=()
bool QBrush::operator!= (const QBrush & brush) const inline
Returns true if the brush is different from the given brush; otherwise returns false.
Two brushes are different if they have different styles, colors or transforms or different pixmaps or gradients depending on the style.
See also
operator==()
Definition at line 127 of file qbrush.h.
 { return !(operator==(b)); }
operator=()
QBrush & QBrush::operator= (const QBrush & brush)
Assigns the given brush to this brush and returns a reference to this brush.
Definition at line 640 of file qbrush.cpp.
 {
     if (d == b.d)
         return *this;
     b.d->ref.ref();
     d.reset(b.d.data());
     return *this;
 }
operator==()
bool QBrush::operator== (const QBrush & brush) const
Returns true if the brush is equal to the given brush; otherwise returns false.
Two brushes are equal if they have equal styles, colors and transforms and equal pixmaps or gradients depending on the style.
See also
operator!=()
Definition at line 1017 of file qbrush.cpp.
 {
     if (b.d == d)
         return true;
     if (b.d->style != d->style || b.d->color != d->color || b.d->transform != d->transform)
         return false;
     switch (d->style) {
     case Qt::TexturePattern:
         {
             const QPixmap &us = (static_cast<QTexturedBrushData *>(d.data()))->pixmap();
             const QPixmap &them = (static_cast<QTexturedBrushData *>(b.d.data()))->pixmap();
             return ((us.isNull() && them.isNull()) || us.cacheKey() == them.cacheKey());
         }
     case Qt::LinearGradientPattern:
     case Qt::RadialGradientPattern:
     case Qt::ConicalGradientPattern:
         {
             const QGradientBrushData *d1 = static_cast<QGradientBrushData *>(d.data());
             const QGradientBrushData *d2 = static_cast<QGradientBrushData *>(b.d.data());
             return d1->gradient == d2->gradient;
         }
     default:
         return true;
     }
 }
setColor() [1/2]
void QBrush::setColor (const QColor & color)
Sets the brush color to the given color.
Note that calling setColor() will not make a difference if the style is a gradient. The same is the case if the style is Qt::TexturePattern style unless the current texture is a QBitmap.
See also
color()
Definition at line 725 of file qbrush.cpp.
Referenced by QSvgAnimateColor::apply(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), qBrushDark(), qBrushLight(), and qBrushSetAlphaF().
 {
     detach(d->style);
     d->color = c;
 }
setColor() [2/2]
void QBrush::setColor (Qt::GlobalColor color) inline
Sets the brush color to the given color.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 155 of file qbrush.h.
 { setColor(QColor(acolor)); }
setMatrix()
void QBrush::setMatrix (const QMatrix & matrix)
Sets matrix as an explicit transformation matrix on the current brush.
Since
4.2
The brush transformation matrix is merged with QPainter transformation matrix to produce the final result.
See also
matrix()
Definition at line 951 of file qbrush.cpp.
Referenced by QSvgGradientStyle::brush().
 {
     setTransform(QTransform(matrix));
 }
setStyle()
void QBrush::setStyle (Qt::BrushStyle style)
Sets the brush style to style.
See also
style()
Definition at line 687 of file qbrush.cpp.
 {
     if (d->style == style)
         return;
     if (qbrush_check_type(style)) {
         detach(style);
         d->style = style;
     }
 }
setTexture()
void QBrush::setTexture (const QPixmap & pixmap)
Sets the brush pixmap to pixmap.
The style is set to Qt::TexturePattern.
The current brush color will only have an effect for monochrome pixmaps, i.e. for QPixmap::depth() == 1 (QBitmap{QBitmaps}).
See also
texture()
Definition at line 802 of file qbrush.cpp.
Referenced by QBrush(), qBrushDark(), qBrushLight(), and qBrushSetAlphaF().
 {
     if (!pixmap.isNull()) {
         detach(Qt::TexturePattern);
         QTexturedBrushData *data = static_cast<QTexturedBrushData *>(d.data());
         data->setPixmap(pixmap);
     } else {
         detach(Qt::NoBrush);
     }
 }
setTextureImage()
void QBrush::setTextureImage (const QImage & image)
Sets the brush image to image.
Since
4.2
The style is set to Qt::TexturePattern.
Note the current brush color will not have any affect on monochrome images, as opposed to calling setTexture() with a QBitmap. If you want to change the color of monochrome image brushes, either convert the image to QBitmap with QBitmap::fromImage() and set the resulting QBitmap as a texture, or change the entries in the color table for the image.
See also
textureImage(), setTexture()
Definition at line 856 of file qbrush.cpp.
Referenced by QWindowsMobileStylePrivate::drawScrollbarGroove(), and QBrush().
 {
     if (!image.isNull()) {
         detach(Qt::TexturePattern);
         QTexturedBrushData *data = static_cast<QTexturedBrushData *>(d.data());
         data->setImage(image);
     } else {
         detach(Qt::NoBrush);
     }
 }
setTransform()
void QBrush::setTransform (const QTransform & matrix)
Sets matrix as an explicit transformation matrix on the current brush.
Since
4.3
The brush transformation matrix is merged with QPainter transformation matrix to produce the final result.
See also
transform()
Definition at line 968 of file qbrush.cpp.
Referenced by QOpenGLPaintEnginePrivate::drawImageAsPath(), QEmulationPaintEngine::drawTextItem(), QOpenGLPaintEnginePrivate::drawTiledImageAsPath(), QVGPaintEngine::drawTiledPixmap(), QEmulationPaintEngine::fill(), fillBackground(), operator>>(), setMatrix(), stretchGradientToUserSpace(), QEmulationPaintEngine::stroke(), and QPaintEngineEx::stroke().
 {
     detach(d->style);
     d->transform = matrix;
 }
style()
Qt::BrushStyle QBrush::style () const inline
Returns the brush style.
See also
setStyle()
Definition at line 182 of file qbrush.h.
Referenced by QPdfEnginePrivate::addBrushPattern(), QTextHtmlParserNode::applyCssDeclarations(), QAccessibleTextWidget::attributes(), QRenderRule::configurePalette(), coordinateMode(), QVGPaintEnginePrivate::draw(), QSvgPolyline::draw(), QTextLayout::draw(), QTextLine::draw(), QRenderRule::drawBackground(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QOpenGLPaintEnginePrivate::drawItem(), QPainterPrivate::drawOpaqueBackground(), QWindowsVistaStyle::drawPrimitive(), QPlastiqueStyle::drawPrimitive(), QDirectFBPaintEngine::drawRects(), QPainterPrivate::drawStretchedGradient(), QTextDocumentLayoutPrivate::drawTableCell(), QWin32PrintEngine::drawTextItem(), QWidgetPrivate::drawWidget(), QTextHtmlExporter::emitBackgroundAttribute(), QTextHtmlExporter::emitBlockAttributes(), QTextHtmlExporter::emitCharFormatStyle(), QRasterPaintEngine::ensureBrush(), QEmulationPaintEngine::fill(), QOpenGLPaintEngine::fill(), QDirectFBPaintEngine::fill(), QVGPaintEnginePrivate::fill(), QVGCompositionHelper::fillBackground(), fillBackground(), QX11PaintEnginePrivate::fillPolygon_dev(), QBlitterPaintEngine::fillRect(), QDirectFBPaintEngine::fillRect(), QVGPaintEngine::fillRect(), QPainter::fillRect(), fillRegion(), QRenderRule::fixupBorder(), QOpenGLPaintEnginePrivate::flushDrawQueue(), getPatternFill(), hash(), QWidgetPrivate::init(), QTextControlPrivate::inputMethodEvent(), is_brush_transparent(), QWidgetPrivate::isBackgroundInherited(), QWidgetPrivate::mapFromGlobal(), needsResolving(), operator<<(), operator>>(), QScreen::paintBackground(), QPdf::patternForBrush(), QGL2PaintEngineExPrivate::prepareForDraw(), QTextHtmlImporter::processBlockNode(), QLineControl::processInputMethodEvent(), QTextHtmlImporter::processSpecialNodes(), QSvgPaintEngine::qbrushToSvg(), qHasPixmapTexture(), QRenderRule::QRenderRule(), qt_isExtendedRadialGradient(), QTextHtmlImporter::scanTable(), QWorkspace::setBackground(), QPainter::setBackground(), QDirectFBPaintEnginePrivate::setBrush(), QVGPaintEnginePrivate::setBrush(), QPainter::setBrush(), QGL2PaintEngineExPrivate::setBrush(), QOpenGLPaintEnginePrivate::setGradientOps(), QGraphicsOpacityEffect::setOpacityMask(), QDirectFBPaintEnginePrivate::setPen(), QPainter::setPen(), QPdfBaseEngine::setPen(), setPenAndDrawBackground(), setStyle(), stretchGradientToUserSpace(), QSvgNode::strokeWidth(), QStyleSheetStyle::styleHint(), QPicturePaintEngine::updateBackground(), QPicturePaintEngine::updateBrush(), QOpenGLPaintEngine::updateBrush(), QGL2PaintEngineExPrivate::updateBrushTexture(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QPainterPrivate::updateEmulationSpecifier(), QOpenGLPaintEnginePrivate::updateGradient(), QDirectFBWindowSurface::updateIsOpaque(), QWidgetPrivate::updateIsOpaque(), QOpenGLPaintEngine::updatePen(), QAlphaPaintEngine::updateState(), QWin32PrintEngine::updateState(), QOpenGLPaintEngine::updateState(), and QPdfBaseEngine::updateState().
 { return d->style; }
swap()
void QBrush::swap (QBrush & other) inline
Swaps brush other with this brush.
Since
4.8
This operation is very fast and never fails.
Definition at line 99 of file qbrush.h.
 { qSwap(d, other.d); }
texture()
QPixmap QBrush::texture () const
Returns the custom brush pattern, or a null pixmap if no custom brush pattern has been set.
See also
setTexture()
Definition at line 785 of file qbrush.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), QPlastiqueStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), QWidgetPrivate::drawWidget(), QTextHtmlExporter::emitBackgroundAttribute(), QX11PaintEnginePrivate::fillPolygon_dev(), QBlitterPaintEngine::fillRect(), QDirectFBPaintEngine::fillRect(), fillRegion(), is_brush_transparent(), isOpaque(), QWidgetPrivate::mapFromGlobal(), operator<<(), qBrushDark(), qBrushLight(), qBrushSetAlphaF(), qt_mac_display_change_callbk(), qt_mac_fill_background(), QVGPaintEnginePrivate::setBrush(), QGL2PaintEngineExPrivate::setBrush(), QOpenGLPaintEnginePrivate::setGradientOps(), QSpanData::setup(), QGL2PaintEngineExPrivate::updateBrushTexture(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QPainterPrivate::updateEmulationSpecifier(), and QOpenGLPaintEnginePrivate::updateFragmentProgramData().
 {
     return d->style == Qt::TexturePattern
                      ? (static_cast<QTexturedBrushData *>(d.data()))->pixmap()
                      : QPixmap();
 }
textureImage()
QImage QBrush::textureImage () const
Returns the custom brush pattern, or a null image if no custom brush pattern has been set.
Since
4.2
If the texture was set as a QPixmap it will be converted to a QImage.
See also
setTextureImage()
Definition at line 829 of file qbrush.cpp.
Referenced by QOpenGLPaintEnginePrivate::composite(), QTextHtmlExporter::emitBackgroundAttribute(), is_brush_transparent(), isOpaque(), QSpanData::setup(), and QPainterPrivate::updateEmulationSpecifier().
 {
     return d->style == Qt::TexturePattern
                      ? (static_cast<QTexturedBrushData *>(d.data()))->image()
                      : QImage();
 }
transform()
QTransform QBrush::transform () const inline
Returns the current transformation matrix for the brush.
Since
4.3
See also
setTransform()
Definition at line 185 of file qbrush.h.
Referenced by QEmulationPaintEngine::drawTextItem(), QEmulationPaintEngine::fill(), QBlitterPaintEngine::fillRect(), QDirectFBPaintEngine::fillRect(), operator<<(), operator>>(), QGL2PaintEngineExPrivate::setBrush(), QVGPaintEnginePrivate::setBrushTransform(), stretchGradientToUserSpace(), QEmulationPaintEngine::stroke(), QPaintEngineEx::stroke(), QRasterPaintEngine::updateBrush(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QPainterPrivate::updateEmulationSpecifier(), QOpenGLPaintEnginePrivate::updateGradient(), QRasterPaintEnginePrivate::updateMatrixData(), and QRasterPaintEngine::updatePen().
 { return d->transform; }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QBrush & brush) related
Writes the given brush to the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 1111 of file qbrush.cpp.
 {
     quint8 style = (quint8) b.style();
     bool gradient_style = false;
     if (style == Qt::LinearGradientPattern || style == Qt::RadialGradientPattern
         || style == Qt::ConicalGradientPattern)
         gradient_style = true;
     if (s.version() < QDataStream::Qt_4_0 && gradient_style)
         style = Qt::NoBrush;
     s << style << b.color();
     if (b.style() == Qt::TexturePattern) {
         s << b.texture();
     } else if (s.version() >= QDataStream::Qt_4_0 && gradient_style) {
         const QGradient *gradient = b.gradient();
         int type_as_int = int(gradient->type());
         s << type_as_int;
         if (s.version() >= QDataStream::Qt_4_3) {
             s << int(gradient->spread());
             s << int(gradient->coordinateMode());
         }
         if (s.version() >= QDataStream::Qt_4_5)
             s << int(gradient->interpolationMode());
         if (sizeof(qreal) == sizeof(double)) {
             s << gradient->stops();
         } else {
             // ensure that we write doubles here instead of streaming the stops
             // directly; otherwise, platforms that redefine qreal might generate
             // data that cannot be read on other platforms.
             QVector<QGradientStop> stops = gradient->stops();
             s << quint32(stops.size());
             for (int i = 0; i < stops.size(); ++i) {
                 const QGradientStop &stop = stops.at(i);
                 s << QPair<double, QColor>(double(stop.first), stop.second);
             }
         }
         if (gradient->type() == QGradient::LinearGradient) {
             s << static_cast<const QLinearGradient *>(gradient)->start();
             s << static_cast<const QLinearGradient *>(gradient)->finalStop();
         } else if (gradient->type() == QGradient::RadialGradient) {
             s << static_cast<const QRadialGradient *>(gradient)->center();
             s << static_cast<const QRadialGradient *>(gradient)->focalPoint();
             s << (double) static_cast<const QRadialGradient *>(gradient)->radius();
         } else { // type == Conical
             s << static_cast<const QConicalGradient *>(gradient)->center();
             s << (double) static_cast<const QConicalGradient *>(gradient)->angle();
         }
     }
     if (s.version() >= QDataStream::Qt_4_3)
         s << b.transform();
     return s;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QBrush & brush) related
Reads the given brush from the given stream and returns a reference to the stream.
See also
{Serializing Qt Data Types}
Definition at line 1182 of file qbrush.cpp.
 {
     quint8 style;
     QColor color;
     s >> style;
     s >> color;
     if (style == Qt::TexturePattern) {
         QPixmap pm;
         s >> pm;
         b = QBrush(color, pm);
     } else if (style == Qt::LinearGradientPattern
                || style == Qt::RadialGradientPattern
                || style == Qt::ConicalGradientPattern) {
         int type_as_int;
         QGradient::Type type;
         QGradientStops stops;
         QGradient::CoordinateMode cmode = QGradient::LogicalMode;
         QGradient::Spread spread = QGradient::PadSpread;
         QGradient::InterpolationMode imode = QGradient::ColorInterpolation;
         s >> type_as_int;
         type = QGradient::Type(type_as_int);
         if (s.version() >= QDataStream::Qt_4_3) {
             s >> type_as_int;
             spread = QGradient::Spread(type_as_int);
             s >> type_as_int;
             cmode = QGradient::CoordinateMode(type_as_int);
         }
         if (s.version() >= QDataStream::Qt_4_5) {
             s >> type_as_int;
             imode = QGradient::InterpolationMode(type_as_int);
         }
         if (sizeof(qreal) == sizeof(double)) {
             s >> stops;
         } else {
             quint32 numStops;
             double n;
             QColor c;
             s >> numStops;
             for (quint32 i = 0; i < numStops; ++i) {
                 s >> n >> c;
                 stops << QPair<qreal, QColor>(n, c);
             }
         }
         if (type == QGradient::LinearGradient) {
             QPointF p1, p2;
             s >> p1;
             s >> p2;
             QLinearGradient lg(p1, p2);
             lg.setStops(stops);
             lg.setSpread(spread);
             lg.setCoordinateMode(cmode);
             lg.setInterpolationMode(imode);
             b = QBrush(lg);
         } else if (type == QGradient::RadialGradient) {
             QPointF center, focal;
             double radius;
             s >> center;
             s >> focal;
             s >> radius;
             QRadialGradient rg(center, radius, focal);
             rg.setStops(stops);
             rg.setSpread(spread);
             rg.setCoordinateMode(cmode);
             rg.setInterpolationMode(imode);
             b = QBrush(rg);
         } else { // type == QGradient::ConicalGradient
             QPointF center;
             double angle;
             s >> center;
             s >> angle;
             QConicalGradient cg(center, angle);
             cg.setStops(stops);
             cg.setSpread(spread);
             cg.setCoordinateMode(cmode);
             cg.setInterpolationMode(imode);
             b = QBrush(cg);
         }
     } else {
         b = QBrush(color, (Qt::BrushStyle)style);
     }
     if (s.version() >= QDataStream::Qt_4_3) {
         QTransform transform;
         s >> transform;
         b.setTransform(transform);
     }
     return s;
 }
qHasPixmapTexture
bool Q_GUI_EXPORT qHasPixmapTexture (const QBrush & brush) friend
Definition at line 223 of file qbrush.cpp.
Referenced by isOpaque().
 {
     if (brush.style() != Qt::TexturePattern)
         return false;
     QTexturedBrushData *tx_data = static_cast<QTexturedBrushData *>(brush.d.data());
     return tx_data->m_has_pixmap_texture;
 }
QPainter
friend class QPainter friend
Definition at line 142 of file qbrush.h.
QRasterPaintEngine
friend class QRasterPaintEngine friend
Definition at line 139 of file qbrush.h.
QRasterPaintEnginePrivate
friend class QRasterPaintEnginePrivate friend
Definition at line 140 of file qbrush.h.
QSpanData
friend struct QSpanData friend
Definition at line 141 of file qbrush.h.
QX11PaintEngine
friend class QX11PaintEngine friend
Definition at line 137 of file qbrush.h.
Properties
d
QScopedPointer<QBrushData, QBrushDataPointerDeleter> QBrush::d private
Definition at line 146 of file qbrush.h.
Referenced by detach(), gradient(), isOpaque(), operator=(), operator==(), QBrush(), qHasPixmapTexture(), QPainter::setBrush(), setColor(), setStyle(), setTexture(), setTextureImage(), setTransform(), swap(), texture(), textureImage(), and QRasterPaintEnginePrivate::updateMatrixData().
The documentation for this class was generated from the following files:
/src/gui/painting/qbrush.h
/src/gui/painting/qbrush.cpp