Qt 4.8: QScriptDebuggerValue Class Reference
QScriptDebuggerValue Class Reference
The QScriptDebuggerValue class represents a script value.
#include <qscriptdebuggervalue_p.h>
Public Types
enum ValueType {
NoValue, UndefinedValue, NullValue, BooleanValue,
StringValue, NumberValue, ObjectValue
}
Public Functions
bool booleanValue () const
Returns this value as a boolean.
double numberValue () const
Returns this value as a number.
qint64 objectId () const
Returns this value as an object ID.
bool operator!= (const QScriptDebuggerValue &other) const
Returns true if this QScriptDebuggerValue is not equal to the other value, otherwise returns false.
QScriptDebuggerValue & operator= (const QScriptDebuggerValue &other)
bool operator== (const QScriptDebuggerValue &other) const
Returns true if this QScriptDebuggerValue is equal to the other value, otherwise returns false.
QScriptDebuggerValue ()
QScriptDebuggerValue (const QScriptValue &value)
QScriptDebuggerValue (double value)
QScriptDebuggerValue (bool value)
QScriptDebuggerValue (const QString &value)
QScriptDebuggerValue (qint64 objectId)
QScriptDebuggerValue (ValueType type)
QScriptDebuggerValue (const QScriptDebuggerValue &other)
QString stringValue () const
Returns this value as a string.
QScriptValue toScriptValue (QScriptEngine *engine) const
Converts this QScriptDebuggerValue to a QScriptValue in the given engine and returns the resulting value.
QString toString () const
Returns a string representation of this value.
ValueType type () const
Returns the type of this value.
~QScriptDebuggerValue ()
Properties
QScopedSharedPointer< QScriptDebuggerValuePrivate > d_ptr
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &stream, const QScriptDebuggerValue &value)
Writes the given value to the specified stream.
QDataStream & operator>> (QDataStream &stream, QScriptDebuggerValue &value)
Reads a QScriptDebuggerValue from the specified stream into the given value.
Detailed Description
The QScriptDebuggerValue class represents a script value.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 67 of file qscriptdebuggervalue_p.h.
Enumerations
ValueType
enum QScriptDebuggerValue::ValueType
Enumerator
NoValue
UndefinedValue
NullValue
BooleanValue
StringValue
NumberValue
ObjectValue
Definition at line 70 of file qscriptdebuggervalue_p.h.
                    {
         NoValue,
         UndefinedValue,
         NullValue,
         BooleanValue,
         StringValue,
         NumberValue,
         ObjectValue
     };
Constructors and Destructors
QScriptDebuggerValue() [1/8]
QScriptDebuggerValue::QScriptDebuggerValue ()
Definition at line 91 of file qscriptdebuggervalue.cpp.
Referenced by operator>>().
     : d_ptr(0)
 {
 }
QScriptDebuggerValue() [2/8]
QScriptDebuggerValue::QScriptDebuggerValue (const QScriptValue & value)
Definition at line 96 of file qscriptdebuggervalue.cpp.
     : d_ptr(0)
 {
     if (value.isValid()) {
         d_ptr.reset(new QScriptDebuggerValuePrivate);
         if (value.isUndefined())
             d_ptr->type = UndefinedValue;
         else if (value.isNull())
             d_ptr->type = NullValue;
         else if (value.isNumber()) {
             d_ptr->type = NumberValue;
             d_ptr->numberValue = value.toNumber();
         } else if (value.isBoolean()) {
             d_ptr->type = BooleanValue;
             d_ptr->booleanValue = value.toBoolean();
         } else if (value.isString()) {
             d_ptr->type = StringValue;
             d_ptr->stringValue = new QString(value.toString());
         } else {
             Q_ASSERT(value.isObject());
             d_ptr->type = ObjectValue;
             d_ptr->objectId = value.objectId();
         }
         d_ptr->ref.ref();
     }
 }
QScriptDebuggerValue() [3/8]
QScriptDebuggerValue::QScriptDebuggerValue (double value)
Definition at line 123 of file qscriptdebuggervalue.cpp.
     : d_ptr(new QScriptDebuggerValuePrivate)
 {
     d_ptr->type = NumberValue;
     d_ptr->numberValue = value;
     d_ptr->ref.ref();
 }
QScriptDebuggerValue() [4/8]
QScriptDebuggerValue::QScriptDebuggerValue (bool value)
Definition at line 131 of file qscriptdebuggervalue.cpp.
     : d_ptr(new QScriptDebuggerValuePrivate)
 {
     d_ptr->type = BooleanValue;
     d_ptr->booleanValue = value;
     d_ptr->ref.ref();
 }
QScriptDebuggerValue() [5/8]
QScriptDebuggerValue::QScriptDebuggerValue (const QString & value)
Definition at line 139 of file qscriptdebuggervalue.cpp.
     : d_ptr(new QScriptDebuggerValuePrivate)
 {
     d_ptr->type = StringValue;
     d_ptr->stringValue = new QString(value);
     d_ptr->ref.ref();
 }
QScriptDebuggerValue() [6/8]
QScriptDebuggerValue::QScriptDebuggerValue (qint64 objectId)
Definition at line 147 of file qscriptdebuggervalue.cpp.
     : d_ptr(new QScriptDebuggerValuePrivate)
 {
     d_ptr->type = ObjectValue;
     d_ptr->objectId = objectId;
     d_ptr->ref.ref();
 }
QScriptDebuggerValue() [7/8]
QScriptDebuggerValue::QScriptDebuggerValue (ValueType type)
Definition at line 155 of file qscriptdebuggervalue.cpp.
     : d_ptr(new QScriptDebuggerValuePrivate)
 {
     d_ptr->type = type;
     d_ptr->ref.ref();
 }
QScriptDebuggerValue() [8/8]
QScriptDebuggerValue::QScriptDebuggerValue (const QScriptDebuggerValue & other)
Definition at line 162 of file qscriptdebuggervalue.cpp.
     : d_ptr(other.d_ptr.data())
 {
     if (d_ptr)
         d_ptr->ref.ref();
 }
~QScriptDebuggerValue()
QScriptDebuggerValue::~QScriptDebuggerValue ()
Definition at line 169 of file qscriptdebuggervalue.cpp.
 {
 }
Functions
booleanValue()
bool QScriptDebuggerValue::booleanValue () const
Returns this value as a boolean.
Definition at line 205 of file qscriptdebuggervalue.cpp.
Referenced by operator<<().
 {
     Q_D(const QScriptDebuggerValue);
     if (!d)
         return false;
     Q_ASSERT(d->type == BooleanValue);
     return d->booleanValue;
 }
numberValue()
double QScriptDebuggerValue::numberValue () const
Returns this value as a number.
Definition at line 193 of file qscriptdebuggervalue.cpp.
Referenced by operator<<().
 {
     Q_D(const QScriptDebuggerValue);
     if (!d)
         return 0;
     Q_ASSERT(d->type == NumberValue);
     return d->numberValue;
 }
objectId()
qint64 QScriptDebuggerValue::objectId () const
Returns this value as an object ID.
Definition at line 229 of file qscriptdebuggervalue.cpp.
Referenced by operator<<(), and QScriptDebuggerValue().
 {
     Q_D(const QScriptDebuggerValue);
     if (!d)
         return -1;
     Q_ASSERT(d->type == ObjectValue);
     return d->objectId;
 }
operator!=()
bool QScriptDebuggerValue::operator!= (const QScriptDebuggerValue & other) const
Returns true if this QScriptDebuggerValue is not equal to the other value, otherwise returns false.
Definition at line 331 of file qscriptdebuggervalue.cpp.
 {
     return !(*this == other);
 }
operator=()
QScriptDebuggerValue & QScriptDebuggerValue::operator= (const QScriptDebuggerValue & other)
Definition at line 173 of file qscriptdebuggervalue.cpp.
 {
     d_ptr.assign(other.d_ptr.data());
     return *this;
 }
operator==()
bool QScriptDebuggerValue::operator== (const QScriptDebuggerValue & other) const
Returns true if this QScriptDebuggerValue is equal to the other value, otherwise returns false.
Definition at line 300 of file qscriptdebuggervalue.cpp.
 {
     Q_D(const QScriptDebuggerValue);
     const QScriptDebuggerValuePrivate *od = other.d_func();
     if (d == od)
         return true;
     if (!d || !od)
         return false;
     if (d->type != od->type)
         return false;
     switch (d->type) {
     case NoValue:
     case UndefinedValue:
     case NullValue:
         return true;
     case BooleanValue:
         return d->booleanValue == od->booleanValue;
     case StringValue:
         return *d->stringValue == *od->stringValue;
     case NumberValue:
         return d->numberValue == od->numberValue;
     case ObjectValue:
         return d->objectId == od->objectId;
     }
     return false;
 }
stringValue()
QString QScriptDebuggerValue::stringValue () const
Returns this value as a string.
Definition at line 217 of file qscriptdebuggervalue.cpp.
Referenced by operator<<().
 {
     Q_D(const QScriptDebuggerValue);
     if (!d)
         return QString();
     Q_ASSERT(d->type == StringValue);
     return *d->stringValue;
 }
toScriptValue()
QScriptValue QScriptDebuggerValue::toScriptValue (QScriptEngine * engine) const
Converts this QScriptDebuggerValue to a QScriptValue in the given engine and returns the resulting value.
Definition at line 242 of file qscriptdebuggervalue.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute().
 {
     Q_D(const QScriptDebuggerValue);
     if (!d)
         return QScriptValue();
     switch (d->type) {
     case NoValue:
         return QScriptValue();
     case UndefinedValue:
         return engine->undefinedValue();
     case NullValue:
         return engine->nullValue();
     case BooleanValue:
         return QScriptValue(engine, d->booleanValue);
     case StringValue:
         return QScriptValue(engine, *d->stringValue);
     case NumberValue:
         return QScriptValue(engine, d->numberValue);
     case ObjectValue:
         return engine->objectById(d->objectId);
     }
     return QScriptValue();
 }
toString()
QString QScriptDebuggerValue::toString () const
Returns a string representation of this value.
Definition at line 269 of file qscriptdebuggervalue.cpp.
 {
     Q_D(const QScriptDebuggerValue);
     if (!d)
         return QString();
     switch (d->type) {
     case NoValue:
         return QString();
     case UndefinedValue:
         return QString::fromLatin1("undefined");
     case NullValue:
         return QString::fromLatin1("null");
     case BooleanValue:
         if (d->booleanValue)
             return QString::fromLatin1("true");
         else
             return QString::fromLatin1("false");
     case StringValue:
         return *d->stringValue;
     case NumberValue:
         return QString::number(d->numberValue); // ### qScriptNumberToString()
     case ObjectValue:
         return QString::fromLatin1("[object Object]");
     }
     return QString();
 }
type()
QScriptDebuggerValue::ValueType QScriptDebuggerValue::type () const
Returns the type of this value.
Definition at line 182 of file qscriptdebuggervalue.cpp.
Referenced by QScriptDebuggerLocalsModel::canFetchMore(), QScriptDebuggerLocalsModel::data(), QScriptDebuggerPrivate::debuggerEvent(), QScriptDebuggerLocalsModel::hasChildren(), operator<<(), operator>>(), QScriptDebuggerLocalsModelPrivate::populateIndex(), QScriptDebuggerValue(), and QScriptDebuggerLocalsModelPrivate::repopulate().
 {
     Q_D(const QScriptDebuggerValue);
     if (!d)
         return NoValue;
     return d->type;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & stream, const QScriptDebuggerValue & value) related
Writes the given value to the specified stream.
Definition at line 345 of file qscriptdebuggervalue.cpp.
 {
     out << (quint32)value.type();
     switch (value.type()) {
     case QScriptDebuggerValue::NoValue:
     case QScriptDebuggerValue::UndefinedValue:
     case QScriptDebuggerValue::NullValue:
         break;
     case QScriptDebuggerValue::BooleanValue:
         out << value.booleanValue();
         break;
     case QScriptDebuggerValue::StringValue:
         out << value.stringValue();
         break;
     case QScriptDebuggerValue::NumberValue:
         out << value.numberValue();
         break;
     case QScriptDebuggerValue::ObjectValue:
         out << value.objectId();
         break;
     }
     return out;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QScriptDebuggerValue & value) related
Reads a QScriptDebuggerValue from the specified stream into the given value.
Definition at line 379 of file qscriptdebuggervalue.cpp.
 {
     quint32 type;
     in >> type;
     switch (QScriptDebuggerValue::ValueType(type)) {
     case QScriptDebuggerValue::UndefinedValue:
     case QScriptDebuggerValue::NullValue:
         value = QScriptDebuggerValue(QScriptDebuggerValue::ValueType(type));
         break;
     case QScriptDebuggerValue::BooleanValue: {
         bool b;
         in >> b;
         value = QScriptDebuggerValue(b);
     }   break;
     case QScriptDebuggerValue::StringValue: {
         QString s;
         in >> s;
         value = QScriptDebuggerValue(s);
     }   break;
     case QScriptDebuggerValue::NumberValue: {
         double d;
         in >> d;
         value = QScriptDebuggerValue(d);
     }   break;
     case QScriptDebuggerValue::ObjectValue: {
         qint64 id;
         in >> id;
         value = QScriptDebuggerValue(id);
     }   break;
     case QScriptDebuggerValue::NoValue:
     default:
         value = QScriptDebuggerValue();
         break;
     }
     return in;
 }
Properties
d_ptr
QScopedSharedPointer<QScriptDebuggerValuePrivate> QScriptDebuggerValue::d_ptr private
Definition at line 106 of file qscriptdebuggervalue_p.h.
Referenced by operator=(), and QScriptDebuggerValue().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggervalue_p.h
/src/scripttools/debugging/qscriptdebuggervalue.cpp