Qt 4.8: QAxScriptManager Class Reference
QAxScriptManager Class Reference
The QAxScriptManager class provides a bridge between application objects and script code.
#include <qaxscript.h>
Signals
void error (QAxScript *script, int code, const QString &description, int sourcePosition, const QString &sourceText)
This signal is emitted when an execution error occurred while running script.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addObject (QAxBase *object)
Adds object to the manager.
void addObject (QObject *object)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Adds a generic COM wrapper for object to the manager.
QVariant call (const QString &function, const QVariant &v1=QVariant(), const QVariant &v2=QVariant(), const QVariant &v3=QVariant(), const QVariant &v4=QVariant(), const QVariant &v5=QVariant(), const QVariant &v6=QVariant(), const QVariant &v7=QVariant(), const QVariant &v8=QVariant())
Calls function, passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8 as arguments and returns the value returned by the function, or an invalid QVariant if the function does not return a value or when the function call failed.
QVariant call (const QString &function, QList< QVariant > &arguments)
Calls function passing arguments as parameters, and returns the result.
QStringList functions (QAxScript::FunctionFlags=QAxScript::FunctionNames) const
Returns a list with all the functions that are available.
QAxScript * load (const QString &code, const QString &name, const QString &language)
Loads the script source code using the script engine for language.
QAxScript * load (const QString &file, const QString &name)
Loads the source code from the file.
QAxScriptManager (QObject *parent=0)
Creates a QAxScriptManager object.
QAxScript * script (const QString &name) const
Returns the script called name.
QStringList scriptNames () const
Returns a list with the names of all the scripts.
~QAxScriptManager ()
Destroys the objects, releasing all allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool registerEngine (const QString &name, const QString &extension, const QString &code=QString())
Registers the script engine called name and returns true if the engine was found; otherwise does nothing and returns false.
static QString scriptFileFilter ()
Returns a file filter listing all the supported script languages.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Slots
void objectDestroyed (QObject *o)
void scriptError (int code, const QString &description, int sourcePosition, const QString &sourceText)
Private Functions
QAxScript * scriptForFunction (const QString &function) const
Returns a pointer to the first QAxScript that knows about function, or 0 if this function is unknown.
void updateScript (QAxScript *)
Properties
QAxScriptManagerPrivate * d
Friends
class QAxScript
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAxScriptManager class provides a bridge between application objects and script code.
Attention
Module: QAxContainer
The QAxScriptManager acts as a bridge between the COM objects embedded in the Qt application through QAxObject or QAxWidget, and the scripting languages available through the Windows Script technologies, usually JScript and VBScript.
Create one QAxScriptManager for each separate document in your application, and add the COM objects the scripts need to access using addObject(). Then load() the script sources and invoke the functions using call().
Warning
This class is not available with the bcc5.5 and MingW compilers.
See also
QAxScript, QAxScriptEngine, QAxBase, {ActiveQt Framework}
Definition at line 153 of file qaxscript.h.
Constructors and Destructors
QAxScriptManager()
QAxScriptManager::QAxScriptManager (QObject * parent = 0)
Creates a QAxScriptManager object.
parent is passed on to the QObject constructor.
It is usual to create one QAxScriptManager for each document in an application.
Definition at line 972 of file qaxscript.cpp.
 : QObject(parent)
 {
     d = new QAxScriptManagerPrivate;
 }
~QAxScriptManager()
QAxScriptManager::~QAxScriptManager ()
Destroys the objects, releasing all allocated resources.
Definition at line 981 of file qaxscript.cpp.
 {
     delete d;
 }
Functions
addObject() [1/2]
void QAxScriptManager::addObject (QAxBase * object)
Adds object to the manager.
Scripts handled by this manager can access the object in the code using the object's objectName property.
You must add all the necessary objects before loading any scripts.
Definition at line 1040 of file qaxscript.cpp.
 {
     QObject *obj = object->qObject();
     QString name = obj->objectName();
     if (d->objectDict.contains(name))
         return;
     d->objectDict.insert(name, object);
     connect(obj, SIGNAL(destroyed(QObject*)), this, SLOT(objectDestroyed(QObject*)));
 }
addObject() [2/2]
void QAxScriptManager::addObject (QObject * object) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Adds a generic COM wrapper for object to the manager.
object must be exposed as a COM object using the functionality provided by the QAxServer module. Applications using this function you must link against the qaxserver library.
Definition at line 233 of file qaxscript.h.
 {
     QAxBase *wrapper = qax_create_object_wrapper(object);
     if (!wrapper) {
         qWarning("QAxScriptMananger::addObject: Class %s not exposed through the QAxFactory",
             object->metaObject()->className());
         Q_ASSERT(wrapper);
     }
     addObject(wrapper);
 }
call() [1/2]
QVariant QAxScriptManager::call (const QString & function, const QVariant & var1 = QVariant(), const QVariant & var2 = QVariant(), const QVariant & var3 = QVariant(), const QVariant & var4 = QVariant(), const QVariant & var5 = QVariant(), const QVariant & var6 = QVariant(), const QVariant & var7 = QVariant(), const QVariant & var8 = QVariant())
Calls function, passing the parameters var1, var1, var2, var3, var4, var5, var6, var7 and var8 as arguments and returns the value returned by the function, or an invalid QVariant if the function does not return a value or when the function call failed.
The call returns when the script's execution has finished.
In most script engines the only supported parameter type is "const QVariant&", for example, to call a JavaScript function
function setNumber(number)
{
    n = number;
}
use
QValueList args;
args << 5;
script->call("setNumber(const QVariant&)", args);
As with dynamicCall the parameters can directly be embedded in the function string.
script->call("setNumber(5)");
However, this is slower.
Functions provided by script engines that don't support introspection are not available and must be called directly using QAxScript::call() on the respective script object.
Note that calling this function can be significantely slower than using call() on the respective QAxScript directly.
Definition at line 1177 of file qaxscript.cpp.
 {
     QAxScript *s = script(function);
     if (!s) {
 #ifdef QT_CHECK_STATE
         qWarning("QAxScriptManager::call: No script provides function %s, or this function\n"
             "\tis provided through an engine that does not support introspection", function.latin1());
 #endif
         return QVariant();
     }
     return s->call(function, var1, var2, var3, var4, var5, var6, var7, var8);
 }
call() [2/2]
QVariant QAxScriptManager::call (const QString & function, QList< QVariant > & arguments)
Calls function passing arguments as parameters, and returns the result.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns when the script's execution has finished.
Definition at line 1206 of file qaxscript.cpp.
 {
     QAxScript *s = script(function);
     if (!s) {
 #ifdef QT_CHECK_STATE
         qWarning("QAxScriptManager::call: No script provides function %s, or this function\n"
             "\tis provided through an engine that does not support introspection", function.latin1());
 #endif
         return QVariant();
     }
     QList<QVariant> args(arguments);
     return s->call(function, args);
 }
error
void QAxScriptManager::error (QAxScript * script, int code, const QString & description, int sourcePosition, const QString & sourceText) signal
This signal is emitted when an execution error occurred while running script.
code, description, sourcePosition and sourceText contain information about the execution error.
Warning
Do not delete script in a slot connected to this signal. Use deleteLater() instead.
Referenced by scriptError().
functions()
QStringList QAxScriptManager::functions (QAxScript::FunctionFlags flags = QAxScript::FunctionNames) const
Returns a list with all the functions that are available.
Functions provided by script engines that don't support introspection are not included in the list. The functions are either provided with full prototypes or only as names, depending on the value of flags.
Definition at line 993 of file qaxscript.cpp.
 {
     QStringList functions;
     QHash<QString, QAxScript*>::ConstIterator scriptIt;
     for (scriptIt = d->scriptDict.begin(); scriptIt != d->scriptDict.end(); ++scriptIt) {
         QAxScript *script = scriptIt.value();
         functions += script->functions(flags);
     }
     return functions;
 }
load() [1/2]
QAxScript * QAxScriptManager::load (const QString & code, const QString & name, const QString & language)
Loads the script source code using the script engine for language.
The script can later be referred to using its name which should not be empty.
The function returns a pointer to the script for the given code if the code was loaded successfully; otherwise it returns 0.
If language is empty it will be determined heuristically. If code contains the string "End Sub" it will be interpreted as VBScript, otherwise as JScript. Additional script engines can be registered using registerEngine().
You must add all the objects necessary (using addObject()) before loading any scripts. If code declares a function that is already available (no matter in which language) the first function is overloaded and can no longer be called via call(); but it will still be available by calling its script directly.
See also
addObject(), scriptNames(), functions()
Definition at line 1083 of file qaxscript.cpp.
 {
     QAxScript *script = new QAxScript(name, this);
     if (script->load(code, language))
         return script;
     delete script;
     return 0;
 }
load() [2/2]
QAxScript * QAxScriptManager::load (const QString & file, const QString & name)
Loads the source code from the file.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The script can later be referred to using its name which should not be empty.
The function returns a pointer to the script engine for the code in file if file was loaded successfully; otherwise it returns 0.
The script engine used is determined from the file's extension. By default ".js" files are interpreted as JScript files, and ".vbs" and ".dsm" files are interpreted as VBScript. Additional script engines can be registered using registerEngine().
Definition at line 1111 of file qaxscript.cpp.
 {
     QFile f(file);
     if (!f.open(QIODevice::ReadOnly))
         return 0;
     QByteArray data = f.readAll();
     QString contents = QString::fromLocal8Bit(data, data.size());
     f.close();
     if (contents.isEmpty())
         return 0;
     QString language;
     if (file.endsWith(QLatin1String(".js"))) {
         language = QLatin1String("JScript");
     } else {
         QList<QAxEngineDescriptor>::ConstIterator it;
         for (it = engines.begin(); it != engines.end(); ++it) {
             QAxEngineDescriptor engine = *it;
             if (engine.extension.isEmpty())
                 continue;
             if (file.endsWith(engine.extension)) {
                 language = engine.name;
                 break;
             }
         }
     }
     if (language.isEmpty())
         language = QLatin1String("VBScript");
     QAxScript *script = new QAxScript(name, this);
     if (script->load(contents, language))
         return script;
     delete script;
     return 0;
 }
objectDestroyed
void QAxScriptManager::objectDestroyed (QObject * o) private slot
Warning
This function is not part of the public interface.
Definition at line 1340 of file qaxscript.cpp.
Referenced by addObject().
 {
     d->objectDict.take(o->objectName());
 }
registerEngine()
bool QAxScriptManager::registerEngine (const QString & name, const QString & extension, const QString & code = QString()) static
Registers the script engine called name and returns true if the engine was found; otherwise does nothing and returns false.
The script engine will be used when loading files with the given extension, or when loading source code that contains the string code.
Definition at line 1229 of file qaxscript.cpp.
 {
     if (name.isEmpty())
         return false;
     CLSID clsid;
     HRESULT hres = CLSIDFromProgID((wchar_t*)name.utf16(), &clsid);
     if (hres != S_OK)
         return false;
     QAxEngineDescriptor engine;
     engine.name = name;
     engine.extension = extension;
     engine.code = code;
     engines.prepend(engine);
     return true;
 }
script()
QAxScript * QAxScriptManager::script (const QString & name) const
Returns the script called name.
You can use the returned pointer to call functions directly through QAxScript::call(), to access the script engine directly, or to delete and thus unload the script.
Definition at line 1028 of file qaxscript.cpp.
Referenced by call(), functions(), load(), and scriptForFunction().
 {
     return d->scriptDict.value(name);
 }
scriptError
void QAxScriptManager::scriptError (int code, const QString & desc, int spos, const QString & stext) private slot
Warning
This function is not part of the public interface.
Definition at line 1348 of file qaxscript.cpp.
 {
     QAxScript *source = qobject_cast<QAxScript*>(sender());
     emit error(source, code, desc, spos, stext);
 }
scriptFileFilter()
QString QAxScriptManager::scriptFileFilter () static
Returns a file filter listing all the supported script languages.
This filter string is convenient for use with QFileDialog.
Definition at line 1252 of file qaxscript.cpp.
 {
     QString allFiles = QLatin1String("Script Files (*.js *.vbs *.dsm");
     QString specialFiles = QLatin1String(";;VBScript Files (*.vbs *.dsm)"
         ";;JavaScript Files (*.js)");
     QList<QAxEngineDescriptor>::ConstIterator it;
     for (it = engines.begin(); it != engines.end(); ++it) {
         QAxEngineDescriptor engine = *it;
         if (engine.extension.isEmpty())
             continue;
         allFiles += QLatin1String(" *") + engine.extension;
         specialFiles += QLatin1String(";;") + engine.name + QLatin1String(" Files (*") + engine.extension + QLatin1Char(')');
     }
     allFiles += QLatin1Char(')');
     return allFiles + specialFiles + QLatin1String(";;All Files (*.*)");
 }
scriptForFunction()
QAxScript * QAxScriptManager::scriptForFunction (const QString & function) const private
Returns a pointer to the first QAxScript that knows about function, or 0 if this function is unknown.
Warning
This function is not part of the public interface.
Definition at line 1295 of file qaxscript.cpp.
 {
     // check full prototypes if included
     if (function.contains(QLatin1Char('('))) {
         QHash<QString, QAxScript*>::ConstIterator scriptIt;
         for (scriptIt = d->scriptDict.begin(); scriptIt != d->scriptDict.end(); ++scriptIt) {
             QAxScript *script = scriptIt.value();
             if (script->functions(QAxScript::FunctionSignatures).contains(function))
                 return script;
         }
     }
     QString funcName = function;
     funcName = funcName.left(funcName.indexOf(QLatin1Char('(')));
     // second try, checking only names, not prototypes
     QHash<QString, QAxScript*>::ConstIterator scriptIt;
     for (scriptIt = d->scriptDict.begin(); scriptIt != d->scriptDict.end(); ++scriptIt) {
         QAxScript *script = scriptIt.value();
         if (script->functions(QAxScript::FunctionNames).contains(funcName))
             return script;
     }
     return 0;
 }
scriptNames()
QStringList QAxScriptManager::scriptNames () const
Returns a list with the names of all the scripts.
Definition at line 1009 of file qaxscript.cpp.
 {
     QStringList scripts;
     QHash<QString, QAxScript*>::ConstIterator scriptIt;
     for (scriptIt = d->scriptDict.begin(); scriptIt != d->scriptDict.end(); ++scriptIt) {
         scripts << scriptIt.key();
     }
     return scripts;
 }
updateScript()
void QAxScriptManager::updateScript (QAxScript * script) private
Warning
This function is not part of the public interface.
Definition at line 1325 of file qaxscript.cpp.
Referenced by QAxScript::updateObjects().
 {
     QHash<QString, QAxBase*>::ConstIterator objectIt;
     for (objectIt = d->objectDict.constBegin(); objectIt != d->objectDict.constEnd(); ++objectIt) {
         QString name = objectIt.key();
         QAxScriptEngine *engine = script->scriptEngine();
         if (engine)
             engine->addItem(name);
     }
 }
Friends and Related Functions
QAxScript
friend class QAxScript friend
Definition at line 192 of file qaxscript.h.
Referenced by load().
Properties
d
QAxScriptManagerPrivate* QAxScriptManager::d private
Definition at line 193 of file qaxscript.h.
Referenced by addObject(), QAxScript::findObject(), functions(), objectDestroyed(), QAxScript::QAxScript(), QAxScriptManager(), script(), scriptForFunction(), scriptNames(), updateScript(), and ~QAxScriptManager().
The documentation for this class was generated from the following files:
/src/activeqt/container/qaxscript.h
/src/activeqt/container/qaxscript.cpp