Qt 4.8: QOCICols Class Reference
QOCICols Class Reference
Classes
class OraFieldInf
Public Functions
int fieldFromDefine (OCIDefine *d)
void getValues (QVector< QVariant > &v, int index)
QOCICols (int size, QOCIResultPrivate *dp)
int readLOBs (QVector< QVariant > &values, int index=0)
int readPiecewise (QVector< QVariant > &values, int index=0)
int size ()
~QOCICols ()
Static Public Functions
static bool execBatch (QOCIResultPrivate *d, QVector< QVariant > &boundValues, bool arrayBind)
Public Variables
QSqlRecord rec
Private Functions
char * create (int position, int size)
OCILobLocator ** createLobLocator (int position, OCIEnv *env)
OraFieldInfo qMakeOraField (const QOCIResultPrivate *p, OCIParam *param) const
Properties
const QOCIResultPrivate *const d
QVector< OraFieldInf > fieldInf
Detailed Description
Definition at line 789 of file qsql_oci.cpp.
Constructors and Destructors
QOCICols()
QOCICols::QOCICols (int size, QOCIResultPrivate * dp)
Definition at line 837 of file qsql_oci.cpp.
     : fieldInf(size), d(dp)
 {
     ub4 dataSize = 0;
     OCIDefine* dfn = 0;
     int r;
     OCIParam* param = 0;
     sb4 parmStatus = 0;
     ub4 count = 1;
     int idx = 0;
     parmStatus = OCIParamGet(d->sql,
                              OCI_HTYPE_STMT,
                              d->err,
                              reinterpret_cast<void **>(&param),
                              count);
     while (parmStatus == OCI_SUCCESS) {
         OraFieldInfo ofi = qMakeOraField(d, param);
         if (ofi.oraType == SQLT_RDD)
             dataSize = 50;
 #ifdef SQLT_INTERVAL_YM
 #ifdef SQLT_INTERVAL_DS
         else if (ofi.oraType == SQLT_INTERVAL_YM || ofi.oraType == SQLT_INTERVAL_DS)
             // since we are binding interval datatype as string,
             // we are not interested in the number of bytes but characters.
             dataSize = 50;  // magic number
 #endif //SQLT_INTERVAL_DS
 #endif //SQLT_INTERVAL_YM
         else if (ofi.oraType == SQLT_NUM || ofi.oraType == SQLT_VNU){
             if (ofi.oraPrecision > 0)
                 dataSize = (ofi.oraPrecision + 1) * sizeof(utext);
             else
                 dataSize = (38 + 1) * sizeof(utext);
         }
         else
             dataSize = ofi.oraLength;
         fieldInf[idx].typ = ofi.type;
         fieldInf[idx].oraType = ofi.oraType;
         rec.append(qFromOraInf(ofi));
         switch (ofi.type) {
         case QVariant::DateTime:
             r = OCIDefineByPos(d->sql,
                                &dfn,
                                d->err,
                                count,
                                create(idx, dataSize+1),
                                dataSize+1,
                                SQLT_DAT,
                                &(fieldInf[idx].ind),
                                0, 0, OCI_DEFAULT);
             break;
         case QVariant::Double:
             r = OCIDefineByPos(d->sql,
                                &dfn,
                                d->err,
                                count,
                                create(idx, sizeof(double) - 1),
                                sizeof(double),
                                SQLT_FLT,
                                &(fieldInf[idx].ind),
                                0, 0, OCI_DEFAULT);
             break;
         case QVariant::Int:
             r = OCIDefineByPos(d->sql,
                                &dfn,
                                d->err,
                                count,
                                create(idx, sizeof(qint32) - 1),
                                sizeof(qint32),
                                SQLT_INT,
                                &(fieldInf[idx].ind),
                                0, 0, OCI_DEFAULT);
             break;
         case QVariant::LongLong:
             r = OCIDefineByPos(d->sql,
                                &dfn,
                                d->err,
                                count,
                                create(idx, sizeof(OCINumber)),
                                sizeof(OCINumber),
                                SQLT_VNU,
                                &(fieldInf[idx].ind),
                                0, 0, OCI_DEFAULT);
             break;
         case QVariant::ByteArray:
             // RAW and LONG RAW fields can't be bound to LOB locators
             if (ofi.oraType == SQLT_BIN) {
 //                                qDebug("binding SQLT_BIN");
                 r = OCIDefineByPos(d->sql,
                                    &dfn,
                                    d->err,
                                    count,
                                    create(idx, dataSize),
                                    dataSize,
                                    SQLT_BIN,
                                    &(fieldInf[idx].ind),
                                    0, 0, OCI_DYNAMIC_FETCH);
             } else if (ofi.oraType == SQLT_LBI) {
 //                                    qDebug("binding SQLT_LBI");
                 r = OCIDefineByPos(d->sql,
                                    &dfn,
                                    d->err,
                                    count,
                                    0,
                                    SB4MAXVAL,
                                    SQLT_LBI,
                                    &(fieldInf[idx].ind),
                                    0, 0, OCI_DYNAMIC_FETCH);
             } else if (ofi.oraType == SQLT_CLOB) {
                 r = OCIDefineByPos(d->sql,
                                    &dfn,
                                    d->err,
                                    count,
                                    createLobLocator(idx, d->env),
                                    -1,
                                    SQLT_CLOB,
                                    &(fieldInf[idx].ind),
                                    0, 0, OCI_DEFAULT);
             } else {
 //                 qDebug("binding SQLT_BLOB");
                 r = OCIDefineByPos(d->sql,
                                    &dfn,
                                    d->err,
                                    count,
                                    createLobLocator(idx, d->env),
                                    -1,
                                    SQLT_BLOB,
                                    &(fieldInf[idx].ind),
                                    0, 0, OCI_DEFAULT);
             }
             break;
         case QVariant::String:
             if (ofi.oraType == SQLT_LNG) {
                 r = OCIDefineByPos(d->sql,
                         &dfn,
                         d->err,
                         count,
                         0,
                         SB4MAXVAL,
                         SQLT_LNG,
                         &(fieldInf[idx].ind),
                         0, 0, OCI_DYNAMIC_FETCH);
             } else {
                 dataSize += dataSize + sizeof(QChar);
                 //qDebug("OCIDefineByPosStr(%d): %d", count, dataSize);
                 r = OCIDefineByPos(d->sql,
                         &dfn,
                         d->err,
                         count,
                         create(idx, dataSize),
                         dataSize,
                         SQLT_STR,
                         &(fieldInf[idx].ind),
                         0, 0, OCI_DEFAULT);
                 if (r == 0)
                     d->setCharset(dfn, OCI_HTYPE_DEFINE);
             }
            break;
         default:
             // this should make enough space even with character encoding
             dataSize = (dataSize + 1) * sizeof(utext) ;
             //qDebug("OCIDefineByPosDef(%d): %d", count, dataSize);
             r = OCIDefineByPos(d->sql,
                                 &dfn,
                                 d->err,
                                 count,
                                 create(idx, dataSize),
                                 dataSize+1,
                                 SQLT_STR,
                                 &(fieldInf[idx].ind),
                                 0, 0, OCI_DEFAULT);
             break;
         }
         if (r != 0)
             qOraWarning("QOCICols::bind:", d->err);
         fieldInf[idx].def = dfn;
         ++count;
         ++idx;
         parmStatus = OCIParamGet(d->sql,
                                   OCI_HTYPE_STMT,
                                   d->err,
                                   reinterpret_cast<void **>(&param),
                                   count);
     }
 }
~QOCICols()
QOCICols::~QOCICols ()
Definition at line 1026 of file qsql_oci.cpp.
 {
 }
Functions
create()
char * QOCICols::create (int position, int size) private
Definition at line 1030 of file qsql_oci.cpp.
Referenced by QOCICols().
 {
     char* c = new char[size+1];
     // Oracle may not fill fixed width fields
     memset(c, 0, size+1);
     fieldInf[position].data = c;
     fieldInf[position].len = size;
     return c;
 }
createLobLocator()
OCILobLocator ** QOCICols::createLobLocator (int position, OCIEnv * env) private
Definition at line 1040 of file qsql_oci.cpp.
Referenced by QOCICols().
 {
     OCILobLocator *& lob = fieldInf[position].lob;
     int r = OCIDescriptorAlloc(env,
                                reinterpret_cast<void **>(&lob),
                                OCI_DTYPE_LOB,
                                0,
                                0);
     if (r != 0) {
         qWarning("QOCICols: Cannot create LOB locator");
         lob = 0;
     }
     return &lob;
 }
execBatch()
bool QOCICols::execBatch (QOCIResultPrivate * d, QVector< QVariant > & boundValues, bool arrayBind) static
Definition at line 1283 of file qsql_oci.cpp.
Referenced by QOCIResult::virtual_hook().
 {
     int columnCount = boundValues.count();
     if (boundValues.isEmpty() || columnCount == 0)
         return false;
 #ifdef QOCI_DEBUG
     qDebug() << "columnCount:" << columnCount << boundValues;
 #endif
     int i;
     sword r;
     QVarLengthArray<QVariant::Type> fieldTypes;
     for (i = 0; i < columnCount; ++i) {
         QVariant::Type tp = boundValues.at(i).type();
         fieldTypes.append(tp == QVariant::List ? boundValues.at(i).toList().value(0).type()
                                                : tp);
     }
     QList<QByteArray> tmpStorage;
     SizeArray tmpSizes(columnCount);
     QVector<QOCIBatchColumn> columns(columnCount);
     QOCIBatchCleanupHandler cleaner(columns);
     // figuring out buffer sizes
     for (i = 0; i < columnCount; ++i) {
         if (boundValues.at(i).type() != QVariant::List) {
             // not a list - create a deep-copy of the single value
             QOCIBatchColumn &singleCol = columns[i];
             singleCol.indicators = new sb2[1];
             *singleCol.indicators = boundValues.at(i).isNull() ? -1 : 0;
             r = d->bindValue(d->sql, &singleCol.bindh, d->err, i,
                              boundValues.at(i), singleCol.indicators, &tmpSizes[i], tmpStorage);
             if (r != OCI_SUCCESS && r != OCI_SUCCESS_WITH_INFO) {
                 qOraWarning("QOCIPrivate::execBatch: unable to bind column:", d->err);
                 d->q->setLastError(qMakeError(QCoreApplication::translate("QOCIResult",
                          "Unable to bind column for batch execute"),
                          QSqlError::StatementError, d->err));
                 return false;
             }
             continue;
         }
         QOCIBatchColumn &col = columns[i];
         col.recordCount = boundValues.at(i).toList().count();
         col.lengths = new ub2[col.recordCount];
         col.indicators = new sb2[col.recordCount];
         col.maxarr_len = col.recordCount;
         col.curelep = col.recordCount;
         switch (fieldTypes[i]) {
             case QVariant::Time:
             case QVariant::Date:
             case QVariant::DateTime:
                 col.bindAs = SQLT_DAT;
                 col.maxLen = 7;
                 break;
             case QVariant::Int:
                 col.bindAs = SQLT_INT;
                 col.maxLen = sizeof(int);
                 break;
             case QVariant::UInt:
                 col.bindAs = SQLT_UIN;
                 col.maxLen = sizeof(uint);
                 break;
             case QVariant::LongLong:
                 col.bindAs = SQLT_VNU;
                 col.maxLen = sizeof(OCINumber);
                 break;
             case QVariant::ULongLong:
                 col.bindAs = SQLT_VNU;
                 col.maxLen = sizeof(OCINumber);
                 break;
             case QVariant::Double:
                 col.bindAs = SQLT_FLT;
                 col.maxLen = sizeof(double);
                 break;
             case QVariant::UserType:
                 col.bindAs = SQLT_RDD;
                 col.maxLen = sizeof(OCIRowid*);
                 break;
             case QVariant::String: {
                 col.bindAs = SQLT_STR;
                 for (uint j = 0; j < col.recordCount; ++j) {
                     uint len;
                     if(d->isOutValue(i))
                         len = boundValues.at(i).toList().at(j).toString().capacity() + 1;
                     else
                         len = boundValues.at(i).toList().at(j).toString().length() + 1;
                     if (len > col.maxLen)
                         col.maxLen = len;
                 }
                 col.maxLen *= sizeof(QChar);
                 break; }
             case QVariant::ByteArray:
             default: {
                 col.bindAs = SQLT_LBI;
                 for (uint j = 0; j < col.recordCount; ++j) {
                     if(d->isOutValue(i))
                         col.lengths[j] = boundValues.at(i).toList().at(j).toByteArray().capacity();
                     else
                         col.lengths[j] = boundValues.at(i).toList().at(j).toByteArray().size();
                     if (col.lengths[j] > col.maxLen)
                         col.maxLen = col.lengths[j];
                 }
                 break; }
         }
         col.data = new char[col.maxLen * col.recordCount];
         memset(col.data, 0, col.maxLen * col.recordCount);
         // we may now populate column with data
         for (uint row = 0; row < col.recordCount; ++row) {
             const QVariant &val = boundValues.at(i).toList().at(row);
             if (val.isNull()){
                 columns[i].indicators[row] = -1;
                 columns[i].lengths[row] = 0;
             } else {
                 columns[i].indicators[row] = 0;
                 char *dataPtr = columns[i].data + (columns[i].maxLen * row);
                 switch (fieldTypes[i]) {
                     case QVariant::Time:
                     case QVariant::Date:
                     case QVariant::DateTime:{
                         columns[i].lengths[row] = columns[i].maxLen;
                         const QByteArray ba = qMakeOraDate(val.toDateTime());
                         Q_ASSERT(ba.size() == int(columns[i].maxLen));
                         memcpy(dataPtr, ba.constData(), columns[i].maxLen);
                         break;
                     }
                     case QVariant::Int:
                         columns[i].lengths[row] = columns[i].maxLen;
                         *reinterpret_cast<int*>(dataPtr) = val.toInt();
                         break;
                     case QVariant::UInt:
                         columns[i].lengths[row] = columns[i].maxLen;
                         *reinterpret_cast<uint*>(dataPtr) = val.toUInt();
                         break;
                     case QVariant::LongLong:
                     {
                         columns[i].lengths[row] = columns[i].maxLen;
                         const QByteArray ba = qMakeOCINumber(val.toLongLong(), d->err);
                         Q_ASSERT(ba.size() == int(columns[i].maxLen));
                         memcpy(dataPtr, ba.constData(), columns[i].maxLen);
                         break;
                     }
                     case QVariant::ULongLong:
                     {
                         columns[i].lengths[row] = columns[i].maxLen;
                         const QByteArray ba = qMakeOCINumber(val.toULongLong(), d->err);
                         Q_ASSERT(ba.size() == int(columns[i].maxLen));
                         memcpy(dataPtr, ba.constData(), columns[i].maxLen);
                         break;
                     }
                     case QVariant::Double:
                          columns[i].lengths[row] = columns[i].maxLen;
                          *reinterpret_cast<double*>(dataPtr) = val.toDouble();
                          break;
                     case QVariant::String: {
                         const QString s = val.toString();
                         columns[i].lengths[row] = (s.length() + 1) * sizeof(QChar);
                         memcpy(dataPtr, s.utf16(), columns[i].lengths[row]);
                         break;
                     }
                     case QVariant::UserType:
                         if (val.canConvert<QOCIRowIdPointer>()) {
                             const QOCIRowIdPointer rptr = qvariant_cast<QOCIRowIdPointer>(val);
                             *reinterpret_cast<OCIRowid**>(dataPtr) = rptr->id;
                             columns[i].lengths[row] = 0;
                             break;
                         }
                     case QVariant::ByteArray:
                     default: {
                         const QByteArray ba = val.toByteArray();
                         columns[i].lengths[row] = ba.size();
                         memcpy(dataPtr, ba.constData(), ba.size());
                         break;
                     }
                 }
             }
         }
         QOCIBatchColumn &bindColumn = columns[i];
 #ifdef QOCI_DEBUG
             qDebug("OCIBindByPos(%p, %p, %p, %d, %p, %d, %d, %p, %p, 0, %d, %p, OCI_DEFAULT)",
             d->sql, &bindColumn.bindh, d->err, i + 1, bindColumn.data,
             bindColumn.maxLen, bindColumn.bindAs, bindColumn.indicators, bindColumn.lengths,
             arrayBind ? bindColumn.maxarr_len : 0, arrayBind ? &bindColumn.curelep : 0);
         for (int ii = 0; ii < (int)bindColumn.recordCount; ++ii) {
             qDebug(" record %d: indicator %d, length %d", ii, bindColumn.indicators[ii],
                     bindColumn.lengths[ii]);
         }
 #endif
         // binding the column
         r = OCIBindByPos(
                 d->sql, &bindColumn.bindh, d->err, i + 1,
                 bindColumn.data,
                 bindColumn.maxLen,
                 bindColumn.bindAs,
                 bindColumn.indicators,
                 bindColumn.lengths,
                 0,
                 arrayBind ? bindColumn.maxarr_len : 0,
                 arrayBind ? &bindColumn.curelep : 0,
                 OCI_DEFAULT);
 #ifdef QOCI_DEBUG
         qDebug("After OCIBindByPos: r = %d, bindh = %p", r, bindColumn.bindh);
 #endif
         if (r != OCI_SUCCESS && r != OCI_SUCCESS_WITH_INFO) {
             qOraWarning("QOCIPrivate::execBatch: unable to bind column:", d->err);
             d->q->setLastError(qMakeError(QCoreApplication::translate("QOCIResult",
                      "Unable to bind column for batch execute"),
                      QSqlError::StatementError, d->err));
             return false;
         }
         r = OCIBindArrayOfStruct (
                 columns[i].bindh, d->err,
                 columns[i].maxLen,
                 sizeof(columns[i].indicators[0]),
                 sizeof(columns[i].lengths[0]),
                 0);
         if (r != OCI_SUCCESS && r != OCI_SUCCESS_WITH_INFO) {
             qOraWarning("QOCIPrivate::execBatch: unable to bind column:", d->err);
             d->q->setLastError(qMakeError(QCoreApplication::translate("QOCIResult",
                      "Unable to bind column for batch execute"),
                      QSqlError::StatementError, d->err));
             return false;
         }
     }
     //finaly we can execute
     r = OCIStmtExecute(d->svc, d->sql, d->err,
                        arrayBind ? 1 : columns[0].recordCount,
                        0, NULL, NULL,
                        d->transaction ? OCI_DEFAULT : OCI_COMMIT_ON_SUCCESS);
     if (r != OCI_SUCCESS && r != OCI_SUCCESS_WITH_INFO) {
         qOraWarning("QOCIPrivate::execBatch: unable to execute batch statement:", d->err);
         d->q->setLastError(qMakeError(QCoreApplication::translate("QOCIResult",
                         "Unable to execute batch statement"),
                         QSqlError::StatementError, d->err));
         return false;
     }
     // for out parameters we copy data back to value vector
     for (i = 0; i < columnCount; ++i) {
         if (!d->isOutValue(i))
             continue;
         QVariant::Type tp = boundValues.at(i).type();
         if (tp != QVariant::List) {
             qOraOutValue(boundValues[i], tmpStorage, d->err);
             if (*columns[i].indicators == -1)
                 boundValues[i] = QVariant(tp);
             continue;
         }
         QVariantList *list = static_cast<QVariantList *>(const_cast<void*>(boundValues.at(i).data()));
         char* data = columns[i].data;
         for (uint r = 0; r < columns[i].recordCount; ++r){
             if (columns[i].indicators[r] == -1) {
                 (*list)[r] = QVariant();
                 continue;
             }
             switch(columns[i].bindAs) {
                 case SQLT_DAT:
                     (*list)[r] =  qMakeDate(data + r * columns[i].maxLen);
                     break;
                 case SQLT_INT:
                     (*list)[r] =  *reinterpret_cast<int*>(data + r * columns[i].maxLen);
                     break;
                 case SQLT_UIN:
                     (*list)[r] =  *reinterpret_cast<uint*>(data + r * columns[i].maxLen);
                     break;
                 case SQLT_VNU:
                 {
                     switch (boundValues.at(i).type()) {
                     case QVariant::LongLong:
                         (*list)[r] =  qMakeLongLong(data + r * columns[i].maxLen, d->err);
                         break;
                     case QVariant::ULongLong:
                         (*list)[r] =  qMakeULongLong(data + r * columns[i].maxLen, d->err);
                         break;
                     default:
                         break;
                     }
                     break;
                 }
                 case SQLT_FLT:
                     (*list)[r] =  *reinterpret_cast<double*>(data + r * columns[i].maxLen);
                     break;
                 case SQLT_STR:
                     (*list)[r] =  QString(reinterpret_cast<const QChar *>(data
                                                                 + r * columns[i].maxLen));
                     break;
                 default:
                     (*list)[r] =  QByteArray(data + r * columns[i].maxLen, columns[i].maxLen);
                 break;
             }
         }
     }
     d->q->setSelect(false);
     d->q->setAt(QSql::BeforeFirstRow);
     d->q->setActive(true);
     return true;
 }
fieldFromDefine()
int QOCICols::fieldFromDefine (OCIDefine * d)
Definition at line 1709 of file qsql_oci.cpp.
Referenced by readPiecewise().
 {
     for (int i = 0; i < fieldInf.count(); ++i) {
         if (fieldInf.at(i).def == d)
             return i;
     }
     return -1;
 }
getValues()
void QOCICols::getValues (QVector< QVariant > & v, int index)
Definition at line 1718 of file qsql_oci.cpp.
Referenced by QOCIResult::gotoNext().
 {
     for (int i = 0; i < fieldInf.size(); ++i) {
         const OraFieldInf &fld = fieldInf.at(i);
         if (fld.ind == -1) {
             // got a NULL value
             v[index + i] = QVariant(fld.typ);
             continue;
         }
         if (fld.oraType == SQLT_BIN || fld.oraType == SQLT_LBI || fld.oraType == SQLT_LNG)
             continue; // already fetched piecewise
         switch (fld.typ) {
         case QVariant::DateTime:
             v[index + i] = QVariant(qMakeDate(fld.data));
             break;
         case QVariant::Double:
         case QVariant::Int:
         case QVariant::LongLong:
             if (d->q->numericalPrecisionPolicy() != QSql::HighPrecision) {
                 if ((d->q->numericalPrecisionPolicy() == QSql::LowPrecisionDouble)
                         && (fld.typ == QVariant::Double)) {
                     v[index + i] = *reinterpret_cast<double *>(fld.data);
                     break;
                 } else if ((d->q->numericalPrecisionPolicy() == QSql::LowPrecisionInt64)
                         && (fld.typ == QVariant::LongLong)) {
                     qint64 qll = 0;
                     int r = OCINumberToInt(d->err, reinterpret_cast<OCINumber *>(fld.data), sizeof(qint64),
                                    OCI_NUMBER_SIGNED, &qll);
                     if(r == OCI_SUCCESS)
                         v[index + i] = qll;
                     else
                         v[index + i] = QVariant();
                     break;
                 } else if ((d->q->numericalPrecisionPolicy() == QSql::LowPrecisionInt32)
                         && (fld.typ == QVariant::Int)) {
                     v[index + i] = *reinterpret_cast<int *>(fld.data);
                     break;
                 }
             }
             // else fall through
         case QVariant::String:
             v[index + i] = QString(reinterpret_cast<const QChar *>(fld.data));
             break;
         case QVariant::ByteArray:
             if (fld.len > 0)
                 v[index + i] = QByteArray(fld.data, fld.len);
             else
                 v[index + i] = QVariant(QVariant::ByteArray);
             break;
         default:
             qWarning("QOCICols::value: unknown data type");
             break;
         }
     }
 }
qMakeOraField()
OraFieldInfo QOCICols::qMakeOraField (const QOCIResultPrivate * p, OCIParam * param) const private
Definition at line 1119 of file qsql_oci.cpp.
Referenced by QOCICols().
 {
     OraFieldInfo ofi;
     ub2 colType(0);
     text *colName = 0;
     ub4 colNameLen(0);
     sb1 colScale(0);
     ub2 colLength(0);
     ub2 colFieldLength(0);
     sb2 colPrecision(0);
     ub1 colIsNull(0);
     int r(0);
     QVariant::Type type(QVariant::Invalid);
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colType,
                    0,
                    OCI_ATTR_DATA_TYPE,
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colName,
                    &colNameLen,
                    OCI_ATTR_NAME,
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colLength,
                    0,
                    OCI_ATTR_DATA_SIZE, /* in bytes */
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
 #ifdef OCI_ATTR_CHAR_SIZE
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colFieldLength,
                    0,
                    OCI_ATTR_CHAR_SIZE,
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
 #else
     // for Oracle8.
     colFieldLength = colLength;
 #endif
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colPrecision,
                    0,
                    OCI_ATTR_PRECISION,
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colScale,
                    0,
                    OCI_ATTR_SCALE,
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colType,
                    0,
                    OCI_ATTR_DATA_TYPE,
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
     r = OCIAttrGet(param,
                    OCI_DTYPE_PARAM,
                    &colIsNull,
                    0,
                    OCI_ATTR_IS_NULL,
                    p->err);
     if (r != 0)
         qOraWarning("qMakeOraField:", p->err);
     type = qDecodeOCIType(colType, p->q->numericalPrecisionPolicy());
     if (type == QVariant::Int) {
         if (colLength == 22 && colPrecision == 0 && colScale == 0)
             type = QVariant::String;
         if (colScale > 0)
             type = QVariant::String;
     }
     // bind as double if the precision policy asks for it
     if (((colType == SQLT_FLT) || (colType == SQLT_NUM))
             && (p->q->numericalPrecisionPolicy() == QSql::LowPrecisionDouble)) {
         type = QVariant::Double;
     }
     // bind as int32 or int64 if the precision policy asks for it
     if ((colType == SQLT_NUM) || (colType == SQLT_VNU) || (colType == SQLT_UIN)
             || (colType == SQLT_INT)) {
         if (p->q->numericalPrecisionPolicy() == QSql::LowPrecisionInt64)
             type = QVariant::LongLong;
         else if (p->q->numericalPrecisionPolicy() == QSql::LowPrecisionInt32)
             type = QVariant::Int;
     }
     if (colType == SQLT_BLOB)
         colLength = 0;
     // colNameLen is length in bytes
     ofi.name = QString(reinterpret_cast<const QChar*>(colName), colNameLen / 2);
     ofi.type = type;
     ofi.oraType = colType;
     ofi.oraFieldLength = colFieldLength;
     ofi.oraLength = colLength;
     ofi.oraScale = colScale;
     ofi.oraPrecision = colPrecision;
     ofi.oraIsNull = colIsNull;
     return ofi;
 }
readLOBs()
int QOCICols::readLOBs (QVector< QVariant > & values, int index = 0)
Definition at line 1679 of file qsql_oci.cpp.
Referenced by QOCIResult::gotoNext().
 {
     OCILobLocator *lob;
     int r = OCI_SUCCESS;
     for (int i = 0; i < size(); ++i) {
         const OraFieldInf &fi = fieldInf.at(i);
         if (fi.ind == -1 || !(lob = fi.lob))
             continue;
         bool isClob = fi.oraType == SQLT_CLOB;
         QVariant var;
         if (isClob) {
             QString str;
             r = qReadLob<QString, sizeof(QChar)>(str, d, lob);
             var = str;
         } else {
             QByteArray buf;
             r = qReadLob<QByteArray, sizeof(char)>(buf, d, lob);
             var = buf;
         }
         if (r == OCI_SUCCESS)
             values[index + i] = var;
         else
             break;
     }
     return r;
 }
readPiecewise()
int QOCICols::readPiecewise (QVector< QVariant > & values, int index = 0)
Definition at line 1055 of file qsql_oci.cpp.
Referenced by QOCIResult::gotoNext().
 {
     OCIDefine*     dfn;
     ub4            typep;
     ub1            in_outp;
     ub4            iterp;
     ub4            idxp;
     ub1            piecep;
     sword          status;
     text           col [QOCI_DYNAMIC_CHUNK_SIZE+1];
     int            fieldNum = -1;
     int            r = 0;
     bool           nullField;
     do {
         r = OCIStmtGetPieceInfo(d->sql, d->err, reinterpret_cast<void **>(&dfn), &typep,
                                  &in_outp, &iterp, &idxp, &piecep);
         if (r != OCI_SUCCESS)
             qOraWarning("OCIResultPrivate::readPiecewise: unable to get piece info:", d->err);
         fieldNum = fieldFromDefine(dfn);
         bool isStringField = fieldInf.at(fieldNum).oraType == SQLT_LNG;
         ub4 chunkSize = QOCI_DYNAMIC_CHUNK_SIZE;
         nullField = false;
         r  = OCIStmtSetPieceInfo(dfn, OCI_HTYPE_DEFINE,
                                  d->err, col,
                                  &chunkSize, piecep, NULL, NULL);
         if (r != OCI_SUCCESS)
             qOraWarning("OCIResultPrivate::readPiecewise: unable to set piece info:", d->err);
         status = OCIStmtFetch (d->sql, d->err, 1, OCI_FETCH_NEXT, OCI_DEFAULT);
         if (status == -1) {
             sb4 errcode;
             OCIErrorGet(d->err, 1, 0, &errcode, 0, 0,OCI_HTYPE_ERROR);
             switch (errcode) {
             case 1405: /* NULL */
                 nullField = true;
                 break;
             default:
                 qOraWarning("OCIResultPrivate::readPiecewise: unable to fetch next:", d->err);
                 break;
             }
         }
         if (status == OCI_NO_DATA)
             break;
         if (nullField || !chunkSize) {
             fieldInf[fieldNum].ind = -1;
         } else {
             if (isStringField) {
                 QString str = values.at(fieldNum + index).toString();
                 str += QString(reinterpret_cast<const QChar *>(col), chunkSize / 2);
                 values[fieldNum + index] = str;
                 fieldInf[fieldNum].ind = 0;
             } else {
                 QByteArray ba = values.at(fieldNum + index).toByteArray();
                 int sz = ba.size();
                 ba.resize(sz + chunkSize);
                 memcpy(ba.data() + sz, reinterpret_cast<char *>(col), chunkSize);
                 values[fieldNum + index] = ba;
                 fieldInf[fieldNum].ind = 0;
             }
         }
     } while (status == OCI_SUCCESS_WITH_INFO || status == OCI_NEED_DATA);
     return r;
 }
size()
int QOCICols::size () inline
Definition at line 798 of file qsql_oci.cpp.
Referenced by create(), and readLOBs().
 { return fieldInf.size(); }
Properties
d
const QOCIResultPrivate* const QOCICols::d private
Definition at line 824 of file qsql_oci.cpp.
Referenced by fieldFromDefine(), getValues(), QOCICols(), readLOBs(), and readPiecewise().
fieldInf
QVector<OraFieldInf> QOCICols::fieldInf private
Definition at line 823 of file qsql_oci.cpp.
Referenced by create(), createLobLocator(), fieldFromDefine(), getValues(), QOCICols(), readLOBs(), and readPiecewise().
rec
QSqlRecord QOCICols::rec
Definition at line 801 of file qsql_oci.cpp.
Referenced by QOCICols(), and QOCIResult::record().
The documentation for this class was generated from the following file:
/src/sql/drivers/oci/qsql_oci.cpp