Qt 4.8: QSslKey Class Reference
QSslKey Class Reference
The QSslKey class provides an interface for private and public keys.
#include <qsslkey.h>
Public Functions
QSsl::KeyAlgorithm algorithm () const
Returns the key algorithm.
void clear ()
Clears the contents of this key, making it a null key.
Qt::HANDLE handle () const
Returns a pointer to the native key handle, if it is available; otherwise a null pointer is returned.
bool isNull () const
Returns true if this is a null key; otherwise false.
int length () const
Returns the length of the key in bits, or -1 if the key is null.
bool operator!= (const QSslKey &key) const
Returns true if this key is not equal to key other; otherwise returns false.
QSslKey & operator= (const QSslKey &other)
Copies the contents of other into this key, making the two keys identical.
bool operator== (const QSslKey &key) const
Returns true if this key is equal to other; otherwise returns false.
QSslKey ()
Constructs a null key.
QSslKey (const QByteArray &encoded, QSsl::KeyAlgorithm algorithm, QSsl::EncodingFormat format=QSsl::Pem, QSsl::KeyType type=QSsl::PrivateKey, const QByteArray &passPhrase=QByteArray())
Constructs a QSslKey by decoding the string in the byte array encoded using a specified algorithm and encoding format.
QSslKey (QIODevice *device, QSsl::KeyAlgorithm algorithm, QSsl::EncodingFormat format=QSsl::Pem, QSsl::KeyType type=QSsl::PrivateKey, const QByteArray &passPhrase=QByteArray())
Constructs a QSslKey by reading and decoding data from a device using a specified algorithm and encoding format.
QSslKey (const QSslKey &other)
Constructs an identical copy of other.
QByteArray toDer (const QByteArray &passPhrase=QByteArray()) const
Returns the key in DER encoding.
QByteArray toPem (const QByteArray &passPhrase=QByteArray()) const
Returns the key in PEM encoding.
QSsl::KeyType type () const
Returns the type of the key (i.e., PublicKey or PrivateKey).
~QSslKey ()
Destroys the QSslKey object.
Properties
QExplicitlySharedDataPointer< QSslKeyPrivate > d
Friends
class QSslCertificate
Detailed Description
The QSslKey class provides an interface for private and public keys.
Since
4.3
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QSslKey provides a simple API for managing keys.
See also
QSslSocket, QSslCertificate, QSslCipher
Definition at line 64 of file qsslkey.h.
Constructors and Destructors
QSslKey() [1/4]
QSslKey::QSslKey ()
Constructs a null key.
See also
isNull()
Definition at line 152 of file qsslkey.cpp.
     : d(new QSslKeyPrivate)
 {
 }
QSslKey() [2/4]
QSslKey::QSslKey (const QByteArray & encoded, QSsl::KeyAlgorithm algorithm, QSsl::EncodingFormat encoding = QSsl::Pem, QSsl::KeyType type = QSsl::PrivateKey, const QByteArray & passPhrase = QByteArray())
Constructs a QSslKey by decoding the string in the byte array encoded using a specified algorithm and encoding format.
If the encoded key is encrypted, passPhrase is used to decrypt it. type specifies whether the key is public or private.
After construction, use isNull() to check if encoded contained a valid key.
Definition at line 245 of file qsslkey.cpp.
     : d(new QSslKeyPrivate)
 {
     d->type = type;
     d->algorithm = algorithm;
     d->decodePem((encoding == QSsl::Der)
                  ? d->pemFromDer(encoded) : encoded,
                  passPhrase);
 }
QSslKey() [3/4]
QSslKey::QSslKey (QIODevice * device, QSsl::KeyAlgorithm algorithm, QSsl::EncodingFormat encoding = QSsl::Pem, QSsl::KeyType type = QSsl::PrivateKey, const QByteArray & passPhrase = QByteArray())
Constructs a QSslKey by reading and decoding data from a device using a specified algorithm and encoding format.
If the encoded key is encrypted, passPhrase is used to decrypt it. type specifies whether the key is public or private.
After construction, use isNull() to check if device provided a valid key.
Definition at line 265 of file qsslkey.cpp.
     : d(new QSslKeyPrivate)
 {
     QByteArray encoded;
     if (device)
         encoded = device->readAll();
     d->type = type;
     d->algorithm = algorithm;
     d->decodePem((encoding == QSsl::Der) ?
                  d->pemFromDer(encoded) : encoded,
                  passPhrase);
 }
QSslKey() [4/4]
QSslKey::QSslKey (const QSslKey & other)
Constructs an identical copy of other.
Definition at line 282 of file qsslkey.cpp.
                                      : d(other.d)
 {
 }
~QSslKey()
QSslKey::~QSslKey ()
Destroys the QSslKey object.
Definition at line 289 of file qsslkey.cpp.
 {
 }
Functions
algorithm()
QSsl::KeyAlgorithm QSslKey::algorithm () const
Returns the key algorithm.
Definition at line 347 of file qsslkey.cpp.
Referenced by QSslSocketBackendPrivate::initSslContext(), operator<<(), operator==(), QSslKeyPrivate::pemFooter(), QSslKeyPrivate::pemHeader(), and QSslKey().
 {
     return d->algorithm;
 }
clear()
void QSslKey::clear ()
Clears the contents of this key, making it a null key.
See also
isNull()
Definition at line 320 of file qsslkey.cpp.
 {
     d = new QSslKeyPrivate;
 }
handle()
Qt::HANDLE QSslKey::handle () const
Returns a pointer to the native key handle, if it is available; otherwise a null pointer is returned.
You can use this handle together with the native API to access extended information about the key.
Warning
Use of this function has a high probability of being non-portable, and its return value may vary across platforms, and between minor Qt releases.
Definition at line 430 of file qsslkey.cpp.
Referenced by QSslSocketBackendPrivate::initSslContext().
 {
     return (d->algorithm == QSsl::Rsa) ? Qt::HANDLE(d->rsa) : Qt::HANDLE(d->dsa);
 }
isNull()
bool QSslKey::isNull () const
Returns true if this is a null key; otherwise false.
See also
clear()
Definition at line 310 of file qsslkey.cpp.
Referenced by QSslSocketBackendPrivate::initSslContext(), QSslConfiguration::isNull(), and operator==().
 {
     return d->isNull;
 }
length()
int QSslKey::length () const
Returns the length of the key in bits, or -1 if the key is null.
Definition at line 328 of file qsslkey.cpp.
Referenced by operator<<(), and operator==().
 {
     if (d->isNull)
         return -1;
     return (d->algorithm == QSsl::Rsa)
            ? q_BN_num_bits(d->rsa->n) : q_BN_num_bits(d->dsa->p);
 }
operator!=()
bool QSslKey::operator!= (const QSslKey & key) const inline
Returns true if this key is not equal to key other; otherwise returns false.
Definition at line 93 of file qsslkey.h.
 { return !operator==(key); }
operator=()
QSslKey & QSslKey::operator= (const QSslKey & other)
Copies the contents of other into this key, making the two keys identical.
Returns a reference to this QSslKey.
Definition at line 299 of file qsslkey.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QSslKey::operator== (const QSslKey & key) const
Returns true if this key is equal to other; otherwise returns false.
Definition at line 438 of file qsslkey.cpp.
 {
     if (isNull())
         return other.isNull();
     if (other.isNull())
         return isNull();
     if (algorithm() != other.algorithm())
         return false;
     if (type() != other.type())
         return false;
     if (length() != other.length())
         return false;
     return toDer() == other.toDer();
 }
toDer()
QByteArray QSslKey::toDer (const QByteArray & passPhrase = QByteArray()) const
Returns the key in DER encoding.
The result is encrypted with passPhrase if the key is a private key and passPhrase is non-empty.
Definition at line 358 of file qsslkey.cpp.
Referenced by operator==().
 {
     if (d->isNull)
         return QByteArray();
     return d->derFromPem(toPem(passPhrase));
 }
toPem()
QByteArray QSslKey::toPem (const QByteArray & passPhrase = QByteArray()) const
Returns the key in PEM encoding.
The result is encrypted with passPhrase if the key is a private key and passPhrase is non-empty.
Definition at line 370 of file qsslkey.cpp.
Referenced by toDer().
 {
     if (!QSslSocket::supportsSsl() || d->isNull)
         return QByteArray();
     BIO *bio = q_BIO_new(q_BIO_s_mem());
     if (!bio)
         return QByteArray();
     bool fail = false;
     if (d->algorithm == QSsl::Rsa) {
         if (d->type == QSsl::PublicKey) {
             if (!q_PEM_write_bio_RSA_PUBKEY(bio, d->rsa))
                 fail = true;
         } else {
             if (!q_PEM_write_bio_RSAPrivateKey(
                     bio, d->rsa,
                     // ### the cipher should be selectable in the API:
                     passPhrase.isEmpty() ? (const EVP_CIPHER *)0 : q_EVP_des_ede3_cbc(),
                     (uchar *)passPhrase.data(), passPhrase.size(), 0, 0)) {
                 fail = true;
             }
         }
     } else {
         if (d->type == QSsl::PublicKey) {
             if (!q_PEM_write_bio_DSA_PUBKEY(bio, d->dsa))
                 fail = true;
         } else {
             if (!q_PEM_write_bio_DSAPrivateKey(
                     bio, d->dsa,
                     // ### the cipher should be selectable in the API:
                     passPhrase.isEmpty() ? (const EVP_CIPHER *)0 : q_EVP_des_ede3_cbc(),
                     (uchar *)passPhrase.data(), passPhrase.size(), 0, 0)) {
                 fail = true;
             }
         }
     }
     QByteArray pem;
     if (!fail) {
         char *data;
         long size = q_BIO_get_mem_data(bio, &data);
         pem = QByteArray(data, size);
     }
     q_BIO_free(bio);
     return pem;
 }
type()
QSsl::KeyType QSslKey::type () const
Returns the type of the key (i.e., PublicKey or PrivateKey).
Definition at line 339 of file qsslkey.cpp.
Referenced by operator<<(), operator==(), QSslKeyPrivate::pemFooter(), QSslKeyPrivate::pemHeader(), and QSslKey().
 {
     return d->type;
 }
Friends and Related Functions
QSslCertificate
friend class QSslCertificate friend
Definition at line 97 of file qsslkey.h.
Properties
d
QExplicitlySharedDataPointer<QSslKeyPrivate> QSslKey::d private
Definition at line 96 of file qsslkey.h.
Referenced by algorithm(), clear(), handle(), isNull(), length(), operator=(), QSslCertificate::publicKey(), QSslKey(), toDer(), toPem(), and type().
The documentation for this class was generated from the following files:
/src/network/ssl/qsslkey.h
/src/network/ssl/qsslkey.cpp