Qt 4.8: QBBScreenEventHandler Class Reference
QBBScreenEventHandler Class Reference
#include <qbbscreeneventhandler.h>
Signals
void newWindowCreated (screen_window_t window)
void windowClosed (screen_window_t window)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool handleEvent (screen_event_t event)
bool handleEvent (screen_event_t event, int qnxType)
void injectPointerMoveEvent (int x, int y)
QBBScreenEventHandler (QBBIntegration *integration)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void injectKeyboardEvent (int flags, int sym, int mod, int scan, int cap)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Types
enum { MAX_TOUCH_POINTS = 10 }
Private Functions
void handleCloseEvent (screen_event_t event)
void handleCreateEvent (screen_event_t event)
void handleDisplayEvent (screen_event_t event)
void handleKeyboardEvent (screen_event_t event)
void handlePointerEvent (screen_event_t event)
void handleTouchEvent (screen_event_t event, int type)
Properties
QBBIntegration * mBBIntegration
Qt::MouseButtons mLastButtonState
QPoint mLastGlobalMousePoint
QPoint mLastLocalMousePoint
void * mLastMouseWindow
QWindowSystemInterface::TouchPoint mTouchPoints [MAX_TOUCH_POINTS]
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 53 of file qbbscreeneventhandler.h.
Enumerations
anonymous enum
anonymous enum private
Enumerator
MAX_TOUCH_POINTS
Definition at line 78 of file qbbscreeneventhandler.h.
          {
         MAX_TOUCH_POINTS = 10
     };
Constructors and Destructors
QBBScreenEventHandler()
QBBScreenEventHandler::QBBScreenEventHandler (QBBIntegration * integration) explicit
Definition at line 59 of file qbbscreeneventhandler.cpp.
     : mBBIntegration(integration)
     , mLastButtonState(Qt::NoButton)
     , mLastMouseWindow(0)
 {
     // initialize array of touch points
     for (int i = 0; i < MAX_TOUCH_POINTS; i++) {
         // map array index to id
         mTouchPoints[i].id = i;
         // first finger is primary
         mTouchPoints[i].isPrimary = (i == 0);
         // pressure is not supported - use default
         mTouchPoints[i].pressure = 1.0;
         // nothing touching
         mTouchPoints[i].state = Qt::TouchPointReleased;
     }
 }
Functions
handleCloseEvent()
void QBBScreenEventHandler::handleCloseEvent (screen_event_t event) private
Definition at line 529 of file qbbscreeneventhandler.cpp.
Referenced by handleEvent().
 {
     screen_window_t window = 0;
     if (screen_get_event_property_pv(event, SCREEN_PROPERTY_WINDOW, (void**)&window) != 0)
         qFatal("QBB: failed to query event window property, errno=%d", errno);
     emit windowClosed(window);
     // map window to top-level widget
     QWidget* w = QWidget::find( (WId)window );
     if (w != NULL)
         QWindowSystemInterface::handleCloseEvent(w);
 }
handleCreateEvent()
void QBBScreenEventHandler::handleCreateEvent (screen_event_t event) private
Definition at line 543 of file qbbscreeneventhandler.cpp.
Referenced by handleEvent().
 {
     screen_window_t window = 0;
     if (screen_get_event_property_pv(event, SCREEN_PROPERTY_WINDOW, (void**)&window) != 0)
         qFatal("QBB: failed to query event window property, errno=%d", errno);
     emit newWindowCreated(window);
 }
handleDisplayEvent()
void QBBScreenEventHandler::handleDisplayEvent (screen_event_t event) private
Definition at line 552 of file qbbscreeneventhandler.cpp.
Referenced by handleEvent().
 {
     screen_display_t nativeDisplay = 0;
     if (screen_get_event_property_pv(event, SCREEN_PROPERTY_DISPLAY, (void **)&nativeDisplay) != 0) {
         qWarning("QBB: failed to query display property, errno=%d", errno);
         return;
     }
     int isAttached = 0;
     if (screen_get_event_property_iv(event, SCREEN_PROPERTY_ATTACHED, &isAttached) != 0) {
         qWarning("QBB: failed to query display attached property, errno=%d", errno);
         return;
     }
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
     qDebug() << Q_FUNC_INFO << "display attachment is now:" << isAttached;
 #endif
     QBBScreen *screen = mBBIntegration->screenForNative(nativeDisplay);
     if (!screen) {
         if (isAttached)
             mBBIntegration->createDisplay(nativeDisplay, false /* not primary, we assume */);
     } else if (!isAttached) {
         // libscreen display is deactivated, let's remove the QBBScreen / QScreen
         mBBIntegration->removeDisplay(screen);
     }
 }
handleEvent() [1/2]
bool QBBScreenEventHandler::handleEvent (screen_event_t event)
Definition at line 81 of file qbbscreeneventhandler.cpp.
Referenced by QBBBpsEventFilter::bpsEventFilter(), and QBBScreenEventThread::run().
 {
     // get the event type
     errno = 0;
     int qnxType;
     int result = screen_get_event_property_iv(event, SCREEN_PROPERTY_TYPE, &qnxType);
     if (result)
         qFatal("QBB: failed to query event type, errno=%d", errno);
     return handleEvent(event, qnxType);
 }
handleEvent() [2/2]
bool QBBScreenEventHandler::handleEvent (screen_event_t event, int qnxType)
Definition at line 94 of file qbbscreeneventhandler.cpp.
 {
     switch (qnxType) {
     case SCREEN_EVENT_MTOUCH_TOUCH:
     case SCREEN_EVENT_MTOUCH_MOVE:
     case SCREEN_EVENT_MTOUCH_RELEASE:
         handleTouchEvent(event, qnxType);
         break;
     case SCREEN_EVENT_KEYBOARD:
         handleKeyboardEvent(event);
         break;
     case SCREEN_EVENT_POINTER:
         handlePointerEvent(event);
         break;
     case SCREEN_EVENT_CLOSE:
         handleCloseEvent(event);
         break;
     case SCREEN_EVENT_CREATE:
         handleCreateEvent(event);
         break;
     case SCREEN_EVENT_DISPLAY:
         handleDisplayEvent(event);
         break;
     default:
         // event ignored
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
         qDebug() << "QBB: QNX unknown event";
 #endif
         return false;
     }
     return true;
 }
handleKeyboardEvent()
void QBBScreenEventHandler::handleKeyboardEvent (screen_event_t event) private
Definition at line 134 of file qbbscreeneventhandler.cpp.
Referenced by handleEvent().
 {
     // get flags of key event
     errno = 0;
     int flags;
     int result = screen_get_event_property_iv(event, SCREEN_PROPERTY_KEY_FLAGS, &flags);
     if (result) {
         qFatal("QBB: failed to query event flags, errno=%d", errno);
     }
     // get key code
     errno = 0;
     int sym;
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_KEY_SYM, &sym);
     if (result) {
         qFatal("QBB: failed to query event sym, errno=%d", errno);
     }
     int modifiers;
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_KEY_MODIFIERS, &modifiers);
     if (result) {
         qFatal("QBB: failed to query event modifiers, errno=%d", errno);
     }
     int scan;
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_KEY_SCAN, &scan);
     if (result) {
         qFatal("QBB: failed to query event modifiers, errno=%d", errno);
     }
     int cap;
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_KEY_CAP, &cap);
     if (result) {
         qFatal("QBB: failed to query event cap, errno=%d", errno);
     }
     // Let the input context have a stab at it first.
     QWidget *focusWidget = QApplication::focusWidget();
     if (focusWidget) {
         QInputContext* inputContext = focusWidget->inputContext();
         if (inputContext) {
             QBBInputContext *qbbInputContext = dynamic_cast<QBBInputContext *>(inputContext);
             if (qbbInputContext && qbbInputContext->handleKeyboardEvent(flags, sym, modifiers, scan, cap))
                 return;
         }
     }
     injectKeyboardEvent(flags, sym, modifiers, scan, cap);
 }
handlePointerEvent()
void QBBScreenEventHandler::handlePointerEvent (screen_event_t event) private
Definition at line 289 of file qbbscreeneventhandler.cpp.
Referenced by handleEvent().
 {
     errno = 0;
     // Query the window that was clicked
     void *qnxWindow;
     int result = screen_get_event_property_pv(event, SCREEN_PROPERTY_WINDOW, &qnxWindow);
     if (result) {
         qFatal("QBB: failed to query event window, errno=%d", errno);
     }
     // Query the button states
     int buttonState = 0;
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_BUTTONS, &buttonState);
     if (result) {
         qFatal("QBB: failed to query event button state, errno=%d", errno);
     }
     // Query the window position
     int windowPos[2];
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_SOURCE_POSITION, windowPos);
     if (result) {
         qFatal("QBB: failed to query event window position, errno=%d", errno);
     }
     // Query the screen position
     int pos[2];
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_POSITION, pos);
     if (result) {
         qFatal("QBB: failed to query event position, errno=%d", errno);
     }
     // Query the wheel delta
     int wheelDelta = 0;
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_MOUSE_WHEEL, &wheelDelta);
     if (result) {
         qFatal("QBB: failed to query event wheel delta, errno=%d", errno);
     }
     // map window to top-level widget
     QWidget* w = QWidget::find( (WId)qnxWindow );
     // Generate enter and leave events as needed.
     if (qnxWindow != mLastMouseWindow) {
         QWidget* wOld = QWidget::find( (WId)mLastMouseWindow );
         if (wOld) {
             QWindowSystemInterface::handleLeaveEvent(wOld);
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
             qDebug() << "QBB: Qt leave, w=" << wOld;
 #endif
         }
         if (w) {
             QWindowSystemInterface::handleEnterEvent(w);
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
             qDebug() << "QBB: Qt enter, w=" << w;
 #endif
         }
     }
     mLastMouseWindow = qnxWindow;
     // Apply scaling to wheel delta and invert value for Qt. We'll probably want to scale
     // this via a system preference at some point. But for now this is a sane value and makes
     // the wheel usable.
     wheelDelta *= -10;
     // convert point to local coordinates
     QPoint globalPoint(pos[0], pos[1]);
     QPoint localPoint(windowPos[0], windowPos[1]);
     // Convert buttons.
     // Some QNX header files invert 'Right Button versus "Left Button' ('Right' == 0x01). But they also offer a 'Button Swap' bit,
     // so we may receive events as shown. (If this is wrong, the fix is easy.)
     // QNX Button mask is 8 buttons wide, with a maximum value of 0x80.
     Qt::MouseButtons buttons = Qt::NoButton;
     if (buttonState & 0x01)
         buttons |= Qt::LeftButton;
     if (buttonState & 0x02)
         buttons |= Qt::MidButton;
     if (buttonState & 0x04)
         buttons |= Qt::RightButton;
     if (buttonState & 0x08)
         buttons |= Qt::XButton1;
     if (buttonState & 0x10)
         buttons |= Qt::XButton2;
     if (w) {
         // Inject mouse event into Qt only if something has changed.
         if (mLastGlobalMousePoint != globalPoint ||
             mLastLocalMousePoint != localPoint ||
             mLastButtonState != buttons) {
             QWindowSystemInterface::handleMouseEvent(w, localPoint, globalPoint, buttons);
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
             qDebug() << "QBB: Qt mouse, w=" << w << ", (" << localPoint.x() << "," << localPoint.y() << "), b=" << (int)buttons;
 #endif
         }
         if (wheelDelta) {
             // Screen only supports a single wheel, so we will assume Vertical orientation for
             // now since that is pretty much standard.
             QWindowSystemInterface::handleWheelEvent(w, localPoint, globalPoint, wheelDelta, Qt::Vertical);
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
             qDebug() << "QBB: Qt wheel, w=" << w << ", (" << localPoint.x() << "," << localPoint.y() << "), d=" << (int)wheelDelta;
 #endif
         }
     }
     mLastGlobalMousePoint = globalPoint;
     mLastLocalMousePoint = localPoint;
     mLastButtonState = buttons;
 }
handleTouchEvent()
void QBBScreenEventHandler::handleTouchEvent (screen_event_t event, int type) private
Definition at line 402 of file qbbscreeneventhandler.cpp.
Referenced by handleEvent().
 {
     // get display coordinates of touch
     errno = 0;
     int pos[2];
     int result = screen_get_event_property_iv(event, SCREEN_PROPERTY_POSITION, pos);
     if (result) {
         qFatal("QBB: failed to query event position, errno=%d", errno);
     }
     QCursor::setPos(pos[0], pos[1]);
     // get window coordinates of touch
     errno = 0;
     int windowPos[2];
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_SOURCE_POSITION, windowPos);
     if (result) {
         qFatal("QBB: failed to query event window position, errno=%d", errno);
     }
     // determine which finger touched
     errno = 0;
     int touchId;
     result = screen_get_event_property_iv(event, SCREEN_PROPERTY_TOUCH_ID, &touchId);
     if (result) {
         qFatal("QBB: failed to query event touch id, errno=%d", errno);
     }
     // determine which window was touched
     errno = 0;
     void *qnxWindow;
     result = screen_get_event_property_pv(event, SCREEN_PROPERTY_WINDOW, &qnxWindow);
     if (result) {
         qFatal("QBB: failed to query event window, errno=%d", errno);
     }
     // check if finger is valid
     if (touchId < MAX_TOUCH_POINTS) {
         // map window to top-level widget
         QWidget* w = QWidget::find( (WId)qnxWindow );
         // Generate enter and leave events as needed.
         if (qnxWindow != mLastMouseWindow) {
             QWidget* wOld = QWidget::find( (WId)mLastMouseWindow );
             if (wOld) {
                 QWindowSystemInterface::handleLeaveEvent(wOld);
     #if defined(QBBSCREENEVENTHANDLER_DEBUG)
                 qDebug() << "QBB: Qt leave, w=" << wOld;
     #endif
             }
             if (w) {
                 QWindowSystemInterface::handleEnterEvent(w);
     #if defined(QBBSCREENEVENTHANDLER_DEBUG)
                 qDebug() << "QBB: Qt enter, w=" << w;
     #endif
             }
         }
         mLastMouseWindow = qnxWindow;
         if (w) {
             // convert primary touch to mouse event
             if (touchId == 0) {
                 // convert point to local coordinates
                 QPoint globalPoint(pos[0], pos[1]);
                 QPoint localPoint(windowPos[0], windowPos[1]);
                 // map touch state to button state
                 Qt::MouseButtons buttons = (qnxType == SCREEN_EVENT_MTOUCH_RELEASE) ? Qt::NoButton : Qt::LeftButton;
                 // inject event into Qt
                 QWindowSystemInterface::handleMouseEvent(w, localPoint, globalPoint, buttons);
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
                 qDebug() << "QBB: Qt mouse, w=" << w << ", (" << localPoint.x() << "," << localPoint.y() << "), b=" << buttons;
 #endif
             }
             // get size of screen which contains window
             QPlatformScreen* platformScreen = QPlatformScreen::platformScreenForWidget(w);
             QSize screenSize = platformScreen->physicalSize();
             // update cached position of current touch point
             mTouchPoints[touchId].normalPosition = QPointF( ((qreal)pos[0]) / screenSize.width(), ((qreal)pos[1]) / screenSize.height() );
             mTouchPoints[touchId].area = QRectF( pos[0], pos[1], 0.0, 0.0 );
             // determine event type and update state of current touch point
             QEvent::Type type = QEvent::None;
             switch (qnxType) {
             case SCREEN_EVENT_MTOUCH_TOUCH:
                 mTouchPoints[touchId].state = Qt::TouchPointPressed;
                 type = QEvent::TouchBegin;
                 break;
             case SCREEN_EVENT_MTOUCH_MOVE:
                 mTouchPoints[touchId].state = Qt::TouchPointMoved;
                 type = QEvent::TouchUpdate;
                 break;
             case SCREEN_EVENT_MTOUCH_RELEASE:
                 mTouchPoints[touchId].state = Qt::TouchPointReleased;
                 type = QEvent::TouchEnd;
                 break;
             }
             // build list of active touch points
             QList<QWindowSystemInterface::TouchPoint> pointList;
             for (int i = 0; i < MAX_TOUCH_POINTS; i++) {
                 if (i == touchId) {
                     // current touch point is always active
                     pointList.append(mTouchPoints[i]);
                 } else if (mTouchPoints[i].state != Qt::TouchPointReleased) {
                     // finger is down but did not move
                     mTouchPoints[i].state = Qt::TouchPointStationary;
                     pointList.append(mTouchPoints[i]);
                 }
             }
             // inject event into Qt
             QWindowSystemInterface::handleTouchEvent(w, type, QTouchEvent::TouchScreen, pointList);
 #if defined(QBBSCREENEVENTHANDLER_DEBUG)
             qDebug() << "QBB: Qt touch, w=" << w << ", p=(" << pos[0] << "," << pos[1] << "), t=" << type;
 #endif
         }
     }
 }
injectKeyboardEvent()
void QBBScreenEventHandler::injectKeyboardEvent (int flags, int sym, int mod, int scan, int cap) static
Definition at line 185 of file qbbscreeneventhandler.cpp.
Referenced by handleKeyboardEvent(), and QBBScreenEventThread::injectKeyboardEvent().
 {
     Q_UNUSED(scan);
     Qt::KeyboardModifiers qtMod = Qt::NoModifier;
     if (modifiers & KEYMOD_SHIFT)
         qtMod |= Qt::ShiftModifier;
     if (modifiers & KEYMOD_CTRL)
         qtMod |= Qt::ControlModifier;
     if (modifiers & KEYMOD_ALT)
         qtMod |= Qt::AltModifier;
     // determine event type
     QEvent::Type type = (flags & KEY_DOWN) ? QEvent::KeyPress : QEvent::KeyRelease;
     // Check if the key cap is valid
     if (flags & KEY_CAP_VALID) {
         Qt::Key key;
         QString keyStr;
         if (cap >= 0x20 && cap <= 0x0ff) {
             key = Qt::Key(std::toupper(cap));   // Qt expects the CAP to be upper case.
             if ( qtMod & Qt::ControlModifier ) {
                 keyStr = QChar((int)(key & 0x3f));
             } else {
                 if (flags & KEY_SYM_VALID) {
                     keyStr = QChar(sym);
                 }
             }
         } else if ((cap > 0x0ff && cap < UNICODE_PRIVATE_USE_AREA_FIRST) || cap > UNICODE_PRIVATE_USE_AREA_LAST) {
             key = (Qt::Key)cap;
             keyStr = QChar(sym);
         } else {
             if (isKeypadKey(cap))
                 qtMod |= Qt::KeypadModifier; // Is this right?
             key = keyTranslator(cap);
         }
         QWindowSystemInterface::handleExtendedKeyEvent(QApplication::activeWindow(), type, key, qtMod,
                                                        scan, sym, modifiers, keyStr);
 #if defined(QBBScreenEventHandler_DEBUG)
         qDebug() << "QBB: Qt key t=" << type << ", k=" << key << ", s=" << keyStr;
 #endif
     }
 }
injectPointerMoveEvent()
void QBBScreenEventHandler::injectPointerMoveEvent (int x, int y)
Definition at line 232 of file qbbscreeneventhandler.cpp.
Referenced by QBBScreenEventThread::injectPointerMoveEvent().
 {
 #if defined(QBBScreenEventHandler_DEBUG)
     qDebug() << "Injecting mouse event..." << x << y;
 #endif
     QWidget *w = qApp->topLevelAt(x, y);
     void *qnxWindow = w ? w->platformWindow() : 0;
     // Generate enter and leave events as needed.
     if (qnxWindow != mLastMouseWindow) {
         QWidget* wOld = QWidget::find( (WId)mLastMouseWindow );
         if (wOld) {
             QWindowSystemInterface::handleLeaveEvent(wOld);
 #if defined(QBBScreenEventHandler_DEBUG)
             qDebug() << "QBB: Qt leave, w=" << wOld;
 #endif
         }
         if (w) {
             QWindowSystemInterface::handleEnterEvent(w);
 #if defined(QBBScreenEventHandler_DEBUG)
             qDebug() << "QBB: Qt enter, w=" << w;
 #endif
         }
     }
     mLastMouseWindow = qnxWindow;
     // convert point to local coordinates
     QPoint globalPoint(x, y);
     QPoint localPoint(x, y);
     if (w)
         localPoint = QPoint(x - w->x(), y - w->y());
     // Convert buttons.
     Qt::MouseButtons buttons = mLastButtonState;
     if (w) {
         // Inject mouse event into Qt only if something has changed.
         if (mLastGlobalMousePoint != globalPoint ||
             mLastLocalMousePoint != localPoint ||
             mLastButtonState != buttons) {
             QWindowSystemInterface::handleMouseEvent(w, localPoint, globalPoint, buttons);
 #if defined(QBBScreenEventHandler_DEBUG)
             qDebug() << "QBB: Qt mouse, w=" << w << ", (" << localPoint.x() << "," << localPoint.y() << "), b=" << (int)buttons;
 #endif
         }
     }
     mLastGlobalMousePoint = globalPoint;
     mLastLocalMousePoint = localPoint;
     mLastButtonState = buttons;
 }
newWindowCreated
void QBBScreenEventHandler::newWindowCreated (screen_window_t window) signal
Referenced by handleCreateEvent().
windowClosed
void QBBScreenEventHandler::windowClosed (screen_window_t window) signal
Referenced by handleCloseEvent().
Properties
mBBIntegration
QBBIntegration* QBBScreenEventHandler::mBBIntegration private
Definition at line 82 of file qbbscreeneventhandler.h.
Referenced by handleDisplayEvent().
mLastButtonState
Qt::MouseButtons QBBScreenEventHandler::mLastButtonState private
Definition at line 85 of file qbbscreeneventhandler.h.
Referenced by handlePointerEvent(), and injectPointerMoveEvent().
mLastGlobalMousePoint
QPoint QBBScreenEventHandler::mLastGlobalMousePoint private
Definition at line 83 of file qbbscreeneventhandler.h.
Referenced by handlePointerEvent(), and injectPointerMoveEvent().
mLastLocalMousePoint
QPoint QBBScreenEventHandler::mLastLocalMousePoint private
Definition at line 84 of file qbbscreeneventhandler.h.
Referenced by handlePointerEvent(), and injectPointerMoveEvent().
mLastMouseWindow
void* QBBScreenEventHandler::mLastMouseWindow private
Definition at line 86 of file qbbscreeneventhandler.h.
Referenced by handlePointerEvent(), handleTouchEvent(), and injectPointerMoveEvent().
mTouchPoints
QWindowSystemInterface::TouchPoint QBBScreenEventHandler::mTouchPoints[MAX_TOUCH_POINTS] private
Definition at line 88 of file qbbscreeneventhandler.h.
Referenced by handleTouchEvent(), and QBBScreenEventHandler().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbscreeneventhandler.h
/src/plugins/platforms/blackberry/qbbscreeneventhandler.cpp