Qt 4.8: QUrlInfo Class Reference
QUrlInfo Class Reference
The QUrlInfo class stores information about URLs.
#include <qurlinfo.h>
Public Types
enum PermissionSpec {
ReadOwner = 00400, WriteOwner = 00200, ExeOwner = 00100, ReadGroup = 00040,
WriteGroup = 00020, ExeGroup = 00010, ReadOther = 00004, WriteOther = 00002,
ExeOther = 00001
}
This enum is used by the permissions() function to report the permissions of a file.
Public Functions
QString group () const
Returns the group of the URL.
bool isDir () const
Returns true if the URL is a directory; otherwise returns false.
bool isExecutable () const
Returns true if the URL is executable; otherwise returns false.
bool isFile () const
Returns true if the URL is a file; otherwise returns false.
bool isReadable () const
Returns true if the URL is readable; otherwise returns false.
bool isSymLink () const
Returns true if the URL is a symbolic link; otherwise returns false.
bool isValid () const
Returns true if the URL info is valid; otherwise returns false.
bool isWritable () const
Returns true if the URL is writable; otherwise returns false.
QDateTime lastModified () const
Returns the last modification date of the URL.
QDateTime lastRead () const
Returns the date when the URL was last read.
QString name () const
Returns the file name of the URL.
bool operator!= (const QUrlInfo &i) const
Returns true if this QUrlInfo is not equal to other; otherwise returns false.
QUrlInfo & operator= (const QUrlInfo &ui)
Assigns the values of ui to this QUrlInfo object.
bool operator== (const QUrlInfo &i) const
Returns true if this QUrlInfo is equal to other; otherwise returns false.
QString owner () const
Returns the owner of the URL.
int permissions () const
Returns the permissions of the URL.
QUrlInfo ()
Constructs an invalid QUrlInfo object with default values.
QUrlInfo (const QUrlInfo &ui)
Copy constructor, copies ui to this URL info object.
QUrlInfo (const QString &name, int permissions, const QString &owner, const QString &group, qint64 size, const QDateTime &lastModified, const QDateTime &lastRead, bool isDir, bool isFile, bool isSymLink, bool isWritable, bool isReadable, bool isExecutable)
Constructs a QUrlInfo object by specifying all the URL's information.
QUrlInfo (const QUrl &url, int permissions, const QString &owner, const QString &group, qint64 size, const QDateTime &lastModified, const QDateTime &lastRead, bool isDir, bool isFile, bool isSymLink, bool isWritable, bool isReadable, bool isExecutable)
Constructs a QUrlInfo object by specifying all the URL's information.
virtual void setDir (bool b)
If b is true then the URL is set to be a directory; if b is false then the URL is set not to be a directory (which normally means it is a file).
virtual void setFile (bool b)
If b is true then the URL is set to be a file; if is false then the URL is set not to be a file (which normally means it is a directory).
virtual void setGroup (const QString &s)
Specifies that the owning group of the URL is called s.
virtual void setLastModified (const QDateTime &dt)
Specifies that the object the URL refers to was last modified at dt.
void setLastRead (const QDateTime &dt)
Specifies that the object the URL refers to was last read at dt.
virtual void setName (const QString &name)
Sets the name of the URL to name.
virtual void setOwner (const QString &s)
Specifies that the owner of the URL is called s.
virtual void setPermissions (int p)
Specifies that the URL has access permissions p.
virtual void setReadable (bool b)
Specifies that the URL is readable if b is true and not readable if b is false.
virtual void setSize (qint64 size)
Specifies the size of the URL.
virtual void setSymLink (bool b)
Specifies that the URL refers to a symbolic link if b is true and that it does not if b is false.
virtual void setWritable (bool b)
Specifies that the URL is writable if b is true and not writable if b is false.
qint64 size () const
Returns the size of the URL.
virtual ~QUrlInfo ()
Destroys the URL info object.
Static Public Functions
static bool equal (const QUrlInfo &i1, const QUrlInfo &i2, int sortBy)
Returns true if i1 equals to i2; otherwise returns false.
static bool greaterThan (const QUrlInfo &i1, const QUrlInfo &i2, int sortBy)
Returns true if i1 is greater than i2; otherwise returns false.
static bool lessThan (const QUrlInfo &i1, const QUrlInfo &i2, int sortBy)
Returns true if i1 is less than i2; otherwise returns false.
Properties
QUrlInfoPrivate * d
Detailed Description
The QUrlInfo class stores information about URLs.
The information about a URL that can be retrieved includes name(), permissions(), owner(), group(), size(), lastModified(), lastRead(), isDir(), isFile(), isSymLink(), isWritable(), isReadable() and isExecutable().
You can create your own QUrlInfo objects passing in all the relevant information in the constructor, and you can modify a QUrlInfo; for each getter mentioned above there is an equivalent setter. Note that setting values does not affect the underlying resource that the QUrlInfo provides information about; for example if you call setWritable(true) on a read-only resource the only thing changed is the QUrlInfo object, not the resource.
See also
QUrl, {FTP Example}
Definition at line 60 of file qurlinfo.h.
Enumerations
PermissionSpec
enum QUrlInfo::PermissionSpec
This enum is used by the permissions() function to report the permissions of a file.
ReadOwner The file is readable by the owner of the file.
WriteOwner The file is writable by the owner of the file.
ExeOwner The file is executable by the owner of the file.
ReadGroup The file is readable by the group.
WriteGroup The file is writable by the group.
ExeGroup The file is executable by the group.
ReadOther The file is readable by anyone.
WriteOther The file is writable by anyone.
ExeOther The file is executable by anyone.
Enumerator
ReadOwner
WriteOwner
ExeOwner
ReadGroup
WriteGroup
ExeGroup
ReadOther
WriteOther
ExeOther
Definition at line 63 of file qurlinfo.h.
{
         ReadOwner = 00400, WriteOwner = 00200, ExeOwner = 00100,
         ReadGroup = 00040, WriteGroup = 00020, ExeGroup = 00010,
         ReadOther = 00004, WriteOther = 00002, ExeOther = 00001 };
Constructors and Destructors
QUrlInfo() [1/4]
QUrlInfo::QUrlInfo ()
Constructs an invalid QUrlInfo object with default values.
See also
isValid()
Definition at line 135 of file qurlinfo.cpp.
 {
     d = 0;
 }
QUrlInfo() [2/4]
QUrlInfo::QUrlInfo (const QUrlInfo & ui)
Copy constructor, copies ui to this URL info object.
Definition at line 144 of file qurlinfo.cpp.
 {
     if (ui.d) {
         d = new QUrlInfoPrivate;
         *d = *ui.d;
     } else {
         d = 0;
     }
 }
QUrlInfo() [3/4]
QUrlInfo::QUrlInfo (const QString & name, int permissions, const QString & owner, const QString & group, qint64 size, const QDateTime & lastModified, const QDateTime & lastRead, bool isDir, bool isFile, bool isSymLink, bool isWritable, bool isReadable, bool isExecutable)
Constructs a QUrlInfo object by specifying all the URL's information.
The information that is passed is the name, file permissions, owner and group and the file's size. Also passed is the lastModified date/time and the lastRead date/time. Flags are also passed, specifically, isDir, isFile, isSymLink, isWritable, isReadable and isExecutable.
Definition at line 166 of file qurlinfo.cpp.
 {
     d = new QUrlInfoPrivate;
     d->name = name;
     d->permissions = permissions;
     d->owner = owner;
     d->group = group;
     d->size = size;
     d->lastModified = lastModified;
     d->lastRead = lastRead;
     d->isDir = isDir;
     d->isFile = isFile;
     d->isSymLink = isSymLink;
     d->isWritable = isWritable;
     d->isReadable = isReadable;
     d->isExecutable = isExecutable;
 }
QUrlInfo() [4/4]
QUrlInfo::QUrlInfo (const QUrl & url, int permissions, const QString & owner, const QString & group, qint64 size, const QDateTime & lastModified, const QDateTime & lastRead, bool isDir, bool isFile, bool isSymLink, bool isWritable, bool isReadable, bool isExecutable)
Constructs a QUrlInfo object by specifying all the URL's information.
The information that is passed is the url, file permissions, owner and group and the file's size. Also passed is the lastModified date/time and the lastRead date/time. Flags are also passed, specifically, isDir, isFile, isSymLink, isWritable, isReadable and isExecutable.
Definition at line 200 of file qurlinfo.cpp.
 {
     d = new QUrlInfoPrivate;
     d->name = QFileInfo(url.path()).fileName();
     d->permissions = permissions;
     d->owner = owner;
     d->group = group;
     d->size = size;
     d->lastModified = lastModified;
     d->lastRead = lastRead;
     d->isDir = isDir;
     d->isFile = isFile;
     d->isSymLink = isSymLink;
     d->isWritable = isWritable;
     d->isReadable = isReadable;
     d->isExecutable = isExecutable;
 }
~QUrlInfo()
QUrlInfo::~QUrlInfo () virtual
Destroys the URL info object.
Definition at line 440 of file qurlinfo.cpp.
 {
     delete d;
 }
Functions
equal()
bool QUrlInfo::equal (const QUrlInfo & i1, const QUrlInfo & i2, int sortBy) static
Returns true if i1 equals to i2; otherwise returns false.
The objects are compared by the value, which is specified by sortBy. This must be one of QDir::Name, QDir::Time or QDir::Size.
Definition at line 672 of file qurlinfo.cpp.
 {
     switch (sortBy) {
     case QDir::Name:
         return i1.name() == i2.name();
     case QDir::Time:
         return i1.lastModified() == i2.lastModified();
     case QDir::Size:
         return i1.size() == i2.size();
     default:
         return false;
     }
 }
greaterThan()
bool QUrlInfo::greaterThan (const QUrlInfo & i1, const QUrlInfo & i2, int sortBy) static
Returns true if i1 is greater than i2; otherwise returns false.
The objects are compared by the value, which is specified by sortBy. This must be one of QDir::Name, QDir::Time or QDir::Size.
Definition at line 639 of file qurlinfo.cpp.
 {
     switch (sortBy) {
     case QDir::Name:
         return i1.name() > i2.name();
     case QDir::Time:
         return i1.lastModified() > i2.lastModified();
     case QDir::Size:
         return i1.size() > i2.size();
     default:
         return false;
     }
 }
group()
QString QUrlInfo::group () const
Returns the group of the URL.
See also
isValid()
Definition at line 508 of file qurlinfo.cpp.
 {
     if (!d)
         return QString();
     return d->group;
 }
isDir()
bool QUrlInfo::isDir () const
Returns true if the URL is a directory; otherwise returns false.
See also
isValid()
Definition at line 560 of file qurlinfo.cpp.
 {
     if (!d)
         return false;
     return d->isDir;
 }
isExecutable()
bool QUrlInfo::isExecutable () const
Returns true if the URL is executable; otherwise returns false.
See also
isValid()
Definition at line 625 of file qurlinfo.cpp.
 {
     if (!d)
         return false;
     return d->isExecutable;
 }
isFile()
bool QUrlInfo::isFile () const
Returns true if the URL is a file; otherwise returns false.
See also
isValid()
Definition at line 573 of file qurlinfo.cpp.
Referenced by _q_parseDosDir().
 {
     if (!d)
         return false;
     return d->isFile;
 }
isReadable()
bool QUrlInfo::isReadable () const
Returns true if the URL is readable; otherwise returns false.
See also
isValid()
Definition at line 612 of file qurlinfo.cpp.
 {
     if (!d)
         return false;
     return d->isReadable;
 }
isSymLink()
bool QUrlInfo::isSymLink () const
Returns true if the URL is a symbolic link; otherwise returns false.
See also
isValid()
Definition at line 586 of file qurlinfo.cpp.
Referenced by _q_parseUnixDir().
 {
     if (!d)
         return false;
     return d->isSymLink;
 }
isValid()
bool QUrlInfo::isValid () const
Returns true if the URL info is valid; otherwise returns false.
Valid means that the QUrlInfo contains real information.
You should always check if the URL info is valid before relying on the values.
Definition at line 736 of file qurlinfo.cpp.
 {
     return d != 0;
 }
isWritable()
bool QUrlInfo::isWritable () const
Returns true if the URL is writable; otherwise returns false.
See also
isValid()
Definition at line 599 of file qurlinfo.cpp.
 {
     if (!d)
         return false;
     return d->isWritable;
 }
lastModified()
QDateTime QUrlInfo::lastModified () const
Returns the last modification date of the URL.
See also
isValid()
Definition at line 534 of file qurlinfo.cpp.
Referenced by equal(), and greaterThan().
 {
     if (!d)
         return QDateTime();
     return d->lastModified;
 }
lastRead()
QDateTime QUrlInfo::lastRead () const
Returns the date when the URL was last read.
See also
isValid()
Definition at line 547 of file qurlinfo.cpp.
 {
     if (!d)
         return QDateTime();
     return d->lastRead;
 }
lessThan()
bool QUrlInfo::lessThan (const QUrlInfo & i1, const QUrlInfo & i2, int sortBy) static
Returns true if i1 is less than i2; otherwise returns false.
The objects are compared by the value, which is specified by sortBy. This must be one of QDir::Name, QDir::Time or QDir::Size.
Definition at line 660 of file qurlinfo.cpp.
 {
     return !greaterThan(i1, i2, sortBy);
 }
name()
QString QUrlInfo::name () const
Returns the file name of the URL.
See also
isValid()
Definition at line 468 of file qurlinfo.cpp.
Referenced by equal(), and greaterThan().
 {
     if (!d)
         return QString();
     return d->name;
 }
operator!=()
bool QUrlInfo::operator!= (const QUrlInfo & other) const inline
Returns true if this QUrlInfo is not equal to other; otherwise returns false.
Since
4.2
See also
lessThan(), equal()
Definition at line 118 of file qurlinfo.h.
     { return !operator==(i); }
operator=()
QUrlInfo & QUrlInfo::operator= (const QUrlInfo & ui)
Assigns the values of ui to this QUrlInfo object.
Definition at line 449 of file qurlinfo.cpp.
 {
     if (ui.d) {
         if (!d)
             d= new QUrlInfoPrivate;
         *d = *ui.d;
     } else {
         delete d;
         d = 0;
     }
     return *this;
 }
operator==()
bool QUrlInfo::operator== (const QUrlInfo & other) const
Returns true if this QUrlInfo is equal to other; otherwise returns false.
See also
lessThan(), equal()
Definition at line 694 of file qurlinfo.cpp.
 {
     if (!d)
         return other.d == 0;
     if (!other.d)
         return false;
     return (d->name == other.d->name &&
             d->permissions == other.d->permissions &&
             d->owner == other.d->owner &&
             d->group == other.d->group &&
             d->size == other.d->size &&
             d->lastModified == other.d->lastModified &&
             d->lastRead == other.d->lastRead &&
             d->isDir == other.d->isDir &&
             d->isFile == other.d->isFile &&
             d->isSymLink == other.d->isSymLink &&
             d->isWritable == other.d->isWritable &&
             d->isReadable == other.d->isReadable &&
             d->isExecutable == other.d->isExecutable);
 }
owner()
QString QUrlInfo::owner () const
Returns the owner of the URL.
See also
isValid()
Definition at line 495 of file qurlinfo.cpp.
Referenced by _q_parseUnixDir().
 {
     if (!d)
         return QString();
     return d->owner;
 }
permissions()
int QUrlInfo::permissions () const
Returns the permissions of the URL.
You can use the PermissionSpec flags to test for certain permissions.
See also
isValid()
Definition at line 482 of file qurlinfo.cpp.
 {
     if (!d)
         return 0;
     return d->permissions;
 }
setDir()
void QUrlInfo::setDir (bool b) virtual
If b is true then the URL is set to be a directory; if b is false then the URL is set not to be a directory (which normally means it is a file).
(Note that a URL can refer to both a file and a directory even though most file systems do not support this.)
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 252 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->isDir = b;
 }
setFile()
void QUrlInfo::setFile (bool b) virtual
If b is true then the URL is set to be a file; if is false then the URL is set not to be a file (which normally means it is a directory).
(Note that a URL can refer to both a file and a directory even though most file systems do not support this.)
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 272 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->isFile = b;
 }
setGroup()
void QUrlInfo::setGroup (const QString & s) virtual
Specifies that the owning group of the URL is called s.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 358 of file qurlinfo.cpp.
Referenced by _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->group = s;
 }
setLastModified()
void QUrlInfo::setLastModified (const QDateTime & dt) virtual
Specifies that the object the URL refers to was last modified at dt.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 407 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->lastModified = dt;
 }
setLastRead()
void QUrlInfo::setLastRead (const QDateTime & dt)
Specifies that the object the URL refers to was last read at dt.
Since
4.4
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 429 of file qurlinfo.cpp.
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->lastRead = dt;
 }
setName()
void QUrlInfo::setName (const QString & name) virtual
Sets the name of the URL to name.
The name is the full text, for example, "http://qt.nokia.com/doc/qurlinfo.html".
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 232 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->name = name;
 }
setOwner()
void QUrlInfo::setOwner (const QString & s) virtual
Specifies that the owner of the URL is called s.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 342 of file qurlinfo.cpp.
Referenced by _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->owner = s;
 }
setPermissions()
void QUrlInfo::setPermissions (int p) virtual
Specifies that the URL has access permissions p.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 390 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->permissions = p;
 }
setReadable()
void QUrlInfo::setReadable (bool b) virtual
Specifies that the URL is readable if b is true and not readable if b is false.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 326 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->isReadable = b;
 }
setSize()
void QUrlInfo::setSize (qint64 size) virtual
Specifies the size of the URL.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 374 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->size = size;
 }
setSymLink()
void QUrlInfo::setSymLink (bool b) virtual
Specifies that the URL refers to a symbolic link if b is true and that it does not if b is false.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 290 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->isSymLink = b;
 }
setWritable()
void QUrlInfo::setWritable (bool b) virtual
Specifies that the URL is writable if b is true and not writable if b is false.
If you call this function for an invalid URL info, this function turns it into a valid one.
See also
isValid()
Definition at line 308 of file qurlinfo.cpp.
Referenced by _q_parseDosDir(), and _q_parseUnixDir().
 {
     if (!d)
         d = new QUrlInfoPrivate;
     d->isWritable = b;
 }
size()
qint64 QUrlInfo::size () const
Returns the size of the URL.
See also
isValid()
Definition at line 521 of file qurlinfo.cpp.
Referenced by equal(), and greaterThan().
 {
     if (!d)
         return 0;
     return d->size;
 }
Properties
d
QUrlInfoPrivate* QUrlInfo::d private
Definition at line 122 of file qurlinfo.h.
Referenced by operator=(), operator==(), and QUrlInfo().
The documentation for this class was generated from the following files:
/src/network/kernel/qurlinfo.h
/src/network/kernel/qurlinfo.cpp