Qt 4.8: QScript::QObjectDelegate Class Reference
QScript::QObjectDelegate Class Reference
#include <qscriptqobject_p.h>
Classes
struct Data
Public Functions
virtual bool compareToObject (QScriptObject *, JSC::ExecState *, JSC::JSObject *)
virtual bool deleteProperty (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName)
virtual bool getOwnPropertyDescriptor (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertyDescriptor &)
virtual void getOwnPropertyNames (QScriptObject *, JSC::ExecState *, JSC::PropertyNameArray &, JSC::EnumerationMode mode=JSC::ExcludeDontEnumProperties)
virtual bool getOwnPropertySlot (QScriptObject *, JSC::ExecState *, const JSC::Identifier &propertyName, JSC::PropertySlot &)
virtual void markChildren (QScriptObject *, JSC::MarkStack &markStack)
QScriptEngine::QObjectWrapOptions options () const
QScriptEngine::ValueOwnership ownership () const
virtual void put (QScriptObject *, JSC::ExecState *exec, const JSC::Identifier &propertyName, JSC::JSValue, JSC::PutPropertySlot &)
QObjectDelegate (QObject *object, QScriptEngine::ValueOwnership ownership, const QScriptEngine::QObjectWrapOptions &options)
void setOptions (QScriptEngine::QObjectWrapOptions options)
void setOwnership (QScriptEngine::ValueOwnership ownership)
void setValue (QObject *value)
virtual Type type () const
QObject * value () const
~QObjectDelegate ()
Public Functions inherited from QScriptObjectDelegate
virtual JSC::CallType getCallData (QScriptObject *, JSC::CallData &)
virtual JSC::ConstructType getConstructData (QScriptObject *, JSC::ConstructData &)
virtual bool hasInstance (QScriptObject *, JSC::ExecState *, JSC::JSValue value, JSC::JSValue proto)
QScriptObjectDelegate ()
virtual ~QScriptObjectDelegate ()
Protected Variables
Data * data
Additional Inherited Members
Public Types inherited from QScriptObjectDelegate
enum Type { QtObject, Variant, ClassObject, DeclarativeClassObject }
Detailed Description
Definition at line 55 of file qscriptqobject_p.h.
Constructors and Destructors
QObjectDelegate()
QScript::QObjectDelegate::QObjectDelegate (QObject * object, QScriptEngine::ValueOwnership ownership, const QScriptEngine::QObjectWrapOptions & options)
Definition at line 1163 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data().
     : data(new Data(object, ownership, options))
 {
 }
~QObjectDelegate()
QScript::QObjectDelegate::~QObjectDelegate ()
Definition at line 1170 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data().
 {
     switch (data->ownership) {
     case QScriptEngine::QtOwnership:
         break;
     case QScriptEngine::ScriptOwnership:
         if (data->value)
             delete data->value; // ### fixme
 //            eng->disposeQObject(value);
         break;
     case QScriptEngine::AutoOwnership:
         if (data->value && !data->value->parent())
             delete data->value; // ### fixme
 //            eng->disposeQObject(value);
         break;
     }
     delete data;
 }
Functions
compareToObject()
bool QScript::QObjectDelegate::compareToObject (QScriptObject * , JSC::ExecState * exec, JSC::JSObject * o2) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 1654 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data().
 {
     if (!o2->inherits(&QScriptObject::info))
         return false;
     QScriptObject *object = static_cast<QScriptObject*>(o2);
     QScriptObjectDelegate *delegate = object->delegate();
     if (!delegate || (delegate->type() != QScriptObjectDelegate::QtObject))
         return false;
     return value() == static_cast<QObjectDelegate *>(delegate)->value();
 }
deleteProperty()
bool QScript::QObjectDelegate::deleteProperty (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 1544 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data(), and QScript::QMetaObjectWrapperObject::Data::Data().
 {
 #ifndef QT_NO_PROPERTIES
     QByteArray name = convertToLatin1(propertyName.ustring());
     QObject *qobject = data->value;
     if (!qobject) {
         QString message = QString::fromLatin1("cannot access member `%0' of deleted QObject")
                           .arg(QString::fromLatin1(name));
         JSC::throwError(exec, JSC::GeneralError, message);
         return false;
     }
     const QMetaObject *meta = qobject->metaObject();
     {
         QHash<QByteArray, JSC::JSValue>::iterator it = data->cachedMembers.find(name);
         if (it != data->cachedMembers.end()) {
             if (GeneratePropertyFunctions && (meta->indexOfProperty(name) != -1))
                 return false;
             data->cachedMembers.erase(it);
             return true;
         }
     }
     const QScriptEngine::QObjectWrapOptions &opt = data->options;
     int index = meta->indexOfProperty(name);
     if (index != -1) {
         QMetaProperty prop = meta->property(index);
         if (prop.isScriptable() &&
             (!(opt & QScriptEngine::ExcludeSuperClassProperties)
              || (index >= meta->propertyOffset()))) {
                 return false;
         }
     }
     index = qobject->dynamicPropertyNames().indexOf(name);
     if (index != -1) {
         (void)qobject->setProperty(name, QVariant());
         return true;
     }
     return QScriptObjectDelegate::deleteProperty(object, exec, propertyName);
 #else //QT_NO_PROPERTIES
     return false;
 #endif //QT_NO_PROPERTIES
 }
getOwnPropertyDescriptor()
bool QScript::QObjectDelegate::getOwnPropertyDescriptor (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertyDescriptor & descriptor) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 1311 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data(), and QScript::QMetaObjectWrapperObject::Data::Data().
 {
     //Note: this has to be kept in sync with getOwnPropertySlot
 #ifndef QT_NO_PROPERTIES
     QByteArray name = convertToLatin1(propertyName.ustring());
     QObject *qobject = data->value;
     if (!qobject) {
         QString message = QString::fromLatin1("cannot access member `%0' of deleted QObject")
                           .arg(QString::fromLatin1(name));
         descriptor.setValue(JSC::throwError(exec, JSC::GeneralError, message));
         return true;
     }
     const QScriptEngine::QObjectWrapOptions &opt = data->options;
     const QMetaObject *meta = qobject->metaObject();
     {
         QHash<QByteArray, JSC::JSValue>::const_iterator it = data->cachedMembers.constFind(name);
         if (it != data->cachedMembers.constEnd()) {
             int index;
             if (GeneratePropertyFunctions && ((index = meta->indexOfProperty(name)) != -1)) {
                 QMetaProperty prop = meta->property(index);
                 descriptor.setAccessorDescriptor(it.value(), it.value(), flagsForMetaProperty(prop));
                 if (!prop.isWritable())
                     descriptor.setWritable(false);
             } else {
                 unsigned attributes = QObjectMemberAttribute;
                 if (opt & QScriptEngine::SkipMethodsInEnumeration)
                     attributes |= JSC::DontEnum;
                 descriptor.setDescriptor(it.value(), attributes);
             }
             return true;
         }
     }
     QScriptEnginePrivate *eng = scriptEngineFromExec(exec);
     int index = -1;
     if (name.contains('(')) {
         QByteArray normalized = QMetaObject::normalizedSignature(name);
         if (-1 != (index = meta->indexOfMethod(normalized))) {
             QMetaMethod method = meta->method(index);
             if (hasMethodAccess(method, index, opt)) {
                 if (!(opt & QScriptEngine::ExcludeSuperClassMethods)
                     || (index >= meta->methodOffset())) {
                     QtFunction *fun = new (exec)QtFunction(
                         object, index, /*maybeOverloaded=*/false,
                         &exec->globalData(), eng->originalGlobalObject()->functionStructure(),
                         propertyName);
                     data->cachedMembers.insert(name, fun);
                     unsigned attributes = QObjectMemberAttribute;
                     if (opt & QScriptEngine::SkipMethodsInEnumeration)
                         attributes |= JSC::DontEnum;
                     descriptor.setDescriptor(fun, attributes);
                     return true;
                 }
             }
         }
     }
     index = meta->indexOfProperty(name);
     if (index != -1) {
         QMetaProperty prop = meta->property(index);
         if (prop.isScriptable()) {
             if (!(opt & QScriptEngine::ExcludeSuperClassProperties)
                 || (index >= meta->propertyOffset())) {
                 unsigned attributes = flagsForMetaProperty(prop);
                 if (GeneratePropertyFunctions) {
                     QtPropertyFunction *fun = new (exec)QtPropertyFunction(
                         meta, index, &exec->globalData(),
                         eng->originalGlobalObject()->functionStructure(),
                         propertyName);
                     data->cachedMembers.insert(name, fun);
                     descriptor.setAccessorDescriptor(fun, fun, attributes);
                     if (attributes & JSC::ReadOnly)
                         descriptor.setWritable(false);
                 } else {
                     JSC::JSValue val;
                     if (!prop.isValid())
                         val = JSC::jsUndefined();
                     else
                         val = QScriptEnginePrivate::jscValueFromVariant(exec, prop.read(qobject));
                     descriptor.setDescriptor(val, attributes);
                 }
                 return true;
             }
         }
     }
     index = qobject->dynamicPropertyNames().indexOf(name);
     if (index != -1) {
         JSC::JSValue val = QScriptEnginePrivate::jscValueFromVariant(exec, qobject->property(name));
         descriptor.setDescriptor(val, QObjectMemberAttribute);
         return true;
     }
     const int offset = (opt & QScriptEngine::ExcludeSuperClassMethods)
                        ? meta->methodOffset() : 0;
     for (index = meta->methodCount() - 1; index >= offset; --index) {
         QMetaMethod method = meta->method(index);
         if (hasMethodAccess(method, index, opt)
             && methodNameEquals(method, name.constData(), name.length())) {
             QtFunction *fun = new (exec)QtFunction(
                 object, index, /*maybeOverloaded=*/true,
                 &exec->globalData(), eng->originalGlobalObject()->functionStructure(),
                 propertyName);
             unsigned attributes = QObjectMemberAttribute;
             if (opt & QScriptEngine::SkipMethodsInEnumeration)
                 attributes |= JSC::DontEnum;
             descriptor.setDescriptor(fun, attributes);
             data->cachedMembers.insert(name, fun);
             return true;
         }
     }
     if (!(opt & QScriptEngine::ExcludeChildObjects)) {
         QList<QObject*> children = qobject->children();
         for (index = 0; index < children.count(); ++index) {
             QObject *child = children.at(index);
             if (child->objectName() == QString(propertyName.ustring())) {
                 QScriptEngine::QObjectWrapOptions opt = QScriptEngine::PreferExistingWrapperObject;
                 descriptor.setDescriptor(eng->newQObject(child, QScriptEngine::QtOwnership, opt),
                                          JSC::ReadOnly | JSC::DontDelete | JSC::DontEnum);
                 return true;
             }
         }
     }
     return QScriptObjectDelegate::getOwnPropertyDescriptor(object, exec, propertyName, descriptor);
 #else //QT_NO_PROPERTIES
     return false;
 #endif //QT_NO_PROPERTIES
 }
getOwnPropertyNames()
void QScript::QObjectDelegate::getOwnPropertyNames (QScriptObject * object, JSC::ExecState * exec, JSC::PropertyNameArray & propertyNames, JSC::EnumerationMode mode = JSC::ExcludeDontEnumProperties) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 1591 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data(), and QScript::QMetaObjectWrapperObject::Data::Data().
 {
 #ifndef QT_NO_PROPERTIES
     QObject *qobject = data->value;
     if (!qobject) {
         QString message = QString::fromLatin1("cannot get property names of deleted QObject");
         JSC::throwError(exec, JSC::GeneralError, message);
         return;
     }
     const QScriptEngine::QObjectWrapOptions &opt = data->options;
     const QMetaObject *meta = qobject->metaObject();
     {
         int i = (opt & QScriptEngine::ExcludeSuperClassProperties)
                     ? meta->propertyOffset() : 0;
         for ( ; i < meta->propertyCount(); ++i) {
             QMetaProperty prop = meta->property(i);
             if (isEnumerableMetaProperty(prop, meta, i)) {
                 QString name = QString::fromLatin1(prop.name());
                 propertyNames.add(JSC::Identifier(exec, name));
             }
         }
     }
     {
         QList<QByteArray> dpNames = qobject->dynamicPropertyNames();
         for (int i = 0; i < dpNames.size(); ++i) {
             QString name = QString::fromLatin1(dpNames.at(i));
             propertyNames.add(JSC::Identifier(exec, name));
         }
     }
     if (!(opt & QScriptEngine::SkipMethodsInEnumeration)) {
         int i = (opt & QScriptEngine::ExcludeSuperClassMethods)
                     ? meta->methodOffset() : 0;
         for ( ; i < meta->methodCount(); ++i) {
             QMetaMethod method = meta->method(i);
             if (hasMethodAccess(method, i, opt)) {
                 QMetaMethod method = meta->method(i);
                 QString sig = QString::fromLatin1(method.signature());
                 propertyNames.add(JSC::Identifier(exec, sig));
             }
         }
     }
     QScriptObjectDelegate::getOwnPropertyNames(object, exec, propertyNames, mode);
 #endif //QT_NO_PROPERTIES
 }
getOwnPropertySlot()
bool QScript::QObjectDelegate::getOwnPropertySlot (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::PropertySlot & slot) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 1194 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data(), and QScript::QMetaObjectWrapperObject::Data::Data().
 {
     //Note: this has to be kept in sync with getOwnPropertyDescriptor
 #ifndef QT_NO_PROPERTIES
     QByteArray name = convertToLatin1(propertyName.ustring());
     QObject *qobject = data->value;
     if (!qobject) {
         QString message = QString::fromLatin1("cannot access member `%0' of deleted QObject")
                           .arg(QString::fromLatin1(name));
         slot.setValue(JSC::throwError(exec, JSC::GeneralError, message));
         return true;
     }
     const QMetaObject *meta = qobject->metaObject();
     {
         QHash<QByteArray, JSC::JSValue>::const_iterator it = data->cachedMembers.constFind(name);
         if (it != data->cachedMembers.constEnd()) {
             if (GeneratePropertyFunctions && (meta->indexOfProperty(name) != -1))
                 slot.setGetterSlot(JSC::asObject(it.value()));
             else
                 slot.setValue(it.value());
             return true;
         }
     }
     const QScriptEngine::QObjectWrapOptions &opt = data->options;
     QScriptEnginePrivate *eng = scriptEngineFromExec(exec);
     int index = -1;
     if (name.contains('(')) {
         QByteArray normalized = QMetaObject::normalizedSignature(name);
         if (-1 != (index = meta->indexOfMethod(normalized))) {
             QMetaMethod method = meta->method(index);
             if (hasMethodAccess(method, index, opt)) {
                 if (!(opt & QScriptEngine::ExcludeSuperClassMethods)
                     || (index >= meta->methodOffset())) {
                     QtFunction *fun = new (exec)QtFunction(
                         object, index, /*maybeOverloaded=*/false,
                         &exec->globalData(), eng->originalGlobalObject()->functionStructure(),
                         propertyName);
                     slot.setValue(fun);
                     data->cachedMembers.insert(name, fun);
                     return true;
                 }
             }
         }
     }
     index = meta->indexOfProperty(name);
     if (index != -1) {
         QMetaProperty prop = meta->property(index);
         if (prop.isScriptable()) {
             if (!(opt & QScriptEngine::ExcludeSuperClassProperties)
                 || (index >= meta->propertyOffset())) {
                 if (GeneratePropertyFunctions) {
                     QtPropertyFunction *fun = new (exec)QtPropertyFunction(
                         meta, index, &exec->globalData(),
                         eng->originalGlobalObject()->functionStructure(),
                         propertyName);
                     data->cachedMembers.insert(name, fun);
                     slot.setGetterSlot(fun);
                 } else {
                     JSC::JSValue val;
                     if (!prop.isValid())
                         val = JSC::jsUndefined();
                     else
                         val = QScriptEnginePrivate::jscValueFromVariant(exec, prop.read(qobject));
                     slot.setValue(val);
                 }
                 return true;
             }
         }
     }
     index = qobject->dynamicPropertyNames().indexOf(name);
     if (index != -1) {
         JSC::JSValue val = QScriptEnginePrivate::jscValueFromVariant(exec, qobject->property(name));
         slot.setValue(val);
         return true;
     }
     const int offset = (opt & QScriptEngine::ExcludeSuperClassMethods)
                        ? meta->methodOffset() : 0;
     for (index = meta->methodCount() - 1; index >= offset; --index) {
         QMetaMethod method = meta->method(index);
         if (hasMethodAccess(method, index, opt)
             && methodNameEquals(method, name.constData(), name.length())) {
             QtFunction *fun = new (exec)QtFunction(
                 object, index, /*maybeOverloaded=*/true,
                 &exec->globalData(), eng->originalGlobalObject()->functionStructure(),
                 propertyName);
             slot.setValue(fun);
             data->cachedMembers.insert(name, fun);
             return true;
         }
     }
     if (!(opt & QScriptEngine::ExcludeChildObjects)) {
         QList<QObject*> children = qobject->children();
         for (index = 0; index < children.count(); ++index) {
             QObject *child = children.at(index);
             if (child->objectName() == QString(propertyName.ustring())) {
                 QScriptEngine::QObjectWrapOptions opt = QScriptEngine::PreferExistingWrapperObject;
                 slot.setValue(eng->newQObject(child, QScriptEngine::QtOwnership, opt));
                 return true;
             }
         }
     }
     return QScriptObjectDelegate::getOwnPropertySlot(object, exec, propertyName, slot);
 #else //QT_NO_PROPERTIES
     return false;
 #endif //QT_NO_PROPERTIES
 }
markChildren()
void QScript::QObjectDelegate::markChildren (QScriptObject * object, JSC::MarkStack & markStack) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 1642 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data(), QScript::QtFunction::Data::Data(), and QScript::QMetaObjectWrapperObject::Data::Data().
 {
     QHash<QByteArray, JSC::JSValue>::const_iterator it;
     for (it = data->cachedMembers.constBegin(); it != data->cachedMembers.constEnd(); ++it) {
         JSC::JSValue val = it.value();
         if (val)
             markStack.append(val);
     }
     QScriptObjectDelegate::markChildren(object, markStack);
 }
options()
QScriptEngine::QObjectWrapOptions QScript::QObjectDelegate::options () const inline
Definition at line 104 of file qscriptqobject_p.h.
         { return data->options; }
ownership()
QScriptEngine::ValueOwnership QScript::QObjectDelegate::ownership () const inline
Definition at line 99 of file qscriptqobject_p.h.
Referenced by QScript::QObjectConnection::mark().
         { return data->ownership; }
put()
void QScript::QObjectDelegate::put (QScriptObject * object, JSC::ExecState * exec, const JSC::Identifier & propertyName, JSC::JSValue value, JSC::PutPropertySlot & slot) virtual
Reimplemented from QScriptObjectDelegate.
Definition at line 1446 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data(), and QScript::QMetaObjectWrapperObject::Data::Data().
 {
 #ifndef QT_NO_PROPERTIES
     QByteArray name = convertToLatin1(propertyName.ustring());
     QObject *qobject = data->value;
     if (!qobject) {
         QString message = QString::fromLatin1("cannot access member `%0' of deleted QObject")
                           .arg(QString::fromLatin1(name));
         JSC::throwError(exec, JSC::GeneralError, message);
         return;
     }
     const QScriptEngine::QObjectWrapOptions &opt = data->options;
     const QMetaObject *meta = qobject->metaObject();
     QScriptEnginePrivate *eng = scriptEngineFromExec(exec);
     int index = -1;
     if (name.contains('(')) {
         QByteArray normalized = QMetaObject::normalizedSignature(name);
         if (-1 != (index = meta->indexOfMethod(normalized))) {
             QMetaMethod method = meta->method(index);
             if (hasMethodAccess(method, index, opt)) {
                 if (!(opt & QScriptEngine::ExcludeSuperClassMethods)
                     || (index >= meta->methodOffset())) {
                     data->cachedMembers.insert(name, value);
                     return;
                 }
             }
         }
     }
     index = meta->indexOfProperty(name);
     if (index != -1) {
         QMetaProperty prop = meta->property(index);
         if (prop.isScriptable()) {
             if (!(opt & QScriptEngine::ExcludeSuperClassProperties)
                 || (index >= meta->propertyOffset())) {
                 if (GeneratePropertyFunctions) {
                     // ### ideally JSC would do this for us already, i.e. find out
                     // that the property is a setter and call the setter.
                     // Maybe QtPropertyFunction needs to inherit JSC::GetterSetter.
                     JSC::JSValue fun;
                     QHash<QByteArray, JSC::JSValue>::const_iterator it;
                     it = data->cachedMembers.constFind(name);
                     if (it != data->cachedMembers.constEnd()) {
                         fun = it.value();
                     } else {
                         fun = new (exec)QtPropertyFunction(
                             meta, index, &exec->globalData(),
                             eng->originalGlobalObject()->functionStructure(),
                             propertyName);
                         data->cachedMembers.insert(name, fun);
                     }
                     JSC::CallData callData;
                     JSC::CallType callType = fun.getCallData(callData);
                     JSC::JSValue argv[1] = { value };
                     JSC::ArgList args(argv, 1);
                     (void)JSC::call(exec, fun, callType, callData, object, args);
                 } else {
                     QVariant v;
                     if (prop.isEnumType() && value.isString()
                         && !eng->hasDemarshalFunction(prop.userType())) {
                         // give QMetaProperty::write() a chance to convert from
                         // string to enum value
                         v = (QString)value.toString(exec);
                     } else {
                         v = QScriptEnginePrivate::jscValueToVariant(exec, value, prop.userType());
                     }
                     (void)prop.write(qobject, v);
                 }
                 return;
             }
         }
     }
     const int offset = (opt & QScriptEngine::ExcludeSuperClassMethods)
                        ? meta->methodOffset() : 0;
     for (index = meta->methodCount() - 1; index >= offset; --index) {
         QMetaMethod method = meta->method(index);
         if (hasMethodAccess(method, index, opt)
             && methodNameEquals(method, name.constData(), name.length())) {
             data->cachedMembers.insert(name, value);
             return;
         }
     }
     index = qobject->dynamicPropertyNames().indexOf(name);
     if ((index != -1) || (opt & QScriptEngine::AutoCreateDynamicProperties)) {
         QVariant v = QScriptEnginePrivate::toVariant(exec, value);
         (void)qobject->setProperty(name, v);
         return;
     }
     QScriptObjectDelegate::put(object, exec, propertyName, value, slot);
 #endif //QT_NO_PROPERTIES
 }
setOptions()
void QScript::QObjectDelegate::setOptions (QScriptEngine::QObjectWrapOptions options) inline
Definition at line 106 of file qscriptqobject_p.h.
Referenced by QScriptEngine::newQObject().
         { data->options = options; }
setOwnership()
void QScript::QObjectDelegate::setOwnership (QScriptEngine::ValueOwnership ownership) inline
Definition at line 101 of file qscriptqobject_p.h.
Referenced by QScript::QMetaObjectWrapperObject::execute(), and QScriptEngine::newQObject().
         { data->ownership = ownership; }
setValue()
void QScript::QObjectDelegate::setValue (QObject * value) inline
Definition at line 97 of file qscriptqobject_p.h.
Referenced by QScriptEngine::newQObject().
 { data->value = value; }
type()
QScriptObjectDelegate::Type QScript::QObjectDelegate::type () const virtual
Implements QScriptObjectDelegate.
Definition at line 1189 of file qscriptqobject.cpp.
Referenced by QScript::QObjectDelegate::Data::Data().
 {
     return QtObject;
 }
value()
QObject* QScript::QObjectDelegate::value () const inline
Definition at line 96 of file qscriptqobject_p.h.
Referenced by compareToObject(), QScript::QObjectConnection::mark(), QScript::qobjectProtoFuncFindChild(), QScript::qobjectProtoFuncFindChildren(), and QScript::qobjectProtoFuncToString().
 { return data->value; }
Properties
data
Data* QScript::QObjectDelegate::data protected
Definition at line 110 of file qscriptqobject_p.h.
Referenced by deleteProperty(), getOwnPropertyDescriptor(), getOwnPropertyNames(), getOwnPropertySlot(), markChildren(), options(), ownership(), put(), setOptions(), setOwnership(), setValue(), QScript::QMetaObjectWrapperObject::setValue(), value(), QScript::QMetaObjectWrapperObject::value(), and ~QObjectDelegate().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptqobject_p.h
/src/script/bridge/qscriptqobject.cpp