Qt 4.8: QDeclarativeRotationAnimation Class Reference
QDeclarativeRotationAnimation Class Reference
#include <qdeclarativeanimation_p.h>
Public Types
enum RotationDirection { Numerical, Shortest, Clockwise, Counterclockwise }
Public Types inherited from QDeclarativeAbstractAnimation
enum Loops { Infinite = -2 }
enum TransitionDirection { Forward, Backward }
Signals
void directionChanged ()
Signals inherited from QDeclarativePropertyAnimation
void durationChanged (int)
void easingChanged (const QEasingCurve &)
void fromChanged (QVariant)
void propertiesChanged (const QString &)
void propertyChanged ()
void targetChanged ()
void toChanged (QVariant)
Signals inherited from QDeclarativeAbstractAnimation
void alwaysRunToEndChanged (bool)
void completed ()
void loopCountChanged (int)
void pausedChanged (bool)
void runningChanged (bool)
void started ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
RotationDirection direction () const
qreal from () const
QDeclarativeRotationAnimation (QObject *parent=0)
void setDirection (RotationDirection direction)
void setFrom (qreal)
void setTo (qreal)
qreal to () const
virtual ~QDeclarativeRotationAnimation ()
Public Functions inherited from QDeclarativePropertyAnimation
virtual int duration () const
QEasingCurve easing () const
QDeclarativeListProperty< QObject > exclude ()
QVariant from () const
QString properties () const
QString property () const
QDeclarativePropertyAnimation (QObject *parent=0)
virtual void setDuration (int)
void setEasing (const QEasingCurve &)
void setFrom (const QVariant &)
void setProperties (const QString &)
void setProperty (const QString &)
void setTarget (QObject *)
void setTo (const QVariant &)
QObject * target () const
QDeclarativeListProperty< QObject > targets ()
QVariant to () const
virtual ~QDeclarativePropertyAnimation ()
Public Functions inherited from QDeclarativeAbstractAnimation
bool alwaysRunToEnd () const
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
int currentTime ()
QDeclarativeAnimationGroup * group () const
bool isPaused () const
bool isRunning () const
int loops () const
QDeclarativeAbstractAnimation (QObject *parent=0)
void setAlwaysRunToEnd (bool)
void setCurrentTime (int)
void setDefaultTarget (const QDeclarativeProperty &)
void setDisableUserControl ()
void setGroup (QDeclarativeAnimationGroup *)
void setLoops (int)
void setPaused (bool)
void setRunning (bool)
virtual ~QDeclarativeAbstractAnimation ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativePropertyValueSource
QDeclarativePropertyValueSource ()
Constructs a QDeclarativePropertyValueSource.
virtual ~QDeclarativePropertyValueSource ()
Destroys the value source.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Properties
RotationDirection direction
qreal from
qreal to
Additional Inherited Members
Public Slots inherited from QDeclarativeAbstractAnimation
void complete ()
void pause ()
void restart ()
void resume ()
void start ()
void stop ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QDeclarativePropertyAnimation
QDeclarativePropertyAnimation (QDeclarativePropertyAnimationPrivate &dd, QObject *parent)
virtual QAbstractAnimation * qtAnimation ()
virtual void transition (QDeclarativeStateActions &actions, QDeclarativeProperties &modified, TransitionDirection direction)
Protected Functions inherited from QDeclarativeAbstractAnimation
QDeclarativeAbstractAnimation (QDeclarativeAbstractAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 363 of file qdeclarativeanimation_p.h.
Enumerations
RotationDirection
enum QDeclarativeRotationAnimation::RotationDirection
Enumerator
Numerical
Shortest
Clockwise
Counterclockwise
Definition at line 383 of file qdeclarativeanimation_p.h.
 { Numerical, Shortest, Clockwise, Counterclockwise };
Constructors and Destructors
QDeclarativeRotationAnimation()
QDeclarativeRotationAnimation::QDeclarativeRotationAnimation (QObject * parent = 0)
Definition at line 1480 of file qdeclarativeanimation.cpp.
 : QDeclarativePropertyAnimation(*(new QDeclarativeRotationAnimationPrivate), parent)
 {
     Q_D(QDeclarativeRotationAnimation);
     d->interpolatorType = QMetaType::QReal;
     d->interpolator = QVariantAnimationPrivate::getInterpolator(d->interpolatorType);
     d->defaultProperties = QLatin1String("rotation,angle");
 }
~QDeclarativeRotationAnimation()
QDeclarativeRotationAnimation::~QDeclarativeRotationAnimation () virtual
Definition at line 1489 of file qdeclarativeanimation.cpp.
 {
 }
Functions
direction()
RotationDirection QDeclarativeRotationAnimation::direction () const
Referenced by setDirection(), and setTo().
directionChanged
void QDeclarativeRotationAnimation::directionChanged () signal
Referenced by setDirection().
from()
qreal QDeclarativeRotationAnimation::from () const
Referenced by ~QDeclarativeRotationAnimation().
setDirection()
void QDeclarativeRotationAnimation::setDirection (QDeclarativeRotationAnimation::RotationDirection direction)
Definition at line 1582 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeRotationAnimation);
     if (d->direction == direction)
         return;
     d->direction = direction;
     switch(d->direction) {
     case Clockwise:
         d->interpolator = reinterpret_cast<QVariantAnimation::Interpolator>(&_q_interpolateClockwiseRotation);
         break;
     case Counterclockwise:
         d->interpolator = reinterpret_cast<QVariantAnimation::Interpolator>(&_q_interpolateCounterclockwiseRotation);
         break;
     case Shortest:
         d->interpolator = reinterpret_cast<QVariantAnimation::Interpolator>(&_q_interpolateShortestRotation);
         break;
     default:
         d->interpolator = QVariantAnimationPrivate::getInterpolator(d->interpolatorType);
         break;
     }
     emit directionChanged();
 }
setFrom()
void QDeclarativeRotationAnimation::setFrom (qreal f)
Definition at line 1528 of file qdeclarativeanimation.cpp.
 {
     QDeclarativePropertyAnimation::setFrom(f);
 }
setTo()
void QDeclarativeRotationAnimation::setTo (qreal t)
Definition at line 1553 of file qdeclarativeanimation.cpp.
 {
     QDeclarativePropertyAnimation::setTo(t);
 }
to()
qreal QDeclarativeRotationAnimation::to () const
Referenced by setFrom().
Properties
direction
QDeclarativeRotationAnimation::RotationDirection QDeclarativeRotationAnimation::direction private
Definition at line 371 of file qdeclarativeanimation_p.h.
from
qreal QDeclarativeRotationAnimation::from private
Definition at line 369 of file qdeclarativeanimation_p.h.
to
qreal QDeclarativeRotationAnimation::to private
Definition at line 370 of file qdeclarativeanimation_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeanimation_p.h
/src/declarative/util/qdeclarativeanimation.cpp