Qt 4.8: QWindowsMime Class Reference
QWindowsMime Class Reference abstract
The QWindowsMime class maps open-standard MIME to Window Clipboard formats.
#include <qmime.h>
Public Functions
virtual bool canConvertFromMime (const FORMATETC &formatetc, const QMimeData *mimeData) const =0
Returns true if the converter can convert from the mimeData to the format specified in formatetc.
virtual bool canConvertToMime (const QString &mimeType, IDataObject *pDataObj) const =0
Returns true if the converter can convert to the mimeType from the available formats in pDataObj.
virtual bool convertFromMime (const FORMATETC &formatetc, const QMimeData *mimeData, STGMEDIUM *pmedium) const =0
Convert the mimeData to the format specified in formatetc.
virtual QVariant convertToMime (const QString &mimeType, IDataObject *pDataObj, QVariant::Type preferredType) const =0
Returns a QVariant containing the converted data for mimeType from pDataObj.
virtual QVector< FORMATETC > formatsForMime (const QString &mimeType, const QMimeData *mimeData) const =0
Returns a QVector of FORMATETC structures representing the different windows clipboard formats that can be provided for the mimeType from the mimeData.
virtual QString mimeForFormat (const FORMATETC &formatetc) const =0
Returns the mime type that will be created form the format specified in formatetc, or an empty string if this converter does not support formatetc.
QWindowsMime ()
Constructs a new conversion object, adding it to the globally accessed list of available converters.
virtual ~QWindowsMime ()
Destroys a conversion object, removing it from the global list of available converters.
Static Public Functions
static int registerMimeType (const QString &mime)
Registers the MIME type mime, and returns an ID number identifying the format on Windows.
Static Private Functions
static QVector< FORMATETC > allFormatsForMime (const QMimeData *mimeData)
static QStringList allMimesForFormats (IDataObject *pDataObj)
static QWindowsMime * converterFromMime (const FORMATETC &formatetc, const QMimeData *mimeData)
static QWindowsMime * converterToMime (const QString &mimeType, IDataObject *pDataObj)
Friends
class QClipboardWatcher
class QDragManager
class QDropData
class QOleDataObject
Detailed Description
The QWindowsMime class maps open-standard MIME to Window Clipboard formats.
Qt's drag-and-drop and clipboard facilities use the MIME standard. On X11, this maps trivially to the Xdnd protocol, but on Windows although some applications use MIME types to describe clipboard formats, others use arbitrary non-standardized naming conventions, or unnamed built-in formats of Windows.
By instantiating subclasses of QWindowsMime that provide conversions between Windows Clipboard and MIME formats, you can convert proprietary clipboard formats to MIME formats.
Qt has predefined support for the following Windows Clipboard formats:
Windows Format Equivalent MIME type
CF_UNICODETEXT text/plain
CF_TEXT text/plain
CF_DIB image/xyz, where xyz is a Qt image format
CF_HDROP text/uri-list
CF_INETURL text/uri-list
CF_HTML text/html
An example use of this class would be to map the Windows Metafile clipboard format (CF_METAFILEPICT) to and from the MIME type image/x-wmf. This conversion might simply be adding or removing a header, or even just passing on the data. See Drag and Drop for more information on choosing and definition MIME types.
You can check if a MIME type is convertible using canConvertFromMime() and can perform conversions with convertToMime() and convertFromMime().
Definition at line 79 of file qmime.h.
Constructors and Destructors
QWindowsMime()
QWindowsMime::QWindowsMime ()
Constructs a new conversion object, adding it to the globally accessed list of available converters.
Definition at line 264 of file qmime_win.cpp.
 {
     theMimeList()->addWindowsMime(this);
 }
~QWindowsMime()
QWindowsMime::~QWindowsMime () virtual
Destroys a conversion object, removing it from the global list of available converters.
Definition at line 273 of file qmime_win.cpp.
 {
     theMimeList()->removeWindowsMime(this);
 }
Functions
allFormatsForMime()
QVector< FORMATETC > QWindowsMime::allFormatsForMime (const QMimeData * mimeData) static private
Definition at line 375 of file qmime_win.cpp.
Referenced by QOleDataObject::EnumFormatEtc().
 {
     QList<QWindowsMime*> mimes = theMimeList()->windowsMimes();
     QVector<FORMATETC> formatics;
     formatics.reserve(20);
 #ifndef QT_NO_DRAGANDDROP
     QStringList formats = QInternalMimeData::formatsHelper(mimeData);
     for (int f=0; f<formats.size(); ++f) {
         for (int i=mimes.size()-1; i>=0; --i)
             formatics += mimes.at(i)->formatsForMime(formats.at(f), mimeData);
     }
 #else
     Q_UNUSED(mimeData);
 #endif //QT_NO_DRAGANDDROP
     return formatics;
 }
allMimesForFormats()
QStringList QWindowsMime::allMimesForFormats (IDataObject * pDataObj) static private
Definition at line 392 of file qmime_win.cpp.
Referenced by QOleDropTarget::Drop(), and QClipboardWatcher::formats_sys().
 {
     QList<QWindowsMime*> mimes = theMimeList()->windowsMimes();
     QStringList formats;
     LPENUMFORMATETC FAR fmtenum;
     HRESULT hr = pDataObj->EnumFormatEtc(DATADIR_GET, &fmtenum);
     if (hr == NOERROR) {
         FORMATETC fmtetc;
         while (S_OK == fmtenum->Next(1, &fmtetc, 0)) {
 #if defined(QMIME_DEBUG) && !defined(Q_OS_WINCE)
             qDebug("QWindowsMime::allMimesForFormats()");
             wchar_t buf[256] = {0};
             GetClipboardFormatName(fmtetc.cfFormat, buf, 255);
             qDebug("CF = %d : %s", fmtetc.cfFormat, QString::fromWCharArray(buf));
 #endif
             for (int i=mimes.size()-1; i>=0; --i) {
                 QString format = mimes.at(i)->mimeForFormat(fmtetc);
                 if (!format.isEmpty() && !formats.contains(format)) {
                     formats += format;
                 }
             }
             // as documented in MSDN to avoid possible memleak
             if (fmtetc.ptd)
                 CoTaskMemFree(fmtetc.ptd);
         }
         fmtenum->Release();
     }
     return formats;
 }
canConvertFromMime()
bool QWindowsMime::canConvertFromMime (const FORMATETC & formatetc, const QMimeData * mimeData) const pure virtual
Returns true if the converter can convert from the mimeData to the format specified in formatetc.
All subclasses must reimplement this pure virtual function.
Implemented in QLastResortMimes, QBuiltInMimes, QWindowsMimeImage, QWindowsMimeHtml, QWindowsMimeURI, and QWindowsMimeText.
Referenced by converterFromMime().
canConvertToMime()
bool QWindowsMime::canConvertToMime (const QString & mimeType, IDataObject * pDataObj) const pure virtual
Returns true if the converter can convert to the mimeType from the available formats in pDataObj.
All subclasses must reimplement this pure virtual function.
Implemented in QLastResortMimes, QBuiltInMimes, QWindowsMimeImage, QWindowsMimeHtml, QWindowsMimeURI, and QWindowsMimeText.
Referenced by converterToMime().
converterFromMime()
QWindowsMime * QWindowsMime::converterFromMime (const FORMATETC & formatetc, const QMimeData * mimeData) static private
Definition at line 355 of file qmime_win.cpp.
Referenced by QOleDataObject::GetData(), and QOleDataObject::QueryGetData().
 {
     QList<QWindowsMime*> mimes = theMimeList()->windowsMimes();
     for (int i=mimes.size()-1; i>=0; --i) {
         if (mimes.at(i)->canConvertFromMime(formatetc, mimeData))
             return mimes.at(i);
     }
     return 0;
 }
converterToMime()
QWindowsMime * QWindowsMime::converterToMime (const QString & mimeType, IDataObject * pDataObj) static private
Definition at line 365 of file qmime_win.cpp.
Referenced by QOleDropTarget::Drop(), QClipboardWatcher::hasFormat_sys(), and QClipboardWatcher::retrieveData_sys().
 {
     QList<QWindowsMime*> mimes = theMimeList()->windowsMimes();
     for (int i=mimes.size()-1; i>=0; --i) {
         if (mimes.at(i)->canConvertToMime(mimeType, pDataObj))
             return mimes.at(i);
     }
     return 0;
 }
convertFromMime()
bool QWindowsMime::convertFromMime (const FORMATETC & formatetc, const QMimeData * mimeData, STGMEDIUM * pmedium) const pure virtual
Convert the mimeData to the format specified in formatetc.
The converted data should then be placed in pmedium structure.
Return true if the conversion was successful.
All subclasses must reimplement this pure virtual function.
Implemented in QLastResortMimes, QBuiltInMimes, QWindowsMimeImage, QWindowsMimeHtml, QWindowsMimeURI, and QWindowsMimeText.
Referenced by QOleDataObject::GetData().
convertToMime()
QVariant QWindowsMime::convertToMime (const QString & mimeType, IDataObject * pDataObj, QVariant::Type preferredType) const pure virtual
Returns a QVariant containing the converted data for mimeType from pDataObj.
If possible the QVariant should be of the preferredType to avoid needless conversions.
All subclasses must reimplement this pure virtual function.
Implemented in QLastResortMimes, QBuiltInMimes, QWindowsMimeImage, and QWindowsMimeHtml.
Referenced by QOleDropTarget::Drop(), and QClipboardWatcher::retrieveData_sys().
formatsForMime()
QVector< FORMATETC > QWindowsMime::formatsForMime (const QString & mimeType, const QMimeData * mimeData) const pure virtual
Returns a QVector of FORMATETC structures representing the different windows clipboard formats that can be provided for the mimeType from the mimeData.
All subclasses must reimplement this pure virtual function.
Implemented in QLastResortMimes, QBuiltInMimes, QWindowsMimeImage, QWindowsMimeHtml, QWindowsMimeURI, and QWindowsMimeText.
Referenced by allFormatsForMime().
mimeForFormat()
QString QWindowsMime::mimeForFormat (const FORMATETC & formatetc) const pure virtual
Returns the mime type that will be created form the format specified in formatetc, or an empty string if this converter does not support formatetc.
All subclasses must reimplement this pure virtual function.
Implemented in QLastResortMimes, QBuiltInMimes, QWindowsMimeImage, QWindowsMimeHtml, QWindowsMimeURI, and QWindowsMimeText.
Referenced by allMimesForFormats().
registerMimeType()
int QWindowsMime::registerMimeType (const QString & mime) static
Registers the MIME type mime, and returns an ID number identifying the format on Windows.
Definition at line 283 of file qmime_win.cpp.
Referenced by QLastResortMimes::canConvertToMime(), QLastResortMimes::convertToMime(), QLastResortMimes::formatsForMime(), QBuiltInMimes::QBuiltInMimes(), QWindowsMimeHtml::QWindowsMimeHtml(), and QWindowsMimeURI::QWindowsMimeURI().
 {
     int f = RegisterClipboardFormat(reinterpret_cast<const wchar_t *> (mime.utf16()));
     if (!f)
         qErrnoWarning("QWindowsMime::registerMimeType: Failed to register clipboard format");
     return f;
 }
Friends and Related Functions
QClipboardWatcher
friend class QClipboardWatcher friend
Definition at line 98 of file qmime.h.
QDragManager
friend class QDragManager friend
Definition at line 99 of file qmime.h.
QDropData
friend class QDropData friend
Definition at line 100 of file qmime.h.
QOleDataObject
friend class QOleDataObject friend
Definition at line 101 of file qmime.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qmime.h
/src/gui/kernel/qmime_win.cpp