Qt 4.8: OutputPrivate Class Reference
OutputPrivate Class Reference
#include <qaudiooutput_alsa_p.h>
Public Functions
OutputPrivate (QAudioOutputPrivate *audio)
OutputPrivate (QAudioOutputPrivate *audio)
qint64 readData (char *data, qint64 len)
Reads up to maxSize bytes from the device into data, and returns the number of bytes read or -1 if an error occurred.
qint64 readData (char *data, qint64 len)
Reads up to maxSize bytes from the device into data, and returns the number of bytes read or -1 if an error occurred.
qint64 writeData (const char *data, qint64 len)
Writes up to maxSize bytes from data to the device.
qint64 writeData (const char *data, qint64 len)
Writes up to maxSize bytes from data to the device.
~OutputPrivate ()
~OutputPrivate ()
Public Functions inherited from QIODevice
virtual bool atEnd () const
Returns true if the current read and write position is at the end of the device (i.e.
virtual qint64 bytesAvailable () const
Returns the number of bytes that are available for reading.
virtual qint64 bytesToWrite () const
For buffered devices, this function returns the number of bytes waiting to be written.
virtual bool canReadLine () const
Returns true if a complete line of data can be read from the device; otherwise returns false.
virtual void close ()
First emits aboutToClose(), then closes the device and sets its OpenMode to NotOpen.
QString errorString () const
Returns a human-readable description of the last device error that occurred.
bool getChar (char *c)
Reads one character from the device and stores it in c.
bool isOpen () const
Returns true if the device is open; otherwise returns false.
bool isReadable () const
Returns true if data can be read from the device; otherwise returns false.
virtual bool isSequential () const
Returns true if this device is sequential; otherwise returns false.
bool isTextModeEnabled () const
Returns true if the Text flag is enabled; otherwise returns false.
bool isWritable () const
Returns true if data can be written to the device; otherwise returns false.
virtual bool open (OpenMode mode)
Opens the device and sets its OpenMode to mode.
OpenMode openMode () const
Returns the mode in which the device has been opened; i.e.
qint64 peek (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, without side effects (i.
QByteArray peek (qint64 maxlen)
Peeks at most maxSize bytes from the device, returning the data peeked as a QByteArray.
virtual qint64 pos () const
For random-access devices, this function returns the position that data is written to or read from.
bool putChar (char c)
Writes the character c to the device.
QIODevice ()
Constructs a QIODevice object.
QIODevice (QObject *parent)
Constructs a QIODevice object with the given parent.
qint64 read (char *data, qint64 maxlen)
Reads at most maxSize bytes from the device into data, and returns the number of bytes read.
QByteArray read (qint64 maxlen)
Reads at most maxSize bytes from the device, and returns the data read as a QByteArray.
QByteArray readAll ()
Reads all available data from the device, and returns it as a QByteArray.
qint64 readLine (char *data, qint64 maxlen)
This function reads a line of ASCII characters from the device, up to a maximum of maxSize - 1 bytes, stores the characters in data, and returns the number of bytes read.
QByteArray readLine (qint64 maxlen=0)
Reads a line from the device, but no more than maxSize characters, and returns the result as a QByteArray.
virtual bool reset ()
Seeks to the start of input for random-access devices.
virtual bool seek (qint64 pos)
For random-access devices, this function sets the current position to pos, returning true on success, or false if an error occurred.
void setTextModeEnabled (bool enabled)
If enabled is true, this function sets the Text flag on the device; otherwise the Text flag is removed.
virtual qint64 size () const
For open random-access devices, this function returns the size of the device.
void ungetChar (char c)
Puts the character c back into the device, and decrements the current position unless the position is 0.
virtual bool waitForBytesWritten (int msecs)
For buffered devices, this function waits until a payload of buffered written data has been written to the device and the bytesWritten() signal has been emitted, or until msecs milliseconds have passed.
virtual bool waitForReadyRead (int msecs)
Blocks until new data is available for reading and the readyRead() signal has been emitted, or until msecs milliseconds have passed.
qint64 write (const char *data, qint64 len)
Writes at most maxSize bytes of data from data to the device.
qint64 write (const char *data)
Writes data from a zero-terminated string of 8-bit characters to the device.
qint64 write (const QByteArray &data)
Writes the content of byteArray to the device.
virtual ~QIODevice ()
The destructor is virtual, and QIODevice is an abstract base class.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QAudioOutputPrivate * audioDevice
Friends
class QAudioOutputPrivate
Additional Inherited Members
Public Types inherited from QIODevice
enum OpenModeFlag {
NotOpen = 0x0000, ReadOnly = 0x0001, WriteOnly = 0x0002, ReadWrite = ReadOnly | WriteOnly,
Append = 0x0004, Truncate = 0x0008, Text = 0x0010, Unbuffered = 0x0020
}
This enum is used with open() to describe the mode in which a device is opened.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QIODevice
void aboutToClose ()
This signal is emitted when the device is about to close.
void bytesWritten (qint64 bytes)
This signal is emitted every time a payload of data has been written to the device.
void readChannelFinished ()
This signal is emitted when the input (reading) stream is closed in this device.
void readyRead ()
This signal is emitted once every time new data is available for reading from the device.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QIODevice
QIODevice (QIODevicePrivate &dd, QObject *parent=0)
virtual qint64 readLineData (char *data, qint64 maxlen)
Reads up to maxSize characters into data and returns the number of characters read.
void setErrorString (const QString &errorString)
Sets the human readable description of the last device error that occurred to str.
void setOpenMode (OpenMode openMode)
Sets the OpenMode of the device to openMode.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 149 of file qaudiooutput_alsa_p.h.
Constructors and Destructors
OutputPrivate() [1/2]
OutputPrivate::OutputPrivate (QAudioOutputPrivate * audio)
Definition at line 757 of file qaudiooutput_alsa_p.cpp.
Referenced by QAudioOutputPrivate::freeBlocks().
 {
     audioDevice = qobject_cast<QAudioOutputPrivate*>(audio);
 }
~OutputPrivate() [1/2]
OutputPrivate::~OutputPrivate ()
Definition at line 762 of file qaudiooutput_alsa_p.cpp.
Referenced by QAudioOutputPrivate::freeBlocks().
 {}
OutputPrivate() [2/2]
OutputPrivate::OutputPrivate (QAudioOutputPrivate * audio)
~OutputPrivate() [2/2]
OutputPrivate::~OutputPrivate ()
Functions
readData() [1/2]
qint64 OutputPrivate::readData (char * data, qint64 maxSize) virtual
Reads up to maxSize bytes from the device into data, and returns the number of bytes read or -1 if an error occurred.
If there are no bytes to be read and there can never be more bytes available (examples include socket closed, pipe closed, sub-process finished), this function returns -1.
This function is called by QIODevice. Reimplement this function when creating a subclass of QIODevice.
When reimplementing this function it is important that this function reads all the required data before returning. This is required in order for QDataStream to be able to operate on the class. QDataStream assumes all the requested information was read and therefore does not retry reading if there was a problem.
See also
read() readLine() writeData()
Implements QIODevice.
readData() [2/2]
qint64 OutputPrivate::readData (char * data, qint64 maxSize) virtual
Reads up to maxSize bytes from the device into data, and returns the number of bytes read or -1 if an error occurred.
If there are no bytes to be read and there can never be more bytes available (examples include socket closed, pipe closed, sub-process finished), this function returns -1.
This function is called by QIODevice. Reimplement this function when creating a subclass of QIODevice.
When reimplementing this function it is important that this function reads all the required data before returning. This is required in order for QDataStream to be able to operate on the class. QDataStream assumes all the requested information was read and therefore does not retry reading if there was a problem.
See also
read() readLine() writeData()
Implements QIODevice.
Definition at line 764 of file qaudiooutput_alsa_p.cpp.
Referenced by QAudioOutputPrivate::freeBlocks().
 {
     Q_UNUSED(data)
     Q_UNUSED(len)
     return 0;
 }
writeData() [1/2]
qint64 OutputPrivate::writeData (const char * data, qint64 maxSize) virtual
Writes up to maxSize bytes from data to the device.
Returns the number of bytes written, or -1 if an error occurred.
This function is called by QIODevice. Reimplement this function when creating a subclass of QIODevice.
When reimplementing this function it is important that this function writes all the data available before returning. This is required in order for QDataStream to be able to operate on the class. QDataStream assumes all the information was written and therefore does not retry writing if there was a problem.
See also
read() write()
Implements QIODevice.
writeData() [2/2]
qint64 OutputPrivate::writeData (const char * data, qint64 maxSize) virtual
Writes up to maxSize bytes from data to the device.
Returns the number of bytes written, or -1 if an error occurred.
This function is called by QIODevice. Reimplement this function when creating a subclass of QIODevice.
When reimplementing this function it is important that this function writes all the data available before returning. This is required in order for QDataStream to be able to operate on the class. QDataStream assumes all the information was written and therefore does not retry writing if there was a problem.
See also
read() write()
Implements QIODevice.
Definition at line 772 of file qaudiooutput_alsa_p.cpp.
Referenced by QAudioOutputPrivate::freeBlocks().
 {
     int retry = 0;
     qint64 written = 0;
     if((audioDevice->deviceState == QAudio::ActiveState)
             ||(audioDevice->deviceState == QAudio::IdleState)) {
         while(written < len) {
             int chunk = audioDevice->write(data+written,(len-written));
             if(chunk <= 0)
                 retry++;
             written+=chunk;
             if(retry > 10)
                 return written;
         }
     }
     return written;
 }
Friends and Related Functions
QAudioOutputPrivate
friend class QAudioOutputPrivate friend
Definition at line 151 of file qaudiooutput_alsa_p.h.
Properties
audioDevice
QAudioOutputPrivate * OutputPrivate::audioDevice private
Definition at line 161 of file qaudiooutput_alsa_p.h.
The documentation for this class was generated from the following files:
/src/multimedia/audio/qaudiooutput_alsa_p.h
/src/multimedia/audio/qaudiooutput_win32_p.h
/src/multimedia/audio/qaudiooutput_alsa_p.cpp
/src/multimedia/audio/qaudiooutput_win32_p.cpp