Qt 4.8: QFont Class Reference
QFont Class Reference
The QFont class specifies a font used for drawing text.
#include <qfont.h>
Public Types
enum Capitalization {
MixedCase, AllUppercase, AllLowercase, SmallCaps,
Capitalize
}
Rendering option for text this font applies to.
enum HintingPreference { PreferDefaultHinting = 0, PreferNoHinting = 1, PreferVerticalHinting = 2, PreferFullHinting = 3 }
This enum describes the different levels of hinting that can be applied to glyphs to improve legibility on displays where it might be warranted by the density of pixels.
enum ResolveProperties {
FamilyResolved = 0x0001, SizeResolved = 0x0002, StyleHintResolved = 0x0004, StyleStrategyResolved = 0x0008,
WeightResolved = 0x0010, StyleResolved = 0x0020, UnderlineResolved = 0x0040, OverlineResolved = 0x0080,
StrikeOutResolved = 0x0100, FixedPitchResolved = 0x0200, StretchResolved = 0x0400, KerningResolved = 0x0800,
CapitalizationResolved = 0x1000, LetterSpacingResolved = 0x2000, WordSpacingResolved = 0x4000, HintingPreferenceResolved = 0x8000,
StyleNameResolved = 0x10000, AllPropertiesResolved = 0x1ffff
}
This enum describes the properties of a QFont that can be set on a font individually and then considered resolved.
enum SpacingType { PercentageSpacing, AbsoluteSpacing }
enum Stretch {
UltraCondensed = 50, ExtraCondensed = 62, Condensed = 75, SemiCondensed = 87,
Unstretched = 100, SemiExpanded = 112, Expanded = 125, ExtraExpanded = 150,
UltraExpanded = 200
}
Predefined stretch values that follow the CSS naming convention.
enum Style { StyleNormal, StyleItalic, StyleOblique }
This enum describes the different styles of glyphs that are used to display text.
enum StyleHint {
Helvetica, SansSerif = Helvetica, Times, Serif = Times,
Courier, TypeWriter = Courier, OldEnglish, Decorative = OldEnglish,
System, AnyStyle, Cursive, Monospace,
Fantasy
}
Style hints are used by the font matching algorithm to find an appropriate default family if a selected font family is not available.
enum StyleStrategy {
PreferDefault = 0x0001, PreferBitmap = 0x0002, PreferDevice = 0x0004, PreferOutline = 0x0008,
ForceOutline = 0x0010, PreferMatch = 0x0020, PreferQuality = 0x0040, PreferAntialias = 0x0080,
NoAntialias = 0x0100, OpenGLCompatible = 0x0200, ForceIntegerMetrics = 0x0400, NoFontMerging = 0x8000
}
The style strategy tells the font matching algorithm what type of fonts should be used to find an appropriate default family.
enum Weight {
Light = 25, Normal = 50, DemiBold = 63, Bold = 75,
Black = 87
}
Qt uses a weighting scale from 0 to 99 similar to, but not the same as, the scales used in Windows or CSS.
Public Functions
bool bold () const
Returns true if weight() is a value greater than QFont::Normal ; otherwise returns false.
Capitalization capitalization () const
Returns the current capitalization type of the font.
QString defaultFamily () const
Returns the family name that corresponds to the current style hint.
bool exactMatch () const
Returns true if a window system font exactly matching the settings of this font is available.
QString family () const
Returns the requested font family name, i.e.
bool fixedPitch () const
Returns true if fixed pitch has been set; otherwise returns false.
FT_Face freetypeFace () const
Returns the handle to the primary FreeType face of the font.
bool fromString (const QString &)
Sets this font to match the description descrip.
HFONT handle () const
Returns the window system handle to the font, for low-level access.
HintingPreference hintingPreference () const
Returns the currently preferred hinting level for glyphs rendered with this font.
bool isCopyOf (const QFont &) const
Returns true if this font and f are copies of each other, i.e.
bool italic () const
Returns true if the style() of the font is not QFont::StyleNormal.
bool kerning () const
Returns true if kerning should be used when drawing text with this font.
QString key () const
Returns the font's key, a textual representation of a font.
QString lastResortFamily () const
Returns the "last resort" font family name.
QString lastResortFont () const
Returns a "last resort" font name for the font matching algorithm.
qreal letterSpacing () const
Returns the letter spacing for the font.
SpacingType letterSpacingType () const
Returns the spacing type used for letter spacing.
quint32 macFontID () const
Returns an ATSUFontID.
operator QVariant () const
Returns the font as a QVariant.
bool operator!= (const QFont &) const
Returns true if this font is different from f; otherwise returns false.
bool operator< (const QFont &) const
Provides an arbitrary comparison of this font and font f.
QFont & operator= (const QFont &)
Assigns font to this font and returns a reference to it.
bool operator== (const QFont &) const
Returns true if this font is equal to f; otherwise returns false.
bool overline () const
Returns true if overline has been set; otherwise returns false.
int pixelSize () const
Returns the pixel size of the font if it was set with setPixelSize().
int pointSize () const
Returns the point size of the font.
qreal pointSizeF () const
Returns the point size of the font.
QFont ()
Constructs a font object that uses the application's default font.
QFont (const QString &family, int pointSize=-1, int weight=-1, bool italic=false)
Constructs a font object with the specified family, pointSize, weight and italic settings.
QFont (const QFont &, QPaintDevice *pd)
Constructs a font from font for use on the paint device pd.
QFont (const QFont &)
Constructs a font that is a copy of font.
bool rawMode () const
Returns true if raw mode is used for font name matching; otherwise returns false.
QString rawName () const
Returns the name of the font within the underlying window system.
QFont resolve (const QFont &) const
Returns a new QFont that has attributes copied from other that have not been previously set on this font.
uint resolve () const
void resolve (uint mask)
void setBold (bool)
If enable is true sets the font's weight to QFont::Bold ; otherwise sets the weight to QFont::Normal.
void setCapitalization (Capitalization)
Sets the capitalization of the text in this font to caps.
void setFamily (const QString &)
Sets the family name of the font.
void setFixedPitch (bool)
If enable is true, sets fixed pitch on; otherwise sets fixed pitch off.
void setHintingPreference (HintingPreference hintingPreference)
Set the preference for the hinting level of the glyphs to hintingPreference.
void setItalic (bool b)
Sets the style() of the font to QFont::StyleItalic if enable is true; otherwise the style is set to QFont::StyleNormal.
void setKerning (bool)
Enables kerning for this font if enable is true; otherwise disables it.
void setLetterSpacing (SpacingType type, qreal spacing)
Sets the letter spacing for the font to spacing and the type of spacing to type.
void setOverline (bool)
If enable is true, sets overline on; otherwise sets overline off.
void setPixelSize (int)
Sets the font size to pixelSize pixels.
void setPointSize (int)
Sets the point size to pointSize.
void setPointSizeF (qreal)
Sets the point size to pointSize.
void setRawMode (bool)
If enable is true, turns raw mode on; otherwise turns raw mode off.
void setRawName (const QString &)
Sets a font by its system specific name.
void setStretch (int)
Sets the stretch factor for the font.
void setStrikeOut (bool)
If enable is true, sets strikeout on; otherwise sets strikeout off.
void setStyle (Style style)
Sets the style of the font to style.
void setStyleHint (StyleHint, StyleStrategy=PreferDefault)
Sets the style hint and strategy to hint and strategy, respectively.
void setStyleName (const QString &)
Sets the style name of the font to the given styleName.
void setStyleStrategy (StyleStrategy s)
Sets the style strategy for the font to s.
void setUnderline (bool)
If enable is true, sets underline on; otherwise sets underline off.
void setWeight (int)
Sets the weight the font to weight, which should be a value from the QFont::Weight enumeration.
void setWordSpacing (qreal spacing)
Sets the word spacing for the font to spacing.
int stretch () const
Returns the stretch factor for the font.
bool strikeOut () const
Returns true if strikeout has been set; otherwise returns false.
Style style () const
Returns the style of the font.
StyleHint styleHint () const
Returns the StyleHint.
QString styleName () const
Returns the requested font style name, it will be used to match the font with irregular styles (that can't be normalized in other style properties).
StyleStrategy styleStrategy () const
Returns the StyleStrategy.
QString toString () const
Returns a description of the font.
bool underline () const
Returns true if underline has been set; otherwise returns false.
int weight () const
Returns the weight of the font which is one of the enumerated values from QFont::Weight.
qreal wordSpacing () const
Returns the word spacing for the font.
~QFont ()
Destroys the font object and frees all allocated resources.
Static Public Functions
static void cleanup ()
Internal function that cleans up the font system.
static void initialize ()
Internal function that initializes the font system.
static void insertSubstitution (const QString &, const QString &)
Inserts substituteName into the substitution table for the family familyName.
static void insertSubstitutions (const QString &, const QStringList &)
Inserts the list of families substituteNames into the substitution list for familyName.
static void removeSubstitution (const QString &)
Removes all the substitutions for familyName.
static QString substitute (const QString &)
Returns the first family name to be used whenever familyName is specified.
static QStringList substitutes (const QString &)
Returns a list of family names to be used whenever familyName is specified.
static QStringList substitutions ()
Returns a sorted list of substituted family names.
Private Functions
void detach ()
Detaches the font object from common font data.
void macSetFont (QPaintDevice *)
QFont (QFontPrivate *)
Properties
QExplicitlySharedDataPointer< QFontPrivate > d
uint resolve_mask
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QFont &)
Writes the font font to the data stream s.
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QFont &)
Reads the font font from the data stream s.
class Q3TextFormatCollection
class QAlphaPaintEngine
class QApplication
class QCommandLinkButtonPrivate
class QFontDialogPrivate
class QFontEngine
class QFontInfo
class QFontMetrics
class QFontMetricsF
class QFontPrivate
class QGLContext
class QPaintBufferEngine
class QPainter
class QPainterPath
class QPainterPrivate
class QPainterReplayer
class QPicturePaintEngine
class QPSPrintEngineFont
struct QScriptLine
class QStackTextEngine
class QTextEngine
class QTextItemInt
class QTextLayout
class QTextLine
class QWidget
class QWidgetPrivate
class QWin32PaintEngine
Detailed Description
The QFont class specifies a font used for drawing text.
Note
This class or function is reentrant.
When you create a QFont object you specify various attributes that you want the font to have. Qt will use the font with the specified attributes, or if no matching font exists, Qt will use the closest matching installed font. The attributes of the font that is actually used are retrievable from a QFontInfo object. If the window system provides an exact match exactMatch() returns true. Use QFontMetrics to get measurements, e.g. the pixel length of a string using QFontMetrics::width().
Note that a QApplication instance must exist before a QFont can be used. You can set the application's default font with QApplication::setFont().
If a chosen font does not include all the characters that need to be displayed, QFont will try to find the characters in the nearest equivalent fonts. When a QPainter draws a character from a font the QFont will report whether or not it has the character; if it does not, QPainter will draw an unfilled square.
Create QFonts like this:
QFont serifFont("Times", 10, QFont::Bold);
QFont sansFont("Helvetica [Cronyx]", 12);
The attributes set in the constructor can also be set later, e.g. setFamily(), setPointSize(), setPointSizeFloat(), setWeight() and setItalic(). The remaining attributes must be set after contstruction, e.g. setBold(), setUnderline(), setOverline(), setStrikeOut() and setFixedPitch(). QFontInfo objects should be created after the font's attributes have been set. A QFontInfo object will not change, even if you change the font's attributes. The corresponding "get" functions, e.g. family(), pointSize(), etc., return the values that were set, even though the values used may differ. The actual values are available from a QFontInfo object.
If the requested font family is unavailable you can influence the font matching algorithm by choosing a particular QFont::StyleHint and QFont::StyleStrategy with setStyleHint(). The default family (corresponding to the current style hint) is returned by defaultFamily().
The font-matching algorithm has a lastResortFamily() and lastResortFont() in cases where a suitable match cannot be found. You can provide substitutions for font family names using insertSubstitution() and insertSubstitutions(). Substitutions can be removed with removeSubstitution(). Use substitute() to retrieve a family's first substitute, or the family name itself if it has no substitutes. Use substitutes() to retrieve a list of a family's substitutes (which may be empty).
Every QFont has a key() which you can use, for example, as the key in a cache or dictionary. If you want to store a user's font preferences you could use QSettings, writing the font information with toString() and reading it back with fromString(). The operator<<() and operator>>() functions are also available, but they work on a data stream.
It is possible to set the height of characters shown on the screen to a specified number of pixels with setPixelSize(); however using setPointSize() has a similar effect and provides device independence.
In X11 you can set a font using its system specific name with setRawName().
Loading fonts can be expensive, especially on X11. QFont contains extensive optimizations to make the copying of QFont objects fast, and to cache the results of the slow window system functions it depends upon.
The font matching algorithm works as follows:
The specified font family is searched for.
If not found, the styleHint() is used to select a replacement family.
Each replacement font family is searched for.
If none of these are found or there was no styleHint(), "helvetica" will be searched for.
If "helvetica" isn't found Qt will try the lastResortFamily().
If the lastResortFamily() isn't found Qt will try the lastResortFont() which will always return a name of some kind.
Note that the actual font matching algorithm varies from platform to platform.
In Windows a request for the "Courier" font is automatically changed to "Courier New", an improved version of Courier that allows for smooth scaling. The older "Courier" bitmap font can be selected by setting the PreferBitmap style strategy (see setStyleStrategy()).
Once a font is found, the remaining attributes are matched in order of priority:
fixedPitch()
pointSize() (see below)
weight()
style()
If you have a font which matches on family, even if none of the other attributes match, this font will be chosen in preference to a font which doesn't match on family but which does match on the other attributes. This is because font family is the dominant search criteria.
The point size is defined to match if it is within 20% of the requested point size. When several fonts match and are only distinguished by point size, the font with the closest point size to the one requested will be chosen.
The actual family, font size, weight and other font attributes used for drawing text will depend on what's available for the chosen family under the window system. A QFontInfo object can be used to determine the actual values used for drawing the text.
Examples:
QFont f("Helvetica");
If you had both an Adobe and a Cronyx Helvetica, you might get either.
QFont f("Helvetica [Cronyx]");
You can specify the foundry you want in the family name. The font f in the above example will be set to "Helvetica [Cronyx]".
To determine the attributes of the font actually used in the window system, use a QFontInfo object, e.g.
QFontInfo info(f1);
QString family = info.family();
To find out font metrics use a QFontMetrics object, e.g.
QFontMetrics fm(f1);
int textWidthInPixels = fm.width("How many pixels wide is this text?");
int textHeightInPixels = fm.height();
For more general information on fonts, see the http://nwalsh.com/comp.fonts/FAQ/ . Information on encodings can be found from http://czyborra.com/ Roman Czyborra's page.
See also
QFontComboBox, QFontMetrics, QFontInfo, QFontDatabase, {Character Map Example}
Definition at line 64 of file qfont.h.
Enumerations
Capitalization
enum QFont::Capitalization
Rendering option for text this font applies to.
Since
4.4
MixedCase This is the normal text rendering option where no capitalization change is applied.
AllUppercase This alters the text to be rendered in all uppercase type.
AllLowercase This alters the text to be rendered in all lowercase type.
SmallCaps This alters the text to be rendered in small-caps type.
Capitalize This alters the text to be rendered with the first character of each word as an uppercase character.
Enumerator
MixedCase
AllUppercase
AllLowercase
SmallCaps
Capitalize
Definition at line 129 of file qfont.h.
{
         MixedCase,
         AllUppercase,
         AllLowercase,
         SmallCaps,
         Capitalize
     };
HintingPreference
enum QFont::HintingPreference
This enum describes the different levels of hinting that can be applied to glyphs to improve legibility on displays where it might be warranted by the density of pixels.
Since
4.8
PreferDefaultHinting Use the default hinting level for the target platform.
PreferNoHinting If possible, render text without hinting the outlines of the glyphs. The text layout will be typographically accurate and scalable, using the same metrics as are used e.g. when printing.
PreferVerticalHinting If possible, render text with no horizontal hinting, but align glyphs to the pixel grid in the vertical direction. The text will appear crisper on displays where the density is too low to give an accurate rendering of the glyphs. But since the horizontal metrics of the glyphs are unhinted, the text's layout will be scalable to higher density devices (such as printers) without impacting details such as line breaks.
PreferFullHinting If possible, render text with hinting in both horizontal and vertical directions. The text will be altered to optimize legibility on the target device, but since the metrics will depend on the target size of the text, the positions of glyphs, line breaks, and other typographical detail will not scale, meaning that a text layout may look different on devices with different pixel densities.
Please note that this enum only describes a preference, as the full range of hinting levels are not supported on all of Qt's supported platforms. The following table details the effect of a given hinting preference on a selected set of target platforms.
PreferDefaultHinting PreferNoHinting PreferVerticalHinting PreferFullHinting
Windows Vista (w/o Platform Update) and earlier Full hinting Full hinting Full hinting Full hinting
Windows 7 and Windows Vista (w/Platform Update) and DirectWrite enabled in Qt Full hinting Vertical hinting Vertical hinting Full hinting
FreeType Operating System setting No hinting Vertical hinting (light) Full hinting
Cocoa on Mac OS X No hinting No hinting No hinting No hinting
Note
Please be aware that altering the hinting preference on Windows is available through the DirectWrite font engine. This is available on Windows Vista after installing the platform update, and on Windows 7. In order to use this extension, configure Qt using -directwrite. The target application will then depend on the availability of DirectWrite on the target system.
Enumerator
PreferDefaultHinting
PreferNoHinting
PreferVerticalHinting
PreferFullHinting
Definition at line 96 of file qfont.h.
{
         PreferDefaultHinting        = 0,
         PreferNoHinting             = 1,
         PreferVerticalHinting       = 2,
         PreferFullHinting           = 3
     };
ResolveProperties
enum QFont::ResolveProperties
This enum describes the properties of a QFont that can be set on a font individually and then considered resolved.
Warning
This function is not part of the public interface.
FamilyResolved
SizeResolved
StyleHintResolved
StyleStrategyResolved
WeightResolved
StyleResolved
UnderlineResolved
OverlineResolved
StrikeOutResolved
FixedPitchResolved
StretchResolved
KerningResolved
CapitalizationResolved
LetterSpacingResolved
WordSpacingResolved
CompletelyResolved
Enumerator
FamilyResolved
SizeResolved
StyleHintResolved
StyleStrategyResolved
WeightResolved
StyleResolved
UnderlineResolved
OverlineResolved
StrikeOutResolved
FixedPitchResolved
StretchResolved
KerningResolved
CapitalizationResolved
LetterSpacingResolved
WordSpacingResolved
HintingPreferenceResolved
StyleNameResolved
AllPropertiesResolved
Definition at line 142 of file qfont.h.
{
         FamilyResolved              = 0x0001,
         SizeResolved                = 0x0002,
         StyleHintResolved           = 0x0004,
         StyleStrategyResolved       = 0x0008,
         WeightResolved              = 0x0010,
         StyleResolved               = 0x0020,
         UnderlineResolved           = 0x0040,
         OverlineResolved            = 0x0080,
         StrikeOutResolved           = 0x0100,
         FixedPitchResolved          = 0x0200,
         StretchResolved             = 0x0400,
         KerningResolved             = 0x0800,
         CapitalizationResolved      = 0x1000,
         LetterSpacingResolved       = 0x2000,
         WordSpacingResolved         = 0x4000,
         HintingPreferenceResolved   = 0x8000,
         StyleNameResolved           = 0x10000,
         AllPropertiesResolved       = 0x1ffff
     };
SpacingType
enum QFont::SpacingType
Since
4.4
PercentageSpacing A value of 100 will keep the spacing unchanged; a value of 200 will enlarge the spacing after a character by the width of the character itself.
AbsoluteSpacing A positive value increases the letter spacing by the corresponding pixels; a negative value decreases the spacing.
Enumerator
PercentageSpacing
AbsoluteSpacing
Definition at line 137 of file qfont.h.
                      {
         PercentageSpacing,
         AbsoluteSpacing
     };
Stretch
enum QFont::Stretch
Predefined stretch values that follow the CSS naming convention.
The higher the value, the more stretched the text is.
UltraCondensed 50
ExtraCondensed 62
Condensed 75
SemiCondensed 87
Unstretched 100
SemiExpanded 112
Expanded 125
ExtraExpanded 150
UltraExpanded 200
See also
setStretch() stretch()
Enumerator
UltraCondensed
ExtraCondensed
Condensed
SemiCondensed
Unstretched
SemiExpanded
Expanded
ExtraExpanded
UltraExpanded
Definition at line 117 of file qfont.h.
                  {
         UltraCondensed =  50,
         ExtraCondensed =  62,
         Condensed      =  75,
         SemiCondensed  =  87,
         Unstretched    = 100,
         SemiExpanded   = 112,
         Expanded       = 125,
         ExtraExpanded  = 150,
         UltraExpanded  = 200
     };
Style
enum QFont::Style
This enum describes the different styles of glyphs that are used to display text.
StyleNormal Normal glyphs used in unstyled text.
StyleItalic Italic glyphs that are specifically designed for the purpose of representing italicized text.
StyleOblique Glyphs with an italic appearance that are typically based on the unstyled glyphs, but are not fine-tuned for the purpose of representing italicized text.
See also
Weight
Enumerator
StyleNormal
StyleItalic
StyleOblique
Definition at line 111 of file qfont.h.
                {
         StyleNormal,
         StyleItalic,
         StyleOblique
     };
StyleHint
enum QFont::StyleHint
Style hints are used by the font matching algorithm to find an appropriate default family if a selected font family is not available.
AnyStyle leaves the font matching algorithm to choose the family. This is the default.
SansSerif the font matcher prefer sans serif fonts.
Helvetica is a synonym for SansSerif.
Serif the font matcher prefers serif fonts.
Times is a synonym for Serif.
TypeWriter the font matcher prefers fixed pitch fonts.
Courier a synonym for TypeWriter.
OldEnglish the font matcher prefers decorative fonts.
Decorative is a synonym for OldEnglish.
Monospace the font matcher prefers fonts that map to the CSS generic font-family 'monospace'.
Fantasy the font matcher prefers fonts that map to the CSS generic font-family 'fantasy'.
Cursive the font matcher prefers fonts that map to the CSS generic font-family 'cursive'.
System the font matcher prefers system fonts.
Enumerator
Helvetica
SansSerif
Times
Serif
Courier
TypeWriter
OldEnglish
Decorative
System
AnyStyle
Cursive
Monospace
Fantasy
Definition at line 69 of file qfont.h.
                    {
         Helvetica,  SansSerif = Helvetica,
         Times,      Serif = Times,
         Courier,    TypeWriter = Courier,
         OldEnglish, Decorative = OldEnglish,
         System,
         AnyStyle,
         Cursive,
         Monospace,
         Fantasy
     };
StyleStrategy
enum QFont::StyleStrategy
The style strategy tells the font matching algorithm what type of fonts should be used to find an appropriate default family.
The following strategies are available:
PreferDefault the default style strategy. It does not prefer any type of font.
PreferBitmap prefers bitmap fonts (as opposed to outline fonts).
PreferDevice prefers device fonts.
PreferOutline prefers outline fonts (as opposed to bitmap fonts).
ForceOutline forces the use of outline fonts.
NoAntialias don't antialias the fonts.
PreferAntialias antialias if possible.
OpenGLCompatible forces the use of OpenGL compatible fonts.
NoFontMerging If the font selected for a certain writing system does not contain a character requested to draw, then Qt automatically chooses a similar looking font that contains the character. The NoFontMerging flag disables this feature. Please note that enabling this flag will not prevent Qt from automatically picking a suitable font when the selected font does not support the writing system of the text.
Any of these may be OR-ed with one of these flags:
PreferMatch prefer an exact match. The font matcher will try to use the exact font size that has been specified.
PreferQuality prefer the best quality font. The font matcher will use the nearest standard point size that the font supports.
ForceIntegerMetrics forces the use of integer values in font engines that support fractional font metrics.
Enumerator
PreferDefault
PreferBitmap
PreferDevice
PreferOutline
ForceOutline
PreferMatch
PreferQuality
PreferAntialias
NoAntialias
OpenGLCompatible
ForceIntegerMetrics
NoFontMerging
Definition at line 81 of file qfont.h.
{
         PreferDefault       = 0x0001,
         PreferBitmap        = 0x0002,
         PreferDevice        = 0x0004,
         PreferOutline       = 0x0008,
         ForceOutline        = 0x0010,
         PreferMatch         = 0x0020,
         PreferQuality       = 0x0040,
         PreferAntialias     = 0x0080,
         NoAntialias         = 0x0100,
         OpenGLCompatible    = 0x0200,
         ForceIntegerMetrics = 0x0400,
         NoFontMerging       = 0x8000
     };
Weight
enum QFont::Weight
Qt uses a weighting scale from 0 to 99 similar to, but not the same as, the scales used in Windows or CSS.
A weight of 0 is ultralight, whilst 99 will be an extremely black.
This enum contains the predefined font weights:
Light 25
Normal 50
DemiBold 63
Bold 75
Black 87
Enumerator
Light
Normal
DemiBold
Bold
Black
Definition at line 103 of file qfont.h.
                 {
         Light    = 25,
         Normal   = 50,
         DemiBold = 63,
         Bold     = 75,
         Black    = 87
     };
Constructors and Destructors
QFont() [1/5]
QFont::QFont ()
Constructs a font object that uses the application's default font.
See also
QApplication::setFont(), QApplication::font()
Definition at line 823 of file qfont.cpp.
     : d(QApplication::font().d.data()), resolve_mask(0)
 {
 }
QFont() [2/5]
QFont::QFont (const QString & family, int pointSize = -1, int weight = -1, bool italic = false)
Constructs a font object with the specified family, pointSize, weight and italic settings.
If pointSize is zero or negative, the point size of the font is set to a system-dependent default value. Generally, this is 12 points, except on Symbian where it is 7 points.
The family name may optionally also include a foundry name, e.g. "Helvetica [Cronyx]". If the family is available from more than one foundry and the foundry isn't specified, an arbitrary foundry is chosen. If the family isn't available a family will be set using the font matching algorithm.
See also
Weight, setFamily(), setPointSize(), setWeight(), setItalic(), setStyleHint() QApplication::font()
Definition at line 846 of file qfont.cpp.
     : d(new QFontPrivate()), resolve_mask(QFont::FamilyResolved)
 {
     if (pointSize <= 0) {
 #ifdef Q_OS_SYMBIAN
         pointSize = 7;
 #else
         pointSize = 12;
 #endif
     } else {
         resolve_mask |= QFont::SizeResolved;
     }
     if (weight < 0) {
         weight = Normal;
     } else {
         resolve_mask |= QFont::WeightResolved | QFont::StyleResolved;
     }
     if (italic)
         resolve_mask |= QFont::StyleResolved;
     d->request.family = family;
     d->request.pointSize = qreal(pointSize);
     d->request.pixelSize = -1;
     d->request.weight = weight;
     d->request.style = italic ? QFont::StyleItalic : QFont::StyleNormal;
 }
QFont() [3/5]
QFont::QFont (const QFont & font, QPaintDevice * pd)
Constructs a font from font for use on the paint device pd.
Definition at line 765 of file qfont.cpp.
     : resolve_mask(font.resolve_mask)
 {
     Q_ASSERT(pd != 0);
     int dpi = pd->logicalDpiY();
 #ifdef Q_WS_X11
     const QX11Info *info = qt_x11Info(pd);
     int screen = info ? info->screen() : 0;
 #else
     const int screen = 0;
 #endif
     if (font.d->dpi != dpi || font.d->screen != screen ) {
         d = new QFontPrivate(*font.d);
         d->dpi = dpi;
         d->screen = screen;
     } else {
         d = font.d.data();
     }
 #ifdef Q_WS_WIN
     if (pd->devType() == QInternal::Printer && pd->getDC())
         d->hdc = pd->getDC();
 #endif
 }
QFont() [4/5]
QFont::QFont (const QFont & font)
Constructs a font that is a copy of font.
Definition at line 878 of file qfont.cpp.
     : d(font.d.data()), resolve_mask(font.resolve_mask)
 {
 }
~QFont()
QFont::~QFont ()
Destroys the font object and frees all allocated resources.
Definition at line 886 of file qfont.cpp.
 {
 }
QFont() [5/5]
QFont::QFont (QFontPrivate * data) private
Warning
This function is not part of the public interface.
Definition at line 792 of file qfont.cpp.
     : d(data), resolve_mask(QFont::AllPropertiesResolved)
 {
 }
Functions
bold()
bool QFont::bold () const inline
Returns true if weight() is a value greater than QFont::Normal ; otherwise returns false.
See also
weight(), setBold(), QFontInfo::bold()
Definition at line 348 of file qfont.h.
Referenced by getFontSet(), QDeclarativeFontValueType::setFamily(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 { return weight() > Normal; }
capitalization()
QFont::Capitalization QFont::capitalization () const
Returns the current capitalization type of the font.
Since
4.4
See also
setCapitalization()
Definition at line 1819 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), QTextHtmlParserNode::applyCssDeclarations(), setCapitalization(), QTextCharFormat::setFont(), and QDeclarativeFontValueType::setPixelSize().
 {
     return static_cast<QFont::Capitalization> (d->capital);
 }
cleanup()
void QFont::cleanup () static
Internal function that cleans up the font system.
Warning
This function is not part of the public interface.
Definition at line 93 of file qfont_mac.cpp.
Referenced by pointSize(), qt_cleanup(), and qt_x11_set_fallback_font_family().
 {
     QFontCache::cleanup();
 }
defaultFamily()
QString QFont::defaultFamily () const
Returns the family name that corresponds to the current style hint.
See also
StyleHint styleHint() setStyleHint()
Definition at line 134 of file qfont_mac.cpp.
Referenced by freetypeFace(), getFcPattern(), loadFromDatabase(), loadWin(), pointSize(), qt_x11_set_fallback_font_family(), and registerFont().
 {
     switch(d->request.styleHint) {
         case QFont::Times:
             return QString::fromLatin1("Times New Roman");
         case QFont::Courier:
             return QString::fromLatin1("Courier New");
         case QFont::Monospace:
             return QString::fromLatin1("Courier");
         case QFont::Decorative:
             return QString::fromLatin1("Bookman Old Style");
         case QFont::Cursive:
             return QString::fromLatin1("Apple Chancery");
         case QFont::Fantasy:
             return QString::fromLatin1("Papyrus");
         case QFont::Helvetica:
         case QFont::System:
         default:
             return QString::fromLatin1("Helvetica");
     }
 }
detach()
void QFont::detach () private
Detaches the font object from common font data.
Warning
This function is not part of the public interface.
Definition at line 803 of file qfont.cpp.
Referenced by QCommandLinkButtonPrivate::descriptionFont(), qt_x11_set_fallback_font_family(), resolve(), setCapitalization(), setFamily(), setFixedPitch(), setHintingPreference(), setKerning(), setLetterSpacing(), setOverline(), setPixelSize(), setPointSize(), setPointSizeF(), setRawMode(), setStretch(), setStrikeOut(), setStyle(), setStyleHint(), setStyleName(), setStyleStrategy(), setUnderline(), setWeight(), setWordSpacing(), and QCommandLinkButtonPrivate::titleFont().
 {
     if (d->ref == 1) {
         if (d->engineData)
             d->engineData->ref.deref();
         d->engineData = 0;
         if (d->scFont && d->scFont != d.data())
             d->scFont->ref.deref();
         d->scFont = 0;
         return;
     }
     d.detach();
 }
exactMatch()
bool QFont::exactMatch () const
Returns true if a window system font exactly matching the settings of this font is available.
See also
QFontInfo
Definition at line 1857 of file qfont.cpp.
Referenced by qt_set_x11_resources().
 {
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     Q_ASSERT(engine != 0);
     return (d->rawMode
             ? engine->type() != QFontEngine::Box
             : d->request.exactMatch(engine->fontDef));
 }
family()
QString QFont::family () const
Returns the requested font family name, i.e.
the name set in the constructor or the last setFont() call.
See also
setFamily() substitutes() substitute()
Definition at line 906 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), QTextHtmlParserNode::applyCssDeclarations(), QGLContext::choosePixelFormat(), QPaintBuffer::commandDescription(), QFontDatabase::findFont(), QRawFont::fromFont(), getFcPattern(), loadWin(), pointSize(), QFont(), QFontToIFont(), qt_init(), rawName(), registerFont(), QFontDialog::setCurrentFont(), setFamily(), QPainter::setFont(), QTextCharFormat::setFont(), QDeclarativeFontValueType::setValue(), QMenuPrivate::QMacMenuPrivate::syncAction(), toString(), QWindowsVistaStyle::unpolish(), QFontDialogPrivate::updateFamilies(), and writingSystemForFont().
 {
     return d->request.family;
 }
fixedPitch()
bool QFont::fixedPitch () const
Returns true if fixed pitch has been set; otherwise returns false.
See also
setFixedPitch(), QFontInfo::fixedPitch()
Definition at line 1391 of file qfont.cpp.
Referenced by QTextFormatPrivate::recalcFont(), QTextCharFormat::setFont(), and toString().
 {
     return d->request.fixedPitch;
 }
freetypeFace()
FT_Face QFont::freetypeFace () const
Returns the handle to the primary FreeType face of the font.
If font merging is not disabled a QFont can contain several physical fonts.
Returns 0 if the font does not contain a FreeType face.
Note
This function is only available on platforms that provide the FreeType library; i.e., X11 and some Embedded Linux platforms.
Definition at line 82 of file qfont_qws.cpp.
Referenced by qt_x11_set_fallback_font_family().
 {
 #ifndef QT_NO_FREETYPE
     QFontEngine *engine = d->engineForScript(QUnicodeTables::Common);
     if (engine->type() == QFontEngine::Multi)
         engine = static_cast<QFontEngineMulti *>(engine)->engine(0);
     if (engine->type() == QFontEngine::Freetype) {
         const QFontEngineFT *ft = static_cast<const QFontEngineFT *>(engine);
         return ft->non_locked_face();
     }
 #endif
     return 0;
 }
fromString()
bool QFont::fromString (const QString & descrip)
Sets this font to match the description descrip.
The description is a comma-separated list of the font attributes, as returned by toString().
See also
toString()
Definition at line 2367 of file qfont.cpp.
Referenced by convert(), QApplicationPrivate::qt_mac_apply_settings(), and QApplicationPrivate::x11_apply_settings().
 {
     QStringList l(descrip.split(QLatin1Char(',')));
     int count = l.count();
     if (!count || (count > 2 && count < 9) || count > 11) {
         qWarning("QFont::fromString: Invalid description '%s'",
                  descrip.isEmpty() ? "(empty)" : descrip.toLatin1().data());
         return false;
     }
     setFamily(l[0]);
     if (count > 1 && l[1].toDouble() > 0.0)
         setPointSizeF(l[1].toDouble());
     if (count == 9) {
         setStyleHint((StyleHint) l[2].toInt());
         setWeight(qMax(qMin(99, l[3].toInt()), 0));
         setItalic(l[4].toInt());
         setUnderline(l[5].toInt());
         setStrikeOut(l[6].toInt());
         setFixedPitch(l[7].toInt());
         setRawMode(l[8].toInt());
     } else if (count == 10) {
         if (l[2].toInt() > 0)
             setPixelSize(l[2].toInt());
         setStyleHint((StyleHint) l[3].toInt());
         setWeight(qMax(qMin(99, l[4].toInt()), 0));
         setStyle((QFont::Style)l[5].toInt());
         setUnderline(l[6].toInt());
         setStrikeOut(l[7].toInt());
         setFixedPitch(l[8].toInt());
         setRawMode(l[9].toInt());
     }
     if (count >= 9 && !d->request.fixedPitch) // assume 'false' fixedPitch equals default
         d->request.ignorePitch = true;
     return true;
 }
handle()
Qt::HANDLE QFont::handle () const
Returns the window system handle to the font, for low-level access.
Using this function is not portable.
Definition at line 121 of file qfont_mac.cpp.
Referenced by QGLContext::choosePixelFormat(), macFontID(), pointSize(), qgl_use_font(), qt_x11_set_fallback_font_family(), and QWinInputContext::update().
 {
 #ifdef QT_MAC_USE_COCOA
     QFontEngine *fe = d->engineForScript(QUnicodeTables::Common);
     if (fe && fe->type() == QFontEngine::Multi)
         return (Qt::HANDLE)static_cast<QCoreTextFontEngineMulti*>(fe)->macFontID();
 #endif
     return 0;
 }
hintingPreference()
QFont::HintingPreference QFont::hintingPreference () const
Returns the currently preferred hinting level for glyphs rendered with this font.
Since
4.8
Definition at line 1088 of file qfont.cpp.
Referenced by QRawFont::fromFont(), and setHintingPreference().
 {
     return QFont::HintingPreference(d->request.hintingPreference);
 }
initialize()
void QFont::initialize () static
Internal function that initializes the font system.
Warning
This function is not part of the public interface.
The font cache and font dict do not alloc the keys. The key is a QString which is shared between QFontPrivate and QXFontName.
Definition at line 131 of file qfont_mac.cpp.
Referenced by init_display(), pointSize(), qt_init(), and qt_x11_set_fallback_font_family().
 { }
insertSubstitution()
void QFont::insertSubstitution (const QString & familyName, const QString & substituteName) static
Inserts substituteName into the substitution table for the family familyName.
See also
insertSubstitutions() removeSubstitution() substitutions() substitute() substitutes()
Definition at line 2155 of file qfont.cpp.
 {
     initFontSubst();
     QFontSubst *fontSubst = globalFontSubst();
     Q_ASSERT(fontSubst != 0);
     QStringList &list = (*fontSubst)[familyName.toLower()];
     QString s = substituteName.toLower();
     if (!list.contains(s))
         list.append(s);
 }
insertSubstitutions()
void QFont::insertSubstitutions (const QString & familyName, const QStringList & substituteNames) static
Inserts the list of families substituteNames into the substitution list for familyName.
See also
insertSubstitution(), removeSubstitution(), substitutions(), substitute()
Definition at line 2175 of file qfont.cpp.
Referenced by QApplicationPrivate::qt_mac_apply_settings(), and QApplicationPrivate::x11_apply_settings().
 {
     initFontSubst();
     QFontSubst *fontSubst = globalFontSubst();
     Q_ASSERT(fontSubst != 0);
     QStringList &list = (*fontSubst)[familyName.toLower()];
     QStringList::ConstIterator it = substituteNames.constBegin();
     while (it != substituteNames.constEnd()) {
         QString s = (*it).toLower();
         if (!list.contains(s))
             list.append(s);
         it++;
     }
 }
isCopyOf()
bool QFont::isCopyOf (const QFont & f) const
Returns true if this font and f are copies of each other, i.e.
one of them was created as a copy of the other and neither has been modified since. This is much stricter than equality.
See also
operator=() operator==()
Definition at line 1963 of file qfont.cpp.
Referenced by QWidgetPrivate::naturalWidgetFont(), and QApplication::setFont().
 {
     return d == f.d;
 }
italic()
bool QFont::italic () const inline
Returns true if the style() of the font is not QFont::StyleNormal.
See also
setItalic() style()
Definition at line 355 of file qfont.h.
Referenced by getFontSet(), QFontToIFont(), QTextCharFormat::setFont(), QDeclarativeFontValueType::setWeight(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
     return (style() != StyleNormal);
 }
kerning()
bool QFont::kerning () const
Returns true if kerning should be used when drawing text with this font.
See also
setKerning()
Definition at line 1416 of file qfont.cpp.
Referenced by draw_text_item_win(), and QTextCharFormat::setFont().
 {
     return d->kerning;
 }
key()
QString QFont::key () const
Returns the font's key, a textual representation of a font.
It is typically used as the key for a cache or dictionary of fonts.
See also
QMap
Definition at line 2332 of file qfont.cpp.
 {
     return toString();
 }
lastResortFamily()
QString QFont::lastResortFamily () const
Returns the "last resort" font family name.
The current implementation tries a wide variety of common fonts, returning the first one it finds. Is is possible that no family is found in which case an empty string is returned.
See also
lastResortFont()
Definition at line 156 of file qfont_mac.cpp.
Referenced by freetypeFace(), pointSize(), qt_x11_set_fallback_font_family(), and QFontDialogPrivate::updateFamilies().
 {
     return QString::fromLatin1("Helvetica");
 }
lastResortFont()
QString QFont::lastResortFont () const
Returns a "last resort" font name for the font matching algorithm.
This is used if the last resort family is not available. It will always return a name, if necessary returning something like "fixed" or "system".
The current implementation tries a wide variety of common fonts, returning the first one it finds. The implementation may change at any time, but this function will always return a string containing something.
It is theoretically possible that there really isn't a lastResortFont() in which case Qt will abort with an error message. We have not been able to identify a case where this happens. Please report it as a bug if it does, preferably with a list of the fonts you have installed.
See also
lastResortFamily() rawName()
Definition at line 161 of file qfont_mac.cpp.
Referenced by fontExists(), freetypeFace(), and pointSize().
 {
     return QString::fromLatin1("Geneva");
 }
letterSpacing()
qreal QFont::letterSpacing () const
Returns the letter spacing for the font.
Since
4.4
See also
setLetterSpacing(), letterSpacingType(), setWordSpacing()
Definition at line 1677 of file qfont.cpp.
Referenced by QDeclarativeFontValueType::setCapitalization(), and QTextCharFormat::setFont().
 {
     return d->letterSpacing.toReal();
 }
letterSpacingType()
QFont::SpacingType QFont::letterSpacingType () const
Returns the spacing type used for letter spacing.
Since
4.4
See also
letterSpacing(), setLetterSpacing(), setWordSpacing()
Definition at line 1721 of file qfont.cpp.
Referenced by QTextCharFormat::setFont().
 {
     return d->letterSpacingIsAbsolute ? AbsoluteSpacing : PercentageSpacing;
 }
macFontID()
quint32 QFont::macFontID () const
Returns an ATSUFontID.
Definition at line 101 of file qfont_mac.cpp.
Referenced by handle(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 {
 #ifdef QT_MAC_USE_COCOA
     return 0;
 #elif 1
     QFontEngine *fe = d->engineForScript(QUnicodeTables::Common);
     if (fe && fe->type() == QFontEngine::Multi)
         return static_cast<QFontEngineMacMulti*>(fe)->macFontID();
 #else
     Str255 name;
     if(FMGetFontFamilyName((FMFontFamily)((UInt32)handle()), name) == noErr) {
         short fnum;
         GetFNum(name, &fnum);
         return fnum;
     }
 #endif
     return 0;
 }
macSetFont()
void QFont::macSetFont (QPaintDevice *) private
operator QVariant()
QFont::operator QVariant () const
Returns the font as a QVariant.
Definition at line 1951 of file qfont.cpp.
 {
     return QVariant(QVariant::Font, this);
 }
operator!=()
bool QFont::operator!= (const QFont & f) const
Returns true if this font is different from f; otherwise returns false.
Two QFonts are considered to be different if their font attributes are different. If rawMode() is enabled for both fonts, only the family fields are compared.
See also
operator==()
Definition at line 1943 of file qfont.cpp.
 {
     return !(operator==(f));
 }
operator<()
bool QFont::operator< (const QFont & f) const
Provides an arbitrary comparison of this font and font f.
All that is guaranteed is that the operator returns false if both fonts are equal and that (f1 < f2) == !(f2 < f1) if the fonts are not equal.
This function is useful in some circumstances, for example if you want to use QFont objects as keys in a QMap.
See also
operator==() operator!=() isCopyOf()
Definition at line 1904 of file qfont.cpp.
 {
     if (f.d == d) return false;
     // the < operator for fontdefs ignores point sizes.
     QFontDef &r1 = f.d->request;
     QFontDef &r2 = d->request;
     if (r1.pointSize != r2.pointSize) return r1.pointSize < r2.pointSize;
     if (r1.pixelSize != r2.pixelSize) return r1.pixelSize < r2.pixelSize;
     if (r1.weight != r2.weight) return r1.weight < r2.weight;
     if (r1.style != r2.style) return r1.style < r2.style;
     if (r1.stretch != r2.stretch) return r1.stretch < r2.stretch;
     if (r1.styleHint != r2.styleHint) return r1.styleHint < r2.styleHint;
     if (r1.styleStrategy != r2.styleStrategy) return r1.styleStrategy < r2.styleStrategy;
     if (r1.family != r2.family) return r1.family < r2.family;
 #ifdef Q_WS_X11
     if (r1.addStyle != r2.addStyle) return r1.addStyle < r2.addStyle;
 #endif // Q_WS_X11
     if (f.d->capital != d->capital) return f.d->capital < d->capital;
     if (f.d->letterSpacingIsAbsolute != d->letterSpacingIsAbsolute) return f.d->letterSpacingIsAbsolute < d->letterSpacingIsAbsolute;
     if (f.d->letterSpacing != d->letterSpacing) return f.d->letterSpacing < d->letterSpacing;
     if (f.d->wordSpacing != d->wordSpacing) return f.d->wordSpacing < d->wordSpacing;
     int f1attrs = (f.d->underline << 3) + (f.d->overline << 2) + (f.d->strikeOut<<1) + f.d->kerning;
     int f2attrs = (d->underline << 3) + (d->overline << 2) + (d->strikeOut<<1) + d->kerning;
     return f1attrs < f2attrs;
 }
operator=()
QFont & QFont::operator= (const QFont & font)
Assigns font to this font and returns a reference to it.
Definition at line 893 of file qfont.cpp.
 {
     d = font.d.data();
     resolve_mask = font.resolve_mask;
     return *this;
 }
operator==()
bool QFont::operator== (const QFont & f) const
Returns true if this font is equal to f; otherwise returns false.
Two QFonts are considered equal if their font attributes are equal. If rawMode() is enabled for both fonts, only the family fields are compared.
See also
operator!=() isCopyOf()
Definition at line 1876 of file qfont.cpp.
Referenced by operator!=().
 {
     return (f.d == d
             || (f.d->request   == d->request
                 && f.d->request.pointSize == d->request.pointSize
                 && f.d->underline == d->underline
                 && f.d->overline  == d->overline
                 && f.d->strikeOut == d->strikeOut
                 && f.d->kerning == d->kerning
                 && f.d->capital == d->capital
                 && f.d->letterSpacingIsAbsolute == d->letterSpacingIsAbsolute
                 && f.d->letterSpacing == d->letterSpacing
                 && f.d->wordSpacing == d->wordSpacing
             ));
 }
overline()
bool QFont::overline () const
Returns true if overline has been set; otherwise returns false.
See also
setOverline()
Definition at line 1344 of file qfont.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QTextLine::glyphs(), qt_draw_decoration_for_glyphs(), QTextCharFormat::setFont(), and QDeclarativeFontValueType::setUnderline().
 {
     return d->overline;
 }
pixelSize()
int QFont::pixelSize () const
Returns the pixel size of the font if it was set with setPixelSize().
Returns -1 if the size was set with setPointSize() or setPointSizeF().
See also
setPixelSize() pointSize() QFontInfo::pointSize() QFontInfo::pixelSize()
Definition at line 1178 of file qfont.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QPainter::drawStaticText(), QTextEngine::font(), QTextEngine::fontEngine(), qt_set_x11_resources(), QTextFormatPrivate::resolveFont(), QTextCharFormat::setFont(), setPixelSize(), QDeclarativeFontValueType::setPointSize(), QDeclarativeFontValueType::setStrikeout(), QFontPrivate::smallCapsFontPrivate(), and toString().
 {
     return d->request.pixelSize;
 }
pointSize()
int QFont::pointSize () const
Returns the point size of the font.
Returns -1 if the font size was specified in pixels.
See also
setPointSize() pointSizeF()
Definition at line 981 of file qfont.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QWindowsMobileStyle::drawControl(), QTextEngine::font(), QTextEngine::fontEngine(), getFontSet(), QBalloonTip::QBalloonTip(), QFontToIFont(), qt_aqua_get_known_size(), qt_set_windows_font_resources(), qt_set_x11_resources(), QWizardPrivate::recreateLayout(), QTextFormatPrivate::resolveFont(), QFontDialog::setCurrentFont(), QPainter::setFont(), setPointSizeF(), QMenuPrivate::QMacMenuPrivate::syncAction(), QPicturePaintEngine::updateFont(), and QTextEdit::zoomIn().
 {
     return qRound(d->request.pointSize);
 }
pointSizeF()
qreal QFont::pointSizeF () const
Returns the point size of the font.
Returns -1 if the font size was specified in pixels.
See also
pointSize() setPointSizeF() pixelSize() QFontInfo::pointSize() QFontInfo::pixelSize()
Definition at line 1142 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), QSvgText::draw(), QPagePreview::paintEvent(), QTextFormatPrivate::resolveFont(), QTextCharFormat::setFont(), QDeclarativeFontValueType::setPointSize(), QDeclarativeFontValueType::setStrikeout(), QFontPrivate::smallCapsFontPrivate(), and toString().
 {
     return d->request.pointSize;
 }
rawMode()
bool QFont::rawMode () const
Returns true if raw mode is used for font name matching; otherwise returns false.
See also
setRawMode() rawName()
Definition at line 1974 of file qfont.cpp.
Referenced by qt_set_x11_resources(), and toString().
 {
     return d->rawMode;
 }
rawName()
QString QFont::rawName () const
Returns the name of the font within the underlying window system.
On X11, this function will return an empty string if Qt is built with FontConfig support; otherwise the XLFD (X Logical Font Description) is returned.
Using the return value of this function is usually not portable.
See also
setRawName()
Definition at line 83 of file qfont_mac.cpp.
Referenced by freetypeFace(), pointSize(), and qt_x11_set_fallback_font_family().
 {
     return family();
 }
removeSubstitution()
void QFont::removeSubstitution (const QString & familyName) static
Removes all the substitutions for familyName.
See also
insertSubstitutions(), insertSubstitution(), substitutions(), substitute()
Definition at line 2218 of file qfont.cpp.
 { // ### function name should be removeSubstitutions() or
   // ### removeSubstitutionList()
     initFontSubst();
     QFontSubst *fontSubst = globalFontSubst();
     Q_ASSERT(fontSubst != 0);
     fontSubst->remove(familyName.toLower());
 }
resolve() [1/3]
QFont QFont::resolve (const QFont & other) const
Returns a new QFont that has attributes copied from other that have not been previously set on this font.
Definition at line 1983 of file qfont.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QCommandLinkButtonPrivate::descriptionFont(), QStyleSheetStyle::drawComplexControl(), QStyleSheetStyle::drawControl(), QTextEngine::font(), QTextEngine::fontEngine(), QMenu::initStyleOption(), QGraphicsWidgetPrivate::naturalWidgetFont(), QWidgetPrivate::naturalWidgetFont(), QGraphicsWidgetPrivate::resolveFont(), QTextFormatPrivate::resolveFont(), QGraphicsScenePrivate::resolveFont(), QWidgetPrivate::resolveFont(), QGraphicsWidget::setFont(), QPainter::setFont(), QGraphicsScene::setFont(), QWidget::setFont(), QGraphicsWidgetPrivate::setFont_helper(), QGraphicsScenePrivate::setFont_helper(), QWidgetPrivate::setFont_helper(), QGraphicsWidget::setStyle(), QMenuPrivate::QMacMenuPrivate::syncAction(), QCommandLinkButtonPrivate::titleFont(), QGraphicsWidgetPrivate::updateFont(), QGraphicsScenePrivate::updateFont(), QWidgetPrivate::updateFont(), and QStyleSheetStyle::updateStyleSheetFont().
 {
     if (*this == other
         && (resolve_mask == other.resolve_mask || resolve_mask == 0)
         && d->dpi == other.d->dpi) {
         QFont o = other;
         o.resolve_mask = resolve_mask;
         return o;
     }
     QFont font(*this);
     font.detach();
     font.d->resolve(resolve_mask, other.d.data());
     return font;
 }
resolve() [2/3]
uint QFont::resolve () const inline
Warning
This function is not part of the public interface.
Definition at line 287 of file qfont.h.
 { return resolve_mask; }
resolve() [3/3]
void QFont::resolve (uint mask) inline
Warning
This function is not part of the public interface.
Definition at line 288 of file qfont.h.
 { resolve_mask = mask; }
setBold()
void QFont::setBold (bool enable) inline
If enable is true sets the font's weight to QFont::Bold ; otherwise sets the weight to QFont::Normal.
For finer boldness control use setWeight().
See also
bold(), setWeight()
Definition at line 352 of file qfont.h.
Referenced by QMessageBox::changeEvent(), QmlJSDebugger::LiveSelectionTool::createContextMenu(), QCalendarWidgetPrivate::createNavigationBar(), QScriptDebuggerLocalsModel::data(), QPPDOptionsModel::data(), QWindowsCEStyle::drawComplexControl(), QPlastiqueStyle::drawComplexControl(), QWindowsMobileStyle::drawComplexControl(), QCleanlooksStyle::drawComplexControl(), QGtkStyle::drawComplexControl(), QWindowsCEStyle::drawControl(), QWindowsVistaStyle::drawControl(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QCleanlooksStyle::drawControl(), QWindowsXPStyle::drawControl(), QWindowsStyle::drawControl(), QGtkStyle::drawControl(), IFontToQFont(), QMessageBoxPrivate::init(), QBalloonTip::QBalloonTip(), qt_set_windows_font_resources(), QWizardHeader::QWizardHeader(), QWizardPrivate::recreateLayout(), QDeclarativeFontValueType::setBold(), QCleanlooksStyle::sizeFromContents(), QWindowsStyle::sizeFromContents(), QCleanlooksStyle::subControlRect(), QGtkStyle::subControlRect(), and QCommandLinkButtonPrivate::titleFont().
 { setWeight(enable ? Bold : Normal); }
setCapitalization()
void QFont::setCapitalization (Capitalization caps)
Sets the capitalization of the text in this font to caps.
Since
4.4
A font's capitalization makes the text appear in the selected capitalization mode.
See also
capitalization()
Definition at line 1798 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), QTextFormatPrivate::recalcFont(), QDeclarativeFontValueType::setCapitalization(), setFontVariantFromValue(), and setTextTransformFromValue().
 {
     if ((resolve_mask & QFont::CapitalizationResolved) &&
         capitalization() == caps)
         return;
     detach();
     d->capital = caps;
     resolve_mask |= QFont::CapitalizationResolved;
 }
setFamily()
void QFont::setFamily (const QString & family)
Sets the family name of the font.
The name is case insensitive and may include a foundry name.
The family name may optionally also include a foundry name, e.g. "Helvetica [Cronyx]". If the family is available from more than one foundry and the foundry isn't specified, an arbitrary foundry is chosen. If the family isn't available a family will be set using the font matching algorithm.
See also
family(), setStyleHint(), QFontInfo
Definition at line 924 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), fromString(), QGtkStylePrivate::getThemeFont(), QFontFamilyDelegate::paint(), pointSize(), QWindowsVistaStyle::polish(), qt_init(), qt_set_x11_resources(), qt_x11_set_fallback_font_family(), QTextFormatPrivate::recalcFont(), QDeclarativeFontValueType::setFamily(), setFontFamilyFromValues(), setRawName(), and QWindowsVistaStyle::unpolish().
 {
     detach();
     d->request.family = family;
 #if defined(Q_WS_X11)
     d->request.addStyle.clear();
 #endif // Q_WS_X11
     resolve_mask |= QFont::FamilyResolved;
 }
setFixedPitch()
void QFont::setFixedPitch (bool enable)
If enable is true, sets fixed pitch on; otherwise sets fixed pitch off.
See also
fixedPitch(), QFontInfo
Definition at line 1402 of file qfont.cpp.
Referenced by fromString(), and QTextFormatPrivate::recalcFont().
 {
     detach();
     d->request.fixedPitch = enable;
     d->request.ignorePitch = false;
     resolve_mask |= QFont::FixedPitchResolved;
 }
setHintingPreference()
void QFont::setHintingPreference (HintingPreference hintingPreference)
Set the preference for the hinting level of the glyphs to hintingPreference.
Since
4.8
This is a hint to the underlying font rendering system to use a certain level of hinting, and has varying support across platforms. See the table in the documentation for QFont::HintingPreference for more details.
The default hinting preference is QFont::PreferDefaultHinting.
Definition at line 1071 of file qfont.cpp.
Referenced by QTextFormatPrivate::recalcFont().
 {
     detach();
     d->request.hintingPreference = hintingPreference;
     resolve_mask |= QFont::HintingPreferenceResolved;
 }
setItalic()
void QFont::setItalic (bool enable) inline
Sets the style() of the font to QFont::StyleItalic if enable is true; otherwise the style is set to QFont::StyleNormal.
See also
italic() QFontInfo
Definition at line 360 of file qfont.h.
Referenced by fromString(), qt_LOGFONTtoQFont(), qt_set_x11_resources(), QTextFormatPrivate::recalcFont(), and QDeclarativeFontValueType::setItalic().
{
     setStyle(b ? StyleItalic : StyleNormal);
 }
setKerning()
void QFont::setKerning (bool enable)
Enables kerning for this font if enable is true; otherwise disables it.
By default, kerning is enabled.
When kerning is enabled, glyph metrics do not add up anymore, even for Latin text. In other words, the assumption that width('a') + width('b') is equal to width("ab") is not neccesairly true.
See also
kerning(), QFontMetrics
Definition at line 1432 of file qfont.cpp.
Referenced by QTextFormatPrivate::recalcFont().
 {
     detach();
     d->kerning = enable;
     resolve_mask |= QFont::KerningResolved;
 }
setLetterSpacing()
void QFont::setLetterSpacing (SpacingType type, qreal spacing)
Sets the letter spacing for the font to spacing and the type of spacing to type.
Since
4.4
Letter spacing changes the default spacing between individual letters in the font. The spacing between the letters can be made smaller as well as larger.
See also
letterSpacing(), letterSpacingType(), setWordSpacing()
Definition at line 1696 of file qfont.cpp.
Referenced by QTextFormatPrivate::recalcFont(), and QDeclarativeFontValueType::setLetterSpacing().
 {
     const QFixed newSpacing = QFixed::fromReal(spacing);
     const bool absoluteSpacing = type == AbsoluteSpacing;
     if ((resolve_mask & QFont::LetterSpacingResolved) &&
         d->letterSpacingIsAbsolute == absoluteSpacing &&
         d->letterSpacing == newSpacing)
         return;
     detach();
     d->letterSpacing = newSpacing;
     d->letterSpacingIsAbsolute = absoluteSpacing;
     resolve_mask |= QFont::LetterSpacingResolved;
 }
setOverline()
void QFont::setOverline (bool enable)
If enable is true, sets overline on; otherwise sets overline off.
See also
overline(), QFontInfo
Definition at line 1354 of file qfont.cpp.
Referenced by QPicturePaintEngine::drawTextItem(), qt_LOGFONTtoQFont(), QTextFormatPrivate::recalcFont(), QDeclarativeFontValueType::setOverline(), and setTextDecorationFromValues().
 {
     detach();
     d->overline = enable;
     resolve_mask |= QFont::OverlineResolved;
 }
setPixelSize()
void QFont::setPixelSize (int pixelSize)
Sets the font size to pixelSize pixels.
Using this function makes the font device dependent. Use setPointSize() or setPointSizeF() to set the size of the font in a device independent manner.
See also
pixelSize()
Definition at line 1156 of file qfont.cpp.
Referenced by QSvgText::draw(), QTextEngine::font(), QTextEngine::fontEngine(), fromString(), pixelSize(), QUIKitScreen::QUIKitScreen(), QTextFormatPrivate::recalcFont(), QTextFormatPrivate::resolveFont(), setFontSizeFromValue(), QDeclarativeFontValueType::setPixelSize(), and QFontPrivate::smallCapsFontPrivate().
 {
     if (pixelSize <= 0) {
         qWarning("QFont::setPixelSize: Pixel size <= 0 (%d)", pixelSize);
         return;
     }
     detach();
     d->request.pixelSize = pixelSize;
     d->request.pointSize = -1;
     resolve_mask |= QFont::SizeResolved;
 }
setPointSize()
void QFont::setPointSize (int pointSize)
Sets the point size to pointSize.
The point size must be greater than zero.
See also
pointSize() setPointSizeF()
Definition at line 1099 of file qfont.cpp.
Referenced by QDragManager::drag(), QPlastiqueStyle::drawControl(), QWindowsMobileStyle::drawControl(), QApplication::font(), QTextEngine::font(), QTextEngine::fontEngine(), QFontFamilyDelegate::paint(), QBalloonTip::QBalloonTip(), qt_set_windows_font_resources(), qt_set_x11_resources(), QWizardPrivate::recreateLayout(), QFontFamilyDelegate::sizeHint(), and QTextEdit::zoomIn().
 {
     if (pointSize <= 0) {
         qWarning("QFont::setPointSize: Point size <= 0 (%d), must be greater than 0", pointSize);
         return;
     }
     detach();
     d->request.pointSize = qreal(pointSize);
     d->request.pixelSize = -1;
     resolve_mask |= QFont::SizeResolved;
 }
setPointSizeF()
void QFont::setPointSizeF (qreal pointSize)
Sets the point size to pointSize.
The point size must be greater than zero. The requested precision may not be achieved on all platforms.
See also
pointSizeF() setPointSize() setPixelSize()
Definition at line 1121 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), QCommandLinkButtonPrivate::descriptionFont(), QCleanlooksStyle::drawControl(), QMacStyle::drawControl(), fromString(), QGtkStylePrivate::getThemeFont(), QPagePreview::paintEvent(), qt_LOGFONTtoQFont(), QTextFormatPrivate::recalcFont(), QTextFormatPrivate::resolveFont(), setFontSizeFromValue(), QDeclarativeFontValueType::setPointSize(), QFontPrivate::smallCapsFontPrivate(), and QCommandLinkButtonPrivate::titleFont().
 {
     if (pointSize <= 0) {
         qWarning("QFont::setPointSizeF: Point size <= 0 (%f), must be greater than 0", pointSize);
         return;
     }
     detach();
     d->request.pointSize = pointSize;
     d->request.pixelSize = -1;
     resolve_mask |= QFont::SizeResolved;
 }
setRawMode()
void QFont::setRawMode (bool enable)
If enable is true, turns raw mode on; otherwise turns raw mode off.
This function only has an effect under X11.
If raw mode is enabled, Qt will search for an X font with a complete font name matching the family name, ignoring all other values set for the QFont. If the font name matches several fonts, Qt will use the first font returned by X. QFontInfo cannot be used to fetch information about a QFont using raw mode (it will return the values set in the QFont for all parameters, including the family name).
Warning
Do not use raw mode unless you really, really need it! In most (if not all) cases, setRawName() is a much better choice.
See also
rawMode(), setRawName()
Definition at line 1842 of file qfont.cpp.
Referenced by fromString(), qt_set_x11_resources(), and qt_x11_set_fallback_font_family().
 {
     detach();
     if ((bool) d->rawMode == enable) return;
     d->rawMode = enable;
 }
setRawName()
void QFont::setRawName (const QString & name)
Sets a font by its system specific name.
The function is particularly useful under X, where system font settings (for example X resources) are usually available in XLFD (X Logical Font Description) form only. You can pass an XLFD as name to this function.
A font set with setRawName() is still a full-featured QFont. It can be queried (for example with italic()) or modified (for example with setItalic()) and is therefore also suitable for rendering rich text.
If Qt's internal font database cannot resolve the raw name, the font becomes a raw font with name as its family.
Note that the present implementation does not handle wildcards in XLFDs well, and that font aliases (file fonts.alias in the font directory on X11) are not supported.
See also
rawName(), setRawMode(), setFamily()
Definition at line 88 of file qfont_mac.cpp.
Referenced by freetypeFace(), pointSize(), qt_set_x11_resources(), and qt_x11_set_fallback_font_family().
 {
     setFamily(name);
 }
setStretch()
void QFont::setStretch (int factor)
Sets the stretch factor for the font.
The stretch factor changes the width of all characters in the font by factor percent. For example, setting factor to 150 results in all characters in the font being 1.5 times (ie. 150%) wider. The default stretch factor is 100. The minimum stretch factor is 1, and the maximum stretch factor is 4000.
The stretch factor is only applied to outline fonts. The stretch factor is ignored for bitmap fonts.
NOTE: QFont cannot stretch XLFD fonts. When loading XLFD fonts on X11, the stretch factor is matched against a predefined set of values for the SETWIDTH_NAME field of the XLFD.
See also
stretch() QFont::Stretch
Definition at line 1641 of file qfont.cpp.
 {
     if (factor < 1 || factor > 4000) {
         qWarning("QFont::setStretch: Parameter '%d' out of range", factor);
         return;
     }
     if ((resolve_mask & QFont::StretchResolved) &&
          d->request.stretch == (uint)factor)
         return;
     detach();
     d->request.stretch = (uint)factor;
     resolve_mask |= QFont::StretchResolved;
 }
setStrikeOut()
void QFont::setStrikeOut (bool enable)
If enable is true, sets strikeout on; otherwise sets strikeout off.
See also
strikeOut(), QFontInfo
Definition at line 1378 of file qfont.cpp.
Referenced by QFontDialogPrivate::_q_updateSample(), QPicturePaintEngine::drawTextItem(), fromString(), IFontToQFont(), qfontForCocoaFont(), qt_LOGFONTtoQFont(), qt_set_x11_resources(), QTextFormatPrivate::recalcFont(), QDeclarativeFontValueType::setStrikeout(), and setTextDecorationFromValues().
 {
     detach();
     d->strikeOut = enable;
     resolve_mask |= QFont::StrikeOutResolved;
 }
setStyle()
void QFont::setStyle (Style style)
Sets the style of the font to style.
See also
italic(), QFontInfo
Definition at line 1234 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), QFontDatabase::font(), fromString(), QGtkStylePrivate::getThemeFont(), parseShorthandFontProperty(), and setFontStyleFromValue().
 {
     detach();
     d->request.style = style;
     resolve_mask |= QFont::StyleResolved;
 }
setStyleHint()
void QFont::setStyleHint (StyleHint hint, StyleStrategy strategy = PreferDefault)
Sets the style hint and strategy to hint and strategy, respectively.
If these aren't set explicitly the style hint will default to AnyStyle and the style strategy to PreferDefault.
Qt does not support style hints on X11 since this information is not provided by the window system.
See also
StyleHint, styleHint(), StyleStrategy, styleStrategy(), QFontInfo
Definition at line 1554 of file qfont.cpp.
Referenced by fromString(), qt_set_x11_resources(), and QTextFormatPrivate::recalcFont().
 {
     detach();
     if ((resolve_mask & (QFont::StyleHintResolved | QFont::StyleStrategyResolved)) &&
          (StyleHint) d->request.styleHint == hint &&
          (StyleStrategy) d->request.styleStrategy == strategy)
         return;
     d->request.styleHint = hint;
     d->request.styleStrategy = strategy;
     resolve_mask |= QFont::StyleHintResolved;
     resolve_mask |= QFont::StyleStrategyResolved;
 #if defined(Q_WS_X11)
     d->request.addStyle.clear();
 #endif // Q_WS_X11
 }
setStyleName()
void QFont::setStyleName (const QString & styleName)
Sets the style name of the font to the given styleName.
Since
4.8
When set, other style properties like style() and weight() will be ignored for font matching.
See also
styleName()
Definition at line 967 of file qfont.cpp.
Referenced by QFontDatabase::font().
 {
     detach();
     d->request.styleName = styleName;
     resolve_mask |= QFont::StyleNameResolved;
 }
setStyleStrategy()
void QFont::setStyleStrategy (StyleStrategy s)
Sets the style strategy for the font to s.
See also
QFont::StyleStrategy
Definition at line 1578 of file qfont.cpp.
Referenced by qgl_use_font(), and QTextFormatPrivate::recalcFont().
 {
     detach();
     if ((resolve_mask & QFont::StyleStrategyResolved) &&
          s == (StyleStrategy)d->request.styleStrategy)
         return;
     d->request.styleStrategy = s;
     resolve_mask |= QFont::StyleStrategyResolved;
 }
setUnderline()
void QFont::setUnderline (bool enable)
If enable is true, sets underline on; otherwise sets underline off.
See also
underline(), QFontInfo
Definition at line 1331 of file qfont.cpp.
Referenced by QFontDialogPrivate::_q_updateSample(), QPicturePaintEngine::drawTextItem(), QPaintBufferEngine::drawTextItem(), fromString(), IFontToQFont(), QPainterReplayer::process(), qfontForCocoaFont(), qt_LOGFONTtoQFont(), qt_set_x11_resources(), QTextFormatPrivate::recalcFont(), setTextDecorationFromValues(), and QDeclarativeFontValueType::setUnderline().
 {
     detach();
     d->underline = enable;
     resolve_mask |= QFont::UnderlineResolved;
 }
setWeight()
void QFont::setWeight (int weight)
Sets the weight the font to weight, which should be a value from the QFont::Weight enumeration.
See also
weight(), QFontInfo
Definition at line 1278 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), fromString(), QGtkStylePrivate::getThemeFont(), parseShorthandFontProperty(), qt_LOGFONTtoQFont(), qt_set_x11_resources(), QTextFormatPrivate::recalcFont(), setFontWeightFromValue(), and QDeclarativeFontValueType::setWeight().
 {
     Q_ASSERT_X(weight >= 0 && weight <= 99, "QFont::setWeight", "Weight must be between 0 and 99");
     detach();
     d->request.weight = weight;
     resolve_mask |= QFont::WeightResolved;
 }
setWordSpacing()
void QFont::setWordSpacing (qreal spacing)
Sets the word spacing for the font to spacing.
Since
4.4
Word spacing changes the default spacing between individual words. A positive value increases the word spacing by a corresponding amount of pixels, while a negative value decreases the inter-word spacing accordingly.
Word spacing will not apply to writing systems, where indiviaul words are not separated by white space.
See also
wordSpacing(), setLetterSpacing()
Definition at line 1757 of file qfont.cpp.
Referenced by QTextFormatPrivate::recalcFont(), and QDeclarativeFontValueType::setWordSpacing().
 {
     const QFixed newSpacing = QFixed::fromReal(spacing);
     if ((resolve_mask & QFont::WordSpacingResolved) &&
         d->wordSpacing == newSpacing)
         return;
     detach();
     d->wordSpacing = newSpacing;
     resolve_mask |= QFont::WordSpacingResolved;
 }
stretch()
int QFont::stretch () const
Returns the stretch factor for the font.
See also
setStretch()
Definition at line 1618 of file qfont.cpp.
 {
     return d->request.stretch;
 }
strikeOut()
bool QFont::strikeOut () const
Returns true if strikeout has been set; otherwise returns false.
See also
setStrikeOut()
Definition at line 1367 of file qfont.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QTextLine::glyphs(), qfontForCocoaFont(), QFontToIFont(), qt_draw_decoration_for_glyphs(), QFontDialog::setCurrentFont(), QTextCharFormat::setFont(), QDeclarativeFontValueType::setOverline(), and toString().
 {
     return d->strikeOut;
 }
style()
QFont::Style QFont::style () const
Returns the style of the font.
See also
setStyle()
Definition at line 1223 of file qfont.cpp.
Referenced by QSvgFontStyle::apply(), QTextHtmlParserNode::applyCssDeclarations(), QAccessibleTextWidget::attributes(), QFontDialogPrivate::setFont(), setStyle(), QFontDatabase::styleString(), and toString().
 {
     return (QFont::Style)d->request.style;
 }
styleHint()
QFont::StyleHint QFont::styleHint () const
Returns the StyleHint.
The style hint affects the font matching algorithm. See QFont::StyleHint for the list of available hints.
See also
setStyleHint(), QFont::StyleStrategy QFontInfo::styleHint()
Definition at line 1460 of file qfont.cpp.
Referenced by QTextCharFormat::setFont(), and toString().
 {
     return (StyleHint) d->request.styleHint;
 }
styleName()
QString QFont::styleName () const
Returns the requested font style name, it will be used to match the font with irregular styles (that can't be normalized in other style properties).
Since
4.8
It depends on system font support, thus only works for Mac OS X and X11 so far. On Windows irregular styles will be added as separate font families so there is no need for this.
See also
setFamily() setStyle()
Definition at line 950 of file qfont.cpp.
Referenced by setStyleName(), and QFontDatabase::styleString().
 {
     return d->request.styleName;
 }
styleStrategy()
QFont::StyleStrategy QFont::styleStrategy () const
Returns the StyleStrategy.
The style strategy affects the font matching algorithm. See QFont::StyleStrategy for the list of available strategies.
See also
setStyleHint() QFont::StyleHint
Definition at line 1447 of file qfont.cpp.
Referenced by QTextFormatPrivate::recalcFont(), and QTextCharFormat::setFont().
 {
     return (StyleStrategy) d->request.styleStrategy;
 }
substitute()
QString QFont::substitute (const QString & familyName) static
Returns the first family name to be used whenever familyName is specified.
The lookup is case insensitive.
If there is no substitution for familyName, familyName is returned.
To obtain a list of substitutions use substitutes().
See also
setFamily() insertSubstitutions() insertSubstitution() removeSubstitution()
Definition at line 2116 of file qfont.cpp.
 {
     initFontSubst();
     QFontSubst *fontSubst = globalFontSubst();
     Q_ASSERT(fontSubst != 0);
     QFontSubst::ConstIterator it = fontSubst->constFind(familyName.toLower());
     if (it != fontSubst->constEnd() && !(*it).isEmpty())
         return (*it).first();
     return familyName;
 }
substitutes()
QStringList QFont::substitutes (const QString & familyName) static
Returns a list of family names to be used whenever familyName is specified.
The lookup is case insensitive.
If there is no substitution for familyName, an empty list is returned.
See also
substitute() insertSubstitutions() insertSubstitution() removeSubstitution()
Definition at line 2139 of file qfont.cpp.
Referenced by familyList(), and registerFont().
 {
     initFontSubst();
     QFontSubst *fontSubst = globalFontSubst();
     Q_ASSERT(fontSubst != 0);
     return fontSubst->value(familyName.toLower(), QStringList());
 }
substitutions()
QStringList QFont::substitutions () static
Returns a sorted list of substituted family names.
See also
insertSubstitution(), removeSubstitution(), substitute()
Definition at line 2234 of file qfont.cpp.
 {
     initFontSubst();
     QFontSubst *fontSubst = globalFontSubst();
     Q_ASSERT(fontSubst != 0);
     QStringList ret;
     QFontSubst::ConstIterator it = fontSubst->constBegin();
     while (it != fontSubst->constEnd()) {
         ret.append(it.key());
         ++it;
     }
     ret.sort();
     return ret;
 }
toString()
QString QFont::toString () const
Returns a description of the font.
The description is a comma-separated list of the attributes, perfectly suited for use in QSettings.
See also
fromString()
Definition at line 2344 of file qfont.cpp.
Referenced by key(), and operator<<().
 {
     const QChar comma(QLatin1Char(','));
     return family() + comma +
         QString::number(     pointSizeF()) + comma +
         QString::number(      pixelSize()) + comma +
         QString::number((int) styleHint()) + comma +
         QString::number(         weight()) + comma +
         QString::number((int)     style()) + comma +
         QString::number((int) underline()) + comma +
         QString::number((int) strikeOut()) + comma +
         QString::number((int)fixedPitch()) + comma +
         QString::number((int)   rawMode());
 }
underline()
bool QFont::underline () const
Returns true if underline has been set; otherwise returns false.
See also
setUnderline()
Definition at line 1320 of file qfont.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QAccessibleTextWidget::attributes(), QTextLine::glyphs(), qfontForCocoaFont(), QFontToIFont(), qt_draw_decoration_for_glyphs(), QFontDialog::setCurrentFont(), QTextCharFormat::setFont(), QDeclarativeFontValueType::setItalic(), QMenuPrivate::QMacMenuPrivate::syncAction(), and toString().
 {
     return d->underline;
 }
weight()
int QFont::weight () const
Returns the weight of the font which is one of the enumerated values from QFont::Weight.
See also
setWeight(), Weight, QFontInfo
Definition at line 1248 of file qfont.cpp.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QFont(), QFontToIFont(), QDeclarativeFontValueType::setBold(), QFontDialogPrivate::setFont(), QTextCharFormat::setFont(), setWeight(), QFontDatabase::styleString(), and toString().
 {
     return d->request.weight;
 }
wordSpacing()
qreal QFont::wordSpacing () const
Returns the word spacing for the font.
Since
4.4
See also
setWordSpacing(), setLetterSpacing()
Definition at line 1735 of file qfont.cpp.
Referenced by QTextCharFormat::setFont(), and QDeclarativeFontValueType::setLetterSpacing().
 {
     return d->wordSpacing.toReal();
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & s, const QFont & font) friend
Writes the font font to the data stream s.
(toString() writes to a text stream.)
See also
Format of the QDataStream operators
Definition at line 2439 of file qfont.cpp.
 {
     if (s.version() == 1) {
         s << font.d->request.family.toLatin1();
     } else {
         s << font.d->request.family;
     }
     if (s.version() >= QDataStream::Qt_4_0) {
         // 4.0
         double pointSize = font.d->request.pointSize;
         qint32 pixelSize = font.d->request.pixelSize;
         s << pointSize;
         s << pixelSize;
     } else if (s.version() <= 3) {
         qint16 pointSize = (qint16) (font.d->request.pointSize * 10);
         if (pointSize < 0) {
 #ifdef Q_WS_X11
             pointSize = (qint16)(font.d->request.pixelSize*720/QX11Info::appDpiY());
 #else
             pointSize = (qint16)QFontInfo(font).pointSize() * 10;
 #endif
         }
         s << pointSize;
     } else {
         s << (qint16) (font.d->request.pointSize * 10);
         s << (qint16) font.d->request.pixelSize;
     }
     s << (quint8) font.d->request.styleHint;
     if (s.version() >= QDataStream::Qt_3_1)
         s << (quint8) font.d->request.styleStrategy;
     s << (quint8) 0
       << (quint8) font.d->request.weight
       << get_font_bits(s.version(), font.d.data());
     if (s.version() >= QDataStream::Qt_4_3)
         s << (quint16)font.d->request.stretch;
     if (s.version() >= QDataStream::Qt_4_4)
         s << get_extended_font_bits(font.d.data());
     if (s.version() >= QDataStream::Qt_4_5) {
         s << font.d->letterSpacing.value();
         s << font.d->wordSpacing.value();
     }
     return s;
 }
operator>>
QDataStream & operator>> (QDataStream & s, QFont & font) friend
Reads the font font from the data stream s.
(fromString() reads from a text stream.)
See also
Format of the QDataStream operators
Definition at line 2497 of file qfont.cpp.
 {
     font.d = new QFontPrivate;
     font.resolve_mask = QFont::AllPropertiesResolved;
     quint8 styleHint, styleStrategy = QFont::PreferDefault, charSet, weight, bits;
     if (s.version() == 1) {
         QByteArray fam;
         s >> fam;
         font.d->request.family = QString::fromLatin1(fam);
     } else {
         s >> font.d->request.family;
     }
     if (s.version() >= QDataStream::Qt_4_0) {
         // 4.0
         double pointSize;
         qint32 pixelSize;
         s >> pointSize;
         s >> pixelSize;
         font.d->request.pointSize = qreal(pointSize);
         font.d->request.pixelSize = pixelSize;
     } else {
         qint16 pointSize, pixelSize = -1;
         s >> pointSize;
         if (s.version() >= 4)
             s >> pixelSize;
         font.d->request.pointSize = qreal(pointSize / 10.);
         font.d->request.pixelSize = pixelSize;
     }
     s >> styleHint;
     if (s.version() >= QDataStream::Qt_3_1)
         s >> styleStrategy;
     s >> charSet;
     s >> weight;
     s >> bits;
     font.d->request.styleHint = styleHint;
     font.d->request.styleStrategy = styleStrategy;
     font.d->request.weight = weight;
     set_font_bits(s.version(), bits, font.d.data());
     if (s.version() >= QDataStream::Qt_4_3) {
         quint16 stretch;
         s >> stretch;
         font.d->request.stretch = stretch;
     }
     if (s.version() >= QDataStream::Qt_4_4) {
         quint8 extendedBits;
         s >> extendedBits;
         set_extended_font_bits(extendedBits, font.d.data());
     }
     if (s.version() >= QDataStream::Qt_4_5) {
         int value;
         s >> value;
         font.d->letterSpacing.setValue(value);
         s >> value;
         font.d->wordSpacing.setValue(value);
     }
     return s;
 }
Q3TextFormatCollection
friend class Q3TextFormatCollection friend
Definition at line 321 of file qfont.h.
QAlphaPaintEngine
friend class QAlphaPaintEngine friend
Definition at line 329 of file qfont.h.
QApplication
friend class QApplication friend
Definition at line 318 of file qfont.h.
QCommandLinkButtonPrivate
friend class QCommandLinkButtonPrivate friend
Definition at line 335 of file qfont.h.
QFontDialogPrivate
friend class QFontDialogPrivate friend
Definition at line 311 of file qfont.h.
QFontEngine
friend class QFontEngine friend
Definition at line 336 of file qfont.h.
QFontInfo
friend class QFontInfo friend
Definition at line 314 of file qfont.h.
QFontMetrics
friend class QFontMetrics friend
Definition at line 312 of file qfont.h.
QFontMetricsF
friend class QFontMetricsF friend
Definition at line 313 of file qfont.h.
QFontPrivate
friend class QFontPrivate friend
Definition at line 310 of file qfont.h.
Referenced by QFont().
QGLContext
friend class QGLContext friend
Definition at line 327 of file qfont.h.
QPaintBufferEngine
friend class QPaintBufferEngine friend
Definition at line 334 of file qfont.h.
QPainter
friend class QPainter friend
Definition at line 315 of file qfont.h.
QPainterPath
friend class QPainterPath friend
Definition at line 330 of file qfont.h.
QPainterPrivate
friend class QPainterPrivate friend
Definition at line 316 of file qfont.h.
QPainterReplayer
friend class QPainterReplayer friend
Definition at line 333 of file qfont.h.
QPicturePaintEngine
friend class QPicturePaintEngine friend
Definition at line 332 of file qfont.h.
QPSPrintEngineFont
friend class QPSPrintEngineFont friend
Definition at line 317 of file qfont.h.
QScriptLine
friend struct QScriptLine friend
Definition at line 326 of file qfont.h.
QStackTextEngine
friend class QStackTextEngine friend
Definition at line 324 of file qfont.h.
QTextEngine
friend class QTextEngine friend
Definition at line 323 of file qfont.h.
QTextItemInt
friend class QTextItemInt friend
Definition at line 331 of file qfont.h.
QTextLayout
friend class QTextLayout friend
Definition at line 322 of file qfont.h.
QTextLine
friend class QTextLine friend
Definition at line 325 of file qfont.h.
QWidget
friend class QWidget friend
Definition at line 319 of file qfont.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 320 of file qfont.h.
QWin32PaintEngine
friend class QWin32PaintEngine friend
Definition at line 328 of file qfont.h.
Properties
d
QExplicitlySharedDataPointer<QFontPrivate> QFont::d private
Definition at line 343 of file qfont.h.
Referenced by QPainterPath::addText(), QTextEngine::calculateTabWidth(), capitalization(), defaultFamily(), detach(), QTextLine::draw(), QPicturePaintEngine::drawTextItem(), QTextEngine::elidedText(), exactMatch(), family(), fixedPitch(), QTextEngine::font(), QTextEngine::fontEngine(), freetypeFace(), fromString(), QTextLine::glyphs(), handle(), hintingPreference(), QTextItemInt::initWithScriptItem(), isCopyOf(), QTextEngine::itemize(), kerning(), letterSpacing(), letterSpacingType(), macFontID(), operator<(), operator=(), operator==(), overline(), pixelSize(), pointSize(), pointSize(), pointSizeF(), QFont(), QFontMetrics::QFontMetrics(), QFontMetricsF::QFontMetricsF(), qgl_use_font(), qt_x11_set_fallback_font_family(), QTextItemInt::QTextItemInt(), QTextLayout::QTextLayout(), rawMode(), resolve(), setCapitalization(), QTextFormatCollection::setDefaultFont(), QScriptLine::setDefaultHeight(), setFamily(), setFixedPitch(), QFontDialogPrivate::setFont(), setHintingPreference(), setKerning(), setLetterSpacing(), setOverline(), setPixelSize(), setPointSize(), setPointSizeF(), setRawMode(), setStretch(), setStrikeOut(), setStyle(), setStyleHint(), setStyleName(), setStyleStrategy(), setUnderline(), setWeight(), setWordSpacing(), QTextEngine::shapeText(), QFontPrivate::smallCapsFontPrivate(), stretch(), strikeOut(), style(), styleHint(), styleName(), styleStrategy(), underline(), weight(), and wordSpacing().
resolve_mask
uint QFont::resolve_mask private
Definition at line 344 of file qfont.h.
Referenced by QCommandLinkButtonPrivate::descriptionFont(), operator=(), QFont(), qt_x11_set_fallback_font_family(), resolve(), setCapitalization(), setFamily(), setFixedPitch(), setHintingPreference(), setKerning(), setLetterSpacing(), setOverline(), setPixelSize(), setPointSize(), setPointSizeF(), setStretch(), setStrikeOut(), setStyle(), setStyleHint(), setStyleName(), setStyleStrategy(), setUnderline(), setWeight(), setWordSpacing(), and QCommandLinkButtonPrivate::titleFont().
The documentation for this class was generated from the following files:
/src/gui/text/qfont.h
/src/gui/text/qfont.cpp
/src/gui/text/qfont_mac.cpp
/src/gui/text/qfont_qpa.cpp
/src/gui/text/qfont_qws.cpp
/src/gui/text/qfont_win.cpp
/src/gui/text/qfont_x11.cpp