Qt 4.8: QMacPasteboardMime Class Reference
QMacPasteboardMime Class Reference abstract
The QMacPasteboardMime class converts between a MIME type and a.
#include <qmime.h>
Public Types
enum QMacPasteboardMimeType {
MIME_DND =0x01, MIME_CLIP =0x02, MIME_QT_CONVERTOR =0x04, MIME_QT3_CONVERTOR =0x08,
MIME_ALL =MIME_DND|MIME_CLIP
}
Public Functions
virtual bool canConvert (const QString &mime, QString flav)=0
Returns true if the convertor can convert (both ways) between mime and flav; otherwise returns false.
virtual QList< QByteArray > convertFromMime (const QString &mime, QVariant data, QString flav)=0
Returns data converted from MIME type mime to Mac UTI flav.
virtual QString convertorName ()=0
Returns a name for the convertor.
virtual QVariant convertToMime (const QString &mime, QList< QByteArray > data, QString flav)=0
Returns data converted from Mac UTI flav to MIME type mime.
virtual QString flavorFor (const QString &mime)=0
Returns the Mac UTI used for MIME type mime, or 0 if this convertor does not support mime.
virtual QString mimeFor (QString flav)=0
Returns the MIME UTI used for Mac flavor flav, or 0 if this convertor does not support flav.
QMacPasteboardMime (char)
Constructs a new conversion object of type t, adding it to the globally accessed list of available convertors.
virtual ~QMacPasteboardMime ()
Destroys a conversion object, removing it from the global list of available convertors.
Static Public Functions
static QList< QMacPasteboardMime * > all (uchar)
Returns a list of all currently defined QMacPasteboardMime objects of type t.
static QMacPasteboardMime * convertor (uchar, const QString &mime, QString flav)
Returns the most-recently created QMacPasteboardMime of type t that can convert between the mime and flav formats.
static QString flavorToMime (uchar, QString flav)
Returns a MIME type of type t for flav, or 0 if none exists.
static void initialize ()
This is an internal function.
Properties
char type
Related Functions
(Note that these are not member functions.)
void qRegisterDraggedTypes (const QStringList &types)
Registers the given types as custom pasteboard types.
Detailed Description
The QMacPasteboardMime class converts between a MIME type and a.
Uniform Type Identifier (UTI) format.
Since
4.2
Qt's drag and drop and clipboard facilities use the MIME standard. On X11, this maps trivially to the Xdnd protocol. On Mac, although some applications use MIME to describe clipboard contents, it is more common to use Apple's UTI format.
QMacPasteboardMime's role is to bridge the gap between MIME and UTI; By subclasses this class, one can extend Qt's drag and drop and clipboard handling to convert to and from unsupported, or proprietary, UTI formats.
A subclass of QMacPasteboardMime will automatically be registered, and active, upon instantiation.
Qt has predefined support for the following UTIs:
public.utf8-plain-text - converts to "text/plain"
public.utf16-plain-text - converts to "text/plain"
public.html - converts to "text/html"
public.url - converts to "text/uri-list"
public.file-url - converts to "text/uri-list"
public.tiff - converts to "application/x-qt-image"
public.vcard - converts to "text/plain"
com.apple.traditional-mac-plain-text - converts to "text/plain"
com.apple.pict - converts to "application/x-qt-image"
When working with MIME data, Qt will interate through all instances of QMacPasteboardMime to find an instance that can convert to, or from, a specific MIME type. It will do this by calling canConvert() on each instance, starting with (and choosing) the last created instance first. The actual conversions will be done by using convertToMime() and convertFromMime().
Note
The API uses the term "flavor" in some cases. This is for backwards compatibility reasons, and should now be understood as UTIs.
Definition at line 141 of file qmime.h.
Enumerations
QMacPasteboardMimeType
enum QMacPasteboardMime::QMacPasteboardMimeType
Warning
This function is not part of the public interface.
Enumerator
MIME_DND
MIME_CLIP
MIME_QT_CONVERTOR
MIME_QT3_CONVERTOR
MIME_ALL
Definition at line 144 of file qmime.h.
                                 { MIME_DND=0x01,
                                   MIME_CLIP=0x02,
                                   MIME_QT_CONVERTOR=0x04,
                                   MIME_QT3_CONVERTOR=0x08,
                                   MIME_ALL=MIME_DND|MIME_CLIP
     };
Constructors and Destructors
QMacPasteboardMime()
QMacPasteboardMime::QMacPasteboardMime (char t) explicit
Constructs a new conversion object of type t, adding it to the globally accessed list of available convertors.
Definition at line 180 of file qmime_mac.cpp.
Referenced by QMacPasteboardMimeHTMLText::convertFromMime(), and QMacPasteboardMimeVCard::convertFromMime().
                                              : type(t)
 {
     globalMimeList()->append(this);
 }
~QMacPasteboardMime()
QMacPasteboardMime::~QMacPasteboardMime () virtual
Destroys a conversion object, removing it from the global list of available convertors.
Definition at line 189 of file qmime_mac.cpp.
 {
     if(!QApplication::closingDown())
         globalMimeList()->removeAll(this);
 }
Functions
all()
QList< QMacPasteboardMime * > QMacPasteboardMime::all (uchar t) static
Returns a list of all currently defined QMacPasteboardMime objects of type t.
Definition at line 1244 of file qmime_mac.cpp.
Referenced by QMacPasteboard::retrieveData(), and QMacPasteboard::setMimeData().
 {
     MimeList ret;
     MimeList *mimes = globalMimeList();
     for(MimeList::const_iterator it = mimes->constBegin(); it != mimes->constEnd(); ++it) {
         if((*it)->type & t)
             ret.append((*it));
     }
     return ret;
 }
canConvert()
bool QMacPasteboardMime::canConvert (const QString & mime, QString flav) pure virtual
Returns true if the convertor can convert (both ways) between mime and flav; otherwise returns false.
All subclasses must reimplement this pure virtual function.
Implemented in QMacPasteboardMimeVCard, QMacPasteboardMimeUrl, QMacPasteboardMimeFileUri, QMacPasteboardMimeTiff, QMacPasteboardMimeHTMLText, QMacPasteboardMimeUnicodeText, QMacPasteboardMimePlainText, QMacPasteboardMimeTypeName, and QMacPasteboardMimeAny.
Referenced by QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeTiff::convertFromMime(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QMacPasteboardMimeVCard::convertFromMime(), QMacPasteboardMimeHTMLText::convertToMime(), QMacPasteboardMimeTiff::convertToMime(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), QMacPasteboard::promiseKeeper(), QMacPasteboardMimeFileUri::QMacPasteboardMimeFileUri(), QMacPasteboardMimeHTMLText::QMacPasteboardMimeHTMLText(), QMacPasteboardMimePlainText::QMacPasteboardMimePlainText(), QMacPasteboardMimeTiff::QMacPasteboardMimeTiff(), QMacPasteboardMimeUnicodeText::QMacPasteboardMimeUnicodeText(), QMacPasteboardMimeUrl::QMacPasteboardMimeUrl(), QMacPasteboardMimeVCard::QMacPasteboardMimeVCard(), QMacPasteboardMimeAny::~QMacPasteboardMimeAny(), and QMacPasteboardMimeTypeName::~QMacPasteboardMimeTypeName().
convertFromMime()
QList< QByteArray > QMacPasteboardMime::convertFromMime (const QString & mime, QVariant data, QString flav) pure virtual
Returns data converted from MIME type mime to Mac UTI flav.
Note that Mac flavors must all be self-terminating. The return value may contain trailing data.
All subclasses must reimplement this pure virtual function.
Implemented in QMacPasteboardMimeVCard, QMacPasteboardMimeUrl, QMacPasteboardMimeFileUri, QMacPasteboardMimeTiff, QMacPasteboardMimeHTMLText, QMacPasteboardMimeUnicodeText, QMacPasteboardMimePlainText, QMacPasteboardMimeTypeName, and QMacPasteboardMimeAny.
Referenced by QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeVCard::convertFromMime(), QMacPasteboard::promiseKeeper(), QMacPasteboardMimeFileUri::QMacPasteboardMimeFileUri(), QMacPasteboardMimeHTMLText::QMacPasteboardMimeHTMLText(), QMacPasteboardMimePlainText::QMacPasteboardMimePlainText(), QMacPasteboardMimeTiff::QMacPasteboardMimeTiff(), QMacPasteboardMimeUnicodeText::QMacPasteboardMimeUnicodeText(), QMacPasteboardMimeUrl::QMacPasteboardMimeUrl(), QMacPasteboardMimeVCard::QMacPasteboardMimeVCard(), QMacPasteboard::setMimeData(), QMacPasteboardMimeAny::~QMacPasteboardMimeAny(), and QMacPasteboardMimeTypeName::~QMacPasteboardMimeTypeName().
convertor()
QMacPasteboardMime * QMacPasteboardMime::convertor (uchar t, const QString & mime, QString flav) static
Returns the most-recently created QMacPasteboardMime of type t that can convert between the mime and flav formats.
Returns 0 if no such convertor exists.
Definition at line 1196 of file qmime_mac.cpp.
 {
     MimeList *mimes = globalMimeList();
     for(MimeList::const_iterator it = mimes->constBegin(); it != mimes->constEnd(); ++it) {
 #ifdef DEBUG_MIME_MAPS
         qDebug("QMacPasteboardMime::convertor: seeing if %s (%d) can convert %s to %d[%c%c%c%c] [%d]",
                (*it)->convertorName().toLatin1().constData(),
                (*it)->type & t, mime.toLatin1().constData(),
                flav, (flav >> 24) & 0xFF, (flav >> 16) & 0xFF, (flav >> 8) & 0xFF, (flav) & 0xFF,
                (*it)->canConvert(mime,flav));
         for(int i = 0; i < (*it)->countFlavors(); ++i) {
             int f = (*it)->flavor(i);
             qDebug("  %d) %d[%c%c%c%c] [%s]", i, f,
                    (f >> 24) & 0xFF, (f >> 16) & 0xFF, (f >> 8) & 0xFF, (f) & 0xFF,
                    (*it)->convertorName().toLatin1().constData());
         }
 #endif
         if(((*it)->type & t) && (*it)->canConvert(mime, flav))
             return (*it);
     }
     return 0;
 }
convertorName()
QString QMacPasteboardMime::convertorName () pure virtual
Returns a name for the convertor.
All subclasses must reimplement this pure virtual function.
Implemented in QMacPasteboardMimeVCard, QMacPasteboardMimeUrl, QMacPasteboardMimeFileUri, QMacPasteboardMimeTiff, QMacPasteboardMimeHTMLText, QMacPasteboardMimeUnicodeText, QMacPasteboardMimePlainText, QMacPasteboardMimeTypeName, and QMacPasteboardMimeAny.
Referenced by QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeVCard::convertFromMime(), QMacPasteboard::promiseKeeper(), QMacPasteboardMimeFileUri::QMacPasteboardMimeFileUri(), QMacPasteboardMimeHTMLText::QMacPasteboardMimeHTMLText(), QMacPasteboardMimePlainText::QMacPasteboardMimePlainText(), QMacPasteboardMimeTiff::QMacPasteboardMimeTiff(), QMacPasteboardMimeUnicodeText::QMacPasteboardMimeUnicodeText(), QMacPasteboardMimeUrl::QMacPasteboardMimeUrl(), QMacPasteboardMimeVCard::QMacPasteboardMimeVCard(), QMacPasteboard::retrieveData(), QMacPasteboard::setMimeData(), QMacPasteboardMimeAny::~QMacPasteboardMimeAny(), and QMacPasteboardMimeTypeName::~QMacPasteboardMimeTypeName().
convertToMime()
QVariant QMacPasteboardMime::convertToMime (const QString & mime, QList< QByteArray > data, QString flav) pure virtual
Returns data converted from Mac UTI flav to MIME type mime.
Note that Mac flavors must all be self-terminating. The input data may contain trailing data.
All subclasses must reimplement this pure virtual function.
Implemented in QMacPasteboardMimeVCard, QMacPasteboardMimeUrl, QMacPasteboardMimeFileUri, QMacPasteboardMimeTiff, QMacPasteboardMimeHTMLText, QMacPasteboardMimeUnicodeText, QMacPasteboardMimePlainText, QMacPasteboardMimeTypeName, and QMacPasteboardMimeAny.
Referenced by QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeVCard::convertFromMime(), QMacPasteboardMimeFileUri::QMacPasteboardMimeFileUri(), QMacPasteboardMimeHTMLText::QMacPasteboardMimeHTMLText(), QMacPasteboardMimePlainText::QMacPasteboardMimePlainText(), QMacPasteboardMimeTiff::QMacPasteboardMimeTiff(), QMacPasteboardMimeUnicodeText::QMacPasteboardMimeUnicodeText(), QMacPasteboardMimeUrl::QMacPasteboardMimeUrl(), QMacPasteboardMimeVCard::QMacPasteboardMimeVCard(), QMacPasteboard::retrieveData(), QMacPasteboardMimeAny::~QMacPasteboardMimeAny(), and QMacPasteboardMimeTypeName::~QMacPasteboardMimeTypeName().
flavorFor()
QString QMacPasteboardMime::flavorFor (const QString & mime) pure virtual
Returns the Mac UTI used for MIME type mime, or 0 if this convertor does not support mime.
All subclasses must reimplement this pure virtual function.
Implemented in QMacPasteboardMimeVCard, QMacPasteboardMimeUrl, QMacPasteboardMimeFileUri, QMacPasteboardMimeTiff, QMacPasteboardMimeHTMLText, QMacPasteboardMimeUnicodeText, QMacPasteboardMimePlainText, QMacPasteboardMimeTypeName, and QMacPasteboardMimeAny.
Referenced by QMacPasteboardMimePlainText::canConvert(), QMacPasteboardMimeUnicodeText::canConvert(), QMacPasteboardMimeHTMLText::canConvert(), QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeVCard::convertFromMime(), QMacPasteboardMimeFileUri::QMacPasteboardMimeFileUri(), QMacPasteboardMimeHTMLText::QMacPasteboardMimeHTMLText(), QMacPasteboardMimePlainText::QMacPasteboardMimePlainText(), QMacPasteboardMimeTiff::QMacPasteboardMimeTiff(), QMacPasteboardMimeUnicodeText::QMacPasteboardMimeUnicodeText(), QMacPasteboardMimeUrl::QMacPasteboardMimeUrl(), QMacPasteboardMimeVCard::QMacPasteboardMimeVCard(), QMacPasteboard::retrieveData(), QMacPasteboard::setMimeData(), QMacPasteboard::~QMacPasteboard(), QMacPasteboardMimeAny::~QMacPasteboardMimeAny(), and QMacPasteboardMimeTypeName::~QMacPasteboardMimeTypeName().
flavorToMime()
QString QMacPasteboardMime::flavorToMime (uchar t, QString flav) static
Returns a MIME type of type t for flav, or 0 if none exists.
Definition at line 1221 of file qmime_mac.cpp.
Referenced by QMacPasteboard::formats(), and QMacPasteboard::hasFormat().
 {
     MimeList *mimes = globalMimeList();
     for(MimeList::const_iterator it = mimes->constBegin(); it != mimes->constEnd(); ++it) {
 #ifdef DEBUG_MIME_MAPS
         qDebug("QMacMIme::flavorToMime: attempting %s (%d) for flavor %d[%c%c%c%c] [%s]",
                (*it)->convertorName().toLatin1().constData(),
                (*it)->type & t, flav, (flav >> 24) & 0xFF, (flav >> 16) & 0xFF, (flav >> 8) & 0xFF, (flav) & 0xFF,
                (*it)->mimeFor(flav).toLatin1().constData());
 #endif
         if((*it)->type & t) {
             QString mimeType = (*it)->mimeFor(flav);
             if(!mimeType.isNull())
                 return mimeType;
         }
     }
     return QString();
 }
initialize()
void QMacPasteboardMime::initialize () static
This is an internal function.
Warning
This function is not part of the public interface.
Definition at line 1162 of file qmime_mac.cpp.
Referenced by qt_init().
 {
     if(globalMimeList()->isEmpty()) {
         qAddPostRoutine(cleanup_mimes);
         //standard types that we wrap
         new QMacPasteboardMimeTiff;
 #ifdef Q_WS_MAC32
         // 10.6 does automatic synthesis to and from PICT to standard image types (like TIFF),
         // so don't bother doing it ourselves, especially since it's not available in 64-bit.
         if (QSysInfo::MacintoshVersion < QSysInfo::MV_10_6)
             new QMacPasteboardMimePict;
 #endif
         new QMacPasteboardMimeUnicodeText;
         new QMacPasteboardMimePlainText;
         new QMacPasteboardMimeHTMLText;
         new QMacPasteboardMimeFileUri;
         new QMacPasteboardMimeUrl;
         new QMacPasteboardMimeTypeName;
         new QMacPasteboardMimeVCard;
         //make sure our "non-standard" types are always last! --Sam
         new QMacPasteboardMimeAny;
 #ifdef QT3_SUPPORT
         new QMacPasteboardMimeQt3Any;
 #endif
     }
 }
mimeFor()
QString QMacPasteboardMime::mimeFor (QString flav) pure virtual
Returns the MIME UTI used for Mac flavor flav, or 0 if this convertor does not support flav.
All subclasses must reimplement this pure virtual function.
Implemented in QMacPasteboardMimeVCard, QMacPasteboardMimeUrl, QMacPasteboardMimeFileUri, QMacPasteboardMimeTiff, QMacPasteboardMimeHTMLText, QMacPasteboardMimeUnicodeText, QMacPasteboardMimePlainText, QMacPasteboardMimeTypeName, and QMacPasteboardMimeAny.
Referenced by QMacPasteboardMimeAny::canConvert(), QMacPasteboardMimeVCard::canConvert(), QMacPasteboardMimeHTMLText::convertFromMime(), QMacPasteboardMimeVCard::convertFromMime(), QMacPasteboardMimeFileUri::QMacPasteboardMimeFileUri(), QMacPasteboardMimeHTMLText::QMacPasteboardMimeHTMLText(), QMacPasteboardMimePlainText::QMacPasteboardMimePlainText(), QMacPasteboardMimeTiff::QMacPasteboardMimeTiff(), QMacPasteboardMimeUnicodeText::QMacPasteboardMimeUnicodeText(), QMacPasteboardMimeUrl::QMacPasteboardMimeUrl(), QMacPasteboardMimeVCard::QMacPasteboardMimeVCard(), QMacPasteboardMimeAny::~QMacPasteboardMimeAny(), and QMacPasteboardMimeTypeName::~QMacPasteboardMimeTypeName().
Friends and Related Functions
qRegisterDraggedTypes()
void qRegisterDraggedTypes (const QStringList & types) related
Registers the given types as custom pasteboard types.
This function should be called to enable the Drag and Drop events for custom pasteboard types on Cocoa implementations. This is required in addition to a QMacPasteboardMime subclass implementation. By default drag and drop is enabled for all standard pasteboard types.
See also
QMacPasteboardMime
Properties
type
char QMacPasteboardMime::type private
Definition at line 142 of file qmime.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qmime.h
/src/gui/kernel/qmime_mac.cpp