Qt 4.8: QXIMInputContext Class Reference
QXIMInputContext Class Reference
#include <qximinputcontext_p.h>
Classes
struct ICData
Public Functions
void close_xim ()
void create_xim ()
ICData * icData () const
QString identifierName ()
This function must be implemented in any subclasses to return the identifier name of the input method.
bool isComposing () const
This function indicates whether InputMethodStart event had been sent to the current focus widget.
QString language ()
This function must be implemented in any subclasses to return a language code (e.
void mouseHandler (int x, QMouseEvent *event)
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
QXIMInputContext ()
void reset ()
This function can be reimplemented in a subclass to reset the state of the input method.
void setFocusWidget (QWidget *w)
Sets the widget that has an input focus for this input context.
void update ()
This virtual function is called when a state in the focus widget has changed.
void widgetDestroyed (QWidget *w)
This virtual function is called when the specified widget is destroyed.
~QXIMInputContext ()
Public Functions inherited from QInputContext
virtual QList< QAction * > actions ()
This is a preliminary interface for Qt 4.
virtual bool filterEvent (const QEvent *event)
This function can be reimplemented in a subclass to filter input events.
QWidget * focusWidget () const
Returns the widget that has an input focus for this input context.
virtual QFont font () const
Returns the font of the current input widget.
QInputContext (QObject *parent=0)
Constructs an input context with the given parent.
void sendEvent (const QInputMethodEvent &event)
Sends an input method event specified by event to the current focus widget.
QTextFormat standardFormat (StandardFormat s) const
Returns a QTextFormat object that specifies the format for component s.
virtual ~QInputContext ()
Destroys the input context.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool x11FilterEvent (QWidget *keywidget, XEvent *event)
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
ICData * createICData (QWidget *w)
Properties
QString _language
XIM xim
QHash< WId, ICData * > ximData
Static Private Attributes
static XIMStyle xim_style = 0
Additional Inherited Members
Public Types inherited from QInputContext
enum StandardFormat { PreeditFormat, SelectionFormat }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 90 of file qximinputcontext_p.h.
Constructors and Destructors
QXIMInputContext()
QXIMInputContext::QXIMInputContext ()
Definition at line 352 of file qximinputcontext_x11.cpp.
 {
     if (!qt_xim_preferred_style) // no configured input style, use the default
         qt_xim_preferred_style = xim_default_style;
     xim = 0;
     QByteArray ximServerName(qt_ximServer);
     if (qt_ximServer)
         ximServerName.prepend("@im=");
     else
         ximServerName = "";
     if (!XSupportsLocale())
 #ifndef QT_NO_DEBUG
         qWarning("Qt: Locale not supported on X server")
 #endif
             ;
 #ifdef USE_X11R6_XIM
     else if (XSetLocaleModifiers (ximServerName.constData()) == 0)
         qWarning("Qt: Cannot set locale modifiers: %s", ximServerName.constData());
     else
         XRegisterIMInstantiateCallback(X11->display, 0, 0, 0,
                                        (XIMProc) xim_create_callback, reinterpret_cast<char *>(this));
 #else // !USE_X11R6_XIM
     else if (XSetLocaleModifiers ("") == 0)
         qWarning("Qt: Cannot set locale modifiers");
     else
         QXIMInputContext::create_xim();
 #endif // USE_X11R6_XIM
 #ifndef QT_NO_XKB
     if (X11->use_xkb) {
         QByteArray layoutName;
         QByteArray variantName;
         Atom type = XNone;
         int format = 0;
         ulong nitems = 0;
         ulong bytesAfter = 0;
         uchar *data = 0;
         if (XGetWindowProperty(X11->display, RootWindow(X11->display, 0), ATOM(_XKB_RULES_NAMES), 0, 1024,
                                false, XA_STRING, &type, &format, &nitems, &bytesAfter, &data) == Success
             && type == XA_STRING && format == 8 && nitems > 2) {
             char *names[5] = { 0, 0, 0, 0, 0 };
             char *p = reinterpret_cast<char *>(data), *end = p + nitems;
             int i = 0;
             do {
                 names[i++] = p;
                 p += qstrlen(p) + 1;
             } while (p < end);
             QList<QByteArray> layoutNames = QByteArray::fromRawData(names[2], qstrlen(names[2])).split(',');
             QList<QByteArray> variantNames = QByteArray::fromRawData(names[3], qstrlen(names[3])).split(',');
             for (int i = 0; i < qMin(layoutNames.count(), variantNames.count()); ++i  ) {
                 QByteArray variantName = variantNames.at(i);
                 const int dashPos = variantName.indexOf("-");
                 if (dashPos >= 0)
                     variantName.truncate(dashPos);
                 QLocale keyboardInputLocale = q_getKeyboardLocale(layoutNames.at(i), variantName);
                 if (keyboardInputLocale.textDirection() == Qt::RightToLeft)
                     qt_use_rtl_extensions = true;
             }
         }
         if (data)
             XFree(data);
     }
 #endif // QT_NO_XKB
 }
~QXIMInputContext()
QXIMInputContext::~QXIMInputContext ()
Definition at line 539 of file qximinputcontext_x11.cpp.
Referenced by update().
 {
     XIM old_xim = xim; // close_xim clears xim pointer.
     close_xim();
     if (old_xim)
         XCloseIM(old_xim);
 }
Functions
close_xim()
void QXIMInputContext::close_xim ()
Warning
This function is not part of the public interface. Closes the application input method.
Definition at line 512 of file qximinputcontext_x11.cpp.
Referenced by create_xim(), and ~QXIMInputContext().
 {
     for(QHash<WId, ICData *>::const_iterator i = ximData.constBegin(),
                                              e = ximData.constEnd(); i != e; ++i) {
         ICData *data = i.value();
         if (data->ic)
             XDestroyIC(data->ic);
         delete data;
     }
     ximData.clear();
     if ( --fontsetRefCount == 0 ) {
     Display *dpy = X11->display;
     for ( int i = 0; i < 8; i++ ) {
         if ( fontsetCache[i] && fontsetCache[i] != (XFontSet)-1 ) {
         XFreeFontSet(dpy, fontsetCache[i]);
         fontsetCache[i] = 0;
         }
     }
     }
     setFocusWidget(0);
     xim = 0;
 }
create_xim()
void QXIMInputContext::create_xim ()
Warning
This function is not part of the public interface. Creates the application input method.
Definition at line 428 of file qximinputcontext_x11.cpp.
Referenced by QXIMInputContext().
 {
     ++fontsetRefCount;
 #ifndef QT_NO_XIM
     xim = XOpenIM(X11->display, 0, 0, 0);
     if (xim) {
 #ifdef USE_X11R6_XIM
         XIMCallback destroy;
         destroy.callback = (XIMProc) xim_destroy_callback;
         destroy.client_data = XPointer(this);
         if (XSetIMValues(xim, XNDestroyCallback, &destroy, (char *) 0) != 0)
             qWarning("Xlib doesn't support destroy callback");
 #endif // USE_X11R6_XIM
         XIMStyles *styles = 0;
         XGetIMValues(xim, XNQueryInputStyle, &styles, (char *) 0, (char *) 0);
         if (styles) {
             int i;
             for (i = 0; !xim_style && i < styles->count_styles; i++) {
                 if (styles->supported_styles[i] == qt_xim_preferred_style) {
                     xim_style = qt_xim_preferred_style;
                     break;
                 }
             }
             // if the preferred input style couldn't be found, look for
             // Nothing
             for (i = 0; !xim_style && i < styles->count_styles; i++) {
                 if (styles->supported_styles[i] == (XIMPreeditNothing | XIMStatusNothing)) {
                     xim_style = XIMPreeditNothing | XIMStatusNothing;
                     break;
                 }
             }
             // ... and failing that, None.
             for (i = 0; !xim_style && i < styles->count_styles; i++) {
                 if (styles->supported_styles[i] == (XIMPreeditNone |
                                                     XIMStatusNone)) {
                     xim_style = XIMPreeditNone | XIMStatusNone;
                     break;
                 }
             }
             // qDebug("QApplication: using im style %lx", xim_style);
             XFree((char *)styles);
         }
         if (xim_style) {
 #ifdef USE_X11R6_XIM
             XUnregisterIMInstantiateCallback(X11->display, 0, 0, 0,
                                              (XIMProc) xim_create_callback, reinterpret_cast<char *>(this));
 #endif // USE_X11R6_XIM
             if (QWidget *focusWidget = QApplication::focusWidget()) {
                 // reinitialize input context after the input method
                 // server (like SCIM) has been launched without
                 // requiring the user to manually switch focus.
                 if (focusWidget->testAttribute(Qt::WA_InputMethodEnabled)
                     && focusWidget->testAttribute(Qt::WA_WState_Created)
                     && focusWidget->isEnabled())
                     setFocusWidget(focusWidget);
             }
             // following code fragment is not required for immodule
             // version of XIM
 #if 0
             QWidgetList list = qApp->topLevelWidgets();
             for (int i = 0; i < list.size(); ++i) {
                 QWidget *w = list.at(i);
                 w->d->createTLSysExtra();
             }
 #endif
         } else {
             // Give up
             qWarning("No supported input style found."
                      "  See InputMethod documentation.");
             close_xim();
         }
     }
 #endif // QT_NO_XIM
 }
createICData()
QXIMInputContext::ICData * QXIMInputContext::createICData (QWidget * w) private
Definition at line 737 of file qximinputcontext_x11.cpp.
Referenced by setFocusWidget().
 {
     ICData *data = new ICData;
     data->widget = w;
     data->preeditEmpty = true;
     XVaNestedList preedit_attr = 0;
     XIMCallback startcallback, drawcallback, donecallback;
     QFont font = w->font();
     data->fontset = getFontSet(font);
     if (xim_style & XIMPreeditArea) {
         XRectangle rect;
         rect.x = 0;
         rect.y = 0;
         rect.width = w->width();
         rect.height = w->height();
         preedit_attr = XVaCreateNestedList(0,
                                            XNArea, &rect,
                                            XNFontSet, data->fontset,
                                            (char *) 0);
     } else if (xim_style & XIMPreeditPosition) {
         XPoint spot;
         spot.x = 1;
         spot.y = 1;
         preedit_attr = XVaCreateNestedList(0,
                                            XNSpotLocation, &spot,
                                            XNFontSet, data->fontset,
                                            (char *) 0);
     } else if (xim_style & XIMPreeditCallbacks) {
         startcallback.client_data = (XPointer) this;
         startcallback.callback = (XIMProc) xic_start_callback;
         drawcallback.client_data = (XPointer) this;
         drawcallback.callback = (XIMProc)xic_draw_callback;
         donecallback.client_data = (XPointer) this;
         donecallback.callback = (XIMProc) xic_done_callback;
         preedit_attr = XVaCreateNestedList(0,
                                            XNPreeditStartCallback, &startcallback,
                                            XNPreeditDrawCallback, &drawcallback,
                                            XNPreeditDoneCallback, &donecallback,
                                            (char *) 0);
     }
     if (preedit_attr) {
         data->ic = XCreateIC(xim,
                              XNInputStyle, xim_style,
                              XNClientWindow, w->effectiveWinId(),
                              XNPreeditAttributes, preedit_attr,
                              (char *) 0);
         XFree(preedit_attr);
     } else {
         data->ic = XCreateIC(xim,
                              XNInputStyle, xim_style,
                              XNClientWindow, w->effectiveWinId(),
                              (char *) 0);
     }
     if (data->ic) {
         // when resetting the input context, preserve the input state
         (void) XSetICValues(data->ic, XNResetState, XIMPreserveState, (char *) 0);
     } else {
         qWarning("Failed to create XIC");
     }
     ximData[w->effectiveWinId()] = data;
     return data;
 }
icData()
QXIMInputContext::ICData * QXIMInputContext::icData () const
Definition at line 294 of file qximinputcontext_x11.cpp.
Referenced by xic_draw_callback(), and xic_start_callback().
 {
     if (QWidget *w = focusWidget())
         return ximData.value(w->effectiveWinId());
     return 0;
 }
identifierName()
QString QXIMInputContext::identifierName () virtual
This function must be implemented in any subclasses to return the identifier name of the input method.
Return value is the name to identify and specify input methods for the input method switching mechanism and so on. The name has to be consistent with QInputContextPlugin::keys(). The name has to consist of ASCII characters only.
There are two different names with different responsibility in the input method domain. This function returns one of them. Another name is called 'display name' that stands for the name for endusers appeared in a menu and so on.
See also
QInputContextPlugin::keys(), QInputContextPlugin::displayName()
Implements QInputContext.
Definition at line 548 of file qximinputcontext_x11.cpp.
Referenced by update().
 {
     // the name should be "xim" rather than "XIM" to be consistent
     // with corresponding immodule of GTK+
     return QLatin1String("xim");
 }
isComposing()
bool QXIMInputContext::isComposing () const virtual
This function indicates whether InputMethodStart event had been sent to the current focus widget.
It is ensured that an input context can send InputMethodCompose or InputMethodEnd event safely if this function returned true.
The state is automatically being tracked through sendEvent().
See also
sendEvent()
Implements QInputContext.
Definition at line 628 of file qximinputcontext_x11.cpp.
Referenced by update(), and x11FilterEvent().
 {
     QWidget *w = focusWidget();
     if (!w)
         return false;
     ICData *data = ximData.value(w->effectiveWinId());
     if (!data)
         return false;
     return data->composing;
 }
language()
QString QXIMInputContext::language () virtual
This function must be implemented in any subclasses to return a language code (e.
g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...) of the input context. If the input context can handle multiple languages, return the currently used one. The name has to be consistent with QInputContextPlugin::language().
This information will be used by language tagging feature in QInputMethodEvent. It is required to distinguish unified han characters correctly. It enables proper font and character code handling. Suppose CJK-awared multilingual web browser (that automatically modifies fonts in CJK-mixed text) and XML editor (that automatically inserts lang attr).
Implements QInputContext.
Definition at line 556 of file qximinputcontext_x11.cpp.
Referenced by setFocusWidget(), and update().
 {
     QString language;
     if (xim) {
         QByteArray locale(XLocaleOfIM(xim));
         if (locale.startsWith("zh")) {
             // Chinese language should be formed as "zh_CN", "zh_TW", "zh_HK"
             language = QLatin1String(locale.left(5));
         } else {
             // other languages should be two-letter ISO 639 language code
             language = QLatin1String(locale.left(2));
         }
     }
     return language;
 }
mouseHandler()
void QXIMInputContext::mouseHandler (int x, QMouseEvent * event) virtual
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
You can use the function to implement mouse-oriented user interface such as text selection or popup menu for candidate selection.
The x parameter is the offset within the string that was sent with the InputMethodCompose event. The alteration boundary of x is ensured as character boundary of preedit string accurately.
The event parameter is the event that was sent to the editor widget. The event type is QEvent::MouseButtonPress, QEvent::MouseButtonRelease, QEvent::MouseButtonDblClick or QEvent::MouseMove. The event's button and state indicate the kind of operation that was performed.
Reimplemented from QInputContext.
Definition at line 612 of file qximinputcontext_x11.cpp.
Referenced by update().
 {
     if(e->type() != QEvent::MouseButtonPress)
         return;
     XIM_DEBUG("QXIMInputContext::mouseHandler pos=%d", pos);
     if (QWidget *w = focusWidget()) {
         ICData *data = ximData.value(w->effectiveWinId());
         if (!data)
             return;
         if (pos < 0 || pos > data->text.length())
             reset();
         // ##### handle mouse position
     }
 }
reset()
void QXIMInputContext::reset () virtual
This function can be reimplemented in a subclass to reset the state of the input method.
This function is called by several widgets to reset input state. For example, a text widget call this function before inserting a text to make widget ready to accept a text.
Default implementation is sufficient for simple input method. You can override this function to reset external input method engines in complex input method. In the case, call QInputContext::reset() to ensure proper termination of inputting.
In a reimplementation of reset(), you must not send any QInputMethodEvent containing preedit text. You can only commit string and attributes; otherwise, you risk breaking input state consistency.
Implements QInputContext.
Definition at line 573 of file qximinputcontext_x11.cpp.
Referenced by mouseHandler(), setFocusWidget(), and update().
 {
     QWidget *w = focusWidget();
     if (!w)
         return;
     ICData *data = ximData.value(w->effectiveWinId());
     if (!data)
         return;
     if (data->ic) {
         char *mb = XmbResetIC(data->ic);
         QInputMethodEvent e;
         if (mb) {
             e.setCommitString(QString::fromLocal8Bit(mb));
             XFree(mb);
             data->preeditEmpty = false; // force sending an event
         }
         if (!data->preeditEmpty) {
             sendEvent(e);
             update();
         }
     }
     data->clear();
 }
setFocusWidget()
void QXIMInputContext::setFocusWidget (QWidget * widget) virtual
Sets the widget that has an input focus for this input context.
Warning
Ordinary input methods must not call this function directly.
See also
focusWidget()
Reimplemented from QInputContext.
Definition at line 640 of file qximinputcontext_x11.cpp.
Referenced by close_xim(), create_xim(), and update().
 {
     if (!xim)
         return;
     QWidget *oldFocus = focusWidget();
     if (oldFocus == w)
         return;
     if (language() != QLatin1String("ja"))
         reset();
     if (oldFocus) {
         ICData *data = ximData.value(oldFocus->effectiveWinId());
         if (data && data->ic)
             XUnsetICFocus(data->ic);
     }
     QInputContext::setFocusWidget(w);
     if (!w || w->inputMethodHints() & (Qt::ImhExclusiveInputMask | Qt::ImhHiddenText))
         return;
     ICData *data = ximData.value(w->effectiveWinId());
     if (!data)
         data = createICData(w);
     if (data->ic)
         XSetICFocus(data->ic);
     update();
 }
update()
void QXIMInputContext::update () virtual
This virtual function is called when a state in the focus widget has changed.
QInputContext can then use QWidget::inputMethodQuery() to query the new state of the widget.
Reimplemented from QInputContext.
Definition at line 809 of file qximinputcontext_x11.cpp.
Referenced by reset(), setFocusWidget(), and x11FilterEvent().
 {
     QWidget *w = focusWidget();
     if (!w)
         return;
     ICData *data = ximData.value(w->effectiveWinId());
     if (!data || !data->ic)
         return;
     QRect r = w->inputMethodQuery(Qt::ImMicroFocus).toRect();
     QPoint p;
     if (w->nativeParentWidget())
         p = w->mapTo(w->nativeParentWidget(), QPoint((r.left() + r.right() + 1)/2, r.bottom()));
     else
         p = QPoint((r.left() + r.right() + 1)/2, r.bottom());
     XPoint spot;
     spot.x = p.x();
     spot.y = p.y();
     r = w->rect();
     XRectangle area;
     area.x = r.x();
     area.y = r.y();
     area.width = r.width();
     area.height = r.height();
     XFontSet fontset = getFontSet(qvariant_cast<QFont>(w->inputMethodQuery(Qt::ImFont)));
     if (data->fontset == fontset)
         fontset = 0;
     else
         data->fontset = fontset;
     XVaNestedList preedit_attr;
     if (fontset)
         preedit_attr = XVaCreateNestedList(0,
                                            XNSpotLocation, &spot,
                                            XNArea, &area,
                                            XNFontSet, fontset,
                                            (char *) 0);
     else
         preedit_attr = XVaCreateNestedList(0,
                                            XNSpotLocation, &spot,
                                            XNArea, &area,
                                            (char *) 0);
     XSetICValues(data->ic, XNPreeditAttributes, preedit_attr, (char *) 0);
     XFree(preedit_attr);
 }
widgetDestroyed()
void QXIMInputContext::widgetDestroyed (QWidget * widget) virtual
This virtual function is called when the specified widget is destroyed.
The widget is a widget on which this input context is installed.
Reimplemented from QInputContext.
Definition at line 599 of file qximinputcontext_x11.cpp.
Referenced by update().
 {
     QInputContext::widgetDestroyed(w);
     ICData *data = ximData.take(w->effectiveWinId());
     if (!data)
         return;
     data->clear();
     if (data->ic)
         XDestroyIC(data->ic);
     delete data;
 }
x11FilterEvent()
bool QXIMInputContext::x11FilterEvent (QWidget * keywidget, XEvent * event) protected virtual
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
Otherwise, this function must not.
This function is designed to filter raw key events for XIM, but other input methods may use this to implement some special features such as distinguishing Shift_L and Shift_R.
Return true if the event has been consumed. Otherwise, the unfiltered event will be translated into QEvent and forwarded to filterEvent(). Filtering at both x11FilterEvent() and filterEvent() in single input method is allowed.
keywidget is a client widget into which a text is inputted. event is inputted XEvent.
See also
filterEvent()
Reimplemented from QInputContext.
Definition at line 673 of file qximinputcontext_x11.cpp.
Referenced by update().
 {
     int xkey_keycode = event->xkey.keycode;
     if (!keywidget->testAttribute(Qt::WA_WState_Created))
         return false;
     if (XFilterEvent(event, keywidget->effectiveWinId())) {
         qt_ximComposingKeycode = xkey_keycode; // ### not documented in xlib
         update();
         return true;
     }
     if (event->type != XKeyPress || event->xkey.keycode != 0)
         return false;
     QWidget *w = focusWidget();
     if (keywidget != w)
         return false;
     ICData *data = ximData.value(w->effectiveWinId());
     if (!data)
         return false;
     // input method has sent us a commit string
     QByteArray string;
     string.resize(513);
     KeySym key;    // unused
     Status status; // unused
     QString text;
     int count = XmbLookupString(data->ic, &event->xkey, string.data(), string.size(),
                                 &key, &status);
     if (status == XBufferOverflow) {
         string.resize(count + 1);
         count = XmbLookupString(data->ic, &event->xkey, string.data(), string.size(),
                                 &key, &status);
     }
     if (count > 0) {
         // XmbLookupString() gave us some text, convert it to unicode
         text = qt_input_mapper->toUnicode(string.constData() , count);
         if (text.isEmpty()) {
             // codec couldn't convert to unicode? this can happen when running in the
             // C locale (or with no LANG set). try converting from latin-1
             text = QString::fromLatin1(string.constData(), count);
         }
     }
 #if 0
     if (!(xim_style & XIMPreeditCallbacks) || !isComposing()) {
         // ############### send a regular key event here!
         ;
     }
 #endif
     QInputMethodEvent e;
     e.setCommitString(text);
     sendEvent(e);
     data->clear();
     update();
     return true;
 }
Properties
_language
QString QXIMInputContext::_language private
Definition at line 131 of file qximinputcontext_p.h.
xim
XIM QXIMInputContext::xim private
Definition at line 132 of file qximinputcontext_p.h.
Referenced by close_xim(), create_xim(), createICData(), language(), QXIMInputContext(), setFocusWidget(), and ~QXIMInputContext().
xim_style
XIMStyle QXIMInputContext::xim_style = 0 static private
Definition at line 129 of file qximinputcontext_p.h.
Referenced by create_xim(), createICData(), and x11FilterEvent().
ximData
QHash<WId, ICData *> QXIMInputContext::ximData private
Definition at line 133 of file qximinputcontext_p.h.
Referenced by close_xim(), icData(), isComposing(), mouseHandler(), reset(), setFocusWidget(), update(), widgetDestroyed(), and x11FilterEvent().
The documentation for this class was generated from the following files:
/src/gui/inputmethod/qximinputcontext_p.h
/src/gui/inputmethod/qximinputcontext_x11.cpp