Qt 4.8: QDeclarativeEnginePrivate Class Reference
QDeclarativeEnginePrivate Class Reference
#include <qdeclarativeengine_p.h>
Classes
struct CapturedProperty
struct SimpleList
Public Functions
QDeclarativePropertyCache * cache (QObject *obj)
Returns a QDeclarativePropertyCache for obj if one is available.
QDeclarativePropertyCache * cache (const QMetaObject *)
Returns a QDeclarativePropertyCache for metaObject.
QDeclarativePropertyCache * cache (QDeclarativeType *, int, QDeclarativeError &error)
Returns a QDeclarativePropertyCache for type with minorVersion.
QDeclarativePropertyCache * createCache (const QMetaObject *)
QDeclarativePropertyCache * createCache (QDeclarativeType *, int, QDeclarativeError &error)
QNetworkAccessManager * createNetworkAccessManager (QObject *parent) const
QDeclarativeContextData * getContext (QScriptContext *)
Returns the QDeclarativeContext for the executing QScript ctxt.
QImage getImageFromProvider (const QUrl &url, QSize *size, const QSize &req_size)
QDeclarativeImageProvider::ImageType getImageProviderType (const QUrl &url)
QNetworkAccessManager * getNetworkAccessManager () const
QPixmap getPixmapFromProvider (const QUrl &url, QSize *size, const QSize &req_size)
quint32 getUniqueId () const
QUrl getUrl (QScriptContext *)
Returns the QUrl associated with the script ctxt for the case that there is no QDeclarativeContext.
QDeclarativeWorkerScriptEngine * getWorkerScriptEngine ()
void init ()
bool isList (int) const
bool isQObject (int)
int listType (int) const
const QMetaObject * metaObjectForType (int) const
QDeclarativeEnginePrivate (QDeclarativeEngine *)
const QMetaObject * rawMetaObjectForType (int) const
void registerCompositeType (QDeclarativeCompiledData *)
void registerFinalizedParserStatusObject (QObject *obj, int index)
QScriptValue scriptValueFromVariant (const QVariant &)
QVariant scriptValueToVariant (const QScriptValue &, int hint=QVariant::Invalid)
void sendQuit ()
QObject * toQObject (const QVariant &, bool *ok=0) const
QDeclarativeMetaType::TypeCategory typeCategory (int) const
void warning (const QDeclarativeError &)
void warning (const QList< QDeclarativeError > &)
~QDeclarativeEnginePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QScriptValue atob (QScriptContext *, QScriptEngine *)
static QScriptValue btoa (QScriptContext *, QScriptEngine *)
static void clear (SimpleList< QDeclarativeAbstractBinding > &)
static void clear (SimpleList< QDeclarativeParserStatus > &)
static QScriptValue consoleLog (QScriptContext *, QScriptEngine *)
static QScriptValue createComponent (QScriptContext *, QScriptEngine *)
static QScriptValue createQmlObject (QScriptContext *, QScriptEngine *)
static QScriptValue darker (QScriptContext *, QScriptEngine *)
static void defineModule ()
static void defineModuleCompat ()
static QScriptValue desktopOpenUrl (QScriptContext *, QScriptEngine *)
static QScriptValue fontFamilies (QScriptContext *, QScriptEngine *)
static QScriptValue formatDate (QScriptContext *, QScriptEngine *)
static QScriptValue formatDateTime (QScriptContext *, QScriptEngine *)
static QScriptValue formatTime (QScriptContext *, QScriptEngine *)
static QDeclarativeEnginePrivate * get (QDeclarativeEngine *e)
static QDeclarativeEnginePrivate * get (QDeclarativeContext *c)
static QDeclarativeEnginePrivate * get (QDeclarativeContextData *c)
static QDeclarativeEnginePrivate * get (QScriptEngine *e)
static QDeclarativeEngine * get (QDeclarativeEnginePrivate *p)
static QDeclarativeEngine * getEngine (QScriptEngine *e)
static QScriptEngine * getScriptEngine (QDeclarativeEngine *e)
static QScriptValue hsla (QScriptContext *, QScriptEngine *)
static QScriptValue isQtObject (QScriptContext *, QScriptEngine *)
static QScriptValue lighter (QScriptContext *, QScriptEngine *)
static QScriptValue md5 (QScriptContext *, QScriptEngine *)
static QScriptValue point (QScriptContext *, QScriptEngine *)
static QScriptValue qmlScriptObject (QObject *, QDeclarativeEngine *)
Creates a QScriptValue allowing you to use object in QML script.
static QScriptValue quit (QScriptContext *, QScriptEngine *)
static QScriptValue rect (QScriptContext *, QScriptEngine *)
static QScriptValue rgba (QScriptContext *, QScriptEngine *)
static QScriptValue size (QScriptContext *, QScriptEngine *)
static QScriptValue tint (QScriptContext *, QScriptEngine *)
static QString urlToLocalFileOrQrc (const QUrl &url)
static QScriptValue vector3d (QScriptContext *, QScriptEngine *)
static void warning (QDeclarativeEngine *, const QDeclarativeError &)
static void warning (QDeclarativeEngine *, const QList< QDeclarativeError > &)
static void warning (QDeclarativeEnginePrivate *, const QDeclarativeError &)
static void warning (QDeclarativeEnginePrivate *, const QList< QDeclarativeError > &)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QUrl baseUrl
QList< SimpleList< QDeclarativeAbstractBinding > > bindValues
QPODVector< CapturedProperty, 16 > capturedProperties
bool captureProperties
QDeclarativeCleanup * cleanup
QDeclarativeComponentAttached * componentAttached
QDeclarativeContextScriptClass * contextClass
QDeclarativeDelayedError * erroredBindings
QList< QPair< QDeclarativeGuard< QObject >, int > > finalizedParserStatus
QDeclarativeGlobalScriptClass * globalClass
QHash< QString, QSharedPointer< QDeclarativeImageProvider > > imageProviders
QDeclarativeImportDatabase importDatabase
bool inBeginCreate
int inProgressCreations
bool isDebugging
QDeclarativeListScriptClass * listClass
QHash< int, QDeclarativeCompiledData * > m_compositeTypes
QHash< int, int > m_qmlLists
QHash< QString, QScriptValue > m_sharedScriptImports
QMutex mutex
QNetworkAccessManager * networkAccessManager
QDeclarativeNetworkAccessManagerFactory * networkAccessManagerFactory
QDeclarativeObjectScriptClass * objectClass
QString offlineStoragePath
bool outputWarningsToStdErr
QList< SimpleList< QDeclarativeParserStatus > > parserStatus
QHash< const QMetaObject *, QDeclarativePropertyCache * > propertyCache
QDeclarativeContext * rootContext
QDeclarativeScriptEngine scriptEngine
QDeclarativeContextData * sharedContext
QObject * sharedScope
QDeclarativeTypeLoader typeLoader
QDeclarativeTypeNameScriptClass * typeNameClass
QHash< QPair< QDeclarativeType *, int >, QDeclarativePropertyCache * > typePropertyCache
quint32 uniqueId
QDeclarativeValueTypeScriptClass * valueTypeClass
QDeclarativeValueTypeFactory valueTypes
QDeclarativeWorkerScriptEngine * workerScriptEngine
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables
static bool qml_debugging_enabled = false
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 139 of file qdeclarativeengine_p.h.
Constructors and Destructors
QDeclarativeEnginePrivate()
QDeclarativeEnginePrivate::QDeclarativeEnginePrivate (QDeclarativeEngine * e)
Definition at line 357 of file qdeclarativeengine.cpp.
 : captureProperties(false), rootContext(0), isDebugging(false),
   outputWarningsToStdErr(true), contextClass(0), sharedContext(0), sharedScope(0),
   objectClass(0), valueTypeClass(0), globalClass(0), cleanup(0), erroredBindings(0),
   inProgressCreations(0), scriptEngine(this), workerScriptEngine(0), componentAttached(0),
   inBeginCreate(false), networkAccessManager(0), networkAccessManagerFactory(0),
   typeLoader(e), importDatabase(e), uniqueId(1)
 {
     if (!qt_QmlQtModule_registered) {
         qt_QmlQtModule_registered = true;
         QDeclarativeEnginePrivate::defineModule();
         QDeclarativeItemModule::defineModule();
         QDeclarativeValueTypeFactory::registerValueTypes();
         QDeclarativeUtilModule::defineModule();
     }
     globalClass = new QDeclarativeGlobalScriptClass(&scriptEngine);
 }
~QDeclarativeEnginePrivate()
QDeclarativeEnginePrivate::~QDeclarativeEnginePrivate ()
Definition at line 495 of file qdeclarativeengine.cpp.
 {
     Q_ASSERT(inProgressCreations == 0);
     Q_ASSERT(bindValues.isEmpty());
     Q_ASSERT(parserStatus.isEmpty());
     while (cleanup) {
         QDeclarativeCleanup *c = cleanup;
         cleanup = c->next;
         if (cleanup) cleanup->prev = &cleanup;
         c->next = 0;
         c->prev = 0;
         c->clear();
     }
     delete rootContext;
     rootContext = 0;
     delete contextClass;
     contextClass = 0;
     delete objectClass;
     objectClass = 0;
     delete valueTypeClass;
     valueTypeClass = 0;
     delete typeNameClass;
     typeNameClass = 0;
     delete listClass;
     listClass = 0;
     delete globalClass;
     globalClass = 0;
     for(QHash<int, QDeclarativeCompiledData*>::ConstIterator iter = m_compositeTypes.constBegin(); iter != m_compositeTypes.constEnd(); ++iter)
         (*iter)->release();
     for(QHash<const QMetaObject *, QDeclarativePropertyCache *>::Iterator iter = propertyCache.begin(); iter != propertyCache.end(); ++iter)
         (*iter)->release();
     for(QHash<QPair<QDeclarativeType *, int>, QDeclarativePropertyCache *>::Iterator iter = typePropertyCache.begin(); iter != typePropertyCache.end(); ++iter)
         (*iter)->release();
 }
Functions
atob()
QScriptValue QDeclarativeEnginePrivate::atob (QScriptContext * ctxt, QScriptEngine *) static
Definition at line 1942 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if (ctxt->argumentCount() != 1)
         return ctxt->throwError(QLatin1String("Qt.atob(): Invalid arguments"));
     QByteArray data = ctxt->argument(0).toString().toUtf8();
     return QScriptValue(QLatin1String(QByteArray::fromBase64(data)));
 }
btoa()
QScriptValue QDeclarativeEnginePrivate::btoa (QScriptContext * ctxt, QScriptEngine *) static
Definition at line 1927 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if (ctxt->argumentCount() != 1)
         return ctxt->throwError(QLatin1String("Qt.btoa(): Invalid arguments"));
     QByteArray data = ctxt->argument(0).toString().toUtf8();
     return QScriptValue(QLatin1String(data.toBase64()));
 }
cache() [1/3]
QDeclarativePropertyCache * QDeclarativeEnginePrivate::cache (QObject * obj) inline
Returns a QDeclarativePropertyCache for obj if one is available.
If obj is null, being deleted or contains a dynamic meta object 0 is returned.
The returned cache is not referenced, so if it is to be stored, call addref().
Definition at line 340 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeCompiler::compile(), QDeclarativeCompiledData::TypeReference::createPropertyCache(), QDeclarativePropertyCache::property(), and QDeclarativeObjectScriptClass::propertyNames().
 {
     if (!obj || QObjectPrivate::get(obj)->metaObject || QObjectPrivate::get(obj)->wasDeleted)
         return 0;
     const QMetaObject *mo = obj->metaObject();
     QDeclarativePropertyCache *rv = propertyCache.value(mo);
     if (!rv) rv = createCache(mo);
     return rv;
 }
cache() [2/3]
QDeclarativePropertyCache * QDeclarativeEnginePrivate::cache (const QMetaObject * metaObject) inline
Returns a QDeclarativePropertyCache for metaObject.
As the cache is persisted for the life of the engine, metaObject must be a static "compile time" meta-object, or a meta-object that is otherwise known to exist for the lifetime of the QDeclarativeEngine.
The returned cache is not referenced, so if it is to be stored, call addref().
Definition at line 360 of file qdeclarativeengine_p.h.
 {
     Q_ASSERT(metaObject);
     QDeclarativePropertyCache *rv = propertyCache.value(metaObject);
     if (!rv) rv = createCache(metaObject);
     return rv;
 }
cache() [3/3]
QDeclarativePropertyCache * QDeclarativeEnginePrivate::cache (QDeclarativeType * type, int minorVersion, QDeclarativeError & error) inline
Returns a QDeclarativePropertyCache for type with minorVersion.
The returned cache is not referenced, so if it is to be stored, call addref().
Definition at line 374 of file qdeclarativeengine_p.h.
 {
     Q_ASSERT(type);
     if (minorVersion == -1 || !type->containsRevisionedAttributes())
         return cache(type->metaObject());
     QDeclarativePropertyCache *rv = typePropertyCache.value(qMakePair(type, minorVersion));
     if (!rv) rv = createCache(type, minorVersion, error);
     return rv;
 }
clear() [1/2]
void QDeclarativeEnginePrivate::clear (SimpleList< QDeclarativeAbstractBinding > & bvs) static
Definition at line 534 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeComponentPrivate::complete().
 {
     bvs.clear();
 }
clear() [2/2]
void QDeclarativeEnginePrivate::clear (SimpleList< QDeclarativeParserStatus > & pss) static
Definition at line 539 of file qdeclarativeengine.cpp.
 {
     for (int ii = 0; ii < pss.count; ++ii) {
         QDeclarativeParserStatus *ps = pss.at(ii);
         if(ps)
             ps->d = 0;
     }
     pss.clear();
 }
consoleLog()
QScriptValue QDeclarativeEnginePrivate::consoleLog (QScriptContext * ctxt, QScriptEngine * e) static
Definition at line 1952 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() < 1)
         return e->newVariant(QVariant(false));
     QByteArray msg;
     for (int i=0; i<ctxt->argumentCount(); ++i) {
         if (!msg.isEmpty()) msg += ' ';
         msg += ctxt->argument(i).toString().toLocal8Bit();
         // does not support firebug "%[a-z]" formatting, since firebug really
         // does just ignore the format letter, which makes it pointless.
     }
     qDebug("%s",msg.constData());
     return e->newVariant(QVariant(true));
 }
createCache() [1/2]
QDeclarativePropertyCache * QDeclarativeEnginePrivate::createCache (const QMetaObject * mo)
Definition at line 2352 of file qdeclarativeengine.cpp.
 {
     Q_Q(QDeclarativeEngine);
     if (!mo->superClass()) {
         QDeclarativePropertyCache *rv = new QDeclarativePropertyCache(q, mo);
         propertyCache.insert(mo, rv);
         return rv;
     } else {
         QDeclarativePropertyCache *super = cache(mo->superClass());
         QDeclarativePropertyCache *rv = super->copy();
         rv->append(q, mo);
         propertyCache.insert(mo, rv);
         return rv;
     }
 }
createCache() [2/2]
QDeclarativePropertyCache * QDeclarativeEnginePrivate::createCache (QDeclarativeType * type, int minorVersion, QDeclarativeError & error)
Definition at line 2369 of file qdeclarativeengine.cpp.
 {
     QList<QDeclarativeType *> types;
     int maxMinorVersion = 0;
     const QMetaObject *metaObject = type->metaObject();
     while (metaObject) {
         QDeclarativeType *t = QDeclarativeMetaType::qmlType(metaObject, type->module(),
                                                             type->majorVersion(), minorVersion);
         if (t) {
             maxMinorVersion = qMax(maxMinorVersion, t->minorVersion());
             types << t;
         } else {
             types << 0;
         }
         metaObject = metaObject->superClass();
     }
     if (QDeclarativePropertyCache *c = typePropertyCache.value(qMakePair(type, maxMinorVersion))) {
         c->addref();
         typePropertyCache.insert(qMakePair(type, minorVersion), c);
         return c;
     }
     QDeclarativePropertyCache *raw = cache(type->metaObject());
     bool hasCopied = false;
     for (int ii = 0; ii < types.count(); ++ii) {
         QDeclarativeType *currentType = types.at(ii);
         if (!currentType)
             continue;
         int rev = currentType->metaObjectRevision();
         int moIndex = types.count() - 1 - ii;
         if (raw->allowedRevisionCache[moIndex] != rev) {
             if (!hasCopied) {
                 raw = raw->copy();
                 hasCopied = true;
             }
             raw->allowedRevisionCache[moIndex] = rev;
         }
     }
     // Test revision compatibility - the basic rule is:
     //    * Anything that is excluded, cannot overload something that is not excluded *
     // Signals override:
     //    * other signals and methods of the same name.
     //    * properties named on<Signal Name>
     //    * automatic <property name>Changed notify signals
     // Methods override:
     //    * other methods of the same name
     // Properties override:
     //    * other elements of the same name
     bool overloadError = false;
     QString overloadName;
 #if 0
     for (QDeclarativePropertyCache::StringCache::ConstIterator iter = raw->stringCache.begin();
          !overloadError && iter != raw->stringCache.end();
          ++iter) {
         QDeclarativePropertyCache::Data *d = *iter;
         if (raw->isAllowedInRevision(d))
             continue; // Not excluded - no problems
         // check that a regular "name" overload isn't happening
         QDeclarativePropertyCache::Data *current = d;
         while (!overloadError && current) {
             current = d->overrideData(current);
             if (current && raw->isAllowedInRevision(current))
                 overloadError = true;
         }
     }
 #endif
     if (overloadError) {
         if (hasCopied) raw->release();
         error.setDescription(QLatin1String("Type ") + QString::fromUtf8(type->qmlTypeName()) + QLatin1String(" ") + QString::number(type->majorVersion()) + QLatin1String(".") + QString::number(minorVersion) + QLatin1String(" contains an illegal property \"") + overloadName + QLatin1String("\".  This is an error in the type's implementation."));
         return 0;
     }
     if (!hasCopied) raw->addref();
     typePropertyCache.insert(qMakePair(type, minorVersion), raw);
     if (minorVersion != maxMinorVersion) {
         raw->addref();
         typePropertyCache.insert(qMakePair(type, maxMinorVersion), raw);
     }
     return raw;
 }
createComponent()
QScriptValue QDeclarativeEnginePrivate::createComponent (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1346 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     QDeclarativeEnginePrivate *activeEnginePriv =
         static_cast<QDeclarativeScriptEngine*>(engine)->p;
     QDeclarativeEngine* activeEngine = activeEnginePriv->q_func();
     if(ctxt->argumentCount() != 1) {
         return ctxt->throwError(QLatin1String("Qt.createComponent(): Invalid arguments"));
     } else {
         QString arg = ctxt->argument(0).toString();
         if (arg.isEmpty())
             return engine->nullValue();
         QUrl url = QDeclarativeScriptEngine::get(engine)->resolvedUrl(ctxt, QUrl(arg));
         QDeclarativeContextData* context = activeEnginePriv->getContext(ctxt);
         QDeclarativeComponent *c = new QDeclarativeComponent(activeEngine, url, activeEngine);
         QDeclarativeComponentPrivate::get(c)->creationContext = context;
         QDeclarativeData::get(c, true)->setImplicitDestructible();
         return activeEnginePriv->objectClass->newQObject(c, qMetaTypeId<QDeclarativeComponent*>());
     }
 }
createNetworkAccessManager()
QNetworkAccessManager * QDeclarativeEnginePrivate::createNetworkAccessManager (QObject * parent) const
Definition at line 749 of file qdeclarativeengine.cpp.
Referenced by QDeclarativePixmapReader::networkAccessManager().
 {
     QMutexLocker locker(&mutex);
     QNetworkAccessManager *nam;
     if (networkAccessManagerFactory) {
         nam = networkAccessManagerFactory->create(parent);
     } else {
         nam = new QNetworkAccessManager(parent);
     }
     return nam;
 }
createQmlObject()
QScriptValue QDeclarativeEnginePrivate::createQmlObject (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1393 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     QDeclarativeEnginePrivate *activeEnginePriv =
         static_cast<QDeclarativeScriptEngine*>(engine)->p;
     QDeclarativeEngine* activeEngine = activeEnginePriv->q_func();
     if(ctxt->argumentCount() < 2 || ctxt->argumentCount() > 3)
         return ctxt->throwError(QLatin1String("Qt.createQmlObject(): Invalid arguments"));
     QDeclarativeContextData* context = activeEnginePriv->getContext(ctxt);
     Q_ASSERT(context);
     QString qml = ctxt->argument(0).toString();
     if (qml.isEmpty())
         return engine->nullValue();
     QUrl url;
     if(ctxt->argumentCount() > 2)
         url = QUrl(ctxt->argument(2).toString());
     else
         url = QUrl(QLatin1String("inline"));
     if (url.isValid() && url.isRelative())
         url = context->resolvedUrl(url);
     QObject *parentArg = activeEnginePriv->objectClass->toQObject(ctxt->argument(1));
     if(!parentArg)
         return ctxt->throwError(QLatin1String("Qt.createQmlObject(): Missing parent object"));
     QDeclarativeComponent component(activeEngine);
     component.setData(qml.toUtf8(), url);
     if(component.isError()) {
         QList<QDeclarativeError> errors = component.errors();
         QString errstr = QLatin1String("Qt.createQmlObject() failed to create object: ");
         QScriptValue arr = ctxt->engine()->newArray(errors.length());
         int i = 0;
         foreach (const QDeclarativeError &error, errors){
             errstr += QLatin1String("    ") + error.toString() + QLatin1String("\n");
             QScriptValue qmlErrObject = ctxt->engine()->newObject();
             qmlErrObject.setProperty(QLatin1String("lineNumber"), QScriptValue(error.line()));
             qmlErrObject.setProperty(QLatin1String("columnNumber"), QScriptValue(error.column()));
             qmlErrObject.setProperty(QLatin1String("fileName"), QScriptValue(error.url().toString()));
             qmlErrObject.setProperty(QLatin1String("message"), QScriptValue(error.description()));
             arr.setProperty(i++, qmlErrObject);
         }
         QScriptValue err = ctxt->throwError(errstr);
         err.setProperty(QLatin1String("qmlErrors"),arr);
         return err;
     }
     if (!component.isReady())
         return ctxt->throwError(QLatin1String("Qt.createQmlObject(): Component is not ready"));
     QObject *obj = component.beginCreate(context->asQDeclarativeContext());
     if(obj)
         QDeclarativeData::get(obj, true)->setImplicitDestructible();
     component.completeCreate();
     if(component.isError()) {
         QList<QDeclarativeError> errors = component.errors();
         QString errstr = QLatin1String("Qt.createQmlObject() failed to create object: ");
         QScriptValue arr = ctxt->engine()->newArray(errors.length());
         int i = 0;
         foreach (const QDeclarativeError &error, errors){
             errstr += QLatin1String("    ") + error.toString() + QLatin1String("\n");
             QScriptValue qmlErrObject = ctxt->engine()->newObject();
             qmlErrObject.setProperty(QLatin1String("lineNumber"), QScriptValue(error.line()));
             qmlErrObject.setProperty(QLatin1String("columnNumber"), QScriptValue(error.column()));
             qmlErrObject.setProperty(QLatin1String("fileName"), QScriptValue(error.url().toString()));
             qmlErrObject.setProperty(QLatin1String("message"), QScriptValue(error.description()));
             arr.setProperty(i++, qmlErrObject);
         }
         QScriptValue err = ctxt->throwError(errstr);
         err.setProperty(QLatin1String("qmlErrors"),arr);
         return err;
     }
     Q_ASSERT(obj);
     obj->setParent(parentArg);
     QList<QDeclarativePrivate::AutoParentFunction> functions = QDeclarativeMetaType::parentFunctions();
     for (int ii = 0; ii < functions.count(); ++ii) {
         if (QDeclarativePrivate::Parented == functions.at(ii)(obj, parentArg))
             break;
     }
     QDeclarativeData::get(obj, true)->setImplicitDestructible();
     return activeEnginePriv->objectClass->newQObject(obj, QMetaType::QObjectStar);
 }
darker()
QScriptValue QDeclarativeEnginePrivate::darker (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1856 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 1 && ctxt->argumentCount() != 2)
         return ctxt->throwError(QLatin1String("Qt.darker(): Invalid arguments"));
     QVariant v = ctxt->argument(0).toVariant();
     QColor color;
     if (v.userType() == QVariant::Color)
         color = v.value<QColor>();
     else if (v.userType() == QVariant::String) {
         bool ok;
         color = QDeclarativeStringConverters::colorFromString(v.toString(), &ok);
         if (!ok)
             return engine->nullValue();
     } else
         return engine->nullValue();
     qsreal factor = 2.0;
     if (ctxt->argumentCount() == 2)
         factor = ctxt->argument(1).toNumber();
     color = color.darker(int(qRound(factor*100.)));
     return engine->toScriptValue(QVariant::fromValue(color));
 }
defineModule()
void QDeclarativeEnginePrivate::defineModule () static
Definition at line 189 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeEnginePrivate().
 {
     qmlRegisterType<QDeclarativeComponent>("QtQuick",1,0,"Component");
     qmlRegisterType<QObject>("QtQuick",1,0,"QtObject");
     qmlRegisterType<QDeclarativeWorkerScript>("QtQuick",1,0,"WorkerScript");
     qmlRegisterType<QDeclarativeBinding>();
 }
defineModuleCompat()
void QDeclarativeEnginePrivate::defineModuleCompat () static
Definition at line 198 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeMetaType::isModule().
 {
     qmlRegisterType<QDeclarativeComponent>("Qt",4,7,"Component");
     qmlRegisterType<QObject>("Qt",4,7,"QtObject");
     qmlRegisterType<QDeclarativeWorkerScript>("Qt",4,7,"WorkerScript");
 }
desktopOpenUrl()
QScriptValue QDeclarativeEnginePrivate::desktopOpenUrl (QScriptContext * ctxt, QScriptEngine * e) static
Definition at line 1882 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() < 1)
         return QScriptValue(e, false);
     bool ret = false;
 #ifndef QT_NO_DESKTOPSERVICES
     ret = QDesktopServices::openUrl(QDeclarativeScriptEngine::get(e)->resolvedUrl(ctxt, QUrl(ctxt->argument(0).toString())));
 #endif
     return QScriptValue(e, ret);
 }
fontFamilies()
QScriptValue QDeclarativeEnginePrivate::fontFamilies (QScriptContext * ctxt, QScriptEngine * e) static
Definition at line 1898 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 0)
         return ctxt->throwError(QLatin1String("Qt.fontFamilies(): Invalid arguments"));
     QDeclarativeEnginePrivate *p = QDeclarativeEnginePrivate::get(e);
     QFontDatabase database;
     return p->scriptValueFromVariant(database.families());
 }
formatDate()
QScriptValue QDeclarativeEnginePrivate::formatDate (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1526 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     int argCount = ctxt->argumentCount();
     if(argCount == 0 || argCount > 2)
         return ctxt->throwError(QLatin1String("Qt.formatDate(): Invalid arguments"));
     QDate date = ctxt->argument(0).toDateTime().date();
     Qt::DateFormat enumFormat = Qt::DefaultLocaleShortDate;
     if (argCount == 2) {
         QScriptValue formatArg = ctxt->argument(1);
         if (formatArg.isString()) {
             QString format = formatArg.toString();
             return engine->newVariant(QVariant::fromValue(date.toString(format)));
         } else if (formatArg.isNumber()) {
             enumFormat = Qt::DateFormat(formatArg.toUInt32());
         } else {
             return ctxt->throwError(QLatin1String("Qt.formatDate(): Invalid date format"));
         }
     }
     return engine->newVariant(QVariant::fromValue(date.toString(enumFormat)));
 }
formatDateTime()
QScriptValue QDeclarativeEnginePrivate::formatDateTime (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1680 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     int argCount = ctxt->argumentCount();
     if(argCount == 0 || argCount > 2)
         return ctxt->throwError(QLatin1String("Qt.formatDateTime(): Invalid arguments"));
     QDateTime date = ctxt->argument(0).toDateTime();
     Qt::DateFormat enumFormat = Qt::DefaultLocaleShortDate;
     if (argCount == 2) {
         QScriptValue formatArg = ctxt->argument(1);
         if (formatArg.isString()) {
             QString format = formatArg.toString();
             return engine->newVariant(QVariant::fromValue(date.toString(format)));
         } else if (formatArg.isNumber()) {
             enumFormat = Qt::DateFormat(formatArg.toUInt32());
         } else {
             return ctxt->throwError(QLatin1String("Qt.formatDateTime(): Invalid datetime format"));
         }
     }
     return engine->newVariant(QVariant::fromValue(date.toString(enumFormat)));
 }
formatTime()
QScriptValue QDeclarativeEnginePrivate::formatTime (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1561 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     int argCount = ctxt->argumentCount();
     if(argCount == 0 || argCount > 2)
         return ctxt->throwError(QLatin1String("Qt.formatTime(): Invalid arguments"));
     QTime time;
     QScriptValue sv = ctxt->argument(0);
     if (sv.isDate())
         time = sv.toDateTime().time();
     else if (sv.toVariant().type() == QVariant::Time)
         time = sv.toVariant().toTime();
     Qt::DateFormat enumFormat = Qt::DefaultLocaleShortDate;
     if (argCount == 2) {
         QScriptValue formatArg = ctxt->argument(1);
         if (formatArg.isString()) {
             QString format = formatArg.toString();
             return engine->newVariant(QVariant::fromValue(time.toString(format)));
         } else if (formatArg.isNumber()) {
             enumFormat = Qt::DateFormat(formatArg.toUInt32());
         } else {
             return ctxt->throwError(QLatin1String("Qt.formatTime(): Invalid time format"));
         }
     }
     return engine->newVariant(QVariant::fromValue(time.toString(enumFormat)));
 }
get() [1/5]
static QDeclarativeEnginePrivate* QDeclarativeEnginePrivate::get (QDeclarativeEngine * e) inline static
Definition at line 316 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeIntegerCache::add(), QDeclarativeTypeNameCache::add(), QDeclarativeContextData::addImportedScript(), QDeclarativePropertyCache::append(), QDeclarativeComponentPrivate::begin(), QDeclarativeCompiler::compile(), QDeclarativeComponentPrivate::completeCreate(), QDeclarativeObjectMethodScriptClass::connect(), QDeclarativeBinding::createBinding(), QDeclarativeComponentPrivate::createObject(), createPixmapDataSync(), QDeclarativeCompiledData::TypeReference::createPropertyCache(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeObjectMethodScriptClass::disconnect(), QDeclarativeWorkerScript::engine(), QDeclarativeQtScriptExpression::eval(), QDeclarativeExpressionPrivate::evalInObjectScope(), QDeclarativeCompiledBindingsPrivate::findgeneric(), QDeclarativeCompiledBindingsPrivate::findproperty(), QDeclarativeInclude::finished(), QDeclarativePropertyCache::Data::flagsForProperty(), fontFamilies(), get(), ContextData::getContext(), ContextData::getScope(), QDeclarativeInclude::include(), QDeclarativeListReferencePrivate::init(), QDeclarativeExpressionPrivate::init(), QDeclarativeDomDocument::load(), QDeclarativePixmap::load(), QDeclarativeComponent::loadUrl(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeProperty::name(), QDeclarativePixmapReader::networkAccessManager(), point(), QDeclarativeXMLHttpRequest::printError(), QDeclarativePixmapReader::processJob(), QDeclarativeListScriptClass::property(), QDeclarativeTypeNameScriptClass::property(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContextScriptClass::property(), QDeclarativeObjectScriptClass::property(), QDeclarativePropertyCache::property(), QDeclarativeObjectScriptClass::propertyNames(), QDeclarativeProperty::propertyTypeName(), QDeclarativeCleanup::QDeclarativeCleanup(), QDeclarativeInclude::QDeclarativeInclude(), QDeclarativeListReference::QDeclarativeListReference(), QDeclarativeComponent::qmlAttachedProperties(), qmlExecuteDeferred(), qmlScriptObject(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeContextScriptClass::queryProperty(), QDeclarativeObjectScriptClass::queryProperty(), QDeclarativePropertyPrivate::readValueProperty(), QDeclarativeVMEMetaObject::readVarProperty(), QDeclarativeVMEMetaObject::readVarPropertyAsVariant(), rect(), QDeclarativeTypeData::resolveTypes(), QDeclarativeVME::run(), QDeclarativeCompiledBindingsPrivate::run(), QDeclarativeQtScriptExpression::scriptValue(), QDeclarativeExpressionPrivate::scriptValue(), QDeclarativeContext::setContextProperty(), QDeclarativeComponent::setData(), QDeclarativeListAccessor::setList(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeTypeNameScriptClass::setProperty(), QDeclarativeContextScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeAbstractAnimation::setRunning(), QDeclarativeBehavior::setTarget(), size(), throwException(), QDeclarativeBinding::update(), QDeclarativeExpressionPrivate::value(), vector3d(), warning(), QDeclarativePropertyPrivate::write(), and QDeclarativePropertyPrivate::writeValueProperty().
 { return e->d_func(); }
get() [2/5]
static QDeclarativeEnginePrivate* QDeclarativeEnginePrivate::get (QDeclarativeContext * c) inline static
Definition at line 317 of file qdeclarativeengine_p.h.
 { return (c && c->engine()) ? QDeclarativeEnginePrivate::get(c->engine()) : 0; }
get() [3/5]
static QDeclarativeEnginePrivate* QDeclarativeEnginePrivate::get (QDeclarativeContextData * c) inline static
Definition at line 318 of file qdeclarativeengine_p.h.
 { return (c && c->engine) ? QDeclarativeEnginePrivate::get(c->engine) : 0; }
get() [4/5]
static QDeclarativeEnginePrivate* QDeclarativeEnginePrivate::get (QScriptEngine * e) inline static
Definition at line 319 of file qdeclarativeengine_p.h.
 { return static_cast<QDeclarativeScriptEngine*>(e)->p; }
get() [5/5]
static QDeclarativeEngine* QDeclarativeEnginePrivate::get (QDeclarativeEnginePrivate * p) inline static
Definition at line 320 of file qdeclarativeengine_p.h.
 { return p->q_func(); }
getContext()
QDeclarativeContextData * QDeclarativeEnginePrivate::getContext (QScriptContext * ctxt)
Returns the QDeclarativeContext for the executing QScript ctxt.
Definition at line 1293 of file qdeclarativeengine.cpp.
Referenced by createComponent(), createQmlObject(), and QDeclarativeValueTypeScriptClass::setProperty().
 {
     QScriptValue scopeNode = QScriptDeclarativeClass::scopeChainValue(ctxt, -3);
     Q_ASSERT(scopeNode.isValid());
     Q_ASSERT(QScriptDeclarativeClass::scriptClass(scopeNode) == contextClass);
     return contextClass->contextFromValue(scopeNode);
 }
getEngine()
static QDeclarativeEngine* QDeclarativeEnginePrivate::getEngine (QScriptEngine * e) inline static
Definition at line 315 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeInclude::include().
 { return static_cast<QDeclarativeScriptEngine*>(e)->p->q_func(); }
getImageFromProvider()
QImage QDeclarativeEnginePrivate::getImageFromProvider (const QUrl & url, QSize * size, const QSize & req_size)
Definition at line 844 of file qdeclarativeengine.cpp.
Referenced by createPixmapDataSync(), and QDeclarativePixmapReader::processJob().
 {
     QMutexLocker locker(&mutex);
     QImage image;
     QSharedPointer<QDeclarativeImageProvider> provider = imageProviders.value(url.host());
     locker.unlock();
     if (provider) {
         QString imageId = url.toString(QUrl::RemoveScheme | QUrl::RemoveAuthority).mid(1);
         image = provider->requestImage(imageId, size, req_size);
     }
     return image;
 }
getImageProviderType()
QDeclarativeImageProvider::ImageType QDeclarativeEnginePrivate::getImageProviderType (const QUrl & url)
Definition at line 834 of file qdeclarativeengine.cpp.
Referenced by createPixmapDataSync(), and QDeclarativePixmap::load().
 {
     QMutexLocker locker(&mutex);
     QSharedPointer<QDeclarativeImageProvider> provider = imageProviders.value(url.host());
     locker.unlock();
     if (provider)
         return provider->imageType();
     return static_cast<QDeclarativeImageProvider::ImageType>(-1);
 }
getNetworkAccessManager()
QNetworkAccessManager * QDeclarativeEnginePrivate::getNetworkAccessManager () const
Definition at line 762 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::networkAccessManager().
 {
     Q_Q(const QDeclarativeEngine);
     if (!networkAccessManager)
         networkAccessManager = createNetworkAccessManager(const_cast<QDeclarativeEngine*>(q));
     return networkAccessManager;
 }
getPixmapFromProvider()
QPixmap QDeclarativeEnginePrivate::getPixmapFromProvider (const QUrl & url, QSize * size, const QSize & req_size)
Definition at line 857 of file qdeclarativeengine.cpp.
Referenced by createPixmapDataSync().
 {
     QMutexLocker locker(&mutex);
     QPixmap pixmap;
     QSharedPointer<QDeclarativeImageProvider> provider = imageProviders.value(url.host());
     locker.unlock();
     if (provider) {
         QString imageId = url.toString(QUrl::RemoveScheme | QUrl::RemoveAuthority).mid(1);
         pixmap = provider->requestPixmap(imageId, size, req_size);
     }
     return pixmap;
 }
getScriptEngine()
static QScriptEngine* QDeclarativeEnginePrivate::getScriptEngine (QDeclarativeEngine * e) inline static
Definition at line 314 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextData::addImportedScript(), QDeclarativeQtScriptExpression::eval(), QDeclarativeWorkerScript::event(), FlatListModel::get(), QDeclarativeXmlListModel::get(), NestedListModel::get(), QDeclarativeDebugHelper::getScriptEngine(), QDeclarativeExpressionPrivate::init(), QDeclarativeItem::mapFromItem(), QDeclarativeItem::mapToItem(), QDeclarativeContextScriptClass::newContext(), QDeclarativeListScriptClass::newList(), QDeclarativeObjectMethodScriptClass::newMethod(), QDeclarativeValueTypeScriptClass::newObject(), QDeclarativeTypeNameScriptClass::newObject(), QDeclarativeObjectScriptClass::newQObject(), QDeclarativeContextScriptClass::newSharedContext(), QDeclarativeContextScriptClass::newUrlContext(), ModelNode::object(), QDeclarativeValueTypeScriptClass::property(), QDeclarativeListScriptClass::property(), QDeclarativeTypeNameScriptClass::property(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContextScriptClass::property(), QDeclarativeObjectScriptClass::property(), QDeclarativeInclude::QDeclarativeInclude(), QDeclarativeListScriptClass::QDeclarativeListScriptClass(), QDeclarativeObjectMethodScriptClass::QDeclarativeObjectMethodScriptClass(), QDeclarativeObjectScriptClass::QDeclarativeObjectScriptClass(), and QDeclarativeExpressionPrivate::scriptValue().
 { if (!e) return 0; return &e->d_func()->scriptEngine; }
getUniqueId()
quint32 QDeclarativeEnginePrivate::getUniqueId () const inline
Definition at line 246 of file qdeclarativeengine_p.h.
{
         return uniqueId++;
     }
getUrl()
QUrl QDeclarativeEnginePrivate::getUrl (QScriptContext * ctxt)
Returns the QUrl associated with the script ctxt for the case that there is no QDeclarativeContext.
Definition at line 1305 of file qdeclarativeengine.cpp.
 {
     QScriptValue scopeNode = QScriptDeclarativeClass::scopeChainValue(ctxt, -3);
     Q_ASSERT(scopeNode.isValid());
     Q_ASSERT(QScriptDeclarativeClass::scriptClass(scopeNode) == contextClass);
     return contextClass->urlFromValue(scopeNode);
 }
getWorkerScriptEngine()
QDeclarativeWorkerScriptEngine * QDeclarativeEnginePrivate::getWorkerScriptEngine ()
Definition at line 609 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeWorkerScript::engine().
 {
     Q_Q(QDeclarativeEngine);
     if (!workerScriptEngine)
         workerScriptEngine = new QDeclarativeWorkerScriptEngine(q);
     return workerScriptEngine;
 }
hsla()
QScriptValue QDeclarativeEnginePrivate::hsla (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1737 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     int argCount = ctxt->argumentCount();
     if(argCount < 3 || argCount > 4)
         return ctxt->throwError(QLatin1String("Qt.hsla(): Invalid arguments"));
     qsreal h = ctxt->argument(0).toNumber();
     qsreal s = ctxt->argument(1).toNumber();
     qsreal l = ctxt->argument(2).toNumber();
     qsreal a = (argCount == 4) ? ctxt->argument(3).toNumber() : 1;
     if (h < 0.0) h=0.0;
     if (h > 1.0) h=1.0;
     if (s < 0.0) s=0.0;
     if (s > 1.0) s=1.0;
     if (l < 0.0) l=0.0;
     if (l > 1.0) l=1.0;
     if (a < 0.0) a=0.0;
     if (a > 1.0) a=1.0;
     return engine->toScriptValue(QVariant::fromValue(QColor::fromHslF(h, s, l, a)));
 }
init()
void QDeclarativeEnginePrivate::init ()
Definition at line 581 of file qdeclarativeengine.cpp.
 {
     Q_Q(QDeclarativeEngine);
     qRegisterMetaType<QVariant>("QVariant");
     qRegisterMetaType<QDeclarativeScriptString>("QDeclarativeScriptString");
     qRegisterMetaType<QScriptValue>("QScriptValue");
     qRegisterMetaType<QDeclarativeComponent::Status>("QDeclarativeComponent::Status");
     QDeclarativeData::init();
     contextClass = new QDeclarativeContextScriptClass(q);
     objectClass = new QDeclarativeObjectScriptClass(q);
     valueTypeClass = new QDeclarativeValueTypeScriptClass(q);
     typeNameClass = new QDeclarativeTypeNameScriptClass(q);
     listClass = new QDeclarativeListScriptClass(q);
     rootContext = new QDeclarativeContext(q,true);
     QScriptValue applicationObject = objectClass->newQObject(new QDeclarativeApplication(q));
     scriptEngine.globalObject().property(QLatin1String("Qt")).setProperty(QLatin1String("application"), applicationObject);
     if (QCoreApplication::instance()->thread() == q->thread() &&
         QDeclarativeEngineDebugService::isDebuggingEnabled()) {
         isDebugging = true;
         QDeclarativeEngineDebugService::instance()->addEngine(q);
         QJSDebugService::instance()->addEngine(q);
     }
 }
isList()
bool QDeclarativeEnginePrivate::isList (int t) const
Definition at line 2488 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeCompiler::buildListProperty(), QDeclarativeCompiler::buildProperty(), and QDeclarativeCompiler::genValueProperty().
 {
     return m_qmlLists.contains(t) || QDeclarativeMetaType::isList(t);
 }
isQObject()
bool QDeclarativeEnginePrivate::isQObject (int t)
Definition at line 2502 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeListAccessor::setList().
 {
     return m_compositeTypes.contains(t) || QDeclarativeMetaType::isQObject(t);
 }
isQtObject()
QScriptValue QDeclarativeEnginePrivate::isQtObject (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1489 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if (ctxt->argumentCount() == 0)
         return QScriptValue(engine, false);
     return QScriptValue(engine, 0 != ctxt->argument(0).toQObject());
 }
lighter()
QScriptValue QDeclarativeEnginePrivate::lighter (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1819 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 1 && ctxt->argumentCount() != 2)
         return ctxt->throwError(QLatin1String("Qt.lighter(): Invalid arguments"));
     QVariant v = ctxt->argument(0).toVariant();
     QColor color;
     if (v.userType() == QVariant::Color)
         color = v.value<QColor>();
     else if (v.userType() == QVariant::String) {
         bool ok;
         color = QDeclarativeStringConverters::colorFromString(v.toString(), &ok);
         if (!ok)
             return engine->nullValue();
     } else
         return engine->nullValue();
     qsreal factor = 1.5;
     if (ctxt->argumentCount() == 2)
         factor = ctxt->argument(1).toNumber();
     color = color.lighter(int(qRound(factor*100.)));
     return engine->toScriptValue(QVariant::fromValue(color));
 }
listType()
int QDeclarativeEnginePrivate::listType (int t) const
Definition at line 2493 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeCompiler::buildListProperty(), QDeclarativeCompiler::genListProperty(), QDeclarativeListReferencePrivate::init(), QDeclarativeListReference::QDeclarativeListReference(), and QDeclarativePropertyPrivate::write().
 {
     QHash<int, int>::ConstIterator iter = m_qmlLists.find(t);
     if (iter != m_qmlLists.end())
         return *iter;
     else
         return QDeclarativeMetaType::listType(t);
 }
md5()
QScriptValue QDeclarativeEnginePrivate::md5 (QScriptContext * ctxt, QScriptEngine *) static
Definition at line 1912 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if (ctxt->argumentCount() != 1)
         return ctxt->throwError(QLatin1String("Qt.md5(): Invalid arguments"));
     QByteArray data = ctxt->argument(0).toString().toUtf8();
     QByteArray result = QCryptographicHash::hash(data, QCryptographicHash::Md5);
     return QScriptValue(QLatin1String(result.toHex()));
 }
metaObjectForType()
const QMetaObject * QDeclarativeEnginePrivate::metaObjectForType (int t) const
Definition at line 2539 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeCompiler::buildGroupedProperty().
 {
     QHash<int, QDeclarativeCompiledData*>::ConstIterator iter = m_compositeTypes.find(t);
     if (iter != m_compositeTypes.end()) {
         return (*iter)->root;
     } else {
         QDeclarativeType *type = QDeclarativeMetaType::qmlType(t);
         return type?type->metaObject():0;
     }
 }
point()
QScriptValue QDeclarativeEnginePrivate::point (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1783 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 2)
         return ctxt->throwError(QLatin1String("Qt.point(): Invalid arguments"));
     qsreal x = ctxt->argument(0).toNumber();
     qsreal y = ctxt->argument(1).toNumber();
     return QDeclarativeEnginePrivate::get(engine)->scriptValueFromVariant(QVariant::fromValue(QPointF(x, y)));
 }
qmlScriptObject()
QScriptValue QDeclarativeEnginePrivate::qmlScriptObject (QObject * object, QDeclarativeEngine * engine) static
Creates a QScriptValue allowing you to use object in QML script.
engine is the QDeclarativeEngine it is to be created in.
The QScriptValue returned is a QtScript Object, not a QtScript QObject, due to the special needs of QML requiring more functionality than a standard QtScript QObject.
Definition at line 1283 of file qdeclarativeengine.cpp.
Referenced by NestedListModel::get().
 {
     QDeclarativeEnginePrivate *enginePriv = QDeclarativeEnginePrivate::get(engine);
     return enginePriv->objectClass->newQObject(object);
 }
quit()
QScriptValue QDeclarativeEnginePrivate::quit (QScriptContext * , QScriptEngine * e) static
Definition at line 2047 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     QDeclarativeEnginePrivate *qe = get (e);
     qe->sendQuit();
     return QScriptValue();
 }
rawMetaObjectForType()
const QMetaObject * QDeclarativeEnginePrivate::rawMetaObjectForType (int t) const
Definition at line 2528 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeCompiler::buildPropertyObjectAssignment(), QDeclarativeCompiler::canCoerce(), QDeclarativeListReferencePrivate::init(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeListReference::QDeclarativeListReference(), QDeclarativePropertyPrivate::rawMetaObjectForType(), and QDeclarativePropertyPrivate::write().
 {
     QHash<int, QDeclarativeCompiledData*>::ConstIterator iter = m_compositeTypes.find(t);
     if (iter != m_compositeTypes.end()) {
         return (*iter)->root;
     } else {
         QDeclarativeType *type = QDeclarativeMetaType::qmlType(t);
         return type?type->baseMetaObject():0;
     }
 }
rect()
QScriptValue QDeclarativeEnginePrivate::rect (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1766 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 4)
         return ctxt->throwError(QLatin1String("Qt.rect(): Invalid arguments"));
     qsreal x = ctxt->argument(0).toNumber();
     qsreal y = ctxt->argument(1).toNumber();
     qsreal w = ctxt->argument(2).toNumber();
     qsreal h = ctxt->argument(3).toNumber();
     return QDeclarativeEnginePrivate::get(engine)->scriptValueFromVariant(QVariant::fromValue(QRectF(x, y, w, h)));
 }
registerCompositeType()
void QDeclarativeEnginePrivate::registerCompositeType (QDeclarativeCompiledData * data)
Definition at line 2471 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeCompiler::compileTree().
 {
     QByteArray name = data->root->className();
     QByteArray ptr = name + '*';
     QByteArray lst = "QDeclarativeListProperty<" + name + '>';
     int ptr_type = QMetaType::registerType(ptr.constData(), voidptr_destructor,
                                            voidptr_constructor);
     int lst_type = QMetaType::registerType(lst.constData(), voidptr_destructor,
                                            voidptr_constructor);
     m_qmlLists.insert(lst_type, ptr_type);
     m_compositeTypes.insert(ptr_type, data);
     data->addref();
 }
registerFinalizedParserStatusObject()
void QDeclarativeEnginePrivate::registerFinalizedParserStatusObject (QObject * obj, int index) inline
Definition at line 222 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeAbstractAnimation::setRunning(), and QDeclarativeBehavior::setTarget().
{
         finalizedParserStatus.append(qMakePair(QDeclarativeGuard<QObject>(obj), index));
     }
rgba()
QScriptValue QDeclarativeEnginePrivate::rgba (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1709 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     int argCount = ctxt->argumentCount();
     if(argCount < 3 || argCount > 4)
         return ctxt->throwError(QLatin1String("Qt.rgba(): Invalid arguments"));
     qsreal r = ctxt->argument(0).toNumber();
     qsreal g = ctxt->argument(1).toNumber();
     qsreal b = ctxt->argument(2).toNumber();
     qsreal a = (argCount == 4) ? ctxt->argument(3).toNumber() : 1;
     if (r < 0.0) r=0.0;
     if (r > 1.0) r=1.0;
     if (g < 0.0) g=0.0;
     if (g > 1.0) g=1.0;
     if (b < 0.0) b=0.0;
     if (b > 1.0) b=1.0;
     if (a < 0.0) a=0.0;
     if (a > 1.0) a=1.0;
     return engine->toScriptValue(QVariant::fromValue(QColor::fromRgbF(r, g, b, a)));
 }
scriptValueFromVariant()
QScriptValue QDeclarativeEnginePrivate::scriptValueFromVariant (const QVariant & val)
Definition at line 2131 of file qdeclarativeengine.cpp.
Referenced by fontFamilies(), QDeclarativeVMEMetaObject::metaCall(), point(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContextScriptClass::property(), QDeclarativeObjectScriptClass::property(), QDeclarativeVMEMetaObject::readVarProperty(), rect(), size(), and vector3d().
 {
     if (val.userType() == qMetaTypeId<QDeclarativeListReference>()) {
         QDeclarativeListReferencePrivate *p =
             QDeclarativeListReferencePrivate::get((QDeclarativeListReference*)val.constData());
         if (p->object) {
             return listClass->newList(p->property, p->propertyType);
         } else {
             return scriptEngine.nullValue();
         }
     } else if (val.userType() == qMetaTypeId<QList<QObject *> >()) {
         const QList<QObject *> &list = *(QList<QObject *>*)val.constData();
         QScriptValue rv = scriptEngine.newArray(list.count());
         for (int ii = 0; ii < list.count(); ++ii) {
             QObject *object = list.at(ii);
             rv.setProperty(ii, objectClass->newQObject(object));
         }
         return rv;
     } else if (QDeclarativeValueType *vt = valueTypes[val.userType()]) {
         return valueTypeClass->newObject(val, vt);
     }
     bool objOk;
     QObject *obj = QDeclarativeMetaType::toQObject(val, &objOk);
     if (objOk) {
         return objectClass->newQObject(obj);
     } else {
         return scriptEngine.toScriptValue(val);
     }
 }
scriptValueToVariant()
QVariant QDeclarativeEnginePrivate::scriptValueToVariant (const QScriptValue & val, int hint = QVariant::Invalid)
Definition at line 2162 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeVMEMetaObject::metaCall(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeVMEMetaObject::readVarPropertyAsVariant(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativeBinding::update(), and QDeclarativeExpressionPrivate::value().
 {
     QScriptDeclarativeClass *dc = QScriptDeclarativeClass::scriptClass(val);
     if (dc == objectClass)
         return QVariant::fromValue(objectClass->toQObject(val));
     else if (dc == valueTypeClass)
         return valueTypeClass->toVariant(val);
     else if (dc == contextClass)
         return QVariant();
     // Convert to a QList<QObject*> only if val is an array and we were explicitly hinted
     if (hint == qMetaTypeId<QList<QObject *> >() && val.isArray()) {
         QList<QObject *> list;
         int length = val.property(QLatin1String("length")).toInt32();
         for (int ii = 0; ii < length; ++ii) {
             QScriptValue arrayItem = val.property(ii);
             QObject *d = arrayItem.toQObject();
             list << d;
         }
         return QVariant::fromValue(list);
     }
     return val.toVariant();
 }
sendQuit()
void QDeclarativeEnginePrivate::sendQuit ()
Definition at line 1971 of file qdeclarativeengine.cpp.
Referenced by quit().
 {
     Q_Q(QDeclarativeEngine);
     emit q->quit();
     if (q->receivers(SIGNAL(quit())) == 0) {
         qWarning("Signal QDeclarativeEngine::quit() emitted, but no receivers connected to handle it.");
     }
 }
size()
QScriptValue QDeclarativeEnginePrivate::size (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1796 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 2)
         return ctxt->throwError(QLatin1String("Qt.size(): Invalid arguments"));
     qsreal w = ctxt->argument(0).toNumber();
     qsreal h = ctxt->argument(1).toNumber();
     return QDeclarativeEnginePrivate::get(engine)->scriptValueFromVariant(QVariant::fromValue(QSizeF(w, h)));
 }
tint()
QScriptValue QDeclarativeEnginePrivate::tint (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 2081 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 2)
         return ctxt->throwError(QLatin1String("Qt.tint(): Invalid arguments"));
     //get color
     QVariant v = ctxt->argument(0).toVariant();
     QColor color;
     if (v.userType() == QVariant::Color)
         color = v.value<QColor>();
     else if (v.userType() == QVariant::String) {
         bool ok;
         color = QDeclarativeStringConverters::colorFromString(v.toString(), &ok);
         if (!ok)
             return engine->nullValue();
     } else
         return engine->nullValue();
     //get tint color
     v = ctxt->argument(1).toVariant();
     QColor tintColor;
     if (v.userType() == QVariant::Color)
         tintColor = v.value<QColor>();
     else if (v.userType() == QVariant::String) {
         bool ok;
         tintColor = QDeclarativeStringConverters::colorFromString(v.toString(), &ok);
         if (!ok)
             return engine->nullValue();
     } else
         return engine->nullValue();
     //tint
     QColor finalColor;
     int a = tintColor.alpha();
     if (a == 0xFF)
         finalColor = tintColor;
     else if (a == 0x00)
         finalColor = color;
     else {
         qreal a = tintColor.alphaF();
         qreal inv_a = 1.0 - a;
         finalColor.setRgbF(tintColor.redF() * a + color.redF() * inv_a,
                            tintColor.greenF() * a + color.greenF() * inv_a,
                            tintColor.blueF() * a + color.blueF() * inv_a,
                            a + inv_a * color.alphaF());
     }
     return engine->toScriptValue(QVariant::fromValue(finalColor));
 }
toQObject()
QObject * QDeclarativeEnginePrivate::toQObject (const QVariant & v, bool * ok = 0) const
Definition at line 2507 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContext::setContextProperty(), QDeclarativeListAccessor::setList(), and QDeclarativePropertyPrivate::write().
 {
     int t = v.userType();
     if (t == QMetaType::QObjectStar || m_compositeTypes.contains(t)) {
         if (ok) *ok = true;
         return *(QObject **)(v.constData());
     } else {
         return QDeclarativeMetaType::toQObject(v, ok);
     }
 }
typeCategory()
QDeclarativeMetaType::TypeCategory QDeclarativeEnginePrivate::typeCategory (int t) const
Definition at line 2518 of file qdeclarativeengine.cpp.
Referenced by QDeclarativePropertyCache::Data::flagsForProperty().
 {
     if (m_compositeTypes.contains(t))
         return QDeclarativeMetaType::Object;
     else if (m_qmlLists.contains(t))
         return QDeclarativeMetaType::List;
     else
         return QDeclarativeMetaType::typeCategory(t);
 }
urlToLocalFileOrQrc()
QString QDeclarativeEnginePrivate::urlToLocalFileOrQrc (const QUrl & url) static
Definition at line 1313 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeImportsPrivate::add(), createPixmapDataSync(), QDeclarativeTypeData::dataReceived(), QDeclarativeImportedNamespace::find_helper(), QDeclarativeTypeLoader::get(), QDeclarativeTypeLoader::getQmldir(), QDeclarativeTypeLoader::getScript(), QDeclarativeInclude::include(), QDeclarativeBorderImage::load(), QDeclarativeAnimatedImage::load(), QDeclarativeDataLoader::load(), QDeclarativePixmapReader::processJob(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), QDeclarativeFontLoader::setSource(), and QDeclarativeInclude::worker_include().
 {
     if (url.scheme().compare(QLatin1String("qrc"), Qt::CaseInsensitive) == 0) {
         if (url.authority().isEmpty())
             return QLatin1Char(':') + url.path();
         return QString();
     }
     return url.toLocalFile();
 }
vector3d()
QScriptValue QDeclarativeEnginePrivate::vector3d (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 1501 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if(ctxt->argumentCount() != 3)
         return ctxt->throwError(QLatin1String("Qt.vector(): Invalid arguments"));
     qsreal x = ctxt->argument(0).toNumber();
     qsreal y = ctxt->argument(1).toNumber();
     qsreal z = ctxt->argument(2).toNumber();
     return QDeclarativeEnginePrivate::get(engine)->scriptValueFromVariant(QVariant::fromValue(QVector3D(x, y, z)));
 }
warning() [1/6]
void QDeclarativeEnginePrivate::warning (const QDeclarativeError & error)
Definition at line 1991 of file qdeclarativeengine.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), QDeclarativeContextData::addImportedScript(), QDeclarativeComponentPrivate::complete(), QDeclarativeWorkerScript::event(), QDeclarativeXMLHttpRequest::printError(), QDeclarativeBoundSignal::qt_metacall(), throwException(), QDeclarativeBinding::update(), warning(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     Q_Q(QDeclarativeEngine);
     q->warnings(QList<QDeclarativeError>() << error);
     if (outputWarningsToStdErr)
         dumpwarning(error);
 }
warning() [2/6]
void QDeclarativeEnginePrivate::warning (const QList< QDeclarativeError > & errors)
Definition at line 1999 of file qdeclarativeengine.cpp.
 {
     Q_Q(QDeclarativeEngine);
     q->warnings(errors);
     if (outputWarningsToStdErr)
         dumpwarning(errors);
 }
warning() [3/6]
void QDeclarativeEnginePrivate::warning (QDeclarativeEngine * engine, const QDeclarativeError & error) static
Definition at line 2007 of file qdeclarativeengine.cpp.
 {
     if (engine)
         QDeclarativeEnginePrivate::get(engine)->warning(error);
     else
         dumpwarning(error);
 }
warning() [4/6]
void QDeclarativeEnginePrivate::warning (QDeclarativeEngine * engine, const QList< QDeclarativeError > & error) static
Definition at line 2015 of file qdeclarativeengine.cpp.
 {
     if (engine)
         QDeclarativeEnginePrivate::get(engine)->warning(error);
     else
         dumpwarning(error);
 }
warning() [5/6]
void QDeclarativeEnginePrivate::warning (QDeclarativeEnginePrivate * engine, const QDeclarativeError & error) static
Definition at line 2023 of file qdeclarativeengine.cpp.
 {
     if (engine)
         engine->warning(error);
     else
         dumpwarning(error);
 }
warning() [6/6]
void QDeclarativeEnginePrivate::warning (QDeclarativeEnginePrivate * engine, const QList< QDeclarativeError > & error) static
Definition at line 2031 of file qdeclarativeengine.cpp.
 {
     if (engine)
         engine->warning(error);
     else
         dumpwarning(error);
 }
Properties
baseUrl
QUrl QDeclarativeEnginePrivate::baseUrl
Definition at line 189 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeScriptEngine::resolvedUrl().
bindValues
QList<SimpleList<QDeclarativeAbstractBinding> > QDeclarativeEnginePrivate::bindValues
Definition at line 217 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeComponentPrivate::begin(), and QDeclarativeComponentPrivate::beginDeferred().
capturedProperties
QPODVector<CapturedProperty, 16> QDeclarativeEnginePrivate::capturedProperties
Definition at line 160 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextScriptClass::property(), QDeclarativeObjectScriptClass::property(), and QDeclarativeQtScriptExpression::scriptValue().
captureProperties
bool QDeclarativeEnginePrivate::captureProperties
Definition at line 159 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextScriptClass::property(), QDeclarativeObjectScriptClass::property(), and QDeclarativeQtScriptExpression::scriptValue().
cleanup
QDeclarativeCleanup* QDeclarativeEnginePrivate::cleanup
Definition at line 178 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeCleanup::QDeclarativeCleanup().
componentAttached
QDeclarativeComponentAttached* QDeclarativeEnginePrivate::componentAttached
Definition at line 220 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeComponentPrivate::begin(), QDeclarativeComponentPrivate::beginDeferred(), and QDeclarativeComponent::qmlAttachedProperties().
contextClass
QDeclarativeContextScriptClass* QDeclarativeEnginePrivate::contextClass
Definition at line 167 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextData::addImportedScript(), QDeclarativeQtScriptExpression::eval(), QDeclarativeExpressionPrivate::evalInObjectScope(), QDeclarativeInclude::finished(), QDeclarativeInclude::include(), QDeclarativeExpressionPrivate::init(), QDeclarativeInclude::QDeclarativeInclude(), QDeclarativeObjectScriptClass::queryProperty(), QDeclarativeExpressionPrivate::scriptValue(), and QDeclarativeObjectScriptClass::setProperty().
erroredBindings
QDeclarativeDelayedError* QDeclarativeEnginePrivate::erroredBindings
Definition at line 181 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeDelayedError::addError(), and QDeclarativeComponentPrivate::complete().
finalizedParserStatus
QList<QPair<QDeclarativeGuard<QObject>,int> > QDeclarativeEnginePrivate::finalizedParserStatus
Definition at line 219 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeComponentPrivate::begin(), QDeclarativeComponentPrivate::beginDeferred(), and QDeclarativeComponentPrivate::complete().
globalClass
QDeclarativeGlobalScriptClass* QDeclarativeEnginePrivate::globalClass
Definition at line 175 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextData::addImportedScript(), QDeclarativeCompiler::checkDynamicMeta(), QDeclarativeCompiler::checkValidId(), QDeclarativeExpressionPrivate::evalInObjectScope(), QDeclarativeInclude::include(), QDeclarativeExpressionPrivate::init(), QDeclarativeEnginePrivate(), and QDeclarativeExpressionPrivate::scriptValue().
imageProviders
QHash<QString,QSharedPointer<QDeclarativeImageProvider> > QDeclarativeEnginePrivate::imageProviders
Definition at line 233 of file qdeclarativeengine_p.h.
importDatabase
QDeclarativeImportDatabase QDeclarativeEnginePrivate::importDatabase
Definition at line 241 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeTypeData::resolveTypes().
inBeginCreate
bool QDeclarativeEnginePrivate::inBeginCreate
Definition at line 226 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeComponentPrivate::begin(), and QDeclarativeComponentPrivate::beginDeferred().
inProgressCreations
int QDeclarativeEnginePrivate::inProgressCreations
Definition at line 182 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeDelayedError::addError(), QDeclarativeComponentPrivate::begin(), QDeclarativeComponentPrivate::beginDeferred(), and QDeclarativeComponentPrivate::complete().
isDebugging
bool QDeclarativeEnginePrivate::isDebugging
Definition at line 163 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeComponentPrivate::begin().
listClass
QDeclarativeListScriptClass* QDeclarativeEnginePrivate::listClass
Definition at line 173 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextScriptClass::property(), and QDeclarativeObjectScriptClass::property().
m_compositeTypes
QHash<int, QDeclarativeCompiledData *> QDeclarativeEnginePrivate::m_compositeTypes
Definition at line 270 of file qdeclarativeengine_p.h.
m_qmlLists
QHash<int, int> QDeclarativeEnginePrivate::m_qmlLists
Definition at line 269 of file qdeclarativeengine_p.h.
m_sharedScriptImports
QHash<QString, QScriptValue> QDeclarativeEnginePrivate::m_sharedScriptImports
Definition at line 272 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextData::addImportedScript().
mutex
QMutex QDeclarativeEnginePrivate::mutex mutable
Definition at line 238 of file qdeclarativeengine_p.h.
networkAccessManager
QNetworkAccessManager* QDeclarativeEnginePrivate::networkAccessManager mutable
Definition at line 230 of file qdeclarativeengine_p.h.
networkAccessManagerFactory
QDeclarativeNetworkAccessManagerFactory* QDeclarativeEnginePrivate::networkAccessManagerFactory mutable
Definition at line 231 of file qdeclarativeengine_p.h.
objectClass
QDeclarativeObjectScriptClass* QDeclarativeEnginePrivate::objectClass
Definition at line 170 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeTypeNameCache::add(), QDeclarativePropertyCache::append(), QDeclarativeObjectMethodScriptClass::connect(), createComponent(), QDeclarativeComponentPrivate::createObject(), createQmlObject(), QDeclarativeObjectScriptClass::destroy(), QDeclarativeObjectMethodScriptClass::disconnect(), QDeclarativeQtScriptExpression::eval(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeListScriptClass::property(), QDeclarativeTypeNameScriptClass::property(), QDeclarativeObjectMethodScriptClass::property(), QDeclarativeContextScriptClass::property(), QDeclarativePropertyCache::property(), qmlScriptObject(), QDeclarativeTypeNameScriptClass::queryProperty(), QDeclarativeContextScriptClass::queryProperty(), QDeclarativeVMEMetaObject::readVarProperty(), QDeclarativeCompiledBindingsPrivate::run(), QDeclarativeTypeNameScriptClass::setProperty(), QDeclarativeContextScriptClass::setProperty(), and QDeclarativeBinding::update().
offlineStoragePath
QString QDeclarativeEnginePrivate::offlineStoragePath
Definition at line 243 of file qdeclarativeengine_p.h.
outputWarningsToStdErr
bool QDeclarativeEnginePrivate::outputWarningsToStdErr
Definition at line 165 of file qdeclarativeengine_p.h.
parserStatus
QList<SimpleList<QDeclarativeParserStatus> > QDeclarativeEnginePrivate::parserStatus
Definition at line 218 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeComponentPrivate::begin(), and QDeclarativeComponentPrivate::beginDeferred().
propertyCache
QHash<const QMetaObject *, QDeclarativePropertyCache *> QDeclarativeEnginePrivate::propertyCache
Definition at line 252 of file qdeclarativeengine_p.h.
qml_debugging_enabled
bool QDeclarativeEnginePrivate::qml_debugging_enabled = false static
Definition at line 329 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeDebugHelper::enableDebugging(), QDeclarativeDebugServer::instance(), and QDeclarativeDebuggingEnabler::QDeclarativeDebuggingEnabler().
rootContext
QDeclarativeContext* QDeclarativeEnginePrivate::rootContext
Definition at line 162 of file qdeclarativeengine_p.h.
scriptEngine
QDeclarativeScriptEngine QDeclarativeEnginePrivate::scriptEngine
Definition at line 184 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeExpressionPrivate::evalInObjectScope(), and QDeclarativeEnginePrivate().
sharedContext
QDeclarativeContextData* QDeclarativeEnginePrivate::sharedContext
Definition at line 168 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeQtScriptExpression::eval(), and ContextData::getContext().
sharedScope
QObject* QDeclarativeEnginePrivate::sharedScope
Definition at line 169 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeQtScriptExpression::eval(), and ContextData::getScope().
typeLoader
QDeclarativeTypeLoader QDeclarativeEnginePrivate::typeLoader
Definition at line 240 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeBinding::createBinding(), QDeclarativeDomDocument::load(), QDeclarativeComponent::loadUrl(), and QDeclarativeComponent::setData().
typeNameClass
QDeclarativeTypeNameScriptClass* QDeclarativeEnginePrivate::typeNameClass
Definition at line 172 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeContextScriptClass::property(), and QDeclarativeObjectScriptClass::property().
typePropertyCache
QHash<QPair<QDeclarativeType *, int>, QDeclarativePropertyCache *> QDeclarativeEnginePrivate::typePropertyCache
Definition at line 253 of file qdeclarativeengine_p.h.
uniqueId
quint32 QDeclarativeEnginePrivate::uniqueId mutable
Definition at line 245 of file qdeclarativeengine_p.h.
valueTypeClass
QDeclarativeValueTypeScriptClass* QDeclarativeEnginePrivate::valueTypeClass
Definition at line 171 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeObjectScriptClass::property().
valueTypes
QDeclarativeValueTypeFactory QDeclarativeEnginePrivate::valueTypes
Definition at line 250 of file qdeclarativeengine_p.h.
Referenced by QDeclarativeCompiler::buildGroupedProperty(), QDeclarativeCompiler::compileAlias(), QDeclarativeCompiler::genValueTypeData(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeProperty::name(), QDeclarativeObjectScriptClass::property(), QDeclarativeProperty::propertyTypeName(), QDeclarativePropertyPrivate::readValueProperty(), QDeclarativeCompiledBindingsPrivate::run(), and QDeclarativePropertyPrivate::writeValueProperty().
workerScriptEngine
QDeclarativeWorkerScriptEngine* QDeclarativeEnginePrivate::workerScriptEngine
Definition at line 187 of file qdeclarativeengine_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeengine_p.h
/src/declarative/qml/qdeclarativeengine.cpp