Qt 4.8: QTgaHandler Class Reference
QTgaHandler Class Reference
#include <qtgahandler.h>
Public Functions
bool canRead () const
Returns true if an image can be read from the device (i.
QByteArray name () const
Use format() instead.
QVariant option (ImageOption option) const
Returns the value assigned to option as a QVariant.
QTgaHandler ()
bool read (QImage *image)
Read an image from the device, and stores it in image.
void setOption (ImageOption option, const QVariant &value)
Sets the option option with the value value.
bool supportsOption (ImageOption option) const
Returns true if the QImageIOHandler supports the option option; otherwise returns false.
~QTgaHandler ()
Public Functions inherited from QImageIOHandler
virtual int currentImageNumber () const
For image formats that support animation, this function returns the sequence number of the current image in the animation.
virtual QRect currentImageRect () const
Returns the rect of the current image.
QIODevice * device () const
Returns the device currently assigned to the QImageIOHandler.
QByteArray format () const
Returns the format that is currently assigned to QImageIOHandler.
virtual int imageCount () const
For image formats that support animation, this function returns the number of images in the animation.
virtual bool jumpToImage (int imageNumber)
For image formats that support animation, this function jumps to the image whose sequence number is imageNumber.
virtual bool jumpToNextImage ()
For image formats that support animation, this function jumps to the next image.
virtual int loopCount () const
For image formats that support animation, this function returns the number of times the animation should loop.
virtual int nextImageDelay () const
For image formats that support animation, this function returns the number of milliseconds to wait until reading the next image.
QImageIOHandler ()
Constructs a QImageIOHandler object.
void setDevice (QIODevice *device)
Sets the device of the QImageIOHandler to device.
void setFormat (const QByteArray &format)
Sets the format of the QImageIOHandler to format.
void setFormat (const QByteArray &format) const
Sets the format of the QImageIOHandler to format.
virtual bool write (const QImage &image)
Writes the image image to the assigned device.
virtual ~QImageIOHandler ()
Destructs the QImageIOHandler object.
Static Public Functions
static bool canRead (QIODevice *device)
Properties
QTgaFile * tga
Additional Inherited Members
Public Types inherited from QImageIOHandler
enum ImageOption {
Size, ClipRect, Description, ScaledClipRect,
ScaledSize, CompressionRatio, Gamma, Quality,
Name, SubType, IncrementalReading, Endianness,
Animation, BackgroundColor, ImageFormat
}
This enum describes the different options supported by QImageIOHandler.
Protected Functions inherited from QImageIOHandler
QImageIOHandler (QImageIOHandlerPrivate &dd)
Constructs a QImageIOHandler object, using the private member dd.
Protected Variables inherited from QImageIOHandler
QScopedPointer< QImageIOHandlerPrivate > d_ptr
Detailed Description
Definition at line 51 of file qtgahandler.h.
Constructors and Destructors
QTgaHandler()
QTgaHandler::QTgaHandler ()
Definition at line 51 of file qtgahandler.cpp.
     : QImageIOHandler()
     , tga(0)
 {
 }
~QTgaHandler()
QTgaHandler::~QTgaHandler ()
Definition at line 57 of file qtgahandler.cpp.
 {
     delete tga;
 }
Functions
canRead() [1/2]
bool QTgaHandler::canRead () const virtual
Returns true if an image can be read from the device (i.
e., the image format is supported, the device can be read from and the initial header information suggests that the image can be read); otherwise returns false.
When reimplementing canRead(), make sure that the I/O device (device()) is left in its original state (e.g., by using peek() rather than read()).
See also
read(), QIODevice::peek()
Implements QImageIOHandler.
Definition at line 62 of file qtgahandler.cpp.
Referenced by QTgaPlugin::capabilities(), option(), and read().
 {
     if (!tga)
         tga = new QTgaFile(device());
     if (tga->isValid())
     {
         setFormat("tga");
         return true;
     }
     return false;
 }
canRead() [2/2]
bool QTgaHandler::canRead (QIODevice * device) static
Definition at line 74 of file qtgahandler.cpp.
 {
     if (!device) {
         qWarning("QTgaHandler::canRead() called with no device");
         return false;
     }
     QTgaFile tga(device);
     return tga.isValid();
 }
name()
QByteArray QTgaHandler::name () const virtual
Use format() instead.
Reimplemented from QImageIOHandler.
Definition at line 92 of file qtgahandler.cpp.
 {
     return "tga";
 }
option()
QVariant QTgaHandler::option (ImageOption option) const virtual
Returns the value assigned to option as a QVariant.
The type of the value depends on the option. For example, option(Size) returns a QSize variant.
See also
setOption(), supportsOption()
Reimplemented from QImageIOHandler.
Definition at line 97 of file qtgahandler.cpp.
 {
     if (option == Size && canRead()) {
         return tga->size();
     } else if (option == CompressionRatio) {
         return tga->compression();
     } else if (option == ImageFormat) {
         return QImage::Format_ARGB32;
     }
     return QVariant();
 }
read()
bool QTgaHandler::read (QImage * image) virtual
Read an image from the device, and stores it in image.
Returns true if the image is successfully read; otherwise returns false.
For image formats that support incremental loading, and for animation formats, the image handler can assume that image points to the previous frame.
See also
canRead()
Implements QImageIOHandler.
Definition at line 84 of file qtgahandler.cpp.
 {
     if (!canRead())
         return false;
     *image = tga->readImage();
     return !image->isNull();
 }
setOption()
void QTgaHandler::setOption (ImageOption option, const QVariant & value) virtual
Sets the option option with the value value.
See also
option(), ImageOption
Reimplemented from QImageIOHandler.
Definition at line 109 of file qtgahandler.cpp.
 {
     Q_UNUSED(option);
     Q_UNUSED(value);
 }
supportsOption()
bool QTgaHandler::supportsOption (ImageOption option) const virtual
Returns true if the QImageIOHandler supports the option option; otherwise returns false.
For example, if the QImageIOHandler supports the Size option, supportsOption(Size) must return true.
See also
setOption(), option()
Reimplemented from QImageIOHandler.
Definition at line 115 of file qtgahandler.cpp.
 {
     return option == CompressionRatio
             || option == Size
             || option == ImageFormat;
 }
Properties
tga
QTgaFile* QTgaHandler::tga mutable private
Definition at line 69 of file qtgahandler.h.
Referenced by canRead(), option(), read(), and ~QTgaHandler().
The documentation for this class was generated from the following files:
/src/plugins/imageformats/tga/qtgahandler.h
/src/plugins/imageformats/tga/qtgahandler.cpp