Qt 4.8: QWindowSurface Class Reference
QWindowSurface Class Reference abstract
The QWindowSurface class provides the drawing area for top-level windows.
#include <qwindowsurface_p.h>
Public Types
enum WindowSurfaceFeature { PartialUpdates = 0x00000001, PreservedContents = 0x00000002, StaticContents = 0x00000004, AllFeatures = 0xffffffff }
Public Functions
virtual void beginPaint (const QRegion &)
This function is called before painting onto the surface begins, with the region in which the painting will occur.
virtual QImage * buffer (const QWidget *widget)
Returns a QImage pointer which represents the actual buffer the widget is drawn into or 0 if this is unavailable.
virtual void endPaint (const QRegion &)
This function is called after painting onto the surface has ended, with the region in which the painting was performed.
virtual WindowSurfaceFeatures features () const
virtual void flush (QWidget *widget, const QRegion &region, const QPoint &offset)=0
Flushes the given region from the specified widget onto the screen.
QRect geometry () const
Returns the currently allocated area on the screen.
virtual QPixmap grabWidget (const QWidget *widget, const QRect &rectangle=QRect()) const
Returns a QPixmap generated from the part of the backing store corresponding to widget.
bool hasFeature (WindowSurfaceFeature feature) const
virtual QPoint offset (const QWidget *widget) const
Returns the offset of widget in the coordinates of this window surface.
virtual QPaintDevice * paintDevice ()=0
Implement this function to return the appropriate paint device.
QWindowSurface (QWidget *window, bool setDefaultSurface=true)
Constructs an empty surface for the given top-level window.
QRect rect (const QWidget *widget) const
Returns the rectangle for widget in the coordinates of this window surface.
virtual bool scroll (const QRegion &area, int dx, int dy)
Scrolls the given area dx pixels to the right and dy downward; both dx and dy may be negative.
virtual void setGeometry (const QRect &rect)
Sets the currently allocated area to be the given rect.
void setStaticContents (const QRegion &region)
QRegion staticContents () const
QWidget * window () const
Returns a pointer to the top-level window associated with this surface.
virtual ~QWindowSurface ()
Destroys this surface.
Protected Functions
bool hasStaticContents () const
Properties
QWindowSurfacePrivate * d_ptr
Detailed Description
The QWindowSurface class provides the drawing area for top-level windows.
Since
4.3
Warning
This function is not part of the public interface. This function is under development and subject to change.
Definition at line 68 of file qwindowsurface_p.h.
Enumerations
WindowSurfaceFeature
enum QWindowSurface::WindowSurfaceFeature
Enumerator
PartialUpdates
PreservedContents
StaticContents
AllFeatures
Definition at line 71 of file qwindowsurface_p.h.
{
         PartialUpdates               = 0x00000001, // Supports doing partial updates.
         PreservedContents            = 0x00000002, // Supports doing flush without first doing a repaint.
         StaticContents               = 0x00000004, // Supports having static content regions when being resized.
         AllFeatures                  = 0xffffffff  // For convenience
     };
Constructors and Destructors
QWindowSurface()
QWindowSurface::QWindowSurface (QWidget * window, bool setDefaultSurface = true)
Constructs an empty surface for the given top-level window.
Definition at line 126 of file qwindowsurface.cpp.
     : d_ptr(new QWindowSurfacePrivate(window))
 {
     if (!QApplicationPrivate::runtime_graphics_system) {
         if(setDefaultSurface && window)
             window->setWindowSurface(this);
     }
 }
~QWindowSurface()
QWindowSurface::~QWindowSurface () virtual
Destroys this surface.
Definition at line 138 of file qwindowsurface.cpp.
 {
     if (d_ptr->window)
         d_ptr->window->d_func()->extra->topextra->windowSurface = 0;
     delete d_ptr;
 }
Functions
beginPaint()
void QWindowSurface::beginPaint (const QRegion & region) virtual
This function is called before painting onto the surface begins, with the region in which the painting will occur.
See also
endPaint(), paintDevice()
Reimplemented in QWSDirectPainterSurface, QWSMemorySurface, QRuntimeWindowSurface, QRasterWindowSurface, QFbWindowSurface, QGLWindowSurface, QDirectFBWindowSurface, QWSWindowSurface, QVGWindowSurface, QBBGLWindowSurface, QX11WindowSurface, QWaylandShmWindowSurface, QXlibWindowSurface, QXcbWindowSurface, QBBRasterWindowSurface, QDirectFbWindowSurface, ShivaVGWindowSurface, QTraceWindowSurface, and QWaylandGLWindowSurface.
Definition at line 154 of file qwindowsurface.cpp.
Referenced by QRuntimeWindowSurface::beginPaint(), QWidgetBackingStore::beginPaint(), and QWidgetBackingStore::removeDirtyWidget().
 {
 }
buffer()
QImage * QWindowSurface::buffer (const QWidget * widget) virtual
Returns a QImage pointer which represents the actual buffer the widget is drawn into or 0 if this is unavailable.
You must call beginPaint() before you call this function and the returned pointer is only valid until endPaint() is called.
Reimplemented in QRuntimeWindowSurface, and QGLWindowSurface.
Definition at line 229 of file qwindowsurface.cpp.
Referenced by QRuntimeWindowSurface::buffer(), and grabWidget().
 {
     if (widget->window() != window())
         return 0;
     QPaintDevice *pdev = paintDevice();
     if (!pdev || pdev->devType() != QInternal::Image)
         return 0;
     const QPoint off = offset(widget);
     QImage *img = static_cast<QImage*>(pdev);
     QRect rect(off, widget->size());
     rect &= QRect(QPoint(), img->size());
     if (rect.isEmpty())
         return 0;
     img = new QImage(img->scanLine(rect.y()) + rect.x() * img->depth() / 8,
                      rect.width(), rect.height(),
                      img->bytesPerLine(), img->format());
     d_ptr->bufferImages.append(img);
     return img;
 }
endPaint()
void QWindowSurface::endPaint (const QRegion & region) virtual
This function is called after painting onto the surface has ended, with the region in which the painting was performed.
See also
beginPaint(), paintDevice()
Reimplemented in QRuntimeWindowSurface, QFbWindowSurface, QGLWindowSurface, QDirectFBWindowSurface, QWSWindowSurface, QVGWindowSurface, QBBGLWindowSurface, QXlibWindowSurface, QXcbWindowSurface, QBBRasterWindowSurface, QDirectFbWindowSurface, ShivaVGWindowSurface, and QTraceWindowSurface.
Definition at line 158 of file qwindowsurface.cpp.
Referenced by QTraceWindowSurface::endPaint(), QRuntimeWindowSurface::endPaint(), QWidgetBackingStore::endPaint(), and QWidgetBackingStore::removeDirtyWidget().
 {
 //     QApplication::syncX();
     qDeleteAll(d_ptr->bufferImages);
     d_ptr->bufferImages.clear();
 }
features()
QWindowSurface::WindowSurfaceFeatures QWindowSurface::features () const virtual
Reimplemented in QRuntimeWindowSurface, QRasterWindowSurface, QGLWindowSurface, QVGWindowSurface, QX11WindowSurface, QBBGLWindowSurface, and QUIKitWindowSurface.
Definition at line 334 of file qwindowsurface.cpp.
Referenced by QRuntimeWindowSurface::features().
 {
     return PartialUpdates | PreservedContents;
 }
flush()
void QWindowSurface::flush (QWidget * widget, const QRegion & region, const QPoint & offset) pure virtual
Flushes the given region from the specified widget onto the screen.
Note that the offset parameter is currently unused.
Implemented in QDummyWindowSurface, QWSDirectPainterSurface, QWSYellowSurface, QRuntimeWindowSurface, QRasterWindowSurface, QFbWindowSurface, QGLWindowSurface, QDirectFBWindowSurface, QWSWindowSurface, QBBGLWindowSurface, QX11WindowSurface, QMacWindowSurface, QVGWindowSurface, QWaylandShmWindowSurface, QX11GLWindowSurface, PvrEglWindowSurface, QXlibWindowSurface, QCocoaWindowSurface, QBBRasterWindowSurface, QVFbWindowSurface, QWaylandGLWindowSurface, QXcbWindowSurface, QDirectFbWindowSurface, QEglFSWindowSurface, ShivaVGWindowSurface, QMinimalWindowSurface, and QUIKitWindowSurface.
Referenced by QRuntimeWindowSurface::flush(), QXcbWindow::handleExposeEvent(), and qt_flush().
geometry()
QRect QWindowSurface::geometry () const
Returns the currently allocated area on the screen.
Definition at line 182 of file qwindowsurface.cpp.
Referenced by QWidgetBackingStore::dirtyRegion(), effectiveState(), QDirectFBScreen::exposeRegion(), QXcbWindowSurface::flush(), QWSWindowSurface::flush(), QDirectFBWindowSurface::flush(), QGLWindowSurface::flush(), PvrEglWindowSurface::move(), QWSWindowSurface::move(), QDirectFBWindowSurface::move(), QTraceWindowSurface::paintDevice(), QWSOnScreenSurface::painterOffset(), QFbWindow::repaint(), QDirectFBWindowSurface::setGeometry(), QWSWindowSurface::setGeometry(), QFbWindow::setGeometry(), QRuntimeGraphicsSystem::setGraphicsSystem(), QFbWindow::setVisible(), QWidgetBackingStore::staticContents(), QWidgetBackingStore::sync(), and QGLWindowSurface::updateGeometry().
 {
     return d_ptr->geometry;
 }
grabWidget()
QPixmap QWindowSurface::grabWidget (const QWidget * widget, const QRect & rectangle = QRect()) const virtual
Returns a QPixmap generated from the part of the backing store corresponding to widget.
Returns a null QPixmap if an error occurs. The contents of the pixmap are only defined for the regions of widget that have received paint events since the last resize of the backing store.
If rectangle is a null rectangle (the default), the entire widget is grabbed. Otherwise, the grabbed area is limited to rectangle.
The default implementation uses QWindowSurface::buffer().
See also
QPixmap::grabWidget()
Reimplemented in QRuntimeWindowSurface, QX11WindowSurface, QX11GLWindowSurface, and QBBRasterWindowSurface.
Definition at line 269 of file qwindowsurface.cpp.
Referenced by QBBRasterWindowSurface::grabWidget(), and QRuntimeWindowSurface::grabWidget().
 {
     QPixmap result;
     if (widget->window() != window())
         return result;
     const QImage *img = const_cast<QWindowSurface *>(this)->buffer(widget->window());
     if (!img || img->isNull())
         return result;
     QRect rect = rectangle.isEmpty() ? widget->rect() : (widget->rect() & rectangle);
     rect.translate(offset(widget) - offset(widget->window()));
     rect &= QRect(QPoint(), img->size());
     if (rect.isEmpty())
         return result;
     QImage subimg(img->scanLine(rect.y()) + rect.x() * img->depth() / 8,
                   rect.width(), rect.height(),
                   img->bytesPerLine(), img->format());
     subimg.detach(); //### expensive -- maybe we should have a real SubImage that shares reference count
     result = QPixmap::fromImage(subimg);
     return result;
 }
hasFeature()
bool QWindowSurface::hasFeature (WindowSurfaceFeature feature) const inline
Definition at line 131 of file qwindowsurface_p.h.
Referenced by hasStaticContents(), QWidgetBackingStore::hasStaticContents(), QWidgetBackingStore::markDirty(), and QWidgetBackingStore::sync().
 {
     return (features() & feature) != 0;
 }
hasStaticContents()
bool QWindowSurface::hasStaticContents () const protected
Definition at line 329 of file qwindowsurface.cpp.
Referenced by QRasterWindowSurface::prepareBuffer(), and QX11WindowSurface::setGeometry().
 {
     return hasFeature(QWindowSurface::StaticContents) && !d_ptr->staticContents.isEmpty();
 }
offset()
QPoint QWindowSurface::offset (const QWidget * widget) const virtual
Returns the offset of widget in the coordinates of this window surface.
Reimplemented in QRuntimeWindowSurface.
Definition at line 302 of file qwindowsurface.cpp.
Referenced by addCircle(), QWSMemorySurface::beginPaint(), buffer(), QXlibWindowSurface::flush(), good_offset(), grabWidget(), PvrEglWindowSurface::key(), QRuntimeWindowSurface::offset(), QEglFSWindowSurface::paintDevice(), qt_scrollRectInImage(), QXcbWindowSurface::resize(), QRasterWindowSurface::setGeometry(), and shift().
 {
     QWidget *window = d_ptr->window;
     QPoint offset = widget->mapTo(window, QPoint());
 #ifdef Q_WS_QWS
     offset += window->geometry().topLeft() - window->frameGeometry().topLeft();
 #endif
     return offset;
 }
paintDevice()
QPaintDevice * QWindowSurface::paintDevice () pure virtual
Implement this function to return the appropriate paint device.
Implemented in QDummyWindowSurface, QWSDirectPainterSurface, QWSYellowSurface, QWSMemorySurface, QRuntimeWindowSurface, QRasterWindowSurface, QWSWindowSurface, QFbWindowSurface, QGLWindowSurface, QDirectFBWindowSurface, QBBGLWindowSurface, QX11WindowSurface, QMacWindowSurface, QVGWindowSurface, QWaylandShmWindowSurface, PvrEglWindowSurface, QX11GLWindowSurface, QXlibWindowSurface, QCocoaWindowSurface, QTraceWindowSurface, QBBRasterWindowSurface, QVFbWindowSurface, QWaylandGLWindowSurface, QXcbWindowSurface, QDirectFbWindowSurface, QEglFSWindowSurface, ShivaVGWindowSurface, QMinimalWindowSurface, EGLNullWSWindowSurface, and QUIKitWindowSurface.
Referenced by buffer(), QRuntimeWindowSurface::paintDevice(), QWidgetBackingStore::removeDirtyWidget(), and QWidgetBackingStore::sync().
rect()
QRect QWindowSurface::rect (const QWidget * widget) const inline
Returns the rectangle for widget in the coordinates of this window surface.
Definition at line 126 of file qwindowsurface_p.h.
Referenced by QWSMemorySurface::beginPaint(), buffer(), QDirectFbWindowSurface::flush(), QWaylandGLWindowSurface::flush(), QCocoaWindowSurface::flush(), QXlibWindowSurface::flush(), QWaylandShmWindowSurface::flush(), QMacWindowSurface::flush(), QGLWindowSurface::flush(), QRasterWindowSurface::flush(), grabWidget(), PvrEglWindowSurface::key(), PvrEglWindowSurface::move(), QGLWindowSurface::paintDevice(), QCocoaWindowSurface::QCocoaWindowSurface(), rect(), QXcbWindowSurface::resize(), QVFbWindowSurface::resize(), QX11GLWindowSurface::scroll(), QMacWindowSurface::scroll(), QX11WindowSurface::scroll(), QDirectFBWindowSurface::scroll(), scrollSurface(), PvrEglWindowSurface::setDirectRegion(), QWSWindowSurface::setGeometry(), setGeometry(), and QRasterWindowSurface::setGeometry().
 {
     return widget->rect().translated(offset(widget));
 }
scroll()
bool QWindowSurface::scroll (const QRegion & area, int dx, int dy) virtual
Scrolls the given area dx pixels to the right and dy downward; both dx and dy may be negative.
Returns true if the area was scrolled successfully; false otherwise.
Reimplemented in QWSMemorySurface, QRuntimeWindowSurface, QRasterWindowSurface, QFbWindowSurface, QGLWindowSurface, QDirectFBWindowSurface, QX11WindowSurface, QVGWindowSurface, QMacWindowSurface, QX11GLWindowSurface, QTraceWindowSurface, QXlibWindowSurface, QBBRasterWindowSurface, QXcbWindowSurface, QDirectFbWindowSurface, and ShivaVGWindowSurface.
Definition at line 213 of file qwindowsurface.cpp.
Referenced by QWidgetBackingStore::bltRect(), QWSMemorySurface::paintDevice(), ShivaVGWindowSurface::scroll(), QVGWindowSurface::scroll(), QFbWindowSurface::scroll(), and QRuntimeWindowSurface::scroll().
 {
     Q_UNUSED(area);
     Q_UNUSED(dx);
     Q_UNUSED(dy);
     return false;
 }
setGeometry()
void QWindowSurface::setGeometry (const QRect & rect) virtual
Sets the currently allocated area to be the given rect.
This function is called whenever area covered by the top-level window changes.
See also
geometry()
Reimplemented in QWSDirectPainterSurface, QWSSharedMemSurface, QWSLocalMemSurface, QRuntimeWindowSurface, QRasterWindowSurface, QGLWindowSurface, QX11WindowSurface, QWSWindowSurface, QDirectFBWindowSurface, QMacWindowSurface, QVGWindowSurface, QX11GLWindowSurface, PvrEglWindowSurface, and ShivaVGWindowSurface.
Definition at line 174 of file qwindowsurface.cpp.
Referenced by effectiveState(), isServerProcess(), QWSWindowSurface::move(), QWidgetBackingStore::releaseBuffer(), ShivaVGWindowSurface::setGeometry(), QX11GLWindowSurface::setGeometry(), QVGWindowSurface::setGeometry(), QMacWindowSurface::setGeometry(), QDirectFBWindowSurface::setGeometry(), QWSWindowSurface::setGeometry(), QX11WindowSurface::setGeometry(), QGLWindowSurface::setGeometry(), QRasterWindowSurface::setGeometry(), QRuntimeWindowSurface::setGeometry(), QRuntimeGraphicsSystem::setGraphicsSystem(), and QWidgetBackingStore::sync().
 {
     d_ptr->geometry = rect;
 }
setStaticContents()
void QWindowSurface::setStaticContents (const QRegion & region)
Definition at line 319 of file qwindowsurface.cpp.
Referenced by QWidgetBackingStore::sync().
 {
     d_ptr->staticContents = region;
 }
staticContents()
QRegion QWindowSurface::staticContents () const
Definition at line 324 of file qwindowsurface.cpp.
Referenced by QRasterWindowSurface::prepareBuffer(), and QX11WindowSurface::setGeometry().
 {
     return d_ptr->staticContents;
 }
window()
QWidget * QWindowSurface::window () const
Returns a pointer to the top-level window associated with this surface.
Definition at line 149 of file qwindowsurface.cpp.
Referenced by QWaylandGLWindowSurface::beginPaint(), QBBRasterWindowSurface::beginPaint(), QWaylandShmWindowSurface::beginPaint(), QBBGLWindowSurface::beginPaint(), QVGWindowSurface::beginPaint(), QDirectFBWindowSurface::beginPaint(), QGLWindowSurface::beginPaint(), QRasterWindowSurface::beginPaint(), QWidgetBackingStore::beginPaint(), QWSMemorySurface::beginPaint(), buffer(), QDirectFBWindowSurface::createWindow(), QGLWindowSurface::deleted(), QTraceWindowSurface::endPaint(), QBBRasterWindowSurface::endPaint(), QBBGLWindowSurface::endPaint(), QXcbWindowSurface::flush(), QBBRasterWindowSurface::flush(), QXlibWindowSurface::flush(), QX11GLWindowSurface::flush(), QVGWindowSurface::flush(), QWaylandShmWindowSurface::flush(), QBBGLWindowSurface::flush(), QWSWindowSurface::flush(), QDirectFBWindowSurface::flush(), QGLWindowSurface::flush(), QRasterWindowSurface::flush(), QX11GLWindowSurface::grabWidget(), QX11WindowSurface::grabWidget(), grabWidget(), QWSWindowSurface::invalidateBuffer(), EGLNullWSWindowSurface::isValid(), QWSMemorySurface::isValid(), QWSOnScreenSurface::isValid(), ShivaVGWindowSurface::metric(), QVGWindowSurface::metric(), offset(), ShivaVGWindowSurface::paintDevice(), QGLWindowSurface::paintDevice(), QWSWindowSurface::painterOffset(), QWSMemorySurface::painterOffset(), QWSOnScreenSurface::permanentState(), QRasterWindowSurface::prepareBuffer(), QBBGLWindowSurface::QBBGLWindowSurface(), QBBRasterWindowSurface::QBBRasterWindowSurface(), QCocoaWindowSurface::QCocoaWindowSurface(), QApplication::qwsProcessEvent(), QDirectFBWindowSurface::raise(), QXcbWindowSurface::resize(), QBBRasterWindowSurface::resize(), QWaylandGLWindowSurface::resize(), QWaylandShmWindowSurface::resize(), QBBGLWindowSurface::resize(), QBBRasterWindowSurface::scroll(), QGLWindowSurface::scroll(), QWSWindowSurface::setClipRegion(), PvrEglWindowSurface::setDirectRegion(), QX11GLWindowSurface::setGeometry(), QDirectFBWindowSurface::setGeometry(), QWSWindowSurface::setGeometry(), QRasterWindowSurface::setGeometry(), QWSLocalMemSurface::setGeometry(), QWSSharedMemSurface::setGeometry(), QRuntimeGraphicsSystem::setGraphicsSystem(), QDirectFBWindowSurface::surfaceForWidget(), QWidgetBackingStore::sync(), QGLWindowSurface::updateGeometry(), QDirectFBWindowSurface::updateIsOpaque(), QWidget::visibleRegion(), QBBGLWindowSurface::~QBBGLWindowSurface(), and QBBRasterWindowSurface::~QBBRasterWindowSurface().
 {
     return d_ptr->window;
 }
Properties
d_ptr
QWindowSurfacePrivate* QWindowSurface::d_ptr private
Definition at line 121 of file qwindowsurface_p.h.
Referenced by buffer(), endPaint(), geometry(), hasStaticContents(), offset(), setGeometry(), setStaticContents(), staticContents(), window(), and ~QWindowSurface().
The documentation for this class was generated from the following files:
/src/gui/painting/qwindowsurface_p.h
/src/gui/painting/qwindowsurface.cpp