Qt 4.8: QGLXContext Class Reference
QGLXContext Class Reference
#include <qglxintegration.h>
Public Functions
virtual void doneCurrent ()
Reimplement in subclass to release current context.
virtual void doneCurrent ()
Reimplement in subclass to release current context.
virtual void * getProcAddress (const QString &procName)
Reimplement in subclass to native getProcAddr calls.
virtual void * getProcAddress (const QString &procName)
Reimplement in subclass to native getProcAddr calls.
GLXContext glxContext () const
GLXContext glxContext () const
virtual void makeCurrent ()
Reimplement in subclass to do makeCurrent on native GL context.
virtual void makeCurrent ()
Reimplement in subclass to do makeCurrent on native GL context.
QPlatformWindowFormat platformWindowFormat () const
QWidget has the function qplatformWindowFormat().
QPlatformWindowFormat platformWindowFormat () const
QWidget has the function qplatformWindowFormat().
QGLXContext (Window window, QXcbScreen *xd, const QPlatformWindowFormat &format)
QGLXContext (Window window, QXlibScreen *xd, const QPlatformWindowFormat &format)
virtual void swapBuffers ()
Reimplement in subclass to native swap buffers calls.
virtual void swapBuffers ()
Reimplement in subclass to native swap buffers calls.
~QGLXContext ()
~QGLXContext ()
Public Functions inherited from QPlatformGLContext
QPlatformGLContext ()
All subclasses needs to specify the platformWindow.
virtual ~QPlatformGLContext ()
If this is the current context for the thread, doneCurrent is called.
Private Functions
QGLXContext (QXcbScreen *screen, Drawable drawable, GLXContext context)
QGLXContext (QXlibScreen *screen, Drawable drawable, GLXContext context)
Properties
GLXContext m_context
Drawable m_drawable
QXcbScreen * m_screen
QXlibScreen * m_screen
QPlatformWindowFormat m_windowFormat
Additional Inherited Members
Static Public Functions inherited from QPlatformGLContext
static const QPlatformGLContext * currentContext ()
Returns the last context which called makeCurrent.
Protected Variables inherited from QPlatformGLContext
QScopedPointer< QPlatformGLContextPrivate > d_ptr
Detailed Description
Definition at line 54 of file qglxintegration.h.
Constructors and Destructors
QGLXContext() [1/4]
QGLXContext::QGLXContext (Window window, QXcbScreen * xd, const QPlatformWindowFormat & format)
Definition at line 60 of file qglxintegration.cpp.
     : QPlatformGLContext()
     , m_screen(screen)
     , m_drawable((Drawable)window)
     , m_context(0)
 {
     Q_XCB_NOOP(m_screen->connection());
     const QPlatformGLContext *sharePlatformContext;
     sharePlatformContext = format.sharedGLContext();
     GLXContext shareGlxContext = 0;
     if (sharePlatformContext)
         shareGlxContext = static_cast<const QGLXContext*>(sharePlatformContext)->glxContext();
     GLXFBConfig config = qglx_findConfig(DISPLAY_FROM_XCB(screen),screen->screenNumber(),format);
     m_context = glXCreateNewContext(DISPLAY_FROM_XCB(screen), config, GLX_RGBA_TYPE, shareGlxContext, TRUE);
     m_windowFormat = qglx_platformWindowFromGLXFBConfig(DISPLAY_FROM_XCB(screen), config, m_context);
     Q_XCB_NOOP(m_screen->connection());
 }
~QGLXContext() [1/2]
QGLXContext::~QGLXContext ()
Definition at line 85 of file qglxintegration.cpp.
Referenced by QGLXContext().
 {
     Q_XCB_NOOP(m_screen->connection());
     if (m_context)
         glXDestroyContext(DISPLAY_FROM_XCB(m_screen), m_context);
     Q_XCB_NOOP(m_screen->connection());
 }
QGLXContext() [2/4]
QGLXContext::QGLXContext (QXcbScreen * screen, Drawable drawable, GLXContext context) private
Definition at line 79 of file qglxintegration.cpp.
     : QPlatformGLContext(), m_screen(screen), m_drawable(drawable), m_context(context)
 {
 }
QGLXContext() [3/4]
QGLXContext::QGLXContext (Window window, QXlibScreen * xd, const QPlatformWindowFormat & format)
Definition at line 62 of file qglxintegration.cpp.
     : QPlatformGLContext()
     , m_screen(screen)
     , m_drawable((Drawable)window)
     , m_context(0)
 {
     const QPlatformGLContext *sharePlatformContext;
     sharePlatformContext = format.sharedGLContext();
     GLXContext shareGlxContext = 0;
     if (sharePlatformContext)
         shareGlxContext = static_cast<const QGLXContext*>(sharePlatformContext)->glxContext();
     GLXFBConfig config = qglx_findConfig(screen->display()->nativeDisplay(),screen->xScreenNumber(),format);
     m_context = glXCreateNewContext(screen->display()->nativeDisplay(),config,GLX_RGBA_TYPE,shareGlxContext,TRUE);
     m_windowFormat = qglx_platformWindowFromGLXFBConfig(screen->display()->nativeDisplay(),config,m_context);
 #ifdef MYX11_DEBUG
     qDebug() << "QGLXGLContext::create context" << m_context;
 #endif
 }
~QGLXContext() [2/2]
QGLXContext::~QGLXContext ()
QGLXContext() [4/4]
QGLXContext::QGLXContext (QXlibScreen * screen, Drawable drawable, GLXContext context) private
Definition at line 84 of file qglxintegration.cpp.
     : QPlatformGLContext(), m_screen(screen), m_drawable(drawable), m_context(context)
 {
 }
Functions
doneCurrent() [1/2]
void QGLXContext::doneCurrent () virtual
Reimplement in subclass to release current context.
Typically this is calling makeCurrent with 0 "surface"
Reimplemented from QPlatformGLContext.
Definition at line 101 of file qglxintegration.cpp.
Referenced by QGLXContext().
 {
     Q_XCB_NOOP(m_screen->connection());
     QPlatformGLContext::doneCurrent();
     glXMakeCurrent(DISPLAY_FROM_XCB(m_screen), 0, 0);
     Q_XCB_NOOP(m_screen->connection());
 }
doneCurrent() [2/2]
virtual void QGLXContext::doneCurrent () virtual
Reimplement in subclass to release current context.
Typically this is calling makeCurrent with 0 "surface"
Reimplemented from QPlatformGLContext.
getProcAddress() [1/2]
void * QGLXContext::getProcAddress (const QString & procName) virtual
Reimplement in subclass to native getProcAddr calls.
Note: its convenient to use qPrintable(const QString &str) to get the const char * pointer
Implements QPlatformGLContext.
Definition at line 116 of file qglxintegration.cpp.
Referenced by QGLXContext().
 {
     Q_XCB_NOOP(m_screen->connection());
     typedef void *(*qt_glXGetProcAddressARB)(const GLubyte *);
     static qt_glXGetProcAddressARB glXGetProcAddressARB = 0;
     static bool resolved = false;
     if (resolved && !glXGetProcAddressARB)
         return 0;
     if (!glXGetProcAddressARB) {
         QList<QByteArray> glxExt = QByteArray(glXGetClientString(DISPLAY_FROM_XCB(m_screen), GLX_EXTENSIONS)).split(' ');
         if (glxExt.contains("GLX_ARB_get_proc_address")) {
 #if defined(Q_OS_LINUX) || defined(Q_OS_BSD4)
             void *handle = dlopen(NULL, RTLD_LAZY);
             if (handle) {
                 glXGetProcAddressARB = (qt_glXGetProcAddressARB) dlsym(handle, "glXGetProcAddressARB");
                 dlclose(handle);
             }
             if (!glXGetProcAddressARB)
 #endif
             {
                 extern const QString qt_gl_library_name();
 //                QLibrary lib(qt_gl_library_name());
                 QLibrary lib(QLatin1String("GL"));
                 glXGetProcAddressARB = (qt_glXGetProcAddressARB) lib.resolve("glXGetProcAddressARB");
             }
         }
         resolved = true;
     }
     if (!glXGetProcAddressARB)
         return 0;
     return glXGetProcAddressARB(reinterpret_cast<const GLubyte *>(procName.toLatin1().data()));
 }
getProcAddress() [2/2]
virtual void* QGLXContext::getProcAddress (const QString & procName) virtual
Reimplement in subclass to native getProcAddr calls.
Note: its convenient to use qPrintable(const QString &str) to get the const char * pointer
Implements QPlatformGLContext.
glxContext() [1/2]
GLXContext QGLXContext::glxContext () const inline
Definition at line 65 of file qglxintegration.h.
Referenced by QGLXContext().
 { return m_context; }
glxContext() [2/2]
GLXContext QGLXContext::glxContext () const inline
Definition at line 68 of file qglxintegration.h.
 {return m_context;}
makeCurrent() [1/2]
void QGLXContext::makeCurrent () virtual
Reimplement in subclass to do makeCurrent on native GL context.
Reimplemented from QPlatformGLContext.
Definition at line 93 of file qglxintegration.cpp.
Referenced by QGLXContext().
 {
     Q_XCB_NOOP(m_screen->connection());
     QPlatformGLContext::makeCurrent();
     glXMakeCurrent(DISPLAY_FROM_XCB(m_screen), m_drawable, m_context);
     Q_XCB_NOOP(m_screen->connection());
 }
makeCurrent() [2/2]
virtual void QGLXContext::makeCurrent () virtual
Reimplement in subclass to do makeCurrent on native GL context.
Reimplemented from QPlatformGLContext.
platformWindowFormat() [1/2]
QPlatformWindowFormat QGLXContext::platformWindowFormat () const virtual
QWidget has the function qplatformWindowFormat().
That function is for the application programmer to request the format of the window and the context that he wants.
Reimplement this function in a subclass to indicate what format the glContext actually has.
Implements QPlatformGLContext.
Definition at line 150 of file qglxintegration.cpp.
Referenced by glxContext(), and QGLXContext().
 {
     return m_windowFormat;
 }
platformWindowFormat() [2/2]
QPlatformWindowFormat QGLXContext::platformWindowFormat () const virtual
QWidget has the function qplatformWindowFormat().
That function is for the application programmer to request the format of the window and the context that he wants.
Reimplement this function in a subclass to indicate what format the glContext actually has.
Implements QPlatformGLContext.
swapBuffers() [1/2]
void QGLXContext::swapBuffers () virtual
Reimplement in subclass to native swap buffers calls.
Implements QPlatformGLContext.
Definition at line 109 of file qglxintegration.cpp.
Referenced by QGLXContext().
 {
     Q_XCB_NOOP(m_screen->connection());
     glXSwapBuffers(DISPLAY_FROM_XCB(m_screen), m_drawable);
     Q_XCB_NOOP(m_screen->connection());
 }
swapBuffers() [2/2]
virtual void QGLXContext::swapBuffers () virtual
Reimplement in subclass to native swap buffers calls.
Implements QPlatformGLContext.
Properties
m_context
GLXContext QGLXContext::m_context private
Definition at line 72 of file qglxintegration.h.
Referenced by glxContext(), makeCurrent(), QGLXContext(), and ~QGLXContext().
m_drawable
Drawable QGLXContext::m_drawable private
Definition at line 71 of file qglxintegration.h.
Referenced by makeCurrent(), QGLXContext(), and swapBuffers().
m_screen [1/2]
QXcbScreen* QGLXContext::m_screen private
Definition at line 70 of file qglxintegration.h.
Referenced by doneCurrent(), getProcAddress(), makeCurrent(), QGLXContext(), swapBuffers(), and ~QGLXContext().
m_screen [2/2]
QXlibScreen* QGLXContext::m_screen private
Definition at line 73 of file qglxintegration.h.
m_windowFormat
QPlatformWindowFormat QGLXContext::m_windowFormat private
Definition at line 73 of file qglxintegration.h.
Referenced by platformWindowFormat(), and QGLXContext().
The documentation for this class was generated from the following files:
/src/plugins/platforms/xcb/qglxintegration.h
/src/plugins/platforms/xcb/qglxintegration.cpp