Qt 4.8: QIsciiCodec Class Reference
QIsciiCodec Class Reference
The QIsciiCodec class provides conversion to and from the ISCII encoding.
#include <qisciicodec_p.h>
Public Functions
QByteArray convertFromUnicode (const QChar *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
QString convertToUnicode (const char *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
QIsciiCodec (int i)
~QIsciiCodec ()
Public Functions inherited from QTextCodec
virtual QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Properties
int idx
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
The QIsciiCodec class provides conversion to and from the ISCII encoding.
Warning
This function is not part of the public interface.
Definition at line 62 of file qisciicodec_p.h.
Constructors and Destructors
QIsciiCodec()
QIsciiCodec::QIsciiCodec (int i) inline explicit
Definition at line 64 of file qisciicodec_p.h.
 : idx(i) {}
~QIsciiCodec()
QIsciiCodec::~QIsciiCodec ()
Definition at line 76 of file qisciicodec.cpp.
Referenced by QIsciiCodec().
 {
 }
Functions
convertFromUnicode()
QByteArray QIsciiCodec::convertFromUnicode (const QChar * input, int number, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first number of characters from the input array from Unicode to the encoding of the subclass, and returns the result in a QByteArray.
state can be 0 in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 181 of file qisciicodec.cpp.
Referenced by QIsciiCodec().
 {
     char replacement = '?';
     bool halant = false;
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = 0;
         halant = state->state_data[0];
     }
     int invalid = 0;
     QByteArray result(2 * len, Qt::Uninitialized); //worst case
     uchar *ch = reinterpret_cast<uchar *>(result.data());
     const int base = codecs[idx].base;
     for (int i =0; i < len; ++i) {
         const ushort codePoint = uc[i].unicode();
         /* The low 7 bits of ISCII is plain ASCII. However, we go all the
          * way up to 0xA0 such that we can roundtrip with convertToUnicode()'s
          * behavior. */
         if(codePoint < 0xA0) {
             *ch++ = static_cast<uchar>(codePoint);
             continue;
         }
         const int pos = codePoint - base;
         if (pos > 0 && pos < 0x80) {
             uchar iscii = uni_to_iscii_table[pos];
             if (iscii > 0x80) {
                 *ch++ = iscii;
             } else if (iscii) {
                 const uchar *pair = uni_to_iscii_pairs + 2*iscii;
                 *ch++ = *pair++;
                 *ch++ = *pair++;
             } else {
                 *ch++ = replacement;
                 ++invalid;
             }
         } else {
             if (uc[i].unicode() == 0x200c) { // ZWNJ
                 if (halant)
                     // Consonant Halant ZWNJ -> Consonant Halant Halant
                     *ch++ = 0xe8;
             } else if (uc[i].unicode() == 0x200d) { // ZWJ
                 if (halant)
                     // Consonant Halant ZWJ -> Consonant Halant Nukta
                     *ch++ = 0xe9;
             } else {
                 *ch++ = replacement;
                 ++invalid;
             }
         }
         halant = (pos == 0x4d);
     }
     result.truncate(ch - (uchar *)result.data());
     if (state) {
         state->invalidChars += invalid;
         state->state_data[0] = halant;
     }
     return result;
 }
convertToUnicode()
QString QIsciiCodec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 247 of file qisciicodec.cpp.
Referenced by QIsciiCodec().
 {
     bool halant = false;
     if (state) {
         halant = state->state_data[0];
     }
     QString result(len, Qt::Uninitialized);
     QChar *uc = result.data();
     const int base = codecs[idx].base;
     for (int i = 0; i < len; ++i) {
         ushort ch = (uchar) chars[i];
         if (ch < 0xa0)
             *uc++ = ch;
         else {
             ushort c = iscii_to_uni_table[ch - 0xa0];
             if (halant && (c == inv || c == 0xe9)) {
                 // Consonant Halant inv -> Consonant Halant ZWJ
                 // Consonant Halant Nukta -> Consonant Halant ZWJ
                 *uc++ = QChar(0x200d);
             } else if (halant && c == 0xe8) {
                 // Consonant Halant Halant -> Consonant Halant ZWNJ
                 *uc++ = QChar(0x200c);
             } else {
                 *uc++ = QChar(c+base);
             }
         }
         halant = ((uchar)chars[i] == 0xe8);
     }
     result.resize(uc - result.unicode());
     if (state) {
         state->state_data[0] = halant;
     }
     return result;
 }
mibEnum()
int QIsciiCodec::mibEnum () const virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implements QTextCodec.
Definition at line 85 of file qisciicodec.cpp.
Referenced by QIsciiCodec().
 {
     /* There is no MIBEnum for Iscii */
     return -3000-idx;
 }
name()
QByteArray QIsciiCodec::name () const virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implements QTextCodec.
Definition at line 80 of file qisciicodec.cpp.
Referenced by QIsciiCodec().
 {
   return codecs[idx].name;
 }
Properties
idx
int QIsciiCodec::idx private
Definition at line 74 of file qisciicodec_p.h.
The documentation for this class was generated from the following files:
/src/corelib/codecs/qisciicodec_p.h
/src/corelib/codecs/qisciicodec.cpp