Qt 4.8: QDomDocument Class Reference
QDomDocument Class Reference
The QDomDocument class represents an XML document.
#include <qdom.h>
Public Functions
QDomAttr createAttribute (const QString &name)
Creates a new attribute called name that can be inserted into an element, e.g.
QDomAttr createAttributeNS (const QString &nsURI, const QString &qName)
Creates a new attribute with namespace support that can be inserted into an element.
QDomCDATASection createCDATASection (const QString &data)
Creates a new CDATA section for the string value that can be inserted into the document, e.g.
QDomComment createComment (const QString &data)
Creates a new comment for the string value that can be inserted into the document, e.g.
QDomDocumentFragment createDocumentFragment ()
Creates a new document fragment, that can be used to hold parts of the document, e.g.
QDomElement createElement (const QString &tagName)
Creates a new element called tagName that can be inserted into the DOM tree, e.g.
QDomElement createElementNS (const QString &nsURI, const QString &qName)
Creates a new element with namespace support that can be inserted into the DOM tree.
QDomEntityReference createEntityReference (const QString &name)
Creates a new entity reference called name that can be inserted into the document, e.g.
QDomProcessingInstruction createProcessingInstruction (const QString &target, const QString &data)
Creates a new processing instruction that can be inserted into the document, e.g.
QDomText createTextNode (const QString &data)
Creates a text node for the string value that can be inserted into the document tree, e.g.
QDomDocumentType doctype () const
Returns the document type of this document.
QDomElement documentElement () const
Returns the root element of the document.
QDomElement elementById (const QString &elementId)
Returns the element whose ID is equal to elementId.
QDomNodeList elementsByTagName (const QString &tagname) const
Returns a QDomNodeList, that contains all the elements in the document with the name tagname.
QDomNodeList elementsByTagNameNS (const QString &nsURI, const QString &localName)
Returns a QDomNodeList that contains all the elements in the document with the local name localName and a namespace URI of nsURI.
QDomImplementation implementation () const
Returns a QDomImplementation object.
QDomNode importNode (const QDomNode &importedNode, bool deep)
Imports the node importedNode from another document to this document.
QDomNode::NodeType nodeType () const
Returns DocumentNode.
QDomDocument & operator= (const QDomDocument &)
Assigns x to this DOM document.
QDomDocument ()
Constructs an empty document.
QDomDocument (const QString &name)
Creates a document and sets the name of the document type to name.
QDomDocument (const QDomDocumentType &doctype)
Creates a document with the document type doctype.
QDomDocument (const QDomDocument &x)
Constructs a copy of x.
bool setContent (const QByteArray &text, bool namespaceProcessing, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
bool setContent (const QString &text, bool namespaceProcessing, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
This function reads the XML document from the string text, returning true if the content was successfully parsed; otherwise returns false.
bool setContent (QIODevice *dev, bool namespaceProcessing, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
This function reads the XML document from the IO device dev, returning true if the content was successfully parsed; otherwise returns false.
bool setContent (QXmlInputSource *source, bool namespaceProcessing, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
This function reads the XML document from the QXmlInputSource source, returning true if the content was successfully parsed; otherwise returns false.
bool setContent (const QByteArray &text, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
This function reads the XML document from the byte array buffer, returning true if the content was successfully parsed; otherwise returns false.
bool setContent (const QString &text, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
This function reads the XML document from the string text, returning true if the content was successfully parsed; otherwise returns false.
bool setContent (QIODevice *dev, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
This function reads the XML document from the IO device dev, returning true if the content was successfully parsed; otherwise returns false.
bool setContent (QXmlInputSource *source, QXmlReader *reader, QString *errorMsg=0, int *errorLine=0, int *errorColumn=0)
This function reads the XML document from the QXmlInputSource source and parses it with the QXmlReader reader, returning true if the content was successfully parsed; otherwise returns false.
QByteArray toByteArray (int=1) const
Converts the parsed document back to its textual representation and returns a QByteArray containing the data encoded as UTF-8.
QString toString (int=1) const
Converts the parsed document back to its textual representation.
~QDomDocument ()
Destroys the object and frees its resources.
Public Functions inherited from QDomNode
QDomNode appendChild (const QDomNode &newChild)
Appends newChild as the node's last child.
QDomNamedNodeMap attributes () const
Returns a named node map of all attributes.
QDomNodeList childNodes () const
Returns a list of all direct child nodes.
void clear ()
Converts the node into a null node; if it was not a null node before, its type and contents are deleted.
QDomNode cloneNode (bool deep=true) const
Creates a deep (not shallow) copy of the QDomNode.
int columnNumber () const
For nodes created by QDomDocument::setContent(), this function returns the column number in the XML document where the node was parsed.
QDomNode firstChild () const
Returns the first child of the node.
QDomElement firstChildElement (const QString &tagName=QString()) const
Returns the first child element with tag name tagName if tagName is non-empty; otherwise returns the first child element.
bool hasAttributes () const
Returns true if the node has attributes; otherwise returns false.
bool hasChildNodes () const
Returns true if the node has one or more children; otherwise returns false.
QDomNode insertAfter (const QDomNode &newChild, const QDomNode &refChild)
Inserts the node newChild after the child node refChild.
QDomNode insertBefore (const QDomNode &newChild, const QDomNode &refChild)
Inserts the node newChild before the child node refChild.
bool isAttr () const
Returns true if the node is an attribute; otherwise returns false.
bool isCDATASection () const
Returns true if the node is a CDATA section; otherwise returns false.
bool isCharacterData () const
Returns true if the node is a character data node; otherwise returns false.
bool isComment () const
Returns true if the node is a comment; otherwise returns false.
bool isDocument () const
Returns true if the node is a document; otherwise returns false.
bool isDocumentFragment () const
Returns true if the node is a document fragment; otherwise returns false.
bool isDocumentType () const
Returns true if the node is a document type; otherwise returns false.
bool isElement () const
Returns true if the node is an element; otherwise returns false.
bool isEntity () const
Returns true if the node is an entity; otherwise returns false.
bool isEntityReference () const
Returns true if the node is an entity reference; otherwise returns false.
bool isNotation () const
Returns true if the node is a notation; otherwise returns false.
bool isNull () const
Returns true if this node is null (i.e.
bool isProcessingInstruction () const
Returns true if the node is a processing instruction; otherwise returns false.
bool isSupported (const QString &feature, const QString &version) const
Returns true if the DOM implementation implements the feature feature and this feature is supported by this node in the version version; otherwise returns false.
bool isText () const
Returns true if the node is a text node; otherwise returns false.
QDomNode lastChild () const
Returns the last child of the node.
QDomElement lastChildElement (const QString &tagName=QString()) const
Returns the last child element with tag name tagName if tagName is non-empty; otherwise returns the last child element.
int lineNumber () const
For nodes created by QDomDocument::setContent(), this function returns the line number in the XML document where the node was parsed.
QString localName () const
If the node uses namespaces, this function returns the local name of the node; otherwise it returns an empty string.
QDomNode namedItem (const QString &name) const
Returns the first direct child node for which nodeName() equals name.
QString namespaceURI () const
Returns the namespace URI of this node or an empty string if the node has no namespace URI.
QDomNode nextSibling () const
Returns the next sibling in the document tree.
QDomElement nextSiblingElement (const QString &taName=QString()) const
Returns the next sibling element with tag name tagName if tagName is non-empty; otherwise returns any next sibling element.
QString nodeName () const
Returns the name of the node.
NodeType nodeType () const
Returns the type of the node.
QString nodeValue () const
Returns the value of the node.
void normalize ()
Calling normalize() on an element converts all its children into a standard form.
bool operator!= (const QDomNode &) const
Returns true if n and this DOM node are not equal; otherwise returns false.
QDomNode & operator= (const QDomNode &)
Assigns a copy of n to this DOM node.
bool operator== (const QDomNode &) const
Returns true if n and this DOM node are equal; otherwise returns false.
QDomDocument ownerDocument () const
Returns the document to which this node belongs.
QDomNode parentNode () const
Returns the parent node.
QString prefix () const
Returns the namespace prefix of the node or an empty string if the node has no namespace prefix.
QDomNode previousSibling () const
Returns the previous sibling in the document tree.
QDomElement previousSiblingElement (const QString &tagName=QString()) const
Returns the previous sibilng element with tag name tagName if tagName is non-empty; otherwise returns any previous sibling element.
QDomNode ()
Constructs a null node.
QDomNode (const QDomNode &)
Constructs a copy of n.
QDomNode removeChild (const QDomNode &oldChild)
Removes oldChild from the list of children.
QDomNode replaceChild (const QDomNode &newChild, const QDomNode &oldChild)
Replaces oldChild with newChild.
void save (QTextStream &, int) const
Writes the XML representation of the node and all its children to the stream str.
void save (QTextStream &, int, EncodingPolicy) const
If encodingPolicy is QDomNode::EncodingFromDocument, this function behaves as save(QTextStream &str, int indent).
void setNodeValue (const QString &)
Sets the node's value to v.
void setPrefix (const QString &pre)
If the node has a namespace prefix, this function changes the namespace prefix of the node to pre.
QDomAttr toAttr () const
Converts a QDomNode into a QDomAttr.
QDomCDATASection toCDATASection () const
Converts a QDomNode into a QDomCDATASection.
QDomCharacterData toCharacterData () const
Converts a QDomNode into a QDomCharacterData.
QDomComment toComment () const
Converts a QDomNode into a QDomComment.
QDomDocument toDocument () const
Converts a QDomNode into a QDomDocument.
QDomDocumentFragment toDocumentFragment () const
Converts a QDomNode into a QDomDocumentFragment.
QDomDocumentType toDocumentType () const
Converts a QDomNode into a QDomDocumentType.
QDomElement toElement () const
Converts a QDomNode into a QDomElement.
QDomEntity toEntity () const
Converts a QDomNode into a QDomEntity.
QDomEntityReference toEntityReference () const
Converts a QDomNode into a QDomEntityReference.
QDomNotation toNotation () const
Converts a QDomNode into a QDomNotation.
QDomProcessingInstruction toProcessingInstruction () const
Converts a QDomNode into a QDomProcessingInstruction.
QDomText toText () const
Converts a QDomNode into a QDomText.
~QDomNode ()
Destroys the object and frees its resources.
Private Functions
QDomDocument (QDomDocumentPrivate *)
Friends
class QDomNode
Additional Inherited Members
Public Types inherited from QDomNode
enum EncodingPolicy { EncodingFromDocument = 1, EncodingFromTextStream = 2 }
This enum specifies how QDomNode::save() determines what encoding to use when serializing.
enum NodeType {
ElementNode = 1, AttributeNode = 2, TextNode = 3, CDATASectionNode = 4,
EntityReferenceNode = 5, EntityNode = 6, ProcessingInstructionNode = 7, CommentNode = 8,
DocumentNode = 9, DocumentTypeNode = 10, DocumentFragmentNode = 11, NotationNode = 12,
BaseNode = 21, CharacterDataNode = 22
}
This enum defines the type of the node:
Protected Functions inherited from QDomNode
QDomNode (QDomNodePrivate *)
Constructs a new node for the data n.
Protected Variables inherited from QDomNode
QDomNodePrivate * impl
Related Functions inherited from QDomNode
QTextStream & operator<< (QTextStream &str, const QDomNode &node)
Writes the XML representation of the node node and all its children to the stream str.
Detailed Description
The QDomDocument class represents an XML document.
Note
This class or function is reentrant.
Attention
Module: QtXml
The QDomDocument class represents the entire XML document. Conceptually, it is the root of the document tree, and provides the primary access to the document's data.
Since elements, text nodes, comments, processing instructions, etc., cannot exist outside the context of a document, the document class also contains the factory functions needed to create these objects. The node objects created have an ownerDocument() function which associates them with the document within whose context they were created. The DOM classes that will be used most often are QDomNode, QDomDocument, QDomElement and QDomText.
The parsed XML is represented internally by a tree of objects that can be accessed using the various QDom classes. All QDom classes only reference objects in the internal tree. The internal objects in the DOM tree will get deleted once the last QDom object referencing them and the QDomDocument itself are deleted.
Creation of elements, text nodes, etc. is done using the various factory functions provided in this class. Using the default constructors of the QDom classes will only result in empty objects that cannot be manipulated or inserted into the Document.
The QDomDocument class has several functions for creating document data, for example, createElement(), createTextNode(), createComment(), createCDATASection(), createProcessingInstruction(), createAttribute() and createEntityReference(). Some of these functions have versions that support namespaces, i.e. createElementNS() and createAttributeNS(). The createDocumentFragment() function is used to hold parts of the document; this is useful for manipulating for complex documents.
The entire content of the document is set with setContent(). This function parses the string it is passed as an XML document and creates the DOM tree that represents the document. The root element is available using documentElement(). The textual representation of the document can be obtained using toString().
Note
The DOM tree might end up reserving a lot of memory if the XML document is big. For big XML documents, the QXmlStreamReader or the QXmlQuery classes might be better solutions.
It is possible to insert a node from another document into the document using importNode().
You can obtain a list of all the elements that have a particular tag with elementsByTagName() or with elementsByTagNameNS().
The QDom classes are typically used as follows:
QDomDocument doc("mydocument");
QFile file("mydocument.xml");
if (!file.open(QIODevice::ReadOnly))
    return;
if (!doc.setContent(&file)) {
    file.close();
    return;
}
file.close();
// print out the element names of all elements that are direct children
// of the outermost element.
QDomElement docElem = doc.documentElement();
QDomNode n = docElem.firstChild();
while(!n.isNull()) {
    QDomElement e = n.toElement(); // try to convert the node to an element.
    if(!e.isNull()) {
        cout << qPrintable(e.tagName()) << endl; // the node really is an element.
    }
    n = n.nextSibling();
}
// Here we append a new element to the end of the document
QDomElement elem = doc.createElement("img");
elem.setAttribute("src", "myimage.png");
docElem.appendChild(elem);
Once doc and elem go out of scope, the whole internal tree representing the XML document is deleted.
To create a document using DOM use code like this:
QDomDocument doc("MyML");
QDomElement root = doc.createElement("MyML");
doc.appendChild(root);
QDomElement tag = doc.createElement("Greeting");
root.appendChild(tag);
QDomText t = doc.createTextNode("Hello World");
tag.appendChild(t);
QString xml = doc.toString();
For further information about the Document Object Model see the Document Object Model (DOM) Level 1 and Level 2 Core Specifications.
See also
{DOM Bookmarks Example}, {Simple DOM Model Example}
Definition at line 308 of file qdom.h.
Constructors and Destructors
QDomDocument() [1/5]
QDomDocument::QDomDocument ()
Constructs an empty document.
Definition at line 6751 of file qdom.cpp.
Referenced by QDomNode::toDocument().
 {
     impl = 0;
 }
QDomDocument() [2/5]
QDomDocument::QDomDocument (const QString & name) explicit
Creates a document and sets the name of the document type to name.
Definition at line 6760 of file qdom.cpp.
 {
     // We take over ownership
     impl = new QDomDocumentPrivate(name);
 }
QDomDocument() [3/5]
QDomDocument::QDomDocument (const QDomDocumentType & doctype) explicit
Creates a document with the document type doctype.
See also
QDomImplementation::createDocumentType()
Definition at line 6771 of file qdom.cpp.
 {
     impl = new QDomDocumentPrivate((QDomDocumentTypePrivate*)(doctype.impl));
 }
QDomDocument() [4/5]
QDomDocument::QDomDocument (const QDomDocument & x)
Constructs a copy of x.
The data of the copy is shared (shallow copy): modifying one node will also change the other. If you want to make a deep copy, use cloneNode().
Definition at line 6783 of file qdom.cpp.
     : QDomNode(x)
 {
 }
~QDomDocument()
QDomDocument::~QDomDocument ()
Destroys the object and frees its resources.
Definition at line 6808 of file qdom.cpp.
 {
 }
QDomDocument() [5/5]
QDomDocument::QDomDocument (QDomDocumentPrivate * x) private
Definition at line 6788 of file qdom.cpp.
     : QDomNode(x)
 {
 }
Functions
createAttribute()
QDomAttr QDomDocument::createAttribute (const QString & name)
Creates a new attribute called name that can be inserted into an element, e.g.
using QDomElement::setAttributeNode().
If name is not a valid XML name, the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
createAttributeNS()
Definition at line 7180 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomAttr(IMPL->createAttribute(name));
 }
createAttributeNS()
QDomAttr QDomDocument::createAttributeNS (const QString & nsURI, const QString & qName)
Creates a new attribute with namespace support that can be inserted into an element.
The name of the attribute is qName and the namespace URI is nsURI. This function also sets QDomNode::prefix() and QDomNode::localName() to appropriate values (depending on qName).
If qName is not a valid XML name, the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
createAttribute()
Definition at line 7320 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomAttr(IMPL->createAttributeNS(nsURI, qName));
 }
createCDATASection()
QDomCDATASection QDomDocument::createCDATASection (const QString & value)
Creates a new CDATA section for the string value that can be inserted into the document, e.g.
using QDomNode::appendChild().
If value contains characters which cannot be stored in a CDATA section, the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
QDomNode::appendChild() QDomNode::insertBefore() QDomNode::insertAfter()
Definition at line 7143 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomCDATASection(IMPL->createCDATASection(value));
 }
createComment()
QDomComment QDomDocument::createComment (const QString & value)
Creates a new comment for the string value that can be inserted into the document, e.g.
using QDomNode::appendChild().
If value contains characters which cannot be stored in an XML comment, the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
QDomNode::appendChild() QDomNode::insertBefore() QDomNode::insertAfter()
Definition at line 7126 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomComment(IMPL->createComment(value));
 }
createDocumentFragment()
QDomDocumentFragment QDomDocument::createDocumentFragment ()
Creates a new document fragment, that can be used to hold parts of the document, e.g.
when doing complex manipulations of the document tree.
Definition at line 7093 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomDocumentFragment(IMPL->createDocumentFragment());
 }
createElement()
QDomElement QDomDocument::createElement (const QString & tagName)
Creates a new element called tagName that can be inserted into the DOM tree, e.g.
using QDomNode::appendChild().
If tagName is not a valid XML name, the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
createElementNS() QDomNode::appendChild() QDomNode::insertBefore() QDomNode::insertAfter()
Definition at line 7081 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomElement(IMPL->createElement(tagName));
 }
createElementNS()
QDomElement QDomDocument::createElementNS (const QString & nsURI, const QString & qName)
Creates a new element with namespace support that can be inserted into the DOM tree.
The name of the element is qName and the namespace URI is nsURI. This function also sets QDomNode::prefix() and QDomNode::localName() to appropriate values (depending on qName).
If qName is an empty string, returns a null element regardless of whether the invalid data policy is set.
See also
createElement()
Definition at line 7301 of file qdom.cpp.
Referenced by QDomImplementation::createDocument().
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomElement(IMPL->createElementNS(nsURI, qName));
 }
createEntityReference()
QDomEntityReference QDomDocument::createEntityReference (const QString & name)
Creates a new entity reference called name that can be inserted into the document, e.g.
using QDomNode::appendChild().
If name is not a valid XML name, the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
QDomNode::appendChild() QDomNode::insertBefore() QDomNode::insertAfter()
Definition at line 7196 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomEntityReference(IMPL->createEntityReference(name));
 }
createProcessingInstruction()
QDomProcessingInstruction QDomDocument::createProcessingInstruction (const QString & target, const QString & data)
Creates a new processing instruction that can be inserted into the document, e.g.
using QDomNode::appendChild(). This function sets the target for the processing instruction to target and the data to data.
If target is not a valid XML name, or data if contains characters which cannot appear in a processing instruction, the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
QDomNode::appendChild() QDomNode::insertBefore() QDomNode::insertAfter()
Definition at line 7162 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomProcessingInstruction(IMPL->createProcessingInstruction(target, data));
 }
createTextNode()
QDomText QDomDocument::createTextNode (const QString & value)
Creates a text node for the string value that can be inserted into the document tree, e.g.
using QDomNode::appendChild().
If value contains characters which cannot be stored as character data of an XML document (even in the form of character references), the behavior of this function is governed by QDomImplementation::InvalidDataPolicy.
See also
QDomNode::appendChild() QDomNode::insertBefore() QDomNode::insertAfter()
Definition at line 7110 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomText(IMPL->createTextNode(value));
 }
doctype()
QDomDocumentType QDomDocument::doctype () const
Returns the document type of this document.
Definition at line 7044 of file qdom.cpp.
 {
     if (!impl)
         return QDomDocumentType();
     return QDomDocumentType(IMPL->doctype());
 }
documentElement()
QDomElement QDomDocument::documentElement () const
Returns the root element of the document.
Definition at line 7064 of file qdom.cpp.
 {
     if (!impl)
         return QDomElement();
     return QDomElement(IMPL->documentElement());
 }
elementById()
QDomElement QDomDocument::elementById (const QString & elementId)
Returns the element whose ID is equal to elementId.
If no element with the ID was found, this function returns a null element.
Since the QDomClasses do not know which attributes are element IDs, this function returns always a null element. This may change in a future version.
Definition at line 7349 of file qdom.cpp.
 {
     qWarning("elementById() is not implemented and will always return a null node.");
     return QDomElement();
 }
elementsByTagName()
QDomNodeList QDomDocument::elementsByTagName (const QString & tagname) const
Returns a QDomNodeList, that contains all the elements in the document with the name tagname.
The order of the node list is the order they are encountered in a preorder traversal of the element tree.
See also
elementsByTagNameNS() QDomElement::elementsByTagName()
Definition at line 7211 of file qdom.cpp.
 {
     return QDomNodeList(new QDomNodeListPrivate(impl, tagname));
 }
elementsByTagNameNS()
QDomNodeList QDomDocument::elementsByTagNameNS (const QString & nsURI, const QString & localName)
Returns a QDomNodeList that contains all the elements in the document with the local name localName and a namespace URI of nsURI.
The order of the node list is the order they are encountered in a preorder traversal of the element tree.
See also
elementsByTagName() QDomElement::elementsByTagNameNS()
Definition at line 7335 of file qdom.cpp.
 {
     return QDomNodeList(new QDomNodeListPrivate(impl, nsURI, localName));
 }
implementation()
QDomImplementation QDomDocument::implementation () const
Returns a QDomImplementation object.
Definition at line 7054 of file qdom.cpp.
 {
     if (!impl)
         return QDomImplementation();
     return QDomImplementation(IMPL->implementation());
 }
importNode()
QDomNode QDomDocument::importNode (const QDomNode & importedNode, bool deep)
Imports the node importedNode from another document to this document.
importedNode remains in the original document; this function creates a copy that can be used within this document.
This function returns the imported node that belongs to this document. The returned node has no parent. It is not possible to import QDomDocument and QDomDocumentType nodes. In those cases this function returns a null node.
If deep is true, this function imports not only the node importedNode but its whole subtree; if it is false, only the importedNode is imported. The argument deep has no effect on QDomAttr and QDomEntityReference nodes, since the descendants of QDomAttr nodes are always imported and those of QDomEntityReference nodes are never imported.
The behavior of this function is slightly different depending on the node types:
Node Type Behavior
QDomAttr The owner element is set to 0 and the specified flag is set to true in the generated attribute. The whole subtree of importedNode is always imported for attribute nodes: deep has no effect.
QDomDocument Document nodes cannot be imported.
QDomDocumentFragment If deep is true, this function imports the whole document fragment; otherwise it only generates an empty document fragment.
QDomDocumentType Document type nodes cannot be imported.
QDomElement Attributes for which QDomAttr::specified() is true are also imported, other attributes are not imported. If deep is true, this function also imports the subtree of importedNode; otherwise it imports only the element node (and some attributes, see above).
QDomEntity Entity nodes can be imported, but at the moment there is no way to use them since the document type is read-only in DOM level 2.
QDomEntityReference Descendants of entity reference nodes are never imported: deep has no effect.
QDomNotation Notation nodes can be imported, but at the moment there is no way to use them since the document type is read-only in DOM level 2.
QDomProcessingInstruction The target and value of the processing instruction is copied to the new node.
QDomText The text is copied to the new node.
QDomCDATASection The text is copied to the new node.
QDomComment The text is copied to the new node.
See also
QDomElement::setAttribute() QDomNode::insertBefore() QDomNode::insertAfter() QDomNode::replaceChild() QDomNode::removeChild() QDomNode::appendChild()
Definition at line 7282 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return QDomNode(IMPL->importNode(importedNode.impl, deep));
 }
nodeType()
QDomNode::NodeType QDomDocument::nodeType () const inline
Returns DocumentNode.
Definition at line 340 of file qdom.h.
 { return DocumentNode; }
operator=()
QDomDocument & QDomDocument::operator= (const QDomDocument & x)
Assigns x to this DOM document.
The data of the copy is shared (shallow copy): modifying one node will also change the other. If you want to make a deep copy, use cloneNode().
Definition at line 6800 of file qdom.cpp.
 {
     return (QDomDocument&) QDomNode::operator=(x);
 }
setContent() [1/8]
bool QDomDocument::setContent (const QByteArray & data, bool namespaceProcessing, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
Note
This class or function is not reentrant.
This function parses the XML document from the byte array data and sets it as the content of the document. It tries to detect the encoding of the document as required by the XML specification.
If namespaceProcessing is true, the parser recognizes namespaces in the XML file and sets the prefix name, local name and namespace URI to appropriate values. If namespaceProcessing is false, the parser does no namespace processing when it reads the XML file.
If a parse error occurs, this function returns false and the error message is placed in *{errorMsg}, the line number in *{errorLine} and the column number in *{errorColumn} (unless the associated pointer is set to 0); otherwise this function returns true. The various error messages are described in the QXmlParseException class documentation. Note that, if you want to display these error messages to your application's users, they will be displayed in English unless they are explicitly translated.
If namespaceProcessing is true, the function QDomNode::prefix() returns a string for all elements and attributes. It returns an empty string if the element or attribute has no prefix.
Text nodes consisting only of whitespace are stripped and won't appear in the QDomDocument. If this behavior is not desired, one can use the setContent() overload that allows a QXmlReader to be supplied.
If namespaceProcessing is false, the functions QDomNode::prefix(), QDomNode::localName() and QDomNode::namespaceURI() return an empty string.
Entity references are handled as follows:
References to internal general entities and character entities occurring in the content are included. The result is a QDomText node with the references replaced by their corresponding entity values.
References to parameter entities occurring in the internal subset are included. The result is a QDomDocumentType node which contains entity and notation declarations with the references replaced by their corresponding entity values.
Any general parsed entity reference which is not defined in the internal subset and which occurs in the content is represented as a QDomEntityReference node.
Any parsed entity reference which is not defined in the internal subset and which occurs outside of the content is replaced with an empty string.
Any unparsed entity reference is replaced with an empty string.
See also
QDomNode::namespaceURI() QDomNode::localName() QDomNode::prefix() QString::isNull() QString::isEmpty()
Definition at line 6887 of file qdom.cpp.
Referenced by QDBusXmlParser::QDBusXmlParser(), and setContent().
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     QBuffer buf;
     buf.setData(data);
     QXmlInputSource source(&buf);
     return IMPL->setContent(&source, namespaceProcessing, errorMsg, errorLine, errorColumn);
 }
setContent() [2/8]
bool QDomDocument::setContent (const QString & text, bool namespaceProcessing, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
This function reads the XML document from the string text, returning true if the content was successfully parsed; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since text is already a Unicode string, no encoding detection is done.
Definition at line 6823 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     QXmlInputSource source;
     source.setData(text);
     return IMPL->setContent(&source, namespaceProcessing, errorMsg, errorLine, errorColumn);
 }
setContent() [3/8]
bool QDomDocument::setContent (QIODevice * dev, bool namespaceProcessing, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
This function reads the XML document from the IO device dev, returning true if the content was successfully parsed; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 6906 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     QXmlInputSource source(dev);
     return IMPL->setContent(&source, namespaceProcessing, errorMsg, errorLine, errorColumn);
 }
setContent() [4/8]
bool QDomDocument::setContent (QXmlInputSource * source, bool namespaceProcessing, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
This function reads the XML document from the QXmlInputSource source, returning true if the content was successfully parsed; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Definition at line 6925 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     QXmlSimpleReader reader;
     initializeReader(reader, namespaceProcessing);
     return IMPL->setContent(source, &reader, errorMsg, errorLine, errorColumn);
 }
setContent() [5/8]
bool QDomDocument::setContent (const QByteArray & buffer, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
This function reads the XML document from the byte array buffer, returning true if the content was successfully parsed; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
No namespace processing is performed.
Definition at line 6964 of file qdom.cpp.
 {
     return setContent(buffer, false, errorMsg, errorLine, errorColumn);
 }
setContent() [6/8]
bool QDomDocument::setContent (const QString & text, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
This function reads the XML document from the string text, returning true if the content was successfully parsed; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since text is already a Unicode string, no encoding detection is performed.
No namespace processing is performed either.
Definition at line 6947 of file qdom.cpp.
 {
     return setContent(text, false, errorMsg, errorLine, errorColumn);
 }
setContent() [7/8]
bool QDomDocument::setContent (QIODevice * dev, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
This function reads the XML document from the IO device dev, returning true if the content was successfully parsed; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
No namespace processing is performed.
Definition at line 6980 of file qdom.cpp.
 {
     return setContent(dev, false, errorMsg, errorLine, errorColumn);
 }
setContent() [8/8]
bool QDomDocument::setContent (QXmlInputSource * source, QXmlReader * reader, QString * errorMsg = 0, int * errorLine = 0, int * errorColumn = 0)
This function reads the XML document from the QXmlInputSource source and parses it with the QXmlReader reader, returning true if the content was successfully parsed; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function doesn't change the features of the reader. If you want to use certain features for parsing you can use this function to set up the reader appropriately.
See also
QXmlSimpleReader
Definition at line 7001 of file qdom.cpp.
 {
     if (!impl)
         impl = new QDomDocumentPrivate();
     return IMPL->setContent(source, reader, errorMsg, errorLine, errorColumn);
 }
toByteArray()
QByteArray QDomDocument::toByteArray (int indent = 1) const
Converts the parsed document back to its textual representation and returns a QByteArray containing the data encoded as UTF-8.
This function uses indent as the amount of space to indent subelements.
See also
toString()
Definition at line 7033 of file qdom.cpp.
 {
     // ### if there is an encoding specified in the xml declaration, this
     // encoding declaration should be changed to utf8
     return toString(indent).toUtf8();
 }
toString()
QString QDomDocument::toString (int indent = 1) const
Converts the parsed document back to its textual representation.
This function uses indent as the amount of space to indent subelements.
If indent is -1, no whitespace at all is added.
Definition at line 7016 of file qdom.cpp.
Referenced by toByteArray().
 {
     QString str;
     QTextStream s(&str, QIODevice::WriteOnly);
     save(s, indent);
     return str;
 }
Friends and Related Functions
QDomNode
friend class QDomNode friend
Definition at line 359 of file qdom.h.
The documentation for this class was generated from the following files:
/src/xml/dom/qdom.h
/src/xml/dom/qdom.cpp