Qt 4.8: QTest::TestFunction Class Reference
QTest::TestFunction Class Reference
Public Functions
char * data () const
int function () const
void set (int function, char *data)
TestFunction ()
~TestFunction ()
Properties
char * data_
int function_
Detailed Description
Definition at line 905 of file qtestcase.cpp.
Constructors and Destructors
TestFunction()
QTest::TestFunction::TestFunction () inline
Definition at line 907 of file qtestcase.cpp.
 : function_(-1), data_(0) {}
~TestFunction()
QTest::TestFunction::~TestFunction () inline
Definition at line 911 of file qtestcase.cpp.
 { delete[] data_; }
Functions
data()
char* QTest::TestFunction::data () const inline
Definition at line 909 of file qtestcase.cpp.
Referenced by QTest::qElementData(), QTest::qInvokeTestMethod(), QTest::qInvokeTestMethods(), QTest::qtest_qParseArgs(), and set().
 { return data_; }
function()
int QTest::TestFunction::function () const inline
Definition at line 910 of file qtestcase.cpp.
Referenced by QTest::qInvokeTestMethods().
 { return function_; }
set()
void QTest::TestFunction::set (int function, char * data) inline
Definition at line 908 of file qtestcase.cpp.
Referenced by QTest::qtest_qParseArgs().
 { function_ = function; data_ = data; }
Properties
data_
char* QTest::TestFunction::data_ private
Definition at line 914 of file qtestcase.cpp.
Referenced by data(), set(), and ~TestFunction().
function_
int QTest::TestFunction::function_ private
Definition at line 913 of file qtestcase.cpp.
Referenced by function(), and set().
The documentation for this class was generated from the following file:
/src/testlib/qtestcase.cpp