Qt 4.8: QTextList Class Reference
QTextList Class Reference
The QTextList class provides a decorated list of items in a QTextDocument.
#include <qtextlist.h>
Public Functions
void add (const QTextBlock &block)
Makes the given block part of the list.
int count () const
Returns the number of items in the list.
QTextListFormat format () const
Returns the list's format.
bool isEmpty () const
Returns true if the list has no items; otherwise returns false.
QTextBlock item (int i) const
Returns the {i}-th text block in the list.
int itemNumber (const QTextBlock &) const
Returns the index of the list item that corresponds to the given block.
QString itemText (const QTextBlock &) const
Returns the text of the list item that corresponds to the given block.
QTextList (QTextDocument *doc)
void remove (const QTextBlock &)
Removes the given block from the list.
void removeItem (int i)
Removes the item at item position i from the list.
void setFormat (const QTextListFormat &format)
Sets the list's format to format.
~QTextList ()
Public Functions inherited from QTextObject
QTextDocumentPrivate * docHandle () const
QTextDocument * document () const
Returns the document this object belongs to.
QTextFormat format () const
Returns the text object's format.
int formatIndex () const
Returns the index of the object's format in the document's internal list of formats.
int objectIndex () const
Returns the object index of this object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QTextBlockGroup
virtual void blockFormatChanged (const QTextBlock &block)
This function is called whenever the specified block of text is changed.
virtual void blockInserted (const QTextBlock &block)
Appends the given block to the end of the group.
QList< QTextBlock > blockList () const
Returns a (possibly empty) list of all the blocks that are part of the block group.
virtual void blockRemoved (const QTextBlock &block)
Removes the given block from the group; the block itself is not deleted, it simply isn't a member of this group anymore.
QTextBlockGroup (QTextDocument *doc)
Creates a new new block group for the given document.
QTextBlockGroup (QTextBlockGroupPrivate &p, QTextDocument *doc)
~QTextBlockGroup ()
Destroys this block group; the blocks are not deleted, they simply don't belong to this block anymore.
Protected Functions inherited from QTextObject
QTextObject (QTextDocument *doc)
Creates a new QTextObject for the given document.
QTextObject (QTextObjectPrivate &p, QTextDocument *doc)
void setFormat (const QTextFormat &format)
Sets the text object's format.
~QTextObject ()
Destroys the text object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTextList class provides a decorated list of items in a QTextDocument.
Note
This class or function is reentrant.
A list contains a sequence of text blocks, each of which is marked with a bullet point or other symbol. Multiple levels of lists can be used, and the automatic numbering feature provides support for ordered numeric and alphabetical lists.
Lists are created by using a text cursor to insert an empty list at the current position or by moving existing text into a new list. The QTextCursor::insertList() function inserts an empty block into the document at the cursor position, and makes it the first item in a list.
    QTextListFormat listFormat;
    if (list) {
        listFormat = list->format();
        listFormat.setIndent(listFormat.indent() + 1);
    }
    listFormat.setStyle(QTextListFormat::ListDisc);
    cursor.insertList(listFormat);
The QTextCursor::createList() function takes the contents of the cursor's current block and turns it into the first item of a new list.
The cursor's current list is found with QTextCursor::currentList().
The number of items in a list is given by count(). Each item can be obtained by its index in the list with the item() function. Similarly, the index of a given item can be found with itemNumber(). The text of each item can be found with the itemText() function.
Note that the items in the list may not be adjacent elements in the document. For example, the top-level items in a multi-level list will be separated by the items in lower levels of the list.
List items can be deleted by index with the removeItem() function. remove() deletes the specified item in the list.
The list's format is set with setFormat() and read with format(). The format describes the decoration of the list itself, and not the individual items.
See also
QTextBlock, QTextListFormat, QTextCursor
Definition at line 57 of file qtextlist.h.
Constructors and Destructors
QTextList()
QTextList::QTextList (QTextDocument * doc) explicit
Warning
This function is not part of the public interface.
Definition at line 124 of file qtextlist.cpp.
     : QTextBlockGroup(*new QTextListPrivate(doc), doc)
 {
 }
~QTextList()
QTextList::~QTextList ()
Warning
This function is not part of the public interface.
Definition at line 132 of file qtextlist.cpp.
 {
 }
Functions
add()
void QTextList::add (const QTextBlock & block)
Makes the given block part of the list.
See also
remove(), removeItem()
Definition at line 332 of file qtextlist.cpp.
Referenced by QTextHtmlImporter::processBlockNode().
 {
     QTextBlockFormat fmt = block.blockFormat();
     fmt.setObjectIndex(objectIndex());
     block.docHandle()->setBlockFormat(block, block, fmt, QTextDocumentPrivate::SetFormat);
 }
count()
int QTextList::count () const
Returns the number of items in the list.
Definition at line 139 of file qtextlist.cpp.
Referenced by QTextHtmlExporter::emitBlock().
 {
     Q_D(const QTextList);
     return d->blocks.count();
 }
format()
QTextListFormat QTextList::format () const inline
Returns the list's format.
Definition at line 80 of file qtextlist.h.
Referenced by QTextHtmlExporter::emitBlock(), QTextControlPrivate::indent(), itemText(), QTextControlPrivate::outdent(), remove(), and QTextOdfWriter::writeBlock().
 { return QTextObject::format().toListFormat(); }
isEmpty()
bool QTextList::isEmpty () const inline
Returns true if the list has no items; otherwise returns false.
Note: Empty lists are automatically deleted by the QTextDocument that owns them.
See also
count()
Definition at line 66 of file qtextlist.h.
     { return count() == 0; }
item()
QTextBlock QTextList::item (int i) const
Returns the {i}-th text block in the list.
See also
count() itemText()
Definition at line 150 of file qtextlist.cpp.
Referenced by itemText().
 {
     Q_D(const QTextList);
     if (i < 0 || i >= d->blocks.size())
         return QTextBlock();
     return d->blocks.at(i);
 }
itemNumber()
int QTextList::itemNumber (const QTextBlock & block) const
Returns the index of the list item that corresponds to the given block.
Returns -1 if the block was not present in the list.
Definition at line 185 of file qtextlist.cpp.
Referenced by QTextHtmlExporter::emitBlock(), and QTextControlPrivate::indent().
 {
     Q_D(const QTextList);
     return d->blocks.indexOf(blockIt);
 }
itemText()
QString QTextList::itemText (const QTextBlock & block) const
Returns the text of the list item that corresponds to the given block.
Definition at line 199 of file qtextlist.cpp.
 {
     Q_D(const QTextList);
     int item = d->blocks.indexOf(blockIt) + 1;
     if (item <= 0)
         return QString();
     QTextBlock block = d->blocks.at(item-1);
     QTextBlockFormat blockFormat = block.blockFormat();
     QString result;
     const int style = format().style();
     QString numberPrefix;
     QString numberSuffix = QLatin1String(".");
     if (format().hasProperty(QTextFormat::ListNumberPrefix))
         numberPrefix = format().numberPrefix();
     if (format().hasProperty(QTextFormat::ListNumberSuffix))
         numberSuffix = format().numberSuffix();
     switch (style) {
         case QTextListFormat::ListDecimal:
             result = QString::number(item);
             break;
             // from the old richtext
         case QTextListFormat::ListLowerAlpha:
         case QTextListFormat::ListUpperAlpha:
             {
                 const char baseChar = style == QTextListFormat::ListUpperAlpha ? 'A' : 'a';
                 int c = item;
                 while (c > 0) {
                     c--;
                     result.prepend(QChar(baseChar + (c % 26)));
                     c /= 26;
                 }
             }
             break;
         case QTextListFormat::ListLowerRoman:
         case QTextListFormat::ListUpperRoman:
             {
                 if (item < 5000) {
                     QByteArray romanNumeral;
                     // works for up to 4999 items
                     static const char romanSymbolsLower[] = "iiivixxxlxcccdcmmmm";
                     static const char romanSymbolsUpper[] = "IIIVIXXXLXCCCDCMMMM";
                     QByteArray romanSymbols; // wrap to have "mid"
                     if (style == QTextListFormat::ListLowerRoman)
                         romanSymbols = QByteArray::fromRawData(romanSymbolsLower, sizeof(romanSymbolsLower));
                     else
                         romanSymbols = QByteArray::fromRawData(romanSymbolsUpper, sizeof(romanSymbolsUpper));
                     int c[] = { 1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000 };
                     int n = item;
                     for (int i = 12; i >= 0; n %= c[i], i--) {
                         int q = n / c[i];
                         if (q > 0) {
                             int startDigit = i + (i+3)/4;
                             int numDigits;
                             if (i % 4) {
                                 // c[i] == 4|5|9|40|50|90|400|500|900
                                 if ((i-2) % 4) {
                                     // c[i] == 4|9|40|90|400|900 => with subtraction (IV, IX, XL, XC, ...)
                                     numDigits = 2;
                                 }
                                 else {
                                     // c[i] == 5|50|500 (V, L, D)
                                     numDigits = 1;
                                 }
                             }
                             else {
                                 // c[i] == 1|10|100|1000 (I, II, III, X, XX, ...)
                                 numDigits = q;
                             }
                             romanNumeral.append(romanSymbols.mid(startDigit, numDigits));
                         }
                     }
                     result = QString::fromLatin1(romanNumeral);
                 }
                 else {
                     result = QLatin1String("?");
                 }
         }
         break;
         default:
             Q_ASSERT(false);
     }
     if (blockIt.textDirection() == Qt::RightToLeft)
         return numberSuffix + result + numberPrefix;
     else
         return numberPrefix + result + numberSuffix;
 }
remove()
void QTextList::remove (const QTextBlock & block)
Removes the given block from the list.
See also
add(), removeItem()
Definition at line 319 of file qtextlist.cpp.
Referenced by QTextControlPrivate::keyPressEvent(), QPlainTextEdit::keyReleaseEvent(), and QTextEdit::keyReleaseEvent().
 {
     QTextBlockFormat fmt = block.blockFormat();
     fmt.setIndent(fmt.indent() + format().indent());
     fmt.setObjectIndex(-1);
     block.docHandle()->setBlockFormat(block, block, fmt, QTextDocumentPrivate::SetFormat);
 }
removeItem()
void QTextList::removeItem (int i)
Removes the item at item position i from the list.
When the last item in the list is removed, the list is automatically deleted by the QTextDocument that owns it.
See also
add(), remove()
Definition at line 303 of file qtextlist.cpp.
 {
     Q_D(QTextList);
     if (i < 0 || i >= d->blocks.size())
         return;
     QTextBlock block = d->blocks.at(i);
     remove(block);
 }
setFormat()
void QTextList::setFormat (const QTextListFormat & format) inline
Sets the list's format to format.
Definition at line 87 of file qtextlist.h.
Referenced by QTextControlPrivate::indent(), and QTextControlPrivate::outdent().
 { QTextObject::setFormat(aformat); }
The documentation for this class was generated from the following files:
/src/gui/text/qtextlist.h
/src/gui/text/qtextlist.cpp