Qt 4.8: QBBGLContext Class Reference
QBBGLContext Class Reference
#include <qbbglcontext.h>
Public Functions
virtual void doneCurrent ()
Reimplement in subclass to release current context.
virtual void * getProcAddress (const QString &procName)
Reimplement in subclass to native getProcAddr calls.
virtual void makeCurrent ()
Reimplement in subclass to do makeCurrent on native GL context.
virtual QPlatformWindowFormat platformWindowFormat () const
QWidget has the function qplatformWindowFormat().
QBBGLContext (QBBWindow *platformWindow)
void resizeSurface (const QSize &size)
QSize surfaceSize () const
virtual void swapBuffers ()
Reimplement in subclass to native swap buffers calls.
virtual ~QBBGLContext ()
Public Functions inherited from QPlatformGLContext
QPlatformGLContext ()
All subclasses needs to specify the platformWindow.
virtual ~QPlatformGLContext ()
If this is the current context for the thread, doneCurrent is called.
Static Public Functions
static void initialize ()
static void shutdown ()
Static Public Functions inherited from QPlatformGLContext
static const QPlatformGLContext * currentContext ()
Returns the last context which called makeCurrent.
Private Functions
void createSurface ()
void destroySurface ()
bool isCurrent () const
Static Private Functions
static EGLint * contextAttrs ()
Properties
EGLConfig mEglConfig
EGLContext mEglContext
EGLSurface mEglSurface
QBBWindow * mPlatformWindow
QSize mSurfaceSize
QPlatformWindowFormat mWindowFormat
Static Private Attributes
static EGLDisplay sEglDisplay = EGL_NO_DISPLAY
Additional Inherited Members
Protected Variables inherited from QPlatformGLContext
QScopedPointer< QPlatformGLContextPrivate > d_ptr
Detailed Description
Definition at line 55 of file qbbglcontext.h.
Constructors and Destructors
QBBGLContext()
QBBGLContext::QBBGLContext (QBBWindow * platformWindow)
Definition at line 57 of file qbbglcontext.cpp.
     : QPlatformGLContext(),
       mPlatformWindow(platformWindow),
       mEglSurface(EGL_NO_SURFACE)
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::QBBGLContext - w=" << mPlatformWindow->widget();
 #endif
     // verify rendering API is correct
     QPlatformWindowFormat format = mPlatformWindow->widget()->platformWindowFormat();
     if (format.windowApi() != QPlatformWindowFormat::OpenGL) {
         qFatal("QBB: window API is not OpenGL");
     }
     // set current rendering API
     EGLBoolean eglResult = eglBindAPI(EGL_OPENGL_ES_API);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to set EGL API, err=%d", eglGetError());
     }
     // get colour channel sizes from window format
     int alphaSize = format.alphaBufferSize();
     int redSize = format.redBufferSize();
     int greenSize = format.greenBufferSize();
     int blueSize = format.blueBufferSize();
     // check if all channels are don't care
     if (alphaSize == -1 && redSize == -1 && greenSize == -1 && blueSize == -1) {
         // set colour channels based on depth of window's screen
         int depth = platformWindow->screen()->depth();
         if (depth == 32) {
             // SCREEN_FORMAT_RGBA8888
             alphaSize = 8;
             redSize = 8;
             greenSize = 8;
             blueSize = 8;
         } else {
             // SCREEN_FORMAT_RGB565
             alphaSize = 0;
             redSize = 5;
             greenSize = 6;
             blueSize = 5;
         }
     } else {
         // choose best match based on supported pixel formats
         if (alphaSize <= 0 && redSize <= 5 && greenSize <= 6 && blueSize <= 5) {
             // SCREEN_FORMAT_RGB565
             alphaSize = 0;
             redSize = 5;
             greenSize = 6;
             blueSize = 5;
         } else {
             // SCREEN_FORMAT_RGBA8888
             alphaSize = 8;
             redSize = 8;
             greenSize = 8;
             blueSize = 8;
         }
     }
     // update colour channel sizes in window format
     format.setAlphaBufferSize(alphaSize);
     format.setRedBufferSize(redSize);
     format.setGreenBufferSize(greenSize);
     format.setBlueBufferSize(blueSize);
     // select EGL config based on requested window format
     mEglConfig = q_configFromQPlatformWindowFormat(sEglDisplay, format);
     if (mEglConfig == 0) {
         qFatal("QBB: failed to find EGL config");
     }
     mEglContext = eglCreateContext(sEglDisplay, mEglConfig, EGL_NO_CONTEXT, contextAttrs());
     if (mEglContext == EGL_NO_CONTEXT) {
         qFatal("QBB: failed to create EGL context, err=%d", eglGetError());
     }
     // query/cache window format of selected EGL config
     mWindowFormat = qt_qPlatformWindowFormatFromConfig(sEglDisplay, mEglConfig);
 }
~QBBGLContext()
QBBGLContext::~QBBGLContext () virtual
Definition at line 142 of file qbbglcontext.cpp.
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::~QBBGLContext - w=" << mPlatformWindow->widget();
 #endif
     // cleanup EGL context if it exists
     if (mEglContext != EGL_NO_CONTEXT) {
         eglDestroyContext(sEglDisplay, mEglContext);
     }
     // cleanup EGL surface if it exists
     destroySurface();
 }
Functions
contextAttrs()
EGLint * QBBGLContext::contextAttrs () static private
Definition at line 303 of file qbbglcontext.cpp.
Referenced by QBBGLContext().
 {
     // choose EGL settings based on OpenGL version
 #if defined(QT_OPENGL_ES_2)
     static EGLint attrs[] = { EGL_CONTEXT_CLIENT_VERSION, 2, EGL_NONE };
     return attrs;
 #else
     return NULL;
 #endif
 }
createSurface()
void QBBGLContext::createSurface () private
Definition at line 319 of file qbbglcontext.cpp.
Referenced by makeCurrent(), and resizeSurface().
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::createSurface - w=" << mPlatformWindow->widget();
 #endif
     // create EGL surface
     mEglSurface = eglCreateWindowSurface(sEglDisplay, mEglConfig, (EGLNativeWindowType)mPlatformWindow->winId(), NULL);
     if (mEglSurface == EGL_NO_SURFACE) {
         qFatal("QBB: failed to create EGL surface, err=%d", eglGetError());
     }
 }
destroySurface()
void QBBGLContext::destroySurface () private
Definition at line 332 of file qbbglcontext.cpp.
Referenced by resizeSurface(), and ~QBBGLContext().
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::destroySurface - w=" << mPlatformWindow->widget();
 #endif
     // destroy EGL surface if it exists
     if (mEglSurface != EGL_NO_SURFACE) {
         EGLBoolean eglResult = eglDestroySurface(sEglDisplay, mEglSurface);
         if (eglResult != EGL_TRUE) {
             qFatal("QBB: failed to destroy EGL surface, err=%d", eglGetError());
         }
     }
 }
doneCurrent()
void QBBGLContext::doneCurrent () virtual
Reimplement in subclass to release current context.
Typically this is calling makeCurrent with 0 "surface"
Reimplemented from QPlatformGLContext.
Definition at line 214 of file qbbglcontext.cpp.
Referenced by resizeSurface().
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::doneCurrent - w=" << mPlatformWindow->widget();
 #endif
     // call the parent method
     QPlatformGLContext::doneCurrent();
     // set current rendering API
     EGLBoolean eglResult = eglBindAPI(EGL_OPENGL_ES_API);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to set EGL API, err=%d", eglGetError());
     }
     // clear curent EGL context and unbind EGL surface
     eglResult = eglMakeCurrent(sEglDisplay, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to clear current EGL context, err=%d", eglGetError());
     }
 }
getProcAddress()
void * QBBGLContext::getProcAddress (const QString & procName) virtual
Reimplement in subclass to native getProcAddr calls.
Note: its convenient to use qPrintable(const QString &str) to get the const char * pointer
Implements QPlatformGLContext.
Definition at line 261 of file qbbglcontext.cpp.
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::getProcAddress - w=" << mPlatformWindow->widget();
 #endif
     // set current rendering API
     EGLBoolean eglResult = eglBindAPI(EGL_OPENGL_ES_API);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to set EGL API, err=%d", eglGetError());
     }
     // lookup EGL extension function pointer
     return (void *)eglGetProcAddress( procName.toAscii().constData() );
 }
initialize()
void QBBGLContext::initialize () static
Definition at line 157 of file qbbglcontext.cpp.
Referenced by QBBIntegration::QBBIntegration().
 {
     // initialize connection to EGL
     sEglDisplay = eglGetDisplay(EGL_DEFAULT_DISPLAY);
     if (sEglDisplay == EGL_NO_DISPLAY) {
         qFatal("QBB: failed to obtain EGL display");
     }
     EGLBoolean eglResult = eglInitialize(sEglDisplay, NULL, NULL);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to initialize EGL display, err=%d", eglGetError());
     }
     // choose EGL settings based on OpenGL version
 #if defined(QT_OPENGL_ES_2)
     EGLint renderableType = EGL_OPENGL_ES2_BIT;
 #else
     EGLint renderableType = EGL_OPENGL_ES_BIT;
 #endif
 }
isCurrent()
bool QBBGLContext::isCurrent () const private
Definition at line 314 of file qbbglcontext.cpp.
Referenced by resizeSurface().
 {
     return (eglGetCurrentContext() == mEglContext);
 }
makeCurrent()
void QBBGLContext::makeCurrent () virtual
Reimplement in subclass to do makeCurrent on native GL context.
Reimplemented from QPlatformGLContext.
Definition at line 184 of file qbbglcontext.cpp.
Referenced by resizeSurface().
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::makeCurrent - w=" << mPlatformWindow->widget();
 #endif
     if (!mPlatformWindow->hasBuffers()) {
         // NOTE: create a dummy EGL surface since Qt will call makeCurrent() before
         // setting the geometry on the associated window
         mSurfaceSize = QSize(1, 1);
         mPlatformWindow->setBufferSize(mSurfaceSize);
         createSurface();
     }
     // call the parent method
     QPlatformGLContext::makeCurrent();
     // set current rendering API
     EGLBoolean eglResult = eglBindAPI(EGL_OPENGL_ES_API);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to set EGL API, err=%d", eglGetError());
     }
     // set current EGL context and bind with EGL surface
     eglResult = eglMakeCurrent(sEglDisplay, mEglSurface, mEglSurface, mEglContext);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to set current EGL context, err=%d", eglGetError());
     }
 }
platformWindowFormat()
virtual QPlatformWindowFormat QBBGLContext::platformWindowFormat () const inline virtual
QWidget has the function qplatformWindowFormat().
That function is for the application programmer to request the format of the window and the context that he wants.
Reimplement this function in a subclass to indicate what format the glContext actually has.
Implements QPlatformGLContext.
Definition at line 69 of file qbbglcontext.h.
Referenced by QBBWindow::setBufferSize().
 { return mWindowFormat; }
resizeSurface()
void QBBGLContext::resizeSurface (const QSize & size)
Definition at line 277 of file qbbglcontext.cpp.
Referenced by QBBGLWindowSurface::beginPaint(), platformWindowFormat(), and swapBuffers().
 {
     // need to destroy surface so make sure its not current
     bool restoreCurrent = false;
     if (isCurrent()) {
         doneCurrent();
         restoreCurrent = true;
     }
     // destroy old EGL surface
     destroySurface();
     // resize window's buffers
     mPlatformWindow->setBufferSize(size);
     // re-create EGL surface with new size
     mSurfaceSize = size;
     createSurface();
     // make context current again
     if (restoreCurrent) {
         makeCurrent();
         mPlatformWindow->widget()->update();
     }
 }
shutdown()
void QBBGLContext::shutdown () static
Definition at line 178 of file qbbglcontext.cpp.
Referenced by QBBIntegration::~QBBIntegration().
 {
     // close connection to EGL
     eglTerminate(sEglDisplay);
 }
surfaceSize()
QSize QBBGLContext::surfaceSize () const inline
Definition at line 72 of file qbbglcontext.h.
Referenced by QBBGLWindowSurface::beginPaint(), and QBBGLPaintDevice::size().
 { return mSurfaceSize; }
swapBuffers()
void QBBGLContext::swapBuffers () virtual
Reimplement in subclass to native swap buffers calls.
Implements QPlatformGLContext.
Definition at line 236 of file qbbglcontext.cpp.
Referenced by QBBGLWindowSurface::flush().
 {
 #if defined(QBBGLCONTEXT_DEBUG)
     qDebug() << "QBBGLContext::swapBuffers - w=" << mPlatformWindow->widget();
 #endif
     // set current rendering API
     EGLBoolean eglResult = eglBindAPI(EGL_OPENGL_ES_API);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to set EGL API, err=%d", eglGetError());
     }
     // post EGL surface to window
     eglResult = eglSwapBuffers(sEglDisplay, mEglSurface);
     if (eglResult != EGL_TRUE) {
         qFatal("QBB: failed to swap EGL buffers, err=%d", eglGetError());
     }
     // resize surface if window was resized
     QSize s = mPlatformWindow->geometry().size();
     if (s != mSurfaceSize) {
         resizeSurface(s);
     }
 }
Properties
mEglConfig
EGLConfig QBBGLContext::mEglConfig private
Definition at line 78 of file qbbglcontext.h.
Referenced by createSurface(), and QBBGLContext().
mEglContext
EGLContext QBBGLContext::mEglContext private
Definition at line 80 of file qbbglcontext.h.
Referenced by isCurrent(), makeCurrent(), QBBGLContext(), and ~QBBGLContext().
mEglSurface
EGLSurface QBBGLContext::mEglSurface private
Definition at line 81 of file qbbglcontext.h.
Referenced by createSurface(), destroySurface(), makeCurrent(), and swapBuffers().
mPlatformWindow
QBBWindow* QBBGLContext::mPlatformWindow private
Definition at line 79 of file qbbglcontext.h.
Referenced by createSurface(), destroySurface(), doneCurrent(), getProcAddress(), makeCurrent(), QBBGLContext(), resizeSurface(), swapBuffers(), and ~QBBGLContext().
mSurfaceSize
QSize QBBGLContext::mSurfaceSize private
Definition at line 82 of file qbbglcontext.h.
Referenced by makeCurrent(), resizeSurface(), surfaceSize(), and swapBuffers().
mWindowFormat
QPlatformWindowFormat QBBGLContext::mWindowFormat private
Definition at line 77 of file qbbglcontext.h.
Referenced by platformWindowFormat(), and QBBGLContext().
sEglDisplay
EGLDisplay QBBGLContext::sEglDisplay = EGL_NO_DISPLAY static private
Definition at line 75 of file qbbglcontext.h.
Referenced by createSurface(), destroySurface(), doneCurrent(), initialize(), makeCurrent(), QBBGLContext(), shutdown(), swapBuffers(), and ~QBBGLContext().
The documentation for this class was generated from the following files:
/src/plugins/platforms/blackberry/qbbglcontext.h
/src/plugins/platforms/blackberry/qbbglcontext.cpp