Qt 4.8: QSystemLocale Class Reference
QSystemLocale Class Reference
#include <qlocale.h>
Classes
struct CurrencyToStringArgument
Public Types
enum QueryType {
LanguageId, CountryId, DecimalPoint, GroupSeparator,
ZeroDigit, NegativeSign, DateFormatLong, DateFormatShort,
TimeFormatLong, TimeFormatShort, DayNameLong, DayNameShort,
MonthNameLong, MonthNameShort, DateToStringLong, DateToStringShort,
TimeToStringLong, TimeToStringShort, DateTimeFormatLong, DateTimeFormatShort,
DateTimeToStringLong, DateTimeToStringShort, MeasurementSystem, PositiveSign,
AMText, PMText, FirstDayOfWeek, Weekdays,
CurrencySymbol, CurrencyToString, UILanguages, StringToStandardQuotation,
StringToAlternateQuotation, ScriptId, ListToSeparatedString, LocaleChanged,
NativeLanguageName, NativeCountryName, StandaloneMonthNameLong, StandaloneMonthNameShort
}
Public Functions
virtual QLocale fallbackLocale () const
QSystemLocale ()
Constructs a QSystemLocale object.
virtual QVariant query (QueryType type, QVariant in) const
virtual ~QSystemLocale ()
Deletes the object.
Private Functions
QSystemLocale (bool)
Friends
QSystemLocale * QSystemLocale_globalSystemLocale ()
Detailed Description
Definition at line 66 of file qlocale.h.
Enumerations
QueryType
enum QSystemLocale::QueryType
Enumerator
LanguageId
CountryId
DecimalPoint
GroupSeparator
ZeroDigit
NegativeSign
DateFormatLong
DateFormatShort
TimeFormatLong
TimeFormatShort
DayNameLong
DayNameShort
MonthNameLong
MonthNameShort
DateToStringLong
DateToStringShort
TimeToStringLong
TimeToStringShort
DateTimeFormatLong
DateTimeFormatShort
DateTimeToStringLong
DateTimeToStringShort
MeasurementSystem
PositiveSign
AMText
PMText
FirstDayOfWeek
Weekdays
CurrencySymbol
CurrencyToString
UILanguages
StringToStandardQuotation
StringToAlternateQuotation
ScriptId
ListToSeparatedString
LocaleChanged
NativeLanguageName
NativeCountryName
StandaloneMonthNameLong
StandaloneMonthNameShort
Definition at line 81 of file qlocale.h.
                    {
         LanguageId, // uint
         CountryId, // uint
         DecimalPoint, // QString
         GroupSeparator, // QString
         ZeroDigit, // QString
         NegativeSign, // QString
         DateFormatLong, // QString
         DateFormatShort, // QString
         TimeFormatLong, // QString
         TimeFormatShort, // QString
         DayNameLong, // QString, in: int
         DayNameShort, // QString, in: int
         MonthNameLong, // QString, in: int
         MonthNameShort, // QString, in: int
         DateToStringLong, // QString, in: QDate
         DateToStringShort, // QString in: QDate
         TimeToStringLong, // QString in: QTime
         TimeToStringShort, // QString in: QTime
         DateTimeFormatLong, // QString
         DateTimeFormatShort, // QString
         DateTimeToStringLong, // QString in: QDateTime
         DateTimeToStringShort, // QString in: QDateTime
         MeasurementSystem, // uint
         PositiveSign, // QString
         AMText, // QString
         PMText, // QString
         FirstDayOfWeek, // Qt::DayOfWeek
         Weekdays, // QList<Qt::DayOfWeek>
         CurrencySymbol, // QString in: CurrencyToStringArgument
         CurrencyToString, // QString in: qlonglong, qulonglong or double
         UILanguages, // QStringList
         StringToStandardQuotation, // QString in: QStringRef to quote
         StringToAlternateQuotation, // QString in: QStringRef to quote
         ScriptId, // uint
         ListToSeparatedString, // QString
         LocaleChanged, // system locale changed
         NativeLanguageName, // QString
         NativeCountryName, // QString
         StandaloneMonthNameLong, // QString, in: int
         StandaloneMonthNameShort // QString, in: int
     };
Constructors and Destructors
QSystemLocale() [1/2]
QSystemLocale::QSystemLocale ()
Constructs a QSystemLocale object.
The constructor will automatically install this object as the system locale and remove any earlier installed system locales.
Definition at line 445 of file qlocale.cpp.
 {
     delete _systemLocale;
     _systemLocale = this;
     if (system_lp)
         system_lp->m_language_id = 0;
 }
~QSystemLocale()
QSystemLocale::~QSystemLocale () virtual
Deletes the object.
Definition at line 461 of file qlocale.cpp.
 {
     if (_systemLocale == this) {
         _systemLocale = 0;
         if (system_lp)
             system_lp->m_language_id = 0;
     }
 }
QSystemLocale() [2/2]
QSystemLocale::QSystemLocale (bool) private
Warning
This function is not part of the public interface.
Definition at line 455 of file qlocale.cpp.
 { }
Functions
fallbackLocale()
QLocale QSystemLocale::fallbackLocale () const virtual
Definition at line 263 of file qlocale_blackberry.cpp.
Referenced by macQuoteString(), QLocalePrivate::updateSystemPrivate(), and QSystemLocalePrivate::winToQtFormat().
 {
     return bbSysLocaleData()->languageLocale();
 }
query()
QVariant QSystemLocale::query (QueryType type, QVariant in = QVariant()) const virtual
Definition at line 268 of file qlocale_blackberry.cpp.
Referenced by QLocale::amText(), QLocale::createSeparatedList(), QLocale::currencySymbol(), QLocale::dateFormat(), QLocale::dateTimeFormat(), QLocale::dayName(), QLocale::firstDayOfWeek(), macQuoteString(), QLocale::measurementSystem(), QLocale::monthName(), QLocale::nativeCountryName(), QLocale::nativeLanguageName(), QLocale::pmText(), QLocale::quoteString(), QLocale::standaloneDayName(), QLocale::standaloneMonthName(), QLocale::timeFormat(), QLocale::toCurrencyString(), QLocale::toString(), QLocale::uiLanguages(), QLocalePrivate::updateSystemPrivate(), QLocale::weekdays(), and QSystemLocalePrivate::winToQtFormat().
 {
     QBBSystemLocaleData *d = bbSysLocaleData();
     QReadLocker locker(&d->lock);
     const QLocale &lc_language = d->languageLocale();
     const QLocale &lc_region = d->regionLocale();
     switch (type) {
     case DecimalPoint:
         return lc_region.decimalPoint();
     case GroupSeparator:
         return lc_region.groupSeparator();
     case NegativeSign:
         return lc_region.negativeSign();
     case PositiveSign:
         return lc_region.positiveSign();
     case DateFormatLong:
         return lc_region.dateFormat(QLocale::LongFormat);
     case DateFormatShort:
         return lc_region.dateFormat(QLocale::ShortFormat);
     case TimeFormatLong:
         return d->timeFormat(QLocale::LongFormat);
     case TimeFormatShort:
         return d->timeFormat(QLocale::ShortFormat);
     case DateTimeFormatLong:
         return d->dateTimeFormat(QLocale::LongFormat);
     case DateTimeFormatShort:
         return d->dateTimeFormat(QLocale::ShortFormat);
     case DayNameLong:
         return lc_language.dayName(in.toInt(), QLocale::LongFormat);
     case DayNameShort:
         return lc_language.dayName(in.toInt(), QLocale::ShortFormat);
     case MonthNameLong:
         return lc_language.monthName(in.toInt(), QLocale::LongFormat);
     case MonthNameShort:
         return lc_language.monthName(in.toInt(), QLocale::ShortFormat);
     case StandaloneMonthNameLong:
          return lc_language.standaloneMonthName(in.toInt(), QLocale::LongFormat);
     case StandaloneMonthNameShort:
          return lc_language.standaloneMonthName(in.toInt(), QLocale::ShortFormat);
     case DateToStringLong:
         return lc_region.toString(in.toDate(), QLocale::LongFormat);
     case DateToStringShort:
         return lc_region.toString(in.toDate(), QLocale::ShortFormat);
     case TimeToStringLong:
         return lc_region.toString(in.toTime(), d->timeFormat(QLocale::LongFormat).toString());
     case TimeToStringShort:
         return lc_region.toString(in.toTime(), d->timeFormat(QLocale::ShortFormat).toString());
     case DateTimeToStringShort:
         return lc_region.toString(in.toDateTime(), d->dateTimeFormat(QLocale::ShortFormat).toString());
     case DateTimeToStringLong:
         return lc_region.toString(in.toDateTime(), d->dateTimeFormat(QLocale::LongFormat).toString());
     case MeasurementSystem:
         return d->measurementSystem();
     case ZeroDigit:
         return lc_region.zeroDigit();
     case CountryId:
         return lc_region.country();
     case LanguageId:
         return lc_language.language();
     case AMText:
         return lc_language.amText();
     case PMText:
         return lc_language.pmText();
     default:
         break;
     }
     return QVariant();
 }
Friends and Related Functions
QSystemLocale_globalSystemLocale
QSystemLocale* QSystemLocale_globalSystemLocale () friend
The documentation for this class was generated from the following files:
/src/corelib/tools/qlocale.h
/src/corelib/tools/qlocale.cpp
/src/corelib/tools/qlocale_blackberry.cpp
/src/corelib/tools/qlocale_mac.mm
/src/corelib/tools/qlocale_unix.cpp
/src/corelib/tools/qlocale_win.cpp