Qt 4.8: QDeclarativeTypeData Class Reference
QDeclarativeTypeData Class Reference
#include <qdeclarativetypeloader_p.h>
Classes
struct ScriptReference
struct TypeDataCallback
struct TypeReference
Public Functions
QDeclarativeCompiledData * compiledData () const
const QDeclarativeImports & imports () const
const QDeclarativeScriptParser & parser () const
QDeclarativeTypeData (const QUrl &, QDeclarativeTypeLoader::Options, QDeclarativeTypeLoader *)
void registerCallback (TypeDataCallback *)
const QList< ScriptReference > & resolvedScripts () const
const QList< TypeReference > & resolvedTypes () const
QDeclarativeTypeLoader * typeLoader () const
void unregisterCallback (TypeDataCallback *)
~QDeclarativeTypeData ()
Public Functions inherited from QDeclarativeDataBlob
void addDependency (QDeclarativeDataBlob *)
Wait for blob to become complete or to error.
QList< QDeclarativeError > errors () const
Return the errors on this blob.
QUrl finalUrl () const
Returns the final url of the data.
bool isComplete () const
Returns true if the status is Complete.
bool isCompleteOrError () const
Returns true if the status is Complete or Error.
bool isError () const
Returns true if the status is Error.
bool isLoading () const
Returns true if the status is Loading.
bool isNull () const
Returns true if the status is Null.
bool isWaiting () const
Returns true if the status is WaitingForDependencies.
qreal progress () const
Returns the data download progress from 0 to 1.
QDeclarativeDataBlob (const QUrl &, Type)
Create a new QDeclarativeDataBlob for url and of the provided type.
void setError (const QDeclarativeError &)
Mark this blob as having errors.
void setError (const QList< QDeclarativeError > &errors)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Status status () const
Returns the blob's status.
Type type () const
Returns the type provided to the constructor.
QUrl url () const
Returns the blob url passed to the constructor.
virtual ~QDeclarativeDataBlob ()
Public Functions inherited from QDeclarativeRefCount
void addref ()
QDeclarativeRefCount ()
void release ()
virtual ~QDeclarativeRefCount ()
Protected Functions
virtual void allDependenciesDone ()
Called when all blobs waited for have completed.
virtual void dataReceived (const QByteArray &)
Invoked when data for the blob is received.
virtual void done ()
Invoked once data has either been received or a network error occurred, and all dependencies are complete.
virtual void downloadProgressChanged (qreal)
Called when the download progress of this blob changes.
Protected Functions inherited from QDeclarativeDataBlob
virtual void dependencyComplete (QDeclarativeDataBlob *)
Called if blob, which was previously waited for, has completed.
virtual void dependencyError (QDeclarativeDataBlob *)
Called if blob, which was previously waited for, has an error.
virtual void networkError (QNetworkReply::NetworkError)
Invoked if there is a network error while fetching this blob.
Private Functions
void compile ()
QDeclarativeQmldirData * qmldirForUrl (const QUrl &)
void resolveTypes ()
Properties
QList< TypeDataCallback * > m_callbacks
QDeclarativeCompiledData * m_compiledData
QDeclarativeImports m_imports
QDeclarativeTypeLoader::Options m_options
QList< QDeclarativeQmldirData * > m_qmldirs
QList< ScriptReference > m_scripts
QDeclarativeTypeLoader * m_typeLoader
QList< TypeReference > m_types
bool m_typesResolved:1
QDeclarativeScriptParser scriptParser
Additional Inherited Members
Public Types inherited from QDeclarativeDataBlob
enum Status {
Null, Loading, WaitingForDependencies, Complete,
Error
}
This enum describes the status of the data blob.
enum Type { QmlFile, JavaScriptFile, QmldirFile }
This enum describes the type of the data blob.
Detailed Description
Definition at line 224 of file qdeclarativetypeloader_p.h.
Constructors and Destructors
QDeclarativeTypeData()
QDeclarativeTypeData::QDeclarativeTypeData (const QUrl & url, QDeclarativeTypeLoader::Options options, QDeclarativeTypeLoader * manager)
Definition at line 864 of file qdeclarativetypeloader.cpp.
 : QDeclarativeDataBlob(url, QmlFile), m_options(options), m_imports(manager), m_typesResolved(false),
   m_compiledData(0), m_typeLoader(manager)
 {
 }
~QDeclarativeTypeData()
QDeclarativeTypeData::~QDeclarativeTypeData ()
Definition at line 871 of file qdeclarativetypeloader.cpp.
 {
     for (int ii = 0; ii < m_scripts.count(); ++ii)
         m_scripts.at(ii).script->release();
     for (int ii = 0; ii < m_qmldirs.count(); ++ii)
         m_qmldirs.at(ii)->release();
     for (int ii = 0; ii < m_types.count(); ++ii)
         if (m_types.at(ii).typeData) m_types.at(ii).typeData->release();
     if (m_compiledData)
         m_compiledData->release();
 }
Functions
allDependenciesDone()
void QDeclarativeTypeData::allDependenciesDone () protected virtual
Called when all blobs waited for have completed.
This occurs regardless of whether they are in error, or complete state.
The default implementation does nothing.
Reimplemented from QDeclarativeDataBlob.
Definition at line 1024 of file qdeclarativetypeloader.cpp.
 {
     if (!m_typesResolved) {
         resolveTypes();
         m_typesResolved = true;
     }
 }
compile()
void QDeclarativeTypeData::compile () private
Definition at line 1040 of file qdeclarativetypeloader.cpp.
Referenced by done().
 {
     Q_ASSERT(m_compiledData == 0);
     QDeclarativeDebugTrace::startRange(QDeclarativeDebugTrace::Compiling);
     m_compiledData = new QDeclarativeCompiledData(typeLoader()->engine());
     m_compiledData->url = m_imports.baseUrl();
     m_compiledData->name = m_compiledData->url.toString();
     QDeclarativeDebugTrace::rangeData(QDeclarativeDebugTrace::Compiling, m_compiledData->name);
     QDeclarativeCompiler compiler;
     if (!compiler.compile(typeLoader()->engine(), this, m_compiledData)) {
         setError(compiler.errors());
         m_compiledData->release();
         m_compiledData = 0;
     }
     QDeclarativeDebugTrace::endRange(QDeclarativeDebugTrace::Compiling);
 }
compiledData()
QDeclarativeCompiledData * QDeclarativeTypeData::compiledData () const
Definition at line 908 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeCompiler::compile(), QDeclarativeBinding::createBinding(), and QDeclarativeComponentPrivate::fromTypeData().
 {
     if (m_compiledData)
         m_compiledData->addref();
     return m_compiledData;
 }
dataReceived()
void QDeclarativeTypeData::dataReceived (const QByteArray & data) protected virtual
Invoked when data for the blob is received.
Implementors should use this callback to determine a blob's dependencies. Within this callback you may call setError() or addDependency().
Implements QDeclarativeDataBlob.
Definition at line 983 of file qdeclarativetypeloader.cpp.
 {
     if (!scriptParser.parse(data, finalUrl())) {
         setError(scriptParser.errors());
         return;
     }
     m_imports.setBaseUrl(finalUrl());
     foreach (const QDeclarativeScriptParser::Import &import, scriptParser.imports()) {
         if (import.type == QDeclarativeScriptParser::Import::File && import.qualifier.isEmpty()) {
             QUrl importUrl = finalUrl().resolved(QUrl(import.uri + QLatin1String("/qmldir")));
             if (QDeclarativeEnginePrivate::urlToLocalFileOrQrc(importUrl).isEmpty()) {
                 QDeclarativeQmldirData *data = typeLoader()->getQmldir(importUrl);
                 addDependency(data);
                 m_qmldirs << data;
             }
         } else if (import.type == QDeclarativeScriptParser::Import::Script) {
             QUrl scriptUrl = finalUrl().resolved(QUrl(import.uri));
             QDeclarativeScriptData *data = typeLoader()->getScript(scriptUrl);
             addDependency(data);
             ScriptReference ref;
             ref.location = import.location.start;
             ref.qualifier = import.qualifier;
             ref.script = data;
             m_scripts << ref;
         }
     }
     if (!finalUrl().scheme().isEmpty()) {
         QUrl importUrl = finalUrl().resolved(QUrl(QLatin1String("qmldir")));
         if (QDeclarativeEnginePrivate::urlToLocalFileOrQrc(importUrl).isEmpty()) {
             QDeclarativeQmldirData *data = typeLoader()->getQmldir(importUrl);
             addDependency(data);
             m_qmldirs << data;
         }
     }
 }
done()
void QDeclarativeTypeData::done () protected virtual
Invoked once data has either been received or a network error occurred, and all dependencies are complete.
You can set an error in this method, but you cannot add new dependencies. Implementors should use this callback to finalize processing of data.
The default implementation does nothing.
Reimplemented from QDeclarativeDataBlob.
Definition at line 929 of file qdeclarativetypeloader.cpp.
 {
     addref();
     // Check all script dependencies for errors
     for (int ii = 0; !isError() && ii < m_scripts.count(); ++ii) {
         const ScriptReference &script = m_scripts.at(ii);
         Q_ASSERT(script.script->isCompleteOrError());
         if (script.script->isError()) {
             QList<QDeclarativeError> errors = script.script->errors();
             QDeclarativeError error;
             error.setUrl(finalUrl());
             error.setLine(script.location.line);
             error.setColumn(script.location.column);
             error.setDescription(QDeclarativeTypeLoader::tr("Script %1 unavailable").arg(script.script->url().toString()));
             errors.prepend(error);
             setError(errors);
         }
     }
     // Check all type dependencies for errors
     for (int ii = 0; !isError() && ii < m_types.count(); ++ii) {
         const TypeReference &type = m_types.at(ii);
         Q_ASSERT(!type.typeData || type.typeData->isCompleteOrError());
         if (type.typeData && type.typeData->isError()) {
             QString typeName = scriptParser.referencedTypes().at(ii)->name;
             QList<QDeclarativeError> errors = type.typeData->errors();
             QDeclarativeError error;
             error.setUrl(finalUrl());
             error.setLine(type.location.line);
             error.setColumn(type.location.column);
             error.setDescription(QDeclarativeTypeLoader::tr("Type %1 unavailable").arg(typeName));
             errors.prepend(error);
             setError(errors);
         }
     }
     // Compile component
     if (!isError())
         compile();
     if (!(m_options & QDeclarativeTypeLoader::PreserveParser))
         scriptParser.clear();
     // Notify callbacks
     while (!m_callbacks.isEmpty()) {
         TypeDataCallback *callback = m_callbacks.takeFirst();
         callback->typeDataReady(this);
     }
     release();
 }
downloadProgressChanged()
void QDeclarativeTypeData::downloadProgressChanged (qreal progress) protected virtual
Called when the download progress of this blob changes.
progress goes from 0 to 1.
Reimplemented from QDeclarativeDataBlob.
Definition at line 1032 of file qdeclarativetypeloader.cpp.
 {
     for (int ii = 0; ii < m_callbacks.count(); ++ii) {
         TypeDataCallback *callback = m_callbacks.at(ii);
         callback->typeDataProgress(this, p);
     }
 }
imports()
const QDeclarativeImports & QDeclarativeTypeData::imports () const
Definition at line 888 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildPropertyInNamespace(), QDeclarativeCompiler::compileTree(), QDeclarativeCompiler::completeComponentBuild(), QDeclarativeCompiler::evaluateEnum(), QDeclarativeCompiler::resolveType(), and QDeclarativeCompiler::testQualifiedEnumAssignment().
 {
     return m_imports;
 }
parser()
const QDeclarativeScriptParser & QDeclarativeTypeData::parser () const
Definition at line 893 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::compile(), and QDeclarativeDomDocument::load().
 {
     return scriptParser;
 }
qmldirForUrl()
QDeclarativeQmldirData * QDeclarativeTypeData::qmldirForUrl (const QUrl & url) private
Definition at line 1185 of file qdeclarativetypeloader.cpp.
Referenced by resolveTypes().
 {
     for (int ii = 0; ii < m_qmldirs.count(); ++ii) {
         if (m_qmldirs.at(ii)->url() == url)
             return m_qmldirs.at(ii);
     }
     return 0;
 }
registerCallback()
void QDeclarativeTypeData::registerCallback (TypeDataCallback * callback)
Definition at line 916 of file qdeclarativetypeloader.cpp.
 {
     Q_ASSERT(!m_callbacks.contains(callback));
     m_callbacks.append(callback);
 }
resolvedScripts()
const QList< QDeclarativeTypeData::ScriptReference > & QDeclarativeTypeData::resolvedScripts () const
Definition at line 903 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::compileTree().
 {
     return m_scripts;
 }
resolvedTypes()
const QList< QDeclarativeTypeData::TypeReference > & QDeclarativeTypeData::resolvedTypes () const
Definition at line 898 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildSignal(), and QDeclarativeCompiler::compile().
 {
     return m_types;
 }
resolveTypes()
void QDeclarativeTypeData::resolveTypes () private
Definition at line 1059 of file qdeclarativetypeloader.cpp.
Referenced by allDependenciesDone().
 {
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(m_typeLoader->engine());
     QDeclarativeImportDatabase *importDatabase = &ep->importDatabase;
     foreach (const QDeclarativeScriptParser::Import &import, scriptParser.imports()) {
         QDeclarativeDirComponents qmldircomponentsnetwork;
         if (import.type == QDeclarativeScriptParser::Import::Script)
             continue;
         if (import.type == QDeclarativeScriptParser::Import::File && import.qualifier.isEmpty()) {
             QUrl qmldirUrl = finalUrl().resolved(QUrl(import.uri + QLatin1String("/qmldir")));
             if (QDeclarativeQmldirData *qmldir = qmldirForUrl(qmldirUrl))
                 qmldircomponentsnetwork = qmldir->dirComponents();
         }
         int vmaj = -1;
         int vmin = -1;
         if (!import.version.isEmpty()) {
             int dot = import.version.indexOf(QLatin1Char('.'));
             if (dot < 0) {
                 vmaj = import.version.toInt();
                 vmin = 0;
             } else {
                 vmaj = import.version.left(dot).toInt();
                 vmin = import.version.mid(dot+1).toInt();
             }
         }
         QString errorString;
         if (!m_imports.addImport(importDatabase, import.uri, import.qualifier,
                                  vmaj, vmin, import.type, qmldircomponentsnetwork, &errorString)) {
             QDeclarativeError error;
             error.setUrl(m_imports.baseUrl());
             error.setDescription(errorString);
             error.setLine(import.location.start.line);
             error.setColumn(import.location.start.column);
             setError(error);
             return;
         }
     }
     bool implicitImportLoaded = false;
     foreach (QDeclarativeScriptParser::TypeReference *parserRef, scriptParser.referencedTypes()) {
         QByteArray typeName = parserRef->name.toUtf8();
         TypeReference ref;
         QUrl url;
         int majorVersion;
         int minorVersion;
         QDeclarativeImportedNamespace *typeNamespace = 0;
         QString errorString;
         if (!m_imports.resolveType(typeName, &ref.type, &url, &majorVersion, &minorVersion,
                                    &typeNamespace, &errorString) || typeNamespace) {
             // Known to not be a type:
             //  - known to be a namespace (Namespace {})
             //  - type with unknown namespace (UnknownNamespace.SomeType {})
             bool typeFound = false;
             if (!typeNamespace && !implicitImportLoaded) {
                 implicitImportLoaded = true;
                 // For local urls, add an implicit import "." as most overridden lookup.
                 // This will also trigger the loading of the qmldir and the import of any native
                 // types from available plugins.
                 // This is only done if the type is not otherwise found, side effects of plugin loading may be avoided
                 // ### This should be an acceptable variation because A) It's only side effects (and img providers) B) You shouldn't be doing that in "." anyways!
                 if (QDeclarativeQmldirData *qmldir = qmldirForUrl(finalUrl().resolved(QUrl(QLatin1String("./qmldir"))))) {
                     m_imports.addImport(importDatabase, QLatin1String("."),
                                         QString(), -1, -1, QDeclarativeScriptParser::Import::Implicit,
                                         qmldir->dirComponents(), 0);
                 } else {
                     m_imports.addImport(importDatabase, QLatin1String("."),
                                         QString(), -1, -1, QDeclarativeScriptParser::Import::Implicit,
                                         QDeclarativeDirComponents(), 0);
                 }
                 if (m_imports.resolveType(typeName, &ref.type, &url, &majorVersion, &minorVersion,
                                            &typeNamespace, &errorString) || typeNamespace) {
                     typeFound = true;
                 }
             }
             if (!typeFound) {
                 QDeclarativeError error;
                 error.setUrl(m_imports.baseUrl());
                 QString userTypeName = parserRef->name;
                 userTypeName.replace(QLatin1Char('/'),QLatin1Char('.'));
                 if (typeNamespace)
                     error.setDescription(QDeclarativeTypeLoader::tr("Namespace %1 cannot be used as a type").arg(userTypeName));
                 else
                     error.setDescription(QDeclarativeTypeLoader::tr("%1 %2").arg(userTypeName).arg(errorString));
                 if (!parserRef->refObjects.isEmpty()) {
                     QDeclarativeParser::Object *obj = parserRef->refObjects.first();
                     error.setLine(obj->location.start.line);
                     error.setColumn(obj->location.start.column);
                 }
                 setError(error);
                 return;
             }
         }
         if (ref.type) {
             ref.majorVersion = majorVersion;
             ref.minorVersion = minorVersion;
             foreach (QDeclarativeParser::Object *obj, parserRef->refObjects) {
                // store namespace for DOM
                obj->majorVersion = majorVersion;
                obj->minorVersion = minorVersion;
             }
         } else {
             ref.typeData = typeLoader()->get(url);
             addDependency(ref.typeData);
         }
         if (parserRef->refObjects.count())
             ref.location = parserRef->refObjects.first()->location.start;
         m_types << ref;
     }
 }
typeLoader()
QDeclarativeTypeLoader * QDeclarativeTypeData::typeLoader () const
Definition at line 883 of file qdeclarativetypeloader.cpp.
Referenced by compile(), dataReceived(), and resolveTypes().
 {
     return m_typeLoader;
 }
unregisterCallback()
void QDeclarativeTypeData::unregisterCallback (TypeDataCallback * callback)
Definition at line 922 of file qdeclarativetypeloader.cpp.
Referenced by QDeclarativeComponentPrivate::clear().
 {
     Q_ASSERT(m_callbacks.contains(callback));
     m_callbacks.removeOne(callback);
     Q_ASSERT(!m_callbacks.contains(callback));
 }
Properties
m_callbacks
QList<TypeDataCallback *> QDeclarativeTypeData::m_callbacks private
Definition at line 294 of file qdeclarativetypeloader_p.h.
Referenced by done(), downloadProgressChanged(), registerCallback(), and unregisterCallback().
m_compiledData
QDeclarativeCompiledData* QDeclarativeTypeData::m_compiledData private
Definition at line 292 of file qdeclarativetypeloader_p.h.
Referenced by compile(), compiledData(), and ~QDeclarativeTypeData().
m_imports
QDeclarativeImports QDeclarativeTypeData::m_imports private
Definition at line 284 of file qdeclarativetypeloader_p.h.
Referenced by compile(), dataReceived(), imports(), and resolveTypes().
m_options
QDeclarativeTypeLoader::Options QDeclarativeTypeData::m_options private
Definition at line 279 of file qdeclarativetypeloader_p.h.
Referenced by done().
m_qmldirs
QList<QDeclarativeQmldirData *> QDeclarativeTypeData::m_qmldirs private
Definition at line 287 of file qdeclarativetypeloader_p.h.
Referenced by dataReceived(), qmldirForUrl(), and ~QDeclarativeTypeData().
m_scripts
QList<ScriptReference> QDeclarativeTypeData::m_scripts private
Definition at line 286 of file qdeclarativetypeloader_p.h.
Referenced by dataReceived(), done(), resolvedScripts(), and ~QDeclarativeTypeData().
m_typeLoader
QDeclarativeTypeLoader* QDeclarativeTypeData::m_typeLoader private
Definition at line 296 of file qdeclarativetypeloader_p.h.
Referenced by resolveTypes(), and typeLoader().
m_types
QList<TypeReference> QDeclarativeTypeData::m_types private
Definition at line 289 of file qdeclarativetypeloader_p.h.
Referenced by done(), resolvedTypes(), resolveTypes(), and ~QDeclarativeTypeData().
m_typesResolved
bool QDeclarativeTypeData::m_typesResolved private
Definition at line 290 of file qdeclarativetypeloader_p.h.
Referenced by allDependenciesDone().
scriptParser
QDeclarativeScriptParser QDeclarativeTypeData::scriptParser private
Definition at line 283 of file qdeclarativetypeloader_p.h.
Referenced by dataReceived(), done(), parser(), and resolveTypes().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativetypeloader_p.h
/src/declarative/qml/qdeclarativetypeloader.cpp