Qt 4.8: QMetaPropertyBuilderPrivate Class Reference
QMetaPropertyBuilderPrivate Class Reference
Public Functions
bool flag (int f) const
QMetaPropertyBuilderPrivate (const QByteArray &_name, const QByteArray &_type, int notifierIdx=-1)
void setFlag (int f, bool value)
Public Variables
int flags
QByteArray name
int notifySignal
QByteArray type
Detailed Description
Definition at line 203 of file qmetaobjectbuilder.cpp.
Constructors and Destructors
QMetaPropertyBuilderPrivate()
QMetaPropertyBuilderPrivate::QMetaPropertyBuilderPrivate (const QByteArray & _name, const QByteArray & _type, int notifierIdx = -1) inline
Definition at line 207 of file qmetaobjectbuilder.cpp.
         : name(_name),
           type(QMetaObject::normalizedType(_type.constData())),
           flags(Readable | Writable | Scriptable), notifySignal(-1)
     {
         if (notifierIdx >= 0) {
             flags |= Notify;
             notifySignal = notifierIdx;
         }
     }
Functions
flag()
bool QMetaPropertyBuilderPrivate::flag (int f) const inline
Definition at line 223 of file qmetaobjectbuilder.cpp.
Referenced by QMetaPropertyBuilder::hasNotifySignal(), QMetaPropertyBuilder::hasStdCppSet(), QMetaPropertyBuilder::isConstant(), QMetaPropertyBuilder::isDesignable(), QMetaPropertyBuilder::isEditable(), QMetaPropertyBuilder::isEnumOrFlag(), QMetaPropertyBuilder::isFinal(), QMetaPropertyBuilder::isReadable(), QMetaPropertyBuilder::isResettable(), QMetaPropertyBuilder::isScriptable(), QMetaPropertyBuilder::isStored(), QMetaPropertyBuilder::isUser(), and QMetaPropertyBuilder::isWritable().
     {
         return ((flags & f) != 0);
     }
setFlag()
void QMetaPropertyBuilderPrivate::setFlag (int f, bool value) inline
Definition at line 228 of file qmetaobjectbuilder.cpp.
Referenced by QMetaPropertyBuilder::removeNotifySignal(), QMetaPropertyBuilder::setConstant(), QMetaPropertyBuilder::setDesignable(), QMetaPropertyBuilder::setEditable(), QMetaPropertyBuilder::setEnumOrFlag(), QMetaPropertyBuilder::setFinal(), QMetaPropertyBuilder::setNotifySignal(), QMetaPropertyBuilder::setReadable(), QMetaPropertyBuilder::setResettable(), QMetaPropertyBuilder::setScriptable(), QMetaPropertyBuilder::setStdCppSet(), QMetaPropertyBuilder::setStored(), QMetaPropertyBuilder::setUser(), and QMetaPropertyBuilder::setWritable().
     {
         if (value)
             flags |= f;
         else
             flags &= ~f;
     }
Properties
flags
int QMetaPropertyBuilderPrivate::flags
Definition at line 220 of file qmetaobjectbuilder.cpp.
Referenced by buildMetaObject().
name
QByteArray QMetaPropertyBuilderPrivate::name
Definition at line 218 of file qmetaobjectbuilder.cpp.
Referenced by buildMetaObject(), and QMetaPropertyBuilder::name().
notifySignal
int QMetaPropertyBuilderPrivate::notifySignal
Definition at line 221 of file qmetaobjectbuilder.cpp.
Referenced by buildMetaObject(), QMetaPropertyBuilder::notifySignal(), QMetaPropertyBuilder::removeNotifySignal(), and QMetaPropertyBuilder::setNotifySignal().
type
QByteArray QMetaPropertyBuilderPrivate::type
Definition at line 219 of file qmetaobjectbuilder.cpp.
Referenced by buildMetaObject(), and QMetaPropertyBuilder::type().
The documentation for this class was generated from the following file:
/src/declarative/qml/qmetaobjectbuilder.cpp