Qt 4.8: QNativeSocketEngine Class Reference
QNativeSocketEngine Class Reference
The QNativeSocketEngine class provides low level access to a socket.
#include <qnativesocketengine_p.h>
Public Slots
void connectionNotification ()
If there's a connection activity on the socket, process it.
Public Slots inherited from QAbstractSocketEngine
void connectionNotification ()
void exceptionNotification ()
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
void readNotification ()
void writeNotification ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
int accept ()
Accepts a pending connection from the socket, which must be in ListeningState, and returns its socket descriptor.
bool bind (const QHostAddress &address, quint16 port)
Binds the socket to the address address and port port.
qint64 bytesAvailable () const
Returns the number of bytes that are currently available for reading.
qint64 bytesToWrite () const
void close ()
Closes the socket.
bool connectToHost (const QHostAddress &address, quint16 port)
Connects to the IP address and port specified by address and port.
bool connectToHostByName (const QString &name, quint16 port)
Connects to the remote host name given by name on port port.
bool hasPendingDatagrams () const
Returns true if there is at least one datagram pending.
bool initialize (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol=QAbstractSocket::IPv4Protocol)
Initializes a QNativeSocketEngine by creating a new socket of type socketType and network layer protocol protocol.
bool initialize (int socketDescriptor, QAbstractSocket::SocketState socketState=QAbstractSocket::ConnectedState)
Initializes the socket using socketDescriptor instead of creating a new one.
bool isExceptionNotificationEnabled () const
bool isReadNotificationEnabled () const
bool isValid () const
Returns true if the socket is valid; otherwise returns false.
bool isWriteNotificationEnabled () const
bool joinMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &iface)
bool leaveMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &iface)
bool listen ()
Prepares a TCP server for accepting incoming connections.
QNetworkInterface multicastInterface () const
int option (SocketOption option) const
Returns the value of the option socketOption.
qint64 pendingDatagramSize () const
Returns the size of the pending datagram, or -1 if no datagram is pending.
QNativeSocketEngine (QObject *parent=0)
Constructs a QNativeSocketEngine.
qint64 read (char *data, qint64 maxlen)
Reads up to maxSize bytes into data from the socket.
qint64 readDatagram (char *data, qint64 maxlen, QHostAddress *addr=0, quint16 *port=0)
Reads up to maxSize bytes of a datagram from the socket, stores it in data and returns the number of bytes read.
qint64 receiveBufferSize () const
Returns the size of the operating system's socket receive buffer.
qint64 sendBufferSize () const
Returns the size of the operating system send buffer.
void setExceptionNotificationEnabled (bool enable)
bool setMulticastInterface (const QNetworkInterface &iface)
bool setOption (SocketOption option, int value)
Sets the option option to the value value.
void setReadNotificationEnabled (bool enable)
void setReceiveBufferSize (qint64 bufferSize)
Sets the size of the operating system receive buffer to size.
void setSendBufferSize (qint64 bufferSize)
Sets the size of the operating system send buffer to size.
void setWriteNotificationEnabled (bool enable)
int socketDescriptor () const
Returns the native socket descriptor.
bool waitForRead (int msecs=30000, bool *timedOut=0)
Waits for msecs milliseconds or until the socket is ready for reading.
bool waitForReadOrWrite (bool *readyToRead, bool *readyToWrite, bool checkRead, bool checkWrite, int msecs=30000, bool *timedOut=0)
bool waitForWrite (int msecs=30000, bool *timedOut=0)
Waits for msecs milliseconds or until the socket is ready for writing.
qint64 write (const char *data, qint64 len)
Writes a block of size bytes from data to the socket.
qint64 writeDatagram (const char *data, qint64 len, const QHostAddress &addr, quint16 port)
Writes a UDP datagram of size size bytes to the socket from data to the address host on port port, and returns the number of bytes written, or -1 if an error occurred.
~QNativeSocketEngine ()
Destructs a QNativeSocketEngine.
Public Functions inherited from QAbstractSocketEngine
QAbstractSocket::SocketError error () const
QString errorString () const
QHostAddress localAddress () const
quint16 localPort () const
QHostAddress peerAddress () const
quint16 peerPort () const
QAbstractSocket::NetworkLayerProtocol protocol () const
QAbstractSocketEngine (QObject *parent=0)
void setReceiver (QAbstractSocketEngineReceiver *receiver)
QAbstractSocket::SocketType socketType () const
QAbstractSocket::SocketState state () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Types inherited from QAbstractSocketEngine
enum SocketOption {
NonBlockingSocketOption, BroadcastSocketOption, ReceiveBufferSocketOption, SendBufferSocketOption,
AddressReusable, BindExclusively, ReceiveOutOfBandData, LowDelayOption,
KeepAliveOption, MulticastTtlOption, MulticastLoopbackOption
}
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QAbstractSocketEngine
static QAbstractSocketEngine * createSocketEngine (QAbstractSocket::SocketType socketType, const QNetworkProxy &, QObject *parent)
static QAbstractSocketEngine * createSocketEngine (int socketDescripter, QObject *parent)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QAbstractSocketEngine
QAbstractSocketEngine (QAbstractSocketEnginePrivate &dd, QObject *parent=0)
void setError (QAbstractSocket::SocketError error, const QString &errorString) const
void setLocalAddress (const QHostAddress &address)
void setLocalPort (quint16 port)
void setPeerAddress (const QHostAddress &address)
void setPeerPort (quint16 port)
void setProtocol (QAbstractSocket::NetworkLayerProtocol protocol)
void setSocketType (QAbstractSocket::SocketType socketType)
void setState (QAbstractSocket::SocketState state)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QNativeSocketEngine class provides low level access to a socket.
Warning
This function is not part of the public interface.
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QtSocketLayer provides basic socket functionality provided by the operating system. It also keeps track of what state the socket is in, and which errors that occur.
The classes QTcpSocket, QUdpSocket and QTcpServer provide a higher level API, and are in general more useful for the common application.
There are two main ways of initializing the a QNativeSocketEngine; either create a new socket by passing the socket type (TcpSocket or UdpSocket) and network layer protocol (IPv4Protocol or IPv6Protocol) to initialize(), or pass an existing socket descriptor and have QNativeSocketEngine determine the type and protocol itself. The native socket descriptor can later be fetched by calling socketDescriptor(). The socket is made non-blocking, but blocking behavior can still be achieved by calling waitForRead() and waitForWrite(). isValid() can be called to check if the socket has been successfully initialized and is ready to use.
To connect to a host, determine its address and pass this and the port number to connectToHost(). The socket can then be used as a TCP or UDP client. Otherwise; bind(), listen() and accept() are used to have the socket function as a TCP or UDP server. Call close() to close the socket.
bytesAvailable() is called to determine how much data is available for reading. read() and write() are used by both TCP and UDP clients to exchange data with the connected peer. UDP clients can also call hasMoreDatagrams(), nextDatagramSize(), readDatagram(), and writeDatagram().
Call state() to determine the state of the socket, for example, ListeningState or ConnectedState. socketType() tells whether the socket is a TCP socket or a UDP socket, or if the socket type is unknown. protocol() is used to determine the socket's network layer protocol.
localAddress(), localPort() are called to find the address and port that are currently bound to the socket. If the socket is connected, peerAddress() and peerPort() determine the address and port of the connected peer.
Finally, if any function should fail, error() and errorString() can be called to determine the cause of the error.
Definition at line 103 of file qnativesocketengine_p.h.
Constructors and Destructors
QNativeSocketEngine()
QNativeSocketEngine::QNativeSocketEngine (QObject * parent = 0)
Constructs a QNativeSocketEngine.
See also
initialize()
Definition at line 330 of file qnativesocketengine.cpp.
     : QAbstractSocketEngine(*new QNativeSocketEnginePrivate(), parent)
 {
 }
~QNativeSocketEngine()
QNativeSocketEngine::~QNativeSocketEngine ()
Destructs a QNativeSocketEngine.
Definition at line 338 of file qnativesocketengine.cpp.
 {
     close();
 }
Functions
accept()
int QNativeSocketEngine::accept () virtual
Accepts a pending connection from the socket, which must be in ListeningState, and returns its socket descriptor.
If no pending connections are available, -1 is returned.
See also
bind(), listen()
Implements QAbstractSocketEngine.
Definition at line 654 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::accept(), -1);
     Q_CHECK_STATE(QNativeSocketEngine::accept(), QAbstractSocket::ListeningState, false);
     Q_CHECK_TYPE(QNativeSocketEngine::accept(), QAbstractSocket::TcpSocket, false);
     return d->nativeAccept();
 }
bind()
bool QNativeSocketEngine::bind (const QHostAddress & address, quint16 port) virtual
Binds the socket to the address address and port port.
Returns true on success; otherwise false is returned. The port may be 0, in which case an arbitrary unused port is assigned automatically by the operating system.
Servers call this function to set up the server's address and port. TCP servers must in addition call listen() after bind().
Implements QAbstractSocketEngine.
Definition at line 594 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::bind(), false);
 #if defined (QT_NO_IPV6)
     if (address.protocol() == QAbstractSocket::IPv6Protocol) {
         d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                     QNativeSocketEnginePrivate::NoIpV6ErrorString);
         return false;
     }
 #endif
     if (!d->checkProxy(address))
         return false;
     Q_CHECK_STATE(QNativeSocketEngine::bind(), QAbstractSocket::UnconnectedState, false);
     if (!d->nativeBind(address, port))
         return false;
     d->fetchConnectionParameters();
     return true;
 }
bytesAvailable()
qint64 QNativeSocketEngine::bytesAvailable () const virtual
Returns the number of bytes that are currently available for reading.
On error, -1 is returned.
For UDP sockets, this function returns the accumulated size of all pending datagrams, and it is therefore more useful for UDP sockets to call hasPendingDatagrams() and pendingDatagramSize().
Implements QAbstractSocketEngine.
Definition at line 720 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::bytesAvailable(), -1);
     Q_CHECK_NOT_STATE(QNativeSocketEngine::bytesAvailable(), QAbstractSocket::UnconnectedState, false);
     return d->nativeBytesAvailable();
 }
bytesToWrite()
qint64 QNativeSocketEngine::bytesToWrite () const virtual
Implements QAbstractSocketEngine.
Definition at line 824 of file qnativesocketengine.cpp.
 {
     return 0;
 }
close()
void QNativeSocketEngine::close () virtual
Closes the socket.
In order to use the socket again, initialize() must be called.
Implements QAbstractSocketEngine.
Definition at line 863 of file qnativesocketengine.cpp.
Referenced by initialize(), read(), and ~QNativeSocketEngine().
 {
     Q_D(QNativeSocketEngine);
     if (d->readNotifier)
         d->readNotifier->setEnabled(false);
     if (d->writeNotifier)
         d->writeNotifier->setEnabled(false);
     if (d->exceptNotifier)
         d->exceptNotifier->setEnabled(false);
     if(d->socketDescriptor != -1) {
         d->nativeClose();
         d->socketDescriptor = -1;
     }
     d->socketState = QAbstractSocket::UnconnectedState;
     d->hasSetSocketError = false;
     d->localPort = 0;
     d->localAddress.clear();
     d->peerPort = 0;
     d->peerAddress.clear();
     if (d->readNotifier) {
         qDeleteInEventHandler(d->readNotifier);
         d->readNotifier = 0;
     }
     if (d->writeNotifier) {
         qDeleteInEventHandler(d->writeNotifier);
         d->writeNotifier = 0;
     }
     if (d->exceptNotifier) {
         qDeleteInEventHandler(d->exceptNotifier);
         d->exceptNotifier = 0;
     }
 }
connectionNotification
void QNativeSocketEngine::connectionNotification () slot
If there's a connection activity on the socket, process it.
Then notify our parent if there really was activity.
Definition at line 555 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_ASSERT(state() == QAbstractSocket::ConnectingState);
     connectToHost(d->peerAddress, d->peerPort);
     if (state() != QAbstractSocket::ConnectingState) {
         // we changed states
         QAbstractSocketEngine::connectionNotification();
     }
 }
connectToHost()
bool QNativeSocketEngine::connectToHost (const QHostAddress & address, quint16 port) virtual
Connects to the IP address and port specified by address and port.
If the connection is established, this function returns true and the socket enters ConnectedState. Otherwise, false is returned.
If false is returned, state() should be called to see if the socket is in ConnectingState. If so, a delayed TCP connection is taking place, and connectToHost() must be called again later to determine if the connection was established successfully or not. The second connection attempt must be made when the socket is ready for writing. This state can be determined either by connecting a QSocketNotifier to the socket descriptor returned by socketDescriptor(), or by calling the blocking function waitForWrite().
Example:
QNativeSocketEngine socketLayer;
socketLayer.initialize(QAbstractSocket::TcpSocket, QAbstractSocket::IPv4Protocol);
socketLayer.connectToHost(QHostAddress::LocalHost, 22);
// returns false
socketLayer.waitForWrite();
socketLayer.connectToHost(QHostAddress::LocalHost, 22);
// returns true
Otherwise, error() should be called to determine the cause of the error.
Implements QAbstractSocketEngine.
Definition at line 524 of file qnativesocketengine.cpp.
Referenced by connectionNotification(), waitForRead(), waitForReadOrWrite(), and waitForWrite().
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::connectToHost(), false);
 #if defined (QT_NO_IPV6)
     if (address.protocol() == QAbstractSocket::IPv6Protocol) {
         d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                     QNativeSocketEnginePrivate::NoIpV6ErrorString);
         return false;
     }
 #endif
     if (!d->checkProxy(address))
         return false;
     Q_CHECK_STATES(QNativeSocketEngine::connectToHost(),
                    QAbstractSocket::UnconnectedState, QAbstractSocket::ConnectingState, false);
     d->peerAddress = address;
     d->peerPort = port;
     bool connected = d->nativeConnect(address, port);
     if (connected)
         d->fetchConnectionParameters();
     return connected;
 }
connectToHostByName()
bool QNativeSocketEngine::connectToHostByName (const QString & name, quint16 port) virtual
Connects to the remote host name given by name on port port.
When this function is called, the upper-level will not perform a hostname lookup.
The native socket engine does not support this operation, but some other socket engines (notably proxy-based ones) do.
Implements QAbstractSocketEngine.
Definition at line 575 of file qnativesocketengine.cpp.
 {
     Q_UNUSED(name);
     Q_UNUSED(port);
     Q_D(QNativeSocketEngine);
     d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                 QNativeSocketEnginePrivate::OperationUnsupportedErrorString);
     return false;
 }
hasPendingDatagrams()
bool QNativeSocketEngine::hasPendingDatagrams () const virtual
Returns true if there is at least one datagram pending.
This function is only called by UDP sockets, where a datagram can have a size of 0. TCP sockets call bytesAvailable().
Implements QAbstractSocketEngine.
Definition at line 734 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::hasPendingDatagrams(), false);
     Q_CHECK_NOT_STATE(QNativeSocketEngine::hasPendingDatagrams(), QAbstractSocket::UnconnectedState, false);
     Q_CHECK_TYPE(QNativeSocketEngine::hasPendingDatagrams(), QAbstractSocket::UdpSocket, false);
     return d->nativeHasPendingDatagrams();
 }
initialize() [1/2]
bool QNativeSocketEngine::initialize (QAbstractSocket::SocketType socketType, QAbstractSocket::NetworkLayerProtocol protocol = QAbstractSocket::IPv4Protocol) virtual
Initializes a QNativeSocketEngine by creating a new socket of type socketType and network layer protocol protocol.
Returns true on success; otherwise returns false.
If the socket was already initialized, this function closes the socket before reeinitializing it.
The new socket is non-blocking, and for UDP sockets it's also broadcast enabled.
Implements QAbstractSocketEngine.
Definition at line 354 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     if (isValid())
         close();
 #if defined(QT_NO_IPV6)
     if (protocol == QAbstractSocket::IPv6Protocol) {
         d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                     QNativeSocketEnginePrivate::NoIpV6ErrorString);
         return false;
     }
 #endif
     // Create the socket
     if (!d->createNewSocket(socketType, protocol)) {
 #if defined (QNATIVESOCKETENGINE_DEBUG)
         QString typeStr = QLatin1String("UnknownSocketType");
         if (socketType == QAbstractSocket::TcpSocket) typeStr = QLatin1String("TcpSocket");
         else if (socketType == QAbstractSocket::UdpSocket) typeStr = QLatin1String("UdpSocket");
         QString protocolStr = QLatin1String("UnknownProtocol");
         if (protocol == QAbstractSocket::IPv4Protocol) protocolStr = QLatin1String("IPv4Protocol");
         else if (protocol == QAbstractSocket::IPv6Protocol) protocolStr = QLatin1String("IPv6Protocol");
         qDebug("QNativeSocketEngine::initialize(type == %s, protocol == %s) failed: %s",
                typeStr.toLatin1().constData(), protocolStr.toLatin1().constData(), d->socketErrorString.toLatin1().constData());
 #endif
         return false;
     }
     // Make the socket nonblocking.
     if (!setOption(NonBlockingSocketOption, 1)) {
         d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                     QNativeSocketEnginePrivate::NonBlockingInitFailedErrorString);
         close();
         return false;
     }
     // Set the broadcasting flag if it's a UDP socket.
     if (socketType == QAbstractSocket::UdpSocket
         && !setOption(BroadcastSocketOption, 1)) {
         d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                     QNativeSocketEnginePrivate::BroadcastingInitFailedErrorString);
         close();
         return false;
     }
     // Make sure we receive out-of-band data
     if (socketType == QAbstractSocket::TcpSocket
         && !setOption(ReceiveOutOfBandData, 1)) {
         qWarning("QNativeSocketEngine::initialize unable to inline out-of-band data");
     }
     // Before Qt 4.6, we always set the send and receive buffer size to 49152 as
     // this was found to be an optimal value. However, modern OS
     // all have some kind of auto tuning for this and we therefore don't set
     // this explictly anymore.
     // If it introduces any performance regressions for Qt 4.6.x (x > 0) then
     // it will be put back in.
     //
     // You can use tests/manual/qhttpnetworkconnection to test HTTP download speed
     // with this.
     //
     // pre-4.6:
     // setReceiveBufferSize(49152);
     // setSendBufferSize(49152);
     d->socketType = socketType;
     d->socketProtocol = protocol;
     return true;
 }
initialize() [2/2]
bool QNativeSocketEngine::initialize (int socketDescriptor, QAbstractSocket::SocketState socketState = QAbstractSocket::ConnectedState) virtual
Initializes the socket using socketDescriptor instead of creating a new one.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The socket type and network layer protocol are determined automatically. The socket's state is set to socketState.
If the socket type is either TCP or UDP, it is made non-blocking. UDP sockets are also broadcast enabled.
Implements QAbstractSocketEngine.
Definition at line 439 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     if (isValid())
         close();
     d->socketDescriptor = socketDescriptor;
     // determine socket type and protocol
     if (!d->fetchConnectionParameters()) {
 #if defined (QNATIVESOCKETENGINE_DEBUG)
         qDebug("QNativeSocketEngine::initialize(socketDescriptor == %i) failed: %s",
                socketDescriptor, d->socketErrorString.toLatin1().constData());
 #endif
         d->socketDescriptor = -1;
         return false;
     }
     if (d->socketType != QAbstractSocket::UnknownSocketType) {
         // Make the socket nonblocking.
         if (!setOption(NonBlockingSocketOption, 1)) {
             d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                 QNativeSocketEnginePrivate::NonBlockingInitFailedErrorString);
             close();
             return false;
         }
         // Set the broadcasting flag if it's a UDP socket.
         if (d->socketType == QAbstractSocket::UdpSocket
             && !setOption(BroadcastSocketOption, 1)) {
             d->setError(QAbstractSocket::UnsupportedSocketOperationError,
                 QNativeSocketEnginePrivate::BroadcastingInitFailedErrorString);
             close();
             return false;
         }
     }
     d->socketState = socketState;
     return true;
 }
isExceptionNotificationEnabled()
bool QNativeSocketEngine::isExceptionNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 1256 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     return d->exceptNotifier && d->exceptNotifier->isEnabled();
 }
isReadNotificationEnabled()
bool QNativeSocketEngine::isReadNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 1136 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     return d->readNotifier && d->readNotifier->isEnabled();
 }
isValid()
bool QNativeSocketEngine::isValid () const virtual
Returns true if the socket is valid; otherwise returns false.
A socket is valid if it has not been successfully initialized, or if it has been closed.
Implements QAbstractSocketEngine.
Definition at line 486 of file qnativesocketengine.cpp.
Referenced by initialize().
 {
     Q_D(const QNativeSocketEngine);
     return d->socketDescriptor != -1;
 }
isWriteNotificationEnabled()
bool QNativeSocketEngine::isWriteNotificationEnabled () const virtual
Implements QAbstractSocketEngine.
Definition at line 1239 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     return d->writeNotifier && d->writeNotifier->isEnabled();
 }
joinMulticastGroup()
bool QNativeSocketEngine::joinMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & iface) virtual
Since
4.8
Implements QAbstractSocketEngine.
Definition at line 669 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::joinMulticastGroup(), false);
     Q_CHECK_STATE(QNativeSocketEngine::joinMulticastGroup(), QAbstractSocket::BoundState, false);
     Q_CHECK_TYPE(QNativeSocketEngine::joinMulticastGroup(), QAbstractSocket::UdpSocket, false);
     return d->nativeJoinMulticastGroup(groupAddress, iface);
 }
leaveMulticastGroup()
bool QNativeSocketEngine::leaveMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & iface) virtual
Since
4.8
Implements QAbstractSocketEngine.
Definition at line 682 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::leaveMulticastGroup(), false);
     Q_CHECK_STATE(QNativeSocketEngine::leaveMulticastGroup(), QAbstractSocket::BoundState, false);
     Q_CHECK_TYPE(QNativeSocketEngine::leaveMulticastGroup(), QAbstractSocket::UdpSocket, false);
     return d->nativeLeaveMulticastGroup(groupAddress, iface);
 }
listen()
bool QNativeSocketEngine::listen () virtual
Prepares a TCP server for accepting incoming connections.
This function must be called after bind(), and only by TCP sockets.
After this function has been called, pending client connections are detected by checking if the socket is ready for reading. This can be done by either creating a QSocketNotifier, passing the socket descriptor returned by socketDescriptor(), or by calling the blocking function waitForRead().
Example:
QNativeSocketEngine socketLayer;
socketLayer.bind(QHostAddress::Any, 4000);
socketLayer.listen();
if (socketLayer.waitForRead()) {
    int clientSocket = socketLayer.accept();
    // a client is connected
}
See also
bind(), accept()
Implements QAbstractSocketEngine.
Definition at line 633 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::listen(), false);
     Q_CHECK_STATE(QNativeSocketEngine::listen(), QAbstractSocket::BoundState, false);
     Q_CHECK_TYPE(QNativeSocketEngine::listen(), QAbstractSocket::TcpSocket, false);
     // We're using a backlog of 50. Most modern kernels support TCP
     // syncookies by default, and if they do, the backlog is ignored.
     // When there is no support for TCP syncookies, this value is
     // fine.
     return d->nativeListen(50);
 }
multicastInterface()
QNetworkInterface QNativeSocketEngine::multicastInterface () const virtual
Since
4.8
Implements QAbstractSocketEngine.
Definition at line 693 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::multicastInterface(), QNetworkInterface());
     Q_CHECK_TYPE(QNativeSocketEngine::multicastInterface(), QAbstractSocket::UdpSocket, QNetworkInterface());
     return d->nativeMulticastInterface();
 }
option()
int QNativeSocketEngine::option (SocketOption option) const virtual
Returns the value of the option socketOption.
Implements QAbstractSocketEngine.
Definition at line 1130 of file qnativesocketengine.cpp.
Referenced by receiveBufferSize(), and sendBufferSize().
 {
     Q_D(const QNativeSocketEngine);
     return d->option(socketOption);
 }
pendingDatagramSize()
qint64 QNativeSocketEngine::pendingDatagramSize () const virtual
Returns the size of the pending datagram, or -1 if no datagram is pending.
A datagram size of 0 is perfectly valid. This function is called by UDP sockets before receiveMessage(). For TCP sockets, call bytesAvailable().
Implements QAbstractSocketEngine.
Definition at line 750 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::pendingDatagramSize(), -1);
     Q_CHECK_TYPE(QNativeSocketEngine::pendingDatagramSize(), QAbstractSocket::UdpSocket, false);
     return d->nativePendingDatagramSize();
 }
read()
qint64 QNativeSocketEngine::read (char * data, qint64 maxSize) virtual
Reads up to maxSize bytes into data from the socket.
Returns the number of bytes read, or -1 if an error occurred.
Implements QAbstractSocketEngine.
Definition at line 833 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::read(), -1);
     Q_CHECK_STATES(QNativeSocketEngine::read(), QAbstractSocket::ConnectedState, QAbstractSocket::BoundState, -1);
     qint64 readBytes = d->nativeRead(data, maxSize);
     // Handle remote close
     if (readBytes == 0 && d->socketType == QAbstractSocket::TcpSocket) {
         d->setError(QAbstractSocket::RemoteHostClosedError,
                     QNativeSocketEnginePrivate::RemoteHostClosedErrorString);
         close();
         return -1;
     } else if (readBytes == -1) {
         if (!d->hasSetSocketError) {
             d->hasSetSocketError = true;
             d->socketError = QAbstractSocket::NetworkError;
             d->socketErrorString = qt_error_string();
         }
         close();
         return -1;
     }
     return readBytes;
 }
readDatagram()
qint64 QNativeSocketEngine::readDatagram (char * data, qint64 maxSize, QHostAddress * address = 0, quint16 * port = 0) virtual
Reads up to maxSize bytes of a datagram from the socket, stores it in data and returns the number of bytes read.
The address and port of the sender are stored in address and port. If either of these pointers is 0, the corresponding value is discarded.
To avoid unnecessarily loss of data, call pendingDatagramSize() to determine the size of the pending message before reading it. If maxSize is too small, the rest of the datagram will be lost.
Returns -1 if an error occurred.
See also
hasPendingDatagrams()
Implements QAbstractSocketEngine.
Definition at line 774 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::readDatagram(), -1);
     Q_CHECK_TYPE(QNativeSocketEngine::readDatagram(), QAbstractSocket::UdpSocket, false);
     return d->nativeReceiveDatagram(data, maxSize, address, port);
 }
receiveBufferSize()
qint64 QNativeSocketEngine::receiveBufferSize () const
Returns the size of the operating system's socket receive buffer.
Depending on the operating system, this size may be different from what has been set earlier with setReceiveBufferSize().
Definition at line 1064 of file qnativesocketengine.cpp.
 {
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::receiveBufferSize(), -1);
     return option(ReceiveBufferSocketOption);
 }
sendBufferSize()
qint64 QNativeSocketEngine::sendBufferSize () const
Returns the size of the operating system send buffer.
Depending on the operating system, this size may be different from what has been set earlier with setSendBufferSize().
Definition at line 1096 of file qnativesocketengine.cpp.
 {
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::setSendBufferSize(), -1);
     return option(SendBufferSocketOption);
 }
setExceptionNotificationEnabled()
void QNativeSocketEngine::setExceptionNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 1262 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     if (d->exceptNotifier) {
         d->exceptNotifier->setEnabled(enable);
     } else if (enable && d->threadData->eventDispatcher) {
         d->exceptNotifier = new QExceptionNotifier(d->socketDescriptor, this);
         d->exceptNotifier->setEnabled(true);
     }
 }
setMulticastInterface()
bool QNativeSocketEngine::setMulticastInterface (const QNetworkInterface & iface) virtual
Since
4.8
Implements QAbstractSocketEngine.
Definition at line 702 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::setMulticastInterface(), false);
     Q_CHECK_TYPE(QNativeSocketEngine::setMulticastInterface(), QAbstractSocket::UdpSocket, false);
     return d->nativeSetMulticastInterface(iface);
 }
setOption()
bool QNativeSocketEngine::setOption (SocketOption option, int value) virtual
Sets the option option to the value value.
Implements QAbstractSocketEngine.
Definition at line 1121 of file qnativesocketengine.cpp.
Referenced by initialize(), setReceiveBufferSize(), and setSendBufferSize().
 {
     Q_D(QNativeSocketEngine);
     return d->setOption(option, value);
 }
setReadNotificationEnabled()
void QNativeSocketEngine::setReadNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 1228 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     if (d->readNotifier) {
         d->readNotifier->setEnabled(enable);
     } else if (enable && d->threadData->eventDispatcher) {
         d->readNotifier = new QReadNotifier(d->socketDescriptor, this);
         d->readNotifier->setEnabled(true);
     }
 }
setReceiveBufferSize()
void QNativeSocketEngine::setReceiveBufferSize (qint64 size)
Sets the size of the operating system receive buffer to size.
For clients, this should be set before connectToHost() is called; otherwise it will have no effect. For servers, it should be called before listen().
The operating system receive buffer size effectively limits two things: how much data can be in transit at any one moment, and how much data can be received in one iteration of the main event loop. Setting the size of the receive buffer may have an impact on the socket's performance.
The default value is operating system-dependent.
Definition at line 1085 of file qnativesocketengine.cpp.
 {
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::setReceiveBufferSize(), Q_VOID);
     setOption(ReceiveBufferSocketOption, size);
 }
setSendBufferSize()
void QNativeSocketEngine::setSendBufferSize (qint64 size)
Sets the size of the operating system send buffer to size.
The operating system send buffer size effectively limits how much data can be in transit at any one moment. Setting the size of the send buffer may have an impact on the socket's performance.
The default value is operating system-dependent.
Definition at line 1111 of file qnativesocketengine.cpp.
Referenced by sendBufferSize().
 {
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::setSendBufferSize(), Q_VOID);
     setOption(SendBufferSocketOption, size);
 }
setWriteNotificationEnabled()
void QNativeSocketEngine::setWriteNotificationEnabled (bool enable) virtual
Implements QAbstractSocketEngine.
Definition at line 1245 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     if (d->writeNotifier) {
         d->writeNotifier->setEnabled(enable);
     } else if (enable && d->threadData->eventDispatcher) {
         d->writeNotifier = new QWriteNotifier(d->socketDescriptor, this);
         d->writeNotifier->setEnabled(true);
     }
 }
socketDescriptor()
int QNativeSocketEngine::socketDescriptor () const virtual
Returns the native socket descriptor.
Any use of this descriptor stands the risk of being non-portable.
Implements QAbstractSocketEngine.
Definition at line 496 of file qnativesocketengine.cpp.
Referenced by initialize().
 {
     Q_D(const QNativeSocketEngine);
     return d->socketDescriptor;
 }
waitForRead()
bool QNativeSocketEngine::waitForRead (int msecs = 30000, bool * timedOut = 0) virtual
Waits for msecs milliseconds or until the socket is ready for reading.
If timedOut is not 0 and msecs milliseconds have passed, the value of timedOut is set to true.
Returns true if data is available for reading; otherwise returns false.
This is a blocking function call; its use is disadvised in a single threaded application, as the whole thread will stop responding until the function returns. waitForRead() is most useful when there is no event loop available. The general approach is to create a QSocketNotifier, passing the socket descriptor returned by socketDescriptor() to its constructor.
Implements QAbstractSocketEngine.
Definition at line 912 of file qnativesocketengine.cpp.
 {
     Q_D(const QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::waitForRead(), false);
     Q_CHECK_NOT_STATE(QNativeSocketEngine::waitForRead(),
                       QAbstractSocket::UnconnectedState, false);
     if (timedOut)
         *timedOut = false;
     int ret = d->nativeSelect(msecs, true);
     if (ret == 0) {
         if (timedOut)
             *timedOut = true;
         d->setError(QAbstractSocket::SocketTimeoutError,
             QNativeSocketEnginePrivate::TimeOutErrorString);
         d->hasSetSocketError = false; // A timeout error is temporary in waitFor functions
         return false;
     } else if (state() == QAbstractSocket::ConnectingState) {
         connectToHost(d->peerAddress, d->peerPort);
     }
     return ret > 0;
 }
waitForReadOrWrite()
bool QNativeSocketEngine::waitForReadOrWrite (bool * readyToRead, bool * readyToWrite, bool checkRead, bool checkWrite, int msecs = 30000, bool * timedOut = 0) virtual
Implements QAbstractSocketEngine.
Definition at line 1006 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::waitForWrite(), false);
     Q_CHECK_NOT_STATE(QNativeSocketEngine::waitForReadOrWrite(),
                       QAbstractSocket::UnconnectedState, false);
     int ret = d->nativeSelect(msecs, checkRead, checkWrite, readyToRead, readyToWrite);
     // On Windows, the socket is in connected state if a call to
     // select(writable) is successful. In this case we should not
     // issue a second call to WSAConnect()
 #if defined (Q_WS_WIN)
     if (checkWrite && ((readyToWrite && *readyToWrite) || !readyToWrite) && ret > 0) {
         setState(QAbstractSocket::ConnectedState);
         d_func()->fetchConnectionParameters();
         return true;
     } else {
         int value = 0;
         int valueSize = sizeof(value);
         if (::getsockopt(d->socketDescriptor, SOL_SOCKET, SO_ERROR, (char *) &value, &valueSize) == 0) {
             if (value == WSAECONNREFUSED) {
                 d->setError(QAbstractSocket::ConnectionRefusedError, QNativeSocketEnginePrivate::ConnectionRefusedErrorString);
                 d->socketState = QAbstractSocket::UnconnectedState;
                 return false;
             } else if (value == WSAETIMEDOUT) {
                 d->setError(QAbstractSocket::NetworkError, QNativeSocketEnginePrivate::ConnectionTimeOutErrorString);
                 d->socketState = QAbstractSocket::UnconnectedState;
                 return false;
             } else if (value == WSAEHOSTUNREACH) {
                 d->setError(QAbstractSocket::NetworkError, QNativeSocketEnginePrivate::HostUnreachableErrorString);
                 d->socketState = QAbstractSocket::UnconnectedState;
                 return false;
             }
         }
     }
 #endif
     if (ret == 0) {
         if (timedOut)
             *timedOut = true;
         d->setError(QAbstractSocket::SocketTimeoutError,
                     QNativeSocketEnginePrivate::TimeOutErrorString);
         d->hasSetSocketError = false; // A timeout error is temporary in waitFor functions
         return false;
     } else if (state() == QAbstractSocket::ConnectingState) {
         connectToHost(d->peerAddress, d->peerPort);
     }
     return ret > 0;
 }
waitForWrite()
bool QNativeSocketEngine::waitForWrite (int msecs = 30000, bool * timedOut = 0) virtual
Waits for msecs milliseconds or until the socket is ready for writing.
If timedOut is not 0 and msecs milliseconds have passed, the value of timedOut is set to true.
Returns true if data is available for writing; otherwise returns false.
This is a blocking function call; its use is disadvised in a single threaded application, as the whole thread will stop responding until the function returns. waitForWrite() is most useful when there is no event loop available. The general approach is to create a QSocketNotifier, passing the socket descriptor returned by socketDescriptor() to its constructor.
Implements QAbstractSocketEngine.
Definition at line 952 of file qnativesocketengine.cpp.
Referenced by waitForReadOrWrite().
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::waitForWrite(), false);
     Q_CHECK_NOT_STATE(QNativeSocketEngine::waitForWrite(),
                       QAbstractSocket::UnconnectedState, false);
     if (timedOut)
         *timedOut = false;
     int ret = d->nativeSelect(msecs, false);
     // On Windows, the socket is in connected state if a call to
     // select(writable) is successful. In this case we should not
     // issue a second call to WSAConnect()
 #if defined (Q_WS_WIN)
     if (ret > 0) {
         setState(QAbstractSocket::ConnectedState);
         d_func()->fetchConnectionParameters();
         return true;
     } else {
         int value = 0;
         int valueSize = sizeof(value);
         if (::getsockopt(d->socketDescriptor, SOL_SOCKET, SO_ERROR, (char *) &value, &valueSize) == 0) {
             if (value == WSAECONNREFUSED) {
                 d->setError(QAbstractSocket::ConnectionRefusedError, QNativeSocketEnginePrivate::ConnectionRefusedErrorString);
                 d->socketState = QAbstractSocket::UnconnectedState;
                 return false;
             } else if (value == WSAETIMEDOUT) {
                 d->setError(QAbstractSocket::NetworkError, QNativeSocketEnginePrivate::ConnectionTimeOutErrorString);
                 d->socketState = QAbstractSocket::UnconnectedState;
                 return false;
             } else if (value == WSAEHOSTUNREACH) {
                 d->setError(QAbstractSocket::NetworkError, QNativeSocketEnginePrivate::HostUnreachableErrorString);
                 d->socketState = QAbstractSocket::UnconnectedState;
                 return false;
             }
         }
     }
 #endif
     if (ret == 0) {
         if (timedOut)
             *timedOut = true;
         d->setError(QAbstractSocket::SocketTimeoutError,
                     QNativeSocketEnginePrivate::TimeOutErrorString);
         d->hasSetSocketError = false; // A timeout error is temporary in waitFor functions
         return false;
     } else if (state() == QAbstractSocket::ConnectingState) {
         connectToHost(d->peerAddress, d->peerPort);
     }
     return ret > 0;
 }
write()
qint64 QNativeSocketEngine::write (const char * data, qint64 size) virtual
Writes a block of size bytes from data to the socket.
Returns the number of bytes written, or -1 if an error occurred.
Implements QAbstractSocketEngine.
Definition at line 815 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::write(), -1);
     Q_CHECK_STATE(QNativeSocketEngine::write(), QAbstractSocket::ConnectedState, -1);
     return d->nativeWrite(data, size);
 }
writeDatagram()
qint64 QNativeSocketEngine::writeDatagram (const char * data, qint64 size, const QHostAddress & host, quint16 port) virtual
Writes a UDP datagram of size size bytes to the socket from data to the address host on port port, and returns the number of bytes written, or -1 if an error occurred.
Only one datagram is sent, and if there is too much data to fit into a single datagram, the operation will fail and error() will return QAbstractSocket::DatagramTooLargeError. Operating systems impose an upper limit to the size of a datagram, but this size is different on almost all platforms. Sending large datagrams is in general disadvised, as even if they are sent successfully, they are likely to be fragmented before arriving at their destination.
Experience has shown that it is in general safe to send datagrams no larger than 512 bytes.
See also
readDatagram()
Implements QAbstractSocketEngine.
Definition at line 802 of file qnativesocketengine.cpp.
 {
     Q_D(QNativeSocketEngine);
     Q_CHECK_VALID_SOCKETLAYER(QNativeSocketEngine::writeDatagram(), -1);
     Q_CHECK_TYPE(QNativeSocketEngine::writeDatagram(), QAbstractSocket::UdpSocket, -1);
     return d->nativeSendDatagram(data, size, host, port);
 }
The documentation for this class was generated from the following files:
/src/network/socket/qnativesocketengine_p.h
/src/network/socket/qnativesocketengine.cpp