Qt 4.8: QXmlAttributes Class Reference
QXmlAttributes Class Reference
The QXmlAttributes class provides XML attributes.
#include <qxml.h>
Classes
struct Attribute
Public Functions
void append (const QString &qName, const QString &uri, const QString &localPart, const QString &value)
Appends a new attribute entry to the list of attributes.
void clear ()
Clears the list of attributes.
int count () const
Returns the number of attributes in the list.
int index (const QString &qName) const
Looks up the index of an attribute by the qualified name qName.
int index (const QLatin1String &qName) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int index (const QString &uri, const QString &localPart) const
Looks up the index of an attribute by a namespace name.
int length () const
Returns the number of attributes in the list.
QString localName (int index) const
Looks up an attribute's local name for the attribute at position index.
QString qName (int index) const
Looks up an attribute's XML 1.0 qualified name for the attribute at position index.
QXmlAttributes ()
Constructs an empty attribute list.
QString type (int index) const
Looks up an attribute's type for the attribute at position index.
QString type (const QString &qName) const
Looks up an attribute's type for the qualified name qName.
QString type (const QString &uri, const QString &localName) const
Looks up an attribute's type by namespace name.
QString uri (int index) const
Looks up an attribute's namespace URI for the attribute at position index.
QString value (int index) const
Returns an attribute's value for the attribute at position index.
QString value (const QString &qName) const
Returns an attribute's value for the qualified name qName, or an empty string if no attribute exists for the name given.
QString value (const QLatin1String &qName) const
Returns an attribute's value for the qualified name qName, or an empty string if no attribute exists for the name given.
QString value (const QString &uri, const QString &localName) const
Returns an attribute's value by namespace name.
virtual ~QXmlAttributes ()
Destroys the attributes object.
Private Types
typedef QList< Attribute > AttributeList
Properties
AttributeList attList
QXmlAttributesPrivate * d
Detailed Description
The QXmlAttributes class provides XML attributes.
Note
This class or function is reentrant.
Attention
Module: QtXml
If attributes are reported by QXmlContentHandler::startElement() this class is used to pass the attribute values.
Use index() to locate the position of an attribute in the list, count() to retrieve the number of attributes, and clear() to remove the attributes. New attributes can be added with append(). Use type() to get an attribute's type and value() to get its value. The attribute's name is available from localName() or qName(), and its namespace URI from uri().
Definition at line 119 of file qxml.h.
Typedefs
AttributeList
typedef QList<Attribute> QXmlAttributes::AttributeList private
Definition at line 148 of file qxml.h.
Constructors and Destructors
QXmlAttributes()
QXmlAttributes::QXmlAttributes () inline
Constructs an empty attribute list.
Definition at line 122 of file qxml.h.
 {}
~QXmlAttributes()
QXmlAttributes::~QXmlAttributes () inline virtual
Destroys the attributes object.
Definition at line 123 of file qxml.h.
 {}
Functions
append()
void QXmlAttributes::append (const QString & qName, const QString & uri, const QString & localPart, const QString & value)
Appends a new attribute entry to the list of attributes.
The qualified name of the attribute is qName, the namespace URI is uri and the local name is localPart. The value of the attribute is value.
See also
qName() uri() localName() value()
Definition at line 1273 of file qxml.cpp.
Referenced by append(), and QXmlSimpleReaderPrivate::processElementAttribute().
 {
     Attribute att;
     att.qname = qName;
     att.uri = uri;
     att.localname = localPart;
     att.value = value;
     attList.append(att);
 }
clear()
void QXmlAttributes::clear (void)
Clears the list of attributes.
See also
append()
Definition at line 1260 of file qxml.cpp.
Referenced by clear(), and QXmlSimpleReaderPrivate::parseElement().
 {
     attList.clear();
 }
count()
int QXmlAttributes::count () const inline
Returns the number of attributes in the list.
This function is equivalent to length().
Definition at line 420 of file qxml.h.
Referenced by length().
 { return length(); }
index() [1/3]
int QXmlAttributes::index (const QString & qName) const
Looks up the index of an attribute by the qualified name qName.
Returns the index of the attribute or -1 if it wasn't found.
See also
{Namespace Support via Features}
Definition at line 1041 of file qxml.cpp.
 {
     for (int i = 0; i < attList.size(); ++i) {
         if (attList.at(i).qname == qName)
             return i;
     }
     return -1;
 }
index() [2/3]
int QXmlAttributes::index (const QLatin1String & qName) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1052 of file qxml.cpp.
 {
     for (int i = 0; i < attList.size(); ++i) {
         if (attList.at(i).qname == qName)
             return i;
     }
     return -1;
 }
index() [3/3]
int QXmlAttributes::index (const QString & uri, const QString & localPart) const
Looks up the index of an attribute by a namespace name.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
uri specifies the namespace URI, or an empty string if the name has no namespace URI. localPart specifies the attribute's local name.
Returns the index of the attribute, or -1 if it wasn't found.
See also
{Namespace Support via Features}
Definition at line 1077 of file qxml.cpp.
 {
     for (int i = 0; i < attList.size(); ++i) {
         const Attribute &att = attList.at(i);
         if (att.uri == uri && att.localname == localPart)
             return i;
     }
     return -1;
 }
length()
int QXmlAttributes::length () const
Returns the number of attributes in the list.
See also
count()
Definition at line 1092 of file qxml.cpp.
Referenced by QDomHandler::startElement().
 {
     return attList.count();
 }
localName()
QString QXmlAttributes::localName (int index) const
Looks up an attribute's local name for the attribute at position index.
If no namespace processing is done, the local name is an empty string.
See also
{Namespace Support via Features}
Definition at line 1114 of file qxml.cpp.
 {
     return attList.at(index).localname;
 }
qName()
QString QXmlAttributes::qName (int index) const
Looks up an attribute's XML 1.0 qualified name for the attribute at position index.
See also
{Namespace Support via Features}
Definition at line 1125 of file qxml.cpp.
Referenced by QDomHandler::startElement().
 {
     return attList.at(index).qname;
 }
type() [1/3]
QString QXmlAttributes::type (int index) const
Looks up an attribute's type for the attribute at position index.
Currently only "CDATA" is returned.
Definition at line 1148 of file qxml.cpp.
 {
     return QLatin1String("CDATA");
 }
type() [2/3]
QString QXmlAttributes::type (const QString & qName) const
Looks up an attribute's type for the qualified name qName.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Currently only "CDATA" is returned.
Definition at line 1163 of file qxml.cpp.
 {
     return QLatin1String("CDATA");
 }
type() [3/3]
QString QXmlAttributes::type (const QString & uri, const QString & localName) const
Looks up an attribute's type by namespace name.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
uri specifies the namespace URI and localName specifies the local name. If the name has no namespace URI, use an empty string for uri.
Currently only "CDATA" is returned.
Definition at line 1182 of file qxml.cpp.
 {
     return QLatin1String("CDATA");
 }
uri()
QString QXmlAttributes::uri (int index) const
Looks up an attribute's namespace URI for the attribute at position index.
If no namespace processing is done or if the attribute has no namespace, the namespace URI is an empty string.
See also
{Namespace Support via Features}
Definition at line 1137 of file qxml.cpp.
Referenced by QDomHandler::startElement(), and uri().
 {
     return attList.at(index).uri;
 }
value() [1/4]
QString QXmlAttributes::value (int index) const
Returns an attribute's value for the attribute at position index.
The index must be a valid position (i.e., 0 <= index < count()).
Definition at line 1192 of file qxml.cpp.
Referenced by QDomHandler::startElement(), and value().
 {
     return attList.at(index).value;
 }
value() [2/4]
QString QXmlAttributes::value (const QString & qName) const
Returns an attribute's value for the qualified name qName, or an empty string if no attribute exists for the name given.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
{Namespace Support via Features}
Definition at line 1208 of file qxml.cpp.
 {
     int i = index(qName);
     if (i == -1)
         return QString();
     return attList.at(i).value;
 }
value() [3/4]
QString QXmlAttributes::value (const QLatin1String & qName) const
Returns an attribute's value for the qualified name qName, or an empty string if no attribute exists for the name given.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
{Namespace Support via Features}
Definition at line 1227 of file qxml.cpp.
 {
     int i = index(qName);
     if (i == -1)
         return QString();
     return attList.at(i).value;
 }
value() [4/4]
QString QXmlAttributes::value (const QString & uri, const QString & localName) const
Returns an attribute's value by namespace name.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
uri specifies the namespace URI, or an empty string if the name has no namespace URI. localName specifies the attribute's local name.
Definition at line 1247 of file qxml.cpp.
 {
     int i = index(uri, localName);
     if (i == -1)
         return QString();
     return attList.at(i).value;
 }
Properties
attList
AttributeList QXmlAttributes::attList private
Definition at line 149 of file qxml.h.
d
QXmlAttributesPrivate* QXmlAttributes::d private
Definition at line 151 of file qxml.h.
The documentation for this class was generated from the following files:
/src/xml/sax/qxml.h
/src/xml/sax/qxml.cpp