Qt 4.8: QStandardItem Class Reference
QStandardItem Class Reference
The QStandardItem class provides an item for use with the QStandardItemModel class.
#include <qstandarditemmodel.h>
Public Types
enum ItemType { Type = 0, UserType = 1000 }
This enum describes the types that are used to describe standard items.
Public Functions
QString accessibleDescription () const
Returns the item's accessible description.
QString accessibleText () const
Returns the item's accessible text.
void appendColumn (const QList< QStandardItem *> &items)
Appends a column containing items.
void appendRow (const QList< QStandardItem *> &items)
Appends a row containing items.
void appendRow (QStandardItem *item)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Appends a row containing item.
void appendRows (const QList< QStandardItem *> &items)
Appends rows containing items.
QBrush background () const
Returns the brush used to render the item's background.
Qt::CheckState checkState () const
Returns the checked state of the item.
QStandardItem * child (int row, int column=0) const
Returns the child item at (row, column) if one has been set; otherwise returns 0.
virtual QStandardItem * clone () const
Returns a copy of this item.
int column () const
Returns the column where the item is located in its parent's child table, or -1 if the item has no parent.
int columnCount () const
Returns the number of child item columns that the item has.
virtual QVariant data (int role=Qt::UserRole+1) const
Returns the item's data for the given role, or an invalid QVariant if there is no data for the role.
Qt::ItemFlags flags () const
Returns the item flags for the item.
QFont font () const
Returns the font used to render the item's text.
QBrush foreground () const
Returns the brush used to render the item's foreground (e.
bool hasChildren () const
Returns true if this item has any children; otherwise returns false.
QIcon icon () const
Returns the item's icon.
QModelIndex index () const
Returns the QModelIndex associated with this item.
void insertColumn (int column, const QList< QStandardItem *> &items)
Inserts a column at column containing items.
void insertColumns (int column, int count)
Inserts count columns of child items at column column.
void insertRow (int row, const QList< QStandardItem *> &items)
Inserts a row at row containing items.
void insertRow (int row, QStandardItem *item)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Inserts a row at row containing item.
void insertRows (int row, const QList< QStandardItem *> &items)
Inserts items at row.
void insertRows (int row, int count)
Inserts count rows of child items at row row.
bool isCheckable () const
Returns whether the item is user-checkable.
bool isDragEnabled () const
Returns whether the item is drag enabled.
bool isDropEnabled () const
Returns whether the item is drop enabled.
bool isEditable () const
Returns whether the item can be edited by the user.
bool isEnabled () const
Returns whether the item is enabled.
bool isSelectable () const
Returns whether the item is selectable by the user.
bool isTristate () const
Returns whether the item is tristate; that is, if it's checkable with three separate states.
QStandardItemModel * model () const
Returns the QStandardItemModel that this item belongs to.
virtual bool operator< (const QStandardItem &other) const
Returns true if this item is less than other; otherwise returns false.
QStandardItem * parent () const
Returns the item's parent item, or 0 if the item has no parent.
QStandardItem ()
Constructs an item.
QStandardItem (const QString &text)
Constructs an item with the given text.
QStandardItem (const QIcon &icon, const QString &text)
Constructs an item with the given icon and text.
QStandardItem (int rows, int columns=1)
Constructs an item with rows rows and columns columns of child items.
virtual void read (QDataStream &in)
Reads the item from stream in.
void removeColumn (int column)
Removes the given column.
void removeColumns (int column, int count)
Removes count columns at column column.
void removeRow (int row)
Removes the given row.
void removeRows (int row, int count)
Removes count rows at row row.
int row () const
Returns the row where the item is located in its parent's child table, or -1 if the item has no parent.
int rowCount () const
Returns the number of child item rows that the item has.
void setAccessibleDescription (const QString &accessibleDescription)
Sets the item's accessible description to the string specified by accessibleDescription.
void setAccessibleText (const QString &accessibleText)
Sets the item's accessible text to the string specified by accessibleText.
void setBackground (const QBrush &brush)
Sets the item's background brush to the specified brush.
void setCheckable (bool checkable)
Sets whether the item is user-checkable.
void setCheckState (Qt::CheckState checkState)
Sets the check state of the item to be state.
void setChild (int row, int column, QStandardItem *item)
Sets the child item at (row, column) to item.
void setChild (int row, QStandardItem *item)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the child at row to item.
void setColumnCount (int columns)
Sets the number of child item columns to columns.
virtual void setData (const QVariant &value, int role=Qt::UserRole+1)
Sets the item's data for the given role to the specified value.
void setDragEnabled (bool dragEnabled)
Sets whether the item is drag enabled.
void setDropEnabled (bool dropEnabled)
Sets whether the item is drop enabled.
void setEditable (bool editable)
Sets whether the item is editable.
void setEnabled (bool enabled)
Sets whether the item is enabled.
void setFlags (Qt::ItemFlags flags)
Sets the item flags for the item to flags.
void setFont (const QFont &font)
Sets the font used to display the item's text to the given font.
void setForeground (const QBrush &brush)
Sets the brush used to display the item's foreground (e.
void setIcon (const QIcon &icon)
Sets the item's icon to the icon specified.
void setRowCount (int rows)
Sets the number of child item rows to rows.
void setSelectable (bool selectable)
Sets whether the item is selectable.
void setSizeHint (const QSize &sizeHint)
Sets the size hint for the item to be size.
void setStatusTip (const QString &statusTip)
Sets the item's status tip to the string specified by statusTip.
void setText (const QString &text)
Sets the item's text to the text specified.
void setTextAlignment (Qt::Alignment textAlignment)
Sets the text alignment for the item's text to the alignment specified.
void setToolTip (const QString &toolTip)
Sets the item's tooltip to the string specified by toolTip.
void setTristate (bool tristate)
Sets whether the item is tristate.
void setWhatsThis (const QString &whatsThis)
Sets the item's "What's This?" help to the string specified by whatsThis.
QSize sizeHint () const
Returns the size hint set for the item, or an invalid QSize if no size hint has been set.
void sortChildren (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts the children of the item using the given order, by the values in the given column.
QString statusTip () const
Returns the item's status tip.
QStandardItem * takeChild (int row, int column=0)
Removes the child item at (row, column) without deleting it, and returns a pointer to the item.
QList< QStandardItem * > takeColumn (int column)
Removes column without deleting the column items, and returns a list of pointers to the removed items.
QList< QStandardItem * > takeRow (int row)
Removes row without deleting the row items, and returns a list of pointers to the removed items.
QString text () const
Returns the item's text.
Qt::Alignment textAlignment () const
Returns the text alignment for the item's text.
QString toolTip () const
Returns the item's tooltip.
virtual int type () const
Returns the type of this item.
QString whatsThis () const
Returns the item's "What's This?" help.
virtual void write (QDataStream &out) const
Writes the item to stream out.
virtual ~QStandardItem ()
Destructs the item.
Protected Functions
void emitDataChanged ()
Causes the model associated with this item to emit a dataChanged() signal for this item.
QStandardItem & operator= (const QStandardItem &other)
Assigns other's data and flags to this item.
QStandardItem (const QStandardItem &other)
Constructs a copy of other.
QStandardItem (QStandardItemPrivate &dd)
Protected Variables
QScopedPointer< QStandardItemPrivate > d_ptr
Friends
class QStandardItemModel
class QStandardItemModelPrivate
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QStandardItem &item)
Writes the QStandardItem item to stream out.
QDataStream & operator>> (QDataStream &in, QStandardItem &item)
Reads a QStandardItem from stream in into item.
Detailed Description
The QStandardItem class provides an item for use with the QStandardItemModel class.
Since
4.2
Items usually contain text, icons, or checkboxes.
Each item can have its own background brush which is set with the setBackground() function. The current background brush can be found with background(). The text label for each item can be rendered with its own font and brush. These are specified with the setFont() and setForeground() functions, and read with font() and foreground().
By default, items are enabled, editable, selectable, checkable, and can be used both as the source of a drag and drop operation and as a drop target. Each item's flags can be changed by calling setFlags(). Checkable items can be checked and unchecked with the setCheckState() function. The corresponding checkState() function indicates whether the item is currently checked.
You can store application-specific data in an item by calling setData().
Each item can have a two-dimensional table of child items. This makes it possible to build hierarchies of items. The typical hierarchy is the tree, in which case the child table is a table with a single column (a list).
The dimensions of the child table can be set with setRowCount() and setColumnCount(). Items can be positioned in the child table with setChild(). Get a pointer to a child item with child(). New rows and columns of children can also be inserted with insertRow() and insertColumn(), or appended with appendRow() and appendColumn(). When using the append and insert functions, the dimensions of the child table will grow as needed.
An existing row of children can be removed with removeRow() or takeRow(); correspondingly, a column can be removed with removeColumn() or takeColumn().
An item's children can be sorted by calling sortChildren().
Subclassing
When subclassing QStandardItem to provide custom items, it is possible to define new types for them so that they can be distinguished from the base class. The type() function should be reimplemented to return a new type value equal to or greater than UserType .
Reimplement data() and setData() if you want to perform custom handling of data queries and/or control how an item's data is represented.
Reimplement clone() if you want QStandardItemModel to be able to create instances of your custom item class on demand (see QStandardItemModel::setItemPrototype()).
Reimplement read() and write() if you want to control how items are represented in their serialized form.
Reimplement operator<() if you want to control the semantics of item comparison. operator<() determines the sorted order when sorting items with sortChildren() or with QStandardItemModel::sort().
See also
QStandardItemModel, {Item View Convenience Classes}, {Model/View Programming}
Definition at line 66 of file qstandarditemmodel.h.
Enumerations
ItemType
enum QStandardItem::ItemType
This enum describes the types that are used to describe standard items.
Type The default type for standard items.
UserType The minimum value for custom types. Values below UserType are reserved by Qt.
You can define new user types in QStandardItem subclasses to ensure that custom items are treated specially; for example, when items are sorted.
See also
type()
Enumerator
Type
UserType
Definition at line 230 of file qstandarditemmodel.h.
 { Type = 0, UserType = 1000 };
Constructors and Destructors
QStandardItem() [1/6]
QStandardItem::QStandardItem ()
Constructs an item.
Definition at line 701 of file qstandarditemmodel.cpp.
Referenced by clone().
     : d_ptr(new QStandardItemPrivate)
 {
     Q_D(QStandardItem);
     d->q_ptr = this;
 }
QStandardItem() [2/6]
QStandardItem::QStandardItem (const QString & text)
Constructs an item with the given text.
Definition at line 711 of file qstandarditemmodel.cpp.
     : d_ptr(new QStandardItemPrivate)
 {
     Q_D(QStandardItem);
     d->q_ptr = this;
     setText(text);
 }
QStandardItem() [3/6]
QStandardItem::QStandardItem (const QIcon & icon, const QString & text)
Constructs an item with the given icon and text.
Definition at line 722 of file qstandarditemmodel.cpp.
     : d_ptr(new QStandardItemPrivate)
 {
     Q_D(QStandardItem);
     d->q_ptr = this;
     setIcon(icon);
     setText(text);
 }
QStandardItem() [4/6]
QStandardItem::QStandardItem (int rows, int columns = 1) explicit
Constructs an item with rows rows and columns columns of child items.
Definition at line 734 of file qstandarditemmodel.cpp.
     : d_ptr(new QStandardItemPrivate)
 {
     Q_D(QStandardItem);
     d->q_ptr = this;
     setRowCount(rows);
     setColumnCount(columns);
 }
~QStandardItem()
QStandardItem::~QStandardItem () virtual
Destructs the item.
This causes the item's children to be destructed as well.
Definition at line 784 of file qstandarditemmodel.cpp.
 {
 }
QStandardItem() [5/6]
QStandardItem::QStandardItem (const QStandardItem & other) protected
Constructs a copy of other.
Note that model() is not copied.
This function is useful when reimplementing clone().
Definition at line 759 of file qstandarditemmodel.cpp.
     : d_ptr(new QStandardItemPrivate)
 {
     Q_D(QStandardItem);
     d->q_ptr = this;
     operator=(other);
 }
QStandardItem() [6/6]
QStandardItem::QStandardItem (QStandardItemPrivate & dd) protected
Warning
This function is not part of the public interface.
Definition at line 746 of file qstandarditemmodel.cpp.
     : d_ptr(&dd)
 {
     Q_D(QStandardItem);
     d->q_ptr = this;
 }
Functions
accessibleDescription()
QString QStandardItem::accessibleDescription () const inline
Returns the item's accessible description.
The accessible description is used by assistive technologies (i.e. for users who cannot use conventional means of interaction).
See also
setAccessibleDescription(), accessibleText()
Definition at line 144 of file qstandarditemmodel.h.
{
         return qvariant_cast<QString>(data(Qt::AccessibleDescriptionRole));
     }
accessibleText()
QString QStandardItem::accessibleText () const inline
Returns the item's accessible text.
The accessible text is used by assistive technologies (i.e. for users who cannot use conventional means of interaction).
See also
setAccessibleText(), accessibleDescription()
Definition at line 139 of file qstandarditemmodel.h.
{
         return qvariant_cast<QString>(data(Qt::AccessibleTextRole));
     }
appendColumn()
void QStandardItem::appendColumn (const QList< QStandardItem *> & items) inline
Appends a column containing items.
If necessary, the row count is increased to the size of items.
See also
insertColumn()
Definition at line 307 of file qstandarditemmodel.h.
Referenced by QStandardItemModel::appendColumn().
 { insertColumn(columnCount(), aitems); }
appendRow() [1/2]
void QStandardItem::appendRow (const QList< QStandardItem *> & items) inline
Appends a row containing items.
If necessary, the column count is increased to the size of items.
See also
insertRow()
Definition at line 301 of file qstandarditemmodel.h.
Referenced by QStandardItemModel::appendRow().
 { insertRow(rowCount(), aitems); }
appendRow() [2/2]
void QStandardItem::appendRow (QStandardItem * item) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Appends a row containing item.
When building a list or a tree that has only one column, this function provides a convenient way to append a single new item.
Definition at line 313 of file qstandarditemmodel.h.
 { insertRow(rowCount(), aitem); }
appendRows()
void QStandardItem::appendRows (const QList< QStandardItem *> & items) inline
Appends rows containing items.
The column count will not change.
See also
insertRow()
Definition at line 304 of file qstandarditemmodel.h.
 { insertRows(rowCount(), aitems); }
background()
QBrush QStandardItem::background () const inline
Returns the brush used to render the item's background.
See also
foreground() setBackground()
Definition at line 124 of file qstandarditemmodel.h.
{
         return qvariant_cast<QBrush>(data(Qt::BackgroundRole));
     }
checkState()
Qt::CheckState QStandardItem::checkState () const inline
Returns the checked state of the item.
See also
setCheckState(), isCheckable()
Definition at line 134 of file qstandarditemmodel.h.
{
         return Qt::CheckState(qvariant_cast<int>(data(Qt::CheckStateRole)));
     }
child()
QStandardItem * QStandardItem::child (int row, int column = 0) const
Returns the child item at (row, column) if one has been set; otherwise returns 0.
See also
setChild(), takeChild(), parent()
Definition at line 1811 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModelPrivate::itemFromIndex(), QStandardItemModel::itemFromIndex(), and QStandardItemPrivate::sortChildren().
 {
     Q_D(const QStandardItem);
     int index = d->childIndex(row, column);
     if (index == -1)
         return 0;
     return d->children.at(index);
 }
clone()
QStandardItem * QStandardItem::clone () const virtual
Returns a copy of this item.
The item's children are not copied.
When subclassing QStandardItem, you can reimplement this function to provide QStandardItemModel with a factory that it can use to create new items on demand.
See also
QStandardItemModel::setItemPrototype(), operator=()
Definition at line 1982 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModelPrivate::createItem().
 {
     return new QStandardItem(*this);
 }
column()
int QStandardItem::column () const
Returns the column where the item is located in its parent's child table, or -1 if the item has no parent.
See also
row(), parent()
Definition at line 1457 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::mimeData(), and takeRow().
 {
     Q_D(const QStandardItem);
     QPair<int, int> pos = d->position();
     return pos.second;
 }
columnCount()
int QStandardItem::columnCount () const
Returns the number of child item columns that the item has.
See also
setColumnCount(), rowCount()
Definition at line 1546 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::columnCount(), hasChildren(), QStandardItemModel::index(), insertColumns(), insertRow(), QStandardItemModel::mimeData(), removeColumns(), QStandardItemModel::removeColumns(), setColumnCount(), and takeColumn().
 {
     Q_D(const QStandardItem);
     return d->columnCount();
 }
data()
QVariant QStandardItem::data (int role = Qt::UserRole + 1) const virtual
Returns the item's data for the given role, or an invalid QVariant if there is no data for the role.
Note
The default implementation treats Qt::EditRole and Qt::DisplayRole as referring to the same data.
Definition at line 845 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::data(), flags(), QStandardItemModel::headerData(), operator<(), and setCheckable().
 {
     Q_D(const QStandardItem);
     role = (role == Qt::EditRole) ? Qt::DisplayRole : role;
     QVector<QWidgetItemData>::const_iterator it;
     for (it = d->values.begin(); it != d->values.end(); ++it) {
         if ((*it).role == role)
             return (*it).value;
     }
     return QVariant();
 }
emitDataChanged()
void QStandardItem::emitDataChanged () protected
Causes the model associated with this item to emit a dataChanged() signal for this item.
Since
4.4
You normally only need to call this function if you have subclassed QStandardItem and reimplemented data() and/or setData().
See also
setData()
Definition at line 872 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     if (d->model)
         d->model->d_func()->itemChanged(this);
 }
flags()
Qt::ItemFlags QStandardItem::flags () const
Returns the item flags for the item.
The item flags determine how the user can interact with the item.
By default, items are enabled, editable, selectable, checkable, and can be used both as the source of a drag and drop operation and as a drop target.
See also
setFlags()
Definition at line 902 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::flags(), read(), and write().
 {
     QVariant v = data(Qt::UserRole - 1);
     if (!v.isValid())
         return (Qt::ItemIsSelectable|Qt::ItemIsEnabled|Qt::ItemIsEditable
                 |Qt::ItemIsDragEnabled|Qt::ItemIsDropEnabled);
     return Qt::ItemFlags(v.toInt());
 }
font()
QFont QStandardItem::font () const inline
Returns the font used to render the item's text.
See also
setFont()
Definition at line 114 of file qstandarditemmodel.h.
{
         return qvariant_cast<QFont>(data(Qt::FontRole));
     }
foreground()
QBrush QStandardItem::foreground () const inline
Returns the brush used to render the item's foreground (e.
g. text).
\sa setForeground() background()
Definition at line 129 of file qstandarditemmodel.h.
{
         return qvariant_cast<QBrush>(data(Qt::ForegroundRole));
     }
hasChildren()
bool QStandardItem::hasChildren () const
Returns true if this item has any children; otherwise returns false.
See also
rowCount(), columnCount(), child()
Definition at line 1780 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::hasChildren().
 {
     return (rowCount() > 0) && (columnCount() > 0);
 }
icon()
QIcon QStandardItem::icon () const inline
Returns the item's icon.
See also
setIcon(), {QAbstractItemView::iconSize}{iconSize}
Definition at line 83 of file qstandarditemmodel.h.
{
         return qvariant_cast<QIcon>(data(Qt::DecorationRole));
     }
index()
QModelIndex QStandardItem::index () const
Returns the QModelIndex associated with this item.
When you need to invoke item functionality in a QModelIndex-based API (e.g. QAbstractItemView), you can call this function to obtain an index that corresponds to the item's location in the model.
If the item is not associated with a model, an invalid QModelIndex is returned.
See also
model(), QStandardItemModel::itemFromIndex()
Definition at line 1476 of file qstandarditemmodel.cpp.
Referenced by child(), QStandardItemModel::dropMimeData(), takeChild(), takeColumn(), and takeRow().
 {
     Q_D(const QStandardItem);
     return d->model ? d->model->indexFromItem(this) : QModelIndex();
 }
insertColumn()
void QStandardItem::insertColumn (int column, const QList< QStandardItem *> & items)
Inserts a column at column containing items.
If necessary, the row count is increased to the size of items.
See also
insertColumns(), insertRow()
Definition at line 1587 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::insertColumn().
 {
     Q_D(QStandardItem);
     if (column < 0)
         return;
     if (rowCount() < items.count())
         setRowCount(items.count());
     d->insertColumns(column, 1, items);
 }
insertColumns()
void QStandardItem::insertColumns (int column, int count)
Inserts count columns of child items at column column.
See also
insertColumn(), insertRows()
Definition at line 1617 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::insertColumns(), and setColumnCount().
 {
     Q_D(QStandardItem);
     if (columnCount() < column) {
         count += column - columnCount();
         column = columnCount();
     }
     d->insertColumns(column, count, QList<QStandardItem*>());
 }
insertRow() [1/2]
void QStandardItem::insertRow (int row, const QList< QStandardItem *> & items)
Inserts a row at row containing items.
If necessary, the column count is increased to the size of items.
See also
insertRows(), insertColumn()
Definition at line 1558 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::insertRow().
 {
     Q_D(QStandardItem);
     if (row < 0)
         return;
     if (columnCount() < items.count())
         setColumnCount(items.count());
     d->insertRows(row, 1, items);
 }
insertRow() [2/2]
void QStandardItem::insertRow (int row, QStandardItem * item) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Inserts a row at row containing item.
When building a list or a tree that has only one column, this function provides a convenient way to insert a single new item.
Definition at line 310 of file qstandarditemmodel.h.
 { insertRow(arow, QList<QStandardItem*>() << aitem); }
insertRows() [1/2]
void QStandardItem::insertRows (int row, const QList< QStandardItem *> & items)
Inserts items at row.
The column count wont be changed.
See also
insertRow(), insertColumn()
Definition at line 1573 of file qstandarditemmodel.cpp.
Referenced by QComboBox::insertItems(), QStandardItemModel::insertRows(), and setRowCount().
 {
     Q_D(QStandardItem);
     if (row < 0)
         return;
     d->insertRows(row, items);
 }
insertRows() [2/2]
void QStandardItem::insertRows (int row, int count)
Inserts count rows of child items at row row.
See also
insertRow(), insertColumns()
Definition at line 1602 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     if (rowCount() < row) {
         count += row - rowCount();
         row = rowCount();
     }
     d->insertRows(row, count, QList<QStandardItem*>());
 }
isCheckable()
bool QStandardItem::isCheckable () const inline
Returns whether the item is user-checkable.
The default value is false.
See also
setCheckable(), checkState(), isTristate()
Definition at line 167 of file qstandarditemmodel.h.
Referenced by setCheckable().
{
         return (flags() & Qt::ItemIsUserCheckable) != 0;
     }
isDragEnabled()
bool QStandardItem::isDragEnabled () const inline
Returns whether the item is drag enabled.
An item that is drag enabled can be dragged by the user.
The default value is true.
Note that item dragging must be enabled in the view for dragging to work; see QAbstractItemView::dragEnabled.
See also
setDragEnabled(), isDropEnabled(), flags()
Definition at line 178 of file qstandarditemmodel.h.
{
         return (flags() & Qt::ItemIsDragEnabled) != 0;
     }
isDropEnabled()
bool QStandardItem::isDropEnabled () const inline
Returns whether the item is drop enabled.
When an item is drop enabled, it can be used as a drop target.
The default value is true.
See also
setDropEnabled(), isDragEnabled(), flags()
Definition at line 183 of file qstandarditemmodel.h.
{
         return (flags() & Qt::ItemIsDropEnabled) != 0;
     }
isEditable()
bool QStandardItem::isEditable () const inline
Returns whether the item can be edited by the user.
When an item is editable (and enabled), the user can edit the item by invoking one of the view's edit triggers; see QAbstractItemView::editTriggers.
The default value is true.
See also
setEditable(), flags()
Definition at line 157 of file qstandarditemmodel.h.
{
         return (flags() & Qt::ItemIsEditable) != 0;
     }
isEnabled()
bool QStandardItem::isEnabled () const inline
Returns whether the item is enabled.
When an item is enabled, the user can interact with it. The possible types of interaction are specified by the other item flags, such as isEditable() and isSelectable().
The default value is true.
See also
setEnabled(), flags()
Definition at line 152 of file qstandarditemmodel.h.
{
         return (flags() & Qt::ItemIsEnabled) != 0;
     }
isSelectable()
bool QStandardItem::isSelectable () const inline
Returns whether the item is selectable by the user.
The default value is true.
See also
setSelectable(), flags()
Definition at line 162 of file qstandarditemmodel.h.
{
         return (flags() & Qt::ItemIsSelectable) != 0;
     }
isTristate()
bool QStandardItem::isTristate () const inline
Returns whether the item is tristate; that is, if it's checkable with three separate states.
The default value is false.
See also
setTristate(), isCheckable(), checkState()
Definition at line 172 of file qstandarditemmodel.h.
{
         return (flags() & Qt::ItemIsTristate) != 0;
     }
model()
QStandardItemModel * QStandardItem::model () const
Returns the QStandardItemModel that this item belongs to.
If the item is not a child of another item that belongs to the model, this function returns 0.
See also
index()
Definition at line 1490 of file qstandarditemmodel.cpp.
Referenced by QStandardItemPrivate::insertRows(), operator<(), QStandardItemModel::setHorizontalHeaderItem(), QStandardItemPrivate::setModel(), and QStandardItemModel::setVerticalHeaderItem().
 {
     Q_D(const QStandardItem);
     return d->model;
 }
operator<()
bool QStandardItem::operator< (const QStandardItem & other) const virtual
Returns true if this item is less than other; otherwise returns false.
The default implementation uses the data for the item's sort role (see QStandardItemModel::sortRole) to perform the comparison if the item belongs to a model; otherwise, the data for the item's Qt::DisplayRole (text()) is used to perform the comparison.
sortChildren() and QStandardItemModel::sort() use this function when sorting items. If you want custom sorting, you can subclass QStandardItem and reimplement this function.
Definition at line 1918 of file qstandarditemmodel.cpp.
 {
     const int role = model() ? model()->sortRole() : Qt::DisplayRole;
     const QVariant l = data(role), r = other.data(role);
     // this code is copied from QSortFilterProxyModel::lessThan()
     switch (l.userType()) {
     case QVariant::Invalid:
         return (r.type() == QVariant::Invalid);
     case QVariant::Int:
         return l.toInt() < r.toInt();
     case QVariant::UInt:
         return l.toUInt() < r.toUInt();
     case QVariant::LongLong:
         return l.toLongLong() < r.toLongLong();
     case QVariant::ULongLong:
         return l.toULongLong() < r.toULongLong();
     case QMetaType::Float:
         return l.toFloat() < r.toFloat();
     case QVariant::Double:
         return l.toDouble() < r.toDouble();
     case QVariant::Char:
         return l.toChar() < r.toChar();
     case QVariant::Date:
         return l.toDate() < r.toDate();
     case QVariant::Time:
         return l.toTime() < r.toTime();
     case QVariant::DateTime:
         return l.toDateTime() < r.toDateTime();
     case QVariant::String:
     default:
         return l.toString().compare(r.toString()) < 0;
     }
 }
operator=()
QStandardItem & QStandardItem::operator= (const QStandardItem & other) protected
Assigns other's data and flags to this item.
Note that type() and model() are not copied.
This function is useful when reimplementing clone().
Definition at line 773 of file qstandarditemmodel.cpp.
Referenced by QStandardItem().
 {
     Q_D(QStandardItem);
     d->values = other.d_func()->values;
     return *this;
 }
parent()
QStandardItem * QStandardItem::parent () const
Returns the item's parent item, or 0 if the item has no parent.
See also
child()
Definition at line 793 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::indexFromItem(), QStandardItemPrivate::insertColumns(), QStandardItemPrivate::insertRows(), QStandardItemModelPrivate::itemChanged(), and QStandardItemPrivate::setChild().
 {
     Q_D(const QStandardItem);
     if (!d->model || (d->model->d_func()->root.data() != d->parent))
         return d->parent;
     return 0;
 }
read()
void QStandardItem::read (QDataStream & in) virtual
Reads the item from stream in.
Only the data and flags of the item are read, not the child items.
See also
write()
Definition at line 2008 of file qstandarditemmodel.cpp.
Referenced by operator>>().
 {
     Q_D(QStandardItem);
     in >> d->values;
     qint32 flags;
     in >> flags;
     setFlags(Qt::ItemFlags(flags));
 }
removeColumn()
void QStandardItem::removeColumn (int column)
Removes the given column.
The items that were in the column are deleted.
See also
takeColumn(), removeColumns(), removeRow()
Definition at line 1715 of file qstandarditemmodel.cpp.
 {
     removeColumns(column, 1);
 }
removeColumns()
void QStandardItem::removeColumns (int column, int count)
Removes count columns at column column.
The items that were in those columns are deleted.
See also
removeColumn(), removeRows()
Definition at line 1753 of file qstandarditemmodel.cpp.
Referenced by removeColumn(), QStandardItemModel::removeColumns(), and setColumnCount().
 {
     Q_D(QStandardItem);
     if ((count < 1) || (column < 0) || ((column + count) > columnCount()))
         return;
     if (d->model)
         d->model->d_func()->columnsAboutToBeRemoved(this, column, column + count - 1);
     for (int row = d->rowCount() - 1; row >= 0; --row) {
         int i = d->childIndex(row, column);
         for (int j=i; j<i+count; ++j) {
             QStandardItem *oldItem = d->children.at(j);
             if (oldItem)
                 oldItem->d_func()->setModel(0);
             delete oldItem;
         }
         d->children.remove(i, count);
     }
     d->columns -= count;
     if (d->model)
         d->model->d_func()->columnsRemoved(this, column, count);
 }
removeRow()
void QStandardItem::removeRow (int row)
Removes the given row.
The items that were in the row are deleted.
See also
takeRow(), removeRows(), removeColumn()
Definition at line 1704 of file qstandarditemmodel.cpp.
 {
     removeRows(row, 1);
 }
removeRows()
void QStandardItem::removeRows (int row, int count)
Removes count rows at row row.
The items that were in those rows are deleted.
See also
removeRow(), removeColumn()
Definition at line 1726 of file qstandarditemmodel.cpp.
Referenced by removeRow(), QStandardItemModel::removeRows(), and setRowCount().
 {
     Q_D(QStandardItem);
     if ((count < 1) || (row < 0) || ((row + count) > rowCount()))
         return;
     if (d->model)
         d->model->d_func()->rowsAboutToBeRemoved(this, row, row + count - 1);
     int i = d->childIndex(row, 0);
     int n = count * d->columnCount();
     for (int j = i; j < n+i; ++j) {
         QStandardItem *oldItem = d->children.at(j);
         if (oldItem)
             oldItem->d_func()->setModel(0);
         delete oldItem;
     }
     d->children.remove(qMax(i, 0), n);
     d->rows -= count;
     if (d->model)
         d->model->d_func()->rowsRemoved(this, row, count);
 }
row()
int QStandardItem::row () const
Returns the row where the item is located in its parent's child table, or -1 if the item has no parent.
See also
column(), parent()
Definition at line 1444 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::mimeData(), removeColumns(), and takeColumn().
 {
     Q_D(const QStandardItem);
     QPair<int, int> pos = d->position();
     return pos.first;
 }
rowCount()
int QStandardItem::rowCount () const
Returns the number of child item rows that the item has.
See also
setRowCount(), columnCount()
Definition at line 1518 of file qstandarditemmodel.cpp.
Referenced by hasChildren(), QStandardItemModel::index(), insertColumn(), insertRows(), removeRows(), QStandardItemModel::removeRows(), QStandardItemModel::rowCount(), setRowCount(), sortChildren(), and takeRow().
 {
     Q_D(const QStandardItem);
     return d->rowCount();
 }
setAccessibleDescription()
void QStandardItem::setAccessibleDescription (const QString & accessibleDescription) inline
Sets the item's accessible description to the string specified by accessibleDescription.
The accessible description is used by assistive technologies (i.e. for users who cannot use conventional means of interaction).
See also
accessibleDescription(), setAccessibleText()
Definition at line 295 of file qstandarditemmodel.h.
 { setData(aaccessibleDescription, Qt::AccessibleDescriptionRole); }
setAccessibleText()
void QStandardItem::setAccessibleText (const QString & accessibleText) inline
Sets the item's accessible text to the string specified by accessibleText.
The accessible text is used by assistive technologies (i.e. for users who cannot use conventional means of interaction).
See also
accessibleText(), setAccessibleDescription()
Definition at line 292 of file qstandarditemmodel.h.
 { setData(aaccessibleText, Qt::AccessibleTextRole); }
setBackground()
void QStandardItem::setBackground (const QBrush & brush) inline
Sets the item's background brush to the specified brush.
See also
background() setForeground()
Definition at line 283 of file qstandarditemmodel.h.
 { setData(abrush, Qt::BackgroundRole); }
setCheckable()
void QStandardItem::setCheckable (bool checkable)
Sets whether the item is user-checkable.
If checkable is true, the item can be checked by the user; otherwise, the user cannot check the item.
The item delegate will render a checkable item with a check box next to the item's text.
See also
isCheckable(), setCheckState(), setTristate()
Definition at line 1320 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     if (checkable && !isCheckable()) {
         // make sure there's data for the checkstate role
         if (!data(Qt::CheckStateRole).isValid())
             setData(Qt::Unchecked, Qt::CheckStateRole);
     }
     d->changeFlags(checkable, Qt::ItemIsUserCheckable);
 }
setCheckState()
void QStandardItem::setCheckState (Qt::CheckState state) inline
Sets the check state of the item to be state.
See also
checkState(), setCheckable()
Definition at line 289 of file qstandarditemmodel.h.
 { setData(acheckState, Qt::CheckStateRole); }
setChild() [1/2]
void QStandardItem::setChild (int row, int column, QStandardItem * item)
Sets the child item at (row, column) to item.
This item (the parent item) takes ownership of item. If necessary, the row count and column count are increased to fit the item.
See also
child()
Definition at line 1792 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModel::dropMimeData(), and QStandardItemModel::itemFromIndex().
 {
     Q_D(QStandardItem);
     d->setChild(row, column, item, true);
 }
setChild() [2/2]
void QStandardItem::setChild (int row, QStandardItem * item) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Sets the child at row to item.
Definition at line 298 of file qstandarditemmodel.h.
 { setChild(arow, 0, aitem); }
setColumnCount()
void QStandardItem::setColumnCount (int columns)
Sets the number of child item columns to columns.
If this is less than columnCount(), the data in the unwanted columns is discarded.
See also
columnCount(), setRowCount()
Definition at line 1530 of file qstandarditemmodel.cpp.
Referenced by insertRow(), and QStandardItem().
 {
     int cc = columnCount();
     if (cc == columns)
         return;
     if (cc < columns)
         insertColumns(qMax(cc, 0), columns - cc);
     else
         removeColumns(qMax(columns, 0), cc - columns);
 }
setData()
void QStandardItem::setData (const QVariant & value, int role = Qt::UserRole + 1) virtual
Sets the item's data for the given role to the specified value.
If you subclass QStandardItem and reimplement this function, your reimplementation should call emitDataChanged() if you do not call the base implementation of setData(). This will ensure that e.g. views using the model are notified of the changes.
Note
The default implementation treats Qt::EditRole and Qt::DisplayRole as referring to the same data.
See also
Qt::ItemDataRole, data(), setFlags()
Definition at line 814 of file qstandarditemmodel.cpp.
Referenced by QComboBox::insertItem(), setCheckable(), QStandardItemModel::setData(), setFlags(), and QStandardItemModel::setHeaderData().
 {
     Q_D(QStandardItem);
     role = (role == Qt::EditRole) ? Qt::DisplayRole : role;
     QVector<QWidgetItemData>::iterator it;
     for (it = d->values.begin(); it != d->values.end(); ++it) {
         if ((*it).role == role) {
             if (value.isValid()) {
                 if ((*it).value.type() == value.type() && (*it).value == value)
                     return;
                 (*it).value = value;
             } else {
                 d->values.erase(it);
             }
             if (d->model)
                 d->model->d_func()->itemChanged(this);
             return;
         }
     }
     d->values.append(QWidgetItemData(role, value));
     if (d->model)
         d->model->d_func()->itemChanged(this);
 }
setDragEnabled()
void QStandardItem::setDragEnabled (bool dragEnabled)
Sets whether the item is drag enabled.
If dragEnabled is true, the item can be dragged by the user; otherwise, the user cannot drag the item.
Note that you also need to ensure that item dragging is enabled in the view; see QAbstractItemView::dragEnabled.
See also
isDragEnabled(), setDropEnabled(), setFlags()
Definition at line 1383 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     d->changeFlags(dragEnabled, Qt::ItemIsDragEnabled);
 }
setDropEnabled()
void QStandardItem::setDropEnabled (bool dropEnabled)
Sets whether the item is drop enabled.
If dropEnabled is true, the item can be used as a drop target; otherwise, it cannot.
Note that you also need to ensure that drops are enabled in the view; see QWidget::acceptDrops(); and that the model supports the desired drop actions; see QAbstractItemModel::supportedDropActions().
See also
isDropEnabled(), setDragEnabled(), setFlags()
Definition at line 1416 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     d->changeFlags(dropEnabled, Qt::ItemIsDropEnabled);
 }
setEditable()
void QStandardItem::setEditable (bool editable)
Sets whether the item is editable.
If editable is true, the item can be edited by the user; otherwise, the user cannot edit the item.
How the user can edit items in a view is determined by the view's edit triggers; see QAbstractItemView::editTriggers.
See also
isEditable(), setFlags()
Definition at line 1258 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     d->changeFlags(editable, Qt::ItemIsEditable);
 }
setEnabled()
void QStandardItem::setEnabled (bool enabled)
Sets whether the item is enabled.
If enabled is true, the item is enabled, meaning that the user can interact with the item; if enabled is false, the user cannot interact with the item.
This flag takes precedence over the other item flags; e.g. if an item is not enabled, it cannot be selected by the user, even if the Qt::ItemIsSelectable flag has been set.
See also
isEnabled(), Qt::ItemIsEnabled, setFlags()
Definition at line 1226 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     d->changeFlags(enabled, Qt::ItemIsEnabled);
 }
setFlags()
void QStandardItem::setFlags (Qt::ItemFlags flags)
Sets the item flags for the item to flags.
The item flags determine how the user can interact with the item. This is often used to disable an item.
See also
flags(), setData()
Definition at line 887 of file qstandarditemmodel.cpp.
Referenced by QStandardItemModelPrivate::QStandardItemModelPrivate(), and read().
 {
     setData((int)flags, Qt::UserRole - 1);
 }
setFont()
void QStandardItem::setFont (const QFont & font) inline
Sets the font used to display the item's text to the given font.
See also
font() setText() setForeground()
Definition at line 277 of file qstandarditemmodel.h.
 { setData(afont, Qt::FontRole); }
setForeground()
void QStandardItem::setForeground (const QBrush & brush) inline
Sets the brush used to display the item's foreground (e.
g. text) to the given brush.
See also
foreground() setBackground() setFont()
Definition at line 286 of file qstandarditemmodel.h.
 { setData(abrush, Qt::ForegroundRole); }
setIcon()
void QStandardItem::setIcon (const QIcon & icon) inline
Sets the item's icon to the icon specified.
Definition at line 256 of file qstandarditemmodel.h.
Referenced by QStandardItem().
 { setData(aicon, Qt::DecorationRole); }
setRowCount()
void QStandardItem::setRowCount (int rows)
Sets the number of child item rows to rows.
If this is less than rowCount(), the data in the unwanted rows is discarded.
See also
rowCount(), setColumnCount()
Definition at line 1502 of file qstandarditemmodel.cpp.
Referenced by insertColumn(), and QStandardItem().
 {
     int rc = rowCount();
     if (rc == rows)
         return;
     if (rc < rows)
         insertRows(qMax(rc, 0), rows - rc);
     else
         removeRows(qMax(rows, 0), rc - rows);
 }
setSelectable()
void QStandardItem::setSelectable (bool selectable)
Sets whether the item is selectable.
If selectable is true, the item can be selected by the user; otherwise, the user cannot select the item.
You can control the selection behavior and mode by manipulating their view properties; see QAbstractItemView::selectionMode and QAbstractItemView::selectionBehavior.
See also
isSelectable(), setFlags()
Definition at line 1291 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     d->changeFlags(selectable, Qt::ItemIsSelectable);
 }
setSizeHint()
void QStandardItem::setSizeHint (const QSize & size) inline
Sets the size hint for the item to be size.
If no size hint is set, the item delegate will compute the size hint based on the item data.
See also
sizeHint()
Definition at line 274 of file qstandarditemmodel.h.
 { setData(asizeHint, Qt::SizeHintRole); }
setStatusTip()
void QStandardItem::setStatusTip (const QString & statusTip) inline
Sets the item's status tip to the string specified by statusTip.
See also
statusTip(), setToolTip(), setWhatsThis()
Definition at line 265 of file qstandarditemmodel.h.
 { setData(astatusTip, Qt::StatusTipRole); }
setText()
void QStandardItem::setText (const QString & text) inline
Sets the item's text to the text specified.
See also
text(), setFont(), setForeground()
Definition at line 253 of file qstandarditemmodel.h.
Referenced by QStandardItem(), QStandardItemModel::setHorizontalHeaderLabels(), and QStandardItemModel::setVerticalHeaderLabels().
 { setData(atext, Qt::DisplayRole); }
setTextAlignment()
void QStandardItem::setTextAlignment (Qt::Alignment alignment) inline
Sets the text alignment for the item's text to the alignment specified.
See also
textAlignment()
Definition at line 280 of file qstandarditemmodel.h.
 { setData(int(atextAlignment), Qt::TextAlignmentRole); }
setToolTip()
void QStandardItem::setToolTip (const QString & toolTip) inline
Sets the item's tooltip to the string specified by toolTip.
See also
toolTip(), setStatusTip(), setWhatsThis()
Definition at line 260 of file qstandarditemmodel.h.
 { setData(atoolTip, Qt::ToolTipRole); }
setTristate()
void QStandardItem::setTristate (bool tristate)
Sets whether the item is tristate.
If tristate is true, the item is checkable with three separate states; otherwise, the item is checkable with two states. (Note that this also requires that the item is checkable; see isCheckable().)
See also
isTristate(), setCheckable(), setCheckState()
Definition at line 1352 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     d->changeFlags(tristate, Qt::ItemIsTristate);
 }
setWhatsThis()
void QStandardItem::setWhatsThis (const QString & whatsThis) inline
Sets the item's "What's This?" help to the string specified by whatsThis.
See also
whatsThis(), setStatusTip(), setToolTip()
Definition at line 270 of file qstandarditemmodel.h.
 { setData(awhatsThis, Qt::WhatsThisRole); }
sizeHint()
QSize QStandardItem::sizeHint () const inline
Returns the size hint set for the item, or an invalid QSize if no size hint has been set.
If no size hint has been set, the item delegate will compute the size hint based on the item data.
See also
setSizeHint()
Definition at line 109 of file qstandarditemmodel.h.
{
         return qvariant_cast<QSize>(data(Qt::SizeHintRole));
     }
sortChildren()
void QStandardItem::sortChildren (int column, Qt::SortOrder order = Qt::AscendingOrder)
Sorts the children of the item using the given order, by the values in the given column.
Note
This function is recursive, therefore it sorts the children of the item, its grandchildren, etc.
See also
{operator<()}
Definition at line 1961 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     if ((column < 0) || (rowCount() == 0))
         return;
     if (d->model)
         emit d->model->layoutAboutToBeChanged();
     d->sortChildren(column, order);
     if (d->model)
         emit d->model->layoutChanged();
 }
statusTip()
QString QStandardItem::statusTip () const inline
Returns the item's status tip.
See also
setStatusTip(), toolTip(), whatsThis()
Definition at line 96 of file qstandarditemmodel.h.
{
         return qvariant_cast<QString>(data(Qt::StatusTipRole));
     }
takeChild()
QStandardItem * QStandardItem::takeChild (int row, int column = 0)
Removes the child item at (row, column) without deleting it, and returns a pointer to the item.
If there was no child at the given location, then this function returns 0.
Note that this function, unlike takeRow() and takeColumn(), does not affect the dimensions of the child table.
See also
child(), takeRow(), takeColumn()
Definition at line 1830 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     QStandardItem *item = 0;
     int index = d->childIndex(row, column);
     if (index != -1) {
         item = d->children.at(index);
         if (item)
             item->d_func()->setParentAndModel(0, 0);
         d->children.replace(index, 0);
     }
     return item;
 }
takeColumn()
QList< QStandardItem * > QStandardItem::takeColumn (int column)
Removes column without deleting the column items, and returns a list of pointers to the removed items.
For items in the column that have not been set, the corresponding pointers in the list will be 0.
See also
removeColumn(), insertColumn(), takeRow()
Definition at line 1883 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     if ((column < 0) || (column >= columnCount()))
         return QList<QStandardItem*>();
     if (d->model)
         d->model->d_func()->columnsAboutToBeRemoved(this, column, column);
     QList<QStandardItem*> items;
     for (int row = d->rowCount() - 1; row >= 0; --row) {
         int index = d->childIndex(row, column);
         QStandardItem *ch = d->children.at(index);
         if (ch)
             ch->d_func()->setParentAndModel(0, 0);
         d->children.remove(index);
         items.prepend(ch);
     }
     d->columns--;
     if (d->model)
         d->model->d_func()->columnsRemoved(this, column, 1);
     return items;
 }
takeRow()
QList< QStandardItem * > QStandardItem::takeRow (int row)
Removes row without deleting the row items, and returns a list of pointers to the removed items.
For items in the row that have not been set, the corresponding pointers in the list will be 0.
See also
removeRow(), insertRow(), takeColumn()
Definition at line 1851 of file qstandarditemmodel.cpp.
 {
     Q_D(QStandardItem);
     if ((row < 0) || (row >= rowCount()))
         return QList<QStandardItem*>();
     if (d->model)
         d->model->d_func()->rowsAboutToBeRemoved(this, row, row);
     QList<QStandardItem*> items;
     int index = d->childIndex(row, 0);  // Will return -1 if there are no columns
     if (index != -1) {
         int col_count = d->columnCount();
         for (int column = 0; column < col_count; ++column) {
             QStandardItem *ch = d->children.at(index + column);
             if (ch)
                 ch->d_func()->setParentAndModel(0, 0);
             items.append(ch);
         }
         d->children.remove(index, col_count);
     }
     d->rows--;
     if (d->model)
         d->model->d_func()->rowsRemoved(this, row, 1);
     return items;
 }
text()
QString QStandardItem::text () const inline
Returns the item's text.
This is the text that's presented to the user in a view.
See also
setText()
Definition at line 78 of file qstandarditemmodel.h.
{
         return qvariant_cast<QString>(data(Qt::DisplayRole));
     }
textAlignment()
int QStandardItem::textAlignment () const inline
Returns the text alignment for the item's text.
Definition at line 119 of file qstandarditemmodel.h.
{
         return Qt::Alignment(qvariant_cast<int>(data(Qt::TextAlignmentRole)));
     }
toolTip()
QString QStandardItem::toolTip () const inline
Returns the item's tooltip.
See also
setToolTip(), statusTip(), whatsThis()
Definition at line 89 of file qstandarditemmodel.h.
{
         return qvariant_cast<QString>(data(Qt::ToolTipRole));
     }
type()
int QStandardItem::type () const virtual
Returns the type of this item.
The type is used to distinguish custom items from the base class. When subclassing QStandardItem, you should reimplement this function and return a new value greater than or equal to UserType .
See also
QStandardItem::Type
Definition at line 1995 of file qstandarditemmodel.cpp.
 {
     return Type;
 }
whatsThis()
QString QStandardItem::whatsThis () const inline
Returns the item's "What's This?" help.
See also
setWhatsThis(), toolTip(), statusTip()
Definition at line 103 of file qstandarditemmodel.h.
{
         return qvariant_cast<QString>(data(Qt::WhatsThisRole));
     }
write()
void QStandardItem::write (QDataStream & out) const virtual
Writes the item to stream out.
Only the data and flags of the item are written, not the child items.
See also
read()
Definition at line 2023 of file qstandarditemmodel.cpp.
Referenced by operator<<().
 {
     Q_D(const QStandardItem);
     out << d->values;
     out << flags();
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & out, const QStandardItem & item) related
Writes the QStandardItem item to stream out.
Since
4.2
This operator uses QStandardItem::write().
See also
{Serializing Qt Data Types}
Definition at line 2062 of file qstandarditemmodel.cpp.
 {
     item.write(out);
     return out;
 }
operator>>()
QDataStream & operator>> (QDataStream & in, QStandardItem & item) related
Reads a QStandardItem from stream in into item.
Since
4.2
This operator uses QStandardItem::read().
See also
{Serializing Qt Data Types}
Definition at line 2043 of file qstandarditemmodel.cpp.
 {
     item.read(in);
     return in;
 }
QStandardItemModel
friend class QStandardItemModel friend
Definition at line 250 of file qstandarditemmodel.h.
QStandardItemModelPrivate
friend class QStandardItemModelPrivate friend
Definition at line 249 of file qstandarditemmodel.h.
Properties
d_ptr
QScopedPointer<QStandardItemPrivate> QStandardItem::d_ptr protected
Definition at line 243 of file qstandarditemmodel.h.
Referenced by QStandardItemModel::mimeData().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qstandarditemmodel.h
/src/gui/itemviews/qstandarditemmodel.cpp