Qt 4.8: QDeclarativeDebugServer Class Reference
QDeclarativeDebugServer Class Reference
#include <qdeclarativedebugserver_p.h>
Public Functions
bool addService (QDeclarativeDebugService *service)
bool hasDebuggingClient () const
void receiveMessage (const QByteArray &message)
bool removeService (QDeclarativeDebugService *service)
void sendMessage (QDeclarativeDebugService *service, const QByteArray &message)
QStringList serviceNames () const
QList< QDeclarativeDebugService * > services () const
void setConnection (QDeclarativeDebugServerConnection *connection)
bool waitForMessage (QDeclarativeDebugService *service)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeDebugServer * instance ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Functions
QDeclarativeDebugServer ()
Friends
class QDeclarativeDebugService
class QDeclarativeDebugServicePrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 57 of file qdeclarativedebugserver_p.h.
Constructors and Destructors
QDeclarativeDebugServer()
QDeclarativeDebugServer::QDeclarativeDebugServer () private
Definition at line 239 of file qdeclarativedebugserver.cpp.
 : QObject(*(new QDeclarativeDebugServerPrivate))
 {
 }
Functions
addService()
bool QDeclarativeDebugServer::addService (QDeclarativeDebugService * service)
Definition at line 360 of file qdeclarativedebugserver.cpp.
 {
     Q_D(QDeclarativeDebugServer);
     if (!service || d->plugins.contains(service->name()))
         return false;
     d->plugins.insert(service->name(), service);
     d->advertisePlugins();
     QDeclarativeDebugService::Status newStatus = QDeclarativeDebugService::Unavailable;
     if (d->clientPlugins.contains(service->name()))
         newStatus = QDeclarativeDebugService::Enabled;
     service->d_func()->status = newStatus;
     service->statusChanged(newStatus);
     return true;
 }
hasDebuggingClient()
bool QDeclarativeDebugServer::hasDebuggingClient () const
Definition at line 156 of file qdeclarativedebugserver.cpp.
Referenced by QDeclarativeDebugService::hasDebuggingClient().
 {
     Q_D(const QDeclarativeDebugServer);
     return d->connection
             && d->connection->isConnected()
             && d->gotHello;
 }
instance()
QDeclarativeDebugServer * QDeclarativeDebugServer::instance () static
Definition at line 164 of file qdeclarativedebugserver.cpp.
Referenced by QDeclarativeDebugService::hasDebuggingClient(), QDeclarativeDebugService::isDebuggingEnabled(), and QDeclarativeDebugService::QDeclarativeDebugService().
 {
     static bool commandLineTested = false;
     static QDeclarativeDebugServer *server = 0;
     if (!commandLineTested) {
         commandLineTested = true;
         QCoreApplicationPrivate *appD = static_cast<QCoreApplicationPrivate*>(QObjectPrivate::get(qApp));
 #ifndef QDECLARATIVE_NO_DEBUG_PROTOCOL
         // ### remove port definition when protocol is changed
         int port = 0;
         bool block = false;
         bool ok = false;
         // format: qmljsdebugger=port:3768[,block] OR qmljsdebugger=ost[,block]
         if (!appD->qmljsDebugArguments().isEmpty()) {
             if (!QDeclarativeEnginePrivate::qml_debugging_enabled) {
                 qWarning() << QString::fromLatin1(
                                   "QDeclarativeDebugServer: Ignoring \"-qmljsdebugger=%1\". "
                                   "Debugging has not been enabled.").arg(
                                   appD->qmljsDebugArguments());
                 return 0;
             }
             QString pluginName;
             if (appD->qmljsDebugArguments().indexOf(QLatin1String("port:")) == 0) {
                 int separatorIndex = appD->qmljsDebugArguments().indexOf(QLatin1Char(','));
                 port = appD->qmljsDebugArguments().mid(5, separatorIndex - 5).toInt(&ok);
                 pluginName = QLatin1String("qmldbg_tcp");
             } else if (appD->qmljsDebugArguments().contains(QLatin1String("ost"))) {
                 pluginName = QLatin1String("qmldbg_ost");
                 ok = true;
             }
             block = appD->qmljsDebugArguments().contains(QLatin1String("block"));
             if (ok) {
                 server = new QDeclarativeDebugServer();
                 QPluginLoader *loader = new QPluginLoader(server);
                 QDeclarativeDebugServerConnection *connection
                         = QDeclarativeDebugServerPrivate::loadConnectionPlugin(loader, pluginName);
                 if (connection) {
                     server->d_func()->connection = connection;
                     connection->setServer(server);
                     connection->setPort(port, block);
                 } else {
                     qWarning() << QString::fromLatin1(
                                       "QDeclarativeDebugServer: Ignoring \"-qmljsdebugger=%1\". "
                                       "Remote debugger plugin has not been found.").arg(
                                       appD->qmljsDebugArguments());
                 }
             } else {
                 qWarning() << QString::fromLatin1(
                                   "QDeclarativeDebugServer: Ignoring \"-qmljsdebugger=%1\". "
                                   "Format is -qmljsdebugger=port:<port>[,block]").arg(
                                   appD->qmljsDebugArguments());
             }
         }
 #else
         if (!appD->qmljsDebugArguments().isEmpty()) {
             qWarning() << QString::fromLatin1(
                               "QDeclarativeDebugServer: Ignoring \"-qmljsdebugger=%1\". "
                               "QtDeclarative is not configured for debugging.").arg(
                               appD->qmljsDebugArguments());
         }
 #endif
     }
     return server;
 }
receiveMessage()
void QDeclarativeDebugServer::receiveMessage (const QByteArray & message)
Definition at line 244 of file qdeclarativedebugserver.cpp.
 {
     Q_D(QDeclarativeDebugServer);
     QDataStream in(message);
     if (!d->gotHello) {
         QString name;
         int op;
         in >> name >> op;
         if (name != QLatin1String("QDeclarativeDebugServer")
                 || op != 0) {
             qWarning("QDeclarativeDebugServer: Invalid hello message");
             d->connection->disconnect();
             return;
         }
         int version;
         in >> version >> d->clientPlugins;
         // Send the hello answer immediately, since it needs to arrive before
         // the plugins below start sending messages.
         QByteArray helloAnswer;
         {
             QDataStream out(&helloAnswer, QIODevice::WriteOnly);
             out << QString(QLatin1String("QDeclarativeDebugClient")) << 0 << protocolVersion << d->plugins.keys();
         }
         d->connection->send(helloAnswer);
         d->gotHello = true;
         QHash<QString, QDeclarativeDebugService*>::Iterator iter = d->plugins.begin();
         for (; iter != d->plugins.end(); ++iter) {
             QDeclarativeDebugService::Status newStatus = QDeclarativeDebugService::Unavailable;
             if (d->clientPlugins.contains(iter.key()))
                 newStatus = QDeclarativeDebugService::Enabled;
             iter.value()->d_func()->status = newStatus;
             iter.value()->statusChanged(newStatus);
         }
         qDebug("QDeclarativeDebugServer: Connection established");
     } else {
         QString debugServer(QLatin1String("QDeclarativeDebugServer"));
         QString name;
         in >> name;
         if (name == debugServer) {
             int op = -1;
             in >> op;
             if (op == 1) {
                 // Service Discovery
                 QStringList oldClientPlugins = d->clientPlugins;
                 in >> d->clientPlugins;
                 QHash<QString, QDeclarativeDebugService*>::Iterator iter = d->plugins.begin();
                 for (; iter != d->plugins.end(); ++iter) {
                     const QString pluginName = iter.key();
                     QDeclarativeDebugService::Status newStatus = QDeclarativeDebugService::Unavailable;
                     if (d->clientPlugins.contains(pluginName))
                         newStatus = QDeclarativeDebugService::Enabled;
                     if (oldClientPlugins.contains(pluginName)
                             != d->clientPlugins.contains(pluginName)) {
                         iter.value()->d_func()->status = newStatus;
                         iter.value()->statusChanged(newStatus);
                     }
                 }
             } else {
                 qWarning("QDeclarativeDebugServer: Invalid control message %d", op);
             }
         } else {
             QByteArray message;
             in >> message;
             if (d->waitingForMsgFromService == name) {
                 // deliver directly so that it is delivered before waitForMessage is returning.
                 d->_q_deliverMessage(name, message);
                 d->waitingForMsgSucceeded = true;
             } else {
                 // deliver message in next event loop run.
                 // Fixes the case that the service does start it's own event loop ...,
                 // but the networking code doesn't deliver any new messages because readyRead
                 // hasn't returned.
                 QMetaObject::invokeMethod(this, "_q_deliverMessage", Qt::QueuedConnection,
                                           Q_ARG(QString, name),
                                           Q_ARG(QByteArray, message));
             }
         }
     }
 }
removeService()
bool QDeclarativeDebugServer::removeService (QDeclarativeDebugService * service)
Definition at line 377 of file qdeclarativedebugserver.cpp.
 {
     Q_D(QDeclarativeDebugServer);
     if (!service || !d->plugins.contains(service->name()))
         return false;
     d->plugins.remove(service->name());
     d->advertisePlugins();
     QDeclarativeDebugService::Status newStatus = QDeclarativeDebugService::NotConnected;
     service->d_func()->server = 0;
     service->d_func()->status = newStatus;
     service->statusChanged(newStatus);
     return true;
 }
sendMessage()
void QDeclarativeDebugServer::sendMessage (QDeclarativeDebugService * service, const QByteArray & message)
Definition at line 393 of file qdeclarativedebugserver.cpp.
 {
     Q_D(QDeclarativeDebugServer);
     QByteArray msg;
     {
         QDataStream out(&msg, QIODevice::WriteOnly);
         out << service->name() << message;
     }
     d->connection->send(msg);
 }
serviceNames()
QStringList QDeclarativeDebugServer::serviceNames () const
Definition at line 354 of file qdeclarativedebugserver.cpp.
 {
     const Q_D(QDeclarativeDebugServer);
     return d->plugins.keys();
 }
services()
QList< QDeclarativeDebugService * > QDeclarativeDebugServer::services () const
Definition at line 348 of file qdeclarativedebugserver.cpp.
 {
     const Q_D(QDeclarativeDebugServer);
     return d->plugins.values();
 }
setConnection()
void QDeclarativeDebugServer::setConnection (QDeclarativeDebugServerConnection * connection)
waitForMessage()
bool QDeclarativeDebugServer::waitForMessage (QDeclarativeDebugService * service)
Definition at line 405 of file qdeclarativedebugserver.cpp.
 {
     Q_D(QDeclarativeDebugServer);
     if (!service
             || !d->plugins.contains(service->name())
             || !d->waitingForMsgFromService.isEmpty())
         return false;
     d->waitingForMsgFromService = service->name();
     do {
         d->connection->waitForMessage();
     } while (!d->waitingForMsgSucceeded);
     d->waitingForMsgSucceeded = false;
     d->waitingForMsgFromService.clear();
     return true;
 }
Friends and Related Functions
QDeclarativeDebugService
friend class QDeclarativeDebugService friend
Definition at line 81 of file qdeclarativedebugserver_p.h.
QDeclarativeDebugServicePrivate
friend class QDeclarativeDebugServicePrivate friend
Definition at line 82 of file qdeclarativedebugserver_p.h.
The documentation for this class was generated from the following files:
/src/declarative/debugger/qdeclarativedebugserver_p.h
/src/declarative/debugger/qdeclarativedebugserver.cpp