Qt 4.8: QDecorationStyled Class Reference
QDecorationStyled Class Reference
#include <qdecorationstyled_qws.h>
Public Functions
bool paint (QPainter *painter, const QWidget *widget, int decorationRegion=All, DecorationState state=Normal)
Paints the border and title decoration for the top-level widget using the painter provided and the decoration state.
QDecorationStyled ()
QRegion region (const QWidget *widget, const QRect &rect, int decorationRegion=All)
Returns the region specified by decorationRegion for the top-level widget.
int titleBarHeight (const QWidget *widget)
Returns the title bar height in pixels for the given widget.
virtual ~QDecorationStyled ()
Public Functions inherited from QDecorationDefault
QDecorationDefault ()
Default constructor.
virtual ~QDecorationDefault ()
The constructor deletes the static pixmaps.
Public Functions inherited from QDecoration
virtual void buildSysMenu (QWidget *widget, QMenu *menu)
Builds the system menu for the given top level widget, adding Restore, Move, Size, Minimize, Maximize and Close actions to the given menu.
void menuTriggered (QWidget *widget, QAction *action)
This function is called whenever an action in a top level widget's menu is triggered, and simply calls the regionClicked() function passing the widget and action parameters as arguments.
QDecoration ()
Constructs a decoration object.
QRegion region (const QWidget *w, int decorationRegion=All)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
virtual int regionAt (const QWidget *w, const QPoint &point)
Returns the type of the first region of the specified top level widget containing the given point.
virtual void regionClicked (QWidget *widget, int region)
Handles the event that the specified region in the given top level widget is activated by a single click (the region parameter is described using the DecorationRegion enum).
virtual void regionDoubleClicked (QWidget *widget, int region)
Handles the event that the specified region in the given top level widget is activated by a double click (the region parameter is described using the DecorationRegion enum).
virtual ~QDecoration ()
Destroys this decoration object.
Additional Inherited Members
Public Types inherited from QDecoration
enum DecorationRegion {
None = 0x0000000000, All = 0x7fffffff, TopLeft = 0x0000000001, Top = 0x0000000002,
TopRight = 0x0000000004, Left = 0x0000000008, Right = 0x0000000010, BottomLeft = 0x0000000020,
Bottom = 0x0000000040, BottomRight = 0x0000000080, Borders = 0x00000000ff, Menu = 0x0000000100,
Title = 0x0000000200, Help = 0x0000000400, Minimize = 0x0000000800, Maximize = 0x0000001000,
Normalize = 0x0000002000, Close = 0x0000004000, Move = 0x0000008000, Resize = 0x0000010000
}
This enum describes the various regions of the window decoration.
enum DecorationState { Normal = 0x04, Disabled = 0x08, Hover = 0x01, Pressed = 0x02 }
This enum describes the various states of a decoration region.
Static Public Functions inherited from QDecoration
static void startMove (QWidget *widget)
Starts to move the given top level widget by making its Title region active and grabbing the mouse input.
static void startResize (QWidget *widget)
Starts to resize the given top level widget by making its BottomRight region active and grabbing the mouse input.
Protected Functions inherited from QDecorationDefault
virtual void paintButton (QPainter *painter, const QWidget *widget, int buttonRegion, DecorationState state, const QPalette &pal)
Paints a region of the top-level widget.
virtual QPixmap pixmapFor (const QWidget *widget, int decorationRegion, int &xoff, int &yoff)
Returns a pointer to the QPixmap for the widget specified by widget and decorationRegion.
QString windowTitleFor (const QWidget *widget) const
virtual const char ** xpmForRegion (int region)
Returns a pointer to the X pixmap for the icon specified by region.
Protected Variables inherited from QDecorationDefault
int close_width
int help_width
int maximize_width
int menu_width
int minimize_width
int normalize_width
Detailed Description
Definition at line 55 of file qdecorationstyled_qws.h.
Constructors and Destructors
QDecorationStyled()
QDecorationStyled::QDecorationStyled ()
Definition at line 55 of file qdecorationstyled_qws.cpp.
     : QDecorationDefault()
 {
 }
~QDecorationStyled()
QDecorationStyled::~QDecorationStyled () virtual
Definition at line 60 of file qdecorationstyled_qws.cpp.
 {
 }
Functions
paint()
bool QDecorationStyled::paint (QPainter * painter, const QWidget * widget, int decorationRegion = All, DecorationState state = Normal) virtual
Paints the border and title decoration for the top-level widget using the painter provided and the decoration state.
The value of decorationRegion is a combination of the bitmask values of enum DecorationRegion.
Note that Qt for Embedded Linux expects this function to return true if any of the widget's decorations are repainted; otherwise it returns false.
Reimplemented from QDecorationDefault.
Definition at line 87 of file qdecorationstyled_qws.cpp.
 {
     if (decorationRegion == None)
         return false;
     bool isActive = (widget == qApp->activeWindow());
     QPalette pal = qApp->palette();
     //ideally, the difference between Active and Inactive should be enough, so we shouldn't need to test this
     if (!isActive) {
         //pal.setCurrentColorGroup(QPalette::Disabled); //Can't do this either, because of palette limitations
         //copied from Q3TitleBar:
     pal.setColor(QPalette::Inactive, QPalette::Highlight,
              pal.color(QPalette::Inactive, QPalette::Dark));
         pal.setColor(QPalette::Inactive, QPalette::Base,
                       pal.color(QPalette::Inactive, QPalette::Dark));
         pal.setColor(QPalette::Inactive, QPalette::HighlightedText,
                       pal.color(QPalette::Inactive, QPalette::Window));
     }
     Qt::WindowFlags flags = widget->windowFlags();
     bool hasBorder = !widget->isMaximized();
     bool hasTitle = flags & Qt::WindowTitleHint;
     bool hasSysMenu = flags & Qt::WindowSystemMenuHint;
     bool hasContextHelp = flags & Qt::WindowContextHelpButtonHint;
     bool hasMinimize = flags & Qt::WindowMinimizeButtonHint;
     bool hasMaximize = flags & Qt::WindowMaximizeButtonHint;
     bool paintAll = (DecorationRegion(decorationRegion) == All);
     bool handled = false;
     QStyle *style = QApplication::style();
     // In the case of a borderless title bar, the title bar must be expanded one
     // borderWidth to the left, right and up.
     bool noTitleBorder = style->styleHint(QStyle::SH_TitleBar_NoBorder, 0, widget);
     int borderWidth = style->pixelMetric(QStyle::PM_MDIFrameWidth, 0, 0);
     int titleHeight = titleBarHeight(widget) + (noTitleBorder ? borderWidth : 0);
     int titleExtra = noTitleBorder ? borderWidth : 0;
     if ((paintAll || decorationRegion & Borders) && state == Normal && hasBorder) {
         QRegion newClip = painter->clipRegion();
         if (hasTitle) { // reduce flicker
             QRect rect(widget->rect());
             QRect r(rect.left() - titleExtra, rect.top() - titleHeight,
                     rect.width() + 2 * titleExtra, titleHeight);
             newClip -= r;
         }
         if (!newClip.isEmpty()) {
             QRect br = QDecoration::region(widget).boundingRect();
             painter->save();
             painter->setClipRegion(newClip);
             QStyleOptionFrame opt;
             opt.palette = pal;
             opt.rect = br;
             opt.lineWidth = borderWidth;
             if (isActive)
                 opt.state |= QStyle::State_Active;
             bool porterDuff = painter->paintEngine()->hasFeature(QPaintEngine::PorterDuff);
             if (porterDuff)
                 painter->setCompositionMode(QPainter::CompositionMode_Source);
             painter->fillRect(br, pal.window());
             if (porterDuff)
                 painter->setCompositionMode(QPainter::CompositionMode_SourceOver);
             style->drawPrimitive(QStyle::PE_FrameWindow, &opt, painter, 0);
             painter->restore();
             decorationRegion &= (~Borders);
             handled |= true;
         }
     }
     if (hasTitle) {
         painter->save();
         QStyleOptionTitleBar opt;
         opt.subControls = (decorationRegion & Title
                               ? QStyle::SC_TitleBarLabel : QStyle::SubControl(0))
                           | (decorationRegion & Menu
                               ? QStyle::SC_TitleBarSysMenu : QStyle::SubControl(0))
                           | (decorationRegion & Help
                               ? QStyle::SC_TitleBarContextHelpButton : QStyle::SubControl(0))
                           | (decorationRegion & Minimize
                               ? QStyle::SC_TitleBarMinButton : QStyle::SubControl(0))
                           | (decorationRegion & Maximize
                               ? QStyle::SC_TitleBarMaxButton : QStyle::SubControl(0))
                           | (decorationRegion & (Minimize | Maximize)
                               ? QStyle::SC_TitleBarNormalButton : QStyle::SubControl(0))
                           | (decorationRegion & Close
                               ? QStyle::SC_TitleBarCloseButton : QStyle::SubControl(0));
         opt.titleBarFlags = widget->windowFlags();
         opt.titleBarState = widget->windowState();
         if (isActive)
             opt.titleBarState |= QStyle::State_Active;
         opt.text = windowTitleFor(widget);
         opt.icon = widget->windowIcon();
         opt.palette = pal;
         opt.rect = QRect(widget->rect().x() - titleExtra, -titleHeight,
                          widget->rect().width() + 2 * titleExtra, titleHeight);
         if (paintAll) {
             painter->setClipRegion(opt.rect);
         } else {
             const QRect widgetRect = widget->rect();
             QRegion newClip = opt.rect;
             if (!(decorationRegion & Menu) && hasSysMenu)
                 newClip -= region(widget, widgetRect, Menu);
             if (!(decorationRegion & Title) && hasTitle)
                 newClip -= region(widget, widgetRect, Title);
             if (!(decorationRegion & Help) && hasContextHelp)
                 newClip -= region(widget, widgetRect, Help);
             if (!(decorationRegion & Minimize) && hasMinimize)
                 newClip -= region(widget, widgetRect, Minimize);
             if (!(decorationRegion & Maximize) && hasMaximize)
                 newClip -= region(widget, widgetRect, Maximize);
             if (!(decorationRegion & (Minimize | Maximize)) && (hasMaximize | hasMinimize))
                 newClip -= region(widget, widgetRect, Normal);
             if (!(decorationRegion & Close))
                 newClip -= region(widget, widgetRect, Close);
             painter->setClipRegion(newClip);
         }
         if (state == Pressed)
             opt.activeSubControls = opt.subControls;
         style->drawComplexControl(QStyle::CC_TitleBar, &opt, painter, 0);
         painter->restore();
         decorationRegion &= ~(Title | Menu | Help | Normalize | Minimize | Maximize | Close);
         handled |= true;
     }
     return handled;
 }
region()
QRegion QDecorationStyled::region (const QWidget * widget, const QRect & rect, int decorationRegion = All) virtual
Returns the region specified by decorationRegion for the top-level widget.
rect specifies the rectangle the decoration wraps. The value of decorationRegion is a combination of the bitmask values of enum DecorationRegion.
Reimplemented from QDecorationDefault.
Definition at line 224 of file qdecorationstyled_qws.cpp.
Referenced by paint().
 {
     QStyle *style = QApplication::style();
     // In the case of a borderless title bar, the title bar must be expanded one
     // borderWidth to the left, right and up.
     bool noTitleBorder = style->styleHint(QStyle::SH_TitleBar_NoBorder, 0, widget);
     int borderWidth = style->pixelMetric(QStyle::PM_MDIFrameWidth, 0, 0);
     int titleHeight = titleBarHeight(widget) + (noTitleBorder ? borderWidth : 0);
     int titleExtra = noTitleBorder ? borderWidth : 0;
     QRect inside = QRect(rect.x() - titleExtra, rect.top() - titleHeight,
                          rect.width() + 2 * titleExtra, titleHeight);
     Qt::WindowFlags flags = widget->windowFlags();
     bool hasSysMenu = flags & Qt::WindowSystemMenuHint;
     bool hasContextHelp = flags & Qt::WindowContextHelpButtonHint;
     bool hasMinimize = flags & Qt::WindowMinimizeButtonHint;
     bool hasMaximize = flags & Qt::WindowMaximizeButtonHint;
     QStyleOptionTitleBar opt;
     opt.subControls = QStyle::SC_TitleBarLabel
                       | QStyle::SC_TitleBarSysMenu
                       | QStyle::SC_TitleBarNormalButton
                       | QStyle::SC_TitleBarMinButton
                       | QStyle::SC_TitleBarMaxButton
                       | QStyle::SC_TitleBarCloseButton;
     opt.titleBarFlags = widget->windowFlags();
     opt.direction = QApplication::layoutDirection();
     opt.text = windowTitleFor(widget);
     opt.icon = widget->windowIcon();
     opt.rect = inside;
     QRegion region;
     switch (decorationRegion) {
     case Title:
         region = style->subControlRect(QStyle::CC_TitleBar, &opt,
                                        QStyle::SC_TitleBarLabel, 0);
         break;
     case Menu:
         if (hasSysMenu)
             region = style->subControlRect(QStyle::CC_TitleBar, &opt,
                                            QStyle::SC_TitleBarSysMenu, 0);
         break;
     case Help:
         if (hasContextHelp)
             region = style->subControlRect(QStyle::CC_TitleBar, &opt,
                                            QStyle::SC_TitleBarContextHelpButton,
                                            0);
         break;
     case Normalize:
         if (hasMaximize | hasMinimize)
             region = style->subControlRect(QStyle::CC_TitleBar, &opt,
                                            QStyle::SC_TitleBarNormalButton,
                                            0);
         break;
     case Minimize:
         if (hasMinimize)
             region = style->subControlRect(QStyle::CC_TitleBar, &opt,
                                            QStyle::SC_TitleBarMinButton,
                                            0);
         break;
     case Maximize:
         if (hasMaximize)
             region = style->subControlRect(QStyle::CC_TitleBar, &opt,
                                            QStyle::SC_TitleBarMaxButton,
                                            0);
         break;
     case Close:
         region = style->subControlRect(QStyle::CC_TitleBar, &opt,
                                        QStyle::SC_TitleBarCloseButton, 0);
         break;
     default:
         region = QDecorationDefault::region(widget, rect, decorationRegion);
     }
     opt.rect = QRect(rect.x() - titleExtra, rect.top() - titleHeight,
                          rect.width() + 2 * titleExtra,
                          rect.height() + titleHeight + titleExtra);
     QStyleHintReturnMask mask;
     style->styleHint(QStyle::SH_WindowFrame_Mask, &opt, 0, &mask);
     return (mask.region.isEmpty() ? region : (region & mask.region));
 }
titleBarHeight()
int QDecorationStyled::titleBarHeight (const QWidget * widget) virtual
Returns the title bar height in pixels for the given widget.
It is the greater of 20, or the sum of the application font's line spacing value plus a border width fudge factor.
Reimplemented from QDecorationDefault.
Definition at line 64 of file qdecorationstyled_qws.cpp.
Referenced by paint(), and region().
 {
     QStyleOptionTitleBar opt;
     opt.subControls = QStyle::SC_TitleBarLabel
                       | QStyle::SC_TitleBarSysMenu
                       | QStyle::SC_TitleBarNormalButton
                       | QStyle::SC_TitleBarContextHelpButton
                       | QStyle::SC_TitleBarMinButton
                       | QStyle::SC_TitleBarMaxButton
                       | QStyle::SC_TitleBarCloseButton;
     opt.titleBarFlags = widget->windowFlags();
     opt.direction = QApplication::layoutDirection();
     opt.text = windowTitleFor(widget);
     opt.icon = widget->windowIcon();
     opt.rect = widget->rect();
     QStyle *style = QApplication::style();
     if (!style)
         return 18;
     return style->pixelMetric(QStyle::PM_TitleBarHeight, &opt, 0);
 }
The documentation for this class was generated from the following files:
/src/gui/embedded/qdecorationstyled_qws.h
/src/gui/embedded/qdecorationstyled_qws.cpp