Qt 4.8: QRfbMultiColorHextile< SRC > Class Template Reference
QRfbMultiColorHextile< SRC > Class Template Reference
#include <qscreenvnc_p.h>
Public Functions
QRfbMultiColorHextile (QRfbHextileEncoder< SRC > *e)
QRfbMultiColorHextile (QRfbHextileEncoder< SRC > *e)
bool read (const uchar *data, int width, int height, int stride)
bool read (const uchar *data, int width, int height, int stride)
void write (QTcpSocket *socket) const
void write (QTcpSocket *socket) const
Private Functions
bool beginRect ()
bool beginRect ()
void endRect ()
void endRect ()
quint8 * rect (int r)
const quint8 * rect (int r) const
quint8 * rect (int r)
const quint8 * rect (int r) const
int rectx (int r) const
int rectx (int r) const
int recty (int r) const
int recty (int r) const
void setColor (SRC color)
void setColor (SRC color)
void setHeight (int r, int height)
void setHeight (int r, int height)
void setWidth (int r, int width)
void setWidth (int r, int width)
void setX (int r, int x)
void setX (int r, int x)
void setY (int r, int y)
void setY (int r, int y)
Properties
quint8 bpp
QRfbHextileEncoder< SRC > * encoder
quint8 numRects
QVarLengthArray< quint8, maxRectsSize > rects
Static Private Attributes
static const int maxRectsSize = 16 * 16
Detailed Description
template<class SRC>
class QRfbMultiColorHextile< SRC >
Definition at line 349 of file qscreenvnc_p.h.
Constructors and Destructors
QRfbMultiColorHextile() [1/2]
template<class SRC> QRfbMultiColorHextile< SRC >::QRfbMultiColorHextile (QRfbHextileEncoder< SRC > * e) inline
Definition at line 352 of file qscreenvnc_p.h.
 : encoder(e) {}
QRfbMultiColorHextile() [2/2]
template<class SRC> QRfbMultiColorHextile< SRC >::QRfbMultiColorHextile (QRfbHextileEncoder< SRC > * e) inline
Definition at line 358 of file qvncserver.h.
 : encoder(e) {}
Functions
beginRect() [1/2]
template<class SRC > bool QRfbMultiColorHextile< SRC >::beginRect () inline private
Definition at line 1300 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     if ((rects.size() + bpp + 2) > maxRectsSize)
         return false;
     rects.resize(rects.size() + bpp + 2);
     return true;
 }
beginRect() [2/2]
template<class SRC> bool QRfbMultiColorHextile< SRC >::beginRect () private
endRect() [1/2]
template<class SRC > void QRfbMultiColorHextile< SRC >::endRect () inline private
Definition at line 1309 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     setHeight(numRects, 1);
     ++numRects;
 }
endRect() [2/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::endRect () private
read() [1/2]
template<class SRC > bool QRfbMultiColorHextile< SRC >::read (const uchar * data, int width, int height, int stride)
Definition at line 1316 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     const SRC *ptr = reinterpret_cast<const SRC*>(data);
     const int linestep = (stride / sizeof(SRC)) - width;
     bpp = encoder->server->clientBytesPerPixel();
     if (encoder->newBg)
         encoder->bg = ptr[0];
     const SRC bg = encoder->bg;
     SRC color = bg;
     bool inRect = false;
     numRects = 0;
     rects.clear();
     for (int y = 0; y < height; ++y) {
         for (int x = 0; x < width; ++x) {
             if (inRect && *ptr != color) { // end rect
                 setWidth(numRects, x - rectx(numRects));
                 endRect();
                 inRect = false;
             }
             if (!inRect && *ptr != bg) { // begin rect
                 if (!beginRect())
                     return false;
                 inRect = true;
                 color = *ptr;
                 setColor(color);
                 setX(numRects, x);
                 setY(numRects, y);
             }
             ++ptr;
         }
         if (inRect) { // end rect
             setWidth(numRects, width - rectx(numRects));
             endRect();
             inRect = false;
         }
         ptr += linestep;
     }
     return true;
 }
read() [2/2]
template<class SRC> bool QRfbMultiColorHextile< SRC >::read (const uchar * data, int width, int height, int stride)
rect() [1/4]
template<class SRC> quint8* QRfbMultiColorHextile< SRC >::rect (int r) inline private
Definition at line 357 of file qscreenvnc_p.h.
{
         return rects.data() + r * (bpp + 2);
     }
rect() [2/4]
template<class SRC> const quint8* QRfbMultiColorHextile< SRC >::rect (int r) const inline private
Definition at line 360 of file qscreenvnc_p.h.
{
         return rects.constData() + r * (bpp + 2);
     }
rect() [3/4]
template<class SRC> quint8* QRfbMultiColorHextile< SRC >::rect (int r) inline private
Definition at line 363 of file qvncserver.h.
{
         return rects.data() + r * (bpp + 2);
     }
rect() [4/4]
template<class SRC> const quint8* QRfbMultiColorHextile< SRC >::rect (int r) const inline private
Definition at line 366 of file qvncserver.h.
{
         return rects.constData() + r * (bpp + 2);
     }
rectx() [1/2]
template<class SRC> int QRfbMultiColorHextile< SRC >::rectx (int r) const inline private
Definition at line 372 of file qscreenvnc_p.h.
{
         const quint8 *ptr = rect(r) + bpp;
         return *ptr >> 4;
     }
rectx() [2/2]
template<class SRC> int QRfbMultiColorHextile< SRC >::rectx (int r) const inline private
Definition at line 378 of file qvncserver.h.
{
         const quint8 *ptr = rect(r) + bpp;
         return *ptr >> 4;
     }
recty() [1/2]
template<class SRC> int QRfbMultiColorHextile< SRC >::recty (int r) const inline private
Definition at line 376 of file qscreenvnc_p.h.
{
         const quint8 *ptr = rect(r) + bpp;
         return *ptr & 0x0f;
     }
recty() [2/2]
template<class SRC> int QRfbMultiColorHextile< SRC >::recty (int r) const inline private
Definition at line 382 of file qvncserver.h.
{
         const quint8 *ptr = rect(r) + bpp;
         return *ptr & 0x0f;
     }
setColor() [1/2]
template<class SRC > void QRfbMultiColorHextile< SRC >::setColor (SRC color) inline private
Definition at line 1293 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     encoder->server->convertPixels(reinterpret_cast<char*>(rect(numRects)),
                                    (const char*)&color, 1);
 }
setColor() [2/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setColor (SRC color) private
setHeight() [1/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setHeight (int r, int height) inline private
Definition at line 384 of file qscreenvnc_p.h.
{
         quint8 *ptr = rect(r) + bpp + 1;
         *ptr = (*ptr & 0xf0) | (height - 1);
     }
setHeight() [2/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setHeight (int r, int height) inline private
Definition at line 390 of file qvncserver.h.
{
         quint8 *ptr = rect(r) + bpp + 1;
         *ptr = (*ptr & 0xf0) | (height - 1);
     }
setWidth() [1/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setWidth (int r, int width) inline private
Definition at line 380 of file qscreenvnc_p.h.
{
         quint8 *ptr = rect(r) + bpp + 1;
         *ptr = ((width - 1) << 4) | (*ptr & 0x0f);
     }
setWidth() [2/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setWidth (int r, int width) inline private
Definition at line 386 of file qvncserver.h.
{
         quint8 *ptr = rect(r) + bpp + 1;
         *ptr = ((width - 1) << 4) | (*ptr & 0x0f);
     }
setX() [1/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setX (int r, int x) inline private
Definition at line 363 of file qscreenvnc_p.h.
{
         quint8 *ptr = rect(r) + bpp;
         *ptr = (x << 4) | (*ptr & 0x0f);
     }
setX() [2/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setX (int r, int x) inline private
Definition at line 369 of file qvncserver.h.
{
         quint8 *ptr = rect(r) + bpp;
         *ptr = (x << 4) | (*ptr & 0x0f);
     }
setY() [1/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setY (int r, int y) inline private
Definition at line 367 of file qscreenvnc_p.h.
{
         quint8 *ptr = rect(r) + bpp;
         *ptr = (*ptr & 0xf0) | y;
     }
setY() [2/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::setY (int r, int y) inline private
Definition at line 373 of file qvncserver.h.
{
         quint8 *ptr = rect(r) + bpp;
         *ptr = (*ptr & 0xf0) | y;
     }
write() [1/2]
template<class SRC > void QRfbMultiColorHextile< SRC >::write (QTcpSocket * socket) const
Definition at line 1365 of file qscreenvnc_qws.cpp.
Referenced by buttonChange().
 {
     const int padding = 3;
     QVarLengthArray<quint8> buffer(bpp + padding + sizeof(quint8) + sizeof(numRects));
     quint8 &subenc = buffer[padding];
     int n = padding + sizeof(quint8);
     subenc = 8 | 16; // AnySubrects | SubrectsColoured
     if (encoder->newBg) {
         subenc |= 0x2; // Background
         encoder->server->convertPixels(reinterpret_cast<char*>(buffer.data() + n),
                                        reinterpret_cast<const char*>(&encoder->bg),
                                        1);
         n += bpp;
 //        encoder->newBg = false;
     }
     buffer[n] = numRects;
     n += sizeof(numRects);
     socket->write(reinterpret_cast<const char*>(buffer.data() + padding),
                   n - padding);
     socket->write(reinterpret_cast<const char*>(rects.constData()),
                   rects.size());
 }
write() [2/2]
template<class SRC> void QRfbMultiColorHextile< SRC >::write (QTcpSocket * socket) const
Properties
bpp
template<class SRC> quint8 QRfbMultiColorHextile< SRC >::bpp private
Definition at line 395 of file qscreenvnc_p.h.
encoder
template<class SRC> QRfbHextileEncoder< SRC > * QRfbMultiColorHextile< SRC >::encoder private
Definition at line 397 of file qscreenvnc_p.h.
maxRectsSize
template<class SRC> static const int QRfbMultiColorHextile< SRC >::maxRectsSize = 16 * 16 static private
Definition at line 392 of file qscreenvnc_p.h.
numRects
template<class SRC> quint8 QRfbMultiColorHextile< SRC >::numRects private
Definition at line 396 of file qscreenvnc_p.h.
rects
template<class SRC> QVarLengthArray< quint8, maxRectsSize > QRfbMultiColorHextile< SRC >::rects private
Definition at line 393 of file qscreenvnc_p.h.
The documentation for this class was generated from the following files:
/src/plugins/gfxdrivers/vnc/qscreenvnc_p.h
/src/plugins/platforms/vnc/qvncserver.h
/src/plugins/gfxdrivers/vnc/qscreenvnc_qws.cpp
/src/plugins/platforms/vnc/qvncserver.cpp