Qt 4.8: QFSFileEngine Class Reference
QFSFileEngine Class Reference
The QFSFileEngine class implements Qt's default file engine.
#include <qfsfileengine.h>
Public Functions
Iterator * beginEntryList (QDir::Filters filters, const QStringList &filterNames)
bool caseSensitive () const
Returns true for Windows, false for Unix.
bool close ()
Reimplemented Function
bool copy (const QString &newName)
For windows, copy the file to file copyName.
Iterator * endEntryList ()
QStringList entryList (QDir::Filters filters, const QStringList &filterNames) const
bool extension (Extension extension, const ExtensionOption *option=0, ExtensionReturn *output=0)
Reimplemented Function
FileFlags fileFlags (FileFlags type) const
Reimplemented Function
QString fileName (FileName file) const
Reimplemented Function
QDateTime fileTime (FileTime time) const
Reimplemented Function
bool flush ()
Reimplemented Function
int handle () const
Reimplemented Function
bool isRelativePath () const
Reimplemented Function
bool isSequential () const
Reimplemented Function
bool link (const QString &newName)
Creates a link from the file currently specified by fileName() to newName.
bool mkdir (const QString &dirName, bool createParentDirectories) const
Reimplemented Function
bool open (QIODevice::OpenMode openMode)
Reimplemented Function
bool open (QIODevice::OpenMode flags, FILE *fh)
Opens the file handle fh in openMode mode.
bool open (QIODevice::OpenMode flags, int fd)
Opens the file descriptor fd in openMode mode.
bool open (QIODevice::OpenMode flags, int fd, QFile::FileHandleFlags handleFlags)
Opens the file descriptor fd in openMode mode.
bool open (QIODevice::OpenMode flags, FILE *fh, QFile::FileHandleFlags handleFlags)
Opens the file handle fh in openMode mode.
QString owner (FileOwner) const
Reimplemented Function
uint ownerId (FileOwner) const
In Unix, if stat() is successful, the uid is returned if own is the owner.
qint64 pos () const
Reimplemented Function
QFSFileEngine ()
Constructs a QFSFileEngine.
QFSFileEngine (const QString &file)
Constructs a QFSFileEngine for the file name file.
qint64 read (char *data, qint64 maxlen)
Reimplemented Function
qint64 readLine (char *data, qint64 maxlen)
Reimplemented Function
bool remove ()
Reimplemented Function
bool rename (const QString &newName)
Reimplemented Function
bool rmdir (const QString &dirName, bool recurseParentDirectories) const
Reimplemented Function
bool seek (qint64)
Reimplemented Function
void setFileName (const QString &file)
Reimplemented Function
bool setPermissions (uint perms)
Reimplemented Function
bool setSize (qint64 size)
Reimplemented Function
qint64 size () const
Reimplemented Function
bool supportsExtension (Extension extension) const
Reimplemented Function
qint64 write (const char *data, qint64 len)
Reimplemented Function
~QFSFileEngine ()
Destructs the QFSFileEngine.
Public Functions inherited from QAbstractFileEngine
bool atEnd () const
Returns true if the current position is at the end of the file; otherwise, returns false.
QFile::FileError error () const
Returns the QFile::FileError that resulted from the last failed operation.
QString errorString () const
Returns the human-readable message appropriate to the current error reported by error().
uchar * map (qint64 offset, qint64 size, QFile::MemoryMapFlags flags)
Maps size bytes of the file into memory starting at offset.
bool unmap (uchar *ptr)
Unmaps the memory address.
virtual ~QAbstractFileEngine ()
Destroys the QAbstractFileEngine.
Static Public Functions
static QString currentPath (const QString &path=QString())
For Unix, returns the current working directory for the file engine.
static QFileInfoList drives ()
For Windows, returns the list of drives in the file system as a list of QFileInfo objects.
static QString homePath ()
Returns the home path of the current user.
static QString rootPath ()
Returns the root path.
static bool setCurrentPath (const QString &path)
Sets the current path (e.
static QString tempPath ()
Returns the temporary path (i.
Static Public Functions inherited from QAbstractFileEngine
static QAbstractFileEngine * create (const QString &fileName)
Creates and returns a QAbstractFileEngine suitable for processing fileName.
Protected Functions
QFSFileEngine (QFSFileEnginePrivate &dd)
Protected Functions inherited from QAbstractFileEngine
QAbstractFileEngine ()
Constructs a new QAbstractFileEngine that does not refer to any file or directory.
QAbstractFileEngine (QAbstractFileEnginePrivate &)
Constructs a QAbstractFileEngine.
void setError (QFile::FileError error, const QString &str)
Sets the error type to error, and the error string to errorString.
Additional Inherited Members
Public Types inherited from QAbstractFileEngine
enum Extension { AtEndExtension, FastReadLineExtension, MapExtension, UnMapExtension }
This enum describes the types of extensions that the file engine can support.
enum FileFlag {
ReadOwnerPerm = 0x4000, WriteOwnerPerm = 0x2000, ExeOwnerPerm = 0x1000, ReadUserPerm = 0x0400,
WriteUserPerm = 0x0200, ExeUserPerm = 0x0100, ReadGroupPerm = 0x0040, WriteGroupPerm = 0x0020,
ExeGroupPerm = 0x0010, ReadOtherPerm = 0x0004, WriteOtherPerm = 0x0002, ExeOtherPerm = 0x0001,
LinkType = 0x10000, FileType = 0x20000, DirectoryType = 0x40000, BundleType = 0x80000,
HiddenFlag = 0x0100000, LocalDiskFlag = 0x0200000, ExistsFlag = 0x0400000, RootFlag = 0x0800000,
Refresh = 0x1000000, PermsMask = 0x0000FFFF, TypesMask = 0x000F0000, FlagsMask = 0x0FF00000,
FileInfoAll = FlagsMask | PermsMask | TypesMask
}
The permissions and types of a file, suitable for OR'ing together.
enum FileName {
DefaultName, BaseName, PathName, AbsoluteName,
AbsolutePathName, LinkName, CanonicalName, CanonicalPathName,
BundleName, NFileNames = 9
}
These values are used to request a file name in a particular format.
enum FileOwner { OwnerUser, OwnerGroup }
enum FileTime { CreationTime, ModificationTime, AccessTime }
These are used by the fileTime() function.
typedef QAbstractFileEngineIterator Iterator
Protected Variables inherited from QAbstractFileEngine
QScopedPointer< QAbstractFileEnginePrivate > d_ptr
Related Functions inherited from QAbstractFileEngine
Iterator
Synonym for QAbstractFileEngineIterator.
Detailed Description
The QFSFileEngine class implements Qt's default file engine.
Since
4.1
This class is part of the file engine framework in Qt. If you only want to access files or directories, use QFile, QFileInfo or QDir instead.
QFSFileEngine is the default file engine for accessing regular files. It is provided for convenience; by subclassing this class, you can alter its behavior slightly, without having to write a complete QAbstractFileEngine subclass. To install your custom file engine, you must also subclass QAbstractFileEngineHandler and create an instance of your handler.
It can also be useful to create a QFSFileEngine object directly if you need to use the local file system inside QAbstractFileEngine::create(), in order to avoid recursion (as higher-level classes tend to call QAbstractFileEngine::create()).
Definition at line 60 of file qfsfileengine.h.
Constructors and Destructors
QFSFileEngine() [1/3]
QFSFileEngine::QFSFileEngine ()
Constructs a QFSFileEngine.
Definition at line 158 of file qfsfileengine.cpp.
                              : QAbstractFileEngine(*new QFSFileEnginePrivate)
 {
 }
QFSFileEngine() [2/3]
QFSFileEngine::QFSFileEngine (const QString & file) explicit
Constructs a QFSFileEngine for the file name file.
Definition at line 148 of file qfsfileengine.cpp.
     : QAbstractFileEngine(*new QFSFileEnginePrivate)
 {
     Q_D(QFSFileEngine);
     d->fileEntry = QFileSystemEntry(file);
 }
~QFSFileEngine()
QFSFileEngine::~QFSFileEngine ()
Destructs the QFSFileEngine.
Definition at line 173 of file qfsfileengine.cpp.
 {
     Q_D(QFSFileEngine);
     if (d->closeFileHandle) {
         if (d->fh) {
             int ret;
             do {
                 ret = fclose(d->fh);
             } while (ret == EOF && errno == EINTR);
         } else if (d->fd != -1) {
             int ret;
             do {
                 ret = QT_CLOSE(d->fd);
             } while (ret == -1 && errno == EINTR);
         }
     }
     QList<uchar*> keys = d->maps.keys();
     for (int i = 0; i < keys.count(); ++i)
         unmap(keys.at(i));
 }
QFSFileEngine() [3/3]
QFSFileEngine::QFSFileEngine (QFSFileEnginePrivate & dd) protected
Warning
This function is not part of the public interface.
Definition at line 165 of file qfsfileengine.cpp.
     : QAbstractFileEngine(dd)
 {
 }
Functions
beginEntryList()
QAbstractFileEngine::Iterator * QFSFileEngine::beginEntryList (QDir::Filters filters, const QStringList & filterNames) virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractFileEngine.
Definition at line 787 of file qfsfileengine.cpp.
 {
     return new QFSFileEngineIterator(filters, filterNames);
 }
caseSensitive()
bool QFSFileEngine::caseSensitive () const virtual
Returns true for Windows, false for Unix.
Reimplemented from QAbstractFileEngine.
Definition at line 725 of file qfsfileengine_unix.cpp.
Referenced by QExtendedInformation::isCaseSensitive(), and QFSFileEnginePrivate::longFileName().
 {
 #if defined(Q_OS_SYMBIAN)
     return false;
 #else
     return true;
 #endif
 }
close()
bool QFSFileEngine::close () virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Reimplemented in QTemporaryFileEngine.
Definition at line 377 of file qfsfileengine.cpp.
Referenced by QTemporaryFileEngine::remove(), QTemporaryFileEngine::rename(), QTemporaryFileEngine::setFileName(), and QTemporaryFileEngine::~QTemporaryFileEngine().
 {
     Q_D(QFSFileEngine);
     d->openMode = QIODevice::NotOpen;
     return d->nativeClose();
 }
copy()
bool QFSFileEngine::copy (const QString & copyName) virtual
For windows, copy the file to file copyName.
Not implemented for Unix.
Reimplemented from QAbstractFileEngine.
Definition at line 659 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(QFSFileEngine);
     QSystemError error;
     bool ret = QFileSystemEngine::copyFile(d->fileEntry, QFileSystemEntry(newName), error);
     if (!ret) {
         setError(QFile::CopyError, error.toString());
     }
     return ret;
 }
currentPath()
QString QFSFileEngine::currentPath (const QString & fileName = QString()) static
For Unix, returns the current working directory for the file engine.
For Windows, returns the canonicalized form of the current path used by the file engine for the drive specified by fileName. On Windows, each drive has its own current directory, so a different path is returned for file names that include different drive names (e.g. A: or C:).
See also
setCurrentPath()
Definition at line 739 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     return QFileSystemEngine::currentPath().filePath();
 }
drives()
QFileInfoList QFSFileEngine::drives () static
For Windows, returns the list of drives in the file system as a list of QFileInfo objects.
On unix, Mac OS X and Windows CE, only the root path is returned. On Windows, this function returns all drives (A:\, C:\, D:\, etc.).
For Unix, the list contains just the root path "/".
Definition at line 759 of file qfsfileengine_unix.cpp.
Referenced by QDir::drives(), and QFSFileEnginePrivate::longFileName().
 {
     QFileInfoList ret;
 #if defined(Q_OS_SYMBIAN)
     TDriveList driveList;
     RFs rfs = qt_s60GetRFs();
     TInt err = rfs.DriveList(driveList);
     if (err == KErrNone) {
         char driveName[] = "A:/";
         for (char i = 0; i < KMaxDrives; i++) {
             if (driveList[i]) {
                 driveName[0] = 'A' + i;
                 ret.append(QFileInfo(QLatin1String(driveName)));
             }
         }
     } else {
         qWarning("QFSFileEngine::drives: Getting drives failed");
     }
 #else
     ret.append(QFileInfo(rootPath()));
 #endif
     return ret;
 }
endEntryList()
QAbstractFileEngine::Iterator * QFSFileEngine::endEntryList () virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractFileEngine.
Definition at line 795 of file qfsfileengine.cpp.
 {
     return 0;
 }
entryList()
QStringList QFSFileEngine::entryList (QDir::Filters filters, const QStringList & filterNames) const virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractFileEngine.
Definition at line 804 of file qfsfileengine.cpp.
 {
     return QAbstractFileEngine::entryList(filters, filterNames);
 }
extension()
bool QFSFileEngine::extension (Extension extension, const ExtensionOption * option = 0, ExtensionReturn * output = 0) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 835 of file qfsfileengine.cpp.
 {
     Q_D(QFSFileEngine);
     if (extension == AtEndExtension && d->fh && isSequential())
         return feof(d->fh);
     if (extension == MapExtension) {
         const MapExtensionOption *options = (MapExtensionOption*)(option);
         MapExtensionReturn *returnValue = static_cast<MapExtensionReturn*>(output);
         returnValue->address = d->map(options->offset, options->size, options->flags);
         return (returnValue->address != 0);
     }
     if (extension == UnMapExtension) {
         UnMapExtensionOption *options = (UnMapExtensionOption*)option;
         return d->unmap(options->address);
     }
     return false;
 }
fileFlags()
QAbstractFileEngine::FileFlags QFSFileEngine::fileFlags (FileFlags type) const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 813 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(const QFSFileEngine);
     if (type & Refresh)
         d->metaData.clear();
     QAbstractFileEngine::FileFlags ret = 0;
     if (type & FlagsMask)
         ret |= LocalDiskFlag;
     bool exists;
     {
         QFileSystemMetaData::MetaDataFlags queryFlags = 0;
         queryFlags |= QFileSystemMetaData::MetaDataFlags(uint(type))
                 & QFileSystemMetaData::Permissions;
         if (type & TypesMask)
             queryFlags |= QFileSystemMetaData::AliasType
                     | QFileSystemMetaData::LinkType
                     | QFileSystemMetaData::FileType
                     | QFileSystemMetaData::DirectoryType
                     | QFileSystemMetaData::BundleType;
         if (type & FlagsMask)
             queryFlags |= QFileSystemMetaData::HiddenAttribute
                     | QFileSystemMetaData::ExistsAttribute;
         queryFlags |= QFileSystemMetaData::LinkType;
         exists = d->doStat(queryFlags);
     }
     if (!exists && !d->metaData.isLink())
         return ret;
     if (exists && (type & PermsMask))
         ret |= FileFlags(uint(d->metaData.permissions()));
     if (type & TypesMask) {
         if (d->metaData.isAlias()) {
             ret |= LinkType;
         } else {
             if ((type & LinkType) && d->metaData.isLink())
                 ret |= LinkType;
             if (exists) {
                 if (d->metaData.isFile()) {
                     ret |= FileType;
                 } else if (d->metaData.isDirectory()) {
                     ret |= DirectoryType;
                     if ((type & BundleType) && d->metaData.isBundle())
                         ret |= BundleType;
                 }
             }
         }
     }
     if (type & FlagsMask) {
         if (exists)
             ret |= ExistsFlag;
         if (d->fileEntry.isRoot())
             ret |= RootFlag;
         else if (d->metaData.isHidden())
             ret |= HiddenFlag;
     }
     return ret;
 }
fileName()
QString QFSFileEngine::fileName (FileName file) const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 884 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(const QFSFileEngine);
     if (file == BundleName) {
         return QFileSystemEngine::bundleName(d->fileEntry);
     } else if (file == BaseName) {
         return d->fileEntry.fileName();
     } else if (file == PathName) {
         return d->fileEntry.path();
     } else if (file == AbsoluteName || file == AbsolutePathName) {
         QFileSystemEntry entry(QFileSystemEngine::absoluteName(d->fileEntry));
         if (file == AbsolutePathName) {
             return entry.path();
         }
         return entry.filePath();
     } else if (file == CanonicalName || file == CanonicalPathName) {
         QFileSystemEntry entry(QFileSystemEngine::canonicalName(d->fileEntry, d->metaData));
         if (file == CanonicalPathName)
             return entry.path();
         return entry.filePath();
     } else if (file == LinkName) {
         if (d->isSymlink()) {
             QFileSystemEntry entry = QFileSystemEngine::getLinkTarget(d->fileEntry, d->metaData);
             return entry.filePath();
         }
         return QString();
     }
     return d->fileEntry.filePath();
 }
fileTime()
QDateTime QFSFileEngine::fileTime (FileTime time) const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 1012 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(const QFSFileEngine);
     if (d->doStat(QFileSystemMetaData::Times))
         return d->metaData.fileTime(time);
     return QDateTime();
 }
flush()
bool QFSFileEngine::flush () virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 454 of file qfsfileengine.cpp.
Referenced by QFSFileEnginePrivate::longFileName(), read(), readLine(), size(), and write().
 {
     Q_D(QFSFileEngine);
     if ((d->openMode & QIODevice::WriteOnly) == 0) {
         // Nothing in the write buffers, so flush succeeds in doing
         // nothing.
         return true;
     }
     return d->nativeFlush();
 }
handle()
int QFSFileEngine::handle () const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 585 of file qfsfileengine.cpp.
 {
     Q_D(const QFSFileEngine);
     return d->nativeHandle();
 }
homePath()
QString QFSFileEngine::homePath () static
Returns the home path of the current user.
See also
rootPath()
Definition at line 744 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     return QFileSystemEngine::homePath();
 }
isRelativePath()
bool QFSFileEngine::isRelativePath () const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 914 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(const QFSFileEngine);
 #if defined(Q_OS_SYMBIAN)
     return isRelativePathSymbian(d->fileEntry.filePath());
 #else
     return d->fileEntry.filePath().length() ? d->fileEntry.filePath()[0] != QLatin1Char('/') : true;
 #endif
 }
isSequential()
bool QFSFileEngine::isSequential () const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 812 of file qfsfileengine.cpp.
Referenced by extension(), and supportsExtension().
 {
     Q_D(const QFSFileEngine);
     if (d->is_sequential == 0)
         d->is_sequential = d->nativeIsSequential() ? 1 : 2;
     return d->is_sequential == 1;
 }
link()
bool QFSFileEngine::link (const QString & newName) virtual
Creates a link from the file currently specified by fileName() to newName.
What a link is depends on the underlying filesystem (be it a shortcut on Windows or a symbolic link on Unix). Returns true if successful; otherwise returns false.
Reimplemented from QAbstractFileEngine.
Definition at line 683 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(QFSFileEngine);
     QSystemError error;
     bool ret = QFileSystemEngine::createLink(d->fileEntry, QFileSystemEntry(newName), error);
     if (!ret) {
         setError(QFile::RenameError, error.toString());
     }
     return ret;
 }
mkdir()
bool QFSFileEngine::mkdir (const QString & dirName, bool createParentDirectories) const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 715 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     return QFileSystemEngine::createDirectory(QFileSystemEntry(name), createParentDirectories);
 }
open() [1/5]
bool QFSFileEngine::open (QIODevice::OpenMode openMode) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Reimplemented in QTemporaryFileEngine.
Definition at line 207 of file qfsfileengine.cpp.
Referenced by open(), QTemporaryFileEngine::open(), QFilePrivate::openExternalFile(), and setCloseOnExec().
 {
     Q_D(QFSFileEngine);
     if (d->fileEntry.isEmpty()) {
         qWarning("QFSFileEngine::open: No file name specified");
         setError(QFile::OpenError, QLatin1String("No file name specified"));
         return false;
     }
     // Append implies WriteOnly.
     if (openMode & QFile::Append)
         openMode |= QFile::WriteOnly;
     // WriteOnly implies Truncate if neither ReadOnly nor Append are sent.
     if ((openMode & QFile::WriteOnly) && !(openMode & (QFile::ReadOnly | QFile::Append)))
         openMode |= QFile::Truncate;
     d->openMode = openMode;
     d->lastFlushFailed = false;
     d->tried_stat = 0;
     d->fh = 0;
     d->fd = -1;
     return d->nativeOpen(openMode);
 }
open() [2/5]
bool QFSFileEngine::open (QIODevice::OpenMode openMode, FILE * fh)
Opens the file handle fh in openMode mode.
Returns true on success; otherwise returns false.
Definition at line 237 of file qfsfileengine.cpp.
 {
     return open(openMode, fh, QFile::DontCloseHandle);
 }
open() [3/5]
bool QFSFileEngine::open (QIODevice::OpenMode openMode, int fd)
Opens the file descriptor fd in openMode mode.
Returns true on success; otherwise returns false.
Definition at line 306 of file qfsfileengine.cpp.
 {
     return open(openMode, fd, QFile::DontCloseHandle);
 }
open() [4/5]
bool QFSFileEngine::open (QIODevice::OpenMode openMode, int fd, QFile::FileHandleFlags handleFlags)
Opens the file descriptor fd in openMode mode.
Returns true on success; otherwise returns false.
The handleFlags argument specifies whether the file handle will be closed by Qt. See the QFile::FileHandleFlags documentation for more information.
Definition at line 319 of file qfsfileengine.cpp.
 {
     Q_D(QFSFileEngine);
     // Append implies WriteOnly.
     if (openMode & QFile::Append)
         openMode |= QFile::WriteOnly;
     // WriteOnly implies Truncate if neither ReadOnly nor Append are sent.
     if ((openMode & QFile::WriteOnly) && !(openMode & (QFile::ReadOnly | QFile::Append)))
         openMode |= QFile::Truncate;
     d->openMode = openMode;
     d->lastFlushFailed = false;
     d->closeFileHandle = (handleFlags & QFile::AutoCloseHandle);
     d->fileEntry.clear();
     d->fh = 0;
     d->fd = -1;
     d->tried_stat = 0;
     return d->openFd(openMode, fd);
 }
open() [5/5]
bool QFSFileEngine::open (QIODevice::OpenMode openMode, FILE * fh, QFile::FileHandleFlags handleFlags)
Opens the file handle fh in openMode mode.
Returns true on success; otherwise returns false.
The handleFlags argument specifies whether the file handle will be closed by Qt. See the QFile::FileHandleFlags documentation for more information.
Definition at line 250 of file qfsfileengine.cpp.
 {
     Q_D(QFSFileEngine);
     // Append implies WriteOnly.
     if (openMode & QFile::Append)
         openMode |= QFile::WriteOnly;
     // WriteOnly implies Truncate if neither ReadOnly nor Append are sent.
     if ((openMode & QFile::WriteOnly) && !(openMode & (QFile::ReadOnly | QFile::Append)))
         openMode |= QFile::Truncate;
     d->openMode = openMode;
     d->lastFlushFailed = false;
     d->closeFileHandle = (handleFlags & QFile::AutoCloseHandle);
     d->fileEntry.clear();
     d->tried_stat = 0;
     d->fd = -1;
     return d->openFh(openMode, fh);
 }
owner()
QString QFSFileEngine::owner (FileOwner own) const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 935 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
 #ifndef Q_OS_SYMBIAN
     if (own == OwnerUser)
         return QFileSystemEngine::resolveUserName(ownerId(own));
     return QFileSystemEngine::resolveGroupName(ownerId(own));
 #else
     Q_UNUSED(own)
     return QString();
 #endif
 }
ownerId()
uint QFSFileEngine::ownerId (FileOwner own) const virtual
In Unix, if stat() is successful, the uid is returned if own is the owner.
Otherwise the gid is returned. If stat() is unsuccessful, -2 is reuturned.
For Windows, -2 is always returned.
Reimplemented from QAbstractFileEngine.
Definition at line 924 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(const QFSFileEngine);
     static const uint nobodyID = (uint) -2;
     if (d->doStat(QFileSystemMetaData::OwnerIds))
         return d->metaData.ownerId(own);
     return nobodyID;
 }
pos()
qint64 QFSFileEngine::pos () const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 519 of file qfsfileengine.cpp.
Referenced by QFSFileEnginePrivate::seekFdFh().
 {
     Q_D(const QFSFileEngine);
     return d->nativePos();
 }
read()
qint64 QFSFileEngine::read (char * data, qint64 maxlen) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 594 of file qfsfileengine.cpp.
 {
     Q_D(QFSFileEngine);
     // On Windows' stdlib implementation, the results of calling fread and
     // fwrite are undefined if not called either in sequence, or if preceded
     // with a call to fflush().
     if (d->lastIOCommand != QFSFileEnginePrivate::IOReadCommand) {
         flush();
         d->lastIOCommand = QFSFileEnginePrivate::IOReadCommand;
     }
     return d->nativeRead(data, maxlen);
 }
readLine()
qint64 QFSFileEngine::readLine (char * data, qint64 maxlen) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 670 of file qfsfileengine.cpp.
 {
     Q_D(QFSFileEngine);
     // On Windows' stdlib implementation, the results of calling fread and
     // fwrite are undefined if not called either in sequence, or if preceded
     // with a call to fflush().
     if (d->lastIOCommand != QFSFileEnginePrivate::IOReadCommand) {
         flush();
         d->lastIOCommand = QFSFileEnginePrivate::IOReadCommand;
     }
     return d->nativeReadLine(data, maxlen);
 }
remove()
bool QFSFileEngine::remove () virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Reimplemented in QTemporaryFileEngine.
Definition at line 647 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName(), and QTemporaryFileEngine::remove().
 {
     Q_D(QFSFileEngine);
     QSystemError error;
     bool ret = QFileSystemEngine::removeFile(d->fileEntry, error);
     d->metaData.clear();
     if (!ret) {
         setError(QFile::RemoveError, error.toString());
     }
     return ret;
 }
rename()
bool QFSFileEngine::rename (const QString & newName) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Reimplemented in QTemporaryFileEngine.
Definition at line 670 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName(), and QTemporaryFileEngine::rename().
 {
     Q_D(QFSFileEngine);
     QSystemError error;
     bool ret = QFileSystemEngine::renameFile(d->fileEntry, QFileSystemEntry(newName), error);
     if (!ret) {
         setError(QFile::RenameError, error.toString());
     }
     return ret;
 }
rmdir()
bool QFSFileEngine::rmdir (const QString & dirName, bool recurseParentDirectories) const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 720 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     return QFileSystemEngine::removeDirectory(QFileSystemEntry(name), recurseParentDirectories);
 }
rootPath()
QString QFSFileEngine::rootPath () static
Returns the root path.
See also
homePath()
Definition at line 749 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     return QFileSystemEngine::rootPath();
 }
seek()
bool QFSFileEngine::seek (qint64 pos) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 538 of file qfsfileengine.cpp.
Referenced by QTemporaryFileEngine::close().
 {
     Q_D(QFSFileEngine);
     return d->nativeSeek(pos);
 }
setCurrentPath()
bool QFSFileEngine::setCurrentPath (const QString & path) static
Sets the current path (e.
g., for QDir), to path. Returns true if the new path exists; otherwise this function does nothing, and returns false.
See also
currentPath()
Definition at line 734 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     return QFileSystemEngine::setCurrentPath(QFileSystemEntry(path));
 }
setFileName()
void QFSFileEngine::setFileName (const QString & file) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Reimplemented in QTemporaryFileEngine.
Definition at line 197 of file qfsfileengine.cpp.
Referenced by QTemporaryFileEngine::QTemporaryFileEngine(), and QTemporaryFileEngine::setFileName().
 {
     Q_D(QFSFileEngine);
     d->init();
     d->fileEntry = QFileSystemEntry(file);
 }
setPermissions()
bool QFSFileEngine::setPermissions (uint perms) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 947 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     Q_D(QFSFileEngine);
     QSystemError error;
     if (!QFileSystemEngine::setPermissions(d->fileEntry, QFile::Permissions(perms), error, 0)) {
         setError(QFile::PermissionsError, error.toString());
         return false;
     }
     return true;
 }
setSize()
bool QFSFileEngine::setSize (qint64 size) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 996 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName(), and setPermissions().
 {
     Q_D(QFSFileEngine);
     bool ret = false;
     if (d->fd != -1)
         ret = QT_FTRUNCATE(d->fd, size) == 0;
     else if (d->fh)
         ret = QT_FTRUNCATE(QT_FILENO(d->fh), size) == 0;
     else
         ret = QT_TRUNCATE(d->fileEntry.nativeFilePath().constData(), size) == 0;
     if (!ret)
         setError(QFile::ResizeError, qt_error_string(errno));
     return ret;
 }
size()
qint64 QFSFileEngine::size () const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 493 of file qfsfileengine.cpp.
 {
     Q_D(const QFSFileEngine);
     return d->nativeSize();
 }
supportsExtension()
bool QFSFileEngine::supportsExtension (Extension extension) const virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 858 of file qfsfileengine.cpp.
 {
     Q_D(const QFSFileEngine);
     if (extension == AtEndExtension && d->fh && isSequential())
         return true;
     if (extension == FastReadLineExtension && d->fh)
         return true;
     if (extension == FastReadLineExtension && d->fd != -1 && isSequential())
         return true;
     if (extension == UnMapExtension || extension == MapExtension)
         return true;
     return false;
 }
tempPath()
QString QFSFileEngine::tempPath () static
Returns the temporary path (i.
e., a path in which it is safe to store temporary files).
Definition at line 754 of file qfsfileengine_unix.cpp.
Referenced by QFSFileEnginePrivate::longFileName().
 {
     return QFileSystemEngine::tempPath();
 }
write()
qint64 QFSFileEngine::write (const char * data, qint64 len) virtual
Reimplemented Function
Reimplemented from QAbstractFileEngine.
Definition at line 723 of file qfsfileengine.cpp.
 {
     Q_D(QFSFileEngine);
     // On Windows' stdlib implementation, the results of calling fread and
     // fwrite are undefined if not called either in sequence, or if preceded
     // with a call to fflush().
     if (d->lastIOCommand != QFSFileEnginePrivate::IOWriteCommand) {
         flush();
         d->lastIOCommand = QFSFileEnginePrivate::IOWriteCommand;
     }
     return d->nativeWrite(data, len);
 }
The documentation for this class was generated from the following files:
/src/corelib/io/qfsfileengine.h
/src/corelib/io/qfsfileengine.cpp
/src/corelib/io/qfsfileengine_unix.cpp
/src/corelib/io/qfsfileengine_win.cpp