Qt 4.8: QDeclarativeFlickable Class Reference
QDeclarativeFlickable Class Reference
#include <qdeclarativeflickable_p.h>
Public Types
enum BoundsBehavior { StopAtBounds, DragOverBounds, DragAndOvershootBounds }
enum FlickableDirection { AutoFlickDirection =0x00, HorizontalFlick =0x01, VerticalFlick =0x02, HorizontalAndVerticalFlick =0x03 }
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Signals
void boundsBehaviorChanged ()
void contentHeightChanged ()
void contentWidthChanged ()
void contentXChanged ()
void contentYChanged ()
void flickableDirectionChanged ()
void flickDecelerationChanged ()
void flickEnded ()
void flickingChanged ()
void flickingHorizontallyChanged ()
void flickingVerticallyChanged ()
void flickStarted ()
void horizontalVelocityChanged ()
void interactiveChanged ()
void isAtBoundaryChanged ()
void maximumFlickVelocityChanged ()
void movementEnded ()
void movementStarted ()
void movingChanged ()
void movingHorizontallyChanged ()
void movingVerticallyChanged ()
void pressDelayChanged ()
void verticalVelocityChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
BoundsBehavior boundsBehavior () const
qreal contentHeight () const
QDeclarativeItem * contentItem ()
qreal contentWidth () const
qreal contentX () const
qreal contentY () const
QDeclarativeListProperty< QGraphicsObject > flickableChildren ()
QDeclarativeListProperty< QObject > flickableData ()
FlickableDirection flickableDirection () const
qreal flickDeceleration () const
qreal horizontalVelocity () const
bool isAtXBeginning () const
bool isAtXEnd () const
bool isAtYBeginning () const
bool isAtYEnd () const
bool isFlicking () const
bool isFlickingHorizontally () const
bool isFlickingVertically () const
bool isInteractive () const
bool isMoving () const
bool isMovingHorizontally () const
bool isMovingVertically () const
qreal maximumFlickVelocity () const
int pressDelay () const
QDeclarativeFlickable (QDeclarativeItem *parent=0)
Q_INVOKABLE void resizeContent (qreal w, qreal h, QPointF center)
Q_INVOKABLE void returnToBounds ()
void setBoundsBehavior (BoundsBehavior)
void setContentHeight (qreal)
void setContentWidth (qreal)
virtual void setContentX (qreal pos)
virtual void setContentY (qreal pos)
void setFlickableDirection (FlickableDirection)
void setFlickDeceleration (qreal)
void setInteractive (bool)
void setMaximumFlickVelocity (qreal)
void setPressDelay (int delay)
qreal verticalVelocity () const
~QDeclarativeFlickable ()
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
virtual void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Slots
void movementEnding ()
void movementStarting ()
virtual void ticked ()
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Functions
void cancelFlick ()
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
virtual qreal maxXExtent () const
virtual qreal maxYExtent () const
virtual qreal minXExtent () const
virtual qreal minYExtent () const
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void movementXEnding ()
void movementYEnding ()
QDeclarativeFlickable (QDeclarativeFlickablePrivate &dd, QDeclarativeItem *parent)
bool sceneEvent (QEvent *event)
virtual bool sceneEventFilter (QGraphicsItem *, QEvent *)
Filters events for the item watched.
bool sendMouseEvent (QGraphicsSceneMouseEvent *event)
void timerEvent (QTimerEvent *event)
This event handler can be reimplemented in a subclass to receive timer events for the object.
qreal vHeight () const
virtual void viewportMoved ()
QDeclarativeFlickableVisibleArea * visibleArea ()
qreal vWidth () const
void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
bool xflick () const
bool yflick () const
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
virtual void componentComplete ()
virtual bool event (QEvent *)
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
virtual void keyPressEvent (QKeyEvent *event)
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
Properties
bool atXBeginning
bool atXEnd
bool atYBeginning
bool atYEnd
BoundsBehavior boundsBehavior
qreal contentHeight
QDeclarativeItem * contentItem
qreal contentWidth
qreal contentX
qreal contentY
QDeclarativeListProperty< QGraphicsObject > flickableChildren
QDeclarativeListProperty< QObject > flickableData
FlickableDirection flickableDirection
qreal flickDeceleration
bool flicking
bool flickingHorizontally
bool flickingVertically
qreal horizontalVelocity
bool interactive
qreal maximumFlickVelocity
bool moving
bool movingHorizontally
bool movingVertically
int pressDelay
qreal verticalVelocity
QDeclarativeFlickableVisibleArea * visibleArea
Friends
class QDeclarativeFlickableVisibleArea
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 55 of file qdeclarativeflickable_p.h.
Enumerations
BoundsBehavior
enum QDeclarativeFlickable::BoundsBehavior
Enumerator
StopAtBounds
DragOverBounds
DragAndOvershootBounds
Definition at line 103 of file qdeclarativeflickable_p.h.
 { StopAtBounds, DragOverBounds, DragAndOvershootBounds };
FlickableDirection
enum QDeclarativeFlickable::FlickableDirection
Enumerator
AutoFlickDirection
HorizontalFlick
VerticalFlick
HorizontalAndVerticalFlick
Definition at line 148 of file qdeclarativeflickable_p.h.
 { AutoFlickDirection=0x00, HorizontalFlick=0x01, VerticalFlick=0x02, HorizontalAndVerticalFlick=0x03 };
Constructors and Destructors
QDeclarativeFlickable() [1/2]
QDeclarativeFlickable::QDeclarativeFlickable (QDeclarativeItem * parent = 0)
Definition at line 547 of file qdeclarativeflickable.cpp.
   : QDeclarativeItem(*(new QDeclarativeFlickablePrivate), parent)
 {
     Q_D(QDeclarativeFlickable);
     d->init();
 }
~QDeclarativeFlickable()
QDeclarativeFlickable::~QDeclarativeFlickable ()
Definition at line 561 of file qdeclarativeflickable.cpp.
 {
 }
QDeclarativeFlickable() [2/2]
QDeclarativeFlickable::QDeclarativeFlickable (QDeclarativeFlickablePrivate & dd, QDeclarativeItem * parent) protected
Definition at line 554 of file qdeclarativeflickable.cpp.
   : QDeclarativeItem(dd, parent)
 {
     Q_D(QDeclarativeFlickable);
     d->init();
 }
Functions
boundsBehavior()
BoundsBehavior QDeclarativeFlickable::boundsBehavior () const
Referenced by QDeclarativeFlickablePrivate::data_clear(), and QDeclarativeFlickablePrivate::handleMouseMoveEvent().
boundsBehaviorChanged
void QDeclarativeFlickable::boundsBehaviorChanged () signal
Referenced by setBoundsBehavior().
cancelFlick()
void QDeclarativeFlickable::cancelFlick () protected
Definition at line 1245 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::trackedPositionChanged(), and QDeclarativeListView::trackedPositionChanged().
 {
     Q_D(QDeclarativeFlickable);
     d->timeline.reset(d->hData.move);
     d->timeline.reset(d->vData.move);
     movementEnding();
 }
contentHeight()
qreal QDeclarativeFlickable::contentHeight () const
Referenced by setContentWidth().
contentHeightChanged
void QDeclarativeFlickable::contentHeightChanged () signal
Referenced by geometryChanged(), resizeContent(), and setContentHeight().
contentItem()
QDeclarativeItem* QDeclarativeFlickable::contentItem ()
Referenced by QDeclarativeListView::createdItem(), QDeclarativeFlickablePrivate::data_at(), QDeclarativeFlickablePrivate::data_clear(), QDeclarativeFlickablePrivate::data_count(), QDeclarativeFlickablePrivate::setRoundedViewportX(), QDeclarativeFlickablePrivate::setRoundedViewportY(), and ticked().
contentWidth()
qreal QDeclarativeFlickable::contentWidth () const
Referenced by setBoundsBehavior().
contentWidthChanged
void QDeclarativeFlickable::contentWidthChanged () signal
Referenced by geometryChanged(), resizeContent(), and setContentWidth().
contentX()
qreal QDeclarativeFlickable::contentX () const
Referenced by QDeclarativeListView::geometryChanged(), resizeContent(), wheelEvent(), and ~QDeclarativeFlickable().
contentXChanged
void QDeclarativeFlickable::contentXChanged () signal
contentY()
qreal QDeclarativeFlickable::contentY () const
Referenced by resizeContent(), setContentX(), and wheelEvent().
contentYChanged
void QDeclarativeFlickable::contentYChanged () signal
flickableChildren()
QDeclarativeListProperty<QGraphicsObject> QDeclarativeFlickable::flickableChildren ()
Referenced by QDeclarativeFlickablePrivate::data_clear().
flickableData()
QDeclarativeListProperty<QObject> QDeclarativeFlickable::flickableData ()
Referenced by QDeclarativeFlickablePrivate::data_clear().
flickableDirection()
FlickableDirection QDeclarativeFlickable::flickableDirection () const
Referenced by ticked().
flickableDirectionChanged
void QDeclarativeFlickable::flickableDirectionChanged () signal
Referenced by setFlickableDirection().
flickDeceleration()
qreal QDeclarativeFlickable::flickDeceleration () const
Referenced by setMaximumFlickVelocity().
flickDecelerationChanged
void QDeclarativeFlickable::flickDecelerationChanged () signal
Referenced by setFlickDeceleration().
flickEnded
void QDeclarativeFlickable::flickEnded () signal
Referenced by movementXEnding(), movementYEnding(), and setInteractive().
flickingChanged
void QDeclarativeFlickable::flickingChanged () signal
Referenced by movementXEnding(), movementYEnding(), and setInteractive().
flickingHorizontallyChanged
void QDeclarativeFlickable::flickingHorizontallyChanged () signal
Referenced by movementXEnding(), and setInteractive().
flickingVerticallyChanged
void QDeclarativeFlickable::flickingVerticallyChanged () signal
Referenced by movementYEnding(), and setInteractive().
flickStarted
void QDeclarativeFlickable::flickStarted () signal
geometryChanged()
void QDeclarativeFlickable::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
If the two geometries are the same, it doesn't do anything.
Reimplemented from QDeclarativeItem.
Reimplemented in QDeclarativeListView.
Definition at line 1207 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeListView::geometryChanged().
 {
     Q_D(QDeclarativeFlickable);
     QDeclarativeItem::geometryChanged(newGeometry, oldGeometry);
     bool changed = false;
     if (newGeometry.width() != oldGeometry.width()) {
         if (xflick())
             changed = true;
         if (d->hData.viewSize < 0) {
             d->contentItem->setWidth(width());
             emit contentWidthChanged();
         }
         // Make sure that we're entirely in view.
         if (!d->pressed && !d->hData.moving && !d->vData.moving) {
             d->fixupMode = QDeclarativeFlickablePrivate::Immediate;
             d->fixupX();
         }
     }
     if (newGeometry.height() != oldGeometry.height()) {
         if (yflick())
             changed = true;
         if (d->vData.viewSize < 0) {
             d->contentItem->setHeight(height());
             emit contentHeightChanged();
         }
         // Make sure that we're entirely in view.
         if (!d->pressed && !d->hData.moving && !d->vData.moving) {
             d->fixupMode = QDeclarativeFlickablePrivate::Immediate;
             d->fixupY();
         }
     }
     if (changed)
         d->updateBeginningEnd();
 }
horizontalVelocity()
qreal QDeclarativeFlickable::horizontalVelocity () const
Referenced by setInteractive(), and viewportMoved().
horizontalVelocityChanged
void QDeclarativeFlickable::horizontalVelocityChanged () signal
interactiveChanged
void QDeclarativeFlickable::interactiveChanged () signal
Referenced by setInteractive().
isAtBoundaryChanged
void QDeclarativeFlickable::isAtBoundaryChanged () signal
isAtXBeginning()
bool QDeclarativeFlickable::isAtXBeginning () const
Definition at line 694 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->hData.atBeginning;
 }
isAtXEnd()
bool QDeclarativeFlickable::isAtXEnd () const
Definition at line 688 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->hData.atEnd;
 }
isAtYBeginning()
bool QDeclarativeFlickable::isAtYBeginning () const
Definition at line 706 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->vData.atBeginning;
 }
isAtYEnd()
bool QDeclarativeFlickable::isAtYEnd () const
Definition at line 700 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->vData.atEnd;
 }
isFlicking()
bool QDeclarativeFlickable::isFlicking () const
Definition at line 1689 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->hData.flicking ||  d->vData.flicking;
 }
isFlickingHorizontally()
bool QDeclarativeFlickable::isFlickingHorizontally () const
Definition at line 1706 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->hData.flicking;
 }
isFlickingVertically()
bool QDeclarativeFlickable::isFlickingVertically () const
Definition at line 1712 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->vData.flicking;
 }
isInteractive()
bool QDeclarativeFlickable::isInteractive () const
Definition at line 628 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeFlickablePrivate::isOutermostPressDelay().
 {
     Q_D(const QDeclarativeFlickable);
     return d->interactive;
 }
isMoving()
bool QDeclarativeFlickable::isMoving () const
Definition at line 1751 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->hData.moving || d->vData.moving;
 }
isMovingHorizontally()
bool QDeclarativeFlickable::isMovingHorizontally () const
Definition at line 1769 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->hData.moving;
 }
isMovingVertically()
bool QDeclarativeFlickable::isMovingVertically () const
Definition at line 1775 of file qdeclarativeflickable.cpp.
 {
     Q_D(const QDeclarativeFlickable);
     return d->vData.moving;
 }
maximumFlickVelocity()
qreal QDeclarativeFlickable::maximumFlickVelocity () const
Referenced by sceneEventFilter().
maximumFlickVelocityChanged
void QDeclarativeFlickable::maximumFlickVelocityChanged () signal
Referenced by setMaximumFlickVelocity().
maxXExtent()
qreal QDeclarativeFlickable::maxXExtent () const protected virtual
Reimplemented in QDeclarativeListView, and QDeclarativeGridView.
Definition at line 1138 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::maxXExtent(), QDeclarativeFlickableVisibleArea::updateVisible(), viewportMoved(), and wheelEvent().
 {
     return width() - vWidth();
 }
maxYExtent()
qreal QDeclarativeFlickable::maxYExtent () const protected virtual
Reimplemented in QDeclarativeListView, and QDeclarativeGridView.
Definition at line 1143 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::maxYExtent(), QDeclarativeFlickableVisibleArea::updateVisible(), viewportMoved(), and wheelEvent().
 {
     return height() - vHeight();
 }
minXExtent()
qreal QDeclarativeFlickable::minXExtent () const protected virtual
Reimplemented in QDeclarativeListView, and QDeclarativeGridView.
Definition at line 1132 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::minXExtent(), QDeclarativeListView::minXExtent(), QDeclarativeFlickableVisibleArea::updateVisible(), viewportMoved(), and wheelEvent().
 {
     return 0.0;
 }
minYExtent()
qreal QDeclarativeFlickable::minYExtent () const protected virtual
Reimplemented in QDeclarativeListView, and QDeclarativeGridView.
Definition at line 1127 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::minYExtent(), QDeclarativeListView::minYExtent(), QDeclarativeFlickableVisibleArea::updateVisible(), viewportMoved(), and wheelEvent().
 {
     return 0.0;
 }
mouseMoveEvent()
void QDeclarativeFlickable::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
If you do receive this event, you can be certain that this item also received a mouse press event, and that this item is the current mouse grabber.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseMoveEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 972 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (d->interactive) {
         d->handleMouseMoveEvent(event);
         event->accept();
     } else {
         QDeclarativeItem::mouseMoveEvent(event);
     }
 }
mousePressEvent()
void QDeclarativeFlickable::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
Mouse press events are only delivered to items that accept the mouse button that is pressed. By default, an item accepts all mouse buttons, but you can change this by calling setAcceptedMouseButtons().
The mouse press event decides which item should become the mouse grabber (see QGraphicsScene::mouseGrabberItem()). If you do not reimplement this function, the press event will propagate to any topmost item beneath this item, and no other mouse events will be delivered to this item.
If you do reimplement this function, event will by default be accepted (see QEvent::accept()), and this item is then the mouse grabber. This allows the item to receive future move, release and doubleclick events. If you call QEvent::ignore() on event, this item will lose the mouse grab, and event will propagate to any topmost item beneath. No further mouse events will be delivered to this item unless a new mouse press event is received.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mousePressEvent() in your reimplementation.
The event is for items that are neither QGraphicsItem::ItemIsMovable "movable" nor QGraphicsItem::ItemIsSelectable "selectable". mouseMoveEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 960 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (d->interactive) {
         if (!d->pressed)
             d->handleMousePressEvent(event);
         event->accept();
     } else {
         QDeclarativeItem::mousePressEvent(event);
     }
 }
mouseReleaseEvent()
void QDeclarativeFlickable::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseReleaseEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseMoveEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 983 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (d->interactive) {
         d->clearDelayedPress();
         d->handleMouseReleaseEvent(event);
         event->accept();
         ungrabMouse();
     } else {
         QDeclarativeItem::mouseReleaseEvent(event);
     }
 }
movementEnded
void QDeclarativeFlickable::movementEnded () signal
Referenced by movementXEnding(), and movementYEnding().
movementEnding
void QDeclarativeFlickable::movementEnding () protected slot
Definition at line 1800 of file qdeclarativeflickable.cpp.
Referenced by cancelFlick().
 {
     Q_D(QDeclarativeFlickable);
     movementXEnding();
     movementYEnding();
     d->hData.smoothVelocity.setValue(0);
     d->vData.smoothVelocity.setValue(0);
 }
movementStarted
void QDeclarativeFlickable::movementStarted () signal
Referenced by movementStarting().
movementStarting
void QDeclarativeFlickable::movementStarting () protected slot
Definition at line 1781 of file qdeclarativeflickable.cpp.
Referenced by wheelEvent().
 {
     Q_D(QDeclarativeFlickable);
     if (d->hMoved && !d->hData.moving) {
         d->hData.moving = true;
         emit movingChanged();
         emit movingHorizontallyChanged();
         if (!d->vData.moving)
             emit movementStarted();
     }
     else if (d->vMoved && !d->vData.moving) {
         d->vData.moving = true;
         emit movingChanged();
         emit movingVerticallyChanged();
         if (!d->hData.moving)
             emit movementStarted();
     }
 }
movementXEnding()
void QDeclarativeFlickable::movementXEnding () protected
Definition at line 1809 of file qdeclarativeflickable.cpp.
Referenced by movementEnding(), and setContentX().
 {
     Q_D(QDeclarativeFlickable);
     if (d->hData.flicking) {
         d->hData.flicking = false;
         emit flickingChanged();
         emit flickingHorizontallyChanged();
         if (!d->vData.flicking)
            emit flickEnded();
     }
     if (!d->pressed && !d->stealMouse) {
         if (d->hData.moving) {
             d->hData.moving = false;
             d->hMoved = false;
             emit movingChanged();
             emit movingHorizontallyChanged();
             if (!d->vData.moving)
                 emit movementEnded();
         }
     }
     d->hData.fixingUp = false;
 }
movementYEnding()
void QDeclarativeFlickable::movementYEnding () protected
Definition at line 1832 of file qdeclarativeflickable.cpp.
Referenced by movementEnding(), and setContentY().
 {
     Q_D(QDeclarativeFlickable);
     if (d->vData.flicking) {
         d->vData.flicking = false;
         emit flickingChanged();
         emit flickingVerticallyChanged();
         if (!d->hData.flicking)
            emit flickEnded();
     }
     if (!d->pressed && !d->stealMouse) {
         if (d->vData.moving) {
             d->vData.moving = false;
             d->vMoved = false;
             emit movingChanged();
             emit movingVerticallyChanged();
             if (!d->hData.moving)
                 emit movementEnded();
         }
     }
     d->vData.fixingUp = false;
 }
movingChanged
void QDeclarativeFlickable::movingChanged () signal
Referenced by movementStarting(), movementXEnding(), and movementYEnding().
movingHorizontallyChanged
void QDeclarativeFlickable::movingHorizontallyChanged () signal
Referenced by movementStarting(), and movementXEnding().
movingVerticallyChanged
void QDeclarativeFlickable::movingVerticallyChanged () signal
Referenced by movementStarting(), and movementYEnding().
pressDelay()
int QDeclarativeFlickable::pressDelay () const
Referenced by QDeclarativeFlickablePrivate::captureDelayedPress(), and isFlickingVertically().
pressDelayChanged
void QDeclarativeFlickable::pressDelayChanged () signal
Referenced by setPressDelay().
resizeContent()
void QDeclarativeFlickable::resizeContent (qreal w, qreal h, QPointF center)
Definition at line 1452 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (w != d->hData.viewSize) {
         qreal oldSize = d->hData.viewSize;
         d->hData.viewSize = w;
         d->contentItem->setWidth(w);
         emit contentWidthChanged();
         if (center.x() != 0) {
             qreal pos = center.x() * w / oldSize;
             setContentX(contentX() + pos - center.x());
         }
     }
     if (h != d->vData.viewSize) {
         qreal oldSize = d->vData.viewSize;
         d->vData.viewSize = h;
         d->contentItem->setHeight(h);
         emit contentHeightChanged();
         if (center.y() != 0) {
             qreal pos = center.y() * h / oldSize;
             setContentY(contentY() + pos - center.y());
         }
     }
     d->updateBeginningEnd();
 }
returnToBounds()
void QDeclarativeFlickable::returnToBounds ()
Definition at line 1491 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     d->fixupX();
     d->fixupY();
 }
sceneEvent()
bool QDeclarativeFlickable::sceneEvent (QEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 1532 of file qdeclarativeflickable.cpp.
 {
     bool rv = QDeclarativeItem::sceneEvent(event);
     if (event->type() == QEvent::UngrabMouse) {
         Q_D(QDeclarativeFlickable);
         if (d->pressed) {
             // if our mouse grab has been removed (probably by another Flickable),
             // fix our state
             d->pressed = false;
             d->stealMouse = false;
             setKeepMouseGrab(false);
         }
     }
     return rv;
 }
sceneEventFilter()
bool QDeclarativeFlickable::sceneEventFilter (QGraphicsItem * watched, QEvent * event) protected virtual
Filters events for the item watched.
event is the filtered event.
Reimplementing this function in a subclass makes it possible for the item to be used as an event filter for other items, intercepting all the events send to those items before they are able to respond.
Reimplementations must return true to prevent further processing of a given event, ensuring that it will not be delivered to the watched item, or return false to indicate that the event should be propagated further by the event system.
See also
installSceneEventFilter()
Reimplemented from QGraphicsItem.
Definition at line 1624 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (!isVisible() || !d->interactive || !isEnabled())
         return QDeclarativeItem::sceneEventFilter(i, e);
     switch (e->type()) {
     case QEvent::GraphicsSceneMousePress:
     case QEvent::GraphicsSceneMouseMove:
     case QEvent::GraphicsSceneMouseRelease:
         return sendMouseEvent(static_cast<QGraphicsSceneMouseEvent *>(e));
     default:
         break;
     }
     return QDeclarativeItem::sceneEventFilter(i, e);
 }
sendMouseEvent()
bool QDeclarativeFlickable::sendMouseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 1548 of file qdeclarativeflickable.cpp.
Referenced by sceneEventFilter().
 {
     Q_D(QDeclarativeFlickable);
     QGraphicsSceneMouseEvent mouseEvent(event->type());
     QRectF myRect = mapToScene(QRectF(0, 0, width(), height())).boundingRect();
     QGraphicsScene *s = scene();
     QDeclarativeItem *grabber = s ? qobject_cast<QDeclarativeItem*>(s->mouseGrabberItem()) : 0;
     QGraphicsItem *grabberItem = s ? s->mouseGrabberItem() : 0;
     bool disabledItem = grabberItem && !grabberItem->isEnabled();
     bool stealThisEvent = d->stealMouse;
     if ((stealThisEvent || myRect.contains(event->scenePos().toPoint())) && (!grabber || !grabber->keepMouseGrab() || disabledItem)) {
         mouseEvent.setAccepted(false);
         for (int i = 0x1; i <= 0x10; i <<= 1) {
             if (event->buttons() & i) {
                 Qt::MouseButton button = Qt::MouseButton(i);
                 mouseEvent.setButtonDownPos(button, mapFromScene(event->buttonDownPos(button)));
             }
         }
         mouseEvent.setScenePos(event->scenePos());
         mouseEvent.setLastScenePos(event->lastScenePos());
         mouseEvent.setPos(mapFromScene(event->scenePos()));
         mouseEvent.setLastPos(mapFromScene(event->lastScenePos()));
         switch(mouseEvent.type()) {
         case QEvent::GraphicsSceneMouseMove:
             d->handleMouseMoveEvent(&mouseEvent);
             break;
         case QEvent::GraphicsSceneMousePress:
             if (d->pressed && !event->spontaneous()) // we are already pressed - this is a delayed replay
                 return false;
             d->handleMousePressEvent(&mouseEvent);
             d->captureDelayedPress(event);
             stealThisEvent = d->stealMouse;   // Update stealThisEvent in case changed by function call above
             break;
         case QEvent::GraphicsSceneMouseRelease:
             if (d->delayedPressEvent) {
                 // We replay the mouse press but the grabber we had might not be interessted by the event (e.g. overlay)
                 // so we reset the grabber
                 if (s->mouseGrabberItem() == d->delayedPressTarget)
                     d->delayedPressTarget->ungrabMouse();
                 //Use the event handler that will take care of finding the proper item to propagate the event
                 QApplication::sendEvent(scene(), d->delayedPressEvent);
                 d->clearDelayedPress();
                 // We send the release
                 scene()->sendEvent(s->mouseGrabberItem(), event);
                 // And the event has been consumed
                 d->stealMouse = false;
                 d->pressed = false;
                 return true;
             }
             d->handleMouseReleaseEvent(&mouseEvent);
             break;
         default:
             break;
         }
         grabber = qobject_cast<QDeclarativeItem*>(s->mouseGrabberItem());
         if ((grabber && stealThisEvent && !grabber->keepMouseGrab() && grabber != this) || disabledItem) {
             d->clearDelayedPress();
             grabMouse();
         }
         return stealThisEvent || d->delayedPressEvent || disabledItem;
     } else if (d->lastPosTime.isValid()) {
         d->lastPosTime.invalidate();
     }
     if (mouseEvent.type() == QEvent::GraphicsSceneMouseRelease) {
         d->clearDelayedPress();
         d->stealMouse = false;
         d->pressed = false;
     }
     return false;
 }
setBoundsBehavior()
void QDeclarativeFlickable::setBoundsBehavior (BoundsBehavior b)
Definition at line 1350 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (b == d->boundsBehavior)
         return;
     d->boundsBehavior = b;
     emit boundsBehaviorChanged();
 }
setContentHeight()
void QDeclarativeFlickable::setContentHeight (qreal h)
Definition at line 1413 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::setFlow(), and QDeclarativeListView::setOrientation().
 {
     Q_D(QDeclarativeFlickable);
     if (d->vData.viewSize == h)
         return;
     d->vData.viewSize = h;
     if (h < 0)
         d->contentItem->setHeight(height());
     else
         d->contentItem->setHeight(h);
     // Make sure that we're entirely in view.
     if (!d->pressed && !d->hData.moving && !d->vData.moving) {
         d->fixupMode = QDeclarativeFlickablePrivate::Immediate;
         d->fixupY();
     } else if (!d->pressed && d->vData.fixingUp) {
         d->fixupMode = QDeclarativeFlickablePrivate::ExtentChanged;
         d->fixupY();
     }
     emit contentHeightChanged();
     d->updateBeginningEnd();
 }
setContentWidth()
void QDeclarativeFlickable::setContentWidth (qreal w)
Definition at line 1385 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::setFlow(), and QDeclarativeListView::setOrientation().
 {
     Q_D(QDeclarativeFlickable);
     if (d->hData.viewSize == w)
         return;
     d->hData.viewSize = w;
     if (w < 0)
         d->contentItem->setWidth(width());
     else
         d->contentItem->setWidth(w);
     // Make sure that we're entirely in view.
     if (!d->pressed && !d->hData.moving && !d->vData.moving) {
         d->fixupMode = QDeclarativeFlickablePrivate::Immediate;
         d->fixupX();
     } else if (!d->pressed && d->hData.fixingUp) {
         d->fixupMode = QDeclarativeFlickablePrivate::ExtentChanged;
         d->fixupX();
     }
     emit contentWidthChanged();
     d->updateBeginningEnd();
 }
setContentX()
void QDeclarativeFlickable::setContentX (qreal pos) virtual
Reimplemented in QDeclarativeListView, and QDeclarativeGridView.
Definition at line 582 of file qdeclarativeflickable.cpp.
Referenced by resizeContent(), QDeclarativeGridView::setContentX(), and QDeclarativeListView::setContentX().
 {
     Q_D(QDeclarativeFlickable);
     d->timeline.reset(d->hData.move);
     d->vTime = d->timeline.time();
     movementXEnding();
     if (-pos != d->hData.move.value()) {
         d->hData.move.setValue(-pos);
         viewportMoved();
     }
 }
setContentY()
void QDeclarativeFlickable::setContentY (qreal pos) virtual
Reimplemented in QDeclarativeListView, and QDeclarativeGridView.
Definition at line 600 of file qdeclarativeflickable.cpp.
Referenced by resizeContent(), QDeclarativeGridView::setContentY(), and QDeclarativeListView::setContentY().
 {
     Q_D(QDeclarativeFlickable);
     d->timeline.reset(d->vData.move);
     d->vTime = d->timeline.time();
     movementYEnding();
     if (-pos != d->vData.move.value()) {
         d->vData.move.setValue(-pos);
         viewportMoved();
     }
 }
setFlickableDirection()
void QDeclarativeFlickable::setFlickableDirection (FlickableDirection direction)
Definition at line 776 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeGridView::setFlow(), and QDeclarativeListView::setOrientation().
 {
     Q_D(QDeclarativeFlickable);
     if (direction != d->flickableDirection) {
         d->flickableDirection = direction;
         emit flickableDirectionChanged();
     }
 }
setFlickDeceleration()
void QDeclarativeFlickable::setFlickDeceleration (qreal deceleration)
Definition at line 1680 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (deceleration == d->deceleration)
         return;
     d->deceleration = deceleration;
     emit flickDecelerationChanged();
 }
setInteractive()
void QDeclarativeFlickable::setInteractive (bool interactive)
Definition at line 634 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (interactive != d->interactive) {
         d->interactive = interactive;
         if (!interactive && (d->hData.flicking || d->vData.flicking)) {
             d->timeline.clear();
             d->vTime = d->timeline.time();
             d->hData.flicking = false;
             d->vData.flicking = false;
             emit flickingChanged();
             emit flickingHorizontallyChanged();
             emit flickingVerticallyChanged();
             emit flickEnded();
         }
         emit interactiveChanged();
     }
 }
setMaximumFlickVelocity()
void QDeclarativeFlickable::setMaximumFlickVelocity (qreal v)
Definition at line 1656 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (v == d->maxVelocity)
         return;
     d->maxVelocity = v;
     emit maximumFlickVelocityChanged();
 }
setPressDelay()
void QDeclarativeFlickable::setPressDelay (int delay)
Definition at line 1741 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (d->pressDelay == delay)
         return;
     d->pressDelay = delay;
     emit pressDelayChanged();
 }
ticked
void QDeclarativeFlickable::ticked () protected virtual slot
Definition at line 712 of file qdeclarativeflickable.cpp.
 {
     viewportMoved();
 }
timerEvent()
void QDeclarativeFlickable::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 1105 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (event->timerId() == d->delayedPressTimer.timerId()) {
         d->delayedPressTimer.stop();
         if (d->delayedPressEvent) {
             QDeclarativeItem *grabber = scene() ? qobject_cast<QDeclarativeItem*>(scene()->mouseGrabberItem()) : 0;
             if (!grabber || grabber != this) {
                 // We replay the mouse press but the grabber we had might not be interessted by the event (e.g. overlay)
                 // so we reset the grabber
                 if (scene()->mouseGrabberItem() == d->delayedPressTarget)
                     d->delayedPressTarget->ungrabMouse();
                 //Use the event handler that will take care of finding the proper item to propagate the event
                 QApplication::postEvent(scene(), d->delayedPressEvent);
             } else {
                 delete d->delayedPressEvent;
             }
             d->delayedPressEvent = 0;
         }
     }
 }
verticalVelocity()
qreal QDeclarativeFlickable::verticalVelocity () const
Referenced by setInteractive(), and viewportMoved().
verticalVelocityChanged
void QDeclarativeFlickable::verticalVelocityChanged () signal
vHeight()
qreal QDeclarativeFlickable::vHeight () const protected
Definition at line 1507 of file qdeclarativeflickable.cpp.
Referenced by maxYExtent(), and yflick().
 {
     Q_D(const QDeclarativeFlickable);
     if (d->vData.viewSize < 0)
         return height();
     else
         return d->vData.viewSize;
 }
viewportMoved()
void QDeclarativeFlickable::viewportMoved () protected virtual
Reimplemented in QDeclarativeListView, and QDeclarativeGridView.
Definition at line 1148 of file qdeclarativeflickable.cpp.
Referenced by setContentX(), setContentY(), ticked(), QDeclarativeGridView::viewportMoved(), and QDeclarativeListView::viewportMoved().
 {
     Q_D(QDeclarativeFlickable);
     qreal prevX = d->lastFlickablePosition.x();
     qreal prevY = d->lastFlickablePosition.y();
     if (d->pressed || d->calcVelocity) {
         int elapsed = QDeclarativeItemPrivate::restart(d->velocityTime);
         if (elapsed > 0) {
             qreal horizontalVelocity = (prevX - d->hData.move.value()) * 1000 / elapsed;
             if (qAbs(horizontalVelocity) > 0) {
                 d->velocityTimeline.reset(d->hData.smoothVelocity);
                 d->velocityTimeline.move(d->hData.smoothVelocity, horizontalVelocity, d->reportedVelocitySmoothing);
                 d->velocityTimeline.move(d->hData.smoothVelocity, 0, d->reportedVelocitySmoothing);
             }
             qreal verticalVelocity = (prevY - d->vData.move.value()) * 1000 / elapsed;
             if (qAbs(verticalVelocity) > 0) {
                 d->velocityTimeline.reset(d->vData.smoothVelocity);
                 d->velocityTimeline.move(d->vData.smoothVelocity, verticalVelocity, d->reportedVelocitySmoothing);
                 d->velocityTimeline.move(d->vData.smoothVelocity, 0, d->reportedVelocitySmoothing);
             }
         }
     } else {
         if (d->timeline.time() > d->vTime) {
             d->velocityTimeline.clear();
             qreal horizontalVelocity = (prevX - d->hData.move.value()) * 1000 / (d->timeline.time() - d->vTime);
             qreal verticalVelocity = (prevY - d->vData.move.value()) * 1000 / (d->timeline.time() - d->vTime);
             d->hData.smoothVelocity.setValue(horizontalVelocity);
             d->vData.smoothVelocity.setValue(verticalVelocity);
         }
     }
     if (!d->vData.inOvershoot && !d->vData.fixingUp && d->vData.flicking
             && (d->vData.move.value() > minYExtent() || d->vData.move.value() < maxYExtent())
             && qAbs(d->vData.smoothVelocity.value()) > 100) {
         // Increase deceleration if we've passed a bound
         d->vData.inOvershoot = true;
         qreal maxDistance = d->overShootDistance(height());
         d->timeline.reset(d->vData.move);
         d->timeline.accel(d->vData.move, -d->vData.smoothVelocity.value(), d->deceleration*QML_FLICK_OVERSHOOTFRICTION, maxDistance);
         d->timeline.callback(QDeclarativeTimeLineCallback(&d->vData.move, d->fixupY_callback, d));
     }
     if (!d->hData.inOvershoot && !d->hData.fixingUp && d->hData.flicking
             && (d->hData.move.value() > minXExtent() || d->hData.move.value() < maxXExtent())
             && qAbs(d->hData.smoothVelocity.value()) > 100) {
         // Increase deceleration if we've passed a bound
         d->hData.inOvershoot = true;
         qreal maxDistance = d->overShootDistance(width());
         d->timeline.reset(d->hData.move);
         d->timeline.accel(d->hData.move, -d->hData.smoothVelocity.value(), d->deceleration*QML_FLICK_OVERSHOOTFRICTION, maxDistance);
         d->timeline.callback(QDeclarativeTimeLineCallback(&d->hData.move, d->fixupX_callback, d));
     }
     d->lastFlickablePosition = QPointF(d->hData.move.value(), d->vData.move.value());
     d->vTime = d->timeline.time();
     d->updateBeginningEnd();
 }
visibleArea()
QDeclarativeFlickableVisibleArea* QDeclarativeFlickable::visibleArea () protected
Referenced by ticked().
vWidth()
qreal QDeclarativeFlickable::vWidth () const protected
Definition at line 1498 of file qdeclarativeflickable.cpp.
Referenced by maxXExtent(), and xflick().
 {
     Q_D(const QDeclarativeFlickable);
     if (d->hData.viewSize < 0)
         return width();
     else
         return d->hData.viewSize;
 }
wheelEvent()
void QDeclarativeFlickable::wheelEvent (QGraphicsSceneWheelEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive wheel events for this item.
If you reimplement this function, event will be accepted by default.
If you ignore the event, (i.e., by calling QEvent::ignore(),) it will propagate to any item beneath this item. If no items accept the event, it will be ignored by the scene, and propagate to the view (e.g., the view's vertical scroll bar).
The default implementation ignores the event.
See also
sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 996 of file qdeclarativeflickable.cpp.
 {
     Q_D(QDeclarativeFlickable);
     if (!d->interactive) {
         QDeclarativeItem::wheelEvent(event);
     } else if (yflick() && event->orientation() == Qt::Vertical) {
         bool valid = false;
         if (event->delta() > 0 && contentY() > -minYExtent()) {
             d->vData.velocity = qMax(event->delta()*2 - d->vData.smoothVelocity.value(), qreal(d->maxVelocity/4));
             valid = true;
         } else if (event->delta() < 0 && contentY() < -maxYExtent()) {
             d->vData.velocity = qMin(event->delta()*2 - d->vData.smoothVelocity.value(), qreal(-d->maxVelocity/4));
             valid = true;
         }
         if (valid) {
             d->vData.flicking = false;
             d->flickY(d->vData.velocity);
             if (d->vData.flicking) {
                 d->vMoved = true;
                 movementStarting();
             }
             event->accept();
         }
     } else if (xflick() && event->orientation() == Qt::Horizontal) {
         bool valid = false;
         if (event->delta() > 0 && contentX() > -minXExtent()) {
             d->hData.velocity = qMax(event->delta()*2 - d->hData.smoothVelocity.value(), qreal(d->maxVelocity/4));
             valid = true;
         } else if (event->delta() < 0 && contentX() < -maxXExtent()) {
             d->hData.velocity = qMin(event->delta()*2 - d->hData.smoothVelocity.value(), qreal(-d->maxVelocity/4));
             valid = true;
         }
         if (valid) {
             d->hData.flicking = false;
             d->flickX(d->hData.velocity);
             if (d->hData.flicking) {
                 d->hMoved = true;
                 movementStarting();
             }
             event->accept();
         }
     } else {
         QDeclarativeItem::wheelEvent(event);
     }
 }
xflick()
bool QDeclarativeFlickable::xflick () const protected
Definition at line 1516 of file qdeclarativeflickable.cpp.
Referenced by geometryChanged(), QDeclarativeGridView::viewportMoved(), QDeclarativeListView::viewportMoved(), and wheelEvent().
 {
     Q_D(const QDeclarativeFlickable);
     if (d->flickableDirection == QDeclarativeFlickable::AutoFlickDirection)
         return vWidth() != width();
     return d->flickableDirection & QDeclarativeFlickable::HorizontalFlick;
 }
yflick()
bool QDeclarativeFlickable::yflick () const protected
Definition at line 1524 of file qdeclarativeflickable.cpp.
Referenced by geometryChanged(), QDeclarativeGridView::viewportMoved(), QDeclarativeListView::viewportMoved(), and wheelEvent().
 {
     Q_D(const QDeclarativeFlickable);
     if (d->flickableDirection == QDeclarativeFlickable::AutoFlickDirection)
         return vHeight() !=  height();
     return d->flickableDirection & QDeclarativeFlickable::VerticalFlick;
 }
Friends and Related Functions
QDeclarativeFlickableVisibleArea
friend class QDeclarativeFlickableVisibleArea friend
Definition at line 220 of file qdeclarativeflickable_p.h.
Referenced by ticked().
Properties
atXBeginning
bool QDeclarativeFlickable::atXBeginning private
Definition at line 84 of file qdeclarativeflickable_p.h.
atXEnd
bool QDeclarativeFlickable::atXEnd private
Definition at line 82 of file qdeclarativeflickable_p.h.
atYBeginning
bool QDeclarativeFlickable::atYBeginning private
Definition at line 85 of file qdeclarativeflickable_p.h.
atYEnd
bool QDeclarativeFlickable::atYEnd private
Definition at line 83 of file qdeclarativeflickable_p.h.
boundsBehavior
QDeclarativeFlickable::BoundsBehavior QDeclarativeFlickable::boundsBehavior private
Definition at line 68 of file qdeclarativeflickable_p.h.
contentHeight
qreal QDeclarativeFlickable::contentHeight private
Definition at line 60 of file qdeclarativeflickable_p.h.
contentItem
QDeclarativeItem * QDeclarativeFlickable::contentItem private
Definition at line 63 of file qdeclarativeflickable_p.h.
contentWidth
qreal QDeclarativeFlickable::contentWidth private
Definition at line 59 of file qdeclarativeflickable_p.h.
contentX
qreal QDeclarativeFlickable::contentX private
Definition at line 61 of file qdeclarativeflickable_p.h.
contentY
qreal QDeclarativeFlickable::contentY private
Definition at line 62 of file qdeclarativeflickable_p.h.
flickableChildren
QDeclarativeListProperty< QGraphicsObject > QDeclarativeFlickable::flickableChildren private
Definition at line 90 of file qdeclarativeflickable_p.h.
flickableData
QDeclarativeListProperty< QObject > QDeclarativeFlickable::flickableData private
Definition at line 89 of file qdeclarativeflickable_p.h.
flickableDirection
QDeclarativeFlickable::FlickableDirection QDeclarativeFlickable::flickableDirection private
Definition at line 77 of file qdeclarativeflickable_p.h.
flickDeceleration
qreal QDeclarativeFlickable::flickDeceleration private
Definition at line 70 of file qdeclarativeflickable_p.h.
flicking
bool QDeclarativeFlickable::flicking private
Definition at line 74 of file qdeclarativeflickable_p.h.
flickingHorizontally
bool QDeclarativeFlickable::flickingHorizontally private
Definition at line 75 of file qdeclarativeflickable_p.h.
flickingVertically
bool QDeclarativeFlickable::flickingVertically private
Definition at line 76 of file qdeclarativeflickable_p.h.
horizontalVelocity
qreal QDeclarativeFlickable::horizontalVelocity private
Definition at line 65 of file qdeclarativeflickable_p.h.
interactive
bool QDeclarativeFlickable::interactive private
Definition at line 79 of file qdeclarativeflickable_p.h.
Referenced by QDeclarativeFlickablePrivate::handleMouseMoveEvent(), QDeclarativeFlickablePrivate::handleMousePressEvent(), and setInteractive().
maximumFlickVelocity
qreal QDeclarativeFlickable::maximumFlickVelocity private
Definition at line 69 of file qdeclarativeflickable_p.h.
moving
bool QDeclarativeFlickable::moving private
Definition at line 71 of file qdeclarativeflickable_p.h.
movingHorizontally
bool QDeclarativeFlickable::movingHorizontally private
Definition at line 72 of file qdeclarativeflickable_p.h.
movingVertically
bool QDeclarativeFlickable::movingVertically private
Definition at line 73 of file qdeclarativeflickable_p.h.
pressDelay
int QDeclarativeFlickable::pressDelay private
Definition at line 80 of file qdeclarativeflickable_p.h.
Referenced by QDeclarativeFlickablePrivate::isOutermostPressDelay().
verticalVelocity
qreal QDeclarativeFlickable::verticalVelocity private
Definition at line 66 of file qdeclarativeflickable_p.h.
visibleArea
QDeclarativeFlickableVisibleArea * QDeclarativeFlickable::visibleArea private
Definition at line 87 of file qdeclarativeflickable_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeflickable_p.h
/src/declarative/graphicsitems/qdeclarativeflickable.cpp