Qt 4.8: QTransform Class Reference
QTransform Class Reference
The QTransform class specifies 2D transformations of a coordinate system.
#include <qtransform.h>
Public Types
enum TransformationType {
TxNone = 0x00, TxTranslate = 0x01, TxScale = 0x02, TxRotate = 0x04,
TxShear = 0x08, TxProject = 0x10
}
Public Functions
QTransform adjoint () const
Returns the adjoint of this matrix.
qreal det () const
Returns the matrix's determinant.
qreal determinant () const
Returns the matrix's determinant.
qreal dx () const
Returns the horizontal translation factor.
qreal dy () const
Returns the vertical translation factor.
QTransform inverted (bool *invertible=0) const
Returns an inverted copy of this matrix.
bool isAffine () const
Returns true if the matrix represent an affine transformation, otherwise returns false.
bool isIdentity () const
Returns true if the matrix is the identity matrix, otherwise returns false.
bool isInvertible () const
Returns true if the matrix is invertible, otherwise returns false.
bool isRotating () const
Returns true if the matrix represents some kind of a rotating transformation, otherwise returns false.
bool isScaling () const
Returns true if the matrix represents a scaling transformation, otherwise returns false.
bool isTranslating () const
Returns true if the matrix represents a translating transformation, otherwise returns false.
qreal m11 () const
Returns the horizontal scaling factor.
qreal m12 () const
Returns the vertical shearing factor.
qreal m13 () const
Returns the horizontal projection factor.
qreal m21 () const
Returns the horizontal shearing factor.
qreal m22 () const
Returns the vertical scaling factor.
qreal m23 () const
Returns the vertical projection factor.
qreal m31 () const
Returns the horizontal translation factor.
qreal m32 () const
Returns the vertical translation factor.
qreal m33 () const
Returns the division factor.
QPoint map (const QPoint &p) const
Creates and returns a QPoint object that is a copy of the given point, mapped into the coordinate system defined by this matrix.
QPointF map (const QPointF &p) const
Creates and returns a QPointF object that is a copy of the given point, p, mapped into the coordinate system defined by this matrix.
QLine map (const QLine &l) const
Creates and returns a QLineF object that is a copy of the given line, l, mapped into the coordinate system defined by this matrix.
QLineF map (const QLineF &l) const
Creates and returns a QLine object that is a copy of the given line, mapped into the coordinate system defined by this matrix.
QPolygonF map (const QPolygonF &a) const
Creates and returns a QPolygonF object that is a copy of the given polygon, mapped into the coordinate system defined by this matrix.
QPolygon map (const QPolygon &a) const
Creates and returns a QPolygon object that is a copy of the given polygon, mapped into the coordinate system defined by this matrix.
QRegion map (const QRegion &r) const
Creates and returns a QRegion object that is a copy of the given region, mapped into the coordinate system defined by this matrix.
QPainterPath map (const QPainterPath &p) const
Creates and returns a QPainterPath object that is a copy of the given path, mapped into the coordinate system defined by this matrix.
void map (int x, int y, int *tx, int *ty) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Maps the given coordinates x and y into the coordinate system defined by this matrix.
void map (qreal x, qreal y, qreal *tx, qreal *ty) const
Maps the given coordinates x and y into the coordinate system defined by this matrix.
QRect mapRect (const QRect &) const
Creates and returns a QRect object that is a copy of the given rectangle, mapped into the coordinate system defined by this matrix.
QRectF mapRect (const QRectF &) const
Creates and returns a QRectF object that is a copy of the given rectangle, mapped into the coordinate system defined by this matrix.
QPolygon mapToPolygon (const QRect &r) const
Creates and returns a QPolygon representation of the given rectangle, mapped into the coordinate system defined by this matrix.
operator QVariant () const
Returns the transform as a QVariant.
bool operator!= (const QTransform &) const
Returns true if this matrix is not equal to the given matrix, otherwise returns false.
QTransform operator* (const QTransform &o) const
Returns the result of multiplying this matrix by the given matrix.
QTransform & operator*= (const QTransform &)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the result of multiplying this matrix by the given matrix.
QTransform & operator*= (qreal div)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the result of performing an element-wise multiplication of this matrix with the given scalar.
QTransform & operator+= (qreal div)
Returns the matrix obtained by adding the given scalar to each element of this matrix.
QTransform & operator-= (qreal div)
Returns the matrix obtained by subtracting the given scalar from each element of this matrix.
QTransform & operator/= (qreal div)
Returns the result of performing an element-wise division of this matrix by the given scalar.
QTransform & operator= (const QTransform &)
Assigns the given matrix's values to this matrix.
bool operator== (const QTransform &) const
Returns true if this matrix is equal to the given matrix, otherwise returns false.
QTransform (Qt::Initialization)
QTransform ()
Constructs an identity matrix.
QTransform (qreal h11, qreal h12, qreal h13, qreal h21, qreal h22, qreal h23, qreal h31, qreal h32, qreal h33=1.0)
Constructs a matrix with the elements, m11, m12, m13, m21, m22, m23, m31, m32, m33.
QTransform (qreal h11, qreal h12, qreal h21, qreal h22, qreal dx, qreal dy)
Constructs a matrix with the elements, m11, m12, m21, m22, dx and dy.
QTransform (const QMatrix &mtx)
Constructs a matrix that is a copy of the given matrix.
void reset ()
Resets the matrix to an identity matrix, i.e.
QTransform & rotate (qreal a, Qt::Axis axis=Qt::ZAxis)
Rotates the coordinate system counterclockwise by the given angle about the specified axis and returns a reference to the matrix.
QTransform & rotateRadians (qreal a, Qt::Axis axis=Qt::ZAxis)
Rotates the coordinate system counterclockwise by the given angle about the specified axis and returns a reference to the matrix.
QTransform & scale (qreal sx, qreal sy)
Scales the coordinate system by sx horizontally and sy vertically, and returns a reference to the matrix.
void setMatrix (qreal m11, qreal m12, qreal m13, qreal m21, qreal m22, qreal m23, qreal m31, qreal m32, qreal m33)
Sets the matrix elements to the specified values, m11, m12, m13 m21, m22, m23 m31, m32 and m33.
QTransform & shear (qreal sh, qreal sv)
Shears the coordinate system by sh horizontally and sv vertically, and returns a reference to the matrix.
const QMatrix & toAffine () const
Returns the QTransform as an affine matrix.
QTransform & translate (qreal dx, qreal dy)
Moves the coordinate system dx along the x axis and dy along the y axis, and returns a reference to the matrix.
QTransform transposed () const
Returns the transpose of this matrix.
TransformationType type () const
Returns the transformation type of this matrix.
Static Public Functions
static QTransform fromScale (qreal dx, qreal dy)
Creates a matrix which corresponds to a scaling of sx horizontally and sy vertically.
static QTransform fromTranslate (qreal dx, qreal dy)
Creates a matrix which corresponds to a translation of dx along the x axis and dy along the y axis.
static bool quadToQuad (const QPolygonF &one, const QPolygonF &two, QTransform &result)
Creates a transformation matrix, trans, that maps a four-sided polygon, one, to another four-sided polygon, two.
static bool quadToSquare (const QPolygonF &quad, QTransform &result)
Creates a transformation matrix, trans, that maps a four-sided polygon, quad, to a unit square.
static bool squareToQuad (const QPolygonF &square, QTransform &result)
Creates a transformation matrix, trans, that maps a unit square to a four-sided polygon, quad.
Private Functions
TransformationType inline_type () const
QTransform (qreal h11, qreal h12, qreal h13, qreal h21, qreal h22, qreal h23, qreal h31, qreal h32, qreal h33, bool)
QTransform (bool)
Properties
QMatrix affine
Private * d
qreal m_13
qreal m_23
qreal m_33
uint m_dirty: 5
uint m_type: 5
Related Functions
(Note that these are not member functions.)
QPoint operator* (const QPoint &point, const QTransform &matrix)
QPointF operator* (const QPointF &point, const QTransform &matrix)
QLineF operator* (const QLineF &line, const QTransform &matrix)
QLine operator* (const QLine &line, const QTransform &matrix)
QPolygonF operator* (const QPolygonF &polygon, const QTransform &matrix)
QPolygon operator* (const QPolygon &polygon, const QTransform &matrix)
QRegion operator* (const QRegion &region, const QTransform &matrix)
QPainterPath operator* (const QPainterPath &path, const QTransform &matrix)
QDataStream & operator<< (QDataStream &stream, const QTransform &matrix)
Writes the given matrix to the given stream and returns a reference to the stream.
QDataStream & operator>> (QDataStream &stream, QTransform &matrix)
Reads the given matrix from the given stream and returns a reference to the stream.
bool qFuzzyCompare (const QTransform &t1, const QTransform &t2)
Returns true if t1 and t2 are equal, allowing for a small fuzziness factor for floating-point comparisons; false otherwise.
Detailed Description
The QTransform class specifies 2D transformations of a coordinate system.
Since
4.3
A transformation specifies how to translate, scale, shear, rotate or project the coordinate system, and is typically used when rendering graphics.
QTransform differs from QMatrix in that it is a true 3x3 matrix, allowing perspective transformations. QTransform's toAffine() method allows casting QTransform to QMatrix. If a perspective transformation has been specified on the matrix, then the conversion will cause loss of data.
QTransform is the recommended transformation class in Qt.
A QTransform object can be built using the setMatrix(), scale(), rotate(), translate() and shear() functions. Alternatively, it can be built by applying basic matrix operations. The matrix can also be defined when constructed, and it can be reset to the identity matrix (the default) using the reset() function.
The QTransform class supports mapping of graphic primitives: A given point, line, polygon, region, or painter path can be mapped to the coordinate system defined by this matrix using the map() function. In case of a rectangle, its coordinates can be transformed using the mapRect() function. A rectangle can also be transformed into a polygon (mapped to the coordinate system defined by this matrix), using the mapToPolygon() function.
QTransform provides the isIdentity() function which returns true if the matrix is the identity matrix, and the isInvertible() function which returns true if the matrix is non-singular (i.e. AB = BA = I). The inverted() function returns an inverted copy of this matrix if it is invertible (otherwise it returns the identity matrix), and adjoint() returns the matrix's classical adjoint. In addition, QTransform provides the determinant() function which returns the matrix's determinant.
Finally, the QTransform class supports matrix multiplication, addition and subtraction, and objects of the class can be streamed as well as compared.
Rendering Graphics
When rendering graphics, the matrix defines the transformations but the actual transformation is performed by the drawing routines in QPainter.
By default, QPainter operates on the associated device's own coordinate system. The standard coordinate system of a QPaintDevice has its origin located at the top-left position. The x values increase to the right; y values increase downward. For a complete description, see the Coordinate System documentation.
QPainter has functions to translate, scale, shear and rotate the coordinate system without using a QTransform. For example:
void SimpleTransformation::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    painter.setPen(QPen(Qt::blue, 1, Qt::DashLine));
    painter.drawRect(0, 0, 100, 100);
    painter.rotate(45);
    painter.setFont(QFont("Helvetica", 24));
    painter.setPen(QPen(Qt::black, 1));
    painter.drawText(20, 10, "QTransform");
}
Although these functions are very convenient, it can be more efficient to build a QTransform and call QPainter::setTransform() if you want to perform more than a single transform operation. For example:
void CombinedTransformation::paintEvent(QPaintEvent *)
{
    QPainter painter(this);
    painter.setPen(QPen(Qt::blue, 1, Qt::DashLine));
    painter.drawRect(0, 0, 100, 100);
    QTransform transform;
    transform.translate(50, 50);
    transform.rotate(45);
    transform.scale(0.5, 1.0);
    painter.setTransform(transform);
    painter.setFont(QFont("Helvetica", 24));
    painter.setPen(QPen(Qt::black, 1));
    painter.drawText(20, 10, "QTransform");
}
Basic Matrix Operations
A QTransform object contains a 3 x 3 matrix. The m31 (dx) and m32 (dy) elements specify horizontal and vertical translation. The m11 and m22 elements specify horizontal and vertical scaling. The m21 and m12 elements specify horizontal and vertical shearing. And finally, the m13 and m23 elements specify horizontal and vertical projection, with m33 as an additional projection factor.
QTransform transforms a point in the plane to another point using the following formulas:
x' = m11*x + m21*y + dx
y' = m22*y + m12*x + dy
if (is not affine) {
    w' = m13*x + m23*y + m33
    x' /= w'
    y' /= w'
}
The point (x, y) is the original point, and (x', y') is the transformed point. (x', y') can be transformed back to (x, y) by performing the same operation on the inverted() matrix.
The various matrix elements can be set when constructing the matrix, or by using the setMatrix() function later on. They can also be manipulated using the translate(), rotate(), scale() and shear() convenience functions. The currently set values can be retrieved using the m11(), m12(), m13(), m21(), m22(), m23(), m31(), m32(), m33(), dx() and dy() functions.
Translation is the simplest transformation. Setting dx and dy will move the coordinate system dx units along the X axis and dy units along the Y axis. Scaling can be done by setting m11 and m22. For example, setting m11 to 2 and m22 to 1.5 will double the height and increase the width by 50%. The identity matrix has m11, m22, and m33 set to 1 (all others are set to 0) mapping a point to itself. Shearing is controlled by m12 and m21. Setting these elements to values different from zero will twist the coordinate system. Rotation is achieved by setting both the shearing factors and the scaling factors. Perspective transformation is achieved by setting both the projection factors and the scaling factors.
Here's the combined transformations example using basic matrix operations:
void BasicOperations::paintEvent(QPaintEvent *)
{
    double pi = 3.14;
    double a    = pi/180 * 45.0;
    double sina = sin(a);
    double cosa = cos(a);
    QTransform translationTransform(1, 0, 0, 1, 50.0, 50.0);
    QTransform rotationTransform(cosa, sina, -sina, cosa, 0, 0);
    QTransform scalingTransform(0.5, 0, 0, 1.0, 0, 0);
    QTransform transform;
    transform = scalingTransform * rotationTransform * translationTransform;
    QPainter painter(this);
    painter.setPen(QPen(Qt::blue, 1, Qt::DashLine));
    painter.drawRect(0, 0, 100, 100);
    painter.setTransform(transform);
    painter.setFont(QFont("Helvetica", 24));
    painter.setPen(QPen(Qt::black, 1));
    painter.drawText(20, 10, "QTransform");
}
See also
QPainter, {Coordinate System}, {demos/affine}{Affine Transformations Demo}, {Transformations Example}
Definition at line 65 of file qtransform.h.
Enumerations
TransformationType
enum QTransform::TransformationType
TxNone
TxTranslate
TxScale
TxRotate
TxShear
TxProject
Enumerator
TxNone
TxTranslate
TxScale
TxRotate
TxShear
TxProject
Definition at line 68 of file qtransform.h.
{
         TxNone      = 0x00,
         TxTranslate = 0x01,
         TxScale     = 0x02,
         TxRotate    = 0x04,
         TxShear     = 0x08,
         TxProject   = 0x10
     };
Constructors and Destructors
QTransform() [1/7]
QTransform::QTransform (Qt::Initialization) inline explicit
Warning
This function is not part of the public interface.
Definition at line 77 of file qtransform.h.
 : affine(Qt::Uninitialized) {}
QTransform() [2/7]
QTransform::QTransform ()
Constructs an identity matrix.
All elements are set to zero except m11 and m22 (specifying the scale) and m13 which are set to 1.
See also
reset()
Definition at line 252 of file qtransform.cpp.
Referenced by adjoint(), fromScale(), fromTranslate(), and map().
     : affine(true)
     , m_13(0), m_23(0), m_33(1)
     , m_type(TxNone)
     , m_dirty(TxNone)
 {
 }
QTransform() [3/7]
QTransform::QTransform (qreal m11, qreal m12, qreal m13, qreal m21, qreal m22, qreal m23, qreal m31, qreal m32, qreal m33 = 1.0)
Constructs a matrix with the elements, m11, m12, m13, m21, m22, m23, m31, m32, m33.
See also
setMatrix()
Definition at line 271 of file qtransform.cpp.
     : affine(h11, h12, h21, h22, h31, h32, true)
     , m_13(h13), m_23(h23), m_33(h33)
     , m_type(TxNone)
     , m_dirty(TxProject)
 {
 }
QTransform() [4/7]
QTransform::QTransform (qreal m11, qreal m12, qreal m21, qreal m22, qreal dx, qreal dy)
Constructs a matrix with the elements, m11, m12, m21, m22, dx and dy.
See also
setMatrix()
Definition at line 291 of file qtransform.cpp.
     : affine(h11, h12, h21, h22, dx, dy, true)
     , m_13(0), m_23(0), m_33(1)
     , m_type(TxNone)
     , m_dirty(TxShear)
 {
 }
QTransform() [5/7]
QTransform::QTransform (const QMatrix & matrix) explicit
Constructs a matrix that is a copy of the given matrix.
Note that the m13, m23, and m33 elements are set to 0, 0, and 1 respectively.
Definition at line 310 of file qtransform.cpp.
     : affine(mtx._m11, mtx._m12, mtx._m21, mtx._m22, mtx._dx, mtx._dy, true),
       m_13(0), m_23(0), m_33(1)
     , m_type(TxNone)
     , m_dirty(TxShear)
 {
 }
QTransform() [6/7]
QTransform::QTransform (qreal h11, qreal h12, qreal h13, qreal h21, qreal h22, qreal h23, qreal h31, qreal h32, qreal h33, bool) inline private
Definition at line 166 of file qtransform.h.
         : affine(h11, h12, h21, h22, h31, h32, true)
         , m_13(h13), m_23(h23), m_33(h33)
         , m_type(TxNone)
         , m_dirty(TxProject) {}
QTransform() [7/7]
QTransform::QTransform (bool) inline private
Definition at line 173 of file qtransform.h.
         : affine(true)
         , m_13(0), m_23(0), m_33(1)
         , m_type(TxNone)
         , m_dirty(TxNone) {}
Functions
adjoint()
QTransform QTransform::adjoint () const
Returns the adjoint of this matrix.
Definition at line 321 of file qtransform.cpp.
Referenced by inverted().
 {
     qreal h11, h12, h13,
         h21, h22, h23,
         h31, h32, h33;
     h11 = affine._m22*m_33 - m_23*affine._dy;
     h21 = m_23*affine._dx - affine._m21*m_33;
     h31 = affine._m21*affine._dy - affine._m22*affine._dx;
     h12 = m_13*affine._dy - affine._m12*m_33;
     h22 = affine._m11*m_33 - m_13*affine._dx;
     h32 = affine._m12*affine._dx - affine._m11*affine._dy;
     h13 = affine._m12*m_23 - m_13*affine._m22;
     h23 = m_13*affine._m21 - affine._m11*m_23;
     h33 = affine._m11*affine._m22 - affine._m12*affine._m21;
     return QTransform(h11, h12, h13,
                       h21, h22, h23,
                       h31, h32, h33, true);
 }
det()
qreal QTransform::det () const inline
Returns the matrix's determinant.
Use determinant() instead.
Definition at line 233 of file qtransform.h.
Referenced by inverted(), and QFontEngineFT::loadTransformedGlyphSet().
 {
     return determinant();
 }
determinant()
qreal QTransform::determinant () const inline
Returns the matrix's determinant.
Definition at line 228 of file qtransform.h.
Referenced by QGL2PaintEngineEx::drawStaticTextItem(), QGL2PaintEngineEx::drawTextItem(), inverted(), and QRasterPaintEngine::supportsTransformations().
 {
     return affine._m11*(m_33*affine._m22-affine._dy*m_23) -
         affine._m21*(m_33*affine._m12-affine._dy*m_13)+affine._dx*(m_23*affine._m12-affine._m22*m_13);
 }
dx()
qreal QTransform::dx () const inline
Returns the horizontal translation factor.
See also
m31(), translate(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 273 of file qtransform.h.
Referenced by QPdfEnginePrivate::addBrushPattern(), QGL2PaintEngineEx::beginNativePainting(), QProxyFontEngine::canRender(), QPixmapConvolutionFilter::draw(), QFontEngineQPF::draw(), QFontEngineQPF1::draw(), draw_text_item_win(), QVGPaintEngine::drawCachedGlyphs(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawPixmap(), QRasterPaintEngine::drawRects(), QGraphicsScenePrivate::drawSubtreeRecursive(), QRasterPaintEngine::drawTiledPixmap(), QBlitterPaintEngine::fillRect(), QRasterPaintEngine::fillRect(), QGraphicsView::fitInView(), QPdf::generateMatrix(), QFontEngine::getGlyphPositions(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsItem::mapFromScene(), QGraphicsItem::mapRectFromScene(), QGraphicsItem::mapRectToScene(), QGraphicsItem::mapToScene(), QGraphicsItem::prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QMacCGContext::QMacCGContext(), QMatrix4x4::QMatrix4x4(), qt_mac_convert_transform_to_cg(), qt_xForm_helper(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsItem::sceneBoundingRect(), QOutlineMapper::setMatrix(), QGraphicsViewPrivate::setUpdateClip(), QSpanData::setupMatrix(), QPaintBufferEngine::transformChanged(), QPaintEnginePrivate::transformSystemClip(), translate(), updateHelper(), QOpenGLPaintEngine::updateMatrix(), QRasterPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), and QRasterPaintEnginePrivate::updateMatrixData().
 {
     return affine._dx;
 }
dy()
qreal QTransform::dy () const inline
Returns the vertical translation factor.
See also
translate(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 277 of file qtransform.h.
Referenced by QPdfEnginePrivate::addBrushPattern(), QGL2PaintEngineEx::beginNativePainting(), QProxyFontEngine::canRender(), QPixmapConvolutionFilter::draw(), QFontEngineQPF::draw(), QFontEngineQPF1::draw(), draw_text_item_win(), QVGPaintEngine::drawCachedGlyphs(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawPixmap(), QRasterPaintEngine::drawRects(), QGraphicsScenePrivate::drawSubtreeRecursive(), QRasterPaintEngine::drawTiledPixmap(), QBlitterPaintEngine::fillRect(), QRasterPaintEngine::fillRect(), QGraphicsView::fitInView(), QPdf::generateMatrix(), QFontEngine::getGlyphPositions(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsItem::mapFromScene(), QGraphicsItem::mapRectFromScene(), QGraphicsItem::mapRectToScene(), QGraphicsItem::mapToScene(), QGraphicsItem::prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QMacCGContext::QMacCGContext(), QMatrix4x4::QMatrix4x4(), qt_mac_convert_transform_to_cg(), qt_xForm_helper(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsItem::sceneBoundingRect(), QOutlineMapper::setMatrix(), QGraphicsViewPrivate::setUpdateClip(), QSpanData::setupMatrix(), QPaintBufferEngine::transformChanged(), QPaintEnginePrivate::transformSystemClip(), translate(), updateHelper(), QOpenGLPaintEngine::updateMatrix(), QRasterPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), and QRasterPaintEnginePrivate::updateMatrixData().
 {
     return affine._dy;
 }
fromScale()
QTransform QTransform::fromScale (qreal sx, qreal sy) static
Creates a matrix which corresponds to a scaling of sx horizontally and sy vertically.
This is the same as QTransform().scale(sx, sy) but slightly faster.
Since
4.5
Definition at line 528 of file qtransform.cpp.
Referenced by QGraphicsItem::boundingRegion(), QWin32PrintEngine::drawPixmap(), QGraphicsItem::scale(), QPixmap::scaled(), QImage::scaled(), QPixmap::scaledToHeight(), QImage::scaledToHeight(), QPixmap::scaledToWidth(), and QImage::scaledToWidth().
 {
 #ifndef QT_NO_DEBUG
     if (qIsNaN(sx) | qIsNaN(sy)) {
         qWarning() << "QTransform::fromScale with NaN called";
         return QTransform();
 }
 #endif
     QTransform transform(sx, 0, 0, 0, sy, 0, 0, 0, 1, true);
     if (sx == 1. && sy == 1.)
         transform.m_type = TxNone;
     else
         transform.m_type = TxScale;
     transform.m_dirty = TxNone;
     return transform;
 }
fromTranslate()
QTransform QTransform::fromTranslate (qreal dx, qreal dy) static
Creates a matrix which corresponds to a translation of dx along the x axis and dy along the y axis.
This is the same as QTransform().translate(dx, dy) but slightly faster.
Since
4.5
Definition at line 462 of file qtransform.cpp.
Referenced by QFontEngine::addOutlineToPath(), QFontEngineBox::addOutlineToPath(), QGraphicsItemGroup::addToGroup(), QPainterPrivate::attachPainterPrivate(), QFontEngineBox::boundingBox(), QGraphicsItemPrivate::combineTransformToParent(), QGraphicsItem::deviceTransform(), QGraphicsOpacityEffect::draw(), draw_text_item_win(), QPaintEnginePrivate::drawBoxTextItem(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QRasterPaintEngine::drawImage(), QOpenGLPaintEnginePrivate::drawImageAsPath(), QGraphicsScenePrivate::drawItemHelper(), QGL2PaintEngineEx::drawTextItem(), QOpenGLPaintEngine::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), QOpenGLPaintEnginePrivate::drawTiledImageAsPath(), QVGPaintEngine::drawTiledPixmap(), QPaintEngineEx::drawTiledPixmap(), QVGPaintEnginePrivate::ensurePathTransform(), fillBackground(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsItem::itemTransform(), QGraphicsView::mapFromScene(), QGraphicsView::mapToScene(), QGraphicsItemEffectSourcePrivate::pixmap(), qt_true_matrix(), QGraphicsItemGroup::removeFromGroup(), QGraphicsView::render(), QWidgetPrivate::render_helper(), QGraphicsItem::translate(), QGraphicsItemPrivate::updateSceneTransformFromParent(), and QGraphicsView::viewportTransform().
 {
 #ifndef QT_NO_DEBUG
     if (qIsNaN(dx) | qIsNaN(dy)) {
         qWarning() << "QTransform::fromTranslate with NaN called";
         return QTransform();
 }
 #endif
     QTransform transform(1, 0, 0, 0, 1, 0, dx, dy, 1, true);
     if (dx == 0 && dy == 0)
         transform.m_type = TxNone;
     else
         transform.m_type = TxTranslate;
     transform.m_dirty = TxNone;
     return transform;
 }
inline_type()
QTransform::TransformationType QTransform::inline_type () const inline private
Definition at line 193 of file qtransform.h.
Referenced by inverted(), map(), mapRect(), mapToPolygon(), operator*(), operator*=(), rotate(), rotateRadians(), scale(), shear(), and translate().
 {
     if (m_dirty == TxNone)
         return static_cast<TransformationType>(m_type);
     return type();
 }
inverted()
QTransform QTransform::inverted (bool * invertible = 0) const
Returns an inverted copy of this matrix.
If the matrix is singular (not invertible), the returned matrix is the identity matrix. If invertible is valid (i.e. not 0), its value is set to true if the matrix is invertible, otherwise it is set to false.
See also
isInvertible()
Definition at line 364 of file qtransform.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsItem::boundingRegion(), draw_text_item_win(), QRasterPaintEngine::drawImage(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsScenePrivate::drawItems(), QGLEllipseMaskGenerator::drawMask(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsItemPrivate::initStyleOption(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsView::items(), QGraphicsScenePrivate::itemsAtPosition(), QGraphicsItem::itemTransform(), QMacPixmapData::macCreatePixels(), QGraphicsItem::mapFromParent(), QGraphicsItem::mapFromScene(), QGraphicsItem::mapRectFromParent(), QGraphicsItem::mapRectFromScene(), QGraphicsViewPrivate::mapRectToScene(), QGraphicsItem::mouseMoveEvent(), QDeclarativePaintedItem::paint(), QGraphicsItemEffectSourcePrivate::pixmap(), quadToSquare(), QGraphicsItemGroup::removeFromGroup(), QGL2PaintEngineExPrivate::resetClipIfNeeded(), roundInDeviceCoordinates(), QPaintEngineEx::stroke(), QImage::transformed(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QPainterPrivate::updateInvMatrix(), and QRasterPaintEngine::updatePen().
 {
     QTransform invert(true);
     bool inv = true;
     switch(inline_type()) {
     case TxNone:
         break;
     case TxTranslate:
         invert.affine._dx = -affine._dx;
         invert.affine._dy = -affine._dy;
         break;
     case TxScale:
         inv = !qFuzzyIsNull(affine._m11);
         inv &= !qFuzzyIsNull(affine._m22);
         if (inv) {
             invert.affine._m11 = 1. / affine._m11;
             invert.affine._m22 = 1. / affine._m22;
             invert.affine._dx = -affine._dx * invert.affine._m11;
             invert.affine._dy = -affine._dy * invert.affine._m22;
         }
         break;
     case TxRotate:
     case TxShear:
         invert.affine = affine.inverted(&inv);
         break;
     default:
         // general case
         qreal det = determinant();
         inv = !qFuzzyIsNull(det);
         if (inv)
             invert = adjoint() / det;
         break;
     }
     if (invertible)
         *invertible = inv;
     if (inv) {
         // inverting doesn't change the type
         invert.m_type = m_type;
         invert.m_dirty = m_dirty;
     }
     return invert;
 }
isAffine()
bool QTransform::isAffine () const inline
Returns true if the matrix represent an affine transformation, otherwise returns false.
Definition at line 200 of file qtransform.h.
Referenced by QDeclarativeTextLayout::draw(), QRasterPaintEngine::drawCachedGlyphs(), QPaintEngineEx::supportsTransformations(), QPainterPrivate::updateEmulationSpecifier(), and QGLEngineShaderManager::useCorrectShaderProg().
 {
     return inline_type() < TxProject;
 }
isIdentity()
bool QTransform::isIdentity () const inline
Returns true if the matrix is the identity matrix, otherwise returns false.
See also
reset()
Definition at line 204 of file qtransform.h.
Referenced by QGraphicsItemPrivate::TransformData::computedFullTransform(), QDeclarativeImage::paint(), qt_plastique_draw_gradient(), QVGPaintEnginePrivate::setBrushTransform(), QPaintEnginePrivate::setSystemTransform(), QStrokerOps::strokeEllipse(), QStrokerOps::strokePath(), QStrokerOps::strokePolygon(), QPainterPrivate::updateEmulationSpecifier(), and QCoreGraphicsPaintEngine::updateMatrix().
 {
     return inline_type() == TxNone;
 }
isInvertible()
bool QTransform::isInvertible () const inline
Returns true if the matrix is invertible, otherwise returns false.
See also
inverted()
Definition at line 209 of file qtransform.h.
 {
     return !qFuzzyIsNull(determinant());
 }
isRotating()
bool QTransform::isRotating () const inline
Returns true if the matrix represents some kind of a rotating transformation, otherwise returns false.
See also
reset()
Definition at line 218 of file qtransform.h.
 {
     return inline_type() >= TxRotate;
 }
isScaling()
bool QTransform::isScaling () const inline
Returns true if the matrix represents a scaling transformation, otherwise returns false.
See also
reset()
Definition at line 214 of file qtransform.h.
Referenced by QDirectFBPaintEngine::drawTiledPixmap(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QDirectFBPaintEngine::fillRect(), and QWidgetPrivate::render_helper().
 {
     return type() >= TxScale;
 }
isTranslating()
bool QTransform::isTranslating () const inline
Returns true if the matrix represents a translating transformation, otherwise returns false.
See also
reset()
Definition at line 223 of file qtransform.h.
Referenced by QPainter::drawStaticText().
 {
     return inline_type() >= TxTranslate;
 }
m11()
qreal QTransform::m11 () const inline
Returns the horizontal scaling factor.
See also
scale(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 237 of file qtransform.h.
Referenced by QPdfEnginePrivate::addBrushPattern(), QFontEngineDirectWrite::alphaMapBoundingBox(), QFontEngineFT::alphaMapBoundingBox(), QGL2PaintEngineEx::beginNativePainting(), QFontEngineWin::boundingBox(), QVGPaintEngine::canVgWritePixels(), clipTransformIsSimple(), QDeclarativeParentChangePrivate::doChange(), QPainterPrivate::draw_helper(), draw_text_item_win(), QRasterPaintEngine::drawCachedGlyphs(), QFontEngineWin::drawGDIGlyph(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawTextItem(), QPainter::drawTextItem(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QPdf::generateMatrix(), QFontEngine::getGlyphPositions(), QDirectFBPaintEnginePrivate::getTransformationType(), QGLMaskTextureCache::hash(), QFontEngineDirectWrite::imageForGlyph(), QFontEngineFT::loadTransformedGlyphSet(), QMacPixmapData::macCreatePixels(), mapHomogeneous(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QMatrix4x4::QMatrix4x4(), qt_format_text(), qt_mac_convert_transform_to_cg(), qt_scaleForTransform(), qt_xForm_helper(), qtransform_equals_no_translate(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), QOutlineMapper::setMatrix(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), QSpanData::setupMatrix(), QX11PixmapData::transformed(), QImage::transformed(), transformIsSimple(), QDeclarativeParentAnimation::transition(), QOpenGLPaintEnginePrivate::updateGradient(), QCoreGraphicsPaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QRasterPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), and QBlitterPaintEnginePrivate::updateTransformState().
 {
     return affine._m11;
 }
m12()
qreal QTransform::m12 () const inline
Returns the vertical shearing factor.
See also
shear(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 241 of file qtransform.h.
Referenced by QPdfEnginePrivate::addBrushPattern(), QFontEngineDirectWrite::alphaMapBoundingBox(), QFontEngineFT::alphaMapBoundingBox(), QGL2PaintEngineEx::beginNativePainting(), QFontEngineWin::boundingBox(), clipTransformIsSimple(), QDeclarativeParentChangePrivate::doChange(), draw_text_item_win(), QFontEngineWin::drawGDIGlyph(), QRasterPaintEngine::drawImage(), QPainter::drawTextItem(), QPdf::generateMatrix(), QFontEngine::getGlyphPositions(), QGLMaskTextureCache::hash(), QFontEngineDirectWrite::imageForGlyph(), QFontEngineFT::loadTransformedGlyphSet(), QMacPixmapData::macCreatePixels(), mapHomogeneous(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QMatrix4x4::QMatrix4x4(), qt_mac_convert_transform_to_cg(), qt_scaleForTransform(), qt_xForm_helper(), qtransform_equals_no_translate(), QGLEllipseMaskGenerator::screenRect(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), QOutlineMapper::setMatrix(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), QSpanData::setupMatrix(), QX11PixmapData::transformed(), QImage::transformed(), transformIsSimple(), QDeclarativeParentAnimation::transition(), QOpenGLPaintEnginePrivate::updateGradient(), QCoreGraphicsPaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QRasterPaintEngine::updateMatrix(), and QGL2PaintEngineExPrivate::updateMatrix().
 {
     return affine._m12;
 }
m13()
qreal QTransform::m13 () const inline
Returns the horizontal projection factor.
See also
translate(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 245 of file qtransform.h.
Referenced by QGL2PaintEngineEx::beginNativePainting(), QRasterPaintEngine::drawImage(), QGLMaskTextureCache::hash(), mapHomogeneous(), needsPerspectiveClipping(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QMatrix4x4::QMatrix4x4(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), QOutlineMapper::setMatrix(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), QSpanData::setupMatrix(), QX11PixmapData::transformed(), QCoreGraphicsPaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), and QVGPaintEnginePrivate::updateTransform().
 {
     return m_13;
 }
m21()
qreal QTransform::m21 () const inline
Returns the horizontal shearing factor.
See also
shear(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 249 of file qtransform.h.
Referenced by QPdfEnginePrivate::addBrushPattern(), QFontEngineDirectWrite::alphaMapBoundingBox(), QFontEngineFT::alphaMapBoundingBox(), QGL2PaintEngineEx::beginNativePainting(), QFontEngineWin::boundingBox(), clipTransformIsSimple(), draw_text_item_win(), QFontEngineWin::drawGDIGlyph(), QRasterPaintEngine::drawImage(), QPainter::drawTextItem(), QPdf::generateMatrix(), QFontEngine::getGlyphPositions(), QGLMaskTextureCache::hash(), QFontEngineDirectWrite::imageForGlyph(), QFontEngineFT::loadTransformedGlyphSet(), QMacPixmapData::macCreatePixels(), mapHomogeneous(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QMatrix4x4::QMatrix4x4(), qt_mac_convert_transform_to_cg(), qt_scaleForTransform(), qt_xForm_helper(), qtransform_equals_no_translate(), QGLEllipseMaskGenerator::screenRect(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), QOutlineMapper::setMatrix(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), QSpanData::setupMatrix(), QX11PixmapData::transformed(), QImage::transformed(), transformIsSimple(), QOpenGLPaintEnginePrivate::updateGradient(), QCoreGraphicsPaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QRasterPaintEngine::updateMatrix(), and QGL2PaintEngineExPrivate::updateMatrix().
 {
     return affine._m21;
 }
m22()
qreal QTransform::m22 () const inline
Returns the vertical scaling factor.
See also
scale(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 253 of file qtransform.h.
Referenced by QPdfEnginePrivate::addBrushPattern(), QFontEngineDirectWrite::alphaMapBoundingBox(), QFontEngineFT::alphaMapBoundingBox(), QGL2PaintEngineEx::beginNativePainting(), QFontEngineWin::boundingBox(), QVGPaintEngine::canVgWritePixels(), QGL2PaintEngineEx::clip(), clipTransformIsSimple(), QDeclarativeParentChangePrivate::doChange(), QPainterPrivate::draw_helper(), draw_text_item_win(), QFontEngineWin::drawGDIGlyph(), QVGPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QRasterPaintEngine::drawTextItem(), QPainter::drawTextItem(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QPdf::generateMatrix(), QFontEngine::getGlyphPositions(), QDirectFBPaintEnginePrivate::getTransformationType(), QGLMaskTextureCache::hash(), QFontEngineDirectWrite::imageForGlyph(), QFontEngineFT::loadTransformedGlyphSet(), QMacPixmapData::macCreatePixels(), mapHomogeneous(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QMatrix4x4::QMatrix4x4(), qt_format_text(), qt_mac_convert_transform_to_cg(), qt_scaleForTransform(), qt_xForm_helper(), qtransform_equals_no_translate(), QGLEllipseMaskGenerator::screenRect(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), QOutlineMapper::setMatrix(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), QSpanData::setupMatrix(), QX11PixmapData::transformed(), QImage::transformed(), transformIsSimple(), QDeclarativeParentAnimation::transition(), QOpenGLPaintEnginePrivate::updateGradient(), QCoreGraphicsPaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QRasterPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), and QBlitterPaintEnginePrivate::updateTransformState().
 {
     return affine._m22;
 }
m23()
qreal QTransform::m23 () const inline
Returns the vertical projection factor.
See also
translate(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 257 of file qtransform.h.
Referenced by QGL2PaintEngineEx::beginNativePainting(), QRasterPaintEngine::drawImage(), QGLMaskTextureCache::hash(), mapHomogeneous(), needsPerspectiveClipping(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QMatrix4x4::QMatrix4x4(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), QOutlineMapper::setMatrix(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), QSpanData::setupMatrix(), QX11PixmapData::transformed(), QCoreGraphicsPaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), and QVGPaintEnginePrivate::updateTransform().
 {
     return m_23;
 }
m31()
qreal QTransform::m31 () const inline
Returns the horizontal translation factor.
See also
dx(), translate(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 261 of file qtransform.h.
Referenced by QRasterPaintEngine::drawImage(), QGLMaskTextureCache::hash(), mapHomogeneous(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), and QCoreGraphicsPaintEngine::updateMatrix().
 {
     return affine._dx;
 }
m32()
qreal QTransform::m32 () const inline
Returns the vertical translation factor.
See also
dy(), translate(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 265 of file qtransform.h.
Referenced by QRasterPaintEngine::drawImage(), QGLMaskTextureCache::hash(), mapHomogeneous(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), and QCoreGraphicsPaintEngine::updateMatrix().
 {
     return affine._dy;
 }
m33()
qreal QTransform::m33 () const inline
Returns the division factor.
See also
translate(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 269 of file qtransform.h.
Referenced by QGL2PaintEngineEx::beginNativePainting(), QRasterPaintEngine::drawImage(), QGLMaskTextureCache::hash(), mapHomogeneous(), needsPerspectiveClipping(), operator*(), operator*=(), operator<<(), operator>>(), qFuzzyCompare(), QMatrix4x4::QMatrix4x4(), QVGPaintEnginePrivate::setBrushTransform(), QOpenGLPaintEnginePrivate::setInvMatrixData(), QOutlineMapper::setMatrix(), setMatrix(), QVGPaintEnginePrivate::setTransform(), QGLShaderProgram::setUniformValue(), QSpanData::setupMatrix(), QCoreGraphicsPaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), and QVGPaintEnginePrivate::updateTransform().
 {
     return m_33;
 }
map() [1/10]
QPoint QTransform::map (const QPoint & point) const
Creates and returns a QPoint object that is a copy of the given point, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the transformed coordinates are rounded to the nearest integer.
Definition at line 1154 of file qtransform.cpp.
Referenced by QGraphicsItem::boundingRegion(), QSvgArc::bounds(), QSvgEllipse::bounds(), QSvgLine::bounds(), QSvgPath::bounds(), QSvgPolygon::bounds(), QSvgPolyline::bounds(), boundsOnStroke(), QRasterPaintEngine::clip(), QGraphicsItem::clipPath(), QPainter::clipRegion(), QOpenGLPaintEnginePrivate::composite(), QGLLineMaskGenerator::computeScreenRect(), QGLRectMaskGenerator::computeScreenRect(), cubicToHook(), QDeclarativeParentChangePrivate::doChange(), draw_text_item_win(), QVGPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QPaintEngine::drawPoints(), QRasterPaintEngine::drawRects(), QPdfEnginePrivate::drawTextItem(), QRasterPaintEngine::drawTiledPixmap(), QOutlineMapper::endOutline(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillRect(), QGraphicsView::fitInView(), QPdf::generatePath(), QGraphicsScenePrivate::gestureEventHandler(), QTriangulator< T >::initialize(), QGraphicsScene::inputMethodQuery(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsScenePrivate::itemsAtPosition(), QStyleOptionGraphicsItem::levelOfDetailFromTransform(), lineToHook(), QMacPixmapData::macCreatePixels(), map(), map(), QBezier::mapBy(), QGraphicsItem::mapFromItem(), QGraphicsItem::mapFromParent(), QGraphicsView::mapFromScene(), QGraphicsItem::mapFromScene(), mapProjective(), mapRect(), QGraphicsItem::mapToItem(), QGraphicsItem::mapToParent(), QGraphicsView::mapToScene(), QGraphicsViewPrivate::mapToScene(), QGraphicsItem::mapToScene(), QGraphicsItem::mouseMoveEvent(), moveToHook(), operator*(), QDeclarativePaintedItem::paint(), QVGPaintEnginePrivate::painterPathToVGPath(), QPaintBufferEngine::penChanged(), QWidgetEffectSourcePrivate::pixmap(), qt_transform_image(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QWidget::render(), roundInDeviceCoordinates(), QPaintEngineEx::stroke(), QRasterPaintEngine::stroke(), QOpenGLPaintEnginePrivate::strokePath(), glyph_metrics_t::transformed(), QImage::transformed(), QPaintEnginePrivate::transformSystemClip(), QDeclarativeParentAnimation::transition(), QWin32PrintEngine::updateClipPath(), QOpenGLPaintEnginePrivate::updateGradient(), QGraphicsViewPrivate::updateRegion(), QDeclarativeFlipablePrivate::updateSceneTransformFromParent(), QVGPaintEnginePrivate::vectorPathToVGPath(), and QPdfEnginePrivate::~QPdfEnginePrivate().
 {
     qreal fx = p.x();
     qreal fy = p.y();
     qreal x = 0, y = 0;
     TransformationType t = inline_type();
     switch(t) {
     case TxNone:
         x = fx;
         y = fy;
         break;
     case TxTranslate:
         x = fx + affine._dx;
         y = fy + affine._dy;
         break;
     case TxScale:
         x = affine._m11 * fx + affine._dx;
         y = affine._m22 * fy + affine._dy;
         break;
     case TxRotate:
     case TxShear:
     case TxProject:
         x = affine._m11 * fx + affine._m21 * fy + affine._dx;
         y = affine._m12 * fx + affine._m22 * fy + affine._dy;
         if (t == TxProject) {
             qreal w = 1./(m_13 * fx + m_23 * fy + m_33);
             x *= w;
             y *= w;
         }
     }
     return QPoint(qRound(x), qRound(y));
 }
map() [2/10]
QPointF QTransform::map (const QPointF & p) const
Creates and returns a QPointF object that is a copy of the given point, p, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1208 of file qtransform.cpp.
 {
     qreal fx = p.x();
     qreal fy = p.y();
     qreal x = 0, y = 0;
     TransformationType t = inline_type();
     switch(t) {
     case TxNone:
         x = fx;
         y = fy;
         break;
     case TxTranslate:
         x = fx + affine._dx;
         y = fy + affine._dy;
         break;
     case TxScale:
         x = affine._m11 * fx + affine._dx;
         y = affine._m22 * fy + affine._dy;
         break;
     case TxRotate:
     case TxShear:
     case TxProject:
         x = affine._m11 * fx + affine._m21 * fy + affine._dx;
         y = affine._m12 * fx + affine._m22 * fy + affine._dy;
         if (t == TxProject) {
             qreal w = 1./(m_13 * fx + m_23 * fy + m_33);
             x *= w;
             y *= w;
         }
     }
     return QPointF(x, y);
 }
map() [3/10]
QLine QTransform::map (const QLine & l) const
Creates and returns a QLineF object that is a copy of the given line, l, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1283 of file qtransform.cpp.
 {
     qreal fx1 = l.x1();
     qreal fy1 = l.y1();
     qreal fx2 = l.x2();
     qreal fy2 = l.y2();
     qreal x1 = 0, y1 = 0, x2 = 0, y2 = 0;
     TransformationType t = inline_type();
     switch(t) {
     case TxNone:
         x1 = fx1;
         y1 = fy1;
         x2 = fx2;
         y2 = fy2;
         break;
     case TxTranslate:
         x1 = fx1 + affine._dx;
         y1 = fy1 + affine._dy;
         x2 = fx2 + affine._dx;
         y2 = fy2 + affine._dy;
         break;
     case TxScale:
         x1 = affine._m11 * fx1 + affine._dx;
         y1 = affine._m22 * fy1 + affine._dy;
         x2 = affine._m11 * fx2 + affine._dx;
         y2 = affine._m22 * fy2 + affine._dy;
         break;
     case TxRotate:
     case TxShear:
     case TxProject:
         x1 = affine._m11 * fx1 + affine._m21 * fy1 + affine._dx;
         y1 = affine._m12 * fx1 + affine._m22 * fy1 + affine._dy;
         x2 = affine._m11 * fx2 + affine._m21 * fy2 + affine._dx;
         y2 = affine._m12 * fx2 + affine._m22 * fy2 + affine._dy;
         if (t == TxProject) {
             qreal w = 1./(m_13 * fx1 + m_23 * fy1 + m_33);
             x1 *= w;
             y1 *= w;
             w = 1./(m_13 * fx2 + m_23 * fy2 + m_33);
             x2 *= w;
             y2 *= w;
         }
     }
     return QLine(qRound(x1), qRound(y1), qRound(x2), qRound(y2));
 }
map() [4/10]
QLineF QTransform::map (const QLineF & line) const
Creates and returns a QLine object that is a copy of the given line, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the transformed coordinates are rounded to the nearest integer.
Definition at line 1345 of file qtransform.cpp.
 {
     qreal fx1 = l.x1();
     qreal fy1 = l.y1();
     qreal fx2 = l.x2();
     qreal fy2 = l.y2();
     qreal x1 = 0, y1 = 0, x2 = 0, y2 = 0;
     TransformationType t = inline_type();
     switch(t) {
     case TxNone:
         x1 = fx1;
         y1 = fy1;
         x2 = fx2;
         y2 = fy2;
         break;
     case TxTranslate:
         x1 = fx1 + affine._dx;
         y1 = fy1 + affine._dy;
         x2 = fx2 + affine._dx;
         y2 = fy2 + affine._dy;
         break;
     case TxScale:
         x1 = affine._m11 * fx1 + affine._dx;
         y1 = affine._m22 * fy1 + affine._dy;
         x2 = affine._m11 * fx2 + affine._dx;
         y2 = affine._m22 * fy2 + affine._dy;
         break;
     case TxRotate:
     case TxShear:
     case TxProject:
         x1 = affine._m11 * fx1 + affine._m21 * fy1 + affine._dx;
         y1 = affine._m12 * fx1 + affine._m22 * fy1 + affine._dy;
         x2 = affine._m11 * fx2 + affine._m21 * fy2 + affine._dx;
         y2 = affine._m12 * fx2 + affine._m22 * fy2 + affine._dy;
         if (t == TxProject) {
             qreal w = 1./(m_13 * fx1 + m_23 * fy1 + m_33);
             x1 *= w;
             y1 *= w;
             w = 1./(m_13 * fx2 + m_23 * fy2 + m_33);
             x2 *= w;
             y2 *= w;
         }
     }
     return QLineF(x1, y1, x2, y2);
 }
map() [5/10]
QPolygonF QTransform::map (const QPolygonF & polygon) const
Creates and returns a QPolygonF object that is a copy of the given polygon, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1443 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     if (t <= TxTranslate)
         return a.translated(affine._dx, affine._dy);
     if (t >= QTransform::TxProject)
         return mapProjective(*this, a);
     int size = a.size();
     int i;
     QPolygonF p(size);
     const QPointF *da = a.constData();
     QPointF *dp = p.data();
     for(i = 0; i < size; ++i) {
         MAP(da[i].xp, da[i].yp, dp[i].xp, dp[i].yp);
     }
     return p;
 }
map() [6/10]
QPolygon QTransform::map (const QPolygon & polygon) const
Creates and returns a QPolygon object that is a copy of the given polygon, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the transformed coordinates are rounded to the nearest integer.
Definition at line 1476 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     if (t <= TxTranslate)
         return a.translated(qRound(affine._dx), qRound(affine._dy));
     if (t >= QTransform::TxProject)
         return mapProjective(*this, QPolygonF(a)).toPolygon();
     int size = a.size();
     int i;
     QPolygon p(size);
     const QPoint *da = a.constData();
     QPoint *dp = p.data();
     for(i = 0; i < size; ++i) {
         qreal nx = 0, ny = 0;
         MAP(da[i].xp, da[i].yp, nx, ny);
         dp[i].xp = qRound(nx);
         dp[i].yp = qRound(ny);
     }
     return p;
 }
map() [7/10]
QRegion QTransform::map (const QRegion & region) const
Creates and returns a QRegion object that is a copy of the given region, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Calling this method can be rather expensive if rotations or shearing are used.
Definition at line 1524 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     if (t == TxNone)
         return r;
     if (t == TxTranslate) {
         QRegion copy(r);
         copy.translate(qRound(affine._dx), qRound(affine._dy));
         return copy;
     }
     if (t == TxScale && r.rectCount() == 1)
         return QRegion(mapRect(r.boundingRect()));
     QPainterPath p = map(qt_regionToPath(r));
     return p.toFillPolygon(QTransform()).toPolygon();
 }
map() [8/10]
QPainterPath QTransform::map (const QPainterPath & path) const
Creates and returns a QPainterPath object that is a copy of the given path, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1687 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     if (t == TxNone || path.elementCount() == 0)
         return path;
     if (t >= TxProject)
         return mapProjective(*this, path);
     QPainterPath copy = path;
     if (t == TxTranslate) {
         copy.translate(affine._dx, affine._dy);
     } else {
         copy.detach();
         // Full xform
         for (int i=0; i<path.elementCount(); ++i) {
             QPainterPath::Element &e = copy.d_ptr->elements[i];
             MAP(e.x, e.y, e.x, e.y);
         }
     }
     return copy;
 }
map() [9/10]
void QTransform::map (int x, int y, int * tx, int * ty) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Maps the given coordinates x and y into the coordinate system defined by this matrix.
The resulting values are put in *tx and *ty, respectively. Note that the transformed coordinates are rounded to the nearest integer.
Definition at line 2084 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     qreal fx = 0, fy = 0;
     MAP(x, y, fx, fy);
     *tx = qRound(fx);
     *ty = qRound(fy);
 }
map() [10/10]
void QTransform::map (qreal x, qreal y, qreal * tx, qreal * ty) const
Maps the given coordinates x and y into the coordinate system defined by this matrix.
The resulting values are put in *tx and *ty, respectively.
The coordinates are transformed using the following formulas:
x' = m11*x + m21*y + dx
y' = m22*y + m12*x + dy
if (is not affine) {
    w' = m13*x + m23*y + m33
    x' /= w'
    y' /= w'
}
The point (x, y) is the original point, and (x', y') is the transformed point.
See also
{QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 2070 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     MAP(x, y, *tx, *ty);
 }
mapRect() [1/2]
QRect QTransform::mapRect (const QRect & rectangle) const
Creates and returns a QRect object that is a copy of the given rectangle, mapped into the coordinate system defined by this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note that the transformed coordinates are rounded to the nearest integer.
Definition at line 1920 of file qtransform.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QDirectFBPaintEnginePrivate::blit(), QGraphicsItem::boundingRegion(), QSvgImage::bounds(), QSvgRect::bounds(), QGraphicsItemPrivate::childrenBoundingRectHelper(), QGL2PaintEngineEx::clip(), QRasterPaintEngine::clip(), QPainter::clipBoundingRect(), QPainter::clipRegion(), QStyleSheetStyle::drawControl(), QRasterPaintEngine::drawEllipse(), QDirectFBPaintEngine::drawImage(), QRasterPaintEngine::drawImage(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsScenePrivate::drawItems(), QBlitterPaintEngine::drawPixmap(), QDirectFBPaintEngine::drawPixmap(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsItem::ensureVisible(), QRasterPaintEngine::fill(), QRasterPaintEngine::fillPath(), QBlitterPaintEngine::fillRect(), QDirectFBPaintEngine::fillRect(), QRasterPaintEngine::fillRect(), QGraphicsItemPrivate::initStyleOption(), QGraphicsScene::inputMethodQuery(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QOpenGLPaintEnginePrivate::isFastRect(), QGraphicsView::items(), QGraphicsScenePrivate::itemsAtPosition(), map(), map(), QGraphicsItem::mapRectFromItem(), QGraphicsItem::mapRectFromParent(), QGraphicsViewPrivate::mapRectFromScene(), QGraphicsItem::mapRectFromScene(), QGraphicsItem::mapRectToItem(), QGraphicsItem::mapRectToParent(), QGraphicsViewPrivate::mapRectToScene(), QGraphicsItem::mapRectToScene(), QSvgTinyDocument::mapSourceToTarget(), QGraphicsViewPrivate::mapToViewRect(), QGraphicsViewPrivate::mapToViewRegion(), QDeclarativePaintedItem::paint(), QBlittablePixmapData::paintEngine(), QGraphicsView::paintEvent(), QWidgetEffectSourcePrivate::pixmap(), QGraphicsItem::prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QWin32PrintEngine::property(), qt_graphicsItem_highlightSelected(), qt_true_matrix(), QSvgIOHandler::read(), QGraphicsViewPrivate::recalculateContentSize(), QWidgetPrivate::render_helper(), QGL2PaintEngineExPrivate::resetClipIfNeeded(), QGraphicsItem::sceneBoundingRect(), QGraphicsItemPrivate::sceneEffectiveBoundingRect(), QGLEllipseMaskGenerator::screenRect(), QGraphicsViewPrivate::setUpdateClip(), QPaintEngineEx::stroke(), QDirectFBPixmapData::transformed(), glyph_metrics_t::transformed(), QImage::trueMatrix(), QGraphicsScene::update(), QPaintBufferPrivate::updateBoundingRect(), updateHelper(), QRasterPaintEngine::updatePen(), QGraphicsViewPrivate::updateRegion(), QGraphicsView::updateScene(), and QPicturePaintEngine::writeCmdLength().
 {
     TransformationType t = inline_type();
     if (t <= TxTranslate)
         return rect.translated(qRound(affine._dx), qRound(affine._dy));
     if (t <= TxScale) {
         int x = qRound(affine._m11*rect.x() + affine._dx);
         int y = qRound(affine._m22*rect.y() + affine._dy);
         int w = qRound(affine._m11*rect.width());
         int h = qRound(affine._m22*rect.height());
         if (w < 0) {
             w = -w;
             x -= w;
         }
         if (h < 0) {
             h = -h;
             y -= h;
         }
         return QRect(x, y, w, h);
     } else if (t < TxProject || !needsPerspectiveClipping(rect, *this)) {
         // see mapToPolygon for explanations of the algorithm.
         qreal x = 0, y = 0;
         MAP(rect.left(), rect.top(), x, y);
         qreal xmin = x;
         qreal ymin = y;
         qreal xmax = x;
         qreal ymax = y;
         MAP(rect.right() + 1, rect.top(), x, y);
         xmin = qMin(xmin, x);
         ymin = qMin(ymin, y);
         xmax = qMax(xmax, x);
         ymax = qMax(ymax, y);
         MAP(rect.right() + 1, rect.bottom() + 1, x, y);
         xmin = qMin(xmin, x);
         ymin = qMin(ymin, y);
         xmax = qMax(xmax, x);
         ymax = qMax(ymax, y);
         MAP(rect.left(), rect.bottom() + 1, x, y);
         xmin = qMin(xmin, x);
         ymin = qMin(ymin, y);
         xmax = qMax(xmax, x);
         ymax = qMax(ymax, y);
         return QRect(qRound(xmin), qRound(ymin), qRound(xmax)-qRound(xmin), qRound(ymax)-qRound(ymin));
     } else {
         QPainterPath path;
         path.addRect(rect);
         return map(path).boundingRect().toRect();
     }
 }
mapRect() [2/2]
QRectF QTransform::mapRect (const QRectF & rectangle) const
Creates and returns a QRectF object that is a copy of the given rectangle, mapped into the coordinate system defined by this matrix.
The rectangle's coordinates are transformed using the following formulas:
x' = m11*x + m21*y + dx
y' = m22*y + m12*x + dy
if (is not affine) {
    w' = m13*x + m23*y + m33
    x' /= w'
    y' /= w'
}
If rotation or shearing has been specified, this function returns the bounding rectangle. To retrieve the exact region the given rectangle maps to, use the mapToPolygon() function instead.
See also
mapToPolygon(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 1993 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     if (t <= TxTranslate)
         return rect.translated(affine._dx, affine._dy);
     if (t <= TxScale) {
         qreal x = affine._m11*rect.x() + affine._dx;
         qreal y = affine._m22*rect.y() + affine._dy;
         qreal w = affine._m11*rect.width();
         qreal h = affine._m22*rect.height();
         if (w < 0) {
             w = -w;
             x -= w;
         }
         if (h < 0) {
             h = -h;
             y -= h;
         }
         return QRectF(x, y, w, h);
     } else if (t < TxProject || !needsPerspectiveClipping(rect, *this)) {
         qreal x = 0, y = 0;
         MAP(rect.x(), rect.y(), x, y);
         qreal xmin = x;
         qreal ymin = y;
         qreal xmax = x;
         qreal ymax = y;
         MAP(rect.x() + rect.width(), rect.y(), x, y);
         xmin = qMin(xmin, x);
         ymin = qMin(ymin, y);
         xmax = qMax(xmax, x);
         ymax = qMax(ymax, y);
         MAP(rect.x() + rect.width(), rect.y() + rect.height(), x, y);
         xmin = qMin(xmin, x);
         ymin = qMin(ymin, y);
         xmax = qMax(xmax, x);
         ymax = qMax(ymax, y);
         MAP(rect.x(), rect.y() + rect.height(), x, y);
         xmin = qMin(xmin, x);
         ymin = qMin(ymin, y);
         xmax = qMax(xmax, x);
         ymax = qMax(ymax, y);
         return QRectF(xmin, ymin, xmax-xmin, ymax - ymin);
     } else {
         QPainterPath path;
         path.addRect(rect);
         return map(path).boundingRect();
     }
 }
mapToPolygon()
QPolygon QTransform::mapToPolygon (const QRect & rectangle) const
Creates and returns a QPolygon representation of the given rectangle, mapped into the coordinate system defined by this matrix.
The rectangle's coordinates are transformed using the following formulas:
x' = m11*x + m21*y + dx
y' = m22*y + m12*x + dy
if (is not affine) {
    w' = m13*x + m23*y + m33
    x' /= w'
    y' /= w'
}
Polygons and rectangles behave slightly differently when transformed (due to integer rounding), so matrix.map(QPolygon(rectangle)) is not always the same as matrix.mapToPolygon(rectangle).
See also
mapRect(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 1735 of file qtransform.cpp.
 {
     TransformationType t = inline_type();
     QPolygon a(4);
     qreal x[4] = { 0, 0, 0, 0 }, y[4] = { 0, 0, 0, 0 };
     if (t <= TxScale) {
         x[0] = affine._m11*rect.x() + affine._dx;
         y[0] = affine._m22*rect.y() + affine._dy;
         qreal w = affine._m11*rect.width();
         qreal h = affine._m22*rect.height();
         if (w < 0) {
             w = -w;
             x[0] -= w;
         }
         if (h < 0) {
             h = -h;
             y[0] -= h;
         }
         x[1] = x[0]+w;
         x[2] = x[1];
         x[3] = x[0];
         y[1] = y[0];
         y[2] = y[0]+h;
         y[3] = y[2];
     } else {
         qreal right = rect.x() + rect.width();
         qreal bottom = rect.y() + rect.height();
         MAP(rect.x(), rect.y(), x[0], y[0]);
         MAP(right, rect.y(), x[1], y[1]);
         MAP(right, bottom, x[2], y[2]);
         MAP(rect.x(), bottom, x[3], y[3]);
     }
     // all coordinates are correctly, tranform to a pointarray
     // (rounding to the next integer)
     a.setPoints(4, qRound(x[0]), qRound(y[0]),
                 qRound(x[1]), qRound(y[1]),
                 qRound(x[2]), qRound(y[2]),
                 qRound(x[3]), qRound(y[3]));
     return a;
 }
operator QVariant()
QTransform::operator QVariant () const
Returns the transform as a QVariant.
Definition at line 2160 of file qtransform.cpp.
 {
     return QVariant(QVariant::Transform, this);
 }
operator!=()
bool QTransform::operator!= (const QTransform & matrix) const
Returns true if this matrix is not equal to the given matrix, otherwise returns false.
Definition at line 804 of file qtransform.cpp.
 {
     return !operator==(o);
 }
operator*()
QTransform QTransform::operator* (const QTransform & matrix) const
Returns the result of multiplying this matrix by the given matrix.
Note that matrix multiplication is not commutative, i.e. a*b != b*a.
Definition at line 898 of file qtransform.cpp.
 {
     const TransformationType otherType = m.inline_type();
     if (otherType == TxNone)
         return *this;
     const TransformationType thisType = inline_type();
     if (thisType == TxNone)
         return m;
     QTransform t(true);
     TransformationType type = qMax(thisType, otherType);
     switch(type) {
     case TxNone:
         break;
     case TxTranslate:
         t.affine._dx = affine._dx + m.affine._dx;
         t.affine._dy += affine._dy + m.affine._dy;
         break;
     case TxScale:
     {
         qreal m11 = affine._m11*m.affine._m11;
         qreal m22 = affine._m22*m.affine._m22;
         qreal m31 = affine._dx*m.affine._m11 + m.affine._dx;
         qreal m32 = affine._dy*m.affine._m22 + m.affine._dy;
         t.affine._m11 = m11;
         t.affine._m22 = m22;
         t.affine._dx = m31; t.affine._dy = m32;
         break;
     }
     case TxRotate:
     case TxShear:
     {
         qreal m11 = affine._m11*m.affine._m11 + affine._m12*m.affine._m21;
         qreal m12 = affine._m11*m.affine._m12 + affine._m12*m.affine._m22;
         qreal m21 = affine._m21*m.affine._m11 + affine._m22*m.affine._m21;
         qreal m22 = affine._m21*m.affine._m12 + affine._m22*m.affine._m22;
         qreal m31 = affine._dx*m.affine._m11 + affine._dy*m.affine._m21 + m.affine._dx;
         qreal m32 = affine._dx*m.affine._m12 + affine._dy*m.affine._m22 + m.affine._dy;
         t.affine._m11 = m11; t.affine._m12 = m12;
         t.affine._m21 = m21; t.affine._m22 = m22;
         t.affine._dx = m31; t.affine._dy = m32;
         break;
     }
     case TxProject:
     {
         qreal m11 = affine._m11*m.affine._m11 + affine._m12*m.affine._m21 + m_13*m.affine._dx;
         qreal m12 = affine._m11*m.affine._m12 + affine._m12*m.affine._m22 + m_13*m.affine._dy;
         qreal m13 = affine._m11*m.m_13 + affine._m12*m.m_23 + m_13*m.m_33;
         qreal m21 = affine._m21*m.affine._m11 + affine._m22*m.affine._m21 + m_23*m.affine._dx;
         qreal m22 = affine._m21*m.affine._m12 + affine._m22*m.affine._m22 + m_23*m.affine._dy;
         qreal m23 = affine._m21*m.m_13 + affine._m22*m.m_23 + m_23*m.m_33;
         qreal m31 = affine._dx*m.affine._m11 + affine._dy*m.affine._m21 + m_33*m.affine._dx;
         qreal m32 = affine._dx*m.affine._m12 + affine._dy*m.affine._m22 + m_33*m.affine._dy;
         qreal m33 = affine._dx*m.m_13 + affine._dy*m.m_23 + m_33*m.m_33;
         t.affine._m11 = m11; t.affine._m12 = m12; t.m_13 = m13;
         t.affine._m21 = m21; t.affine._m22 = m22; t.m_23 = m23;
         t.affine._dx = m31; t.affine._dy = m32; t.m_33 = m33;
     }
     }
     t.m_dirty = type;
     t.m_type = type;
     return t;
 }
operator*=() [1/2]
QTransform & QTransform::operator*= (const QTransform & matrix)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the result of multiplying this matrix by the given matrix.
Definition at line 816 of file qtransform.cpp.
 {
     const TransformationType otherType = o.inline_type();
     if (otherType == TxNone)
         return *this;
     const TransformationType thisType = inline_type();
     if (thisType == TxNone)
         return operator=(o);
     TransformationType t = qMax(thisType, otherType);
     switch(t) {
     case TxNone:
         break;
     case TxTranslate:
         affine._dx += o.affine._dx;
         affine._dy += o.affine._dy;
         break;
     case TxScale:
     {
         qreal m11 = affine._m11*o.affine._m11;
         qreal m22 = affine._m22*o.affine._m22;
         qreal m31 = affine._dx*o.affine._m11 + o.affine._dx;
         qreal m32 = affine._dy*o.affine._m22 + o.affine._dy;
         affine._m11 = m11;
         affine._m22 = m22;
         affine._dx = m31; affine._dy = m32;
         break;
     }
     case TxRotate:
     case TxShear:
     {
         qreal m11 = affine._m11*o.affine._m11 + affine._m12*o.affine._m21;
         qreal m12 = affine._m11*o.affine._m12 + affine._m12*o.affine._m22;
         qreal m21 = affine._m21*o.affine._m11 + affine._m22*o.affine._m21;
         qreal m22 = affine._m21*o.affine._m12 + affine._m22*o.affine._m22;
         qreal m31 = affine._dx*o.affine._m11 + affine._dy*o.affine._m21 + o.affine._dx;
         qreal m32 = affine._dx*o.affine._m12 + affine._dy*o.affine._m22 + o.affine._dy;
         affine._m11 = m11; affine._m12 = m12;
         affine._m21 = m21; affine._m22 = m22;
         affine._dx = m31; affine._dy = m32;
         break;
     }
     case TxProject:
     {
         qreal m11 = affine._m11*o.affine._m11 + affine._m12*o.affine._m21 + m_13*o.affine._dx;
         qreal m12 = affine._m11*o.affine._m12 + affine._m12*o.affine._m22 + m_13*o.affine._dy;
         qreal m13 = affine._m11*o.m_13 + affine._m12*o.m_23 + m_13*o.m_33;
         qreal m21 = affine._m21*o.affine._m11 + affine._m22*o.affine._m21 + m_23*o.affine._dx;
         qreal m22 = affine._m21*o.affine._m12 + affine._m22*o.affine._m22 + m_23*o.affine._dy;
         qreal m23 = affine._m21*o.m_13 + affine._m22*o.m_23 + m_23*o.m_33;
         qreal m31 = affine._dx*o.affine._m11 + affine._dy*o.affine._m21 + m_33*o.affine._dx;
         qreal m32 = affine._dx*o.affine._m12 + affine._dy*o.affine._m22 + m_33*o.affine._dy;
         qreal m33 = affine._dx*o.m_13 + affine._dy*o.m_23 + m_33*o.m_33;
         affine._m11 = m11; affine._m12 = m12; m_13 = m13;
         affine._m21 = m21; affine._m22 = m22; m_23 = m23;
         affine._dx = m31; affine._dy = m32; m_33 = m33;
     }
     }
     m_dirty = t;
     m_type = t;
     return *this;
 }
operator*=() [2/2]
QTransform & QTransform::operator*= (qreal div) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns the result of performing an element-wise multiplication of this matrix with the given scalar.
Definition at line 282 of file qtransform.h.
 {
     if (num == 1.)
         return *this;
     affine._m11 *= num;
     affine._m12 *= num;
     m_13        *= num;
     affine._m21 *= num;
     affine._m22 *= num;
     m_23        *= num;
     affine._dx  *= num;
     affine._dy  *= num;
     m_33        *= num;
     if (m_dirty < TxScale)
         m_dirty = TxScale;
     return *this;
 }
operator+=()
QTransform & QTransform::operator+= (qreal scalar) inline
Returns the matrix obtained by adding the given scalar to each element of this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 306 of file qtransform.h.
 {
     if (num == 0)
         return *this;
     affine._m11 += num;
     affine._m12 += num;
     m_13        += num;
     affine._m21 += num;
     affine._m22 += num;
     m_23        += num;
     affine._dx  += num;
     affine._dy  += num;
     m_33        += num;
     m_dirty     = TxProject;
     return *this;
 }
operator-=()
QTransform & QTransform::operator-= (qreal scalar) inline
Returns the matrix obtained by subtracting the given scalar from each element of this matrix.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 322 of file qtransform.h.
 {
     if (num == 0)
         return *this;
     affine._m11 -= num;
     affine._m12 -= num;
     m_13        -= num;
     affine._m21 -= num;
     affine._m22 -= num;
     m_23        -= num;
     affine._dx  -= num;
     affine._dy  -= num;
     m_33        -= num;
     m_dirty     = TxProject;
     return *this;
 }
operator/=()
QTransform & QTransform::operator/= (qreal scalar) inline
Returns the result of performing an element-wise division of this matrix by the given scalar.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 299 of file qtransform.h.
 {
     if (div == 0)
         return *this;
     div = 1/div;
     return operator*=(div);
 }
operator=()
QTransform & QTransform::operator= (const QTransform & matrix)
Assigns the given matrix's values to this matrix.
Definition at line 1017 of file qtransform.cpp.
Referenced by operator*=().
 {
     affine._m11 = matrix.affine._m11;
     affine._m12 = matrix.affine._m12;
     affine._m21 = matrix.affine._m21;
     affine._m22 = matrix.affine._m22;
     affine._dx = matrix.affine._dx;
     affine._dy = matrix.affine._dy;
     m_13 = matrix.m_13;
     m_23 = matrix.m_23;
     m_33 = matrix.m_33;
     m_type = matrix.m_type;
     m_dirty = matrix.m_dirty;
     return *this;
 }
operator==()
bool QTransform::operator== (const QTransform & matrix) const
Returns true if this matrix is equal to the given matrix, otherwise returns false.
Definition at line 783 of file qtransform.cpp.
Referenced by operator!=().
 {
     return affine._m11 == o.affine._m11 &&
            affine._m12 == o.affine._m12 &&
            affine._m21 == o.affine._m21 &&
            affine._m22 == o.affine._m22 &&
            affine._dx == o.affine._dx &&
            affine._dy == o.affine._dy &&
            m_13 == o.m_13 &&
            m_23 == o.m_23 &&
            m_33 == o.m_33;
 }
quadToQuad()
bool QTransform::quadToQuad (const QPolygonF & one, const QPolygonF & two, QTransform & trans) static
Creates a transformation matrix, trans, that maps a four-sided polygon, one, to another four-sided polygon, two.
Returns true if the transformation is possible; otherwise returns false.
This is a convenience method combining quadToSquare() and squareToQuad() methods. It allows the input quad to be transformed into any other quad.
See also
squareToQuad(), quadToSquare()
Definition at line 1876 of file qtransform.cpp.
 {
     QTransform stq;
     if (!quadToSquare(one, trans))
         return false;
     if (!squareToQuad(two, stq))
         return false;
     trans *= stq;
     //qDebug()<<"Final = "<<trans;
     return true;
 }
quadToSquare()
bool QTransform::quadToSquare (const QPolygonF & quad, QTransform & trans) static
Creates a transformation matrix, trans, that maps a four-sided polygon, quad, to a unit square.
Returns true if the transformation is constructed or false if such a transformation does not exist.
See also
squareToQuad(), quadToQuad()
Definition at line 1853 of file qtransform.cpp.
Referenced by quadToQuad().
 {
     if (!squareToQuad(quad, trans))
         return false;
     bool invertible = false;
     trans = trans.inverted(&invertible);
     return invertible;
 }
reset()
void QTransform::reset ()
Resets the matrix to an identity matrix, i.e.
all elements are set to zero, except m11 and m22 (specifying the scale) and m33 which are set to 1.
See also
QTransform(), isIdentity(), {QTransform::Basic Matrix Operations}{Basic Matrix Operations}
Definition at line 1042 of file qtransform.cpp.
Referenced by QPainterState::init().
 {
     affine._m11 = affine._m22 = m_33 = 1.0;
     affine._m12 = m_13 = affine._m21 = m_23 = affine._dx = affine._dy = 0;
     m_type = TxNone;
     m_dirty = TxNone;
 }
rotate()
QTransform & QTransform::rotate (qreal angle, Qt::Axis axis = Qt::ZAxis)
Rotates the coordinate system counterclockwise by the given angle about the specified axis and returns a reference to the matrix.
Note that if you apply a QTransform to a point defined in widget coordinates, the direction of the rotation will be clockwise because the y-axis points downwards.
The angle is specified in degrees.
See also
setMatrix()
Definition at line 615 of file qtransform.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsItemPrivate::TransformData::computedFullTransform(), QDeclarativeParentChangePrivate::doChange(), QCommonStyle::drawControl(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QGtkStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QEmulationPaintEngine::drawPixmapFragments(), QVGPaintEngine::drawPixmapFragments(), QPaintEngineEx::drawPixmapFragments(), QPainter::drawPixmapFragments(), QWindowsMobileStylePrivate::drawScrollbarGrip(), QWindowsMobileStylePrivate::drawScrollbarHandleDown(), QWindowsMobileStylePrivate::drawScrollbarHandleUp(), qDrawPlainRect(), QGraphicsItemGroup::removeFromGroup(), QSvgAnimateTransform::resolveMatrix(), QGraphicsView::rotate(), QDeclarativeFlipablePrivate::setBackTransform(), and QDeclarativeParentAnimation::transition().
 {
     if (a == 0)
         return *this;
 #ifndef QT_NO_DEBUG
     if (qIsNaN(a)) {
         qWarning() << "QTransform::rotate with NaN called";
         return *this;
     }
 #endif
     qreal sina = 0;
     qreal cosa = 0;
     if (a == 90. || a == -270.)
         sina = 1.;
     else if (a == 270. || a == -90.)
         sina = -1.;
     else if (a == 180.)
         cosa = -1.;
     else{
         qreal b = deg2rad*a;          // convert to radians
         sina = qSin(b);               // fast and convenient
         cosa = qCos(b);
     }
     if (axis == Qt::ZAxis) {
         switch(inline_type()) {
         case TxNone:
         case TxTranslate:
             affine._m11 = cosa;
             affine._m12 = sina;
             affine._m21 = -sina;
             affine._m22 = cosa;
             break;
         case TxScale: {
             qreal tm11 = cosa*affine._m11;
             qreal tm12 = sina*affine._m22;
             qreal tm21 = -sina*affine._m11;
             qreal tm22 = cosa*affine._m22;
             affine._m11 = tm11; affine._m12 = tm12;
             affine._m21 = tm21; affine._m22 = tm22;
             break;
         }
         case TxProject: {
             qreal tm13 = cosa*m_13 + sina*m_23;
             qreal tm23 = -sina*m_13 + cosa*m_23;
             m_13 = tm13;
             m_23 = tm23;
             // fall through
         }
         case TxRotate:
         case TxShear: {
             qreal tm11 = cosa*affine._m11 + sina*affine._m21;
             qreal tm12 = cosa*affine._m12 + sina*affine._m22;
             qreal tm21 = -sina*affine._m11 + cosa*affine._m21;
             qreal tm22 = -sina*affine._m12 + cosa*affine._m22;
             affine._m11 = tm11; affine._m12 = tm12;
             affine._m21 = tm21; affine._m22 = tm22;
             break;
         }
         }
         if (m_dirty < TxRotate)
             m_dirty = TxRotate;
     } else {
         QTransform result;
         if (axis == Qt::YAxis) {
             result.affine._m11 = cosa;
             result.m_13 = -sina * inv_dist_to_plane;
         } else {
             result.affine._m22 = cosa;
             result.m_23 = -sina * inv_dist_to_plane;
         }
         result.m_type = TxProject;
         *this = result * *this;
     }
     return *this;
 }
rotateRadians()
QTransform & QTransform::rotateRadians (qreal angle, Qt::Axis axis = Qt::ZAxis)
Rotates the coordinate system counterclockwise by the given angle about the specified axis and returns a reference to the matrix.
Note that if you apply a QTransform to a point defined in widget coordinates, the direction of the rotation will be clockwise because the y-axis points downwards.
The angle is specified in radians.
See also
setMatrix()
Definition at line 711 of file qtransform.cpp.
 {
 #ifndef QT_NO_DEBUG
     if (qIsNaN(a)) {
         qWarning() << "QTransform::rotateRadians with NaN called";
         return *this;
     }
 #endif
     qreal sina = qSin(a);
     qreal cosa = qCos(a);
     if (axis == Qt::ZAxis) {
         switch(inline_type()) {
         case TxNone:
         case TxTranslate:
             affine._m11 = cosa;
             affine._m12 = sina;
             affine._m21 = -sina;
             affine._m22 = cosa;
             break;
         case TxScale: {
             qreal tm11 = cosa*affine._m11;
             qreal tm12 = sina*affine._m22;
             qreal tm21 = -sina*affine._m11;
             qreal tm22 = cosa*affine._m22;
             affine._m11 = tm11; affine._m12 = tm12;
             affine._m21 = tm21; affine._m22 = tm22;
             break;
         }
         case TxProject: {
             qreal tm13 = cosa*m_13 + sina*m_23;
             qreal tm23 = -sina*m_13 + cosa*m_23;
             m_13 = tm13;
             m_23 = tm23;
             // fall through
         }
         case TxRotate:
         case TxShear: {
             qreal tm11 = cosa*affine._m11 + sina*affine._m21;
             qreal tm12 = cosa*affine._m12 + sina*affine._m22;
             qreal tm21 = -sina*affine._m11 + cosa*affine._m21;
             qreal tm22 = -sina*affine._m12 + cosa*affine._m22;
             affine._m11 = tm11; affine._m12 = tm12;
             affine._m21 = tm21; affine._m22 = tm22;
             break;
         }
         }
         if (m_dirty < TxRotate)
             m_dirty = TxRotate;
     } else {
         QTransform result;
         if (axis == Qt::YAxis) {
             result.affine._m11 = cosa;
             result.m_13 = -sina * inv_dist_to_plane;
         } else {
             result.affine._m22 = cosa;
             result.m_23 = -sina * inv_dist_to_plane;
         }
         result.m_type = TxProject;
         *this = result * *this;
     }
     return *this;
 }
scale()
QTransform & QTransform::scale (qreal sx, qreal sy)
Scales the coordinate system by sx horizontally and sy vertically, and returns a reference to the matrix.
See also
setMatrix()
Definition at line 485 of file qtransform.cpp.
Referenced by QPrintPreviewWidgetPrivate::_q_fit(), QGraphicsItemGroup::addToGroup(), QGraphicsItemPrivate::TransformData::computedFullTransform(), cubicTo_clipped(), QDeclarativeParentChangePrivate::doChange(), QAlphaPaintEnginePrivate::drawAlphaImage(), QVGPaintEngine::drawCachedGlyphs(), QCleanlooksStyle::drawControl(), QRasterPaintEngine::drawImage(), QOpenGLPaintEnginePrivate::drawImageAsPath(), QGraphicsScenePrivate::drawItemHelper(), QVGPaintEngine::drawPixmapFragments(), QEmulationPaintEngine::drawTextItem(), QOpenGLPaintEnginePrivate::drawTiledImageAsPath(), drawVGImage(), QPicture::exec(), QEmulationPaintEngine::fill(), fillBackground(), QAlphaPaintEngine::flushAndInit(), lineTo_clipped(), QSvgTinyDocument::mapSourceToTarget(), QmlJSDebugger::ZoomTool::mouseReleaseEvent(), QDeclarativeImage::paint(), QSvgIOHandler::read(), QGraphicsItemGroup::removeFromGroup(), QSvgAnimateTransform::resolveMatrix(), QGraphicsView::scale(), QmlJSDebugger::ZoomTool::scaleView(), QPainterReplayer::setupTransform(), QEmulationPaintEngine::stroke(), and QDeclarativeParentAnimation::transition().
 {
     if (sx == 1 && sy == 1)
         return *this;
 #ifndef QT_NO_DEBUG
     if (qIsNaN(sx) | qIsNaN(sy)) {
         qWarning() << "QTransform::scale with NaN called";
         return *this;
     }
 #endif
     switch(inline_type()) {
     case TxNone:
     case TxTranslate:
         affine._m11 = sx;
         affine._m22 = sy;
         break;
     case TxProject:
         m_13 *= sx;
         m_23 *= sy;
         // fall through
     case TxRotate:
     case TxShear:
         affine._m12 *= sx;
         affine._m21 *= sy;
         // fall through
     case TxScale:
         affine._m11 *= sx;
         affine._m22 *= sy;
         break;
     }
     if (m_dirty < TxScale)
         m_dirty = TxScale;
     return *this;
 }
setMatrix()
void QTransform::setMatrix (qreal m11, qreal m12, qreal m13, qreal m21, qreal m22, qreal m23, qreal m31, qreal m32, qreal m33)
Sets the matrix elements to the specified values, m11, m12, m13 m21, m22, m23 m31, m32 and m33.
Note that this function replaces the previous values. QTransform provides the translate(), rotate(), scale() and shear() convenience functions to manipulate the various matrix elements based on the currently defined coordinate system.
See also
QTransform()
Definition at line 1901 of file qtransform.cpp.
Referenced by operator>>(), and squareToQuad().
 {
     affine._m11 = m11; affine._m12 = m12; m_13 = m13;
     affine._m21 = m21; affine._m22 = m22; m_23 = m23;
     affine._dx = m31; affine._dy = m32; m_33 = m33;
     m_type = TxNone;
     m_dirty = TxProject;
 }
shear()
QTransform & QTransform::shear (qreal sh, qreal sv)
Shears the coordinate system by sh horizontally and sv vertically, and returns a reference to the matrix.
See also
setMatrix()
Definition at line 551 of file qtransform.cpp.
Referenced by QSvgAnimateTransform::resolveMatrix(), and QGraphicsView::shear().
 {
     if (sh == 0 && sv == 0)
         return *this;
 #ifndef QT_NO_DEBUG
     if (qIsNaN(sh) | qIsNaN(sv)) {
         qWarning() << "QTransform::shear with NaN called";
         return *this;
     }
 #endif
     switch(inline_type()) {
     case TxNone:
     case TxTranslate:
         affine._m12 = sv;
         affine._m21 = sh;
         break;
     case TxScale:
         affine._m12 = sv*affine._m22;
         affine._m21 = sh*affine._m11;
         break;
     case TxProject: {
         qreal tm13 = sv*m_23;
         qreal tm23 = sh*m_13;
         m_13 += tm13;
         m_23 += tm23;
     }
         // fall through
     case TxRotate:
     case TxShear: {
         qreal tm11 = sv*affine._m21;
         qreal tm22 = sh*affine._m12;
         qreal tm12 = sv*affine._m22;
         qreal tm21 = sh*affine._m11;
         affine._m11 += tm11; affine._m12 += tm12;
         affine._m21 += tm21; affine._m22 += tm22;
         break;
     }
     }
     if (m_dirty < TxShear)
         m_dirty = TxShear;
     return *this;
 }
squareToQuad()
bool QTransform::squareToQuad (const QPolygonF & quad, QTransform & trans) static
Creates a transformation matrix, trans, that maps a unit square to a four-sided polygon, quad.
Returns true if the transformation is constructed or false if such a transformation does not exist.
See also
quadToSquare(), quadToQuad()
Definition at line 1785 of file qtransform.cpp.
Referenced by quadToQuad(), and quadToSquare().
 {
     if (quad.count() != 4)
         return false;
     qreal dx0 = quad[0].x();
     qreal dx1 = quad[1].x();
     qreal dx2 = quad[2].x();
     qreal dx3 = quad[3].x();
     qreal dy0 = quad[0].y();
     qreal dy1 = quad[1].y();
     qreal dy2 = quad[2].y();
     qreal dy3 = quad[3].y();
     double ax  = dx0 - dx1 + dx2 - dx3;
     double ay  = dy0 - dy1 + dy2 - dy3;
     if (!ax && !ay) { //afine transform
         trans.setMatrix(dx1 - dx0, dy1 - dy0,  0,
                         dx2 - dx1, dy2 - dy1,  0,
                         dx0,       dy0,  1);
     } else {
         double ax1 = dx1 - dx2;
         double ax2 = dx3 - dx2;
         double ay1 = dy1 - dy2;
         double ay2 = dy3 - dy2;
         /*determinants */
         double gtop    =  ax  * ay2 - ax2 * ay;
         double htop    =  ax1 * ay  - ax  * ay1;
         double bottom  =  ax1 * ay2 - ax2 * ay1;
         double a, b, c, d, e, f, g, h;  /*i is always 1*/
         if (!bottom)
             return false;
         g = gtop/bottom;
         h = htop/bottom;
         a = dx1 - dx0 + g * dx1;
         b = dx3 - dx0 + h * dx3;
         c = dx0;
         d = dy1 - dy0 + g * dy1;
         e = dy3 - dy0 + h * dy3;
         f = dy0;
         trans.setMatrix(a, d, g,
                         b, e, h,
                         c, f, 1.0);
     }
     return true;
 }
toAffine()
const QMatrix & QTransform::toAffine () const
Returns the QTransform as an affine matrix.
Warning
If a perspective transformation has been specified, then the conversion will cause loss of data.
Definition at line 2099 of file qtransform.cpp.
Referenced by QPainter::combinedMatrix(), QGraphicsItemPrivate::initStyleOption(), QGraphicsItem::matrix(), QPaintEngineState::matrix(), QSvgTinyDocument::matrixForElement(), QGraphicsItem::sceneMatrix(), and QGraphicsItem::setMatrix().
 {
     return affine;
 }
translate()
QTransform & QTransform::translate (qreal dx, qreal dy)
Moves the coordinate system dx along the x axis and dy along the y axis, and returns a reference to the matrix.
See also
setMatrix()
Definition at line 417 of file qtransform.cpp.
Referenced by QPdfEnginePrivate::addBrushPattern(), QFontEngineFT::addOutlineToPath(), QGraphicsItemGroup::addToGroup(), QPainterPrivate::attachPainterPrivate(), QVGCompositionHelper::blitWindow(), QRasterPaintEnginePrivate::brushMatrix(), QProxyFontEngine::canRender(), QGraphicsItemPrivate::combineTransformFromParent(), QGraphicsItemPrivate::TransformData::computedFullTransform(), QDeclarativeParentChangePrivate::doChange(), QFontEngineMac::draw(), QFontEngineQPF::draw(), QFontEngineQPF1::draw(), QVGPaintEngine::drawCachedGlyphs(), QRasterPaintEngine::drawCachedGlyphs(), QPlastiqueStyle::drawControl(), QCleanlooksStyle::drawControl(), QMotifStyle::drawControl(), QStyleSheetStyle::drawControl(), QVGCompositionHelper::drawCursorPixmap(), QX11PaintEngine::drawFreetype(), QRasterPaintEngine::drawImage(), QOpenGLPaintEnginePrivate::drawImageAsPath(), QGraphicsScenePrivate::drawItemHelper(), QEmulationPaintEngine::drawPixmapFragments(), QVGPaintEngine::drawPixmapFragments(), QPaintEngineEx::drawPixmapFragments(), QPainter::drawPixmapFragments(), QEmulationPaintEngine::drawTextItem(), QRasterPaintEngine::drawTextItem(), QOpenGLPaintEnginePrivate::drawTiledImageAsPath(), QRasterPaintEngine::drawTiledPixmap(), drawVGImage(), QX11PaintEngine::drawXLFD(), QEmulationPaintEngine::fill(), fillBackground(), QDirectFBPaintEngine::fillRect(), QStaticTextPrivate::get(), QGraphicsItem::mouseMoveEvent(), QPdfEnginePrivate::pageMatrix(), QDeclarativeImage::paint(), QDeclarativeBorderImage::paint(), qDrawPlainRect(), qt_vg_drawVGImageStencil(), QSvgIOHandler::read(), QGraphicsItemGroup::removeFromGroup(), QGraphicsScene::render(), QGraphicsView::render(), QWidgetPrivate::render_helper(), QSvgAnimateTransform::resolveMatrix(), QDeclarativeFlipablePrivate::setBackTransform(), QVGPaintEnginePrivate::setBrushTransform(), QSpanData::setupMatrix(), QEmulationPaintEngine::stroke(), QDeclarativeParentAnimation::transition(), QGraphicsView::translate(), QImage::trueMatrix(), QGL2PaintEngineExPrivate::updateBrushUniforms(), QOpenGLPaintEnginePrivate::updateGradient(), and QGraphicsItemPrivate::updateSceneTransformFromParent().
 {
     if (dx == 0 && dy == 0)
         return *this;
 #ifndef QT_NO_DEBUG
     if (qIsNaN(dx) | qIsNaN(dy)) {
         qWarning() << "QTransform::translate with NaN called";
         return *this;
     }
 #endif
     switch(inline_type()) {
     case TxNone:
         affine._dx = dx;
         affine._dy = dy;
         break;
     case TxTranslate:
         affine._dx += dx;
         affine._dy += dy;
         break;
     case TxScale:
         affine._dx += dx*affine._m11;
         affine._dy += dy*affine._m22;
         break;
     case TxProject:
         m_33 += dx*m_13 + dy*m_23;
         // Fall through
     case TxShear:
     case TxRotate:
         affine._dx += dx*affine._m11 + dy*affine._m21;
         affine._dy += dy*affine._m22 + dx*affine._m12;
         break;
     }
     if (m_dirty < TxTranslate)
         m_dirty = TxTranslate;
     return *this;
 }
transposed()
QTransform QTransform::transposed () const
Returns the transpose of this matrix.
Definition at line 344 of file qtransform.cpp.
 {
     QTransform t(affine._m11, affine._m21, affine._dx,
                  affine._m12, affine._m22, affine._dy,
                  m_13, m_23, m_33, true);
     t.m_type = m_type;
     t.m_dirty = m_dirty;
     return t;
 }
type()
QTransform::TransformationType QTransform::type () const
Returns the transformation type of this matrix.
The transformation type is the highest enumeration value capturing all of the matrix's transformations. For example, if the matrix both scales and shears, the type would be TxShear, because TxShear has a higher enumeration value than TxScale.
Knowing the transformation type of a matrix is useful for optimization: you can often handle specific types more optimally than handling the generic case.
Definition at line 2116 of file qtransform.cpp.
Referenced by QFontEngineFT::alphaMapBoundingBox(), QFontEngine::alphaMapForGlyph(), QFontEngineMac::alphaRGBMapForGlyph(), QFontEngineFT::alphaRGBMapForGlyph(), QFontEngineWin::boundingBox(), QFontEngine::boundingBox(), QVGPaintEngine::canVgWritePixels(), QGL2PaintEngineEx::clip(), QRasterPaintEngine::clip(), QPainter::clipRegion(), clipTransformIsSimple(), QDeclarativeParentChangePrivate::doChange(), QPixmapConvolutionFilter::draw(), QPainterPrivate::draw_helper(), QWindowsXPStylePrivate::drawBackground(), QVGPaintEngine::drawCachedGlyphs(), QGL2PaintEngineExPrivate::drawCachedGlyphs(), QRasterPaintEngine::drawCachedGlyphs(), QTextLayout::drawCursor(), QRasterPaintEngine::drawEllipse(), QFontEngineWin::drawGDIGlyph(), QRasterPaintEngine::drawImage(), QGraphicsScenePrivate::drawItemHelper(), QRasterPaintEngine::drawPixmap(), QRasterPaintEngine::drawRects(), QGL2PaintEngineEx::drawStaticTextItem(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGL2PaintEngineEx::drawTextItem(), QRasterPaintEngine::drawTextItem(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QRasterPaintEngine::drawTiledPixmap(), QRasterPaintEngine::fill(), QBlitterPaintEngine::fillRect(), QRasterPaintEngine::fillRect(), QGraphicsViewPrivate::findItems(), QGLRectMaskGenerator::generateTrapezoids(), QRasterPaintEnginePrivate::getPenFunc(), QDirectFBPaintEnginePrivate::getTransformationType(), QOpenGLPaintEnginePrivate::isFastRect(), QGraphicsScenePrivate::itemsAtPosition(), QStyleOptionGraphicsItem::levelOfDetailFromTransform(), QFontEngineFT::loadTransformedGlyphSet(), operator*(), operator<<(), QDeclarativePaintedItem::paint(), qDrawBorderPixmap(), qt_format_text(), qt_scaleForTransform(), qtransform_equals_no_translate(), QRasterPaintEnginePrivate::recalculateFastImages(), QGL2PaintEngineExPrivate::setBrush(), QOutlineMapper::setMatrix(), QSpanData::setupMatrix(), QPaintEngineEx::stroke(), QRasterPaintEngine::supportsTransformations(), QTextureGlyphCache::textureMapForGlyph(), QPaintBufferEngine::transformChanged(), QDirectFBPixmapData::transformed(), QX11PixmapData::transformed(), glyph_metrics_t::transformed(), QPixmap::transformed(), QImage::transformed(), transformIsSimple(), QPaintEnginePrivate::transformSystemClip(), QDeclarativeParentAnimation::transition(), QRasterPaintEngine::updateBrush(), QPainterPrivate::updateEmulationSpecifier(), QX11PaintEngine::updateMatrix(), QOpenGLPaintEngine::updateMatrix(), QRasterPaintEngine::updateMatrix(), QGL2PaintEngineExPrivate::updateMatrix(), QRasterPaintEnginePrivate::updateMatrixData(), QRasterPaintEngine::updatePen(), and QBlitterPaintEnginePrivate::updateTransformState().
 {
     if(m_dirty == TxNone || m_dirty < m_type)
         return static_cast<TransformationType>(m_type);
     switch (static_cast<TransformationType>(m_dirty)) {
     case TxProject:
         if (!qFuzzyIsNull(m_13) || !qFuzzyIsNull(m_23) || !qFuzzyIsNull(m_33 - 1)) {
              m_type = TxProject;
              break;
          }
     case TxShear:
     case TxRotate:
         if (!qFuzzyIsNull(affine._m12) || !qFuzzyIsNull(affine._m21)) {
             const qreal dot = affine._m11 * affine._m12 + affine._m21 * affine._m22;
             if (qFuzzyIsNull(dot))
                 m_type = TxRotate;
             else
                 m_type = TxShear;
             break;
         }
     case TxScale:
         if (!qFuzzyIsNull(affine._m11 - 1) || !qFuzzyIsNull(affine._m22 - 1)) {
             m_type = TxScale;
             break;
         }
     case TxTranslate:
         if (!qFuzzyIsNull(affine._dx) || !qFuzzyIsNull(affine._dy)) {
             m_type = TxTranslate;
             break;
         }
     case TxNone:
         m_type = TxNone;
         break;
     }
     m_dirty = TxNone;
     return static_cast<TransformationType>(m_type);
 }
Friends and Related Functions
operator*() [1/8]
QPoint operator* (const QPoint & point, const QTransform & matrix) related
This is the same as {matrix}.map({point}).
See also
QTransform::map()
Definition at line 365 of file qtransform.h.
 { return m.map(p); }
operator*() [2/8]
QPointF operator* (const QPointF & point, const QTransform & matrix) related
Same as {matrix}.map({point}).
See also
QTransform::map()
Definition at line 367 of file qtransform.h.
 { return m.map(p); }
operator*() [3/8]
QLineF operator* (const QLineF & line, const QTransform & matrix) related
This is the same as {matrix}.map({line}).
See also
QTransform::map()
Definition at line 369 of file qtransform.h.
 { return m.map(l); }
operator*() [4/8]
QLine operator* (const QLine & line, const QTransform & matrix) related
This is the same as {matrix}.map({line}).
See also
QTransform::map()
Definition at line 371 of file qtransform.h.
 { return m.map(l); }
operator*() [5/8]
QPolygonF operator* (const QPolygonF & polygon, const QTransform & matrix) related
Since
4.3
This is the same as {matrix}.map({polygon}).
See also
QTransform::map()
Definition at line 375 of file qtransform.h.
 { return m.map(a); }
operator*() [6/8]
QPolygon operator* (const QPolygon & polygon, const QTransform & matrix) related
This is the same as {matrix}.map({polygon}).
See also
QTransform::map()
Definition at line 373 of file qtransform.h.
 { return m.map(a); }
operator*() [7/8]
QRegion operator* (const QRegion & region, const QTransform & matrix) related
This is the same as {matrix}.map({region}).
See also
QTransform::map()
Definition at line 377 of file qtransform.h.
 { return m.map(r); }
operator*() [8/8]
QPainterPath operator* (const QPainterPath & path, const QTransform & matrix) related
Since
4.3
This is the same as {matrix}.map({path}).
See also
QTransform::map()
Definition at line 379 of file qtransform.h.
 { return m.map(p); }
operator<<()
QDataStream & operator<< (QDataStream & stream, const QTransform & matrix) related
Writes the given matrix to the given stream and returns a reference to the stream.
Since
4.3
See also
{Serializing Qt Data Types}
Definition at line 1064 of file qtransform.cpp.
 {
     s << double(m.m11())
       << double(m.m12())
       << double(m.m13())
       << double(m.m21())
       << double(m.m22())
       << double(m.m23())
       << double(m.m31())
       << double(m.m32())
       << double(m.m33());
     return s;
 }
operator>>()
QDataStream & operator>> (QDataStream & stream, QTransform & matrix) related
Reads the given matrix from the given stream and returns a reference to the stream.
Since
4.3
See also
{Serializing Qt Data Types}
Definition at line 1091 of file qtransform.cpp.
 {
      double m11, m12, m13,
          m21, m22, m23,
          m31, m32, m33;
      s >> m11;
      s >> m12;
      s >> m13;
      s >> m21;
      s >> m22;
      s >> m23;
      s >> m31;
      s >> m32;
      s >> m33;
      t.setMatrix(m11, m12, m13,
                  m21, m22, m23,
                  m31, m32, m33);
      return s;
 }
qFuzzyCompare()
bool qFuzzyCompare (const QTransform & t1, const QTransform & t2) related
Returns true if t1 and t2 are equal, allowing for a small fuzziness factor for floating-point comparisons; false otherwise.
Since
4.6
Definition at line 339 of file qtransform.h.
Referenced by qt_scaleForTransform().
 {
     return qFuzzyCompare(t1.m11(), t2.m11())
         && qFuzzyCompare(t1.m12(), t2.m12())
         && qFuzzyCompare(t1.m13(), t2.m13())
         && qFuzzyCompare(t1.m21(), t2.m21())
         && qFuzzyCompare(t1.m22(), t2.m22())
         && qFuzzyCompare(t1.m23(), t2.m23())
         && qFuzzyCompare(t1.m31(), t2.m31())
         && qFuzzyCompare(t1.m32(), t2.m32())
         && qFuzzyCompare(t1.m33(), t2.m33());
 }
Properties
affine
QMatrix QTransform::affine private
Definition at line 179 of file qtransform.h.
Referenced by adjoint(), inverted(), map(), mapRect(), mapToPolygon(), operator*(), operator*=(), operator=(), operator==(), reset(), rotate(), rotateRadians(), scale(), setMatrix(), shear(), toAffine(), translate(), transposed(), and type().
d
Private* QTransform::d private
Definition at line 187 of file qtransform.h.
Referenced by squareToQuad().
m_13
qreal QTransform::m_13 private
Definition at line 180 of file qtransform.h.
Referenced by adjoint(), map(), operator*(), operator*=(), operator=(), operator==(), reset(), rotate(), rotateRadians(), scale(), setMatrix(), shear(), translate(), transposed(), and type().
m_23
qreal QTransform::m_23 private
Definition at line 181 of file qtransform.h.
Referenced by adjoint(), map(), operator*(), operator*=(), operator=(), operator==(), reset(), rotate(), rotateRadians(), scale(), setMatrix(), shear(), translate(), transposed(), and type().
m_33
qreal QTransform::m_33 private
Definition at line 182 of file qtransform.h.
Referenced by adjoint(), map(), operator*(), operator*=(), operator=(), operator==(), reset(), setMatrix(), translate(), transposed(), and type().
m_dirty
uint QTransform::m_dirty mutable private
Definition at line 185 of file qtransform.h.
Referenced by fromScale(), fromTranslate(), inverted(), operator*(), operator*=(), operator=(), reset(), rotate(), rotateRadians(), scale(), setMatrix(), shear(), translate(), transposed(), and type().
m_type
uint QTransform::m_type mutable private
Definition at line 184 of file qtransform.h.
Referenced by fromScale(), fromTranslate(), inverted(), operator*(), operator*=(), operator=(), reset(), rotate(), rotateRadians(), setMatrix(), transposed(), and type().
The documentation for this class was generated from the following files:
/src/gui/painting/qtransform.h
/src/gui/painting/qtransform.cpp