Qt 4.8: QDateTimeParser Class Reference
QDateTimeParser Class Reference
#include <qdatetime_p.h>
Classes
struct SectionNode
struct StateNode
Public Types
enum {
Neither = -1, AM = 0, PM = 1, PossibleAM = 2,
PossiblePM = 3, PossibleBoth = 4
}
enum AmPm { AmText, PmText }
enum Case { UpperCase, LowerCase }
enum Context { FromString, DateTimeEdit }
enum FieldInfoFlag { Numeric = 0x01, FixedWidth = 0x02, AllowPartial = 0x04, Fraction = 0x08 }
enum Section {
NoSection = 0x00000, AmPmSection = 0x00001, MSecSection = 0x00002, SecondSection = 0x00004,
MinuteSection = 0x00008, Hour12Section = 0x00010, Hour24Section = 0x00020, TimeSectionMask = (AmPmSection|MSecSection|SecondSection|MinuteSection|Hour12Section|Hour24Section),
Internal = 0x10000, DaySection = 0x00100, MonthSection = 0x00200, YearSection = 0x00400,
YearSection2Digits = 0x00800, DayOfWeekSection = 0x01000, DateSectionMask = (DaySection|MonthSection|YearSection|YearSection2Digits|DayOfWeekSection), FirstSection = 0x02000|Internal,
LastSection = 0x04000|Internal, CalendarPopupSection = 0x08000|Internal, NoSectionIndex = -1, FirstSectionIndex = -2,
LastSectionIndex = -3, CalendarPopupIndex = -4
}
enum State { Invalid, Intermediate, Acceptable }
Public Functions
int absoluteMax (int index, const QDateTime &value=QDateTime()) const
\
int absoluteMin (int index) const
virtual int cursorPosition () const
virtual QString displayText () const
FieldInfo fieldInfo (int index) const
int findAmPm (QString &str1, int index, int *used=0) const
int findDay (const QString &str1, int intDaystart, int sectionIndex, QString *dayName=0, int *used=0) const
int findMonth (const QString &str1, int monthstart, int sectionIndex, QString *monthName=0, int *used=0) const
bool fromString (const QString &text, QDate *date, QTime *time) const
virtual QString getAmPmText (AmPm ap, Case cs) const
int getDigit (const QDateTime &dt, int index) const
Gets the digit from a datetime.
virtual QDateTime getMaximum () const
virtual QDateTime getMinimum () const
virtual QLocale locale () const
int maxChange (int s) const
Max number of units that can be changed by this section.
StateNode parse (QString &input, int &cursorPosition, const QDateTime &currentValue, bool fixup) const
bool parseFormat (const QString &format)
int parseSection (const QDateTime &currentValue, int sectionIndex, QString &txt, int &cursorPosition, int index, QDateTimeParser::State &state, int *used=0) const
bool potentialValue (const QString &str, int min, int max, int index, const QDateTime &currentValue, int insert) const
QDateTimeParser (QVariant::Type t, Context ctx)
QString sectionFormat (int index) const
QString sectionFormat (Section s, int count) const
int sectionMaxSize (int index) const
int sectionMaxSize (Section s, int count) const
QString sectionName (int s) const
For debugging.
const SectionNode & sectionNode (int index) const
Returns the sectionNode for the Section s.
int sectionPos (int index) const
Returns the starting position for section s.
int sectionPos (const SectionNode &sn) const
int sectionSize (int index) const
Returns the size of section s.
QString sectionText (int sectionIndex) const
QString sectionText (const QString &text, int sectionIndex, int index) const
Returns the text of section s.
Section sectionType (int index) const
bool setDigit (QDateTime &t, int index, int newval) const
Sets a digit in a datetime.
bool skipToNextSection (int section, const QDateTime &current, const QString &sectionText) const
QString stateName (int s) const
For debugging.
virtual ~QDateTimeParser ()
Public Variables
int cachedDay
Context context
int currentSectionIndex
QLocale defaultLocale
Sections display
QString displayFormat
SectionNode first
bool fixday
SectionNode last
SectionNode none
QVariant::Type parserType
SectionNode popup
QVector< SectionNode > sectionNodes
QStringList separators
Qt::TimeSpec spec
QString text
Detailed Description
Definition at line 112 of file qdatetime_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
Neither
AM
PM
PossibleAM
PossiblePM
PossibleBoth
Definition at line 135 of file qdatetime_p.h.
          {
         Neither = -1,
         AM = 0,
         PM = 1,
         PossibleAM = 2,
         PossiblePM = 3,
         PossibleBoth = 4
     };
AmPm
enum QDateTimeParser::AmPm
Enumerator
AmText
PmText
Definition at line 191 of file qdatetime_p.h.
               {
         AmText,
         PmText
     };
Case
enum QDateTimeParser::Case
Enumerator
UpperCase
LowerCase
Definition at line 196 of file qdatetime_p.h.
               {
         UpperCase,
         LowerCase
     };
Context
enum QDateTimeParser::Context
Enumerator
FromString
DateTimeEdit
Definition at line 115 of file qdatetime_p.h.
                  {
         FromString,
         DateTimeEdit
     };
FieldInfoFlag
enum QDateTimeParser::FieldInfoFlag
Enumerator
Numeric
FixedWidth
AllowPartial
Fraction
Definition at line 242 of file qdatetime_p.h.
{
         Numeric = 0x01,
         FixedWidth = 0x02,
         AllowPartial = 0x04,
         Fraction = 0x08
     };
Section
enum QDateTimeParser::Section
Enumerator
NoSection
AmPmSection
MSecSection
SecondSection
MinuteSection
Hour12Section
Hour24Section
TimeSectionMask
Internal
DaySection
MonthSection
YearSection
YearSection2Digits
DayOfWeekSection
DateSectionMask
FirstSection
LastSection
CalendarPopupSection
NoSectionIndex
FirstSectionIndex
LastSectionIndex
CalendarPopupIndex
Definition at line 144 of file qdatetime_p.h.
                  {
         NoSection = 0x00000,
         AmPmSection = 0x00001,
         MSecSection = 0x00002,
         SecondSection = 0x00004,
         MinuteSection = 0x00008,
         Hour12Section   = 0x00010,
         Hour24Section   = 0x00020,
         TimeSectionMask = (AmPmSection|MSecSection|SecondSection|MinuteSection|Hour12Section|Hour24Section),
         Internal = 0x10000,
         DaySection = 0x00100,
         MonthSection = 0x00200,
         YearSection = 0x00400,
         YearSection2Digits = 0x00800,
         DayOfWeekSection = 0x01000,
         DateSectionMask = (DaySection|MonthSection|YearSection|YearSection2Digits|DayOfWeekSection),
         FirstSection = 0x02000|Internal,
         LastSection = 0x04000|Internal,
         CalendarPopupSection = 0x08000|Internal,
         NoSectionIndex = -1,
         FirstSectionIndex = -2,
         LastSectionIndex = -3,
         CalendarPopupIndex = -4
     }; // duplicated from qdatetimeedit.h
State
enum QDateTimeParser::State
Enumerator
Invalid
Intermediate
Acceptable
Definition at line 177 of file qdatetime_p.h.
                { // duplicated from QValidator
         Invalid,
         Intermediate,
         Acceptable
     };
Constructors and Destructors
QDateTimeParser()
QDateTimeParser::QDateTimeParser (QVariant::Type t, Context ctx) inline
Definition at line 119 of file qdatetime_p.h.
         : currentSectionIndex(-1), display(0), cachedDay(-1), parserType(t),
         fixday(false), spec(Qt::LocalTime), context(ctx)
     {
         defaultLocale = QLocale::system();
         first.type = FirstSection;
         first.pos = -1;
         first.count = -1;
         last.type = FirstSection;
         last.pos = -1;
         last.count = -1;
         none.type = NoSection;
         none.pos = -1;
         none.count = -1;
     }
~QDateTimeParser()
virtual QDateTimeParser::~QDateTimeParser () inline virtual
Definition at line 134 of file qdatetime_p.h.
 {}
Functions
absoluteMax()
int QDateTimeParser::absoluteMax (int s, const QDateTime & cur = QDateTime()) const
\
Returns the absolute maximum for a section
Definition at line 4590 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::stepBy().
 {
     const SectionNode &sn = sectionNode(s);
     switch (sn.type) {
     case Hour24Section:
     case Hour12Section: return 23; // this is special-cased in
                                    // parseSection. We want it to be
                                    // 23 for the stepBy case.
     case MinuteSection:
     case SecondSection: return 59;
     case MSecSection: return 999;
     case YearSection2Digits:
     case YearSection: return 9999; // sectionMaxSize will prevent
                                    // people from typing in a larger
                                    // number in count == 2 sections.
                                    // stepBy() will work on real years anyway
     case MonthSection: return 12;
     case DaySection:
     case DayOfWeekSection: return cur.isValid() ? cur.date().daysInMonth() : 31;
     case AmPmSection: return 1;
     default: break;
     }
     qWarning("QDateTimeParser::absoluteMax() Internal error (%s)",
              qPrintable(sectionName(sn.type)));
     return -1;
 }
absoluteMin()
int QDateTimeParser::absoluteMin (int s) const
Warning
This function is not part of the public interface.
Returns the absolute minimum for a section
Definition at line 4623 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::stepBy().
 {
     const SectionNode &sn = sectionNode(s);
     switch (sn.type) {
     case Hour24Section:
     case Hour12Section:
     case MinuteSection:
     case SecondSection:
     case MSecSection:
     case YearSection2Digits:
     case YearSection: return 0;
     case MonthSection:
     case DaySection:
     case DayOfWeekSection: return 1;
     case AmPmSection: return 0;
     default: break;
     }
     qWarning("QDateTimeParser::absoluteMin() Internal error (%s, %0x)",
              qPrintable(sectionName(sn.type)), sn.type);
     return -1;
 }
cursorPosition()
virtual int QDateTimeParser::cursorPosition () const inline virtual
Reimplemented in QDateTimeEditPrivate.
Definition at line 254 of file qdatetime_p.h.
 { return -1; }
displayText()
virtual QString QDateTimeParser::displayText () const inline virtual
Reimplemented in QDateTimeEditPrivate.
Definition at line 255 of file qdatetime_p.h.
 { return text; }
fieldInfo()
QDateTimeParser::FieldInfo QDateTimeParser::fieldInfo (int index) const
Definition at line 5868 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::interpret(), and QDateTimeEditPrivate::isSeparatorKey().
 {
     FieldInfo ret = 0;
     const SectionNode &sn = sectionNode(index);
     const Section s = sn.type;
     switch (s) {
     case MSecSection:
         ret |= Fraction;
         // fallthrough
     case SecondSection:
     case MinuteSection:
     case Hour24Section:
     case Hour12Section:
     case YearSection:
     case YearSection2Digits:
         ret |= Numeric;
         if (s != YearSection) {
             ret |= AllowPartial;
         }
         if (sn.count != 1) {
             ret |= FixedWidth;
         }
         break;
     case MonthSection:
     case DaySection:
         switch (sn.count) {
         case 2:
             ret |= FixedWidth;
             // fallthrough
         case 1:
             ret |= (Numeric|AllowPartial);
             break;
         }
         break;
     case DayOfWeekSection:
         if (sn.count == 3)
             ret |= FixedWidth;
         break;
     case AmPmSection:
         ret |= FixedWidth;
         break;
     default:
         qWarning("QDateTimeParser::fieldInfo Internal error 2 (%d %s %d)",
                  index, qPrintable(sectionName(sn.type)), sn.count);
         break;
     }
     return ret;
 }
findAmPm()
int QDateTimeParser::findAmPm (QString & str, int index, int * used = 0) const
Warning
This function is not part of the public interface.
returns 0 if str == QDateTimeEdit::tr("AM") 1 if str == QDateTimeEdit::tr("PM") 2 if str can become QDateTimeEdit::tr("AM") 3 if str can become QDateTimeEdit::tr("PM") 4 if str can become QDateTimeEdit::tr("PM") and can become QDateTimeEdit::tr("AM") -1 can't become anything sensible
Definition at line 5759 of file qdatetime.cpp.
 {
     const SectionNode &s = sectionNode(index);
     if (s.type != AmPmSection) {
         qWarning("QDateTimeParser::findAmPm Internal error");
         return -1;
     }
     if (used)
         *used = str.size();
     if (str.trimmed().isEmpty()) {
         return PossibleBoth;
     }
     const QLatin1Char space(' ');
     int size = sectionMaxSize(index);
     enum {
         amindex = 0,
         pmindex = 1
     };
     QString ampm[2];
     ampm[amindex] = getAmPmText(AmText, s.count == 1 ? UpperCase : LowerCase);
     ampm[pmindex] = getAmPmText(PmText, s.count == 1 ? UpperCase : LowerCase);
     for (int i=0; i<2; ++i)
         ampm[i].truncate(size);
     QDTPDEBUG << "findAmPm" << str << ampm[0] << ampm[1];
     if (str.indexOf(ampm[amindex], 0, Qt::CaseInsensitive) == 0) {
         str = ampm[amindex];
         return AM;
     } else if (str.indexOf(ampm[pmindex], 0, Qt::CaseInsensitive) == 0) {
         str = ampm[pmindex];
         return PM;
     } else if (context == FromString || (str.count(space) == 0 && str.size() >= size)) {
         return Neither;
     }
     size = qMin(size, str.size());
     bool broken[2] = {false, false};
     for (int i=0; i<size; ++i) {
         if (str.at(i) != space) {
             for (int j=0; j<2; ++j) {
                 if (!broken[j]) {
                     int index = ampm[j].indexOf(str.at(i));
                     QDTPDEBUG << "looking for" << str.at(i)
                               << "in" << ampm[j] << "and got" << index;
                     if (index == -1) {
                         if (str.at(i).category() == QChar::Letter_Uppercase) {
                             index = ampm[j].indexOf(str.at(i).toLower());
                             QDTPDEBUG << "trying with" << str.at(i).toLower()
                                       << "in" << ampm[j] << "and got" << index;
                         } else if (str.at(i).category() == QChar::Letter_Lowercase) {
                             index = ampm[j].indexOf(str.at(i).toUpper());
                             QDTPDEBUG << "trying with" << str.at(i).toUpper()
                                       << "in" << ampm[j] << "and got" << index;
                         }
                         if (index == -1) {
                             broken[j] = true;
                             if (broken[amindex] && broken[pmindex]) {
                                 QDTPDEBUG << str << "didn't make it";
                                 return Neither;
                             }
                             continue;
                         } else {
                             str[i] = ampm[j].at(index); // fix case
                         }
                     }
                     ampm[j].remove(index, 1);
                 }
             }
         }
     }
     if (!broken[pmindex] && !broken[amindex])
         return PossibleBoth;
     return (!broken[amindex] ? PossibleAM : PossiblePM);
 }
findDay()
int QDateTimeParser::findDay (const QString & str1, int intDaystart, int sectionIndex, QString * dayName = 0, int * used = 0) const
Definition at line 5688 of file qdatetime.cpp.
 {
     int bestMatch = -1;
     int bestCount = 0;
     if (!str1.isEmpty()) {
         const SectionNode &sn = sectionNode(sectionIndex);
         if (!(sn.type & (DaySection|DayOfWeekSection))) {
             qWarning("QDateTimeParser::findDay Internal error");
             return -1;
         }
         const QLocale l = locale();
         for (int day=startDay; day<=7; ++day) {
             const QString str2 = l.dayName(day, sn.count == 4 ? QLocale::LongFormat : QLocale::ShortFormat);
             if (str1.startsWith(str2.toLower())) {
                 if (used)
                     *used = str2.size();
                 if (usedDay) {
                     *usedDay = str2;
                 }
                 return day;
             }
             if (context == FromString)
                 continue;
             const int limit = qMin(str1.size(), str2.size());
             bool found = true;
             for (int i=0; i<limit; ++i) {
                 if (str1.at(i) != str2.at(i) && !str1.at(i).isSpace()) {
                     if (i > bestCount) {
                         bestCount = i;
                         bestMatch = day;
                     }
                     found = false;
                     break;
                 }
             }
             if (found) {
                 if (used)
                     *used = limit;
                 if (usedDay)
                     *usedDay = str2;
                 return day;
             }
         }
         if (usedDay && bestMatch != -1) {
             *usedDay = l.dayName(bestMatch, sn.count == 4 ? QLocale::LongFormat : QLocale::ShortFormat);
         }
     }
     if (used)
         *used = bestCount;
     return bestMatch;
 }
findMonth()
int QDateTimeParser::findMonth (const QString & str1, int startMonth, int sectionIndex, QString * usedMonth = 0, int * used = 0) const
Warning
This function is not part of the public interface. finds the first possible monthname that str1 can match. Starting from index; str should already by lowered
Definition at line 5625 of file qdatetime.cpp.
 {
     int bestMatch = -1;
     int bestCount = 0;
     if (!str1.isEmpty()) {
         const SectionNode &sn = sectionNode(sectionIndex);
         if (sn.type != MonthSection) {
             qWarning("QDateTimeParser::findMonth Internal error");
             return -1;
         }
         QLocale::FormatType type = sn.count == 3 ? QLocale::ShortFormat : QLocale::LongFormat;
         QLocale l = locale();
         for (int month=startMonth; month<=12; ++month) {
             QString str2 = l.monthName(month, type).toLower();
             if (str1.startsWith(str2)) {
                 if (used) {
                     QDTPDEBUG << "used is set to" << str2.size();
                     *used = str2.size();
                 }
                 if (usedMonth)
                     *usedMonth = l.monthName(month, type);
                 return month;
             }
             if (context == FromString)
                 continue;
             const int limit = qMin(str1.size(), str2.size());
             QDTPDEBUG << "limit is" << limit << str1 << str2;
             bool equal = true;
             for (int i=0; i<limit; ++i) {
                 if (str1.at(i) != str2.at(i)) {
                     equal = false;
                     if (i > bestCount) {
                         bestCount = i;
                         bestMatch = month;
                     }
                     break;
                 }
             }
             if (equal) {
                 if (used)
                     *used = limit;
                 if (usedMonth)
                     *usedMonth = l.monthName(month, type);
                 return month;
             }
         }
         if (usedMonth && bestMatch != -1)
             *usedMonth = l.monthName(bestMatch, type);
     }
     if (used) {
         QDTPDEBUG << "used is set to" << bestCount;
         *used = bestCount;
     }
     return bestMatch;
 }
fromString()
bool QDateTimeParser::fromString (const QString & text, QDate * date, QTime * time) const
Definition at line 6084 of file qdatetime.cpp.
Referenced by QDate::fromString(), QTime::fromString(), QDateTime::fromString(), QLocale::toDate(), QLocale::toDateTime(), and QLocale::toTime().
 {
     QDateTime val(QDate(1900, 1, 1), QDATETIMEEDIT_TIME_MIN);
     QString text = t;
     int copy = -1;
     const StateNode tmp = parse(text, copy, val, false);
     if (tmp.state != Acceptable || tmp.conflicts) {
         return false;
     }
     if (time) {
         const QTime t = tmp.value.time();
         if (!t.isValid()) {
             return false;
         }
         *time = t;
     }
     if (date) {
         const QDate d = tmp.value.date();
         if (!d.isValid()) {
             return false;
         }
         *date = d;
     }
     return true;
 }
getAmPmText()
QString QDateTimeParser::getAmPmText (AmPm ap, Case cs) const virtual
Reimplemented in QDateTimeEditPrivate.
Definition at line 6122 of file qdatetime.cpp.
 {
     if (ap == AmText) {
         return (cs == UpperCase ? QLatin1String("AM") : QLatin1String("am"));
     } else {
         return (cs == UpperCase ? QLatin1String("PM") : QLatin1String("pm"));
     }
 }
getDigit()
int QDateTimeParser::getDigit (const QDateTime & t, int index) const
Gets the digit from a datetime.
Warning
This function is not part of the public interface. E.g.
QDateTime var(QDate(2004, 02, 02)); int digit = getDigit(var, Year); digit = 2004
Definition at line 4469 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::stepBy().
 {
     if (index < 0 || index >= sectionNodes.size()) {
 #ifndef QT_NO_DATESTRING
         qWarning("QDateTimeParser::getDigit() Internal error (%s %d)",
                  qPrintable(t.toString()), index);
 #else
         qWarning("QDateTimeParser::getDigit() Internal error (%d)", index);
 #endif
         return -1;
     }
     const SectionNode &node = sectionNodes.at(index);
     switch (node.type) {
     case Hour24Section: case Hour12Section: return t.time().hour();
     case MinuteSection: return t.time().minute();
     case SecondSection: return t.time().second();
     case MSecSection: return t.time().msec();
     case YearSection2Digits:
     case YearSection: return t.date().year();
     case MonthSection: return t.date().month();
     case DaySection: return t.date().day();
     case DayOfWeekSection: return t.date().day();
     case AmPmSection: return t.time().hour() > 11 ? 1 : 0;
     default: break;
     }
 #ifndef QT_NO_DATESTRING
     qWarning("QDateTimeParser::getDigit() Internal error 2 (%s %d)",
              qPrintable(t.toString()), index);
 #else
     qWarning("QDateTimeParser::getDigit() Internal error 2 (%d)", index);
 #endif
     return -1;
 }
getMaximum()
QDateTime QDateTimeParser::getMaximum () const virtual
Reimplemented in QDateTimeEditPrivate.
Definition at line 6117 of file qdatetime.cpp.
 {
     return QDateTime(QDATETIMEEDIT_DATE_MAX, QDATETIMEEDIT_TIME_MAX, spec);
 }
getMinimum()
QDateTime QDateTimeParser::getMinimum () const virtual
Reimplemented in QDateTimeEditPrivate.
Definition at line 6112 of file qdatetime.cpp.
 {
     return QDateTime(QDATETIMEEDIT_DATE_MIN, QDATETIMEEDIT_TIME_MIN, spec);
 }
locale()
virtual QLocale QDateTimeParser::locale () const inline virtual
Reimplemented in QDateTimeEditPrivate.
Definition at line 257 of file qdatetime_p.h.
 { return defaultLocale; }
maxChange()
int QDateTimeParser::maxChange (int index) const
Max number of units that can be changed by this section.
Warning
This function is not part of the public interface.
Definition at line 5844 of file qdatetime.cpp.
Referenced by parse().
 {
     const SectionNode &sn = sectionNode(index);
     switch (sn.type) {
         // Time. unit is msec
     case MSecSection: return 999;
     case SecondSection: return 59 * 1000;
     case MinuteSection: return 59 * 60 * 1000;
     case Hour24Section: case Hour12Section: return 59 * 60 * 60 * 1000;
         // Date. unit is day
     case DayOfWeekSection: return 7;
     case DaySection: return 30;
     case MonthSection: return 365 - 31;
     case YearSection: return 9999 * 365;
     case YearSection2Digits: return 100 * 365;
     default:
         qWarning("QDateTimeParser::maxChange() Internal error (%s)",
                  qPrintable(sectionName(sectionType(index))));
     }
     return -1;
 }
parse()
QDateTimeParser::StateNode QDateTimeParser::parse (QString & input, int & cursorPosition, const QDateTime & currentValue, bool fixup) const
Warning
This function is not part of the public interface.
Definition at line 5271 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::validateAndInterpret().
 {
     const QDateTime minimum = getMinimum();
     const QDateTime maximum = getMaximum();
     State state = Acceptable;
     QDateTime newCurrentValue;
     int pos = 0;
     bool conflicts = false;
     const int sectionNodesCount = sectionNodes.size();
     QDTPDEBUG << "parse" << input;
     {
         int year, month, day, hour12, hour, minute, second, msec, ampm, dayofweek, year2digits;
         getDateFromJulianDay(currentValue.date().toJulianDay(), &year, &month, &day);
         year2digits = year % 100;
         hour = currentValue.time().hour();
         hour12 = -1;
         minute = currentValue.time().minute();
         second = currentValue.time().second();
         msec = currentValue.time().msec();
         dayofweek = currentValue.date().dayOfWeek();
         ampm = -1;
         Sections isSet = NoSection;
         int num;
         State tmpstate;
         for (int index=0; state != Invalid && index<sectionNodesCount; ++index) {
             if (QStringRef(&input, pos, separators.at(index).size()) != separators.at(index)) {
                 QDTPDEBUG << "invalid because" << input.mid(pos, separators.at(index).size())
                           << "!=" << separators.at(index)
                           << index << pos << currentSectionIndex;
                 state = Invalid;
                 goto end;
             }
             pos += separators.at(index).size();
             sectionNodes[index].pos = pos;
             int *current = 0;
             const SectionNode sn = sectionNodes.at(index);
             int used;
             num = parseSection(currentValue, index, input, cursorPosition, pos, tmpstate, &used);
             QDTPDEBUG << "sectionValue" << sectionName(sectionType(index)) << input
                       << "pos" << pos << "used" << used << stateName(tmpstate);
             if (fixup && tmpstate == Intermediate && used < sn.count) {
                 const FieldInfo fi = fieldInfo(index);
                 if ((fi & (Numeric|FixedWidth)) == (Numeric|FixedWidth)) {
                     const QString newText = QString::fromLatin1("%1").arg(num, sn.count, 10, QLatin1Char('0'));
                     input.replace(pos, used, newText);
                     used = sn.count;
                 }
             }
             pos += qMax(0, used);
             state = qMin<State>(state, tmpstate);
             if (state == Intermediate && context == FromString) {
                 state = Invalid;
                 break;
             }
             QDTPDEBUG << index << sectionName(sectionType(index)) << "is set to"
                       << pos << "state is" << stateName(state);
             if (state != Invalid) {
                 switch (sn.type) {
                 case Hour24Section: current = &hour; break;
                 case Hour12Section: current = &hour12; break;
                 case MinuteSection: current = &minute; break;
                 case SecondSection: current = &second; break;
                 case MSecSection: current = &msec; break;
                 case YearSection: current = &year; break;
                 case YearSection2Digits: current = &year2digits; break;
                 case MonthSection: current = &month; break;
                 case DayOfWeekSection: current = &dayofweek; break;
                 case DaySection: current = &day; num = qMax<int>(1, num); break;
                 case AmPmSection: current = &ampm; break;
                 default:
                     qWarning("QDateTimeParser::parse Internal error (%s)",
                              qPrintable(sectionName(sn.type)));
                     break;
                 }
                 if (!current) {
                     qWarning("QDateTimeParser::parse Internal error 2");
                     return StateNode();
                 }
                 if (isSet & sn.type && *current != num) {
                     QDTPDEBUG << "CONFLICT " << sectionName(sn.type) << *current << num;
                     conflicts = true;
                     if (index != currentSectionIndex || num == -1) {
                         continue;
                     }
                 }
                 if (num != -1)
                     *current = num;
                 isSet |= sn.type;
             }
         }
         if (state != Invalid && QStringRef(&input, pos, input.size() - pos) != separators.last()) {
             QDTPDEBUG << "invalid because" << input.mid(pos)
                       << "!=" << separators.last() << pos;
             state = Invalid;
         }
         if (state != Invalid) {
             if (parserType != QVariant::Time) {
                 if (year % 100 != year2digits) {
                     switch (isSet & (YearSection2Digits|YearSection)) {
                     case YearSection2Digits:
                         year = (year / 100) * 100;
                         year += year2digits;
                         break;
                     case ((uint)YearSection2Digits|(uint)YearSection): {
                         conflicts = true;
                         const SectionNode &sn = sectionNode(currentSectionIndex);
                         if (sn.type == YearSection2Digits) {
                             year = (year / 100) * 100;
                             year += year2digits;
                         }
                         break; }
                     default:
                         break;
                     }
                 }
                 const QDate date(year, month, day);
                 const int diff = dayofweek - date.dayOfWeek();
                 if (diff != 0 && state == Acceptable && isSet & DayOfWeekSection) {
                     conflicts = isSet & DaySection;
                     const SectionNode &sn = sectionNode(currentSectionIndex);
                     if (sn.type == DayOfWeekSection || currentSectionIndex == -1) {
                         // dayofweek should be preferred
                         day += diff;
                         if (day <= 0) {
                             day += 7;
                         } else if (day > date.daysInMonth()) {
                             day -= 7;
                         }
                         QDTPDEBUG << year << month << day << dayofweek
                                   << diff << QDate(year, month, day).dayOfWeek();
                     }
                 }
                 bool needfixday = false;
                 if (sectionType(currentSectionIndex) & (DaySection|DayOfWeekSection)) {
                     cachedDay = day;
                 } else if (cachedDay > day) {
                     day = cachedDay;
                     needfixday = true;
                 }
                 if (!QDate::isValid(year, month, day)) {
                     if (day < 32) {
                         cachedDay = day;
                     }
                     if (day > 28 && QDate::isValid(year, month, 1)) {
                         needfixday = true;
                     }
                 }
                 if (needfixday) {
                     if (context == FromString) {
                         state = Invalid;
                         goto end;
                     }
                     if (state == Acceptable && fixday) {
                         day = qMin<int>(day, QDate(year, month, 1).daysInMonth());
                         const QLocale loc = locale();
                         for (int i=0; i<sectionNodesCount; ++i) {
                             if (sectionType(i) & (DaySection|DayOfWeekSection)) {
                                 input.replace(sectionPos(i), sectionSize(i), loc.toString(day));
                             }
                         }
                     } else {
                         state = qMin(Intermediate, state);
                     }
                 }
             }
             if (parserType != QVariant::Date) {
                 if (isSet & Hour12Section) {
                     const bool hasHour = isSet & Hour24Section;
                     if (ampm == -1) {
                         if (hasHour) {
                             ampm = (hour < 12 ? 0 : 1);
                         } else {
                             ampm = 0; // no way to tell if this is am or pm so I assume am
                         }
                     }
                     hour12 = (ampm == 0 ? hour12 % 12 : (hour12 % 12) + 12);
                     if (!hasHour) {
                         hour = hour12;
                     } else if (hour != hour12) {
                         conflicts = true;
                     }
                 } else if (ampm != -1) {
                     if (!(isSet & (Hour24Section))) {
                         hour = (12 * ampm); // special case. Only ap section
                     } else if ((ampm == 0) != (hour < 12)) {
                         conflicts = true;
                     }
                 }
             }
             newCurrentValue = QDateTime(QDate(year, month, day), QTime(hour, minute, second, msec), spec);
             QDTPDEBUG << year << month << day << hour << minute << second << msec;
         }
         QDTPDEBUGN("'%s' => '%s'(%s)", input.toLatin1().constData(),
                    newCurrentValue.toString(QLatin1String("yyyy/MM/dd hh:mm:ss.zzz")).toLatin1().constData(),
                    stateName(state).toLatin1().constData());
     }
 end:
     if (newCurrentValue.isValid()) {
         if (context != FromString && state != Invalid && newCurrentValue < minimum) {
             const QLatin1Char space(' ');
             if (newCurrentValue >= minimum)
                 qWarning("QDateTimeParser::parse Internal error 3 (%s %s)",
                          qPrintable(newCurrentValue.toString()), qPrintable(minimum.toString()));
             bool done = false;
             state = Invalid;
             for (int i=0; i<sectionNodesCount && !done; ++i) {
                 const SectionNode &sn = sectionNodes.at(i);
                 QString t = sectionText(input, i, sn.pos).toLower();
                 if ((t.size() < sectionMaxSize(i) && (((int)fieldInfo(i) & (FixedWidth|Numeric)) != Numeric))
                     || t.contains(space)) {
                     switch (sn.type) {
                     case AmPmSection:
                         switch (findAmPm(t, i)) {
                         case AM:
                         case PM:
                             state = Acceptable;
                             done = true;
                             break;
                         case Neither:
                             state = Invalid;
                             done = true;
                             break;
                         case PossibleAM:
                         case PossiblePM:
                         case PossibleBoth: {
                             const QDateTime copy(newCurrentValue.addSecs(12 * 60 * 60));
                             if (copy >= minimum && copy <= maximum) {
                                 state = Intermediate;
                                 done = true;
                             }
                             break; }
                         }
                     case MonthSection:
                         if (sn.count >= 3) {
                             int tmp = newCurrentValue.date().month();
                             // I know the first possible month makes the date too early
                             while ((tmp = findMonth(t, tmp + 1, i)) != -1) {
                                 const QDateTime copy(newCurrentValue.addMonths(tmp - newCurrentValue.date().month()));
                                 if (copy >= minimum && copy <= maximum)
                                     break; // break out of while
                             }
                             if (tmp == -1) {
                                 break;
                             }
                             state = Intermediate;
                             done = true;
                             break;
                         }
                         // fallthrough
                     default: {
                         int toMin;
                         int toMax;
                         if (sn.type & TimeSectionMask) {
                             if (newCurrentValue.daysTo(minimum) != 0) {
                                 break;
                             }
                             toMin = newCurrentValue.time().msecsTo(minimum.time());
                             if (newCurrentValue.daysTo(maximum) > 0) {
                                 toMax = -1; // can't get to max
                             } else {
                                 toMax = newCurrentValue.time().msecsTo(maximum.time());
                             }
                         } else {
                             toMin = newCurrentValue.daysTo(minimum);
                             toMax = newCurrentValue.daysTo(maximum);
                         }
                         const int maxChange = QDateTimeParser::maxChange(i);
                         if (toMin > maxChange) {
                             QDTPDEBUG << "invalid because toMin > maxChange" << toMin
                                       << maxChange << t << newCurrentValue << minimum;
                             state = Invalid;
                             done = true;
                             break;
                         } else if (toMax > maxChange) {
                             toMax = -1; // can't get to max
                         }
                         const int min = getDigit(minimum, i);
                         if (min == -1) {
                             qWarning("QDateTimeParser::parse Internal error 4 (%s)",
                                      qPrintable(sectionName(sn.type)));
                             state = Invalid;
                             done = true;
                             break;
                         }
                         int max = toMax != -1 ? getDigit(maximum, i) : absoluteMax(i, newCurrentValue);
                         int pos = cursorPosition - sn.pos;
                         if (pos < 0 || pos >= t.size())
                             pos = -1;
                         if (!potentialValue(t.simplified(), min, max, i, newCurrentValue, pos)) {
                             QDTPDEBUG << "invalid because potentialValue(" << t.simplified() << min << max
                                       << sectionName(sn.type) << "returned" << toMax << toMin << pos;
                             state = Invalid;
                             done = true;
                             break;
                         }
                         state = Intermediate;
                         done = true;
                         break; }
                     }
                 }
             }
         } else {
             if (context == FromString) {
                 // optimization
                 Q_ASSERT(getMaximum().date().toJulianDay() == 4642999);
                 if (newCurrentValue.date().toJulianDay() > 4642999)
                     state = Invalid;
             } else {
                 if (newCurrentValue > getMaximum())
                     state = Invalid;
             }
             QDTPDEBUG << "not checking intermediate because newCurrentValue is" << newCurrentValue << getMinimum() << getMaximum();
         }
     }
     StateNode node;
     node.input = input;
     node.state = state;
     node.conflicts = conflicts;
     node.value = newCurrentValue.toTimeSpec(spec);
     text = input;
     return node;
 }
parseFormat()
bool QDateTimeParser::parseFormat (const QString & format)
Definition at line 4769 of file qdatetime.cpp.
Referenced by QDate::fromString(), QTime::fromString(), QDateTime::fromString(), QLocale::toDate(), QLocale::toDateTime(), and QLocale::toTime().
 {
     const QLatin1Char quote('\'');
     const QLatin1Char slash('\\');
     const QLatin1Char zero('0');
     if (newFormat == displayFormat && !newFormat.isEmpty()) {
         return true;
     }
     QDTPDEBUGN("parseFormat: %s", newFormat.toLatin1().constData());
     QVector<SectionNode> newSectionNodes;
     Sections newDisplay = 0;
     QStringList newSeparators;
     int i, index = 0;
     int add = 0;
     QChar status(zero);
     const int max = newFormat.size();
     int lastQuote = -1;
     for (i = 0; i<max; ++i) {
         if (newFormat.at(i) == quote) {
             lastQuote = i;
             ++add;
             if (status != quote) {
                 status = quote;
             } else if (newFormat.at(i - 1) != slash) {
                 status = zero;
             }
         } else if (status != quote) {
             const char sect = newFormat.at(i).toLatin1();
             switch (sect) {
             case 'H':
             case 'h':
                 if (parserType != QVariant::Date) {
                     const Section hour = (sect == 'h') ? Hour12Section : Hour24Section;
                     const SectionNode sn = { hour, i - add, countRepeat(newFormat, i, 2) };
                     newSectionNodes.append(sn);
                     appendSeparator(&newSeparators, newFormat, index, i - index, lastQuote);
                     i += sn.count - 1;
                     index = i + 1;
                     newDisplay |= hour;
                 }
                 break;
             case 'm':
                 if (parserType != QVariant::Date) {
                     const SectionNode sn = { MinuteSection, i - add, countRepeat(newFormat, i, 2) };
                     newSectionNodes.append(sn);
                     appendSeparator(&newSeparators, newFormat, index, i - index, lastQuote);
                     i += sn.count - 1;
                     index = i + 1;
                     newDisplay |= MinuteSection;
                 }
                 break;
             case 's':
                 if (parserType != QVariant::Date) {
                     const SectionNode sn = { SecondSection, i - add, countRepeat(newFormat, i, 2) };
                     newSectionNodes.append(sn);
                     appendSeparator(&newSeparators, newFormat, index, i - index, lastQuote);
                     i += sn.count - 1;
                     index = i + 1;
                     newDisplay |= SecondSection;
                 }
                 break;
             case 'z':
                 if (parserType != QVariant::Date) {
                     const SectionNode sn = { MSecSection, i - add, countRepeat(newFormat, i, 3) < 3 ? 1 : 3 };
                     newSectionNodes.append(sn);
                     appendSeparator(&newSeparators, newFormat, index, i - index, lastQuote);
                     i += sn.count - 1;
                     index = i + 1;
                     newDisplay |= MSecSection;
                 }
                 break;
             case 'A':
             case 'a':
                 if (parserType != QVariant::Date) {
                     const bool cap = (sect == 'A');
                     const SectionNode sn = { AmPmSection, i - add, (cap ? 1 : 0) };
                     newSectionNodes.append(sn);
                     appendSeparator(&newSeparators, newFormat, index, i - index, lastQuote);
                     newDisplay |= AmPmSection;
                     if (i + 1 < newFormat.size()
                         && newFormat.at(i+1) == (cap ? QLatin1Char('P') : QLatin1Char('p'))) {
                         ++i;
                     }
                     index = i + 1;
                 }
                 break;
             case 'y':
                 if (parserType != QVariant::Time) {
                     const int repeat = countRepeat(newFormat, i, 4);
                     if (repeat >= 2) {
                         const SectionNode sn = { repeat == 4 ? YearSection : YearSection2Digits,
                                                  i - add, repeat == 4 ? 4 : 2 };
                         newSectionNodes.append(sn);
                         appendSeparator(&newSeparators, newFormat, index, i - index, lastQuote);
                         i += sn.count - 1;
                         index = i + 1;
                         newDisplay |= sn.type;
                     }
                 }
                 break;
             case 'M':
                 if (parserType != QVariant::Time) {
                     const SectionNode sn = { MonthSection, i - add, countRepeat(newFormat, i, 4) };
                     newSectionNodes.append(sn);
                     newSeparators.append(unquote(newFormat.mid(index, i - index)));
                     i += sn.count - 1;
                     index = i + 1;
                     newDisplay |= MonthSection;
                 }
                 break;
             case 'd':
                 if (parserType != QVariant::Time) {
                     const int repeat = countRepeat(newFormat, i, 4);
                     const SectionNode sn = { repeat >= 3 ? DayOfWeekSection : DaySection, i - add, repeat };
                     newSectionNodes.append(sn);
                     appendSeparator(&newSeparators, newFormat, index, i - index, lastQuote);
                     i += sn.count - 1;
                     index = i + 1;
                     newDisplay |= sn.type;
                 }
                 break;
             default:
                 break;
             }
         }
     }
     if (newSectionNodes.isEmpty() && context == DateTimeEdit) {
         return false;
     }
     if ((newDisplay & (AmPmSection|Hour12Section)) == Hour12Section) {
         const int max = newSectionNodes.size();
         for (int i=0; i<max; ++i) {
             SectionNode &node = newSectionNodes[i];
             if (node.type == Hour12Section)
                 node.type = Hour24Section;
         }
     }
     if (index < newFormat.size()) {
         appendSeparator(&newSeparators, newFormat, index, index - max, lastQuote);
     } else {
         newSeparators.append(QString());
     }
     displayFormat = newFormat;
     separators = newSeparators;
     sectionNodes = newSectionNodes;
     display = newDisplay;
     last.pos = -1;
 //     for (int i=0; i<sectionNodes.size(); ++i) {
 //         QDTPDEBUG << sectionName(sectionNodes.at(i).type) << sectionNodes.at(i).count;
 //     }
     QDTPDEBUG << newFormat << displayFormat;
     QDTPDEBUGN("separators:\n'%s'", separators.join(QLatin1String("\n")).toLatin1().constData());
     return true;
 }
parseSection()
int QDateTimeParser::parseSection (const QDateTime & currentValue, int sectionIndex, QString & txt, int & cursorPosition, int index, QDateTimeParser::State & state, int * used = 0) const
Warning
This function is not part of the public interface.:skipToNextSection
Parses the part of text that corresponds to s and returns the value of that field. Sets *stateptr to the right state if stateptr != 0.
Definition at line 5088 of file qdatetime.cpp.
 {
     state = Invalid;
     int num = 0;
     const SectionNode &sn = sectionNode(sectionIndex);
     if ((sn.type & Internal) == Internal) {
         qWarning("QDateTimeParser::parseSection Internal error (%s %d)",
                  qPrintable(sectionName(sn.type)), sectionIndex);
         return -1;
     }
     const int sectionmaxsize = sectionMaxSize(sectionIndex);
     QString sectiontext = text.mid(index, sectionmaxsize);
     int sectiontextSize = sectiontext.size();
     QDTPDEBUG << "sectionValue for" << sectionName(sn.type)
               << "with text" << text << "and st" << sectiontext
               << text.mid(index, sectionmaxsize)
               << index;
     int used = 0;
     switch (sn.type) {
     case AmPmSection: {
         const int ampm = findAmPm(sectiontext, sectionIndex, &used);
         switch (ampm) {
         case AM: // sectiontext == AM
         case PM: // sectiontext == PM
             num = ampm;
             state = Acceptable;
             break;
         case PossibleAM: // sectiontext => AM
         case PossiblePM: // sectiontext => PM
             num = ampm - 2;
             state = Intermediate;
             break;
         case PossibleBoth: // sectiontext => AM|PM
             num = 0;
             state = Intermediate;
             break;
         case Neither:
             state = Invalid;
             QDTPDEBUG << "invalid because findAmPm(" << sectiontext << ") returned -1";
             break;
         default:
             QDTPDEBUGN("This should never happen (findAmPm returned %d)", ampm);
             break;
         }
         if (state != Invalid) {
             QString str = text;
             text.replace(index, used, sectiontext.left(used));
         }
         break; }
     case MonthSection:
     case DayOfWeekSection:
         if (sn.count >= 3) {
             if (sn.type == MonthSection) {
                 int min = 1;
                 const QDate minDate = getMinimum().date();
                 if (currentValue.date().year() == minDate.year()) {
                     min = minDate.month();
                 }
                 num = findMonth(sectiontext.toLower(), min, sectionIndex, &sectiontext, &used);
             } else {
                 num = findDay(sectiontext.toLower(), 1, sectionIndex, &sectiontext, &used);
             }
             if (num != -1) {
                 state = (used == sectiontext.size() ? Acceptable : Intermediate);
                 QString str = text;
                 text.replace(index, used, sectiontext.left(used));
             } else {
                 state = Intermediate;
             }
             break; }
         // fall through
     case DaySection:
     case YearSection:
     case YearSection2Digits:
     case Hour12Section:
     case Hour24Section:
     case MinuteSection:
     case SecondSection:
     case MSecSection: {
         if (sectiontextSize == 0) {
             num = 0;
             used = 0;
             state = Intermediate;
         } else {
             const int absMax = absoluteMax(sectionIndex);
             QLocale loc;
             bool ok = true;
             int last = -1;
             used = -1;
             QString digitsStr(sectiontext);
             for (int i = 0; i < sectiontextSize; ++i) {
                 if (digitsStr.at(i).isSpace()) {
                     sectiontextSize = i;
                     break;
                 }
             }
             const int max = qMin(sectionmaxsize, sectiontextSize);
             for (int digits = max; digits >= 1; --digits) {
                 digitsStr.truncate(digits);
                 int tmp = (int)loc.toUInt(digitsStr, &ok, 10);
                 if (ok && sn.type == Hour12Section) {
                     if (tmp > 12) {
                         tmp = -1;
                         ok = false;
                     } else if (tmp == 12) {
                         tmp = 0;
                     }
                 }
                 if (ok && tmp <= absMax) {
                     QDTPDEBUG << sectiontext.left(digits) << tmp << digits;
                     last = tmp;
                     used = digits;
                     break;
                 }
             }
             if (last == -1) {
                 QChar first(sectiontext.at(0));
                 if (separators.at(sectionIndex + 1).startsWith(first)) {
                     used = 0;
                     state = Intermediate;
                 } else {
                     state = Invalid;
                     QDTPDEBUG << "invalid because" << sectiontext << "can't become a uint" << last << ok;
                 }
             } else {
                 num += last;
                 const FieldInfo fi = fieldInfo(sectionIndex);
                 const bool done = (used == sectionmaxsize);
                 if (!done && fi & Fraction) { // typing 2 in a zzz field should be .200, not .002
                     for (int i=used; i<sectionmaxsize; ++i) {
                         num *= 10;
                     }
                 }
                 const int absMin = absoluteMin(sectionIndex);
                 if (num < absMin) {
                     state = done ? Invalid : Intermediate;
                     if (done)
                         QDTPDEBUG << "invalid because" << num << "is less than absoluteMin" << absMin;
                 } else if (num > absMax) {
                     state = Intermediate;
                 } else if (!done && (fi & (FixedWidth|Numeric)) == (FixedWidth|Numeric)) {
                     if (skipToNextSection(sectionIndex, currentValue, digitsStr)) {
                         state = Acceptable;
                         const int missingZeroes = sectionmaxsize - digitsStr.size();
                         text.insert(index, QString().fill(QLatin1Char('0'), missingZeroes));
                         used = sectionmaxsize;
                         cursorPosition += missingZeroes;
                     } else {
                         state = Intermediate;;
                     }
                 } else {
                     state = Acceptable;
                 }
             }
         }
         break; }
     default:
         qWarning("QDateTimeParser::parseSection Internal error (%s %d)",
                  qPrintable(sectionName(sn.type)), sectionIndex);
         return -1;
     }
     if (usedptr)
         *usedptr = used;
     return (state != Invalid ? num : -1);
 }
potentialValue()
bool QDateTimeParser::potentialValue (const QString & str, int min, int max, int index, const QDateTime & currentValue, int insert) const
Warning
This function is not part of the public interface. Returns true if str can be modified to represent a number that is within min and max.
Definition at line 5964 of file qdatetime.cpp.
 {
     if (str.isEmpty()) {
         return true;
     }
     const int size = sectionMaxSize(index);
     int val = (int)locale().toUInt(str);
     const SectionNode &sn = sectionNode(index);
     if (sn.type == YearSection2Digits) {
         val += currentValue.date().year() - (currentValue.date().year() % 100);
     }
     if (val >= min && val <= max && str.size() == size) {
         return true;
     } else if (val > max) {
         return false;
     } else if (str.size() == size && val < min) {
         return false;
     }
     const int len = size - str.size();
     for (int i=0; i<len; ++i) {
         for (int j=0; j<10; ++j) {
             if (potentialValue(str + QLatin1Char('0' + j), min, max, index, currentValue, insert)) {
                 return true;
             } else if (insert >= 0) {
                 QString tmp = str;
                 tmp.insert(insert, QLatin1Char('0' + j));
                 if (potentialValue(tmp, min, max, index, currentValue, insert))
                     return true;
             }
         }
     }
     return false;
 }
sectionFormat() [1/2]
QString QDateTimeParser::sectionFormat (int index) const
Warning
This function is not part of the public interface. Get a number that str can become which is between min and max or -1 if this is not possible.
Definition at line 5923 of file qdatetime.cpp.
 {
     const SectionNode &sn = sectionNode(index);
     return sectionFormat(sn.type, sn.count);
 }
sectionFormat() [2/2]
QString QDateTimeParser::sectionFormat (Section s, int count) const
Definition at line 5929 of file qdatetime.cpp.
 {
     QChar fillChar;
     switch (s) {
     case AmPmSection: return count == 1 ? QLatin1String("AP") : QLatin1String("ap");
     case MSecSection: fillChar = QLatin1Char('z'); break;
     case SecondSection: fillChar = QLatin1Char('s'); break;
     case MinuteSection: fillChar = QLatin1Char('m'); break;
     case Hour24Section: fillChar = QLatin1Char('H'); break;
     case Hour12Section: fillChar = QLatin1Char('h'); break;
     case DayOfWeekSection:
     case DaySection: fillChar = QLatin1Char('d'); break;
     case MonthSection: fillChar = QLatin1Char('M'); break;
     case YearSection2Digits:
     case YearSection: fillChar = QLatin1Char('y'); break;
     default:
         qWarning("QDateTimeParser::sectionFormat Internal error (%s)",
                  qPrintable(sectionName(s)));
         return QString();
     }
     if (fillChar.isNull()) {
         qWarning("QDateTimeParser::sectionFormat Internal error 2");
         return QString();
     }
     QString str;
     str.fill(fillChar, count);
     return str;
 }
sectionMaxSize() [1/2]
int QDateTimeParser::sectionMaxSize (int index) const
Definition at line 5033 of file qdatetime.cpp.
 {
     const SectionNode &sn = sectionNode(index);
     return sectionMaxSize(sn.type, sn.count);
 }
sectionMaxSize() [2/2]
int QDateTimeParser::sectionMaxSize (Section s, int count) const
Definition at line 4961 of file qdatetime.cpp.
 {
 #ifndef QT_NO_TEXTDATE
     int mcount = 12;
 #endif
     switch (s) {
     case FirstSection:
     case NoSection:
     case LastSection: return 0;
     case AmPmSection: {
         const int lowerMax = qMin(getAmPmText(AmText, LowerCase).size(),
                                   getAmPmText(PmText, LowerCase).size());
         const int upperMax = qMin(getAmPmText(AmText, UpperCase).size(),
                                   getAmPmText(PmText, UpperCase).size());
         return qMin(4, qMin(lowerMax, upperMax));
     }
     case Hour24Section:
     case Hour12Section:
     case MinuteSection:
     case SecondSection:
     case DaySection: return 2;
     case DayOfWeekSection:
 #ifdef QT_NO_TEXTDATE
         return 2;
 #else
         mcount = 7;
         // fall through
 #endif
     case MonthSection:
         if (count <= 2)
             return 2;
 #ifdef QT_NO_TEXTDATE
         return 2;
 #else
         {
             int ret = 0;
             const QLocale l = locale();
             for (int i=1; i<=mcount; ++i) {
                 const QString str = (s == MonthSection
                                      ? l.monthName(i, count == 4 ? QLocale::LongFormat : QLocale::ShortFormat)
                                      : l.dayName(i, count == 4 ? QLocale::LongFormat : QLocale::ShortFormat));
                 ret = qMax(str.size(), ret);
             }
             return ret;
         }
 #endif
     case MSecSection: return 3;
     case YearSection: return 4;
     case YearSection2Digits: return 2;
     case CalendarPopupSection:
     case Internal:
     case TimeSectionMask:
     case DateSectionMask:
         qWarning("QDateTimeParser::sectionMaxSize: Invalid section %s",
                  sectionName(s).toLatin1().constData());
     case NoSectionIndex:
     case FirstSectionIndex:
     case LastSectionIndex:
     case CalendarPopupIndex:
         // these cases can't happen
         break;
     }
     return -1;
 }
sectionName()
QString QDateTimeParser::sectionName (int s) const
For debugging.
Warning
This function is not part of the public interface. Returns the name of the section s.
Definition at line 6044 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged().
 {
     switch (s) {
     case QDateTimeParser::AmPmSection: return QLatin1String("AmPmSection");
     case QDateTimeParser::DaySection: return QLatin1String("DaySection");
     case QDateTimeParser::DayOfWeekSection: return QLatin1String("DayOfWeekSection");
     case QDateTimeParser::Hour24Section: return QLatin1String("Hour24Section");
     case QDateTimeParser::Hour12Section: return QLatin1String("Hour12Section");
     case QDateTimeParser::MSecSection: return QLatin1String("MSecSection");
     case QDateTimeParser::MinuteSection: return QLatin1String("MinuteSection");
     case QDateTimeParser::MonthSection: return QLatin1String("MonthSection");
     case QDateTimeParser::SecondSection: return QLatin1String("SecondSection");
     case QDateTimeParser::YearSection: return QLatin1String("YearSection");
     case QDateTimeParser::YearSection2Digits: return QLatin1String("YearSection2Digits");
     case QDateTimeParser::NoSection: return QLatin1String("NoSection");
     case QDateTimeParser::FirstSection: return QLatin1String("FirstSection");
     case QDateTimeParser::LastSection: return QLatin1String("LastSection");
     default: return QLatin1String("Unknown section ") + QString::number(s);
     }
 }
sectionNode()
const QDateTimeParser::SectionNode & QDateTimeParser::sectionNode (int sectionIndex) const
Returns the sectionNode for the Section s.
Warning
This function is not part of the public interface.
Definition at line 4654 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::setSelected(), and QDateTimeEditPrivate::stepBy().
 {
     if (sectionIndex < 0) {
         switch (sectionIndex) {
         case FirstSectionIndex:
             return first;
         case LastSectionIndex:
             return last;
         case NoSectionIndex:
             return none;
         }
     } else if (sectionIndex < sectionNodes.size()) {
         return sectionNodes.at(sectionIndex);
     }
     qWarning("QDateTimeParser::sectionNode() Internal error (%d)",
              sectionIndex);
     return none;
 }
sectionPos() [1/2]
int QDateTimeParser::sectionPos (int sectionIndex) const
Returns the starting position for section s.
Warning
This function is not part of the public interface.
Definition at line 4689 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QDateTimeEditPrivate::clearSection(), QDateTimeEditPrivate::closestSection(), QDateTimeEditPrivate::sectionAt(), QDateTimeEditPrivate::setSelected(), and QDateTimeEditPrivate::updateEdit().
 {
     return sectionPos(sectionNode(sectionIndex));
 }
sectionPos() [2/2]
int QDateTimeParser::sectionPos (const SectionNode & sn) const
Definition at line 4694 of file qdatetime.cpp.
 {
     switch (sn.type) {
     case FirstSection: return 0;
     case LastSection: return displayText().size() - 1;
     default: break;
     }
     if (sn.pos == -1) {
         qWarning("QDateTimeParser::sectionPos Internal error (%s)", qPrintable(sectionName(sn.type)));
         return -1;
     }
     return sn.pos;
 }
sectionSize()
int QDateTimeParser::sectionSize (int sectionIndex) const
Returns the size of section s.
Warning
This function is not part of the public interface.
Definition at line 4943 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QDateTimeEditPrivate::clearSection(), QDateTimeEditPrivate::closestSection(), QDateTimeEditPrivate::sectionAt(), and QDateTimeEditPrivate::setSelected().
 {
     if (sectionIndex < 0)
         return 0;
     if (sectionIndex >= sectionNodes.size()) {
         qWarning("QDateTimeParser::sectionSize Internal error (%d)", sectionIndex);
         return -1;
     }
     if (sectionIndex == sectionNodes.size() - 1) {
         return displayText().size() - sectionPos(sectionIndex) - separators.last().size();
     } else {
         return sectionPos(sectionIndex + 1) - sectionPos(sectionIndex)
             - separators.at(sectionIndex + 1).size();
     }
 }
sectionText() [1/2]
QString QDateTimeParser::sectionText (int sectionIndex) const
Definition at line 5064 of file qdatetime.cpp.
 {
     const SectionNode &sn = sectionNode(sectionIndex);
     switch (sn.type) {
     case NoSectionIndex:
     case FirstSectionIndex:
     case LastSectionIndex:
         return QString();
     default: break;
     }
     return displayText().mid(sn.pos, sectionSize(sectionIndex));
 }
sectionText() [2/2]
QString QDateTimeParser::sectionText (const QString & text, int sectionIndex, int index) const
Returns the text of section s.
Warning
This function is not part of the public interface.
This function operates on the arg text rather than edit->text().
Definition at line 5050 of file qdatetime.cpp.
 {
     const SectionNode &sn = sectionNode(sectionIndex);
     switch (sn.type) {
     case NoSectionIndex:
     case FirstSectionIndex:
     case LastSectionIndex:
         return QString();
     default: break;
     }
     return text.mid(index, sectionSize(sectionIndex));
 }
sectionType()
QDateTimeParser::Section QDateTimeParser::sectionType (int index) const
Definition at line 4674 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged().
 {
     return sectionNode(sectionIndex).type;
 }
setDigit()
bool QDateTimeParser::setDigit (QDateTime & v, int index, int newVal) const
Sets a digit in a datetime.
Warning
This function is not part of the public interface. E.g.
QDateTime var(QDate(2004, 02, 02)); int digit = getDigit(var, Year); digit = 2004 setDigit(&var, Year, 2005); digit = getDigit(var, Year); digit = 2005
Definition at line 4520 of file qdatetime.cpp.
Referenced by QDateTimeEditPrivate::stepBy().
 {
     if (index < 0 || index >= sectionNodes.size()) {
 #ifndef QT_NO_DATESTRING
         qWarning("QDateTimeParser::setDigit() Internal error (%s %d %d)",
                  qPrintable(v.toString()), index, newVal);
 #else
         qWarning("QDateTimeParser::setDigit() Internal error (%d %d)", index, newVal);
 #endif
         return false;
     }
     const SectionNode &node = sectionNodes.at(index);
     int year, month, day, hour, minute, second, msec;
     year = v.date().year();
     month = v.date().month();
     day = v.date().day();
     hour = v.time().hour();
     minute = v.time().minute();
     second = v.time().second();
     msec = v.time().msec();
     switch (node.type) {
     case Hour24Section: case Hour12Section: hour = newVal; break;
     case MinuteSection: minute = newVal; break;
     case SecondSection: second = newVal; break;
     case MSecSection: msec = newVal; break;
     case YearSection2Digits:
     case YearSection: year = newVal; break;
     case MonthSection: month = newVal; break;
     case DaySection:
     case DayOfWeekSection:
         if (newVal > 31) {
             // have to keep legacy behavior. setting the
             // date to 32 should return false. Setting it
             // to 31 for february should return true
             return false;
         }
         day = newVal;
         break;
     case AmPmSection: hour = (newVal == 0 ? hour % 12 : (hour % 12) + 12); break;
     default:
         qWarning("QDateTimeParser::setDigit() Internal error (%s)",
                  qPrintable(sectionName(node.type)));
         break;
     }
     if (!(node.type & (DaySection|DayOfWeekSection))) {
         if (day < cachedDay)
             day = cachedDay;
         const int max = QDate(year, month, 1).daysInMonth();
         if (day > max) {
             day = max;
         }
     }
     if (QDate::isValid(year, month, day) && QTime::isValid(hour, minute, second, msec)) {
         v = QDateTime(QDate(year, month, day), QTime(hour, minute, second, msec), spec);
         return true;
     }
     return false;
 }
skipToNextSection()
bool QDateTimeParser::skipToNextSection (int section, const QDateTime & current, const QString & sectionText) const
Definition at line 6001 of file qdatetime.cpp.
 {
     Q_ASSERT(current >= getMinimum() && current <= getMaximum());
     const SectionNode &node = sectionNode(index);
     Q_ASSERT(text.size() < sectionMaxSize(index));
     const QDateTime maximum = getMaximum();
     const QDateTime minimum = getMinimum();
     QDateTime tmp = current;
     int min = absoluteMin(index);
     setDigit(tmp, index, min);
     if (tmp < minimum) {
         min = getDigit(minimum, index);
     }
     int max = absoluteMax(index, current);
     setDigit(tmp, index, max);
     if (tmp > maximum) {
         max = getDigit(maximum, index);
     }
     int pos = cursorPosition() - node.pos;
     if (pos < 0 || pos >= text.size())
         pos = -1;
     const bool potential = potentialValue(text, min, max, index, current, pos);
     return !potential;
     /* If the value potentially can become another valid entry we
      * don't want to skip to the next. E.g. In a M field (month
      * without leading 0 if you type 1 we don't want to autoskip but
      * if you type 3 we do
     */
 }
stateName()
QString QDateTimeParser::stateName (int s) const
For debugging.
Warning
This function is not part of the public interface. Returns the name of the state s.
Definition at line 6073 of file qdatetime.cpp.
 {
     switch (s) {
     case Invalid: return QLatin1String("Invalid");
     case Intermediate: return QLatin1String("Intermediate");
     case Acceptable: return QLatin1String("Acceptable");
     default: return QLatin1String("Unknown state ") + QString::number(s);
     }
 }
Properties
cachedDay
int QDateTimeParser::cachedDay mutable
Definition at line 261 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::clearCache(), QDateTimeEditPrivate::QDateTimeEditPrivate(), and QDateTimeEditPrivate::stepBy().
context
Context QDateTimeParser::context
Definition at line 273 of file qdatetime_p.h.
currentSectionIndex
int QDateTimeParser::currentSectionIndex mutable
Definition at line 259 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QDateTimeEditPrivate::interpret(), QDateTimeEditPrivate::isSeparatorKey(), QDateTimeEditPrivate::QDateTimeEditPrivate(), and QDateTimeEditPrivate::updateEdit().
defaultLocale
QLocale QDateTimeParser::defaultLocale
Definition at line 267 of file qdatetime_p.h.
Referenced by QLocale::toDate(), QLocale::toDateTime(), and QLocale::toTime().
display
Sections QDateTimeParser::display
Definition at line 260 of file qdatetime_p.h.
displayFormat
QString QDateTimeParser::displayFormat
Definition at line 266 of file qdatetime_p.h.
first
SectionNode QDateTimeParser::first
Definition at line 264 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::QDateTimeEditPrivate().
fixday
bool QDateTimeParser::fixday
Definition at line 270 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::QDateTimeEditPrivate().
last
SectionNode QDateTimeParser::last
Definition at line 264 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::QDateTimeEditPrivate().
none
SectionNode QDateTimeParser::none
Definition at line 264 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::QDateTimeEditPrivate().
parserType
QVariant::Type QDateTimeParser::parserType
Definition at line 268 of file qdatetime_p.h.
popup
SectionNode QDateTimeParser::popup
Definition at line 264 of file qdatetime_p.h.
sectionNodes
QVector<SectionNode> QDateTimeParser::sectionNodes
Definition at line 263 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::_q_editorCursorPositionChanged(), QDateTimeEditPrivate::absoluteIndex(), QDateTimeEditPrivate::closestSection(), QDateTimeEditPrivate::init(), QDateTimeEditPrivate::isSeparatorKey(), QDateTimeEditPrivate::nextPrevSection(), QDateTimeEditPrivate::sectionAt(), and QDateTimeEditPrivate::validateAndInterpret().
separators
QStringList QDateTimeParser::separators
Definition at line 265 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::closestSection(), QDateTimeEditPrivate::isSeparatorKey(), and QDateTimeEditPrivate::sectionAt().
spec
Qt::TimeSpec QDateTimeParser::spec
Definition at line 272 of file qdatetime_p.h.
Referenced by QDateTimeEditPrivate::getZeroVariant(), QDateTimeEditPrivate::stepBy(), QDateTimeEditPrivate::updateTimeSpec(), and QDateTimeEditPrivate::valueFromText().
text
QString QDateTimeParser::text mutable
Definition at line 262 of file qdatetime_p.h.
The documentation for this class was generated from the following files:
/src/corelib/tools/qdatetime_p.h
/src/corelib/tools/qdatetime.cpp