Qt 4.8: QLibraryInfo Class Reference
QLibraryInfo Class Reference
The QLibraryInfo class provides information about the Qt library.
#include <qlibraryinfo.h>
Public Types
enum LibraryLocation {
PrefixPath, DocumentationPath, HeadersPath, LibrariesPath,
BinariesPath, PluginsPath, DataPath, TranslationsPath,
SettingsPath, DemosPath, ExamplesPath, ImportsPath
}
This enum type is used to specify a specific location specifier:
Static Public Functions
static QDate buildDate ()
Returns the installation date for this build of Qt.
static QString buildKey ()
Returns a unique key identifying this build of Qt and its configurations.
static QString licensedProducts ()
Returns the products that the license for this build of Qt has access to.
static QString licensee ()
Returns the person to whom this build of Qt is licensed.
static QString location (LibraryLocation)
Returns the location specified by loc.
Private Functions
QLibraryInfo ()
You cannot create a QLibraryInfo, instead only the static functions are available to query information.
Detailed Description
The QLibraryInfo class provides information about the Qt library.
Many pieces of information are established when Qt is configured. Installation paths, license information, and even a unique build key. This class provides an abstraction for accessing this information.
Function Return value
buildKey() A string that identifies the Qt version and the configuration. This key is used to ensure that plugins link against the same version of Qt as the application.
location() The path to a certain Qt component (e.g., documentation, header files).
licensee(), licensedProducts() Licensing information.
You can also use a qt.conf file to override the hard-coded paths that are compiled into the Qt library. For more information, see the {Using qt.conf} documentation.
See also
QSysInfo, {Using qt.conf}
Definition at line 56 of file qlibraryinfo.h.
Enumerations
LibraryLocation
enum QLibraryInfo::LibraryLocation
This enum type is used to specify a specific location specifier:
PrefixPath The default prefix for all paths.
library location
DocumentationPath The location for documentation upon install.
HeadersPath The location for all headers.
LibrariesPath The location of installed libraries.
BinariesPath The location of installed Qt binaries (tools and applications).
PluginsPath The location of installed Qt plugins.
ImportsPath The location of installed QML extensions to import.
DataPath The location of general Qt data.
TranslationsPath The location of translation information for Qt strings.
SettingsPath The location for Qt settings.
ExamplesPath The location for examples upon install.
DemosPath The location for demos upon install.
See also
location()
Enumerator
PrefixPath
DocumentationPath
HeadersPath
LibrariesPath
BinariesPath
PluginsPath
DataPath
TranslationsPath
SettingsPath
DemosPath
ExamplesPath
ImportsPath
Definition at line 67 of file qlibraryinfo.h.
     {
         PrefixPath,
         DocumentationPath,
         HeadersPath,
         LibrariesPath,
         BinariesPath,
         PluginsPath,
         DataPath,
         TranslationsPath,
         SettingsPath,
         DemosPath,
         ExamplesPath,
         ImportsPath
     };
Constructors and Destructors
QLibraryInfo()
QLibraryInfo::QLibraryInfo () private
You cannot create a QLibraryInfo, instead only the static functions are available to query information.
Warning
This function is not part of the public interface.
Definition at line 182 of file qlibraryinfo.cpp.
 { }
Functions
buildDate()
QDate QLibraryInfo::buildDate () static
Returns the installation date for this build of Qt.
Since
4.6 The install date will usually be the last time that Qt sources were configured.
Definition at line 236 of file qlibraryinfo.cpp.
Referenced by qt_eval_days_left().
 {
     return QDate::fromString(QString::fromLatin1(qt_configure_installation + 12), Qt::ISODate);
 }
buildKey()
QString QLibraryInfo::buildKey () static
Returns a unique key identifying this build of Qt and its configurations.
This key is not globally unique, rather only useful for establishing of two configurations are compatible. This can be used to compare with the QT_BUILD_KEY preprocessor symbol.
See also
location()
Definition at line 221 of file qlibraryinfo.cpp.
 {
     return QString::fromLatin1(QT_BUILD_KEY);
 }
licensedProducts()
QString QLibraryInfo::licensedProducts () static
Returns the products that the license for this build of Qt has access to.
See also
licensee()
Definition at line 205 of file qlibraryinfo.cpp.
 {
     const char *str = QT_CONFIGURE_LICENSED_PRODUCTS;
     return QString::fromLatin1(str);
 }
licensee()
QString QLibraryInfo::licensee () static
Returns the person to whom this build of Qt is licensed.
See also
licensedProducts()
Definition at line 192 of file qlibraryinfo.cpp.
Referenced by qt_eval_string().
 {
     const char *str = QT_CONFIGURE_LICENSEE;
     return QString::fromLocal8Bit(str);
 }
location()
QString QLibraryInfo::location (LibraryLocation loc) static
Returns the location specified by loc.
Definition at line 248 of file qlibraryinfo.cpp.
Referenced by QCoreApplicationPrivate::appendApplicationPathToLibraryPaths(), QPlatformFontDatabase::fontDir(), initDefaultPaths(), QCoreApplication::libraryPaths(), QDeclarativeImportDatabase::QDeclarativeImportDatabase(), QFontEngineQPF::QFontEngineQPF(), qwsFontPath(), QFactoryLoader::refreshAll(), and QCoreApplication::removeLibraryPath().
 {
     QString ret;
     if(!QLibraryInfoPrivate::configuration()) {
         const char *path = 0;
         switch (loc) {
 #ifdef QT_CONFIGURE_PREFIX_PATH
         case PrefixPath:
             path = QT_CONFIGURE_PREFIX_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_DOCUMENTATION_PATH
         case DocumentationPath:
             path = QT_CONFIGURE_DOCUMENTATION_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_HEADERS_PATH
         case HeadersPath:
             path = QT_CONFIGURE_HEADERS_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_LIBRARIES_PATH
         case LibrariesPath:
             path = QT_CONFIGURE_LIBRARIES_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_BINARIES_PATH
         case BinariesPath:
             path = QT_CONFIGURE_BINARIES_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_PLUGINS_PATH
         case PluginsPath:
             path = QT_CONFIGURE_PLUGINS_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_IMPORTS_PATH
         case ImportsPath:
             path = QT_CONFIGURE_IMPORTS_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_DATA_PATH
         case DataPath:
             path = QT_CONFIGURE_DATA_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_TRANSLATIONS_PATH
         case TranslationsPath:
             path = QT_CONFIGURE_TRANSLATIONS_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_SETTINGS_PATH
         case SettingsPath:
             path = QT_CONFIGURE_SETTINGS_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_EXAMPLES_PATH
         case ExamplesPath:
             path = QT_CONFIGURE_EXAMPLES_PATH;
             break;
 #endif
 #ifdef QT_CONFIGURE_DEMOS_PATH
         case DemosPath:
             path = QT_CONFIGURE_DEMOS_PATH;
             break;
 #endif
         default:
             break;
         }
         if (path)
             ret = QString::fromLocal8Bit(path);
     } else {
         QString key;
         QString defaultValue;
         switch(loc) {
         case PrefixPath:
             key = QLatin1String("Prefix");
             break;
         case DocumentationPath:
             key = QLatin1String("Documentation");
             defaultValue = QLatin1String("doc");
             break;
         case HeadersPath:
             key = QLatin1String("Headers");
             defaultValue = QLatin1String("include");
             break;
         case LibrariesPath:
             key = QLatin1String("Libraries");
             defaultValue = QLatin1String("lib");
             break;
         case BinariesPath:
             key = QLatin1String("Binaries");
             defaultValue = QLatin1String("bin");
             break;
         case PluginsPath:
             key = QLatin1String("Plugins");
             defaultValue = QLatin1String("plugins");
             break;
         case ImportsPath:
             key = QLatin1String("Imports");
             defaultValue = QLatin1String("imports");
             break;
         case DataPath:
             key = QLatin1String("Data");
             break;
         case TranslationsPath:
             key = QLatin1String("Translations");
             defaultValue = QLatin1String("translations");
             break;
         case SettingsPath:
             key = QLatin1String("Settings");
             break;
         case ExamplesPath:
             key = QLatin1String("Examples");
             break;
         case DemosPath:
             key = QLatin1String("Demos");
             break;
         default:
             break;
         }
         if(!key.isNull()) {
             QSettings *config = QLibraryInfoPrivate::configuration();
             config->beginGroup(QLatin1String("Paths"));
             QString subKey;
             {
                 /*
                   find the child group whose version number is closest
                   to the library version.  for example and we have the
                   following groups:
                   Paths
                   Paths/4.0
                   Paths/4.1.2
                   Paths/4.2.5
                   Paths/5
                   if QT_VERSION is 4.0.1, then we use 'Paths/4.0'
                   if QT_VERSION is 4.1.5, then we use 'Paths/4.1.2'
                   if QT_VERSION is 4.6.3, then we use 'Paths/4.2.5'
                   if QT_VERSION is 6.0.2, then we use 'Paths/5'
                   note: any of the trailing version numbers may be
                   omitted (in which case, they default to zero),
                   i.e. 4 == 4.0.0, 4.1 == 4.1.0, and so on
                 */
                 enum {
                     QT_MAJOR = ((QT_VERSION >> 16) & 0xFF),
                     QT_MINOR = ((QT_VERSION >> 8) & 0xFF),
                     QT_PATCH = (QT_VERSION & 0xFF)
                 };
                 int maj = 0, min = 0, pat = 0;
                 QStringList children = config->childGroups();
                 for(int child = 0; child < children.size(); ++child) {
                     QString cver = children.at(child);
                     QStringList cver_list = cver.split(QLatin1Char('.'));
                     if(cver_list.size() > 0 && cver_list.size() < 4) {
                         bool ok;
                         int cmaj = -1, cmin = -1, cpat = -1;
                         cmaj = cver_list[0].toInt(&ok);
                         if(!ok || cmaj < 0)
                             continue;
                         if(cver_list.size() >= 2) {
                             cmin = cver_list[1].toInt(&ok);
                             if(!ok)
                                 continue;
                             if(cmin < 0)
                                 cmin = -1;
                         }
                         if(cver_list.size() >= 3) {
                             cpat = cver_list[2].toInt(&ok);
                             if(!ok)
                                 continue;
                             if(cpat < 0)
                                 cpat = -1;
                         }
                         if((cmaj >= maj && cmaj <= QT_MAJOR) &&
                            (cmin == -1 || (cmin >= min && cmin <= QT_MINOR)) &&
                            (cpat == -1 || (cpat >= pat && cpat <= QT_PATCH)) &&
                            config->contains(cver + QLatin1Char('/') + key)) {
                             subKey = cver + QLatin1Char('/');
                             maj = cmaj;
                             min = cmin;
                             pat = cpat;
                         }
                     }
                 }
             }
             ret = config->value(subKey + key, defaultValue).toString();
             // expand environment variables in the form $(ENVVAR)
             int rep;
             QRegExp reg_var(QLatin1String("\\$\\(.*\\)"));
             reg_var.setMinimal(true);
             while((rep = reg_var.indexIn(ret)) != -1) {
                 ret.replace(rep, reg_var.matchedLength(),
                             QString::fromLocal8Bit(qgetenv(ret.mid(rep + 2,
                                 reg_var.matchedLength() - 3).toLatin1().constData()).constData()));
             }
 #ifdef QLIBRARYINFO_EPOCROOT
             // $${EPOCROOT} is a special case, resolve it similarly to qmake.
             QRegExp epocrootMatcher(QLatin1String("\\$\\$\\{EPOCROOT\\}"));
             if ((rep = epocrootMatcher.indexIn(ret)) != -1)
                 ret.replace(rep, epocrootMatcher.matchedLength(), qt_epocRoot());
 #endif
             config->endGroup();
         }
     }
     if (QDir::isRelativePath(ret)) {
         QString baseDir;
         if (loc == PrefixPath) {
             // we make the prefix path absolute to the executable's directory
 #ifdef BOOTSTRAPPING
             baseDir = QFileInfo(qmake_libraryInfoFile()).absolutePath();
 #else
             if (QCoreApplication::instance()) {
 #ifdef Q_OS_MAC
                 CFBundleRef bundleRef = CFBundleGetMainBundle();
                 if (bundleRef) {
                     QCFType<CFURLRef> urlRef = CFBundleCopyBundleURL(bundleRef);
                     if (urlRef) {
                         QCFString path = CFURLCopyFileSystemPath(urlRef, kCFURLPOSIXPathStyle);
                         return QDir::cleanPath(QString(path) + QLatin1String("/Contents/") + ret);
                     }
                 }
 #endif
                 baseDir = QCoreApplication::applicationDirPath();
             } else {
                 baseDir = QDir::currentPath();
             }
 #endif
         } else {
             // we make any other path absolute to the prefix directory
             baseDir = location(PrefixPath);
         }
         ret = QDir::cleanPath(baseDir + QLatin1Char('/') + ret);
     }
     return ret;
 }
The documentation for this class was generated from the following files:
/src/corelib/global/qlibraryinfo.h
/src/corelib/global/qlibraryinfo.cpp