Qt 4.8: QPatternist::DecimalMathematician Class Reference
QPatternist::DecimalMathematician Class Reference
#include <qatomicmathematicians_p.h>
Public Functions
virtual Item calculate (const Item &o1, const Operator op, const Item &o2, const QExplicitlySharedDataPointer< DynamicContext > &context) const
DecimalMathematician (const SourceLocationReflection *const r)
Public Functions inherited from QPatternist::AtomicMathematician
virtual ~AtomicMathematician ()
Public Functions inherited from QPatternist::AtomicTypeVisitorResult
AtomicTypeVisitorResult ()
virtual ~AtomicTypeVisitorResult ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::DelegatingSourceLocationReflection
virtual const SourceLocationReflection * actualReflection () const
DelegatingSourceLocationReflection (const SourceLocationReflection *const r)
virtual QString description () const
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Additional Inherited Members
Public Types inherited from QPatternist::AtomicMathematician
enum Operator {
Div = 1, IDiv = 2, Substract = 4, Mod = 8,
Multiply = 16, Add = 32
}
typedef QFlags< Operator > Operators
typedef QExplicitlySharedDataPointer< AtomicMathematician > Ptr
Public Types inherited from QPatternist::AtomicTypeVisitorResult
typedef QExplicitlySharedDataPointer< AtomicTypeVisitorResult > Ptr
Static Public Functions inherited from QPatternist::AtomicMathematician
static QString displayName (const AtomicMathematician::Operator op)
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 75 of file qatomicmathematicians_p.h.
Constructors and Destructors
DecimalMathematician()
QPatternist::DecimalMathematician::DecimalMathematician (const SourceLocationReflection *const r) inline
Definition at line 79 of file qatomicmathematicians_p.h.
                                                                              : DelegatingSourceLocationReflection(r)
         {
         }
Functions
calculate()
Item DecimalMathematician::calculate (const Item & o1, const Operator op, const Item & o2, const QExplicitlySharedDataPointer< DynamicContext > & context) const virtual
Implements QPatternist::AtomicMathematician.
Definition at line 84 of file qatomicmathematicians.cpp.
Referenced by QPatternist::DateTimeDurationMathematician::DateTimeDurationMathematician(), DecimalMathematician(), QPatternist::DurationNumericMathematician::DurationNumericMathematician(), and QPatternist::IntegerMathematician::IntegerMathematician().
 {
     switch(op)
     {
         case Div:
         {
             if(o2.as<Numeric>()->toInteger() == 0)
             {
                 context->error(divZeroInvalid(), ReportContext::FOAR0001, this);
                 return Item(); /* Silences source code analyzer warning. */
             }
             else
                 return toItem(Decimal::fromValue(o1.as<Numeric>()->toDecimal() / o2.as<Numeric>()->toDecimal()));
         }
         case IDiv:
         {
             if(o2.as<Numeric>()->toInteger() == 0)
             {
                 context->error(idivZeroInvalid(), ReportContext::FOAR0001, this);
                 return Item(); /* Silences source code analyzer warning. */
             }
             else
                 return Integer::fromValue(static_cast<xsInteger>(o1.as<Numeric>()->toDecimal() /
                                                                  o2.as<Numeric>()->toDecimal()));
         }
         case Substract:
             return toItem(Decimal::fromValue(o1.as<Numeric>()->toDecimal() - o2.as<Numeric>()->toDecimal()));
         case Mod:
         {
             if(o2.as<Numeric>()->toInteger() == 0)
             {
                 context->error(modZeroInvalid(), ReportContext::FOAR0001, this);
                 return Item(); /* Silences source code analyzer warning. */
             }
             else
                 return toItem(Decimal::fromValue(::fmod(o1.as<Numeric>()->toDecimal(), o2.as<Numeric>()->toDecimal())));
         }
         case Multiply:
             return toItem(Decimal::fromValue(o1.as<Numeric>()->toDecimal() * o2.as<Numeric>()->toDecimal()));
         case Add:
             return toItem(Decimal::fromValue(o1.as<Numeric>()->toDecimal() + o2.as<Numeric>()->toDecimal()));
     }
     Q_ASSERT(false);
     return Item(); /* GCC unbarfer. */
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qatomicmathematicians_p.h
/src/xmlpatterns/data/qatomicmathematicians.cpp