Qt 4.8: QRegion Class Reference
QRegion Class Reference
The QRegion class specifies a clip region for a painter.
#include <qregion.h>
Classes
struct QRegionData
Public Types
enum RegionType { Rectangle, Ellipse }
Specifies the shape of the region to be created.
Public Functions
QRect boundingRect () const
Returns the bounding rectangle of this region.
bool contains (const QPoint &p) const
Returns true if the region contains the point p; otherwise returns false.
bool contains (const QRect &r) const
Returns true if the region overlaps the rectangle r; otherwise returns false.
QRegion eor (const QRegion &r) const
Use xored(r) instead.
Handle handle () const
Returns a platform-specific region handle.
QRegion intersect (const QRegion &r) const
Use intersected(r) instead.
QRegion intersect (const QRect &r) const
Use intersected(rect) instead.
QRegion intersected (const QRegion &r) const
Returns a region which is the intersection of this region and r.
QRegion intersected (const QRect &r) const
Returns a region which is the intersection of this region and the given rect.
bool intersects (const QRegion &r) const
Returns true if this region intersects with region, otherwise returns false.
bool intersects (const QRect &r) const
Returns true if this region intersects with rect, otherwise returns false.
bool isEmpty () const
Returns true if the region is empty; otherwise returns false.
QT_DEPRECATED int numRects () const
Returns the number of rectangles that will be returned in rects().
const QRegion operator & (const QRegion &r) const
const QRegion operator & (const QRect &r) const
QRegion & operator &= (const QRegion &r)
QRegion & operator &= (const QRect &r)
operator QVariant () const
Returns the region as a QVariant.
bool operator!= (const QRegion &r) const
Returns true if this region is different from the other region; otherwise returns false.
const QRegion operator+ (const QRegion &r) const
Applies the united() function to this region and r.
const QRegion operator+ (const QRect &r) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
QRegion & operator+= (const QRegion &r)
Applies the united() function to this region and r and assigns the result to this region.
QRegion & operator+= (const QRect &r)
Returns a region that is the union of this region with the specified rect.
const QRegion operator- (const QRegion &r) const
Applies the subtracted() function to this region and r.
QRegion & operator-= (const QRegion &r)
Applies the subtracted() function to this region and r and assigns the result to this region.
QRegion & operator= (const QRegion &)
Assigns r to this region and returns a reference to the region.
bool operator== (const QRegion &r) const
Returns true if the region is equal to r; otherwise returns false.
const QRegion operator^ (const QRegion &r) const
Applies the xored() function to this region and r.
QRegion & operator^= (const QRegion &r)
Applies the xored() function to this region and r and assigns the result to this region.
const QRegion operator| (const QRegion &r) const
Applies the united() function to this region and r.
QRegion & operator|= (const QRegion &r)
Applies the united() function to this region and r and assigns the result to this region.
QRegion ()
Constructs an empty region.
QRegion (int x, int y, int w, int h, RegionType t=Rectangle)
Constructs a rectangular or elliptic region.
QRegion (const QRect &r, RegionType t=Rectangle)
Create a region based on the rectange r with region type t.
QRegion (const QPolygon &pa, Qt::FillRule fillRule=Qt::OddEvenFill)
Constructs a polygon region from the point array a with the fill rule specified by fillRule.
QRegion (const QRegion &region)
Constructs a new region which is equal to region r.
QRegion (const QBitmap &bitmap)
Constructs a region from the bitmap bm.
int rectCount () const
Returns the number of rectangles that will be returned in rects().
QVector< QRect > rects () const
Returns an array of non-overlapping rectangles that make up the region.
void setRects (const QRect *rect, int num)
Sets the region using the array of rectangles specified by rects and number.
QRegion subtract (const QRegion &r) const
Use subtracted(r) instead.
QRegion subtracted (const QRegion &r) const
Returns a region which is r subtracted from this region.
void swap (QRegion &other)
Swaps region other with this region.
void translate (int dx, int dy)
Translates (moves) the region dx along the X axis and dy along the Y axis.
void translate (const QPoint &p)
Translates the region {point}.
QRegion translated (int dx, int dy) const
Returns a copy of the region that is translated dx along the x axis and dy along the y axis, relative to the current position.
QRegion translated (const QPoint &p) const
Returns a copy of the regtion that is translated {p}.
QRegion unite (const QRegion &r) const
Use united(r) instead.
QRegion unite (const QRect &r) const
Use united(rect) instead.
QRegion united (const QRegion &r) const
Returns a region which is the union of this region and r.
QRegion united (const QRect &r) const
Returns a region which is the union of this region and the given rect.
QRegion xored (const QRegion &r) const
Returns a region which is the exclusive or (XOR) of this region and r.
~QRegion ()
Destroys the region.
Private Functions
QRegion copy () const
void detach ()
void ensureHandle () const
void exec (const QByteArray &ba, int ver=0, QDataStream::ByteOrder byteOrder=QDataStream::BigEndian)
QRegion winCombine (const QRegion &r, int num) const
Static Private Functions
static void cleanUp (QRegionData *x)
Properties
struct QRegionData * d
Static Private Attributes
static struct QRegionData shared_empty = { Q_BASIC_ATOMIC_INITIALIZER(1), 0 }
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QRegion &)
Writes the region r to the stream s and returns a reference to the stream.
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QRegion &)
Reads a region from the stream s into r and returns a reference to the stream.
class QETWidget
struct QRegionPrivate
bool qt_region_strictContains (const QRegion &region, const QRect &rect)
Returns true if rect is guaranteed to be fully contained in region.
Detailed Description
The QRegion class specifies a clip region for a painter.
QRegion is used with QPainter::setClipRegion() to limit the paint area to what needs to be painted. There is also a QWidget::repaint() function that takes a QRegion parameter. QRegion is the best tool for minimizing the amount of screen area to be updated by a repaint.
This class is not suitable for constructing shapes for rendering, especially as outlines. Use QPainterPath to create paths and shapes for use with QPainter.
QRegion is an implicitly shared class.
Creating and Using Regions
A region can be created from a rectangle, an ellipse, a polygon or a bitmap. Complex regions may be created by combining simple regions using united(), intersected(), subtracted(), or xored() (exclusive or). You can move a region using translate().
You can test whether a region isEmpty() or if it contains() a QPoint or QRect. The bounding rectangle can be found with boundingRect().
The function rects() gives a decomposition of the region into rectangles.
Example of using complex regions:
void MyWidget::paintEvent(QPaintEvent *)
{
    QRegion r1(QRect(100, 100, 200, 80),    // r1: elliptic region
               QRegion::Ellipse);
    QRegion r2(QRect(100, 120, 90, 30));    // r2: rectangular region
    QRegion r3 = r1.intersected(r2);        // r3: intersection
    QPainter painter(this);
    painter.setClipRegion(r3);
    ...                                     // paint clipped graphics
}
Additional License Information
On Embedded Linux, Windows CE and X11 platforms, parts of this class rely on code obtained under the following licenses:
Copyright (c) 1987 X Consortium
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Except as contained in this notice, the name of the X Consortium shall not be used in advertising or otherwise to promote the sale, use or other dealings in this Software without prior written authorization from the X Consortium.
Copyright 1987 by Digital Equipment Corporation, Maynard, Massachusetts.
                    All Rights Reserved
Permission to use, copy, modify, and distribute this software and its documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all copies and that both that copyright notice and this permission notice appear in supporting documentation, and that the name of Digital not be used in advertising or publicity pertaining to distribution of the software without specific, written prior permission.
DIGITAL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL DIGITAL BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
See also
QPainter::setClipRegion(), QPainter::setClipRect(), QPainterPath
Definition at line 68 of file qregion.h.
Enumerations
RegionType
enum QRegion::RegionType
Specifies the shape of the region to be created.
Rectangle the region covers the entire rectangle.
Ellipse the region is an ellipse inside the rectangle.
Enumerator
Rectangle
Ellipse
Definition at line 71 of file qregion.h.
 { Rectangle, Ellipse };
Constructors and Destructors
QRegion() [1/6]
QRegion::QRegion ()
Constructs an empty region.
See also
isEmpty()
Definition at line 3961 of file qregion.cpp.
Referenced by eor(), exec(), intersect(), intersects(), operator|=(), QRegion(), qt_bitmapToRegion(), setRects(), and subtract().
     : d(&shared_empty)
 {
     d->ref.ref();
 }
QRegion() [2/6]
QRegion::QRegion (int x, int y, int w, int h, RegionType t = Rectangle)
Constructs a rectangular or elliptic region.
If t is Rectangle, the region is the filled rectangle (x, y, w, h). If t is Ellipse, the region is the filled ellipse with center at (x + w / 2, y + h / 2) and size (w ,h).
Definition at line 272 of file qregion.cpp.
 {
     QRegion tmp(QRect(x, y, w, h), t);
     tmp.d->ref.ref();
     d = tmp.d;
 }
QRegion() [3/6]
QRegion::QRegion (const QRect & r, RegionType t = Rectangle)
Create a region based on the rectange r with region type t.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the rectangle is invalid a null region will be created.
See also
QRegion::RegionType
Definition at line 3967 of file qregion.cpp.
 {
     if (r.isEmpty()) {
         d = &shared_empty;
         d->ref.ref();
     } else {
         d = new QRegionData;
         d->ref = 1;
 #if defined(Q_WS_X11)
         d->rgn = 0;
         d->xrectangles = 0;
 #elif defined(Q_WS_WIN)
         d->rgn = 0;
 #endif
         if (t == Rectangle) {
             d->qt_rgn = new QRegionPrivate(r);
         } else if (t == Ellipse) {
             QPainterPath path;
             path.addEllipse(r.x(), r.y(), r.width(), r.height());
             QPolygon a = path.toSubpathPolygons().at(0).toPolygon();
             d->qt_rgn = PolygonRegion(a.constData(), a.size(), EvenOddRule);
         }
     }
 }
QRegion() [4/6]
QRegion::QRegion (const QPolygon & a, Qt::FillRule fillRule = Qt::OddEvenFill)
Constructs a polygon region from the point array a with the fill rule specified by fillRule.
If fillRule is Qt::WindingFill, the polygon region is defined using the winding algorithm; if it is Qt::OddEvenFill, the odd-even fill algorithm is used.
Warning
This constructor can be used to create complex regions that will slow down painting when used.
Definition at line 3992 of file qregion.cpp.
 {
     if (a.count() > 2) {
         QRegionPrivate *qt_rgn = PolygonRegion(a.constData(), a.size(),
                                                fillRule == Qt::WindingFill ? WindingRule : EvenOddRule);
         if (qt_rgn) {
             d =  new QRegionData;
             d->ref = 1;
 #if defined(Q_WS_X11)
             d->rgn = 0;
             d->xrectangles = 0;
 #elif defined(Q_WS_WIN)
             d->rgn = 0;
 #endif
             d->qt_rgn = qt_rgn;
         } else {
             d = &shared_empty;
             d->ref.ref();
         }
     } else {
         d = &shared_empty;
         d->ref.ref();
     }
 }
QRegion() [5/6]
QRegion::QRegion (const QRegion & region)
Constructs a new region which is equal to region r.
Definition at line 4017 of file qregion.cpp.
 {
     d = r.d;
     d->ref.ref();
 }
QRegion() [6/6]
QRegion::QRegion (const QBitmap & bm)
Constructs a region from the bitmap bm.
The resulting region consists of the pixels in bitmap bm that are Qt::color1, as if each pixel was a 1 by 1 rectangle.
This constructor may create complex regions that will slow down painting when used. Note that drawing masked pixmaps can be done much faster using QPixmap::setMask().
Definition at line 4024 of file qregion.cpp.
 {
     if (bm.isNull()) {
         d = &shared_empty;
         d->ref.ref();
     } else {
         d = new QRegionData;
         d->ref = 1;
 #if defined(Q_WS_X11)
         d->rgn = 0;
         d->xrectangles = 0;
 #elif defined(Q_WS_WIN)
         d->rgn = 0;
 #endif
         d->qt_rgn = qt_bitmapToRegion(bm);
     }
 }
~QRegion()
QRegion::~QRegion ()
Destroys the region.
Warning
This function is not part of the public interface.
Definition at line 4057 of file qregion.cpp.
Referenced by qt_bitmapToRegion().
 {
     if (!d->ref.deref())
         cleanUp(d);
 }
Functions
boundingRect()
QRect QRegion::boundingRect () const
Returns the bounding rectangle of this region.
An empty region gives a rectangle that is QRect::isNull().
Definition at line 4363 of file qregion.cpp.
Referenced by _q_paintIntoCache(), QWidgetBackingStore::addDirtyWidget(), QOnScreenRasterPaintEngine::begin(), QScreen::blit(), blit_template(), QVGPaintEngine::clip(), QPaintEngineEx::clip(), QRasterPaintEngine::clip(), QPaintBufferEngine::clip(), QPainter::clipBoundingRect(), QPaintBuffer::commandDescription(), QScreen::compose(), QMultiScreen::connect(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QMacStyle::drawComplexControl(), QGraphicsScenePrivate::drawItems(), QTreeView::drawTree(), effectiveState(), QDirectFBScreen::exposeRegion(), QScreen::exposeRegion(), QVGCompositionHelper::fillBackground(), QVGPaintEngine::fillRegion(), fillRegion(), QOpenGLPaintEnginePrivate::fillVertexArray(), QGraphicsViewPrivate::findItems(), QDirectFBScreen::flipSurface(), QVFbWindowSurface::flush(), QXcbWindowSurface::flush(), QCocoaWindowSurface::flush(), QX11GLWindowSurface::flush(), QX11WindowSurface::flush(), QWSWindowSurface::flush(), QGLWindowSurface::flush(), QRasterWindowSurface::flush(), QWSYellowSurface::flush(), intersects(), QVGPaintEngine::isDefaultClipRegion(), isFullUpdate(), isServerProcess(), make_widget_eventUPP(), QTransform::map(), QTransformedScreen::mapFromDevice(), QWidgetBackingStore::markDirty(), QWidgetPrivate::moveRect(), operator<<(), QDecorationStyled::paint(), QDecorationWindows::paint(), QDecorationDefault::paint(), QDeclarativePaintedItem::paint(), QScreen::paintBackground(), QWSMemorySurface::painterOffset(), QSystemTrayIconSys::paintEvent(), QWidgetPrivate::paintSiblingsRecursive(), QBBWindow::post(), QPainterReplayer::process(), QPaintEngineExReplayer::process(), qt_bitmapToRegion(), qt_mac_fill_background(), qt_mac_unregister_widget(), qt_regionToPath(), QWidgetPrivate::render(), QWidgetPrivate::render_helper(), QFbWindow::repaint(), QWSServerPrivate::request_region(), QDirectFbWindowSurface::scroll(), QMacWindowSurface::scroll(), QX11WindowSurface::scroll(), QDirectFBWindowSurface::scroll(), QGLWindowSurface::scroll(), QRasterWindowSurface::scroll(), QVGEGLWindowSurfaceDirect::scroll(), QWidgetPrivate::scrollRect(), QPainter::setClipRegion(), QClipData::setClipRegion(), PvrEglWindowSurface::setDirectRegion(), QVFbScreen::setDirty(), QMultiScreen::setDirty(), QDirectFBWindowSurface::setGeometry(), QX11WindowSurface::setGeometry(), QWSLocalMemSurface::setGeometry(), QMacStyle::sizeFromContents(), QTransformedScreen::solidFill(), QDirectFBScreen::solidFill(), QWidgetPrivate::subtractOpaqueSiblings(), QWidgetBackingStore::sync(), QGL2PaintEngineExPrivate::systemStateChanged(), QRasterPaintEnginePrivate::systemStateChanged(), QPaintEnginePrivate::transformSystemClip(), QETWidget::translateEmbedEvent(), QWidget::update(), QPicturePaintEngine::updateClipRegion(), QGL2PaintEngineExPrivate::updateClipScissorTest(), QETWidget::updateRegion(), QDesktopWidgetPrivate::updateScreenList(), QVGEGLWindowSurfacePrivate::windowSurfaceSize(), and QPicturePaintEngine::writeCmdLength().
 {
     if (isEmpty())
         return QRect();
     return d->qt_rgn->extents;
 }
cleanUp()
void QRegion::cleanUp (QRegion::QRegionData * x) static private
Definition at line 4042 of file qregion.cpp.
Referenced by copy(), operator=(), qt_bitmapToRegion(), and ~QRegion().
 {
     delete x->qt_rgn;
 #if defined(Q_WS_X11)
     if (x->rgn)
         XDestroyRegion(x->rgn);
     if (x->xrectangles)
         free(x->xrectangles);
 #elif defined(Q_WS_WIN)
     if (x->rgn)
         qt_win_dispose_rgn(x->rgn);
 #endif
     delete x;
 }
contains() [1/2]
bool QRegion::contains (const QPoint & p) const
Returns true if the region contains the point p; otherwise returns false.
Definition at line 4104 of file qregion.cpp.
Referenced by QRegionPrivate::contains(), QWSServerPrivate::invokeSelectCursor(), QMultiScreenCursor::move(), QDeclarativePaintedItem::paint(), QDockAreaLayoutInfo::paintSeparators(), QDockAreaLayout::paintSeparators(), parseGeometry(), QWidgetPrivate::pointInsideRectAndMask(), qt_bitmapToRegion(), QDecoration::regionAt(), setMaxWindowRect(), QScreen::subScreenIndexAt(), QApplication::topLevelAt(), and QWSServer::windowAt().
 {
     return PointInRegion(d->qt_rgn, p.x(), p.y());
 }
contains() [2/2]
bool QRegion::contains (const QRect & r) const
Returns true if the region overlaps the rectangle r; otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 4109 of file qregion.cpp.
 {
     return RectInRegion(d->qt_rgn, r.left(), r.top(), r.width(), r.height()) != RectangleOut;
 }
copy()
QRegion QRegion::copy () const private
Warning
This function is not part of the public interface.
Definition at line 4077 of file qregion.cpp.
Referenced by detach(), exec(), qt_bitmapToRegion(), and QVector< QPoint >::replace().
 {
     QRegion r;
     QScopedPointer<QRegionData> x(new QRegionData);
     x->ref = 1;
 #if defined(Q_WS_X11)
     x->rgn = 0;
     x->xrectangles = 0;
 #elif defined(Q_WS_WIN)
     x->rgn = 0;
 #endif
     if (d->qt_rgn)
         x->qt_rgn = new QRegionPrivate(*d->qt_rgn);
     else
         x->qt_rgn = new QRegionPrivate;
     if (!r.d->ref.deref())
         cleanUp(r.d);
     r.d = x.take();
     return r;
 }
detach()
void QRegion::detach () private
Definition at line 300 of file qregion.cpp.
Referenced by eor(), intersect(), operator+=(), qt_bitmapToRegion(), setRects(), subtract(), translate(), and unite().
 {
     if (d->ref != 1)
         *this = copy();
 #if defined(Q_WS_X11)
     else if (d->xrectangles) {
         free(d->xrectangles);
         d->xrectangles = 0;
     }
 #endif
 }
ensureHandle()
void QRegion::ensureHandle () const private
Definition at line 130 of file qregion_win.cpp.
 {
     if (d->rgn)
         DeleteObject(d->rgn);
     d->rgn = CreateRectRgn(0,0,0,0);
     if (d->qt_rgn) {
         if (d->qt_rgn->numRects == 1) {
             QRect r = d->qt_rgn->extents;
             qt_add_rect(d->rgn, r);
             return;
         }
         for (int i = 0;i < d->qt_rgn->numRects;i++) {
             QRect r = d->qt_rgn->rects.at(i);
             qt_add_rect(d->rgn, r);
         }
     }
 }
eor()
QRegion QRegion::eor (const QRegion & r) const
Use xored(r) instead.
Definition at line 4345 of file qregion.cpp.
Referenced by qt_bitmapToRegion().
 {
     if (isEmptyHelper(d->qt_rgn)) {
         return r;
     } else if (isEmptyHelper(r.d->qt_rgn)) {
         return *this;
     } else if (!EXTENTCHECK(&d->qt_rgn->extents, &r.d->qt_rgn->extents)) {
         return (*this + r);
     } else if (d == r.d || EqualRegion(d->qt_rgn, r.d->qt_rgn)) {
         return QRegion();
     } else {
         QRegion result;
         result.detach();
         XorRegion(d->qt_rgn, r.d->qt_rgn, *result.d->qt_rgn);
         return result;
     }
 }
exec()
void QRegion::exec (const QByteArray & ba, int ver = 0, QDataStream::ByteOrder byteOrder = QDataStream::BigEndian) private
Definition at line 336 of file qregion.cpp.
Referenced by exec().
 {
     QByteArray copy = buffer;
     QDataStream s(&copy, QIODevice::ReadOnly);
     if (ver)
         s.setVersion(ver);
     s.setByteOrder(byteOrder);
     QRegion rgn;
 #ifndef QT_NO_DEBUG
     int test_cnt = 0;
 #endif
     while (!s.atEnd()) {
         qint32 id;
         if (s.version() == 1) {
             int id_int;
             s >> id_int;
             id = id_int;
         } else {
             s >> id;
         }
 #ifndef QT_NO_DEBUG
         if (test_cnt > 0 && id != QRGN_TRANSLATE)
             qWarning("QRegion::exec: Internal error");
         test_cnt++;
 #endif
         if (id == QRGN_SETRECT || id == QRGN_SETELLIPSE) {
             QRect r;
             s >> r;
             rgn = QRegion(r, id == QRGN_SETRECT ? Rectangle : Ellipse);
         } else if (id == QRGN_SETPTARRAY_ALT || id == QRGN_SETPTARRAY_WIND) {
             QPolygon a;
             s >> a;
             rgn = QRegion(a, id == QRGN_SETPTARRAY_WIND ? Qt::WindingFill : Qt::OddEvenFill);
         } else if (id == QRGN_TRANSLATE) {
             QPoint p;
             s >> p;
             rgn.translate(p.x(), p.y());
         } else if (id >= QRGN_OR && id <= QRGN_XOR) {
             QByteArray bop1, bop2;
             QRegion r1, r2;
             s >> bop1;
             r1.exec(bop1);
             s >> bop2;
             r2.exec(bop2);
             switch (id) {
                 case QRGN_OR:
                     rgn = r1.united(r2);
                     break;
                 case QRGN_AND:
                     rgn = r1.intersected(r2);
                     break;
                 case QRGN_SUB:
                     rgn = r1.subtracted(r2);
                     break;
                 case QRGN_XOR:
                     rgn = r1.xored(r2);
                     break;
             }
         } else if (id == QRGN_RECTS) {
             // (This is the only form used in Qt 2.0)
             quint32 n;
             s >> n;
             QRect r;
             for (int i=0; i<(int)n; i++) {
                 s >> r;
                 rgn = rgn.united(QRegion(r));
             }
         }
     }
     *this = rgn;
 }
handle()
Handle QRegion::handle () const
Returns a platform-specific region handle.
The Handle type is HRGN on Windows, Region on X11, and RgnHandle on Mac OS X. On Qt for Embedded Linux it is {void *}.
Warning
This function is not portable.
Referenced by do_size_hints(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), qt_grab_cursor(), QETWidget::translatePaintEvent(), QWin32PrintEngine::updateClipPath(), QAxServerBase::updateMask(), and QGLContext::updatePaintDevice().
intersect() [1/2]
QRegion QRegion::intersect (const QRegion & r) const
Use intersected(r) instead.
Definition at line 4249 of file qregion.cpp.
Referenced by QVGPaintEngine::clip(), clipTransformIsSimple(), intersects(), QRegionPrivate::operator=(), qt_bitmapToRegion(), PvrEglWindowSurface::setDirectRegion(), and QVGPaintEngine::updateScissor().
 {
     if (isEmptyHelper(d->qt_rgn) || isEmptyHelper(r.d->qt_rgn)
         || !EXTENTCHECK(&d->qt_rgn->extents, &r.d->qt_rgn->extents))
         return QRegion();
     /* this is fully contained in r */
     if (r.d->qt_rgn->contains(*d->qt_rgn))
         return *this;
     /* r is fully contained in this */
     if (d->qt_rgn->contains(*r.d->qt_rgn))
         return r;
     if (r.d->qt_rgn->numRects == 1 && d->qt_rgn->numRects == 1) {
         const QRect rect = qt_rect_intersect_normalized(r.d->qt_rgn->extents,
                                                         d->qt_rgn->extents);
         return QRegion(rect);
     } else if (r.d->qt_rgn->numRects == 1) {
         QRegion result(*this);
         result.detach();
         result.d->qt_rgn->intersect(r.d->qt_rgn->extents);
         return result;
     } else if (d->qt_rgn->numRects == 1) {
         QRegion result(r);
         result.detach();
         result.d->qt_rgn->intersect(d->qt_rgn->extents);
         return result;
     }
     QRegion result;
     result.detach();
     miRegionOp(*result.d->qt_rgn, d->qt_rgn, r.d->qt_rgn, miIntersectO, 0, 0);
     /*
      * Can't alter dest's extents before we call miRegionOp because
      * it might be one of the source regions and miRegionOp depends
      * on the extents of those regions being the same. Besides, this
      * way there's no checking against rectangles that will be nuked
      * due to coalescing, so we have to examine fewer rectangles.
      */
     miSetExtents(*result.d->qt_rgn);
     return result;
 }
intersect() [2/2]
QRegion QRegion::intersect (const QRect & rect) const
Use intersected(rect) instead.
Since
4.4
Definition at line 4294 of file qregion.cpp.
 {
     if (isEmptyHelper(d->qt_rgn) || r.isEmpty()
         || !EXTENTCHECK(&d->qt_rgn->extents, &r))
         return QRegion();
     /* this is fully contained in r */
     if (d->qt_rgn->within(r))
         return *this;
     /* r is fully contained in this */
     if (d->qt_rgn->contains(r))
         return r;
     if (d->qt_rgn->numRects == 1) {
         const QRect rect = qt_rect_intersect_normalized(d->qt_rgn->extents,
                                                         r.normalized());
         return QRegion(rect);
     }
     QRegion result(*this);
     result.detach();
     result.d->qt_rgn->intersect(r);
     return result;
 }
intersected() [1/2]
QRegion QRegion::intersected (const QRegion & r) const inline
Returns a region which is the intersection of this region and r.
Since
4.2
Region Intersection
The figure shows the intersection of two elliptical regions.
See also
subtracted(), united(), xored()
Definition at line 112 of file qregion.h.
Referenced by QFbScreen::doRedraw(), exec(), QBlitterPaintEngine::fillRect(), QGL2PaintEngineExPrivate::fillStencilWithVertexArray(), QBBRasterWindowSurface::flush(), QAlphaPaintEnginePrivate::fullyContained(), operator+(), QWidgetPrivate::scrollRect(), and QX11PaintEngine::updateClipRegion_dev().
 { return intersect(r); }
intersected() [2/2]
QRegion QRegion::intersected (const QRect & rect) const inline
Returns a region which is the intersection of this region and the given rect.
Since
4.4
See also
subtracted(), united(), xored()
Definition at line 113 of file qregion.h.
 { return intersect(r); }
intersects() [1/2]
bool QRegion::intersects (const QRegion & region) const
Returns true if this region intersects with region, otherwise returns false.
Since
4.2
Definition at line 766 of file qregion.cpp.
Referenced by QWidgetBackingStore::bltRect(), QFbScreen::doRedraw(), QTableViewPrivate::drawAndClipSpans(), QGraphicsScenePrivate::drawSubtreeRecursive(), QDirectFBScreen::exposeRegion(), QScreen::exposeRegion(), QGL2PaintEngineExPrivate::fillStencilWithVertexArray(), QXcbShmImage::preparePaint(), QBBRasterWindowSurface::scroll(), and QWidgetBackingStore::sync().
 {
     if (isEmpty() || region.isEmpty())
         return false;
     if (!rect_intersects(boundingRect(), region.boundingRect()))
         return false;
     if (rectCount() == 1 && region.rectCount() == 1)
         return true;
     const QVector<QRect> myRects = rects();
     const QVector<QRect> otherRects = region.rects();
     for (QVector<QRect>::const_iterator i1 = myRects.constBegin(); i1 < myRects.constEnd(); ++i1)
         for (QVector<QRect>::const_iterator i2 = otherRects.constBegin(); i2 < otherRects.constEnd(); ++i2)
             if (rect_intersects(*i1, *i2))
                 return true;
     return false;
 }
intersects() [2/2]
bool QRegion::intersects (const QRect & rect) const
Returns true if this region intersects with rect, otherwise returns false.
Since
4.2
Definition at line 4480 of file qregion.cpp.
 {
     if (isEmptyHelper(d->qt_rgn) || rect.isNull())
         return false;
     const QRect r = rect.normalized();
     if (!rect_intersects(d->qt_rgn->extents, r))
         return false;
     if (d->qt_rgn->numRects == 1)
         return true;
     const QVector<QRect> myRects = rects();
     for (QVector<QRect>::const_iterator it = myRects.constBegin(); it < myRects.constEnd(); ++it)
         if (rect_intersects(r, *it))
             return true;
     return false;
 }
isEmpty()
bool QRegion::isEmpty () const
Returns true if the region is empty; otherwise returns false.
An empty region is a region that contains no points.
Example:
QRegion r1(10, 10, 20, 20);
r1.isEmpty();               // false
QRegion r3;
r3.isEmpty();               // true
QRegion r2(40, 40, 20, 20);
r3 = r1.intersected(r2);    // r3: intersection of r1 and r2
r3.isEmpty();               // true
r3 = r1.united(r2);         // r3: union of r1 and r2
r3.isEmpty();               // false
Definition at line 4098 of file qregion.cpp.
Referenced by _q_paintIntoCache(), QGL2PaintEngineEx::begin(), QWidgetBackingStore::beginPaint(), QMultiScreen::blit(), QScreen::blit(), boundingRect(), QVGPaintEngine::clip(), QGL2PaintEngineEx::clip(), QScreen::compose(), QBBWindow::copyBack(), do_size_hints(), QFbScreen::doRedraw(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QGraphicsScenePrivate::drawItemHelper(), QWidgetPrivate::drawWidget(), effectiveState(), QMultiScreen::exposeRegion(), QDirectFBScreen::exposeRegion(), QScreen::exposeRegion(), QWSServerPrivate::exposeRegion(), QWSWindowSurface::flush(), QWidgetBackingStore::flush(), QGLWindowSurface::flush(), QWidgetPrivate::getOpaqueChildren(), QWSTtyKbPrivate::handleConsoleSwitch(), QWindowSurface::hasStaticContents(), intersects(), QWidgetPrivate::invalidateBuffer(), QWidgetPrivate::invalidateBuffer_resizeHelper(), QWSWindow::isFullyObscured(), isServerProcess(), QWSServerPrivate::lowerWindow(), make_widget_eventUPP(), QTransformedScreen::mapFromDevice(), QWidgetBackingStore::markDirty(), QWidgetBackingStore::markDirtyOnScreen(), QMdiSubWindow::mouseMoveEvent(), QWidgetPrivate::moveRect(), QWSServerPrivate::moveWindowRegion(), operator==(), QDecorationStyled::paint(), QDeclarativePaintedItem::paint(), QScreen::paintBackground(), QWSMemorySurface::painterOffset(), QGraphicsWidget::paintWindowFrame(), parseGeometry(), QBBWindow::post(), QMacCGContext::QMacCGContext(), qt_bitmapToRegion(), qt_flush(), qt_grab_cursor(), qt_mac_clip_cg(), qt_mac_post_retranslateAppMenu(), qt_mac_unregister_widget(), qt_region_strictContains(), qt_tablet_cleanup_wce(), QWSServerPrivate::raiseWindow(), QWidgetBackingStore::removeDirtyWidget(), QWidget::render(), QWidgetPrivate::render(), QWidgetPrivate::render_helper(), QWidget::repaint(), QETWidget::repaintDecoration(), QWSServerPrivate::request_region(), QDirectFbWindowSurface::scroll(), QWidgetPrivate::scrollRect(), QCoreGraphicsPaintEnginePrivate::setClip(), QRasterPaintEngine::setClipRectInDeviceCoords(), QWSWindowSurface::setClipRegion(), QMenuPrivate::setCurrentAction(), PvrEglWindowSurface::setDirectRegion(), QMultiScreen::setDirty(), QWidget::setDisabled(), QWSWindowSurface::setGeometry(), QWSLocalMemSurface::setGeometry(), QWidget::setMask(), QWidgetPrivate::setMask_sys(), QPaintEnginePrivate::setSystemViewport(), QMultiScreen::solidFill(), QDirectFBScreen::solidFill(), QWidgetBackingStore::staticContents(), QWidgetPrivate::subtractOpaqueChildren(), QWidgetPrivate::subtractOpaqueSiblings(), QWidgetBackingStore::sync(), QGL2PaintEngineExPrivate::systemStateChanged(), QApplication::topLevelAt(), QPaintEnginePrivate::transformSystemClip(), QETWidget::translateEmbedEvent(), QETWidget::translatePaintEvent(), QWidgetBackingStore::unflushPaint(), QWidget::update(), QX11PaintEngine::updateBrush(), QOpenGLPaintEngine::updateClipRegion(), QX11PaintEngine::updateClipRegion_dev(), QMdiSubWindowPrivate::updateMask(), QWorkspaceChild::updateMask(), QGLContext::updatePaintDevice(), QX11PaintEngine::updatePen(), updateRedirectedToGraphicsProxyWidget(), QVGPaintEngine::updateScissor(), QApplication::widgetAt(), and QVGEGLWindowSurfacePrivate::windowSurfaceSize().
 {
     return d == &shared_empty || d->qt_rgn->numRects == 0;
 }
numRects()
int QRegion::numRects () const
Returns the number of rectangles that will be returned in rects().
Since
4.4
Definition at line 4456 of file qregion.cpp.
Referenced by QRegionPrivate::append(), QRegionPrivate::canAppend(), QRegionPrivate::canPrepend(), clipTransformIsSimple(), QFbScreen::doRedraw(), QRegionPrivate::intersect(), QDeclarativePaintedItem::paint(), and QRegionPrivate::prepend().
 {
     return (d->qt_rgn ? d->qt_rgn->numRects : 0);
 }
operator &() [1/2]
const QRegion QRegion::operator& (const QRegion & r) const
Referenced by operator+(), and qt_bitmapToRegion().
operator &() [2/2]
const QRegion QRegion::operator& (const QRect & r) const
operator &=() [1/2]
QRegion& QRegion::operator&= (const QRegion & r)
Referenced by operator|=(), and qt_bitmapToRegion().
operator &=() [2/2]
QRegion& QRegion::operator&= (const QRect & r)
operator QVariant()
QRegion::operator QVariant () const
Returns the region as a QVariant.
Definition at line 677 of file qregion.cpp.
 {
     return QVariant(QVariant::Region, this);
 }
operator!=()
bool QRegion::operator!= (const QRegion & r) const inline
Returns true if this region is different from the other region; otherwise returns false.
Definition at line 144 of file qregion.h.
 { return !(operator==(r)); }
operator+() [1/2]
const QRegion QRegion::operator+ (const QRegion & r) const
Applies the united() function to this region and r.
r1+r2 is equivalent to r1.united(r2).
See also
united(), operator|()
Definition at line 523 of file qregion.cpp.
     { return united(r); }
operator+() [2/2]
const QRegion QRegion::operator+ (const QRect & r) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.4
Definition at line 530 of file qregion.cpp.
     { return united(r); }
operator+=() [1/2]
QRegion & QRegion::operator+= (const QRegion & r)
Applies the united() function to this region and r and assigns the result to this region.
r1+=r2 is equivalent to {r1 = r1.united(r2)}.
See also
intersected()
Definition at line 4158 of file qregion.cpp.
Referenced by operator|=(), and qt_bitmapToRegion().
 {
     if (isEmptyHelper(d->qt_rgn))
         return *this = r;
     if (isEmptyHelper(r.d->qt_rgn))
         return *this;
     if (d == r.d)
         return *this;
     if (d->qt_rgn->contains(*r.d->qt_rgn)) {
         return *this;
     } else if (r.d->qt_rgn->contains(*d->qt_rgn)) {
         return *this = r;
     } else if (d->qt_rgn->canAppend(r.d->qt_rgn)) {
         detach();
         d->qt_rgn->append(r.d->qt_rgn);
         return *this;
     } else if (d->qt_rgn->canPrepend(r.d->qt_rgn)) {
         detach();
         d->qt_rgn->prepend(r.d->qt_rgn);
         return *this;
     } else if (EqualRegion(d->qt_rgn, r.d->qt_rgn)) {
         return *this;
     } else {
         detach();
         UnionRegion(d->qt_rgn, r.d->qt_rgn, *d->qt_rgn);
         return *this;
     }
 }
operator+=() [2/2]
QRegion & QRegion::operator+= (const QRect & rect)
Returns a region that is the union of this region with the specified rect.
See also
united()
Definition at line 4220 of file qregion.cpp.
 {
     if (isEmptyHelper(d->qt_rgn))
         return *this = r;
     if (r.isEmpty())
         return *this;
     if (d->qt_rgn->contains(r)) {
         return *this;
     } else if (d->qt_rgn->within(r)) {
         return *this = r;
     } else if (d->qt_rgn->canAppend(&r)) {
         detach();
         d->qt_rgn->append(&r);
         return *this;
     } else if (d->qt_rgn->canPrepend(&r)) {
         detach();
         d->qt_rgn->prepend(&r);
         return *this;
     } else if (d->qt_rgn->numRects == 1 && d->qt_rgn->extents == r) {
         return *this;
     } else {
         detach();
         QRegionPrivate p(r);
         UnionRegion(d->qt_rgn, &p, *d->qt_rgn);
         return *this;
     }
 }
operator-()
const QRegion QRegion::operator- (const QRegion & r) const
Applies the subtracted() function to this region and r.
r1-r2 is equivalent to r1.subtracted(r2).
See also
subtracted()
Definition at line 557 of file qregion.cpp.
     { return subtracted(r); }
operator-=()
QRegion & QRegion::operator-= (const QRegion & r)
Applies the subtracted() function to this region and r and assigns the result to this region.
r1-=r2 is equivalent to {r1 = r1.subtracted(r2)}.
See also
subtracted()
Definition at line 651 of file qregion.cpp.
     { return *this = *this - r; }
operator=()
QRegion & QRegion::operator= (const QRegion & r)
Assigns r to this region and returns a reference to the region.
Definition at line 4064 of file qregion.cpp.
Referenced by qt_bitmapToRegion().
 {
     r.d->ref.ref();
     if (!d->ref.deref())
         cleanUp(d);
     d = r.d;
     return *this;
 }
operator==()
bool QRegion::operator== (const QRegion & r) const
Returns true if the region is equal to r; otherwise returns false.
Definition at line 4467 of file qregion.cpp.
Referenced by qt_region_strictContains().
 {
     if (!d->qt_rgn)
         return r.isEmpty();
     if (!r.d->qt_rgn)
         return isEmpty();
     if (d == r.d)
         return true;
     else
         return EqualRegion(d->qt_rgn, r.d->qt_rgn);
 }
operator^()
const QRegion QRegion::operator^ (const QRegion & r) const
Applies the xored() function to this region and r.
r1^r2 is equivalent to r1.xored(r2).
See also
xored()
Definition at line 566 of file qregion.cpp.
     { return xored(r); }
operator^=()
QRegion & QRegion::operator^= (const QRegion & r)
Applies the xored() function to this region and r and assigns the result to this region.
r1^=r2 is equivalent to {r1 = r1.xored(r2)}.
See also
xored()
Definition at line 661 of file qregion.cpp.
     { return *this = *this ^ r; }
operator|()
const QRegion QRegion::operator| (const QRegion & r) const
Applies the united() function to this region and r.
r1|r2 is equivalent to r1.united(r2).
See also
united(), operator+()
Definition at line 514 of file qregion.cpp.
     { return united(r); }
operator|=()
QRegion & QRegion::operator|= (const QRegion & r)
Applies the united() function to this region and r and assigns the result to this region.
r1|=r2 is equivalent to {r1 = r1.united(r2)}.
See also
united()
Definition at line 576 of file qregion.cpp.
     { return *this = *this | r; }
rectCount()
int QRegion::rectCount () const
Returns the number of rectangles that will be returned in rects().
Since
4.6
Definition at line 4461 of file qregion.cpp.
Referenced by _q_paintIntoCache(), blit_template(), QVGPaintEngine::clip(), QPaintEngineEx::clip(), QRasterPaintEngine::clip(), QDirectFBScreen::exposeRegion(), QScreen::exposeRegion(), QVGCompositionHelper::fillBackground(), QVGPaintEngine::fillRegion(), QGraphicsViewPrivate::findItems(), QDirectFBScreen::flipSurface(), QRasterWindowSurface::flush(), intersects(), QVGPaintEngine::isDefaultClipRegion(), isFullUpdate(), QTransform::map(), qt_regionToPath(), QDirectFbWindowSurface::scroll(), QDirectFBWindowSurface::scroll(), QClipData::setClipRegion(), PvrEglWindowSurface::setDirectRegion(), QDirectFBScreen::solidFill(), and QGL2PaintEngineExPrivate::systemStateChanged().
 {
     return (d->qt_rgn ? d->qt_rgn->numRects : 0);
 }
rects()
QVector< QRect > QRegion::rects () const
Returns an array of non-overlapping rectangles that make up the region.
The union of all the rectangles is equal to the original region.
Definition at line 4412 of file qregion.cpp.
Referenced by QPainterPath::addRegion(), QRegionPrivate::append(), QXcbWindowSurface::beginPaint(), QXlibWindowSurface::beginPaint(), QX11WindowSurface::beginPaint(), QRasterWindowSurface::beginPaint(), QWSMemorySurface::beginPaint(), QTransformedScreen::blit(), blit_template(), QGraphicsItem::boundingRegion(), QRegionPrivate::canAppend(), QRegionPrivate::canPrepend(), QPaintEngineEx::clip(), QScreen::compose(), QBBWindow::copyBack(), QLinuxFbScreen::doRedraw(), QVNCScreen::doRedraw(), QFbScreen::doRedraw(), QWindowsXPStylePrivate::drawBackgroundThruNativeBuffer(), QGraphicsScenePrivate::drawItemHelper(), QBlitterPaintEngine::drawPixmap(), QTreeView::drawTree(), QQnxScreen::exposeRegion(), QProxyScreen::exposeRegion(), QDirectFBScreen::exposeRegion(), QScreen::exposeRegion(), QVGCompositionHelper::fillBackground(), QBlitterPaintEngine::fillRect(), QBlitterPaintEnginePrivate::fillRect(), QVGPaintEngine::fillRegion(), fillRegion(), QGL2PaintEngineExPrivate::fillStencilWithVertexArray(), QGraphicsViewPrivate::findItems(), QDirectFBScreen::flipSurface(), QDirectFbWindowSurface::flush(), QXcbWindowSurface::flush(), QWaylandShmWindowSurface::flush(), QMacWindowSurface::flush(), QGLWindowSurface::flush(), QRasterWindowSurface::flush(), QFbScreen::generateRects(), QClipData::initialize(), QGraphicsItemPrivate::initStyleOption(), QRegionPrivate::intersect(), intersects(), make_widget_eventUPP(), QTransformedScreen::mapFromDevice(), QVGPaintEnginePrivate::modifyMask(), QVNCCursor::move(), operator<<(), QDeclarativePaintedItem::paint(), QScreen::paintBackground(), QBlittablePixmapData::paintEngine(), QTableView::paintEvent(), QMdiArea::paintEvent(), QRasterWindowSurface::prepareBuffer(), QRegionPrivate::prepend(), qt_mac_clip_cg(), qt_mac_fill_background(), qt_mac_post_retranslateAppMenu(), qt_region_strictContains(), qt_regionToPath(), QVNCDirtyMap::QVNCDirtyMap(), QmlJSDebugger::regionToPolygon(), QWSDisplay::repaintRegion(), QDirectFbWindowSurface::scroll(), QXcbWindowSurface::scroll(), QXlibWindowSurface::scroll(), QX11GLWindowSurface::scroll(), QRasterWindowSurface::scroll(), QWSMemorySurface::scroll(), QGraphicsItem::scroll(), QVNCCursor::set(), QPainter::setClipRegion(), QClipData::setClipRegion(), QWSRegionEvent::setData(), QWSRegionCommand::setData(), PvrEglWindowSurface::setDirectRegion(), setRects(), QVGCompositionHelper::setScissor(), QWidgetPrivate::setWindowOpacity_sys(), showYellowThing_win(), QDirectFBScreen::solidFill(), solidFill_template(), QEglContext::swapBuffersRegion2NOK(), QWidgetBackingStore::sync(), QOpenGLPaintEngine::updateClipRegion(), QGLContext::updatePaintDevice(), updateRedirectedToGraphicsProxyWidget(), QVGPaintEngine::updateScissor(), QPdfBaseEngine::updateState(), and QRfbRawEncoder::write().
 {
     if (d->qt_rgn) {
         d->qt_rgn->vectorize();
         // hw: modify the vector size directly to avoid reallocation
         d->qt_rgn->rects.d->size = d->qt_rgn->numRects;
         return d->qt_rgn->rects;
     } else {
         return QVector<QRect>();
     }
 }
setRects()
void QRegion::setRects (const QRect * rects, int number)
Sets the region using the array of rectangles specified by rects and number.
The rectangles must be optimally Y-X sorted and follow these restrictions:
The rectangles must not intersect.
All rectangles with a given top coordinate must have the same height.
No two rectangles may abut horizontally (they should be combined into a single wider rectangle in that case).
The rectangles must be sorted in ascending order, with Y as the major sort key and X as the minor sort key.
Warning
This function is not part of the public interface. Only some platforms have these restrictions (Qt for Embedded Linux, X11 and Mac OS X).
Definition at line 4424 of file qregion.cpp.
Referenced by QWSServerPrivate::invokeRepaintRegion(), qt_region_strictContains(), QApplication::qwsProcessEvent(), and QETWidget::translateRegionEvent().
 {
     *this = QRegion();
     if (!rects || num == 0 || (num == 1 && rects->isEmpty()))
         return;
     detach();
     d->qt_rgn->numRects = num;
     if (num == 1) {
         d->qt_rgn->extents = *rects;
         d->qt_rgn->innerRect = *rects;
     } else {
         d->qt_rgn->rects.resize(num);
         int left = INT_MAX,
             right = INT_MIN,
             top = INT_MAX,
             bottom = INT_MIN;
         for (int i = 0; i < num; ++i) {
             const QRect &rect = rects[i];
             d->qt_rgn->rects[i] = rect;
             left = qMin(rect.left(), left);
             right = qMax(rect.right(), right);
             top = qMin(rect.top(), top);
             bottom = qMax(rect.bottom(), bottom);
             d->qt_rgn->updateInnerRect(rect);
         }
         d->qt_rgn->extents = QRect(QPoint(left, top), QPoint(right, bottom));
     }
 }
subtract()
QRegion QRegion::subtract (const QRegion & r) const
Use subtracted(r) instead.
Definition at line 4320 of file qregion.cpp.
Referenced by qt_bitmapToRegion().
 {
     if (isEmptyHelper(d->qt_rgn) || isEmptyHelper(r.d->qt_rgn))
         return *this;
     if (r.d->qt_rgn->contains(*d->qt_rgn))
         return QRegion();
     if (!EXTENTCHECK(&d->qt_rgn->extents, &r.d->qt_rgn->extents))
         return *this;
     if (d == r.d || EqualRegion(d->qt_rgn, r.d->qt_rgn))
         return QRegion();
 #ifdef QT_REGION_DEBUG
     d->qt_rgn->selfTest();
     r.d->qt_rgn->selfTest();
 #endif
     QRegion result;
     result.detach();
     SubtractRegion(d->qt_rgn, r.d->qt_rgn, *result.d->qt_rgn);
 #ifdef QT_REGION_DEBUG
     result.d->qt_rgn->selfTest();
 #endif
     return result;
 }
subtracted()
QRegion QRegion::subtracted (const QRegion & r) const inline
Returns a region which is r subtracted from this region.
Since
4.2
Region Subtraction
The figure shows the result when the ellipse on the right is subtracted from the ellipse on the left ({left - right}).
See also
intersected(), united(), xored()
Definition at line 114 of file qregion.h.
Referenced by QPlastiqueStyle::drawControl(), QGtkStyle::drawControl(), exec(), operator-(), and QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem().
 { return subtract(r); }
swap()
void QRegion::swap (QRegion & other) inline
Swaps region other with this region.
Since
4.8
This operation is very fast and never fails.
Definition at line 88 of file qregion.h.
 { qSwap(d, other.d); }
translate() [1/2]
void QRegion::translate (int dx, int dy)
Translates (moves) the region dx along the X axis and dy along the Y axis.
Definition at line 4116 of file qregion.cpp.
Referenced by QOnScreenRasterPaintEngine::begin(), QWidgetBackingStore::beginPaint(), effectiveState(), exec(), QX11WindowSurface::flush(), QWSWindowSurface::flush(), QWSYellowSurface::flush(), QWidgetPrivate::getOpaqueChildren(), isServerProcess(), make_widget_eventUPP(), QMatrix::map(), QTransform::map(), QWidgetPrivate::moveRect(), QWSServerPrivate::moveWindowRegion(), QWidgetPrivate::paintSiblingsRecursive(), QMacCGContext::QMacCGContext(), qt_bitmapToRegion(), qt_mac_unregister_widget(), QGraphicsItem::scroll(), QWidgetPrivate::scrollRect(), QWSWindowSurface::setClipRegion(), QWidget::setMask(), QWidgetBackingStore::showYellowThing(), QWidgetBackingStore::staticContents(), QWidgetPrivate::subtractOpaqueSiblings(), QWidgetBackingStore::sync(), QPaintEnginePrivate::transformSystemClip(), translated(), QETWidget::translateRegionEvent(), and QETWidget::updateRegion().
 {
     if ((dx == 0 && dy == 0) || isEmptyHelper(d->qt_rgn))
         return;
     detach();
     OffsetRegion(*d->qt_rgn, dx, dy);
 }
translate() [2/2]
void QRegion::translate (const QPoint & point) inline
Translates the region {point}.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
x() along the x axis and {point}.y() along the y axis, relative to the current position. Positive values move the region to the right and down.
Translates to the given point.
Definition at line 98 of file qregion.h.
Referenced by translate().
 { translate(p.x(), p.y()); }
translated() [1/2]
QRegion QRegion::translated (int dx, int dy) const
Returns a copy of the region that is translated dx along the x axis and dy along the y axis, relative to the current position.
Since
4.1
Positive values move the region to the right and down.
See also
translate()
Definition at line 743 of file qregion.cpp.
Referenced by QWidgetBackingStore::beginPaint(), QWidgetPrivate::clipToEffectiveMask(), QWidgetBackingStore::dirtyRegion(), QWindowsXPStylePrivate::drawBackgroundDirectly(), QWidgetPrivate::drawWidget(), effectiveState(), QBBRasterWindowSurface::flush(), QWSWindowSurface::flush(), QDirectFBWindowSurface::flush(), QWidgetPrivate::invalidateBuffer_resizeHelper(), QWidgetPrivate::isOverlapped(), QWidgetBackingStore::markDirty(), QWidgetBackingStore::markDirtyOnScreen(), QWidgetPrivate::moveRect(), QTableView::paintEvent(), QWidgetPrivate::paintSiblingsRecursive(), QWidgetBackingStore::removeDirtyWidget(), QWidgetPrivate::render(), QBBRasterWindowSurface::scroll(), QGraphicsView::scrollContentsBy(), QWidgetPrivate::scrollRect(), QWidget::setDisabled(), QWSWindowSurface::setGeometry(), QScreen::solidFill(), QWidgetPrivate::subtractOpaqueSiblings(), QWidgetBackingStore::sync(), and QWidget::visibleRegion().
 {
     QRegion ret(*this);
     ret.translate(dx, dy);
     return ret;
 }
translated() [2/2]
QRegion QRegion::translated (const QPoint & p) const inline
Returns a copy of the regtion that is translated {p}.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.1
x() along the x axis and {p}.y() along the y axis, relative to the current position. Positive values move the rectangle to the right and down.
See also
translate()
Definition at line 100 of file qregion.h.
Referenced by translated().
 { return translated(p.x(), p.y()); }
unite() [1/2]
QRegion QRegion::unite (const QRegion & r) const
Use united(r) instead.
Definition at line 4125 of file qregion.cpp.
Referenced by clipTransformIsSimple(), qt_bitmapToRegion(), and QColumnView::visualRegionForSelection().
 {
     if (isEmptyHelper(d->qt_rgn))
         return r;
     if (isEmptyHelper(r.d->qt_rgn))
         return *this;
     if (d == r.d)
         return *this;
     if (d->qt_rgn->contains(*r.d->qt_rgn)) {
         return *this;
     } else if (r.d->qt_rgn->contains(*d->qt_rgn)) {
         return r;
     } else if (d->qt_rgn->canAppend(r.d->qt_rgn)) {
         QRegion result(*this);
         result.detach();
         result.d->qt_rgn->append(r.d->qt_rgn);
         return result;
     } else if (d->qt_rgn->canPrepend(r.d->qt_rgn)) {
         QRegion result(*this);
         result.detach();
         result.d->qt_rgn->prepend(r.d->qt_rgn);
         return result;
     } else if (EqualRegion(d->qt_rgn, r.d->qt_rgn)) {
         return *this;
     } else {
         QRegion result;
         result.detach();
         UnionRegion(d->qt_rgn, r.d->qt_rgn, *result.d->qt_rgn);
         return result;
     }
 }
unite() [2/2]
QRegion QRegion::unite (const QRect & rect) const
Use united(rect) instead.
Since
4.4
Definition at line 4188 of file qregion.cpp.
 {
     if (isEmptyHelper(d->qt_rgn))
         return r;
     if (r.isEmpty())
         return *this;
     if (d->qt_rgn->contains(r)) {
         return *this;
     } else if (d->qt_rgn->within(r)) {
         return r;
     } else if (d->qt_rgn->numRects == 1 && d->qt_rgn->extents == r) {
         return *this;
     } else if (d->qt_rgn->canAppend(&r)) {
         QRegion result(*this);
         result.detach();
         result.d->qt_rgn->append(&r);
         return result;
     } else if (d->qt_rgn->canPrepend(&r)) {
         QRegion result(*this);
         result.detach();
         result.d->qt_rgn->prepend(&r);
         return result;
     } else {
         QRegion result;
         result.detach();
         QRegionPrivate rp(r);
         UnionRegion(d->qt_rgn, &rp, *result.d->qt_rgn);
         return result;
     }
 }
united() [1/2]
QRegion QRegion::united (const QRegion & r) const inline
Returns a region which is the union of this region and r.
Since
4.2
Region Union
The figure shows the union of two elliptical regions.
See also
intersected(), subtracted(), xored()
Definition at line 110 of file qregion.h.
Referenced by exec(), operator+(), and operator|().
 { return unite(r); }
united() [2/2]
QRegion QRegion::united (const QRect & rect) const inline
Returns a region which is the union of this region and the given rect.
Since
4.4
See also
intersected(), subtracted(), xored()
Definition at line 111 of file qregion.h.
 { return unite(r); }
winCombine()
QRegion QRegion::winCombine (const QRegion & r, int num) const private
xored()
QRegion QRegion::xored (const QRegion & r) const inline
Returns a region which is the exclusive or (XOR) of this region and r.
Since
4.2
Region XORed
The figure shows the exclusive or of two elliptical regions.
See also
intersected(), united(), subtracted()
Definition at line 115 of file qregion.h.
Referenced by exec(), and operator^().
 { return eor(r); }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & s, const QRegion & r) friend
Writes the region r to the stream s and returns a reference to the stream.
See also
Format of the QDataStream operators
Definition at line 446 of file qregion.cpp.
 {
     QVector<QRect> a = r.rects();
     if (a.isEmpty()) {
         s << (quint32)0;
     } else {
         if (s.version() == 1) {
             int i;
             for (i = a.size() - 1; i > 0; --i) {
                 s << (quint32)(12 + i * 24);
                 s << (int)QRGN_OR;
             }
             for (i = 0; i < a.size(); ++i) {
                 s << (quint32)(4+8) << (int)QRGN_SETRECT << a[i];
             }
         } else {
             s << (quint32)(4 + 4 + 16 * a.size()); // 16: storage size of QRect
             s << (qint32)QRGN_RECTS;
             s << a;
         }
     }
     return s;
 }
operator>>
QDataStream & operator>> (QDataStream & s, QRegion & r) friend
Reads a region from the stream s into r and returns a reference to the stream.
See also
Format of the QDataStream operators
Definition at line 482 of file qregion.cpp.
 {
     QByteArray b;
     s >> b;
     r.exec(b, s.version(), s.byteOrder());
     return s;
 }
QETWidget
friend class QETWidget friend
Definition at line 215 of file qregion.h.
QRegionPrivate
friend struct QRegionPrivate friend
Definition at line 195 of file qregion.h.
Referenced by copy(), QRegion(), qt_bitmapToRegion(), and UnionRectWithRegion().
qt_region_strictContains
bool qt_region_strictContains (const QRegion & region, const QRect & rect) friend
Returns true if rect is guaranteed to be fully contained in region.
Warning
This function is not part of the public interface.
A false return value does not guarantee the opposite.
Definition at line 4380 of file qregion.cpp.
 {
     if (isEmptyHelper(region.d->qt_rgn) || !rect.isValid())
         return false;
 #if 0 // TEST_INNERRECT
     static bool guard = false;
     if (guard)
         return false;
     guard = true;
     QRegion inner = region.d->qt_rgn->innerRect;
     Q_ASSERT((inner - region).isEmpty());
     guard = false;
     int maxArea = 0;
     for (int i = 0; i < region.d->qt_rgn->numRects; ++i) {
         const QRect r = region.d->qt_rgn->rects.at(i);
         if (r.width() * r.height() > maxArea)
             maxArea = r.width() * r.height();
     }
     if (maxArea > region.d->qt_rgn->innerArea) {
         qDebug() << "not largest rectangle" << region << region.d->qt_rgn->innerRect;
     }
     Q_ASSERT(maxArea <= region.d->qt_rgn->innerArea);
 #endif
     const QRect r1 = region.d->qt_rgn->innerRect;
     return (rect.left() >= r1.left() && rect.right() <= r1.right()
             && rect.top() >= r1.top() && rect.bottom() <= r1.bottom());
 }
Properties
d
struct QRegionData* QRegion::d private
Definition at line 217 of file qregion.h.
Referenced by boundingRect(), contains(), copy(), detach(), ensureHandle(), eor(), intersect(), intersects(), isEmpty(), numRects(), operator+=(), operator=(), operator==(), QRegion(), qt_bitmapToRegion(), qt_region_strictContains(), rectCount(), rects(), setRects(), subtract(), swap(), translate(), unite(), and ~QRegion().
shared_empty
QRegion::QRegionData QRegion::shared_empty = { Q_BASIC_ATOMIC_INITIALIZER(1), 0 } static private
Definition at line 218 of file qregion.h.
Referenced by QRegionPrivate::canPrepend(), isEmpty(), isEmptyHelper(), and QRegion().
The documentation for this class was generated from the following files:
/src/gui/painting/qregion.h
/src/gui/painting/qregion.cpp
/src/gui/painting/qregion_mac.cpp
/src/gui/painting/qregion_qws.cpp
/src/gui/painting/qregion_win.cpp
/src/gui/painting/qregion_x11.cpp