Qt 4.8: QDeclarativeInspectorService Class Reference
QDeclarativeInspectorService Class Reference
#include <qdeclarativeinspectorservice_p.h>
Signals
void gotMessage (const QByteArray &message)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addView (QDeclarativeView *)
QDeclarativeInspectorService ()
void removeView (QDeclarativeView *)
void sendMessage (const QByteArray &message)
QList< QDeclarativeView * > views () const
Public Functions inherited from QDeclarativeDebugService
QString name () const
QDeclarativeDebugService (const QString &, QObject *parent=0)
void sendMessage (const QByteArray &)
Status status () const
bool waitForMessage ()
~QDeclarativeDebugService ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeInspectorService * instance ()
Static Public Functions inherited from QDeclarativeDebugService
static bool hasDebuggingClient ()
static int idForObject (QObject *)
Returns a unique id for object.
static bool isDebuggingEnabled ()
static QObject * objectForId (int)
Returns the object for unique id.
static QString objectToString (QObject *obj)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual void messageReceived (const QByteArray &)
virtual void statusChanged (Status status)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void updateStatus ()
Static Private Functions
static QDeclarativeInspectorInterface * loadInspectorPlugin ()
Properties
QDeclarativeInspectorInterface * m_inspectorPlugin
QList< QDeclarativeView * > m_views
Additional Inherited Members
Public Types inherited from QDeclarativeDebugService
enum Status { NotConnected, Unavailable, Enabled }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 59 of file qdeclarativeinspectorservice_p.h.
Constructors and Destructors
QDeclarativeInspectorService()
QDeclarativeInspectorService::QDeclarativeInspectorService ()
Definition at line 56 of file qdeclarativeinspectorservice.cpp.
     : QDeclarativeDebugService(QLatin1String("QDeclarativeObserverMode"))
     , m_inspectorPlugin(0)
 {
 }
Functions
addView()
void QDeclarativeInspectorService::addView (QDeclarativeView * view)
Definition at line 67 of file qdeclarativeinspectorservice.cpp.
Referenced by QDeclarativeViewPrivate::init().
 {
     m_views.append(view);
     updateStatus();
 }
gotMessage
void QDeclarativeInspectorService::gotMessage (const QByteArray & message) signal
Referenced by messageReceived().
instance()
QDeclarativeInspectorService * QDeclarativeInspectorService::instance () static
Definition at line 62 of file qdeclarativeinspectorservice.cpp.
Referenced by QmlJSDebugger::AbstractViewInspector::AbstractViewInspector(), QmlJSDebugger::QDeclarativeInspectorPlugin::activate(), QDeclarativeViewPrivate::init(), and QDeclarativeView::~QDeclarativeView().
 {
     return serviceInstance();
 }
loadInspectorPlugin()
QDeclarativeInspectorInterface * QDeclarativeInspectorService::loadInspectorPlugin () static private
Definition at line 122 of file qdeclarativeinspectorservice.cpp.
Referenced by updateStatus().
 {
     QStringList pluginCandidates;
     const QStringList paths = QCoreApplication::libraryPaths();
     foreach (const QString &libPath, paths) {
         const QDir dir(libPath + QLatin1String("/qmltooling"));
         if (dir.exists())
             foreach (const QString &pluginPath, dir.entryList(QDir::Files))
                 pluginCandidates << dir.absoluteFilePath(pluginPath);
     }
     foreach (const QString &pluginPath, pluginCandidates) {
         QPluginLoader loader(pluginPath);
         if (!loader.load())
             continue;
         QDeclarativeInspectorInterface *inspector =
                 qobject_cast<QDeclarativeInspectorInterface*>(loader.instance());
         if (inspector)
             return inspector;
         loader.unload();
     }
     return 0;
 }
messageReceived()
void QDeclarativeInspectorService::messageReceived (const QByteArray & message) protected virtual
Reimplemented from QDeclarativeDebugService.
Definition at line 117 of file qdeclarativeinspectorservice.cpp.
 {
     emit gotMessage(message);
 }
removeView()
void QDeclarativeInspectorService::removeView (QDeclarativeView * view)
Definition at line 73 of file qdeclarativeinspectorservice.cpp.
Referenced by QDeclarativeView::~QDeclarativeView().
 {
     m_views.removeAll(view);
     updateStatus();
 }
sendMessage()
void QDeclarativeInspectorService::sendMessage (const QByteArray & message)
Definition at line 79 of file qdeclarativeinspectorservice.cpp.
Referenced by QmlJSDebugger::AbstractViewInspector::sendAnimationPaused(), QmlJSDebugger::AbstractViewInspector::sendAnimationSpeed(), QmlJSDebugger::AbstractViewInspector::sendColorChanged(), QmlJSDebugger::AbstractViewInspector::sendCurrentObjects(), QmlJSDebugger::AbstractViewInspector::sendCurrentTool(), QmlJSDebugger::AbstractViewInspector::sendDesignModeBehavior(), QmlJSDebugger::AbstractViewInspector::sendReloaded(), and QmlJSDebugger::AbstractViewInspector::sendShowAppOnTop().
 {
     if (status() != Enabled)
         return;
     QDeclarativeDebugService::sendMessage(message);
 }
statusChanged()
void QDeclarativeInspectorService::statusChanged (Status status) protected virtual
Reimplemented from QDeclarativeDebugService.
Definition at line 87 of file qdeclarativeinspectorservice.cpp.
 {
     Q_UNUSED(status);
     updateStatus();
 }
updateStatus()
void QDeclarativeInspectorService::updateStatus () private
Definition at line 93 of file qdeclarativeinspectorservice.cpp.
Referenced by addView(), removeView(), and statusChanged().
 {
     if (m_views.isEmpty()) {
         if (m_inspectorPlugin)
             m_inspectorPlugin->deactivate();
         return;
     }
     if (status() == Enabled) {
         if (!m_inspectorPlugin)
             m_inspectorPlugin = loadInspectorPlugin();
         if (!m_inspectorPlugin) {
             qWarning() << "Error while loading inspector plugin";
             return;
         }
         m_inspectorPlugin->activate();
     } else {
         if (m_inspectorPlugin)
             m_inspectorPlugin->deactivate();
     }
 }
views()
QList<QDeclarativeView*> QDeclarativeInspectorService::views () const inline
Definition at line 69 of file qdeclarativeinspectorservice_p.h.
Referenced by QmlJSDebugger::QDeclarativeInspectorPlugin::activate().
 { return m_views; }
Properties
m_inspectorPlugin
QDeclarativeInspectorInterface* QDeclarativeInspectorService::m_inspectorPlugin private
Definition at line 86 of file qdeclarativeinspectorservice_p.h.
Referenced by updateStatus().
m_views
QList<QDeclarativeView*> QDeclarativeInspectorService::m_views private
Definition at line 85 of file qdeclarativeinspectorservice_p.h.
Referenced by addView(), removeView(), and updateStatus().
The documentation for this class was generated from the following files:
/src/declarative/debugger/qdeclarativeinspectorservice_p.h
/src/declarative/debugger/qdeclarativeinspectorservice.cpp