Qt 4.8: QWSSocket Class Reference
QWSSocket Class Reference
#include <qwssocket_qws.h>
Signals
void connected ()
void disconnected ()
void error (QAbstractSocket::SocketError)
Public Functions
bool connectToLocalFile (const QString &file)
QString errorString ()
QWSSocket (QObject *parent=0)
~QWSSocket ()
Private Slots
void forwardStateChange (SocketState)
Detailed Description
Definition at line 66 of file qwssocket_qws.h.
Constructors and Destructors
QWSSocket()
QWSSocket::QWSSocket (QObject * parent = 0) explicit
Definition at line 88 of file qwssocket_qws.cpp.
Referenced by QWSServerSocket::nextPendingConnection().
     : QWS_SOCK_BASE(parent)
 {
 #ifndef QT_NO_SXE
     QObject::connect( this, SIGNAL(stateChanged(SocketState)),
             this, SLOT(forwardStateChange(SocketState)));
 #endif
 }
~QWSSocket()
QWSSocket::~QWSSocket ()
Definition at line 97 of file qwssocket_qws.cpp.
 {
 }
Functions
connected
void QWSSocket::connected () signal
Referenced by forwardStateChange().
connectToLocalFile()
bool QWSSocket::connectToLocalFile (const QString & file)
Definition at line 136 of file qwssocket_qws.cpp.
 {
 #ifndef QT_NO_SXE
     bool result = QUnixSocket::connect( file.toLocal8Bit() );
     if ( !result )
     {
         perror( "QWSSocketAuth::connectToLocalFile could not connect:" );
         emit error(QAbstractSocket::ConnectionRefusedError);
         return false;
     }
     return true;
 #else
     // create socket
     int s = ::socket(PF_LOCAL, SOCK_STREAM, 0);
     // connect to socket
     struct sockaddr_un a;
     memset(&a, 0, sizeof(a));
     a.sun_family = PF_LOCAL;
     strncpy(a.sun_path, file.toLocal8Bit().constData(), sizeof(a.sun_path) - 1);
     int r = ::connect(s, (struct sockaddr*)&a, SUN_LEN(&a));
     if (r == 0) {
         setSocketDescriptor(s);
     } else {
         perror("QWSSocket::connectToLocalFile could not connect:");
         ::close(s);
         emit error(ConnectionRefusedError);
         return false;
     }
 #endif
     return true;
 }
disconnected
void QWSSocket::disconnected () signal
Referenced by forwardStateChange().
error
void QWSSocket::error (QAbstractSocket::SocketError) signal
Referenced by connectToLocalFile(), and forwardStateChange().
errorString()
QString QWSSocket::errorString ()
Definition at line 102 of file qwssocket_qws.cpp.
Referenced by QWSClient::errorHandler(), and QWSServerSocket::init().
 {
     switch (QUnixSocket::error()) {
     case NoError:
         return QString();
     case InvalidPath:
     case NonexistentPath:
         return QLatin1String("Bad path"); // NO_TR
     default:
         return QLatin1String("Bad socket"); // NO TR
     }
 }
forwardStateChange
void QWSSocket::forwardStateChange (SocketState) private slot
Definition at line 115 of file qwssocket_qws.cpp.
Referenced by QWSSocket().
 {
     switch ( st )
     {
         case ConnectedState:
             emit connected();
             break;
         case ClosingState:
             break;
         case UnconnectedState:
             emit disconnected();
             break;
         default:
             // nothing
             break;
     }
     if ( QUnixSocket::error() != NoError )
         emit error((QAbstractSocket::SocketError)0);
 }
The documentation for this class was generated from the following files:
/src/gui/embedded/qwssocket_qws.h
/src/gui/embedded/qwssocket_qws.cpp