Qt 4.8: QGraphicsEffect Class Reference
QGraphicsEffect Class Reference abstract
The QGraphicsEffect class is the base class for all graphics effects.
#include <qgraphicseffect.h>
Public Types
enum ChangeFlag { SourceAttached = 0x1, SourceDetached = 0x2, SourceBoundingRectChanged = 0x4, SourceInvalidated = 0x8 }
This enum describes what has changed in QGraphicsEffectSource.
enum PixmapPadMode { NoPad, PadToTransparentBorder, PadToEffectiveBoundingRect }
This enum describes how the pixmap returned from sourcePixmap should be padded.
Public Slots
void setEnabled (bool enable)
void update ()
Schedules a redraw of the effect.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void enabledChanged (bool enabled)
This signal is emitted whenever the effect is enabled or disabled.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QRectF boundingRect () const
Returns the effective bounding rectangle for this effect, i.e., the bounding rectangle of the source in device coordinates, adjusted by any margins applied by the effect itself.
virtual QRectF boundingRectFor (const QRectF &sourceRect) const
Returns the effective bounding rectangle for this effect, given the provided rect in the device coordinates.
bool isEnabled () const
QGraphicsEffect (QObject *parent=0)
Constructs a new QGraphicsEffect instance having the specified parent.
QGraphicsEffectSource * source () const
Returns a pointer to the source, which provides extra context information that can be useful for the effect.
virtual ~QGraphicsEffect ()
Removes the effect from the source, and destroys the graphics effect.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void draw (QPainter *painter)=0
This pure virtual function draws the effect and is called whenever the source needs to be drawn.
void drawSource (QPainter *painter)
Draws the source directly using the given painter.
QGraphicsEffect (QGraphicsEffectPrivate &d, QObject *parent=0)
QRectF sourceBoundingRect (Qt::CoordinateSystem system=Qt::LogicalCoordinates) const
Returns the bounding rectangle of the source mapped to the given system.
virtual void sourceChanged (ChangeFlags flags)
This virtual function is called by QGraphicsEffect to notify the effect that the source has changed.
bool sourceIsPixmap () const
Returns true if the source effectively is a pixmap, e.g., a QGraphicsPixmapItem.
QPixmap sourcePixmap (Qt::CoordinateSystem system=Qt::LogicalCoordinates, QPoint *offset=0, PixmapPadMode mode=PadToEffectiveBoundingRect) const
Returns a pixmap with the source painted into it.
void updateBoundingRect ()
This function notifies the effect framework when the effect's bounding rectangle has changed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool enabled
whether the effect is enabled or not.
Friends
class QGraphicsItem
class QGraphicsItemPrivate
class QGraphicsScenePrivate
class QWidget
class QWidgetPrivate
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsEffect class is the base class for all graphics effects.
Since
4.6
Effects alter the appearance of elements by hooking into the rendering pipeline and operating between the source (e.g., a QGraphicsPixmapItem) and the destination device (e.g., QGraphicsView's viewport). Effects can be disabled by calling setEnabled(false). If effects are disabled, the source is rendered directly.
To add a visual effect to a QGraphicsItem, for example, you can use one of the standard effects, or alternately, create your own effect by creating a subclass of QGraphicsEffect. The effect can then be installed on the item using QGraphicsItem::setGraphicsEffect().
Qt provides the following standard effects:
QGraphicsBlurEffect - blurs the item by a given radius
QGraphicsDropShadowEffect - renders a dropshadow behind the item
QGraphicsColorizeEffect - renders the item in shades of any given color
QGraphicsOpacityEffect - renders the item with an opacity
For more information on how to use each effect, refer to the specific effect's documentation.
To create your own custom effect, create a subclass of QGraphicsEffect (or any other existing effects) and reimplement the virtual function draw(). This function is called whenever the effect needs to redraw. The draw() function takes the painter with which to draw as an argument. For more information, refer to the documenation for draw(). In the draw() function you can call sourcePixmap() to get a pixmap of the graphics effect source which you can then process.
If your effect changes, use update() to request for a redraw. If your custom effect changes the bounding rectangle of the source, e.g., a radial glow effect may need to apply an extra margin, you can reimplement the virtual boundingRectFor() function, and call updateBoundingRect() to notify the framework whenever this rectangle changes. The virtual sourceChanged() function is called to notify the effects that the source has changed in some way - e.g., if the source is a QGraphicsRectItem and its rectangle parameters have changed.
See also
QGraphicsItem::setGraphicsEffect(), QWidget::setGraphicsEffect()
Definition at line 66 of file qgraphicseffect.h.
Enumerations
ChangeFlag
enum QGraphicsEffect::ChangeFlag
This enum describes what has changed in QGraphicsEffectSource.
SourceAttached The effect is installed on a source.
SourceDetached The effect is uninstalled on a source.
SourceBoundingRectChanged The bounding rect of the source has changed.
SourceInvalidated The visual appearance of the source has changed.
Enumerator
SourceAttached
SourceDetached
SourceBoundingRectChanged
SourceInvalidated
Definition at line 72 of file qgraphicseffect.h.
                     {
         SourceAttached = 0x1,
         SourceDetached = 0x2,
         SourceBoundingRectChanged = 0x4,
         SourceInvalidated = 0x8
     };
PixmapPadMode
enum QGraphicsEffect::PixmapPadMode
This enum describes how the pixmap returned from sourcePixmap should be padded.
NoPad The pixmap should not receive any additional padding.
PadToTransparentBorder The pixmap should be padded to ensure it has a completely transparent border.
PadToEffectiveBoundingRect The pixmap should be padded to match the effective bounding rectangle of the effect.
Enumerator
NoPad
PadToTransparentBorder
PadToEffectiveBoundingRect
Definition at line 80 of file qgraphicseffect.h.
{
         NoPad,
         PadToTransparentBorder,
         PadToEffectiveBoundingRect
     };
Constructors and Destructors
QGraphicsEffect() [1/2]
QGraphicsEffect::QGraphicsEffect (QObject * parent = 0)
Constructs a new QGraphicsEffect instance having the specified parent.
Definition at line 403 of file qgraphicseffect.cpp.
     : QObject(*new QGraphicsEffectPrivate, parent)
 {
 }
~QGraphicsEffect()
QGraphicsEffect::~QGraphicsEffect () virtual
Removes the effect from the source, and destroys the graphics effect.
Definition at line 419 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsEffect);
     d->setGraphicsEffectSource(0);
 }
QGraphicsEffect() [2/2]
QGraphicsEffect::QGraphicsEffect (QGraphicsEffectPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 411 of file qgraphicseffect.cpp.
     : QObject(dd, parent)
 {
 }
Functions
boundingRect()
QRectF QGraphicsEffect::boundingRect () const
Returns the effective bounding rectangle for this effect, i.e., the bounding rectangle of the source in device coordinates, adjusted by any margins applied by the effect itself.
See also
boundingRectFor(), updateBoundingRect()
Definition at line 432 of file qgraphicseffect.cpp.
 {
     Q_D(const QGraphicsEffect);
     if (d->source)
         return boundingRectFor(d->source->boundingRect());
     return QRectF();
 }
boundingRectFor()
QRectF QGraphicsEffect::boundingRectFor (const QRectF & rect) const virtual
Returns the effective bounding rectangle for this effect, given the provided rect in the device coordinates.
When writing you own custom effect, you must call updateBoundingRect() whenever any parameters are changed that may cause this this function to return a different value.
See also
sourceBoundingRect()
Reimplemented in QGraphicsDropShadowEffect, and QGraphicsBlurEffect.
Definition at line 449 of file qgraphicseffect.cpp.
Referenced by boundingRect(), and QGraphicsItemPrivate::effectiveBoundingRect().
 {
     return rect;
 }
draw()
void QGraphicsEffect::draw (QPainter * painter) protected pure virtual
This pure virtual function draws the effect and is called whenever the source needs to be drawn.
Reimplement this function in a QGraphicsEffect subclass to provide the effect's drawing implementation, using painter.
For example:
MyGraphicsEffect::draw(QPainter *painter)
{
    ...
    QPoint offset;
    if (sourceIsPixmap()) {
        // No point in drawing in device coordinates (pixmap will be scaled anyways).
        const QPixmap pixmap = sourcePixmap(Qt::LogicalCoordinates, &offset);
        ...
        painter->drawPixmap(offset, pixmap);
    } else {
        // Draw pixmap in device coordinates to avoid pixmap scaling;
        const QPixmap pixmap = sourcePixmap(Qt::DeviceCoordinates, &offset);
        painter->setWorldTransform(QTransform());
        ...
        painter->drawPixmap(offset, pixmap);
    }
    ...
}
This function should not be called explicitly by the user, since it is meant for reimplementation purposes only.
Implemented in QGraphicsOpacityEffect, QGraphicsDropShadowEffect, QGraphicsBlurEffect, QGraphicsColorizeEffect, QGraphicsShaderEffect, and ShaderEffect.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QWidgetPrivate::drawWidget(), and QGraphicsDropShadowEffect::setYOffset().
drawSource()
void QGraphicsEffect::drawSource (QPainter * painter) protected
Draws the source directly using the given painter.
This function should only be called from QGraphicsEffect::draw().
For example:
MyGraphicsOpacityEffect::draw(QPainter *painter)
{
    // Fully opaque; draw directly without going through a pixmap.
    if (qFuzzyCompare(m_opacity, 1)) {
        drawSource(painter);
        return;
    }
    ...
}
See also
QGraphicsEffect::draw()
Definition at line 255 of file qgraphicseffect.cpp.
Referenced by ShaderEffect::draw(), QGraphicsShaderEffect::draw(), QGraphicsColorizeEffect::draw(), QGraphicsBlurEffect::draw(), QGraphicsDropShadowEffect::draw(), QGraphicsOpacityEffect::draw(), and ShaderEffect::updateRenderTargets().
 {
     Q_D(const QGraphicsEffect);
     if (d->source)
         d->source->draw(painter);
 }
enabledChanged
void QGraphicsEffect::enabledChanged (bool enabled) signal
This signal is emitted whenever the effect is enabled or disabled.
The enabled parameter holds the effects's new enabled state.
See also
isEnabled()
Referenced by setEnabled().
isEnabled()
bool QGraphicsEffect::isEnabled () const
Definition at line 470 of file qgraphicseffect.cpp.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QWidgetPrivate::drawWidget(), QGraphicsItemPrivate::effectiveBoundingRect(), and QGraphicsItemPrivate::markParentDirty().
 {
     Q_D(const QGraphicsEffect);
     return d->isEnabled;
 }
setEnabled
void QGraphicsEffect::setEnabled (bool enable) slot
Definition at line 476 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsEffect);
     if (d->isEnabled == enable)
         return;
     d->isEnabled = enable;
     if (d->source) {
         d->source->d_func()->effectBoundingRectChanged();
         d->source->d_func()->invalidateCache();
     }
     emit enabledChanged(enable);
 }
source()
QGraphicsEffectSource * QGraphicsEffect::source () const
Returns a pointer to the source, which provides extra context information that can be useful for the effect.
Warning
This function is not part of the public interface.
See also
draw()
Definition at line 526 of file qgraphicseffect.cpp.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QWidgetPrivate::drawWidget(), QGraphicsItemPrivate::invalidateChildGraphicsEffectsRecursively(), QWidgetPrivate::invalidateGraphicsEffectsRecursively(), QGraphicsItemPrivate::invalidateParentGraphicsEffectsRecursively(), and QGraphicsItemPrivate::markParentDirty().
 {
     Q_D(const QGraphicsEffect);
     return d->source;
 }
sourceBoundingRect()
QRectF QGraphicsEffect::sourceBoundingRect (Qt::CoordinateSystem system = Qt::LogicalCoordinates) const protected
Returns the bounding rectangle of the source mapped to the given system.
Calling this function with Qt::DeviceCoordinates outside of QGraphicsEffect::draw() will give undefined results, as there is no device context available.
See also
draw()
Definition at line 175 of file qgraphicseffect.cpp.
Referenced by QGraphicsOpacityEffect::draw().
 {
     Q_D(const QGraphicsEffect);
     if (d->source)
         return d->source->boundingRect(system);
     return QRectF();
 }
sourceChanged()
void QGraphicsEffect::sourceChanged (ChangeFlags flags) protected virtual
This virtual function is called by QGraphicsEffect to notify the effect that the source has changed.
If the effect applies any cache, then this cache must be purged in order to reflect the new appearance of the source.
The flags describes what has changed.
Reimplemented in ShaderEffect.
Definition at line 607 of file qgraphicseffect.cpp.
Referenced by QGraphicsScenePrivate::resetDirtyItem().
 {
     Q_UNUSED(flags);
 }
sourceIsPixmap()
bool QGraphicsEffect::sourceIsPixmap () const protected
Returns true if the source effectively is a pixmap, e.g., a QGraphicsPixmapItem.
This function is useful for optimization purposes. For instance, there's no point in drawing the source in device coordinates to avoid pixmap scaling if this function returns true - the source pixmap will be scaled anyways.
Definition at line 295 of file qgraphicseffect.cpp.
Referenced by QGraphicsShaderEffect::draw(), QGraphicsColorizeEffect::draw(), and QGraphicsOpacityEffect::draw().
 {
     return source() ? source()->isPixmap() : false;
 }
sourcePixmap()
QPixmap QGraphicsEffect::sourcePixmap (Qt::CoordinateSystem system = Qt::LogicalCoordinates, QPoint * offset = 0, QGraphicsEffect::PixmapPadMode mode = PadToEffectiveBoundingRect) const protected
Returns a pixmap with the source painted into it.
The system specifies which coordinate system to be used for the source. The optional offset parameter returns the offset where the pixmap should be painted at using the current painter. For control on how the pixmap is padded use the mode parameter.
The returned pixmap is clipped to the current painter's device rectangle when system is Qt::DeviceCoordinates.
Calling this function with Qt::DeviceCoordinates outside of QGraphicsEffect::draw() will give undefined results, as there is no device context available.
See also
draw(), boundingRect()
Definition at line 370 of file qgraphicseffect.cpp.
Referenced by QGraphicsShaderEffect::draw(), QGraphicsColorizeEffect::draw(), QGraphicsBlurEffect::draw(), QGraphicsDropShadowEffect::draw(), and QGraphicsOpacityEffect::draw().
 {
     Q_D(const QGraphicsEffect);
     if (d->source)
         return d->source->pixmap(system, offset, mode);
     return QPixmap();
 }
update
void QGraphicsEffect::update () slot
Schedules a redraw of the effect.
Call this function whenever the effect needs to be redrawn. This function does not trigger a redraw of the source.
See also
updateBoundingRect()
Definition at line 508 of file qgraphicseffect.cpp.
Referenced by QGraphicsColorizeEffect::setColor(), QGraphicsDropShadowEffect::setColor(), QGraphicsOpacityEffect::setOpacity(), QGraphicsOpacityEffect::setOpacityMask(), and QGraphicsColorizeEffect::setStrength().
 {
     Q_D(QGraphicsEffect);
     if (d->source)
         d->source->update();
 }
updateBoundingRect()
void QGraphicsEffect::updateBoundingRect () protected
This function notifies the effect framework when the effect's bounding rectangle has changed.
As a custom effect author, you must call this function whenever you change any parameters that will cause the virtual boundingRectFor() function to return a different value.
This function will call update() if this is necessary.
See also
boundingRectFor(), boundingRect(), sourceBoundingRect()
Definition at line 542 of file qgraphicseffect.cpp.
Referenced by QGraphicsBlurEffect::setBlurRadius(), QGraphicsDropShadowEffect::setBlurRadius(), and QGraphicsDropShadowEffect::setOffset().
 {
     Q_D(QGraphicsEffect);
     if (d->source) {
         d->source->d_func()->effectBoundingRectChanged();
         d->source->d_func()->invalidateCache(QGraphicsEffectSourcePrivate::EffectRectChanged);
     }
 }
Friends and Related Functions
QGraphicsItem
friend class QGraphicsItem friend
Definition at line 117 of file qgraphicseffect.h.
QGraphicsItemPrivate
friend class QGraphicsItemPrivate friend
Definition at line 118 of file qgraphicseffect.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 119 of file qgraphicseffect.h.
QWidget
friend class QWidget friend
Definition at line 120 of file qgraphicseffect.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 121 of file qgraphicseffect.h.
Properties
enabled
QGraphicsEffect::enabled private
whether the effect is enabled or not.
If an effect is disabled, the source will be rendered with as normal, with no interference from the effect. If the effect is enabled, the source will be rendered with the effect applied.
This property is enabled by default.
Using this property, you can disable certain effects on slow platforms, in order to ensure that the user interface is responsive.
Definition at line 70 of file qgraphicseffect.h.
The documentation for this class was generated from the following files:
/src/gui/effects/qgraphicseffect.h
/src/gui/effects/qgraphicseffect.cpp