Qt 4.8: QFrameInfo Class Reference
QFrameInfo Class Reference
Public Functions
bool isEndMarker ()
bool isValid ()
QFrameInfo (bool endMark)
QFrameInfo ()
QFrameInfo (const QPixmap &pixmap, int delay)
Static Public Functions
static QFrameInfo endMarker ()
Public Variables
int delay
bool endMark
QPixmap pixmap
Detailed Description
Definition at line 227 of file qmovie.cpp.
Constructors and Destructors
QFrameInfo() [1/3]
QFrameInfo::QFrameInfo (bool endMark) inline
Definition at line 233 of file qmovie.cpp.
         : pixmap(QPixmap()), delay(QMOVIE_INVALID_DELAY), endMark(endMark)
     { }
QFrameInfo() [2/3]
QFrameInfo::QFrameInfo () inline
Definition at line 237 of file qmovie.cpp.
Referenced by endMarker().
         : pixmap(QPixmap()), delay(QMOVIE_INVALID_DELAY), endMark(false)
     { }
QFrameInfo() [3/3]
QFrameInfo::QFrameInfo (const QPixmap & pixmap, int delay) inline
Definition at line 241 of file qmovie.cpp.
         : pixmap(pixmap), delay(delay), endMark(false)
     { }
Functions
endMarker()
static QFrameInfo QFrameInfo::endMarker () inline static
Definition at line 253 of file qmovie.cpp.
Referenced by QMoviePrivate::infoForFrame().
     { return QFrameInfo(true); }
isEndMarker()
bool QFrameInfo::isEndMarker () inline
Definition at line 250 of file qmovie.cpp.
Referenced by QMoviePrivate::next().
     { return endMark; }
isValid()
bool QFrameInfo::isValid () inline
Definition at line 245 of file qmovie.cpp.
Referenced by QMoviePrivate::next().
     {
         return endMark || !(pixmap.isNull() && (delay == QMOVIE_INVALID_DELAY));
     }
Properties
delay
int QFrameInfo::delay
Definition at line 231 of file qmovie.cpp.
Referenced by QMoviePrivate::next().
endMark
bool QFrameInfo::endMark
Definition at line 232 of file qmovie.cpp.
Referenced by isEndMarker().
pixmap
QPixmap QFrameInfo::pixmap
Definition at line 230 of file qmovie.cpp.
Referenced by QMoviePrivate::next().
The documentation for this class was generated from the following file:
/src/gui/image/qmovie.cpp