Qt 4.8: QTextStream Class Reference
QTextStream Class Reference
The QTextStream class provides a convenient interface for reading and writing text.
#include <qtextstream.h>
Public Types
enum FieldAlignment { AlignLeft, AlignRight, AlignCenter, AlignAccountingStyle }
This enum specifies how to align text in fields when the field is wider than the text that occupies it.
enum NumberFlag {
ShowBase = 0x1, ForcePoint = 0x2, ForceSign = 0x4, UppercaseBase = 0x8,
UppercaseDigits = 0x10
}
This enum specifies various flags that can be set to affect the output of integers, floats, and doubles.
enum RealNumberNotation { SmartNotation, FixedNotation, ScientificNotation }
This enum specifies which notations to use for expressing float and double as strings.
enum Status { Ok, ReadPastEnd, ReadCorruptData, WriteFailed }
This enum describes the current status of the text stream.
Public Functions
bool atEnd () const
Returns true if there is no more data to be read from the QTextStream; otherwise returns false.
bool autoDetectUnicode () const
Returns true if automatic Unicode detection is enabled, otherwise returns false.
QTextCodec * codec () const
Returns the codec that is current assigned to the stream.
QIODevice * device () const
Returns the current device associated with the QTextStream, or 0 if no device has been assigned.
FieldAlignment fieldAlignment () const
Returns the current field alignment.
int fieldWidth () const
Returns the current field width.
void flush ()
Flushes any buffered data waiting to be written to the device.
bool generateByteOrderMark () const
Returns true if QTextStream is set to generate the UTF BOM (Byte Order Mark) when using a UTF codec; otherwise returns false.
int integerBase () const
Returns the current base of integers.
QLocale locale () const
Returns the locale for this stream.
NumberFlags numberFlags () const
Returns the current number flags.
QTextStream & operator<< (QBool b)
QTextStream & operator<< (QChar ch)
Writes the character c to the stream, then returns a reference to the QTextStream.
QTextStream & operator<< (char ch)
Converts c from ASCII to a QChar, then writes it to the stream.
QTextStream & operator<< (signed short i)
Writes the integer number i to the stream, then returns a reference to the QTextStream.
QTextStream & operator<< (unsigned short i)
Writes the unsigned short i to the stream.
QTextStream & operator<< (signed int i)
Writes the signed int i to the stream.
QTextStream & operator<< (unsigned int i)
Writes the unsigned int i to the stream.
QTextStream & operator<< (signed long i)
Writes the signed long i to the stream.
QTextStream & operator<< (unsigned long i)
Writes the unsigned long i to the stream.
QTextStream & operator<< (qlonglong i)
Writes the qlonglong i to the stream.
QTextStream & operator<< (qulonglong i)
Writes the qulonglong i to the stream.
QTextStream & operator<< (float f)
Writes the real number f to the stream, then returns a reference to the QTextStream.
QTextStream & operator<< (double f)
Writes the double f to the stream.
QTextStream & operator<< (const QString &s)
Writes the string string to the stream, and returns a reference to the QTextStream.
QTextStream & operator<< (const QByteArray &array)
Writes array to the stream.
QTextStream & operator<< (const char *c)
Writes the constant string pointed to by string to the stream.
QTextStream & operator<< (const void *ptr)
Writes ptr to the stream as a hexadecimal number with a base.
QTextStream & operator>> (QChar &ch)
Reads a character from the stream and stores it in c.
QTextStream & operator>> (char &ch)
Reads a character from the stream and stores it in c.
QTextStream & operator>> (signed short &i)
Reads an integer from the stream and stores it in i, then returns a reference to the QTextStream.
QTextStream & operator>> (unsigned short &i)
Stores the integer in the unsigned short i.
QTextStream & operator>> (signed int &i)
Stores the integer in the signed int i.
QTextStream & operator>> (unsigned int &i)
Stores the integer in the unsigned int i.
QTextStream & operator>> (signed long &i)
Stores the integer in the signed long i.
QTextStream & operator>> (unsigned long &i)
Stores the integer in the unsigned long i.
QTextStream & operator>> (qlonglong &i)
Stores the integer in the qlonglong i.
QTextStream & operator>> (qulonglong &i)
Stores the integer in the qulonglong i.
QTextStream & operator>> (float &f)
Reads a real number from the stream and stores it in f, then returns a reference to the QTextStream.
QTextStream & operator>> (double &f)
Stores the real number in the double f.
QTextStream & operator>> (QString &s)
Reads a word from the stream and stores it in str, then returns a reference to the stream.
QTextStream & operator>> (QByteArray &array)
Converts the word to ISO-8859-1, then stores it in array.
QTextStream & operator>> (char *c)
Stores the word in c, terminated by a '\0' character.
QChar padChar () const
Returns the current pad character.
qint64 pos () const
Returns the device position corresponding to the current position of the stream, or -1 if an error occurs (e.
QTextStream ()
Constructs a QTextStream.
QTextStream (QIODevice *device)
Constructs a QTextStream that operates on device.
QTextStream (FILE *fileHandle, QIODevice::OpenMode openMode=QIODevice::ReadWrite)
Constructs a QTextStream that operates on fileHandle, using openMode to define the open mode.
QTextStream (QString *string, QIODevice::OpenMode openMode=QIODevice::ReadWrite)
Constructs a QTextStream that operates on string, using openMode to define the open mode.
QTextStream (QByteArray *array, QIODevice::OpenMode openMode=QIODevice::ReadWrite)
Constructs a QTextStream that operates on array, using openMode to define the open mode.
QTextStream (const QByteArray &array, QIODevice::OpenMode openMode=QIODevice::ReadOnly)
Constructs a QTextStream that operates on array, using openMode to define the open mode.
QString read (qint64 maxlen)
Reads at most maxlen characters from the stream, and returns the data read as a QString.
QString readAll ()
Reads the entire content of the stream, and returns it as a QString.
QString readLine (qint64 maxlen=0)
Reads one line of text from the stream, and returns it as a QString.
RealNumberNotation realNumberNotation () const
Returns the current real number notation.
int realNumberPrecision () const
Returns the current real number precision, or the number of fraction digits QTextStream will write when generating real numbers.
void reset ()
Resets QTextStream's formatting options, bringing it back to its original constructed state.
void resetStatus ()
Resets the status of the text stream.
bool seek (qint64 pos)
Seeks to the position pos in the device.
void setAutoDetectUnicode (bool enabled)
If enabled is true, QTextStream will attempt to detect Unicode encoding by peeking into the stream data to see if it can find the UTF-16 or UTF-32 BOM (Byte Order Mark).
void setCodec (QTextCodec *codec)
Sets the codec for this stream to codec.
void setCodec (const char *codecName)
Sets the codec for this stream to the QTextCodec for the encoding specified by codecName.
void setDevice (QIODevice *device)
Sets the current device to device.
void setFieldAlignment (FieldAlignment alignment)
Sets the field alignment to mode.
void setFieldWidth (int width)
Sets the current field width to width.
void setGenerateByteOrderMark (bool generate)
If generate is true and a UTF codec is used, QTextStream will insert the BOM (Byte Order Mark) before any data has been written to the device.
void setIntegerBase (int base)
Sets the base of integers to base, both for reading and for generating numbers.
void setLocale (const QLocale &locale)
Sets the locale for this stream to locale.
void setNumberFlags (NumberFlags flags)
Sets the current number flags to flags.
void setPadChar (QChar ch)
Sets the pad character to ch.
void setRealNumberNotation (RealNumberNotation notation)
Sets the real number notation to notation (SmartNotation, FixedNotation, ScientificNotation).
void setRealNumberPrecision (int precision)
Sets the precision of real numbers to precision.
void setStatus (Status status)
Sets the status of the text stream to the status given.
void setString (QString *string, QIODevice::OpenMode openMode=QIODevice::ReadWrite)
Sets the current string to string, using the given openMode.
void skipWhiteSpace ()
Reads and discards whitespace from the stream until either a non-space character is detected, or until atEnd() returns true.
Status status () const
Returns the status of the text stream.
QString * string () const
Returns the current string assigned to the QTextStream, or 0 if no string has been assigned.
virtual ~QTextStream ()
Destroys the QTextStream.
Properties
QScopedPointer< QTextStreamPrivate > d_ptr
Related Functions
(Note that these are not member functions.)
QTextStream & bin (QTextStream &stream)
Calls QTextStream::setIntegerBase(2) on stream and returns stream.
QTextStream & bom (QTextStream &stream)
Toggles insertion of the Byte Order Mark on stream when QTextStream is used with a UTF codec.
QTextStream & center (QTextStream &stream)
Calls QTextStream::setFieldAlignment(QTextStream::AlignCenter) on stream and returns stream.
QTextStream & dec (QTextStream &stream)
Calls QTextStream::setIntegerBase(10) on stream and returns stream.
QTextStream & endl (QTextStream &stream)
Writes '
' to the stream and flushes the stream.
QTextStream & fixed (QTextStream &stream)
Calls QTextStream::setRealNumberNotation(QTextStream::FixedNotation) on stream and returns stream.
QTextStream & flush (QTextStream &stream)
Calls QTextStream::flush() on stream and returns stream.
QTextStream & forcepoint (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::ForcePoint) on stream and returns stream.
QTextStream & forcesign (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::ForceSign) on stream and returns stream.
QTextStream & hex (QTextStream &stream)
Calls QTextStream::setIntegerBase(16) on stream and returns stream.
QTextStream & left (QTextStream &stream)
Calls QTextStream::setFieldAlignment(QTextStream::AlignLeft) on stream and returns stream.
QTextStream & lowercasebase (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::UppercaseBase) on stream and returns stream.
QTextStream & lowercasedigits (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::UppercaseDigits) on stream and returns stream.
QTextStream & noforcepoint (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::ForcePoint) on stream and returns stream.
QTextStream & noforcesign (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::ForceSign) on stream and returns stream.
QTextStream & noshowbase (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::ShowBase) on stream and returns stream.
QTextStream & oct (QTextStream &stream)
Calls QTextStream::setIntegerBase(8) on stream and returns stream.
QTextStreamManipulator qSetFieldWidth (int width)
Equivalent to QTextStream::setFieldWidth(width).
QTextStreamManipulator qSetPadChar (QChar ch)
Equivalent to QTextStream::setPadChar(ch).
QTextStreamManipulator qSetRealNumberPrecision (int precision)
Equivalent to QTextStream::setRealNumberPrecision(precision).
QTextStream & reset (QTextStream &stream)
Calls QTextStream::reset() on stream and returns stream.
QTextStream & right (QTextStream &stream)
Calls QTextStream::setFieldAlignment(QTextStream::AlignRight) on stream and returns stream.
QTextStream & scientific (QTextStream &stream)
Calls QTextStream::setRealNumberNotation(QTextStream::ScientificNotation) on stream and returns stream.
QTextStream & showbase (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::ShowBase) on stream and returns stream.
QTextStream & uppercasebase (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::UppercaseBase) on stream and returns stream.
QTextStream & uppercasedigits (QTextStream &stream)
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::UppercaseDigits) on stream and returns stream.
QTextStream & ws (QTextStream &stream)
Calls skipWhiteSpace() on stream and returns stream.
Detailed Description
The QTextStream class provides a convenient interface for reading and writing text.
Note
This class or function is reentrant.
QTextStream can operate on a QIODevice, a QByteArray or a QString. Using QTextStream's streaming operators, you can conveniently read and write words, lines and numbers. For generating text, QTextStream supports formatting options for field padding and alignment, and formatting of numbers. Example:
QFile data("output.txt");
if (data.open(QFile::WriteOnly | QFile::Truncate)) {
    QTextStream out(&data);
    out << "Result: " << qSetFieldWidth(10) << left << 3.14 << 2.7;
    // writes "Result: 3.14      2.7       "
}
It's also common to use QTextStream to read console input and write console output. QTextStream is locale aware, and will automatically decode standard input using the correct codec. Example:
QTextStream stream(stdin);
QString line;
do {
    line = stream.readLine();
} while (!line.isNull());
Besides using QTextStream's constructors, you can also set the device or string QTextStream operates on by calling setDevice() or setString(). You can seek to a position by calling seek(), and atEnd() will return true when there is no data left to be read. If you call flush(), QTextStream will empty all data from its write buffer into the device and call flush() on the device.
Internally, QTextStream uses a Unicode based buffer, and QTextCodec is used by QTextStream to automatically support different character sets. By default, QTextCodec::codecForLocale() is used for reading and writing, but you can also set the codec by calling setCodec(). Automatic Unicode detection is also supported. When this feature is enabled (the default behavior), QTextStream will detect the UTF-16 or the UTF-32 BOM (Byte Order Mark) and switch to the appropriate UTF codec when reading. QTextStream does not write a BOM by default, but you can enable this by calling setGenerateByteOrderMark(true). When QTextStream operates on a QString directly, the codec is disabled.
There are three general ways to use QTextStream when reading text files:
Chunk by chunk, by calling readLine() or readAll().
Word by word. QTextStream supports streaming into QStrings, QByteArrays and char* buffers. Words are delimited by space, and leading white space is automatically skipped.
Character by character, by streaming into QChar or char types. This method is often used for convenient input handling when parsing files, independent of character encoding and end-of-line semantics. To skip white space, call skipWhiteSpace().
Since the text stream uses a buffer, you should not read from the stream using the implementation of a superclass. For instance, if you have a QFile and read from it directly using QFile::readLine() instead of using the stream, the text stream's internal position will be out of sync with the file's position.
By default, when reading numbers from a stream of text, QTextStream will automatically detect the number's base representation. For example, if the number starts with "0x", it is assumed to be in hexadecimal form. If it starts with the digits 1-9, it is assumed to be in decimal form, and so on. You can set the integer base, thereby disabling the automatic detection, by calling setIntegerBase(). Example:
QTextStream in("0x50 0x20");
int firstNumber, secondNumber;
in >> firstNumber;             // firstNumber == 80
in >> dec >> secondNumber;     // secondNumber == 0
char ch;
in >> ch;                      // ch == 'x'
QTextStream supports many formatting options for generating text. You can set the field width and pad character by calling setFieldWidth() and setPadChar(). Use setFieldAlignment() to set the alignment within each field. For real numbers, call setRealNumberNotation() and setRealNumberPrecision() to set the notation (SmartNotation, ScientificNotation, FixedNotation) and precision in digits of the generated number. Some extra number formatting options are also available through setNumberFlags().
QTextStream manipulators
Like <iostream> in the standard C++ library, QTextStream also defines several global manipulator functions:
Manipulator Description
bin Same as setIntegerBase(2).
oct Same as setIntegerBase(8).
dec Same as setIntegerBase(10).
hex Same as setIntegerBase(16).
showbase Same as setNumberFlags(numberFlags() | ShowBase).
forcesign Same as setNumberFlags(numberFlags() | ForceSign).
forcepoint Same as setNumberFlags(numberFlags() | ForcePoint).
noshowbase Same as setNumberFlags(numberFlags() & ~ShowBase).
noforcesign Same as setNumberFlags(numberFlags() & ~ForceSign).
noforcepoint Same as setNumberFlags(numberFlags() & ~ForcePoint).
uppercasebase Same as setNumberFlags(numberFlags() | UppercaseBase).
uppercasedigits Same as setNumberFlags(numberFlags() | UppercaseDigits).
lowercasebase Same as setNumberFlags(numberFlags() & ~UppercaseBase).
lowercasedigits Same as setNumberFlags(numberFlags() & ~UppercaseDigits).
fixed Same as setRealNumberNotation(FixedNotation).
scientific Same as setRealNumberNotation(ScientificNotation).
left Same as setFieldAlignment(AlignLeft).
right Same as setFieldAlignment(AlignRight).
center Same as setFieldAlignment(AlignCenter).
endl Same as operator<<('
') and flush().
flush Same as flush().
reset Same as reset().
ws Same as skipWhiteSpace().
bom Same as setGenerateByteOrderMark(true).
In addition, Qt provides three global manipulators that take a parameter: qSetFieldWidth(), qSetPadChar(), and qSetRealNumberPrecision().
See also
QDataStream, QIODevice, QFile, QBuffer, QTcpSocket, {Codecs Example}
Definition at line 73 of file qtextstream.h.
Enumerations
FieldAlignment
enum QTextStream::FieldAlignment
This enum specifies how to align text in fields when the field is wider than the text that occupies it.
AlignLeft Pad on the right side of fields.
AlignRight Pad on the left side of fields.
AlignCenter Pad on both sides of field.
AlignAccountingStyle Same as AlignRight, except that the sign of a number is flush left.
See also
setFieldAlignment()
Enumerator
AlignLeft
AlignRight
AlignCenter
AlignAccountingStyle
Definition at line 83 of file qtextstream.h.
{
         AlignLeft,
         AlignRight,
         AlignCenter,
         AlignAccountingStyle
     };
NumberFlag
enum QTextStream::NumberFlag
This enum specifies various flags that can be set to affect the output of integers, floats, and doubles.
ShowBase Show the base as a prefix if the base is 16 ("0x"), 8 ("0"), or 2 ("0b").
ForcePoint Always put the decimal separator in numbers, even if there are no decimals.
ForceSign Always put the sign in numbers, even for positive numbers.
UppercaseBase Use uppercase versions of base prefixes ("0X", "0B").
UppercaseDigits Use uppercase letters for expressing digits 10 to 35 instead of lowercase.
See also
setNumberFlags()
Enumerator
ShowBase
ForcePoint
ForceSign
UppercaseBase
UppercaseDigits
Definition at line 95 of file qtextstream.h.
                     {
         ShowBase = 0x1,
         ForcePoint = 0x2,
         ForceSign = 0x4,
         UppercaseBase = 0x8,
         UppercaseDigits = 0x10
     };
RealNumberNotation
enum QTextStream::RealNumberNotation
This enum specifies which notations to use for expressing float and double as strings.
ScientificNotation Scientific notation (printf()'s e flag).
FixedNotation Fixed-point notation (printf()'s f flag).
SmartNotation Scientific or fixed-point notation, depending on which makes most sense (printf()'s g flag).
See also
setRealNumberNotation()
Enumerator
SmartNotation
FixedNotation
ScientificNotation
Definition at line 78 of file qtextstream.h.
{
         SmartNotation,
         FixedNotation,
         ScientificNotation
     };
Status
enum QTextStream::Status
This enum describes the current status of the text stream.
Ok The text stream is operating normally.
ReadPastEnd The text stream has read past the end of the data in the underlying device.
ReadCorruptData The text stream has read corrupt data.
WriteFailed The text stream cannot write to the underlying device.
See also
status()
Enumerator
Ok
ReadPastEnd
ReadCorruptData
WriteFailed
Definition at line 89 of file qtextstream.h.
                 {
         Ok,
         ReadPastEnd,
         ReadCorruptData,
         WriteFailed
     };
Constructors and Destructors
QTextStream() [1/6]
QTextStream::QTextStream ()
Constructs a QTextStream.
Before you can use it for reading or writing, you must assign a device or a string.
See also
setDevice(), setString()
Definition at line 1027 of file qtextstream.cpp.
Referenced by qSetRealNumberPrecision().
     : d_ptr(new QTextStreamPrivate(this))
 {
 #if defined (QTEXTSTREAM_DEBUG)
     qDebug("QTextStream::QTextStream()");
 #endif
     Q_D(QTextStream);
     d->status = Ok;
 }
QTextStream() [2/6]
QTextStream::QTextStream (QIODevice * device) explicit
Constructs a QTextStream that operates on device.
Definition at line 1040 of file qtextstream.cpp.
     : d_ptr(new QTextStreamPrivate(this))
 {
 #if defined (QTEXTSTREAM_DEBUG)
     qDebug("QTextStream::QTextStream(QIODevice *device == *%p)",
            device);
 #endif
     Q_D(QTextStream);
     d->device = device;
 #ifndef QT_NO_QOBJECT
     d->deviceClosedNotifier.setupDevice(this, d->device);
 #endif
     d->status = Ok;
 }
QTextStream() [3/6]
QTextStream::QTextStream (FILE * fileHandle, QIODevice::OpenMode openMode = QIODevice::ReadWrite) explicit
Constructs a QTextStream that operates on fileHandle, using openMode to define the open mode.
Internally, a QFile is created to handle the FILE pointer.
This constructor is useful for working directly with the common FILE based input and output streams: stdin, stdout and stderr. Example:
QString str;
QTextStream in(stdin);
in >> str;
Definition at line 1135 of file qtextstream.cpp.
     : d_ptr(new QTextStreamPrivate(this))
 {
 #if defined (QTEXTSTREAM_DEBUG)
     qDebug("QTextStream::QTextStream(FILE *fileHandle = %p, openMode = %d)",
            fileHandle, int(openMode));
 #endif
     QFile *file = new QFile;
     file->open(fileHandle, openMode);
     Q_D(QTextStream);
     d->device = file;
     d->deleteDevice = true;
 #ifndef QT_NO_QOBJECT
     d->deviceClosedNotifier.setupDevice(this, d->device);
 #endif
     d->status = Ok;
 }
QTextStream() [4/6]
QTextStream::QTextStream (QString * string, QIODevice::OpenMode openMode = QIODevice::ReadWrite) explicit
Constructs a QTextStream that operates on string, using openMode to define the open mode.
Definition at line 1059 of file qtextstream.cpp.
     : d_ptr(new QTextStreamPrivate(this))
 {
 #if defined (QTEXTSTREAM_DEBUG)
     qDebug("QTextStream::QTextStream(QString *string == *%p, openMode = %d)",
            string, int(openMode));
 #endif
     Q_D(QTextStream);
     d->string = string;
     d->stringOpenMode = openMode;
     d->status = Ok;
 }
QTextStream() [5/6]
QTextStream::QTextStream (QByteArray * array, QIODevice::OpenMode openMode = QIODevice::ReadWrite) explicit
Constructs a QTextStream that operates on array, using openMode to define the open mode.
Internally, the array is wrapped by a QBuffer.
Definition at line 1077 of file qtextstream.cpp.
     : d_ptr(new QTextStreamPrivate(this))
 {
 #if defined (QTEXTSTREAM_DEBUG)
     qDebug("QTextStream::QTextStream(QByteArray *array == *%p, openMode = %d)",
            array, int(openMode));
 #endif
     Q_D(QTextStream);
     d->device = new QBuffer(array);
     d->device->open(openMode);
     d->deleteDevice = true;
 #ifndef QT_NO_QOBJECT
     d->deviceClosedNotifier.setupDevice(this, d->device);
 #endif
     d->status = Ok;
 }
QTextStream() [6/6]
QTextStream::QTextStream (const QByteArray & array, QIODevice::OpenMode openMode = QIODevice::ReadOnly) explicit
Constructs a QTextStream that operates on array, using openMode to define the open mode.
The array is accessed as read-only, regardless of the values in openMode.
This constructor is convenient for working on constant strings. Example:
int main(int argc, char *argv[])
{
    // read numeric arguments (123, 0x20, 4.5...)
    for (int i = 1; i < argc; ++i) {
          int number;
          QTextStream in(argv[i]);
          in >> number;
          ...
    }
}
Definition at line 1104 of file qtextstream.cpp.
     : d_ptr(new QTextStreamPrivate(this))
 {
 #if defined (QTEXTSTREAM_DEBUG)
     qDebug("QTextStream::QTextStream(const QByteArray &array == *(%p), openMode = %d)",
            &array, int(openMode));
 #endif
     QBuffer *buffer = new QBuffer;
     buffer->setData(array);
     buffer->open(openMode);
     Q_D(QTextStream);
     d->device = buffer;
     d->deleteDevice = true;
 #ifndef QT_NO_QOBJECT
     d->deviceClosedNotifier.setupDevice(this, d->device);
 #endif
     d->status = Ok;
 }
~QTextStream()
QTextStream::~QTextStream () virtual
Destroys the QTextStream.
If the stream operates on a device, flush() will be called implicitly. Otherwise, the device is unaffected.
Definition at line 1160 of file qtextstream.cpp.
Referenced by lowercasebase(), lowercasedigits(), noforcepoint(), noforcesign(), and noshowbase().
 {
     Q_D(QTextStream);
 #if defined (QTEXTSTREAM_DEBUG)
     qDebug("QTextStream::~QTextStream()");
 #endif
     if (!d->writeBuffer.isEmpty())
         d->flushWriteBuffer();
 }
Functions
atEnd()
bool QTextStream::atEnd () const
Returns true if there is no more data to be read from the QTextStream; otherwise returns false.
This is similar to, but not the same as calling QIODevice::atEnd(), as QTextStream also takes into account its internal Unicode buffer.
Definition at line 1646 of file qtextstream.cpp.
Referenced by QMacPasteboardMimeVCard::convertFromMime(), getLocations(), QGtkStylePrivate::getThemeName(), getVariables(), launchWebBrowser(), qt_parseQconfig(), readConf(), readSourceFile(), and trimmed().
 {
     Q_D(const QTextStream);
     CHECK_VALID_STREAM(true);
     if (d->string)
         return d->string->size() == d->stringOffset;
     return d->readBuffer.isEmpty() && d->device->atEnd();
 }
autoDetectUnicode()
bool QTextStream::autoDetectUnicode () const
Returns true if automatic Unicode detection is enabled, otherwise returns false.
Automatic Unicode detection is enabled by default.
See also
setAutoDetectUnicode(), setCodec()
Definition at line 3215 of file qtextstream.cpp.
 {
     Q_D(const QTextStream);
     return d->autoDetectUnicode;
 }
codec()
QTextCodec * QTextStream::codec () const
Returns the codec that is current assigned to the stream.
See also
setCodec(), setAutoDetectUnicode(), locale()
Definition at line 3186 of file qtextstream.cpp.
Referenced by encodeText(), QDomDocumentPrivate::saveDocument(), and setCodec().
 {
     Q_D(const QTextStream);
     return d->codec;
 }
device()
QIODevice * QTextStream::device () const
Returns the current device associated with the QTextStream, or 0 if no device has been assigned.
See also
setDevice(), string()
Definition at line 1352 of file qtextstream.cpp.
Referenced by QTextStream(), and setDevice().
 {
     Q_D(const QTextStream);
     return d->device;
 }
fieldAlignment()
QTextStream::FieldAlignment QTextStream::fieldAlignment () const
Returns the current field alignment.
See also
setFieldAlignment(), fieldWidth()
Definition at line 1415 of file qtextstream.cpp.
 {
     Q_D(const QTextStream);
     return d->fieldAlignment;
 }
fieldWidth()
int QTextStream::fieldWidth () const
Returns the current field width.
See also
setFieldWidth()
Definition at line 1476 of file qtextstream.cpp.
 {
     Q_D(const QTextStream);
     return d->fieldWidth;
 }
flush()
void QTextStream::flush ()
Flushes any buffered data waiting to be written to the device.
If QTextStream operates on a string, this function does nothing.
Definition at line 1193 of file qtextstream.cpp.
Referenced by QMacPasteboardMimeVCard::convertFromMime(), endl(), flush(), QDeviceClosedNotifier::flushStream(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::outputGraph(), setDevice(), and setString().
 {
     Q_D(QTextStream);
     d->flushWriteBuffer();
 }
generateByteOrderMark()
bool QTextStream::generateByteOrderMark () const
Returns true if QTextStream is set to generate the UTF BOM (Byte Order Mark) when using a UTF codec; otherwise returns false.
UTF BOM generation is set to false by default.
See also
setGenerateByteOrderMark()
Definition at line 3247 of file qtextstream.cpp.
 {
     Q_D(const QTextStream);
     return (d->writeConverterState.flags & QTextCodec::IgnoreHeader) == 0;
 }
integerBase()
int QTextStream::integerBase () const
Returns the current base of integers.
0 means that the base is detected when reading, or 10 (decimal) when generating numbers.
See also
setIntegerBase(), QString::number(), numberFlags()
Definition at line 1529 of file qtextstream.cpp.
Referenced by QTextStreamPrivate::getNumber(), and QTextStreamPrivate::putNumber().
 {
     Q_D(const QTextStream);
     return d->integerBase;
 }
locale()
QLocale QTextStream::locale () const
Returns the locale for this stream.
Since
4.5
The default locale is C.
See also
setLocale()
Definition at line 3285 of file qtextstream.cpp.
Referenced by QTextStreamPrivate::getNumber(), QTextStreamPrivate::getReal(), QTextStreamPrivate::putNumber(), and setLocale().
 {
     Q_D(const QTextStream);
     return d->locale;
 }
numberFlags()
QTextStream::NumberFlags QTextStream::numberFlags () const
Returns the current number flags.
See also
setNumberFlags(), integerBase(), realNumberNotation()
Definition at line 1501 of file qtextstream.cpp.
Referenced by forcepoint(), forcesign(), locale(), lowercasebase(), lowercasedigits(), noforcepoint(), noforcesign(), noshowbase(), operator<<(), QTextStreamPrivate::putNumber(), showbase(), uppercasebase(), and uppercasedigits().
 {
     Q_D(const QTextStream);
     return d->numberFlags;
 }
operator<<() [1/17]
QTextStream & QTextStream::operator<< (QBool b)
Warning
This function is not part of the public interface. This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2388 of file qtextstream.cpp.
 {
     return *this << bool(b);
 }
operator<<() [2/17]
QTextStream & QTextStream::operator<< (QChar c)
Writes the character c to the stream, then returns a reference to the QTextStream.
See also
setFieldWidth()
Definition at line 2399 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putString(QString(c));
     return *this;
 }
operator<<() [3/17]
QTextStream & QTextStream::operator<< (char c)
Converts c from ASCII to a QChar, then writes it to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2415 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putString(QString(QChar::fromAscii(c)));
     return *this;
 }
operator<<() [4/17]
QTextStream & QTextStream::operator<< (signed short i)
Writes the integer number i to the stream, then returns a reference to the QTextStream.
By default, the number is stored in decimal form, but you can also set the base by calling setIntegerBase().
See also
setFieldWidth(), setNumberFlags()
Definition at line 2431 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber((qulonglong)qAbs(qlonglong(i)), i < 0);
     return *this;
 }
operator<<() [5/17]
QTextStream & QTextStream::operator<< (unsigned short i)
Writes the unsigned short i to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2447 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber((qulonglong)i, false);
     return *this;
 }
operator<<() [6/17]
QTextStream & QTextStream::operator<< (signed int i)
Writes the signed int i to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2463 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber((qulonglong)qAbs(qlonglong(i)), i < 0);
     return *this;
 }
operator<<() [7/17]
QTextStream & QTextStream::operator<< (unsigned int i)
Writes the unsigned int i to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2479 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber((qulonglong)i, false);
     return *this;
 }
operator<<() [8/17]
QTextStream & QTextStream::operator<< (signed long i)
Writes the signed long i to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2495 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber((qulonglong)qAbs(qlonglong(i)), i < 0);
     return *this;
 }
operator<<() [9/17]
QTextStream & QTextStream::operator<< (unsigned long i)
Writes the unsigned long i to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2511 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber((qulonglong)i, false);
     return *this;
 }
operator<<() [10/17]
QTextStream & QTextStream::operator<< (qlonglong i)
Writes the qlonglong i to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2527 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber((qulonglong)qAbs(i), i < 0);
     return *this;
 }
operator<<() [11/17]
QTextStream & QTextStream::operator<< (qulonglong i)
Writes the qulonglong i to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2543 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putNumber(i, false);
     return *this;
 }
operator<<() [12/17]
QTextStream & QTextStream::operator<< (float f)
Writes the real number f to the stream, then returns a reference to the QTextStream.
By default, QTextStream stores it using SmartNotation, with up to 6 digits of precision. You can change the textual representation QTextStream will use for real numbers by calling setRealNumberNotation(), setRealNumberPrecision() and setNumberFlags().
See also
setFieldWidth(), setRealNumberNotation(), setRealNumberPrecision(), setNumberFlags()
Definition at line 2562 of file qtextstream.cpp.
 {
     return *this << double(f);
 }
operator<<() [13/17]
QTextStream & QTextStream::operator<< (double f)
Writes the double f to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2575 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     QLocalePrivate::DoubleForm form = QLocalePrivate::DFDecimal;
     switch (realNumberNotation()) {
     case FixedNotation:
         form = QLocalePrivate::DFDecimal;
         break;
     case ScientificNotation:
         form = QLocalePrivate::DFExponent;
         break;
     case SmartNotation:
         form = QLocalePrivate::DFSignificantDigits;
         break;
     }
     uint flags = 0;
     if (numberFlags() & ShowBase)
         flags |= QLocalePrivate::ShowBase;
     if (numberFlags() & ForceSign)
         flags |= QLocalePrivate::AlwaysShowSign;
     if (numberFlags() & UppercaseBase)
         flags |= QLocalePrivate::UppercaseBase;
     if (numberFlags() & UppercaseDigits)
         flags |= QLocalePrivate::CapitalEorX;
     if (numberFlags() & ForcePoint)
         flags |= QLocalePrivate::Alternate;
     const QLocalePrivate *dd = d->locale.d();
     QString num = dd->doubleToString(f, d->realNumberPrecision, form, -1, flags);
     d->putString(num, true);
     return *this;
 }
operator<<() [14/17]
QTextStream & QTextStream::operator<< (const QString & string)
Writes the string string to the stream, and returns a reference to the QTextStream.
The string is first encoded using the assigned codec (the default codec is QTextCodec::codecForLocale()) before it is written to the stream.
See also
setFieldWidth(), setCodec()
Definition at line 2619 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putString(string);
     return *this;
 }
operator<<() [15/17]
QTextStream & QTextStream::operator<< (const QByteArray & array)
Writes array to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The contents of array are converted with QString::fromAscii().
Definition at line 2636 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putString(QString::fromAscii(array.constData(), array.length()));
     return *this;
 }
operator<<() [16/17]
QTextStream & QTextStream::operator<< (const char * string)
Writes the constant string pointed to by string to the stream.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
string is assumed to be in ISO-8859-1 encoding. This operator is convenient when working with constant string data. Example:
QTextStream out(stdout);
out << "Qt rocks!" << endl;
Warning: QTextStream assumes that string points to a string of text, terminated by a '\0' character. If there is no terminating '\0' character, your application may crash.
Definition at line 2660 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->putString(QLatin1String(string));
     return *this;
 }
operator<<() [17/17]
QTextStream & QTextStream::operator<< (const void * ptr)
Writes ptr to the stream as a hexadecimal number with a base.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2677 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     int oldBase = d->integerBase;
     NumberFlags oldFlags = d->numberFlags;
     d->integerBase = 16;
     d->numberFlags |= ShowBase;
     d->putNumber(reinterpret_cast<quintptr>(ptr), false);
     d->integerBase = oldBase;
     d->numberFlags = oldFlags;
     return *this;
 }
operator>>() [1/15]
QTextStream & QTextStream::operator>> (QChar & c)
Reads a character from the stream and stores it in c.
Returns a reference to the QTextStream, so several operators can be nested. Example:
QTextStream in(file);
QChar ch1, ch2, ch3;
in >> ch1 >> ch2 >> ch3;
Whitespace is not skipped.
Definition at line 2061 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     d->scan(0, 0, 0, QTextStreamPrivate::NotSpace);
     if (!d->getChar(&c))
         setStatus(ReadPastEnd);
     return *this;
 }
operator>>() [2/15]
QTextStream & QTextStream::operator>> (char & c)
Reads a character from the stream and stores it in c.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The character from the stream is converted to ISO-5589-1 before it is stored.
See also
QChar::toLatin1()
Definition at line 2083 of file qtextstream.cpp.
 {
     QChar ch;
     *this >> ch;
     c = ch.toLatin1();
     return *this;
 }
operator>>() [3/15]
QTextStream & QTextStream::operator>> (signed short & i)
Reads an integer from the stream and stores it in i, then returns a reference to the QTextStream.
The number is cast to the correct type before it is stored. If no number was detected on the stream, i is set to 0.
By default, QTextStream will attempt to detect the base of the number using the following rules:
Prefix Base
"0b" or "0B" 2 (binary)
"0" followed by "0-7" 8 (octal)
"0" otherwise 10 (decimal)
"0x" or "0X" 16 (hexadecimal)
"1" to "9" 10 (decimal)
By calling setIntegerBase(), you can specify the integer base explicitly. This will disable the auto-detection, and speed up QTextStream slightly.
Leading whitespace is skipped.
Definition at line 2115 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(signed short);
 }
operator>>() [4/15]
QTextStream & QTextStream::operator>> (unsigned short & i)
Stores the integer in the unsigned short i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2128 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(unsigned short);
 }
operator>>() [5/15]
QTextStream & QTextStream::operator>> (signed int & i)
Stores the integer in the signed int i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2141 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(signed int);
 }
operator>>() [6/15]
QTextStream & QTextStream::operator>> (unsigned int & i)
Stores the integer in the unsigned int i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2154 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(unsigned int);
 }
operator>>() [7/15]
QTextStream & QTextStream::operator>> (signed long & i)
Stores the integer in the signed long i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2167 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(signed long);
 }
operator>>() [8/15]
QTextStream & QTextStream::operator>> (unsigned long & i)
Stores the integer in the unsigned long i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2180 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(unsigned long);
 }
operator>>() [9/15]
QTextStream & QTextStream::operator>> (qlonglong & i)
Stores the integer in the qlonglong i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2193 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(qlonglong);
 }
operator>>() [10/15]
QTextStream & QTextStream::operator>> (qulonglong & i)
Stores the integer in the qulonglong i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2206 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_INT_OPERATOR(qulonglong);
 }
operator>>() [11/15]
QTextStream & QTextStream::operator>> (float & f)
Reads a real number from the stream and stores it in f, then returns a reference to the QTextStream.
The number is cast to the correct type. If no real number is detect on the stream, f is set to 0.0.
As a special exception, QTextStream allows the strings "nan" and "inf" to represent NAN and INF floats or doubles.
Leading whitespace is skipped.
Definition at line 2222 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_REAL_OPERATOR(float);
 }
operator>>() [12/15]
QTextStream & QTextStream::operator>> (double & f)
Stores the real number in the double f.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 2235 of file qtextstream.cpp.
 {
     IMPLEMENT_STREAM_RIGHT_REAL_OPERATOR(double);
 }
operator>>() [13/15]
QTextStream & QTextStream::operator>> (QString & str)
Reads a word from the stream and stores it in str, then returns a reference to the stream.
Words are separated by whitespace (i.e., all characters for which QChar::isSpace() returns true).
Leading whitespace is skipped.
Definition at line 2247 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     str.clear();
     d->scan(0, 0, 0, QTextStreamPrivate::NotSpace);
     d->consumeLastToken();
     const QChar *ptr;
     int length;
     if (!d->scan(&ptr, &length, 0, QTextStreamPrivate::Space)) {
         setStatus(ReadPastEnd);
         return *this;
     }
     str = QString(ptr, length);
     d->consumeLastToken();
     return *this;
 }
operator>>() [14/15]
QTextStream & QTextStream::operator>> (QByteArray & array)
Converts the word to ISO-8859-1, then stores it in array.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
QString::toLatin1()
Definition at line 2278 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(*this);
     array.clear();
     d->scan(0, 0, 0, QTextStreamPrivate::NotSpace);
     d->consumeLastToken();
     const QChar *ptr;
     int length;
     if (!d->scan(&ptr, &length, 0, QTextStreamPrivate::Space)) {
         setStatus(ReadPastEnd);
         return *this;
     }
     for (int i = 0; i < length; ++i)
         array += ptr[i].toLatin1();
     d->consumeLastToken();
     return *this;
 }
operator>>() [15/15]
QTextStream & QTextStream::operator>> (char * c)
Stores the word in c, terminated by a '\0' character.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If no word is available, only the '\0' character is stored.
Warning: Although convenient, this operator is dangerous and must be used with care. QTextStream assumes that c points to a buffer with enough space to hold the word. If the buffer is too small, your application may crash.
If possible, use the QByteArray operator instead.
Definition at line 2317 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     *c = 0;
     CHECK_VALID_STREAM(*this);
     d->scan(0, 0, 0, QTextStreamPrivate::NotSpace);
     d->consumeLastToken();
     const QChar *ptr;
     int length;
     if (!d->scan(&ptr, &length, 0, QTextStreamPrivate::Space)) {
         setStatus(ReadPastEnd);
         return *this;
     }
     for (int i = 0; i < length; ++i)
         *c++ = ptr[i].toLatin1();
     *c = '\0';
     d->consumeLastToken();
     return *this;
 }
padChar()
QChar QTextStream::padChar () const
Returns the current pad character.
See also
setPadChar(), setFieldWidth()
Definition at line 1447 of file qtextstream.cpp.
 {
     Q_D(const QTextStream);
     return d->padChar;
 }
pos()
qint64 QTextStream::pos () const
Returns the device position corresponding to the current position of the stream, or -1 if an error occurs (e.
Since
4.2
g., if there is no device or string, or if there's a device error).
Because QTextStream is buffered, this function may have to seek the device to reconstruct a valid device position. This operation can be expensive, so you may want to avoid calling this function in a tight loop.
See also
seek()
Definition at line 1251 of file qtextstream.cpp.
Referenced by setCodec().
 {
     Q_D(const QTextStream);
     if (d->device) {
         // Cutoff
         if (d->readBuffer.isEmpty())
             return d->device->pos();
         if (d->device->isSequential())
             return 0;
         // Seek the device
         if (!d->device->seek(d->readBufferStartDevicePos))
             return qint64(-1);
         // Reset the read buffer
         QTextStreamPrivate *thatd = const_cast<QTextStreamPrivate *>(d);
         thatd->readBuffer.clear();
 #ifndef QT_NO_TEXTCODEC
         thatd->restoreToSavedConverterState();
         if (d->readBufferStartDevicePos == 0)
             thatd->autoDetectUnicode = true;
 #endif
         // Rewind the device to get to the current position Ensure that
         // readBufferOffset is unaffected by fillReadBuffer()
         int oldReadBufferOffset = d->readBufferOffset + d->readConverterSavedStateOffset;
         while (d->readBuffer.size() < oldReadBufferOffset) {
             if (!thatd->fillReadBuffer(1))
                 return qint64(-1);
         }
         thatd->readBufferOffset = oldReadBufferOffset;
         thatd->readConverterSavedStateOffset = 0;
         // Return the device position.
         return d->device->pos();
     }
     if (d->string)
         return d->stringOffset;
     qWarning("QTextStream::pos: no device");
     return qint64(-1);
 }
read()
QString QTextStream::read (qint64 maxlen)
Reads at most maxlen characters from the stream, and returns the data read as a QString.
Since
4.1
See also
readAll(), readLine(), QIODevice::read()
Definition at line 1718 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(QString());
     if (maxlen <= 0)
         return QString::fromLatin1("");     // empty, not null
     return d->read(int(maxlen));
 }
readAll()
QString QTextStream::readAll ()
Reads the entire content of the stream, and returns it as a QString.
Avoid this function when working on large files, as it will consume a significant amount of memory.
Calling readLine() is better if you do not know how much data is available.
See also
readLine()
Definition at line 1666 of file qtextstream.cpp.
Referenced by QScriptEngine::importExtension(), QCss::Parser::init(), QScriptDebuggerConsolePrivate::loadScriptedCommands(), operator<<(), and QDeclarativeScriptParser::parse().
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(QString());
     return d->read(INT_MAX);
 }
readLine()
QString QTextStream::readLine (qint64 maxlen = 0)
Reads one line of text from the stream, and returns it as a QString.
The maximum allowed line length is set to maxlen. If the stream contains lines longer than this, then the lines will be split after maxlen characters and returned in parts.
If maxlen is 0, the lines can be of any length. A common value for maxlen is 75.
The returned line has no trailing end-of-line characters ("\\n" or "\\r\\n"), so calling QString::trimmed() is unnecessary.
If the stream has read to the end of the file, readLine() will return a null QString. For strings, or for devices that support it, you can explicitly test for the end of the stream using atEnd().
See also
readAll(), QIODevice::readLine()
Definition at line 1692 of file qtextstream.cpp.
Referenced by QMacPasteboardMimeVCard::convertFromMime(), getLocations(), QGtkStylePrivate::getThemeName(), getVariables(), launchWebBrowser(), QSplitter::operator>>(), QDeclarativeDirParser::parse(), qt_parseQconfig(), readConf(), readSourceFile(), and trimmed().
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(QString());
     const QChar *readPtr;
     int length;
     if (!d->scan(&readPtr, &length, int(maxlen), QTextStreamPrivate::EndOfLine))
         return QString();
     QString tmp = QString(readPtr, length);
     d->consumeLastToken();
     return tmp;
 }
realNumberNotation()
QTextStream::RealNumberNotation QTextStream::realNumberNotation () const
Returns the current real number notation.
See also
setRealNumberNotation(), realNumberPrecision(), numberFlags(), integerBase()
Definition at line 1554 of file qtextstream.cpp.
Referenced by operator<<().
 {
     Q_D(const QTextStream);
     return d->realNumberNotation;
 }
realNumberPrecision()
int QTextStream::realNumberPrecision () const
Returns the current real number precision, or the number of fraction digits QTextStream will write when generating real numbers.
See also
setRealNumberNotation(), realNumberNotation(), numberFlags(), integerBase()
Definition at line 1586 of file qtextstream.cpp.
 {
     Q_D(const QTextStream);
     return d->realNumberPrecision;
 }
reset()
void QTextStream::reset ()
Resets QTextStream's formatting options, bringing it back to its original constructed state.
The device, string and any buffered data is left untouched.
Definition at line 1175 of file qtextstream.cpp.
Referenced by reset().
 {
     Q_D(QTextStream);
     d->realNumberPrecision = 6;
     d->integerBase = 0;
     d->fieldWidth = 0;
     d->padChar = QLatin1Char(' ');
     d->fieldAlignment = QTextStream::AlignRight;
     d->realNumberNotation = QTextStream::SmartNotation;
     d->numberFlags = 0;
 }
resetStatus()
void QTextStream::resetStatus ()
Resets the status of the text stream.
Since
4.1
See also
QTextStream::Status, status(), setStatus()
Definition at line 1614 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     d->status = Ok;
 }
seek()
bool QTextStream::seek (qint64 pos)
Seeks to the position pos in the device.
Returns true on success; otherwise returns false.
Definition at line 1203 of file qtextstream.cpp.
Referenced by setCodec().
 {
     Q_D(QTextStream);
     d->lastTokenSize = 0;
     if (d->device) {
         // Empty the write buffer
         d->flushWriteBuffer();
         if (!d->device->seek(pos))
             return false;
         d->resetReadBuffer();
 #ifndef QT_NO_TEXTCODEC
         // Reset the codec converter states.
         resetCodecConverterStateHelper(&d->readConverterState);
         resetCodecConverterStateHelper(&d->writeConverterState);
         delete d->readConverterSavedState;
         d->readConverterSavedState = 0;
         d->writeConverterState.flags |= QTextCodec::IgnoreHeader;
 #endif
         return true;
     }
     // string
     if (d->string && pos <= d->string->size()) {
         d->stringOffset = int(pos);
         return true;
     }
     return false;
 }
setAutoDetectUnicode()
void QTextStream::setAutoDetectUnicode (bool enabled)
If enabled is true, QTextStream will attempt to detect Unicode encoding by peeking into the stream data to see if it can find the UTF-16 or UTF-32 BOM (Byte Order Mark).
If this mark is found, QTextStream will replace the current codec with the UTF codec.
This function can be used together with setCodec(). It is common to set the codec to UTF-8, and then enable UTF-16 detection.
See also
autoDetectUnicode(), setCodec()
Definition at line 3203 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     d->autoDetectUnicode = enabled;
 }
setCodec() [1/2]
void QTextStream::setCodec (QTextCodec * codec)
Sets the codec for this stream to codec.
The codec is used for decoding any data that is read from the assigned device, and for encoding any data that is written. By default, QTextCodec::codecForLocale() is used, and automatic unicode detection is enabled.
If QTextStream operates on a string, this function does nothing.
Warning
If you call this function while the text stream is reading from an open sequential socket, the internal buffer may still contain text decoded using the old codec.
See also
codec(), setAutoDetectUnicode(), setLocale()
Definition at line 3148 of file qtextstream.cpp.
Referenced by locale(), operator<<(), QDeclarativeScriptParser::parse(), QDomDocumentPrivate::saveDocument(), setCodec(), and QTextDocumentWriter::write().
 {
     Q_D(QTextStream);
     qint64 seekPos = -1;
     if (!d->readBuffer.isEmpty()) {
         if (!d->device->isSequential()) {
             seekPos = pos();
         }
     }
     d->codec = codec;
     if (seekPos >=0 && !d->readBuffer.isEmpty())
         seek(seekPos);
 }
setCodec() [2/2]
void QTextStream::setCodec (const char * codecName)
Sets the codec for this stream to the QTextCodec for the encoding specified by codecName.
Common values for codecName include "ISO 8859-1", "UTF-8", and "UTF-16". If the encoding isn't recognized, nothing happens.
Example:
QTextStream out(&file);
out.setCodec("UTF-8");
See also
QTextCodec::codecForName(), setLocale()
Definition at line 3174 of file qtextstream.cpp.
 {
     QTextCodec *codec = QTextCodec::codecForName(codecName);
     if (codec)
         setCodec(codec);
 }
setDevice()
void QTextStream::setDevice (QIODevice * device)
Sets the current device to device.
If a device has already been assigned, QTextStream will call flush() before the old device is replaced.
Note
This function resets locale to the default locale ('C') and codec to the default codec, QTextCodec::codecForLocale().
See also
device(), setString()
Definition at line 1325 of file qtextstream.cpp.
Referenced by DumpIDL().
 {
     Q_D(QTextStream);
     flush();
     if (d->deleteDevice) {
 #ifndef QT_NO_QOBJECT
         d->deviceClosedNotifier.disconnect();
 #endif
         delete d->device;
         d->deleteDevice = false;
     }
     d->reset();
     d->status = Ok;
     d->device = device;
     d->resetReadBuffer();
 #ifndef QT_NO_QOBJECT
     d->deviceClosedNotifier.setupDevice(this, d->device);
 #endif
 }
setFieldAlignment()
void QTextStream::setFieldAlignment (FieldAlignment mode)
Sets the field alignment to mode.
When used together with setFieldWidth(), this function allows you to generate formatted output with text aligned to the left, to the right or center aligned.
See also
fieldAlignment(), setFieldWidth()
Definition at line 1404 of file qtextstream.cpp.
Referenced by center(), left(), locale(), and right().
 {
     Q_D(QTextStream);
     d->fieldAlignment = mode;
 }
setFieldWidth()
void QTextStream::setFieldWidth (int width)
Sets the current field width to width.
If width is 0 (the default), the field width is equal to the length of the generated text.
Note
The field width applies to every element appended to this stream after this function has been called (e.g., it also pads endl). This behavior is different from similar classes in the STL, where the field width only applies to the next element.
See also
fieldWidth(), setPadChar()
Definition at line 1465 of file qtextstream.cpp.
Referenced by qSetFieldWidth().
 {
     Q_D(QTextStream);
     d->fieldWidth = width;
 }
setGenerateByteOrderMark()
void QTextStream::setGenerateByteOrderMark (bool generate)
If generate is true and a UTF codec is used, QTextStream will insert the BOM (Byte Order Mark) before any data has been written to the device.
If generate is false, no BOM will be inserted. This function must be called before any data is written. Otherwise, it does nothing.
See also
generateByteOrderMark(), bom()
Definition at line 3229 of file qtextstream.cpp.
Referenced by bom().
 {
     Q_D(QTextStream);
     if (d->writeBuffer.isEmpty()) {
         if (generate)
             d->writeConverterState.flags &= ~QTextCodec::IgnoreHeader;
         else
             d->writeConverterState.flags |= QTextCodec::IgnoreHeader;
     }
 }
setIntegerBase()
void QTextStream::setIntegerBase (int base)
Sets the base of integers to base, both for reading and for generating numbers.
base can be either 2 (binary), 8 (octal), 10 (decimal) or 16 (hexadecimal). If base is 0, QTextStream will attempt to detect the base by inspecting the data on the stream. When generating numbers, QTextStream assumes base is 10 unless the base has been set explicitly.
See also
integerBase(), QString::number(), setNumberFlags()
Definition at line 1517 of file qtextstream.cpp.
Referenced by bin(), dec(), hex(), locale(), and oct().
 {
     Q_D(QTextStream);
     d->integerBase = base;
 }
setLocale()
void QTextStream::setLocale (const QLocale & locale)
Sets the locale for this stream to locale.
Since
4.5
The specified locale is used for conversions between numbers and their string representations.
The default locale is C and it is a special case - the thousands group separator is not used for backward compatibility reasons.
See also
locale()
Definition at line 3269 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     d->locale = locale;
 }
setNumberFlags()
void QTextStream::setNumberFlags (NumberFlags flags)
Sets the current number flags to flags.
flags is a set of flags from the NumberFlag enum, and describes options for formatting generated code (e.g., whether or not to always write the base or sign of a number).
See also
numberFlags(), setIntegerBase(), setRealNumberNotation()
Definition at line 1490 of file qtextstream.cpp.
Referenced by forcepoint(), forcesign(), locale(), lowercasebase(), lowercasedigits(), noforcepoint(), noforcesign(), noshowbase(), showbase(), uppercasebase(), and uppercasedigits().
 {
     Q_D(QTextStream);
     d->numberFlags = flags;
 }
setPadChar()
void QTextStream::setPadChar (QChar ch)
Sets the pad character to ch.
The default value is the ASCII space character (' '), or QChar(0x20). This character is used to fill in the space in fields when generating text.
Example:
QString s;
QTextStream out(&s);
out.setFieldWidth(10);
out.setFieldAlignment(QTextStream::AlignCenter);
out.setPadChar('-');
out << "Qt" << "rocks!";
The string s contains:
----Qt------rocks!--
See also
padChar(), setFieldWidth()
Definition at line 1436 of file qtextstream.cpp.
Referenced by qSetPadChar().
 {
     Q_D(QTextStream);
     d->padChar = ch;
 }
setRealNumberNotation()
void QTextStream::setRealNumberNotation (RealNumberNotation notation)
Sets the real number notation to notation (SmartNotation, FixedNotation, ScientificNotation).
When reading and generating numbers, QTextStream uses this value to detect the formatting of real numbers.
See also
realNumberNotation(), setRealNumberPrecision(), setNumberFlags(), setIntegerBase()
Definition at line 1543 of file qtextstream.cpp.
Referenced by fixed(), locale(), and scientific().
 {
     Q_D(QTextStream);
     d->realNumberNotation = notation;
 }
setRealNumberPrecision()
void QTextStream::setRealNumberPrecision (int precision)
Sets the precision of real numbers to precision.
This value describes the number of fraction digits QTextStream should write when generating real numbers.
The precision cannot be a negative value. The default value is 6.
See also
realNumberPrecision(), setRealNumberNotation()
Definition at line 1569 of file qtextstream.cpp.
Referenced by qSetRealNumberPrecision().
 {
     Q_D(QTextStream);
     if (precision < 0) {
         qWarning("QTextStream::setRealNumberPrecision: Invalid precision (%d)", precision);
         d->realNumberPrecision = 6;
         return;
     }
     d->realNumberPrecision = precision;
 }
setStatus()
void QTextStream::setStatus (Status status)
Sets the status of the text stream to the status given.
Since
4.1
Subsequent calls to setStatus() are ignored until resetStatus() is called.
See also
Status status() resetStatus()
Definition at line 1633 of file qtextstream.cpp.
Referenced by operator>>().
 {
     Q_D(QTextStream);
     if (d->status == Ok)
         d->status = status;
 }
setString()
void QTextStream::setString (QString * string, QIODevice::OpenMode openMode = QIODevice::ReadWrite)
Sets the current string to string, using the given openMode.
If a device has already been assigned, QTextStream will call flush() before replacing it.
See also
string(), setDevice()
Definition at line 1365 of file qtextstream.cpp.
 {
     Q_D(QTextStream);
     flush();
     if (d->deleteDevice) {
 #ifndef QT_NO_QOBJECT
         d->deviceClosedNotifier.disconnect();
         d->device->blockSignals(true);
 #endif
         delete d->device;
         d->deleteDevice = false;
     }
     d->reset();
     d->status = Ok;
     d->string = string;
     d->stringOpenMode = openMode;
 }
skipWhiteSpace()
void QTextStream::skipWhiteSpace ()
Reads and discards whitespace from the stream until either a non-space character is detected, or until atEnd() returns true.
This function is useful when reading a stream character by character.
Whitespace characters are all characters for which QChar::isSpace() returns true.
See also
operator>>()
Definition at line 1307 of file qtextstream.cpp.
Referenced by ws().
 {
     Q_D(QTextStream);
     CHECK_VALID_STREAM(Q_VOID);
     d->scan(0, 0, 0, QTextStreamPrivate::NotSpace);
     d->consumeLastToken();
 }
status()
QTextStream::Status QTextStream::status () const
Returns the status of the text stream.
See also
QTextStream::Status, setStatus(), resetStatus()
Definition at line 1598 of file qtextstream.cpp.
Referenced by QWSCalibratedMouseHandler::readCalibration(), setStatus(), and write_xpm_image().
 {
     Q_D(const QTextStream);
     return d->status;
 }
string()
QString * QTextStream::string () const
Returns the current string assigned to the QTextStream, or 0 if no string has been assigned.
See also
setString(), device()
Definition at line 1390 of file qtextstream.cpp.
Referenced by QTextStream(), seek(), and setString().
 {
     Q_D(const QTextStream);
     return d->string;
 }
Friends and Related Functions
bin()
QTextStream & bin (QTextStream & stream) related
Calls QTextStream::setIntegerBase(2) on stream and returns stream.
See also
oct(), dec(), hex(), {QTextStream manipulators}
Definition at line 2702 of file qtextstream.cpp.
Referenced by locale().
 {
     stream.setIntegerBase(2);
     return stream;
 }
bom()
QTextStream & bom (QTextStream & stream) related
Toggles insertion of the Byte Order Mark on stream when QTextStream is used with a UTF codec.
See also
QTextStream::setGenerateByteOrderMark(), {QTextStream manipulators}
Definition at line 3127 of file qtextstream.cpp.
 {
     stream.setGenerateByteOrderMark(true);
     return stream;
 }
center()
QTextStream & center (QTextStream & stream) related
Calls QTextStream::setFieldAlignment(QTextStream::AlignCenter) on stream and returns stream.
See also
left(), right(), {QTextStream manipulators}
Definition at line 3009 of file qtextstream.cpp.
Referenced by QTriangulator< T >::ComplexToSimple::Event::operator<(), QRect::QRect(), and QSplashScreen::setPixmap().
 {
     stream.setFieldAlignment(QTextStream::AlignCenter);
     return stream;
 }
dec()
QTextStream & dec (QTextStream & stream) related
Calls QTextStream::setIntegerBase(10) on stream and returns stream.
See also
bin(), oct(), hex(), {QTextStream manipulators}
Definition at line 2736 of file qtextstream.cpp.
Referenced by locale().
 {
     stream.setIntegerBase(10);
     return stream;
 }
endl()
QTextStream & endl (QTextStream & stream) related
Writes '
' to the stream and flushes the stream.
Equivalent to
stream << '\n' << flush;
Note: On Windows, all '
' characters are written as '
' if QTextStream's device or string is opened using the QIODevice::Text flag.
See also
flush(), reset(), {QTextStream manipulators}
Definition at line 3032 of file qtextstream.cpp.
Referenced by classIDL(), DumpIDL(), noegl(), and qax_generateDocumentation().
 {
     return stream << QLatin1Char('\n') << flush;
 }
fixed()
QTextStream & fixed (QTextStream & stream) related
Calls QTextStream::setRealNumberNotation(QTextStream::FixedNotation) on stream and returns stream.
See also
scientific(), {QTextStream manipulators}
Definition at line 2941 of file qtextstream.cpp.
Referenced by addFontToDatabase(), and locale().
 {
     stream.setRealNumberNotation(QTextStream::FixedNotation);
     return stream;
 }
flush()
QTextStream & flush (QTextStream & stream) related
Calls QTextStream::flush() on stream and returns stream.
See also
endl(), reset(), {QTextStream manipulators}
Definition at line 3047 of file qtextstream.cpp.
Referenced by QDirectFBWindowSurface::paintDevice().
 {
     stream.flush();
     return stream;
 }
forcepoint()
QTextStream & forcepoint (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::ForcePoint) on stream and returns stream.
See also
noforcepoint(), forcesign(), showbase(), {QTextStream manipulators}
Definition at line 2805 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() | QTextStream::ForcePoint);
     return stream;
 }
forcesign()
QTextStream & forcesign (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::ForceSign) on stream and returns stream.
See also
noforcesign(), forcepoint(), showbase(), {QTextStream manipulators}
Definition at line 2788 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() | QTextStream::ForceSign);
     return stream;
 }
hex()
QTextStream & hex (QTextStream & stream) related
Calls QTextStream::setIntegerBase(16) on stream and returns stream.
Note
The hex modifier can only be used for writing to streams.
See also
bin(), oct(), dec(), {QTextStream manipulators}
Definition at line 2754 of file qtextstream.cpp.
Referenced by initWritingSystems(), locale(), and verifyTag().
 {
     stream.setIntegerBase(16);
     return stream;
 }
left()
QTextStream & left (QTextStream & stream) related
Calls QTextStream::setFieldAlignment(QTextStream::AlignLeft) on stream and returns stream.
See also
right(), center(), {QTextStream manipulators}
Definition at line 2975 of file qtextstream.cpp.
Referenced by locale(), QRect::QRect(), and QWindowsMobileStyle::subControlRect().
 {
     stream.setFieldAlignment(QTextStream::AlignLeft);
     return stream;
 }
lowercasebase()
QTextStream & lowercasebase (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::UppercaseBase) on stream and returns stream.
See also
uppercasebase(), lowercasedigits(), {QTextStream manipulators}
Definition at line 2907 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() & ~QTextStream::UppercaseBase);
     return stream;
 }
lowercasedigits()
QTextStream & lowercasedigits (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::UppercaseDigits) on stream and returns stream.
See also
uppercasedigits(), lowercasebase(), {QTextStream manipulators}
Definition at line 2924 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() & ~QTextStream::UppercaseDigits);
     return stream;
 }
noforcepoint()
QTextStream & noforcepoint (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::ForcePoint) on stream and returns stream.
See also
forcepoint(), noforcesign(), noshowbase(), {QTextStream manipulators}
Definition at line 2856 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() &= ~QTextStream::ForcePoint);
     return stream;
 }
noforcesign()
QTextStream & noforcesign (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::ForceSign) on stream and returns stream.
See also
forcesign(), noforcepoint(), noshowbase(), {QTextStream manipulators}
Definition at line 2839 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() &= ~QTextStream::ForceSign);
     return stream;
 }
noshowbase()
QTextStream & noshowbase (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() & ~QTextStream::ShowBase) on stream and returns stream.
See also
showbase(), noforcesign(), noforcepoint(), {QTextStream manipulators}
Definition at line 2822 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() &= ~QTextStream::ShowBase);
     return stream;
 }
oct()
QTextStream & oct (QTextStream & stream) related
Calls QTextStream::setIntegerBase(8) on stream and returns stream.
See also
bin(), dec(), hex(), {QTextStream manipulators}
Definition at line 2719 of file qtextstream.cpp.
Referenced by locale().
 {
     stream.setIntegerBase(8);
     return stream;
 }
qSetFieldWidth()
QTextStreamManipulator qSetFieldWidth (int width) related
Equivalent to QTextStream::setFieldWidth(width).
Definition at line 329 of file qtextstream.h.
 {
     QTSMFI func = &QTextStream::setFieldWidth;
     return QTextStreamManipulator(func,width);
 }
qSetPadChar()
QTextStreamManipulator qSetPadChar (QChar ch) related
Equivalent to QTextStream::setPadChar(ch).
Definition at line 335 of file qtextstream.h.
 {
     QTSMFC func = &QTextStream::setPadChar;
     return QTextStreamManipulator(func, ch);
 }
qSetRealNumberPrecision()
QTextStreamManipulator qSetRealNumberPrecision (int precision) related
Equivalent to QTextStream::setRealNumberPrecision(precision).
Definition at line 341 of file qtextstream.h.
 {
     QTSMFI func = &QTextStream::setRealNumberPrecision;
     return QTextStreamManipulator(func, precision);
 }
reset()
QTextStream & reset (QTextStream & stream) related
Calls QTextStream::reset() on stream and returns stream.
See also
flush(), {QTextStream manipulators}
Definition at line 3063 of file qtextstream.cpp.
 {
     stream.reset();
     return stream;
 }
right()
QTextStream & right (QTextStream & stream) related
Calls QTextStream::setFieldAlignment(QTextStream::AlignRight) on stream and returns stream.
See also
left(), center(), {QTextStream manipulators}
Definition at line 2992 of file qtextstream.cpp.
Referenced by QPainterPath::computeBoundingRect(), locale(), and QRect::QRect().
 {
     stream.setFieldAlignment(QTextStream::AlignRight);
     return stream;
 }
scientific()
QTextStream & scientific (QTextStream & stream) related
Calls QTextStream::setRealNumberNotation(QTextStream::ScientificNotation) on stream and returns stream.
See also
fixed(), {QTextStream manipulators}
Definition at line 2958 of file qtextstream.cpp.
Referenced by locale().
 {
     stream.setRealNumberNotation(QTextStream::ScientificNotation);
     return stream;
 }
showbase()
QTextStream & showbase (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::ShowBase) on stream and returns stream.
See also
noshowbase(), forcesign(), forcepoint(), {QTextStream manipulators}
Definition at line 2771 of file qtextstream.cpp.
Referenced by locale().
 {
     stream.setNumberFlags(stream.numberFlags() | QTextStream::ShowBase);
     return stream;
 }
uppercasebase()
QTextStream & uppercasebase (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::UppercaseBase) on stream and returns stream.
See also
lowercasebase(), uppercasedigits(), {QTextStream manipulators}
Definition at line 2873 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() | QTextStream::UppercaseBase);
     return stream;
 }
uppercasedigits()
QTextStream & uppercasedigits (QTextStream & stream) related
Calls QTextStream::setNumberFlags(QTextStream::numberFlags() | QTextStream::UppercaseDigits) on stream and returns stream.
See also
lowercasedigits(), uppercasebase(), {QTextStream manipulators}
Definition at line 2890 of file qtextstream.cpp.
 {
     stream.setNumberFlags(stream.numberFlags() | QTextStream::UppercaseDigits);
     return stream;
 }
ws()
QTextStream & ws (QTextStream & stream) related
Calls skipWhiteSpace() on stream and returns stream.
See also
{QTextStream manipulators}
Definition at line 3079 of file qtextstream.cpp.
 {
     stream.skipWhiteSpace();
     return stream;
 }
Properties
d_ptr
QScopedPointer<QTextStreamPrivate> QTextStream::d_ptr private
Definition at line 261 of file qtextstream.h.
The documentation for this class was generated from the following files:
/src/corelib/io/qtextstream.h
/src/corelib/io/qtextstream.cpp