Qt 4.8: QPatternist::Numeric Class Reference
QPatternist::Numeric Class Reference abstract
Base class for all numeric values.
#include <qschemanumeric_p.h>
Public Types
typedef QExplicitlySharedDataPointer< Numeric > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual Numeric::Ptr abs () const =0
virtual Numeric::Ptr ceiling () const =0
virtual Numeric::Ptr floor () const =0
virtual bool isInf () const =0
virtual bool isNaN () const =0
virtual bool isSigned () const =0
Returns true if this value is signed. If false is returned, the value is unsigned.
virtual Numeric::Ptr round () const =0
virtual Numeric::Ptr roundHalfToEven (const xsInteger scale) const =0
virtual xsFloat toDecimal () const =0
virtual xsDouble toDouble () const =0
virtual xsFloat toFloat () const =0
virtual xsInteger toInteger () const =0
virtual Item toNegated () const =0
virtual qulonglong toUnsignedInteger () const =0
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual QString stringValue () const =0
virtual ItemType::Ptr type () const =0
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr fromLexical (const QString &number)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Static Protected Functions
static xsDouble roundFloat (const xsDouble val)
Implements fn:round() for types implemented with floating point.
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Detailed Description
Base class for all numeric values.
Creating Instances
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6 Functions and Operators on Numerics
XQuery 1.0 and XPath 2.0 Functions and Operators, 1.2 Function Overloading
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 90 of file qschemanumeric_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<Numeric> QPatternist::Numeric::Ptr
Definition at line 94 of file qschemanumeric_p.h.
Functions
abs()
virtual Numeric::Ptr QPatternist::Numeric::abs () const pure virtual
Performs the algorithm specified for the function fn:abs on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.1 fn:abs
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::AbsFN::evaluateSingleton().
ceiling()
virtual Numeric::Ptr QPatternist::Numeric::ceiling () const pure virtual
Performs the algorithm specified for the function fn:ceiling on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.2 fn:ceiling
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::CeilingFN::evaluateSingleton().
floor()
virtual Numeric::Ptr QPatternist::Numeric::floor () const pure virtual
Performs the algorithm specified for the function fn:floor on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.3 fn:floor
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::FloorFN::evaluateSingleton().
fromLexical()
AtomicValue::Ptr Numeric::fromLexical (const QString & number) static
Creates a Numeric sub-class that is appropriate for number.
Note
usages of e/E is not handled; Double::fromLexical should be used in that case. There is no function similar to fromLexical that also takes double values into account(because that distinction is done in the scanner).
Currently used in the parser to create appropriate expressions.
Definition at line 62 of file qschemanumeric.cpp.
 {
     Q_ASSERT(!number.isEmpty());
     Q_ASSERT_X(!number.contains(QLatin1Char('e')) &&
                !number.contains(QLatin1Char('E')),
                Q_FUNC_INFO, "Should not contain any e/E");
     if(number.contains(QLatin1Char('.'))) /* an xs:decimal. */
         return Decimal::fromLexical(number);
     else /* It's an integer, of some sort. E.g, -3, -2, -1, 0, 1, 2, 3 */
         return Integer::fromLexical(number);
 }
isInf()
virtual bool QPatternist::Numeric::isInf () const pure virtual
Determines whether this Numeric is an infinite number. Signedness is irrelevant, -INF as well as INF is considered infinity.
For numeric types that cannot represent infinity, such as xs:integer , this function should return false.
Returns
true if this Numeric is an infinite number
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::Decimal, QPatternist::AbstractFloat< isDouble >, and QPatternist::Integer.
Referenced by QPatternist::AbstractFloatMathematician< isDouble >::calculate().
isNaN()
virtual bool QPatternist::Numeric::isNaN () const pure virtual
Determines whether this Numeric is not-a-number, NaN. For numeric types that cannot represent NaN, this function should return false.
Returns
true if this Numeric is NaN
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::AbstractFloatMathematician< isDouble >::calculate(), and qLess< Item::List >::isNaN().
isSigned()
virtual bool QPatternist::Numeric::isSigned () const pure virtual
Returns true if this value is signed. If false is returned, the value is unsigned.
For float and decimal values, xs:double, xs:float and xs:decimal, the code asserts and behavior is undefined.
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::Decimal, QPatternist::AbstractFloat< isDouble >, and QPatternist::Integer.
Referenced by QPatternist::IntegerComparator::compare().
round()
virtual Numeric::Ptr QPatternist::Numeric::round () const pure virtual
Performs the algorithm specified for the function fn:round on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.4 fn:round
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::RoundFN::evaluateSingleton().
roundFloat()
xsDouble Numeric::roundFloat (const xsDouble val) static protected
Implements fn:round() for types implemented with floating point.
MS Windows and at least IRIX does not have C99's nearbyint() function(see the man page), so we reinvent it.
Definition at line 75 of file qschemanumeric.cpp.
Referenced by QPatternist::Decimal::round(), and QPatternist::AbstractFloat< isDouble >::round().
 {
     if(qIsInf(val) || AbstractFloat<true>::isEqual(val, 0.0))
         return val;
     else if(qIsNaN(val))
         return val;
     else
     {
         if(val >= -0.5 && val < 0)
             return -0.0;
         else
             return ::floor(val + 0.5);
     }
 }
roundHalfToEven()
virtual Numeric::Ptr QPatternist::Numeric::roundHalfToEven (const xsInteger scale) const pure virtual
Performs rounding as defined for the fn:round-half-to-even on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.5 fn:round-half-to-even
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::RoundHalfToEvenFN::evaluateSingleton().
toDecimal()
virtual xsFloat QPatternist::Numeric::toDecimal () const pure virtual
Returns
the particular number's value as a native representation of the type xs:decimal. This can be considered that the value is cast to xs:decimal.
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::ComparingAggregator< oper, result >::applyNumericPromotion(), QPatternist::DecimalMathematician::calculate(), QPatternist::IntegerMathematician::calculate(), and QPatternist::DecimalComparator::equals().
toDouble()
virtual xsDouble QPatternist::Numeric::toDouble () const pure virtual
Returns
the particular number's value as a native representation of the type xs:double. This can be considered that the value is cast to xs:double.
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::ComparingAggregator< oper, result >::applyNumericPromotion(), QPatternist::AbstractFloatMathematician< isDouble >::calculate(), QPatternist::XsdTypeChecker::checkConstrainingFacets(), QPatternist::AbstractFloatComparator::equals(), QPatternist::SubstringFN::evaluateSingleton(), QPatternist::GenericPredicate::mapToItem(), and QPatternist::AtomicValue::toQt().
toFloat()
virtual xsFloat QPatternist::Numeric::toFloat () const pure virtual
Returns
the particular number's value as a native representation of the type xs:float. This can be considered that the value is cast to xs:float.
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
toInteger()
virtual xsInteger QPatternist::Numeric::toInteger () const pure virtual
Returns
the particular number's value as a native representation of the type xs:integer. This can be considered that the value is cast to xs:integer.
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::DecimalMathematician::calculate(), QPatternist::IntegerMathematician::calculate(), QPatternist::XsdTypeChecker::checkConstrainingFacets(), QPatternist::SubsequenceFN::compress(), QPatternist::SubsequenceFN::evaluateSequence(), QPatternist::SubsequenceFN::staticType(), and QPatternist::AtomicValue::toQt().
toNegated()
virtual Item QPatternist::Numeric::toNegated () const pure virtual
Unary minus.
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::Decimal, QPatternist::AbstractFloat< isDouble >, and QPatternist::Integer.
toUnsignedInteger()
virtual qulonglong QPatternist::Numeric::toUnsignedInteger () const pure virtual
Returns
the number as an unsigned integer. If the value is not unsigned, the code asserts and behavior is undefined.
Implemented in QPatternist::DerivedInteger< DerivedType >, QPatternist::AbstractFloat< isDouble >, QPatternist::Decimal, and QPatternist::Integer.
Referenced by QPatternist::XsdTypeChecker::checkConstrainingFacets().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qschemanumeric_p.h
/src/xmlpatterns/data/qschemanumeric.cpp