Qt 4.8: QJSDebugService Class Reference
QJSDebugService Class Reference
#include <qjsdebugservice_p.h>
Public Functions
void addEngine (QDeclarativeEngine *)
void processMessage (const JSAgentCoverageData &message)
QJSDebugService (QObject *parent=0)
void removeEngine (QDeclarativeEngine *)
~QJSDebugService ()
Public Functions inherited from QDeclarativeDebugService
QString name () const
QDeclarativeDebugService (const QString &, QObject *parent=0)
void sendMessage (const QByteArray &)
Status status () const
bool waitForMessage ()
~QDeclarativeDebugService ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QJSDebugService * instance ()
Static Public Functions inherited from QDeclarativeDebugService
static bool hasDebuggingClient ()
static int idForObject (QObject *)
Returns a unique id for object.
static bool isDebuggingEnabled ()
static QObject * objectForId (int)
Returns the object for unique id.
static QString objectToString (QObject *obj)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
QElapsedTimer m_timer
Protected Functions
void messageReceived (const QByteArray &)
void statusChanged (Status status)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void executionStopped (bool becauseOfException, const QString &exception)
Private Functions
void sendMessages ()
Properties
QPointer< QJSDebuggerAgent > m_agent
QList< JSAgentCoverageData > m_data
bool m_deferredSend
QList< QDeclarativeEngine * > m_engines
Additional Inherited Members
Public Types inherited from QDeclarativeDebugService
enum Status { NotConnected, Unavailable, Enabled }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 87 of file qjsdebugservice_p.h.
Constructors and Destructors
QJSDebugService()
QJSDebugService::QJSDebugService (QObject * parent = 0)
Definition at line 63 of file qjsdebugservice.cpp.
     : QDeclarativeDebugService(QLatin1String("JSDebugger"), parent)
     , m_agent(0), m_deferredSend(true)
 {
     m_timer.start();
 }
~QJSDebugService()
QJSDebugService::~QJSDebugService ()
Definition at line 70 of file qjsdebugservice.cpp.
 {
     delete m_agent;
 }
Functions
addEngine()
void QJSDebugService::addEngine (QDeclarativeEngine * engine)
Definition at line 80 of file qjsdebugservice.cpp.
Referenced by QDeclarativeEnginePrivate::init().
 {
     Q_ASSERT(engine);
     Q_ASSERT(!m_engines.contains(engine));
     m_engines.append(engine);
     if (status() == Enabled && !m_engines.isEmpty() && !m_agent) {
         m_agent = new QJSDebuggerAgent(engine, engine);
         connect(m_agent, SIGNAL(stopped(bool,QString)),
                 this, SLOT(executionStopped(bool,QString)));
         while (!m_agent->isInitialized()) {
             waitForMessage();
         }
     }
 }
executionStopped
void QJSDebugService::executionStopped (bool becauseOfException, const QString & exception) private slot
Definition at line 215 of file qjsdebugservice.cpp.
Referenced by addEngine(), and statusChanged().
 {
     const QList<JSAgentStackData> backtrace = m_agent->backtrace();
     const QList<JSAgentWatchData> watches = m_agent->watches();
     const QList<JSAgentWatchData> locals = m_agent->locals();
     QByteArray reply;
     QDataStream rs(&reply, QIODevice::WriteOnly);
     rs << QByteArray("STOPPED") << backtrace << watches << locals
        << becauseOfException << exception;
     sendMessage(reply);
 }
instance()
QJSDebugService * QJSDebugService::instance () static
Definition at line 75 of file qjsdebugservice.cpp.
Referenced by QJSDebuggerAgent::functionEntry(), QJSDebuggerAgent::functionExit(), QDeclarativeEnginePrivate::init(), QJSDebuggerAgent::positionChange(), QJSDebuggerAgent::scriptLoad(), and QDeclarativeEngine::~QDeclarativeEngine().
 {
     return serviceInstance();
 }
messageReceived()
void QJSDebugService::messageReceived (const QByteArray & message) protected virtual
Reimplemented from QDeclarativeDebugService.
Definition at line 122 of file qjsdebugservice.cpp.
 {
     if (!m_agent) {
         qWarning() << "QJSDebugService::messageReceived: No QJSDebuggerAgent available";
         return;
     }
     QDataStream ds(message);
     QByteArray command;
     ds >> command;
     if (command == "BREAKPOINTS") {
         JSAgentBreakpoints breakpoints;
         ds >> breakpoints;
         m_agent->setBreakpoints(breakpoints);
         //qDebug() << "BREAKPOINTS";
         //foreach (const JSAgentBreakpointData &bp, breakpoints)
         //    qDebug() << "BREAKPOINT: " << bp.fileUrl << bp.lineNumber;
     } else if (command == "WATCH_EXPRESSIONS") {
         QStringList watchExpressions;
         ds >> watchExpressions;
         m_agent->setWatchExpressions(watchExpressions);
     } else if (command == "STEPOVER") {
         m_agent->stepOver();
     } else if (command == "STEPINTO" || command == "INTERRUPT") {
         m_agent->stepInto();
     } else if (command == "STEPOUT") {
         m_agent->stepOut();
     } else if (command == "CONTINUE") {
         m_agent->continueExecution();
     } else if (command == "EXEC") {
         QByteArray id;
         QString expr;
         ds >> id >> expr;
         JSAgentWatchData data = m_agent->executeExpression(expr);
         QByteArray reply;
         QDataStream rs(&reply, QIODevice::WriteOnly);
         rs << QByteArray("RESULT") << id << data;
         sendMessage(reply);
     } else if (command == "EXPAND") {
         QByteArray requestId;
         quint64 objectId;
         ds >> requestId >> objectId;
         QList<JSAgentWatchData> result = m_agent->expandObjectById(objectId);
         QByteArray reply;
         QDataStream rs(&reply, QIODevice::WriteOnly);
         rs << QByteArray("EXPANDED") << requestId << result;
         sendMessage(reply);
     } else if (command == "ACTIVATE_FRAME") {
         int frameId;
         ds >> frameId;
         QList<JSAgentWatchData> locals = m_agent->localsAtFrame(frameId);
         QByteArray reply;
         QDataStream rs(&reply, QIODevice::WriteOnly);
         rs << QByteArray("LOCALS") << frameId << locals;
         sendMessage(reply);
     } else if (command == "SET_PROPERTY") {
         QByteArray id;
         qint64 objectId;
         QString property;
         QString value;
         ds >> id >> objectId >> property >> value;
         m_agent->setProperty(objectId, property, value);
         //TODO: feedback
     } else if (command == "PING") {
         int ping;
         ds >> ping;
         QByteArray reply;
         QDataStream rs(&reply, QIODevice::WriteOnly);
         rs << QByteArray("PONG") << ping;
         sendMessage(reply);
     } else if (command == "COVERAGE") {
         bool enabled;
         ds >> enabled;
         m_agent->setCoverageEnabled(enabled);
         if (!enabled) {
             sendMessages();
         }
     } else {
         qDebug() << Q_FUNC_INFO << "Unknown command" << command;
     }
     QDeclarativeDebugService::messageReceived(message);
 }
processMessage()
void QJSDebugService::processMessage (const JSAgentCoverageData & message)
Definition at line 233 of file qjsdebugservice.cpp.
Referenced by QJSDebuggerAgent::functionEntry(), QJSDebuggerAgent::functionExit(), QJSDebuggerAgent::positionChange(), and QJSDebuggerAgent::scriptLoad().
 {
     if (m_deferredSend)
         m_data.append(message);
     else
         sendMessage(message.toByteArray());
 }
removeEngine()
void QJSDebugService::removeEngine (QDeclarativeEngine * engine)
Definition at line 98 of file qjsdebugservice.cpp.
Referenced by QDeclarativeEngine::~QDeclarativeEngine().
 {
     Q_ASSERT(engine);
     Q_ASSERT(m_engines.contains(engine));
     m_engines.removeAll(engine);
 }
sendMessages()
void QJSDebugService::sendMessages () private
Definition at line 244 of file qjsdebugservice.cpp.
Referenced by messageReceived().
 {
     if (m_deferredSend) {
         //### this is a suboptimal way to send batched messages
         for (int i = 0; i < m_data.count(); ++i)
             sendMessage(m_data.at(i).toByteArray());
         m_data.clear();
         //indicate completion
         QByteArray data;
         QDataStream ds(&data, QIODevice::WriteOnly);
         ds << QByteArray("COVERAGE") << (qint64)-1 << (int)CoverageComplete;
         sendMessage(data);
     }
 }
statusChanged()
void QJSDebugService::statusChanged (Status status) protected virtual
Reimplemented from QDeclarativeDebugService.
Definition at line 106 of file qjsdebugservice.cpp.
 {
     if (status == Enabled && !m_engines.isEmpty() && !m_agent) {
         // Multiple engines are currently unsupported
         QDeclarativeEngine *engine = m_engines.first();
         m_agent = new QJSDebuggerAgent(engine, engine);
         connect(m_agent, SIGNAL(stopped(bool,QString)),
                 this, SLOT(executionStopped(bool,QString)));
     } else if (status != Enabled && m_agent) {
         delete m_agent;
         m_agent = 0;
     }
 }
Properties
m_agent
QPointer<QJSDebuggerAgent> QJSDebugService::m_agent private
Definition at line 114 of file qjsdebugservice_p.h.
Referenced by addEngine(), executionStopped(), messageReceived(), statusChanged(), and ~QJSDebugService().
m_data
QList<JSAgentCoverageData> QJSDebugService::m_data private
Definition at line 116 of file qjsdebugservice_p.h.
Referenced by processMessage(), and sendMessages().
m_deferredSend
bool QJSDebugService::m_deferredSend private
Definition at line 115 of file qjsdebugservice_p.h.
Referenced by processMessage(), and sendMessages().
m_engines
QList<QDeclarativeEngine *> QJSDebugService::m_engines private
Definition at line 113 of file qjsdebugservice_p.h.
Referenced by addEngine(), removeEngine(), and statusChanged().
m_timer
QElapsedTimer QJSDebugService::m_timer
Definition at line 101 of file qjsdebugservice_p.h.
Referenced by QJSDebuggerAgent::functionEntry(), QJSDebuggerAgent::functionExit(), QJSDebuggerAgent::positionChange(), QJSDebugService(), and QJSDebuggerAgent::scriptLoad().
The documentation for this class was generated from the following files:
/src/declarative/debugger/qjsdebugservice_p.h
/src/declarative/debugger/qjsdebugservice.cpp