Qt 4.8: Graph< Vertex, EdgeData > Class Template Reference
Graph< Vertex, EdgeData > Class Template Reference
#include <qgraph_p.h>
Classes
class const_iterator
Public Functions
QList< Vertex * > adjacentVertices (Vertex *vertex) const
QList< QPair< Vertex *, Vertex * > > connections () const
const_iterator constBegin () const
const_iterator constEnd () const
void createEdge (Vertex *first, Vertex *second, EdgeData *data)
EdgeData * edgeData (Vertex *first, Vertex *second)
Graph ()
void removeEdge (Vertex *first, Vertex *second)
QString serializeToDot ()
EdgeData * takeEdge (Vertex *first, Vertex *second)
QSet< Vertex * > vertices () const
Protected Functions
void createDirectedEdge (Vertex *from, Vertex *to, EdgeData *data)
void removeDirectedEdge (Vertex *from, Vertex *to)
Properties
QHash< Vertex *, QHash< Vertex *, EdgeData * > * > m_graph
Detailed Description
template<typename Vertex, typename EdgeData>
class Graph< Vertex, EdgeData >
Definition at line 66 of file qgraph_p.h.
Constructors and Destructors
Graph()
template<typename Vertex, typename EdgeData> Graph< Vertex, EdgeData >::Graph () inline
Definition at line 69 of file qgraph_p.h.
 {}
Functions
adjacentVertices()
template<typename Vertex, typename EdgeData> QList<Vertex *> Graph< Vertex, EdgeData >::adjacentVertices (Vertex * vertex) const inline
Definition at line 195 of file qgraph_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QGraphicsAnchorLayoutPrivate::removeCenterAnchors(), QGraphicsAnchorLayoutPrivate::removeVertex(), QGraphicsAnchorLayoutPrivate::restoreVertices(), Graph< AnchorVertex, AnchorData >::serializeToDot(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), and QGraphicsAnchorLayoutPrivate::simplifyVertices().
     {
         QHash<Vertex *, EdgeData *> *row = m_graph.value(vertex);
         QList<Vertex *> l;
         if (row)
             l = row->keys();
         return l;
     }
connections()
template<typename Vertex, typename EdgeData> QList<QPair<Vertex*, Vertex*> > Graph< Vertex, EdgeData >::connections () const inline
Definition at line 212 of file qgraph_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::refreshAllSizeHints(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedGraph(), and QGraphicsAnchorLayoutPrivate::updateAnchorSizes().
{
         QList<QPair<Vertex*, Vertex*> > conns;
         for (const_iterator it = constBegin(); it != constEnd(); ++it) {
             Vertex *from = it.from();
             Vertex *to = it.to();
             // do not return (from,to) *and* (to,from)
             if (from < to) {
                 conns.append(qMakePair(from, to));
             }
         }
         return conns;
     }
constBegin()
template<typename Vertex, typename EdgeData> const_iterator Graph< Vertex, EdgeData >::constBegin () const inline
Definition at line 128 of file qgraph_p.h.
Referenced by Graph< AnchorVertex, AnchorData >::connections(), and Graph< AnchorVertex, AnchorData >::vertices().
{
         return const_iterator(this,true);
     }
constEnd()
template<typename Vertex, typename EdgeData> const_iterator Graph< Vertex, EdgeData >::constEnd () const inline
Definition at line 132 of file qgraph_p.h.
Referenced by Graph< AnchorVertex, AnchorData >::connections(), and Graph< AnchorVertex, AnchorData >::vertices().
{
         return const_iterator(this,false);
     }
createDirectedEdge()
template<typename Vertex, typename EdgeData> void Graph< Vertex, EdgeData >::createDirectedEdge (Vertex * from, Vertex * to, EdgeData * data) inline protected
Definition at line 257 of file qgraph_p.h.
Referenced by Graph< AnchorVertex, AnchorData >::createEdge().
     {
         QHash<Vertex *, EdgeData *> *adjacentToFirst = m_graph.value(from);
         if (!adjacentToFirst) {
             adjacentToFirst = new QHash<Vertex *, EdgeData *>();
             m_graph.insert(from, adjacentToFirst);
         }
         adjacentToFirst->insert(to, data);
     }
createEdge()
template<typename Vertex, typename EdgeData> void Graph< Vertex, EdgeData >::createEdge (Vertex * first, Vertex * second, EdgeData * data) inline
Definition at line 148 of file qgraph_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::addAnchor_helper(), QGraphicsAnchorLayoutPrivate::addAnchorMaybeParallel(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedAnchor(), and QGraphicsAnchorLayoutPrivate::restoreVertices().
     {
         // Creates a bidirectional edge
 #if defined(QT_DEBUG) && 0
         qDebug("Graph::createEdge(): %s",
                qPrintable(QString::fromAscii("%1-%2")
                           .arg(first->toString()).arg(second->toString())));
 #endif
         if (edgeData(first, second)) {
 #ifdef QT_DEBUG
             qWarning("%s-%s already has an edge", qPrintable(first->toString()), qPrintable(second->toString()));
 #endif
         }
         createDirectedEdge(first, second, data);
         createDirectedEdge(second, first, data);
     }
edgeData()
template<typename Vertex, typename EdgeData> EdgeData* Graph< Vertex, EdgeData >::edgeData (Vertex * first, Vertex * second) inline
Warning
This function is not part of the public interface.
If there is an edge between first and second, it will return a structure containing the data associated with the edge, otherwise it will return 0.
Definition at line 143 of file qgraph_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::calculateVertexPositions(), QGraphicsAnchorLayoutPrivate::constraintsFromSizeHints(), Graph< AnchorVertex, AnchorData >::createEdge(), QGraphicsAnchorLayoutPrivate::findPaths(), QGraphicsAnchorLayoutPrivate::getAnchor(), QGraphicsAnchorLayoutPrivate::getGraphParts(), QGraphicsAnchorLayoutPrivate::refreshAllSizeHints(), QGraphicsAnchorLayoutPrivate::removeCenterAnchors(), QGraphicsAnchorLayoutPrivate::removeCenterConstraints(), Graph< AnchorVertex, AnchorData >::removeEdge(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedGraph(), Graph< AnchorVertex, AnchorData >::serializeToDot(), QGraphicsAnchorLayoutPrivate::simplifyGraphIteration(), QGraphicsAnchorLayoutPrivate::simplifyVertices(), Graph< AnchorVertex, AnchorData >::takeEdge(), and QGraphicsAnchorLayoutPrivate::updateAnchorSizes().
{
         QHash<Vertex *, EdgeData *> *row = m_graph.value(first);
         return row ? row->value(second) : 0;
     }
removeDirectedEdge()
template<typename Vertex, typename EdgeData> void Graph< Vertex, EdgeData >::removeDirectedEdge (Vertex * from, Vertex * to) inline protected
Definition at line 267 of file qgraph_p.h.
Referenced by Graph< AnchorVertex, AnchorData >::removeEdge(), and Graph< AnchorVertex, AnchorData >::takeEdge().
     {
         QHash<Vertex *, EdgeData *> *adjacentToFirst = m_graph.value(from);
         Q_ASSERT(adjacentToFirst);
         adjacentToFirst->remove(to);
         if (adjacentToFirst->isEmpty()) {
             //nobody point to 'from' so we can remove it from the graph
             m_graph.remove(from);
             delete adjacentToFirst;
         }
     }
removeEdge()
template<typename Vertex, typename EdgeData> void Graph< Vertex, EdgeData >::removeEdge (Vertex * first, Vertex * second) inline
Definition at line 165 of file qgraph_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::removeAnchor_helper(), and QGraphicsAnchorLayoutPrivate::removeVertex().
     {
         // Removes a bidirectional edge
 #if defined(QT_DEBUG) && 0
         qDebug("Graph::removeEdge(): %s",
                qPrintable(QString::fromAscii("%1-%2")
                           .arg(first->toString()).arg(second->toString())));
 #endif
         EdgeData *data = edgeData(first, second);
         removeDirectedEdge(first, second);
         removeDirectedEdge(second, first);
         if (data) delete data;
     }
serializeToDot()
template<typename Vertex, typename EdgeData> QString Graph< Vertex, EdgeData >::serializeToDot () inline
Definition at line 226 of file qgraph_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::dumpGraph().
                              {   // traversal
         QString strVertices;
         QString edges;
         QSet<Vertex *> setOfVertices = vertices();
         for (Q_TYPENAME QSet<Vertex*>::const_iterator it = setOfVertices.begin(); it != setOfVertices.end(); ++it) {
             Vertex *v = *it;
             QList<Vertex*> adjacents = adjacentVertices(v);
             for (int i = 0; i < adjacents.count(); ++i) {
                 Vertex *v1 = adjacents.at(i);
                 EdgeData *data = edgeData(v, v1);
                 bool forward = data->from == v;
                 if (forward) {
                     edges += QString::fromAscii("\"%1\"->\"%2\" [label=\"[%3,%4,%5,%6,%7]\" color=\"#000000\"] \n")
                         .arg(v->toString())
                         .arg(v1->toString())
                         .arg(data->minSize)
                         .arg(data->minPrefSize)
                         .arg(data->prefSize)
                         .arg(data->maxPrefSize)
                         .arg(data->maxSize)
                         ;
                 }
             }
             strVertices += QString::fromAscii("\"%1\" [label=\"%2\"]\n").arg(v->toString()).arg(v->toString());
         }
         return QString::fromAscii("%1\n%2\n").arg(strVertices).arg(edges);
     }
takeEdge()
template<typename Vertex, typename EdgeData> EdgeData* Graph< Vertex, EdgeData >::takeEdge (Vertex * first, Vertex * second) inline
Definition at line 179 of file qgraph_p.h.
Referenced by QGraphicsAnchorLayoutPrivate::addAnchorMaybeParallel(), createSequence(), QGraphicsAnchorLayoutPrivate::replaceVertex(), QGraphicsAnchorLayoutPrivate::restoreSimplifiedGraph(), QGraphicsAnchorLayoutPrivate::restoreVertices(), and QGraphicsAnchorLayoutPrivate::simplifyVertices().
     {
 #if defined(QT_DEBUG) && 0
         qDebug("Graph::takeEdge(): %s",
                qPrintable(QString::fromAscii("%1-%2")
                           .arg(first->toString()).arg(second->toString())));
 #endif
         // Removes a bidirectional edge
         EdgeData *data = edgeData(first, second);
         if (data) {
             removeDirectedEdge(first, second);
             removeDirectedEdge(second, first);
         }
         return data;
     }
vertices()
template<typename Vertex, typename EdgeData> QSet<Vertex*> Graph< Vertex, EdgeData >::vertices () const inline
Definition at line 204 of file qgraph_p.h.
Referenced by Graph< AnchorVertex, AnchorData >::serializeToDot().
{
         QSet<Vertex *> setOfVertices;
         for (const_iterator it = constBegin(); it != constEnd(); ++it) {
             setOfVertices.insert(*it);
         }
         return setOfVertices;
     }
Properties
m_graph
template<typename Vertex, typename EdgeData> QHash<Vertex *, QHash<Vertex *, EdgeData *> *> Graph< Vertex, EdgeData >::m_graph private
Definition at line 281 of file qgraph_p.h.
Referenced by Graph< AnchorVertex, AnchorData >::adjacentVertices(), Graph< Vertex, EdgeData >::const_iterator::const_iterator(), Graph< AnchorVertex, AnchorData >::createDirectedEdge(), Graph< AnchorVertex, AnchorData >::edgeData(), Graph< Vertex, EdgeData >::const_iterator::operator!=(), Graph< Vertex, EdgeData >::const_iterator::operator++(), and Graph< AnchorVertex, AnchorData >::removeDirectedEdge().
The documentation for this class was generated from the following file:
/src/gui/graphicsview/qgraph_p.h