Qt 4.8: QPatternist::XsdSchemaParserContext Class Reference
QPatternist::XsdSchemaParserContext Class Reference
XML Schema Processing
A context for schema parsing.
#include <qxsdschemaparsercontext_p.h>
Public Types
typedef QExplicitlySharedDataPointer< XsdSchemaParserContext > Ptr
Public Functions
XsdSchemaChecker::Ptr checker () const
QXmlName createAnonymousName (const QString &targetNamespace) const
ElementDescription< XsdSchemaToken, XsdTagScope::Type >::Hash elementDescriptions () const
NamePool::Ptr namePool () const
XsdSchemaResolver::Ptr resolver () const
XsdSchema::Ptr schema () const
XsdSchemaParserContext (const NamePool::Ptr &namePool, const XsdSchemaContext::Ptr &context)
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Private Functions
static ElementDescription< XsdSchemaToken, XsdTagScope::Type >::Hash setupElementDescriptions ()
Properties
QAtomicInt m_anonymousNameCounter
XsdSchemaChecker::Ptr m_checker
const ElementDescription< XsdSchemaToken, XsdTagScope::Type >::Hash m_elementDescriptions
NamePool::Ptr m_namePool
XsdSchemaResolver::Ptr m_resolver
XsdSchema::Ptr m_schema
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
A context for schema parsing.
This class provides a context for all components that are nedded for parsing and compiling the XML schema.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 158 of file qxsdschemaparsercontext_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<XsdSchemaParserContext> QPatternist::XsdSchemaParserContext::Ptr
A smart pointer wrapping XsdSchemaParserContext instances.
Definition at line 164 of file qxsdschemaparsercontext_p.h.
Constructors and Destructors
XsdSchemaParserContext()
XsdSchemaParserContext::XsdSchemaParserContext (const NamePool::Ptr & namePool, const XsdSchemaContext::Ptr & context)
Creates a new schema parser context object.
Parameters
namePool The name pool where all names of the schema will be stored in.
context The schema context to use for error reporting etc.
Definition at line 48 of file qxsdschemaparsercontext.cpp.
     : m_namePool(namePool)
     , m_schema(new XsdSchema(m_namePool))
     , m_checker(new XsdSchemaChecker(context, this))
     , m_resolver(new XsdSchemaResolver(context, this))
     , m_elementDescriptions(setupElementDescriptions())
 {
 }
Functions
checker()
XsdSchemaChecker::Ptr XsdSchemaParserContext::checker () const
Returns the schema resolver of the schema context.
Definition at line 67 of file qxsdschemaparsercontext.cpp.
 {
     return m_checker;
 }
createAnonymousName()
QXmlName XsdSchemaParserContext::createAnonymousName (const QString & targetNamespace) const
Returns an unique name that is used by the schema parser for anonymous types.
Parameters
targetNamespace The namespace of the name.
Definition at line 82 of file qxsdschemaparsercontext.cpp.
Referenced by QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), and QPatternist::XsdSchemaParser::parseRedefine().
 {
     m_anonymousNameCounter.ref();
     const QString name = QString::fromLatin1("__AnonymousClass_%1").arg((int)m_anonymousNameCounter);
     return m_namePool->allocateQName(targetNamespace, name);
 }
elementDescriptions()
ElementDescription< XsdSchemaToken, XsdTagScope::Type >::Hash XsdSchemaParserContext::elementDescriptions () const
Returns the element descriptions for the schema parser.
The element descriptions are a fast lookup table for verifying whether certain attributes are allowed for a given element type.
Definition at line 77 of file qxsdschemaparsercontext.cpp.
Referenced by setupElementDescriptions().
 {
     return m_elementDescriptions;
 }
namePool()
NamePool::Ptr XsdSchemaParserContext::namePool () const
Returns the name pool of the schema parser context.
Definition at line 57 of file qxsdschemaparsercontext.cpp.
 {
     return m_namePool;
 }
resolver()
XsdSchemaResolver::Ptr XsdSchemaParserContext::resolver () const
Returns the schema resolver of the schema context.
Definition at line 62 of file qxsdschemaparsercontext.cpp.
Referenced by QPatternist::XsdSchemaParser::parseRedefine(), and QPatternist::XsdSchemaParser::XsdSchemaParser().
 {
     return m_resolver;
 }
schema()
XsdSchema::Ptr XsdSchemaParserContext::schema () const
Returns the schema object of the schema context.
Definition at line 72 of file qxsdschemaparsercontext.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::loadSchema(), QPatternist::XsdSchemaParser::parseRedefine(), and QPatternist::XsdSchemaParser::XsdSchemaParser().
 {
     return m_schema;
 }
setupElementDescriptions()
ElementDescription< XsdSchemaToken, XsdTagScope::Type >::Hash XsdSchemaParserContext::setupElementDescriptions () static private
Fills the element description hash with the required and prohibited attributes.
Definition at line 91 of file qxsdschemaparsercontext.cpp.
 {
     enum
     {
         ReservedForElements = 60
     };
     ElementDescription<XsdSchemaToken, XsdTagScope::Type>::Hash elementDescriptions;
     elementDescriptions.reserve(ReservedForElements);
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Schema];
         description.optionalAttributes.reserve(10);
         //description.tagToken = XsdSchemaToken::Schema;
         description.optionalAttributes.insert(XsdSchemaToken::AttributeFormDefault);
         description.optionalAttributes.insert(XsdSchemaToken::BlockDefault);
         description.optionalAttributes.insert(XsdSchemaToken::DefaultAttributes);
         description.optionalAttributes.insert(XsdSchemaToken::XPathDefaultNamespace);
         description.optionalAttributes.insert(XsdSchemaToken::ElementFormDefault);
         description.optionalAttributes.insert(XsdSchemaToken::FinalDefault);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::TargetNamespace);
         description.optionalAttributes.insert(XsdSchemaToken::Version);
         description.optionalAttributes.insert(XsdSchemaToken::XmlLanguage);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Include];
         //description.tagToken = XsdSchemaToken::Include;
         description.requiredAttributes.insert(XsdSchemaToken::SchemaLocation);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Import];
         //description.tagToken = XsdSchemaToken::Import;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Namespace);
         description.optionalAttributes.insert(XsdSchemaToken::SchemaLocation);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Redefine];
         //description.tagToken = XsdSchemaToken::Redefine;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::SchemaLocation);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Override];
         //description.tagToken = XsdSchemaToken::Override;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::SchemaLocation);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Annotation];
         //description.tagToken = XsdSchemaToken::Annotation;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::AppInfo];
         //description.tagToken = XsdSchemaToken::Appinfo;
         description.optionalAttributes.insert(XsdSchemaToken::Source);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Documentation];
         //description.tagToken = XsdSchemaToken::Documentation;
         description.optionalAttributes.insert(XsdSchemaToken::Source);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::GlobalSimpleType];
         //description.tagToken = XsdSchemaToken::SimpleType;
         description.optionalAttributes.insert(XsdSchemaToken::Final);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LocalSimpleType];
         //description.tagToken = XsdSchemaToken::SimpleType;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::SimpleRestriction];
         //description.tagToken = XsdSchemaToken::Restriction;
         description.optionalAttributes.insert(XsdSchemaToken::Base);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::List];
         //description.tagToken = XsdSchemaToken::List;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::ItemType);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Union];
         //description.tagToken = XsdSchemaToken::Union;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::MemberTypes);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::MinExclusiveFacet];
         //description.tagToken = XsdSchemaToken::MinExclusive;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::MinInclusiveFacet];
         //description.tagToken = XsdSchemaToken::MinInclusive;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::MaxExclusiveFacet];
         //description.tagToken = XsdSchemaToken::MaxExclusive;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::MaxInclusiveFacet];
         //description.tagToken = XsdSchemaToken::MaxInclusive;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::TotalDigitsFacet];
         //description.tagToken = XsdSchemaToken::TotalDigits;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::FractionDigitsFacet];
         //description.tagToken = XsdSchemaToken::FractionDigits;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LengthFacet];
         //description.tagToken = XsdSchemaToken::Length;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::MinLengthFacet];
         //description.tagToken = XsdSchemaToken::MinLength;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::MaxLengthFacet];
         //description.tagToken = XsdSchemaToken::MaxLength;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::EnumerationFacet];
         //description.tagToken = XsdSchemaToken::Enumeration;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::WhiteSpaceFacet];
         //description.tagToken = XsdSchemaToken::WhiteSpace;
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::PatternFacet];
         //description.tagToken = XsdSchemaToken::Pattern;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Value);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::GlobalComplexType];
         description.optionalAttributes.reserve(7);
         //description.tagToken = XsdSchemaToken::ComplexType;
         description.optionalAttributes.insert(XsdSchemaToken::Abstract);
         description.optionalAttributes.insert(XsdSchemaToken::Block);
         description.optionalAttributes.insert(XsdSchemaToken::DefaultAttributesApply);
         description.optionalAttributes.insert(XsdSchemaToken::Final);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Mixed);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LocalComplexType];
         //description.tagToken = XsdSchemaToken::ComplexType;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Mixed);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::SimpleContent];
         //description.tagToken = XsdSchemaToken::SimpleContent;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::SimpleContentRestriction];
         //description.tagToken = XsdSchemaToken::Restriction;
         description.requiredAttributes.insert(XsdSchemaToken::Base);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::SimpleContentExtension];
         //description.tagToken = XsdSchemaToken::Extension;
         description.requiredAttributes.insert(XsdSchemaToken::Base);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::ComplexContent];
         //description.tagToken = XsdSchemaToken::ComplexContent;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Mixed);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::ComplexContentRestriction];
         //description.tagToken = XsdSchemaToken::Restriction;
         description.requiredAttributes.insert(XsdSchemaToken::Base);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::ComplexContentExtension];
         //description.tagToken = XsdSchemaToken::Extension;
         description.requiredAttributes.insert(XsdSchemaToken::Base);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::NamedGroup];
         //description.tagToken = XsdSchemaToken::Group;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::ReferredGroup];
         description.optionalAttributes.reserve(4);
         //description.tagToken = XsdSchemaToken::Group;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::MaxOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::MinOccurs);
         description.requiredAttributes.insert(XsdSchemaToken::Ref);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::All];
         //description.tagToken = XsdSchemaToken::All;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LocalAll];
         //description.tagToken = XsdSchemaToken::All;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::MaxOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::MinOccurs);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Choice];
         //description.tagToken = XsdSchemaToken::Choice;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LocalChoice];
         //description.tagToken = XsdSchemaToken::Choice;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::MaxOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::MinOccurs);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Sequence];
         //description.tagToken = XsdSchemaToken::Sequence;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LocalSequence];
         //description.tagToken = XsdSchemaToken::Sequence;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::MaxOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::MinOccurs);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::GlobalAttribute];
         description.optionalAttributes.reserve(5);
         //description.tagToken = XsdSchemaToken::Attribute;
         description.optionalAttributes.insert(XsdSchemaToken::Default);
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
         description.optionalAttributes.insert(XsdSchemaToken::Type);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LocalAttribute];
         description.optionalAttributes.reserve(8);
         //description.tagToken = XsdSchemaToken::Attribute;
         description.optionalAttributes.insert(XsdSchemaToken::Default);
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Form);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Name);
         description.optionalAttributes.insert(XsdSchemaToken::Ref);
         description.optionalAttributes.insert(XsdSchemaToken::Type);
         description.optionalAttributes.insert(XsdSchemaToken::Use);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::NamedAttributeGroup];
         //description.tagToken = XsdSchemaToken::AttributeGroup;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::ReferredAttributeGroup];
         //description.tagToken = XsdSchemaToken::AttributeGroup;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Ref);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::LocalElement];
         description.optionalAttributes.reserve(11);
         //description.tagToken = XsdSchemaToken::Element;
         description.optionalAttributes.insert(XsdSchemaToken::Block);
         description.optionalAttributes.insert(XsdSchemaToken::Default);
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Form);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::MinOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::MaxOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::Name);
         description.optionalAttributes.insert(XsdSchemaToken::Nillable);
         description.optionalAttributes.insert(XsdSchemaToken::Ref);
         description.optionalAttributes.insert(XsdSchemaToken::Type);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::GlobalElement];
         description.optionalAttributes.reserve(10);
         //description.tagToken = XsdSchemaToken::Element;
         description.optionalAttributes.insert(XsdSchemaToken::Abstract);
         description.optionalAttributes.insert(XsdSchemaToken::Block);
         description.optionalAttributes.insert(XsdSchemaToken::Default);
         description.optionalAttributes.insert(XsdSchemaToken::Final);
         description.optionalAttributes.insert(XsdSchemaToken::Fixed);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
         description.optionalAttributes.insert(XsdSchemaToken::Nillable);
         description.optionalAttributes.insert(XsdSchemaToken::SubstitutionGroup);
         description.optionalAttributes.insert(XsdSchemaToken::Type);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Unique];
         //description.tagToken = XsdSchemaToken::Unique;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Key];
         //description.tagToken = XsdSchemaToken::Key;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::KeyRef];
         //description.tagToken = XsdSchemaToken::Keyref;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
         description.requiredAttributes.insert(XsdSchemaToken::Refer);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Selector];
         //description.tagToken = XsdSchemaToken::Selector;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Xpath);
         description.optionalAttributes.insert(XsdSchemaToken::XPathDefaultNamespace);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Field];
         //description.tagToken = XsdSchemaToken::Field;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Xpath);
         description.optionalAttributes.insert(XsdSchemaToken::XPathDefaultNamespace);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Notation];
         description.optionalAttributes.reserve(4);
         //description.tagToken = XsdSchemaToken::Notation;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Name);
         description.optionalAttributes.insert(XsdSchemaToken::Public);
         description.optionalAttributes.insert(XsdSchemaToken::System);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Any];
         description.optionalAttributes.reserve(7);
         //description.tagToken = XsdSchemaToken::Any;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::MaxOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::MinOccurs);
         description.optionalAttributes.insert(XsdSchemaToken::Namespace);
         description.optionalAttributes.insert(XsdSchemaToken::NotNamespace);
         description.optionalAttributes.insert(XsdSchemaToken::NotQName);
         description.optionalAttributes.insert(XsdSchemaToken::ProcessContents);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::AnyAttribute];
         description.optionalAttributes.reserve(5);
         //description.tagToken = XsdSchemaToken::AnyAttribute;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Namespace);
         description.optionalAttributes.insert(XsdSchemaToken::NotNamespace);
         description.optionalAttributes.insert(XsdSchemaToken::NotQName);
         description.optionalAttributes.insert(XsdSchemaToken::ProcessContents);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Alternative];
         //description.tagToken = XsdSchemaToken::Alternative;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Test);
         description.optionalAttributes.insert(XsdSchemaToken::Type);
         description.optionalAttributes.insert(XsdSchemaToken::XPathDefaultNamespace);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::OpenContent];
         //description.tagToken = XsdSchemaToken::OpenContent;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Mode);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::DefaultOpenContent];
         //description.tagToken = XsdSchemaToken::DefaultOpenContent;
         description.optionalAttributes.insert(XsdSchemaToken::AppliesToEmpty);
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.optionalAttributes.insert(XsdSchemaToken::Mode);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Assert];
         //description.tagToken = XsdSchemaToken::Assert;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Test);
         description.optionalAttributes.insert(XsdSchemaToken::XPathDefaultNamespace);
     }
     {
         ElementDescription<XsdSchemaToken, XsdTagScope::Type> &description = elementDescriptions[XsdTagScope::Assertion];
         //description.tagToken = XsdSchemaToken::Assertion;
         description.optionalAttributes.insert(XsdSchemaToken::Id);
         description.requiredAttributes.insert(XsdSchemaToken::Test);
         description.optionalAttributes.insert(XsdSchemaToken::XPathDefaultNamespace);
     }
     Q_ASSERT_X(elementDescriptions.count() == ReservedForElements, Q_FUNC_INFO,
                qPrintable(QString::fromLatin1("Expected is %1, actual is %2.").arg(ReservedForElements).arg(elementDescriptions.count())));
     return elementDescriptions;
 }
Properties
m_anonymousNameCounter
QAtomicInt QPatternist::XsdSchemaParserContext::m_anonymousNameCounter mutable private
Definition at line 223 of file qxsdschemaparsercontext_p.h.
Referenced by createAnonymousName().
m_checker
XsdSchemaChecker::Ptr QPatternist::XsdSchemaParserContext::m_checker private
Definition at line 220 of file qxsdschemaparsercontext_p.h.
Referenced by checker().
m_elementDescriptions
const ElementDescription<XsdSchemaToken, XsdTagScope::Type>::Hash QPatternist::XsdSchemaParserContext::m_elementDescriptions private
Definition at line 222 of file qxsdschemaparsercontext_p.h.
Referenced by elementDescriptions().
m_namePool
NamePool::Ptr QPatternist::XsdSchemaParserContext::m_namePool private
Definition at line 218 of file qxsdschemaparsercontext_p.h.
Referenced by createAnonymousName(), and namePool().
m_resolver
XsdSchemaResolver::Ptr QPatternist::XsdSchemaParserContext::m_resolver private
Definition at line 221 of file qxsdschemaparsercontext_p.h.
Referenced by resolver().
m_schema
XsdSchema::Ptr QPatternist::XsdSchemaParserContext::m_schema private
Definition at line 219 of file qxsdschemaparsercontext_p.h.
Referenced by schema().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdschemaparsercontext_p.h
/src/xmlpatterns/schema/qxsdschemaparsercontext.cpp