Qt 4.8: QDeclarativeListModel Class Reference
QDeclarativeListModel Class Reference
#include <qdeclarativelistmodel_p.h>
Signals
void countChanged ()
Signals inherited from QListModelInterface
void itemsChanged (int index, int count, const QList< int > &roles)
Emit this signal when count items at index have had their roles changed.
void itemsInserted (int index, int count)
Emit this signal when count items are inserted at index.
void itemsMoved (int from, int to, int count)
Emit this signal when count items are moved from index from to index to.
void itemsRemoved (int index, int count)
Emit this signal when count items are removed at index.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeListModelWorkerAgent * agent ()
Q_INVOKABLE void append (const QScriptValue &)
Q_INVOKABLE void clear ()
virtual int count () const
Returns the number of data entries in the model.
virtual QVariant data (int index, int role) const
Returns the data at the given index for the specified roles.
Q_INVOKABLE QScriptValue get (int index) const
Q_INVOKABLE void insert (int index, const QScriptValue &)
Q_INVOKABLE void move (int from, int to, int count)
QDeclarativeListModel (QObject *parent=0)
Q_INVOKABLE void remove (int index)
virtual QList< int > roles () const
Returns the list of roles for which the list model interface provides data.
Q_INVOKABLE void set (int index, const QScriptValue &)
Q_INVOKABLE void setProperty (int index, const QString &property, const QVariant &value)
Q_INVOKABLE void sync ()
virtual QString toString (int role) const
Returns a string description of the specified role.
~QDeclarativeListModel ()
Public Functions inherited from QListModelInterface
QListModelInterface (QObject *parent=0)
Constructs a QListModelInterface with the specified parent.
virtual ~QListModelInterface ()
The destructor is virtual.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
bool canMove (int from, int to, int n) const
bool flatten ()
bool inWorkerThread () const
QDeclarativeListModel (const QDeclarativeListModel *orig, QDeclarativeListModelWorkerAgent *parent)
void set (int index, const QScriptValue &, QList< int > *roles)
void setProperty (int index, const QString &property, const QVariant &value, QList< int > *roles)
Properties
int count
QDeclarativeListModelWorkerAgent * m_agent
FlatListModel * m_flat
NestedListModel * m_nested
Friends
class FlatListModel
class FlatListScriptClass
struct ModelNode
class QDeclarativeListModelParser
class QDeclarativeListModelWorkerAgent
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QListModelInterface
QListModelInterface (QObjectPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 67 of file qdeclarativelistmodel_p.h.
Constructors and Destructors
QDeclarativeListModel() [1/2]
QDeclarativeListModel::QDeclarativeListModel (QObject * parent = 0)
Definition at line 222 of file qdeclarativelistmodel.cpp.
Referenced by ModelNode::model().
 : QListModelInterface(parent), m_agent(0), m_nested(new NestedListModel(this)), m_flat(0)
 {
 }
~QDeclarativeListModel()
QDeclarativeListModel::~QDeclarativeListModel ()
Definition at line 244 of file qdeclarativelistmodel.cpp.
 {
     if (m_agent)
         m_agent->release();
     delete m_nested;
     delete m_flat;
 }
QDeclarativeListModel() [2/2]
QDeclarativeListModel::QDeclarativeListModel (const QDeclarativeListModel * orig, QDeclarativeListModelWorkerAgent * parent) private
Definition at line 227 of file qdeclarativelistmodel.cpp.
 : QListModelInterface(parent), m_agent(0), m_nested(0), m_flat(0)
 {
     m_flat = new FlatListModel(this);
     m_flat->m_parentAgent = parent;
     if (orig->m_flat) {
         m_flat->m_roles = orig->m_flat->m_roles;
         m_flat->m_strings = orig->m_flat->m_strings;
         m_flat->m_values = orig->m_flat->m_values;
         m_flat->m_nodeData.reserve(m_flat->m_values.count());
         for (int i=0; i<m_flat->m_values.count(); i++)
             m_flat->m_nodeData << 0;
     }
 }
Functions
agent()
QDeclarativeListModelWorkerAgent * QDeclarativeListModel::agent ()
Definition at line 292 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeWorkerScriptEnginePrivate::scriptValueToVariant().
 {
     if (m_agent)
         return m_agent;
     if (!flatten()) {
         qmlInfo(this) << "List contains list-type data and cannot be used from a worker script";
         return 0;
     }
     m_agent = new QDeclarativeListModelWorkerAgent(this);
     return m_agent;
 }
append()
void QDeclarativeListModel::append (const QScriptValue & valuemap)
Definition at line 518 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelWorkerAgent::append(), and set().
 {
     if (!valuemap.isObject() || valuemap.isArray()) {
         qmlInfo(this) << tr("append: value is not an object");
         return;
     }
     insert(count(), valuemap);
 }
canMove()
bool QDeclarativeListModel::canMove (int from, int to, int n) const inline private
Definition at line 112 of file qdeclarativelistmodel_p.h.
Referenced by move(), and FlatListModel::moveNodes().
 { return !(from+n > count() || to+n > count() || from < 0 || to < 0 || n < 0); }
clear()
void QDeclarativeListModel::clear ()
Definition at line 346 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelWorkerAgent::clear().
 {
     int cleared = count();
     if (m_flat)
         m_flat->clear();
     else
         m_nested->clear();
     if (!inWorkerThread()) {
         emit itemsRemoved(0, cleared);
         emit countChanged();
     }
 }
count()
virtual int QDeclarativeListModel::count () const virtual
Returns the number of data entries in the model.
Implements QListModelInterface.
Referenced by append(), clear(), data(), insert(), remove(), set(), and setProperty().
countChanged
void QDeclarativeListModel::countChanged () signal
Referenced by clear(), QDeclarativeListModelWorkerAgent::event(), insert(), and remove().
data()
QVariant QDeclarativeListModel::data (int index, int role) const virtual
Returns the data at the given index for the specified roles.
Implements QListModelInterface.
Definition at line 316 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelParser::compile(), and QDeclarativeListModelParser::setCustomData().
 {
     if (index >= count() || index < 0)
         return QVariant();
     return m_flat ? m_flat->data(index, role) : m_nested->data(index, role);
 }
flatten()
bool QDeclarativeListModel::flatten () private
Definition at line 253 of file qdeclarativelistmodel.cpp.
Referenced by agent().
 {
     if (m_flat)
         return true;
     QList<int> roles = m_nested->roles();
     QList<QHash<int, QVariant> > values;
     bool hasNested = false;
     for (int i=0; i<m_nested->count(); i++) {
         values.append(m_nested->data(i, roles, &hasNested));
         if (hasNested)
             return false;
     }
     FlatListModel *flat = new FlatListModel(this);
     flat->m_values = values;
     for (int i=0; i<roles.count(); i++) {
         QString s = m_nested->toString(roles[i]);
         flat->m_roles.insert(roles[i], s);
         flat->m_strings.insert(s, roles[i]);
     }
     flat->m_nodeData.reserve(flat->m_values.count());
     for (int i=0; i<flat->m_values.count(); i++)
         flat->m_nodeData << 0;
     m_flat = flat;
     delete m_nested;
     m_nested = 0;
     return true;
 }
get()
QScriptValue QDeclarativeListModel::get (int index) const
Definition at line 562 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelWorkerAgent::get().
 {
     // the internal flat/nested class checks for bad index
     return m_flat ? m_flat->get(index) : m_nested->get(index);
 }
insert()
void QDeclarativeListModel::insert (int index, const QScriptValue & valuemap)
Definition at line 437 of file qdeclarativelistmodel.cpp.
Referenced by append(), and QDeclarativeListModelWorkerAgent::insert().
 {
     if (!valuemap.isObject() || valuemap.isArray()) {
         qmlInfo(this) << tr("insert: value is not an object");
         return;
     }
     if (index < 0 || index > count()) {
         qmlInfo(this) << tr("insert: index %1 out of range").arg(index);
         return;
     }
     bool ok = m_flat ?  m_flat->insert(index, valuemap) : m_nested->insert(index, valuemap);
     if (ok && !inWorkerThread()) {
         emit itemsInserted(index, 1);
         emit countChanged();
     }
 }
inWorkerThread()
bool QDeclarativeListModel::inWorkerThread () const private
Definition at line 287 of file qdeclarativelistmodel.cpp.
Referenced by clear(), insert(), move(), remove(), set(), and setProperty().
 {
     return m_flat && m_flat->m_parentAgent;
 }
move()
void QDeclarativeListModel::move (int from, int to, int count)
Definition at line 473 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelWorkerAgent::move().
 {
     if (n==0 || from==to)
         return;
     if (!canMove(from, to, n)) {
         qmlInfo(this) << tr("move: out of range");
         return;
     }
     int origfrom = from;
     int origto = to;
     int orign = n;
     if (from > to) {
         // Only move forwards - flip if backwards moving
         int tfrom = from;
         int tto = to;
         from = tto;
         to = tto+n;
         n = tfrom-tto;
     }
     if (m_flat)
         m_flat->move(from, to, n);
     else
         m_nested->move(from, to, n);
     if (!inWorkerThread())
         emit itemsMoved(origfrom, origto, orign);
 }
remove()
void QDeclarativeListModel::remove (int index)
Definition at line 401 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelWorkerAgent::remove().
 {
     if (index < 0 || index >= count()) {
         qmlInfo(this) << tr("remove: index %1 out of range").arg(index);
         return;
     }
     if (m_flat)
         m_flat->remove(index);
     else
         m_nested->remove(index);
     if (!inWorkerThread()) {
         emit itemsRemoved(index, 1);
         emit countChanged();
     }
 }
roles()
QList< int > QDeclarativeListModel::roles () const virtual
Returns the list of roles for which the list model interface provides data.
Implements QListModelInterface.
Definition at line 306 of file qdeclarativelistmodel.cpp.
Referenced by flatten(), set(), and setProperty().
 {
     return m_flat ? m_flat->roles() : m_nested->roles();
 }
set() [1/2]
void QDeclarativeListModel::set (int index, const QScriptValue & valuemap)
Definition at line 587 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelWorkerAgent::set().
 {
     QList<int> roles;
     set(index, valuemap, &roles);
     if (!roles.isEmpty() && !inWorkerThread())
         emit itemsChanged(index, 1, roles);
 }
set() [2/2]
void QDeclarativeListModel::set (int index, const QScriptValue & valuemap, QList< int > * roles) private
Definition at line 595 of file qdeclarativelistmodel.cpp.
 {
     if (!valuemap.isObject() || valuemap.isArray()) {
         qmlInfo(this) << tr("set: value is not an object");
         return;
     }
     if (index > count() || index < 0) {
         qmlInfo(this) << tr("set: index %1 out of range").arg(index);
         return;
     }
     if (index == count()) {
         append(valuemap);
     } else {
         if (m_flat)
             m_flat->set(index, valuemap, roles);
         else
             m_nested->set(index, valuemap, roles);
     }
 }
setProperty() [1/2]
void QDeclarativeListModel::setProperty (int index, const QString & property, const QVariant & value)
Definition at line 632 of file qdeclarativelistmodel.cpp.
Referenced by QDeclarativeListModelWorkerAgent::setProperty().
 {
     QList<int> roles;
     setProperty(index, property, value, &roles);
     if (!roles.isEmpty() && !inWorkerThread())
         emit itemsChanged(index, 1, roles);
 }
setProperty() [2/2]
void QDeclarativeListModel::setProperty (int index, const QString & property, const QVariant & value, QList< int > * roles) private
Definition at line 640 of file qdeclarativelistmodel.cpp.
 {
     if (count() == 0 || index >= count() || index < 0) {
         qmlInfo(this) << tr("set: index %1 out of range").arg(index);
         return;
     }
     if (m_flat)
         m_flat->setProperty(index, property, value, roles);
     else
         m_nested->setProperty(index, property, value, roles);
 }
sync()
void QDeclarativeListModel::sync ()
Definition at line 662 of file qdeclarativelistmodel.cpp.
 {
     // This is just a dummy method to make it look like sync() exists in
     // ListModel (and not just QDeclarativeListModelWorkerAgent) and to let
     // us document sync().
     qmlInfo(this) << "List sync() can only be called from a WorkerScript";
 }
toString()
QString QDeclarativeListModel::toString (int role) const virtual
Returns a string description of the specified role.
Implements QListModelInterface.
Definition at line 311 of file qdeclarativelistmodel.cpp.
 {
     return m_flat ? m_flat->toString(role) : m_nested->toString(role);
 }
Friends and Related Functions
FlatListModel
friend class FlatListModel friend
Definition at line 99 of file qdeclarativelistmodel_p.h.
Referenced by flatten(), and QDeclarativeListModel().
FlatListScriptClass
friend class FlatListScriptClass friend
Definition at line 100 of file qdeclarativelistmodel_p.h.
ModelNode
friend struct ModelNode friend
Definition at line 101 of file qdeclarativelistmodel_p.h.
Referenced by QDeclarativeListModelParser::setCustomData().
QDeclarativeListModelParser
friend class QDeclarativeListModelParser friend
Definition at line 97 of file qdeclarativelistmodel_p.h.
QDeclarativeListModelWorkerAgent
friend class QDeclarativeListModelWorkerAgent friend
Definition at line 98 of file qdeclarativelistmodel_p.h.
Referenced by agent().
Properties
count
int QDeclarativeListModel::count private
Definition at line 70 of file qdeclarativelistmodel_p.h.
Referenced by QDeclarativeListModelWorkerAgent::append(), QDeclarativeListModelWorkerAgent::clear(), QDeclarativeListModelWorkerAgent::event(), QDeclarativeListModelWorkerAgent::insert(), QDeclarativeListModelWorkerAgent::release(), and QDeclarativeListModelWorkerAgent::remove().
m_agent
QDeclarativeListModelWorkerAgent* QDeclarativeListModel::m_agent private
Definition at line 114 of file qdeclarativelistmodel_p.h.
Referenced by agent(), and ~QDeclarativeListModel().
m_flat
FlatListModel* QDeclarativeListModel::m_flat private
Definition at line 116 of file qdeclarativelistmodel_p.h.
Referenced by clear(), data(), QDeclarativeListModelWorkerAgent::event(), flatten(), get(), insert(), inWorkerThread(), move(), QDeclarativeListModel(), remove(), roles(), set(), setProperty(), QDeclarativeListModelWorkerAgent::setScriptEngine(), toString(), and ~QDeclarativeListModel().
m_nested
NestedListModel* QDeclarativeListModel::m_nested private
Definition at line 115 of file qdeclarativelistmodel_p.h.
Referenced by clear(), data(), flatten(), get(), insert(), move(), remove(), roles(), set(), QDeclarativeListModelParser::setCustomData(), setProperty(), toString(), ModelNode::~ModelNode(), and ~QDeclarativeListModel().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativelistmodel_p.h
/src/declarative/util/qdeclarativelistmodel.cpp