Qt 4.8: QIntersectionFinder Class Reference
QIntersectionFinder Class Reference
Public Functions
bool hasIntersections (const QPathSegments &a, const QPathSegments &b) const
void produceIntersections (QPathSegments &segments)
Private Functions
bool linesIntersect (const QLineF &a, const QLineF &b) const
Detailed Description
Definition at line 104 of file qpathclipper.cpp.
Functions
hasIntersections()
bool QIntersectionFinder::hasIntersections (const QPathSegments & a, const QPathSegments & b) const
Definition at line 181 of file qpathclipper.cpp.
Referenced by QPathClipper::contains(), and QPathClipper::intersect().
 {
     if (a.segments() == 0 || b.segments() == 0)
         return false;
     const QRectF &rb0 = b.elementBounds(0);
     qreal minX = rb0.left();
     qreal minY = rb0.top();
     qreal maxX = rb0.right();
     qreal maxY = rb0.bottom();
     for (int i = 1; i < b.segments(); ++i) {
         const QRectF &r = b.elementBounds(i);
         minX = qMin(minX, r.left());
         minY = qMin(minY, r.top());
         maxX = qMax(maxX, r.right());
         maxY = qMax(maxY, r.bottom());
     }
     QRectF rb(minX, minY, maxX - minX, maxY - minY);
     for (int i = 0; i < a.segments(); ++i) {
         const QRectF &r1 = a.elementBounds(i);
         if (r1.left() > rb.right() || rb.left() > r1.right())
             continue;
         if (r1.top() > rb.bottom() || rb.top() > r1.bottom())
             continue;
         for (int j = 0; j < b.segments(); ++j) {
             const QRectF &r2 = b.elementBounds(j);
             if (r1.left() > r2.right() || r2.left() > r1.right())
                 continue;
             if (r1.top() > r2.bottom() || r2.top() > r1.bottom())
                 continue;
             if (linesIntersect(a.lineAt(i), b.lineAt(j)))
                 return true;
         }
     }
     return false;
 }
linesIntersect()
bool QIntersectionFinder::linesIntersect (const QLineF & a, const QLineF & b) const private
Definition at line 114 of file qpathclipper.cpp.
 {
     const QPointF p1 = a.p1();
     const QPointF p2 = a.p2();
     const QPointF q1 = b.p1();
     const QPointF q2 = b.p2();
     if (comparePoints(p1, p2) || comparePoints(q1, q2))
         return false;
     const bool p1_equals_q1 = comparePoints(p1, q1);
     const bool p2_equals_q2 = comparePoints(p2, q2);
     if (p1_equals_q1 && p2_equals_q2)
         return true;
     const bool p1_equals_q2 = comparePoints(p1, q2);
     const bool p2_equals_q1 = comparePoints(p2, q1);
     if (p1_equals_q2 && p2_equals_q1)
         return true;
     const QPointF pDelta = p2 - p1;
     const QPointF qDelta = q2 - q1;
     const qreal par = pDelta.x() * qDelta.y() - pDelta.y() * qDelta.x();
     if (qFuzzyIsNull(par)) {
         const QPointF normal(-pDelta.y(), pDelta.x());
         // coinciding?
         if (qFuzzyIsNull(dot(normal, q1 - p1))) {
             const qreal dp = dot(pDelta, pDelta);
             const qreal tq1 = dot(pDelta, q1 - p1);
             const qreal tq2 = dot(pDelta, q2 - p1);
             if ((tq1 > 0 && tq1 < dp) || (tq2 > 0 && tq2 < dp))
                 return true;
             const qreal dq = dot(qDelta, qDelta);
             const qreal tp1 = dot(qDelta, p1 - q1);
             const qreal tp2 = dot(qDelta, p2 - q1);
             if ((tp1 > 0 && tp1 < dq) || (tp2 > 0 && tp2 < dq))
                 return true;
         }
         return false;
     }
     const qreal invPar = 1 / par;
     const qreal tp = (qDelta.y() * (q1.x() - p1.x()) -
                       qDelta.x() * (q1.y() - p1.y())) * invPar;
     if (tp < 0 || tp > 1)
         return false;
     const qreal tq = (pDelta.y() * (q1.x() - p1.x()) -
                       pDelta.x() * (q1.y() - p1.y())) * invPar;
     return tq >= 0 && tq <= 1;
 }
produceIntersections()
void QIntersectionFinder::produceIntersections (QPathSegments & segments)
Definition at line 594 of file qpathclipper.cpp.
Referenced by QWingedEdge::intersectAndAdd().
 {
     SegmentTree tree(segments);
     for (int i = 0; i < segments.segments(); ++i)
         tree.produceIntersections(i);
 }
The documentation for this class was generated from the following file:
/src/gui/painting/qpathclipper.cpp