Qt 4.8: QGestureManager Class Reference
QGestureManager Class Reference
#include <qgesturemanager_p.h>
Classes
struct ObjectGesture
Public Functions
void cleanupCachedGestures (QObject *target, Qt::GestureType type)
bool filterEvent (QWidget *receiver, QEvent *event)
bool filterEvent (QObject *receiver, QEvent *event)
bool filterEvent (QGraphicsObject *receiver, QEvent *event)
QGestureManager (QObject *parent)
void recycle (QGesture *gesture)
Qt::GestureType registerGestureRecognizer (QGestureRecognizer *recognizer)
void unregisterGestureRecognizer (Qt::GestureType type)
~QGestureManager ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QGestureManager * instance ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
bool filterEventThroughContexts (const QMultiMap< QObject *, Qt::GestureType > &contexts, QEvent *event)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Types
enum State { Gesture, NotGesture, MaybeGesture }
Private Functions
void cancelGesturesForChildren (QGesture *originatingGesture)
void cleanupGesturesForRemovedRecognizer (QGesture *gesture)
void deliverEvents (const QSet< QGesture *> &gestures, QSet< QGesture *> *undeliveredGestures)
void getGestureTargets (const QSet< QGesture *> &gestures, QMap< QWidget *, QList< QGesture *> > *conflicts, QMap< QWidget *, QList< QGesture *> > *normal)
QGesture * getState (QObject *widget, QGestureRecognizer *recognizer, Qt::GestureType gesture)
Properties
QSet< QGesture * > m_activeGestures
QHash< QGesture *, QGestureRecognizer * > m_deletedRecognizers
QHash< QGesture *, QObject * > m_gestureOwners
QSet< QGesture * > m_gesturesToDelete
QHash< QGesture *, QWidget * > m_gestureTargets
QHash< QGesture *, QGestureRecognizer * > m_gestureToRecognizer
int m_lastCustomGestureId
QSet< QGesture * > m_maybeGestures
QMap< ObjectGesture, QList< QGesture * > > m_objectGestures
QHash< QGestureRecognizer *, QSet< QGesture * > > m_obsoleteGestures
QMultiMap< Qt::GestureType, QGestureRecognizer * > m_recognizers
enum QGestureManager::State state
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 67 of file qgesturemanager_p.h.
Enumerations
State
enum QGestureManager::State private
Enumerator
Gesture
NotGesture
MaybeGesture
Definition at line 99 of file qgesturemanager_p.h.
                {
         Gesture,
         NotGesture,
         MaybeGesture // this means timers are up and waiting for some
                      // more events, and input events are handled by
                      // gesture recognizer explicitly
     } state;
Constructors and Destructors
QGestureManager()
QGestureManager::QGestureManager (QObject * parent)
Definition at line 73 of file qgesturemanager.cpp.
     : QObject(parent), state(NotGesture), m_lastCustomGestureId(Qt::CustomGesture)
 {
     qRegisterMetaType<Qt::GestureState>();
 #if defined(Q_WS_MAC)
     registerGestureRecognizer(new QMacSwipeGestureRecognizer);
     registerGestureRecognizer(new QMacPinchGestureRecognizer);
   #if defined(QT_MAC_USE_COCOA)
     registerGestureRecognizer(new QMacPanGestureRecognizer);
   #endif
 #else
     registerGestureRecognizer(new QPanGestureRecognizer);
     registerGestureRecognizer(new QPinchGestureRecognizer);
     registerGestureRecognizer(new QSwipeGestureRecognizer);
     registerGestureRecognizer(new QTapGestureRecognizer);
 #endif
 #if defined(Q_OS_WIN)
   #if !defined(QT_NO_NATIVE_GESTURES)
     if (QApplicationPrivate::HasTouchSupport)
         registerGestureRecognizer(new QWinNativePanGestureRecognizer);
   #endif
 #else
     registerGestureRecognizer(new QTapAndHoldGestureRecognizer);
 #endif
 }
~QGestureManager()
QGestureManager::~QGestureManager ()
Definition at line 100 of file qgesturemanager.cpp.
 {
     qDeleteAll(m_recognizers.values());
     foreach (QGestureRecognizer *recognizer, m_obsoleteGestures.keys()) {
         qDeleteAll(m_obsoleteGestures.value(recognizer));
         delete recognizer;
     }
     m_obsoleteGestures.clear();
 }
Functions
cancelGesturesForChildren()
void QGestureManager::cancelGesturesForChildren (QGesture * originatingGesture) private
Definition at line 396 of file qgesturemanager.cpp.
Referenced by filterEventThroughContexts().
 {
     Q_ASSERT(original);
     QWidget *originatingWidget = m_gestureTargets.value(original);
     Q_ASSERT(originatingWidget);
     // iterate over all active gestures and all maybe gestures
     // for each find the owner
     // if the owner is part of our sub-hierarchy, cancel it.
     QSet<QGesture*> cancelledGestures;
     QSet<QGesture*>::Iterator iter = m_activeGestures.begin();
     while (iter != m_activeGestures.end()) {
         QWidget *widget = m_gestureTargets.value(*iter);
         // note that we don't touch the gestures for our originatingWidget
         if (widget != originatingWidget && originatingWidget->isAncestorOf(widget)) {
             DEBUG() << "  found a gesture to cancel" << (*iter);
             (*iter)->d_func()->state = Qt::GestureCanceled;
             cancelledGestures << *iter;
             iter = m_activeGestures.erase(iter);
         } else {
             ++iter;
         }
     }
     // TODO handle 'maybe' gestures too
     // sort them per target widget by cherry picking from almostCanceledGestures and delivering
     QSet<QGesture *> almostCanceledGestures = cancelledGestures;
     while (!almostCanceledGestures.isEmpty()) {
         QWidget *target = 0;
         QSet<QGesture*> gestures;
         iter = almostCanceledGestures.begin();
         // sort per target widget
         while (iter != almostCanceledGestures.end()) {
             QWidget *widget = m_gestureTargets.value(*iter);
             if (target == 0)
                 target = widget;
             if (target == widget) {
                 gestures << *iter;
                 iter = almostCanceledGestures.erase(iter);
             } else {
                 ++iter;
             }
         }
         Q_ASSERT(target);
         QSet<QGesture*> undeliveredGestures;
         deliverEvents(gestures, &undeliveredGestures);
     }
     for (iter = cancelledGestures.begin(); iter != cancelledGestures.end(); ++iter)
         recycle(*iter);
 }
cleanupCachedGestures()
void QGestureManager::cleanupCachedGestures (QObject * target, Qt::GestureType type)
Definition at line 160 of file qgesturemanager.cpp.
Referenced by QGraphicsScenePrivate::ungrabGesture().
 {
     QMap<ObjectGesture, QList<QGesture *> >::Iterator iter = m_objectGestures.begin();
     while (iter != m_objectGestures.end()) {
         ObjectGesture objectGesture = iter.key();
         if (objectGesture.gesture == type && target == objectGesture.object) {
             QSet<QGesture *> gestures = iter.value().toSet();
             for (QHash<QGestureRecognizer *, QSet<QGesture *> >::iterator
                  it = m_obsoleteGestures.begin(), e = m_obsoleteGestures.end(); it != e; ++it) {
                 it.value() -= gestures;
             }
             foreach (QGesture *g, gestures) {
                 m_deletedRecognizers.remove(g);
                 m_gestureToRecognizer.remove(g);
                 m_maybeGestures.remove(g);
                 m_activeGestures.remove(g);
                 m_gestureOwners.remove(g);
                 m_gestureTargets.remove(g);
                 m_gesturesToDelete.insert(g);
             }
             iter = m_objectGestures.erase(iter);
         } else {
             ++iter;
         }
     }
 }
cleanupGesturesForRemovedRecognizer()
void QGestureManager::cleanupGesturesForRemovedRecognizer (QGesture * gesture) private
Definition at line 451 of file qgesturemanager.cpp.
Referenced by recycle().
 {
     QGestureRecognizer *recognizer = m_deletedRecognizers.value(gesture);
     if(!recognizer) //The Gesture is removed while in the even loop, so the recognizers for this gestures was removed
         return;
     m_deletedRecognizers.remove(gesture);
     if (m_deletedRecognizers.keys(recognizer).isEmpty()) {
         // no more active gestures, cleanup!
         qDeleteAll(m_obsoleteGestures.value(recognizer));
         m_obsoleteGestures.remove(recognizer);
         delete recognizer;
     }
 }
deliverEvents()
void QGestureManager::deliverEvents (const QSet< QGesture *> & gestures, QSet< QGesture *> * undeliveredGestures) private
Definition at line 585 of file qgesturemanager.cpp.
Referenced by cancelGesturesForChildren(), and filterEventThroughContexts().
 {
     if (gestures.isEmpty())
         return;
     typedef QMap<QWidget *, QList<QGesture *> > GesturesPerWidget;
     GesturesPerWidget conflictedGestures;
     GesturesPerWidget normalStartedGestures;
     QSet<QGesture *> startedGestures;
     // first figure out the initial receivers of gestures
     for (QSet<QGesture *>::const_iterator it = gestures.begin(),
          e = gestures.end(); it != e; ++it) {
         QGesture *gesture = *it;
         QWidget *target = m_gestureTargets.value(gesture, 0);
         if (!target) {
             // the gesture has just started and doesn't have a target yet.
             Q_ASSERT(gesture->state() == Qt::GestureStarted);
             if (gesture->hasHotSpot()) {
                 // guess the target widget using the hotspot of the gesture
                 QPoint pt = gesture->hotSpot().toPoint();
                 if (QWidget *topLevel = qApp->topLevelAt(pt)) {
                     QWidget *child = topLevel->childAt(topLevel->mapFromGlobal(pt));
                     target = child ? child : topLevel;
                 }
             } else {
                 // or use the context of the gesture
                 QObject *context = m_gestureOwners.value(gesture, 0);
                 if (context->isWidgetType())
                     target = static_cast<QWidget *>(context);
             }
             if (target)
                 m_gestureTargets.insert(gesture, target);
         }
         Qt::GestureType gestureType = gesture->gestureType();
         Q_ASSERT(gestureType != Qt::CustomGesture);
         Q_UNUSED(gestureType);
         if (target) {
             if (gesture->state() == Qt::GestureStarted) {
                 startedGestures.insert(gesture);
             } else {
                 normalStartedGestures[target].append(gesture);
             }
         } else {
             DEBUG() << "QGestureManager::deliverEvent: could not find the target for gesture"
                     << gesture->gestureType();
             qWarning("QGestureManager::deliverEvent: could not find the target for gesture");
             undeliveredGestures->insert(gesture);
         }
     }
     getGestureTargets(startedGestures, &conflictedGestures, &normalStartedGestures);
     DEBUG() << "QGestureManager::deliverEvents:"
             << "\nstarted: " << startedGestures
             << "\nconflicted: " << conflictedGestures
             << "\nnormal: " << normalStartedGestures
             << "\n";
     // if there are conflicting gestures, send the GestureOverride event
     for (GesturesPerWidget::const_iterator it = conflictedGestures.begin(),
         e = conflictedGestures.end(); it != e; ++it) {
         QWidget *receiver = it.key();
         QList<QGesture *> gestures = it.value();
         DEBUG() << "QGestureManager::deliverEvents: sending GestureOverride to"
                 << receiver
                 << "gestures:" << gestures;
         QGestureEvent event(gestures);
         event.t = QEvent::GestureOverride;
         // mark event and individual gestures as ignored
         event.ignore();
         foreach(QGesture *g, gestures)
             event.setAccepted(g, false);
         QApplication::sendEvent(receiver, &event);
         bool eventAccepted = event.isAccepted();
         foreach(QGesture *gesture, event.gestures()) {
             if (eventAccepted || event.isAccepted(gesture)) {
                 QWidget *w = event.d_func()->targetWidgets.value(gesture->gestureType(), 0);
                 Q_ASSERT(w);
                 DEBUG() << "override event: gesture was accepted:" << gesture << w;
                 QList<QGesture *> &gestures = normalStartedGestures[w];
                 gestures.append(gesture);
                 // override the target
                 m_gestureTargets[gesture] = w;
             } else {
                 DEBUG() << "override event: gesture wasn't accepted. putting back:" << gesture;
                 QList<QGesture *> &gestures = normalStartedGestures[receiver];
                 gestures.append(gesture);
             }
         }
     }
     // delivering gestures that are not in conflicted state
     for (GesturesPerWidget::const_iterator it = normalStartedGestures.begin(),
         e = normalStartedGestures.end(); it != e; ++it) {
         if (!it.value().isEmpty()) {
             DEBUG() << "QGestureManager::deliverEvents: sending to" << it.key()
                     << "gestures:" << it.value();
             QGestureEvent event(it.value());
             QApplication::sendEvent(it.key(), &event);
             bool eventAccepted = event.isAccepted();
             foreach (QGesture *gesture, event.gestures()) {
                 if (gesture->state() == Qt::GestureStarted &&
                     (eventAccepted || event.isAccepted(gesture))) {
                     QWidget *w = event.d_func()->targetWidgets.value(gesture->gestureType(), 0);
                     Q_ASSERT(w);
                     DEBUG() << "started gesture was delivered and accepted by" << w;
                     m_gestureTargets[gesture] = w;
                 }
             }
         }
     }
 }
filterEvent() [1/3]
bool QGestureManager::filterEvent (QWidget * receiver, QEvent * event)
Definition at line 466 of file qgesturemanager.cpp.
Referenced by QGraphicsScenePrivate::sendEvent().
 {
     QMap<Qt::GestureType, int> types;
     QMultiMap<QObject *, Qt::GestureType> contexts;
     QWidget *w = receiver;
     typedef QMap<Qt::GestureType, Qt::GestureFlags>::const_iterator ContextIterator;
     if (!w->d_func()->gestureContext.isEmpty()) {
         for(ContextIterator it = w->d_func()->gestureContext.begin(),
             e = w->d_func()->gestureContext.end(); it != e; ++it) {
             types.insert(it.key(), 0);
             contexts.insertMulti(w, it.key());
         }
     }
     // find all gesture contexts for the widget tree
     w = w->isWindow() ? 0 : w->parentWidget();
     while (w)
     {
         for (ContextIterator it = w->d_func()->gestureContext.begin(),
              e = w->d_func()->gestureContext.end(); it != e; ++it) {
             if (!(it.value() & Qt::DontStartGestureOnChildren)) {
                 if (!types.contains(it.key())) {
                     types.insert(it.key(), 0);
                     contexts.insertMulti(w, it.key());
                 }
             }
         }
         if (w->isWindow())
             break;
         w = w->parentWidget();
     }
     return contexts.isEmpty() ? false : filterEventThroughContexts(contexts, event);
 }
filterEvent() [2/3]
bool QGestureManager::filterEvent (QObject * receiver, QEvent * event)
Definition at line 533 of file qgesturemanager.cpp.
 {
     if (!m_gestureToRecognizer.contains(static_cast<QGesture *>(receiver)))
         return false;
     QGesture *state = static_cast<QGesture *>(receiver);
     QMultiMap<QObject *, Qt::GestureType> contexts;
     contexts.insert(state, state->gestureType());
     return filterEventThroughContexts(contexts, event);
 }
filterEvent() [3/3]
bool QGestureManager::filterEvent (QGraphicsObject * receiver, QEvent * event)
Definition at line 500 of file qgesturemanager.cpp.
 {
     QMap<Qt::GestureType, int> types;
     QMultiMap<QObject *, Qt::GestureType> contexts;
     QGraphicsObject *item = receiver;
     if (!item->QGraphicsItem::d_func()->gestureContext.isEmpty()) {
         typedef QMap<Qt::GestureType, Qt::GestureFlags>::const_iterator ContextIterator;
         for(ContextIterator it = item->QGraphicsItem::d_func()->gestureContext.begin(),
             e = item->QGraphicsItem::d_func()->gestureContext.end(); it != e; ++it) {
             types.insert(it.key(), 0);
             contexts.insertMulti(item, it.key());
         }
     }
     // find all gesture contexts for the graphics object tree
     item = item->parentObject();
     while (item)
     {
         typedef QMap<Qt::GestureType, Qt::GestureFlags>::const_iterator ContextIterator;
         for (ContextIterator it = item->QGraphicsItem::d_func()->gestureContext.begin(),
              e = item->QGraphicsItem::d_func()->gestureContext.end(); it != e; ++it) {
             if (!(it.value() & Qt::DontStartGestureOnChildren)) {
                 if (!types.contains(it.key())) {
                     types.insert(it.key(), 0);
                     contexts.insertMulti(item, it.key());
                 }
             }
         }
         item = item->parentObject();
     }
     return contexts.isEmpty() ? false : filterEventThroughContexts(contexts, event);
 }
filterEventThroughContexts()
bool QGestureManager::filterEventThroughContexts (const QMultiMap< QObject *, Qt::GestureType > & contexts, QEvent * event) protected
Definition at line 234 of file qgesturemanager.cpp.
Referenced by filterEvent().
 {
     QSet<QGesture *> triggeredGestures;
     QSet<QGesture *> finishedGestures;
     QSet<QGesture *> newMaybeGestures;
     QSet<QGesture *> notGestures;
     // TODO: sort contexts by the gesture type and check if one of the contexts
     //       is already active.
     bool consumeEventHint = false;
     // filter the event through recognizers
     typedef QMultiMap<QObject *, Qt::GestureType>::const_iterator ContextIterator;
     ContextIterator contextEnd = contexts.end();
     for (ContextIterator context = contexts.begin(); context != contextEnd; ++context) {
         Qt::GestureType gestureType = context.value();
         QMap<Qt::GestureType, QGestureRecognizer *>::const_iterator
                 typeToRecognizerIterator = m_recognizers.lowerBound(gestureType),
                 typeToRecognizerEnd = m_recognizers.upperBound(gestureType);
         for (; typeToRecognizerIterator != typeToRecognizerEnd; ++typeToRecognizerIterator) {
             QGestureRecognizer *recognizer = typeToRecognizerIterator.value();
             QObject *target = context.key();
             QGesture *state = getState(target, recognizer, gestureType);
             if (!state)
                 continue;
             QGestureRecognizer::Result recognizerResult = recognizer->recognize(state, target, event);
             QGestureRecognizer::Result recognizerState = recognizerResult & QGestureRecognizer::ResultState_Mask;
             QGestureRecognizer::Result resultHint = recognizerResult & QGestureRecognizer::ResultHint_Mask;
             if (recognizerState == QGestureRecognizer::TriggerGesture) {
                 DEBUG() << "QGestureManager:Recognizer: gesture triggered: " << state;
                 triggeredGestures << state;
             } else if (recognizerState == QGestureRecognizer::FinishGesture) {
                 DEBUG() << "QGestureManager:Recognizer: gesture finished: " << state;
                 finishedGestures << state;
             } else if (recognizerState == QGestureRecognizer::MayBeGesture) {
                 DEBUG() << "QGestureManager:Recognizer: maybe gesture: " << state;
                 newMaybeGestures << state;
             } else if (recognizerState == QGestureRecognizer::CancelGesture) {
                 DEBUG() << "QGestureManager:Recognizer: not gesture: " << state;
                 notGestures << state;
             } else if (recognizerState == QGestureRecognizer::Ignore) {
                 DEBUG() << "QGestureManager:Recognizer: ignored the event: " << state;
             } else {
                 DEBUG() << "QGestureManager:Recognizer: hm, lets assume the recognizer"
                         << "ignored the event: " << state;
             }
             if (resultHint & QGestureRecognizer::ConsumeEventHint) {
                 DEBUG() << "QGestureManager: we were asked to consume the event: "
                         << state;
                 consumeEventHint = true;
             }
         }
     }
     if (!triggeredGestures.isEmpty() || !finishedGestures.isEmpty()
         || !newMaybeGestures.isEmpty() || !notGestures.isEmpty()) {
         QSet<QGesture *> startedGestures = triggeredGestures - m_activeGestures;
         triggeredGestures &= m_activeGestures;
         // check if a running gesture switched back to maybe state
         QSet<QGesture *> activeToMaybeGestures = m_activeGestures & newMaybeGestures;
         // check if a maybe gesture switched to canceled - reset it but don't send an event
         QSet<QGesture *> maybeToCanceledGestures = m_maybeGestures & notGestures;
         // check if a running gesture switched back to not gesture state,
         // i.e. were canceled
         QSet<QGesture *> canceledGestures = m_activeGestures & notGestures;
         // new gestures in maybe state
         m_maybeGestures += newMaybeGestures;
         // gestures that were in maybe state
         QSet<QGesture *> notMaybeGestures = (startedGestures | triggeredGestures
                                              | finishedGestures | canceledGestures
                                              | notGestures);
         m_maybeGestures -= notMaybeGestures;
         Q_ASSERT((startedGestures & finishedGestures).isEmpty());
         Q_ASSERT((startedGestures & newMaybeGestures).isEmpty());
         Q_ASSERT((startedGestures & canceledGestures).isEmpty());
         Q_ASSERT((finishedGestures & newMaybeGestures).isEmpty());
         Q_ASSERT((finishedGestures & canceledGestures).isEmpty());
         Q_ASSERT((canceledGestures & newMaybeGestures).isEmpty());
         QSet<QGesture *> notStarted = finishedGestures - m_activeGestures;
         if (!notStarted.isEmpty()) {
             // there are some gestures that claim to be finished, but never started.
             // probably those are "singleshot" gestures so we'll fake the started state.
             foreach (QGesture *gesture, notStarted)
                 gesture->d_func()->state = Qt::GestureStarted;
             QSet<QGesture *> undeliveredGestures;
             deliverEvents(notStarted, &undeliveredGestures);
             finishedGestures -= undeliveredGestures;
         }
         m_activeGestures += startedGestures;
         // sanity check: all triggered gestures should already be in active gestures list
         Q_ASSERT((m_activeGestures & triggeredGestures).size() == triggeredGestures.size());
         m_activeGestures -= finishedGestures;
         m_activeGestures -= activeToMaybeGestures;
         m_activeGestures -= canceledGestures;
         // set the proper gesture state on each gesture
         foreach (QGesture *gesture, startedGestures)
             gesture->d_func()->state = Qt::GestureStarted;
         foreach (QGesture *gesture, triggeredGestures)
             gesture->d_func()->state = Qt::GestureUpdated;
         foreach (QGesture *gesture, finishedGestures)
             gesture->d_func()->state = Qt::GestureFinished;
         foreach (QGesture *gesture, canceledGestures)
             gesture->d_func()->state = Qt::GestureCanceled;
         foreach (QGesture *gesture, activeToMaybeGestures)
             gesture->d_func()->state = Qt::GestureFinished;
         if (!m_activeGestures.isEmpty() || !m_maybeGestures.isEmpty() ||
             !startedGestures.isEmpty() || !triggeredGestures.isEmpty() ||
             !finishedGestures.isEmpty() || !canceledGestures.isEmpty()) {
             DEBUG() << "QGestureManager::filterEventThroughContexts:"
                     << "\n\tactiveGestures:" << m_activeGestures
                     << "\n\tmaybeGestures:" << m_maybeGestures
                     << "\n\tstarted:" << startedGestures
                     << "\n\ttriggered:" << triggeredGestures
                     << "\n\tfinished:" << finishedGestures
                     << "\n\tcanceled:" << canceledGestures
                     << "\n\tmaybe-canceled:" << maybeToCanceledGestures;
         }
         QSet<QGesture *> undeliveredGestures;
         deliverEvents(startedGestures+triggeredGestures+finishedGestures+canceledGestures,
                       &undeliveredGestures);
         foreach (QGesture *g, startedGestures) {
             if (undeliveredGestures.contains(g))
                 continue;
             if (g->gestureCancelPolicy() == QGesture::CancelAllInContext) {
                 DEBUG() << "lets try to cancel some";
                 // find gestures in context in Qt::GestureStarted or Qt::GestureUpdated state and cancel them
                 cancelGesturesForChildren(g);
             }
         }
         m_activeGestures -= undeliveredGestures;
         // reset gestures that ended
         QSet<QGesture *> endedGestures =
                 finishedGestures + canceledGestures + undeliveredGestures + maybeToCanceledGestures;
         foreach (QGesture *gesture, endedGestures) {
             recycle(gesture);
             m_gestureTargets.remove(gesture);
         }
     }
     //Clean up the Gestures
     qDeleteAll(m_gesturesToDelete);
     m_gesturesToDelete.clear();
     return consumeEventHint;
 }
getGestureTargets()
void QGestureManager::getGestureTargets (const QSet< QGesture *> & gestures, QMap< QWidget *, QList< QGesture *> > * conflicts, QMap< QWidget *, QList< QGesture *> > * normal) private
Definition at line 543 of file qgesturemanager.cpp.
Referenced by deliverEvents().
 {
     typedef QHash<Qt::GestureType, QHash<QWidget *, QGesture *> > GestureByTypes;
     GestureByTypes gestureByTypes;
     // sort gestures by types
     foreach (QGesture *gesture, gestures) {
         QWidget *receiver = m_gestureTargets.value(gesture, 0);
         Q_ASSERT(receiver);
         gestureByTypes[gesture->gestureType()].insert(receiver, gesture);
     }
     // for each gesture type
     foreach (Qt::GestureType type, gestureByTypes.keys()) {
         QHash<QWidget *, QGesture *> gestures = gestureByTypes.value(type);
         foreach (QWidget *widget, gestures.keys()) {
             QWidget *w = widget->parentWidget();
             while (w) {
                 QMap<Qt::GestureType, Qt::GestureFlags>::const_iterator it
                         = w->d_func()->gestureContext.find(type);
                 if (it != w->d_func()->gestureContext.end()) {
                     // i.e. 'w' listens to gesture 'type'
                     if (!(it.value() & Qt::DontStartGestureOnChildren) && w != widget) {
                         // conflicting gesture!
                         (*conflicts)[widget].append(gestures[widget]);
                         break;
                     }
                 }
                 if (w->isWindow()) {
                     w = 0;
                     break;
                 }
                 w = w->parentWidget();
             }
             if (!w)
                 (*normal)[widget].append(gestures[widget]);
         }
     }
 }
getState()
QGesture * QGestureManager::getState (QObject * widget, QGestureRecognizer * recognizer, Qt::GestureType gesture) private
Definition at line 189 of file qgesturemanager.cpp.
Referenced by filterEventThroughContexts().
 {
     // if the widget is being deleted we should be careful not to
     // create a new state, as it will create QWeakPointer which doesn't work
     // from the destructor.
     if (object->isWidgetType()) {
         if (static_cast<QWidget *>(object)->d_func()->data.in_destructor)
             return 0;
     } else if (QGesture *g = qobject_cast<QGesture *>(object)) {
         return g;
 #ifndef QT_NO_GRAPHICSVIEW
     } else {
         Q_ASSERT(qobject_cast<QGraphicsObject *>(object));
         QGraphicsObject *graphicsObject = static_cast<QGraphicsObject *>(object);
         if (graphicsObject->QGraphicsItem::d_func()->inDestructor)
             return 0;
 #endif
     }
     // check if the QGesture for this recognizer has already been created
     foreach (QGesture *state, m_objectGestures.value(QGestureManager::ObjectGesture(object, type))) {
         if (m_gestureToRecognizer.value(state) == recognizer)
             return state;
     }
     Q_ASSERT(recognizer);
     QGesture *state = recognizer->create(object);
     if (!state)
         return 0;
     state->setParent(this);
     if (state->gestureType() == Qt::CustomGesture) {
         // if the recognizer didn't fill in the gesture type, then this
         // is a custom gesture with autogenerated id and we fill it.
         state->d_func()->gestureType = type;
 #if defined(GESTURE_DEBUG)
         state->setObjectName(QString::number((int)type));
 #endif
     }
     m_objectGestures[QGestureManager::ObjectGesture(object, type)].append(state);
     m_gestureToRecognizer[state] = recognizer;
     m_gestureOwners[state] = object;
     return state;
 }
instance()
QGestureManager * QGestureManager::instance () static
Definition at line 6199 of file qapplication.cpp.
Referenced by QGestureRecognizer::registerRecognizer(), QGraphicsScenePrivate::ungrabGesture(), QWidget::ungrabGesture(), QGestureRecognizer::unregisterRecognizer(), and QGraphicsItem::~QGraphicsItem().
 {
     QApplicationPrivate *qAppPriv = QApplicationPrivate::instance();
     if (!qAppPriv)
         return 0;
     if (!qAppPriv->gestureManager)
         qAppPriv->gestureManager = new QGestureManager(qApp);
     return qAppPriv->gestureManager;
 }
recycle()
void QGestureManager::recycle (QGesture * gesture)
Definition at line 702 of file qgesturemanager.cpp.
Referenced by cancelGesturesForChildren(), QGraphicsScenePrivate::cancelGesturesForChildren(), and filterEventThroughContexts().
 {
     QGestureRecognizer *recognizer = m_gestureToRecognizer.value(gesture, 0);
     if (recognizer) {
         gesture->setGestureCancelPolicy(QGesture::CancelNone);
         recognizer->reset(gesture);
         m_activeGestures.remove(gesture);
     } else {
         cleanupGesturesForRemovedRecognizer(gesture);
     }
 }
registerGestureRecognizer()
Qt::GestureType QGestureManager::registerGestureRecognizer (QGestureRecognizer * recognizer)
Definition at line 110 of file qgesturemanager.cpp.
Referenced by QGestureManager(), and QGestureRecognizer::registerRecognizer().
 {
     QGesture *dummy = recognizer->create(0);
     if (!dummy) {
         qWarning("QGestureManager::registerGestureRecognizer: "
                  "the recognizer fails to create a gesture object, skipping registration.");
         return Qt::GestureType(0);
     }
     Qt::GestureType type = dummy->gestureType();
     if (type == Qt::CustomGesture) {
         // generate a new custom gesture id
         ++m_lastCustomGestureId;
         type = Qt::GestureType(m_lastCustomGestureId);
     }
     m_recognizers.insertMulti(type, recognizer);
     delete dummy;
     return type;
 }
unregisterGestureRecognizer()
void QGestureManager::unregisterGestureRecognizer (Qt::GestureType type)
Definition at line 129 of file qgesturemanager.cpp.
Referenced by QGestureRecognizer::unregisterRecognizer().
 {
     QList<QGestureRecognizer *> list = m_recognizers.values(type);
     while (QGestureRecognizer *recognizer = m_recognizers.take(type)) {
         if (!m_obsoleteGestures.contains(recognizer)) {
             // inserting even an empty QSet will cause the recognizer to be deleted on destruction of the manager
             m_obsoleteGestures.insert(recognizer, QSet<QGesture *>());
         }
     }
     foreach (QGesture *g, m_gestureToRecognizer.keys()) {
         QGestureRecognizer *recognizer = m_gestureToRecognizer.value(g);
         if (list.contains(recognizer)) {
             m_deletedRecognizers.insert(g, recognizer);
         }
     }
     QMap<ObjectGesture, QList<QGesture *> >::const_iterator iter = m_objectGestures.begin();
     while (iter != m_objectGestures.end()) {
         ObjectGesture objectGesture = iter.key();
         if (objectGesture.gesture == type) {
             foreach (QGesture *g, iter.value()) {
                 if (QGestureRecognizer *recognizer = m_gestureToRecognizer.value(g)) {
                     m_gestureToRecognizer.remove(g);
                     m_obsoleteGestures[recognizer].insert(g);
                 }
             }
         }
         ++iter;
     }
 }
Properties
m_activeGestures
QSet<QGesture *> QGestureManager::m_activeGestures private
Definition at line 96 of file qgesturemanager_p.h.
Referenced by cancelGesturesForChildren(), cleanupCachedGestures(), filterEventThroughContexts(), and recycle().
m_deletedRecognizers
QHash<QGesture *, QGestureRecognizer *> QGestureManager::m_deletedRecognizers private
Definition at line 132 of file qgesturemanager_p.h.
Referenced by cleanupCachedGestures(), cleanupGesturesForRemovedRecognizer(), and unregisterGestureRecognizer().
m_gestureOwners
QHash<QGesture *, QObject *> QGestureManager::m_gestureOwners private
Definition at line 125 of file qgesturemanager_p.h.
Referenced by cleanupCachedGestures(), deliverEvents(), and getState().
m_gesturesToDelete
QSet<QGesture *> QGestureManager::m_gesturesToDelete private
Definition at line 133 of file qgesturemanager_p.h.
Referenced by cleanupCachedGestures(), and filterEventThroughContexts().
m_gestureTargets
QHash<QGesture *, QWidget *> QGestureManager::m_gestureTargets private
Definition at line 127 of file qgesturemanager_p.h.
Referenced by cancelGesturesForChildren(), cleanupCachedGestures(), deliverEvents(), filterEventThroughContexts(), and getGestureTargets().
m_gestureToRecognizer
QHash<QGesture *, QGestureRecognizer *> QGestureManager::m_gestureToRecognizer private
Definition at line 124 of file qgesturemanager_p.h.
Referenced by cleanupCachedGestures(), filterEvent(), getState(), recycle(), and unregisterGestureRecognizer().
m_lastCustomGestureId
int QGestureManager::m_lastCustomGestureId private
Definition at line 129 of file qgesturemanager_p.h.
Referenced by registerGestureRecognizer().
m_maybeGestures
QSet<QGesture *> QGestureManager::m_maybeGestures private
Definition at line 97 of file qgesturemanager_p.h.
Referenced by cleanupCachedGestures(), and filterEventThroughContexts().
m_objectGestures
QMap<ObjectGesture, QList<QGesture *> > QGestureManager::m_objectGestures private
Definition at line 123 of file qgesturemanager_p.h.
Referenced by cleanupCachedGestures(), getState(), and unregisterGestureRecognizer().
m_obsoleteGestures
QHash<QGestureRecognizer *, QSet<QGesture *> > QGestureManager::m_obsoleteGestures private
Definition at line 131 of file qgesturemanager_p.h.
Referenced by cleanupCachedGestures(), cleanupGesturesForRemovedRecognizer(), unregisterGestureRecognizer(), and ~QGestureManager().
m_recognizers
QMultiMap<Qt::GestureType, QGestureRecognizer *> QGestureManager::m_recognizers private
Definition at line 94 of file qgesturemanager_p.h.
Referenced by filterEventThroughContexts(), registerGestureRecognizer(), unregisterGestureRecognizer(), and ~QGestureManager().
state
enum QGestureManager::State QGestureManager::state private
Referenced by filterEvent(), filterEventThroughContexts(), and getState().
The documentation for this class was generated from the following files:
/src/gui/kernel/qgesturemanager_p.h
/src/gui/kernel/qapplication.cpp
/src/gui/kernel/qgesturemanager.cpp