Qt 4.8: QStrokerOps Class Reference
QStrokerOps Class Reference abstract
#include <qstroker_p.h>
Classes
struct Element
Public Functions
virtual void begin (void *customData)
Prepares the stroker.
QRectF clipRect () const
void cubicTo (qfixed x1, qfixed y1, qfixed x2, qfixed y2, qfixed ex, qfixed ey)
qfixed curveThreshold () const
virtual void end ()
Finishes the stroke.
void lineTo (qfixed x, qfixed y)
void moveTo (qfixed x, qfixed y)
QStrokerOps ()
void setClipRect (const QRectF &clip)
void setCubicToHook (qStrokerCubicToHook cubicToHook)
void setCurveThreshold (qfixed threshold)
void setCurveThresholdFromTransform (const QTransform &transform)
void setLineToHook (qStrokerLineToHook lineToHook)
void setMoveToHook (qStrokerMoveToHook moveToHook)
void strokeEllipse (const QRectF &ellipse, void *data, const QTransform &matrix)
Convenience function for stroking an ellipse with bounding rect rect.
void strokePath (const QPainterPath &path, void *data, const QTransform &matrix)
Convenience function that decomposes path into begin(), moveTo(), lineTo(), curevTo() and end() calls.
void strokePolygon (const QPointF *points, int pointCount, bool implicit_close, void *data, const QTransform &matrix)
Convenience function for stroking a polygon of the pointCount first points in points.
virtual ~QStrokerOps ()
Protected Functions
void emitCubicTo (qfixed c1x, qfixed c1y, qfixed c2x, qfixed c2y, qfixed ex, qfixed ey)
void emitLineTo (qfixed x, qfixed y)
void emitMoveTo (qfixed x, qfixed y)
virtual void processCurrentSubpath ()=0
Protected Variables
QRectF m_clip_rect
qStrokerCubicToHook m_cubicTo
qfixed m_curveThreshold
void * m_customData
qfixed m_dashThreshold
QDataBuffer< Element > m_elements
qStrokerLineToHook m_lineTo
qStrokerMoveToHook m_moveTo
Detailed Description
Definition at line 130 of file qstroker_p.h.
Constructors and Destructors
QStrokerOps()
QStrokerOps::QStrokerOps ()
Definition at line 190 of file qstroker.cpp.
     : m_elements(0)
     , m_curveThreshold(qt_real_to_fixed(0.25))
     , m_dashThreshold(qt_real_to_fixed(0.25))
     , m_customData(0)
     , m_moveTo(0)
     , m_lineTo(0)
     , m_cubicTo(0)
 {
 }
~QStrokerOps()
QStrokerOps::~QStrokerOps () virtual
Definition at line 201 of file qstroker.cpp.
 {
 }
Functions
begin()
void QStrokerOps::begin (void * customData) virtual
Prepares the stroker.
Call this function once before starting a stroke by calling moveTo, lineTo or cubicTo.
The customData is passed back through that callback functions and can be used by the user to for instance maintain state information.
Reimplemented in QDashStroker.
Definition at line 213 of file qstroker.cpp.
Referenced by QDashStroker::begin(), strokeEllipse(), strokePath(), and strokePolygon().
 {
     m_customData = customData;
     m_elements.reset();
 }
clipRect()
QRectF QStrokerOps::clipRect () const inline
Definition at line 164 of file qstroker_p.h.
Referenced by QPainterPathStroker::createStroke().
 { return m_clip_rect; }
cubicTo()
void QStrokerOps::cubicTo (qfixed x1, qfixed y1, qfixed x2, qfixed y2, qfixed ex, qfixed ey) inline
Definition at line 323 of file qstroker_p.h.
Referenced by strokeEllipse(), and strokePath().
 {
     Element c1 = { QPainterPath::CurveToElement, x1, y1 };
     Element c2 = { QPainterPath::CurveToDataElement, x2, y2 };
     Element e = { QPainterPath::CurveToDataElement, ex, ey };
     m_elements.add(c1);
     m_elements.add(c2);
     m_elements.add(e);
 }
curveThreshold()
qfixed QStrokerOps::curveThreshold () const inline
Definition at line 175 of file qstroker_p.h.
Referenced by qt_stroke_side().
 { return m_curveThreshold; }
emitCubicTo()
void QStrokerOps::emitCubicTo (qfixed c1x, qfixed c1y, qfixed c2x, qfixed c2y, qfixed ex, qfixed ey) inline protected
Definition at line 302 of file qstroker_p.h.
Referenced by QStroker::emitCubicTo().
 {
     Q_ASSERT(m_cubicTo);
     m_cubicTo(c1x, c1y, c2x, c2y, ex, ey, m_customData);
 }
emitLineTo()
void QStrokerOps::emitLineTo (qfixed x, qfixed y) inline protected
Definition at line 296 of file qstroker_p.h.
Referenced by QStroker::emitLineTo(), and QDashStroker::processCurrentSubpath().
 {
     Q_ASSERT(m_lineTo);
     m_lineTo(x, y, m_customData);
 }
emitMoveTo()
void QStrokerOps::emitMoveTo (qfixed x, qfixed y) inline protected
Definition at line 290 of file qstroker_p.h.
Referenced by QStroker::emitMoveTo(), and QDashStroker::processCurrentSubpath().
 {
     Q_ASSERT(m_moveTo);
     m_moveTo(x, y, m_customData);
 }
end()
void QStrokerOps::end () virtual
Finishes the stroke.
Call this function once when an entire primitive has been stroked.
Reimplemented in QDashStroker.
Definition at line 224 of file qstroker.cpp.
Referenced by QDashStroker::end(), qt_curves_for_arc(), strokeEllipse(), strokePath(), and strokePolygon().
 {
     if (m_elements.size() > 1)
         processCurrentSubpath();
     m_customData = 0;
 }
lineTo()
void QStrokerOps::lineTo (qfixed x, qfixed y) inline
Definition at line 317 of file qstroker_p.h.
Referenced by QDashedStrokeProcessor::process(), strokePath(), and strokePolygon().
 {
     Element e = { QPainterPath::LineToElement, x, y };
     m_elements.add(e);
 }
moveTo()
void QStrokerOps::moveTo (qfixed x, qfixed y) inline
Definition at line 308 of file qstroker_p.h.
Referenced by QDashedStrokeProcessor::process(), strokeEllipse(), strokePath(), and strokePolygon().
 {
     if (m_elements.size()>1)
         processCurrentSubpath();
     m_elements.reset();
     Element e = { QPainterPath::MoveToElement, x, y };
     m_elements.add(e);
 }
processCurrentSubpath()
virtual void QStrokerOps::processCurrentSubpath () protected pure virtual
Implemented in QDashStroker, and QStroker.
Referenced by end().
setClipRect()
void QStrokerOps::setClipRect (const QRectF & clip) inline
Definition at line 165 of file qstroker_p.h.
Referenced by QPainterPathStroker::createStroke(), QX11PaintEngine::drawPath(), and QDashedStrokeProcessor::process().
 { m_clip_rect = clip; }
setCubicToHook()
void QStrokerOps::setCubicToHook (qStrokerCubicToHook cubicToHook) inline
Definition at line 150 of file qstroker_p.h.
Referenced by QDashedStrokeProcessor::QDashedStrokeProcessor(), QDashStroker::QDashStroker(), QPainterPathStrokerPrivate::QPainterPathStrokerPrivate(), and QPdf::Stroker::Stroker().
 { m_cubicTo = cubicToHook; }
setCurveThreshold()
void QStrokerOps::setCurveThreshold (qfixed threshold) inline
Definition at line 174 of file qstroker_p.h.
 { m_curveThreshold = threshold; }
setCurveThresholdFromTransform()
void QStrokerOps::setCurveThresholdFromTransform (const QTransform & transform) inline
Definition at line 167 of file qstroker_p.h.
Referenced by strokeEllipse(), strokePath(), and strokePolygon().
     {
         qreal scale;
         qt_scaleForTransform(transform, &scale);
         m_dashThreshold = scale == 0 ? qreal(0.5) : (qreal(0.5) / scale);
     }
setLineToHook()
void QStrokerOps::setLineToHook (qStrokerLineToHook lineToHook) inline
Definition at line 149 of file qstroker_p.h.
Referenced by QDashedStrokeProcessor::QDashedStrokeProcessor(), QDashStroker::QDashStroker(), QPainterPathStrokerPrivate::QPainterPathStrokerPrivate(), and QPdf::Stroker::Stroker().
 { m_lineTo = lineToHook; }
setMoveToHook()
void QStrokerOps::setMoveToHook (qStrokerMoveToHook moveToHook) inline
Definition at line 148 of file qstroker_p.h.
Referenced by QDashedStrokeProcessor::QDashedStrokeProcessor(), QDashStroker::QDashStroker(), QPainterPathStrokerPrivate::QPainterPathStrokerPrivate(), and QPdf::Stroker::Stroker().
 { m_moveTo = moveToHook; }
strokeEllipse()
void QStrokerOps::strokeEllipse (const QRectF & rect, void * data, const QTransform & matrix)
Convenience function for stroking an ellipse with bounding rect rect.
The matrix is used to transform the coordinates before they enter the stroker.
Definition at line 346 of file qstroker.cpp.
 {
     int count = 0;
     QPointF pts[12];
     QPointF start = qt_curves_for_arc(rect, 0, -360, pts, &count);
     Q_ASSERT(count == 12); // a perfect circle..
     if (!matrix.isIdentity()) {
         start = start * matrix;
         for (int i=0; i<12; ++i) {
             pts[i] = pts[i] * matrix;
         }
     }
     setCurveThresholdFromTransform(QTransform());
     begin(data);
     moveTo(qt_real_to_fixed(start.x()), qt_real_to_fixed(start.y()));
     for (int i=0; i<12; i+=3) {
         cubicTo(qt_real_to_fixed(pts[i].x()), qt_real_to_fixed(pts[i].y()),
                 qt_real_to_fixed(pts[i+1].x()), qt_real_to_fixed(pts[i+1].y()),
                 qt_real_to_fixed(pts[i+2].x()), qt_real_to_fixed(pts[i+2].y()));
     }
     end();
 }
strokePath()
void QStrokerOps::strokePath (const QPainterPath & path, void * customData, const QTransform & matrix)
Convenience function that decomposes path into begin(), moveTo(), lineTo(), curevTo() and end() calls.
The customData parameter is used in the callback functions
The matrix is used to transform the points before input to the stroker.
See also
begin()
Definition at line 242 of file qstroker.cpp.
Referenced by QPainterPathStroker::createStroke(), and QPdf::Stroker::strokePath().
 {
     if (path.isEmpty())
         return;
     setCurveThresholdFromTransform(QTransform());
     begin(customData);
     int count = path.elementCount();
     if (matrix.isIdentity()) {
         for (int i=0; i<count; ++i) {
             const QPainterPath::Element &e = path.elementAt(i);
             switch (e.type) {
             case QPainterPath::MoveToElement:
                 moveTo(qt_real_to_fixed(e.x), qt_real_to_fixed(e.y));
                 break;
             case QPainterPath::LineToElement:
                 lineTo(qt_real_to_fixed(e.x), qt_real_to_fixed(e.y));
                 break;
             case QPainterPath::CurveToElement:
                 {
                     const QPainterPath::Element &cp2 = path.elementAt(++i);
                     const QPainterPath::Element &ep = path.elementAt(++i);
                     cubicTo(qt_real_to_fixed(e.x), qt_real_to_fixed(e.y),
                             qt_real_to_fixed(cp2.x), qt_real_to_fixed(cp2.y),
                             qt_real_to_fixed(ep.x), qt_real_to_fixed(ep.y));
                 }
                 break;
             default:
                 break;
             }
         }
     } else {
         for (int i=0; i<count; ++i) {
             const QPainterPath::Element &e = path.elementAt(i);
             QPointF pt = QPointF(e.x, e.y) * matrix;
             switch (e.type) {
             case QPainterPath::MoveToElement:
                 moveTo(qt_real_to_fixed(pt.x()), qt_real_to_fixed(pt.y()));
                 break;
             case QPainterPath::LineToElement:
                 lineTo(qt_real_to_fixed(pt.x()), qt_real_to_fixed(pt.y()));
                 break;
             case QPainterPath::CurveToElement:
                 {
                     QPointF cp2 = ((QPointF) path.elementAt(++i)) * matrix;
                     QPointF ep = ((QPointF) path.elementAt(++i)) * matrix;
                     cubicTo(qt_real_to_fixed(pt.x()), qt_real_to_fixed(pt.y()),
                             qt_real_to_fixed(cp2.x()), qt_real_to_fixed(cp2.y()),
                             qt_real_to_fixed(ep.x()), qt_real_to_fixed(ep.y()));
                 }
                 break;
             default:
                 break;
             }
         }
     }
     end();
 }
strokePolygon()
void QStrokerOps::strokePolygon (const QPointF * points, int pointCount, bool implicit_close, void * data, const QTransform & matrix)
Convenience function for stroking a polygon of the pointCount first points in points.
If implicit_close is set to true a line is implictly drawn between the first and last point in the polygon. Typically true for polygons and false for polylines.
The matrix is used to transform the points before they enter the stroker.
See also
begin()
Definition at line 313 of file qstroker.cpp.
 {
     if (!pointCount)
         return;
     setCurveThresholdFromTransform(QTransform());
     begin(data);
     if (matrix.isIdentity()) {
         moveTo(qt_real_to_fixed(points[0].x()), qt_real_to_fixed(points[0].y()));
         for (int i=1; i<pointCount; ++i)
             lineTo(qt_real_to_fixed(points[i].x()),
                    qt_real_to_fixed(points[i].y()));
         if (implicit_close)
             lineTo(qt_real_to_fixed(points[0].x()), qt_real_to_fixed(points[0].y()));
     } else {
         QPointF start = points[0] * matrix;
         moveTo(qt_real_to_fixed(start.x()), qt_real_to_fixed(start.y()));
         for (int i=1; i<pointCount; ++i) {
             QPointF pt = points[i] * matrix;
             lineTo(qt_real_to_fixed(pt.x()), qt_real_to_fixed(pt.y()));
         }
         if (implicit_close)
             lineTo(qt_real_to_fixed(start.x()), qt_real_to_fixed(start.y()));
     }
     end();
 }
Properties
m_clip_rect
QRectF QStrokerOps::m_clip_rect protected
Definition at line 185 of file qstroker_p.h.
Referenced by QDashStroker::processCurrentSubpath().
m_cubicTo
qStrokerCubicToHook QStrokerOps::m_cubicTo protected
Definition at line 192 of file qstroker_p.h.
m_curveThreshold
qfixed QStrokerOps::m_curveThreshold protected
Definition at line 186 of file qstroker_p.h.
m_customData
void* QStrokerOps::m_customData protected
Definition at line 189 of file qstroker_p.h.
Referenced by begin(), end(), and QDashStroker::processCurrentSubpath().
m_dashThreshold
qfixed QStrokerOps::m_dashThreshold protected
Definition at line 187 of file qstroker_p.h.
Referenced by QDashStroker::processCurrentSubpath().
m_elements
QDataBuffer<Element> QStrokerOps::m_elements protected
Definition at line 183 of file qstroker_p.h.
Referenced by begin(), end(), QStroker::processCurrentSubpath(), and QDashStroker::processCurrentSubpath().
m_lineTo
qStrokerLineToHook QStrokerOps::m_lineTo protected
Definition at line 191 of file qstroker_p.h.
m_moveTo
qStrokerMoveToHook QStrokerOps::m_moveTo protected
Definition at line 190 of file qstroker_p.h.
The documentation for this class was generated from the following files:
/src/gui/painting/qstroker_p.h
/src/gui/painting/qstroker.cpp