Qt 4.8: NamedNodeMap Class Reference
NamedNodeMap Class Reference
Public Functions
bool isNull ()
NamedNodeMap ()
NamedNodeMap (const NamedNodeMap &)
~NamedNodeMap ()
Static Public Functions
static QScriptValue create (QScriptEngine *, NodeImpl *, QList< NodeImpl *> *)
static QScriptValue length (QScriptContext *context, QScriptEngine *engine)
static QScriptValue prototype (QScriptEngine *)
Public Variables
NodeImpl * d
QList< NodeImpl * > * list
Private Functions
NamedNodeMap & operator= (const NamedNodeMap &)
Detailed Description
Definition at line 166 of file qdeclarativexmlhttprequest.cpp.
Constructors and Destructors
NamedNodeMap() [1/2]
NamedNodeMap::NamedNodeMap ()
Definition at line 776 of file qdeclarativexmlhttprequest.cpp.
 : d(0), list(0)
 {
 }
NamedNodeMap() [2/2]
NamedNodeMap::NamedNodeMap (const NamedNodeMap & o)
Definition at line 781 of file qdeclarativexmlhttprequest.cpp.
 : d(o.d), list(o.list)
 {
     if (d) A(d);
 }
~NamedNodeMap()
NamedNodeMap::~NamedNodeMap ()
Definition at line 787 of file qdeclarativexmlhttprequest.cpp.
 {
     if (d) D(d);
 }
Functions
create()
QScriptValue NamedNodeMap::create (QScriptEngine * engine, NodeImpl * data, QList< NodeImpl *> * list) static
Definition at line 756 of file qdeclarativexmlhttprequest.cpp.
Referenced by Node::attributes().
 {
     QScriptValue instance = engine->newObject();
     instance.setPrototype(NamedNodeMap::prototype(engine));
     NamedNodeMap map;
     map.d = data;
     map.list = list;
     if (data) A(data);
     instance.setData(engine->newVariant(QVariant::fromValue(map)));
     if (!QDeclarativeScriptEngine::get(engine)->namedNodeMapClass)
         QDeclarativeScriptEngine::get(engine)->namedNodeMapClass= new NamedNodeMapClass(engine);
     instance.setScriptClass(QDeclarativeScriptEngine::get(engine)->namedNodeMapClass);
     return instance;
 }
isNull()
bool NamedNodeMap::isNull ()
Definition at line 792 of file qdeclarativexmlhttprequest.cpp.
Referenced by length(), and NamedNodeMapClass::queryProperty().
 {
     return d == 0;
 }
length()
QScriptValue NamedNodeMap::length (QScriptContext * context, QScriptEngine * engine) static
Definition at line 739 of file qdeclarativexmlhttprequest.cpp.
Referenced by NodeList::prototype().
 {
     NamedNodeMap map = qscriptvalue_cast<NamedNodeMap>(context->thisObject().data());
     if (map.isNull()) return engine->undefinedValue();
     return QScriptValue(map.list->count());
 }
operator=()
NamedNodeMap& NamedNodeMap::operator= (const NamedNodeMap &) private
prototype()
QScriptValue NamedNodeMap::prototype (QScriptEngine * engine) static
Definition at line 747 of file qdeclarativexmlhttprequest.cpp.
Referenced by create().
 {
     QScriptValue proto = engine->newObject();
     proto.setProperty(QLatin1String("length"), engine->newFunction(length), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     return proto;
 }
Properties
d
NodeImpl* NamedNodeMap::d
Definition at line 181 of file qdeclarativexmlhttprequest.cpp.
Referenced by create(), isNull(), NamedNodeMap(), and ~NamedNodeMap().
list
QList<NodeImpl *>* NamedNodeMap::list
Definition at line 182 of file qdeclarativexmlhttprequest.cpp.
Referenced by create(), NodeList::create(), length(), NodeList::length(), NamedNodeMapClass::property(), and NamedNodeMapClass::queryProperty().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativexmlhttprequest.cpp