Qt 4.8: QSplitter Class Reference
QSplitter Class Reference
The QSplitter class implements a splitter widget.
#include <qsplitter.h>
Signals
void splitterMoved (int pos, int index)
This signal is emitted when the splitter handle at a particular index has been moved to position pos.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addWidget (QWidget *widget)
Adds the given widget to the splitter's layout after all the other items.
bool childrenCollapsible () const
int count () const
Returns the number of widgets contained in the splitter's layout.
void getRange (int index, int *, int *) const
Returns the valid range of the splitter with index index in {min} and *{max} if min and max are not 0.
QSplitterHandle * handle (int index) const
Returns the handle to the left (or above) for the item in the splitter's layout at the given index.
int handleWidth () const
int indexOf (QWidget *w) const
Returns the index in the splitter's layout of the specified widget.
void insertWidget (int index, QWidget *widget)
Inserts the widget specified into the splitter's layout at the given index.
bool isCollapsible (int index) const
Returns true if the widget at index is collapsible, otherwise returns false.
QSize minimumSizeHint () const
Reimplemented Function
bool opaqueResize () const
Qt::Orientation orientation () const
QSplitter (QWidget *parent=0)
Constructs a horizontal splitter with the parent argument passed on to the QFrame constructor.
QSplitter (Qt::Orientation, QWidget *parent=0)
Constructs a splitter with the given orientation and parent.
void refresh ()
Updates the splitter's state.
bool restoreState (const QByteArray &state)
Restores the splitter's layout to the state specified.
QByteArray saveState () const
Saves the state of the splitter's layout.
void setChildrenCollapsible (bool)
void setCollapsible (int index, bool)
Sets whether the child widget at index index is collapsible to collapse.
void setHandleWidth (int)
void setOpaqueResize (bool opaque=true)
void setOrientation (Qt::Orientation)
void setSizes (const QList< int > &list)
Sets the child widgets respective sizes to the values given in the list.
void setStretchFactor (int index, int stretch)
Updates the size policy of the widget at position index to have a stretch factor of stretch.
QSize sizeHint () const
Reimplemented Function
QList< int > sizes () const
Returns a list of the size parameters of all the widgets in this splitter.
QWidget * widget (int index) const
Returns the widget at the given index in the splitter's layout.
~QSplitter ()
Destroys the splitter.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *)
Reimplemented Function
void childEvent (QChildEvent *)
Tells the splitter that the child widget described by c has been inserted or removed.
int closestLegalPosition (int, int)
Returns the closest legal position to pos of the widget with index index.
virtual QSplitterHandle * createHandle ()
Returns a new splitter handle as a child widget of this splitter.
bool event (QEvent *)
Reimplemented Function
void moveSplitter (int pos, int index)
Moves the left or top edge of the splitter handle at index as close as possible to position pos, which is the distance from the left or top edge of the widget.
void resizeEvent (QResizeEvent *)
Reimplemented Function
void setRubberBand (int position)
Displays a rubber band at position pos.
Protected Functions inherited from QFrame
void drawFrame (QPainter *)
em>Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool childrenCollapsible
whether child widgets can be resized down to size 0 by the user
int handleWidth
the width of the splitter handles
bool opaqueResize
whether resizing is opaque
Qt::Orientation orientation
the orientation of the splitter
Friends
class QSplitterHandle
Related Functions
(Note that these are not member functions.)
QTextStream & operator<< (QTextStream &ts, const QSplitter &splitter)
Use ts << {splitter}.
QTextStream & operator>> (QTextStream &ts, QSplitter &splitter)
Use ts >> {splitter}.
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Additional Inherited Members
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Detailed Description
The QSplitter class implements a splitter widget.
A splitter lets the user control the size of child widgets by dragging the boundary between the children. Any number of widgets may be controlled by a single splitter. The typical use of a QSplitter is to create several widgets and add them using insertWidget() or addWidget().
The following example will show a QListView, QTreeView, and QTextEdit side by side, with two splitter handles:
    QSplitter *splitter = new QSplitter(parent);
    QListView *listview = new QListView;
    QTreeView *treeview = new QTreeView;
    QTextEdit *textedit = new QTextEdit;
    splitter->addWidget(listview);
    splitter->addWidget(treeview);
    splitter->addWidget(textedit);
If a widget is already inside a QSplitter when insertWidget() or addWidget() is called, it will move to the new position. This can be used to reorder widgets in the splitter later. You can use indexOf(), widget(), and count() to get access to the widgets inside the splitter.
A default QSplitter lays out its children horizontally (side by side); you can use setOrientation(Qt::Vertical) to lay its children out vertically.
By default, all widgets can be as large or as small as the user wishes, between the minimumSizeHint() (or minimumSize()) and maximumSize() of the widgets.
QSplitter resizes its children dynamically by default. If you would rather have QSplitter resize the children only at the end of a resize operation, call setOpaqueResize(false).
The initial distribution of size between the widgets is determined by multiplying the initial size with the stretch factor. You can also use setSizes() to set the sizes of all the widgets. The function sizes() returns the sizes set by the user. Alternatively, you can save and restore the sizes of the widgets from a QByteArray using saveState() and restoreState() respectively.
When you hide() a child its space will be distributed among the other children. It will be reinstated when you show() it again.
See also
QSplitterHandle, QHBoxLayout, QVBoxLayout, QTabWidget
Definition at line 62 of file qsplitter.h.
Constructors and Destructors
QSplitter() [1/2]
QSplitter::QSplitter (QWidget * parent = 0) explicit
Constructs a horizontal splitter with the parent argument passed on to the QFrame constructor.
See also
setOrientation()
Definition at line 1028 of file qsplitter.cpp.
Referenced by QSplitterPrivate::findWidget().
     : QFrame(*new QSplitterPrivate, parent)
 {
     Q_D(QSplitter);
     d->orient = Qt::Horizontal;
     d->init();
 }
QSplitter() [2/2]
QSplitter::QSplitter (Qt::Orientation orientation, QWidget * parent = 0) explicit
Constructs a splitter with the given orientation and parent.
See also
setOrientation()
Definition at line 1042 of file qsplitter.cpp.
     : QFrame(*new QSplitterPrivate, parent)
 {
     Q_D(QSplitter);
     d->orient = orientation;
     d->init();
 }
~QSplitter()
QSplitter::~QSplitter ()
Destroys the splitter.
All children are deleted.
Definition at line 1055 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     delete d->rubberBand;
     while (!d->list.isEmpty())
         delete d->list.takeFirst();
 }
Functions
addWidget()
void QSplitter::addWidget (QWidget * widget)
Adds the given widget to the splitter's layout after all the other items.
If widget is already in the splitter, it will be moved to the new position.
See also
insertWidget() widget() indexOf()
Definition at line 1194 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     insertWidget(d->list.count(), widget);
 }
changeEvent()
void QSplitter::changeEvent (QEvent * ev) protected virtual
Reimplemented Function
Reimplemented from QFrame.
Definition at line 1748 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     if(ev->type() == QEvent::StyleChange)
         d->updateHandles();
     QFrame::changeEvent(ev);
 }
childEvent()
void QSplitter::childEvent (QChildEvent * c) protected virtual
Tells the splitter that the child widget described by c has been inserted or removed.
Reimplemented Function
This method is also used to handle the situation where a widget is created with the splitter as a parent but not explicitly added with insertWidget() or addWidget(). This is for compatibility and not the recommended way of putting widgets into a splitter in new code. Please use insertWidget() or addWidget() in new code.
See also
addWidget() insertWidget()
Reimplemented from QObject.
Definition at line 1313 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     if (!c->child()->isWidgetType())
         return;
     QWidget *w = static_cast<QWidget*>(c->child());
     if (c->added() && !d->blockChildAdd && !w->isWindow() && !d->findWidget(w)) {
         d->insertWidget_helper(d->list.count(), w, false);
     } else if (c->polished() && !d->blockChildAdd) {
         if (isVisible() && !(w->isHidden() && w->testAttribute(Qt::WA_WState_ExplicitShowHide)))
             w->show();
     } else if (c->type() == QEvent::ChildRemoved) {
         for (int i = 0; i < d->list.size(); ++i) {
             QSplitterLayoutStruct *s = d->list.at(i);
             if (s->widget == w) {
                 d->list.removeAt(i);
                 delete s;
                 d->recalc(isVisible());
                 return;
             }
         }
     }
 }
childrenCollapsible()
bool QSplitter::childrenCollapsible () const
Referenced by saveState(), and setChildrenCollapsible().
closestLegalPosition()
int QSplitter::closestLegalPosition (int pos, int index) protected
Returns the closest legal position to pos of the widget with index index.
For right-to-left languages such as Arabic and Hebrew, the layout of horizontal splitters is reversed. Positions are then measured from the right edge of the widget.
See also
getRange()
Definition at line 1495 of file qsplitter.cpp.
Referenced by QSplitterHandle::closestLegalPosition().
 {
     Q_D(QSplitter);
     int x, i, n, u;
     return d->adjustPos(pos, index, &u, &n, &i, &x);
 }
count()
int QSplitter::count () const
Returns the number of widgets contained in the splitter's layout.
See also
widget(), handle()
Definition at line 1289 of file qsplitter.cpp.
Referenced by handleSplittersAttribute(), and moveSplitter().
 {
     Q_D(const QSplitter);
     return d->list.count();
 }
createHandle()
QSplitterHandle * QSplitter::createHandle () protected virtual
Returns a new splitter handle as a child widget of this splitter.
This function can be reimplemented in subclasses to provide support for custom handles.
See also
handle(), indexOf()
Definition at line 1246 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     return new QSplitterHandle(d->orient, this);
 }
event()
bool QSplitter::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QFrame.
Definition at line 1371 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     switch (e->type()) {
     case QEvent::Hide:
         // Reset firstShow to false here since things can be done to the splitter in between
         if (!d->firstShow)
             d->firstShow = true;
         break;
     case QEvent::Show:
         if (!d->firstShow)
             break;
         d->firstShow = false;
         // fall through
     case QEvent::HideToParent:
     case QEvent::ShowToParent:
     case QEvent::LayoutRequest:
 #ifdef QT3_SUPPORT
     case QEvent::LayoutHint:
 #endif
         d->recalc(isVisible());
         break;
     default:
         ;
     }
     return QWidget::event(e);
 }
getRange()
void QSplitter::getRange (int index, int * min, int * max) const
Returns the valid range of the splitter with index index in {min} and *{max} if min and max are not 0.
Definition at line 1477 of file qsplitter.cpp.
 {
     Q_D(const QSplitter);
     d->getRange(index, min, 0, 0, max);
 }
handle()
QSplitterHandle * QSplitter::handle (int index) const
Returns the handle to the left (or above) for the item in the splitter's layout at the given index.
The handle at index 0 is always hidden.
For right-to-left languages such as Arabic and Hebrew, the layout of horizontal splitters is reversed. The handle will be to the right of the widget at index.
See also
count(), widget(), indexOf(), createHandle(), setHandleWidth()
Definition at line 1263 of file qsplitter.cpp.
Referenced by handleSplittersAttribute().
 {
     Q_D(const QSplitter);
     if (index < 0 || index >= d->list.size())
         return 0;
     return d->list.at(index)->handle;
 }
handleWidth()
int QSplitter::handleWidth () const
Referenced by saveState(), setRubberBand(), and setSizes().
indexOf()
int QSplitter::indexOf (QWidget * widget) const
Returns the index in the splitter's layout of the specified widget.
This also works for handles.
Handles are numbered from 0. There are as many handles as there are child widgets, but the handle at position 0 is always hidden.
See also
count(), widget()
Definition at line 1228 of file qsplitter.cpp.
Referenced by QSplitterHandle::closestLegalPosition(), and handleSplitterContentsAttribute().
 {
     Q_D(const QSplitter);
     for (int i = 0; i < d->list.size(); ++i) {
         QSplitterLayoutStruct *s = d->list.at(i);
         if (s->widget == w || s->handle == w)
             return i;
     }
     return -1;
 }
insertWidget()
void QSplitter::insertWidget (int index, QWidget * widget)
Inserts the widget specified into the splitter's layout at the given index.
If widget is already in the splitter, it will be moved to the new position.
if index is an invalid index, then the widget will be inserted at the end.
See also
addWidget() indexOf() widget()
Definition at line 1210 of file qsplitter.cpp.
Referenced by addWidget().
 {
     Q_D(QSplitter);
     d->insertWidget_helper(index, widget, true);
 }
isCollapsible()
bool QSplitter::isCollapsible (int index) const
Returns true if the widget at index is collapsible, otherwise returns false.
Definition at line 1167 of file qsplitter.cpp.
 {
     Q_D(const QSplitter);
     if (index < 0 || index >= d->list.size()) {
         qWarning("QSplitter::isCollapsible: Index %d out of range", index);
         return false;
     }
     return d->list.at(index)->collapsible;
 }
minimumSizeHint()
QSize QSplitter::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1628 of file qsplitter.cpp.
 {
     Q_D(const QSplitter);
     ensurePolished();
     int l = 0;
     int t = 0;
     for (int i = 0; i < d->list.size(); ++i) {
         QSplitterLayoutStruct *s = d->list.at(i);
         if (!s || !s->widget)
             continue;
         if (s->widget->isHidden())
             continue;
         QSize widgetSize = qSmartMinSize(s->widget);
         if (widgetSize.isValid()) {
             l += d->pick(widgetSize);
             t = qMax(t, d->trans(widgetSize));
         }
         if (!s->handle || s->handle->isHidden())
             continue;
         QSize splitterSize = s->handle->sizeHint();
         if (splitterSize.isValid()) {
             l += d->pick(splitterSize);
             t = qMax(t, d->trans(splitterSize));
         }
     }
     return orientation() == Qt::Horizontal ? QSize(l, t) : QSize(t, l);
 }
moveSplitter()
void QSplitter::moveSplitter (int pos, int index) protected
Moves the left or top edge of the splitter handle at index as close as possible to position pos, which is the distance from the left or top edge of the widget.
For right-to-left languages such as Arabic and Hebrew, the layout of horizontal splitters is reversed. pos is then the distance from the right edge of the widget.
See also
splitterMoved(), closestLegalPosition(), getRange()
Definition at line 1426 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     QSplitterLayoutStruct *s = d->list.at(index);
     int farMin;
     int min;
     int max;
     int farMax;
 #ifdef QSPLITTER_DEBUG
     int debugp = pos;
 #endif
     pos = d->adjustPos(pos, index, &farMin, &min, &max, &farMax);
     int oldP = d->pick(s->rect.topLeft());
 #ifdef QSPLITTER_DEBUG
     qDebug() << "QSplitter::moveSplitter" << debugp << index << "adjusted" << pos << "oldP" << oldP;
 #endif
     QVarLengthArray<int, 32> poss(d->list.count());
     QVarLengthArray<int, 32> ws(d->list.count());
     bool upLeft;
     d->doMove(false, pos, index, +1, (d->collapsible(s) && (pos > max)), poss.data(), ws.data());
     d->doMove(true, pos, index - 1, +1, (d->collapsible(index - 1) && (pos < min)), poss.data(), ws.data());
     upLeft = (pos < oldP);
     int wid, delta, count = d->list.count();
     if (upLeft) {
         wid = 0;
         delta = 1;
     } else {
         wid = count - 1;
         delta = -1;
     }
     for (; wid >= 0 && wid < count; wid += delta) {
         QSplitterLayoutStruct *sls = d->list.at( wid );
         if (!sls->widget->isHidden())
             d->setGeo(sls, poss[wid], ws[wid], true);
     }
     d->storeSizes();
     emit splitterMoved(pos, index);
 }
opaqueResize()
bool QSplitter::opaqueResize () const
Referenced by closestLegalPosition(), and saveState().
orientation()
Qt::Orientation QSplitter::orientation () const
Referenced by minimumSizeHint(), QSplitter(), saveState(), setOrientation(), and sizeHint().
refresh()
void QSplitter::refresh ()
Updates the splitter's state.
You should not need to call this function.
Definition at line 1067 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     d->recalc(true);
 }
resizeEvent()
void QSplitter::resizeEvent (QResizeEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1180 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     d->doResize();
 }
restoreState()
bool QSplitter::restoreState (const QByteArray & state)
Restores the splitter's layout to the state specified.
Returns true if the state is restored; otherwise returns false.
Typically this is used in conjunction with QSettings to restore the size from a past session. Here is an example:
Restore the splitters's state:
    QSettings settings;
    splitter->restoreState(settings.value("splitterSizes").toByteArray());
A failure to restore the splitter's layout may result from either invalid or out-of-date data in the supplied byte array.
See also
saveState()
Definition at line 1807 of file qsplitter.cpp.
Referenced by operator>>().
 {
     Q_D(QSplitter);
     int version = 0;
     QByteArray sd = state;
     QDataStream stream(&sd, QIODevice::ReadOnly);
     QList<int> list;
     bool b;
     qint32 i;
     qint32 marker;
     qint32 v;
     stream >> marker;
     stream >> v;
     if (marker != SplitterMagic || v != version)
         return false;
     stream >> list;
     d->setSizes_helper(list, false);
     stream >> b;
     setChildrenCollapsible(b);
     stream >> i;
     setHandleWidth(i);
     stream >> b;
     setOpaqueResize(b);
     stream >> i;
     setOrientation(Qt::Orientation(i));
     d->doResize();
     return true;
 }
saveState()
QByteArray QSplitter::saveState () const
Saves the state of the splitter's layout.
Typically this is used in conjunction with QSettings to remember the size for a future session. A version number is stored as part of the data. Here is an example:
    QSettings settings;
    settings.setValue("splitterSizes", splitter->saveState());
See also
restoreState()
Definition at line 1769 of file qsplitter.cpp.
Referenced by operator<<().
 {
     Q_D(const QSplitter);
     int version = 0;
     QByteArray data;
     QDataStream stream(&data, QIODevice::WriteOnly);
     stream << qint32(SplitterMagic);
     stream << qint32(version);
     QList<int> list;
     for (int i = 0; i < d->list.size(); ++i) {
         QSplitterLayoutStruct *s = d->list.at(i);
         list.append(s->sizer);
     }
     stream << list;
     stream << childrenCollapsible();
     stream << qint32(handleWidth());
     stream << opaqueResize();
     stream << qint32(orientation());
     return data;
 }
setChildrenCollapsible()
void QSplitter::setChildrenCollapsible (bool collapse)
Definition at line 1129 of file qsplitter.cpp.
Referenced by restoreState().
 {
     Q_D(QSplitter);
     d->childrenCollapsible = collapse;
 }
setCollapsible()
void QSplitter::setCollapsible (int index, bool collapse)
Sets whether the child widget at index index is collapsible to collapse.
By default, children are collapsible, meaning that the user can resize them down to size 0, even if they have a non-zero minimumSize() or minimumSizeHint(). This behavior can be changed on a per-widget basis by calling this function, or globally for all the widgets in the splitter by setting the childrenCollapsible property.
See also
childrenCollapsible
Definition at line 1153 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     if (index < 0 || index >= d->list.size()) {
         qWarning("QSplitter::setCollapsible: Index %d out of range", index);
         return;
     }
     d->list.at(index)->collapsible = collapse ? 1 : 0;
 }
setHandleWidth()
void QSplitter::setHandleWidth (int width)
Definition at line 1738 of file qsplitter.cpp.
Referenced by restoreState().
 {
     Q_D(QSplitter);
     d->handleWidth = width;
     d->updateHandles();
 }
setOpaqueResize()
void QSplitter::setOpaqueResize (bool opaque = true)
Definition at line 1519 of file qsplitter.cpp.
Referenced by restoreState().
 {
     Q_D(QSplitter);
     d->opaque = on;
 }
setOrientation()
void QSplitter::setOrientation (Qt::Orientation orientation)
Definition at line 1087 of file qsplitter.cpp.
Referenced by restoreState().
 {
     Q_D(QSplitter);
     if (d->orient == orientation)
         return;
     if (!testAttribute(Qt::WA_WState_OwnSizePolicy)) {
         QSizePolicy sp = sizePolicy();
         sp.transpose();
         setSizePolicy(sp);
         setAttribute(Qt::WA_WState_OwnSizePolicy, false);
     }
     d->orient = orientation;
     for (int i = 0; i < d->list.size(); ++i) {
         QSplitterLayoutStruct *s = d->list.at(i);
         s->handle->setOrientation(orientation);
     }
     d->recalc(isVisible());
 }
setRubberBand()
void QSplitter::setRubberBand (int pos) protected
Displays a rubber band at position pos.
If pos is negative, the rubber band is removed.
Definition at line 1343 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     if (pos < 0) {
         if (d->rubberBand)
             d->rubberBand->deleteLater();
         return;
     }
     QRect r = contentsRect();
     const int rBord = 3; // customizable?
     int hw = handleWidth();
     if (!d->rubberBand) {
         QBoolBlocker b(d->blockChildAdd);
         d->rubberBand = new QRubberBand(QRubberBand::Line, this);
         // For accessibility to identify this special widget.
         d->rubberBand->setObjectName(QLatin1String("qt_rubberband"));
     }
     const QRect newGeom = d->orient == Qt::Horizontal ? QRect(QPoint(pos + hw / 2 - rBord, r.y()), QSize(2 * rBord, r.height()))
                                                       : QRect(QPoint(r.x(), pos + hw / 2 - rBord), QSize(r.width(), 2 * rBord));
     d->rubberBand->setGeometry(newGeom);
     d->rubberBand->show();
 }
setSizes()
void QSplitter::setSizes (const QList< int > & list)
Sets the child widgets respective sizes to the values given in the list.
If the splitter is horizontal, the values set the widths of each widget in pixels, from left to right. If the splitter is vertical, the heights of each widget is set, from top to bottom.
Extra values in the list are ignored. If list contains too few values, the result is undefined but the program will still be well-behaved.
The overall size of the splitter widget is not affected. Instead, any additional/missing space is distributed amongst the widgets according to the relative weight of the sizes.
If you specify a size of 0, the widget will be invisible. The size policies of the widgets are preserved. That is, a value smaller then the minimal size hint of the respective widget will be replaced by the value of the hint.
See also
sizes()
Definition at line 1708 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     d->setSizes_helper(list, true);
 }
setStretchFactor()
void QSplitter::setStretchFactor (int index, int stretch)
Updates the size policy of the widget at position index to have a stretch factor of stretch.
stretch is not the effective stretch factor; the effective stretch factor is calculated by taking the initial size of the widget and multiplying it with stretch.
This function is provided for convenience. It is equivalent to
QWidget *widget = splitter->widget(index);
QSizePolicy policy = widget->sizePolicy();
policy.setHorizontalStretch(stretch);
policy.setVerticalStretch(stretch);
widget->setSizePolicy(policy);
See also
setSizes(), widget()
Definition at line 1857 of file qsplitter.cpp.
 {
     Q_D(QSplitter);
     if (index <= -1 || index >= d->list.count())
         return;
     QWidget *widget = d->list.at(index)->widget;
     QSizePolicy sp = widget->sizePolicy();
     sp.setHorizontalStretch(stretch);
     sp.setVerticalStretch(stretch);
     widget->setSizePolicy(sp);
 }
sizeHint()
QSize QSplitter::sizeHint () const virtual
Reimplemented Function
Reimplemented from QFrame.
Definition at line 1604 of file qsplitter.cpp.
 {
     Q_D(const QSplitter);
     ensurePolished();
     int l = 0;
     int t = 0;
     for (int i = 0; i < d->list.size(); ++i) {
         QWidget *w = d->list.at(i)->widget;
         if (w->isHidden())
             continue;
         QSize s = w->sizeHint();
         if (s.isValid()) {
             l += d->pick(s);
             t = qMax(t, d->trans(s));
         }
     }
     return orientation() == Qt::Horizontal ? QSize(l, t) : QSize(t, l);
 }
sizes()
QList< int > QSplitter::sizes () const
Returns a list of the size parameters of all the widgets in this splitter.
If the splitter's orientation is horizontal, the list contains the widgets width in pixels, from left to right; if the orientation is vertical, the list contains the widgets height in pixels, from top to bottom.
Giving the values to another splitter's setSizes() function will produce a splitter with the same layout as this one.
Note that invisible widgets have a size of 0.
See also
setSizes()
Definition at line 1674 of file qsplitter.cpp.
 {
     Q_D(const QSplitter);
     ensurePolished();
     QList<int> list;
     for (int i = 0; i < d->list.size(); ++i) {
         QSplitterLayoutStruct *s = d->list.at(i);
         list.append(d->pick(s->rect.size()));
     }
     return list;
 }
splitterMoved
QSplitter::splitterMoved (int pos, int index) signal
This signal is emitted when the splitter handle at a particular index has been moved to position pos.
For right-to-left languages such as Arabic and Hebrew, the layout of horizontal splitters is reversed. pos is then the distance from the right edge of the widget.
See also
moveSplitter()
Referenced by moveSplitter().
widget()
QWidget * QSplitter::widget (int index) const
Returns the widget at the given index in the splitter's layout.
See also
count(), handle(), indexOf(), insertWidget()
Definition at line 1276 of file qsplitter.cpp.
Referenced by addWidget(), handleSplitterContentsAttribute(), and setStretchFactor().
 {
     Q_D(const QSplitter);
     if (index < 0 || index >= d->list.size())
         return 0;
     return d->list.at(index)->widget;
 }
Friends and Related Functions
operator<<()
QTextStream & operator<< (QTextStream & ts, const QSplitter & splitter) related
Use ts << {splitter}.
saveState() instead.
Definition at line 1883 of file qsplitter.cpp.
 {
     ts << splitter.saveState() << endl;
     return ts;
 }
operator>>()
QTextStream & operator>> (QTextStream & ts, QSplitter & splitter) related
Use ts >> {splitter}.
restoreState() instead.
Definition at line 1899 of file qsplitter.cpp.
 {
     QString line = ts.readLine();
     line = line.simplified();
     line.replace(QLatin1Char(' '), QString());
     line = line.toUpper();
     splitter.restoreState(line.toAscii());
     return ts;
 }
QSplitterHandle
friend class QSplitterHandle friend
Definition at line 147 of file qsplitter.h.
Referenced by createHandle().
Properties
childrenCollapsible
bool QSplitter::childrenCollapsible private
whether child widgets can be resized down to size 0 by the user
By default, children are collapsible. It is possible to enable and disable the collapsing of individual children using setCollapsible().
See also
setCollapsible()
Definition at line 69 of file qsplitter.h.
handleWidth
int QSplitter::handleWidth private
the width of the splitter handles
By default, this property contains a value that depends on the user's platform and style preferences.
If you set handleWidth to 1, the actual grab area will grow to overlap a few pixels of it's respective widgets.
Definition at line 68 of file qsplitter.h.
opaqueResize
bool QSplitter::opaqueResize private
whether resizing is opaque
Opaque resizing is on by default.
Definition at line 67 of file qsplitter.h.
orientation
Qt::Orientation QSplitter::orientation private
the orientation of the splitter
By default the orientation is horizontal (i.e., the widgets are laid out side by side). The possible orientations are Qt::Horizontal and Qt::Vertical.
See also
QSplitterHandle::orientation()
Definition at line 66 of file qsplitter.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qsplitter.h
/src/gui/widgets/qsplitter.cpp