Qt 4.8: QXmlQueryPrivate Class Reference
QXmlQueryPrivate Class Reference
#include <qxmlquery_p.h>
Public Functions
void addAdditionalNamespaceBinding (const QXmlName &binding)
void detach ()
QPatternist::DynamicContext::Ptr dynamicContext (QAbstractXmlReceiver *const callback=0)
QPatternist::Expression::Ptr expression (QIODevice *const queryDevice=0)
bool isValid ()
QObject * ownerObject ()
QXmlQueryPrivate (const QXmlNamePool &np=QXmlNamePool())
void recompileRequired ()
QPatternist::SequenceType::Ptr requiredType ()
QPatternist::AccelTreeResourceLoader::Ptr resourceLoader ()
void setExpressionFactory (const QPatternist::ExpressionFactory::Ptr &expr)
void setRequiredType (const QPatternist::SequenceType::Ptr &seqType)
QPatternist::GenericStaticContext::Ptr staticContext ()
QPatternist::VariableLoader::Ptr variableLoader ()
Public Variables
QXmlItem contextItem
QXmlName initialTemplateName
QList< QXmlName > m_additionalNamespaceBindings
QPatternist::Expression::Ptr m_expr
QPatternist::ExpressionFactory::Ptr m_expressionFactory
QPatternist::FunctionFactory::Ptr m_functionFactory
QPatternist::NetworkAccessDelegator::Ptr m_networkAccessDelegator
QPatternist::ReferenceCountedValue< QObject >::Ptr m_owner
QPatternist::SequenceType::Ptr m_requiredType
QPatternist::DeviceResourceLoader::Ptr m_resourceLoader
QPatternist::StaticContext::Ptr m_staticContext
QPatternist::VariableLoader::Ptr m_variableLoader
QPointer< QAbstractMessageHandler > messageHandler
QXmlNamePool namePool
QXmlQuery::QueryLanguage queryLanguage
QUrl queryURI
const QAbstractUriResolver * uriResolver
QPointer< QNetworkAccessManager > userNetworkManager
Detailed Description
Definition at line 84 of file qxmlquery_p.h.
Constructors and Destructors
QXmlQueryPrivate()
QXmlQueryPrivate::QXmlQueryPrivate (const QXmlNamePool & np = QXmlNamePool()) inline
Definition at line 88 of file qxmlquery_p.h.
                                                                      : namePool(np)
                                                                      , messageHandler(0)
                                                                      , uriResolver(0)
                                                                      , queryLanguage(QXmlQuery::XQuery10)
                                                                      , m_networkAccessDelegator(new QPatternist::NetworkAccessDelegator(0, 0))
     {
         m_networkAccessDelegator->m_variableURIManager = new QPatternist::URILoader(ownerObject(), namePool.d, variableLoader());
     }
Functions
addAdditionalNamespaceBinding()
void QXmlQueryPrivate::addAdditionalNamespaceBinding (const QXmlName & binding) inline
Definition at line 272 of file qxmlquery_p.h.
Referenced by QPatternist::XsdValidatingInstanceReader::createXQuery(), and QPatternist::XsdSchemaParser::readXPathAttribute().
     {
         m_additionalNamespaceBindings.append(binding);
     }
detach()
void QXmlQueryPrivate::detach () inline
Definition at line 97 of file qxmlquery_p.h.
Referenced by QXmlQuery::operator=(), and QXmlQuery::QXmlQuery().
     {
         if(m_variableLoader)
             m_variableLoader = QPatternist::VariableLoader::Ptr(new QPatternist::VariableLoader(namePool.d, m_variableLoader));
         delete m_networkAccessDelegator->m_variableURIManager;
         m_networkAccessDelegator->m_variableURIManager = new QPatternist::URILoader(ownerObject(), namePool.d, m_variableLoader);
         if(m_resourceLoader)
         {
             const QPatternist::AccelTreeResourceLoader::Ptr nev(new QPatternist::AccelTreeResourceLoader(namePool.d,
                                                                                                          m_networkAccessDelegator));
             m_resourceLoader = QPatternist::ResourceLoader::Ptr(new QPatternist::ResourceDelegator(m_resourceLoader->deviceURIs(),
                                                                                                    m_resourceLoader,
                                                                                                    nev));
         }
     }
dynamicContext()
QPatternist::DynamicContext::Ptr QXmlQueryPrivate::dynamicContext (QAbstractXmlReceiver *const callback = 0) inline
Definition at line 175 of file qxmlquery_p.h.
Referenced by QPatternist::VariableLoader::evaluateSequence(), and QXmlQuery::evaluateTo().
     {
         const QPatternist::StaticContext::Ptr statContext(staticContext());
         Q_ASSERT(statContext);
         QPatternist::GenericDynamicContext::Ptr dynContext(new QPatternist::GenericDynamicContext(namePool.d, statContext->messageHandler(),
                                                                                                   statContext->sourceLocations()));
         QPatternist::AutoPtr<QPatternist::NodeBuilder> nodeBuilder(new QPatternist::AccelTreeBuilder<false>(QUrl(), QUrl(), namePool.d,
                                                                                                             dynContext.data()));
         dynContext->setNodeBuilder(nodeBuilder);
         dynContext->setResourceLoader(statContext->resourceLoader());
         dynContext->setExternalVariableLoader(statContext->externalVariableLoader());
         dynContext->setUriResolver(uriResolver);
         if(callback)
             dynContext->setOutputReceiver(callback);
         if(contextItem.isNull())
             return dynContext;
         else
         {
             QPatternist::DynamicContext::Ptr focus(new QPatternist::Focus(dynContext));
             QPatternist::Item::Iterator::Ptr it(QPatternist::makeSingletonIterator(QPatternist::Item::fromPublic(contextItem)));
             it->next();
             focus->setFocusIterator(it);
             return focus;
         }
     }
expression()
QPatternist::Expression::Ptr QXmlQueryPrivate::expression (QIODevice *const queryDevice = 0) inline
Definition at line 235 of file qxmlquery_p.h.
Referenced by QPatternist::VariableLoader::announceExternalVariable(), QPatternist::VariableLoader::evaluateSequence(), QXmlQuery::evaluateTo(), isValid(), and QXmlQuery::setQuery().
     {
         if(m_expr && !queryDevice)
             return m_expr;
         /* If we need to update, but we don't have any source code, we can
          * never create an Expression. */
         if(!queryDevice)
             return QPatternist::Expression::Ptr();
         try
         {
             /* The static context has source locations, and they need to be
              * updated to the new query. */
             m_staticContext.reset();
             if(!m_expressionFactory)
                 m_expressionFactory = QPatternist::ExpressionFactory::Ptr(new QPatternist::ExpressionFactory());
             m_expr = m_expressionFactory->createExpression(queryDevice, staticContext(),
                                                            queryLanguage,
                                                            requiredType(),
                                                            queryURI,
                                                            initialTemplateName);
         }
         catch(const QPatternist::Exception)
         {
             m_expr.reset();
             /* We don't call m_staticContext.reset() because it shouldn't be
              * necessary, since m_staticContext is changed when the expression
              * is changed. */
         }
         return m_expr;
     }
isValid()
bool QXmlQueryPrivate::isValid () inline
Definition at line 115 of file qxmlquery_p.h.
Referenced by QXmlQuery::isValid().
     {
         return expression();
     }
ownerObject()
QObject* QXmlQueryPrivate::ownerObject () inline
Definition at line 295 of file qxmlquery_p.h.
Referenced by detach(), QXmlQueryPrivate(), and staticContext().
     {
         if(!m_owner)
             m_owner = new QPatternist::ReferenceCountedValue<QObject>(new QObject());
         return m_owner->value;
     }
recompileRequired()
void QXmlQueryPrivate::recompileRequired () inline
Definition at line 120 of file qxmlquery_p.h.
Referenced by QXmlQuery::bindVariable(), and QXmlQuery::setQuery().
     {
         m_expr.reset();
     }
requiredType()
QPatternist::SequenceType::Ptr QXmlQueryPrivate::requiredType () inline
Definition at line 224 of file qxmlquery_p.h.
Referenced by expression().
     {
         if(m_requiredType)
             return m_requiredType;
         else
         {
             m_requiredType = QPatternist::CommonSequenceTypes::ZeroOrMoreItems;
             return m_requiredType;
         }
     }
resourceLoader()
QPatternist::AccelTreeResourceLoader::Ptr QXmlQueryPrivate::resourceLoader () inline
Definition at line 206 of file qxmlquery_p.h.
Referenced by QXmlQuery::bindVariable(), and staticContext().
     {
         if(!m_resourceLoader)
             m_resourceLoader = (new QPatternist::AccelTreeResourceLoader(namePool.d, m_networkAccessDelegator));
         return m_resourceLoader;
     }
setExpressionFactory()
void QXmlQueryPrivate::setExpressionFactory (const QPatternist::ExpressionFactory::Ptr & expr) inline
Definition at line 287 of file qxmlquery_p.h.
     {
         m_expressionFactory = expr;
     }
setRequiredType()
void QXmlQueryPrivate::setRequiredType (const QPatternist::SequenceType::Ptr & seqType) inline
Definition at line 214 of file qxmlquery_p.h.
     {
         Q_ASSERT(seqType);
         if(!m_requiredType || m_requiredType->is(seqType))
             return;
         m_requiredType = seqType;
         m_staticContext.reset();
     }
staticContext()
QPatternist::GenericStaticContext::Ptr QXmlQueryPrivate::staticContext () inline
Definition at line 133 of file qxmlquery_p.h.
Referenced by dynamicContext(), expression(), and QXmlQuery::setQuery().
     {
         if(m_staticContext && m_expr)
             return m_staticContext;
         /* Else, re-create the staticContext. */
         if(!messageHandler)
             messageHandler = new QPatternist::ColoringMessageHandler(ownerObject());
         if(!m_functionFactory)
         {
             if(queryLanguage == QXmlQuery::XSLT20)
                 m_functionFactory = QPatternist::FunctionFactoryCollection::xslt20Factory(namePool.d);
             else
                 m_functionFactory = QPatternist::FunctionFactoryCollection::xpath20Factory(namePool.d);
         }
         const QPatternist::GenericStaticContext::Ptr genericStaticContext(new QPatternist::GenericStaticContext(namePool.d,
                                                                                                                 messageHandler,
                                                                                                                 queryURI,
                                                                                                                 m_functionFactory,
                                                                                                                 queryLanguage));
         genericStaticContext->setResourceLoader(resourceLoader());
         genericStaticContext->setExternalVariableLoader(variableLoader());
         m_staticContext = genericStaticContext;
         if(!contextItem.isNull())
             m_staticContext = QPatternist::StaticContext::Ptr(new QPatternist::StaticFocusContext(QPatternist::AtomicValue::qtToXDMType(contextItem), m_staticContext));
         else if(   queryLanguage == QXmlQuery::XmlSchema11IdentityConstraintField
                 || queryLanguage == QXmlQuery::XmlSchema11IdentityConstraintSelector
                 || queryLanguage == QXmlQuery::XPath20)
             m_staticContext = QPatternist::StaticContext::Ptr(new QPatternist::StaticFocusContext(QPatternist::BuiltinTypes::node, m_staticContext));
         for (int i = 0; i < m_additionalNamespaceBindings.count(); ++i) {
             m_staticContext->namespaceBindings()->addBinding(m_additionalNamespaceBindings.at(i));
         }
         return m_staticContext;
     }
variableLoader()
QPatternist::VariableLoader::Ptr QXmlQueryPrivate::variableLoader () inline
Definition at line 125 of file qxmlquery_p.h.
Referenced by QXmlQuery::bindVariable(), QXmlQueryPrivate(), and staticContext().
     {
         if(!m_variableLoader)
             m_variableLoader = QPatternist::VariableLoader::Ptr(new QPatternist::VariableLoader(namePool.d));
         return m_variableLoader;
     }
Properties
contextItem
QXmlItem QXmlQueryPrivate::contextItem
Definition at line 284 of file qxmlquery_p.h.
Referenced by dynamicContext(), QXmlQuery::setFocus(), and staticContext().
initialTemplateName
QXmlName QXmlQueryPrivate::initialTemplateName
Definition at line 285 of file qxmlquery_p.h.
Referenced by expression(), QXmlQuery::initialTemplateName(), and QXmlQuery::setInitialTemplateName().
m_additionalNamespaceBindings
QList<QXmlName> QXmlQueryPrivate::m_additionalNamespaceBindings
Definition at line 321 of file qxmlquery_p.h.
Referenced by addAdditionalNamespaceBinding(), and staticContext().
m_expr
QPatternist::Expression::Ptr QXmlQueryPrivate::m_expr
This is the AST for the query.
Definition at line 310 of file qxmlquery_p.h.
Referenced by expression(), recompileRequired(), and staticContext().
m_expressionFactory
QPatternist::ExpressionFactory::Ptr QXmlQueryPrivate::m_expressionFactory
Definition at line 303 of file qxmlquery_p.h.
Referenced by expression(), and setExpressionFactory().
m_functionFactory
QPatternist::FunctionFactory::Ptr QXmlQueryPrivate::m_functionFactory
Definition at line 318 of file qxmlquery_p.h.
Referenced by staticContext().
m_networkAccessDelegator
QPatternist::NetworkAccessDelegator::Ptr QXmlQueryPrivate::m_networkAccessDelegator
Definition at line 319 of file qxmlquery_p.h.
Referenced by detach(), QXmlQuery::networkAccessManager(), QXmlQueryPrivate(), resourceLoader(), QXmlQuery::setNetworkAccessManager(), and QXmlQuery::setQuery().
m_owner
QPatternist::ReferenceCountedValue<QObject>::Ptr QXmlQueryPrivate::m_owner
Definition at line 311 of file qxmlquery_p.h.
Referenced by ownerObject().
m_requiredType
QPatternist::SequenceType::Ptr QXmlQueryPrivate::m_requiredType
This is our effective network manager, that we end up using. The one the user sets is userNetworkManager.
Definition at line 317 of file qxmlquery_p.h.
Referenced by requiredType(), and setRequiredType().
m_resourceLoader
QPatternist::DeviceResourceLoader::Ptr QXmlQueryPrivate::m_resourceLoader
Definition at line 306 of file qxmlquery_p.h.
Referenced by detach(), and resourceLoader().
m_staticContext
QPatternist::StaticContext::Ptr QXmlQueryPrivate::m_staticContext
Definition at line 304 of file qxmlquery_p.h.
Referenced by expression(), setRequiredType(), and staticContext().
m_variableLoader
QPatternist::VariableLoader::Ptr QXmlQueryPrivate::m_variableLoader
Definition at line 305 of file qxmlquery_p.h.
Referenced by detach(), and variableLoader().
messageHandler
QPointer<QAbstractMessageHandler> QXmlQueryPrivate::messageHandler
Definition at line 278 of file qxmlquery_p.h.
Referenced by QXmlQuery::messageHandler(), QXmlQuery::setMessageHandler(), and staticContext().
namePool
QXmlNamePool QXmlQueryPrivate::namePool
Definition at line 277 of file qxmlquery_p.h.
Referenced by QXmlQuery::bindVariable(), detach(), dynamicContext(), QXmlQuery::namePool(), QXmlQueryPrivate(), resourceLoader(), QXmlQuery::setInitialTemplateName(), staticContext(), and variableLoader().
queryLanguage
QXmlQuery::QueryLanguage QXmlQueryPrivate::queryLanguage
Definition at line 292 of file qxmlquery_p.h.
Referenced by expression(), QXmlQuery::queryLanguage(), QXmlQuery::QXmlQuery(), and staticContext().
queryURI
QUrl QXmlQueryPrivate::queryURI
Must be absolute and valid.
Definition at line 282 of file qxmlquery_p.h.
Referenced by expression(), QXmlQuery::setQuery(), and staticContext().
uriResolver
const QAbstractUriResolver* QXmlQueryPrivate::uriResolver
Definition at line 283 of file qxmlquery_p.h.
Referenced by dynamicContext(), QXmlQuery::setUriResolver(), and QXmlQuery::uriResolver().
userNetworkManager
QPointer<QNetworkAccessManager> QXmlQueryPrivate::userNetworkManager
Definition at line 293 of file qxmlquery_p.h.
The documentation for this class was generated from the following file:
/src/xmlpatterns/api/qxmlquery_p.h