Qt 4.8: QMacFontPath Class Reference
QMacFontPath Class Reference
Public Functions
void advance (float _x)
QMacFontPath (float _x, float _y, QPainterPath *_path)
void setPosition (float _x, float _y)
Static Public Functions
static OSStatus closePath (void *)
static OSStatus cubicTo (const Float32Point *, const Float32Point *, const Float32Point *, void *)
static OSStatus lineTo (const Float32Point *, void *)
static OSStatus moveTo (const Float32Point *, void *)
Properties
QPainterPath * path
float x
float y
Detailed Description
Definition at line 77 of file qfontengine_mac.mm.
Constructors and Destructors
QMacFontPath()
QMacFontPath::QMacFontPath (float _x, float _y, QPainterPath * _path) inline
Definition at line 82 of file qfontengine_mac.mm.
 : x(_x), y(_y), path(_path) { }
Functions
advance()
void QMacFontPath::advance (float _x) inline
Definition at line 84 of file qfontengine_mac.mm.
 { x += _x; }
closePath()
OSStatus QMacFontPath::closePath (void * data) static
Definition at line 118 of file qfontengine_mac.mm.
Referenced by addGlyphsToPathHelper(), and advance().
 {
     static_cast<QMacFontPath*>(data)->path->closeSubpath();
     return noErr;
 }
cubicTo()
OSStatus QMacFontPath::cubicTo (const Float32Point * cp1, const Float32Point * cp2, const Float32Point * ep, void * data) static
Definition at line 100 of file qfontengine_mac.mm.
Referenced by addGlyphsToPathHelper(), and advance().
 {
     QMacFontPath *p = static_cast<QMacFontPath*>(data);
     p->path->cubicTo(p->x + cp1->x, p->y + cp1->y,
                      p->x + cp2->x, p->y + cp2->y,
                      p->x + ep->x, p->y + ep->y);
     return noErr;
 }
lineTo()
OSStatus QMacFontPath::lineTo (const Float32Point * pt, void * data) static
Definition at line 92 of file qfontengine_mac.mm.
Referenced by addGlyphsToPathHelper(), and advance().
 {
     QMacFontPath *p = static_cast<QMacFontPath*>(data);
     p->path->lineTo(p->x + pt->x, p->y + pt->y);
     return noErr;
 }
moveTo()
OSStatus QMacFontPath::moveTo (const Float32Point * pt, void * data) static
Definition at line 111 of file qfontengine_mac.mm.
Referenced by addGlyphsToPathHelper(), and advance().
 {
     QMacFontPath *p = static_cast<QMacFontPath*>(data);
     p->path->moveTo(p->x + pt->x, p->y + pt->y);
     return noErr;
 }
setPosition()
void QMacFontPath::setPosition (float _x, float _y) inline
Definition at line 83 of file qfontengine_mac.mm.
Referenced by addGlyphsToPathHelper().
 { x = _x; y = _y; }
Properties
path
QPainterPath* QMacFontPath::path private
Definition at line 80 of file qfontengine_mac.mm.
Referenced by closePath(), cubicTo(), lineTo(), and moveTo().
x
float QMacFontPath::x private
Definition at line 79 of file qfontengine_mac.mm.
Referenced by cubicTo(), lineTo(), and moveTo().
y
float QMacFontPath::y private
Definition at line 79 of file qfontengine_mac.mm.
Referenced by cubicTo(), lineTo(), and moveTo().
The documentation for this class was generated from the following file:
/src/gui/text/qfontengine_mac.mm