Qt 4.8: QEventDispatcherWin32 Class Reference
QEventDispatcherWin32 Class Reference
#include <qeventdispatcher_win_p.h>
Public Functions
void activateEventNotifiers ()
void closingDown ()
bool event (QEvent *e)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
void flush ()
Flushes the event queue.
bool hasPendingEvents ()
Returns true if there is an event waiting; otherwise returns false.
void interrupt ()
Interrupts event dispatching; i.
bool QT_ENSURE_STACK_ALIGNED_FOR_SSE processEvents (QEventLoop::ProcessEventsFlags flags)
Processes pending events that match flags until there are no more events to process.
QEventDispatcherWin32 (QObject *parent=0)
QList< TimerInfo > registeredTimers (QObject *object) const
Returns a list of registered timers for object.
bool registerEventNotifier (QWinEventNotifier *notifier)
void registerSocketNotifier (QSocketNotifier *notifier)
Registers notifier with the event loop.
void registerTimer (int timerId, int interval, QObject *object)
Register a timer with the specified timerId and interval for the given object.
void startingUp ()
void unregisterEventNotifier (QWinEventNotifier *notifier)
void unregisterSocketNotifier (QSocketNotifier *notifier)
Unregisters notifier from the event dispatcher.
bool unregisterTimer (int timerId)
Unregisters the timer with the given timerId.
bool unregisterTimers (QObject *object)
Unregisters all the timers associated with the given object.
void wakeUp ()
Wakes up the event loop.
~QEventDispatcherWin32 ()
Public Functions inherited from QAbstractEventDispatcher
bool filterEvent (void *message)
Sends message through the event filter that was set by setEventFilter().
QAbstractEventDispatcher (QObject *parent=0)
Constructs a new event dispatcher with the given parent.
int registerTimer (int interval, QObject *object)
Registers a timer with the specified interval for the given object.
EventFilter setEventFilter (EventFilter filter)
Replaces the event filter function for this QAbstractEventDispatcher with filter and returns the replaced event filter function.
~QAbstractEventDispatcher ()
Destroys the event dispatcher.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
void createInternalHwnd ()
Friends
class QGuiEventDispatcherWin32
LRESULT QT_WIN_CALLBACK qt_GetMessageHook (int, WPARAM, LPARAM)
LRESULT QT_WIN_CALLBACK qt_internal_proc (HWND hwnd, UINT message, WPARAM wp, LPARAM lp)
Additional Inherited Members
Public Types inherited from QAbstractEventDispatcher
typedef bool(* EventFilter) (void *message)
Typedef for a function with the signature.
typedef QPair< int, int > TimerInfo
Typedef for QPair<int, int>.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractEventDispatcher
void aboutToBlock ()
This signal is emitted before the event loop calls a function that could block.
void awake ()
This signal is emitted after the event loop returns from a function that could block.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QAbstractEventDispatcher
static QAbstractEventDispatcher * instance (QThread *thread=0)
Returns a pointer to the event dispatcher object for the specified thread.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QAbstractEventDispatcher
QAbstractEventDispatcher (QAbstractEventDispatcherPrivate &, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 67 of file qeventdispatcher_win_p.h.
Constructors and Destructors
QEventDispatcherWin32()
QEventDispatcherWin32::QEventDispatcherWin32 (QObject * parent = 0) explicit
Definition at line 712 of file qeventdispatcher_win.cpp.
Referenced by QGuiEventDispatcherWin32::processEvents().
     : QAbstractEventDispatcher(*new QEventDispatcherWin32Private, parent)
 {
 }
~QEventDispatcherWin32()
QEventDispatcherWin32::~QEventDispatcherWin32 ()
Definition at line 717 of file qeventdispatcher_win.cpp.
 {
 }
Functions
activateEventNotifiers()
void QEventDispatcherWin32::activateEventNotifiers ()
Definition at line 1076 of file qeventdispatcher_win.cpp.
 {
     Q_D(QEventDispatcherWin32);
     //### this could break if events are removed/added in the activation
     for (int i=0; i<d->winEventNotifierList.count(); i++) {
 #if !defined(Q_OS_WINCE)
         if (WaitForSingleObjectEx(d->winEventNotifierList.at(i)->handle(), 0, TRUE) == WAIT_OBJECT_0)
             d->activateEventNotifier(d->winEventNotifierList.at(i));
 #else
         if (WaitForSingleObject(d->winEventNotifierList.at(i)->handle(), 0) == WAIT_OBJECT_0)
             d->activateEventNotifier(d->winEventNotifierList.at(i));
 #endif
     }
 }
closingDown()
void QEventDispatcherWin32::closingDown () virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractEventDispatcher.
Definition at line 1114 of file qeventdispatcher_win.cpp.
 {
     Q_D(QEventDispatcherWin32);
     // clean up any socketnotifiers
     while (!d->sn_read.isEmpty())
         unregisterSocketNotifier((*(d->sn_read.begin()))->obj);
     while (!d->sn_write.isEmpty())
         unregisterSocketNotifier((*(d->sn_write.begin()))->obj);
     while (!d->sn_except.isEmpty())
         unregisterSocketNotifier((*(d->sn_except.begin()))->obj);
     // clean up any timers
     for (int i = 0; i < d->timerVec.count(); ++i)
         d->unregisterTimer(d->timerVec.at(i), true);
     d->timerVec.clear();
     d->timerDict.clear();
 #ifndef Q_OS_WINCE
     if (d->getMessageHook)
         UnhookWindowsHookEx(d->getMessageHook);
     d->getMessageHook = 0;
 #endif
 }
createInternalHwnd()
void QEventDispatcherWin32::createInternalHwnd () private
Definition at line 680 of file qeventdispatcher_win.cpp.
Referenced by processEvents(), and QGuiEventDispatcherWin32::QGuiEventDispatcherWin32().
 {
     Q_D(QEventDispatcherWin32);
     Q_ASSERT(!d->internalHwnd);
     if (d->internalHwnd)
         return;
     d->internalHwnd = qt_create_internal_window(this);
 #ifndef Q_OS_WINCE
     // setup GetMessage hook needed to drive our posted events
     d->getMessageHook = SetWindowsHookEx(WH_GETMESSAGE, (HOOKPROC) qt_GetMessageHook, NULL, GetCurrentThreadId());
     if (!d->getMessageHook) {
         qFatal("Qt: INTERNALL ERROR: failed to install GetMessage hook");
     }
 #endif
     // register all socket notifiers
     QList<int> sockets = (d->sn_read.keys().toSet()
                           + d->sn_write.keys().toSet()
                           + d->sn_except.keys().toSet()).toList();
     for (int i = 0; i < sockets.count(); ++i)
         d->doWsaAsyncSelect(sockets.at(i));
     // start all normal timers
     for (int i = 0; i < d->timerVec.count(); ++i)
         d->registerTimer(d->timerVec.at(i));
     // trigger a call to sendPostedEvents()
     wakeUp();
 }
event()
bool QEventDispatcherWin32::event (QEvent * e) virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 1139 of file qeventdispatcher_win.cpp.
Referenced by QETWidget::translateGestureEvent().
 {
     Q_D(QEventDispatcherWin32);
     if (e->type() == QEvent::ZeroTimerEvent) {
         QZeroTimerEvent *zte = static_cast<QZeroTimerEvent*>(e);
         WinTimerInfo *t = d->timerDict.value(zte->timerId());
         if (t) {
             t->inTimerEvent = true;
             QTimerEvent te(zte->timerId());
             QCoreApplication::sendEvent(t->obj, &te);
             t = d->timerDict.value(zte->timerId());
             if (t) {
                 if (t->interval == 0 && t->inTimerEvent) {
                     // post the next zero timer event as long as the timer was not restarted
                     QCoreApplication::postEvent(this, new QZeroTimerEvent(zte->timerId()));
                 }
                 t->inTimerEvent = false;
             }
         }
         return true;
     } else if (e->type() == QEvent::Timer) {
         QTimerEvent *te = static_cast<QTimerEvent*>(e);
         d->sendTimerEvent(te->timerId());
     }
     return QAbstractEventDispatcher::event(e);
 }
flush()
void QEventDispatcherWin32::flush () virtual
Flushes the event queue.
This normally returns almost immediately. Does nothing on platforms other than X11.
Implements QAbstractEventDispatcher.
Definition at line 1108 of file qeventdispatcher_win.cpp.
 { }
hasPendingEvents()
bool QEventDispatcherWin32::hasPendingEvents () virtual
Returns true if there is an event waiting; otherwise returns false.
Implements QAbstractEventDispatcher.
Definition at line 864 of file qeventdispatcher_win.cpp.
 {
     MSG msg;
     return qGlobalPostedEventsCount() || PeekMessage(&msg, NULL, 0, 0, PM_NOREMOVE);
 }
interrupt()
void QEventDispatcherWin32::interrupt () virtual
Interrupts event dispatching; i.
e. the event dispatcher will return from processEvents() as soon as possible.
Implements QAbstractEventDispatcher.
Definition at line 1101 of file qeventdispatcher_win.cpp.
 {
     Q_D(QEventDispatcherWin32);
     d->interrupt = true;
     wakeUp();
 }
processEvents()
bool QEventDispatcherWin32::processEvents (QEventLoop::ProcessEventsFlags flags) virtual
Processes pending events that match flags until there are no more events to process.
Returns true if an event was processed; otherwise returns false.
This function is especially useful if you have a long running operation and want to show its progress without allowing user input; i.e. by using the QEventLoop::ExcludeUserInputEvents flag.
If the QEventLoop::WaitForMoreEvents flag is set in flags, the behavior of this function is as follows:
If events are available, this function returns after processing them.
If no events are available, this function will wait until more are available and return after processing newly available events.
If the QEventLoop::WaitForMoreEvents flag is not set in flags, and no events are available, this function will return immediately.
Note: This function does not process events continuously; it returns after all available events are processed.
See also
hasPendingEvents()
Implements QAbstractEventDispatcher.
Reimplemented in QGuiEventDispatcherWin32.
Definition at line 721 of file qeventdispatcher_win.cpp.
Referenced by QGuiEventDispatcherWin32::processEvents().
 {
     Q_D(QEventDispatcherWin32);
     if (!d->internalHwnd)
         createInternalHwnd();
     d->interrupt = false;
     emit awake();
     bool canWait;
     bool retVal = false;
     bool seenWM_QT_SENDPOSTEDEVENTS = false;
     bool needWM_QT_SENDPOSTEDEVENTS = false;
     do {
         DWORD waitRet = 0;
         HANDLE pHandles[MAXIMUM_WAIT_OBJECTS - 1];
         QVarLengthArray<MSG> processedTimers;
         while (!d->interrupt) {
             DWORD nCount = d->winEventNotifierList.count();
             Q_ASSERT(nCount < MAXIMUM_WAIT_OBJECTS - 1);
             MSG msg;
             bool haveMessage;
             if (!(flags & QEventLoop::ExcludeUserInputEvents) && !d->queuedUserInputEvents.isEmpty()) {
                 // process queued user input events
                 haveMessage = true;
                 msg = d->queuedUserInputEvents.takeFirst();
             } else if(!(flags & QEventLoop::ExcludeSocketNotifiers) && !d->queuedSocketEvents.isEmpty()) {
                 // process queued socket events
                 haveMessage = true;
                 msg = d->queuedSocketEvents.takeFirst();
             } else {
                 haveMessage = PeekMessage(&msg, 0, 0, 0, PM_REMOVE);
                 if (haveMessage && (flags & QEventLoop::ExcludeUserInputEvents)
                     && ((msg.message >= WM_KEYFIRST
                          && msg.message <= WM_KEYLAST)
                         || (msg.message >= WM_MOUSEFIRST
                             && msg.message <= WM_MOUSELAST)
                         || msg.message == WM_MOUSEWHEEL
                         || msg.message == WM_MOUSEHWHEEL
                         || msg.message == WM_TOUCH
 #ifndef QT_NO_GESTURES
                         || msg.message == WM_GESTURE
                         || msg.message == WM_GESTURENOTIFY
 #endif
                         || msg.message == WM_CLOSE)) {
                     // queue user input events for later processing
                     haveMessage = false;
                     d->queuedUserInputEvents.append(msg);
                 }
                 if (haveMessage && (flags & QEventLoop::ExcludeSocketNotifiers)
                     && (msg.message == WM_QT_SOCKETNOTIFIER && msg.hwnd == d->internalHwnd)) {
                     // queue socket events for later processing
                     haveMessage = false;
                     d->queuedSocketEvents.append(msg);
                 }
             }
             if (!haveMessage) {
                 // no message - check for signalled objects
                 for (int i=0; i<(int)nCount; i++)
                     pHandles[i] = d->winEventNotifierList.at(i)->handle();
                 waitRet = MsgWaitForMultipleObjectsEx(nCount, pHandles, 0, QS_ALLINPUT, MWMO_ALERTABLE);
                 if ((haveMessage = (waitRet == WAIT_OBJECT_0 + nCount))) {
                     // a new message has arrived, process it
                     continue;
                 }
             }
             if (haveMessage) {
 #ifdef Q_OS_WINCE
                 // WinCE doesn't support hooks at all, so we have to call this by hand :(
                 (void) qt_GetMessageHook(0, PM_REMOVE, (LPARAM) &msg);
 #endif
                 if (d->internalHwnd == msg.hwnd && msg.message == WM_QT_SENDPOSTEDEVENTS) {
                     if (seenWM_QT_SENDPOSTEDEVENTS) {
                         // when calling processEvents() "manually", we only want to send posted
                         // events once
                         needWM_QT_SENDPOSTEDEVENTS = true;
                         continue;
                     }
                     seenWM_QT_SENDPOSTEDEVENTS = true;
                 } else if (msg.message == WM_TIMER) {
                     // avoid live-lock by keeping track of the timers we've already sent
                     bool found = false;
                     for (int i = 0; !found && i < processedTimers.count(); ++i) {
                         const MSG processed = processedTimers.constData()[i];
                         found = (processed.wParam == msg.wParam && processed.hwnd == msg.hwnd && processed.lParam == msg.lParam);
                     }
                     if (found)
                         continue;
                     processedTimers.append(msg);
                 } else if (msg.message == WM_QUIT) {
                     if (QCoreApplication::instance())
                         QCoreApplication::instance()->quit();
                     return false;
                 }
                 if (!filterEvent(&msg)) {
                     TranslateMessage(&msg);
                     DispatchMessage(&msg);
                 }
             } else if (waitRet < WAIT_OBJECT_0 + nCount) {
                 d->activateEventNotifier(d->winEventNotifierList.at(waitRet - WAIT_OBJECT_0));
             } else {
                 // nothing todo so break
                 break;
             }
             retVal = true;
         }
         // still nothing - wait for message or signalled objects
         canWait = (!retVal
                    && !d->interrupt
                    && (flags & QEventLoop::WaitForMoreEvents));
         if (canWait) {
             DWORD nCount = d->winEventNotifierList.count();
             Q_ASSERT(nCount < MAXIMUM_WAIT_OBJECTS - 1);
             for (int i=0; i<(int)nCount; i++)
                 pHandles[i] = d->winEventNotifierList.at(i)->handle();
             emit aboutToBlock();
             waitRet = MsgWaitForMultipleObjectsEx(nCount, pHandles, INFINITE, QS_ALLINPUT, MWMO_ALERTABLE | MWMO_INPUTAVAILABLE);
             emit awake();
             if (waitRet < WAIT_OBJECT_0 + nCount) {
                 d->activateEventNotifier(d->winEventNotifierList.at(waitRet - WAIT_OBJECT_0));
                 retVal = true;
             }
         }
     } while (canWait);
     if (!seenWM_QT_SENDPOSTEDEVENTS && (flags & QEventLoop::EventLoopExec) == 0) {
         // when called "manually", always send posted events
         QCoreApplicationPrivate::sendPostedEvents(0, 0, d->threadData);
     }
     if (needWM_QT_SENDPOSTEDEVENTS)
         PostMessage(d->internalHwnd, WM_QT_SENDPOSTEDEVENTS, 0, 0);
     return retVal;
 }
registeredTimers()
QList< QEventDispatcherWin32::TimerInfo > QEventDispatcherWin32::registeredTimers (QObject * object) const virtual
Returns a list of registered timers for object.
The timer ID is the first member in each pair; the interval is the second.
Implements QAbstractEventDispatcher.
Definition at line 1019 of file qeventdispatcher_win.cpp.
 {
     if (!object) {
         qWarning("QEventDispatcherWin32:registeredTimers: invalid argument");
         return QList<TimerInfo>();
     }
     Q_D(const QEventDispatcherWin32);
     QList<TimerInfo> list;
     for (int i = 0; i < d->timerVec.size(); ++i) {
         const WinTimerInfo *t = d->timerVec.at(i);
         if (t && t->obj == object)
             list << TimerInfo(t->timerId, t->interval);
     }
     return list;
 }
registerEventNotifier()
bool QEventDispatcherWin32::registerEventNotifier (QWinEventNotifier * notifier)
Definition at line 1036 of file qeventdispatcher_win.cpp.
Referenced by QWinEventNotifier::QWinEventNotifier(), and QWinEventNotifier::setEnabled().
 {
     if (!notifier) {
         qWarning("QWinEventNotifier: Internal error");
         return false;
     } else if (notifier->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QWinEventNotifier: event notifiers cannot be enabled from another thread");
         return false;
     }
     Q_D(QEventDispatcherWin32);
     if (d->winEventNotifierList.contains(notifier))
         return true;
     if (d->winEventNotifierList.count() >= MAXIMUM_WAIT_OBJECTS - 2) {
         qWarning("QWinEventNotifier: Cannot have more than %d enabled at one time", MAXIMUM_WAIT_OBJECTS - 2);
         return false;
     }
     d->winEventNotifierList.append(notifier);
     return true;
 }
registerSocketNotifier()
void QEventDispatcherWin32::registerSocketNotifier (QSocketNotifier * notifier) virtual
Registers notifier with the event loop.
Subclasses must implement this method to tie a socket notifier into another event loop.
Implements QAbstractEventDispatcher.
Definition at line 870 of file qeventdispatcher_win.cpp.
 {
     Q_ASSERT(notifier);
     int sockfd = notifier->socket();
     int type = notifier->type();
 #ifndef QT_NO_DEBUG
     if (sockfd < 0) {
         qWarning("QSocketNotifier: Internal error");
         return;
     } else if (notifier->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QSocketNotifier: socket notifiers cannot be enabled from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherWin32);
     QSNDict *sn_vec[3] = { &d->sn_read, &d->sn_write, &d->sn_except };
     QSNDict *dict = sn_vec[type];
     if (QCoreApplication::closingDown()) // ### d->exitloop?
         return; // after sn_cleanup, don't reinitialize.
     if (dict->contains(sockfd)) {
         const char *t[] = { "Read", "Write", "Exception" };
     /* Variable "socket" below is a function pointer. */
         qWarning("QSocketNotifier: Multiple socket notifiers for "
                  "same socket %d and type %s", sockfd, t[type]);
     }
     QSockNot *sn = new QSockNot;
     sn->obj = notifier;
     sn->fd  = sockfd;
     dict->insert(sn->fd, sn);
     if (d->internalHwnd)
         d->doWsaAsyncSelect(sockfd);
 }
registerTimer()
void QEventDispatcherWin32::registerTimer (int timerId, int interval, QObject * object) virtual
Register a timer with the specified timerId and interval for the given object.
Implements QAbstractEventDispatcher.
Definition at line 937 of file qeventdispatcher_win.cpp.
 {
     if (timerId < 1 || interval < 0 || !object) {
         qWarning("QEventDispatcherWin32::registerTimer: invalid arguments");
         return;
     } else if (object->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QObject::startTimer: timers cannot be started from another thread");
         return;
     }
     Q_D(QEventDispatcherWin32);
     register WinTimerInfo *t = new WinTimerInfo;
     t->dispatcher = this;
     t->timerId  = timerId;
     t->interval = interval;
     t->obj  = object;
     t->inTimerEvent = false;
     t->fastTimerId = 0;
     if (d->internalHwnd)
         d->registerTimer(t);
     d->timerVec.append(t);                      // store in timer vector
     d->timerDict.insert(t->timerId, t);          // store timers in dict
 }
startingUp()
void QEventDispatcherWin32::startingUp () virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractEventDispatcher.
Definition at line 1111 of file qeventdispatcher_win.cpp.
 { }
unregisterEventNotifier()
void QEventDispatcherWin32::unregisterEventNotifier (QWinEventNotifier * notifier)
Definition at line 1059 of file qeventdispatcher_win.cpp.
Referenced by QWinEventNotifier::setEnabled().
 {
     if (!notifier) {
         qWarning("QWinEventNotifier: Internal error");
         return;
     } else if (notifier->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QWinEventNotifier: event notifiers cannot be disabled from another thread");
         return;
     }
     Q_D(QEventDispatcherWin32);
     int i = d->winEventNotifierList.indexOf(notifier);
     if (i != -1)
         d->winEventNotifierList.takeAt(i);
 }
unregisterSocketNotifier()
void QEventDispatcherWin32::unregisterSocketNotifier (QSocketNotifier * notifier) virtual
Unregisters notifier from the event dispatcher.
Subclasses must reimplement this method to tie a socket notifier into another event loop. Reimplementations must call the base implementation.
Implements QAbstractEventDispatcher.
Definition at line 908 of file qeventdispatcher_win.cpp.
Referenced by closingDown().
 {
     Q_ASSERT(notifier);
     int sockfd = notifier->socket();
     int type = notifier->type();
 #ifndef QT_NO_DEBUG
     if (sockfd < 0) {
         qWarning("QSocketNotifier: Internal error");
         return;
     } else if (notifier->thread() != thread() || thread() != QThread::currentThread()) {
         qWarning("QSocketNotifier: socket notifiers cannot be disabled from another thread");
         return;
     }
 #endif
     Q_D(QEventDispatcherWin32);
     QSNDict *sn_vec[3] = { &d->sn_read, &d->sn_write, &d->sn_except };
     QSNDict *dict = sn_vec[type];
     QSockNot *sn = dict->value(sockfd);
     if (!sn)
         return;
     dict->remove(sockfd);
     delete sn;
     if (d->internalHwnd)
         d->doWsaAsyncSelect(sockfd);
 }
unregisterTimer()
bool QEventDispatcherWin32::unregisterTimer (int timerId) virtual
Unregisters the timer with the given timerId.
Returns true if successful; otherwise returns false.
See also
registerTimer(), unregisterTimers()
Implements QAbstractEventDispatcher.
Definition at line 964 of file qeventdispatcher_win.cpp.
 {
     if (timerId < 1) {
         qWarning("QEventDispatcherWin32::unregisterTimer: invalid argument");
         return false;
     }
     QThread *currentThread = QThread::currentThread();
     if (thread() != currentThread) {
         qWarning("QObject::killTimer: timers cannot be stopped from another thread");
         return false;
     }
     Q_D(QEventDispatcherWin32);
     if (d->timerVec.isEmpty() || timerId <= 0)
         return false;
     WinTimerInfo *t = d->timerDict.value(timerId);
     if (!t)
         return false;
     d->timerDict.remove(t->timerId);
     d->timerVec.removeAll(t);
     d->unregisterTimer(t);
     return true;
 }
unregisterTimers()
bool QEventDispatcherWin32::unregisterTimers (QObject * object) virtual
Unregisters all the timers associated with the given object.
Returns true if all timers were successful removed; otherwise returns false.
See also
unregisterTimer(), registeredTimers()
Implements QAbstractEventDispatcher.
Definition at line 990 of file qeventdispatcher_win.cpp.
 {
     if (!object) {
         qWarning("QEventDispatcherWin32::unregisterTimers: invalid argument");
         return false;
     }
     QThread *currentThread = QThread::currentThread();
     if (object->thread() != thread() || thread() != currentThread) {
         qWarning("QObject::killTimers: timers cannot be stopped from another thread");
         return false;
     }
     Q_D(QEventDispatcherWin32);
     if (d->timerVec.isEmpty())
         return false;
     register WinTimerInfo *t;
     for (int i=0; i<d->timerVec.size(); i++) {
         t = d->timerVec.at(i);
         if (t && t->obj == object) {                // object found
             d->timerDict.remove(t->timerId);
             d->timerVec.removeAt(i);
             d->unregisterTimer(t);
             --i;
         }
     }
     return true;
 }
wakeUp()
void QEventDispatcherWin32::wakeUp () virtual
Wakes up the event loop.
Note
This class or function is threadsafe.
See also
awake()
Implements QAbstractEventDispatcher.
Definition at line 1091 of file qeventdispatcher_win.cpp.
Referenced by interrupt().
 {
     Q_D(QEventDispatcherWin32);
     d->serialNumber.ref();
     if (d->internalHwnd && d->wakeUps.testAndSetAcquire(0, 1)) {
         // post a WM_QT_SENDPOSTEDEVENTS to this thread if there isn't one already pending
         PostMessage(d->internalHwnd, WM_QT_SENDPOSTEDEVENTS, 0, 0);
     }
 }
Friends and Related Functions
QGuiEventDispatcherWin32
friend class QGuiEventDispatcherWin32 friend
Definition at line 73 of file qeventdispatcher_win_p.h.
qt_GetMessageHook
LRESULT QT_WIN_CALLBACK qt_GetMessageHook (int code, WPARAM wp, LPARAM lp) friend
Definition at line 520 of file qeventdispatcher_win.cpp.
 {
     if (wp == PM_REMOVE) {
         QEventDispatcherWin32 *q = qobject_cast<QEventDispatcherWin32 *>(QAbstractEventDispatcher::instance());
         Q_ASSERT(q != 0);
         if (q) {
             MSG *msg = (MSG *) lp;
             QEventDispatcherWin32Private *d = q->d_func();
             int localSerialNumber = d->serialNumber;
             static const UINT mask = inputTimerMask();
             if (HIWORD(GetQueueStatus(mask)) == 0) {
                 // no more input or timer events in the message queue, we can allow posted events to be sent normally now
                 if (d->sendPostedEventsWindowsTimerId != 0) {
                     // stop the timer to send posted events, since we now allow the WM_QT_SENDPOSTEDEVENTS message
                     KillTimer(d->internalHwnd, d->sendPostedEventsWindowsTimerId);
                     d->sendPostedEventsWindowsTimerId = 0;
                 }
                 (void) d->wakeUps.fetchAndStoreRelease(0);
                 if (localSerialNumber != d->lastSerialNumber
                     // if this message IS the one that triggers sendPostedEvents(), no need to post it again
                     && (msg->hwnd != d->internalHwnd
                         || msg->message != WM_QT_SENDPOSTEDEVENTS)) {
                     PostMessage(d->internalHwnd, WM_QT_SENDPOSTEDEVENTS, 0, 0);
                 }
             } else if (d->sendPostedEventsWindowsTimerId == 0
                        && localSerialNumber != d->lastSerialNumber) {
                 // start a special timer to continue delivering posted events while
                 // there are still input and timer messages in the message queue
                 d->sendPostedEventsWindowsTimerId = SetTimer(d->internalHwnd,
                                                              SendPostedEventsWindowsTimerId,
                                                              0, // we specify zero, but Windows uses USER_TIMER_MINIMUM
                                                              NULL);
                 // we don't check the return value of SetTimer()... if creating the timer failed, there's little
                 // we can do. we just have to accept that posted events will be starved
             }
         }
     }
 #ifdef Q_OS_WINCE
     Q_UNUSED(code);
     return 0;
 #else
     return CallNextHookEx(0, code, wp, lp);
 #endif
 }
qt_internal_proc
LRESULT QT_WIN_CALLBACK qt_internal_proc (HWND hwnd, UINT message, WPARAM wp, LPARAM lp) friend
Definition at line 430 of file qeventdispatcher_win.cpp.
 {
     if (message == WM_NCCREATE)
         return true;
     MSG msg;
     msg.hwnd = hwnd;
     msg.message = message;
     msg.wParam = wp;
     msg.lParam = lp;
     QCoreApplication *app = QCoreApplication::instance();
     long result;
     if (!app) {
         if (message == WM_TIMER)
             KillTimer(hwnd, wp);
         return 0;
     } else if (app->filterEvent(&msg, &result)) {
         return result;
     }
 #ifdef GWLP_USERDATA
     QEventDispatcherWin32 *q = (QEventDispatcherWin32 *) GetWindowLongPtr(hwnd, GWLP_USERDATA);
 #else
     QEventDispatcherWin32 *q = (QEventDispatcherWin32 *) GetWindowLong(hwnd, GWL_USERDATA);
 #endif
     QEventDispatcherWin32Private *d = 0;
     if (q != 0)
         d = q->d_func();
     if (message == WM_QT_SOCKETNOTIFIER) {
         // socket notifier message
         int type = -1;
         switch (WSAGETSELECTEVENT(lp)) {
         case FD_READ:
         case FD_CLOSE:
         case FD_ACCEPT:
             type = 0;
             break;
         case FD_WRITE:
         case FD_CONNECT:
             type = 1;
             break;
         case FD_OOB:
             type = 2;
             break;
         }
         if (type >= 0) {
             Q_ASSERT(d != 0);
             QSNDict *sn_vec[3] = { &d->sn_read, &d->sn_write, &d->sn_except };
             QSNDict *dict = sn_vec[type];
             QSockNot *sn = dict ? dict->value(wp) : 0;
             if (sn) {
                 QEvent event(QEvent::SockAct);
                 QCoreApplication::sendEvent(sn->obj, &event);
             }
         }
         return 0;
     } else if (message == WM_QT_SENDPOSTEDEVENTS
                // we also use a Windows timer to send posted events when the message queue is full
                || (message == WM_TIMER
                    && d->sendPostedEventsWindowsTimerId != 0
                    && wp == (uint)d->sendPostedEventsWindowsTimerId)) {
         int localSerialNumber = d->serialNumber;
         if (localSerialNumber != d->lastSerialNumber) {
             d->lastSerialNumber = localSerialNumber;
             QCoreApplicationPrivate::sendPostedEvents(0, 0, d->threadData);
         }
         return 0;
     } else if (message == WM_TIMER) {
         Q_ASSERT(d != 0);
         d->sendTimerEvent(wp);
         return 0;
     }
     return DefWindowProc(hwnd, message, wp, lp);
 }
The documentation for this class was generated from the following files:
/src/corelib/kernel/qeventdispatcher_win_p.h
/src/corelib/kernel/qeventdispatcher_win.cpp