Qt 4.8: QDeclarativeContextPrivate Class Reference
QDeclarativeContextPrivate Class Reference
#include <qdeclarativecontext_p.h>
Public Functions
QDeclarativeContextPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QObject * context_at (QDeclarativeListProperty< QObject > *, int)
static int context_count (QDeclarativeListProperty< QObject > *)
static QDeclarativeContextPrivate * get (QDeclarativeContext *context)
static QDeclarativeContext * get (QDeclarativeContextPrivate *context)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QDeclarativeContextData * data
QList< QPointer< QObject > > instances
int notifyIndex
QList< QVariant > propertyValues
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 83 of file qdeclarativecontext_p.h.
Constructors and Destructors
QDeclarativeContextPrivate()
QDeclarativeContextPrivate::QDeclarativeContextPrivate ()
Definition at line 61 of file qdeclarativecontext.cpp.
 : data(0), notifyIndex(-1)
 {
 }
Functions
context_at()
QObject * QDeclarativeContextPrivate::context_at (QDeclarativeListProperty< QObject > * prop, int index) static
Definition at line 489 of file qdeclarativecontext.cpp.
Referenced by QDeclarativeContextScriptClass::property().
 {
     QDeclarativeContext *context = static_cast<QDeclarativeContext*>(prop->object);
     QDeclarativeContextPrivate *d = QDeclarativeContextPrivate::get(context);
     int contextProperty = (int)(quintptr)prop->data;
     if (d->propertyValues.at(contextProperty).userType() != qMetaTypeId<QList<QObject*> >()) {
         return 0;
     } else {
         return ((const QList<QObject*> *)d->propertyValues.at(contextProperty).constData())->at(index);
     }
 }
context_count()
int QDeclarativeContextPrivate::context_count (QDeclarativeListProperty< QObject > * prop) static
Definition at line 476 of file qdeclarativecontext.cpp.
Referenced by QDeclarativeContextScriptClass::property().
 {
     QDeclarativeContext *context = static_cast<QDeclarativeContext*>(prop->object);
     QDeclarativeContextPrivate *d = QDeclarativeContextPrivate::get(context);
     int contextProperty = (int)(quintptr)prop->data;
     if (d->propertyValues.at(contextProperty).userType() != qMetaTypeId<QList<QObject*> >()) {
         return 0;
     } else {
         return ((const QList<QObject> *)d->propertyValues.at(contextProperty).constData())->count();
     }
 }
get() [1/2]
static QDeclarativeContextPrivate* QDeclarativeContextPrivate::get (QDeclarativeContext * context) inline static
Definition at line 94 of file qdeclarativecontext_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), QDeclarativeContextData::asQDeclarativeContextPrivate(), QDeclarativeEngineDebugService::buildObjectList(), QDeclarativeEngineDebugService::buildStatesList(), QDeclarativeVMEMetaObject::connectAlias(), context_at(), context_count(), QDeclarativeContextData::get(), and QDeclarativeVMEMetaObject::metaCall().
{
         return static_cast<QDeclarativeContextPrivate *>(QObjectPrivate::get(context));
     }
get() [2/2]
static QDeclarativeContext* QDeclarativeContextPrivate::get (QDeclarativeContextPrivate * context) inline static
Definition at line 97 of file qdeclarativecontext_p.h.
{
         return static_cast<QDeclarativeContext *>(context->q_func());
     }
Properties
data
QDeclarativeContextData* QDeclarativeContextPrivate::data
Definition at line 89 of file qdeclarativecontext_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), QDeclarativeVMEMetaObject::connectAlias(), QDeclarativeContextData::get(), and QDeclarativeVMEMetaObject::metaCall().
instances
QList<QPointer<QObject> > QDeclarativeContextPrivate::instances
Definition at line 102 of file qdeclarativecontext_p.h.
Referenced by QDeclarativeComponentPrivate::begin(), QDeclarativeEngineDebugService::buildObjectList(), and QDeclarativeEngineDebugService::buildStatesList().
notifyIndex
int QDeclarativeContextPrivate::notifyIndex
Definition at line 92 of file qdeclarativecontext_p.h.
Referenced by QDeclarativeVMEMetaObject::connectAlias(), QDeclarativeCompiledBindingsPrivate::findgeneric(), and QDeclarativeContextScriptClass::property().
propertyValues
QList<QVariant> QDeclarativeContextPrivate::propertyValues
Definition at line 91 of file qdeclarativecontext_p.h.
Referenced by context_at(), context_count(), QDeclarativeCompiledBindingsPrivate::findgeneric(), and QDeclarativeContextScriptClass::property().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecontext_p.h
/src/declarative/qml/qdeclarativecontext.cpp