Qt 4.8: QToolButton Class Reference
QToolButton Class Reference
The QToolButton class provides a quick-access button to commands or options, usually used inside a QToolBar.
#include <qtoolbutton.h>
Public Types
enum ToolButtonPopupMode { DelayedPopup, MenuButtonPopup, InstantPopup }
Describes how a menu should be popped up for tool buttons that has a menu set or contains a list of actions.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void setDefaultAction (QAction *)
Sets the default action to action.
void setToolButtonStyle (Qt::ToolButtonStyle style)
void showMenu ()
Shows (pops up) the associated popup menu.
Public Slots inherited from QAbstractButton
void animateClick (int msec=100)
Performs an animated click: the button is pressed immediately, and released msec milliseconds later (the default is 100 ms).
void click ()
Performs a click.
void setChecked (bool)
void setIconSize (const QSize &size)
void toggle ()
Toggles the state of a checkable button.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void triggered (QAction *)
This signal is emitted when the given action is triggered.
Signals inherited from QAbstractButton
void clicked (bool checked=false)
This signal is emitted when the button is activated (i.e.
void pressed ()
This signal is emitted when the button is pressed down.
void released ()
This signal is emitted when the button is released.
void toggled (bool checked)
This signal is emitted whenever a checkable button changes its state.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
Qt::ArrowType arrowType () const
bool autoRaise () const
QAction * defaultAction () const
Returns the default action.
QMenu * menu () const
Returns the associated menu, or 0 if no menu has been defined.
QSize minimumSizeHint () const
Reimplemented Function
ToolButtonPopupMode popupMode () const
QToolButton (QWidget *parent=0)
Constructs an empty tool button with parent parent.
void setArrowType (Qt::ArrowType type)
void setAutoRaise (bool enable)
void setMenu (QMenu *menu)
Associates the given menu with this tool button.
void setPopupMode (ToolButtonPopupMode mode)
QSize sizeHint () const
Reimplemented Function
Qt::ToolButtonStyle toolButtonStyle () const
~QToolButton ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QAbstractButton
bool autoExclusive () const
bool autoRepeat () const
int autoRepeatDelay () const
int autoRepeatInterval () const
QButtonGroup * group () const
Returns the group that this button belongs to.
QIcon icon () const
QSize iconSize () const
bool isCheckable () const
bool isChecked () const
bool isDown () const
QAbstractButton (QWidget *parent=0)
Constructs an abstract button with a parent.
void setAutoExclusive (bool)
void setAutoRepeat (bool)
void setAutoRepeatDelay (int)
void setAutoRepeatInterval (int)
void setCheckable (bool)
void setDown (bool)
void setIcon (const QIcon &icon)
void setShortcut (const QKeySequence &key)
void setText (const QString &text)
QKeySequence shortcut () const
QString text () const
~QAbstractButton ()
Destroys the button.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void actionEvent (QActionEvent *)
Reimplemented Function
void changeEvent (QEvent *)
Reimplemented Function
void enterEvent (QEvent *)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
bool hitButton (const QPoint &pos) const
Reimplemented Function
void initStyleOption (QStyleOptionToolButton *option) const
Initialize option with the values from this QToolButton.
void leaveEvent (QEvent *)
Reimplemented Function
void mousePressEvent (QMouseEvent *)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *)
Reimplemented Function
void nextCheckState ()
Reimplemented Function
void paintEvent (QPaintEvent *)
Paints the button in response to the paint event.
QToolButton (QToolButtonPrivate &, QWidget *parent)
void timerEvent (QTimerEvent *)
Reimplemented Function
Protected Functions inherited from QAbstractButton
virtual void checkStateSet ()
This virtual handler is called when setChecked() was called, unless it was called from within nextCheckState().
void focusInEvent (QFocusEvent *e)
Reimplemented Function
void focusOutEvent (QFocusEvent *e)
Reimplemented Function
void keyPressEvent (QKeyEvent *e)
Reimplemented Function
void keyReleaseEvent (QKeyEvent *e)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
QAbstractButton (QAbstractButtonPrivate &dd, QWidget *parent=0)
Protected Functions inherited from QWidget
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void languageChange ()
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
Qt::ArrowType arrowType
whether the button displays an arrow instead of a normal icon
bool autoRaise
whether auto-raising is enabled or not.
ToolButtonPopupMode popupMode
describes the way that popup menus are used with tool buttons
Qt::ToolButtonStyle toolButtonStyle
whether the tool button displays an icon only, text only, or text beside/below the icon.
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QToolButton class provides a quick-access button to commands or options, usually used inside a QToolBar.
A tool button is a special button that provides quick-access to specific commands or options. As opposed to a normal command button, a tool button usually doesn't show a text label, but shows an icon instead.
Tool buttons are normally created when new QAction instances are created with QToolBar::addAction() or existing actions are added to a toolbar with QToolBar::addAction(). It is also possible to construct tool buttons in the same way as any other widget, and arrange them alongside other widgets in layouts.
One classic use of a tool button is to select tools; for example, the "pen" tool in a drawing program. This would be implemented by using a QToolButton as a toggle button (see setToggleButton()).
QToolButton supports auto-raising. In auto-raise mode, the button draws a 3D frame only when the mouse points at it. The feature is automatically turned on when a button is used inside a QToolBar. Change it with setAutoRaise().
A tool button's icon is set as QIcon. This makes it possible to specify different pixmaps for the disabled and active state. The disabled pixmap is used when the button's functionality is not available. The active pixmap is displayed when the button is auto-raised because the mouse pointer is hovering over it.
The button's look and dimension is adjustable with setToolButtonStyle() and setIconSize(). When used inside a QToolBar in a QMainWindow, the button automatically adjusts to QMainWindow's settings (see QMainWindow::setToolButtonStyle() and QMainWindow::setIconSize()). Instead of an icon, a tool button can also display an arrow symbol, specified with arrowType.
A tool button can offer additional choices in a popup menu. The popup menu can be set using setMenu(). Use setPopupMode() to configure the different modes available for tool buttons with a menu set. The default mode is DelayedPopupMode which is sometimes used with the "Back" button in a web browser. After pressing and holding the button down for a while, a menu pops up showing a list of possible pages to jump to. The default delay is 600 ms; you can adjust it with setPopupDelay().
Qt Assistant's toolbar with tool buttons
Qt Assistant's toolbar contains tool buttons that are associated with actions used in other parts of the main window.
See also
QPushButton, QToolBar, QMainWindow, QAction, {fowler}{GUI Design Handbook: Push Button}
Definition at line 59 of file qtoolbutton.h.
Enumerations
ToolButtonPopupMode
enum QToolButton::ToolButtonPopupMode
Describes how a menu should be popped up for tool buttons that has a menu set or contains a list of actions.
DelayedPopup After pressing and holding the tool button down for a certain amount of time (the timeout is style dependant, see QStyle::SH_ToolButton_PopupDelay), the menu is displayed. A typical application example is the "back" button in some web browsers's tool bars. If the user clicks it, the browser simply browses back to the previous page. If the user presses and holds the button down for a while, the tool button shows a menu containing the current history list
MenuButtonPopup In this mode the tool button displays a special arrow to indicate that a menu is present. The menu is displayed when the arrow part of the button is pressed.
InstantPopup The menu is displayed, without delay, when the tool button is pressed. In this mode, the button's own action is not triggered.
Enumerator
DelayedPopup
MenuButtonPopup
InstantPopup
Definition at line 71 of file qtoolbutton.h.
{
         DelayedPopup,
         MenuButtonPopup,
         InstantPopup
     };
Constructors and Destructors
QToolButton() [1/2]
QToolButton::QToolButton (QWidget * parent = 0) explicit
Constructs an empty tool button with parent parent.
Definition at line 192 of file qtoolbutton.cpp.
     : QAbstractButton(*new QToolButtonPrivate, parent)
 {
     Q_D(QToolButton);
     d->init();
 }
~QToolButton()
QToolButton::~QToolButton ()
Destroys the object and frees any allocated resources.
Definition at line 410 of file qtoolbutton.cpp.
 {
 }
QToolButton() [2/2]
QToolButton::QToolButton (QToolButtonPrivate & dd, QWidget * parent) protected
Warning
This function is not part of the public interface.
Definition at line 1209 of file qtoolbutton.cpp.
     :QAbstractButton(dd, parent)
 {
     Q_D(QToolButton);
     d->init();
 }
Functions
actionEvent()
void QToolButton::actionEvent (QActionEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 576 of file qtoolbutton.cpp.
 {
     Q_D(QToolButton);
     QAction *action = event->action();
     switch (event->type()) {
     case QEvent::ActionChanged:
         if (action == d->defaultAction)
             setDefaultAction(action); // update button state
         break;
     case QEvent::ActionAdded:
         connect(action, SIGNAL(triggered()), this, SLOT(_q_actionTriggered()));
         break;
     case QEvent::ActionRemoved:
         if (d->defaultAction == action)
             d->defaultAction = 0;
 #ifndef QT_NO_MENU
         if (action == d->menuAction)
             d->menuAction = 0;
 #endif
         action->disconnect(this);
         break;
     default:
         ;
     }
     QAbstractButton::actionEvent(event);
 }
arrowType()
Qt::ArrowType QToolButton::arrowType () const
Referenced by QToolButtonPrivate::init(), and minimumSizeHint().
autoRaise()
bool QToolButton::autoRaise () const
Referenced by QToolButtonPrivate::init(), and setAutoRaise().
changeEvent()
void QToolButton::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 684 of file qtoolbutton.cpp.
 {
 #ifndef QT_NO_TOOLBAR
     Q_D(QToolButton);
     if (e->type() == QEvent::ParentChange) {
         if (qobject_cast<QToolBar*>(parentWidget()))
             d->autoRaise = true;
     } else if (e->type() == QEvent::StyleChange
 #ifdef Q_WS_MAC
                || e->type() == QEvent::MacSizeChange
 #endif
                ) {
 #ifdef QT3_SUPPORT
         if (!d->userDefinedPopupDelay)
 #endif
         d->delay = style()->styleHint(QStyle::SH_ToolButton_PopupDelay, 0, this);
         d->setLayoutItemMargins(QStyle::SE_ToolButtonLayoutItem);
     }
 #endif
     QAbstractButton::changeEvent(e);
 }
defaultAction()
QAction * QToolButton::defaultAction () const
Returns the default action.
See also
setDefaultAction()
Definition at line 1171 of file qtoolbutton.cpp.
Referenced by QToolButtonPrivate::init(), and QToolButtonPrivate::popupTimerDone().
 {
     Q_D(const QToolButton);
     return d->defaultAction;
 }
enterEvent()
void QToolButton::enterEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 641 of file qtoolbutton.cpp.
 {
     Q_D(QToolButton);
     if (d->autoRaise)
         update();
     if (d->defaultAction)
         d->defaultAction->hover();
     QAbstractButton::enterEvent(e);
 }
event()
bool QToolButton::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 1192 of file qtoolbutton.cpp.
 {
     switch(event->type()) {
     case QEvent::HoverEnter:
     case QEvent::HoverLeave:
     case QEvent::HoverMove:
     if (const QHoverEvent *he = static_cast<const QHoverEvent *>(event))
         d_func()->updateHoverControl(he->pos());
         break;
     default:
         break;
     }
     return QAbstractButton::event(event);
 }
hitButton()
bool QToolButton::hitButton (const QPoint & pos) const protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 742 of file qtoolbutton.cpp.
 {
     Q_D(const QToolButton);
     if(QAbstractButton::hitButton(pos))
         return (d->buttonPressed != QToolButtonPrivate::MenuButtonPressed);
     return false;
 }
initStyleOption()
void QToolButton::initStyleOption (QStyleOptionToolButton * option) const protected
Initialize option with the values from this QToolButton.
This method is useful for subclasses when they need a QStyleOptionToolButton, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom()
Definition at line 315 of file qtoolbutton.cpp.
Referenced by mousePressEvent(), QToolBarExtension::paintEvent(), QMenuBarExtension::paintEvent(), paintEvent(), and sizeHint().
 {
     if (!option)
         return;
     Q_D(const QToolButton);
     option->initFrom(this);
     bool forceNoText = false;
     option->iconSize = iconSize(); //default value
 #ifndef QT_NO_TOOLBAR
     if (parentWidget()) {
         if (QToolBar *toolBar = qobject_cast<QToolBar *>(parentWidget())) {
             option->iconSize = toolBar->iconSize();
         }
 #ifdef QT3_SUPPORT
         else if (parentWidget()->inherits("Q3ToolBar")) {
             if (!option->iconSize.isValid()) {
                 int iconSize = style()->pixelMetric(QStyle::PM_ToolBarIconSize, option, this);
                 option->iconSize = d->icon.actualSize(QSize(iconSize, iconSize));
             }
             forceNoText = d->toolButtonStyle == Qt::ToolButtonIconOnly;
         }
 #endif
     }
 #endif // QT_NO_TOOLBAR
     if (!forceNoText)
         option->text = d->text;
     option->icon = d->icon;
     option->arrowType = d->arrowType;
     if (d->down)
         option->state |= QStyle::State_Sunken;
     if (d->checked)
         option->state |= QStyle::State_On;
     if (d->autoRaise)
         option->state |= QStyle::State_AutoRaise;
     if (!d->checked && !d->down)
         option->state |= QStyle::State_Raised;
     option->subControls = QStyle::SC_ToolButton;
     option->activeSubControls = QStyle::SC_None;
     option->features = QStyleOptionToolButton::None;
     if (d->popupMode == QToolButton::MenuButtonPopup) {
         option->subControls |= QStyle::SC_ToolButtonMenu;
         option->features |= QStyleOptionToolButton::MenuButtonPopup;
     }
     if (option->state & QStyle::State_MouseOver) {
         option->activeSubControls = d->hoverControl;
     }
     if (d->menuButtonDown) {
         option->state |= QStyle::State_Sunken;
         option->activeSubControls |= QStyle::SC_ToolButtonMenu;
     }
     if (d->down) {
         option->state |= QStyle::State_Sunken;
         option->activeSubControls |= QStyle::SC_ToolButton;
     }
     if (d->arrowType != Qt::NoArrow)
         option->features |= QStyleOptionToolButton::Arrow;
     if (d->popupMode == QToolButton::DelayedPopup)
         option->features |= QStyleOptionToolButton::PopupDelay;
 #ifndef QT_NO_MENU
     if (d->hasMenu())
         option->features |= QStyleOptionToolButton::HasMenu;
 #endif
     if (d->toolButtonStyle == Qt::ToolButtonFollowStyle) {
         option->toolButtonStyle = Qt::ToolButtonStyle(style()->styleHint(QStyle::SH_ToolButtonStyle, option, this));
     } else
         option->toolButtonStyle = d->toolButtonStyle;
     if (option->toolButtonStyle == Qt::ToolButtonTextBesideIcon) {
         // If the action is not prioritized, remove the text label to save space
         if (d->defaultAction && d->defaultAction->priority() < QAction::NormalPriority)
             option->toolButtonStyle = Qt::ToolButtonIconOnly;
     }
     if (d->icon.isNull() && d->arrowType == Qt::NoArrow && !forceNoText) {
         if (!d->text.isEmpty())
             option->toolButtonStyle = Qt::ToolButtonTextOnly;
         else if (option->toolButtonStyle != Qt::ToolButtonTextOnly)
             option->toolButtonStyle = Qt::ToolButtonIconOnly;
     }
     option->pos = pos();
     option->font = font();
 }
leaveEvent()
void QToolButton::leaveEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 655 of file qtoolbutton.cpp.
 {
     Q_D(QToolButton);
     if (d->autoRaise)
         update();
     QAbstractButton::leaveEvent(e);
 }
menu()
QMenu * QToolButton::menu () const
Returns the associated menu, or 0 if no menu has been defined.
See also
setMenu()
Definition at line 868 of file qtoolbutton.cpp.
Referenced by QAccessibleToolButton::actionCount(), AccessibleFactory::create(), QAccessibleToolButton::isSplitButton(), and QMenuBarPrivate::setCurrentAction().
 {
     Q_D(const QToolButton);
     if (d->menuAction)
         return d->menuAction->menu();
     return 0;
 }
minimumSizeHint()
QSize QToolButton::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 469 of file qtoolbutton.cpp.
 {
     return sizeHint();
 }
mousePressEvent()
void QToolButton::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 709 of file qtoolbutton.cpp.
 {
     Q_D(QToolButton);
 #ifndef QT_NO_MENU
     QStyleOptionToolButton opt;
     initStyleOption(&opt);
     if (e->button() == Qt::LeftButton && (d->popupMode == MenuButtonPopup)) {
         QRect popupr = style()->subControlRect(QStyle::CC_ToolButton, &opt,
                                                QStyle::SC_ToolButtonMenu, this);
         if (popupr.isValid() && popupr.contains(e->pos())) {
             d->buttonPressed = QToolButtonPrivate::MenuButtonPressed;
             showMenu();
             return;
         }
     }
 #endif
     d->buttonPressed = QToolButtonPrivate::ToolButtonPressed;
     QAbstractButton::mousePressEvent(e);
 }
mouseReleaseEvent()
void QToolButton::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 732 of file qtoolbutton.cpp.
 {
     Q_D(QToolButton);
     QAbstractButton::mouseReleaseEvent(e);
     d->buttonPressed = QToolButtonPrivate::NoButtonPressed;
 }
nextCheckState()
void QToolButton::nextCheckState () protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 1182 of file qtoolbutton.cpp.
 {
     Q_D(QToolButton);
     if (!d->defaultAction)
         QAbstractButton::nextCheckState();
     else
         d->defaultAction->trigger();
 }
paintEvent()
void QToolButton::paintEvent (QPaintEvent * event) protected virtual
Paints the button in response to the paint event.
Implements QAbstractButton.
Definition at line 565 of file qtoolbutton.cpp.
Referenced by QCalToolButton::paintEvent().
 {
     QStylePainter p(this);
     QStyleOptionToolButton opt;
     initStyleOption(&opt);
     p.drawComplexControl(QStyle::CC_ToolButton, opt);
 }
popupMode()
ToolButtonPopupMode QToolButton::popupMode () const
Referenced by QToolButtonPrivate::_q_buttonPressed(), QToolButtonPrivate::init(), and setPopupMode().
setArrowType()
void QToolButton::setArrowType (Qt::ArrowType type)
Definition at line 546 of file qtoolbutton.cpp.
Referenced by QTabBarPrivate::layoutTabs().
 {
     Q_D(QToolButton);
     if (d->arrowType == type)
         return;
     d->arrowType = type;
     d->sizeHint = QSize();
     updateGeometry();
     if (isVisible()) {
         update();
     }
 }
setAutoRaise()
void QToolButton::setAutoRaise (bool enable)
Definition at line 1107 of file qtoolbutton.cpp.
Referenced by QToolBarLayout::createItem(), QCalendarWidgetPrivate::createNavigationBar(), QMenuBarExtension::QMenuBarExtension(), QScriptNewBreakpointWidget::QScriptNewBreakpointWidget(), and QToolBarExtension::QToolBarExtension().
 {
     Q_D(QToolButton);
     d->autoRaise = enable;
     update();
 }
setDefaultAction
void QToolButton::setDefaultAction (QAction * action) slot
Sets the default action to action.
If a tool button has a default action, the action defines the button's properties like text, icon, tool tip, etc.
Definition at line 1127 of file qtoolbutton.cpp.
Referenced by actionEvent(), and QToolBarLayout::createItem().
 {
     Q_D(QToolButton);
 #ifndef QT_NO_MENU
     bool hadMenu = false;
     hadMenu = d->hasMenu();
 #endif
     d->defaultAction = action;
     if (!action)
         return;
     if (!actions().contains(action))
         addAction(action);
     setText(action->iconText());
     setIcon(action->icon());
 #ifndef QT_NO_TOOLTIP
     setToolTip(action->toolTip());
 #endif
 #ifndef QT_NO_STATUSTIP
     setStatusTip(action->statusTip());
 #endif
 #ifndef QT_NO_WHATSTHIS
     setWhatsThis(action->whatsThis());
 #endif
 #ifndef QT_NO_MENU
     if (action->menu() && !hadMenu) {
         // new 'default' popup mode defined introduced by tool bar. We
         // should have changed QToolButton's default instead. Do that
         // in 4.2.
         setPopupMode(QToolButton::MenuButtonPopup);
     }
 #endif
     setCheckable(action->isCheckable());
     setChecked(action->isChecked());
     setEnabled(action->isEnabled());
     if (action->d_func()->fontSet)
         setFont(action->font());
 }
setMenu()
void QToolButton::setMenu (QMenu * menu)
Associates the given menu with this tool button.
The menu will be shown according to the button's popupMode .
Ownership of the menu is not transferred to the tool button.
See also
menu()
Definition at line 847 of file qtoolbutton.cpp.
Referenced by QCalendarWidgetPrivate::createNavigationBar(), and QToolBarLayout::setUsePopupMenu().
 {
     Q_D(QToolButton);
     if (d->menuAction)
         removeAction(d->menuAction);
     if (menu) {
         d->menuAction = menu->menuAction();
         addAction(d->menuAction);
     } else {
         d->menuAction = 0;
     }
     update();
 }
setPopupMode()
void QToolButton::setPopupMode (ToolButtonPopupMode mode)
Definition at line 1083 of file qtoolbutton.cpp.
Referenced by QCalendarWidgetPrivate::createNavigationBar(), QMenuBarExtension::QMenuBarExtension(), setDefaultAction(), and QToolBarLayout::setUsePopupMenu().
 {
     Q_D(QToolButton);
     d->popupMode = mode;
 }
setToolButtonStyle
void QToolButton::setToolButtonStyle (Qt::ToolButtonStyle style) slot
Definition at line 532 of file qtoolbutton.cpp.
Referenced by QToolBarLayout::createItem().
 {
     Q_D(QToolButton);
     if (d->toolButtonStyle == style)
         return;
     d->toolButtonStyle = style;
     d->sizeHint = QSize();
     updateGeometry();
     if (isVisible()) {
         update();
     }
 }
showMenu
void QToolButton::showMenu () slot
Shows (pops up) the associated popup menu.
If there is no such menu, this function does nothing. This function does not return until the popup menu has been closed by the user.
Definition at line 881 of file qtoolbutton.cpp.
Referenced by QAccessibleToolButton::doAction(), and mousePressEvent().
 {
     Q_D(QToolButton);
     if (!d->hasMenu()) {
         d->menuButtonDown = false;
         return; // no menu to show
     }
     // prevent recursions spinning another event loop
     if (d->menuButtonDown)
         return;
     d->menuButtonDown = true;
     repaint();
     d->popupTimer.stop();
     d->popupTimerDone();
 }
sizeHint()
QSize QToolButton::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 417 of file qtoolbutton.cpp.
Referenced by minimumSizeHint().
 {
     Q_D(const QToolButton);
     if (d->sizeHint.isValid())
         return d->sizeHint;
     ensurePolished();
     int w = 0, h = 0;
     QStyleOptionToolButton opt;
     initStyleOption(&opt);
     QFontMetrics fm = fontMetrics();
     if (opt.toolButtonStyle != Qt::ToolButtonTextOnly) {
         QSize icon = opt.iconSize;
         w = icon.width();
         h = icon.height();
 #ifdef Q_WS_MAC
         extern CGFloat qt_mac_get_scalefactor();
         w /= qt_mac_get_scalefactor();
         h /= qt_mac_get_scalefactor();
 #endif
     }
     if (opt.toolButtonStyle != Qt::ToolButtonIconOnly) {
         QSize textSize = fm.size(Qt::TextShowMnemonic, text());
         textSize.setWidth(textSize.width() + fm.width(QLatin1Char(' '))*2);
         if (opt.toolButtonStyle == Qt::ToolButtonTextUnderIcon) {
             h += 4 + textSize.height();
             if (textSize.width() > w)
                 w = textSize.width();
         } else if (opt.toolButtonStyle == Qt::ToolButtonTextBesideIcon) {
             w += 4 + textSize.width();
             if (textSize.height() > h)
                 h = textSize.height();
         } else { // TextOnly
             w = textSize.width();
             h = textSize.height();
         }
     }
     opt.rect.setSize(QSize(w, h)); // PM_MenuButtonIndicator depends on the height
     if (d->popupMode == MenuButtonPopup)
         w += style()->pixelMetric(QStyle::PM_MenuButtonIndicator, &opt, this);
     d->sizeHint = style()->sizeFromContents(QStyle::CT_ToolButton, &opt, QSize(w, h), this).
                   expandedTo(QApplication::globalStrut());
     return d->sizeHint;
 }
timerEvent()
void QToolButton::timerEvent (QTimerEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractButton.
Definition at line 668 of file qtoolbutton.cpp.
 {
 #ifndef QT_NO_MENU
     Q_D(QToolButton);
     if (e->timerId() == d->popupTimer.timerId()) {
         d->popupTimerDone();
         return;
     }
 #endif
     QAbstractButton::timerEvent(e);
 }
toolButtonStyle()
Qt::ToolButtonStyle QToolButton::toolButtonStyle () const
Referenced by QToolButtonPrivate::init(), and minimumSizeHint().
triggered
void QToolButton::triggered (QAction * action) signal
This signal is emitted when the given action is triggered.
The action may also be associated with other parts of the user interface, such as menu items and keyboard shortcuts. Sharing actions in this way helps make the user interface more consistent and is often less work to implement.
Referenced by actionEvent(), and QToolButtonPrivate::popupTimerDone().
Properties
arrowType
Qt::ArrowType QToolButton::arrowType private
whether the button displays an arrow instead of a normal icon
This displays an arrow as the icon for the QToolButton.
By default, this property is set to Qt::NoArrow.
Definition at line 68 of file qtoolbutton.h.
autoRaise
bool QToolButton::autoRaise private
whether auto-raising is enabled or not.
The default is disabled (i.e. false).
This property is currently ignored on Mac OS X when using QMacStyle.
Definition at line 67 of file qtoolbutton.h.
popupMode
QToolButton::ToolButtonPopupMode QToolButton::popupMode private
describes the way that popup menus are used with tool buttons
By default, this property is set to DelayedPopup .
Definition at line 64 of file qtoolbutton.h.
Referenced by AccessibleFactory::create(), and QAccessibleToolButton::isSplitButton().
toolButtonStyle
Qt::ToolButtonStyle QToolButton::toolButtonStyle private
whether the tool button displays an icon only, text only, or text beside/below the icon.
The default is Qt::ToolButtonIconOnly.
To have the style of toolbuttons follow the system settings (as available in GNOME and KDE desktop environments), set this property to Qt::ToolButtonFollowStyle.
QToolButton automatically connects this slot to the relevant signal in the QMainWindow in which is resides.
Definition at line 66 of file qtoolbutton.h.
Referenced by qt_aqua_get_known_size().
The documentation for this class was generated from the following files:
/src/gui/widgets/qtoolbutton.h
/src/gui/widgets/qtoolbutton.cpp