Qt 4.8: QThreadStorageData Class Reference
QThreadStorageData Class Reference
#include <qthreadstorage.h>
Public Functions
void ** get () const
QThreadStorageData (void(*func)(void *))
void ** set (void *p)
~QThreadStorageData ()
Static Public Functions
static void finish (void **)
Public Variables
int id
Detailed Description
Definition at line 55 of file qthreadstorage.h.
Constructors and Destructors
QThreadStorageData()
QThreadStorageData::QThreadStorageData (void(*)(void *) func) explicit
Definition at line 78 of file qthreadstorage.cpp.
 {
     QMutexLocker locker(mutex());
     DestructorMap *destr = destructors();
     if (!destr) {
         /*
          the destructors vector has already been destroyed, yet a new
          QThreadStorage is being allocated. this can only happen during global
          destruction, at which point we assume that there is only one thread.
          in order to keep QThreadStorage working, we need somewhere to store
          the data, best place we have in this situation is at the tail of the
          current thread's tls vector. the destructor is ignored, since we have
          no where to store it, and no way to actually call it.
          */
         QThreadData *data = QThreadData::current();
         id = data->tls.count();
         DEBUG_MSG("QThreadStorageData: Allocated id %d, destructor %p cannot be stored", id, func);
         return;
     }
     for (id = 0; id < destr->count(); id++) {
         if (destr->at(id) == 0)
             break;
     }
     if (id == destr->count()) {
         destr->append(func);
     } else {
         (*destr)[id] = func;
     }
     DEBUG_MSG("QThreadStorageData: Allocated id %d, destructor %p", id, func);
 }
~QThreadStorageData()
QThreadStorageData::~QThreadStorageData ()
Definition at line 109 of file qthreadstorage.cpp.
 {
     DEBUG_MSG("QThreadStorageData: Released id %d", id);
     QMutexLocker locker(mutex());
     if (destructors())
         (*destructors())[id] = 0;
 }
Functions
finish()
void QThreadStorageData::finish (void ** p) static
Definition at line 174 of file qthreadstorage.cpp.
Referenced by QThreadPrivate::finish(), and QCoreApplicationPrivate::~QCoreApplicationPrivate().
 {
     QVector<void *> *tls = reinterpret_cast<QVector<void *> *>(p);
     if (!tls || tls->isEmpty() || !mutex())
         return; // nothing to do
     DEBUG_MSG("QThreadStorageData: Destroying storage for thread %p", QThread::currentThread());
     while (!tls->isEmpty()) {
         void *&value = tls->last();
         void *q = value;
         value = 0;
         int i = tls->size() - 1;
         tls->resize(i);
         if (!q) {
             // data already deleted
             continue;
         }
         QMutexLocker locker(mutex());
         void (*destructor)(void *) = destructors()->value(i);
         locker.unlock();
         if (!destructor) {
             if (QThread::currentThread())
                 qWarning("QThreadStorage: Thread %p exited after QThreadStorage %d destroyed",
                          QThread::currentThread(), i);
             continue;
         }
         destructor(q); //crash here might mean the thread exited after qthreadstorage was destroyed
         if (tls->size() > i) {
             //re reset the tls in case it has been recreated by its own destructor.
             (*tls)[i] = 0;
         }
     }
     tls->clear();
 }
get()
void ** QThreadStorageData::get () const
Definition at line 117 of file qthreadstorage.cpp.
Referenced by QThreadStorage< QNetworkAccessCache *>::hasLocalData(), qThreadStorage_localData(), and qThreadStorage_localData_const().
 {
     QThreadData *data = QThreadData::current();
     if (!data) {
         qWarning("QThreadStorage::get: QThreadStorage can only be used with threads started with QThread");
         return 0;
     }
     QVector<void *> &tls = data->tls;
     if (tls.size() <= id)
         tls.resize(id + 1);
     void **v = &tls[id];
     DEBUG_MSG("QThreadStorageData: Returning storage %d, data %p, for thread %p",
           id,
           *v,
           data->thread);
     return *v ? v : 0;
 }
set()
void ** QThreadStorageData::set (void * p)
Definition at line 137 of file qthreadstorage.cpp.
Referenced by qThreadStorage_localData().
 {
     QThreadData *data = QThreadData::current();
     if (!data) {
         qWarning("QThreadStorage::set: QThreadStorage can only be used with threads started with QThread");
         return 0;
     }
     QVector<void *> &tls = data->tls;
     if (tls.size() <= id)
         tls.resize(id + 1);
     void *&value = tls[id];
     // delete any previous data
     if (value != 0) {
         DEBUG_MSG("QThreadStorageData: Deleting previous storage %d, data %p, for thread %p",
                 id,
                 value,
                 data->thread);
         QMutexLocker locker(mutex());
         DestructorMap *destr = destructors();
         void (*destructor)(void *) = destr ? destr->value(id) : 0;
         locker.unlock();
         void *q = value;
         value = 0;
         if (destructor)
             destructor(q);
     }
     // store new data
     value = p;
     DEBUG_MSG("QThreadStorageData: Set storage %d for thread %p to %p", id, data->thread, p);
     return &value;
 }
Properties
id
int QThreadStorageData::id
Definition at line 65 of file qthreadstorage.h.
Referenced by get(), and set().
The documentation for this class was generated from the following files:
/src/corelib/thread/qthreadstorage.h
/src/corelib/thread/qthreadstorage.cpp