Qt 4.8: QScriptContextInfo Class Reference
QScriptContextInfo Class Reference
The QScriptContextInfo class provides additional information about a QScriptContext.
#include <qscriptcontextinfo.h>
Public Types
enum FunctionType { ScriptFunction, QtFunction, QtPropertyFunction, NativeFunction }
This enum specifies the type of function being called.
Public Functions
QT_DEPRECATED int columnNumber () const
QString fileName () const
Returns the name of the file where the code being executed was defined, if available; otherwise returns an empty string.
int functionEndLineNumber () const
Returns the line number where the definition of the called function ends, or -1 if the line number is not available.
int functionMetaIndex () const
Returns the meta index of the called function, or -1 if the meta index is not available.
QString functionName () const
Returns the name of the called function, or an empty string if the name is not available.
QStringList functionParameterNames () const
Returns the names of the formal parameters of the called function, or an empty QStringList if the parameter names are not available.
int functionStartLineNumber () const
Returns the line number where the definition of the called function starts, or -1 if the line number is not available.
FunctionType functionType () const
Returns the type of the called function.
bool isNull () const
Returns true if this QScriptContextInfo is null, i.e.
int lineNumber () const
Returns the line number corresponding to the statement being executed, or -1 if the line number is not available.
bool operator!= (const QScriptContextInfo &other) const
Returns true if this QScriptContextInfo is not equal to the other info, otherwise returns false.
QScriptContextInfo & operator= (const QScriptContextInfo &other)
Assigns the other info to this QScriptContextInfo, and returns a reference to this QScriptContextInfo.
bool operator== (const QScriptContextInfo &other) const
Returns true if this QScriptContextInfo is equal to the other info, otherwise returns false.
QScriptContextInfo (const QScriptContext *context)
Constructs a new QScriptContextInfo from the given context.
QScriptContextInfo (const QScriptContextInfo &other)
Constructs a new QScriptContextInfo from the other info.
QScriptContextInfo ()
Constructs a null QScriptContextInfo.
qint64 scriptId () const
Returns the ID of the script where the code being executed was defined, or -1 if the ID is not available (i.e.
~QScriptContextInfo ()
Destroys the QScriptContextInfo.
Properties
QExplicitlySharedDataPointer< QScriptContextInfoPrivate > d_ptr
Friends
Q_SCRIPT_EXPORT QDataStream & operator<< (QDataStream &, const QScriptContextInfo &)
Writes the given info to the specified stream.
Q_SCRIPT_EXPORT QDataStream & operator>> (QDataStream &, QScriptContextInfo &)
Reads a QScriptContextInfo from the specified stream into the given info.
Detailed Description
The QScriptContextInfo class provides additional information about a QScriptContext.
Since
4.4
QScriptContextInfo is typically used for debugging purposes. It can provide information about the code being executed, such as the type of the called function, and the original source code location of the current statement.
If the called function is executing Qt Script code, you can obtain the script location with the functions fileName() and lineNumber().
You can obtain the starting line number and ending line number of a Qt Script function definition with functionStartLineNumber() and functionEndLineNumber(), respectively.
For Qt Script functions and Qt methods (e.g. slots), you can call functionParameterNames() to get the names of the formal parameters of the function.
For Qt methods and Qt property accessors, you can obtain the index of the underlying QMetaMethod or QMetaProperty by calling functionMetaIndex().
See also
QScriptContext, QScriptEngineAgent
Definition at line 45 of file qscriptcontextinfo.h.
Enumerations
FunctionType
enum QScriptContextInfo::FunctionType
This enum specifies the type of function being called.
ScriptFunction The function is a Qt Script function, i.e. it was defined through a call to QScriptEngine::evaluate().
QtFunction The function is a Qt function (a signal, slot or method).
QtPropertyFunction The function is a Qt property getter or setter.
NativeFunction The function is a built-in Qt Script function, or it was defined through a call to QScriptEngine::newFunction().
Enumerator
ScriptFunction
QtFunction
QtPropertyFunction
NativeFunction
Definition at line 53 of file qscriptcontextinfo.h.
                       {
         ScriptFunction,
         QtFunction,
         QtPropertyFunction,
         NativeFunction
     };
Constructors and Destructors
QScriptContextInfo() [1/3]
QScriptContextInfo::QScriptContextInfo (const QScriptContext * context)
Constructs a new QScriptContextInfo from the given context.
The relevant information is extracted from the context at construction time; i.e. if you continue script execution in the context, the new state of the context will not be reflected in a previously created QScriptContextInfo.
Definition at line 240 of file qscriptcontextinfo.cpp.
     : d_ptr(0)
 {
     if (context) {
         d_ptr = new QScriptContextInfoPrivate(context);
         d_ptr->q_ptr = this;
     }
 }
QScriptContextInfo() [2/3]
QScriptContextInfo::QScriptContextInfo (const QScriptContextInfo & other)
Constructs a new QScriptContextInfo from the other info.
Definition at line 252 of file qscriptcontextinfo.cpp.
     : d_ptr(other.d_ptr)
 {
 }
QScriptContextInfo() [3/3]
QScriptContextInfo::QScriptContextInfo ()
Constructs a null QScriptContextInfo.
See also
isNull()
Definition at line 262 of file qscriptcontextinfo.cpp.
     : d_ptr(0)
 {
 }
~QScriptContextInfo()
QScriptContextInfo::~QScriptContextInfo ()
Destroys the QScriptContextInfo.
Definition at line 270 of file qscriptcontextinfo.cpp.
 {
 }
Functions
columnNumber()
int QScriptContextInfo::columnNumber () const
Definition at line 336 of file qscriptcontextinfo.cpp.
Referenced by contextInfoToScriptValue(), and operator<<().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return -1;
     return d->columnNumber;
 }
fileName()
QString QScriptContextInfo::fileName () const
Returns the name of the file where the code being executed was defined, if available; otherwise returns an empty string.
For Qt Script code, this function returns the fileName argument that was passed to QScriptEngine::evaluate().
See also
lineNumber(), functionName()
Definition at line 308 of file qscriptcontextinfo.cpp.
Referenced by QJSDebuggerAgent::backtrace(), contextInfoToScriptValue(), QScriptDebuggerStackModel::data(), operator<<(), QJSDebuggerAgentPrivate::positionChange(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), and QScriptContext::toString().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return QString();
     return d->fileName;
 }
functionEndLineNumber()
int QScriptContextInfo::functionEndLineNumber () const
Returns the line number where the definition of the called function ends, or -1 if the line number is not available.
The ending line number is only available if the functionType() is ScriptFunction.
See also
functionStartLineNumber()
Definition at line 402 of file qscriptcontextinfo.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), and operator<<().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return -1;
     return d->functionEndLineNumber;
 }
functionMetaIndex()
int QScriptContextInfo::functionMetaIndex () const
Returns the meta index of the called function, or -1 if the meta index is not available.
The meta index is only available if the functionType() is QtFunction or QtPropertyFunction. For QtFunction, the meta index can be passed to QMetaObject::method() to obtain the corresponding method definition; for QtPropertyFunction, the meta index can be passed to QMetaObject::property() to obtain the corresponding property definition.
See also
QScriptContext::thisObject()
Definition at line 437 of file qscriptcontextinfo.cpp.
Referenced by operator<<().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return -1;
     return d->functionMetaIndex;
 }
functionName()
QString QScriptContextInfo::functionName () const
Returns the name of the called function, or an empty string if the name is not available.
For script functions of type QtPropertyFunction, this function always returns the name of the property; you can use QScriptContext::argumentCount() to differentiate between reads and writes.
See also
fileName(), functionType()
Definition at line 355 of file qscriptcontextinfo.cpp.
Referenced by QJSDebuggerAgent::backtrace(), contextInfoToScriptValue(), QScriptDebuggerStackModel::data(), operator<<(), and QScriptContext::toString().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return QString();
     return d->functionName;
 }
functionParameterNames()
QStringList QScriptContextInfo::functionParameterNames () const
Returns the names of the formal parameters of the called function, or an empty QStringList if the parameter names are not available.
See also
QScriptContext::argument()
Definition at line 416 of file qscriptcontextinfo.cpp.
Referenced by operator<<(), and QScriptContext::toString().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return QStringList();
     return d->parameterNames;
 }
functionStartLineNumber()
int QScriptContextInfo::functionStartLineNumber () const
Returns the line number where the definition of the called function starts, or -1 if the line number is not available.
The starting line number is only available if the functionType() is ScriptFunction.
See also
functionEndLineNumber(), fileName()
Definition at line 385 of file qscriptcontextinfo.cpp.
Referenced by QJSDebuggerAgent::backtrace(), QScriptDebuggerCommandExecutor::execute(), operator<<(), QDeclarativeValueTypeScriptClass::setProperty(), and QDeclarativeObjectScriptClass::setProperty().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return -1;
     return d->functionStartLineNumber;
 }
functionType()
QScriptContextInfo::FunctionType QScriptContextInfo::functionType () const
Returns the type of the called function.
See also
functionName(), QScriptContext::callee()
Definition at line 368 of file qscriptcontextinfo.cpp.
Referenced by QJSDebuggerAgent::backtrace(), QScriptDebuggerStackModel::data(), operator<<(), QJSDebuggerAgentPrivate::positionChange(), and QScriptContext::toString().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return NativeFunction;
     return d->functionType;
 }
isNull()
bool QScriptContextInfo::isNull () const
Returns true if this QScriptContextInfo is null, i.e.
does not contain any information.
Definition at line 449 of file qscriptcontextinfo.cpp.
 {
     Q_D(const QScriptContextInfo);
     return (d == 0);
 }
lineNumber()
int QScriptContextInfo::lineNumber () const
Returns the line number corresponding to the statement being executed, or -1 if the line number is not available.
The line number is only available if Qt Script code is being executed.
See also
columnNumber(), fileName()
Definition at line 325 of file qscriptcontextinfo.cpp.
Referenced by QJSDebuggerAgent::backtrace(), contextInfoToScriptValue(), QScriptDebuggerStackModel::data(), operator<<(), and QScriptContext::toString().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return -1;
     return d->lineNumber;
 }
operator!=()
bool QScriptContextInfo::operator!= (const QScriptContextInfo & other) const
Returns true if this QScriptContextInfo is not equal to the other info, otherwise returns false.
Definition at line 483 of file qscriptcontextinfo.cpp.
 {
     return !(*this == other);
 }
operator=()
QScriptContextInfo & QScriptContextInfo::operator= (const QScriptContextInfo & other)
Assigns the other info to this QScriptContextInfo, and returns a reference to this QScriptContextInfo.
Definition at line 278 of file qscriptcontextinfo.cpp.
 {
     d_ptr = other.d_ptr;
     return *this;
 }
operator==()
bool QScriptContextInfo::operator== (const QScriptContextInfo & other) const
Returns true if this QScriptContextInfo is equal to the other info, otherwise returns false.
Definition at line 459 of file qscriptcontextinfo.cpp.
 {
     Q_D(const QScriptContextInfo);
     const QScriptContextInfoPrivate *od = other.d_func();
     if (d == od)
         return true;
     if (!d || !od)
         return false;
     return ((d->scriptId == od->scriptId)
             && (d->lineNumber == od->lineNumber)
             && (d->columnNumber == od->columnNumber)
             && (d->fileName == od->fileName)
             && (d->functionName == od->functionName)
             && (d->functionType == od->functionType)
             && (d->functionStartLineNumber == od->functionStartLineNumber)
             && (d->functionEndLineNumber == od->functionEndLineNumber)
             && (d->functionMetaIndex == od->functionMetaIndex)
             && (d->parameterNames == od->parameterNames));
 }
scriptId()
qint64 QScriptContextInfo::scriptId () const
Returns the ID of the script where the code being executed was defined, or -1 if the ID is not available (i.e.
a native function is being executed).
See also
QScriptEngineAgent::scriptLoad()
Definition at line 291 of file qscriptcontextinfo.cpp.
Referenced by contextInfoToScriptValue(), QScriptDebuggerStackModel::data(), and operator<<().
 {
     Q_D(const QScriptContextInfo);
     if (!d)
         return -1;
     return d->scriptId;
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & stream, const QScriptContextInfo & info) friend
Writes the given info to the specified stream.
Since
4.4
Definition at line 499 of file qscriptcontextinfo.cpp.
 {
     out << info.scriptId();
     out << (qint32)info.lineNumber();
     out << (qint32)info.columnNumber();
     out << (quint32)info.functionType();
     out << (qint32)info.functionStartLineNumber();
     out << (qint32)info.functionEndLineNumber();
     out << (qint32)info.functionMetaIndex();
     out << info.fileName();
     out << info.functionName();
     out << info.functionParameterNames();
     return out;
 }
operator>>
QDataStream & operator>> (QDataStream & stream, QScriptContextInfo & info) friend
Reads a QScriptContextInfo from the specified stream into the given info.
Since
4.4
Definition at line 528 of file qscriptcontextinfo.cpp.
 {
     if (!info.d_ptr) {
         info.d_ptr = new QScriptContextInfoPrivate();
     }
     in >> info.d_ptr->scriptId;
     qint32 line;
     in >> line;
     info.d_ptr->lineNumber = line;
     qint32 column;
     in >> column;
     info.d_ptr->columnNumber = column;
     quint32 ftype;
     in >> ftype;
     info.d_ptr->functionType = QScriptContextInfo::FunctionType(ftype);
     qint32 startLine;
     in >> startLine;
     info.d_ptr->functionStartLineNumber = startLine;
     qint32 endLine;
     in >> endLine;
     info.d_ptr->functionEndLineNumber = endLine;
     qint32 metaIndex;
     in >> metaIndex;
     info.d_ptr->functionMetaIndex = metaIndex;
     in >> info.d_ptr->fileName;
     in >> info.d_ptr->functionName;
     in >> info.d_ptr->parameterNames;
     return in;
 }
Properties
d_ptr
QExplicitlySharedDataPointer<QScriptContextInfoPrivate> QScriptContextInfo::d_ptr private
Definition at line 90 of file qscriptcontextinfo.h.
Referenced by operator=(), operator>>(), and QScriptContextInfo().
The documentation for this class was generated from the following files:
/src/script/api/qscriptcontextinfo.h
/src/script/api/qscriptcontextinfo.cpp