Qt 4.8: QPaintEnginePrivate Class Reference
QPaintEnginePrivate Class Reference
#include <qpaintengine_p.h>
Public Functions
void drawBoxTextItem (const QPointF &p, const QTextItemInt &ti)
QPaintEnginePrivate ()
void setSystemTransform (const QTransform &xform)
void setSystemViewport (const QRegion &region)
virtual void systemStateChanged ()
void transformSystemClip ()
virtual ~QPaintEnginePrivate ()
Public Variables
QWidget * currentClipWidget
uint hasSystemTransform: 1
uint hasSystemViewport: 1
QPaintDevice * pdev
QPaintEngine * q_ptr
QRegion systemClip
QRect systemRect
QTransform systemTransform
QRegion systemViewport
Detailed Description
Definition at line 65 of file qpaintengine_p.h.
Constructors and Destructors
QPaintEnginePrivate()
QPaintEnginePrivate::QPaintEnginePrivate () inline
Definition at line 69 of file qpaintengine_p.h.
                           : pdev(0), q_ptr(0), currentClipWidget(0), hasSystemTransform(0),
                             hasSystemViewport(0) {}
~QPaintEnginePrivate()
virtual QPaintEnginePrivate::~QPaintEnginePrivate () inline virtual
Definition at line 71 of file qpaintengine_p.h.
 { }
Functions
drawBoxTextItem()
void QPaintEnginePrivate::drawBoxTextItem (const QPointF & p, const QTextItemInt & ti)
Definition at line 1098 of file qpaintengine.cpp.
Referenced by systemStateChanged().
 {
     if (!ti.glyphs.numGlyphs)
         return;
     // any fixes here should probably also be done in QFontEngineBox::draw
     const int size = qRound(ti.fontEngine->ascent());
     QVarLengthArray<QFixedPoint> positions;
     QVarLengthArray<glyph_t> glyphs;
     QTransform matrix = QTransform::fromTranslate(p.x(), p.y() - size);
     ti.fontEngine->getGlyphPositions(ti.glyphs, matrix, ti.flags, glyphs, positions);
     if (glyphs.size() == 0)
         return;
     QSize s(size - 3, size - 3);
     QPainter *painter = q_func()->state->painter();
     painter->save();
     painter->setBrush(Qt::NoBrush);
     QPen pen = painter->pen();
     pen.setWidthF(ti.fontEngine->lineThickness().toReal());
     painter->setPen(pen);
     for (int k = 0; k < positions.size(); k++)
         painter->drawRect(QRectF(positions[k].toPointF(), s));
     painter->restore();
 }
setSystemTransform()
void QPaintEnginePrivate::setSystemTransform (const QTransform & xform) inline
Definition at line 104 of file qpaintengine_p.h.
Referenced by QPainterPrivate::attachPainterPrivate(), and QWidget::render().
     {
         systemTransform = xform;
         if ((hasSystemTransform = !xform.isIdentity()) || hasSystemViewport)
             transformSystemClip();
         systemStateChanged();
     }
setSystemViewport()
void QPaintEnginePrivate::setSystemViewport (const QRegion & region) inline
Definition at line 112 of file qpaintengine_p.h.
Referenced by QWidget::render().
     {
         systemViewport = region;
         hasSystemViewport = !systemViewport.isEmpty();
     }
systemStateChanged()
virtual void QPaintEnginePrivate::systemStateChanged () inline virtual
Reimplemented in QOpenGLPaintEnginePrivate, QPaintBufferEnginePrivate, QRasterPaintEnginePrivate, QGL2PaintEngineExPrivate, QX11PaintEnginePrivate, QVGPaintEnginePrivate, and QDirectFBPaintEnginePrivate.
Definition at line 118 of file qpaintengine_p.h.
Referenced by QPainterPrivate::attachPainterPrivate(), QPainterReplayer::process(), and setSystemTransform().
 { }
transformSystemClip()
void QPaintEnginePrivate::transformSystemClip () inline
Definition at line 82 of file qpaintengine_p.h.
Referenced by setSystemTransform().
     {
         if (systemClip.isEmpty())
             return;
         if (hasSystemTransform) {
             if (systemTransform.type() <= QTransform::TxTranslate)
                 systemClip.translate(qRound(systemTransform.dx()), qRound(systemTransform.dy()));
             else
                 systemClip = systemTransform.map(systemClip);
         }
         // Make sure we're inside the viewport.
         if (hasSystemViewport) {
             systemClip &= systemViewport;
             if (systemClip.isEmpty()) {
                 // We don't want to paint without system clip, so set it to 1 pixel :)
                 systemClip = QRect(systemViewport.boundingRect().topLeft(), QSize(1, 1));
             }
         }
     }
Properties
currentClipWidget
QWidget* QPaintEnginePrivate::currentClipWidget
Definition at line 78 of file qpaintengine_p.h.
Referenced by QPainterPrivate::attachPainterPrivate().
hasSystemTransform
uint QPaintEnginePrivate::hasSystemTransform
Definition at line 79 of file qpaintengine_p.h.
Referenced by setSystemTransform(), and transformSystemClip().
hasSystemViewport
uint QPaintEnginePrivate::hasSystemViewport
Definition at line 80 of file qpaintengine_p.h.
Referenced by setSystemTransform(), setSystemViewport(), and transformSystemClip().
pdev
QPaintDevice* QPaintEnginePrivate::pdev
Definition at line 72 of file qpaintengine_p.h.
Referenced by QAlphaPaintEngine::begin().
q_ptr
QPaintEngine* QPaintEnginePrivate::q_ptr
Definition at line 73 of file qpaintengine_p.h.
Referenced by QPSPrintEnginePrivate::emitHeader(), and QPaintEngine::QPaintEngine().
systemClip
QRegion QPaintEnginePrivate::systemClip
Definition at line 74 of file qpaintengine_p.h.
Referenced by QWidget::render().
systemRect
QRect QPaintEnginePrivate::systemRect
Definition at line 75 of file qpaintengine_p.h.
systemTransform
QTransform QPaintEnginePrivate::systemTransform
Definition at line 77 of file qpaintengine_p.h.
Referenced by QWidget::render().
systemViewport
QRegion QPaintEnginePrivate::systemViewport
Definition at line 76 of file qpaintengine_p.h.
Referenced by QWidget::render(), and transformSystemClip().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengine_p.h
/src/gui/painting/qpaintengine.cpp