Qt 4.8: QTextBlockFormat Class Reference
QTextBlockFormat Class Reference
The QTextBlockFormat class provides formatting information for blocks of text in a QTextDocument.
#include <qtextformat.h>
Public Types
enum LineHeightTypes {
SingleHeight = 0, ProportionalHeight = 1, FixedHeight = 2, MinimumHeight = 3,
LineDistanceHeight = 4
}
This enum describes the various types of line spacing support paragraphs can have.
Public Types inherited from QTextFormat
enum FormatType {
InvalidFormat = -1, BlockFormat = 1, CharFormat = 2, ListFormat = 3,
TableFormat = 4, FrameFormat = 5, UserFormat = 100
}
This enum describes the text item a QTextFormat object is formatting.
enum ObjectTypes {
NoObject, ImageObject, TableObject, TableCellObject,
UserObject = 0x1000
}
This enum describes what kind of QTextObject this format is associated with.
enum PageBreakFlag { PageBreak_Auto = 0, PageBreak_AlwaysBefore = 0x001, PageBreak_AlwaysAfter = 0x010 }
This enum describes how page breaking is performed when printing.
enum Property {
ObjectIndex = 0x0, CssFloat = 0x0800, LayoutDirection = 0x0801, OutlinePen = 0x810,
BackgroundBrush = 0x820, ForegroundBrush = 0x821, BackgroundImageUrl = 0x823, BlockAlignment = 0x1010,
BlockTopMargin = 0x1030, BlockBottomMargin = 0x1031, BlockLeftMargin = 0x1032, BlockRightMargin = 0x1033,
TextIndent = 0x1034, TabPositions = 0x1035, BlockIndent = 0x1040, LineHeight = 0x1048,
LineHeightType = 0x1049, BlockNonBreakableLines = 0x1050, BlockTrailingHorizontalRulerWidth = 0x1060, FirstFontProperty = 0x1FE0,
FontCapitalization = FirstFontProperty, FontLetterSpacing = 0x1FE1, FontWordSpacing = 0x1FE2, FontStyleHint = 0x1FE3,
FontStyleStrategy = 0x1FE4, FontKerning = 0x1FE5, FontHintingPreference = 0x1FE6, FontFamily = 0x2000,
FontPointSize = 0x2001, FontSizeAdjustment = 0x2002, FontSizeIncrement = FontSizeAdjustment, FontWeight = 0x2003,
FontItalic = 0x2004, FontUnderline = 0x2005, FontOverline = 0x2006, FontStrikeOut = 0x2007,
FontFixedPitch = 0x2008, FontPixelSize = 0x2009, LastFontProperty = FontPixelSize, TextUnderlineColor = 0x2010,
TextVerticalAlignment = 0x2021, TextOutline = 0x2022, TextUnderlineStyle = 0x2023, TextToolTip = 0x2024,
IsAnchor = 0x2030, AnchorHref = 0x2031, AnchorName = 0x2032, ObjectType = 0x2f00,
ListStyle = 0x3000, ListIndent = 0x3001, ListNumberPrefix = 0x3002, ListNumberSuffix = 0x3003,
FrameBorder = 0x4000, FrameMargin = 0x4001, FramePadding = 0x4002, FrameWidth = 0x4003,
FrameHeight = 0x4004, FrameTopMargin = 0x4005, FrameBottomMargin = 0x4006, FrameLeftMargin = 0x4007,
FrameRightMargin = 0x4008, FrameBorderBrush = 0x4009, FrameBorderStyle = 0x4010, TableColumns = 0x4100,
TableColumnWidthConstraints = 0x4101, TableCellSpacing = 0x4102, TableCellPadding = 0x4103, TableHeaderRowCount = 0x4104,
TableCellRowSpan = 0x4810, TableCellColumnSpan = 0x4811, TableCellTopPadding = 0x4812, TableCellBottomPadding = 0x4813,
TableCellLeftPadding = 0x4814, TableCellRightPadding = 0x4815, ImageName = 0x5000, ImageWidth = 0x5010,
ImageHeight = 0x5011, FullWidthSelection = 0x06000, PageBreakPolicy = 0x7000, UserProperty = 0x100000
}
This enum describes the different properties a format can have.
Public Functions
Qt::Alignment alignment () const
Returns the paragraph's alignment.
qreal bottomMargin () const
Returns the paragraph's bottom margin.
int indent () const
Returns the paragraph's indent.
bool isValid () const
Returns true if this block format is valid; otherwise returns false.
qreal leftMargin () const
Returns the paragraph's left margin.
qreal lineHeight (qreal scriptLineHeight, qreal scaling) const
Returns the height of the lines in the paragraph based on the height of the script line given by scriptLineHeight and the specified scaling factor.
qreal lineHeight () const
This returns the LineHeight property for the paragraph.
int lineHeightType () const
This returns the LineHeightType property of the paragraph.
bool nonBreakableLines () const
Returns true if the lines in the paragraph are non-breakable; otherwise returns false.
PageBreakFlags pageBreakPolicy () const
Returns the currently set page break policy for the paragraph.
QTextBlockFormat ()
Constructs a new QTextBlockFormat.
qreal rightMargin () const
Returns the paragraph's right margin.
void setAlignment (Qt::Alignment alignment)
Sets the paragraph's alignment.
void setBottomMargin (qreal margin)
Sets the paragraph's bottom margin.
void setIndent (int indent)
Sets the paragraph's indentation.
void setLeftMargin (qreal margin)
Sets the paragraph's left margin.
void setLineHeight (qreal height, int heightType)
Sets the line height for the paragraph to the value given by height which is dependent on heightType in the way described by the LineHeightTypes enum.
void setNonBreakableLines (bool b)
If b is true, the lines in the paragraph are treated as non-breakable; otherwise they are breakable.
void setPageBreakPolicy (PageBreakFlags flags)
Sets the page break policy for the paragraph to policy.
void setRightMargin (qreal margin)
Sets the paragraph's right margin.
void setTabPositions (const QList< QTextOption::Tab > &tabs)
Sets the tab positions for the text block to those specified by tabs.
void setTextIndent (qreal aindent)
Sets the indent for the first line in the block.
void setTopMargin (qreal margin)
Sets the paragraph's top margin.
QList< QTextOption::Tab > tabPositions () const
Returns a list of tab positions defined for the text block.
qreal textIndent () const
Returns the paragraph's text indent.
qreal topMargin () const
Returns the paragraph's top margin.
Public Functions inherited from QTextFormat
QBrush background () const
Returns the brush used to paint the document's background.
bool boolProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush brushProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Brush type, Qt::NoBrush is returned instead.
void clearBackground ()
Clears the brush used to paint the document's background.
void clearForeground ()
Clears the brush used to paint the document's foreground.
void clearProperty (int propertyId)
Clears the value of the property given by propertyId.
QColor colorProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Color type, an invalid color is returned instead.
qreal doubleProperty (int propertyId) const
Returns the value of the property specified by propertyId.
QBrush foreground () const
Returns the brush used to render foreground details, such as text, frame outlines, and table borders.
bool hasProperty (int propertyId) const
Returns true if the text format has a property with the given propertyId; otherwise returns false.
int intProperty (int propertyId) const
Returns the value of the property specified by propertyId.
bool isBlockFormat () const
Returns true if this text format is a BlockFormat; otherwise returns false.
bool isCharFormat () const
Returns true if this text format is a CharFormat; otherwise returns false.
bool isFrameFormat () const
Returns true if this text format is a FrameFormat; otherwise returns false.
bool isImageFormat () const
Returns true if this text format is an image format; otherwise returns false.
bool isListFormat () const
Returns true if this text format is a ListFormat; otherwise returns false.
bool isTableCellFormat () const
Returns true if this text format is a TableCellFormat; otherwise returns false.
bool isTableFormat () const
Returns true if this text format is a TableFormat; otherwise returns false.
bool isValid () const
Returns true if the format is valid (i.
Qt::LayoutDirection layoutDirection () const
Returns the document's layout direction.
QTextLength lengthProperty (int propertyId) const
Returns the value of the property given by propertyId.
QVector< QTextLength > lengthVectorProperty (int propertyId) const
Returns the value of the property given by propertyId.
void merge (const QTextFormat &other)
Merges the other format with this format; where there are conflicts the other format takes precedence.
int objectIndex () const
Returns the index of the format object, or -1 if the format object is invalid.
int objectType () const
Returns the text format's object type.
operator QVariant () const
Returns the text format as a QVariant.
bool operator!= (const QTextFormat &rhs) const
Returns true if this text format is different from the other text format.
QTextFormat & operator= (const QTextFormat &rhs)
Assigns the other text format to this text format, and returns a reference to this text format.
bool operator== (const QTextFormat &rhs) const
Returns true if this text format is the same as the other text format.
QPen penProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::Pen type, Qt::NoPen is returned instead.
QMap< int, QVariant > properties () const
Returns a map with all properties of this text format.
QVariant property (int propertyId) const
Returns the property specified by the given propertyId.
int propertyCount () const
Returns the number of properties stored in the format.
QTextFormat ()
Creates a new text format with an InvalidFormat.
QTextFormat (int type)
Creates a new text format of the given type.
QTextFormat (const QTextFormat &rhs)
Creates a new text format with the same attributes as the other text format.
void setBackground (const QBrush &brush)
Sets the brush use to paint the document's background to the brush specified.
void setForeground (const QBrush &brush)
Sets the foreground brush to the specified brush.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the document's layout direction to the specified direction.
void setObjectIndex (int object)
Sets the format object's object index.
void setObjectType (int type)
Sets the text format's object type to type.
void setProperty (int propertyId, const QVariant &value)
Sets the property specified by the propertyId to the given value.
void setProperty (int propertyId, const QVector< QTextLength > &lengths)
Sets the value of the property given by propertyId to value.
QString stringProperty (int propertyId) const
Returns the value of the property given by propertyId; if the property isn't of QVariant::String type, an empty string is returned instead.
QTextBlockFormat toBlockFormat () const
Returns this format as a block format.
QTextCharFormat toCharFormat () const
Returns this format as a character format.
QTextFrameFormat toFrameFormat () const
Returns this format as a frame format.
QTextImageFormat toImageFormat () const
Returns this format as an image format.
QTextListFormat toListFormat () const
Returns this format as a list format.
QTextTableCellFormat toTableCellFormat () const
Returns this format as a table cell format.
QTextTableFormat toTableFormat () const
Returns this format as a table format.
int type () const
Returns the type of this format.
~QTextFormat ()
Destroys this text format.
Protected Functions
QTextBlockFormat (const QTextFormat &fmt)
Creates a new block format with the same attributes as the given text format.
Friends
class QTextFormat
Detailed Description
The QTextBlockFormat class provides formatting information for blocks of text in a QTextDocument.
Note
This class or function is reentrant.
A document is composed of a list of blocks, represented by QTextBlock objects. Each block can contain an item of some kind, such as a paragraph of text, a table, a list, or an image. Every block has an associated QTextBlockFormat that specifies its characteristics.
To cater for left-to-right and right-to-left languages you can set a block's direction with setDirection(). Paragraph alignment is set with setAlignment(). Margins are controlled by setTopMargin(), setBottomMargin(), setLeftMargin(), setRightMargin(). Overall indentation is set with setIndent(), the indentation of the first line with setTextIndent().
Line spacing is set with setLineHeight() and retrieved via lineHeight() and lineHeightType(). The types of line spacing available are in the LineHeightTypes enum.
Line breaking can be enabled and disabled with setNonBreakableLines().
The brush used to paint the paragraph's background is set with setBackground(), and other aspects of the text's appearance can be customized by using the setProperty() function with the OutlinePen, ForegroundBrush, and BackgroundBrush QTextFormat::Property values.
If a text block is part of a list, it can also have a list format that is accessible with the listFormat() function.
See also
QTextBlock, QTextCharFormat
Definition at line 545 of file qtextformat.h.
Enumerations
LineHeightTypes
enum QTextBlockFormat::LineHeightTypes
This enum describes the various types of line spacing support paragraphs can have.
Since
4.8
SingleHeight This is the default line height: single spacing.
ProportionalHeight This sets the spacing proportional to the line (in percentage). For example, set to 200 for double spacing.
FixedHeight This sets the line height to a fixed line height (in pixels).
MinimumHeight This sets the minimum line height (in pixels).
LineDistanceHeight This adds the specified height between lines (in pixels).
See also
lineHeight(), lineHeightType(), setLineHeight()
Enumerator
SingleHeight
ProportionalHeight
FixedHeight
MinimumHeight
LineDistanceHeight
Definition at line 548 of file qtextformat.h.
{
         SingleHeight = 0,
         ProportionalHeight = 1,
         FixedHeight = 2,
         MinimumHeight = 3,
         LineDistanceHeight = 4
     };
Constructors and Destructors
QTextBlockFormat() [1/2]
QTextBlockFormat::QTextBlockFormat ()
Constructs a new QTextBlockFormat.
Definition at line 2199 of file qtextformat.cpp.
 : QTextFormat(BlockFormat) {}
QTextBlockFormat() [2/2]
QTextBlockFormat::QTextBlockFormat (const QTextFormat & other) explicit protected
Creates a new block format with the same attributes as the given text format.
Warning
This function is not part of the public interface.
Definition at line 2211 of file qtextformat.cpp.
  : QTextFormat(fmt)
 {
 }
Functions
alignment()
Qt::Alignment QTextBlockFormat::alignment () const inline
Returns the paragraph's alignment.
See also
setAlignment()
Definition at line 561 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes(), QAccessibleTextWidget::attributes(), QTextHtmlExporter::emitBlockAttributes(), QTextHtmlParserNode::initializeProperties(), QTextDocumentLayoutPrivate::layoutBlock(), QTextHtmlImporter::scanTable(), and QTextOdfWriter::writeBlockFormat().
     { int a = intProperty(BlockAlignment); if (a == 0) a = Qt::AlignLeft; return QFlag(a); }
bottomMargin()
qreal QTextBlockFormat::bottomMargin () const inline
Returns the paragraph's bottom margin.
See also
setBottomMargin() topMargin()
Definition at line 571 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlockAttributes(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), QTextHtmlImporter::processBlockNode(), and QTextOdfWriter::writeBlockFormat().
     { return doubleProperty(BlockBottomMargin); }
indent()
int QTextBlockFormat::indent () const inline
Returns the paragraph's indent.
See also
setIndent()
Definition at line 590 of file qtextformat.h.
Referenced by QTextDocumentLayoutPrivate::blockIndent(), QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), QTextHtmlExporter::emitBlockAttributes(), QTextControlPrivate::indent(), QTextControlPrivate::keyPressEvent(), QPlainTextEdit::keyReleaseEvent(), QTextEdit::keyReleaseEvent(), QTextControlPrivate::outdent(), QTextList::remove(), and QTextOdfWriter::writeBlockFormat().
     { return intProperty(BlockIndent); }
isValid()
QTextBlockFormat::isValid () const inline
Returns true if this block format is valid; otherwise returns false.
Definition at line 558 of file qtextformat.h.
Referenced by QTextDocumentPrivate::setBlockFormat().
 { return isBlockFormat(); }
leftMargin()
qreal QTextBlockFormat::leftMargin () const inline
Returns the paragraph's left margin.
See also
setLeftMargin() rightMargin() indent()
Definition at line 576 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlockAttributes(), QTextDocumentLayoutPrivate::layoutBlock(), QTextHtmlImporter::processBlockNode(), and QTextOdfWriter::writeBlockFormat().
     { return doubleProperty(BlockLeftMargin); }
lineHeight() [1/2]
qreal QTextBlockFormat::lineHeight (qreal scriptLineHeight, qreal scaling = 1.0) const inline
Returns the height of the lines in the paragraph based on the height of the script line given by scriptLineHeight and the specified scaling factor.
Since
4.8
The value that is returned is also dependent on the given LineHeightType of the paragraph as well as the LineHeight setting that has been set for the paragraph.
The scaling is needed for heights that include a fixed number of pixels, to scale them appropriately for printing.
See also
LineHeightTypes, setLineHeight(), lineHeightType()
Definition at line 625 of file qtextformat.h.
Referenced by getLineHeightParams().
 {
   switch(intProperty(LineHeightType)) {
     case SingleHeight:
       return(scriptLineHeight);
     case ProportionalHeight:
       return(scriptLineHeight * doubleProperty(LineHeight) / 100.0);
     case FixedHeight:
       return(doubleProperty(LineHeight) * scaling);
     case MinimumHeight:
       return(qMax(scriptLineHeight, doubleProperty(LineHeight) * scaling));
     case LineDistanceHeight:
       return(scriptLineHeight + doubleProperty(LineHeight) * scaling);
   }
   return(0);
 }
lineHeight() [2/2]
qreal QTextBlockFormat::lineHeight () const inline
This returns the LineHeight property for the paragraph.
Since
4.8
See also
LineHeightTypes, setLineHeight(), lineHeightType()
Definition at line 596 of file qtextformat.h.
     { return doubleProperty(LineHeight); }
lineHeightType()
qreal QTextBlockFormat::lineHeightType () const inline
This returns the LineHeightType property of the paragraph.
Since
4.8
See also
LineHeightTypes, setLineHeight(), lineHeight()
Definition at line 598 of file qtextformat.h.
Referenced by getLineHeightParams().
     { return intProperty(LineHeightType); }
nonBreakableLines()
bool QTextBlockFormat::nonBreakableLines () const inline
Returns true if the lines in the paragraph are non-breakable; otherwise returns false.
See also
setNonBreakableLines()
Definition at line 603 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlock(), QTextDocumentLayoutPrivate::layoutBlock(), and QTextOdfWriter::writeBlockFormat().
     { return boolProperty(BlockNonBreakableLines); }
pageBreakPolicy()
QTextFormat::PageBreakFlags QTextBlockFormat::pageBreakPolicy () const inline
Returns the currently set page break policy for the paragraph.
Since
4.2
The default is QTextFormat::PageBreak_Auto.
See also
setPageBreakPolicy()
Definition at line 608 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QTextHtmlExporter::emitBlockAttributes(), QTextHtmlImporter::import(), QTextDocumentLayoutPrivate::layoutFlow(), QTextHtmlImporter::scanTable(), and QTextOdfWriter::writeBlockFormat().
     { return PageBreakFlags(intProperty(PageBreakPolicy)); }
rightMargin()
qreal QTextBlockFormat::rightMargin () const inline
Returns the paragraph's right margin.
See also
setRightMargin() leftMargin()
Definition at line 581 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlockAttributes(), QTextDocumentLayoutPrivate::layoutBlock(), QTextHtmlImporter::processBlockNode(), and QTextOdfWriter::writeBlockFormat().
     { return doubleProperty(BlockRightMargin); }
setAlignment()
void QTextBlockFormat::setAlignment (Qt::Alignment alignment) inline
Sets the paragraph's alignment.
See also
alignment()
Definition at line 619 of file qtextformat.h.
Referenced by QTextHtmlParser::applyAttributes(), QSplashScreen::drawContents(), QTextHtmlParserNode::initializeProperties(), and QTextEdit::setAlignment().
 { setProperty(BlockAlignment, int(aalignment)); }
setBottomMargin()
void QTextBlockFormat::setBottomMargin (qreal margin) inline
Sets the paragraph's bottom margin.
See also
bottomMargin() setTopMargin() setLeftMargin() setRightMargin()
Definition at line 569 of file qtextformat.h.
Referenced by QTextHtmlImporter::processBlockNode(), and QTextHtmlImporter::processSpecialNodes().
     { setProperty(BlockBottomMargin, margin); }
setIndent()
void QTextBlockFormat::setIndent (int indentation) inline
Sets the paragraph's indentation.
Margins are set independently of indentation with setLeftMargin() and setTextIndent(). The indentation is an integer that is multiplied with the document-wide standard indent, resulting in the actual indent of the paragraph.
See also
indent() QTextDocument::indentWidth()
Definition at line 622 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), QTextControlPrivate::createAutoBulletList(), QTextEditPrivate::createAutoBulletList(), QTextHtmlImporter::import(), QTextControlPrivate::indent(), QTextControlPrivate::keyPressEvent(), QPlainTextEdit::keyReleaseEvent(), QTextEdit::keyReleaseEvent(), QTextControlPrivate::outdent(), QTextHtmlImporter::processBlockNode(), and QTextList::remove().
 { setProperty(BlockIndent, aindent); }
setLeftMargin()
void QTextBlockFormat::setLeftMargin (qreal margin) inline
Sets the paragraph's left margin.
Indentation can be applied separately with setIndent().
See also
leftMargin() setRightMargin() setTopMargin() setBottomMargin()
Definition at line 574 of file qtextformat.h.
Referenced by QTextHtmlImporter::processBlockNode().
     { setProperty(BlockLeftMargin, margin); }
setLineHeight()
void QTextBlockFormat::setLineHeight (qreal height, int heightType) inline
Sets the line height for the paragraph to the value given by height which is dependent on heightType in the way described by the LineHeightTypes enum.
Since
4.8
See also
LineHeightTypes, lineHeight(), lineHeightType()
Definition at line 593 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations().
     { setProperty(LineHeight, height); setProperty(LineHeightType, heightType); }
setNonBreakableLines()
void QTextBlockFormat::setNonBreakableLines (bool b) inline
If b is true, the lines in the paragraph are treated as non-breakable; otherwise they are breakable.
See also
nonBreakableLines()
Definition at line 601 of file qtextformat.h.
Referenced by QTextHtmlImporter::processBlockNode().
     { setProperty(BlockNonBreakableLines, b); }
setPageBreakPolicy()
void QTextBlockFormat::setPageBreakPolicy (PageBreakFlags policy) inline
Sets the page break policy for the paragraph to policy.
Since
4.2
See also
pageBreakPolicy()
Definition at line 606 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations(), and QTextHtmlImporter::import().
     { setProperty(PageBreakPolicy, int(flags)); }
setRightMargin()
void QTextBlockFormat::setRightMargin (qreal margin) inline
Sets the paragraph's right margin.
See also
rightMargin() setLeftMargin() setTopMargin() setBottomMargin()
Definition at line 579 of file qtextformat.h.
Referenced by QTextHtmlImporter::processBlockNode().
     { setProperty(BlockRightMargin, margin); }
setTabPositions()
void QTextBlockFormat::setTabPositions (const QList< QTextOption::Tab > & tabs)
Sets the tab positions for the text block to those specified by tabs.
Since
4.4
See also
tabPositions()
Definition at line 2226 of file qtextformat.cpp.
 {
     QList<QVariant> list;
     QList<QTextOption::Tab>::ConstIterator iter = tabs.constBegin();
     while (iter != tabs.constEnd()) {
         QVariant v;
         v.setValue<QTextOption::Tab>(*iter);
         list.append(v);
         ++iter;
     }
     setProperty(TabPositions, list);
 }
setTextIndent()
void QTextBlockFormat::setTextIndent (qreal indent) inline
Sets the indent for the first line in the block.
This allows the first line of a paragraph to be indented differently to the other lines, enhancing the readability of the text.
See also
textIndent() setLeftMargin() setRightMargin() setTopMargin() setBottomMargin()
Definition at line 584 of file qtextformat.h.
Referenced by QTextHtmlParserNode::applyCssDeclarations().
     { setProperty(TextIndent, aindent); }
setTopMargin()
void QTextBlockFormat::setTopMargin (qreal margin) inline
Sets the paragraph's top margin.
See also
topMargin() setBottomMargin() setLeftMargin() setRightMargin()
Definition at line 564 of file qtextformat.h.
Referenced by QTextHtmlImporter::processBlockNode(), and QTextHtmlImporter::processSpecialNodes().
     { setProperty(BlockTopMargin, margin); }
tabPositions()
QList< QTextOption::Tab > QTextBlockFormat::tabPositions () const
Returns a list of tab positions defined for the text block.
Since
4.4
See also
setTabPositions()
Definition at line 2248 of file qtextformat.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutBlock(), and QTextOdfWriter::writeBlockFormat().
 {
     QVariant variant = property(TabPositions);
     if(variant.isNull())
         return QList<QTextOption::Tab>();
     QList<QTextOption::Tab> answer;
     QList<QVariant> variantsList = qvariant_cast<QList<QVariant> >(variant);
     QList<QVariant>::Iterator iter = variantsList.begin();
     while(iter != variantsList.end()) {
         answer.append( qvariant_cast<QTextOption::Tab>(*iter));
         ++iter;
     }
     return answer;
 }
textIndent()
qreal QTextBlockFormat::textIndent () const inline
Returns the paragraph's text indent.
See also
setTextIndent()
Definition at line 586 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlockAttributes(), QTextDocumentLayoutPrivate::layoutBlock(), and QTextOdfWriter::writeBlockFormat().
     { return doubleProperty(TextIndent); }
topMargin()
qreal QTextBlockFormat::topMargin () const inline
Returns the paragraph's top margin.
See also
setTopMargin() bottomMargin()
Definition at line 566 of file qtextformat.h.
Referenced by QTextHtmlExporter::emitBlockAttributes(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutFlow(), QTextHtmlImporter::processBlockNode(), and QTextOdfWriter::writeBlockFormat().
     { return doubleProperty(BlockTopMargin); }
Friends and Related Functions
QTextFormat
friend class QTextFormat friend
Definition at line 616 of file qtextformat.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtextformat.h
/src/gui/text/qtextformat.cpp