Qt 4.8: QDeclarativeMouseArea Class Reference
QDeclarativeMouseArea Class Reference
#include <qdeclarativemousearea_p.h>
Signals
void acceptedButtonsChanged ()
void canceled ()
void clicked (QDeclarativeMouseEvent *mouse)
void doubleClicked (QDeclarativeMouseEvent *mouse)
void enabledChanged ()
void entered ()
void exited ()
void hoveredChanged ()
void hoverEnabledChanged ()
void mousePositionChanged (QDeclarativeMouseEvent *mouse)
void positionChanged (QDeclarativeMouseEvent *mouse)
void pressAndHold (QDeclarativeMouseEvent *mouse)
void pressed (QDeclarativeMouseEvent *mouse)
void pressedChanged ()
void preventStealingChanged ()
void released (QDeclarativeMouseEvent *mouse)
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
Qt::MouseButtons acceptedButtons () const
QDeclarativeDrag * drag ()
bool hovered () const
bool hoverEnabled () const
bool isEnabled () const
qreal mouseX () const
qreal mouseY () const
bool pressed () const
Qt::MouseButtons pressedButtons () const
bool preventStealing () const
QDeclarativeMouseArea (QDeclarativeItem *parent=0)
This handler is called when the mouse enters the mouse area.
void setAcceptedButtons (Qt::MouseButtons buttons)
void setEnabled (bool)
void setHoverEnabled (bool h)
void setPreventStealing (bool prevent)
~QDeclarativeMouseArea ()
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
virtual void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
bool sceneEvent (QEvent *)
bool sceneEventFilter (QGraphicsItem *i, QEvent *e)
Filters events for the item watched.
bool sendMouseEvent (QGraphicsSceneMouseEvent *event)
void setHovered (bool)
bool setPressed (bool)
void timerEvent (QTimerEvent *event)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
virtual void componentComplete ()
virtual bool event (QEvent *)
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual void keyPressEvent (QKeyEvent *event)
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Private Functions
void handlePress ()
void handleRelease ()
Properties
Qt::MouseButtons acceptedButtons
bool containsMouse
QDeclarativeDrag * drag
bool enabled
bool hoverEnabled
qreal mouseX
qreal mouseY
bool pressed
Qt::MouseButtons pressedButtons
bool preventStealing
Additional Inherited Members
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 119 of file qdeclarativemousearea_p.h.
Constructors and Destructors
QDeclarativeMouseArea()
QDeclarativeMouseArea::QDeclarativeMouseArea (QDeclarativeItem * parent = 0)
This handler is called when the mouse enters the mouse area.
MouseArea::onEntered()
By default the onEntered handler is only called while a button is pressed. Setting hoverEnabled to true enables handling of onEntered when no mouse button is pressed.
See also
hoverEnabled
This handler is called when the mouse exists the mouse area.
MouseArea::onExited()
By default the onExited handler is only called while a button is pressed. Setting hoverEnabled to true enables handling of onExited when no mouse button is pressed.
See also
hoverEnabled
This handler is called when the mouse position changes.
MouseArea::onPositionChanged(MouseEvent mouse)
The MouseEvent{mouse} parameter provides information about the mouse, including the x and y position, and any buttons currently pressed.
The accepted property of the MouseEvent parameter is ignored in this handler.
By default the onPositionChanged handler is only called while a button is pressed. Setting hoverEnabled to true enables handling of onPositionChanged when no mouse button is pressed.
This handler is called when there is a click.
MouseArea::onClicked(MouseEvent mouse)
A click is defined as a press followed by a release, both inside the MouseArea (pressing, moving outside the MouseArea, and then moving back inside and releasing is also considered a click).
The MouseEvent{mouse} parameter provides information about the click, including the x and y position of the release of the click, and whether the click was held.
The accepted property of the MouseEvent parameter is ignored in this handler.
This handler is called when there is a press.
MouseArea::onPressed(MouseEvent mouse)
The MouseEvent{mouse} parameter provides information about the press, including the x and y position and which button was pressed.
The accepted property of the MouseEvent parameter determines whether this MouseArea will handle the press and all future mouse events until release. The default is to accept the event and not allow other MouseArea beneath this one to handle the event. If accepted is set to false, no further events will be sent to this MouseArea until the button is next pressed.
This handler is called when there is a release.
MouseArea::onReleased(MouseEvent mouse)
The MouseEvent{mouse} parameter provides information about the click, including the x and y position of the release of the click, and whether the click was held.
The accepted property of the MouseEvent parameter is ignored in this handler.
See also
onCanceled
This handler is called when there is a long press (currently 800ms).
MouseArea::onPressAndHold(MouseEvent mouse)
The MouseEvent{mouse} parameter provides information about the press, including the x and y position of the press, and which button is pressed.
The accepted property of the MouseEvent parameter is ignored in this handler.
This handler is called when there is a double-click (a press followed by a release followed by a press).
MouseArea::onDoubleClicked(MouseEvent mouse)
The MouseEvent{mouse} parameter provides information about the click, including the x and y position of the release of the click, and whether the click was held.
If the accepted property of the MouseEvent{mouse} parameter is set to false in the handler, the onPressed/onReleased/onClicked handlers will be called for the second click; otherwise they are suppressed. The accepted property defaults to true.
This handler is called when mouse events have been canceled, either because an event was not accepted, or because another element stole the mouse event handling.
MouseArea::onCanceled()
This signal is for advanced use: it is useful when there is more than one MouseArea that is handling input, or when there is a MouseArea inside a Flickable . In the latter case, if you execute some logic on the pressed signal and then start dragging, the Flickable will steal the mouse handling from the MouseArea. In these cases, to reset the logic when the MouseArea has lost the mouse handling to the Flickable , onCanceled should be used in addition to onReleased.
Definition at line 387 of file qdeclarativemousearea.cpp.
   : QDeclarativeItem(*(new QDeclarativeMouseAreaPrivate), parent)
 {
     Q_D(QDeclarativeMouseArea);
     d->init();
 }
~QDeclarativeMouseArea()
QDeclarativeMouseArea::~QDeclarativeMouseArea ()
Definition at line 394 of file qdeclarativemousearea.cpp.
 {
 }
Functions
acceptedButtons()
Qt::MouseButtons QDeclarativeMouseArea::acceptedButtons () const
Referenced by contextMenuEvent(), and setHovered().
acceptedButtonsChanged
void QDeclarativeMouseArea::acceptedButtonsChanged () signal
Referenced by setAcceptedButtons().
canceled
void QDeclarativeMouseArea::canceled () signal
Referenced by sceneEvent(), and sendMouseEvent().
clicked
void QDeclarativeMouseArea::clicked (QDeclarativeMouseEvent * mouse) signal
Referenced by setPressed().
contextMenuEvent()
void QDeclarativeMouseArea::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected virtual
This event handler can be reimplemented in a subclass to process context menu events.
The event parameter contains details about the event to be handled.
If you ignore the event, (i.e., by calling QEvent::ignore(),) event will propagate to any item beneath this item. If no items accept the event, it will be ignored by the scene, and propagate to the view.
It's common to open a QMenu in response to receiving a context menu event. Example:
void CustomItem::contextMenuEvent(QGraphicsSceneContextMenuEvent *event)
{
    QMenu menu;
    QAction *removeAction = menu.addAction("Remove");
    QAction *markAction = menu.addAction("Mark");
    QAction *selectedAction = menu.exec(event->screenPos());
    // ...
}
The default implementation ignores the event.
See also
sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 691 of file qdeclarativemousearea.cpp.
 {
     bool acceptsContextMenuButton;
 #if defined(Q_OS_SYMBIAN)
     // In Symbian a Long Tap on the screen will trigger. See QSymbianControl::HandleLongTapEventL().
     acceptsContextMenuButton = acceptedButtons() & Qt::LeftButton;
 #elif defined(Q_WS_WINCE)
     // ### WinCE can trigger context menu event with a gesture in the left button or a
     // click with the right button. Since we have no way here to differentiate them when
     // event happens, accepting either of the them will block the event.
     acceptsContextMenuButton = acceptedButtons() & (Qt::LeftButton | Qt::RightButton);
 #else
     acceptsContextMenuButton = acceptedButtons() & Qt::RightButton;
 #endif
     if (isEnabled() && event->reason() == QGraphicsSceneContextMenuEvent::Mouse
         && acceptsContextMenuButton) {
         // Do not let the context menu event propagate to items behind.
         return;
     }
     QDeclarativeItem::contextMenuEvent(event);
 }
doubleClicked
void QDeclarativeMouseArea::doubleClicked (QDeclarativeMouseEvent * mouse) signal
Referenced by mouseDoubleClickEvent().
drag()
QDeclarativeDrag* QDeclarativeMouseArea::drag ()
Referenced by mouseMoveEvent(), and setPressed().
enabledChanged
void QDeclarativeMouseArea::enabledChanged () signal
Referenced by setEnabled().
entered
void QDeclarativeMouseArea::entered () signal
Referenced by setHovered().
exited
void QDeclarativeMouseArea::exited () signal
Referenced by setHovered().
geometryChanged()
void QDeclarativeMouseArea::geometryChanged (const QRectF & newGeometry, const QRectF & oldGeometry) protected virtual
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
If the two geometries are the same, it doesn't do anything.
Reimplemented from QDeclarativeItem.
Definition at line 827 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     QDeclarativeItem::geometryChanged(newGeometry, oldGeometry);
     if (d->lastScenePos.isNull)
         d->lastScenePos = mapToScene(d->lastPos);
     else if (newGeometry.x() != oldGeometry.x() || newGeometry.y() != oldGeometry.y())
         d->lastPos = mapFromScene(d->lastScenePos);
 }
handlePress()
void QDeclarativeMouseArea::handlePress () private
handleRelease()
void QDeclarativeMouseArea::handleRelease () private
hovered()
bool QDeclarativeMouseArea::hovered () const
Definition at line 896 of file qdeclarativemousearea.cpp.
 {
     Q_D(const QDeclarativeMouseArea);
     return d->hovered;
 }
hoveredChanged
void QDeclarativeMouseArea::hoveredChanged () signal
Referenced by sceneEvent(), sendMouseEvent(), and setHovered().
hoverEnabled()
bool QDeclarativeMouseArea::hoverEnabled () const
Referenced by itemChange().
hoverEnabledChanged
void QDeclarativeMouseArea::hoverEnabledChanged () signal
Referenced by setHoverEnabled().
hoverEnterEvent()
void QDeclarativeMouseArea::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
The default implementation calls update(); otherwise it does nothing.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
See also
hoverMoveEvent(), hoverLeaveEvent(), sceneEvent(), setAcceptHoverEvents()
Reimplemented from QGraphicsItem.
Definition at line 653 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (!d->absorb)
         QDeclarativeItem::hoverEnterEvent(event);
     else {
         d->lastPos = event->pos();
         setHovered(true);
         QDeclarativeMouseEvent me(d->lastPos.x(), d->lastPos.y(), Qt::NoButton, Qt::NoButton, event->modifiers(), false, false);
         emit mousePositionChanged(&me);
     }
 }
hoverLeaveEvent()
void QDeclarativeMouseArea::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
The default implementation calls update(); otherwise it does nothing.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
See also
hoverEnterEvent(), hoverMoveEvent(), sceneEvent(), setAcceptHoverEvents()
Reimplemented from QGraphicsItem.
Definition at line 681 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (!d->absorb)
         QDeclarativeItem::hoverLeaveEvent(event);
     else
         setHovered(false);
 }
hoverMoveEvent()
void QDeclarativeMouseArea::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive hover move events for this item.
The default implementation does nothing.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
See also
hoverEnterEvent(), hoverLeaveEvent(), sceneEvent(), setAcceptHoverEvents()
Reimplemented from QGraphicsItem.
Definition at line 666 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (!d->absorb) {
         QDeclarativeItem::hoverMoveEvent(event);
     } else {
         d->lastPos = event->pos();
         QDeclarativeMouseEvent me(d->lastPos.x(), d->lastPos.y(), Qt::NoButton, Qt::NoButton, event->modifiers(), false, false);
         emit mousePositionChanged(&me);
         me.setX(d->lastPos.x());
         me.setY(d->lastPos.y());
         emit positionChanged(&me);
     }
 }
isEnabled()
bool QDeclarativeMouseArea::isEnabled () const
Definition at line 441 of file qdeclarativemousearea.cpp.
Referenced by contextMenuEvent().
 {
     Q_D(const QDeclarativeMouseArea);
     return d->absorb;
 }
itemChange()
QVariant QDeclarativeMouseArea::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
Warning
This function is not part of the public interface.
Items wishing to optimize start-up construction should instead consider using componentComplete().
Reimplemented from QDeclarativeItem.
Definition at line 839 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     switch (change) {
     case ItemVisibleHasChanged:
         if (acceptHoverEvents() && d->hovered != (isVisible() && isUnderMouse()))
             setHovered(!d->hovered);
         break;
     default:
         break;
     }
     return QDeclarativeItem::itemChange(change, value);
 }
mouseDoubleClickEvent()
void QDeclarativeMouseArea::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
When doubleclicking an item, the item will first receive a mouse press event, followed by a release event (i.e., a click), then a doubleclick event, and finally a release event.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation calls mousePressEvent(). If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseDoubleClickEvent() in your reimplementation.
Note that an item will not receive double click events if it is neither QGraphicsItem::ItemIsSelectable{selectable} nor movable (single mouse clicks are ignored in this case, and that stops the generation of double clicks).
See also
mousePressEvent(), mouseMoveEvent(), mouseReleaseEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 637 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (!d->absorb) {
         QDeclarativeItem::mouseDoubleClickEvent(event);
     } else {
         if (d->isDoubleClickConnected())
             d->doubleClick = true;
         d->saveEvent(event);
         QDeclarativeMouseEvent me(d->lastPos.x(), d->lastPos.y(), d->lastButton, d->lastButtons, d->lastModifiers, true, false);
         me.setAccepted(d->isDoubleClickConnected());
         emit this->doubleClicked(&me);
         QDeclarativeItem::mouseDoubleClickEvent(event);
     }
 }
mouseMoveEvent()
void QDeclarativeMouseArea::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
If you do receive this event, you can be certain that this item also received a mouse press event, and that this item is the current mouse grabber.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseMoveEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 540 of file qdeclarativemousearea.cpp.
Referenced by sendMouseEvent().
 {
     Q_D(QDeclarativeMouseArea);
     if (!d->absorb) {
         QDeclarativeItem::mouseMoveEvent(event);
         return;
     }
     d->saveEvent(event);
     // ### we should skip this if these signals aren't used
     // ### can GV handle this for us?
     bool contains = boundingRect().contains(d->lastPos);
     if (d->hovered && !contains)
         setHovered(false);
     else if (!d->hovered && contains)
         setHovered(true);
     if (d->drag && d->drag->target()) {
         if (!d->moved) {
             d->startX = drag()->target()->x();
             d->startY = drag()->target()->y();
         }
         QPointF startLocalPos;
         QPointF curLocalPos;
         if (drag()->target()->parentItem()) {
             startLocalPos = drag()->target()->parentItem()->mapFromScene(d->startScene);
             curLocalPos = drag()->target()->parentItem()->mapFromScene(event->scenePos());
         } else {
             startLocalPos = d->startScene;
             curLocalPos = event->scenePos();
         }
         if (keepMouseGrab() && d->stealMouse)
             d->drag->setActive(true);
         bool dragX = drag()->axis() & QDeclarativeDrag::XAxis;
         bool dragY = drag()->axis() & QDeclarativeDrag::YAxis;
         const qreal x = dragX
                 ? qBound(d->drag->xmin(), d->startX + curLocalPos.x() - startLocalPos.x(), d->drag->xmax())
                 : d->startX;
         const qreal y = dragY
                 ? qBound(d->drag->ymin(), d->startY + curLocalPos.y() - startLocalPos.y(), d->drag->ymax())
                 : d->startY;
         if (d->drag->active()) {
             if (dragX && dragY)
                 d->drag->target()->setPos(x, y);
             else if (dragX)
                 d->drag->target()->setX(x);
             else if (dragY)
                 d->drag->target()->setY(y);
         }
         if (!keepMouseGrab()) {
             const int dragThreshold = QApplication::startDragDistance();
             if (qAbs(x - d->startX) > dragThreshold || qAbs(y - d->startY) > dragThreshold) {
                 setKeepMouseGrab(true);
                 d->stealMouse = true;
             }
         }
         d->moved = true;
     }
     QDeclarativeMouseEvent me(d->lastPos.x(), d->lastPos.y(), d->lastButton, d->lastButtons, d->lastModifiers, false, d->longPress);
     emit mousePositionChanged(&me);
     me.setX(d->lastPos.x());
     me.setY(d->lastPos.y());
     emit positionChanged(&me);
 }
mousePositionChanged
void QDeclarativeMouseArea::mousePositionChanged (QDeclarativeMouseEvent * mouse) signal
Referenced by hoverEnterEvent(), hoverMoveEvent(), mouseMoveEvent(), and setPressed().
mousePressEvent()
void QDeclarativeMouseArea::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
Mouse press events are only delivered to items that accept the mouse button that is pressed. By default, an item accepts all mouse buttons, but you can change this by calling setAcceptedMouseButtons().
The mouse press event decides which item should become the mouse grabber (see QGraphicsScene::mouseGrabberItem()). If you do not reimplement this function, the press event will propagate to any topmost item beneath this item, and no other mouse events will be delivered to this item.
If you do reimplement this function, event will by default be accepted (see QEvent::accept()), and this item is then the mouse grabber. This allows the item to receive future move, release and doubleclick events. If you call QEvent::ignore() on event, this item will lose the mouse grab, and event will propagate to any topmost item beneath. No further mouse events will be delivered to this item unless a new mouse press event is received.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mousePressEvent() in your reimplementation.
The event is for items that are neither QGraphicsItem::ItemIsMovable "movable" nor QGraphicsItem::ItemIsSelectable "selectable". mouseMoveEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 518 of file qdeclarativemousearea.cpp.
Referenced by sendMouseEvent().
 {
     Q_D(QDeclarativeMouseArea);
     d->moved = false;
     d->stealMouse = d->preventStealing;
     if (!d->absorb)
         QDeclarativeItem::mousePressEvent(event);
     else {
         d->longPress = false;
         d->saveEvent(event);
         if (d->drag)
             d->drag->setActive(false);
         setHovered(true);
         d->startScene = event->scenePos();
         // we should only start timer if pressAndHold is connected to.
         if (d->isPressAndHoldConnected())
             d->pressAndHoldTimer.start(PressAndHoldDelay, this);
         setKeepMouseGrab(d->stealMouse);
         event->setAccepted(setPressed(true));
     }
 }
mouseReleaseEvent()
void QDeclarativeMouseArea::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseReleaseEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseMoveEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 615 of file qdeclarativemousearea.cpp.
Referenced by sendMouseEvent().
 {
     Q_D(QDeclarativeMouseArea);
     d->stealMouse = false;
     if (!d->absorb) {
         QDeclarativeItem::mouseReleaseEvent(event);
     } else {
         d->saveEvent(event);
         setPressed(false);
         if (d->drag)
             d->drag->setActive(false);
         // If we don't accept hover, we need to reset containsMouse.
         if (!acceptHoverEvents())
             setHovered(false);
         QGraphicsScene *s = scene();
         if (s && s->mouseGrabberItem() == this)
             ungrabMouse();
         setKeepMouseGrab(false);
     }
     d->doubleClick = false;
 }
mouseX()
qreal QDeclarativeMouseArea::mouseX () const
Referenced by ~QDeclarativeMouseArea().
mouseY()
qreal QDeclarativeMouseArea::mouseY () const
Referenced by ~QDeclarativeMouseArea().
positionChanged
void QDeclarativeMouseArea::positionChanged (QDeclarativeMouseEvent * mouse) signal
Referenced by hoverMoveEvent(), and mouseMoveEvent().
pressAndHold
void QDeclarativeMouseArea::pressAndHold (QDeclarativeMouseEvent * mouse) signal
Referenced by timerEvent().
pressed() [1/2]
bool QDeclarativeMouseArea::pressed () const
Referenced by hovered(), and setPressed().
pressed [2/2]
void QDeclarativeMouseArea::pressed (QDeclarativeMouseEvent * mouse) signal
pressedButtons()
Qt::MouseButtons QDeclarativeMouseArea::pressedButtons () const
Referenced by setPreventStealing().
pressedChanged
void QDeclarativeMouseArea::pressedChanged () signal
Referenced by sceneEvent(), sendMouseEvent(), and setPressed().
preventStealing()
bool QDeclarativeMouseArea::preventStealing () const
Referenced by setEnabled().
preventStealingChanged
void QDeclarativeMouseArea::preventStealingChanged () signal
Referenced by setPreventStealing().
released
void QDeclarativeMouseArea::released (QDeclarativeMouseEvent * mouse) signal
Referenced by setPressed().
sceneEvent()
bool QDeclarativeMouseArea::sceneEvent (QEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 716 of file qdeclarativemousearea.cpp.
 {
     bool rv = QDeclarativeItem::sceneEvent(event);
     if (event->type() == QEvent::UngrabMouse) {
         Q_D(QDeclarativeMouseArea);
         if (d->pressed) {
             // if our mouse grab has been removed (probably by Flickable), fix our
             // state
             d->pressed = false;
             d->stealMouse = false;
             setKeepMouseGrab(false);
             emit canceled();
             emit pressedChanged();
             if (d->hovered) {
                 d->hovered = false;
                 emit hoveredChanged();
             }
         }
     }
     return rv;
 }
sceneEventFilter()
bool QDeclarativeMouseArea::sceneEventFilter (QGraphicsItem * watched, QEvent * event) protected virtual
Filters events for the item watched.
event is the filtered event.
Reimplementing this function in a subclass makes it possible for the item to be used as an event filter for other items, intercepting all the events send to those items before they are able to respond.
Reimplementations must return true to prevent further processing of a given event, ensuring that it will not be delivered to the watched item, or return false to indicate that the event should be propagated further by the event system.
See also
installSceneEventFilter()
Reimplemented from QGraphicsItem.
Definition at line 796 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (!d->absorb || !isVisible() || !d->drag || !d->drag->filterChildren())
         return QDeclarativeItem::sceneEventFilter(i, e);
     switch (e->type()) {
     case QEvent::GraphicsSceneMousePress:
     case QEvent::GraphicsSceneMouseMove:
     case QEvent::GraphicsSceneMouseRelease:
         return sendMouseEvent(static_cast<QGraphicsSceneMouseEvent *>(e));
     default:
         break;
     }
     return QDeclarativeItem::sceneEventFilter(i, e);
 }
sendMouseEvent()
bool QDeclarativeMouseArea::sendMouseEvent (QGraphicsSceneMouseEvent * event) protected
Definition at line 738 of file qdeclarativemousearea.cpp.
Referenced by sceneEventFilter().
 {
     Q_D(QDeclarativeMouseArea);
     QGraphicsSceneMouseEvent mouseEvent(event->type());
     QRectF myRect = mapToScene(QRectF(0, 0, width(), height())).boundingRect();
     QGraphicsScene *s = scene();
     QDeclarativeItem *grabber = s ? qobject_cast<QDeclarativeItem*>(s->mouseGrabberItem()) : 0;
     bool stealThisEvent = d->stealMouse;
     if ((stealThisEvent || myRect.contains(event->scenePos().toPoint())) && (!grabber || !grabber->keepMouseGrab())) {
         mouseEvent.setAccepted(false);
         for (int i = 0x1; i <= 0x10; i <<= 1) {
             if (event->buttons() & i) {
                 Qt::MouseButton button = Qt::MouseButton(i);
                 mouseEvent.setButtonDownPos(button, mapFromScene(event->buttonDownPos(button)));
             }
         }
         mouseEvent.setScenePos(event->scenePos());
         mouseEvent.setLastScenePos(event->lastScenePos());
         mouseEvent.setPos(mapFromScene(event->scenePos()));
         mouseEvent.setLastPos(mapFromScene(event->lastScenePos()));
         switch(mouseEvent.type()) {
         case QEvent::GraphicsSceneMouseMove:
             mouseMoveEvent(&mouseEvent);
             break;
         case QEvent::GraphicsSceneMousePress:
             mousePressEvent(&mouseEvent);
             break;
         case QEvent::GraphicsSceneMouseRelease:
             mouseReleaseEvent(&mouseEvent);
             break;
         default:
             break;
         }
         grabber = qobject_cast<QDeclarativeItem*>(s->mouseGrabberItem());
         if (grabber && stealThisEvent && !grabber->keepMouseGrab() && grabber != this)
             grabMouse();
         return stealThisEvent;
     }
     if (mouseEvent.type() == QEvent::GraphicsSceneMouseRelease) {
         if (d->pressed) {
             d->pressed = false;
             d->stealMouse = false;
             if (s && s->mouseGrabberItem() == this)
                 ungrabMouse();
             emit canceled();
             emit pressedChanged();
             if (d->hovered) {
                 d->hovered = false;
                 emit hoveredChanged();
             }
         }
     }
     return false;
 }
setAcceptedButtons()
void QDeclarativeMouseArea::setAcceptedButtons (Qt::MouseButtons buttons)
Definition at line 955 of file qdeclarativemousearea.cpp.
 {
     if (buttons != acceptedMouseButtons()) {
         setAcceptedMouseButtons(buttons);
         emit acceptedButtonsChanged();
     }
 }
setEnabled()
void QDeclarativeMouseArea::setEnabled (bool a)
Definition at line 447 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (a != d->absorb) {
         d->absorb = a;
         emit enabledChanged();
     }
 }
setHovered()
void QDeclarativeMouseArea::setHovered (bool h) protected
Definition at line 915 of file qdeclarativemousearea.cpp.
Referenced by hoverEnterEvent(), hoverLeaveEvent(), itemChange(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and setHoverEnabled().
 {
     Q_D(QDeclarativeMouseArea);
     if (d->hovered != h) {
         d->hovered = h;
         emit hoveredChanged();
         d->hovered ? emit entered() : emit exited();
     }
 }
setHoverEnabled()
void QDeclarativeMouseArea::setHoverEnabled (bool h)
Definition at line 874 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (h == acceptHoverEvents())
         return;
     setAcceptHoverEvents(h);
     emit hoverEnabledChanged();
     if (d->hovered != isUnderMouse())
         setHovered(!d->hovered);
 }
setPressed()
bool QDeclarativeMouseArea::setPressed (bool p) protected
Definition at line 963 of file qdeclarativemousearea.cpp.
Referenced by mousePressEvent(), and mouseReleaseEvent().
 {
     Q_D(QDeclarativeMouseArea);
     bool dragged = d->drag && d->drag->active();
     bool isclick = d->pressed == true && p == false && dragged == false && d->hovered == true;
     if (d->pressed != p) {
         d->pressed = p;
         QDeclarativeMouseEvent me(d->lastPos.x(), d->lastPos.y(), d->lastButton, d->lastButtons, d->lastModifiers, isclick, d->longPress);
         if (d->pressed) {
             if (!d->doubleClick)
                 emit pressed(&me);
             me.setX(d->lastPos.x());
             me.setY(d->lastPos.y());
             emit mousePositionChanged(&me);
             emit pressedChanged();
         } else {
             emit released(&me);
             me.setX(d->lastPos.x());
             me.setY(d->lastPos.y());
             emit pressedChanged();
             if (isclick && !d->longPress && !d->doubleClick)
                 emit clicked(&me);
         }
         return me.isAccepted();
     }
     return false;
 }
setPreventStealing()
void QDeclarativeMouseArea::setPreventStealing (bool prevent)
Definition at line 482 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (prevent != d->preventStealing) {
         d->preventStealing = prevent;
         setKeepMouseGrab(d->preventStealing && d->absorb);
         emit preventStealingChanged();
     }
 }
timerEvent()
void QDeclarativeMouseArea::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 813 of file qdeclarativemousearea.cpp.
 {
     Q_D(QDeclarativeMouseArea);
     if (event->timerId() == d->pressAndHoldTimer.timerId()) {
         d->pressAndHoldTimer.stop();
         bool dragged = d->drag && d->drag->active();
         if (d->pressed && dragged == false && d->hovered == true) {
             d->longPress = true;
             QDeclarativeMouseEvent me(d->lastPos.x(), d->lastPos.y(), d->lastButton, d->lastButtons, d->lastModifiers, false, d->longPress);
             emit pressAndHold(&me);
         }
     }
 }
Properties
acceptedButtons
Qt::MouseButtons QDeclarativeMouseArea::acceptedButtons private
Definition at line 129 of file qdeclarativemousearea_p.h.
containsMouse
bool QDeclarativeMouseArea::containsMouse private
Definition at line 125 of file qdeclarativemousearea_p.h.
drag
QDeclarativeDrag * QDeclarativeMouseArea::drag private
Definition at line 131 of file qdeclarativemousearea_p.h.
enabled
bool QDeclarativeMouseArea::enabled private
Definition at line 127 of file qdeclarativemousearea_p.h.
hoverEnabled
bool QDeclarativeMouseArea::hoverEnabled private
Definition at line 130 of file qdeclarativemousearea_p.h.
mouseX
qreal QDeclarativeMouseArea::mouseX private
Definition at line 123 of file qdeclarativemousearea_p.h.
mouseY
qreal QDeclarativeMouseArea::mouseY private
Definition at line 124 of file qdeclarativemousearea_p.h.
pressed
bool QDeclarativeMouseArea::pressed private
Definition at line 126 of file qdeclarativemousearea_p.h.
pressedButtons
Qt::MouseButtons QDeclarativeMouseArea::pressedButtons private
Definition at line 128 of file qdeclarativemousearea_p.h.
preventStealing
bool QDeclarativeMouseArea::preventStealing private
Definition at line 132 of file qdeclarativemousearea_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativemousearea_p.h
/src/declarative/graphicsitems/qdeclarativemousearea.cpp