Qt 4.8: QRawFontPrivate Class Reference
QRawFontPrivate Class Reference
#include <qrawfont_p.h>
Public Functions
void cleanUp ()
bool isValid () const
void platformCleanUp ()
void platformLoadFromData (const QByteArray &fontData, qreal pixelSize, QFont::HintingPreference hintingPreference)
QRawFontPrivate ()
QRawFontPrivate (const QRawFontPrivate &other)
~QRawFontPrivate ()
Static Public Functions
static QRawFontPrivate * get (const QRawFont &font)
Public Variables
QFontEngine * fontEngine
HANDLE fontHandle
QFont::HintingPreference hintingPreference
QAtomicInt ref
QThread * thread
Detailed Description
Definition at line 67 of file qrawfont_p.h.
Constructors and Destructors
QRawFontPrivate() [1/2]
QRawFontPrivate::QRawFontPrivate () inline
Definition at line 70 of file qrawfont_p.h.
         : fontEngine(0)
         , hintingPreference(QFont::PreferDefaultHinting)
         , thread(0)
 #if defined(Q_WS_WIN)
         , fontHandle(NULL)
 #endif
     {}
QRawFontPrivate() [2/2]
QRawFontPrivate::QRawFontPrivate (const QRawFontPrivate & other) inline
Definition at line 79 of file qrawfont_p.h.
         : fontEngine(other.fontEngine)
         , hintingPreference(other.hintingPreference)
         , thread(other.thread)
 #if defined(Q_WS_WIN)
         , fontHandle(NULL)
 #endif
     {
         if (fontEngine != 0)
             fontEngine->ref.ref();
     }
~QRawFontPrivate()
QRawFontPrivate::~QRawFontPrivate () inline
Definition at line 91 of file qrawfont_p.h.
     {
         Q_ASSERT(ref == 0);
         cleanUp();
     }
Functions
cleanUp()
void QRawFontPrivate::cleanUp ()
Warning
This function is not part of the public interface.
Definition at line 705 of file qrawfont.cpp.
Referenced by QRawFont::loadFromData().
 {
     platformCleanUp();
     if (fontEngine != 0) {
         fontEngine->ref.deref();
         if (fontEngine->cache_count == 0 && fontEngine->ref == 0)
             delete fontEngine;
         fontEngine = 0;
     }
     hintingPreference = QFont::PreferDefaultHinting;
 }
get()
static QRawFontPrivate* QRawFontPrivate::get (const QRawFont & font) inline static
Definition at line 109 of file qrawfont_p.h.
Referenced by QPainter::drawGlyphRun(), QPainterPrivate::drawGlyphs(), QTextLine::glyphs(), and QPainterReplayer::process().
 { return font.d.data(); }
isValid()
bool QRawFontPrivate::isValid () const inline
Definition at line 97 of file qrawfont_p.h.
Referenced by QRawFont::advancesForGlyphIndexes(), QRawFont::alphaMapForGlyph(), QRawFont::ascent(), QRawFont::averageCharWidth(), QRawFont::descent(), QRawFont::familyName(), QRawFont::fontTable(), QRawFont::glyphIndexesForChars(), QRawFont::glyphIndexesForString(), QRawFont::hintingPreference(), QRawFont::isValid(), QRawFont::leading(), QRawFont::maxCharWidth(), QRawFont::pathForGlyph(), QRawFont::pixelSize(), QRawFont::style(), QRawFont::styleName(), QRawFont::supportedWritingSystems(), QRawFont::supportsCharacter(), QRawFont::unitsPerEm(), QRawFont::weight(), and QRawFont::xHeight().
     {
         Q_ASSERT(thread == 0 || thread == QThread::currentThread());
         return fontEngine != 0;
     }
platformCleanUp()
void QRawFontPrivate::platformCleanUp ()
Definition at line 98 of file qrawfont_ft.cpp.
Referenced by resolveGdi32().
 {
     // Font engine handles all resources
 }
platformLoadFromData()
void QRawFontPrivate::platformLoadFromData (const QByteArray & fontData, qreal pixelSize, QFont::HintingPreference hintingPreference)
Definition at line 103 of file qrawfont_ft.cpp.
Referenced by QRawFont::loadFromData(), releaseFontData(), and resolveGdi32().
 {
     Q_ASSERT(fontEngine == 0);
     QFontDef fontDef;
     fontDef.pixelSize = pixelSize;
     QFontEngineFTRawFont *fe = new QFontEngineFTRawFont(fontDef);
     if (!fe->initFromData(fontData)) {
         delete fe;
         return;
     }
     fe->updateFamilyNameAndStyle();
     switch (hintingPreference) {
     case QFont::PreferNoHinting:
         fe->setDefaultHintStyle(QFontEngineFT::HintNone);
         break;
     case QFont::PreferFullHinting:
         fe->setDefaultHintStyle(QFontEngineFT::HintFull);
         break;
     case QFont::PreferVerticalHinting:
         fe->setDefaultHintStyle(QFontEngineFT::HintLight);
         break;
     default:
         // Leave it as it is
         break;
     }
     fontEngine = fe;
     fontEngine->ref.ref();
 }
Properties
fontEngine
QFontEngine* QRawFontPrivate::fontEngine
Definition at line 111 of file qrawfont_p.h.
Referenced by QRawFont::advancesForGlyphIndexes(), QRawFont::alphaMapForGlyph(), QRawFont::ascent(), QRawFont::averageCharWidth(), QRawFont::descent(), QPainter::drawGlyphRun(), QPainterPrivate::drawGlyphs(), QRawFont::familyName(), QRawFont::fontTable(), QRawFont::fromFont(), QRawFont::glyphIndexesForChars(), QTextLine::glyphs(), QRawFont::leading(), QRawFont::maxCharWidth(), QRawFont::operator==(), QRawFont::pathForGlyph(), QRawFont::pixelSize(), platformLoadFromData(), QPainterReplayer::process(), releaseFontData(), QRawFont::setPixelSize(), QRawFont::style(), QRawFont::styleName(), QRawFont::supportsCharacter(), QRawFont::unitsPerEm(), QRawFont::weight(), and QRawFont::xHeight().
fontHandle
HANDLE QRawFontPrivate::fontHandle
Definition at line 117 of file qrawfont_p.h.
hintingPreference
QFont::HintingPreference QRawFontPrivate::hintingPreference
Definition at line 112 of file qrawfont_p.h.
Referenced by QRawFont::fromFont(), QTextLine::glyphs(), QRawFont::hintingPreference(), QRawFont::loadFromData(), and releaseFontData().
ref
QAtomicInt QRawFontPrivate::ref
Definition at line 114 of file qrawfont_p.h.
thread
QThread* QRawFontPrivate::thread
Definition at line 113 of file qrawfont_p.h.
Referenced by QRawFont::loadFromData().
The documentation for this class was generated from the following files:
/src/gui/text/qrawfont_p.h
/src/gui/text/qrawfont.cpp
/src/gui/text/qrawfont_ft.cpp
/src/gui/text/qrawfont_mac.cpp
/src/gui/text/qrawfont_qpa.cpp
/src/gui/text/qrawfont_win.cpp