Qt 4.8: QPatternist::FunctionFactory Class Reference
QPatternist::FunctionFactory Class Reference abstract
An entry point for looking up and creating FunctionCall instances.
#include <qfunctionfactory_p.h>
Public Types
typedef QList< FunctionFactory::Ptr > List
typedef QExplicitlySharedDataPointer< FunctionFactory > Ptr
Public Functions
virtual Expression::Ptr createFunctionCall (const QXmlName name, const Expression::List &arguments, const StaticContext::Ptr &context, const SourceLocationReflection *const r)=0
virtual FunctionSignature::Hash functionSignatures () const =0
bool hasSignature (const FunctionSignature::Ptr &signature) const
virtual bool isAvailable (const NamePool::Ptr &np, const QXmlName name, const xsInteger arity)
virtual ~FunctionFactory ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Protected Functions
FunctionFactory ()
This constructor cannot be removed, because it can't be synthesized, for some reason.
virtual FunctionSignature::Ptr retrieveFunctionSignature (const NamePool::Ptr &np, const QXmlName name)=0
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
An entry point for looking up and creating FunctionCall instances.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators
XML Path Language (XPath) 2.0, Definition: Function signatures
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 81 of file qfunctionfactory_p.h.
Typedefs
List
typedef QList<FunctionFactory::Ptr> QPatternist::FunctionFactory::List
Definition at line 86 of file qfunctionfactory_p.h.
Ptr
typedef QExplicitlySharedDataPointer<FunctionFactory> QPatternist::FunctionFactory::Ptr
Definition at line 85 of file qfunctionfactory_p.h.
Constructors and Destructors
~FunctionFactory()
FunctionFactory::~FunctionFactory () virtual
Definition at line 50 of file qfunctionfactory.cpp.
 {
 }
FunctionFactory()
QPatternist::FunctionFactory::FunctionFactory () inline protected
This constructor cannot be removed, because it can't be synthesized, for some reason.
Definition at line 144 of file qfunctionfactory_p.h.
         {
         }
Functions
createFunctionCall()
virtual Expression::Ptr QPatternist::FunctionFactory::createFunctionCall (const QXmlName name, const Expression::List & arguments, const StaticContext::Ptr & context, const SourceLocationReflection *const r) pure virtual
Creates a function call implementation.
A FunctionFactory represents a set of functions, which it is able to instantiate and to serve FunctionSignatures for. Conventionally, a FunctionFactory per namespace exists.
Note
This function should not issue any error unless it is absolutely confident that the error cannot be fixed in another way. For example, in some cases it might be that a function is available in another FunctionFactory and it would therefore be wrong to issue an error signalling that no function by that name exists, but leave that to the callee.
Parameters
name the name of the function to create. In Clark syntax, this could for example be {http://www.w3.org/2005/04/xpath-functions}lower-case
arguments the function's operands
context the usual StaticContext which supplies compile time data and reporting functionality.
r the SourceLocationReflection that identifies the callsite.
Returns
an instance of Expression which is the function implementation for name. Or, a static error was raised.
Implemented in QPatternist::FunctionFactoryCollection, and QPatternist::AbstractFunctionFactory.
Referenced by QPatternist::ByIDCreator::create().
functionSignatures()
virtual FunctionSignature::Hash QPatternist::FunctionFactory::functionSignatures () const pure virtual
Implemented in QPatternist::FunctionFactoryCollection, and QPatternist::AbstractFunctionFactory.
Referenced by hasSignature().
hasSignature()
bool FunctionFactory::hasSignature (const FunctionSignature::Ptr & signature) const
Determines whether this FunctionFactory contains the function signature signature.
The implementation uses functionSignatures().
Definition at line 65 of file qfunctionfactory.cpp.
 {
     const FunctionSignature::Hash signs(functionSignatures());
     const FunctionSignature::Hash::const_iterator end(signs.constEnd());
     FunctionSignature::Hash::const_iterator it(signs.constBegin());
     for(; it != end; ++it)
     {
         if(*(*it) == *signature)
             return true;
     }
     return false;
 }
isAvailable()
bool FunctionFactory::isAvailable (const NamePool::Ptr & np, const QXmlName name, const xsInteger arity) virtual
Determines whether a function with the name name and arity arity is available. The implementation operates on the result of retrieveFunctionSignature() to determine the result.
Parameters
np the NamePool.
name the name of the function. For example fn:string-join.
arity the number of arguments the function must have.
Reimplemented in QPatternist::FunctionFactoryCollection.
Definition at line 54 of file qfunctionfactory.cpp.
Referenced by QPatternist::FunctionAvailableFN::evaluateSingleton().
 {
     const FunctionSignature::Ptr sign(retrieveFunctionSignature(np, name));
     if(sign)
         return arity == FunctionSignature::UnlimitedArity || sign->isArityValid(arity);
     else
         return false;
 }
retrieveFunctionSignature()
virtual FunctionSignature::Ptr QPatternist::FunctionFactory::retrieveFunctionSignature (const NamePool::Ptr & np, const QXmlName name) protected pure virtual
This is a convenience function for sub-classes. It retrieves the function signature for function with name name.
According to the specifications are function signatures identified by their name and arity, but currently is the arity not part of the signature.
If no function could be found for the given name, null is returned.
Implemented in QPatternist::FunctionFactoryCollection, QPatternist::XPath20CoreFunctions, QPatternist::XPath10CoreFunctions, QPatternist::XSLT20CoreFunctions, and QPatternist::ConstructorFunctionsFactory.
Referenced by QPatternist::AbstractFunctionFactory::createFunctionCall(), FunctionFactory(), and isAvailable().
The documentation for this class was generated from the following files:
/src/xmlpatterns/functions/qfunctionfactory_p.h
/src/xmlpatterns/functions/qfunctionfactory.cpp