Qt 4.8: QTcpServerConnection Class Reference
QTcpServerConnection Class Reference
#include <qtcpserverconnection.h>
Public Functions
void disconnect ()
bool isConnected () const
void listen ()
QTcpServerConnection ()
void send (const QByteArray &message)
void setPort (int port, bool bock)
void setServer (QDeclarativeDebugServer *server)
void waitForConnection ()
bool waitForMessage ()
~QTcpServerConnection ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeDebugServerConnection
QDeclarativeDebugServerConnection ()
virtual ~QDeclarativeDebugServerConnection ()
Private Slots
void newConnection ()
void readyRead ()
Properties
QTcpServerConnectionPrivate * d_ptr
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 51 of file qtcpserverconnection.h.
Constructors and Destructors
QTcpServerConnection()
QTcpServerConnection::QTcpServerConnection ()
Definition at line 76 of file qtcpserverconnection.cpp.
                                            :
     d_ptr(new QTcpServerConnectionPrivate)
 {
 }
~QTcpServerConnection()
QTcpServerConnection::~QTcpServerConnection ()
Definition at line 82 of file qtcpserverconnection.cpp.
 {
     delete d_ptr;
 }
Functions
disconnect()
void QTcpServerConnection::disconnect () virtual
Implements QDeclarativeDebugServerConnection.
Definition at line 114 of file qtcpserverconnection.cpp.
 {
     Q_D(QTcpServerConnection);
     // protocol might still be processing packages at this point
     d->protocol->deleteLater();
     d->protocol = 0;
     d->socket->deleteLater();
     d->socket = 0;
 }
isConnected()
bool QTcpServerConnection::isConnected () const virtual
Implements QDeclarativeDebugServerConnection.
Definition at line 93 of file qtcpserverconnection.cpp.
Referenced by send().
 {
     Q_D(const QTcpServerConnection);
     return d->socket && d->socket->state() == QTcpSocket::ConnectedState;
 }
listen()
void QTcpServerConnection::listen ()
Definition at line 148 of file qtcpserverconnection.cpp.
Referenced by setPort().
 {
     Q_D(QTcpServerConnection);
     d->tcpServer = new QTcpServer(this);
     QObject::connect(d->tcpServer, SIGNAL(newConnection()), this, SLOT(newConnection()));
     if (d->tcpServer->listen(QHostAddress::Any, d->port)) {
         qDebug("QDeclarativeDebugServer: Waiting for connection on port %d...", d->port);
     } else {
         qWarning("QDeclarativeDebugServer: Unable to listen on port %d", d->port);
     }
 }
newConnection
void QTcpServerConnection::newConnection () private slot
Definition at line 174 of file qtcpserverconnection.cpp.
Referenced by listen().
 {
     Q_D(QTcpServerConnection);
     if (d->socket) {
         qWarning("QDeclarativeDebugServer: Another client is already connected");
         QTcpSocket *faultyConnection = d->tcpServer->nextPendingConnection();
         delete faultyConnection;
         return;
     }
     d->socket = d->tcpServer->nextPendingConnection();
     d->socket->setParent(this);
     d->protocol = new QPacketProtocol(d->socket, this);
     QObject::connect(d->protocol, SIGNAL(readyRead()), this, SLOT(readyRead()));
     if (d->block) {
         d->protocol->waitForReadyRead(-1);
     }
 }
readyRead
void QTcpServerConnection::readyRead () private slot
Definition at line 162 of file qtcpserverconnection.cpp.
Referenced by newConnection().
 {
     Q_D(QTcpServerConnection);
     if (!d->protocol)
         return;
     while (d->protocol->packetsAvailable() > 0) {
         QPacket packet = d->protocol->read();
         d->debugServer->receiveMessage(packet.data());
     }
 }
send()
void QTcpServerConnection::send (const QByteArray & message) virtual
Implements QDeclarativeDebugServerConnection.
Definition at line 99 of file qtcpserverconnection.cpp.
 {
     Q_D(QTcpServerConnection);
     if (!isConnected()
             || !d->protocol || !d->socket)
         return;
     QPacket pack;
     pack.writeRawData(message.data(), message.length());
     d->protocol->send(pack);
     d->socket->flush();
 }
setPort()
void QTcpServerConnection::setPort (int port, bool bock) virtual
Implements QDeclarativeDebugServerConnection.
Definition at line 137 of file qtcpserverconnection.cpp.
 {
     Q_D(QTcpServerConnection);
     d->port = port;
     d->block = block;
     listen();
     if (block)
         d->tcpServer->waitForNewConnection(-1);
 }
setServer()
void QTcpServerConnection::setServer (QDeclarativeDebugServer * server) virtual
Implements QDeclarativeDebugServerConnection.
Definition at line 87 of file qtcpserverconnection.cpp.
 {
     Q_D(QTcpServerConnection);
     d->debugServer = server;
 }
waitForConnection()
void QTcpServerConnection::waitForConnection ()
waitForMessage()
bool QTcpServerConnection::waitForMessage () virtual
Implements QDeclarativeDebugServerConnection.
Definition at line 125 of file qtcpserverconnection.cpp.
 {
     Q_D(QTcpServerConnection);
     if (d->protocol->packetsAvailable() > 0) {
         QPacket packet = d->protocol->read();
         d->debugServer->receiveMessage(packet.data());
         return true;
     } else {
         return d->protocol->waitForReadyRead(-1);
     }
 }
Properties
d_ptr
QTcpServerConnectionPrivate* QTcpServerConnection::d_ptr private
Definition at line 79 of file qtcpserverconnection.h.
Referenced by ~QTcpServerConnection().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_tcp/qtcpserverconnection.h
/src/plugins/qmltooling/qmldbg_tcp/qtcpserverconnection.cpp