Qt 4.8: QPaintEngineEx Class Reference
QPaintEngineEx Class Reference abstract
#include <qpaintengineex_p.h>
Public Types
enum Flags { DoNotEmulate = 0x01, IsEmulationEngine = 0x02 }
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Functions
virtual void beginNativePainting ()
virtual void brushChanged ()=0
virtual void brushOriginChanged ()=0
virtual void clip (const QVectorPath &path, Qt::ClipOperation op)=0
virtual void clip (const QRect &rect, Qt::ClipOperation op)
virtual void clip (const QRegion &region, Qt::ClipOperation op)
virtual void clip (const QPainterPath &path, Qt::ClipOperation op)
virtual void clipEnabledChanged ()=0
virtual void compositionModeChanged ()=0
virtual QPainterState * createState (QPainterState *orig) const
virtual void draw (const QVectorPath &path)
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)=0
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawImage (const QPointF &pos, const QImage &image)
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
virtual void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
virtual void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)=0
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
virtual void drawPixmap (const QPointF &pos, const QPixmap &pm)
virtual void drawPixmapFragments (const QPainter::PixmapFragment *fragments, int fragmentCount, const QPixmap &pixmap, QPainter::PixmapFragmentHints hints)
virtual void drawPixmapFragments (const QRectF *targetRects, const QRectF *sourceRects, int fragmentCount, const QPixmap &pixmap, QPainter::PixmapFragmentHints hints)
virtual void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
virtual void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
virtual void drawRoundedRect (const QRectF &rect, qreal xrad, qreal yrad, Qt::SizeMode mode)
virtual void drawStaticTextItem (QStaticTextItem *)
virtual void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
virtual void endNativePainting ()
virtual void fill (const QVectorPath &path, const QBrush &brush)=0
virtual void fillRect (const QRectF &rect, const QBrush &brush)
virtual void fillRect (const QRectF &rect, const QColor &color)
virtual uint flags () const
virtual void opacityChanged ()=0
virtual void penChanged ()=0
virtual QPixmapFilter * pixmapFilter (int, const QPixmapFilter *)
QPaintEngineEx ()
virtual void renderHintsChanged ()=0
virtual void setState (QPainterState *s)
QPainterState * state ()
const QPainterState * state () const
virtual void stroke (const QVectorPath &path, const QPen &pen)
virtual bool supportsTransformations (qreal pixelSize, const QTransform &m) const
virtual void sync ()
virtual void transformChanged ()=0
virtual void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
Public Functions inherited from QPaintEngine
virtual bool begin (QPaintDevice *pdev)=0
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
virtual bool end ()=0
Reimplement this function to finish painting on the current paint device.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual Type type () const =0
Reimplement this function to return the paint engine Type.
virtual ~QPaintEngine ()
Destroys the paint engine.
Protected Functions
QPaintEngineEx (QPaintEngineExPrivate &data)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Additional Inherited Members
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 143 of file qpaintengineex_p.h.
Enumerations
Flags
enum QPaintEngineEx::Flags
Enumerator
DoNotEmulate
IsEmulationEngine
Definition at line 226 of file qpaintengineex_p.h.
     {
         DoNotEmulate = 0x01,        // If set, QPainter will not wrap this engine in an emulation engine.
         IsEmulationEngine = 0x02    // If set, this object is a QEmulationEngine.
     };
Constructors and Destructors
QPaintEngineEx() [1/2]
QPaintEngineEx::QPaintEngineEx ()
Definition at line 367 of file qpaintengineex.cpp.
     : QPaintEngine(*new QPaintEngineExPrivate, AllFeatures)
 {
     extended = true;
 }
QPaintEngineEx() [2/2]
QPaintEngineEx::QPaintEngineEx (QPaintEngineExPrivate & data) protected
Definition at line 373 of file qpaintengineex.cpp.
     : QPaintEngine(data, AllFeatures)
 {
     extended = true;
 }
Functions
beginNativePainting()
virtual void QPaintEngineEx::beginNativePainting () inline virtual
Reimplemented in QGL2PaintEngineEx, QVGPaintEngine, and QEmulationPaintEngine.
Definition at line 215 of file qpaintengineex_p.h.
Referenced by QEmulationPaintEngine::beginNativePainting(), and QVGPaintEngine::state().
 {}
brushChanged()
virtual void QPaintEngineEx::brushChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Referenced by QEmulationPaintEngine::brushChanged(), and QVGPaintEngine::type().
brushOriginChanged()
virtual void QPaintEngineEx::brushOriginChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QEmulationPaintEngine, and QOpenGLPaintEngine.
Referenced by QEmulationPaintEngine::brushOriginChanged(), and QVGPaintEngine::type().
clip() [1/4]
virtual void QPaintEngineEx::clip (const QVectorPath & path, Qt::ClipOperation op) pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QDirectFBPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, and QEmulationPaintEngine.
Referenced by QEmulationPaintEngine::clip(), QVGPaintEngine::clip(), clip(), QRasterPaintEngine::clip(), QPaintBufferEngine::clip(), clipTransformIsSimple(), and QVGPaintEngine::type().
clip() [2/4]
void QPaintEngineEx::clip (const QRect & rect, Qt::ClipOperation op) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QDirectFBPaintEngine, and QVGPaintEngine.
Definition at line 607 of file qpaintengineex.cpp.
 {
     qreal right = r.x() + r.width();
     qreal bottom = r.y() + r.height();
     qreal pts[] = { qreal(r.x()), qreal(r.y()),
                     right, qreal(r.y()),
                     right, bottom,
                     qreal(r.x()), bottom,
                     qreal(r.x()), qreal(r.y()) };
     QVectorPath vp(pts, 5, 0, QVectorPath::RectangleHint);
     clip(vp, op);
 }
clip() [3/4]
void QPaintEngineEx::clip (const QRegion & region, Qt::ClipOperation op) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QDirectFBPaintEngine, and QVGPaintEngine.
Definition at line 620 of file qpaintengineex.cpp.
 {
     if (region.rectCount() == 1)
         clip(region.boundingRect(), op);
     QVector<QRect> rects = region.rects();
     if (rects.size() <= 32) {
         qreal pts[2*32*4];
         int pos = 0;
         for (QVector<QRect>::const_iterator i = rects.constBegin(); i != rects.constEnd(); ++i) {
             qreal x1 = i->x();
             qreal y1 = i->y();
             qreal x2 = i->x() + i->width();
             qreal y2 = i->y() + i->height();
             pts[pos++] = x1;
             pts[pos++] = y1;
             pts[pos++] = x2;
             pts[pos++] = y1;
             pts[pos++] = x2;
             pts[pos++] = y2;
             pts[pos++] = x1;
             pts[pos++] = y2;
         }
         QVectorPath vp(pts, rects.size() * 4, qpaintengineex_rect4_types_32);
         clip(vp, op);
     } else {
         QVarLengthArray<qreal> pts(rects.size() * 2 * 4);
         QVarLengthArray<QPainterPath::ElementType> types(rects.size() * 4);
         int ppos = 0;
         int tpos = 0;
         for (QVector<QRect>::const_iterator i = rects.constBegin(); i != rects.constEnd(); ++i) {
             qreal x1 = i->x();
             qreal y1 = i->y();
             qreal x2 = i->x() + i->width();
             qreal y2 = i->y() + i->height();
             pts[ppos++] = x1;
             pts[ppos++] = y1;
             pts[ppos++] = x2;
             pts[ppos++] = y1;
             pts[ppos++] = x2;
             pts[ppos++] = y2;
             pts[ppos++] = x1;
             pts[ppos++] = y2;
             types[tpos++] = QPainterPath::MoveToElement;
             types[tpos++] = QPainterPath::LineToElement;
             types[tpos++] = QPainterPath::LineToElement;
             types[tpos++] = QPainterPath::LineToElement;
         }
         QVectorPath vp(pts.data(), rects.size() * 4, types.data());
         clip(vp, op);
     }
 }
clip() [4/4]
void QPaintEngineEx::clip (const QPainterPath & path, Qt::ClipOperation op) virtual
Reimplemented in QPaintBufferEngine, and QVGPaintEngine.
Definition at line 685 of file qpaintengineex.cpp.
 {
     if (path.isEmpty()) {
         QVectorPath vp(0, 0);
         clip(vp, op);
     } else {
         clip(qtVectorPathForPath(path), op);
     }
 }
clipEnabledChanged()
virtual void QPaintEngineEx::clipEnabledChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Referenced by QEmulationPaintEngine::clipEnabledChanged(), and QVGPaintEngine::type().
compositionModeChanged()
virtual void QPaintEngineEx::compositionModeChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Referenced by QEmulationPaintEngine::compositionModeChanged(), and QVGPaintEngine::type().
createState()
QPainterState * QPaintEngineEx::createState (QPainterState * orig) const virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QOpenGLPaintEngine, QVGPaintEngine, and QEmulationPaintEngine.
Definition at line 379 of file qpaintengineex.cpp.
Referenced by QEmulationPaintEngine::createState(), and QVGPaintEngine::type().
 {
     if (!orig)
         return new QPainterState;
     return new QPainterState(orig);
 }
draw()
void QPaintEngineEx::draw (const QVectorPath & path) virtual
Reimplemented in QPaintBufferEngine, and QVGPaintEngine.
Definition at line 595 of file qpaintengineex.cpp.
Referenced by QVGPaintEngine::draw(), drawEllipse(), drawPath(), drawPolygon(), drawRects(), drawRoundedRect(), and QVGPaintEngine::type().
 {
     const QBrush &brush = state()->brush;
     if (qbrush_style(brush) != Qt::NoBrush)
         fill(path, brush);
     const QPen &pen = state()->pen;
     if (qpen_style(pen) != Qt::NoPen && qbrush_style(qpen_brush(pen)) != Qt::NoBrush)
         stroke(path, pen);
 }
drawEllipse() [1/2]
void QPaintEngineEx::drawEllipse (const QRectF & rect) virtual
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
The default implementation calls drawPolygon().
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QDirectFBPaintEngine, and QBlitterPaintEngine.
Definition at line 825 of file qpaintengineex.cpp.
Referenced by QVGPaintEngine::drawEllipse(), QOpenGLPaintEngine::drawEllipse(), QRasterPaintEngine::drawEllipse(), drawEllipse(), and QVGPaintEngine::type().
 {
     qreal pts[26]; // QPointF[13] without constructors...
     union {
         qreal *ptr;
         QPointF *points;
     } x;
     x.ptr = pts;
     int point_count = 0;
     x.points[0] = qt_curves_for_arc(r, 0, -360, x.points + 1, &point_count);
     QVectorPath vp((qreal *) pts, point_count + 1, qpaintengineex_ellipse_types, QVectorPath::EllipseHint);
     draw(vp);
 }
drawEllipse() [2/2]
void QPaintEngineEx::drawEllipse (const QRect & r) virtual
The default implementation of this function calls the floating point version of this function.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, and QVGPaintEngine.
Definition at line 840 of file qpaintengineex.cpp.
 {
     drawEllipse(QRectF(r));
 }
drawImage() [1/2]
virtual void QPaintEngineEx::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) pure virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented from QPaintEngine.
Implemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QOpenGLPaintEngine, QGL2PaintEngineEx, QBlitterPaintEngine, QEmulationPaintEngine, and QDirectFBPaintEngine.
Referenced by QEmulationPaintEngine::drawImage(), drawImage(), and QVGPaintEngine::type().
drawImage() [2/2]
void QPaintEngineEx::drawImage (const QPointF & pos, const QImage & image) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 955 of file qpaintengineex.cpp.
 {
     drawImage(QRectF(pos, image.size()), image, image.rect());
 }
drawLines() [1/2]
void QPaintEngineEx::drawLines (const QLine * lines, int lineCount) virtual
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, and QDirectFBPaintEngine.
Definition at line 784 of file qpaintengineex.cpp.
Referenced by QVGPaintEngine::drawLines(), QOpenGLPaintEngine::drawLines(), QRasterPaintEngine::drawLines(), and QVGPaintEngine::type().
 {
     int elementCount = lineCount << 1;
     while (elementCount > 0) {
         int count = qMin(elementCount, 32);
         qreal pts[64];
         int count2 = count<<1;
 #ifdef Q_WS_MAC
         for (int i=0; i<count2; i+=2) {
             pts[i] = ((int *) lines)[i+1];
             pts[i+1] = ((int *) lines)[i];
         }
 #else
         for (int i=0; i<count2; ++i)
             pts[i] = ((int *) lines)[i];
 #endif
         QVectorPath path(pts, count, qpaintengineex_line_types_16, QVectorPath::LinesHint);
         stroke(path, state()->pen);
         elementCount -= 32;
         lines += 16;
     }
 }
drawLines() [2/2]
void QPaintEngineEx::drawLines (const QLineF * lines, int lineCount) virtual
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, and QDirectFBPaintEngine.
Definition at line 810 of file qpaintengineex.cpp.
 {
     int elementCount = lineCount << 1;
     while (elementCount > 0) {
         int count = qMin(elementCount, 32);
         QVectorPath path((qreal *) lines, count, qpaintengineex_line_types_16,
                          QVectorPath::LinesHint);
         stroke(path, state()->pen);
         elementCount -= 32;
         lines += 16;
     }
 }
drawPath()
void QPaintEngineEx::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QOpenGLPaintEngine, QVGPaintEngine, and QDirectFBPaintEngine.
Definition at line 845 of file qpaintengineex.cpp.
Referenced by QDirectFBPaintEngine::drawPath(), QVGPaintEngine::drawPath(), QOpenGLPaintEngine::drawPath(), QPaintBufferEngine::drawPath(), and QVGPaintEngine::type().
 {
     if (!path.isEmpty())
         draw(qtVectorPathForPath(path));
 }
drawPixmap() [1/2]
virtual void QPaintEngineEx::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) pure virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngine.
Implemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QGL2PaintEngineEx, QOpenGLPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QBlitterPaintEngine, and QVolatileImagePaintEngine.
Referenced by QEmulationPaintEngine::drawPixmap(), drawPixmap(), drawPixmapFragments(), and QVGPaintEngine::type().
drawPixmap() [2/2]
void QPaintEngineEx::drawPixmap (const QPointF & pos, const QPixmap & pm) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QDirectFBPaintEngine, QBlitterPaintEngine, and QVolatileImagePaintEngine.
Definition at line 950 of file qpaintengineex.cpp.
 {
     drawPixmap(QRectF(pos, pm.size()), pm, pm.rect());
 }
drawPixmapFragments() [1/2]
void QPaintEngineEx::drawPixmapFragments (const QPainter::PixmapFragment * fragments, int fragmentCount, const QPixmap & pixmap, QPainter::PixmapFragmentHints hints) virtual
Reimplemented in QGL2PaintEngineEx, and QEmulationPaintEngine.
Definition at line 975 of file qpaintengineex.cpp.
Referenced by QEmulationPaintEngine::drawPixmapFragments(), QGL2PaintEngineEx::drawPixmapFragments(), QVGPaintEngine::drawPixmapFragments(), and QVGPaintEngine::type().
 {
     if (pixmap.isNull())
         return;
     qreal oldOpacity = state()->opacity;
     QTransform oldTransform = state()->matrix;
     for (int i = 0; i < fragmentCount; ++i) {
         QTransform transform = oldTransform;
         transform.translate(fragments[i].x, fragments[i].y);
         transform.rotate(fragments[i].rotation);
         state()->opacity = oldOpacity * fragments[i].opacity;
         state()->matrix = transform;
         opacityChanged();
         transformChanged();
         qreal w = fragments[i].scaleX * fragments[i].width;
         qreal h = fragments[i].scaleY * fragments[i].height;
         QRectF sourceRect(fragments[i].sourceLeft, fragments[i].sourceTop,
                           fragments[i].width, fragments[i].height);
         drawPixmap(QRectF(-0.5 * w, -0.5 * h, w, h), pixmap, sourceRect);
     }
     state()->opacity = oldOpacity;
     state()->matrix = oldTransform;
     opacityChanged();
     transformChanged();
 }
drawPixmapFragments() [2/2]
void QPaintEngineEx::drawPixmapFragments (const QRectF * targetRects, const QRectF * sourceRects, int fragmentCount, const QPixmap & pixmap, QPainter::PixmapFragmentHints hints) virtual
Reimplemented in QGL2PaintEngineEx, and QEmulationPaintEngine.
Definition at line 1006 of file qpaintengineex.cpp.
 {
     if (pixmap.isNull())
         return;
     if (sourceRects) {
         for (int i = 0; i < fragmentCount; ++i)
             drawPixmap(targetRects[i], pixmap, sourceRects[i]);
     } else {
         QRectF sourceRect = pixmap.rect();
         for (int i = 0; i < fragmentCount; ++i)
             drawPixmap(targetRects[i], pixmap, sourceRect);
     }
 }
drawPoints() [1/2]
void QPaintEngineEx::drawPoints (const QPointF * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QOpenGLPaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 852 of file qpaintengineex.cpp.
Referenced by QOpenGLPaintEngine::drawPoints(), QVGPaintEngine::drawPoints(), QRasterPaintEngine::drawPoints(), and QVGPaintEngine::type().
 {
     QPen pen = state()->pen;
     if (pen.capStyle() == Qt::FlatCap)
         pen.setCapStyle(Qt::SquareCap);
     if (pen.brush().isOpaque()) {
         while (pointCount > 0) {
             int count = qMin(pointCount, 16);
             qreal pts[64];
             int oset = -1;
             for (int i=0; i<count; ++i) {
                 pts[++oset] = points[i].x();
                 pts[++oset] = points[i].y();
                 pts[++oset] = points[i].x() + 1/qreal(63.);
                 pts[++oset] = points[i].y();
             }
             QVectorPath path(pts, count * 2, qpaintengineex_line_types_16, QVectorPath::LinesHint);
             stroke(path, pen);
             pointCount -= 16;
             points += 16;
         }
     } else {
         for (int i=0; i<pointCount; ++i) {
             qreal pts[] = { points[i].x(), points[i].y(), points[i].x() + 1/qreal(63.), points[i].y() };
             QVectorPath path(pts, 2, 0);
             stroke(path, pen);
         }
     }
 }
drawPoints() [2/2]
void QPaintEngineEx::drawPoints (const QPoint * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
The default implementation converts the first pointCount QPoints in points to QPointFs and calls the floating point version of drawPoints.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QOpenGLPaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 883 of file qpaintengineex.cpp.
 {
     QPen pen = state()->pen;
     if (pen.capStyle() == Qt::FlatCap)
         pen.setCapStyle(Qt::SquareCap);
     if (pen.brush().isOpaque()) {
         while (pointCount > 0) {
             int count = qMin(pointCount, 16);
             qreal pts[64];
             int oset = -1;
             for (int i=0; i<count; ++i) {
                 pts[++oset] = points[i].x();
                 pts[++oset] = points[i].y();
                 pts[++oset] = points[i].x() + 1/qreal(63.);
                 pts[++oset] = points[i].y();
             }
             QVectorPath path(pts, count * 2, qpaintengineex_line_types_16, QVectorPath::LinesHint);
             stroke(path, pen);
             pointCount -= 16;
             points += 16;
         }
     } else {
         for (int i=0; i<pointCount; ++i) {
             qreal pts[] = { qreal(points[i].x()), qreal(points[i].y()),
                             qreal(points[i].x() +1/qreal(63.)), qreal(points[i].y()) };
             QVectorPath path(pts, 2, 0);
             stroke(path, pen);
         }
     }
 }
drawPolygon() [1/2]
void QPaintEngineEx::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QDirectFBPaintEngine, and QBlitterPaintEngine.
Definition at line 916 of file qpaintengineex.cpp.
Referenced by QVGPaintEngine::drawPolygon(), QOpenGLPaintEngine::drawPolygon(), and QVGPaintEngine::type().
 {
     QVectorPath path((qreal *) points, pointCount, 0, QVectorPath::polygonFlags(mode));
     if (mode == PolylineMode)
         stroke(path, state()->pen);
     else
         draw(path);
 }
drawPolygon() [2/2]
void QPaintEngineEx::drawPolygon (const QPoint * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QDirectFBPaintEngine, and QBlitterPaintEngine.
Definition at line 926 of file qpaintengineex.cpp.
 {
     int count = pointCount<<1;
     QVarLengthArray<qreal> pts(count);
 #ifdef Q_WS_MAC
     for (int i=0; i<count; i+=2) {
         pts[i] = ((int *) points)[i+1];
         pts[i+1] = ((int *) points)[i];
     }
 #else
     for (int i=0; i<count; ++i)
         pts[i] = ((int *) points)[i];
 #endif
     QVectorPath path(pts.data(), pointCount, 0, QVectorPath::polygonFlags(mode));
     if (mode == PolylineMode)
         stroke(path, state()->pen);
     else
         draw(path);
 }
drawRects() [1/2]
void QPaintEngineEx::drawRects (const QRect * rects, int rectCount) virtual
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 708 of file qpaintengineex.cpp.
Referenced by QVGPaintEngine::drawRects(), QOpenGLPaintEngine::drawRects(), QRasterPaintEngine::drawRects(), and QVGPaintEngine::type().
 {
     for (int i=0; i<rectCount; ++i) {
         const QRect &r = rects[i];
         // ### Is there a one off here?
         qreal right = r.x() + r.width();
         qreal bottom = r.y() + r.height();
         qreal pts[] = { qreal(r.x()), qreal(r.y()),
                         right, qreal(r.y()),
                         right, bottom,
                         qreal(r.x()), bottom,
                         qreal(r.x()), qreal(r.y()) };
         QVectorPath vp(pts, 5, 0, QVectorPath::RectangleHint);
         draw(vp);
     }
 }
drawRects() [2/2]
void QPaintEngineEx::drawRects (const QRectF * rects, int rectCount) virtual
Draws the first rectCount rectangles in the buffer rects.
The default implementation of this function calls drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QOpenGLPaintEngine, QVGPaintEngine, QBlitterPaintEngine, and QDirectFBPaintEngine.
Definition at line 725 of file qpaintengineex.cpp.
 {
     for (int i=0; i<rectCount; ++i) {
         const QRectF &r = rects[i];
         qreal right = r.x() + r.width();
         qreal bottom = r.y() + r.height();
         qreal pts[] = { r.x(), r.y(),
                         right, r.y(),
                         right, bottom,
                         r.x(), bottom,
                         r.x(), r.y() };
         QVectorPath vp(pts, 5, 0, QVectorPath::RectangleHint);
         draw(vp);
     }
 }
drawRoundedRect()
void QPaintEngineEx::drawRoundedRect (const QRectF & rect, qreal xrad, qreal yrad, Qt::SizeMode mode) virtual
Reimplemented in QVGPaintEngine, and QDirectFBPaintEngine.
Definition at line 742 of file qpaintengineex.cpp.
Referenced by QDirectFBPaintEngine::drawRoundedRect(), QVGPaintEngine::drawRoundedRect(), and QVGPaintEngine::type().
 {
     qreal x1 = rect.left();
     qreal x2 = rect.right();
     qreal y1 = rect.top();
     qreal y2 = rect.bottom();
     if (mode == Qt::RelativeSize) {
         xRadius = xRadius * rect.width() / qreal(200.);
         yRadius = yRadius * rect.height() / qreal(200.);
     }
     xRadius = qMin(xRadius, rect.width() / 2);
     yRadius = qMin(yRadius, rect.height() / 2);
     qreal pts[] = {
         x1 + xRadius, y1,                   // MoveTo
         x2 - xRadius, y1,                   // LineTo
         x2 - (1 - KAPPA) * xRadius, y1,     // CurveTo
         x2, y1 + (1 - KAPPA) * yRadius,
         x2, y1 + yRadius,
         x2, y2 - yRadius,                   // LineTo
         x2, y2 - (1 - KAPPA) * yRadius,     // CurveTo
         x2 - (1 - KAPPA) * xRadius, y2,
         x2 - xRadius, y2,
         x1 + xRadius, y2,                   // LineTo
         x1 + (1 - KAPPA) * xRadius, y2,           // CurveTo
         x1, y2 - (1 - KAPPA) * yRadius,
         x1, y2 - yRadius,
         x1, y1 + yRadius,                   // LineTo
         x1, y1 + (1 - KAPPA) * yRadius,           // CurveTo
         x1 + (1 - KAPPA) * xRadius, y1,
         x1 + xRadius, y1
     };
     QVectorPath path(pts, 17, qpaintengineex_roundedrect_types, QVectorPath::RoundedRectHint);
     draw(path);
 }
drawStaticTextItem()
void QPaintEngineEx::drawStaticTextItem (QStaticTextItem * staticTextItem) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QGL2PaintEngineEx, QOpenGLPaintEngine, QDirectFBPaintEngine, QBlitterPaintEngine, and QEmulationPaintEngine.
Definition at line 1078 of file qpaintengineex.cpp.
Referenced by QDeclarativeTextLayout::draw(), QEmulationPaintEngine::drawStaticTextItem(), QGL2PaintEngineEx::drawStaticTextItem(), QRasterPaintEngine::drawStaticTextItem(), and QVGPaintEngine::type().
 {
     QPainterPath path;
 #ifndef Q_WS_MAC
     path.setFillRule(Qt::WindingFill);
 #endif
     if (staticTextItem->numGlyphs == 0)
         return;
     QFontEngine *fontEngine = staticTextItem->fontEngine();
     fontEngine->addGlyphsToPath(staticTextItem->glyphs, staticTextItem->glyphPositions,
                                 staticTextItem->numGlyphs, &path, 0);
     if (!path.isEmpty()) {
         QPainterState *s = state();
         QPainter::RenderHints oldHints = s->renderHints;
         bool changedHints = false;
         if (bool(oldHints & QPainter::TextAntialiasing)
             && !bool(fontEngine->fontDef.styleStrategy & QFont::NoAntialias)
             && !bool(oldHints & QPainter::Antialiasing)) {
             s->renderHints |= QPainter::Antialiasing;
             renderHintsChanged();
             changedHints = true;
         }
         fill(qtVectorPathForPath(path), s->pen.color());
         if (changedHints) {
             s->renderHints = oldHints;
             renderHintsChanged();
         }
     }
 }
drawTiledPixmap()
void QPaintEngineEx::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QPaintEngine.
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QOpenGLPaintEngine, QBlitterPaintEngine, QDirectFBPaintEngine, and QEmulationPaintEngine.
Definition at line 960 of file qpaintengineex.cpp.
Referenced by QEmulationPaintEngine::drawTiledPixmap(), and QVGPaintEngine::type().
 {
     QBrush brush(state()->pen.color(), pixmap);
     QTransform xform = QTransform::fromTranslate(r.x() - s.x(), r.y() - s.y());
     brush.setTransform(xform);
     qreal pts[] = { r.x(), r.y(),
                     r.x() + r.width(), r.y(),
                     r.x() + r.width(), r.y() + r.height(),
                     r.x(), r.y() + r.height() };
     QVectorPath path(pts, 4, 0, QVectorPath::RectangleHint);
     fill(path, brush);
 }
endNativePainting()
virtual void QPaintEngineEx::endNativePainting () inline virtual
Reimplemented in QGL2PaintEngineEx, QVGPaintEngine, and QEmulationPaintEngine.
Definition at line 216 of file qpaintengineex_p.h.
Referenced by QEmulationPaintEngine::endNativePainting(), and QVGPaintEngine::state().
 {}
fill()
virtual void QPaintEngineEx::fill (const QVectorPath & path, const QBrush & brush) pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QOpenGLPaintEngine, QDirectFBPaintEngine, QVGPaintEngine, QEmulationPaintEngine, and QBlitterPaintEngine.
Referenced by draw(), drawStaticTextItem(), drawTiledPixmap(), QEmulationPaintEngine::fill(), QEmulationPaintEngine::fillBGRect(), fillRect(), stroke(), and QVGPaintEngine::type().
fillRect() [1/2]
void QPaintEngineEx::fillRect (const QRectF & rect, const QBrush & brush) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QDirectFBPaintEngine, and QBlitterPaintEngine.
Definition at line 695 of file qpaintengineex.cpp.
Referenced by QVGPaintEngine::fillRect(), fillRect(), and QVGPaintEngine::type().
 {
     qreal pts[] = { r.x(), r.y(), r.x() + r.width(), r.y(),
                     r.x() + r.width(), r.y() + r.height(), r.x(), r.y() + r.height() };
     QVectorPath vp(pts, 4, 0, QVectorPath::RectangleHint);
     fill(vp, brush);
 }
fillRect() [2/2]
void QPaintEngineEx::fillRect (const QRectF & rect, const QColor & color) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QDirectFBPaintEngine, and QBlitterPaintEngine.
Definition at line 703 of file qpaintengineex.cpp.
 {
     fillRect(r, QBrush(color));
 }
flags()
virtual uint QPaintEngineEx::flags () const inline virtual
Reimplemented in QPaintBufferEngine, and QEmulationPaintEngine.
Definition at line 231 of file qpaintengineex_p.h.
Referenced by QPainterPrivate::checkEmulation(), QVGPaintEngine::drawImage(), QRasterPaintEngineState::QRasterPaintEngineState(), stroke(), QOpenGLPaintEngine::updateState(), and QRasterPaintEngineState::~QRasterPaintEngineState().
 {return 0;}
opacityChanged()
virtual void QPaintEngineEx::opacityChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Referenced by QEmulationPaintEngine::drawPixmapFragments(), drawPixmapFragments(), QEmulationPaintEngine::opacityChanged(), and QVGPaintEngine::type().
penChanged()
virtual void QPaintEngineEx::penChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Referenced by QEmulationPaintEngine::penChanged(), and QVGPaintEngine::type().
pixmapFilter()
virtual QPixmapFilter* QPaintEngineEx::pixmapFilter (int , const QPixmapFilter *) inline virtual
Reimplemented in QGL2PaintEngineEx, and QVGPaintEngine.
Definition at line 223 of file qpaintengineex_p.h.
Referenced by QVGPaintEngine::pixmapFilter(), QGL2PaintEngineEx::pixmapFilter(), and QVGPaintEngine::state().
 { return 0; }
renderHintsChanged()
virtual void QPaintEngineEx::renderHintsChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Referenced by drawStaticTextItem(), QEmulationPaintEngine::renderHintsChanged(), and QVGPaintEngine::type().
setState()
void QPaintEngineEx::setState (QPainterState * s) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QVGPaintEngine, QGL2PaintEngineEx, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Definition at line 1022 of file qpaintengineex.cpp.
Referenced by QPainterPrivate::checkEmulation(), QEmulationPaintEngine::setState(), QOpenGLPaintEngine::setState(), QGL2PaintEngineEx::setState(), QVGPaintEngine::setState(), QRasterPaintEngine::setState(), QPaintBufferEngine::setState(), and QVGPaintEngine::type().
 {
     QPaintEngine::state = s;
 }
state() [1/2]
QPainterState* QPaintEngineEx::state () inline
Definition at line 210 of file qpaintengineex_p.h.
Referenced by QPaintBufferEngine::backgroundModeChanged(), QPaintBufferEngine::brushChanged(), QPaintBufferEngine::brushOriginChanged(), QPaintBufferEngine::clipEnabledChanged(), QPaintBufferEngine::compositionModeChanged(), QPaintBufferEngine::createState(), draw(), QPaintBufferEngine::draw(), drawLines(), QEmulationPaintEngine::drawPixmapFragments(), drawPixmapFragments(), drawPoints(), drawPolygon(), drawStaticTextItem(), drawTiledPixmap(), QPaintBufferEngine::opacityChanged(), QPaintBufferEngine::penChanged(), QEmulationPaintEngine::QEmulationPaintEngine(), QPaintBufferEngine::renderHintsChanged(), QOpenGLPaintEngine::state(), QGL2PaintEngineEx::state(), QVGPaintEngine::state(), QRasterPaintEngine::state(), stroke(), and QPaintBufferEngine::transformChanged().
 { return static_cast<QPainterState *>(QPaintEngine::state); }
state() [2/2]
const QPainterState* QPaintEngineEx::state () const inline
Definition at line 211 of file qpaintengineex_p.h.
 { return static_cast<const QPainterState *>(QPaintEngine::state); }
stroke()
void QPaintEngineEx::stroke (const QVectorPath & path, const QPen & pen) virtual
Reimplemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QBlitterPaintEngine, QVGPaintEngine, QDirectFBPaintEngine, and QEmulationPaintEngine.
Definition at line 388 of file qpaintengineex.cpp.
Referenced by draw(), drawLines(), drawPoints(), QRasterPaintEngine::drawPolygon(), drawPolygon(), QRasterPaintEngine::drawRects(), QEmulationPaintEngine::stroke(), QVGPaintEngine::stroke(), QGL2PaintEngineEx::stroke(), QRasterPaintEngine::stroke(), and QVGPaintEngine::type().
 {
 #ifdef QT_DEBUG_DRAW
     qDebug() << "QPaintEngineEx::stroke()" << pen;
 #endif
     Q_D(QPaintEngineEx);
     if (path.isEmpty())
         return;
     if (!d->strokeHandler) {
         d->strokeHandler = new StrokeHandler(path.elementCount()+4);
         d->stroker.setMoveToHook(qpaintengineex_moveTo);
         d->stroker.setLineToHook(qpaintengineex_lineTo);
         d->stroker.setCubicToHook(qpaintengineex_cubicTo);
     }
     if (!qpen_fast_equals(pen, d->strokerPen)) {
         d->strokerPen = pen;
         d->stroker.setJoinStyle(pen.joinStyle());
         d->stroker.setCapStyle(pen.capStyle());
         d->stroker.setMiterLimit(pen.miterLimit());
         qreal penWidth = pen.widthF();
         if (penWidth == 0)
             d->stroker.setStrokeWidth(1);
         else
             d->stroker.setStrokeWidth(penWidth);
         Qt::PenStyle style = pen.style();
         if (style == Qt::SolidLine) {
             d->activeStroker = &d->stroker;
         } else if (style == Qt::NoPen) {
             d->activeStroker = 0;
         } else {
             d->dasher.setDashPattern(pen.dashPattern());
             d->dasher.setDashOffset(pen.dashOffset());
             d->activeStroker = &d->dasher;
         }
     }
     if (!d->activeStroker) {
         return;
     }
     if (pen.style() > Qt::SolidLine) {
         if (pen.isCosmetic()) {
             d->activeStroker->setClipRect(d->exDeviceRect);
         } else {
             QRectF clipRect = state()->matrix.inverted().mapRect(QRectF(d->exDeviceRect));
             d->activeStroker->setClipRect(clipRect);
         }
     }
     const QPainterPath::ElementType *types = path.elements();
     const qreal *points = path.points();
     int pointCount = path.elementCount();
     const qreal *lastPoint = points + (pointCount<<1);
     d->strokeHandler->types.reset();
     d->strokeHandler->pts.reset();
     // Some engines might decide to optimize for the non-shape hint later on...
     uint flags = QVectorPath::WindingFill;
     if (path.elementCount() > 2)
         flags |= QVectorPath::NonConvexShapeMask;
     if (d->stroker.capStyle() == Qt::RoundCap || d->stroker.joinStyle() == Qt::RoundJoin)
         flags |= QVectorPath::CurvedShapeMask;
     // ### Perspective Xforms are currently not supported...
     if (!pen.isCosmetic()) {
         // We include cosmetic pens in this case to avoid having to
         // change the current transform. Normal transformed,
         // non-cosmetic pens will be transformed as part of fill
         // later, so they are also covered here..
         d->activeStroker->setCurveThresholdFromTransform(state()->matrix);
         d->activeStroker->begin(d->strokeHandler);
         if (types) {
             while (points < lastPoint) {
                 switch (*types) {
                 case QPainterPath::MoveToElement:
                     d->activeStroker->moveTo(points[0], points[1]);
                     points += 2;
                     ++types;
                     break;
                 case QPainterPath::LineToElement:
                     d->activeStroker->lineTo(points[0], points[1]);
                     points += 2;
                     ++types;
                     break;
                 case QPainterPath::CurveToElement:
                     d->activeStroker->cubicTo(points[0], points[1],
                                               points[2], points[3],
                                               points[4], points[5]);
                     points += 6;
                     types += 3;
                     flags |= QVectorPath::CurvedShapeMask;
                     break;
                 default:
                     break;
                 }
             }
             if (path.hasImplicitClose())
                 d->activeStroker->lineTo(path.points()[0], path.points()[1]);
         } else {
             d->activeStroker->moveTo(points[0], points[1]);
             points += 2;
             while (points < lastPoint) {
                 d->activeStroker->lineTo(points[0], points[1]);
                 points += 2;
             }
             if (path.hasImplicitClose())
                 d->activeStroker->lineTo(path.points()[0], path.points()[1]);
         }
         d->activeStroker->end();
         if (!d->strokeHandler->types.size()) // an empty path...
             return;
         QVectorPath strokePath(d->strokeHandler->pts.data(),
                                d->strokeHandler->types.size(),
                                d->strokeHandler->types.data(),
                                flags);
         fill(strokePath, pen.brush());
     } else {
         // For cosmetic pens we need a bit of trickery... We to process xform the input points
         if (state()->matrix.type() >= QTransform::TxProject) {
             QPainterPath painterPath = state()->matrix.map(path.convertToPainterPath());
             d->activeStroker->strokePath(painterPath, d->strokeHandler, QTransform());
         } else {
             d->activeStroker->setCurveThresholdFromTransform(QTransform());
             d->activeStroker->begin(d->strokeHandler);
             if (types) {
                 while (points < lastPoint) {
                     switch (*types) {
                     case QPainterPath::MoveToElement: {
                         QPointF pt = (*(QPointF *) points) * state()->matrix;
                         d->activeStroker->moveTo(pt.x(), pt.y());
                         points += 2;
                         ++types;
                         break;
                     }
                     case QPainterPath::LineToElement: {
                         QPointF pt = (*(QPointF *) points) * state()->matrix;
                         d->activeStroker->lineTo(pt.x(), pt.y());
                         points += 2;
                         ++types;
                         break;
                     }
                     case QPainterPath::CurveToElement: {
                         QPointF c1 = ((QPointF *) points)[0] * state()->matrix;
                         QPointF c2 = ((QPointF *) points)[1] * state()->matrix;
                         QPointF e =  ((QPointF *) points)[2] * state()->matrix;
                         d->activeStroker->cubicTo(c1.x(), c1.y(), c2.x(), c2.y(), e.x(), e.y());
                         points += 6;
                         types += 3;
                         flags |= QVectorPath::CurvedShapeMask;
                         break;
                     }
                     default:
                         break;
                     }
                 }
                 if (path.hasImplicitClose()) {
                     QPointF pt = * ((QPointF *) path.points()) * state()->matrix;
                     d->activeStroker->lineTo(pt.x(), pt.y());
                 }
             } else {
                 QPointF p = ((QPointF *)points)[0] * state()->matrix;
                 d->activeStroker->moveTo(p.x(), p.y());
                 points += 2;
                 while (points < lastPoint) {
                     QPointF p = ((QPointF *)points)[0] * state()->matrix;
                     d->activeStroker->lineTo(p.x(), p.y());
                     points += 2;
                 }
                 if (path.hasImplicitClose())
                     d->activeStroker->lineTo(p.x(), p.y());
             }
             d->activeStroker->end();
         }
         QVectorPath strokePath(d->strokeHandler->pts.data(),
                                d->strokeHandler->types.size(),
                                d->strokeHandler->types.data(),
                                flags);
         QTransform xform = state()->matrix;
         state()->matrix = QTransform();
         transformChanged();
         QBrush brush = pen.brush();
         if (qbrush_style(brush) != Qt::SolidPattern)
             brush.setTransform(brush.transform() * xform);
         fill(strokePath, brush);
         state()->matrix = xform;
         transformChanged();
     }
 }
supportsTransformations()
bool QPaintEngineEx::supportsTransformations (qreal pixelSize, const QTransform & m) const virtual
Reimplemented in QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, and QOpenGLPaintEngine.
Definition at line 1112 of file qpaintengineex.cpp.
 {
     Q_UNUSED(pixelSize);
     if (!m.isAffine())
         return true;
     return false;
 }
sync()
virtual void QPaintEngineEx::sync () inline virtual
Definition at line 213 of file qpaintengineex_p.h.
 {}
transformChanged()
virtual void QPaintEngineEx::transformChanged () pure virtual
Implemented in QPaintBufferEngine, QRasterPaintEngine, QGL2PaintEngineEx, QVGPaintEngine, QDirectFBPaintEngine, QEmulationPaintEngine, QOpenGLPaintEngine, and QBlitterPaintEngine.
Referenced by QPainterPrivate::draw_helper(), QEmulationPaintEngine::drawPixmapFragments(), drawPixmapFragments(), stroke(), QEmulationPaintEngine::transformChanged(), QVGPaintEngine::type(), and QPainterPrivate::updateMatrix().
updateState()
void QPaintEngineEx::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implements QPaintEngine.
Reimplemented in QOpenGLPaintEngine.
Definition at line 1028 of file qpaintengineex.cpp.
 {
     // do nothing...
 }
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintengineex_p.h
/src/gui/painting/qpaintengineex.cpp