Qt 4.8: QDockWidgetPrivate Class Reference
QDockWidgetPrivate Class Reference
#include <qdockwidget_p.h>
Classes
struct DragState
Public Functions
void _q_toggleTopLevel ()
void _q_toggleView (bool)
void endDrag (bool abort=false)
void init ()
void initDrag (const QPoint &pos, bool nca)
bool isAnimating () const
bool mouseDoubleClickEvent (QMouseEvent *event)
bool mouseMoveEvent (QMouseEvent *event)
bool mousePressEvent (QMouseEvent *event)
bool mouseReleaseEvent (QMouseEvent *event)
void moveEvent (QMoveEvent *event)
void nonClientAreaMouseEvent (QMouseEvent *event)
void plug (const QRect &rect)
QDockWidgetPrivate ()
void setWindowState (bool floating, bool unplug=false, const QRect &rect=QRect())
void startDrag ()
void unplug (const QRect &rect)
void updateButtons ()
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
Qt::DockWidgetAreas allowedAreas
QDockWidget::DockWidgetFeatures features
QString fixedWindowTitle
QWidgetResizeHandler * resizer
DragState * state
QAction * toggleViewAction
QRect undockedGeometry
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 72 of file qdockwidget_p.h.
Constructors and Destructors
QDockWidgetPrivate()
QDockWidgetPrivate::QDockWidgetPrivate () inline
Definition at line 86 of file qdockwidget_p.h.
     : QWidgetPrivate(), state(0),
           features(QDockWidget::DockWidgetClosable
                    | QDockWidget::DockWidgetMovable
                    | QDockWidget::DockWidgetFloatable),
           allowedAreas(Qt::AllDockWidgetAreas)
     { }
Functions
_q_toggleTopLevel()
void QDockWidgetPrivate::_q_toggleTopLevel ()
Definition at line 682 of file qdockwidget.cpp.
Referenced by QDockWidgetPrivate().
 {
     Q_Q(QDockWidget);
     q->setFloating(!q->isFloating());
 }
_q_toggleView()
void QDockWidgetPrivate::_q_toggleView (bool b)
Definition at line 640 of file qdockwidget.cpp.
Referenced by QDockWidgetPrivate().
 {
     Q_Q(QDockWidget);
     if (b == q->isHidden()) {
         if (b)
             q->show();
         else
             q->close();
     }
 }
endDrag()
void QDockWidgetPrivate::endDrag (bool abort = false)
Definition at line 747 of file qdockwidget.cpp.
 {
     Q_Q(QDockWidget);
     Q_ASSERT(state != 0);
     q->releaseMouse();
     if (state->dragging) {
         QMainWindowLayout *mwLayout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
         Q_ASSERT(mwLayout != 0);
         if (abort || !mwLayout->plug(state->widgetItem)) {
             if (hasFeature(this, QDockWidget::DockWidgetFloatable)) {
                 if (state->ownWidgetItem)
                     delete state->widgetItem;
                 mwLayout->restore();
 #ifdef Q_WS_X11
                 // get rid of the X11BypassWindowManager window flag and activate the resizer
                 Qt::WindowFlags flags = q->windowFlags();
                 flags &= ~Qt::X11BypassWindowManagerHint;
                 q->setWindowFlags(flags);
                 resizer->setActive(QWidgetResizeHandler::Resize, true);
                 q->show();
 #else
                 QDockWidgetLayout *myLayout
                     = qobject_cast<QDockWidgetLayout*>(layout);
                 resizer->setActive(QWidgetResizeHandler::Resize,
                                     myLayout->widgetForRole(QDockWidgetLayout::TitleBar) != 0);
 #endif
                 undockedGeometry = q->geometry();
                 q->activateWindow();
             } else {
                 mwLayout->revert(state->widgetItem);
             }
         }
     }
     delete state;
     state = 0;
 }
init()
void QDockWidgetPrivate::init ()
Definition at line 578 of file qdockwidget.cpp.
Referenced by QDockWidgetPrivate().
 {
     Q_Q(QDockWidget);
     QDockWidgetLayout *layout = new QDockWidgetLayout(q);
     layout->setSizeConstraint(QLayout::SetMinAndMaxSize);
     QAbstractButton *button = new QDockWidgetTitleButton(q);
     button->setObjectName(QLatin1String("qt_dockwidget_floatbutton"));
     QObject::connect(button, SIGNAL(clicked()), q, SLOT(_q_toggleTopLevel()));
     layout->setWidgetForRole(QDockWidgetLayout::FloatButton, button);
     button = new QDockWidgetTitleButton(q);
     button->setObjectName(QLatin1String("qt_dockwidget_closebutton"));
     QObject::connect(button, SIGNAL(clicked()), q, SLOT(close()));
     layout->setWidgetForRole(QDockWidgetLayout::CloseButton, button);
     resizer = new QWidgetResizeHandler(q);
     resizer->setMovingEnabled(false);
     resizer->setActive(false);
 #ifndef QT_NO_ACTION
     toggleViewAction = new QAction(q);
     toggleViewAction->setCheckable(true);
     fixedWindowTitle = qt_setWindowTitle_helperHelper(q->windowTitle(), q);
     toggleViewAction->setText(fixedWindowTitle);
     QObject::connect(toggleViewAction, SIGNAL(triggered(bool)),
                         q, SLOT(_q_toggleView(bool)));
 #endif
     updateButtons();
 }
initDrag()
void QDockWidgetPrivate::initDrag (const QPoint & pos, bool nca)
Definition at line 688 of file qdockwidget.cpp.
 {
     if (state != 0)
         return;
     Q_Q(QDockWidget);
     QMainWindow *win = qobject_cast<QMainWindow*>(parent);
     Q_ASSERT(win != 0);
     QMainWindowLayout *layout = qt_mainwindow_layout(win);
     Q_ASSERT(layout != 0);
     if (layout->pluggingWidget != 0) // the main window is animating a docking operation
         return;
     state = new QDockWidgetPrivate::DragState;
     state->dragging = false;
     state->widgetItem = 0;
     state->ownWidgetItem = false;
     state->nca = nca;
     state->ctrlDrag = false;
     if (!q->isFloating()) {
         // When dragging the widget out of the docking area,
         // use the middle of title area as pressPos
         QDockWidgetLayout *dwlayout = qobject_cast<QDockWidgetLayout*>(q->layout());
         Q_ASSERT(dwlayout != 0);
         int width = undockedGeometry.isNull() ? q->width() : undockedGeometry.width();
         state->pressPos.setY(dwlayout->titleArea().height() / 2);
         state->pressPos.setX(width / 2);
     } else {
         state->pressPos = pos;
     }
 }
isAnimating()
bool QDockWidgetPrivate::isAnimating () const
Definition at line 787 of file qdockwidget.cpp.
 {
     Q_Q(const QDockWidget);
     QMainWindow *mainWin = qobject_cast<QMainWindow*>(parent);
     if (mainWin == 0)
         return false;
     QMainWindowLayout *mainWinLayout = qt_mainwindow_layout(mainWin);
     if (mainWinLayout == 0)
         return false;
     return (void*)mainWinLayout->pluggingWidget == (void*)q;
 }
mouseDoubleClickEvent()
bool QDockWidgetPrivate::mouseDoubleClickEvent (QMouseEvent * event)
Definition at line 835 of file qdockwidget.cpp.
 {
     QDockWidgetLayout *dwLayout = qobject_cast<QDockWidgetLayout*>(layout);
     if (!dwLayout->nativeWindowDeco()) {
         QRect titleArea = dwLayout->titleArea();
         if (event->button() == Qt::LeftButton && titleArea.contains(event->pos()) &&
             hasFeature(this, QDockWidget::DockWidgetFloatable)) {
             _q_toggleTopLevel();
             return true;
         }
     }
     return false;
 }
mouseMoveEvent()
bool QDockWidgetPrivate::mouseMoveEvent (QMouseEvent * event)
Definition at line 851 of file qdockwidget.cpp.
 {
     bool ret = false;
 #if !defined(QT_NO_MAINWINDOW)
     Q_Q(QDockWidget);
     if (!state)
         return ret;
     QDockWidgetLayout *dwlayout
         = qobject_cast<QDockWidgetLayout *>(layout);
     QMainWindowLayout *mwlayout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
     if (!dwlayout->nativeWindowDeco()) {
         if (!state->dragging
             && mwlayout->pluggingWidget == 0
             && (event->pos() - state->pressPos).manhattanLength()
                 > QApplication::startDragDistance()) {
             startDrag();
 #ifdef Q_OS_WIN
             grabMouseWhileInWindow();
 #else
             q->grabMouse();
 #endif
             ret = true;
         }
     }
     if (state->dragging && !state->nca) {
         QPoint pos = event->globalPos() - state->pressPos;
         q->move(pos);
         if (!state->ctrlDrag)
             mwlayout->hover(state->widgetItem, event->globalPos());
         ret = true;
     }
 #endif // !defined(QT_NO_MAINWINDOW)
     return ret;
 }
mousePressEvent()
bool QDockWidgetPrivate::mousePressEvent (QMouseEvent * event)
Definition at line 802 of file qdockwidget.cpp.
 {
 #if !defined(QT_NO_MAINWINDOW)
     Q_Q(QDockWidget);
     QDockWidgetLayout *dwLayout
         = qobject_cast<QDockWidgetLayout*>(layout);
     if (!dwLayout->nativeWindowDeco()) {
         QRect titleArea = dwLayout->titleArea();
         if (event->button() != Qt::LeftButton ||
             !titleArea.contains(event->pos()) ||
             // check if the tool window is movable... do nothing if it
             // is not (but allow moving if the window is floating)
             (!hasFeature(this, QDockWidget::DockWidgetMovable) && !q->isFloating()) ||
             qobject_cast<QMainWindow*>(parent) == 0 ||
             isAnimating() || state != 0) {
             return false;
         }
         initDrag(event->pos(), false);
         if (state)
             state->ctrlDrag = hasFeature(this, QDockWidget::DockWidgetFloatable) && event->modifiers() & Qt::ControlModifier;
         return true;
     }
 #endif // !defined(QT_NO_MAINWINDOW)
     return false;
 }
mouseReleaseEvent()
bool QDockWidgetPrivate::mouseReleaseEvent (QMouseEvent * event)
Definition at line 892 of file qdockwidget.cpp.
 {
 #if !defined(QT_NO_MAINWINDOW)
     if (event->button() == Qt::LeftButton && state && !state->nca) {
         endDrag();
         return true; //filter out the event
     }
 #endif // !defined(QT_NO_MAINWINDOW)
     return false;
 }
moveEvent()
void QDockWidgetPrivate::moveEvent (QMoveEvent * event)
Definition at line 979 of file qdockwidget.cpp.
 {
     Q_Q(QDockWidget);
     if (state == 0 || !state->dragging || !state->nca || !q->isWindow())
         return;
     // When the native window frame is being dragged, all we get is these mouse
     // move events.
     if (state->ctrlDrag)
         return;
     QMainWindowLayout *layout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
     Q_ASSERT(layout != 0);
     QPoint globalMousePos = event->pos() + state->pressPos;
     layout->hover(state->widgetItem, globalMousePos);
 }
nonClientAreaMouseEvent()
void QDockWidgetPrivate::nonClientAreaMouseEvent (QMouseEvent * event)
Definition at line 905 of file qdockwidget.cpp.
 {
     Q_Q(QDockWidget);
     int fw = q->style()->pixelMetric(QStyle::PM_DockWidgetFrameWidth, 0, q);
     QRect geo = q->geometry();
     QRect titleRect = q->frameGeometry();
 #ifdef Q_WS_MAC
     if ((features & QDockWidget::DockWidgetVerticalTitleBar)) {
         titleRect.setTop(geo.top());
         titleRect.setBottom(geo.bottom());
         titleRect.setRight(geo.left() - 1);
     } else
 #endif
     {
         titleRect.setLeft(geo.left());
         titleRect.setRight(geo.right());
         titleRect.setBottom(geo.top() - 1);
         titleRect.adjust(0, fw, 0, 0);
     }
     switch (event->type()) {
         case QEvent::NonClientAreaMouseButtonPress:
             if (!titleRect.contains(event->globalPos()))
                 break;
             if (state != 0)
                 break;
             if (qobject_cast<QMainWindow*>(parent) == 0)
                 break;
             if (isAnimating())
                 break;
             initDrag(event->pos(), true);
             if (state == 0)
                 break;
 #ifdef Q_OS_WIN
             // On Windows, NCA mouse events don't contain modifier info
             state->ctrlDrag = GetKeyState(VK_CONTROL) & 0x8000;
 #else
             state->ctrlDrag = event->modifiers() & Qt::ControlModifier;
 #endif
             startDrag();
             break;
         case QEvent::NonClientAreaMouseMove:
             if (state == 0 || !state->dragging)
                 break;
             if (state->nca) {
                 endDrag();
             }
 #ifdef Q_OS_MAC
             else { // workaround for lack of mouse-grab on Mac
                 QMainWindowLayout *layout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
                 Q_ASSERT(layout != 0);
                 q->move(event->globalPos() - state->pressPos);
                 if (!state->ctrlDrag)
                     layout->hover(state->widgetItem, event->globalPos());
             }
 #endif
             break;
         case QEvent::NonClientAreaMouseButtonRelease:
 #ifdef Q_OS_MAC
                         if (state)
                                 endDrag();
 #endif
                         break;
         case QEvent::NonClientAreaMouseButtonDblClick:
             _q_toggleTopLevel();
             break;
         default:
             break;
     }
 }
plug()
void QDockWidgetPrivate::plug (const QRect & rect)
Definition at line 1016 of file qdockwidget.cpp.
 {
     setWindowState(false, false, rect);
 }
setWindowState()
void QDockWidgetPrivate::setWindowState (bool floating, bool unplug = false, const QRect & rect = QRect())
Definition at line 1021 of file qdockwidget.cpp.
 {
     Q_Q(QDockWidget);
     if (!floating && parent) {
         QMainWindowLayout *mwlayout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
         if (mwlayout && mwlayout->dockWidgetArea(q) == Qt::NoDockWidgetArea)
             return; // this dockwidget can't be redocked
     }
     bool wasFloating = q->isFloating();
     bool hidden = q->isHidden();
     if (q->isVisible())
         q->hide();
     Qt::WindowFlags flags = floating ? Qt::Tool : Qt::Widget;
     QDockWidgetLayout *dwLayout = qobject_cast<QDockWidgetLayout*>(layout);
     const bool nativeDeco = dwLayout->nativeWindowDeco(floating);
     if (nativeDeco) {
         flags |= Qt::CustomizeWindowHint | Qt::WindowTitleHint;
         if (hasFeature(this, QDockWidget::DockWidgetClosable))
             flags |= Qt::WindowCloseButtonHint;
     } else {
         flags |= Qt::FramelessWindowHint;
     }
     if (unplug)
         flags |= Qt::X11BypassWindowManagerHint;
     q->setWindowFlags(flags);
 #if defined(Q_WS_MAC) && !defined(QT_MAC_USE_COCOA)
     if (floating && nativeDeco && (q->features() & QDockWidget::DockWidgetVerticalTitleBar)) {
         ChangeWindowAttributes(HIViewGetWindow(HIViewRef(q->winId())), kWindowSideTitlebarAttribute, 0);
     }
 #endif
     if (!rect.isNull())
         q->setGeometry(rect);
     updateButtons();
     if (!hidden)
         q->show();
     if (floating != wasFloating) {
         emit q->topLevelChanged(floating);
         if (!floating && parent) {
             QMainWindowLayout *mwlayout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
             if (mwlayout)
                 emit q->dockLocationChanged(mwlayout->dockWidgetArea(q));
         }
     }
     resizer->setActive(QWidgetResizeHandler::Resize, !unplug && floating && !nativeDeco);
 }
startDrag()
void QDockWidgetPrivate::startDrag ()
Definition at line 721 of file qdockwidget.cpp.
 {
     Q_Q(QDockWidget);
     if (state == 0 || state->dragging)
         return;
     QMainWindowLayout *layout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
     Q_ASSERT(layout != 0);
     state->widgetItem = layout->unplug(q);
     if (state->widgetItem == 0) {
         /* I have a QMainWindow parent, but I was never inserted with
             QMainWindow::addDockWidget, so the QMainWindowLayout has no
             widget item for me. :( I have to create it myself, and then
             delete it if I don't get dropped into a dock area. */
         state->widgetItem = new QDockWidgetItem(q);
         state->ownWidgetItem = true;
     }
     if (state->ctrlDrag)
         layout->restore();
     state->dragging = true;
 }
unplug()
void QDockWidgetPrivate::unplug (const QRect & rect)
Definition at line 999 of file qdockwidget.cpp.
 {
     Q_Q(QDockWidget);
     QRect r;
     if (!undockedGeometry.isNull()) {
         r = undockedGeometry;
     } else {
         r = rect;
         r.moveTopLeft(q->mapToGlobal(QPoint(0, 0)));
         QDockWidgetLayout *dwLayout = qobject_cast<QDockWidgetLayout*>(layout);
         if (dwLayout->nativeWindowDeco(true))
             r.adjust(0, dwLayout->titleHeight(), 0, 0);
     }
     setWindowState(true, true, r);
 }
updateButtons()
void QDockWidgetPrivate::updateButtons ()
Definition at line 651 of file qdockwidget.cpp.
Referenced by QDockWidgetPrivate().
 {
     Q_Q(QDockWidget);
     QDockWidgetLayout *dwLayout = qobject_cast<QDockWidgetLayout*>(layout);
     QStyleOptionDockWidget opt;
     q->initStyleOption(&opt);
     bool customTitleBar = dwLayout->widgetForRole(QDockWidgetLayout::TitleBar) != 0;
     bool nativeDeco = dwLayout->nativeWindowDeco();
     bool hideButtons = nativeDeco || customTitleBar;
     bool canClose = hasFeature(this, QDockWidget::DockWidgetClosable);
     bool canFloat = hasFeature(this, QDockWidget::DockWidgetFloatable);
     QAbstractButton *button
         = qobject_cast<QAbstractButton*>(dwLayout->widgetForRole(QDockWidgetLayout::FloatButton));
     button->setIcon(q->style()->standardIcon(QStyle::SP_TitleBarNormalButton, &opt, q));
     button->setVisible(canFloat && !hideButtons);
     button
         = qobject_cast <QAbstractButton*>(dwLayout->widgetForRole(QDockWidgetLayout::CloseButton));
     button->setIcon(q->style()->standardIcon(QStyle::SP_TitleBarCloseButton, &opt, q));
     button->setVisible(canClose && !hideButtons);
     q->setAttribute(Qt::WA_ContentsPropagated,
                     (canFloat || canClose) && !hideButtons);
     layout->invalidate();
 }
Properties
allowedAreas
Qt::DockWidgetAreas QDockWidgetPrivate::allowedAreas
Definition at line 102 of file qdockwidget_p.h.
features
QDockWidget::DockWidgetFeatures QDockWidgetPrivate::features
Definition at line 101 of file qdockwidget_p.h.
Referenced by hasFeature().
fixedWindowTitle
QString QDockWidgetPrivate::fixedWindowTitle
Definition at line 112 of file qdockwidget_p.h.
resizer
QWidgetResizeHandler* QDockWidgetPrivate::resizer
Definition at line 104 of file qdockwidget_p.h.
state
DragState* QDockWidgetPrivate::state
Definition at line 99 of file qdockwidget_p.h.
toggleViewAction
QAction* QDockWidgetPrivate::toggleViewAction
Definition at line 107 of file qdockwidget_p.h.
undockedGeometry
QRect QDockWidgetPrivate::undockedGeometry
Definition at line 111 of file qdockwidget_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qdockwidget_p.h
/src/gui/widgets/qdockwidget.cpp