Qt 4.8: QWaylandReadbackGlxIntegration Class Reference
QWaylandReadbackGlxIntegration Class Reference
#include <qwaylandreadbackglxintegration.h>
Public Functions
QWaylandWindow * createEglWindow (QWidget *widget)
void initialize ()
QWaylandReadbackGlxIntegration (QWaylandDisplay *waylandDispaly)
Window rootWindow () const
int screen () const
QWaylandDisplay * waylandDisplay () const
Display * xDisplay () const
~QWaylandReadbackGlxIntegration ()
Public Functions inherited from QWaylandGLIntegration
QWaylandGLIntegration ()
virtual ~QWaylandGLIntegration ()
Properties
Display * mDisplay
Window mRootWindow
int mScreen
QWaylandDisplay * mWaylandDisplay
Additional Inherited Members
Static Public Functions inherited from QWaylandGLIntegration
static QWaylandGLIntegration * createGLIntegration (QWaylandDisplay *waylandDisplay)
Detailed Description
Definition at line 55 of file qwaylandreadbackglxintegration.h.
Constructors and Destructors
QWaylandReadbackGlxIntegration()
QWaylandReadbackGlxIntegration::QWaylandReadbackGlxIntegration (QWaylandDisplay * waylandDispaly)
Definition at line 48 of file qwaylandreadbackglxintegration.cpp.
Referenced by createEglWindow().
     : QWaylandGLIntegration()
     , mWaylandDisplay(waylandDispaly)
 {
     qDebug() << "Using Readback-GLX";
     char *display_name = getenv("DISPLAY");
     mDisplay = XOpenDisplay(display_name);
     mScreen = XDefaultScreen(mDisplay);
     mRootWindow = XDefaultRootWindow(mDisplay);
     XSync(mDisplay, False);
 }
~QWaylandReadbackGlxIntegration()
QWaylandReadbackGlxIntegration::~QWaylandReadbackGlxIntegration ()
Definition at line 60 of file qwaylandreadbackglxintegration.cpp.
 {
     XCloseDisplay(mDisplay);
 }
Functions
createEglWindow()
QWaylandWindow * QWaylandReadbackGlxIntegration::createEglWindow (QWidget * widget) virtual
Implements QWaylandGLIntegration.
Definition at line 69 of file qwaylandreadbackglxintegration.cpp.
 {
     return new QWaylandReadbackGlxWindow(widget,this);
 }
initialize()
void QWaylandReadbackGlxIntegration::initialize () virtual
Implements QWaylandGLIntegration.
Definition at line 65 of file qwaylandreadbackglxintegration.cpp.
 {
 }
rootWindow()
Window QWaylandReadbackGlxIntegration::rootWindow () const
Definition at line 89 of file qwaylandreadbackglxintegration.cpp.
Referenced by QWaylandReadbackGlxContext::geometryChanged().
 {
     return mRootWindow;
 }
screen()
int QWaylandReadbackGlxIntegration::screen () const
Definition at line 84 of file qwaylandreadbackglxintegration.cpp.
Referenced by QWaylandReadbackGlxContext::geometryChanged().
 {
     return mScreen;
 }
waylandDisplay()
QWaylandDisplay * QWaylandReadbackGlxIntegration::waylandDisplay () const
Definition at line 94 of file qwaylandreadbackglxintegration.cpp.
Referenced by createEglWindow(), and QWaylandReadbackGlxContext::geometryChanged().
 {
     return mWaylandDisplay;
 }
xDisplay()
Display * QWaylandReadbackGlxIntegration::xDisplay () const
Definition at line 79 of file qwaylandreadbackglxintegration.cpp.
Referenced by QWaylandReadbackGlxContext::geometryChanged(), QWaylandReadbackGlxContext::makeCurrent(), QWaylandReadbackGlxContext::platformWindowFormat(), and QWaylandReadbackGlxContext::QWaylandReadbackGlxContext().
 {
     return mDisplay;
 }
Properties
mDisplay
Display* QWaylandReadbackGlxIntegration::mDisplay private
Definition at line 74 of file qwaylandreadbackglxintegration.h.
Referenced by QWaylandReadbackGlxIntegration(), xDisplay(), and ~QWaylandReadbackGlxIntegration().
mRootWindow
Window QWaylandReadbackGlxIntegration::mRootWindow private
Definition at line 76 of file qwaylandreadbackglxintegration.h.
Referenced by QWaylandReadbackGlxIntegration(), and rootWindow().
mScreen
int QWaylandReadbackGlxIntegration::mScreen private
Definition at line 75 of file qwaylandreadbackglxintegration.h.
Referenced by QWaylandReadbackGlxIntegration(), and screen().
mWaylandDisplay
QWaylandDisplay* QWaylandReadbackGlxIntegration::mWaylandDisplay private
Definition at line 72 of file qwaylandreadbackglxintegration.h.
Referenced by waylandDisplay().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/gl_integration/readback_glx/qwaylandreadbackglxintegration.h
/src/plugins/platforms/wayland/gl_integration/readback_glx/qwaylandreadbackglxintegration.cpp