Qt 4.8: QPatternist::AnyURI Class Reference
QPatternist::AnyURI Class Reference
A value of type xs:anyURI.
#include <qanyuri_p.h>
Public Types
typedef QExplicitlySharedDataPointer< AnyURI > Ptr
Public Types inherited from QPatternist::AtomicString
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
QUrl toQUrl () const
Returns this xs:anyURI value in a QUrl.
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicString
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual QString stringValue () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
template<const ReportContext::ErrorCode code, typename TReportContext >
static AnyURI::Ptr fromLexical (const QString &value, const TReportContext &context, const SourceLocationReflection *const r)
Constructs a xs:anyURI value from the lexical representation value.
static AnyURI::Ptr fromLexical (const QString &value)
static AnyURI::Ptr fromValue (const QString &value)
static AnyURI::Ptr fromValue (const QUrl &uri)
static bool isValid (const QString &candidate)
Return true if candidate is a valid xs:anyURI, otherwise false.
static AnyURI::Ptr resolveURI (const QString &relative, const QString &base)
template<const ReportContext::ErrorCode code, typename TReportContext >
static QUrl toQUrl (const QString &value, const TReportContext &context, const SourceLocationReflection *const r, bool *const isValid=0, const bool issueError=true)
Treates value as a lexical representation of xs:anyURI but returns the value instance as a QUrl.
Static Public Functions inherited from QPatternist::AtomicString
static AtomicString::Ptr fromValue (const QString &value)
static AtomicString::Ptr fromValue (const QUrl &value)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
AnyURI (const QString &value)
Protected Functions inherited from QPatternist::AtomicString
AtomicString (const QString &value)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Variables inherited from QPatternist::AtomicString
const QString m_value
Detailed Description
A value of type xs:anyURI.
Due to bugs in QUrl and slight differences in behavior and interpretation, QUrl can never be used directly for dealing with URIs, values of type xs:anyURI. Therefore, it's important to use the functionality this class provides, such as the functions toQUrl(), fromLexical(), isValid(), and resolveURI().
See also
QUrl
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 82 of file qanyuri_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<AnyURI> QPatternist::AnyURI::Ptr
Definition at line 85 of file qanyuri_p.h.
Constructors and Destructors
AnyURI()
AnyURI::AnyURI (const QString & value) protected
Definition at line 52 of file qanyuri.cpp.
Referenced by fromLexical(), and fromValue().
                                : AtomicString(s)
 {
 }
Functions
fromLexical() [1/2]
template<const ReportContext::ErrorCode code, typename TReportContext > static AnyURI::Ptr QPatternist::AnyURI::fromLexical (const QString & value, const TReportContext & context, const SourceLocationReflection *const r) inline static
Constructs a xs:anyURI value from the lexical representation value.
If value is not a valid lexical representation of xs:anyURI, an error is issued via context.
Definition at line 153 of file qanyuri_p.h.
Referenced by QPatternist::ToAnyURICaster::castFrom(), isValidUri(), QPatternist::XsdSchemaParser::parseAppInfo(), QPatternist::XsdSchemaParser::parseDocumentation(), QPatternist::XsdSchemaParser::parseNotation(), and QPatternist::XsdSchemaParser::readXPathExpression().
         {
             return AnyURI::Ptr(new AnyURI(toQUrl<code>(value, context, r).toString()));
         }
fromLexical() [2/2]
AnyURI::Ptr AnyURI::fromLexical (const QString & value) static
If value is not a valid lexical representation for xs:anyURI, a ValidationError is returned.
Definition at line 78 of file qanyuri.cpp.
 {
     bool isValid;
     /* The error code doesn't matter, because we never raise error. */
     const QUrl retval(toQUrl<ReportContext::FORG0001>(value,
                                                       DynamicContext::Ptr(),
                                                       0,
                                                       &isValid,
                                                       false));
     if(isValid)
         return fromValue(retval);
     else
         return ValidationError::createError();
 }
fromValue() [1/2]
AnyURI::Ptr AnyURI::fromValue (const QString & value) static
Creates an instance representing value.
Note
value must be a valid xs:anyURI. If it is of interest to construct from a lexical representation, use fromLexical().
Definition at line 56 of file qanyuri.cpp.
Referenced by QPatternist::ResolveURIFN::evaluateSingleton(), QPatternist::UnparsedEntityURIFN::evaluateSingleton(), QPatternist::NamespaceURIFN::evaluateSingleton(), QPatternist::BaseURIFN::evaluateSingleton(), QPatternist::NamespaceURIFromQNameFN::evaluateSingleton(), QPatternist::DocumentURIFN::evaluateSingleton(), QPatternist::NamespaceURIForPrefixFN::evaluateSingleton(), fromLexical(), QPatternist::VariableLoader::itemForName(), resolveURI(), QPatternist::ResolveURIFN::typeCheck(), and QPatternist::StaticBaseURIFN::typeCheck().
 {
     return AnyURI::Ptr(new AnyURI(value));
 }
fromValue() [2/2]
AnyURI::Ptr AnyURI::fromValue (const QUrl & uri) static
Definition at line 61 of file qanyuri.cpp.
 {
     return AnyURI::Ptr(new AnyURI(uri.toString()));
 }
isValid()
bool AnyURI::isValid (const QString & candidate) static
Return true if candidate is a valid xs:anyURI, otherwise false.
Definition at line 93 of file qanyuri.cpp.
Referenced by fromLexical(), toQUrl(), and QPatternist::yyparse().
 {
     bool isOk = false;
     /* The error code doesn't matter, because we never raise error. */
     toQUrl<ReportContext::FORG0001>(candidate,
                                     ReportContext::Ptr(),
                                     0,
                                     &isOk,
                                     false);
     return isOk;
 }
resolveURI()
AnyURI::Ptr AnyURI::resolveURI (const QString & relative, const QString & base) static
Creates an AnyURI instance representing an absolute URI which is created from resolving relative against base.
This function must be compatible with the resolution semantics specified for fn:resolve-uri. In fact, the implementation of fn:resolve-uri, ResourceURIFN, relies on this function.
See also
RFC 3986 - Uniform Resource Identifier (URI): Generic Syntax
XQuery 1.0 and XPath 2.0 Functions and Operators, 8.1 fn:resolve-uri
Definition at line 66 of file qanyuri.cpp.
Referenced by fromLexical().
 {
     const QUrl urlBase(base);
     return AnyURI::fromValue(urlBase.resolved(relative).toString());
 }
toQUrl() [1/2]
template<const ReportContext::ErrorCode code, typename TReportContext > static QUrl QPatternist::AnyURI::toQUrl (const QString & value, const TReportContext & context, const SourceLocationReflection *const r, bool *const isValid = 0, const bool issueError = true) inline static
Treates value as a lexical representation of xs:anyURI but returns the value instance as a QUrl.
If value is not a valid lexical representation of xs:anyURI, an error is issued via context.
If isValid is passed, no error is raised and it is instead set appropriately.
Definition at line 108 of file qanyuri_p.h.
         {
             /* QUrl doesn't flag ":/..." so we workaround it. */
             const QString simplified(value.simplified());
             const QUrl uri(simplified, QUrl::StrictMode);
             if(uri.isEmpty() || (uri.isValid() && (!simplified.startsWith(QLatin1Char(':')) || !uri.isRelative())))
             {
                 if(isValid)
                     *isValid = true;
                 return uri;
             }
             else
             {
                 if(isValid)
                     *isValid = false;
                 if(issueError)
                 {
                     context->error(QtXmlPatterns::tr("%1 is not a valid value of type %2.").arg(formatURI(value), formatType(context->namePool(), BuiltinTypes::xsAnyURI)),
                                    code, r);
                 }
                 return QUrl();
             }
         }
toQUrl() [2/2]
QUrl QPatternist::AnyURI::toQUrl () const inline
Returns this xs:anyURI value in a QUrl.
Definition at line 187 of file qanyuri_p.h.
         {
             Q_ASSERT_X(QUrl(m_value).isValid(), Q_FUNC_INFO,
                        qPrintable(QString::fromLatin1("%1 is apparently not ok for QUrl.").arg(m_value)));
             return QUrl(m_value);
         }
type()
ItemType::Ptr AnyURI::type () const virtual
Reimplemented from QPatternist::AtomicString.
Definition at line 73 of file qanyuri.cpp.
Referenced by fromLexical().
 {
     return BuiltinTypes::xsAnyURI;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 194 of file qanyuri_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qanyuri_p.h
/src/xmlpatterns/data/qanyuri.cpp