Qt 4.8: QDeclarativeSystemPalette Class Reference
QDeclarativeSystemPalette Class Reference
#include <qdeclarativesystempalette_p.h>
Public Types
enum ColorGroup { Active = QPalette::Active, Inactive = QPalette::Inactive, Disabled = QPalette::Disabled }
Signals
void paletteChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QColor alternateBase () const
QColor base () const
QColor button () const
QColor buttonText () const
QDeclarativeSystemPalette::ColorGroup colorGroup () const
QColor dark () const
QColor highlight () const
QColor highlightedText () const
QColor light () const
QColor mid () const
QColor midlight () const
QDeclarativeSystemPalette (QObject *parent=0)
void setColorGroup (QDeclarativeSystemPalette::ColorGroup)
QColor shadow () const
QColor text () const
QColor window () const
QColor windowText () const
~QDeclarativeSystemPalette ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
bool event (QEvent *event)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
bool eventFilter (QObject *watched, QEvent *event)
Filters events if this object has been installed as an event filter for the watched object.
Properties
QColor alternateBase
QColor base
QColor button
QColor buttonText
QDeclarativeSystemPalette::ColorGroup colorGroup
QColor dark
QColor highlight
QColor highlightedText
QColor light
QColor mid
QColor midlight
QColor shadow
QColor text
QColor window
QColor windowText
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 57 of file qdeclarativesystempalette_p.h.
Enumerations
ColorGroup
enum QDeclarativeSystemPalette::ColorGroup
Enumerator
Active
Inactive
Disabled
Definition at line 83 of file qdeclarativesystempalette_p.h.
 { Active = QPalette::Active, Inactive = QPalette::Inactive, Disabled = QPalette::Disabled };
Constructors and Destructors
QDeclarativeSystemPalette()
QDeclarativeSystemPalette::QDeclarativeSystemPalette (QObject * parent = 0)
Definition at line 86 of file qdeclarativesystempalette.cpp.
     : QObject(*(new QDeclarativeSystemPalettePrivate), parent)
 {
     Q_D(QDeclarativeSystemPalette);
     d->palette = QApplication::palette();
     d->group = QPalette::Active;
     qApp->installEventFilter(this);
 }
~QDeclarativeSystemPalette()
QDeclarativeSystemPalette::~QDeclarativeSystemPalette ()
Definition at line 95 of file qdeclarativesystempalette.cpp.
 {
 }
Functions
alternateBase()
QColor QDeclarativeSystemPalette::alternateBase () const
Referenced by ~QDeclarativeSystemPalette().
base()
QColor QDeclarativeSystemPalette::base () const
Referenced by ~QDeclarativeSystemPalette().
button()
QColor QDeclarativeSystemPalette::button () const
Referenced by ~QDeclarativeSystemPalette().
buttonText()
QColor QDeclarativeSystemPalette::buttonText () const
Referenced by ~QDeclarativeSystemPalette().
colorGroup()
QDeclarativeSystemPalette::ColorGroup QDeclarativeSystemPalette::colorGroup () const
Referenced by ~QDeclarativeSystemPalette().
dark()
QColor QDeclarativeSystemPalette::dark () const
Referenced by ~QDeclarativeSystemPalette().
event()
bool QDeclarativeSystemPalette::event (QEvent * e) private virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 349 of file qdeclarativesystempalette.cpp.
 {
     Q_D(QDeclarativeSystemPalette);
     if (event->type() == QEvent::ApplicationPaletteChange) {
         d->palette = QApplication::palette();
         emit paletteChanged();
         return true;
     }
     return QObject::event(event);
 }
eventFilter()
bool QDeclarativeSystemPalette::eventFilter (QObject * , QEvent *) private virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 338 of file qdeclarativesystempalette.cpp.
 {
     if (watched == qApp) {
         if (event->type() == QEvent::ApplicationPaletteChange) {
             QApplication::postEvent(this, new QEvent(QEvent::ApplicationPaletteChange));
             return false;
         }
     }
     return QObject::eventFilter(watched, event);
 }
highlight()
QColor QDeclarativeSystemPalette::highlight () const
Referenced by ~QDeclarativeSystemPalette().
highlightedText()
QColor QDeclarativeSystemPalette::highlightedText () const
Referenced by ~QDeclarativeSystemPalette().
light()
QColor QDeclarativeSystemPalette::light () const
Referenced by ~QDeclarativeSystemPalette().
mid()
QColor QDeclarativeSystemPalette::mid () const
Referenced by ~QDeclarativeSystemPalette().
midlight()
QColor QDeclarativeSystemPalette::midlight () const
Referenced by ~QDeclarativeSystemPalette().
paletteChanged
void QDeclarativeSystemPalette::paletteChanged () signal
Referenced by event(), and setColorGroup().
setColorGroup()
void QDeclarativeSystemPalette::setColorGroup (QDeclarativeSystemPalette::ColorGroup colorGroup)
Definition at line 331 of file qdeclarativesystempalette.cpp.
 {
     Q_D(QDeclarativeSystemPalette);
     d->group = (QPalette::ColorGroup)colorGroup;
     emit paletteChanged();
 }
shadow()
QColor QDeclarativeSystemPalette::shadow () const
Referenced by ~QDeclarativeSystemPalette().
text()
QColor QDeclarativeSystemPalette::text () const
Referenced by ~QDeclarativeSystemPalette().
window()
QColor QDeclarativeSystemPalette::window () const
Referenced by ~QDeclarativeSystemPalette().
windowText()
QColor QDeclarativeSystemPalette::windowText () const
Referenced by ~QDeclarativeSystemPalette().
Properties
alternateBase
QColor QDeclarativeSystemPalette::alternateBase private
Definition at line 68 of file qdeclarativesystempalette_p.h.
base
QColor QDeclarativeSystemPalette::base private
Definition at line 66 of file qdeclarativesystempalette_p.h.
button
QColor QDeclarativeSystemPalette::button private
Definition at line 69 of file qdeclarativesystempalette_p.h.
buttonText
QColor QDeclarativeSystemPalette::buttonText private
Definition at line 70 of file qdeclarativesystempalette_p.h.
colorGroup
QDeclarativeSystemPalette::ColorGroup QDeclarativeSystemPalette::colorGroup private
Definition at line 63 of file qdeclarativesystempalette_p.h.
dark
QColor QDeclarativeSystemPalette::dark private
Definition at line 73 of file qdeclarativesystempalette_p.h.
highlight
QColor QDeclarativeSystemPalette::highlight private
Definition at line 76 of file qdeclarativesystempalette_p.h.
highlightedText
QColor QDeclarativeSystemPalette::highlightedText private
Definition at line 77 of file qdeclarativesystempalette_p.h.
light
QColor QDeclarativeSystemPalette::light private
Definition at line 71 of file qdeclarativesystempalette_p.h.
mid
QColor QDeclarativeSystemPalette::mid private
Definition at line 74 of file qdeclarativesystempalette_p.h.
midlight
QColor QDeclarativeSystemPalette::midlight private
Definition at line 72 of file qdeclarativesystempalette_p.h.
shadow
QColor QDeclarativeSystemPalette::shadow private
Definition at line 75 of file qdeclarativesystempalette_p.h.
text
QColor QDeclarativeSystemPalette::text private
Definition at line 67 of file qdeclarativesystempalette_p.h.
window
QColor QDeclarativeSystemPalette::window private
Definition at line 64 of file qdeclarativesystempalette_p.h.
windowText
QColor QDeclarativeSystemPalette::windowText private
Definition at line 65 of file qdeclarativesystempalette_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativesystempalette_p.h
/src/declarative/util/qdeclarativesystempalette.cpp