Qt 4.8: QPatternist::YearMonthDuration Class Reference
QPatternist::YearMonthDuration Class Reference
Implements the value instance of the xs:yearMonthDuration type.
#include <qyearmonthduration_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AbstractDuration
typedef QExplicitlySharedDataPointer< AbstractDuration > Ptr
typedef qint64 Value
The amount in milli seconds.
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual DayCountProperty days () const
virtual Item fromValue (const Value val) const
virtual HourProperty hours () const
virtual MinuteProperty minutes () const
virtual MonthProperty months () const
virtual MSecondProperty mseconds () const
virtual SecondProperty seconds () const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
virtual Value value () const
virtual YearProperty years () const
Public Functions inherited from QPatternist::AbstractDuration
bool isPositive () const
bool operator== (const AbstractDuration &other) const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static YearMonthDuration::Ptr fromComponents (const bool isPositive, const YearProperty years, const MonthProperty months)
static YearMonthDuration::Ptr fromLexical (const QString &string)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
YearMonthDuration (const bool isPositive, const YearProperty years, const MonthProperty months)
Protected Functions inherited from QPatternist::AbstractDuration
AbstractDuration (const bool isPos)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Properties
const MonthProperty m_months
const YearProperty m_years
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::AbstractDuration
static AtomicValue::Ptr create (const CaptureTable &captTable, const QString &lexical, bool *isPositive, YearProperty *years, MonthProperty *months, DayCountProperty *days, HourProperty *hours, MinuteProperty *minutes, SecondProperty *seconds, MSecondProperty *mseconds)
static QString serializeMSeconds (const MSecondProperty mseconds)
Protected Variables inherited from QPatternist::AbstractDuration
const bool m_isPositive
Detailed Description
Implements the value instance of the xs:yearMonthDuration type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 69 of file qyearmonthduration_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::YearMonthDuration::Ptr
Definition at line 72 of file qyearmonthduration_p.h.
Constructors and Destructors
YearMonthDuration()
YearMonthDuration::YearMonthDuration (const bool isPositive, const YearProperty years, const MonthProperty months) protected
Definition at line 51 of file qyearmonthduration.cpp.
Referenced by fromComponents(), and fromLexical().
                                                                   : AbstractDuration(isPositiveP),
                                                                     m_years(yearsP),
                                                                     m_months(monthsP)
 {
     Q_ASSERT(monthsP < 32 && monthsP > -32);
 }
Functions
days()
DayCountProperty YearMonthDuration::days () const virtual
Returns
always 0.
Implements QPatternist::AbstractDuration.
Definition at line 160 of file qyearmonthduration.cpp.
 {
     return 0;
 }
fromComponents()
YearMonthDuration::Ptr YearMonthDuration::fromComponents (const bool isPositive, const YearProperty years, const MonthProperty months) static
Definition at line 84 of file qyearmonthduration.cpp.
Referenced by QPatternist::AbstractDurationToYearMonthDurationCaster::castFrom(), and fromValue().
 {
     return YearMonthDuration::Ptr(new YearMonthDuration(isPositive, years, months));
 }
fromLexical()
YearMonthDuration::Ptr YearMonthDuration::fromLexical (const QString & string) static
Creates an instance from the lexical representation string.
Definition at line 60 of file qyearmonthduration.cpp.
Referenced by QPatternist::StringToYearMonthDurationCaster::castFrom().
 {
     static const CaptureTable captureTable(
         /* The extra paranthesis is a build fix for GCC 3.3. */
         (QRegExp(QLatin1String(
                 "^\\s*"         /* Any preceding whitespace. */
                 "(-)?"          /* Sign, if any. */
                 "P"             /* Delimiter. */
                 "(?:(\\d+)Y)?"  /* The years part. */
                 "(?:(\\d+)M)?"  /* The months part. */
                 "\\s*$"         /* Any terminating whitespace. */))),
         2,                      /* yearP. */
         3                       /* monthP. */);
     YearProperty years = 0;
     MonthProperty months = 0;
     bool isPos;
     const AtomicValue::Ptr err(create(captureTable, lexical, &isPos, &years,
                                       &months, 0, 0, 0, 0, 0));
     return err ? err : YearMonthDuration::Ptr(new YearMonthDuration(isPos, years, months));
 }
fromValue()
Item YearMonthDuration::fromValue (const Value val) const virtual
If val is zero, is CommonValues::YearMonthDurationZero returned.
Implements QPatternist::AbstractDuration.
Definition at line 132 of file qyearmonthduration.cpp.
 {
     if(val == 0)
         return toItem(CommonValues::YearMonthDurationZero);
     else
     {
         const Value absValue = qAbs(val);
         return toItem(YearMonthDuration::fromComponents(val >= 0,
                                                         absValue / 12,
                                                         absValue % 12));
     }
 }
hours()
HourProperty YearMonthDuration::hours () const virtual
Returns
always 0.
Implements QPatternist::AbstractDuration.
Definition at line 165 of file qyearmonthduration.cpp.
 {
     return 0;
 }
minutes()
MinuteProperty YearMonthDuration::minutes () const virtual
Returns
always 0.
Implements QPatternist::AbstractDuration.
Definition at line 170 of file qyearmonthduration.cpp.
 {
     return 0;
 }
months()
MonthProperty YearMonthDuration::months () const virtual
Returns
the months component. Always positive.
Implements QPatternist::AbstractDuration.
Definition at line 155 of file qyearmonthduration.cpp.
Referenced by fromLexical().
 {
     return m_months;
 }
mseconds()
MSecondProperty YearMonthDuration::mseconds () const virtual
Returns
always 0.
Implements QPatternist::AbstractDuration.
Definition at line 180 of file qyearmonthduration.cpp.
 {
     return 0;
 }
seconds()
SecondProperty YearMonthDuration::seconds () const virtual
Returns
always 0.
Implements QPatternist::AbstractDuration.
Definition at line 175 of file qyearmonthduration.cpp.
 {
     return 0;
 }
stringValue()
QString YearMonthDuration::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 91 of file qyearmonthduration.cpp.
 {
     QString retval;
     if(!m_isPositive)
         retval.append(QLatin1Char('-'));
     retval.append(QLatin1Char('P'));
     /* When years == 0 and months == 0, we get "P0M", which
      * is the correct canonical form. */
     if(m_years)
     {
         retval.append(QString::number(m_years));
         retval.append(QLatin1Char('Y'));
         if(m_months)
         {
             retval.append(QString::number(m_months));
             retval.append(QLatin1Char('M'));
         }
     }
     else
     {
         if(m_months)
         {
             retval.append(QString::number(m_months));
             retval.append(QLatin1Char('M'));
         }
         else
             return QLatin1String("P0M"); /* Ensure the canonical form. */
     }
     return retval;
 }
type()
ItemType::Ptr YearMonthDuration::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 145 of file qyearmonthduration.cpp.
 {
     return BuiltinTypes::xsYearMonthDuration;
 }
value()
AbstractDuration::Value YearMonthDuration::value () const virtual
Returns
the value of this xs:yearMonthDuration in months.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 10.3.2.2 Calculating the value of a xs:dayTimeDuration from the lexical representation
Implements QPatternist::AbstractDuration.
Definition at line 127 of file qyearmonthduration.cpp.
 {
     return (m_years * 12 + m_months) * (m_isPositive ? 1 : -1);
 }
years()
YearProperty YearMonthDuration::years () const virtual
Returns
the years component. Always positive.
Implements QPatternist::AbstractDuration.
Definition at line 150 of file qyearmonthduration.cpp.
Referenced by fromLexical().
 {
     return m_years;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 135 of file qyearmonthduration_p.h.
Properties
m_months
const MonthProperty QPatternist::YearMonthDuration::m_months private
Definition at line 143 of file qyearmonthduration_p.h.
Referenced by months(), stringValue(), and value().
m_years
const YearProperty QPatternist::YearMonthDuration::m_years private
Definition at line 142 of file qyearmonthduration_p.h.
Referenced by stringValue(), value(), and years().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qyearmonthduration_p.h
/src/xmlpatterns/data/qyearmonthduration.cpp