Qt 4.8: QGesture Class Reference
QGesture Class Reference
The QGesture class represents a gesture, containing properties that describe the corresponding user input.
#include <qgesture.h>
Public Types
enum GestureCancelPolicy { CancelNone = 0, CancelAllInContext }
This enum describes how accepting a gesture can cancel other gestures automatically.
Public Functions
GestureCancelPolicy gestureCancelPolicy () const
Qt::GestureType gestureType () const
bool hasHotSpot () const
QPointF hotSpot () const
QGesture (QObject *parent=0)
Constructs a new gesture object with the given parent.
void setGestureCancelPolicy (GestureCancelPolicy policy)
void setHotSpot (const QPointF &value)
Qt::GestureState state () const
void unsetHotSpot ()
~QGesture ()
Destroys the gesture object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QGesture (QGesturePrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
QGesture::GestureCancelPolicy gestureCancelPolicy
the policy for deciding what happens on accepting a gesture
Qt::GestureType gestureType
the type of the gesture
bool hasHotSpot
whether the gesture has a hot-spot
QPointF hotSpot
The point that is used to find the receiver for the gesture event.
Qt::GestureState state
the current state of the gesture
Friends
class QGestureEvent
class QGestureManager
class QGestureRecognizer
class QGraphicsScenePrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGesture class represents a gesture, containing properties that describe the corresponding user input.
Since
4.6
Gesture objects are not constructed directly by developers. They are created by the QGestureRecognizer object that is registered with the application; see QGestureRecognizer::registerRecognizer().
For an overview of gesture handling in Qt and information on using gestures in your applications, see the Gestures Programming document.
Gesture Properties
The class has a list of properties that can be queried by the user to get some gesture-specific arguments. For example, the pinch gesture has a scale factor that is exposed as a property.
Developers of custom gesture recognizers can add additional properties in order to provide additional information about a gesture. This can be done by adding new dynamic properties to a QGesture object, or by subclassing the QGesture class (or one of its subclasses).
Lifecycle of a Gesture Object
A QGesture instance is implicitly created when needed and is owned by Qt. Developers should never destroy them or store them for later use as Qt may destroy particular instances of them and create new ones to replace them.
The registered gesture recognizer monitors the input events for the target object via its QGestureRecognizer::recognize() function, updating the properties of the gesture object as required.
The gesture object may be delivered to the target object in a QGestureEvent if the corresponding gesture is active or has just been canceled. Each event that is delivered contains a list of gesture objects, since support for more than one gesture may be enabled for the target object. Due to the way events are handled in Qt, gesture events may be filtered by other objects.
See also
QGestureEvent, QGestureRecognizer
Definition at line 64 of file qgesture.h.
Enumerations
GestureCancelPolicy
enum QGesture::GestureCancelPolicy
This enum describes how accepting a gesture can cancel other gestures automatically.
CancelNone On accepting this gesture no other gestures will be affected.
CancelAllInContext On accepting this gesture all gestures that are active in the context (respecting the Qt::GestureFlag that were specified when subscribed to the gesture) will be cancelled.
Enumerator
CancelNone
CancelAllInContext
Definition at line 88 of file qgesture.h.
{
         CancelNone = 0,
         CancelAllInContext
     };
Constructors and Destructors
QGesture() [1/2]
QGesture::QGesture (QObject * parent = 0) explicit
Constructs a new gesture object with the given parent.
QGesture objects are created by gesture recognizers in the QGestureRecognizer::create() function.
Definition at line 104 of file qgesture.cpp.
     : QObject(*new QGesturePrivate, parent)
 {
     d_func()->gestureType = Qt::CustomGesture;
 }
~QGesture()
QGesture::~QGesture ()
Destroys the gesture object.
Definition at line 121 of file qgesture.cpp.
 {
 }
QGesture() [2/2]
QGesture::QGesture (QGesturePrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 113 of file qgesture.cpp.
     : QObject(dd, parent)
 {
 }
Functions
gestureCancelPolicy()
GestureCancelPolicy QGesture::gestureCancelPolicy () const
Referenced by setGestureCancelPolicy().
gestureType()
Qt::GestureType QGesture::gestureType () const
Referenced by ~QGesture().
hasHotSpot()
bool QGesture::hasHotSpot () const
Referenced by setHotSpot().
hotSpot()
QPointF QGesture::hotSpot () const
Referenced by ~QGesture().
setGestureCancelPolicy()
void QGesture::setGestureCancelPolicy (GestureCancelPolicy policy)
Definition at line 226 of file qgesture.cpp.
Referenced by QGestureManager::recycle().
 {
     Q_D(QGesture);
     d->gestureCancelPolicy = static_cast<uint>(policy);
 }
setHotSpot()
void QGesture::setHotSpot (const QPointF & value)
Definition at line 180 of file qgesture.cpp.
Referenced by QPanGestureRecognizer::recognize(), QMacSwipeGestureRecognizer::recognize(), QMacPinchGestureRecognizer::recognize(), QTapGestureRecognizer::recognize(), QTapAndHoldGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     Q_D(QGesture);
     d->hotSpot = value;
     d->isHotSpotSet = true;
 }
state()
Qt::GestureState QGesture::state () const
Referenced by QPlainTextEdit::event(), QPanGestureRecognizer::recognize(), QWinNativePanGestureRecognizer::recognize(), QPinchGestureRecognizer::recognize(), QSwipeGestureRecognizer::recognize(), QTapGestureRecognizer::recognize(), and ~QGesture().
unsetHotSpot()
void QGesture::unsetHotSpot ()
Definition at line 192 of file qgesture.cpp.
 {
     d_func()->isHotSpotSet = false;
 }
Friends and Related Functions
QGestureEvent
friend class QGestureEvent friend
Definition at line 100 of file qgesture.h.
QGestureManager
friend class QGestureManager friend
Definition at line 102 of file qgesture.h.
QGestureRecognizer
friend class QGestureRecognizer friend
Definition at line 101 of file qgesture.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 103 of file qgesture.h.
Properties
gestureCancelPolicy
QGesture::GestureCancelPolicy QGesture::gestureCancelPolicy private
the policy for deciding what happens on accepting a gesture
On accepting one gesture Qt can automatically cancel other gestures that belong to other targets. The policy is normally set to not cancel any other gestures and can be set to cancel all active gestures in the context. For example for all child widgets.
Definition at line 71 of file qgesture.h.
Referenced by QGestureManager::filterEventThroughContexts(), and QGraphicsScenePrivate::gestureEventHandler().
gestureType
Qt::GestureType QGesture::gestureType private
the type of the gesture
Definition at line 70 of file qgesture.h.
Referenced by QGestureEvent::accept(), QGraphicsScenePrivate::cancelGesturesForChildren(), QGestureManager::deliverEvents(), QGestureManager::filterEvent(), QGestureEvent::gesture(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsScenePrivate::gestureTargetsAtHotSpots(), QGestureManager::getGestureTargets(), QGestureManager::getState(), QGestureEvent::ignore(), QGestureEvent::isAccepted(), QApplication::notify(), QPanGesture::QPanGesture(), QPinchGesture::QPinchGesture(), QSwipeGesture::QSwipeGesture(), QTapAndHoldGesture::QTapAndHoldGesture(), QTapGesture::QTapGesture(), QGestureManager::registerGestureRecognizer(), and QGestureEvent::setAccepted().
hasHotSpot
bool QGesture::hasHotSpot private
whether the gesture has a hot-spot
Definition at line 73 of file qgesture.h.
Referenced by QGraphicsScenePrivate::cancelGesturesForChildren(), QGestureManager::deliverEvents(), QGraphicsScenePrivate::gestureEventHandler(), and QGraphicsScenePrivate::gestureTargetsAtHotSpots().
hotSpot
QPointF QGesture::hotSpot private
The point that is used to find the receiver for the gesture event.
The hot-spot is a point in the global coordinate system, use QWidget::mapFromGlobal() or QGestureEvent::mapToGraphicsScene() to get a local hot-spot.
The hot-spot should be set by the gesture recognizer to allow gesture event delivery to a QGraphicsObject.
Definition at line 72 of file qgesture.h.
Referenced by QGestureManager::deliverEvents(), and QGraphicsScenePrivate::gestureEventHandler().
state
Qt::GestureState QGesture::state private
the current state of the gesture
Definition at line 69 of file qgesture.h.
Referenced by QGestureEvent::activeGestures(), QGestureEvent::canceledGestures(), QGestureManager::deliverEvents(), QGestureManager::filterEventThroughContexts(), QGraphicsScenePrivate::gestureEventHandler(), and QApplication::notify().
The documentation for this class was generated from the following files:
/src/gui/kernel/qgesture.h
/src/gui/kernel/qgesture.cpp