Qt 4.8: QTextFragment Class Reference
QTextFragment Class Reference
The QTextFragment class holds a piece of text in a QTextDocument with a single QTextCharFormat.
#include <qtextobject.h>
Public Functions
QTextCharFormat charFormat () const
Returns the text fragment's character format.
int charFormatIndex () const
Returns an index into the document's internal list of character formats for the text fragment's character format.
bool contains (int position) const
Returns true if the text fragment contains the text at the given position in the document; otherwise returns false.
QList< QGlyphRun > glyphRuns () const
Returns the glyphs of this text fragment.
bool isValid () const
Returns true if this is a valid text fragment (i.
int length () const
Returns the number of characters in the text fragment.
bool operator!= (const QTextFragment &o) const
Returns true if this text fragment is different (at a different position) from the other text fragment; otherwise returns false.
bool operator< (const QTextFragment &o) const
Returns true if this text fragment appears earlier in the document than the other text fragment; otherwise returns false.
QTextFragment & operator= (const QTextFragment &o)
Assigns the content (text and format) of the other text fragment to this text fragment.
bool operator== (const QTextFragment &o) const
Returns true if this text fragment is the same (at the same position) as the other text fragment; otherwise returns false.
int position () const
Returns the position of this text fragment in the document.
QTextFragment (const QTextDocumentPrivate *priv, int f, int fe)
QTextFragment ()
Creates a new empty text fragment.
QTextFragment (const QTextFragment &o)
Copies the content (text and format) of the other text fragment to this text fragment.
QString text () const
Returns the text fragment's as plain text.
Properties
int n
int ne
const QTextDocumentPrivate * p
Detailed Description
The QTextFragment class holds a piece of text in a QTextDocument with a single QTextCharFormat.
Note
This class or function is reentrant.
A text fragment describes a piece of text that is stored with a single character format. Text in which the character format changes can be represented by sequences of text fragments with different formats.
If the user edits the text in a fragment and introduces a different character format, the fragment's text will be split at each point where the format changes, and new fragments will be created. For example, changing the style of some text in the middle of a sentence will cause the fragment to be broken into three separate fragments: the first and third with the same format as before, and the second with the new style. The first fragment will contain the text from the beginning of the sentence, the second will contain the text from the middle, and the third takes the text from the end of the sentence.
A fragment's text and character format can be obtained with the text() and charFormat() functions. The length() function gives the length of the text in the fragment. position() gives the position in the document of the start of the fragment. To determine whether the fragment contains a particular position within the document, use the contains() function.
See also
QTextDocument, {Rich Text Document Structure}
Definition at line 297 of file qtextobject.h.
Constructors and Destructors
QTextFragment() [1/3]
QTextFragment::QTextFragment (const QTextDocumentPrivate * priv, int f, int fe) inline
Warning
This function is not part of the public interface.
Definition at line 300 of file qtextobject.h.
 : p(priv), n(f), ne(fe) {}
QTextFragment() [2/3]
QTextFragment::QTextFragment () inline
Creates a new empty text fragment.
Definition at line 301 of file qtextobject.h.
 : p(0), n(0), ne(0) {}
QTextFragment() [3/3]
QTextFragment::QTextFragment (const QTextFragment & o) inline
Copies the content (text and format) of the other text fragment to this text fragment.
Definition at line 302 of file qtextobject.h.
 : p(o.p), n(o.n), ne(o.ne) {}
Functions
charFormat()
QTextCharFormat QTextFragment::charFormat () const
Returns the text fragment's character format.
See also
text()
Definition at line 1884 of file qtextobject.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextControl::anchorPosition(), QTextHtmlExporter::emitFragment(), QTextControl::findNextPrevAnchor(), and QTextOdfWriter::writeInlineCharacter().
 {
     if (!p || !n)
         return QTextCharFormat();
     const QTextFragmentData *data = p->fragmentMap().fragment(n);
     return p->formatCollection()->charFormat(data->format);
 }
charFormatIndex()
int QTextFragment::charFormatIndex () const
Returns an index into the document's internal list of character formats for the text fragment's character format.
See also
QTextDocument::allFormats()
Definition at line 1898 of file qtextobject.cpp.
 {
     if (!p || !n)
         return -1;
     const QTextFragmentData *data = p->fragmentMap().fragment(n);
     return data->format;
 }
contains()
bool QTextFragment::contains (int position) const
Returns true if the text fragment contains the text at the given position in the document; otherwise returns false.
Definition at line 1871 of file qtextobject.cpp.
 {
     if (!p || !n)
         return false;
     int pos = this->position();
     return position >= pos && position < pos + length();
 }
glyphRuns()
QList< QGlyphRun > QTextFragment::glyphRuns () const
Returns the glyphs of this text fragment.
The positions of the glyphs are relative to the position of the QTextBlock's layout.
See also
QGlyphRun, QTextBlock::layout(), QTextLayout::position(), QPainter::drawGlyphRun()
Definition at line 1812 of file qtextobject.cpp.
 {
     if (!p || !n)
         return QList<QGlyphRun>();
     int pos = position();
     int len = length();
     if (len == 0)
         return QList<QGlyphRun>();
     int blockNode = p->blockMap().findNode(pos);
     const QTextBlockData *blockData = p->blockMap().fragment(blockNode);
     QTextLayout *layout = blockData->layout;
     QList<QGlyphRun> ret;
     for (int i=0; i<layout->lineCount(); ++i) {
         QTextLine textLine = layout->lineAt(i);
         ret += textLine.glyphs(pos, len);
     }
     return ret;
 }
isValid()
bool QTextFragment::isValid () const inline
Returns true if this is a valid text fragment (i.
e. has a valid position in a document); otherwise returns false.
Definition at line 305 of file qtextobject.h.
 { return p && n; }
length()
int QTextFragment::length () const
Returns the number of characters in the text fragment.
See also
text()
Definition at line 1853 of file qtextobject.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), and QTextControl::findNextPrevAnchor().
 {
     if (!p || !n)
         return 0;
     int len = 0;
     int f = n;
     while (f != ne) {
         len += p->fragmentMap().size(f);
         f = p->fragmentMap().next(f);
     }
     return len;
 }
operator!=()
bool QTextFragment::operator!= (const QTextFragment & o) const inline
Returns true if this text fragment is different (at a different position) from the other text fragment; otherwise returns false.
Definition at line 308 of file qtextobject.h.
 { return p != o.p || n != o.n; }
operator<()
bool QTextFragment::operator< (const QTextFragment & o) const inline
Returns true if this text fragment appears earlier in the document than the other text fragment; otherwise returns false.
Definition at line 309 of file qtextobject.h.
 { return position() < o.position(); }
operator=()
QTextFragment & QTextFragment::operator= (const QTextFragment & o) inline
Assigns the content (text and format) of the other text fragment to this text fragment.
Definition at line 303 of file qtextobject.h.
 { p = o.p; n = o.n; ne = o.ne; return *this; }
operator==()
bool QTextFragment::operator== (const QTextFragment & o) const inline
Returns true if this text fragment is the same (at the same position) as the other text fragment; otherwise returns false.
Definition at line 307 of file qtextobject.h.
 { return p == o.p && n == o.n; }
position()
int QTextFragment::position () const
Returns the position of this text fragment in the document.
Definition at line 1840 of file qtextobject.cpp.
Referenced by QTextControlPrivate::activateLinkUnderCursor(), QTextControl::anchorPosition(), QTextControl::findNextPrevAnchor(), and operator<().
 {
     if (!p || !n)
         return 0; // ### -1 instead?
     return p->fragmentMap().position(n);
 }
text()
QString QTextFragment::text () const
Returns the text fragment's as plain text.
See also
length(), charFormat()
Definition at line 1911 of file qtextobject.cpp.
Referenced by QTextHtmlExporter::emitFragment().
 {
     if (!p || !n)
         return QString();
     QString result;
     QString buffer = p->buffer();
     int f = n;
     while (f != ne) {
         const QTextFragmentData * const frag = p->fragmentMap().fragment(f);
         result += QString(buffer.constData() + frag->stringPosition, frag->size_array[0]);
         f = p->fragmentMap().next(f);
     }
     return result;
 }
Properties
n
int QTextFragment::n private
Definition at line 325 of file qtextobject.h.
Referenced by operator!=(), operator=(), and operator==().
ne
int QTextFragment::ne private
Definition at line 326 of file qtextobject.h.
Referenced by operator=().
p
const QTextDocumentPrivate* QTextFragment::p private
Definition at line 324 of file qtextobject.h.
Referenced by operator!=(), operator=(), and operator==().
The documentation for this class was generated from the following files:
/src/gui/text/qtextobject.h
/src/gui/text/qtextobject.cpp