Qt 4.8: QXmlStreamAttribute Class Reference
QXmlStreamAttribute Class Reference
The QXmlStreamAttribute class represents a single XML attribute.
#include <qxmlstream.h>
Public Functions
bool isDefault () const
Returns true if the parser added this attribute with a default value following an ATTLIST declaration in the DTD; otherwise returns false.
QStringRef name () const
Returns the attribute's local name.
QStringRef namespaceUri () const
Returns the attribute's resolved namespaceUri, or an empty string reference if the attribute does not have a defined namespace.
bool operator!= (const QXmlStreamAttribute &other) const
Compares this attribute with other and returns true if they are not equal; otherwise returns false.
QXmlStreamAttribute & operator= (const QXmlStreamAttribute &)
Assigns other to this attribute.
bool operator== (const QXmlStreamAttribute &other) const
Compares this attribute with other and returns true if they are equal; otherwise returns false.
QStringRef prefix () const
Returns the attribute's namespace prefix.
QStringRef qualifiedName () const
Returns the attribute's qualified name.
QXmlStreamAttribute ()
Creates an empty attribute.
QXmlStreamAttribute (const QString &qualifiedName, const QString &value)
Constructs an attribute with qualified name qualifiedName and value value.
QXmlStreamAttribute (const QString &namespaceUri, const QString &name, const QString &value)
Constructs an attribute in the namespace described with namespaceUri with name and value value.
QXmlStreamAttribute (const QXmlStreamAttribute &)
Creates a copy of other.
QStringRef value () const
Returns the attribute's value.
~QXmlStreamAttribute ()
Destructs an attribute.
Properties
uint m_isDefault: 1
QXmlStreamStringRef m_name
QXmlStreamStringRef m_namespaceUri
QXmlStreamStringRef m_qualifiedName
QXmlStreamStringRef m_value
void * reserved
Friends
class QXmlStreamAttributes
class QXmlStreamReaderPrivate
Detailed Description
The QXmlStreamAttribute class represents a single XML attribute.
Since
4.3
Note
This class or function is reentrant.
An attribute consists of an optionally empty namespaceUri(), a name(), a value(), and an isDefault() attribute.
The raw XML attribute name is returned as qualifiedName().
Definition at line 135 of file qxmlstream.h.
Constructors and Destructors
QXmlStreamAttribute() [1/4]
QXmlStreamAttribute::QXmlStreamAttribute ()
Creates an empty attribute.
Definition at line 2345 of file qxmlstream.cpp.
 {
     m_isDefault = false;
 }
QXmlStreamAttribute() [2/4]
QXmlStreamAttribute::QXmlStreamAttribute (const QString & qualifiedName, const QString & value)
Constructs an attribute with qualified name qualifiedName and value value.
Definition at line 2371 of file qxmlstream.cpp.
 {
     int colon = qualifiedName.indexOf(QLatin1Char(':'));
     m_name = QXmlStreamStringRef(QStringRef(&qualifiedName,
                                             colon + 1,
                                             qualifiedName.size() - (colon + 1)));
     m_qualifiedName = QXmlStreamStringRef(QStringRef(&qualifiedName));
     m_value = QXmlStreamStringRef(QStringRef(&value));
 }
QXmlStreamAttribute() [3/4]
QXmlStreamAttribute::QXmlStreamAttribute (const QString & namespaceUri, const QString & name, const QString & value)
Constructs an attribute in the namespace described with namespaceUri with name and value value.
Definition at line 2360 of file qxmlstream.cpp.
 {
     m_namespaceUri = QXmlStreamStringRef(QStringRef(&namespaceUri));
     m_name = m_qualifiedName = QXmlStreamStringRef(QStringRef(&name));
     m_value = QXmlStreamStringRef(QStringRef(&value));
     m_namespaceUri = QXmlStreamStringRef(QStringRef(&namespaceUri));
 }
QXmlStreamAttribute() [4/4]
QXmlStreamAttribute::QXmlStreamAttribute (const QXmlStreamAttribute & other)
Creates a copy of other.
Definition at line 2458 of file qxmlstream.cpp.
 {
     *this = other;
 }
~QXmlStreamAttribute()
QXmlStreamAttribute::~QXmlStreamAttribute ()
Destructs an attribute.
Definition at line 2353 of file qxmlstream.cpp.
 {
 }
Functions
isDefault()
bool QXmlStreamAttribute::isDefault () const inline
Returns true if the parser added this attribute with a default value following an ATTLIST declaration in the DTD; otherwise returns false.
Definition at line 157 of file qxmlstream.h.
 { return m_isDefault; }
name()
QStringRef QXmlStreamAttribute::name () const inline
Returns the attribute's local name.
Definition at line 149 of file qxmlstream.h.
Referenced by QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::handleValidationAttributes(), Document::load(), operator==(), QPatternist::XSLTTokenizer::readAlternativeAttribute(), QXmlStreamReaderPrivate::resolveTag(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QXmlStreamAttributes::value(), and QXmlStreamWriter::writeAttribute().
 { return m_name; }
namespaceUri()
QStringRef QXmlStreamAttribute::namespaceUri () const inline
Returns the attribute's resolved namespaceUri, or an empty string reference if the attribute does not have a defined namespace.
Definition at line 148 of file qxmlstream.h.
Referenced by QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::handleValidationAttributes(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), Document::load(), operator==(), QXmlStreamReaderPrivate::resolveTag(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QXmlStreamAttributes::value(), and QXmlStreamWriter::writeAttribute().
 { return m_namespaceUri; }
operator!=()
bool QXmlStreamAttribute::operator!= (const QXmlStreamAttribute & other) const inline
Compares this attribute with other and returns true if they are not equal; otherwise returns false.
Definition at line 163 of file qxmlstream.h.
         { return !operator==(other); }
operator=()
QXmlStreamAttribute & QXmlStreamAttribute::operator= (const QXmlStreamAttribute & other)
Assigns other to this attribute.
Definition at line 2466 of file qxmlstream.cpp.
 {
     m_name = other.m_name;
     m_namespaceUri = other.m_namespaceUri;
     m_qualifiedName = other.m_qualifiedName;
     m_value = other.m_value;
     m_isDefault = other.m_isDefault;
     return *this;
 }
operator==()
bool QXmlStreamAttribute::operator== (const QXmlStreamAttribute & other) const inline
Compares this attribute with other and returns true if they are equal; otherwise returns false.
Definition at line 158 of file qxmlstream.h.
{
         return (value() == other.value()
                 && (namespaceUri().isNull() ? (qualifiedName() == other.qualifiedName())
                     : (namespaceUri() == other.namespaceUri() && name() == other.name())));
     }
prefix()
QStringRef QXmlStreamAttribute::prefix () const inline
Returns the attribute's namespace prefix.
Since
4.4
See also
name(), qualifiedName()
Definition at line 151 of file qxmlstream.h.
Referenced by QPatternist::XSLTTokenizer::insideSequenceConstructor(), and QPatternist::AccelTreeResourceLoader::streamToReceiver().
{
         return QStringRef(m_qualifiedName.string(),
                           m_qualifiedName.position(),
                           qMax(0, m_qualifiedName.size() - m_name.size() - 1));
     }
qualifiedName()
QStringRef QXmlStreamAttribute::qualifiedName () const inline
Returns the attribute's qualified name.
A qualified name is the raw name of an attribute in the XML data. It consists of the namespace prefix(), followed by colon, followed by the attribute's local name(). Since the namespace prefix is not unique (the same prefix can point to different namespaces and different prefixes can point to the same namespace), you shouldn't use qualifiedName(), but the resolved namespaceUri() and the attribute's local name().
Definition at line 150 of file qxmlstream.h.
Referenced by QPatternist::XSLTTokenizer::handleStandardAttributes(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), operator==(), parseCoreNode(), QSvgAttributes::QSvgAttributes(), QXmlStreamReaderPrivate::resolveTag(), QXmlStreamAttributes::value(), and QXmlStreamWriter::writeAttribute().
 { return m_qualifiedName; }
value()
QStringRef QXmlStreamAttribute::value () const inline
Returns the attribute's value.
Definition at line 156 of file qxmlstream.h.
Referenced by QPatternist::XSLTTokenizer::insideSequenceConstructor(), Document::load(), operator==(), parseCoreNode(), QSvgAttributes::QSvgAttributes(), QPatternist::XSLTTokenizer::readAlternativeAttribute(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), QXmlStreamAttributes::value(), and QXmlStreamWriter::writeAttribute().
 { return m_value; }
Friends and Related Functions
QXmlStreamAttributes
friend class QXmlStreamAttributes friend
Definition at line 140 of file qxmlstream.h.
QXmlStreamReaderPrivate
friend class QXmlStreamReaderPrivate friend
Definition at line 139 of file qxmlstream.h.
Properties
m_isDefault
uint QXmlStreamAttribute::m_isDefault private
Definition at line 138 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveTag().
m_name
QXmlStreamStringRef QXmlStreamAttribute::m_name private
Definition at line 136 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveTag().
m_namespaceUri
QXmlStreamStringRef QXmlStreamAttribute::m_namespaceUri private
Definition at line 136 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveTag().
m_qualifiedName
QXmlStreamStringRef QXmlStreamAttribute::m_qualifiedName private
Definition at line 136 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveTag().
m_value
QXmlStreamStringRef QXmlStreamAttribute::m_value private
Definition at line 136 of file qxmlstream.h.
Referenced by operator=(), and QXmlStreamReaderPrivate::resolveTag().
reserved
void* QXmlStreamAttribute::reserved private
Definition at line 137 of file qxmlstream.h.
The documentation for this class was generated from the following files:
/src/corelib/xml/qxmlstream.h
/src/corelib/xml/qxmlstream.cpp