Qt 4.8: Node Class Reference
Node Class Reference
Public Functions
bool isNull () const
Node ()
Node (const Node &o)
~Node ()
Static Public Functions
static QScriptValue attributes (QScriptContext *context, QScriptEngine *engine)
static QScriptValue childNodes (QScriptContext *context, QScriptEngine *engine)
static QScriptValue create (QScriptEngine *, NodeImpl *)
static QScriptValue firstChild (QScriptContext *context, QScriptEngine *engine)
static QScriptValue lastChild (QScriptContext *context, QScriptEngine *engine)
static QScriptValue nextSibling (QScriptContext *context, QScriptEngine *engine)
static QScriptValue nodeName (QScriptContext *context, QScriptEngine *engine)
static QScriptValue nodeType (QScriptContext *context, QScriptEngine *engine)
static QScriptValue nodeValue (QScriptContext *context, QScriptEngine *engine)
static QScriptValue parentNode (QScriptContext *context, QScriptEngine *engine)
static QScriptValue previousSibling (QScriptContext *context, QScriptEngine *engine)
static QScriptValue prototype (QScriptEngine *)
Public Variables
NodeImpl * d
Private Functions
Node & operator= (const Node &)
Detailed Description
Definition at line 224 of file qdeclarativexmlhttprequest.cpp.
Constructors and Destructors
Node() [1/2]
Node::Node ()
Definition at line 718 of file qdeclarativexmlhttprequest.cpp.
 : d(0)
 {
 }
Node() [2/2]
Node::Node (const Node & o)
Definition at line 723 of file qdeclarativexmlhttprequest.cpp.
 : d(o.d)
 {
     if (d) A(d);
 }
~Node()
Node::~Node ()
Definition at line 729 of file qdeclarativexmlhttprequest.cpp.
 {
     if (d) D(d);
 }
Functions
attributes()
QScriptValue Node::attributes (QScriptContext * context, QScriptEngine * engine) static
Definition at line 454 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     if (node.d->type != NodeImpl::Element)
         return engine->nullValue();
     else
         return NamedNodeMap::create(engine, node.d, &node.d->attributes);
 }
childNodes()
QScriptValue Node::childNodes (QScriptContext * context, QScriptEngine * engine) static
Definition at line 394 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     return NodeList::create(engine, node.d);
 }
create()
QScriptValue Node::create (QScriptEngine * engine, NodeImpl * data) static
Definition at line 483 of file qdeclarativexmlhttprequest.cpp.
Referenced by Document::documentElement(), firstChild(), lastChild(), nextSibling(), Attr::ownerElement(), parentNode(), previousSibling(), NamedNodeMapClass::property(), and NodeListClass::property().
 {
     QScriptValue instance = engine->newObject();
     switch (data->type) {
     case NodeImpl::Attr:
         instance.setPrototype(Attr::prototype(engine));
         break;
     case NodeImpl::Comment:
     case NodeImpl::Document:
     case NodeImpl::DocumentFragment:
     case NodeImpl::DocumentType:
     case NodeImpl::Entity:
     case NodeImpl::EntityReference:
     case NodeImpl::Notation:
     case NodeImpl::ProcessingInstruction:
         return QScriptValue();
     case NodeImpl::CDATA:
         instance.setPrototype(CDATA::prototype(engine));
         break;
     case NodeImpl::Text:
         instance.setPrototype(Text::prototype(engine));
         break;
     case NodeImpl::Element:
         instance.setPrototype(Element::prototype(engine));
         break;
     }
     Node node;
     node.d = data;
     if (data) A(data);
     return engine->newVariant(instance, QVariant::fromValue(node));
 }
firstChild()
QScriptValue Node::firstChild (QScriptContext * context, QScriptEngine * engine) static
Definition at line 402 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     if (node.d->children.isEmpty()) return engine->nullValue();
     else return Node::create(engine, node.d->children.first());
 }
isNull()
bool Node::isNull () const
Definition at line 734 of file qdeclarativexmlhttprequest.cpp.
Referenced by attributes(), childNodes(), Document::documentElement(), firstChild(), Text::isElementContentWhitespace(), lastChild(), CharacterData::length(), Attr::name(), nextSibling(), nodeName(), nodeType(), nodeValue(), Attr::ownerElement(), parentNode(), previousSibling(), Attr::value(), Text::wholeText(), Document::xmlEncoding(), Document::xmlStandalone(), and Document::xmlVersion().
 {
     return d == 0;
 }
lastChild()
QScriptValue Node::lastChild (QScriptContext * context, QScriptEngine * engine) static
Definition at line 411 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     if (node.d->children.isEmpty()) return engine->nullValue();
     else return Node::create(engine, node.d->children.last());
 }
nextSibling()
QScriptValue Node::nextSibling (QScriptContext * context, QScriptEngine * engine) static
Definition at line 437 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     if (!node.d->parent) return engine->nullValue();
     for (int ii = 0; ii < node.d->parent->children.count(); ++ii) {
         if (node.d->parent->children.at(ii) == node.d) {
             if ((ii + 1) == node.d->parent->children.count()) return engine->nullValue();
             else return Node::create(engine, node.d->parent->children.at(ii + 1));
         }
     }
     return engine->nullValue();
 }
nodeName()
QScriptValue Node::nodeName (QScriptContext * context, QScriptEngine * engine) static
Definition at line 344 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     switch (node.d->type) {
     case NodeImpl::Document:
         return QScriptValue(QLatin1String("#document"));
     case NodeImpl::CDATA:
         return QScriptValue(QLatin1String("#cdata-section"));
     case NodeImpl::Text:
         return QScriptValue(QLatin1String("#text"));
     default:
         return QScriptValue(node.d->name);
     }
 }
nodeType()
QScriptValue Node::nodeType (QScriptContext * context, QScriptEngine * engine) static
Definition at line 378 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     return QScriptValue(node.d->type);
 }
nodeValue()
QScriptValue Node::nodeValue (QScriptContext * context, QScriptEngine * engine) static
Definition at line 361 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     if (node.d->type == NodeImpl::Document ||
         node.d->type == NodeImpl::DocumentFragment ||
         node.d->type == NodeImpl::DocumentType ||
         node.d->type == NodeImpl::Element ||
         node.d->type == NodeImpl::Entity ||
         node.d->type == NodeImpl::EntityReference ||
         node.d->type == NodeImpl::Notation)
         return engine->nullValue();
     return QScriptValue(node.d->data);
 }
operator=()
Node& Node::operator= (const Node &) private
Referenced by QMap< int, QFrameInfo >::~QMap().
parentNode()
QScriptValue Node::parentNode (QScriptContext * context, QScriptEngine * engine) static
Definition at line 385 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     if (node.d->parent) return Node::create(engine, node.d->parent);
     else return engine->nullValue();
 }
previousSibling()
QScriptValue Node::previousSibling (QScriptContext * context, QScriptEngine * engine) static
Definition at line 420 of file qdeclarativexmlhttprequest.cpp.
 {
     Node node = qscriptvalue_cast<Node>(context->thisObject());
     if (node.isNull()) return engine->undefinedValue();
     if (!node.d->parent) return engine->nullValue();
     for (int ii = 0; ii < node.d->parent->children.count(); ++ii) {
         if (node.d->parent->children.at(ii) == node.d) {
             if (ii == 0) return engine->nullValue();
             else return Node::create(engine, node.d->parent->children.at(ii - 1));
         }
     }
     return engine->nullValue();
 }
prototype()
QScriptValue Node::prototype (QScriptEngine * engine) static
Definition at line 465 of file qdeclarativexmlhttprequest.cpp.
Referenced by Element::prototype(), Attr::prototype(), CharacterData::prototype(), and Document::prototype().
 {
     QScriptValue proto = engine->newObject();
     proto.setProperty(QLatin1String("nodeName"), engine->newFunction(nodeName), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("nodeValue"), engine->newFunction(nodeValue), QScriptValue::ReadOnly | QScriptValue::PropertyGetter | QScriptValue::PropertySetter);
     proto.setProperty(QLatin1String("nodeType"), engine->newFunction(nodeType), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("parentNode"), engine->newFunction(parentNode), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("childNodes"), engine->newFunction(childNodes), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("firstChild"), engine->newFunction(firstChild), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("lastChild"), engine->newFunction(lastChild), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("previousSibling"), engine->newFunction(previousSibling), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("nextSibling"), engine->newFunction(nextSibling), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     proto.setProperty(QLatin1String("attributes"), engine->newFunction(attributes), QScriptValue::ReadOnly | QScriptValue::PropertyGetter);
     return proto;
 }
Properties
d
NodeImpl* Node::d
Definition at line 256 of file qdeclarativexmlhttprequest.cpp.
Referenced by attributes(), childNodes(), QMap< int, QFrameInfo >::count(), create(), QMap< int, QFrameInfo >::detach(), QMap< int, QFrameInfo >::detach_helper(), Document::documentElement(), QMap< int, QFrameInfo >::empty(), QMap< int, QFrameInfo >::erase(), QMap< int, QFrameInfo >::findNode(), firstChild(), QMap< int, QFrameInfo >::insert(), QMap< int, QFrameInfo >::insertMulti(), QMap< int, QFrameInfo >::isDetached(), Text::isElementContentWhitespace(), QMap< int, QFrameInfo >::isEmpty(), isNull(), QMap< int, QFrameInfo >::isSharedWith(), lastChild(), CharacterData::length(), Document::load(), QMap< int, QFrameInfo >::mutableFindNode(), Attr::name(), nextSibling(), Node(), nodeName(), nodeType(), nodeValue(), QMap< int, QFrameInfo >::operator=(), QMap< int, QFrameInfo >::operator==(), QMap< int, QFrameInfo >::operator[](), Attr::ownerElement(), parentNode(), previousSibling(), QMap< int, QFrameInfo >::QMap(), QMap< int, QFrameInfo >::remove(), QMap< int, QFrameInfo >::setInsertInOrder(), QMap< int, QFrameInfo >::setSharable(), QMap< int, QFrameInfo >::size(), QMap< int, QFrameInfo >::swap(), QMap< int, QFrameInfo >::take(), QMap< int, QFrameInfo >::value(), Attr::value(), Text::wholeText(), Document::xmlEncoding(), Document::xmlStandalone(), Document::xmlVersion(), ~Node(), and QMap< int, QFrameInfo >::~QMap().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativexmlhttprequest.cpp