Qt 4.8: QProxyScreenCursor Class Reference
QProxyScreenCursor Class Reference
The QProxyScreenCursor class provides a generic interface to QScreenCursor implementations.
#include <qscreenproxy_qws.h>
Public Functions
void hide ()
Reimplemented Function
void move (int x, int y)
Reimplemented Function
QProxyScreenCursor ()
Constructs a proxy screen cursor.
QScreenCursor * screenCursor () const
Returns the real screen cursor used by the proxy screen cursor.
void set (const QImage &image, int hotx, int hoty)
Reimplemented Function
void setScreenCursor (QScreenCursor *cursor)
Sets the real screen cursor to be used for the proxy screen cursor to the cursor specified.
void show ()
Reimplemented Function
~QProxyScreenCursor ()
Destroys the proxy screen cursor.
Public Functions inherited from QScreenCursor
QRect boundingRect () const
Returns the cursor's bounding rectangle.
QImage image () const
Returns the cursor's image.
bool isAccelerated () const
Returns true if the cursor is accelerated; otherwise false.
bool isVisible () const
Returns true if the cursor is visible; otherwise false.
QScreenCursor ()
Constructs a screen cursor.
bool supportsAlphaCursor () const
virtual ~QScreenCursor ()
Destroys the screen cursor.
Private Functions
void configure ()
Properties
QProxyScreenCursorPrivate * d_ptr
QScreenCursor * realCursor
Additional Inherited Members
Static Public Functions inherited from QScreenCursor
static bool enabled ()
static void initSoftwareCursor ()
Initializes the screen cursor.
static QScreenCursor * instance ()
Protected Variables inherited from QScreenCursor
QImage cursor
uint enable: 1
QPoint hotspot
uint hwaccel: 1
QPoint pos
QSize size
uint supportsAlpha: 1
Detailed Description
The QProxyScreenCursor class provides a generic interface to QScreenCursor implementations.
Since
4.5
Definition at line 61 of file qscreenproxy_qws.h.
Constructors and Destructors
QProxyScreenCursor()
QProxyScreenCursor::QProxyScreenCursor ()
Constructs a proxy screen cursor.
Definition at line 65 of file qscreenproxy_qws.cpp.
     : QScreenCursor(), realCursor(0), d_ptr(0)
 {
 }
~QProxyScreenCursor()
QProxyScreenCursor::~QProxyScreenCursor ()
Destroys the proxy screen cursor.
Definition at line 73 of file qscreenproxy_qws.cpp.
 {
 }
Functions
configure()
void QProxyScreenCursor::configure () private
Warning
This function is not part of the public interface.
Definition at line 156 of file qscreenproxy_qws.cpp.
Referenced by setScreenCursor().
 {
     if (!realCursor)
         return;
     cursor = realCursor->cursor;
     size = realCursor->size;
     pos = realCursor->pos;
     hotspot = realCursor->hotspot;
     enable = realCursor->enable;
     hwaccel = realCursor->hwaccel;
     supportsAlpha = realCursor->supportsAlpha;
 }
hide()
void QProxyScreenCursor::hide () virtual
Reimplemented Function
Reimplemented from QScreenCursor.
Reimplemented in QVNCCursor.
Definition at line 143 of file qscreenproxy_qws.cpp.
Referenced by QVNCCursor::hide().
 {
     if (realCursor) {
         realCursor->hide();
         enable = false;
     } else {
         QScreenCursor::hide();
     }
 }
move()
void QProxyScreenCursor::move (int x, int y) virtual
Reimplemented Function
Reimplemented from QScreenCursor.
Reimplemented in QVNCCursor.
Definition at line 117 of file qscreenproxy_qws.cpp.
Referenced by QVNCCursor::move().
 {
     if (realCursor) {
         pos = QPoint(x, y);
         realCursor->move(x, y);
     } else {
         QScreenCursor::move(x, y);
     }
 }
screenCursor()
QScreenCursor * QProxyScreenCursor::screenCursor () const
Returns the real screen cursor used by the proxy screen cursor.
See also
setScreenCursor()
Definition at line 94 of file qscreenproxy_qws.cpp.
Referenced by QVNCClientCursor::~QVNCClientCursor(), and QVNCCursor::~QVNCCursor().
 {
     return realCursor;
 }
set()
void QProxyScreenCursor::set (const QImage & image, int hotx, int hoty) virtual
Reimplemented Function
Reimplemented from QScreenCursor.
Reimplemented in QVNCClientCursor, and QVNCCursor.
Definition at line 102 of file qscreenproxy_qws.cpp.
Referenced by QVNCCursor::set().
 {
     if (realCursor) {
         hotspot = QPoint(hotx, hoty);
         cursor = image;
         size = image.size();
         realCursor->set(image, hotx, hoty);
     } else {
         QScreenCursor::set(image, hotx, hoty);
     }
 }
setScreenCursor()
void QProxyScreenCursor::setScreenCursor (QScreenCursor * cursor)
Sets the real screen cursor to be used for the proxy screen cursor to the cursor specified.
See also
screenCursor()
Definition at line 83 of file qscreenproxy_qws.cpp.
Referenced by QVNCClientCursor::QVNCClientCursor(), and QVNCCursor::QVNCCursor().
 {
     realCursor = cursor;
     configure();
 }
show()
void QProxyScreenCursor::show () virtual
Reimplemented Function
Reimplemented from QScreenCursor.
Reimplemented in QVNCCursor.
Definition at line 130 of file qscreenproxy_qws.cpp.
Referenced by QVNCCursor::show().
 {
     if (realCursor) {
         realCursor->show();
         enable = true;
     } else {
         QScreenCursor::show();
     }
 }
Properties
d_ptr
QProxyScreenCursorPrivate* QProxyScreenCursor::d_ptr private
Definition at line 79 of file qscreenproxy_qws.h.
realCursor
QScreenCursor* QProxyScreenCursor::realCursor private
Definition at line 78 of file qscreenproxy_qws.h.
Referenced by configure(), hide(), move(), screenCursor(), set(), setScreenCursor(), and show().
The documentation for this class was generated from the following files:
/src/gui/embedded/qscreenproxy_qws.h
/src/gui/embedded/qscreenproxy_qws.cpp