Qt 4.8: QSourceLocation Class Reference
QSourceLocation Class Reference
The QSourceLocation class identifies a location in a resource by URI, line, and column.
#include <qsourcelocation.h>
Public Functions
qint64 column () const
Returns the current column number.
bool isNull () const
Returns true if this QSourceLocation doesn't identify anything.
qint64 line () const
Returns the current line number.
bool operator!= (const QSourceLocation &other) const
Returns the opposite of applying operator==() for this QXmlName and other.
QSourceLocation & operator= (const QSourceLocation &other)
Assigns this QSourceLocation instance to other.
bool operator== (const QSourceLocation &other) const
Returns true if this QSourceLocation is identical to other.
QSourceLocation ()
Construct a QSourceLocation that doesn't identify anything at all.
QSourceLocation (const QSourceLocation &other)
Constructs a QSourceLocation that is a copy of other.
QSourceLocation (const QUrl &uri, int line=-1, int column=-1)
Constructs a QSourceLocation with URI u, line l and column c.
void setColumn (qint64 newColumn)
Sets the column number to newColumn.
void setLine (qint64 newLine)
Sets the line number to newLine.
void setUri (const QUrl &newUri)
Sets the URI to newUri.
QUrl uri () const
Returns the resource that this QSourceLocation refers to.
~QSourceLocation ()
Destructor.
Properties
union {
qint64 m_line
QSourceLocationPrivate * m_ptr
};
qint64 m_column
QUrl m_uri
Related Functions
(Note that these are not member functions.)
QDebug operator<< (QDebug debug, const QSourceLocation &sourceLocation)
Prints sourceLocation to the debug stream debug.
uint qHash (const QSourceLocation &location)
Detailed Description
The QSourceLocation class identifies a location in a resource by URI, line, and column.
Note
This class or function is reentrant.
Since
4.4
QSourceLocation is a simple value based class that has three properties, uri(), line(), and column(), that, taken together, identify a certain point in a resource, e.g., a file or an in-memory document.
line() and column() refer to character counts (not byte counts), and they both start from 1, as opposed to 0.
Definition at line 56 of file qsourcelocation.h.
Constructors and Destructors
QSourceLocation() [1/3]
QSourceLocation::QSourceLocation ()
Construct a QSourceLocation that doesn't identify anything at all.
For a default constructed QSourceLocation(), isNull() returns true.
Definition at line 73 of file qsourcelocation.cpp.
                                  : m_line(-1), m_column(-1)
 {
 }
QSourceLocation() [2/3]
QSourceLocation::QSourceLocation (const QSourceLocation & other)
Constructs a QSourceLocation that is a copy of other.
Definition at line 80 of file qsourcelocation.cpp.
   : m_line(other.m_line), m_column(other.m_column), m_uri(other.m_uri)
 {
 }
QSourceLocation() [3/3]
QSourceLocation::QSourceLocation (const QUrl & uri, int line = -1, int column = -1)
Constructs a QSourceLocation with URI u, line l and column c.
Definition at line 88 of file qsourcelocation.cpp.
   : m_line(l), m_column(c), m_uri(u)
 {
 }
~QSourceLocation()
QSourceLocation::~QSourceLocation ()
Destructor.
Definition at line 96 of file qsourcelocation.cpp.
 {
 }
Functions
column()
qint64 QSourceLocation::column () const
Returns the current column number.
The column number refers to the count of characters, not bytes. The first column is column 1, not 0. The default value is -1, indicating the column number is unknown.
Definition at line 145 of file qsourcelocation.cpp.
Referenced by QPatternist::ColoringMessageHandler::handleMessage(), operator<<(), and qHash().
 {
     return m_column;
 }
isNull()
bool QSourceLocation::isNull () const
Returns true if this QSourceLocation doesn't identify anything.
For a default constructed QSourceLocation, this function returns true. The same applies for any other QSourceLocation whose uri() is invalid.
Definition at line 227 of file qsourcelocation.cpp.
Referenced by QPatternist::GenericStaticContext::addLocation(), QPatternist::ColoringMessageHandler::handleMessage(), and QPatternist::ReportContext::lookupSourceLocation().
 {
     return !m_uri.isValid();
 }
line()
qint64 QSourceLocation::line () const
Returns the current line number.
The first line number is 1, not 0. The default value is -1, indicating the line number is unknown.
Definition at line 165 of file qsourcelocation.cpp.
Referenced by QPatternist::ColoringMessageHandler::handleMessage(), operator<<(), and qHash().
 {
     return m_line;
 }
operator!=()
bool QSourceLocation::operator!= (const QSourceLocation & other) const
Returns the opposite of applying operator==() for this QXmlName and other.
Definition at line 120 of file qsourcelocation.cpp.
 {
     return operator==(other);
 }
operator=()
QSourceLocation & QSourceLocation::operator= (const QSourceLocation & other)
Assigns this QSourceLocation instance to other.
Definition at line 128 of file qsourcelocation.cpp.
 {
     if(this != &other)
     {
         m_line = other.m_line;
         m_column = other.m_column;
         m_uri = other.m_uri;
     }
     return *this;
 }
operator==()
bool QSourceLocation::operator== (const QSourceLocation & other) const
Returns true if this QSourceLocation is identical to other.
Two QSourceLocation instances are equal if their uri(), line() and column() are equal.
QSourceLocation instances for which isNull() returns true are considered equal.
Definition at line 109 of file qsourcelocation.cpp.
Referenced by operator!=().
 {
     return    m_line == other.m_line
            && m_column == other.m_column
            && m_uri == other.m_uri;
 }
setColumn()
void QSourceLocation::setColumn (qint64 newColumn)
Sets the column number to newColumn.
0 is an invalid column number. The first column number is 1.
Definition at line 154 of file qsourcelocation.cpp.
Referenced by QPatternist::XsdSchemaParser::currentSourceLocation(), QPatternist::XsdSchemaChecker::sourceLocation(), and QPatternist::XsdSchemaResolver::sourceLocation().
 {
     Q_ASSERT_X(newColumn != 0, Q_FUNC_INFO,
                "0 is an invalid column number. The first column number is 1.");
     m_column = newColumn;
 }
setLine()
void QSourceLocation::setLine (qint64 newLine)
Sets the line number to newLine.
0 is an invalid line number. The first line number is 1.
Definition at line 174 of file qsourcelocation.cpp.
Referenced by QPatternist::XsdSchemaParser::currentSourceLocation(), QPatternist::XsdSchemaChecker::sourceLocation(), and QPatternist::XsdSchemaResolver::sourceLocation().
 {
     m_line = newLine;
 }
setUri()
void QSourceLocation::setUri (const QUrl & newUri)
Sets the URI to newUri.
Definition at line 192 of file qsourcelocation.cpp.
Referenced by QPatternist::XsdSchemaParser::currentSourceLocation(), QPatternist::XsdSchemaChecker::sourceLocation(), and QPatternist::XsdSchemaResolver::sourceLocation().
 {
     m_uri = newUri;
 }
uri()
QUrl QSourceLocation::uri () const
Returns the resource that this QSourceLocation refers to.
For example, the resource could be a file in the local file system, if the URI scheme is file.
Definition at line 184 of file qsourcelocation.cpp.
Referenced by QPatternist::ColoringMessageHandler::handleMessage(), operator<<(), and qHash().
 {
     return m_uri;
 }
Friends and Related Functions
operator<<()
QDebug operator<< (QDebug debug, const QSourceLocation & sourceLocation) related
Prints sourceLocation to the debug stream debug.
Since
4.4
Definition at line 207 of file qsourcelocation.cpp.
 {
     debug << "QSourceLocation("
           << sourceLocation.uri()
           << ", line:"
           << sourceLocation.line()
           << ", column:"
           << sourceLocation.column()
           << ')';
     return debug;
 }
qHash()
uint qHash (const QSourceLocation & location) related
Since
4.4
Computes a hash key for the QSourceLocation location.
Definition at line 239 of file qsourcelocation.cpp.
 {
     /* Not the world's best hash function exactly. */
     return qHash(location.uri().toString()) + location.line() + location.column();
 }
Properties
@375
union { ... }
m_column
qint64 QSourceLocation::m_column private
Definition at line 83 of file qsourcelocation.h.
Referenced by column(), operator=(), operator==(), and setColumn().
m_line
qint64 QSourceLocation::m_line
Definition at line 80 of file qsourcelocation.h.
Referenced by line(), operator=(), operator==(), and setLine().
m_ptr
QSourceLocationPrivate* QSourceLocation::m_ptr
Definition at line 81 of file qsourcelocation.h.
m_uri
QUrl QSourceLocation::m_uri private
Definition at line 84 of file qsourcelocation.h.
Referenced by isNull(), operator=(), operator==(), setUri(), and uri().
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qsourcelocation.h
/src/xmlpatterns/api/qsourcelocation.cpp