Qt 4.8: QScriptEngineAgent Class Reference
QScriptEngineAgent Class Reference
The QScriptEngineAgent class provides an interface to report events pertaining to QScriptEngine execution.
#include <qscriptengineagent.h>
Public Types
enum Extension { DebuggerInvocationRequest }
This enum specifies the possible extensions to a QScriptEngineAgent.
Public Functions
virtual void contextPop ()
This function is called when the current script context is about to be popped.
virtual void contextPush ()
This function is called when a new script context has been pushed.
QScriptEngine * engine () const
Returns the QScriptEngine that this agent is associated with.
virtual void exceptionCatch (qint64 scriptId, const QScriptValue &exception)
This function is called when the given exception is about to be caught, in the script identified by scriptId.
virtual void exceptionThrow (qint64 scriptId, const QScriptValue &exception, bool hasHandler)
This function is called when the given exception has occurred in the engine, in the script identified by scriptId.
virtual QVariant extension (Extension extension, const QVariant &argument=QVariant())
This virtual function can be reimplemented in a QScriptEngineAgent subclass to provide support for extensions.
virtual void functionEntry (qint64 scriptId)
This function is called when a script function is called in the engine.
virtual void functionExit (qint64 scriptId, const QScriptValue &returnValue)
This function is called when the currently executing script function is about to return.
virtual void positionChange (qint64 scriptId, int lineNumber, int columnNumber)
This function is called when the engine is about to execute a new statement in the script identified by scriptId.
QScriptEngineAgent (QScriptEngine *engine)
Constructs a QScriptEngineAgent object for the given engine.
virtual void scriptLoad (qint64 id, const QString &program, const QString &fileName, int baseLineNumber)
This function is called when the engine has parsed a script and has associated it with the given id.
virtual void scriptUnload (qint64 id)
This function is called when the engine has discarded the script identified by the given id.
virtual bool supportsExtension (Extension extension) const
Returns true if the QScriptEngineAgent supports the given extension; otherwise, false is returned.
virtual ~QScriptEngineAgent ()
Destroys this QScriptEngineAgent.
Protected Functions
QScriptEngineAgent (QScriptEngineAgentPrivate &dd, QScriptEngine *engine)
Protected Variables
QScopedPointer< QScriptEngineAgentPrivate > d_ptr
Detailed Description
The QScriptEngineAgent class provides an interface to report events pertaining to QScriptEngine execution.
Since
4.4
The QScriptEngineAgent class is the basis of tools that monitor and/or control the execution of a QScriptEngine, such as debuggers and profilers.
To process script loading and unloading events, reimplement the scriptLoad() and scriptUnload() functions. scriptLoad() is called after the input to QScriptEngine::evaluate() has been parsed, right before the given script is executed. The engine assigns each script an ID, which is available as one of the arguments to scriptLoad(); subsequently, other event handlers can use the ID to identify a particular script. One common usage of scriptLoad() is to retain the script text, filename and base line number (the original input to QScriptEngine::evaluate()), so that other event handlers can e.g. map a line number to the corresponding line of text.
scriptUnload() is called when the QScriptEngine has no further use for a script; the QScriptEngineAgent may at this point safely discard any resources associated with the script (such as the script text). Note that after scriptUnload() has been called, the QScriptEngine may reuse the relevant script ID for new scripts (i.e. as argument to a subsequent call to scriptLoad()).
Evaluating the following script will result in scriptUnload() being called immediately after evaluation has completed:
var a = Math.random() + 2;
Evaluating the following script will {not} result in a call to scriptUnload() when evaluation has completed:
function cube(a) {
    return a * a * a;
}
var a = cube(3);
The script isn't unloaded because it defines a function (cube) that remains in the script environment after evaluation has completed. If a subsequent script removed the cube function (e.g. by setting it to null), scriptUnload() would be called when the function is garbage collected. In general terms, a script isn't unloaded until the engine has determined that none of its contents is referenced.
To process script function calls and returns, reimplement the functionEntry() and functionExit() functions. functionEntry() is called when a script function is about to be executed; functionExit() is called when a script function is about to return, either normally or due to an exception.
To process individual script statements, reimplement positionChange(). positionChange() is called each time the engine is about to execute a new statement of a script, and thus offers the finest level of script monitoring.
To process exceptions, reimplement exceptionThrow() and exceptionCatch(). exceptionThrow() is called when a script exception is thrown, before it has been handled. exceptionCatch() is called when an exception handler is present, and execution is about to be resumed at the handler code.
See also
QScriptEngine::setAgent(), QScriptContextInfo
Definition at line 42 of file qscriptengineagent.h.
Enumerations
Extension
enum QScriptEngineAgent::Extension
This enum specifies the possible extensions to a QScriptEngineAgent.
DebuggerInvocationRequest The agent handles debugger script statements.
See also
extension()
Enumerator
DebuggerInvocationRequest
Definition at line 45 of file qscriptengineagent.h.
                    {
         DebuggerInvocationRequest
     };
Constructors and Destructors
QScriptEngineAgent() [1/2]
QScriptEngineAgent::QScriptEngineAgent (QScriptEngine * engine)
Constructs a QScriptEngineAgent object for the given engine.
The engine takes ownership of the agent.
Call QScriptEngine::setAgent() to make this agent the active agent.
Definition at line 227 of file qscriptengineagent.cpp.
         : d_ptr(new QScriptEngineAgentPrivate())
 {
     d_ptr->q_ptr = this;
     d_ptr->engine = QScriptEnginePrivate::get(engine);
     d_ptr->engine->ownedAgents.append(this);
 }
~QScriptEngineAgent()
QScriptEngineAgent::~QScriptEngineAgent () virtual
Destroys this QScriptEngineAgent.
Definition at line 248 of file qscriptengineagent.cpp.
 {
     d_ptr->engine->agentDeleted(this); //### TODO: Can this throw?
 }
QScriptEngineAgent() [2/2]
QScriptEngineAgent::QScriptEngineAgent (QScriptEngineAgentPrivate & dd, QScriptEngine * engine) protected
Warning
This function is not part of the public interface.
Definition at line 238 of file qscriptengineagent.cpp.
     : d_ptr(&dd)
 {
     d_ptr->q_ptr = this;
     d_ptr->engine = QScriptEnginePrivate::get(engine);
 }
Functions
contextPop()
void QScriptEngineAgent::contextPop () virtual
This function is called when the current script context is about to be popped.
The default implementation does nothing.
See also
contextPush(), functionExit()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 319 of file qscriptengineagent.cpp.
Referenced by QScriptEngineAgentPrivate::functionExit(), and QScriptEngine::popContext().
 {
 }
contextPush()
void QScriptEngineAgent::contextPush () virtual
This function is called when a new script context has been pushed.
The default implementation does nothing.
See also
contextPop(), functionEntry()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 307 of file qscriptengineagent.cpp.
Referenced by QScriptDeclarativeClass::pushCleanContext(), and QScriptEngine::pushContext().
 {
 }
engine()
QScriptEngine * QScriptEngineAgent::engine () const
Returns the QScriptEngine that this agent is associated with.
Definition at line 510 of file qscriptengineagent.cpp.
Referenced by QJSDebuggerAgent::backtrace(), QJSDebuggerAgentPrivate::engine(), QScriptDebuggerAgent::enterReturnByForceMode(), QScriptDebuggerAgent::enterStepOutMode(), QScriptDebuggerAgent::enterStepOverMode(), QJSDebuggerAgent::executeExpression(), QJSDebuggerAgent::expandObjectById(), QScriptDebuggerAgent::functionExit(), QJSDebuggerAgent::locals(), QJSDebuggerAgent::localsAtFrame(), QJSDebuggerAgentPrivate::positionChange(), QScriptDebuggerAgent::positionChange(), QScriptDebuggerBackendPrivate::postEvent(), QJSDebuggerAgent::QJSDebuggerAgent(), QScriptEngine::setAgent(), QJSDebuggerAgent::setProperty(), QJSDebuggerAgent::watches(), and QJSDebuggerAgent::~QJSDebuggerAgent().
 {
     Q_D(const QScriptEngineAgent);
     return QScriptEnginePrivate::get(d->engine);
 }
exceptionCatch()
void QScriptEngineAgent::exceptionCatch (qint64 scriptId, const QScriptValue & exception) virtual
This function is called when the given exception is about to be caught, in the script identified by scriptId.
Reimplement this function if you want to handle this event.
The default implementation does nothing.
See also
exceptionThrow()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 440 of file qscriptengineagent.cpp.
Referenced by QScriptEngineAgentPrivate::exceptionCatch().
 {
     Q_UNUSED(scriptId);
     Q_UNUSED(exception);
 }
exceptionThrow()
void QScriptEngineAgent::exceptionThrow (qint64 scriptId, const QScriptValue & exception, bool hasHandler) virtual
This function is called when the given exception has occurred in the engine, in the script identified by scriptId.
If the exception was thrown by a native Qt Script function, scriptId is -1.
If hasHandler is true, there is a catch or finally block that will handle the exception. If hasHandler is false, there is no handler for the exception.
Reimplement this function if you want to handle this event. For example, a debugger can notify the user when an uncaught exception occurs (i.e. hasHandler is false).
The default implementation does nothing.
See also
exceptionCatch()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 421 of file qscriptengineagent.cpp.
Referenced by QScriptEngineAgentPrivate::exceptionThrow().
 {
     Q_UNUSED(scriptId);
     Q_UNUSED(exception);
     Q_UNUSED(hasHandler);
 }
extension()
QVariant QScriptEngineAgent::extension (Extension extension, const QVariant & argument = QVariant()) virtual
This virtual function can be reimplemented in a QScriptEngineAgent subclass to provide support for extensions.
The optional argument can be provided as input to the extension; the result must be returned in the form of a QVariant. You can call supportsExtension() to check if an extension is supported by the QScriptEngineAgent. By default, no extensions are supported, and this function returns an invalid QVariant.
If you implement the DebuggerInvocationRequest extension, Qt Script will call this function when a debugger statement is encountered in a script. The argument is a QVariantList containing three items: The first item is the scriptId (a qint64), the second item is the line number (an int), and the third item is the column number (an int).
See also
supportsExtension()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 499 of file qscriptengineagent.cpp.
Referenced by QScriptEngineAgentPrivate::didReachBreakpoint(), and QJSDebuggerAgent::extension().
 {
     Q_UNUSED(extension);
     Q_UNUSED(argument);
     return QVariant();
 }
functionEntry()
void QScriptEngineAgent::functionEntry (qint64 scriptId) virtual
This function is called when a script function is called in the engine.
If the script function is not a native Qt Script function, it resides in the script identified by scriptId; otherwise, scriptId is -1.
This function is called just before execution of the script function begins. You can obtain the QScriptContext associated with the function call with QScriptEngine::currentContext(). The arguments passed to the function are available.
Reimplement this function to handle this event. For example, a debugger implementation could reimplement this function (and functionExit()) to keep track of the call stack and provide step-over functionality.
The default implementation does nothing.
See also
functionExit(), positionChange(), QScriptEngine::currentContext()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 343 of file qscriptengineagent.cpp.
 {
     Q_UNUSED(scriptId);
 }
functionExit()
void QScriptEngineAgent::functionExit (qint64 scriptId, const QScriptValue & returnValue) virtual
This function is called when the currently executing script function is about to return.
If the script function is not a native Qt Script function, it resides in the script identified by scriptId; otherwise, scriptId is -1. The returnValue is the value that the script function will return.
This function is called just before the script function returns. You can still access the QScriptContext associated with the script function call with QScriptEngine::currentContext().
If the engine's hasUncaughtException() function returns true, the script function is exiting due to an exception; otherwise, the script function is returning normally.
Reimplement this function to handle this event; typically you will then also want to reimplement functionEntry().
The default implementation does nothing.
See also
functionEntry(), QScriptEngine::hasUncaughtException()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 371 of file qscriptengineagent.cpp.
Referenced by QScriptEngineAgentPrivate::evaluateStop(), and QScriptEngineAgentPrivate::functionExit().
 {
     Q_UNUSED(scriptId);
     Q_UNUSED(returnValue);
 }
positionChange()
void QScriptEngineAgent::positionChange (qint64 scriptId, int lineNumber, int columnNumber) virtual
This function is called when the engine is about to execute a new statement in the script identified by scriptId.
The statement begins on the line and column specified by lineNumber This event is not generated for native Qt Script functions.
Reimplement this function to handle this event. For example, a debugger implementation could reimplement this function to provide line-by-line stepping, and a profiler implementation could use it to count the number of times each statement is executed.
The default implementation does nothing.
Note
columnNumber is undefined
See also
scriptLoad(), functionEntry()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 395 of file qscriptengineagent.cpp.
Referenced by QScriptEngineAgentPrivate::atStatement().
 {
     Q_UNUSED(scriptId);
     Q_UNUSED(lineNumber);
     Q_UNUSED(columnNumber);
 }
scriptLoad()
void QScriptEngineAgent::scriptLoad (qint64 id, const QString & program, const QString & fileName, int baseLineNumber) virtual
This function is called when the engine has parsed a script and has associated it with the given id.
The id can be used to identify this particular script in subsequent event notifications.
program, fileName and baseLineNumber are the original arguments to the QScriptEngine::evaluate() call that triggered this event.
This function is called just before the script is about to be evaluated.
You can reimplement this function to record information about the script; for example, by retaining the script text, you can obtain the line of text corresponding to a line number in a subsequent call to positionChange().
The default implementation does nothing.
See also
scriptUnload()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 275 of file qscriptengineagent.cpp.
 {
     Q_UNUSED(id);
     Q_UNUSED(program);
     Q_UNUSED(fileName);
     Q_UNUSED(baseLineNumber);
 }
scriptUnload()
void QScriptEngineAgent::scriptUnload (qint64 id) virtual
This function is called when the engine has discarded the script identified by the given id.
You can reimplement this function to clean up any resources you have associated with the script.
The default implementation does nothing.
See also
scriptLoad()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 295 of file qscriptengineagent.cpp.
 {
     Q_UNUSED(id);
 }
supportsExtension()
bool QScriptEngineAgent::supportsExtension (Extension extension) const virtual
Returns true if the QScriptEngineAgent supports the given extension; otherwise, false is returned.
By default, no extensions are supported.
See also
extension()
Reimplemented in QJSDebuggerAgent, and QScriptDebuggerAgent.
Definition at line 475 of file qscriptengineagent.cpp.
Referenced by QScriptEngineAgentPrivate::didReachBreakpoint().
 {
     Q_UNUSED(extension);
     return false;
 }
Properties
d_ptr
QScopedPointer<QScriptEngineAgentPrivate> QScriptEngineAgent::d_ptr protected
Definition at line 80 of file qscriptengineagent.h.
Referenced by QScriptEngineAgent(), and ~QScriptEngineAgent().
The documentation for this class was generated from the following files:
/src/script/api/qscriptengineagent.h
/src/script/api/qscriptengineagent.cpp