Qt 4.8: QStylePainter Class Reference
QStylePainter Class Reference
The QStylePainter class is a convenience class for drawing QStyle elements inside a widget.
#include <qstylepainter.h>
Public Functions
bool begin (QWidget *w)
Begin painting operations on the specified widget.
bool begin (QPaintDevice *pd, QWidget *w)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Begin painting operations on paint device pd as if it was widget.
void drawComplexControl (QStyle::ComplexControl cc, const QStyleOptionComplex &opt)
Use the widget's style to draw a complex control cc specified by the QStyleOptionComplex option.
void drawControl (QStyle::ControlElement ce, const QStyleOption &opt)
Use the widget's style to draw a control element ce specified by QStyleOption option.
void drawItemPixmap (const QRect &r, int flags, const QPixmap &pixmap)
Draws the pixmap in rectangle rect.
void drawItemText (const QRect &r, int flags, const QPalette &pal, bool enabled, const QString &text, QPalette::ColorRole textRole=QPalette::NoRole)
void drawPrimitive (QStyle::PrimitiveElement pe, const QStyleOption &opt)
Use the widget's style to draw a primitive element pe specified by QStyleOption option.
QStylePainter ()
Constructs a QStylePainter.
QStylePainter (QWidget *w)
Construct a QStylePainter using widget widget for its paint device.
QStylePainter (QPaintDevice *pd, QWidget *w)
Construct a QStylePainter using pd for its paint device, and attributes from widget.
QStyle * style () const
Return the current style used by the QStylePainter.
Public Functions inherited from QPainter
const QBrush & background () const
Returns the current background brush.
Qt::BGMode backgroundMode () const
Returns the current background mode.
bool begin (QPaintDevice *)
Begins painting the paint device and returns true if successful; otherwise returns false.
void beginNativePainting ()
Flushes the painting pipeline and prepares for the user issuing commands directly to the underlying graphics context.
QRectF boundingRect (const QRectF &rect, int flags, const QString &text)
Returns the bounding rectangle of the text as it will appear when drawn inside the given rectangle with the specified flags using the currently set font(); i.
QRect boundingRect (const QRect &rect, int flags, const QString &text)
Returns the bounding rectangle of the text as it will appear when drawn inside the given rectangle with the specified flags using the currently set font().
QRect boundingRect (int x, int y, int w, int h, int flags, const QString &text)
Returns the bounding rectangle of the given text as it will appear when drawn inside the rectangle beginning at the point ({x}, {y}) with width w and height h.
QRectF boundingRect (const QRectF &rect, const QString &text, const QTextOption &o=QTextOption())
Instead of specifying flags as a bitwise OR of the Qt::AlignmentFlag and Qt::TextFlag, this overloaded function takes an option argument.
const QBrush & brush () const
Returns the painter's current brush.
QPoint brushOrigin () const
Returns the currently set brush origin.
QRectF clipBoundingRect () const
Returns the bounding rectangle of the current clip if there is a clip; otherwise returns an empty rectangle.
QPainterPath clipPath () const
Returns the currently clip as a path.
QRegion clipRegion () const
Returns the currently set clip region.
QMatrix combinedMatrix () const
Returns the transformation matrix combining the current window/viewport and world transformation.
QTransform combinedTransform () const
Returns the transformation matrix combining the current window/viewport and world transformation.
CompositionMode compositionMode () const
Returns the current composition mode.
QPaintDevice * device () const
Returns the paint device on which this painter is currently painting, or 0 if the painter is not active.
const QMatrix & deviceMatrix () const
Returns the matrix that transforms from logical coordinates to device coordinates of the platform dependent paint device.
const QTransform & deviceTransform () const
Returns the matrix that transforms from logical coordinates to device coordinates of the platform dependent paint device.
void drawArc (const QRectF &rect, int a, int alen)
Draws the arc defined by the given rectangle, startAngle and spanAngle.
void drawArc (const QRect &, int a, int alen)
Draws the arc defined by the given rectangle, startAngle and spanAngle.
void drawArc (int x, int y, int w, int h, int a, int alen)
Draws the arc defined by the rectangle beginning at (x, y) with the specified width and height, and the given startAngle and spanAngle.
void drawChord (const QRectF &rect, int a, int alen)
Draws the chord defined by the given rectangle, startAngle and spanAngle.
void drawChord (int x, int y, int w, int h, int a, int alen)
Draws the chord defined by the rectangle beginning at (x, y) with the specified width and height, and the given startAngle and spanAngle.
void drawChord (const QRect &, int a, int alen)
Draws the chord defined by the given rectangle, startAngle and spanAngle.
void drawConvexPolygon (const QPointF *points, int pointCount)
Draws the convex polygon defined by the first pointCount points in the array points using the current pen.
void drawConvexPolygon (const QPolygonF &polygon)
Draws the convex polygon defined by polygon using the current pen and brush.
void drawConvexPolygon (const QPoint *points, int pointCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the convex polygon defined by the first pointCount points in the array points using the current pen.
void drawConvexPolygon (const QPolygon &polygon)
Draws the convex polygon defined by polygon using the current pen and brush.
void drawEllipse (const QRectF &r)
Draws the ellipse defined by the given rectangle.
void drawEllipse (const QRect &r)
Draws the ellipse defined by the given rectangle.
void drawEllipse (int x, int y, int w, int h)
Draws the ellipse defined by the rectangle beginning at ({x}, {y}) with the given width and height.
void drawEllipse (const QPointF &center, qreal rx, qreal ry)
Draws the ellipse positioned at {center} with radii {rx} and {ry}.
void drawEllipse (const QPoint &center, int rx, int ry)
Draws the ellipse positioned at {center} with radii {rx} and {ry}.
void drawGlyphRun (const QPointF &position, const QGlyphRun &glyphRun)
Draws the specified glyphs at the given position.
void drawImage (const QRectF &targetRect, const QImage &image, const QRectF &sourceRect, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QRect &targetRect, const QImage &image, const QRect &sourceRect, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QPointF &p, const QImage &image, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QPoint &p, const QImage &image, const QRect &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawImage (const QRectF &r, const QImage &image)
Draws the given image into the given rectangle.
void drawImage (const QRect &r, const QImage &image)
Draws the given image into the given rectangle.
void drawImage (const QPointF &p, const QImage &image)
Draws the given image at the given point.
void drawImage (const QPoint &p, const QImage &image)
Draws the given image at the given point.
void drawImage (int x, int y, const QImage &image, int sx=0, int sy=0, int sw=-1, int sh=-1, Qt::ImageConversionFlags flags=Qt::AutoColor)
void drawLine (const QLineF &line)
Draws a line defined by line.
void drawLine (const QLine &line)
Draws a line defined by line.
void drawLine (int x1, int y1, int x2, int y2)
Draws a line from (x1, y1) to (x2, y2) and sets the current pen position to (x2, y2).
void drawLine (const QPoint &p1, const QPoint &p2)
Draws a line from p1 to p2.
void drawLine (const QPointF &p1, const QPointF &p2)
Draws a line from p1 to p2.
void drawLines (const QLineF *lines, int lineCount)
Draws the first lineCount lines in the array lines using the current pen.
void drawLines (const QVector< QLineF > &lines)
Draws the set of lines defined by the list lines using the current pen and brush.
void drawLines (const QPointF *pointPairs, int lineCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first lineCount lines in the array pointPairs using the current pen.
void drawLines (const QVector< QPointF > &pointPairs)
Draws a line for each pair of points in the vector pointPairs using the current pen.
void drawLines (const QLine *lines, int lineCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first lineCount lines in the array lines using the current pen.
void drawLines (const QVector< QLine > &lines)
Draws the set of lines defined by the list lines using the current pen and brush.
void drawLines (const QPoint *pointPairs, int lineCount)
Draws the first lineCount lines in the array pointPairs using the current pen.
void drawLines (const QVector< QPoint > &pointPairs)
Draws a line for each pair of points in the vector pointPairs using the current pen.
void drawPath (const QPainterPath &path)
Draws the given painter path using the current pen for outline and the current brush for filling.
void drawPicture (const QPointF &p, const QPicture &picture)
Replays the given picture at the given point.
void drawPicture (int x, int y, const QPicture &picture)
Draws the given picture at point (x, y).
void drawPicture (const QPoint &p, const QPicture &picture)
Replays the given picture at the given point.
void drawPie (const QRectF &rect, int a, int alen)
Draws a pie defined by the given rectangle, startAngle and and spanAngle.
void drawPie (int x, int y, int w, int h, int a, int alen)
void drawPie (const QRect &, int a, int alen)
Draws a pie defined by the given rectangle, startAngle and and spanAngle.
void drawPixmap (const QRectF &targetRect, const QPixmap &pixmap, const QRectF &sourceRect)
Draws the rectangular portion source of the given pixmap into the given target in the paint device.
void drawPixmap (const QRect &targetRect, const QPixmap &pixmap, const QRect &sourceRect)
Draws the rectangular portion source of the given pixmap into the given target in the paint device.
void drawPixmap (int x, int y, int w, int h, const QPixmap &pm, int sx, int sy, int sw, int sh)
Draws the rectangular portion with the origin ({sx}, {sy}), width sw and height sh, of the given pixmap , at the point ({x}, {y}), with a width of w and a height of h.
void drawPixmap (int x, int y, const QPixmap &pm, int sx, int sy, int sw, int sh)
Draws a pixmap at ({x}, {y}) by copying a part of the given pixmap into the paint device.
void drawPixmap (const QPointF &p, const QPixmap &pm, const QRectF &sr)
Draws the rectangular portion source of the given pixmap with its origin at the given point.
void drawPixmap (const QPoint &p, const QPixmap &pm, const QRect &sr)
Draws the rectangular portion source of the given pixmap with its origin at the given point.
void drawPixmap (const QPointF &p, const QPixmap &pm)
Draws the given pixmap with its origin at the given point.
void drawPixmap (const QPoint &p, const QPixmap &pm)
Draws the given pixmap with its origin at the given point.
void drawPixmap (int x, int y, const QPixmap &pm)
Draws the given pixmap at position ({x}, {y}).
void drawPixmap (const QRect &r, const QPixmap &pm)
Draws the given pixmap into the given rectangle.
void drawPixmap (int x, int y, int w, int h, const QPixmap &pm)
Draws the pixmap into the rectangle at position ({x}, {y}) with the given width and height.
void drawPixmapFragments (const PixmapFragment *fragments, int fragmentCount, const QPixmap &pixmap, PixmapFragmentHints hints=0)
This function is used to draw pixmap, or a sub-rectangle of pixmap, at multiple positions with different scale, rotation and opacity.
void drawPixmapFragments (const QRectF *targetRects, const QRectF *sourceRects, int fragmentCount, const QPixmap &pixmap, PixmapFragmentHints hints=0)
This function is used to draw the same pixmap with multiple target and source rectangles specified by targetRects.
void drawPoint (const QPointF &pt)
Draws a single point at the given position using the current pen's color.
void drawPoint (const QPoint &p)
Draws a single point at the given position using the current pen's color.
void drawPoint (int x, int y)
Draws a single point at position (x, y).
void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the array points using the current pen's color.
void drawPoints (const QPolygonF &points)
Draws the points in the vector points.
void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the array points using the current pen's color.
void drawPoints (const QPolygon &points)
Draws the points in the vector points.
void drawPolygon (const QPointF *points, int pointCount, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the first pointCount points in the array points using the current pen and brush.
void drawPolygon (const QPolygonF &polygon, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the given points using the fill rule fillRule.
void drawPolygon (const QPoint *points, int pointCount, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the first pointCount points in the array points.
void drawPolygon (const QPolygon &polygon, Qt::FillRule fillRule=Qt::OddEvenFill)
Draws the polygon defined by the given points using the fill rule fillRule.
void drawPolyline (const QPointF *points, int pointCount)
Draws the polyline defined by the first pointCount points in points using the current pen.
void drawPolyline (const QPolygonF &polyline)
Draws the polyline defined by the given points using the current pen.
void drawPolyline (const QPoint *points, int pointCount)
Draws the polyline defined by the first pointCount points in points using the current pen.
void drawPolyline (const QPolygon &polygon)
Draws the polyline defined by the given points using the current pen.
void drawRect (const QRectF &rect)
Draws the current rectangle with the current pen and brush.
void drawRect (int x1, int y1, int w, int h)
Draws a rectangle with upper left corner at ({x}, {y}) and with the given width and height.
void drawRect (const QRect &rect)
Draws the current rectangle with the current pen and brush.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount of the given rectangles using the current pen and brush.
void drawRects (const QVector< QRectF > &rectangles)
Draws the given rectangles using the current pen and brush.
void drawRects (const QRect *rects, int rectCount)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the first rectCount of the given rectangles using the current pen and brush.
void drawRects (const QVector< QRect > &rectangles)
Draws the given rectangles using the current pen and brush.
void drawRoundedRect (const QRectF &rect, qreal xRadius, qreal yRadius, Qt::SizeMode mode=Qt::AbsoluteSize)
Draws the given rectangle rect with rounded corners.
void drawRoundedRect (int x, int y, int w, int h, qreal xRadius, qreal yRadius, Qt::SizeMode mode=Qt::AbsoluteSize)
void drawRoundedRect (const QRect &rect, qreal xRadius, qreal yRadius, Qt::SizeMode mode=Qt::AbsoluteSize)
void drawRoundRect (const QRectF &r, int xround=25, int yround=25)
Draws a rectangle r with rounded corners.
void drawRoundRect (int x, int y, int w, int h, int=25, int=25)
Draws the rectangle x, y, w, h with rounded corners.
void drawRoundRect (const QRect &r, int xround=25, int yround=25)
Draws the rectangle r with rounded corners.
void drawStaticText (const QPointF &topLeftPosition, const QStaticText &staticText)
Draws the given staticText at the given topLeftPosition.
void drawStaticText (const QPoint &topLeftPosition, const QStaticText &staticText)
Draws the staticText at the topLeftPosition.
void drawStaticText (int left, int top, const QStaticText &staticText)
Draws the staticText at coordinates left and top.
void drawText (const QPointF &p, const QString &s)
Draws the given text with the currently defined text direction, beginning at the given position.
void drawText (const QPoint &p, const QString &s)
Draws the given text with the currently defined text direction, beginning at the given position.
void drawText (int x, int y, const QString &s)
Draws the given text at position ({x}, {y}), using the painter's currently defined text direction.
void drawText (const QPointF &p, const QString &str, int tf, int justificationPadding)
void drawText (const QRectF &r, int flags, const QString &text, QRectF *br=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the provided rectangle.
void drawText (const QRect &r, int flags, const QString &text, QRect *br=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the provided rectangle according to the specified flags.
void drawText (int x, int y, int w, int h, int flags, const QString &text, QRect *br=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Draws the given text within the rectangle with origin ({x}, {y}), width and height.
void drawText (const QRectF &r, const QString &text, const QTextOption &o=QTextOption())
Draws the given text in the rectangle specified using the option to control its positioning and orientation.
void drawTextItem (const QPointF &p, const QTextItem &ti)
Draws the text item ti at position p.
void drawTextItem (int x, int y, const QTextItem &ti)
void drawTextItem (const QPoint &p, const QTextItem &ti)
Draws the text item ti at position p.
void drawTiledPixmap (const QRectF &rect, const QPixmap &pm, const QPointF &offset=QPointF())
Draws a tiled pixmap, inside the given rectangle with its origin at the given position.
void drawTiledPixmap (int x, int y, int w, int h, const QPixmap &, int sx=0, int sy=0)
void drawTiledPixmap (const QRect &, const QPixmap &, const QPoint &=QPoint())
Draws a tiled pixmap, inside the given rectangle with its origin at the given position.
bool end ()
Ends painting.
void endNativePainting ()
Restores the painter after manually issuing native painting commands.
void eraseRect (const QRectF &)
Erases the area inside the given rectangle.
void eraseRect (int x, int y, int w, int h)
Erases the area inside the rectangle beginning at (x, y) with the given width and height.
void eraseRect (const QRect &)
Erases the area inside the given rectangle.
void fillPath (const QPainterPath &path, const QBrush &brush)
Fills the given path using the given brush.
void fillRect (const QRectF &, const QBrush &)
Fills the given rectangle with the brush specified.
void fillRect (int x, int y, int w, int h, const QBrush &)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given brush.
void fillRect (const QRect &, const QBrush &)
Fills the given rectangle with the specified brush.
void fillRect (const QRectF &, const QColor &color)
Fills the given rectangle with the color specified.
void fillRect (int x, int y, int w, int h, const QColor &color)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given color.
void fillRect (const QRect &, const QColor &color)
Fills the given rectangle with the color specified.
void fillRect (int x, int y, int w, int h, Qt::GlobalColor c)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the given color.
void fillRect (const QRect &r, Qt::GlobalColor c)
Fills the given rectangle with the specified color.
void fillRect (const QRectF &r, Qt::GlobalColor c)
Fills the given rectangle with the specified color.
void fillRect (int x, int y, int w, int h, Qt::BrushStyle style)
Fills the rectangle beginning at ({x}, {y}) with the given width and height, using the brush style specified.
void fillRect (const QRect &r, Qt::BrushStyle style)
Fills the given rectangle with the brush style specified.
void fillRect (const QRectF &r, Qt::BrushStyle style)
Fills the given rectangle with the brush style specified.
const QFont & font () const
Returns the currently set font used for drawing text.
QFontInfo fontInfo () const
Returns the font info for the painter if the painter is active.
QFontMetrics fontMetrics () const
Returns the font metrics for the painter if the painter is active.
bool hasClipping () const
Returns true if clipping has been set; otherwise returns false.
void initFrom (const QWidget *widget)
Initializes the painters pen, background and font to the same as the given widget.
bool isActive () const
Returns true if begin() has been called and end() has not yet been called; otherwise returns false.
Qt::LayoutDirection layoutDirection () const
Returns the layout direction used by the painter when drawing text.
const QMatrix & matrix () const
Use worldTransform() instead.
bool matrixEnabled () const
qreal opacity () const
Returns the opacity of the painter.
QPaintEngine * paintEngine () const
Returns the paint engine that the painter is currently operating on if the painter is active; otherwise 0.
const QPen & pen () const
Returns the painter's current pen.
QPainter ()
Constructs a painter.
QPainter (QPaintDevice *)
Constructs a painter that begins painting the paint device immediately.
RenderHints renderHints () const
Returns a flag that specifies the rendering hints that are set for this painter.
void resetMatrix ()
Resets any transformations that were made using translate(), scale(), shear(), rotate(), setWorldMatrix(), setViewport() and setWindow().
void resetTransform ()
Resets any transformations that were made using translate(), scale(), shear(), rotate(), setWorldTransform(), setViewport() and setWindow().
void restore ()
Restores the current painter state (pops a saved state off the stack).
void rotate (qreal a)
Rotates the coordinate system the given angle clockwise.
void save ()
Saves the current painter state (pushes the state onto a stack).
void scale (qreal sx, qreal sy)
Scales the coordinate system by ({sx}, {sy}).
void setBackground (const QBrush &bg)
Sets the background brush of the painter to the given brush.
void setBackgroundMode (Qt::BGMode mode)
Sets the background mode of the painter to the given mode.
void setBrush (const QBrush &brush)
Sets the painter's brush to the given brush.
void setBrush (Qt::BrushStyle style)
Sets the painter's brush to black color and the specified style.
void setBrushOrigin (int x, int y)
Sets the brush's origin to point (x, y).
void setBrushOrigin (const QPoint &)
Sets the brush's origin to the given position.
void setBrushOrigin (const QPointF &)
Sets the brush origin to position.
void setClipPath (const QPainterPath &path, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip path for the painter to the given path, with the clip operation.
void setClipping (bool enable)
Enables clipping if enable is true, or disables clipping if enable is false.
void setClipRect (const QRectF &, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip region to the given rectangle using the given clip operation.
void setClipRect (const QRect &, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip region to the given rectangle using the given clip operation.
void setClipRect (int x, int y, int w, int h, Qt::ClipOperation op=Qt::ReplaceClip)
Enables clipping, and sets the clip region to the rectangle beginning at (x, y) with the given width and height.
void setClipRegion (const QRegion &, Qt::ClipOperation op=Qt::ReplaceClip)
Sets the clip region to the given region using the specified clip operation.
void setCompositionMode (CompositionMode mode)
Sets the composition mode to the given mode.
void setFont (const QFont &f)
Sets the painter's font to the given font.
void setLayoutDirection (Qt::LayoutDirection direction)
Sets the layout direction used by the painter when drawing text, to the specified direction.
void setMatrix (const QMatrix &matrix, bool combine=false)
Use setWorldTransform() instead.
void setMatrixEnabled (bool enabled)
Use setWorldMatrixEnabled() instead.
void setOpacity (qreal opacity)
Sets the opacity of the painter to opacity.
void setPen (const QColor &color)
Sets the painter's pen to have style Qt::SolidLine, width 0 and the specified color.
void setPen (const QPen &pen)
Sets the painter's pen to be the given pen.
void setPen (Qt::PenStyle style)
Sets the painter's pen to have the given style, width 0 and black color.
void setRenderHint (RenderHint hint, bool on=true)
Sets the given render hint on the painter if on is true; otherwise clears the render hint.
void setRenderHints (RenderHints hints, bool on=true)
Sets the given render hints on the painter if on is true; otherwise clears the render hints.
void setTransform (const QTransform &transform, bool combine=false)
Sets the world transformation matrix.
void setViewport (const QRect &viewport)
Sets the painter's viewport rectangle to the given rectangle, and enables view transformations.
void setViewport (int x, int y, int w, int h)
Sets the painter's viewport rectangle to be the rectangle beginning at (x, y) with the given width and height.
void setViewTransformEnabled (bool enable)
Enables view transformations if enable is true, or disables view transformations if enable is false.
void setWindow (const QRect &window)
Sets the painter's window to the given rectangle, and enables view transformations.
void setWindow (int x, int y, int w, int h)
Sets the painter's window to the rectangle beginning at (x, y) and the given width and height.
void setWorldMatrix (const QMatrix &matrix, bool combine=false)
Sets the transformation matrix to matrix and enables transformations.
void setWorldMatrixEnabled (bool enabled)
Enables transformations if enable is true, or disables transformations if enable is false.
void setWorldTransform (const QTransform &matrix, bool combine=false)
Sets the world transformation matrix.
void shear (qreal sh, qreal sv)
Shears the coordinate system by ({sh}, {sv}).
void strokePath (const QPainterPath &path, const QPen &pen)
Draws the outline (strokes) the path path with the pen specified by pen.
bool testRenderHint (RenderHint hint) const
Returns true if hint is set; otherwise returns false.
const QTransform & transform () const
Returns the world transformation matrix.
void translate (const QPointF &offset)
Translates the coordinate system by the given offset; i.e.
void translate (const QPoint &offset)
Translates the coordinate system by the given offset.
void translate (qreal dx, qreal dy)
Translates the coordinate system by the vector (dx, dy).
QRect viewport () const
Returns the viewport rectangle.
bool viewTransformEnabled () const
Returns true if view transformation is enabled; otherwise returns false.
QRect window () const
Returns the window rectangle.
const QMatrix & worldMatrix () const
Returns the world transformation matrix.
bool worldMatrixEnabled () const
Returns true if world transformation is enabled; otherwise returns false.
const QTransform & worldTransform () const
Returns the world transformation matrix.
~QPainter ()
Destroys the painter.
Properties
QWidget * widget
QStyle * wstyle
Additional Inherited Members
Public Types inherited from QPainter
enum CompositionMode {
CompositionMode_SourceOver, CompositionMode_DestinationOver, CompositionMode_Clear, CompositionMode_Source,
CompositionMode_Destination, CompositionMode_SourceIn, CompositionMode_DestinationIn, CompositionMode_SourceOut,
CompositionMode_DestinationOut, CompositionMode_SourceAtop, CompositionMode_DestinationAtop, CompositionMode_Xor,
CompositionMode_Plus, CompositionMode_Multiply, CompositionMode_Screen, CompositionMode_Overlay,
CompositionMode_Darken, CompositionMode_Lighten, CompositionMode_ColorDodge, CompositionMode_ColorBurn,
CompositionMode_HardLight, CompositionMode_SoftLight, CompositionMode_Difference, CompositionMode_Exclusion,
RasterOp_SourceOrDestination, RasterOp_SourceAndDestination, RasterOp_SourceXorDestination, RasterOp_NotSourceAndNotDestination,
RasterOp_NotSourceOrNotDestination, RasterOp_NotSourceXorDestination, RasterOp_NotSource, RasterOp_NotSourceAndDestination,
RasterOp_SourceAndNotDestination
}
Defines the modes supported for digital image compositing.
enum PixmapFragmentHint { OpaqueHint = 0x01 }
enum RenderHint {
Antialiasing = 0x01, TextAntialiasing = 0x02, SmoothPixmapTransform = 0x04, HighQualityAntialiasing = 0x08,
NonCosmeticDefaultPen = 0x10
}
Renderhints are used to specify flags to QPainter that may or may not be respected by any given engine.
Static Public Functions inherited from QPainter
static QPaintDevice * redirected (const QPaintDevice *device, QPoint *offset=0)
Using QWidget::render() obsoletes the use of this function.
static void restoreRedirected (const QPaintDevice *device)
Using QWidget::render() obsoletes the use of this function.
static void setRedirected (const QPaintDevice *device, QPaintDevice *replacement, const QPoint &offset=QPoint())
Please use QWidget::render() instead.
Detailed Description
The QStylePainter class is a convenience class for drawing QStyle elements inside a widget.
QStylePainter extends QPainter with a set of high-level draw...() functions implemented on top of QStyle's API. The advantage of using QStylePainter is that the parameter lists get considerably shorter. Whereas a QStyle object must be able to draw on any widget using any painter (because the application normally has one QStyle object shared by all widget), a QStylePainter is initialized with a widget, eliminating the need to specify the QWidget, the QPainter, and the QStyle for every function call.
Example using QStyle directly:
void MyWidget::paintEvent(QPaintEvent * /* event */)
{
    QPainter painter(this);
    QStyleOptionFocusRect option;
    option.initFrom(this);
    option.backgroundColor = palette().color(QPalette::Background);
    style()->drawPrimitive(QStyle::PE_FrameFocusRect, &option, &painter, this);
}
Example using QStylePainter:
void MyWidget::paintEvent(QPaintEvent * /* event */)
{
    QStylePainter painter(this);
    QStyleOptionFocusRect option;
    option.initFrom(this);
    option.backgroundColor = palette().color(QPalette::Background);
    painter.drawPrimitive(QStyle::PE_FrameFocusRect, option);
}
See also
QStyle, QStyleOption
Definition at line 55 of file qstylepainter.h.
Constructors and Destructors
QStylePainter() [1/3]
QStylePainter::QStylePainter () inline
Constructs a QStylePainter.
Definition at line 58 of file qstylepainter.h.
 : QPainter(), widget(0), wstyle(0) {}
QStylePainter() [2/3]
QStylePainter::QStylePainter (QWidget * w) inline explicit
Construct a QStylePainter using widget widget for its paint device.
Definition at line 59 of file qstylepainter.h.
 { begin(w, w); }
QStylePainter() [3/3]
QStylePainter::QStylePainter (QPaintDevice * pd, QWidget * w) inline
Construct a QStylePainter using pd for its paint device, and attributes from widget.
Definition at line 60 of file qstylepainter.h.
 { begin(pd, w); }
Functions
begin() [1/2]
bool QStylePainter::begin (QWidget * widget) inline
Begin painting operations on the specified widget.
Returns true if the painter is ready to use; otherwise returns false.
This is automatically called by the constructor that takes a QWidget.
Definition at line 61 of file qstylepainter.h.
Referenced by begin().
 { return begin(w, w); }
begin() [2/2]
bool QStylePainter::begin (QPaintDevice * pd, QWidget * widget) inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Begin painting operations on paint device pd as if it was widget.
This is automatically called by the constructor that takes a QPaintDevice and a QWidget.
Definition at line 62 of file qstylepainter.h.
{
         Q_ASSERT_X(w, "QStylePainter::QStylePainter", "Widget must be non-zero");
         widget = w;
         wstyle = w->style();
         return QPainter::begin(pd);
     };
drawComplexControl()
void QStylePainter::drawComplexControl (QStyle::ComplexControl cc, const QStyleOptionComplex & option) inline
Use the widget's style to draw a complex control cc specified by the QStyleOptionComplex option.
See also
QStyle::drawComplexControl()
Definition at line 92 of file qstylepainter.h.
Referenced by QToolBarExtension::paintEvent(), QDial::paintEvent(), QMenuBarExtension::paintEvent(), QGroupBox::paintEvent(), QToolButton::paintEvent(), QMdiSubWindow::paintEvent(), QAbstractSpinBox::paintEvent(), QComboBox::paintEvent(), QFileDialogComboBox::paintEvent(), and QPrevNextCalButton::paintEvent().
 {
     wstyle->drawComplexControl(cc, &opt, this, widget);
 }
drawControl()
void QStylePainter::drawControl (QStyle::ControlElement ce, const QStyleOption & option) inline
Use the widget's style to draw a control element ce specified by QStyleOption option.
See also
QStyle::drawControl()
Definition at line 87 of file qstylepainter.h.
Referenced by QFocusFrame::paintEvent(), QRadioButton::paintEvent(), QCommandLinkButton::paintEvent(), QRubberBand::paintEvent(), QCheckBox::paintEvent(), QPushButton::paintEvent(), QProgressBar::paintEvent(), QDockWidget::paintEvent(), QTabBar::paintEvent(), QComboBox::paintEvent(), QFileDialogComboBox::paintEvent(), and QTabBarPrivate::setupMovableTab().
 {
     wstyle->drawControl(ce, &opt, this, widget);
 }
drawItemPixmap()
void QStylePainter::drawItemPixmap (const QRect & rect, int flags, const QPixmap & pixmap) inline
Draws the pixmap in rectangle rect.
The pixmap is aligned according to flags.
See also
QStyle::drawItemPixmap(), Qt::Alignment
Definition at line 103 of file qstylepainter.h.
 {
     wstyle->drawItemPixmap(this, r, flags, pixmap);
 }
drawItemText()
void QStylePainter::drawItemText (const QRect & r, int flags, const QPalette & pal, bool enabled, const QString & text, QPalette::ColorRole textRole = QPalette::NoRole) inline
Definition at line 97 of file qstylepainter.h.
Referenced by QCommandLinkButton::paintEvent().
 {
     wstyle->drawItemText(this, r, flags, pal, enabled, text, textRole);
 }
drawPrimitive()
void QStylePainter::drawPrimitive (QStyle::PrimitiveElement pe, const QStyleOption & option) inline
Use the widget's style to draw a primitive element pe specified by QStyleOption option.
See also
QStyle::drawPrimitive()
Definition at line 82 of file qstylepainter.h.
Referenced by QDockWidget::paintEvent(), QMdiSubWindow::paintEvent(), QTipLabel::paintEvent(), QTabWidget::paintEvent(), and QTabBar::paintEvent().
 {
     wstyle->drawPrimitive(pe, &opt, this, widget);
 }
style()
QStyle * QStylePainter::style () const inline
Return the current style used by the QStylePainter.
Definition at line 74 of file qstylepainter.h.
 { return wstyle; }
Properties
widget
QWidget* QStylePainter::widget private
Definition at line 77 of file qstylepainter.h.
Referenced by drawComplexControl(), drawControl(), and drawPrimitive().
wstyle
QStyle* QStylePainter::wstyle private
Definition at line 78 of file qstylepainter.h.
Referenced by drawComplexControl(), drawControl(), drawItemPixmap(), drawItemText(), and drawPrimitive().
The documentation for this class was generated from the following files:
/src/gui/painting/qstylepainter.h
/src/gui/painting/qstylepainter.cpp