Qt 4.8: QWindowSystemInterfacePrivate Class Reference
QWindowSystemInterfacePrivate Class Reference
#include <qwindowsysteminterface_qpa_p.h>
Classes
class ActivatedWindowEvent
class CloseEvent
class EnterEvent
class GeometryChangeEvent
class KeyEvent
class LeaveEvent
class LocaleChangeEvent
class MouseEvent
class PlatformPanelEvent
class ScreenAvailableGeometryEvent
class ScreenCountEvent
class ScreenGeometryEvent
class TouchEvent
class UserEvent
class WheelEvent
class WindowStateChangedEvent
class WindowSystemEvent
Public Types
enum EventType {
Close, GeometryChange, Enter, Leave,
ActivatedWindow, WindowStateChanged, Mouse, Wheel,
Key, Touch, ScreenGeometry, ScreenAvailableGeometry,
ScreenCountChange, LocaleChange, PlatformPanel
}
Static Public Functions
static WindowSystemEvent * getWindowSystemEvent ()
static void queueWindowSystemEvent (WindowSystemEvent *ev)
static int windowSystemEventsQueued ()
Static Public Variables
static QTime eventTime
static QMutex queueMutex
static QList< WindowSystemEvent * > windowSystemEventQueue
Detailed Description
Definition at line 50 of file qwindowsysteminterface_qpa_p.h.
Enumerations
EventType
enum QWindowSystemInterfacePrivate::EventType
Enumerator
Close
GeometryChange
Enter
Leave
ActivatedWindow
WindowStateChanged
Mouse
Wheel
Key
Touch
ScreenGeometry
ScreenAvailableGeometry
ScreenCountChange
LocaleChange
PlatformPanel
Definition at line 52 of file qwindowsysteminterface_qpa_p.h.
                    {
         Close,
         GeometryChange,
         Enter,
         Leave,
         ActivatedWindow,
         WindowStateChanged,
         Mouse,
         Wheel,
         Key,
         Touch,
         ScreenGeometry,
         ScreenAvailableGeometry,
         ScreenCountChange,
         LocaleChange,
         PlatformPanel
     };
Functions
getWindowSystemEvent()
QWindowSystemInterfacePrivate::WindowSystemEvent * QWindowSystemInterfacePrivate::getWindowSystemEvent () static
Definition at line 217 of file qwindowsysteminterface_qpa.cpp.
Referenced by QEventDispatcherQPA::processEvents(), sendWindowSystemEvents(), and userEventSourceDispatch().
 {
     queueMutex.lock();
     QWindowSystemInterfacePrivate::WindowSystemEvent *ret;
     if (windowSystemEventQueue.isEmpty())
         ret = 0;
     else
         ret = windowSystemEventQueue.takeFirst();
     queueMutex.unlock();
     return ret;
 }
queueWindowSystemEvent()
void QWindowSystemInterfacePrivate::queueWindowSystemEvent (QWindowSystemInterfacePrivate::WindowSystemEvent * ev) static
Definition at line 229 of file qwindowsysteminterface_qpa.cpp.
Referenced by QWindowSystemInterface::handleCloseEvent(), QWindowSystemInterface::handleEnterEvent(), QWindowSystemInterface::handleExtendedKeyEvent(), QWindowSystemInterface::handleGeometryChange(), QWindowSystemInterface::handleKeyEvent(), QWindowSystemInterface::handleLeaveEvent(), QWindowSystemInterface::handleLocaleChange(), QWindowSystemInterface::handleMouseEvent(), QWindowSystemInterface::handlePlatformPanelEvent(), QWindowSystemInterface::handleScreenAvailableGeometryChange(), QWindowSystemInterface::handleScreenCountChange(), QWindowSystemInterface::handleScreenGeometryChange(), QWindowSystemInterface::handleTouchEvent(), QWindowSystemInterface::handleWheelEvent(), QWindowSystemInterface::handleWindowActivated(), and QWindowSystemInterface::handleWindowStateChanged().
 {
     queueMutex.lock();
     windowSystemEventQueue.append(ev);
     queueMutex.unlock();
     QAbstractEventDispatcher *dispatcher = QApplicationPrivate::qt_qpa_core_dispatcher();
     if (dispatcher)
         dispatcher->wakeUp();
 }
windowSystemEventsQueued()
int QWindowSystemInterfacePrivate::windowSystemEventsQueued () static
Definition at line 209 of file qwindowsysteminterface_qpa.cpp.
Referenced by QEventDispatcherBlackberryQPA::hasPendingEvents(), QEventDispatcherQPA::hasPendingEvents(), QEventDispatcherQPA::processEvents(), sendWindowSystemEvents(), userEventSourceDispatch(), and userEventSourcePrepare().
 {
     queueMutex.lock();
     int ret = windowSystemEventQueue.count();
     queueMutex.unlock();
     return ret;
 }
Properties
eventTime
QTime QWindowSystemInterfacePrivate::eventTime static
Definition at line 229 of file qwindowsysteminterface_qpa_p.h.
Referenced by QWindowSystemInterface::handleExtendedKeyEvent(), QWindowSystemInterface::handleKeyEvent(), QWindowSystemInterface::handleMouseEvent(), QWindowSystemInterface::handleTouchEvent(), and QWindowSystemInterface::handleWheelEvent().
queueMutex
QMutex QWindowSystemInterfacePrivate::queueMutex static
Definition at line 223 of file qwindowsysteminterface_qpa_p.h.
windowSystemEventQueue
QList< QWindowSystemInterfacePrivate::WindowSystemEvent * > QWindowSystemInterfacePrivate::windowSystemEventQueue static
Definition at line 222 of file qwindowsysteminterface_qpa_p.h.
Referenced by qt_cleanup().
The documentation for this class was generated from the following files:
/src/gui/kernel/qwindowsysteminterface_qpa_p.h
/src/gui/kernel/qwindowsysteminterface_qpa.cpp