Qt 4.8: QPatternist::AccelTree::BasicNodeData Class Reference
QPatternist::AccelTree::BasicNodeData Class Reference
Houses data for a node, and that all node kinds have.
#include <qacceltree_p.h>
Public Functions
BasicNodeData ()
BasicNodeData (const PreNumber aDepth, const PreNumber aParent, const QXmlNodeModelIndex::NodeKind k, const PreNumber s, const QXmlName n=QXmlName())
Depth depth () const
bool isCompressed () const
QXmlNodeModelIndex::NodeKind kind () const
QXmlName name () const
PreNumber parent () const
void setSize (const PreNumber aSize)
PreNumber size () const
Properties
Depth m_depth
QXmlNodeModelIndex::NodeKind m_kind: 8
QXmlName m_name
PreNumber m_parent
PreNumber m_size
Detailed Description
Houses data for a node, and that all node kinds have.
BasicNodeData is internal to the Accel tree implementation, and is only used by those classes.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 121 of file qacceltree_p.h.
Constructors and Destructors
BasicNodeData() [1/2]
QPatternist::AccelTree::BasicNodeData::BasicNodeData () inline
Definition at line 125 of file qacceltree_p.h.
             {
             }
BasicNodeData() [2/2]
QPatternist::AccelTree::BasicNodeData::BasicNodeData (const PreNumber aDepth, const PreNumber aParent, const QXmlNodeModelIndex::NodeKind k, const PreNumber s, const QXmlName n = QXmlName()) inline
Definition at line 129 of file qacceltree_p.h.
                                                                 : m_parent(aParent)
                                                                 , m_size(s)
                                                                 , m_name(n)
                                                                 , m_depth(aDepth)
                                                                 , m_kind(k)
             {
             }
Functions
depth()
Depth QPatternist::AccelTree::BasicNodeData::depth () const inline
Definition at line 141 of file qacceltree_p.h.
Referenced by QPatternist::AccelTree::postNumber(), and QPatternist::AccelTree::printStats().
             {
                 return m_depth;
             }
isCompressed()
bool QPatternist::AccelTree::BasicNodeData::isCompressed () const inline
Definition at line 179 of file qacceltree_p.h.
             {
                 Q_ASSERT_X(m_kind == QXmlNodeModelIndex::Text, Q_FUNC_INFO,
                            "Currently, only text nodes are compressed.");
                 /* Note, we don't call size() here, since it has logic for text
                  * nodes. */
                 return m_size == IsCompressed;
             }
kind()
QXmlNodeModelIndex::NodeKind QPatternist::AccelTree::BasicNodeData::kind () const inline
Definition at line 169 of file qacceltree_p.h.
Referenced by QPatternist::AccelTree::printStats().
             {
                 return m_kind;
             }
name()
QXmlName QPatternist::AccelTree::BasicNodeData::name () const inline
Definition at line 174 of file qacceltree_p.h.
Referenced by QPatternist::AccelTree::printStats().
             {
                 return m_name;
             }
parent()
PreNumber QPatternist::AccelTree::BasicNodeData::parent () const inline
Definition at line 146 of file qacceltree_p.h.
             {
                 return m_parent;
             }
setSize()
void QPatternist::AccelTree::BasicNodeData::setSize (const PreNumber aSize) inline
Definition at line 164 of file qacceltree_p.h.
Referenced by QPatternist::AccelTreeBuilder< true >::endElement().
             {
                 m_size = aSize;
             }
size()
PreNumber QPatternist::AccelTree::BasicNodeData::size () const inline
See also
AccelTree::size()
Definition at line 154 of file qacceltree_p.h.
Referenced by QPatternist::AccelTree::postNumber(), and QPatternist::AccelTree::printStats().
             {
                 /* Remember that we use the m_size to signal compression if
                  * we're a text node. */
                 if(m_kind == QXmlNodeModelIndex::Text)
                     return 0;
                 else
                     return m_size;
             }
Properties
m_depth
Depth QPatternist::AccelTree::BasicNodeData::m_depth private
Definition at line 210 of file qacceltree_p.h.
m_kind
QXmlNodeModelIndex::NodeKind QPatternist::AccelTree::BasicNodeData::m_kind private
Technically it is sufficient with 7 bits. However, at least MSVC 2005 miscompiles it such that QXmlNodeModelIndex::Text becomes -64 instead of 64 with hilarious crashes as result.
Fortunately this extra bit would be padded anyway.
Definition at line 219 of file qacceltree_p.h.
m_name
QXmlName QPatternist::AccelTree::BasicNodeData::m_name private
For text nodes, and less importantly, comments, this variable is not used.
Definition at line 208 of file qacceltree_p.h.
m_parent
PreNumber QPatternist::AccelTree::BasicNodeData::m_parent private
This is the pre number of the parent.
Definition at line 192 of file qacceltree_p.h.
m_size
PreNumber QPatternist::AccelTree::BasicNodeData::m_size private
This is the count of children this node has.
In the case of a text node, which cannot have children, it is set to IsCompressed, if the content has been the result of CompressedWhitespace::compress(). If it's not compressed, it is zero.
Definition at line 202 of file qacceltree_p.h.
The documentation for this class was generated from the following file:
/src/xmlpatterns/acceltree/qacceltree_p.h