Qt 4.8: QPatternist::XsdComplexType::OpenContent Class Reference
QPatternist::XsdComplexType::OpenContent Class Reference
Describes the open content object of a complex type.
#include <qxsdcomplextype_p.h>
Public Types
enum Mode { None, Interleave, Suffix }
typedef QExplicitlySharedDataPointer< OpenContent > Ptr
Public Functions
Mode mode () const
void setMode (Mode mode)
void setWildcard (const XsdWildcard::Ptr &wildcard)
XsdWildcard::Ptr wildcard () const
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Properties
Mode m_mode
XsdWildcard::Ptr m_wildcard
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Describes the open content object of a complex type.
See also
Open Content Definition
Definition at line 94 of file qxsdcomplextype_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<OpenContent> QPatternist::XsdComplexType::OpenContent::Ptr
Definition at line 97 of file qxsdcomplextype_p.h.
Enumerations
Mode
enum QPatternist::XsdComplexType::OpenContent::Mode
Describes the mode of the open content.
See also
Mode Definition
Enumerator
None
Interleave
Suffix
Definition at line 104 of file qxsdcomplextype_p.h.
                     {
                         None,
                         Interleave,
                         Suffix
                     };
Functions
mode()
XsdComplexType::OpenContent::Mode XsdComplexType::OpenContent::mode () const
Returns the mode of the open content.
Definition at line 53 of file qxsdcomplextype.cpp.
Referenced by setMode().
 {
     return m_mode;
 }
setMode()
void XsdComplexType::OpenContent::setMode (Mode mode)
Sets the mode of the open content.
See also
Mode Definition
Definition at line 48 of file qxsdcomplextype.cpp.
 {
     m_mode = mode;
 }
setWildcard()
void XsdComplexType::OpenContent::setWildcard (const XsdWildcard::Ptr & wildcard)
Sets the wildcard of the open content.
See also
Wildcard Definition
Definition at line 58 of file qxsdcomplextype.cpp.
 {
     m_wildcard = wildcard;
 }
wildcard()
XsdWildcard::Ptr XsdComplexType::OpenContent::wildcard () const
Returns the wildcard of the open content.
Definition at line 63 of file qxsdcomplextype.cpp.
Referenced by setWildcard(), and QPatternist::XsdComplexType::~XsdComplexType().
 {
     return m_wildcard;
 }
Properties
m_mode
Mode QPatternist::XsdComplexType::OpenContent::m_mode private
Definition at line 136 of file qxsdcomplextype_p.h.
Referenced by mode(), and setMode().
m_wildcard
XsdWildcard::Ptr QPatternist::XsdComplexType::OpenContent::m_wildcard private
Definition at line 137 of file qxsdcomplextype_p.h.
Referenced by setWildcard(), and wildcard().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdcomplextype_p.h
/src/xmlpatterns/schema/qxsdcomplextype.cpp