Qt 4.8: QDeclarativeInclude Class Reference
QDeclarativeInclude Class Reference
#include <qdeclarativeinclude_p.h>
Public Types
enum Status { Ok = 0, Loading = 1, NetworkError = 2, Exception = 3 }
Public Slots
void finished ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QScriptValue callback () const
QDeclarativeInclude (const QUrl &, QDeclarativeEngine *, QScriptContext *ctxt)
QScriptValue result () const
void setCallback (const QScriptValue &)
~QDeclarativeInclude ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void callback (QScriptEngine *, QScriptValue &callback, QScriptValue &status)
static QScriptValue include (QScriptContext *ctxt, QScriptEngine *engine)
static QScriptValue resultValue (QScriptEngine *, Status status=Loading)
static QScriptValue worker_include (QScriptContext *ctxt, QScriptEngine *engine)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Properties
QScriptValue m_callback
QDeclarativeGuardedContextData m_context
QDeclarativeEngine * m_engine
QNetworkAccessManager * m_network
int m_redirectCount
QDeclarativeGuard< QNetworkReply > m_reply
QScriptValue m_result
QScriptValue m_scope [2]
QScriptEngine * m_scriptEngine
QUrl m_url
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 70 of file qdeclarativeinclude_p.h.
Enumerations
Status
enum QDeclarativeInclude::Status
Enumerator
Ok
Loading
NetworkError
Exception
Definition at line 74 of file qdeclarativeinclude_p.h.
                 {
         Ok = 0,
         Loading = 1,
         NetworkError = 2,
         Exception = 3
     };
Constructors and Destructors
QDeclarativeInclude()
QDeclarativeInclude::QDeclarativeInclude (const QUrl & url, QDeclarativeEngine * engine, QScriptContext * ctxt)
Definition at line 54 of file qdeclarativeinclude.cpp.
Referenced by include().
 : QObject(engine), m_engine(engine), m_network(0), m_reply(0), m_url(url), m_redirectCount(0)
 {
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     m_context = ep->contextClass->contextFromValue(QScriptDeclarativeClass::scopeChainValue(ctxt, -3));
     m_scope[0] = QScriptDeclarativeClass::scopeChainValue(ctxt, -4);
     m_scope[1] = QScriptDeclarativeClass::scopeChainValue(ctxt, -5);
     m_scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     m_network = QDeclarativeScriptEngine::get(m_scriptEngine)->networkAccessManager();
     m_result = resultValue(m_scriptEngine);
     QNetworkRequest request;
     request.setUrl(url);
     m_reply = m_network->get(request);
     QObject::connect(m_reply, SIGNAL(finished()), this, SLOT(finished()));
 }
~QDeclarativeInclude()
QDeclarativeInclude::~QDeclarativeInclude ()
Definition at line 77 of file qdeclarativeinclude.cpp.
 {
     delete m_reply;
 }
Functions
callback() [1/2]
QScriptValue QDeclarativeInclude::callback () const
Definition at line 104 of file qdeclarativeinclude.cpp.
Referenced by finished(), include(), and worker_include().
 {
     return m_callback;
 }
callback() [2/2]
void QDeclarativeInclude::callback (QScriptEngine * engine, QScriptValue & callback, QScriptValue & status) static
Definition at line 166 of file qdeclarativeinclude.cpp.
 {
     if (callback.isValid()) {
         QScriptValue args = engine->newArray(1);
         args.setProperty(0, status);
         callback.call(QScriptValue(), args);
     }
 }
finished
void QDeclarativeInclude::finished () slot
Definition at line 110 of file qdeclarativeinclude.cpp.
Referenced by QDeclarativeInclude().
 {
     m_redirectCount++;
     if (m_redirectCount < INCLUDE_MAXIMUM_REDIRECT_RECURSION) {
         QVariant redirect = m_reply->attribute(QNetworkRequest::RedirectionTargetAttribute);
         if (redirect.isValid()) {
             m_url = m_url.resolved(redirect.toUrl());
             delete m_reply;
             QNetworkRequest request;
             request.setUrl(m_url);
             m_reply = m_network->get(request);
             QObject::connect(m_reply, SIGNAL(finished()), this, SLOT(finished()));
             return;
         }
     }
     if (m_reply->error() == QNetworkReply::NoError) {
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(m_engine);
         QByteArray data = m_reply->readAll();
         QString code = QString::fromUtf8(data);
         QString urlString = m_url.toString();
         QScriptContext *scriptContext = QScriptDeclarativeClass::pushCleanContext(m_scriptEngine);
         scriptContext->pushScope(ep->contextClass->newUrlContext(m_context, 0, urlString));
         scriptContext->pushScope(m_scope[0]);
         scriptContext->pushScope(m_scope[1]);
         scriptContext->setActivationObject(m_scope[1]);
         QDeclarativeScriptParser::extractPragmas(code);
         m_scriptEngine->evaluate(code, urlString, 1);
         m_scriptEngine->popContext();
         if (m_scriptEngine->hasUncaughtException()) {
             m_result.setProperty(QLatin1String("status"), QScriptValue(m_scriptEngine, Exception));
             m_result.setProperty(QLatin1String("exception"), m_scriptEngine->uncaughtException());
             m_scriptEngine->clearExceptions();
         } else {
             m_result.setProperty(QLatin1String("status"), QScriptValue(m_scriptEngine, Ok));
         }
     } else {
         m_result.setProperty(QLatin1String("status"), QScriptValue(m_scriptEngine, NetworkError));
     }
     callback(m_scriptEngine, m_callback, m_result);
     disconnect();
     deleteLater();
 }
include()
QScriptValue QDeclarativeInclude::include (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 178 of file qdeclarativeinclude.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if (ctxt->argumentCount() == 0)
         return engine->undefinedValue();
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     QUrl contextUrl = ep->contextClass->urlFromValue(QScriptDeclarativeClass::scopeChainValue(ctxt, -3));
     if (contextUrl.isEmpty())
         return ctxt->throwError(QLatin1String("Qt.include(): Can only be called from JavaScript files"));
     QString urlString = ctxt->argument(0).toString();
     QUrl url(urlString);
     if (url.isRelative()) {
         url = QUrl(contextUrl).resolved(url);
         urlString = url.toString();
     }
     QString localFile = QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url);
     QScriptValue func = ctxt->argument(1);
     if (!func.isFunction())
         func = QScriptValue();
     QScriptValue result;
     if (localFile.isEmpty()) {
         QDeclarativeInclude *i =
             new QDeclarativeInclude(url, QDeclarativeEnginePrivate::getEngine(engine), ctxt);
         if (func.isValid())
             i->setCallback(func);
         result = i->result();
     } else {
         QFile f(localFile);
         if (f.open(QIODevice::ReadOnly)) {
             QByteArray data = f.readAll();
             QString code = QString::fromUtf8(data);
             QDeclarativeContextData *context =
                 ep->contextClass->contextFromValue(QScriptDeclarativeClass::scopeChainValue(ctxt, -3));
             QScriptContext *scriptContext = QScriptDeclarativeClass::pushCleanContext(engine);
             scriptContext->pushScope(ep->contextClass->newUrlContext(context, 0, urlString));
             scriptContext->pushScope(ep->globalClass->staticGlobalObject());
             QScriptValue scope = QScriptDeclarativeClass::scopeChainValue(ctxt, -5);
             scriptContext->pushScope(scope);
             scriptContext->setActivationObject(scope);
             QDeclarativeScriptParser::extractPragmas(code);
             engine->evaluate(code, urlString, 1);
             engine->popContext();
             if (engine->hasUncaughtException()) {
                 result = resultValue(engine, Exception);
                 result.setProperty(QLatin1String("exception"), engine->uncaughtException());
                 engine->clearExceptions();
             } else {
                 result = resultValue(engine, Ok);
             }
             callback(engine, func, result);
         } else {
             result = resultValue(engine, NetworkError);
             callback(engine, func, result);
         }
     }
     return result;
 }
result()
QScriptValue QDeclarativeInclude::result () const
Definition at line 94 of file qdeclarativeinclude.cpp.
Referenced by include(), resultValue(), and worker_include().
 {
     return m_result;
 }
resultValue()
QScriptValue QDeclarativeInclude::resultValue (QScriptEngine * engine, Status status = Loading) static
Definition at line 82 of file qdeclarativeinclude.cpp.
Referenced by include(), QDeclarativeInclude(), and worker_include().
 {
     QScriptValue result = engine->newObject();
     result.setProperty(QLatin1String("OK"), QScriptValue(engine, Ok));
     result.setProperty(QLatin1String("LOADING"), QScriptValue(engine, Loading));
     result.setProperty(QLatin1String("NETWORK_ERROR"), QScriptValue(engine, NetworkError));
     result.setProperty(QLatin1String("EXCEPTION"), QScriptValue(engine, Exception));
     result.setProperty(QLatin1String("status"), QScriptValue(engine, status));
     return result;
 }
setCallback()
void QDeclarativeInclude::setCallback (const QScriptValue & c)
Definition at line 99 of file qdeclarativeinclude.cpp.
Referenced by include().
 {
     m_callback = c;
 }
worker_include()
QScriptValue QDeclarativeInclude::worker_include (QScriptContext * ctxt, QScriptEngine * engine) static
Definition at line 250 of file qdeclarativeinclude.cpp.
Referenced by QDeclarativeScriptEngine::QDeclarativeScriptEngine().
 {
     if (ctxt->argumentCount() == 0)
         return engine->undefinedValue();
     QString urlString = ctxt->argument(0).toString();
     QUrl url(ctxt->argument(0).toString());
     if (url.isRelative()) {
         QString contextUrl = QScriptDeclarativeClass::scopeChainValue(ctxt, -3).data().toString();
         Q_ASSERT(!contextUrl.isEmpty());
         url = QUrl(contextUrl).resolved(url);
         urlString = url.toString();
     }
     QString localFile = QDeclarativeEnginePrivate::urlToLocalFileOrQrc(url);
     QScriptValue func = ctxt->argument(1);
     if (!func.isFunction())
         func = QScriptValue();
     QScriptValue result;
     if (!localFile.isEmpty()) {
         QFile f(localFile);
         if (f.open(QIODevice::ReadOnly)) {
             QByteArray data = f.readAll();
             QString code = QString::fromUtf8(data);
             QScriptContext *scriptContext = QScriptDeclarativeClass::pushCleanContext(engine);
             QScriptValue urlContext = engine->newObject();
             urlContext.setData(QScriptValue(engine, urlString));
             scriptContext->pushScope(urlContext);
             QScriptValue scope = QScriptDeclarativeClass::scopeChainValue(ctxt, -4);
             scriptContext->pushScope(scope);
             scriptContext->setActivationObject(scope);
             QDeclarativeScriptParser::extractPragmas(code);
             engine->evaluate(code, urlString, 1);
             engine->popContext();
             if (engine->hasUncaughtException()) {
                 result = resultValue(engine, Exception);
                 result.setProperty(QLatin1String("exception"), engine->uncaughtException());
                 engine->clearExceptions();
             } else {
                 result = resultValue(engine, Ok);
             }
             callback(engine, func, result);
         } else {
             result = resultValue(engine, NetworkError);
             callback(engine, func, result);
         }
     }
     return result;
 }
Properties
m_callback
QScriptValue QDeclarativeInclude::m_callback private
Definition at line 106 of file qdeclarativeinclude_p.h.
Referenced by callback(), finished(), and setCallback().
m_context
QDeclarativeGuardedContextData QDeclarativeInclude::m_context private
Definition at line 108 of file qdeclarativeinclude_p.h.
Referenced by finished(), and QDeclarativeInclude().
m_engine
QDeclarativeEngine* QDeclarativeInclude::m_engine private
Definition at line 99 of file qdeclarativeinclude_p.h.
Referenced by finished().
m_network
QNetworkAccessManager* QDeclarativeInclude::m_network private
Definition at line 101 of file qdeclarativeinclude_p.h.
Referenced by finished(), and QDeclarativeInclude().
m_redirectCount
int QDeclarativeInclude::m_redirectCount private
Definition at line 105 of file qdeclarativeinclude_p.h.
Referenced by finished().
m_reply
QDeclarativeGuard<QNetworkReply> QDeclarativeInclude::m_reply private
Definition at line 102 of file qdeclarativeinclude_p.h.
Referenced by finished(), QDeclarativeInclude(), and ~QDeclarativeInclude().
m_result
QScriptValue QDeclarativeInclude::m_result private
Definition at line 107 of file qdeclarativeinclude_p.h.
Referenced by finished(), QDeclarativeInclude(), and result().
m_scope
QScriptValue QDeclarativeInclude::m_scope[2] private
Definition at line 109 of file qdeclarativeinclude_p.h.
Referenced by finished(), and QDeclarativeInclude().
m_scriptEngine
QScriptEngine* QDeclarativeInclude::m_scriptEngine private
Definition at line 100 of file qdeclarativeinclude_p.h.
Referenced by finished(), and QDeclarativeInclude().
m_url
QUrl QDeclarativeInclude::m_url private
Definition at line 104 of file qdeclarativeinclude_p.h.
Referenced by finished().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeinclude_p.h
/src/declarative/qml/qdeclarativeinclude.cpp