Qt 4.8: QPatternist::VariableDeclaration Class Reference
QPatternist::VariableDeclaration Class Reference
Represents a declared variable. Only used at the compilation stage.
#include <qvariabledeclaration_p.h>
Public Types
typedef QHash< QXmlName, VariableDeclaration::Ptr > Hash
The key is the variable name.
typedef QList< VariableDeclaration::Ptr > List
typedef QExplicitlySharedDataPointer< VariableDeclaration > Ptr
typedef QStack< VariableDeclaration::Ptr > Stack
enum Type {
RangeVariable, ExpressionVariable, FunctionArgument, PositionalVariable,
TemplateParameter, GlobalVariable, ExternalVariable
}
Public Functions
const Expression::Ptr & expression () const
bool isUsed () const
void setExpression (const Expression::Ptr &expr)
bool usedByMany () const
Returns how many times this variable is used.
VariableDeclaration (const QXmlName n, const VariableSlotID varSlot, const Type t, const SequenceType::Ptr &seqType)
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static bool contains (const VariableDeclaration::List &list, const QXmlName &lookup)
Returns true if list contains lookup.
Public Variables
bool canSourceRewrite
Whether a reference can rewrite itself to expression().
const QXmlName name
VariableReference::List references
const SequenceType::Ptr sequenceType
const VariableSlotID slot
const Type type
Public Variables inherited from QSharedData
QAtomicInt ref
Properties
Expression::Ptr m_expression
Related Functions
(Note that these are not member functions.)
static QString formatKeyword (const VariableDeclaration::Ptr &var, const NamePool::Ptr &np)
Formats var appropriately for display.
Detailed Description
Represents a declared variable. Only used at the compilation stage.
See also
FunctionArgument
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 77 of file qvariabledeclaration_p.h.
Typedefs
Hash
typedef QHash<QXmlName, VariableDeclaration::Ptr> QPatternist::VariableDeclaration::Hash
The key is the variable name.
Definition at line 87 of file qvariabledeclaration_p.h.
List
typedef QList<VariableDeclaration::Ptr> QPatternist::VariableDeclaration::List
Definition at line 82 of file qvariabledeclaration_p.h.
Ptr
typedef QExplicitlySharedDataPointer<VariableDeclaration> QPatternist::VariableDeclaration::Ptr
Definition at line 80 of file qvariabledeclaration_p.h.
Stack
typedef QStack<VariableDeclaration::Ptr> QPatternist::VariableDeclaration::Stack
Definition at line 81 of file qvariabledeclaration_p.h.
Enumerations
Type
enum QPatternist::VariableDeclaration::Type
Enumerator
RangeVariable
ExpressionVariable
FunctionArgument
PositionalVariable
TemplateParameter
GlobalVariable
A global variable is always an external variable, but it is cached differently.
See also
DynamicContext::globalItemCacheCell()
ExternalVariable
External variables doesn't use slots, that's a big difference compared to the other types.
Definition at line 89 of file qvariabledeclaration_p.h.
         {
             RangeVariable,
             ExpressionVariable,
             FunctionArgument,
             PositionalVariable,
             TemplateParameter,
             GlobalVariable,
             ExternalVariable
         };
Constructors and Destructors
VariableDeclaration()
QPatternist::VariableDeclaration::VariableDeclaration (const QXmlName n, const VariableSlotID varSlot, const Type t, const SequenceType::Ptr & seqType) inline
Creates a VariableDeclaration.
sourceExpr and seqType may be null.
Definition at line 117 of file qvariabledeclaration_p.h.
                                                             : name(n)
                                                               , slot(varSlot)
                                                               , type(t)
                                                               , sequenceType(seqType)
                                                               , canSourceRewrite(true)
         {
             Q_ASSERT(!name.isNull());
             Q_ASSERT(t == ExternalVariable || t == TemplateParameter || varSlot > -1);
         }
Functions
contains()
bool VariableDeclaration::contains (const VariableDeclaration::List & list, const QXmlName & lookup) static
Returns true if list contains lookup.
Definition at line 48 of file qvariabledeclaration.cpp.
Referenced by QPatternist::CallTemplate::typeCheck(), usedByMany(), and QPatternist::yyparse().
 {
     VariableDeclaration::List::const_iterator it(list.constBegin());
     const VariableDeclaration::List::const_iterator end(list.constEnd());
     for(; it != end; ++it)
     {
         if((*it)->name == lookup)
             return true;
     }
     return false;
 }
expression()
const Expression::Ptr& QPatternist::VariableDeclaration::expression () const inline
Definition at line 135 of file qvariabledeclaration_p.h.
Referenced by QPatternist::TemplateParameterReference::sourceExpression(), QPatternist::ExpressionVariableReference::sourceExpression(), QPatternist::ExpressionVariableReference::staticType(), and QPatternist::ExpressionVariableReference::typeCheck().
         {
             return m_expression;
         }
isUsed()
bool QPatternist::VariableDeclaration::isUsed () const inline
Definition at line 130 of file qvariabledeclaration_p.h.
         {
             return !references.isEmpty();
         }
setExpression()
void QPatternist::VariableDeclaration::setExpression (const Expression::Ptr & expr) inline
Definition at line 140 of file qvariabledeclaration_p.h.
         {
             m_expression = expr;
         }
usedByMany()
bool QPatternist::VariableDeclaration::usedByMany () const inline
Returns how many times this variable is used.
Definition at line 148 of file qvariabledeclaration_p.h.
         {
             return references.count() > 1;
         }
Friends and Related Functions
formatKeyword()
static QString formatKeyword (const VariableDeclaration::Ptr & var, const NamePool::Ptr & np) related
Formats var appropriately for display.
Definition at line 189 of file qvariabledeclaration_p.h.
Referenced by QPatternist::AbstractFloatMathematician< isDouble >::calculate(), and QPatternist::ComparisonPlatform< IndexOfIterator, false >::fetchComparator().
     {
         Q_ASSERT(var);
         Q_ASSERT(np);
         return formatKeyword(np->displayName(var->name));
     }
Properties
canSourceRewrite
bool QPatternist::VariableDeclaration::canSourceRewrite
Whether a reference can rewrite itself to expression().
The default value is true.
Definition at line 177 of file qvariabledeclaration_p.h.
Referenced by QPatternist::ExpressionVariableReference::typeCheck().
m_expression
Expression::Ptr QPatternist::VariableDeclaration::m_expression private
Definition at line 180 of file qvariabledeclaration_p.h.
Referenced by expression(), and setExpression().
name
const QXmlName QPatternist::VariableDeclaration::name
Definition at line 159 of file qvariabledeclaration_p.h.
Referenced by QPatternist::TemplateParameterReference::evaluateEBV(), QPatternist::TemplateParameterReference::evaluateSequence(), QPatternist::TemplateParameterReference::evaluateSingleton(), and VariableDeclaration().
references
VariableReference::List QPatternist::VariableDeclaration::references
Definition at line 170 of file qvariabledeclaration_p.h.
Referenced by isUsed(), and usedByMany().
sequenceType
const SequenceType::Ptr QPatternist::VariableDeclaration::sequenceType
The declared type of the variable. What the value might be, depends on the context which VariableDeclaration is used in. Note that sequenceType is hence not in anyway obligated to the type of expression().
Definition at line 169 of file qvariabledeclaration_p.h.
Referenced by QPatternist::TemplateParameterReference::staticType().
slot
const VariableSlotID QPatternist::VariableDeclaration::slot
Definition at line 160 of file qvariabledeclaration_p.h.
type
const Type QPatternist::VariableDeclaration::type
Definition at line 161 of file qvariabledeclaration_p.h.
Referenced by QPatternist::checkVariableCircularity().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qvariabledeclaration_p.h
/src/xmlpatterns/expr/qvariabledeclaration.cpp