Qt 4.8: QmlJSDebugger::LiveSingleSelectionManipulator Class Reference
QmlJSDebugger::LiveSingleSelectionManipulator Class Reference
#include <livesingleselectionmanipulator.h>
Public Types
enum SelectionType { ReplaceSelection, AddToSelection, RemoveFromSelection, InvertSelection }
Public Functions
void begin (const QPointF &beginPoint)
QPointF beginPoint () const
void clear ()
void end (const QPointF &updatePoint)
bool isActive () const
LiveSingleSelectionManipulator (QDeclarativeViewInspector *editorView)
void select (SelectionType selectionType, const QList< QGraphicsItem *> &items, bool selectOnlyContentItems)
void select (SelectionType selectionType, bool selectOnlyContentItems)
void update (const QPointF &updatePoint)
Properties
QPointF m_beginPoint
QDeclarativeViewInspector * m_editorView
bool m_isActive
QList< QGraphicsItem * > m_oldSelectionList
Detailed Description
Definition at line 54 of file livesingleselectionmanipulator.h.
Enumerations
SelectionType
enum QmlJSDebugger::LiveSingleSelectionManipulator::SelectionType
Enumerator
ReplaceSelection
AddToSelection
RemoveFromSelection
InvertSelection
Definition at line 59 of file livesingleselectionmanipulator.h.
{
         ReplaceSelection,
         AddToSelection,
         RemoveFromSelection,
         InvertSelection
     };
Constructors and Destructors
LiveSingleSelectionManipulator()
QmlJSDebugger::LiveSingleSelectionManipulator::LiveSingleSelectionManipulator (QDeclarativeViewInspector * editorView)
Definition at line 50 of file livesingleselectionmanipulator.cpp.
     : m_editorView(editorView),
       m_isActive(false)
 {
 }
Functions
begin()
void QmlJSDebugger::LiveSingleSelectionManipulator::begin (const QPointF & beginPoint)
Definition at line 57 of file livesingleselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::contextMenuElementSelected(), QmlJSDebugger::LiveSelectionTool::mousePressEvent(), QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent(), QmlJSDebugger::LiveSelectionTool::selectUnderPoint(), and QmlJSDebugger::LiveSelectionTool::wheelEvent().
 {
     m_beginPoint = beginPoint;
     m_isActive = true;
     m_oldSelectionList = QDeclarativeViewInspectorPrivate::get(m_editorView)->selectedItems();
 }
beginPoint()
QPointF QmlJSDebugger::LiveSingleSelectionManipulator::beginPoint () const
Definition at line 146 of file livesingleselectionmanipulator.cpp.
Referenced by begin(), and QmlJSDebugger::LiveSelectionTool::mouseMoveEvent().
 {
     return m_beginPoint;
 }
clear()
void QmlJSDebugger::LiveSingleSelectionManipulator::clear (void)
Definition at line 69 of file livesingleselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::clear().
 {
     m_beginPoint = QPointF();
     m_oldSelectionList.clear();
 }
end()
void QmlJSDebugger::LiveSingleSelectionManipulator::end (const QPointF & updatePoint)
Definition at line 76 of file livesingleselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::contextMenuElementSelected(), QmlJSDebugger::LiveSelectionTool::mouseMoveEvent(), QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent(), QmlJSDebugger::LiveSelectionTool::selectUnderPoint(), and QmlJSDebugger::LiveSelectionTool::wheelEvent().
 {
     m_oldSelectionList.clear();
     m_isActive = false;
 }
isActive()
bool QmlJSDebugger::LiveSingleSelectionManipulator::isActive () const
Definition at line 141 of file livesingleselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::mouseMoveEvent(), and QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent().
 {
     return m_isActive;
 }
select() [1/2]
void QmlJSDebugger::LiveSingleSelectionManipulator::select (SelectionType selectionType, const QList< QGraphicsItem *> & items, bool selectOnlyContentItems)
Definition at line 82 of file livesingleselectionmanipulator.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::contextMenuElementSelected(), QmlJSDebugger::LiveSelectionTool::mousePressEvent(), QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent(), select(), QmlJSDebugger::LiveSelectionTool::selectUnderPoint(), and QmlJSDebugger::LiveSelectionTool::wheelEvent().
 {
     QGraphicsItem *selectedItem = 0;
     foreach (QGraphicsItem* item, items)
     {
         //FormEditorItem *formEditorItem = FormEditorItem::fromQGraphicsItem(item);
         if (item
             /*&& !formEditorItem->qmlItemNode().isRootNode()
                && (formEditorItem->qmlItemNode().hasShowContent() || !selectOnlyContentItems)*/)
         {
             selectedItem = item;
             break;
         }
     }
     QList<QGraphicsItem*> resultList;
     switch (selectionType) {
     case AddToSelection: {
         resultList.append(m_oldSelectionList);
         if (selectedItem && !m_oldSelectionList.contains(selectedItem))
             resultList.append(selectedItem);
     }
         break;
     case ReplaceSelection: {
         if (selectedItem)
             resultList.append(selectedItem);
     }
         break;
     case RemoveFromSelection: {
         resultList.append(m_oldSelectionList);
         if (selectedItem)
             resultList.removeAll(selectedItem);
     }
         break;
     case InvertSelection: {
         if (selectedItem
                 && !m_oldSelectionList.contains(selectedItem))
         {
             resultList.append(selectedItem);
         }
     }
     }
     m_editorView->setSelectedItems(resultList);
 }
select() [2/2]
void QmlJSDebugger::LiveSingleSelectionManipulator::select (SelectionType selectionType, bool selectOnlyContentItems)
Definition at line 132 of file livesingleselectionmanipulator.cpp.
 {
     QDeclarativeViewInspectorPrivate *inspectorPrivate =
             QDeclarativeViewInspectorPrivate::get(m_editorView);
     QList<QGraphicsItem*> itemList = inspectorPrivate->selectableItems(m_beginPoint);
     select(selectionType, itemList, selectOnlyContentItems);
 }
update()
void QmlJSDebugger::LiveSingleSelectionManipulator::update (const QPointF & updatePoint)
Definition at line 64 of file livesingleselectionmanipulator.cpp.
 {
     m_oldSelectionList.clear();
 }
Properties
m_beginPoint
QPointF QmlJSDebugger::LiveSingleSelectionManipulator::m_beginPoint private
Definition at line 82 of file livesingleselectionmanipulator.h.
Referenced by begin(), beginPoint(), clear(), and select().
m_editorView
QDeclarativeViewInspector* QmlJSDebugger::LiveSingleSelectionManipulator::m_editorView private
Definition at line 83 of file livesingleselectionmanipulator.h.
Referenced by begin(), and select().
m_isActive
bool QmlJSDebugger::LiveSingleSelectionManipulator::m_isActive private
Definition at line 84 of file livesingleselectionmanipulator.h.
Referenced by begin(), end(), and isActive().
m_oldSelectionList
QList<QGraphicsItem*> QmlJSDebugger::LiveSingleSelectionManipulator::m_oldSelectionList private
Definition at line 81 of file livesingleselectionmanipulator.h.
Referenced by begin(), clear(), end(), select(), and update().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/livesingleselectionmanipulator.h
/src/plugins/qmltooling/qmldbg_inspector/editor/livesingleselectionmanipulator.cpp