Qt 4.8: QAbstractXmlForwardIterator< T > Class Template Reference
QAbstractXmlForwardIterator< T > Class Template Reference abstract
The QAbstractXmlForwardIterator class is a base class for forward iterators.
#include <qabstractxmlforwarditerator_p.h>
Public Types
typedef QList< QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< T > > > List
A QList containing QAbstractXmlForwardIterator::Ptr instances.
typedef QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< T > > Ptr
A smart pointer wrapping an instance of a QAbstractXmlForwardIterator subclass.
typedef QVector< QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< T > > > Vector
A QVector containing QAbstractXmlForwardIterator::Ptr instances.
Public Functions
virtual QAbstractXmlForwardIterator< T >::Ptr copy () const
Copies this QAbstractXmlForwardIterator and returns the copy.
virtual qint64 count ()
Determines the number of items this QAbstractXmlForwardIterator represents.
virtual T current () const =0
Returns the current item in the sequence.
virtual bool isEmpty ()
Returns true if the sequence is empty.
virtual T last ()
Returns the item at the end of this QAbstractXmlForwardIterator.
virtual T next ()=0
Returns the next item in the sequence, or a null object if the end has been reached.
virtual qint64 position () const =0
Returns the current position in the sequence represented by this.
QAbstractXmlForwardIterator ()
Default constructor.
virtual qint64 sizeHint () const
Gives a hint to the size of the contained sequence.
virtual QList< T > toList ()
Performs a copy of this QAbstractXmlForwardIterator(with copy()), and returns its items in a QList.
virtual QAbstractXmlForwardIterator< T >::Ptr toReversed ()
Returns a reverse iterator for the sequence.
virtual ~QAbstractXmlForwardIterator ()
Destructor.
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Properties
QAbstractXmlForwardIteratorPrivate * d_ptr
Related Functions
(Note that these are not member functions.)
template<typename TResult , typename TSource , typename TMapper >
static QAbstractXmlForwardIterator< TResult >::Ptr makeSequenceMappingIterator (const TMapper &mapper, const QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< TSource > > &source, const DynamicContext::Ptr &context)
An object generator for SequenceMappingIterator.
bool qIsForwardIteratorEnd (const T &unit)
The Callback QAbstractXmlForwardIterator uses for determining whether unit is the end of a sequence.
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
template<typename T>
class QAbstractXmlForwardIterator< T >
The QAbstractXmlForwardIterator class is a base class for forward iterators.
Note
This class or function is reentrant.
Since
4.4
Warning
This function is not part of the public interface.
This abstract base class is for creating iterators for traversing custom data structures modeled to look like XML. An item can be instantiated in QAbstractXmlForwardIterator if:
It has a default constructor, a copy constructor, and an assignment operator, and
It has an appropriate qIsForwardIteratorEnd() function.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 90 of file qabstractxmlforwarditerator_p.h.
Typedefs
List
template<typename T> QAbstractXmlForwardIterator< T >::List
A QList containing QAbstractXmlForwardIterator::Ptr instances.
Definition at line 99 of file qabstractxmlforwarditerator_p.h.
Ptr
template<typename T> QAbstractXmlForwardIterator< T >::Ptr
A smart pointer wrapping an instance of a QAbstractXmlForwardIterator subclass.
Definition at line 98 of file qabstractxmlforwarditerator_p.h.
Vector
template<typename T> QAbstractXmlForwardIterator< T >::Vector
A QVector containing QAbstractXmlForwardIterator::Ptr instances.
Definition at line 100 of file qabstractxmlforwarditerator_p.h.
Constructors and Destructors
QAbstractXmlForwardIterator()
template<typename T> QAbstractXmlForwardIterator< T >::QAbstractXmlForwardIterator () inline
Default constructor.
Definition at line 102 of file qabstractxmlforwarditerator_p.h.
 : d_ptr(0) {}
~QAbstractXmlForwardIterator()
template<typename T> QAbstractXmlForwardIterator< T >::~QAbstractXmlForwardIterator () inline virtual
Destructor.
Definition at line 103 of file qabstractxmlforwarditerator_p.h.
 {}
Functions
copy()
template<typename T > QAbstractXmlForwardIterator< T >::Ptr QAbstractXmlForwardIterator< T >::copy () const virtual
Copies this QAbstractXmlForwardIterator and returns the copy.
Warning
This function is not part of the public interface.
A copy and the original instance are completely independent of each other. Because evaluating an QAbstractXmlForwardIterator modifies it, one should always use a copy when an QAbstractXmlForwardIterator needs to be used several times.
Reimplemented in QPatternist::IteratorVector, QPatternist::AttributeIterator, QPatternist::PrecedingIterator, QPatternist::FollowingIterator, QPatternist::DescendantIterator< IncludeSelf >, QPatternist::SiblingIterator< IsFollowing >, QPatternist::ChildIterator, QPatternist::ListIteratorPlatform< InputType, OutputType, Derived, ListType >, QPatternist::ListIteratorPlatform< QVariant, Item, VariantListIterator >, QPatternist::ListIteratorPlatform< QString, Item, StringListIterator >, QPatternist::ListIteratorPlatform< T, T, ListIterator< T, ListType >, ListType >, QPatternist::ItemMappingIterator< TResult, TSource, TMapper, Context >, QPatternist::AncestorIterator< IncludeSelf >, QPatternist::SingletonIterator< T >, QPatternist::EmptyIterator< T >, QPatternist::EmptyIterator< QPatternist::Item >, QPatternist::RangeIterator, QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >, QPatternist::RemovalIterator, QPatternist::DistinctIterator, QPatternist::IndexOfIterator, QPatternist::InsertionIterator, QPatternist::SubsequenceIterator, QPatternist::CachingIterator, QPatternist::ToCodepointsIterator, QPatternist::DeduplicateIterator, QPatternist::IntersectIterator, QPatternist::ExceptIterator, and QPatternist::UnionIterator.
Definition at line 317 of file qabstractxmlforwarditerator_p.h.
Referenced by QPatternist::AttributeIterator::AttributeIterator(), QPatternist::ChildIterator::ChildIterator(), QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >::copy(), QPatternist::ItemMappingIterator< TResult, TSource, TMapper, Context >::copy(), QPatternist::FollowingIterator::FollowingIterator(), QPatternist::PrecedingIterator::PrecedingIterator(), and QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "This function is internal, unsupported, and should never be called.");
     return typename QAbstractXmlForwardIterator<T>::Ptr();
 }
count()
template<typename T > qint64 QAbstractXmlForwardIterator< T >::count () virtual
Determines the number of items this QAbstractXmlForwardIterator represents.
Warning
This function is not part of the public interface.
Note that this function is not const. It modifies the QAbstractXmlForwardIterator. The reason for this is efficiency. If this QAbstractXmlForwardIterator must not be changed, get a copy() before performing the count.
The default implementation simply calls next() until the end is reached. Hence, it may be of interest to override this function if the sub-class knows a better way of computing its count.
The number of items in the sequence is returned.
Reimplemented in QPatternist::ListIteratorPlatform< InputType, OutputType, Derived, ListType >, QPatternist::ListIteratorPlatform< QVariant, Item, VariantListIterator >, QPatternist::ListIteratorPlatform< QString, Item, StringListIterator >, QPatternist::ListIteratorPlatform< T, T, ListIterator< T, ListType >, ListType >, QPatternist::SingletonIterator< T >, QPatternist::RangeIterator, QPatternist::EmptyIterator< T >, QPatternist::EmptyIterator< QPatternist::Item >, QPatternist::RemovalIterator, QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >, QPatternist::InsertionIterator, QPatternist::ToCodepointsIterator, and QPatternist::DeduplicateIterator.
Definition at line 280 of file qabstractxmlforwarditerator_p.h.
Referenced by QPatternist::DeduplicateIterator::count(), QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >::count(), and QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
 {
     qint64 retval = 0;
     while(!qIsForwardIteratorEnd(next()))
         ++retval;
     return retval;
 }
current()
template<typename T> T QAbstractXmlForwardIterator< T >::current () const pure virtual
Returns the current item in the sequence.
If this function is called before the first call to next(), a null object is returned. If the end of the sequence has been reached, a null object is returned.
Implemented in QPatternist::ListIteratorPlatform< InputType, OutputType, Derived, ListType >, QPatternist::ListIteratorPlatform< QVariant, Item, VariantListIterator >, QPatternist::ListIteratorPlatform< QString, Item, StringListIterator >, QPatternist::ListIteratorPlatform< T, T, ListIterator< T, ListType >, ListType >, QPatternist::ItemMappingIterator< TResult, TSource, TMapper, Context >, QPatternist::RangeIterator, QPatternist::SingletonIterator< T >, QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >, QPatternist::DistinctIterator, QPatternist::IndexOfIterator, QPatternist::InsertionIterator, QPatternist::RemovalIterator, QPatternist::SubsequenceIterator, StringSplitter, QPatternist::CachingIterator, QPatternist::EmptyIterator< T >, QPatternist::EmptyIterator< QPatternist::Item >, QPatternist::ToCodepointsIterator, QPatternist::IntersectIterator, QPatternist::ExceptIterator, QPatternist::UnionIterator, and QPatternist::AccelIterator.
Referenced by QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
isEmpty()
template<typename T > bool QAbstractXmlForwardIterator< T >::isEmpty () virtual
Returns true if the sequence is empty.
Warning
This function is not part of the public interface.
Definition at line 325 of file qabstractxmlforwarditerator_p.h.
Referenced by QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
 {
     return qIsForwardIteratorEnd(next());
 }
last()
template<typename T > T QAbstractXmlForwardIterator< T >::last () virtual
Returns the item at the end of this QAbstractXmlForwardIterator.
Warning
This function is not part of the public interface.
The default implementation calls next() until the end is reached.
Definition at line 306 of file qabstractxmlforwarditerator_p.h.
Referenced by QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
 {
     T item(next());
     while(!qIsForwardIteratorEnd(item))
         item = next();
     return item;
 }
next()
template<typename T> T QAbstractXmlForwardIterator< T >::next () pure virtual
Returns the next item in the sequence, or a null object if the end has been reached.
Implemented in QPatternist::AttributeIterator, QPatternist::PrecedingIterator, QPatternist::FollowingIterator, QPatternist::DescendantIterator< IncludeSelf >, QPatternist::SiblingIterator< IsFollowing >, QPatternist::ChildIterator, QPatternist::ListIteratorPlatform< InputType, OutputType, Derived, ListType >, QPatternist::ListIteratorPlatform< QVariant, Item, VariantListIterator >, QPatternist::ListIteratorPlatform< QString, Item, StringListIterator >, QPatternist::ListIteratorPlatform< T, T, ListIterator< T, ListType >, ListType >, QPatternist::AncestorIterator< IncludeSelf >, QPatternist::ItemMappingIterator< TResult, TSource, TMapper, Context >, QPatternist::RangeIterator, QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >, QPatternist::DistinctIterator, QPatternist::IndexOfIterator, QPatternist::InsertionIterator, QPatternist::RemovalIterator, QPatternist::SubsequenceIterator, QPatternist::SingletonIterator< T >, StringSplitter, QPatternist::CachingIterator, QPatternist::ToCodepointsIterator, QPatternist::DeduplicateIterator, QPatternist::EmptyIterator< T >, QPatternist::EmptyIterator< QPatternist::Item >, QPatternist::IntersectIterator, QPatternist::ExceptIterator, and QPatternist::UnionIterator.
Referenced by QPatternist::AttributeIterator::AttributeIterator(), QPatternist::ChildIterator::ChildIterator(), QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >::count(), QAbstractXmlForwardIterator< OutputType >::count(), QPatternist::FollowingIterator::FollowingIterator(), QAbstractXmlForwardIterator< OutputType >::isEmpty(), QAbstractXmlForwardIterator< OutputType >::last(), QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >::next(), QPatternist::ItemMappingIterator< TResult, TSource, TMapper, Context >::next(), QPatternist::PrecedingIterator::PrecedingIterator(), QAbstractXmlForwardIterator< OutputType >::toList(), QAbstractXmlForwardIterator< OutputType >::toReversed(), and QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
position()
template<typename T> qint64 QAbstractXmlForwardIterator< T >::position () const pure virtual
Returns the current position in the sequence represented by this.
The first position is 1, not 0. If next() hasn't been called, 0 is returned. If this has reached the end, -1 is returned.
Implemented in QPatternist::ListIteratorPlatform< InputType, OutputType, Derived, ListType >, QPatternist::ListIteratorPlatform< QVariant, Item, VariantListIterator >, QPatternist::ListIteratorPlatform< QString, Item, StringListIterator >, QPatternist::ListIteratorPlatform< T, T, ListIterator< T, ListType >, ListType >, QPatternist::ItemMappingIterator< TResult, TSource, TMapper, Context >, QPatternist::SingletonIterator< T >, QPatternist::RangeIterator, QPatternist::SequenceMappingIterator< TResult, TSource, TMapper >, QPatternist::DistinctIterator, QPatternist::IndexOfIterator, QPatternist::InsertionIterator, QPatternist::RemovalIterator, QPatternist::SubsequenceIterator, QPatternist::EmptyIterator< T >, QPatternist::EmptyIterator< QPatternist::Item >, StringSplitter, QPatternist::CachingIterator, QPatternist::ToCodepointsIterator, QPatternist::IntersectIterator, QPatternist::ExceptIterator, QPatternist::UnionIterator, and QPatternist::AccelIterator.
Referenced by QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
sizeHint()
template<typename T > qint64 QAbstractXmlForwardIterator< T >::sizeHint () const virtual
Gives a hint to the size of the contained sequence.
Warning
This function is not part of the public interface.
The hint is assumed to be as close as possible to the actual size.
If no sensible estimate can be computed, -1 should be returned.
Definition at line 331 of file qabstractxmlforwarditerator_p.h.
Referenced by QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
 {
     Q_ASSERT_X(false, Q_FUNC_INFO, "This function is currently not expected to be used.");
     return -1;
 }
toList()
template<typename T > QList< T > QAbstractXmlForwardIterator< T >::toList () virtual
Performs a copy of this QAbstractXmlForwardIterator(with copy()), and returns its items in a QList.
Warning
This function is not part of the public interface.
Thus, this function acts as a conversion function, converting the sequence to a QList.
This function may modify the iterator. It is not a getter, but potentially alters the iterator in the same way the next() function does. If this QAbstractXmlForwardIterator must not be modified, such that it can be used for evaluation with next(), use a copy().
Reimplemented in QPatternist::ListIterator< T, ListType >, QPatternist::ListIterator< Item >, and QPatternist::ListIterator< QXmlNodeModelIndexIteratorPointer, QVector< QXmlNodeModelIndexIteratorPointer > >.
Definition at line 265 of file qabstractxmlforwarditerator_p.h.
Referenced by QPatternist::ListIterator< QXmlNodeModelIndexIteratorPointer, QVector< QXmlNodeModelIndexIteratorPointer > >::toList(), and QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
 {
     QList<T> result;
     T item(next());
     while(!qIsForwardIteratorEnd(item))
     {
         result.append(item);
         item = next();
     }
     return result;
 }
toReversed()
template<typename T > QAbstractXmlForwardIterator< T >::Ptr QAbstractXmlForwardIterator< T >::toReversed () virtual
Returns a reverse iterator for the sequence.
Warning
This function is not part of the public interface.
This function may modify the iterator, it can be considered a function that evaluates this QAbstractXmlForwardIterator. It is not a getter, but potentially alters the iterator in the same way the next() function does. If this QAbstractXmlForwardIterator must not be modified, such that it can be used for evaluation with next(), use a copy().
Reimplemented in QPatternist::SingletonIterator< T >, QPatternist::RangeIterator, QPatternist::EmptyIterator< T >, and QPatternist::EmptyIterator< QPatternist::Item >.
Definition at line 291 of file qabstractxmlforwarditerator_p.h.
Referenced by QAbstractXmlForwardIterator< OutputType >::~QAbstractXmlForwardIterator().
 {
     T item(next());
     QList<T> result;
     while(!qIsForwardIteratorEnd(item))
     {
         result.prepend(item);
         item = next();
     }
     return QExplicitlySharedDataPointer<QAbstractXmlForwardIterator<T> >(new QPatternist::ListIterator<T>(result));
 }
Friends and Related Functions
makeSequenceMappingIterator()
template<typename TResult , typename TSource , typename TMapper > static QAbstractXmlForwardIterator< TResult >::Ptr makeSequenceMappingIterator (const TMapper & mapper, const QExplicitlySharedDataPointer< QAbstractXmlForwardIterator< TSource > > & source, const DynamicContext::Ptr & context) related
An object generator for SequenceMappingIterator.
makeSequenceMappingIterator() is a convenience function for avoiding specifying the full template instantiation for SequenceMappingIterator. Conceptually, it is identical to Qt's qMakePair().
Returns
a SequenceMappingIterator wrapped in a smart pointer, that has been passed the constructor arguments mapper, source, and context.
See also
makeMappingCallbackPtr()
Definition at line 224 of file qsequencemappingiterator_p.h.
     {
         return typename QAbstractXmlForwardIterator<TResult>::Ptr
             (new SequenceMappingIterator<TResult, TSource, TMapper>(mapper, source, context));
     }
qIsForwardIteratorEnd()
template<typename T> bool qIsForwardIteratorEnd (const T & unit) related
The Callback QAbstractXmlForwardIterator uses for determining whether unit is the end of a sequence.
Since
4.4
If unit is a value that would signal the end of a sequence (typically a default constructed value), this function returns true, otherwise false.
This implementation works for any type that has a boolean operator. For example, this function should work satisfactory for pointers.
Definition at line 72 of file qabstractxmlforwarditerator_p.h.
Referenced by QAbstractXmlForwardIterator< OutputType >::count(), QAbstractXmlForwardIterator< OutputType >::isEmpty(), QAbstractXmlForwardIterator< OutputType >::last(), QPatternist::SingletonIterator< T >::SingletonIterator(), QAbstractXmlForwardIterator< OutputType >::toList(), and QAbstractXmlForwardIterator< OutputType >::toReversed().
 {
     return !unit;
 }
Properties
d_ptr
template<typename T> QAbstractXmlForwardIteratorPrivate* QAbstractXmlForwardIterator< T >::d_ptr private
Definition at line 121 of file qabstractxmlforwarditerator_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qabstractxmlforwarditerator_p.h
/src/xmlpatterns/api/qabstractxmlforwarditerator.cpp
/src/xmlpatterns/iterators/qsequencemappingiterator_p.h