Qt 4.8: QBasicTimer Class Reference
QBasicTimer Class Reference
The QBasicTimer class provides timer events for objects.
#include <qbasictimer.h>
Public Functions
bool isActive () const
Returns true if the timer is running and has not been stopped; otherwise returns false.
QBasicTimer ()
Contructs a basic timer.
void start (int msec, QObject *obj)
Starts (or restarts) the timer with a msec milliseconds timeout.
void stop ()
Stops the timer.
int timerId () const
Returns the timer's ID.
~QBasicTimer ()
Destroys the basic timer.
Properties
int id
Detailed Description
The QBasicTimer class provides timer events for objects.
This is a fast, lightweight, and low-level class used by Qt internally. We recommend using the higher-level QTimer class rather than this class if you want to use timers in your applications. Note that this timer is a repeating timer that will send subsequent timer events unless the stop() function is called.
To use this class, create a QBasicTimer, and call its start() function with a timeout interval and with a pointer to a QObject subclass. When the timer times out it will send a timer event to the QObject subclass. The timer can be stopped at any time using stop(). isActive() returns true for a timer that is running; i.e. it has been started, has not reached the timeout time, and has not been stopped. The timer's ID can be retrieved using timerId().
The Wiggly example uses QBasicTimer to repaint a widget at regular intervals.
See also
QTimer, QTimerEvent, QObject::timerEvent(), Timers, {Wiggly Example}
Definition at line 55 of file qbasictimer.h.
Constructors and Destructors
QBasicTimer()
QBasicTimer::QBasicTimer () inline
Contructs a basic timer.
See also
start()
Definition at line 59 of file qbasictimer.h.
 : id(0) {}
~QBasicTimer()
QBasicTimer::~QBasicTimer () inline
Destroys the basic timer.
Definition at line 60 of file qbasictimer.h.
 { if (id) stop(); }
Functions
isActive()
bool QBasicTimer::isActive () const inline
Returns true if the timer is running and has not been stopped; otherwise returns false.
See also
start() stop()
Definition at line 62 of file qbasictimer.h.
Referenced by QHeaderViewPrivate::doDelayedResizeSections(), QTreeModel::executePendingSort(), QHeaderViewPrivate::executePostedResize(), QTipLabel::hideTip(), QMenuPrivate::popupAction(), QUnifiedTimer::registerAnimation(), QWindowsVistaStylePrivate::startAnimation(), QUnifiedTimer::timerEvent(), QWindowsVistaStylePrivate::timerEvent(), and QUnifiedTimer::unregisterAnimation().
 { return id != 0; }
start()
void QBasicTimer::start (int msec, QObject * object)
Starts (or restarts) the timer with a msec milliseconds timeout.
The given object will receive timer events.
See also
stop() isActive() QObject::timerEvent()
Definition at line 131 of file qbasictimer.cpp.
Referenced by QComboBoxPrivate::adjustComboBoxSize(), QHeaderViewPrivate::doDelayedResizeSections(), QTipLabel::hideTip(), QMenuPrivate::mouseEventTaken(), QFileSystemModelPrivate::node(), QMenuPrivate::popupAction(), QUnifiedTimer::registerAnimation(), QUnifiedTimer::restartAnimationTimer(), QTipLabel::restartExpireTimer(), QTextControlPrivate::setBlinkingCursorEnabled(), QWindowsVistaStylePrivate::startAnimation(), QDefaultAnimationDriver::started(), QUnifiedTimer::unregisterAnimation(), and QNetworkAccessCache::updateTimer().
 {
    stop();
    if (obj)
        id = obj->startTimer(msec);
 }
stop()
void QBasicTimer::stop ()
Stops the timer.
See also
start() isActive()
Definition at line 143 of file qbasictimer.cpp.
Referenced by QTreeModel::clear(), QNetworkAccessCache::clear(), QLineEditPrivate::drag(), QTreeModel::ensureSorted(), QTreeModel::executePendingSort(), QMenuPrivate::mouseEventTaken(), QTipLabel::restartExpireTimer(), QTextControlPrivate::setBlinkingCursorEnabled(), QTreeModel::sort(), start(), QDefaultAnimationDriver::stopped(), QTipLabel::timerEvent(), QMainWindowLayout::timerEvent(), QUnifiedTimer::timerEvent(), QWindowsVistaStylePrivate::timerEvent(), and QNetworkAccessCache::updateTimer().
 {
     if (id) {
         QAbstractEventDispatcher *eventDispatcher = QAbstractEventDispatcher::instance();
         if (eventDispatcher)
             eventDispatcher->unregisterTimer(id);
     }
     id = 0;
 }
timerId()
int QBasicTimer::timerId () const inline
Returns the timer's ID.
See also
QTimerEvent::timerId()
Definition at line 63 of file qbasictimer.h.
Referenced by QDefaultAnimationDriver::timerEvent(), QTipLabel::timerEvent(), QTreeModel::timerEvent(), QMainWindowLayout::timerEvent(), and QUnifiedTimer::timerEvent().
 { return id; }
Properties
id
int QBasicTimer::id private
Definition at line 57 of file qbasictimer.h.
The documentation for this class was generated from the following files:
/src/corelib/kernel/qbasictimer.h
/src/corelib/kernel/qbasictimer.cpp