Qt 4.8: QAbstractItemView Class Reference
QAbstractItemView Class Reference abstract
The QAbstractItemView class provides the basic functionality for item view classes.
#include <qabstractitemview.h>
Public Types
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void clearSelection ()
Deselects all selected items.
virtual void doItemsLayout ()
This function is intended to lay out the items in the view.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
virtual void reset ()
Reset the internal state of the view.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
virtual void selectAll ()
Selects all items in the view.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
virtual void setRootIndex (const QModelIndex &index)
Sets the root item to the item at the given index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
virtual QModelIndex indexAt (const QPoint &point) const =0
Returns the model index of the item at the viewport coordinates point.
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
virtual void keyboardSearch (const QString &search)
Moves to and selects the item best matching the string search.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
virtual void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)=0
Scrolls the view if necessary to ensure that the item at index is visible.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
virtual void setModel (QAbstractItemModel *model)
Sets the model for the view to present.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
virtual void setSelectionModel (QItemSelectionModel *selectionModel)
Sets the current selection model to the given selectionModel.
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
virtual int sizeHintForColumn (int column) const
Returns the width size hint for the specified column or -1 if there is no model.
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
virtual int sizeHintForRow (int row) const
Returns the height size hint for the specified row or -1 if there is no model.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
virtual QRect visualRect (const QModelIndex &index) const =0
Returns the rectangle on the viewport occupied by the item at index.
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Types
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Slots
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void currentChanged (const QModelIndex &current, const QModelIndex &previous)
This slot is called when a new item becomes the current item.
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This slot is called when items are changed in the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarAction (int action)
virtual void horizontalScrollbarValueChanged (int value)
virtual void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
This slot is called when rows are about to be removed.
virtual void rowsInserted (const QModelIndex &parent, int start, int end)
This slot is called when rows are inserted.
virtual void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
This slot is called when the selection is changed.
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void updateGeometries ()
Updates the geometry of the child widgets of the view.
virtual void verticalScrollbarAction (int action)
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
void dragLeaveEvent (QDragLeaveEvent *event)
This function is called when the item being dragged leaves the view.
void dragMoveEvent (QDragMoveEvent *event)
This function is called continuously with the given event during a drag and drop operation over the widget.
void dropEvent (QDropEvent *event)
This function is called with the given event when a drop event occurs over the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
bool event (QEvent *event)
Reimplemented Function
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
virtual int horizontalOffset () const =0
Returns the horizontal offset of the view.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
virtual bool isIndexHidden (const QModelIndex &index) const =0
Returns true if the item referred to by the given index is hidden in the view, otherwise returns false.
void keyPressEvent (QKeyEvent *event)
This function is called with the given event when a key event is sent to the widget.
void mouseDoubleClickEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is double clicked inside the widget.
void mouseMoveEvent (QMouseEvent *event)
This function is called with the given event when a mouse move event is sent to the widget.
void mousePressEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is pressed while the cursor is inside the widget.
void mouseReleaseEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is released, after a mouse press event on the widget.
virtual QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)=0
Returns a QModelIndex object pointing to the next object in the view, based on the given cursorAction and keyboard modifiers specified by modifiers.
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
This function is called with the given event when a resize event is sent to the widget.
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QModelIndexList selectedIndexes () const
This convenience function returns a list of all selected and non-hidden item indexes in the view.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
virtual void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)=0
Applies the selection flags to the items in or touched by the rectangle, rect.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
virtual void startDrag (Qt::DropActions supportedActions)
Starts a drag by calling drag->exec() using the given supportedActions.
State state () const
Returns the item view's state.
void stopAutoScroll ()
void timerEvent (QTimerEvent *event)
This function is called with the given event when a timer event is sent to the widget.
virtual int verticalOffset () const =0
Returns the vertical offset of the view.
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
virtual QStyleOptionViewItem viewOptions () const
Returns a QStyleOptionViewItem structure populated with the view's palette, font, state, alignments etc.
bool viewportEvent (QEvent *event)
This function is used to handle tool tips, and What's This? mode, if the given event is a QEvent::ToolTip,or a QEvent::WhatsThis.
virtual QRegion visualRegionForSelection (const QItemSelection &selection) const =0
Returns the region from the viewport of the items in the given selection.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
virtual void scrollContentsBy (int dx, int dy)
This virtual handler is called when the scroll bars are moved by dx, dy, and consequently the viewport's contents should be scrolled accordingly.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool alternatingRowColors
whether to draw the background using alternating colors
bool autoScroll
whether autoscrolling in drag move events is enabled
int autoScrollMargin
the size of the area when auto scrolling is triggered
Qt::DropAction defaultDropAction
the drop action that will be used by default in QAbstractItemView::drag()
DragDropMode dragDropMode
the drag and drop event the view will act upon
bool dragDropOverwriteMode
the view's drag and drop behavior
bool dragEnabled
whether the view supports dragging of its own items
EditTriggers editTriggers
which actions will initiate item editing
ScrollMode horizontalScrollMode
how the view scrolls its contents in the horizontal direction
QSize iconSize
the size of items' icons
SelectionBehavior selectionBehavior
which selection behavior the view uses
SelectionMode selectionMode
which selection mode the view operates in
bool showDropIndicator
whether the drop indicator is shown when dragging items and dropping.
bool tabKeyNavigation
whether item navigation with tab and backtab is enabled.
Qt::TextElideMode textElideMode
the position of the "..." in elided text.
ScrollMode verticalScrollMode
how the view scrolls its contents in the vertical direction
Friends
class QAccessibleItemRow
class QListModeViewBase
class QListViewPrivate
class QTreeViewPrivate
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QAbstractItemView class provides the basic functionality for item view classes.
QAbstractItemView class is the base class for every standard view that uses a QAbstractItemModel. QAbstractItemView is an abstract class and cannot itself be instantiated. It provides a standard interface for interoperating with models through the signals and slots mechanism, enabling subclasses to be kept up-to-date with changes to their models. This class provides standard support for keyboard and mouse navigation, viewport scrolling, item editing, and selections. The keyboard navigation implements this functionality:
Keys Functionality
Arrow keys Changes the current item and selects it.
Ctrl+Arrow keys Changes the current item but does not select it.
Shift+Arrow keys Changes the current item and selects it. The previously selected item(s) is not deselected.
Ctr+Space Toggles selection of the current item.
Tab/Backtab Changes the current item to the next/previous item.
Home/End Selects the first/last item in the model.
Page up/Page down Scrolls the rows shown up/down by the number of visible rows in the view.
Ctrl+A Selects all items in the model.
Note that the above table assumes that the selection mode allows the operations. For instance, you cannot select items if the selection mode is QAbstractItemView::NoSelection.
The QAbstractItemView class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
The view classes that inherit QAbstractItemView only need to implement their own view-specific functionality, such as drawing items, returning the geometry of items, finding items, etc.
QAbstractItemView provides common slots such as edit() and setCurrentIndex(). Many protected slots are also provided, including dataChanged(), rowsInserted(), rowsAboutToBeRemoved(), selectionChanged(), and currentChanged().
The root item is returned by rootIndex(), and the current item by currentIndex(). To make sure that an item is visible use scrollTo().
Some of QAbstractItemView's functions are concerned with scrolling, for example setHorizontalScrollMode() and setVerticalScrollMode(). To set the range of the scroll bars, you can, for example, reimplement the view's resizeEvent() function:
void MyView::resizeEvent(QResizeEvent *event) {
    horizontalScrollBar()->setRange(0, realWidth - width());
    ...
}
Note that the range is not updated until the widget is shown.
Several other functions are concerned with selection control; for example setSelectionMode(), and setSelectionBehavior(). This class provides a default selection model to work with (selectionModel()), but this can be replaced by using setSelectionModel() with an instance of QItemSelectionModel.
For complete control over the display and editing of items you can specify a delegate with setItemDelegate().
QAbstractItemView provides a lot of protected functions. Some are concerned with editing, for example, edit(), and commitData(), whilst others are keyboard and mouse event handlers.
Note
If you inherit QAbstractItemView and intend to update the contents of the viewport, you should use viewport->update() instead of update() as all painting operations take place on the viewport.
See also
{View Classes}, {Model/View Programming}, QAbstractItemModel, {Chart Example}
Definition at line 63 of file qabstractitemview.h.
Enumerations
CursorAction
enum QAbstractItemView::CursorAction protected
This enum describes the different ways to navigate between items,.
See also
moveCursor()
MoveUp Move to the item above the current item.
MoveDown Move to the item below the current item.
MoveLeft Move to the item left of the current item.
MoveRight Move to the item right of the current item.
MoveHome Move to the top-left corner item.
MoveEnd Move to the bottom-right corner item.
MovePageUp Move one page up above the current item.
MovePageDown Move one page down below the current item.
MoveNext Move to the item after the current item.
MovePrevious Move to the item before the current item.
Enumerator
MoveUp
MoveDown
MoveLeft
MoveRight
MoveHome
MoveEnd
MovePageUp
MovePageDown
MoveNext
MovePrevious
Definition at line 277 of file qabstractitemview.h.
                       { MoveUp, MoveDown, MoveLeft, MoveRight,
                         MoveHome, MoveEnd, MovePageUp, MovePageDown,
                         MoveNext, MovePrevious };
DragDropMode
enum QAbstractItemView::DragDropMode
Describes the various drag and drop events the view can act upon.
Since
4.2
By default the view does not support dragging or dropping (NoDragDrop).
NoDragDrop Does not support dragging or dropping.
DragOnly The view supports dragging of its own items
DropOnly The view accepts drops
DragDrop The view supports both dragging and dropping
InternalMove The view accepts move (not copy) operations only from itself.
Note that the model used needs to provide support for drag and drop operations.
See also
setDragDropMode() {Using drag and drop with item views}
Enumerator
NoDragDrop
DragOnly
DropOnly
DragDrop
InternalMove
Definition at line 175 of file qabstractitemview.h.
                       {
         NoDragDrop,
         DragOnly,
         DropOnly,
         DragDrop,
         InternalMove
     };
DropIndicatorPosition
enum QAbstractItemView::DropIndicatorPosition protected
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
OnItem The item will be dropped on the index.
AboveItem The item will be dropped above the index.
BelowItem The item will be dropped below the index.
OnViewport The item will be dropped onto a region of the viewport with no items. The way each view handles items dropped onto the viewport depends on the behavior of the underlying model in use.
Enumerator
OnItem
AboveItem
BelowItem
OnViewport
Definition at line 348 of file qabstractitemview.h.
 { OnItem, AboveItem, BelowItem, OnViewport };
EditTrigger
enum QAbstractItemView::EditTrigger
This enum describes actions which will initiate item editing.
NoEditTriggers No editing possible.
CurrentChanged Editing start whenever current item changes.
DoubleClicked Editing starts when an item is double clicked.
SelectedClicked Editing starts when clicking on an already selected item.
EditKeyPressed Editing starts when the platform edit key has been pressed over an item.
AnyKeyPressed Editing starts when any key is pressed over an item.
AllEditTriggers Editing starts for all above actions.
Enumerator
NoEditTriggers
CurrentChanged
DoubleClicked
SelectedClicked
EditKeyPressed
AnyKeyPressed
AllEditTriggers
Definition at line 109 of file qabstractitemview.h.
                      {
         NoEditTriggers = 0,
         CurrentChanged = 1,
         DoubleClicked = 2,
         SelectedClicked = 4,
         EditKeyPressed = 8,
         AnyKeyPressed = 16,
         AllEditTriggers = 31
     };
ScrollHint
enum QAbstractItemView::ScrollHint
EnsureVisible Scroll to ensure that the item is visible.
PositionAtTop Scroll to position the item at the top of the viewport.
PositionAtBottom Scroll to position the item at the bottom of the viewport.
PositionAtCenter Scroll to position the item at the center of the viewport.
Enumerator
EnsureVisible
PositionAtTop
PositionAtBottom
PositionAtCenter
Definition at line 102 of file qabstractitemview.h.
                     {
         EnsureVisible,
         PositionAtTop,
         PositionAtBottom,
         PositionAtCenter
     };
ScrollMode
enum QAbstractItemView::ScrollMode
Since
4.2
ScrollPerItem The view will scroll the contents one item at a time.
ScrollPerPixel The view will scroll the contents one pixel at a time.
Enumerator
ScrollPerItem
ScrollPerPixel
Definition at line 121 of file qabstractitemview.h.
                     {
         ScrollPerItem,
         ScrollPerPixel
     };
SelectionBehavior
enum QAbstractItemView::SelectionBehavior
SelectItems Selecting single items.
SelectRows Selecting only rows.
SelectColumns Selecting only columns.
Enumerator
SelectItems
SelectRows
SelectColumns
Definition at line 96 of file qabstractitemview.h.
{
         SelectItems,
         SelectRows,
         SelectColumns
     };
SelectionMode
enum QAbstractItemView::SelectionMode
This enum indicates how the view responds to user selections:
SingleSelection When the user selects an item, any already-selected item becomes unselected, and the user cannot unselect the selected item by clicking on it.
ContiguousSelection When the user selects an item in the usual way, the selection is cleared and the new item selected. However, if the user presses the Shift key while clicking on an item, all items between the current item and the clicked item are selected or unselected, depending on the state of the clicked item.
ExtendedSelection When the user selects an item in the usual way, the selection is cleared and the new item selected. However, if the user presses the Ctrl key when clicking on an item, the clicked item gets toggled and all other items are left untouched. If the user presses the Shift key while clicking on an item, all items between the current item and the clicked item are selected or unselected, depending on the state of the clicked item. Multiple items can be selected by dragging the mouse over them.
MultiSelection When the user selects an item in the usual way, the selection status of that item is toggled and the other items are left alone. Multiple items can be toggled by dragging the mouse over them.
NoSelection Items cannot be selected.
The most commonly used modes are SingleSelection and ExtendedSelection.
Enumerator
NoSelection
SingleSelection
MultiSelection
ExtendedSelection
ContiguousSelection
Definition at line 88 of file qabstractitemview.h.
{
         NoSelection,
         SingleSelection,
         MultiSelection,
         ExtendedSelection,
         ContiguousSelection
     };
State
enum QAbstractItemView::State protected
Describes the different states the view can be in.
This is usually only interesting when reimplementing your own view.
NoState The is the default state.
DraggingState The user is dragging items.
DragSelectingState The user is selecting items.
EditingState The user is editing an item in a widget editor.
ExpandingState The user is opening a branch of items.
CollapsingState The user is closing a branch of items.
AnimatingState The item view is performing an animation.
Enumerator
NoState
DraggingState
DragSelectingState
EditingState
ExpandingState
CollapsingState
AnimatingState
Definition at line 303 of file qabstractitemview.h.
                {
         NoState,
         DraggingState,
         DragSelectingState,
         EditingState,
         ExpandingState,
         CollapsingState,
         AnimatingState
     };
Constructors and Destructors
QAbstractItemView() [1/2]
QAbstractItemView::QAbstractItemView (QWidget * parent = 0) explicit
Constructs an abstract item view with the given parent.
Definition at line 640 of file qabstractitemview.cpp.
     : QAbstractScrollArea(*(new QAbstractItemViewPrivate), parent)
 {
     d_func()->init();
 }
~QAbstractItemView()
QAbstractItemView::~QAbstractItemView ()
Destroys the view.
Definition at line 658 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     // stop these timers here before ~QObject
     d->delayedReset.stop();
     d->updateTimer.stop();
     d->delayedEditing.stop();
     d->delayedAutoScroll.stop();
     d->autoScrollTimer.stop();
     d->delayedLayout.stop();
     d->fetchMoreTimer.stop();
 }
QAbstractItemView() [2/2]
QAbstractItemView::QAbstractItemView (QAbstractItemViewPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 649 of file qabstractitemview.cpp.
     : QAbstractScrollArea(dd, parent)
 {
     d_func()->init();
 }
Functions
activated
void QAbstractItemView::activated (const QModelIndex & index) signal
This signal is emitted when the item specified by index is activated by the user.
How to activate items depends on the platform; e.g., by single- or double-clicking the item, or by pressing the Return or Enter key when the item is current.
See also
clicked(), doubleClicked(), entered(), pressed()
Referenced by QColumnViewPrivate::createColumn(), keyPressEvent(), QTreeView::mouseDoubleClickEvent(), mouseDoubleClickEvent(), mouseReleaseEvent(), and QTreeWidget::QTreeWidget().
alternatingRowColors()
bool QAbstractItemView::alternatingRowColors () const
Referenced by QColumnView::initializeColumn(), and setAlternatingRowColors().
autoScrollMargin()
int QAbstractItemView::autoScrollMargin () const
Referenced by setAutoScrollMargin(), and QAbstractItemViewPrivate::shouldAutoScroll().
clearSelection
void QAbstractItemView::clearSelection () slot
Deselects all selected items.
The current index will not be changed.
See also
setSelection(), selectAll()
Definition at line 1225 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (d->selectionModel)
         d->selectionModel->clearSelection();
 }
clicked
void QAbstractItemView::clicked (const QModelIndex & index) signal
This signal is emitted when a mouse button is clicked.
The item the mouse was clicked on is specified by index. The signal is only emitted when the index is valid.
See also
activated(), doubleClicked(), entered(), pressed()
Referenced by QColumnViewPrivate::createColumn(), mouseReleaseEvent(), and QTreeWidget::QTreeWidget().
closeEditor
void QAbstractItemView::closeEditor (QWidget * editor, QAbstractItemDelegate::EndEditHint hint) protected virtual slot
Closes the given editor, and releases it.
The hint is used to specify how the view should respond to the end of the editing operation. For example, the hint may indicate that the next item in the view should be opened for editing.
See also
edit(), commitData()
Definition at line 2849 of file qabstractitemview.cpp.
Referenced by closePersistentEditor(), currentChanged(), setItemDelegate(), setItemDelegateForColumn(), and setItemDelegateForRow().
 {
     Q_D(QAbstractItemView);
     // Close the editor
     if (editor) {
         bool isPersistent = d->persistent.contains(editor);
         bool hadFocus = editor->hasFocus();
         QModelIndex index = d->indexForEditor(editor);
         if (!index.isValid())
             return; // the editor was not registered
         if (!isPersistent) {
             setState(NoState);
             QModelIndex index = d->indexForEditor(editor);
             editor->removeEventFilter(d->delegateForIndex(index));
             d->removeEditor(editor);
         }
         if (hadFocus)
             setFocus(); // this will send a focusLost event to the editor
         else
             d->checkPersistentEditorFocus();
         QPointer<QWidget> ed = editor;
         QApplication::sendPostedEvents(editor, 0);
         editor = ed;
         if (!isPersistent && editor)
             d->releaseEditor(editor);
     }
     // The EndEditHint part
     QItemSelectionModel::SelectionFlags flags = QItemSelectionModel::ClearAndSelect
                                                 | d->selectionBehaviorFlags();
     switch (hint) {
     case QAbstractItemDelegate::EditNextItem: {
         QModelIndex index = moveCursor(MoveNext, Qt::NoModifier);
         if (index.isValid()) {
             QPersistentModelIndex persistent(index);
             d->selectionModel->setCurrentIndex(persistent, flags);
             // currentChanged signal would have already started editing
             if (index.flags() & Qt::ItemIsEditable
                 && (!(editTriggers() & QAbstractItemView::CurrentChanged)))
                 edit(persistent);
         } break; }
     case QAbstractItemDelegate::EditPreviousItem: {
         QModelIndex index = moveCursor(MovePrevious, Qt::NoModifier);
         if (index.isValid()) {
             QPersistentModelIndex persistent(index);
             d->selectionModel->setCurrentIndex(persistent, flags);
             // currentChanged signal would have already started editing
             if (index.flags() & Qt::ItemIsEditable
                 && (!(editTriggers() & QAbstractItemView::CurrentChanged)))
                 edit(persistent);
         } break; }
     case QAbstractItemDelegate::SubmitModelCache:
         d->model->submit();
         break;
     case QAbstractItemDelegate::RevertModelCache:
         d->model->revert();
         break;
     default:
         break;
     }
 }
closePersistentEditor()
void QAbstractItemView::closePersistentEditor (const QModelIndex & index)
Closes the persistent editor for the item at the given index.
See also
openPersistentEditor()
Definition at line 3205 of file qabstractitemview.cpp.
Referenced by QListWidget::addItems(), QListWidget::closePersistentEditor(), QTableWidget::closePersistentEditor(), and QTreeWidget::closePersistentEditor().
 {
     Q_D(QAbstractItemView);
     if (QWidget *editor = d->editorForIndex(index).widget.data()) {
         if (index == selectionModel()->currentIndex())
             closeEditor(editor, QAbstractItemDelegate::RevertModelCache);
         d->persistent.remove(editor);
         d->removeEditor(editor);
         d->releaseEditor(editor);
     }
 }
commitData
void QAbstractItemView::commitData (QWidget * editor) protected virtual slot
Commit the data in the editor to the model.
See also
closeEditor()
Definition at line 2920 of file qabstractitemview.cpp.
Referenced by currentChanged(), setItemDelegate(), setItemDelegateForColumn(), and setItemDelegateForRow().
 {
     Q_D(QAbstractItemView);
     if (!editor || !d->itemDelegate || d->currentlyCommittingEditor)
         return;
     QModelIndex index = d->indexForEditor(editor);
     if (!index.isValid())
         return;
     d->currentlyCommittingEditor = editor;
     QAbstractItemDelegate *delegate = d->delegateForIndex(index);
     editor->removeEventFilter(delegate);
     delegate->setModelData(editor, d->model, index);
     editor->installEventFilter(delegate);
     d->currentlyCommittingEditor = 0;
 }
currentChanged
void QAbstractItemView::currentChanged (const QModelIndex & current, const QModelIndex & previous) protected virtual slot
This slot is called when a new item becomes the current item.
The previous current item is specified by the previous index, and the new item by the current index.
If you want to know about changes to items see the dataChanged() signal.
Reimplemented in QTreeView, QHeaderView, QListView, QTableView, QColumnView, and QFontListView.
Definition at line 3671 of file qabstractitemview.cpp.
Referenced by QColumnView::currentChanged(), QTableView::currentChanged(), QListView::currentChanged(), QTreeView::currentChanged(), and setSelectionModel().
 {
     Q_D(QAbstractItemView);
     Q_ASSERT(d->model);
     if (previous.isValid()) {
         QModelIndex buddy = d->model->buddy(previous);
         QWidget *editor = d->editorForIndex(buddy).widget.data();
         if (editor && !d->persistent.contains(editor)) {
             commitData(editor);
             if (current.row() != previous.row())
                 closeEditor(editor, QAbstractItemDelegate::SubmitModelCache);
             else
                 closeEditor(editor, QAbstractItemDelegate::NoHint);
         }
         if (isVisible()) {
             update(previous);
         }
     }
     if (current.isValid() && !d->autoScrollTimer.isActive()) {
         if (isVisible()) {
             if (d->autoScroll)
                 scrollTo(current);
             update(current);
             edit(current, CurrentChanged, 0);
             if (current.row() == (d->model->rowCount(d->root) - 1))
                 d->fetchMore();
         } else {
             d->shouldScrollToCurrentOnShow = d->autoScroll;
         }
     }
 }
currentIndex()
QModelIndex QAbstractItemView::currentIndex () const
Returns the model index of the current item.
See also
setCurrentIndex()
Definition at line 1112 of file qabstractitemview.cpp.
Referenced by QTableWidget::currentColumn(), QTreeWidget::currentColumn(), QFontListView::currentItem(), QListWidget::currentItem(), QTableWidget::currentItem(), QTreeWidget::currentItem(), QTableWidget::currentRow(), QFontListView::currentText(), QAccessibleItemRow::doAction(), QTreeView::drawRow(), event(), QComboBoxPrivateContainer::eventFilter(), focusInEvent(), QCalendarWidgetPrivate::getCurrentDate(), inputMethodEvent(), inputMethodQuery(), QTreeView::keyboardSearch(), keyboardSearch(), QComboBoxPrivate::keyboardSearchString(), QTreeView::keyPressEvent(), keyPressEvent(), mousePressEvent(), QColumnView::moveCursor(), QTableView::moveCursor(), QListView::moveCursor(), QTreeView::moveCursor(), QCalendarView::moveCursor(), QAccessibleItemRow::navigate(), openPersistentEditor(), QListView::paintEvent(), rowsAboutToBeRemoved(), setCurrentIndex(), QListWidget::setCurrentItem(), timerEvent(), viewportEvent(), and QCalendarView::wheelEvent().
 {
     Q_D(const QAbstractItemView);
     return d->selectionModel ? d->selectionModel->currentIndex() : QModelIndex();
 }
dataChanged
void QAbstractItemView::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual slot
This slot is called when items are changed in the model.
The changed items are those from topLeft to bottomRight inclusive. If just one item is changed topLeft == bottomRight.
Reimplemented in QHeaderView, QListView, and QTreeView.
Definition at line 3348 of file qabstractitemview.cpp.
Referenced by QTreeView::dataChanged(), QListView::dataChanged(), setIndexWidget(), and setModel().
 {
     // Single item changed
     Q_D(QAbstractItemView);
     if (topLeft == bottomRight && topLeft.isValid()) {
         const QEditorInfo &editorInfo = d->editorForIndex(topLeft);
         //we don't update the edit data if it is static
         if (!editorInfo.isStatic && editorInfo.widget) {
             QAbstractItemDelegate *delegate = d->delegateForIndex(topLeft);
             if (delegate) {
                 delegate->setEditorData(editorInfo.widget.data(), topLeft);
             }
         }
         if (isVisible() && !d->delayedPendingLayout) {
             // otherwise the items will be update later anyway
             update(topLeft);
         }
         return;
     }
     d->updateEditorData(topLeft, bottomRight);
     if (!isVisible() || d->delayedPendingLayout)
         return; // no need to update
     d->viewport->update();
 }
defaultDropAction()
Qt::DropAction QAbstractItemView::defaultDropAction () const
Referenced by setDefaultDropAction(), and startDrag().
dirtyRegionOffset()
QPoint QAbstractItemView::dirtyRegionOffset () const protected
Returns the offset of the dirty regions in the view.
If you use scrollDirtyRegion() and implement a paintEvent() in a subclass of QAbstractItemView, you should translate the area given by the paint event with the offset returned from this function.
See also
scrollDirtyRegion(), setDirtyRegion()
Definition at line 3875 of file qabstractitemview.cpp.
 {
     Q_D(const QAbstractItemView);
     return d->scrollDelayOffset;
 }
doAutoScroll()
void QAbstractItemView::doAutoScroll () protected
Warning
This function is not part of the public interface.
Definition at line 3900 of file qabstractitemview.cpp.
Referenced by timerEvent().
 {
     // find how much we should scroll with
     Q_D(QAbstractItemView);
     int verticalStep = verticalScrollBar()->pageStep();
     int horizontalStep = horizontalScrollBar()->pageStep();
     if (d->autoScrollCount < qMax(verticalStep, horizontalStep))
         ++d->autoScrollCount;
     int margin = d->autoScrollMargin;
     int verticalValue = verticalScrollBar()->value();
     int horizontalValue = horizontalScrollBar()->value();
     QPoint pos = d->viewport->mapFromGlobal(QCursor::pos());
     QRect area = static_cast<QAbstractItemView*>(d->viewport)->d_func()->clipRect(); // access QWidget private by bending C++ rules
     // do the scrolling if we are in the scroll margins
     if (pos.y() - area.top() < margin)
         verticalScrollBar()->setValue(verticalValue - d->autoScrollCount);
     else if (area.bottom() - pos.y() < margin)
         verticalScrollBar()->setValue(verticalValue + d->autoScrollCount);
     if (pos.x() - area.left() < margin)
         horizontalScrollBar()->setValue(horizontalValue - d->autoScrollCount);
     else if (area.right() - pos.x() < margin)
         horizontalScrollBar()->setValue(horizontalValue + d->autoScrollCount);
     // if nothing changed, stop scrolling
     bool verticalUnchanged = (verticalValue == verticalScrollBar()->value());
     bool horizontalUnchanged = (horizontalValue == horizontalScrollBar()->value());
     if (verticalUnchanged && horizontalUnchanged) {
         stopAutoScroll();
     } else {
 #ifndef QT_NO_DRAGANDDROP
         d->dropIndicatorRect = QRect();
         d->dropIndicatorPosition = QAbstractItemView::OnViewport;
 #endif
         d->viewport->update();
     }
 }
doItemsLayout
void QAbstractItemView::doItemsLayout () virtual slot
This function is intended to lay out the items in the view.
Warning
This function is not part of the public interface.
The default implementation just calls updateGeometries() and updates the viewport.
Reimplemented in QHeaderView, QTreeView, QListView, and QTableView.
Definition at line 1241 of file qabstractitemview.cpp.
Referenced by QTableView::doItemsLayout(), QListView::doItemsLayout(), QTreeView::doItemsLayout(), QHeaderView::doItemsLayout(), event(), setItemDelegate(), and timerEvent().
 {
     Q_D(QAbstractItemView);
     d->interruptDelayedItemsLayout();
     updateGeometries();
     d->viewport->update();
 }
doubleClicked
void QAbstractItemView::doubleClicked (const QModelIndex & index) signal
This signal is emitted when a mouse button is double-clicked.
The item the mouse was double-clicked on is specified by index. The signal is only emitted when the index is valid.
See also
clicked(), activated()
Referenced by QColumnViewPrivate::createColumn(), QTreeView::mouseDoubleClickEvent(), mouseDoubleClickEvent(), and QTreeWidget::QTreeWidget().
dragDropMode()
DragDropMode QAbstractItemView::dragDropMode () const
Referenced by dragEnterEvent(), dragMoveEvent(), QListWidget::dropEvent(), QTableWidget::dropEvent(), dropEvent(), QTreeWidget::dropEvent(), QColumnView::initializeColumn(), setDragDropMode(), and startDrag().
dragDropOverwriteMode()
bool QAbstractItemView::dragDropOverwriteMode () const
Referenced by QColumnView::initializeColumn(), and setDragDropOverwriteMode().
dragEnabled()
bool QAbstractItemView::dragEnabled () const
Referenced by setDragDropMode(), and setDragEnabled().
dragEnterEvent()
void QAbstractItemView::dragEnterEvent (QDragEnterEvent * event) protected virtual
This function is called with the given event when a drag and drop operation enters the widget.
If the drag is over a valid dropping place (e.g. over an item that accepts drops), the event is accepted; otherwise it is ignored.
See also
dropEvent() startDrag()
Reimplemented from QWidget.
Definition at line 1987 of file qabstractitemview.cpp.
Referenced by QSidebar::dragEnterEvent().
 {
     if (dragDropMode() == InternalMove
         && (event->source() != this|| !(event->possibleActions() & Qt::MoveAction)))
         return;
     if (d_func()->canDecode(event)) {
         event->accept();
         setState(DraggingState);
     } else {
         event->ignore();
     }
 }
dragLeaveEvent()
void QAbstractItemView::dragLeaveEvent (QDragLeaveEvent * event) protected virtual
This function is called when the item being dragged leaves the view.
The event describes the state of the drag and drop operation.
Reimplemented from QWidget.
Reimplemented in QListView.
Definition at line 2107 of file qabstractitemview.cpp.
Referenced by QListView::dragLeaveEvent().
 {
     Q_D(QAbstractItemView);
     stopAutoScroll();
     setState(NoState);
     d->hover = QModelIndex();
     d->viewport->update();
 }
dragMoveEvent()
void QAbstractItemView::dragMoveEvent (QDragMoveEvent * event) protected virtual
This function is called continuously with the given event during a drag and drop operation over the widget.
It can cause the view to scroll if, for example, the user drags a selection to view's right or bottom edge. In this case, the event will be accepted; otherwise it will be ignored.
See also
dropEvent() startDrag()
Reimplemented from QWidget.
Reimplemented in QTreeView, and QListView.
Definition at line 2009 of file qabstractitemview.cpp.
Referenced by QListView::dragMoveEvent(), and QTreeView::dragMoveEvent().
 {
     Q_D(QAbstractItemView);
     if (dragDropMode() == InternalMove
         && (event->source() != this || !(event->possibleActions() & Qt::MoveAction)))
         return;
     // ignore by default
     event->ignore();
     QModelIndex index = indexAt(event->pos());
     d->hover = index;
     if (!d->droppingOnItself(event, index)
         && d->canDecode(event)) {
         if (index.isValid() && d->showDropIndicator) {
             QRect rect = visualRect(index);
             d->dropIndicatorPosition = d->position(event->pos(), rect, index);
             switch (d->dropIndicatorPosition) {
             case AboveItem:
                 if (d->isIndexDropEnabled(index.parent())) {
                     d->dropIndicatorRect = QRect(rect.left(), rect.top(), rect.width(), 0);
                     event->accept();
                 } else {
                     d->dropIndicatorRect = QRect();
                 }
                 break;
             case BelowItem:
                 if (d->isIndexDropEnabled(index.parent())) {
                     d->dropIndicatorRect = QRect(rect.left(), rect.bottom(), rect.width(), 0);
                     event->accept();
                 } else {
                     d->dropIndicatorRect = QRect();
                 }
                 break;
             case OnItem:
                 if (d->isIndexDropEnabled(index)) {
                     d->dropIndicatorRect = rect;
                     event->accept();
                 } else {
                     d->dropIndicatorRect = QRect();
                 }
                 break;
             case OnViewport:
                 d->dropIndicatorRect = QRect();
                 if (d->isIndexDropEnabled(rootIndex())) {
                     event->accept(); // allow dropping in empty areas
                 }
                 break;
             }
         } else {
             d->dropIndicatorRect = QRect();
             d->dropIndicatorPosition = OnViewport;
             if (d->isIndexDropEnabled(rootIndex())) {
                 event->accept(); // allow dropping in empty areas
             }
         }
         d->viewport->update();
     } // can decode
     if (d->shouldAutoScroll(event->pos()))
         startAutoScroll();
 }
dropEvent()
void QAbstractItemView::dropEvent (QDropEvent * event) protected virtual
This function is called with the given event when a drop event occurs over the widget.
If the model accepts the even position the drop event is accepted; otherwise it is ignored.
See also
startDrag()
Reimplemented from QWidget.
Reimplemented in QTreeWidget, QTableWidget, QListWidget, and QListView.
Definition at line 2123 of file qabstractitemview.cpp.
Referenced by QListView::dropEvent(), QTableWidget::dropEvent(), and QTreeWidget::dropEvent().
 {
     Q_D(QAbstractItemView);
     if (dragDropMode() == InternalMove) {
         if (event->source() != this || !(event->possibleActions() & Qt::MoveAction))
             return;
     }
     QModelIndex index;
     int col = -1;
     int row = -1;
     if (d->dropOn(event, &row, &col, &index)) {
         if (d->model->dropMimeData(event->mimeData(),
             dragDropMode() == InternalMove ? Qt::MoveAction : event->dropAction(), row, col, index)) {
                 if (dragDropMode() == InternalMove)
                     event->setDropAction(Qt::MoveAction);
                 event->accept();
         }
     }
     stopAutoScroll();
     setState(NoState);
     d->viewport->update();
 }
dropIndicatorPosition()
QAbstractItemView::DropIndicatorPosition QAbstractItemView::dropIndicatorPosition () const protected
Returns the position of the drop indicator in relation to the closest item.
Since
4.1
Definition at line 2631 of file qabstractitemview.cpp.
Referenced by QListWidget::dropMimeData(), QTableWidget::dropMimeData(), and QAbstractItemViewPrivate::dropOn().
 {
     Q_D(const QAbstractItemView);
     return d->dropIndicatorPosition;
 }
edit [1/2]
void QAbstractItemView::edit (const QModelIndex & index) slot
Starts editing the item corresponding to the given index if it is editable.
Note that this function does not change the current index. Since the current index defines the next and previous items to edit, users may find that keyboard navigation does not work as expected. To provide consistent navigation behavior, call setCurrentIndex() before this function with the same model index.
See also
QModelIndex::flags()
Definition at line 1211 of file qabstractitemview.cpp.
Referenced by QFileDialogPrivate::_q_createDirectory(), closeEditor(), currentChanged(), QListWidget::editItem(), QTableWidget::editItem(), QTreeWidget::editItem(), inputMethodEvent(), keyPressEvent(), QTreeView::mouseDoubleClickEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and timerEvent().
 {
     Q_D(QAbstractItemView);
     if (!d->isIndexValid(index))
         qWarning("edit: index was invalid");
     if (!edit(index, AllEditTriggers, 0))
         qWarning("edit: editing failed");
 }
edit() [2/2]
bool QAbstractItemView::edit (const QModelIndex & index, EditTrigger trigger, QEvent * event) protected virtual
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
The action that caused the editing process is described by trigger, and the associated event is specified by event.
Editing can be forced by specifying the trigger to be QAbstractItemView::AllEditTriggers.
See also
closeEditor()
Definition at line 2674 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (!d->isIndexValid(index))
         return false;
     if (QWidget *w = (d->persistent.isEmpty() ? static_cast<QWidget*>(0) : d->editorForIndex(index).widget.data())) {
         if (w->focusPolicy() == Qt::NoFocus)
             return false;
         w->setFocus();
         return true;
     }
     if (trigger == DoubleClicked) {
         d->delayedEditing.stop();
         d->delayedAutoScroll.stop();
     } else if (trigger == CurrentChanged) {
         d->delayedEditing.stop();
     }
     if (d->sendDelegateEvent(index, event)) {
         update(index);
         return true;
     }
     // save the previous trigger before updating
     EditTriggers lastTrigger = d->lastTrigger;
     d->lastTrigger = trigger;
     if (!d->shouldEdit(trigger, d->model->buddy(index)))
         return false;
     if (d->delayedEditing.isActive())
         return false;
     // we will receive a mouseButtonReleaseEvent after a
     // mouseDoubleClickEvent, so we need to check the previous trigger
     if (lastTrigger == DoubleClicked && trigger == SelectedClicked)
         return false;
     // we may get a double click event later
     if (trigger == SelectedClicked)
         d->delayedEditing.start(QApplication::doubleClickInterval(), this);
     else
         d->openEditor(index, d->shouldForwardEvent(trigger, event) ? event : 0);
     return true;
 }
editorDestroyed
void QAbstractItemView::editorDestroyed (QObject * editor) protected virtual slot
This function is called when the given editor has been destroyed.
See also
closeEditor()
Definition at line 2941 of file qabstractitemview.cpp.
Referenced by QAbstractItemViewPrivate::editor().
 {
     Q_D(QAbstractItemView);
     QWidget *w = qobject_cast<QWidget*>(editor);
     d->removeEditor(w);
     d->persistent.remove(w);
     if (state() == EditingState)
         setState(NoState);
 }
editTriggers()
EditTriggers QAbstractItemView::editTriggers () const
Referenced by closeEditor(), QColumnView::initializeColumn(), setEditTriggers(), QAbstractItemViewPrivate::shouldEdit(), and QAbstractItemViewPrivate::shouldForwardEvent().
entered
void QAbstractItemView::entered (const QModelIndex & index) signal
This signal is emitted when the mouse cursor enters the item specified by index.
Mouse tracking needs to be enabled for this feature to work.
See also
viewportEntered(), activated(), clicked(), doubleClicked(), pressed()
Referenced by QColumnViewPrivate::createColumn(), and QTreeWidget::QTreeWidget().
event()
bool QAbstractItemView::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Reimplemented in QCalendarView, QTreeWidget, QTableWidget, QListWidget, QHeaderView, and QListView.
Definition at line 1664 of file qabstractitemview.cpp.
Referenced by edit(), QListView::event(), QHeaderView::event(), QTableWidget::event(), QTreeWidget::event(), QCalendarView::event(), QAbstractItemViewPrivate::extendedSelectionCommand(), focusNextPrevChild(), QAbstractItemViewPrivate::multiSelectionCommand(), QAbstractItemViewPrivate::openEditor(), QTreeView::viewportEvent(), and viewportEvent().
 {
     Q_D(QAbstractItemView);
     switch (event->type()) {
     case QEvent::Paint:
         //we call this here because the scrollbars' visibility might be altered
         //so this can't be done in the paintEvent method
         d->executePostedLayout(); //make sure we set the layout properly
         break;
     case QEvent::Show:
         d->executePostedLayout(); //make sure we set the layout properly
         if (d->shouldScrollToCurrentOnShow) {
             d->shouldScrollToCurrentOnShow = false;
             const QModelIndex current = currentIndex();
             if (current.isValid() && (d->state == QAbstractItemView::EditingState || d->autoScroll))
                 scrollTo(current);
         }
         break;
     case QEvent::LocaleChange:
         viewport()->update();
         break;
     case QEvent::LayoutDirectionChange:
     case QEvent::ApplicationLayoutDirectionChange:
         updateGeometries();
         break;
     case QEvent::StyleChange:
         doItemsLayout();
         break;
     case QEvent::FocusOut:
         d->checkPersistentEditorFocus();
         break;
     case QEvent::FontChange:
         d->doDelayedItemsLayout(); // the size of the items will change
         break;
 #ifdef QT_SOFTKEYS_ENABLED
     case QEvent::LanguageChange:
         d->doneSoftKey->setText(QSoftKeyManager::standardSoftKeyText(QSoftKeyManager::DoneSoftKey));
         break;
 #endif
     default:
         break;
     }
     return QAbstractScrollArea::event(event);
 }
executeDelayedItemsLayout()
void QAbstractItemView::executeDelayedItemsLayout () protected
Executes the scheduled layouts without waiting for the event processing to begin.
See also
scheduleDelayedItemsLayout()
Definition at line 3825 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     d->executePostedLayout();
 }
focusInEvent()
void QAbstractItemView::focusInEvent (QFocusEvent * event) protected virtual
This function is called with the given event when the widget obtains the focus.
By default, the event is ignored.
See also
setFocus(), focusOutEvent()
Reimplemented from QWidget.
Definition at line 2240 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     QAbstractScrollArea::focusInEvent(event);
     const QItemSelectionModel* model = selectionModel();
     const bool currentIndexValid = currentIndex().isValid();
     if (model
         && !d->currentIndexSet
         && !currentIndexValid) {
         bool autoScroll = d->autoScroll;
         d->autoScroll = false;
         QModelIndex index = moveCursor(MoveNext, Qt::NoModifier); // first visible index
         if (index.isValid() && d->isIndexEnabled(index) && event->reason() != Qt::MouseFocusReason)
             selectionModel()->setCurrentIndex(index, QItemSelectionModel::NoUpdate);
         d->autoScroll = autoScroll;
     }
     if (model && currentIndexValid) {
         if (currentIndex().flags() != Qt::ItemIsEditable)
             setAttribute(Qt::WA_InputMethodEnabled, false);
         else
             setAttribute(Qt::WA_InputMethodEnabled);
     }
     if (!currentIndexValid)
         setAttribute(Qt::WA_InputMethodEnabled, false);
     d->viewport->update();
 }
focusNextPrevChild()
bool QAbstractItemView::focusNextPrevChild (bool next) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1649 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (d->tabKeyNavigation && isEnabled() && d->viewport->isEnabled()) {
         QKeyEvent event(QEvent::KeyPress, next ? Qt::Key_Tab : Qt::Key_Backtab, Qt::NoModifier);
         keyPressEvent(&event);
         if (event.isAccepted())
             return true;
     }
     return QAbstractScrollArea::focusNextPrevChild(next);
 }
focusOutEvent()
void QAbstractItemView::focusOutEvent (QFocusEvent * event) protected virtual
This function is called with the given event when the widget looses the focus.
By default, the event is ignored.
See also
clearFocus(), focusInEvent()
Reimplemented from QWidget.
Definition at line 2278 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     QAbstractScrollArea::focusOutEvent(event);
     d->viewport->update();
 #ifdef QT_SOFTKEYS_ENABLED
     if(!hasEditFocus())
         removeAction(d->doneSoftKey);
 #endif
 }
hasAutoScroll()
bool QAbstractItemView::hasAutoScroll () const
Definition at line 1388 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(const QAbstractItemView);
     return d->autoScroll;
 }
horizontalOffset()
int QAbstractItemView::horizontalOffset () const protected pure virtual
Returns the horizontal offset of the view.
In the base class this is a pure virtual function.
See also
verticalOffset()
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by startDrag().
horizontalScrollbarAction
void QAbstractItemView::horizontalScrollbarAction (int action) protected virtual slot
Warning
This function is not part of the public interface.
Reimplemented in QTreeView, and QTableView.
Definition at line 2835 of file qabstractitemview.cpp.
Referenced by QTableView::horizontalScrollbarAction(), and QTreeView::horizontalScrollbarAction().
 {
     //do nothing
 }
horizontalScrollbarValueChanged
void QAbstractItemView::horizontalScrollbarValueChanged (int value) protected virtual slot
Warning
This function is not part of the public interface.
Definition at line 2814 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (horizontalScrollBar()->maximum() == value && d->model->canFetchMore(d->root))
         d->model->fetchMore(d->root);
     QPoint posInVp = viewport()->mapFromGlobal(QCursor::pos());
     if (viewport()->rect().contains(posInVp))
         d->checkMouseMove(posInVp);
 }
horizontalScrollMode()
ScrollMode QAbstractItemView::horizontalScrollMode () const
Referenced by QTableView::columnCountChanged(), QColumnView::initializeColumn(), QTableView::paintEvent(), QTableView::scrollContentsBy(), QTreeView::scrollContentsBy(), QTableView::scrollTo(), setHorizontalScrollMode(), QTableView::updateGeometries(), and QTreeViewPrivate::updateScrollBars().
horizontalStepsPerItem()
int QAbstractItemView::horizontalStepsPerItem () const protected
Returns the horizontal scroll bar's steps per item.
See also
setHorizontalStepsPerItem() verticalStepsPerItem()
Definition at line 2981 of file qabstractitemview.cpp.
 {
     return 1;
 }
iconSize()
QSize QAbstractItemView::iconSize () const
Referenced by QColumnView::initializeColumn(), and setIconSize().
indexAt()
QModelIndex QAbstractItemView::indexAt (const QPoint & point) const pure virtual
Returns the model index of the item at the viewport coordinates point.
In the base class this is a pure virtual function.
See also
visualRect()
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by QFileDialogPrivate::_q_showContextMenu(), QAccessibleTable2::childAt(), QAccessibleTree::childAt(), dragMoveEvent(), QComboBoxPrivateContainer::eventFilter(), keyPressEvent(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), setVerticalScrollMode(), and viewportEvent().
indexWidget()
QWidget * QAbstractItemView::indexWidget (const QModelIndex & index) const
Returns the widget for the item at the given index.
Since
4.1
Definition at line 3275 of file qabstractitemview.cpp.
Referenced by QAccessibleItemView::accessibleAt(), QTableWidget::cellWidget(), QTreeView::drawRow(), QListWidget::itemWidget(), QTreeWidget::itemWidget(), keyPressEvent(), and setIndexWidget().
 {
     Q_D(const QAbstractItemView);
     if (d->isIndexValid(index))
         if (QWidget *editor = d->editorForIndex(index).widget.data())
             return editor;
     return 0;
 }
inputMethodEvent()
void QAbstractItemView::inputMethodEvent (QInputMethodEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2588 of file qabstractitemview.cpp.
 {
     if (event->commitString().isEmpty() && event->preeditString().isEmpty()) {
         event->ignore();
         return;
     }
     if (!edit(currentIndex(), AnyKeyPressed, event)) {
         if (!event->commitString().isEmpty())
             keyboardSearch(event->commitString());
         event->ignore();
     }
 }
inputMethodQuery()
QVariant QAbstractItemView::inputMethodQuery (Qt::InputMethodQuery query) const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 886 of file qabstractitemview.cpp.
 {
     const QModelIndex current = currentIndex();
     if (!current.isValid() || query != Qt::ImMicroFocus)
         return QAbstractScrollArea::inputMethodQuery(query);
     return visualRect(current);
 }
isIndexHidden()
bool QAbstractItemView::isIndexHidden (const QModelIndex & index) const protected pure virtual
Returns true if the item referred to by the given index is hidden in the view, otherwise returns false.
Hiding is a view specific feature. For example in TableView a column can be marked as hidden or a row in the TreeView.
In the base class this is a pure virtual function.
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by QAccessibleItemRow::children(), rowsAboutToBeRemoved(), selectedIndexes(), and QAccessibleItemRow::text().
itemDelegate() [1/2]
QAbstractItemDelegate * QAbstractItemView::itemDelegate () const
Returns the item delegate used by this view and model.
This is either one set with setItemDelegate(), or the default one.
See also
setItemDelegate()
Definition at line 878 of file qabstractitemview.cpp.
Referenced by QColumnViewPrivate::initialize(), QColumnView::initializeColumn(), QComboBox::itemDelegate(), QTreeViewPrivate::paintAlternatingRowColors(), QComboBox::setItemDelegate(), QFontComboBox::setWritingSystem(), QTableView::sizeHintForColumn(), and QTableView::sizeHintForRow().
 {
     return d_func()->itemDelegate;
 }
itemDelegate() [2/2]
QAbstractItemDelegate * QAbstractItemView::itemDelegate (const QModelIndex & index) const
Returns the item delegate used by this view and model for the given index.
Definition at line 1025 of file qabstractitemview.cpp.
 {
     Q_D(const QAbstractItemView);
     return d->delegateForIndex(index);
 }
itemDelegateForColumn()
QAbstractItemDelegate * QAbstractItemView::itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
Since
4.2
You can call itemDelegate() to get a pointer to the current delegate for a given index.
See also
setItemDelegateForColumn(), itemDelegateForRow(), itemDelegate()
Definition at line 1015 of file qabstractitemview.cpp.
 {
     Q_D(const QAbstractItemView);
     return d->columnDelegates.value(column, 0);
 }
itemDelegateForRow()
QAbstractItemDelegate * QAbstractItemView::itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
Since
4.2
You can call itemDelegate() to get a pointer to the current delegate for a given index.
See also
setItemDelegateForRow(), itemDelegateForColumn(), setItemDelegate()
Definition at line 952 of file qabstractitemview.cpp.
 {
     Q_D(const QAbstractItemView);
     return d->rowDelegates.value(row, 0);
 }
keyboardSearch()
void QAbstractItemView::keyboardSearch (const QString & search) virtual
Moves to and selects the item best matching the string search.
If no item is found nothing happens.
In the default implementation, the search is reset if search is empty, or the time interval since the last search has exceeded QApplication::keyboardInputInterval().
Reimplemented in QCalendarView, and QTreeView.
Definition at line 3029 of file qabstractitemview.cpp.
Referenced by inputMethodEvent(), QComboBoxPrivate::keyboardSearchString(), and keyPressEvent().
 {
     Q_D(QAbstractItemView);
     if (!d->model->rowCount(d->root) || !d->model->columnCount(d->root))
         return;
     QModelIndex start = currentIndex().isValid() ? currentIndex()
                         : d->model->index(0, 0, d->root);
     bool skipRow = false;
     bool keyboardTimeWasValid = d->keyboardInputTime.isValid();
     qint64 keyboardInputTimeElapsed = d->keyboardInputTime.restart();
     if (search.isEmpty() || !keyboardTimeWasValid
         || keyboardInputTimeElapsed > QApplication::keyboardInputInterval()) {
         d->keyboardInput = search;
         skipRow = currentIndex().isValid(); //if it is not valid we should really start at QModelIndex(0,0)
     } else {
         d->keyboardInput += search;
     }
     // special case for searches with same key like 'aaaaa'
     bool sameKey = false;
     if (d->keyboardInput.length() > 1) {
         int c = d->keyboardInput.count(d->keyboardInput.at(d->keyboardInput.length() - 1));
         sameKey = (c == d->keyboardInput.length());
         if (sameKey)
             skipRow = true;
     }
     // skip if we are searching for the same key or a new search started
     if (skipRow) {
         QModelIndex parent = start.parent();
         int newRow = (start.row() < d->model->rowCount(parent) - 1) ? start.row() + 1 : 0;
         start = d->model->index(newRow, start.column(), parent);
     }
     // search from start with wraparound
     const QString searchString = sameKey ? QString(d->keyboardInput.at(0)) : d->keyboardInput;
     QModelIndex current = start;
     QModelIndexList match;
     QModelIndex firstMatch;
     QModelIndex startMatch;
     QModelIndexList previous;
     do {
         match = d->model->match(current, Qt::DisplayRole, searchString);
         if (match == previous)
             break;
         firstMatch = match.value(0);
         previous = match;
         if (firstMatch.isValid()) {
             if (d->isIndexEnabled(firstMatch)) {
                 setCurrentIndex(firstMatch);
                 break;
             }
             int row = firstMatch.row() + 1;
             if (row >= d->model->rowCount(firstMatch.parent()))
                 row = 0;
             current = firstMatch.sibling(row, firstMatch.column());
             //avoid infinite loop if all the matching items are disabled.
             if (!startMatch.isValid())
                 startMatch = firstMatch;
             else if (startMatch == firstMatch)
                 break;
         }
     } while (current != start && firstMatch.isValid());
 }
keyPressEvent()
void QAbstractItemView::keyPressEvent (QKeyEvent * event) protected virtual
This function is called with the given event when a key event is sent to the widget.
The default implementation handles basic cursor movement, e.g. Up, Down, Left, Right, Home, PageUp, and PageDown; the activated() signal is emitted if the current index is valid and the activation key is pressed (e.g. Enter or Return, depending on the platform). This function is where editing is initiated by key press, e.g. if F2 is pressed.
See also
edit(), moveCursor(), keyboardSearch(), tabKeyNavigation
Reimplemented from QWidget.
Reimplemented in QCalendarView, and QTreeView.
Definition at line 2301 of file qabstractitemview.cpp.
Referenced by focusNextPrevChild(), QTreeView::keyPressEvent(), QFileDialogListView::keyPressEvent(), and QCalendarView::keyPressEvent().
 {
     Q_D(QAbstractItemView);
     d->delayedAutoScroll.stop(); //any interaction with the view cancel the auto scrolling
 #ifdef QT_KEYPAD_NAVIGATION
     switch (event->key()) {
     case Qt::Key_Select:
         if (QApplication::keypadNavigationEnabled()) {
             if (!hasEditFocus()) {
                 setEditFocus(true);
 #ifdef QT_SOFTKEYS_ENABLED
                 // If we can't keypad navigate to any direction, there is no sense to add
                 // "Done" softkey, since it basically does nothing when there is
                 // only one widget in screen
                 if(QWidgetPrivate::canKeypadNavigate(Qt::Horizontal)
                         || QWidgetPrivate::canKeypadNavigate(Qt::Vertical))
                     addAction(d->doneSoftKey);
 #endif
                 return;
             }
         }
         break;
     case Qt::Key_Back:
         if (QApplication::keypadNavigationEnabled() && hasEditFocus()) {
 #ifdef QT_SOFTKEYS_ENABLED
             removeAction(d->doneSoftKey);
 #endif
             setEditFocus(false);
         } else {
             event->ignore();
         }
         return;
     case Qt::Key_Down:
     case Qt::Key_Up:
         // Let's ignore vertical navigation events, only if there is no other widget
         // what can take the focus in vertical direction. This means widget can handle navigation events
         // even the widget don't have edit focus, and there is no other widget in requested direction.
         if(QApplication::keypadNavigationEnabled() && !hasEditFocus()
                 && QWidgetPrivate::canKeypadNavigate(Qt::Vertical)) {
             event->ignore();
             return;
         }
         break;
     case Qt::Key_Left:
     case Qt::Key_Right:
         // Similar logic as in up and down events
         if(QApplication::keypadNavigationEnabled() && !hasEditFocus()
                 && (QWidgetPrivate::canKeypadNavigate(Qt::Horizontal) || QWidgetPrivate::inTabWidget(this))) {
             event->ignore();
             return;
         }
         break;
     default:
         if (QApplication::keypadNavigationEnabled() && !hasEditFocus()) {
             event->ignore();
             return;
         }
     }
 #endif
 #if !defined(QT_NO_CLIPBOARD) && !defined(QT_NO_SHORTCUT)
     if (event == QKeySequence::Copy) {
         QVariant variant;
         if (d->model)
             variant = d->model->data(currentIndex(), Qt::DisplayRole);
         if (variant.type() == QVariant::String)
             QApplication::clipboard()->setText(variant.toString());
         event->accept();
     }
 #endif
     QPersistentModelIndex newCurrent;
     d->moveCursorUpdatedView = false;
     switch (event->key()) {
     case Qt::Key_Down:
         newCurrent = moveCursor(MoveDown, event->modifiers());
         break;
     case Qt::Key_Up:
         newCurrent = moveCursor(MoveUp, event->modifiers());
         break;
     case Qt::Key_Left:
         newCurrent = moveCursor(MoveLeft, event->modifiers());
         break;
     case Qt::Key_Right:
         newCurrent = moveCursor(MoveRight, event->modifiers());
         break;
     case Qt::Key_Home:
         newCurrent = moveCursor(MoveHome, event->modifiers());
         break;
     case Qt::Key_End:
         newCurrent = moveCursor(MoveEnd, event->modifiers());
         break;
     case Qt::Key_PageUp:
         newCurrent = moveCursor(MovePageUp, event->modifiers());
         break;
     case Qt::Key_PageDown:
         newCurrent = moveCursor(MovePageDown, event->modifiers());
         break;
     case Qt::Key_Tab:
         if (d->tabKeyNavigation)
             newCurrent = moveCursor(MoveNext, event->modifiers());
         break;
     case Qt::Key_Backtab:
         if (d->tabKeyNavigation)
             newCurrent = moveCursor(MovePrevious, event->modifiers());
         break;
     }
     QPersistentModelIndex oldCurrent = currentIndex();
     if (newCurrent != oldCurrent && newCurrent.isValid() && d->isIndexEnabled(newCurrent)) {
         if (!hasFocus() && QApplication::focusWidget() == indexWidget(oldCurrent))
             setFocus();
         QItemSelectionModel::SelectionFlags command = selectionCommand(newCurrent, event);
         if (command != QItemSelectionModel::NoUpdate
              || style()->styleHint(QStyle::SH_ItemView_MovementWithoutUpdatingSelection, 0, this)) {
             // note that we don't check if the new current index is enabled because moveCursor() makes sure it is
             if (command & QItemSelectionModel::Current) {
                 d->selectionModel->setCurrentIndex(newCurrent, QItemSelectionModel::NoUpdate);
                 if (!indexAt(d->pressedPosition - d->offset()).isValid())
                     d->pressedPosition = visualRect(oldCurrent).center() + d->offset();
                 QRect rect(d->pressedPosition - d->offset(), visualRect(newCurrent).center());
                 setSelection(rect, command);
             } else {
                 d->selectionModel->setCurrentIndex(newCurrent, command);
                 d->pressedPosition = visualRect(newCurrent).center() + d->offset();
                 if (newCurrent.isValid()) {
                     // We copy the same behaviour as for mousePressEvent().
                     QRect rect(d->pressedPosition - d->offset(), QSize(1, 1));
                     setSelection(rect, command);
                 }
             }
             event->accept();
             return;
         }
     }
     switch (event->key()) {
     // ignored keys
     case Qt::Key_Down:
     case Qt::Key_Up:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled() && QWidgetPrivate::canKeypadNavigate(Qt::Vertical)) {
             event->accept(); // don't change focus
             break;
         }
 #endif
     case Qt::Key_Left:
     case Qt::Key_Right:
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::navigationMode() == Qt::NavigationModeKeypadDirectional
                 && (QWidgetPrivate::canKeypadNavigate(Qt::Horizontal)
                 || (QWidgetPrivate::inTabWidget(this) && d->model->columnCount(d->root) > 1))) {
             event->accept(); // don't change focus
             break;
         }
 #endif // QT_KEYPAD_NAVIGATION
     case Qt::Key_Home:
     case Qt::Key_End:
     case Qt::Key_PageUp:
     case Qt::Key_PageDown:
     case Qt::Key_Escape:
     case Qt::Key_Shift:
     case Qt::Key_Control:
     case Qt::Key_Delete:
     case Qt::Key_Backspace:
         event->ignore();
         break;
     case Qt::Key_Space:
     case Qt::Key_Select:
         if (!edit(currentIndex(), AnyKeyPressed, event) && d->selectionModel)
             d->selectionModel->select(currentIndex(), selectionCommand(currentIndex(), event));
 #ifdef QT_KEYPAD_NAVIGATION
         if ( event->key()==Qt::Key_Select ) {
             // Also do Key_Enter action.
             if (currentIndex().isValid()) {
                 if (state() != EditingState)
                     emit activated(currentIndex());
             } else {
                 event->ignore();
             }
         }
 #endif
         break;
 #ifdef Q_WS_MAC
     case Qt::Key_Enter:
     case Qt::Key_Return:
         // Propagate the enter if you couldn't edit the item and there are no
         // current editors (if there are editors, the event was most likely propagated from it).
         if (!edit(currentIndex(), EditKeyPressed, event) && d->editorIndexHash.isEmpty())
             event->ignore();
         break;
 #else
     case Qt::Key_F2:
         if (!edit(currentIndex(), EditKeyPressed, event))
             event->ignore();
         break;
     case Qt::Key_Enter:
     case Qt::Key_Return:
         // ### we can't open the editor on enter, becuse
         // some widgets will forward the enter event back
         // to the viewport, starting an endless loop
         if (state() != EditingState || hasFocus()) {
             if (currentIndex().isValid())
                 emit activated(currentIndex());
             event->ignore();
         }
         break;
 #endif
     case Qt::Key_A:
         if (event->modifiers() & Qt::ControlModifier) {
             selectAll();
             break;
         }
     default: {
 #ifdef Q_WS_MAC
         if (event->key() == Qt::Key_O && event->modifiers() & Qt::ControlModifier && currentIndex().isValid()) {
             emit activated(currentIndex());
             break;
         }
 #endif
         bool modified = (event->modifiers() & (Qt::ControlModifier | Qt::AltModifier | Qt::MetaModifier));
         if (!event->text().isEmpty() && !modified && !edit(currentIndex(), AnyKeyPressed, event)) {
             keyboardSearch(event->text());
             event->accept();
         } else {
             event->ignore();
         }
         break; }
     }
     if (d->moveCursorUpdatedView)
         event->accept();
 }
model()
QAbstractItemModel * QAbstractItemView::model () const
Returns the model that this view is presenting.
Definition at line 768 of file qabstractitemview.cpp.
Referenced by QAbstractItemViewPrivate::_q_columnsAboutToBeRemoved(), QHeaderViewPrivate::_q_layoutAboutToBeChanged(), QAbstractItemViewPrivate::_q_modelDestroyed(), QTreeViewPrivate::_q_sortIndicatorChanged(), QAccessibleTable2::cellAt(), QTableWidget::cellWidget(), QAccessibleTree::childAt(), QAccessibleTable2::childCount(), QAccessibleTree::childCount(), QAccessibleItemView::childCount(), QAccessibleTable2::childFromLogical(), QAccessibleItemView::childIndex(), QAbstractItemViewPrivate::clearOrRemove(), QSidebar::clicked(), QColumnViewPrivate::closeColumns(), QAccessibleTable2::columnCount(), QAccessibleItemView::columnCount(), QAccessibleTable2::columnDescription(), QAccessibleItemView::columnDescription(), QAccessibleItemView::columnIndex(), QColumnView::createColumn(), QColumnViewPrivate::createColumn(), QColumnView::currentChanged(), QListWidget::dropEvent(), QTreeWidget::dropEvent(), QListWidget::dropMimeData(), QTableWidget::dropMimeData(), QTreeWidget::dropMimeData(), QAbstractItemViewPrivate::dropOn(), QCalendarView::event(), QTreeWidgetItem::executePendingSort(), QTreeViewPrivate::expand(), QAbstractItemViewPrivate::fetchMore(), QListWidget::findItems(), QTableWidget::findItems(), QTreeWidget::findItems(), QHeaderViewPrivate::flipSortIndicator(), focusInEvent(), QCalendarView::handleMouseEvent(), QTreeViewPrivate::hasVisibleChildren(), QListModel::index(), QAccessibleItemView::index(), QAccessibleTree::indexFromLogical(), QAccessibleTable2::indexOfChild(), QAccessibleTree::indexOfChild(), QSidebar::init(), QColumnView::initializeColumn(), QTreeWidgetItem::insertChild(), QTreeWidgetItem::insertChildren(), QAccessibleTable2Cell::isExpandable(), QAccessibleTable2Cell::isValid(), QAccessibleTable2HeaderCell::isValid(), QTreeWidgetItem::itemChanged(), QCalendarView::keyPressEvent(), QTreeViewPrivate::layout(), QTreeWidget::mimeTypes(), QFontListView::model(), ModelIndexIterator::ModelIndexIterator(), QCalendarView::mouseDoubleClickEvent(), QCalendarView::mouseMoveEvent(), QCalendarView::mousePressEvent(), QCalendarView::mouseReleaseEvent(), QColumnView::moveCursor(), QTableView::moveCursor(), QTreeView::moveCursor(), QCalendarView::moveCursor(), QAccessibleTree::navigate(), QAbstractItemViewPrivate::openEditor(), QAbstractItemViewPrivate::position(), QListWidgetItem::QListWidgetItem(), QTreeWidget::QTreeWidget(), QTreeWidgetItem::QTreeWidgetItem(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), QSidebar::removeEntry(), QAccessibleTable2::rowCount(), QAccessibleItemView::rowCount(), QAccessibleTable2::rowDescription(), QAccessibleItemView::rowDescription(), QAccessibleItemView::rowIndex(), QTreeViewPrivate::select(), QColumnView::selectAll(), QAbstractItemViewPrivate::selectAll(), QListViewPrivate::selectAll(), QAccessibleTable2::selectColumn(), QTableViewPrivate::selectColumn(), QAccessibleTable2::selectRow(), QTableViewPrivate::selectRow(), QSidebar::selectUrl(), QAbstractItemViewPrivate::sendDelegateEvent(), QTableWidget::setCellWidget(), QTableWidget::setCurrentCell(), QListWidgetItem::setData(), QTableWidgetItem::setData(), QTreeWidgetItem::setData(), QListWidgetItem::setFlags(), QTableWidget::setHorizontalHeaderLabels(), QHeaderView::setModel(), setModel(), QCompleter::setPopup(), QTableWidget::setRangeSelected(), QColumnView::setRootIndex(), QAccessibleItemRow::setText(), QAccessibleTable2Cell::setText(), QTableWidget::setVerticalHeaderLabels(), QComboBox::setView(), QAbstractItemViewPrivate::shouldEdit(), QCompleterPrivate::showPopup(), QSidebar::sizeHint(), QTableView::sizeHintForColumn(), QTableView::sizeHintForRow(), QTreeWidgetItem::sortChildren(), QTreeWidget::supportedDropActions(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::takeChildren(), QAccessibleHeader::text(), QAccessibleItemRow::text(), QAccessibleTable2Cell::text(), QAccessibleTable2HeaderCell::text(), QAccessibleItemRow::text_helper(), QAccessibleTable2::unselectColumn(), QAccessibleTable2::unselectRow(), QColumnView::visualRegionForSelection(), QCalendarView::wheelEvent(), QListWidgetItem::~QListWidgetItem(), QTableWidgetItem::~QTableWidgetItem(), and QTreeWidgetItem::~QTreeWidgetItem().
 {
     Q_D(const QAbstractItemView);
     return (d->model == QAbstractItemModelPrivate::staticEmptyModel() ? 0 : d->model);
 }
mouseDoubleClickEvent()
void QAbstractItemView::mouseDoubleClickEvent (QMouseEvent * event) protected virtual
This function is called with the given event when a mouse button is double clicked inside the widget.
If the double-click is on a valid item it emits the doubleClicked() signal and calls edit() on the item.
Reimplemented from QWidget.
Reimplemented in QCalendarView, QHeaderView, and QTreeView.
Definition at line 1956 of file qabstractitemview.cpp.
Referenced by QCalendarView::mouseDoubleClickEvent().
 {
     Q_D(QAbstractItemView);
     QModelIndex index = indexAt(event->pos());
     if (!index.isValid()
         || !d->isIndexEnabled(index)
         || (d->pressedIndex != index)) {
         QMouseEvent me(QEvent::MouseButtonPress,
                        event->pos(), event->button(),
                        event->buttons(), event->modifiers());
         mousePressEvent(&me);
         return;
     }
     // signal handlers may change the model
     QPersistentModelIndex persistent = index;
     emit doubleClicked(persistent);
     if ((event->button() & Qt::LeftButton) && !edit(persistent, DoubleClicked, event)
         && !style()->styleHint(QStyle::SH_ItemView_ActivateItemOnSingleClick, 0, this))
         emit activated(persistent);
 }
mouseMoveEvent()
void QAbstractItemView::mouseMoveEvent (QMouseEvent * event) protected virtual
This function is called with the given event when a mouse move event is sent to the widget.
If a selection is in progress and new items are moved over the selection is extended; if a drag is in progress it is continued.
Reimplemented from QWidget.
Reimplemented in QCalendarView, QHeaderView, QTreeView, and QListView.
Definition at line 1837 of file qabstractitemview.cpp.
Referenced by QListView::mouseMoveEvent(), QTreeView::mouseMoveEvent(), and QCalendarView::mouseMoveEvent().
 {
     Q_D(QAbstractItemView);
     QPoint topLeft;
     QPoint bottomRight = event->pos();
     if (state() == ExpandingState || state() == CollapsingState)
         return;
 #ifndef QT_NO_DRAGANDDROP
     if (state() == DraggingState) {
         topLeft = d->pressedPosition - d->offset();
         if ((topLeft - bottomRight).manhattanLength() > QApplication::startDragDistance()) {
             d->pressedIndex = QModelIndex();
             startDrag(d->model->supportedDragActions());
             setState(NoState); // the startDrag will return when the dnd operation is done
             stopAutoScroll();
         }
         return;
     }
 #endif // QT_NO_DRAGANDDROP
     QPersistentModelIndex index = indexAt(bottomRight);
     QModelIndex buddy = d->model->buddy(d->pressedIndex);
     if ((state() == EditingState && d->hasEditor(buddy))
         || edit(index, NoEditTriggers, event))
         return;
     if (d->selectionMode != SingleSelection)
         topLeft = d->pressedPosition - d->offset();
     else
         topLeft = bottomRight;
     d->checkMouseMove(index);
 #ifndef QT_NO_DRAGANDDROP
     if (d->pressedIndex.isValid()
         && d->dragEnabled
         && (state() != DragSelectingState)
         && (event->buttons() != Qt::NoButton)
         && !d->selectedDraggableIndexes().isEmpty()) {
             setState(DraggingState);
             return;
     }
 #endif
     if ((event->buttons() & Qt::LeftButton) && d->selectionAllowed(index) && d->selectionModel) {
         setState(DragSelectingState);
         QItemSelectionModel::SelectionFlags command = selectionCommand(index, event);
         if (d->ctrlDragSelectionFlag != QItemSelectionModel::NoUpdate && command.testFlag(QItemSelectionModel::Toggle)) {
             command &= ~QItemSelectionModel::Toggle;
             command |= d->ctrlDragSelectionFlag;
         }
         // Do the normalize ourselves, since QRect::normalized() is flawed
         QRect selectionRect = QRect(topLeft, bottomRight);
         setSelection(selectionRect, command);
         // set at the end because it might scroll the view
         if (index.isValid()
             && (index != d->selectionModel->currentIndex())
             && d->isIndexEnabled(index))
             d->selectionModel->setCurrentIndex(index, QItemSelectionModel::NoUpdate);
     }
 }
mousePressEvent()
void QAbstractItemView::mousePressEvent (QMouseEvent * event) protected virtual
This function is called with the given event when a mouse button is pressed while the cursor is inside the widget.
If a valid item is pressed on it is made into the current item. This function emits the pressed() signal.
Reimplemented from QWidget.
Reimplemented in QCalendarView, QHeaderView, and QTreeView.
Definition at line 1778 of file qabstractitemview.cpp.
Referenced by mouseDoubleClickEvent(), QTreeView::mousePressEvent(), and QCalendarView::mousePressEvent().
 {
     Q_D(QAbstractItemView);
     d->delayedAutoScroll.stop(); //any interaction with the view cancel the auto scrolling
     QPoint pos = event->pos();
     QPersistentModelIndex index = indexAt(pos);
     if (!d->selectionModel
         || (d->state == EditingState && d->hasEditor(index)))
         return;
     d->pressedAlreadySelected = d->selectionModel->isSelected(index);
     d->pressedIndex = index;
     d->pressedModifiers = event->modifiers();
     QItemSelectionModel::SelectionFlags command = selectionCommand(index, event);
     d->noSelectionOnMousePress = command == QItemSelectionModel::NoUpdate || !index.isValid();
     QPoint offset = d->offset();
     if ((command & QItemSelectionModel::Current) == 0)
         d->pressedPosition = pos + offset;
     else if (!indexAt(d->pressedPosition - offset).isValid())
         d->pressedPosition = visualRect(currentIndex()).center() + offset;
     if (edit(index, NoEditTriggers, event))
         return;
     if (index.isValid() && d->isIndexEnabled(index)) {
         // we disable scrollTo for mouse press so the item doesn't change position
         // when the user is interacting with it (ie. clicking on it)
         bool autoScroll = d->autoScroll;
         d->autoScroll = false;
         d->selectionModel->setCurrentIndex(index, QItemSelectionModel::NoUpdate);
         d->autoScroll = autoScroll;
         QRect rect(d->pressedPosition - offset, pos);
         if (command.testFlag(QItemSelectionModel::Toggle)) {
             command &= ~QItemSelectionModel::Toggle;
             d->ctrlDragSelectionFlag = d->selectionModel->isSelected(index) ? QItemSelectionModel::Deselect : QItemSelectionModel::Select;
             command |= d->ctrlDragSelectionFlag;
         }
         setSelection(rect, command);
         // signal handlers may change the model
         emit pressed(index);
         if (d->autoScroll) {
             //we delay the autoscrolling to filter out double click event
             //100 is to be sure that there won't be a double-click misinterpreted as a 2 single clicks
             d->delayedAutoScroll.start(QApplication::doubleClickInterval()+100, this);
         }
     } else {
         // Forces a finalize() even if mouse is pressed, but not on a item
         d->selectionModel->select(QModelIndex(), QItemSelectionModel::Select);
     }
 }
mouseReleaseEvent()
void QAbstractItemView::mouseReleaseEvent (QMouseEvent * event) protected virtual
This function is called with the given event when a mouse button is released, after a mouse press event on the widget.
If a user presses the mouse inside your widget and then drags the mouse to another location before releasing the mouse button, your widget receives the release event. The function will emit the clicked() signal if an item was being pressed.
Reimplemented from QWidget.
Reimplemented in QCalendarView, QHeaderView, QTreeView, and QListView.
Definition at line 1910 of file qabstractitemview.cpp.
Referenced by QListView::mouseReleaseEvent(), QTreeView::mouseReleaseEvent(), and QCalendarView::mouseReleaseEvent().
 {
     Q_D(QAbstractItemView);
     QPoint pos = event->pos();
     QPersistentModelIndex index = indexAt(pos);
     if (state() == EditingState) {
         if (d->isIndexValid(index)
             && d->isIndexEnabled(index)
             && d->sendDelegateEvent(index, event))
             update(index);
         return;
     }
     bool click = (index == d->pressedIndex && index.isValid());
     bool selectedClicked = click && (event->button() & Qt::LeftButton) && d->pressedAlreadySelected;
     EditTrigger trigger = (selectedClicked ? SelectedClicked : NoEditTriggers);
     bool edited = edit(index, trigger, event);
     d->ctrlDragSelectionFlag = QItemSelectionModel::NoUpdate;
     if (d->selectionModel && d->noSelectionOnMousePress) {
         d->noSelectionOnMousePress = false;
         d->selectionModel->select(index, selectionCommand(index, event));
     }
     setState(NoState);
     if (click) {
         emit clicked(index);
         if (edited)
             return;
         QStyleOptionViewItemV4 option = d->viewOptionsV4();
         if (d->pressedAlreadySelected)
             option.state |= QStyle::State_Selected;
         if (style()->styleHint(QStyle::SH_ItemView_ActivateItemOnSingleClick, &option, this))
             emit activated(index);
     }
 }
moveCursor()
QModelIndex QAbstractItemView::moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers) protected pure virtual
Returns a QModelIndex object pointing to the next object in the view, based on the given cursorAction and keyboard modifiers specified by modifiers.
In the base class this is a pure virtual function.
Implemented in QCalendarView, QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by closeEditor(), focusInEvent(), keyPressEvent(), and QAccessibleItemRow::navigate().
openPersistentEditor()
void QAbstractItemView::openPersistentEditor (const QModelIndex & index)
Opens a persistent editor on the item at the given index.
If no editor exists, the delegate will create a new editor.
See also
closePersistentEditor()
Definition at line 3186 of file qabstractitemview.cpp.
Referenced by QListWidget::addItems(), QListWidget::openPersistentEditor(), QTableWidget::openPersistentEditor(), and QTreeWidget::openPersistentEditor().
 {
     Q_D(QAbstractItemView);
     QStyleOptionViewItemV4 options = d->viewOptionsV4();
     options.rect = visualRect(index);
     options.state |= (index == currentIndex() ? QStyle::State_HasFocus : QStyle::State_None);
     QWidget *editor = d->editor(index, options);
     if (editor) {
         editor->show();
         d->persistent.insert(editor);
     }
 }
pressed
void QAbstractItemView::pressed (const QModelIndex & index) signal
This signal is emitted when a mouse button is pressed.
The item the mouse was pressed on is specified by index. The signal is only emitted when the index is valid.
Use the QApplication::mouseButtons() function to get the state of the mouse buttons.
See also
activated(), clicked(), doubleClicked(), entered()
Referenced by QColumnViewPrivate::createColumn(), mousePressEvent(), and QTreeWidget::QTreeWidget().
reset
void QAbstractItemView::reset () virtual slot
Reset the internal state of the view.
Warning
This function will reset open editors, scroll bar positions, selections, etc. Existing changes will not be committed. If you would like to save your changes when resetting the view, you can reimplement this function, commit your changes, and then call the superclass' implementation.
Reimplemented in QHeaderView, QTreeView, and QListView.
Definition at line 1128 of file qabstractitemview.cpp.
Referenced by QListView::reset(), QTreeView::reset(), QHeaderView::reset(), setModel(), and timerEvent().
 {
     Q_D(QAbstractItemView);
     d->delayedReset.stop(); //make sure we stop the timer
     foreach (const QEditorInfo &info, d->indexEditorHash) {
         if (info.widget)
             d->releaseEditor(info.widget.data());
     }
     d->editorIndexHash.clear();
     d->indexEditorHash.clear();
     d->persistent.clear();
     d->currentIndexSet = false;
     setState(NoState);
     setRootIndex(QModelIndex());
     if (d->selectionModel)
         d->selectionModel->reset();
 #ifndef QT_NO_ACCESSIBILITY
 #ifdef Q_WS_X11
     if (QAccessible::isActive()) {
         QAccessible::queryAccessibleInterface(this)->table2Interface()->modelReset();
         QAccessible::updateAccessibility(this, 0, QAccessible::TableModelChanged);
     }
 #endif
 #endif
 }
resizeEvent()
void QAbstractItemView::resizeEvent (QResizeEvent * event) protected virtual
This function is called with the given event when a resize event is sent to the widget.
See also
QWidget::resizeEvent()
Reimplemented from QWidget.
Reimplemented in QListView, QColumnView, QComboBoxListView, and QColumnViewPreviewColumn.
Definition at line 2541 of file qabstractitemview.cpp.
Referenced by QColumnView::resizeEvent(), and QListView::resizeEvent().
 {
     QAbstractScrollArea::resizeEvent(event);
     updateGeometries();
 }
rootIndex()
QModelIndex QAbstractItemView::rootIndex () const
Returns the model index of the model's root item.
The root item is the parent item to the view's toplevel items. The root can be invalid.
See also
setRootIndex()
Definition at line 1176 of file qabstractitemview.cpp.
Referenced by QColumnViewPrivate::checkColumnCreation(), dragMoveEvent(), ModelIndexIterator::ModelIndexIterator(), QColumnView::moveCursor(), QTreeView::moveCursor(), QColumnView::selectAll(), QTableWidget::setRangeSelected(), and QColumnView::visualRegionForSelection().
 {
     return QModelIndex(d_func()->root);
 }
rowsAboutToBeRemoved
void QAbstractItemView::rowsAboutToBeRemoved (const QModelIndex & parent, int start, int end) protected virtual slot
This slot is called when rows are about to be removed.
The deleted rows are those under the given parent from start to end inclusive.
See also
rowsInserted()
Reimplemented in QTreeView, and QListView.
Definition at line 3395 of file qabstractitemview.cpp.
Referenced by QListView::rowsAboutToBeRemoved(), QTreeView::rowsAboutToBeRemoved(), QHeaderView::setModel(), and setModel().
 {
     Q_D(QAbstractItemView);
     setState(CollapsingState);
     // Ensure one selected item in single selection mode.
     QModelIndex current = currentIndex();
     if (d->selectionMode == SingleSelection
         && current.isValid()
         && current.row() >= start
         && current.row() <= end
         && current.parent() == parent) {
         int totalToRemove = end - start + 1;
         if (d->model->rowCount(parent) <= totalToRemove) { // no more children
             QModelIndex index = parent;
             while (index != d->root && !d->isIndexEnabled(index))
                 index = index.parent();
             if (index != d->root)
                 setCurrentIndex(index);
         } else {
             int row = end + 1;
             QModelIndex next;
             do { // find the next visible and enabled item
                 next = d->model->index(row++, current.column(), current.parent());
             } while (next.isValid() && (isIndexHidden(next) || !d->isIndexEnabled(next)));
             if (row > d->model->rowCount(parent)) {
                 row = start - 1;
                 do { // find the previous visible and enabled item
                     next = d->model->index(row--, current.column(), current.parent());
                 } while (next.isValid() && (isIndexHidden(next) || !d->isIndexEnabled(next)));
             }
             setCurrentIndex(next);
         }
     }
     // Remove all affected editors; this is more efficient than waiting for updateGeometries() to clean out editors for invalid indexes
     QEditorIndexHash::iterator i = d->editorIndexHash.begin();
     while (i != d->editorIndexHash.end()) {
         const QModelIndex index = i.value();
         if (index.row() >= start && index.row() <= end && d->model->parent(index) == parent) {
             QWidget *editor = i.key();
             QEditorInfo info = d->indexEditorHash.take(index);
             i = d->editorIndexHash.erase(i);
             if (info.widget)
                 d->releaseEditor(editor);
         } else {
             ++i;
         }
     }
 }
rowsInserted
void QAbstractItemView::rowsInserted (const QModelIndex & parent, int start, int end) protected virtual slot
This slot is called when rows are inserted.
The new rows are those under the given parent from start to end inclusive. The base class implementation calls fetchMore() on the model to check for more data.
See also
rowsAboutToBeRemoved()
Reimplemented in QHeaderView, QTreeView, QListView, and QColumnView.
Definition at line 3381 of file qabstractitemview.cpp.
Referenced by QColumnView::rowsInserted(), QListView::rowsInserted(), QTreeView::rowsInserted(), QTableView::setModel(), and setModel().
 {
     if (!isVisible())
         d_func()->fetchMoreTimer.start(0, this); //fetch more later
     else
         updateEditorGeometries();
 }
scheduleDelayedItemsLayout()
void QAbstractItemView::scheduleDelayedItemsLayout () protected
Schedules a layout of the items in the view to be executed when the event processing starts.
Even if scheduleDelayedItemsLayout() is called multiple times before events are processed, the view will only do the layout once.
See also
executeDelayedItemsLayout()
Definition at line 3813 of file qabstractitemview.cpp.
Referenced by QTreeWidgetItem::setChildIndicatorPolicy().
 {
     Q_D(QAbstractItemView);
     d->doDelayedItemsLayout();
 }
scrollDirtyRegion()
void QAbstractItemView::scrollDirtyRegion (int dx, int dy) protected
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
You only need to call this function if you are implementing a scrolling viewport in your view subclass.
If you implement scrollContentsBy() in a subclass of QAbstractItemView, call this function before you call QWidget::scroll() on the viewport. Alternatively, just call update().
See also
scrollContentsBy(), dirtyRegionOffset(), setDirtyRegion()
Definition at line 3860 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     d->scrollDirtyRegion(dx, dy);
 }
scrollTo()
void QAbstractItemView::scrollTo (const QModelIndex & index, ScrollHint hint = EnsureVisible) pure virtual
Scrolls the view if necessary to ensure that the item at index is visible.
The view will try to position the item according to the given hint.
In the base class this is a pure virtual function.
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by currentChanged(), event(), QCompleterPrivate::setCurrentIndex(), setVerticalScrollMode(), QComboBox::showPopup(), and timerEvent().
scrollToBottom
void QAbstractItemView::scrollToBottom () slot
Scrolls the view to the bottom.
Since
4.1
See also
scrollTo(), scrollToTop()
Definition at line 3310 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (d->delayedPendingLayout) {
         d->executePostedLayout();
         updateGeometries();
     }
     verticalScrollBar()->setValue(verticalScrollBar()->maximum());
 }
scrollToTop
void QAbstractItemView::scrollToTop () slot
Scrolls the view to the top.
Since
4.1
See also
scrollTo(), scrollToBottom()
Definition at line 3295 of file qabstractitemview.cpp.
Referenced by QCompleterPrivate::setCurrentIndex().
 {
     verticalScrollBar()->setValue(verticalScrollBar()->minimum());
 }
selectAll
void QAbstractItemView::selectAll () virtual slot
Selects all items in the view.
This function will use the selection behavior set on the view when selecting.
See also
setSelection(), selectedIndexes(), clearSelection()
Reimplemented in QTreeView, and QColumnView.
Definition at line 1188 of file qabstractitemview.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QAbstractItemView);
     SelectionMode mode = d->selectionMode;
     if (mode == MultiSelection || mode == ExtendedSelection)
         d->selectAll(QItemSelectionModel::ClearAndSelect
                      |d->selectionBehaviorFlags());
     else if (mode != SingleSelection)
         d->selectAll(selectionCommand(d->model->index(0, 0, d->root)));
 }
selectedIndexes()
QModelIndexList QAbstractItemView::selectedIndexes () const protected virtual
This convenience function returns a list of all selected and non-hidden item indexes in the view.
The list contains no duplicates, and is not sorted.
See also
QItemSelectionModel::selectedIndexes()
Reimplemented in QTreeView, QListView, and QTableView.
Definition at line 2645 of file qabstractitemview.cpp.
Referenced by QAbstractItemViewPrivate::droppingOnItself().
 {
     Q_D(const QAbstractItemView);
     QModelIndexList indexes;
     if (d->selectionModel) {
         indexes = d->selectionModel->selectedIndexes();
         QList<QModelIndex>::iterator it = indexes.begin();
         while (it != indexes.end())
             if (isIndexHidden(*it))
                 it = indexes.erase(it);
             else
                 ++it;
     }
     return indexes;
 }
selectionBehavior()
QAbstractItemView::SelectionBehavior QAbstractItemView::selectionBehavior () const
Referenced by QTreeViewPrivate::adjustViewOptionsForIndex(), QTreeView::drawBranches(), QTreeView::drawRow(), QColumnView::initializeColumn(), and setSelectionBehavior().
selectionChanged
void QAbstractItemView::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) protected virtual slot
This slot is called when the selection is changed.
The previous selection (which may be empty), is specified by deselected, and the new selection by selected.
See also
setSelection()
Reimplemented in QTreeView, QListView, and QTableView.
Definition at line 3654 of file qabstractitemview.cpp.
Referenced by QTableView::selectionChanged(), QListView::selectionChanged(), QTreeView::selectionChanged(), and setSelectionModel().
 {
     Q_D(QAbstractItemView);
     if (isVisible() && updatesEnabled()) {
         d->viewport->update(visualRegionForSelection(deselected) | visualRegionForSelection(selected));
     }
 }
selectionCommand()
QItemSelectionModel::SelectionFlags QAbstractItemView::selectionCommand (const QModelIndex & index, const QEvent * event = 0) const protected virtual
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
The event is a user input event, such as a mouse or keyboard event.
Reimplement this function to define your own selection behavior.
See also
setSelection()
Definition at line 3948 of file qabstractitemview.cpp.
Referenced by keyPressEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), selectAll(), and setCurrentIndex().
 {
     Q_D(const QAbstractItemView);
     switch (d->selectionMode) {
         case NoSelection: // Never update selection model
             return QItemSelectionModel::NoUpdate;
         case SingleSelection: // ClearAndSelect on valid index otherwise NoUpdate
             if (event && event->type() == QEvent::MouseButtonRelease)
                 return QItemSelectionModel::NoUpdate;
             return QItemSelectionModel::ClearAndSelect|d->selectionBehaviorFlags();
         case MultiSelection:
             return d->multiSelectionCommand(index, event);
         case ExtendedSelection:
             return d->extendedSelectionCommand(index, event);
         case ContiguousSelection:
             return d->contiguousSelectionCommand(index, event);
     }
     return QItemSelectionModel::NoUpdate;
 }
selectionMode()
QAbstractItemView::SelectionMode QAbstractItemView::selectionMode () const
Referenced by QAbstractItemViewPrivate::_q_columnsAboutToBeRemoved(), QColumnView::initializeColumn(), and setSelectionMode().
selectionModel()
QItemSelectionModel * QAbstractItemView::selectionModel () const
Returns the current selection model.
See also
setSelectionModel(), selectedIndexes()
Definition at line 823 of file qabstractitemview.cpp.
Referenced by QColumnViewPrivate::_q_clicked(), QAbstractItemViewPrivate::checkPersistentEditorFocus(), QListWidget::clear(), QTableWidget::clear(), QTreeWidget::clear(), QTableWidget::clearContents(), QAbstractItemViewPrivate::clearOrRemove(), closePersistentEditor(), QAccessibleItemRow::doAction(), QInputDialogPrivate::ensureListView(), QAbstractItemViewPrivate::extendedSelectionCommand(), focusInEvent(), QComboBox::hidePopup(), QSidebar::init(), QAccessibleTable2::isColumnSelected(), QAccessibleItemView::isColumnSelected(), QListWidget::isItemSelected(), QTableWidget::isItemSelected(), QAccessibleTable2::isRowSelected(), QAccessibleTree::isRowSelected(), QAccessibleItemView::isRowSelected(), QAccessibleItemView::isSelected(), QAccessibleTable2Cell::isSelected(), QTreeView::keyboardSearch(), QInputDialogPrivate::listViewText(), QCalendarView::mouseMoveEvent(), QCalendarView::mousePressEvent(), QAccessibleItemRow::navigate(), QTreeWidget::QTreeWidget(), QSidebar::removeEntry(), QColumnView::selectAll(), QTreeView::selectAll(), QAbstractItemViewPrivate::selectAll(), QListViewPrivate::selectAll(), QAccessibleTable2::selectColumn(), QAccessibleItemView::selectColumn(), QTableViewPrivate::selectColumn(), QAccessibleTable2::selectedCellCount(), QAccessibleTable2::selectedColumnCount(), QAccessibleItemView::selectedColumnCount(), QAccessibleItemView::selectedColumns(), QTreeView::selectedIndexes(), QListWidget::selectedItems(), QTableWidget::selectedItems(), QTreeWidget::selectedItems(), QTableWidget::selectedRanges(), QAccessibleTable2::selectedRowCount(), QAccessibleItemView::selectedRowCount(), QAccessibleItemView::selectedRows(), QAccessibleTable2::selectRow(), QAccessibleTree::selectRow(), QAccessibleItemView::selectRow(), QTableViewPrivate::selectRow(), QSidebar::selectUrl(), QCompleterPrivate::setCurrentIndex(), QListWidget::setCurrentRow(), QInputDialogPrivate::setInputWidget(), QListWidget::setItemSelected(), QTableWidget::setItemSelected(), QTreeWidget::setItemSelected(), QInputDialogPrivate::setListViewText(), QCompleter::setPopup(), QTableWidget::setRangeSelected(), QColumnView::setRootIndex(), QTreeView::setSelection(), QColumnView::setSelectionModel(), setSelectionModel(), QAbstractItemViewPrivate::shouldEdit(), QComboBox::showPopup(), QAccessibleItemRow::state(), QAccessibleTable2Cell::state(), QAccessibleTable2::unselectColumn(), QAccessibleItemView::unselectColumn(), QAccessibleTable2::unselectRow(), QAccessibleItemView::unselectRow(), and QCalendarWidgetPrivate::updateCurrentPage().
 {
     Q_D(const QAbstractItemView);
     return d->selectionModel;
 }
setAlternatingRowColors()
void QAbstractItemView::setAlternatingRowColors (bool enable)
Definition at line 1586 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     d->alternatingColors = enable;
     if (isVisible())
         d->viewport->update();
 }
setAutoScroll()
void QAbstractItemView::setAutoScroll (bool enable)
Definition at line 1382 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     d->autoScroll = enable;
 }
setAutoScrollMargin()
void QAbstractItemView::setAutoScrollMargin (int margin)
Definition at line 1405 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     d->autoScrollMargin = margin;
 }
setCurrentIndex
void QAbstractItemView::setCurrentIndex (const QModelIndex & index) slot
Sets the current item to be the item at index.
Unless the current selection mode is QAbstractItemView::NoSelection, the item is also be selected. Note that this function also updates the starting position for any new selections the user performs.
To set an item as the current item without selecting it, call
selectionModel()->setCurrentIndex(index, QItemSelectionModel::NoUpdate);
See also
currentIndex(), currentChanged(), selectionMode
Definition at line 1095 of file qabstractitemview.cpp.
Referenced by QColumnViewPrivate::_q_changeCurrentColumn(), QColumnViewPrivate::closeColumns(), QAccessibleItemRow::doAction(), QInputDialogPrivate::ensureListView(), QComboBoxPrivateContainer::eventFilter(), QSidebar::init(), keyboardSearch(), QComboBoxPrivate::keyboardSearchString(), QAccessibleItemRow::navigate(), rowsAboutToBeRemoved(), QTableWidget::setCurrentCell(), QFontListView::setCurrentItem(), QTableWidget::setCurrentItem(), QTreeWidget::setCurrentItem(), and QComboBoxPrivate::~QComboBoxPrivate().
 {
     Q_D(QAbstractItemView);
     if (d->selectionModel && (!index.isValid() || d->isIndexEnabled(index))) {
         QItemSelectionModel::SelectionFlags command = selectionCommand(index, 0);
         d->selectionModel->setCurrentIndex(index, command);
         d->currentIndexSet = true;
         if ((command & QItemSelectionModel::Current) == 0)
             d->pressedPosition = visualRect(currentIndex()).center() + d->offset();
     }
 }
setDefaultDropAction()
void QAbstractItemView::setDefaultDropAction (Qt::DropAction dropAction)
Definition at line 1559 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     d->defaultDropAction = dropAction;
 }
setDirtyRegion()
void QAbstractItemView::setDirtyRegion (const QRegion & region) protected
Marks the given region as dirty and schedules it to be updated.
Since
4.1
You only need to call this function if you are implementing your own view subclass.
See also
scrollDirtyRegion(), dirtyRegionOffset()
Definition at line 3844 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     d->setDirtyRegion(region);
 }
setDragDropMode()
void QAbstractItemView::setDragDropMode (DragDropMode behavior)
Definition at line 1515 of file qabstractitemview.cpp.
Referenced by QSidebar::init(), QFileDialogListView::init(), QFileDialogTreeView::init(), and QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     d->dragDropMode = behavior;
     setDragEnabled(behavior == DragOnly || behavior == DragDrop || behavior == InternalMove);
     setAcceptDrops(behavior == DropOnly || behavior == DragDrop || behavior == InternalMove);
 }
setDragDropOverwriteMode()
void QAbstractItemView::setDragDropOverwriteMode (bool overwrite)
Definition at line 1352 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     d->overwrite = overwrite;
 }
setDragEnabled()
void QAbstractItemView::setDragEnabled (bool enable)
Definition at line 1470 of file qabstractitemview.cpp.
Referenced by setDragDropMode(), QListView::setMovement(), and QListView::setViewMode().
 {
     Q_D(QAbstractItemView);
     d->dragEnabled = enable;
 }
setDropIndicatorShown()
void QAbstractItemView::setDropIndicatorShown (bool enable)
Definition at line 1448 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     d->showDropIndicator = enable;
 }
setEditTriggers()
void QAbstractItemView::setEditTriggers (EditTriggers triggers)
Definition at line 1261 of file qabstractitemview.cpp.
Referenced by QInputDialogPrivate::ensureListView(), QFileDialogListView::init(), QFileDialogTreeView::init(), QColumnView::initializeColumn(), QCompleter::popup(), QFontListView::QFontListView(), and QComboBoxPrivateContainer::setItemView().
 {
     Q_D(QAbstractItemView);
     d->editTriggers = actions;
 }
setHorizontalScrollMode()
void QAbstractItemView::setHorizontalScrollMode (ScrollMode mode)
Definition at line 1314 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     d->horizontalScrollMode = mode;
     updateGeometries(); // update the scroll bars
 }
setHorizontalStepsPerItem()
void QAbstractItemView::setHorizontalStepsPerItem (int steps) protected
Sets the horizontal scroll bar's steps per item to steps.
This is the number of steps used by the horizontal scroll bar to represent the width of an item.
Note that if the view has a horizontal header, the item steps will be ignored and the header section size will be used instead.
See also
horizontalStepsPerItem() setVerticalStepsPerItem()
Definition at line 2966 of file qabstractitemview.cpp.
 {
     Q_UNUSED(steps)
     // do nothing
 }
setIconSize()
void QAbstractItemView::setIconSize (const QSize & size)
Definition at line 1610 of file qabstractitemview.cpp.
Referenced by QSidebar::init(), QColumnView::initializeColumn(), and QComboBox::setIconSize().
 {
     Q_D(QAbstractItemView);
     if (size == d->iconSize)
         return;
     d->iconSize = size;
     d->doDelayedItemsLayout();
 }
setIndexWidget()
void QAbstractItemView::setIndexWidget (const QModelIndex & index, QWidget * widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
Since
4.1
If index is invalid (e.g., if you pass the root index), this function will do nothing.
The given widget's autoFillBackground property must be set to true, otherwise the widget's background will be transparent, showing both the model data and the item at the given index.
If index widget A is replaced with index widget B, index widget A will be deleted. For example, in the code snippet below, the QLineEdit object will be deleted.
setIndexWidget(index, new QLineEdit);
...
setIndexWidget(index, new QTextEdit);
This function should only be used to display static content within the visible area corresponding to an item of data. If you want to display custom dynamic content or implement a custom editor widget, subclass QItemDelegate instead.
See also
{Delegate Classes}
Definition at line 3246 of file qabstractitemview.cpp.
Referenced by QTableWidget::setCellWidget(), QListWidget::setItemWidget(), and QTreeWidget::setItemWidget().
 {
     Q_D(QAbstractItemView);
     if (!d->isIndexValid(index))
         return;
     if (QWidget *oldWidget = indexWidget(index)) {
         d->persistent.remove(oldWidget);
         d->removeEditor(oldWidget);
         oldWidget->deleteLater();
     }
     if (widget) {
         widget->setParent(viewport());
         d->persistent.insert(widget);
         d->addEditor(index, widget, true);
         widget->show();
         dataChanged(index, index); // update the geometry
         if (!d->delayedPendingLayout)
             widget->setGeometry(visualRect(index));
     }
 }
setItemDelegate()
void QAbstractItemView::setItemDelegate (QAbstractItemDelegate * delegate)
Sets the item delegate for this view and its model to delegate.
This is useful if you want complete control over the editing and display of items.
Any existing delegate will be removed, but not deleted. QAbstractItemView does not take ownership of delegate.
Warning
You should not share the same instance of a delegate between views. Doing so can cause incorrect or unintuitive editing behavior since each view connected to a given delegate may receive the QAbstractItemDelegate::closeEditor() signal, and attempt to access, modify or close an editor that has already been closed.
See also
itemDelegate()
Definition at line 844 of file qabstractitemview.cpp.
Referenced by QSidebar::init(), QColumnView::initializeColumn(), QComboBox::setItemDelegate(), and QCompleter::setPopup().
 {
     Q_D(QAbstractItemView);
     if (delegate == d->itemDelegate)
         return;
     if (d->itemDelegate) {
         if (d->delegateRefCount(d->itemDelegate) == 1) {
             disconnect(d->itemDelegate, SIGNAL(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)),
                        this, SLOT(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)));
             disconnect(d->itemDelegate, SIGNAL(commitData(QWidget*)), this, SLOT(commitData(QWidget*)));
             disconnect(d->itemDelegate, SIGNAL(sizeHintChanged(QModelIndex)), this, SLOT(doItemsLayout()));
         }
     }
     if (delegate) {
         if (d->delegateRefCount(delegate) == 0) {
             connect(delegate, SIGNAL(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)),
                     this, SLOT(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)));
             connect(delegate, SIGNAL(commitData(QWidget*)), this, SLOT(commitData(QWidget*)));
             qRegisterMetaType<QModelIndex>("QModelIndex");
             connect(delegate, SIGNAL(sizeHintChanged(QModelIndex)), this, SLOT(doItemsLayout()), Qt::QueuedConnection);
         }
     }
     d->itemDelegate = delegate;
     viewport()->update();
 }
setItemDelegateForColumn()
void QAbstractItemView::setItemDelegateForColumn (int column, QAbstractItemDelegate * delegate)
Sets the given item delegate used by this view and model for the given column.
Since
4.2
All items on column will be drawn and managed by delegate instead of using the default delegate (i.e., itemDelegate()).
Any existing column delegate for column will be removed, but not deleted. QAbstractItemView does not take ownership of delegate.
Note
If a delegate has been assigned to both a row and a column, the row delegate will take precedence and manage the intersecting cell index.
Warning
You should not share the same instance of a delegate between views. Doing so can cause incorrect or unintuitive editing behavior since each view connected to a given delegate may receive the QAbstractItemDelegate::closeEditor() signal, and attempt to access, modify or close an editor that has already been closed.
See also
itemDelegateForColumn(), setItemDelegateForRow(), itemDelegate()
Definition at line 981 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (QAbstractItemDelegate *columnDelegate = d->columnDelegates.value(column, 0)) {
         if (d->delegateRefCount(columnDelegate) == 1) {
             disconnect(columnDelegate, SIGNAL(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)),
                        this, SLOT(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)));
             disconnect(columnDelegate, SIGNAL(commitData(QWidget*)), this, SLOT(commitData(QWidget*)));
         }
         d->columnDelegates.remove(column);
     }
     if (delegate) {
         if (d->delegateRefCount(delegate) == 0) {
             connect(delegate, SIGNAL(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)),
                     this, SLOT(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)));
             connect(delegate, SIGNAL(commitData(QWidget*)), this, SLOT(commitData(QWidget*)));
         }
         d->columnDelegates.insert(column, delegate);
     }
     viewport()->update();
 }
setItemDelegateForRow()
void QAbstractItemView::setItemDelegateForRow (int row, QAbstractItemDelegate * delegate)
Sets the given item delegate used by this view and model for the given row.
Since
4.2
All items on row will be drawn and managed by delegate instead of using the default delegate (i.e., itemDelegate()).
Any existing row delegate for row will be removed, but not deleted. QAbstractItemView does not take ownership of delegate.
Note
If a delegate has been assigned to both a row and a column, the row delegate (i.e., this delegate) will take precedence and manage the intersecting cell index.
Warning
You should not share the same instance of a delegate between views. Doing so can cause incorrect or unintuitive editing behavior since each view connected to a given delegate may receive the QAbstractItemDelegate::closeEditor() signal, and attempt to access, modify or close an editor that has already been closed.
See also
itemDelegateForRow(), setItemDelegateForColumn(), itemDelegate()
Definition at line 918 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     if (QAbstractItemDelegate *rowDelegate = d->rowDelegates.value(row, 0)) {
         if (d->delegateRefCount(rowDelegate) == 1) {
             disconnect(rowDelegate, SIGNAL(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)),
                        this, SLOT(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)));
             disconnect(rowDelegate, SIGNAL(commitData(QWidget*)), this, SLOT(commitData(QWidget*)));
         }
         d->rowDelegates.remove(row);
     }
     if (delegate) {
         if (d->delegateRefCount(delegate) == 0) {
             connect(delegate, SIGNAL(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)),
                     this, SLOT(closeEditor(QWidget*,QAbstractItemDelegate::EndEditHint)));
             connect(delegate, SIGNAL(commitData(QWidget*)), this, SLOT(commitData(QWidget*)));
         }
         d->rowDelegates.insert(row, delegate);
     }
     viewport()->update();
 }
setModel()
void QAbstractItemView::setModel (QAbstractItemModel * model) virtual
Sets the model for the view to present.
This function will create and set a new selection model, replacing any model that was previously set with setSelectionModel(). However, the old selection model will not be deleted as it may be shared between several views. We recommend that you delete the old selection model if it is no longer required. This is done with the following code:
QItemSelectionModel *m = view->selectionModel();
view->setModel(new model);
delete m;
If both the old model and the old selection model do not have parents, or if their parents are long-lived objects, it may be preferable to call their deleteLater() functions to explicitly delete them.
The view does not take ownership of the model unless it is the model's parent object because the model may be shared between many different views.
See also
selectionModel(), setSelectionModel()
Reimplemented in QTreeWidget, QTableWidget, QListWidget, QHeaderView, QTreeView, QColumnView, and QTableView.
Definition at line 691 of file qabstractitemview.cpp.
Referenced by QListWidget::addItems(), QInputDialogPrivate::ensureListView(), QSidebar::init(), QColumnView::initializeColumn(), QFontListView::QFontListView(), QTableView::setModel(), QColumnView::setModel(), QTreeView::setModel(), QHeaderView::setModel(), QCompleter::setPopup(), and QComboBox::setView().
 {
     Q_D(QAbstractItemView);
     if (model == d->model)
         return;
     if (d->model && d->model != QAbstractItemModelPrivate::staticEmptyModel()) {
         disconnect(d->model, SIGNAL(destroyed()),
                    this, SLOT(_q_modelDestroyed()));
         disconnect(d->model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
                    this, SLOT(dataChanged(QModelIndex,QModelIndex)));
         disconnect(d->model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                    this, SLOT(_q_headerDataChanged()));
         disconnect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                    this, SLOT(rowsInserted(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                    this, SLOT(rowsAboutToBeRemoved(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                    this, SLOT(_q_rowsRemoved(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                    this, SLOT(_q_rowsInserted(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
                    this, SLOT(_q_columnsAboutToBeRemoved(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                    this, SLOT(_q_columnsRemoved(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                    this, SLOT(_q_columnsInserted(QModelIndex,int,int)));
         disconnect(d->model, SIGNAL(modelReset()), this, SLOT(reset()));
         disconnect(d->model, SIGNAL(layoutChanged()), this, SLOT(_q_layoutChanged()));
     }
     d->model = (model ? model : QAbstractItemModelPrivate::staticEmptyModel());
     // These asserts do basic sanity checking of the model
     Q_ASSERT_X(d->model->index(0,0) == d->model->index(0,0),
                "QAbstractItemView::setModel",
                "A model should return the exact same index "
                "(including its internal id/pointer) when asked for it twice in a row.");
     Q_ASSERT_X(!d->model->index(0,0).parent().isValid(),
                "QAbstractItemView::setModel",
                "The parent of a top level index should be invalid");
     if (d->model != QAbstractItemModelPrivate::staticEmptyModel()) {
         connect(d->model, SIGNAL(destroyed()),
                 this, SLOT(_q_modelDestroyed()));
         connect(d->model, SIGNAL(dataChanged(QModelIndex,QModelIndex)),
                 this, SLOT(dataChanged(QModelIndex,QModelIndex)));
         connect(d->model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                 this, SLOT(_q_headerDataChanged()));
         connect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                 this, SLOT(rowsInserted(QModelIndex,int,int)));
         connect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                 this, SLOT(_q_rowsInserted(QModelIndex,int,int)));
         connect(d->model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                 this, SLOT(rowsAboutToBeRemoved(QModelIndex,int,int)));
         connect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_rowsRemoved(QModelIndex,int,int)));
         connect(d->model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_columnsAboutToBeRemoved(QModelIndex,int,int)));
         connect(d->model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_columnsRemoved(QModelIndex,int,int)));
         connect(d->model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                 this, SLOT(_q_columnsInserted(QModelIndex,int,int)));
         connect(d->model, SIGNAL(modelReset()), this, SLOT(reset()));
         connect(d->model, SIGNAL(layoutChanged()), this, SLOT(_q_layoutChanged()));
     }
     QItemSelectionModel *selection_model = new QItemSelectionModel(d->model, this);
     connect(d->model, SIGNAL(destroyed()), selection_model, SLOT(deleteLater()));
     setSelectionModel(selection_model);
     reset(); // kill editors, set new root and do layout
 }
setRootIndex
void QAbstractItemView::setRootIndex (const QModelIndex & index) virtual slot
Sets the root item to the item at the given index.
See also
rootIndex()
Reimplemented in QListView, QTreeView, QColumnView, and QTableView.
Definition at line 1159 of file qabstractitemview.cpp.
Referenced by reset(), QTableView::setRootIndex(), QColumnView::setRootIndex(), QTreeView::setRootIndex(), QListView::setRootIndex(), and QComboBox::setRootModelIndex().
 {
     Q_D(QAbstractItemView);
     if (index.isValid() && index.model() != d->model) {
         qWarning("QAbstractItemView::setRootIndex failed : index must be from the currently set model");
         return;
     }
     d->root = index;
     d->doDelayedItemsLayout();
 }
setSelection()
void QAbstractItemView::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags flags) protected pure virtual
Applies the selection flags to the items in or touched by the rectangle, rect.
When implementing your own itemview setSelection should call selectionModel()->select(selection, flags) where selection is either an empty QModelIndex or a QItemSelection that contains all items that are contained in rect.
See also
selectionCommand(), selectedIndexes()
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by keyPressEvent(), mouseMoveEvent(), and mousePressEvent().
setSelectionBehavior()
void QAbstractItemView::setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
Definition at line 1069 of file qabstractitemview.cpp.
Referenced by QFileDialogListView::init(), QFileDialogTreeView::init(), QColumnView::initializeColumn(), and QCompleter::popup().
 {
     Q_D(QAbstractItemView);
     d->selectionBehavior = behavior;
 }
setSelectionMode()
void QAbstractItemView::setSelectionMode (QAbstractItemView::SelectionMode mode)
Definition at line 1044 of file qabstractitemview.cpp.
Referenced by QInputDialogPrivate::ensureListView(), QColumnView::initializeColumn(), QCompleter::popup(), QListView::QListView(), and QComboBoxPrivateContainer::setItemView().
 {
     Q_D(QAbstractItemView);
     d->selectionMode = mode;
 }
setSelectionModel()
void QAbstractItemView::setSelectionModel (QItemSelectionModel * selectionModel) virtual
Sets the current selection model to the given selectionModel.
Note that, if you call setModel() after this function, the given selectionModel will be replaced by one created by the view.
Note
It is up to the application to delete the old selection model if it is no longer needed; i.e., if it is not being used by other views. This will happen automatically when its parent object is deleted. However, if it does not have a parent, or if the parent is a long-lived object, it may be preferable to call its deleteLater() function to explicitly delete it.
See also
selectionModel(), setModel(), clearSelection()
Reimplemented in QTreeWidget, QTreeView, QColumnView, and QTableView.
Definition at line 788 of file qabstractitemview.cpp.
Referenced by QColumnViewPrivate::_q_changeCurrentColumn(), setModel(), QTableView::setSelectionModel(), QColumnView::setSelectionModel(), and QTreeView::setSelectionModel().
 {
     // ### if the given model is null, we should use the original selection model
     Q_ASSERT(selectionModel);
     Q_D(QAbstractItemView);
     if (selectionModel->model() != d->model) {
         qWarning("QAbstractItemView::setSelectionModel() failed: "
                  "Trying to set a selection model, which works on "
                  "a different model than the view.");
         return;
     }
     if (d->selectionModel) {
         disconnect(d->selectionModel, SIGNAL(selectionChanged(QItemSelection,QItemSelection)),
                    this, SLOT(selectionChanged(QItemSelection,QItemSelection)));
         disconnect(d->selectionModel, SIGNAL(currentChanged(QModelIndex,QModelIndex)),
                    this, SLOT(currentChanged(QModelIndex,QModelIndex)));
     }
     d->selectionModel = selectionModel;
     if (d->selectionModel) {
         connect(d->selectionModel, SIGNAL(selectionChanged(QItemSelection,QItemSelection)),
                 this, SLOT(selectionChanged(QItemSelection,QItemSelection)));
         connect(d->selectionModel, SIGNAL(currentChanged(QModelIndex,QModelIndex)),
                 this, SLOT(currentChanged(QModelIndex,QModelIndex)));
     }
 }
setState()
void QAbstractItemView::setState (State state) protected
Sets the item view's state to the given state.
See also
state()
Definition at line 3798 of file qabstractitemview.cpp.
Referenced by closeEditor(), QListView::doItemsLayout(), dragEnterEvent(), dragLeaveEvent(), dropEvent(), editorDestroyed(), mouseMoveEvent(), QTreeView::mouseReleaseEvent(), mouseReleaseEvent(), reset(), and rowsAboutToBeRemoved().
 {
     Q_D(QAbstractItemView);
     d->state = state;
 }
setTabKeyNavigation()
void QAbstractItemView::setTabKeyNavigation (bool enable)
Definition at line 1425 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn(), and QCalendarView::QCalendarView().
 {
     Q_D(QAbstractItemView);
     d->tabKeyNavigation = enable;
 }
setTextElideMode()
void QAbstractItemView::setTextElideMode (Qt::TextElideMode mode)
Definition at line 1635 of file qabstractitemview.cpp.
Referenced by QFileDialogTreeView::init(), and QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     d->textElideMode = mode;
 }
setVerticalScrollMode()
void QAbstractItemView::setVerticalScrollMode (ScrollMode mode)
Definition at line 1285 of file qabstractitemview.cpp.
Referenced by QColumnView::initializeColumn().
 {
     Q_D(QAbstractItemView);
     if (mode == d->verticalScrollMode)
         return;
     QModelIndex topLeft = indexAt(QPoint(0, 0));
     d->verticalScrollMode = mode;
     updateGeometries(); // update the scroll bars
     scrollTo(topLeft, QAbstractItemView::PositionAtTop);
 }
setVerticalStepsPerItem()
void QAbstractItemView::setVerticalStepsPerItem (int steps) protected
Sets the vertical scroll bar's steps per item to steps.
This is the number of steps used by the vertical scroll bar to represent the height of an item.
Note that if the view has a vertical header, the item steps will be ignored and the header section size will be used instead.
See also
verticalStepsPerItem() setHorizontalStepsPerItem()
Definition at line 3001 of file qabstractitemview.cpp.
 {
     Q_UNUSED(steps)
     // do nothing
 }
showDropIndicator()
bool QAbstractItemView::showDropIndicator () const
Referenced by QColumnView::initializeColumn(), and setDropIndicatorShown().
sizeHintForColumn()
int QAbstractItemView::sizeHintForColumn (int column) const virtual
Returns the width size hint for the specified column or -1 if there is no model.
This function is used in views with a horizontal header to find the size hint for a header section based on the contents of the given column.
See also
sizeHintForRow()
Reimplemented in QTreeView, and QTableView.
Definition at line 3157 of file qabstractitemview.cpp.
 {
     Q_D(const QAbstractItemView);
     if (column < 0 || column >= d->model->columnCount(d->root))
         return -1;
     ensurePolished();
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     int width = 0;
     int rows = d->model->rowCount(d->root);
     QModelIndex index;
     for (int r = 0; r < rows; ++r) {
         index = d->model->index(r, column, d->root);
         if (QWidget *editor = d->editorForIndex(index).widget.data())
             width = qMax(width, editor->sizeHint().width());
         int hint = d->delegateForIndex(index)->sizeHint(option, index).width();
         width = qMax(width, hint);
     }
     return width;
 }
sizeHintForIndex()
QSize QAbstractItemView::sizeHintForIndex (const QModelIndex & index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
See also
sizeHintForRow(), sizeHintForColumn()
Definition at line 3102 of file qabstractitemview.cpp.
Referenced by QSidebar::sizeHint().
 {
     Q_D(const QAbstractItemView);
     if (!d->isIndexValid(index) || !d->itemDelegate)
         return QSize();
     return d->delegateForIndex(index)->sizeHint(d->viewOptionsV4(), index);
 }
sizeHintForRow()
int QAbstractItemView::sizeHintForRow (int row) const virtual
Returns the height size hint for the specified row or -1 if there is no model.
The returned height is calculated using the size hints of the given row's items, i.e. the returned value is the maximum height among the items. Note that to control the height of a row, you must reimplement the QAbstractItemDelegate::sizeHint() function.
This function is used in views with a vertical header to find the size hint for a header section based on the contents of the given row.
See also
sizeHintForColumn()
Reimplemented in QTableView.
Definition at line 3126 of file qabstractitemview.cpp.
Referenced by QTreeView::scrollContentsBy(), QCompleterPrivate::showPopup(), QFileDialogListView::sizeHint(), and QFileDialogTreeView::sizeHint().
 {
     Q_D(const QAbstractItemView);
     if (row < 0 || row >= d->model->rowCount(d->root))
         return -1;
     ensurePolished();
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     int height = 0;
     int colCount = d->model->columnCount(d->root);
     QModelIndex index;
     for (int c = 0; c < colCount; ++c) {
         index = d->model->index(row, c, d->root);
         if (QWidget *editor = d->editorForIndex(index).widget.data())
             height = qMax(height, editor->height());
         int hint = d->delegateForIndex(index)->sizeHint(option, index).height();
         height = qMax(height, hint);
     }
     return height;
 }
startAutoScroll()
void QAbstractItemView::startAutoScroll () protected
Warning
This function is not part of the public interface.
Definition at line 3884 of file qabstractitemview.cpp.
Referenced by dragMoveEvent().
 {
     d_func()->startAutoScroll();
 }
startDrag()
void QAbstractItemView::startDrag (Qt::DropActions supportedActions) protected virtual
Starts a drag by calling drag->exec() using the given supportedActions.
Reimplemented in QListView.
Definition at line 3709 of file qabstractitemview.cpp.
Referenced by mouseMoveEvent(), and QListView::startDrag().
 {
     Q_D(QAbstractItemView);
     QModelIndexList indexes = d->selectedDraggableIndexes();
     if (indexes.count() > 0) {
         QMimeData *data = d->model->mimeData(indexes);
         if (!data)
             return;
         QRect rect;
         QPixmap pixmap = d->renderToPixmap(indexes, &rect);
         rect.adjust(horizontalOffset(), verticalOffset(), 0, 0);
         QDrag *drag = new QDrag(this);
         drag->setPixmap(pixmap);
         drag->setMimeData(data);
         drag->setHotSpot(d->pressedPosition - rect.topLeft());
         Qt::DropAction defaultDropAction = Qt::IgnoreAction;
         if (d->defaultDropAction != Qt::IgnoreAction && (supportedActions & d->defaultDropAction))
             defaultDropAction = d->defaultDropAction;
         else if (supportedActions & Qt::CopyAction && dragDropMode() != QAbstractItemView::InternalMove)
             defaultDropAction = Qt::CopyAction;
         if (drag->exec(supportedActions, defaultDropAction) == Qt::MoveAction)
             d->clearOrRemove();
     }
 }
state()
QAbstractItemView::State QAbstractItemView::state () const protected
Returns the item view's state.
See also
setState()
Definition at line 3787 of file qabstractitemview.cpp.
Referenced by QHeaderViewPrivate::clear(), QTreeViewPrivate::collapse(), QListView::doItemsLayout(), QTreeView::drawRow(), QTreeView::drawTree(), editorDestroyed(), QTreeViewPrivate::expand(), QTreeViewPrivate::expandOrCollapseItemAtPos(), QAbstractItemViewPrivate::extendedSelectionCommand(), keyPressEvent(), QTreeView::mouseDoubleClickEvent(), QListView::mouseMoveEvent(), mouseMoveEvent(), QTreeView::mouseReleaseEvent(), mouseReleaseEvent(), QListView::paintEvent(), QHeaderView::paintSection(), QListView::resizeEvent(), QHeaderView::restoreState(), QTreeView::scrollTo(), QListView::setSelection(), setState(), QAbstractItemViewPrivate::shouldEdit(), QTreeView::timerEvent(), and QComboBoxPrivate::~QComboBoxPrivate().
 {
     Q_D(const QAbstractItemView);
     return d->state;
 }
stopAutoScroll()
void QAbstractItemView::stopAutoScroll () protected
Warning
This function is not part of the public interface.
Definition at line 3892 of file qabstractitemview.cpp.
Referenced by doAutoScroll(), dragLeaveEvent(), dropEvent(), and mouseMoveEvent().
 {
     d_func()->stopAutoScroll();
 }
tabKeyNavigation()
bool QAbstractItemView::tabKeyNavigation () const
Referenced by QColumnView::initializeColumn(), and setTabKeyNavigation().
textElideMode()
Qt::TextElideMode QAbstractItemView::textElideMode () const
Referenced by QColumnView::initializeColumn(), and setTextElideMode().
timerEvent()
void QAbstractItemView::timerEvent (QTimerEvent * event) protected virtual
This function is called with the given event when a timer event is sent to the widget.
See also
QObject::timerEvent()
Reimplemented from QObject.
Reimplemented in QTreeView, QListView, and QTableView.
Definition at line 2553 of file qabstractitemview.cpp.
Referenced by QTableView::timerEvent(), QListView::timerEvent(), and QTreeView::timerEvent().
 {
     Q_D(QAbstractItemView);
     if (event->timerId() == d->fetchMoreTimer.timerId())
         d->fetchMore();
     else if (event->timerId() == d->delayedReset.timerId())
         reset();
     else if (event->timerId() == d->autoScrollTimer.timerId())
         doAutoScroll();
     else if (event->timerId() == d->updateTimer.timerId())
         d->updateDirtyRegion();
     else if (event->timerId() == d->delayedEditing.timerId()) {
         d->delayedEditing.stop();
         edit(currentIndex());
     } else if (event->timerId() == d->delayedLayout.timerId()) {
         d->delayedLayout.stop();
         if (isVisible()) {
             d->interruptDelayedItemsLayout();
             doItemsLayout();
             const QModelIndex current = currentIndex();
             if (current.isValid() && d->state == QAbstractItemView::EditingState)
                 scrollTo(current);
         }
     } else if (event->timerId() == d->delayedAutoScroll.timerId()) {
         d->delayedAutoScroll.stop();
         //end of the timer: if the current item is still the same as the one when the mouse press occurred
         //we only get here if there was no double click
         if (d->pressedIndex.isValid() && d->pressedIndex == currentIndex())
             scrollTo(d->pressedIndex);
     }
 }
update
void QAbstractItemView::update (const QModelIndex & index) slot
Updates the area occupied by the given index.
Warning
This function is not part of the public interface.
Since
4.3
Definition at line 3329 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (index.isValid()) {
         const QRect rect = visualRect(index);
         //this test is important for peformance reason
         //For example in dataChanged we simply update all the cells without checking
         //it can be a major bottleneck to update rects that aren't even part of the viewport
         if (d->viewport->rect().intersects(rect))
             d->viewport->update(rect);
     }
 }
updateEditorData
void QAbstractItemView::updateEditorData () protected virtual slot
Updates the data shown in the open editor widgets in the view.
Warning
This function is not part of the public interface.
Definition at line 2731 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     d->updateEditorData(QModelIndex(), QModelIndex());
 }
updateEditorGeometries
void QAbstractItemView::updateEditorGeometries () protected virtual slot
Updates the geometry of the open editor widgets in the view.
Warning
This function is not part of the public interface.
Definition at line 2744 of file qabstractitemview.cpp.
Referenced by QTreeView::columnMoved(), rowsInserted(), and updateGeometries().
 {
     Q_D(QAbstractItemView);
     if(d->editorIndexHash.isEmpty())
         return;
     QStyleOptionViewItemV4 option = d->viewOptionsV4();
     QEditorIndexHash::iterator it = d->editorIndexHash.begin();
     QWidgetList editorsToRelease;
     QWidgetList editorsToHide;
     while (it != d->editorIndexHash.end()) {
         QModelIndex index = it.value();
         QWidget *editor = it.key();
         if (index.isValid() && editor) {
             option.rect = visualRect(index);
             if (option.rect.isValid()) {
                 editor->show();
                 QAbstractItemDelegate *delegate = d->delegateForIndex(index);
                 if (delegate)
                     delegate->updateEditorGeometry(editor, option, index);
             } else {
                 editorsToHide << editor;
             }
             ++it;
         } else {
             d->indexEditorHash.remove(it.value());
             it = d->editorIndexHash.erase(it);
             editorsToRelease << editor;
         }
     }
     //we hide and release the editor outside of the loop because it might change the focus and try
     //to change the editors hashes.
     for (int i = 0; i < editorsToHide.count(); ++i) {
         editorsToHide.at(i)->hide();
     }
     for (int i = 0; i < editorsToRelease.count(); ++i) {
         d->releaseEditor(editorsToRelease.at(i));
     }
 }
updateGeometries
void QAbstractItemView::updateGeometries () protected virtual slot
Updates the geometry of the child widgets of the view.
Since
4.4
Reimplemented in QHeaderView, QTreeView, QListView, and QTableView.
Definition at line 2792 of file qabstractitemview.cpp.
Referenced by doItemsLayout(), event(), resizeEvent(), scrollToBottom(), setHorizontalScrollMode(), setVerticalScrollMode(), QTableView::updateGeometries(), QListView::updateGeometries(), and QTreeView::updateGeometries().
 {
     updateEditorGeometries();
     d_func()->fetchMoreTimer.start(0, this); //fetch more later
 }
verticalOffset()
int QAbstractItemView::verticalOffset () const protected pure virtual
Returns the vertical offset of the view.
In the base class this is a pure virtual function.
See also
horizontalOffset()
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by startDrag().
verticalScrollbarAction
void QAbstractItemView::verticalScrollbarAction (int action) protected virtual slot
Warning
This function is not part of the public interface.
Reimplemented in QTableView.
Definition at line 2827 of file qabstractitemview.cpp.
Referenced by QTableView::verticalScrollbarAction().
 {
     //do nothing
 }
verticalScrollbarValueChanged
void QAbstractItemView::verticalScrollbarValueChanged (int value) protected virtual slot
Warning
This function is not part of the public interface.
Definition at line 2801 of file qabstractitemview.cpp.
 {
     Q_D(QAbstractItemView);
     if (verticalScrollBar()->maximum() == value && d->model->canFetchMore(d->root))
         d->model->fetchMore(d->root);
     QPoint posInVp = viewport()->mapFromGlobal(QCursor::pos());
     if (viewport()->rect().contains(posInVp))
         d->checkMouseMove(posInVp);
 }
verticalScrollMode()
ScrollMode QAbstractItemView::verticalScrollMode () const
Referenced by QTreeViewPrivate::coordinateForItem(), QTableView::doItemsLayout(), QTreeView::drawBranches(), QTreeViewPrivate::firstVisibleItem(), QColumnView::initializeColumn(), QTreeViewPrivate::itemAtCoordinate(), QTableView::paintEvent(), QTableView::scrollContentsBy(), QTreeView::scrollContentsBy(), QTableView::scrollTo(), QTreeView::scrollTo(), setVerticalScrollMode(), QTableView::updateGeometries(), and QTreeViewPrivate::updateScrollBars().
verticalStepsPerItem()
int QAbstractItemView::verticalStepsPerItem () const protected
Returns the vertical scroll bar's steps per item.
See also
setVerticalStepsPerItem() horizontalStepsPerItem()
Definition at line 3016 of file qabstractitemview.cpp.
 {
     return 1;
 }
viewOptions()
QStyleOptionViewItem QAbstractItemView::viewOptions () const protected virtual
Returns a QStyleOptionViewItem structure populated with the view's palette, font, state, alignments etc.
Reimplemented in QListView, QTableView, and QComboBoxListView.
Definition at line 3739 of file qabstractitemview.cpp.
Referenced by QTreeView::drawBranches(), QTableView::viewOptions(), and QListView::viewOptions().
 {
     Q_D(const QAbstractItemView);
     QStyleOptionViewItem option;
     option.init(this);
     option.state &= ~QStyle::State_MouseOver;
     option.font = font();
 #ifndef Q_WS_MAC
     // On mac the focus appearance follows window activation
     // not widget activation
     if (!hasFocus())
         option.state &= ~QStyle::State_Active;
 #endif
     option.state &= ~QStyle::State_HasFocus;
     if (d->iconSize.isValid()) {
         option.decorationSize = d->iconSize;
     } else {
         int pm = style()->pixelMetric(QStyle::PM_SmallIconSize, 0, this);
         option.decorationSize = QSize(pm, pm);
     }
     option.decorationPosition = QStyleOptionViewItem::Left;
     option.decorationAlignment = Qt::AlignCenter;
     option.displayAlignment = Qt::AlignLeft|Qt::AlignVCenter;
     option.textElideMode = d->textElideMode;
     option.rect = QRect();
     option.showDecorationSelected = style()->styleHint(QStyle::SH_ItemView_ShowDecorationSelected, 0, this);
     return option;
 }
viewportEntered
void QAbstractItemView::viewportEntered () signal
This signal is emitted when the mouse cursor enters the viewport.
Mouse tracking needs to be enabled for this feature to work.
See also
entered()
viewportEvent()
bool QAbstractItemView::viewportEvent (QEvent * event) protected virtual
This function is used to handle tool tips, and What's This? mode, if the given event is a QEvent::ToolTip,or a QEvent::WhatsThis.
It passes all other events on to its base class viewportEvent() handler.
Reimplemented from QAbstractScrollArea.
Reimplemented in QTreeView, and QHeaderView.
Definition at line 1717 of file qabstractitemview.cpp.
Referenced by QHeaderView::viewportEvent(), and QTreeView::viewportEvent().
 {
     Q_D(QAbstractItemView);
     switch (event->type()) {
     case QEvent::HoverMove:
     case QEvent::HoverEnter:
         d->setHoverIndex(indexAt(static_cast<QHoverEvent*>(event)->pos()));
         break;
     case QEvent::HoverLeave:
         d->setHoverIndex(QModelIndex());
         break;
     case QEvent::Enter:
         d->viewportEnteredNeeded = true;
         break;
     case QEvent::Leave:
     #ifndef QT_NO_STATUSTIP
         if (d->shouldClearStatusTip && d->parent) {
             QString empty;
             QStatusTipEvent tip(empty);
             QApplication::sendEvent(d->parent, &tip);
             d->shouldClearStatusTip = false;
         }
     #endif
         d->enteredIndex = QModelIndex();
         break;
     case QEvent::ToolTip:
     case QEvent::QueryWhatsThis:
     case QEvent::WhatsThis: {
         QHelpEvent *he = static_cast<QHelpEvent*>(event);
         const QModelIndex index = indexAt(he->pos());
         QStyleOptionViewItemV4 option = d->viewOptionsV4();
         option.rect = visualRect(index);
         option.state |= (index == currentIndex() ? QStyle::State_HasFocus : QStyle::State_None);
         bool retval = false;
         // ### Qt 5: make this a normal function call to a virtual function
         QMetaObject::invokeMethod(d->delegateForIndex(index), "helpEvent",
                                   Q_RETURN_ARG(bool, retval),
                                   Q_ARG(QHelpEvent *, he),
                                   Q_ARG(QAbstractItemView *, this),
                                   Q_ARG(QStyleOptionViewItem, option),
                                   Q_ARG(QModelIndex, index));
         return retval;
     }
     case QEvent::FontChange:
         d->doDelayedItemsLayout(); // the size of the items will change
         break;
     case QEvent::WindowActivate:
     case QEvent::WindowDeactivate:
         d->viewport->update();
         break;
     default:
         break;
     }
     return QAbstractScrollArea::viewportEvent(event);
 }
visualRect()
QRect QAbstractItemView::visualRect (const QModelIndex & index) const pure virtual
Returns the rectangle on the viewport occupied by the item at index.
If your item is displayed in several areas then visualRect should return the primary area that contains index and not the complete area that index might encompasses, touch or cause drawing.
In the base class this is a pure virtual function.
See also
indexAt(), visualRegionForSelection()
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by dragMoveEvent(), inputMethodQuery(), keyPressEvent(), mousePressEvent(), openPersistentEditor(), QAccessibleItemRow::rect(), QAccessibleTable2Cell::rect(), setCurrentIndex(), setIndexWidget(), QComboBox::showPopup(), update(), updateEditorGeometries(), and viewportEvent().
visualRegionForSelection()
QRegion QAbstractItemView::visualRegionForSelection (const QItemSelection & selection) const protected pure virtual
Returns the region from the viewport of the items in the given selection.
In the base class this is a pure virtual function.
See also
visualRect(), selectedIndexes()
Implemented in QHeaderView, QTreeView, QListView, QTableView, QColumnViewPreviewColumn, and QColumnView.
Referenced by selectionChanged().
Friends and Related Functions
QAccessibleItemRow
friend class QAccessibleItemRow friend
Definition at line 365 of file qabstractitemview.h.
QListModeViewBase
friend class QListModeViewBase friend
Definition at line 366 of file qabstractitemview.h.
Referenced by QListView::setViewMode().
QListViewPrivate
friend class QListViewPrivate friend
Definition at line 367 of file qabstractitemview.h.
QTreeViewPrivate
friend class QTreeViewPrivate friend
Definition at line 364 of file qabstractitemview.h.
Properties
alternatingRowColors
bool QAbstractItemView::alternatingRowColors private
whether to draw the background using alternating colors
If this property is true, the item background will be drawn using QPalette::Base and QPalette::AlternateBase; otherwise the background will be drawn using the QPalette::Base color.
By default, this property is false.
Definition at line 79 of file qabstractitemview.h.
autoScroll
QAbstractItemView::autoScroll private
whether autoscrolling in drag move events is enabled
If this property is set to true (the default), the QAbstractItemView automatically scrolls the contents of the view if the user drags within 16 pixels of the viewport edge. If the current item changes, then the view will scroll automatically to ensure that the current item is fully visible.
This property only works if the viewport accepts drops. Autoscroll is switched off by setting this property to false.
Definition at line 68 of file qabstractitemview.h.
Referenced by focusInEvent(), mousePressEvent(), and QAbstractItemViewPrivate::shouldAutoScroll().
autoScrollMargin
int QAbstractItemView::autoScrollMargin private
the size of the area when auto scrolling is triggered
Since
4.4
This property controls the size of the area at the edge of the viewport that triggers autoscrolling. The default value is 16 pixels.
Definition at line 69 of file qabstractitemview.h.
defaultDropAction
Qt::DropAction QAbstractItemView::defaultDropAction private
the drop action that will be used by default in QAbstractItemView::drag()
If the property is not set, the drop action is CopyAction when the supported actions support CopyAction.
Since
4.6
See also
showDropIndicator dragDropOverwriteMode
Definition at line 77 of file qabstractitemview.h.
dragDropMode
QAbstractItemView::DragDropMode QAbstractItemView::dragDropMode private
the drag and drop event the view will act upon
Since
4.2
See also
showDropIndicator dragDropOverwriteMode
Definition at line 76 of file qabstractitemview.h.
dragDropOverwriteMode
bool QAbstractItemView::dragDropOverwriteMode private
the view's drag and drop behavior
Since
4.2
If its value is true, the selected data will overwrite the existing item data when dropped, while moving the data will clear the item. If its value is false, the selected data will be inserted as a new item when the data is dropped. When the data is moved, the item is removed as well.
The default value is false, as in the QListView and QTreeView subclasses. In the QTableView subclass, on the other hand, the property has been set to true.
Note: This is not intended to prevent overwriting of items. The model's implementation of flags() should do that by not returning Qt::ItemIsDropEnabled.
See also
dragDropMode
Definition at line 75 of file qabstractitemview.h.
dragEnabled
bool QAbstractItemView::dragEnabled private
whether the view supports dragging of its own items
See also
showDropIndicator DragDropMode dragDropOverwriteMode acceptDrops
Definition at line 74 of file qabstractitemview.h.
editTriggers
QAbstractItemView::EditTriggers QAbstractItemView::editTriggers private
which actions will initiate item editing
This property is a selection of flags defined by EditTrigger, combined using the OR operator. The view will only initiate the editing of an item if the action performed is set in this property.
Definition at line 70 of file qabstractitemview.h.
horizontalScrollMode
QAbstractItemView::ScrollMode QAbstractItemView::horizontalScrollMode private
how the view scrolls its contents in the horizontal direction
Since
4.2
This property controls how the view scroll its contents horizontally. Scrolling can be done either per pixel or per item.
Definition at line 85 of file qabstractitemview.h.
iconSize
QSize QAbstractItemView::iconSize private
the size of items' icons
Setting this property when the view is visible will cause the items to be laid out again.
Definition at line 82 of file qabstractitemview.h.
selectionBehavior
QAbstractItemView::SelectionBehavior QAbstractItemView::selectionBehavior private
which selection behavior the view uses
This property holds whether selections are done in terms of single items, rows or columns.
See also
SelectionMode SelectionBehavior
Definition at line 81 of file qabstractitemview.h.
Referenced by QWindowsVistaStyle::drawPrimitive().
selectionMode
QAbstractItemView::SelectionMode QAbstractItemView::selectionMode private
which selection mode the view operates in
This property controls whether the user can select one or many items and, in many-item selections, whether the selection must be a continuous range of items.
See also
SelectionMode SelectionBehavior
Definition at line 80 of file qabstractitemview.h.
Referenced by QWindowsVistaStyle::drawControl(), QWindowsVistaStyle::drawPrimitive(), QAccessibleTable2::selectColumn(), QAccessibleTable2::selectRow(), QAccessibleTree::selectRow(), QAccessibleItemRow::state(), QAccessibleItemView::state(), QAccessibleTable2Cell::state(), QAccessibleTable2::unselectColumn(), and QAccessibleTable2::unselectRow().
showDropIndicator
bool QAbstractItemView::showDropIndicator private
whether the drop indicator is shown when dragging items and dropping.
See also
dragEnabled DragDropMode dragDropOverwriteMode acceptDrops
Definition at line 73 of file qabstractitemview.h.
tabKeyNavigation
bool QAbstractItemView::tabKeyNavigation private
whether item navigation with tab and backtab is enabled.
Definition at line 71 of file qabstractitemview.h.
textElideMode
Qt::TextElideMode QAbstractItemView::textElideMode private
the position of the "..." in elided text.
The default value for all item views is Qt::ElideRight.
Definition at line 83 of file qabstractitemview.h.
verticalScrollMode
QAbstractItemView::ScrollMode QAbstractItemView::verticalScrollMode private
how the view scrolls its contents in the vertical direction
Since
4.2
This property controls how the view scroll its contents vertically. Scrolling can be done either per pixel or per item.
Definition at line 84 of file qabstractitemview.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qabstractitemview.h
/src/gui/itemviews/qabstractitemview.cpp