Qt 4.8: QSGGeometry Class Reference
QSGGeometry Class Reference
#include <qsggeometry.h>
Classes
struct Attribute
struct AttributeSet
struct ColoredPoint2D
struct Point2D
struct TexturedPoint2D
Public Functions
void allocate (int vertexCount, int indexCount=0)
int attributeCount () const
const Attribute * attributes () const
GLenum drawingMode () const
int indexCount () const
void * indexData ()
const void * indexData () const
uint * indexDataAsUInt ()
const uint * indexDataAsUInt () const
quint16 * indexDataAsUShort ()
const quint16 * indexDataAsUShort () const
int indexType () const
QSGGeometry (const QSGGeometry::AttributeSet &attribs, int vertexCount, int indexCount=0, int indexType=GL_UNSIGNED_SHORT)
void setDrawingMode (GLenum mode)
int stride () const
int vertexCount () const
void * vertexData ()
const void * vertexData () const
ColoredPoint2D * vertexDataAsColoredPoint2D ()
const ColoredPoint2D * vertexDataAsColoredPoint2D () const
Point2D * vertexDataAsPoint2D ()
const Point2D * vertexDataAsPoint2D () const
TexturedPoint2D * vertexDataAsTexturedPoint2D ()
const TexturedPoint2D * vertexDataAsTexturedPoint2D () const
~QSGGeometry ()
Static Public Functions
static const AttributeSet & defaultAttributes_ColoredPoint2D ()
static const AttributeSet & defaultAttributes_Point2D ()
static const AttributeSet & defaultAttributes_TexturedPoint2D ()
static void updateRectGeometry (QSGGeometry *g, const QRectF &rect)
static void updateTexturedRectGeometry (QSGGeometry *g, const QRectF &rect, const QRectF &sourceRect)
Properties
const AttributeSet & m_attributes
void * m_data
int m_drawing_mode
int m_index_count
int m_index_data_offset
int m_index_type
uint m_owns_data: 1
float m_prealloc [16]
uint m_reserved_bits: 31
void * m_reserved_pointer
int m_vertex_count
Detailed Description
Definition at line 51 of file qsggeometry.h.
Constructors and Destructors
QSGGeometry()
QSGGeometry::QSGGeometry (const QSGGeometry::AttributeSet & attribs, int vertexCount, int indexCount = 0, int indexType = GL_UNSIGNED_SHORT)
Definition at line 80 of file qsggeometry.cpp.
     : m_drawing_mode(GL_TRIANGLE_STRIP)
     , m_vertex_count(0)
     , m_index_count(0)
     , m_index_type(indexType)
     , m_attributes(attributes)
     , m_data(0)
     , m_index_data_offset(-1)
     , m_owns_data(false)
 {
     Q_ASSERT(m_attributes.count > 0);
     Q_ASSERT(m_attributes.stride > 0);
     // Because allocate reads m_vertex_count, m_index_count and m_owns_data, these
     // need to be set before calling allocate...
     allocate(vertexCount, indexCount);
 }
~QSGGeometry()
QSGGeometry::~QSGGeometry ()
Definition at line 101 of file qsggeometry.cpp.
 {
     if (m_owns_data)
         qFree(m_data);
 }
Functions
allocate()
void QSGGeometry::allocate (int vertexCount, int indexCount = 0)
Definition at line 126 of file qsggeometry.cpp.
Referenced by drawingMode(), QSGGeometry(), and ShaderEffectItem::updateGeometry().
 {
     if (vertexCount == m_vertex_count && indexCount == m_index_count)
         return;
     m_vertex_count = vertexCount;
     m_index_count = indexCount;
     bool canUsePrealloc = m_index_count <= 0;
     int vertexByteSize = m_attributes.stride * m_vertex_count;
     if (m_owns_data)
         qFree(m_data);
     if (canUsePrealloc && vertexByteSize <= (int) sizeof(m_prealloc)) {
         m_data = (void *) &m_prealloc[0];
         m_index_data_offset = -1;
         m_owns_data = false;
     } else {
         Q_ASSERT(m_index_type == GL_UNSIGNED_INT || m_index_type == GL_UNSIGNED_SHORT);
         int indexByteSize = indexCount * (m_index_type == GL_UNSIGNED_SHORT ? sizeof(quint16) : sizeof(quint32));
         m_data = (void *) qMalloc(vertexByteSize + indexByteSize);
         m_index_data_offset = vertexByteSize;
         m_owns_data = true;
     }
 }
attributeCount()
int QSGGeometry::attributeCount () const inline
Definition at line 110 of file qsggeometry.h.
Referenced by ShaderEffectItem::bindGeometry().
 { return m_attributes.count; }
attributes()
const Attribute* QSGGeometry::attributes () const inline
Definition at line 111 of file qsggeometry.h.
Referenced by ShaderEffectItem::bindGeometry(), ShaderEffectItem::renderEffect(), and ShaderEffectItem::updateShaderProgram().
 { return m_attributes.attributes; }
defaultAttributes_ColoredPoint2D()
const QSGGeometry::AttributeSet & QSGGeometry::defaultAttributes_ColoredPoint2D () static
Definition at line 68 of file qsggeometry.cpp.
 {
     static Attribute data[] = {
         { 0, 2, GL_FLOAT },
         { 1, 4, GL_UNSIGNED_BYTE }
     };
     static AttributeSet attrs = { 2, 2 * sizeof(float) + 4 * sizeof(char), data };
     return attrs;
 }
defaultAttributes_Point2D()
const QSGGeometry::AttributeSet & QSGGeometry::defaultAttributes_Point2D () static
Definition at line 47 of file qsggeometry.cpp.
 {
     static Attribute data[] = {
         { 0, 2, GL_FLOAT }
     };
     static AttributeSet attrs = { 1, sizeof(float) * 2, data };
     return attrs;
 }
defaultAttributes_TexturedPoint2D()
const QSGGeometry::AttributeSet & QSGGeometry::defaultAttributes_TexturedPoint2D () static
Definition at line 57 of file qsggeometry.cpp.
 {
     static Attribute data[] = {
         { 0, 2, GL_FLOAT },
         { 1, 2, GL_FLOAT }
     };
     static AttributeSet attrs = { 2, sizeof(float) * 4, data };
     return attrs;
 }
drawingMode()
GLenum QSGGeometry::drawingMode () const inline
Definition at line 82 of file qsggeometry.h.
Referenced by ShaderEffectItem::renderEffect().
 { return m_drawing_mode; }
indexCount()
int QSGGeometry::indexCount () const inline
Definition at line 100 of file qsggeometry.h.
Referenced by allocate(), drawingMode(), and ShaderEffectItem::renderEffect().
 { return m_index_count; }
indexData() [1/2]
void * QSGGeometry::indexData ()
Definition at line 107 of file qsggeometry.cpp.
Referenced by indexCount(), indexDataAsUInt(), indexDataAsUShort(), and ShaderEffectItem::renderEffect().
 {
     return m_index_data_offset < 0
             ? 0
             : ((char *) m_data + m_index_data_offset);
 }
indexData() [2/2]
const void * QSGGeometry::indexData () const
Definition at line 114 of file qsggeometry.cpp.
 {
     return m_index_data_offset < 0
             ? 0
             : ((char *) m_data + m_index_data_offset);
 }
indexDataAsUInt() [1/2]
uint * QSGGeometry::indexDataAsUInt () inline
Definition at line 134 of file qsggeometry.h.
Referenced by indexCount().
 {
     Q_ASSERT(m_index_type == GL_UNSIGNED_INT);
     return (uint *) indexData();
 }
indexDataAsUInt() [2/2]
const uint * QSGGeometry::indexDataAsUInt () const inline
Definition at line 146 of file qsggeometry.h.
 {
     Q_ASSERT(m_index_type == GL_UNSIGNED_INT);
     return (uint *) indexData();
 }
indexDataAsUShort() [1/2]
quint16 * QSGGeometry::indexDataAsUShort () inline
Definition at line 140 of file qsggeometry.h.
Referenced by indexCount(), and ShaderEffectItem::updateGeometry().
 {
     Q_ASSERT(m_index_type == GL_UNSIGNED_SHORT);
     return (quint16 *) indexData();
 }
indexDataAsUShort() [2/2]
const quint16 * QSGGeometry::indexDataAsUShort () const inline
Definition at line 152 of file qsggeometry.h.
 {
     Q_ASSERT(m_index_type == GL_UNSIGNED_SHORT);
     return (quint16 *) indexData();
 }
indexType()
int QSGGeometry::indexType () const inline
Definition at line 98 of file qsggeometry.h.
Referenced by ShaderEffectItem::renderEffect().
 { return m_index_type; }
setDrawingMode()
void QSGGeometry::setDrawingMode (GLenum mode)
Definition at line 121 of file qsggeometry.cpp.
 {
     m_drawing_mode = mode;
 }
stride()
int QSGGeometry::stride () const inline
Definition at line 112 of file qsggeometry.h.
Referenced by ShaderEffectItem::bindGeometry().
 { return m_attributes.stride; }
updateRectGeometry()
void QSGGeometry::updateRectGeometry (QSGGeometry * g, const QRectF & rect) static
Definition at line 154 of file qsggeometry.cpp.
Referenced by stride().
 {
     Point2D *v = g->vertexDataAsPoint2D();
     v[0].x = rect.left();
     v[0].y = rect.top();
     v[1].x = rect.right();
     v[1].y = rect.top();
     v[2].x = rect.left();
     v[2].y = rect.bottom();
     v[3].x = rect.right();
     v[3].y = rect.bottom();
 }
updateTexturedRectGeometry()
void QSGGeometry::updateTexturedRectGeometry (QSGGeometry * g, const QRectF & rect, const QRectF & sourceRect) static
Definition at line 170 of file qsggeometry.cpp.
Referenced by stride(), and ShaderEffectItem::updateGeometry().
 {
     TexturedPoint2D *v = g->vertexDataAsTexturedPoint2D();
     v[0].x = rect.left();
     v[0].y = rect.top();
     v[0].tx = textureRect.left();
     v[0].ty = textureRect.top();
     v[1].x = rect.right();
     v[1].y = rect.top();
     v[1].tx = textureRect.right();
     v[1].ty = textureRect.top();
     v[2].x = rect.left();
     v[2].y = rect.bottom();
     v[2].tx = textureRect.left();
     v[2].ty = textureRect.bottom();
     v[3].x = rect.right();
     v[3].y = rect.bottom();
     v[3].tx = textureRect.right();
     v[3].ty = textureRect.bottom();
 }
vertexCount()
int QSGGeometry::vertexCount () const inline
Definition at line 86 of file qsggeometry.h.
Referenced by allocate(), ShaderEffectItem::renderEffect(), and ShaderEffectItem::updateGeometry().
 { return m_vertex_count; }
vertexData() [1/2]
void* QSGGeometry::vertexData () inline
Definition at line 88 of file qsggeometry.h.
Referenced by ShaderEffectItem::bindGeometry().
 { return m_data; }
vertexData() [2/2]
const void* QSGGeometry::vertexData () const inline
Definition at line 93 of file qsggeometry.h.
 { return m_data; }
vertexDataAsColoredPoint2D() [1/2]
QSGGeometry::ColoredPoint2D * QSGGeometry::vertexDataAsColoredPoint2D () inline
Definition at line 181 of file qsggeometry.h.
Referenced by vertexData().
 {
     Q_ASSERT(m_attributes.count == 2);
     Q_ASSERT(m_attributes.stride == 2 * sizeof(float) + 4 * sizeof(char));
     Q_ASSERT(m_attributes.attributes[0].position == 0);
     Q_ASSERT(m_attributes.attributes[0].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[0].type == GL_FLOAT);
     Q_ASSERT(m_attributes.attributes[1].position == 1);
     Q_ASSERT(m_attributes.attributes[1].tupleSize == 4);
     Q_ASSERT(m_attributes.attributes[1].type == GL_UNSIGNED_BYTE);
     return (ColoredPoint2D *) m_data;
 }
vertexDataAsColoredPoint2D() [2/2]
const QSGGeometry::ColoredPoint2D * QSGGeometry::vertexDataAsColoredPoint2D () const inline
Definition at line 217 of file qsggeometry.h.
 {
     Q_ASSERT(m_attributes.count == 2);
     Q_ASSERT(m_attributes.stride == 2 * sizeof(float) + 4 * sizeof(char));
     Q_ASSERT(m_attributes.attributes[0].position == 0);
     Q_ASSERT(m_attributes.attributes[0].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[0].type == GL_FLOAT);
     Q_ASSERT(m_attributes.attributes[1].position == 1);
     Q_ASSERT(m_attributes.attributes[1].tupleSize == 4);
     Q_ASSERT(m_attributes.attributes[1].type == GL_UNSIGNED_BYTE);
     return (const ColoredPoint2D *) m_data;
 }
vertexDataAsPoint2D() [1/2]
QSGGeometry::Point2D * QSGGeometry::vertexDataAsPoint2D () inline
Definition at line 158 of file qsggeometry.h.
Referenced by updateRectGeometry(), and vertexData().
 {
     Q_ASSERT(m_attributes.count == 1);
     Q_ASSERT(m_attributes.stride == 2 * sizeof(float));
     Q_ASSERT(m_attributes.attributes[0].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[0].type == GL_FLOAT);
     Q_ASSERT(m_attributes.attributes[0].position == 0);
     return (Point2D *) m_data;
 }
vertexDataAsPoint2D() [2/2]
const QSGGeometry::Point2D * QSGGeometry::vertexDataAsPoint2D () const inline
Definition at line 194 of file qsggeometry.h.
 {
     Q_ASSERT(m_attributes.count == 1);
     Q_ASSERT(m_attributes.stride == 2 * sizeof(float));
     Q_ASSERT(m_attributes.attributes[0].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[0].type == GL_FLOAT);
     Q_ASSERT(m_attributes.attributes[0].position == 0);
     return (const Point2D *) m_data;
 }
vertexDataAsTexturedPoint2D() [1/2]
QSGGeometry::TexturedPoint2D * QSGGeometry::vertexDataAsTexturedPoint2D () inline
Definition at line 168 of file qsggeometry.h.
Referenced by ShaderEffectItem::updateGeometry(), updateTexturedRectGeometry(), and vertexData().
 {
     Q_ASSERT(m_attributes.count == 2);
     Q_ASSERT(m_attributes.stride == 4 * sizeof(float));
     Q_ASSERT(m_attributes.attributes[0].position == 0);
     Q_ASSERT(m_attributes.attributes[0].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[0].type == GL_FLOAT);
     Q_ASSERT(m_attributes.attributes[1].position == 1);
     Q_ASSERT(m_attributes.attributes[1].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[1].type == GL_FLOAT);
     return (TexturedPoint2D *) m_data;
 }
vertexDataAsTexturedPoint2D() [2/2]
const QSGGeometry::TexturedPoint2D * QSGGeometry::vertexDataAsTexturedPoint2D () const inline
Definition at line 204 of file qsggeometry.h.
 {
     Q_ASSERT(m_attributes.count == 2);
     Q_ASSERT(m_attributes.stride == 4 * sizeof(float));
     Q_ASSERT(m_attributes.attributes[0].position == 0);
     Q_ASSERT(m_attributes.attributes[0].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[0].type == GL_FLOAT);
     Q_ASSERT(m_attributes.attributes[1].position == 1);
     Q_ASSERT(m_attributes.attributes[1].tupleSize == 2);
     Q_ASSERT(m_attributes.attributes[1].type == GL_FLOAT);
     return (const TexturedPoint2D *) m_data;
 }
Properties
m_attributes
const AttributeSet& QSGGeometry::m_attributes private
Definition at line 122 of file qsggeometry.h.
Referenced by allocate(), attributeCount(), attributes(), QSGGeometry(), stride(), vertexDataAsColoredPoint2D(), vertexDataAsPoint2D(), and vertexDataAsTexturedPoint2D().
m_data
void* QSGGeometry::m_data private
Definition at line 123 of file qsggeometry.h.
Referenced by allocate(), indexData(), vertexData(), vertexDataAsColoredPoint2D(), vertexDataAsPoint2D(), vertexDataAsTexturedPoint2D(), and ~QSGGeometry().
m_drawing_mode
int QSGGeometry::m_drawing_mode private
Definition at line 118 of file qsggeometry.h.
Referenced by drawingMode(), and setDrawingMode().
m_index_count
int QSGGeometry::m_index_count private
Definition at line 120 of file qsggeometry.h.
Referenced by allocate(), and indexCount().
m_index_data_offset
int QSGGeometry::m_index_data_offset private
Definition at line 124 of file qsggeometry.h.
Referenced by allocate(), and indexData().
m_index_type
int QSGGeometry::m_index_type private
Definition at line 121 of file qsggeometry.h.
Referenced by allocate(), indexDataAsUInt(), indexDataAsUShort(), and indexType().
m_owns_data
uint QSGGeometry::m_owns_data private
Definition at line 128 of file qsggeometry.h.
Referenced by allocate(), and ~QSGGeometry().
m_prealloc
float QSGGeometry::m_prealloc[16] private
Definition at line 131 of file qsggeometry.h.
Referenced by allocate().
m_reserved_bits
uint QSGGeometry::m_reserved_bits private
Definition at line 129 of file qsggeometry.h.
m_reserved_pointer
void* QSGGeometry::m_reserved_pointer private
Definition at line 126 of file qsggeometry.h.
m_vertex_count
int QSGGeometry::m_vertex_count private
Definition at line 119 of file qsggeometry.h.
Referenced by allocate(), and vertexCount().
The documentation for this class was generated from the following files:
/src/imports/shaders/scenegraph/qsggeometry.h
/src/imports/shaders/scenegraph/qsggeometry.cpp