Qt 4.8: QFileSystemModelPrivate::QFileSystemNode Class Reference
QFileSystemModelPrivate::QFileSystemNode Class Reference
#include <qfilesystemmodel_p.h>
Public Functions
bool caseSensitive () const
bool hasInformation () const
QIcon icon () const
bool isDir () const
bool isExecutable () const
bool isFile () const
bool isHidden () const
bool isReadable () const
bool isSymLink (bool ignoreNtfsSymLinks=false) const
bool isSystem () const
bool isWritable () const
QDateTime lastModified () const
bool operator!= (const QExtendedInformation &fileInfo) const
bool operator< (const QFileSystemNode &node) const
bool operator< (const QString &name) const
bool operator== (const QString &name) const
bool operator== (const QExtendedInformation &fileInfo) const
bool operator> (const QString &name) const
QFile::Permissions permissions () const
void populate (const QExtendedInformation &fileInfo)
QFileSystemNode (const QString &filename=QString(), QFileSystemNode *p=0)
void retranslateStrings (QFileIconProvider *iconProvider, const QString &path)
qint64 size () const
QString type () const
void updateIcon (QFileIconProvider *iconProvider, const QString &path)
int visibleLocation (QString childName)
~QFileSystemNode ()
Public Variables
QHash< QString, QFileSystemNode * > children
int dirtyChildrenIndex
QString fileName
QExtendedInformation * info
bool isVisible
QFileSystemNode * parent
bool populatedChildren
QList< QString > visibleChildren
Detailed Description
Definition at line 83 of file qfilesystemmodel_p.h.
Constructors and Destructors
QFileSystemNode()
QFileSystemModelPrivate::QFileSystemNode::QFileSystemNode (const QString & filename = QString(), QFileSystemNode * p = 0) inline
Definition at line 86 of file qfilesystemmodel_p.h.
             : fileName(filename), populatedChildren(false), isVisible(false), dirtyChildrenIndex(-1), parent(p), info(0) {}
~QFileSystemNode()
QFileSystemModelPrivate::QFileSystemNode::~QFileSystemNode () inline
Definition at line 88 of file qfilesystemmodel_p.h.
{
             QHash<QString, QFileSystemNode*>::const_iterator i = children.constBegin();
             while (i != children.constEnd()) {
                     delete i.value();
                     ++i;
             }
             delete info;
             info = 0;
             parent = 0;
         }
Functions
caseSensitive()
bool QFileSystemModelPrivate::QFileSystemNode::caseSensitive () const inline
Definition at line 122 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::_q_fileSystemChanged(), QFileSystemModelPrivate::node(), and operator<().
 { if (info) return info->isCaseSensitive(); return false; }
hasInformation()
bool QFileSystemModelPrivate::QFileSystemNode::hasInformation () const inline
Definition at line 152 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode(), QFileSystemModel::isDir(), QFileSystemModelPrivate::node(), and QFileSystemModel::timerEvent().
 { return info != 0; }
icon()
QIcon QFileSystemModelPrivate::QFileSystemNode::icon () const inline
Definition at line 123 of file qfilesystemmodel_p.h.
 { if (info) return info->icon; return QIcon(); }
isDir()
bool QFileSystemModelPrivate::QFileSystemNode::isDir () const inline
Definition at line 111 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelSorter::compareNodes(), QFileSystemModel::filePath(), QFileSystemModelPrivate::filtersAcceptsNode(), QFileSystemModel::flags(), QFileSystemModel::hasChildren(), QFileSystemModel::isDir(), QFileSystemModelPrivate::passNameFilters(), QFileSystemModel::setNameFilters(), and QFileSystemModelPrivate::size().
{
             if (info)
                 return info->isDir();
             if (children.count() > 0)
                 return true;
             return false;
         }
isExecutable()
bool QFileSystemModelPrivate::QFileSystemNode::isExecutable () const inline
Definition at line 110 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode().
 { return ((permissions() & QFile::ExeUser) != 0); }
isFile()
bool QFileSystemModelPrivate::QFileSystemNode::isFile () const inline
Definition at line 118 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode().
 { if (info) return info->isFile(); return true; }
isHidden()
bool QFileSystemModelPrivate::QFileSystemNode::isHidden () const inline
Definition at line 120 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode().
 { if (info) return info->isHidden(); return false; }
isReadable()
bool QFileSystemModelPrivate::QFileSystemNode::isReadable () const inline
Definition at line 108 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode().
 { return ((permissions() & QFile::ReadUser) != 0); }
isSymLink()
bool QFileSystemModelPrivate::QFileSystemNode::isSymLink (bool ignoreNtfsSymLinks = false) const inline
Definition at line 121 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModel::filePath(), QFileSystemModelPrivate::filtersAcceptsNode(), and QFileSystemModelPrivate::name().
 { return info && info->isSymLink(ignoreNtfsSymLinks); }
isSystem()
bool QFileSystemModelPrivate::QFileSystemNode::isSystem () const inline
Definition at line 119 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode().
 { if (info) return info->isSystem(); return true; }
isWritable()
bool QFileSystemModelPrivate::QFileSystemNode::isWritable () const inline
Definition at line 109 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode().
 { return ((permissions() & QFile::WriteUser) != 0); }
lastModified()
QDateTime QFileSystemModelPrivate::QFileSystemNode::lastModified () const inline
Definition at line 106 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelSorter::compareNodes().
 { if (info) return info->lastModified(); return QDateTime(); }
operator!=()
bool QFileSystemModelPrivate::QFileSystemNode::operator!= (const QExtendedInformation & fileInfo) const inline
Definition at line 140 of file qfilesystemmodel_p.h.
{
             return !operator==(fileInfo);
         }
operator<() [1/2]
bool QFileSystemModelPrivate::QFileSystemNode::operator< (const QFileSystemNode & node) const inline
Definition at line 125 of file qfilesystemmodel_p.h.
{
             if (caseSensitive() || node.caseSensitive())
                 return fileName < node.fileName;
             return QString::compare(fileName, node.fileName, Qt::CaseInsensitive) < 0;
         }
operator<() [2/2]
bool QFileSystemModelPrivate::QFileSystemNode::operator< (const QString & name) const inline
Definition at line 135 of file qfilesystemmodel_p.h.
{
             if (caseSensitive())
                 return fileName < name;
             return QString::compare(fileName, name, Qt::CaseInsensitive) < 0;
         }
operator==() [1/2]
bool QFileSystemModelPrivate::QFileSystemNode::operator== (const QString & name) const inline
Definition at line 143 of file qfilesystemmodel_p.h.
{
             if (caseSensitive())
                 return fileName == name;
             return QString::compare(fileName, name, Qt::CaseInsensitive) == 0;
         }
operator==() [2/2]
bool QFileSystemModelPrivate::QFileSystemNode::operator== (const QExtendedInformation & fileInfo) const inline
Definition at line 148 of file qfilesystemmodel_p.h.
{
             return info && (*info == fileInfo);
         }
operator>()
bool QFileSystemModelPrivate::QFileSystemNode::operator> (const QString & name) const inline
Definition at line 130 of file qfilesystemmodel_p.h.
{
             if (caseSensitive())
                 return fileName > name;
             return QString::compare(fileName, name, Qt::CaseInsensitive) > 0;
         }
permissions()
QFile::Permissions QFileSystemModelPrivate::QFileSystemNode::permissions () const inline
Definition at line 107 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModel::flags().
 { if (info) return info->permissions(); return 0; }
populate()
void QFileSystemModelPrivate::QFileSystemNode::populate (const QExtendedInformation & fileInfo) inline
Definition at line 154 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::addNode(), QFileSystemModelPrivate::node(), and QFileSystemModel::setData().
{
             if (!info)
                 info = new QExtendedInformation(fileInfo.fileInfo());
             (*info) = fileInfo;
         }
retranslateStrings()
void QFileSystemModelPrivate::QFileSystemNode::retranslateStrings (QFileIconProvider * iconProvider, const QString & path) inline
Definition at line 180 of file qfilesystemmodel_p.h.
{
             if (info)
                 info->displayType = iconProvider->type(QFileInfo(path));
             QHash<QString, QFileSystemNode *>::const_iterator iterator;
             for(iterator = children.constBegin() ; iterator != children.constEnd() ; ++iterator) {
                 //On windows the root (My computer) has no path so we don't want to add a / for nothing (e.g. /C:/)
                 if (!path.isEmpty()) {
                     if (path.endsWith(QLatin1Char('/')))
                         iterator.value()->retranslateStrings(iconProvider, path + iterator.value()->fileName);
                     else
                         iterator.value()->retranslateStrings(iconProvider, path + QLatin1Char('/') + iterator.value()->fileName);
                 } else
                     iterator.value()->retranslateStrings(iconProvider, iterator.value()->fileName);
             }
         }
size()
qint64 QFileSystemModelPrivate::QFileSystemNode::size () const inline
Definition at line 104 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelSorter::compareNodes(), and QFileSystemModelPrivate::size().
 { if (info && !info->isDir()) return info->size(); return 0; }
type()
QString QFileSystemModelPrivate::QFileSystemNode::type () const inline
Definition at line 105 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelSorter::compareNodes().
 { if (info) return info->displayType; return QLatin1String(""); }
updateIcon()
void QFileSystemModelPrivate::QFileSystemNode::updateIcon (QFileIconProvider * iconProvider, const QString & path) inline
Definition at line 164 of file qfilesystemmodel_p.h.
{
             if (info)
                 info->icon = iconProvider->icon(QFileInfo(path));
             QHash<QString, QFileSystemNode *>::const_iterator iterator;
             for(iterator = children.constBegin() ; iterator != children.constEnd() ; ++iterator) {
                 //On windows the root (My computer) has no path so we don't want to add a / for nothing (e.g. /C:/)
                 if (!path.isEmpty()) {
                     if (path.endsWith(QLatin1Char('/')))
                         iterator.value()->updateIcon(iconProvider, path + iterator.value()->fileName);
                     else
                         iterator.value()->updateIcon(iconProvider, path + QLatin1Char('/') + iterator.value()->fileName);
                 } else
                     iterator.value()->updateIcon(iconProvider, iterator.value()->fileName);
             }
         }
visibleLocation()
int QFileSystemModelPrivate::QFileSystemNode::visibleLocation (QString childName) inline
Definition at line 161 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::_q_fileSystemChanged(), QFileSystemModelPrivate::index(), QFileSystemModelPrivate::node(), QFileSystemModel::parent(), QFileSystemModelPrivate::removeNode(), and QFileSystemModel::setData().
{
             return visibleChildren.indexOf(childName);
         }
Properties
children
QHash<QString,QFileSystemNode *> QFileSystemModelPrivate::QFileSystemNode::children
Definition at line 198 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::_q_directoryChanged(), QFileSystemModelPrivate::_q_fileSystemChanged(), QFileSystemModelPrivate::addNode(), QFileSystemModelPrivate::addVisibleFiles(), QFileSystemModel::index(), QFileSystemModel::mkdir(), QFileSystemModelPrivate::node(), QFileSystemModel::parent(), QFileSystemModelPrivate::removeNode(), QFileSystemModelPrivate::removeVisibleFile(), QFileSystemModel::setData(), and QFileSystemModelPrivate::sortChildren().
dirtyChildrenIndex
int QFileSystemModelPrivate::QFileSystemNode::dirtyChildrenIndex
Definition at line 200 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::addVisibleFiles(), QFileSystemModelPrivate::sortChildren(), and QFileSystemModelPrivate::translateVisibleLocation().
fileName
QString QFileSystemModelPrivate::QFileSystemNode::fileName
Definition at line 99 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::addNode(), QFileSystemModelSorter::compareNodes(), QFileSystemModelPrivate::filePath(), QFileSystemModelPrivate::filtersAcceptsNode(), QFileSystemModelPrivate::index(), QFileSystemModelPrivate::name(), QFileSystemModelPrivate::nodeCaseInsensitiveLessThan(), operator<(), QFileSystemModel::parent(), QFileSystemModelPrivate::passNameFilters(), and QFileSystemModel::setData().
info
QExtendedInformation* QFileSystemModelPrivate::QFileSystemNode::info
Definition at line 204 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModel::setData().
isVisible
bool QFileSystemModelPrivate::QFileSystemNode::isVisible
Definition at line 197 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::index(), QFileSystemModelPrivate::node(), QFileSystemModel::setData(), and QFileSystemModelPrivate::sortChildren().
parent
QFileSystemNode* QFileSystemModelPrivate::QFileSystemNode::parent
Definition at line 201 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::filtersAcceptsNode(), QFileSystemModelPrivate::index(), QFileSystemModel::parent(), QFileSystemModel::setData(), and QFileSystemModel::setNameFilters().
populatedChildren
bool QFileSystemModelPrivate::QFileSystemNode::populatedChildren
Definition at line 196 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModel::canFetchMore(), and QFileSystemModel::fetchMore().
visibleChildren
QList<QString> QFileSystemModelPrivate::QFileSystemNode::visibleChildren
Definition at line 199 of file qfilesystemmodel_p.h.
Referenced by QFileSystemModelPrivate::_q_fileSystemChanged(), QFileSystemModelPrivate::addVisibleFiles(), QFileSystemModel::index(), QFileSystemModelPrivate::removeNode(), QFileSystemModelPrivate::removeVisibleFile(), QFileSystemModel::rowCount(), QFileSystemModel::setData(), QFileSystemModelPrivate::sortChildren(), and QFileSystemModelPrivate::translateVisibleLocation().
The documentation for this class was generated from the following file:
/src/gui/dialogs/qfilesystemmodel_p.h