Qt 4.8: QPicturePaintEngine Class Reference
QPicturePaintEngine Class Reference
#include <qpaintengine_pic_p.h>
Public Functions
bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void drawEllipse (const QRectF &rect)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
void drawImage (const QRectF &r, const QImage &image, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
void drawPolygon (const QPointF *points, int numPoints, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawTextItem (const QPointF &p, const QTextItem &ti)
This function draws the text item textItem at position p.
void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
bool end ()
Reimplement this function to finish painting on the current paint device.
QPicturePaintEngine ()
Type type () const
Reimplement this function to return the paint engine Type.
void updateBackground (Qt::BGMode bgmode, const QBrush &bgBrush)
void updateBrush (const QBrush &brush)
void updateBrushOrigin (const QPointF &origin)
void updateClipEnabled (bool enabled)
void updateClipPath (const QPainterPath &path, Qt::ClipOperation op)
void updateClipRegion (const QRegion &region, Qt::ClipOperation op)
void updateCompositionMode (QPainter::CompositionMode cmode)
void updateFont (const QFont &font)
void updateMatrix (const QTransform &matrix)
void updateOpacity (qreal opacity)
void updatePen (const QPen &pen)
void updateRenderHints (QPainter::RenderHints hints)
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
~QPicturePaintEngine ()
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
virtual void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
virtual void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Protected Functions
QPicturePaintEngine (QPaintEnginePrivate &dptr)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Private Functions
void writeCmdLength (int pos, const QRectF &r, bool corr)
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 66 of file qpaintengine_pic_p.h.
Constructors and Destructors
QPicturePaintEngine() [1/2]
QPicturePaintEngine::QPicturePaintEngine ()
Definition at line 74 of file qpaintengine_pic.cpp.
Referenced by type().
     : QPaintEngine(*(new QPicturePaintEnginePrivate), AllFeatures)
 {
     Q_D(QPicturePaintEngine);
     d->pt = 0;
 }
~QPicturePaintEngine()
QPicturePaintEngine::~QPicturePaintEngine ()
Definition at line 88 of file qpaintengine_pic.cpp.
 {
 }
QPicturePaintEngine() [2/2]
QPicturePaintEngine::QPicturePaintEngine (QPaintEnginePrivate & dptr) protected
Definition at line 81 of file qpaintengine_pic.cpp.
     : QPaintEngine(dptr, AllFeatures)
 {
     Q_D(QPicturePaintEngine);
     d->pt = 0;
 }
Functions
begin()
bool QPicturePaintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implements QPaintEngine.
Definition at line 92 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << "QPicturePaintEngine::begin()";
 #endif
     Q_ASSERT(pd);
     QPicture *pic = static_cast<QPicture *>(pd);
     d->pdev = pd;
     d->pic_d = pic->d_func();
     Q_ASSERT(d->pic_d);
     d->s.setDevice(&d->pic_d->pictb);
     d->s.setVersion(d->pic_d->formatMajor);
     d->pic_d->pictb.open(QIODevice::WriteOnly | QIODevice::Truncate);
     d->s.writeRawData(qt_mfhdr_tag, 4);
     d->s << (quint16) 0 << (quint16) d->pic_d->formatMajor << (quint16) d->pic_d->formatMinor;
     d->s << (quint8) QPicturePrivate::PdcBegin << (quint8) sizeof(qint32);
     d->pic_d->brect = QRect();
     if (d->pic_d->formatMajor >= 4) {
         QRect r = pic->boundingRect();
         d->s << (qint32) r.left() << (qint32) r.top() << (qint32) r.width()
              << (qint32) r.height();
     }
     d->pic_d->trecs = 0;
     d->s << (quint32)d->pic_d->trecs; // total number of records
     d->pic_d->formatOk = false;
     setActive(true);
     return true;
 }
drawEllipse()
void QPicturePaintEngine::drawEllipse (const QRectF & rect) virtual
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
The default implementation calls drawPolygon().
Reimplemented from QPaintEngine.
Definition at line 376 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> drawEllipse():" << rect;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcDrawEllipse);
     d->s << rect;
     writeCmdLength(pos, rect, true);
 }
drawImage()
void QPicturePaintEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented from QPaintEngine.
Definition at line 461 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> drawImage():" << r << sr;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcDrawImage);
     if (d->pic_d->in_memory_only) {
         int index = d->pic_d->image_list.size();
         d->pic_d->image_list.append(image);
         d->s << r << index << sr << (quint32) flags;
     } else {
         d->s << r << image << sr << (quint32) flags;
     }
     writeCmdLength(pos, r, false);
 }
drawPath()
void QPicturePaintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QPaintEngine.
Definition at line 388 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> drawPath():" << path.boundingRect();
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcDrawPath);
     d->s << path;
     writeCmdLength(pos, path.boundingRect(), true);
 }
drawPixmap()
void QPicturePaintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngine.
Definition at line 424 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> drawPixmap():" << r;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcDrawPixmap);
     if (d->pic_d->in_memory_only) {
         int index = d->pic_d->pixmap_list.size();
         d->pic_d->pixmap_list.append(pm);
         d->s << r << index << sr;
     } else {
         d->s << r << pm << sr;
     }
     writeCmdLength(pos, r, false);
 }
drawPolygon()
void QPicturePaintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Definition at line 400 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> drawPolygon(): size=" << numPoints;
 #endif
     int pos;
     QPolygonF polygon;
     for (int i=0; i<numPoints; ++i)
         polygon << points[i];
     if (mode == PolylineMode) {
         SERIALIZE_CMD(QPicturePrivate::PdcDrawPolyline);
         d->s << polygon;
     } else {
         SERIALIZE_CMD(QPicturePrivate::PdcDrawPolygon);
         d->s << polygon;
         d->s << (qint8)(mode == OddEvenMode ? 0 : 1);
     }
     writeCmdLength(pos, polygon.boundingRect(), true);
 }
drawTextItem()
void QPicturePaintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QPaintEngine.
Definition at line 480 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> drawTextItem():" << p << ti.text();
 #endif
     const QTextItemInt &si = static_cast<const QTextItemInt &>(ti);
     if (si.chars == 0)
         QPaintEngine::drawTextItem(p, ti); // Draw as path
     if (d->pic_d->formatMajor >= 9) {
         int pos;
         SERIALIZE_CMD(QPicturePrivate::PdcDrawTextItem);
         QFont fnt = ti.font();
         fnt.setUnderline(false);
         fnt.setStrikeOut(false);
         fnt.setOverline(false);
         qreal justificationWidth = 0;
         if (si.justified)
             justificationWidth = si.width.toReal();
         d->s << p << ti.text() << fnt << ti.renderFlags() << double(fnt.d->dpi)/qt_defaultDpi() << justificationWidth;
         writeCmdLength(pos, /*brect=*/QRectF(), /*corr=*/false);
     } else if (d->pic_d->formatMajor >= 8) {
         // old old (buggy) format
         int pos;
         SERIALIZE_CMD(QPicturePrivate::PdcDrawTextItem);
         d->s << QPointF(p.x(), p.y() - ti.ascent()) << ti.text() << ti.font() << ti.renderFlags();
         writeCmdLength(pos, /*brect=*/QRectF(), /*corr=*/false);
     } else {
         // old (buggy) format
         int pos;
         SERIALIZE_CMD(QPicturePrivate::PdcDrawText2);
         d->s << p << ti.text();
         writeCmdLength(pos, QRectF(p, QSizeF(1,1)), true);
     }
 }
drawTiledPixmap()
void QPicturePaintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QPaintEngine.
Definition at line 443 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> drawTiledPixmap():" << r << s;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcDrawTiledPixmap);
     if (d->pic_d->in_memory_only) {
         int index = d->pic_d->pixmap_list.size();
         d->pic_d->pixmap_list.append(pixmap);
         d->s << r << index << s;
     } else {
         d->s << r << pixmap << s;
     }
     writeCmdLength(pos, r, false);
 }
end()
bool QPicturePaintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implements QPaintEngine.
Definition at line 125 of file qpaintengine_pic.cpp.
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << "QPicturePaintEngine::end()";
 #endif
     d->pic_d->trecs++;
     d->s << (quint8) QPicturePrivate::PdcEnd << (quint8) 0;
     int cs_start = sizeof(quint32);                // pos of checksum word
     int data_start = cs_start + sizeof(quint16);
     int brect_start = data_start + 2*sizeof(qint16) + 2*sizeof(quint8);
     int pos = d->pic_d->pictb.pos();
     d->pic_d->pictb.seek(brect_start);
     if (d->pic_d->formatMajor >= 4) { // bounding rectangle
         QRect r = static_cast<QPicture *>(d->pdev)->boundingRect();
         d->s << (qint32) r.left() << (qint32) r.top() << (qint32) r.width()
              << (qint32) r.height();
     }
     d->s << (quint32) d->pic_d->trecs;                        // write number of records
     d->pic_d->pictb.seek(cs_start);
     QByteArray buf = d->pic_d->pictb.buffer();
     quint16 cs = (quint16) qChecksum(buf.constData() + data_start, pos - data_start);
     d->s << cs;                                // write checksum
     d->pic_d->pictb.close();
     setActive(false);
     return true;
 }
type()
Type QPicturePaintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 107 of file qpaintengine_pic_p.h.
 { return Picture; }
updateBackground()
void QPicturePaintEngine::updateBackground (Qt::BGMode bgmode, const QBrush & bgBrush)
Definition at line 257 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateBackground(): mode:" << bgMode << "style:" << bgBrush.style();
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetBkColor);
     d->s << bgBrush.color();
     writeCmdLength(pos, QRect(), false);
     SERIALIZE_CMD(QPicturePrivate::PdcSetBkMode);
     d->s << (qint8) bgMode;
     writeCmdLength(pos, QRectF(), false);
 }
updateBrush()
void QPicturePaintEngine::updateBrush (const QBrush & brush)
Definition at line 214 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateBrush(): style:" << brush.style();
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetBrush);
     if (d->pic_d->in_memory_only) {
         int index = d->pic_d->brush_list.size();
         d->pic_d->brush_list.append(brush);
         d->s << index;
     } else {
         d->s << brush;
     }
     writeCmdLength(pos, QRect(), false);
 }
updateBrushOrigin()
void QPicturePaintEngine::updateBrushOrigin (const QPointF & origin)
Definition at line 232 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateBrushOrigin(): " << p;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetBrushOrigin);
     d->s << p;
     writeCmdLength(pos, QRect(), false);
 }
updateClipEnabled()
void QPicturePaintEngine::updateClipEnabled (bool enabled)
Definition at line 190 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateClipEnabled():" << enabled;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetClipEnabled);
     d->s << enabled;
     writeCmdLength(pos, QRectF(), false);
 }
updateClipPath()
void QPicturePaintEngine::updateClipPath (const QPainterPath & path, Qt::ClipOperation op)
Definition at line 298 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateClipPath(): op:" << op
              << "bounding rect:" << path.boundingRect();
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetClipPath);
     d->s << path << qint8(op);
     writeCmdLength(pos, QRectF(), false);
 }
updateClipRegion()
void QPicturePaintEngine::updateClipRegion (const QRegion & region, Qt::ClipOperation op)
Definition at line 285 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateClipRegion(): op:" << op
              << "bounding rect:" << region.boundingRect();
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetClipRegion);
     d->s << region << qint8(op);
     writeCmdLength(pos, QRectF(), false);
 }
updateCompositionMode()
void QPicturePaintEngine::updateCompositionMode (QPainter::CompositionMode cmode)
Definition at line 178 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateCompositionMode():" << cmode;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetCompositionMode);
     d->s << (qint32)cmode;
     writeCmdLength(pos, QRectF(), false);
 }
updateFont()
void QPicturePaintEngine::updateFont (const QFont & font)
Definition at line 244 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateFont(): pt sz:" << font.pointSize();
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetFont);
     QFont fnt = font;
     d->s << fnt;
     writeCmdLength(pos, QRectF(), false);
 }
updateMatrix()
void QPicturePaintEngine::updateMatrix (const QTransform & matrix)
Definition at line 273 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateMatrix():" << matrix;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetWMatrix);
     d->s << matrix << (qint8) false;
     writeCmdLength(pos, QRectF(), false);
 }
updateOpacity()
void QPicturePaintEngine::updateOpacity (qreal opacity)
Definition at line 202 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateOpacity():" << opacity;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetOpacity);
     d->s << double(opacity);
     writeCmdLength(pos, QRectF(), false);
 }
updatePen()
void QPicturePaintEngine::updatePen (const QPen & pen)
Definition at line 159 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updatePen(): width:" << pen.width() << "style:"
              << pen.style() << "color:" << pen.color();
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetPen);
     if (d->pic_d->in_memory_only) {
         int index = d->pic_d->pen_list.size();
         d->pic_d->pen_list.append(pen);
         d->s << index;
     } else {
         d->s << pen;
     }
     writeCmdLength(pos, QRect(), false);
 }
updateRenderHints()
void QPicturePaintEngine::updateRenderHints (QPainter::RenderHints hints)
Definition at line 312 of file qpaintengine_pic.cpp.
Referenced by updateState().
 {
     Q_D(QPicturePaintEngine);
 #ifdef QT_PICTURE_DEBUG
     qDebug() << " -> updateRenderHints(): " << hints;
 #endif
     int pos;
     SERIALIZE_CMD(QPicturePrivate::PdcSetRenderHint);
     d->s << (quint32) hints;
     writeCmdLength(pos, QRect(), false);
 }
updateState()
void QPicturePaintEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implements QPaintEngine.
Definition at line 520 of file qpaintengine_pic.cpp.
 {
     QPaintEngine::DirtyFlags flags = state.state();
     if (flags & DirtyPen) updatePen(state.pen());
     if (flags & DirtyBrush) updateBrush(state.brush());
     if (flags & DirtyBrushOrigin) updateBrushOrigin(state.brushOrigin());
     if (flags & DirtyFont) updateFont(state.font());
     if (flags & DirtyBackground) updateBackground(state.backgroundMode(), state.backgroundBrush());
     if (flags & DirtyTransform) updateMatrix(state.transform());
     if (flags & DirtyClipEnabled) updateClipEnabled(state.isClipEnabled());
     if (flags & DirtyClipRegion) updateClipRegion(state.clipRegion(), state.clipOperation());
     if (flags & DirtyClipPath) updateClipPath(state.clipPath(), state.clipOperation());
     if (flags & DirtyHints) updateRenderHints(state.renderHints());
     if (flags & DirtyCompositionMode) updateCompositionMode(state.compositionMode());
     if (flags & DirtyOpacity) updateOpacity(state.opacity());
 }
writeCmdLength()
void QPicturePaintEngine::writeCmdLength (int pos, const QRectF & r, bool corr) private
Definition at line 324 of file qpaintengine_pic.cpp.
Referenced by drawEllipse(), drawImage(), drawPath(), drawPixmap(), drawPolygon(), drawTextItem(), drawTiledPixmap(), type(), updateBackground(), updateBrush(), updateBrushOrigin(), updateClipEnabled(), updateClipPath(), updateClipRegion(), updateCompositionMode(), updateFont(), updateMatrix(), updateOpacity(), updatePen(), and updateRenderHints().
 {
     Q_D(QPicturePaintEngine);
     int newpos = d->pic_d->pictb.pos();            // new position
     int length = newpos - pos;
     QRectF br(r);
     if (length < 255) {                         // write 8-bit length
         d->pic_d->pictb.seek(pos - 1);             // position to right index
         d->s << (quint8)length;
     } else {                                    // write 32-bit length
         d->s << (quint32)0;                    // extend the buffer
         d->pic_d->pictb.seek(pos - 1);             // position to right index
         d->s << (quint8)255;                   // indicate 32-bit length
         char *p = d->pic_d->pictb.buffer().data();
         memmove(p+pos+4, p+pos, length);        // make room for 4 byte
         d->s << (quint32)length;
         newpos += 4;
     }
     d->pic_d->pictb.seek(newpos);                  // set to new position
     if (br.width() > 0.0 || br.height() > 0.0) {
         if (corr) {                             // widen bounding rect
             int w2 = painter()->pen().width() / 2;
             br.setCoords(br.left() - w2, br.top() - w2,
                          br.right() + w2, br.bottom() + w2);
         }
         br = painter()->transform().mapRect(br);
         if (painter()->hasClipping()) {
             QRect cr = painter()->clipRegion().boundingRect();
             br &= cr;
         }
         if (br.width() > 0.0 || br.height() > 0.0) {
             int minx = qFloor(br.left());
             int miny = qFloor(br.top());
             int maxx = qCeil(br.right());
             int maxy = qCeil(br.bottom());
             if (d->pic_d->brect.width() > 0 || d->pic_d->brect.height() > 0) {
                 minx = qMin(minx, d->pic_d->brect.left());
                 miny = qMin(miny, d->pic_d->brect.top());
                 maxx = qMax(maxx, d->pic_d->brect.x() + d->pic_d->brect.width());
                 maxy = qMax(maxy, d->pic_d->brect.y() + d->pic_d->brect.height());
                 d->pic_d->brect = QRect(minx, miny, maxx - minx, maxy - miny);
             } else {
                 d->pic_d->brect = QRect(minx, miny, maxx - minx, maxy - miny);
             }
         }
     }
 }
The documentation for this class was generated from the following files:
/src/gui/image/qpaintengine_pic_p.h
/src/gui/image/qpaintengine_pic.cpp