Qt 4.8: QPersistentModelIndex Class Reference
QPersistentModelIndex Class Reference
The QPersistentModelIndex class is used to locate data in a data model.
#include <qabstractitemmodel.h>
Public Functions
QModelIndex child (int row, int column) const
Returns the child of the model index that is stored in the given row and column.
int column () const
Returns the column this persistent model index refers to.
QVariant data (int role=Qt::DisplayRole) const
Returns the data for the given role for the item referred to by the index.
Qt::ItemFlags flags () const
Returns the flags for the item referred to by the index.
qint64 internalId () const
void * internalPointer () const
bool isValid () const
Returns true if this persistent model index is valid; otherwise returns false.
const QAbstractItemModel * model () const
Returns the model that the index belongs to.
operator const QModelIndex & () const
Cast operator that returns a const QModelIndex&.
bool operator!= (const QPersistentModelIndex &other) const
Returns true if this persistent model index is not equal to the other persistent model index; otherwise returns false.
bool operator!= (const QModelIndex &other) const
Returns true if this persistent model index does not refer to the same location as the other model index; otherwise returns false.
bool operator< (const QPersistentModelIndex &other) const
Returns true if this persistent model index is smaller than the other persistent model index; otherwise returns false.
QPersistentModelIndex & operator= (const QPersistentModelIndex &other)
Sets the persistent model index to refer to the same item in a model as the other persistent model index.
QPersistentModelIndex & operator= (const QModelIndex &other)
Sets the persistent model index to refer to the same item in a model as the other model index.
bool operator== (const QPersistentModelIndex &other) const
Returns true if this persistent model index is equal to the other persistent model index; otherwise returns false.
bool operator== (const QModelIndex &other) const
Returns true if this persistent model index refers to the same location as the other model index; otherwise returns false.
QModelIndex parent () const
Returns the parent QModelIndex for this persistent index, or an invalid QModelIndex if it has no parent.
QPersistentModelIndex ()
QPersistentModelIndex (const QModelIndex &index)
Creates a new QPersistentModelIndex that is a copy of the model index.
QPersistentModelIndex (const QPersistentModelIndex &other)
Creates a new QPersistentModelIndex that is a copy of the other persistent model index.
int row () const
Returns the row this persistent model index refers to.
QModelIndex sibling (int row, int column) const
Returns the sibling at row and column or an invalid QModelIndex if there is no sibling at this position.
~QPersistentModelIndex ()
Properties
QPersistentModelIndexData * d
Friends
Q_CORE_EXPORT QDebug operator<< (QDebug, const QPersistentModelIndex &)
uint qHash (const QPersistentModelIndex &)
Detailed Description
The QPersistentModelIndex class is used to locate data in a data model.
A QPersistentModelIndex is a model index that can be stored by an application, and later used to access information in a model. Unlike the QModelIndex class, it is safe to store a QPersistentModelIndex since the model will ensure that references to items will continue to be valid as long as they can be accessed by the model.
It is good practice to check that persistent model indexes are valid before using them.
See also
{Model/View Programming}, QModelIndex, QAbstractItemModel
Definition at line 107 of file qabstractitemmodel.h.
Constructors and Destructors
QPersistentModelIndex() [1/3]
QPersistentModelIndex::QPersistentModelIndex ()
Warning
This function is not part of the public interface.
Definition at line 118 of file qabstractitemmodel.cpp.
     : d(0)
 {
 }
QPersistentModelIndex() [2/3]
QPersistentModelIndex::QPersistentModelIndex (const QModelIndex & index)
Creates a new QPersistentModelIndex that is a copy of the model index.
Definition at line 143 of file qabstractitemmodel.cpp.
     : d(0)
 {
     if (index.isValid()) {
         d = QPersistentModelIndexData::create(index);
         d->ref.ref();
     }
 }
QPersistentModelIndex() [3/3]
QPersistentModelIndex::QPersistentModelIndex (const QPersistentModelIndex & other)
Creates a new QPersistentModelIndex that is a copy of the other persistent model index.
Definition at line 133 of file qabstractitemmodel.cpp.
     : d(other.d)
 {
     if (d) d->ref.ref();
 }
~QPersistentModelIndex()
QPersistentModelIndex::~QPersistentModelIndex ()
Warning
This function is not part of the public interface.
Definition at line 158 of file qabstractitemmodel.cpp.
 {
     if (d && !d->ref.deref()) {
         QPersistentModelIndexData::destroy(d);
         d = 0;
     }
 }
Functions
child()
QModelIndex QPersistentModelIndex::child (int row, int column) const
Returns the child of the model index that is stored in the given row and column.
See also
parent() sibling()
Definition at line 399 of file qabstractitemmodel.cpp.
 {
     if (d)
         return d->index.child(row, column);
     return QModelIndex();
 }
column()
int QPersistentModelIndex::column () const
Returns the column this persistent model index refers to.
Definition at line 326 of file qabstractitemmodel.cpp.
Referenced by QDataWidgetMapperPrivate::currentIdx(), QAbstractItemModelPrivate::movePersistentIndexes(), QItemSelectionRange::operator<(), and QItemSelectionModel::setCurrentIndex().
 {
     if (d)
         return d->index.column();
     return -1;
 }
data()
QVariant QPersistentModelIndex::data (int role = Qt::DisplayRole) const
Returns the data for the given role for the item referred to by the index.
See also
Qt::ItemDataRole, QAbstractItemModel::setData()
Definition at line 412 of file qabstractitemmodel.cpp.
Referenced by QAbstractItemModelPrivate::columnsAboutToBeInserted(), QAbstractItemModelPrivate::columnsAboutToBeRemoved(), QAbstractItemModelPrivate::columnsInserted(), QAbstractItemModelPrivate::columnsRemoved(), QAbstractItemModelPrivate::itemsAboutToBeMoved(), QAbstractItemModelPrivate::movePersistentIndexes(), QDataWidgetMapperPrivate::populate(), QSidebar::removeEntry(), QAbstractItemModelPrivate::rowsAboutToBeInserted(), QAbstractItemModelPrivate::rowsAboutToBeRemoved(), QAbstractItemModelPrivate::rowsInserted(), and QAbstractItemModelPrivate::rowsRemoved().
 {
     if (d)
         return d->index.data(role);
     return QVariant();
 }
flags()
Qt::ItemFlags QPersistentModelIndex::flags () const
Returns the flags for the item referred to by the index.
Since
4.2
Definition at line 427 of file qabstractitemmodel.cpp.
Referenced by QAccessibleItemRow::state().
 {
     if (d)
         return d->index.flags();
     return 0;
 }
internalId()
qint64 QPersistentModelIndex::internalId () const
Warning
This function is not part of the public interface.
Returns a qint64 used by the model to associate the index with the internal data structure.
Definition at line 358 of file qabstractitemmodel.cpp.
 {
     if (d)
         return d->index.internalId();
     return 0;
 }
internalPointer()
void * QPersistentModelIndex::internalPointer () const
Warning
This function is not part of the public interface.
Returns a void * pointer used by the model to associate the index with the internal data structure.
Definition at line 342 of file qabstractitemmodel.cpp.
 {
     if (d)
         return d->index.internalPointer();
     return 0;
 }
isValid()
bool QPersistentModelIndex::isValid () const
Returns true if this persistent model index is valid; otherwise returns false.
A valid index belongs to a model, and has non-negative row and column numbers.
See also
model(), row(), column()
Definition at line 459 of file qabstractitemmodel.cpp.
Referenced by QListWidgetPrivate::_q_emitCurrentItemChanged(), QAbstractItemViewPrivate::checkMouseMove(), QDataWidgetMapperPrivate::commit(), QAccessibleItemRow::isValid(), QAbstractItemView::keyPressEvent(), QTreeView::mouseDoubleClickEvent(), QAbstractItemView::mouseMoveEvent(), QAbstractItemView::mousePressEvent(), QAbstractItemView::mouseReleaseEvent(), and QAccessibleItemRow::rect().
 {
     return d && d->index.isValid();
 }
model()
const QAbstractItemModel * QPersistentModelIndex::model () const
Returns the model that the index belongs to.
Definition at line 437 of file qabstractitemmodel.cpp.
Referenced by QAccessibleItemRow::children(), QItemSelectionRange::operator<(), and QAccessibleItemRow::rect().
 {
     if (d)
         return d->index.model();
     return 0;
 }
operator const QModelIndex &()
QPersistentModelIndex::operator const QModelIndex & () const
Cast operator that returns a const QModelIndex&.
Definition at line 256 of file qabstractitemmodel.cpp.
 {
     static const QModelIndex invalid;
     if (d)
         return d->index;
     return invalid;
 }
operator!=() [1/2]
bool QPersistentModelIndex::operator!= (const QPersistentModelIndex & other) const inline
Returns true if this persistent model index is not equal to the other persistent model index; otherwise returns false.
Since
4.2
Definition at line 116 of file qabstractitemmodel.h.
     { return !operator==(other); }
operator!=() [2/2]
bool QPersistentModelIndex::operator!= (const QModelIndex & other) const
Returns true if this persistent model index does not refer to the same location as the other model index; otherwise returns false.
Definition at line 294 of file qabstractitemmodel.cpp.
 {
     if (d)
         return d->index != other;
     return other.isValid();
 }
operator<()
bool QPersistentModelIndex::operator< (const QPersistentModelIndex & other) const
Returns true if this persistent model index is smaller than the other persistent model index; otherwise returns false.
Since
4.1
All values in the persistent model index are used when comparing with another persistent model index.
Definition at line 194 of file qabstractitemmodel.cpp.
 {
     if (d && other.d)
         return d->index < other.d->index;
     return d < other.d;
 }
operator=() [1/2]
QPersistentModelIndex & QPersistentModelIndex::operator= (const QPersistentModelIndex & other)
Sets the persistent model index to refer to the same item in a model as the other persistent model index.
Definition at line 218 of file qabstractitemmodel.cpp.
 {
     if (d == other.d)
         return *this;
     if (d && !d->ref.deref())
         QPersistentModelIndexData::destroy(d);
     d = other.d;
     if (d) d->ref.ref();
     return *this;
 }
operator=() [2/2]
QPersistentModelIndex & QPersistentModelIndex::operator= (const QModelIndex & other)
Sets the persistent model index to refer to the same item in a model as the other model index.
Definition at line 234 of file qabstractitemmodel.cpp.
 {
     if (d && !d->ref.deref())
         QPersistentModelIndexData::destroy(d);
     if (other.isValid()) {
         d = QPersistentModelIndexData::create(other);
         if (d) d->ref.ref();
     } else {
         d = 0;
     }
     return *this;
 }
operator==() [1/2]
bool QPersistentModelIndex::operator== (const QPersistentModelIndex & other) const
Returns true if this persistent model index is equal to the other persistent model index; otherwise returns false.
All values in the persistent model index are used when comparing with another persistent model index.
Definition at line 174 of file qabstractitemmodel.cpp.
 {
     if (d && other.d)
         return d->index == other.d->index;
     return d == other.d;
 }
operator==() [2/2]
bool QPersistentModelIndex::operator== (const QModelIndex & other) const
Returns true if this persistent model index refers to the same location as the other model index; otherwise returns false.
All values in the persistent model index are used when comparing with another model index.
Definition at line 277 of file qabstractitemmodel.cpp.
 {
     if (d)
         return d->index == other;
     return !other.isValid();
 }
parent()
QModelIndex QPersistentModelIndex::parent () const
Returns the parent QModelIndex for this persistent index, or an invalid QModelIndex if it has no parent.
See also
child() sibling() model()
Definition at line 371 of file qabstractitemmodel.cpp.
Referenced by QAccessibleItemRow::children(), QAbstractItemModelPrivate::columnsAboutToBeInserted(), QAbstractItemModelPrivate::columnsInserted(), QAbstractItemModelPrivate::columnsRemoved(), QAbstractItemModelPrivate::itemsAboutToBeMoved(), QAccessibleItemRow::navigate(), QItemSelectionRange::operator<(), QAccessibleItemRow::rect(), QAbstractItemModelPrivate::rowsAboutToBeInserted(), QAbstractItemModelPrivate::rowsInserted(), QAbstractItemModelPrivate::rowsRemoved(), QItemSelectionModel::setCurrentIndex(), QAccessibleItemRow::state(), and QAccessibleItemRow::text().
 {
     if (d)
         return d->index.parent();
     return QModelIndex();
 }
row()
int QPersistentModelIndex::row () const
Returns the row this persistent model index refers to.
Definition at line 310 of file qabstractitemmodel.cpp.
Referenced by QListWidgetPrivate::_q_emitCurrentItemChanged(), QComboBoxPrivate::_q_modelReset(), QAccessibleItemRow::children(), QDataWidgetMapperPrivate::currentIdx(), QListWidget::dropEvent(), QTreeWidget::dropEvent(), QAbstractItemModelPrivate::movePersistentIndexes(), QAccessibleItemRow::navigate(), ModelIndexIterator::next(), QItemSelectionRange::operator<(), QAccessibleItemRow::rect(), QSidebar::removeEntry(), QItemSelectionModel::setCurrentIndex(), QAccessibleItemRow::setText(), QAccessibleItemRow::state(), QAccessibleItemRow::text(), and QAccessibleItemRow::text_helper().
 {
     if (d)
         return d->index.row();
     return -1;
 }
sibling()
QModelIndex QPersistentModelIndex::sibling (int row, int column) const
Returns the sibling at row and column or an invalid QModelIndex if there is no sibling at this position.
See also
parent() child()
Definition at line 385 of file qabstractitemmodel.cpp.
Referenced by QAccessibleItemRow::text().
 {
     if (d)
         return d->index.sibling(row, column);
     return QModelIndex();
 }
Friends and Related Functions
operator<<
Q_CORE_EXPORT QDebug operator<< (QDebug , const QPersistentModelIndex &) friend
Definition at line 478 of file qabstractitemmodel.cpp.
 {
     if (idx.d)
         dbg << idx.d->index;
     else
         dbg << QModelIndex();
     return dbg;
 }
qHash
uint qHash (const QPersistentModelIndex & index) friend
Definition at line 143 of file qabstractitemmodel.h.
 { return qHash(index.d); }
Properties
d
QPersistentModelIndexData* QPersistentModelIndex::d private
Definition at line 135 of file qabstractitemmodel.h.
Referenced by child(), column(), data(), flags(), internalId(), internalPointer(), isValid(), model(), operator const QModelIndex &(), operator!=(), operator<(), operator<<(), operator=(), operator==(), parent(), qHash(), QPersistentModelIndex(), row(), sibling(), and ~QPersistentModelIndex().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qabstractitemmodel.h
/src/corelib/kernel/qabstractitemmodel.cpp