Qt 4.8: QTabBarPrivate Class Reference
QTabBarPrivate Class Reference
#include <qtabbar_p.h>
Classes
struct Tab
Public Functions
void _q_closeTab ()
void _q_scrollTabs ()
Tab * at (int index)
const Tab * at (int index) const
int calculateNewPosition (int from, int to, int index) const
int extraWidth () const
int indexAtPos (const QPoint &p) const
void init ()
void layoutTab (int index)
void layoutTabs ()
void layoutWidgets (int start=0)
void makeVisible (int index)
QSize minimumTabSizeHint (int index)
void moveTab (int index, int offset)
em>Reimplemented Function
void moveTabFinished (int index)
em>Reimplemented Function
QTabBarPrivate ()
void refresh ()
void setCurrentNextEnabledIndex (int offset)
em>Reimplemented Function
void setupMovableTab ()
void slide (int from, int to)
void updateMacBorderMetrics ()
bool validIndex (int index) const
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static void initStyleBaseOption (QStyleOptionTabBarBaseV2 *optTabBase, QTabBar *tabbar, QSize size)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool closeButtonOnTabs
int currentIndex
bool documentMode
bool dragInProgress
QPoint dragStartPosition
bool drawBase
Qt::TextElideMode elideMode
bool elideModeSetByUser
bool expanding
QRect hoverRect
QSize iconSize
bool layoutDirty
QToolButton * leftB
bool movable
QWidget * movingTab
bool paintWithOffsets
int pressedIndex
int previousPressedIndex
QToolButton * rightB
int scrollOffset
QTabBar::SelectionBehavior selectionBehaviorOnRemove
QTabBar::Shape shape
QList< Tab > tabList
bool useScrollButtons
bool useScrollButtonsSetByUser
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 72 of file qtabbar_p.h.
Constructors and Destructors
QTabBarPrivate()
QTabBarPrivate::QTabBarPrivate () inline
Definition at line 76 of file qtabbar_p.h.
         :currentIndex(-1), pressedIndex(-1), shape(QTabBar::RoundedNorth), layoutDirty(false),
         drawBase(true), scrollOffset(0), elideModeSetByUser(false), useScrollButtonsSetByUser(false), expanding(true), closeButtonOnTabs(false),
         selectionBehaviorOnRemove(QTabBar::SelectRightTab), paintWithOffsets(true), movable(false),
         dragInProgress(false), documentMode(false), movingTab(0)
 #ifdef Q_WS_MAC
         , previousPressedIndex(-1)
 #endif
         {}
Functions
_q_closeTab()
void QTabBarPrivate::_q_closeTab ()
Definition at line 655 of file qtabbar.cpp.
 {
     Q_Q(QTabBar);
     QObject *object = q->sender();
     int tabToClose = -1;
     QTabBar::ButtonPosition closeSide = (QTabBar::ButtonPosition)q->style()->styleHint(QStyle::SH_TabBar_CloseButtonPosition, 0, q);
     for (int i = 0; i < tabList.count(); ++i) {
         if (closeSide == QTabBar::LeftSide) {
             if (tabList.at(i).leftWidget == object) {
                 tabToClose = i;
                 break;
             }
         } else {
             if (tabList.at(i).rightWidget == object) {
                 tabToClose = i;
                 break;
             }
         }
     }
     if (tabToClose != -1)
         emit q->tabCloseRequested(tabToClose);
 }
_q_scrollTabs()
void QTabBarPrivate::_q_scrollTabs ()
Definition at line 678 of file qtabbar.cpp.
Referenced by init().
 {
     Q_Q(QTabBar);
     const QObject *sender = q->sender();
     int i = -1;
     if (!verticalTabs(shape)) {
         if (sender == leftB) {
             for (i = tabList.count() - 1; i >= 0; --i) {
                 if (tabList.at(i).rect.left() - scrollOffset < 0) {
                     makeVisible(i);
                     return;
                 }
             }
         } else if (sender == rightB) {
             int availableWidth = q->width() - extraWidth();
             for (i = 0; i < tabList.count(); ++i) {
                 if (tabList.at(i).rect.right() - scrollOffset > availableWidth) {
                     makeVisible(i);
                     return;
                 }
             }
         }
     } else { // vertical
         if (sender == leftB) {
             for (i = tabList.count() - 1; i >= 0; --i) {
                 if (tabList.at(i).rect.top() - scrollOffset < 0) {
                     makeVisible(i);
                     return;
                 }
             }
         } else if (sender == rightB) {
             int available = q->height() - extraWidth();
             for (i = 0; i < tabList.count(); ++i) {
                 if (tabList.at(i).rect.bottom() - scrollOffset > available) {
                     makeVisible(i);
                     return;
                 }
             }
         }
     }
 }
at() [1/2]
QTabBarPrivate::Tab * QTabBarPrivate::at (int index)
Definition at line 385 of file qtabbar.cpp.
 {
     return validIndex(index)?&tabList[index]:0;
 }
at() [2/2]
const QTabBarPrivate::Tab * QTabBarPrivate::at (int index) const
Definition at line 390 of file qtabbar.cpp.
 {
     return validIndex(index)?&tabList[index]:0;
 }
calculateNewPosition()
int QTabBarPrivate::calculateNewPosition (int from, int to, int index) const
Definition at line 1654 of file qtabbar.cpp.
 {
     if (index == from)
         return to;
     int start = qMin(from, to);
     int end = qMax(from, to);
     if (index >= start && index <= end)
         index += (from < to) ? -1 : 1;
     return index;
 }
extraWidth()
int QTabBarPrivate::extraWidth () const
Definition at line 354 of file qtabbar.cpp.
Referenced by _q_scrollTabs(), layoutTabs(), and makeVisible().
 {
     Q_Q(const QTabBar);
     return 2 * qMax(q->style()->pixelMetric(QStyle::PM_TabBarScrollButtonWidth, 0, q),
                     QApplication::globalStrut().width());
 }
indexAtPos()
int QTabBarPrivate::indexAtPos (const QPoint & p) const
Definition at line 395 of file qtabbar.cpp.
 {
     Q_Q(const QTabBar);
     if (q->tabRect(currentIndex).contains(p))
         return currentIndex;
     for (int i = 0; i < tabList.count(); ++i)
         if (tabList.at(i).enabled && q->tabRect(i).contains(p))
             return i;
     return -1;
 }
init()
void QTabBarPrivate::init ()
Definition at line 361 of file qtabbar.cpp.
 {
     Q_Q(QTabBar);
     leftB = new QToolButton(q);
     leftB->setAutoRepeat(true);
     QObject::connect(leftB, SIGNAL(clicked()), q, SLOT(_q_scrollTabs()));
     leftB->hide();
     rightB = new QToolButton(q);
     rightB->setAutoRepeat(true);
     QObject::connect(rightB, SIGNAL(clicked()), q, SLOT(_q_scrollTabs()));
     rightB->hide();
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled()) {
         leftB->setFocusPolicy(Qt::NoFocus);
         rightB->setFocusPolicy(Qt::NoFocus);
         q->setFocusPolicy(Qt::NoFocus);
     } else
 #endif
     q->setFocusPolicy(Qt::TabFocus);
     q->setSizePolicy(QSizePolicy::Preferred, QSizePolicy::Fixed);
     elideMode = Qt::TextElideMode(q->style()->styleHint(QStyle::SH_TabBar_ElideMode, 0, q));
     useScrollButtons = !q->style()->styleHint(QStyle::SH_TabBar_PreferNoArrows, 0, q);
 }
initStyleBaseOption()
static void QTabBarPrivate::initStyleBaseOption (QStyleOptionTabBarBaseV2 * optTabBase, QTabBar * tabbar, QSize size) inline static
Definition at line 208 of file qtabbar_p.h.
Referenced by QTabWidget::paintEvent(), and QTabBar::paintEvent().
     {
         QStyleOptionTab tabOverlap;
         tabOverlap.shape = tabbar->shape();
         int overlap = tabbar->style()->pixelMetric(QStyle::PM_TabBarBaseOverlap, &tabOverlap, tabbar);
         QWidget *theParent = tabbar->parentWidget();
         optTabBase->init(tabbar);
         optTabBase->shape = tabbar->shape();
         optTabBase->documentMode = tabbar->documentMode();
         if (theParent && overlap > 0) {
             QRect rect;
             switch (tabOverlap.shape) {
             case QTabBar::RoundedNorth:
             case QTabBar::TriangularNorth:
                 rect.setRect(0, size.height()-overlap, size.width(), overlap);
                 break;
             case QTabBar::RoundedSouth:
             case QTabBar::TriangularSouth:
                 rect.setRect(0, 0, size.width(), overlap);
                 break;
             case QTabBar::RoundedEast:
             case QTabBar::TriangularEast:
                 rect.setRect(0, 0, overlap, size.height());
                 break;
             case QTabBar::RoundedWest:
             case QTabBar::TriangularWest:
                 rect.setRect(size.width() - overlap, 0, overlap, size.height());
                 break;
             }
             optTabBase->rect = rect;
         }
     }
layoutTab()
void QTabBarPrivate::layoutTab (int index)
Definition at line 611 of file qtabbar.cpp.
Referenced by layoutWidgets().
 {
     Q_Q(QTabBar);
     Q_ASSERT(index >= 0);
     Tab &tab = tabList[index];
     bool vertical = verticalTabs(shape);
     if (!(tab.leftWidget || tab.rightWidget))
         return;
     QStyleOptionTabV3 opt;
     q->initStyleOption(&opt, index);
     if (tab.leftWidget) {
         QRect rect = q->style()->subElementRect(QStyle::SE_TabBarTabLeftButton, &opt, q);
         QPoint p = rect.topLeft();
         if ((index == pressedIndex) || paintWithOffsets) {
             if (vertical)
                 p.setY(p.y() + tabList[index].dragOffset);
             else
                 p.setX(p.x() + tabList[index].dragOffset);
         }
         tab.leftWidget->move(p);
     }
     if (tab.rightWidget) {
         QRect rect = q->style()->subElementRect(QStyle::SE_TabBarTabRightButton, &opt, q);
         QPoint p = rect.topLeft();
         if ((index == pressedIndex) || paintWithOffsets) {
             if (vertical)
                 p.setY(p.y() + tab.dragOffset);
             else
                 p.setX(p.x() + tab.dragOffset);
         }
         tab.rightWidget->move(p);
     }
 }
layoutTabs()
void QTabBarPrivate::layoutTabs ()
Definition at line 406 of file qtabbar.cpp.
Referenced by refresh().
 {
     Q_Q(QTabBar);
     scrollOffset = 0;
     layoutDirty = false;
     QSize size = q->size();
     int last, available;
     int maxExtent;
     int i;
     bool vertTabs = verticalTabs(shape);
     int tabChainIndex = 0;
     Qt::Alignment tabAlignment = Qt::Alignment(q->style()->styleHint(QStyle::SH_TabBar_Alignment, 0, q));
     QVector<QLayoutStruct> tabChain(tabList.count() + 2);
     // We put an empty item at the front and back and set its expansive attribute
     // depending on tabAlignment.
     tabChain[tabChainIndex].init();
     tabChain[tabChainIndex].expansive = (tabAlignment != Qt::AlignLeft)
                                         && (tabAlignment != Qt::AlignJustify);
     tabChain[tabChainIndex].empty = true;
     ++tabChainIndex;
     // We now go through our list of tabs and set the minimum size and the size hint
     // This will allow us to elide text if necessary. Since we don't set
     // a maximum size, tabs will EXPAND to fill up the empty space.
     // Since tab widget is rather *ahem* strict about keeping the geometry of the
     // tab bar to its absolute minimum, this won't bleed through, but will show up
     // if you use tab bar on its own (a.k.a. not a bug, but a feature).
     // Update: if expanding is false, we DO set a maximum size to prevent the tabs
     // being wider than necessary.
     if (!vertTabs) {
         int minx = 0;
         int x = 0;
         int maxHeight = 0;
         for (i = 0; i < tabList.count(); ++i, ++tabChainIndex) {
             QSize sz = q->tabSizeHint(i);
             tabList[i].maxRect = QRect(x, 0, sz.width(), sz.height());
             x += sz.width();
             maxHeight = qMax(maxHeight, sz.height());
             sz = minimumTabSizeHint(i);
             tabList[i].minRect = QRect(minx, 0, sz.width(), sz.height());
             minx += sz.width();
             tabChain[tabChainIndex].init();
             tabChain[tabChainIndex].sizeHint = tabList.at(i).maxRect.width();
             tabChain[tabChainIndex].minimumSize = sz.width();
             tabChain[tabChainIndex].empty = false;
             tabChain[tabChainIndex].expansive = true;
             if (!expanding)
                 tabChain[tabChainIndex].maximumSize = tabChain[tabChainIndex].sizeHint;
         }
         last = minx;
         available = size.width();
         maxExtent = maxHeight;
     } else {
         int miny = 0;
         int y = 0;
         int maxWidth = 0;
         for (i = 0; i < tabList.count(); ++i, ++tabChainIndex) {
             QSize sz = q->tabSizeHint(i);
             tabList[i].maxRect = QRect(0, y, sz.width(), sz.height());
             y += sz.height();
             maxWidth = qMax(maxWidth, sz.width());
             sz = minimumTabSizeHint(i);
             tabList[i].minRect = QRect(0, miny, sz.width(), sz.height());
             miny += sz.height();
             tabChain[tabChainIndex].init();
             tabChain[tabChainIndex].sizeHint = tabList.at(i).maxRect.height();
             tabChain[tabChainIndex].minimumSize = sz.height();
             tabChain[tabChainIndex].empty = false;
             tabChain[tabChainIndex].expansive = true;
             if (!expanding)
                 tabChain[tabChainIndex].maximumSize = tabChain[tabChainIndex].sizeHint;
         }
         last = miny;
         available = size.height();
         maxExtent = maxWidth;
     }
     Q_ASSERT(tabChainIndex == tabChain.count() - 1); // add an assert just to make sure.
     // Mirror our front item.
     tabChain[tabChainIndex].init();
     tabChain[tabChainIndex].expansive = (tabAlignment != Qt::AlignRight)
                                         && (tabAlignment != Qt::AlignJustify);
     tabChain[tabChainIndex].empty = true;
     // Do the calculation
     qGeomCalc(tabChain, 0, tabChain.count(), 0, qMax(available, last), 0);
     // Use the results
     for (i = 0; i < tabList.count(); ++i) {
         const QLayoutStruct &lstruct = tabChain.at(i + 1);
         if (!vertTabs)
             tabList[i].rect.setRect(lstruct.pos, 0, lstruct.size, maxExtent);
         else
             tabList[i].rect.setRect(0, lstruct.pos, maxExtent, lstruct.size);
     }
     if (useScrollButtons && tabList.count() && last > available) {
         int extra = extraWidth();
 #ifndef QT_NO_STYLE_S60
         QS60Style *s60Style = qobject_cast<QS60Style*>(QApplication::style());
 #endif
         if (!vertTabs) {
             Qt::LayoutDirection ld = q->layoutDirection();
             QRect arrows = QStyle::visualRect(ld, q->rect(),
                                               QRect(available - extra, 0, extra, size.height()));
             int buttonOverlap = q->style()->pixelMetric(QStyle::PM_TabBar_ScrollButtonOverlap, 0, q);
             if (ld == Qt::LeftToRight) {
 // In S60style, tab scroll buttons are layoutted separately, on the sides of the tabbar.
 #ifndef QT_NO_STYLE_S60
                 if (s60Style) {
                     rightB->setGeometry(arrows.left() + extra / 2, arrows.top(), extra / 2, arrows.height());
                     leftB->setGeometry(0, arrows.top(), extra / 2, arrows.height());
                 } else {
 #endif
                 leftB->setGeometry(arrows.left(), arrows.top(), extra/2, arrows.height());
                 rightB->setGeometry(arrows.right() - extra/2 + buttonOverlap, arrows.top(),
                                     extra/2, arrows.height());
 #ifndef QT_NO_STYLE_S60
                 }
 #endif
                 leftB->setArrowType(Qt::LeftArrow);
                 rightB->setArrowType(Qt::RightArrow);
             } else {
 #ifndef QT_NO_STYLE_S60
                 if (s60Style) {
                     rightB->setGeometry(arrows.left() + extra / 2, arrows.top(), extra / 2, arrows.height());
                     leftB->setGeometry(0, arrows.top(), extra / 2, arrows.height());
                 } else {
 #endif
                 rightB->setGeometry(arrows.left(), arrows.top(), extra/2, arrows.height());
                 leftB->setGeometry(arrows.right() - extra/2 + buttonOverlap, arrows.top(),
                                     extra/2, arrows.height());
 #ifndef QT_NO_STYLE_S60
                 }
 #endif
                 rightB->setArrowType(Qt::LeftArrow);
                 leftB->setArrowType(Qt::RightArrow);
             }
         } else {
 #ifndef QT_NO_STYLE_S60
             if (s60Style) {
                 QRect arrows = QRect(0, 0, size.width(), available );
                 leftB->setGeometry(arrows.left(), arrows.top(), arrows.width(), extra / 2);
                 leftB->setArrowType(Qt::UpArrow);
                 rightB->setGeometry(arrows.left(), arrows.bottom() - extra / 2 + 1,
                                     arrows.width(), extra / 2);
                 rightB->setArrowType(Qt::DownArrow);
             } else {
 #endif
             QRect arrows = QRect(0, available - extra, size.width(), extra );
             leftB->setGeometry(arrows.left(), arrows.top(), arrows.width(), extra/2);
             leftB->setArrowType(Qt::UpArrow);
             rightB->setGeometry(arrows.left(), arrows.bottom() - extra/2 + 1,
                                 arrows.width(), extra/2);
             rightB->setArrowType(Qt::DownArrow);
 #ifndef QT_NO_STYLE_S60
             }
 #endif
         }
         leftB->setEnabled(scrollOffset > 0);
         rightB->setEnabled(last - scrollOffset >= available - extra);
         leftB->show();
         rightB->show();
     } else {
         rightB->hide();
         leftB->hide();
     }
     layoutWidgets();
     q->tabLayoutChange();
 }
layoutWidgets()
void QTabBarPrivate::layoutWidgets (int start = 0)
Definition at line 647 of file qtabbar.cpp.
Referenced by layoutTabs(), and makeVisible().
 {
     Q_Q(QTabBar);
     for (int i = start; i < q->count(); ++i) {
         layoutTab(i);
     }
 }
makeVisible()
void QTabBarPrivate::makeVisible (int index)
Definition at line 585 of file qtabbar.cpp.
Referenced by _q_scrollTabs(), and refresh().
 {
     Q_Q(QTabBar);
     if (!validIndex(index) || leftB->isHidden())
         return;
     const QRect tabRect = tabList.at(index).rect;
     const int oldScrollOffset = scrollOffset;
     const bool horiz = !verticalTabs(shape);
     const int available = (horiz ? q->width() : q->height()) - extraWidth();
     const int start = horiz ? tabRect.left() : tabRect.top();
     const int end = horiz ? tabRect.right() : tabRect.bottom();
     if (start < scrollOffset) // too far left
         scrollOffset = start - (index ? 8 : 0);
     else if (end > scrollOffset + available) // too far right
         scrollOffset = end - available + 1;
     leftB->setEnabled(scrollOffset > 0);
     const int last = horiz ? tabList.last().rect.right() : tabList.last().rect.bottom();
     rightB->setEnabled(last - scrollOffset >= available);
     if (oldScrollOffset != scrollOffset) {
         q->update();
         layoutWidgets();
     }
 }
minimumTabSizeHint()
QSize QTabBarPrivate::minimumTabSizeHint (int index)
Definition at line 1373 of file qtabbar.cpp.
Referenced by layoutTabs(), and validIndex().
 {
     Q_Q(QTabBar);
     // ### Qt 5: make this a protected virtual function in QTabBar
     Tab &tab = tabList[index];
     QString oldText = tab.text;
     tab.text = computeElidedText(elideMode, oldText);
     QSize size = q->tabSizeHint(index);
     tab.text = oldText;
     return size;
 }
moveTab()
void QTabBarPrivate::moveTab (int index, int offset)
em>Reimplemented Function
Definition at line 1768 of file qtabbar.cpp.
Referenced by QTabBarPrivate::Tab::TabBarAnimation::updateCurrentValue().
moveTabFinished()
void QTabBarPrivate::moveTabFinished (int index)
em>Reimplemented Function
Definition at line 1936 of file qtabbar.cpp.
Referenced by refresh(), QTabBarPrivate::Tab::startAnimation(), and QTabBarPrivate::Tab::TabBarAnimation::updateState().
refresh()
void QTabBarPrivate::refresh ()
Definition at line 720 of file qtabbar.cpp.
 {
     Q_Q(QTabBar);
     // be safe in case a subclass is also handling move with the tabs
     if (pressedIndex != -1
         && movable
         && QApplication::mouseButtons() == Qt::NoButton) {
         moveTabFinished(pressedIndex);
         if (!validIndex(pressedIndex))
             pressedIndex = -1;
     }
     if (!q->isVisible()) {
         layoutDirty = true;
     } else {
         layoutTabs();
         makeVisible(currentIndex);
         q->update();
         q->updateGeometry();
     }
 }
setCurrentNextEnabledIndex()
void QTabBarPrivate::setCurrentNextEnabledIndex (int offset)
em>Reimplemented Function
Definition at line 2027 of file qtabbar.cpp.
Referenced by validIndex().
setupMovableTab()
void QTabBarPrivate::setupMovableTab ()
Definition at line 1896 of file qtabbar.cpp.
 {
     Q_Q(QTabBar);
     if (!movingTab)
         movingTab = new QWidget(q);
     int taboverlap = q->style()->pixelMetric(QStyle::PM_TabBarTabOverlap, 0 ,q);
     QRect grabRect = q->tabRect(pressedIndex);
     grabRect.adjust(-taboverlap, 0, taboverlap, 0);
     QPixmap grabImage(grabRect.size());
     grabImage.fill(Qt::transparent);
     QStylePainter p(&grabImage, q);
     p.initFrom(q);
     QStyleOptionTabV3 tab;
     q->initStyleOption(&tab, pressedIndex);
     tab.rect.moveTopLeft(QPoint(taboverlap, 0));
     p.drawControl(QStyle::CE_TabBarTab, tab);
     p.end();
     QPalette pal;
     pal.setBrush(QPalette::All, QPalette::Window, grabImage);
     movingTab->setPalette(pal);
     movingTab->setGeometry(grabRect);
     movingTab->setAutoFillBackground(true);
     movingTab->raise();
     // Re-arrange widget order to avoid overlaps
     if (tabList[pressedIndex].leftWidget)
         tabList[pressedIndex].leftWidget->raise();
     if (tabList[pressedIndex].rightWidget)
         tabList[pressedIndex].rightWidget->raise();
     if (leftB)
         leftB->raise();
     if (rightB)
         rightB->raise();
     movingTab->setVisible(true);
 }
slide()
void QTabBarPrivate::slide (int from, int to)
Definition at line 1750 of file qtabbar.cpp.
 {
     Q_Q(QTabBar);
     if (from == to
             || !validIndex(from)
             || !validIndex(to))
         return;
     bool vertical = verticalTabs(shape);
     int preLocation = vertical ? q->tabRect(from).y() : q->tabRect(from).x();
     q->setUpdatesEnabled(false);
     q->moveTab(from, to);
     q->setUpdatesEnabled(true);
     int postLocation = vertical ? q->tabRect(to).y() : q->tabRect(to).x();
     int length = postLocation - preLocation;
     tabList[to].dragOffset -= length;
     tabList[to].startAnimation(this, ANIMATION_DURATION);
 }
updateMacBorderMetrics()
void QTabBarPrivate::updateMacBorderMetrics ()
Definition at line 85 of file qtabbar.cpp.
 {
 #if (defined Q_WS_MAC) && (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
     if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
         Q_Q(QTabBar);
         ::HIContentBorderMetrics metrics;
         // TODO: get metrics to preserve the bottom value
         // TODO: test tab bar position
         OSWindowRef window = qt_mac_window_for(q);
         // push base line separator down to the client are so we can paint over it (Carbon)
         metrics.top = (documentMode && q->isVisible()) ? 1 : 0;
         metrics.bottom = 0;
         metrics.left = 0;
         metrics.right = 0;
         qt_mac_updateContentBorderMetricts(window, metrics);
 #if QT_MAC_USE_COCOA
         // In Cocoa we need to keep track of the drawRect method.
         // If documentMode is enabled we need to change it, unless
         // a toolbar is present.
         // Notice that all the information is kept in the window,
         // that's why we get the private widget for it instead of
         // the private widget for this widget.
         QWidgetPrivate *privateWidget = qt_widget_private(q->window());
         if(privateWidget)
             privateWidget->changeMethods = documentMode;
         // Since in Cocoa there is no simple way to remove the baseline, so we just ask the
         // top level to do the magic for us.
         privateWidget->syncUnifiedMode();
 #endif // QT_MAC_USE_COCOA
     }
 #endif
 }
validIndex()
bool QTabBarPrivate::validIndex (int index) const inline
Definition at line 165 of file qtabbar_p.h.
Referenced by at(), makeVisible(), and refresh().
 { return index >= 0 && index < tabList.count(); }
Properties
closeButtonOnTabs
bool QTabBarPrivate::closeButtonOnTabs
Definition at line 194 of file qtabbar_p.h.
currentIndex
int QTabBarPrivate::currentIndex
Definition at line 86 of file qtabbar_p.h.
Referenced by indexAtPos(), and refresh().
documentMode
bool QTabBarPrivate::documentMode
Definition at line 201 of file qtabbar_p.h.
Referenced by updateMacBorderMetrics().
dragInProgress
bool QTabBarPrivate::dragInProgress
Definition at line 200 of file qtabbar_p.h.
dragStartPosition
QPoint QTabBarPrivate::dragStartPosition
Definition at line 197 of file qtabbar_p.h.
drawBase
bool QTabBarPrivate::drawBase
Definition at line 90 of file qtabbar_p.h.
elideMode
Qt::TextElideMode QTabBarPrivate::elideMode
Definition at line 188 of file qtabbar_p.h.
Referenced by init().
elideModeSetByUser
bool QTabBarPrivate::elideModeSetByUser
Definition at line 189 of file qtabbar_p.h.
expanding
bool QTabBarPrivate::expanding
Definition at line 193 of file qtabbar_p.h.
Referenced by layoutTabs().
hoverRect
QRect QTabBarPrivate::hoverRect
Definition at line 177 of file qtabbar_p.h.
iconSize
QSize QTabBarPrivate::iconSize
Definition at line 187 of file qtabbar_p.h.
Referenced by QTabBar::initStyleOption().
layoutDirty
bool QTabBarPrivate::layoutDirty
Definition at line 89 of file qtabbar_p.h.
Referenced by layoutTabs(), and refresh().
leftB
QToolButton* QTabBarPrivate::leftB
Definition at line 171 of file qtabbar_p.h.
Referenced by _q_scrollTabs(), QAccessibleTabBar::button(), init(), layoutTabs(), and makeVisible().
movable
bool QTabBarPrivate::movable
Definition at line 199 of file qtabbar_p.h.
Referenced by refresh().
movingTab
QWidget* QTabBarPrivate::movingTab
Definition at line 203 of file qtabbar_p.h.
paintWithOffsets
bool QTabBarPrivate::paintWithOffsets
Definition at line 198 of file qtabbar_p.h.
Referenced by layoutTab().
pressedIndex
int QTabBarPrivate::pressedIndex
Definition at line 87 of file qtabbar_p.h.
Referenced by layoutTab(), and refresh().
previousPressedIndex
int QTabBarPrivate::previousPressedIndex
Definition at line 205 of file qtabbar_p.h.
rightB
QToolButton* QTabBarPrivate::rightB
Definition at line 170 of file qtabbar_p.h.
Referenced by _q_scrollTabs(), QAccessibleTabBar::button(), init(), layoutTabs(), and makeVisible().
scrollOffset
int QTabBarPrivate::scrollOffset
Definition at line 91 of file qtabbar_p.h.
Referenced by _q_scrollTabs(), layoutTabs(), and makeVisible().
selectionBehaviorOnRemove
QTabBar::SelectionBehavior QTabBarPrivate::selectionBehaviorOnRemove
Definition at line 195 of file qtabbar_p.h.
shape
QTabBar::Shape QTabBarPrivate::shape
Definition at line 88 of file qtabbar_p.h.
Referenced by _q_scrollTabs(), layoutTab(), layoutTabs(), and makeVisible().
tabList
QList<Tab> QTabBarPrivate::tabList
Definition at line 153 of file qtabbar_p.h.
Referenced by _q_closeTab(), _q_scrollTabs(), at(), indexAtPos(), layoutTab(), layoutTabs(), makeVisible(), QTabBarPrivate::Tab::startAnimation(), QTabBarPrivate::Tab::TabBarAnimation::updateCurrentValue(), and QTabBarPrivate::Tab::TabBarAnimation::updateState().
useScrollButtons
bool QTabBarPrivate::useScrollButtons
Definition at line 190 of file qtabbar_p.h.
Referenced by init(), and layoutTabs().
useScrollButtonsSetByUser
bool QTabBarPrivate::useScrollButtonsSetByUser
Definition at line 191 of file qtabbar_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qtabbar_p.h
/src/gui/widgets/qtabbar.cpp