Qt 4.8: QDeclarativeTimer Class Reference
QDeclarativeTimer Class Reference
#include <qdeclarativetimer_p.h>
Public Slots
void restart ()
void start ()
void stop ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void intervalChanged ()
void repeatChanged ()
void runningChanged ()
void triggered ()
void triggeredOnStartChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int interval () const
bool isRepeating () const
bool isRunning () const
QDeclarativeTimer (QObject *parent=0)
void setInterval (int interval)
void setRepeating (bool repeating)
void setRunning (bool running)
void setTriggeredOnStart (bool triggeredOnStart)
bool triggeredOnStart () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void finished ()
void ticked ()
This handler is called when the Timer is triggered.
Private Functions
void update ()
Properties
int interval
QObject * parent
bool repeat
bool running
bool triggeredOnStart
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 59 of file qdeclarativetimer_p.h.
Constructors and Destructors
QDeclarativeTimer()
QDeclarativeTimer::QDeclarativeTimer (QObject * parent = 0)
Definition at line 113 of file qdeclarativetimer.cpp.
     : QObject(*(new QDeclarativeTimerPrivate), parent)
 {
     Q_D(QDeclarativeTimer);
     connect(&d->pause, SIGNAL(currentLoopChanged(int)), this, SLOT(ticked()));
     connect(&d->pause, SIGNAL(finished()), this, SLOT(finished()));
     d->pause.setLoopCount(1);
     d->pause.setDuration(d->interval);
 }
Functions
classBegin()
void QDeclarativeTimer::classBegin () protected virtual
Invoked after class creation, but before any properties have been set.
Implements QDeclarativeParserStatus.
Definition at line 311 of file qdeclarativetimer.cpp.
 {
     Q_D(QDeclarativeTimer);
     d->classBegun = true;
 }
componentComplete()
void QDeclarativeTimer::componentComplete () protected virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 317 of file qdeclarativetimer.cpp.
 {
     Q_D(QDeclarativeTimer);
     d->componentComplete = true;
     update();
 }
finished
void QDeclarativeTimer::finished () private slot
Definition at line 340 of file qdeclarativetimer.cpp.
Referenced by QDeclarativeTimer().
 {
     Q_D(QDeclarativeTimer);
     if (d->repeating || !d->running)
         return;
     emit triggered();
     d->running = false;
     d->firstTick = false;
     emit runningChanged();
 }
interval()
int QDeclarativeTimer::interval () const
Referenced by setInterval().
intervalChanged
void QDeclarativeTimer::intervalChanged () signal
Referenced by setInterval().
isRepeating()
bool QDeclarativeTimer::isRepeating () const
Definition at line 194 of file qdeclarativetimer.cpp.
 {
     Q_D(const QDeclarativeTimer);
     return d->repeating;
 }
isRunning()
bool QDeclarativeTimer::isRunning () const
Definition at line 163 of file qdeclarativetimer.cpp.
 {
     Q_D(const QDeclarativeTimer);
     return d->running;
 }
repeatChanged
void QDeclarativeTimer::repeatChanged () signal
Referenced by setRepeating().
restart
void QDeclarativeTimer::restart () slot
Definition at line 287 of file qdeclarativetimer.cpp.
 {
     setRunning(false);
     setRunning(true);
 }
runningChanged
void QDeclarativeTimer::runningChanged () signal
Referenced by finished(), and setRunning().
setInterval()
void QDeclarativeTimer::setInterval (int interval)
Definition at line 133 of file qdeclarativetimer.cpp.
 {
     Q_D(QDeclarativeTimer);
     if (interval != d->interval) {
         d->interval = interval;
         update();
         emit intervalChanged();
     }
 }
setRepeating()
void QDeclarativeTimer::setRepeating (bool repeating)
Definition at line 200 of file qdeclarativetimer.cpp.
 {
     Q_D(QDeclarativeTimer);
     if (repeating != d->repeating) {
         d->repeating = repeating;
         update();
         emit repeatChanged();
     }
 }
setRunning()
void QDeclarativeTimer::setRunning (bool running)
Definition at line 169 of file qdeclarativetimer.cpp.
Referenced by restart(), start(), and stop().
 {
     Q_D(QDeclarativeTimer);
     if (d->running != running) {
         d->running = running;
         d->firstTick = true;
         emit runningChanged();
         update();
     }
 }
setTriggeredOnStart()
void QDeclarativeTimer::setTriggeredOnStart (bool triggeredOnStart)
Definition at line 236 of file qdeclarativetimer.cpp.
 {
     Q_D(QDeclarativeTimer);
     if (d->triggeredOnStart != triggeredOnStart) {
         d->triggeredOnStart = triggeredOnStart;
         update();
         emit triggeredOnStartChanged();
     }
 }
start
void QDeclarativeTimer::start () slot
Definition at line 256 of file qdeclarativetimer.cpp.
 {
     setRunning(true);
 }
stop
void QDeclarativeTimer::stop () slot
Definition at line 271 of file qdeclarativetimer.cpp.
 {
     setRunning(false);
 }
ticked
void QDeclarativeTimer::ticked () private slot
This handler is called when the Timer is triggered.
Timer::onTriggered()
Definition at line 332 of file qdeclarativetimer.cpp.
Referenced by QDeclarativeTimer().
 {
     Q_D(QDeclarativeTimer);
     if (d->running && (d->pause.currentTime() > 0 || (d->triggeredOnStart && d->firstTick)))
         emit triggered();
     d->firstTick = false;
 }
triggered
void QDeclarativeTimer::triggered () signal
Referenced by finished(), and ticked().
triggeredOnStart()
bool QDeclarativeTimer::triggeredOnStart () const
Referenced by setRepeating(), and setTriggeredOnStart().
triggeredOnStartChanged
void QDeclarativeTimer::triggeredOnStartChanged () signal
Referenced by setTriggeredOnStart().
update()
void QDeclarativeTimer::update () private
Definition at line 293 of file qdeclarativetimer.cpp.
Referenced by componentComplete(), setInterval(), setRepeating(), setRunning(), and setTriggeredOnStart().
 {
     Q_D(QDeclarativeTimer);
     if (d->classBegun && !d->componentComplete)
         return;
     d->pause.stop();
     if (d->running) {
         d->pause.setCurrentTime(0);
         d->pause.setLoopCount(d->repeating ? -1 : 1);
         d->pause.setDuration(d->interval);
         d->pause.start();
         if (d->triggeredOnStart && d->firstTick) {
             QCoreApplication::removePostedEvents(this, QEvent::MetaCall);
             QMetaObject::invokeMethod(this, "ticked", Qt::QueuedConnection);
         }
     }
 }
Properties
interval
int QDeclarativeTimer::interval private
Definition at line 64 of file qdeclarativetimer_p.h.
parent
QObject* QDeclarativeTimer::parent private
Definition at line 68 of file qdeclarativetimer_p.h.
repeat
bool QDeclarativeTimer::repeat private
Definition at line 66 of file qdeclarativetimer_p.h.
running
bool QDeclarativeTimer::running private
Definition at line 65 of file qdeclarativetimer_p.h.
Referenced by setRunning().
triggeredOnStart
bool QDeclarativeTimer::triggeredOnStart private
Definition at line 67 of file qdeclarativetimer_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativetimer_p.h
/src/declarative/util/qdeclarativetimer.cpp