Qt 4.8: QNetworkCookie Class Reference
QNetworkCookie Class Reference
The QNetworkCookie class holds one network cookie.
#include <qnetworkcookie.h>
Public Types
enum RawForm { NameAndValueOnly, Full }
This enum is used with the toRawForm() function to declare which form of a cookie shall be returned.
Public Functions
QString domain () const
Returns the domain this cookie is associated with.
QDateTime expirationDate () const
Returns the expiration date for this cookie.
bool isHttpOnly () const
Returns true if the "HttpOnly" flag is enabled for this cookie.
bool isSecure () const
Returns true if the "secure" option was specified in the cookie string, false otherwise.
bool isSessionCookie () const
Returns true if this cookie is a session cookie.
QByteArray name () const
Returns the name of this cookie.
bool operator!= (const QNetworkCookie &other) const
Returns true if this cookie is not equal to other.
QNetworkCookie & operator= (const QNetworkCookie &other)
Copies the contents of the QNetworkCookie object other to this object.
bool operator== (const QNetworkCookie &other) const
Returns true if this cookie is equal to other.
QString path () const
Returns the path associated with this cookie.
QNetworkCookie (const QByteArray &name=QByteArray(), const QByteArray &value=QByteArray())
Create a new QNetworkCookie object, initializing the cookie name to name and its value to value.
QNetworkCookie (const QNetworkCookie &other)
Creates a new QNetworkCookie object by copying the contents of other.
void setDomain (const QString &domain)
Sets the domain associated with this cookie to be domain.
void setExpirationDate (const QDateTime &date)
Sets the expiration date of this cookie to date.
void setHttpOnly (bool enable)
Sets this cookie's "HttpOnly" flag to enable.
void setName (const QByteArray &cookieName)
Sets the name of this cookie to be cookieName.
void setPath (const QString &path)
Sets the path associated with this cookie to be path.
void setSecure (bool enable)
Sets the secure flag of this cookie to enable.
void setValue (const QByteArray &value)
Sets the value of this cookie to be value.
QByteArray toRawForm (RawForm form=Full) const
Returns the raw form of this QNetworkCookie.
QByteArray value () const
Returns this cookies value, as specified in the cookie string.
~QNetworkCookie ()
Destroys this QNetworkCookie object.
Static Public Functions
static QList< QNetworkCookie > parseCookies (const QByteArray &cookieString)
Parses the cookie string cookieString as received from a server response in the "Set-Cookie:" header.
Properties
QSharedDataPointer< QNetworkCookiePrivate > d
Friends
class QNetworkCookiePrivate
Detailed Description
The QNetworkCookie class holds one network cookie.
Since
4.4
Cookies are small bits of information that stateless protocols like HTTP use to maintain some persistent information across requests.
A cookie is set by a remote server when it replies to a request and it expects the same cookie to be sent back when further requests are sent.
QNetworkCookie holds one such cookie as received from the network. A cookie has a name and a value, but those are opaque to the application (that is, the information stored in them has no meaning to the application). A cookie has an associated path name and domain, which indicate when the cookie should be sent again to the server.
A cookie can also have an expiration date, indicating its validity. If the expiration date is not present, the cookie is considered a "session cookie" and should be discarded when the application exits (or when its concept of session is over).
QNetworkCookie provides a way of parsing a cookie from the HTTP header format using the QNetworkCookie::parseCookies() function. However, when received in a QNetworkReply, the cookie is already parsed.
This class implements cookies as described by the Netscape Cookie Specification{initial cookie specification by Netscape}, which is somewhat similar to the RFC 2109 specification, plus the Mitigating Cross-site Scripting With HTTP-only Cookies {"HttpOnly" extension}. The more recent RFC 2965 specification (which uses the Set-Cookie2 header) is not supported.
See also
QNetworkCookieJar, QNetworkRequest, QNetworkReply
Definition at line 62 of file qnetworkcookie.h.
Enumerations
RawForm
enum QNetworkCookie::RawForm
This enum is used with the toRawForm() function to declare which form of a cookie shall be returned.
NameAndValueOnly makes toRawForm() return only the "NAME=VALUE" part of the cookie, as suitable for sending back to a server in a client request's "Cookie:" header. Multiple cookies are separated by a semi-colon in the "Cookie:" header field.
Full makes toRawForm() return the full cookie contents, as suitable for sending to a client in a server's "Set-Cookie:" header.
Note that only the Full form of the cookie can be parsed back into its original contents.
See also
toRawForm(), parseCookies()
Enumerator
NameAndValueOnly
Full
Definition at line 65 of file qnetworkcookie.h.
                  {
         NameAndValueOnly,
         Full
     };
Constructors and Destructors
QNetworkCookie() [1/2]
QNetworkCookie::QNetworkCookie (const QByteArray & name = QByteArray(), const QByteArray & value = QByteArray())
Create a new QNetworkCookie object, initializing the cookie name to name and its value to value.
A cookie is only valid if it has a name. However, the value is opaque to the application and being empty may have significance to the remote server.
Definition at line 109 of file qnetworkcookie.cpp.
     : d(new QNetworkCookiePrivate)
 {
     qRegisterMetaType<QNetworkCookie>();
     qRegisterMetaType<QList<QNetworkCookie> >();
     d->name = name;
     d->value = value;
 }
QNetworkCookie() [2/2]
QNetworkCookie::QNetworkCookie (const QNetworkCookie & other)
Creates a new QNetworkCookie object by copying the contents of other.
Definition at line 123 of file qnetworkcookie.cpp.
     : d(other.d)
 {
 }
~QNetworkCookie()
QNetworkCookie::~QNetworkCookie ()
Destroys this QNetworkCookie object.
Definition at line 131 of file qnetworkcookie.cpp.
 {
     // QSharedDataPointer auto deletes
     d = 0;
 }
Functions
domain()
QString QNetworkCookie::domain () const
Returns the domain this cookie is associated with.
This corresponds to the "domain" field of the cookie string.
Note that the domain here may start with a dot, which is not a valid hostname. However, it means this cookie matches all hostnames ending with that domain name.
See also
setDomain()
Definition at line 290 of file qnetworkcookie.cpp.
Referenced by QNetworkCookieJar::setCookiesFromUrl(), and setDomain().
 {
     return d->domain;
 }
expirationDate()
QDateTime QNetworkCookie::expirationDate () const
Returns the expiration date for this cookie.
If this cookie is a session cookie, the QDateTime returned will not be valid. If the date is in the past, this cookie has already expired and should not be sent again back to a remote server.
The expiration date corresponds to the parameters of the "expires" entry in the cookie string.
See also
isSessionCookie(), setExpirationDate()
Definition at line 263 of file qnetworkcookie.cpp.
Referenced by QNetworkCookieJar::setCookiesFromUrl().
 {
     return d->expirationDate;
 }
isHttpOnly()
bool QNetworkCookie::isHttpOnly () const
Returns true if the "HttpOnly" flag is enabled for this cookie.
Since
4.5
A cookie that is "HttpOnly" is only set and retrieved by the network requests and replies; i.e., the HTTP protocol. It is not accessible from scripts running on browsers.
See also
isSecure()
Definition at line 221 of file qnetworkcookie.cpp.
Referenced by toRawForm().
 {
     return d->httpOnly;
 }
isSecure()
bool QNetworkCookie::isSecure () const
Returns true if the "secure" option was specified in the cookie string, false otherwise.
Secure cookies may contain private information and should not be resent over unencrypted connections.
See also
setSecure()
Definition at line 189 of file qnetworkcookie.cpp.
Referenced by toRawForm().
 {
     return d->secure;
 }
isSessionCookie()
bool QNetworkCookie::isSessionCookie () const
Returns true if this cookie is a session cookie.
A session cookie is a cookie which has no expiration date, which means it should be discarded when the application's concept of session is over (usually, when the application exits).
See also
expirationDate(), setExpirationDate()
Definition at line 247 of file qnetworkcookie.cpp.
Referenced by QNetworkCookieJar::setCookiesFromUrl(), and toRawForm().
 {
     return !d->expirationDate.isValid();
 }
name()
QByteArray QNetworkCookie::name () const
Returns the name of this cookie.
The only mandatory field of a cookie is its name, without which it is not considered valid.
See also
setName(), value()
Definition at line 332 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine(), QNetworkCookie(), and QNetworkCookieJar::setCookiesFromUrl().
 {
     return d->name;
 }
operator!=()
bool QNetworkCookie::operator!= (const QNetworkCookie & other) const inline
Returns true if this cookie is not equal to other.
See also
operator==()
Definition at line 75 of file qnetworkcookie.h.
     { return !(*this == other); }
operator=()
QNetworkCookie & QNetworkCookie::operator= (const QNetworkCookie & other)
Copies the contents of the QNetworkCookie object other to this object.
Definition at line 141 of file qnetworkcookie.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QNetworkCookie::operator== (const QNetworkCookie & other) const
Returns true if this cookie is equal to other.
This function only returns true if all fields of the cookie are the same.
However, in some contexts, two cookies of the same name could be considered equal.
See also
operator!=()
Definition at line 167 of file qnetworkcookie.cpp.
 {
     if (d == other.d)
         return true;
     return d->name == other.d->name &&
         d->value == other.d->value &&
         d->expirationDate.toUTC() == other.d->expirationDate.toUTC() &&
         d->domain == other.d->domain &&
         d->path == other.d->path &&
         d->secure == other.d->secure &&
         d->comment == other.d->comment;
 }
parseCookies()
QList< QNetworkCookie > QNetworkCookie::parseCookies (const QByteArray & cookieString) static
Parses the cookie string cookieString as received from a server response in the "Set-Cookie:" header.
If there's a parsing error, this function returns an empty list.
Since the HTTP header can set more than one cookie at the same time, this function returns a QList<QNetworkCookie>, one for each cookie that is parsed.
See also
toRawForm()
Definition at line 944 of file qnetworkcookie.cpp.
Referenced by parseCookieHeader(), and parseHeaderValue().
 {
     // cookieString can be a number of set-cookie header strings joined together
     // by \n, parse each line separately.
     QList<QNetworkCookie> cookies;
     QList<QByteArray> list = cookieString.split('\n');
     for (int a = 0; a < list.size(); a++)
         cookies += QNetworkCookiePrivate::parseSetCookieHeaderLine(list.at(a));
     return cookies;
 }
path()
QString QNetworkCookie::path () const
Returns the path associated with this cookie.
This corresponds to the "path" field of the cookie string.
See also
setPath()
Definition at line 311 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine(), QNetworkCookieJar::setCookiesFromUrl(), and setPath().
 {
     return d->path;
 }
setDomain()
void QNetworkCookie::setDomain (const QString & domain)
Sets the domain associated with this cookie to be domain.
See also
domain()
Definition at line 300 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine(), and QNetworkCookieJar::setCookiesFromUrl().
 {
     d->domain = domain;
 }
setExpirationDate()
void QNetworkCookie::setExpirationDate (const QDateTime & date)
Sets the expiration date of this cookie to date.
Setting an invalid expiration date to this cookie will mean it's a session cookie.
See also
isSessionCookie(), expirationDate()
Definition at line 275 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     d->expirationDate = date;
 }
setHttpOnly()
void QNetworkCookie::setHttpOnly (bool enable)
Sets this cookie's "HttpOnly" flag to enable.
Since
4.5
Definition at line 234 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     d->httpOnly = enable;
 }
setName()
void QNetworkCookie::setName (const QByteArray & cookieName)
Sets the name of this cookie to be cookieName.
Note that setting a cookie name to an empty QByteArray will make this cookie invalid.
See also
name(), value()
Definition at line 344 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     d->name = cookieName;
 }
setPath()
void QNetworkCookie::setPath (const QString & path)
Sets the path associated with this cookie to be path.
See also
path()
Definition at line 321 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine(), and QNetworkCookieJar::setCookiesFromUrl().
 {
     d->path = path;
 }
setSecure()
void QNetworkCookie::setSecure (bool enable)
Sets the secure flag of this cookie to enable.
Secure cookies may contain private information and should not be resent over unencrypted connections.
See also
isSecure()
Definition at line 202 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     d->secure = enable;
 }
setValue()
void QNetworkCookie::setValue (const QByteArray & value)
Sets the value of this cookie to be value.
See also
value(), name()
Definition at line 368 of file qnetworkcookie.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     d->value = value;
 }
toRawForm()
QByteArray QNetworkCookie::toRawForm (RawForm form = Full) const
Returns the raw form of this QNetworkCookie.
The QByteArray returned by this function is suitable for an HTTP header, either in a server response (the Set-Cookie header) or the client request (the Cookie header). You can choose from one of two formats, using form.
See also
parseCookies()
Definition at line 496 of file qnetworkcookie.cpp.
Referenced by headerValue(), and operator<<().
 {
     QByteArray result;
     if (d->name.isEmpty())
         return result;          // not a valid cookie
     result = d->name;
     result += '=';
     if ((d->value.contains(';') ||
         d->value.contains('"')) &&
         (!d->value.startsWith('"') &&
         !d->value.endsWith('"'))) {
         result += '"';
         QByteArray value = d->value;
         value.replace('"', "\\\"");
         result += value;
         result += '"';
     } else {
         result += d->value;
     }
     if (form == Full) {
         // same as above, but encoding everything back
         if (isSecure())
             result += "; secure";
         if (isHttpOnly())
             result += "; HttpOnly";
         if (!isSessionCookie()) {
             result += "; expires=";
             result += QLocale::c().toString(d->expirationDate.toUTC(),
                                             QLatin1String("ddd, dd-MMM-yyyy hh:mm:ss 'GMT")).toLatin1();
         }
         if (!d->domain.isEmpty()) {
             result += "; domain=";
             QString domainNoDot = d->domain;
             if (domainNoDot.startsWith(QLatin1Char('.'))) {
                 result += '.';
                 domainNoDot = domainNoDot.mid(1);
             }
             result += QUrl::toAce(domainNoDot);
         }
         if (!d->path.isEmpty()) {
             result += "; path=";
             result += QUrl::toPercentEncoding(d->path, "/");
         }
     }
     return result;
 }
value()
QByteArray QNetworkCookie::value () const
Returns this cookies value, as specified in the cookie string.
Note that a cookie is still valid if its value is empty.
Cookie name-value pairs are considered opaque to the application: that is, their values don't mean anything.
See also
setValue(), name()
Definition at line 358 of file qnetworkcookie.cpp.
Referenced by QNetworkCookie(), setValue(), and toRawForm().
 {
     return d->value;
 }
Friends and Related Functions
QNetworkCookiePrivate
friend class QNetworkCookiePrivate friend
Definition at line 105 of file qnetworkcookie.h.
Properties
d
QSharedDataPointer<QNetworkCookiePrivate> QNetworkCookie::d private
Definition at line 104 of file qnetworkcookie.h.
Referenced by domain(), expirationDate(), isHttpOnly(), isSecure(), isSessionCookie(), name(), operator=(), operator==(), parseDateString(), path(), QNetworkCookie(), setDomain(), setExpirationDate(), setHttpOnly(), setName(), setPath(), setSecure(), setValue(), toRawForm(), value(), and ~QNetworkCookie().
The documentation for this class was generated from the following files:
/src/network/access/qnetworkcookie.h
/src/network/access/qnetworkcookie.cpp