Qt 4.8: QFileSystemMetaData Class Reference
QFileSystemMetaData Class Reference
#include <qfilesystemmetadata_p.h>
Public Types
enum MetaDataFlag {
OtherReadPermission = 0x00000004, OtherWritePermission = 0x00000002, OtherExecutePermission = 0x00000001, GroupReadPermission = 0x00000040,
GroupWritePermission = 0x00000020, GroupExecutePermission = 0x00000010, UserReadPermission = 0x00000400, UserWritePermission = 0x00000200,
UserExecutePermission = 0x00000100, OwnerReadPermission = 0x00004000, OwnerWritePermission = 0x00002000, OwnerExecutePermission = 0x00001000,
OtherPermissions = OtherReadPermission | OtherWritePermission | OtherExecutePermission, GroupPermissions = GroupReadPermission | GroupWritePermission | GroupExecutePermission, UserPermissions = UserReadPermission | UserWritePermission | UserExecutePermission, OwnerPermissions = OwnerReadPermission | OwnerWritePermission | OwnerExecutePermission,
ReadPermissions = OtherReadPermission | GroupReadPermission | UserReadPermission | OwnerReadPermission, WritePermissions = OtherWritePermission | GroupWritePermission | UserWritePermission | OwnerWritePermission, ExecutePermissions = OtherExecutePermission | GroupExecutePermission | UserExecutePermission | OwnerExecutePermission, Permissions = OtherPermissions | GroupPermissions | UserPermissions | OwnerPermissions,
LinkType = 0x00010000, FileType = 0x00020000, DirectoryType = 0x00040000, BundleType = 0x00080000,
AliasType = 0x08000000, WinLnkType = 0x08000000, SequentialType = 0x00800000, LegacyLinkType = LinkType | AliasType | WinLnkType,
Type = LinkType | FileType | DirectoryType | BundleType | SequentialType | AliasType, HiddenAttribute = 0x00100000, SizeAttribute = 0x00200000, ExistsAttribute = 0x00400000,
Attributes = HiddenAttribute | SizeAttribute | ExistsAttribute, CreationTime = 0x01000000, ModificationTime = 0x02000000, AccessTime = 0x04000000,
Times = CreationTime | ModificationTime | AccessTime, UserId = 0x10000000, GroupId = 0x20000000, OwnerIds = UserId | GroupId,
PosixStatFlags, SymbianTEntryFlags, WinStatFlags, AllMetaDataFlags = 0xFFFFFFFF
}
Public Functions
QDateTime accessTime () const
void clear ()
void clearFlags (MetaDataFlags flags=AllMetaDataFlags)
QDateTime creationTime () const
bool exists () const
QDateTime fileTime (QAbstractFileEngine::FileTime time) const
void fillFromDirEnt (const QT_DIRENT &statBuffer)
void fillFromFileAttribute (DWORD fileAttribute, bool isDriveRoot=false)
void fillFromFindData (WIN32_FIND_DATA &findData, bool setLinkType=false, bool isDriveRoot=false)
void fillFromFindInfo (BY_HANDLE_FILE_INFORMATION &fileInfo)
void fillFromStatBuf (const QT_STATBUF &statBuffer)
uint groupId () const
bool hasFlags (MetaDataFlags flags) const
bool isAlias () const
bool isBundle () const
bool isDirectory () const
bool isFile () const
bool isHidden () const
bool isLegacyLink () const
bool isLink () const
bool isLnkFile () const
bool isSequential () const
MetaDataFlags missingFlags (MetaDataFlags flags)
QDateTime modificationTime () const
uint ownerId (QAbstractFileEngine::FileOwner owner) const
QFile::Permissions permissions () const
QFileSystemMetaData ()
qint64 size () const
uint userId () const
Properties
FILETIME creationTime_
MetaDataFlags entryFlags
DWORD fileAttribute_
MetaDataFlags knownFlagsMask
FILETIME lastAccessTime_
FILETIME lastWriteTime_
qint64 size_
Friends
class QFileSystemEngine
Detailed Description
Definition at line 75 of file qfilesystemmetadata_p.h.
Enumerations
MetaDataFlag
enum QFileSystemMetaData::MetaDataFlag
Enumerator
OtherReadPermission
OtherWritePermission
OtherExecutePermission
GroupReadPermission
GroupWritePermission
GroupExecutePermission
UserReadPermission
UserWritePermission
UserExecutePermission
OwnerReadPermission
OwnerWritePermission
OwnerExecutePermission
OtherPermissions
GroupPermissions
UserPermissions
OwnerPermissions
ReadPermissions
WritePermissions
ExecutePermissions
Permissions
LinkType
FileType
DirectoryType
BundleType
AliasType
WinLnkType
SequentialType
LegacyLinkType
Type
HiddenAttribute
SizeAttribute
ExistsAttribute
Attributes
CreationTime
ModificationTime
AccessTime
Times
UserId
GroupId
OwnerIds
PosixStatFlags
SymbianTEntryFlags
WinStatFlags
AllMetaDataFlags
Definition at line 83 of file qfilesystemmetadata_p.h.
                       {
         // Permissions, overlaps with QFile::Permissions
         OtherReadPermission = 0x00000004,   OtherWritePermission = 0x00000002,  OtherExecutePermission = 0x00000001,
         GroupReadPermission = 0x00000040,   GroupWritePermission = 0x00000020,  GroupExecutePermission = 0x00000010,
         UserReadPermission  = 0x00000400,   UserWritePermission  = 0x00000200,  UserExecutePermission  = 0x00000100,
         OwnerReadPermission = 0x00004000,   OwnerWritePermission = 0x00002000,  OwnerExecutePermission = 0x00001000,
         OtherPermissions    = OtherReadPermission | OtherWritePermission | OtherExecutePermission,
         GroupPermissions    = GroupReadPermission | GroupWritePermission | GroupExecutePermission,
         UserPermissions     = UserReadPermission  | UserWritePermission  | UserExecutePermission,
         OwnerPermissions    = OwnerReadPermission | OwnerWritePermission | OwnerExecutePermission,
         ReadPermissions     = OtherReadPermission | GroupReadPermission | UserReadPermission | OwnerReadPermission,
         WritePermissions    = OtherWritePermission | GroupWritePermission | UserWritePermission | OwnerWritePermission,
         ExecutePermissions  = OtherExecutePermission | GroupExecutePermission | UserExecutePermission | OwnerExecutePermission,
         Permissions         = OtherPermissions | GroupPermissions | UserPermissions | OwnerPermissions,
         // Type
 #ifdef Q_OS_SYMBIAN
         LinkType            = 0,
 #else
         LinkType            = 0x00010000,
 #endif
         FileType            = 0x00020000,
         DirectoryType       = 0x00040000,
 #if !defined(QWS) && !defined(Q_WS_QPA) && defined(Q_OS_MAC)
         BundleType          = 0x00080000,
         AliasType           = 0x08000000,
 #else
         BundleType          =        0x0,
         AliasType           =        0x0,
 #endif
 #if defined(Q_OS_WIN)
         WinLnkType          = 0x08000000,   // Note: Uses the same position for AliasType on Mac
 #else
         WinLnkType          =        0x0,
 #endif
         SequentialType      = 0x00800000,   // Note: overlaps with QAbstractFileEngine::RootFlag
         LegacyLinkType      = LinkType | AliasType | WinLnkType,
         Type                = LinkType | FileType | DirectoryType | BundleType | SequentialType | AliasType,
         // Attributes
         HiddenAttribute     = 0x00100000,
         SizeAttribute       = 0x00200000,   // Note: overlaps with QAbstractFileEngine::LocalDiskFlag
         ExistsAttribute     = 0x00400000,
         Attributes          = HiddenAttribute | SizeAttribute | ExistsAttribute,
         // Times
         CreationTime        = 0x01000000,   // Note: overlaps with QAbstractFileEngine::Refresh
         ModificationTime    = 0x02000000,
         AccessTime          = 0x04000000,
         Times               = CreationTime | ModificationTime | AccessTime,
         // Owner IDs
         UserId              = 0x10000000,
         GroupId             = 0x20000000,
         OwnerIds            = UserId | GroupId,
         PosixStatFlags      = QFileSystemMetaData::OtherPermissions
                             | QFileSystemMetaData::GroupPermissions
                             | QFileSystemMetaData::OwnerPermissions
                             | QFileSystemMetaData::FileType
                             | QFileSystemMetaData::DirectoryType
                             | QFileSystemMetaData::SequentialType
                             | QFileSystemMetaData::SizeAttribute
                             | QFileSystemMetaData::Times
                             | QFileSystemMetaData::OwnerIds,
         SymbianTEntryFlags  = QFileSystemMetaData::Permissions
                             | QFileSystemMetaData::FileType
                             | QFileSystemMetaData::DirectoryType
                             | QFileSystemMetaData::SequentialType
                             | QFileSystemMetaData::Attributes
                             | QFileSystemMetaData::Times,
 #if defined(Q_OS_WIN)
         WinStatFlags        = QFileSystemMetaData::FileType
                             | QFileSystemMetaData::DirectoryType
                             | QFileSystemMetaData::HiddenAttribute
                             | QFileSystemMetaData::ExistsAttribute
                             | QFileSystemMetaData::SizeAttribute
                             | QFileSystemMetaData::Times,
 #endif
         AllMetaDataFlags    = 0xFFFFFFFF
     };
Constructors and Destructors
QFileSystemMetaData()
QFileSystemMetaData::QFileSystemMetaData () inline
Definition at line 78 of file qfilesystemmetadata_p.h.
         : knownFlagsMask(0)
     {
     }
Functions
accessTime()
QDateTime QFileSystemMetaData::accessTime () const inline
Definition at line 1249 of file qfilesystemengine_win.cpp.
Referenced by fileTime(), ownerId(), and permissions().
 {
     return fileTimeToQDateTime(&lastAccessTime_);
 }
clear()
void QFileSystemMetaData::clear () inline
Definition at line 187 of file qfilesystemmetadata_p.h.
Referenced by _q_checkEntry(), QFileInfoPrivate::clear(), QDir::refresh(), QFileSystemEngine::resolveEntryAndCreateLegacyEngine(), and QDirPrivate::setPath().
     {
         knownFlagsMask = 0;
     }
clearFlags()
void QFileSystemMetaData::clearFlags (MetaDataFlags flags = AllMetaDataFlags) inline
Definition at line 192 of file qfilesystemmetadata_p.h.
Referenced by QFSFileEnginePrivate::longFileName(), and openModeToFopenMode().
     {
         knownFlagsMask &= ~flags;
     }
creationTime()
QDateTime QFileSystemMetaData::creationTime () const inline
Definition at line 1241 of file qfilesystemengine_win.cpp.
Referenced by fileTime(), ownerId(), and permissions().
 {
     return fileTimeToQDateTime(&creationTime_);
 }
exists()
bool QFileSystemMetaData::exists () const inline
Definition at line 197 of file qfilesystemmetadata_p.h.
Referenced by _q_checkEntry(), QFileSystemEngine::clearWinStatData(), QFSFileEnginePrivate::doStat(), QDirPrivate::exists(), isDirPath(), and QFSFileEnginePrivate::longFileName().
 { return (entryFlags & ExistsAttribute); }
fileTime()
QDateTime QFileSystemMetaData::fileTime (QAbstractFileEngine::FileTime time) const inline
Definition at line 278 of file qfilesystemmetadata_p.h.
Referenced by ownerId(), and permissions().
 {
     switch (time) {
     case QAbstractFileEngine::ModificationTime:
         return modificationTime();
     case QAbstractFileEngine::AccessTime:
         return accessTime();
     case QAbstractFileEngine::CreationTime:
         return creationTime();
     }
     return QDateTime();
 }
fillFromDirEnt()
void QFileSystemMetaData::fillFromDirEnt (const QT_DIRENT & statBuffer)
Definition at line 309 of file qfilesystemengine.cpp.
Referenced by QFileSystemIterator::advance(), and permissions().
 {
 #if defined(Q_OS_QNX)
     entryFlags = 0;
     knownFlagsMask = 0;
     for (dirent_extra *extra = _DEXTRA_FIRST(&entry); _DEXTRA_VALID(extra, &entry);
          extra = _DEXTRA_NEXT(extra)) {
         if (extra->d_type == _DTYPE_STAT || extra->d_type == _DTYPE_LSTAT) {
             const struct dirent_extra_stat * const extra_stat =
                     reinterpret_cast<struct dirent_extra_stat *>(extra);
             // Remember whether this was a link or not, this saves an lstat() call later.
             if (extra->d_type == _DTYPE_LSTAT) {
                 knownFlagsMask |= QFileSystemMetaData::LinkType;
                 if (S_ISLNK(extra_stat->d_stat.st_mode))
                     entryFlags |= QFileSystemMetaData::LinkType;
             }
             // For symlinks, the extra type _DTYPE_LSTAT doesn't work for filling out the meta data,
             // as we need the stat() information there, not the lstat() information.
             // In this case, don't use the extra information.
             // Unfortunately, readdir() never seems to return extra info of type _DTYPE_STAT, so for
             // symlinks, we always incur the cost of an extra stat() call later.
             if (S_ISLNK(extra_stat->d_stat.st_mode) && extra->d_type == _DTYPE_LSTAT)
                 continue;
 #if defined(QT_USE_XOPEN_LFS_EXTENSIONS) && defined(QT_LARGEFILE_SUPPORT)
             // Even with large file support, d_stat is always of type struct stat, not struct stat64,
             // so it needs to be converted
             struct stat64 statBuf;
             fillStat64fromStat32(&statBuf, extra_stat->d_stat);
             fillFromStatBuf(statBuf);
 #else
             fillFromStatBuf(extra_stat->d_stat);
 #endif
             knownFlagsMask |= QFileSystemMetaData::PosixStatFlags;
             if (!S_ISLNK(extra_stat->d_stat.st_mode)) {
                 knownFlagsMask |= QFileSystemMetaData::ExistsAttribute;
                 entryFlags |= QFileSystemMetaData::ExistsAttribute;
             }
         }
     }
 #elif defined(_DIRENT_HAVE_D_TYPE) || defined(Q_OS_BSD4) || defined(Q_OS_SYMBIAN)
     // BSD4 includes Mac OS X
     // ### This will clear all entry flags and knownFlagsMask
     switch (entry.d_type)
     {
     case DT_DIR:
         knownFlagsMask = QFileSystemMetaData::LinkType
             | QFileSystemMetaData::FileType
             | QFileSystemMetaData::DirectoryType
             | QFileSystemMetaData::SequentialType
             | QFileSystemMetaData::ExistsAttribute;
         entryFlags = QFileSystemMetaData::DirectoryType
             | QFileSystemMetaData::ExistsAttribute;
         break;
     case DT_BLK:
     case DT_CHR:
     case DT_FIFO:
     case DT_SOCK:
         // ### System attribute
         knownFlagsMask = QFileSystemMetaData::LinkType
             | QFileSystemMetaData::FileType
             | QFileSystemMetaData::DirectoryType
             | QFileSystemMetaData::BundleType
             | QFileSystemMetaData::AliasType
             | QFileSystemMetaData::SequentialType
             | QFileSystemMetaData::ExistsAttribute;
         entryFlags = QFileSystemMetaData::SequentialType
             | QFileSystemMetaData::ExistsAttribute;
         break;
     case DT_LNK:
         knownFlagsMask = QFileSystemMetaData::LinkType;
         entryFlags = QFileSystemMetaData::LinkType;
         break;
     case DT_REG:
         knownFlagsMask = QFileSystemMetaData::LinkType
             | QFileSystemMetaData::FileType
             | QFileSystemMetaData::DirectoryType
             | QFileSystemMetaData::BundleType
             | QFileSystemMetaData::SequentialType
             | QFileSystemMetaData::ExistsAttribute;
         entryFlags = QFileSystemMetaData::FileType
             | QFileSystemMetaData::ExistsAttribute;
         break;
     case DT_UNKNOWN:
     default:
         clear();
     }
 #else
     Q_UNUSED(entry)
 #endif
 }
fillFromFileAttribute()
void QFileSystemMetaData::fillFromFileAttribute (DWORD fileAttribute, bool isDriveRoot = false) inline
Definition at line 342 of file qfilesystemmetadata_p.h.
Referenced by fillFromFindData(), fillFromFindInfo(), permissions(), and tryDriveUNCFallback().
 {
     fileAttribute_ = fileAttribute;
     // Ignore the hidden attribute for drives.
     if (!isDriveRoot && (fileAttribute_ & FILE_ATTRIBUTE_HIDDEN))
         entryFlags |= HiddenAttribute;
     entryFlags |= ((fileAttribute & FILE_ATTRIBUTE_DIRECTORY) ? DirectoryType: FileType);
     entryFlags |= ExistsAttribute;
     knownFlagsMask |= FileType | DirectoryType | HiddenAttribute | ExistsAttribute;
 }
fillFromFindData()
void QFileSystemMetaData::fillFromFindData (WIN32_FIND_DATA & findData, bool setLinkType = false, bool isDriveRoot = false) inline
Definition at line 353 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::fillMetaData(), permissions(), and tryFindFallback().
 {
     fillFromFileAttribute(findData.dwFileAttributes, isDriveRoot);
     creationTime_ = findData.ftCreationTime;
     lastAccessTime_ = findData.ftLastAccessTime;
     lastWriteTime_ = findData.ftLastWriteTime;
     if (fileAttribute_ & FILE_ATTRIBUTE_DIRECTORY) {
         size_ = 0;
     } else {
         size_ = findData.nFileSizeHigh;
         size_ <<= 32;
         size_ += findData.nFileSizeLow;
     }
     knownFlagsMask |=  Times | SizeAttribute;
     if (setLinkType) {
         knownFlagsMask |=  LinkType;
         entryFlags &= ~LinkType;
 #if !defined(Q_OS_WINCE)
         if ((fileAttribute_ & FILE_ATTRIBUTE_REPARSE_POINT)
             && findData.dwReserved0 == IO_REPARSE_TAG_SYMLINK) {
             entryFlags |= LinkType;
         }
 #endif
     }
 }
fillFromFindInfo()
void QFileSystemMetaData::fillFromFindInfo (BY_HANDLE_FILE_INFORMATION & fileInfo) inline
Definition at line 380 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::fillMetaData(), and permissions().
 {
     fillFromFileAttribute(fileInfo.dwFileAttributes);
     creationTime_ = fileInfo.ftCreationTime;
     lastAccessTime_ = fileInfo.ftLastAccessTime;
     lastWriteTime_ = fileInfo.ftLastWriteTime;
     if (fileAttribute_ & FILE_ATTRIBUTE_DIRECTORY) {
         size_ = 0;
     } else {
         size_ = fileInfo.nFileSizeHigh;
         size_ <<= 32;
         size_ += fileInfo.nFileSizeLow;
     }
     knownFlagsMask |=  Times | SizeAttribute;
 }
fillFromStatBuf()
void QFileSystemMetaData::fillFromStatBuf (const QT_STATBUF & statBuffer)
Definition at line 254 of file qfilesystemengine.cpp.
Referenced by QFileSystemEngine::fillMetaData(), and permissions().
 {
     // Permissions
     if (statBuffer.st_mode & S_IRUSR)
         entryFlags |= QFileSystemMetaData::OwnerReadPermission;
     if (statBuffer.st_mode & S_IWUSR)
         entryFlags |= QFileSystemMetaData::OwnerWritePermission;
     if (statBuffer.st_mode & S_IXUSR)
         entryFlags |= QFileSystemMetaData::OwnerExecutePermission;
     if (statBuffer.st_mode & S_IRGRP)
         entryFlags |= QFileSystemMetaData::GroupReadPermission;
     if (statBuffer.st_mode & S_IWGRP)
         entryFlags |= QFileSystemMetaData::GroupWritePermission;
     if (statBuffer.st_mode & S_IXGRP)
         entryFlags |= QFileSystemMetaData::GroupExecutePermission;
     if (statBuffer.st_mode & S_IROTH)
         entryFlags |= QFileSystemMetaData::OtherReadPermission;
     if (statBuffer.st_mode & S_IWOTH)
         entryFlags |= QFileSystemMetaData::OtherWritePermission;
     if (statBuffer.st_mode & S_IXOTH)
         entryFlags |= QFileSystemMetaData::OtherExecutePermission;
     // Type
     if ((statBuffer.st_mode & S_IFMT) == S_IFREG)
         entryFlags |= QFileSystemMetaData::FileType;
     else if ((statBuffer.st_mode & S_IFMT) == S_IFDIR)
         entryFlags |= QFileSystemMetaData::DirectoryType;
     else
         entryFlags |= QFileSystemMetaData::SequentialType;
     // Attributes
     entryFlags |= QFileSystemMetaData::ExistsAttribute;
     size_ = statBuffer.st_size;
 #if !defined(QWS) && !defined(Q_WS_QPA) && defined(Q_OS_MAC) \
         && MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5
     if (statBuffer.st_flags & UF_HIDDEN) {
         entryFlags |= QFileSystemMetaData::HiddenAttribute;
         knownFlagsMask |= QFileSystemMetaData::HiddenAttribute;
     }
 #endif
     // Times
 #ifdef Q_OS_SYMBIAN
     modificationTime_ = qt_symbian_time_t_To_TTime(statBuffer.st_mtime);
 #else
     creationTime_ = statBuffer.st_ctime ? statBuffer.st_ctime : statBuffer.st_mtime;
     modificationTime_ = statBuffer.st_mtime;
     accessTime_ = statBuffer.st_atime;
     userId_ = statBuffer.st_uid;
     groupId_ = statBuffer.st_gid;
 #endif
 }
groupId()
uint QFileSystemMetaData::groupId () const inline
Definition at line 301 of file qfilesystemmetadata_p.h.
Referenced by ownerId(), permissions(), and QFileSystemEngine::resolveGroupName().
 { return groupId_; }
hasFlags()
bool QFileSystemMetaData::hasFlags (MetaDataFlags flags) const inline
Definition at line 177 of file qfilesystemmetadata_p.h.
Referenced by QFSFileEnginePrivate::doStat(), QFileSystemEngine::fillMetaData(), QFileSystemEngine::fillPermissions(), QFileSystemEngine::getLinkTarget(), QDir::isReadable(), QFSFileEnginePrivate::isSymlink(), QFSFileEnginePrivate::longFileName(), QFileSystemEngine::resolveGroupName(), and QFileSystemEngine::resolveUserName().
     {
         return ((knownFlagsMask & flags) == flags);
     }
isAlias()
bool QFileSystemMetaData::isAlias () const inline
Definition at line 271 of file qfilesystemmetadata_p.h.
Referenced by isDirectory().
 { return (entryFlags & AliasType); }
isBundle()
bool QFileSystemMetaData::isBundle () const inline
Definition at line 270 of file qfilesystemmetadata_p.h.
Referenced by isAlias(), and isDirectory().
 { return (entryFlags & BundleType); }
isDirectory()
bool QFileSystemMetaData::isDirectory () const inline
Definition at line 201 of file qfilesystemmetadata_p.h.
Referenced by QDirPrivate::exists(), QFileSystemEngine::fillMetaData(), QFileSystemEngine::fillPermissions(), QFileSystemEngine::getLinkTarget(), isDirPath(), and QFSFileEnginePrivate::nativeOpen().
 { return (entryFlags & DirectoryType); }
isFile()
bool QFileSystemMetaData::isFile () const inline
Definition at line 200 of file qfilesystemmetadata_p.h.
Referenced by openModeToFopenMode().
 { return (entryFlags & FileType); }
isHidden()
bool QFileSystemMetaData::isHidden () const inline
Definition at line 206 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::fillMetaData().
 { return (entryFlags & HiddenAttribute); }
isLegacyLink()
bool QFileSystemMetaData::isLegacyLink () const inline
Definition at line 204 of file qfilesystemmetadata_p.h.
 { return (entryFlags & LegacyLinkType); }
isLink()
bool QFileSystemMetaData::isLink () const inline
Definition at line 199 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData(), and QFSFileEnginePrivate::isSymlink().
 { return  (entryFlags & LinkType); }
isLnkFile()
bool QFileSystemMetaData::isLnkFile () const inline
Definition at line 208 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData().
 { return (entryFlags & WinLnkType); }
isSequential()
bool QFileSystemMetaData::isSequential () const inline
Definition at line 205 of file qfilesystemmetadata_p.h.
 { return (entryFlags & SequentialType); }
missingFlags()
MetaDataFlags QFileSystemMetaData::missingFlags (MetaDataFlags flags) inline
Definition at line 182 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData(), QFSFileEnginePrivate::doStat(), QFileSystemEngine::fillMetaData(), and QFSFileEnginePrivate::longFileName().
     {
         return flags & ~knownFlagsMask;
     }
modificationTime()
QDateTime QFileSystemMetaData::modificationTime () const inline
Definition at line 1245 of file qfilesystemengine_win.cpp.
Referenced by fileTime(), ownerId(), and permissions().
 {
     return fileTimeToQDateTime(&lastWriteTime_);
 }
ownerId()
uint QFileSystemMetaData::ownerId (QAbstractFileEngine::FileOwner owner) const inline
Definition at line 303 of file qfilesystemmetadata_p.h.
Referenced by permissions().
 {
     if (owner == QAbstractFileEngine::OwnerUser)
         return userId();
     else
         return groupId();
 }
permissions()
QFile::Permissions QFileSystemMetaData::permissions () const inline
Definition at line 215 of file qfilesystemmetadata_p.h.
Referenced by QDir::isReadable().
 { return QFile::Permissions(Permissions & entryFlags); }
size()
qint64 QFileSystemMetaData::size () const inline
Definition at line 213 of file qfilesystemmetadata_p.h.
Referenced by QFSFileEnginePrivate::longFileName(), and QFSFileEnginePrivate::map().
 { return size_; }
userId()
uint QFileSystemMetaData::userId () const inline
Definition at line 300 of file qfilesystemmetadata_p.h.
Referenced by ownerId(), permissions(), and QFileSystemEngine::resolveUserName().
 { return userId_; }
Friends and Related Functions
QFileSystemEngine
friend class QFileSystemEngine friend
Definition at line 241 of file qfilesystemmetadata_p.h.
Properties
creationTime_
FILETIME QFileSystemMetaData::creationTime_ private
Definition at line 251 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData(), fileTime(), fillFromFindData(), fillFromFindInfo(), and QFileSystemEngine::fillMetaData().
entryFlags
MetaDataFlags QFileSystemMetaData::entryFlags private
Definition at line 244 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::canonicalName(), exists(), fillFromFileAttribute(), fillFromFindData(), QFileSystemEngine::fillMetaData(), QFileSystemEngine::fillPermissions(), isAlias(), isBundle(), isDirectory(), isFile(), isHidden(), isLegacyLink(), isLink(), isLnkFile(), isSequential(), permissions(), and QFileSystemEngine::setPermissions().
fileAttribute_
DWORD QFileSystemMetaData::fileAttribute_ private
Definition at line 250 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData(), fillFromFileAttribute(), fillFromFindData(), fillFromFindInfo(), QFileSystemEngine::fillMetaData(), and QFileSystemEngine::fillPermissions().
knownFlagsMask
MetaDataFlags QFileSystemMetaData::knownFlagsMask private
Definition at line 243 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::canonicalName(), clear(), clearFlags(), fillFromFileAttribute(), fillFromFindData(), fillFromFindInfo(), QFileSystemEngine::fillMetaData(), QFileSystemEngine::fillPermissions(), hasFlags(), missingFlags(), and QFileSystemEngine::setPermissions().
lastAccessTime_
FILETIME QFileSystemMetaData::lastAccessTime_ private
Definition at line 252 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData(), fillFromFindData(), and fillFromFindInfo().
lastWriteTime_
FILETIME QFileSystemMetaData::lastWriteTime_ private
Definition at line 253 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData(), fillFromFindData(), and fillFromFindInfo().
size_
qint64 QFileSystemMetaData::size_ private
Definition at line 246 of file qfilesystemmetadata_p.h.
Referenced by QFileSystemEngine::clearWinStatData(), fillFromFindData(), fillFromFindInfo(), QFileSystemEngine::fillMetaData(), and size().
The documentation for this class was generated from the following files:
/src/corelib/io/qfilesystemmetadata_p.h
/src/corelib/io/qfilesystemengine.cpp
/src/corelib/io/qfilesystemengine_win.cpp