Qt 4.8: QFtpDTP Class Reference
QFtpDTP Class Reference
Public Types
enum ConnectState {
CsHostFound, CsConnected, CsClosed, CsHostNotFound,
CsConnectionRefused
}
Signals
void connectState (int)
void dataTransferProgress (qint64, qint64)
void listInfo (const QUrlInfo &)
void readyRead ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void abortConnection ()
qint64 bytesAvailable () const
void clearError ()
void connectToHost (const QString &host, quint16 port)
QString errorMessage () const
bool hasError () const
QFtpDTP (QFtpPI *p, QObject *parent=0)
qint64 read (char *data, qint64 maxlen)
QByteArray readAll ()
void setBytesTotal (qint64 bytes)
void setData (QByteArray *)
void setDevice (QIODevice *)
int setupListener (const QHostAddress &address)
QTcpSocket::SocketState state () const
void waitForConnection ()
void writeData ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool parseDir (const QByteArray &buffer, const QString &userName, QUrlInfo *info)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Slots
void dataReadyRead ()
void setupSocket ()
void socketBytesWritten (qint64)
void socketConnected ()
void socketConnectionClosed ()
void socketError (QAbstractSocket::SocketError)
void socketReadyRead ()
Private Functions
void clearData ()
Properties
qint64 bytesDone
QByteArray bytesFromSocket
qint64 bytesTotal
bool callWriteData
union {
QByteArray * ba
QIODevice * dev
} data
QString err
bool is_ba
QTcpServer listener
QFtpPI * pi
QTcpSocket * socket
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 69 of file qftp.cpp.
Enumerations
ConnectState
enum QFtpDTP::ConnectState
Enumerator
CsHostFound
CsConnected
CsClosed
CsHostNotFound
CsConnectionRefused
Definition at line 74 of file qftp.cpp.
                       {
         CsHostFound,
         CsConnected,
         CsClosed,
         CsHostNotFound,
         CsConnectionRefused
     };
Constructors and Destructors
QFtpDTP()
QFtpDTP::QFtpDTP (QFtpPI * p, QObject * parent = 0)
Definition at line 282 of file qftp.cpp.
                                            :
     QObject(parent),
     socket(0),
     listener(this),
     pi(p),
     callWriteData(false)
 {
     clearData();
     listener.setObjectName(QLatin1String("QFtpDTP active state server"));
     connect(&listener, SIGNAL(newConnection()), SLOT(setupSocket()));
 }
Functions
abortConnection()
void QFtpDTP::abortConnection ()
Definition at line 456 of file qftp.cpp.
Referenced by QFtpPI::abort(), and QFtpPI::clearPendingCommands().
 {
 #if defined(QFTPDTP_DEBUG)
     qDebug("QFtpDTP::abortConnection, bytesAvailable == %lli",
            socket ? socket->bytesAvailable() : (qint64) 0);
 #endif
     callWriteData = false;
     clearData();
     if (socket)
         socket->abort();
 }
bytesAvailable()
qint64 QFtpDTP::bytesAvailable () const
Definition at line 361 of file qftp.cpp.
Referenced by socketReadyRead().
 {
     if (!socket || socket->state() != QTcpSocket::ConnectedState)
         return (qint64) bytesFromSocket.size();
     return socket->bytesAvailable();
 }
clearData()
void QFtpDTP::clearData () private
Definition at line 811 of file qftp.cpp.
Referenced by abortConnection(), QFtpDTP(), socketConnectionClosed(), and writeData().
 {
     is_ba = false;
     data.dev = 0;
 }
clearError()
void QFtpDTP::clearError () inline
Definition at line 451 of file qftp.cpp.
Referenced by QFtpPI::processReply().
 {
     err.clear();
 }
connectState
void QFtpDTP::connectState (int) signal
Referenced by socketConnected(), socketConnectionClosed(), socketError(), and socketReadyRead().
connectToHost()
void QFtpDTP::connectToHost (const QString & host, quint16 port)
Definition at line 313 of file qftp.cpp.
Referenced by QFtpPI::processReply().
 {
     bytesFromSocket.clear();
     if (socket) {
         delete socket;
         socket = 0;
     }
     socket = new QTcpSocket(this);
 #ifndef QT_NO_BEARERMANAGEMENT
     //copy network session down to the socket
     socket->setProperty("_q_networksession", property("_q_networksession"));
 #endif
     socket->setObjectName(QLatin1String("QFtpDTP Passive state socket"));
     connect(socket, SIGNAL(connected()), SLOT(socketConnected()));
     connect(socket, SIGNAL(readyRead()), SLOT(socketReadyRead()));
     connect(socket, SIGNAL(error(QAbstractSocket::SocketError)), SLOT(socketError(QAbstractSocket::SocketError)));
     connect(socket, SIGNAL(disconnected()), SLOT(socketConnectionClosed()));
     connect(socket, SIGNAL(bytesWritten(qint64)), SLOT(socketBytesWritten(qint64)));
     socket->connectToHost(host, port);
 }
dataReadyRead
void QFtpDTP::dataReadyRead () private slot
Definition at line 436 of file qftp.cpp.
 {
     writeData();
 }
dataTransferProgress
void QFtpDTP::dataTransferProgress (qint64 , qint64) signal
Referenced by setBytesTotal(), socketBytesWritten(), socketReadyRead(), and writeData().
errorMessage()
QString QFtpDTP::errorMessage () const inline
Definition at line 446 of file qftp.cpp.
Referenced by QFtpPI::processReply().
 {
     return err;
 }
hasError()
bool QFtpDTP::hasError () const inline
Definition at line 441 of file qftp.cpp.
Referenced by QFtpPI::processReply().
 {
     return !err.isNull();
 }
listInfo
void QFtpDTP::listInfo (const QUrlInfo &) signal
Referenced by socketReadyRead().
parseDir()
bool QFtpDTP::parseDir (const QByteArray & buffer, const QString & userName, QUrlInfo * info) static
Definition at line 651 of file qftp.cpp.
Referenced by socketReadyRead().
 {
     if (buffer.isEmpty())
         return false;
     QString bufferStr = QString::fromLatin1(buffer).trimmed();
     // Unix style FTP servers
     QRegExp unixPattern(QLatin1String("^([\\-dl])([a-zA-Z\\-]{9,9})\\s+\\d+\\s+(\\S*)\\s+"
                                       "(\\S*)\\s+(\\d+)\\s+(\\S+\\s+\\S+\\s+\\S+)\\s+(\\S.*)"));
     if (unixPattern.indexIn(bufferStr) == 0) {
         _q_parseUnixDir(unixPattern.capturedTexts(), userName, info);
         return true;
     }
     // DOS style FTP servers
     QRegExp dosPattern(QLatin1String("^(\\d\\d-\\d\\d-\\d\\d\\ \\ \\d\\d:\\d\\d[AP]M)\\s+"
                                      "(<DIR>|\\d+)\\s+(\\S.*)$"));
     if (dosPattern.indexIn(bufferStr) == 0) {
         _q_parseDosDir(dosPattern.capturedTexts(), userName, info);
         return true;
     }
     // Unsupported
     return false;
 }
read()
qint64 QFtpDTP::read (char * data, qint64 maxlen)
Definition at line 368 of file qftp.cpp.
Referenced by writeData().
 {
     qint64 read;
     if (socket && socket->state() == QTcpSocket::ConnectedState) {
         read = socket->read(data, maxlen);
     } else {
         read = qMin(maxlen, qint64(bytesFromSocket.size()));
         memcpy(data, bytesFromSocket.data(), read);
         bytesFromSocket.remove(0, read);
     }
     bytesDone += read;
     return read;
 }
readAll()
QByteArray QFtpDTP::readAll ()
Definition at line 383 of file qftp.cpp.
 {
     QByteArray tmp;
     if (socket && socket->state() == QTcpSocket::ConnectedState) {
         tmp = socket->readAll();
         bytesDone += tmp.size();
     } else {
         tmp = bytesFromSocket;
         bytesFromSocket.clear();
     }
     return tmp;
 }
readyRead
void QFtpDTP::readyRead () signal
Referenced by connectToHost(), setupSocket(), and socketReadyRead().
setBytesTotal()
void QFtpDTP::setBytesTotal (qint64 bytes)
Definition at line 306 of file qftp.cpp.
Referenced by QFtpPI::processReply().
 {
     bytesTotal = bytes;
     bytesDone = 0;
     emit dataTransferProgress(bytesDone, bytesTotal);
 }
setData()
void QFtpDTP::setData (QByteArray * ba)
Definition at line 294 of file qftp.cpp.
 {
     is_ba = true;
     data.ba = ba;
 }
setDevice()
void QFtpDTP::setDevice (QIODevice * dev)
Definition at line 300 of file qftp.cpp.
 {
     is_ba = false;
     data.dev = dev;
 }
setupListener()
int QFtpDTP::setupListener (const QHostAddress & address)
Definition at line 336 of file qftp.cpp.
Referenced by QFtpPI::startNextCmd().
 {
 #ifndef QT_NO_BEARERMANAGEMENT
     //copy network session down to the socket
     listener.setProperty("_q_networksession", property("_q_networksession"));
 #endif
     if (!listener.isListening() && !listener.listen(address, 0))
         return -1;
     return listener.serverPort();
 }
setupSocket
void QFtpDTP::setupSocket () private slot
Definition at line 798 of file qftp.cpp.
Referenced by QFtpDTP().
 {
     socket = listener.nextPendingConnection();
     socket->setObjectName(QLatin1String("QFtpDTP Active state socket"));
     connect(socket, SIGNAL(connected()), SLOT(socketConnected()));
     connect(socket, SIGNAL(readyRead()), SLOT(socketReadyRead()));
     connect(socket, SIGNAL(error(QAbstractSocket::SocketError)), SLOT(socketError(QAbstractSocket::SocketError)));
     connect(socket, SIGNAL(disconnected()), SLOT(socketConnectionClosed()));
     connect(socket, SIGNAL(bytesWritten(qint64)), SLOT(socketBytesWritten(qint64)));
     listener.close();
 }
socketBytesWritten
void QFtpDTP::socketBytesWritten (qint64 bytes) private slot
Definition at line 787 of file qftp.cpp.
Referenced by connectToHost(), and setupSocket().
 {
     bytesDone += bytes;
 #if defined(QFTPDTP_DEBUG)
     qDebug("QFtpDTP::bytesWritten(%lli)", bytesDone);
 #endif
     emit dataTransferProgress(bytesDone, bytesTotal);
     if (callWriteData)
         writeData();
 }
socketConnected
void QFtpDTP::socketConnected () private slot
Definition at line 678 of file qftp.cpp.
Referenced by connectToHost(), and setupSocket().
 {
     bytesDone = 0;
 #if defined(QFTPDTP_DEBUG)
     qDebug("QFtpDTP::connectState(CsConnected)");
 #endif
     emit connectState(QFtpDTP::CsConnected);
 }
socketConnectionClosed
void QFtpDTP::socketConnectionClosed () private slot
Definition at line 774 of file qftp.cpp.
Referenced by connectToHost(), and setupSocket().
 {
     if (!is_ba && data.dev) {
         clearData();
     }
     bytesFromSocket = socket->readAll();
 #if defined(QFTPDTP_DEBUG)
     qDebug("QFtpDTP::connectState(CsClosed)");
 #endif
     emit connectState(QFtpDTP::CsClosed);
 }
socketError
void QFtpDTP::socketError (QAbstractSocket::SocketError e) private slot
Definition at line 759 of file qftp.cpp.
Referenced by connectToHost(), and setupSocket().
 {
     if (e == QTcpSocket::HostNotFoundError) {
 #if defined(QFTPDTP_DEBUG)
         qDebug("QFtpDTP::connectState(CsHostNotFound)");
 #endif
         emit connectState(QFtpDTP::CsHostNotFound);
     } else if (e == QTcpSocket::ConnectionRefusedError) {
 #if defined(QFTPDTP_DEBUG)
         qDebug("QFtpDTP::connectState(CsConnectionRefused)");
 #endif
         emit connectState(QFtpDTP::CsConnectionRefused);
     }
 }
socketReadyRead
void QFtpDTP::socketReadyRead () private slot
Definition at line 687 of file qftp.cpp.
Referenced by connectToHost(), and setupSocket().
 {
     if (!socket)
         return;
     if (pi->currentCommand().isEmpty()) {
         socket->close();
 #if defined(QFTPDTP_DEBUG)
         qDebug("QFtpDTP::connectState(CsClosed)");
 #endif
         emit connectState(QFtpDTP::CsClosed);
         return;
     }
     if (pi->abortState != QFtpPI::None) {
         // discard data
         socket->readAll();
         return;
     }
     if (pi->currentCommand().startsWith(QLatin1String("LIST"))) {
         while (socket->canReadLine()) {
             QUrlInfo i;
             QByteArray line = socket->readLine();
 #if defined(QFTPDTP_DEBUG)
             qDebug("QFtpDTP read (list): '%s'", line.constData());
 #endif
             if (parseDir(line, QLatin1String(""), &i)) {
                 emit listInfo(i);
             } else {
                 // some FTP servers don't return a 550 if the file or directory
                 // does not exist, but rather write a text to the data socket
                 // -- try to catch these cases
                 if (line.endsWith("No such file or directory\r\n"))
                     err = QString::fromLatin1(line);
             }
         }
     } else {
         if (!is_ba && data.dev) {
             do {
                 QByteArray ba;
                 ba.resize(socket->bytesAvailable());
                 qint64 bytesRead = socket->read(ba.data(), ba.size());
                 if (bytesRead < 0) {
                     // a read following a readyRead() signal will
                     // never fail.
                     return;
                 }
                 ba.resize(bytesRead);
                 bytesDone += bytesRead;
 #if defined(QFTPDTP_DEBUG)
                 qDebug("QFtpDTP read: %lli bytes (total %lli bytes)", bytesRead, bytesDone);
 #endif
                 if (data.dev)       // make sure it wasn't deleted in the slot
                     data.dev->write(ba);
                 emit dataTransferProgress(bytesDone, bytesTotal);
                 // Need to loop; dataTransferProgress is often connected to
                 // slots that update the GUI (e.g., progress bar values), and
                 // if events are processed, more data may have arrived.
             } while (socket->bytesAvailable());
         } else {
 #if defined(QFTPDTP_DEBUG)
             qDebug("QFtpDTP readyRead: %lli bytes available (total %lli bytes read)",
                    bytesAvailable(), bytesDone);
 #endif
             emit dataTransferProgress(bytesDone+socket->bytesAvailable(), bytesTotal);
             emit readyRead();
         }
     }
 }
state()
QTcpSocket::SocketState QFtpDTP::state () const
Definition at line 356 of file qftp.cpp.
Referenced by QFtpPI::processReply().
 {
     return socket ? socket->state() : QTcpSocket::UnconnectedState;
 }
waitForConnection()
void QFtpDTP::waitForConnection ()
Definition at line 347 of file qftp.cpp.
Referenced by QFtpPI::processReply().
 {
     // This function is only interesting in Active transfer mode; it works
     // around a limitation in QFtp's design by blocking, waiting for an
     // incoming connection. For the default Passive mode, it does nothing.
     if (listener.isListening())
         listener.waitForNewConnection();
 }
writeData()
void QFtpDTP::writeData ()
Definition at line 396 of file qftp.cpp.
Referenced by dataReadyRead(), QFtpPI::processReply(), and socketBytesWritten().
 {
     if (!socket)
         return;
     if (is_ba) {
 #if defined(QFTPDTP_DEBUG)
         qDebug("QFtpDTP::writeData: write %d bytes", data.ba->size());
 #endif
         if (data.ba->size() == 0)
             emit dataTransferProgress(0, bytesTotal);
         else
             socket->write(data.ba->data(), data.ba->size());
         socket->close();
         clearData();
     } else if (data.dev) {
         callWriteData = false;
         const qint64 blockSize = 16*1024;
         char buf[16*1024];
         qint64 read = data.dev->read(buf, blockSize);
 #if defined(QFTPDTP_DEBUG)
         qDebug("QFtpDTP::writeData: write() of size %lli bytes", read);
 #endif
         if (read > 0) {
             socket->write(buf, read);
         } else if (read == -1 || (!data.dev->isSequential() && data.dev->atEnd())) {
             // error or EOF
             if (bytesDone == 0 && socket->bytesToWrite() == 0)
                 emit dataTransferProgress(0, bytesTotal);
             socket->close();
             clearData();
         }
         // do we continue uploading?
         callWriteData = data.dev != 0;
     }
 }
Properties
ba
QByteArray* QFtpDTP::ba
Definition at line 138 of file qftp.cpp.
Referenced by setData(), and socketReadyRead().
bytesDone
qint64 QFtpDTP::bytesDone private
Definition at line 131 of file qftp.cpp.
Referenced by read(), readAll(), setBytesTotal(), socketBytesWritten(), socketConnected(), socketReadyRead(), and writeData().
bytesFromSocket
QByteArray QFtpDTP::bytesFromSocket private
Definition at line 143 of file qftp.cpp.
Referenced by bytesAvailable(), connectToHost(), read(), readAll(), and socketConnectionClosed().
bytesTotal
qint64 QFtpDTP::bytesTotal private
Definition at line 132 of file qftp.cpp.
Referenced by setBytesTotal(), socketBytesWritten(), socketReadyRead(), and writeData().
callWriteData
bool QFtpDTP::callWriteData private
Definition at line 133 of file qftp.cpp.
Referenced by abortConnection(), socketBytesWritten(), and writeData().
data
union { ... } QFtpDTP::data
Referenced by clearData(), setData(), setDevice(), socketConnectionClosed(), socketReadyRead(), and writeData().
dev
QIODevice* QFtpDTP::dev
Definition at line 139 of file qftp.cpp.
Referenced by setDevice().
err
QString QFtpDTP::err private
Definition at line 130 of file qftp.cpp.
Referenced by clearError(), errorMessage(), hasError(), and socketReadyRead().
is_ba
bool QFtpDTP::is_ba private
Definition at line 141 of file qftp.cpp.
Referenced by clearData(), setData(), setDevice(), socketConnectionClosed(), socketReadyRead(), and writeData().
listener
QTcpServer QFtpDTP::listener private
Definition at line 127 of file qftp.cpp.
Referenced by QFtpDTP(), setupListener(), setupSocket(), and waitForConnection().
pi
QFtpPI* QFtpDTP::pi private
Definition at line 129 of file qftp.cpp.
Referenced by socketReadyRead().
socket
QTcpSocket* QFtpDTP::socket private
Definition at line 126 of file qftp.cpp.
Referenced by abortConnection(), bytesAvailable(), connectToHost(), read(), readAll(), setupSocket(), socketConnectionClosed(), socketReadyRead(), state(), and writeData().
The documentation for this class was generated from the following file:
/src/network/access/qftp.cpp