Qt 4.8: QDeclarativeGridView Class Reference
QDeclarativeGridView Class Reference
#include <qdeclarativegridview_p.h>
Public Types
enum Flow { LeftToRight, TopToBottom }
enum HighlightRangeMode { NoHighlightRange, ApplyRange, StrictlyEnforceRange }
enum PositionMode {
Beginning, Center, End, Visible,
Contain
}
enum SnapMode { NoSnap, SnapToRow, SnapOneRow }
Public Types inherited from QDeclarativeFlickable
enum BoundsBehavior { StopAtBounds, DragOverBounds, DragAndOvershootBounds }
enum FlickableDirection { AutoFlickDirection =0x00, HorizontalFlick =0x01, VerticalFlick =0x02, HorizontalAndVerticalFlick =0x03 }
Public Types inherited from QDeclarativeItem
enum TransformOrigin {
TopLeft, Top, TopRight, Left,
Center, Right, BottomLeft, Bottom,
BottomRight
}
Controls the point about which simple transforms like scale apply.
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots
void moveCurrentIndexDown ()
void moveCurrentIndexLeft ()
void moveCurrentIndexRight ()
void moveCurrentIndexUp ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void cacheBufferChanged ()
void cellHeightChanged ()
void cellWidthChanged ()
void countChanged ()
void currentIndexChanged ()
void delegateChanged ()
void flowChanged ()
void footerChanged ()
void headerChanged ()
void highlightChanged ()
void highlightItemChanged ()
void highlightMoveDurationChanged ()
void highlightRangeModeChanged ()
void keyNavigationWrapsChanged ()
void layoutDirectionChanged ()
void modelChanged ()
void preferredHighlightBeginChanged ()
void preferredHighlightEndChanged ()
void snapModeChanged ()
Signals inherited from QDeclarativeFlickable
void boundsBehaviorChanged ()
void contentHeightChanged ()
void contentWidthChanged ()
void contentXChanged ()
void contentYChanged ()
void flickableDirectionChanged ()
void flickDecelerationChanged ()
void flickEnded ()
void flickingChanged ()
void flickingHorizontallyChanged ()
void flickingVerticallyChanged ()
void flickStarted ()
void horizontalVelocityChanged ()
void interactiveChanged ()
void isAtBoundaryChanged ()
void maximumFlickVelocityChanged ()
void movementEnded ()
void movementStarted ()
void movingChanged ()
void movingHorizontallyChanged ()
void movingVerticallyChanged ()
void pressDelayChanged ()
void verticalVelocityChanged ()
Signals inherited from QDeclarativeItem
void activeFocusChanged (bool)
void baselineOffsetChanged (qreal)
void childrenRectChanged (const QRectF &)
void clipChanged (bool)
void focusChanged (bool)
void implicitHeightChanged ()
void implicitWidthChanged ()
void parentChanged (QDeclarativeItem *)
void smoothChanged (bool)
void stateChanged (const QString &)
void transformOriginChanged (TransformOrigin)
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int cacheBuffer () const
int cellHeight () const
int cellWidth () const
int count () const
int currentIndex () const
QDeclarativeItem * currentItem ()
QDeclarativeComponent * delegate () const
Qt::LayoutDirection effectiveLayoutDirection () const
Flow flow () const
QDeclarativeComponent * footer () const
QDeclarativeComponent * header () const
QDeclarativeComponent * highlight () const
bool highlightFollowsCurrentItem () const
QDeclarativeItem * highlightItem ()
int highlightMoveDuration () const
HighlightRangeMode highlightRangeMode () const
Q_INVOKABLE int indexAt (qreal x, qreal y) const
bool isWrapEnabled () const
Qt::LayoutDirection layoutDirection () const
QVariant model () const
int modelCount () const
Q_INVOKABLE void positionViewAtBeginning ()
Q_INVOKABLE void positionViewAtEnd ()
Q_INVOKABLE void positionViewAtIndex (int index, int mode)
qreal preferredHighlightBegin () const
qreal preferredHighlightEnd () const
QDeclarativeGridView (QDeclarativeItem *parent=0)
void resetPreferredHighlightBegin ()
void resetPreferredHighlightEnd ()
void setCacheBuffer (int)
void setCellHeight (int)
void setCellWidth (int)
virtual void setContentX (qreal pos)
virtual void setContentY (qreal pos)
void setCurrentIndex (int idx)
void setDelegate (QDeclarativeComponent *)
void setFlow (Flow)
void setFooter (QDeclarativeComponent *)
void setHeader (QDeclarativeComponent *)
void setHighlight (QDeclarativeComponent *highlight)
void setHighlightFollowsCurrentItem (bool)
void setHighlightMoveDuration (int)
void setHighlightRangeMode (HighlightRangeMode mode)
void setLayoutDirection (Qt::LayoutDirection)
void setModel (const QVariant &)
void setPreferredHighlightBegin (qreal)
void setPreferredHighlightEnd (qreal)
void setSnapMode (SnapMode mode)
void setWrapEnabled (bool)
SnapMode snapMode () const
~QDeclarativeGridView ()
Public Functions inherited from QDeclarativeFlickable
BoundsBehavior boundsBehavior () const
qreal contentHeight () const
QDeclarativeItem * contentItem ()
qreal contentWidth () const
qreal contentX () const
qreal contentY () const
QDeclarativeListProperty< QGraphicsObject > flickableChildren ()
QDeclarativeListProperty< QObject > flickableData ()
FlickableDirection flickableDirection () const
qreal flickDeceleration () const
qreal horizontalVelocity () const
bool isAtXBeginning () const
bool isAtXEnd () const
bool isAtYBeginning () const
bool isAtYEnd () const
bool isFlicking () const
bool isFlickingHorizontally () const
bool isFlickingVertically () const
bool isInteractive () const
bool isMoving () const
bool isMovingHorizontally () const
bool isMovingVertically () const
qreal maximumFlickVelocity () const
int pressDelay () const
QDeclarativeFlickable (QDeclarativeItem *parent=0)
Q_INVOKABLE void resizeContent (qreal w, qreal h, QPointF center)
Q_INVOKABLE void returnToBounds ()
void setBoundsBehavior (BoundsBehavior)
void setContentHeight (qreal)
void setContentWidth (qreal)
void setFlickableDirection (FlickableDirection)
void setFlickDeceleration (qreal)
void setInteractive (bool)
void setMaximumFlickVelocity (qreal)
void setPressDelay (int delay)
qreal verticalVelocity () const
~QDeclarativeFlickable ()
Public Functions inherited from QDeclarativeItem
qreal baselineOffset () const
QRectF boundingRect () const
Q_INVOKABLE QDeclarativeItem * childAt (qreal x, qreal y) const
Returns the visible child item at point (x, y), which is in this item's coordinate system, or 0 if there is no such item.
QRectF childrenRect ()
bool clip () const
Q_INVOKABLE void forceActiveFocus ()
Forces active focus on the item.
bool hasActiveFocus () const
bool hasFocus () const
qreal height () const
qreal implicitHeight () const
qreal implicitWidth () const
bool keepMouseGrab () const
Returns a value indicating whether mouse input should remain with this item exclusively.
Q_INVOKABLE QScriptValue mapFromItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in item's coordinate system, to this item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
Q_INVOKABLE QScriptValue mapToItem (const QScriptValue &item, qreal x, qreal y) const
Maps the point (x, y), which is in this item's coordinate system, to item's coordinate system, and returns a script value with x and y properties matching the mapped cooordinate.
virtual void paint (QPainter *, const QStyleOptionGraphicsItem *, QWidget *)
QDeclarativeItem * parentItem () const
Returns the QDeclarativeItem parent of this item.
QDeclarativeItem (QDeclarativeItem *parent=0)
Constructs a QDeclarativeItem with the given parent.
void resetHeight ()
void resetWidth ()
void setBaselineOffset (qreal)
void setClip (bool)
void setFocus (bool)
void setHeight (qreal)
void setKeepMouseGrab (bool)
The flag indicating whether the mouse should remain with this item is set to keep.
void setParentItem (QDeclarativeItem *parent)
void setSize (const QSizeF &size)
void setSmooth (bool)
Sets whether the item should be drawn with antialiasing and smooth pixmap filtering to smooth.
void setTransformOrigin (TransformOrigin)
Set the transform origin.
void setWidth (qreal)
bool smooth () const
QDeclarativeListProperty< QGraphicsTransform > transform ()
TransformOrigin transformOrigin () const
qreal width () const
virtual ~QDeclarativeItem ()
Destroys the QDeclarativeItem.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Static Public Functions
static QDeclarativeGridViewAttached * qmlAttachedProperties (QObject *)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual void componentComplete ()
virtual bool event (QEvent *event)
virtual void keyPressEvent (QKeyEvent *)
virtual qreal maxXExtent () const
virtual qreal maxYExtent () const
virtual qreal minXExtent () const
virtual qreal minYExtent () const
virtual void viewportMoved ()
Protected Functions inherited from QDeclarativeFlickable
void cancelFlick ()
virtual void geometryChanged (const QRectF &newGeometry, const QRectF &oldGeometry)
This function is called to handle this item's changes in geometry from oldGeometry to newGeometry.
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void movementXEnding ()
void movementYEnding ()
QDeclarativeFlickable (QDeclarativeFlickablePrivate &dd, QDeclarativeItem *parent)
bool sceneEvent (QEvent *event)
virtual bool sceneEventFilter (QGraphicsItem *, QEvent *)
Filters events for the item watched.
bool sendMouseEvent (QGraphicsSceneMouseEvent *event)
void timerEvent (QTimerEvent *event)
This event handler can be reimplemented in a subclass to receive timer events for the object.
qreal vHeight () const
QDeclarativeFlickableVisibleArea * visibleArea ()
qreal vWidth () const
void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
bool xflick () const
bool yflick () const
Protected Functions inherited from QDeclarativeItem
virtual void classBegin ()
bool heightValid () const
Returns whether the height property has been set explicitly.
virtual void inputMethodEvent (QInputMethodEvent *)
void inputMethodPreHandler (QInputMethodEvent *)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
bool isComponentComplete () const
Returns true if construction of the QML component is complete; otherwise returns false.
virtual QVariant itemChange (GraphicsItemChange, const QVariant &)
Note that unlike QGraphicsItems, QDeclarativeItem::itemChange() is not called during initial widget polishing.
void keyPressPreHandler (QKeyEvent *)
virtual void keyReleaseEvent (QKeyEvent *event)
void keyReleasePreHandler (QKeyEvent *)
QDeclarativeItem (QDeclarativeItemPrivate &dd, QDeclarativeItem *parent=0)
void setImplicitHeight (qreal)
Sets the implied height of the item to h.
void setImplicitWidth (qreal)
Sets the implied width of the item to w.
bool widthValid () const
Returns whether the width property has been set explicitly.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
Private Slots
void animStopped ()
void createdItem (int index, QDeclarativeItem *item)
void destroyingItem (QDeclarativeItem *item)
void destroyRemoved ()
void itemsInserted (int index, int count)
void itemsMoved (int from, int to, int count)
void itemsRemoved (int index, int count)
void modelReset ()
void trackedPositionChanged ()
Private Functions
void refill ()
Properties
int cacheBuffer
int cellHeight
int cellWidth
int count
int currentIndex
QDeclarativeItem * currentItem
QDeclarativeComponent * delegate
Flow flow
QDeclarativeComponent * footer
QDeclarativeComponent * header
QDeclarativeComponent * highlight
bool highlightFollowsCurrentItem
QDeclarativeItem * highlightItem
int highlightMoveDuration
HighlightRangeMode highlightRangeMode
bool keyNavigationWraps
Qt::LayoutDirection layoutDirection
QVariant model
qreal preferredHighlightBegin
qreal preferredHighlightEnd
SnapMode snapMode
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QDeclarativeFlickable
void movementEnding ()
void movementStarting ()
virtual void ticked ()
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
Definition at line 56 of file qdeclarativegridview_p.h.
Enumerations
Flow
enum QDeclarativeGridView::Flow
Enumerator
LeftToRight
TopToBottom
Definition at line 137 of file qdeclarativegridview_p.h.
 { LeftToRight, TopToBottom };
HighlightRangeMode
enum QDeclarativeGridView::HighlightRangeMode
Enumerator
NoHighlightRange
ApplyRange
StrictlyEnforceRange
Definition at line 121 of file qdeclarativegridview_p.h.
 { NoHighlightRange, ApplyRange, StrictlyEnforceRange };
PositionMode
enum QDeclarativeGridView::PositionMode
Enumerator
Beginning
Center
End
Visible
Contain
Definition at line 166 of file qdeclarativegridview_p.h.
 { Beginning, Center, End, Visible, Contain };
SnapMode
enum QDeclarativeGridView::SnapMode
Enumerator
NoSnap
SnapToRow
SnapOneRow
Definition at line 153 of file qdeclarativegridview_p.h.
 { NoSnap, SnapToRow, SnapOneRow };
Constructors and Destructors
QDeclarativeGridView()
QDeclarativeGridView::QDeclarativeGridView (QDeclarativeItem * parent = 0)
Definition at line 1349 of file qdeclarativegridview.cpp.
     : QDeclarativeFlickable(*(new QDeclarativeGridViewPrivate), parent)
 {
     Q_D(QDeclarativeGridView);
     d->init();
 }
~QDeclarativeGridView()
QDeclarativeGridView::~QDeclarativeGridView ()
Definition at line 1356 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     d->clear();
     if (d->ownModel)
         delete d->model;
     delete d->header;
     delete d->footer;
 }
Functions
animStopped
void QDeclarativeGridView::animStopped () private slot
Definition at line 3230 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     d->bufferMode = QDeclarativeGridViewPrivate::NoBuffer;
     if (d->haveHighlightRange && d->highlightRange == QDeclarativeGridView::StrictlyEnforceRange)
         d->updateHighlight();
 }
cacheBuffer()
int QDeclarativeGridView::cacheBuffer () const
Referenced by setWrapEnabled().
cacheBufferChanged
void QDeclarativeGridView::cacheBufferChanged () signal
Referenced by setCacheBuffer().
cellHeight()
int QDeclarativeGridView::cellHeight () const
Referenced by setCellWidth().
cellHeightChanged
void QDeclarativeGridView::cellHeightChanged () signal
Referenced by setCellHeight().
cellWidth()
int QDeclarativeGridView::cellWidth () const
Referenced by setCacheBuffer().
cellWidthChanged
void QDeclarativeGridView::cellWidthChanged () signal
Referenced by setCellWidth().
componentComplete()
void QDeclarativeGridView::componentComplete () protected virtual
Warning
This function is not part of the public interface.
componentComplete() is called when all items in the component have been constructed. It is often desirable to delay some processing until the component is complete an all bindings in the component have been resolved.
Reimplemented from QDeclarativeItem.
Definition at line 2766 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     QDeclarativeFlickable::componentComplete();
     d->updateHeader();
     d->updateFooter();
     d->updateGrid();
     if (d->isValid()) {
         refill();
         d->moveReason = QDeclarativeGridViewPrivate::SetIndex;
         if (d->currentIndex < 0 && !d->currentIndexCleared)
             d->updateCurrent(0);
         else
             d->updateCurrent(d->currentIndex);
         if (d->highlight && d->currentItem) {
             if (d->autoHighlight)
                 d->highlight->setPosition(d->currentItem->colPos(), d->currentItem->rowPos());
             d->updateTrackedItem();
         }
         d->moveReason = QDeclarativeGridViewPrivate::Other;
         d->fixupPosition();
     }
 }
count()
int QDeclarativeGridView::count () const
Referenced by itemsInserted(), itemsMoved(), itemsRemoved(), moveCurrentIndexDown(), moveCurrentIndexLeft(), moveCurrentIndexRight(), moveCurrentIndexUp(), and setCurrentIndex().
countChanged
void QDeclarativeGridView::countChanged () signal
Referenced by itemsInserted(), itemsRemoved(), modelReset(), setDelegate(), and setModel().
createdItem
void QDeclarativeGridView::createdItem (int index, QDeclarativeItem * item) private slot
Definition at line 3210 of file qdeclarativegridview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeGridView);
     if (d->requestedIndex != index) {
         item->setParentItem(this);
         d->unrequestedItems.insert(item, index);
         if (d->flow == QDeclarativeGridView::LeftToRight) {
             item->setPos(QPointF(d->colPosAt(index), d->rowPosAt(index)));
         } else {
             item->setPos(QPointF(d->rowPosAt(index), d->colPosAt(index)));
         }
     }
 }
currentIndex()
int QDeclarativeGridView::currentIndex () const
Referenced by keyPressEvent(), moveCurrentIndexDown(), moveCurrentIndexLeft(), moveCurrentIndexRight(), moveCurrentIndexUp(), and setDelegate().
currentIndexChanged
void QDeclarativeGridView::currentIndexChanged () signal
Referenced by itemsInserted(), itemsMoved(), itemsRemoved(), and setCurrentIndex().
currentItem()
QDeclarativeItem* QDeclarativeGridView::currentItem ()
Referenced by setCurrentIndex(), and trackedPositionChanged().
delegate()
QDeclarativeComponent* QDeclarativeGridView::delegate () const
Referenced by setDelegate(), and setModel().
delegateChanged
void QDeclarativeGridView::delegateChanged () signal
Referenced by setDelegate().
destroyingItem
void QDeclarativeGridView::destroyingItem (QDeclarativeItem * item) private slot
Definition at line 3224 of file qdeclarativegridview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeGridView);
     d->unrequestedItems.remove(item);
 }
destroyRemoved
void QDeclarativeGridView::destroyRemoved () private slot
Definition at line 3078 of file qdeclarativegridview.cpp.
Referenced by itemsRemoved().
 {
     Q_D(QDeclarativeGridView);
     for (QList<FxGridItem*>::Iterator it = d->visibleItems.begin();
             it != d->visibleItems.end();) {
         FxGridItem *listItem = *it;
         if (listItem->index == -1 && listItem->attached->delayRemove() == false) {
             d->releaseItem(listItem);
             it = d->visibleItems.erase(it);
         } else {
             ++it;
         }
     }
     // Correct the positioning of the items
     d->layout();
 }
effectiveLayoutDirection()
Qt::LayoutDirection QDeclarativeGridView::effectiveLayoutDirection () const
Definition at line 1905 of file qdeclarativegridview.cpp.
Referenced by FxGridItem::colPos(), FxGridItem::endRowPos(), moveCurrentIndexLeft(), moveCurrentIndexRight(), FxGridItem::rowPos(), and FxGridItem::setPosition().
 {
     Q_D(const QDeclarativeGridView);
     if (d->effectiveLayoutMirror)
         return d->layoutDirection == Qt::RightToLeft ? Qt::LeftToRight : Qt::RightToLeft;
     else
         return d->layoutDirection;
 }
event()
bool QDeclarativeGridView::event (QEvent * ev) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 2193 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (event->type() == QEvent::User) {
         if (d->layoutScheduled)
             d->layout();
         return true;
     }
     return QDeclarativeFlickable::event(event);
 }
flow()
Flow QDeclarativeGridView::flow () const
Referenced by effectiveLayoutDirection(), QDeclarativeGridViewPrivate::positionViewAtIndex(), and setFlow().
flowChanged
void QDeclarativeGridView::flowChanged () signal
Referenced by setFlow().
footer()
QDeclarativeComponent* QDeclarativeGridView::footer () const
Referenced by QDeclarativeGridViewPrivate::positionViewAtIndex(), setFooter(), and setSnapMode().
footerChanged
void QDeclarativeGridView::footerChanged () signal
Referenced by setFooter().
header()
QDeclarativeComponent* QDeclarativeGridView::header () const
Referenced by QDeclarativeGridViewPrivate::positionViewAtIndex(), setFooter(), and setHeader().
headerChanged
void QDeclarativeGridView::headerChanged () signal
Referenced by setHeader().
highlight()
QDeclarativeComponent* QDeclarativeGridView::highlight () const
Referenced by setCurrentIndex(), and setHighlight().
highlightChanged
void QDeclarativeGridView::highlightChanged () signal
Referenced by setHighlight().
highlightFollowsCurrentItem()
bool QDeclarativeGridView::highlightFollowsCurrentItem () const
Referenced by setHighlight().
highlightItem()
QDeclarativeItem* QDeclarativeGridView::highlightItem ()
Referenced by setCurrentIndex().
highlightItemChanged
void QDeclarativeGridView::highlightItemChanged () signal
highlightMoveDuration()
int QDeclarativeGridView::highlightMoveDuration () const
Referenced by setHighlightFollowsCurrentItem().
highlightMoveDurationChanged
void QDeclarativeGridView::highlightMoveDurationChanged () signal
Referenced by setHighlightMoveDuration().
highlightRangeMode()
HighlightRangeMode QDeclarativeGridView::highlightRangeMode () const
Referenced by resetPreferredHighlightEnd().
highlightRangeModeChanged
void QDeclarativeGridView::highlightRangeModeChanged () signal
Referenced by setHighlightRangeMode().
indexAt()
int QDeclarativeGridView::indexAt (qreal x, qreal y) const
Definition at line 2754 of file qdeclarativegridview.cpp.
 {
     Q_D(const QDeclarativeGridView);
     for (int i = 0; i < d->visibleItems.count(); ++i) {
         const FxGridItem *listItem = d->visibleItems.at(i);
         if(listItem->contains(x, y))
             return listItem->index;
     }
     return -1;
 }
isWrapEnabled()
bool QDeclarativeGridView::isWrapEnabled () const
Definition at line 1966 of file qdeclarativegridview.cpp.
 {
     Q_D(const QDeclarativeGridView);
     return d->wrap;
 }
itemsInserted
void QDeclarativeGridView::itemsInserted (int index, int count) private slot
Definition at line 2856 of file qdeclarativegridview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeGridView);
     if (!isComponentComplete())
         return;
     int index = d->visibleItems.count() ? d->mapFromModel(modelIndex) : 0;
     if (index < 0) {
         int i = d->visibleItems.count() - 1;
         while (i > 0 && d->visibleItems.at(i)->index == -1)
             --i;
         if (d->visibleItems.at(i)->index + 1 == modelIndex) {
             // Special case of appending an item to the model.
             index = d->visibleIndex + d->visibleItems.count();
         } else {
             if (modelIndex <= d->visibleIndex) {
                 // Insert before visible items
                 d->visibleIndex += count;
                 for (int i = 0; i < d->visibleItems.count(); ++i) {
                     FxGridItem *listItem = d->visibleItems.at(i);
                     if (listItem->index != -1 && listItem->index >= modelIndex)
                         listItem->index += count;
                 }
             }
             if (d->currentIndex >= modelIndex) {
                 // adjust current item index
                 d->currentIndex += count;
                 if (d->currentItem)
                     d->currentItem->index = d->currentIndex;
                 emit currentIndexChanged();
             }
             d->scheduleLayout();
             d->itemCount += count;
             emit countChanged();
             return;
         }
     }
     int insertCount = count;
     if (index < d->visibleIndex && d->visibleItems.count()) {
         insertCount -= d->visibleIndex - index;
         index = d->visibleIndex;
         modelIndex = d->visibleIndex;
     }
     qreal tempPos = d->isRightToLeftTopToBottom() ? -d->position()-d->size()+d->width()+1 : d->position();
     int to = d->buffer+tempPos+d->size()-1;
     int colPos = 0;
     int rowPos = 0;
     if (d->visibleItems.count()) {
         index -= d->visibleIndex;
         if (index < d->visibleItems.count()) {
             colPos = d->visibleItems.at(index)->colPos();
             rowPos = d->visibleItems.at(index)->rowPos();
         } else {
             // appending items to visible list
             colPos = d->visibleItems.at(index-1)->colPos() + d->colSize();
             rowPos = d->visibleItems.at(index-1)->rowPos();
             if (colPos > d->colSize() * (d->columns-1)) {
                 colPos = 0;
                 rowPos += d->rowSize();
             }
         }
     } else if (d->itemCount == 0 && d->header) {
         rowPos = d->headerSize();
     }
     // Update the indexes of the following visible items.
     for (int i = 0; i < d->visibleItems.count(); ++i) {
         FxGridItem *listItem = d->visibleItems.at(i);
         if (listItem->index != -1 && listItem->index >= modelIndex)
             listItem->index += count;
     }
     bool addedVisible = false;
     QList<FxGridItem*> added;
     int i = 0;
     while (i < insertCount && rowPos <= to + d->rowSize()*(d->columns - (colPos/d->colSize()))/qreal(d->columns+1)) {
         if (!addedVisible) {
             d->scheduleLayout();
             addedVisible = true;
         }
         FxGridItem *item = d->createItem(modelIndex + i);
         if (!item) {
             // broken or no delegate
             d->clear();
             return;
         }
         d->visibleItems.insert(index, item);
         item->setPosition(colPos, rowPos);
         added.append(item);
         colPos += d->colSize();
         if (colPos > d->colSize() * (d->columns-1)) {
             colPos = 0;
             rowPos += d->rowSize();
         }
         ++index;
         ++i;
     }
     if (i < insertCount) {
         // We didn't insert all our new items, which means anything
         // beyond the current index is not visible - remove it.
         while (d->visibleItems.count() > index) {
             d->releaseItem(d->visibleItems.takeLast());
         }
     }
     // update visibleIndex
     d->visibleIndex = 0;
     for (QList<FxGridItem*>::Iterator it = d->visibleItems.begin(); it != d->visibleItems.end(); ++it) {
         if ((*it)->index != -1) {
             d->visibleIndex = (*it)->index;
             break;
         }
     }
     if (d->itemCount && d->currentIndex >= modelIndex) {
         // adjust current item index
         d->currentIndex += count;
         if (d->currentItem) {
             d->currentItem->index = d->currentIndex;
             d->currentItem->setPosition(d->colPosAt(d->currentIndex), d->rowPosAt(d->currentIndex));
         }
         emit currentIndexChanged();
     } else if (d->itemCount == 0 && (!d->currentIndex || (d->currentIndex < 0 && !d->currentIndexCleared))) {
         setCurrentIndex(0);
     }
     // everything is in order now - emit add() signal
     for (int j = 0; j < added.count(); ++j)
         added.at(j)->attached->emitAdd();
     d->itemCount += count;
     emit countChanged();
 }
itemsMoved
void QDeclarativeGridView::itemsMoved (int from, int to, int count) private slot
Definition at line 3096 of file qdeclarativegridview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeGridView);
     if (!isComponentComplete())
         return;
     QHash<int,FxGridItem*> moved;
     FxGridItem *firstItem = d->firstVisibleItem();
     QList<FxGridItem*>::Iterator it = d->visibleItems.begin();
     while (it != d->visibleItems.end()) {
         FxGridItem *item = *it;
         if (item->index >= from && item->index < from + count) {
             // take the items that are moving
             item->index += (to-from);
             moved.insert(item->index, item);
             it = d->visibleItems.erase(it);
         } else {
             if (item->index > from && item->index != -1) {
                 // move everything after the moved items.
                 item->index -= count;
                 if (item->index < d->visibleIndex)
                     d->visibleIndex = item->index;
             }
             ++it;
         }
     }
     int remaining = count;
     int endIndex = d->visibleIndex;
     it = d->visibleItems.begin();
     while (it != d->visibleItems.end()) {
         FxGridItem *item = *it;
         if (remaining && item->index >= to && item->index < to + count) {
             // place items in the target position, reusing any existing items
             FxGridItem *movedItem = moved.take(item->index);
             if (!movedItem)
                 movedItem = d->createItem(item->index);
             if (!movedItem) {
                 // broken or no delegate
                 d->clear();
                 return;
             }
             it = d->visibleItems.insert(it, movedItem);
             if (it == d->visibleItems.begin() && firstItem)
                 movedItem->setPosition(firstItem->colPos(), firstItem->rowPos());
             ++it;
             --remaining;
         } else {
             if (item->index != -1) {
                 if (item->index >= to) {
                     // update everything after the moved items.
                     item->index += count;
                 }
                 endIndex = item->index;
             }
             ++it;
         }
     }
     // If we have moved items to the end of the visible items
     // then add any existing moved items that we have
     while (FxGridItem *item = moved.take(endIndex+1)) {
         d->visibleItems.append(item);
         ++endIndex;
     }
     // update visibleIndex
     for (it = d->visibleItems.begin(); it != d->visibleItems.end(); ++it) {
         if ((*it)->index != -1) {
             d->visibleIndex = (*it)->index;
             break;
         }
     }
     // Fix current index
     if (d->currentIndex >= 0 && d->currentItem) {
         int oldCurrent = d->currentIndex;
         d->currentIndex = d->model->indexOf(d->currentItem->item, this);
         if (oldCurrent != d->currentIndex) {
             d->currentItem->index = d->currentIndex;
             emit currentIndexChanged();
         }
     }
     // Whatever moved items remain are no longer visible items.
     while (moved.count()) {
         int idx = moved.begin().key();
         FxGridItem *item = moved.take(idx);
         if (d->currentItem && item->item == d->currentItem->item)
             item->setPosition(d->colPosAt(idx), d->rowPosAt(idx));
         d->releaseItem(item);
     }
     d->layout();
 }
itemsRemoved
void QDeclarativeGridView::itemsRemoved (int index, int count) private slot
Definition at line 2992 of file qdeclarativegridview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeGridView);
     if (!isComponentComplete())
         return;
     d->itemCount -= count;
     bool currentRemoved = d->currentIndex >= modelIndex && d->currentIndex < modelIndex + count;
     bool removedVisible = false;
     // Remove the items from the visible list, skipping anything already marked for removal
     QList<FxGridItem*>::Iterator it = d->visibleItems.begin();
     while (it != d->visibleItems.end()) {
         FxGridItem *item = *it;
         if (item->index == -1 || item->index < modelIndex) {
             // already removed, or before removed items
             if (item->index < modelIndex && !removedVisible) {
                 d->scheduleLayout();
                 removedVisible = true;
             }
             ++it;
         } else if (item->index >= modelIndex + count) {
             // after removed items
             item->index -= count;
             ++it;
         } else {
             // removed item
             if (!removedVisible) {
                 d->scheduleLayout();
                 removedVisible = true;
             }
             item->attached->emitRemove();
             if (item->attached->delayRemove()) {
                 item->index = -1;
                 connect(item->attached, SIGNAL(delayRemoveChanged()), this, SLOT(destroyRemoved()), Qt::QueuedConnection);
                 ++it;
             } else {
                 it = d->visibleItems.erase(it);
                 d->releaseItem(item);
             }
         }
     }
     // If we removed items before visible items a layout may be
     // required to ensure item 0 is in the first column.
     if (!removedVisible && modelIndex < d->visibleIndex)
         d->scheduleLayout();
     // fix current
     if (d->currentIndex >= modelIndex + count) {
         d->currentIndex -= count;
         if (d->currentItem)
             d->currentItem->index -= count;
         emit currentIndexChanged();
     } else if (currentRemoved) {
         // current item has been removed.
         d->releaseItem(d->currentItem);
         d->currentItem = 0;
         d->currentIndex = -1;
         if (d->itemCount)
             d->updateCurrent(qMin(modelIndex, d->itemCount-1));
         else
             emit currentIndexChanged();
     }
     // update visibleIndex
     d->visibleIndex = 0;
     for (it = d->visibleItems.begin(); it != d->visibleItems.end(); ++it) {
         if ((*it)->index != -1) {
             d->visibleIndex = (*it)->index;
             break;
         }
     }
     if (removedVisible && d->visibleItems.isEmpty()) {
         d->timeline.clear();
         if (d->itemCount == 0) {
             d->setPosition(0);
             d->updateHeader();
             d->updateFooter();
             update();
         }
     }
     emit countChanged();
 }
keyNavigationWrapsChanged
void QDeclarativeGridView::keyNavigationWrapsChanged () signal
Referenced by setWrapEnabled().
keyPressEvent()
void QDeclarativeGridView::keyPressEvent (QKeyEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QDeclarativeItem.
Definition at line 2383 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     keyPressPreHandler(event);
     if (event->isAccepted())
         return;
     if (d->model && d->model->count() && d->interactive) {
         d->moveReason = QDeclarativeGridViewPrivate::SetIndex;
         int oldCurrent = currentIndex();
         switch (event->key()) {
         case Qt::Key_Up:
             moveCurrentIndexUp();
             break;
         case Qt::Key_Down:
             moveCurrentIndexDown();
             break;
         case Qt::Key_Left:
             moveCurrentIndexLeft();
             break;
         case Qt::Key_Right:
             moveCurrentIndexRight();
             break;
         default:
             break;
         }
         if (oldCurrent != currentIndex()) {
             event->accept();
             return;
         }
     }
     d->moveReason = QDeclarativeGridViewPrivate::Other;
     event->ignore();
     QDeclarativeFlickable::keyPressEvent(event);
 }
layoutDirection()
Qt::LayoutDirection QDeclarativeGridView::layoutDirection () const
Referenced by setHighlightRangeMode(), and setLayoutDirection().
layoutDirectionChanged
void QDeclarativeGridView::layoutDirectionChanged () signal
Referenced by setLayoutDirection().
maxXExtent()
qreal QDeclarativeGridView::maxXExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2338 of file qdeclarativegridview.cpp.
 {
     Q_D(const QDeclarativeGridView);
     if (d->flow == QDeclarativeGridView::LeftToRight)
         return QDeclarativeFlickable::maxXExtent();
     qreal extent;
     qreal highlightStart;
     qreal highlightEnd;
     qreal lastItemPosition = 0;
     if (d->isRightToLeftTopToBottom()){
         highlightStart = d->highlightRangeStartValid ? d->highlightRangeEnd : d->size();
         highlightEnd = d->highlightRangeEndValid ? d->highlightRangeStart : d->size();
         lastItemPosition = d->endPosition();
     } else {
         highlightStart = d->highlightRangeStart;
         highlightEnd = d->highlightRangeEnd;
         lastItemPosition = 0;
         if (d->model && d->model->count())
             lastItemPosition = d->rowPosAt(d->model->count()-1);
     }
     if (!d->model || !d->model->count()) {
         extent = 0;
     } else if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
         extent = -(lastItemPosition - highlightStart);
         if (highlightEnd != highlightStart)
             extent = d->isRightToLeftTopToBottom()
                     ? qMax(extent, -(d->endPosition() - highlightEnd + 1))
                     : qMin(extent, -(d->endPosition() - highlightEnd + 1));
     } else {
         extent = -(d->endPosition() - width());
     }
     if (d->isRightToLeftTopToBottom()) {
         if (d->header)
             extent -= d->header->item->width();
     } else {
         if (d->footer)
             extent -= d->footer->item->width();
     }
     const qreal minX = minXExtent();
     if (extent > minX)
         extent = minX;
     return extent;
 }
maxYExtent()
qreal QDeclarativeGridView::maxYExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2283 of file qdeclarativegridview.cpp.
 {
     Q_D(const QDeclarativeGridView);
     if (d->flow == QDeclarativeGridView::TopToBottom)
         return QDeclarativeFlickable::maxYExtent();
     qreal extent;
     if (!d->model || !d->model->count()) {
         extent = 0;
     } else if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
         extent = -(d->rowPosAt(d->model->count()-1) - d->highlightRangeStart);
         if (d->highlightRangeEnd != d->highlightRangeStart)
             extent = qMin(extent, -(d->endPosition() - d->highlightRangeEnd + 1));
     } else {
         extent = -(d->endPosition() - height());
     }
     if (d->footer)
         extent -= d->footer->item->height();
     const qreal minY = minYExtent();
     if (extent > minY)
         extent = minY;
     return extent;
 }
minXExtent()
qreal QDeclarativeGridView::minXExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2306 of file qdeclarativegridview.cpp.
Referenced by maxXExtent().
 {
     Q_D(const QDeclarativeGridView);
     if (d->flow == QDeclarativeGridView::LeftToRight)
         return QDeclarativeFlickable::minXExtent();
     qreal extent = -d->startPosition();
     qreal highlightStart;
     qreal highlightEnd;
     qreal endPositionFirstItem = 0;
     if (d->isRightToLeftTopToBottom()) {
         if (d->model && d->model->count())
             endPositionFirstItem = d->rowPosAt(d->model->count()-1);
         highlightStart = d->highlightRangeStartValid
                 ? d->highlightRangeStart - (d->lastPosition()-endPositionFirstItem)
                 : d->size() - (d->lastPosition()-endPositionFirstItem);
         highlightEnd = d->highlightRangeEndValid ? d->highlightRangeEnd : d->size();
         if (d->footer && d->visibleItems.count())
             extent += d->footer->item->width();
     } else {
         endPositionFirstItem = d->rowPosAt(0)+d->rowSize();
         highlightStart = d->highlightRangeStart;
         highlightEnd = d->highlightRangeEnd;
         if (d->header && d->visibleItems.count())
             extent += d->header->item->width();
     }
     if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
         extent += d->isRightToLeftTopToBottom() ? -highlightStart : highlightStart;
         extent = qMax(extent, -(endPositionFirstItem - highlightEnd));
     }
     return extent;
 }
minYExtent()
qreal QDeclarativeGridView::minYExtent () const protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2268 of file qdeclarativegridview.cpp.
Referenced by maxYExtent().
 {
     Q_D(const QDeclarativeGridView);
     if (d->flow == QDeclarativeGridView::TopToBottom)
         return QDeclarativeFlickable::minYExtent();
     qreal extent = -d->startPosition();
     if (d->header && d->visibleItems.count())
         extent += d->header->item->height();
     if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange) {
         extent += d->highlightRangeStart;
         extent = qMax(extent, -(d->rowPosAt(0) + d->rowSize() - d->highlightRangeEnd));
     }
     return extent;
 }
model()
QVariant QDeclarativeGridView::model () const
Referenced by QDeclarativeGridViewPrivate::positionViewAtIndex(), setModel(), and ~QDeclarativeGridView().
modelChanged
void QDeclarativeGridView::modelChanged () signal
Referenced by setModel().
modelCount()
int QDeclarativeGridView::modelCount () const
Definition at line 1444 of file qdeclarativegridview.cpp.
 {
     Q_D(const QDeclarativeGridView);
     return d->model->count();
 }
modelReset
void QDeclarativeGridView::modelReset () private slot
Definition at line 3193 of file qdeclarativegridview.cpp.
Referenced by setModel().
 {
     Q_D(QDeclarativeGridView);
     d->clear();
     refill();
     d->moveReason = QDeclarativeGridViewPrivate::SetIndex;
     d->updateCurrent(d->currentIndex);
     if (d->highlight && d->currentItem) {
         if (d->autoHighlight)
             d->highlight->setPosition(d->currentItem->colPos(), d->currentItem->rowPos());
         d->updateTrackedItem();
     }
     d->moveReason = QDeclarativeGridViewPrivate::Other;
     emit countChanged();
 }
moveCurrentIndexDown
void QDeclarativeGridView::moveCurrentIndexDown () slot
Definition at line 2461 of file qdeclarativegridview.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDeclarativeGridView);
     const int count = d->model ? d->model->count() : 0;
     if (!count)
         return;
     if (d->flow == QDeclarativeGridView::LeftToRight) {
         if (currentIndex() < count - d->columns || d->wrap) {
             int index = currentIndex()+d->columns;
             setCurrentIndex((index >= 0 && index < count) ? index : 0);
         }
     } else {
         if (currentIndex() < count - 1 || d->wrap) {
             int index = currentIndex() + 1;
             setCurrentIndex((index >= 0 && index < count) ? index : 0);
         }
     }
 }
moveCurrentIndexLeft
void QDeclarativeGridView::moveCurrentIndexLeft () slot
Definition at line 2492 of file qdeclarativegridview.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDeclarativeGridView);
     const int count = d->model ? d->model->count() : 0;
     if (!count)
         return;
     if (effectiveLayoutDirection() == Qt::LeftToRight) {
         if (d->flow == QDeclarativeGridView::LeftToRight) {
             if (currentIndex() > 0 || d->wrap) {
                 int index = currentIndex() - 1;
                 setCurrentIndex((index >= 0 && index < count) ? index : count-1);
             }
         } else {
             if (currentIndex() >= d->columns || d->wrap) {
                 int index = currentIndex() - d->columns;
                 setCurrentIndex((index >= 0 && index < count) ? index : count-1);
             }
         }
     } else {
         if (d->flow == QDeclarativeGridView::LeftToRight) {
             if (currentIndex() < count - 1 || d->wrap) {
                 int index = currentIndex() + 1;
                 setCurrentIndex((index >= 0 && index < count) ? index : 0);
             }
         } else {
             if (currentIndex() < count - d->columns || d->wrap) {
                 int index = currentIndex() + d->columns;
                 setCurrentIndex((index >= 0 && index < count) ? index : 0);
             }
         }
     }
 }
moveCurrentIndexRight
void QDeclarativeGridView::moveCurrentIndexRight () slot
Definition at line 2538 of file qdeclarativegridview.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDeclarativeGridView);
     const int count = d->model ? d->model->count() : 0;
     if (!count)
         return;
     if (effectiveLayoutDirection() == Qt::LeftToRight) {
         if (d->flow == QDeclarativeGridView::LeftToRight) {
             if (currentIndex() < count - 1 || d->wrap) {
                 int index = currentIndex() + 1;
                 setCurrentIndex((index >= 0 && index < count) ? index : 0);
             }
         } else {
             if (currentIndex() < count - d->columns || d->wrap) {
                 int index = currentIndex()+d->columns;
                 setCurrentIndex((index >= 0 && index < count) ? index : 0);
             }
         }
     } else {
         if (d->flow == QDeclarativeGridView::LeftToRight) {
             if (currentIndex() > 0 || d->wrap) {
                 int index = currentIndex() - 1;
                 setCurrentIndex((index >= 0 && index < count) ? index : count-1);
             }
         } else {
             if (currentIndex() >= d->columns || d->wrap) {
                 int index = currentIndex() - d->columns;
                 setCurrentIndex((index >= 0 && index < count) ? index : count-1);
             }
         }
     }
 }
moveCurrentIndexUp
void QDeclarativeGridView::moveCurrentIndexUp () slot
Definition at line 2430 of file qdeclarativegridview.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QDeclarativeGridView);
     const int count = d->model ? d->model->count() : 0;
     if (!count)
         return;
     if (d->flow == QDeclarativeGridView::LeftToRight) {
         if (currentIndex() >= d->columns || d->wrap) {
             int index = currentIndex() - d->columns;
             setCurrentIndex((index >= 0 && index < count) ? index : count-1);
         }
     } else {
         if (currentIndex() > 0 || d->wrap) {
             int index = currentIndex() - 1;
             setCurrentIndex((index >= 0 && index < count) ? index : count-1);
         }
     }
 }
positionViewAtBeginning()
void QDeclarativeGridView::positionViewAtBeginning ()
Definition at line 2723 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (!d->isValid())
         return;
     d->positionViewAtIndex(-1, Beginning);
 }
positionViewAtEnd()
void QDeclarativeGridView::positionViewAtEnd ()
Definition at line 2731 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (!d->isValid())
         return;
     d->positionViewAtIndex(d->model->count(), End);
 }
positionViewAtIndex()
void QDeclarativeGridView::positionViewAtIndex (int index, int mode)
Definition at line 2692 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (!d->isValid() || index < 0 || index >= d->model->count())
         return;
     d->positionViewAtIndex(index, mode);
 }
preferredHighlightBegin()
qreal QDeclarativeGridView::preferredHighlightBegin () const
Referenced by setHighlightMoveDuration().
preferredHighlightBeginChanged
void QDeclarativeGridView::preferredHighlightBeginChanged () signal
Referenced by resetPreferredHighlightBegin(), and setPreferredHighlightBegin().
preferredHighlightEnd()
qreal QDeclarativeGridView::preferredHighlightEnd () const
Referenced by resetPreferredHighlightBegin().
preferredHighlightEndChanged
void QDeclarativeGridView::preferredHighlightEndChanged () signal
Referenced by resetPreferredHighlightEnd(), and setPreferredHighlightEnd().
qmlAttachedProperties()
QDeclarativeGridViewAttached * QDeclarativeGridView::qmlAttachedProperties (QObject * obj) static
Definition at line 3248 of file qdeclarativegridview.cpp.
 {
     return new QDeclarativeGridViewAttached(obj);
 }
refill()
void QDeclarativeGridView::refill () private
Definition at line 3238 of file qdeclarativegridview.cpp.
Referenced by componentComplete(), modelReset(), setCacheBuffer(), setDelegate(), setModel(), and viewportMoved().
 {
     Q_D(QDeclarativeGridView);
     if (d->isRightToLeftTopToBottom())
         d->refill(-d->position()-d->size()+1, -d->position());
     else
         d->refill(d->position(), d->position()+d->size()-1);
 }
resetPreferredHighlightBegin()
void QDeclarativeGridView::resetPreferredHighlightBegin ()
Definition at line 1812 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     d->highlightRangeStartValid = false;
     if (d->highlightRangeStart == 0)
         return;
     d->highlightRangeStart = 0;
     emit preferredHighlightBeginChanged();
 }
resetPreferredHighlightEnd()
void QDeclarativeGridView::resetPreferredHighlightEnd ()
Definition at line 1839 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     d->highlightRangeEndValid = false;
     if (d->highlightRangeEnd == 0)
         return;
     d->highlightRangeEnd = 0;
     emit preferredHighlightEndChanged();
 }
setCacheBuffer()
void QDeclarativeGridView::setCacheBuffer (int buffer)
Definition at line 2009 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->buffer != buffer) {
         d->buffer = buffer;
         if (isComponentComplete())
             refill();
         emit cacheBufferChanged();
     }
 }
setCellHeight()
void QDeclarativeGridView::setCellHeight (int cellHeight)
Definition at line 2054 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (cellHeight != d->cellHeight && cellHeight > 0) {
         d->cellHeight = qMax(1, cellHeight);
         d->updateGrid();
         emit cellHeightChanged();
         d->layout();
     }
 }
setCellWidth()
void QDeclarativeGridView::setCellWidth (int cellWidth)
Definition at line 2037 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (cellWidth != d->cellWidth && cellWidth > 0) {
         d->cellWidth = qMax(1, cellWidth);
         d->updateGrid();
         emit cellWidthChanged();
         d->layout();
     }
 }
setContentX()
void QDeclarativeGridView::setContentX (qreal pos) virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2177 of file qdeclarativegridview.cpp.
Referenced by setFlow().
 {
     Q_D(QDeclarativeGridView);
     // Positioning the view manually should override any current movement state
     d->moveReason = QDeclarativeGridViewPrivate::Other;
     QDeclarativeFlickable::setContentX(pos);
 }
setContentY()
void QDeclarativeGridView::setContentY (qreal pos) virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2185 of file qdeclarativegridview.cpp.
Referenced by setFlow().
 {
     Q_D(QDeclarativeGridView);
     // Positioning the view manually should override any current movement state
     d->moveReason = QDeclarativeGridViewPrivate::Other;
     QDeclarativeFlickable::setContentY(pos);
 }
setCurrentIndex()
void QDeclarativeGridView::setCurrentIndex (int idx)
Definition at line 1600 of file qdeclarativegridview.cpp.
Referenced by itemsInserted(), moveCurrentIndexDown(), moveCurrentIndexLeft(), moveCurrentIndexRight(), moveCurrentIndexUp(), and setModel().
 {
     Q_D(QDeclarativeGridView);
     if (d->requestedIndex >= 0) // currently creating item
         return;
     d->currentIndexCleared = (index == -1);
     if (index == d->currentIndex)
         return;
     if (isComponentComplete() && d->isValid()) {
         if (d->layoutScheduled)
             d->layout();
         d->moveReason = QDeclarativeGridViewPrivate::SetIndex;
         d->updateCurrent(index);
     } else {
         d->currentIndex = index;
         emit currentIndexChanged();
     }
 }
setDelegate()
void QDeclarativeGridView::setDelegate (QDeclarativeComponent * delegate)
Definition at line 1541 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (delegate == this->delegate())
         return;
     if (!d->ownModel) {
         d->model = new QDeclarativeVisualDataModel(qmlContext(this));
         d->ownModel = true;
     }
     if (QDeclarativeVisualDataModel *dataModel = qobject_cast<QDeclarativeVisualDataModel*>(d->model)) {
         int oldCount = dataModel->count();
         dataModel->setDelegate(delegate);
         if (isComponentComplete()) {
             for (int i = 0; i < d->visibleItems.count(); ++i)
                 d->releaseItem(d->visibleItems.at(i));
             d->visibleItems.clear();
             d->releaseItem(d->currentItem);
             d->currentItem = 0;
             refill();
             d->moveReason = QDeclarativeGridViewPrivate::SetIndex;
             d->updateCurrent(d->currentIndex);
             if (d->highlight && d->currentItem) {
                 if (d->autoHighlight)
                     d->highlight->setPosition(d->currentItem->colPos(), d->currentItem->rowPos());
                 d->updateTrackedItem();
             }
             d->moveReason = QDeclarativeGridViewPrivate::Other;
         }
         if (oldCount != dataModel->count())
             emit countChanged();
         emit delegateChanged();
     }
 }
setFlow()
void QDeclarativeGridView::setFlow (Flow flow)
Definition at line 1934 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->flow != flow) {
         d->flow = flow;
         if (d->flow == LeftToRight) {
             setContentWidth(-1);
             setFlickableDirection(QDeclarativeFlickable::VerticalFlick);
         } else {
             setContentHeight(-1);
             setFlickableDirection(QDeclarativeFlickable::HorizontalFlick);
         }
         setContentX(0);
         setContentY(0);
         d->regenerate();
         emit flowChanged();
     }
 }
setFooter()
void QDeclarativeGridView::setFooter (QDeclarativeComponent * footer)
Definition at line 2116 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->footerComponent != footer) {
         if (d->footer) {
             if (scene())
                 scene()->removeItem(d->footer->item);
             d->footer->item->deleteLater();
             delete d->footer;
             d->footer = 0;
         }
         d->footerComponent = footer;
         if (isComponentComplete()) {
             d->updateFooter();
             d->updateGrid();
             d->fixupPosition();
         }
         emit footerChanged();
     }
 }
setHeader()
void QDeclarativeGridView::setHeader (QDeclarativeComponent * header)
Definition at line 2155 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->headerComponent != header) {
         if (d->header) {
             if (scene())
                 scene()->removeItem(d->header->item);
             d->header->item->deleteLater();
             delete d->header;
             d->header = 0;
         }
         d->headerComponent = header;
         if (isComponentComplete()) {
             d->updateHeader();
             d->updateFooter();
             d->updateGrid();
             d->fixupPosition();
         }
         emit headerChanged();
     }
 }
setHighlight()
void QDeclarativeGridView::setHighlight (QDeclarativeComponent * highlight)
Definition at line 1682 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (highlight != d->highlightComponent) {
         d->highlightComponent = highlight;
         d->updateCurrent(d->currentIndex);
         emit highlightChanged();
     }
 }
setHighlightFollowsCurrentItem()
void QDeclarativeGridView::setHighlightFollowsCurrentItem (bool autoHighlight)
Definition at line 1714 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->autoHighlight != autoHighlight) {
         d->autoHighlight = autoHighlight;
         if (autoHighlight) {
             d->updateHighlight();
         } else if (d->highlightXAnimator) {
             d->highlightXAnimator->stop();
             d->highlightYAnimator->stop();
         }
     }
 }
setHighlightMoveDuration()
void QDeclarativeGridView::setHighlightMoveDuration (int duration)
Definition at line 1748 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->highlightMoveDuration != duration) {
         d->highlightMoveDuration = duration;
         if (d->highlightYAnimator) {
             d->highlightXAnimator->userDuration = d->highlightMoveDuration;
             d->highlightYAnimator->userDuration = d->highlightMoveDuration;
         }
         emit highlightMoveDurationChanged();
     }
 }
setHighlightRangeMode()
void QDeclarativeGridView::setHighlightRangeMode (HighlightRangeMode mode)
Definition at line 1855 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->highlightRange == mode)
         return;
     d->highlightRange = mode;
     d->haveHighlightRange = d->highlightRange != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     emit highlightRangeModeChanged();
 }
setLayoutDirection()
void QDeclarativeGridView::setLayoutDirection (Qt::LayoutDirection layoutDirection)
Definition at line 1895 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->layoutDirection != layoutDirection) {
         d->layoutDirection = layoutDirection;
         d->regenerate();
         emit layoutDirectionChanged();
     }
 }
setModel()
void QDeclarativeGridView::setModel (const QVariant & model)
Definition at line 1450 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->modelVariant == model)
         return;
     if (d->model) {
         disconnect(d->model, SIGNAL(itemsInserted(int,int)), this, SLOT(itemsInserted(int,int)));
         disconnect(d->model, SIGNAL(itemsRemoved(int,int)), this, SLOT(itemsRemoved(int,int)));
         disconnect(d->model, SIGNAL(itemsMoved(int,int,int)), this, SLOT(itemsMoved(int,int,int)));
         disconnect(d->model, SIGNAL(modelReset()), this, SLOT(modelReset()));
         disconnect(d->model, SIGNAL(createdItem(int,QDeclarativeItem*)), this, SLOT(createdItem(int,QDeclarativeItem*)));
         disconnect(d->model, SIGNAL(destroyingItem(QDeclarativeItem*)), this, SLOT(destroyingItem(QDeclarativeItem*)));
     }
     d->clear();
     d->modelVariant = model;
     QObject *object = qvariant_cast<QObject*>(model);
     QDeclarativeVisualModel *vim = 0;
     if (object && (vim = qobject_cast<QDeclarativeVisualModel *>(object))) {
         if (d->ownModel) {
             delete d->model;
             d->ownModel = false;
         }
         d->model = vim;
     } else {
         if (!d->ownModel) {
             d->model = new QDeclarativeVisualDataModel(qmlContext(this), this);
             d->ownModel = true;
         }
         if (QDeclarativeVisualDataModel *dataModel = qobject_cast<QDeclarativeVisualDataModel*>(d->model))
             dataModel->setModel(model);
     }
     if (d->model) {
         d->bufferMode = QDeclarativeGridViewPrivate::BufferBefore | QDeclarativeGridViewPrivate::BufferAfter;
         if (isComponentComplete()) {
             refill();
             if ((d->currentIndex >= d->model->count() || d->currentIndex < 0) && !d->currentIndexCleared) {
                 setCurrentIndex(0);
             } else {
                 d->moveReason = QDeclarativeGridViewPrivate::SetIndex;
                 d->updateCurrent(d->currentIndex);
                 if (d->highlight && d->currentItem) {
                     if (d->autoHighlight)
                         d->highlight->setPosition(d->currentItem->colPos(), d->currentItem->rowPos());
                     d->updateTrackedItem();
                 }
                 d->moveReason = QDeclarativeGridViewPrivate::Other;
             }
         }
         connect(d->model, SIGNAL(itemsInserted(int,int)), this, SLOT(itemsInserted(int,int)));
         connect(d->model, SIGNAL(itemsRemoved(int,int)), this, SLOT(itemsRemoved(int,int)));
         connect(d->model, SIGNAL(itemsMoved(int,int,int)), this, SLOT(itemsMoved(int,int,int)));
         connect(d->model, SIGNAL(modelReset()), this, SLOT(modelReset()));
         connect(d->model, SIGNAL(createdItem(int,QDeclarativeItem*)), this, SLOT(createdItem(int,QDeclarativeItem*)));
         connect(d->model, SIGNAL(destroyingItem(QDeclarativeItem*)), this, SLOT(destroyingItem(QDeclarativeItem*)));
         emit countChanged();
     }
     emit modelChanged();
 }
setPreferredHighlightBegin()
void QDeclarativeGridView::setPreferredHighlightBegin (qreal start)
Definition at line 1801 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     d->highlightRangeStartValid = true;
     if (d->highlightRangeStart == start)
         return;
     d->highlightRangeStart = start;
     d->haveHighlightRange = d->highlightRange != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     emit preferredHighlightBeginChanged();
 }
setPreferredHighlightEnd()
void QDeclarativeGridView::setPreferredHighlightEnd (qreal end)
Definition at line 1828 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     d->highlightRangeEndValid = true;
     if (d->highlightRangeEnd == end)
         return;
     d->highlightRangeEnd = end;
     d->haveHighlightRange = d->highlightRange != NoHighlightRange && d->highlightRangeStart <= d->highlightRangeEnd;
     emit preferredHighlightEndChanged();
 }
setSnapMode()
void QDeclarativeGridView::setSnapMode (SnapMode mode)
Definition at line 2089 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->snapMode != mode) {
         d->snapMode = mode;
         emit snapModeChanged();
     }
 }
setWrapEnabled()
void QDeclarativeGridView::setWrapEnabled (bool wrap)
Definition at line 1972 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (d->wrap == wrap)
         return;
     d->wrap = wrap;
     emit keyNavigationWrapsChanged();
 }
snapMode()
SnapMode QDeclarativeGridView::snapMode () const
Referenced by setCellHeight().
snapModeChanged
void QDeclarativeGridView::snapModeChanged () signal
Referenced by setSnapMode().
trackedPositionChanged
void QDeclarativeGridView::trackedPositionChanged () private slot
Definition at line 2790 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     if (!d->trackedItem || !d->currentItem)
         return;
     if (d->moveReason == QDeclarativeGridViewPrivate::SetIndex) {
         const qreal trackedPos = d->trackedItem->rowPos();
         qreal viewPos;
         qreal highlightStart;
         qreal highlightEnd;
         if (d->isRightToLeftTopToBottom()) {
             viewPos = -d->position()-d->size();
             highlightStart = d->highlightRangeStartValid ? d->size()-d->highlightRangeEnd : d->highlightRangeStart;
             highlightEnd = d->highlightRangeEndValid ? d->size()-d->highlightRangeStart : d->highlightRangeEnd;
         } else {
             viewPos = d->position();
             highlightStart = d->highlightRangeStart;
             highlightEnd = d->highlightRangeEnd;
         }
         qreal pos = viewPos;
         if (d->haveHighlightRange) {
             if (d->highlightRange == StrictlyEnforceRange) {
                 if (trackedPos > pos + highlightEnd - d->rowSize())
                     pos = trackedPos - highlightEnd + d->rowSize();
                 if (trackedPos < pos + highlightStart)
                     pos = trackedPos - highlightStart;
             } else {
                 if (trackedPos < d->startPosition() + highlightStart) {
                     pos = d->startPosition();
                 } else if (d->trackedItem->endRowPos() > d->endPosition() - d->size() + highlightEnd) {
                     pos = d->endPosition() - d->size() + 1;
                     if (pos < d->startPosition())
                         pos = d->startPosition();
                 } else {
                     if (trackedPos < viewPos + highlightStart) {
                         pos = trackedPos - highlightStart;
                     } else if (trackedPos > viewPos + highlightEnd - d->rowSize()) {
                         pos = trackedPos - highlightEnd + d->rowSize();
                     }
                 }
             }
         } else {
             if (trackedPos < viewPos && d->currentItem->rowPos() < viewPos) {
                 pos = qMax(trackedPos, d->currentItem->rowPos());
             } else if (d->trackedItem->endRowPos() >= viewPos + d->size()
                 && d->currentItem->endRowPos() >= viewPos + d->size()) {
                 if (d->trackedItem->endRowPos() <= d->currentItem->endRowPos()) {
                     pos = d->trackedItem->endRowPos() - d->size() + 1;
                     if (d->rowSize() > d->size())
                         pos = trackedPos;
                 } else {
                     pos = d->currentItem->endRowPos() - d->size() + 1;
                     if (d->rowSize() > d->size())
                         pos = d->currentItem->rowPos();
                 }
             }
         }
         if (viewPos != pos) {
             cancelFlick();
             d->calcVelocity = true;
             d->setPosition(pos);
             d->calcVelocity = false;
         }
     }
 }
viewportMoved()
void QDeclarativeGridView::viewportMoved () protected virtual
Reimplemented from QDeclarativeFlickable.
Definition at line 2205 of file qdeclarativegridview.cpp.
 {
     Q_D(QDeclarativeGridView);
     QDeclarativeFlickable::viewportMoved();
     if (!d->itemCount)
         return;
     d->lazyRelease = true;
     if (d->hData.flicking || d->vData.flicking) {
         if (yflick()) {
             if (d->vData.velocity > 0)
                 d->bufferMode = QDeclarativeGridViewPrivate::BufferBefore;
             else if (d->vData.velocity < 0)
                 d->bufferMode = QDeclarativeGridViewPrivate::BufferAfter;
         }
         if (xflick()) {
             if (d->hData.velocity > 0)
                 d->bufferMode = QDeclarativeGridViewPrivate::BufferBefore;
             else if (d->hData.velocity < 0)
                 d->bufferMode = QDeclarativeGridViewPrivate::BufferAfter;
         }
     }
     refill();
     if (d->hData.flicking || d->vData.flicking || d->hData.moving || d->vData.moving)
         d->moveReason = QDeclarativeGridViewPrivate::Mouse;
     if (d->moveReason != QDeclarativeGridViewPrivate::SetIndex) {
         if (d->haveHighlightRange && d->highlightRange == StrictlyEnforceRange && d->highlight) {
             // reposition highlight
             qreal pos = d->highlight->rowPos();
             qreal viewPos;
             qreal highlightStart;
             qreal highlightEnd;
             if (d->isRightToLeftTopToBottom()) {
                 highlightStart = d->highlightRangeStartValid ? d->size()-d->highlightRangeEnd : d->highlightRangeStart;
                 highlightEnd = d->highlightRangeEndValid ? d->size()-d->highlightRangeStart : d->highlightRangeEnd;
                 viewPos = -d->position()-d->size();
             } else {
                 highlightStart = d->highlightRangeStart;
                 highlightEnd = d->highlightRangeEnd;
                 viewPos = d->position();
             }
             if (pos > viewPos + highlightEnd - d->rowSize())
                 pos = viewPos + highlightEnd - d->rowSize();
             if (pos < viewPos + highlightStart)
                 pos = viewPos + highlightStart;
             d->highlight->setPosition(d->highlight->colPos(), qRound(pos));
             // update current index
             int idx = d->snapIndex();
             if (idx >= 0 && idx != d->currentIndex) {
                 d->updateCurrent(idx);
                 if (d->currentItem && d->currentItem->colPos() != d->highlight->colPos() && d->autoHighlight) {
                     if (d->flow == LeftToRight)
                         d->highlightXAnimator->to = d->currentItem->item->x();
                     else
                         d->highlightYAnimator->to = d->currentItem->item->y();
                 }
             }
         }
     }
 }
Properties
cacheBuffer
int QDeclarativeGridView::cacheBuffer private
Definition at line 79 of file qdeclarativegridview_p.h.
cellHeight
int QDeclarativeGridView::cellHeight private
Definition at line 81 of file qdeclarativegridview_p.h.
Referenced by FxGridItem::contains(), and FxGridItem::endRowPos().
cellWidth
int QDeclarativeGridView::cellWidth private
Definition at line 80 of file qdeclarativegridview_p.h.
Referenced by FxGridItem::colPos(), FxGridItem::contains(), FxGridItem::endRowPos(), FxGridItem::rowPos(), and FxGridItem::setPosition().
count
int QDeclarativeGridView::count private
Definition at line 65 of file qdeclarativegridview_p.h.
currentIndex
int QDeclarativeGridView::currentIndex private
Definition at line 63 of file qdeclarativegridview_p.h.
currentItem
QDeclarativeItem * QDeclarativeGridView::currentItem private
Definition at line 64 of file qdeclarativegridview_p.h.
delegate
QDeclarativeComponent * QDeclarativeGridView::delegate private
Definition at line 62 of file qdeclarativegridview_p.h.
flow
QDeclarativeGridView::Flow QDeclarativeGridView::flow private
Definition at line 76 of file qdeclarativegridview_p.h.
Referenced by FxGridItem::colPos(), FxGridItem::endRowPos(), FxGridItem::rowPos(), and FxGridItem::setPosition().
footer
QDeclarativeComponent * QDeclarativeGridView::footer private
Definition at line 86 of file qdeclarativegridview_p.h.
header
QDeclarativeComponent * QDeclarativeGridView::header private
Definition at line 85 of file qdeclarativegridview_p.h.
highlight
QDeclarativeComponent * QDeclarativeGridView::highlight private
Definition at line 67 of file qdeclarativegridview_p.h.
highlightFollowsCurrentItem
bool QDeclarativeGridView::highlightFollowsCurrentItem private
Definition at line 69 of file qdeclarativegridview_p.h.
highlightItem
QDeclarativeItem * QDeclarativeGridView::highlightItem private
Definition at line 68 of file qdeclarativegridview_p.h.
highlightMoveDuration
int QDeclarativeGridView::highlightMoveDuration private
Definition at line 70 of file qdeclarativegridview_p.h.
highlightRangeMode
QDeclarativeGridView::HighlightRangeMode QDeclarativeGridView::highlightRangeMode private
Definition at line 74 of file qdeclarativegridview_p.h.
keyNavigationWraps
bool QDeclarativeGridView::keyNavigationWraps private
Definition at line 78 of file qdeclarativegridview_p.h.
layoutDirection
Qt::LayoutDirection QDeclarativeGridView::layoutDirection private
Definition at line 77 of file qdeclarativegridview_p.h.
model
QVariant QDeclarativeGridView::model private
Definition at line 61 of file qdeclarativegridview_p.h.
preferredHighlightBegin
qreal QDeclarativeGridView::preferredHighlightBegin private
Definition at line 72 of file qdeclarativegridview_p.h.
preferredHighlightEnd
qreal QDeclarativeGridView::preferredHighlightEnd private
Definition at line 73 of file qdeclarativegridview_p.h.
snapMode
QDeclarativeGridView::SnapMode QDeclarativeGridView::snapMode private
Definition at line 83 of file qdeclarativegridview_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativegridview_p.h
/src/declarative/graphicsitems/qdeclarativegridview.cpp