Qt 4.8: QAudioFormat Class Reference
QAudioFormat Class Reference
The QAudioFormat class stores audio parameter information.
#include <qaudioformat.h>
Public Types
enum Endian { BigEndian = QSysInfo::BigEndian, LittleEndian = QSysInfo::LittleEndian }
enum SampleType { Unknown, SignedInt, UnSignedInt, Float }
Public Functions
QAudioFormat::Endian byteOrder () const
Returns the current byteOrder value.
int channelCount () const
Returns the current channel count value.
int channels () const
Use channelCount() instead.
QString codec () const
Returns the current codec value.
int frequency () const
Use sampleRate() instead.
bool isValid () const
Returns true if all of the parameters are valid.
bool operator!= (const QAudioFormat &other) const
Returns true if this QAudioFormat is not equal to the other QAudioFormat; otherwise returns false.
QAudioFormat & operator= (const QAudioFormat &other)
Assigns other to this QAudioFormat implementation.
bool operator== (const QAudioFormat &other) const
Returns true if this QAudioFormat is equal to the other QAudioFormat; otherwise returns false.
QAudioFormat ()
Construct a new audio format.
QAudioFormat (const QAudioFormat &other)
Construct a new audio format using other.
int sampleRate () const
Returns the current sample rate in Hertz.
int sampleSize () const
Returns the current sample size value.
QAudioFormat::SampleType sampleType () const
Returns the current SampleType value.
void setByteOrder (QAudioFormat::Endian byteOrder)
Sets the byteOrder to byteOrder.
void setChannelCount (int channelCount)
Sets the channel count to channels.
void setChannels (int channels)
Use setChannelCount() instead.
void setCodec (const QString &codec)
Sets the codec to codec.
void setFrequency (int frequency)
Use setSampleRate() instead.
void setSampleRate (int sampleRate)
Sets the sample rate to samplerate Hertz.
void setSampleSize (int sampleSize)
Sets the sample size to the sampleSize specified.
void setSampleType (QAudioFormat::SampleType sampleType)
Sets the sampleType to sampleType.
~QAudioFormat ()
Destroy this audio format.
Properties
QSharedDataPointer< QAudioFormatPrivate > d
Detailed Description
The QAudioFormat class stores audio parameter information.
Attention
Module: QtMultimedia
Since
4.6
An audio format specifies how data in an audio stream is arranged, i.e, how the stream is to be interpreted. The encoding itself is specified by the codec() used for the stream.
In addition to the encoding, QAudioFormat contains other parameters that further specify how the audio data is arranged. These are the frequency, the number of channels, the sample size, the sample type, and the byte order. The following table describes these in more detail.
Parameter Description
Sample Rate Samples per second of audio data in Hertz.
Number of channels The number of audio channels (typically one for mono or two for stereo)
Sample size How much data is stored in each sample (typically 8 or 16 bits)
Sample type Numerical representation of sample (typically signed integer, unsigned integer or float)
Byte order Byte ordering of sample (typically little endian, big endian)
You can obtain audio formats compatible with the audio device used through functions in QAudioDeviceInfo. This class also lets you query available parameter values for a device, so that you can set the parameters yourself. See the QAudioDeviceInfo class description for details. You need to know the format of the audio streams you wish to play. Qt does not set up formats for you.
Definition at line 60 of file qaudioformat.h.
Enumerations
Endian
enum QAudioFormat::Endian
BigEndian samples are big endian byte order
LittleEndian samples are little endian byte order
Enumerator
BigEndian
LittleEndian
Definition at line 64 of file qaudioformat.h.
 { BigEndian = QSysInfo::BigEndian, LittleEndian = QSysInfo::LittleEndian };
SampleType
enum QAudioFormat::SampleType
Unknown Not Set
SignedInt samples are signed integers
UnSignedInt samples are unsigned intergers
Float samples are floats
Enumerator
Unknown
SignedInt
UnSignedInt
Float
Definition at line 63 of file qaudioformat.h.
 { Unknown, SignedInt, UnSignedInt, Float };
Constructors and Destructors
QAudioFormat() [1/2]
QAudioFormat::QAudioFormat ()
Construct a new audio format.
Values are initialized as follows:
sampleRate() = -1
channelCount() = -1
sampleSize() = -1
byteOrder() = QAudioFormat::Endian(QSysInfo::ByteOrder)
sampleType() = QAudioFormat::Unknown codec() = ""
Definition at line 158 of file qaudioformat.cpp.
                           :
     d(new QAudioFormatPrivate)
 {
 }
QAudioFormat() [2/2]
QAudioFormat::QAudioFormat (const QAudioFormat & other)
Construct a new audio format using other.
Definition at line 167 of file qaudioformat.cpp.
                                                    :
     d(other.d)
 {
 }
~QAudioFormat()
QAudioFormat::~QAudioFormat ()
Destroy this audio format.
Definition at line 176 of file qaudioformat.cpp.
 {
 }
Functions
byteOrder()
QAudioFormat::Endian QAudioFormat::byteOrder () const
Returns the current byteOrder value.
Definition at line 382 of file qaudioformat.cpp.
Referenced by QAudioOutputPrivate::freeBlocks(), operator<<(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), setByteOrder(), QAudioInputPrivate::setFormat(), QAudioOutputPrivate::setFormat(), QAudioDeviceInfoInternal::testSettings(), and toAudioStreamBasicDescription().
 {
     return d->byteOrder;
 }
channelCount()
int QAudioFormat::channelCount () const
Returns the current channel count value.
Since
4.7
Definition at line 310 of file qaudioformat.cpp.
 {
     return d->channels;
 }
channels()
int QAudioFormat::channels () const
Use channelCount() instead.
Definition at line 324 of file qaudioformat.cpp.
Referenced by QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QAudioInputPrivate::open(), QAudioOutputPrivate::open(), operator<<(), QAudioInputPrivate::processedUSecs(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), QtMultimediaInternal::QAudioOutputBuffer::QAudioOutputBuffer(), setChannelCount(), setChannels(), QAudioDeviceInfoInternal::testSettings(), and toAudioStreamBasicDescription().
 {
     return d->channels;
 }
codec()
QString QAudioFormat::codec () const
Returns the current codec value.
See also
QAudioDeviceInfo::supportedCodecs()
Definition at line 364 of file qaudioformat.cpp.
Referenced by operator<<(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), setCodec(), and QAudioDeviceInfoInternal::testSettings().
 {
     return d->codec;
 }
frequency()
int QAudioFormat::frequency () const
Use sampleRate() instead.
Definition at line 274 of file qaudioformat.cpp.
Referenced by QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QAudioDeviceInfo::nearestFormat(), QAudioInputPrivate::open(), QAudioOutputPrivate::open(), operator<<(), QAudioInputPrivate::processedUSecs(), QAudioOutputPrivate::processedUSecs(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), QtMultimediaInternal::QAudioOutputBuffer::QAudioOutputBuffer(), setFrequency(), QAudioDeviceInfoInternal::testSettings(), and toAudioStreamBasicDescription().
 {
     return d->frequency;
 }
isValid()
bool QAudioFormat::isValid () const
Returns true if all of the parameters are valid.
Definition at line 223 of file qaudioformat.cpp.
Referenced by QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QAudioInputPrivate::open(), QAudioOutputPrivate::open(), and QAudioDeviceInfoInternal::QAudioDeviceInfoInternal().
 {
     return d->frequency != -1 && d->channels != -1 && d->sampleSize != -1 &&
             d->sampleType != QAudioFormat::Unknown && !d->codec.isEmpty();
 }
operator!=()
bool QAudioFormat::operator!= (const QAudioFormat & other) const
Returns true if this QAudioFormat is not equal to the other QAudioFormat; otherwise returns false.
All elements of QAudioFormat are used for the comparison.
Definition at line 214 of file qaudioformat.cpp.
 {
     return !(*this == other);
 }
operator=()
QAudioFormat & QAudioFormat::operator= (const QAudioFormat & other)
Assigns other to this QAudioFormat implementation.
Definition at line 184 of file qaudioformat.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QAudioFormat::operator== (const QAudioFormat & other) const
Returns true if this QAudioFormat is equal to the other QAudioFormat; otherwise returns false.
All elements of QAudioFormat are used for the comparison.
Definition at line 197 of file qaudioformat.cpp.
 {
     return d->frequency == other.d->frequency &&
             d->channels == other.d->channels &&
             d->sampleSize == other.d->sampleSize &&
             d->byteOrder == other.d->byteOrder &&
             d->codec == other.d->codec &&
             d->sampleType == other.d->sampleType;
 }
sampleRate()
int QAudioFormat::sampleRate () const
Returns the current sample rate in Hertz.
Since
4.7
Definition at line 260 of file qaudioformat.cpp.
 {
     return d->frequency;
 }
sampleSize()
int QAudioFormat::sampleSize () const
Returns the current sample size value.
Definition at line 342 of file qaudioformat.cpp.
Referenced by QAudioOutputPrivate::freeBlocks(), QAudioInputPrivate::freeBlocks(), QAudioDeviceInfo::nearestFormat(), operator<<(), QAudioInputPrivate::processedUSecs(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), QtMultimediaInternal::QAudioOutputBuffer::QAudioOutputBuffer(), QAudioInputPrivate::setFormat(), QAudioOutputPrivate::setFormat(), setSampleSize(), QAudioDeviceInfoInternal::testSettings(), and toAudioStreamBasicDescription().
 {
     return d->sampleSize;
 }
sampleType()
QAudioFormat::SampleType QAudioFormat::sampleType () const
Returns the current SampleType value.
Definition at line 400 of file qaudioformat.cpp.
Referenced by QAudioDeviceInfo::nearestFormat(), operator<<(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), QAudioInputPrivate::setFormat(), QAudioOutputPrivate::setFormat(), setSampleType(), QAudioDeviceInfoInternal::testSettings(), and toAudioStreamBasicDescription().
 {
     return d->sampleType;
 }
setByteOrder()
void QAudioFormat::setByteOrder (QAudioFormat::Endian byteOrder)
Sets the byteOrder to byteOrder.
Definition at line 373 of file qaudioformat.cpp.
Referenced by QAudioDeviceInfoInternal::preferredFormat(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), and toQAudioFormat().
 {
     d->byteOrder = byteOrder;
 }
setChannelCount()
void QAudioFormat::setChannelCount (int channels)
Sets the channel count to channels.
Since
4.7
Definition at line 285 of file qaudioformat.cpp.
 {
     d->channels = channels;
 }
setChannels()
void QAudioFormat::setChannels (int channels)
Use setChannelCount() instead.
Definition at line 299 of file qaudioformat.cpp.
Referenced by QAudioDeviceInfoInternal::preferredFormat(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), and toQAudioFormat().
 {
     d->channels = channels;
 }
setCodec()
void QAudioFormat::setCodec (const QString & codec)
Sets the codec to codec.
See also
QAudioDeviceInfo::supportedCodecs()
Definition at line 353 of file qaudioformat.cpp.
Referenced by QAudioDeviceInfo::nearestFormat(), QAudioDeviceInfoInternal::preferredFormat(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), and toQAudioFormat().
 {
     d->codec = codec;
 }
setFrequency()
void QAudioFormat::setFrequency (int frequency)
Use setSampleRate() instead.
Definition at line 249 of file qaudioformat.cpp.
Referenced by QAudioDeviceInfo::nearestFormat(), QAudioDeviceInfoInternal::preferredFormat(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), and toQAudioFormat().
 {
     d->frequency = frequency;
 }
setSampleRate()
void QAudioFormat::setSampleRate (int samplerate)
Sets the sample rate to samplerate Hertz.
Since
4.7
Definition at line 235 of file qaudioformat.cpp.
 {
     d->frequency = samplerate;
 }
setSampleSize()
void QAudioFormat::setSampleSize (int sampleSize)
Sets the sample size to the sampleSize specified.
Definition at line 333 of file qaudioformat.cpp.
Referenced by QAudioDeviceInfo::nearestFormat(), QAudioDeviceInfoInternal::preferredFormat(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), and toQAudioFormat().
 {
     d->sampleSize = sampleSize;
 }
setSampleType()
void QAudioFormat::setSampleType (QAudioFormat::SampleType sampleType)
Sets the sampleType to sampleType.
Definition at line 391 of file qaudioformat.cpp.
Referenced by QAudioDeviceInfo::nearestFormat(), QAudioDeviceInfoInternal::preferredFormat(), QAudioDeviceInfoInternal::QAudioDeviceInfoInternal(), and toQAudioFormat().
 {
     d->sampleType = sampleType;
 }
Properties
d
QSharedDataPointer<QAudioFormatPrivate> QAudioFormat::d private
Definition at line 99 of file qaudioformat.h.
Referenced by byteOrder(), channelCount(), channels(), codec(), frequency(), isValid(), operator=(), operator==(), sampleRate(), sampleSize(), sampleType(), setByteOrder(), setChannelCount(), setChannels(), setCodec(), setFrequency(), setSampleRate(), setSampleSize(), and setSampleType().
The documentation for this class was generated from the following files:
/src/multimedia/audio/qaudioformat.h
/src/multimedia/audio/qaudioformat.cpp