Qt 4.8: QImageReader Class Reference
QImageReader Class Reference
The QImageReader class provides a format independent interface for reading images from files or other devices.
#include <qimagereader.h>
Public Types
enum ImageReaderError {
UnknownError, FileNotFoundError, DeviceError, UnsupportedFormatError,
InvalidDataError
}
This enum describes the different types of errors that can occur when reading images with QImageReader.
Public Functions
bool autoDetectImageFormat () const
Returns true if image format autodetection is enabled on this image reader; otherwise returns false.
QColor backgroundColor () const
Returns the background color that's used when reading an image.
bool canRead () const
Returns true if an image can be read for the device (i.e., the image format is supported, and the device seems to contain valid data); otherwise returns false.
QRect clipRect () const
Returns the clip rect (also known as the ROI, or Region Of Interest) of the image.
int currentImageNumber () const
For image formats that support animation, this function returns the sequence number of the current frame.
QRect currentImageRect () const
For image formats that support animation, this function returns the rect for the current frame.
bool decideFormatFromContent () const
Returns whether the image reader should decide which plugin to use only based on the contents of the datastream rather than on the file extension.
QIODevice * device () const
Returns the device currently assigned to QImageReader, or 0 if no device has been assigned.
ImageReaderError error () const
Returns the type of error that occurred last.
QString errorString () const
Returns a human readable description of the last error that occurred.
QString fileName () const
If the currently assigned device is a QFile, or if setFileName() has been called, this function returns the name of the file QImageReader reads from.
QByteArray format () const
Returns the format QImageReader uses for reading images.
int imageCount () const
For image formats that support animation, this function returns the total number of images in the animation.
QImage::Format imageFormat () const
Returns the format of the image, without actually reading the image contents.
bool jumpToImage (int imageNumber)
For image formats that support animation, this function skips to the image whose sequence number is imageNumber, returning true if successful or false if the corresponding image cannot be found.
bool jumpToNextImage ()
For image formats that support animation, this function steps over the current image, returning true if successful or false if there is no following image in the animation.
int loopCount () const
For image formats that support animation, this function returns the number of times the animation should loop.
int nextImageDelay () const
For image formats that support animation, this function returns the number of milliseconds to wait until displaying the next frame in the animation.
QImageReader ()
Constructs an empty QImageReader object.
QImageReader (QIODevice *device, const QByteArray &format=QByteArray())
Constructs a QImageReader object with the device device and the image format format.
QImageReader (const QString &fileName, const QByteArray &format=QByteArray())
Constructs a QImageReader object with the file name fileName and the image format format.
int quality () const
Returns the quality level of the image.
QImage read ()
Reads an image from the device.
bool read (QImage *image)
Reads an image from the device into image, which must point to a QImage.
QRect scaledClipRect () const
Returns the scaled clip rect of the image.
QSize scaledSize () const
Returns the scaled size of the image.
void setAutoDetectImageFormat (bool enabled)
If enabled is true, image format autodetection is enabled; otherwise, it is disabled.
void setBackgroundColor (const QColor &color)
Sets the background color to color.
void setClipRect (const QRect &rect)
Sets the image clip rect (also known as the ROI, or Region Of Interest) to rect.
void setDecideFormatFromContent (bool ignored)
If ignored is set to true, then the image reader will ignore specified formats or file extensions and decide which plugin to use only based on the contents in the datastream.
void setDevice (QIODevice *device)
Sets QImageReader's device to device.
void setFileName (const QString &fileName)
Sets the file name of QImageReader to fileName.
void setFormat (const QByteArray &format)
Sets the format QImageReader will use when reading images, to format.
void setQuality (int quality)
This is an image format specific function that sets the quality level of the image to quality.
void setScaledClipRect (const QRect &rect)
Sets the scaled clip rect to rect.
void setScaledSize (const QSize &size)
Sets the scaled size of the image to size.
QSize size () const
Returns the size of the image, without actually reading the image contents.
bool supportsAnimation () const
Returns true if the image format supports animation; otherwise, false is returned.
bool supportsOption (QImageIOHandler::ImageOption option) const
Returns true if the reader supports option; otherwise returns false.
QString text (const QString &key) const
Returns the image text associated with key.
QStringList textKeys () const
Returns the text keys for this image.
~QImageReader ()
Destructs the QImageReader object.
Static Public Functions
static QByteArray imageFormat (const QString &fileName)
If supported, this function returns the image format of the file fileName.
static QByteArray imageFormat (QIODevice *device)
If supported, this function returns the image format of the device device.
static QList< QByteArray > supportedImageFormats ()
Returns the list of image formats supported by QImageReader.
Properties
QImageReaderPrivate * d
Detailed Description
The QImageReader class provides a format independent interface for reading images from files or other devices.
Note
This class or function is reentrant.
The most common way to read images is through QImage and QPixmap's constructors, or by calling QImage::load() and QPixmap::load(). QImageReader is a specialized class which gives you more control when reading images. For example, you can read an image into a specific size by calling setScaledSize(), and you can select a clip rect, effectively loading only parts of an image, by calling setClipRect(). Depending on the underlying support in the image format, this can save memory and speed up loading of images.
To read an image, you start by constructing a QImageReader object. Pass either a file name or a device pointer, and the image format to QImageReader's constructor. You can then set several options, such as the clip rect (by calling setClipRect()) and scaled size (by calling setScaledSize()). canRead() returns the image if the QImageReader can read the image (i.e., the image format is supported and the device is open for reading). Call read() to read the image.
If any error occurs when reading the image, read() will return a null QImage. You can then call error() to find the type of error that occurred, or errorString() to get a human readable description of what went wrong.
Call supportedImageFormats() for a list of formats that QImageReader can read. QImageReader supports all built-in image formats, in addition to any image format plugins that support reading.
QImageReader autodetects the image format by default, by looking at the provided (optional) format string, the file name suffix, and the data stream contents. You can enable or disable this feature, by calling setAutoDetectImageFormat().
See also
QImageWriter, QImageIOHandler, QImageIOPlugin
Definition at line 62 of file qimagereader.h.
Enumerations
ImageReaderError
enum QImageReader::ImageReaderError
This enum describes the different types of errors that can occur when reading images with QImageReader.
FileNotFoundError QImageReader was used with a file name, but not file was found with that name. This can also happen if the file name contained no extension, and the file with the correct extension is not supported by Qt.
DeviceError QImageReader encountered a device error when reading the image. You can consult your particular device for more details on what went wrong.
UnsupportedFormatError Qt does not support the requested image format.
InvalidDataError The image data was invalid, and QImageReader was unable to read an image from it. The can happen if the image file is damaged.
UnknownError An unknown error occurred. If you get this value after calling read(), it is most likely caused by a bug in QImageReader.
Enumerator
UnknownError
FileNotFoundError
DeviceError
UnsupportedFormatError
InvalidDataError
Definition at line 65 of file qimagereader.h.
{
         UnknownError,
         FileNotFoundError,
         DeviceError,
         UnsupportedFormatError,
         InvalidDataError
     };
Constructors and Destructors
QImageReader() [1/3]
QImageReader::QImageReader ()
Constructs an empty QImageReader object.
Before reading an image, call setDevice() or setFileName().
Definition at line 655 of file qimagereader.cpp.
     : d(new QImageReaderPrivate(this))
 {
 }
QImageReader() [2/3]
QImageReader::QImageReader (QIODevice * device, const QByteArray & format = QByteArray()) explicit
Constructs a QImageReader object with the device device and the image format format.
Definition at line 664 of file qimagereader.cpp.
     : d(new QImageReaderPrivate(this))
 {
     d->device = device;
     d->format = format;
 }
QImageReader() [3/3]
QImageReader::QImageReader (const QString & fileName, const QByteArray & format = QByteArray()) explicit
Constructs a QImageReader object with the file name fileName and the image format format.
See also
setFileName()
Definition at line 677 of file qimagereader.cpp.
     : d(new QImageReaderPrivate(this))
 {
     QFile *file = new QFile(fileName);
     d->device = file;
     d->deleteDevice = true;
     d->format = format;
 }
~QImageReader()
QImageReader::~QImageReader ()
Destructs the QImageReader object.
Definition at line 689 of file qimagereader.cpp.
 {
     delete d;
 }
Functions
autoDetectImageFormat()
bool QImageReader::autoDetectImageFormat () const
Returns true if image format autodetection is enabled on this image reader; otherwise returns false.
By default, autodetection is enabled.
See also
setAutoDetectImageFormat()
Definition at line 785 of file qimagereader.cpp.
 {
     return d->autoDetectImageFormat;
 }
backgroundColor()
QColor QImageReader::backgroundColor () const
Returns the background color that's used when reading an image.
Since
4.1
If the image format does not support setting the background color an invalid color is returned.
See also
setBackgroundColor(), read()
Definition at line 1116 of file qimagereader.cpp.
Referenced by QMoviePrivate::infoForFrame().
 {
     if (!d->initHandler())
         return QColor();
     if (d->handler->supportsOption(QImageIOHandler::BackgroundColor))
         return qvariant_cast<QColor>(d->handler->option(QImageIOHandler::BackgroundColor));
     return QColor();
 }
canRead()
bool QImageReader::canRead () const
Returns true if an image can be read for the device (i.e., the image format is supported, and the device seems to contain valid data); otherwise returns false.
canRead() is a lightweight function that only does a quick test to see if the image data is valid. read() may still return false after canRead() returns true, if the image data is corrupt.
For images that support animation, canRead() returns false when all frames have been read.
See also
read(), supportedImageFormats()
Definition at line 1159 of file qimagereader.cpp.
Referenced by QMoviePrivate::isValid().
 {
     if (!d->initHandler())
         return false;
     return d->handler->canRead();
 }
clipRect()
QRect QImageReader::clipRect () const
Returns the clip rect (also known as the ROI, or Region Of Interest) of the image.
If no clip rect has been set, an invalid QRect is returned.
See also
setClipRect()
Definition at line 1032 of file qimagereader.cpp.
 {
     return d->clipRect;
 }
currentImageNumber()
int QImageReader::currentImageNumber () const
For image formats that support animation, this function returns the sequence number of the current frame.
If the image format doesn't support animation, 0 is returned.
This function returns -1 if an error occurred.
See also
supportsAnimation(), QImageIOHandler::currentImageNumber(), canRead()
Definition at line 1391 of file qimagereader.cpp.
 {
     if (!d->initHandler())
         return -1;
     return d->handler->currentImageNumber();
 }
currentImageRect()
QRect QImageReader::currentImageRect () const
For image formats that support animation, this function returns the rect for the current frame.
Otherwise, a null rect is returned.
See also
supportsAnimation(), QImageIOHandler::currentImageRect()
Definition at line 1404 of file qimagereader.cpp.
 {
     if (!d->initHandler())
         return QRect();
     return d->handler->currentImageRect();
 }
decideFormatFromContent()
bool QImageReader::decideFormatFromContent () const
Returns whether the image reader should decide which plugin to use only based on the contents of the datastream rather than on the file extension.
See also
setDecideFormatFromContent()
Definition at line 819 of file qimagereader.cpp.
 {
     return d->ignoresFormatAndExtension;
 }
device()
QIODevice * QImageReader::device () const
Returns the device currently assigned to QImageReader, or 0 if no device has been assigned.
Definition at line 853 of file qimagereader.cpp.
Referenced by QMoviePrivate::infoForFrame(), QImageReader(), QMoviePrivate::reset(), and setDevice().
 {
     return d->device;
 }
error()
QImageReader::ImageReaderError QImageReader::error () const
Returns the type of error that occurred last.
See also
ImageReaderError, errorString()
Definition at line 1416 of file qimagereader.cpp.
Referenced by QMoviePrivate::_q_loadNextFrame().
 {
     return d->imageReaderError;
 }
errorString()
QString QImageReader::errorString () const
Returns a human readable description of the last error that occurred.
See also
error()
Definition at line 1427 of file qimagereader.cpp.
Referenced by readImage().
 {
     if (d->errorString.isEmpty())
         return QLatin1String(QT_TRANSLATE_NOOP(QImageReader, "Unknown error"));
     return d->errorString;
 }
fileName()
QString QImageReader::fileName () const
If the currently assigned device is a QFile, or if setFileName() has been called, this function returns the name of the file QImageReader reads from.
Otherwise (i.e., if no device has been assigned or the device is not a QFile), an empty QString is returned.
See also
setFileName(), setDevice()
Definition at line 883 of file qimagereader.cpp.
Referenced by QMoviePrivate::infoForFrame().
 {
     QFile *file = qobject_cast<QFile *>(d->device);
     return file ? file->fileName() : QString();
 }
format()
QByteArray QImageReader::format () const
Returns the format QImageReader uses for reading images.
You can call this function after assigning a device to the reader to determine the format of the device. For example:
QImageReader reader("image.png");
// reader.format() == "png"
If the reader cannot read any image from the device (e.g., there is no image there, or the image has already been read), or if the format is unsupported, this function returns an empty QByteArray().
See also
setFormat(), supportedImageFormats()
Definition at line 724 of file qimagereader.cpp.
Referenced by imageFormat(), QMoviePrivate::infoForFrame(), QImageReader(), and setFormat().
 {
     if (d->format.isEmpty()) {
         if (!d->initHandler())
             return QByteArray();
         return d->handler->canRead() ? d->handler->format() : QByteArray();
     }
     return d->format;
 }
imageCount()
int QImageReader::imageCount () const
For image formats that support animation, this function returns the total number of images in the animation.
If the format does not support animation, 0 is returned.
This function returns -1 if an error occurred.
See also
supportsAnimation(), QImageIOHandler::imageCount(), canRead()
Definition at line 1359 of file qimagereader.cpp.
Referenced by QMoviePrivate::frameCount().
 {
     if (!d->initHandler())
         return -1;
     return d->handler->imageCount();
 }
imageFormat() [1/3]
QImage::Format QImageReader::imageFormat () const
Returns the format of the image, without actually reading the image contents.
Since
4.5
The format describes the image format QImageReader::read() returns, not the format of the actual image.
If the image format does not support this feature, this function returns an invalid format.
See also
QImageIOHandler::ImageOption, QImageIOHandler::option(), QImageIOHandler::supportsOption()
Definition at line 962 of file qimagereader.cpp.
Referenced by imageFormat().
 {
     if (!d->initHandler())
         return QImage::Format_Invalid;
     if (d->handler->supportsOption(QImageIOHandler::ImageFormat))
         return (QImage::Format)d->handler->option(QImageIOHandler::ImageFormat).toInt();
     return QImage::Format_Invalid;
 }
imageFormat() [2/3]
QByteArray QImageReader::imageFormat (const QString & fileName) static
If supported, this function returns the image format of the file fileName.
Otherwise, an empty string is returned.
Definition at line 1464 of file qimagereader.cpp.
 {
     QFile file(fileName);
     if (!file.open(QFile::ReadOnly))
         return QByteArray();
     return imageFormat(&file);
 }
imageFormat() [3/3]
QByteArray QImageReader::imageFormat (QIODevice * device) static
If supported, this function returns the image format of the device device.
Otherwise, an empty string is returned.
See also
QImageReader::autoDetectImageFormat()
Definition at line 1479 of file qimagereader.cpp.
 {
     QByteArray format;
     QImageIOHandler *handler = createReadHandlerHelper(device, format, /* autoDetectImageFormat = */ true, false);
     if (handler) {
         if (handler->canRead())
             format = handler->format();
         delete handler;
     }
     return format;
 }
jumpToImage()
bool QImageReader::jumpToImage (int imageNumber)
For image formats that support animation, this function skips to the image whose sequence number is imageNumber, returning true if successful or false if the corresponding image cannot be found.
The next call to read() will attempt to read this image.
See also
jumpToNextImage(), QImageIOHandler::jumpToImage()
Definition at line 1328 of file qimagereader.cpp.
Referenced by QMoviePrivate::infoForFrame().
 {
     if (!d->initHandler())
         return false;
     return d->handler->jumpToImage(imageNumber);
 }
jumpToNextImage()
bool QImageReader::jumpToNextImage ()
For image formats that support animation, this function steps over the current image, returning true if successful or false if there is no following image in the animation.
The default implementation calls read(), then discards the resulting image, but the image handler may have a more efficient way of implementing this operation.
See also
jumpToImage(), QImageIOHandler::jumpToNextImage()
Definition at line 1312 of file qimagereader.cpp.
 {
     if (!d->initHandler())
         return false;
     return d->handler->jumpToNextImage();
 }
loopCount()
int QImageReader::loopCount () const
For image formats that support animation, this function returns the number of times the animation should loop.
If this function returns -1, it can either mean the animation should loop forever, or that an error occurred. If an error occurred, canRead() will return false.
See also
supportsAnimation(), QImageIOHandler::loopCount(), canRead()
Definition at line 1343 of file qimagereader.cpp.
Referenced by QMoviePrivate::next().
 {
     if (!d->initHandler())
         return -1;
     return d->handler->loopCount();
 }
nextImageDelay()
int QImageReader::nextImageDelay () const
For image formats that support animation, this function returns the number of milliseconds to wait until displaying the next frame in the animation.
If the image format doesn't support animation, 0 is returned.
This function returns -1 if an error occurred.
See also
supportsAnimation(), QImageIOHandler::nextImageDelay(), canRead()
Definition at line 1375 of file qimagereader.cpp.
 {
     if (!d->initHandler())
         return -1;
     return d->handler->nextImageDelay();
 }
quality()
int QImageReader::quality () const
Returns the quality level of the image.
Since
4.2
See also
setQuality()
Definition at line 920 of file qimagereader.cpp.
Referenced by setQuality().
 {
     return d->quality;
 }
read() [1/2]
QImage QImageReader::read ()
Reads an image from the device.
On success, the image that was read is returned; otherwise, a null QImage is returned. You can then call error() to find the type of error that occurred, or errorString() to get a human readable description of the error.
For image formats that support animation, calling read() repeatedly will return the next frame. When all frames have been read, a null image will be returned.
See also
canRead(), supportedImageFormats(), supportsAnimation(), QMovie
Definition at line 1179 of file qimagereader.cpp.
Referenced by QRasterPixmapData::fromData(), QVGPixmapData::fromData(), QPixmapData::fromData(), QGLPixmapData::fromData(), QImage::fromData(), QVGPixmapData::fromFile(), QPixmapData::fromFile(), QGLPixmapData::fromFile(), QRasterPixmapData::fromImageReader(), QVGPixmapData::fromImageReader(), QPixmapData::fromImageReader(), QGLPixmapData::fromImageReader(), QImage::load(), and readImage().
 {
     // Because failed image reading might have side effects, we explicitly
     // return a null image instead of the image we've just created.
     QImage image;
     return read(&image) ? image : QImage();
 }
read() [2/2]
bool QImageReader::read (QImage * image)
Reads an image from the device into image, which must point to a QImage.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true on success; otherwise, returns false.
If image has same format and size as the image data that is about to be read, this function may not need to allocate a new image before reading. Because of this, it can be faster than the other read() overload, which always constructs a new image; especially when reading several images with the same format and size.
QImage icon(64, 64, QImage::Format_RGB32);
QImageReader reader("icon_64x64.bmp");
if (reader.read(&icon)) {
    // Display icon
}
For image formats that support animation, calling read() repeatedly will return the next frame. When all frames have been read, a null image will be returned.
See also
canRead(), supportedImageFormats(), supportsAnimation(), QMovie
Definition at line 1210 of file qimagereader.cpp.
 {
     if (!image) {
         qWarning("QImageReader::read: cannot read into null pointer");
         return false;
     }
     if (!d->handler && !d->initHandler())
         return false;
     // set the handler specific options.
     if (d->handler->supportsOption(QImageIOHandler::ScaledSize) && d->scaledSize.isValid()) {
         if ((d->handler->supportsOption(QImageIOHandler::ClipRect) && !d->clipRect.isNull())
             || d->clipRect.isNull()) {
             // Only enable the ScaledSize option if there is no clip rect, or
             // if the handler also supports ClipRect.
             d->handler->setOption(QImageIOHandler::ScaledSize, d->scaledSize);
         }
     }
     if (d->handler->supportsOption(QImageIOHandler::ClipRect) && !d->clipRect.isNull())
         d->handler->setOption(QImageIOHandler::ClipRect, d->clipRect);
     if (d->handler->supportsOption(QImageIOHandler::ScaledClipRect) && !d->scaledClipRect.isNull())
         d->handler->setOption(QImageIOHandler::ScaledClipRect, d->scaledClipRect);
     if (d->handler->supportsOption(QImageIOHandler::Quality))
         d->handler->setOption(QImageIOHandler::Quality, d->quality);
     // read the image
     if (!d->handler->read(image)) {
         d->imageReaderError = InvalidDataError;
         d->errorString = QLatin1String(QT_TRANSLATE_NOOP(QImageReader, "Unable to read image data"));
         return false;
     }
     // provide default implementations for any unsupported image
     // options
     if (d->handler->supportsOption(QImageIOHandler::ClipRect) && !d->clipRect.isNull()) {
         if (d->handler->supportsOption(QImageIOHandler::ScaledSize) && d->scaledSize.isValid()) {
             if (d->handler->supportsOption(QImageIOHandler::ScaledClipRect) && !d->scaledClipRect.isNull()) {
                 // all features are supported by the handler; nothing to do.
             } else {
                 // the image is already scaled, so apply scaled clipping.
                 if (!d->scaledClipRect.isNull())
                     *image = image->copy(d->scaledClipRect);
             }
         } else {
             if (d->handler->supportsOption(QImageIOHandler::ScaledClipRect) && !d->scaledClipRect.isNull()) {
                 // supports scaled clipping but not scaling, most
                 // likely a broken handler.
             } else {
                 if (d->scaledSize.isValid()) {
                     *image = image->scaled(d->scaledSize, Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
                 }
                 if (d->scaledClipRect.isValid()) {
                     *image = image->copy(d->scaledClipRect);
                 }
             }
         }
     } else {
         if (d->handler->supportsOption(QImageIOHandler::ScaledSize) && d->scaledSize.isValid()) {
             // in this case, there's nothing we can do. if the
             // plugin supports scaled size but not ClipRect, then
             // we have to ignore ClipRect."
             if (d->handler->supportsOption(QImageIOHandler::ScaledClipRect) && !d->scaledClipRect.isNull()) {
                 // nothing to do (ClipRect is ignored!)
             } else {
                 // provide all workarounds.
                 if (d->scaledClipRect.isValid()) {
                     *image = image->copy(d->scaledClipRect);
                 }
             }
         } else {
             if (d->handler->supportsOption(QImageIOHandler::ScaledClipRect) && !d->scaledClipRect.isNull()) {
                 // this makes no sense; a handler that supports
                 // ScaledClipRect but not ScaledSize is broken, and we
                 // can't work around it.
             } else {
                 // provide all workarounds.
                 if (d->clipRect.isValid())
                     *image = image->copy(d->clipRect);
                 if (d->scaledSize.isValid())
                     *image = image->scaled(d->scaledSize, Qt::IgnoreAspectRatio, Qt::SmoothTransformation);
                 if (d->scaledClipRect.isValid())
                     *image = image->copy(d->scaledClipRect);
             }
         }
     }
     return true;
 }
scaledClipRect()
QRect QImageReader::scaledClipRect () const
Returns the scaled clip rect of the image.
See also
setScaledClipRect()
Definition at line 1079 of file qimagereader.cpp.
 {
     return d->scaledClipRect;
 }
scaledSize()
QSize QImageReader::scaledSize () const
Returns the scaled size of the image.
See also
setScaledSize()
Definition at line 1057 of file qimagereader.cpp.
Referenced by QMoviePrivate::infoForFrame(), and QMoviePrivate::next().
 {
     return d->scaledSize;
 }
setAutoDetectImageFormat()
void QImageReader::setAutoDetectImageFormat (bool enabled)
If enabled is true, image format autodetection is enabled; otherwise, it is disabled.
By default, autodetection is enabled.
QImageReader uses an extensive approach to detecting the image format; firstly, if you pass a file name to QImageReader, it will attempt to detect the file extension if the given file name does not point to an existing file, by appending supported default extensions to the given file name, one at a time. It then uses the following approach to detect the image format:
Image plugins are queried first, based on either the optional format string, or the file name suffix (if the source device is a file). No content detection is done at this stage. QImageReader will choose the first plugin that supports reading for this format.
If no plugin supports the image format, Qt's built-in handlers are checked based on either the optional format string, or the file name suffix.
If no capable plugins or built-in handlers are found, each plugin is tested by inspecting the content of the data stream.
If no plugins could detect the image format based on data contents, each built-in image handler is tested by inspecting the contents.
Finally, if all above approaches fail, QImageReader will report failure when trying to read the image.
By disabling image format autodetection, QImageReader will only query the plugins and built-in handlers based on the format string (i.e., no file name extensions are tested).
See also
QImageIOHandler::canRead(), QImageIOPlugin::capabilities()
Definition at line 774 of file qimagereader.cpp.
 {
     d->autoDetectImageFormat = enabled;
 }
setBackgroundColor()
void QImageReader::setBackgroundColor (const QColor & color)
Sets the background color to color.
Since
4.1
Image formats that support this operation are expected to initialize the background to color before reading an image.
See also
backgroundColor(), read()
Definition at line 1096 of file qimagereader.cpp.
 {
     if (!d->initHandler())
         return;
     if (d->handler->supportsOption(QImageIOHandler::BackgroundColor))
         d->handler->setOption(QImageIOHandler::BackgroundColor, color);
 }
setClipRect()
void QImageReader::setClipRect (const QRect & rect)
Sets the image clip rect (also known as the ROI, or Region Of Interest) to rect.
The coordinates of rect are relative to the untransformed image size, as returned by size().
See also
clipRect(), setScaledSize(), setScaledClipRect()
Definition at line 1020 of file qimagereader.cpp.
 {
     d->clipRect = rect;
 }
setDecideFormatFromContent()
void QImageReader::setDecideFormatFromContent (bool ignored)
If ignored is set to true, then the image reader will ignore specified formats or file extensions and decide which plugin to use only based on the contents in the datastream.
Setting this flag means that all image plugins gets loaded. Each plugin will read the first bytes in the image data and decide if the plugin is compatible or not.
This also disables auto detecting the image format.
See also
decideFormatFromContent()
Definition at line 805 of file qimagereader.cpp.
 {
     d->ignoresFormatAndExtension = ignored;
 }
setDevice()
void QImageReader::setDevice (QIODevice * device)
Sets QImageReader's device to device.
If a device has already been set, the old device is removed from QImageReader and is otherwise left unchanged.
If the device is not already open, QImageReader will attempt to open the device in QIODevice::ReadOnly mode by calling open(). Note that this does not work for certain devices, such as QProcess, QTcpSocket and QUdpSocket, where more logic is required to open the device.
See also
device(), setFileName()
Definition at line 838 of file qimagereader.cpp.
Referenced by setFileName().
 {
     if (d->device && d->deleteDevice)
         delete d->device;
     d->device = device;
     d->deleteDevice = false;
     delete d->handler;
     d->handler = 0;
     d->text.clear();
 }
setFileName()
void QImageReader::setFileName (const QString & fileName)
Sets the file name of QImageReader to fileName.
Internally, QImageReader will create a QFile object and open it in QIODevice::ReadOnly mode, and use this when reading images.
If fileName does not include a file extension (e.g., .png or .bmp), QImageReader will cycle through all supported extensions until it finds a matching file.
See also
fileName(), setDevice(), supportedImageFormats()
Definition at line 868 of file qimagereader.cpp.
 {
     setDevice(new QFile(fileName));
     d->deleteDevice = true;
 }
setFormat()
void QImageReader::setFormat (const QByteArray & format)
Sets the format QImageReader will use when reading images, to format.
format is a case insensitive text string. Example:
QImageReader reader;
reader.setFormat("png"); // same as reader.setFormat("PNG");
You can call supportedImageFormats() for the full list of formats QImageReader supports.
See also
format()
Definition at line 705 of file qimagereader.cpp.
Referenced by readImage().
 {
     d->format = format;
 }
setQuality()
void QImageReader::setQuality (int quality)
This is an image format specific function that sets the quality level of the image to quality.
Since
4.2
For image formats that do not support setting the quality, this value is ignored.
The value range of quality depends on the image format. For example, the "jpeg" format supports a quality range from 0 (low quality, high compression) to 100 (high quality, low compression).
See also
quality()
Definition at line 905 of file qimagereader.cpp.
 {
     d->quality = quality;
 }
setScaledClipRect()
void QImageReader::setScaledClipRect (const QRect & rect)
Sets the scaled clip rect to rect.
The scaled clip rect is the clip rect (also known as ROI, or Region Of Interest) that is applied after the image has been scaled.
See also
scaledClipRect(), setScaledSize()
Definition at line 1069 of file qimagereader.cpp.
 {
     d->scaledClipRect = rect;
 }
setScaledSize()
void QImageReader::setScaledSize (const QSize & size)
Sets the scaled size of the image to size.
The scaling is performed after the initial clip rect, but before the scaled clip rect is applied. The algorithm used for scaling depends on the image format. By default (i.e., if the image format does not support scaling), QImageReader will use QImage::scale() with Qt::SmoothScaling.
See also
scaledSize(), setClipRect(), setScaledClipRect()
Definition at line 1047 of file qimagereader.cpp.
Referenced by readImage().
 {
     d->scaledSize = size;
 }
size()
QSize QImageReader::size () const
Returns the size of the image, without actually reading the image contents.
If the image format does not support this feature, this function returns an invalid size. Qt's built-in image handlers all support this feature, but custom image format plugins are not required to do so.
See also
QImageIOHandler::ImageOption, QImageIOHandler::option(), QImageIOHandler::supportsOption()
Definition at line 936 of file qimagereader.cpp.
Referenced by readImage(), and setScaledSize().
 {
     if (!d->initHandler())
         return QSize();
     if (d->handler->supportsOption(QImageIOHandler::Size))
         return d->handler->option(QImageIOHandler::Size).toSize();
     return QSize();
 }
supportedImageFormats()
QList< QByteArray > QImageReader::supportedImageFormats () static
Returns the list of image formats supported by QImageReader.
By default, Qt can read the following formats:
Format Description
BMP Windows Bitmap
GIF Graphic Interchange Format (optional)
JPG Joint Photographic Experts Group
JPEG Joint Photographic Experts Group
MNG Multiple-image Network Graphics
PNG Portable Network Graphics
PBM Portable Bitmap
PGM Portable Graymap
PPM Portable Pixmap
TIFF Tagged Image File Format
XBM X11 Bitmap
XPM X11 Pixmap
SVG Scalable Vector Graphics
TGA Targa Image Format
Reading and writing SVG files is supported through Qt's QtSvg Module{SVG Module}.
TGA support only extends to reading non-RLE compressed files. In particular calls to capabilities for the tga plugin returns only QImageIOPlugin::CanRead, not QImageIOPlugin::CanWrite.
To configure Qt with GIF support, pass -qt-gif to the configure script or check the appropriate option in the graphical installer.
Note that the QApplication instance must be created before this function is called.
See also
setFormat(), QImageWriter::supportedImageFormats(), QImageIOPlugin
Definition at line 1530 of file qimagereader.cpp.
Referenced by imageReadMimeFormats(), QImageReaderPrivate::initHandler(), and QMovie::supportedFormats().
 {
     QSet<QByteArray> formats;
     for (int i = 0; i < _qt_NumFormats; ++i)
         formats << _qt_BuiltInFormats[i].extension;
 #ifndef QT_NO_LIBRARY
     QFactoryLoader *l = loader();
     QStringList keys = l->keys();
     for (int i = 0; i < keys.count(); ++i) {
         QImageIOPlugin *plugin = qobject_cast<QImageIOPlugin *>(l->instance(keys.at(i)));
         if (plugin && plugin->capabilities(0, keys.at(i).toLatin1()) & QImageIOPlugin::CanRead)
             formats << keys.at(i).toLatin1();
     }
 #endif // QT_NO_LIBRARY
     QList<QByteArray> sortedFormats;
     for (QSet<QByteArray>::ConstIterator it = formats.constBegin(); it != formats.constEnd(); ++it)
         sortedFormats << *it;
     qSort(sortedFormats);
     return sortedFormats;
 }
supportsAnimation()
bool QImageReader::supportsAnimation () const
Returns true if the image format supports animation; otherwise, false is returned.
Since
4.1
See also
QMovie::supportedFormats()
Definition at line 1136 of file qimagereader.cpp.
 {
     if (!d->initHandler())
         return false;
     if (d->handler->supportsOption(QImageIOHandler::Animation))
         return d->handler->option(QImageIOHandler::Animation).toBool();
     return false;
 }
supportsOption()
bool QImageReader::supportsOption (QImageIOHandler::ImageOption option) const
Returns true if the reader supports option; otherwise returns false.
Since
4.2
Different image formats support different options. Call this function to determine whether a certain option is supported by the current format. For example, the PNG format allows you to embed text into the image's metadata (see text()), and the BMP format allows you to determine the image's size without loading the whole image into memory (see size()).
QImageReader reader(":/image.png");
if (reader.supportsOption(QImageIOHandler::Size))
    qDebug() << "Size:" << reader.size();
See also
QImageWriter::supportsOption()
Definition at line 1453 of file qimagereader.cpp.
 {
     if (!d->initHandler())
         return false;
     return d->handler->supportsOption(option);
 }
text()
QString QImageReader::text (const QString & key) const
Returns the image text associated with key.
Since
4.1
Support for this option is implemented through QImageIOHandler::Description.
See also
textKeys(), QImageWriter::setText()
Definition at line 1007 of file qimagereader.cpp.
 {
     d->getText();
     return d->text.value(key);
 }
textKeys()
QStringList QImageReader::textKeys () const
Returns the text keys for this image.
Since
4.1
You can use these keys with text() to list the image text for a certain key.
Support for this option is implemented through QImageIOHandler::Description.
See also
text(), QImageWriter::setText(), QImage::textKeys()
Definition at line 988 of file qimagereader.cpp.
 {
     d->getText();
     return d->text.keys();
 }
Properties
d
QImageReaderPrivate* QImageReader::d private
Definition at line 140 of file qimagereader.h.
Referenced by autoDetectImageFormat(), backgroundColor(), canRead(), clipRect(), currentImageNumber(), currentImageRect(), decideFormatFromContent(), device(), error(), errorString(), fileName(), format(), imageCount(), imageFormat(), jumpToImage(), jumpToNextImage(), loopCount(), nextImageDelay(), QImageReader(), quality(), read(), scaledClipRect(), scaledSize(), setAutoDetectImageFormat(), setBackgroundColor(), setClipRect(), setDecideFormatFromContent(), setDevice(), setFileName(), setFormat(), setQuality(), setScaledClipRect(), setScaledSize(), size(), supportsAnimation(), supportsOption(), text(), textKeys(), and ~QImageReader().
The documentation for this class was generated from the following files:
/src/gui/image/qimagereader.h
/src/gui/image/qimagereader.cpp