Qt 4.8: QUIKitSoftwareInputHandler Class Reference
QUIKitSoftwareInputHandler Class Reference
#include <quikitsoftwareinputhandler.h>
Public Functions
bool eventFilter (QObject *obj, QEvent *event)
Filters events if this object has been installed as an event filter for the watched object.
QUIKitSoftwareInputHandler ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void activeFocusChanged (bool focus)
Private Functions
bool closeSoftwareInputPanel (QWidget *widget)
Properties
QPointer< QObject > mCurrentFocusObject
QPointer< QWidget > mCurrentFocusWidget
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 53 of file quikitsoftwareinputhandler.h.
Constructors and Destructors
QUIKitSoftwareInputHandler()
QUIKitSoftwareInputHandler::QUIKitSoftwareInputHandler () inline
Definition at line 58 of file quikitsoftwareinputhandler.h.
 : mCurrentFocusWidget(0), mCurrentFocusObject(0) {}
Functions
activeFocusChanged
void QUIKitSoftwareInputHandler::activeFocusChanged (bool focus) private slot
Definition at line 269 of file quikiteventloop.mm.
Referenced by QUIKitSoftwareInputHandler().
 {
     if (!focus && mCurrentFocusWidget && mCurrentFocusObject) {
         closeSoftwareInputPanel(mCurrentFocusWidget);
     }
 }
closeSoftwareInputPanel()
bool QUIKitSoftwareInputHandler::closeSoftwareInputPanel (QWidget * widget) private
Definition at line 253 of file quikiteventloop.mm.
Referenced by QUIKitSoftwareInputHandler().
 {
     if (widget) {
         QUIKitWindow *platformWindow = static_cast<QUIKitWindow *>(widget->window()->platformWindow());
         if (platformWindow) {
             [platformWindow->nativeView() resignFirstResponder];
             mCurrentFocusWidget = 0;
             if (mCurrentFocusObject)
                 disconnect(mCurrentFocusObject, 0, this, SLOT(activeFocusChanged(bool)));
             mCurrentFocusObject = 0;
         }
         return true;
     }
     return false;
 }
eventFilter()
bool QUIKitSoftwareInputHandler::eventFilter (QObject * , QEvent *) virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 218 of file quikiteventloop.mm.
Referenced by QUIKitSoftwareInputHandler().
 {
     if (event->type() == QEvent::RequestSoftwareInputPanel) {
         UIReturnKeyType returnKeyType = UIReturnKeyDone;
         if (QGraphicsView *declarativeView = qobject_cast<QGraphicsView *>(obj)) {
             // register on loosing the focus, so we can auto-remove the input panel again
             QGraphicsScene *scene = declarativeView->scene();
             if (scene) {
                 if (mCurrentFocusObject)
                     disconnect(mCurrentFocusObject, 0, this, SLOT(activeFocusChanged(bool)));
                 QObject *focus = dynamic_cast<QObject *>(scene->focusItem());
                 mCurrentFocusObject = focus;
                 if (focus) {
                     connect(mCurrentFocusObject, SIGNAL(activeFocusChanged(bool)), this, SLOT(activeFocusChanged(bool)));
                     returnKeyType = keyTypeForObject(mCurrentFocusObject);
                 }
             }
         }
         QWidget *widget = qobject_cast<QWidget *>(obj);
         if (widget) {
             mCurrentFocusWidget = widget;
             QUIKitWindow *platformWindow = static_cast<QUIKitWindow *>(widget->window()->platformWindow());
             if (platformWindow) {
                 platformWindow->nativeView().returnKeyType = returnKeyType;
                 [platformWindow->nativeView() becomeFirstResponder];
             }
             return true;
         }
     } else if (event->type() == QEvent::CloseSoftwareInputPanel) {
         QWidget *widget = qobject_cast<QWidget *>(obj);
         return closeSoftwareInputPanel(widget);
     }
     return false;
 }
Properties
mCurrentFocusObject
QPointer<QObject> QUIKitSoftwareInputHandler::mCurrentFocusObject private
Definition at line 68 of file quikitsoftwareinputhandler.h.
mCurrentFocusWidget
QPointer<QWidget> QUIKitSoftwareInputHandler::mCurrentFocusWidget private
Definition at line 67 of file quikitsoftwareinputhandler.h.
The documentation for this class was generated from the following files:
/src/plugins/platforms/uikit/quikitsoftwareinputhandler.h
/src/plugins/platforms/uikit/quikiteventloop.mm