Qt 4.8: QScriptDebuggerConsoleCommandGroupData Class Reference
QScriptDebuggerConsoleCommandGroupData Class Reference
The QScriptDebuggerConsoleCommandGroupData class holds data associated with a console command group.
#include <qscriptdebuggerconsolecommandgroupdata_p.h>
Public Functions
bool isValid () const
QString longDescription () const
QScriptDebuggerConsoleCommandGroupData & operator= (const QScriptDebuggerConsoleCommandGroupData &other)
QScriptDebuggerConsoleCommandGroupData ()
QScriptDebuggerConsoleCommandGroupData (const QString &shortDescription, const QString &longDescription)
QScriptDebuggerConsoleCommandGroupData (const QScriptDebuggerConsoleCommandGroupData &other)
QString shortDescription () const
~QScriptDebuggerConsoleCommandGroupData ()
Properties
QScopedSharedPointer< QScriptDebuggerConsoleCommandGroupDataPrivate > d_ptr
Detailed Description
The QScriptDebuggerConsoleCommandGroupData class holds data associated with a console command group.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 65 of file qscriptdebuggerconsolecommandgroupdata_p.h.
Constructors and Destructors
QScriptDebuggerConsoleCommandGroupData() [1/3]
QScriptDebuggerConsoleCommandGroupData::QScriptDebuggerConsoleCommandGroupData ()
Definition at line 80 of file qscriptdebuggerconsolecommandgroupdata.cpp.
     : d_ptr(0)
 {
 }
QScriptDebuggerConsoleCommandGroupData() [2/3]
QScriptDebuggerConsoleCommandGroupData::QScriptDebuggerConsoleCommandGroupData (const QString & shortDescription, const QString & longDescription)
Definition at line 85 of file qscriptdebuggerconsolecommandgroupdata.cpp.
     : d_ptr(new QScriptDebuggerConsoleCommandGroupDataPrivate)
 {
     d_ptr->shortDescription = shortDescription;
     d_ptr->longDescription = longDescription;
     d_ptr->ref.ref();
 }
QScriptDebuggerConsoleCommandGroupData() [3/3]
QScriptDebuggerConsoleCommandGroupData::QScriptDebuggerConsoleCommandGroupData (const QScriptDebuggerConsoleCommandGroupData & other)
Definition at line 94 of file qscriptdebuggerconsolecommandgroupdata.cpp.
     : d_ptr(other.d_ptr.data())
 {
     if (d_ptr)
         d_ptr->ref.ref();
 }
~QScriptDebuggerConsoleCommandGroupData()
QScriptDebuggerConsoleCommandGroupData::~QScriptDebuggerConsoleCommandGroupData ()
Definition at line 102 of file qscriptdebuggerconsolecommandgroupdata.cpp.
 {
 }
Functions
isValid()
bool QScriptDebuggerConsoleCommandGroupData::isValid () const
Definition at line 125 of file qscriptdebuggerconsolecommandgroupdata.cpp.
 {
     Q_D(const QScriptDebuggerConsoleCommandGroupData);
     return (d != 0);
 }
longDescription()
QString QScriptDebuggerConsoleCommandGroupData::longDescription () const
Definition at line 119 of file qscriptdebuggerconsolecommandgroupdata.cpp.
Referenced by consoleCommandGroupDataToScriptValue(), and QScriptDebuggerConsoleCommandGroupData().
 {
     Q_D(const QScriptDebuggerConsoleCommandGroupData);
     return d->longDescription;
 }
operator=()
QScriptDebuggerConsoleCommandGroupData & QScriptDebuggerConsoleCommandGroupData::operator= (const QScriptDebuggerConsoleCommandGroupData & other)
Definition at line 106 of file qscriptdebuggerconsolecommandgroupdata.cpp.
 {
     d_ptr.assign(other.d_ptr.data());
     return *this;
 }
shortDescription()
QString QScriptDebuggerConsoleCommandGroupData::shortDescription () const
Definition at line 113 of file qscriptdebuggerconsolecommandgroupdata.cpp.
Referenced by consoleCommandGroupDataToScriptValue(), and QScriptDebuggerConsoleCommandGroupData().
 {
     Q_D(const QScriptDebuggerConsoleCommandGroupData);
     return d->shortDescription;
 }
Properties
d_ptr
QScopedSharedPointer<QScriptDebuggerConsoleCommandGroupDataPrivate> QScriptDebuggerConsoleCommandGroupData::d_ptr private
Definition at line 85 of file qscriptdebuggerconsolecommandgroupdata_p.h.
Referenced by operator=(), and QScriptDebuggerConsoleCommandGroupData().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerconsolecommandgroupdata_p.h
/src/scripttools/debugging/qscriptdebuggerconsolecommandgroupdata.cpp