Qt 4.8: QCocoaWindow Class Reference
QCocoaWindow Class Reference
#include <qcocoawindow.h>
Public Functions
NSView * contentView () const
QCocoaWindow (QWidget *tlw)
void setContentView (NSView *contentView)
void setGeometry (const QRect &rect)
This function is called by Qt whenever a window is moved or the window is resized.
void setVisible (bool visible)
Reimplemented in subclasses to show the surface if visible is true, and hide it if visible is false.
void windowDidResize ()
WId winId () const
Reimplement in subclasses to return a handle to the native window.
~QCocoaWindow ()
Public Functions inherited from QPlatformWindow
virtual QRect geometry () const
Returnes the current geometry of a window.
virtual QPlatformGLContext * glContext () const
Reimplement to return the glContext associated with the window.
virtual void lower ()
Reimplement to be able to let Qt lower windows to the bottom of the desktop.
QPlatformWindow (QWidget *tlw)
Constructs a platform window with the given top level widget.
virtual void raise ()
Reimplement to be able to let Qt rais windows to the top of the desktop.
virtual void requestActivateWindow ()
Reimplement to let Qt be able to request activation/focus for a window.
virtual void setOpacity (qreal level)
Reimplement to be able to let Qt set the opacity level of a window.
virtual void setParent (const QPlatformWindow *window)
This function is called to enable native child widgets in QPA.
virtual Qt::WindowFlags setWindowFlags (Qt::WindowFlags flags)
Requests setting the window flags of this surface to type.
virtual void setWindowTitle (const QString &title)
Reimplement to set the window title to title.
QWidget * widget () const
Returnes the widget which belongs to the QPlatformWindow.
virtual Qt::WindowFlags windowFlags () const
Returns the effective window flags for this surface.
virtual ~QPlatformWindow ()
Virtual destructor does not delete its top level widget.
Properties
NSWindow * m_nsWindow
Additional Inherited Members
Protected Variables inherited from QPlatformWindow
QScopedPointer< QPlatformWindowPrivate > d_ptr
Detailed Description
Definition at line 51 of file qcocoawindow.h.
Constructors and Destructors
QCocoaWindow()
QCocoaWindow::QCocoaWindow (QWidget * tlw)
Definition at line 53 of file qcocoawindow.mm.
     : QPlatformWindow(tlw)
 {
     QCocoaAutoReleasePool pool;
     const QRect geo = tlw->geometry();
     NSRect frame = NSMakeRect(geo.x(), geo.y(), geo.width(), geo.height());
     m_nsWindow  = [[NSWindow alloc] initWithContentRect:frame
                                             styleMask:NSTitledWindowMask|NSClosableWindowMask|NSMiniaturizableWindowMask|NSResizableWindowMask
                                             backing:NSBackingStoreBuffered
                                             defer:YES];
     QNSWindowDelegate *delegate = [[QNSWindowDelegate alloc] initWithQCocoaWindow:this];
     [m_nsWindow setDelegate:delegate];
     [m_nsWindow makeKeyAndOrderFront:nil];
     [m_nsWindow setAcceptsMouseMovedEvents:YES];
 #if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_7
     if ([m_nsWindow respondsToSelector:@selector(setRestorable:)])
         [m_nsWindow setRestorable: NO];
 #endif
 }
~QCocoaWindow()
QCocoaWindow::~QCocoaWindow ()
Definition at line 77 of file qcocoawindow.mm.
 {
 }
Functions
contentView()
NSView * QCocoaWindow::contentView () const
Definition at line 99 of file qcocoawindow.mm.
Referenced by setContentView(), setGeometry(), and windowDidResize().
 {
     return [m_nsWindow contentView];
 }
setContentView()
void QCocoaWindow::setContentView (NSView * contentView)
Definition at line 104 of file qcocoawindow.mm.
Referenced by QCocoaWindowSurface::QCocoaWindowSurface().
 {
     [m_nsWindow setContentView:contentView];
 }
setGeometry()
void QCocoaWindow::setGeometry (const QRect & rect) virtual
This function is called by Qt whenever a window is moved or the window is resized.
The resize can happen programatically(from ie. user application) or by the window manager. This means that there is no need to call this function specifically from the window manager callback, instead call QWindowSystemInterface::handleGeometryChange(QWidget *w, const QRect &newRect);
Reimplemented from QPlatformWindow.
Definition at line 81 of file qcocoawindow.mm.
 {
     QPlatformWindow::setGeometry(rect);
     NSRect bounds = NSMakeRect(rect.x(), rect.y(), rect.width(), rect.height());
     [[m_nsWindow contentView]setFrameSize:bounds.size];
 }
setVisible()
void QCocoaWindow::setVisible (bool visible) virtual
Reimplemented in subclasses to show the surface if visible is true, and hide it if visible is false.
Reimplemented from QPlatformWindow.
Definition at line 89 of file qcocoawindow.mm.
 {
     Q_UNUSED(visible);
 }
windowDidResize()
void QCocoaWindow::windowDidResize ()
Definition at line 109 of file qcocoawindow.mm.
 {
     //jlind: XXX This isn't ideal. Eventdispatcher does not run when resizing...
     NSRect rect = [[m_nsWindow contentView]frame];
     QRect geo(rect.origin.x,rect.origin.y,rect.size.width,rect.size.height);
     QWindowSystemInterface::handleGeometryChange(widget(),geo);
 }
winId()
WId QCocoaWindow::winId () const virtual
Reimplement in subclasses to return a handle to the native window.
Reimplemented from QPlatformWindow.
Definition at line 94 of file qcocoawindow.mm.
 {
     return WId([m_nsWindow windowNumber]);
 }
Properties
m_nsWindow
NSWindow* QCocoaWindow::m_nsWindow private
Definition at line 69 of file qcocoawindow.h.
Referenced by contentView(), QCocoaWindow(), setContentView(), setGeometry(), windowDidResize(), and winId().
The documentation for this class was generated from the following files:
/src/plugins/platforms/cocoa/qcocoawindow.h
/src/plugins/platforms/cocoa/qcocoawindow.mm