Qt 4.8: QmlJSDebugger::ColorPickerTool Class Reference
QmlJSDebugger::ColorPickerTool Class Reference
#include <colorpickertool.h>
Signals
void selectedColorChanged (const QColor &color)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void clear ()
ColorPickerTool (QDeclarativeViewInspector *view)
void hoverMoveEvent (QMouseEvent *)
void itemsAboutToRemoved (const QList< QGraphicsItem *> &)
void keyPressEvent (QKeyEvent *)
void keyReleaseEvent (QKeyEvent *)
void mouseDoubleClickEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *)
void wheelEvent (QWheelEvent *)
virtual ~ColorPickerTool ()
Public Functions inherited from QmlJSDebugger::AbstractLiveEditTool
AbstractLiveEditTool (QDeclarativeViewInspector *inspector)
QList< QGraphicsItem * > items () const
void leaveEvent (QEvent *)
QString titleForItem (QGraphicsItem *item)
bool topItemIsMovable (const QList< QGraphicsItem *> &itemList)
bool topItemIsResizeHandle (const QList< QGraphicsItem *> &itemList)
bool topSelectedItemIsMovable (const QList< QGraphicsItem *> &itemList)
void updateSelectedItems ()
virtual ~AbstractLiveEditTool ()
Public Functions inherited from QmlJSDebugger::AbstractTool
AbstractTool (AbstractViewInspector *inspector)
AbstractViewInspector * inspector () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void selectedItemsChanged (const QList< QGraphicsItem *> &)
Protected Functions inherited from QmlJSDebugger::AbstractLiveEditTool
QDeclarativeViewInspector * inspector () const
QGraphicsScene * scene () const
QDeclarativeView * view () const
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
void pickColor (const QPoint &pos)
Properties
QColor m_selectedColor
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QmlJSDebugger::AbstractLiveEditTool
static QList< QGraphicsObject * > toGraphicsObjectList (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * topMovableDeclarativeItem (const QList< QGraphicsItem *> &itemList)
static QGraphicsItem * topMovableGraphicsItem (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * toQDeclarativeItem (QGraphicsItem *item)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 53 of file colorpickertool.h.
Constructors and Destructors
ColorPickerTool()
QmlJSDebugger::ColorPickerTool::ColorPickerTool (QDeclarativeViewInspector * view) explicit
Definition at line 56 of file colorpickertool.cpp.
                                                                 :
     AbstractLiveEditTool(view)
 {
     m_selectedColor.setRgb(0,0,0);
 }
~ColorPickerTool()
QmlJSDebugger::ColorPickerTool::~ColorPickerTool () virtual
Definition at line 62 of file colorpickertool.cpp.
 {
 }
Functions
clear()
void QmlJSDebugger::ColorPickerTool::clear (void) virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 76 of file colorpickertool.cpp.
Referenced by itemsAboutToRemoved().
 {
 #ifndef QT_NO_CURSOR
     view()->setCursor(Qt::CrossCursor);
 #endif
 }
hoverMoveEvent()
void QmlJSDebugger::ColorPickerTool::hoverMoveEvent (QMouseEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 66 of file colorpickertool.h.
 {}
itemsAboutToRemoved()
void QmlJSDebugger::ColorPickerTool::itemsAboutToRemoved (const QList< QGraphicsItem *> &) inline virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 73 of file colorpickertool.h.
 {}
keyPressEvent()
void QmlJSDebugger::ColorPickerTool::keyPressEvent (QKeyEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 68 of file colorpickertool.h.
 {}
keyReleaseEvent()
void QmlJSDebugger::ColorPickerTool::keyReleaseEvent (QKeyEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 69 of file colorpickertool.h.
 {}
mouseDoubleClickEvent()
void QmlJSDebugger::ColorPickerTool::mouseDoubleClickEvent (QMouseEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 64 of file colorpickertool.h.
 {}
mouseMoveEvent()
void QmlJSDebugger::ColorPickerTool::mouseMoveEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 71 of file colorpickertool.cpp.
 {
     pickColor(event->pos());
 }
mousePressEvent()
void QmlJSDebugger::ColorPickerTool::mousePressEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 66 of file colorpickertool.cpp.
 {
     pickColor(event->pos());
 }
mouseReleaseEvent()
void QmlJSDebugger::ColorPickerTool::mouseReleaseEvent (QMouseEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 63 of file colorpickertool.h.
 {}
pickColor()
void QmlJSDebugger::ColorPickerTool::pickColor (const QPoint & pos) private
Definition at line 83 of file colorpickertool.cpp.
Referenced by mouseMoveEvent(), mousePressEvent(), and selectedItemsChanged().
 {
     QRgb fillColor = view()->backgroundBrush().color().rgb();
     if (view()->backgroundBrush().style() == Qt::NoBrush)
         fillColor = view()->palette().color(QPalette::Base).rgb();
     QRectF target(0,0, 1, 1);
     QRect source(pos.x(), pos.y(), 1, 1);
     QImage img(1, 1, QImage::Format_ARGB32);
     img.fill(fillColor);
     QPainter painter(&img);
     view()->render(&painter, target, source);
     m_selectedColor = QColor::fromRgb(img.pixel(0, 0));
     emit selectedColorChanged(m_selectedColor);
 }
selectedColorChanged
void QmlJSDebugger::ColorPickerTool::selectedColorChanged (const QColor & color) signal
Referenced by itemsAboutToRemoved(), and pickColor().
selectedItemsChanged()
void QmlJSDebugger::ColorPickerTool::selectedItemsChanged (const QList< QGraphicsItem *> &) inline protected virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 81 of file colorpickertool.h.
 {}
wheelEvent()
void QmlJSDebugger::ColorPickerTool::wheelEvent (QWheelEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 71 of file colorpickertool.h.
 {}
Properties
m_selectedColor
QColor QmlJSDebugger::ColorPickerTool::m_selectedColor private
Definition at line 87 of file colorpickertool.h.
Referenced by ColorPickerTool(), and pickColor().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/colorpickertool.h
/src/plugins/qmltooling/qmldbg_inspector/editor/colorpickertool.cpp