Qt 4.8: QDeclarativeExpression Class Reference
QDeclarativeExpression Class Reference
The QDeclarativeExpression class evaluates JavaScript in a QML context.
#include <qdeclarativeexpression.h>
Signals
void valueChanged ()
Emitted each time the expression value changes from the last time it was evaluated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void clearError ()
Clear any expression errors.
QDeclarativeContext * context () const
Returns the QDeclarativeContext this expression is associated with, or 0 if there is no association or the QDeclarativeContext has been destroyed.
QDeclarativeEngine * engine () const
Returns the QDeclarativeEngine this expression is associated with, or 0 if there is no association or the QDeclarativeEngine has been destroyed.
QDeclarativeError error () const
Return any error from the last call to evaluate().
QVariant evaluate (bool *valueIsUndefined=0)
Evaulates the expression, returning the result of the evaluation, or an invalid QVariant if the expression is invalid or has an error.
QString expression () const
Returns the expression string.
bool hasError () const
Returns true if the last call to evaluate() resulted in an error, otherwise false.
int lineNumber () const
Returns the source file line number for this expression.
bool notifyOnValueChanged () const
Returns true if the valueChanged() signal is emitted when the expression's evaluated value changes.
QDeclarativeExpression ()
Create an invalid QDeclarativeExpression.
QDeclarativeExpression (QDeclarativeContext *, QObject *, const QString &, QObject *=0)
Create a QDeclarativeExpression object that is a child of parent.
QObject * scopeObject () const
Returns the expression's scope object, if provided, otherwise 0.
void setExpression (const QString &)
Set the expression to expression.
void setNotifyOnValueChanged (bool)
Sets whether the valueChanged() signal is emitted when the expression's evaluated value changes.
void setSourceLocation (const QString &fileName, int line)
Set the location of this expression to line of url.
QString sourceFile () const
Returns the source file URL for this expression.
virtual ~QDeclarativeExpression ()
Destroy the QDeclarativeExpression instance.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QDeclarativeExpression (QDeclarativeContextData *, QObject *, const QString &, QDeclarativeExpressionPrivate &dd)
QDeclarativeExpression (QDeclarativeContextData *, QObject *, const QScriptValue &, QDeclarativeExpressionPrivate &dd)
QDeclarativeExpression (QDeclarativeContextData *, void *, QDeclarativeRefCount *rc, QObject *me, const QString &, int, QDeclarativeExpressionPrivate &dd)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
QDeclarativeExpression (QDeclarativeContextData *, QObject *, const QString &)
Friends
class QDeclarativeContext
class QDeclarativeDebugger
class QDeclarativeVME
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDeclarativeExpression class evaluates JavaScript in a QML context.
Since
4.7
For example, given a file main.qml like this:
import QtQuick 1.0
Item {
    width: 200; height: 200
}
The following code evaluates a JavaScript expression in the context of the above QML:
QDeclarativeEngine *engine = new QDeclarativeEngine;
QDeclarativeComponent component(engine, QUrl::fromLocalFile("main.qml"));
QObject *myObject = component.create();
QDeclarativeExpression *expr = new QDeclarativeExpression(engine->rootContext(), myObject, "width * 2");
int result = expr->evaluate().toInt();  // result = 400
Definition at line 63 of file qdeclarativeexpression.h.
Constructors and Destructors
QDeclarativeExpression() [1/6]
QDeclarativeExpression::QDeclarativeExpression ()
Create an invalid QDeclarativeExpression.
As the expression will not have an associated QDeclarativeContext, this will be a null expression object and its value will always be an invalid QVariant.
Definition at line 249 of file qdeclarativeexpression.cpp.
 : QObject(*new QDeclarativeExpressionPrivate, 0)
 {
     Q_D(QDeclarativeExpression);
     if (QDeclarativeExpression_notifyIdx == -1)
         QDeclarativeExpression_notifyIdx = QDeclarativeExpression::staticMetaObject.indexOfMethod("_q_notify()");
     d->setNotifyObject(this, QDeclarativeExpression_notifyIdx);
 }
QDeclarativeExpression() [2/6]
QDeclarativeExpression::QDeclarativeExpression (QDeclarativeContext * ctxt, QObject * scope, const QString & expression, QObject * parent = 0)
Create a QDeclarativeExpression object that is a child of parent.
The expression JavaScript will be executed in the ctxt QDeclarativeContext. If specified, the scope object's properties will also be in scope during the expression's execution.
Definition at line 281 of file qdeclarativeexpression.cpp.
 : QObject(*new QDeclarativeExpressionPrivate, parent)
 {
     Q_D(QDeclarativeExpression);
     d->init(QDeclarativeContextData::get(ctxt), expression, scope);
     if (QDeclarativeExpression_notifyIdx == -1)
         QDeclarativeExpression_notifyIdx = QDeclarativeExpression::staticMetaObject.indexOfMethod("_q_notify()");
     d->setNotifyObject(this, QDeclarativeExpression_notifyIdx);
 }
~QDeclarativeExpression()
QDeclarativeExpression::~QDeclarativeExpression () virtual
Destroy the QDeclarativeExpression instance.
Definition at line 339 of file qdeclarativeexpression.cpp.
 {
 }
QDeclarativeExpression() [3/6]
QDeclarativeExpression::QDeclarativeExpression (QDeclarativeContextData * ctxt, QObject * scope, const QString & expression, QDeclarativeExpressionPrivate & dd) protected
Warning
This function is not part of the public interface.
Definition at line 311 of file qdeclarativeexpression.cpp.
 : QObject(dd, 0)
 {
     Q_D(QDeclarativeExpression);
     d->init(ctxt, expression, scope);
     if (QDeclarativeExpression_notifyIdx == -1)
         QDeclarativeExpression_notifyIdx = QDeclarativeExpression::staticMetaObject.indexOfMethod("_q_notify()");
     d->setNotifyObject(this, QDeclarativeExpression_notifyIdx);
 }
QDeclarativeExpression() [4/6]
QDeclarativeExpression::QDeclarativeExpression (QDeclarativeContextData * ctxt, QObject * scope, const QScriptValue & func, QDeclarativeExpressionPrivate & dd) protected
Warning
This function is not part of the public interface.
Definition at line 324 of file qdeclarativeexpression.cpp.
 : QObject(dd, 0)
 {
     Q_D(QDeclarativeExpression);
     d->init(ctxt, func, scope);
     if (QDeclarativeExpression_notifyIdx == -1)
         QDeclarativeExpression_notifyIdx = QDeclarativeExpression::staticMetaObject.indexOfMethod("_q_notify()");
     d->setNotifyObject(this, QDeclarativeExpression_notifyIdx);
 }
QDeclarativeExpression() [5/6]
QDeclarativeExpression::QDeclarativeExpression (QDeclarativeContextData * ctxt, void * expr, QDeclarativeRefCount * rc, QObject * me, const QString & url, int lineNumber, QDeclarativeExpressionPrivate & dd) protected
Warning
This function is not part of the public interface.
Definition at line 260 of file qdeclarativeexpression.cpp.
 : QObject(dd, 0)
 {
     Q_D(QDeclarativeExpression);
     d->init(ctxt, expr, rc, me, url, lineNumber);
     if (QDeclarativeExpression_notifyIdx == -1)
         QDeclarativeExpression_notifyIdx = QDeclarativeExpression::staticMetaObject.indexOfMethod("_q_notify()");
     d->setNotifyObject(this, QDeclarativeExpression_notifyIdx);
 }
QDeclarativeExpression() [6/6]
QDeclarativeExpression::QDeclarativeExpression (QDeclarativeContextData * ctxt, QObject * scope, const QString & expression) private
Warning
This function is not part of the public interface.
Definition at line 298 of file qdeclarativeexpression.cpp.
 : QObject(*new QDeclarativeExpressionPrivate, 0)
 {
     Q_D(QDeclarativeExpression);
     d->init(ctxt, expression, scope);
     if (QDeclarativeExpression_notifyIdx == -1)
         QDeclarativeExpression_notifyIdx = QDeclarativeExpression::staticMetaObject.indexOfMethod("_q_notify()");
     d->setNotifyObject(this, QDeclarativeExpression_notifyIdx);
 }
Functions
clearError()
void QDeclarativeExpression::clearError ()
Clear any expression errors.
Calls to hasError() following this will return false.
See also
hasError(), error()
Definition at line 781 of file qdeclarativeexpression.cpp.
 {
     Q_D(QDeclarativeExpression);
     d->error = QDeclarativeError();
 }
context()
QDeclarativeContext * QDeclarativeExpression::context () const
Returns the QDeclarativeContext this expression is associated with, or 0 if there is no association or the QDeclarativeContext has been destroyed.
Definition at line 357 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeQtScriptExpression::eval(), QDeclarativeQtScriptExpression::scriptValue(), QDeclarativeExpressionPrivate::scriptValue(), and QDeclarativeExpressionPrivate::value().
 {
     Q_D(const QDeclarativeExpression);
     QDeclarativeContextData *data = d->context();
     return data?data->asQDeclarativeContext():0;
 }
engine()
QDeclarativeEngine * QDeclarativeExpression::engine () const
Returns the QDeclarativeEngine this expression is associated with, or 0 if there is no association or the QDeclarativeEngine has been destroyed.
Definition at line 347 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeBinding::createBinding(), QDeclarativeQtScriptExpression::eval(), QDeclarativeBoundSignal::qt_metacall(), QDeclarativeQtScriptExpression::scriptValue(), and QDeclarativeExpressionPrivate::scriptValue().
 {
     Q_D(const QDeclarativeExpression);
     return d->context()?d->context()->engine:0;
 }
error()
QDeclarativeError QDeclarativeExpression::error () const
Return any error from the last call to evaluate().
If there was no error, this returns an invalid QDeclarativeError instance.
See also
hasError(), clearError()
Definition at line 794 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeQtScriptExpression::eval(), QDeclarativeGestureAreaPrivate::gestureEvent(), and QDeclarativeBoundSignal::qt_metacall().
 {
     Q_D(const QDeclarativeExpression);
     return d->error;
 }
evaluate()
QVariant QDeclarativeExpression::evaluate (bool * valueIsUndefined = 0)
Evaulates the expression, returning the result of the evaluation, or an invalid QVariant if the expression is invalid or has an error.
valueIsUndefined is set to true if the expression resulted in an undefined value.
See also
hasError(), error()
Definition at line 682 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativePropertyChanges::changeExpression(), QDeclarativeGestureAreaPrivate::gestureEvent(), QDeclarativeEngineDebugService::messageReceived(), QDeclarativeWatchProxy::notifyValueChanged(), and QDeclarativeStateGroupPrivate::updateAutoState().
 {
     Q_D(QDeclarativeExpression);
     return d->value(0, valueIsUndefined);
 }
expression()
QString QDeclarativeExpression::expression () const
Returns the expression string.
Definition at line 367 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativePropertyChanges::changeExpression(), QDeclarativeBinding::expression(), QDeclarativeBoundSignal::qt_metacall(), QDeclarativeExpressionPrivate::scriptValue(), setExpression(), and QDeclarativeQtScriptExpression::updateGuards().
 {
     Q_D(const QDeclarativeExpression);
     return d->expression;
 }
hasError()
bool QDeclarativeExpression::hasError () const
Returns true if the last call to evaluate() resulted in an error, otherwise false.
See also
error(), clearError()
Definition at line 769 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeGestureAreaPrivate::gestureEvent(), and QDeclarativeBoundSignal::qt_metacall().
 {
     Q_D(const QDeclarativeExpression);
     return d->error.isValid();
 }
lineNumber()
int QDeclarativeExpression::lineNumber () const
Returns the source file line number for this expression.
The source location must have been previously set by calling setSourceLocation().
Definition at line 734 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativeBinding::createBinding(), QDeclarativeExpressionPrivate::exceptionToError(), QDeclarativeBindingProfiler::QDeclarativeBindingProfiler(), and QDeclarativeBoundSignal::qt_metacall().
 {
     Q_D(const QDeclarativeExpression);
     return d->line;
 }
notifyOnValueChanged()
bool QDeclarativeExpression::notifyOnValueChanged () const
Returns true if the valueChanged() signal is emitted when the expression's evaluated value changes.
Definition at line 692 of file qdeclarativeexpression.cpp.
 {
     Q_D(const QDeclarativeExpression);
     return d->notifyOnValueChange();
 }
scopeObject()
QObject * QDeclarativeExpression::scopeObject () const
Returns the expression's scope object, if provided, otherwise 0.
In addition to data provided by the expression's QDeclarativeContext, the scope object's properties are also in scope during the expression's evaluation.
Definition at line 757 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeEngineDebugService::buildObjectDump(), QDeclarativeQtScriptExpression::eval(), and QDeclarativeExpressionPrivate::scriptValue().
 {
     Q_D(const QDeclarativeExpression);
     return d->scopeObject;
 }
setExpression()
void QDeclarativeExpression::setExpression (const QString & expression)
Set the expression to expression.
Definition at line 376 of file qdeclarativeexpression.cpp.
 {
     Q_D(QDeclarativeExpression);
     d->resetNotifyOnChange();
     d->expression = expression;
     d->expressionFunctionValid = false;
     d->expressionFunction = QScriptValue();
 }
setNotifyOnValueChanged()
void QDeclarativeExpression::setNotifyOnValueChanged (bool notifyOnChange)
Sets whether the valueChanged() signal is emitted when the expression's evaluated value changes.
If notifyOnChange is true, the QDeclarativeExpression will monitor properties involved in the expression's evaluation, and emit QDeclarativeExpression::valueChanged() if they have changed. This allows an application to ensure that any value associated with the result of the expression remains up to date.
If notifyOnChange is false (default), the QDeclarativeExpression will not montitor properties involved in the expression's evaluation, and QDeclarativeExpression::valueChanged() will never be emitted. This is more efficient if an application wants a "one off" evaluation of the expression.
Definition at line 714 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeWatcher::addWatch(), QDeclarativeBinding::disconnect(), QDeclarativeBinding::QDeclarativeBinding(), QDeclarativeEngineDebugService::setBinding(), QDeclarativeBinding::setEnabled(), and QDeclarativeBoundSignal::setExpression().
 {
     Q_D(QDeclarativeExpression);
     d->setNotifyOnValueChange(notifyOnChange);
 }
setSourceLocation()
void QDeclarativeExpression::setSourceLocation (const QString & url, int line)
Set the location of this expression to line of url.
This information is used by the script engine.
Definition at line 744 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativePropertyChangesPrivate::decode(), QDeclarativeEngineDebugService::setBinding(), QDeclarativeValueTypeScriptClass::setProperty(), and QDeclarativeObjectScriptClass::setProperty().
 {
     Q_D(QDeclarativeExpression);
     d->url = url;
     d->line = line;
 }
sourceFile()
QString QDeclarativeExpression::sourceFile () const
Returns the source file URL for this expression.
The source location must have been previously set by calling setSourceLocation().
Definition at line 724 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativePropertyChanges::actions(), QDeclarativeBindingProfiler::QDeclarativeBindingProfiler(), and QDeclarativeBoundSignal::qt_metacall().
 {
     Q_D(const QDeclarativeExpression);
     return d->url;
 }
valueChanged
void QDeclarativeExpression::valueChanged () signal
Emitted each time the expression value changes from the last time it was evaluated.
The expression must have been evaluated at least once (by calling QDeclarativeExpression::evaluate()) before this signal will be emitted.
Friends and Related Functions
QDeclarativeContext
friend class QDeclarativeContext friend
Definition at line 110 of file qdeclarativeexpression.h.
QDeclarativeDebugger
friend class QDeclarativeDebugger friend
Definition at line 109 of file qdeclarativeexpression.h.
QDeclarativeVME
friend class QDeclarativeVME friend
Definition at line 111 of file qdeclarativeexpression.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeexpression.h
/src/declarative/qml/qdeclarativeexpression.cpp