Qt 4.8: QBenchmarkValgrindUtils Class Reference
QBenchmarkValgrindUtils Class Reference
#include <qbenchmarkvalgrind_p.h>
Static Public Functions
static void cleanup ()
static qint64 extractLastResult ()
static qint64 extractResult (const QString &fileName)
static QString getNewestFileName ()
static bool haveValgrind ()
static QString outFileBase (qint64 pid=-1)
static bool rerunThroughCallgrind (const QStringList &origAppArgs, int &exitCode)
static bool runCallgrindSubProcess (const QStringList &origAppArgs, int &exitCode)
Detailed Description
Definition at line 65 of file qbenchmarkvalgrind_p.h.
Functions
cleanup()
void QBenchmarkValgrindUtils::cleanup () static
Definition at line 165 of file qbenchmarkvalgrind.cpp.
Referenced by QTest::qExec().
 {
     QStringList nameFilters;
     QString base = QBenchmarkGlobalData::current->callgrindOutFileBase;
     Q_ASSERT(!base.isEmpty());
     nameFilters
         << base // overall summary
         << QString::fromLatin1("%1.*").arg(base); // individual dumps
     QFileInfoList fiList = QDir().entryInfoList(nameFilters, QDir::Files | QDir::Readable);
     foreach (QFileInfo fileInfo, fiList) {
         const bool removeOk = QFile::remove(fileInfo.fileName());
         Q_ASSERT(removeOk);
         Q_UNUSED(removeOk);
     }
 }
extractLastResult()
qint64 QBenchmarkValgrindUtils::extractLastResult () static
Definition at line 160 of file qbenchmarkvalgrind.cpp.
Referenced by QBenchmarkCallgrindMeasurer::checkpoint().
 {
     return extractResult(getNewestFileName());
 }
extractResult()
qint64 QBenchmarkValgrindUtils::extractResult (const QString & fileName) static
Definition at line 104 of file qbenchmarkvalgrind.cpp.
Referenced by extractLastResult().
 {
     QFile file(fileName);
     const bool openOk = file.open(QIODevice::ReadOnly | QIODevice::Text);
     Q_ASSERT(openOk);
     Q_UNUSED(openOk);
     qint64 val = -1;
     bool valSeen = false;
     const QRegExp rxValue(QLatin1String("^summary: (\\d+)"));
     while (!file.atEnd()) {
         const QString line(QLatin1String(file.readLine()));
         if (rxValue.indexIn(line) != -1) {
             Q_ASSERT(rxValue.captureCount() == 1);
             bool ok;
             val = rxValue.cap(1).toLongLong(&ok);
             Q_ASSERT(ok);
             valSeen = true;
             break;
         }
     }
     Q_ASSERT(valSeen);
     return val;
 }
getNewestFileName()
QString QBenchmarkValgrindUtils::getNewestFileName () static
Definition at line 130 of file qbenchmarkvalgrind.cpp.
Referenced by extractLastResult().
 {
     QStringList nameFilters;
     QString base = QBenchmarkGlobalData::current->callgrindOutFileBase;
     Q_ASSERT(!base.isEmpty());
     nameFilters << QString::fromLatin1("%1.*").arg(base);
     QFileInfoList fiList = QDir().entryInfoList(nameFilters, QDir::Files | QDir::Readable);
     Q_ASSERT(!fiList.empty());
     int hiSuffix = -1;
     QFileInfo lastFileInfo;
     const QString pattern = QString::fromLatin1("%1.(\\d+)").arg(base);
     const QRegExp rx(pattern);
     foreach (QFileInfo fileInfo, fiList) {
         const int index = rx.indexIn(fileInfo.fileName());
         Q_ASSERT(index == 0);
         Q_UNUSED(index);
         bool ok;
         const int suffix = rx.cap(1).toInt(&ok);
         Q_ASSERT(ok);
         Q_ASSERT(suffix >= 0);
         if (suffix > hiSuffix) {
             lastFileInfo = fileInfo;
             hiSuffix = suffix;
         }
     }
     return lastFileInfo.fileName();
 }
haveValgrind()
bool QBenchmarkValgrindUtils::haveValgrind () static
Definition at line 57 of file qbenchmarkvalgrind.cpp.
Referenced by QTest::qtest_qParseArgs().
 {
 #ifdef NVALGRIND
     return false;
 #else
     QProcess process;
     QStringList args;
     args << QLatin1String("--version");
     process.start(QLatin1String("valgrind"), args);
     if (!process.waitForFinished(-1))
         return false;
     const QByteArray out = process.readAllStandardOutput();
     const QRegExp rx(QLatin1String("^valgrind-([0-9]).([0-9]).[0-9]"));
     if (rx.indexIn(QLatin1String(out.data())) == -1)
         return false;
     bool ok;
     const int major = rx.cap(1).toInt(&ok);
     if (!ok)
         return false;
     const int minor = rx.cap(2).toInt(&ok);
     if (!ok)
         return false;
 //    return (major > 3 || (major == 3 && minor >= 3)); // v >= 3.3 for --callgrind-out-file option
     Q_UNUSED(major);
     Q_UNUSED(minor);
     return true; // skip version restriction for now
 #endif
 }
outFileBase()
QString QBenchmarkValgrindUtils::outFileBase (qint64 pid = -1) static
Definition at line 181 of file qbenchmarkvalgrind.cpp.
Referenced by QTest::qtest_qParseArgs(), and runCallgrindSubProcess().
 {
     return QString::fromLatin1("callgrind.out.%1").arg(
         pid != -1 ? pid : QCoreApplication::applicationPid());
 }
rerunThroughCallgrind()
bool QBenchmarkValgrindUtils::rerunThroughCallgrind (const QStringList & origAppArgs, int & exitCode) static
Definition at line 88 of file qbenchmarkvalgrind.cpp.
Referenced by QTest::qExec().
 {
     if (!QBenchmarkValgrindUtils::runCallgrindSubProcess(origAppArgs, exitCode)) {
         qWarning("failed to run callgrind subprocess");
         return false;
     }
     return true;
 }
runCallgrindSubProcess()
bool QBenchmarkValgrindUtils::runCallgrindSubProcess (const QStringList & origAppArgs, int & exitCode) static
Definition at line 190 of file qbenchmarkvalgrind.cpp.
Referenced by rerunThroughCallgrind().
 {
     const QString execFile(origAppArgs.at(0));
     QStringList args;
     args << QLatin1String("--tool=callgrind") << QLatin1String("--instr-atstart=yes")
          << QLatin1String("--quiet")
          << execFile << QLatin1String("-callgrindchild");
 #if (defined Q_WS_QWS)
     // While running the child process, we aren't processing events, and hence aren't
     // acting as the QWS server. Therefore it's necessary to tell the child to act
     // as its own server instead of connecting to us.
     args << QLatin1String("-qws");
 #endif
     // pass on original arguments that make sense (e.g. avoid wasting time producing output
     // that will be ignored anyway) ...
     for (int i = 1; i < origAppArgs.size(); ++i) {
         const QString arg(origAppArgs.at(i));
         if (arg == QLatin1String("-callgrind"))
             continue;
         args << arg; // ok to pass on
     }
     QProcess process;
     process.start(QLatin1String("valgrind"), args);
     process.waitForStarted(-1);
     QBenchmarkGlobalData::current->callgrindOutFileBase =
         QBenchmarkValgrindUtils::outFileBase(process.pid());
     const bool finishedOk = process.waitForFinished(-1);
     exitCode = process.exitCode();
     dumpOutput(process.readAllStandardOutput(), stdout);
     dumpOutput(process.readAllStandardError(), stderr);
     return finishedOk;
 }
The documentation for this class was generated from the following files:
/src/testlib/qbenchmarkvalgrind_p.h
/src/testlib/qbenchmarkvalgrind.cpp