Qt 4.8: QHttpNetworkReply Class Reference
QHttpNetworkReply Class Reference
#include <qhttpnetworkreply_p.h>
Signals
void authenticationRequired (const QHttpNetworkRequest &request, QAuthenticator *authenticator)
void cacheCredentials (const QHttpNetworkRequest &request, QAuthenticator *authenticator)
void dataReadProgress (int done, int total)
void dataSendProgress (qint64 done, qint64 total)
void finished ()
void finishedWithError (QNetworkReply::NetworkError errorCode, const QString &detail=QString())
void headerChanged ()
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
void readyRead ()
void sslErrors (const QList< QSslError > &errors)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qint64 bytesAvailable () const
qint64 bytesAvailableNextBlock () const
QHttpNetworkConnection * connection ()
qint64 contentLength () const
QString errorString () const
QList< QPair< QByteArray, QByteArray > > header () const
QByteArray headerField (const QByteArray &name, const QByteArray &defaultValue=QByteArray()) const
void ignoreSslErrors ()
void ignoreSslErrors (const QList< QSslError > &errors)
bool isFinished () const
bool isPipeliningUsed () const
int majorVersion () const
int minorVersion () const
void parseHeader (const QByteArray &header)
QHttpNetworkReply (const QUrl &url=QUrl(), QObject *parent=0)
QByteArray read (qint64 amount)
QByteArray readAll ()
QByteArray readAny ()
bool readAnyAvailable () const
QString reasonPhrase () const
QHttpNetworkRequest request () const
void setContentLength (qint64 length)
void setDownstreamLimited (bool t)
void setErrorString (const QString &error)
void setHeaderField (const QByteArray &name, const QByteArray &data)
void setReadBufferSize (qint64 size)
void setRequest (const QHttpNetworkRequest &request)
void setSslConfiguration (const QSslConfiguration &config)
void setStatusCode (int code)
void setUrl (const QUrl &url)
void setUserProvidedDownloadBuffer (char *)
qint64 sizeNextBlock ()
QSslConfiguration sslConfiguration () const
int statusCode () const
bool supportsUserProvidedDownloadBuffer ()
QUrl url () const
char * userProvidedDownloadBuffer ()
virtual ~QHttpNetworkReply ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QHttpNetworkHeader
virtual ~QHttpNetworkHeader ()
Friends
class QHttpNetworkConnection
class QHttpNetworkConnectionChannel
class QHttpNetworkConnectionPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 93 of file qhttpnetworkreply_p.h.
Constructors and Destructors
QHttpNetworkReply()
QHttpNetworkReply::QHttpNetworkReply (const QUrl & url = QUrl(), QObject * parent = 0) explicit
Definition at line 57 of file qhttpnetworkreply.cpp.
     : QObject(*new QHttpNetworkReplyPrivate(url), parent)
 {
 }
~QHttpNetworkReply()
QHttpNetworkReply::~QHttpNetworkReply () virtual
Definition at line 62 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     if (d->connection) {
         d->connection->d_func()->removeReply(this);
     }
 }
Functions
authenticationRequired
void QHttpNetworkReply::authenticationRequired (const QHttpNetworkRequest & request, QAuthenticator * authenticator) signal
Referenced by QHttpNetworkConnectionPrivate::handleAuthenticateChallenge().
bytesAvailable()
qint64 QHttpNetworkReply::bytesAvailable () const
Definition at line 162 of file qhttpnetworkreply.cpp.
 {
     Q_D(const QHttpNetworkReply);
     if (d->connection)
         return d->connection->d_func()->uncompressedBytesAvailable(*this);
     else
         return -1;
 }
bytesAvailableNextBlock()
qint64 QHttpNetworkReply::bytesAvailableNextBlock () const
Definition at line 171 of file qhttpnetworkreply.cpp.
 {
     Q_D(const QHttpNetworkReply);
     if (d->connection)
         return d->connection->d_func()->uncompressedBytesAvailableNextBlock(*this);
     else
         return -1;
 }
cacheCredentials
void QHttpNetworkReply::cacheCredentials (const QHttpNetworkRequest & request, QAuthenticator * authenticator) signal
Referenced by QHttpNetworkConnectionPrivate::handleAuthenticateChallenge().
connection()
QHttpNetworkConnection * QHttpNetworkReply::connection ()
Definition at line 258 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::handleUnexpectedEOF(), QHttpNetworkConnectionChannel::pipelineInto(), and QHttpNetworkConnectionPrivate::queueRequest().
 {
     return d_func()->connection;
 }
contentLength()
qint64 QHttpNetworkReply::contentLength () const virtual
Implements QHttpNetworkHeader.
Definition at line 80 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_error(), QHttpThreadDelegate::headerChangedSlot(), and QHttpThreadDelegate::synchronousHeaderChangedSlot().
 {
     return d_func()->contentLength();
 }
dataReadProgress
void QHttpNetworkReply::dataReadProgress (int done, int total) signal
Referenced by QHttpNetworkConnectionChannel::_q_receiveReply(), and QHttpNetworkConnectionChannel::expand().
dataSendProgress
void QHttpNetworkReply::dataSendProgress (qint64 done, qint64 total) signal
Referenced by QHttpNetworkConnectionChannel::sendRequest().
errorString()
QString QHttpNetworkReply::errorString () const
Definition at line 136 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_error(), QHttpNetworkConnectionPrivate::emitReplyError(), QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), QHttpNetworkConnectionChannel::handleStatus(), and QHttpNetworkConnectionChannel::handleUnexpectedEOF().
 {
     return d_func()->errorString;
 }
finished
void QHttpNetworkReply::finished () signal
finishedWithError
void QHttpNetworkReply::finishedWithError (QNetworkReply::NetworkError errorCode, const QString & detail = QString()) signal
Referenced by QHttpNetworkConnectionChannel::_q_error(), QHttpNetworkConnectionPrivate::emitReplyError(), QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), QHttpNetworkConnectionChannel::handleStatus(), and QHttpNetworkConnectionChannel::handleUnexpectedEOF().
header()
QList< QPair< QByteArray, QByteArray > > QHttpNetworkReply::header () const virtual
Implements QHttpNetworkHeader.
Definition at line 91 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), QHttpThreadDelegate::headerChangedSlot(), and QHttpThreadDelegate::synchronousHeaderChangedSlot().
 {
     return d_func()->fields;
 }
headerChanged
void QHttpNetworkReply::headerChanged () signal
Referenced by QHttpNetworkConnectionChannel::_q_receiveReply(), QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), and QHttpNetworkConnectionChannel::handleStatus().
headerField()
QByteArray QHttpNetworkReply::headerField (const QByteArray & name, const QByteArray & defaultValue = QByteArray()) const virtual
Implements QHttpNetworkHeader.
Definition at line 96 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::detectPipeliningSupport().
 {
     return d_func()->headerField(name, defaultValue);
 }
ignoreSslErrors() [1/2]
void QHttpNetworkReply::ignoreSslErrors ()
Definition at line 983 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::sslErrorsSlot().
 {
     Q_D(QHttpNetworkReply);
     if (d->connection)
         d->connection->ignoreSslErrors();
 }
ignoreSslErrors() [2/2]
void QHttpNetworkReply::ignoreSslErrors (const QList< QSslError > & errors)
Definition at line 990 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     if (d->connection)
         d->connection->ignoreSslErrors(errors);
 }
isFinished()
bool QHttpNetworkReply::isFinished () const
Definition at line 248 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionPrivate::removeReply().
 {
     return d_func()->state == QHttpNetworkReplyPrivate::AllDoneState;
 }
isPipeliningUsed()
bool QHttpNetworkReply::isPipeliningUsed () const
Definition at line 253 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::headerChangedSlot(), and QHttpThreadDelegate::synchronousHeaderChangedSlot().
 {
     return d_func()->pipeliningUsed;
 }
majorVersion()
int QHttpNetworkReply::majorVersion () const virtual
Implements QHttpNetworkHeader.
Definition at line 152 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::detectPipeliningSupport().
 {
     return d_func()->majorVersion;
 }
minorVersion()
int QHttpNetworkReply::minorVersion () const virtual
Implements QHttpNetworkHeader.
Definition at line 157 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::detectPipeliningSupport().
 {
     return d_func()->minorVersion;
 }
parseHeader()
void QHttpNetworkReply::parseHeader (const QByteArray & header)
Definition at line 107 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     d->parseHeader(header);
 }
proxyAuthenticationRequired
void QHttpNetworkReply::proxyAuthenticationRequired (const QNetworkProxy & proxy, QAuthenticator * authenticator) signal
Referenced by QHttpNetworkConnectionPrivate::emitProxyAuthenticationRequired(), and QHttpNetworkConnectionPrivate::handleAuthenticateChallenge().
read()
QByteArray QHttpNetworkReply::read (qint64 amount)
Definition at line 204 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::readyReadSlot().
 {
     Q_D(QHttpNetworkReply);
     return d->responseData.read(amount);
 }
readAll()
QByteArray QHttpNetworkReply::readAll ()
Definition at line 198 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::synchronousFinishedSlot().
 {
     Q_D(QHttpNetworkReply);
     return d->responseData.readAll();
 }
readAny()
QByteArray QHttpNetworkReply::readAny ()
Definition at line 186 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::finishedSlot(), and QHttpThreadDelegate::readyReadSlot().
 {
     Q_D(QHttpNetworkReply);
     if (d->responseData.bufferCount() == 0)
         return QByteArray();
     // we'll take the last buffer, so schedule another read from http
     if (d->downstreamLimited && d->responseData.bufferCount() == 1)
         d->connection->d_func()->readMoreLater(this);
     return d->responseData.read();
 }
readAnyAvailable()
bool QHttpNetworkReply::readAnyAvailable () const
Definition at line 180 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::finishedSlot(), and QHttpThreadDelegate::readyReadSlot().
 {
     Q_D(const QHttpNetworkReply);
     return (d->responseData.bufferCount() > 0);
 }
readyRead
void QHttpNetworkReply::readyRead () signal
Referenced by QHttpNetworkConnectionChannel::_q_receiveReply(), QHttpNetworkConnectionChannel::expand(), QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), and QHttpNetworkConnectionChannel::handleStatus().
reasonPhrase()
QString QHttpNetworkReply::reasonPhrase () const
Definition at line 141 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::finishedSlot(), QHttpThreadDelegate::headerChangedSlot(), QHttpThreadDelegate::synchronousFinishedSlot(), and QHttpThreadDelegate::synchronousHeaderChangedSlot().
 {
     return d_func()->reasonPhrase;
 }
request()
QHttpNetworkRequest QHttpNetworkReply::request () const
Definition at line 113 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionPrivate::handleAuthenticateChallenge(), and setRequest().
 {
     return d_func()->request;
 }
setContentLength()
void QHttpNetworkReply::setContentLength (qint64 length) virtual
Implements QHttpNetworkHeader.
Definition at line 85 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     d->setContentLength(length);
 }
setDownstreamLimited()
void QHttpNetworkReply::setDownstreamLimited (bool t)
Definition at line 216 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::readBufferSizeChanged().
 {
     Q_D(QHttpNetworkReply);
     d->downstreamLimited = dsl;
     d->connection->d_func()->readMoreLater(this);
 }
setErrorString()
void QHttpNetworkReply::setErrorString (const QString & error)
Definition at line 146 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     d->errorString = error;
 }
setHeaderField()
void QHttpNetworkReply::setHeaderField (const QByteArray & name, const QByteArray & data) virtual
Implements QHttpNetworkHeader.
Definition at line 101 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     d->setHeaderField(name, data);
 }
setReadBufferSize()
void QHttpNetworkReply::setReadBufferSize (qint64 size)
Definition at line 223 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_error(), and QHttpThreadDelegate::readBufferSizeChanged().
 {
     Q_D(QHttpNetworkReply);
     d->readBufferMaxSize = size;
 }
setRequest()
void QHttpNetworkReply::setRequest (const QHttpNetworkRequest & request)
Definition at line 118 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionPrivate::queueRequest().
 {
     Q_D(QHttpNetworkReply);
     d->request = request;
     d->ssl = request.isSsl();
 }
setSslConfiguration()
void QHttpNetworkReply::setSslConfiguration (const QSslConfiguration & config)
Definition at line 976 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     if (d->connection)
         d->connection->setSslConfiguration(config);
 }
setStatusCode()
void QHttpNetworkReply::setStatusCode (int code)
Definition at line 130 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     d->statusCode = code;
 }
setUrl()
void QHttpNetworkReply::setUrl (const QUrl & url) virtual
Implements QHttpNetworkHeader.
Definition at line 74 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     d->url = url;
 }
setUserProvidedDownloadBuffer()
void QHttpNetworkReply::setUserProvidedDownloadBuffer (char * b)
Definition at line 235 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::headerChangedSlot().
 {
     Q_D(QHttpNetworkReply);
     if (supportsUserProvidedDownloadBuffer())
         d->userProvidedDownloadBuffer = b;
 }
sizeNextBlock()
qint64 QHttpNetworkReply::sizeNextBlock ()
Definition at line 210 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::readyReadSlot(), and QHttpNetworkConnectionPrivate::uncompressedBytesAvailableNextBlock().
 {
     Q_D(QHttpNetworkReply);
     return d->responseData.sizeNextBlock();
 }
sslConfiguration()
QSslConfiguration QHttpNetworkReply::sslConfiguration () const
Definition at line 962 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::finishedSlot(), QHttpThreadDelegate::finishedWithErrorSlot(), QHttpThreadDelegate::headerChangedSlot(), and QHttpThreadDelegate::sslErrorsSlot().
 {
     Q_D(const QHttpNetworkReply);
     if (!d->connectionChannel)
         return QSslConfiguration();
     QSslSocket *sslSocket = qobject_cast<QSslSocket*>(d->connectionChannel->socket);
     if (!sslSocket)
         return QSslConfiguration();
     return sslSocket->sslConfiguration();
 }
sslErrors
void QHttpNetworkReply::sslErrors (const QList< QSslError > & errors) signal
Referenced by QHttpNetworkConnectionChannel::_q_sslErrors().
statusCode()
int QHttpNetworkReply::statusCode () const
Definition at line 125 of file qhttpnetworkreply.cpp.
Referenced by QHttpNetworkConnectionChannel::_q_receiveReply(), QHttpThreadDelegate::finishedSlot(), QHttpNetworkConnectionChannel::handleStatus(), QHttpThreadDelegate::headerChangedSlot(), QHttpThreadDelegate::synchronousFinishedSlot(), and QHttpThreadDelegate::synchronousHeaderChangedSlot().
 {
     return d_func()->statusCode;
 }
supportsUserProvidedDownloadBuffer()
bool QHttpNetworkReply::supportsUserProvidedDownloadBuffer ()
Definition at line 229 of file qhttpnetworkreply.cpp.
Referenced by QHttpThreadDelegate::headerChangedSlot(), and setUserProvidedDownloadBuffer().
 {
     Q_D(QHttpNetworkReply);
     return (!d->isChunked() && !d->autoDecompress && d->bodyLength > 0);
 }
url()
QUrl QHttpNetworkReply::url () const virtual
Implements QHttpNetworkHeader.
Definition at line 70 of file qhttpnetworkreply.cpp.
Referenced by setUrl().
 {
     return d_func()->url;
 }
userProvidedDownloadBuffer()
char * QHttpNetworkReply::userProvidedDownloadBuffer ()
Definition at line 242 of file qhttpnetworkreply.cpp.
 {
     Q_D(QHttpNetworkReply);
     return d->userProvidedDownloadBuffer;
 }
Friends and Related Functions
QHttpNetworkConnection
friend class QHttpNetworkConnection friend
Definition at line 171 of file qhttpnetworkreply_p.h.
QHttpNetworkConnectionChannel
friend class QHttpNetworkConnectionChannel friend
Definition at line 173 of file qhttpnetworkreply_p.h.
QHttpNetworkConnectionPrivate
friend class QHttpNetworkConnectionPrivate friend
Definition at line 172 of file qhttpnetworkreply_p.h.
The documentation for this class was generated from the following files:
/src/network/access/qhttpnetworkreply_p.h
/src/network/access/qhttpnetworkreply.cpp