Qt 4.8: QFontSubset Class Reference
QFontSubset Class Reference
#include <qfontsubset_p.h>
Public Functions
int addGlyph (int index)
QByteArray createToUnicodeMap () const
QVector< int > getReverseMap () const
QByteArray glyphName (unsigned int glyph, const QVector< int > reverseMap) const
int nGlyphs () const
QFontSubset (QFontEngine *fe, int obj_id=0)
QByteArray toTruetype () const
QByteArray toType1 () const
QByteArray type1AddedGlyphs () const
QByteArray widthArray () const
~QFontSubset ()
Static Public Functions
static QByteArray glyphName (unsigned short unicode, bool symbol)
Public Variables
int downloaded_glyphs
QFixed emSquare
QFontEngine * fontEngine
QList< int > glyph_indices
bool noEmbed
const int object_id
bool standard_font
QVector< QFixed > widths
Detailed Description
Definition at line 62 of file qfontsubset_p.h.
Constructors and Destructors
QFontSubset()
QFontSubset::QFontSubset (QFontEngine * fe, int obj_id = 0) inline
Definition at line 65 of file qfontsubset_p.h.
         : object_id(obj_id), noEmbed(false), fontEngine(fe), downloaded_glyphs(0), standard_font(false)
         { fontEngine->ref.ref(); addGlyph(0); }
~QFontSubset()
QFontSubset::~QFontSubset () inline
Definition at line 68 of file qfontsubset_p.h.
                    {
         if (!fontEngine->ref.deref())
             delete fontEngine;
     }
Functions
addGlyph()
int QFontSubset::addGlyph (int index)
Definition at line 531 of file qfontsubset.cpp.
Referenced by QPdfBaseEnginePrivate::drawTextItem(), QFontSubset(), and ~QFontSubset().
 {
     int idx = glyph_indices.indexOf(index);
     if (idx < 0) {
         idx = glyph_indices.size();
         glyph_indices.append(index);
     }
     return idx;
 }
createToUnicodeMap()
QByteArray QFontSubset::createToUnicodeMap () const
Definition at line 439 of file qfontsubset.cpp.
Referenced by QPdfEnginePrivate::embedFont(), and ~QFontSubset().
 {
     QVector<int> reverseMap = getReverseMap();
     QByteArray touc;
     QPdf::ByteStream ts(&touc);
     ts << "/CIDInit /ProcSet findresource begin\n"
         "12 dict begin\n"
         "begincmap\n"
         "/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def\n"
         "/CMapName /Adobe-Identity-UCS def\n"
         "/CMapType 2 def\n"
         "1 begincodespacerange\n"
         "<0000> <FFFF>\n"
         "endcodespacerange\n";
     int nranges = 1;
     QByteArray ranges = "<0000> <0000> <0000>\n";
     QPdf::ByteStream s(&ranges);
     char buf[5];
     for (int g = 1; g < nGlyphs(); ) {
         int uc0 = reverseMap.at(g);
         if (!uc0) {
             ++g;
             continue;
         }
         int start = g;
         int startLinear = 0;
         ++g;
         while (g < nGlyphs()) {
             int uc = reverseMap[g];
             // cmaps can't have the high byte changing within one range, so we need to break on that as well
             if (!uc || (g>>8) != (start >> 8))
                 break;
             if (uc == uc0 + 1) {
                 if (!startLinear)
                     startLinear = g - 1;
             } else {
                 if (startLinear > 0 && g - startLinear >= 10)
                     break;
                 startLinear = 0;
             }
             uc0 = uc;
             ++g;
         }
         // qDebug("start=%x startLinear=%x g-1=%x",start,startLinear,g-1);
         if (g - startLinear < 10)
             startLinear = 0;
         int endnonlinear = startLinear ? startLinear : g;
         // qDebug("    startLinear=%x endnonlinear=%x", startLinear,endnonlinear);
         if (endnonlinear > start) {
             s << '<' << QPdf::toHex((ushort)start, buf) << "> <";
             s << QPdf::toHex((ushort)(endnonlinear - 1), buf) << "> ";
             if (endnonlinear == start + 1) {
                 s << '<' << QPdf::toHex((ushort)reverseMap[start], buf) << ">\n";
             } else {
                 s << '[';
                 for (int i = start; i < endnonlinear; ++i) {
                     s << '<' << QPdf::toHex((ushort)reverseMap[i], buf) << "> ";
                 }
                 s << "]\n";
             }
             checkRanges(ts, ranges, nranges);
         }
         if (startLinear) {
             while (startLinear < g) {
                 int len = g - startLinear;
                 int uc_start = reverseMap[startLinear];
                 int uc_end = uc_start + len - 1;
                 if ((uc_end >> 8) != (uc_start >> 8))
                     len = 256 - (uc_start & 0xff);
                 s << '<' << QPdf::toHex((ushort)startLinear, buf) << "> <";
                 s << QPdf::toHex((ushort)(startLinear + len - 1), buf) << "> ";
                 s << '<' << QPdf::toHex((ushort)reverseMap[startLinear], buf) << ">\n";
                 checkRanges(ts, ranges, nranges);
                 startLinear += len;
             }
         }
     }
     if (nranges) {
         ts << nranges << "beginbfrange\n"
            << ranges << "endbfrange\n";
     }
     ts << "endcmap\n"
         "CMapName currentdict /CMap defineresource pop\n"
         "end\n"
         "end\n";
     return touc;
 }
getReverseMap()
QVector< int > QFontSubset::getReverseMap () const
Definition at line 421 of file qfontsubset.cpp.
Referenced by createToUnicodeMap(), toType1(), type1AddedGlyphs(), and ~QFontSubset().
 {
     QVector<int> reverseMap;
     reverseMap.resize(0x10000);
     for (uint i = 0; i < 0x10000; ++i)
         reverseMap[i] = 0;
     QGlyphLayoutArray<10> glyphs;
     for (uint uc = 0; uc < 0x10000; ++uc) {
         QChar ch(uc);
         int nglyphs = 10;
         fontEngine->stringToCMap(&ch, 1, &glyphs, &nglyphs, QTextEngine::GlyphIndicesOnly);
         int idx = glyph_indices.indexOf(glyphs.glyphs[0]);
         if (idx >= 0 && !reverseMap.at(idx))
             reverseMap[idx] = uc;
     }
     return reverseMap;
 }
glyphName() [1/2]
QByteArray QFontSubset::glyphName (unsigned int glyph, const QVector< int > reverseMap) const
Definition at line 312 of file qfontsubset.cpp.
Referenced by type1AddedGlyphs(), and ~QFontSubset().
 {
     uint glyphIndex = glyph_indices[glyph];
     if (glyphIndex == 0)
         return "/.notdef";
     QByteArray ba;
     QPdf::ByteStream s(&ba);
 #ifndef QT_NO_FREETYPE
     FT_Face face = ft_face(fontEngine);
     char name[32];
     name[0] = 0;
     if (face && FT_HAS_GLYPH_NAMES(face)) {
 #if defined(Q_WS_X11)
         if (fontEngine->type() == QFontEngine::XLFD)
             glyphIndex = static_cast<QFontEngineXLFD *>(fontEngine)->glyphIndexToFreetypeGlyphIndex(glyphIndex);
 #endif
         FT_Get_Glyph_Name(face, glyphIndex, &name, 32);
         if (name[0] == '.') // fix broken PS fonts returning .notdef for many glyphs
             name[0] = 0;
     }
     if (name[0]) {
         s << '/' << name;
     } else
 #endif
 #if defined(Q_WS_X11)
     if (fontEngine->type() == QFontEngine::XLFD) {
         uint uc = static_cast<QFontEngineXLFD *>(fontEngine)->toUnicode(glyphIndex);
         s << '/' << glyphName(uc, false /* ### */);
     } else
 #endif
     if (reverseMap[glyphIndex] && reverseMap[glyphIndex] < 0x10000) {
         s << '/' << glyphName(reverseMap[glyphIndex], false);
     } else {
         s << "/gl" << (int)glyphIndex;
     }
     return ba;
 }
glyphName() [2/2]
QByteArray QFontSubset::glyphName (unsigned short unicode, bool symbol) static
Definition at line 267 of file qfontsubset.cpp.
 {
     if (symbol && unicode < 0x100)
         // map from latin1 to symbol
         unicode = symbol_map[unicode];
     int l = 0;
     while(unicode_to_aglindex[l].u < unicode)
         l++;
     if (unicode_to_aglindex[l].u == unicode)
         return agl + unicode_to_aglindex[l].index;
     char buffer[8];
     buffer[0] = 'u';
     buffer[1] = 'n';
     buffer[2] = 'i';
     QPdf::toHex(unicode, buffer+3);
     return buffer;
 }
nGlyphs()
int QFontSubset::nGlyphs () const inline
Definition at line 90 of file qfontsubset_p.h.
Referenced by createToUnicodeMap(), generateGlyphTables(), toTruetype(), type1AddedGlyphs(), and widthArray().
 { return glyph_indices.size(); }
toTruetype()
QByteArray QFontSubset::toTruetype () const
Definition at line 1385 of file qfontsubset.cpp.
Referenced by QPdfEnginePrivate::embedFont(), and ~QFontSubset().
 {
     qttf_font_tables font;
     memset(&font, 0, sizeof(qttf_font_tables));
     qreal ppem = fontEngine->fontDef.pixelSize;
 #define TO_TTF(x) qRound(x * 2048. / ppem)
     QList<QTtfGlyph> glyphs;
     QFontEngine::Properties properties = fontEngine->properties();
     // initialize some stuff needed in createWidthArray
     emSquare = 2048;
     widths.resize(nGlyphs());
     // head table
     font.head.font_revision = 0x00010000;
     font.head.flags = (1 << 2) | (1 << 4);
     font.head.created = 0; // ###
     font.head.modified = 0; // ###
     font.head.xMin = SHRT_MAX;
     font.head.xMax = SHRT_MIN;
     font.head.yMin = SHRT_MAX;
     font.head.yMax = SHRT_MIN;
     font.head.macStyle = (fontEngine->fontDef.weight > QFont::Normal) ? 1 : 0;
     font.head.macStyle |= (fontEngine->fontDef.styleHint != QFont::StyleNormal) ? 1 : 0;
     // hhea table
     font.hhea.ascender = qRound(properties.ascent);
     font.hhea.descender = -qRound(properties.descent);
     font.hhea.lineGap = qRound(properties.leading);
     font.hhea.maxAdvanceWidth = TO_TTF(fontEngine->maxCharWidth());
     font.hhea.minLeftSideBearing = TO_TTF(fontEngine->minLeftBearing());
     font.hhea.minRightSideBearing = TO_TTF(fontEngine->minRightBearing());
     font.hhea.xMaxExtent = SHRT_MIN;
     font.maxp.numGlyphs = 0;
     font.maxp.maxPoints = 0;
     font.maxp.maxContours = 0;
     font.maxp.maxCompositePoints = 0;
     font.maxp.maxCompositeContours = 0;
     font.maxp.maxComponentElements = 0;
     font.maxp.maxComponentDepth = 0;
     font.maxp.numGlyphs = nGlyphs();
     uint sumAdvances = 0;
     for (int i = 0; i < nGlyphs(); ++i) {
         glyph_t g = glyph_indices.at(i);
         QPainterPath path;
         glyph_metrics_t metric;
         fontEngine->getUnscaledGlyph(g, &path, &metric);
         if (noEmbed) {
             path = QPainterPath();
             if (g == 0)
                 path.addRect(QRectF(0, 0, 1000, 1000));
         }
         QTtfGlyph glyph = generateGlyph(i, path, metric.xoff.toReal(), metric.x.toReal(), properties.emSquare.toReal());
         font.head.xMin = qMin(font.head.xMin, glyph.xMin);
         font.head.xMax = qMax(font.head.xMax, glyph.xMax);
         font.head.yMin = qMin(font.head.yMin, glyph.yMin);
         font.head.yMax = qMax(font.head.yMax, glyph.yMax);
         font.hhea.xMaxExtent = qMax(font.hhea.xMaxExtent, (qint16)(glyph.lsb + glyph.xMax - glyph.xMin));
         font.maxp.maxPoints = qMax(font.maxp.maxPoints, glyph.numPoints);
         font.maxp.maxContours = qMax(font.maxp.maxContours, glyph.numContours);
         if (glyph.xMax > glyph.xMin)
             sumAdvances += glyph.xMax - glyph.xMin;
 //         qDebug("adding glyph %d size=%d", glyph.index, glyph.data.size());
         glyphs.append(glyph);
         widths[i] = glyph.advanceWidth;
     }
     QList<QTtfTable> tables = generateGlyphTables(font, glyphs);
     tables.append(generateHead(font.head));
     tables.append(generateHhea(font.hhea));
     tables.append(generateMaxp(font.maxp));
     // name
     QTtfTable name_table;
     name_table.tag = MAKE_TAG('n', 'a', 'm', 'e');
     if (!noEmbed)
         name_table.data = fontEngine->getSfntTable(name_table.tag);
     if (name_table.data.isEmpty()) {
         qttf_name_table name;
         if (noEmbed)
             name.copyright = QLatin1String("Fake font");
         else
             name.copyright = QLatin1String(properties.copyright);
         name.family = fontEngine->fontDef.family;
         name.subfamily = QLatin1String("Regular"); // ######
         name.postscript_name = QLatin1String(properties.postscriptName);
         name_table = generateName(name);
     }
     tables.append(name_table);
     if (!noEmbed) {
         QTtfTable os2;
         os2.tag = MAKE_TAG('O', 'S', '/', '2');
         os2.data = fontEngine->getSfntTable(os2.tag);
         if (!os2.data.isEmpty())
             tables.append(os2);
     }
     return bindFont(tables);
 }
toType1()
QByteArray QFontSubset::toType1 () const
Definition at line 1648 of file qfontsubset.cpp.
Referenced by ~QFontSubset().
 {
     QFontEngine::Properties properties = fontEngine->properties();
     QVector<int> reverseMap = getReverseMap();
     QByteArray font;
     QPdf::ByteStream s(&font);
     QByteArray id = QByteArray::number(object_id);
     QByteArray psname = properties.postscriptName;
     psname.replace(' ', "");
     standard_font = false;
 #ifndef QT_NO_FREETYPE
     FT_Face face = ft_face(fontEngine);
     if (face && !FT_IS_SCALABLE(face)) {
         int style = 0;
         if (fontEngine->fontDef.style)
             style += 2;
         if (fontEngine->fontDef.weight >= QFont::Bold)
             style++;
         if (fontEngine->fontDef.family.contains(QLatin1String("Helvetica"))) {
             psname = helvetica_styles[style];
             standard_font = true;
         } else if (fontEngine->fontDef.family.contains(QLatin1String("Times"))) {
             psname = times_styles[style];
             standard_font = true;
         } else if (fontEngine->fontDef.family.contains(QLatin1String("Courier"))) {
             psname = courier_styles[style];
             standard_font = true;
         }
     }
 #endif
     s << "/F" << id << "-Base\n";
     if (standard_font) {
             s << '/' << psname << " findfont\n"
                 "0 dict copy dup /NumGlyphs 0 put dup /CMap 256 array put def\n";
     } else {
         s << "<<\n";
         if(!psname.isEmpty())
             s << "/FontName /" << psname << '\n';
         s << "/FontInfo <</FsType " << (int)fontEngine->fsType << ">>\n"
             "/FontType 1\n"
             "/PaintType 0\n"
             "/FontMatrix [.001 0 0 .001 0 0]\n"
             "/FontBBox { 0 0 0 0 }\n"
             "/Private <<\n"
             "/password 5839\n"
             "/MinFeature {16 16}\n"
             "/BlueValues []\n"
             "/lenIV -1\n"
             ">>\n"
             "/CharStrings << >>\n"
             "/NumGlyphs 0\n"
             "/CMap 256 array\n"
             ">> def\n";
     }
     s << type1AddedGlyphs();
     downloaded_glyphs = glyph_indices.size();
     return font;
 }
type1AddedGlyphs()
QByteArray QFontSubset::type1AddedGlyphs () const
Definition at line 1712 of file qfontsubset.cpp.
Referenced by toType1(), and ~QFontSubset().
 {
     if (downloaded_glyphs == glyph_indices.size())
         return QByteArray();
     QFontEngine::Properties properties = fontEngine->properties();
     QVector<int> reverseMap = getReverseMap();
     QByteArray glyphs;
     QPdf::ByteStream s(&glyphs);
     int nGlyphs = glyph_indices.size();
     QByteArray id = QByteArray::number(object_id);
     s << 'F' << id << "-Base [\n";
     for (int i = downloaded_glyphs; i < nGlyphs; ++i) {
         glyph_t g = glyph_indices.at(i);
         QPainterPath path;
         glyph_metrics_t metric;
         fontEngine->getUnscaledGlyph(g, &path, &metric);
         QByteArray charstring = charString(path, metric.xoff.toReal(), metric.x.toReal(),
                                              properties.emSquare.toReal());
         s << glyphName(i, reverseMap);
         if (!standard_font)
           s << "\n<" << charstring << ">\n";
     }
     s << (standard_font ? "] T1AddMapping\n" : "] T1AddGlyphs\n");
     return glyphs;
 }
widthArray()
QByteArray QFontSubset::widthArray () const
Definition at line 354 of file qfontsubset.cpp.
Referenced by QPdfEnginePrivate::embedFont(), and ~QFontSubset().
 {
     Q_ASSERT(!widths.isEmpty());
     QFontEngine::Properties properties = fontEngine->properties();
     QByteArray width;
     QPdf::ByteStream s(&width);
     QFixed scale = QFixed(1000)/emSquare;
     QFixed defWidth = widths[0];
     //qDebug("defWidth=%d, scale=%f", defWidth.toInt(), scale.toReal());
     for (int i = 0; i < nGlyphs(); ++i) {
         if (defWidth != widths[i])
             defWidth = 0;
     }
     if (defWidth > 0) {
         s << "/DW " << (defWidth*scale).toInt();
     } else {
         s << "/W [";
         for (int g = 0; g < nGlyphs();) {
             QFixed w = widths[g];
             int start = g;
             int startLinear = 0;
             ++g;
             while (g < nGlyphs()) {
                 QFixed nw = widths[g];
                 if (nw == w) {
                 if (!startLinear)
                     startLinear = g - 1;
                 } else {
                     if (startLinear > 0 && g - startLinear >= 10)
                         break;
                     startLinear = 0;
                 }
                 w = nw;
                 ++g;
             }
             // qDebug("start=%x startLinear=%x g-1=%x",start,startLinear,g-1);
             if (g - startLinear < 10)
                 startLinear = 0;
             int endnonlinear = startLinear ? startLinear : g;
             // qDebug("    startLinear=%x endnonlinear=%x", startLinear,endnonlinear);
             if (endnonlinear > start) {
                 s << start << '[';
                 for (int i = start; i < endnonlinear; ++i)
                     s << (widths[i]*scale).toInt();
                 s << "]\n";
             }
             if (startLinear)
                 s << startLinear << g - 1 << (widths[startLinear]*scale).toInt() << '\n';
         }
         s << "]\n";
     }
     return width;
 }
Properties
downloaded_glyphs
int QFontSubset::downloaded_glyphs mutable
Definition at line 88 of file qfontsubset_p.h.
Referenced by toType1(), and type1AddedGlyphs().
emSquare
QFixed QFontSubset::emSquare mutable
Definition at line 91 of file qfontsubset_p.h.
Referenced by toTruetype(), and widthArray().
fontEngine
QFontEngine* QFontSubset::fontEngine
Definition at line 86 of file qfontsubset_p.h.
Referenced by QPdfEnginePrivate::embedFont(), getReverseMap(), glyphName(), QFontSubset(), toTruetype(), toType1(), type1AddedGlyphs(), widthArray(), and ~QFontSubset().
glyph_indices
QList<int> QFontSubset::glyph_indices
Definition at line 87 of file qfontsubset_p.h.
Referenced by addGlyph(), getReverseMap(), glyphName(), toTruetype(), toType1(), and type1AddedGlyphs().
noEmbed
bool QFontSubset::noEmbed
Definition at line 85 of file qfontsubset_p.h.
Referenced by QPdfBaseEnginePrivate::drawTextItem(), and toTruetype().
object_id
const int QFontSubset::object_id
Definition at line 84 of file qfontsubset_p.h.
Referenced by QPdfBaseEnginePrivate::drawTextItem(), QPdfEnginePrivate::embedFont(), toType1(), and type1AddedGlyphs().
standard_font
bool QFontSubset::standard_font mutable
Definition at line 89 of file qfontsubset_p.h.
Referenced by toType1(), and type1AddedGlyphs().
widths
QVector<QFixed> QFontSubset::widths mutable
Definition at line 92 of file qfontsubset_p.h.
Referenced by toTruetype(), and widthArray().
The documentation for this class was generated from the following files:
/src/gui/text/qfontsubset_p.h
/src/gui/text/qfontsubset.cpp