Qt 4.8: QStyledItemDelegate Class Reference
QStyledItemDelegate Class Reference
The QStyledItemDelegate class provides display and editing facilities for data items from a model.
#include <qstyleditemdelegate.h>
Public Functions
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
Returns the widget used to edit the item specified by index for editing.
virtual QString displayText (const QVariant &value, const QLocale &locale) const
This function returns the string that the delegate will use to display the Qt::DisplayRole of the model in locale.
QItemEditorFactory * itemEditorFactory () const
Returns the editor factory used by the item delegate.
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Renders the delegate using the given painter and style option for the item specified by index.
QStyledItemDelegate (QObject *parent=0)
Constructs an item delegate with the given parent.
void setEditorData (QWidget *editor, const QModelIndex &index) const
Sets the data to be displayed and edited by the editor from the data model item specified by the model index.
void setItemEditorFactory (QItemEditorFactory *factory)
Sets the editor factory to be used by the item delegate to be the factory specified.
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
Gets data from the editor widget and stores it in the specified model at the item index.
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
Returns the size needed by the delegate to display the item specified by index, taking into account the style information provided by option.
void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const
Updates the editor for the item specified by index according to the style option given.
~QStyledItemDelegate ()
Destroys the item delegate.
Public Functions inherited from QAbstractItemDelegate
QAbstractItemDelegate (QObject *parent=0)
Creates a new abstract item delegate with the given parent.
virtual ~QAbstractItemDelegate ()
Destroys the abstract item delegate.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index)
Reimplemented Function
bool eventFilter (QObject *object, QEvent *event)
Returns true if the given editor is a valid QWidget and the given event is handled; otherwise returns false.
virtual void initStyleOption (QStyleOptionViewItem *option, const QModelIndex &index) const
Initialize option with the values using the index index.
Protected Functions inherited from QAbstractItemDelegate
QAbstractItemDelegate (QObjectPrivate &, QObject *parent=0)
Creates a new abstract item delegate with the given parent.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Types inherited from QAbstractItemDelegate
enum EndEditHint {
NoHint, EditNextItem, EditPreviousItem, SubmitModelCache,
RevertModelCache
}
This enum describes the different hints that the delegate can give to the model and view components to make editing data in a model a comfortable experience for the user.
Public Slots inherited from QAbstractItemDelegate
bool helpEvent (QHelpEvent *event, QAbstractItemView *view, const QStyleOptionViewItem &option, const QModelIndex &index)
Whenever a help event occurs, this function is called with the event view option and the index that corresponds to the item where the event occurs.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemDelegate
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint=NoHint)
This signal is emitted when the user has finished editing an item using the specified editor.
void commitData (QWidget *editor)
This signal must be emitted when the editor widget has completed editing the data, and wants to write it back into the model.
void sizeHintChanged (const QModelIndex &)
This signal must be emitted when the sizeHint() of index changed.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QAbstractItemDelegate
static QString elidedText (const QFontMetrics &fontMetrics, int width, Qt::TextElideMode mode, const QString &text)
Use QFontMetrics::elidedText() instead.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QStyledItemDelegate class provides display and editing facilities for data items from a model.
Since
4.4
When displaying data from models in Qt item views, e.g., a QTableView, the individual items are drawn by a delegate. Also, when an item is edited, it provides an editor widget, which is placed on top of the item view while editing takes place. QStyledItemDelegate is the default delegate for all Qt item views, and is installed upon them when they are created.
The QStyledItemDelegate class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}. The delegate allows the display and editing of items to be developed independently from the model and view.
The data of items in models are assigned an Qt::ItemDataRole; each item can store a QVariant for each role. QStyledItemDelegate implements display and editing for the most common datatypes expected by users, including booleans, integers, and strings.
The data will be drawn differently depending on which role they have in the model. The following table describes the roles and the data types the delegate can handle for each of them. It is often sufficient to ensure that the model returns appropriate data for each of the roles to determine the appearance of items in views.
Role Accepted Types
Warning
This function is not part of the public interface.
Qt::AccessibleDescriptionRole QString
Qt::AccessibleTextRole QString
Qt::BackgroundRole
QBrush
Qt::BackgroundColorRole
QColor (obsolete; use Qt::BackgroundRole instead)
Qt::CheckStateRole
Qt::CheckState
Qt::DecorationRole
QIcon, QPixmap, QImage and QColor
Qt::DisplayRole
QString and types with a string representation
Qt::EditRole
See QItemEditorFactory for details
Qt::FontRole
QFont
Qt::SizeHintRole
QSize
Warning
This function is not part of the public interface.
Qt::StatusTipRole
Qt::TextAlignmentRole
Qt::Alignment
Qt::ForegroundRole
QBrush
Qt::TextColorRole
QColor (obsolete; use Qt::ForegroundRole instead)
Warning
This function is not part of the public interface.
Qt::ToolTipRole
Qt::WhatsThisRole
Editors are created with a QItemEditorFactory; a default static instance provided by QItemEditorFactory is installed on all item delegates. You can set a custom factory using setItemEditorFactory() or set a new default factory with QItemEditorFactory::setDefaultFactory(). It is the data stored in the item model with the Qt::EditRole that is edited. See the QItemEditorFactory class for a more high-level introduction to item editor factories. The Color Editor Factory Example{Color Editor Factory} example shows how to create custom editors with a factory.
Subclassing QStyledItemDelegate
If the delegate does not support painting of the data types you need or you want to customize the drawing of items, you need to subclass QStyledItemDelegate, and reimplement paint() and possibly sizeHint(). The paint() function is called individually for each item, and with sizeHint(), you can specify the hint for each of them.
When reimplementing paint(), one would typically handle the datatypes one would like to draw and use the superclass implementation for other types.
The painting of check box indicators are performed by the current style. The style also specifies the size and the bounding rectangles in which to draw the data for the different data roles. The bounding rectangle of the item itself is also calculated by the style. When drawing already supported datatypes, it is therefore a good idea to ask the style for these bounding rectangles. The QStyle class description describes this in more detail.
If you wish to change any of the bounding rectangles calculated by the style or the painting of check box indicators, you can subclass QStyle. Note, however, that the size of the items can also be affected by reimplementing sizeHint().
It is possible for a custom delegate to provide editors without the use of an editor item factory. In this case, the following virtual functions must be reimplemented:
createEditor() returns the widget used to change data from the model and can be reimplemented to customize editing behavior.
setEditorData() provides the widget with data to manipulate.
updateEditorGeometry() ensures that the editor is displayed correctly with respect to the item view.
setModelData() returns updated data to the model.
The Star Delegate Example{Star Delegate} example creates editors by reimplementing these methods.
.-QItemDelegate
QStyledItemDelegate vs. QItemDelegate
Since Qt 4.4, there are two delegate classes: QItemDelegate and QStyledItemDelegate. However, the default delegate is QStyledItemDelegate. These two classes are independent alternatives to painting and providing editors for items in views. The difference between them is that QStyledItemDelegate uses the current style to paint its items. We therefore recommend using QStyledItemDelegate as the base class when implementing custom delegates or when working with Qt style sheets. The code required for either class should be equal unless the custom delegate needs to use the style for drawing.
If you wish to customize the painting of item views, you should implement a custom style. Please see the QStyle class documentation for details.
See also
{Delegate Classes}, QItemDelegate, QAbstractItemDelegate, QStyle, {Spin Box Delegate Example}, {Star Delegate Example}, {Color Editor Factory Example}
Definition at line 61 of file qstyleditemdelegate.h.
Constructors and Destructors
QStyledItemDelegate()
QStyledItemDelegate::QStyledItemDelegate (QObject * parent = 0) explicit
Constructs an item delegate with the given parent.
Definition at line 249 of file qstyleditemdelegate.cpp.
     : QAbstractItemDelegate(*new QStyledItemDelegatePrivate(), parent)
 {
 }
~QStyledItemDelegate()
QStyledItemDelegate::~QStyledItemDelegate ()
Destroys the item delegate.
Definition at line 257 of file qstyleditemdelegate.cpp.
 {
 }
Functions
createEditor()
QWidget * QStyledItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Returns the widget used to edit the item specified by index for editing.
The parent widget and style option are used to control how the editor widget appears.
See also
QAbstractItemDelegate::createEditor()
Reimplemented from QAbstractItemDelegate.
Reimplemented in QScriptBreakpointsItemDelegate, and QScriptDebuggerLocalsItemDelegate.
Definition at line 465 of file qstyleditemdelegate.cpp.
Referenced by QScriptDebuggerLocalsItemDelegate::createEditor(), and QScriptBreakpointsItemDelegate::createEditor().
 {
     Q_D(const QStyledItemDelegate);
     if (!index.isValid())
         return 0;
     QVariant::Type t = static_cast<QVariant::Type>(index.data(Qt::EditRole).userType());
     return d->editorFactory()->createEditor(t, parent);
 }
displayText()
QString QStyledItemDelegate::displayText (const QVariant & value, const QLocale & locale) const virtual
This function returns the string that the delegate will use to display the Qt::DisplayRole of the model in locale.
value is the value of the Qt::DisplayRole provided by the model.
The default implementation uses the QLocale::toString to convert value into a QString.
This function is not called for empty model indices, i.e., indices for which the model returns an invalid QVariant.
See also
QAbstractItemModel::data()
Definition at line 274 of file qstyleditemdelegate.cpp.
Referenced by initStyleOption().
 {
     QString text;
     switch (value.userType()) {
     case QMetaType::Float:
     case QVariant::Double:
         text = locale.toString(value.toReal());
         break;
     case QVariant::Int:
     case QVariant::LongLong:
         text = locale.toString(value.toLongLong());
         break;
     case QVariant::UInt:
     case QVariant::ULongLong:
         text = locale.toString(value.toULongLong());
         break;
     case QVariant::Date:
         text = locale.toString(value.toDate(), QLocale::ShortFormat);
         break;
     case QVariant::Time:
         text = locale.toString(value.toTime(), QLocale::ShortFormat);
         break;
     case QVariant::DateTime:
         text = locale.toString(value.toDateTime().date(), QLocale::ShortFormat);
         text += QLatin1Char(' ');
         text += locale.toString(value.toDateTime().time(), QLocale::ShortFormat);
         break;
     default:
         // convert new lines into line separators
         text = value.toString();
         for (int i = 0; i < text.count(); ++i) {
             if (text.at(i) == QLatin1Char('\n'))
                 text[i] = QChar::LineSeparator;
         }
         break;
     }
     return text;
 }
editorEvent()
bool QStyledItemDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemDelegate.
Definition at line 712 of file qstyleditemdelegate.cpp.
 {
     Q_ASSERT(event);
     Q_ASSERT(model);
     // make sure that the item is checkable
     Qt::ItemFlags flags = model->flags(index);
     if (!(flags & Qt::ItemIsUserCheckable) || !(option.state & QStyle::State_Enabled)
         || !(flags & Qt::ItemIsEnabled))
         return false;
     // make sure that we have a check state
     QVariant value = index.data(Qt::CheckStateRole);
     if (!value.isValid())
         return false;
     const QWidget *widget = QStyledItemDelegatePrivate::widget(option);
     QStyle *style = widget ? widget->style() : QApplication::style();
     // make sure that we have the right event type
     if ((event->type() == QEvent::MouseButtonRelease)
         || (event->type() == QEvent::MouseButtonDblClick)
         || (event->type() == QEvent::MouseButtonPress)) {
         QStyleOptionViewItemV4 viewOpt(option);
         initStyleOption(&viewOpt, index);
         QRect checkRect = style->subElementRect(QStyle::SE_ItemViewItemCheckIndicator, &viewOpt, widget);
         QMouseEvent *me = static_cast<QMouseEvent*>(event);
         if (me->button() != Qt::LeftButton || !checkRect.contains(me->pos()))
             return false;
         if ((event->type() == QEvent::MouseButtonPress)
             || (event->type() == QEvent::MouseButtonDblClick))
             return true;
     } else if (event->type() == QEvent::KeyPress) {
         if (static_cast<QKeyEvent*>(event)->key() != Qt::Key_Space
          && static_cast<QKeyEvent*>(event)->key() != Qt::Key_Select)
             return false;
     } else {
         return false;
     }
     Qt::CheckState state = (static_cast<Qt::CheckState>(value.toInt()) == Qt::Checked
                             ? Qt::Unchecked : Qt::Checked);
     return model->setData(index, state, Qt::CheckStateRole);
 }
eventFilter()
bool QStyledItemDelegate::eventFilter (QObject * editor, QEvent * event) protected virtual
Returns true if the given editor is a valid QWidget and the given event is handled; otherwise returns false.
The following key press events are handled by default:
Tab
Backtab
Enter
Return
Esc
In the case of Tab, Backtab, Enter and Return key press events, the editor's data is comitted to the model and the editor is closed. If the event is a Tab key press the view will open an editor on the next item in the view. Likewise, if the event is a Backtab key press the view will open an editor on the previous item in the view.
If the event is a Esc key press event, the editor is closed without committing its data.
See also
commitData(), closeEditor()
Reimplemented from QObject.
Reimplemented in QScriptBreakpointsItemDelegate, and QScriptDebuggerLocalsItemDelegate.
Definition at line 639 of file qstyleditemdelegate.cpp.
Referenced by QScriptDebuggerLocalsItemDelegate::eventFilter(), and QScriptBreakpointsItemDelegate::eventFilter().
 {
     QWidget *editor = qobject_cast<QWidget*>(object);
     if (!editor)
         return false;
     if (event->type() == QEvent::KeyPress) {
         switch (static_cast<QKeyEvent *>(event)->key()) {
         case Qt::Key_Tab:
             emit commitData(editor);
             emit closeEditor(editor, QAbstractItemDelegate::EditNextItem);
             return true;
         case Qt::Key_Backtab:
             emit commitData(editor);
             emit closeEditor(editor, QAbstractItemDelegate::EditPreviousItem);
             return true;
         case Qt::Key_Enter:
         case Qt::Key_Return:
 #ifndef QT_NO_TEXTEDIT
             if (qobject_cast<QTextEdit *>(editor) || qobject_cast<QPlainTextEdit *>(editor))
                 return false; // don't filter enter key events for QTextEdit
             // We want the editor to be able to process the key press
             // before committing the data (e.g. so it can do
             // validation/fixup of the input).
 #endif // QT_NO_TEXTEDIT
 #ifndef QT_NO_LINEEDIT
             if (QLineEdit *e = qobject_cast<QLineEdit*>(editor))
                 if (!e->hasAcceptableInput())
                     return false;
 #endif // QT_NO_LINEEDIT
             QMetaObject::invokeMethod(this, "_q_commitDataAndCloseEditor",
                                       Qt::QueuedConnection, Q_ARG(QWidget*, editor));
             return false;
         case Qt::Key_Escape:
             // don't commit data
             emit closeEditor(editor, QAbstractItemDelegate::RevertModelCache);
             break;
         default:
             return false;
         }
         if (editor->parentWidget())
             editor->parentWidget()->setFocus();
         return true;
     } else if (event->type() == QEvent::FocusOut || (event->type() == QEvent::Hide && editor->isWindow())) {
         //the Hide event will take care of he editors that are in fact complete dialogs
         if (!editor->isActiveWindow() || (QApplication::focusWidget() != editor)) {
             QWidget *w = QApplication::focusWidget();
             while (w) { // don't worry about focus changes internally in the editor
                 if (w == editor)
                     return false;
                 w = w->parentWidget();
             }
 #ifndef QT_NO_DRAGANDDROP
             // The window may lose focus during an drag operation.
             // i.e when dragging involves the taskbar on Windows.
             if (QDragManager::self() && QDragManager::self()->object != 0)
                 return false;
 #endif
             emit commitData(editor);
             emit closeEditor(editor, NoHint);
         }
     } else if (event->type() == QEvent::ShortcutOverride) {
         if (static_cast<QKeyEvent*>(event)->key() == Qt::Key_Escape) {
             event->accept();
             return true;
         }
     }
     return false;
 }
initStyleOption()
void QStyledItemDelegate::initStyleOption (QStyleOptionViewItem * option, const QModelIndex & index) const protected virtual
Initialize option with the values using the index index.
This method is useful for subclasses when they need a QStyleOptionViewItem, but don't want to fill in all the information themselves. This function will check the version of the QStyleOptionViewItem and fill in the additional values for a QStyleOptionViewItemV2, QStyleOptionViewItemV3 and QStyleOptionViewItemV4.
See also
QStyleOption::initFrom()
Reimplemented in QSideBarDelegate.
Definition at line 322 of file qstyleditemdelegate.cpp.
Referenced by editorEvent(), QSideBarDelegate::initStyleOption(), paint(), sizeHint(), and updateEditorGeometry().
 {
     QVariant value = index.data(Qt::FontRole);
     if (value.isValid() && !value.isNull()) {
         option->font = qvariant_cast<QFont>(value).resolve(option->font);
         option->fontMetrics = QFontMetrics(option->font);
     }
     value = index.data(Qt::TextAlignmentRole);
     if (value.isValid() && !value.isNull())
         option->displayAlignment = Qt::Alignment(value.toInt());
     value = index.data(Qt::ForegroundRole);
     if (value.canConvert<QBrush>())
         option->palette.setBrush(QPalette::Text, qvariant_cast<QBrush>(value));
     if (QStyleOptionViewItemV4 *v4 = qstyleoption_cast<QStyleOptionViewItemV4 *>(option)) {
         v4->index = index;
         QVariant value = index.data(Qt::CheckStateRole);
         if (value.isValid() && !value.isNull()) {
             v4->features |= QStyleOptionViewItemV2::HasCheckIndicator;
             v4->checkState = static_cast<Qt::CheckState>(value.toInt());
         }
         value = index.data(Qt::DecorationRole);
         if (value.isValid() && !value.isNull()) {
             v4->features |= QStyleOptionViewItemV2::HasDecoration;
             switch (value.type()) {
             case QVariant::Icon: {
                 v4->icon = qvariant_cast<QIcon>(value);
                 QIcon::Mode mode;
                 if (!(option->state & QStyle::State_Enabled))
                     mode = QIcon::Disabled;
                 else if (option->state & QStyle::State_Selected)
                     mode = QIcon::Selected;
                 else
                     mode = QIcon::Normal;
                 QIcon::State state = option->state & QStyle::State_Open ? QIcon::On : QIcon::Off;
                 v4->decorationSize = v4->icon.actualSize(option->decorationSize, mode, state);
                 break;
             }
             case QVariant::Color: {
                 QPixmap pixmap(option->decorationSize);
                 pixmap.fill(qvariant_cast<QColor>(value));
                 v4->icon = QIcon(pixmap);
                 break;
             }
             case QVariant::Image: {
                 QImage image = qvariant_cast<QImage>(value);
                 v4->icon = QIcon(QPixmap::fromImage(image));
                 v4->decorationSize = image.size();
                 break;
             }
             case QVariant::Pixmap: {
                 QPixmap pixmap = qvariant_cast<QPixmap>(value);
                 v4->icon = QIcon(pixmap);
                 v4->decorationSize = pixmap.size();
                 break;
             }
             default:
                 break;
             }
         }
         value = index.data(Qt::DisplayRole);
         if (value.isValid() && !value.isNull()) {
             v4->features |= QStyleOptionViewItemV2::HasDisplay;
             v4->text = displayText(value, v4->locale);
         }
         v4->backgroundBrush = qvariant_cast<QBrush>(index.data(Qt::BackgroundRole));
     }
 }
itemEditorFactory()
QItemEditorFactory * QStyledItemDelegate::itemEditorFactory () const
Returns the editor factory used by the item delegate.
If no editor factory is set, the function will return null.
See also
setItemEditorFactory()
Definition at line 592 of file qstyleditemdelegate.cpp.
 {
     Q_D(const QStyledItemDelegate);
     return d->factory;
 }
paint()
void QStyledItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Renders the delegate using the given painter and style option for the item specified by index.
This function paints the item using the view's QStyle.
When reimplementing paint in a subclass. Use the initStyleOption() to set up the option in the same way as the QStyledItemDelegate; the option will always be an instance of QStyleOptionViewItemV4. Please see its class description for information on its contents.
Whenever possible, use the option while painting. Especially its QStyleOption::rect variable to decide where to draw and its QStyleOption::state to determine if it is enabled or selected.
After painting, you should ensure that the painter is returned to its the state it was supplied in when this function was called. For example, it may be useful to call QPainter::save() before painting and QPainter::restore() afterwards.
See also
QItemDelegate::paint(), QStyle::drawControl(), QStyle::CE_ItemViewItem
Implements QAbstractItemDelegate.
Reimplemented in QScriptDebuggerLocalsItemDelegate.
Definition at line 421 of file qstyleditemdelegate.cpp.
Referenced by QScriptDebuggerLocalsItemDelegate::paint().
 {
     Q_ASSERT(index.isValid());
     QStyleOptionViewItemV4 opt = option;
     initStyleOption(&opt, index);
     const QWidget *widget = QStyledItemDelegatePrivate::widget(option);
     QStyle *style = widget ? widget->style() : QApplication::style();
     style->drawControl(QStyle::CE_ItemViewItem, &opt, painter, widget);
 }
setEditorData()
void QStyledItemDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const virtual
Sets the data to be displayed and edited by the editor from the data model item specified by the model index.
The default implementation stores the data in the editor widget's Qt's Property System.
See also
QMetaProperty::isUser()
Reimplemented from QAbstractItemDelegate.
Definition at line 485 of file qstyleditemdelegate.cpp.
 {
 #ifdef QT_NO_PROPERTIES
     Q_UNUSED(editor);
     Q_UNUSED(index);
 #else
     Q_D(const QStyledItemDelegate);
     QVariant v = index.data(Qt::EditRole);
     QByteArray n = editor->metaObject()->userProperty().name();
     // ### Qt 5: remove
     // A work-around for missing "USER true" in qdatetimeedit.h for
     // QTimeEdit's time property and QDateEdit's date property.
     // It only triggers if the default user property "dateTime" is
     // reported for QTimeEdit and QDateEdit.
     if (n == "dateTime") {
         if (editor->inherits("QTimeEdit"))
             n = "time";
         else if (editor->inherits("QDateEdit"))
             n = "date";
     }
     // ### Qt 5: give QComboBox a USER property
     if (n.isEmpty() && editor->inherits("QComboBox"))
         n = d->editorFactory()->valuePropertyName(static_cast<QVariant::Type>(v.userType()));
     if (!n.isEmpty()) {
         if (!v.isValid())
             v = QVariant(editor->property(n).userType(), (const void *)0);
         editor->setProperty(n, v);
     }
 #endif
 }
setItemEditorFactory()
void QStyledItemDelegate::setItemEditorFactory (QItemEditorFactory * factory)
Sets the editor factory to be used by the item delegate to be the factory specified.
If no editor factory is set, the item delegate will use the default editor factory.
See also
itemEditorFactory()
Definition at line 605 of file qstyleditemdelegate.cpp.
 {
     Q_D(QStyledItemDelegate);
     d->factory = factory;
 }
setModelData()
void QStyledItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const virtual
Gets data from the editor widget and stores it in the specified model at the item index.
The default implementation gets the value to be stored in the data model from the editor widget's Qt's Property System.
See also
QMetaProperty::isUser()
Reimplemented from QAbstractItemDelegate.
Reimplemented in QScriptBreakpointsItemDelegate, and QScriptDebuggerLocalsItemDelegate.
Definition at line 527 of file qstyleditemdelegate.cpp.
Referenced by QScriptDebuggerLocalsItemDelegate::setModelData(), and QScriptBreakpointsItemDelegate::setModelData().
 {
 #ifdef QT_NO_PROPERTIES
     Q_UNUSED(model);
     Q_UNUSED(editor);
     Q_UNUSED(index);
 #else
     Q_D(const QStyledItemDelegate);
     Q_ASSERT(model);
     Q_ASSERT(editor);
     QByteArray n = editor->metaObject()->userProperty().name();
     if (n.isEmpty())
         n = d->editorFactory()->valuePropertyName(
             static_cast<QVariant::Type>(model->data(index, Qt::EditRole).userType()));
     if (!n.isEmpty())
         model->setData(index, editor->property(n), Qt::EditRole);
 #endif
 }
sizeHint()
QSize QStyledItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Returns the size needed by the delegate to display the item specified by index, taking into account the style information provided by option.
This function uses the view's QStyle to determine the size of the item.
See also
QStyle::sizeFromContents(), QStyle::CT_ItemViewItem
Implements QAbstractItemDelegate.
Definition at line 444 of file qstyleditemdelegate.cpp.
 {
     QVariant value = index.data(Qt::SizeHintRole);
     if (value.isValid())
         return qvariant_cast<QSize>(value);
     QStyleOptionViewItemV4 opt = option;
     initStyleOption(&opt, index);
     const QWidget *widget = QStyledItemDelegatePrivate::widget(option);
     QStyle *style = widget ? widget->style() : QApplication::style();
     return style->sizeFromContents(QStyle::CT_ItemViewItem, &opt, QSize(), widget);
 }
updateEditorGeometry()
void QStyledItemDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Updates the editor for the item specified by index according to the style option given.
Reimplemented from QAbstractItemDelegate.
Definition at line 552 of file qstyleditemdelegate.cpp.
 {
     if (!editor)
         return;
     Q_ASSERT(index.isValid());
     const QWidget *widget = QStyledItemDelegatePrivate::widget(option);
     QStyleOptionViewItemV4 opt = option;
     initStyleOption(&opt, index);
     // let the editor take up all available space
     //if the editor is not a QLineEdit
     //or it is in a QTableView
 #if !defined(QT_NO_TABLEVIEW) && !defined(QT_NO_LINEEDIT)
     if (qobject_cast<QExpandingLineEdit*>(editor) && !qobject_cast<const QTableView*>(widget))
         opt.showDecorationSelected = editor->style()->styleHint(QStyle::SH_ItemView_ShowDecorationSelected, 0, editor);
     else
 #endif
         opt.showDecorationSelected = true;
     QStyle *style = widget ? widget->style() : QApplication::style();
     QRect geom = style->subElementRect(QStyle::SE_ItemViewItemText, &opt, widget);
     if ( editor->layoutDirection() == Qt::RightToLeft) {
         const int delta = qSmartMinSize(editor).width() - geom.width();
         if (delta > 0) {
             //we need to widen the geometry
             geom.adjust(-delta, 0, 0, 0);
         }
     }
     editor->setGeometry(geom);
 }
The documentation for this class was generated from the following files:
/src/gui/itemviews/qstyleditemdelegate.h
/src/gui/itemviews/qstyleditemdelegate.cpp