Qt 4.8: QBBClipboard::MimeData Class Reference
QBBClipboard::MimeData Class Reference
Public Functions
void addFormatToCheck (const QString &format)
QStringList formats () const
Returns a list of formats supported by the object.
bool hasFormat (const QString &mimetype) const
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
MimeData (QBBClipboard *clipboard)
void setUserMimeData (QMimeData *userMimeData)
QMimeData * userMimeData ()
~MimeData ()
Public Functions inherited from QMimeData
void clear ()
Removes all the MIME type and data entries in the object.
QVariant colorData () const
Returns a color if the data stored in the object represents a color (MIME type application/x-color); otherwise returns a null variant.
QByteArray data (const QString &mimetype) const
Returns the data stored in the object in the format described by the MIME type specified by mimeType.
bool hasColor () const
Returns true if the object can return a color (MIME type application/x-color); otherwise returns false.
bool hasHtml () const
Returns true if the object can return HTML (MIME type text/html); otherwise returns false.
bool hasImage () const
Returns true if the object can return an image; otherwise returns false.
bool hasText () const
Returns true if the object can return plain text (MIME type text/plain); otherwise returns false.
bool hasUrls () const
Returns true if the object can return a list of urls; otherwise returns false.
QString html () const
Returns a string if the data stored in the object is HTML (MIME type text/html); otherwise returns an empty string.
QVariant imageData () const
Returns a QVariant storing a QImage if the object can return an image; otherwise returns a null variant.
QMimeData ()
Constructs a new MIME data object with no data in it.
void removeFormat (const QString &mimetype)
Removes the data entry for mimeType in the object.
void setColorData (const QVariant &color)
Sets the color data in the object to the given color.
void setData (const QString &mimetype, const QByteArray &data)
Sets the data associated with the MIME type given by mimeType to the specified data.
void setHtml (const QString &html)
Sets html as the HTML (MIME type text/html) used to represent the data.
void setImageData (const QVariant &image)
Sets the data in the object to the given image.
void setText (const QString &text)
Sets text as the plain text (MIME type text/plain) used to represent the data.
void setUrls (const QList< QUrl > &urls)
Sets the URLs stored in the MIME data object to those specified by urls.
QString text () const
Returns a plain text (MIME type text/plain) representation of the data.
QList< QUrl > urls () const
Returns a list of URLs contained within the MIME data object.
~QMimeData ()
Destroys the MIME data object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QVariant retrieveData (const QString &mimetype, QVariant::Type preferredType) const
Returns a variant with the given type containing data for the MIME type specified by mimeType.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void releaseOwnership ()
Properties
QBBClipboard *const m_clipboard
QSet< QString > m_formatsToCheck
QMimeData * m_userMimeData
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 75 of file qbbclipboard.cpp.
Constructors and Destructors
MimeData()
QBBClipboard::MimeData::MimeData (QBBClipboard * clipboard) inline
Definition at line 79 of file qbbclipboard.cpp.
         : QMimeData(),
           m_clipboard(clipboard),
           m_userMimeData(0)
     {
         Q_ASSERT(clipboard);
         for (int i = 0; typeList[i] != 0; ++i) {
             m_formatsToCheck << QString::fromUtf8(typeList[i]);
         }
     }
~MimeData()
QBBClipboard::MimeData::~MimeData () inline
Definition at line 91 of file qbbclipboard.cpp.
     {
         delete m_userMimeData;
     }
Functions
addFormatToCheck()
void QBBClipboard::MimeData::addFormatToCheck (const QString & format) inline
Definition at line 96 of file qbbclipboard.cpp.
Referenced by QBBClipboard::setMimeData().
{
         m_formatsToCheck << format;
 #if defined(QBBCLIPBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "formats=" << m_formatsToCheck;
 #endif
     }
formats()
QStringList QBBClipboard::MimeData::formats () const inline virtual
Returns a list of formats supported by the object.
This is a list of MIME types for which the object can return suitable data. The formats in the list are in a priority order.
For the most common types of data, you can call the higher-level functions hasText(), hasHtml(), hasUrls(), hasImage(), and hasColor() instead.
See also
hasFormat(), setData(), data()
Reimplemented from QMimeData.
Definition at line 113 of file qbbclipboard.cpp.
Referenced by releaseOwnership().
     {
         QStringList result;
         Q_FOREACH (const QString &format, m_formatsToCheck) {
             if (is_clipboard_format_present(format.toUtf8().constData()) == 0)
                 result << format;
         }
 #if defined(QBBCLIPBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "result=" << result;
 #endif
         return result;
     }
hasFormat()
bool QBBClipboard::MimeData::hasFormat (const QString & mimeType) const inline virtual
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
For the most common types of data, you can call the higher-level functions hasText(), hasHtml(), hasUrls(), hasImage(), and hasColor() instead.
See also
formats(), setData(), data()
Reimplemented from QMimeData.
Definition at line 104 of file qbbclipboard.cpp.
     {
         const bool result = is_clipboard_format_present(mimetype.toUtf8().constData()) == 0;
 #if defined(QBBCLIPBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "mimetype=" << mimetype << "result=" << result;
 #endif
         return result;
     }
releaseOwnership
void QBBClipboard::MimeData::releaseOwnership () inline private slot
Definition at line 159 of file qbbclipboard.cpp.
     {
         if (m_userMimeData) {
 #if defined(QBBCLIPBOARD_DEBUG)
             qDebug() << Q_FUNC_INFO << "user data formats=" << m_userMimeData->formats() << "system formats=" << formats();
 #endif
             delete m_userMimeData;
             m_userMimeData = 0;
             m_clipboard->emitChanged(QClipboard::Clipboard);
         }
     }
retrieveData()
QVariant QBBClipboard::MimeData::retrieveData (const QString & mimeType, QVariant::Type type) const inline protected virtual
Returns a variant with the given type containing data for the MIME type specified by mimeType.
If the object does not support the MIME type or variant type given, a null variant is returned instead.
This function is called by the general data() getter and by the convenience getters (text(), html(), urls(), imageData(), and colorData()). You can reimplement it if you want to store your data using a custom data structure (instead of a QByteArray, which is what setData() provides). You would then also need to reimplement hasFormat() and formats().
See also
data()
Reimplemented from QMimeData.
Definition at line 146 of file qbbclipboard.cpp.
     {
 #if defined(QBBCLIPBOARD_DEBUG)
         qDebug() << Q_FUNC_INFO << "mimetype=" << mimetype << "preferredType=" << preferredType;
 #endif
         if (is_clipboard_format_present(mimetype.toUtf8().constData()) != 0)
             return QMimeData::retrieveData(mimetype, preferredType);
         const QByteArray data = readClipboardBuff(mimetype.toUtf8().constData());
         return qVariantFromValue(data);
     }
setUserMimeData()
void QBBClipboard::MimeData::setUserMimeData (QMimeData * userMimeData) inline
Definition at line 128 of file qbbclipboard.cpp.
Referenced by QBBClipboard::setMimeData().
     {
         delete m_userMimeData;
         m_userMimeData = userMimeData;
         // system clipboard API doesn't allow detection of changes by other applications
         // simulate an owner change through delayed invocation
         // basically transfer ownership of data to the system clipboard once event processing resumes
         if (m_userMimeData)
             QMetaObject::invokeMethod(this, "releaseOwnership", Qt::QueuedConnection);
     }
userMimeData()
QMimeData* QBBClipboard::MimeData::userMimeData () inline
Definition at line 140 of file qbbclipboard.cpp.
Referenced by QBBClipboard::mimeData(), QBBClipboard::setMimeData(), and setUserMimeData().
     {
         return m_userMimeData;
     }
Properties
m_clipboard
QBBClipboard* const QBBClipboard::MimeData::m_clipboard private
Definition at line 172 of file qbbclipboard.cpp.
Referenced by releaseOwnership().
m_formatsToCheck
QSet<QString> QBBClipboard::MimeData::m_formatsToCheck private
Definition at line 174 of file qbbclipboard.cpp.
Referenced by addFormatToCheck(), formats(), and MimeData().
m_userMimeData
QMimeData* QBBClipboard::MimeData::m_userMimeData private
Definition at line 175 of file qbbclipboard.cpp.
Referenced by releaseOwnership(), setUserMimeData(), userMimeData(), and ~MimeData().
The documentation for this class was generated from the following file:
/src/plugins/platforms/blackberry/qbbclipboard.cpp