Qt 4.8: QPatternist::XsdParticle Class Reference
QPatternist::XsdParticle Class Reference
XML Schema Processing
Represents a XSD particle object.
#include <qxsdparticle_p.h>
Public Types
typedef QList< XsdParticle::Ptr > List
typedef QExplicitlySharedDataPointer< XsdParticle > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
unsigned int maximumOccurs () const
bool maximumOccursUnbounded () const
unsigned int minimumOccurs () const
void setMaximumOccurs (unsigned int occurrence)
void setMaximumOccursUnbounded (bool unbounded)
void setMinimumOccurs (unsigned int occurrence)
void setTerm (const XsdTerm::Ptr &term)
XsdTerm::Ptr term () const
XsdParticle ()
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Properties
unsigned int m_maximumOccurs
bool m_maximumOccursUnbounded
unsigned int m_minimumOccurs
XsdTerm::Ptr m_term
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Represents a XSD particle object.
This class represents the particle object of a XML schema as described here.
It contains information about the number of occurrence and a reference to either an element object, a group object or an any object.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 79 of file qxsdparticle_p.h.
Typedefs
List
typedef QList<XsdParticle::Ptr> QPatternist::XsdParticle::List
Definition at line 83 of file qxsdparticle_p.h.
Ptr
typedef QExplicitlySharedDataPointer<XsdParticle> QPatternist::XsdParticle::Ptr
Definition at line 82 of file qxsdparticle_p.h.
Constructors and Destructors
XsdParticle()
XsdParticle::XsdParticle ()
Creates a new particle object.
Definition at line 48 of file qxsdparticle.cpp.
     : m_minimumOccurs(1)
     , m_maximumOccurs(1)
     , m_maximumOccursUnbounded(false)
 {
 }
Functions
maximumOccurs()
unsigned int XsdParticle::maximumOccurs () const
Returns the maximum occurrence of the particle.
Note
This value has only a meaning if maximumOccursUnbounded is false.
Definition at line 70 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildParticle(), QPatternist::XsdSchemaDebugger::dumpParticle(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), and QPatternist::XsdSchemaResolver::resolveTermReference().
 {
     return m_maximumOccurs;
 }
maximumOccursUnbounded()
bool XsdParticle::maximumOccursUnbounded () const
Returns whether the maximum occurrence of the particle is unbounded.
Definition at line 80 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildParticle(), QPatternist::XsdSchemaDebugger::dumpParticle(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), and QPatternist::XsdSchemaResolver::resolveTermReference().
 {
     return m_maximumOccursUnbounded;
 }
minimumOccurs()
unsigned int XsdParticle::minimumOccurs () const
Returns the minimum occurrence of the particle.
Definition at line 60 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildParticle(), QPatternist::XsdSchemaDebugger::dumpParticle(), effectiveTotalRangeMinimum(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), QPatternist::XsdSchemaHelper::isParticleEmptiable(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdSchemaResolver::resolveTermReference().
 {
     return m_minimumOccurs;
 }
setMaximumOccurs()
void XsdParticle::setMaximumOccurs (unsigned int occurrence)
Sets the maximum occurrence of the particle.
See also
Maximum Occurrence Definition
Definition at line 65 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_maximumOccurs = occurs;
 }
setMaximumOccursUnbounded()
void XsdParticle::setMaximumOccursUnbounded (bool unbounded)
Sets whether the maximum occurrence of the particle is unbounded.
See also
Maximum Occurrence Definition
Definition at line 75 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_maximumOccursUnbounded = unbounded;
 }
setMinimumOccurs()
void XsdParticle::setMinimumOccurs (unsigned int occurrence)
Sets the minimum occurrence of the particle.
See also
Minimum Occurrence Definition
Definition at line 55 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_minimumOccurs = occurs;
 }
setTerm()
void XsdParticle::setTerm (const XsdTerm::Ptr & term)
Sets the term of the particle.
The term can be an element, a model group or an element wildcard.
See also
Term Definition
Definition at line 85 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaResolver::checkRedefinedGroups(), QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveTermReference(), QPatternist::XsdSchemaResolver::resolveTermReferences(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_term = term;
 }
term()
XsdTerm::Ptr XsdParticle::term () const
Returns the term of the particle.
Definition at line 90 of file qxsdparticle.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildParticle(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), collectAllElements(), collectGroupRef(), QPatternist::XsdSchemaDebugger::dumpParticle(), effectiveTotalRangeMinimum(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), hasDuplicatedElementsInternal(), internalParticleLookupMap(), QPatternist::XsdSchemaHelper::isParticleEmptiable(), QPatternist::XsdParticleChecker::isUPAConform(), QPatternist::XsdParticleChecker::isUPAConformXsdAll(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), QPatternist::XsdSchemaResolver::resolveTermReference(), and setTerm().
 {
     return m_term;
 }
Properties
m_maximumOccurs
unsigned int QPatternist::XsdParticle::m_maximumOccurs private
Definition at line 144 of file qxsdparticle_p.h.
Referenced by maximumOccurs(), and setMaximumOccurs().
m_maximumOccursUnbounded
bool QPatternist::XsdParticle::m_maximumOccursUnbounded private
Definition at line 145 of file qxsdparticle_p.h.
Referenced by maximumOccursUnbounded(), and setMaximumOccursUnbounded().
m_minimumOccurs
unsigned int QPatternist::XsdParticle::m_minimumOccurs private
Definition at line 143 of file qxsdparticle_p.h.
Referenced by minimumOccurs(), and setMinimumOccurs().
m_term
XsdTerm::Ptr QPatternist::XsdParticle::m_term private
Definition at line 146 of file qxsdparticle_p.h.
Referenced by setTerm(), and term().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdparticle_p.h
/src/xmlpatterns/schema/qxsdparticle.cpp