Qt 4.8: QPatternist::CallTargetDescription Class Reference
QPatternist::CallTargetDescription Class Reference
Contains metadata for a callable component, such as a function or template.
#include <qcalltargetdescription_p.h>
Public Types
typedef QList< Ptr > List
typedef QExplicitlySharedDataPointer< CallTargetDescription > Ptr
Public Functions
CallTargetDescription (const QXmlName &name)
QXmlName name () const
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static void checkCallsiteCircularity (CallTargetDescription::List &signList, const Expression::Ptr expr)
Static Private Functions
static void checkArgumentsCircularity (CallTargetDescription::List &signList, const Expression::Ptr callsite)
Properties
const QXmlName m_name
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Contains metadata for a callable component, such as a function or template.
CallTargetDescription can be used directly and is so for templates, but can also be sub-classed which FunctionSignature do.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 80 of file qcalltargetdescription_p.h.
Typedefs
List
typedef QList<Ptr> QPatternist::CallTargetDescription::List
Definition at line 84 of file qcalltargetdescription_p.h.
Ptr
typedef QExplicitlySharedDataPointer<CallTargetDescription> QPatternist::CallTargetDescription::Ptr
Definition at line 83 of file qcalltargetdescription_p.h.
Constructors and Destructors
CallTargetDescription()
CallTargetDescription::CallTargetDescription (const QXmlName & name)
Definition at line 50 of file qcalltargetdescription.cpp.
                                                                  : m_name(name)
 {
     Q_ASSERT(!m_name.isNull());
 }
Functions
checkArgumentsCircularity()
void CallTargetDescription::checkArgumentsCircularity (CallTargetDescription::List & signList, const Expression::Ptr callsite) static private
Helper function for checkCallsiteCircularity(). If C++ allowed it, it would have been local to it.
Definition at line 60 of file qcalltargetdescription.cpp.
Referenced by checkCallsiteCircularity().
 {
     /* Check the arguments. */
     const Expression::List ops(callsite->operands());
     const Expression::List::const_iterator end(ops.constEnd());
     Expression::List::const_iterator it(ops.constBegin());
     for(; it != end; ++it)
         checkCallsiteCircularity(signList, *it);
 }
checkCallsiteCircularity()
void CallTargetDescription::checkCallsiteCircularity (CallTargetDescription::List & signList, const Expression::Ptr expr) static
Flags callsites to be aware of their recursion by calling UserFunctionCallsite::configureRecursion(), if that is the case.
Note
We pass expr by value here intentionally.
Definition at line 72 of file qcalltargetdescription.cpp.
Referenced by checkArgumentsCircularity(), and QPatternist::yyparse().
 {
     Q_ASSERT(expr);
     if(expr->is(Expression::IDUserFunctionCallsite))
     {
         CallTargetDescription::List::const_iterator it(signList.constBegin());
         const CallTargetDescription::List::const_iterator end(signList.constEnd());
         CallSite *const callsite = static_cast<CallSite *>(expr.data());
         for(; it != end; ++it)
         {
             if(callsite->configureRecursion(*it))
             {
                 /* A callsite inside the function body to the function. This user function
                  * is recursive if it's to the same function, in other words. Which it was
                  * if configureRecursion() returned true. */
                 /* Now we continue and check the arguments of the callsite. That is, the arguments.
                  * This catches for instance local:foo(local:foo(3)). */
                 checkArgumentsCircularity(signList, expr);
                 return;
             }
         }
         /* Check the body of the function so this callsite isn't "indirectly" a
          * recursive call to the function we're checking. XQTS test case
          * default_namespace-011 is an example of this. */
         signList.append(callsite->callTargetDescription());
         checkCallsiteCircularity(signList, callsite->body());
     }
     checkArgumentsCircularity(signList, expr); /* We're done in this case. */
 }
name()
QXmlName CallTargetDescription::name () const
The function's name. For example, the name of the signature fn:string() as xs:string is fn:string.
Definition at line 55 of file qcalltargetdescription.cpp.
Referenced by QPatternist::FunctionSignature::displayName(), QPatternist::UserFunctionCallsite::isSignatureValid(), QPatternist::FunctionSignature::operator==(), and QPatternist::ErrorFN::signature().
 {
     return m_name;
 }
Properties
m_name
const QXmlName QPatternist::CallTargetDescription::m_name private
Definition at line 111 of file qcalltargetdescription_p.h.
Referenced by CallTargetDescription(), and name().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qcalltargetdescription_p.h
/src/xmlpatterns/expr/qcalltargetdescription.cpp