Qt 4.8: QAbstractProxyModel Class Reference
QAbstractProxyModel Class Reference abstract
The QAbstractProxyModel class provides a base class for proxy item models that can do sorting, filtering or other data processing tasks.
#include <qabstractproxymodel.h>
Public Functions
QModelIndex buddy (const QModelIndex &index) const
Reimplemented Function
bool canFetchMore (const QModelIndex &parent) const
Reimplemented Function
QVariant data (const QModelIndex &proxyIndex, int role=Qt::DisplayRole) const
Reimplemented Function
void fetchMore (const QModelIndex &parent)
Reimplemented Function
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role) const
Reimplemented Function
QMap< int, QVariant > itemData (const QModelIndex &index) const
Reimplemented Function
virtual QModelIndex mapFromSource (const QModelIndex &sourceIndex) const =0
Reimplement this function to return the model index in the proxy model that corresponds to the sourceIndex from the source model.
virtual QItemSelection mapSelectionFromSource (const QItemSelection &selection) const
Returns a proxy selection mapped from the specified sourceSelection.
virtual QItemSelection mapSelectionToSource (const QItemSelection &selection) const
Returns a source selection mapped from the specified proxySelection.
virtual QModelIndex mapToSource (const QModelIndex &proxyIndex) const =0
Reimplement this function to return the model index in the source model that corresponds to the proxyIndex in the proxy model.
QMimeData * mimeData (const QModelIndexList &indexes) const
Reimplemented Function
QStringList mimeTypes () const
Reimplemented Function
QAbstractProxyModel (QObject *parent=0)
Constructs a proxy model with the given parent.
void revert ()
Reimplemented Function
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Reimplemented Function
virtual void setSourceModel (QAbstractItemModel *sourceModel)
Sets the given sourceModel to be processed by the proxy model.
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
QAbstractItemModel * sourceModel () const
Returns the model that contains the data that is available through the proxy model.
QSize span (const QModelIndex &index) const
Reimplemented Function
bool submit ()
Reimplemented Function
Qt::DropActions supportedDropActions () const
Reimplemented Function
~QAbstractProxyModel ()
Destroys the proxy model.
Public Functions inherited from QAbstractItemModel
virtual int columnCount (const QModelIndex &parent=QModelIndex()) const =0
Returns the number of columns for the children of the given parent.
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
virtual QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const =0
Returns the index of the item in the model specified by the given row, column and parent index.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QModelIndex parent (const QModelIndex &child) const =0
Returns the parent of the model item with the given index.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual int rowCount (const QModelIndex &parent=QModelIndex()) const =0
Returns the number of rows under the given parent.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QAbstractProxyModel (QAbstractProxyModelPrivate &, QObject *parent)
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractProxyModel class provides a base class for proxy item models that can do sorting, filtering or other data processing tasks.
Since
4.1
This class defines the standard interface that proxy models must use to be able to interoperate correctly with other model/view components. It is not supposed to be instantiated directly.
All standard proxy models are derived from the QAbstractProxyModel class. If you need to create a new proxy model class, it is usually better to subclass an existing class that provides the closest behavior to the one you want to provide.
Proxy models that filter or sort items of data from a source model should be created by using or subclassing QSortFilterProxyModel.
To subclass QAbstractProxyModel, you need to implement mapFromSource() and mapToSource(). The mapSelectionFromSource() and mapSelectionToSource() functions only need to be reimplemented if you need a behavior different from the default behavior.
Note
If the source model is deleted or no source model is specified, the proxy model operates on a empty placeholder model.
See also
QSortFilterProxyModel, QAbstractItemModel, {Model/View Programming}
Definition at line 58 of file qabstractproxymodel.h.
Constructors and Destructors
QAbstractProxyModel() [1/2]
QAbstractProxyModel::QAbstractProxyModel (QObject * parent = 0)
Constructs a proxy model with the given parent.
Definition at line 97 of file qabstractproxymodel.cpp.
     :QAbstractItemModel(*new QAbstractProxyModelPrivate, parent)
 {
     setSourceModel(QAbstractItemModelPrivate::staticEmptyModel());
 }
~QAbstractProxyModel()
QAbstractProxyModel::~QAbstractProxyModel ()
Destroys the proxy model.
Definition at line 116 of file qabstractproxymodel.cpp.
 {
 }
QAbstractProxyModel() [2/2]
QAbstractProxyModel::QAbstractProxyModel (QAbstractProxyModelPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 107 of file qabstractproxymodel.cpp.
     : QAbstractItemModel(dd, parent)
 {
     setSourceModel(QAbstractItemModelPrivate::staticEmptyModel());
 }
Functions
buddy()
QModelIndex QAbstractProxyModel::buddy (const QModelIndex & index) const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 310 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     return mapFromSource(d->model->buddy(mapToSource(index)));
 }
canFetchMore()
bool QAbstractProxyModel::canFetchMore (const QModelIndex & parent) const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 320 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     return d->model->canFetchMore(mapToSource(parent));
 }
data()
QVariant QAbstractProxyModel::data (const QModelIndex & proxyIndex, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Reimplemented in QCompletionModel, and QSortFilterProxyModel.
Definition at line 232 of file qabstractproxymodel.cpp.
 {
     Q_D(const QAbstractProxyModel);
     return d->model->data(mapToSource(proxyIndex), role);
 }
fetchMore()
void QAbstractProxyModel::fetchMore (const QModelIndex & parent) virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 330 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(QAbstractProxyModel);
     d->model->fetchMore(mapToSource(parent));
 }
flags()
Qt::ItemFlags QAbstractProxyModel::flags (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 266 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     return d->model->flags(mapToSource(index));
 }
hasChildren()
bool QAbstractProxyModel::hasChildren (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QCompletionModel, and QSortFilterProxyModel.
Definition at line 360 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     return d->model->hasChildren(mapToSource(parent));
 }
headerData()
QVariant QAbstractProxyModel::headerData (int section, Qt::Orientation orientation, int role) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 241 of file qabstractproxymodel.cpp.
Referenced by QSortFilterProxyModel::headerData(), and QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     int sourceSection;
     if (orientation == Qt::Horizontal) {
         const QModelIndex proxyIndex = index(0, section);
         sourceSection = mapToSource(proxyIndex).column();
     } else {
         const QModelIndex proxyIndex = index(section, 0);
         sourceSection = mapToSource(proxyIndex).row();
     }
     return d->model->headerData(sourceSection, orientation, role);
 }
itemData()
QMap< int, QVariant > QAbstractProxyModel::itemData (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 258 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     return QAbstractItemModel::itemData(proxyIndex);
 }
mapFromSource()
QModelIndex QAbstractProxyModel::mapFromSource (const QModelIndex & sourceIndex) const pure virtual
Reimplement this function to return the model index in the proxy model that corresponds to the sourceIndex from the source model.
See also
mapToSource()
Implemented in QCompletionModel, QSortFilterProxyModel, and QIdentityProxyModel.
Referenced by buddy(), and mapSelectionFromSource().
mapSelectionFromSource()
QItemSelection QAbstractProxyModel::mapSelectionFromSource (const QItemSelection & sourceSelection) const virtual
Returns a proxy selection mapped from the specified sourceSelection.
Reimplement this method to map source selections to proxy selections.
Reimplemented in QSortFilterProxyModel, and QIdentityProxyModel.
Definition at line 216 of file qabstractproxymodel.cpp.
Referenced by QSortFilterProxyModel::mapSelectionFromSource().
 {
     QModelIndexList sourceIndexes = sourceSelection.indexes();
     QItemSelection proxySelection;
     for (int i = 0; i < sourceIndexes.size(); ++i) {
         const QModelIndex srcIdx = mapFromSource(sourceIndexes.at(i));
         if (!srcIdx.isValid())
             continue;
         proxySelection << QItemSelectionRange(srcIdx);
     }
     return proxySelection;
 }
mapSelectionToSource()
QItemSelection QAbstractProxyModel::mapSelectionToSource (const QItemSelection & proxySelection) const virtual
Returns a source selection mapped from the specified proxySelection.
Reimplement this method to map proxy selections to source selections.
Reimplemented in QSortFilterProxyModel, and QIdentityProxyModel.
Definition at line 198 of file qabstractproxymodel.cpp.
Referenced by QSortFilterProxyModel::mapSelectionToSource().
 {
     QModelIndexList proxyIndexes = proxySelection.indexes();
     QItemSelection sourceSelection;
     for (int i = 0; i < proxyIndexes.size(); ++i) {
         const QModelIndex proxyIdx = mapToSource(proxyIndexes.at(i));
         if (!proxyIdx.isValid())
             continue;
         sourceSelection << QItemSelectionRange(proxyIdx);
     }
     return sourceSelection;
 }
mapToSource()
QModelIndex QAbstractProxyModel::mapToSource (const QModelIndex & proxyIndex) const pure virtual
Reimplement this function to return the model index in the source model that corresponds to the proxyIndex in the proxy model.
See also
mapFromSource()
Implemented in QCompletionModel, QSortFilterProxyModel, and QIdentityProxyModel.
Referenced by buddy(), canFetchMore(), data(), fetchMore(), flags(), hasChildren(), headerData(), mapSelectionToSource(), mimeData(), setData(), setHeaderData(), and span().
mimeData()
QMimeData * QAbstractProxyModel::mimeData (const QModelIndexList & indexes) const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 370 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     QModelIndexList list;
     foreach(const QModelIndex &index, indexes)
         list << mapToSource(index);
     return d->model->mimeData(list);
 }
mimeTypes()
QStringList QAbstractProxyModel::mimeTypes () const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 383 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     return d->model->mimeTypes();
 }
revert()
void QAbstractProxyModel::revert () virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 162 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(QAbstractProxyModel);
     d->model->revert();
 }
setData()
bool QAbstractProxyModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 275 of file qabstractproxymodel.cpp.
 {
     Q_D(QAbstractProxyModel);
     return d->model->setData(mapToSource(index), value, role);
 }
setHeaderData()
bool QAbstractProxyModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 292 of file qabstractproxymodel.cpp.
Referenced by QSortFilterProxyModel::setHeaderData(), and QAbstractItemModel::sibling().
 {
     Q_D(QAbstractProxyModel);
     int sourceSection;
     if (orientation == Qt::Horizontal) {
         const QModelIndex proxyIndex = index(0, section);
         sourceSection = mapToSource(proxyIndex).column();
     } else {
         const QModelIndex proxyIndex = index(section, 0);
         sourceSection = mapToSource(proxyIndex).row();
     }
     return d->model->setHeaderData(sourceSection, orientation, value, role);
 }
setItemData()
bool QAbstractProxyModel::setItemData (const QModelIndex & index, const QMap< int, QVariant > & roles) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 284 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     return QAbstractItemModel::setItemData(index, roles);
 }
setSourceModel()
void QAbstractProxyModel::setSourceModel (QAbstractItemModel * sourceModel) virtual
Sets the given sourceModel to be processed by the proxy model.
Reimplemented in QCompletionModel, QSortFilterProxyModel, and QIdentityProxyModel.
Definition at line 124 of file qabstractproxymodel.cpp.
Referenced by QCompletionModel::modelDestroyed(), QAbstractProxyModel(), QFileDialog::setProxyModel(), QIdentityProxyModel::setSourceModel(), QSortFilterProxyModel::setSourceModel(), and QCompletionModel::setSourceModel().
 {
     Q_D(QAbstractProxyModel);
     if (d->model)
         disconnect(d->model, SIGNAL(destroyed()), this, SLOT(_q_sourceModelDestroyed()));
     if (sourceModel) {
         d->model = sourceModel;
         connect(d->model, SIGNAL(destroyed()), this, SLOT(_q_sourceModelDestroyed()));
     } else {
         d->model = QAbstractItemModelPrivate::staticEmptyModel();
     }
     d->roleNames = d->model->roleNames();
 }
sort()
void QAbstractProxyModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 340 of file qabstractproxymodel.cpp.
 {
     Q_D(QAbstractProxyModel);
     d->model->sort(column, order);
 }
sourceModel()
QAbstractItemModel * QAbstractProxyModel::sourceModel () const
Returns the model that contains the data that is available through the proxy model.
Definition at line 142 of file qabstractproxymodel.cpp.
Referenced by QCompleterPrivate::_q_complete(), QUnsortedModelEngine::buildIndices(), QCompletionEngine::filter(), QSortedModelEngine::filter(), QUnsortedModelEngine::filter(), QCompletionEngine::filterHistory(), QUnsortedModelEngine::filterOnDemand(), QSortedModelEngine::indexHint(), setSourceModel(), QIdentityProxyModel::setSourceModel(), QCompletionModel::setSourceModel(), and QSortedModelEngine::sortOrder().
 {
     Q_D(const QAbstractProxyModel);
     if (d->model == QAbstractItemModelPrivate::staticEmptyModel())
         return 0;
     return d->model;
 }
span()
QSize QAbstractProxyModel::span (const QModelIndex & index) const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 350 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     return d->model->span(mapToSource(index));
 }
submit()
bool QAbstractProxyModel::submit () virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 153 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(QAbstractProxyModel);
     return d->model->submit();
 }
supportedDropActions()
Qt::DropActions QAbstractProxyModel::supportedDropActions () const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractItemModel.
Reimplemented in QSortFilterProxyModel.
Definition at line 393 of file qabstractproxymodel.cpp.
Referenced by QAbstractItemModel::sibling().
 {
     Q_D(const QAbstractProxyModel);
     return d->model->supportedDropActions();
 }
The documentation for this class was generated from the following files:
/src/gui/itemviews/qabstractproxymodel.h
/src/gui/itemviews/qabstractproxymodel.cpp