Qt 4.8: QProcessEnvironmentPrivate Class Reference
QProcessEnvironmentPrivate Class Reference
#include <qprocess_p.h>
Classes
struct MutexLocker
struct OrderedMutexLocker
Public Types
typedef QHash< Key, Value > Hash
typedef QProcEnvKey Key
typedef QHash< QString, Key > NameHash
typedef QProcEnvValue Value
Public Functions
void insert (const QProcessEnvironmentPrivate &other)
QStringList keys () const
QString nameToString (const Key &name) const
Key prepareName (const QString &name) const
Value prepareValue (const QString &value) const
QStringList toList () const
QString valueToString (const Value &value) const
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Static Public Functions
static QProcessEnvironment fromList (const QStringList &list)
Public Variables
Hash hash
QMutex mutex
NameHash nameMap
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Definition at line 146 of file qprocess_p.h.
Typedefs
Hash
typedef QHash<Key, Value> QProcessEnvironmentPrivate::Hash
Definition at line 212 of file qprocess_p.h.
Key
typedef QProcEnvKey QProcessEnvironmentPrivate::Key
Definition at line 149 of file qprocess_p.h.
NameHash
typedef QHash<QString, Key> QProcessEnvironmentPrivate::NameHash
Definition at line 216 of file qprocess_p.h.
Value
typedef QProcEnvValue QProcessEnvironmentPrivate::Value
Definition at line 150 of file qprocess_p.h.
Functions
fromList()
QProcessEnvironment QProcessEnvironmentPrivate::fromList (const QStringList & list) static
Definition at line 167 of file qprocess.cpp.
Referenced by QProcess::setEnvironment().
 {
     QProcessEnvironment env;
     QStringList::ConstIterator it = list.constBegin(),
                               end = list.constEnd();
     for ( ; it != end; ++it) {
         int pos = it->indexOf(QLatin1Char('='));
         if (pos < 1)
             continue;
         QString value = it->mid(pos + 1);
         QString name = *it;
         name.truncate(pos);
         env.insert(name, value);
     }
     return env;
 }
insert()
void QProcessEnvironmentPrivate::insert (const QProcessEnvironmentPrivate & other)
Definition at line 196 of file qprocess.cpp.
Referenced by QProcessEnvironment::insert().
 {
     Hash::ConstIterator it = other.hash.constBegin(),
                        end = other.hash.constEnd();
     for ( ; it != end; ++it)
         hash.insert(it.key(), it.value());
 #ifdef Q_OS_UNIX
     QHash<QString, Key>::ConstIterator nit = other.nameMap.constBegin(),
                                       nend = other.nameMap.constEnd();
     for ( ; nit != nend; ++nit)
         nameMap.insert(nit.key(), nit.value());
 #endif
 }
keys()
QStringList QProcessEnvironmentPrivate::keys () const
Definition at line 185 of file qprocess.cpp.
Referenced by QProcessEnvironment::keys().
 {
     QStringList result;
     result.reserve(hash.size());
     Hash::ConstIterator it = hash.constBegin(),
                        end = hash.constEnd();
     for ( ; it != end; ++it)
         result << nameToString(it.key());
     return result;
 }
nameToString()
QString QProcessEnvironmentPrivate::nameToString (const Key & name) const inline
Definition at line 153 of file qprocess_p.h.
Referenced by keys(), and toList().
 { return name; }
prepareName()
Key QProcessEnvironmentPrivate::prepareName (const QString & name) const inline
Definition at line 152 of file qprocess_p.h.
Referenced by QProcessEnvironment::contains(), QProcessEnvironment::insert(), QProcessEnvironment::remove(), and QProcessEnvironment::value().
 { return Key(name); }
prepareValue()
Value QProcessEnvironmentPrivate::prepareValue (const QString & value) const inline
Definition at line 154 of file qprocess_p.h.
Referenced by QProcessEnvironment::insert().
 { return value; }
toList()
QStringList QProcessEnvironmentPrivate::toList () const
Definition at line 150 of file qprocess.cpp.
Referenced by QProcessEnvironment::toStringList().
 {
     QStringList result;
     result.reserve(hash.size());
     Hash::ConstIterator it = hash.constBegin(),
                        end = hash.constEnd();
     for ( ; it != end; ++it) {
         QString data = nameToString(it.key());
         QString value = valueToString(it.value());
         data.reserve(data.length() + value.length() + 1);
         data.append(QLatin1Char('='));
         data.append(value);
         result << data;
     }
     return result;
 }
valueToString()
QString QProcessEnvironmentPrivate::valueToString (const Value & value) const inline
Definition at line 155 of file qprocess_p.h.
Referenced by toList(), and QProcessEnvironment::value().
 { return value; }
Properties
hash
Hash QProcessEnvironmentPrivate::hash
Definition at line 213 of file qprocess_p.h.
Referenced by QProcessEnvironment::clear(), QProcessEnvironment::contains(), QProcessEnvironment::insert(), insert(), QProcessEnvironment::isEmpty(), keys(), QProcessEnvironment::operator==(), QProcessEnvironmentPrivate::OrderedMutexLocker::OrderedMutexLocker(), qt_create_commandline(), QProcessEnvironment::remove(), QProcessEnvironment::systemEnvironment(), toList(), and QProcessEnvironment::value().
mutex
QMutex QProcessEnvironmentPrivate::mutex mutable
Definition at line 219 of file qprocess_p.h.
Referenced by QProcessEnvironmentPrivate::OrderedMutexLocker::OrderedMutexLocker().
nameMap
NameHash QProcessEnvironmentPrivate::nameMap mutable
Definition at line 217 of file qprocess_p.h.
Referenced by insert(), and QProcessEnvironmentPrivate::OrderedMutexLocker::OrderedMutexLocker().
The documentation for this class was generated from the following files:
/src/corelib/io/qprocess_p.h
/src/corelib/io/qprocess.cpp