Qt 4.8: QDeclarativeDebugService Class Reference
QDeclarativeDebugService Class Reference
#include <qdeclarativedebugservice_p.h>
Public Types
enum Status { NotConnected, Unavailable, Enabled }
Public Functions
QString name () const
QDeclarativeDebugService (const QString &, QObject *parent=0)
void sendMessage (const QByteArray &)
Status status () const
bool waitForMessage ()
~QDeclarativeDebugService ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool hasDebuggingClient ()
static int idForObject (QObject *)
Returns a unique id for object.
static bool isDebuggingEnabled ()
static QObject * objectForId (int)
Returns the object for unique id.
static QString objectToString (QObject *obj)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual void messageReceived (const QByteArray &)
virtual void statusChanged (Status)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QDeclarativeDebugServer
class QDeclarativeDebugServerPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 56 of file qdeclarativedebugservice_p.h.
Enumerations
Status
enum QDeclarativeDebugService::Status
Enumerator
NotConnected
Unavailable
Enabled
Definition at line 68 of file qdeclarativedebugservice_p.h.
 { NotConnected, Unavailable, Enabled };
Constructors and Destructors
QDeclarativeDebugService()
QDeclarativeDebugService::QDeclarativeDebugService (const QString & name, QObject * parent = 0) explicit
Definition at line 56 of file qdeclarativedebugservice.cpp.
 : QObject(*(new QDeclarativeDebugServicePrivate), parent)
 {
     Q_D(QDeclarativeDebugService);
     d->name = name;
     d->server = QDeclarativeDebugServer::instance();
     d->status = QDeclarativeDebugService::NotConnected;
     if (!d->server)
         return;
     if (d->server->serviceNames().contains(name)) {
         qWarning() << "QDeclarativeDebugService: Conflicting plugin name" << name;
         d->server = 0;
     } else {
         d->server->addService(this);
     }
 }
~QDeclarativeDebugService()
QDeclarativeDebugService::~QDeclarativeDebugService ()
Definition at line 75 of file qdeclarativedebugservice.cpp.
 {
     Q_D(const QDeclarativeDebugService);
     if (d->server) {
         d->server->removeService(this);
     }
 }
Functions
hasDebuggingClient()
bool QDeclarativeDebugService::hasDebuggingClient () static
Definition at line 181 of file qdeclarativedebugservice.cpp.
 {
     return QDeclarativeDebugServer::instance() != 0
             && QDeclarativeDebugServer::instance()->hasDebuggingClient();
 }
idForObject()
int QDeclarativeDebugService::idForObject (QObject * object) static
Returns a unique id for object.
Calling this method multiple times for the same object will return the same id.
Definition at line 121 of file qdeclarativedebugservice.cpp.
Referenced by QDeclarativeEngineDebugService::buildObjectList(), QmlJSDebugger::AbstractViewInspector::idStringForObject(), QDeclarativeEngineDebugService::messageReceived(), QDeclarativeEngineDebugService::objectCreated(), QDeclarativeEngineDebugService::objectData(), and QmlJSDebugger::AbstractViewInspector::sendCurrentObjects().
 {
     if (!object)
         return -1;
     ObjectReferenceHash *hash = objectReferenceHash();
     QHash<QObject *, ObjectReference>::Iterator iter =
         hash->objects.find(object);
     if (iter == hash->objects.end()) {
         int id = hash->nextId++;
         hash->ids.insert(id, object);
         iter = hash->objects.insert(object, ObjectReference());
         iter->object = object;
         iter->id = id;
     } else if (iter->object != object) {
         int id = hash->nextId++;
         hash->ids.remove(iter->id);
         hash->ids.insert(id, object);
         iter->object = object;
         iter->id = id;
     }
     return iter->id;
 }
isDebuggingEnabled()
bool QDeclarativeDebugService::isDebuggingEnabled () static
Definition at line 176 of file qdeclarativedebugservice.cpp.
Referenced by QDeclarativeDebugTrace::addEvent(), QDeclarativeDebugTrace::endRange(), QDeclarativeEnginePrivate::init(), qmlExecuteDeferred(), QDeclarativeBoundSignal::qt_metacall(), QDeclarativeDebugTrace::rangeData(), QDeclarativeDebugTrace::rangeLocation(), and QDeclarativeDebugTrace::startRange().
 {
     return QDeclarativeDebugServer::instance() != 0;
 }
messageReceived()
void QDeclarativeDebugService::messageReceived (const QByteArray &) protected virtual
Reimplemented in QDeclarativeDebugTrace, QDeclarativeEngineDebugService, QJSDebugService, and QDeclarativeInspectorService.
Definition at line 226 of file qdeclarativedebugservice.cpp.
Referenced by QJSDebugService::messageReceived(), and QDeclarativeInspectorService::views().
 {
 }
name()
QString QDeclarativeDebugService::name () const
Definition at line 83 of file qdeclarativedebugservice.cpp.
Referenced by QDeclarativeDebugServer::addService(), QDeclarativeDebugService(), QDeclarativeDebugServer::removeService(), QDeclarativeDebugServer::sendMessage(), QDeclarativeEngineDebugService::valueContents(), and QDeclarativeDebugServer::waitForMessage().
 {
     Q_D(const QDeclarativeDebugService);
     return d->name;
 }
objectForId()
QObject * QDeclarativeDebugService::objectForId (int id) static
Returns the object for unique id.
If the object has not previously been assigned an id, through idForObject(), then 0 is returned. If the object has been destroyed, 0 is returned.
Definition at line 154 of file qdeclarativedebugservice.cpp.
Referenced by QDeclarativeWatcher::addWatch(), QmlJSDebugger::AbstractViewInspector::handleMessage(), QDeclarativeEngineDebugService::messageReceived(), QDeclarativeEngineDebugService::resetBinding(), QDeclarativeEngineDebugService::setBinding(), and QDeclarativeEngineDebugService::setMethodBody().
 {
     ObjectReferenceHash *hash = objectReferenceHash();
     QHash<int, QObject *>::Iterator iter = hash->ids.find(id);
     if (iter == hash->ids.end())
         return 0;
     QHash<QObject *, ObjectReference>::Iterator objIter =
         hash->objects.find(*iter);
     Q_ASSERT(objIter != hash->objects.end());
     if (objIter->object == 0) {
         hash->ids.erase(iter);
         hash->objects.erase(objIter);
         return 0;
     } else {
         return *iter;
     }
 }
objectToString()
QString QDeclarativeDebugService::objectToString (QObject * obj) static
Definition at line 187 of file qdeclarativedebugservice.cpp.
 {
     if(!obj)
         return QLatin1String("NULL");
     QString objectName = obj->objectName();
     if(objectName.isEmpty())
         objectName = QLatin1String("<unnamed>");
     QString rv = QString::fromUtf8(obj->metaObject()->className()) +
                  QLatin1String(": ") + objectName;
     return rv;
 }
sendMessage()
void QDeclarativeDebugService::sendMessage (const QByteArray & message)
Definition at line 202 of file qdeclarativedebugservice.cpp.
Referenced by QJSDebugService::executionStopped(), QDeclarativeEngineDebugService::messageReceived(), QJSDebugService::messageReceived(), QDeclarativeEngineDebugService::objectCreated(), QJSDebugService::processMessage(), QDeclarativeDebugTrace::processMessage(), QDeclarativeEngineDebugService::propertyChanged(), QDeclarativeInspectorService::sendMessage(), QJSDebugService::sendMessages(), QDeclarativeDebugTrace::sendMessages(), and QDeclarativeInspectorService::views().
 {
     Q_D(QDeclarativeDebugService);
     if (status() != Enabled)
         return;
     d->server->sendMessage(this, message);
 }
status()
QDeclarativeDebugService::Status QDeclarativeDebugService::status () const
Definition at line 89 of file qdeclarativedebugservice.cpp.
Referenced by QJSDebugService::addEngine(), QDeclarativeDebugTrace::addEventImpl(), QDeclarativeDebugServer::addService(), QDeclarativeDebugTrace::endRangeImpl(), QDeclarativeDebugTrace::QDeclarativeDebugTrace(), QDeclarativeDebugTrace::rangeDataImpl(), QDeclarativeDebugTrace::rangeLocationImpl(), QDeclarativeDebugServer::removeService(), QDeclarativeInspectorService::sendMessage(), sendMessage(), QDeclarativeDebugTrace::startRangeImpl(), QDeclarativeInspectorService::updateStatus(), and waitForMessage().
 {
     Q_D(const QDeclarativeDebugService);
     return d->status;
 }
statusChanged()
void QDeclarativeDebugService::statusChanged (Status) protected virtual
Reimplemented in QJSDebugService, and QDeclarativeInspectorService.
Definition at line 222 of file qdeclarativedebugservice.cpp.
Referenced by QDeclarativeDebugServer::addService(), QDeclarativeDebugServer::removeService(), and QDeclarativeInspectorService::views().
 {
 }
waitForMessage()
bool QDeclarativeDebugService::waitForMessage ()
Definition at line 212 of file qdeclarativedebugservice.cpp.
Referenced by QJSDebugService::addEngine(), and QDeclarativeDebugTrace::QDeclarativeDebugTrace().
 {
     Q_D(QDeclarativeDebugService);
     if (status() != Enabled)
         return false;
     return d->server->waitForMessage(this);
 }
Friends and Related Functions
QDeclarativeDebugServer
friend class QDeclarativeDebugServer friend
Definition at line 87 of file qdeclarativedebugservice_p.h.
QDeclarativeDebugServerPrivate
friend class QDeclarativeDebugServerPrivate friend
Definition at line 88 of file qdeclarativedebugservice_p.h.
The documentation for this class was generated from the following files:
/src/declarative/debugger/qdeclarativedebugservice_p.h
/src/declarative/debugger/qdeclarativedebugservice.cpp