Qt 4.8: QItemSelectionModel Class Reference
QItemSelectionModel Class Reference
The QItemSelectionModel class keeps track of a view's selected items.
#include <qitemselectionmodel.h>
Public Types
enum SelectionFlag {
NoUpdate = 0x0000, Clear = 0x0001, Select = 0x0002, Deselect = 0x0004,
Toggle = 0x0008, Current = 0x0010, Rows = 0x0020, Columns = 0x0040,
SelectCurrent = Select | Current, ToggleCurrent = Toggle | Current, ClearAndSelect = Clear | Select
}
This enum describes the way the selection model will be updated.
Public Slots
virtual void clear ()
Clears the selection model.
void clearSelection ()
Clears the selection in the selection model.
virtual void reset ()
Clears the selection model.
virtual void select (const QModelIndex &index, QItemSelectionModel::SelectionFlags command)
Selects the model item index using the specified command, and emits selectionChanged().
virtual void select (const QItemSelection &selection, QItemSelectionModel::SelectionFlags command)
Selects the item selection using the specified command, and emits selectionChanged().
void setCurrentIndex (const QModelIndex &index, QItemSelectionModel::SelectionFlags command)
Sets the model item index to be the current item, and emits currentChanged().
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
This signal is emitted whenever the current item changes.
void currentColumnChanged (const QModelIndex &current, const QModelIndex &previous)
This signal is emitted if the current item changes and its column is different to the column of the previous current item.
void currentRowChanged (const QModelIndex &current, const QModelIndex &previous)
This signal is emitted if the current item changes and its row is different to the row of the previous current item.
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
This signal is emitted whenever the selection changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool columnIntersectsSelection (int column, const QModelIndex &parent) const
Returns true if there are any items selected in the column with the given parent.
QModelIndex currentIndex () const
Returns the model item index for the current item, or an invalid index if there is no current item.
bool hasSelection () const
Returns true if the selection model contains any selection ranges; otherwise returns false.
bool isColumnSelected (int column, const QModelIndex &parent) const
Returns true if all items are selected in the column with the given parent.
bool isRowSelected (int row, const QModelIndex &parent) const
Returns true if all items are selected in the row with the given parent.
bool isSelected (const QModelIndex &index) const
Returns true if the given model item index is selected.
const QAbstractItemModel * model () const
Returns the item model operated on by the selection model.
QItemSelectionModel (QAbstractItemModel *model)
Constructs a selection model that operates on the specified item model.
QItemSelectionModel (QAbstractItemModel *model, QObject *parent)
Constructs a selection model that operates on the specified item model with parent.
bool rowIntersectsSelection (int row, const QModelIndex &parent) const
Returns true if there are any items selected in the row with the given parent.
QModelIndexList selectedColumns (int row=0) const
Returns the indexes in the given row for columns where all rows are selected.
QModelIndexList selectedIndexes () const
Returns a list of all selected model item indexes.
QModelIndexList selectedRows (int column=0) const
Returns the indexes in the given column for the rows where all columns are selected.
const QItemSelection selection () const
Returns the selection ranges stored in the selection model.
virtual ~QItemSelectionModel ()
Destroys the selection model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void emitSelectionChanged (const QItemSelection &newSelection, const QItemSelection &oldSelection)
Compares the two selections newSelection and oldSelection and emits selectionChanged() with the deselected and selected items.
QItemSelectionModel (QItemSelectionModelPrivate &dd, QAbstractItemModel *model)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QItemSelectionModel class keeps track of a view's selected items.
A QItemSelectionModel keeps track of the selected items in a view, or in several views onto the same model. It also keeps track of the currently selected item in a view.
The QItemSelectionModel class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
The selected items are stored using ranges. Whenever you want to modify the selected items use select() and provide either a QItemSelection, or a QModelIndex and a QItemSelectionModel::SelectionFlag.
The QItemSelectionModel takes a two layer approach to selection management, dealing with both selected items that have been committed and items that are part of the current selection. The current selected items are part of the current interactive selection (for example with rubber-band selection or keyboard-shift selections).
To update the currently selected items, use the bitwise OR of QItemSelectionModel::Current and any of the other SelectionFlags. If you omit the QItemSelectionModel::Current command, a new current selection will be created, and the previous one added to the whole selection. All functions operate on both layers; for example, selectedItems() will return items from both layers.
See also
{Model/View Programming}, QAbstractItemModel, {Chart Example}
Definition at line 151 of file qitemselectionmodel.h.
Enumerations
SelectionFlag
enum QItemSelectionModel::SelectionFlag
This enum describes the way the selection model will be updated.
NoUpdate No selection will be made.
Clear The complete selection will be cleared.
Select All specified indexes will be selected.
Deselect All specified indexes will be deselected.
Toggle All specified indexes will be selected or deselected depending on their current state.
Current The current selection will be updated.
Rows All indexes will be expanded to span rows.
Columns All indexes will be expanded to span columns.
SelectCurrent A combination of Select and Current, provided for convenience.
ToggleCurrent A combination of Toggle and Current, provided for convenience.
ClearAndSelect A combination of Clear and Select, provided for convenience.
Enumerator
NoUpdate
Clear
Select
Deselect
Toggle
Current
Rows
Columns
SelectCurrent
ToggleCurrent
ClearAndSelect
Definition at line 159 of file qitemselectionmodel.h.
{
         NoUpdate       = 0x0000,
         Clear          = 0x0001,
         Select         = 0x0002,
         Deselect       = 0x0004,
         Toggle         = 0x0008,
         Current        = 0x0010,
         Rows           = 0x0020,
         Columns        = 0x0040,
         SelectCurrent  = Select | Current,
         ToggleCurrent  = Toggle | Current,
         ClearAndSelect = Clear | Select
     };
Constructors and Destructors
QItemSelectionModel() [1/3]
QItemSelectionModel::QItemSelectionModel (QAbstractItemModel * model) explicit
Constructs a selection model that operates on the specified item model.
Definition at line 1035 of file qitemselectionmodel.cpp.
     : QObject(*new QItemSelectionModelPrivate, model)
 {
     d_func()->initModel(model);
 }
QItemSelectionModel() [2/3]
QItemSelectionModel::QItemSelectionModel (QAbstractItemModel * model, QObject * parent) explicit
Constructs a selection model that operates on the specified item model with parent.
Definition at line 1044 of file qitemselectionmodel.cpp.
     : QObject(*new QItemSelectionModelPrivate, parent)
 {
     d_func()->initModel(model);
 }
~QItemSelectionModel()
QItemSelectionModel::~QItemSelectionModel () virtual
Destroys the selection model.
Definition at line 1062 of file qitemselectionmodel.cpp.
 {
 }
QItemSelectionModel() [3/3]
QItemSelectionModel::QItemSelectionModel (QItemSelectionModelPrivate & dd, QAbstractItemModel * model) protected
Warning
This function is not part of the public interface.
Definition at line 1053 of file qitemselectionmodel.cpp.
     : QObject(dd, model)
 {
     dd.initModel(model);
 }
Functions
clear
void QItemSelectionModel::clear () virtual slot
Clears the selection model.
Emits selectionChanged() and currentChanged().
Definition at line 1221 of file qitemselectionmodel.cpp.
Referenced by QListWidget::clear(), QTableWidget::clear(), QTreeWidget::clear(), QTableWidget::clearContents(), reset(), QSidebar::selectUrl(), QCompleterPrivate::setCurrentIndex(), QTreeView::setSelection(), and QCalendarWidgetPrivate::update().
 {
     Q_D(QItemSelectionModel);
     clearSelection();
     QModelIndex previous = d->currentIndex;
     d->currentIndex = QModelIndex();
     if (previous.isValid()) {
         emit currentChanged(d->currentIndex, previous);
         emit currentRowChanged(d->currentIndex, previous);
         emit currentColumnChanged(d->currentIndex, previous);
     }
 }
clearSelection
void QItemSelectionModel::clearSelection () slot
Clears the selection in the selection model.
Since
4.2 Emits selectionChanged().
Definition at line 1251 of file qitemselectionmodel.cpp.
Referenced by clear().
 {
     Q_D(QItemSelectionModel);
     if (d->ranges.count() == 0 && d->currentSelection.count() == 0)
         return;
     select(QItemSelection(), Clear);
 }
columnIntersectsSelection()
bool QItemSelectionModel::columnIntersectsSelection (int column, const QModelIndex & parent) const
Returns true if there are any items selected in the column with the given parent.
Definition at line 1491 of file qitemselectionmodel.cpp.
Referenced by QHeaderViewPrivate::columnIntersectsSelection().
 {
     Q_D(const QItemSelectionModel);
     if (parent.isValid() && d->model != parent.model())
         return false;
     QItemSelection sel = d->ranges;
     sel.merge(d->currentSelection, d->currentCommand);
     for (int i = 0; i < sel.count(); ++i) {
         int left = sel.at(i).left();
         int right = sel.at(i).right();
         int top =  sel.at(i).top();
         int bottom =  sel.at(i).bottom();
         if (left <= column && right >= column) {
             for (int j = top; j <= bottom; j++) {
                 const Qt::ItemFlags flags = d->model->index(j, column, parent).flags();
                 if ((flags & Qt::ItemIsSelectable) && (flags & Qt::ItemIsEnabled))
                     return true;
             }
         }
     }
     return false;
 }
currentChanged
void QItemSelectionModel::currentChanged (const QModelIndex & current, const QModelIndex & previous) signal
This signal is emitted whenever the current item changes.
The previous model item index is replaced by the current index as the selection's current item.
Note that this signal will not be emitted when the item model is reset.
See also
currentIndex() setCurrentIndex() selectionChanged()
Referenced by clear(), and setCurrentIndex().
currentColumnChanged
void QItemSelectionModel::currentColumnChanged (const QModelIndex & current, const QModelIndex & previous) signal
This signal is emitted if the current item changes and its column is different to the column of the previous current item.
Note that this signal will not be emitted when the item model is reset.
See also
currentChanged() currentRowChanged() currentIndex() setCurrentIndex()
Referenced by clear(), and setCurrentIndex().
currentIndex()
QModelIndex QItemSelectionModel::currentIndex () const
Returns the model item index for the current item, or an invalid index if there is no current item.
Definition at line 1296 of file qitemselectionmodel.cpp.
Referenced by QAbstractItemViewPrivate::checkPersistentEditorFocus(), QAbstractItemView::closePersistentEditor(), QCompleterPrivate::setCurrentIndex(), QAccessibleItemRow::state(), and QAccessibleTable2Cell::state().
 {
     return static_cast<QModelIndex>(d_func()->currentIndex);
 }
currentRowChanged
void QItemSelectionModel::currentRowChanged (const QModelIndex & current, const QModelIndex & previous) signal
This signal is emitted if the current item changes and its row is different to the row of the previous current item.
Note that this signal will not be emitted when the item model is reset.
See also
currentChanged() currentColumnChanged() currentIndex() setCurrentIndex()
Referenced by clear(), and setCurrentIndex().
emitSelectionChanged()
void QItemSelectionModel::emitSelectionChanged (const QItemSelection & newSelection, const QItemSelection & oldSelection) protected
Compares the two selections newSelection and oldSelection and emits selectionChanged() with the deselected and selected items.
Definition at line 1651 of file qitemselectionmodel.cpp.
Referenced by select().
 {
     // if both selections are empty or equal we return
     if ((oldSelection.isEmpty() && newSelection.isEmpty()) ||
         oldSelection == newSelection)
         return;
     // if either selection is empty we do not need to compare
     if (oldSelection.isEmpty() || newSelection.isEmpty()) {
         emit selectionChanged(newSelection, oldSelection);
         return;
     }
     QItemSelection deselected = oldSelection;
     QItemSelection selected = newSelection;
     // remove equal ranges
     bool advance;
     for (int o = 0; o < deselected.count(); ++o) {
         advance = true;
         for (int s = 0; s < selected.count() && o < deselected.count();) {
             if (deselected.at(o) == selected.at(s)) {
                 deselected.removeAt(o);
                 selected.removeAt(s);
                 advance = false;
             } else {
                 ++s;
             }
         }
         if (advance)
             ++o;
     }
     // find intersections
     QItemSelection intersections;
     for (int o = 0; o < deselected.count(); ++o) {
         for (int s = 0; s < selected.count(); ++s) {
             if (deselected.at(o).intersects(selected.at(s)))
                 intersections.append(deselected.at(o).intersected(selected.at(s)));
         }
     }
     // compare remaining ranges with intersections and split them to find deselected and selected
     for (int i = 0; i < intersections.count(); ++i) {
         // split deselected
         for (int o = 0; o < deselected.count();) {
             if (deselected.at(o).intersects(intersections.at(i))) {
                 QItemSelection::split(deselected.at(o), intersections.at(i), &deselected);
                 deselected.removeAt(o);
             } else {
                 ++o;
             }
         }
         // split selected
         for (int s = 0; s < selected.count();) {
             if (selected.at(s).intersects(intersections.at(i))) {
                 QItemSelection::split(selected.at(s), intersections.at(i), &selected);
                 selected.removeAt(s);
             } else {
                 ++s;
             }
         }
     }
     if (!selected.isEmpty() || !deselected.isEmpty())
         emit selectionChanged(selected, deselected);
 }
hasSelection()
bool QItemSelectionModel::hasSelection () const
Returns true if the selection model contains any selection ranges; otherwise returns false.
Since
4.2
Definition at line 1525 of file qitemselectionmodel.cpp.
Referenced by QComboBox::hidePopup(), QInputDialogPrivate::listViewText(), QHeaderViewPrivate::prepareSectionSelected(), and QInputDialogPrivate::setInputWidget().
 {
     Q_D(const QItemSelectionModel);
     if (d->currentCommand & (Toggle | Deselect)) {
         QItemSelection sel = d->ranges;
         sel.merge(d->currentSelection, d->currentCommand);
         return !sel.isEmpty();
     } else {
         return !(d->ranges.isEmpty() && d->currentSelection.isEmpty());
     }
 }
isColumnSelected()
bool QItemSelectionModel::isColumnSelected (int column, const QModelIndex & parent) const
Returns true if all items are selected in the column with the given parent.
Note that this function is usually faster than calling isSelected() on all items in the same column and that unselectable items are ignored.
Definition at line 1406 of file qitemselectionmodel.cpp.
Referenced by QAccessibleTable2::isColumnSelected(), QHeaderViewPrivate::isColumnSelected(), QAccessibleItemView::isColumnSelected(), and selectedColumns().
 {
     Q_D(const QItemSelectionModel);
     if (parent.isValid() && d->model != parent.model())
         return false;
     // return false if column exist in currentSelection (Deselect)
     if (d->currentCommand & Deselect && d->currentSelection.count()) {
         for (int i = 0; i < d->currentSelection.count(); ++i) {
             if (d->currentSelection.at(i).parent() == parent &&
                 column >= d->currentSelection.at(i).left() &&
                 column <= d->currentSelection.at(i).right())
                 return false;
         }
     }
     // return false if ranges in both currentSelection and the selection model
     // intersect and have the same column contained
     if (d->currentCommand & Toggle && d->currentSelection.count()) {
         for (int i = 0; i < d->currentSelection.count(); ++i) {
             if (d->currentSelection.at(i).left() <= column &&
                 d->currentSelection.at(i).right() >= column) {
                 for (int j = 0; j < d->ranges.count(); ++j) {
                     if (d->ranges.at(j).left() <= column && d->ranges.at(j).right() >= column
                         && d->currentSelection.at(i).intersected(d->ranges.at(j)).isValid()) {
                         return false;
                     }
                 }
             }
         }
     }
     // add ranges and currentSelection and check through them all
     QList<QItemSelectionRange>::const_iterator it;
     QList<QItemSelectionRange> joined = d->ranges;
     if (d->currentSelection.count())
         joined += d->currentSelection;
     int rowCount = d->model->rowCount(parent);
     for (int row = 0; row < rowCount; ++row) {
          for (it = joined.constBegin(); it != joined.constEnd(); ++it) {
              if ((*it).contains(row, column, parent)) {
                  Qt::ItemFlags flags = d->model->index(row, column, parent).flags();
                  if ((flags & Qt::ItemIsSelectable) && (flags & Qt::ItemIsEnabled)) {
                      row = qMax(row, (*it).bottom());
                      break;
                  }
              }
          }
          if (it == joined.constEnd())
              return false;
     }
     return rowCount > 0; // no rows means no selected items
 }
isRowSelected()
bool QItemSelectionModel::isRowSelected (int row, const QModelIndex & parent) const
Returns true if all items are selected in the row with the given parent.
Note that this function is usually faster than calling isSelected() on all items in the same row and that unselectable items are ignored.
Definition at line 1346 of file qitemselectionmodel.cpp.
Referenced by QAccessibleTable2::isRowSelected(), QHeaderViewPrivate::isRowSelected(), QAccessibleTree::isRowSelected(), QAccessibleItemView::isRowSelected(), selectedRows(), and QAccessibleItemRow::state().
 {
     Q_D(const QItemSelectionModel);
     if (parent.isValid() && d->model != parent.model())
         return false;
     // return false if row exist in currentSelection (Deselect)
     if (d->currentCommand & Deselect && d->currentSelection.count()) {
         for (int i=0; i<d->currentSelection.count(); ++i) {
             if (d->currentSelection.at(i).parent() == parent &&
                 row >= d->currentSelection.at(i).top() &&
                 row <= d->currentSelection.at(i).bottom())
                 return false;
         }
     }
     // return false if ranges in both currentSelection and ranges
     // intersect and have the same row contained
     if (d->currentCommand & Toggle && d->currentSelection.count()) {
         for (int i=0; i<d->currentSelection.count(); ++i)
             if (d->currentSelection.at(i).top() <= row &&
                 d->currentSelection.at(i).bottom() >= row)
                 for (int j=0; j<d->ranges.count(); ++j)
                     if (d->ranges.at(j).top() <= row && d->ranges.at(j).bottom() >= row
                         && d->currentSelection.at(i).intersected(d->ranges.at(j)).isValid())
                         return false;
     }
     // add ranges and currentSelection and check through them all
     QList<QItemSelectionRange>::const_iterator it;
     QList<QItemSelectionRange> joined = d->ranges;
     if (d->currentSelection.count())
         joined += d->currentSelection;
     int colCount = d->model->columnCount(parent);
     for (int column = 0; column < colCount; ++column) {
         for (it = joined.constBegin(); it != joined.constEnd(); ++it) {
             if ((*it).contains(row, column, parent)) {
                 bool selectable = false;
                 for (int i = column; !selectable && i <= (*it).right(); ++i) {
                     Qt::ItemFlags flags = d->model->index(row, i, parent).flags();
                     selectable = flags & Qt::ItemIsSelectable;
                 }
                 if (selectable){
                     column = qMax(column, (*it).right());
                     break;
                 }
             }
         }
         if (it == joined.constEnd())
             return false;
     }
     return colCount > 0; // no columns means no selected items
 }
isSelected()
bool QItemSelectionModel::isSelected (const QModelIndex & index) const
Returns true if the given model item index is selected.
Definition at line 1304 of file qitemselectionmodel.cpp.
Referenced by QColumnViewPrivate::_q_clicked(), QAbstractItemViewPrivate::extendedSelectionCommand(), QListWidget::isItemSelected(), QTableWidget::isItemSelected(), QAccessibleItemView::isSelected(), QAccessibleTable2Cell::isSelected(), QListView::paintEvent(), QAbstractItemViewPrivate::shouldEdit(), QAccessibleItemRow::state(), and QAccessibleTable2Cell::state().
 {
     Q_D(const QItemSelectionModel);
     if (d->model != index.model() || !index.isValid())
         return false;
     bool selected = false;
     //  search model ranges
     QList<QItemSelectionRange>::const_iterator it = d->ranges.begin();
     for (; it != d->ranges.end(); ++it) {
         if ((*it).isValid() && (*it).contains(index)) {
             selected = true;
             break;
         }
     }
     // check  currentSelection
     if (d->currentSelection.count()) {
         if ((d->currentCommand & Deselect) && selected)
             selected = !d->currentSelection.contains(index);
         else if (d->currentCommand & Toggle)
             selected ^= d->currentSelection.contains(index);
         else if ((d->currentCommand & Select) && !selected)
             selected = d->currentSelection.contains(index);
     }
     if (selected) {
         Qt::ItemFlags flags = d->model->flags(index);
         return (flags & Qt::ItemIsSelectable);
     }
     return false;
 }
model()
const QAbstractItemModel * QItemSelectionModel::model () const
Returns the item model operated on by the selection model.
Definition at line 1642 of file qitemselectionmodel.cpp.
Referenced by selectedColumns(), selectedRows(), and QAbstractItemView::setSelectionModel().
 {
     return d_func()->model;
 }
reset
void QItemSelectionModel::reset () virtual slot
Clears the selection model.
Does not emit any signals.
Definition at line 1237 of file qitemselectionmodel.cpp.
 {
     bool block = blockSignals(true);
     clear();
     blockSignals(block);
 }
rowIntersectsSelection()
bool QItemSelectionModel::rowIntersectsSelection (int row, const QModelIndex & parent) const
Returns true if there are any items selected in the row with the given parent.
Definition at line 1462 of file qitemselectionmodel.cpp.
Referenced by QHeaderViewPrivate::rowIntersectsSelection().
 {
     Q_D(const QItemSelectionModel);
     if (parent.isValid() && d->model != parent.model())
          return false;
     QItemSelection sel = d->ranges;
     sel.merge(d->currentSelection, d->currentCommand);
     for (int i = 0; i < sel.count(); ++i) {
         int top = sel.at(i).top();
         int bottom = sel.at(i).bottom();
         int left = sel.at(i).left();
         int right = sel.at(i).right();
         if (top <= row && bottom >= row) {
             for (int j = left; j <= right; j++) {
                 const Qt::ItemFlags flags = d->model->index(row, j, parent).flags();
                 if ((flags & Qt::ItemIsSelectable) && (flags & Qt::ItemIsEnabled))
                     return true;
             }
         }
     }
     return false;
 }
select [1/2]
void QItemSelectionModel::select (const QModelIndex & index, QItemSelectionModel::SelectionFlags command) virtual slot
Selects the model item index using the specified command, and emits selectionChanged().
See also
QItemSelectionModel::SelectionFlags
Definition at line 1072 of file qitemselectionmodel.cpp.
Referenced by QColumnViewPrivate::_q_changeCurrentColumn(), clearSelection(), QAccessibleItemRow::doAction(), QComboBox::hidePopup(), QAccessibleItemRow::navigate(), QColumnView::selectAll(), QAbstractItemViewPrivate::selectAll(), QListViewPrivate::selectAll(), QAccessibleTable2::selectColumn(), QAccessibleItemView::selectColumn(), QTableViewPrivate::selectColumn(), QAccessibleTable2::selectRow(), QAccessibleTree::selectRow(), QAccessibleItemView::selectRow(), QTableViewPrivate::selectRow(), QSidebar::selectUrl(), setCurrentIndex(), QListWidget::setItemSelected(), QTableWidget::setItemSelected(), QTreeWidget::setItemSelected(), QTableWidget::setRangeSelected(), QAccessibleTable2::unselectColumn(), QAccessibleItemView::unselectColumn(), QAccessibleTable2::unselectRow(), and QAccessibleItemView::unselectRow().
 {
     QItemSelection selection(index, index);
     select(selection, command);
 }
select [2/2]
void QItemSelectionModel::select (const QItemSelection & selection, QItemSelectionModel::SelectionFlags command) virtual slot
Selects the item selection using the specified command, and emits selectionChanged().
See also
QItemSelectionModel::SelectionFlag
Definition at line 1168 of file qitemselectionmodel.cpp.
 {
     Q_D(QItemSelectionModel);
     if (command == NoUpdate)
         return;
     // store old selection
     QItemSelection sel = selection;
     // If d->ranges is non-empty when the source model is reset the persistent indexes
     // it contains will be invalid. We can't clear them in a modelReset slot because that might already
     // be too late if another model observer is connected to the same modelReset slot and is invoked first
     // it might call select() on this selection model before any such QItemSelectionModelPrivate::_q_modelReset() slot
     // is invoked, so it would not be cleared yet. We clear it invalid ranges in it here.
     QItemSelection::iterator it = d->ranges.begin();
     while (it != d->ranges.end()) {
       if (!it->isValid())
         it = d->ranges.erase(it);
       else
         ++it;
     }
     QItemSelection old = d->ranges;
     old.merge(d->currentSelection, d->currentCommand);
     // expand selection according to SelectionBehavior
     if (command & Rows || command & Columns)
         sel = d->expandSelection(sel, command);
     // clear ranges and currentSelection
     if (command & Clear) {
         d->ranges.clear();
         d->currentSelection.clear();
     }
     // merge and clear currentSelection if Current was not set (ie. start new currentSelection)
     if (!(command & Current))
         d->finalize();
     // update currentSelection
     if (command & Toggle || command & Select || command & Deselect) {
         d->currentCommand = command;
         d->currentSelection = sel;
     }
     // generate new selection, compare with old and emit selectionChanged()
     QItemSelection newSelection = d->ranges;
     newSelection.merge(d->currentSelection, d->currentCommand);
     emitSelectionChanged(newSelection, old);
 }
selectedColumns()
QModelIndexList QItemSelectionModel::selectedColumns (int row = 0) const
Returns the indexes in the given row for columns where all rows are selected.
Since
4.2
See also
selectedIndexes(), selectedRows()
Definition at line 1594 of file qitemselectionmodel.cpp.
Referenced by QTableViewPrivate::selectColumn(), QAccessibleTable2::selectedColumnCount(), QAccessibleItemView::selectedColumnCount(), and QAccessibleItemView::selectedColumns().
 {
     QModelIndexList indexes;
     //the QSet contains pairs of parent modelIndex
     //and column number
     QSet< QPair<QModelIndex, int> > columnsSeen;
     const QItemSelection ranges = selection();
     for (int i = 0; i < ranges.count(); ++i) {
         const QItemSelectionRange &range = ranges.at(i);
         QModelIndex parent = range.parent();
         for (int column = range.left(); column <= range.right(); column++) {
             QPair<QModelIndex, int> columnDef = qMakePair(parent, column);
             if (!columnsSeen.contains(columnDef)) {
                 columnsSeen << columnDef;
                 if (isColumnSelected(column, parent)) {
                     indexes.append(model()->index(row, column, parent));
                 }
             }
         }
     }
     return indexes;
 }
selectedIndexes()
QModelIndexList QItemSelectionModel::selectedIndexes () const
Returns a list of all selected model item indexes.
The list contains no duplicates, and is not sorted.
Definition at line 1541 of file qitemselectionmodel.cpp.
Referenced by QSidebar::removeEntry(), QColumnView::selectAll(), QAccessibleTable2::selectedCellCount(), QTreeView::selectedIndexes(), QListWidget::selectedItems(), QTableWidget::selectedItems(), and QTreeWidget::selectedItems().
 {
     Q_D(const QItemSelectionModel);
     QItemSelection selected = d->ranges;
     selected.merge(d->currentSelection, d->currentCommand);
     return selected.indexes();
 }
selectedRows()
QModelIndexList QItemSelectionModel::selectedRows (int column = 0) const
Returns the indexes in the given column for the rows where all columns are selected.
Since
4.2
See also
selectedIndexes(), selectedColumns()
Definition at line 1559 of file qitemselectionmodel.cpp.
Referenced by QInputDialogPrivate::listViewText(), QAccessibleTable2::selectedRowCount(), QAccessibleItemView::selectedRowCount(), QAccessibleItemView::selectedRows(), and QTableViewPrivate::selectRow().
 {
     QModelIndexList indexes;
     //the QSet contains pairs of parent modelIndex
     //and row number
     QSet< QPair<QModelIndex, int> > rowsSeen;
     const QItemSelection ranges = selection();
     for (int i = 0; i < ranges.count(); ++i) {
         const QItemSelectionRange &range = ranges.at(i);
         QModelIndex parent = range.parent();
         for (int row = range.top(); row <= range.bottom(); row++) {
             QPair<QModelIndex, int> rowDef = qMakePair(parent, row);
             if (!rowsSeen.contains(rowDef)) {
                 rowsSeen << rowDef;
                 if (isRowSelected(row, parent)) {
                     indexes.append(model()->index(row, column, parent));
                 }
             }
         }
     }
     return indexes;
 }
selection()
const QItemSelection QItemSelectionModel::selection () const
Returns the selection ranges stored in the selection model.
Definition at line 1622 of file qitemselectionmodel.cpp.
Referenced by QAbstractItemViewPrivate::clearOrRemove(), QComboBox::hidePopup(), QAccessibleItemRow::navigate(), select(), selectedColumns(), QTableWidget::selectedRanges(), selectedRows(), and QTreeWidget::setSelectionModel().
 {
     Q_D(const QItemSelectionModel);
     QItemSelection selected = d->ranges;
     selected.merge(d->currentSelection, d->currentCommand);
     int i = 0;
     // make sure we have no invalid ranges
     // ###  should probably be handled more generic somewhere else
     while (i<selected.count()) {
         if (selected.at(i).isValid())
             ++i;
         else
             (selected.removeAt(i));
     }
     return selected;
 }
selectionChanged
void QItemSelectionModel::selectionChanged (const QItemSelection & selected, const QItemSelection & deselected) signal
This signal is emitted whenever the selection changes.
The change in the selection is represented as an item selection of deselected items and an item selection of selected items.
Note the that the current index changes independently from the selection. Also note that this signal will not be emitted when the item model is reset.
See also
select() currentChanged()
Referenced by emitSelectionChanged().
setCurrentIndex
void QItemSelectionModel::setCurrentIndex (const QModelIndex & index, QItemSelectionModel::SelectionFlags command) slot
Sets the model item index to be the current item, and emits currentChanged().
The current item is used for keyboard navigation and focus indication; it is independent of any selected items, although a selected item can also be the current item.
Depending on the specified command, the index can also become part of the current selection.
See also
select()
Definition at line 1271 of file qitemselectionmodel.cpp.
Referenced by QColumnViewPrivate::_q_changeCurrentColumn(), QAbstractItemView::focusInEvent(), QTreeView::keyboardSearch(), QCalendarView::mouseMoveEvent(), QCalendarView::mousePressEvent(), QTableViewPrivate::selectColumn(), QTableViewPrivate::selectRow(), QCompleterPrivate::setCurrentIndex(), QListWidget::setCurrentRow(), QInputDialogPrivate::setListViewText(), QComboBox::showPopup(), QUndoModel::stackChanged(), QCalendarWidgetPrivate::update(), and QCalendarWidgetPrivate::updateCurrentPage().
 {
     Q_D(QItemSelectionModel);
     if (index == d->currentIndex) {
         if (command != NoUpdate)
             select(index, command); // select item
         return;
     }
     QPersistentModelIndex previous = d->currentIndex;
     d->currentIndex = index; // set current before emitting selection changed below
     if (command != NoUpdate)
         select(d->currentIndex, command); // select item
     emit currentChanged(d->currentIndex, previous);
     if (d->currentIndex.row() != previous.row() ||
             d->currentIndex.parent() != previous.parent())
         emit currentRowChanged(d->currentIndex, previous);
     if (d->currentIndex.column() != previous.column() ||
             d->currentIndex.parent() != previous.parent())
         emit currentColumnChanged(d->currentIndex, previous);
 }
The documentation for this class was generated from the following files:
/src/gui/itemviews/qitemselectionmodel.h
/src/gui/itemviews/qitemselectionmodel.cpp