Qt 4.8: QDeclarativeAnchorSet Class Reference
QDeclarativeAnchorSet Class Reference
#include <qdeclarativestateoperations_p.h>
Public Functions
QDeclarativeScriptString baseline () const
QDeclarativeScriptString bottom () const
QDeclarativeItem * centerIn () const
QDeclarativeItem * fill () const
QDeclarativeScriptString horizontalCenter () const
QDeclarativeScriptString left () const
QDeclarativeAnchorSet (QObject *parent=0)
void resetBaseline ()
void resetBottom ()
void resetCenterIn ()
void resetFill ()
void resetHorizontalCenter ()
void resetLeft ()
void resetRight ()
void resetTop ()
void resetVerticalCenter ()
QDeclarativeScriptString right () const
void setBaseline (const QDeclarativeScriptString &edge)
void setBottom (const QDeclarativeScriptString &edge)
void setCenterIn (QDeclarativeItem *)
void setFill (QDeclarativeItem *)
void setHorizontalCenter (const QDeclarativeScriptString &edge)
void setLeft (const QDeclarativeScriptString &edge)
void setRight (const QDeclarativeScriptString &edge)
void setTop (const QDeclarativeScriptString &edge)
void setVerticalCenter (const QDeclarativeScriptString &edge)
QDeclarativeScriptString top () const
QDeclarativeAnchors::Anchors usedAnchors () const
QDeclarativeScriptString verticalCenter () const
virtual ~QDeclarativeAnchorSet ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QDeclarativeScriptString baseline
QDeclarativeScriptString bottom
QDeclarativeScriptString horizontalCenter
QDeclarativeScriptString left
QDeclarativeScriptString right
QDeclarativeScriptString top
QDeclarativeScriptString verticalCenter
Friends
class QDeclarativeAnchorChanges
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 156 of file qdeclarativestateoperations_p.h.
Constructors and Destructors
QDeclarativeAnchorSet()
QDeclarativeAnchorSet::QDeclarativeAnchorSet (QObject * parent = 0)
Definition at line 781 of file qdeclarativestateoperations.cpp.
   : QObject(*new QDeclarativeAnchorSetPrivate, parent)
 {
 }
~QDeclarativeAnchorSet()
QDeclarativeAnchorSet::~QDeclarativeAnchorSet () virtual
Definition at line 786 of file qdeclarativestateoperations.cpp.
 {
 }
Functions
baseline()
QDeclarativeScriptString QDeclarativeAnchorSet::baseline () const
Referenced by resetVerticalCenter().
bottom()
QDeclarativeScriptString QDeclarativeAnchorSet::bottom () const
Referenced by resetTop().
centerIn()
QDeclarativeItem * QDeclarativeAnchorSet::centerIn () const
Definition at line 968 of file qdeclarativestateoperations.cpp.
 {
     Q_D(const QDeclarativeAnchorSet);
     return d->centerIn;
 }
fill()
QDeclarativeItem * QDeclarativeAnchorSet::fill () const
Definition at line 951 of file qdeclarativestateoperations.cpp.
 {
     Q_D(const QDeclarativeAnchorSet);
     return d->fill;
 }
horizontalCenter()
QDeclarativeScriptString QDeclarativeAnchorSet::horizontalCenter () const
Referenced by resetRight().
left()
QDeclarativeScriptString QDeclarativeAnchorSet::left () const
Referenced by resetBaseline().
resetBaseline()
void QDeclarativeAnchorSet::resetBaseline ()
Definition at line 874 of file qdeclarativestateoperations.cpp.
Referenced by setBaseline().
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors &= ~QDeclarativeAnchors::BaselineAnchor;
     d->baselineScript = QDeclarativeScriptString();
     d->resetAnchors |= QDeclarativeAnchors::BaselineAnchor;
 }
resetBottom()
void QDeclarativeAnchorSet::resetBottom ()
Definition at line 828 of file qdeclarativestateoperations.cpp.
Referenced by setBottom().
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors &= ~QDeclarativeAnchors::BottomAnchor;
     d->bottomScript = QDeclarativeScriptString();
     d->resetAnchors |= QDeclarativeAnchors::BottomAnchor;
 }
resetCenterIn()
void QDeclarativeAnchorSet::resetCenterIn ()
Definition at line 980 of file qdeclarativestateoperations.cpp.
 {
     setCenterIn(0);
 }
resetFill()
void QDeclarativeAnchorSet::resetFill ()
Definition at line 963 of file qdeclarativestateoperations.cpp.
 {
     setFill(0);
 }
resetHorizontalCenter()
void QDeclarativeAnchorSet::resetHorizontalCenter ()
Definition at line 943 of file qdeclarativestateoperations.cpp.
Referenced by setHorizontalCenter().
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors &= ~QDeclarativeAnchors::HCenterAnchor;
     d->hCenterScript = QDeclarativeScriptString();
     d->resetAnchors |= QDeclarativeAnchors::HCenterAnchor;
 }
resetLeft()
void QDeclarativeAnchorSet::resetLeft ()
Definition at line 897 of file qdeclarativestateoperations.cpp.
Referenced by setLeft().
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors &= ~QDeclarativeAnchors::LeftAnchor;
     d->leftScript = QDeclarativeScriptString();
     d->resetAnchors |= QDeclarativeAnchors::LeftAnchor;
 }
resetRight()
void QDeclarativeAnchorSet::resetRight ()
Definition at line 920 of file qdeclarativestateoperations.cpp.
Referenced by setRight().
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors &= ~QDeclarativeAnchors::RightAnchor;
     d->rightScript = QDeclarativeScriptString();
     d->resetAnchors |= QDeclarativeAnchors::RightAnchor;
 }
resetTop()
void QDeclarativeAnchorSet::resetTop ()
Definition at line 805 of file qdeclarativestateoperations.cpp.
Referenced by setTop().
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors &= ~QDeclarativeAnchors::TopAnchor;
     d->topScript = QDeclarativeScriptString();
     d->resetAnchors |= QDeclarativeAnchors::TopAnchor;
 }
resetVerticalCenter()
void QDeclarativeAnchorSet::resetVerticalCenter ()
Definition at line 851 of file qdeclarativestateoperations.cpp.
Referenced by setVerticalCenter().
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors &= ~QDeclarativeAnchors::VCenterAnchor;
     d->vCenterScript = QDeclarativeScriptString();
     d->resetAnchors |= QDeclarativeAnchors::VCenterAnchor;
 }
right()
QDeclarativeScriptString QDeclarativeAnchorSet::right () const
Referenced by resetLeft().
setBaseline()
void QDeclarativeAnchorSet::setBaseline (const QDeclarativeScriptString & edge)
Definition at line 865 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors |= QDeclarativeAnchors::BaselineAnchor;
     d->baselineScript = edge;
     if (edge.script() == QLatin1String("undefined"))
         resetBaseline();
 }
setBottom()
void QDeclarativeAnchorSet::setBottom (const QDeclarativeScriptString & edge)
Definition at line 819 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors |= QDeclarativeAnchors::BottomAnchor;
     d->bottomScript = edge;
     if (edge.script() == QLatin1String("undefined"))
         resetBottom();
 }
setCenterIn()
void QDeclarativeAnchorSet::setCenterIn (QDeclarativeItem * c)
Definition at line 974 of file qdeclarativestateoperations.cpp.
Referenced by resetCenterIn().
 {
     Q_D(QDeclarativeAnchorSet);
     d->centerIn = c;
 }
setFill()
void QDeclarativeAnchorSet::setFill (QDeclarativeItem * f)
Definition at line 957 of file qdeclarativestateoperations.cpp.
Referenced by resetFill().
 {
     Q_D(QDeclarativeAnchorSet);
     d->fill = f;
 }
setHorizontalCenter()
void QDeclarativeAnchorSet::setHorizontalCenter (const QDeclarativeScriptString & edge)
Definition at line 934 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors |= QDeclarativeAnchors::HCenterAnchor;
     d->hCenterScript = edge;
     if (edge.script() == QLatin1String("undefined"))
         resetHorizontalCenter();
 }
setLeft()
void QDeclarativeAnchorSet::setLeft (const QDeclarativeScriptString & edge)
Definition at line 888 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors |= QDeclarativeAnchors::LeftAnchor;
     d->leftScript = edge;
     if (edge.script() == QLatin1String("undefined"))
         resetLeft();
 }
setRight()
void QDeclarativeAnchorSet::setRight (const QDeclarativeScriptString & edge)
Definition at line 911 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors |= QDeclarativeAnchors::RightAnchor;
     d->rightScript = edge;
     if (edge.script() == QLatin1String("undefined"))
         resetRight();
 }
setTop()
void QDeclarativeAnchorSet::setTop (const QDeclarativeScriptString & edge)
Definition at line 796 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors |= QDeclarativeAnchors::TopAnchor;
     d->topScript = edge;
     if (edge.script() == QLatin1String("undefined"))
         resetTop();
 }
setVerticalCenter()
void QDeclarativeAnchorSet::setVerticalCenter (const QDeclarativeScriptString & edge)
Definition at line 842 of file qdeclarativestateoperations.cpp.
 {
     Q_D(QDeclarativeAnchorSet);
     d->usedAnchors |= QDeclarativeAnchors::VCenterAnchor;
     d->vCenterScript = edge;
     if (edge.script() == QLatin1String("undefined"))
         resetVerticalCenter();
 }
top()
QDeclarativeScriptString QDeclarativeAnchorSet::top () const
Referenced by ~QDeclarativeAnchorSet().
usedAnchors()
QDeclarativeAnchors::Anchors QDeclarativeAnchorSet::usedAnchors () const
Referenced by QDeclarativeAnchorChanges::copyOriginals().
verticalCenter()
QDeclarativeScriptString QDeclarativeAnchorSet::verticalCenter () const
Referenced by resetBottom().
Friends and Related Functions
QDeclarativeAnchorChanges
friend class QDeclarativeAnchorChanges friend
Definition at line 256 of file qdeclarativestateoperations_p.h.
Properties
baseline
QDeclarativeScriptString QDeclarativeAnchorSet::baseline private
Definition at line 166 of file qdeclarativestateoperations_p.h.
bottom
QDeclarativeScriptString QDeclarativeAnchorSet::bottom private
Definition at line 164 of file qdeclarativestateoperations_p.h.
horizontalCenter
QDeclarativeScriptString QDeclarativeAnchorSet::horizontalCenter private
Definition at line 162 of file qdeclarativestateoperations_p.h.
left
QDeclarativeScriptString QDeclarativeAnchorSet::left private
Definition at line 160 of file qdeclarativestateoperations_p.h.
right
QDeclarativeScriptString QDeclarativeAnchorSet::right private
Definition at line 161 of file qdeclarativestateoperations_p.h.
top
QDeclarativeScriptString QDeclarativeAnchorSet::top private
Definition at line 163 of file qdeclarativestateoperations_p.h.
verticalCenter
QDeclarativeScriptString QDeclarativeAnchorSet::verticalCenter private
Definition at line 165 of file qdeclarativestateoperations_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativestateoperations_p.h
/src/declarative/util/qdeclarativestateoperations.cpp