Qt 4.8: QVectorPath Class Reference
QVectorPath Class Reference
#include <qvectorpath_p.h>
Classes
struct CacheEntry
Public Types
enum Hint {
AreaShapeMask = 0x0001, NonConvexShapeMask = 0x0002, CurvedShapeMask = 0x0004, LinesShapeMask = 0x0008,
RectangleShapeMask = 0x0010, ShapeMask = 0x001f, LinesHint = LinesShapeMask, RectangleHint = AreaShapeMask | RectangleShapeMask,
EllipseHint = AreaShapeMask | CurvedShapeMask, ConvexPolygonHint = AreaShapeMask, PolygonHint = AreaShapeMask | NonConvexShapeMask, RoundedRectHint = AreaShapeMask | CurvedShapeMask,
ArbitraryShapeHint = AreaShapeMask | NonConvexShapeMask | CurvedShapeMask, IsCachedHint = 0x0100, ShouldUseCacheHint = 0x0200, ControlPointRect = 0x0400,
OddEvenFill = 0x1000, WindingFill = 0x2000, ImplicitClose = 0x4000
}
Public Functions
CacheEntry * addCacheData (QPaintEngineEx *engine, void *data, qvectorpath_cache_cleanup cleanup) const
QRectF controlPointRect () const
const QPainterPath convertToPainterPath () const
int elementCount () const
const QPainterPath::ElementType * elements () const
bool hasImplicitClose () const
bool hasWindingFill () const
uint hints () const
bool isCacheable () const
bool isConvex () const
bool isCurved () const
bool isEmpty () const
CacheEntry * lookupCacheData (QPaintEngineEx *engine) const
void makeCacheable () const
const qreal * points () const
QVectorPath (const qreal *points, int count, const QPainterPath::ElementType *elements=0, uint hints=ArbitraryShapeHint)
Hint shape () const
~QVectorPath ()
Static Public Functions
static uint polygonFlags (QPaintEngine::PolygonDrawMode mode)
Properties
CacheEntry * m_cache
const int m_count
QRealRect m_cp_rect
const QPainterPath::ElementType * m_elements
uint m_hints
const qreal * m_points
Detailed Description
Definition at line 77 of file qvectorpath_p.h.
Enumerations
Hint
enum QVectorPath::Hint
Enumerator
AreaShapeMask
NonConvexShapeMask
CurvedShapeMask
LinesShapeMask
RectangleShapeMask
ShapeMask
LinesHint
RectangleHint
EllipseHint
ConvexPolygonHint
PolygonHint
RoundedRectHint
ArbitraryShapeHint
IsCachedHint
ShouldUseCacheHint
ControlPointRect
OddEvenFill
WindingFill
ImplicitClose
Definition at line 80 of file qvectorpath_p.h.
               {
         // Shape hints, in 0x000000ff, access using shape()
         AreaShapeMask           = 0x0001,       // shape covers an area
         NonConvexShapeMask      = 0x0002,       // shape is not convex
         CurvedShapeMask         = 0x0004,       // shape contains curves...
         LinesShapeMask          = 0x0008,
         RectangleShapeMask      = 0x0010,
         ShapeMask               = 0x001f,
         // Shape hints merged into basic shapes..
         LinesHint               = LinesShapeMask,
         RectangleHint           = AreaShapeMask | RectangleShapeMask,
         EllipseHint             = AreaShapeMask | CurvedShapeMask,
         ConvexPolygonHint       = AreaShapeMask,
         PolygonHint             = AreaShapeMask | NonConvexShapeMask,
         RoundedRectHint         = AreaShapeMask | CurvedShapeMask,
         ArbitraryShapeHint      = AreaShapeMask | NonConvexShapeMask | CurvedShapeMask,
         // Other hints
         IsCachedHint            = 0x0100, // Set if the cache hint is set
         ShouldUseCacheHint      = 0x0200, // Set if the path should be cached when possible..
         ControlPointRect        = 0x0400, // Set if the control point rect has been calculated...
         // Shape rendering specifiers...
         OddEvenFill             = 0x1000,
         WindingFill             = 0x2000,
         ImplicitClose           = 0x4000
     };
Constructors and Destructors
QVectorPath()
QVectorPath::QVectorPath (const qreal * points, int count, const QPainterPath::ElementType * elements = 0, uint hints = ArbitraryShapeHint) inline
Definition at line 110 of file qvectorpath_p.h.
         : m_elements(elements),
           m_points(points),
           m_count(count),
           m_hints(hints)
     {
     }
~QVectorPath()
QVectorPath::~QVectorPath ()
Definition at line 61 of file qpaintengineex.cpp.
 {
     if (m_hints & ShouldUseCacheHint) {
         CacheEntry *e = m_cache;
         while (e) {
             if (e->data)
                 e->cleanup(e->engine, e->data);
             CacheEntry *n = e->next;
             delete e;
             e = n;
         }
     }
 }
Functions
addCacheData()
QVectorPath::CacheEntry * QVectorPath::addCacheData (QPaintEngineEx * engine, void * data, qvectorpath_cache_cleanup cleanup) const
Definition at line 112 of file qpaintengineex.cpp.
{
     Q_ASSERT(!lookupCacheData(engine));
     if ((m_hints & IsCachedHint) == 0) {
         m_cache = 0;
         m_hints |= IsCachedHint;
     }
     CacheEntry *e = new CacheEntry;
     e->engine = engine;
     e->data = data;
     e->cleanup = cleanup;
     e->next = m_cache;
     m_cache = e;
     return m_cache;
 }
controlPointRect()
QRectF QVectorPath::controlPointRect () const
Definition at line 76 of file qpaintengineex.cpp.
Referenced by QGL2PaintEngineEx::clip(), clipTransformIsSimple(), QEmulationPaintEngine::fill(), QRasterPaintEngine::fill(), QGL2PaintEngineExPrivate::fill(), operator<<(), QEmulationPaintEngine::stroke(), and QGL2PaintEngineExPrivate::stroke().
 {
     if (m_hints & ControlPointRect)
         return QRectF(QPointF(m_cp_rect.x1, m_cp_rect.y1), QPointF(m_cp_rect.x2, m_cp_rect.y2));
     if (m_count == 0) {
         m_cp_rect.x1 = m_cp_rect.x2 = m_cp_rect.y1 = m_cp_rect.y2 = 0;
         m_hints |= ControlPointRect;
         return QRectF(QPointF(m_cp_rect.x1, m_cp_rect.y1), QPointF(m_cp_rect.x2, m_cp_rect.y2));
     }
     Q_ASSERT(m_points && m_count > 0);
     const qreal *pts = m_points;
     m_cp_rect.x1 = m_cp_rect.x2 = *pts;
     ++pts;
     m_cp_rect.y1 = m_cp_rect.y2 = *pts;
     ++pts;
     const qreal *epts = m_points + (m_count << 1);
     while (pts < epts) {
         qreal x = *pts;
         if (x < m_cp_rect.x1) m_cp_rect.x1 = x;
         else if (x > m_cp_rect.x2) m_cp_rect.x2 = x;
         ++pts;
         qreal y = *pts;
         if (y < m_cp_rect.y1) m_cp_rect.y1 = y;
         else if (y > m_cp_rect.y2) m_cp_rect.y2 = y;
         ++pts;
     }
     m_hints |= ControlPointRect;
     return QRectF(QPointF(m_cp_rect.x1, m_cp_rect.y1), QPointF(m_cp_rect.x2, m_cp_rect.y2));
 }
convertToPainterPath()
const QPainterPath QVectorPath::convertToPainterPath () const inline
Definition at line 199 of file qpainterpath_p.h.
Referenced by clipTransformIsSimple(), QDirectFBPaintEngine::fill(), QBlittablePixmapData::markRasterOverlay(), and QPaintEngineEx::stroke().
 {
         QPainterPath path;
         path.ensureData();
         QPainterPathData *data = path.d_func();
         data->elements.reserve(m_count);
         int index = 0;
         data->elements[0].x = m_points[index++];
         data->elements[0].y = m_points[index++];
         if (m_elements) {
             data->elements[0].type = m_elements[0];
             for (int i=1; i<m_count; ++i) {
                 QPainterPath::Element element;
                 element.x = m_points[index++];
                 element.y = m_points[index++];
                 element.type = m_elements[i];
                 data->elements << element;
             }
         } else {
             data->elements[0].type = QPainterPath::MoveToElement;
             for (int i=1; i<m_count; ++i) {
                 QPainterPath::Element element;
                 element.x = m_points[index++];
                 element.y = m_points[index++];
                 element.type = QPainterPath::LineToElement;
                 data->elements << element;
             }
         }
         if (m_hints & OddEvenFill)
             data->fillRule = Qt::OddEvenFill;
         else
             data->fillRule = Qt::WindingFill;
         return path;
 }
elementCount()
int QVectorPath::elementCount () const inline
Definition at line 140 of file qvectorpath_p.h.
Referenced by QGL2PEXVertexArray::addCentroid(), QPaintBufferPrivate::addCommand(), QGL2PEXVertexArray::addPath(), QVGPaintEngine::clip(), QOpenGLPaintEngine::clip(), QRasterPaintEngine::clip(), QPaintBufferEngine::clip(), clipTransformIsSimple(), QOutlineMapper::convertPath(), QPaintBufferEngine::draw(), QCosmeticStroker::drawPath(), QDirectFBPaintEngine::fill(), QRasterPaintEngine::fill(), QPaintBufferEngine::fill(), QTriangulator< T >::initialize(), operator<<(), QTriangulatingStroker::process(), QDashedStrokeProcessor::process(), qt_painterPathFromVectorPath(), QPaintEngineEx::stroke(), QRasterPaintEngine::stroke(), QPaintBufferEngine::stroke(), and QVGPaintEnginePrivate::vectorPathToVGPath().
 { return m_count; }
elements()
const QPainterPath::ElementType* QVectorPath::elements () const inline
Definition at line 136 of file qvectorpath_p.h.
Referenced by QGL2PEXVertexArray::addCentroid(), QPaintBufferPrivate::addCommand(), QGL2PEXVertexArray::addPath(), QOpenGLPaintEngine::clip(), QRasterPaintEngine::clip(), QOutlineMapper::convertPath(), QCosmeticStroker::drawPath(), QOpenGLPaintEngine::fill(), QTriangulator< T >::initialize(), QTriangulatingStroker::process(), QDashedStrokeProcessor::process(), qt_painterPathFromVectorPath(), QPaintEngineEx::stroke(), and QVGPaintEnginePrivate::vectorPathToVGPath().
 { return m_elements; }
hasImplicitClose()
bool QVectorPath::hasImplicitClose () const inline
Definition at line 130 of file qvectorpath_p.h.
Referenced by QCosmeticStroker::drawPath(), QTriangulatingStroker::process(), QPaintEngineEx::stroke(), and QVGPaintEnginePrivate::vectorPathToVGPath().
 { return m_hints & ImplicitClose; }
hasWindingFill()
bool QVectorPath::hasWindingFill () const inline
Definition at line 131 of file qvectorpath_p.h.
Referenced by QOutlineMapper::convertPath(), QVGPaintEngine::draw(), QVGPaintEngine::fill(), QGL2PaintEngineExPrivate::fill(), and QGL2PaintEngineExPrivate::writeClip().
 { return m_hints & WindingFill; }
hints()
uint QVectorPath::hints () const inline
Definition at line 134 of file qvectorpath_p.h.
Referenced by QPaintBufferPrivate::addCommand(), QOpenGLPaintEngine::clip(), QRasterPaintEngine::fill(), QTriangulator< T >::initialize(), operator<<(), and qt_painterPathFromVectorPath().
 { return m_hints; }
isCacheable()
bool QVectorPath::isCacheable () const inline
Definition at line 129 of file qvectorpath_p.h.
Referenced by QGL2PaintEngineExPrivate::fill().
 { return m_hints & ShouldUseCacheHint; }
isConvex()
bool QVectorPath::isConvex () const inline
Definition at line 126 of file qvectorpath_p.h.
Referenced by QGL2PEXVertexArray::addPath(), and QGL2PaintEngineExPrivate::fill().
 { return (m_hints & NonConvexShapeMask) == 0; }
isCurved()
bool QVectorPath::isCurved () const inline
Definition at line 127 of file qvectorpath_p.h.
Referenced by QGL2PaintEngineExPrivate::fill().
 { return m_hints & CurvedShapeMask; }
isEmpty()
bool QVectorPath::isEmpty () const inline
Definition at line 138 of file qvectorpath_p.h.
Referenced by QOpenGLPaintEngine::clip(), QGL2PaintEngineEx::clip(), clipTransformIsSimple(), QCosmeticStroker::drawPath(), QRasterPaintEngine::fill(), QPaintEngineEx::stroke(), and QGL2PaintEngineExPrivate::writeClip().
 { return m_points == 0; }
lookupCacheData()
CacheEntry* QVectorPath::lookupCacheData (QPaintEngineEx * engine) const inline
Definition at line 153 of file qvectorpath_p.h.
Referenced by addCacheData(), and QGL2PaintEngineExPrivate::fill().
{
         Q_ASSERT(m_hints & ShouldUseCacheHint);
         CacheEntry *e = m_cache;
         while (e) {
             if (e->engine == engine)
                 return e;
             e = e->next;
         }
         return 0;
     }
makeCacheable()
void QVectorPath::makeCacheable () const inline
Definition at line 133 of file qvectorpath_p.h.
Referenced by QGL2PaintEngineExPrivate::fill().
 { m_hints |= ShouldUseCacheHint; m_cache = 0; }
points()
const qreal* QVectorPath::points () const inline
Definition at line 137 of file qvectorpath_p.h.
Referenced by QGL2PEXVertexArray::addCentroid(), QPaintBufferPrivate::addCommand(), QGL2PEXVertexArray::addPath(), QVGPaintEngine::clip(), QOpenGLPaintEngine::clip(), QGL2PaintEngineEx::clip(), QRasterPaintEngine::clip(), clipTransformIsSimple(), QOutlineMapper::convertPath(), QCosmeticStroker::drawPath(), QBlitterPaintEngine::fill(), QOpenGLPaintEngine::fill(), QDirectFBPaintEngine::fill(), QRasterPaintEngine::fill(), QGL2PaintEngineExPrivate::fill(), QTriangulator< T >::initialize(), QTriangulatingStroker::process(), QDashedStrokeProcessor::process(), qt_painterPathFromVectorPath(), QPaintEngineEx::stroke(), QRasterPaintEngine::stroke(), and QVGPaintEnginePrivate::vectorPathToVGPath().
 { return m_points; }
polygonFlags()
uint QVectorPath::polygonFlags (QPaintEngine::PolygonDrawMode mode) inline static
Definition at line 257 of file qpaintengineex_p.h.
Referenced by QRasterPaintEngine::drawPolygon(), QPaintEngineEx::drawPolygon(), and QRasterPaintEngine::fillPolygon().
{
     switch (mode) {
     case QPaintEngine::ConvexMode: return ConvexPolygonHint | ImplicitClose;
     case QPaintEngine::OddEvenMode: return PolygonHint | OddEvenFill | ImplicitClose;
     case QPaintEngine::WindingMode: return PolygonHint | WindingFill | ImplicitClose;
     case QPaintEngine::PolylineMode: return PolygonHint;
     default: return 0;
     }
 }
shape()
Hint QVectorPath::shape () const inline
Definition at line 125 of file qvectorpath_p.h.
Referenced by QVGPaintEngine::clip(), QOpenGLPaintEngine::clip(), QGL2PaintEngineEx::clip(), QRasterPaintEngine::clip(), clipTransformIsSimple(), QBlitterPaintEngine::fill(), QDirectFBPaintEngine::fill(), QOpenGLPaintEngine::fill(), QRasterPaintEngine::fill(), QGL2PaintEngineExPrivate::fill(), and QRasterPaintEngine::stroke().
 { return (Hint) (m_hints & ShapeMask); }
Properties
m_cache
CacheEntry* QVectorPath::m_cache mutable private
Definition at line 175 of file qvectorpath_p.h.
Referenced by addCacheData(), and ~QVectorPath().
m_count
const int QVectorPath::m_count private
Definition at line 170 of file qvectorpath_p.h.
Referenced by controlPointRect().
m_cp_rect
QRealRect QVectorPath::m_cp_rect mutable private
Definition at line 173 of file qvectorpath_p.h.
Referenced by controlPointRect().
m_elements
const QPainterPath::ElementType* QVectorPath::m_elements private
Definition at line 168 of file qvectorpath_p.h.
m_hints
uint QVectorPath::m_hints mutable private
Definition at line 172 of file qvectorpath_p.h.
Referenced by addCacheData(), controlPointRect(), and ~QVectorPath().
m_points
const qreal* QVectorPath::m_points private
Definition at line 169 of file qvectorpath_p.h.
Referenced by controlPointRect().
The documentation for this class was generated from the following files:
/src/gui/painting/qvectorpath_p.h
/src/gui/painting/qpaintengineex.cpp
/src/gui/painting/qpaintengineex_p.h
/src/gui/painting/qpainterpath_p.h