Qt 4.8: QPODVector< T, Increment > Class Template Reference
QPODVector< T, Increment > Class Template Reference
#include <qpodvector_p.h>
Public Functions
void append (const T &v)
const T & at (int idx) const
void clear ()
bool contains (const T &v)
void copyAndClear (QPODVector< T, Increment > &other)
int count () const
int find (const T &v)
void insert (int idx, const T &v)
void insertBlank (int idx, int count)
QPODVector< T, Increment > & operator<< (const T &v)
T & operator[] (int idx)
void prepend (const T &v)
QPODVector ()
void remove (int idx, int count=1)
void removeOne (const T &v)
void reserve (int count)
~QPODVector ()
Private Functions
QPODVector & operator= (const QPODVector &)
QPODVector (const QPODVector &)
Properties
int m_capacity
int m_count
T * m_data
Detailed Description
template<class T, int Increment = 1024>
class QPODVector< T, Increment >
Definition at line 62 of file qpodvector_p.h.
Constructors and Destructors
QPODVector() [1/2]
template<class T, int Increment = 1024> QPODVector< T, Increment >::QPODVector () inline
Definition at line 65 of file qpodvector_p.h.
Referenced by QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::operator<<().
     : m_count(0), m_capacity(0), m_data(0) {}
~QPODVector()
template<class T, int Increment = 1024> QPODVector< T, Increment >::~QPODVector () inline
Definition at line 67 of file qpodvector_p.h.
 { if (m_data) ::free(m_data); }
QPODVector() [2/2]
template<class T, int Increment = 1024> QPODVector< T, Increment >::QPODVector (const QPODVector< T, Increment > &) private
Functions
append()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::append (const T & v) inline
Definition at line 85 of file qpodvector_p.h.
Referenced by QDeclarativeGrid::doPositioning(), and QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::operator<<().
{
         insert(m_count, v);
     }
at()
template<class T, int Increment = 1024> const T& QPODVector< T, Increment >::at (int idx) const inline
Definition at line 69 of file qpodvector_p.h.
Referenced by QDeclarativeGrid::doPositioning(), QDeclarativeItemPrivate::siblingOrderChange(), and QDeclarativeQtScriptExpression::updateGuards().
{
         return m_data[idx];
     }
clear()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::clear () inline
Definition at line 77 of file qpodvector_p.h.
                  {
         m_count = 0;
     }
contains()
template<class T, int Increment = 1024> bool QPODVector< T, Increment >::contains (const T & v) inline
Definition at line 144 of file qpodvector_p.h.
{
         return find(v) != -1;
     }
copyAndClear()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::copyAndClear (QPODVector< T, Increment > & other) inline
Definition at line 152 of file qpodvector_p.h.
Referenced by QDeclarativeQtScriptExpression::scriptValue().
{
         if (other.m_data) ::free(other.m_data);
         other.m_count = m_count;
         other.m_capacity = m_capacity;
         other.m_data = m_data;
         m_count = 0;
         m_capacity = 0;
         m_data = 0;
     }
count()
template<class T, int Increment = 1024> int QPODVector< T, Increment >::count () const inline
Definition at line 148 of file qpodvector_p.h.
Referenced by QDeclarativeGrid::doPositioning(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::insertBlank(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::remove(), QDeclarativeItemPrivate::siblingOrderChange(), and QDeclarativeQtScriptExpression::updateGuards().
                       {
         return m_count;
     }
find()
template<class T, int Increment = 1024> int QPODVector< T, Increment >::find (const T & v) inline
Definition at line 137 of file qpodvector_p.h.
Referenced by QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::contains().
{
         for (int idx = 0; idx < m_count; ++idx)
             if (m_data[idx] == v)
                 return idx;
         return -1;
     }
insert()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::insert (int idx, const T & v) inline
Definition at line 89 of file qpodvector_p.h.
Referenced by QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::append(), and QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::prepend().
{
         if (m_count == m_capacity) {
             m_capacity += Increment;
             m_data = (T *)q_check_ptr(realloc(m_data, m_capacity * sizeof(T)));
         }
         int moveCount = m_count - idx;
         if (moveCount)
             ::memmove(m_data + idx + 1, m_data + idx, moveCount * sizeof(T));
         m_count++;
         m_data[idx] = v;
     }
insertBlank()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::insertBlank (int idx, int count) inline
Definition at line 108 of file qpodvector_p.h.
{
         int newSize = m_count + count;
         reserve(newSize);
         int moveCount = m_count - idx;
         if (moveCount)
             ::memmove(m_data + idx + count,  m_data + idx,
                       moveCount * sizeof(T));
         m_count = newSize;
     }
operator<<()
template<class T, int Increment = 1024> QPODVector<T,Increment>& QPODVector< T, Increment >::operator<< (const T & v) inline
Definition at line 162 of file qpodvector_p.h.
 { append(v); return *this; }
operator=()
template<class T, int Increment = 1024> QPODVector& QPODVector< T, Increment >::operator= (const QPODVector< T, Increment > &) private
Referenced by QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::operator<<().
operator[]()
template<class T, int Increment = 1024> T& QPODVector< T, Increment >::operator[] (int idx) inline
Definition at line 73 of file qpodvector_p.h.
{
         return m_data[idx];
     }
prepend()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::prepend (const T & v) inline
Definition at line 81 of file qpodvector_p.h.
{
         insert(0, v);
     }
remove()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::remove (int idx, int count = 1) inline
Definition at line 118 of file qpodvector_p.h.
{
         int moveCount = m_count - (idx + count);
         if (moveCount)
             ::memmove(m_data + idx, m_data + idx + count,
                       moveCount * sizeof(T));
         m_count -= count;
     }
removeOne()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::removeOne (const T & v) inline
Definition at line 126 of file qpodvector_p.h.
{
         int idx = 0;
         while (idx < m_count) {
             if (m_data[idx] == v) {
                 remove(idx);
                 return;
             }
             ++idx;
         }
     }
reserve()
template<class T, int Increment = 1024> void QPODVector< T, Increment >::reserve (int count) inline
Definition at line 101 of file qpodvector_p.h.
Referenced by QDeclarativeGrid::doPositioning(), and QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::insertBlank().
{
         if (count >= m_capacity) {
             m_capacity = (count + (Increment-1)) & (0xFFFFFFFF - Increment + 1);
             m_data = (T *)q_check_ptr(realloc(m_data, m_capacity * sizeof(T)));
         }
     }
Properties
m_capacity
template<class T, int Increment = 1024> int QPODVector< T, Increment >::m_capacity private
Definition at line 167 of file qpodvector_p.h.
Referenced by QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::copyAndClear(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::insert(), and QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::reserve().
m_count
template<class T, int Increment = 1024> int QPODVector< T, Increment >::m_count private
Definition at line 166 of file qpodvector_p.h.
Referenced by QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::append(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::clear(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::copyAndClear(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::count(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::find(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::insert(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::insertBlank(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::remove(), and QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::removeOne().
m_data
template<class T, int Increment = 1024> T* QPODVector< T, Increment >::m_data private
Definition at line 168 of file qpodvector_p.h.
Referenced by QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::at(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::copyAndClear(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::find(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::insert(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::insertBlank(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::operator[](), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::remove(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::removeOne(), QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::reserve(), and QPODVector< QDeclarativeEnginePrivate::CapturedProperty, 16 >::~QPODVector().
The documentation for this class was generated from the following file:
/src/declarative/qml/qpodvector_p.h