Qt 4.8: QXmlReader Class Reference
QXmlReader Class Reference abstract
The QXmlReader class provides an interface for XML readers (i.e.
#include <qxml.h>
Public Functions
virtual QXmlContentHandler * contentHandler () const =0
Returns the content handler or 0 if none was set.
virtual QXmlDeclHandler * declHandler () const =0
Returns the declaration handler or 0 if none was set.
virtual QXmlDTDHandler * DTDHandler () const =0
Returns the DTD handler or 0 if none was set.
virtual QXmlEntityResolver * entityResolver () const =0
Returns the entity resolver or 0 if none was set.
virtual QXmlErrorHandler * errorHandler () const =0
Returns the error handler or 0 if none is set.
virtual bool feature (const QString &name, bool *ok=0) const =0
If the reader has the feature called name, the feature's value is returned.
virtual bool hasFeature (const QString &name) const =0
Returns true if the reader has the feature called name; otherwise returns false.
virtual bool hasProperty (const QString &name) const =0
Returns true if the reader has the property name; otherwise returns false.
virtual QXmlLexicalHandler * lexicalHandler () const =0
Returns the lexical handler or 0 if none was set.
virtual bool parse (const QXmlInputSource &input)=0
Parses the given input.
virtual bool parse (const QXmlInputSource *input)=0
Reads an XML document from input and parses it.
virtual void * property (const QString &name, bool *ok=0) const =0
If the reader has the property name, this function returns the value of the property; otherwise the return value is undefined.
virtual void setContentHandler (QXmlContentHandler *handler)=0
Sets the content handler to handler.
virtual void setDeclHandler (QXmlDeclHandler *handler)=0
Sets the declaration handler to handler.
virtual void setDTDHandler (QXmlDTDHandler *handler)=0
Sets the DTD handler to handler.
virtual void setEntityResolver (QXmlEntityResolver *handler)=0
Sets the entity resolver to handler.
virtual void setErrorHandler (QXmlErrorHandler *handler)=0
Sets the error handler to handler.
virtual void setFeature (const QString &name, bool value)=0
Sets the feature called name to the given value.
virtual void setLexicalHandler (QXmlLexicalHandler *handler)=0
Sets the lexical handler to handler.
virtual void setProperty (const QString &name, void *value)=0
Sets the property name to value.
virtual ~QXmlReader ()
Destroys the reader.
Detailed Description
The QXmlReader class provides an interface for XML readers (i.e.
parsers).
Note
This class or function is reentrant.
Attention
Module: QtXml
This abstract class provides an interface for all of Qt's XML readers. Currently there is only one implementation of a reader included in Qt's XML module: QXmlSimpleReader. In future releases there might be more readers with different properties available (e.g. a validating parser).
The design of the XML classes follows the SAX2 Java interface, with the names adapted to fit Qt naming conventions. It should be very easy for anybody who has worked with SAX2 to get started with the Qt XML classes.
All readers use the class QXmlInputSource to read the input document. Since you are normally interested in particular content in the XML document, the reader reports the content through special handler classes (QXmlDTDHandler, QXmlDeclHandler, QXmlContentHandler, QXmlEntityResolver, QXmlErrorHandler and QXmlLexicalHandler), which you must subclass, if you want to process the contents.
Since the handler classes only describe interfaces you must implement all the functions. We provide the QXmlDefaultHandler class to make this easier: it implements a default behavior (do nothing) for all functions, so you can subclass it and just implement the functions you are interested in.
Features and properties of the reader can be set with setFeature() and setProperty() respectively. You can set the reader to use your own subclasses with setEntityResolver(), setDTDHandler(), setContentHandler(), setErrorHandler(), setLexicalHandler() and setDeclHandler(). The parse itself is started with a call to parse().
See also
QXmlSimpleReader
Definition at line 215 of file qxml.h.
Constructors and Destructors
~QXmlReader()
QXmlReader::~QXmlReader () inline virtual
Destroys the reader.
Definition at line 218 of file qxml.h.
 {}
Functions
contentHandler()
QXmlContentHandler * QXmlReader::contentHandler () const pure virtual
Returns the content handler or 0 if none was set.
See also
setContentHandler()
Implemented in QXmlSimpleReader.
declHandler()
QXmlDeclHandler * QXmlReader::declHandler () const pure virtual
Returns the declaration handler or 0 if none was set.
See also
setDeclHandler()
Implemented in QXmlSimpleReader.
DTDHandler()
QXmlDTDHandler * QXmlReader::DTDHandler () const pure virtual
Returns the DTD handler or 0 if none was set.
See also
setDTDHandler()
Implemented in QXmlSimpleReader.
entityResolver()
QXmlEntityResolver * QXmlReader::entityResolver () const pure virtual
Returns the entity resolver or 0 if none was set.
See also
setEntityResolver()
Implemented in QXmlSimpleReader.
errorHandler()
QXmlErrorHandler * QXmlReader::errorHandler () const pure virtual
Returns the error handler or 0 if none is set.
See also
setErrorHandler()
Implemented in QXmlSimpleReader.
feature()
bool QXmlReader::feature (const QString & name, bool * ok = 0) const pure virtual
If the reader has the feature called name, the feature's value is returned.
If no such feature exists the return value is undefined.
If ok is not 0: *{ok} is set to true if the reader has the feature called name; otherwise *{ok} is set to false.
See also
setFeature(), hasFeature()
Implemented in QXmlSimpleReader.
Referenced by QDomDocumentPrivate::setContent().
hasFeature()
bool QXmlReader::hasFeature (const QString & name) const pure virtual
Returns true if the reader has the feature called name; otherwise returns false.
See also
feature(), setFeature()
Implemented in QXmlSimpleReader.
hasProperty()
bool QXmlReader::hasProperty (const QString & name) const pure virtual
Returns true if the reader has the property name; otherwise returns false.
See also
property(), setProperty()
Implemented in QXmlSimpleReader.
lexicalHandler()
QXmlLexicalHandler * QXmlReader::lexicalHandler () const pure virtual
Returns the lexical handler or 0 if none was set.
See also
setLexicalHandler()
Implemented in QXmlSimpleReader.
parse() [1/2]
bool QXmlReader::parse (const QXmlInputSource & input) pure virtual
Parses the given input.
Implemented in QXmlSimpleReader.
Referenced by QDomDocumentPrivate::setContent().
parse() [2/2]
bool QXmlReader::parse (const QXmlInputSource * input) pure virtual
Reads an XML document from input and parses it.
Returns true if the parsing was successful; otherwise returns false.
Implemented in QXmlSimpleReader.
property()
void * QXmlReader::property (const QString & name, bool * ok = 0) const pure virtual
If the reader has the property name, this function returns the value of the property; otherwise the return value is undefined.
If ok is not 0: if the reader has the name property *{ok} is set to true; otherwise *{ok} is set to false.
See also
setProperty(), hasProperty()
Implemented in QXmlSimpleReader.
setContentHandler()
void QXmlReader::setContentHandler (QXmlContentHandler * handler) pure virtual
Sets the content handler to handler.
See also
contentHandler()
Implemented in QXmlSimpleReader.
Referenced by QDomDocumentPrivate::setContent().
setDeclHandler()
void QXmlReader::setDeclHandler (QXmlDeclHandler * handler) pure virtual
Sets the declaration handler to handler.
See also
declHandler()
Implemented in QXmlSimpleReader.
Referenced by QDomDocumentPrivate::setContent().
setDTDHandler()
void QXmlReader::setDTDHandler (QXmlDTDHandler * handler) pure virtual
Sets the DTD handler to handler.
See also
DTDHandler()
Implemented in QXmlSimpleReader.
Referenced by QDomDocumentPrivate::setContent().
setEntityResolver()
void QXmlReader::setEntityResolver (QXmlEntityResolver * handler) pure virtual
Sets the entity resolver to handler.
See also
entityResolver()
Implemented in QXmlSimpleReader.
setErrorHandler()
void QXmlReader::setErrorHandler (QXmlErrorHandler * handler) pure virtual
Sets the error handler to handler.
Clears the error handler if handler is 0.
See also
errorHandler()
Implemented in QXmlSimpleReader.
Referenced by QDomDocumentPrivate::setContent().
setFeature()
void QXmlReader::setFeature (const QString & name, bool value) pure virtual
Sets the feature called name to the given value.
If the reader doesn't have the feature nothing happens.
See also
feature(), hasFeature()
Implemented in QXmlSimpleReader.
setLexicalHandler()
void QXmlReader::setLexicalHandler (QXmlLexicalHandler * handler) pure virtual
Sets the lexical handler to handler.
See also
lexicalHandler()
Implemented in QXmlSimpleReader.
Referenced by QDomDocumentPrivate::setContent().
setProperty()
void QXmlReader::setProperty (const QString & name, void * value) pure virtual
Sets the property name to value.
If the reader doesn't have the property nothing happens.
See also
property(), hasProperty()
Implemented in QXmlSimpleReader.
The documentation for this class was generated from the following files:
/src/xml/sax/qxml.h
/src/xml/sax/qxml.cpp