Qt 4.8: QToolBarAreaLayoutItem Class Reference
QToolBarAreaLayoutItem Class Reference
#include <qtoolbararealayout_p.h>
Public Functions
void extendSize (Qt::Orientation o, int extent)
QSize minimumSize () const
QToolBarAreaLayoutItem (QLayoutItem *item=0)
QSize realSizeHint () const
void resize (Qt::Orientation o, int newSize)
QSize sizeHint () const
bool skip () const
Public Variables
bool gap
int pos
int preferredSize
int size
QLayoutItem * widgetItem
Detailed Description
Definition at line 96 of file qtoolbararealayout_p.h.
Constructors and Destructors
QToolBarAreaLayoutItem()
QToolBarAreaLayoutItem::QToolBarAreaLayoutItem (QLayoutItem * item = 0) inline
Definition at line 99 of file qtoolbararealayout_p.h.
         : widgetItem(item), pos(0), size(-1), preferredSize(-1), gap(false) {}
Functions
extendSize()
void QToolBarAreaLayoutItem::extendSize (Qt::Orientation o, int extent) inline
Definition at line 119 of file qtoolbararealayout_p.h.
Referenced by QToolBarAreaLayoutInfo::moveToolBar().
     {
         int newSize = qMax(pick(o, minimumSize()), (preferredSize > 0 ? preferredSize : pick(o, sizeHint())) + extent);
         int sizeh = pick(o, sizeHint());
         if (newSize == sizeh) {
             preferredSize = -1;
             size = sizeh;
         } else {
             preferredSize = newSize;
         }
     }
minimumSize()
QSize QToolBarAreaLayoutItem::minimumSize () const
Definition at line 65 of file qtoolbararealayout.cpp.
Referenced by extendSize(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayoutLine::minimumSize(), QToolBarAreaLayoutInfo::moveToolBar(), QToolBarAreaLayoutItem(), and resize().
 {
     if (skip())
         return QSize(0, 0);
     return qSmartMinSize(static_cast<QWidgetItem*>(widgetItem));
 }
realSizeHint()
QSize QToolBarAreaLayoutItem::realSizeHint () const
Definition at line 81 of file qtoolbararealayout.cpp.
Referenced by QToolBarAreaLayoutItem(), and sizeHint().
 {
     QWidget *wid = widgetItem->widget();
     QSize s = wid->sizeHint().expandedTo(wid->minimumSizeHint());
     if (wid->sizePolicy().horizontalPolicy() == QSizePolicy::Ignored)
         s.setWidth(0);
     if (wid->sizePolicy().verticalPolicy() == QSizePolicy::Ignored)
         s.setHeight(0);
     s = s.boundedTo(wid->maximumSize())
         .expandedTo(wid->minimumSize());
     return s;
 }
resize()
void QToolBarAreaLayoutItem::resize (Qt::Orientation o, int newSize) inline
Definition at line 107 of file qtoolbararealayout_p.h.
Referenced by QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::moveToolBar(), and QToolBarAreaLayout::unplug().
     {
         newSize = qMax(pick(o, minimumSize()), newSize);
         int sizeh = pick(o, sizeHint());
         if (newSize == sizeh) {
             preferredSize = -1;
             size = sizeh;
         } else {
             preferredSize = newSize;
         }
     }
sizeHint()
QSize QToolBarAreaLayoutItem::sizeHint () const
Definition at line 72 of file qtoolbararealayout.cpp.
Referenced by extendSize(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayoutInfo::gapIndex(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::moveToolBar(), QToolBarAreaLayoutItem(), resize(), QToolBarAreaLayoutLine::sizeHint(), and QToolBarAreaLayout::unplug().
 {
     if (skip())
         return QSize(0, 0);
     return realSizeHint();
 }
skip()
bool QToolBarAreaLayoutItem::skip () const
Definition at line 94 of file qtoolbararealayout.cpp.
Referenced by QToolBarAreaLayout::apply(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayoutInfo::gapIndex(), QToolBarAreaLayoutInfo::insertGap(), minimumSize(), QToolBarAreaLayoutLine::minimumSize(), QToolBarAreaLayoutInfo::moveToolBar(), QToolBarAreaLayoutItem(), sizeHint(), QToolBarAreaLayoutLine::sizeHint(), QToolBarAreaLayoutLine::skip(), and QToolBarAreaLayout::unplug().
 {
     if (gap)
         return false;
     return widgetItem == 0 || widgetItem->isEmpty();
 }
Properties
gap
bool QToolBarAreaLayoutItem::gap
Definition at line 135 of file qtoolbararealayout_p.h.
Referenced by QToolBarAreaLayout::apply(), QToolBarAreaLayout::deleteAllLayoutItems(), QToolBarAreaLayout::indexOf(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayout::plug(), and skip().
pos
int QToolBarAreaLayoutItem::pos
Definition at line 132 of file qtoolbararealayout_p.h.
Referenced by QToolBarAreaLayout::apply(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayoutInfo::gapIndex(), QToolBarAreaLayoutInfo::itemRect(), QToolBarAreaLayoutInfo::moveToolBar(), QToolBarAreaLayout::restoreState(), QToolBarAreaLayout::saveState(), and QToolBarAreaLayout::unplug().
preferredSize
int QToolBarAreaLayoutItem::preferredSize
Definition at line 134 of file qtoolbararealayout_p.h.
Referenced by extendSize(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayoutInfo::insertGap(), resize(), QToolBarAreaLayout::restoreState(), QToolBarAreaLayout::saveState(), and QToolBarAreaLayoutLine::sizeHint().
size
int QToolBarAreaLayoutItem::size
Definition at line 133 of file qtoolbararealayout_p.h.
Referenced by QToolBarAreaLayout::apply(), extendSize(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayoutInfo::gapIndex(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::itemRect(), QToolBarAreaLayoutInfo::moveToolBar(), resize(), and QToolBarAreaLayout::restoreState().
widgetItem
QLayoutItem* QToolBarAreaLayoutItem::widgetItem
Definition at line 131 of file qtoolbararealayout_p.h.
Referenced by QToolBarAreaLayout::apply(), QToolBarAreaLayout::deleteAllLayoutItems(), QToolBarAreaLayout::findToolBar(), QToolBarAreaLayoutLine::fitLayout(), QToolBarAreaLayout::getStyleOptionInfo(), QToolBarAreaLayout::indexOf(), QToolBarAreaLayoutInfo::insertGap(), QToolBarAreaLayoutInfo::insertItem(), QToolBarAreaLayoutInfo::insertToolBarBreak(), QMainWindowLayoutState::item(), QToolBarAreaLayout::itemAt(), minimumSize(), QToolBarAreaLayoutInfo::moveToolBar(), QToolBarAreaLayout::plug(), realSizeHint(), QToolBarAreaLayoutInfo::removeToolBar(), QToolBarAreaLayoutInfo::removeToolBarBreak(), QToolBarAreaLayout::restoreState(), QToolBarAreaLayout::saveState(), skip(), QToolBarAreaLayout::takeAt(), and QToolBarAreaLayout::toolBarBreak().
The documentation for this class was generated from the following files:
/src/gui/widgets/qtoolbararealayout_p.h
/src/gui/widgets/qtoolbararealayout.cpp