Qt 4.8: QPatternist::TargetNode Class Reference
QPatternist::TargetNode Class Reference
A helper class for validating identity constraints.
#include <qxsdidchelper_p.h>
Public Types
typedef QSet< TargetNode > Set
Public Functions
void addField (const QXmlItem &item, const QString &data, const SchemaType::Ptr &type)
int emptyFieldsCount () const
QVector< QXmlItem > fieldItems () const
bool fieldsAreEqual (const TargetNode &other, const NamePool::Ptr &namePool, const ReportContext::Ptr &context, const SourceLocationReflection *const reflection) const
QXmlItem item () const
bool operator== (const TargetNode &other) const
TargetNode (const QXmlItem &item)
Properties
QVector< FieldNode > m_fields
QXmlItem m_item
Detailed Description
A helper class for validating identity constraints.
This class represents a target or qualified node from the target or qualified node set as defined in the validation rules at http://www.w3.org/TR/xmlschema11-1/#d0e32243.
A target node is part of the qualified node set, if all of its fields are not empty.
Definition at line 125 of file qxsdidchelper_p.h.
Typedefs
Set
typedef QSet<TargetNode> QPatternist::TargetNode::Set
Defines a set of target nodes.
Definition at line 131 of file qxsdidchelper_p.h.
Constructors and Destructors
TargetNode()
TargetNode::TargetNode (const QXmlItem & item) explicit
Creates a new target node that is bound to the xml node item.
Definition at line 83 of file qxsdidchelper.cpp.
     : m_item(item)
 {
 }
Functions
addField()
void TargetNode::addField (const QXmlItem & item, const QString & data, const SchemaType::Ptr & type)
Adds a new field to the target node with the given values.
Definition at line 127 of file qxsdidchelper.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::selectNodeSets().
 {
     m_fields.append(FieldNode(item, data, type));
 }
emptyFieldsCount()
int TargetNode::emptyFieldsCount () const
Returns the number of fields that are empty.
Definition at line 103 of file qxsdidchelper.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::selectNodeSets().
 {
     int counter = 0;
     for (int i = 0; i < m_fields.count(); ++i) {
         if (m_fields.at(i).isEmpty())
             ++counter;
     }
     return counter;
 }
fieldItems()
QVector< QXmlItem > TargetNode::fieldItems () const
Returns all xml node items, the fields of that target node are bound to.
Definition at line 93 of file qxsdidchelper.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateKeyIdentityConstraint().
 {
     QVector<QXmlItem> items;
     for (int i = 0; i < m_fields.count(); ++i)
         items.append(m_fields.at(i).item());
     return items;
 }
fieldsAreEqual()
bool TargetNode::fieldsAreEqual (const TargetNode & other, const NamePool::Ptr & namePool, const ReportContext::Ptr & context, const SourceLocationReflection *const reflection) const
Returns whether the target node has the same fields as the other target node.
Definition at line 114 of file qxsdidchelper.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateKeyRefIdentityConstraint(), and QPatternist::XsdValidatingInstanceReader::validateUniqueIdentityConstraint().
 {
     if (m_fields.count() != other.m_fields.count())
         return false;
     for (int i = 0; i < m_fields.count(); ++i) {
         if (!m_fields.at(i).isEqualTo(other.m_fields.at(i), namePool, context, reflection))
             return false;
     }
     return true;
 }
item()
QXmlItem TargetNode::item () const
Returns the xml node item the target node is bound to.
Definition at line 88 of file qxsdidchelper.cpp.
Referenced by QPatternist::qHash().
 {
     return m_item;
 }
operator==()
bool TargetNode::operator== (const TargetNode & other) const
Returns whether the target node is equal to the other target node.
Definition at line 132 of file qxsdidchelper.cpp.
 {
     return (m_item.toNodeModelIndex() == other.m_item.toNodeModelIndex());
 }
Properties
m_fields
QVector<FieldNode> QPatternist::TargetNode::m_fields private
Definition at line 170 of file qxsdidchelper_p.h.
Referenced by addField(), emptyFieldsCount(), fieldItems(), and fieldsAreEqual().
m_item
QXmlItem QPatternist::TargetNode::m_item private
Definition at line 169 of file qxsdidchelper_p.h.
Referenced by item(), and operator==().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdidchelper_p.h
/src/xmlpatterns/schema/qxsdidchelper.cpp