Qt 4.8: QDeclarativeSpringAnimation Class Reference
QDeclarativeSpringAnimation Class Reference
#include <qdeclarativespringanimation_p.h>
Signals
void massChanged ()
void modulusChanged ()
void syncChanged ()
Signals inherited from QDeclarativePropertyAnimation
void durationChanged (int)
void easingChanged (const QEasingCurve &)
void fromChanged (QVariant)
void propertiesChanged (const QString &)
void propertyChanged ()
void targetChanged ()
void toChanged (QVariant)
Signals inherited from QDeclarativeAbstractAnimation
void alwaysRunToEndChanged (bool)
void completed ()
void loopCountChanged (int)
void pausedChanged (bool)
void runningChanged (bool)
void started ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qreal damping () const
qreal epsilon () const
qreal mass () const
qreal modulus () const
QDeclarativeSpringAnimation (QObject *parent=0)
void setDamping (qreal damping)
void setEpsilon (qreal epsilon)
void setMass (qreal modulus)
void setModulus (qreal modulus)
void setSpring (qreal spring)
void setVelocity (qreal velocity)
qreal spring () const
virtual void transition (QDeclarativeStateActions &actions, QDeclarativeProperties &modified, TransitionDirection direction)
qreal velocity () const
~QDeclarativeSpringAnimation ()
Public Functions inherited from QDeclarativeNumberAnimation
qreal from () const
QDeclarativeNumberAnimation (QObject *parent=0)
void setFrom (qreal)
void setTo (qreal)
qreal to () const
virtual ~QDeclarativeNumberAnimation ()
Public Functions inherited from QDeclarativePropertyAnimation
virtual int duration () const
QEasingCurve easing () const
QDeclarativeListProperty< QObject > exclude ()
QVariant from () const
QString properties () const
QString property () const
QDeclarativePropertyAnimation (QObject *parent=0)
virtual void setDuration (int)
void setEasing (const QEasingCurve &)
void setFrom (const QVariant &)
void setProperties (const QString &)
void setProperty (const QString &)
void setTarget (QObject *)
void setTo (const QVariant &)
QObject * target () const
QDeclarativeListProperty< QObject > targets ()
QVariant to () const
virtual ~QDeclarativePropertyAnimation ()
Public Functions inherited from QDeclarativeAbstractAnimation
bool alwaysRunToEnd () const
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
int currentTime ()
QDeclarativeAnimationGroup * group () const
bool isPaused () const
bool isRunning () const
int loops () const
QDeclarativeAbstractAnimation (QObject *parent=0)
void setAlwaysRunToEnd (bool)
void setCurrentTime (int)
void setDefaultTarget (const QDeclarativeProperty &)
void setDisableUserControl ()
void setGroup (QDeclarativeAnimationGroup *)
void setLoops (int)
void setPaused (bool)
void setRunning (bool)
virtual ~QDeclarativeAbstractAnimation ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativePropertyValueSource
QDeclarativePropertyValueSource ()
Constructs a QDeclarativePropertyValueSource.
virtual ~QDeclarativePropertyValueSource ()
Destroys the value source.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
virtual QAbstractAnimation * qtAnimation ()
Protected Functions inherited from QDeclarativeNumberAnimation
QDeclarativeNumberAnimation (QDeclarativePropertyAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QDeclarativePropertyAnimation
QDeclarativePropertyAnimation (QDeclarativePropertyAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QDeclarativeAbstractAnimation
QDeclarativeAbstractAnimation (QDeclarativeAbstractAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
qreal damping
qreal epsilon
qreal mass
qreal modulus
qreal spring
qreal velocity
Additional Inherited Members
Public Types inherited from QDeclarativeAbstractAnimation
enum Loops { Infinite = -2 }
enum TransitionDirection { Forward, Backward }
Public Slots inherited from QDeclarativeAbstractAnimation
void complete ()
void pause ()
void restart ()
void resume ()
void start ()
void stop ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 57 of file qdeclarativespringanimation_p.h.
Constructors and Destructors
QDeclarativeSpringAnimation()
QDeclarativeSpringAnimation::QDeclarativeSpringAnimation (QObject * parent = 0)
Definition at line 267 of file qdeclarativespringanimation.cpp.
 : QDeclarativeNumberAnimation(*(new QDeclarativeSpringAnimationPrivate),parent)
 {
     Q_D(QDeclarativeSpringAnimation);
     d->clock = new QDeclarativeSpringAnimationPrivate::Clock(d, this);
 }
~QDeclarativeSpringAnimation()
QDeclarativeSpringAnimation::~QDeclarativeSpringAnimation ()
Definition at line 274 of file qdeclarativespringanimation.cpp.
 {
 }
Functions
damping()
qreal QDeclarativeSpringAnimation::damping () const
Referenced by setDamping(), and setSpring().
epsilon()
qreal QDeclarativeSpringAnimation::epsilon () const
Referenced by setDamping(), and setEpsilon().
mass()
qreal QDeclarativeSpringAnimation::mass () const
Referenced by setMass(), and setModulus().
massChanged
void QDeclarativeSpringAnimation::massChanged () signal
Referenced by setMass().
modulus()
qreal QDeclarativeSpringAnimation::modulus () const
Referenced by setEpsilon(), and setModulus().
modulusChanged
void QDeclarativeSpringAnimation::modulusChanged () signal
Referenced by setModulus().
qtAnimation()
QAbstractAnimation * QDeclarativeSpringAnimation::qtAnimation () protected virtual
Reimplemented from QDeclarativePropertyAnimation.
Definition at line 477 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     return d->clock;
 }
setDamping()
void QDeclarativeSpringAnimation::setDamping (qreal damping)
Definition at line 349 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     if (damping > 1.)
         damping = 1.;
     d->damping = damping;
 }
setEpsilon()
void QDeclarativeSpringAnimation::setEpsilon (qreal epsilon)
Definition at line 378 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     d->epsilon = epsilon;
 }
setMass()
void QDeclarativeSpringAnimation::setMass (qreal modulus)
Definition at line 429 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     if (d->mass != mass && mass > 0.0) {
         d->useMass = mass != 1.0;
         d->mass = mass;
         emit massChanged();
     }
 }
setModulus()
void QDeclarativeSpringAnimation::setModulus (qreal modulus)
Definition at line 400 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     if (d->modulus != modulus) {
         d->haveModulus = modulus != 0.0;
         d->modulus = modulus;
         d->updateMode();
         emit modulusChanged();
     }
 }
setSpring()
void QDeclarativeSpringAnimation::setSpring (qreal spring)
Definition at line 323 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     d->spring = spring;
     d->updateMode();
 }
setVelocity()
void QDeclarativeSpringAnimation::setVelocity (qreal velocity)
Definition at line 295 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     d->maxVelocity = velocity;
     d->velocityms = velocity / 1000.0;
     d->updateMode();
 }
spring()
qreal QDeclarativeSpringAnimation::spring () const
Referenced by setSpring(), and setVelocity().
syncChanged
void QDeclarativeSpringAnimation::syncChanged () signal
transition()
void QDeclarativeSpringAnimation::transition (QDeclarativeStateActions & actions, QDeclarativeProperties & modified, TransitionDirection direction) virtual
Reimplemented from QDeclarativePropertyAnimation.
Definition at line 439 of file qdeclarativespringanimation.cpp.
 {
     Q_D(QDeclarativeSpringAnimation);
     Q_UNUSED(direction);
     if (d->clock->state() != QAbstractAnimation::Running) {
         d->lastTime = 0;
     }
     QDeclarativeNumberAnimation::transition(actions, modified, direction);
     if (!d->actions)
         return;
     if (!d->actions->isEmpty()) {
         for (int i = 0; i < d->actions->size(); ++i) {
             const QDeclarativeProperty &property = d->actions->at(i).property;
             QDeclarativeSpringAnimationPrivate::SpringAnimation &animation
                     = d->activeAnimations[property];
             animation.to = d->actions->at(i).toValue.toReal();
             animation.start = d->lastTime;
             if (d->fromIsDefined)
                 animation.currentValue = d->actions->at(i).fromValue.toReal();
             else
                 animation.currentValue = property.read().toReal();
             if (d->mode == QDeclarativeSpringAnimationPrivate::Velocity) {
                 qreal dist = qAbs(animation.currentValue - animation.to);
                 if (d->haveModulus && dist > d->modulus / 2)
                     dist = d->modulus - fmod(dist, d->modulus);
                 animation.duration = dist / d->velocityms;
             }
         }
     }
 }
velocity()
qreal QDeclarativeSpringAnimation::velocity () const
Referenced by setVelocity(), and ~QDeclarativeSpringAnimation().
Properties
damping
qreal QDeclarativeSpringAnimation::damping private
Definition at line 65 of file qdeclarativespringanimation_p.h.
epsilon
qreal QDeclarativeSpringAnimation::epsilon private
Definition at line 66 of file qdeclarativespringanimation_p.h.
mass
qreal QDeclarativeSpringAnimation::mass private
Definition at line 68 of file qdeclarativespringanimation_p.h.
modulus
qreal QDeclarativeSpringAnimation::modulus private
Definition at line 67 of file qdeclarativespringanimation_p.h.
spring
qreal QDeclarativeSpringAnimation::spring private
Definition at line 64 of file qdeclarativespringanimation_p.h.
velocity
qreal QDeclarativeSpringAnimation::velocity private
Definition at line 63 of file qdeclarativespringanimation_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativespringanimation_p.h
/src/declarative/util/qdeclarativespringanimation.cpp