Qt 4.8: QTestCoreElement< ElementType > Class Template Reference
QTestCoreElement< ElementType > Class Template Reference
#include <qtestcoreelement.h>
Public Functions
void addAttribute (const QTest::AttributeIndex index, const char *value)
const QTestElementAttribute * attribute (QTest::AttributeIndex index) const
const char * attributeName (QTest::AttributeIndex index) const
QTestElementAttribute * attributes () const
const char * attributeValue (QTest::AttributeIndex index) const
const char * elementName () const
QTest::LogElementType elementType () const
QTestCoreElement (int type=-1)
virtual ~QTestCoreElement ()
Public Functions inherited from QTestCoreList< ElementType >
void addToList (ElementType **list)
int count (ElementType *list)
int count ()
ElementType * nextElement ()
ElementType * previousElement ()
QTestCoreList ()
virtual ~QTestCoreList ()
Properties
QTestElementAttribute * listOfAttributes
QTest::LogElementType type
Detailed Description
template<class ElementType>
class QTestCoreElement< ElementType >
Definition at line 55 of file qtestcoreelement.h.
Constructors and Destructors
QTestCoreElement()
template<class ElementType > QTestCoreElement< ElementType >::QTestCoreElement (int type = -1)
Definition at line 76 of file qtestcoreelement.h.
     :listOfAttributes(0), type(QTest::LogElementType(t))
 {
 }
~QTestCoreElement()
template<class ElementType > QTestCoreElement< ElementType >::~QTestCoreElement () virtual
Definition at line 82 of file qtestcoreelement.h.
 {
     delete listOfAttributes;
 }
Functions
addAttribute()
template<class ElementType > void QTestCoreElement< ElementType >::addAttribute (const QTest::AttributeIndex index, const char * value)
Definition at line 88 of file qtestcoreelement.h.
Referenced by QTestLogger::addBenchmarkResult(), QTestLogger::addIncident(), QTestLogger::addMessage(), QTestLogger::addTag(), QTestLogger::enterTestFunction(), and QTestLogger::stopLogging().
 {
     if(attributeIndex == -1)
         return;
     if (attribute(attributeIndex))
         return;
     QTestElementAttribute *testAttribute = new QTestElementAttribute;
     testAttribute->setPair(attributeIndex, value);
     testAttribute->addToList(&listOfAttributes);
 }
attribute()
template<class ElementType > const QTestElementAttribute * QTestCoreElement< ElementType >::attribute (QTest::AttributeIndex index) const
Definition at line 155 of file qtestcoreelement.h.
Referenced by QTestCoreElement< QTestElement >::addAttribute(), QTestLogger::addIncident(), QTestCoreElement< QTestElement >::attributeName(), QTestCoreElement< QTestElement >::attributeValue(), QTestLightXmlStreamer::formatBeforeAttributes(), QTestLightXmlStreamer::formatEnd(), QTestXmlStreamer::formatEnd(), and QTestXmlStreamer::formatStart().
 {
     QTestElementAttribute *iterator = listOfAttributes;
     while(iterator){
         if(iterator->index() == index)
             return iterator;
         iterator = iterator->nextElement();
     }
     return 0;
 }
attributeName()
template<class ElementType > const char * QTestCoreElement< ElementType >::attributeName (QTest::AttributeIndex index) const
Definition at line 118 of file qtestcoreelement.h.
Referenced by QTestLightXmlStreamer::formatBeforeAttributes(), QTestXmlStreamer::formatStart(), and QTestLightXmlStreamer::formatStart().
 {
     const QTestElementAttribute *attrb = attribute(index);
     if(attrb)
         return attrb->name();
     return 0;
 }
attributes()
template<class ElementType > QTestElementAttribute * QTestCoreElement< ElementType >::attributes () const
Definition at line 102 of file qtestcoreelement.h.
Referenced by QTestXunitStreamer::outputElements(), and QTestBasicStreamer::outputElements().
 {
     return listOfAttributes;
 }
attributeValue()
template<class ElementType > const char * QTestCoreElement< ElementType >::attributeValue (QTest::AttributeIndex index) const
Definition at line 108 of file qtestcoreelement.h.
Referenced by QTestLightXmlStreamer::formatBeforeAttributes(), QTestXmlStreamer::formatStart(), and QTestLightXmlStreamer::formatStart().
 {
     const QTestElementAttribute *attrb = attribute(index);
     if(attrb)
         return attrb->value();
     return 0;
 }
elementName()
template<class ElementType > const char * QTestCoreElement< ElementType >::elementName () const
Definition at line 128 of file qtestcoreelement.h.
Referenced by QTestXunitStreamer::formatEnd(), and QTestXunitStreamer::formatStart().
 {
     const char *xmlElementNames[] =
     {
         "property",
         "properties",
         "failure",
         "error",
         "testcase",
         "testsuite",
         "benchmark",
         "system-err"
     };
     if(type != QTest::LET_Undefined)
         return xmlElementNames[type];
     return 0;
 }
elementType()
template<class ElementType > QTest::LogElementType QTestCoreElement< ElementType >::elementType () const
Definition at line 149 of file qtestcoreelement.h.
Referenced by QTestElement::addLogElement(), QTestXunitStreamer::formatAfterAttributes(), QTestXunitStreamer::formatAttributes(), QTestLightXmlStreamer::formatBeforeAttributes(), QTestLightXmlStreamer::formatEnd(), QTestXmlStreamer::formatEnd(), QTestXunitStreamer::formatStart(), QTestLightXmlStreamer::formatStart(), QTestXmlStreamer::formatStart(), and QTestXunitStreamer::outputElements().
 {
     return type;
 }
Properties
listOfAttributes
template<class ElementType> QTestElementAttribute* QTestCoreElement< ElementType >::listOfAttributes private
Definition at line 71 of file qtestcoreelement.h.
Referenced by QTestCoreElement< QTestElement >::addAttribute(), QTestCoreElement< QTestElement >::attribute(), QTestCoreElement< QTestElement >::attributes(), and QTestCoreElement< QTestElement >::~QTestCoreElement().
type
template<class ElementType> QTest::LogElementType QTestCoreElement< ElementType >::type private
Definition at line 72 of file qtestcoreelement.h.
Referenced by QTestCoreElement< QTestElement >::elementName(), and QTestCoreElement< QTestElement >::elementType().
The documentation for this class was generated from the following file:
/src/testlib/qtestcoreelement.h