Qt 4.8: QTestElementAttribute Class Reference
QTestElementAttribute Class Reference
#include <qtestelementattribute.h>
Public Functions
QTest::AttributeIndex index () const
bool isNull () const
const char * name () const
QTestElementAttribute ()
bool setPair (QTest::AttributeIndex attributeIndex, const char *value)
const char * value () const
~QTestElementAttribute ()
Public Functions inherited from QTestCoreList< QTestElementAttribute >
void addToList (QTestElementAttribute **list)
int count (QTestElementAttribute *list)
int count ()
QTestElementAttribute * nextElement ()
QTestElementAttribute * previousElement ()
QTestCoreList ()
virtual ~QTestCoreList ()
Properties
QTest::AttributeIndex attributeIndex
char * attributeValue
Detailed Description
Definition at line 90 of file qtestelementattribute.h.
Constructors and Destructors
QTestElementAttribute()
QTestElementAttribute::QTestElementAttribute ()
Definition at line 115 of file qtestelementattribute.cpp.
     :attributeValue(0),
     attributeIndex(QTest::AI_Undefined)
 {
 }
~QTestElementAttribute()
QTestElementAttribute::~QTestElementAttribute ()
Definition at line 121 of file qtestelementattribute.cpp.
 {
     delete[] attributeValue;
 }
Functions
index()
QTest::AttributeIndex QTestElementAttribute::index () const
Definition at line 159 of file qtestelementattribute.cpp.
Referenced by QTestCoreElement< QTestElement >::attribute(), QTestXunitStreamer::formatAttributes(), and setPair().
 {
     return attributeIndex;
 }
isNull()
bool QTestElementAttribute::isNull () const
Definition at line 164 of file qtestelementattribute.cpp.
 {
     return attributeIndex == QTest::AI_Undefined;
 }
name()
const char * QTestElementAttribute::name () const
Definition at line 131 of file qtestelementattribute.cpp.
Referenced by QTestCoreElement< QTestElement >::attributeName(), and QTestXunitStreamer::formatAttributes().
 {
     const char *AttributeNames[] =
     {
         "name",
         "result",
         "tests",
         "failures",
         "errors",
         "type",
         "description",
         "value",
         "qtestversion",
         "qtversion",
         "file",
         "line",
         "metric",
         "tag",
         "value",
         "iterations"
     };
     if(attributeIndex != QTest::AI_Undefined)
         return AttributeNames[attributeIndex];
     return 0;
 }
setPair()
bool QTestElementAttribute::setPair (QTest::AttributeIndex attributeIndex, const char * value)
Definition at line 169 of file qtestelementattribute.cpp.
Referenced by QTestCoreElement< QTestElement >::addAttribute(), and QTestLogger::addIncident().
 {
     if(!value)
         return false;
     delete[] attributeValue;
     attributeIndex = index;
     attributeValue = qstrdup(value);
     return (attributeValue!=0) ? true:false;
 }
value()
const char * QTestElementAttribute::value () const
Definition at line 126 of file qtestelementattribute.cpp.
Referenced by QTestLogger::addIncident(), QTestCoreElement< QTestElement >::attributeValue(), and QTestXunitStreamer::formatAttributes().
 {
     return attributeValue;
 }
Properties
attributeIndex
QTest::AttributeIndex QTestElementAttribute::attributeIndex private
Definition at line 104 of file qtestelementattribute.h.
Referenced by index(), isNull(), name(), and setPair().
attributeValue
char* QTestElementAttribute::attributeValue private
Definition at line 103 of file qtestelementattribute.h.
Referenced by setPair(), value(), and ~QTestElementAttribute().
The documentation for this class was generated from the following files:
/src/testlib/qtestelementattribute.h
/src/testlib/qtestelementattribute.cpp