Qt 4.8: QGraphicsSceneDragDropEvent Class Reference
QGraphicsSceneDragDropEvent Class Reference
The QGraphicsSceneDragDropEvent class provides events for drag and drop in the graphics view framework.
#include <qgraphicssceneevent.h>
Public Functions
void acceptProposedAction ()
Sets the proposed action as accepted, i.e, the drop action is set to the proposed action.
Qt::MouseButtons buttons () const
Returns a Qt::MouseButtons value indicating which buttons were pressed on the mouse when this mouse event was generated.
Qt::DropAction dropAction () const
Returns the action that was performed in this drag and drop.
const QMimeData * mimeData () const
This function returns the MIME data of the event.
Qt::KeyboardModifiers modifiers () const
Returns the keyboard modifiers that were pressed when the drag and drop event was created.
QPointF pos () const
Returns the mouse position of the event relative to the view that sent the event.
Qt::DropActions possibleActions () const
Returns the possible drop actions that the drag and drop can result in.
Qt::DropAction proposedAction () const
Returns the drop action that is proposed, i.e., preferred.
QGraphicsSceneDragDropEvent (Type type=None)
Constructs a new QGraphicsSceneDragDropEvent of the specified type.
QPointF scenePos () const
Returns the position of the mouse in scene coordinates.
QPoint screenPos () const
Returns the position of the mouse relative to the screen.
void setButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that were pressed when the event was created to buttons.
void setDropAction (Qt::DropAction action)
This function lets the receiver of the drop set the drop action that was performed to action, which should be one of the possible actions.
void setMimeData (const QMimeData *data)
This function sets the MIME data for the event.
void setModifiers (Qt::KeyboardModifiers modifiers)
Sets the keyboard modifiers that were pressed when the event was created to modifiers.
void setPos (const QPointF &pos)
Sets the position of the mouse to pos; this should be relative to the widget that generated the event, which normally is a QGraphicsView.
void setPossibleActions (Qt::DropActions actions)
Sets the possible drop actions that the drag can result in to actions.
void setProposedAction (Qt::DropAction action)
Sets the proposed action to action.
void setScenePos (const QPointF &pos)
Sets the scene position of the mouse to pos.
void setScreenPos (const QPoint &pos)
Sets the mouse position relative to the screen to pos.
void setSource (QWidget *source)
This function set the source widget, i.
QWidget * source () const
This function returns the QGraphicsView that created the QGraphicsSceneDragDropEvent.
~QGraphicsSceneDragDropEvent ()
Destroys the object.
Public Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (Type type)
Constructs a generic graphics scene event of the specified type.
void setWidget (QWidget *widget)
Sets the widget related to this event.
QWidget * widget () const
Returns the widget where the event originated, or 0 if the event originates from another application.
~QGraphicsSceneEvent ()
Destroys the event.
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Additional Inherited Members
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Protected Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (QGraphicsSceneEventPrivate &dd, Type type=None)
Constructs a generic graphics scene event.
Protected Variables inherited from QGraphicsSceneEvent
QScopedPointer< QGraphicsSceneEventPrivate > d_ptr
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Detailed Description
The QGraphicsSceneDragDropEvent class provides events for drag and drop in the graphics view framework.
Since
4.2
QGraphicsView inherits the drag and drop functionality provided by QWidget. When it receives a drag and drop event, it translates it to a QGraphicsSceneDragDropEvent.
QGraphicsSceneDragDropEvent stores events of type GraphicsSceneDragEnter, GraphicsSceneDragLeave, GraphicsSceneDragMove, or GraphicsSceneDrop.
QGraphicsSceneDragDropEvent contains the position of the mouse cursor in both item, scene, and screen coordinates; this can be retrieved with pos(), scenePos(), and screenPos().
The scene sends the event to the first QGraphicsItem under the mouse cursor that accepts drops; a graphics item is set to accept drops with QGraphicsItem::setAcceptDrops().
Definition at line 246 of file qgraphicssceneevent.h.
Constructors and Destructors
QGraphicsSceneDragDropEvent()
QGraphicsSceneDragDropEvent::QGraphicsSceneDragDropEvent (Type type = None)
Constructs a new QGraphicsSceneDragDropEvent of the specified type.
Warning
This function is not part of the public interface.
The type can be either QEvent::GraphicsSceneDragEnter, QEvent::GraphicsSceneDragLeave, QEvent::GraphicsSceneDragMove, or QEvent::GraphicsSceneDrop.
Definition at line 1361 of file qgraphicssceneevent.cpp.
     : QGraphicsSceneEvent(*new QGraphicsSceneDragDropEventPrivate, type)
 {
 }
~QGraphicsSceneDragDropEvent()
QGraphicsSceneDragDropEvent::~QGraphicsSceneDragDropEvent ()
Destroys the object.
Definition at line 1369 of file qgraphicssceneevent.cpp.
 {
 }
Functions
acceptProposedAction()
void QGraphicsSceneDragDropEvent::acceptProposedAction ()
Sets the proposed action as accepted, i.e, the drop action is set to the proposed action.
This is equal to:
setDropAction(proposedAction());
When using this function, one should not call accept().
See also
dropAction(), setDropAction(), proposedAction()
Definition at line 1585 of file qgraphicssceneevent.cpp.
Referenced by QTextControl::processEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->dropAction = d->proposedAction;
 }
buttons()
Qt::MouseButtons QGraphicsSceneDragDropEvent::buttons () const
Returns a Qt::MouseButtons value indicating which buttons were pressed on the mouse when this mouse event was generated.
See also
Qt::MouseButtons
Definition at line 1462 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), setButtons(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->buttons;
 }
dropAction()
Qt::DropAction QGraphicsSceneDragDropEvent::dropAction () const
Returns the action that was performed in this drag and drop.
This should be set by the receiver of the drop and is returned by QDrag::exec().
See also
setDropAction(), acceptProposedAction()
Definition at line 1599 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsView::dragEnterEvent(), QGraphicsProxyWidget::dragMoveEvent(), QGraphicsView::dragMoveEvent(), QGraphicsScene::dragMoveEvent(), QGraphicsView::dropEvent(), QTextControl::processEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->dropAction;
 }
mimeData()
const QMimeData * QGraphicsSceneDragDropEvent::mimeData () const
This function returns the MIME data of the event.
Definition at line 1647 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QTextControl::processEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->mimeData;
 }
modifiers()
Qt::KeyboardModifiers QGraphicsSceneDragDropEvent::modifiers () const
Returns the keyboard modifiers that were pressed when the drag and drop event was created.
See also
Qt::KeyboardModifiers
Definition at line 1490 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), setModifiers(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->modifiers;
 }
pos()
QPointF QGraphicsSceneDragDropEvent::pos () const
Returns the mouse position of the event relative to the view that sent the event.
See also
QGraphicsView, screenPos(), scenePos()
Definition at line 1379 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), QGraphicsProxyWidget::dragEnterEvent(), QGraphicsProxyWidget::dropEvent(), QTextControl::processEvent(), setPos(), setScenePos(), and setScreenPos().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->pos;
 }
possibleActions()
Qt::DropActions QGraphicsSceneDragDropEvent::possibleActions () const
Returns the possible drop actions that the drag and drop can result in.
See also
Qt::DropActions
Definition at line 1520 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsProxyWidget::dragMoveEvent(), QGraphicsProxyWidget::dropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->possibleActions;
 }
proposedAction()
Qt::DropAction QGraphicsSceneDragDropEvent::proposedAction () const
Returns the drop action that is proposed, i.e., preferred.
The action must be one of the possible actions as defined by possibleActions().
See also
Qt::DropAction, possibleActions()
Definition at line 1550 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsProxyWidget::dragMoveEvent(), QGraphicsScene::dragMoveEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->proposedAction;
 }
scenePos()
QPointF QGraphicsSceneDragDropEvent::scenePos () const
Returns the position of the mouse in scene coordinates.
See also
pos(), screenPos()
Definition at line 1408 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), QGraphicsScenePrivate::sendDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->scenePos;
 }
screenPos()
QPoint QGraphicsSceneDragDropEvent::screenPos () const
Returns the position of the mouse relative to the screen.
See also
pos(), scenePos()
Definition at line 1434 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), QGraphicsScene::dragMoveEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->screenPos;
 }
setButtons()
void QGraphicsSceneDragDropEvent::setButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that were pressed when the event was created to buttons.
Warning
This function is not part of the public interface.
See also
Qt::MouseButtons, buttons()
Definition at line 1478 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->buttons = buttons;
 }
setDropAction()
void QGraphicsSceneDragDropEvent::setDropAction (Qt::DropAction action)
This function lets the receiver of the drop set the drop action that was performed to action, which should be one of the possible actions.
Call accept() in stead of acceptProposedAction() if you use this function.
See also
dropAction(), accept(), possibleActions()
Definition at line 1614 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsProxyWidget::dragEnterEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsScene::dragMoveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->dropAction = action;
 }
setMimeData()
void QGraphicsSceneDragDropEvent::setMimeData (const QMimeData * data)
This function sets the MIME data for the event.
Warning
This function is not part of the public interface.
Definition at line 1660 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->mimeData = data;
 }
setModifiers()
void QGraphicsSceneDragDropEvent::setModifiers (Qt::KeyboardModifiers modifiers)
Sets the keyboard modifiers that were pressed when the event was created to modifiers.
Warning
This function is not part of the public interface.
See also
Qt::KeyboardModifiers, modifiers()
Definition at line 1507 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->modifiers = modifiers;
 }
setPos()
void QGraphicsSceneDragDropEvent::setPos (const QPointF & pos)
Sets the position of the mouse to pos; this should be relative to the widget that generated the event, which normally is a QGraphicsView.
Warning
This function is not part of the public interface.
See also
pos(), setScenePos(), setScreenPos()
Definition at line 1397 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), and QGraphicsScenePrivate::sendDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->pos = pos;
 }
setPossibleActions()
void QGraphicsSceneDragDropEvent::setPossibleActions (Qt::DropActions actions)
Sets the possible drop actions that the drag can result in to actions.
Warning
This function is not part of the public interface.
See also
Qt::DropActions, possibleActions()
Definition at line 1536 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->possibleActions = actions;
 }
setProposedAction()
void QGraphicsSceneDragDropEvent::setProposedAction (Qt::DropAction action)
Sets the proposed action to action.
Warning
This function is not part of the public interface. The proposed action is a Qt::DropAction that is one of the possible actions as given by possibleActions().
See also
proposedAction(), Qt::DropAction, possibleActions()
Definition at line 1568 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->proposedAction = action;
 }
setScenePos()
void QGraphicsSceneDragDropEvent::setScenePos (const QPointF & pos)
Sets the scene position of the mouse to pos.
Warning
This function is not part of the public interface.
See also
scenePos(), setScreenPos(), setPos()
Definition at line 1423 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->scenePos = pos;
 }
setScreenPos()
void QGraphicsSceneDragDropEvent::setScreenPos (const QPoint & pos)
Sets the mouse position relative to the screen to pos.
Warning
This function is not part of the public interface.
See also
screenPos(), setScenePos(), setPos()
Definition at line 1449 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), cloneEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->screenPos = pos;
 }
setSource()
void QGraphicsSceneDragDropEvent::setSource (QWidget * source)
This function set the source widget, i.
Warning
This function is not part of the public interface. e., the widget that created the drop event, to source.
Definition at line 1638 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QGraphicsView::dragLeaveEvent(), QGraphicsViewPrivate::populateSceneDragDropEvent(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(QGraphicsSceneDragDropEvent);
     d->source = source;
 }
source()
QWidget * QGraphicsSceneDragDropEvent::source () const
This function returns the QGraphicsView that created the QGraphicsSceneDragDropEvent.
Definition at line 1624 of file qgraphicssceneevent.cpp.
Referenced by QGraphicsScenePrivate::cloneDragDropEvent(), QTextControl::processEvent(), setSource(), and QGraphicsViewPrivate::storeDragDropEvent().
 {
     Q_D(const QGraphicsSceneDragDropEvent);
     return d->source;
 }
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicssceneevent.h
/src/gui/graphicsview/qgraphicssceneevent.cpp