Qt 4.8: QRunnable Class Reference
QRunnable Class Reference abstract
The QRunnable class is the base class for all runnable objects.
#include <qrunnable.h>
Public Functions
bool autoDelete () const
Returns true is auto-deletion is enabled; false otherwise.
QRunnable ()
Constructs a QRunnable.
virtual void run ()=0
Implement this pure virtual function in your subclass.
void setAutoDelete (bool _autoDelete)
Enables auto-deletion if autoDelete is true; otherwise auto-deletion is disabled.
virtual ~QRunnable ()
QRunnable virtual destructor.
Properties
int ref
Friends
class QThreadPool
class QThreadPoolPrivate
class QThreadPoolThread
Detailed Description
The QRunnable class is the base class for all runnable objects.
Since
4.4
The QRunnable class is an interface for representing a task or piece of code that needs to be executed, represented by your reimplementation of the run() function.
You can use QThreadPool to execute your code in a separate thread. QThreadPool deletes the QRunnable automatically if autoDelete() returns true (the default). Use setAutoDelete() to change the auto-deletion flag.
QThreadPool supports executing the same QRunnable more than once by calling QThreadPool::tryStart(this) from within the run() function. If autoDelete is enabled the QRunnable will be deleted when the last thread exits the run function. Calling QThreadPool::start() multiple times with the same QRunnable when autoDelete is enabled creates a race condition and is not recommended.
See also
QThreadPool
Definition at line 52 of file qrunnable.h.
Constructors and Destructors
QRunnable()
QRunnable::QRunnable () inline
Constructs a QRunnable.
Auto-deletion is enabled by default.
See also
autoDelete(), setAutoDelete()
Definition at line 63 of file qrunnable.h.
 : ref(0) { }
~QRunnable()
QRunnable::~QRunnable () inline virtual
QRunnable virtual destructor.
Definition at line 64 of file qrunnable.h.
 { }
Functions
autoDelete()
bool QRunnable::autoDelete () const inline
Returns true is auto-deletion is enabled; false otherwise.
If auto-deletion is enabled, QThreadPool will automatically delete this runnable after calling run(); otherwise, ownership remains with the application programmer.
See also
setAutoDelete(), QThreadPool
Definition at line 66 of file qrunnable.h.
Referenced by QThreadPoolPrivate::enqueueTask(), QThreadPoolThread::run(), QThreadPoolPrivate::startFrontRunnable(), QThreadPoolPrivate::startThread(), QThreadPoolPrivate::stealRunnable(), and QThreadPoolPrivate::tryStart().
 { return ref != -1; }
run()
QRunnable::run () pure virtual
Implement this pure virtual function in your subclass.
Implemented in QHostInfoRunnable.
Referenced by QThreadPoolThread::run(), QThreadPoolPrivate::startFrontRunnable(), and QThreadPoolPrivate::stealRunnable().
setAutoDelete()
bool QRunnable::setAutoDelete (bool autoDelete) inline
Enables auto-deletion if autoDelete is true; otherwise auto-deletion is disabled.
If auto-deletion is enabled, QThreadPool will automatically delete this runnable after calling run(); otherwise, ownership remains with the application programmer.
Note that this flag must be set before calling QThreadPool::start(). Calling this function after QThreadPool::start() results in undefined behavior.
See also
autoDelete(), QThreadPool
Definition at line 67 of file qrunnable.h.
Referenced by QHostInfoRunnable::QHostInfoRunnable().
 { ref = _autoDelete ? 0 : -1; }
Friends and Related Functions
QThreadPool
friend class QThreadPool friend
Definition at line 56 of file qrunnable.h.
QThreadPoolPrivate
friend class QThreadPoolPrivate friend
Definition at line 57 of file qrunnable.h.
QThreadPoolThread
friend class QThreadPoolThread friend
Definition at line 58 of file qrunnable.h.
Properties
ref
int QRunnable::ref private
Definition at line 54 of file qrunnable.h.
Referenced by QThreadPoolPrivate::enqueueTask(), QThreadPoolThread::run(), QThreadPoolPrivate::startFrontRunnable(), QThreadPoolPrivate::startThread(), QThreadPoolPrivate::stealRunnable(), and QThreadPoolPrivate::tryStart().
The documentation for this class was generated from the following files:
/src/corelib/concurrent/qrunnable.h
/src/corelib/concurrent/qrunnable.cpp