Qt 4.8: QPatternist::Integer Class Reference
QPatternist::Integer Class Reference
Implements the value instance of the xs:integer type.
#include <qinteger_p.h>
Public Types
typedef Numeric::Ptr Ptr
Public Types inherited from QPatternist::Numeric
typedef QExplicitlySharedDataPointer< Numeric > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual Numeric::Ptr abs () const
virtual Numeric::Ptr ceiling () const
bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual Numeric::Ptr floor () const
virtual bool isInf () const
virtual bool isNaN () const
virtual bool isSigned () const
Returns always true.
virtual Numeric::Ptr round () const
virtual Numeric::Ptr roundHalfToEven (const xsInteger scale) const
virtual QString stringValue () const
virtual xsDecimal toDecimal () const
virtual xsDouble toDouble () const
virtual xsFloat toFloat () const
virtual xsInteger toInteger () const
virtual Item toNegated () const
virtual qulonglong toUnsignedInteger () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr fromLexical (const QString &strNumeric)
static Item fromValue (const xsInteger num)
Static Public Functions inherited from QPatternist::Numeric
static AtomicValue::Ptr fromLexical (const QString &number)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
Integer (const xsInteger num)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Properties
const xsInteger m_value
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::Numeric
static xsDouble roundFloat (const xsDouble val)
Implements fn:round() for types implemented with floating point.
Detailed Description
Implements the value instance of the xs:integer type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 70 of file qinteger_p.h.
Typedefs
Ptr
typedef Numeric::Ptr QPatternist::Integer::Ptr
Definition at line 74 of file qinteger_p.h.
Constructors and Destructors
Integer()
Integer::Integer (const xsInteger num) protected
Definition at line 68 of file qinteger.cpp.
Referenced by abs(), fromLexical(), and fromValue().
                                     : m_value(num)
 {
 }
Functions
abs()
Numeric::Ptr Integer::abs () const virtual
Performs the algorithm specified for the function fn:abs on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.1 fn:abs
Implements QPatternist::Numeric.
Definition at line 128 of file qinteger.cpp.
 {
     /* No reason to allocate an Integer if we're already absolute. */
     if(m_value < 0)
         return Numeric::Ptr(new Integer(qAbs(m_value)));
     else
         return Numeric::Ptr(const_cast<Integer *>(this));
 }
ceiling()
Numeric::Ptr Integer::ceiling () const virtual
Performs the algorithm specified for the function fn:ceiling on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.2 fn:ceiling
Implements QPatternist::Numeric.
Definition at line 123 of file qinteger.cpp.
 {
     return Numeric::Ptr(const_cast<Integer *>(this));
 }
evaluateEBV()
bool Integer::evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const virtual
Determines the Effective Boolean Value of this number.
Returns
false if the number is 0, otherwise true.
Reimplemented from QPatternist::AtomicValue.
Definition at line 72 of file qinteger.cpp.
 {
     return m_value != 0;
 }
floor()
Numeric::Ptr Integer::floor () const virtual
Performs the algorithm specified for the function fn:floor on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.3 fn:floor
Implements QPatternist::Numeric.
Definition at line 118 of file qinteger.cpp.
 {
     return Numeric::Ptr(const_cast<Integer *>(this));
 }
fromLexical()
AtomicValue::Ptr Integer::fromLexical (const QString & strNumeric) static
Constructs an instance from the lexical representation strNumeric.
Definition at line 57 of file qinteger.cpp.
Referenced by QPatternist::StringToIntegerCaster::castFrom(), and QPatternist::Numeric::fromLexical().
 {
     bool conversionOk = false;
     const xsInteger num = strNumeric.toLongLong(&conversionOk);
     if(conversionOk)
         return AtomicValue::Ptr(new Integer(num));
     else
         return ValidationError::createError();
 }
fromValue()
Item Integer::fromValue (const xsInteger num) static
Definition at line 52 of file qinteger.cpp.
Referenced by QPatternist::DerivedInteger< DerivedType >::abs(), QPatternist::DecimalMathematician::calculate(), QPatternist::IntegerMathematician::calculate(), QPatternist::NumericToDecimalCaster< IsInteger >::castFrom(), QPatternist::DerivedInteger< DerivedType >::ceiling(), QPatternist::CountFN::compress(), QPatternist::PositionalVariableReference::evaluateSingleton(), QPatternist::PositionFN::evaluateSingleton(), QPatternist::CountFN::evaluateSingleton(), QPatternist::LastFN::evaluateSingleton(), QPatternist::AvgFN::evaluateSingleton(), QPatternist::StringLengthFN::evaluateSingleton(), QPatternist::DerivedInteger< DerivedType >::floor(), QPatternist::ToCodepointsIterator::next(), QPatternist::IndexOfIterator::next(), QPatternist::RangeIterator::next(), QPatternist::DerivedInteger< DerivedType >::round(), QPatternist::DerivedInteger< DerivedType >::roundHalfToEven(), toNegated(), QPatternist::DerivedInteger< DerivedType >::toNegated(), and QPatternist::AtomicValue::toXDM().
 {
     return toItem(Integer::Ptr(new Integer(num)));
 }
isInf()
bool Integer::isInf () const virtual
Returns
always false, xs:integer doesn't have infinity in its value space.
Implements QPatternist::Numeric.
Definition at line 142 of file qinteger.cpp.
 {
     return false;
 }
isNaN()
bool Integer::isNaN () const virtual
Returns
always false, xs:integer doesn't have not-a-number in its value space.
Implements QPatternist::Numeric.
Definition at line 137 of file qinteger.cpp.
 {
     return false;
 }
isSigned()
bool Integer::isSigned () const virtual
Returns always true.
Implements QPatternist::Numeric.
Definition at line 152 of file qinteger.cpp.
 {
     return true;
 }
round()
Numeric::Ptr Integer::round () const virtual
Performs the algorithm specified for the function fn:round on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.4 fn:round
Implements QPatternist::Numeric.
Definition at line 107 of file qinteger.cpp.
 {
     /* xs:integerS never has a mantissa. */
     return Numeric::Ptr(const_cast<Integer *>(this));
 }
roundHalfToEven()
Numeric::Ptr Integer::roundHalfToEven (const xsInteger scale) const virtual
Performs rounding as defined for the fn:round-half-to-even on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.5 fn:round-half-to-even
Implements QPatternist::Numeric.
Definition at line 113 of file qinteger.cpp.
 {
     return Numeric::Ptr(const_cast<Integer *>(this));
 }
stringValue()
QString Integer::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 77 of file qinteger.cpp.
 {
     return QString::number(m_value);
 }
toDecimal()
xsDecimal Integer::toDecimal () const virtual
Returns
the particular number's value as a native representation of the type xs:decimal. This can be considered that the value is cast to xs:decimal.
Implements QPatternist::Numeric.
Definition at line 102 of file qinteger.cpp.
 {
     return static_cast<xsDecimal>(m_value);
 }
toDouble()
xsDouble Integer::toDouble () const virtual
Returns
the particular number's value as a native representation of the type xs:double. This can be considered that the value is cast to xs:double.
Implements QPatternist::Numeric.
Definition at line 87 of file qinteger.cpp.
 {
     return static_cast<xsDouble>(m_value);
 }
toFloat()
xsFloat Integer::toFloat () const virtual
Returns
the particular number's value as a native representation of the type xs:float. This can be considered that the value is cast to xs:float.
Implements QPatternist::Numeric.
Definition at line 97 of file qinteger.cpp.
 {
     return static_cast<xsFloat>(m_value);
 }
toInteger()
xsInteger Integer::toInteger () const virtual
Returns
the particular number's value as a native representation of the type xs:integer. This can be considered that the value is cast to xs:integer.
Implements QPatternist::Numeric.
Definition at line 92 of file qinteger.cpp.
 {
     return m_value;
 }
toNegated()
Item Integer::toNegated () const virtual
Unary minus.
Implements QPatternist::Numeric.
Definition at line 147 of file qinteger.cpp.
 {
     return fromValue(-m_value);
 }
toUnsignedInteger()
qulonglong Integer::toUnsignedInteger () const virtual
Returns
the number as an unsigned integer. If the value is not unsigned, the code asserts and behavior is undefined.
Implements QPatternist::Numeric.
Definition at line 157 of file qinteger.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "It makes no sense to call this function, see Numeric::toUnsignedInteger().");
     return 0;
 }
type()
ItemType::Ptr Integer::type () const virtual
Returns
always BuiltinTypes::xsInteger
Implements QPatternist::AtomicValue.
Definition at line 82 of file qinteger.cpp.
 {
     return BuiltinTypes::xsInteger;
 }
Properties
m_value
const xsInteger QPatternist::Integer::m_value private
Definition at line 133 of file qinteger_p.h.
Referenced by abs(), evaluateEBV(), stringValue(), toDecimal(), toDouble(), toFloat(), toInteger(), and toNegated().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qinteger_p.h
/src/xmlpatterns/data/qinteger.cpp