Qt 4.8: QPrinterInfo Class Reference
QPrinterInfo Class Reference
The QPrinterInfo class gives access to information about existing printers.
#include <qprinterinfo.h>
Public Functions
bool isDefault () const
Returns whether this printer is the default printer.
bool isNull () const
Returns whether this QPrinterInfo object holds a printer definition.
QPrinterInfo & operator= (const QPrinterInfo &other)
Sets the QPrinterInfo object to be equal to other.
QString printerName () const
Returns the name of the printer.
QPrinterInfo ()
Constructs an empty QPrinterInfo object.
QPrinterInfo (const QPrinterInfo &other)
Constructs a copy of other.
QPrinterInfo (const QPrinter &printer)
Constructs a QPrinterInfo object from printer.
QList< QPrinter::PaperSize > supportedPaperSizes () const
Returns a list of supported paper sizes by the printer.
~QPrinterInfo ()
Destroys the QPrinterInfo object.
Static Public Functions
static QList< QPrinterInfo > availablePrinters ()
Returns a list of available printers on the system.
static QPrinterInfo defaultPrinter ()
Returns the default printer on the system.
Private Functions
QPrinterInfo (const QString &name)
Properties
QScopedPointer< QPrinterInfoPrivate, QPrinterInfoPrivateDeleter > d_ptr
Detailed Description
The QPrinterInfo class gives access to information about existing printers.
Use the static functions to generate a list of QPrinterInfo objects. Each QPrinterInfo object in the list represents a single printer and can be queried for name, supported paper sizes, and whether or not it is the default printer.
Since
4.4
Definition at line 58 of file qprinterinfo.h.
Constructors and Destructors
QPrinterInfo() [1/4]
QPrinterInfo::QPrinterInfo ()
Constructs an empty QPrinterInfo object.
See also
isNull()
Definition at line 85 of file qprinterinfo.cpp.
     : d_ptr(&QPrinterInfoPrivate::shared_null)
 {
 }
QPrinterInfo() [2/4]
QPrinterInfo::QPrinterInfo (const QPrinterInfo & other)
Constructs a copy of other.
Since
4.8
Definition at line 98 of file qprinterinfo.cpp.
     : d_ptr(new QPrinterInfoPrivate(*other.d_ptr))
 {
 }
QPrinterInfo() [3/4]
QPrinterInfo::QPrinterInfo (const QPrinter & printer)
Constructs a QPrinterInfo object from printer.
Definition at line 106 of file qprinterinfo.cpp.
     : d_ptr(&QPrinterInfoPrivate::shared_null)
 {
     foreach (const QPrinterInfo &printerInfo, availablePrinters()) {
         if (printerInfo.printerName() == printer.printerName()) {
             d_ptr.reset(new QPrinterInfoPrivate(*printerInfo.d_ptr));
             break;
         }
     }
 }
~QPrinterInfo()
QPrinterInfo::~QPrinterInfo ()
Destroys the QPrinterInfo object.
References to the values in the object become invalid.
Definition at line 129 of file qprinterinfo.cpp.
 {
 }
QPrinterInfo() [4/4]
QPrinterInfo::QPrinterInfo (const QString & name) private
Warning
This function is not part of the public interface.
Definition at line 120 of file qprinterinfo.cpp.
     : d_ptr(new QPrinterInfoPrivate(name))
 {
 }
Functions
availablePrinters()
QList< QPrinterInfo > QPrinterInfo::availablePrinters () static
Returns a list of available printers on the system.
Definition at line 53 of file qprinterinfo_mac.cpp.
Referenced by defaultPrinter(), QPrinter::QPrinter(), QPrinterInfo(), qt_getLprPrinters(), and QPrinter::setPrinterName().
 {
     QList<QPrinterInfo> printers;
     QCFType<CFArrayRef> array;
     if (PMServerCreatePrinterList(kPMServerLocal, &array) == noErr) {
         CFIndex count = CFArrayGetCount(array);
         for (int i = 0; i < count; ++i) {
             PMPrinter printer = static_cast<PMPrinter>(const_cast<void *>(CFArrayGetValueAtIndex(array, i)));
             QString printerName = QCFString::toQString(PMPrinterGetName(printer));
             QPrinterInfo printerInfo(printerName);
             if (PMPrinterIsDefault(printer))
                 printerInfo.d_ptr->isDefault = true;
             printers.append(printerInfo);
         }
     }
     return printers;
 }
defaultPrinter()
QPrinterInfo QPrinterInfo::defaultPrinter () static
Returns the default printer on the system.
The return value should be checked using isNull() before being used, in case there is no default printer.
See also
isNull()
Definition at line 74 of file qprinterinfo_mac.cpp.
Referenced by QPdfBaseEnginePrivate::closePrintDevice(), QPrinter::QPrinter(), and qt_getLprPrinters().
 {
     QList<QPrinterInfo> printers = availablePrinters();
     foreach (const QPrinterInfo &printerInfo, printers) {
         if (printerInfo.isDefault())
             return printerInfo;
     }
     return printers.value(0);
 }
isDefault()
bool QPrinterInfo::isDefault () const
Returns whether this printer is the default printer.
Definition at line 174 of file qprinterinfo.cpp.
Referenced by defaultPrinter(), and qt_getLprPrinters().
 {
     const Q_D(QPrinterInfo);
     return d->isDefault;
 }
isNull()
bool QPrinterInfo::isNull () const
Returns whether this QPrinterInfo object holds a printer definition.
An empty QPrinterInfo object could result for example from calling defaultPrinter() when there are no printers on the system.
Definition at line 165 of file qprinterinfo.cpp.
Referenced by QPdfBaseEnginePrivate::closePrintDevice(), QPrinter::QPrinter(), and supportedPaperSizes().
 {
     const Q_D(QPrinterInfo);
     return d == &QPrinterInfoPrivate::shared_null;
 }
operator=()
QPrinterInfo & QPrinterInfo::operator= (const QPrinterInfo & other)
Sets the QPrinterInfo object to be equal to other.
Since
4.8
Definition at line 141 of file qprinterinfo.cpp.
 {
     Q_ASSERT(d_ptr);
     d_ptr.reset(new QPrinterInfoPrivate(*other.d_ptr));
     return *this;
 }
printerName()
QString QPrinterInfo::printerName () const
Returns the name of the printer.
See also
QPrinter::setPrinterName()
Definition at line 153 of file qprinterinfo.cpp.
Referenced by availablePrinters(), QPdfBaseEnginePrivate::closePrintDevice(), QPrinter::QPrinter(), and QPrinterInfo().
 {
     const Q_D(QPrinterInfo);
     return d->name;
 }
supportedPaperSizes()
QList< QPrinter::PaperSize > QPrinterInfo::supportedPaperSizes () const
Returns a list of supported paper sizes by the printer.
Since
4.4
Not all printer drivers support this query, so the list may be empty. On Mac OS X 10.3, this function always returns an empty list.
Definition at line 85 of file qprinterinfo_mac.cpp.
Referenced by qt_getLprPrinters().
 {
     const Q_D(QPrinterInfo);
     QList<QPrinter::PaperSize> paperSizes;
     if (isNull())
         return paperSizes;
     PMPrinter cfPrn = PMPrinterCreateFromPrinterID(QCFString::toCFStringRef(d->name));
     if (!cfPrn)
         return paperSizes;
     CFArrayRef array;
     if (PMPrinterGetPaperList(cfPrn, &array) != noErr) {
         PMRelease(cfPrn);
         return paperSizes;
     }
     int count = CFArrayGetCount(array);
     for (int i = 0; i < count; ++i) {
         PMPaper paper = static_cast<PMPaper>(const_cast<void *>(CFArrayGetValueAtIndex(array, i)));
         double width, height;
         if (PMPaperGetWidth(paper, &width) == noErr && PMPaperGetHeight(paper, &height) == noErr) {
             QSizeF size(width * 0.3527, height * 0.3527);
             paperSizes.append(qSizeFTopaperSize(size));
         }
     }
     PMRelease(cfPrn);
     return paperSizes;
 }
Properties
d_ptr
QScopedPointer<QPrinterInfoPrivate, QPrinterInfoPrivateDeleter> QPrinterInfo::d_ptr private
Definition at line 81 of file qprinterinfo.h.
Referenced by availablePrinters(), operator=(), QPrinterInfo(), and qt_getLprPrinters().
The documentation for this class was generated from the following files:
/src/gui/painting/qprinterinfo.h
/src/gui/painting/qprinterinfo.cpp
/src/gui/painting/qprinterinfo_mac.cpp
/src/gui/painting/qprinterinfo_unix.cpp
/src/gui/painting/qprinterinfo_win.cpp