Qt 4.8: QAbstractTransitionPrivate Class Reference
QAbstractTransitionPrivate Class Reference
#include <qabstracttransition_p.h>
Public Functions
bool callEventTest (QEvent *e)
virtual void callOnTransition (QEvent *e)
void emitTriggered ()
QStateMachine * machine () const
QAbstractTransitionPrivate ()
QState * sourceState () const
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QAbstractTransitionPrivate * get (QAbstractTransition *q)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QList< QAbstractAnimation * > animations
QList< QWeakPointer< QAbstractState > > targetStates
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 68 of file qabstracttransition_p.h.
Constructors and Destructors
QAbstractTransitionPrivate()
QAbstractTransitionPrivate::QAbstractTransitionPrivate ()
Definition at line 123 of file qabstracttransition.cpp.
 {
 }
Functions
callEventTest()
bool QAbstractTransitionPrivate::callEventTest (QEvent * e)
Definition at line 140 of file qabstracttransition.cpp.
Referenced by QKeyEventTransition::eventTest(), and QMouseEventTransition::eventTest().
 {
     Q_Q(QAbstractTransition);
     return q->eventTest(e);
 }
callOnTransition()
void QAbstractTransitionPrivate::callOnTransition (QEvent * e) virtual
Reimplemented in QSignalTransitionPrivate.
Definition at line 146 of file qabstracttransition.cpp.
Referenced by QStateMachinePrivate::executeTransitionContent().
 {
     Q_Q(QAbstractTransition);
     q->onTransition(e);
 }
emitTriggered()
void QAbstractTransitionPrivate::emitTriggered ()
Definition at line 157 of file qabstracttransition.cpp.
Referenced by QStateMachinePrivate::executeTransitionContent().
 {
     Q_Q(QAbstractTransition);
     emit q->triggered();
 }
get()
QAbstractTransitionPrivate * QAbstractTransitionPrivate::get (QAbstractTransition * q) static
Definition at line 127 of file qabstracttransition.cpp.
Referenced by QState::addTransition(), QKeyEventTransition::eventTest(), QMouseEventTransition::eventTest(), QStateMachinePrivate::executeTransitionContent(), and QStateMachinePrivate::selectTransitions().
 {
     return q->d_func();
 }
machine()
QStateMachine * QAbstractTransitionPrivate::machine () const
Definition at line 132 of file qabstracttransition.cpp.
Referenced by QEventTransitionPrivate::maybeRegister(), QSignalTransitionPrivate::maybeRegister(), QSignalTransitionPrivate::unregister(), and QEventTransitionPrivate::unregister().
 {
     QState *source = sourceState();
     if (!source)
         return 0;
     return source->machine();
 }
sourceState()
QState * QAbstractTransitionPrivate::sourceState () const
Definition at line 152 of file qabstracttransition.cpp.
Referenced by machine(), QSignalTransitionPrivate::maybeRegister(), and QEventTransitionPrivate::maybeRegister().
 {
     return qobject_cast<QState*>(parent);
 }
Properties
animations
QList<QAbstractAnimation*> QAbstractTransitionPrivate::animations
Definition at line 86 of file qabstracttransition_p.h.
targetStates
QList<QWeakPointer<QAbstractState> > QAbstractTransitionPrivate::targetStates
Definition at line 83 of file qabstracttransition_p.h.
Referenced by QState::addTransition().
The documentation for this class was generated from the following files:
/src/corelib/statemachine/qabstracttransition_p.h
/src/corelib/statemachine/qabstracttransition.cpp