Qt 4.8: QMessageBoxPrivate Class Reference
QMessageBoxPrivate Class Reference
Public Functions
void _q_buttonClicked (QAbstractButton *)
QAbstractButton * abstractButtonForId (int id) const
void addOldButtons (int button0, int button1, int button2)
void detectEscapeButton ()
int execReturnCode (QAbstractButton *button)
QAbstractButton * findButton (int button0, int button1, int button2, int flags)
void hideSpecial ()
Hides special buttons which are rather shown in the title bar on WinCE, to conserve screen space.
void init (const QString &title=QString(), const QString &text=QString())
int layoutMinimumWidth ()
QMessageBoxPrivate ()
void retranslateStrings ()
void updateSize ()
Public Functions inherited from QDialogPrivate
void hideDefault ()
Hides the default button indicator.
virtual void mac_nativeDialogModalHelp ()
QDialogPrivate ()
void resetModalitySetByOpen ()
void setDefault (QPushButton *)
This function is called by the push button pushButton when it becomes the default button.
void setMainDefault (QPushButton *)
This function sets the default default push button to pushButton.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QMessageBox::StandardButton showNewMessageBox (QWidget *parent, QMessageBox::Icon icon, const QString &title, const QString &text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
static int showOldMessageBox (QWidget *parent, QMessageBox::Icon icon, const QString &title, const QString &text, int button0, int button1, int button2)
static int showOldMessageBox (QWidget *parent, QMessageBox::Icon icon, const QString &title, const QString &text, const QString &button0Text, const QString &button1Text, const QString &button2Text, int defaultButtonNumber, int escapeButtonNumber)
static QPixmap standardIcon (QMessageBox::Icon icon, QMessageBox *mb)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool autoAddOkButton
QDialogButtonBox * buttonBox
QAbstractButton * clickedButton
bool compatMode
QList< QAbstractButton * > customButtonList
QPushButton * defaultButton
DetailButton * detailsButton
QMessageBoxDetailsText * detailsText
QAbstractButton * detectedEscapeButton
QAbstractButton * escapeButton
QMessageBox::Icon icon
QLabel * iconLabel
QLabel * informativeLabel
QLabel * label
QByteArray memberToDisconnectOnClose
QPointer< QObject > receiverToDisconnectOnClose
QByteArray signalToDisconnectOnClose
Public Variables inherited from QDialogPrivate
bool doShowExtension
QPointer< QEventLoop > eventLoop
QWidget * extension
QPoint lastRMBPress
QPointer< QPushButton > mainDef
QSize max
QSize min
Qt::Orientation orientation
int rescode
int resetModalityTo
QSizeGrip * resizer
QSize size
bool sizeGripEnabled
bool wasModalitySet
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 163 of file qmessagebox.cpp.
Constructors and Destructors
QMessageBoxPrivate()
QMessageBoxPrivate::QMessageBoxPrivate () inline
Definition at line 168 of file qmessagebox.cpp.
                          : escapeButton(0), defaultButton(0), clickedButton(0), detailsButton(0),
 #ifndef QT_NO_TEXTEDIT
                            detailsText(0),
 #endif
                            compatMode(false), autoAddOkButton(true),
                            detectedEscapeButton(0), informativeLabel(0) { }
Functions
_q_buttonClicked()
void QMessageBoxPrivate::_q_buttonClicked (QAbstractButton * button)
Definition at line 473 of file qmessagebox.cpp.
 {
     Q_Q(QMessageBox);
 #ifndef QT_NO_TEXTEDIT
     if (detailsButton && detailsText && button == detailsButton) {
         detailsButton->setLabel(detailsText->isHidden() ? HideLabel : ShowLabel);
         detailsText->setHidden(!detailsText->isHidden());
         updateSize();
     } else
 #endif
     {
         clickedButton = button;
         q->done(execReturnCode(button)); // does not trigger closeEvent
         emit q->buttonClicked(button);
         if (receiverToDisconnectOnClose) {
             QObject::disconnect(q, signalToDisconnectOnClose, receiverToDisconnectOnClose,
                                 memberToDisconnectOnClose);
             receiverToDisconnectOnClose = 0;
         }
         signalToDisconnectOnClose.clear();
         memberToDisconnectOnClose.clear();
     }
 }
abstractButtonForId()
QAbstractButton * QMessageBoxPrivate::abstractButtonForId (int id) const
Definition at line 1985 of file qmessagebox.cpp.
 {
     Q_Q(const QMessageBox);
     QAbstractButton *result = customButtonList.value(id);
     if (result)
         return result;
     if (id & QMessageBox::FlagMask)    // for compatibility with Qt 4.0/4.1 (even if it is silly)
         return 0;
     return q->button(newButton(id));
 }
addOldButtons()
void QMessageBoxPrivate::addOldButtons (int button0, int button1, int button2)
Definition at line 1973 of file qmessagebox.cpp.
 {
     Q_Q(QMessageBox);
     q->addButton(newButton(button0));
     q->addButton(newButton(button1));
     q->addButton(newButton(button2));
     q->setDefaultButton(
         static_cast<QPushButton *>(findButton(button0, button1, button2, QMessageBox::Default)));
     q->setEscapeButton(findButton(button0, button1, button2, QMessageBox::Escape));
     compatMode = detectedCompat(button0, button1, button2);
 }
detectEscapeButton()
void QMessageBoxPrivate::detectEscapeButton ()
Definition at line 1034 of file qmessagebox.cpp.
 {
     if (escapeButton) { // escape button explicitly set
         detectedEscapeButton = escapeButton;
         return;
     }
     // Cancel button automatically becomes escape button
     detectedEscapeButton = buttonBox->button(QDialogButtonBox::Cancel);
     if (detectedEscapeButton)
         return;
     // If there is only one button, make it the escape button
     const QList<QAbstractButton *> buttons = buttonBox->buttons();
     if (buttons.count() == 1) {
         detectedEscapeButton = buttons.first();
         return;
     }
     // if the message box has one RejectRole button, make it the escape button
     for (int i = 0; i < buttons.count(); i++) {
         if (buttonBox->buttonRole(buttons.at(i)) == QDialogButtonBox::RejectRole) {
             if (detectedEscapeButton) { // already detected!
                 detectedEscapeButton = 0;
                 break;
             }
             detectedEscapeButton = buttons.at(i);
         }
     }
     if (detectedEscapeButton)
         return;
     // if the message box has one NoRole button, make it the escape button
     for (int i = 0; i < buttons.count(); i++) {
         if (buttonBox->buttonRole(buttons.at(i)) == QDialogButtonBox::NoRole) {
             if (detectedEscapeButton) { // already detected!
                 detectedEscapeButton = 0;
                 break;
             }
             detectedEscapeButton = buttons.at(i);
         }
     }
 }
execReturnCode()
int QMessageBoxPrivate::execReturnCode (QAbstractButton * button)
Definition at line 462 of file qmessagebox.cpp.
 {
     int ret = buttonBox->standardButton(button);
     if (ret == QMessageBox::NoButton) {
         ret = customButtonList.indexOf(button); // if button == 0, correctly sets ret = -1
     } else if (compatMode) {
         ret = oldButton(ret);
     }
     return ret;
 }
findButton()
QAbstractButton * QMessageBoxPrivate::findButton (int button0, int button1, int button2, int flags)
Definition at line 1958 of file qmessagebox.cpp.
 {
     Q_Q(QMessageBox);
     int button = 0;
     if (button0 & flags) {
         button = button0;
     } else if (button1 & flags) {
         button = button1;
     } else if (button2 & flags) {
         button = button2;
     }
     return q->button(newButton(button));
 }
hideSpecial()
void QMessageBoxPrivate::hideSpecial ()
Hides special buttons which are rather shown in the title bar on WinCE, to conserve screen space.
Warning
This function is not part of the public interface.
Definition at line 422 of file qmessagebox.cpp.
 {
     Q_Q(QMessageBox);
     QList<QPushButton*> list = q->findChildren<QPushButton*>();
         for (int i=0; i<list.size(); ++i) {
             QPushButton *pb = list.at(i);
             QString text = pb->text();
             text.remove(QChar::fromLatin1('&'));
             if (text == QApplication::translate("QMessageBox", "OK" ))
                 pb->setFixedSize(0,0);
         }
 }
init()
void QMessageBoxPrivate::init (const QString & title = QString(), const QString & text = QString())
Definition at line 234 of file qmessagebox.cpp.
 {
     Q_Q(QMessageBox);
     label = new QLabel;
     label->setObjectName(QLatin1String("qt_msgbox_label"));
     label->setTextInteractionFlags(Qt::TextInteractionFlags(q->style()->styleHint(QStyle::SH_MessageBox_TextInteractionFlags, 0, q)));
     label->setAlignment(Qt::AlignVCenter | Qt::AlignLeft);
     label->setOpenExternalLinks(true);
 #if defined(Q_WS_MAC)
     label->setContentsMargins(16, 0, 0, 0);
 #elif !defined(Q_WS_QWS)
     label->setContentsMargins(2, 0, 0, 0);
     label->setIndent(9);
 #endif
     icon = QMessageBox::NoIcon;
     iconLabel = new QLabel;
     iconLabel->setObjectName(QLatin1String("qt_msgboxex_icon_label"));
     iconLabel->setSizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
     buttonBox = new QDialogButtonBox;
     buttonBox->setObjectName(QLatin1String("qt_msgbox_buttonbox"));
     buttonBox->setCenterButtons(q->style()->styleHint(QStyle::SH_MessageBox_CenterButtons, 0, q));
     QObject::connect(buttonBox, SIGNAL(clicked(QAbstractButton*)),
                      q, SLOT(_q_buttonClicked(QAbstractButton*)));
     QGridLayout *grid = new QGridLayout;
 #ifndef Q_WS_MAC
 #ifdef Q_WS_S60
     const int preferredIconColumn = (QApplication::layoutDirection() == Qt::LeftToRight) ? 1 : 0;
     const int preferredTextColumn = (QApplication::layoutDirection() == Qt::LeftToRight) ? 0 : 1;
 #else
     const int preferredIconColumn = 0;
     const int preferredTextColumn = 1;
 #endif
     grid->addWidget(iconLabel, 0, preferredIconColumn, 2, 1, Qt::AlignTop);
     grid->addWidget(label, 0, preferredTextColumn, 1, 1);
     // -- leave space for information label --
     grid->addWidget(buttonBox, 2, 0, 1, 2);
 #else
     grid->setMargin(0);
     grid->setVerticalSpacing(8);
     grid->setHorizontalSpacing(0);
     q->setContentsMargins(24, 15, 24, 20);
     grid->addWidget(iconLabel, 0, 0, 2, 1, Qt::AlignTop | Qt::AlignLeft);
     grid->addWidget(label, 0, 1, 1, 1);
     // -- leave space for information label --
     grid->setRowStretch(1, 100);
     grid->setRowMinimumHeight(2, 6);
     grid->addWidget(buttonBox, 3, 1, 1, 1);
 #endif
     grid->setSizeConstraint(QLayout::SetNoConstraint);
     q->setLayout(grid);
     if (!title.isEmpty() || !text.isEmpty()) {
         q->setWindowTitle(title);
         q->setText(text);
     }
     q->setModal(true);
 #ifdef Q_WS_MAC
     QFont f = q->font();
     f.setBold(true);
     label->setFont(f);
 #endif
     retranslateStrings();
 }
layoutMinimumWidth()
int QMessageBoxPrivate::layoutMinimumWidth ()
Definition at line 303 of file qmessagebox.cpp.
 {
     layout->activate();
     return layout->totalMinimumSize().width();
 }
retranslateStrings()
void QMessageBoxPrivate::retranslateStrings ()
Definition at line 2030 of file qmessagebox.cpp.
 {
 #ifndef QT_NO_TEXTEDIT
     if (detailsButton)
         detailsButton->setLabel(detailsText->isHidden() ? ShowLabel : HideLabel);
 #endif
 }
showNewMessageBox()
static QMessageBox::StandardButton QMessageBoxPrivate::showNewMessageBox (QWidget * parent, QMessageBox::Icon icon, const QString & title, const QString & text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton) static
showOldMessageBox() [1/2]
int QMessageBoxPrivate::showOldMessageBox (QWidget * parent, QMessageBox::Icon icon, const QString & title, const QString & text, int button0, int button1, int button2) static
Definition at line 1996 of file qmessagebox.cpp.
Referenced by QMessageBox::critical(), QMessageBox::information(), QMessageBox::question(), showNewMessageBox(), and QMessageBox::warning().
 {
     QMessageBox messageBox(icon, title, text, QMessageBox::NoButton, parent);
     messageBox.d_func()->addOldButtons(button0, button1, button2);
     return messageBox.exec();
 }
showOldMessageBox() [2/2]
int QMessageBoxPrivate::showOldMessageBox (QWidget * parent, QMessageBox::Icon icon, const QString & title, const QString & text, const QString & button0Text, const QString & button1Text, const QString & button2Text, int defaultButtonNumber, int escapeButtonNumber) static
Definition at line 2005 of file qmessagebox.cpp.
 {
     QMessageBox messageBox(icon, title, text, QMessageBox::NoButton, parent);
     QString myButton0Text = button0Text;
     if (myButton0Text.isEmpty())
         myButton0Text = QDialogButtonBox::tr("OK");
     messageBox.addButton(myButton0Text, QMessageBox::ActionRole);
     if (!button1Text.isEmpty())
         messageBox.addButton(button1Text, QMessageBox::ActionRole);
     if (!button2Text.isEmpty())
         messageBox.addButton(button2Text, QMessageBox::ActionRole);
     const QList<QAbstractButton *> &buttonList = messageBox.d_func()->customButtonList;
     messageBox.setDefaultButton(static_cast<QPushButton *>(buttonList.value(defaultButtonNumber)));
     messageBox.setEscapeButton(buttonList.value(escapeButtonNumber));
     return messageBox.exec();
 }
standardIcon()
QPixmap QMessageBoxPrivate::standardIcon (QMessageBox::Icon icon, QMessageBox * mb) static
Definition at line 2803 of file qmessagebox.cpp.
Referenced by QMessageBox::setIcon(), and QMessageBox::standardIcon().
 {
     QStyle *style = mb ? mb->style() : QApplication::style();
     int iconSize = style->pixelMetric(QStyle::PM_MessageBoxIconSize, 0, mb);
     QIcon tmpIcon;
     switch (icon) {
     case QMessageBox::Information:
         tmpIcon = style->standardIcon(QStyle::SP_MessageBoxInformation, 0, mb);
         break;
     case QMessageBox::Warning:
         tmpIcon = style->standardIcon(QStyle::SP_MessageBoxWarning, 0, mb);
         break;
     case QMessageBox::Critical:
         tmpIcon = style->standardIcon(QStyle::SP_MessageBoxCritical, 0, mb);
         break;
     case QMessageBox::Question:
         tmpIcon = style->standardIcon(QStyle::SP_MessageBoxQuestion, 0, mb);
     default:
         break;
     }
     if (!tmpIcon.isNull())
         return tmpIcon.pixmap(iconSize, iconSize);
     return QPixmap();
 }
updateSize()
void QMessageBoxPrivate::updateSize ()
Definition at line 309 of file qmessagebox.cpp.
 {
     Q_Q(QMessageBox);
     if (!q->isVisible())
         return;
     QSize screenSize = QApplication::desktop()->availableGeometry(QCursor::pos()).size();
 #if defined(Q_WS_QWS) || defined(Q_WS_WINCE) || defined(Q_OS_SYMBIAN)
     // the width of the screen, less the window border.
     int hardLimit = screenSize.width() - (q->frameGeometry().width() - q->geometry().width());
 #else
     int hardLimit = qMin(screenSize.width() - 480, 1000); // can never get bigger than this
     // on small screens allows the messagebox be the same size as the screen
     if (screenSize.width() <= 1024)
         hardLimit = screenSize.width();
 #endif
 #ifdef Q_WS_MAC
     int softLimit = qMin(screenSize.width()/2, 420);
 #elif defined(Q_WS_QWS)
     int softLimit = qMin(hardLimit, 500);
 #else
     // note: ideally on windows, hard and soft limits but it breaks compat
 #ifndef Q_WS_WINCE
     int softLimit = qMin(screenSize.width()/2, 500);
 #else
     int softLimit = qMin(screenSize.width() * 3 / 4, 500);
 #endif //Q_WS_WINCE
 #endif
     if (informativeLabel)
         informativeLabel->setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Ignored);
     label->setWordWrap(false); // makes the label return min size
     int width = layoutMinimumWidth();
     if (width > softLimit) {
         label->setWordWrap(true);
         width = qMax(softLimit, layoutMinimumWidth());
         if (width > hardLimit) {
             label->d_func()->ensureTextControl();
             if (QTextControl *control = label->d_func()->control) {
                 QTextOption opt = control->document()->defaultTextOption();
                 opt.setWrapMode(QTextOption::WrapAnywhere);
                 control->document()->setDefaultTextOption(opt);
             }
             width = hardLimit;
         }
     }
 #ifdef Q_WS_S60
         // in S60 portait messageBoxes should always occupy maximum width
         if (QApplication::desktop()->size().height() > QApplication::desktop()->size().width()){
             width = hardLimit;
         } else {
             // in landscape the messageBoxes should be of same width as in portrait
             width = qMin(QApplication::desktop()->size().height(), hardLimit);
         }
 #endif
     if (informativeLabel) {
         label->setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Ignored);
         QSizePolicy policy(QSizePolicy::Minimum, QSizePolicy::Preferred);
         policy.setHeightForWidth(true);
         informativeLabel->setSizePolicy(policy);
         width = qMax(width, layoutMinimumWidth());
         if (width > hardLimit) { // longest word is really big, so wrap anywhere
             informativeLabel->d_func()->ensureTextControl();
             if (QTextControl *control = informativeLabel->d_func()->control) {
                 QTextOption opt = control->document()->defaultTextOption();
                 opt.setWrapMode(QTextOption::WrapAnywhere);
                 control->document()->setDefaultTextOption(opt);
             }
             width = hardLimit;
         }
         policy.setHeightForWidth(label->wordWrap());
         label->setSizePolicy(policy);
     }
     QFontMetrics fm(QApplication::font("QWorkspaceTitleBar"));
     int windowTitleWidth = qMin(fm.width(q->windowTitle()) + 50, hardLimit);
     if (windowTitleWidth > width)
         width = windowTitleWidth;
     layout->activate();
     int height = (layout->hasHeightForWidth())
                      ? layout->totalHeightForWidth(width)
                      : layout->totalMinimumSize().height();
 #ifndef QT_NO_STYLE_S60
         QS60Style *s60Style = 0;
         s60Style = qobject_cast<QS60Style *>(QApplication::style());
         //use custom pixel metric to deduce the minimum height of the messagebox
         if (s60Style)
             height = qMax(height, s60Style->pixelMetric((QStyle::PixelMetric)PM_MessageBoxHeight));
 #endif
     q->setFixedSize(width, height);
     QCoreApplication::removePostedEvents(q, QEvent::LayoutRequest);
 }
Properties
autoAddOkButton
bool QMessageBoxPrivate::autoAddOkButton
Definition at line 223 of file qmessagebox.cpp.
buttonBox
QDialogButtonBox* QMessageBoxPrivate::buttonBox
Definition at line 213 of file qmessagebox.cpp.
clickedButton
QAbstractButton* QMessageBoxPrivate::clickedButton
Definition at line 217 of file qmessagebox.cpp.
compatMode
bool QMessageBoxPrivate::compatMode
Definition at line 222 of file qmessagebox.cpp.
customButtonList
QList<QAbstractButton *> QMessageBoxPrivate::customButtonList
Definition at line 214 of file qmessagebox.cpp.
defaultButton
QPushButton* QMessageBoxPrivate::defaultButton
Definition at line 216 of file qmessagebox.cpp.
detailsButton
DetailButton* QMessageBoxPrivate::detailsButton
Definition at line 218 of file qmessagebox.cpp.
detailsText
QMessageBoxDetailsText* QMessageBoxPrivate::detailsText
Definition at line 220 of file qmessagebox.cpp.
detectedEscapeButton
QAbstractButton* QMessageBoxPrivate::detectedEscapeButton
Definition at line 224 of file qmessagebox.cpp.
escapeButton
QAbstractButton* QMessageBoxPrivate::escapeButton
Definition at line 215 of file qmessagebox.cpp.
icon
QMessageBox::Icon QMessageBoxPrivate::icon
Definition at line 211 of file qmessagebox.cpp.
iconLabel
QLabel* QMessageBoxPrivate::iconLabel
Definition at line 212 of file qmessagebox.cpp.
informativeLabel
QLabel* QMessageBoxPrivate::informativeLabel
Definition at line 225 of file qmessagebox.cpp.
label
QLabel* QMessageBoxPrivate::label
Definition at line 210 of file qmessagebox.cpp.
memberToDisconnectOnClose
QByteArray QMessageBoxPrivate::memberToDisconnectOnClose
Definition at line 230 of file qmessagebox.cpp.
receiverToDisconnectOnClose
QPointer<QObject> QMessageBoxPrivate::receiverToDisconnectOnClose
Definition at line 229 of file qmessagebox.cpp.
signalToDisconnectOnClose
QByteArray QMessageBoxPrivate::signalToDisconnectOnClose
Definition at line 231 of file qmessagebox.cpp.
The documentation for this class was generated from the following file:
/src/gui/dialogs/qmessagebox.cpp