Qt 4.8: QFileSystemModel Class Reference
QFileSystemModel Class Reference
The QFileSystemModel class provides a data model for the local filesystem.
#include <qfilesystemmodel.h>
Public Types
enum Roles { FileIconRole = Qt::DecorationRole, FilePathRole = Qt::UserRole + 1, FileNameRole = Qt::UserRole + 2, FilePermissions = Qt::UserRole + 3 }
Signals
void directoryLoaded (const QString &path)
This signal is emitted when the gatherer thread has finished to load the path.
void fileRenamed (const QString &path, const QString &oldName, const QString &newName)
This signal is emitted whenever a file with the oldName is successfully renamed to newName.
void rootPathChanged (const QString &newPath)
This signal is emitted whenever the root path has been changed to a newPath.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool canFetchMore (const QModelIndex &parent) const
Reimplemented Function
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Reimplemented Function
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action over the row in the model specified by the row and column and by the parent index.
void fetchMore (const QModelIndex &parent)
Reimplemented Function
QIcon fileIcon (const QModelIndex &index) const
Returns the icon for the item stored in the model under the given index.
QFileInfo fileInfo (const QModelIndex &index) const
Returns the QFileInfo for the item stored in the model under the given index.
QString fileName (const QModelIndex &index) const
Returns the file name for the item stored in the model under the given index.
QString filePath (const QModelIndex &index) const
Returns the path of the item stored in the model under the index given.
QDir::Filters filter () const
Returns the filter specified for the directory model.
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Reimplemented Function
QFileIconProvider * iconProvider () const
Returns the file icon provider for this directory model.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QModelIndex index (const QString &path, int column=0) const
Returns the model item index for the given path and column.
bool isDir (const QModelIndex &index) const
Returns true if the model item index represents a directory; otherwise returns false.
bool isReadOnly () const
QDateTime lastModified (const QModelIndex &index) const
Returns the date and time when index was last modified.
QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains a serialized description of the specified indexes.
QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of items in the model.
QModelIndex mkdir (const QModelIndex &parent, const QString &name)
Create a directory with the name in the parent model index.
QVariant myComputer (int role=Qt::DisplayRole) const
Returns the data stored under the given role for the item "My Computer".
bool nameFilterDisables () const
QStringList nameFilters () const
Returns a list of filters applied to the names in the model.
QModelIndex parent (const QModelIndex &child) const
Reimplemented Function
QFile::Permissions permissions (const QModelIndex &index) const
Returns the complete OR-ed together combination of QFile::Permission for the index.
QFileSystemModel (QObject *parent=0)
Constructs a file system model with the given parent.
bool remove (const QModelIndex &index) const
Removes the model item index from the file system model and deletes the corresponding file from the file system, returning true if successful.
bool resolveSymlinks () const
bool rmdir (const QModelIndex &index) const
Removes the directory corresponding to the model item index in the file system model and deletes the corresponding directory from the file system, returning true if successful.
QDir rootDirectory () const
The currently set directory.
QString rootPath () const
The currently set root path.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
void setFilter (QDir::Filters filters)
Sets the directory model's filter to that specified by filters.
void setIconProvider (QFileIconProvider *provider)
Sets the provider of file icons for the directory model.
void setNameFilterDisables (bool enable)
void setNameFilters (const QStringList &filters)
Sets the name filters to apply against the existing files.
void setReadOnly (bool enable)
void setResolveSymlinks (bool enable)
QModelIndex setRootPath (const QString &path)
Sets the directory that is being watched by the model to newPath by installing a file system watcher on it.
qint64 size (const QModelIndex &index) const
Returns the size in bytes of index.
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
Qt::DropActions supportedDropActions () const
Reimplemented Function
QString type (const QModelIndex &index) const
Returns the type of file index such as "Directory" or "JPEG file".
~QFileSystemModel ()
Destroys this file system model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *event)
Reimplemented Function
QFileSystemModel (QFileSystemModelPrivate &, QObject *parent=0)
void timerEvent (QTimerEvent *event)
Reimplemented Function
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Properties
bool nameFilterDisables
Whether files that don't pass the name filter are hidden or disabled.
bool readOnly
Whether the directory model allows writing to the file system.
bool resolveSymlinks
Whether the directory model should resolve symbolic links.
Friends
class QFileDialogPrivate
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QFileSystemModel class provides a data model for the local filesystem.
Since
4.4
This class provides access to the local filesystem, providing functions for renaming and removing files and directories, and for creating new directories. In the simplest case, it can be used with a suitable display widget as part of a browser or filter.
QFileSystemModel can be accessed using the standard interface provided by QAbstractItemModel, but it also provides some convenience functions that are specific to a directory model. The fileInfo(), isDir(), name(), and path() functions provide information about the underlying files and directories related to items in the model. Directories can be created and removed using mkdir(), rmdir().
Note
QFileSystemModel requires an instance of a GUI application.
Example Usage
A directory model that displays the contents of a default directory is usually constructed with a parent object:
    QFileSystemModel *model = new QFileSystemModel;
    model->setRootPath(QDir::currentPath());
A tree view can be used to display the contents of the model
    QTreeView *tree = new QTreeView(splitter);
    tree->setModel(model);
and the contents of a particular directory can be displayed by setting the tree view's root index:
    tree->setRootIndex(model->index(QDir::currentPath()));
The view's root index can be used to control how much of a hierarchical model is displayed. QDirModel provides a convenience function that returns a suitable model index for a path to a directory within the model.
Caching and Performance
QFileSystemModel will not fetch any files or directories until setRootPath() is called. This will prevent any unnecessary querying on the file system until that point such as listing the drives on Windows.
Unlike QDirModel, QFileSystemModel uses a separate thread to populate itself so it will not cause the main thread to hang as the file system is being queried. Calls to rowCount() will return 0 until the model populates a directory.
QFileSystemModel keeps a cache with file information. The cache is automatically kept up to date using the QFileSystemWatcher.
See also
{Model Classes}
Definition at line 63 of file qfilesystemmodel.h.
Enumerations
Roles
enum QFileSystemModel::Roles
FileIconRole
FilePathRole
FileNameRole
FilePermissions
Enumerator
FileIconRole
FilePathRole
FileNameRole
FilePermissions
Definition at line 76 of file qfilesystemmodel.h.
                {
         FileIconRole = Qt::DecorationRole,
         FilePathRole = Qt::UserRole + 1,
         FileNameRole = Qt::UserRole + 2,
         FilePermissions = Qt::UserRole + 3
     };
Constructors and Destructors
QFileSystemModel() [1/2]
QFileSystemModel::QFileSystemModel (QObject * parent = 0) explicit
Constructs a file system model with the given parent.
Definition at line 259 of file qfilesystemmodel.cpp.
     : QAbstractItemModel(*new QFileSystemModelPrivate, parent)
 {
     Q_D(QFileSystemModel);
     d->init();
 }
~QFileSystemModel()
QFileSystemModel::~QFileSystemModel ()
Destroys this file system model.
Definition at line 279 of file qfilesystemmodel.cpp.
 {
 }
QFileSystemModel() [2/2]
QFileSystemModel::QFileSystemModel (QFileSystemModelPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 269 of file qfilesystemmodel.cpp.
     : QAbstractItemModel(dd, parent)
 {
     Q_D(QFileSystemModel);
     d->init();
 }
Functions
canFetchMore()
bool QFileSystemModel::canFetchMore (const QModelIndex & parent) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 652 of file qfilesystemmodel.cpp.
 {
     Q_D(const QFileSystemModel);
     const QFileSystemModelPrivate::QFileSystemNode *indexNode = d->node(parent);
     return (!indexNode->populatedChildren);
 }
columnCount()
int QFileSystemModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 693 of file qfilesystemmodel.cpp.
Referenced by index().
 {
     return (parent.column() > 0) ? 0 : 4;
 }
data()
QVariant QFileSystemModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 718 of file qfilesystemmodel.cpp.
Referenced by fileName(), mimeData(), and QUrlModel::setData().
 {
     Q_D(const QFileSystemModel);
     if (!index.isValid() || index.model() != this)
         return QVariant();
     switch (role) {
     case Qt::EditRole:
     case Qt::DisplayRole:
         switch (index.column()) {
         case 0: return d->displayName(index);
         case 1: return d->size(index);
         case 2: return d->type(index);
         case 3: return d->time(index);
         default:
             qWarning("data: invalid display value column %d", index.column());
             break;
         }
         break;
     case FilePathRole:
         return filePath(index);
     case FileNameRole:
         return d->name(index);
     case Qt::DecorationRole:
         if (index.column() == 0) {
             QIcon icon = d->icon(index);
             if (icon.isNull()) {
                 if (d->node(index)->isDir())
                     icon = d->fileInfoGatherer.iconProvider()->icon(QFileIconProvider::Folder);
                 else
                     icon = d->fileInfoGatherer.iconProvider()->icon(QFileIconProvider::File);
             }
             return icon;
         }
         break;
     case Qt::TextAlignmentRole:
         if (index.column() == 1)
             return Qt::AlignRight;
         break;
     case FilePermissions:
         int p = permissions(index);
         return p;
     }
     return QVariant();
 }
directoryLoaded
void QFileSystemModel::directoryLoaded (const QString & path) signal
This signal is emitted when the gatherer thread has finished to load the path.
Since
4.7
Referenced by QFileSystemModelPrivate::init().
dropMimeData()
bool QFileSystemModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Handles the data supplied by a drag and drop operation that ended with the given action over the row in the model specified by the row and column and by the parent index.
See also
supportedDropActions()
Reimplemented from QAbstractItemModel.
Definition at line 1261 of file qfilesystemmodel.cpp.
 {
     Q_UNUSED(row);
     Q_UNUSED(column);
     if (!parent.isValid() || isReadOnly())
         return false;
     bool success = true;
     QString to = filePath(parent) + QDir::separator();
     QList<QUrl> urls = data->urls();
     QList<QUrl>::const_iterator it = urls.constBegin();
     switch (action) {
     case Qt::CopyAction:
         for (; it != urls.constEnd(); ++it) {
             QString path = (*it).toLocalFile();
             success = QFile::copy(path, to + QFileInfo(path).fileName()) && success;
         }
         break;
     case Qt::LinkAction:
         for (; it != urls.constEnd(); ++it) {
             QString path = (*it).toLocalFile();
             success = QFile::link(path, to + QFileInfo(path).fileName()) && success;
         }
         break;
     case Qt::MoveAction:
         for (; it != urls.constEnd(); ++it) {
             QString path = (*it).toLocalFile();
             success = QFile::rename(path, to + QFileInfo(path).fileName()) && success;
         }
         break;
     default:
         return false;
     }
     return success;
 }
event()
bool QFileSystemModel::event (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1670 of file qfilesystemmodel.cpp.
 {
     Q_D(QFileSystemModel);
     if (event->type() == QEvent::LanguageChange) {
         d->root.retranslateStrings(d->fileInfoGatherer.iconProvider(), QString());
         return true;
     }
     return QAbstractItemModel::event(event);
 }
fetchMore()
void QFileSystemModel::fetchMore (const QModelIndex & parent) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 662 of file qfilesystemmodel.cpp.
Referenced by setRootPath(), and QFSCompleter::splitPath().
 {
     Q_D(QFileSystemModel);
     if (!d->setRootPath)
         return;
     QFileSystemModelPrivate::QFileSystemNode *indexNode = d->node(parent);
     if (indexNode->populatedChildren)
         return;
     indexNode->populatedChildren = true;
     d->fileInfoGatherer.list(filePath(parent));
 }
fileIcon()
QIcon QFileSystemModel::fileIcon (const QModelIndex & index) const inline
Returns the icon for the item stored in the model under the given index.
Definition at line 168 of file qfilesystemmodel.h.
 { return qvariant_cast<QIcon>(aindex.data(Qt::DecorationRole)); }
fileInfo()
QFileInfo QFileSystemModel::fileInfo (const QModelIndex & index) const inline
Returns the QFileInfo for the item stored in the model under the given index.
Definition at line 170 of file qfilesystemmodel.h.
Referenced by isDir().
 { return QFileInfo(filePath(aindex)); }
fileName()
QString QFileSystemModel::fileName (const QModelIndex & index) const inline
Returns the file name for the item stored in the model under the given index.
Definition at line 166 of file qfilesystemmodel.h.
Referenced by QFileSystemModelPrivate::_q_fileSystemChanged(), QFileSystemModelPrivate::_q_resolvedName(), and dropMimeData().
 { return aindex.data(Qt::DisplayRole).toString(); }
filePath()
QString QFileSystemModel::filePath (const QModelIndex & index) const
Returns the path of the item stored in the model under the index given.
Definition at line 1313 of file qfilesystemmodel.cpp.
Referenced by data(), dropMimeData(), fetchMore(), mimeData(), mkdir(), QFileSystemModelPrivate::name(), remove(), rmdir(), and setData().
 {
     Q_D(const QFileSystemModel);
     QString fullPath = d->filePath(index);
     QFileSystemModelPrivate::QFileSystemNode *dirNode = d->node(index);
     if (dirNode->isSymLink() && d->fileInfoGatherer.resolveSymlinks()
         && d->resolvedSymLinks.contains(fullPath)
         && dirNode->isDir()) {
         QFileInfo resolvedInfo(fullPath);
         resolvedInfo = resolvedInfo.canonicalFilePath();
         if (resolvedInfo.exists())
             return resolvedInfo.filePath();
     }
     return fullPath;
 }
fileRenamed
void QFileSystemModel::fileRenamed (const QString & path, const QString & oldName, const QString & newName) signal
This signal is emitted whenever a file with the oldName is successfully renamed to newName.
The file is located in in the directory path.
Referenced by setData().
filter()
QDir::Filters QFileSystemModel::filter () const
Returns the filter specified for the directory model.
If a filter has not been set, the default filter is QDir::AllEntries | QDir::NoDotAndDotDot | QDir::AllDirs.
See also
QDir::Filters
Definition at line 1535 of file qfilesystemmodel.cpp.
Referenced by rootDirectory(), and setNameFilters().
 {
     Q_D(const QFileSystemModel);
     return d->filters;
 }
flags()
Qt::ItemFlags QFileSystemModel::flags (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 983 of file qfilesystemmodel.cpp.
Referenced by setData().
 {
     Q_D(const QFileSystemModel);
     Qt::ItemFlags flags = QAbstractItemModel::flags(index);
     if (!index.isValid())
         return flags;
     QFileSystemModelPrivate::QFileSystemNode *indexNode = d->node(index);
     if (d->nameFilterDisables && !d->passNameFilters(indexNode)) {
         flags &= ~Qt::ItemIsEnabled;
         // ### TODO you shouldn't be able to set this as the current item, task 119433
         return flags;
     }
     flags |= Qt::ItemIsDragEnabled;
     if (d->readOnly)
         return flags;
     if ((index.column() == 0) && indexNode->permissions() & QFile::WriteUser) {
         flags |= Qt::ItemIsEditable;
         if (indexNode->isDir())
             flags |= Qt::ItemIsDropEnabled;
     }
     return flags;
 }
hasChildren()
bool QFileSystemModel::hasChildren (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 635 of file qfilesystemmodel.cpp.
 {
     Q_D(const QFileSystemModel);
     if (parent.column() > 0)
         return false;
     if (!parent.isValid()) // drives
         return true;
     const QFileSystemModelPrivate::QFileSystemNode *indexNode = d->node(parent);
     Q_ASSERT(indexNode);
     return (indexNode->isDir());
 }
headerData()
QVariant QFileSystemModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 936 of file qfilesystemmodel.cpp.
 {
     switch (role) {
     case Qt::DecorationRole:
         if (section == 0) {
             // ### TODO oh man this is ugly and doesn't even work all the way!
             // it is still 2 pixels off
             QImage pixmap(16, 1, QImage::Format_Mono);
             pixmap.fill(0);
             pixmap.setAlphaChannel(pixmap.createAlphaMask());
             return pixmap;
         }
         break;
     case Qt::TextAlignmentRole:
         return Qt::AlignLeft;
     }
     if (orientation != Qt::Horizontal || role != Qt::DisplayRole)
         return QAbstractItemModel::headerData(section, orientation, role);
     QString returnValue;
     switch (section) {
     case 0: returnValue = tr("Name");
             break;
     case 1: returnValue = tr("Size");
             break;
     case 2: returnValue =
 #ifdef Q_OS_MAC
                    tr("Kind", "Match OS X Finder");
 #else
                    tr("Type", "All other platforms");
 #endif
            break;
     // Windows   - Type
     // OS X      - Kind
     // Konqueror - File Type
     // Nautilus  - Type
     case 3: returnValue = tr("Date Modified");
             break;
     default: return QVariant();
     }
     return returnValue;
 }
iconProvider()
QFileIconProvider * QFileSystemModel::iconProvider () const
Returns the file icon provider for this directory model.
Definition at line 1501 of file qfilesystemmodel.cpp.
Referenced by QUrlModel::setUrl().
 {
     Q_D(const QFileSystemModel);
     return d->fileInfoGatherer.iconProvider();
 }
index() [1/2]
QModelIndex QFileSystemModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 286 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_autoCompleteFileName(), QFileSystemModelPrivate::_q_fileSystemChanged(), QFileDialogPrivate::_q_goToDirectory(), QFileDialogPrivate::_q_goToUrl(), QFileDialogPrivate::_q_updateOkButton(), QUrlModel::addUrls(), QFileSystemModelPrivate::addVisibleFiles(), QUrlModel::canDrop(), QFileSystemModelPrivate::filePath(), QUrlModel::layoutChanged(), QFileSystemModelPrivate::node(), remove(), QFileDialogPrivate::removeDirectory(), QFileSystemModelPrivate::removeNode(), QFileSystemModelPrivate::removeVisibleFile(), QUrlModel::setData(), setNameFilters(), QFileDialogComboBox::showPopup(), and sort().
 {
     Q_D(const QFileSystemModel);
     if (row < 0 || column < 0 || row >= rowCount(parent) || column >= columnCount(parent))
         return QModelIndex();
     // get the parent node
     QFileSystemModelPrivate::QFileSystemNode *parentNode = (d->indexValid(parent) ? d->node(parent) :
                                                    const_cast<QFileSystemModelPrivate::QFileSystemNode*>(&d->root));
     Q_ASSERT(parentNode);
     // now get the internal pointer for the index
     QString childName = parentNode->visibleChildren[d->translateVisibleLocation(parentNode, row)];
     const QFileSystemModelPrivate::QFileSystemNode *indexNode = parentNode->children.value(childName);
     Q_ASSERT(indexNode);
     return createIndex(row, column, const_cast<QFileSystemModelPrivate::QFileSystemNode*>(indexNode));
 }
index() [2/2]
QModelIndex QFileSystemModel::index (const QString & path, int column = 0) const
Returns the model item index for the given path and column.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 313 of file qfilesystemmodel.cpp.
 {
     Q_D(const QFileSystemModel);
     QFileSystemModelPrivate::QFileSystemNode *node = d->node(path, false);
     QModelIndex idx = d->index(node);
     if (idx.column() != column)
         idx = idx.sibling(idx.row(), column);
     return idx;
 }
isDir()
bool QFileSystemModel::isDir (const QModelIndex & index) const
Returns true if the model item index represents a directory; otherwise returns false.
Definition at line 542 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_deleteCurrent(), QFileDialogPrivate::_q_enterDirectory(), QFileDialogPrivate::_q_selectionChanged(), QFileDialogPrivate::_q_updateOkButton(), QUrlModel::addUrls(), and QUrlModel::canDrop().
 {
     // This function is for public usage only because it could create a file info
     Q_D(const QFileSystemModel);
     if (!index.isValid())
         return true;
     QFileSystemModelPrivate::QFileSystemNode *n = d->node(index);
     if (n->hasInformation())
         return n->isDir();
     return fileInfo(index).isDir();
 }
isReadOnly()
bool QFileSystemModel::isReadOnly () const
Definition at line 1582 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_deleteCurrent(), and dropMimeData().
 {
     Q_D(const QFileSystemModel);
     return d->readOnly;
 }
lastModified()
QDateTime QFileSystemModel::lastModified (const QModelIndex & index) const
Returns the date and time when index was last modified.
Definition at line 579 of file qfilesystemmodel.cpp.
 {
     Q_D(const QFileSystemModel);
     if (!index.isValid())
         return QDateTime();
     return d->node(index)->lastModified();
 }
mimeData()
QMimeData * QFileSystemModel::mimeData (const QModelIndexList & indexes) const virtual
Returns an object that contains a serialized description of the specified indexes.
The format used to describe the items corresponding to the indexes is obtained from the mimeTypes() function.
If the list of indexes is empty, 0 is returned rather than a serialized empty list.
Reimplemented from QAbstractItemModel.
Definition at line 1242 of file qfilesystemmodel.cpp.
 {
     QList<QUrl> urls;
     QList<QModelIndex>::const_iterator it = indexes.begin();
     for (; it != indexes.end(); ++it)
         if ((*it).column() == 0)
             urls << QUrl::fromLocalFile(filePath(*it));
     QMimeData *data = new QMimeData();
     data->setUrls(urls);
     return data;
 }
mimeTypes()
QStringList QFileSystemModel::mimeTypes () const virtual
Returns a list of MIME types that can be used to describe a list of items in the model.
Reimplemented from QAbstractItemModel.
Definition at line 1229 of file qfilesystemmodel.cpp.
 {
     return QStringList(QLatin1String("text/uri-list"));
 }
mkdir()
QModelIndex QFileSystemModel::mkdir (const QModelIndex & parent, const QString & name)
Create a directory with the name in the parent model index.
Definition at line 1360 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_createDirectory().
 {
     Q_D(QFileSystemModel);
     if (!parent.isValid())
         return parent;
     QDir dir(filePath(parent));
     if (!dir.mkdir(name))
         return QModelIndex();
     QFileSystemModelPrivate::QFileSystemNode *parentNode = d->node(parent);
     d->addNode(parentNode, name, QFileInfo());
     Q_ASSERT(parentNode->children.contains(name));
     QFileSystemModelPrivate::QFileSystemNode *node = parentNode->children[name];
     node->populate(d->fileInfoGatherer.getInfo(QFileInfo(dir.absolutePath() + QDir::separator() + name)));
     d->addVisibleFiles(parentNode, QStringList(name));
     return d->index(node);
 }
myComputer()
QVariant QFileSystemModel::myComputer (int role = Qt::DisplayRole) const
Returns the data stored under the given role for the item "My Computer".
See also
Qt::ItemDataRole
Definition at line 703 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_goToDirectory(), QFileDialogPrivate::_q_navigateToParent(), QFileSystemModelPrivate::node(), and QUrlModel::setUrl().
 {
     Q_D(const QFileSystemModel);
     switch (role) {
     case Qt::DisplayRole:
         return d->myComputer();
     case Qt::DecorationRole:
         return d->fileInfoGatherer.iconProvider()->icon(QFileIconProvider::Computer);
     }
     return QVariant();
 }
nameFilterDisables()
bool QFileSystemModel::nameFilterDisables () const
Referenced by QFileSystemModelPrivate::filtersAcceptsNode(), and setNameFilterDisables().
nameFilters()
QStringList QFileSystemModel::nameFilters () const
Returns a list of filters applied to the names in the model.
Definition at line 1655 of file qfilesystemmodel.cpp.
Referenced by QFileSystemModelPrivate::passNameFilters(), rootDirectory(), and setFilter().
 {
     Q_D(const QFileSystemModel);
     QStringList filters;
 #ifndef QT_NO_REGEXP
     for (int i = 0; i < d->nameFilters.size(); ++i) {
          filters << d->nameFilters.at(i).pattern();
     }
 #endif
     return filters;
 }
parent()
QModelIndex QFileSystemModel::parent (const QModelIndex & child) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 590 of file qfilesystemmodel.cpp.
 {
     Q_D(const QFileSystemModel);
     if (!d->indexValid(index))
         return QModelIndex();
     QFileSystemModelPrivate::QFileSystemNode *indexNode = d->node(index);
     Q_ASSERT(indexNode != 0);
     QFileSystemModelPrivate::QFileSystemNode *parentNode = (indexNode ? indexNode->parent : 0);
     if (parentNode == 0 || parentNode == &d->root)
         return QModelIndex();
     // get the parent's row
     QFileSystemModelPrivate::QFileSystemNode *grandParentNode = parentNode->parent;
     Q_ASSERT(grandParentNode->children.contains(parentNode->fileName));
     int visualRow = d->translateVisibleLocation(grandParentNode, grandParentNode->visibleLocation(grandParentNode->children.value(parentNode->fileName)->fileName));
     if (visualRow == -1)
         return QModelIndex();
     return createIndex(visualRow, 0, parentNode);
 }
permissions()
QFile::Permissions QFileSystemModel::permissions (const QModelIndex & index) const
Returns the complete OR-ed together combination of QFile::Permission for the index.
Definition at line 1381 of file qfilesystemmodel.cpp.
Referenced by data().
 {
     Q_D(const QFileSystemModel);
     QFile::Permissions p = d->node(index)->permissions();
     if (d->readOnly) {
         p ^= (QFile::WriteOwner | QFile::WriteUser
             | QFile::WriteGroup | QFile::WriteOther);
     }
     return p;
 }
remove()
bool QFileSystemModel::remove (const QModelIndex & index) const
Removes the model item index from the file system model and deletes the corresponding file from the file system, returning true if successful.
If the item cannot be removed, false is returned.
Warning
This function deletes files from the file system; it does not move them to a location where they can be recovered.
See also
rmdir()
Definition at line 226 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_deleteCurrent(), and QFileDialogPrivate::removeDirectory().
 {
     //### TODO optim
     QString path = filePath(aindex);
     QFileSystemModelPrivate * d = const_cast<QFileSystemModelPrivate*>(d_func());
     d->fileInfoGatherer.removePath(path);
     QDirIterator it(path,
             QDir::AllDirs | QDir:: Files | QDir::NoDotAndDotDot,
             QDirIterator::Subdirectories);
     QStringList children;
     while (it.hasNext())
         children.prepend(it.next());
     children.append(path);
     bool error = false;
     for (int i = 0; i < children.count(); ++i) {
         QFileInfo info(children.at(i));
         QModelIndex modelIndex = index(children.at(i));
         if (info.isDir()) {
             QDir dir;
             if (children.at(i) != path)
                 error |= remove(modelIndex);
             error |= rmdir(modelIndex);
         } else {
             error |= QFile::remove(filePath(modelIndex));
         }
     }
     return error;
 }
resolveSymlinks()
bool QFileSystemModel::resolveSymlinks () const
Referenced by setResolveSymlinks().
rmdir()
bool QFileSystemModel::rmdir (const QModelIndex & index) const
Removes the directory corresponding to the model item index in the file system model and deletes the corresponding directory from the file system, returning true if successful.
If the directory cannot be removed, false is returned.
Warning
This function deletes directories from the file system; it does not move them to a location where they can be recovered.
See also
remove()
Definition at line 1680 of file qfilesystemmodel.cpp.
Referenced by remove().
 {
     QString path = filePath(aindex);
     QFileSystemModelPrivate * d = const_cast<QFileSystemModelPrivate*>(d_func());
     d->fileInfoGatherer.removePath(path);
     return QDir().rmdir(path);
 }
rootDirectory()
QDir QFileSystemModel::rootDirectory () const
The currently set directory.
See also
rootPath()
Definition at line 1479 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_navigateToParent(), and QFileDialogPrivate::_q_pathChanged().
 {
     Q_D(const QFileSystemModel);
     QDir dir(d->rootDir);
     dir.setNameFilters(nameFilters());
     dir.setFilter(filter());
     return dir;
 }
rootPath()
QString QFileSystemModel::rootPath () const
The currently set root path.
See also
rootDirectory()
Definition at line 1468 of file qfilesystemmodel.cpp.
Referenced by QFileSystemModelPrivate::node(), setNameFilters(), setRootPath(), and sort().
 {
     Q_D(const QFileSystemModel);
     return d->rootDir.path();
 }
rootPathChanged
void QFileSystemModel::rootPathChanged (const QString & newPath) signal
This signal is emitted whenever the root path has been changed to a newPath.
Referenced by setRootPath().
rowCount()
int QFileSystemModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Implements QAbstractItemModel.
Definition at line 677 of file qfilesystemmodel.cpp.
Referenced by index().
 {
     Q_D(const QFileSystemModel);
     if (parent.column() > 0)
         return 0;
     if (!parent.isValid())
         return d->root.visibleChildren.count();
     const QFileSystemModelPrivate::QFileSystemNode *parentNode = d->node(parent);
     return parentNode->visibleChildren.count();
 }
setData()
bool QFileSystemModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 874 of file qfilesystemmodel.cpp.
Referenced by QFileDialogComboBox::showPopup().
 {
     Q_D(QFileSystemModel);
     if (!idx.isValid()
         || idx.column() != 0
         || role != Qt::EditRole
         || (flags(idx) & Qt::ItemIsEditable) == 0) {
         return false;
     }
     QString newName = value.toString();
     QString oldName = idx.data().toString();
     if (newName == idx.data().toString())
         return true;
     if (newName.isEmpty()
         || QDir::toNativeSeparators(newName).contains(QDir::separator())
         || !QDir(filePath(parent(idx))).rename(oldName, newName)) {
 #ifndef QT_NO_MESSAGEBOX
         QMessageBox::information(0, QFileSystemModel::tr("Invalid filename"),
                                 QFileSystemModel::tr("<b>The name \"%1\" can not be used.</b><p>Try using another name, with fewer characters or no punctuations marks.")
                                 .arg(newName),
                                  QMessageBox::Ok);
 #endif // QT_NO_MESSAGEBOX
         return false;
     } else {
         /*
             *After re-naming something we don't want the selection to change*
             - can't remove rows and later insert
             - can't quickly remove and insert
             - index pointer can't change because treeview doesn't use persistant index's
             - if this get any more complicated think of changing it to just
               use layoutChanged
          */
         QFileSystemModelPrivate::QFileSystemNode *indexNode = d->node(idx);
         QFileSystemModelPrivate::QFileSystemNode *parentNode = indexNode->parent;
         int visibleLocation = parentNode->visibleLocation(parentNode->children.value(indexNode->fileName)->fileName);
         d->addNode(parentNode, newName,indexNode->info->fileInfo());
         parentNode->visibleChildren.removeAt(visibleLocation);
         QFileSystemModelPrivate::QFileSystemNode * oldValue = parentNode->children.value(oldName);
         parentNode->children[newName] = oldValue;
         QFileInfo info(d->rootDir, newName);
         oldValue->fileName = newName;
         oldValue->parent = parentNode;
         oldValue->populate(d->fileInfoGatherer.getInfo(info));
         oldValue->isVisible = true;
         parentNode->children.remove(oldName);
         parentNode->visibleChildren.insert(visibleLocation, newName);
         d->delayedSort();
         emit fileRenamed(filePath(idx.parent()), oldName, newName);
     }
     return true;
 }
setFilter()
void QFileSystemModel::setFilter (QDir::Filters filters)
Sets the directory model's filter to that specified by filters.
Note that the filter you set should always include the QDir::AllDirs enum value, otherwise QFileSystemModel won't be able to read the directory structure.
See also
QDir::Filters
Definition at line 1515 of file qfilesystemmodel.cpp.
 {
     Q_D(QFileSystemModel);
     if (d->filters == filters)
         return;
     d->filters = filters;
     // CaseSensitivity might have changed
     setNameFilters(nameFilters());
     d->forceSort = true;
     d->delayedSort();
 }
setIconProvider()
void QFileSystemModel::setIconProvider (QFileIconProvider * provider)
Sets the provider of file icons for the directory model.
Definition at line 1491 of file qfilesystemmodel.cpp.
 {
     Q_D(QFileSystemModel);
     d->fileInfoGatherer.setIconProvider(provider);
     d->root.updateIcon(provider, QString());
 }
setNameFilterDisables()
void QFileSystemModel::setNameFilterDisables (bool enable)
Definition at line 1597 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::createWidgets().
 {
     Q_D(QFileSystemModel);
     if (d->nameFilterDisables == enable)
         return;
     d->nameFilterDisables = enable;
     d->forceSort = true;
     d->delayedSort();
 }
setNameFilters()
void QFileSystemModel::setNameFilters (const QStringList & filters)
Sets the name filters to apply against the existing files.
Definition at line 1616 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::_q_useNameFilter(), and setFilter().
 {
     // Prep the regexp's ahead of time
 #ifndef QT_NO_REGEXP
     Q_D(QFileSystemModel);
     if (!d->bypassFilters.isEmpty()) {
         // update the bypass filter to only bypass the stuff that must be kept around
         d->bypassFilters.clear();
         // We guarantee that rootPath will stick around
         QPersistentModelIndex root(index(rootPath()));
         QModelIndexList persistantList = persistentIndexList();
         for (int i = 0; i < persistantList.count(); ++i) {
             QFileSystemModelPrivate::QFileSystemNode *node;
             node = d->node(persistantList.at(i));
             while (node) {
                 if (d->bypassFilters.contains(node))
                     break;
                 if (node->isDir())
                     d->bypassFilters[node] = true;
                 node = node->parent;
             }
         }
     }
     d->nameFilters.clear();
     const Qt::CaseSensitivity caseSensitive =
         (filter() & QDir::CaseSensitive) ? Qt::CaseSensitive : Qt::CaseInsensitive;
     for (int i = 0; i < filters.size(); ++i) {
         d->nameFilters << QRegExp(filters.at(i), caseSensitive, QRegExp::Wildcard);
     }
     d->forceSort = true;
     d->delayedSort();
 #endif
 }
setReadOnly()
void QFileSystemModel::setReadOnly (bool enable)
Definition at line 1576 of file qfilesystemmodel.cpp.
Referenced by QFileDialogPrivate::createWidgets().
 {
     Q_D(QFileSystemModel);
     d->readOnly = enable;
 }
setResolveSymlinks()
void QFileSystemModel::setResolveSymlinks (bool enable)
Definition at line 1552 of file qfilesystemmodel.cpp.
 {
     Q_D(QFileSystemModel);
     d->fileInfoGatherer.setResolveSymlinks(enable);
 }
setRootPath()
QModelIndex QFileSystemModel::setRootPath (const QString & newPath)
Sets the directory that is being watched by the model to newPath by installing a file system watcher on it.
Any changes to files and directories within this directory will be reflected in the model.
If the path is changed, the rootPathChanged() signal will be emitted.
Note
This function does not change the structure of the model or modify the data available to views. In other words, the "root" of the model is not changed to include only files and directories within the directory specified by newPath in the file system.
Definition at line 1405 of file qfilesystemmodel.cpp.
Referenced by QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate().
 {
     Q_D(QFileSystemModel);
 #ifdef Q_OS_WIN
 #ifdef Q_OS_WIN32
     QString longNewPath = qt_GetLongPathName(newPath);
 #else
     QString longNewPath = QDir::fromNativeSeparators(newPath);
 #endif
 #else
     QString longNewPath = newPath;
 #endif
     QDir newPathDir(longNewPath);
     //we remove .. and . from the given path if exist
     if (!newPath.isEmpty()) {
         longNewPath = QDir::cleanPath(longNewPath);
         newPathDir.setPath(longNewPath);
     }
     d->setRootPath = true;
     //user don't ask for the root path ("") but the conversion failed
     if (!newPath.isEmpty() && longNewPath.isEmpty())
         return d->index(rootPath());
     if (d->rootDir.path() == longNewPath)
         return d->index(rootPath());
     bool showDrives = (longNewPath.isEmpty() || longNewPath == d->myComputer());
     if (!showDrives && !newPathDir.exists())
         return d->index(rootPath());
     //We remove the watcher on the previous path
     if (!rootPath().isEmpty() && rootPath() != QLatin1String(".")) {
         //This remove the watcher for the old rootPath
         d->fileInfoGatherer.removePath(rootPath());
         //This line "marks" the node as dirty, so the next fetchMore
         //call on the path will ask the gatherer to install a watcher again
         //But it doesn't re-fetch everything
         d->node(rootPath())->populatedChildren = false;
     }
     // We have a new valid root path
     d->rootDir = newPathDir;
     QModelIndex newRootIndex;
     if (showDrives) {
         // otherwise dir will become '.'
         d->rootDir.setPath(QLatin1String(""));
     } else {
         newRootIndex = d->index(newPathDir.path());
     }
     fetchMore(newRootIndex);
     emit rootPathChanged(longNewPath);
     d->forceSort = true;
     d->delayedSort();
     return newRootIndex;
 }
size()
qint64 QFileSystemModel::size (const QModelIndex & index) const
Returns the size in bytes of index.
If the file does not exist, 0 is returned.
Definition at line 557 of file qfilesystemmodel.cpp.
Referenced by QFileSystemModelPrivate::size().
 {
     Q_D(const QFileSystemModel);
     if (!index.isValid())
         return 0;
     return d->node(index)->size();
 }
sort()
void QFileSystemModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1193 of file qfilesystemmodel.cpp.
 {
     Q_D(QFileSystemModel);
     if (d->sortOrder == order && d->sortColumn == column && !d->forceSort)
         return;
     emit layoutAboutToBeChanged();
     QModelIndexList oldList = persistentIndexList();
     QList<QPair<QFileSystemModelPrivate::QFileSystemNode*, int> > oldNodes;
     for (int i = 0; i < oldList.count(); ++i) {
         QPair<QFileSystemModelPrivate::QFileSystemNode*, int> pair(d->node(oldList.at(i)), oldList.at(i).column());
         oldNodes.append(pair);
     }
     if (!(d->sortColumn == column && d->sortOrder != order && !d->forceSort)) {
         //we sort only from where we are, don't need to sort all the model
         d->sortChildren(column, index(rootPath()));
         d->sortColumn = column;
         d->forceSort = false;
     }
     d->sortOrder = order;
     QModelIndexList newList;
     for (int i = 0; i < oldNodes.count(); ++i) {
         QModelIndex idx = d->index(oldNodes.at(i).first);
         idx = idx.sibling(idx.row(), oldNodes.at(i).second);
         newList.append(idx);
     }
     changePersistentIndexList(oldList, newList);
     emit layoutChanged();
 }
supportedDropActions()
Qt::DropActions QFileSystemModel::supportedDropActions () const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1304 of file qfilesystemmodel.cpp.
 {
     return Qt::CopyAction | Qt::MoveAction | Qt::LinkAction;
 }
timerEvent()
void QFileSystemModel::timerEvent (QTimerEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 518 of file qfilesystemmodel.cpp.
 {
     Q_D(QFileSystemModel);
     if (event->timerId() == d->fetchingTimer.timerId()) {
         d->fetchingTimer.stop();
 #ifndef QT_NO_FILESYSTEMWATCHER
         for (int i = 0; i < d->toFetch.count(); ++i) {
             const QFileSystemModelPrivate::QFileSystemNode *node = d->toFetch.at(i).node;
             if (!node->hasInformation()) {
                 d->fileInfoGatherer.fetchExtendedInformation(d->toFetch.at(i).dir,
                                                  QStringList(d->toFetch.at(i).file));
             } else {
                 // qDebug() << "yah!, you saved a little gerbil soul";
             }
         }
 #endif
         d->toFetch.clear();
     }
 }
type()
QString QFileSystemModel::type (const QModelIndex & index) const
Returns the type of file index such as "Directory" or "JPEG file".
Definition at line 568 of file qfilesystemmodel.cpp.
 {
     Q_D(const QFileSystemModel);
     if (!index.isValid())
         return QString();
     return d->node(index)->type();
 }
Friends and Related Functions
QFileDialogPrivate
friend class QFileDialogPrivate friend
Definition at line 163 of file qfilesystemmodel.h.
Properties
nameFilterDisables
bool QFileSystemModel::nameFilterDisables private
Whether files that don't pass the name filter are hidden or disabled.
This property is true by default
Definition at line 68 of file qfilesystemmodel.h.
readOnly
QFileSystemModel::readOnly private
Whether the directory model allows writing to the file system.
If this property is set to false, the directory model will allow renaming, copying and deleting of files and directories.
This property is true by default
Definition at line 67 of file qfilesystemmodel.h.
resolveSymlinks
bool QFileSystemModel::resolveSymlinks private
Whether the directory model should resolve symbolic links.
This is only relevant on operating systems that support symbolic links.
By default, this property is false.
Definition at line 66 of file qfilesystemmodel.h.
The documentation for this class was generated from the following files:
/src/gui/dialogs/qfilesystemmodel.h
/src/gui/dialogs/qfilesystemmodel.cpp