Qt 4.8: QResourceRoot Class Reference
QResourceRoot Class Reference
Public Types
enum ResourceRootType { Resource_Builtin, Resource_File, Resource_Buffer }
Public Functions
QStringList children (int node) const
const uchar * data (int node, qint64 *size) const
int findNode (const QString &path, const QLocale &locale=QLocale()) const
bool isCompressed (int node) const
bool isContainer (int node) const
virtual QString mappingRoot () const
bool mappingRootSubdir (const QString &path, QString *match=0) const
bool operator!= (const QResourceRoot &other) const
bool operator== (const QResourceRoot &other) const
QResourceRoot ()
QResourceRoot (const uchar *t, const uchar *n, const uchar *d)
virtual ResourceRootType type () const
virtual ~QResourceRoot ()
Public Variables
QAtomicInt ref
Protected Functions
void setSource (const uchar *t, const uchar *n, const uchar *d)
Private Types
enum Flags { Compressed = 0x01, Directory = 0x02 }
Private Functions
int findOffset (int node) const
short flags (int node) const
int hash (int node) const
QString name (int node) const
Properties
const uchar * names
const uchar * payloads
const uchar * tree
Detailed Description
Definition at line 108 of file qresource.cpp.
Enumerations
Flags
enum QResourceRoot::Flags private
Enumerator
Compressed
Directory
Definition at line 110 of file qresource.cpp.
     {
         Compressed = 0x01,
         Directory = 0x02
     };
ResourceRootType
enum QResourceRoot::ResourceRootType
Enumerator
Resource_Builtin
Resource_File
Resource_Buffer
Definition at line 137 of file qresource.cpp.
 { Resource_Builtin, Resource_File, Resource_Buffer };
Constructors and Destructors
QResourceRoot() [1/2]
QResourceRoot::QResourceRoot () inline
Definition at line 123 of file qresource.cpp.
 : tree(0), names(0), payloads(0) {}
QResourceRoot() [2/2]
QResourceRoot::QResourceRoot (const uchar * t, const uchar * n, const uchar * d) inline
Definition at line 124 of file qresource.cpp.
 { setSource(t, n, d); }
~QResourceRoot()
virtual QResourceRoot::~QResourceRoot () inline virtual
Definition at line 125 of file qresource.cpp.
 { }
Functions
children()
QStringList QResourceRoot::children (int node) const
Definition at line 806 of file qresource.cpp.
Referenced by QResourcePrivate::ensureChildren().
 {
     if(node == -1)
         return QStringList();
     int offset = findOffset(node) + 4; //jump past name
     const short flags = (tree[offset+0] << 8) + (tree[offset+1] << 0);
     offset += 2;
     QStringList ret;
     if(flags & Directory) {
         const int child_count = (tree[offset+0] << 24) + (tree[offset+1] << 16) +
                                 (tree[offset+2] << 8) + (tree[offset+3] << 0);
         offset += 4;
         const int child_off = (tree[offset+0] << 24) + (tree[offset+1] << 16) +
                               (tree[offset+2] << 8) + (tree[offset+3] << 0);
         for(int i = child_off; i < child_off+child_count; ++i)
             ret << name(i);
     }
     return ret;
 }
data()
const uchar * QResourceRoot::data (int node, qint64 * size) const
Definition at line 781 of file qresource.cpp.
Referenced by QResourcePrivate::load().
 {
     if(node == -1) {
         *size = 0;
         return 0;
     }
     int offset = findOffset(node) + 4; //jump past name
     const short flags = (tree[offset+0] << 8) + (tree[offset+1] << 0);
     offset += 2;
     offset += 4; //jump past locale
     if(!(flags & Directory)) {
         const int data_offset = (tree[offset+0] << 24) + (tree[offset+1] << 16) +
                                 (tree[offset+2] << 8) + (tree[offset+3] << 0);
         const uint data_length = (payloads[data_offset+0] << 24) + (payloads[data_offset+1] << 16) +
                                  (payloads[data_offset+2] << 8) + (payloads[data_offset+3] << 0);
         const uchar *ret = payloads+data_offset+4;
         *size = data_length;
         return ret;
     }
     *size = 0;
     return 0;
 }
findNode()
int QResourceRoot::findNode (const QString & path, const QLocale & locale = QLocale()) const
Definition at line 644 of file qresource.cpp.
Referenced by QResourcePrivate::ensureChildren(), and QResourcePrivate::load().
 {
     QString path = _path;
     {
         QString root = mappingRoot();
         if(!root.isEmpty()) {
             if(root == path) {
                 path = QLatin1Char('/');
             } else {
                 if(!root.endsWith(QLatin1Char('/')))
                     root += QLatin1Char('/');
                 if(path.size() >= root.size() && path.startsWith(root))
                     path = path.mid(root.length()-1);
                 if(path.isEmpty())
                     path = QLatin1Char('/');
             }
         }
     }
 #ifdef DEBUG_RESOURCE_MATCH
     qDebug() << "!!!!" << "START" << path << locale.country() << locale.language();
 #endif
     if(path == QLatin1String("/"))
         return 0;
     //the root node is always first
     int child_count = (tree[6] << 24) + (tree[7] << 16) +
                       (tree[8] << 8) + (tree[9] << 0);
     int child       = (tree[10] << 24) + (tree[11] << 16) +
                       (tree[12] << 8) + (tree[13] << 0);
     //now iterate up the tree
     int node = -1;
     QStringSplitter splitter(path);
     while (child_count && splitter.hasNext()) {
         QStringRef segment = splitter.next();
 #ifdef DEBUG_RESOURCE_MATCH
         qDebug() << "  CHILDREN" << segment;
         for(int j = 0; j < child_count; ++j) {
             qDebug() << "   " << child+j << " :: " << name(child+j);
         }
 #endif
         const int h = qHash(segment);
         //do the binary search for the hash
         int l = 0, r = child_count-1;
         int sub_node = (l+r+1)/2;
         while(r != l) {
             const int sub_node_hash = hash(child+sub_node);
             if(h == sub_node_hash)
                 break;
             else if(h < sub_node_hash)
                 r = sub_node - 1;
             else
                 l = sub_node;
             sub_node = (l + r + 1) / 2;
         }
         sub_node += child;
         //now do the "harder" compares
         bool found = false;
         if(hash(sub_node) == h) {
             while(sub_node > child && hash(sub_node-1) == h) //backup for collisions
                 --sub_node;
             for(; sub_node < child+child_count && hash(sub_node) == h; ++sub_node) { //here we go...
                 if(name(sub_node) == segment) {
                     found = true;
                     int offset = findOffset(sub_node);
 #ifdef DEBUG_RESOURCE_MATCH
                     qDebug() << "  TRY" << sub_node << name(sub_node) << offset;
 #endif
                     offset += 4;  //jump past name
                     const short flags = (tree[offset+0] << 8) +
                                         (tree[offset+1] << 0);
                     offset += 2;
                     if(!splitter.hasNext()) {
                         if(!(flags & Directory)) {
                             const short country = (tree[offset+0] << 8) +
                                                   (tree[offset+1] << 0);
                             offset += 2;
                             const short language = (tree[offset+0] << 8) +
                                                    (tree[offset+1] << 0);
                             offset += 2;
 #ifdef DEBUG_RESOURCE_MATCH
                             qDebug() << "    " << "LOCALE" << country << language;
 #endif
                             if(country == locale.country() && language == locale.language()) {
 #ifdef DEBUG_RESOURCE_MATCH
                                 qDebug() << "!!!!" << "FINISHED" << __LINE__ << sub_node;
 #endif
                                 return sub_node;
                             } else if((country == QLocale::AnyCountry && language == locale.language()) ||
                                       (country == QLocale::AnyCountry && language == QLocale::C && node == -1)) {
                                 node = sub_node;
                             }
                             continue;
                         } else {
 #ifdef DEBUG_RESOURCE_MATCH
                             qDebug() << "!!!!" << "FINISHED" << __LINE__ << sub_node;
 #endif
                             return sub_node;
                         }
                     }
                     if(!(flags & Directory))
                         return -1;
                     child_count = (tree[offset+0] << 24) + (tree[offset+1] << 16) +
                                   (tree[offset+2] << 8) + (tree[offset+3] << 0);
                     offset += 4;
                     child = (tree[offset+0] << 24) + (tree[offset+1] << 16) +
                             (tree[offset+2] << 8) + (tree[offset+3] << 0);
                     break;
                 }
             }
         }
         if(!found)
             break;
     }
 #ifdef DEBUG_RESOURCE_MATCH
     qDebug() << "!!!!" << "FINISHED" << __LINE__ << node;
 #endif
     return node;
 }
findOffset()
int QResourceRoot::findOffset (int node) const inline private
Definition at line 116 of file qresource.cpp.
 { return node * 14; } //sizeof each tree element
flags()
short QResourceRoot::flags (int node) const private
Definition at line 774 of file qresource.cpp.
 {
     if(node == -1)
         return 0;
     const int offset = findOffset(node) + 4; //jump past name
     return (tree[offset+0] << 8) + (tree[offset+1] << 0);
 }
hash()
int QResourceRoot::hash (int node) const inline private
Definition at line 609 of file qresource.cpp.
 {
     if(!node) //root
         return 0;
     const int offset = findOffset(node);
     int name_offset = (tree[offset+0] << 24) + (tree[offset+1] << 16) +
                       (tree[offset+2] << 8) + (tree[offset+3] << 0);
     name_offset += 2; //jump past name length
     return (names[name_offset+0] << 24) + (names[name_offset+1] << 16) +
            (names[name_offset+2] << 8) + (names[name_offset+3] << 0);
 }
isCompressed()
bool QResourceRoot::isCompressed (int node) const inline
Definition at line 128 of file qresource.cpp.
Referenced by QResourcePrivate::load().
 { return flags(node) & Compressed; }
isContainer()
bool QResourceRoot::isContainer (int node) const inline
Definition at line 127 of file qresource.cpp.
Referenced by QResourcePrivate::load().
 { return flags(node) & Directory; }
mappingRoot()
virtual QString QResourceRoot::mappingRoot () const inline virtual
Reimplemented in QDynamicBufferResourceRoot.
Definition at line 131 of file qresource.cpp.
 { return QString(); }
mappingRootSubdir()
bool QResourceRoot::mappingRootSubdir (const QString & path, QString * match = 0) const
Definition at line 827 of file qresource.cpp.
Referenced by QResourcePrivate::ensureChildren(), and QResourcePrivate::load().
 {
     const QString root = mappingRoot();
     if(!root.isEmpty()) {
         const QStringList root_segments = root.split(QLatin1Char('/'), QString::SkipEmptyParts),
                           path_segments = path.split(QLatin1Char('/'), QString::SkipEmptyParts);
         if(path_segments.size() <= root_segments.size()) {
             int matched = 0;
             for(int i = 0; i < path_segments.size(); ++i) {
                 if(root_segments[i] != path_segments[i])
                     break;
                 ++matched;
             }
             if(matched == path_segments.size()) {
                 if(match && root_segments.size() > matched)
                     *match = root_segments.at(matched);
                 return true;
             }
         }
     }
     return false;
 }
name()
QString QResourceRoot::name (int node) const inline private
Definition at line 620 of file qresource.cpp.
 {
     if(!node) // root
         return QString();
     const int offset = findOffset(node);
     QString ret;
     int name_offset = (tree[offset+0] << 24) + (tree[offset+1] << 16) +
                       (tree[offset+2] << 8) + (tree[offset+3] << 0);
     const short name_length = (names[name_offset+0] << 8) +
                               (names[name_offset+1] << 0);
     name_offset += 2;
     name_offset += 4; //jump past hash
     ret.resize(name_length);
     QChar *strData = ret.data();
     for(int i = 0; i < name_length*2; i+=2) {
         QChar c(names[name_offset+i+1], names[name_offset+i]);
         *strData = c;
         ++strData;
     }
     return ret;
 }
operator!=()
bool QResourceRoot::operator!= (const QResourceRoot & other) const inline
Definition at line 135 of file qresource.cpp.
     { return !operator==(other); }
operator==()
bool QResourceRoot::operator== (const QResourceRoot & other) const inline
Definition at line 133 of file qresource.cpp.
     { return tree == other.tree && names == other.names && payloads == other.payloads; }
setSource()
void QResourceRoot::setSource (const uchar * t, const uchar * n, const uchar * d) inline protected
Definition at line 141 of file qresource.cpp.
{
         tree = t;
         names = n;
         payloads = d;
     }
type()
virtual ResourceRootType QResourceRoot::type () const inline virtual
Reimplemented in QDynamicFileResourceRoot, and QDynamicBufferResourceRoot.
Definition at line 138 of file qresource.cpp.
Referenced by QResource::unregisterResource().
 { return Resource_Builtin; }
Properties
names
const uchar * QResourceRoot::names private
Definition at line 115 of file qresource.cpp.
Referenced by operator==().
payloads
const uchar * QResourceRoot::payloads private
Definition at line 115 of file qresource.cpp.
Referenced by operator==().
ref
QAtomicInt QResourceRoot::ref mutable
Definition at line 121 of file qresource.cpp.
Referenced by QResourcePrivate::clear(), QResourcePrivate::load(), qRegisterResourceData(), qUnregisterResourceData(), QResource::registerResource(), and QResource::unregisterResource().
tree
const uchar* QResourceRoot::tree private
Definition at line 115 of file qresource.cpp.
Referenced by operator==().
The documentation for this class was generated from the following file:
/src/corelib/io/qresource.cpp