Qt 4.8: QPlatformFontDatabase Class Reference
QPlatformFontDatabase Class Reference
The QPlatformFontDatabase class makes it possible to customize how fonts are discovered and how they are rendered.
#include <qplatformfontdatabase_qpa.h>
Public Functions
virtual QStringList addApplicationFont (const QByteArray &fontData, const QString &fileName)
Adds an application font described by the font contained supplied fontData or using the font contained in the file referenced by fileName.
virtual QStringList fallbacksForFamily (const QString family, const QFont::Style &style, const QFont::StyleHint &styleHint, const QUnicodeTables::Script &script) const
Returns a list of alternative fonts for the specified family and style and script using the styleHint given.
virtual QString fontDir () const
Returns the path to the font directory.
virtual QFontEngine * fontEngine (const QFontDef &fontDef, QUnicodeTables::Script script, void *handle)
Returns the font engine that can be used to render the font described by the font definition, fontDef, in the specified script.
virtual QFontEngine * fontEngine (const QByteArray &fontData, qreal pixelSize, QFont::HintingPreference hintingPreference)
virtual void populateFontDatabase ()
This function is called once at startup by Qts internal fontdatabase.
virtual void releaseHandle (void *handle)
Releases the font handle and deletes any associated data loaded from a file.
Static Public Functions
static void registerFont (const QString &familyname, const QString &foundryname, QFont::Weight weight, QFont::Style style, QFont::Stretch stretch, bool antialiased, bool scalable, int pixelSize, const QSupportedWritingSystems &writingSystems, void *handle)
Registers a font with the given set of attributes describing the font's foundry, family name, style and stretch information, pixel size, and supported writing systems.
static void registerQPF2Font (const QByteArray &dataArray, void *handle)
Registers the pre-rendered QPF2 font contained in the given dataArray.
Detailed Description
The QPlatformFontDatabase class makes it possible to customize how fonts are discovered and how they are rendered.
Since
4.8
QPlatformFontDatabase is the superclass which is intended to let platform implementations use native font handling.
Qt has its internal font database which it uses to discover available fonts on the user's system. To be able to populate this database subclass this class, and reimplement populateFontDatabase().
Use the function registerFont() to populate the internal font database.
Sometimes a specified font does not have the required glyphs; in such a case, the fallbackForFamily() function is called automatically to find alternative font families that can supply alternatives to the missing glyphs.
See also
QSupportedWritingSystems
Definition at line 86 of file qplatformfontdatabase_qpa.h.
Functions
addApplicationFont()
QStringList QPlatformFontDatabase::addApplicationFont (const QByteArray & fontData, const QString & fileName) virtual
Adds an application font described by the font contained supplied fontData or using the font contained in the file referenced by fileName.
Returns a list of family names, or an empty list if the font could not be added.
Note
The default implementation of this function does not add an application font. Subclasses should reimplement this function to perform the necessary loading and registration of fonts.
Reimplemented in QBasicUnixFontDatabase.
Definition at line 311 of file qplatformfontdatabase_qpa.cpp.
 {
     Q_UNUSED(fontData);
     Q_UNUSED(fileName);
     qWarning("This plugin does not support application fonts");
     return QStringList();
 }
fallbacksForFamily()
QStringList QPlatformFontDatabase::fallbacksForFamily (const QString family, const QFont::Style & style, const QFont::StyleHint & styleHint, const QUnicodeTables::Script & script) const virtual
Returns a list of alternative fonts for the specified family and style and script using the styleHint given.
Reimplemented in QBasicUnixFontDatabase, QCoreTextFontDatabase, and QFontconfigDatabase.
Definition at line 293 of file qplatformfontdatabase_qpa.cpp.
 {
     Q_UNUSED(family);
     Q_UNUSED(style);
     Q_UNUSED(styleHint);
     Q_UNUSED(script);
     return QStringList();
 }
fontDir()
QString QPlatformFontDatabase::fontDir () const virtual
Returns the path to the font directory.
The font directory is stored in the general Qt settings unless it has been overridden by the QT_QPA_FONTDIR environment variable.
When using builds of Qt that do not support settings, the QT_QPA_FONTDIR environment variable is the only way to specify the font directory.
Definition at line 338 of file qplatformfontdatabase_qpa.cpp.
Referenced by QBasicUnixFontDatabase::populateFontDatabase(), and populateFontDatabase().
 {
     QString fontpath = QString::fromLocal8Bit(qgetenv("QT_QPA_FONTDIR"));
     if (fontpath.isEmpty()) {
 #ifndef QT_NO_SETTINGS
         fontpath = QLibraryInfo::location(QLibraryInfo::LibrariesPath);
         fontpath += QLatin1String("/fonts");
 #endif
     }
     return fontpath;
 }
fontEngine() [1/2]
QFontEngine * QPlatformFontDatabase::fontEngine (const QFontDef & fontDef, QUnicodeTables::Script script, void * handle) virtual
Returns the font engine that can be used to render the font described by the font definition, fontDef, in the specified script.
Reimplemented in QBasicUnixFontDatabase, QCoreTextFontDatabase, and QFontconfigDatabase.
Definition at line 269 of file qplatformfontdatabase_qpa.cpp.
Referenced by loadSingleEngine().
 {
     Q_UNUSED(script);
     Q_UNUSED(handle);
     QByteArray *fileDataPtr = static_cast<QByteArray *>(handle);
     QFontEngineQPA *engine = new QFontEngineQPA(fontDef,*fileDataPtr);
     //qDebug() << fontDef.pixelSize << fontDef.weight << fontDef.style << fontDef.stretch << fontDef.styleHint << fontDef.styleStrategy << fontDef.family << script;
     return engine;
 }
fontEngine() [2/2]
QFontEngine * QPlatformFontDatabase::fontEngine (const QByteArray & fontData, qreal pixelSize, QFont::HintingPreference hintingPreference) virtual
Definition at line 279 of file qplatformfontdatabase_qpa.cpp.
 {
     Q_UNUSED(fontData);
     Q_UNUSED(pixelSize);
     Q_UNUSED(hintingPreference);
     qWarning("This plugin does not support font engines created directly from font data");
     return 0;
 }
populateFontDatabase()
void QPlatformFontDatabase::populateFontDatabase () virtual
This function is called once at startup by Qts internal fontdatabase.
Reimplement this function in a subclass for a convenient place to initialise the internal fontdatabase.
The default implementation looks in the fontDir() location and registers all qpf2 fonts.
Reimplemented in QBasicUnixFontDatabase, QCoreTextFontDatabase, and QFontconfigDatabase.
Definition at line 242 of file qplatformfontdatabase_qpa.cpp.
Referenced by QBasicUnixFontDatabase::populateFontDatabase().
 {
     QString fontpath = fontDir();
     if(!QFile::exists(fontpath)) {
         qFatal("QFontDatabase: Cannot find font directory %s - is Qt installed correctly?",
                qPrintable(fontpath));
     }
     QDir dir(fontpath);
     dir.setNameFilters(QStringList() << QLatin1String("*.qpf2"));
     dir.refresh();
     for (int i = 0; i < int(dir.count()); ++i) {
         const QByteArray fileName = QFile::encodeName(dir.absoluteFilePath(dir[i]));
         QFile file(QString::fromLocal8Bit(fileName));
         if (file.open(QFile::ReadOnly)) {
             const QByteArray fileData = file.readAll();
             QByteArray *fileDataPtr = new QByteArray(fileData);
             registerQPF2Font(fileData, fileDataPtr);
         }
     }
 }
registerFont()
void QPlatformFontDatabase::registerFont (const QString & familyName, const QString & foundryName, QFont::Weight weight, QFont::Style style, QFont::Stretch stretch, bool antialiased, bool scalable, int pixelSize, const QSupportedWritingSystems & writingSystems, void * usrPtr) static
Registers a font with the given set of attributes describing the font's foundry, family name, style and stretch information, pixel size, and supported writing systems.
Additional information about whether the font can be scaled and antialiased can also be provided.
The foundry name and font family are described by foundryName and familyName. The font weight (light, normal, bold, etc.), style (normal, oblique, italic) and stretch information (condensed, expanded, unstretched, etc.) are specified by weight, style and stretch.
Some fonts can be antialiased and scaled; scalable and antialiased can be set to true for fonts with these attributes. The intended pixel size of non-scalable fonts is specified by pixelSize; this value will be ignored for scalable fonts.
The writing systems supported by the font are specified by the writingSystems argument.
See also
registerQPF2Font()
Definition at line 124 of file qplatformfontdatabase_qpa.cpp.
Referenced by QBasicUnixFontDatabase::addTTFile(), QFontconfigDatabase::populateFontDatabase(), QCoreTextFontDatabase::populateFontDatabase(), and registerQPF2Font().
 {
     if (scalable)
         pixelSize = 0;
     qt_registerFont(familyname,foundryname,weight,style,stretch,antialiased,scalable,pixelSize,writingSystems,usrPtr);
 }
registerQPF2Font()
void QPlatformFontDatabase::registerQPF2Font (const QByteArray & dataArray, void * handle) static
Registers the pre-rendered QPF2 font contained in the given dataArray.
See also
registerFont()
Definition at line 61 of file qplatformfontdatabase_qpa.cpp.
Referenced by populateFontDatabase().
 {
     if (dataArray.size() == 0)
         return;
     const uchar *data = reinterpret_cast<const uchar *>(dataArray.constData());
     if (QFontEngineQPA::verifyHeader(data, dataArray.size())) {
         QString fontName = QFontEngineQPA::extractHeaderField(data, QFontEngineQPA::Tag_FontName).toString();
         int pixelSize = QFontEngineQPA::extractHeaderField(data, QFontEngineQPA::Tag_PixelSize).toInt();
         QVariant weight = QFontEngineQPA::extractHeaderField(data, QFontEngineQPA::Tag_Weight);
         QVariant style = QFontEngineQPA::extractHeaderField(data, QFontEngineQPA::Tag_Style);
         QByteArray writingSystemBits = QFontEngineQPA::extractHeaderField(data, QFontEngineQPA::Tag_WritingSystems).toByteArray();
         if (!fontName.isEmpty() && pixelSize) {
             QFont::Weight fontWeight = QFont::Normal;
             if (weight.type() == QVariant::Int || weight.type() == QVariant::UInt)
                 fontWeight = QFont::Weight(weight.toInt());
             QFont::Style fontStyle = static_cast<QFont::Style>(style.toInt());
             QSupportedWritingSystems writingSystems;
             for (int i = 0; i < writingSystemBits.count(); ++i) {
                 uchar currentByte = writingSystemBits.at(i);
                 for (int j = 0; j < 8; ++j) {
                     if (currentByte & 1)
                         writingSystems.setSupported(QFontDatabase::WritingSystem(i * 8 + j));
                     currentByte >>= 1;
                 }
             }
             QFont::Stretch stretch = QFont::Unstretched;
             registerFont(fontName,QString(),fontWeight,fontStyle,stretch,true,false,pixelSize,writingSystems,handle);
         }
     } else {
         qDebug() << "header verification of QPF2 font failed. maybe it is corrupt?";
     }
 }
releaseHandle()
void QPlatformFontDatabase::releaseHandle (void * handle) virtual
Releases the font handle and deletes any associated data loaded from a file.
Reimplemented in QBasicUnixFontDatabase.
Definition at line 323 of file qplatformfontdatabase_qpa.cpp.
Referenced by QtFontStyle::~QtFontStyle().
 {
     QByteArray *fileDataPtr = static_cast<QByteArray *>(handle);
     delete fileDataPtr;
 }
The documentation for this class was generated from the following files:
/src/gui/text/qplatformfontdatabase_qpa.h
/src/gui/text/qplatformfontdatabase_qpa.cpp