Qt 4.8: AVMediaObject Class Reference
AVMediaObject Class Reference
#include <avmediaobject.h>
Signals
void aboutToFinish ()
void bufferStatus (int)
void currentSourceChanged (const MediaSource &)
void finished ()
void hasVideoChanged (bool)
void metaDataChanged (const QMultiMap< QString, QString > &)
void prefinishMarkReached (qint32)
void seekableChanged (bool)
void stateChanged (Phonon::State newstate, Phonon::State oldstate)
void tick (qint64 time)
void totalTimeChanged (qint64 length)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
AVMediaObject (QObject *parent)
qint64 currentTime () const
QString errorString () const
Phonon::ErrorType errorType () const
void handlePlayerFinished ()
bool hasVideo () const
bool isSeekable () const
void pause ()
void play ()
qint32 prefinishMark () const
void seek (qint64 milliseconds)
void setAudioOutput (AVAudioOutput *audioOutput)
void setNextSource (const Phonon::MediaSource &source)
void setPrefinishMark (qint32 newPrefinishMark)
void setSource (const Phonon::MediaSource &source)
void setTickInterval (qint32 newTickInterval)
void setTransitionTime (qint32)
Phonon::MediaSource source () const
Phonon::State state () const
void stop ()
qint32 tickInterval () const
qint64 totalTime () const
qint32 transitionTime () const
~AVMediaObject ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void setVolume (qreal newVolume)
Private Functions
void changeState (Phonon::State state)
bool checkPlayer () const
Properties
AVMediaObjectPrivate * d
QString m_errorString
Phonon::ErrorType m_errorType
Phonon::MediaSource m_mediaSource
AVAudioOutput * m_output
Phonon::State m_state
qint32 m_tickInterval
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 54 of file avmediaobject.h.
Constructors and Destructors
AVMediaObject()
AVMediaObject::AVMediaObject (QObject * parent)
Definition at line 94 of file avmediaobject.mm.
     : QObject(parent),
       m_tickInterval(0),
       m_state(Phonon::LoadingState),
       m_errorType(Phonon::NoError),
       m_output(0),
       d(new AVMediaObjectPrivate(this))
 {
 }
~AVMediaObject()
AVMediaObject::~AVMediaObject ()
Definition at line 104 of file avmediaobject.mm.
 {
     if (m_state == Phonon::PlayingState)
         stop();
     [d->player release];
     delete d;
 }
Functions
aboutToFinish
void AVMediaObject::aboutToFinish () signal
Referenced by handlePlayerFinished().
bufferStatus
void AVMediaObject::bufferStatus (int) signal
changeState()
void AVMediaObject::changeState (Phonon::State state) private
Definition at line 112 of file avmediaobject.mm.
Referenced by handlePlayerFinished(), pause(), play(), setSource(), and stop().
 {
     if (m_state == state)
         return;
     Phonon::State oldState = m_state;
     m_state = state;
     emit stateChanged(m_state, oldState);
 }
checkPlayer()
bool AVMediaObject::checkPlayer () const private
Definition at line 121 of file avmediaobject.mm.
Referenced by currentTime(), pause(), play(), seek(), stop(), and totalTime().
 {
     if (!d->player) {
         m_errorType = Phonon::NormalError;
         m_errorString = tr("Media source has not been set.");
         return false;
     }
     return true;
 }
currentSourceChanged
void AVMediaObject::currentSourceChanged (const MediaSource &) signal
Referenced by setSource().
currentTime()
qint64 AVMediaObject::currentTime () const
Definition at line 188 of file avmediaobject.mm.
 {
     if (!checkPlayer())
         return 0;
     return (qint64)(d->player.currentTime * 1000);
 }
errorString()
QString AVMediaObject::errorString () const
Definition at line 200 of file avmediaobject.mm.
 {
     return m_errorString;
 }
errorType()
Phonon::ErrorType AVMediaObject::errorType () const
Definition at line 205 of file avmediaobject.mm.
 {
     return m_errorType;
 }
finished
void AVMediaObject::finished () signal
Referenced by handlePlayerFinished().
handlePlayerFinished()
void AVMediaObject::handlePlayerFinished ()
Definition at line 292 of file avmediaobject.mm.
 {
     emit aboutToFinish();
     changeState(Phonon::StoppedState);
     emit finished();
 }
hasVideo()
bool AVMediaObject::hasVideo () const
Definition at line 178 of file avmediaobject.mm.
 {
     return false;
 }
hasVideoChanged
void AVMediaObject::hasVideoChanged (bool) signal
isSeekable()
bool AVMediaObject::isSeekable () const
Definition at line 183 of file avmediaobject.mm.
 {
     return true;
 }
metaDataChanged
void AVMediaObject::metaDataChanged (const QMultiMap< QString, QString > &) signal
pause()
void AVMediaObject::pause ()
Definition at line 143 of file avmediaobject.mm.
 {
     if (!checkPlayer())
         return;
     [d->player pause];
     changeState(Phonon::PausedState);
 }
play()
void AVMediaObject::play ()
Definition at line 131 of file avmediaobject.mm.
 {
     if (!checkPlayer())
         return;
     if (![d->player play]) {
         m_errorType = Phonon::NormalError;
         m_errorString = tr("Failed to play media source.");
         return;
     }
     changeState(Phonon::PlayingState);
 }
prefinishMark()
qint32 AVMediaObject::prefinishMark () const
Definition at line 251 of file avmediaobject.mm.
 {
     // not implemented
     return 0;
 }
prefinishMarkReached
void AVMediaObject::prefinishMarkReached (qint32) signal
seek()
void AVMediaObject::seek (qint64 milliseconds)
Definition at line 160 of file avmediaobject.mm.
 {
     if (!checkPlayer())
         return;
     d->player.currentTime = milliseconds/1000.;
 }
seekableChanged
void AVMediaObject::seekableChanged (bool) signal
setAudioOutput()
void AVMediaObject::setAudioOutput (AVAudioOutput * audioOutput)
Definition at line 273 of file avmediaobject.mm.
Referenced by AVBackend::connectNodes(), and AVBackend::disconnectNodes().
 {
     if (m_output) {
         disconnect(m_output, SIGNAL(volumeChanged(qreal)), this, SLOT(setVolume(qreal)));
     }
     m_output = audioOutput;
     if (m_output) {
         connect(m_output, SIGNAL(volumeChanged(qreal)), this, SLOT(setVolume(qreal)));
         setVolume(m_output->volume());
     }
 }
setNextSource()
void AVMediaObject::setNextSource (const Phonon::MediaSource & source)
Definition at line 246 of file avmediaobject.mm.
 {
     setSource(source);
 }
setPrefinishMark()
void AVMediaObject::setPrefinishMark (qint32 newPrefinishMark)
Definition at line 257 of file avmediaobject.mm.
 {
     // not implemented
 }
setSource()
void AVMediaObject::setSource (const Phonon::MediaSource & source)
Definition at line 222 of file avmediaobject.mm.
Referenced by setNextSource().
 {
     if (d->player) {
         stop();
         [d->player release];
         d->player = 0;
     }
     m_mediaSource = source;
     NSString *urlString = [NSString stringWithCString:source.url().toEncoded().constData()
             encoding:NSASCIIStringEncoding];
     NSURL *url = [NSURL URLWithString:urlString];
     d->player = [[AVAudioPlayer alloc] initWithContentsOfURL:url error:NULL];
     if (!d->player) {
         m_errorString = tr("Failed to create player for '%1'").arg(source.url().toString());
         changeState(Phonon::ErrorState);
         return;
     }
     d->player.delegate = d->delegate;
     [d->player prepareToPlay];
     changeState(Phonon::StoppedState);
     emit currentSourceChanged(m_mediaSource);
     emit totalTimeChanged((qint64)(d->player.duration * 1000));
 }
setTickInterval()
void AVMediaObject::setTickInterval (qint32 newTickInterval)
Definition at line 172 of file avmediaobject.mm.
 {
     m_tickInterval = newTickInterval;
     //TODO
 }
setTransitionTime()
void AVMediaObject::setTransitionTime (qint32)
Definition at line 268 of file avmediaobject.mm.
 {
     // not implemented
 }
setVolume
void AVMediaObject::setVolume (qreal newVolume) private slot
Definition at line 285 of file avmediaobject.mm.
Referenced by setAudioOutput().
 {
     if (!d->player) // do nothing, will be set when player is created
         return;
     [d->player setVolume:qMin((float)1.0, (float)newVolume)];
 }
source()
Phonon::MediaSource AVMediaObject::source () const
Definition at line 217 of file avmediaobject.mm.
Referenced by setSource().
 {
     return m_mediaSource;
 }
state()
Phonon::State AVMediaObject::state () const
Definition at line 195 of file avmediaobject.mm.
Referenced by changeState().
 {
     return m_state;
 }
stateChanged
void AVMediaObject::stateChanged (Phonon::State newstate, Phonon::State oldstate) signal
Referenced by changeState().
stop()
void AVMediaObject::stop ()
Definition at line 151 of file avmediaobject.mm.
Referenced by setSource(), and ~AVMediaObject().
 {
     if (!checkPlayer())
         return;
     [d->player stop];
     d->player.currentTime = 0;
     changeState(Phonon::StoppedState);
 }
tick
void AVMediaObject::tick (qint64 time) signal
tickInterval()
qint32 AVMediaObject::tickInterval () const
Definition at line 167 of file avmediaobject.mm.
 {
     return m_tickInterval;
 }
totalTime()
qint64 AVMediaObject::totalTime () const
Definition at line 210 of file avmediaobject.mm.
 {
     if (!checkPlayer())
         return 0;
     return d->player.duration;
 }
totalTimeChanged
void AVMediaObject::totalTimeChanged (qint64 length) signal
Referenced by setSource().
transitionTime()
qint32 AVMediaObject::transitionTime () const
Definition at line 262 of file avmediaobject.mm.
 {
     // not implemented
     return 0;
 }
Properties
d
AVMediaObjectPrivate* AVMediaObject::d private
Definition at line 118 of file avmediaobject.h.
Referenced by checkPlayer(), currentTime(), pause(), play(), seek(), setSource(), setVolume(), stop(), totalTime(), and ~AVMediaObject().
m_errorString
QString AVMediaObject::m_errorString mutable private
Definition at line 113 of file avmediaobject.h.
Referenced by checkPlayer(), errorString(), play(), and setSource().
m_errorType
Phonon::ErrorType AVMediaObject::m_errorType mutable private
Definition at line 114 of file avmediaobject.h.
Referenced by checkPlayer(), errorType(), and play().
m_mediaSource
Phonon::MediaSource AVMediaObject::m_mediaSource private
Definition at line 115 of file avmediaobject.h.
Referenced by setSource(), and source().
m_output
AVAudioOutput* AVMediaObject::m_output private
Definition at line 117 of file avmediaobject.h.
Referenced by setAudioOutput().
m_state
Phonon::State AVMediaObject::m_state private
Definition at line 112 of file avmediaobject.h.
Referenced by changeState(), state(), and ~AVMediaObject().
m_tickInterval
qint32 AVMediaObject::m_tickInterval private
Definition at line 111 of file avmediaobject.h.
Referenced by setTickInterval(), and tickInterval().
The documentation for this class was generated from the following files:
/src/plugins/platforms/uikit/phonon_av/avmediaobject.h
/src/plugins/platforms/uikit/phonon_av/avmediaobject.mm