Qt 4.8: QProgressDialog Class Reference
QProgressDialog Class Reference
The QProgressDialog class provides feedback on the progress of a slow operation.
#include <qprogressdialog.h>
Public Slots
void cancel ()
Resets the progress dialog.
void reset ()
Resets the progress dialog.
void setCancelButtonText (const QString &text)
Sets the cancel button's text to cancelButtonText.
void setLabelText (const QString &text)
void setMaximum (int maximum)
void setMinimum (int minimum)
void setMinimumDuration (int ms)
void setRange (int minimum, int maximum)
Sets the progress dialog's minimum and maximum values to minimum and maximum, respectively.
void setValue (int progress)
Public Slots inherited from QDialog
virtual void accept ()
Hides the modal dialog and sets the result code to Accepted.
virtual void done (int)
Closes the dialog and sets its result code to r.
int exec ()
Shows the dialog as a modal dialog, blocking until the user closes it.
void open ()
Shows the dialog as a window modal dialog, returning immediately.
virtual void reject ()
Hides the modal dialog and sets the result code to Rejected.
void showExtension (bool)
If showIt is true, the dialog's extension is shown; otherwise the extension is hidden.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void canceled ()
This signal is emitted when the cancel button is clicked.
Signals inherited from QDialog
void accepted ()
This signal is emitted when the dialog has been accepted either by the user or by calling accept() or done() with the QDialog::Accepted argument.
void finished (int result)
This signal is emitted when the dialog's result code has been set, either by the user or by calling done(), accept(), or reject().
void rejected ()
This signal is emitted when the dialog has been rejected either by the user or by calling reject() or done() with the QDialog::Rejected argument.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool autoClose () const
bool autoReset () const
QString labelText () const
int maximum () const
int minimum () const
int minimumDuration () const
void open (QObject *receiver, const char *member)
Opens the dialog and connects its accepted() signal to the slot specified by receiver and member.
QProgressDialog (QWidget *parent=0, Qt::WindowFlags flags=0)
Constructs a progress dialog.
QProgressDialog (const QString &labelText, const QString &cancelButtonText, int minimum, int maximum, QWidget *parent=0, Qt::WindowFlags flags=0)
Constructs a progress dialog.
void setAutoClose (bool close)
void setAutoReset (bool reset)
void setBar (QProgressBar *bar)
Sets the progress bar widget to bar.
void setCancelButton (QPushButton *button)
Sets the cancel button to the push button, cancelButton.
void setLabel (QLabel *label)
Sets the label to label.
QSize sizeHint () const
Returns a size that fits the contents of the progress dialog.
int value () const
bool wasCanceled () const
~QProgressDialog ()
Destroys the progress dialog.
Public Functions inherited from QDialog
QWidget * extension () const
Returns the dialog's extension or 0 if no extension has been defined.
bool isSizeGripEnabled () const
QSize minimumSizeHint () const
Reimplemented Function
Qt::Orientation orientation () const
Returns the dialog's extension orientation.
QDialog (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a dialog with parent parent.
int result () const
In general returns the modal dialog's result code, Accepted or Rejected.
void setExtension (QWidget *extension)
Sets the widget, extension, to be the dialog's extension, deleting any previous extension.
void setModal (bool modal)
void setOrientation (Qt::Orientation orientation)
If orientation is Qt::Horizontal, the extension will be displayed to the right of the dialog's main area.
void setResult (int r)
Sets the modal dialog's result code to i.
void setSizeGripEnabled (bool)
void setVisible (bool visible)
Reimplemented Function
~QDialog ()
Destroys the QDialog, deleting all its children.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Slots
void forceShow ()
Shows the dialog if it is still hidden after the algorithm has been started and minimumDuration milliseconds have passed.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
void changeEvent (QEvent *event)
Reimplemented Function
void closeEvent (QCloseEvent *event)
Reimplemented Function
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void showEvent (QShowEvent *event)
Reimplemented Function
Protected Functions inherited from QDialog
void adjustPosition (QWidget *)
void contextMenuEvent (QContextMenuEvent *)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
Reimplemented Function
QDialog (QDialogPrivate &, QWidget *parent, Qt::WindowFlags f=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool autoClose
whether the dialog gets hidden by reset()
bool autoReset
whether the progress dialog calls reset() as soon as value() equals maximum()
QString labelText
the label's text
int maximum
the highest value represented by the progress bar
int minimum
the lowest value represented by the progress bar
int minimumDuration
the time that must pass before the dialog appears
int value
the current amount of progress made.
bool wasCanceled
whether the dialog was canceled
Additional Inherited Members
Public Types inherited from QDialog
enum DialogCode { Rejected, Accepted }
The value returned by a modal dialog.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QProgressDialog class provides feedback on the progress of a slow operation.
A progress dialog is used to give the user an indication of how long an operation is going to take, and to demonstrate that the application has not frozen. It can also give the user an opportunity to abort the operation.
A common problem with progress dialogs is that it is difficult to know when to use them; operations take different amounts of time on different hardware. QProgressDialog offers a solution to this problem: it estimates the time the operation will take (based on time for steps), and only shows itself if that estimate is beyond minimumDuration() (4 seconds by default).
Use setMinimum() and setMaximum() or the constructor to set the number of "steps" in the operation and call setValue() as the operation progresses. The number of steps can be chosen arbitrarily. It can be the number of files copied, the number of bytes received, the number of iterations through the main loop of your algorithm, or some other suitable unit. Progress starts at the value set by setMinimum(), and the progress dialog shows that the operation has finished when you call setValue() with the value set by setMaximum() as its argument.
The dialog automatically resets and hides itself at the end of the operation. Use setAutoReset() and setAutoClose() to change this behavior. Note that if you set a new maximum (using setMaximum() or setRange()) that equals your current value(), the dialog will not close regardless.
There are two ways of using QProgressDialog: modal and modeless.
Compared to a modeless QProgressDialog, a modal QProgressDialog is simpler to use for the programmer. Do the operation in a loop, call setValue() at intervals, and check for cancellation with wasCanceled(). For example:
    QProgressDialog progress("Copying files...", "Abort Copy", 0, numFiles, this);
    progress.setWindowModality(Qt::WindowModal);
    for (int i = 0; i < numFiles; i++) {
        progress.setValue(i);
        if (progress.wasCanceled())
            break;
        //... copy one file
    }
    progress.setValue(numFiles);
A modeless progress dialog is suitable for operations that take place in the background, where the user is able to interact with the application. Such operations are typically based on QTimer (or QObject::timerEvent()), QSocketNotifier, or QUrlOperator; or performed in a separate thread. A QProgressBar in the status bar of your main window is often an alternative to a modeless progress dialog.
You need to have an event loop to be running, connect the canceled() signal to a slot that stops the operation, and call setValue() at intervals. For example:
// Operation constructor
Operation::Operation(QObject *parent)
    : QObject(parent), steps(0)
{
    pd = new QProgressDialog("Operation in progress.", "Cancel", 0, 100);
    connect(pd, SIGNAL(canceled()), this, SLOT(cancel()));
    t = new QTimer(this);
    connect(t, SIGNAL(timeout()), this, SLOT(perform()));
    t->start(0);
}
void Operation::perform()
{
    pd->setValue(steps);
    //... perform one percent of the operation
    steps++;
    if (steps > pd->maximum())
        t->stop();
}
void Operation::cancel()
{
    t->stop();
    //... cleanup
}
In both modes the progress dialog may be customized by replacing the child widgets with custom widgets by using setLabel(), setBar(), and setCancelButton(). The functions setLabelText() and setCancelButtonText() set the texts shown.
A progress dialog shown in the Plastique widget style.
See also
QDialog, QProgressBar, {fowler}{GUI Design Handbook: Progress Indicator}, {Find Files Example}, {Pixelator Example}
Definition at line 61 of file qprogressdialog.h.
Constructors and Destructors
QProgressDialog() [1/2]
QProgressDialog::QProgressDialog (QWidget * parent = 0, Qt::WindowFlags f = 0) explicit
Constructs a progress dialog.
Default settings:
The label text is empty.
The cancel button text is (translated) "Cancel".
minimum is 0;
maximum is 100
The parent argument is dialog's parent widget. The widget flags, f, are passed to the QDialog::QDialog() constructor.
See also
setLabelText(), setCancelButtonText(), setCancelButton(), setMinimum(), setMaximum()
Definition at line 308 of file qprogressdialog.cpp.
     : QDialog(*(new QProgressDialogPrivate), parent, f)
 {
     Q_D(QProgressDialog);
     d->useDefaultCancelText = true;
     d->init(QString::fromLatin1(""), QString(), 0, 100);
 }
QProgressDialog() [2/2]
QProgressDialog::QProgressDialog (const QString & labelText, const QString & cancelButtonText, int minimum, int maximum, QWidget * parent = 0, Qt::WindowFlags f = 0)
Constructs a progress dialog.
The labelText is the text used to remind the user what is progressing.
The cancelButtonText is the text to display on the cancel button. If QString() is passed then no cancel button is shown.
The minimum and maximum is the number of steps in the operation for which this progress dialog shows progress. For example, if the operation is to examine 50 files, this value minimum value would be 0, and the maximum would be 50. Before examining the first file, call setValue(0). As each file is processed call setValue(1), setValue(2), etc., finally calling setValue(50) after examining the last file.
The parent argument is the dialog's parent widget. The parent, parent, and widget flags, f, are passed to the QDialog::QDialog() constructor.
See also
setLabelText(), setLabel(), setCancelButtonText(), setCancelButton(), setMinimum(), setMaximum()
Definition at line 338 of file qprogressdialog.cpp.
     : QDialog(*(new QProgressDialogPrivate), parent, f)
 {
     Q_D(QProgressDialog);
     d->init(labelText, cancelButtonText, minimum, maximum);
 }
~QProgressDialog()
QProgressDialog::~QProgressDialog ()
Destroys the progress dialog.
Definition at line 353 of file qprogressdialog.cpp.
 {
 }
Functions
autoClose()
bool QProgressDialog::autoClose () const
Referenced by setAutoClose().
autoReset()
bool QProgressDialog::autoReset () const
Referenced by setAutoReset().
cancel
void QProgressDialog::cancel () slot
Resets the progress dialog.
wasCanceled() becomes true until the progress dialog is reset. The progress dialog becomes hidden.
Definition at line 653 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->forceHide = true;
     reset();
     d->forceHide = false;
     d->cancellation_flag = true;
 }
canceled
void QProgressDialog::canceled () signal
This signal is emitted when the cancel button is clicked.
It is connected to the cancel() slot by default.
See also
wasCanceled()
Referenced by closeEvent(), open(), and setCancelButton().
changeEvent()
void QProgressDialog::changeEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 780 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     if (ev->type() == QEvent::StyleChange) {
         d->layout();
     } else if (ev->type() == QEvent::LanguageChange) {
         d->retranslateStrings();
     }
     QDialog::changeEvent(ev);
 }
closeEvent()
void QProgressDialog::closeEvent (QCloseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 829 of file qprogressdialog.cpp.
 {
     emit canceled();
     QDialog::closeEvent(e);
 }
forceShow
void QProgressDialog::forceShow () protected slot
Shows the dialog if it is still hidden after the algorithm has been started and minimumDuration milliseconds have passed.
See also
setMinimumDuration()
Definition at line 904 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->forceTimer->stop();
     if (d->shown_once || d->cancellation_flag)
         return;
     show();
     d->shown_once = true;
 }
labelText()
QString QProgressDialog::labelText () const
Referenced by setLabel().
maximum()
int QProgressDialog::maximum () const
Referenced by setBar(), and setValue().
minimum()
int QProgressDialog::minimum () const
Referenced by setMaximum(), and setValue().
minimumDuration()
int QProgressDialog::minimumDuration () const
Referenced by setMinimumDuration().
open()
void QProgressDialog::open (QObject * receiver, const char * member)
Opens the dialog and connects its accepted() signal to the slot specified by receiver and member.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The signal will be disconnected from the slot when the dialog is closed.
Definition at line 927 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     connect(this, SIGNAL(canceled()), receiver, member);
     d->receiverToDisconnectOnClose = receiver;
     d->memberToDisconnectOnClose = member;
     QDialog::open();
 }
reset
void QProgressDialog::reset () slot
Resets the progress dialog.
The progress dialog becomes hidden if autoClose() is true.
See also
setAutoClose(), setAutoReset()
Definition at line 622 of file qprogressdialog.cpp.
Referenced by cancel(), and setValue().
 {
     Q_D(QProgressDialog);
 #ifndef QT_NO_CURSOR
     if (value() >= 0) {
         if (parentWidget())
             parentWidget()->setCursor(d->parentCursor);
     }
 #endif
     if (d->autoClose || d->forceHide)
         hide();
     d->bar->reset();
     d->cancellation_flag = false;
     d->shown_once = false;
     d->forceTimer->stop();
     /*
         I wish we could disconnect the user slot provided to open() here but
         unfortunately reset() is usually called before the slot has been invoked.
         (reset() is itself invoked when canceled() is emitted.)
     */
     if (d->receiverToDisconnectOnClose)
         QMetaObject::invokeMethod(this, "_q_disconnectOnClose", Qt::QueuedConnection);
 }
resizeEvent()
void QProgressDialog::resizeEvent (QResizeEvent *) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 771 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->layout();
 }
setAutoClose()
void QProgressDialog::setAutoClose (bool close)
Definition at line 871 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->autoClose = close;
 }
setAutoReset()
void QProgressDialog::setAutoReset (bool reset)
Definition at line 847 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->autoReset = b;
 }
setBar()
void QProgressDialog::setBar (QProgressBar * bar)
Sets the progress bar widget to bar.
The progress dialog resizes to fit. The progress dialog takes ownership of the progress bar which will be deleted when necessary, so do not use a progress bar allocated on the stack.
Definition at line 513 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     if (!bar) {
         qWarning("QProgressDialog::setBar: Cannot set a null progress bar");
         return;
     }
 #ifndef QT_NO_DEBUG
     if (value() > 0)
         qWarning("QProgressDialog::setBar: Cannot set a new progress bar "
                   "while the old one is active");
 #endif
     delete d->bar;
     d->bar = bar;
     int w = qMax(isVisible() ? width() : 0, sizeHint().width());
     int h = qMax(isVisible() ? height() : 0, sizeHint().height());
     resize(w, h);
 }
setCancelButton()
void QProgressDialog::setCancelButton (QPushButton * cancelButton)
Sets the cancel button to the push button, cancelButton.
The progress dialog takes ownership of this button which will be deleted when necessary, so do not pass the address of an object that is on the stack, i.e. use new() to create the button. If 0 is passed then no cancel button will be shown.
See also
setCancelButtonText()
Definition at line 438 of file qprogressdialog.cpp.
Referenced by setCancelButtonText().
 {
     Q_D(QProgressDialog);
     delete d->cancel;
     d->cancel = cancelButton;
     if (cancelButton) {
         if (cancelButton->parentWidget() == this) {
             cancelButton->hide(); // until we resize
         } else {
             cancelButton->setParent(this, 0);
         }
         connect(d->cancel, SIGNAL(clicked()), this, SIGNAL(canceled()));
 #ifndef QT_NO_SHORTCUT
         d->escapeShortcut = new QShortcut(Qt::Key_Escape, this, SIGNAL(canceled()));
 #endif
     } else {
 #ifndef QT_NO_SHORTCUT
         delete d->escapeShortcut;
         d->escapeShortcut = 0;
 #endif
     }
     int w = qMax(isVisible() ? width() : 0, sizeHint().width());
     int h = qMax(isVisible() ? height() : 0, sizeHint().height());
     resize(w, h);
     if (cancelButton)
 #if !defined(QT_SOFTKEYS_ENABLED)
         cancelButton->show();
 #else
     {
         d->cancelAction = new QAction(cancelButton->text(), cancelButton);
         d->cancelAction->setSoftKeyRole(QAction::NegativeSoftKey);
         connect(d->cancelAction, SIGNAL(triggered()), this, SIGNAL(canceled()));
         addAction(d->cancelAction);
     }
 #endif
 }
setCancelButtonText
void QProgressDialog::setCancelButtonText (const QString & cancelButtonText) slot
Sets the cancel button's text to cancelButtonText.
If the text is set to QString() then it will cause the cancel button to be hidden and deleted.
See also
setCancelButton()
Definition at line 483 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->useDefaultCancelText = false;
     if (!cancelButtonText.isNull()) {
         if (d->cancel) {
             d->cancel->setText(cancelButtonText);
 #ifdef QT_SOFTKEYS_ENABLED
             d->cancelAction->setText(cancelButtonText);
 #endif
         } else {
             setCancelButton(new QPushButton(cancelButtonText, this));
         }
     } else {
         setCancelButton(0);
     }
     int w = qMax(isVisible() ? width() : 0, sizeHint().width());
     int h = qMax(isVisible() ? height() : 0, sizeHint().height());
     resize(w, h);
 }
setLabel()
void QProgressDialog::setLabel (QLabel * label)
Sets the label to label.
The progress dialog resizes to fit. The label becomes owned by the progress dialog and will be deleted when necessary, so do not pass the address of an object on the stack.
See also
setLabelText()
Definition at line 378 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     delete d->label;
     d->label = label;
     if (label) {
         if (label->parentWidget() == this) {
             label->hide(); // until we resize
         } else {
             label->setParent(this, 0);
         }
     }
     int w = qMax(isVisible() ? width() : 0, sizeHint().width());
     int h = qMax(isVisible() ? height() : 0, sizeHint().height());
     resize(w, h);
     if (label)
         label->show();
 }
setLabelText
void QProgressDialog::setLabelText (const QString & text) slot
Definition at line 416 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     if (d->label) {
         d->label->setText(text);
         int w = qMax(isVisible() ? width() : 0, sizeHint().width());
         int h = qMax(isVisible() ? height() : 0, sizeHint().height());
         resize(w, h);
     }
 }
setMaximum
void QProgressDialog::setMaximum (int maximum) slot
Definition at line 566 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->bar->setMaximum(maximum);
 }
setMinimum
void QProgressDialog::setMinimum (int minimum) slot
Definition at line 590 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->bar->setMinimum(minimum);
 }
setMinimumDuration
void QProgressDialog::setMinimumDuration (int ms) slot
Definition at line 808 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->showTime = ms;
     if (d->bar->value() == 0) {
         d->forceTimer->stop();
         d->forceTimer->start(ms);
     }
 }
setRange
void QProgressDialog::setRange (int minimum, int maximum) slot
Sets the progress dialog's minimum and maximum values to minimum and maximum, respectively.
If maximum is smaller than minimum, minimum becomes the only legal value.
If the current value falls outside the new range, the progress dialog is reset with reset().
See also
minimum, maximum
Definition at line 608 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     d->bar->setRange(minimum, maximum);
 }
setValue
void QProgressDialog::setValue (int progress) slot
Definition at line 689 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     if (progress == d->bar->value()
         || (d->bar->value() == -1 && progress == d->bar->maximum()))
         return;
     d->bar->setValue(progress);
     if (d->shown_once) {
         if (isModal())
             QApplication::processEvents();
     } else {
         if (progress == 0) {
             d->starttime.start();
             d->forceTimer->start(d->showTime);
             return;
         } else {
             bool need_show;
             int elapsed = d->starttime.elapsed();
             if (elapsed >= d->showTime) {
                 need_show = true;
             } else {
                 if (elapsed > minWaitTime) {
                     int estimate;
                     int totalSteps = maximum() - minimum();
                     int myprogress = progress - minimum();
                     if (myprogress == 0) myprogress = 1;
                     if ((totalSteps - myprogress) >= INT_MAX / elapsed)
                         estimate = (totalSteps - myprogress) / myprogress * elapsed;
                     else
                         estimate = elapsed * (totalSteps - myprogress) / myprogress;
                     need_show = estimate >= d->showTime;
                 } else {
                     need_show = false;
                 }
             }
             if (need_show) {
                 int w = qMax(isVisible() ? width() : 0, sizeHint().width());
                 int h = qMax(isVisible() ? height() : 0, sizeHint().height());
                 resize(w, h);
                 show();
                 d->shown_once = true;
             }
         }
 #ifdef Q_WS_MAC
         QApplication::flush();
 #endif
     }
     if (progress == d->bar->maximum() && d->autoReset)
         reset();
 }
showEvent()
void QProgressDialog::showEvent (QShowEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 887 of file qprogressdialog.cpp.
 {
     Q_D(QProgressDialog);
     QDialog::showEvent(e);
     int w = qMax(isVisible() ? width() : 0, sizeHint().width());
     int h = qMax(isVisible() ? height() : 0, sizeHint().height());
     resize(w, h);
     d->forceTimer->stop();
 }
sizeHint()
QSize QProgressDialog::sizeHint () const virtual
Returns a size that fits the contents of the progress dialog.
The progress dialog resizes itself as required, so you should not need to call this yourself.em>Reimplemented Function
Reimplemented from QDialog.
Definition at line 749 of file qprogressdialog.cpp.
Referenced by setBar(), setCancelButton(), setCancelButtonText(), setLabel(), setLabelText(), setValue(), and showEvent().
value()
int QProgressDialog::value () const
Referenced by cancel(), reset(), and setBar().
wasCanceled()
bool QProgressDialog::wasCanceled () const
Referenced by setBar().
Properties
autoClose
bool QProgressDialog::autoClose private
whether the dialog gets hidden by reset()
The default is true.
See also
setAutoReset()
Definition at line 70 of file qprogressdialog.h.
autoReset
bool QProgressDialog::autoReset private
whether the progress dialog calls reset() as soon as value() equals maximum()
The default is true.
See also
setAutoClose()
Definition at line 69 of file qprogressdialog.h.
labelText
QString QProgressDialog::labelText private
the label's text
The default text is an empty string.
Definition at line 72 of file qprogressdialog.h.
maximum
int QProgressDialog::maximum private
the highest value represented by the progress bar
The default is 0.
See also
minimum, setRange()
Definition at line 67 of file qprogressdialog.h.
minimum
int QProgressDialog::minimum private
the lowest value represented by the progress bar
The default is 0.
See also
maximum, setRange()
Definition at line 66 of file qprogressdialog.h.
minimumDuration
int QProgressDialog::minimumDuration private
the time that must pass before the dialog appears
If the expected duration of the task is less than the minimumDuration, the dialog will not appear at all. This prevents the dialog popping up for tasks that are quickly over. For tasks that are expected to exceed the minimumDuration, the dialog will pop up after the minimumDuration time or as soon as any progress is set.
If set to 0, the dialog is always shown as soon as any progress is set. The default is 4000 milliseconds.
Definition at line 71 of file qprogressdialog.h.
value
QProgressDialog::value private
the current amount of progress made.
For the progress dialog to work as expected, you should initially set this property to 0 and finally set it to QProgressDialog::maximum(); you can call setValue() any number of times in-between.
Warning
If the progress dialog is modal (see QProgressDialog::QProgressDialog()), setValue() calls QApplication::processEvents(), so take care that this does not cause undesirable re-entrancy in your code. For example, don't use a QProgressDialog inside a paintEvent()!
See also
minimum, maximum
Definition at line 68 of file qprogressdialog.h.
wasCanceled
bool QProgressDialog::wasCanceled private
whether the dialog was canceled
Definition at line 65 of file qprogressdialog.h.
The documentation for this class was generated from the following files:
/src/gui/dialogs/qprogressdialog.h
/src/gui/dialogs/qprogressdialog.cpp