Qt 4.8: QGraphicsItem Class Reference
QGraphicsItem Class Reference abstract
The QGraphicsItem class is the base class for all graphical items in a QGraphicsScene.
#include <qgraphicsitem.h>
Public Types
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Functions
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
virtual QRectF boundingRect () const =0
This pure virtual function defines the outer bounds of the item as a rectangle; all painting must be restricted to inside an item's bounding rect.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
virtual void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)=0
This function, which is usually called by QGraphicsView, paints the contents of an item in local coordinates.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
virtual QPainterPath shape () const
Returns the shape of this item as a QPainterPath in local coordinates.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
virtual int type () const
Returns the type of an item as an int.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Protected Types
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Functions
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void focusInEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus in events for this item.
virtual void focusOutEvent (QFocusEvent *event)
This event handler, for event event, can be reimplemented to receive focus out events for this item.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover move events for this item.
virtual void inputMethodEvent (QInputMethodEvent *event)
This event handler, for event event, can be reimplemented to receive input method events for this item.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
This method is only relevant for input items.
virtual QVariant itemChange (GraphicsItemChange change, const QVariant &value)
This virtual function is called by QGraphicsItem to notify custom items that some part of the item's state changes.
virtual void keyPressEvent (QKeyEvent *event)
This event handler, for event event, can be reimplemented to receive key press events for this item.
virtual void keyReleaseEvent (QKeyEvent *event)
This event handler, for event event, can be reimplemented to receive key release events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEvent (QEvent *event)
This virtual function receives events to this item.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Protected Variables
QScopedPointer< QGraphicsItemPrivate > d_ptr
Friends
class ::tst_QGraphicsItem
class QGestureManager
class QGraphicsItemEffectSourcePrivate
class QGraphicsItemGroup
class QGraphicsObject
class QGraphicsProxyWidgetPrivate
class QGraphicsScene
class QGraphicsSceneBspTree
class QGraphicsSceneBspTreeIndex
class QGraphicsSceneBspTreeIndexPrivate
class QGraphicsSceneFindItemBspTreeVisitor
class QGraphicsSceneIndex
class QGraphicsSceneIndexPrivate
class QGraphicsScenePrivate
class QGraphicsTransformPrivate
class QGraphicsView
class QGraphicsViewPrivate
class QGraphicsWidget
class QGraphicsWidgetPrivate
bool qt_closestItemFirst (const QGraphicsItem *, const QGraphicsItem *)
Returns true if item1 is on top of item2.
bool qt_closestLeaf (const QGraphicsItem *, const QGraphicsItem *)
Related Functions
(Note that these are not member functions.)
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
The QGraphicsItem class is the base class for all graphical items in a QGraphicsScene.
Since
4.2
It provides a light-weight foundation for writing your own custom items. This includes defining the item's geometry, collision detection, its painting implementation and item interaction through its event handlers. QGraphicsItem is part of the Graphics View Framework
For convenience, Qt provides a set of standard graphics items for the most common shapes. These are:
QGraphicsEllipseItem provides an ellipse item
QGraphicsLineItem provides a line item
QGraphicsPathItem provides an arbitrary path item
QGraphicsPixmapItem provides a pixmap item
QGraphicsPolygonItem provides a polygon item
QGraphicsRectItem provides a rectangular item
QGraphicsSimpleTextItem provides a simple text label item
QGraphicsTextItem provides an advanced text browser item
All of an item's geometric information is based on its local coordinate system. The item's position, pos(), is the only function that does not operate in local coordinates, as it returns a position in parent coordinates. The Graphics View Coordinate System describes the coordinate system in detail.
You can set whether an item should be visible (i.e., drawn, and accepting events), by calling setVisible(). Hiding an item will also hide its children. Similarly, you can enable or disable an item by calling setEnabled(). If you disable an item, all its children will also be disabled. By default, items are both visible and enabled. To toggle whether an item is selected or not, first enable selection by setting the ItemIsSelectable flag, and then call setSelected(). Normally, selection is toggled by the scene, as a result of user interaction.
To write your own graphics item, you first create a subclass of QGraphicsItem, and then start by implementing its two pure virtual public functions: boundingRect(), which returns an estimate of the area painted by the item, and paint(), which implements the actual painting. For example:
class SimpleItem : public QGraphicsItem
{
public:
    QRectF boundingRect() const
    {
        qreal penWidth = 1;
        return QRectF(-10 - penWidth / 2, -10 - penWidth / 2,
                      20 + penWidth, 20 + penWidth);
    }
    void paint(QPainter *painter, const QStyleOptionGraphicsItem *option,
               QWidget *widget)
    {
        painter->drawRoundedRect(-10, -10, 20, 20, 5, 5);
    }
};
The boundingRect() function has many different purposes. QGraphicsScene bases its item index on boundingRect(), and QGraphicsView uses it both for culling invisible items, and for determining the area that needs to be recomposed when drawing overlapping items. In addition, QGraphicsItem's collision detection mechanisms use boundingRect() to provide an efficient cut-off. The fine grained collision algorithm in collidesWithItem() is based on calling shape(), which returns an accurate outline of the item's shape as a QPainterPath.
QGraphicsScene expects all items boundingRect() and shape() to remain unchanged unless it is notified. If you want to change an item's geometry in any way, you must first call prepareGeometryChange() to allow QGraphicsScene to update its bookkeeping.
Collision detection can be done in two ways:
Reimplement shape() to return an accurate shape for your item, and rely on the default implementation of collidesWithItem() to do shape-shape intersection. This can be rather expensive if the shapes are complex.
Reimplement collidesWithItem() to provide your own custom item and shape collision algorithm.
The contains() function can be called to determine whether the item contains a point or not. This function can also be reimplemented by the item. The default behavior of contains() is based on calling shape().
Items can contain other items, and also be contained by other items. All items can have a parent item and a list of children. Unless the item has no parent, its position is in parent coordinates (i.e., the parent's local coordinates). Parent items propagate both their position and their transformation to all children.
Transformations
QGraphicsItem supports projective transformations in addition to its base position, pos(). There are several ways to change an item's transformation. For simple transformations, you can call either of the convenience functions setRotation() or setScale(), or you can pass any transformation matrix to setTransform(). For advanced transformation control you also have the option of setting several combined transformations by calling setTransformations().
Item transformations accumulate from parent to child, so if both a parent and child item are rotated 90 degrees, the child's total transformation will be 180 degrees. Similarly, if the item's parent is scaled to 2x its original size, its children will also be twice as large. An item's transformation does not affect its own local geometry; all geometry functions (e.g., contains(), update(), and all the mapping functions) still operate in local coordinates. For convenience, QGraphicsItem provides the functions sceneTransform(), which returns the item's total transformation matrix (including its position and all parents' positions and transformations), and scenePos(), which returns its position in scene coordinates. To reset an item's matrix, call resetTransform().
Certain transformation operations produce a different outcome depending on the order in which they are applied. For example, if you scale an transform, and then rotate it, you may get a different result than if the transform was rotated first. However, the order you set the transformation properties on QGraphicsItem does not affect the resulting transformation; QGraphicsItem always applies the properties in a fixed, defined order:
The item's base transform is applied (transform())
The item's transformations list is applied in order (transformations())
The item is rotated relative to its transform origin point (rotation(), transformOriginPoint())
The item is scaled relative to its transform origin point (scale(), transformOriginPoint())
Painting
The paint() function is called by QGraphicsView to paint the item's contents. The item has no background or default fill of its own; whatever is behind the item will shine through all areas that are not explicitly painted in this function. You can call update() to schedule a repaint, optionally passing the rectangle that needs a repaint. Depending on whether or not the item is visible in a view, the item may or may not be repainted; there is no equivalent to QWidget::repaint() in QGraphicsItem.
Items are painted by the view, starting with the parent items and then drawing children, in ascending stacking order. You can set an item's stacking order by calling setZValue(), and test it by calling zValue(), where items with low z-values are painted before items with high z-values. Stacking order applies to sibling items; parents are always drawn before their children.
Sorting
All items are drawn in a defined, stable order, and this same order decides which items will receive mouse input first when you click on the scene. Normally you don't have to worry about sorting, as the items follow a "natural order", following the logical structure of the scene.
An item's children are stacked on top of the parent, and sibling items are stacked by insertion order (i.e., in the same order that they were either added to the scene, or added to the same parent). If you add item A, and then B, then B will be on top of A. If you then add C, the items' stacking order will be A, then B, then C.
This example shows the stacking order of all limbs of the robot from the Drag and Drop Robot example. The torso is the root item (all other items are children or descendants of the torso), so it is drawn first. Next, the head is drawn, as it is the first item in the torso's list of children. Then the upper left arm is drawn. As the lower arm is a child of the upper arm, the lower arm is then drawn, followed by the upper arm's next sibling, which is the upper right arm, and so on.
For advanced users, there are ways to alter how your items are sorted:
You can call setZValue() on an item to explicitly stack it on top of, or under, other sibling items. The default Z value for an item is 0. Items with the same Z value are stacked by insertion order.
You can call stackBefore() to reorder the list of children. This will directly modify the insertion order.
You can set the ItemStacksBehindParent flag to stack a child item behind its parent.
The stacking order of two sibling items also counts for each item's children and descendant items. So if one item is on top of another, then all its children will also be on top of all the other item's children as well.
Events
QGraphicsItem receives events from QGraphicsScene through the virtual function sceneEvent(). This function distributes the most common events to a set of convenience event handlers:
contextMenuEvent() handles context menu events
focusInEvent() and focusOutEvent() handle focus in and out events
hoverEnterEvent(), hoverMoveEvent(), and hoverLeaveEvent() handles hover enter, move and leave events
inputMethodEvent() handles input events, for accessibility support
keyPressEvent() and keyReleaseEvent() handle key press and release events
mousePressEvent(), mouseMoveEvent(), mouseReleaseEvent(), and mouseDoubleClickEvent() handles mouse press, move, release, click and doubleclick events
You can filter events for any other item by installing event filters. This functionality is separate from Qt's regular event filters (see QObject::installEventFilter()), which only work on subclasses of QObject. After installing your item as an event filter for another item by calling installSceneEventFilter(), the filtered events will be received by the virtual function sceneEventFilter(). You can remove item event filters by calling removeSceneEventFilter().
Custom Data
Sometimes it's useful to register custom data with an item, be it a custom item, or a standard item. You can call setData() on any item to store data in it using a key-value pair (the key being an integer, and the value is a QVariant). To get custom data from an item, call data(). This functionality is completely untouched by Qt itself; it is provided for the user's convenience.
See also
QGraphicsScene, QGraphicsView, {Graphics View Framework}
Definition at line 89 of file qgraphicsitem.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
Type
The type value returned by the virtual type() function in standard graphics item classes in Qt.
All such standard graphics item classes in Qt are associated with a unique value for Type, e.g. the value returned by QGraphicsPathItem::type() is 2.
class QGraphicsPathItem : public QAbstractGraphicsShapeItem
{
 public:
  enum { Type = 2 };
    int type() const { return Type; }
  ...
};
UserType
The lowest permitted type value for custom items (subclasses of QGraphicsItem or any of the standard items).
This value is used in conjunction with a reimplementation of QGraphicsItem::type() and declaring a Type enum value. Example:
class CustomItem : public QGraphicsItem
{
   ...
   enum { Type = UserType + 1 };
   int type() const
   {
       // Enable the use of qgraphicsitem_cast with this item.
       return Type;
   }
   ...
};
Note
UserType = 65536
Definition at line 419 of file qgraphicsitem.h.
          {
         Type = 1,
         UserType = 65536
     };
CacheMode
enum QGraphicsItem::CacheMode
This enum describes QGraphicsItem's cache modes.
Since
4.4
Caching is used to speed up rendering by allocating and rendering to an off-screen pixel buffer, which can be reused when the item requires redrawing. For some paint devices, the cache is stored directly in graphics memory, which makes rendering very quick.
NoCache The default; all item caching is disabled. QGraphicsItem::paint() is called every time the item needs redrawing.
ItemCoordinateCache Caching is enabled for the item's logical (local) coordinate system. QGraphicsItem creates an off-screen pixel buffer with a configurable size / resolution that you can pass to QGraphicsItem::setCacheMode(). Rendering quality will typically degrade, depending on the resolution of the cache and the item transformation. The first time the item is redrawn, it will render itself into the cache, and the cache is then reused for every subsequent expose. The cache is also reused as the item is transformed. To adjust the resolution of the cache, you can call setCacheMode() again.
DeviceCoordinateCache Caching is enabled at the paint device level, in device coordinates. This mode is for items that can move, but are not rotated, scaled or sheared. If the item is transformed directly or indirectly, the cache will be regenerated automatically. Unlike ItemCoordinateCacheMode, DeviceCoordinateCache always renders at maximum quality.
See also
QGraphicsItem::setCacheMode()
Enumerator
NoCache
ItemCoordinateCache
DeviceCoordinateCache
Definition at line 153 of file qgraphicsitem.h.
                    {
         NoCache,
         ItemCoordinateCache,
         DeviceCoordinateCache
     };
Extension
enum QGraphicsItem::Extension protected
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Warning
This function is not part of the public interface.
See also extension(), supportsExtension() and setExtension().
Enumerator
UserExtension
Definition at line 454 of file qgraphicsitem.h.
                    {
         UserExtension = 0x80000000
     };
GraphicsItemChange
enum QGraphicsItem::GraphicsItemChange
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
The notifications are sent as the state changes, and in some cases, adjustments can be made (see the documentation for each change for details).
Note: Be careful with calling functions on the QGraphicsItem itself inside itemChange(), as certain function calls can lead to unwanted recursion. For example, you cannot call setPos() in itemChange() on an ItemPositionChange notification, as the setPos() function will again call itemChange(ItemPositionChange). Instead, you can return the new, adjusted position from itemChange().
ItemEnabledChange The item's enabled state changes. If the item is presently enabled, it will become disabled, and vice verca. The value argument is the new enabled state (i.e., true or false). Do not call setEnabled() in itemChange() as this notification is delivered. Instead, you can return the new state from itemChange().
ItemEnabledHasChanged The item's enabled state has changed. The value argument is the new enabled state (i.e., true or false). Do not call setEnabled() in itemChange() as this notification is delivered. The return value is ignored.
ItemMatrixChange The item's affine transformation matrix is changing. This value is obsolete; you can use ItemTransformChange instead.
ItemPositionChange The item's position changes. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and when the item's local position changes, relative to its parent (i.e., as a result of calling setPos() or moveBy()). The value argument is the new position (i.e., a QPointF). You can call pos() to get the original position. Do not call setPos() or moveBy() in itemChange() as this notification is delivered; instead, you can return the new, adjusted position from itemChange(). After this notification, QGraphicsItem immediately sends the ItemPositionHasChanged notification if the position changed.
ItemPositionHasChanged The item's position has changed. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and after the item's local position, relative to its parent, has changed. The value argument is the new position (the same as pos()), and QGraphicsItem ignores the return value for this notification (i.e., a read-only notification).
ItemTransformChange The item's transformation matrix changes. This notification is send if the ItemSendsGeometryChanges flag is enabled, and when the item's local transformation matrix changes (i.e., as a result of calling setTransform(). The value argument is the new matrix (i.e., a QTransform); to get the old matrix, call transform(). Do not call setTransform() or set any of the transformation properties in itemChange() as this notification is delivered; instead, you can return the new matrix from itemChange(). This notification is not sent if you change the transformation properties.
ItemTransformHasChanged The item's transformation matrix has changed either because setTransform is called, or one of the transformation properties is changed. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and after the item's local transformation matrix has changed. The value argument is the new matrix (same as transform()), and QGraphicsItem ignores the return value for this notification (i.e., a read-only notification).
ItemRotationChange The item's rotation property changes. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and when the item's rotation property changes (i.e., as a result of calling setRotation()). The value argument is the new rotation (i.e., a double); to get the old rotation, call rotation(). Do not call setRotation() in itemChange() as this notification is delivered; instead, you can return the new rotation from itemChange().
ItemRotationHasChanged The item's rotation property has changed. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and after the item's rotation property has changed. The value argument is the new rotation (i.e., a double), and QGraphicsItem ignores the return value for this notification (i.e., a read-only notification). Do not call setRotation() in itemChange() as this notification is delivered.
ItemScaleChange The item's scale property changes. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and when the item's scale property changes (i.e., as a result of calling setScale()). The value argument is the new scale (i.e., a double); to get the old scale, call scale(). Do not call setScale() in itemChange() as this notification is delivered; instead, you can return the new scale from itemChange().
ItemScaleHasChanged The item's scale property has changed. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and after the item's scale property has changed. The value argument is the new scale (i.e., a double), and QGraphicsItem ignores the return value for this notification (i.e., a read-only notification). Do not call setScale() in itemChange() as this notification is delivered.
ItemTransformOriginPointChange The item's transform origin point property changes. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and when the item's transform origin point property changes (i.e., as a result of calling setTransformOriginPoint()). The value argument is the new origin point (i.e., a QPointF); to get the old origin point, call transformOriginPoint(). Do not call setTransformOriginPoint() in itemChange() as this notification is delivered; instead, you can return the new transform origin point from itemChange().
ItemTransformOriginPointHasChanged The item's transform origin point property has changed. This notification is sent if the ItemSendsGeometryChanges flag is enabled, and after the item's transform origin point property has changed. The value argument is the new origin point (i.e., a QPointF), and QGraphicsItem ignores the return value for this notification (i.e., a read-only notification). Do not call setTransformOriginPoint() in itemChange() as this notification is delivered.
ItemSelectedChange The item's selected state changes. If the item is presently selected, it will become unselected, and vice verca. The value argument is the new selected state (i.e., true or false). Do not call setSelected() in itemChange() as this notification is delivered; instead, you can return the new selected state from itemChange().
ItemSelectedHasChanged The item's selected state has changed. The value argument is the new selected state (i.e., true or false). Do not call setSelected() in itemChange() as this notification is delivered. The return value is ignored.
ItemVisibleChange The item's visible state changes. If the item is presently visible, it will become invisible, and vice verca. The value argument is the new visible state (i.e., true or false). Do not call setVisible() in itemChange() as this notification is delivered; instead, you can return the new visible state from itemChange().
ItemVisibleHasChanged The item's visible state has changed. The value argument is the new visible state (i.e., true or false). Do not call setVisible() in itemChange() as this notification is delivered. The return value is ignored.
ItemParentChange The item's parent changes. The value argument is the new parent item (i.e., a QGraphicsItem pointer). Do not call setParentItem() in itemChange() as this notification is delivered; instead, you can return the new parent from itemChange().
ItemParentHasChanged The item's parent has changed. The value argument is the new parent (i.e., a pointer to a QGraphicsItem). Do not call setParentItem() in itemChange() as this notification is delivered. The return value is ignored.
ItemChildAddedChange A child is added to this item. The value argument is the new child item (i.e., a QGraphicsItem pointer). Do not pass this item to any item's setParentItem() function as this notification is delivered. The return value is unused; you cannot adjust anything in this notification. Note that the new child might not be fully constructed when this notification is sent; calling pure virtual functions on the child can lead to a crash.
ItemChildRemovedChange A child is removed from this item. The value argument is the child item that is about to be removed (i.e., a QGraphicsItem pointer). The return value is unused; you cannot adjust anything in this notification.
ItemSceneChange The item is moved to a new scene. This notification is also sent when the item is added to its initial scene, and when it is removed. The item's scene() is the old scene (or 0 if the item has not been added to a scene yet). The value argument is the new scene (i.e., a QGraphicsScene pointer), or a null pointer if the item is removed from a scene. Do not override this change by passing this item to QGraphicsScene::addItem() as this notification is delivered; instead, you can return the new scene from itemChange(). Use this feature with caution; objecting to a scene change can quickly lead to unwanted recursion.
ItemSceneHasChanged The item's scene has changed. The item's scene() is the new scene. This notification is also sent when the item is added to its initial scene, and when it is removed.The value argument is the new scene (i.e., a pointer to a QGraphicsScene). Do not call setScene() in itemChange() as this notification is delivered. The return value is ignored.
ItemCursorChange The item's cursor changes. The value argument is the new cursor (i.e., a QCursor). Do not call setCursor() in itemChange() as this notification is delivered. Instead, you can return a new cursor from itemChange().
ItemCursorHasChanged The item's cursor has changed. The value argument is the new cursor (i.e., a QCursor). Do not call setCursor() as this notification is delivered. The return value is ignored.
ItemToolTipChange The item's tooltip changes. The value argument is the new tooltip (i.e., a QToolTip). Do not call setToolTip() in itemChange() as this notification is delivered. Instead, you can return a new tooltip from itemChange().
ItemToolTipHasChanged The item's tooltip has changed. The value argument is the new tooltip (i.e., a QToolTip). Do not call setToolTip() as this notification is delivered. The return value is ignored.
ItemFlagsChange The item's flags change. The value argument is the new flags (i.e., a quint32). Do not call setFlags() in itemChange() as this notification is delivered. Instead, you can return the new flags from itemChange().
ItemFlagsHaveChanged The item's flags have changed. The value argument is the new flags (i.e., a quint32). Do not call setFlags() in itemChange() as this notification is delivered. The return value is ignored.
ItemZValueChange The item's Z-value changes. The value argument is the new Z-value (i.e., a double). Do not call setZValue() in itemChange() as this notification is delivered. Instead, you can return a new Z-value from itemChange().
ItemZValueHasChanged The item's Z-value has changed. The value argument is the new Z-value (i.e., a double). Do not call setZValue() as this notification is delivered. The return value is ignored.
ItemOpacityChange The item's opacity changes. The value argument is the new opacity (i.e., a double). Do not call setOpacity() in itemChange() as this notification is delivered. Instead, you can return a new opacity from itemChange().
ItemOpacityHasChanged The item's opacity has changed. The value argument is the new opacity (i.e., a double). Do not call setOpacity() as this notification is delivered. The return value is ignored.
ItemScenePositionHasChanged The item's scene position has changed. This notification is sent if the ItemSendsScenePositionChanges flag is enabled, and after the item's scene position has changed (i.e., the position or transformation of the item itself or the position or transformation of any ancestor has changed). The value argument is the new scene position (the same as scenePos()), and QGraphicsItem ignores the return value for this notification (i.e., a read-only notification).
Enumerator
ItemPositionChange
ItemMatrixChange
ItemVisibleChange
ItemEnabledChange
ItemSelectedChange
ItemParentChange
ItemChildAddedChange
ItemChildRemovedChange
ItemTransformChange
ItemPositionHasChanged
ItemTransformHasChanged
ItemSceneChange
ItemVisibleHasChanged
ItemEnabledHasChanged
ItemSelectedHasChanged
ItemParentHasChanged
ItemSceneHasChanged
ItemCursorChange
ItemCursorHasChanged
ItemToolTipChange
ItemToolTipHasChanged
ItemFlagsChange
ItemFlagsHaveChanged
ItemZValueChange
ItemZValueHasChanged
ItemOpacityChange
ItemOpacityHasChanged
ItemScenePositionHasChanged
ItemRotationChange
ItemRotationHasChanged
ItemScaleChange
ItemScaleHasChanged
ItemTransformOriginPointChange
ItemTransformOriginPointHasChanged
Definition at line 116 of file qgraphicsitem.h.
{
         ItemPositionChange,
         ItemMatrixChange,
         ItemVisibleChange,
         ItemEnabledChange,
         ItemSelectedChange,
         ItemParentChange,
         ItemChildAddedChange,
         ItemChildRemovedChange,
         ItemTransformChange,
         ItemPositionHasChanged,
         ItemTransformHasChanged,
         ItemSceneChange,
         ItemVisibleHasChanged,
         ItemEnabledHasChanged,
         ItemSelectedHasChanged,
         ItemParentHasChanged,
         ItemSceneHasChanged,
         ItemCursorChange,
         ItemCursorHasChanged,
         ItemToolTipChange,
         ItemToolTipHasChanged,
         ItemFlagsChange,
         ItemFlagsHaveChanged,
         ItemZValueChange,
         ItemZValueHasChanged,
         ItemOpacityChange,
         ItemOpacityHasChanged,
         ItemScenePositionHasChanged,
         ItemRotationChange,
         ItemRotationHasChanged,
         ItemScaleChange,
         ItemScaleHasChanged,
         ItemTransformOriginPointChange,
         ItemTransformOriginPointHasChanged
     };
GraphicsItemFlag
enum QGraphicsItem::GraphicsItemFlag
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
All flags are disabled by default.
ItemIsMovable The item supports interactive movement using the mouse. By clicking on the item and then dragging, the item will move together with the mouse cursor. If the item has children, all children are also moved. If the item is part of a selection, all selected items are also moved. This feature is provided as a convenience through the base implementation of QGraphicsItem's mouse event handlers.
ItemIsSelectable The item supports selection. Enabling this feature will enable setSelected() to toggle selection for the item. It will also let the item be selected automatically as a result of calling QGraphicsScene::setSelectionArea(), by clicking on an item, or by using rubber band selection in QGraphicsView.
ItemIsFocusable The item supports keyboard input focus (i.e., it is an input item). Enabling this flag will allow the item to accept focus, which again allows the delivery of key events to QGraphicsItem::keyPressEvent() and QGraphicsItem::keyReleaseEvent().
ItemClipsToShape The item clips to its own shape. The item cannot draw or receive mouse, tablet, drag and drop or hover events outside its shape. It is disabled by default. This behavior is enforced by QGraphicsView::drawItems() or QGraphicsScene::drawItems(). This flag was introduced in Qt 4.3.
ItemClipsChildrenToShape The item clips the painting of all its descendants to its own shape. Items that are either direct or indirect children of this item cannot draw outside this item's shape. By default, this flag is disabled; children can draw anywhere. This behavior is enforced by QGraphicsView::drawItems() or QGraphicsScene::drawItems(). This flag was introduced in Qt 4.3.
ItemIgnoresTransformations The item ignores inherited transformations (i.e., its position is still anchored to its parent, but the parent or view rotation, zoom or shear transformations are ignored). This flag is useful for keeping text label items horizontal and unscaled, so they will still be readable if the view is transformed. When set, the item's view geometry and scene geometry will be maintained separately. You must call deviceTransform() to map coordinates and detect collisions in the view. By default, this flag is disabled. This flag was introduced in Qt 4.3.
Note
With this flag set you can still scale the item itself, and that scale transformation will influence the item's children.
ItemIgnoresParentOpacity The item ignores its parent's opacity. The item's effective opacity is the same as its own; it does not combine with the parent's opacity. This flags allows your item to keep its absolute opacity even if the parent is semitransparent. This flag was introduced in Qt 4.5.
ItemDoesntPropagateOpacityToChildren The item doesn't propagate its opacity to its children. This flag allows you to create a semitransparent item that does not affect the opacity of its children. This flag was introduced in Qt 4.5.
ItemStacksBehindParent The item is stacked behind its parent. By default, child items are stacked on top of the parent item. But setting this flag, the child will be stacked behind it. This flag is useful for drop shadow effects and for decoration objects that follow the parent item's geometry without drawing on top of it. This flag was introduced in Qt 4.5.
ItemUsesExtendedStyleOption The item makes use of either QStyleOptionGraphicsItem::exposedRect or QStyleOptionGraphicsItem::matrix in QStyleOptionGraphicsItem. By default, the QStyleOptionGraphicsItem::exposedRect is initialized to the item's boundingRect() and the QStyleOptionGraphicsItem::matrix is untransformed. You can enable this flag for the style options to be set up with more fine-grained values. Note that QStyleOptionGraphicsItem::levelOfDetail is unaffected by this flag and always initialized to 1. Use QStyleOptionGraphicsItem::levelOfDetailFromTransform() if you need a higher value. This flag was introduced in Qt 4.6.
ItemHasNoContents The item does not paint anything (i.e., calling paint() on the item has no effect). You should set this flag on items that do not need to be painted to ensure that Graphics View avoids unnecessary painting preparations. This flag was introduced in Qt 4.6.
ItemSendsGeometryChanges The item enables itemChange() notifications for ItemPositionChange, ItemPositionHasChanged, ItemMatrixChange, ItemTransformChange, ItemTransformHasChanged, ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged, ItemTransformOriginPointChange, and ItemTransformOriginPointHasChanged. For performance reasons, these notifications are disabled by default. You must enable this flag to receive notifications for position and transform changes. This flag was introduced in Qt 4.6.
ItemAcceptsInputMethod The item supports input methods typically used for Asian languages. This flag was introduced in Qt 4.6.
ItemNegativeZStacksBehindParent The item automatically stacks behind it's parent if it's z-value is negative. This flag enables setZValue() to toggle ItemStacksBehindParent. This flag was introduced in Qt 4.6.
ItemIsPanel The item is a panel. A panel provides activation and contained focus handling. Only one panel can be active at a time (see QGraphicsItem::isActive()). When no panel is active, QGraphicsScene activates all non-panel items. Window items (i.e., QGraphicsItem::isWindow() returns true) are panels. This flag was introduced in Qt 4.6.
ItemIsFocusScope
Warning
This function is not part of the public interface. Internal only (for now).
ItemSendsScenePositionChanges The item enables itemChange() notifications for ItemScenePositionHasChanged. For performance reasons, these notifications are disabled by default. You must enable this flag to receive notifications for scene position changes. This flag was introduced in Qt 4.6.
ItemStopsClickFocusPropagation
Warning
This function is not part of the public interface. The item stops propagating click focus to items underneath when being clicked on. This flag allows you create a non-focusable item that can be clicked on without changing the focus.
ItemStopsFocusHandling
Warning
This function is not part of the public interface. Same as ItemStopsClickFocusPropagation, but also suppresses focus-out. This flag allows you to completely take over focus handling. This flag was introduced in Qt 4.7.
Enumerator
ItemIsMovable
ItemIsSelectable
ItemIsFocusable
ItemClipsToShape
ItemClipsChildrenToShape
ItemIgnoresTransformations
ItemIgnoresParentOpacity
ItemDoesntPropagateOpacityToChildren
ItemStacksBehindParent
ItemUsesExtendedStyleOption
ItemHasNoContents
ItemSendsGeometryChanges
ItemAcceptsInputMethod
ItemNegativeZStacksBehindParent
ItemIsPanel
ItemIsFocusScope
ItemSendsScenePositionChanges
ItemStopsClickFocusPropagation
ItemStopsFocusHandling
Definition at line 92 of file qgraphicsitem.h.
{
         ItemIsMovable = 0x1,
         ItemIsSelectable = 0x2,
         ItemIsFocusable = 0x4,
         ItemClipsToShape = 0x8,
         ItemClipsChildrenToShape = 0x10,
         ItemIgnoresTransformations = 0x20,
         ItemIgnoresParentOpacity = 0x40,
         ItemDoesntPropagateOpacityToChildren = 0x80,
         ItemStacksBehindParent = 0x100,
         ItemUsesExtendedStyleOption = 0x200,
         ItemHasNoContents = 0x400,
         ItemSendsGeometryChanges = 0x800,
         ItemAcceptsInputMethod = 0x1000,
         ItemNegativeZStacksBehindParent = 0x2000,
         ItemIsPanel = 0x4000,
         ItemIsFocusScope = 0x8000, // internal
         ItemSendsScenePositionChanges = 0x10000,
         ItemStopsClickFocusPropagation = 0x20000,
         ItemStopsFocusHandling = 0x40000
         // NB! Don't forget to increase the d_ptr->flags bit field by 1 when adding a new flag.
     };
PanelModality
enum QGraphicsItem::PanelModality
This enum specifies the behavior of a modal panel.
Since
4.6
A modal panel is one that blocks input to other panels. Note that items that are children of a modal panel are not blocked.
The values are:
NonModal The panel is not modal and does not block input to other panels. This is the default value for panels.
PanelModal The panel is modal to a single item hierarchy and blocks input to its parent pane, all grandparent panels, and all siblings of its parent and grandparent panels.
SceneModal The window is modal to the entire scene and blocks input to all panels.
See also
QGraphicsItem::setPanelModality(), QGraphicsItem::panelModality(), QGraphicsItem::ItemIsPanel
Enumerator
NonModal
PanelModal
SceneModal
Definition at line 159 of file qgraphicsitem.h.
     {
         NonModal,
         PanelModal,
         SceneModal
     };
Constructors and Destructors
QGraphicsItem() [1/2]
QGraphicsItem::QGraphicsItem (QGraphicsItem * parent = 0)
Constructs a QGraphicsItem with the given parent item.
It does not modify the parent object returned by QObject::parent().
If parent is 0, you can add the item to a scene by calling QGraphicsScene::addItem(). The item will then become a top-level item.
See also
QGraphicsScene::addItem(), setParentItem()
Definition at line 1461 of file qgraphicsitem.cpp.
     : d_ptr(new QGraphicsItemPrivate)
 {
     d_ptr->q_ptr = this;
     setParentItem(parent);
     if (scene && parent && parent->scene() != scene) {
         qWarning("QGraphicsItem::QGraphicsItem: ignoring scene (%p), which is"
                  " different from parent's scene (%p)",
                  scene, parent->scene());
         return;
     }
     if (scene && !parent)
         scene->addItem(this);
 }
~QGraphicsItem()
QGraphicsItem::~QGraphicsItem () virtual
Destroys the QGraphicsItem and all its children.
If this item is currently associated with a scene, the item will be removed from the scene before it is deleted.
Note
It is more efficient to remove the item from the QGraphicsScene before destroying the item.
Definition at line 1510 of file qgraphicsitem.cpp.
 {
     if (d_ptr->isObject) {
         QGraphicsObject *o = static_cast<QGraphicsObject *>(this);
         QObjectPrivate *p = QObjectPrivate::get(o);
         p->wasDeleted = true;
         if (p->declarativeData) {
             QAbstractDeclarativeData::destroyed(p->declarativeData, o);
             p->declarativeData = 0;
         }
     }
     d_ptr->inDestructor = 1;
     d_ptr->removeExtraItemCache();
 #ifndef QT_NO_GESTURES
     if (d_ptr->isObject && !d_ptr->gestureContext.isEmpty()) {
         QGraphicsObject *o = static_cast<QGraphicsObject *>(this);
         if (QGestureManager *manager = QGestureManager::instance()) {
             foreach (Qt::GestureType type, d_ptr->gestureContext.keys())
                 manager->cleanupCachedGestures(o, type);
         }
     }
 #endif
     clearFocus();
     // Update focus scope item ptr.
     QGraphicsItem *p = d_ptr->parent;
     while (p) {
         if (p->flags() & ItemIsFocusScope) {
             if (p->d_ptr->focusScopeItem == this)
                 p->d_ptr->focusScopeItem = 0;
             break;
         }
         p = p->d_ptr->parent;
     }
     if (!d_ptr->children.isEmpty()) {
         while (!d_ptr->children.isEmpty())
             delete d_ptr->children.first();
         Q_ASSERT(d_ptr->children.isEmpty());
     }
     if (d_ptr->scene) {
         d_ptr->scene->d_func()->removeItemHelper(this);
     } else {
         d_ptr->resetFocusProxy();
         setParentItem(0);
     }
 #ifndef QT_NO_GRAPHICSEFFECT
     delete d_ptr->graphicsEffect;
 #endif //QT_NO_GRAPHICSEFFECT
     if (d_ptr->transformData) {
         for(int i = 0; i < d_ptr->transformData->graphicsTransforms.size(); ++i) {
             QGraphicsTransform *t = d_ptr->transformData->graphicsTransforms.at(i);
             static_cast<QGraphicsTransformPrivate *>(t->d_ptr.data())->item = 0;
             delete t;
         }
     }
     delete d_ptr->transformData;
     if (QGraphicsItemCustomDataStore *dataStore = qt_dataStore())
         dataStore->data.remove(this);
 }
QGraphicsItem() [2/2]
QGraphicsItem::QGraphicsItem (QGraphicsItemPrivate & dd, QGraphicsItem * parent, QGraphicsScene * scene) protected
Warning
This function is not part of the public interface.
Definition at line 1485 of file qgraphicsitem.cpp.
     : d_ptr(&dd)
 {
     d_ptr->q_ptr = this;
     setParentItem(parent);
     if (scene && parent && parent->scene() != scene) {
         qWarning("QGraphicsItem::QGraphicsItem: ignoring scene (%p), which is"
                  " different from parent's scene (%p)",
                  scene, parent->scene());
         return;
     }
     if (scene && !parent)
         scene->addItem(this);
 }
Functions
acceptDrops()
bool QGraphicsItem::acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
By default, items do not accept drag and drop events; items are transparent to drag and drop.
See also
setAcceptDrops()
Definition at line 3064 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::dragMoveEvent().
 {
     return d_ptr->acceptDrops;
 }
acceptedMouseButtons()
Qt::MouseButtons QGraphicsItem::acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
By default, all mouse buttons are accepted.
If an item accepts a mouse button, it will become the mouse grabber item when a mouse press event is delivered for that mouse button. However, if the item does not accept the button, QGraphicsScene will forward the mouse events to the first item beneath it that does.
See also
setAcceptedMouseButtons(), mousePressEvent()
Definition at line 3093 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::mousePressEventHandler(), QDeclarativeMouseArea::setAcceptedButtons(), and QDeclarativeMouseArea::setHovered().
 {
     return Qt::MouseButtons(d_ptr->acceptedMouseButtons);
 }
acceptHoverEvents()
bool QGraphicsItem::acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
Since
4.4
By default, items do not accept hover events.
See also
setAcceptedMouseButtons()
Definition at line 3135 of file qgraphicsitem.cpp.
Referenced by QDeclarativeMouseArea::itemChange(), QDeclarativeMouseArea::mouseReleaseEvent(), and QDeclarativeMouseArea::setHoverEnabled().
 {
     return d_ptr->acceptsHover;
 }
acceptsHoverEvents()
bool QGraphicsItem::acceptsHoverEvents () const
Call acceptHoverEvents() instead.
Definition at line 3148 of file qgraphicsitem.cpp.
Referenced by QGraphicsWidget::event().
 {
     return d_ptr->acceptsHover;
 }
acceptTouchEvents()
bool QGraphicsItem::acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
Since
4.6
By default, items do not accept touch events.
See also
setAcceptTouchEvents()
Definition at line 3221 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::sendTouchBeginEvent().
 {
     return d_ptr->acceptTouchEvents;
 }
addToIndex()
void QGraphicsItem::addToIndex () protected
Adds this item to the scene's index.
Warning
This function is not part of the public interface.
Called in conjunction with removeFromIndex() to ensure the index bookkeeping is correct when the item's position, transformation or shape changes.
Definition at line 7936 of file qgraphicsitem.cpp.
 {
     if (d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren) {
         // ### add to child index only if applicable
         return;
     }
     if (d_ptr->scene)
         d_ptr->scene->d_func()->index->addItem(this);
 }
advance()
void QGraphicsItem::advance (int phase) virtual
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
In the first phase, all items are called with phase == 0, indicating that items on the scene are about to advance, and then all items are called with phase == 1. Reimplement this function to update your item if you need simple scene-controlled animation.
The default implementation does nothing.
For individual item animation, an alternative to this function is to either use QGraphicsItemAnimation, or to multiple-inherit from QObject and QGraphicsItem, and animate your item using QObject::startTimer() and QObject::timerEvent().
See also
QGraphicsItemAnimation, QTimeLine
Definition at line 4882 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::advance().
 {
     Q_UNUSED(phase);
 }
boundingRect()
QRectF QGraphicsItem::boundingRect () const pure virtual
This pure virtual function defines the outer bounds of the item as a rectangle; all painting must be restricted to inside an item's bounding rect.
QGraphicsView uses this to determine whether the item requires redrawing.
Although the item's shape can be arbitrary, the bounding rect is always rectangular, and it is unaffected by the items' transformation.
If you want to change the item's bounding rectangle, you must first call prepareGeometryChange(). This notifies the scene of the imminent change, so that its can update its item geometry index; otherwise, the scene will be unaware of the item's new geometry, and the results are undefined (typically, rendering artifacts are left around in the view).
Reimplement this function to let QGraphicsView determine what parts of the widget, if any, need to be redrawn.
Note: For shapes that paint an outline / stroke, it is important to include half the pen width in the bounding rect. It is not necessary to compensate for antialiasing, though.
Example:
QRectF CircleItem::boundingRect() const
{
    qreal penWidth = 1;
    return QRectF(-radius - penWidth / 2, -radius - penWidth / 2,
                  diameter + penWidth, diameter + penWidth);
}
See also
boundingRegion(), shape(), contains(), {The Graphics View Coordinate System}, prepareGeometryChange()
Implemented in QGraphicsItemGroup, QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, QGraphicsPathItem, QDeclarativeTextEdit, QDeclarativeTextInput, QDeclarativeText, QGraphicsWidget, QDeclarativeRectangle, QDeclarativeItem, QDeclarativePaintedItem, QGraphicsSvgItem, QDeclarativeImage, and QmlJSDebugger::LiveLayerItem.
Referenced by QGraphicsItemGroup::addToGroup(), adjustedItemBoundingRect(), boundingRegion(), clipPath(), collidesWithPath(), QGraphicsScenePrivate::drawItemHelper(), QmlJSDebugger::BoundingRectHighlighter::highlightAll(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), isObscured(), isObscuredBy(), prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), qt_graphicsItem_highlightSelected(), sceneBoundingRect(), scroll(), QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem(), QmlJSDebugger::LiveSelectionIndicator::setItems(), QGraphicsLineItem::setLine(), QGraphicsViewPrivate::setUpdateClip(), and shape().
boundingRegion()
QRegion QGraphicsItem::boundingRegion (const QTransform & itemToDeviceTransform) const
Returns the bounding region for this item.
Since
4.4
The coordinate space of the returned region depends on itemToDeviceTransform. If you pass an identity QTransform as a parameter, this function will return a local coordinate region.
The bounding region describes a coarse outline of the item's visual contents. Although it's expensive to calculate, it's also more precise than boundingRect(), and it can help to avoid unnecessary repainting when an item is updated. This is particularly efficient for thin items (e.g., lines or simple polygons). You can tune the granularity for the bounding region by calling setBoundingRegionGranularity(). The default granularity is 0; in which the item's bounding region is the same as its bounding rect.
itemToDeviceTransform is the transformation from item coordinates to device coordinates. If you want this function to return a QRegion in scene coordinates, you can pass sceneTransform() as an argument.
See also
boundingRegionGranularity()
Definition at line 5545 of file qgraphicsitem.cpp.
Referenced by QGraphicsViewPrivate::mapToViewRegion().
 {
     // ### Ideally we would have a better way to generate this region,
     // preferably something in the lines of QPainterPath::toRegion(QTransform)
     // coupled with a way to generate a painter path from a set of painter
     // operations (e.g., QPicture::toPainterPath() or so). The current
     // approach generates a bitmap with the size of the item's bounding rect
     // in device coordinates, scaled by b.r.granularity, then paints the item
     // into the bitmap, converts the result to a QRegion and scales the region
     // back to device space with inverse granularity.
     qreal granularity = boundingRegionGranularity();
     QRect deviceRect = itemToDeviceTransform.mapRect(boundingRect()).toRect();
     _q_adjustRect(&deviceRect);
     if (granularity == 0.0)
         return QRegion(deviceRect);
     int pad = 1;
     QSize bitmapSize(qMax(1, int(deviceRect.width() * granularity) + pad * 2),
                      qMax(1, int(deviceRect.height() * granularity) + pad * 2));
     QImage mask(bitmapSize, QImage::Format_ARGB32_Premultiplied);
     mask.fill(0);
     QPainter p(&mask);
     p.setRenderHints(QPainter::Antialiasing);
     // Transform painter (### this code is from QGraphicsScene::drawItemHelper
     // and doesn't work properly with perspective transformations).
     QPointF viewOrigo = itemToDeviceTransform.map(QPointF(0,  0));
     QPointF offset = viewOrigo - deviceRect.topLeft();
     p.scale(granularity, granularity);
     p.translate(offset);
     p.translate(pad, pad);
     p.setWorldTransform(itemToDeviceTransform, true);
     p.translate(itemToDeviceTransform.inverted().map(QPointF(0, 0)));
     // Render
     QStyleOptionGraphicsItem option;
     const_cast<QGraphicsItem *>(this)->paint(&p, &option, 0);
     p.end();
     // Transform QRegion back to device space
     QTransform unscale = QTransform::fromScale(1 / granularity, 1 / granularity);
     QRegion r;
     QBitmap colorMask = QBitmap::fromImage(mask.createMaskFromColor(0));
     foreach (const QRect &rect, QRegion( colorMask ).rects()) {
         QRect xrect = unscale.mapRect(rect).translated(deviceRect.topLeft() - QPoint(pad, pad));
         r += xrect.adjusted(-1, -1, 1, 1) & deviceRect;
     }
     return r;
 }
boundingRegionGranularity()
qreal QGraphicsItem::boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
Since
4.4
The default value is 0 (i.e., the lowest granularity, where the bounding region corresponds to the item's bounding rectangle).
Warning
This function is not part of the public interface.
NOTE
\sa setBoundingRegionGranularity()
Definition at line 5611 of file qgraphicsitem.cpp.
Referenced by boundingRegion(), and QGraphicsScenePrivate::processDirtyItemsRecursive().
 {
     return d_ptr->hasBoundingRegionGranularity
         ? qvariant_cast<qreal>(d_ptr->extra(QGraphicsItemPrivate::ExtraBoundingRegionGranularity))
         : 0;
 }
cacheMode()
QGraphicsItem::CacheMode QGraphicsItem::cacheMode () const
Returns the cache mode for this item.
Since
4.4 The default mode is NoCache (i.e., cache is disabled and all painting is immediate).
See also
setCacheMode()
Definition at line 2061 of file qgraphicsitem.cpp.
Referenced by QGraphicsSvgItem::isCachingEnabled().
 {
     return QGraphicsItem::CacheMode(d_ptr->cacheMode);
 }
childItems()
QList< QGraphicsItem * > QGraphicsItem::childItems () const
Returns a list of this item's children.
Since
4.4
The items are sorted by stacking order. This takes into account both the items' insertion order and their Z-values.
See also
setParentItem(), zValue(), {QGraphicsItem::Sorting}{Sorting}
Definition at line 1833 of file qgraphicsitem.cpp.
Referenced by QDeclarativeContents::calcHeight(), QDeclarativeContents::calcWidth(), QDeclarativeItem::childAt(), children(), QDeclarativeContents::complete(), QDeclarativeFlickablePrivate::data_at(), QDeclarativeFlickablePrivate::data_clear(), QDeclarativeFlickablePrivate::data_count(), QmlJSDebugger::LiveLayerItem::findAllChildItems(), QGraphicsProxyWidgetPrivate::setWidget_helper(), QDeclarativeContents::~QDeclarativeContents(), and QGraphicsWidget::~QGraphicsWidget().
 {
     const_cast<QGraphicsItem *>(this)->d_ptr->ensureSortedChildren();
     return d_ptr->children;
 }
children()
QList< QGraphicsItem * > QGraphicsItem::children () const
Use childItems() instead.
See also
setParentItem()
Definition at line 1815 of file qgraphicsitem.cpp.
Referenced by _q_qgraphicsItemSetFlag(), QGraphicsItemPrivate::addChild(), QGraphicsScene::destroyItemGroup(), QGraphicsItemPrivate::ensureSequentialSiblingIndex(), QGraphicsItemPrivate::invalidateChildGraphicsEffectsRecursively(), QGraphicsItemPrivate::invalidateDepthRecursively(), QGraphicsItemPrivate::removeChild(), QGraphicsScene::setActiveWindow(), QGraphicsItemPrivate::setEnabledHelper(), QGraphicsItemPrivate::setVisibleHelper(), and QGraphicsItemPrivate::updatePaintedViewBoundingRects().
 {
     return childItems();
 }
childrenBoundingRect()
QRectF QGraphicsItem::childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
The rectangle will contain all descendants after they have been mapped to local coordinates. If the item has no children, this function returns an empty QRectF.
This does not include this item's own bounding rect; it only returns its descendants' accumulated bounding rect. If you need to include this item's bounding rect, you can add boundingRect() to childrenBoundingRect() using QRectF::operator|().
This function is linear in complexity; it determines the size of the returned bounding rect by iterating through all descendants.
See also
boundingRect(), sceneBoundingRect()
Definition at line 5068 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QmlJSDebugger::LiveLayerItem::boundingRect(), QGraphicsItemGroup::removeFromGroup(), and QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem().
 {
     if (!d_ptr->dirtyChildrenBoundingRect)
         return d_ptr->childrenBoundingRect;
     d_ptr->childrenBoundingRect = QRectF();
     d_ptr->childrenBoundingRectHelper(0, &d_ptr->childrenBoundingRect, 0);
     d_ptr->dirtyChildrenBoundingRect = 0;
     return d_ptr->childrenBoundingRect;
 }
clearFocus()
void QGraphicsItem::clearFocus ()
Takes keyboard input focus from the item.
If it has focus, a focus out event is sent to this item to tell it that it is about to lose the focus.
Only items that set the ItemIsFocusable flag, or widgets that set an appropriate focus policy, can accept keyboard focus.
See also
setFocus(), hasFocus(), QGraphicsWidget::focusPolicy
Definition at line 3521 of file qgraphicsitem.cpp.
Referenced by QWidget::clearFocus(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsItemPrivate::setEnabledHelper(), setFlags(), QDeclarativeItem::setFocus(), QGraphicsWidget::setFocusPolicy(), ~QGraphicsItem(), and QGraphicsWidget::~QGraphicsWidget().
 {
     d_ptr->clearFocusHelper(/* giveFocusToParent = */ true);
 }
clipPath()
QPainterPath QGraphicsItem::clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
Since
4.5
The clip path constrains the item's appearance and interaction (i.e., restricts the area the item can draw, and it also restricts the area that the item receives events).
You can enable clipping by setting the ItemClipsToShape or ItemClipsChildrenToShape flags. The item's clip path is calculated by intersecting all clipping ancestors' shapes. If the item sets ItemClipsToShape, the final clip is intersected with the item's own shape.
Note
Clipping introduces a performance penalty for all items involved; you should generally avoid using clipping if you can (e.g., if your items always draw inside boundingRect() or shape() boundaries, clipping is not necessary).
See also
isClipped(), shape(), setFlags()
Definition at line 5215 of file qgraphicsitem.cpp.
Referenced by collidesWithItem(), collidesWithPath(), contains(), QGraphicsView::fitInView(), and QAbstractGraphicsShapeItem::opaqueArea().
 {
     Q_D(const QGraphicsItem);
     if (!isClipped())
         return QPainterPath();
     const QRectF thisBoundingRect(boundingRect());
     if (thisBoundingRect.isEmpty())
         return QPainterPath();
     QPainterPath clip;
     // Start with the item's bounding rect.
     clip.addRect(thisBoundingRect);
     if (d->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren) {
         const QGraphicsItem *parent = this;
         const QGraphicsItem *lastParent = this;
         // Intersect any in-between clips starting at the top and moving downwards.
         while ((parent = parent->d_ptr->parent)) {
             if (parent->d_ptr->flags & ItemClipsChildrenToShape) {
                 // Map clip to the current parent and intersect with its shape/clipPath
                 clip = lastParent->itemTransform(parent).map(clip);
                 clip = clip.intersected(parent->shape());
                 if (clip.isEmpty())
                     return clip;
                 lastParent = parent;
             }
             if (!(parent->d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren))
                 break;
         }
         if (lastParent != this) {
             // Map clip back to the item's transform.
             // ### what if itemtransform fails
             clip = lastParent->itemTransform(this).map(clip);
         }
     }
     if (d->flags & ItemClipsToShape)
         clip = clip.intersected(shape());
     return clip;
 }
collidesWithItem()
bool QGraphicsItem::collidesWithItem (const QGraphicsItem * other, Qt::ItemSelectionMode mode = Qt::IntersectsItemShape) const virtual
Returns true if this item collides with other; otherwise returns false.
The mode is applied to other, and the resulting shape or bounding rectangle is then compared to this item's shape. The default value for mode is Qt::IntersectsItemShape; other collides with this item if it either intersects, contains, or is contained by this item's shape (see Qt::ItemSelectionMode for details).
The default implementation is based on shape intersection, and it calls shape() on both items. Because the complexity of arbitrary shape-shape intersection grows with an order of magnitude when the shapes are complex, this operation can be noticably time consuming. You have the option of reimplementing this function in a subclass of QGraphicsItem to provide a custom algorithm. This allows you to make use of natural constraints in the shapes of your own items, in order to improve the performance of the collision detection. For instance, two untransformed perfectly circular items' collision can be determined very efficiently by comparing their positions and radii.
Keep in mind that when reimplementing this function and calling shape() or boundingRect() on other, the returned coordinates must be mapped to this item's coordinate system before any intersection can take place.
See also
contains(), shape()
Definition at line 5307 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::collidingItems().
 {
     if (other == this)
         return true;
     if (!other)
         return false;
     // The items share the same clip if their closest clipper is the same, or
     // if one clips the other.
     bool clips = (d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren);
     bool otherClips = (other->d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren);
     if (clips || otherClips) {
         const QGraphicsItem *closestClipper = isAncestorOf(other) ? this : parentItem();
         while (closestClipper && !(closestClipper->flags() & ItemClipsChildrenToShape))
             closestClipper = closestClipper->parentItem();
         const QGraphicsItem *otherClosestClipper = other->isAncestorOf(this) ? other : other->parentItem();
         while (otherClosestClipper && !(otherClosestClipper->flags() & ItemClipsChildrenToShape))
             otherClosestClipper = otherClosestClipper->parentItem();
         if (closestClipper == otherClosestClipper) {
             d_ptr->localCollisionHack = 1;
             bool res = collidesWithPath(mapFromItem(other, other->shape()), mode);
             d_ptr->localCollisionHack = 0;
             return res;
         }
     }
     QPainterPath otherShape = other->isClipped() ? other->clipPath() : other->shape();
     return collidesWithPath(mapFromItem(other, otherShape), mode);
 }
collidesWithPath()
bool QGraphicsItem::collidesWithPath (const QPainterPath & path, Qt::ItemSelectionMode mode = Qt::IntersectsItemShape) const virtual
Returns true if this item collides with path.
The collision is determined by mode. The default value for mode is Qt::IntersectsItemShape; path collides with this item if it either intersects, contains, or is contained by this item's shape.
Note that this function checks whether the item's shape or bounding rectangle (depending on mode) is contained within path, and not whether path is contained within the items shape or bounding rectangle.
See also
collidesWithItem(), contains(), shape()
Definition at line 5350 of file qgraphicsitem.cpp.
Referenced by collidesWithItem(), and QGraphicsSceneIndexPrivate::itemCollidesWithPath().
 {
     if (path.isEmpty()) {
         // No collision with empty paths.
         return false;
     }
     QRectF rectA(boundingRect());
     _q_adjustRect(&rectA);
     QRectF rectB(path.controlPointRect());
     _q_adjustRect(&rectB);
     if (!rectA.intersects(rectB)) {
         // This we can determine efficiently. If the two rects neither
         // intersect nor contain eachother, then the two items do not collide.
         return false;
     }
     // For further testing, we need this item's shape or bounding rect.
     QPainterPath thisShape;
     if (mode == Qt::IntersectsItemShape || mode == Qt::ContainsItemShape)
         thisShape = (isClipped() && !d_ptr->localCollisionHack) ? clipPath() : shape();
     else
         thisShape.addRect(rectA);
     if (thisShape == QPainterPath()) {
         // Empty shape? No collision.
         return false;
     }
     // Use QPainterPath boolean operations to determine the collision, O(N*logN).
     if (mode == Qt::IntersectsItemShape || mode == Qt::IntersectsItemBoundingRect)
         return path.intersects(thisShape);
     return path.contains(thisShape);
 }
collidingItems()
QList< QGraphicsItem * > QGraphicsItem::collidingItems (Qt::ItemSelectionMode mode = Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
The way collisions are detected is determined by applying mode to items that are compared to this item, i.e., each item's shape or bounding rectangle is checked against this item's shape. The default value for mode is Qt::IntersectsItemShape.
See also
collidesWithItem()
Definition at line 5395 of file qgraphicsitem.cpp.
 {
     if (d_ptr->scene)
         return d_ptr->scene->collidingItems(this, mode);
     return QList<QGraphicsItem *>();
 }
commonAncestorItem()
QGraphicsItem * QGraphicsItem::commonAncestorItem (const QGraphicsItem * other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
Since
4.4
See also
isAncestorOf()
Definition at line 6897 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::dispatchHoverEvent(), isBlockedByModalPanel(), itemTransform(), and QGraphicsItemPrivate::setFocusHelper().
 {
     if (!other)
         return 0;
     if (other == this)
         return const_cast<QGraphicsItem *>(this);
     const QGraphicsItem *thisw = this;
     const QGraphicsItem *otherw = other;
     int thisDepth = d_ptr->depth();
     int otherDepth = other->d_ptr->depth();
     while (thisDepth > otherDepth) {
         thisw = thisw->d_ptr->parent;
         --thisDepth;
     }
     while (otherDepth > thisDepth) {
         otherw = otherw->d_ptr->parent;
         --otherDepth;
     }
     while (thisw && thisw != otherw) {
         thisw = thisw->d_ptr->parent;
         otherw = otherw->d_ptr->parent;
     }
     return const_cast<QGraphicsItem *>(thisw);
 }
contains()
bool QGraphicsItem::contains (const QPointF & point) const virtual
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
It is most often called from QGraphicsView to determine what item is under the cursor, and for that reason, the implementation of this function should be as light-weight as possible.
By default, this function calls shape(), but you can reimplement it in a subclass to provide a (perhaps more efficient) implementation.
See also
shape(), boundingRect(), collidesWithPath()
Reimplemented in QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, and QGraphicsPathItem.
Definition at line 5273 of file qgraphicsitem.cpp.
Referenced by QGraphicsPathItem::contains(), QGraphicsRectItem::contains(), QGraphicsEllipseItem::contains(), QGraphicsPolygonItem::contains(), QGraphicsLineItem::contains(), QGraphicsPixmapItem::contains(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsObject::grabGesture(), QGraphicsProxyWidget::hoverMoveEvent(), QGraphicsSceneIndexPointIntersector::intersect(), isUnderMouse(), QDeclarativeMouseArea::mouseMoveEvent(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), QGraphicsWidget::paintWindowFrame(), QDeclarativeTextEdit::positionAt(), qt_QGraphicsItem_isObscured(), and QGraphicsLineItem::setLine().
 {
     return isClipped() ? clipPath().contains(point) : shape().contains(point);
 }
contextMenuEvent()
void QGraphicsItem::contextMenuEvent (QGraphicsSceneContextMenuEvent * event) protected virtual
This event handler can be reimplemented in a subclass to process context menu events.
The event parameter contains details about the event to be handled.
If you ignore the event, (i.e., by calling QEvent::ignore(),) event will propagate to any item beneath this item. If no items accept the event, it will be ignored by the scene, and propagate to the view.
It's common to open a QMenu in response to receiving a context menu event. Example:
void CustomItem::contextMenuEvent(QGraphicsSceneContextMenuEvent *event)
{
    QMenu menu;
    QAction *removeAction = menu.addAction("Remove");
    QAction *markAction = menu.addAction("Mark");
    QAction *selectedAction = menu.exec(event->screenPos());
    // ...
}
The default implementation ignores the event.
See also
sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeMouseArea, and QGraphicsProxyWidget.
Definition at line 7248 of file qgraphicsitem.cpp.
Referenced by QDeclarativeMouseArea::contextMenuEvent(), and sceneEvent().
 {
     event->ignore();
 }
cursor()
QCursor QGraphicsItem::cursor () const
Returns the current cursor shape for the item.
The mouse cursor will assume this shape when it's over this item. See the list of predefined cursor objects for a range of useful shapes.
An editor item might want to use an I-beam cursor:
item->setCursor(Qt::IBeamCursor);
If no cursor has been set, the cursor of the item beneath is used.
See also
setCursor(), hasCursor(), unsetCursor(), QWidget::cursor, QApplication::overrideCursor()
Definition at line 2256 of file qgraphicsitem.cpp.
Referenced by QGraphicsViewPrivate::_q_unsetViewportCursor(), QDeclarativeTextInput::mouseDoubleClickEvent(), QGraphicsViewPrivate::mouseMoveEventHandler(), QDeclarativeTextInput::mousePressEvent(), QDeclarativeTextInput::moveCursorSelection(), QDeclarativeTextEdit::moveCursorSelection(), QDeclarativeTextInput::positionAt(), QDeclarativeTextEdit::positionAt(), QDeclarativeTextEdit::select(), setCursor(), QDeclarativeTextEdit::setCursorPosition(), and QDeclarativeTextEditPrivate::updateSelection().
 {
     return qvariant_cast<QCursor>(d_ptr->extra(QGraphicsItemPrivate::ExtraCursor));
 }
data()
QVariant QGraphicsItem::data (int key) const
Returns this item's custom data for the key key as a QVariant.
Custom item data is useful for storing arbitrary properties in any item. Example:
static const int ObjectName = 0;
QGraphicsItem *item = scene.itemAt(100, 50);
if (item->data(ObjectName).toString().isEmpty()) {
    if (qgraphicsitem_cast<ButtonItem *>(item))
        item->setData(ObjectName, "Button");
}
Qt does not use this feature for storing data; it is provided solely for the convenience of the user.
See also
setData()
Definition at line 6959 of file qgraphicsitem.cpp.
Referenced by QGraphicsWidget::close(), QDeclarativeImplicitSizePaintedItem::drawContents(), QmlJSDebugger::isEditorItem(), QDeclarativeGestureAreaParser::setCustomData(), and QmlJSDebugger::LiveSelectionIndicator::setItems().
 {
     QGraphicsItemCustomDataStore *store = qt_dataStore();
     if (!store->data.contains(this))
         return QVariant();
     return store->data.value(this).value(key);
 }
deviceTransform()
QTransform QGraphicsItem::deviceTransform (const QTransform & viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
Since
4.3
This matrix can be used to map coordinates and geometrical shapes from this item's local coordinate system to the viewport's (or any device's) coordinate system. To map coordinates from the viewport, you must first invert the returned matrix.
Example:
QGraphicsRectItem rect;
rect.setPos(100, 100);
rect.deviceTransform(view->viewportTransform()).map(QPointF(0, 0));
// returns the item's (0, 0) point in view's viewport coordinates
rect.deviceTransform(view->viewportTransform()).inverted().map(QPointF(100, 100));
// returns view's viewport's (100, 100) coordinate in item coordinates
This function is the same as combining this item's scene transform with the view's viewport transform, but it also understands the ItemIgnoresTransformations flag. The device transform can be used to do accurate coordinate mapping (and collision detection) for untransformable items.
See also
transform(), setTransform(), scenePos(), {The Graphics View Coordinate System}, itemTransform()
Definition at line 4463 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsSceneIndexRectIntersector::intersect(), QGraphicsSceneIndexPointIntersector::intersect(), QGraphicsSceneIndexPathIntersector::intersect(), QGraphicsViewPrivate::mapToViewRect(), QGraphicsViewPrivate::mapToViewRegion(), mouseMoveEvent(), QGraphicsView::paintEvent(), QGraphicsViewPrivate::setUpdateClip(), and updateHelper().
 {
     // Ensure we return the standard transform if we're not untransformable.
     if (!d_ptr->itemIsUntransformable()) {
         d_ptr->ensureSceneTransform();
         return d_ptr->sceneTransform * viewportTransform;
     }
     // Find the topmost item that ignores view transformations.
     const QGraphicsItem *untransformedAncestor = this;
     QList<const QGraphicsItem *> parents;
     while (untransformedAncestor && ((untransformedAncestor->d_ptr->ancestorFlags
                                      & QGraphicsItemPrivate::AncestorIgnoresTransformations))) {
         parents.prepend(untransformedAncestor);
         untransformedAncestor = untransformedAncestor->parentItem();
     }
     if (!untransformedAncestor) {
         // Assert in debug mode, continue in release.
         Q_ASSERT_X(untransformedAncestor, "QGraphicsItem::deviceTransform",
                    "Invalid object structure!");
         return QTransform();
     }
     // Determine the inherited origin. Find the parent of the topmost untransformable.
     // Use its scene transform to map the position of the untransformable. Then use
     // that viewport position as the anchoring point for the untransformable subtree.
     QGraphicsItem *parentOfUntransformedAncestor = untransformedAncestor->parentItem();
     QTransform inheritedMatrix;
     if (parentOfUntransformedAncestor)
         inheritedMatrix = parentOfUntransformedAncestor->sceneTransform();
     QPointF mappedPoint = (inheritedMatrix * viewportTransform).map(untransformedAncestor->pos());
     // COMBINE
     QTransform matrix = QTransform::fromTranslate(mappedPoint.x(), mappedPoint.y());
     if (untransformedAncestor->d_ptr->transformData)
         matrix = untransformedAncestor->d_ptr->transformData->computedFullTransform(&matrix);
     // Then transform and translate all children.
     for (int i = 0; i < parents.size(); ++i) {
         const QGraphicsItem *parent = parents.at(i);
         parent->d_ptr->combineTransformFromParent(&matrix);
     }
     return matrix;
 }
dragEnterEvent()
void QGraphicsItem::dragEnterEvent (QGraphicsSceneDragDropEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
Drag enter events are generated as the cursor enters the item's area.
By accepting the event, (i.e., by calling QEvent::accept(),) the item will accept drop events, in addition to receiving drag move and drag leave. Otherwise, the event will be ignored and propagate to the item beneath. If the event is accepted, the item will receive a drag move event before control goes back to the event loop.
A common implementation of dragEnterEvent accepts or ignores event depending on the associated mime data in event. Example:
CustomItem::CustomItem()
{
    setAcceptDrops(true);
    ...
}
void CustomItem::dragEnterEvent(QGraphicsSceneDragDropEvent *event)
{
    event->setAccepted(event->mimeData()->hasFormat("text/plain"));
}
Items do not receive drag and drop events by default; to enable this feature, call setAcceptDrops(true).
The default implementation does nothing.
See also
dropEvent(), dragMoveEvent(), dragLeaveEvent()
Reimplemented in QGraphicsTextItem, and QGraphicsProxyWidget.
Definition at line 7276 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     Q_D(QGraphicsItem);
     // binary compatibility workaround between 4.4 and 4.5
     if (d->isProxyWidget())
         static_cast<QGraphicsProxyWidget*>(this)->dragEnterEvent(event);
 }
dragLeaveEvent()
void QGraphicsItem::dragLeaveEvent (QGraphicsSceneDragDropEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
Drag leave events are generated as the cursor leaves the item's area. Most often you will not need to reimplement this function, but it can be useful for resetting state in your item (e.g., highlighting).
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
Items do not receive drag and drop events by default; to enable this feature, call setAcceptDrops(true).
The default implementation does nothing.
See also
dragEnterEvent(), dropEvent(), dragMoveEvent()
Reimplemented in QGraphicsTextItem, and QGraphicsProxyWidget.
Definition at line 7300 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     Q_D(QGraphicsItem);
     // binary compatibility workaround between 4.4 and 4.5
     if (d->isProxyWidget())
         static_cast<QGraphicsProxyWidget*>(this)->dragLeaveEvent(event);
 }
dragMoveEvent()
void QGraphicsItem::dragMoveEvent (QGraphicsSceneDragDropEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive drag move events for this item.
Drag move events are generated as the cursor moves around inside the item's area. Most often you will not need to reimplement this function; it is used to indicate that only parts of the item can accept drops.
Calling QEvent::ignore() or QEvent::accept() on event toggles whether or not the item will accept drops at the position from the event. By default, event is accepted, indicating that the item allows drops at the specified position.
Items do not receive drag and drop events by default; to enable this feature, call setAcceptDrops(true).
The default implementation does nothing.
See also
dropEvent(), dragEnterEvent(), dragLeaveEvent()
Reimplemented in QGraphicsTextItem, and QGraphicsProxyWidget.
Definition at line 7327 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     Q_D(QGraphicsItem);
     // binary compatibility workaround between 4.4 and 4.5
     if (d->isProxyWidget())
         static_cast<QGraphicsProxyWidget*>(this)->dragMoveEvent(event);
 }
dropEvent()
void QGraphicsItem::dropEvent (QGraphicsSceneDragDropEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive drop events for this item.
Items can only receive drop events if the last drag move event was accepted.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
Items do not receive drag and drop events by default; to enable this feature, call setAcceptDrops(true).
The default implementation does nothing.
See also
dragEnterEvent(), dragMoveEvent(), dragLeaveEvent()
Reimplemented in QGraphicsTextItem, and QGraphicsProxyWidget.
Definition at line 7349 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     Q_D(QGraphicsItem);
     // binary compatibility workaround between 4.4 and 4.5
     if (d->isProxyWidget())
         static_cast<QGraphicsProxyWidget*>(this)->dropEvent(event);
 }
effectiveOpacity()
qreal QGraphicsItem::effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
Since
4.5
0 (transparent) and 1.0 (opaque). This value is a combination of this item's local opacity, and its parent and ancestors' opacities. The effective opacity decides how the item is rendered.
See also
opacity(), setOpacity(), paint(), ItemIgnoresParentOpacity, ItemDoesntPropagateOpacityToChildren
Definition at line 2819 of file qgraphicsitem.cpp.
Referenced by ShaderEffectItem::updateEffectState().
 {
     return d_ptr->effectiveOpacity();
 }
ensureVisible() [1/2]
void QGraphicsItem::ensureVisible (const QRectF & rect = QRectF(), int xmargin = 50, int ymargin = 50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
If rect is a null rect (the default), QGraphicsItem will default to the item's bounding rect. xmargin and ymargin are the number of pixels the view should use for margins.
If the specified rect cannot be reached, the contents are scrolled to the nearest valid position.
If this item is not viewed by a QGraphicsView, this function does nothing.
See also
QGraphicsView::ensureVisible()
Definition at line 4015 of file qgraphicsitem.cpp.
 {
     if (d_ptr->scene) {
         QRectF sceneRect;
         if (!rect.isNull())
             sceneRect = sceneTransform().mapRect(rect);
         else
             sceneRect = sceneBoundingRect();
         foreach (QGraphicsView *view, d_ptr->scene->d_func()->views)
             view->ensureVisible(sceneRect, xmargin, ymargin);
     }
 }
ensureVisible() [2/2]
void QGraphicsItem::ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin = 50, int ymargin = 50) inline
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
Definition at line 503 of file qgraphicsitem.h.
 { ensureVisible(QRectF(ax, ay, w, h), xmargin, ymargin); }
extension()
QVariant QGraphicsItem::extension (const QVariant & variant) const protected virtual
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Warning
This function is not part of the public interface.
Reimplemented in QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, and QGraphicsPathItem.
Definition at line 7920 of file qgraphicsitem.cpp.
 {
     Q_UNUSED(variant);
     return QVariant();
 }
filtersChildEvents()
bool QGraphicsItem::filtersChildEvents () const
Returns true if this item filters child events (i.
Since
4.6
e., all events intended for any of its children are instead sent to this item); otherwise, false is returned.
The default value is false; child events are not filtered.
See also
setFiltersChildEvents()
Definition at line 3261 of file qgraphicsitem.cpp.
 {
     return d_ptr->filtersDescendantEvents;
 }
flags()
QGraphicsItem::GraphicsItemFlags QGraphicsItem::flags () const
Returns this item's flags.
The flags describe what configurable features of the item are enabled and not. For example, if the flags include ItemIsFocusable, the item can accept input focus.
By default, no flags are enabled.
See also
setFlags(), setFlag()
Definition at line 1890 of file qgraphicsitem.cpp.
Referenced by _q_qgraphicsItemSetFlag(), _qt_movableAncestorIsSelected(), QGraphicsItemPrivate::clearFocusHelper(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), collidesWithItem(), QDeclarativeKeysAttached::componentComplete(), QDeclarativeItemPrivate::data(), QDeclarativeTextInput::drawContents(), QGraphicsScene::focusNextPrevChild(), QDeclarativeItem::forceActiveFocus(), QDeclarativeItem::hasFocus(), QDeclarativeKeysAttached::inputMethodEvent(), QDeclarativeKeysAttached::inputMethodQuery(), mouseMoveEvent(), mousePressEvent(), QGraphicsTextItem::mousePressEvent(), QGraphicsScenePrivate::mousePressEventHandler(), mouseReleaseEvent(), QGraphicsItemPrivate::movableAncestorIsSelected(), operator<<(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsItemPrivate::sendScenePosChange(), QGraphicsScenePrivate::sendTouchBeginEvent(), setFlags(), QGraphicsItemPrivate::setFocusHelper(), QGraphicsScenePrivate::setFocusItemHelper(), QDeclarativeTextEdit::setReadOnly(), QGraphicsScene::setSelectionArea(), QGraphicsTextItem::setTextInteractionFlags(), QGraphicsItemPrivate::setVisibleHelper(), QmlJSDebugger::AbstractLiveEditTool::topMovableGraphicsItem(), QGraphicsScene::wheelEvent(), and ~QGraphicsItem().
 {
     return GraphicsItemFlags(d_ptr->flags);
 }
focusInEvent()
void QGraphicsItem::focusInEvent (QFocusEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive focus in events for this item.
The default implementation calls ensureVisible().
See also
focusOutEvent(), sceneEvent(), setFocus()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativeTextInput, QGraphicsWidget, and QGraphicsProxyWidget.
Definition at line 7364 of file qgraphicsitem.cpp.
Referenced by QDeclarativeTextInput::focusInEvent(), QDeclarativeTextEdit::focusInEvent(), and sceneEvent().
 {
     Q_UNUSED(event);
     update();
 }
focusItem()
QGraphicsItem * QGraphicsItem::focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
Since
4.6
If no descendant has input focus, 0 is returned.
See also
hasFocus(), setFocus(), QWidget::focusWidget()
Definition at line 3646 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::addItem(), QDeclarativeItemPrivate::focusChanged(), QDeclarativeItem::hasActiveFocus(), QGraphicsScenePrivate::mousePressEventHandler(), QGraphicsScenePrivate::sendTouchBeginEvent(), QGraphicsScenePrivate::setActivePanelHelper(), QGraphicsItemPrivate::setEnabledHelper(), QGraphicsItemPrivate::setFocusHelper(), QGraphicsItemPrivate::setParentItemHelper(), and QGraphicsItemPrivate::setVisibleHelper().
 {
     return d_ptr->subFocusItem;
 }
focusOutEvent()
void QGraphicsItem::focusOutEvent (QFocusEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive focus out events for this item.
The default implementation does nothing.
See also
focusInEvent(), sceneEvent(), setFocus()
Reimplemented in QGraphicsTextItem, QGraphicsWidget, and QGraphicsProxyWidget.
Definition at line 7376 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     Q_UNUSED(event);
     update();
 }
focusProxy()
QGraphicsItem * QGraphicsItem::focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
Since
4.6
See also
setFocusProxy(), setFocus(), hasFocus()
Definition at line 3578 of file qgraphicsitem.cpp.
Referenced by QDeclarativeKeysAttachedPrivate::finalFocusProxy(), and setFocusProxy().
 {
     return d_ptr->focusProxy;
 }
focusScopeItem()
QGraphicsItem * QGraphicsItem::focusScopeItem () const
Returns this item's focus scope item.
Warning
This function is not part of the public interface.
Definition at line 3659 of file qgraphicsitem.cpp.
Referenced by QDeclarativeItem::hasFocus().
 {
     return d_ptr->focusScopeItem;
 }
grabKeyboard()
void QGraphicsItem::grabKeyboard ()
Grabs the keyboard input.
Since
4.4
The item will receive all keyboard input to the scene until one of the following events occur:
The item becomes invisible
The item is removed from the scene
The item is deleted
The item calls ungrabKeyboard()
Another item calls grabKeyboard(); the item will regain the keyboard grab when the other item calls ungrabKeyboard().
When an item gains the keyboard grab, it receives a QEvent::GrabKeyboard event. When it loses the keyboard grab, it receives a QEvent::UngrabKeyboard event. These events can be used to detect when your item gains or loses the keyboard grab through other means than gaining input focus.
It is almost never necessary to explicitly grab the keyboard in Qt, as Qt grabs and releases it sensibly. In particular, Qt grabs the keyboard when your item gains input focus, and releases it when your item loses input focus, or when the item is hidden.
Note that only visible items can grab keyboard input. Calling grabKeyboard() on an invisible item has no effect.
Keyboard events are not affected.
See also
ungrabKeyboard(), grabMouse(), setFocus()
Definition at line 3769 of file qgraphicsitem.cpp.
 {
     if (!d_ptr->scene) {
         qWarning("QGraphicsItem::grabKeyboard: cannot grab keyboard without scene");
         return;
     }
     if (!d_ptr->visible) {
         qWarning("QGraphicsItem::grabKeyboard: cannot grab keyboard while invisible");
         return;
     }
     d_ptr->scene->d_func()->grabKeyboard(this);
 }
grabMouse()
void QGraphicsItem::grabMouse ()
Grabs the mouse input.
Since
4.4
This item will receive all mouse events for the scene until any of the following events occurs:
The item becomes invisible
The item is removed from the scene
The item is deleted
The item call ungrabMouse()
Another item calls grabMouse(); the item will regain the mouse grab when the other item calls ungrabMouse().
When an item gains the mouse grab, it receives a QEvent::GrabMouse event. When it loses the mouse grab, it receives a QEvent::UngrabMouse event. These events can be used to detect when your item gains or loses the mouse grab through other means than receiving mouse button events.
It is almost never necessary to explicitly grab the mouse in Qt, as Qt grabs and releases it sensibly. In particular, Qt grabs the mouse when you press a mouse button, and keeps the mouse grabbed until you release the last mouse button. Also, Qt::Popup widgets implicitly call grabMouse() when shown, and ungrabMouse() when hidden.
Note that only visible items can grab mouse input. Calling grabMouse() on an invisible item has no effect.
Keyboard events are not affected.
See also
QGraphicsScene::mouseGrabberItem(), ungrabMouse(), grabKeyboard()
Definition at line 3701 of file qgraphicsitem.cpp.
Referenced by QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), and QDeclarativePinchArea::updatePinch().
 {
     if (!d_ptr->scene) {
         qWarning("QGraphicsItem::grabMouse: cannot grab mouse without scene");
         return;
     }
     if (!d_ptr->visible) {
         qWarning("QGraphicsItem::grabMouse: cannot grab mouse while invisible");
         return;
     }
     d_ptr->scene->d_func()->grabMouse(this);
 }
graphicsEffect()
QGraphicsEffect * QGraphicsItem::graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
Since
4.6
Definition at line 2892 of file qgraphicsitem.cpp.
Referenced by ShaderEffectSource::attachSourceItem(), ShaderEffectSource::detachSourceItem(), QGraphicsItemPrivate::effectiveBoundingRect(), and ShaderEffectSource::markSourceItemDirty().
 {
     return d_ptr->graphicsEffect;
 }
group()
QGraphicsItemGroup * QGraphicsItem::group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
See also
QGraphicsItemGroup, QGraphicsScene::createItemGroup()
Definition at line 1594 of file qgraphicsitem.cpp.
Referenced by isSelected(), QGraphicsItemGroup::removeFromGroup(), setGroup(), and setSelected().
 {
     if (!d_ptr->isMemberOfGroup)
         return 0;
     QGraphicsItem *parent = const_cast<QGraphicsItem *>(this);
     while ((parent = parent->d_ptr->parent)) {
         if (QGraphicsItemGroup *group = qgraphicsitem_cast<QGraphicsItemGroup *>(parent))
             return group;
     }
     // Unreachable; if d_ptr->isMemberOfGroup is != 0, then one parent of this
     // item is a group item.
     return 0;
 }
handlesChildEvents()
bool QGraphicsItem::handlesChildEvents () const
Returns true if this item handles child events (i.
e., all events intended for any of its children are instead sent to this item); otherwise, false is returned.
This property is useful for item groups; it allows one item to handle events on behalf of its children, as opposed to its children handling their events individually.
The default is to return false; children handle their own events. The exception for this is if the item is a QGraphicsItemGroup, then it defaults to return true.
See also
setHandlesChildEvents()
Definition at line 3309 of file qgraphicsitem.cpp.
 {
     return d_ptr->handlesChildEvents;
 }
hasCursor()
bool QGraphicsItem::hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
By default, items don't have any cursor set. cursor() will return a standard pointing arrow cursor.
See also
unsetCursor()
Definition at line 2309 of file qgraphicsitem.cpp.
Referenced by QGraphicsViewPrivate::_q_unsetViewportCursor(), QGraphicsViewPrivate::mouseMoveEventHandler(), and setCursor().
 {
     return d_ptr->hasCursor;
 }
hasFocus()
bool QGraphicsItem::hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
See also
focusItem(), setFocus(), QGraphicsScene::setFocusItem(), isActive()
Definition at line 3409 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemPrivate::clearFocusHelper(), QGraphicsWidget::close(), QGraphicsProxyWidget::contextMenuEvent(), QGraphicsWidget::focusNextPrevChild(), hasFocus(), QWidget::hasFocus(), QGraphicsWidget::initStyleOption(), QGraphicsTextItem::mouseDoubleClickEvent(), QGraphicsWidget::paintWindowFrame(), setFlags(), QGraphicsWidget::setFocusPolicy(), setInputMethodHints(), and QGraphicsItemPrivate::setVisibleHelper().
 {
     if (!d_ptr->scene || !d_ptr->scene->isActive())
         return false;
     if (d_ptr->focusProxy)
         return d_ptr->focusProxy->hasFocus();
     if (d_ptr->scene->d_func()->focusItem != this)
         return false;
     return panel() == d_ptr->scene->d_func()->activePanel;
 }
hide()
void QGraphicsItem::hide () inline
Hides the item.
(Items are visible by default.)
This convenience function is equivalent to calling setVisible(false).
See also
show(), setVisible()
Definition at line 222 of file qgraphicsitem.h.
Referenced by QGraphicsWidget::close(), QmlJSDebugger::BoundingRectHighlighter::freeBoundingBox(), QmlJSDebugger::LiveSelectionRectangle::hide(), QmlJSDebugger::LiveSelectionIndicator::hide(), ShaderEffectSource::hideSource(), and ShaderEffectSource::setHideSource().
 { setVisible(false); }
hoverEnterEvent()
void QGraphicsItem::hoverEnterEvent (QGraphicsSceneHoverEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
The default implementation calls update(); otherwise it does nothing.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
See also
hoverMoveEvent(), hoverLeaveEvent(), sceneEvent(), setAcceptHoverEvents()
Reimplemented in QGraphicsTextItem, QDeclarativeMouseArea, and QGraphicsProxyWidget.
Definition at line 7391 of file qgraphicsitem.cpp.
Referenced by QDeclarativeMouseArea::hoverEnterEvent(), and sceneEvent().
 {
     Q_UNUSED(event);
     update();
 }
hoverLeaveEvent()
void QGraphicsItem::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive hover leave events for this item.
The default implementation calls update(); otherwise it does nothing.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
See also
hoverEnterEvent(), hoverMoveEvent(), sceneEvent(), setAcceptHoverEvents()
Reimplemented in QGraphicsTextItem, QGraphicsWidget, QDeclarativeMouseArea, and QGraphicsProxyWidget.
Definition at line 7419 of file qgraphicsitem.cpp.
Referenced by QDeclarativeMouseArea::hoverLeaveEvent(), and sceneEvent().
 {
     Q_UNUSED(event);
     update();
 }
hoverMoveEvent()
void QGraphicsItem::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive hover move events for this item.
The default implementation does nothing.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
See also
hoverEnterEvent(), hoverLeaveEvent(), sceneEvent(), setAcceptHoverEvents()
Reimplemented in QGraphicsTextItem, QGraphicsWidget, QDeclarativeMouseArea, and QGraphicsProxyWidget.
Definition at line 7405 of file qgraphicsitem.cpp.
Referenced by QDeclarativeMouseArea::hoverMoveEvent(), and sceneEvent().
 {
     Q_UNUSED(event);
 }
inputMethodEvent()
void QGraphicsItem::inputMethodEvent (QInputMethodEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive input method events for this item.
The default implementation ignores the event.
See also
inputMethodQuery(), sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativeTextInput, and QDeclarativeItem.
Definition at line 7752 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     event->ignore();
 }
inputMethodHints()
Qt::InputMethodHints QGraphicsItem::inputMethodHints () const
Returns the current input method hints of this item.
Input method hints are only relevant for input items. The hints are used by the input method to indicate how it should operate. For example, if the Qt::ImhNumbersOnly flag is set, the input method may change its visual components to reflect that only numbers can be entered.
The effect may vary between input method implementations.
Since
4.6
See also
setInputMethodHints(), inputMethodQuery(), QInputContext
Definition at line 7793 of file qgraphicsitem.cpp.
Referenced by QDeclarativeTextInputPrivate::updateInputMethodHints().
 {
     Q_D(const QGraphicsItem);
     return d->imHints;
 }
inputMethodQuery()
QVariant QGraphicsItem::inputMethodQuery (Qt::InputMethodQuery query) const protected virtual
This method is only relevant for input items.
It is used by the input method to query a set of properties of the item to be able to support complex input method operations, such as support for surrounding text and reconversions. query specifies which property is queried.
See also
inputMethodEvent(), QInputMethodEvent, QInputContext
Reimplemented in QGraphicsTextItem, QDeclarativeTextInput, QDeclarativeTextEdit, and QDeclarativeItem.
Definition at line 7766 of file qgraphicsitem.cpp.
Referenced by QDeclarativeItemAccessor::doInputMethodQuery(), and QDeclarativeItem::inputMethodQuery().
 {
     if (isWidget()) {
         // ### Qt 5: Remove. The reimplementation in
         // QGraphicsProxyWidget solves this problem (but requires a
         // recompile to take effect).
         return d_ptr->inputMethodQueryHelper(query);
     }
     Q_UNUSED(query);
     return QVariant();
 }
installSceneEventFilter()
void QGraphicsItem::installSceneEventFilter (QGraphicsItem * filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
To filter another item's events, install this item as an event filter for the other item. Example:
QGraphicsScene scene;
QGraphicsEllipseItem *ellipse = scene.addEllipse(QRectF(-10, -10, 20, 20));
QGraphicsLineItem *line = scene.addLine(QLineF(-10, -10, 20, 20));
line->installSceneEventFilter(ellipse);
// line's events are filtered by ellipse's sceneEventFilter() function.
ellipse->installSceneEventFilter(line);
// ellipse's events are filtered by line's sceneEventFilter() function.
An item can only filter events for other items in the same scene. Also, an item cannot filter its own events; instead, you can reimplement sceneEvent() directly.
Items must belong to a scene for scene event filters to be installed and used.
See also
removeSceneEventFilter(), sceneEventFilter(), sceneEvent()
Definition at line 7037 of file qgraphicsitem.cpp.
 {
     if (!d_ptr->scene) {
         qWarning("QGraphicsItem::installSceneEventFilter: event filters can only be installed"
                  " on items in a scene.");
         return;
     }
     if (d_ptr->scene != filterItem->scene()) {
         qWarning("QGraphicsItem::installSceneEventFilter: event filters can only be installed"
                  " on items in the same scene.");
         return;
     }
     d_ptr->scene->d_func()->installSceneEventFilter(this, filterItem);
 }
isActive()
bool QGraphicsItem::isActive () const
Returns true if this item is active; otherwise returns false.
Since
4.6
An item can only be active if the scene is active. An item is active if it is, or is a descendent of, an active panel. Items in non-active panels are not active.
Items that are not part of a panel follow scene activation when the scene has no active panel.
Only active items can gain input focus.
See also
QGraphicsScene::isActive(), QGraphicsScene::activePanel(), panel(), isPanel()
Definition at line 3363 of file qgraphicsitem.cpp.
Referenced by QGraphicsWidget::isActiveWindow(), QGraphicsWidget::paintWindowFrame(), and QGraphicsItemPrivate::setFocusHelper().
 {
     if (!d_ptr->scene || !d_ptr->scene->isActive())
         return false;
     return panel() == d_ptr->scene->activePanel();
 }
isAncestorOf()
bool QGraphicsItem::isAncestorOf (const QGraphicsItem * child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
See also
parentItem()
Definition at line 6872 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::cancelGesturesForChildren(), QGraphicsItemPrivate::clearSubFocus(), collidesWithItem(), QGraphicsWidgetPrivate::fixFocusChainBeforeReparenting(), QGraphicsScene::focusNextPrevChild(), isBlockedByModalPanel(), itemTransform(), QGraphicsItemPrivate::setParentItemHelper(), and QGraphicsItemPrivate::setVisibleHelper().
 {
     if (!child || child == this)
         return false;
     if (child->d_ptr->depth() < d_ptr->depth())
         return false;
     const QGraphicsItem *ancestor = child;
     while ((ancestor = ancestor->d_ptr->parent)) {
         if (ancestor == this)
             return true;
     }
     return false;
 }
isBlockedByModalPanel()
bool QGraphicsItem::isBlockedByModalPanel (QGraphicsItem ** blockingPanel = 0) const
Returns true if this item is blocked by a modal panel, false otherwise.
Since
4.6
If blockingPanel is non-zero, blockingPanel will be set to the modal panel that is blocking this item. If this item is not blocked, blockingPanel will not be set by this function.
This function always returns false for items not in a scene.
See also
panelModality() setPanelModality() PanelModality
Definition at line 2175 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::enterModal(), QGraphicsScenePrivate::itemAcceptsHoverEvents_helper(), QGraphicsScene::keyPressEvent(), QGraphicsScene::keyReleaseEvent(), QGraphicsScenePrivate::leaveModal(), QGraphicsScenePrivate::mousePressEventHandler(), and QGraphicsScenePrivate::sendMouseEvent().
 {
     if (!d_ptr->scene)
         return false;
     QGraphicsItem *dummy = 0;
     if (!blockingPanel)
         blockingPanel = &dummy;
     QGraphicsScenePrivate *scene_d = d_ptr->scene->d_func();
     if (scene_d->modalPanels.isEmpty())
         return false;
     // ###
     if (!scene_d->popupWidgets.isEmpty() && scene_d->popupWidgets.first() == this)
         return false;
     for (int i = 0; i < scene_d->modalPanels.count(); ++i) {
         QGraphicsItem *modalPanel = scene_d->modalPanels.at(i);
         if (modalPanel->panelModality() == QGraphicsItem::SceneModal) {
             // Scene modal panels block all non-descendents.
             if (modalPanel != this && !modalPanel->isAncestorOf(this)) {
                 *blockingPanel = modalPanel;
                 return true;
             }
         } else {
             // Window modal panels block ancestors and siblings/cousins.
             if (modalPanel != this
                 && !modalPanel->isAncestorOf(this)
                 && commonAncestorItem(modalPanel)) {
                 *blockingPanel = modalPanel;
                 return true;
             }
         }
     }
     return false;
 }
isClipped()
bool QGraphicsItem::isClipped () const
Returns true if this item is clipped.
An item is clipped if it has either set the ItemClipsToShape flag, or if it or any of its ancestors has set the ItemClipsChildrenToShape flag.
Clipping affects the item's appearance (i.e., painting), as well as mouse and hover event delivery.
See also
clipPath(), shape(), setFlags()
Definition at line 5185 of file qgraphicsitem.cpp.
Referenced by clipPath(), collidesWithItem(), collidesWithPath(), contains(), QGraphicsView::fitInView(), and QAbstractGraphicsShapeItem::opaqueArea().
 {
     Q_D(const QGraphicsItem);
     return (d->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren)
         || (d->flags & QGraphicsItem::ItemClipsToShape);
 }
isEnabled()
bool QGraphicsItem::isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
See also
setEnabled()
Definition at line 2604 of file qgraphicsitem.cpp.
Referenced by QShortcutMap::correctGraphicsWidgetContext(), QGraphicsScene::dragMoveEvent(), QGraphicsScene::focusNextPrevChild(), QGraphicsWidget::initStyleOption(), QGraphicsProxyWidget::itemChange(), QGraphicsScenePrivate::mousePressEventHandler(), QDeclarativeFlickable::sceneEventFilter(), QGraphicsScenePrivate::sendEvent(), QDeclarativeFlickable::sendMouseEvent(), QGraphicsScenePrivate::sendTouchBeginEvent(), QGraphicsScenePrivate::setFocusItemHelper(), QDeclarativeKeyNavigationAttached::setFocusNavigation(), and QGraphicsScene::wheelEvent().
 {
     return d_ptr->enabled;
 }
isObscured() [1/3]
bool QGraphicsItem::isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
Its implementation is based on calling isObscuredBy(), which you can reimplement to provide a custom obscurity algorithm.
See also
opaqueArea()
Definition at line 5412 of file qgraphicsitem.cpp.
 {
     return isObscured(QRectF());
 }
isObscured() [2/3]
bool QGraphicsItem::isObscured (const QRectF & rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.3
e., with a higher Z value than this item).
Unlike the default isObscured() function, this function does not call
isObscuredBy().
\sa opaqueArea()
Definition at line 5452 of file qgraphicsitem.cpp.
 {
     Q_D(const QGraphicsItem);
     if (!d->scene)
         return false;
     QRectF br = boundingRect();
     QRectF testRect = rect.isNull() ? br : rect;
     foreach (QGraphicsItem *item, d->scene->items(mapToScene(br), Qt::IntersectsItemBoundingRect)) {
         if (item == this)
             break;
         if (qt_QGraphicsItem_isObscured(this, item, testRect))
             return true;
     }
     return false;
 }
isObscured() [3/3]
bool QGraphicsItem::isObscured (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
Since
4.3
Definition at line 507 of file qgraphicsitem.h.
 { return isObscured(QRectF(ax, ay, w, h)); }
isObscuredBy()
bool QGraphicsItem::isObscuredBy (const QGraphicsItem * item) const virtual
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
The base implementation maps item's opaqueArea() to this item's coordinate system, and then checks if this item's boundingRect() is fully contained within the mapped shape.
You can reimplement this function to provide a custom algorithm for determining whether this item is obscured by item.
See also
opaqueArea(), isObscured()
Reimplemented in QGraphicsItemGroup, QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, QGraphicsPathItem, and QAbstractGraphicsShapeItem.
Definition at line 5493 of file qgraphicsitem.cpp.
Referenced by QAbstractGraphicsShapeItem::isObscuredBy(), QGraphicsLineItem::isObscuredBy(), QGraphicsPixmapItem::isObscuredBy(), QGraphicsTextItem::isObscuredBy(), QGraphicsItemGroup::isObscuredBy(), and QGraphicsLineItem::setLine().
 {
     if (!item)
         return false;
     return qt_closestItemFirst(item, this)
         && qt_QGraphicsItem_isObscured(this, item, boundingRect());
 }
isPanel()
bool QGraphicsItem::isPanel () const
Returns true if the item is a panel; otherwise returns false.
Since
4.6
See also
QGraphicsItem::panel(), ItemIsPanel
Definition at line 1876 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::addItem(), QGraphicsItemPrivate::clearSubFocus(), QGraphicsScenePrivate::dispatchHoverEvent(), QGraphicsScenePrivate::enterModal(), QGraphicsScene::event(), QGraphicsScene::focusNextPrevChild(), QGraphicsScenePrivate::gestureEventHandler(), QGraphicsScene::keyPressEvent(), QGraphicsScene::keyReleaseEvent(), QGraphicsScenePrivate::leaveModal(), QGraphicsScenePrivate::mousePressEventHandler(), QGraphicsScenePrivate::removeItemHelper(), sceneEvent(), QGraphicsScenePrivate::sendTouchBeginEvent(), QGraphicsScenePrivate::setActivePanelHelper(), QGraphicsItemPrivate::setEnabledHelper(), setPanelModality(), QGraphicsItemPrivate::setSubFocus(), QGraphicsItemPrivate::setVisibleHelper(), and QGraphicsScene::wheelEvent().
 {
     return d_ptr->flags & ItemIsPanel;
 }
isSelected()
bool QGraphicsItem::isSelected () const
Returns true if this item is selected; otherwise, false is returned.
Items that are in a group inherit the group's selected state.
Items are not selected by default.
See also
setSelected(), QGraphicsScene::setSelectionArea()
Definition at line 2714 of file qgraphicsitem.cpp.
Referenced by _qt_movableAncestorIsSelected(), QGraphicsScene::addItem(), isSelected(), mouseReleaseEvent(), QGraphicsItemPrivate::movableAncestorIsSelected(), QGraphicsScene::selectedItems(), setFlags(), and QGraphicsScene::setSelectionArea().
 {
     if (QGraphicsItemGroup *group = this->group())
         return group->isSelected();
     return d_ptr->selected;
 }
isUnderMouse()
bool QGraphicsItem::isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
Since
4,4
See also
QGraphicsScene::views(), QCursor::pos()
Definition at line 6932 of file qgraphicsitem.cpp.
Referenced by QGraphicsWidget::initStyleOption(), QDeclarativeMouseArea::itemChange(), and QDeclarativeMouseArea::setHoverEnabled().
 {
     Q_D(const QGraphicsItem);
     if (!d->scene)
         return false;
     QPoint cursorPos = QCursor::pos();
     foreach (QGraphicsView *view, d->scene->views()) {
         if (contains(mapFromScene(view->mapToScene(view->mapFromGlobal(cursorPos)))))
             return true;
     }
     return false;
 }
isVisible()
bool QGraphicsItem::isVisible () const
Returns true if the item is visible; otherwise, false is returned.
Note that the item's general visibility is unrelated to whether or not it is actually being visualized by a QGraphicsView.
See also
setVisible()
Definition at line 2343 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::addItem(), QGraphicsWidget::close(), QShortcutMap::correctGraphicsWidgetContext(), QDeclarativeGrid::doPositioning(), QGraphicsScene::event(), QDeclarativePinchArea::event(), ShaderEffectItem::handleVisibilityChange(), QDeclarativeItem::hasActiveFocus(), QDeclarativeKeysAttached::inputMethodEvent(), QDeclarativeKeysAttached::inputMethodQuery(), QGraphicsProxyWidget::itemChange(), QDeclarativeMouseArea::itemChange(), QDeclarativeKeysAttached::keyPressed(), QDeclarativeKeysAttached::keyReleased(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsScenePrivate::removePopup(), sceneEvent(), QDeclarativePathView::sceneEventFilter(), QDeclarativeFlickable::sceneEventFilter(), QDeclarativeMouseArea::sceneEventFilter(), QDeclarativePinchArea::sceneEventFilter(), QGraphicsScenePrivate::setActivePanelHelper(), QGraphicsItemPrivate::setFocusHelper(), QGraphicsScenePrivate::setFocusItemHelper(), QDeclarativeKeyNavigationAttached::setFocusNavigation(), setPanelModality(), QGraphicsItemPrivate::setVisibleHelper(), QGraphicsWidget::setWindowFlags(), ShaderEffectItem::ShaderEffectItem(), and QGraphicsWidget::updateGeometry().
 {
     return d_ptr->visible;
 }
isVisibleTo()
bool QGraphicsItem::isVisibleTo (const QGraphicsItem * parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
Since
4.4 parent can be 0, in which case this function will return whether the item is visible to the scene or not.
An item may not be visible to its ancestors even if isVisible() is true. It may also be visible to its ancestors even if isVisible() is false. If any ancestor is hidden, the item itself will be implicitly hidden, in which case this function will return false.
See also
isVisible(), setVisible()
Definition at line 2364 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::focusNextPrevChild().
 {
     const QGraphicsItem *p = this;
     if (d_ptr->explicitlyHidden)
         return false;
     do {
         if (p == parent)
             return true;
         if (p->d_ptr->explicitlyHidden)
             return false;
     } while ((p = p->d_ptr->parent));
     return parent == 0;
 }
isWidget()
bool QGraphicsItem::isWidget () const
Returns true if this item is a widget (i.
Since
4.4 e., QGraphicsWidget); otherwise, returns false.
Definition at line 1847 of file qgraphicsitem.cpp.
Referenced by _q_paintItem(), QDeclarativeLoaderPrivate::_q_updateSize(), QGraphicsLayoutPrivate::addChildLayoutItem(), QGraphicsScene::addItem(), QShortcutMap::correctGraphicsWidgetContext(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsWidgetPrivate::fixFocusChainBeforeReparenting(), QGraphicsScene::focusNextPrevChild(), QDeclarativeLoaderPrivate::initResize(), inputMethodQuery(), QGraphicsWidget::itemChange(), QGraphicsSceneIndexPrivate::itemCollidesWithPath(), QGraphicsScenePrivate::mousePressEventHandler(), parentWidget(), QGraphicsLayout::QGraphicsLayout(), QGraphicsLayoutPrivate::reparentChildItems(), QGraphicsScenePrivate::sendTouchBeginEvent(), QGraphicsItemPrivate::setEnabledHelper(), QGraphicsWidgetPrivate::setLayoutDirection_helper(), QGraphicsItemPrivate::setParentItemHelper(), QGraphicsScene::setStyle(), QGraphicsItemPrivate::setVisibleHelper(), QGraphicsGridLayoutPrivate::styleInfo(), QGraphicsLinearLayoutPrivate::styleInfo(), QGraphicsAnchorLayoutPrivate::styleInfo(), topLevelWidget(), QGraphicsProxyWidgetPrivate::unembedSubWindow(), QGraphicsWidgetPrivate::updateFont(), QGraphicsWidgetPrivate::updatePalette(), QGraphicsScene::wheelEvent(), and QGraphicsWidget::~QGraphicsWidget().
 {
     return d_ptr->isWidget;
 }
isWindow()
bool QGraphicsItem::isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
Since
4.4
See also
QGraphicsWidget::windowFlags()
Definition at line 1862 of file qgraphicsitem.cpp.
Referenced by _q_paintItem(), QGraphicsProxyWidget::event(), QGraphicsWidget::focusNextPrevChild(), QGraphicsWidget::initStyleOption(), QGraphicsSceneIndexPrivate::itemCollidesWithPath(), QGraphicsScene::setActiveWindow(), QGraphicsWidgetPrivate::updateFont(), QGraphicsWidgetPrivate::updatePalette(), and window().
 {
     return d_ptr->isWidget && (static_cast<const QGraphicsWidget *>(this)->windowType() & Qt::Window);
 }
itemChange()
QVariant QGraphicsItem::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
This virtual function is called by QGraphicsItem to notify custom items that some part of the item's state changes.
By reimplementing this function, your can react to a change, and in some cases, (depending on change,) adjustments can be made.
change is the parameter of the item that is changing. value is the new value; the type of the value depends on change.
Example:
QVariant Component::itemChange(GraphicsItemChange change, const QVariant &value)
{
    if (change == ItemPositionChange && scene()) {
        // value is the new position.
        QPointF newPos = value.toPointF();
        QRectF rect = scene()->sceneRect();
        if (!rect.contains(newPos)) {
            // Keep the item inside the scene rect.
            newPos.setX(qMin(rect.right(), qMax(newPos.x(), rect.left())));
            newPos.setY(qMin(rect.bottom(), qMax(newPos.y(), rect.top())));
            return newPos;
        }
    }
    return QGraphicsItem::itemChange(change, value);
}
The default implementation does nothing, and returns value.
Note: Certain QGraphicsItem functions cannot be called in a reimplementation of this function; see the GraphicsItemChange documentation for details.
See also
GraphicsItemChange
Reimplemented in QDeclarativePinchArea, QDeclarativeMouseArea, QGraphicsWidget, QDeclarativeItem, QDeclarativePaintedItem, QDeclarativeLoader, QDeclarativeRepeater, QDeclarativeBasePositioner, and QGraphicsProxyWidget.
Definition at line 7875 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::_q_polishItems(), QGraphicsScene::addItem(), QDeclarativeItem::itemChange(), QGraphicsWidget::itemChange(), QGraphicsScene::removeItem(), QGraphicsItemPrivate::sendScenePosChange(), setCursor(), setFlags(), setMatrix(), setOpacity(), setParentItem(), setPos(), setRotation(), setScale(), setSelected(), setToolTip(), setTransform(), setTransformOriginPoint(), QGraphicsItemPrivate::setVisibleHelper(), and setZValue().
 {
     Q_UNUSED(change);
     return value;
 }
itemTransform()
QTransform QGraphicsItem::itemTransform (const QGraphicsItem * other, bool * ok = 0) const
Returns a QTransform that maps coordinates from this item to other.
Since
4.5
If ok is not null, and if there is no such transform, the boolean pointed to by ok will be set to false; otherwise it will be set to true.
This transform provides an alternative to the mapToItem() or mapFromItem() functions, by returning the appropriate transform so that you can map shapes and coordinates yourself. It also helps you write more efficient code when repeatedly mapping between the same two items.
Note
In rare circumstances, there is no transform that maps between two items.
See also
mapToItem(), mapFromItem(), deviceTransform()
Definition at line 4530 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), clipPath(), QDeclarativeParentChangePrivate::doChange(), itemTransform(), mapFromItem(), mapRectFromItem(), mapRectToItem(), mapToItem(), mouseMoveEvent(), QGraphicsItemGroup::removeFromGroup(), and QDeclarativeParentAnimation::transition().
 {
     // Catch simple cases first.
     if (other == 0) {
         qWarning("QGraphicsItem::itemTransform: null pointer passed");
         return QTransform();
     }
     if (other == this) {
         if (ok)
             *ok = true;
         return QTransform();
     }
     QGraphicsItem *parent = d_ptr->parent;
     const QGraphicsItem *otherParent = other->d_ptr->parent;
     // This is other's child
     if (parent == other) {
         if (ok)
             *ok = true;
         QTransform x;
         d_ptr->combineTransformFromParent(&x);
         return x;
     }
     // This is other's parent
     if (otherParent == this) {
         const QPointF &otherPos = other->d_ptr->pos;
         if (other->d_ptr->transformData) {
             QTransform otherToParent;
             other->d_ptr->combineTransformFromParent(&otherToParent);
             return otherToParent.inverted(ok);
         }
         if (ok)
             *ok = true;
         return QTransform::fromTranslate(-otherPos.x(), -otherPos.y());
     }
     // Siblings
     if (parent == otherParent) {
         // COMBINE
         const QPointF &itemPos = d_ptr->pos;
         const QPointF &otherPos = other->d_ptr->pos;
         if (!d_ptr->transformData && !other->d_ptr->transformData) {
             QPointF delta = itemPos - otherPos;
             if (ok)
                 *ok = true;
             return QTransform::fromTranslate(delta.x(), delta.y());
         }
         QTransform itemToParent;
         d_ptr->combineTransformFromParent(&itemToParent);
         QTransform otherToParent;
         other->d_ptr->combineTransformFromParent(&otherToParent);
         return itemToParent * otherToParent.inverted(ok);
     }
     // Find the closest common ancestor. If the two items don't share an
     // ancestor, then the only way is to combine their scene transforms.
     const QGraphicsItem *commonAncestor = commonAncestorItem(other);
     if (!commonAncestor) {
         d_ptr->ensureSceneTransform();
         other->d_ptr->ensureSceneTransform();
         return d_ptr->sceneTransform * other->d_ptr->sceneTransform.inverted(ok);
     }
     // If the two items are cousins (in sibling branches), map both to the
     // common ancestor, and combine the two transforms.
     bool cousins = other != commonAncestor && this != commonAncestor;
     if (cousins) {
         bool good = false;
         QTransform thisToScene = itemTransform(commonAncestor, &good);
         QTransform otherToScene(Qt::Uninitialized);
         if (good)
             otherToScene = other->itemTransform(commonAncestor, &good);
         if (!good) {
             if (ok)
                 *ok = false;
             return QTransform();
         }
         return thisToScene * otherToScene.inverted(ok);
     }
     // One is an ancestor of the other; walk the chain.
     bool parentOfOther = isAncestorOf(other);
     const QGraphicsItem *child = parentOfOther ? other : this;
     const QGraphicsItem *root = parentOfOther ? this : other;
     QTransform x;
     const QGraphicsItem *p = child;
     do {
         p->d_ptr.data()->combineTransformToParent(&x);
     } while ((p = p->d_ptr->parent) && p != root);
     if (parentOfOther)
         return x.inverted(ok);
     if (ok)
         *ok = true;
     return x;
 }
keyPressEvent()
void QGraphicsItem::keyPressEvent (QKeyEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive key press events for this item.
The default implementation ignores the event. If you reimplement this handler, the event will by default be accepted.
Note that key events are only received for items that set the ItemIsFocusable flag, and that have keyboard input focus.
See also
keyReleaseEvent(), setFocus(), QGraphicsScene::setFocusItem(), sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativeTextInput, QDeclarativeListView, QDeclarativeGridView, QDeclarativeItem, and QGraphicsProxyWidget.
Definition at line 7437 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     event->ignore();
 }
keyReleaseEvent()
void QGraphicsItem::keyReleaseEvent (QKeyEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive key release events for this item.
The default implementation ignores the event. If you reimplement this handler, the event will by default be accepted.
Note that key events are only received for items that set the ItemIsFocusable flag, and that have keyboard input focus.
See also
keyPressEvent(), setFocus(), QGraphicsScene::setFocusItem(), sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativeItem, and QGraphicsProxyWidget.
Definition at line 7454 of file qgraphicsitem.cpp.
Referenced by sceneEvent().
 {
     event->ignore();
 }
mapFromItem() [1/6]
QPointF QGraphicsItem::mapFromItem (const QGraphicsItem * item, const QPointF & point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
If item is 0, this function returns the same as mapFromScene().
See also
itemTransform(), mapFromParent(), mapFromScene(), transform(), mapToItem(), {The Graphics View Coordinate System}
Definition at line 6633 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), collidesWithItem(), and QGraphicsItemPrivate::remapItemPos().
 {
     if (item)
         return item->itemTransform(this).map(point);
     return mapFromScene(point);
 }
mapFromItem() [2/6]
QPolygonF QGraphicsItem::mapFromItem (const QGraphicsItem * item, const QRectF & rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
If item is 0, this function returns the same as mapFromScene()
See also
itemTransform(), mapToItem(), mapFromParent(), transform(), {The Graphics View Coordinate System}
Definition at line 6711 of file qgraphicsitem.cpp.
 {
     if (item)
         return item->itemTransform(this).map(rect);
     return mapFromScene(rect);
 }
mapFromItem() [3/6]
QPolygonF QGraphicsItem::mapFromItem (const QGraphicsItem * item, const QPolygonF & polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
If item is 0, this function returns the same as mapFromScene().
See also
itemTransform(), mapToItem(), mapFromParent(), transform(), {The Graphics View Coordinate System}
Definition at line 6785 of file qgraphicsitem.cpp.
 {
     if (item)
         return item->itemTransform(this).map(polygon);
     return mapFromScene(polygon);
 }
mapFromItem() [4/6]
QPainterPath QGraphicsItem::mapFromItem (const QGraphicsItem * item, const QPainterPath & path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
If item is 0, this function returns the same as mapFromScene().
See also
itemTransform(), mapFromParent(), mapFromScene(), mapToItem(), {The Graphics View Coordinate System}
Definition at line 6830 of file qgraphicsitem.cpp.
 {
     if (item)
         return item->itemTransform(this).map(path);
     return mapFromScene(path);
 }
mapFromItem() [5/6]
QPointF QGraphicsItem::mapFromItem (const QGraphicsItem * item, qreal x, qreal y) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
Definition at line 515 of file qgraphicsitem.h.
 { return mapFromItem(item, QPointF(ax, ay)); }
mapFromItem() [6/6]
QPolygonF QGraphicsItem::mapFromItem (const QGraphicsItem * item, qreal x, qreal y, qreal w, qreal h) const inline
Since
4.3
This convenience function is equivalent to calling mapFromItem(item, QRectF(x, y, w, h)).
Definition at line 533 of file qgraphicsitem.h.
 { return mapFromItem(item, QRectF(ax, ay, w, h)); }
mapFromParent() [1/6]
QPointF QGraphicsItem::mapFromParent (const QPointF & point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
See also
mapFromItem(), mapFromScene(), transform(), mapToParent(), {The Graphics View Coordinate System}
Definition at line 6656 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (d_ptr->transformData)
         return d_ptr->transformToParent().inverted().map(point);
     return point - d_ptr->pos;
 }
mapFromParent() [2/6]
QPolygonF QGraphicsItem::mapFromParent (const QRectF & rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
See also
mapToParent(), mapFromItem(), transform(), {The Graphics View Coordinate System}
Definition at line 6733 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
         return rect.translated(-d_ptr->pos);
     return d_ptr->transformToParent().inverted().map(rect);
 }
mapFromParent() [3/6]
QPolygonF QGraphicsItem::mapFromParent (const QPolygonF & polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
See also
mapToParent(), mapToItem(), transform(), {The Graphics View Coordinate System}
Definition at line 6799 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
         return polygon.translated(-d_ptr->pos);
     return d_ptr->transformToParent().inverted().map(polygon);
 }
mapFromParent() [4/6]
QPainterPath QGraphicsItem::mapFromParent (const QPainterPath & path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
See also
mapFromScene(), mapFromItem(), mapToParent(), {The Graphics View Coordinate System}
Definition at line 6844 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
             return path.translated(-d_ptr->pos);
     return d_ptr->transformToParent().inverted().map(path);
 }
mapFromParent() [5/6]
QPointF QGraphicsItem::mapFromParent (qreal x, qreal y) const inline
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 517 of file qgraphicsitem.h.
 { return mapFromParent(QPointF(ax, ay));  }
mapFromParent() [6/6]
QPolygonF QGraphicsItem::mapFromParent (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
Since
4.3
Definition at line 535 of file qgraphicsitem.h.
 { return mapFromParent(QRectF(ax, ay, w, h)); }
mapFromScene() [1/6]
QPointF QGraphicsItem::mapFromScene (const QPointF & point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
See also
mapFromItem(), mapFromParent(), transform(), mapToScene(), {The Graphics View Coordinate System}
Definition at line 6683 of file qgraphicsitem.cpp.
Referenced by QGraphicsProxyWidget::event(), QDeclarativeMouseArea::geometryChanged(), isUnderMouse(), mapFromItem(), QDeclarativeMouseArea::mouseMoveEvent(), mouseMoveEvent(), QmlJSDebugger::LiveSelectionRectangle::rect(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), QDeclarativePinchArea::updatePinch(), and QGraphicsScenePrivate::updateTouchPointsForItem().
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return QPointF(point.x() - d_ptr->sceneTransform.dx(), point.y() - d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.inverted().map(point);
 }
mapFromScene() [2/6]
QPolygonF QGraphicsItem::mapFromScene (const QRectF & rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
See also
mapToScene(), mapFromItem(), transform(), {The Graphics View Coordinate System}
Definition at line 6759 of file qgraphicsitem.cpp.
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return rect.translated(-d_ptr->sceneTransform.dx(), -d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.inverted().map(rect);
 }
mapFromScene() [3/6]
QPolygonF QGraphicsItem::mapFromScene (const QPolygonF & polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
See also
mapToScene(), mapFromParent(), transform(), {The Graphics View Coordinate System}
Definition at line 6814 of file qgraphicsitem.cpp.
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return polygon.translated(-d_ptr->sceneTransform.dx(), -d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.inverted().map(polygon);
 }
mapFromScene() [4/6]
QPainterPath QGraphicsItem::mapFromScene (const QPainterPath & path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
See also
mapFromParent(), mapFromItem(), mapToScene(), {The Graphics View Coordinate System}
Definition at line 6859 of file qgraphicsitem.cpp.
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return path.translated(-d_ptr->sceneTransform.dx(), -d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.inverted().map(path);
 }
mapFromScene() [5/6]
QPointF QGraphicsItem::mapFromScene (qreal x, qreal y) const inline
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 519 of file qgraphicsitem.h.
 { return mapFromScene(QPointF(ax, ay));  }
mapFromScene() [6/6]
QPolygonF QGraphicsItem::mapFromScene (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
Since
4.3
Definition at line 537 of file qgraphicsitem.h.
 { return mapFromScene(QRectF(ax, ay, w, h)); }
mapRectFromItem() [1/2]
QRectF QGraphicsItem::mapRectFromItem (const QGraphicsItem * item, const QRectF & rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
Since
4.5
e., the bounding rectangle of the resulting polygon).
If \a item is 0, this function returns the same as mapRectFromScene().
\sa itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The
Graphics View Coordinate System}
Definition at line 6454 of file qgraphicsitem.cpp.
 {
     if (item)
         return item->itemTransform(this).mapRect(rect);
     return mapRectFromScene(rect);
 }
mapRectFromItem() [2/2]
QRectF QGraphicsItem::mapRectFromItem (const QGraphicsItem * item, qreal x, qreal y, qreal w, qreal h) const inline
Since
4.5
This convenience function is equivalent to calling mapRectFromItem(item, QRectF(x, y, w, h)).
Definition at line 539 of file qgraphicsitem.h.
 { return mapRectFromItem(item, QRectF(ax, ay, w, h)); }
mapRectFromParent() [1/2]
QRectF QGraphicsItem::mapRectFromParent (const QRectF & rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
Since
4.5
e., the bounding rectangle of the resulting polygon).
See also
itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The Graphics View Coordinate System}
Definition at line 6482 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
         return rect.translated(-d_ptr->pos);
     return d_ptr->transformToParent().inverted().mapRect(rect);
 }
mapRectFromParent() [2/2]
QRectF QGraphicsItem::mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
Since
4.5
Definition at line 541 of file qgraphicsitem.h.
 { return mapRectFromParent(QRectF(ax, ay, w, h)); }
mapRectFromScene() [1/2]
QRectF QGraphicsItem::mapRectFromScene (const QRectF & rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
Since
4.5
e., the bounding rectangle of the resulting polygon).
\sa itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The
Graphics View Coordinate System}
Definition at line 6513 of file qgraphicsitem.cpp.
Referenced by QmlJSDebugger::BoundingRectHighlighter::highlightAll(), mapRectFromItem(), and QmlJSDebugger::LiveSelectionIndicator::setItems().
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return rect.translated(-d_ptr->sceneTransform.dx(), -d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.inverted().mapRect(rect);
 }
mapRectFromScene() [2/2]
QRectF QGraphicsItem::mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
Since
4.5
Definition at line 543 of file qgraphicsitem.h.
 { return mapRectFromScene(QRectF(ax, ay, w, h)); }
mapRectToItem() [1/2]
QRectF QGraphicsItem::mapRectToItem (const QGraphicsItem * item, const QRectF & rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
Since
4.5
e., the bounding rectangle of the resulting polygon).
If \a item is 0, this function returns the same as mapRectToScene().
\sa itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The
Graphics View Coordinate System}
Definition at line 6364 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemPrivate::effectiveBoundingRect().
 {
     if (item)
         return itemTransform(item).mapRect(rect);
     return mapRectToScene(rect);
 }
mapRectToItem() [2/2]
QRectF QGraphicsItem::mapRectToItem (const QGraphicsItem * item, qreal x, qreal y, qreal w, qreal h) const inline
Since
4.5
This convenience function is equivalent to calling mapRectToItem(item, QRectF(x, y, w, h)).
Definition at line 527 of file qgraphicsitem.h.
 { return mapRectToItem(item, QRectF(ax, ay, w, h)); }
mapRectToParent() [1/2]
QRectF QGraphicsItem::mapRectToParent (const QRectF & rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
Since
4.5
e., the bounding rectangle of the resulting polygon).
\sa itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The
Graphics View Coordinate System}
Definition at line 6391 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
         return rect.translated(d_ptr->pos);
     return d_ptr->transformToParent().mapRect(rect);
 }
mapRectToParent() [2/2]
QRectF QGraphicsItem::mapRectToParent (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
Since
4.5
Definition at line 529 of file qgraphicsitem.h.
 { return mapRectToParent(QRectF(ax, ay, w, h)); }
mapRectToScene() [1/2]
QRectF QGraphicsItem::mapRectToScene (const QRectF & rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
Since
4.5
e., the bounding rectangle of the resulting polygon).
\sa itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The
Graphics View Coordinate System}
Definition at line 6422 of file qgraphicsitem.cpp.
Referenced by mapRectToItem(), QmlJSDebugger::SubcomponentMaskLayerItem::setCurrentItem(), and QmlJSDebugger::LiveSelectionIndicator::setItems().
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return rect.translated(d_ptr->sceneTransform.dx(), d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.mapRect(rect);
 }
mapRectToScene() [2/2]
QRectF QGraphicsItem::mapRectToScene (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
Since
4.5
Definition at line 531 of file qgraphicsitem.h.
 { return mapRectToScene(QRectF(ax, ay, w, h)); }
mapToItem() [1/6]
QPointF QGraphicsItem::mapToItem (const QGraphicsItem * item, const QPointF & point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
If item is 0, this function returns the same as mapToScene().
See also
itemTransform(), mapToParent(), mapToScene(), transform(), mapFromItem(), {The Graphics View Coordinate System}
Definition at line 6208 of file qgraphicsitem.cpp.
Referenced by qt_QGraphicsItem_isObscured(), and QGraphicsItemGroup::removeFromGroup().
 {
     if (item)
         return itemTransform(item).map(point);
     return mapToScene(point);
 }
mapToItem() [2/6]
QPolygonF QGraphicsItem::mapToItem (const QGraphicsItem * item, const QRectF & rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
If item is 0, this function returns the same as mapToScene().
See also
itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The Graphics View Coordinate System}
Definition at line 6284 of file qgraphicsitem.cpp.
 {
     if (item)
         return itemTransform(item).map(rect);
     return mapToScene(rect);
 }
mapToItem() [3/6]
QPolygonF QGraphicsItem::mapToItem (const QGraphicsItem * item, const QPolygonF & polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
If item is 0, this function returns the same as mapToScene().
See also
itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The Graphics View Coordinate System}
Definition at line 6539 of file qgraphicsitem.cpp.
 {
     if (item)
         return itemTransform(item).map(polygon);
     return mapToScene(polygon);
 }
mapToItem() [4/6]
QPainterPath QGraphicsItem::mapToItem (const QGraphicsItem * item, const QPainterPath & path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
If item is 0, this function returns the same as mapToScene().
See also
itemTransform(), mapToParent(), mapToScene(), mapFromItem(), {The Graphics View Coordinate System}
Definition at line 6586 of file qgraphicsitem.cpp.
 {
     if (item)
         return itemTransform(item).map(path);
     return mapToScene(path);
 }
mapToItem() [5/6]
QPointF QGraphicsItem::mapToItem (const QGraphicsItem * item, qreal x, qreal y) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
Definition at line 509 of file qgraphicsitem.h.
 { return mapToItem(item, QPointF(ax, ay)); }
mapToItem() [6/6]
QPolygonF QGraphicsItem::mapToItem (const QGraphicsItem * item, qreal x, qreal y, qreal w, qreal h) const inline
Since
4.3
This convenience function is equivalent to calling mapToItem(item, QRectF(x, y, w, h)).
Definition at line 521 of file qgraphicsitem.h.
 { return mapToItem(item, QRectF(ax, ay, w, h)); }
mapToParent() [1/6]
QPointF QGraphicsItem::mapToParent (const QPointF & point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
If the item has no parent, point will be mapped to the scene's coordinate system.
See also
mapToItem(), mapToScene(), transform(), mapFromParent(), {The Graphics View Coordinate System}
Definition at line 6231 of file qgraphicsitem.cpp.
Referenced by mouseMoveEvent().
 {
     // COMBINE
     if (!d_ptr->transformData)
         return point + d_ptr->pos;
     return d_ptr->transformToParent().map(point);
 }
mapToParent() [2/6]
QPolygonF QGraphicsItem::mapToParent (const QRectF & rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
If the item has no parent, rect will be mapped to the scene's coordinate system.
See also
mapToScene(), mapToItem(), mapFromParent(), {The Graphics View Coordinate System}
Definition at line 6307 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
         return rect.translated(d_ptr->pos);
     return d_ptr->transformToParent().map(rect);
 }
mapToParent() [3/6]
QPolygonF QGraphicsItem::mapToParent (const QPolygonF & polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
If the item has no parent, polygon will be mapped to the scene's coordinate system.
See also
mapToScene(), mapToItem(), mapFromParent(), {The Graphics View Coordinate System}
Definition at line 6555 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
         return polygon.translated(d_ptr->pos);
     return d_ptr->transformToParent().map(polygon);
 }
mapToParent() [4/6]
QPainterPath QGraphicsItem::mapToParent (const QPainterPath & path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
If the item has no parent, path will be mapped to the scene's coordinate system.
See also
mapToScene(), mapToItem(), mapFromParent(), {The Graphics View Coordinate System}
Definition at line 6602 of file qgraphicsitem.cpp.
 {
     // COMBINE
     if (!d_ptr->transformData)
         return path.translated(d_ptr->pos);
     return d_ptr->transformToParent().map(path);
 }
mapToParent() [5/6]
QPointF QGraphicsItem::mapToParent (qreal x, qreal y) const inline
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 511 of file qgraphicsitem.h.
 { return mapToParent(QPointF(ax, ay)); }
mapToParent() [6/6]
QPolygonF QGraphicsItem::mapToParent (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
Since
4.3
Definition at line 523 of file qgraphicsitem.h.
 { return mapToParent(QRectF(ax, ay, w, h)); }
mapToScene() [1/6]
QPointF QGraphicsItem::mapToScene (const QPointF & point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
See also
mapToItem(), mapToParent(), transform(), mapFromScene(), {The Graphics View Coordinate System}
Definition at line 6257 of file qgraphicsitem.cpp.
Referenced by QDeclarativeMouseArea::geometryChanged(), QmlJSDebugger::BoundingRectHighlighter::highlightAll(), isObscured(), mapToItem(), scenePos(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), and QDeclarativePinchArea::sendMouseEvent().
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return QPointF(point.x() + d_ptr->sceneTransform.dx(), point.y() + d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.map(point);
 }
mapToScene() [2/6]
QPolygonF QGraphicsItem::mapToScene (const QRectF & rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
See also
mapToParent(), mapToItem(), mapFromScene(), {The Graphics View Coordinate System}
Definition at line 6332 of file qgraphicsitem.cpp.
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return rect.translated(d_ptr->sceneTransform.dx(), d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.map(rect);
 }
mapToScene() [3/6]
QPolygonF QGraphicsItem::mapToScene (const QPolygonF & polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
See also
mapToParent(), mapToItem(), mapFromScene(), {The Graphics View Coordinate System}
Definition at line 6570 of file qgraphicsitem.cpp.
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return polygon.translated(d_ptr->sceneTransform.dx(), d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.map(polygon);
 }
mapToScene() [4/6]
QPainterPath QGraphicsItem::mapToScene (const QPainterPath & path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
See also
mapToParent(), mapToItem(), mapFromScene(), {The Graphics View Coordinate System}
Definition at line 6617 of file qgraphicsitem.cpp.
 {
     if (d_ptr->hasTranslateOnlySceneTransform())
         return path.translated(d_ptr->sceneTransform.dx(), d_ptr->sceneTransform.dy());
     return d_ptr->sceneTransform.map(path);
 }
mapToScene() [5/6]
QPointF QGraphicsItem::mapToScene (qreal x, qreal y) const inline
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 513 of file qgraphicsitem.h.
 { return mapToScene(QPointF(ax, ay));  }
mapToScene() [6/6]
QPolygonF QGraphicsItem::mapToScene (qreal x, qreal y, qreal w, qreal h) const inline
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
Since
4.3
Definition at line 525 of file qgraphicsitem.h.
 { return mapToScene(QRectF(ax, ay, w, h)); }
matrix()
QMatrix QGraphicsItem::matrix () const
Returns the item's affine transformation matrix.
This is a subset or the item's full transformation matrix, and might not represent the item's full transformation.
Use transform() instead.
See also
setTransform(), sceneTransform()
Definition at line 4050 of file qgraphicsitem.cpp.
Referenced by deviceTransform(), ShaderEffectItem::meshResolution(), ShaderEffectItem::renderEffect(), and QGraphicsItemAnimation::reset().
 {
     return transform().toAffine();
 }
mouseDoubleClickEvent()
void QGraphicsItem::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
When doubleclicking an item, the item will first receive a mouse press event, followed by a release event (i.e., a click), then a doubleclick event, and finally a release event.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation calls mousePressEvent(). If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseDoubleClickEvent() in your reimplementation.
Note that an item will not receive double click events if it is neither QGraphicsItem::ItemIsSelectable{selectable} nor movable (single mouse clicks are ignored in this case, and that stops the generation of double clicks).
See also
mousePressEvent(), mouseMoveEvent(), mouseReleaseEvent(), sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativeTextInput, QDeclarativeMouseArea, and QGraphicsProxyWidget.
Definition at line 7721 of file qgraphicsitem.cpp.
Referenced by QDeclarativeMouseArea::mouseDoubleClickEvent(), QDeclarativeTextInput::mouseDoubleClickEvent(), QDeclarativeTextEdit::mouseDoubleClickEvent(), QGraphicsTextItem::mouseDoubleClickEvent(), and sceneEvent().
 {
     mousePressEvent(event);
 }
mouseMoveEvent()
void QGraphicsItem::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
If you do receive this event, you can be certain that this item also received a mouse press event, and that this item is the current mouse grabber.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseMoveEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativePinchArea, QDeclarativeTextInput, QDeclarativeMouseArea, QDeclarativeFlickable, QDeclarativePathView, and QGraphicsProxyWidget.
Definition at line 7556 of file qgraphicsitem.cpp.
Referenced by QDeclarativePathView::mouseMoveEvent(), QDeclarativeFlickable::mouseMoveEvent(), QDeclarativeMouseArea::mouseMoveEvent(), QDeclarativeTextInput::mouseMoveEvent(), QDeclarativePinchArea::mouseMoveEvent(), QDeclarativeTextEdit::mouseMoveEvent(), QGraphicsTextItem::mouseMoveEvent(), and sceneEvent().
 {
     if ((event->buttons() & Qt::LeftButton) && (flags() & ItemIsMovable)) {
         // Determine the list of items that need to be moved.
         QList<QGraphicsItem *> selectedItems;
         QMap<QGraphicsItem *, QPointF> initialPositions;
         if (d_ptr->scene) {
             selectedItems = d_ptr->scene->selectedItems();
             initialPositions = d_ptr->scene->d_func()->movingItemsInitialPositions;
             if (initialPositions.isEmpty()) {
                 foreach (QGraphicsItem *item, selectedItems)
                     initialPositions[item] = item->pos();
                 initialPositions[this] = pos();
             }
             d_ptr->scene->d_func()->movingItemsInitialPositions = initialPositions;
         }
         // Find the active view.
         QGraphicsView *view = 0;
         if (event->widget())
             view = qobject_cast<QGraphicsView *>(event->widget()->parentWidget());
         // Move all selected items
         int i = 0;
         bool movedMe = false;
         while (i <= selectedItems.size()) {
             QGraphicsItem *item = 0;
             if (i < selectedItems.size())
                 item = selectedItems.at(i);
             else
                 item = this;
             if (item == this) {
                 // Slightly clumsy-looking way to ensure that "this" is part
                 // of the list of items to move, this is to avoid allocations
                 // (appending this item to the list of selected items causes a
                 // detach).
                 if (movedMe)
                     break;
                 movedMe = true;
             }
             if ((item->flags() & ItemIsMovable) && !QGraphicsItemPrivate::movableAncestorIsSelected(item)) {
                 QPointF currentParentPos;
                 QPointF buttonDownParentPos;
                 if (item->d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorIgnoresTransformations) {
                     // Items whose ancestors ignore transformations need to
                     // map screen coordinates to local coordinates, then map
                     // those to the parent.
                     QTransform viewToItemTransform = (item->deviceTransform(view->viewportTransform())).inverted();
                     currentParentPos = mapToParent(viewToItemTransform.map(QPointF(view->mapFromGlobal(event->screenPos()))));
                     buttonDownParentPos = mapToParent(viewToItemTransform.map(QPointF(view->mapFromGlobal(event->buttonDownScreenPos(Qt::LeftButton)))));
                 } else if (item->flags() & ItemIgnoresTransformations) {
                     // Root items that ignore transformations need to
                     // calculate their diff by mapping viewport coordinates
                     // directly to parent coordinates.
                     // COMBINE
                     QTransform itemTransform;
                     if (item->d_ptr->transformData)
                         itemTransform = item->d_ptr->transformData->computedFullTransform();
                     itemTransform.translate(item->d_ptr->pos.x(), item->d_ptr->pos.y());
                     QTransform viewToParentTransform = itemTransform
                                                        * (item->sceneTransform() * view->viewportTransform()).inverted();
                     currentParentPos = viewToParentTransform.map(QPointF(view->mapFromGlobal(event->screenPos())));
                     buttonDownParentPos = viewToParentTransform.map(QPointF(view->mapFromGlobal(event->buttonDownScreenPos(Qt::LeftButton))));
                 } else {
                     // All other items simply map from the scene.
                     currentParentPos = item->mapToParent(item->mapFromScene(event->scenePos()));
                     buttonDownParentPos = item->mapToParent(item->mapFromScene(event->buttonDownScenePos(Qt::LeftButton)));
                 }
                 item->setPos(initialPositions.value(item) + currentParentPos - buttonDownParentPos);
                 if (item->flags() & ItemIsSelectable)
                     item->setSelected(true);
             }
             ++i;
         }
     } else {
         event->ignore();
     }
 }
mousePressEvent()
void QGraphicsItem::mousePressEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
Mouse press events are only delivered to items that accept the mouse button that is pressed. By default, an item accepts all mouse buttons, but you can change this by calling setAcceptedMouseButtons().
The mouse press event decides which item should become the mouse grabber (see QGraphicsScene::mouseGrabberItem()). If you do not reimplement this function, the press event will propagate to any topmost item beneath this item, and no other mouse events will be delivered to this item.
If you do reimplement this function, event will by default be accepted (see QEvent::accept()), and this item is then the mouse grabber. This allows the item to receive future move, release and doubleclick events. If you call QEvent::ignore() on event, this item will lose the mouse grab, and event will propagate to any topmost item beneath. No further mouse events will be delivered to this item unless a new mouse press event is received.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mousePressEvent() in your reimplementation.
The event is for items that are neither QGraphicsItem::ItemIsMovable "movable" nor QGraphicsItem::ItemIsSelectable "selectable". mouseMoveEvent(), mouseReleaseEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativePinchArea, QDeclarativeTextInput, QDeclarativeText, QDeclarativeMouseArea, QDeclarativeFlickable, QDeclarativePathView, and QGraphicsProxyWidget.
Definition at line 7492 of file qgraphicsitem.cpp.
Referenced by mouseDoubleClickEvent(), QDeclarativePathView::mousePressEvent(), QDeclarativeFlickable::mousePressEvent(), QDeclarativeMouseArea::mousePressEvent(), QDeclarativeText::mousePressEvent(), QDeclarativePinchArea::mousePressEvent(), QDeclarativeTextEdit::mousePressEvent(), QGraphicsTextItem::mousePressEvent(), and sceneEvent().
 {
     if (event->button() == Qt::LeftButton && (flags() & ItemIsSelectable)) {
         bool multiSelect = (event->modifiers() & Qt::ControlModifier) != 0;
         if (!multiSelect) {
             if (!d_ptr->selected) {
                 if (QGraphicsScene *scene = d_ptr->scene) {
                     ++scene->d_func()->selectionChanging;
                     scene->clearSelection();
                     --scene->d_func()->selectionChanging;
                 }
                 setSelected(true);
             }
         }
     } else if (!(flags() & ItemIsMovable)) {
         event->ignore();
     }
     if (d_ptr->isWidget) {
         // Qt::Popup closes when you click outside.
         QGraphicsWidget *w = static_cast<QGraphicsWidget *>(this);
         if ((w->windowFlags() & Qt::Popup) == Qt::Popup) {
             event->accept();
             if (!w->rect().contains(event->pos()))
                 w->close();
         }
     }
 }
mouseReleaseEvent()
void QGraphicsItem::mouseReleaseEvent (QGraphicsSceneMouseEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
Calling QEvent::ignore() or QEvent::accept() on event has no effect.
The default implementation handles basic item interaction, such as selection and moving. If you want to keep the base implementation when reimplementing this function, call QGraphicsItem::mouseReleaseEvent() in your reimplementation.
Please note that mousePressEvent() decides which graphics item it is that receives mouse events. See the mousePressEvent() description for details.
See also
mousePressEvent(), mouseMoveEvent(), mouseDoubleClickEvent(), sceneEvent()
Reimplemented in QGraphicsTextItem, QDeclarativeTextEdit, QDeclarativePinchArea, QDeclarativeTextInput, QDeclarativeText, QDeclarativeFlickable, QDeclarativeMouseArea, QDeclarativePathView, and QGraphicsProxyWidget.
Definition at line 7658 of file qgraphicsitem.cpp.
Referenced by QDeclarativePathView::mouseReleaseEvent(), QDeclarativeMouseArea::mouseReleaseEvent(), QDeclarativeFlickable::mouseReleaseEvent(), QDeclarativeText::mouseReleaseEvent(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativePinchArea::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), QGraphicsTextItem::mouseReleaseEvent(), and sceneEvent().
 {
     if (event->button() == Qt::LeftButton && (flags() & ItemIsSelectable)) {
         bool multiSelect = (event->modifiers() & Qt::ControlModifier) != 0;
         if (event->scenePos() == event->buttonDownScenePos(Qt::LeftButton)) {
             // The item didn't move
             if (multiSelect) {
                 setSelected(!isSelected());
             } else {
                 bool selectionChanged = false;
                 if (QGraphicsScene *scene = d_ptr->scene) {
                     ++scene->d_func()->selectionChanging;
                     // Clear everything but this item. Bypass
                     // QGraphicsScene::clearSelection()'s default behavior by
                     // temporarily removing this item from the selection list.
                     if (d_ptr->selected) {
                         scene->d_func()->selectedItems.remove(this);
                         foreach (QGraphicsItem *item, scene->d_func()->selectedItems) {
                             if (item->isSelected()) {
                                 selectionChanged = true;
                                 break;
                             }
                         }
                     }
                     scene->clearSelection();
                     if (d_ptr->selected)
                         scene->d_func()->selectedItems.insert(this);
                     --scene->d_func()->selectionChanging;
                     if (selectionChanged)
                         emit d_ptr->scene->selectionChanged();
                 }
                 setSelected(true);
             }
         }
     }
     if (d_ptr->scene && !event->buttons())
         d_ptr->scene->d_func()->movingItemsInitialPositions.clear();
 }
moveBy()
void QGraphicsItem::moveBy (qreal dx, qreal dy) inline
Moves the item by dx points horizontally, and dy point vertically.
This function is equivalent to calling setPos(pos() + QPointF(dx, dy)).
Definition at line 287 of file qgraphicsitem.h.
Referenced by QDeclarativeListView::itemsMoved().
 { setPos(pos().x() + dx, pos().y() + dy); }
opacity()
qreal QGraphicsItem::opacity () const
Returns this item's local opacity, which is between 0.
Since
4.5
0 (transparent) and 1.0 (opaque). This value is combined with parent and ancestor values into the effectiveOpacity(). The effective opacity decides how the item is rendered.
The opacity property decides the state of the painter passed to the paint() function. If the item is cached, i.e., ItemCoordinateCache or DeviceCoordinateCache, the effective property will be applied to the item's cache as it is rendered.
The default opacity is 1.0; fully opaque.
See also
setOpacity(), paint(), ItemIgnoresParentOpacity, ItemDoesntPropagateOpacityToChildren
Definition at line 2800 of file qgraphicsitem.cpp.
 {
     return d_ptr->opacity;
 }
opaqueArea()
QPainterPath QGraphicsItem::opaqueArea () const virtual
This virtual function returns a shape representing the area where this item is opaque.
An area is opaque if it is filled using an opaque brush or color (i.e., not transparent).
This function is used by isObscuredBy(), which is called by underlying items to determine if they are obscured by this item.
The default implementation returns an empty QPainterPath, indicating that this item is completely transparent and does not obscure any other items.
See also
isObscuredBy(), isObscured(), shape()
Reimplemented in QGraphicsItemGroup, QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, QGraphicsPathItem, and QAbstractGraphicsShapeItem.
Definition at line 5514 of file qgraphicsitem.cpp.
Referenced by QAbstractGraphicsShapeItem::opaqueArea(), QGraphicsLineItem::opaqueArea(), QGraphicsTextItem::opaqueArea(), QGraphicsItemGroup::opaqueArea(), qt_QGraphicsItem_isObscured(), and QGraphicsLineItem::setLine().
 {
     return QPainterPath();
 }
paint()
void QGraphicsItem::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) pure virtual
This function, which is usually called by QGraphicsView, paints the contents of an item in local coordinates.
Reimplement this function in a QGraphicsItem subclass to provide the item's painting implementation, using painter. The option parameter provides style options for the item, such as its state, exposed area and its level-of-detail hints. The widget argument is optional. If provided, it points to the widget that is being painted on; otherwise, it is 0. For cached painting, widget is always 0.
void RoundRectItem::paint(QPainter *painter,
                          const QStyleOptionGraphicsItem *option,
                          QWidget *widget)
{
    painter->drawRoundedRect(-10, -10, 20, 20, 5, 5);
}
The painter's pen is 0-width by default, and its pen is initialized to the QPalette::Text brush from the paint device's palette. The brush is initialized to QPalette::Window.
Make sure to constrain all painting inside the boundaries of boundingRect() to avoid rendering artifacts (as QGraphicsView does not clip the painter for you). In particular, when QPainter renders the outline of a shape using an assigned QPen, half of the outline will be drawn outside, and half inside, the shape you're rendering (e.g., with a pen width of 2 units, you must draw outlines 1 unit inside boundingRect()). QGraphicsItem does not support use of cosmetic pens with a non-zero width.
All painting is done in local coordinates.
See also
setCacheMode(), QPen::width(), {Item Coordinates}, ItemUsesExtendedStyleOption
Implemented in QGraphicsItemGroup, QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, QGraphicsPathItem, QDeclarativeParticlesPainter, QDeclarativeParticles, QGraphicsWidget, QDeclarativeText, QDeclarativeRectangle, QDeclarativeItem, QDeclarativePaintedItem, QGraphicsSvgItem, QDeclarativeBorderImage, QDeclarativeImage, QGraphicsProxyWidget, ShaderEffectItem, and QmlJSDebugger::LiveLayerItem.
Referenced by _q_paintItem(), boundingRegion(), QGraphicsScenePrivate::draw(), and QGraphicsLineItem::setLine().
panel()
QGraphicsItem * QGraphicsItem::panel () const
Returns the item's panel, or 0 if this item does not have a panel.
Since
4.6
If the item is a panel, it will return itself. Otherwise it will return the closest ancestor that is a panel.
See also
isPanel(), ItemIsPanel
Definition at line 1737 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::dispatchHoverEvent(), hasFocus(), isActive(), panel(), QGraphicsScenePrivate::setActivePanelHelper(), QGraphicsScene::setActiveWindow(), QGraphicsItemPrivate::setFocusHelper(), QGraphicsItemPrivate::setSubFocus(), and window().
 {
     if (d_ptr->flags & ItemIsPanel)
         return const_cast<QGraphicsItem *>(this);
     return d_ptr->parent ? d_ptr->parent->panel() : 0;
 }
panelModality()
QGraphicsItem::PanelModality QGraphicsItem::panelModality () const
Returns the modality for this item.
Since
4.6
Definition at line 2132 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::addItem(), isBlockedByModalPanel(), QGraphicsScenePrivate::mousePressEventHandler(), QGraphicsScenePrivate::removeItemHelper(), setPanelModality(), and QGraphicsItemPrivate::setVisibleHelper().
 {
     return d_ptr->panelModality;
 }
parentItem()
QGraphicsItem * QGraphicsItem::parentItem () const
Returns a pointer to this item's parent item.
If this item does not have a parent, 0 is returned.
See also
setParentItem(), childItems()
Definition at line 1631 of file qgraphicsitem.cpp.
Referenced by _qt_movableAncestorIsSelected(), QGraphicsLayoutPrivate::addChildLayoutItem(), QDeclarativeAnchorsPrivate::calcStretch(), QDeclarativeAnchorsPrivate::centerInChanged(), QDeclarativeAnchorsPrivate::checkHAnchorValid(), QDeclarativeAnchorsPrivate::checkVAnchorValid(), collidesWithItem(), QGraphicsScene::createItemGroup(), deviceTransform(), QGraphicsScenePrivate::dispatchHoverEvent(), QGraphicsScene::event(), QDeclarativeAnchorsPrivate::fillChanged(), QGraphicsScenePrivate::filterDescendantEvent(), QDeclarativeItem::forceActiveFocus(), QGraphicsScenePrivate::gestureEventHandler(), QDeclarativeItem::hasFocus(), QGraphicsScene::keyPressEvent(), QGraphicsScene::keyReleaseEvent(), QDeclarativeMouseArea::mouseMoveEvent(), operator<<(), QDeclarativeItem::parentItem(), parentWidget(), QGraphicsScenePrivate::removeItemHelper(), QGraphicsLayoutPrivate::reparentChildItems(), sceneBoundingRect(), QGraphicsItemPrivate::sceneEffectiveBoundingRect(), QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), QGraphicsScenePrivate::setActivePanelHelper(), QGraphicsScene::setActiveWindow(), QDeclarativeAnchors::setCenterIn(), QDeclarativeAnchors::setFill(), stackBefore(), topLevelItem(), QGraphicsScenePrivate::updateFont(), QGraphicsWidget::updateGeometry(), QDeclarativeAnchorsPrivate::updateHorizontalAnchors(), QGraphicsScenePrivate::updatePalette(), QDeclarativeAnchorsPrivate::updateVerticalAnchors(), and QDeclarativeItem::~QDeclarativeItem().
 {
     return d_ptr->parent;
 }
parentObject()
QGraphicsObject * QGraphicsItem::parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
Since
4.6
returns 0 if the parent item is not a QGraphicsObject.
See also
parentItem(), childItems()
Definition at line 1662 of file qgraphicsitem.cpp.
Referenced by QGestureManager::filterEvent().
 {
     QGraphicsItem *p = d_ptr->parent;
     return (p && p->d_ptr->isObject) ? static_cast<QGraphicsObject *>(p) : 0;
 }
parentWidget()
QGraphicsWidget * QGraphicsItem::parentWidget () const
Returns a pointer to the item's parent widget.
Since
4.4
The item's parent widget is the closest parent item that is a widget.
See also
parentItem(), childItems()
Definition at line 1679 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::addItem(), QShortcutMap::correctGraphicsWidgetContext(), QGraphicsWidget::focusNextPrevChild(), QGraphicsWidgetPrivate::naturalWidgetFont(), QGraphicsWidgetPrivate::naturalWidgetPalette(), QGraphicsWidgetPrivate::resolveFont(), QGraphicsItemPrivate::setEnabledHelper(), QGraphicsWidgetPrivate::setLayoutDirection_helper(), QGraphicsItemPrivate::setVisibleHelper(), topLevelWidget(), and QGraphicsWidget::updateGeometry().
 {
     QGraphicsItem *p = parentItem();
     while (p && !p->isWidget())
         p = p->parentItem();
     return (p && p->isWidget()) ? static_cast<QGraphicsWidget *>(p) : 0;
 }
pos()
QPointF QGraphicsItem::pos () const
Returns the position of the item in parent coordinates.
If the item has no parent, its position is given in scene coordinates.
The position of the item describes its origin (local coordinate (0, 0)) in parent coordinates; this function returns the same as mapToParent(0, 0).
For convenience, you can also call scenePos() to determine the item's position in scene coordinates, regardless of its parent.
See also
x(), y(), setPos(), transform(), {The Graphics View Coordinate System}
Definition at line 3813 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsProxyWidget::contextMenuEvent(), deviceTransform(), QGraphicsProxyWidget::event(), QGraphicsWidget::insertAction(), QDeclarativeListView::itemsInserted(), ShaderEffectItem::lookThroughShaderCode(), mouseMoveEvent(), QDeclarativeTextEdit::moveCursorSelection(), operator<<(), QDeclarativeTextInput::positionAt(), QDeclarativeGridViewPrivate::positionViewAtIndex(), QDeclarativeListViewPrivate::positionViewAtIndex(), QDeclarativePathView::refill(), QGraphicsItemGroup::removeFromGroup(), QGraphicsItemAnimation::reset(), QGraphicsWidget::resize(), QDeclarativeFlickable::resizeContent(), QDeclarativeTextEdit::setCursorPosition(), QGraphicsWidget::setGeometry(), QGraphicsItemAnimation::setItem(), QGraphicsItemPrivate::setPosHelper(), QDeclarativeGridView::trackedPositionChanged(), QDeclarativeListView::trackedPositionChanged(), QDeclarativePinchArea::updatePinch(), QDeclarativeGridView::viewportMoved(), QDeclarativeListView::viewportMoved(), and QGraphicsProxyWidget::wheelEvent().
 {
     return d_ptr->pos;
 }
prepareGeometryChange()
void QGraphicsItem::prepareGeometryChange () protected
Prepares the item for a geometry change.
Call this function before changing the bounding rect of an item to keep QGraphicsScene's index up to date.
prepareGeometryChange() will call update() if this is necessary.
Example:
void CircleItem::setRadius(qreal newRadius)
{
    if (radius != newRadius) {
        prepareGeometryChange();
        radius = newRadius;
    }
}
See also
boundingRect()
Definition at line 7979 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsItemGroup::removeFromGroup(), QDeclarativePaintedItem::setContentsSize(), QGraphicsWidget::setGeometry(), setGraphicsEffect(), QDeclarativeItem::setImplicitHeight(), QDeclarativeItem::setImplicitWidth(), QGraphicsTransformPrivate::setItem(), QGraphicsLineItem::setLine(), QGraphicsPixmapItem::setOffset(), QGraphicsPathItem::setPath(), QAbstractGraphicsShapeItem::setPen(), QGraphicsLineItem::setPen(), QGraphicsPixmapItem::setPixmap(), QGraphicsPolygonItem::setPolygon(), QGraphicsRectItem::setRect(), QGraphicsEllipseItem::setRect(), setRotation(), setScale(), QDeclarativeItem::setSize(), QGraphicsEllipseItem::setSpanAngle(), QGraphicsEllipseItem::setStartAngle(), QDeclarativeText::setStyle(), setTransformations(), setTransformOriginPoint(), QDeclarativeText::setVAlign(), QGraphicsWidget::setWindowFrameMargins(), QGraphicsTransformPrivate::updateItem(), and QDeclarativeTextEdit::updateSize().
 {
     if (d_ptr->inDestructor)
         return;
     if (d_ptr->scene) {
         d_ptr->scene->d_func()->dirtyGrowingItemsBoundingRect = true;
         d_ptr->geometryChanged = 1;
         d_ptr->paintedViewBoundingRectsNeedRepaint = 1;
         d_ptr->notifyBoundingRectChanged = !d_ptr->inSetPosHelper;
         QGraphicsScenePrivate *scenePrivate = d_ptr->scene->d_func();
         scenePrivate->index->prepareBoundingRectChange(this);
         scenePrivate->markDirty(this, QRectF(), /*invalidateChildren=*/true, /*force=*/false,
                                 /*ignoreOpacity=*/ false, /*removingItemFromScene=*/ false,
                                 /*updateBoundingRect=*/true);
         // For compatibility reasons, we have to update the item's old geometry
         // if someone is connected to the changed signal or the scene has no views.
         // Note that this has to be done *after* markDirty to ensure that
         // _q_processDirtyItems is called before _q_emitUpdated.
         if (scenePrivate->isSignalConnected(scenePrivate->changedSignalIndex)
             || scenePrivate->views.isEmpty()) {
             if (d_ptr->hasTranslateOnlySceneTransform()) {
                 d_ptr->scene->update(boundingRect().translated(d_ptr->sceneTransform.dx(),
                                                                d_ptr->sceneTransform.dy()));
             } else {
                 d_ptr->scene->update(d_ptr->sceneTransform.mapRect(boundingRect()));
             }
         }
     }
     d_ptr->markParentDirty(/*updateBoundingRect=*/true);
 }
removeFromIndex()
void QGraphicsItem::removeFromIndex () protected
Removes this item from the scene's index.
Warning
This function is not part of the public interface.
Called in conjunction with addToIndex() to ensure the index bookkeeping is correct when the item's position, transformation or shape changes.
Definition at line 7956 of file qgraphicsitem.cpp.
 {
     if (d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorClipsChildren) {
         // ### remove from child index only if applicable
         return;
     }
     if (d_ptr->scene)
         d_ptr->scene->d_func()->index->removeItem(this);
 }
removeSceneEventFilter()
void QGraphicsItem::removeSceneEventFilter (QGraphicsItem * filterItem)
Removes an event filter on this item from filterItem.
See also
installSceneEventFilter()
Definition at line 7057 of file qgraphicsitem.cpp.
 {
     if (!d_ptr->scene || d_ptr->scene != filterItem->scene())
         return;
     d_ptr->scene->d_func()->removeSceneEventFilter(this, filterItem);
 }
resetMatrix()
void QGraphicsItem::resetMatrix ()
Use resetTransform() instead.
Definition at line 4736 of file qgraphicsitem.cpp.
 {
     resetTransform();
 }
resetTransform()
void QGraphicsItem::resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
Since
4.3
This is equivalent to calling setTransform(QTransform()).
See also
setTransform(), transform()
Definition at line 4753 of file qgraphicsitem.cpp.
Referenced by resetMatrix().
 {
     setTransform(QTransform(), false);
 }
rotate()
void QGraphicsItem::rotate (qreal angle)
Use.
setRotation(rotation() + angle);
instead.
Rotates the current item transformation angle degrees clockwise around its origin. To translate around an arbitrary point (x, y), you need to combine translation and rotation with setTransform().
Example:
// Rotate an item 45 degrees around (0, 0).
item->rotate(45);
// Rotate an item 45 degrees around (x, y).
item->setTransform(QTransform().translate(x, y).rotate(45).translate(-x, -y));
See also
setTransform(), transform(), scale(), shear(), translate()
Definition at line 4782 of file qgraphicsitem.cpp.
 {
     setTransform(QTransform().rotate(angle), true);
 }
rotation()
qreal QGraphicsItem::rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
Since
4.6
The default value is 0 (i.e., the item is not rotated).
The rotation is combined with the item's scale(), transform() and transformations() to map the item's coordinate system to the parent item.
See also
setRotation(), transformOriginPoint(), {Transformations}
Definition at line 4091 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QDeclarativeParentChangePrivate::doChange(), and QGraphicsItemGroup::removeFromGroup().
 {
     if (!d_ptr->transformData)
         return 0;
     return d_ptr->transformData->rotation;
 }
scale() [1/2]
void QGraphicsItem::scale (qreal sx, qreal sy)
Use.
setTransform(QTransform::fromScale(sx, sy), true);
instead.
Scales the current item transformation by (sx, sy) around its origin. To scale from an arbitrary point (x, y), you need to combine translation and scaling with setTransform().
Example:
// Scale an item by 3x2 from its origin
item->scale(3, 2);
// Scale an item by 3x2 from (x, y)
item->setTransform(QTransform().translate(x, y).scale(3, 2).translate(-x, -y));
See also
setTransform(), transform()
Definition at line 4811 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QDeclarativeParentChangePrivate::doChange(), and QGraphicsItemGroup::removeFromGroup().
 {
     setTransform(QTransform::fromScale(sx, sy), true);
 }
scale() [2/2]
qreal QGraphicsItem::scale () const
Returns the scale factor of the item.
Since
4.6
The default scale factor is 1.0 (i.e., the item is not scaled).
The scale is combined with the item's rotation(), transform() and transformations() to map the item's coordinate system to the parent item.
See also
setScale(), rotation(), {Transformations}
Definition at line 4165 of file qgraphicsitem.cpp.
Referenced by QDeclarativeBorderImage::paint(), QDeclarativePaintedItem::setContentsScale(), and QDeclarativePinchArea::updatePinch().
 {
     if (!d_ptr->transformData)
         return 1.;
     return d_ptr->transformData->scale;
 }
scene()
QGraphicsScene * QGraphicsItem::scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
To add or move an item to a scene, call QGraphicsScene::addItem().
Definition at line 1583 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::addItem(), ShaderEffectItem::checkViewportUpdateMode(), QmlJSDebugger::LiveSelectionIndicator::clear(), QDeclarativeLoaderPrivate::clear(), QGraphicsItemPrivate::clearFocusHelper(), QDeclarativeTextEdit::closeSoftwareInputPanel(), QDeclarativeTextInput::closeSoftwareInputPanel(), QShortcutMap::correctGraphicsWidgetContext(), QDeclarativeFlickablePrivate::data_clear(), QGraphicsItemPrivate::discardUpdateRequest(), QGraphicsItemPrivate::effectiveBoundingRect(), QMotifStyle::event(), QMacStyle::event(), QGraphicsWidgetPrivate::fixFocusChainBeforeReparenting(), QDeclarativeTextEditPrivate::focusChanged(), QDeclarativeTextInputPrivate::focusChanged(), QGraphicsObject::grabGesture(), QDeclarativeItem::hasActiveFocus(), installSceneEventFilter(), mousePressEvent(), QDeclarativeMouseArea::mouseReleaseEvent(), QDeclarativeTextInput::mouseReleaseEvent(), QDeclarativePinchArea::mouseReleaseEvent(), QDeclarativeTextEdit::mouseReleaseEvent(), mouseReleaseEvent(), QDeclarativeTextEdit::openSoftwareInputPanel(), QDeclarativeTextInput::openSoftwareInputPanel(), QGraphicsItem(), QDeclarativeVisualItemModel::release(), QDeclarativeVisualDataModel::release(), QGraphicsScene::removeItem(), QGraphicsScenePrivate::removeItemHelper(), removeSceneEventFilter(), QWidgetPrivate::screenGeometry(), QGraphicsScene::sendEvent(), QDeclarativePathView::sendMouseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativeFlickable::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), QGraphicsItemPrivate::sendScenePosChange(), QGraphicsScenePrivate::setActivePanelHelper(), QGraphicsScene::setActiveWindow(), QGraphicsItemPrivate::setEnabledHelper(), QGraphicsItemPrivate::setFocusHelper(), QGraphicsScenePrivate::setFocusItemHelper(), QDeclarativeGridView::setFooter(), QDeclarativeListView::setFooter(), QDeclarativeGridView::setHeader(), QDeclarativeListView::setHeader(), setInputMethodHints(), QGraphicsItemPrivate::setPosHelper(), QGraphicsItemPrivate::setSubFocus(), QGraphicsWidget::setTabOrder(), QGraphicsItemPrivate::setVisibleHelper(), QGraphicsWidget::style(), QDeclarativeFlickable::timerEvent(), QGraphicsObject::ungrabGesture(), updateMicroFocus(), QGraphicsItemPrivate::updatePaintedViewBoundingRects(), QDeclarativePinchArea::updatePinch(), QmlJSDebugger::LiveSelectionRectangle::~LiveSelectionRectangle(), and QGraphicsWidget::~QGraphicsWidget().
 {
     return d_ptr->scene;
 }
sceneBoundingRect()
QRectF QGraphicsItem::sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
See also
boundingRect(), {The Graphics View Coordinate System}
Definition at line 5121 of file qgraphicsitem.cpp.
Referenced by QGraphicsView::centerOn(), QGraphicsScene::collidingItems(), QGraphicsView::ensureVisible(), ensureVisible(), and QGraphicsScene::itemsBoundingRect().
 {
     // Find translate-only offset
     // COMBINE
     QPointF offset;
     const QGraphicsItem *parentItem = this;
     const QGraphicsItemPrivate *itemd;
     do {
         itemd = parentItem->d_ptr.data();
         if (itemd->transformData)
             break;
         offset += itemd->pos;
     } while ((parentItem = itemd->parent));
     QRectF br = boundingRect();
     br.translate(offset);
     if (!parentItem)
         return br;
     if (parentItem->d_ptr->hasTranslateOnlySceneTransform()) {
         br.translate(parentItem->d_ptr->sceneTransform.dx(), parentItem->d_ptr->sceneTransform.dy());
         return br;
     }
     return parentItem->d_ptr->sceneTransform.mapRect(br);
 }
sceneEvent()
bool QGraphicsItem::sceneEvent (QEvent * event) protected virtual
This virtual function receives events to this item.
Reimplement this function to intercept events before they are dispatched to the specialized event handlers contextMenuEvent(), focusInEvent(), focusOutEvent(), hoverEnterEvent(), hoverMoveEvent(), hoverLeaveEvent(), keyPressEvent(), keyReleaseEvent(), mousePressEvent(), mouseReleaseEvent(), mouseMoveEvent(), and mouseDoubleClickEvent().
Returns true if the event was recognized and handled; otherwise, (e.g., if the event type was not recognized,) false is returned.
event is the intercepted event.
Reimplemented in QGraphicsTextItem, QDeclarativePinchArea, QDeclarativeTextInput, QDeclarativeFlickable, QGraphicsWidget, QDeclarativeMouseArea, QDeclarativeItem, QDeclarativeGestureArea, and QDeclarativeFocusPanel.
Definition at line 7101 of file qgraphicsitem.cpp.
Referenced by QDeclarativeItem::sceneEvent(), QGraphicsWidget::sceneEvent(), sceneEvent(), QGraphicsTextItem::sceneEvent(), and QGraphicsScenePrivate::sendEvent().
 {
     if (d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorHandlesChildEvents) {
         if (event->type() == QEvent::HoverEnter || event->type() == QEvent::HoverLeave
             || event->type() == QEvent::DragEnter || event->type() == QEvent::DragLeave) {
             // Hover enter and hover leave events for children are ignored;
             // hover move events are forwarded.
             return true;
         }
         QGraphicsItem *handler = this;
         do {
             handler = handler->d_ptr->parent;
             Q_ASSERT(handler);
         } while (handler->d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorHandlesChildEvents);
         // Forward the event to the closest parent that handles child
         // events, mapping existing item-local coordinates to its
         // coordinate system.
         d_ptr->remapItemPos(event, handler);
         handler->sceneEvent(event);
         return true;
     }
     if (event->type() == QEvent::FocusOut) {
         focusOutEvent(static_cast<QFocusEvent *>(event));
         return true;
     }
     if (!d_ptr->visible) {
         // Eaten
         return true;
     }
     switch (event->type()) {
     case QEvent::FocusIn:
         focusInEvent(static_cast<QFocusEvent *>(event));
         break;
     case QEvent::GraphicsSceneContextMenu:
         contextMenuEvent(static_cast<QGraphicsSceneContextMenuEvent *>(event));
         break;
     case QEvent::GraphicsSceneDragEnter:
         dragEnterEvent(static_cast<QGraphicsSceneDragDropEvent *>(event));
         break;
     case QEvent::GraphicsSceneDragMove:
         dragMoveEvent(static_cast<QGraphicsSceneDragDropEvent *>(event));
         break;
     case QEvent::GraphicsSceneDragLeave:
         dragLeaveEvent(static_cast<QGraphicsSceneDragDropEvent *>(event));
         break;
     case QEvent::GraphicsSceneDrop:
         dropEvent(static_cast<QGraphicsSceneDragDropEvent *>(event));
         break;
     case QEvent::GraphicsSceneHoverEnter:
         hoverEnterEvent(static_cast<QGraphicsSceneHoverEvent *>(event));
         break;
     case QEvent::GraphicsSceneHoverMove:
         hoverMoveEvent(static_cast<QGraphicsSceneHoverEvent *>(event));
         break;
     case QEvent::GraphicsSceneHoverLeave:
         hoverLeaveEvent(static_cast<QGraphicsSceneHoverEvent *>(event));
         break;
     case QEvent::GraphicsSceneMouseMove:
         mouseMoveEvent(static_cast<QGraphicsSceneMouseEvent *>(event));
         break;
     case QEvent::GraphicsSceneMousePress:
         mousePressEvent(static_cast<QGraphicsSceneMouseEvent *>(event));
         break;
     case QEvent::GraphicsSceneMouseRelease:
         mouseReleaseEvent(static_cast<QGraphicsSceneMouseEvent *>(event));
         break;
     case QEvent::GraphicsSceneMouseDoubleClick:
         mouseDoubleClickEvent(static_cast<QGraphicsSceneMouseEvent *>(event));
         break;
     case QEvent::GraphicsSceneWheel:
         wheelEvent(static_cast<QGraphicsSceneWheelEvent *>(event));
         break;
     case QEvent::KeyPress: {
         QKeyEvent *k = static_cast<QKeyEvent *>(event);
         if (k->key() == Qt::Key_Tab || k->key() == Qt::Key_Backtab) {
             if (!(k->modifiers() & (Qt::ControlModifier | Qt::AltModifier))) {  //### Add MetaModifier?
                 bool res = false;
                 if (k->key() == Qt::Key_Backtab
                     || (k->key() == Qt::Key_Tab && (k->modifiers() & Qt::ShiftModifier))) {
                     if (d_ptr->isWidget) {
                         res = static_cast<QGraphicsWidget *>(this)->focusNextPrevChild(false);
                     } else if (d_ptr->scene) {
                         res = d_ptr->scene->focusNextPrevChild(false);
                     }
                 } else if (k->key() == Qt::Key_Tab) {
                     if (d_ptr->isWidget) {
                         res = static_cast<QGraphicsWidget *>(this)->focusNextPrevChild(true);
                     } else if (d_ptr->scene) {
                         res = d_ptr->scene->focusNextPrevChild(true);
                     }
                 }
                 if (!res)
                     event->ignore();
                 return true;
             }
         }
         keyPressEvent(static_cast<QKeyEvent *>(event));
         break;
     }
     case QEvent::KeyRelease:
         keyReleaseEvent(static_cast<QKeyEvent *>(event));
         break;
     case QEvent::InputMethod:
         inputMethodEvent(static_cast<QInputMethodEvent *>(event));
         break;
     case QEvent::WindowActivate:
     case QEvent::WindowDeactivate:
         // Propagate panel activation.
         if (d_ptr->scene) {
             for (int i = 0; i < d_ptr->children.size(); ++i) {
                 QGraphicsItem *child = d_ptr->children.at(i);
                 if (child->isVisible() && !child->isPanel()) {
                     if (!(child->d_ptr->ancestorFlags & QGraphicsItemPrivate::AncestorHandlesChildEvents))
                         d_ptr->scene->sendEvent(child, event);
                 }
             }
         }
         break;
     default:
         return false;
     }
     return true;
 }
sceneEventFilter()
bool QGraphicsItem::sceneEventFilter (QGraphicsItem * watched, QEvent * event) protected virtual
Filters events for the item watched.
event is the filtered event.
Reimplementing this function in a subclass makes it possible for the item to be used as an event filter for other items, intercepting all the events send to those items before they are able to respond.
Reimplementations must return true to prevent further processing of a given event, ensuring that it will not be delivered to the watched item, or return false to indicate that the event should be propagated further by the event system.
See also
installSceneEventFilter()
Reimplemented in QDeclarativePinchArea, QDeclarativeMouseArea, QDeclarativeFlickable, and QDeclarativePathView.
Definition at line 7080 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::filterDescendantEvent(), QDeclarativePathView::sceneEventFilter(), QDeclarativeFlickable::sceneEventFilter(), QDeclarativeMouseArea::sceneEventFilter(), and QDeclarativePinchArea::sceneEventFilter().
 {
     Q_UNUSED(watched);
     Q_UNUSED(event);
     return false;
 }
sceneMatrix()
QMatrix QGraphicsItem::sceneMatrix () const
Use sceneTransform() instead.
See also
transform(), setTransform(), scenePos(), {The Graphics View Coordinate System}
Definition at line 4404 of file qgraphicsitem.cpp.
 {
     d_ptr->ensureSceneTransform();
     return d_ptr->sceneTransform.toAffine();
 }
scenePos()
QPointF QGraphicsItem::scenePos () const
Returns the item's position in scene coordinates.
This is equivalent to calling mapToScene(0, 0).
See also
pos(), sceneTransform(), {The Graphics View Coordinate System}
Definition at line 3890 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemPrivate::sendScenePosChange().
 {
     return mapToScene(0, 0);
 }
sceneTransform()
QTransform QGraphicsItem::sceneTransform () const
Returns this item's scene transformation matrix.
Since
4.3
This matrix can be used to map coordinates and geometrical shapes from this item's local coordinate system to the scene's coordinate system. To map coordinates from the scene, you must first invert the returned matrix.
Example:
QGraphicsRectItem rect;
rect.setPos(100, 100);
rect.sceneTransform().map(QPointF(0, 0));
// returns QPointF(100, 100);
rect.sceneTransform().inverted().map(QPointF(100, 100));
// returns QPointF(0, 0);
Unlike transform(), which returns only an item's local transformation, this function includes the item's (and any parents') position, and all the transfomation properties.
See also
transform(), setTransform(), scenePos(), {The Graphics View Coordinate System}, {Transformations}
Definition at line 4431 of file qgraphicsitem.cpp.
Referenced by deviceTransform(), ensureVisible(), QGraphicsViewPrivate::mapToViewRect(), mouseMoveEvent(), QGraphicsView::paintEvent(), QGraphicsItemEffectSourcePrivate::pixmap(), QGraphicsItemGroup::removeFromGroup(), QGraphicsItemPrivate::sceneEffectiveBoundingRect(), and QDeclarativeFlipablePrivate::updateSceneTransformFromParent().
 {
     d_ptr->ensureSceneTransform();
     return d_ptr->sceneTransform;
 }
scroll()
void QGraphicsItem::scroll (qreal dx, qreal dy, const QRectF & rect = QRectF())
Scrolls the contents of rect by dx, dy.
Since
4.4 If rect is a null rect (the default), the item's bounding rect is scrolled.
Scrolling provides a fast alternative to simply redrawing when the contents of the item (or parts of the item) are shifted vertically or horizontally. Depending on the current transformation and the capabilities of the paint device (i.e., the viewport), this operation may consist of simply moving pixels from one location to another using memmove(). In most cases this is faster than rerendering the entire area.
After scrolling, the item will issue an update for the newly exposed areas. If scrolling is not supported (e.g., you are rendering to an OpenGL viewport, which does not benefit from scroll optimizations), this function is equivalent to calling update(rect).
Note: Scrolling is only supported when QGraphicsItem::ItemCoordinateCache is enabled; in all other cases calling this function is equivalent to calling update(rect). If you for sure know that the item is opaque and not overlapped by other items, you can map the rect to viewport coordinates and scroll the viewport.
QTransform xform = item->deviceTransform(view->viewportTransform());
QRect deviceRect = xform.mapRect(rect).toAlignedRect();
view->viewport()->scroll(dx, dy, deviceRect);
See also
boundingRect()
Definition at line 6114 of file qgraphicsitem.cpp.
 {
     Q_D(QGraphicsItem);
     if (dx == 0.0 && dy == 0.0)
         return;
     if (!d->scene)
         return;
     // Accelerated scrolling means moving pixels from one location to another
     // and only redraw the newly exposed area. The following requirements must
     // be fulfilled in order to do that:
     //
     // 1) Item is opaque.
     // 2) Item is not overlapped by other items.
     //
     // There's (yet) no way to detect whether an item is opaque or not, which means
     // we cannot do accelerated scrolling unless the cache is enabled. In case of using
     // DeviceCoordinate cache we also have to take the device transform into account in
     // order to determine whether we can do accelerated scrolling or not. That's left out
     // for simplicity here, but it is definitely something we can consider in the future
     // as a performance improvement.
     if (d->cacheMode != QGraphicsItem::ItemCoordinateCache
         || !qFuzzyIsNull(dx - int(dx)) || !qFuzzyIsNull(dy - int(dy))) {
         update(rect);
         return;
     }
     QGraphicsItemCache *cache = d->extraItemCache();
     if (cache->allExposed || cache->fixedSize.isValid()) {
         // Cache is either invalidated or item is scaled (see QGraphicsItem::setCacheMode).
         update(rect);
         return;
     }
     // Find pixmap in cache.
     QPixmap cachedPixmap;
     if (!QPixmapCache::find(cache->key, &cachedPixmap)) {
         update(rect);
         return;
     }
     QRect scrollRect = (rect.isNull() ? boundingRect() : rect).toAlignedRect();
     if (!scrollRect.intersects(cache->boundingRect))
         return; // Nothing to scroll.
     // Remove from cache to avoid deep copy when modifying.
     QPixmapCache::remove(cache->key);
     QRegion exposed;
     cachedPixmap.scroll(dx, dy, scrollRect.translated(-cache->boundingRect.topLeft()), &exposed);
     // Reinsert into cache.
     cache->key = QPixmapCache::insert(cachedPixmap);
     // Translate the existing expose.
     for (int i = 0; i < cache->exposed.size(); ++i) {
         QRectF &e = cache->exposed[i];
         if (!rect.isNull() && !e.intersects(rect))
             continue;
         e.translate(dx, dy);
     }
     // Append newly exposed areas. Note that the exposed region is currently
     // in pixmap coordinates, so we have to translate it to item coordinates.
     exposed.translate(cache->boundingRect.topLeft());
     const QVector<QRect> exposedRects = exposed.rects();
     for (int i = 0; i < exposedRects.size(); ++i)
         cache->exposed += exposedRects.at(i);
     // Trigger update. This will redraw the newly exposed area and make sure
     // the pixmap is re-blitted in case there are overlapping items.
     d->scene->d_func()->markDirty(this, rect);
 }
setAcceptDrops()
void QGraphicsItem::setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
By default, items do not accept drag and drop events.
See also
acceptDrops()
Definition at line 3076 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::QGraphicsTextItem().
 {
     d_ptr->acceptDrops = on;
 }
setAcceptedMouseButtons()
void QGraphicsItem::setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
By default, all mouse buttons are accepted. If an item accepts a mouse button, it will become the mouse grabber item when a mouse press event is delivered for that button. However, if the item does not accept the mouse button, QGraphicsScene will forward the mouse events to the first item beneath it that does.
To disable mouse events for an item (i.e., make it transparent for mouse events), call setAcceptedMouseButtons(0).
See also
acceptedMouseButtons(), mousePressEvent()
Definition at line 3112 of file qgraphicsitem.cpp.
Referenced by QDeclarativeGestureArea::QDeclarativeGestureArea(), and QDeclarativeMouseArea::setAcceptedButtons().
 {
     if (Qt::MouseButtons(d_ptr->acceptedMouseButtons) != buttons) {
         if (buttons == 0 && d_ptr->scene && d_ptr->scene->mouseGrabberItem() == this
             && d_ptr->scene->d_func()->lastMouseGrabberItemHasImplicitMouseGrab) {
             ungrabMouse();
         }
         d_ptr->acceptedMouseButtons = quint32(buttons);
     }
 }
setAcceptHoverEvents()
void QGraphicsItem::setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
Since
4.4
By default, items do not accept hover events.
Hover events are delivered when there is no current mouse grabber item. They are sent when the mouse cursor enters an item, when it moves around inside the item, and when the cursor leaves an item. Hover events are commonly used to highlight an item when it's entered, and for tracking the mouse cursor as it hovers over the item (equivalent to QWidget::mouseTracking).
Parent items receive hover enter events before their children, and leave events after their children. The parent does not receive a hover leave event if the cursor enters a child, though; the parent stays "hovered" until the cursor leaves its area, including its children's areas.
If a parent item handles child events, it will receive hover move, drag move, and drop events as the cursor passes through its children, but it does not receive hover enter and hover leave, nor drag enter and drag leave events on behalf of its children.
A QGraphicsWidget with window decorations will accept hover events regardless of the value of acceptHoverEvents().
See also
acceptHoverEvents(), hoverEnterEvent(), hoverMoveEvent(), hoverLeaveEvent()
Definition at line 3187 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::QGraphicsTextItem(), setAcceptsHoverEvents(), and QDeclarativeMouseArea::setHoverEnabled().
 {
     if (d_ptr->acceptsHover == quint32(enabled))
         return;
     d_ptr->acceptsHover = quint32(enabled);
     if (d_ptr->acceptsHover && d_ptr->scene && d_ptr->scene->d_func()->allItemsIgnoreHoverEvents) {
         d_ptr->scene->d_func()->allItemsIgnoreHoverEvents = false;
         d_ptr->scene->d_func()->enableMouseTrackingOnViews();
     }
 }
setAcceptsHoverEvents()
void QGraphicsItem::setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
Definition at line 3206 of file qgraphicsitem.cpp.
 {
     setAcceptHoverEvents(enabled);
 }
setAcceptTouchEvents()
void QGraphicsItem::setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
Since
4.6
By default, items do not accept touch events.
Definition at line 3236 of file qgraphicsitem.cpp.
Referenced by QDeclarativeGestureArea::QDeclarativeGestureArea().
 {
     if (d_ptr->acceptTouchEvents == quint32(enabled))
         return;
     d_ptr->acceptTouchEvents = quint32(enabled);
     if (d_ptr->acceptTouchEvents && d_ptr->scene && d_ptr->scene->d_func()->allItemsIgnoreTouchEvents) {
         d_ptr->scene->d_func()->allItemsIgnoreTouchEvents = false;
         d_ptr->scene->d_func()->enableTouchEventsOnViews();
     }
 }
setActive()
void QGraphicsItem::setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
Since
4.6
Otherwise, the panel is deactivated.
If the item is not part of an active scene, active will decide what happens to the panel when the scene becomes active or the item is added to the scene. If true, the item's panel will be activated when the item is either added to the scene or the scene is activated. Otherwise, the item will stay inactive independent of the scene's activated state.
See also
isPanel(), QGraphicsScene::setActivePanel(), QGraphicsScene::isActive()
Definition at line 3387 of file qgraphicsitem.cpp.
 {
     d_ptr->explicitActivate = 1;
     d_ptr->wantsActive = active;
     if (d_ptr->scene) {
         if (active) {
             // Activate this item.
             d_ptr->scene->setActivePanel(this);
         } else {
             // Deactivate this item, and reactivate the last active item
             // (if any).
             QGraphicsItem *lastActive = d_ptr->scene->d_func()->lastActivePanel;
             d_ptr->scene->setActivePanel(lastActive != this ? lastActive : 0);
         }
     }
 }
setBoundingRegionGranularity()
void QGraphicsItem::setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
Since
4.4 The default value is 0 (i.e., the lowest granularity, where the bounding region corresponds to the item's bounding rectangle).
The granularity is used by boundingRegion() to calculate how fine the bounding region of the item should be. The highest achievable granularity is 1, where boundingRegion() will return the finest outline possible for the respective device (e.g., for a QGraphicsView viewport, this gives you a pixel-perfect bounding region). The lowest possible granularity is 0. The value of granularity describes the ratio between device resolution and the resolution of the bounding region (e.g., a value of 0.25 will provide a region where each chunk corresponds to 4x4 device units / pixels).
See also
boundingRegionGranularity()
Definition at line 5640 of file qgraphicsitem.cpp.
 {
     if (granularity < 0.0 || granularity > 1.0) {
         qWarning("QGraphicsItem::setBoundingRegionGranularity: invalid granularity %g", granularity);
         return;
     }
     if (granularity == 0.0) {
         d_ptr->unsetExtra(QGraphicsItemPrivate::ExtraBoundingRegionGranularity);
         d_ptr->hasBoundingRegionGranularity = 0;
         return;
     }
     d_ptr->hasBoundingRegionGranularity = 1;
     d_ptr->setExtra(QGraphicsItemPrivate::ExtraBoundingRegionGranularity,
                     QVariant::fromValue<qreal>(granularity));
 }
setCacheMode()
void QGraphicsItem::setCacheMode (CacheMode mode, const QSize & logicalCacheSize = QSize())
Sets the item's cache mode to mode.
Since
4.4
The optional logicalCacheSize argument is used only by ItemCoordinateCache mode, and describes the resolution of the cache buffer; if logicalCacheSize is (100, 100), QGraphicsItem will fit the item into 100x100 pixels in graphics memory, regardless of the logical size of the item itself. By default QGraphicsItem uses the size of boundingRect(). For all other cache modes than ItemCoordinateCache, logicalCacheSize is ignored.
Caching can speed up rendering if your item spends a significant time redrawing itself. In some cases the cache can also slow down rendering, in particular when the item spends less time redrawing than QGraphicsItem spends redrawing from the cache. When enabled, the item's paint() function will be called only once for each call to update(); for any subsequent repaint requests, the Graphics View framework will redraw from the cache. This approach works particularly well with QGLWidget, which stores all the cache as OpenGL textures.
Be aware that QPixmapCache's cache limit may need to be changed to obtain optimal performance.
You can read more about the different cache modes in the CacheMode documentation.
See also
CacheMode, QPixmapCache::setCacheLimit()
Definition at line 2098 of file qgraphicsitem.cpp.
Referenced by QGraphicsSvgItem::setCachingEnabled().
 {
     CacheMode lastMode = CacheMode(d_ptr->cacheMode);
     d_ptr->cacheMode = mode;
     bool noVisualChange = (mode == NoCache && lastMode == NoCache)
                           || (mode == NoCache && lastMode == DeviceCoordinateCache)
                           || (mode == DeviceCoordinateCache && lastMode == NoCache)
                           || (mode == DeviceCoordinateCache && lastMode == DeviceCoordinateCache);
     if (mode == NoCache) {
         d_ptr->removeExtraItemCache();
     } else {
         QGraphicsItemCache *cache = d_ptr->extraItemCache();
         // Reset old cache
         cache->purge();
         if (mode == ItemCoordinateCache) {
             if (lastMode == mode && cache->fixedSize == logicalCacheSize)
                 noVisualChange = true;
             cache->fixedSize = logicalCacheSize;
         }
     }
     if (!noVisualChange)
         update();
 }
setCursor()
void QGraphicsItem::setCursor (const QCursor & cursor)
Sets the current cursor shape for the item to cursor.
The mouse cursor will assume this shape when it's over this item. See the list of predefined cursor objects for a range of useful shapes.
An editor item might want to use an I-beam cursor:
item->setCursor(Qt::IBeamCursor);
If no cursor has been set, the cursor of the item beneath is used.
See also
cursor(), hasCursor(), unsetCursor(), QWidget::cursor, QApplication::overrideCursor()
Definition at line 2276 of file qgraphicsitem.cpp.
Referenced by QApplicationPrivate::dispatchEnterLeave().
 {
     const QVariant cursorVariant(itemChange(ItemCursorChange, QVariant::fromValue<QCursor>(cursor)));
     d_ptr->setExtra(QGraphicsItemPrivate::ExtraCursor, qvariant_cast<QCursor>(cursorVariant));
     d_ptr->hasCursor = 1;
     if (d_ptr->scene) {
         d_ptr->scene->d_func()->allItemsUseDefaultCursor = false;
         foreach (QGraphicsView *view, d_ptr->scene->views()) {
             view->viewport()->setMouseTracking(true);
             // Note: Some of this logic is duplicated in QGraphicsView's mouse events.
             if (view->underMouse()) {
                 foreach (QGraphicsItem *itemUnderCursor, view->items(view->mapFromGlobal(QCursor::pos()))) {
                     if (itemUnderCursor->hasCursor()) {
                         QMetaObject::invokeMethod(view, "_q_setViewportCursor",
                                                   Q_ARG(QCursor, itemUnderCursor->cursor()));
                         break;
                     }
                 }
                 break;
             }
         }
     }
     itemChange(ItemCursorHasChanged, cursorVariant);
 }
setData()
void QGraphicsItem::setData (int key, const QVariant & value)
Sets this item's custom data for the key key to value.
Custom item data is useful for storing arbitrary properties for any item. Qt does not use this feature for storing data; it is provided solely for the convenience of the user.
See also
data()
Definition at line 6976 of file qgraphicsitem.cpp.
Referenced by QmlJSDebugger::LiveSelectionIndicator::setItems(), and QmlJSDebugger::SubcomponentMaskLayerItem::SubcomponentMaskLayerItem().
 {
     qt_dataStore()->data[this][key] = value;
 }
setEnabled()
void QGraphicsItem::setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
Disabled items are visible, but they do not receive any events, and cannot take focus nor be selected. Mouse events are discarded; they are not propagated unless the item is also invisible, or if it does not accept mouse events (see acceptedMouseButtons()). A disabled item cannot become the mouse grabber, and as a result of this, an item loses the grab if it becomes disabled when grabbing the mouse, just like it loses focus if it had focus when it was disabled.
Disabled items are traditionally drawn using grayed-out colors (see QPalette::Disabled).
If you disable a parent item, all its children will also be disabled. If you enable a parent item, all children will be enabled, unless they have been explicitly disabled (i.e., if you call setEnabled(false) on a child, it will not be reenabled if its parent is disabled, and then enabled again).
Items are enabled by default.
Note
If you install an event filter, you can still intercept events before they are delivered to items; this mechanism disregards the item's enabled state.
See also
isEnabled()
Definition at line 2700 of file qgraphicsitem.cpp.
Referenced by QGraphicsProxyWidget::eventFilter().
 {
     d_ptr->setEnabledHelper(enabled, /* explicitly = */ true);
 }
setExtension()
void QGraphicsItem::setExtension (Extension extension, const QVariant & variant) protected virtual
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Warning
This function is not part of the public interface.
Reimplemented in QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, and QGraphicsPathItem.
Definition at line 7905 of file qgraphicsitem.cpp.
 {
     Q_UNUSED(extension);
     Q_UNUSED(variant);
 }
setFiltersChildEvents()
void QGraphicsItem::setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
Since
4.6
e., all events intented for any of its children are instead sent to this item); otherwise, if enabled is false, this item will only handle its own events. The default value is false.
See also
filtersChildEvents()
Definition at line 3280 of file qgraphicsitem.cpp.
 {
     if (d_ptr->filtersDescendantEvents == enabled)
         return;
     d_ptr->filtersDescendantEvents = enabled;
     d_ptr->updateAncestorFlag(QGraphicsItem::GraphicsItemFlag(-2));
 }
setFlag()
void QGraphicsItem::setFlag (GraphicsItemFlag flag, bool enabled = true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
See also
flags(), setFlags()
Definition at line 1901 of file qgraphicsitem.cpp.
Referenced by _q_qgraphicsItemSetFlag(), QmlJSDebugger::BoundingBox::BoundingBox(), QmlJSDebugger::LiveLayerItem::LiveLayerItem(), QGraphicsTextItem::QGraphicsTextItem(), QDeclarativeItem::setClip(), QGraphicsWidget::setFocusPolicy(), QmlJSDebugger::LiveSelectionIndicator::setItems(), QDeclarativeTextInput::setReadOnly(), QDeclarativeTextEdit::setReadOnly(), QGraphicsWidget::setWindowFlags(), setZValue(), and ShaderEffectItem::ShaderEffectItem().
 {
     if (enabled)
         setFlags(GraphicsItemFlags(d_ptr->flags) | flag);
     else
         setFlags(GraphicsItemFlags(d_ptr->flags) & ~flag);
 }
setFlags()
void QGraphicsItem::setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
All flags in flags are enabled; all flags not in flags are disabled.
If the item had focus and flags does not enable ItemIsFocusable, the item loses focus as a result of calling this function. Similarly, if the item was selected, and flags does not enabled ItemIsSelectable, the item is automatically unselected.
By default, no flags are enabled. (QGraphicsWidget enables the ItemSendsGeometryChanges flag by default in order to track position changes.)
See also
flags(), setFlag()
Definition at line 1945 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::QGraphicsTextItem(), setFlag(), and QGraphicsTextItem::setTextInteractionFlags().
 {
     // Notify change and check for adjustment.
     if (quint32(d_ptr->flags) == quint32(flags))
         return;
     flags = GraphicsItemFlags(itemChange(ItemFlagsChange, quint32(flags)).toUInt());
     if (quint32(d_ptr->flags) == quint32(flags))
         return;
     if (d_ptr->scene && d_ptr->scene->d_func()->indexMethod != QGraphicsScene::NoIndex)
         d_ptr->scene->d_func()->index->itemChange(this, ItemFlagsChange, &flags);
     // Flags that alter the geometry of the item (or its children).
     const quint32 geomChangeFlagsMask = (ItemClipsChildrenToShape | ItemClipsToShape | ItemIgnoresTransformations | ItemIsSelectable);
     bool fullUpdate = (quint32(flags) & geomChangeFlagsMask) != (d_ptr->flags & geomChangeFlagsMask);
     if (fullUpdate)
         d_ptr->updatePaintedViewBoundingRects(/*children=*/true);
     // Keep the old flags to compare the diff.
     GraphicsItemFlags oldFlags = GraphicsItemFlags(d_ptr->flags);
     // Update flags.
     d_ptr->flags = flags;
     if (!(d_ptr->flags & ItemIsFocusable) && hasFocus()) {
         // Clear focus on the item if it has focus when the focusable flag
         // is unset.
         clearFocus();
     }
     if (!(d_ptr->flags & ItemIsSelectable) && isSelected()) {
         // Unselect the item if it is selected when the selectable flag is
         // unset.
         setSelected(false);
     }
     if ((flags & ItemClipsChildrenToShape) != (oldFlags & ItemClipsChildrenToShape)) {
         // Item children clipping changes. Propagate the ancestor flag to
         // all children.
         d_ptr->updateAncestorFlag(ItemClipsChildrenToShape);
         // The childrenBoundingRect is clipped to the boundingRect in case of ItemClipsChildrenToShape,
         // which means we have to invalidate the cached childrenBoundingRect whenever this flag changes.
         d_ptr->dirtyChildrenBoundingRect = 1;
         d_ptr->markParentDirty(true);
     }
     if ((flags & ItemIgnoresTransformations) != (oldFlags & ItemIgnoresTransformations)) {
         // Item children clipping changes. Propagate the ancestor flag to
         // all children.
         d_ptr->updateAncestorFlag(ItemIgnoresTransformations);
     }
     if ((flags & ItemNegativeZStacksBehindParent) != (oldFlags & ItemNegativeZStacksBehindParent)) {
         // NB! We change the flags directly here, so we must also update d_ptr->flags.
         // Note that this has do be done before the ItemStacksBehindParent check
         // below; otherwise we will loose the change.
         // Update stack-behind.
         if (d_ptr->z < qreal(0.0))
             flags |= ItemStacksBehindParent;
         else
             flags &= ~ItemStacksBehindParent;
         d_ptr->flags = flags;
     }
     if ((flags & ItemStacksBehindParent) != (oldFlags & ItemStacksBehindParent)) {
         // NB! This check has to come after the ItemNegativeZStacksBehindParent
         // check above. Be careful.
         // Ensure child item sorting is up to date when toggling this flag.
         if (d_ptr->parent)
             d_ptr->parent->d_ptr->needSortChildren = 1;
         else if (d_ptr->scene)
             d_ptr->scene->d_func()->needSortTopLevelItems = 1;
     }
     if ((flags & ItemAcceptsInputMethod) != (oldFlags & ItemAcceptsInputMethod)) {
         // Update input method sensitivity in any views.
         if (d_ptr->scene)
             d_ptr->scene->d_func()->updateInputMethodSensitivityInViews();
     }
     if ((d_ptr->panelModality != NonModal)
         && d_ptr->scene
         && (flags & ItemIsPanel) != (oldFlags & ItemIsPanel)) {
         // update the panel's modal state
         if (flags & ItemIsPanel)
             d_ptr->scene->d_func()->enterModal(this);
         else
             d_ptr->scene->d_func()->leaveModal(this);
     }
     if (d_ptr->scene) {
         if ((flags & ItemSendsScenePositionChanges) != (oldFlags & ItemSendsScenePositionChanges)) {
             if (flags & ItemSendsScenePositionChanges)
                 d_ptr->scene->d_func()->registerScenePosItem(this);
             else
                 d_ptr->scene->d_func()->unregisterScenePosItem(this);
         }
         d_ptr->scene->d_func()->markDirty(this, QRectF(), /*invalidateChildren=*/true);
     }
     // Notify change.
     itemChange(ItemFlagsHaveChanged, quint32(flags));
 }
setFocus()
void QGraphicsItem::setFocus (Qt::FocusReason focusReason = Qt::OtherFocusReason)
Gives keyboard input focus to this item.
The focusReason argument will be passed into any focus event generated by this function; it is used to give an explanation of what caused the item to get focus.
Only enabled items that set the ItemIsFocusable flag can accept keyboard focus.
If this item is not visible, not active, or not associated with a scene, it will not gain immediate input focus. However, it will be registered as the preferred focus item for its subtree of items, should it later become visible.
As a result of calling this function, this item will receive a focus in event with focusReason. If another item already has focus, that item will first receive a focus out event indicating that it has lost input focus.
See also
clearFocus(), hasFocus(), focusItem(), focusProxy()
Definition at line 3442 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::addItem(), QGraphicsWidget::focusNextPrevChild(), QDeclarativeItem::forceActiveFocus(), QGraphicsScenePrivate::setActivePanelHelper(), QDeclarativeItem::setFocus(), QGraphicsScene::setFocusItem(), and QGraphicsScenePrivate::setFocusItemHelper().
 {
     d_ptr->setFocusHelper(focusReason, /* climb = */ true, /* focusFromHide = */ false);
 }
setFocusProxy()
void QGraphicsItem::setFocusProxy (QGraphicsItem * item)
Sets the item's focus proxy to item.
Since
4.6
If an item has a focus proxy, the focus proxy will receive input focus when the item gains input focus. The item itself will still have focus (i.e., hasFocus() will return true), but only the focus proxy will receive the keyboard input.
A focus proxy can itself have a focus proxy, and so on. In such case, keyboard input will be handled by the outermost focus proxy.
The focus proxy item must belong to the same scene as this item.
See also
focusProxy(), setFocus(), hasFocus()
Definition at line 3605 of file qgraphicsitem.cpp.
 {
     if (item == d_ptr->focusProxy)
         return;
     if (item == this) {
         qWarning("QGraphicsItem::setFocusProxy: cannot assign self as focus proxy");
         return;
     }
     if (item) {
         if (item->d_ptr->scene != d_ptr->scene) {
             qWarning("QGraphicsItem::setFocusProxy: focus proxy must be in same scene");
             return;
         }
         for (QGraphicsItem *f = item->focusProxy(); f != 0; f = f->focusProxy()) {
             if (f == this) {
                 qWarning("QGraphicsItem::setFocusProxy: %p is already in the focus proxy chain", item);
                 return;
             }
         }
     }
     QGraphicsItem *lastFocusProxy = d_ptr->focusProxy;
     if (lastFocusProxy)
         lastFocusProxy->d_ptr->focusProxyRefs.removeOne(&d_ptr->focusProxy);
     d_ptr->focusProxy = item;
     if (item)
         item->d_ptr->focusProxyRefs << &d_ptr->focusProxy;
 }
setGraphicsEffect()
void QGraphicsItem::setGraphicsEffect (QGraphicsEffect * effect)
Sets effect as the item's effect.
If there already is an effect installed on this item, QGraphicsItem will delete the existing effect before installing the new effect.
If effect is the installed on a different item, setGraphicsEffect() will remove the effect from the item and install it on this item.
QGraphicsItem takes ownership of effect.
Note
This function will apply the effect on itself and all its children.
Since
4.6
Definition at line 2911 of file qgraphicsitem.cpp.
Referenced by ShaderEffectSource::attachSourceItem().
 {
     if (d_ptr->graphicsEffect == effect)
         return;
     if (d_ptr->graphicsEffect) {
         delete d_ptr->graphicsEffect;
         d_ptr->graphicsEffect = 0;
     } else if (d_ptr->parent) {
         d_ptr->parent->d_ptr->updateChildWithGraphicsEffectFlagRecursively();
     }
     if (effect) {
         // Set new effect.
         QGraphicsEffectSourcePrivate *sourced = new QGraphicsItemEffectSourcePrivate(this);
         QGraphicsEffectSource *source = new QGraphicsEffectSource(*sourced);
         d_ptr->graphicsEffect = effect;
         effect->d_func()->setGraphicsEffectSource(source);
         prepareGeometryChange();
     }
 }
setGroup()
void QGraphicsItem::setGroup (QGraphicsItemGroup * group)
Adds this item to the item group group.
If group is 0, this item is removed from any current group and added as a child of the previous group's parent.
See also
group(), QGraphicsScene::createItemGroup()
Definition at line 1615 of file qgraphicsitem.cpp.
 {
     if (!group) {
         if (QGraphicsItemGroup *group = this->group())
             group->removeFromGroup(this);
     } else {
         group->addToGroup(this);
     }
 }
setHandlesChildEvents()
void QGraphicsItem::setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
e., all events intented for any of its children are instead sent to this item); otherwise, if enabled is false, this item will only handle its own events. The default value is false.
This property is useful for item groups; it allows one item to handle events on behalf of its children, as opposed to its children handling their events individually.
If a child item accepts hover events, its parent will receive hover move events as the cursor passes through the child, but it does not receive hover enter and hover leave events on behalf of its child.
See also
handlesChildEvents()
Definition at line 3337 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::QGraphicsItemGroup().
 {
     if (d_ptr->handlesChildEvents == enabled)
         return;
     d_ptr->handlesChildEvents = enabled;
     d_ptr->updateAncestorFlag(QGraphicsItem::GraphicsItemFlag(-1));
 }
setInputMethodHints()
void QGraphicsItem::setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
Since
4.6
See also
inputMethodHints(), inputMethodQuery(), QInputContext
Definition at line 7806 of file qgraphicsitem.cpp.
Referenced by QGraphicsViewPrivate::updateInputMethodSensitivity().
 {
     Q_D(QGraphicsItem);
     d->imHints = hints;
     if (!hasFocus())
         return;
     d->scene->d_func()->updateInputMethodSensitivityInViews();
 #if !defined(QT_NO_IM) && (defined(Q_WS_X11) || defined(Q_WS_QWS) || defined(Q_OS_SYMBIAN))
     QWidget *fw = QApplication::focusWidget();
     if (!fw)
         return;
     for (int i = 0 ; i < scene()->views().count() ; ++i)
         if (scene()->views().at(i) == fw)
             if (QInputContext *inputContext = fw->inputContext())
                 inputContext->update();
 #endif
 }
setMatrix()
void QGraphicsItem::setMatrix (const QMatrix & matrix, bool combine = false)
Sets the item's affine transformation matrix.
This is a subset or the item's full transformation matrix, and might not represent the item's full transformation.
Use setTransform() instead.
See also
transform(), {The Graphics View Coordinate System}
Definition at line 4644 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemAnimation::setStep().
 {
     if (!d_ptr->transformData)
         d_ptr->transformData = new QGraphicsItemPrivate::TransformData;
     QTransform newTransform(combine ? QTransform(matrix) * d_ptr->transformData->transform : QTransform(matrix));
     if (d_ptr->transformData->transform == newTransform)
         return;
     // Update and set the new transformation.
     if (!(d_ptr->flags & ItemSendsGeometryChanges)) {
         d_ptr->setTransformHelper(newTransform);
         return;
     }
     // Notify the item that the transformation matrix is changing.
     const QVariant newMatrixVariant = QVariant::fromValue<QMatrix>(newTransform.toAffine());
     newTransform = QTransform(qvariant_cast<QMatrix>(itemChange(ItemMatrixChange, newMatrixVariant)));
     if (d_ptr->transformData->transform == newTransform)
         return;
     // Update and set the new transformation.
     d_ptr->setTransformHelper(newTransform);
     // Send post-notification.
     itemChange(ItemTransformHasChanged, QVariant::fromValue<QTransform>(newTransform));
 }
setOpacity()
void QGraphicsItem::setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
Since
4.5
0 (transparent) and 1.0 (opaque). The item's local opacity is combined with parent and ancestor opacities into the effectiveOpacity().
By default, opacity propagates from parent to child, so if a parent's opacity is 0.5 and the child is also 0.5, the child's effective opacity will be 0.25.
The opacity property decides the state of the painter passed to the paint() function. If the item is cached, i.e., ItemCoordinateCache or DeviceCoordinateCache, the effective property will be applied to the item's cache as it is rendered.
There are two item flags that affect how the item's opacity is combined with the parent: ItemIgnoresParentOpacity and ItemDoesntPropagateOpacityToChildren.
See also
opacity(), effectiveOpacity()
Definition at line 2849 of file qgraphicsitem.cpp.
Referenced by QDeclarativeFlipablePrivate::updateSceneTransformFromParent().
 {
     // Notify change.
     const QVariant newOpacityVariant(itemChange(ItemOpacityChange, opacity));
     // Normalized opacity
     qreal newOpacity = qBound(qreal(0), newOpacityVariant.toReal(), qreal(1));
     // No change? Done.
     if (newOpacity == d_ptr->opacity)
         return;
     bool wasFullyTransparent = d_ptr->isOpacityNull();
     d_ptr->opacity = newOpacity;
     // Notify change.
     itemChange(ItemOpacityHasChanged, newOpacityVariant);
     // Update.
     if (d_ptr->scene) {
 #ifndef QT_NO_GRAPHICSEFFECT
         d_ptr->invalidateParentGraphicsEffectsRecursively();
         if (!(d_ptr->flags & ItemDoesntPropagateOpacityToChildren))
             d_ptr->invalidateChildGraphicsEffectsRecursively(QGraphicsItemPrivate::OpacityChanged);
 #endif //QT_NO_GRAPHICSEFFECT
         d_ptr->scene->d_func()->markDirty(this, QRectF(),
                                           /*invalidateChildren=*/true,
                                           /*force=*/false,
                                           /*ignoreOpacity=*/d_ptr->isOpacityNull());
         if (wasFullyTransparent)
             d_ptr->paintedViewBoundingRectsNeedRepaint = 1;
     }
     if (d_ptr->isObject)
         emit static_cast<QGraphicsObject *>(this)->opacityChanged();
 }
setPanelModality()
void QGraphicsItem::setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
Since
4.6
Changing the modality of a visible item takes effect immediately.
Definition at line 2147 of file qgraphicsitem.cpp.
 {
     if (d_ptr->panelModality == panelModality)
         return;
     PanelModality previousModality = d_ptr->panelModality;
     bool enterLeaveModal = (isPanel() && d_ptr->scene && isVisible());
     if (enterLeaveModal && panelModality == NonModal)
         d_ptr->scene->d_func()->leaveModal(this);
     d_ptr->panelModality = panelModality;
     if (enterLeaveModal && d_ptr->panelModality != NonModal)
         d_ptr->scene->d_func()->enterModal(this, previousModality);
 }
setParentItem()
void QGraphicsItem::setParentItem (QGraphicsItem * newParent)
Sets this item's parent item to newParent.
If this item already has a parent, it is first removed from the previous parent. If newParent is 0, this item will become a top-level item.
Note that this implicitly adds this graphics item to the scene of the parent. You should not add the item to the scene yourself.
Calling this function on an item that is an ancestor of newParent have undefined behaviour.
See also
parentItem(), childItems()
Definition at line 1786 of file qgraphicsitem.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_sourceLoaded(), QGraphicsScene::addItem(), QGraphicsItemGroup::addToGroup(), QGraphicsItemPrivate::children_append(), QGraphicsItemPrivate::children_clear(), children_clear_helper(), QDeclarativeLoaderPrivate::clear(), QDeclarativeItemPrivate::data_append(), QDeclarativeFlickablePrivate::data_append(), QGraphicsItem(), qgraphicsobject_autoParent(), QGraphicsItemGroup::removeFromGroup(), QGraphicsScenePrivate::removeItemHelper(), QDeclarativeItem::setParentItem(), and ~QGraphicsItem().
 {
     if (newParent == this) {
         qWarning("QGraphicsItem::setParentItem: cannot assign %p as a parent of itself", this);
         return;
     }
     if (newParent == d_ptr->parent)
         return;
     const QVariant newParentVariant(itemChange(QGraphicsItem::ItemParentChange,
                                                QVariant::fromValue<QGraphicsItem *>(newParent)));
     newParent = qvariant_cast<QGraphicsItem *>(newParentVariant);
     if (newParent == d_ptr->parent)
         return;
     const QVariant thisPointerVariant(QVariant::fromValue<QGraphicsItem *>(this));
     d_ptr->setParentItemHelper(newParent, &newParentVariant, &thisPointerVariant);
 }
setPos() [1/2]
void QGraphicsItem::setPos (const QPointF & pos)
Sets the position of the item to pos, which is in parent coordinates.
For items with no parent, pos is in scene coordinates.
The position of the item describes its origin (local coordinate (0, 0)) in parent coordinates.
See also
pos(), scenePos(), {The Graphics View Coordinate System}
Definition at line 3947 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QDeclarativeGridView::createdItem(), mouseMoveEvent(), QGraphicsItemGroup::removeFromGroup(), QGraphicsWidget::setGeometry(), FxGridItem::setPosition(), QGraphicsItemAnimation::setStep(), setX(), setY(), and QDeclarativeGridViewPrivate::updateUnrequestedPositions().
 {
     if (d_ptr->pos == pos)
         return;
     if (d_ptr->inDestructor)
         return;
     // Update and repositition.
     if (!(d_ptr->flags & (ItemSendsGeometryChanges | ItemSendsScenePositionChanges))) {
         d_ptr->setPosHelper(pos);
         if (d_ptr->isWidget)
             static_cast<QGraphicsWidget *>(this)->d_func()->setGeometryFromSetPos();
         if (d_ptr->scenePosDescendants)
             d_ptr->sendScenePosChange();
         return;
     }
     // Notify the item that the position is changing.
     const QVariant newPosVariant(itemChange(ItemPositionChange, QVariant::fromValue<QPointF>(pos)));
     QPointF newPos = newPosVariant.toPointF();
     if (newPos == d_ptr->pos)
         return;
     // Update and repositition.
     d_ptr->setPosHelper(newPos);
     // Send post-notification.
     itemChange(QGraphicsItem::ItemPositionHasChanged, newPosVariant);
     d_ptr->sendScenePosChange();
 }
setPos() [2/2]
void QGraphicsItem::setPos (qreal x, qreal y) inline
This convenience function is equivalent to calling setPos(QPointF(x, y)).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 501 of file qgraphicsitem.h.
 { setPos(QPointF(ax, ay)); }
setRotation()
void QGraphicsItem::setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
Since
4.6
The default value is 0 (i.e., the item is not rotated). Assigning a negative value will rotate the item counter-clockwise. Normally the rotation angle is in the range (-360, 360), but it's also possible to assign values outside of this range (e.g., a rotation of 370 degrees is the same as a rotation of 10 degrees).
The item is rotated around its transform origin point, which by default is (0, 0). You can select a different transformation origin by calling setTransformOriginPoint().
The rotation is combined with the item's scale(), transform() and transformations() to map the item's coordinate system to the parent item.
See also
rotation(), setTransformOriginPoint(), {Transformations}
Definition at line 4120 of file qgraphicsitem.cpp.
Referenced by QDeclarativeParentChangePrivate::doChange(), and QDeclarativePinchArea::updatePinch().
 {
     prepareGeometryChange();
     qreal newRotation = angle;
     if (d_ptr->flags & ItemSendsGeometryChanges) {
         // Notify the item that the rotation is changing.
         const QVariant newRotationVariant(itemChange(ItemRotationChange, angle));
         newRotation = newRotationVariant.toReal();
     }
     if (!d_ptr->transformData)
         d_ptr->transformData = new QGraphicsItemPrivate::TransformData;
     if (d_ptr->transformData->rotation == newRotation)
         return;
     d_ptr->transformData->rotation = newRotation;
     d_ptr->transformData->onlyTransform = false;
     d_ptr->dirtySceneTransform = 1;
     // Send post-notification.
     if (d_ptr->flags & ItemSendsGeometryChanges)
         itemChange(ItemRotationHasChanged, newRotation);
     if (d_ptr->isObject)
         emit static_cast<QGraphicsObject *>(this)->rotationChanged();
     d_ptr->transformChanged();
 }
setScale()
void QGraphicsItem::setScale (qreal factor)
Sets the scale factor of the item.
Since
4.6
The default scale factor is 1.0 (i.e., the item is not scaled). A scale factor of 0.0 will collapse the item to a single point. If you provide a negative scale factor, the item will be flipped and mirrored (i.e., rotated 180 degrees).
The item is scaled around its transform origin point, which by default is (0, 0). You can select a different transformation origin by calling setTransformOriginPoint().
The scale is combined with the item's rotation(), transform() and transformations() to map the item's coordinate system to the parent item.
See also
scale(), setTransformOriginPoint(), {Transformations Example}
Definition at line 4192 of file qgraphicsitem.cpp.
Referenced by QDeclarativeParentChangePrivate::doChange(), and QDeclarativePinchArea::updatePinch().
 {
     prepareGeometryChange();
     qreal newScale = factor;
     if (d_ptr->flags & ItemSendsGeometryChanges) {
         // Notify the item that the scale is changing.
         const QVariant newScaleVariant(itemChange(ItemScaleChange, factor));
         newScale = newScaleVariant.toReal();
     }
     if (!d_ptr->transformData)
         d_ptr->transformData = new QGraphicsItemPrivate::TransformData;
     if (d_ptr->transformData->scale == newScale)
         return;
     d_ptr->transformData->scale = newScale;
     d_ptr->transformData->onlyTransform = false;
     d_ptr->dirtySceneTransform = 1;
     // Send post-notification.
     if (d_ptr->flags & ItemSendsGeometryChanges)
         itemChange(ItemScaleHasChanged, newScale);
     if (d_ptr->isObject)
         emit static_cast<QGraphicsObject *>(this)->scaleChanged();
     d_ptr->transformChanged();
 }
setSelected()
void QGraphicsItem::setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
If the item is in a group, the whole group's selected state is toggled by this function. If the group is selected, all items in the group are also selected, and if the group is not selected, no item in the group is selected.
Only visible, enabled, selectable items can be selected. If selected is true and this item is either invisible or disabled or unselectable, this function does nothing.
By default, items cannot be selected. To enable selection, set the ItemIsSelectable flag.
This function is provided for convenience, allowing individual toggling of the selected state of an item. However, a more common way of selecting items is to call QGraphicsScene::setSelectionArea(), which will call this function for all visible, enabled, and selectable items within a specified area on the scene.
See also
isSelected(), QGraphicsScene::selectedItems()
Definition at line 2745 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::clearSelection(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), setFlags(), setSelected(), QGraphicsScene::setSelectionArea(), and QGraphicsItemPrivate::setVisibleHelper().
 {
     if (QGraphicsItemGroup *group = this->group()) {
         group->setSelected(selected);
         return;
     }
     if (!(d_ptr->flags & ItemIsSelectable) || !d_ptr->enabled || !d_ptr->visible)
         selected = false;
     if (d_ptr->selected == selected)
         return;
     const QVariant newSelectedVariant(itemChange(ItemSelectedChange, quint32(selected)));
     bool newSelected = newSelectedVariant.toBool();
     if (d_ptr->selected == newSelected)
         return;
     d_ptr->selected = newSelected;
     update();
     if (d_ptr->scene) {
         QGraphicsScenePrivate *sceneD = d_ptr->scene->d_func();
         if (selected) {
             sceneD->selectedItems << this;
         } else {
             // QGraphicsScene::selectedItems() lazily pulls out all items that are
             // no longer selected.
         }
         if (!sceneD->selectionChanging)
             emit d_ptr->scene->selectionChanged();
     }
     // Deliver post-change notification.
     itemChange(QGraphicsItem::ItemSelectedHasChanged, newSelectedVariant);
 }
setToolTip()
void QGraphicsItem::setToolTip (const QString & toolTip)
Sets the item's tool tip to toolTip.
If toolTip is empty, the item's tool tip is cleared.
See also
toolTip(), QToolTip
Definition at line 2232 of file qgraphicsitem.cpp.
Referenced by QGraphicsProxyWidget::eventFilter().
 {
     const QVariant toolTipVariant(itemChange(ItemToolTipChange, toolTip));
     d_ptr->setExtra(QGraphicsItemPrivate::ExtraToolTip, toolTipVariant.toString());
     itemChange(ItemToolTipHasChanged, toolTipVariant);
 }
setTransform()
void QGraphicsItem::setTransform (const QTransform & matrix, bool combine = false)
Sets the item's current transformation matrix to matrix.
Since
4.3
If combine is true, then matrix is combined with the current matrix; otherwise, matrix replaces the current matrix. combine is false by default.
To simplify interation with items using a transformed view, QGraphicsItem provides mapTo... and mapFrom... functions that can translate between items' and the scene's coordinates. For example, you can call mapToScene() to map an item coordiate to a scene coordinate, or mapFromScene() to map from scene coordinates to item coordinates.
The transformation matrix is combined with the item's rotation(), scale() and transformations() into a combined transformation that maps the item's coordinate system to its parent.
See also
transform(), setRotation(), setScale(), setTransformOriginPoint(), {The Graphics View Coordinate System}, {Transformations}
Definition at line 4696 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsItemGroup::removeFromGroup(), resetTransform(), rotate(), scale(), QDeclarativeFlipablePrivate::setBackTransform(), shear(), and translate().
 {
     if (!d_ptr->transformData)
         d_ptr->transformData = new QGraphicsItemPrivate::TransformData;
     QTransform newTransform(combine ? matrix * d_ptr->transformData->transform : matrix);
     if (d_ptr->transformData->transform == newTransform)
         return;
     // Update and set the new transformation.
     if (!(d_ptr->flags & (ItemSendsGeometryChanges | ItemSendsScenePositionChanges))) {
         d_ptr->setTransformHelper(newTransform);
         if (d_ptr->scenePosDescendants)
             d_ptr->sendScenePosChange();
         return;
     }
     // Notify the item that the transformation matrix is changing.
     const QVariant newTransformVariant(itemChange(ItemTransformChange,
                                                   QVariant::fromValue<QTransform>(newTransform)));
     newTransform = qvariant_cast<QTransform>(newTransformVariant);
     if (d_ptr->transformData->transform == newTransform)
         return;
     // Update and set the new transformation.
     d_ptr->setTransformHelper(newTransform);
     // Send post-notification.
     itemChange(ItemTransformHasChanged, newTransformVariant);
     d_ptr->sendScenePosChange();
 }
setTransformations()
void QGraphicsItem::setTransformations (const QList< QGraphicsTransform *> & transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
Since
4.6
If all you want is to rotate or scale an item, you should call setRotation() or setScale() instead. If you want to set an arbitrary transformation on an item, you can call setTransform().
QGraphicsTransform is for applying and controlling a chain of individual transformation operations on an item. It's particularly useful in animations, where each transform operation needs to be interpolated independently, or differently.
The transformations are combined with the item's rotation(), scale() and transform() to map the item's coordinate system to the parent item.
See also
scale(), setTransformOriginPoint(), {Transformations}
Definition at line 4272 of file qgraphicsitem.cpp.
 {
     prepareGeometryChange();
     if (!d_ptr->transformData)
         d_ptr->transformData = new QGraphicsItemPrivate::TransformData;
     d_ptr->transformData->graphicsTransforms = transformations;
     for (int i = 0; i < transformations.size(); ++i)
         transformations.at(i)->d_func()->setItem(this);
     d_ptr->transformData->onlyTransform = false;
     d_ptr->dirtySceneTransform = 1;
     d_ptr->transformChanged();
 }
setTransformOriginPoint() [1/2]
void QGraphicsItem::setTransformOriginPoint (const QPointF & origin)
Sets the origin point for the transformation in item coordinates.
Since
4.6
See also
transformOriginPoint(), {Transformations}
Definition at line 4348 of file qgraphicsitem.cpp.
Referenced by QDeclarativeItem::geometryChanged(), and QDeclarativeItem::setTransformOrigin().
 {
     prepareGeometryChange();
     QPointF newOrigin = origin;
     if (d_ptr->flags & ItemSendsGeometryChanges) {
         // Notify the item that the origin point is changing.
         const QVariant newOriginVariant(itemChange(ItemTransformOriginPointChange,
                                                    QVariant::fromValue<QPointF>(origin)));
         newOrigin = newOriginVariant.toPointF();
     }
     if (!d_ptr->transformData)
         d_ptr->transformData = new QGraphicsItemPrivate::TransformData;
     if (d_ptr->transformData->xOrigin == newOrigin.x()
         && d_ptr->transformData->yOrigin == newOrigin.y()) {
         return;
     }
     d_ptr->transformData->xOrigin = newOrigin.x();
     d_ptr->transformData->yOrigin = newOrigin.y();
     d_ptr->transformData->onlyTransform = false;
     d_ptr->dirtySceneTransform = 1;
     // Send post-notification.
     if (d_ptr->flags & ItemSendsGeometryChanges)
         itemChange(ItemTransformOriginPointHasChanged, QVariant::fromValue<QPointF>(newOrigin));
 }
setTransformOriginPoint() [2/2]
void QGraphicsItem::setTransformOriginPoint (qreal x, qreal y) inline
Sets the origin point for the transformation in item coordinates.
Since
4.6 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This is equivalent to calling setTransformOriginPoint(QPointF(x, y)).
See also
setTransformOriginPoint(), {Transformations}
Definition at line 320 of file qgraphicsitem.h.
     { setTransformOriginPoint(QPointF(ax,ay)); }
setVisible()
void QGraphicsItem::setVisible (bool visible)
If visible is true, the item is made visible.
Otherwise, the item is made invisible. Invisible items are not painted, nor do they receive any events. In particular, mouse events pass right through invisible items, and are delivered to any item that may be behind. Invisible items are also unselectable, they cannot take input focus, and are not detected by QGraphicsScene's item location functions.
If an item becomes invisible while grabbing the mouse, (i.e., while it is receiving mouse events,) it will automatically lose the mouse grab, and the grab is not regained by making the item visible again; it must receive a new mouse press to regain the mouse grab.
Similarly, an invisible item cannot have focus, so if the item has focus when it becomes invisible, it will lose focus, and the focus is not regained by simply making the item visible again.
If you hide a parent item, all its children will also be hidden. If you show a parent item, all children will be shown, unless they have been explicitly hidden (i.e., if you call setVisible(false) on a child, it will not be reshown even if its parent is hidden, and then shown again).
Items are visible by default; it is unnecessary to call setVisible() on a new item.
See also
isVisible(), show(), hide()
Definition at line 2568 of file qgraphicsitem.cpp.
Referenced by QDeclarativeLoaderPrivate::clear(), QDeclarativeListViewPrivate::createSection(), QGraphicsProxyWidget::eventFilter(), and QDeclarativeListViewPrivate::releaseItem().
 {
     d_ptr->setVisibleHelper(visible, /* explicit = */ true);
 }
setX()
void QGraphicsItem::setX (qreal x)
Set's the x coordinate of the item's position.
Since
4.6
Equivalent to calling setPos(x, y()).
See also
x(), setPos()
Definition at line 3840 of file qgraphicsitem.cpp.
Referenced by QDeclarativeListView::createdItem(), QDeclarativeParentChangePrivate::doChange(), QDeclarativeBasePositioner::positionX(), QDeclarativeLayoutItem::setGeometry(), QDeclarativeFlickablePrivate::setRoundedViewportX(), QDeclarativePathViewPrivate::updateItem(), QDeclarativePinchArea::updatePinch(), QDeclarativeParticlesPainter::updateSize(), and QDeclarativeListViewPrivate::updateUnrequestedPositions().
 {
     if (d_ptr->inDestructor)
         return;
     if (qIsNaN(x))
         return;
     setPos(QPointF(x, d_ptr->pos.y()));
 }
setY()
void QGraphicsItem::setY (qreal y)
Set's the y coordinate of the item's position.
Since
4.6
Equivalent to calling setPos(x(), y).
See also
x(), setPos()
Definition at line 3873 of file qgraphicsitem.cpp.
Referenced by QDeclarativeListView::createdItem(), QDeclarativeParentChangePrivate::doChange(), QDeclarativeBasePositioner::positionY(), QDeclarativeLayoutItem::setGeometry(), QDeclarativeFlickablePrivate::setRoundedViewportY(), QDeclarativePathViewPrivate::updateItem(), QDeclarativePinchArea::updatePinch(), QDeclarativeParticlesPainter::updateSize(), and QDeclarativeListViewPrivate::updateUnrequestedPositions().
 {
     if (d_ptr->inDestructor)
         return;
     if (qIsNaN(y))
         return;
     setPos(QPointF(d_ptr->pos.x(), y));
 }
setZValue()
void QGraphicsItem::setZValue (qreal z)
Sets the Z-value of the item to z.
The Z value decides the stacking order of sibling (neighboring) items. A sibling item of high Z value will always be drawn on top of another sibling item with a lower Z value.
If you restore the Z value, the item's insertion order will decide its stacking order.
The Z-value does not affect the item's size in any way.
The default Z-value is 0.
See also
zValue(), {QGraphicsItem::Sorting}{Sorting}, stackBefore(), ItemStacksBehindParent
Definition at line 4914 of file qgraphicsitem.cpp.
Referenced by QDeclarativeGridViewPrivate::createItem(), QDeclarativeListViewPrivate::createItem(), QDeclarativeListViewPrivate::createSection(), QmlJSDebugger::LiveLayerItem::LiveLayerItem(), QDeclarativePathView::refill(), QGraphicsScene::setActiveWindow(), QDeclarativeGridViewPrivate::updateFooter(), QDeclarativeListViewPrivate::updateFooter(), QDeclarativeGridViewPrivate::updateHeader(), and QDeclarativeListViewPrivate::updateHeader().
 {
     const QVariant newZVariant(itemChange(ItemZValueChange, z));
     qreal newZ = newZVariant.toReal();
     if (newZ == d_ptr->z)
         return;
     if (d_ptr->scene && d_ptr->scene->d_func()->indexMethod != QGraphicsScene::NoIndex) {
         // Z Value has changed, we have to notify the index.
         d_ptr->scene->d_func()->index->itemChange(this, ItemZValueChange, &newZ);
     }
     d_ptr->z = newZ;
     if (d_ptr->parent)
         d_ptr->parent->d_ptr->needSortChildren = 1;
     else if (d_ptr->scene)
         d_ptr->scene->d_func()->needSortTopLevelItems = 1;
     if (d_ptr->scene)
         d_ptr->scene->d_func()->markDirty(this, QRectF(), /*invalidateChildren=*/true);
     itemChange(ItemZValueHasChanged, newZVariant);
     if (d_ptr->flags & ItemNegativeZStacksBehindParent)
         setFlag(QGraphicsItem::ItemStacksBehindParent, z < qreal(0.0));
     if (d_ptr->isObject)
         emit static_cast<QGraphicsObject *>(this)->zChanged();
 }
shape()
QPainterPath QGraphicsItem::shape () const virtual
Returns the shape of this item as a QPainterPath in local coordinates.
The shape is used for many things, including collision detection, hit tests, and for the QGraphicsScene::items() functions.
The default implementation calls boundingRect() to return a simple rectangular shape, but subclasses can reimplement this function to return a more accurate shape for non-rectangular items. For example, a round item may choose to return an elliptic shape for better collision detection. For example:
QPainterPath RoundItem::shape() const
{
    QPainterPath path;
    path.addEllipse(boundingRect());
    return path;
}
The outline of a shape can vary depending on the width and style of the pen used when drawing. If you want to include this outline in the item's shape, you can create a shape from the stroke using QPainterPathStroker.
This function is called by the default implementations of contains() and collidesWithPath().
See also
boundingRect(), contains(), prepareGeometryChange(), QPainterPathStroker
Reimplemented in QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, QGraphicsPathItem, and QGraphicsWidget.
Definition at line 5168 of file qgraphicsitem.cpp.
Referenced by clipPath(), collidesWithItem(), collidesWithPath(), contains(), QGraphicsView::fitInView(), QAbstractGraphicsShapeItem::opaqueArea(), QGraphicsSceneIndexPrivate::recursive_items_helper(), setClip(), and QGraphicsLineItem::setLine().
 {
     QPainterPath path;
     path.addRect(boundingRect());
     return path;
 }
shear()
void QGraphicsItem::shear (qreal sh, qreal sv)
Use.
    setTransform(QTransform().
    \obsolete
shear(sh, sv), true);
instead.
Shears the current item transformation by (sh, sv).
See also
setTransform(), transform()
Definition at line 4834 of file qgraphicsitem.cpp.
 {
     setTransform(QTransform().shear(sh, sv), true);
 }
show()
void QGraphicsItem::show () inline
Shows the item.
(Items are visible by default.)
This convenience function is equivalent to calling setVisible(true).
See also
hide(), setVisible()
Definition at line 223 of file qgraphicsitem.h.
Referenced by QmlJSDebugger::BoundingRectHighlighter::createBoundingBox(), QmlJSDebugger::LiveSelectionRectangle::show(), and QmlJSDebugger::LiveSelectionIndicator::show().
 { setVisible(true); }
stackBefore()
void QGraphicsItem::stackBefore (const QGraphicsItem * sibling)
Stacks this item before sibling, which must be a sibling item (i.
Since
4.6
e., the two items must share the same parent item, or must both be toplevel items). The sibling must have the same Z value as this item, otherwise calling this function will have no effect.
By default, all sibling items are stacked by insertion order (i.e., the first item you add is drawn before the next item you add). If two items' Z values are different, then the item with the highest Z value is drawn on top. When the Z values are the same, the insertion order will decide the stacking order.
See also
setZValue(), ItemStacksBehindParent, {QGraphicsItem::Sorting}{Sorting}
Definition at line 5007 of file qgraphicsitem.cpp.
Referenced by QDeclarativeParentChangePrivate::doChange(), QDeclarativeRepeater::itemsInserted(), QDeclarativeRepeater::itemsMoved(), and QDeclarativeRepeater::regenerate().
 {
     if (sibling == this)
         return;
     if (!sibling || d_ptr->parent != sibling->parentItem()) {
         qWarning("QGraphicsItem::stackUnder: cannot stack under %p, which must be a sibling", sibling);
         return;
     }
     QList<QGraphicsItem *> *siblings = d_ptr->parent
                                        ? &d_ptr->parent->d_ptr->children
                                        : (d_ptr->scene ? &d_ptr->scene->d_func()->topLevelItems : 0);
     if (!siblings) {
         qWarning("QGraphicsItem::stackUnder: cannot stack under %p, which must be a sibling", sibling);
         return;
     }
     // First, make sure that the sibling indexes have no holes. This also
     // marks the children list for sorting.
     if (d_ptr->parent)
         d_ptr->parent->d_ptr->ensureSequentialSiblingIndex();
     else
         d_ptr->scene->d_func()->ensureSequentialTopLevelSiblingIndexes();
     // Only move items with the same Z value, and that need moving.
     int siblingIndex = sibling->d_ptr->siblingIndex;
     int myIndex = d_ptr->siblingIndex;
     if (myIndex >= siblingIndex) {
         siblings->move(myIndex, siblingIndex);
         // Fixup the insertion ordering.
         for (int i = 0; i < siblings->size(); ++i) {
             int &index = siblings->at(i)->d_ptr->siblingIndex;
             if (i != siblingIndex && index >= siblingIndex && index <= myIndex)
                 ++index;
         }
         d_ptr->siblingIndex = siblingIndex;
         for (int i = 0; i < siblings->size(); ++i) {
             int &index = siblings->at(i)->d_ptr->siblingIndex;
             if (i != siblingIndex && index >= siblingIndex && index <= myIndex)
                 siblings->at(i)->d_ptr->siblingOrderChange();
         }
         d_ptr->siblingOrderChange();
     }
 }
supportsExtension()
bool QGraphicsItem::supportsExtension (Extension extension) const protected virtual
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Warning
This function is not part of the public interface.
Reimplemented in QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, and QGraphicsPathItem.
Definition at line 7890 of file qgraphicsitem.cpp.
 {
     Q_UNUSED(extension);
     return false;
 }
toGraphicsObject() [1/2]
QGraphicsObject * QGraphicsItem::toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
Since
4.6
Definition at line 1753 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::cancelGesturesForChildren(), QGraphicsItemPrivate::children_at(), children_at_helper(), QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered(), QDeclarativeFlickablePrivate::data_at(), QGraphicsScenePrivate::gestureEventHandler(), QmlJSDebugger::QDeclarativeViewInspectorPrivate::highlight(), QmlJSDebugger::LiveSelectionTool::hoverMoveEvent(), QDeclarativeBasePositioner::itemChange(), operator<<(), QDeclarativeBasePositioner::prePositioning(), qobject_cast(), QGraphicsScenePrivate::sendEvent(), QGraphicsScenePrivate::setFocusItemHelper(), QmlJSDebugger::QDeclarativeViewInspectorPrivate::setSelectedItemsForTools(), QmlJSDebugger::AbstractLiveEditTool::titleForItem(), QmlJSDebugger::AbstractLiveEditTool::toGraphicsObjectList(), QmlJSDebugger::AbstractLiveEditTool::toQDeclarativeItem(), and updateMicroFocus().
 {
     return d_ptr->isObject ? static_cast<QGraphicsObject *>(this) : 0;
 }
toGraphicsObject() [2/2]
const QGraphicsObject * QGraphicsItem::toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
Since
4.6
Definition at line 1767 of file qgraphicsitem.cpp.
 {
     return d_ptr->isObject ? static_cast<const QGraphicsObject *>(this) : 0;
 }
toolTip()
QString QGraphicsItem::toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
See also
setToolTip(), QToolTip
Definition at line 2221 of file qgraphicsitem.cpp.
Referenced by QGraphicsProxyWidget::event(), and QGraphicsScene::helpEvent().
 {
     return d_ptr->extra(QGraphicsItemPrivate::ExtraToolTip).toString();
 }
topLevelItem()
QGraphicsItem * QGraphicsItem::topLevelItem () const
Returns this item's top-level item.
The top-level item is the item's topmost ancestor item whose parent is 0. If an item has no parent, its own pointer is returned (i.e., a top-level item is its own top-level item).
See also
parentItem()
Definition at line 1643 of file qgraphicsitem.cpp.
Referenced by QGraphicsScene::drawItems(), QGraphicsSceneBspTreeIndexPrivate::estimateItems(), QGraphicsWidgetPrivate::fixFocusChainBeforeReparenting(), and QGraphicsSceneFindItemBspTreeVisitor::visit().
 {
     QGraphicsItem *parent = const_cast<QGraphicsItem *>(this);
     while (QGraphicsItem *grandPa = parent->parentItem())
         parent = grandPa;
     return parent;
 }
topLevelWidget()
QGraphicsWidget * QGraphicsItem::topLevelWidget () const
Returns a pointer to the item's top level widget (i.
Since
4.4
e., the item's ancestor whose parent is 0, or whose parent is not a widget), or 0 if this item does not have a top level widget. If the item is its own top level widget, this function returns a pointer to the item itself.
Definition at line 1698 of file qgraphicsitem.cpp.
Referenced by topLevelWidget().
 {
     if (const QGraphicsWidget *p = parentWidget())
         return p->topLevelWidget();
     return isWidget() ? static_cast<QGraphicsWidget *>(const_cast<QGraphicsItem *>(this)) : 0;
 }
transform()
QTransform QGraphicsItem::transform () const
Returns this item's transformation matrix.
Since
4.3
The transformation matrix is combined with the item's rotation(), scale() and transformations() into a combined transformations for the item.
The default transformation matrix is an identity matrix.
See also
setTransform(), sceneTransform()
Definition at line 4070 of file qgraphicsitem.cpp.
Referenced by matrix(), and QGraphicsItemPrivate::setTransformHelper().
 {
     if (!d_ptr->transformData)
         return QTransform();
     return d_ptr->transformData->transform;
 }
transformations()
QList< QGraphicsTransform * > QGraphicsItem::transformations () const
Returns a list of graphics transforms that currently apply to this item.
Since
4.6
QGraphicsTransform is for applying and controlling a chain of individual transformation operations on an item. It's particularly useful in animations, where each transform operation needs to be interpolated independently, or differently.
The transformations are combined with the item's rotation(), scale() and transform() to map the item's coordinate system to the parent item.
See also
scale(), rotation(), transformOriginPoint(), {Transformations}
Definition at line 4242 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QGraphicsItemGroup::removeFromGroup(), and setTransformations().
 {
     if (!d_ptr->transformData)
         return QList<QGraphicsTransform *>();
     return d_ptr->transformData->graphicsTransforms;
 }
transformOriginPoint()
QPointF QGraphicsItem::transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
Since
4.6
The default is QPointF(0,0).
See also
setTransformOriginPoint(), {Transformations}
Definition at line 4331 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), QDeclarativeItem::geometryChanged(), and QGraphicsItemGroup::removeFromGroup().
 {
     if (!d_ptr->transformData)
         return QPointF(0,0);
     return QPointF(d_ptr->transformData->xOrigin, d_ptr->transformData->yOrigin);
 }
translate()
void QGraphicsItem::translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
For identical behavior, use
setTransform(QTransform::fromTranslate(dx, dy), true);
Translates the current item transformation by (dx, dy).
If all you want is to move an item, you should call moveBy() or setPos() instead; this function changes the item's translation, which is conceptually separate from its position.
See also
setTransform(), transform()
Definition at line 4860 of file qgraphicsitem.cpp.
 {
     setTransform(QTransform::fromTranslate(dx, dy), true);
 }
type()
int QGraphicsItem::type () const virtual
Returns the type of an item as an int.
All standard graphicsitem classes are associated with a unique value; see QGraphicsItem::Type. This type information is used by qgraphicsitem_cast() to distinguish between types.
The default implementation (in QGraphicsItem) returns UserType.
To enable use of qgraphicsitem_cast() with a custom item, reimplement this function and declare a Type enum value equal to your custom item's type. Custom items must return a value larger than or equal to UserType (65536).
For example:
class CustomItem : public QGraphicsItem
{
   ...
   enum { Type = UserType + 1 };
   int type() const
   {
       // Enable the use of qgraphicsitem_cast with this item.
       return Type;
   }
   ...
};
See also
UserType
Reimplemented in QGraphicsItemGroup, QGraphicsSimpleTextItem, QGraphicsTextItem, QGraphicsPixmapItem, QGraphicsLineItem, QGraphicsPolygonItem, QGraphicsEllipseItem, QGraphicsRectItem, QGraphicsPathItem, QGraphicsWidget, QmlJSDebugger::BoundingBoxPolygonItem, QGraphicsSvgItem, QGraphicsProxyWidget, QmlJSDebugger::SelectionRectShape, QmlJSDebugger::LiveLayerItem, and QmlJSDebugger::SubcomponentMaskLayerItem.
Definition at line 7013 of file qgraphicsitem.cpp.
Referenced by QDeclarativeGestureAreaParser::compile(), QMotifStyle::event(), QMacStyle::event(), QmlJSDebugger::isEditorItem(), ShaderEffectItem::lookThroughShaderCode(), qgraphicsitem_cast(), qt_graphicsItem_highlightSelected(), and ~QGraphicsItem().
 {
     return (int)UserType;
 }
ungrabKeyboard()
void QGraphicsItem::ungrabKeyboard ()
Releases the keyboard grab.
Since
4.4
See also
grabKeyboard(), ungrabMouse()
Definition at line 3791 of file qgraphicsitem.cpp.
 {
     if (!d_ptr->scene) {
         qWarning("QGraphicsItem::ungrabKeyboard: cannot ungrab keyboard without scene");
         return;
     }
     d_ptr->scene->d_func()->ungrabKeyboard(this);
 }
ungrabMouse()
void QGraphicsItem::ungrabMouse ()
Releases the mouse grab.
Since
4.4
See also
grabMouse(), ungrabKeyboard()
Definition at line 3723 of file qgraphicsitem.cpp.
Referenced by QGraphicsScenePrivate::clearMouseGrabber(), QGraphicsScenePrivate::grabMouse(), QDeclarativePathView::mouseReleaseEvent(), QDeclarativeMouseArea::mouseReleaseEvent(), QDeclarativeFlickable::mouseReleaseEvent(), QDeclarativePinchArea::mouseReleaseEvent(), QDeclarativeMouseArea::sendMouseEvent(), QDeclarativePinchArea::sendMouseEvent(), and setAcceptedMouseButtons().
 {
     if (!d_ptr->scene) {
         qWarning("QGraphicsItem::ungrabMouse: cannot ungrab mouse without scene");
         return;
     }
     d_ptr->scene->d_func()->ungrabMouse(this);
 }
unsetCursor()
void QGraphicsItem::unsetCursor ()
Clears the cursor from this item.
See also
hasCursor(), setCursor()
Definition at line 2319 of file qgraphicsitem.cpp.
 {
     d_ptr->unsetExtra(QGraphicsItemPrivate::ExtraCursor);
     d_ptr->hasCursor = 0;
     if (d_ptr->scene) {
         foreach (QGraphicsView *view, d_ptr->scene->views()) {
             if (view->underMouse() && view->itemAt(view->mapFromGlobal(QCursor::pos())) == this) {
                 QMetaObject::invokeMethod(view, "_q_unsetViewportCursor");
                 break;
             }
         }
     }
 }
update() [1/2]
void QGraphicsItem::update (const QRectF & rect = QRectF())
Schedules a redraw of the area covered by rect in this item.
You can call this function whenever your item needs to be redrawn, such as if it changes appearance or size.
This function does not cause an immediate paint; instead it schedules a paint request that is processed by QGraphicsView after control reaches the event loop. The item will only be redrawn if it is visible in any associated view.
As a side effect of the item being repainted, other items that overlap the area rect may also be repainted.
If the item is invisible (i.e., isVisible() returns false), this function does nothing.
See also
paint(), boundingRect()
Definition at line 6048 of file qgraphicsitem.cpp.
Referenced by QGraphicsItemGroup::addToGroup(), ShaderEffectSource::attachSourceItem(), QGraphicsWidget::changeEvent(), QDeclarativeBorderImage::doUpdate(), QDeclarativeRectangle::doUpdate(), QGraphicsWidget::event(), QGraphicsWidget::focusInEvent(), focusInEvent(), QGraphicsTextItem::focusInEvent(), QGraphicsWidget::focusOutEvent(), focusOutEvent(), QGraphicsTextItem::focusOutEvent(), hoverEnterEvent(), hoverLeaveEvent(), QDeclarativePathView::itemsRemoved(), QDeclarativeGridView::itemsRemoved(), QDeclarativeListView::itemsRemoved(), QDeclarativeBorderImage::load(), QDeclarativeImageBase::load(), ShaderEffectItem::markDirty(), QDeclarativeBorderImage::requestFinished(), QDeclarativeImageBase::requestFinished(), scroll(), QGraphicsWidget::setAutoFillBackground(), QAbstractGraphicsShapeItem::setBrush(), setCacheMode(), QDeclarativeTextInput::setColor(), QDeclarativeTextEdit::setColor(), QDeclarativeRectangle::setColor(), QDeclarativePaintedItem::setContentsScale(), QDeclarativePaintedItem::setContentsSize(), QGraphicsTextItem::setDefaultTextColor(), QGraphicsSvgItem::setElementId(), QDeclarativePaintedItem::setFillColor(), QDeclarativeImage::setFillMode(), QGraphicsPolygonItem::setFillRule(), QDeclarativeTextEdit::setFont(), QDeclarativeRectangle::setGradient(), QDeclarativeBorderImage::setGridScaledImage(), QDeclarativeBorderImage::setHorizontalTileMode(), QGraphicsLineItem::setLine(), QGraphicsSvgItem::setMaximumCacheSize(), QDeclarativeImageBase::setMirror(), QGraphicsPixmapItem::setOffset(), QGraphicsPathItem::setPath(), QAbstractGraphicsShapeItem::setPen(), QGraphicsLineItem::setPen(), QGraphicsPixmapItem::setPixmap(), QGraphicsPolygonItem::setPolygon(), QDeclarativeRectangle::setRadius(), QGraphicsRectItem::setRect(), QGraphicsEllipseItem::setRect(), setSelected(), QDeclarativeTextInput::setSelectedTextColor(), QDeclarativeTextEdit::setSelectedTextColor(), QDeclarativeTextInput::setSelectionColor(), QDeclarativeTextEdit::setSelectionColor(), QGraphicsSvgItem::setSharedRenderer(), QDeclarativeItem::setSmooth(), QGraphicsEllipseItem::setSpanAngle(), QGraphicsEllipseItem::setStartAngle(), QGraphicsSimpleTextItem::setText(), QGraphicsPixmapItem::setTransformationMode(), QDeclarativeBorderImage::setVerticalTileMode(), QDeclarativeTextEdit::updateImgCache(), QDeclarativeTextInput::updateRect(), updateRedirectedToGraphicsProxyWidget(), QDeclarativeTextEdit::updateSize(), and QDeclarativeTextInput::updateSize().
 {
     if (rect.isEmpty() && !rect.isNull())
         return;
     // Make sure we notify effects about invalidated source.
 #ifndef QT_NO_GRAPHICSEFFECT
     d_ptr->invalidateParentGraphicsEffectsRecursively();
 #endif //QT_NO_GRAPHICSEFFECT
 #ifndef QT_NO_GRAPHICSEFFECT
     if (!d_ptr->updateDueToGraphicsEffect) {
 #endif
         if (CacheMode(d_ptr->cacheMode) != NoCache) {
             // Invalidate cache.
             QGraphicsItemCache *cache = d_ptr->extraItemCache();
             if (!cache->allExposed) {
                 if (rect.isNull()) {
                     cache->allExposed = true;
                     cache->exposed.clear();
                 } else {
                     cache->exposed.append(rect);
                 }
             }
             // Only invalidate cache; item is already dirty.
             if (d_ptr->fullUpdatePending)
                 return;
         }
 #ifndef QT_NO_GRAPHICSEFFECT
     }
 #endif
     if (d_ptr->scene)
         d_ptr->scene->d_func()->markDirty(this, rect);
 }
update() [2/2]
void QGraphicsItem::update (qreal x, qreal y, qreal width, qreal height) inline
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 505 of file qgraphicsitem.h.
 { update(QRectF(ax, ay, width, height)); }
updateMicroFocus()
void QGraphicsItem::updateMicroFocus () protected
Updates the item's micro focus.
Since
4.7
See also
QInputContext
Definition at line 7831 of file qgraphicsitem.cpp.
Referenced by QGraphicsObject::updateMicroFocus().
 {
 #if !defined(QT_NO_IM) && (defined(Q_WS_X11) || defined(Q_WS_QWS) || defined(Q_OS_SYMBIAN))
     if (QWidget *fw = QApplication::focusWidget()) {
         if (scene()) {
             for (int i = 0 ; i < scene()->views().count() ; ++i) {
                 if (scene()->views().at(i) == fw) {
                     if (QInputContext *inputContext = fw->inputContext()) {
                         inputContext->update();
 #ifndef QT_NO_ACCESSIBILITY
                         // ##### is this correct
                         if (toGraphicsObject())
                             QAccessible::updateAccessibility(toGraphicsObject(), 0, QAccessible::StateChanged);
 #endif
                         break;
                     }
                 }
             }
         }
     }
 #endif
 }
wheelEvent()
void QGraphicsItem::wheelEvent (QGraphicsSceneWheelEvent * event) protected virtual
This event handler, for event event, can be reimplemented to receive wheel events for this item.
If you reimplement this function, event will be accepted by default.
If you ignore the event, (i.e., by calling QEvent::ignore(),) it will propagate to any item beneath this item. If no items accept the event, it will be ignored by the scene, and propagate to the view (e.g., the view's vertical scroll bar).
The default implementation ignores the event.
See also
sceneEvent()
Reimplemented in QDeclarativeFlickable, and QGraphicsProxyWidget.
Definition at line 7740 of file qgraphicsitem.cpp.
Referenced by sceneEvent(), and QDeclarativeFlickable::wheelEvent().
 {
     event->ignore();
 }
window()
QGraphicsWidget * QGraphicsItem::window () const
Returns the item's window, or 0 if this item does not have a window.
Since
4.4
If the item is a window, it will return itself. Otherwise it will return the closest ancestor that is a window.
See also
QGraphicsWidget::isWindow()
Definition at line 1717 of file qgraphicsitem.cpp.
Referenced by QShortcutMap::correctGraphicsWidgetContext(), QGraphicsWidget::initStyleOption(), QGraphicsScenePrivate::mousePressEventHandler(), and QGraphicsWidget::paintWindowFrame().
 {
     QGraphicsItem *p = panel();
     if (p && p->isWindow())
         return static_cast<QGraphicsWidget *>(p);
     return 0;
 }
x()
QGraphicsItem::x () const inline
This convenience function is equivalent to calling pos().
x().
\sa y()
Definition at line 280 of file qgraphicsitem.h.
Referenced by QGraphicsItemGroup::addToGroup(), QDeclarativeContents::calcWidth(), FxGridItem::colPos(), FxGridItem::contains(), QDeclarativeParentChangePrivate::doChange(), FxGridItem::endRowPos(), itemTransform(), QDeclarativeMouseArea::mouseMoveEvent(), QDeclarativePaintedItem::paint(), QDeclarativeParticlesPainter::paint(), QGraphicsItemGroup::removeFromGroup(), FxGridItem::rowPos(), QDeclarativeItem::setImplicitHeight(), QDeclarativeItem::setImplicitWidth(), QDeclarativeItem::setSize(), QDeclarativePinchArea::updatePinch(), QDeclarativeParticlesPainter::updateSize(), QDeclarativeListViewPrivate::updateUnrequestedPositions(), and QGraphicsWidget::windowFrameSectionAt().
 { return pos().x(); }
y()
QGraphicsItem::y () const inline
This convenience function is equivalent to calling pos().
y().
\sa x()
Definition at line 282 of file qgraphicsitem.h.
Referenced by QGraphicsItemGroup::addToGroup(), QDeclarativeContents::calcHeight(), QDeclarativeItem::childAt(), FxGridItem::colPos(), FxGridItem::contains(), QDeclarativeParentChangePrivate::doChange(), FxGridItem::endRowPos(), QDeclarativeMouseArea::mouseMoveEvent(), QDeclarativeParticlesPainter::paint(), QGraphicsItemGroup::removeFromGroup(), FxGridItem::rowPos(), QDeclarativeItem::setImplicitHeight(), QDeclarativeItem::setImplicitWidth(), QDeclarativeItem::setSize(), setupTextLayout(), setY(), ShaderEffectItem::updateGeometry(), QDeclarativePinchArea::updatePinch(), QDeclarativeParticlesPainter::updateSize(), QDeclarativeListViewPrivate::updateUnrequestedPositions(), and QGraphicsWidget::windowFrameSectionAt().
 { return pos().y(); }
zValue()
qreal QGraphicsItem::zValue () const
Returns the Z-value of the item.
The Z-value affects the stacking order of sibling (neighboring) items.
The default Z-value is 0.
See also
setZValue(), {QGraphicsItem::Sorting}{Sorting}, stackBefore(), ItemStacksBehindParent
Definition at line 4895 of file qgraphicsitem.cpp.
Referenced by operator<<(), and QGraphicsScene::setActiveWindow().
 {
     return d_ptr->z;
 }
Friends and Related Functions
::tst_QGraphicsItem
friend class ::tst_QGraphicsItem friend
Definition at line 493 of file qgraphicsitem.h.
QGestureManager
friend class QGestureManager friend
Definition at line 491 of file qgraphicsitem.h.
qgraphicsitem_cast()
T qgraphicsitem_cast (QGraphicsItem * item) related
Since
4.2
Returns the given item cast to type T if item is of type T; otherwise, 0 is returned.
Note
To make this function work correctly with custom items, reimplement the QGraphicsItem::type() function for each custom QGraphicsItem subclass.
See also
QGraphicsItem::type(), QGraphicsItem::UserType
Definition at line 1139 of file qgraphicsitem.h.
 {
     return int(static_cast<T>(0)->Type) == int(QGraphicsItem::Type)
         || (item && int(static_cast<T>(0)->Type) == item->type()) ? static_cast<T>(item) : 0;
 }
QGraphicsItemEffectSourcePrivate
friend class QGraphicsItemEffectSourcePrivate friend
Definition at line 488 of file qgraphicsitem.h.
Referenced by setGraphicsEffect().
QGraphicsItemGroup
friend class QGraphicsItemGroup friend
Definition at line 473 of file qgraphicsitem.h.
QGraphicsObject
friend class QGraphicsObject friend
Definition at line 480 of file qgraphicsitem.h.
QGraphicsProxyWidgetPrivate
friend class QGraphicsProxyWidgetPrivate friend
Definition at line 483 of file qgraphicsitem.h.
QGraphicsScene
friend class QGraphicsScene friend
Definition at line 474 of file qgraphicsitem.h.
QGraphicsSceneBspTree
friend class QGraphicsSceneBspTree friend
Definition at line 477 of file qgraphicsitem.h.
QGraphicsSceneBspTreeIndex
friend class QGraphicsSceneBspTreeIndex friend
Definition at line 486 of file qgraphicsitem.h.
QGraphicsSceneBspTreeIndexPrivate
friend class QGraphicsSceneBspTreeIndexPrivate friend
Definition at line 487 of file qgraphicsitem.h.
QGraphicsSceneFindItemBspTreeVisitor
friend class QGraphicsSceneFindItemBspTreeVisitor friend
Definition at line 476 of file qgraphicsitem.h.
QGraphicsSceneIndex
friend class QGraphicsSceneIndex friend
Definition at line 484 of file qgraphicsitem.h.
QGraphicsSceneIndexPrivate
friend class QGraphicsSceneIndexPrivate friend
Definition at line 485 of file qgraphicsitem.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 475 of file qgraphicsitem.h.
QGraphicsTransformPrivate
friend class QGraphicsTransformPrivate friend
Definition at line 489 of file qgraphicsitem.h.
QGraphicsView
friend class QGraphicsView friend
Definition at line 478 of file qgraphicsitem.h.
QGraphicsViewPrivate
friend class QGraphicsViewPrivate friend
Definition at line 479 of file qgraphicsitem.h.
QGraphicsWidget
friend class QGraphicsWidget friend
Definition at line 481 of file qgraphicsitem.h.
QGraphicsWidgetPrivate
friend class QGraphicsWidgetPrivate friend
Definition at line 482 of file qgraphicsitem.h.
qt_closestItemFirst
bool qt_closestItemFirst (const QGraphicsItem * item1, const QGraphicsItem * item2) friend
Returns true if item1 is on top of item2.
The items don't need to be siblings.
Warning
This function is not part of the public interface.
Definition at line 729 of file qgraphicsitem_p.h.
Referenced by isObscuredBy().
 {
     // Siblings? Just check their z-values.
     const QGraphicsItemPrivate *d1 = item1->d_ptr.data();
     const QGraphicsItemPrivate *d2 = item2->d_ptr.data();
     if (d1->parent == d2->parent)
         return qt_closestLeaf(item1, item2);
     // Find common ancestor, and each item's ancestor closest to the common
     // ancestor.
     int item1Depth = d1->depth();
     int item2Depth = d2->depth();
     const QGraphicsItem *p = item1;
     const QGraphicsItem *t1 = item1;
     while (item1Depth > item2Depth && (p = p->d_ptr->parent)) {
         if (p == item2) {
             // item2 is one of item1's ancestors; item1 is on top
             return !(t1->d_ptr->flags & QGraphicsItem::ItemStacksBehindParent);
         }
         t1 = p;
         --item1Depth;
     }
     p = item2;
     const QGraphicsItem *t2 = item2;
     while (item2Depth > item1Depth && (p = p->d_ptr->parent)) {
         if (p == item1) {
             // item1 is one of item2's ancestors; item1 is not on top
             return (t2->d_ptr->flags & QGraphicsItem::ItemStacksBehindParent);
         }
         t2 = p;
         --item2Depth;
     }
     // item1Ancestor is now at the same level as item2Ancestor, but not the same.
     const QGraphicsItem *p1 = t1;
     const QGraphicsItem *p2 = t2;
     while (t1 && t1 != t2) {
         p1 = t1;
         p2 = t2;
         t1 = t1->d_ptr->parent;
         t2 = t2->d_ptr->parent;
     }
     // in case we have a common ancestor, we compare the immediate children in the ancestor's path.
     // otherwise we compare the respective items' topLevelItems directly.
     return qt_closestLeaf(p1, p2);
 }
qt_closestLeaf
bool qt_closestLeaf (const QGraphicsItem * item1, const QGraphicsItem * item2) friend
Warning
This function is not part of the public interface.
Definition at line 791 of file qgraphicsitem_p.h.
 {
     // Return true if sibling item1 is on top of item2.
     const QGraphicsItemPrivate *d1 = item1->d_ptr.data();
     const QGraphicsItemPrivate *d2 = item2->d_ptr.data();
     bool f1 = d1->flags & QGraphicsItem::ItemStacksBehindParent;
     bool f2 = d2->flags & QGraphicsItem::ItemStacksBehindParent;
     if (f1 != f2)
         return f2;
     if (d1->z != d2->z)
         return d1->z > d2->z;
     return d1->siblingIndex > d2->siblingIndex;
 }
Properties
d_ptr
QScopedPointer<QGraphicsItemPrivate> QGraphicsItem::d_ptr protected
Definition at line 464 of file qgraphicsitem.h.
Referenced by QGraphicsScenePrivate::_q_polishItems(), QGraphicsScenePrivate::_q_updateScenePosDescendants(), QGraphicsSceneBspTreeIndexPrivate::_q_updateSortCache(), acceptDrops(), acceptedMouseButtons(), acceptHoverEvents(), acceptsHoverEvents(), acceptTouchEvents(), QGraphicsItemPrivate::addChild(), QGraphicsSceneBspTreeIndexPrivate::addItem(), QGraphicsScene::addItem(), addToIndex(), boundingRegionGranularity(), cacheMode(), QGraphicsItemPrivate::calcEffectiveOpacity(), childItems(), childrenBoundingRect(), QGraphicsItemPrivate::childrenBoundingRectHelper(), clearFocus(), QGraphicsItemPrivate::clearFocusHelper(), QGraphicsItemPrivate::clearSubFocus(), QGraphicsSceneBspTreeIndexPrivate::climbTree(), clipPath(), QGraphicsSceneBspTreeIndexPrivate::closestItemFirst_withCache(), QGraphicsSceneBspTreeIndexPrivate::closestItemLast_withCache(), collidesWithItem(), collidesWithPath(), collidingItems(), commonAncestorItem(), QGraphicsScene::contextMenuEvent(), cursor(), deviceTransform(), QGraphicsScenePrivate::draw(), QDeclarativeImplicitSizePaintedItem::drawContents(), QGraphicsScenePrivate::drawItemHelper(), QGraphicsScene::drawItems(), QGraphicsScenePrivate::drawSubtreeRecursive(), QGraphicsItemPrivate::effectiveBoundingRect(), effectiveOpacity(), QGraphicsItemPrivate::ensureSceneTransformRecursive(), QGraphicsItemPrivate::ensureSequentialSiblingIndex(), ensureVisible(), QGraphicsScenePrivate::enterModal(), QGraphicsSceneBspTreeIndexPrivate::estimateItems(), QGraphicsScenePrivate::filterDescendantEvent(), filtersChildEvents(), QGraphicsView::fitInView(), flags(), focusItem(), focusProxy(), focusScopeItem(), QGraphicsObject::grabGesture(), grabKeyboard(), grabMouse(), graphicsEffect(), group(), handlesChildEvents(), hasCursor(), hasFocus(), inputMethodQuery(), QGraphicsItemPrivate::insertionOrder(), installSceneEventFilter(), QGraphicsItemPrivate::invalidateChildGraphicsEffectsRecursively(), QGraphicsItemPrivate::invalidateDepthRecursively(), QGraphicsItemPrivate::invalidateParentGraphicsEffectsRecursively(), isActive(), isAncestorOf(), isBlockedByModalPanel(), isEnabled(), isPanel(), isSelected(), isVisible(), isVisibleTo(), isWidget(), isWindow(), QGraphicsScenePrivate::itemAcceptsHoverEvents_helper(), QGraphicsSceneBspTreeIndex::itemChange(), QGraphicsSceneBspTree::items(), itemTransform(), mapFromParent(), mapFromScene(), mapRectFromParent(), mapRectFromScene(), mapRectToParent(), mapRectToScene(), mapToParent(), mapToScene(), QGraphicsViewPrivate::mapToViewRect(), QGraphicsScenePrivate::markDirty(), QGraphicsItemPrivate::markParentDirty(), mouseMoveEvent(), mousePressEvent(), QGraphicsTextItem::mousePressEvent(), QGraphicsScenePrivate::mousePressEventHandler(), mouseReleaseEvent(), QGraphicsItemPrivate::movableAncestorIsSelected(), opacity(), QGraphicsView::paintEvent(), panel(), panelModality(), parentItem(), parentObject(), pos(), QGraphicsSceneBspTreeIndex::prepareBoundingRectChange(), prepareGeometryChange(), QGraphicsScenePrivate::processDirtyItemsRecursive(), QGraphicsItem(), QGraphicsObject::QGraphicsObject(), qt_closestItemFirst(), qt_closestLeaf(), QGraphicsSceneIndexPrivate::recursive_items_helper(), QGraphicsScenePrivate::registerTopLevelItem(), QGraphicsItemPrivate::removeChild(), QGraphicsItemGroup::removeFromGroup(), removeFromIndex(), QGraphicsSceneBspTreeIndexPrivate::removeItem(), QGraphicsScenePrivate::removeItemHelper(), removeSceneEventFilter(), QGraphicsScenePrivate::resetDirtyItem(), rotation(), scale(), scene(), sceneBoundingRect(), QGraphicsItemPrivate::sceneEffectiveBoundingRect(), sceneEvent(), sceneMatrix(), sceneTransform(), QGraphicsScenePrivate::sendDragDropEvent(), QGraphicsScenePrivate::sendHoverEvent(), QGraphicsScenePrivate::sendMouseEvent(), QGraphicsScenePrivate::sendTouchBeginEvent(), setAcceptDrops(), setAcceptedMouseButtons(), setAcceptHoverEvents(), setAcceptTouchEvents(), setActive(), setBoundingRegionGranularity(), setCacheMode(), setCursor(), setEnabled(), QGraphicsItemPrivate::setEnabledHelper(), setFiltersChildEvents(), setFlag(), setFlags(), setFocus(), QGraphicsItemPrivate::setFocusHelper(), setFocusProxy(), setGraphicsEffect(), setHandlesChildEvents(), QGraphicsTransformPrivate::setItem(), setMatrix(), QGraphicsSvgItem::setMaximumCacheSize(), setOpacity(), setPanelModality(), setParentItem(), QGraphicsItemPrivate::setParentItemHelper(), setPos(), setRotation(), setScale(), QGraphicsScenePrivate::setScenePosItemEnabled(), setSelected(), QGraphicsItemPrivate::setSubFocus(), setToolTip(), setTransform(), setTransformations(), setTransformOriginPoint(), QGraphicsViewPrivate::setUpdateClip(), setVisible(), QGraphicsItemPrivate::setVisibleHelper(), QGraphicsProxyWidgetPrivate::setWidget_helper(), setX(), setY(), setZValue(), stackBefore(), QGraphicsScenePrivate::storeMouseButtonsForMouseGrabber(), toGraphicsObject(), toolTip(), transform(), transformations(), transformOriginPoint(), QGraphicsScenePrivate::ungrabGesture(), QGraphicsObject::ungrabGesture(), ungrabKeyboard(), ungrabMouse(), QGraphicsScenePrivate::unregisterTopLevelItem(), unsetCursor(), update(), QGraphicsItemPrivate::updateChildWithGraphicsEffectFlagRecursively(), QGraphicsWidgetPrivate::updateFont(), QGraphicsScenePrivate::updateFont(), QGraphicsTransformPrivate::updateItem(), QGraphicsItemPrivate::updatePaintedViewBoundingRects(), QGraphicsWidgetPrivate::updatePalette(), QGraphicsScenePrivate::updatePalette(), QGraphicsScenePrivate::updateTouchPointsForItem(), QGraphicsSceneFindItemBspTreeVisitor::visit(), QGraphicsScene::wheelEvent(), zValue(), QDeclarativeItem::~QDeclarativeItem(), and ~QGraphicsItem().
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicsitem.h
/src/gui/graphicsview/qgraphicsitem.cpp