Qt 4.8: QWSSignalHandler Class Reference
QWSSignalHandler Class Reference
#include <qwssignalhandler_p.h>
Public Functions
void addLock (QLock *lock)
void addObject (QObject *object)
void addWSLock (QWSLock *wslock)
void removeLock (QLock *lock)
void removeWSLock (QWSLock *wslock)
~QWSSignalHandler ()
Static Public Functions
static QWSSignalHandler * instance ()
Private Functions
void clear ()
QWSSignalHandler ()
Static Private Functions
static void handleSignal (int signal)
Properties
QList< QLock * > locks
QObjectCleanupHandler objects
QHash< int, qt_sighandler_t > oldHandlers
QList< QWSLock * > wslocks
Friends
class QWSSignalHandlerPrivate
Detailed Description
Definition at line 73 of file qwssignalhandler_p.h.
Constructors and Destructors
~QWSSignalHandler()
QWSSignalHandler::~QWSSignalHandler ()
Definition at line 85 of file qwssignalhandler.cpp.
 {
     clear();
 }
QWSSignalHandler()
QWSSignalHandler::QWSSignalHandler () private
Definition at line 69 of file qwssignalhandler.cpp.
 {
     const int signums[] = { SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGABRT, SIGFPE,
                             SIGSEGV, SIGTERM, SIGBUS };
     const int n = sizeof(signums)/sizeof(int);
     for (int i = 0; i < n; ++i) {
         const int signum = signums[i];
         qt_sighandler_t old = signal(signum, handleSignal);
         if (old == SIG_IGN) // don't remove shm and semaphores when ignored
             signal(signum, old);
         else
             oldHandlers[signum] = (old == SIG_ERR ? SIG_DFL : old);
     }
 }
Functions
addLock()
void QWSSignalHandler::addLock (QLock * lock) inline
Definition at line 81 of file qwssignalhandler_p.h.
Referenced by QLock::QLock().
 { locks.append(lock); }
addObject()
void QWSSignalHandler::addObject (QObject * object) inline
Definition at line 86 of file qwssignalhandler_p.h.
Referenced by QAhiScreenPrivate::QAhiScreenPrivate(), QDirectFBScreenPrivate::QDirectFBScreenPrivate(), QLinuxFbScreenPrivate::QLinuxFbScreenPrivate(), QVNCScreenPrivate::QVNCScreenPrivate(), and QWSTtyKbPrivate::QWSTtyKbPrivate().
 { (void)objects.add(object); }
addWSLock()
void QWSSignalHandler::addWSLock (QWSLock * wslock) inline
Definition at line 83 of file qwssignalhandler_p.h.
Referenced by QWSLock::QWSLock().
 { wslocks.append(wslock); }
clear()
void QWSSignalHandler::clear () private
Definition at line 90 of file qwssignalhandler.cpp.
Referenced by handleSignal(), and ~QWSSignalHandler().
 {
 #if !defined(QT_NO_QWS_MULTIPROCESS)
     // it is safe to call d-tors directly here since, on normal exit,
     // lists should be empty; otherwise, we don't care about semi-alive objects
     // and the only important thing here is to unregister the system semaphores.
     while (!locks.isEmpty())
         locks.takeLast()->~QLock();
     while (!wslocks.isEmpty())
         wslocks.takeLast()->~QWSLock();
 #endif
     objects.clear();
 }
handleSignal()
void QWSSignalHandler::handleSignal (int signal) static private
Definition at line 104 of file qwssignalhandler.cpp.
Referenced by QWSSignalHandler().
 {
     QWSSignalHandler *h = instance();
     if (h) {
         signal(signum, h->oldHandlers[signum]);
         h->clear();
     }
     raise(signum);
 }
instance()
QWSSignalHandler * QWSSignalHandler::instance () static
Definition at line 64 of file qwssignalhandler.cpp.
Referenced by handleSignal(), QAhiScreenPrivate::QAhiScreenPrivate(), QDirectFBScreenPrivate::QDirectFBScreenPrivate(), QLinuxFbScreenPrivate::QLinuxFbScreenPrivate(), QLock::QLock(), QVNCScreenPrivate::QVNCScreenPrivate(), QWSLock::QWSLock(), QWSTtyKbPrivate::QWSTtyKbPrivate(), QLock::~QLock(), and QWSLock::~QWSLock().
 {
     return signalHandlerInstance();
 }
removeLock()
void QWSSignalHandler::removeLock (QLock * lock) inline
Definition at line 82 of file qwssignalhandler_p.h.
Referenced by QLock::~QLock().
 { locks.removeOne(lock); }
removeWSLock()
void QWSSignalHandler::removeWSLock (QWSLock * wslock) inline
Definition at line 84 of file qwssignalhandler_p.h.
Referenced by QWSLock::~QWSLock().
 { wslocks.removeOne(wslock); }
Friends and Related Functions
QWSSignalHandlerPrivate
friend class QWSSignalHandlerPrivate friend
Definition at line 102 of file qwssignalhandler_p.h.
Properties
locks
QList<QLock *> QWSSignalHandler::locks private
Definition at line 97 of file qwssignalhandler_p.h.
Referenced by clear().
objects
QObjectCleanupHandler QWSSignalHandler::objects private
Definition at line 100 of file qwssignalhandler_p.h.
Referenced by clear().
oldHandlers
QHash<int, qt_sighandler_t> QWSSignalHandler::oldHandlers private
Definition at line 95 of file qwssignalhandler_p.h.
Referenced by handleSignal(), and QWSSignalHandler().
wslocks
QList<QWSLock *> QWSSignalHandler::wslocks private
Definition at line 98 of file qwssignalhandler_p.h.
Referenced by clear().
The documentation for this class was generated from the following files:
/src/gui/embedded/qwssignalhandler_p.h
/src/gui/embedded/qwssignalhandler.cpp