Qt 4.8: QItemDelegate Class Reference
QItemDelegate Class Reference
The QItemDelegate class provides display and editing facilities for data items from a model.
#include <qitemdelegate.h>
Public Functions
QWidget * createEditor (QWidget *parent, const QStyleOptionViewItem &option, const QModelIndex &index) const
Returns the widget used to edit the item specified by index for editing.
bool hasClipping () const
QItemEditorFactory * itemEditorFactory () const
Returns the editor factory used by the item delegate.
void paint (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Renders the delegate using the given painter and style option for the item specified by index.
QItemDelegate (QObject *parent=0)
Constructs an item delegate with the given parent.
void setClipping (bool clip)
void setEditorData (QWidget *editor, const QModelIndex &index) const
Sets the data to be displayed and edited by the editor from the data model item specified by the model index.
void setItemEditorFactory (QItemEditorFactory *factory)
Sets the editor factory to be used by the item delegate to be the factory specified.
void setModelData (QWidget *editor, QAbstractItemModel *model, const QModelIndex &index) const
Gets data from the editor widget and stores it in the specified model at the item index.
QSize sizeHint (const QStyleOptionViewItem &option, const QModelIndex &index) const
Returns the size needed by the delegate to display the item specified by index, taking into account the style information provided by option.
void updateEditorGeometry (QWidget *editor, const QStyleOptionViewItem &option, const QModelIndex &index) const
Updates the editor for the item specified by index according to the style option given.
~QItemDelegate ()
Destroys the item delegate.
Public Functions inherited from QAbstractItemDelegate
QAbstractItemDelegate (QObject *parent=0)
Creates a new abstract item delegate with the given parent.
virtual ~QAbstractItemDelegate ()
Destroys the abstract item delegate.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QRect check (const QStyleOptionViewItem &option, const QRect &bounding, const QVariant &variant) const
Note that on Mac, if /usr/include/AssertMacros.
QPixmap decoration (const QStyleOptionViewItem &option, const QVariant &variant) const
Returns the pixmap used to decorate the root of the item view.
void doLayout (const QStyleOptionViewItem &option, QRect *checkRect, QRect *iconRect, QRect *textRect, bool hint) const
void drawBackground (QPainter *painter, const QStyleOptionViewItem &option, const QModelIndex &index) const
Renders the item background for the given index, using the given painter and style option.
virtual void drawCheck (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, Qt::CheckState state) const
Renders a check indicator within the rectangle specified by rect, using the given painter and style option, using the given state.
virtual void drawDecoration (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, const QPixmap &pixmap) const
Renders the decoration pixmap within the rectangle specified by rect using the given painter and style option.
virtual void drawDisplay (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect, const QString &text) const
Renders the item view text within the rectangle specified by rect using the given painter and style option.
virtual void drawFocus (QPainter *painter, const QStyleOptionViewItem &option, const QRect &rect) const
Renders the region within the rectangle specified by rect, indicating that it has the focus, using the given painter and style option.
bool editorEvent (QEvent *event, QAbstractItemModel *model, const QStyleOptionViewItem &option, const QModelIndex &index)
Reimplemented Function
bool eventFilter (QObject *object, QEvent *event)
Returns true if the given editor is a valid QWidget and the given event is handled; otherwise returns false.
QRect rect (const QStyleOptionViewItem &option, const QModelIndex &index, int role) const
QPixmap * selected (const QPixmap &pixmap, const QPalette &palette, bool enabled) const
Returns the selected version of the given pixmap using the given palette.
QStyleOptionViewItem setOptions (const QModelIndex &index, const QStyleOptionViewItem &option) const
QRect textRectangle (QPainter *painter, const QRect &rect, const QFont &font, const QString &text) const
Protected Functions inherited from QAbstractItemDelegate
QAbstractItemDelegate (QObjectPrivate &, QObject *parent=0)
Creates a new abstract item delegate with the given parent.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool clipping
if the delegate should clip the paint events
Additional Inherited Members
Public Types inherited from QAbstractItemDelegate
enum EndEditHint {
NoHint, EditNextItem, EditPreviousItem, SubmitModelCache,
RevertModelCache
}
This enum describes the different hints that the delegate can give to the model and view components to make editing data in a model a comfortable experience for the user.
Public Slots inherited from QAbstractItemDelegate
bool helpEvent (QHelpEvent *event, QAbstractItemView *view, const QStyleOptionViewItem &option, const QModelIndex &index)
Whenever a help event occurs, this function is called with the event view option and the index that corresponds to the item where the event occurs.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemDelegate
void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint=NoHint)
This signal is emitted when the user has finished editing an item using the specified editor.
void commitData (QWidget *editor)
This signal must be emitted when the editor widget has completed editing the data, and wants to write it back into the model.
void sizeHintChanged (const QModelIndex &)
This signal must be emitted when the sizeHint() of index changed.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QAbstractItemDelegate
static QString elidedText (const QFontMetrics &fontMetrics, int width, Qt::TextElideMode mode, const QString &text)
Use QFontMetrics::elidedText() instead.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QItemDelegate class provides display and editing facilities for data items from a model.
QItemDelegate can be used to provide custom display features and editor widgets for item views based on QAbstractItemView subclasses. Using a delegate for this purpose allows the display and editing mechanisms to be customized and developed independently from the model and view.
The QItemDelegate class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}. Note that QStyledItemDelegate has taken over the job of drawing Qt's item views. We recommend the use of QStyledItemDelegate when creating new delegates.
When displaying items from a custom model in a standard view, it is often sufficient to simply ensure that the model returns appropriate data for each of the roles that determine the appearance of items in views. The default delegate used by Qt's standard views uses this role information to display items in most of the common forms expected by users. However, it is sometimes necessary to have even more control over the appearance of items than the default delegate can provide.
This class provides default implementations of the functions for painting item data in a view and editing data from item models. Default implementations of the paint() and sizeHint() virtual functions, defined in QAbstractItemDelegate, are provided to ensure that the delegate implements the correct basic behavior expected by views. You can reimplement these functions in subclasses to customize the appearance of items.
When editing data in an item view, QItemDelegate provides an editor widget, which is a widget that is placed on top of the view while editing takes place. Editors are created with a QItemEditorFactory; a default static instance provided by QItemEditorFactory is installed on all item delegates. You can set a custom factory using setItemEditorFactory() or set a new default factory with QItemEditorFactory::setDefaultFactory(). It is the data stored in the item model with the Qt::EditRole that is edited.
Only the standard editing functions for widget-based delegates are reimplemented here:
createEditor() returns the widget used to change data from the model and can be reimplemented to customize editing behavior.
setEditorData() provides the widget with data to manipulate.
updateEditorGeometry() ensures that the editor is displayed correctly with respect to the item view.
setModelData() returns updated data to the model.
The closeEditor() signal indicates that the user has completed editing the data, and that the editor widget can be destroyed.
Standard Roles and Data Types
The default delegate used by the standard views supplied with Qt associates each standard role (defined by Qt::ItemDataRole) with certain data types. Models that return data in these types can influence the appearance of the delegate as described in the following table.
Role Accepted Types
Warning
This function is not part of the public interface.
Qt::AccessibleDescriptionRole QString
Qt::AccessibleTextRole QString
Qt::BackgroundRole
QBrush
Qt::BackgroundColorRole
QColor (obsolete; use Qt::BackgroundRole instead)
Qt::CheckStateRole
Qt::CheckState
Qt::DecorationRole
QIcon, QPixmap and QColor
Qt::DisplayRole
QString and types with a string representation
Qt::EditRole
See QItemEditorFactory for details
Qt::FontRole
QFont
Qt::SizeHintRole
QSize
Warning
This function is not part of the public interface.
Qt::StatusTipRole
Qt::TextAlignmentRole
Qt::Alignment
Qt::ForegroundRole
QBrush
Qt::TextColorRole
QColor (obsolete; use Qt::ForegroundRole instead)
Warning
This function is not part of the public interface.
Qt::ToolTipRole
Qt::WhatsThisRole
If the default delegate does not allow the level of customization that you need, either for display purposes or for editing data, it is possible to subclass QItemDelegate to implement the desired behavior.
Subclassing
When subclassing QItemDelegate to create a delegate that displays items using a custom renderer, it is important to ensure that the delegate can render items suitably for all the required states; e.g. selected, disabled, checked. The documentation for the paint() function contains some hints to show how this can be achieved.
You can provide custom editors by using a QItemEditorFactory. The Color Editor Factory Example shows how a custom editor can be made available to delegates with the default item editor factory. This way, there is no need to subclass QItemDelegate. An alternative is to reimplement createEditor(), setEditorData(), setModelData(), and updateEditorGeometry(). This process is described in the Spin Box Delegate Example.
.-QItemDelegate
QStyledItemDelegate vs. QItemDelegate
Since Qt 4.4, there are two delegate classes: QItemDelegate and QStyledItemDelegate. However, the default delegate is QStyledItemDelegate. These two classes are independent alternatives to painting and providing editors for items in views. The difference between them is that QStyledItemDelegate uses the current style to paint its items. We therefore recommend using QStyledItemDelegate as the base class when implementing custom delegates or when working with Qt style sheets. The code required for either class should be equal unless the custom delegate needs to use the style for drawing.
See also
{Delegate Classes}, QStyledItemDelegate, QAbstractItemDelegate, {Spin Box Delegate Example}, {Settings Editor Example}, {Icons Example}
Definition at line 61 of file qitemdelegate.h.
Constructors and Destructors
QItemDelegate()
QItemDelegate::QItemDelegate (QObject * parent = 0) explicit
Constructs an item delegate with the given parent.
Definition at line 319 of file qitemdelegate.cpp.
     : QAbstractItemDelegate(*new QItemDelegatePrivate(), parent)
 {
 }
~QItemDelegate()
QItemDelegate::~QItemDelegate ()
Destroys the item delegate.
Definition at line 329 of file qitemdelegate.cpp.
 {
 }
Functions
check()
QRect QItemDelegate::check (const QStyleOptionViewItem & option, const QRect & bounding, const QVariant & value) const protected
Note that on Mac, if /usr/include/AssertMacros.
Warning
This function is not part of the public interface.
h is included prior to QItemDelegate, and the application is building in debug mode, the check(assertion) will conflict with QItemDelegate::check.
To avoid this problem, add
#ifdef check #undef check #endif
after including AssertMacros.h
Definition at line 1141 of file qitemdelegate.cpp.
Referenced by doLayout(), editorEvent(), paint(), rect(), and updateEditorGeometry().
 {
     if (value.isValid()) {
         Q_D(const QItemDelegate);
         QStyleOptionButton opt;
         opt.QStyleOption::operator=(option);
         opt.rect = bounding;
         const QWidget *widget = d->widget(option); // cast
         QStyle *style = widget ? widget->style() : QApplication::style();
         return style->subElementRect(QStyle::SE_ViewItemCheckIndicator, &opt, widget);
     }
     return QRect();
 }
createEditor()
QWidget * QItemDelegate::createEditor (QWidget * parent, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Returns the widget used to edit the item specified by index for editing.
The parent widget and style option are used to control how the editor widget appears.
See also
QAbstractItemDelegate::createEditor()
Reimplemented from QAbstractItemDelegate.
Definition at line 528 of file qitemdelegate.cpp.
 {
     Q_D(const QItemDelegate);
     if (!index.isValid())
         return 0;
     QVariant::Type t = static_cast<QVariant::Type>(index.data(Qt::EditRole).userType());
     const QItemEditorFactory *factory = d->f;
     if (factory == 0)
         factory = QItemEditorFactory::defaultFactory();
     return factory->createEditor(t, parent);
 }
decoration()
QPixmap QItemDelegate::decoration (const QStyleOptionViewItem & option, const QVariant & variant) const protected
Returns the pixmap used to decorate the root of the item view.
Warning
This function is not part of the public interface.
The style option controls the appearance of the root; the variant refers to the data associated with an item.
Definition at line 1014 of file qitemdelegate.cpp.
Referenced by doLayout(), paint(), and updateEditorGeometry().
 {
     Q_D(const QItemDelegate);
     switch (variant.type()) {
     case QVariant::Icon: {
         QIcon::Mode mode = d->iconMode(option.state);
         QIcon::State state = d->iconState(option.state);
         return qvariant_cast<QIcon>(variant).pixmap(option.decorationSize, mode, state); }
     case QVariant::Color: {
         static QPixmap pixmap(option.decorationSize);
         pixmap.fill(qvariant_cast<QColor>(variant));
         return pixmap; }
     default:
         break;
     }
     return qvariant_cast<QPixmap>(variant);
 }
doLayout()
void QItemDelegate::doLayout (const QStyleOptionViewItem & option, QRect * checkRect, QRect * pixmapRect, QRect * textRect, bool hint) const protected
Warning
This function is not part of the public interface.
Code duplicated in QCommonStylePrivate::viewItemLayout
Definition at line 876 of file qitemdelegate.cpp.
Referenced by editorEvent(), paint(), sizeHint(), and updateEditorGeometry().
 {
     Q_ASSERT(checkRect && pixmapRect && textRect);
     Q_D(const QItemDelegate);
     const QWidget *widget = d->widget(option);
     QStyle *style = widget ? widget->style() : QApplication::style();
     const bool hasCheck = checkRect->isValid();
     const bool hasPixmap = pixmapRect->isValid();
     const bool hasText = textRect->isValid();
     const int textMargin = hasText ? style->pixelMetric(QStyle::PM_FocusFrameHMargin, 0, widget) + 1 : 0;
     const int pixmapMargin = hasPixmap ? style->pixelMetric(QStyle::PM_FocusFrameHMargin, 0, widget) + 1 : 0;
     const int checkMargin = hasCheck ? style->pixelMetric(QStyle::PM_FocusFrameHMargin, 0, widget) + 1 : 0;
     int x = option.rect.left();
     int y = option.rect.top();
     int w, h;
     textRect->adjust(-textMargin, 0, textMargin, 0); // add width padding
     if (textRect->height() == 0 && (!hasPixmap || !hint)) {
         //if there is no text, we still want to have a decent height for the item sizeHint and the editor size
         textRect->setHeight(option.fontMetrics.height());
     }
     QSize pm(0, 0);
     if (hasPixmap) {
         pm = pixmapRect->size();
         pm.rwidth() += 2 * pixmapMargin;
     }
     if (hint) {
         h = qMax(checkRect->height(), qMax(textRect->height(), pm.height()));
         if (option.decorationPosition == QStyleOptionViewItem::Left
             || option.decorationPosition == QStyleOptionViewItem::Right) {
             w = textRect->width() + pm.width();
         } else {
             w = qMax(textRect->width(), pm.width());
         }
     } else {
         w = option.rect.width();
         h = option.rect.height();
     }
     int cw = 0;
     QRect check;
     if (hasCheck) {
         cw = checkRect->width() + 2 * checkMargin;
         if (hint) w += cw;
         if (option.direction == Qt::RightToLeft) {
             check.setRect(x + w - cw, y, cw, h);
         } else {
             check.setRect(x + checkMargin, y, cw, h);
         }
     }
     // at this point w should be the *total* width
     QRect display;
     QRect decoration;
     switch (option.decorationPosition) {
     case QStyleOptionViewItem::Top: {
         if (hasPixmap)
             pm.setHeight(pm.height() + pixmapMargin); // add space
         h = hint ? textRect->height() : h - pm.height();
         if (option.direction == Qt::RightToLeft) {
             decoration.setRect(x, y, w - cw, pm.height());
             display.setRect(x, y + pm.height(), w - cw, h);
         } else {
             decoration.setRect(x + cw, y, w - cw, pm.height());
             display.setRect(x + cw, y + pm.height(), w - cw, h);
         }
         break; }
     case QStyleOptionViewItem::Bottom: {
         if (hasText)
             textRect->setHeight(textRect->height() + textMargin); // add space
         h = hint ? textRect->height() + pm.height() : h;
         if (option.direction == Qt::RightToLeft) {
             display.setRect(x, y, w - cw, textRect->height());
             decoration.setRect(x, y + textRect->height(), w - cw, h - textRect->height());
         } else {
             display.setRect(x + cw, y, w - cw, textRect->height());
             decoration.setRect(x + cw, y + textRect->height(), w - cw, h - textRect->height());
         }
         break; }
     case QStyleOptionViewItem::Left: {
         if (option.direction == Qt::LeftToRight) {
             decoration.setRect(x + cw, y, pm.width(), h);
             display.setRect(decoration.right() + 1, y, w - pm.width() - cw, h);
         } else {
             display.setRect(x, y, w - pm.width() - cw, h);
             decoration.setRect(display.right() + 1, y, pm.width(), h);
         }
         break; }
     case QStyleOptionViewItem::Right: {
         if (option.direction == Qt::LeftToRight) {
             display.setRect(x + cw, y, w - pm.width() - cw, h);
             decoration.setRect(display.right() + 1, y, pm.width(), h);
         } else {
             decoration.setRect(x, y, pm.width(), h);
             display.setRect(decoration.right() + 1, y, w - pm.width() - cw, h);
         }
         break; }
     default:
         qWarning("doLayout: decoration position is invalid");
         decoration = *pixmapRect;
         break;
     }
     if (!hint) { // we only need to do the internal layout if we are going to paint
         *checkRect = QStyle::alignedRect(option.direction, Qt::AlignCenter,
                                          checkRect->size(), check);
         *pixmapRect = QStyle::alignedRect(option.direction, option.decorationAlignment,
                                           pixmapRect->size(), decoration);
         // the text takes up all available space, unless the decoration is not shown as selected
         if (option.showDecorationSelected)
             *textRect = display;
         else
             *textRect = QStyle::alignedRect(option.direction, option.displayAlignment,
                                             textRect->size().boundedTo(display.size()), display);
     } else {
         *checkRect = check;
         *pixmapRect = decoration;
         *textRect = display;
     }
 }
drawBackground()
void QItemDelegate::drawBackground (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const protected
Renders the item background for the given index, using the given painter and style option.
Since
4.2
Definition at line 847 of file qitemdelegate.cpp.
Referenced by paint().
 {
     if (option.showDecorationSelected && (option.state & QStyle::State_Selected)) {
         QPalette::ColorGroup cg = option.state & QStyle::State_Enabled
                                   ? QPalette::Normal : QPalette::Disabled;
         if (cg == QPalette::Normal && !(option.state & QStyle::State_Active))
             cg = QPalette::Inactive;
         painter->fillRect(option.rect, option.palette.brush(cg, QPalette::Highlight));
     } else {
         QVariant value = index.data(Qt::BackgroundRole);
         if (value.canConvert<QBrush>()) {
             QPointF oldBO = painter->brushOrigin();
             painter->setBrushOrigin(option.rect.topLeft());
             painter->fillRect(option.rect, qvariant_cast<QBrush>(value));
             painter->setBrushOrigin(oldBO);
         }
     }
 }
drawCheck()
void QItemDelegate::drawCheck (QPainter * painter, const QStyleOptionViewItem & option, const QRect & rect, Qt::CheckState state) const protected virtual
Renders a check indicator within the rectangle specified by rect, using the given painter and style option, using the given state.
Definition at line 808 of file qitemdelegate.cpp.
Referenced by paint().
 {
     Q_D(const QItemDelegate);
     if (!rect.isValid())
         return;
     QStyleOptionViewItem opt(option);
     opt.rect = rect;
     opt.state = opt.state & ~QStyle::State_HasFocus;
     switch (state) {
     case Qt::Unchecked:
         opt.state |= QStyle::State_Off;
         break;
     case Qt::PartiallyChecked:
         opt.state |= QStyle::State_NoChange;
         break;
     case Qt::Checked:
         opt.state |= QStyle::State_On;
         break;
     }
     const QWidget *widget = d->widget(option);
     QStyle *style = widget ? widget->style() : QApplication::style();
     style->drawPrimitive(QStyle::PE_IndicatorViewItemCheck, &opt, painter, widget);
 }
drawDecoration()
void QItemDelegate::drawDecoration (QPainter * painter, const QStyleOptionViewItem & option, const QRect & rect, const QPixmap & pixmap) const protected virtual
Renders the decoration pixmap within the rectangle specified by rect using the given painter and style option.
Definition at line 753 of file qitemdelegate.cpp.
Referenced by paint().
 {
     Q_D(const QItemDelegate);
     // if we have an icon, we ignore the pixmap
     if (!d->tmp.icon.isNull()) {
         d->tmp.icon.paint(painter, rect, option.decorationAlignment,
                           d->tmp.mode, d->tmp.state);
         return;
     }
     if (pixmap.isNull() || !rect.isValid())
         return;
     QPoint p = QStyle::alignedRect(option.direction, option.decorationAlignment,
                                    pixmap.size(), rect).topLeft();
     if (option.state & QStyle::State_Selected) {
         QPixmap *pm = selected(pixmap, option.palette, option.state & QStyle::State_Enabled);
         painter->drawPixmap(p, *pm);
     } else {
         painter->drawPixmap(p, pixmap);
     }
 }
drawDisplay()
void QItemDelegate::drawDisplay (QPainter * painter, const QStyleOptionViewItem & option, const QRect & rect, const QString & text) const protected virtual
Renders the item view text within the rectangle specified by rect using the given painter and style option.
Definition at line 669 of file qitemdelegate.cpp.
Referenced by paint().
 {
     Q_D(const QItemDelegate);
     QPalette::ColorGroup cg = option.state & QStyle::State_Enabled
                               ? QPalette::Normal : QPalette::Disabled;
     if (cg == QPalette::Normal && !(option.state & QStyle::State_Active))
         cg = QPalette::Inactive;
     if (option.state & QStyle::State_Selected) {
         painter->fillRect(rect, option.palette.brush(cg, QPalette::Highlight));
         painter->setPen(option.palette.color(cg, QPalette::HighlightedText));
     } else {
         painter->setPen(option.palette.color(cg, QPalette::Text));
     }
     if (text.isEmpty())
         return;
     if (option.state & QStyle::State_Editing) {
         painter->save();
         painter->setPen(option.palette.color(cg, QPalette::Text));
         painter->drawRect(rect.adjusted(0, 0, -1, -1));
         painter->restore();
     }
     const QStyleOptionViewItemV4 opt = option;
     const QWidget *widget = d->widget(option);
     QStyle *style = widget ? widget->style() : QApplication::style();
     const int textMargin = style->pixelMetric(QStyle::PM_FocusFrameHMargin, 0, widget) + 1;
     QRect textRect = rect.adjusted(textMargin, 0, -textMargin, 0); // remove width padding
     const bool wrapText = opt.features & QStyleOptionViewItemV2::WrapText;
     d->textOption.setWrapMode(wrapText ? QTextOption::WordWrap : QTextOption::ManualWrap);
     d->textOption.setTextDirection(option.direction);
     d->textOption.setAlignment(QStyle::visualAlignment(option.direction, option.displayAlignment));
     d->textLayout.setTextOption(d->textOption);
     d->textLayout.setFont(option.font);
     d->textLayout.setText(QItemDelegatePrivate::replaceNewLine(text));
     QSizeF textLayoutSize = d->doTextLayout(textRect.width());
     if (textRect.width() < textLayoutSize.width()
         || textRect.height() < textLayoutSize.height()) {
         QString elided;
         int start = 0;
         int end = text.indexOf(QChar::LineSeparator, start);
         if (end == -1) {
             elided += option.fontMetrics.elidedText(text, option.textElideMode, textRect.width());
         } else {
             while (end != -1) {
                 elided += option.fontMetrics.elidedText(text.mid(start, end - start),
                                                         option.textElideMode, textRect.width());
                 elided += QChar::LineSeparator;
                 start = end + 1;
                 end = text.indexOf(QChar::LineSeparator, start);
             }
             //let's add the last line (after the last QChar::LineSeparator)
             elided += option.fontMetrics.elidedText(text.mid(start),
                                                     option.textElideMode, textRect.width());
         }
         d->textLayout.setText(elided);
         textLayoutSize = d->doTextLayout(textRect.width());
     }
     const QSize layoutSize(textRect.width(), int(textLayoutSize.height()));
     const QRect layoutRect = QStyle::alignedRect(option.direction, option.displayAlignment,
                                                   layoutSize, textRect);
     // if we still overflow even after eliding the text, enable clipping
     if (!hasClipping() && (textRect.width() < textLayoutSize.width()
                            || textRect.height() < textLayoutSize.height())) {
         painter->save();
         painter->setClipRect(layoutRect);
         d->textLayout.draw(painter, layoutRect.topLeft(), QVector<QTextLayout::FormatRange>(), layoutRect);
         painter->restore();
     } else {
         d->textLayout.draw(painter, layoutRect.topLeft(), QVector<QTextLayout::FormatRange>(), layoutRect);
     }
 }
drawFocus()
void QItemDelegate::drawFocus (QPainter * painter, const QStyleOptionViewItem & option, const QRect & rect) const protected virtual
Renders the region within the rectangle specified by rect, indicating that it has the focus, using the given painter and style option.
Definition at line 781 of file qitemdelegate.cpp.
Referenced by paint().
 {
     Q_D(const QItemDelegate);
     if ((option.state & QStyle::State_HasFocus) == 0 || !rect.isValid())
         return;
     QStyleOptionFocusRect o;
     o.QStyleOption::operator=(option);
     o.rect = rect;
     o.state |= QStyle::State_KeyboardFocusChange;
     o.state |= QStyle::State_Item;
     QPalette::ColorGroup cg = (option.state & QStyle::State_Enabled)
                               ? QPalette::Normal : QPalette::Disabled;
     o.backgroundColor = option.palette.color(cg, (option.state & QStyle::State_Selected)
                                              ? QPalette::Highlight : QPalette::Window);
     const QWidget *widget = d->widget(option);
     QStyle *style = widget ? widget->style() : QApplication::style();
     style->drawPrimitive(QStyle::PE_FrameFocusRect, &o, painter, widget);
 }
editorEvent()
bool QItemDelegate::editorEvent (QEvent * event, QAbstractItemModel * model, const QStyleOptionViewItem & option, const QModelIndex & index) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemDelegate.
Definition at line 1276 of file qitemdelegate.cpp.
 {
     Q_ASSERT(event);
     Q_ASSERT(model);
     // make sure that the item is checkable
     Qt::ItemFlags flags = model->flags(index);
     if (!(flags & Qt::ItemIsUserCheckable) || !(option.state & QStyle::State_Enabled)
         || !(flags & Qt::ItemIsEnabled))
         return false;
     // make sure that we have a check state
     QVariant value = index.data(Qt::CheckStateRole);
     if (!value.isValid())
         return false;
     // make sure that we have the right event type
     if ((event->type() == QEvent::MouseButtonRelease)
         || (event->type() == QEvent::MouseButtonDblClick)
         || (event->type() == QEvent::MouseButtonPress)) {
         QRect checkRect = check(option, option.rect, Qt::Checked);
         QRect emptyRect;
         doLayout(option, &checkRect, &emptyRect, &emptyRect, false);
         QMouseEvent *me = static_cast<QMouseEvent*>(event);
         if (me->button() != Qt::LeftButton || !checkRect.contains(me->pos()))
             return false;
         // eat the double click events inside the check rect
         if ((event->type() == QEvent::MouseButtonPress)
             || (event->type() == QEvent::MouseButtonDblClick))
             return true;
     } else if (event->type() == QEvent::KeyPress) {
         if (static_cast<QKeyEvent*>(event)->key() != Qt::Key_Space
          && static_cast<QKeyEvent*>(event)->key() != Qt::Key_Select)
             return false;
     } else {
         return false;
     }
     Qt::CheckState state = (static_cast<Qt::CheckState>(value.toInt()) == Qt::Checked
                             ? Qt::Unchecked : Qt::Checked);
     return model->setData(index, state, Qt::CheckStateRole);
 }
eventFilter()
bool QItemDelegate::eventFilter (QObject * editor, QEvent * event) protected virtual
Returns true if the given editor is a valid QWidget and the given event is handled; otherwise returns false.
The following key press events are handled by default:
Tab
Backtab
Enter
Return
Esc
In the case of Tab, Backtab, Enter and Return key press events, the editor's data is comitted to the model and the editor is closed. If the event is a Tab key press the view will open an editor on the next item in the view. Likewise, if the event is a Backtab key press the view will open an editor on the previous item in the view.
If the event is a Esc key press event, the editor is closed without committing its data.
See also
commitData(), closeEditor()
Reimplemented from QObject.
Definition at line 1202 of file qitemdelegate.cpp.
 {
     QWidget *editor = qobject_cast<QWidget*>(object);
     if (!editor)
         return false;
     if (event->type() == QEvent::KeyPress) {
         switch (static_cast<QKeyEvent *>(event)->key()) {
         case Qt::Key_Tab:
             emit commitData(editor);
             emit closeEditor(editor, QAbstractItemDelegate::EditNextItem);
             return true;
         case Qt::Key_Backtab:
             emit commitData(editor);
             emit closeEditor(editor, QAbstractItemDelegate::EditPreviousItem);
             return true;
         case Qt::Key_Enter:
         case Qt::Key_Return:
 #ifndef QT_NO_TEXTEDIT
             if (qobject_cast<QTextEdit *>(editor) || qobject_cast<QPlainTextEdit *>(editor))
                 return false; // don't filter enter key events for QTextEdit
             // We want the editor to be able to process the key press
             // before committing the data (e.g. so it can do
             // validation/fixup of the input).
 #endif // QT_NO_TEXTEDIT
 #ifndef QT_NO_LINEEDIT
             if (QLineEdit *e = qobject_cast<QLineEdit*>(editor))
                 if (!e->hasAcceptableInput())
                     return false;
 #endif // QT_NO_LINEEDIT
             QMetaObject::invokeMethod(this, "_q_commitDataAndCloseEditor",
                                       Qt::QueuedConnection, Q_ARG(QWidget*, editor));
             return false;
         case Qt::Key_Escape:
             // don't commit data
             emit closeEditor(editor, QAbstractItemDelegate::RevertModelCache);
             break;
         default:
             return false;
         }
         if (editor->parentWidget())
             editor->parentWidget()->setFocus();
         return true;
     } else if (event->type() == QEvent::FocusOut || (event->type() == QEvent::Hide && editor->isWindow())) {
         //the Hide event will take care of he editors that are in fact complete dialogs
         if (!editor->isActiveWindow() || (QApplication::focusWidget() != editor)) {
             QWidget *w = QApplication::focusWidget();
             while (w) { // don't worry about focus changes internally in the editor
                 if (w == editor)
                     return false;
                 w = w->parentWidget();
             }
 #ifndef QT_NO_DRAGANDDROP
             // The window may lose focus during an drag operation.
             // i.e when dragging involves the taskbar on Windows.
             if (QDragManager::self() && QDragManager::self()->object != 0)
                 return false;
 #endif
             emit commitData(editor);
             emit closeEditor(editor, NoHint);
         }
     } else if (event->type() == QEvent::ShortcutOverride) {
         if (static_cast<QKeyEvent*>(event)->key() == Qt::Key_Escape) {
             event->accept();
             return true;
         }
     }
     return false;
 }
hasClipping()
bool QItemDelegate::hasClipping () const
Definition at line 346 of file qitemdelegate.cpp.
Referenced by drawDisplay().
 {
     Q_D(const QItemDelegate);
     return d->clipPainting;
 }
itemEditorFactory()
QItemEditorFactory * QItemDelegate::itemEditorFactory () const
Returns the editor factory used by the item delegate.
If no editor factory is set, the function will return null.
See also
setItemEditorFactory()
Definition at line 645 of file qitemdelegate.cpp.
 {
     Q_D(const QItemDelegate);
     return d->f;
 }
paint()
void QItemDelegate::paint (QPainter * painter, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Renders the delegate using the given painter and style option for the item specified by index.
When reimplementing this function in a subclass, you should update the area held by the option's rect variable, using the option's state variable to determine the state of the item to be displayed, and adjust the way it is painted accordingly.
For example, a selected item may need to be displayed differently to unselected items, as shown in the following code:
    if (option.state & QStyle::State_Selected)
        painter->fillRect(option.rect, option.palette.highlight());
    int size = qMin(option.rect.width(), option.rect.height());
    int brightness = index.model()->data(index, Qt::DisplayRole).toInt();
    double radius = (size/2.0) - (brightness/255.0 * size/2.0);
    if (radius == 0.0)
        return;
    painter->save();
    painter->setRenderHint(QPainter::Antialiasing, true);
    painter->setPen(Qt::NoPen);
    if (option.state & QStyle::State_Selected)
        painter->setBrush(option.palette.highlightedText());
    else
...
After painting, you should ensure that the painter is returned to its the state it was supplied in when this function was called. For example, it may be useful to call QPainter::save() before painting and QPainter::restore() afterwards.
See also
QStyle::State
Implements QAbstractItemDelegate.
Reimplemented in QCalendarDelegate, QComboBoxDelegate, and QCompleterItemDelegate.
Definition at line 416 of file qitemdelegate.cpp.
Referenced by QColumnViewDelegate::paint(), QCompleterItemDelegate::paint(), QComboBoxDelegate::paint(), QCalendarDelegate::paint(), and QCalendarDelegate::paintCell().
 {
     Q_D(const QItemDelegate);
     Q_ASSERT(index.isValid());
     QStyleOptionViewItemV4 opt = setOptions(index, option);
     const QStyleOptionViewItemV2 *v2 = qstyleoption_cast<const QStyleOptionViewItemV2 *>(&option);
     opt.features = v2 ? v2->features
                     : QStyleOptionViewItemV2::ViewItemFeatures(QStyleOptionViewItemV2::None);
     const QStyleOptionViewItemV3 *v3 = qstyleoption_cast<const QStyleOptionViewItemV3 *>(&option);
     opt.locale = v3 ? v3->locale : QLocale();
     opt.widget = v3 ? v3->widget : 0;
     // prepare
     painter->save();
     if (d->clipPainting)
         painter->setClipRect(opt.rect);
     // get the data and the rectangles
     QVariant value;
     QPixmap pixmap;
     QRect decorationRect;
     value = index.data(Qt::DecorationRole);
     if (value.isValid()) {
         // ### we need the pixmap to call the virtual function
         pixmap = decoration(opt, value);
         if (value.type() == QVariant::Icon) {
             d->tmp.icon = qvariant_cast<QIcon>(value);
             d->tmp.mode = d->iconMode(option.state);
             d->tmp.state = d->iconState(option.state);
             const QSize size = d->tmp.icon.actualSize(option.decorationSize,
                                                       d->tmp.mode, d->tmp.state);
             decorationRect = QRect(QPoint(0, 0), size);
         } else {
             d->tmp.icon = QIcon();
             decorationRect = QRect(QPoint(0, 0), pixmap.size());
         }
     } else {
         d->tmp.icon = QIcon();
         decorationRect = QRect();
     }
     QString text;
     QRect displayRect;
     value = index.data(Qt::DisplayRole);
     if (value.isValid() && !value.isNull()) {
         text = QItemDelegatePrivate::valueToText(value, opt);
         displayRect = textRectangle(painter, d->textLayoutBounds(opt), opt.font, text);
     }
     QRect checkRect;
     Qt::CheckState checkState = Qt::Unchecked;
     value = index.data(Qt::CheckStateRole);
     if (value.isValid()) {
         checkState = static_cast<Qt::CheckState>(value.toInt());
         checkRect = check(opt, opt.rect, value);
     }
     // do the layout
     doLayout(opt, &checkRect, &decorationRect, &displayRect, false);
     // draw the item
     drawBackground(painter, opt, index);
     drawCheck(painter, opt, checkRect, checkState);
     drawDecoration(painter, opt, decorationRect, pixmap);
     drawDisplay(painter, opt, displayRect, text);
     drawFocus(painter, opt, displayRect);
     // done
     painter->restore();
 }
rect()
QRect QItemDelegate::rect (const QStyleOptionViewItem & option, const QModelIndex & index, int role) const protected
Warning
This function is not part of the public interface.
Definition at line 1089 of file qitemdelegate.cpp.
Referenced by drawCheck(), drawDecoration(), drawFocus(), and sizeHint().
 {
     Q_D(const QItemDelegate);
     QVariant value = index.data(role);
     if (role == Qt::CheckStateRole)
         return check(option, option.rect, value);
     if (value.isValid() && !value.isNull()) {
         switch (value.type()) {
         case QVariant::Invalid:
             break;
         case QVariant::Pixmap:
             return QRect(QPoint(0, 0), qvariant_cast<QPixmap>(value).size());
         case QVariant::Image:
             return QRect(QPoint(0, 0), qvariant_cast<QImage>(value).size());
         case QVariant::Icon: {
             QIcon::Mode mode = d->iconMode(option.state);
             QIcon::State state = d->iconState(option.state);
             QIcon icon = qvariant_cast<QIcon>(value);
             QSize size = icon.actualSize(option.decorationSize, mode, state);
             return QRect(QPoint(0, 0), size); }
         case QVariant::Color:
             return QRect(QPoint(0, 0), option.decorationSize);
         case QVariant::String:
         default: {
             QString text = QItemDelegatePrivate::valueToText(value, option);
             value = index.data(Qt::FontRole);
             QFont fnt = qvariant_cast<QFont>(value).resolve(option.font);
             return textRectangle(0, d->textLayoutBounds(option), fnt, text); }
         }
     }
     return QRect();
 }
selected()
QPixmap * QItemDelegate::selected (const QPixmap & pixmap, const QPalette & palette, bool enabled) const protected
Returns the selected version of the given pixmap using the given palette.
Warning
This function is not part of the public interface.
The enabled argument decides whether the normal or disabled highlight color of the palette is used.
Definition at line 1058 of file qitemdelegate.cpp.
Referenced by drawDecoration().
 {
     QString key = qPixmapSerial(qt_pixmap_id(pixmap), enabled);
     QPixmap *pm = QPixmapCache::find(key);
     if (!pm) {
         QImage img = pixmap.toImage().convertToFormat(QImage::Format_ARGB32_Premultiplied);
         QColor color = palette.color(enabled ? QPalette::Normal : QPalette::Disabled,
                                      QPalette::Highlight);
         color.setAlphaF((qreal)0.3);
         QPainter painter(&img);
         painter.setCompositionMode(QPainter::CompositionMode_SourceAtop);
         painter.fillRect(0, 0, img.width(), img.height(), color);
         painter.end();
         QPixmap selected = QPixmap(QPixmap::fromImage(img));
         int n = (img.byteCount() >> 10) + 1;
         if (QPixmapCache::cacheLimit() < n)
             QPixmapCache::setCacheLimit(n);
         QPixmapCache::insert(key, selected);
         pm = QPixmapCache::find(key);
     }
     return pm;
 }
setClipping()
void QItemDelegate::setClipping (bool clip)
Definition at line 352 of file qitemdelegate.cpp.
 {
     Q_D(QItemDelegate);
     d->clipPainting = clip;
 }
setEditorData()
void QItemDelegate::setEditorData (QWidget * editor, const QModelIndex & index) const virtual
Sets the data to be displayed and edited by the editor from the data model item specified by the model index.
The default implementation stores the data in the editor widget's Qt's Property System.
See also
QMetaProperty::isUser()
Reimplemented from QAbstractItemDelegate.
Definition at line 552 of file qitemdelegate.cpp.
 {
 #ifdef QT_NO_PROPERTIES
     Q_UNUSED(editor);
     Q_UNUSED(index);
 #else
     Q_D(const QItemDelegate);
     QVariant v = index.data(Qt::EditRole);
     QByteArray n = editor->metaObject()->userProperty().name();
     // ### Qt 5: remove
     // A work-around for missing "USER true" in qdatetimeedit.h for
     // QTimeEdit's time property and QDateEdit's date property.
     // It only triggers if the default user property "dateTime" is
     // reported for QTimeEdit and QDateEdit.
     if (n == "dateTime") {
         if (editor->inherits("QTimeEdit"))
             n = "time";
         else if (editor->inherits("QDateEdit"))
             n = "date";
     }
     // ### Qt 5: give QComboBox a USER property
     if (n.isEmpty() && editor->inherits("QComboBox"))
         n = d->editorFactory()->valuePropertyName(static_cast<QVariant::Type>(v.userType()));
     if (!n.isEmpty()) {
         if (!v.isValid())
             v = QVariant(editor->property(n).userType(), (const void *)0);
         editor->setProperty(n, v);
     }
 #endif
 }
setItemEditorFactory()
void QItemDelegate::setItemEditorFactory (QItemEditorFactory * factory)
Sets the editor factory to be used by the item delegate to be the factory specified.
If no editor factory is set, the item delegate will use the default editor factory.
See also
itemEditorFactory()
Definition at line 658 of file qitemdelegate.cpp.
 {
     Q_D(QItemDelegate);
     d->f = factory;
 }
setModelData()
void QItemDelegate::setModelData (QWidget * editor, QAbstractItemModel * model, const QModelIndex & index) const virtual
Gets data from the editor widget and stores it in the specified model at the item index.
The default implementation gets the value to be stored in the data model from the editor widget's Qt's Property System.
See also
QMetaProperty::isUser()
Reimplemented from QAbstractItemDelegate.
Definition at line 595 of file qitemdelegate.cpp.
 {
 #ifdef QT_NO_PROPERTIES
     Q_UNUSED(model);
     Q_UNUSED(editor);
     Q_UNUSED(index);
 #else
     Q_D(const QItemDelegate);
     Q_ASSERT(model);
     Q_ASSERT(editor);
     QByteArray n = editor->metaObject()->userProperty().name();
     if (n.isEmpty())
         n = d->editorFactory()->valuePropertyName(
             static_cast<QVariant::Type>(model->data(index, Qt::EditRole).userType()));
     if (!n.isEmpty())
         model->setData(index, editor->property(n), Qt::EditRole);
 #endif
 }
setOptions()
QStyleOptionViewItem QItemDelegate::setOptions (const QModelIndex & index, const QStyleOptionViewItem & option) const protected
Warning
This function is not part of the public interface.
Definition at line 1328 of file qitemdelegate.cpp.
Referenced by paint().
 {
     QStyleOptionViewItem opt = option;
     // set font
     QVariant value = index.data(Qt::FontRole);
     if (value.isValid()){
         opt.font = qvariant_cast<QFont>(value).resolve(opt.font);
         opt.fontMetrics = QFontMetrics(opt.font);
     }
     // set text alignment
     value = index.data(Qt::TextAlignmentRole);
     if (value.isValid())
         opt.displayAlignment = Qt::Alignment(value.toInt());
     // set foreground brush
     value = index.data(Qt::ForegroundRole);
     if (value.canConvert<QBrush>())
         opt.palette.setBrush(QPalette::Text, qvariant_cast<QBrush>(value));
     return opt;
 }
sizeHint()
QSize QItemDelegate::sizeHint (const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Returns the size needed by the delegate to display the item specified by index, taking into account the style information provided by option.
When reimplementing this function, note that in case of text items, QItemDelegate adds a margin (i.e. 2 * QStyle::PM_FocusFrameHMargin) to the length of the text.
Implements QAbstractItemDelegate.
Reimplemented in QComboBoxDelegate.
Definition at line 505 of file qitemdelegate.cpp.
Referenced by QComboBoxDelegate::sizeHint().
 {
     QVariant value = index.data(Qt::SizeHintRole);
     if (value.isValid())
         return qvariant_cast<QSize>(value);
     QRect decorationRect = rect(option, index, Qt::DecorationRole);
     QRect displayRect = rect(option, index, Qt::DisplayRole);
     QRect checkRect = rect(option, index, Qt::CheckStateRole);
     doLayout(option, &checkRect, &decorationRect, &displayRect, true);
     return (decorationRect|displayRect|checkRect).size();
 }
textRectangle()
QRect QItemDelegate::textRectangle (QPainter * painter, const QRect & rect, const QFont & font, const QString & text) const protected
Warning
This function is not part of the public interface.
Definition at line 1159 of file qitemdelegate.cpp.
Referenced by paint(), rect(), and updateEditorGeometry().
 {
     Q_D(const QItemDelegate);
     d->textOption.setWrapMode(QTextOption::WordWrap);
     d->textLayout.setTextOption(d->textOption);
     d->textLayout.setFont(font);
     d->textLayout.setText(QItemDelegatePrivate::replaceNewLine(text));
     QSizeF fpSize = d->doTextLayout(rect.width());
     const QSize size = QSize(qCeil(fpSize.width()), qCeil(fpSize.height()));
     // ###: textRectangle should take style option as argument
     const int textMargin = QApplication::style()->pixelMetric(QStyle::PM_FocusFrameHMargin) + 1;
     return QRect(0, 0, size.width() + 2 * textMargin, size.height());
 }
updateEditorGeometry()
void QItemDelegate::updateEditorGeometry (QWidget * editor, const QStyleOptionViewItem & option, const QModelIndex & index) const virtual
Updates the editor for the item specified by index according to the style option given.
Reimplemented from QAbstractItemDelegate.
Definition at line 621 of file qitemdelegate.cpp.
 {
     if (!editor)
         return;
     Q_ASSERT(index.isValid());
     QPixmap pixmap = decoration(option, index.data(Qt::DecorationRole));
     QString text = QItemDelegatePrivate::replaceNewLine(index.data(Qt::DisplayRole).toString());
     QRect pixmapRect = QRect(QPoint(0, 0), option.decorationSize).intersected(pixmap.rect());
     QRect textRect = textRectangle(0, option.rect, option.font, text);
     QRect checkRect = check(option, textRect, index.data(Qt::CheckStateRole));
     QStyleOptionViewItem opt = option;
     opt.showDecorationSelected = true; // let the editor take up all available space
     doLayout(opt, &checkRect, &pixmapRect, &textRect, false);
     editor->setGeometry(textRect);
 }
Properties
clipping
QItemDelegate::clipping private
if the delegate should clip the paint events
Since
4.2
This property will set the paint clip to the size of the item. The default value is on. It is useful for cases such as when images are larger than the size of the item.
Definition at line 64 of file qitemdelegate.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qitemdelegate.h
/src/gui/itemviews/qitemdelegate.cpp