Qt 4.8: QDeclarativePixmap Class Reference
QDeclarativePixmap Class Reference
#include <qdeclarativepixmapcache_p.h>
Public Types
enum Option { Asynchronous = 0x00000001, Cache = 0x00000002 }
enum Status { Null, Ready, Error, Loading }
Public Functions
void clear ()
void clear (QObject *)
bool connectDownloadProgress (QObject *, const char *)
bool connectDownloadProgress (QObject *, int)
bool connectFinished (QObject *, const char *)
bool connectFinished (QObject *, int)
QString error () const
int height () const
const QSize & implicitSize () const
bool isError () const
bool isLoading () const
bool isNull () const
bool isReady () const
void load (QDeclarativeEngine *, const QUrl &)
void load (QDeclarativeEngine *, const QUrl &, QDeclarativePixmap::Options options)
void load (QDeclarativeEngine *, const QUrl &, const QSize &)
void load (QDeclarativeEngine *, const QUrl &, const QSize &, QDeclarativePixmap::Options options)
operator const QPixmap & () const
const QPixmap & pixmap () const
QDeclarativePixmap ()
QDeclarativePixmap (QDeclarativeEngine *, const QUrl &)
QDeclarativePixmap (QDeclarativeEngine *, const QUrl &, const QSize &)
QRect rect () const
const QSize & requestSize () const
void setPixmap (const QPixmap &)
Status status () const
const QUrl & url () const
int width () const
~QDeclarativePixmap ()
Static Public Functions
static void flushCache ()
Properties
QDeclarativePixmapData * d
Detailed Description
Definition at line 58 of file qdeclarativepixmapcache_p.h.
Enumerations
Option
enum QDeclarativePixmap::Option
Enumerator
Asynchronous
Cache
Definition at line 69 of file qdeclarativepixmapcache_p.h.
                 {
         Asynchronous = 0x00000001,
         Cache        = 0x00000002
     };
Status
enum QDeclarativePixmap::Status
Enumerator
Null
Ready
Error
Loading
Definition at line 67 of file qdeclarativepixmapcache_p.h.
 { Null, Ready, Error, Loading };
Constructors and Destructors
QDeclarativePixmap() [1/3]
QDeclarativePixmap::QDeclarativePixmap ()
Definition at line 869 of file qdeclarativepixmapcache.cpp.
 : d(0)
 {
 }
QDeclarativePixmap() [2/3]
QDeclarativePixmap::QDeclarativePixmap (QDeclarativeEngine * engine, const QUrl & url)
Definition at line 874 of file qdeclarativepixmapcache.cpp.
 : d(0)
 {
     load(engine, url);
 }
QDeclarativePixmap() [3/3]
QDeclarativePixmap::QDeclarativePixmap (QDeclarativeEngine * engine, const QUrl & url, const QSize & size)
Definition at line 880 of file qdeclarativepixmapcache.cpp.
 : d(0)
 {
     load(engine, url, size);
 }
~QDeclarativePixmap()
QDeclarativePixmap::~QDeclarativePixmap ()
Definition at line 886 of file qdeclarativepixmapcache.cpp.
Referenced by load().
 {
     if (d) {
         d->release();
         d = 0;
     }
 }
Functions
clear() [1/2]
void QDeclarativePixmap::clear ()
Definition at line 1054 of file qdeclarativepixmapcache.cpp.
Referenced by setPixmap().
 {
     if (d) {
         d->release();
         d = 0;
     }
 }
clear() [2/2]
void QDeclarativePixmap::clear (QObject * obj)
Definition at line 1062 of file qdeclarativepixmapcache.cpp.
 {
     if (d) {
         if (d->reply)
             QObject::disconnect(d->reply, 0, obj, 0);
         d->release();
         d = 0;
     }
 }
connectDownloadProgress() [1/2]
bool QDeclarativePixmap::connectDownloadProgress (QObject * object, const char * method)
Definition at line 1092 of file qdeclarativepixmapcache.cpp.
 {
     if (!d || !d->reply) {
         qWarning("QDeclarativePixmap: connectDownloadProgress() called when not loading.");
         return false;
     }
     return QObject::connect(d->reply, SIGNAL(downloadProgress(qint64,qint64)), object, method);
 }
connectDownloadProgress() [2/2]
bool QDeclarativePixmap::connectDownloadProgress (QObject * object, int method)
Definition at line 1102 of file qdeclarativepixmapcache.cpp.
 {
     if (!d || !d->reply) {
         qWarning("QDeclarativePixmap: connectDownloadProgress() called when not loading.");
         return false;
     }
     return QMetaObject::connect(d->reply, QDeclarativePixmapReply::downloadProgressIndex, object, method);
 }
connectFinished() [1/2]
bool QDeclarativePixmap::connectFinished (QObject * object, const char * method)
Definition at line 1072 of file qdeclarativepixmapcache.cpp.
Referenced by QTextDocumentWithImageResources::loadResource().
 {
     if (!d || !d->reply) {
         qWarning("QDeclarativePixmap: connectFinished() called when not loading.");
         return false;
     }
     return QObject::connect(d->reply, SIGNAL(finished()), object, method);
 }
connectFinished() [2/2]
bool QDeclarativePixmap::connectFinished (QObject * object, int method)
Definition at line 1082 of file qdeclarativepixmapcache.cpp.
 {
     if (!d || !d->reply) {
         qWarning("QDeclarativePixmap: connectFinished() called when not loading.");
         return false;
     }
     return QMetaObject::connect(d->reply, QDeclarativePixmapReply::finishedIndex, object, method);
 }
error()
QString QDeclarativePixmap::error () const
Definition at line 914 of file qdeclarativepixmapcache.cpp.
Referenced by QTextDocumentWithImageResources::loadResource().
 {
     if (d)
         return d->errorString;
     else
         return QString();
 }
flushCache()
void QDeclarativePixmap::flushCache () static
Definition at line 1112 of file qdeclarativepixmapcache.cpp.
 {
     pixmapStore()->flushCache();
 }
height()
int QDeclarativePixmap::height () const
Definition at line 978 of file qdeclarativepixmapcache.cpp.
 {
     if (d)
         return d->pixmap.height();
     else
         return 0;
 }
implicitSize()
const QSize & QDeclarativePixmap::implicitSize () const
Definition at line 938 of file qdeclarativepixmapcache.cpp.
 {
     if (d)
         return d->implicitSize;
     else
         return nullPixmap()->size;
 }
isError()
bool QDeclarativePixmap::isError () const
Definition at line 904 of file qdeclarativepixmapcache.cpp.
Referenced by QTextDocumentWithImageResources::loadResource().
 {
     return status() == Error;
 }
isLoading()
bool QDeclarativePixmap::isLoading () const
Definition at line 909 of file qdeclarativepixmapcache.cpp.
Referenced by QTextDocumentWithImageResources::loadResource().
 {
     return status() == Loading;
 }
isNull()
bool QDeclarativePixmap::isNull () const
Definition at line 894 of file qdeclarativepixmapcache.cpp.
 {
     return d == 0;
 }
isReady()
bool QDeclarativePixmap::isReady () const
Definition at line 899 of file qdeclarativepixmapcache.cpp.
Referenced by QTextDocumentWithImageResources::loadResource().
 {
     return status() == Ready;
 }
load() [1/4]
void QDeclarativePixmap::load (QDeclarativeEngine * engine, const QUrl & url)
Definition at line 994 of file qdeclarativepixmapcache.cpp.
Referenced by load(), and QDeclarativePixmap().
 {
     load(engine, url, QSize(), QDeclarativePixmap::Cache);
 }
load() [2/4]
void QDeclarativePixmap::load (QDeclarativeEngine * engine, const QUrl & url, QDeclarativePixmap::Options options)
Definition at line 999 of file qdeclarativepixmapcache.cpp.
 {
     load(engine, url, QSize(), options);
 }
load() [3/4]
void QDeclarativePixmap::load (QDeclarativeEngine * engine, const QUrl & url, const QSize & size)
Definition at line 1004 of file qdeclarativepixmapcache.cpp.
 {
     load(engine, url, size, QDeclarativePixmap::Cache);
 }
load() [4/4]
void QDeclarativePixmap::load (QDeclarativeEngine * engine, const QUrl & url, const QSize & requestSize, QDeclarativePixmap::Options options)
Definition at line 1009 of file qdeclarativepixmapcache.cpp.
 {
     if (d) { d->release(); d = 0; }
     QDeclarativePixmapKey key = { &url, &requestSize };
     QDeclarativePixmapStore *store = pixmapStore();
     QHash<QDeclarativePixmapKey, QDeclarativePixmapData *>::Iterator iter = store->m_cache.find(key);
     if (iter == store->m_cache.end()) {
         if (options & QDeclarativePixmap::Asynchronous) {
             // pixmaps can only be loaded synchronously
             if (url.scheme() == QLatin1String("image")
                     && QDeclarativeEnginePrivate::get(engine)->getImageProviderType(url) == QDeclarativeImageProvider::Pixmap) {
                 options &= ~QDeclarativePixmap::Asynchronous;
             }
         }
         if (!(options & QDeclarativePixmap::Asynchronous)) {
             bool ok = false;
             d = createPixmapDataSync(engine, url, requestSize, &ok);
             if (ok) {
                 if (options & QDeclarativePixmap::Cache)
                     d->addToCache();
                 return;
             }
             if (d)  // loadable, but encountered error while loading
                 return;
         }
         if (!engine)
             return;
         d = new QDeclarativePixmapData(url, requestSize);
         if (options & QDeclarativePixmap::Cache)
             d->addToCache();
         QDeclarativePixmapReader::readerMutex.lock();
         d->reply = QDeclarativePixmapReader::instance(engine)->getImage(d);
         QDeclarativePixmapReader::readerMutex.unlock();
     } else {
         d = *iter;
         d->addref();
     }
 }
operator const QPixmap &()
QDeclarativePixmap::operator const QPixmap & () const inline
Definition at line 113 of file qdeclarativepixmapcache_p.h.
 {
     return pixmap();
 }
pixmap()
const QPixmap & QDeclarativePixmap::pixmap () const
Definition at line 954 of file qdeclarativepixmapcache.cpp.
Referenced by QTextDocumentWithImageResources::loadResource().
 {
     if (d)
         return d->pixmap;
     else
         return nullPixmap()->pixmap;
 }
rect()
QRect QDeclarativePixmap::rect () const
Definition at line 986 of file qdeclarativepixmapcache.cpp.
 {
     if (d)
         return d->pixmap.rect();
     else
         return QRect();
 }
requestSize()
const QSize & QDeclarativePixmap::requestSize () const
Definition at line 946 of file qdeclarativepixmapcache.cpp.
 {
     if (d)
         return d->requestSize;
     else
         return nullPixmap()->size;
 }
setPixmap()
void QDeclarativePixmap::setPixmap (const QPixmap & p)
Definition at line 962 of file qdeclarativepixmapcache.cpp.
 {
     clear();
     if (!p.isNull())
         d = new QDeclarativePixmapData(p);
 }
status()
QDeclarativePixmap::Status QDeclarativePixmap::status () const
Definition at line 922 of file qdeclarativepixmapcache.cpp.
Referenced by isError(), isLoading(), and isReady().
 {
     if (d)
         return d->pixmapStatus;
     else
         return Null;
 }
url()
const QUrl & QDeclarativePixmap::url () const
Definition at line 930 of file qdeclarativepixmapcache.cpp.
Referenced by load().
 {
     if (d)
         return d->url;
     else
         return nullPixmap()->url;
 }
width()
int QDeclarativePixmap::width () const
Definition at line 970 of file qdeclarativepixmapcache.cpp.
 {
     if (d)
         return d->pixmap.width();
     else
         return 0;
 }
Properties
d
QDeclarativePixmapData* QDeclarativePixmap::d private
Definition at line 110 of file qdeclarativepixmapcache_p.h.
Referenced by clear(), connectDownloadProgress(), connectFinished(), error(), height(), implicitSize(), isNull(), load(), pixmap(), rect(), requestSize(), setPixmap(), status(), url(), width(), and ~QDeclarativePixmap().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativepixmapcache_p.h
/src/declarative/util/qdeclarativepixmapcache.cpp