Qt 4.8: QDeclarativeEasingValueType Class Reference
QDeclarativeEasingValueType Class Reference
#include <qdeclarativevaluetype_p.h>
Public Types
enum Type {
Linear = QEasingCurve::Linear, InQuad = QEasingCurve::InQuad, OutQuad = QEasingCurve::OutQuad, InOutQuad = QEasingCurve::InOutQuad,
OutInQuad = QEasingCurve::OutInQuad, InCubic = QEasingCurve::InCubic, OutCubic = QEasingCurve::OutCubic, InOutCubic = QEasingCurve::InOutCubic,
OutInCubic = QEasingCurve::OutInCubic, InQuart = QEasingCurve::InQuart, OutQuart = QEasingCurve::OutQuart, InOutQuart = QEasingCurve::InOutQuart,
OutInQuart = QEasingCurve::OutInQuart, InQuint = QEasingCurve::InQuint, OutQuint = QEasingCurve::OutQuint, InOutQuint = QEasingCurve::InOutQuint,
OutInQuint = QEasingCurve::OutInQuint, InSine = QEasingCurve::InSine, OutSine = QEasingCurve::OutSine, InOutSine = QEasingCurve::InOutSine,
OutInSine = QEasingCurve::OutInSine, InExpo = QEasingCurve::InExpo, OutExpo = QEasingCurve::OutExpo, InOutExpo = QEasingCurve::InOutExpo,
OutInExpo = QEasingCurve::OutInExpo, InCirc = QEasingCurve::InCirc, OutCirc = QEasingCurve::OutCirc, InOutCirc = QEasingCurve::InOutCirc,
OutInCirc = QEasingCurve::OutInCirc, InElastic = QEasingCurve::InElastic, OutElastic = QEasingCurve::OutElastic, InOutElastic = QEasingCurve::InOutElastic,
OutInElastic = QEasingCurve::OutInElastic, InBack = QEasingCurve::InBack, OutBack = QEasingCurve::OutBack, InOutBack = QEasingCurve::InOutBack,
OutInBack = QEasingCurve::OutInBack, InBounce = QEasingCurve::InBounce, OutBounce = QEasingCurve::OutBounce, InOutBounce = QEasingCurve::InOutBounce,
OutInBounce = QEasingCurve::OutInBounce, InCurve = QEasingCurve::InCurve, OutCurve = QEasingCurve::OutCurve, SineCurve = QEasingCurve::SineCurve,
CosineCurve = QEasingCurve::CosineCurve
}
Public Functions
qreal amplitude () const
qreal overshoot () const
qreal period () const
QDeclarativeEasingValueType (QObject *parent=0)
virtual void read (QObject *, int)
void setAmplitude (qreal)
void setOvershoot (qreal)
void setPeriod (qreal)
void setType (Type)
virtual void setValue (QVariant value)
Type type () const
virtual QVariant value ()
virtual void write (QObject *, int, QDeclarativePropertyPrivate::WriteFlags)
Public Functions inherited from QDeclarativeValueType
QDeclarativeValueType (QObject *parent=0)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
qreal amplitude
QEasingCurve easing
qreal overshoot
qreal period
QDeclarativeEasingValueType::Type type
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 418 of file qdeclarativevaluetype_p.h.
Enumerations
Type
enum QDeclarativeEasingValueType::Type
Enumerator
Linear
InQuad
OutQuad
InOutQuad
OutInQuad
InCubic
OutCubic
InOutCubic
OutInCubic
InQuart
OutQuart
InOutQuart
OutInQuart
InQuint
OutQuint
InOutQuint
OutInQuint
InSine
OutSine
InOutSine
OutInSine
InExpo
OutExpo
InOutExpo
OutInExpo
InCirc
OutCirc
InOutCirc
OutInCirc
InElastic
OutElastic
InOutElastic
OutInElastic
InBack
OutBack
InOutBack
OutInBack
InBounce
OutBounce
InOutBounce
OutInBounce
InCurve
OutCurve
SineCurve
CosineCurve
Definition at line 428 of file qdeclarativevaluetype_p.h.
               {
         Linear = QEasingCurve::Linear,
         InQuad = QEasingCurve::InQuad, OutQuad = QEasingCurve::OutQuad,
         InOutQuad = QEasingCurve::InOutQuad, OutInQuad = QEasingCurve::OutInQuad,
         InCubic = QEasingCurve::InCubic, OutCubic = QEasingCurve::OutCubic,
         InOutCubic = QEasingCurve::InOutCubic, OutInCubic = QEasingCurve::OutInCubic,
         InQuart = QEasingCurve::InQuart, OutQuart = QEasingCurve::OutQuart,
         InOutQuart = QEasingCurve::InOutQuart, OutInQuart = QEasingCurve::OutInQuart,
         InQuint = QEasingCurve::InQuint, OutQuint = QEasingCurve::OutQuint,
         InOutQuint = QEasingCurve::InOutQuint, OutInQuint = QEasingCurve::OutInQuint,
         InSine = QEasingCurve::InSine, OutSine = QEasingCurve::OutSine,
         InOutSine = QEasingCurve::InOutSine, OutInSine = QEasingCurve::OutInSine,
         InExpo = QEasingCurve::InExpo, OutExpo = QEasingCurve::OutExpo,
         InOutExpo = QEasingCurve::InOutExpo, OutInExpo = QEasingCurve::OutInExpo,
         InCirc = QEasingCurve::InCirc, OutCirc = QEasingCurve::OutCirc,
         InOutCirc = QEasingCurve::InOutCirc, OutInCirc = QEasingCurve::OutInCirc,
         InElastic = QEasingCurve::InElastic, OutElastic = QEasingCurve::OutElastic,
         InOutElastic = QEasingCurve::InOutElastic, OutInElastic = QEasingCurve::OutInElastic,
         InBack = QEasingCurve::InBack, OutBack = QEasingCurve::OutBack,
         InOutBack = QEasingCurve::InOutBack, OutInBack = QEasingCurve::OutInBack,
         InBounce = QEasingCurve::InBounce, OutBounce = QEasingCurve::OutBounce,
         InOutBounce = QEasingCurve::InOutBounce, OutInBounce = QEasingCurve::OutInBounce,
         InCurve = QEasingCurve::InCurve, OutCurve = QEasingCurve::OutCurve,
         SineCurve = QEasingCurve::SineCurve, CosineCurve = QEasingCurve::CosineCurve
     };
Constructors and Destructors
QDeclarativeEasingValueType()
QDeclarativeEasingValueType::QDeclarativeEasingValueType (QObject * parent = 0)
Definition at line 771 of file qdeclarativevaluetype.cpp.
 : QDeclarativeValueType(parent)
 {
 }
Functions
amplitude()
qreal QDeclarativeEasingValueType::amplitude () const
Referenced by setValue().
overshoot()
qreal QDeclarativeEasingValueType::overshoot () const
Referenced by setValue().
period()
qreal QDeclarativeEasingValueType::period () const
Referenced by setValue().
read()
void QDeclarativeEasingValueType::read (QObject * obj, int idx) virtual
Implements QDeclarativeValueType.
Definition at line 776 of file qdeclarativevaluetype.cpp.
 {
     void *a[] = { &easing, 0 };
     QMetaObject::metacall(obj, QMetaObject::ReadProperty, idx, a);
 }
setAmplitude()
void QDeclarativeEasingValueType::setAmplitude (qreal amplitude)
Definition at line 824 of file qdeclarativevaluetype.cpp.
 {
     easing.setAmplitude(amplitude);
 }
setOvershoot()
void QDeclarativeEasingValueType::setOvershoot (qreal overshoot)
Definition at line 829 of file qdeclarativevaluetype.cpp.
 {
     easing.setOvershoot(overshoot);
 }
setPeriod()
void QDeclarativeEasingValueType::setPeriod (qreal period)
Definition at line 834 of file qdeclarativevaluetype.cpp.
 {
     easing.setPeriod(period);
 }
setType()
void QDeclarativeEasingValueType::setType (QDeclarativeEasingValueType::Type type)
Definition at line 819 of file qdeclarativevaluetype.cpp.
 {
     easing.setType((QEasingCurve::Type)type);
 }
setValue()
void QDeclarativeEasingValueType::setValue (QVariant value) virtual
Implements QDeclarativeValueType.
Definition at line 794 of file qdeclarativevaluetype.cpp.
 {
     easing = qvariant_cast<QEasingCurve>(value);
 }
type()
Type QDeclarativeEasingValueType::type () const
Referenced by setValue().
value()
QVariant QDeclarativeEasingValueType::value () virtual
Implements QDeclarativeValueType.
Definition at line 789 of file qdeclarativevaluetype.cpp.
Referenced by setValue().
 {
     return QVariant(easing);
 }
write()
void QDeclarativeEasingValueType::write (QObject * obj, int idx, QDeclarativePropertyPrivate::WriteFlags flags) virtual
Implements QDeclarativeValueType.
Definition at line 782 of file qdeclarativevaluetype.cpp.
 {
     int status = -1;
     void *a[] = { &easing, 0, &status, &flags };
     QMetaObject::metacall(obj, QMetaObject::WriteProperty, idx, a);
 }
Properties
amplitude
qreal QDeclarativeEasingValueType::amplitude private
Definition at line 424 of file qdeclarativevaluetype_p.h.
easing
QEasingCurve QDeclarativeEasingValueType::easing private
Definition at line 471 of file qdeclarativevaluetype_p.h.
Referenced by read(), setAmplitude(), setOvershoot(), setPeriod(), setType(), setValue(), value(), and write().
overshoot
qreal QDeclarativeEasingValueType::overshoot private
Definition at line 425 of file qdeclarativevaluetype_p.h.
period
qreal QDeclarativeEasingValueType::period private
Definition at line 426 of file qdeclarativevaluetype_p.h.
type
QDeclarativeEasingValueType::Type QDeclarativeEasingValueType::type private
Definition at line 423 of file qdeclarativevaluetype_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativevaluetype_p.h
/src/declarative/qml/qdeclarativevaluetype.cpp