Qt 4.8: QDeclarativeScriptString Class Reference
QDeclarativeScriptString Class Reference
The QDeclarativeScriptString class encapsulates a script and its context.
#include <qdeclarativescriptstring.h>
Public Functions
QDeclarativeContext * context () const
Returns the context for the script.
QDeclarativeScriptString & operator= (const QDeclarativeScriptString &)
Assigns other to this.
QDeclarativeScriptString ()
Constructs an empty instance.
QDeclarativeScriptString (const QDeclarativeScriptString &)
Copies other.
QObject * scopeObject () const
Returns the scope object for the script.
QString script () const
Returns the script text.
void setContext (QDeclarativeContext *)
Sets the context for the script.
void setScopeObject (QObject *)
Sets the scope object for the script.
void setScript (const QString &)
Sets the script text.
~QDeclarativeScriptString ()
Properties
QSharedDataPointer< QDeclarativeScriptStringPrivate > d
Detailed Description
The QDeclarativeScriptString class encapsulates a script and its context.
Since
4.7
QDeclarativeScriptString is used to create QObject properties that accept a script "assignment" from QML.
Normally, the following QML would result in a binding being established for the script property; i.e. script would be assigned the value obtained from running {myObj.value = Math.max(myValue, 100)}
MyType {
    script: myObj.value = Math.max(myValue, 100)
}
If instead the property had a type of QDeclarativeScriptString, the script itself – {myObj.value = Math.max(myValue, 100)} – would be passed to the script property and the class could choose how to handle it. Typically, the class will evaluate the script at some later time using a QDeclarativeExpression.
QDeclarativeExpression expr(scriptString.context(), scriptString.script(), scriptStr.scopeObject());
expr.value();
See also
QDeclarativeExpression
Definition at line 58 of file qdeclarativescriptstring.h.
Constructors and Destructors
QDeclarativeScriptString() [1/2]
QDeclarativeScriptString::QDeclarativeScriptString ()
Constructs an empty instance.
Definition at line 91 of file qdeclarativescriptstring.cpp.
 :  d(new QDeclarativeScriptStringPrivate)
 {
 }
QDeclarativeScriptString() [2/2]
QDeclarativeScriptString::QDeclarativeScriptString (const QDeclarativeScriptString & other)
Copies other.
Definition at line 99 of file qdeclarativescriptstring.cpp.
 : d(other.d)
 {
 }
~QDeclarativeScriptString()
QDeclarativeScriptString::~QDeclarativeScriptString ()
Warning
This function is not part of the public interface.
Definition at line 107 of file qdeclarativescriptstring.cpp.
 {
 }
Functions
context()
QDeclarativeContext * QDeclarativeScriptString::context () const
Returns the context for the script.
Definition at line 123 of file qdeclarativescriptstring.cpp.
Referenced by QDeclarativeScriptActionPrivate::execute(), and setContext().
 {
     return d->context;
 }
operator=()
QDeclarativeScriptString & QDeclarativeScriptString::operator= (const QDeclarativeScriptString & other)
Assigns other to this.
Definition at line 114 of file qdeclarativescriptstring.cpp.
 {
     d = other.d;
     return *this;
 }
scopeObject()
QObject * QDeclarativeScriptString::scopeObject () const
Returns the scope object for the script.
Definition at line 139 of file qdeclarativescriptstring.cpp.
Referenced by QDeclarativeScriptActionPrivate::execute().
 {
     return d->scope;
 }
script()
QString QDeclarativeScriptString::script () const
Returns the script text.
Definition at line 155 of file qdeclarativescriptstring.cpp.
Referenced by QDeclarativeScriptActionPrivate::execute(), QDeclarativeAnchorSet::setBaseline(), QDeclarativeAnchorSet::setBottom(), QDeclarativeParentChange::setHeight(), QDeclarativeAnchorSet::setHorizontalCenter(), QDeclarativeAnchorSet::setLeft(), QDeclarativeAnchorSet::setRight(), QDeclarativeParentChange::setRotation(), QDeclarativeParentChange::setScale(), setScript(), QDeclarativeAnchorSet::setTop(), QDeclarativeAnchorSet::setVerticalCenter(), QDeclarativeParentChange::setWidth(), QDeclarativeParentChange::setX(), and QDeclarativeParentChange::setY().
 {
     return d->script;
 }
setContext()
void QDeclarativeScriptString::setContext (QDeclarativeContext * context)
Sets the context for the script.
Definition at line 131 of file qdeclarativescriptstring.cpp.
 {
     d->context = context;
 }
setScopeObject()
void QDeclarativeScriptString::setScopeObject (QObject * object)
Sets the scope object for the script.
Definition at line 147 of file qdeclarativescriptstring.cpp.
 {
     d->scope = object;
 }
setScript()
void QDeclarativeScriptString::setScript (const QString & script)
Sets the script text.
Definition at line 163 of file qdeclarativescriptstring.cpp.
 {
     d->script = script;
 }
Properties
d
QSharedDataPointer<QDeclarativeScriptStringPrivate> QDeclarativeScriptString::d private
Definition at line 77 of file qdeclarativescriptstring.h.
Referenced by context(), operator=(), scopeObject(), script(), setContext(), setScopeObject(), and setScript().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativescriptstring.h
/src/declarative/qml/qdeclarativescriptstring.cpp