Qt 4.8: RegistryKey Class Reference
RegistryKey Class Reference
Public Functions
void close ()
HKEY handle () const
QString key () const
HKEY parentHandle () const
bool readOnly () const
RegistryKey (HKEY parent_handle=0, const QString &key=QString(), bool read_only=true)
Properties
HKEY m_handle
QString m_key
HKEY m_parent_handle
bool m_read_only
Detailed Description
Definition at line 313 of file qsettings_win.cpp.
Constructors and Destructors
RegistryKey()
RegistryKey::RegistryKey (HKEY parent_handle = 0, const QString & key = QString(), bool read_only = true)
Definition at line 329 of file qsettings_win.cpp.
 {
     m_parent_handle = parent_handle;
     m_handle = 0;
     m_read_only = read_only;
     m_key = key;
 }
Functions
close()
void RegistryKey::close ()
Definition at line 365 of file qsettings_win.cpp.
 {
     if (m_handle != 0)
         RegCloseKey(m_handle);
     m_handle = 0;
 }
handle()
HKEY RegistryKey::handle () const
Definition at line 342 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::children(), QWinSettingsPrivate::get(), and QWinSettingsPrivate::writeHandle().
 {
     if (m_handle != 0)
         return m_handle;
     if (m_read_only)
         m_handle = openKey(m_parent_handle, KEY_READ, m_key);
     else
         m_handle = createOrOpenKey(m_parent_handle, m_key, &m_read_only);
     return m_handle;
 }
key()
QString RegistryKey::key () const
Definition at line 337 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::fileName(), RegistryKey(), and QWinSettingsPrivate::~QWinSettingsPrivate().
 {
     return m_key;
 }
parentHandle()
HKEY RegistryKey::parentHandle () const
Definition at line 355 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::fileName().
 {
     return m_parent_handle;
 }
readOnly()
bool RegistryKey::readOnly () const
Definition at line 360 of file qsettings_win.cpp.
Referenced by QWinSettingsPrivate::writeHandle().
 {
     return m_read_only;
 }
Properties
m_handle
HKEY RegistryKey::m_handle mutable private
Definition at line 324 of file qsettings_win.cpp.
Referenced by close(), handle(), and RegistryKey().
m_key
QString RegistryKey::m_key private
Definition at line 325 of file qsettings_win.cpp.
Referenced by handle(), key(), and RegistryKey().
m_parent_handle
HKEY RegistryKey::m_parent_handle private
Definition at line 323 of file qsettings_win.cpp.
Referenced by handle(), parentHandle(), and RegistryKey().
m_read_only
bool RegistryKey::m_read_only mutable private
Definition at line 326 of file qsettings_win.cpp.
Referenced by handle(), readOnly(), and RegistryKey().
The documentation for this class was generated from the following file:
/src/corelib/io/qsettings_win.cpp