Qt 4.8: QVFbScreen Class Reference
QVFbScreen Class Reference
The QVFbScreen class implements a screen driver for the virtual framebuffer.
#include <qscreenvfb_qws.h>
Public Functions
virtual void blank (bool)
Prevents the screen driver form displaying any content on the screen.
virtual bool connect (const QString &displaySpec)
Reimplemented Function
int depth () const
Reimplement in subclass to return current depth of the screen.
virtual void disconnect ()
Reimplemented Function
QImage::Format format () const
Reimplement in subclass to return the image format which corresponds to the screen format.
QRect geometry () const
Reimplement in subclass to return the pixel geometry of the screen.
virtual bool initDevice ()
Reimplemented Function
QSize physicalSize () const
Reimplement this function in subclass to return the physical size of the screen.
QVFbScreen (int id)
QVFbScreen (int display_id)
Constructs a QVNCScreen object.
virtual void restore ()
Reimplemented Function
virtual void save ()
Reimplemented Function
QImage * screenImage ()
void setDirty (const QRect &rect)
Marks the given rectangle as dirty.
virtual void setDirty (const QRect &r)
Reimplemented Function
virtual void setMode (int nw, int nh, int nd)
Reimplemented Function
virtual void shutdownDevice ()
Reimplemented Function
~QVFbScreen ()
virtual ~QVFbScreen ()
Destroys this QVFbScreen object.
Public Functions inherited from QPlatformScreen
virtual QRect availableGeometry () const
Reimplement in subclass to return the pixel geometry of the available space This normally is the desktop screen minus the task manager, global menubar etc.
virtual QWidget * topLevelAt (const QPoint &point) const
Return the given top level widget for a given position.
virtual ~QPlatformScreen ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QScreen
virtual int alloc (unsigned int, unsigned int, unsigned int)
Returns the index in the screen's palette which is the closest match to the given RGB value (red, green, blue).
uchar * base () const
Returns a pointer to the beginning of the framebuffer.
virtual void blit (const QImage &img, const QPoint &topLeft, const QRegion &region)
Copies the given region in the given image to the point specified by topLeft using device coordinates.
void blit (QWSWindow *bs, const QRegion &clip)
virtual uchar * cache (int)
ClassId classId () const
Returns the class identifier for the screen object.
QRgb * clut ()
Returns a pointer to the screen's color lookup table (i.
int colorCount ()
Returns the number of entries in the screen's color lookup table (i.
virtual QWSWindowSurface * createSurface (QWidget *widget) const
Creates and returns a new window surface for the given widget.
virtual QWSWindowSurface * createSurface (const QString &key) const
Creates and returns a new window surface matching the given key.
int depth () const
Returns the depth of the framebuffer, in bits per pixel.
int deviceHeight () const
Returns the full height of the framebuffer device in pixels.
int deviceWidth () const
Returns the physical width of the framebuffer device in pixels.
virtual void exposeRegion (QRegion r, int changing)
This function is called by the Qt for Embedded Linux server whenever a screen update is required.
QGraphicsSystem * graphicsSystem () const
virtual void haltUpdates ()
int height () const
Returns the logical height of the framebuffer in pixels.
virtual bool isInterlaced () const
Returns true if the display is interlaced (i.
virtual bool isTransformed () const
Returns true if the screen is transformed (for instance, rotated 90 degrees); otherwise returns false.
int linestep () const
Returns the length of each scanline of the framebuffer in bytes.
virtual QSize mapFromDevice (const QSize &) const
Maps the given size from the framebuffer coordinate system to the coordinate space used by the application.
virtual QPoint mapFromDevice (const QPoint &, const QSize &) const
Maps the given point from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QRect mapFromDevice (const QRect &, const QSize &) const
Maps the given rectangle from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QImage mapFromDevice (const QImage &) const
Maps the given image from the framebuffer coordinate system to the coordinate space used by the application.
virtual QRegion mapFromDevice (const QRegion &, const QSize &) const
Maps the given region from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QSize mapToDevice (const QSize &) const
Maps the given size from the coordinate space used by the application to the framebuffer coordinate system.
virtual QPoint mapToDevice (const QPoint &, const QSize &) const
Maps the given point from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual QRect mapToDevice (const QRect &, const QSize &) const
Maps the given rectangle from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual QImage mapToDevice (const QImage &) const
Maps the given image from the coordinate space used by the application to the framebuffer coordinate system.
virtual QRegion mapToDevice (const QRegion &, const QSize &) const
Maps the given region from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual int memoryNeeded (const QString &)
QT_DEPRECATED int numCols ()
QPoint offset () const
Returns the logical offset of the screen, i.
virtual bool onCard (const unsigned char *) const
Returns true if the specified buffer is within the graphics card's memory; otherwise returns false (i.e.
virtual bool onCard (const unsigned char *, ulong &out_offset) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.If the specified buffer is within the graphics card's memory, this function stores the offset from the start of graphics card memory (in bytes), in the location specified by the offset parameter.
int physicalHeight () const
Returns the physical height of the screen in millimeters.
int physicalWidth () const
Returns the physical width of the screen in millimeters.
QImage::Format pixelFormat () const
Returns the pixel format of the screen, or QImage::Format_Invalid if the pixel format is not a supported image format.
PixelType pixelType () const
Returns the pixel storage format of the screen.
QPixmapDataFactory * pixmapDataFactory () const
virtual int pixmapDepth () const
Returns the preferred depth for pixmaps, in bits per pixel.
virtual int pixmapLinestepAlignment ()
Returns the value (in bits) to which individual scanlines of pixmaps held in the graphics card's memory, should be aligned.
virtual int pixmapOffsetAlignment ()
Returns the value (in bits) to which the start address of pixmaps held in the graphics card's memory, should be aligned.
QScreen (int display_id, ClassId classId)
Constructs a new screen driver.
QScreen (int display_id)
Constructs a new screen driver.
virtual QRegion region () const
Returns the region covered by this screen driver.
virtual void resumeUpdates ()
int screenSize () const
Returns the size of the screen in bytes.
virtual void set (unsigned int, unsigned int, unsigned int, unsigned int)
void setOffset (const QPoint &p)
virtual int sharedRamSize (void *)
virtual void solidFill (const QColor &color, const QRegion &region)
Fills the given region of the screen with the specified color.
int subScreenIndexAt (const QPoint &p) const
Returns the index of the subscreen at the given position; returns -1 if no screen is found.
virtual QList< QScreen * > subScreens () const
virtual bool supportsDepth (int) const
Returns true if the screen supports the specified color depth; otherwise returns false.
int totalSize () const
Returns the size of the available graphics card memory (including the screen) in bytes.
virtual int transformOrientation () const
Returns the current rotation as an integer value.
virtual void uncache (uchar *)
int width () const
Returns the logical width of the framebuffer in pixels.
virtual ~QScreen ()
Destroys this screen driver.
Properties
QVFbScreenPrivate * d_ptr
Additional Inherited Members
Public Types inherited from QScreen
enum ClassId {
LinuxFBClass, TransformedClass, VNCClass, MultiClass,
VFbClass, DirectFBClass, SvgalibClass, ProxyClass,
GLClass, IntfbClass, CustomClass = 1024
}
This enum defines the class identifiers for the known screen subclasses.
enum PixelType { NormalPixel, BGRPixel }
This enum describes the pixel storage format of the screen, i.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QPlatformScreen
static QPlatformScreen * platformScreenForWidget (const QWidget *widget)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QScreen
static QScreen * instance ()
Returns a pointer to the application's QScreen instance.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QScreen
void setGraphicsSystem (QGraphicsSystem *system)
void setPixelFormat (QImage::Format format)
Sets the screen's pixel format to format.
void setPixmapDataFactory (QPixmapDataFactory *factory)
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QScreen
int d
the pixel depth
uchar * data
points to the first visible pixel in the frame buffer.
int dh
the device height
int displayId
int dw
the device width
QPoolEntry * entries
int * entryp
bool grayscale
the gray scale screen mode flag
int h
the logical height of the screen.
unsigned int * lowest
int lstep
the number of bytes representing a line in the frame buffer.
int mapsize
the total number of bytes in the frame buffer
int physHeight
the physical height of the screen in millimeters.
int physWidth
the physical width of the screen in millimeters.
PixelType pixeltype
set to BGRPixel
QRgb screenclut [256]
the color table
int screencols
the number of entries in the color table
int size
the number of bytes in the visible region of the frame buffer
int w
the logical width of the screen.
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Static Protected Variables inherited from QScreen
static ClearCacheFunc clearCacheFunc = 0
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QScreen
void setTransformation (int transformation, int screenNo)
Here it is.
Detailed Description
The QVFbScreen class implements a screen driver for the virtual framebuffer.
Warning
This function is not part of the public interface.
Note that this class is only available in Qt for Embedded Linux. Custom screen drivers can be added by subclassing the QScreenDriverPlugin class, using the QScreenDriverFactory class to dynamically load the driver into the application, but there should only be one screen object per application.
The Qt for Embedded Linux platform provides a The Virtual Framebuffer{virtual framebuffer} for development and debugging; the virtual framebuffer allows Qt for Embedded Linux applications to be developed on a desktop machine, without switching between consoles and X11.
See also
QScreen, QScreenDriverPlugin, {Running Applications}
Definition at line 58 of file qscreenvfb_qws.h.
Constructors and Destructors
QVFbScreen() [1/2]
QVFbScreen::QVFbScreen (int displayId) explicit
Constructs a QVNCScreen object.
The displayId argument identifies the Qt for Embedded Linux server to connect to.
Definition at line 181 of file qscreenvfb_qws.cpp.
Referenced by QVFbScreenPrivate::disconnect().
     : QScreen(display_id, VFbClass), d_ptr(new QVFbScreenPrivate)
 {
     d_ptr->shmrgn = 0;
     d_ptr->hdr = 0;
     data = 0;
 }
~QVFbScreen() [1/2]
QVFbScreen::~QVFbScreen () virtual
Destroys this QVFbScreen object.
Definition at line 192 of file qscreenvfb_qws.cpp.
Referenced by QVFbScreenPrivate::disconnect().
 {
     delete d_ptr;
 }
QVFbScreen() [2/2]
QVFbScreen::QVFbScreen (int id)
~QVFbScreen() [2/2]
QVFbScreen::~QVFbScreen ()
Functions
blank()
void QVFbScreen::blank (bool on) virtual
Prevents the screen driver form displaying any content on the screen.
Note that the default implementation does nothing.
Reimplement this function to prevent the screen driver from displaying any contents on the screen if on is true; otherwise the contents is expected to be shown.
See also
blit()
Reimplemented from QScreen.
Definition at line 443 of file qscreenvfb_qws.cpp.
 {
     d_ptr->blank = on;
     setBrightness(connected->d_ptr->brightness);
 }
connect()
bool QVFbScreen::connect (const QString & displaySpec) virtual
Reimplemented Function
Implements QScreen.
Definition at line 199 of file qscreenvfb_qws.cpp.
 {
     QStringList displayArgs = displaySpec.split(QLatin1Char(':'));
     if (displayArgs.contains(QLatin1String("Gray")))
         grayscale = true;
     key_t key = ftok(QT_VFB_MOUSE_PIPE(displayId).toLocal8Bit(), 'b');
     if (key == -1)
         return false;
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
 #ifndef QT_QWS_FRAMEBUFFER_LITTLE_ENDIAN
     if (displayArgs.contains(QLatin1String("littleendian")))
 #endif
         QScreen::setFrameBufferLittleEndian(true);
 #endif
     int shmId = shmget(key, 0, 0);
     if (shmId != -1)
         d_ptr->shmrgn = (unsigned char *)shmat(shmId, 0, 0);
     else
         return false;
     if ((long)d_ptr->shmrgn == -1 || d_ptr->shmrgn == 0) {
         qDebug("No shmrgn %ld", (long)d_ptr->shmrgn);
         return false;
     }
     d_ptr->hdr = (QVFbHeader *)d_ptr->shmrgn;
     data = d_ptr->shmrgn + d_ptr->hdr->dataoffset;
     dw = w = d_ptr->hdr->width;
     dh = h = d_ptr->hdr->height;
     d = d_ptr->hdr->depth;
     switch (d) {
     case 1:
         setPixelFormat(QImage::Format_Mono);
         break;
     case 8:
         setPixelFormat(QImage::Format_Indexed8);
         break;
     case 12:
         setPixelFormat(QImage::Format_RGB444);
         break;
     case 15:
         setPixelFormat(QImage::Format_RGB555);
         break;
     case 16:
         setPixelFormat(QImage::Format_RGB16);
         break;
     case 18:
         setPixelFormat(QImage::Format_RGB666);
         break;
     case 24:
         setPixelFormat(QImage::Format_RGB888);
         break;
     case 32:
         setPixelFormat(QImage::Format_ARGB32_Premultiplied);
         break;
     }
     lstep = d_ptr->hdr->linestep;
     // Handle display physical size spec.
     int dimIdxW = -1;
     int dimIdxH = -1;
     for (int i = 0; i < displayArgs.size(); ++i) {
         if (displayArgs.at(i).startsWith(QLatin1String("mmWidth"))) {
             dimIdxW = i;
             break;
         }
     }
     for (int i = 0; i < displayArgs.size(); ++i) {
         if (displayArgs.at(i).startsWith(QLatin1String("mmHeight"))) {
             dimIdxH = i;
             break;
         }
     }
     if (dimIdxW >= 0) {
         bool ok;
         int pos = 7;
         if (displayArgs.at(dimIdxW).at(pos) == QLatin1Char('='))
             ++pos;
         int pw = displayArgs.at(dimIdxW).mid(pos).toInt(&ok);
         if (ok) {
             physWidth = pw;
             if (dimIdxH < 0)
                 physHeight = dh*physWidth/dw;
         }
     }
     if (dimIdxH >= 0) {
         bool ok;
         int pos = 8;
         if (displayArgs.at(dimIdxH).at(pos) == QLatin1Char('='))
             ++pos;
         int ph = displayArgs.at(dimIdxH).mid(pos).toInt(&ok);
         if (ok) {
             physHeight = ph;
             if (dimIdxW < 0)
                 physWidth = dw*physHeight/dh;
         }
     }
     if (dimIdxW < 0 && dimIdxH < 0) {
         const int dpi = 72;
         physWidth = qRound(dw * 25.4 / dpi);
         physHeight = qRound(dh * 25.4 / dpi);
     }
     qDebug("Connected to VFB server %s: %d x %d x %d %dx%dmm (%dx%ddpi)", displaySpec.toLatin1().data(),
         w, h, d, physWidth, physHeight, qRound(dw*25.4/physWidth), qRound(dh*25.4/physHeight) );
     size = lstep * h;
     mapsize = size;
     screencols = d_ptr->hdr->numcols;
     memcpy(screenclut, d_ptr->hdr->clut, sizeof(QRgb) * screencols);
     connected = this;
     if (qgetenv("QT_QVFB_BGR").toInt())
         pixeltype = BGRPixel;
     return true;
 }
depth()
int QVFbScreen::depth () const virtual
Reimplement in subclass to return current depth of the screen.
Implements QPlatformScreen.
Definition at line 384 of file qvfbintegration.cpp.
 {
     return d_ptr->depth();
 }
disconnect()
void QVFbScreen::disconnect () virtual
Reimplemented Function
Implements QScreen.
Definition at line 325 of file qscreenvfb_qws.cpp.
 {
     connected = 0;
     if ((long)d_ptr->shmrgn != -1 && d_ptr->shmrgn) {
         if (qApp->type() == QApplication::GuiServer && d_ptr->hdr->dataoffset >= (int)sizeof(QVFbHeader)) {
             d_ptr->hdr->serverVersion = 0;
         }
         shmdt((char*)d_ptr->shmrgn);
     }
 }
format()
QImage::Format QVFbScreen::format () const virtual
Reimplement in subclass to return the image format which corresponds to the screen format.
Implements QPlatformScreen.
Definition at line 389 of file qvfbintegration.cpp.
 {
     return d_ptr->format();
 }
geometry()
QRect QVFbScreen::geometry () const virtual
Reimplement in subclass to return the pixel geometry of the screen.
Implements QPlatformScreen.
Definition at line 379 of file qvfbintegration.cpp.
{
     return QRect(QPoint(), d_ptr->screenSize());
 }
initDevice()
bool QVFbScreen::initDevice () virtual
Reimplemented Function
Implements QScreen.
Definition at line 336 of file qscreenvfb_qws.cpp.
 {
 #ifndef QT_NO_QWS_MOUSE_QVFB
     const QString mouseDev = QT_VFB_MOUSE_PIPE(displayId);
     d_ptr->mouse = new QVFbMouseHandler(QLatin1String("QVFbMouse"), mouseDev);
     qwsServer->setDefaultMouse("None");
     if (d_ptr->mouse)
         d_ptr->mouse->setScreen(this);
 #endif
 #if !defined(QT_NO_QWS_KBD_QVFB) && !defined(QT_NO_QWS_KEYBOARD)
     const QString keyboardDev = QT_VFB_KEYBOARD_PIPE(displayId);
     d_ptr->keyboard = new QVFbKeyboardHandler(keyboardDev);
     qwsServer->setDefaultKeyboard("None");
 #endif
     if (d_ptr->hdr->dataoffset >= (int)sizeof(QVFbHeader))
         d_ptr->hdr->serverVersion = QT_VERSION;
     if(d==8) {
         screencols=256;
         if (grayscale) {
             // Build grayscale palette
             for(int loopc=0;loopc<256;loopc++) {
                 screenclut[loopc]=qRgb(loopc,loopc,loopc);
             }
         } else {
             // 6x6x6 216 color cube
             int idx = 0;
             for(int ir = 0x0; ir <= 0xff; ir+=0x33) {
                 for(int ig = 0x0; ig <= 0xff; ig+=0x33) {
                     for(int ib = 0x0; ib <= 0xff; ib+=0x33) {
                         screenclut[idx]=qRgb(ir, ig, ib);
                         idx++;
                     }
                 }
             }
             screencols=idx;
         }
         memcpy(d_ptr->hdr->clut, screenclut, sizeof(QRgb) * screencols);
         d_ptr->hdr->numcols = screencols;
     } else if (d == 4) {
         int val = 0;
         for (int idx = 0; idx < 16; idx++, val += 17) {
             screenclut[idx] = qRgb(val, val, val);
         }
         screencols = 16;
         memcpy(d_ptr->hdr->clut, screenclut, sizeof(QRgb) * screencols);
         d_ptr->hdr->numcols = screencols;
     } else if (d == 1) {
         screencols = 2;
         screenclut[1] = qRgb(0xff, 0xff, 0xff);
         screenclut[0] = qRgb(0, 0, 0);
         memcpy(d_ptr->hdr->clut, screenclut, sizeof(QRgb) * screencols);
         d_ptr->hdr->numcols = screencols;
     }
 #ifndef QT_NO_QWS_CURSOR
     QScreenCursor::initSoftwareCursor();
 #endif
     return true;
 }
physicalSize()
QSize QVFbScreen::physicalSize () const virtual
Reimplement this function in subclass to return the physical size of the screen.
This function is used by QFont to convert point sizes to pixel sizes.
The default implementation takes the pixel size of the screen, considers a resolution of 100 dots per inch, and returns the calculated physical size. A device with a screen that has different resolutions will need to be supported by a suitable reimplementation of this function.
Reimplemented from QPlatformScreen.
Definition at line 394 of file qvfbintegration.cpp.
{
     return (d_ptr->screenSize()*254)/720;
 }
restore()
void QVFbScreen::restore () virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 416 of file qscreenvfb_qws.cpp.
 {
 }
save()
void QVFbScreen::save () virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 410 of file qscreenvfb_qws.cpp.
 {
     // nothing to do.
 }
screenImage()
QImage * QVFbScreen::screenImage ()
Definition at line 408 of file qvfbintegration.cpp.
Referenced by QVFbWindowSurface::paintDevice().
 {
     return d_ptr->screenImage();
 }
setDirty() [1/2]
void QVFbScreen::setDirty (const QRect & rectangle) virtual
Marks the given rectangle as dirty.
Note that the default implementation does nothing; reimplement this function to indicate that the given rectangle has been altered.
Reimplemented from QScreen.
setDirty() [2/2]
void QVFbScreen::setDirty (const QRect & r) virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 419 of file qscreenvfb_qws.cpp.
Referenced by QVFbScreenPrivate::disconnect(), QVFbWindowSurface::flush(), and setDirty().
 {
     const QRect r = rect.translated(-offset());
     d_ptr->hdr->dirty = true;
     d_ptr->hdr->update = d_ptr->hdr->update.united(r);
 }
setMode()
void QVFbScreen::setMode (int nw, int nh, int nd) virtual
Reimplemented Function
Implements QScreen.
Definition at line 403 of file qscreenvfb_qws.cpp.
 {
 }
shutdownDevice()
void QVFbScreen::shutdownDevice () virtual
Reimplemented Function
Reimplemented from QScreen.
Definition at line 399 of file qscreenvfb_qws.cpp.
 {
 }
Properties
d_ptr
QVFbScreenPrivate * QVFbScreen::d_ptr private
Definition at line 77 of file qscreenvfb_qws.h.
Referenced by blank(), connect(), disconnect(), initDevice(), QVFbScreen(), setDirty(), and ~QVFbScreen().
The documentation for this class was generated from the following files:
/src/gui/embedded/qscreenvfb_qws.h
/src/plugins/platforms/qvfb/qvfbintegration.h
/src/gui/embedded/qscreenvfb_qws.cpp
/src/plugins/platforms/qvfb/qvfbintegration.cpp