Qt 4.8: QDragMoveEvent Class Reference
QDragMoveEvent Class Reference
The QDragMoveEvent class provides an event which is sent while a drag and drop action is in progress.
#include <qevent.h>
Public Functions
void accept ()
Calls QDropEvent::accept().
void accept (const QRect &r)
The same as accept(), but also notifies that future moves will also be acceptable if they remain within the rectangle given on the widget.
QRect answerRect () const
Returns the rectangle in the widget where the drop will occur if accepted.
void ignore ()
Calls QDropEvent::ignore().
void ignore (const QRect &r)
The opposite of the accept(const QRect&) function.
QDragMoveEvent (const QPoint &pos, Qt::DropActions actions, const QMimeData *data, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Type type=DragMove)
Creates a QDragMoveEvent of the required type indicating that the mouse is at position pos given within a widget.
~QDragMoveEvent ()
Destroys the event.
Public Functions inherited from QDropEvent
void acceptProposedAction ()
Sets the drop action to be the proposed action.
Qt::DropAction dropAction () const
Returns the action to be performed on the data by the target.
QByteArray encodedData (const char *) const
Returns a byte array containing the drag's data, in format.
const char * format (int n=0) const
Returns a string describing one of the available data types for this drag.
Qt::KeyboardModifiers keyboardModifiers () const
Returns the modifier keys that are pressed.
const QMimeData * mimeData () const
Returns the data that was dropped on the widget and its associated MIME type information.
Qt::MouseButtons mouseButtons () const
Returns the mouse buttons that are pressed.
const QPoint & pos () const
Returns the position where the drop was made.
Qt::DropActions possibleActions () const
Returns an OR-combination of possible drop actions.
Qt::DropAction proposedAction () const
Returns the proposed drop action.
bool provides (const char *) const
Returns true if this event provides format mimeType; otherwise returns false.
QDropEvent (const QPoint &pos, Qt::DropActions actions, const QMimeData *data, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Type type=Drop)
Constructs a drop event of a certain type corresponding to a drop at the point specified by pos in the destination widget's coordinate system.
void setDropAction (Qt::DropAction action)
Sets the action to be performed on the data by the target.
QWidget * source () const
If the source of the drag operation is a widget in this application, this function returns that source; otherwise it returns 0.
~QDropEvent ()
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Public Functions inherited from QMimeSource
virtual ~QMimeSource ()
Destroys the MIME source.
Protected Variables
QRect rect
Protected Variables inherited from QDropEvent
Qt::DropActions act
Qt::DropAction default_action
Qt::DropAction drop_action
QList< QByteArray > fmts
const QMimeData * mdata
Qt::KeyboardModifiers modState
Qt::MouseButtons mouseState
QPoint p
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Friends
class QApplication
Additional Inherited Members
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Detailed Description
The QDragMoveEvent class provides an event which is sent while a drag and drop action is in progress.
A widget will receive drag move events repeatedly while the drag is within its boundaries, if it accepts drop events and QWidget::dragEnterEvent() . The widget should examine the event to see what kind of data it provides, and call the accept() function to accept the drop if appropriate.
The rectangle supplied by the answerRect() function can be used to restrict drops to certain parts of the widget. For example, we can check whether the rectangle intersects with the geometry of a certain child widget and only call acceptProposedAction() if that is the case.
Note that this class inherits most of its functionality from QDropEvent.
See also
QDragEnterEvent, QDragLeaveEvent, QDropEvent
Definition at line 530 of file qevent.h.
Constructors and Destructors
QDragMoveEvent()
QDragMoveEvent::QDragMoveEvent (const QPoint & pos, Qt::DropActions actions, const QMimeData * data, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Type type = DragMove)
Creates a QDragMoveEvent of the required type indicating that the mouse is at position pos given within a widget.
The mouse and keyboard states are specified by buttons and modifiers, and the actions describe the types of drag and drop operation that are possible. The drag data is passed as MIME-encoded information in data.
Warning
Do not attempt to create a QDragMoveEvent yourself. These objects rely on Qt's internal state.
Definition at line 2507 of file qevent.cpp.
     : QDropEvent(pos, actions, data, buttons, modifiers, type)
     , rect(pos, QSize(1, 1))
 {}
~QDragMoveEvent()
QDragMoveEvent::~QDragMoveEvent ()
Destroys the event.
Definition at line 2516 of file qevent.cpp.
 {
 }
Functions
accept() [1/2]
void QDragMoveEvent::accept () inline
Calls QDropEvent::accept().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 539 of file qevent.h.
Referenced by QColorWell::dragEnterEvent(), QColorShowLabel::dragEnterEvent(), QColorWell::dragMoveEvent(), QOleDropTarget::DragOver(), QIconModeViewBase::filterDragMoveEvent(), handle_xdnd_position(), QX11Data::motifdndHandle(), qt_mac_mouse_inside_answer_rect(), and QOleDropTarget::sendDragEnterEvent().
 { QDropEvent::accept(); }
accept() [2/2]
void QDragMoveEvent::accept (const QRect & rectangle) inline
The same as accept(), but also notifies that future moves will also be acceptable if they remain within the rectangle given on the widget.
This can improve performance, but may also be ignored by the underlying system.
If the rectangle is empty, drag move events will be sent continuously. This is useful if the source is scrolling in a timer event.
Definition at line 542 of file qevent.h.
Referenced by accept().
 { accept(); rect = r; }
answerRect()
QRect QDragMoveEvent::answerRect () const inline
Returns the rectangle in the widget where the drop will occur if accepted.
You can use this information to restrict drops to certain places on the widget.
Definition at line 537 of file qevent.h.
Referenced by QOleDropTarget::DragOver(), handle_xdnd_position(), qt_mac_copy_answer_rect(), and QOleDropTarget::sendDragEnterEvent().
 { return rect; }
ignore() [1/2]
void QDragMoveEvent::ignore () inline
Calls QDropEvent::ignore().
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 540 of file qevent.h.
Referenced by QColorWell::dragEnterEvent(), QColorShowLabel::dragEnterEvent(), QColorWell::dragMoveEvent(), and QIconModeViewBase::filterDragMoveEvent().
 { QDropEvent::ignore(); }
ignore() [2/2]
void QDragMoveEvent::ignore (const QRect & rectangle) inline
The opposite of the accept(const QRect&) function.
Moves within the rectangle are not acceptable, and will be ignored.
Definition at line 543 of file qevent.h.
Referenced by ignore().
 { ignore(); rect = r; }
Friends and Related Functions
QApplication
friend class QApplication friend
Definition at line 550 of file qevent.h.
Properties
rect
QRect QDragMoveEvent::rect protected
Definition at line 551 of file qevent.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qevent.h
/src/gui/kernel/qevent.cpp