Qt 4.8: QSqlTableModel Class Reference
QSqlTableModel Class Reference
The QSqlTableModel class provides an editable data model for a single database table.
#include <qsqltablemodel.h>
Public Types
enum EditStrategy { OnFieldChange, OnRowChange, OnManualSubmit }
This enum type describes which strategy to choose when editing values in the database.
Public Slots
void revert ()
This reimplemented slot is called by the item delegates when the user canceled editing the current row.
void revertAll ()
Reverts all pending changes.
bool submit ()
This reimplemented slot is called by the item delegates when the user stopped editing the current row.
bool submitAll ()
Submits all pending changes and returns true on success.
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void beforeDelete (int row)
This signal is emitted by deleteRowFromTable() before the row is deleted from the currently active database table.
void beforeInsert (QSqlRecord &record)
This signal is emitted by insertRowIntoTable() before a new row is inserted into the currently active database table.
void beforeUpdate (int row, QSqlRecord &record)
This signal is emitted by updateRowInTable() before the row is updated in the currently active database table with the values from record.
void primeInsert (int row, QSqlRecord &record)
This signal is emitted by insertRows(), when an insertion is initiated in the given row of the currently active database table.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void clear ()
Reimplemented Function
QVariant data (const QModelIndex &idx, int role=Qt::DisplayRole) const
Reimplemented Function
QSqlDatabase database () const
Returns a pointer to the used QSqlDatabase or 0 if no database was set.
EditStrategy editStrategy () const
Returns the current edit strategy.
int fieldIndex (const QString &fieldName) const
Returns the index of the field fieldName, or -1 if no corresponding field exists in the model.
QString filter () const
Returns the currently set filter.
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Reimplemented Function
bool insertRecord (int row, const QSqlRecord &record)
Inserts the record after row.
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Inserts count empty rows at position row.
bool isDirty (const QModelIndex &index) const
Returns true if the value at the index index is dirty, otherwise false.
QSqlIndex primaryKey () const
Returns the primary key for the current table, or an empty QSqlIndex if the table is not set or has no primary key.
QSqlTableModel (QObject *parent=0, QSqlDatabase db=QSqlDatabase())
Creates an empty QSqlTableModel and sets the parent to parent and the database connection to db.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Removes count columns from the parent model, starting at index column.
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Removes count rows starting at row.
virtual void revertRow (int row)
Reverts all changes for the specified row.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
virtual bool select ()
Populates the model with data from the table that was set via setTable(), using the specified filter and sort condition, and returns true if successful; otherwise returns false.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the data for the item index for the role role to value.
virtual void setEditStrategy (EditStrategy strategy)
Sets the strategy for editing values in the database to strategy.
virtual void setFilter (const QString &filter)
Sets the current filter to filter.
bool setRecord (int row, const QSqlRecord &record)
Sets the values at the specified row to the values of record.
virtual void setSort (int column, Qt::SortOrder order)
Sets the sort order for column to order.
virtual void setTable (const QString &tableName)
Sets the database table on which the model operates to tableName.
void sort (int column, Qt::SortOrder order)
Sorts the data by column with the sort order order.
QString tableName () const
Returns the name of the currently selected table.
virtual ~QSqlTableModel ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QSqlQueryModel
bool canFetchMore (const QModelIndex &parent=QModelIndex()) const
Returns true if it is possible to read more rows from the database.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void fetchMore (const QModelIndex &parent=QModelIndex())
Fetches more rows from a database.
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Inserts count columns into the model at position column.
QSqlError lastError () const
Returns information about the last error that occurred on the database.
QSqlQueryModel (QObject *parent=0)
Creates an empty QSqlQueryModel with the given parent.
QSqlQuery query () const
Returns the QSqlQuery associated with this model.
QSqlRecord record (int row) const
Returns the record containing information about the fields of the current query.
QSqlRecord record () const
Returns an empty record containing information about the fields of the current query.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the caption for a horizontal header for the specified role to value.
void setQuery (const QSqlQuery &query)
Resets the model and sets the data provider to be the given query.
void setQuery (const QString &query, const QSqlDatabase &db=QSqlDatabase())
Executes the query query for the given database connection db.
virtual ~QSqlQueryModel ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QAbstractTableModel
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns the index of the data in row and column with parent.
QAbstractTableModel (QObject *parent=0)
Constructs an abstract table model for the given parent.
~QAbstractTableModel ()
Destroys the abstract table model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual bool deleteRowFromTable (int row)
Deletes the given row from the currently active database table.
QModelIndex indexInQuery (const QModelIndex &item) const
Returns the index of the value in the database result set for the given item in the model.
virtual bool insertRowIntoTable (const QSqlRecord &values)
Inserts the values values into the currently active database table.
virtual QString orderByClause () const
Returns an SQL ORDER BY clause based on the currently set sort order.
QSqlTableModel (QSqlTableModelPrivate &dd, QObject *parent=0, QSqlDatabase db=QSqlDatabase())
virtual QString selectStatement () const
Returns the SQL SELECT statement used internally to populate the model.
void setPrimaryKey (const QSqlIndex &key)
Protected method that allows subclasses to set the primary key to key.
void setQuery (const QSqlQuery &query)
This function simply calls QSqlQueryModel::setQuery(query).
virtual bool updateRowInTable (int row, const QSqlRecord &values)
Updates the given row in the currently active database table with the specified values.
Protected Functions inherited from QSqlQueryModel
QModelIndex indexInQuery (const QModelIndex &item) const
Returns the index of the value in the database result set for the given item in the model.
QSqlQueryModel (QSqlQueryModelPrivate &dd, QObject *parent=0)
virtual void queryChange ()
This virtual function is called whenever the query changes.
void setLastError (const QSqlError &error)
Protected function which allows derived classes to set the value of the last error that occurred on the database to error.
Protected Functions inherited from QAbstractTableModel
QAbstractTableModel (QAbstractItemModelPrivate &dd, QObject *parent)
Constructs an abstract table model with dd and the given parent.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSqlTableModel class provides an editable data model for a single database table.
Attention
Module: QtSql
QSqlTableModel is a high-level interface for reading and writing database records from a single table. It is build on top of the lower-level QSqlQuery and can be used to provide data to view classes such as QTableView. For example:
    QSqlTableModel *model = new QSqlTableModel(parentObject, database);
    model->setTable("employee");
    model->setEditStrategy(QSqlTableModel::OnManualSubmit);
    model->select();
    model->setHeaderData(0, Qt::Horizontal, tr("Name"));
    model->setHeaderData(1, Qt::Horizontal, tr("Salary"));
    QTableView *view = new QTableView;
    view->setModel(model);
    view->hideColumn(0); // don't show the ID
    view->show();
We set the SQL table's name and the edit strategy, then we set up the labels displayed in the view header. The edit strategy dictates when the changes done by the user in the view are actually applied to the database. The possible values are OnFieldChange , OnRowChange , and OnManualSubmit .
QSqlTableModel can also be used to access a database programmatically, without binding it to a view:
    QSqlQueryModel model;
    model.setQuery("SELECT * FROM employee");
    int salary = model.record(4).value("salary").toInt();
The code snippet above extracts the salary field from record 4 in the result set of the query SELECT * from employee.
It is possible to set filters using setFilter(), or modify the sort order using setSort(). At the end, you must call select() to populate the model with data.
The sql/tablemodel example illustrates how to use QSqlTableModel as the data source for a QTableView.
QSqlTableModel provides no direct support for foreign keys. Use the QSqlRelationalTableModel and QSqlRelationalDelegate if you want to resolve foreign keys.
See also
QSqlRelationalTableModel, QSqlQuery, {Model/View Programming}, {Table Model Example}, {Cached Table Example}
Definition at line 59 of file qsqltablemodel.h.
Enumerations
EditStrategy
enum QSqlTableModel::EditStrategy
This enum type describes which strategy to choose when editing values in the database.
OnFieldChange All changes to the model will be applied immediately to the database.
OnRowChange Changes to a row will be applied when the user selects a different row.
OnManualSubmit All changes will be cached in the model until either submitAll() or revertAll() is called.
Note: To prevent inserting only partly initialized rows into the database, OnFieldChange will behave like OnRowChange for newly inserted rows.
See also
setEditStrategy()
Enumerator
OnFieldChange
OnRowChange
OnManualSubmit
Definition at line 65 of file qsqltablemodel.h.
 {OnFieldChange, OnRowChange, OnManualSubmit};
Constructors and Destructors
QSqlTableModel() [1/2]
QSqlTableModel::QSqlTableModel (QObject * parent = 0, QSqlDatabase db = QSqlDatabase()) explicit
Creates an empty QSqlTableModel and sets the parent to parent and the database connection to db.
If db is not valid, the default database connection will be used.
The default edit strategy is OnRowChange .
Definition at line 370 of file qsqltablemodel.cpp.
     : QSqlQueryModel(*new QSqlTableModelPrivate, parent)
 {
     Q_D(QSqlTableModel);
     d->db = db.isValid() ? db : QSqlDatabase::database();
 }
~QSqlTableModel()
QSqlTableModel::~QSqlTableModel () virtual
Destroys the object and frees any allocated resources.
Definition at line 389 of file qsqltablemodel.cpp.
 {
 }
QSqlTableModel() [2/2]
QSqlTableModel::QSqlTableModel (QSqlTableModelPrivate & dd, QObject * parent = 0, QSqlDatabase db = QSqlDatabase()) protected
Warning
This function is not part of the public interface.
Definition at line 379 of file qsqltablemodel.cpp.
     : QSqlQueryModel(dd, parent)
 {
     Q_D(QSqlTableModel);
     d->db = db.isValid() ? db : QSqlDatabase::database();
 }
Functions
beforeDelete
QSqlTableModel::beforeDelete (int row) signal
This signal is emitted by deleteRowFromTable() before the row is deleted from the currently active database table.
Referenced by deleteRowFromTable().
beforeInsert
QSqlTableModel::beforeInsert (QSqlRecord & record) signal
This signal is emitted by insertRowIntoTable() before a new row is inserted into the currently active database table.
The values that are about to be inserted are stored in record and can be modified before they will be inserted.
Referenced by insertRowIntoTable().
beforeUpdate
QSqlTableModel::beforeUpdate (int row, QSqlRecord & record) signal
This signal is emitted by updateRowInTable() before the row is updated in the currently active database table with the values from record.
Note that only values that are marked as generated will be updated. The generated flag can be set with QSqlRecord::setGenerated() and checked with QSqlRecord::isGenerated() .
See also
QSqlRecord::isGenerated()
Referenced by updateRowInTable().
clear()
void QSqlTableModel::clear (void) virtual
Reimplemented Function
Reimplemented from QSqlQueryModel.
Definition at line 1325 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModel::clear(), and setTable().
 {
     Q_D(QSqlTableModel);
     d->clear();
     QSqlQueryModel::clear();
 }
data()
QVariant QSqlTableModel::data (const QModelIndex & idx, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QSqlQueryModel.
Definition at line 457 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModel::data().
 {
     Q_D(const QSqlTableModel);
     if (!index.isValid() || (role != Qt::DisplayRole && role != Qt::EditRole))
         return QVariant();
     // Problem.. we need to use QSQM::indexInQuery to handle inserted columns
     // but inserted rows we need to handle
     // and indexInQuery is not virtual (grrr) so any values we pass to QSQM need
     // to handle the insertedRows
     QModelIndex item = indexInQuery(index);
     switch (d->strategy) {
     case OnFieldChange:
     case OnRowChange:
         if (index.row() == d->insertIndex) {
             if (item.column() < 0 || item.column() >= d->rec.count())
                 return QVariant();
             return d->editBuffer.value(index.column());
         }
         if (d->editIndex == item.row()) {
             if (d->editBuffer.isGenerated(item.column()))
                 return d->editBuffer.value(item.column());
         }
         break;
     case OnManualSubmit:
         if (d->cache.contains(index.row())) {
             const QSqlTableModelPrivate::ModifiedRow row = d->cache.value(index.row());
             if (row.rec.isGenerated(item.column()) || row.op == QSqlTableModelPrivate::Insert)
                 return row.rec.value(item.column());
         }
         break;
     }
     // We need to handle row mapping here, but not column mapping
     return QSqlQueryModel::data(index.sibling(item.row(), index.column()), role);
 }
database()
QSqlDatabase QSqlTableModel::database () const
Returns a pointer to the used QSqlDatabase or 0 if no database was set.
Definition at line 976 of file qsqltablemodel.cpp.
Referenced by QRelation::populateDictionary(), QRelation::populateModel(), and QSqlRelationalTableModel::selectStatement().
 {
     Q_D(const QSqlTableModel);
      return d->db;
 }
deleteRowFromTable()
bool QSqlTableModel::deleteRowFromTable (int row) protected virtual
Deletes the given row from the currently active database table.
This is a low-level method that operates directly on the database and should not be called directly. Use removeRow() or removeRows() to delete values. The model will decide depending on its edit strategy when to modify the database.
Returns true if the row was deleted; otherwise returns false.
See also
removeRow(), removeRows()
Definition at line 707 of file qsqltablemodel.cpp.
Referenced by removeRows(), and submitAll().
 {
     Q_D(QSqlTableModel);
     emit beforeDelete(row);
     const QSqlRecord whereValues = d->strategy == OnManualSubmit ? d->cache[row].primaryValues : d->primaryValues(row);
     bool prepStatement = d->db.driver()->hasFeature(QSqlDriver::PreparedQueries);
     QString stmt = d->db.driver()->sqlStatement(QSqlDriver::DeleteStatement,
                                                 d->tableName,
                                                 QSqlRecord(),
                                                 prepStatement);
     QString where = d->db.driver()->sqlStatement(QSqlDriver::WhereStatement,
                                                  d->tableName,
                                                  whereValues,
                                                  prepStatement);
     if (stmt.isEmpty() || where.isEmpty()) {
         d->error = QSqlError(QLatin1String("Unable to delete row"), QString(),
                              QSqlError::StatementError);
         return false;
     }
     stmt.append(QLatin1Char(' ')).append(where);
     return d->exec(stmt, prepStatement, QSqlRecord() /* no new values */, whereValues);
 }
editStrategy()
QSqlTableModel::EditStrategy QSqlTableModel::editStrategy () const
Returns the current edit strategy.
See also
setEditStrategy()
Definition at line 886 of file qsqltablemodel.cpp.
 {
     Q_D(const QSqlTableModel);
     return d->strategy;
 }
fieldIndex()
int QSqlTableModel::fieldIndex (const QString & fieldName) const
Returns the index of the field fieldName, or -1 if no corresponding field exists in the model.
Definition at line 1037 of file qsqltablemodel.cpp.
 {
     Q_D(const QSqlTableModel);
     return d->rec.indexOf(fieldName);
 }
filter()
QString QSqlTableModel::filter () const
Returns the currently set filter.
See also
setFilter(), select()
Definition at line 1297 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModel::selectStatement(), and setFilter().
 {
     Q_D(const QSqlTableModel);
     return d->filter;
 }
flags()
Qt::ItemFlags QSqlTableModel::flags (const QModelIndex & index) const virtual
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 1334 of file qsqltablemodel.cpp.
 {
     Q_D(const QSqlTableModel);
     if (index.internalPointer() || index.column() < 0 || index.column() >= d->rec.count()
         || index.row() < 0)
         return 0;
     if (d->rec.field(index.column()).isReadOnly())
         return Qt::ItemIsSelectable | Qt::ItemIsEnabled;
     return Qt::ItemIsSelectable | Qt::ItemIsEnabled | Qt::ItemIsEditable;
 }
headerData()
QVariant QSqlTableModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QSqlQueryModel.
Definition at line 498 of file qsqltablemodel.cpp.
 {
     Q_D(const QSqlTableModel);
     if (orientation == Qt::Vertical && role == Qt::DisplayRole) {
         switch (d->strategy) {
         case OnFieldChange:
         case OnRowChange:
             if (d->insertIndex == section)
                 return QLatin1String("*");
             break;
         case OnManualSubmit:
             QSqlTableModelPrivate::Op op = d->cache.value(section).op;
             if (op == QSqlTableModelPrivate::Insert)
                 return QLatin1String("*");
             else if (op == QSqlTableModelPrivate::Delete)
                 return QLatin1String("!");
             break;
         }
     }
     return QSqlQueryModel::headerData(section, orientation, role);
 }
indexInQuery()
QModelIndex QSqlTableModel::indexInQuery (const QModelIndex & item) const protected
Returns the index of the value in the database result set for the given item in the model.
The return value is identical to item if no columns or rows have been inserted, removed, or moved around.
Returns an invalid model index if item is out of bounds or if item does not point to a value in the result set.
See also
QSqlQueryModel::indexInQuery()
Definition at line 1272 of file qsqltablemodel.cpp.
Referenced by data(), removeRows(), setData(), and setRecord().
 {
     Q_D(const QSqlTableModel);
     const QModelIndex it = QSqlQueryModel::indexInQuery(item); // this adjusts columns only
     if (d->strategy == OnManualSubmit) {
         int rowOffset = 0;
         QSqlTableModelPrivate::CacheMap::ConstIterator i = d->cache.constBegin();
         while (i != d->cache.constEnd() && i.key() <= it.row()) {
             if (i.value().op == QSqlTableModelPrivate::Insert)
                 ++rowOffset;
             ++i;
         }
         return createIndex(it.row() - rowOffset, it.column(), it.internalPointer());
     } else {
         if (d->insertIndex >= 0 && it.row() >= d->insertIndex)
             return createIndex(it.row() - 1, it.column(), it.internalPointer());
     }
     return it;
 }
insertRecord()
bool QSqlTableModel::insertRecord (int row, const QSqlRecord & record)
Inserts the record after row.
If row is negative, the record will be appended to the end. Calls insertRows() and setRecord() internally.
Returns true if the row could be inserted, otherwise false.
See also
insertRows(), removeRows()
Definition at line 1224 of file qsqltablemodel.cpp.
 {
     Q_D(QSqlTableModel);
     if (row < 0)
         row = rowCount();
     if (!insertRow(row, QModelIndex()))
         return false;
     if (!setRecord(row, record))
         return false;
     if (d->strategy == OnFieldChange || d->strategy == OnRowChange)
         return submit();
     return true;
 }
insertRowIntoTable()
bool QSqlTableModel::insertRowIntoTable (const QSqlRecord & values) protected virtual
Inserts the values values into the currently active database table.
This is a low-level method that operates directly on the database and should not be called directly. Use insertRow() and setData() to insert values. The model will decide depending on its edit strategy when to modify the database.
Returns true if the values could be inserted, otherwise false. Error information can be retrieved with lastError() .
See also
lastError(), insertRow(), insertRows()
Reimplemented in QSqlRelationalTableModel.
Definition at line 676 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModel::insertRowIntoTable(), and submitAll().
 {
     Q_D(QSqlTableModel);
     QSqlRecord rec = values;
     emit beforeInsert(rec);
     bool prepStatement = d->db.driver()->hasFeature(QSqlDriver::PreparedQueries);
     QString stmt = d->db.driver()->sqlStatement(QSqlDriver::InsertStatement, d->tableName,
                                                 rec, prepStatement);
     if (stmt.isEmpty()) {
         d->error = QSqlError(QLatin1String("No Fields to update"), QString(),
                                  QSqlError::StatementError);
         return false;
     }
     return d->exec(stmt, prepStatement, rec, QSqlRecord() /* no where values */);
 }
insertRows()
bool QSqlTableModel::insertRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Inserts count empty rows at position row.
Note that parent must be invalid, since this model does not support parent-child relations.
Only one row at a time can be inserted when using the OnFieldChange or OnRowChange update strategies.
The primeInsert() signal will be emitted for each new row. Connect to it if you want to initialize the new row with default values.
Returns false if the parameters are out of bounds; otherwise returns true.
See also
primeInsert(), insertRecord()
Reimplemented from QAbstractItemModel.
Definition at line 1175 of file qsqltablemodel.cpp.
 {
     Q_D(QSqlTableModel);
     if (row < 0 || count <= 0 || row > rowCount() || parent.isValid())
         return false;
     switch (d->strategy) {
     case OnFieldChange:
     case OnRowChange:
         if (count != 1)
             return false;
         beginInsertRows(parent, row, row);
         d->insertIndex = row;
         // ### apply dangling changes...
         d->clearEditBuffer();
         emit primeInsert(row, d->editBuffer);
         break;
     case OnManualSubmit:
         beginInsertRows(parent, row, row + count - 1);
         if (!d->cache.isEmpty()) {
             QMap<int, QSqlTableModelPrivate::ModifiedRow>::Iterator it = d->cache.end();
             while (it != d->cache.begin() && (--it).key() >= row) {
                 int oldKey = it.key();
                 const QSqlTableModelPrivate::ModifiedRow oldValue = it.value();
                 d->cache.erase(it);
                 it = d->cache.insert(oldKey + count, oldValue);
             }
         }
         for (int i = 0; i < count; ++i) {
             d->cache[row + i] = QSqlTableModelPrivate::ModifiedRow(QSqlTableModelPrivate::Insert,
                                                                    d->rec);
             emit primeInsert(row + i, d->cache[row + i].rec);
         }
         break;
     }
     endInsertRows();
     return true;
 }
isDirty()
bool QSqlTableModel::isDirty (const QModelIndex & index) const
Returns true if the value at the index index is dirty, otherwise false.
Dirty values are values that were modified in the model but not yet written into the database.
If index is invalid or points to a non-existing row, false is returned.
Definition at line 527 of file qsqltablemodel.cpp.
 {
     Q_D(const QSqlTableModel);
     if (!index.isValid())
         return false;
     switch (d->strategy) {
         case OnFieldChange:
             return false;
         case OnRowChange:
             return index.row() == d->editIndex && d->editBuffer.isGenerated(index.column());
         case OnManualSubmit: {
             const QSqlTableModelPrivate::ModifiedRow row = d->cache.value(index.row());
             return row.op == QSqlTableModelPrivate::Insert
                    || row.op == QSqlTableModelPrivate::Delete
                    || (row.op == QSqlTableModelPrivate::Update
                        && row.rec.isGenerated(index.column()));
         }
     }
     return false;
 }
orderByClause()
QString QSqlTableModel::orderByClause () const protected virtual
Returns an SQL ORDER BY clause based on the currently set sort order.
See also
setSort(), selectStatement()
Reimplemented in QSqlRelationalTableModel.
Definition at line 1015 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModel::orderByClause(), and selectStatement().
 {
     Q_D(const QSqlTableModel);
     QString s;
     QSqlField f = d->rec.field(d->sortColumn);
     if (!f.isValid())
         return s;
     QString table = d->tableName;
     //we can safely escape the field because it would have been obtained from the database
     //and have the correct case
     QString field = d->db.driver()->escapeIdentifier(f.name(), QSqlDriver::FieldName);
     s.append(QLatin1String("ORDER BY ")).append(table).append(QLatin1Char('.')).append(field);
     s += d->sortOrder == Qt::AscendingOrder ? QLatin1String(" ASC") : QLatin1String(" DESC");
     return s;
 }
primaryKey()
QSqlIndex QSqlTableModel::primaryKey () const
Returns the primary key for the current table, or an empty QSqlIndex if the table is not set or has no primary key.
See also
setTable(), setPrimaryKey(), QSqlDatabase::primaryIndex()
Definition at line 952 of file qsqltablemodel.cpp.
 {
     Q_D(const QSqlTableModel);
     return d->primaryIndex;
 }
primeInsert
void QSqlTableModel::primeInsert (int row, QSqlRecord & record) signal
This signal is emitted by insertRows(), when an insertion is initiated in the given row of the currently active database table.
The record parameter can be written to (since it is a reference), for example to populate some fields with default values.
Referenced by insertRows().
removeColumns()
bool QSqlTableModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Removes count columns from the parent model, starting at index column.
Returns if the columns were successfully removed; otherwise returns false.
See also
removeRows()
Reimplemented from QSqlQueryModel.
Definition at line 1092 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModel::removeColumns().
 {
     Q_D(QSqlTableModel);
     if (parent.isValid() || column < 0 || column + count > d->rec.count())
         return false;
     for (int i = 0; i < count; ++i)
         d->rec.remove(column);
     if (d->query.isActive())
         return select();
     return true;
 }
removeRows()
bool QSqlTableModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Removes count rows starting at row.
Since this model does not support hierarchical structures, parent must be an invalid model index.
Emits the beforeDelete() signal before a row is deleted. When the edit strategy is OnManualSubmit signal emission is delayed until submitAll() is called.
Returns true if all rows could be removed; otherwise returns false. Detailed error information can be retrieved using lastError().
See also
removeColumns(), insertRows()
Reimplemented from QAbstractItemModel.
Definition at line 1119 of file qsqltablemodel.cpp.
 {
     Q_D(QSqlTableModel);
     if (parent.isValid() || row < 0 || count <= 0)
         return false;
     int i;
     switch (d->strategy) {
     case OnFieldChange:
     case OnRowChange:
         for (i = 0; i < count; ++i) {
             if (row + i == d->insertIndex)
                 d->revertInsertedRow();
             else if (!deleteRowFromTable(row + i))
                 return false;
         }
         select();
         break;
     case OnManualSubmit:
         for (i = 0; i < count; ++i) {
             int idx = row + i;
             if (idx >= rowCount())
                 return false;
             if (d->cache.value(idx).op == QSqlTableModelPrivate::Insert) {
                 revertRow(idx);
                 // Reverting a row means all the other cache entries have been adjusted downwards
                 // so fake this by adjusting row
                 --row;
             } else {
                 d->cache[idx].op = QSqlTableModelPrivate::Delete;
                 d->cache[idx].primaryValues = d->primaryValues(indexInQuery(createIndex(idx, 0)).row());
                 emit headerDataChanged(Qt::Vertical, idx, idx);
             }
         }
         break;
     }
     return true;
 }
revert
void QSqlTableModel::revert () slot
This reimplemented slot is called by the item delegates when the user canceled editing the current row.
Reverts the changes if the model's strategy is set to OnRowChange. Does nothing for the other edit strategies.
Use revertAll() to revert all pending changes for the OnManualSubmit strategy or revertRow() to revert a specific row.
See also
submit(), submitAll(), revertRow(), revertAll()
Definition at line 839 of file qsqltablemodel.cpp.
 {
     Q_D(QSqlTableModel);
     if (d->strategy == OnRowChange)
         revertAll();
 }
revertAll
void QSqlTableModel::revertAll () slot
Reverts all pending changes.
See also
revert(), revertRow(), submitAll()
Definition at line 897 of file qsqltablemodel.cpp.
Referenced by revert(), select(), and setEditStrategy().
 {
     Q_D(QSqlTableModel);
     switch (d->strategy) {
     case OnFieldChange:
         break;
     case OnRowChange:
         if (d->editIndex != -1)
             revertRow(d->editIndex);
         else if (d->insertIndex != -1)
             revertRow(d->insertIndex);
         break;
     case OnManualSubmit:
         while (!d->cache.isEmpty())
             revertRow(d->cache.constBegin().key());
         break;
     }
 }
revertRow()
void QSqlTableModel::revertRow (int row) virtual
Reverts all changes for the specified row.
See also
revert(), revertAll(), submit(), submitAll()
Definition at line 921 of file qsqltablemodel.cpp.
Referenced by removeRows(), revertAll(), and QSqlRelationalTableModel::revertRow().
 {
     if (row < 0)
         return;
     Q_D(QSqlTableModel);
     switch (d->strategy) {
     case OnFieldChange:
         break;
     case OnRowChange: {
         if (d->editIndex == row) {
             d->editBuffer.clear();
             int oldIndex = d->editIndex;
             d->editIndex = -1;
             emit dataChanged(createIndex(oldIndex, 0), createIndex(oldIndex, columnCount() - 1));
         } else if (d->insertIndex == row) {
             d->revertInsertedRow();
         }
         break; }
     case OnManualSubmit:
         d->revertCachedRow(row);
         break;
     }
 }
rowCount()
int QSqlTableModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Reimplemented from QSqlQueryModel.
Definition at line 1240 of file qsqltablemodel.cpp.
Referenced by insertRecord(), insertRows(), QRelation::populateDictionary(), removeRows(), setData(), setRecord(), and updateRowInTable().
 {
     Q_D(const QSqlTableModel);
     if (parent.isValid())
         return 0;
     int rc = QSqlQueryModel::rowCount();
     if (d->strategy == OnManualSubmit) {
         for (QSqlTableModelPrivate::CacheMap::ConstIterator it = d->cache.constBegin();
              it != d->cache.constEnd(); ++it) {
              if (it.value().op == QSqlTableModelPrivate::Insert)
                  ++rc;
         }
     } else if (d->insertIndex >= 0) {
         ++rc;
     }
     return rc;
 }
select()
bool QSqlTableModel::select () virtual
Populates the model with data from the table that was set via setTable(), using the specified filter and sort condition, and returns true if successful; otherwise returns false.
Note
Calling select() will revert any unsubmitted changes and remove any inserted columns.
See also
setTable(), setFilter(), selectStatement()
Reimplemented in QRelatedTableModel, and QSqlRelationalTableModel.
Definition at line 435 of file qsqltablemodel.cpp.
Referenced by removeColumns(), removeRows(), QSqlRelationalTableModel::select(), QRelatedTableModel::select(), setData(), setFilter(), sort(), and submitAll().
 {
     Q_D(QSqlTableModel);
     QString query = selectStatement();
     if (query.isEmpty())
         return false;
     revertAll();
     QSqlQuery qu(query, d->db);
     setQuery(qu);
     if (!qu.isActive() || lastError().isValid()) {
         // something went wrong - revert to non-select state
         d->initRecordAndPrimaryIndex();
         return false;
     }
     return true;
 }
selectStatement()
QString QSqlTableModel::selectStatement () const protected virtual
Returns the SQL SELECT statement used internally to populate the model.
The statement includes the filter and the ORDER BY clause.
See also
filter(), orderByClause()
Reimplemented in QSqlRelationalTableModel.
Definition at line 1050 of file qsqltablemodel.cpp.
Referenced by select(), and QSqlRelationalTableModel::selectStatement().
 {
     Q_D(const QSqlTableModel);
     QString query;
     if (d->tableName.isEmpty()) {
         d->error = QSqlError(QLatin1String("No table name given"), QString(),
                              QSqlError::StatementError);
         return query;
     }
     if (d->rec.isEmpty()) {
         d->error = QSqlError(QLatin1String("Unable to find table ") + d->tableName, QString(),
                              QSqlError::StatementError);
         return query;
     }
     query = d->db.driver()->sqlStatement(QSqlDriver::SelectStatement,
                                          d->tableName,
                                          d->rec,
                                          false);
     if (query.isEmpty()) {
         d->error = QSqlError(QLatin1String("Unable to select fields from table ") + d->tableName,
                              QString(), QSqlError::StatementError);
         return query;
     }
     if (!d->filter.isEmpty())
         query.append(QLatin1String(" WHERE ")).append(d->filter);
     QString orderBy(orderByClause());
     if (!orderBy.isEmpty())
         query.append(QLatin1Char(' ')).append(orderBy);
     return query;
 }
setData()
bool QSqlTableModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Sets the data for the item index for the role role to value.
Depending on the edit strategy, the value might be applied to the database at once or cached in the model.
Returns true if the value could be set or false on error, for example if index is out of bounds.
See also
editStrategy(), data(), submit(), submitAll(), revertRow()
Reimplemented from QAbstractItemModel.
Definition at line 559 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModel::setData().
 {
     Q_D(QSqlTableModel);
     if (role != Qt::EditRole)
         return QSqlQueryModel::setData(index, value, role);
     if (!index.isValid() || index.column() >= d->rec.count() || index.row() >= rowCount())
         return false;
     bool isOk = true;
     switch (d->strategy) {
     case OnFieldChange: {
         if (index.row() == d->insertIndex) {
             QSqlTableModelPrivate::setGeneratedValue(d->editBuffer, index.column(), value);
             return true;
         }
         d->clearEditBuffer();
         QSqlTableModelPrivate::setGeneratedValue(d->editBuffer, index.column(), value);
         isOk = updateRowInTable(index.row(), d->editBuffer);
         if (isOk)
             select();
         emit dataChanged(index, index);
         break; }
     case OnRowChange:
         if (index.row() == d->insertIndex) {
             QSqlTableModelPrivate::setGeneratedValue(d->editBuffer, index.column(), value);
             return true;
         }
         if (d->editIndex != index.row()) {
             if (d->editIndex != -1)
                 submit();
             d->clearEditBuffer();
         }
         QSqlTableModelPrivate::setGeneratedValue(d->editBuffer, index.column(), value);
         d->editIndex = index.row();
         emit dataChanged(index, index);
         break;
     case OnManualSubmit: {
         QSqlTableModelPrivate::ModifiedRow &row = d->cache[index.row()];
         if (row.op == QSqlTableModelPrivate::None) {
             row.op = QSqlTableModelPrivate::Update;
             row.rec = d->rec;
             QSqlTableModelPrivate::clearGenerated(row.rec);
             row.primaryValues = d->primaryValues(indexInQuery(index).row());
         }
         QSqlTableModelPrivate::setGeneratedValue(row.rec, index.column(), value);
         emit dataChanged(index, index);
         break; }
     }
     return isOk;
 }
setEditStrategy()
void QSqlTableModel::setEditStrategy (EditStrategy strategy) virtual
Sets the strategy for editing values in the database to strategy.
This will revert any pending changes.
See also
editStrategy(), revertAll()
Definition at line 874 of file qsqltablemodel.cpp.
 {
     Q_D(QSqlTableModel);
     revertAll();
     d->strategy = strategy;
 }
setFilter()
void QSqlTableModel::setFilter (const QString & filter) virtual
Sets the current filter to filter.
The filter is a SQL WHERE clause without the keyword WHERE (for example, name='Josephine').
If the model is already populated with data from a database, the model re-selects it with the new filter. Otherwise, the filter will be applied the next time select() is called.
See also
filter(), select(), selectStatement(), orderByClause()
Definition at line 1315 of file qsqltablemodel.cpp.
 {
     Q_D(QSqlTableModel);
     d->filter = filter;
     if (d->query.isActive())
         select();
 }
setPrimaryKey()
void QSqlTableModel::setPrimaryKey (const QSqlIndex & key) protected
Protected method that allows subclasses to set the primary key to key.
Normally, the primary index is set automatically whenever you call setTable().
See also
primaryKey(), QSqlDatabase::primaryIndex()
Definition at line 967 of file qsqltablemodel.cpp.
 {
     Q_D(QSqlTableModel);
     d->primaryIndex = key;
 }
setQuery()
void QSqlTableModel::setQuery (const QSqlQuery & query) protected
This function simply calls QSqlQueryModel::setQuery(query).
You should normally not call it on a QSqlTableModel. Instead, use setTable(), setSort(), setFilter(), etc., to set up the query.
See also
selectStatement()
Definition at line 618 of file qsqltablemodel.cpp.
Referenced by select().
 {
     QSqlQueryModel::setQuery(query);
 }
setRecord()
bool QSqlTableModel::setRecord (int row, const QSqlRecord & record)
Sets the values at the specified row to the values of record.
Returns true if all the values could be set; otherwise returns false.
See also
record()
Definition at line 1352 of file qsqltablemodel.cpp.
Referenced by insertRecord().
 {
     Q_D(QSqlTableModel);
     Q_ASSERT_X(row >= 0, "QSqlTableModel::setRecord()", "Cannot set a record to a row less than 0");
     if (row >= rowCount())
         return false;
     bool isOk = true;
     switch (d->strategy) {
     case OnFieldChange:
     case OnRowChange:
         return d->setRecord(row, record);
     case OnManualSubmit: {
         QSqlTableModelPrivate::ModifiedRow &mrow = d->cache[row];
         if (mrow.op == QSqlTableModelPrivate::None) {
             mrow.op = QSqlTableModelPrivate::Update;
             mrow.rec = d->rec;
             QSqlTableModelPrivate::clearGenerated(mrow.rec);
             mrow.primaryValues = d->primaryValues(indexInQuery(createIndex(row, 0)).row());
         }
         QString fieldName;
         for (int i = 0; i < record.count(); ++i) {
             fieldName = record.fieldName(i);
             if (d->db.driver()->isIdentifierEscaped(fieldName, QSqlDriver::FieldName))
                 fieldName = d->db.driver()->stripDelimiters(fieldName, QSqlDriver::FieldName);
             int idx = mrow.rec.indexOf(fieldName);
             if (idx == -1) {
                 isOk = false;
             } else {
                 mrow.rec.setValue(idx, record.value(i));
                 mrow.rec.setGenerated(idx, record.isGenerated(i));
             }
         }
         if (isOk)
             emit dataChanged(createIndex(row, 0), createIndex(row, columnCount() - 1));
         return isOk; }
     }
     return false;
 }
setSort()
void QSqlTableModel::setSort (int column, Qt::SortOrder order) virtual
Sets the sort order for column to order.
This does not affect the current data, to refresh the data using the new sort order, call select().
See also
select(), orderByClause()
Definition at line 1002 of file qsqltablemodel.cpp.
Referenced by sort().
 {
     Q_D(QSqlTableModel);
     d->sortColumn = column;
     d->sortOrder = order;
 }
setTable()
void QSqlTableModel::setTable (const QString & tableName) virtual
Sets the database table on which the model operates to tableName.
Does not select data from the table, but fetches its field information.
To populate the model with the table's data, call select().
Error information can be retrieved with lastError() .
See also
select(), setFilter(), lastError()
Reimplemented in QSqlRelationalTableModel.
Definition at line 404 of file qsqltablemodel.cpp.
Referenced by QRelation::populateModel(), and QSqlRelationalTableModel::setTable().
 {
     Q_D(QSqlTableModel);
     clear();
     d->tableName = tableName;
     d->initRecordAndPrimaryIndex();
     d->initColOffsets(d->rec.count());
     if (d->rec.count() == 0)
         d->error = QSqlError(QLatin1String("Unable to find table ") + d->tableName, QString(),
                              QSqlError::StatementError);
 }
sort()
void QSqlTableModel::sort (int column, Qt::SortOrder order) virtual
Sorts the data by column with the sort order order.
This will immediately select data, use setSort() to set a sort order without populating the model with data.
See also
setSort(), select(), orderByClause()
Reimplemented from QAbstractItemModel.
Definition at line 989 of file qsqltablemodel.cpp.
 {
     setSort(column, order);
     select();
 }
submit
bool QSqlTableModel::submit () slot
This reimplemented slot is called by the item delegates when the user stopped editing the current row.
Submits the currently edited row if the model's strategy is set to OnRowChange or OnFieldChange. Does nothing for the OnManualSubmit strategy.
Use submitAll() to submit all pending changes for the OnManualSubmit strategy.
Returns true on success; otherwise returns false. Use lastError() to query detailed error information.
On success the model will be repopulated. Any views presenting it will lose their selections.
See also
revert(), revertRow(), submitAll(), revertAll(), lastError()
Definition at line 819 of file qsqltablemodel.cpp.
Referenced by insertRecord(), and setData().
 {
     Q_D(QSqlTableModel);
     if (d->strategy == OnRowChange || d->strategy == OnFieldChange)
         return submitAll();
     return true;
 }
submitAll
bool QSqlTableModel::submitAll () slot
Submits all pending changes and returns true on success.
Returns false on error, detailed error information can be obtained with lastError().
On success the model will be repopulated. Any views presenting it will lose their selections.
Note: In OnManualSubmit mode, already submitted changes won't be cleared from the cache when submitAll() fails. This allows transactions to be rolled back and resubmitted again without losing data.
See also
revertAll(), lastError()
Definition at line 748 of file qsqltablemodel.cpp.
Referenced by submit().
 {
     Q_D(QSqlTableModel);
     switch (d->strategy) {
     case OnFieldChange:
         if (d->insertIndex == -1)
             return true;
         // else fall through
     case OnRowChange:
         if (d->editBuffer.isEmpty())
             return true;
         if (d->insertIndex != -1) {
             if (!insertRowIntoTable(d->editBuffer))
                 return false;
             d->bottom = d->bottom.sibling(d->bottom.row() + 1, d->bottom.column());
         } else {
             if (!updateRowInTable(d->editIndex, d->editBuffer))
                 return false;
         }
         d->clearEditBuffer();
         d->editIndex = -1;
         d->insertIndex = -1;
         return select();
     case OnManualSubmit:
         for (QSqlTableModelPrivate::CacheMap::ConstIterator it = d->cache.constBegin();
              it != d->cache.constEnd(); ++it) {
             switch (it.value().op) {
             case QSqlTableModelPrivate::Insert:
                 if (!insertRowIntoTable(it.value().rec))
                     return false;
                 d->bottom = d->bottom.sibling(d->bottom.row() + 1, d->bottom.column());
                 break;
             case QSqlTableModelPrivate::Update:
                 if (!updateRowInTable(it.key(), it.value().rec))
                     return false;
                 break;
             case QSqlTableModelPrivate::Delete:
                 if (!deleteRowFromTable(it.key()))
                     return false;
                 break;
             case QSqlTableModelPrivate::None:
                 Q_ASSERT_X(false, "QSqlTableModel::submitAll()", "Invalid cache operation");
                 break;
             }
         }
         d->clearCache();
         return select();
     }
     return false;
 }
tableName()
QString QSqlTableModel::tableName () const
Returns the name of the currently selected table.
Definition at line 420 of file qsqltablemodel.cpp.
Referenced by QSqlRelationalTableModelPrivate::QSqlRelationalTableModelPrivate(), QSqlRelationalTableModel::selectStatement(), and setTable().
 {
     Q_D(const QSqlTableModel);
     return d->tableName;
 }
updateRowInTable()
bool QSqlTableModel::updateRowInTable (int row, const QSqlRecord & values) protected virtual
Updates the given row in the currently active database table with the specified values.
Returns true if successful; otherwise returns false.
This is a low-level method that operates directly on the database and should not be called directly. Use setData() to update values. The model will decide depending on its edit strategy when to modify the database.
Note that only values that have the generated-flag set are updated. The generated-flag can be set with QSqlRecord::setGenerated() and tested with QSqlRecord::isGenerated().
See also
QSqlRecord::isGenerated(), setData()
Reimplemented in QSqlRelationalTableModel.
Definition at line 639 of file qsqltablemodel.cpp.
Referenced by setData(), submitAll(), and QSqlRelationalTableModel::updateRowInTable().
 {
     Q_D(QSqlTableModel);
     QSqlRecord rec(values);
     emit beforeUpdate(row, rec);
     const QSqlRecord whereValues = d->strategy == OnManualSubmit ? d->cache[row].primaryValues : d->primaryValues(row);
     bool prepStatement = d->db.driver()->hasFeature(QSqlDriver::PreparedQueries);
     QString stmt = d->db.driver()->sqlStatement(QSqlDriver::UpdateStatement, d->tableName,
                                                 rec, prepStatement);
     QString where = d->db.driver()->sqlStatement(QSqlDriver::WhereStatement, d->tableName,
                                                  whereValues, prepStatement);
     if (stmt.isEmpty() || where.isEmpty() || row < 0 || row >= rowCount()) {
         d->error = QSqlError(QLatin1String("No Fields to update"), QString(),
                                  QSqlError::StatementError);
         return false;
     }
     stmt.append(QLatin1Char(' ')).append(where);
     return d->exec(stmt, prepStatement, rec, whereValues);
 }
The documentation for this class was generated from the following files:
/src/sql/models/qsqltablemodel.h
/src/sql/models/qsqltablemodel.cpp