Qt 4.8: QTextDecoder Class Reference
QTextDecoder Class Reference
The QTextDecoder class provides a state-based decoder.
#include <qtextcodec.h>
Public Functions
bool hasFailure () const
Determines whether the decoder encountered a failure while decoding the input.
QTextDecoder (const QTextCodec *codec)
Constructs a text decoder for the given codec.
QTextDecoder (const QTextCodec *codec, QTextCodec::ConversionFlags flags)
Constructs a text decoder for the given codec and conversion flags.
QString toUnicode (const char *chars, int len)
Converts the first len bytes in chars to Unicode, returning the result.
QString toUnicode (const QByteArray &ba)
Converts the bytes in the byte array specified by ba to Unicode and returns the result.
void toUnicode (QString *target, const char *chars, int len)
The converted string is returned in target.
~QTextDecoder ()
Destroys the decoder.
Properties
const QTextCodec * c
QTextCodec::ConverterState state
Detailed Description
The QTextDecoder class provides a state-based decoder.
Note
This class or function is reentrant.
A text decoder converts text from an encoded text format into Unicode using a specific codec.
The decoder converts text in this format into Unicode, remembering any state that is required between calls.
See also
QTextCodec::makeDecoder(), QTextEncoder
Definition at line 177 of file qtextcodec.h.
Constructors and Destructors
QTextDecoder() [1/2]
QTextDecoder::QTextDecoder (const QTextCodec * codec) inline explicit
Constructs a text decoder for the given codec.
Definition at line 180 of file qtextcodec.h.
 : c(codec), state() {}
QTextDecoder() [2/2]
QTextDecoder::QTextDecoder (const QTextCodec * codec, QTextCodec::ConversionFlags flags)
Constructs a text decoder for the given codec and conversion flags.
Since
4.7
Definition at line 1621 of file qtextcodec.cpp.
     : c(codec), state()
 {
     state.flags = flags;
 }
~QTextDecoder()
QTextDecoder::~QTextDecoder ()
Destroys the decoder.
Definition at line 1630 of file qtextcodec.cpp.
 {
 }
Functions
hasFailure()
bool QTextDecoder::hasFailure () const
Determines whether the decoder encountered a failure while decoding the input.
Warning
This function is not part of the public interface.
Since
4.3 If an error was encountered, the produced result is undefined, and gets converted as according to the conversion flags.
Definition at line 1888 of file qtextcodec.cpp.
Referenced by QXmlStreamReaderPrivate::getChar_helper(), and QXmlStreamReaderPrivate::parse().
 {
     return state.invalidChars != 0;
 }
toUnicode() [1/3]
QString QTextDecoder::toUnicode (const char * chars, int len)
Converts the first len bytes in chars to Unicode, returning the result.
If not all characters are used (e.g. if only part of a multi-byte encoding is at the end of the characters), the decoder remembers enough state to continue with the next call to this function.
Definition at line 1644 of file qtextcodec.cpp.
Referenced by QXmlStreamReaderPrivate::getChar_helper(), and QXmlStreamReaderPrivate::startDocument().
 {
     return c->toUnicode(chars, len, &state);
 }
toUnicode() [2/3]
QString QTextDecoder::toUnicode (const QByteArray & ba)
Converts the bytes in the byte array specified by ba to Unicode and returns the result.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1685 of file qtextcodec.cpp.
 {
     return c->toUnicode(ba.constData(), ba.length(), &state);
 }
toUnicode() [3/3]
void QTextDecoder::toUnicode (QString * target, const char * chars, int len)
The converted string is returned in target.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1657 of file qtextcodec.cpp.
 {
     Q_ASSERT(target);
     switch (c->mibEnum()) {
     case 106: // utf8
         static_cast<const QUtf8Codec*>(c)->convertToUnicode(target, chars, len, &state);
         break;
     case 4: { // latin1
         target->resize(len);
         ushort *data = (ushort*)target->data();
         for (int i = len; i >=0; --i)
             data[i] = (uchar) chars[i];
     } break;
     default:
         *target = c->toUnicode(chars, len, &state);
     }
 }
Properties
c
const QTextCodec* QTextDecoder::c private
Definition at line 188 of file qtextcodec.h.
Referenced by QTextCodec::codecForHtml(), and toUnicode().
state
QTextCodec::ConverterState QTextDecoder::state private
Definition at line 189 of file qtextcodec.h.
Referenced by hasFailure(), QTextDecoder(), and toUnicode().
The documentation for this class was generated from the following files:
/src/corelib/codecs/qtextcodec.h
/src/corelib/codecs/qtextcodec.cpp