Qt 4.8: QDeclarativeFlickableVisibleArea Class Reference
QDeclarativeFlickableVisibleArea Class Reference
#include <qdeclarativeflickable_p_p.h>
Signals
void heightRatioChanged (qreal heightRatio)
void widthRatioChanged (qreal widthRatio)
void xPositionChanged (qreal xPosition)
void yPositionChanged (qreal yPosition)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
qreal heightRatio () const
QDeclarativeFlickableVisibleArea (QDeclarativeFlickable *parent=0)
void updateVisible ()
qreal widthRatio () const
qreal xPosition () const
qreal yPosition () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QDeclarativeFlickable * flickable
qreal heightRatio
qreal m_heightRatio
qreal m_widthRatio
qreal m_xPosition
qreal m_yPosition
qreal widthRatio
qreal xPosition
qreal yPosition
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 207 of file qdeclarativeflickable_p_p.h.
Constructors and Destructors
QDeclarativeFlickableVisibleArea()
QDeclarativeFlickableVisibleArea::QDeclarativeFlickableVisibleArea (QDeclarativeFlickable * parent = 0)
Definition at line 91 of file qdeclarativeflickable.cpp.
     : QObject(parent), flickable(parent), m_xPosition(0.), m_widthRatio(0.)
     , m_yPosition(0.), m_heightRatio(0.)
 {
 }
Functions
heightRatio()
qreal QDeclarativeFlickableVisibleArea::heightRatio () const
Referenced by QDeclarativeFlickableVisibleArea().
heightRatioChanged
void QDeclarativeFlickableVisibleArea::heightRatioChanged (qreal heightRatio) signal
Referenced by updateVisible().
updateVisible()
void QDeclarativeFlickableVisibleArea::updateVisible ()
Definition at line 117 of file qdeclarativeflickable.cpp.
Referenced by QDeclarativeFlickablePrivate::updateBeginningEnd().
 {
     QDeclarativeFlickablePrivate *p = static_cast<QDeclarativeFlickablePrivate *>(QGraphicsItemPrivate::get(flickable));
     bool changeX = false;
     bool changeY = false;
     bool changeWidth = false;
     bool changeHeight = false;
     // Vertical
     const qreal viewheight = flickable->height();
     const qreal maxyextent = -flickable->maxYExtent() + flickable->minYExtent();
     qreal pagePos = (-p->vData.move.value() + flickable->minYExtent()) / (maxyextent + viewheight);
     qreal pageSize = viewheight / (maxyextent + viewheight);
     if (pageSize != m_heightRatio) {
         m_heightRatio = pageSize;
         changeHeight = true;
     }
     if (pagePos != m_yPosition) {
         m_yPosition = pagePos;
         changeY = true;
     }
     // Horizontal
     const qreal viewwidth = flickable->width();
     const qreal maxxextent = -flickable->maxXExtent() + flickable->minXExtent();
     pagePos = (-p->hData.move.value() + flickable->minXExtent()) / (maxxextent + viewwidth);
     pageSize = viewwidth / (maxxextent + viewwidth);
     if (pageSize != m_widthRatio) {
         m_widthRatio = pageSize;
         changeWidth = true;
     }
     if (pagePos != m_xPosition) {
         m_xPosition = pagePos;
         changeX = true;
     }
     if (changeX)
         emit xPositionChanged(m_xPosition);
     if (changeY)
         emit yPositionChanged(m_yPosition);
     if (changeWidth)
         emit widthRatioChanged(m_widthRatio);
     if (changeHeight)
         emit heightRatioChanged(m_heightRatio);
 }
widthRatio()
qreal QDeclarativeFlickableVisibleArea::widthRatio () const
Referenced by QDeclarativeFlickableVisibleArea().
widthRatioChanged
void QDeclarativeFlickableVisibleArea::widthRatioChanged (qreal widthRatio) signal
Referenced by updateVisible().
xPosition()
qreal QDeclarativeFlickableVisibleArea::xPosition () const
Referenced by QDeclarativeFlickableVisibleArea().
xPositionChanged
void QDeclarativeFlickableVisibleArea::xPositionChanged (qreal xPosition) signal
Referenced by updateVisible().
yPosition()
qreal QDeclarativeFlickableVisibleArea::yPosition () const
Referenced by QDeclarativeFlickableVisibleArea().
yPositionChanged
void QDeclarativeFlickableVisibleArea::yPositionChanged (qreal yPosition) signal
Referenced by updateVisible().
Properties
flickable
QDeclarativeFlickable* QDeclarativeFlickableVisibleArea::flickable private
Definition at line 233 of file qdeclarativeflickable_p_p.h.
Referenced by updateVisible().
heightRatio
qreal QDeclarativeFlickableVisibleArea::heightRatio private
Definition at line 214 of file qdeclarativeflickable_p_p.h.
m_heightRatio
qreal QDeclarativeFlickableVisibleArea::m_heightRatio private
Definition at line 237 of file qdeclarativeflickable_p_p.h.
Referenced by QDeclarativeFlickableVisibleArea(), and updateVisible().
m_widthRatio
qreal QDeclarativeFlickableVisibleArea::m_widthRatio private
Definition at line 235 of file qdeclarativeflickable_p_p.h.
Referenced by QDeclarativeFlickableVisibleArea(), and updateVisible().
m_xPosition
qreal QDeclarativeFlickableVisibleArea::m_xPosition private
Definition at line 234 of file qdeclarativeflickable_p_p.h.
Referenced by QDeclarativeFlickableVisibleArea(), and updateVisible().
m_yPosition
qreal QDeclarativeFlickableVisibleArea::m_yPosition private
Definition at line 236 of file qdeclarativeflickable_p_p.h.
Referenced by QDeclarativeFlickableVisibleArea(), and updateVisible().
widthRatio
qreal QDeclarativeFlickableVisibleArea::widthRatio private
Definition at line 213 of file qdeclarativeflickable_p_p.h.
xPosition
qreal QDeclarativeFlickableVisibleArea::xPosition private
Definition at line 211 of file qdeclarativeflickable_p_p.h.
yPosition
qreal QDeclarativeFlickableVisibleArea::yPosition private
Definition at line 212 of file qdeclarativeflickable_p_p.h.
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeflickable_p_p.h
/src/declarative/graphicsitems/qdeclarativeflickable.cpp