Qt 4.8: QMacPrintEngine Class Reference
QMacPrintEngine Class Reference
#include <qprintengine_mac_p.h>
Public Functions
bool abort ()
Instructs the print engine to abort the printing process.
bool begin (QPaintDevice *dev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
virtual void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
virtual void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
virtual void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
virtual void drawPath (const QPainterPath &)
The default implementation ignores the path and does nothing.
virtual void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
virtual void drawPoints (const QPointF *p, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRectF *r, int num)
Draws the first rectCount rectangles in the buffer rects.
virtual void drawTextItem (const QPointF &p, const QTextItem &ti)
This function draws the text item textItem at position p.
virtual void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
bool end ()
Reimplement this function to finish painting on the current paint device.
Qt::HANDLE handle () const
int metric (QPaintDevice::PaintDeviceMetric) const
Returns the metric for the given id.
bool newPage ()
Instructs the print engine to start a new page.
QPaintEngine * paintEngine () const
QPrinter::PrinterState printerState () const
Returns the current state of the printer being used by the print engine.
QVariant property (PrintEnginePropertyKey key) const
Returns the print engine's property specified by key.
QMacPrintEngine (QPrinter::PrinterMode mode)
void setProperty (PrintEnginePropertyKey key, const QVariant &value)
Sets the print engine's property specified by key to the given value.
virtual QPaintEngine::Type type () const
Reimplement this function to return the paint engine Type.
void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
virtual void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
virtual void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
virtual void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
virtual void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
virtual void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Public Functions inherited from QPrintEngine
virtual HDC getPrinterDC () const
virtual void releasePrinterDC (HDC) const
virtual ~QPrintEngine ()
Destroys the print engine.
Friends
class QPageSetupDialog
class QPrintDialog
Additional Inherited Members
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Public Types inherited from QPrintEngine
enum PrintEnginePropertyKey {
PPK_CollateCopies, PPK_ColorMode, PPK_Creator, PPK_DocumentName,
PPK_FullPage, PPK_NumberOfCopies, PPK_Orientation, PPK_OutputFileName,
PPK_PageOrder, PPK_PageRect, PPK_PageSize, PPK_PaperRect,
PPK_PaperSource, PPK_PrinterName, PPK_PrinterProgram, PPK_Resolution,
PPK_SelectionOption, PPK_SupportedResolutions, PPK_WindowsPageSize, PPK_FontEmbedding,
PPK_SuppressSystemPrintStatus, PPK_Duplex, PPK_PaperSources, PPK_CustomPaperSize,
PPK_PageMargins, PPK_CopyCount, PPK_SupportsMultipleCopies, PPK_PaperSize = PPK_PageSize,
PPK_CustomBase = 0xff00
}
This enum is used to communicate properties between the print engine and QPrinter.
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 73 of file qprintengine_mac_p.h.
Constructors and Destructors
QMacPrintEngine()
QMacPrintEngine::QMacPrintEngine (QPrinter::PrinterMode mode)
Definition at line 53 of file qprintengine_mac.mm.
                                                          : QPaintEngine(*(new QMacPrintEnginePrivate))
 {
     Q_D(QMacPrintEngine);
     d->mode = mode;
     d->initialize();
 }
Functions
abort()
bool QMacPrintEngine::abort () virtual
Instructs the print engine to abort the printing process.
Returns true if successful; otherwise returns false.
Implements QPrintEngine.
Definition at line 297 of file qprintengine_mac.mm.
Referenced by newPage(), and type().
 {
     Q_D(QMacPrintEngine);
     if (d->state != QPrinter::Active)
         return false;
     bool ret = end();
     d->state = QPrinter::Aborted;
     return ret;
 }
begin()
bool QMacPrintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implements QPaintEngine.
Definition at line 60 of file qprintengine_mac.mm.
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(dev && dev->devType() == QInternal::Printer);
     if (!static_cast<QPrinter *>(dev)->isValid())
     return false;
     if (d->state == QPrinter::Idle && !d->isPrintSessionInitialized()) // Need to reinitialize
         d->initialize();
     d->paintEngine->state = state;
     d->paintEngine->begin(dev);
     Q_ASSERT_X(d->state == QPrinter::Idle, "QMacPrintEngine", "printer already active");
     if (PMSessionValidatePrintSettings(d->session, d->settings, kPMDontWantBoolean) != noErr
         || PMSessionValidatePageFormat(d->session, d->format, kPMDontWantBoolean) != noErr) {
         d->state = QPrinter::Error;
         return false;
     }
     if (!d->outputFilename.isEmpty()) {
         QCFType<CFURLRef> outFile = CFURLCreateWithFileSystemPath(kCFAllocatorSystemDefault,
                                                                   QCFString(d->outputFilename),
                                                                   kCFURLPOSIXPathStyle,
                                                                   false);
         if (PMSessionSetDestination(d->session, d->settings, kPMDestinationFile,
                                     kPMDocumentFormatPDF, outFile) != noErr) {
             qWarning("QMacPrintEngine::begin: Problem setting file [%s]", d->outputFilename.toUtf8().constData());
             return false;
         }
     }
     OSStatus status = noErr;
 #ifndef QT_MAC_USE_COCOA
     status = d->shouldSuppressStatus() ? PMSessionBeginCGDocumentNoDialog(d->session, d->settings, d->format)
                                        : PMSessionBeginCGDocument(d->session, d->settings, d->format);
 #else
     status = PMSessionBeginCGDocumentNoDialog(d->session, d->settings, d->format);
 #endif
     if (status != noErr) {
         d->state = QPrinter::Error;
         return false;
     }
     d->state = QPrinter::Active;
     setActive(true);
     d->newPage_helper();
     return true;
 }
drawEllipse()
void QMacPrintEngine::drawEllipse (const QRectF & rect) virtual
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
The default implementation calls drawPolygon().
Reimplemented from QPaintEngine.
Definition at line 604 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawEllipse(r);
 }
drawImage()
void QMacPrintEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Reimplemented from QPaintEngine.
Definition at line 632 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawImage(r, pm, sr, flags);
 }
drawLines()
void QMacPrintEngine::drawLines (const QLineF * lines, int lineCount) virtual
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 611 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawLines(lines, lineCount);
 }
drawPath()
void QMacPrintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QPaintEngine.
Definition at line 653 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawPath(path);
 }
drawPixmap()
void QMacPrintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngine.
Definition at line 625 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawPixmap(r, pm, sr);
 }
drawPoints()
void QMacPrintEngine::drawPoints (const QPointF * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
Reimplemented from QPaintEngine.
Definition at line 597 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawPoints(points, pointCount);
 }
drawPolygon()
void QMacPrintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngine.
Definition at line 618 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawPolygon(points, pointCount, mode);
 }
drawRects()
void QMacPrintEngine::drawRects (const QRectF * rects, int rectCount) virtual
Draws the first rectCount rectangles in the buffer rects.
The default implementation of this function calls drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngine.
Definition at line 590 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawRects(r, num);
 }
drawTextItem()
void QMacPrintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QPaintEngine.
Definition at line 639 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawTextItem(p, ti);
 }
drawTiledPixmap()
void QMacPrintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QPaintEngine.
Definition at line 646 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     d->paintEngine->drawTiledPixmap(dr, pixmap, sr);
 }
end()
bool QMacPrintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implements QPaintEngine.
Definition at line 111 of file qprintengine_mac.mm.
Referenced by abort().
 {
     Q_D(QMacPrintEngine);
     if (d->state == QPrinter::Aborted)
         return true;  // I was just here a function call ago :)
     if(d->paintEngine->type() == QPaintEngine::CoreGraphics) {
         // We dont need the paint engine to call restoreGraphicsState()
         static_cast<QCoreGraphicsPaintEngine*>(d->paintEngine)->d_func()->stackCount = 0;
         static_cast<QCoreGraphicsPaintEngine*>(d->paintEngine)->d_func()->hd = 0;
     }
     d->paintEngine->end();
     if (d->state != QPrinter::Idle)
     d->releaseSession();
     d->state  = QPrinter::Idle;
     return true;
 }
handle()
Qt::HANDLE QMacPrintEngine::handle () const
Definition at line 134 of file qprintengine_mac.mm.
 {
     QCoreGraphicsPaintEngine *cgEngine = static_cast<QCoreGraphicsPaintEngine*>(paintEngine());
     return cgEngine->d_func()->hd;
 }
metric()
int QMacPrintEngine::metric (QPaintDevice::PaintDeviceMetric id) const virtual
Returns the metric for the given id.
Implements QPrintEngine.
Definition at line 340 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(const QMacPrintEngine);
     int val = 1;
     switch (m) {
     case QPaintDevice::PdmWidth:
         if (d->hasCustomPaperSize) {
             val = qRound(d->customSize.width());
             if (d->hasCustomPageMargins) {
                 val -= qRound(d->leftMargin + d->rightMargin);
             } else {
                 QList<QVariant> margins = property(QPrintEngine::PPK_PageMargins).toList();
                 val -= qRound(margins.at(0).toDouble() + margins.at(2).toDouble());
             }
         } else {
             val = qt_get_PDMWidth(d->format, property(PPK_FullPage).toBool(), d->resolution);
         }
         break;
     case QPaintDevice::PdmHeight:
         if (d->hasCustomPaperSize) {
             val = qRound(d->customSize.height());
             if (d->hasCustomPageMargins) {
                 val -= qRound(d->topMargin + d->bottomMargin);
             } else {
                 QList<QVariant> margins = property(QPrintEngine::PPK_PageMargins).toList();
                 val -= qRound(margins.at(1).toDouble() + margins.at(3).toDouble());
             }
         } else {
             val = qt_get_PDMHeight(d->format, property(PPK_FullPage).toBool(), d->resolution);
         }
         break;
     case QPaintDevice::PdmWidthMM:
         val = metric(QPaintDevice::PdmWidth);
         val = int((val * 254 + 5 * d->resolution.hRes) / (10 * d->resolution.hRes));
         break;
     case QPaintDevice::PdmHeightMM:
         val = metric(QPaintDevice::PdmHeight);
         val = int((val * 254 + 5 * d->resolution.vRes) / (10 * d->resolution.vRes));
         break;
     case QPaintDevice::PdmPhysicalDpiX:
     case QPaintDevice::PdmPhysicalDpiY: {
         PMPrinter printer;
         if(PMSessionGetCurrentPrinter(d->session, &printer) == noErr) {
             PMResolution resolution;
 #ifndef QT_MAC_USE_COCOA
 #  if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
             if (QSysInfo::MacintoshVersion >= QSysInfo::MV_10_5) {
                 PMPrinterGetOutputResolution(printer, d->settings, &resolution);
             } else
 #  endif
             {
                 PMPrinterGetPrinterResolution(printer, kPMCurrentValue, &resolution);
             }
 #else
             PMPrinterGetOutputResolution(printer, d->settings, &resolution);
 #endif
             val = (int)resolution.vRes;
             break;
         }
         //otherwise fall through
     }
     case QPaintDevice::PdmDpiY:
         val = (int)d->resolution.vRes;
         break;
     case QPaintDevice::PdmDpiX:
         val = (int)d->resolution.hRes;
         break;
     case QPaintDevice::PdmNumColors:
         val = (1 << metric(QPaintDevice::PdmDepth));
         break;
     case QPaintDevice::PdmDepth:
         val = 24;
         break;
     default:
         val = 0;
         qWarning("QPrinter::metric: Invalid metric command");
     }
     return val;
 }
newPage()
bool QMacPrintEngine::newPage () virtual
Instructs the print engine to start a new page.
Returns true if the printer was able to create the new page; otherwise returns false.
Implements QPrintEngine.
Definition at line 272 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     Q_ASSERT(d->state == QPrinter::Active);
     OSStatus err =
 #ifndef QT_MAC_USE_COCOA
     d->shouldSuppressStatus() ? PMSessionEndPageNoDialog(d->session)
                               : PMSessionEndPage(d->session);
 #else
     PMSessionEndPageNoDialog(d->session);
 #endif
     if (err != noErr)  {
         if (err == kPMCancel) {
             // User canceled, we need to abort!
             abort();
         } else {
             // Not sure what the problem is...
             qWarning("QMacPrintEngine::newPage: Cannot end current page. %ld", long(err));
             d->state = QPrinter::Error;
         }
         return false;
     }
     return d->newPage_helper();
 }
paintEngine()
QPaintEngine * QMacPrintEngine::paintEngine () const
Definition at line 129 of file qprintengine_mac.mm.
Referenced by handle(), QMacPrintEnginePrivate::initialize(), QMacPrintEnginePrivate::newPage_helper(), type(), and QMacPrintEnginePrivate::~QMacPrintEnginePrivate().
 {
     return d_func()->paintEngine;
 }
printerState()
QPrinter::PrinterState QMacPrintEngine::printerState () const virtual
Returns the current state of the printer being used by the print engine.
Implements QPrintEngine.
Definition at line 267 of file qprintengine_mac.mm.
Referenced by type().
 {
     return d_func()->state;
 }
property()
QVariant QMacPrintEngine::property (PrintEnginePropertyKey key) const virtual
Returns the print engine's property specified by key.
See also
setProperty()
Implements QPrintEngine.
Definition at line 794 of file qprintengine_mac.mm.
Referenced by metric(), and type().
 {
     Q_D(const QMacPrintEngine);
     QVariant ret;
     if (!d->session && d->valueCache.contains(key))
         return *d->valueCache.find(key);
     switch (key) {
     case PPK_CollateCopies:
         ret = false;
         break;
     case PPK_ColorMode:
         ret = QPrinter::Color;
         break;
     case PPK_Creator:
         break;
     case PPK_DocumentName:
         break;
     case PPK_FullPage:
         ret = d->fullPage;
         break;
     case PPK_NumberOfCopies:
         ret = 1;
         break;
     case PPK_CopyCount: {
         UInt32 copies = 1;
         PMGetCopies(d->settings, &copies);
         ret = (uint) copies;
         break;
     }
     case PPK_SupportsMultipleCopies:
         ret = true;
         break;
     case PPK_Orientation:
         PMOrientation orientation;
         PMGetOrientation(d->format, &orientation);
         ret = orientation == kPMPortrait ? QPrinter::Portrait : QPrinter::Landscape;
         break;
     case PPK_OutputFileName:
         ret = d->outputFilename;
         break;
     case PPK_PageOrder:
         break;
     case PPK_PaperSource:
         break;
     case PPK_PageRect: {
         // PageRect is returned in device pixels
         QRect r;
         PMRect macrect, macpaper;
         qreal hRatio = d->resolution.hRes / 72;
         qreal vRatio = d->resolution.vRes / 72;
         if (d->hasCustomPaperSize) {
             r = QRect(0, 0, qRound(d->customSize.width() * hRatio), qRound(d->customSize.height() * vRatio));
             if (d->hasCustomPageMargins) {
                 r.adjust(qRound(d->leftMargin * hRatio), qRound(d->topMargin * vRatio),
                          -qRound(d->rightMargin * hRatio), -qRound(d->bottomMargin * vRatio));
             } else {
                 QList<QVariant> margins = property(QPrintEngine::PPK_PageMargins).toList();
                 r.adjust(qRound(margins.at(0).toDouble() * hRatio),
                          qRound(margins.at(1).toDouble() * vRatio),
                          -qRound(margins.at(2).toDouble() * hRatio),
                          -qRound(margins.at(3).toDouble()) * vRatio);
             }
         } else if (PMGetAdjustedPageRect(d->format, &macrect) == noErr
                    && PMGetAdjustedPaperRect(d->format, &macpaper) == noErr)
         {
             if (d->fullPage || d->hasCustomPageMargins) {
                 r.setCoords(int(macpaper.left * hRatio), int(macpaper.top * vRatio),
                             int(macpaper.right * hRatio), int(macpaper.bottom * vRatio));
                 r.translate(-r.x(), -r.y());
                 if (d->hasCustomPageMargins) {
                     r.adjust(qRound(d->leftMargin * hRatio), qRound(d->topMargin * vRatio),
                              -qRound(d->rightMargin * hRatio), -qRound(d->bottomMargin * vRatio));
                 }
             } else {
                 r.setCoords(int(macrect.left * hRatio), int(macrect.top * vRatio),
                             int(macrect.right * hRatio), int(macrect.bottom * vRatio));
                 r.translate(int(-macpaper.left * hRatio), int(-macpaper.top * vRatio));
             }
         }
         ret = r;
         break; }
     case PPK_PaperSize:
         ret = d->paperSize();
         break;
     case PPK_PaperRect: {
         QRect r;
         PMRect macrect;
         qreal hRatio = d->resolution.hRes / 72;
         qreal vRatio = d->resolution.vRes / 72;
         if (d->hasCustomPaperSize) {
             r = QRect(0, 0, qRound(d->customSize.width() * hRatio), qRound(d->customSize.height() * vRatio));
         } else if (PMGetAdjustedPaperRect(d->format, &macrect) == noErr) {
             r.setCoords(int(macrect.left * hRatio), int(macrect.top * vRatio),
                         int(macrect.right * hRatio), int(macrect.bottom * vRatio));
             r.translate(-r.x(), -r.y());
         }
         ret = r;
         break; }
     case PPK_PrinterName: {
         PMPrinter printer;
         OSStatus status = PMSessionGetCurrentPrinter(d->session, &printer);
         if (status != noErr)
             qWarning("QMacPrintEngine::printerName: Failed getting current PMPrinter: %ld", long(status));
         if (printer)
             ret = QCFString::toQString(PMPrinterGetName(printer));
         break; }
     case PPK_Resolution: {
         ret = d->resolution.hRes;
         break;
     }
     case PPK_SupportedResolutions:
         ret = d->supportedResolutions();
         break;
     case PPK_CustomPaperSize:
         ret = d->customSize;
         break;
     case PPK_PageMargins:
     {
         QList<QVariant> margins;
         if (d->hasCustomPageMargins) {
             margins << d->leftMargin << d->topMargin
                     << d->rightMargin << d->bottomMargin;
         } else {
             PMPaperMargins paperMargins;
             PMPaper paper;
             PMGetPageFormatPaper(d->format, &paper);
             PMPaperGetMargins(paper, &paperMargins);
             margins << paperMargins.left << paperMargins.top
                     << paperMargins.right << paperMargins.bottom;
         }
         ret = margins;
         break;
     }
     default:
         break;
     }
     return ret;
 }
setProperty()
void QMacPrintEngine::setProperty (PrintEnginePropertyKey key, const QVariant & value) virtual
Sets the print engine's property specified by key to the given value.
See also
property()
Implements QPrintEngine.
Definition at line 661 of file qprintengine_mac.mm.
Referenced by type().
 {
     Q_D(QMacPrintEngine);
     d->valueCache.insert(key, value);
     if (!d->session)
         return;
     switch (key) {
     case PPK_CollateCopies:
         break;
     case PPK_ColorMode:
         break;
     case PPK_Creator:
         break;
     case PPK_DocumentName:
         break;
     case PPK_PageOrder:
         break;
     case PPK_PaperSource:
         break;
     case PPK_SelectionOption:
         break;
     case PPK_Resolution:  {
         PMPrinter printer;
         UInt32 count;
         if (PMSessionGetCurrentPrinter(d->session, &printer) != noErr)
             break;
         if (PMPrinterGetPrinterResolutionCount(printer, &count) != noErr)
             break;
         PMResolution resolution = { 0.0, 0.0 };
         PMResolution bestResolution = { 0.0, 0.0 };
         int dpi = value.toInt();
         int bestDistance = INT_MAX;
         for (UInt32 i = 1; i <= count; ++i) {  // Yes, it starts at 1
             if (PMPrinterGetIndexedPrinterResolution(printer, i, &resolution) == noErr) {
                 if (dpi == int(resolution.hRes)) {
                     bestResolution = resolution;
                     break;
                 } else {
                     int distance = qAbs(dpi - int(resolution.hRes));
                     if (distance < bestDistance) {
                         bestDistance = distance;
                         bestResolution = resolution;
                     }
                 }
             }
         }
         PMSessionValidatePageFormat(d->session, d->format, kPMDontWantBoolean);
         break;
     }
     case PPK_FullPage:
         d->fullPage = value.toBool();
         break;
     case PPK_CopyCount: // fallthrough
     case PPK_NumberOfCopies:
         PMSetCopies(d->settings, value.toInt(), false);
         break;
     case PPK_Orientation: {
         if (d->state == QPrinter::Active) {
             qWarning("QMacPrintEngine::setOrientation: Orientation cannot be changed during a print job, ignoring change");
         } else {
             QPrinter::Orientation newOrientation = QPrinter::Orientation(value.toInt());
             if (d->hasCustomPaperSize && (d->orient != newOrientation))
                 d->customSize = QSizeF(d->customSize.height(), d->customSize.width());
             d->orient = newOrientation;
             PMOrientation o = d->orient == QPrinter::Portrait ? kPMPortrait : kPMLandscape;
             PMSetOrientation(d->format, o, false);
             PMSessionValidatePageFormat(d->session, d->format, kPMDontWantBoolean);
         }
         break; }
     case PPK_OutputFileName:
         d->outputFilename = value.toString();
         break;
     case PPK_PaperSize:
         d->setPaperSize(QPrinter::PaperSize(value.toInt()));
         break;
     case PPK_PrinterName: {
         bool printerNameSet = false;
         OSStatus status = noErr;
         QCFType<CFArrayRef> printerList;
         status = PMServerCreatePrinterList(kPMServerLocal, &printerList);
         if (status == noErr) {
             CFIndex count = CFArrayGetCount(printerList);
             for (CFIndex i=0; i<count; ++i) {
                 PMPrinter printer = static_cast<PMPrinter>(const_cast<void *>(CFArrayGetValueAtIndex(printerList, i)));
                 QString name = QCFString::toQString(PMPrinterGetName(printer));
                 if (name == value.toString()) {
                     status = PMSessionSetCurrentPMPrinter(d->session, printer);
                     printerNameSet = true;
                     break;
                 }
             }
         }
         if (status != noErr)
             qWarning("QMacPrintEngine::setPrinterName: Error setting printer: %ld", long(status));
     if (!printerNameSet) {
             qWarning("QMacPrintEngine::setPrinterName: Failed to set printer named '%s'.", qPrintable(value.toString()));
             d->releaseSession();
             d->state = QPrinter::Idle;
         }
         break; }
     case PPK_SuppressSystemPrintStatus:
         d->suppressStatus = value.toBool();
         break;
     case PPK_CustomPaperSize:
     {
         PMOrientation orientation;
         PMGetOrientation(d->format, &orientation);
         d->customSize = value.toSizeF();
         if (orientation != kPMPortrait)
             d->customSize = QSizeF(d->customSize.height(), d->customSize.width());
         d->setPaperSize(QPrinter::Custom);
         break;
     }
     case PPK_PageMargins:
     {
         QList<QVariant> margins(value.toList());
         Q_ASSERT(margins.size() == 4);
         d->leftMargin = margins.at(0).toDouble();
         d->topMargin = margins.at(1).toDouble();
         d->rightMargin = margins.at(2).toDouble();
         d->bottomMargin = margins.at(3).toDouble();
         d->hasCustomPageMargins = true;
         break;
     }
     default:
         break;
     }
 }
type()
virtual QPaintEngine::Type QMacPrintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 83 of file qprintengine_mac_p.h.
 { return QPaintEngine::MacPrinter; }
updateState()
void QMacPrintEngine::updateState (const QPaintEngineState & state) virtual
Reimplement this function to update the state of a paint engine.
When implemented, this function is responsible for checking the paint engine's current state and update the properties that are changed. Use the QPaintEngineState::state() function to find out which properties that must be updated, then use the corresponding GetFunction{get function} to retrieve the current values for the given properties.
See also
QPaintEngineState
Implements QPaintEngine.
Definition at line 585 of file qprintengine_mac.mm.
Referenced by type().
 {
     d_func()->paintEngine->updateState(state);
 }
Friends and Related Functions
QPageSetupDialog
friend class QPageSetupDialog friend
Definition at line 113 of file qprintengine_mac_p.h.
QPrintDialog
friend class QPrintDialog friend
Definition at line 112 of file qprintengine_mac_p.h.
The documentation for this class was generated from the following files:
/src/gui/painting/qprintengine_mac_p.h
/src/gui/painting/qprintengine_mac.mm