Qt 4.8: QAbstractSocketEngine Class Reference
QAbstractSocketEngine Class Reference abstract
#include <qabstractsocketengine_p.h>
Public Types
enum SocketOption {
NonBlockingSocketOption, BroadcastSocketOption, ReceiveBufferSocketOption, SendBufferSocketOption,
AddressReusable, BindExclusively, ReceiveOutOfBandData, LowDelayOption,
KeepAliveOption, MulticastTtlOption, MulticastLoopbackOption
}
Public Slots
void connectionNotification ()
void exceptionNotification ()
void proxyAuthenticationRequired (const QNetworkProxy &proxy, QAuthenticator *authenticator)
void readNotification ()
void writeNotification ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
virtual int accept ()=0
virtual bool bind (const QHostAddress &address, quint16 port)=0
virtual qint64 bytesAvailable () const =0
virtual qint64 bytesToWrite () const =0
virtual void close ()=0
virtual bool connectToHost (const QHostAddress &address, quint16 port)=0
virtual bool connectToHostByName (const QString &name, quint16 port)=0
QAbstractSocket::SocketError error () const
QString errorString () const
virtual bool hasPendingDatagrams () const =0
virtual bool initialize (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol=QAbstractSocket::IPv4Protocol)=0
virtual bool initialize (int socketDescriptor, QAbstractSocket::SocketState socketState=QAbstractSocket::ConnectedState)=0
virtual bool isExceptionNotificationEnabled () const =0
virtual bool isReadNotificationEnabled () const =0
virtual bool isValid () const =0
virtual bool isWriteNotificationEnabled () const =0
virtual bool joinMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &iface)=0
virtual bool leaveMulticastGroup (const QHostAddress &groupAddress, const QNetworkInterface &iface)=0
virtual bool listen ()=0
QHostAddress localAddress () const
quint16 localPort () const
virtual QNetworkInterface multicastInterface () const =0
virtual int option (SocketOption option) const =0
QHostAddress peerAddress () const
quint16 peerPort () const
virtual qint64 pendingDatagramSize () const =0
QAbstractSocket::NetworkLayerProtocol protocol () const
QAbstractSocketEngine (QObject *parent=0)
virtual qint64 read (char *data, qint64 maxlen)=0
virtual qint64 readDatagram (char *data, qint64 maxlen, QHostAddress *addr=0, quint16 *port=0)=0
virtual void setExceptionNotificationEnabled (bool enable)=0
virtual bool setMulticastInterface (const QNetworkInterface &iface)=0
virtual bool setOption (SocketOption option, int value)=0
virtual void setReadNotificationEnabled (bool enable)=0
void setReceiver (QAbstractSocketEngineReceiver *receiver)
virtual void setWriteNotificationEnabled (bool enable)=0
virtual int socketDescriptor () const =0
QAbstractSocket::SocketType socketType () const
QAbstractSocket::SocketState state () const
virtual bool waitForRead (int msecs=30000, bool *timedOut=0)=0
virtual bool waitForReadOrWrite (bool *readyToRead, bool *readyToWrite, bool checkRead, bool checkWrite, int msecs=30000, bool *timedOut=0)=0
virtual bool waitForWrite (int msecs=30000, bool *timedOut=0)=0
virtual qint64 write (const char *data, qint64 len)=0
virtual qint64 writeDatagram (const char *data, qint64 len, const QHostAddress &addr, quint16 port)=0
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QAbstractSocketEngine * createSocketEngine (QAbstractSocket::SocketType socketType, const QNetworkProxy &, QObject *parent)
static QAbstractSocketEngine * createSocketEngine (int socketDescripter, QObject *parent)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
QAbstractSocketEngine (QAbstractSocketEnginePrivate &dd, QObject *parent=0)
void setError (QAbstractSocket::SocketError error, const QString &errorString) const
void setLocalAddress (const QHostAddress &address)
void setLocalPort (quint16 port)
void setPeerAddress (const QHostAddress &address)
void setPeerPort (quint16 port)
void setProtocol (QAbstractSocket::NetworkLayerProtocol protocol)
void setSocketType (QAbstractSocket::SocketType socketType)
void setState (QAbstractSocket::SocketState state)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 81 of file qabstractsocketengine_p.h.
Enumerations
SocketOption
enum QAbstractSocketEngine::SocketOption
Enumerator
NonBlockingSocketOption
BroadcastSocketOption
ReceiveBufferSocketOption
SendBufferSocketOption
AddressReusable
BindExclusively
ReceiveOutOfBandData
LowDelayOption
KeepAliveOption
MulticastTtlOption
MulticastLoopbackOption
Definition at line 91 of file qabstractsocketengine_p.h.
                       {
         NonBlockingSocketOption,
         BroadcastSocketOption,
         ReceiveBufferSocketOption,
         SendBufferSocketOption,
         AddressReusable,
         BindExclusively,
         ReceiveOutOfBandData,
         LowDelayOption,
         KeepAliveOption,
         MulticastTtlOption,
         MulticastLoopbackOption
     };
Constructors and Destructors
QAbstractSocketEngine() [1/2]
QAbstractSocketEngine::QAbstractSocketEngine (QObject * parent = 0)
Definition at line 92 of file qabstractsocketengine.cpp.
     : QObject(*new QAbstractSocketEnginePrivate(), parent)
 {
 }
QAbstractSocketEngine() [2/2]
QAbstractSocketEngine::QAbstractSocketEngine (QAbstractSocketEnginePrivate & dd, QObject * parent = 0) protected
Definition at line 97 of file qabstractsocketengine.cpp.
     : QObject(dd, parent)
 {
 }
Functions
accept()
virtual int QAbstractSocketEngine::accept () pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QTcpServerPrivate::readNotification().
bind()
virtual bool QAbstractSocketEngine::bind (const QHostAddress & address, quint16 port) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
bytesAvailable()
virtual qint64 QAbstractSocketEngine::bytesAvailable () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::readFromSocket().
bytesToWrite()
virtual qint64 QAbstractSocketEngine::bytesToWrite () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::canWriteNotification(), and QAbstractSocketPrivate::flush().
close()
virtual void QAbstractSocketEngine::close () pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::_q_forceDisconnect(), and QAbstractSocketPrivate::resetSocketLayer().
connectionNotification
void QAbstractSocketEngine::connectionNotification () slot
Definition at line 183 of file qabstractsocketengine.cpp.
Referenced by QNativeSocketEngine::connectionNotification(), and QHttpSocketEngine::emitPendingConnectionNotification().
 {
     if (QAbstractSocketEngineReceiver *receiver = d_func()->receiver)
         receiver->connectionNotification();
 }
connectToHost()
virtual bool QAbstractSocketEngine::connectToHost (const QHostAddress & address, quint16 port) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress().
connectToHostByName()
virtual bool QAbstractSocketEngine::connectToHostByName (const QString & name, quint16 port) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::startConnectingByName().
createSocketEngine() [1/2]
QAbstractSocketEngine * QAbstractSocketEngine::createSocketEngine (QAbstractSocket::SocketType socketType, const QNetworkProxy & proxy, QObject * parent) static
Definition at line 102 of file qabstractsocketengine.cpp.
Referenced by createSocketEngine(), QAbstractSocketPrivate::initSocketLayer(), QTcpServer::listen(), QTcpServer::setSocketDescriptor(), and QAbstractSocket::setSocketDescriptor().
 {
 #ifndef QT_NO_NETWORKPROXY
     // proxy type must have been resolved by now
     if (proxy.type() == QNetworkProxy::DefaultProxy)
         return 0;
 #endif
     QMutexLocker locker(&socketHandlers()->mutex);
     for (int i = 0; i < socketHandlers()->size(); i++) {
         if (QAbstractSocketEngine *ret = socketHandlers()->at(i)->createSocketEngine(socketType, proxy, parent))
             return ret;
     }
 #ifndef QT_NO_NETWORKPROXY
     // only NoProxy can have reached here
     if (proxy.type() != QNetworkProxy::NoProxy)
         return 0;
 #endif
 #ifdef Q_OS_SYMBIAN
     return new QSymbianSocketEngine(parent);
 #else
     return new QNativeSocketEngine(parent);
 #endif
 }
createSocketEngine() [2/2]
QAbstractSocketEngine * QAbstractSocketEngine::createSocketEngine (int socketDescripter, QObject * parent) static
Definition at line 129 of file qabstractsocketengine.cpp.
 {
     QMutexLocker locker(&socketHandlers()->mutex);
     for (int i = 0; i < socketHandlers()->size(); i++) {
         if (QAbstractSocketEngine *ret = socketHandlers()->at(i)->createSocketEngine(socketDescripter, parent))
             return ret;
     }
 #ifdef Q_OS_SYMBIAN
     return new QSymbianSocketEngine(parent);
 #else
     return new QNativeSocketEngine(parent);
 #endif
 }
error()
QAbstractSocket::SocketError QAbstractSocketEngine::error () const
Definition at line 143 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QAbstractSocketPrivate::_q_testConnection(), QAbstractSocketPrivate::flush(), QSocks5SocketEngine::initialize(), QHttpSocketEngine::initialize(), QAbstractSocketPrivate::initSocketLayer(), QAbstractSocketPrivate::readFromSocket(), setError(), QHttpSocketEngine::slotSocketError(), and QAbstractSocketPrivate::startConnectingByName().
 {
     return d_func()->socketError;
 }
errorString()
QString QAbstractSocketEngine::errorString () const
Definition at line 148 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QAbstractSocketPrivate::flush(), QAbstractSocketPrivate::initSocketLayer(), QAbstractSocketPrivate::readFromSocket(), setError(), and QAbstractSocketPrivate::startConnectingByName().
 {
     return d_func()->socketErrorString;
 }
exceptionNotification
void QAbstractSocketEngine::exceptionNotification () slot
Definition at line 177 of file qabstractsocketengine.cpp.
 {
     if (QAbstractSocketEngineReceiver *receiver = d_func()->receiver)
         receiver->exceptionNotification();
 }
hasPendingDatagrams()
virtual bool QAbstractSocketEngine::hasPendingDatagrams () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::canReadNotification().
initialize() [1/2]
virtual bool QAbstractSocketEngine::initialize (QAbstractSocket::SocketType type, QAbstractSocket::NetworkLayerProtocol protocol = QAbstractSocket::IPv4Protocol) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::initSocketLayer().
initialize() [2/2]
virtual bool QAbstractSocketEngine::initialize (int socketDescriptor, QAbstractSocket::SocketState socketState = QAbstractSocket::ConnectedState) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
isExceptionNotificationEnabled()
virtual bool QAbstractSocketEngine::isExceptionNotificationEnabled () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::pauseSocketNotifiers().
isReadNotificationEnabled()
virtual bool QAbstractSocketEngine::isReadNotificationEnabled () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::canReadNotification(), QAbstractSocketPrivate::pauseSocketNotifiers(), and QTcpServerPrivate::readNotification().
isValid()
virtual bool QAbstractSocketEngine::isValid () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::_q_forceDisconnect(), QUdpSocketPrivate::doEnsureInitialized(), QAbstractSocketPrivate::flush(), and QAbstractSocketPrivate::readFromSocket().
isWriteNotificationEnabled()
virtual bool QAbstractSocketEngine::isWriteNotificationEnabled () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::canWriteNotification(), QAbstractSocketPrivate::flush(), and QAbstractSocketPrivate::pauseSocketNotifiers().
joinMulticastGroup()
virtual bool QAbstractSocketEngine::joinMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & iface) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
leaveMulticastGroup()
virtual bool QAbstractSocketEngine::leaveMulticastGroup (const QHostAddress & groupAddress, const QNetworkInterface & iface) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
listen()
virtual bool QAbstractSocketEngine::listen () pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
localAddress()
QHostAddress QAbstractSocketEngine::localAddress () const
Definition at line 228 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::fetchConnectionParameters().
 {
     return d_func()->localAddress;
 }
localPort()
quint16 QAbstractSocketEngine::localPort () const
Definition at line 238 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::fetchConnectionParameters().
 {
     return d_func()->localPort;
 }
multicastInterface()
virtual QNetworkInterface QAbstractSocketEngine::multicastInterface () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
option()
virtual int QAbstractSocketEngine::option (SocketOption option) const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
peerAddress()
QHostAddress QAbstractSocketEngine::peerAddress () const
Definition at line 248 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::fetchConnectionParameters(), and QHttpSocketEngine::slotSocketConnected().
 {
     return d_func()->peerAddress;
 }
peerPort()
quint16 QAbstractSocketEngine::peerPort () const
Definition at line 258 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::fetchConnectionParameters().
 {
     return d_func()->peerPort;
 }
pendingDatagramSize()
virtual qint64 QAbstractSocketEngine::pendingDatagramSize () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
protocol()
QAbstractSocket::NetworkLayerProtocol QAbstractSocketEngine::protocol () const
Definition at line 218 of file qabstractsocketengine.cpp.
Referenced by QSocks5SocketEngine::initialize(), QNativeSocketEngine::initialize(), and setProtocol().
 {
     return d_func()->socketProtocol;
 }
proxyAuthenticationRequired
void QAbstractSocketEngine::proxyAuthenticationRequired (const QNetworkProxy & proxy, QAuthenticator * authenticator) slot
Definition at line 190 of file qabstractsocketengine.cpp.
Referenced by QHttpSocketEngine::slotSocketReadNotification().
 {
     if (QAbstractSocketEngineReceiver *receiver = d_func()->receiver)
         receiver->proxyAuthenticationRequired(proxy, authenticator);
 }
read()
virtual qint64 QAbstractSocketEngine::read (char * data, qint64 maxlen) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::readFromSocket().
readDatagram()
virtual qint64 QAbstractSocketEngine::readDatagram (char * data, qint64 maxlen, QHostAddress * addr = 0, quint16 * port = 0) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
readNotification
void QAbstractSocketEngine::readNotification () slot
Definition at line 165 of file qabstractsocketengine.cpp.
Referenced by QHttpSocketEngine::emitPendingReadNotification().
 {
     if (QAbstractSocketEngineReceiver *receiver = d_func()->receiver)
         receiver->readNotification();
 }
setError()
void QAbstractSocketEngine::setError (QAbstractSocket::SocketError error, const QString & errorString) const protected
Definition at line 153 of file qabstractsocketengine.cpp.
Referenced by QSocks5SocketEngine::bind(), QSocks5SocketEngine::joinMulticastGroup(), QHttpSocketEngine::joinMulticastGroup(), QSocks5SocketEngine::leaveMulticastGroup(), QHttpSocketEngine::leaveMulticastGroup(), QSocks5SocketEngine::read(), QHttpSocketEngine::read(), QSocks5SocketEngine::setMulticastInterface(), QHttpSocketEngine::setMulticastInterface(), QHttpSocketEngine::slotSocketError(), QHttpSocketEngine::slotSocketReadNotification(), QSocks5SocketEngine::waitForRead(), QHttpSocketEngine::waitForRead(), and QSocks5SocketEngine::writeDatagram().
 {
     Q_D(const QAbstractSocketEngine);
     d->socketError = error;
     d->socketErrorString = errorString;
 }
setExceptionNotificationEnabled()
virtual void QAbstractSocketEngine::setExceptionNotificationEnabled (bool enable) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::pauseSocketNotifiers(), and QAbstractSocketPrivate::resumeSocketNotifiers().
setLocalAddress()
void QAbstractSocketEngine::setLocalAddress (const QHostAddress & address) protected
Definition at line 233 of file qabstractsocketengine.cpp.
Referenced by QHttpSocketEngine::slotSocketReadNotification().
 {
     d_func()->localAddress = address;
 }
setLocalPort()
void QAbstractSocketEngine::setLocalPort (quint16 port) protected
Definition at line 243 of file qabstractsocketengine.cpp.
Referenced by QHttpSocketEngine::slotSocketReadNotification().
 {
     d_func()->localPort = port;
 }
setMulticastInterface()
virtual bool QAbstractSocketEngine::setMulticastInterface (const QNetworkInterface & iface) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
setOption()
virtual bool QAbstractSocketEngine::setOption (SocketOption option, int value) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
setPeerAddress()
void QAbstractSocketEngine::setPeerAddress (const QHostAddress & address) protected
Definition at line 253 of file qabstractsocketengine.cpp.
Referenced by QSocks5SocketEngine::connectToHost(), QHttpSocketEngine::connectToHost(), QSocks5SocketEngine::connectToHostByName(), and QHttpSocketEngine::connectToHostByName().
 {
    d_func()->peerAddress = address;
 }
setPeerPort()
void QAbstractSocketEngine::setPeerPort (quint16 port) protected
Definition at line 263 of file qabstractsocketengine.cpp.
Referenced by QSocks5SocketEngine::connectToHost(), QHttpSocketEngine::connectToHost(), QSocks5SocketEngine::connectToHostByName(), and QHttpSocketEngine::connectToHostByName().
 {
     d_func()->peerPort = port;
 }
setProtocol()
void QAbstractSocketEngine::setProtocol (QAbstractSocket::NetworkLayerProtocol protocol) protected
Definition at line 223 of file qabstractsocketengine.cpp.
Referenced by QHttpSocketEngine::initialize().
 {
     d_func()->socketProtocol = protocol;
 }
setReadNotificationEnabled()
virtual void QAbstractSocketEngine::setReadNotificationEnabled (bool enable) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::canReadNotification(), QAbstractSocketPrivate::fetchConnectionParameters(), QAbstractSocketPrivate::pauseSocketNotifiers(), QTcpServerPrivate::readNotification(), and QAbstractSocketPrivate::resumeSocketNotifiers().
setReceiver()
void QAbstractSocketEngine::setReceiver (QAbstractSocketEngineReceiver * receiver)
Definition at line 160 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::initSocketLayer().
 {
     d_func()->receiver = receiver;
 }
setSocketType()
void QAbstractSocketEngine::setSocketType (QAbstractSocket::SocketType socketType) protected
Definition at line 213 of file qabstractsocketengine.cpp.
Referenced by QHttpSocketEngine::initialize().
 {
     d_func()->socketType = socketType;
 }
setState()
void QAbstractSocketEngine::setState (QAbstractSocket::SocketState state) protected
Definition at line 203 of file qabstractsocketengine.cpp.
Referenced by QSocks5SocketEngine::bind(), QSocks5SocketEngine::connectInternal(), QHttpSocketEngine::connectInternal(), QSocks5SocketEngine::read(), QHttpSocketEngine::read(), QHttpSocketEngine::slotSocketReadNotification(), QNativeSocketEngine::waitForReadOrWrite(), and QNativeSocketEngine::waitForWrite().
 {
     d_func()->socketState = state;
 }
setWriteNotificationEnabled()
virtual void QAbstractSocketEngine::setWriteNotificationEnabled (bool enable) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::_q_abortConnectionAttempt(), QAbstractSocketPrivate::_q_connectToNextAddress(), QAbstractSocketPrivate::canWriteNotification(), QAbstractSocketPrivate::fetchConnectionParameters(), QAbstractSocketPrivate::flush(), QAbstractSocketPrivate::pauseSocketNotifiers(), and QAbstractSocketPrivate::resumeSocketNotifiers().
socketDescriptor()
virtual int QAbstractSocketEngine::socketDescriptor () const pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QAbstractSocketPrivate::fetchConnectionParameters(), and QAbstractSocketPrivate::startConnectingByName().
socketType()
QAbstractSocket::SocketType QAbstractSocketEngine::socketType () const
Definition at line 208 of file qabstractsocketengine.cpp.
Referenced by QSocks5SocketEngine::bind(), QSocks5SocketEngine::connectInternal(), QNativeSocketEngine::initialize(), and setSocketType().
 {
     return d_func()->socketType;
 }
state()
QAbstractSocket::SocketState QAbstractSocketEngine::state () const
Definition at line 198 of file qabstractsocketengine.cpp.
Referenced by QAbstractSocketPrivate::_q_connectToNextAddress(), QSocks5SocketEnginePrivate::_q_controlSocketStateChanged(), QAbstractSocketPrivate::_q_testConnection(), QNativeSocketEngine::connectionNotification(), setState(), QAbstractSocketPrivate::startConnectingByName(), QNativeSocketEngine::waitForRead(), QNativeSocketEngine::waitForReadOrWrite(), and QNativeSocketEngine::waitForWrite().
 {
     return d_func()->socketState;
 }
waitForRead()
virtual bool QAbstractSocketEngine::waitForRead (int msecs = 30000, bool * timedOut = 0) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
waitForReadOrWrite()
virtual bool QAbstractSocketEngine::waitForReadOrWrite (bool * readyToRead, bool * readyToWrite, bool checkRead, bool checkWrite, int msecs = 30000, bool * timedOut = 0) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
waitForWrite()
virtual bool QAbstractSocketEngine::waitForWrite (int msecs = 30000, bool * timedOut = 0) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
write()
virtual qint64 QAbstractSocketEngine::write (const char * data, qint64 len) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
Referenced by QAbstractSocketPrivate::flush().
writeDatagram()
virtual qint64 QAbstractSocketEngine::writeDatagram (const char * data, qint64 len, const QHostAddress & addr, quint16 port) pure virtual
Implemented in QNativeSocketEngine, QHttpSocketEngine, and QSocks5SocketEngine.
writeNotification
void QAbstractSocketEngine::writeNotification () slot
Definition at line 171 of file qabstractsocketengine.cpp.
Referenced by QHttpSocketEngine::emitPendingWriteNotification().
 {
     if (QAbstractSocketEngineReceiver *receiver = d_func()->receiver)
         receiver->writeNotification();
 }
The documentation for this class was generated from the following files:
/src/network/socket/qabstractsocketengine_p.h
/src/network/socket/qabstractsocketengine.cpp