Qt 4.8: PvrEglWindowSurface Class Reference
PvrEglWindowSurface Class Reference
#include <pvreglwindowsurface.h>
Public Functions
void flush (QWidget *widget, const QRegion &region, const QPoint &offset)
Flushes the given region from the specified widget onto the screen.
QImage image () const
Implement this function to return an image of the top-level window.
bool isValid () const
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
QString key () const
Implement this function to return a string that uniquely identifies the class of this surface.
bool move (const QPoint &offset)
Move the surface with the given offset.
long nativeDrawable () const
QPaintDevice * paintDevice ()
Implement this function to return the appropriate paint device.
QByteArray permanentState () const
Implement this function to return the data required for creating a server-side representation of the surface.
PvrEglWindowSurface (QWidget *widget, PvrEglScreen *screen, int screenNum)
PvrEglWindowSurface ()
void setDirectRegion (const QRegion &region, int id)
void setGeometry (const QRect &rect)
Sets the currently allocated area to be the given rect.
void setPermanentState (const QByteArray &state)
Implement this function to attach a server-side surface instance to the corresponding client side instance using the given data.
~PvrEglWindowSurface ()
Public Functions inherited from QWSGLWindowSurface
QGLContext * context () const
Returns the QGLContext of the window surface.
QWSGLWindowSurface (QWidget *widget)
Constructs an empty QWSGLWindowSurface for the given top-level window.
QWSGLWindowSurface ()
Constructs an empty QWSGLWindowSurface.
void setContext (QGLContext *context)
Sets the QGLContext for this window surface to context.
~QWSGLWindowSurface ()
Destroys the QWSGLWindowSurface object and frees any allocated resources.
Public Functions inherited from QWSWindowSurface
virtual void beginPaint (const QRegion &)
This function is called before painting onto the surface begins, with the region in which the painting will occur.
const QRegion clipRegion () const
Returns the region currently visible on the screen.
virtual void endPaint (const QRegion &)
This function is called after painting onto the surface has ended, with the region in which the painting was performed.
bool isBuffered () const
Returns true if the QWSWindowSurface::Buffered is set; otherwise returns false.
bool isOpaque () const
Returns true if the QWSWindowSurface::Opaque is set; otherwise returns false.
bool isRegionReserved () const
Returns true if the QWSWindowSurface::RegionReserved is set; otherwise returns false.
virtual bool lock (int timeout=-1)
virtual QRegion move (const QPoint &offset, const QRegion &newClip)
Move the surface with the given offset.
virtual QPoint painterOffset () const
Returns the offset to be used when painting.
QWSWindowSurface ()
Constructs an empty surface.
QWSWindowSurface (QWidget *widget)
Constructs an empty surface for the given top-level widget.
virtual void releaseSurface ()
void setClipRegion (const QRegion &)
Sets the region currently visible on the screen to be the given clip region.
virtual void setGeometry (const QRect &rect, const QRegion &mask)
virtual void setTransientState (const QByteArray &state)
SurfaceFlags surfaceFlags () const
Returns the surface flags describing the contents of this surface.
virtual QByteArray transientState () const
virtual void unlock ()
int winId () const
~QWSWindowSurface ()
Public Functions inherited from QWindowSurface
virtual QImage * buffer (const QWidget *widget)
Returns a QImage pointer which represents the actual buffer the widget is drawn into or 0 if this is unavailable.
virtual WindowSurfaceFeatures features () const
QRect geometry () const
Returns the currently allocated area on the screen.
virtual QPixmap grabWidget (const QWidget *widget, const QRect &rectangle=QRect()) const
Returns a QPixmap generated from the part of the backing store corresponding to widget.
bool hasFeature (WindowSurfaceFeature feature) const
virtual QPoint offset (const QWidget *widget) const
Returns the offset of widget in the coordinates of this window surface.
QWindowSurface (QWidget *window, bool setDefaultSurface=true)
Constructs an empty surface for the given top-level window.
QRect rect (const QWidget *widget) const
Returns the rectangle for widget in the coordinates of this window surface.
virtual bool scroll (const QRegion &area, int dx, int dy)
Scrolls the given area dx pixels to the right and dy downward; both dx and dy may be negative.
void setStaticContents (const QRegion &region)
QRegion staticContents () const
QWidget * window () const
Returns a pointer to the top-level window associated with this surface.
virtual ~QWindowSurface ()
Destroys this surface.
Private Functions
void transformRects (PvrQwsRect *rects, int count) const
Properties
PvrQwsDrawable * drawable
QPaintDevice * pdevice
PvrEglScreen * screen
QWidget * widget
Additional Inherited Members
Public Types inherited from QWSWindowSurface
enum SurfaceFlag { RegionReserved = 0x1, Buffered = 0x2, Opaque = 0x4 }
This enum is used to describe the window surface's contents.
Public Types inherited from QWindowSurface
enum WindowSurfaceFeature { PartialUpdates = 0x00000001, PreservedContents = 0x00000002, StaticContents = 0x00000004, AllFeatures = 0xffffffff }
Protected Functions inherited from QWSWindowSurface
void setSurfaceFlags (SurfaceFlags type)
Sets the surface flags describing the contents of this surface, to be the given flags.
void setWinId (int id)
Protected Functions inherited from QWindowSurface
bool hasStaticContents () const
Detailed Description
Definition at line 50 of file pvreglwindowsurface.h.
Constructors and Destructors
PvrEglWindowSurface() [1/2]
PvrEglWindowSurface::PvrEglWindowSurface (QWidget * widget, PvrEglScreen * screen, int screenNum)
Definition at line 49 of file pvreglwindowsurface.cpp.
     : QWSGLWindowSurface(widget)
 {
     setSurfaceFlags(QWSWindowSurface::Opaque);
     this->widget = widget;
     this->screen = screen;
     this->pdevice = 0;
     QPoint pos = offset(widget);
     QSize size = widget->size();
     PvrQwsRect pvrRect;
     pvrRect.x = pos.x();
     pvrRect.y = pos.y();
     pvrRect.width = size.width();
     pvrRect.height = size.height();
     transformRects(&pvrRect, 1);
     // Try to recover a previous PvrQwsDrawable object for the widget
     // if there is one.  This can happen when a PvrEglWindowSurface
     // is created for a widget, bound to a EGLSurface, and then destroyed.
     // When a new PvrEglWindowSurface is created for the widget, it will
     // pick up the previous PvrQwsDrawable if the EGLSurface has not been
     // destroyed in the meantime.
     drawable = pvrQwsFetchWindow((long)widget);
     if (drawable)
         pvrQwsSetGeometry(drawable, &pvrRect);
     else
         drawable = pvrQwsCreateWindow(screenNum, (long)widget, &pvrRect);
     pvrQwsSetRotation(drawable, screen->transformation());
 }
PvrEglWindowSurface() [2/2]
PvrEglWindowSurface::PvrEglWindowSurface ()
Definition at line 82 of file pvreglwindowsurface.cpp.
     : QWSGLWindowSurface()
 {
     setSurfaceFlags(QWSWindowSurface::Opaque);
     drawable = 0;
     widget = 0;
     screen = 0;
     pdevice = 0;
 }
~PvrEglWindowSurface()
PvrEglWindowSurface::~PvrEglWindowSurface ()
Definition at line 92 of file pvreglwindowsurface.cpp.
 {
     // Release the PvrQwsDrawable.  If it is bound to an EGLSurface,
     // then it will stay around until a new PvrEglWindowSurface is
     // created for the widget.  If it is not bound to an EGLSurface,
     // it will be destroyed immediately.
     if (drawable && pvrQwsReleaseWindow(drawable))
         pvrQwsDestroyDrawable(drawable);
     delete pdevice;
 }
Functions
flush()
void PvrEglWindowSurface::flush (QWidget * widget, const QRegion & region, const QPoint & offset) virtual
Flushes the given region from the specified widget onto the screen.
Note that the offset parameter is currently unused.
Reimplemented from QWSWindowSurface.
Definition at line 153 of file pvreglwindowsurface.cpp.
Referenced by key(), and setPermanentState().
 {
     // The GL paint engine is responsible for the swapBuffers() call.
     // If we were to call the base class's implementation of flush()
     // then it would fetch the image() and manually blit it to the
     // screeen instead of using the fast PVR2D blit.
     Q_UNUSED(widget);
     Q_UNUSED(region);
     Q_UNUSED(offset);
 }
image()
QImage PvrEglWindowSurface::image () const virtual
Implement this function to return an image of the top-level window.
See also
geometry()
Implements QWSWindowSurface.
Definition at line 164 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     if (drawable) {
         PvrQwsRect pvrRect;
         pvrQwsGetGeometry(drawable, &pvrRect);
         void *data = pvrQwsGetRenderBuffer(drawable);
         if (data) {
             return QImage((uchar *)data, pvrRect.width, pvrRect.height,
                           pvrQwsGetStride(drawable), screen->pixelFormat());
         }
     }
     return QImage(16, 16, screen->pixelFormat());
 }
isValid()
bool PvrEglWindowSurface::isValid () const virtual
Implement this function to return true if the surface is a valid surface for the given top-level window; otherwise return false.
Since
4.3
See also
window(), key()
Implements QWSWindowSurface.
Definition at line 104 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     return (widget != 0);
 }
key()
QString PvrEglWindowSurface::key () const inline virtual
Implement this function to return a string that uniquely identifies the class of this surface.
See also
window(), isValid()
Implements QWSWindowSurface.
Definition at line 57 of file pvreglwindowsurface.h.
 { return QLatin1String("PvrEgl"); }
move()
bool PvrEglWindowSurface::move (const QPoint & offset) virtual
Move the surface with the given offset.
A subclass may reimplement this function to enable accelerated window move. It must return true if the move was successful and no repaint is necessary, false otherwise.
The default implementation updates the QWindowSurface geometry and returns true if the surface is buffered; false otherwise.
This function is called by the window system on the client instance.
See also
isBuffered()
Reimplemented from QWSWindowSurface.
Definition at line 125 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     QRect rect = geometry().translated(offset);
     if (drawable) {
         PvrQwsRect pvrRect;
         pvrRect.x = rect.x();
         pvrRect.y = rect.y();
         pvrRect.width = rect.width();
         pvrRect.height = rect.height();
         transformRects(&pvrRect, 1);
         pvrQwsSetGeometry(drawable, &pvrRect);
         pvrQwsSetRotation(drawable, screen->transformation());
     }
     return QWSGLWindowSurface::move(offset);
 }
nativeDrawable()
long PvrEglWindowSurface::nativeDrawable () const inline
Definition at line 74 of file pvreglwindowsurface.h.
Referenced by PvrEglScreenSurfaceFunctions::createNativeWindow().
 { return (long)widget; }
paintDevice()
QPaintDevice * PvrEglWindowSurface::paintDevice () virtual
Implement this function to return the appropriate paint device.
Implements QWSWindowSurface.
Definition at line 178 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     return widget;
 }
permanentState()
QByteArray PvrEglWindowSurface::permanentState () const virtual
Implement this function to return the data required for creating a server-side representation of the surface.
Since
4.3
See also
attach()
Reimplemented from QWSWindowSurface.
Definition at line 141 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     // Nothing interesting to pass to the server just yet.
     return QByteArray();
 }
setDirectRegion()
void PvrEglWindowSurface::setDirectRegion (const QRegion & region, int id)
Definition at line 183 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     QWSGLWindowSurface::setDirectRegion(r, id);
     if (!drawable)
         return;
     // Clip the region to the window boundaries in case the child
     // is partially outside the geometry of the parent.
     QWidget *window = widget->window();
     QRegion region = r;
     if (widget != window) {
     QRect rect = window->geometry();
         rect.moveTo(window->mapToGlobal(QPoint(0, 0)));
         region = region.intersect(rect);
     }
     if (region.isEmpty()) {
         pvrQwsClearVisibleRegion(drawable);
     } else if (region.rectCount() == 1) {
         QRect rect = region.boundingRect();
         PvrQwsRect pvrRect;
         pvrRect.x = rect.x();
         pvrRect.y = rect.y();
         pvrRect.width = rect.width();
         pvrRect.height = rect.height();
         transformRects(&pvrRect, 1);
         pvrQwsSetVisibleRegion(drawable, &pvrRect, 1);
         pvrQwsSetRotation(drawable, screen->transformation());
         if (!pvrQwsSwapBuffers(drawable, 1))
             screen->solidFill(QColor(0, 0, 0), region);
     } else {
         QVector<QRect> rects = region.rects();
         PvrQwsRect *pvrRects = new PvrQwsRect [rects.size()];
         for (int index = 0; index < rects.size(); ++index) {
             QRect rect = rects[index];
             pvrRects[index].x = rect.x();
             pvrRects[index].y = rect.y();
             pvrRects[index].width = rect.width();
             pvrRects[index].height = rect.height();
         }
         transformRects(pvrRects, rects.size());
         pvrQwsSetVisibleRegion(drawable, pvrRects, rects.size());
         pvrQwsSetRotation(drawable, screen->transformation());
         if (!pvrQwsSwapBuffers(drawable, 1))
             screen->solidFill(QColor(0, 0, 0), region);
         delete [] pvrRects;
     }
 }
setGeometry()
void PvrEglWindowSurface::setGeometry (const QRect & rect) virtual
Sets the currently allocated area to be the given rect.
This function is called whenever area covered by the top-level window changes.
See also
geometry()
Reimplemented from QWSWindowSurface.
Definition at line 109 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     if (drawable) {
         // XXX: adjust for the screen offset.
         PvrQwsRect pvrRect;
         pvrRect.x = rect.x();
         pvrRect.y = rect.y();
         pvrRect.width = rect.width();
         pvrRect.height = rect.height();
         transformRects(&pvrRect, 1);
         pvrQwsSetGeometry(drawable, &pvrRect);
         pvrQwsSetRotation(drawable, screen->transformation());
     }
     QWSGLWindowSurface::setGeometry(rect);
 }
setPermanentState()
void PvrEglWindowSurface::setPermanentState (const QByteArray & data) virtual
Implement this function to attach a server-side surface instance to the corresponding client side instance using the given data.
Since
4.3
Return true if successful; otherwise return false.
See also
data()
Reimplemented from QWSWindowSurface.
Definition at line 147 of file pvreglwindowsurface.cpp.
Referenced by key().
 {
     Q_UNUSED(state);
 }
transformRects()
void PvrEglWindowSurface::transformRects (PvrQwsRect * rects, int count) const private
Definition at line 233 of file pvreglwindowsurface.cpp.
Referenced by move(), setDirectRegion(), and setGeometry().
 {
     switch (screen->transformation()) {
     case 0: break;
     case 90:
     {
         for (int index = 0; index < count; ++index) {
             int x = rects[index].y;
             int y = screen->height() - (rects[index].x + rects[index].width);
             rects[index].x = x;
             rects[index].y = y;
             qSwap(rects[index].width, rects[index].height);
         }
     }
     break;
     case 180:
     {
         for (int index = 0; index < count; ++index) {
             int x = screen->width() - (rects[index].x + rects[index].width);
             int y = screen->height() - (rects[index].y + rects[index].height);
             rects[index].x = x;
             rects[index].y = y;
         }
     }
     break;
     case 270:
     {
         for (int index = 0; index < count; ++index) {
             int x = screen->width() - (rects[index].y + rects[index].height);
             int y = rects[index].x;
             rects[index].x = x;
             rects[index].y = y;
             qSwap(rects[index].width, rects[index].height);
         }
     }
     break;
     }
 }
Properties
drawable
PvrQwsDrawable* PvrEglWindowSurface::drawable private
Definition at line 78 of file pvreglwindowsurface.h.
Referenced by image(), move(), PvrEglWindowSurface(), setDirectRegion(), setGeometry(), and ~PvrEglWindowSurface().
pdevice
QPaintDevice* PvrEglWindowSurface::pdevice private
Definition at line 80 of file pvreglwindowsurface.h.
Referenced by PvrEglWindowSurface(), and ~PvrEglWindowSurface().
screen
PvrEglScreen* PvrEglWindowSurface::screen private
Definition at line 79 of file pvreglwindowsurface.h.
widget
QWidget* PvrEglWindowSurface::widget private
Definition at line 77 of file pvreglwindowsurface.h.
Referenced by nativeDrawable(), and paintDevice().
The documentation for this class was generated from the following files:
/src/plugins/gfxdrivers/powervr/pvreglscreen/pvreglwindowsurface.h
/src/plugins/gfxdrivers/powervr/pvreglscreen/pvreglwindowsurface.cpp