Qt 4.8: QAuServerNAS Class Reference
QAuServerNAS Class Reference
Public Slots
void dataReceived ()
void soundDestroyed (QObject *o)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void init (QSound *)
Initializes the sound.
bool okay ()
void play (const QString &filename)
void play (QSound *)
QAuServerNAS (QObject *parent)
void setDone (QSound *)
void stop (QSound *)
~QAuServerNAS ()
Public Functions inherited from QAuServer
QAuServer (QObject *parent)
~QAuServer ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
QAuBucketNAS * bucket (QSound *s)
Properties
QSocketNotifier * sn
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QAuServer
QAuBucket * bucket (QSound *)
Returns the internal bucket record of sound s.
int decLoop (QSound *)
Decrements the QSound::loopRemaining() value for sound s, returning the result.
void setBucket (QSound *, QAuBucket *)
Sets the internal bucket record of sound s to b, deleting any previous setting.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 92 of file qsound_x11.cpp.
Constructors and Destructors
QAuServerNAS()
QAuServerNAS::QAuServerNAS (QObject * parent)
Definition at line 119 of file qsound_x11.cpp.
                                           :
     QAuServer(parent)
 {
     setObjectName(QLatin1String("Network Audio System"));
     nas = AuOpenServer(NULL, 0, NULL, 0, NULL, NULL);
     if (nas) {
         AuSetCloseDownMode(nas, AuCloseDownDestroy, NULL);
         // Ask Qt for async messages...
         sn=new QSocketNotifier(AuServerConnectionNumber(nas),
                 QSocketNotifier::Read);
         QObject::connect(sn, SIGNAL(activated(int)),
                 this, SLOT(dataReceived()));
     } else {
         sn = 0;
     }
 }
~QAuServerNAS()
QAuServerNAS::~QAuServerNAS ()
Definition at line 136 of file qsound_x11.cpp.
 {
     if (nas)
         AuCloseServer(nas);
     delete sn;
     nas = 0;
 }
Functions
bucket()
QAuBucketNAS* QAuServerNAS::bucket (QSound * s) inline private
Definition at line 113 of file qsound_x11.cpp.
Referenced by play(), setDone(), and stop().
     {
         return (QAuBucketNAS*)QAuServer::bucket(s);
     }
dataReceived
void QAuServerNAS::dataReceived () slot
Definition at line 253 of file qsound_x11.cpp.
Referenced by play(), QAuServerNAS(), and stop().
 {
     AuHandleEvents(nas);
 }
init()
void QAuServerNAS::init (QSound *) virtual
Initializes the sound.
The default implementation does nothing.
Reimplemented from QAuServer.
Definition at line 235 of file qsound_x11.cpp.
 {
     connect(s, SIGNAL(destroyed(QObject*)),
             this, SLOT(soundDestroyed(QObject*)));
     if (nas) {
         AuBucketID b_id =
             AuSoundCreateBucketFromFile(nas, s->fileName().toLocal8Bit().constData(),
                                         0 /*AuAccessAllMasks*/, NULL, NULL);
         setBucket(s, new QAuBucketNAS(b_id));
     }
 }
okay()
bool QAuServerNAS::okay () virtual
Implements QAuServer.
Definition at line 248 of file qsound_x11.cpp.
 {
     return !!nas;
 }
play() [1/2]
void QAuServerNAS::play (const QString & filename) virtual
Reimplemented from QAuServer.
Definition at line 156 of file qsound_x11.cpp.
Referenced by setDone().
 {
     if (nas) {
         int iv=100;
         AuFixedPoint volume=AuFixedPointFromFraction(iv,100);
         AuSoundPlayFromFile(nas, filename.toLocal8Bit().constData(), AuNone, volume,
                             NULL, NULL, NULL, NULL, NULL, NULL);
         AuFlush(nas);
         dataReceived();
         AuFlush(nas);
         qApp->flush();
     }
 }
play() [2/2]
void QAuServerNAS::play (QSound * s) virtual
Implements QAuServer.
Definition at line 199 of file qsound_x11.cpp.
 {
     if (nas) {
         ++(bucket(s)->numplaying);
         if (!bucket(s)->stopped) {
             stop(s);
         }
         bucket(s)->stopped = false;
         if (!inprogress)
             inprogress = new AuServerHash;
         inprogress->insert(s,this);
         int iv=100;
         AuFixedPoint volume=AuFixedPointFromFraction(iv,100);
         QAuBucketNAS *b = bucket(s);
         AuSoundPlayFromBucket(nas, b->id, AuNone, volume,
                               callback, s, 0, &b->flow, NULL, NULL, NULL);
         AuFlush(nas);
         dataReceived();
         AuFlush(nas);
         qApp->flush();
     }
 }
setDone()
void QAuServerNAS::setDone (QSound * s)
Definition at line 184 of file qsound_x11.cpp.
 {
     if (nas) {
         decLoop(s);
         if (s->loopsRemaining() && !bucket(s)->stopped) {
             bucket(s)->stopped = true;
             play(s);
         } else {
             if (--(bucket(s)->numplaying) == 0)
                 bucket(s)->stopped = true;
             inprogress->remove(s);
         }
     }
 }
soundDestroyed
void QAuServerNAS::soundDestroyed (QObject * o) slot
Definition at line 147 of file qsound_x11.cpp.
Referenced by init().
 {
     if (inprogress) {
         QSound *so = static_cast<QSound *>(o);
         while (inprogress->remove(so))
             ; // Loop while remove returns true
     }
 }
stop()
void QAuServerNAS::stop (QSound * s) virtual
Implements QAuServer.
Definition at line 223 of file qsound_x11.cpp.
Referenced by play().
 {
     if (nas && !bucket(s)->stopped) {
         bucket(s)->stopped = true;
         AuStopFlow(nas, bucket(s)->flow, NULL);
         AuFlush(nas);
         dataReceived();
         AuFlush(nas);
         qApp->flush();
     }
 }
Properties
sn
QSocketNotifier* QAuServerNAS::sn private
Definition at line 95 of file qsound_x11.cpp.
Referenced by QAuServerNAS(), and ~QAuServerNAS().
The documentation for this class was generated from the following file:
/src/gui/kernel/qsound_x11.cpp