Qt 4.8: QPatternist::XsdTerm Class Reference
QPatternist::XsdTerm Class Reference
XML Schema Processing
A base class for all particles of a model group.
#include <qxsdterm_p.h>
Public Types
typedef QExplicitlySharedDataPointer< XsdTerm > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
virtual bool isElement () const
virtual bool isModelGroup () const
virtual bool isReference () const
virtual bool isWildcard () const
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Protected Functions
XsdTerm ()
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
A base class for all particles of a model group.
This class is the base class for all particles of a model group as the element, group or any tag, it is not supposed to be instantiated directly.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 75 of file qxsdterm_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<XsdTerm> QPatternist::XsdTerm::Ptr
Definition at line 78 of file qxsdterm_p.h.
Constructors and Destructors
XsdTerm()
QPatternist::XsdTerm::XsdTerm () inline protected
This constructor only exists to ensure this class is subclassed.
Definition at line 106 of file qxsdterm_p.h.
 {};
Functions
isElement()
bool XsdTerm::isElement () const virtual
Returns true if the term is an element, false otherwise.
Reimplemented in QPatternist::XsdElement.
Definition at line 48 of file qxsdterm.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildTerm(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), derivedTermValid(), QPatternist::XsdSchemaDebugger::dumpParticle(), effectiveTotalRangeMinimum(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), hasDuplicatedElementsInternal(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QPatternist::XsdSchemaResolver::resolveTermReference(), termMatches(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::transitionTypeToString(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     return false;
 }
isModelGroup()
bool XsdTerm::isModelGroup () const virtual
Returns true if the term is a model group (group tag), false otherwise.
Reimplemented in QPatternist::XsdModelGroup.
Definition at line 53 of file qxsdterm.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildTerm(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), collectGroupRef(), QPatternist::XsdSchemaDebugger::dumpParticle(), effectiveTotalRangeMinimum(), hasDuplicatedElementsInternal(), internalParticleLookupMap(), QPatternist::XsdSchemaHelper::isParticleEmptiable(), QPatternist::XsdParticleChecker::isUPAConform(), QPatternist::XsdSchemaChecker::isValidParticleExtension(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdSchemaResolver::resolveTermReference().
 {
     return false;
 }
isReference()
bool XsdTerm::isReference () const virtual
Returns true if the term is a reference, false otherwise.
Note
The reference term is only used internally as helper during type resolving.
Reimplemented in QPatternist::XsdReference.
Definition at line 63 of file qxsdterm.cpp.
Referenced by collectGroupRef(), and QPatternist::XsdSchemaResolver::resolveTermReference().
 {
     return false;
 }
isWildcard()
bool XsdTerm::isWildcard () const virtual
Returns true if the term is a wildcard (any tag), false otherwise.
Reimplemented in QPatternist::XsdWildcard.
Definition at line 58 of file qxsdterm.cpp.
Referenced by QPatternist::XsdStateMachineBuilder::buildTerm(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), derivedTermValid(), QPatternist::XsdSchemaDebugger::dumpParticle(), effectiveTotalRangeMinimum(), QPatternist::XsdSchemaChecker::elementSequenceAccepted(), QPatternist::XsdSchemaChecker::particleEqualsRecursively(), termMatches(), and QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::transitionTypeToString().
 {
     return false;
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdterm_p.h
/src/xmlpatterns/schema/qxsdterm.cpp