Qt 4.8: QPatternist::SourceLocationReflection Class Reference
QPatternist::SourceLocationReflection Class Reference abstract
Base class for all instances that represents something at a certain location.
#include <qsourcelocationreflection_p.h>
Public Functions
virtual const SourceLocationReflection * actualReflection () const =0
virtual QString description () const
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Detailed Description
Base class for all instances that represents something at a certain location.
SourceLocationReflection does not provide the source location itself, the address to an instance is the mark for it, that in turn can be used for looking up the source location where that mapping is provided.
However, this SourceLocationReflection is not itself the mark. The real mark is retrieved by calling actualReflection(). This mechanism allows a SourceLocationReflection sub-class to delegate, or be an alias, for another source location mark.
If sourceLocation() returns a non-null object, it will be used instead of looking up via actualReflection().
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 82 of file qsourcelocationreflection_p.h.
Constructors and Destructors
SourceLocationReflection()
QPatternist::SourceLocationReflection::SourceLocationReflection () inline
Definition at line 85 of file qsourcelocationreflection_p.h.
         {
         }
~SourceLocationReflection()
virtual QPatternist::SourceLocationReflection::~SourceLocationReflection () inline virtual
Definition at line 89 of file qsourcelocationreflection_p.h.
         {
         }
Functions
actualReflection()
virtual const SourceLocationReflection* QPatternist::SourceLocationReflection::actualReflection () const pure virtual
Implemented in QPatternist::Expression, QPatternist::ReflectYYLTYPE, QPatternist::AccelTreeBuilder< FromDocument >, QPatternist::AccelTreeBuilder< true >, QPatternist::QNameConstructor, QPatternist::EvaluationCache< IsForGlobal >, QPatternist::DelegatingSourceLocationReflection, QPatternist::ContextItem, QPatternist::IndexOfIterator, QPatternist::UntypedAtomicConverter, QPatternist::DistinctIterator, QPatternist::CardinalityVerifier, DelegatingReflectionExpression, QPatternist::Template, PerformComparison, QPatternist::CurrentItemStore, QPatternist::Atomizer, QPatternist::ItemVerifier, QPatternist::DynamicContextStore, QPatternist::EBVExtractor, QPatternist::XsdSchemaSourceLocationReflection, and PerformValueConstruction.
Referenced by QPatternist::DelegatingSourceLocationReflection::actualReflection(), QPatternist::GenericDynamicContext::locationFor(), QPatternist::GenericStaticContext::locationFor(), and QPatternist::ReportContext::lookupSourceLocation().
description()
virtual QString QPatternist::SourceLocationReflection::description () const inline virtual
A description of what represents the source code location, for human consumption. Must be translated, as appropriate.
Reimplemented in QPatternist::Expression, QPatternist::ReflectYYLTYPE, QPatternist::GenericPredicate, QPatternist::DelegatingSourceLocationReflection, and QPatternist::Literal.
Definition at line 99 of file qsourcelocationreflection_p.h.
Referenced by QPatternist::ReportContext::lookupSourceLocation().
         {
             return QString();
         }
sourceLocation()
QSourceLocation SourceLocationReflection::sourceLocation () const virtual
Reimplemented in QPatternist::ReflectYYLTYPE, QPatternist::AccelTreeBuilder< FromDocument >, QPatternist::AccelTreeBuilder< true >, and QPatternist::XsdSchemaSourceLocationReflection.
Definition at line 50 of file qsourcelocationreflection.cpp.
Referenced by QPatternist::ReportContext::lookupSourceLocation().
 {
     return QSourceLocation();
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qsourcelocationreflection_p.h
/src/xmlpatterns/expr/qsourcelocationreflection.cpp