Qt 4.8: QHostInfoCache Class Reference
QHostInfoCache Class Reference
#include <qhostinfo_p.h>
Classes
struct QHostInfoCacheElement
Public Functions
void clear ()
QHostInfo get (const QString &name, bool *valid)
bool isEnabled ()
void put (const QString &name, const QHostInfo &info)
QHostInfoCache ()
void setEnabled (bool e)
Public Variables
const int max_age
Properties
QCache< QString, QHostInfoCacheElement > cache
bool enabled
QMutex mutex
Detailed Description
Definition at line 141 of file qhostinfo_p.h.
Constructors and Destructors
QHostInfoCache()
QHostInfoCache::QHostInfoCache ()
Definition at line 765 of file qhostinfo.cpp.
                                : max_age(60), enabled(true), cache(128)
 {
 #ifdef QT_QHOSTINFO_CACHE_DISABLED_BY_DEFAULT
     enabled = false;
 #endif
 }
Functions
clear()
void QHostInfoCache::clear ()
Definition at line 819 of file qhostinfo.cpp.
Referenced by QHostInfoLookupManager::clear().
 {
     QMutexLocker locker(&this->mutex);
     cache.clear();
 }
get()
QHostInfo QHostInfoCache::get (const QString & name, bool * valid)
Definition at line 785 of file qhostinfo.cpp.
Referenced by QHostInfo::lookupHost(), qt_qhostinfo_lookup(), and QHostInfoRunnable::run().
 {
     QMutexLocker locker(&this->mutex);
     *valid = false;
     if (cache.contains(name)) {
         QHostInfoCacheElement *element = cache.object(name);
         if (element->age.elapsed() < max_age*1000)
             *valid = true;
         return element->info;
         // FIXME idea:
         // if too old but not expired, trigger a new lookup
         // to freshen our cache
     }
     return QHostInfo();
 }
isEnabled()
bool QHostInfoCache::isEnabled ()
Definition at line 772 of file qhostinfo.cpp.
Referenced by QHostInfo::lookupHost(), qt_qhostinfo_lookup(), and QHostInfoRunnable::run().
 {
     return enabled;
 }
put()
void QHostInfoCache::put (const QString & name, const QHostInfo & info)
Definition at line 804 of file qhostinfo.cpp.
Referenced by QHostInfo::fromName(), QHostInfoPrivate::fromName(), and QHostInfoRunnable::run().
 {
     // if the lookup failed, don't cache
     if (info.error() != QHostInfo::NoError)
         return;
     QHostInfoCacheElement* element = new QHostInfoCacheElement();
     element->info = info;
     element->age = QElapsedTimer();
     element->age.start();
     QMutexLocker locker(&this->mutex);
     cache.insert(name, element); // cache will take ownership
 }
setEnabled()
void QHostInfoCache::setEnabled (bool e)
Definition at line 779 of file qhostinfo.cpp.
Referenced by qt_qhostinfo_enable_cache().
 {
     enabled = e;
 }
Properties
cache
QCache<QString,QHostInfoCacheElement> QHostInfoCache::cache private
Definition at line 159 of file qhostinfo_p.h.
Referenced by clear(), get(), and put().
enabled
bool QHostInfoCache::enabled private
Definition at line 154 of file qhostinfo_p.h.
Referenced by isEnabled(), QHostInfoCache(), and setEnabled().
max_age
const int QHostInfoCache::max_age
Definition at line 145 of file qhostinfo_p.h.
Referenced by get().
mutex
QMutex QHostInfoCache::mutex private
Definition at line 160 of file qhostinfo_p.h.
Referenced by clear(), get(), and put().
The documentation for this class was generated from the following files:
/src/network/kernel/qhostinfo_p.h
/src/network/kernel/qhostinfo.cpp