Qt 4.8: QWaylandGLIntegration Class Reference
QWaylandGLIntegration Class Reference abstract
#include <qwaylandglintegration.h>
Public Functions
virtual QWaylandWindow * createEglWindow (QWidget *widget)=0
virtual void initialize ()=0
QWaylandGLIntegration ()
virtual ~QWaylandGLIntegration ()
Static Public Functions
static QWaylandGLIntegration * createGLIntegration (QWaylandDisplay *waylandDisplay)
Detailed Description
Definition at line 49 of file qwaylandglintegration.h.
Constructors and Destructors
QWaylandGLIntegration()
QWaylandGLIntegration::QWaylandGLIntegration ()
Definition at line 44 of file qwaylandglintegration.cpp.
 {
 }
~QWaylandGLIntegration()
QWaylandGLIntegration::~QWaylandGLIntegration () virtual
Definition at line 49 of file qwaylandglintegration.cpp.
 {
 }
Functions
createEglWindow()
virtual QWaylandWindow* QWaylandGLIntegration::createEglWindow (QWidget * widget) pure virtual
Implemented in QWaylandXCompositeEGLIntegration, QWaylandXCompositeGLXIntegration, QWaylandReadbackEglIntegration, QWaylandReadbackGlxIntegration, and QWaylandEglIntegration.
createGLIntegration()
QWaylandGLIntegration * QWaylandGLIntegration::createGLIntegration (QWaylandDisplay * waylandDisplay) static
Definition at line 66 of file qwaylandreadbackeglintegration.cpp.
Referenced by QWaylandReadbackGlxIntegration::createEglWindow(), QWaylandEglIntegration::eglDisplay(), and QWaylandDisplay::QWaylandDisplay().
 {
     return new QWaylandReadbackEglIntegration(waylandDisplay);
 }
initialize()
virtual void QWaylandGLIntegration::initialize () pure virtual
Implemented in QWaylandXCompositeEGLIntegration, QWaylandXCompositeGLXIntegration, QWaylandReadbackEglIntegration, QWaylandReadbackGlxIntegration, and QWaylandEglIntegration.
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/gl_integration/qwaylandglintegration.h
/src/plugins/platforms/wayland/gl_integration/qwaylandglintegration.cpp
/src/plugins/platforms/wayland/gl_integration/readback_egl/qwaylandreadbackeglintegration.cpp
/src/plugins/platforms/wayland/gl_integration/readback_glx/qwaylandreadbackglxintegration.cpp
/src/plugins/platforms/wayland/gl_integration/wayland_egl/qwaylandeglintegration.cpp
/src/plugins/platforms/wayland/gl_integration/xcomposite_egl/qwaylandxcompositeeglintegration.cpp
/src/plugins/platforms/wayland/gl_integration/xcomposite_glx/qwaylandxcompositeglxintegration.cpp