Qt 4.8: QPlatformWindowFormat Class Reference
QPlatformWindowFormat Class Reference
The QPlatformWindowFormat class specifies the display format of an OpenGL rendering context and if possible attributes of the corresponding QPlatformWindow.
#include <qplatformwindowformat_qpa.h>
Public Types
enum FormatOption {
DoubleBuffer = 0x0001, DepthBuffer = 0x0002, Rgba = 0x0004, AlphaChannel = 0x0008,
AccumBuffer = 0x0010, StencilBuffer = 0x0020, StereoBuffers = 0x0040, DirectRendering = 0x0080,
HasOverlay = 0x0100, SampleBuffers = 0x0200, DeprecatedFunctions = 0x0400, HasWindowSurface = 0x0800,
SingleBuffer = DoubleBuffer << 16, NoDepthBuffer = DepthBuffer << 16, ColorIndex = Rgba << 16, NoAlphaChannel = AlphaChannel << 16,
NoAccumBuffer = AccumBuffer << 16, NoStencilBuffer = StencilBuffer << 16, NoStereoBuffers = StereoBuffers << 16, IndirectRendering = DirectRendering << 16,
NoOverlay = HasOverlay << 16, NoSampleBuffers = SampleBuffers << 16, NoDeprecatedFunctions = DeprecatedFunctions << 16, NoWindowSurface = HasWindowSurface << 16
}
enum WindowApi { Raster, OpenGL, OpenVG }
Public Functions
bool accum () const
Returns true if the accumulation buffer is enabled; otherwise returns false.
int accumBufferSize () const
Returns the accumulation buffer size.
bool alpha () const
Returns true if the alpha buffer in the framebuffer is enabled; otherwise returns false.
int alphaBufferSize () const
Returns the alpha buffer size.
int blueBufferSize () const
Returns the blue buffer size.
bool depth () const
Returns true if the depth buffer is enabled; otherwise returns false.
int depthBufferSize () const
Returns the depth buffer size.
bool directRendering () const
Returns true if direct rendering is enabled; otherwise returns false.
bool doubleBuffer () const
Returns true if double buffering is enabled; otherwise returns false.
int greenBufferSize () const
Returns the green buffer size.
bool hasWindowSurface () const
Returns true if the corresponding widget has an instance of QWindowSurface.
QPlatformWindowFormat & operator= (const QPlatformWindowFormat &other)
Assigns other to this object.
QPlatformWindowFormat ()
Constructs a QPlatformWindowFormat object with the following default settings:
QPlatformWindowFormat (FormatOptions options)
QPlatformWindowFormat (const QPlatformWindowFormat &other)
Constructs a copy of other.
int redBufferSize () const
Returns the red buffer size.
bool rgba () const
Returns true if RGBA color mode is set.
bool sampleBuffers () const
Returns true if multisample buffer support is enabled; otherwise returns false.
int samples () const
Returns the number of samples per pixel when multisampling is enabled.
void setAccum (bool enable)
If enable is true enables the accumulation buffer; otherwise disables the accumulation buffer.
void setAccumBufferSize (int size)
Set the preferred accumulation buffer size, where size is the bit depth for each RGBA component.
void setAlpha (bool enable)
If enable is true enables the alpha buffer; otherwise disables the alpha buffer.
void setAlphaBufferSize (int size)
Set the preferred alpha buffer size to size.
void setBlueBufferSize (int size)
Set the preferred blue buffer size to size.
void setDepth (bool enable)
If enable is true enables the depth buffer; otherwise disables the depth buffer.
void setDepthBufferSize (int size)
Set the minimum depth buffer size to size.
void setDirectRendering (bool enable)
If enable is true enables direct rendering; otherwise disables direct rendering.
void setDoubleBuffer (bool enable)
If enable is true sets double buffering; otherwise sets single buffering.
void setGreenBufferSize (int size)
Set the preferred green buffer size to size.
void setOption (QPlatformWindowFormat::FormatOptions opt)
Sets the format option to opt.
void setRedBufferSize (int size)
Set the preferred red buffer size to size.
void setRgba (bool enable)
If enable is true sets RGBA mode.
void setSampleBuffers (bool enable)
If enable is true, a GL context with multisample buffer support is picked; otherwise ignored.
void setSamples (int numSamples)
Set the preferred number of samples per pixel when multisampling is enabled to numSamples.
void setSharedContext (QPlatformGLContext *context)
void setStencil (bool enable)
If enable is true enables the stencil buffer; otherwise disables the stencil buffer.
void setStencilBufferSize (int size)
Set the preferred stencil buffer size to size.
void setStereo (bool enable)
If enable is true enables stereo buffering; otherwise disables stereo buffering.
void setSwapInterval (int interval)
Set the preferred swap interval.
void setWindowApi (QPlatformWindowFormat::WindowApi api)
void setWindowSurface (bool enable)
If enable is true a top level QWidget will create a QWindowSurface at creation;.
QPlatformGLContext * sharedGLContext () const
bool stencil () const
Returns true if the stencil buffer is enabled; otherwise returns false.
int stencilBufferSize () const
Returns the stencil buffer size.
bool stereo () const
Returns true if stereo buffering is enabled; otherwise returns false.
int swapInterval () const
Returns the currently set swap interval.
bool testOption (QPlatformWindowFormat::FormatOptions opt) const
Returns true if format option opt is set; otherwise returns false.
WindowApi windowApi () const
~QPlatformWindowFormat ()
Destroys the QPlatformWindowFormat.
Static Public Functions
static QPlatformWindowFormat defaultFormat ()
Returns the default QPlatformWindowFormat for the application.
static void setDefaultFormat (const QPlatformWindowFormat &f)
Sets a new default QPlatformWindowFormat for the application to f.
Private Functions
void detach ()
Properties
QPlatformWindowFormatPrivate * d
Friends
Q_GUI_EXPORT bool operator!= (const QPlatformWindowFormat &, const QPlatformWindowFormat &)
Returns false if all the options of the two QPlatformWindowFormat objects a and b are equal; otherwise returns true.
Q_GUI_EXPORT QDebug operator<< (QDebug, const QPlatformWindowFormat &)
Q_GUI_EXPORT bool operator== (const QPlatformWindowFormat &, const QPlatformWindowFormat &)
Sets a new default QPlatformWindowFormat for overlay contexts to f.
Detailed Description
The QPlatformWindowFormat class specifies the display format of an OpenGL rendering context and if possible attributes of the corresponding QPlatformWindow.
Since
4.8
QWidget has a setter and getter function for QPlatformWindowFormat. These functions can be used by the application programmer to signal what kind of format he wants to the window and glcontext should have. However, it is not always possible to fulfill these requirements. The application programmer should therefore check the resulting QPlatformWindowFormat from QPlatformGLContext to see the format that was actually created.
A display format has several characteristics:
Double or single buffering.
Depth buffer.
RGBA or color index mode.
Alpha channel.
Accumulation buffer.
Stencil buffer.
Stereo buffers.
Direct rendering.
Multisample buffers.
You can also specify preferred bit depths for the color buffer, depth buffer, alpha buffer, accumulation buffer and the stencil buffer with the functions: setRedBufferSize(), setGreenBufferSize(), setBlueBufferSize(), setDepthBufferSize(), setAlphaBufferSize(), setAccumBufferSize() and setStencilBufferSize().
Note that even if you specify that you prefer a 32 bit depth buffer (e.g. with setDepthBufferSize(32)), the format that is chosen may not have a 32 bit depth buffer, even if there is a format available with a 32 bit depth buffer. The main reason for this is how the system dependant picking algorithms work on the different platforms, and some format options may have higher precedence than others.
You create and tell a QPlatformWindowFormat object what rendering options you want from an OpenGL rendering context.
OpenGL drivers or accelerated hardware may or may not support advanced features such as alpha channel or stereographic viewing. If you request some features that the driver/hardware does not provide when you create a QGLWidget, you will get a rendering context with the nearest subset of features.
There are different ways to define the display characteristics of a rendering context. One is to create a QPlatformWindowFormat and make it the default for the entire application:
QGLFormat fmt;
fmt.setAlpha(true);
fmt.setStereo(true);
QGLFormat::setDefaultFormat(fmt);
Or you can specify the desired format when creating an object of your QGLWidget subclass:
QGLFormat fmt;
fmt.setDoubleBuffer(false);                 // single buffer
fmt.setDirectRendering(false);              // software rendering
MyGLWidget* myWidget = new MyGLWidget(fmt, ...);
After the widget has been created, you can find out which of the requested features the system was able to provide:
QGLFormat fmt;
fmt.setOverlay(true);
fmt.setStereo(true);
MyGLWidget* myWidget = new MyGLWidget(fmt, ...);
if (!myWidget->format().stereo()) {
    // ok, goggles off
    if (!myWidget->format().hasOverlay()) {
        qFatal("Cool hardware required");
    }
}
OpenGL is a trademark of Silicon Graphics, Inc. in the United States and other countries.
See also
QPlatformGLContext, QWidget
Definition at line 54 of file qplatformwindowformat_qpa.h.
Enumerations
FormatOption
enum QPlatformWindowFormat::FormatOption
Enumerator
DoubleBuffer
DepthBuffer
Rgba
AlphaChannel
AccumBuffer
StencilBuffer
StereoBuffers
DirectRendering
HasOverlay
SampleBuffers
DeprecatedFunctions
HasWindowSurface
SingleBuffer
NoDepthBuffer
ColorIndex
NoAlphaChannel
NoAccumBuffer
NoStencilBuffer
NoStereoBuffers
IndirectRendering
NoOverlay
NoSampleBuffers
NoDeprecatedFunctions
NoWindowSurface
Definition at line 57 of file qplatformwindowformat_qpa.h.
                       {
         DoubleBuffer            = 0x0001,
         DepthBuffer             = 0x0002,
         Rgba                    = 0x0004,
         AlphaChannel            = 0x0008,
         AccumBuffer             = 0x0010,
         StencilBuffer           = 0x0020,
         StereoBuffers           = 0x0040,
         DirectRendering         = 0x0080,
         HasOverlay              = 0x0100,
         SampleBuffers           = 0x0200,
         DeprecatedFunctions     = 0x0400,
         HasWindowSurface        = 0x0800,
         SingleBuffer            = DoubleBuffer    << 16,
         NoDepthBuffer           = DepthBuffer     << 16,
         ColorIndex              = Rgba            << 16,
         NoAlphaChannel          = AlphaChannel    << 16,
         NoAccumBuffer           = AccumBuffer     << 16,
         NoStencilBuffer         = StencilBuffer   << 16,
         NoStereoBuffers         = StereoBuffers   << 16,
         IndirectRendering       = DirectRendering << 16,
         NoOverlay               = HasOverlay      << 16,
         NoSampleBuffers         = SampleBuffers   << 16,
         NoDeprecatedFunctions   = DeprecatedFunctions << 16,
         NoWindowSurface         = HasWindowSurface << 16
     };
WindowApi
enum QPlatformWindowFormat::WindowApi
Enumerator
Raster
OpenGL
OpenVG
Definition at line 86 of file qplatformwindowformat_qpa.h.
                    {
         Raster,
         OpenGL,
         OpenVG
     };
Constructors and Destructors
QPlatformWindowFormat() [1/3]
QPlatformWindowFormat::QPlatformWindowFormat ()
Constructs a QPlatformWindowFormat object with the following default settings:
Double buffer: Enabled.
Depth buffer: Enabled.
RGBA: Enabled (i.e., color index disabled).
Alpha channel: Disabled.
Accumulator buffer: Disabled.
Stencil buffer: Enabled.
Stereo: Disabled.
Direct rendering: Enabled.
Multisample buffers: Disabled.
Definition at line 190 of file qplatformwindowformat_qpa.cpp.
 {
     d = new QPlatformWindowFormatPrivate;
 }
QPlatformWindowFormat() [2/3]
QPlatformWindowFormat::QPlatformWindowFormat (FormatOptions options)
QPlatformWindowFormat() [3/3]
QPlatformWindowFormat::QPlatformWindowFormat (const QPlatformWindowFormat & other)
Constructs a copy of other.
Definition at line 241 of file qplatformwindowformat_qpa.cpp.
 {
     d = other.d;
     d->ref.ref();
 }
~QPlatformWindowFormat()
QPlatformWindowFormat::~QPlatformWindowFormat ()
Destroys the QPlatformWindowFormat.
Definition at line 265 of file qplatformwindowformat_qpa.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
Functions
accum()
bool QPlatformWindowFormat::accum () const inline
Returns true if the accumulation buffer is enabled; otherwise returns false.
The accumulation buffer is disabled by default.
See also
setAccum(), setAccumBufferSize()
Definition at line 200 of file qplatformwindowformat_qpa.h.
Referenced by qglx_buildSpec(), and qglx_reducePlatformWindowFormat().
 {
     return testOption(QPlatformWindowFormat::AccumBuffer);
 }
accumBufferSize()
int QPlatformWindowFormat::accumBufferSize () const
Returns the accumulation buffer size.
See also
setAccumBufferSize(), accum(), setAccum()
Definition at line 879 of file qplatformwindowformat_qpa.cpp.
Referenced by qglx_buildSpec().
 {
    return d->accumSize;
 }
alpha()
bool QPlatformWindowFormat::alpha () const inline
Returns true if the alpha buffer in the framebuffer is enabled; otherwise returns false.
The alpha buffer is disabled by default.
See also
setAlpha(), setAlphaBufferSize()
Definition at line 195 of file qplatformwindowformat_qpa.h.
Referenced by q_createConfigAttributesFromFormat(), qglx_buildSpec(), qglx_findConfig(), and qglx_reducePlatformWindowFormat().
 {
     return testOption(QPlatformWindowFormat::AlphaChannel);
 }
alphaBufferSize()
int QPlatformWindowFormat::alphaBufferSize () const
Returns the alpha buffer size.
See also
alpha(), setAlpha(), setAlphaBufferSize()
Definition at line 852 of file qplatformwindowformat_qpa.cpp.
Referenced by q_createConfigAttributesFromFormat(), QBBGLContext::QBBGLContext(), and qglx_buildSpec().
 {
    return d->alphaSize;
 }
blueBufferSize()
int QPlatformWindowFormat::blueBufferSize () const
Returns the blue buffer size.
Since
4.2
See also
setBlueBufferSize()
Definition at line 825 of file qplatformwindowformat_qpa.cpp.
Referenced by QXlibWindow::correctColorBuffers(), QBBWindow::platformWindowFormatToNativeFormat(), q_createConfigAttributesFromFormat(), QBBGLContext::QBBGLContext(), and qglx_buildSpec().
 {
    return d->blueSize;
 }
defaultFormat()
QPlatformWindowFormat QPlatformWindowFormat::defaultFormat () static
Returns the default QPlatformWindowFormat for the application.
All QGLWidget objects that are created use this format unless another format is specified, e.g. when they are constructed.
If no special default format has been set using setDefaultFormat(), the default format is the same as that created with QPlatformWindowFormat().
See also
setDefaultFormat()
Definition at line 922 of file qplatformwindowformat_qpa.cpp.
Referenced by QEglFSScreen::createAndSetPlatformContext(), QWidgetPrivate::createTLExtra(), effectiveState(), and QBBIntegration::QBBIntegration().
 {
     return *q_platformwindow_default_format();
 }
depth()
bool QPlatformWindowFormat::depth () const inline
Returns true if the depth buffer is enabled; otherwise returns false.
The depth buffer is enabled by default.
See also
setDepth(), setDepthBufferSize()
Definition at line 185 of file qplatformwindowformat_qpa.h.
Referenced by q_createConfigAttributesFromFormat(), qglx_buildSpec(), and qglx_reducePlatformWindowFormat().
 {
     return testOption(QPlatformWindowFormat::DepthBuffer);
 }
depthBufferSize()
int QPlatformWindowFormat::depthBufferSize () const
Returns the depth buffer size.
See also
depth(), setDepth(), setDepthBufferSize()
Definition at line 720 of file qplatformwindowformat_qpa.cpp.
Referenced by q_createConfigAttributesFromFormat(), and qglx_buildSpec().
 {
    return d->depthSize;
 }
detach()
void QPlatformWindowFormat::detach () private
Warning
This function is not part of the public interface.
Definition at line 227 of file qplatformwindowformat_qpa.cpp.
 {
     if (d->ref != 1) {
         QPlatformWindowFormatPrivate *newd = new QPlatformWindowFormatPrivate(d);
         if (!d->ref.deref())
             delete d;
         d = newd;
     }
 }
directRendering()
bool QPlatformWindowFormat::directRendering () const inline
Returns true if direct rendering is enabled; otherwise returns false.
Direct rendering is enabled by default.
See also
setDirectRendering()
Definition at line 215 of file qplatformwindowformat_qpa.h.
 {
     return testOption(QPlatformWindowFormat::DirectRendering);
 }
doubleBuffer()
bool QPlatformWindowFormat::doubleBuffer () const inline
Returns true if double buffering is enabled; otherwise returns false.
Double buffering is enabled by default.
See also
setDoubleBuffer()
Definition at line 180 of file qplatformwindowformat_qpa.h.
Referenced by qglx_buildSpec(), and qglx_reducePlatformWindowFormat().
 {
     return testOption(QPlatformWindowFormat::DoubleBuffer);
 }
greenBufferSize()
int QPlatformWindowFormat::greenBufferSize () const
Returns the green buffer size.
Since
4.2
See also
setGreenBufferSize()
Definition at line 790 of file qplatformwindowformat_qpa.cpp.
Referenced by QXlibWindow::correctColorBuffers(), QBBWindow::platformWindowFormatToNativeFormat(), q_createConfigAttributesFromFormat(), QBBGLContext::QBBGLContext(), and qglx_buildSpec().
 {
    return d->greenSize;
 }
hasWindowSurface()
bool QPlatformWindowFormat::hasWindowSurface () const inline
Returns true if the corresponding widget has an instance of QWindowSurface.
Otherwise returns false.
WindowSurface is enabled by default.
Definition at line 220 of file qplatformwindowformat_qpa.h.
 {
     return testOption(QPlatformWindowFormat::HasWindowSurface);
 }
operator=()
QPlatformWindowFormat & QPlatformWindowFormat::operator= (const QPlatformWindowFormat & other)
Assigns other to this object.
Definition at line 251 of file qplatformwindowformat_qpa.cpp.
 {
     if (d != other.d) {
         other.d->ref.ref();
         if (!d->ref.deref())
             delete d;
         d = other.d;
     }
     return *this;
 }
redBufferSize()
int QPlatformWindowFormat::redBufferSize () const
Returns the red buffer size.
Since
4.2
See also
setRedBufferSize()
Definition at line 755 of file qplatformwindowformat_qpa.cpp.
Referenced by QXlibWindow::correctColorBuffers(), QBBWindow::platformWindowFormatToNativeFormat(), q_createConfigAttributesFromFormat(), QBBGLContext::QBBGLContext(), and qglx_buildSpec().
 {
    return d->redSize;
 }
rgba()
bool QPlatformWindowFormat::rgba () const inline
Returns true if RGBA color mode is set.
Returns false if color index mode is set. The default color mode is RGBA.
See also
setRgba()
Definition at line 190 of file qplatformwindowformat_qpa.h.
Referenced by qglx_buildSpec().
 {
     return testOption(QPlatformWindowFormat::Rgba);
 }
sampleBuffers()
bool QPlatformWindowFormat::sampleBuffers () const inline
Returns true if multisample buffer support is enabled; otherwise returns false.
The multisample buffer is disabled by default.
See also
setSampleBuffers()
Definition at line 225 of file qplatformwindowformat_qpa.h.
Referenced by q_createConfigAttributesFromFormat(), qglx_buildSpec(), qglx_platformWindowFromGLXFBConfig(), and qglx_reducePlatformWindowFormat().
 {
     return testOption(QPlatformWindowFormat::SampleBuffers);
 }
samples()
int QPlatformWindowFormat::samples () const
Returns the number of samples per pixel when multisampling is enabled.
By default, the highest number of samples that is available is used.
See also
setSampleBuffers(), sampleBuffers(), setSamples()
Definition at line 557 of file qplatformwindowformat_qpa.cpp.
Referenced by q_createConfigAttributesFromFormat(), and qglx_buildSpec().
 {
    return d->numSamples;
 }
setAccum()
void QPlatformWindowFormat::setAccum (bool enable)
If enable is true enables the accumulation buffer; otherwise disables the accumulation buffer.
The accumulation buffer is disabled by default.
The accumulation buffer is used to create blur effects and multiple exposures.
See also
accum(), setAccumBufferSize()
Definition at line 427 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), and qglx_reducePlatformWindowFormat().
 {
     setOption(enable ? QPlatformWindowFormat::AccumBuffer : QPlatformWindowFormat::NoAccumBuffer);
 }
setAccumBufferSize()
void QPlatformWindowFormat::setAccumBufferSize (int size)
Set the preferred accumulation buffer size, where size is the bit depth for each RGBA component.
See also
accum(), setAccum(), accumBufferSize()
Definition at line 863 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (size < 0) {
         qWarning("QPlatformWindowFormat::setAccumBufferSize: Cannot set negative accumulate buffer size %d", size);
         return;
     }
     d->accumSize = size;
     setAccum(size > 0);
 }
setAlpha()
void QPlatformWindowFormat::setAlpha (bool enable)
If enable is true enables the alpha buffer; otherwise disables the alpha buffer.
The alpha buffer is disabled by default.
The alpha buffer is typically used for implementing transparency or translucency. The A in RGBA specifies the transparency of a pixel.
See also
alpha(), setAlphaBufferSize()
Definition at line 397 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), effectiveState(), qDeleteQGLContext(), QDirectFbGLContext::QDirectFbGLContext(), and qglx_reducePlatformWindowFormat().
 {
     setOption(enable ? QPlatformWindowFormat::AlphaChannel : QPlatformWindowFormat::NoAlphaChannel);
 }
setAlphaBufferSize()
void QPlatformWindowFormat::setAlphaBufferSize (int size)
Set the preferred alpha buffer size to size.
This function implicitly enables the alpha channel.
See also
setRedBufferSize(), setGreenBufferSize(), alphaBufferSize()
Definition at line 836 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), QBBGLContext::QBBGLContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (size < 0) {
         qWarning("QPlatformWindowFormat::setAlphaBufferSize: Cannot set negative alpha buffer size %d", size);
         return;
     }
     d->alphaSize = size;
     setAlpha(size > 0);
 }
setBlueBufferSize()
void QPlatformWindowFormat::setBlueBufferSize (int size)
Set the preferred blue buffer size to size.
Since
4.2
See also
setRedBufferSize(), setGreenBufferSize(), setAlphaBufferSize()
Definition at line 805 of file qplatformwindowformat_qpa.cpp.
Referenced by QXlibWindow::correctColorBuffers(), QEglFSScreen::createAndSetPlatformContext(), EAGLPlatformContext::EAGLPlatformContext(), QBBGLContext::QBBGLContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), QOpenKODEWindow::QOpenKODEWindow(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (size < 0) {
         qWarning("QPlatformWindowFormat::setBlueBufferSize: Cannot set negative blue buffer size %d", size);
         return;
     }
     d->blueSize = size;
 }
setDefaultFormat()
void QPlatformWindowFormat::setDefaultFormat (const QPlatformWindowFormat & f) static
Sets a new default QPlatformWindowFormat for the application to f.
For example, to set single buffering as the default instead of double buffering, your main() might contain code like this:
QApplication a(argc, argv);
QGLFormat f;
f.setDoubleBuffer(false);
QGLFormat::setDefaultFormat(f);
See also
defaultFormat()
Definition at line 936 of file qplatformwindowformat_qpa.cpp.
Referenced by QBBIntegration::QBBIntegration().
 {
     *q_platformwindow_default_format() = f;
 }
setDepth()
void QPlatformWindowFormat::setDepth (bool enable)
If enable is true enables the depth buffer; otherwise disables the depth buffer.
The depth buffer is enabled by default.
The purpose of a depth buffer (or Z-buffering) is to remove hidden surfaces. Pixels are assigned Z values based on the distance to the viewer. A pixel with a high Z value is closer to the viewer than a pixel with a low Z value. This information is used to decide whether to draw a pixel or not.
See also
depth(), setDepthBufferSize()
Definition at line 332 of file qplatformwindowformat_qpa.cpp.
Referenced by QEglFSScreen::createAndSetPlatformContext(), EAGLPlatformContext::EAGLPlatformContext(), and qglx_reducePlatformWindowFormat().
 {
     setOption(enable ? QPlatformWindowFormat::DepthBuffer : QPlatformWindowFormat::NoDepthBuffer);
 }
setDepthBufferSize()
void QPlatformWindowFormat::setDepthBufferSize (int size)
Set the minimum depth buffer size to size.
See also
depthBufferSize(), setDepth(), depth()
Definition at line 704 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (size < 0) {
         qWarning("QPlatformWindowFormat::setDepthBufferSize: Cannot set negative depth buffer size %d", size);
         return;
     }
     d->depthSize = size;
     setDepth(size > 0);
 }
setDirectRendering()
void QPlatformWindowFormat::setDirectRendering (bool enable)
If enable is true enables direct rendering; otherwise disables direct rendering.
Direct rendering is enabled by default.
Enabling this option will make OpenGL bypass the underlying window system and render directly from hardware to the screen, if this is supported by the system.
See also
directRendering()
Definition at line 520 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), qglx_platformWindowFromGLXFBConfig(), and qt_qPlatformWindowFormatFromConfig().
 {
     setOption(enable ? QPlatformWindowFormat::DirectRendering : QPlatformWindowFormat::IndirectRendering);
 }
setDoubleBuffer()
void QPlatformWindowFormat::setDoubleBuffer (bool enable)
If enable is true sets double buffering; otherwise sets single buffering.
Double buffering is enabled by default.
Double buffering is a technique where graphics are rendered on an off-screen buffer and not directly to the screen. When the drawing has been completed, the program calls a swapBuffers() function to exchange the screen contents with the buffer. The result is flicker-free drawing and often better performance.
See also
doubleBuffer(), QGLContext::swapBuffers(), QGLWidget::swapBuffers()
Definition at line 299 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), QDirectFbGLContext::QDirectFbGLContext(), and qglx_reducePlatformWindowFormat().
 {
     setOption(enable ? QPlatformWindowFormat::DoubleBuffer : QPlatformWindowFormat::SingleBuffer);
 }
setGreenBufferSize()
void QPlatformWindowFormat::setGreenBufferSize (int size)
Set the preferred green buffer size to size.
Since
4.2
See also
setRedBufferSize(), setBlueBufferSize(), setAlphaBufferSize()
Definition at line 770 of file qplatformwindowformat_qpa.cpp.
Referenced by QXlibWindow::correctColorBuffers(), QEglFSScreen::createAndSetPlatformContext(), EAGLPlatformContext::EAGLPlatformContext(), QBBGLContext::QBBGLContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), QOpenKODEWindow::QOpenKODEWindow(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (size < 0) {
         qWarning("QPlatformWindowFormat::setGreenBufferSize: Cannot set negative green buffer size %d", size);
         return;
     }
     d->greenSize = size;
 }
setOption()
void QPlatformWindowFormat::setOption (QPlatformWindowFormat::FormatOptions opt)
Sets the format option to opt.
See also
testOption()
Definition at line 674 of file qplatformwindowformat_qpa.cpp.
 {
     detach();
     if (opt & 0xffff)
         d->opts |= opt;
     else
        d->opts &= ~(opt >> 16);
 }
setRedBufferSize()
void QPlatformWindowFormat::setRedBufferSize (int size)
Set the preferred red buffer size to size.
Since
4.2
See also
setGreenBufferSize(), setBlueBufferSize(), setAlphaBufferSize()
Definition at line 735 of file qplatformwindowformat_qpa.cpp.
Referenced by QXlibWindow::correctColorBuffers(), QEglFSScreen::createAndSetPlatformContext(), EAGLPlatformContext::EAGLPlatformContext(), QBBGLContext::QBBGLContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), QOpenKODEWindow::QOpenKODEWindow(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (size < 0) {
         qWarning("QPlatformWindowFormat::setRedBufferSize: Cannot set negative red buffer size %d", size);
         return;
     }
     d->redSize = size;
 }
setRgba()
void QPlatformWindowFormat::setRgba (bool enable)
If enable is true sets RGBA mode.
If enable is false sets color index mode.
The default color mode is RGBA.
RGBA is the preferred mode for most OpenGL applications. In RGBA color mode you specify colors as red + green + blue + alpha quadruplets.
In color index mode you specify an index into a color lookup table.
See also
rgba()
Definition at line 366 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), qglx_platformWindowFromGLXFBConfig(), and qt_qPlatformWindowFormatFromConfig().
 {
     setOption(enable ? QPlatformWindowFormat::Rgba : QPlatformWindowFormat::ColorIndex);
 }
setSampleBuffers()
void QPlatformWindowFormat::setSampleBuffers (bool enable)
If enable is true, a GL context with multisample buffer support is picked; otherwise ignored.
See also
sampleBuffers(), setSamples(), samples()
Definition at line 545 of file qplatformwindowformat_qpa.cpp.
Referenced by QEglFSScreen::createAndSetPlatformContext(), EAGLPlatformContext::EAGLPlatformContext(), qglx_platformWindowFromGLXFBConfig(), and qglx_reducePlatformWindowFormat().
 {
     setOption(enable ? QPlatformWindowFormat::SampleBuffers : QPlatformWindowFormat::NoSampleBuffers);
 }
setSamples()
void QPlatformWindowFormat::setSamples (int numSamples)
Set the preferred number of samples per pixel when multisampling is enabled to numSamples.
By default, the highest number of samples available is used.
See also
setSampleBuffers(), sampleBuffers(), samples()
Definition at line 569 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), qglx_platformWindowFromGLXFBConfig(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (numSamples < 0) {
         qWarning("QPlatformWindowFormat::setSamples: Cannot have negative number of samples per pixel %d", numSamples);
         return;
     }
     d->numSamples = numSamples;
     setSampleBuffers(numSamples > 0);
 }
setSharedContext()
void QPlatformWindowFormat::setSharedContext (QPlatformGLContext * context)
Definition at line 632 of file qplatformwindowformat_qpa.cpp.
Referenced by qDeleteQGLContext(), and QWaylandGLContext::QWaylandGLContext().
 {
     d->sharedContext = context;
 }
setStencil()
void QPlatformWindowFormat::setStencil (bool enable)
If enable is true enables the stencil buffer; otherwise disables the stencil buffer.
The stencil buffer is enabled by default.
The stencil buffer masks certain parts of the drawing area so that masked parts are not drawn on.
See also
stencil(), setStencilBufferSize()
Definition at line 457 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), and qglx_reducePlatformWindowFormat().
 {
     setOption(enable ? QPlatformWindowFormat::StencilBuffer: QPlatformWindowFormat::NoStencilBuffer);
 }
setStencilBufferSize()
void QPlatformWindowFormat::setStencilBufferSize (int size)
Set the preferred stencil buffer size to size.
See also
stencilBufferSize(), setStencil(), stencil()
Definition at line 889 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), and qt_qPlatformWindowFormatFromConfig().
 {
     detach();
     if (size < 0) {
         qWarning("QPlatformWindowFormat::setStencilBufferSize: Cannot set negative stencil buffer size %d", size);
         return;
     }
     d->stencilSize = size;
     setStencil(size > 0);
 }
setStereo()
void QPlatformWindowFormat::setStereo (bool enable)
If enable is true enables stereo buffering; otherwise disables stereo buffering.
Stereo buffering is disabled by default.
Stereo buffering provides extra color buffers to generate left-eye and right-eye images.
See also
stereo()
Definition at line 487 of file qplatformwindowformat_qpa.cpp.
Referenced by EAGLPlatformContext::EAGLPlatformContext(), QDirectFbGLContext::QDirectFbGLContext(), qglx_platformWindowFromGLXFBConfig(), qglx_reducePlatformWindowFormat(), and qt_qPlatformWindowFormatFromConfig().
 {
     setOption(enable ? QPlatformWindowFormat::StereoBuffers : QPlatformWindowFormat::NoStereoBuffers);
 }
setSwapInterval()
void QPlatformWindowFormat::setSwapInterval (int interval)
Set the preferred swap interval.
Since
4.2
This can be used to sync the GL drawing into a system window to the vertical refresh of the screen. Setting an interval value of 0 will turn the vertical refresh syncing off, any value higher than 0 will turn the vertical syncing on.
Under Windows and under X11, where the WGL_EXT_swap_control and GLX_SGI_video_sync extensions are used, the interval parameter can be used to set the minimum number of video frames that are displayed before a buffer swap will occur. In effect, setting the interval to 10, means there will be 10 vertical retraces between every buffer swap.
Under Windows the WGL_EXT_swap_control extension has to be present, and under X11 the GLX_SGI_video_sync extension has to be present.
Definition at line 601 of file qplatformwindowformat_qpa.cpp.
 {
     detach();
     d->swapInterval = interval;
 }
setWindowApi()
void QPlatformWindowFormat::setWindowApi (QPlatformWindowFormat::WindowApi api)
Definition at line 621 of file qplatformwindowformat_qpa.cpp.
Referenced by QEglFSScreen::createAndSetPlatformContext(), EAGLPlatformContext::EAGLPlatformContext(), QBBIntegration::QBBIntegration(), and qDeleteQGLContext().
 {
     detach();
     d->windowApi = api;
 }
setWindowSurface()
void QPlatformWindowFormat::setWindowSurface (bool enable)
If enable is true a top level QWidget will create a QWindowSurface at creation;.
otherwise the QWidget will only have a QPlatformWindow.
This is useful for QGLWidget where the QPlatformGLContext controls the surface.
Definition at line 663 of file qplatformwindowformat_qpa.cpp.
Referenced by qDeleteQGLContext().
 {
     setOption(enable ? QPlatformWindowFormat::HasWindowSurface : QPlatformWindowFormat::NoWindowSurface);
 }
sharedGLContext()
QPlatformGLContext * QPlatformWindowFormat::sharedGLContext () const
Definition at line 637 of file qplatformwindowformat_qpa.cpp.
Referenced by QXlibWindow::glContext(), QGLXContext::QGLXContext(), and QWaylandGLContext::QWaylandGLContext().
 {
     return d->sharedContext;
 }
stencil()
bool QPlatformWindowFormat::stencil () const inline
Returns true if the stencil buffer is enabled; otherwise returns false.
The stencil buffer is enabled by default.
See also
setStencil(), setStencilBufferSize()
Definition at line 205 of file qplatformwindowformat_qpa.h.
Referenced by q_createConfigAttributesFromFormat(), qglx_buildSpec(), and qglx_reducePlatformWindowFormat().
 {
     return testOption(QPlatformWindowFormat::StencilBuffer);
 }
stencilBufferSize()
int QPlatformWindowFormat::stencilBufferSize () const
Returns the stencil buffer size.
See also
stencil(), setStencil(), setStencilBufferSize()
Definition at line 905 of file qplatformwindowformat_qpa.cpp.
Referenced by q_createConfigAttributesFromFormat(), and qglx_buildSpec().
 {
    return d->stencilSize;
 }
stereo()
bool QPlatformWindowFormat::stereo () const inline
Returns true if stereo buffering is enabled; otherwise returns false.
Stereo buffering is disabled by default.
See also
setStereo()
Definition at line 210 of file qplatformwindowformat_qpa.h.
Referenced by qglx_buildSpec(), and qglx_reducePlatformWindowFormat().
 {
     return testOption(QPlatformWindowFormat::StereoBuffers);
 }
swapInterval()
int QPlatformWindowFormat::swapInterval () const
Returns the currently set swap interval.
Since
4.2
-1 is returned if setting the swap interval isn't supported in the system GL implementation.
Definition at line 616 of file qplatformwindowformat_qpa.cpp.
 {
     return d->swapInterval;
 }
testOption()
bool QPlatformWindowFormat::testOption (QPlatformWindowFormat::FormatOptions opt) const
Returns true if format option opt is set; otherwise returns false.
See also
setOption()
Definition at line 691 of file qplatformwindowformat_qpa.cpp.
 {
     if (opt & 0xffff)
        return (d->opts & opt) != 0;
     else
        return (d->opts & (opt >> 16)) == 0;
 }
windowApi()
QPlatformWindowFormat::WindowApi QPlatformWindowFormat::windowApi () const
Definition at line 627 of file qplatformwindowformat_qpa.cpp.
Referenced by QBBWindow::glContext(), q_configFromQPlatformWindowFormat(), QBBGLContext::QBBGLContext(), and QBBWindow::QBBWindow().
 {
     return d->windowApi;
 }
Friends and Related Functions
operator!=
bool operator!= (const QPlatformWindowFormat & a, const QPlatformWindowFormat & b) friend
Returns false if all the options of the two QPlatformWindowFormat objects a and b are equal; otherwise returns true.
Since
4.8
Definition at line 1036 of file qplatformwindowformat_qpa.cpp.
 {
     return !(a == b);
 }
operator<<
Q_GUI_EXPORT QDebug operator<< (QDebug , const QPlatformWindowFormat &) friend
Definition at line 1042 of file qplatformwindowformat_qpa.cpp.
 {
     const QPlatformWindowFormatPrivate * const d = f.d;
     dbg.nospace() << "QGLFormat("
                   << "options " << d->opts
                   << ", depthBufferSize " << d->depthSize
                   << ", accumBufferSize " << d->accumSize
                   << ", stencilBufferSize " << d->stencilSize
                   << ", redBufferSize " << d->redSize
                   << ", greenBufferSize " << d->greenSize
                   << ", blueBufferSize " << d->blueSize
                   << ", alphaBufferSize " << d->alphaSize
                   << ", samples " << d->numSamples
                   << ", swapInterval " << d->swapInterval
                   << ')';
     return dbg.space();
 }
operator==
bool operator== (const QPlatformWindowFormat & a, const QPlatformWindowFormat & b) friend
Sets a new default QPlatformWindowFormat for overlay contexts to f.
This format is used whenever a QGLWidget is created with a format that hasOverlay() enabled.
For example, to get a double buffered overlay context (if available), use code like this:
QGLFormat f = QGLFormat::defaultOverlayFormat();
f.setDoubleBuffer(true);
QGLFormat::setDefaultOverlayFormat(f);
As usual, you can find out after widget creation whether the underlying OpenGL system was able to provide the requested specification:
// ...continued from above
MyGLWidget* myWidget = new MyGLWidget(QGLFormat(QGL::HasOverlay), ...);
if (myWidget->format().hasOverlay()) {
    // Yes, we got an overlay, let's check _its_ format:
    QGLContext* olContext = myWidget->overlayContext();
    if (olContext->format().doubleBuffer())
        ; // yes, we got a double buffered overlay
    else
        ; // no, only single buffered overlays are available
}
See also
defaultOverlayFormat()
Returns true if all the options of the two QPlatformWindowFormat objects a and b are equal; otherwise returns false.
Since
4.8
Definition at line 1008 of file qplatformwindowformat_qpa.cpp.
 {
     return (a.d == b.d) || ((int) a.d->opts == (int) b.d->opts
         && a.d->alphaSize == b.d->alphaSize
         && a.d->accumSize == b.d->accumSize
         && a.d->stencilSize == b.d->stencilSize
         && a.d->depthSize == b.d->depthSize
         && a.d->redSize == b.d->redSize
         && a.d->greenSize == b.d->greenSize
         && a.d->blueSize == b.d->blueSize
         && a.d->numSamples == b.d->numSamples
         && a.d->swapInterval == b.d->swapInterval
         && a.d->windowApi == b.d->windowApi);
 }
Properties
d
QPlatformWindowFormatPrivate* QPlatformWindowFormat::d private
Definition at line 160 of file qplatformwindowformat_qpa.h.
Referenced by operator<<(), operator=(), and QPlatformWindowFormat().
The documentation for this class was generated from the following files:
/src/gui/kernel/qplatformwindowformat_qpa.h
/src/gui/kernel/qplatformwindowformat_qpa.cpp