Qt 4.8: QDeclarativeFontValueType Class Reference
QDeclarativeFontValueType Class Reference
#include <qdeclarativevaluetype_p.h>
Public Types
enum Capitalization {
MixedCase = QFont::MixedCase, AllUppercase = QFont::AllUppercase, AllLowercase = QFont::AllLowercase, SmallCaps = QFont::SmallCaps,
Capitalize = QFont::Capitalize
}
enum FontWeight {
Light = QFont::Light, Normal = QFont::Normal, DemiBold = QFont::DemiBold, Bold = QFont::Bold,
Black = QFont::Black
}
Public Functions
bool bold () const
Capitalization capitalization () const
QString family () const
bool italic () const
qreal letterSpacing () const
bool overline () const
int pixelSize () const
qreal pointSize () const
QDeclarativeFontValueType (QObject *parent=0)
virtual void read (QObject *, int)
void setBold (bool b)
void setCapitalization (Capitalization)
void setFamily (const QString &)
void setItalic (bool b)
void setLetterSpacing (qreal spacing)
void setOverline (bool b)
void setPixelSize (int size)
void setPointSize (qreal size)
void setStrikeout (bool b)
void setUnderline (bool b)
virtual void setValue (QVariant value)
void setWeight (FontWeight)
void setWordSpacing (qreal spacing)
bool strikeout () const
bool underline () const
virtual QVariant value ()
FontWeight weight () const
qreal wordSpacing () const
virtual void write (QObject *, int, QDeclarativePropertyPrivate::WriteFlags)
Public Functions inherited from QDeclarativeValueType
QDeclarativeValueType (QObject *parent=0)
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
bool bold
Capitalization capitalization
QDeclarativeNullableValue< int > dpi
QString family
QFont font
bool italic
qreal letterSpacing
bool overline
int pixelSize
bool pixelSizeSet
qreal pointSize
bool pointSizeSet
bool strikeout
bool underline
FontWeight weight
qreal wordSpacing
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 474 of file qdeclarativevaluetype_p.h.
Enumerations
Capitalization
enum QDeclarativeFontValueType::Capitalization
Enumerator
MixedCase
AllUppercase
AllLowercase
SmallCaps
Capitalize
Definition at line 499 of file qdeclarativevaluetype_p.h.
                         { MixedCase = QFont::MixedCase,
                            AllUppercase = QFont::AllUppercase,
                            AllLowercase = QFont::AllLowercase,
                            SmallCaps = QFont::SmallCaps,
                            Capitalize = QFont::Capitalize };
FontWeight
enum QDeclarativeFontValueType::FontWeight
Enumerator
Light
Normal
DemiBold
Bold
Black
Definition at line 494 of file qdeclarativevaluetype_p.h.
                     { Light = QFont::Light,
                        Normal = QFont::Normal,
                        DemiBold = QFont::DemiBold,
                        Bold = QFont::Bold,
                        Black = QFont::Black };
Constructors and Destructors
QDeclarativeFontValueType()
QDeclarativeFontValueType::QDeclarativeFontValueType (QObject * parent = 0)
Definition at line 839 of file qdeclarativevaluetype.cpp.
 : QDeclarativeValueType(parent), pixelSizeSet(false), pointSizeSet(false)
 {
 }
Functions
bold()
bool QDeclarativeFontValueType::bold () const
Referenced by setFamily().
capitalization()
Capitalization QDeclarativeFontValueType::capitalization () const
Referenced by setPixelSize().
family()
QString QDeclarativeFontValueType::family () const
Referenced by setValue().
italic()
bool QDeclarativeFontValueType::italic () const
Referenced by setWeight().
letterSpacing()
qreal QDeclarativeFontValueType::letterSpacing () const
Referenced by setCapitalization().
overline()
bool QDeclarativeFontValueType::overline () const
Referenced by setUnderline().
pixelSize()
int QDeclarativeFontValueType::pixelSize () const
Referenced by setPointSize().
pointSize()
qreal QDeclarativeFontValueType::pointSize () const
Referenced by setStrikeout().
read()
void QDeclarativeFontValueType::read (QObject * obj, int idx) virtual
Implements QDeclarativeValueType.
Definition at line 844 of file qdeclarativevaluetype.cpp.
 {
     void *a[] = { &font, 0 };
     QMetaObject::metacall(obj, QMetaObject::ReadProperty, idx, a);
     pixelSizeSet = false;
     pointSizeSet = false;
 }
setBold()
void QDeclarativeFontValueType::setBold (bool b)
Definition at line 885 of file qdeclarativevaluetype.cpp.
 {
     font.setBold(b);
 }
setCapitalization()
void QDeclarativeFontValueType::setCapitalization (QDeclarativeFontValueType::Capitalization c)
Definition at line 992 of file qdeclarativevaluetype.cpp.
 {
     font.setCapitalization((QFont::Capitalization)c);
 }
setFamily()
void QDeclarativeFontValueType::setFamily (const QString & family)
Definition at line 875 of file qdeclarativevaluetype.cpp.
 {
     font.setFamily(family);
 }
setItalic()
void QDeclarativeFontValueType::setItalic (bool b)
Definition at line 905 of file qdeclarativevaluetype.cpp.
 {
     font.setItalic(b);
 }
setLetterSpacing()
void QDeclarativeFontValueType::setLetterSpacing (qreal spacing)
Definition at line 1002 of file qdeclarativevaluetype.cpp.
 {
     font.setLetterSpacing(QFont::AbsoluteSpacing, size);
 }
setOverline()
void QDeclarativeFontValueType::setOverline (bool b)
Definition at line 925 of file qdeclarativevaluetype.cpp.
 {
     font.setOverline(b);
 }
setPixelSize()
void QDeclarativeFontValueType::setPixelSize (int size)
Definition at line 975 of file qdeclarativevaluetype.cpp.
 {
     if (size >0) {
         if (pointSizeSet)
             qWarning() << "Both point size and pixel size set. Using pixel size.";
         font.setPixelSize(size);
         pixelSizeSet = true;
     } else {
         pixelSizeSet = false;
     }
 }
setPointSize()
void QDeclarativeFontValueType::setPointSize (qreal size)
Definition at line 950 of file qdeclarativevaluetype.cpp.
 {
     if (pixelSizeSet) {
         qWarning() << "Both point size and pixel size set. Using pixel size.";
         return;
     }
     if (size >= 0.0) {
         pointSizeSet = true;
         font.setPointSizeF(size);
     } else {
         pointSizeSet = false;
     }
 }
setStrikeout()
void QDeclarativeFontValueType::setStrikeout (bool b)
Definition at line 935 of file qdeclarativevaluetype.cpp.
 {
     font.setStrikeOut(b);
 }
setUnderline()
void QDeclarativeFontValueType::setUnderline (bool b)
Definition at line 915 of file qdeclarativevaluetype.cpp.
 {
     font.setUnderline(b);
 }
setValue()
void QDeclarativeFontValueType::setValue (QVariant value) virtual
Implements QDeclarativeValueType.
Definition at line 864 of file qdeclarativevaluetype.cpp.
 {
     font = qvariant_cast<QFont>(value);
 }
setWeight()
void QDeclarativeFontValueType::setWeight (QDeclarativeFontValueType::FontWeight w)
Definition at line 895 of file qdeclarativevaluetype.cpp.
 {
     font.setWeight((QFont::Weight)w);
 }
setWordSpacing()
void QDeclarativeFontValueType::setWordSpacing (qreal spacing)
Definition at line 1012 of file qdeclarativevaluetype.cpp.
 {
     font.setWordSpacing(size);
 }
strikeout()
bool QDeclarativeFontValueType::strikeout () const
Referenced by setOverline().
underline()
bool QDeclarativeFontValueType::underline () const
Referenced by setItalic().
value()
QVariant QDeclarativeFontValueType::value () virtual
Implements QDeclarativeValueType.
Definition at line 859 of file qdeclarativevaluetype.cpp.
Referenced by setValue().
 {
     return QVariant(font);
 }
weight()
FontWeight QDeclarativeFontValueType::weight () const
Referenced by setBold().
wordSpacing()
qreal QDeclarativeFontValueType::wordSpacing () const
Referenced by setLetterSpacing().
write()
void QDeclarativeFontValueType::write (QObject * obj, int idx, QDeclarativePropertyPrivate::WriteFlags flags) virtual
Implements QDeclarativeValueType.
Definition at line 852 of file qdeclarativevaluetype.cpp.
 {
     int status = -1;
     void *a[] = { &font, 0, &status, &flags };
     QMetaObject::metacall(obj, QMetaObject::WriteProperty, idx, a);
 }
Properties
bold
bool QDeclarativeFontValueType::bold private
Definition at line 481 of file qdeclarativevaluetype_p.h.
capitalization
QDeclarativeFontValueType::Capitalization QDeclarativeFontValueType::capitalization private
Definition at line 489 of file qdeclarativevaluetype_p.h.
dpi
QDeclarativeNullableValue<int> QDeclarativeFontValueType::dpi mutable private
Definition at line 552 of file qdeclarativevaluetype_p.h.
Referenced by setPointSize(), and setStrikeout().
family
QString QDeclarativeFontValueType::family private
Definition at line 480 of file qdeclarativevaluetype_p.h.
font
QFont QDeclarativeFontValueType::font private
Definition at line 549 of file qdeclarativevaluetype_p.h.
Referenced by read(), setBold(), setCapitalization(), setFamily(), setItalic(), setLetterSpacing(), setOverline(), setPixelSize(), setPointSize(), setStrikeout(), setUnderline(), setValue(), setWeight(), setWordSpacing(), value(), and write().
italic
bool QDeclarativeFontValueType::italic private
Definition at line 483 of file qdeclarativevaluetype_p.h.
letterSpacing
qreal QDeclarativeFontValueType::letterSpacing private
Definition at line 490 of file qdeclarativevaluetype_p.h.
overline
bool QDeclarativeFontValueType::overline private
Definition at line 485 of file qdeclarativevaluetype_p.h.
pixelSize
int QDeclarativeFontValueType::pixelSize private
Definition at line 488 of file qdeclarativevaluetype_p.h.
pixelSizeSet
bool QDeclarativeFontValueType::pixelSizeSet private
Definition at line 550 of file qdeclarativevaluetype_p.h.
Referenced by read(), setPixelSize(), and setPointSize().
pointSize
qreal QDeclarativeFontValueType::pointSize private
Definition at line 487 of file qdeclarativevaluetype_p.h.
pointSizeSet
bool QDeclarativeFontValueType::pointSizeSet private
Definition at line 551 of file qdeclarativevaluetype_p.h.
Referenced by read(), setPixelSize(), and setPointSize().
strikeout
bool QDeclarativeFontValueType::strikeout private
Definition at line 486 of file qdeclarativevaluetype_p.h.
underline
bool QDeclarativeFontValueType::underline private
Definition at line 484 of file qdeclarativevaluetype_p.h.
weight
QDeclarativeFontValueType::FontWeight QDeclarativeFontValueType::weight private
Definition at line 482 of file qdeclarativevaluetype_p.h.
wordSpacing
qreal QDeclarativeFontValueType::wordSpacing private
Definition at line 491 of file qdeclarativevaluetype_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativevaluetype_p.h
/src/declarative/qml/qdeclarativevaluetype.cpp