Qt 4.8: QPatternist::CallTemplate Class Reference
QPatternist::CallTemplate Class Reference
Implements xsl:call-template.
#include <qcalltemplate_p.h>
Public Types
typedef QExplicitlySharedDataPointer< CallTemplate > Ptr
Public Types inherited from QPatternist::UnlimitedContainer
enum CardinalityComputation { ProductOfCardinality, UnionOfCardinality }
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Public Functions
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
virtual Expression::Ptr body () const
Returns the body of the function/template/component that is being called.
virtual CallTargetDescription::Ptr callTargetDescription () const
CallTemplate (const QXmlName &name, const WithParam::Hash &withParams)
virtual bool configureRecursion (const CallTargetDescription::Ptr &sign)
virtual Properties dependencies () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual Properties properties () const
void setTemplate (const Template::Ptr &templ)
virtual SequenceType::Ptr staticType () const
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
Public Functions inherited from QPatternist::TemplateInvoker
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
virtual SequenceType::List expectedOperandTypes () const
const WithParam::Hash & withParams () const
Public Functions inherited from QPatternist::CallSite
bool isRecursive () const
QXmlName name () const
void setIsRecursive (const bool value)
Public Functions inherited from QPatternist::UnlimitedContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &list)
UnlimitedContainer (const Expression::List &operands=Expression::List())
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual QString description () const
virtual Item evaluateSingleton (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
virtual ID id () const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual PatternPriority patternPriority () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Properties
Template::Ptr m_template
Additional Inherited Members
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Public Variables inherited from QPatternist::TemplateInvoker
WithParam::Hash m_withParams
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::TemplateInvoker
TemplateInvoker (const WithParam::Hash &withParams, const QXmlName &name=QXmlName())
Protected Functions inherited from QPatternist::CallSite
CallSite (const QXmlName &name=QXmlName())
Protected Functions inherited from QPatternist::UnlimitedContainer
template<CardinalityComputation suppliedCard>
SequenceType::Ptr operandsUnionType () const
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Protected Variables inherited from QPatternist::UnlimitedContainer
Expression::List m_operands
Detailed Description
Implements xsl:call-template.
Since
4.5
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 71 of file qcalltemplate_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<CallTemplate> QPatternist::CallTemplate::Ptr
Definition at line 74 of file qcalltemplate_p.h.
Constructors and Destructors
CallTemplate()
CallTemplate::CallTemplate (const QXmlName & name, const WithParam::Hash & withParams)
Definition at line 50 of file qcalltemplate.cpp.
                                                             : TemplateInvoker(withParams, name)
 {
 }
Functions
accept()
ExpressionVisitorResult::Ptr CallTemplate::accept (const ExpressionVisitor::Ptr & visitor) const virtual
Implements QPatternist::Expression.
Definition at line 132 of file qcalltemplate.cpp.
 {
     return visitor->visit(this);
 }
body()
Expression::Ptr CallTemplate::body () const virtual
Returns the body of the function/template/component that is being called.
Implements QPatternist::CallSite.
Definition at line 143 of file qcalltemplate.cpp.
Referenced by setTemplate().
 {
     return m_template->body;
 }
callTargetDescription()
CallTargetDescription::Ptr CallTemplate::callTargetDescription () const virtual
Implements QPatternist::CallSite.
Definition at line 148 of file qcalltemplate.cpp.
Referenced by setTemplate().
 {
     return CallTargetDescription::Ptr();
 }
configureRecursion()
bool CallTemplate::configureRecursion (const CallTargetDescription::Ptr & sign) virtual
Called in the earliest stages of the compilation process. sign can be any function signature for a user declared function. If sign matches this UserFunctionCallsite, it means the UserFunction represented by sign is recursive and that this UserFunctionCallsite should take appropriate measures.
Returns
true if is recursive, otherwise false
Implements QPatternist::CallSite.
Definition at line 137 of file qcalltemplate.cpp.
Referenced by setTemplate().
 {
     Q_UNUSED(sign);
     return false;
 }
dependencies()
Expression::Properties CallTemplate::dependencies () const virtual
Recursively computes through all descendants until a Property is encount
Reimplemented from QPatternist::Expression.
Definition at line 119 of file qcalltemplate.cpp.
 {
     if(m_template && !isRecursive())
         return m_template->dependencies();
     else
         return Properties();
 }
evaluateEBV()
bool CallTemplate::evaluateEBV (const DynamicContext::Ptr & context) const virtual
Determines the Effective Boolean Value of the expression.
The Effective Boolean Value of a value is not necessarily the same as converting the value to a new value of type xs:boolean.
Note that this function cannot return the empty sequence, evaluateSingleton() must be overridden in order to be able to do that.
The default implementation results in a type error. Hence, this function must be overridden if such behavior is not of interest.
See also
XML Path Language (XPath) 2.0, 2.4.3 Effective Boolean Value
Reimplemented from QPatternist::Expression.
Definition at line 61 of file qcalltemplate.cpp.
 {
     Q_ASSERT(m_template);
     return m_template->body->evaluateEBV(m_template->createContext(this, context, true));
 }
evaluateSequence()
Item::Iterator::Ptr CallTemplate::evaluateSequence (const DynamicContext::Ptr & context) const virtual
Evaluate this Expression by iterating over it. This is a central function for evaluating expressions.
Expressions must always always return a valid QAbstractXmlForwardIterator and may never return 0. If an empty result is of interest to be returned, the EmptyIterator should be returned.
The default implementation returns a SingletonIterator over the item returned from evaluateSingleton().
Note
This function may raise an exception when calling, not only when QAbstractXmlForwardIterator::next() is called on the return value. This is because in some cases evaluateSingleton() is called directly.
Reimplemented from QPatternist::Expression.
Definition at line 55 of file qcalltemplate.cpp.
 {
     Q_ASSERT(m_template);
     return m_template->body->evaluateSequence(m_template->createContext(this, context, true));
 }
evaluateToSequenceReceiver()
void CallTemplate::evaluateToSequenceReceiver (const DynamicContext::Ptr & context) const virtual
Evaluates this Expression by sending its output to DynamicContext::outputReceiver().
Reimplemented from QPatternist::Expression.
Definition at line 67 of file qcalltemplate.cpp.
 {
     Q_ASSERT(m_template);
     m_template->body->evaluateToSequenceReceiver(m_template->createContext(this, context, true));
 }
properties()
Expression::Properties CallTemplate::properties () const virtual
Returns
a bitwise OR'd value of properties, describing the characteristics of the expression. These properties affects how this Expression is treated in for example type checking stages.
The default implementation returns 0. Override and let the function return a different value, if that's of interest.
An important decision when re-implementing properties() is whether to OR in the properties() of ones operands. For instance, if an operand has RequiresFocus set, that flag nost likely applies to the apparent as well, since it depends on its operand.
See also
deepProperties()
Returns
Expression::None, meaning no special properties
Reimplemented from QPatternist::Expression.
Definition at line 105 of file qcalltemplate.cpp.
 {
     Q_ASSERT(!m_template || m_template->body);
     /* We may be called before our m_template is resolved, namely when we're
      * the body of a variable. In that case querytransformparser.ypp will
      * manually call TypeChecker::applyFunctionConversion(), which is before
      * ExpressionFactory::createExpression() has resolved us. */
     if(m_template && !isRecursive())
         return m_template->properties();
     else
         return Properties();
 }
setTemplate()
void QPatternist::CallTemplate::setTemplate (const Template::Ptr & templ) inline
Definition at line 101 of file qcalltemplate_p.h.
Referenced by QPatternist::ExpressionFactory::createExpression().
         {
             m_template = templ;
         }
staticType()
SequenceType::Ptr CallTemplate::staticType () const virtual
Returns
the static type of this Expression. For example, an 'and' expression have as static type xs:boolean
Implements QPatternist::Expression.
Definition at line 127 of file qcalltemplate.cpp.
 {
     return CommonSequenceTypes::ZeroOrMoreItems;
 }
typeCheck()
Expression::Ptr CallTemplate::typeCheck (const StaticContext::Ptr & context, const SequenceType::Ptr & reqType) virtual
This is a bit complicated by that we have two required types, one specified by xsl:param in the template declaration, and one on xsl:with-param.
See also
UserFunctionCallsite::expectedOperandTypes()
XSL Transformations (XSLT) Version 2.0, 10.1.1 Passing Parameters to Templates
Reimplemented from QPatternist::Expression.
Definition at line 73 of file qcalltemplate.cpp.
 {
     /* Check XTSE0680, that every @c xsl:with-param has a corresponding @c
      * xsl:param declaration. */
     {
         const WithParam::Hash::const_iterator end(m_withParams.constEnd());
         for(WithParam::Hash::const_iterator it(m_withParams.constBegin());
             it != end;
             ++it)
         {
             if(!VariableDeclaration::contains(m_template->templateParameters, it.value()->name()))
                 Template::raiseXTSE0680(context, it.value()->name(), this);
         }
     }
     const Expression::Ptr me(TemplateInvoker::typeCheck(context, reqType));
     const VariableDeclaration::List args(m_template->templateParameters);
     const VariableDeclaration::List::const_iterator end(args.constEnd());
     VariableDeclaration::List::const_iterator it(args.constBegin());
     for(; it != end; ++it)
     {
         // TODO
         Q_ASSERT((*it)->sequenceType);
     }
     return me;
 }
Properties
m_template
Template::Ptr QPatternist::CallTemplate::m_template private
Definition at line 110 of file qcalltemplate_p.h.
Referenced by body(), dependencies(), evaluateEBV(), evaluateSequence(), evaluateToSequenceReceiver(), properties(), setTemplate(), and typeCheck().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/qcalltemplate_p.h
/src/xmlpatterns/expr/qcalltemplate.cpp