Qt 4.8: QDeclarativeExpressionPrivate Class Reference
QDeclarativeExpressionPrivate Class Reference
#include <qdeclarativeexpression_p.h>
Public Functions
void _q_notify ()
virtual void emitValueChanged ()
void init (QDeclarativeContextData *, const QString &, QObject *)
void init (QDeclarativeContextData *, const QScriptValue &, QObject *)
void init (QDeclarativeContextData *, void *, QDeclarativeRefCount *, QObject *, const QString &, int)
QDeclarativeExpressionPrivate ()
QScriptValue scriptValue (QObject *secondaryScope=0, bool *isUndefined=0)
QVariant value (QObject *secondaryScope=0, bool *isUndefined=0)
~QDeclarativeExpressionPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Functions inherited from QDeclarativeQtScriptExpression
EvaluateFlags evaluateFlags () const
bool notifyOnValueChange () const
QDeclarativeQtScriptExpression ()
void resetNotifyOnChange ()
QScriptValue scriptValue (QObject *secondaryScope, bool *isUndefined)
void setEvaluateFlags (EvaluateFlags flags)
void setNotifyObject (QObject *, int)
void setNotifyOnValueChange (bool)
virtual ~QDeclarativeQtScriptExpression ()
Public Functions inherited from QDeclarativeAbstractExpression
QDeclarativeContextData * context () const
bool isValid () const
QDeclarativeAbstractExpression ()
virtual void refresh ()
void setContext (QDeclarativeContextData *)
virtual ~QDeclarativeAbstractExpression ()
Public Functions inherited from QDeclarativeDelayedError
bool addError (QDeclarativeEnginePrivate *)
QDeclarativeDelayedError ()
void removeError ()
~QDeclarativeDelayedError ()
Static Public Functions
static QScriptValue evalInObjectScope (QDeclarativeContextData *, QObject *, const QString &, const QString &, int, QScriptValue *)
static QScriptValue evalInObjectScope (QDeclarativeContextData *, QObject *, const QScriptProgram &, QScriptValue *)
static void exceptionToError (QScriptEngine *, QDeclarativeError &)
static QDeclarativeExpressionPrivate * get (QDeclarativeExpression *expr)
static QDeclarativeExpression * get (QDeclarativeExpressionPrivate *expr)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool expressionFunctionValid:1
int line
QByteArray name
QString url
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Public Variables inherited from QDeclarativeQtScriptExpression
QDeclarativeRefCount * dataRef
QString expression
QScriptValue expressionContext
QScriptValue expressionFunction
Mode expressionFunctionMode
QObject * scopeObject
Public Variables inherited from QDeclarativeDelayedError
QDeclarativeError error
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Types inherited from QDeclarativeQtScriptExpression
enum EvaluateFlag { RequiresThisObject = 0x01 }
enum Mode { SharedContext, ExplicitContext }
Detailed Description
Definition at line 175 of file qdeclarativeexpression_p.h.
Constructors and Destructors
QDeclarativeExpressionPrivate()
QDeclarativeExpressionPrivate::QDeclarativeExpressionPrivate ()
Definition at line 87 of file qdeclarativeexpression.cpp.
 : expressionFunctionValid(true), line(-1)
 {
 }
~QDeclarativeExpressionPrivate()
QDeclarativeExpressionPrivate::~QDeclarativeExpressionPrivate ()
Definition at line 92 of file qdeclarativeexpression.cpp.
 {
 }
Functions
_q_notify()
void QDeclarativeExpressionPrivate::_q_notify ()
Warning
This function is not part of the public interface.
Definition at line 801 of file qdeclarativeexpression.cpp.
 {
     emitValueChanged();
 }
emitValueChanged()
void QDeclarativeExpressionPrivate::emitValueChanged () virtual
Reimplemented in QDeclarativeBindingPrivate.
Definition at line 824 of file qdeclarativeexpression.cpp.
 {
     Q_Q(QDeclarativeExpression);
     emit q->valueChanged();
 }
evalInObjectScope() [1/2]
QScriptValue QDeclarativeExpressionPrivate::evalInObjectScope (QDeclarativeContextData * context, QObject * object, const QString & program, const QString & fileName, int lineNumber, QScriptValue * contextObject) static
Definition at line 174 of file qdeclarativeexpression.cpp.
Referenced by init(), QDeclarativeVMEMetaObject::method(), and QDeclarativeEngineDebugService::setMethodBody().
 {
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(context->engine);
     QScriptContext *scriptContext = QScriptDeclarativeClass::pushCleanContext(&ep->scriptEngine);
     if (contextObject) {
         *contextObject = ep->contextClass->newContext(context, object);
         scriptContext->pushScope(*contextObject);
     } else {
         scriptContext->pushScope(ep->contextClass->newContext(context, object));
     }
     scriptContext->pushScope(ep->globalClass->staticGlobalObject());
     QScriptValue rv = ep->scriptEngine.evaluate(program, fileName, lineNumber);
     ep->scriptEngine.popContext();
     return rv;
 }
evalInObjectScope() [2/2]
QScriptValue QDeclarativeExpressionPrivate::evalInObjectScope (QDeclarativeContextData * context, QObject * object, const QScriptProgram & program, QScriptValue * contextObject) static
Definition at line 192 of file qdeclarativeexpression.cpp.
 {
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(context->engine);
     QScriptContext *scriptContext = QScriptDeclarativeClass::pushCleanContext(&ep->scriptEngine);
     if (contextObject) {
         *contextObject = ep->contextClass->newContext(context, object);
         scriptContext->pushScope(*contextObject);
     } else {
         scriptContext->pushScope(ep->contextClass->newContext(context, object));
     }
     scriptContext->pushScope(ep->globalClass->staticGlobalObject());
     QScriptValue rv = ep->scriptEngine.evaluate(program);
     ep->scriptEngine.popContext();
     return rv;
 }
exceptionToError()
void QDeclarativeExpressionPrivate::exceptionToError (QScriptEngine * scriptEngine, QDeclarativeError & error) static
Definition at line 386 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeContextData::addImportedScript(), QDeclarativeQtScriptExpression::eval(), QDeclarativeXMLHttpRequest::printError(), and QDeclarativeWorkerScriptEnginePrivate::reportScriptException().
 {
     if (scriptEngine->hasUncaughtException() &&
         scriptEngine->uncaughtException().isError()) {
         QString fileName;
         int lineNumber = scriptEngine->uncaughtExceptionLineNumber();
         QScriptValue exception = scriptEngine->uncaughtException();
         QLatin1String fileNameProp("fileName");
         if (!exception.property(fileNameProp).toString().isEmpty()){
             fileName = exception.property(fileNameProp).toString();
         } else {
             fileName = QLatin1String("<Unknown File>");
         }
         error.setUrl(QUrl(fileName));
         error.setLine(lineNumber);
         error.setColumn(-1);
         error.setDescription(exception.toString());
     } else {
         error = QDeclarativeError();
     }
 }
get() [1/2]
static QDeclarativeExpressionPrivate* QDeclarativeExpressionPrivate::get (QDeclarativeExpression * expr) inline static
Definition at line 189 of file qdeclarativeexpression_p.h.
Referenced by QDeclarativeBoundSignal::qt_metacall().
{
         return static_cast<QDeclarativeExpressionPrivate *>(QObjectPrivate::get(expr));
     }
get() [2/2]
static QDeclarativeExpression* QDeclarativeExpressionPrivate::get (QDeclarativeExpressionPrivate * expr) inline static
Definition at line 192 of file qdeclarativeexpression_p.h.
{
         return expr->q_func();
     }
init() [1/3]
void QDeclarativeExpressionPrivate::init (QDeclarativeContextData * ctxt, const QString & expr, QObject * me)
Definition at line 96 of file qdeclarativeexpression.cpp.
 {
     expression = expr;
     QDeclarativeAbstractExpression::setContext(ctxt);
     scopeObject = me;
     expressionFunctionValid = false;
 }
init() [2/3]
void QDeclarativeExpressionPrivate::init (QDeclarativeContextData * ctxt, const QScriptValue & func, QObject * me)
Definition at line 106 of file qdeclarativeexpression.cpp.
 {
     expression = func.toString();
     QDeclarativeAbstractExpression::setContext(ctxt);
     scopeObject = me;
     expressionFunction = func;
     expressionFunctionMode = ExplicitContext;
     expressionFunctionValid = true;
 }
init() [3/3]
void QDeclarativeExpressionPrivate::init (QDeclarativeContextData * ctxt, void * expr, QDeclarativeRefCount * rc, QObject * me, const QString & srcUrl, int lineNumber)
Definition at line 119 of file qdeclarativeexpression.cpp.
 {
     url = srcUrl;
     line = lineNumber;
     if (dataRef) dataRef->release();
     dataRef = rc;
     if (dataRef) dataRef->addref();
     quint32 *exprData = (quint32 *)expr;
     QDeclarativeCompiledData *dd = (QDeclarativeCompiledData *)rc;
     expression = QString::fromRawData((QChar *)(exprData + 2), exprData[1]);
     int progIdx = *(exprData);
     bool isSharedProgram = progIdx & 0x80000000;
     progIdx &= 0x7FFFFFFF;
     QDeclarativeEngine *engine = ctxt->engine;
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     if (isSharedProgram) {
         if (!dd->cachedClosures.at(progIdx)) {
             QScriptContext *scriptContext = QScriptDeclarativeClass::pushCleanContext(scriptEngine);
             scriptContext->pushScope(ep->contextClass->newSharedContext());
             scriptContext->pushScope(ep->globalClass->staticGlobalObject());
             dd->cachedClosures[progIdx] = new QScriptValue(scriptEngine->evaluate(expression, url, line));
             scriptEngine->popContext();
         }
         expressionFunction = *dd->cachedClosures.at(progIdx);
         expressionFunctionMode = SharedContext;
         expressionFunctionValid = true;
     } else {
         if (!dd->cachedPrograms.at(progIdx)) {
             dd->cachedPrograms[progIdx] = new QScriptProgram(expression, url, line);
         }
         expressionFunction = evalInObjectScope(ctxt, me, *dd->cachedPrograms.at(progIdx),
                                                      &expressionContext);
         expressionFunctionMode = ExplicitContext;
         expressionFunctionValid = true;
     }
     QDeclarativeAbstractExpression::setContext(ctxt);
     scopeObject = me;
 }
scriptValue()
QScriptValue QDeclarativeExpressionPrivate::scriptValue (QObject * secondaryScope = 0, bool * isUndefined = 0)
Definition at line 631 of file qdeclarativeexpression.cpp.
 {
     if (!expressionFunctionValid) {
         QDeclarativeEngine *engine = context()->engine;
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
         QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
         QScriptContext *scriptContext = QScriptDeclarativeClass::pushCleanContext(scriptEngine);
         expressionContext = ep->contextClass->newContext(context(), scopeObject);
         scriptContext->pushScope(expressionContext);
         scriptContext->pushScope(ep->globalClass->staticGlobalObject());
         QDeclarativeRewrite::RewriteBinding rewriteBinding;
         rewriteBinding.setName(name);
         bool ok = true;
         const QString code = rewriteBinding(expression, &ok);
         if (ok)
             expressionFunction = scriptEngine->evaluate(code, url, line);
         scriptEngine->popContext();
         expressionFunctionMode = ExplicitContext;
         expressionFunctionValid = true;
     }
     return QDeclarativeQtScriptExpression::scriptValue(secondaryScope, isUndefined);
 }
value()
QVariant QDeclarativeExpressionPrivate::value (QObject * secondaryScope = 0, bool * isUndefined = 0)
Definition at line 659 of file qdeclarativeexpression.cpp.
Referenced by QDeclarativeBoundSignal::qt_metacall().
 {
     Q_Q(QDeclarativeExpression);
     if (!context() || !context()->isValid()) {
         qWarning("QDeclarativeExpression: Attempted to evaluate an expression in an invalid context");
         return QVariant();
     }
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(q->engine());
     return ep->scriptValueToVariant(scriptValue(secondaryScope, isUndefined), qMetaTypeId<QList<QObject*> >());
 }
Properties
expressionFunctionValid
bool QDeclarativeExpressionPrivate::expressionFunctionValid
Definition at line 205 of file qdeclarativeexpression_p.h.
Referenced by init().
line
int QDeclarativeExpressionPrivate::line
Definition at line 208 of file qdeclarativeexpression_p.h.
Referenced by init().
name
QByteArray QDeclarativeExpressionPrivate::name
Definition at line 209 of file qdeclarativeexpression_p.h.
url
QString QDeclarativeExpressionPrivate::url
Definition at line 207 of file qdeclarativeexpression_p.h.
Referenced by init().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeexpression_p.h
/src/declarative/qml/qdeclarativeexpression.cpp