Qt 4.8: QPixmapDropShadowFilter Class Reference
QPixmapDropShadowFilter Class Reference
The QPixmapDropShadowFilter class is a convenience class for drawing pixmaps with drop shadows.
#include <qpixmapfilter_p.h>
Public Functions
qreal blurRadius () const
Returns the radius in pixels of the blur on the drop shadow.
QRectF boundingRectFor (const QRectF &rect) const
QColor color () const
Returns the color of the drop shadow.
void draw (QPainter *p, const QPointF &pos, const QPixmap &px, const QRectF &src=QRectF()) const
QPointF offset () const
Returns the shadow offset in pixels.
QPixmapDropShadowFilter (QObject *parent=0)
Constructs drop shadow filter.
void setBlurRadius (qreal radius)
Sets the radius in pixels of the blur on the drop shadow to the radius specified.
void setColor (const QColor &color)
Sets the color of the drop shadow to the color specified.
void setOffset (const QPointF &offset)
Sets the shadow offset in pixels to the offset specified.
void setOffset (qreal dx, qreal dy)
Sets the shadow offset in pixels to be the displacement specified by the horizontal dx and vertical dy coordinates.
~QPixmapDropShadowFilter ()
Destroys drop shadow filter.
Public Functions inherited from QPixmapFilter
FilterType type () const
Returns the type of the filter.
virtual ~QPixmapFilter ()=0
Destroys the pixmap filter.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Public Types inherited from QPixmapFilter
enum FilterType {
ConvolutionFilter, ColorizeFilter, DropShadowFilter, BlurFilter,
UserFilter = 1024
}
This enum describes the types of filter that can be applied to pixmaps.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QPixmapFilter
QPixmapFilter (QPixmapFilterPrivate &d, FilterType type, QObject *parent)
QPixmapFilter (FilterType type, QObject *parent)
Constructs a default QPixmapFilter with the given type.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPixmapDropShadowFilter class is a convenience class for drawing pixmaps with drop shadows.
Since
4.5
The drop shadow is produced by taking a copy of the source pixmap and applying a color to the copy using a QPainter::CompositionMode_DestinationIn operation. This produces a homogeneously-colored pixmap which is then drawn using a QPixmapConvolutionFilter at an offset. The original pixmap is drawn on top.
The QPixmapDropShadowFilter class provides some customization options to specify how the drop shadow should appear. The color of the drop shadow can be modified using the setColor() function, the drop shadow offset can be modified using the setOffset() function, and the blur radius of the drop shadow can be changed through the setBlurRadius() function.
By default, the drop shadow is a dark gray shadow, blurred with a radius of 1 at an offset of 8 pixels towards the lower right.
Example:
QPixmapDropShadowFilter *myFilter = new QPixmapDropShadowFilter;
myFilter->draw(painter, QPoint(0, 0), originalPixmap);
See also
QPixmapColorizeFilter, QPixmapConvolutionFilter
Warning
This function is not part of the public interface.
Definition at line 168 of file qpixmapfilter_p.h.
Constructors and Destructors
QPixmapDropShadowFilter()
QPixmapDropShadowFilter::QPixmapDropShadowFilter (QObject * parent = 0)
Constructs drop shadow filter.
Warning
This function is not part of the public interface.
Definition at line 1228 of file qpixmapfilter.cpp.
     : QPixmapFilter(*new QPixmapDropShadowFilterPrivate, DropShadowFilter, parent)
 {
 }
~QPixmapDropShadowFilter()
QPixmapDropShadowFilter::~QPixmapDropShadowFilter ()
Destroys drop shadow filter.
Warning
This function is not part of the public interface.
Definition at line 1238 of file qpixmapfilter.cpp.
 {
 }
Functions
blurRadius()
qreal QPixmapDropShadowFilter::blurRadius () const
Returns the radius in pixels of the blur on the drop shadow.
A smaller radius results in a sharper shadow.
See also
color(), offset()
Warning
This function is not part of the public interface.
Definition at line 1251 of file qpixmapfilter.cpp.
Referenced by QVGPixmapDropShadowFilter::draw().
 {
     Q_D(const QPixmapDropShadowFilter);
     return d->radius;
 }
boundingRectFor()
QRectF QPixmapDropShadowFilter::boundingRectFor (const QRectF & rect) const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPixmapFilter.
Definition at line 1342 of file qpixmapfilter.cpp.
 {
     Q_D(const QPixmapDropShadowFilter);
     return rect.united(rect.translated(d->offset).adjusted(-d->radius, -d->radius, d->radius, d->radius));
 }
color()
QColor QPixmapDropShadowFilter::color () const
Returns the color of the drop shadow.
See also
blurRadius(), offset()
Warning
This function is not part of the public interface.
Definition at line 1279 of file qpixmapfilter.cpp.
Referenced by QVGPixmapDropShadowFilter::draw(), and setColor().
 {
     Q_D(const QPixmapDropShadowFilter);
     return d->color;
 }
draw()
void QPixmapDropShadowFilter::draw (QPainter * p, const QPointF & pos, const QPixmap & px, const QRectF & src = QRectF()) const virtual
Warning
This function is not part of the public interface.
Implements QPixmapFilter.
Reimplemented in QVGPixmapDropShadowFilter, and QGLPixmapFilter< QPixmapDropShadowFilter >.
Definition at line 1351 of file qpixmapfilter.cpp.
Referenced by QVGPixmapDropShadowFilter::draw(), and draw().
 {
     Q_D(const QPixmapDropShadowFilter);
     if (px.isNull())
         return;
     QPixmapFilter *filter = p->paintEngine() && p->paintEngine()->isExtended() ?
         static_cast<QPaintEngineEx *>(p->paintEngine())->pixmapFilter(type(), this) : 0;
     QPixmapDropShadowFilter *dropShadowFilter = static_cast<QPixmapDropShadowFilter*>(filter);
     if (dropShadowFilter) {
         dropShadowFilter->setColor(d->color);
         dropShadowFilter->setBlurRadius(d->radius);
         dropShadowFilter->setOffset(d->offset);
         dropShadowFilter->draw(p, pos, px, src);
         return;
     }
     QImage tmp(px.size(), QImage::Format_ARGB32_Premultiplied);
     tmp.fill(0);
     QPainter tmpPainter(&tmp);
     tmpPainter.setCompositionMode(QPainter::CompositionMode_Source);
     tmpPainter.drawPixmap(d->offset, px);
     tmpPainter.end();
     // blur the alpha channel
     QImage blurred(tmp.size(), QImage::Format_ARGB32_Premultiplied);
     blurred.fill(0);
     QPainter blurPainter(&blurred);
     qt_blurImage(&blurPainter, tmp, d->radius, false, true);
     blurPainter.end();
     // blacken the image...
     QPainter blackenPainter(&blurred);
     blackenPainter.setCompositionMode(QPainter::CompositionMode_SourceIn);
     blackenPainter.fillRect(blurred.rect(), d->color);
     blackenPainter.end();
     // draw the blurred drop shadow...
     p->drawImage(pos, blurred);
     // Draw the actual pixmap...
     p->drawPixmap(pos, px, src);
 }
offset()
QPointF QPixmapDropShadowFilter::offset () const
Returns the shadow offset in pixels.
See also
blurRadius(), color()
Warning
This function is not part of the public interface.
Definition at line 1305 of file qpixmapfilter.cpp.
Referenced by QVGPixmapDropShadowFilter::draw(), and setOffset().
 {
     Q_D(const QPixmapDropShadowFilter);
     return d->offset;
 }
setBlurRadius()
void QPixmapDropShadowFilter::setBlurRadius (qreal radius)
Sets the radius in pixels of the blur on the drop shadow to the radius specified.
Using a smaller radius results in a sharper shadow.
See also
setColor(), setOffset()
Warning
This function is not part of the public interface.
Definition at line 1266 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapDropShadowFilter);
     d->radius = radius;
 }
setColor()
void QPixmapDropShadowFilter::setColor (const QColor & color)
Sets the color of the drop shadow to the color specified.
See also
setBlurRadius(), setOffset()
Warning
This function is not part of the public interface.
Definition at line 1292 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapDropShadowFilter);
     d->color = color;
 }
setOffset() [1/2]
void QPixmapDropShadowFilter::setOffset (const QPointF & offset)
Sets the shadow offset in pixels to the offset specified.
See also
setBlurRadius(), setColor()
Warning
This function is not part of the public interface.
Definition at line 1318 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapDropShadowFilter);
     d->offset = offset;
 }
setOffset() [2/2]
void QPixmapDropShadowFilter::setOffset (qreal dx, qreal dy) inline
Sets the shadow offset in pixels to be the displacement specified by the horizontal dx and vertical dy coordinates.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setBlurRadius(), setColor()
Warning
This function is not part of the public interface.
Definition at line 188 of file qpixmapfilter_p.h.
Referenced by setOffset().
 { setOffset(QPointF(dx, dy)); }
The documentation for this class was generated from the following files:
/src/gui/image/qpixmapfilter_p.h
/src/gui/image/qpixmapfilter.cpp