Qt 4.8: QPrinter Class Reference
QPrinter Class Reference
The QPrinter class is a paint device that paints on a printer.
#include <qprinter.h>
Public Types
enum ColorMode { GrayScale, Color }
This enum type is used to indicate whether QPrinter should print in color or not.
enum DuplexMode { DuplexNone = 0, DuplexAuto, DuplexLongSide, DuplexShortSide }
This enum is used to indicate whether printing will occur on one or both sides of each sheet of paper (simplex or duplex printing).
enum Orientation { Portrait, Landscape }
This enum type (not to be confused with Orientation) is used to specify each page's orientation.
enum OutputFormat { NativeFormat, PdfFormat, PostScriptFormat }
The OutputFormat enum is used to describe the format QPrinter should use for printing.
enum PageOrder { FirstPageFirst, LastPageFirst }
This enum type is used by QPrinter to tell the application program how to print.
enum PageSize {
A4, B5, Letter, Legal,
Executive, A0, A1, A2,
A3, A5, A6, A7,
A8, A9, B0, B1,
B10, B2, B3, B4,
B6, B7, B8, B9,
C5E, Comm10E, DLE, Folio,
Ledger, Tabloid, Custom, NPageSize = Custom
}
Use QPrinter::PaperSize instead.
enum PaperSize {
A4, B5, Letter, Legal,
Executive, A0, A1, A2,
A3, A5, A6, A7,
A8, A9, B0, B1,
B10, B2, B3, B4,
B6, B7, B8, B9,
C5E, Comm10E, DLE, Folio,
Ledger, Tabloid, Custom, NPageSize = Custom,
NPaperSize = Custom
}
This enum type specifies what paper size QPrinter should use.
enum PaperSource {
OnlyOne, Lower, Middle, Manual,
Envelope, EnvelopeManual, Auto, Tractor,
SmallFormat, LargeFormat, LargeCapacity, Cassette,
FormSource, MaxPageSource
}
This enum type specifies what paper source QPrinter is to use.
enum PrinterMode { ScreenResolution, PrinterResolution, HighResolution }
This enum describes the mode the printer should work in.
enum PrinterState { Idle, Active, Aborted, Error }
enum PrintRange { AllPages, Selection, PageRange, CurrentPage }
Used to specify the print range selection option.
enum Unit {
Millimeter, Point, Inch, Pica,
Didot, Cicero, DevicePixel
}
This enum type is used to specify the measurement unit for page and paper sizes.
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Functions
bool abort ()
Aborts the current print run.
int actualNumCopies () const
Returns the number of copies that will be printed.
bool collateCopies () const
Returns true if collation is turned on when multiple copies is selected.
ColorMode colorMode () const
Returns the current color mode.
int copyCount () const
Returns the number of copies that will be printed.
QString creator () const
Returns the name of the application that created the document.
int devType () const
QString docName () const
Returns the document name.
bool doubleSidedPrinting () const
Returns true if double side printing is enabled.
DuplexMode duplex () const
Returns the current duplex mode.
bool fontEmbeddingEnabled () const
Returns true if font embedding is enabled.
int fromPage () const
Returns the number of the first page in a range of pages to be printed (the "from page" setting).
bool fullPage () const
Returns true if the origin of the printer's coordinate system is at the corner of the page and false if it is at the edge of the printable area.
HDC getDC () const
void getPageMargins (qreal *left, qreal *top, qreal *right, qreal *bottom, Unit unit) const
Returns the page margins for this printer in left, top, right, bottom.
bool isValid () const
Returns true if the printer currently selected is a valid printer in the system, or a pure PDF/PostScript printer; otherwise returns false.
bool newPage ()
Tells the printer to eject the current page and to continue printing on a new page.
int numCopies () const
Returns the number of copies to be printed.
Orientation orientation () const
Returns the orientation setting.
QString outputFileName () const
Returns the name of the output file.
OutputFormat outputFormat () const
Returns the output format for this printer.
PageOrder pageOrder () const
Returns the current page order.
QRect pageRect () const
Returns the page's rectangle; this is usually smaller than the paperRect() since the page normally has margins between its borders and the paper.
QRectF pageRect (Unit) const
Returns the page's rectangle in unit; this is usually smaller than the paperRect() since the page normally has margins between its borders and the paper.
PageSize pageSize () const
Returns the printer page size.
QPaintEngine * paintEngine () const
Returns the paint engine used by the printer.
QRect paperRect () const
Returns the paper's rectangle; this is usually larger than the pageRect().
QRectF paperRect (Unit) const
Returns the paper's rectangle in unit; this is usually larger than the pageRect().
PaperSize paperSize () const
Returns the printer paper size.
QSizeF paperSize (Unit unit) const
Returns the paper size in unit.
PaperSource paperSource () const
Returns the printer's paper source.
QPrintEngine * printEngine () const
Returns the print engine used by the printer.
QString printerName () const
Returns the printer name.
QString printerSelectionOption () const
Returns the printer options selection string.
PrinterState printerState () const
Returns the current state of the printer.
QString printProgram () const
Returns the name of the program that sends the print output to the printer.
PrintRange printRange () const
Returns the page range of the QPrinter.
QPrinter (PrinterMode mode=ScreenResolution)
Creates a new printer object with the given mode.
QPrinter (const QPrinterInfo &printer, PrinterMode mode=ScreenResolution)
Creates a new printer object with the given printer and mode.
void releaseDC (HDC hdc) const
int resolution () const
Returns the current assumed resolution of the printer, as set by setResolution() or by the printer driver.
void setCollateCopies (bool collate)
Sets the default value for collation checkbox when the print dialog appears.
void setColorMode (ColorMode)
Sets the printer's color mode to newColorMode, which can be either Color or GrayScale.
void setCopyCount (int)
Sets the number of copies to be printed to count.
void setCreator (const QString &)
Sets the name of the application that created the document to creator.
void setDocName (const QString &)
Sets the document name to name.
void setDoubleSidedPrinting (bool enable)
Enables double sided printing if doubleSided is true; otherwise disables it.
void setDuplex (DuplexMode duplex)
Enables double sided printing based on the duplex mode.
void setFontEmbeddingEnabled (bool enable)
Enabled or disables font embedding depending on enable.
void setFromTo (int fromPage, int toPage)
Sets the range of pages to be printed to cover the pages with numbers specified by from and to, where from corresponds to the first page in the range and to corresponds to the last.
void setFullPage (bool)
If fp is true, enables support for painting over the entire page; otherwise restricts painting to the printable area reported by the device.
void setNumCopies (int)
Sets the number of copies to be printed to numCopies.
void setOrientation (Orientation)
Sets the print orientation to orientation.
void setOutputFileName (const QString &)
Sets the name of the output file to fileName.
void setOutputFormat (OutputFormat format)
Sets the output format for this printer to format.
void setPageMargins (qreal left, qreal top, qreal right, qreal bottom, Unit unit)
This function sets the left, top, right and bottom page margins for this printer.
void setPageOrder (PageOrder)
Sets the page order to pageOrder.
void setPageSize (PageSize)
Sets the printer page size based on newPageSize.
void setPaperSize (PaperSize)
Sets the printer paper size to newPaperSize if that size is supported.
void setPaperSize (const QSizeF &paperSize, Unit unit)
Sets the paper size based on paperSize in unit.
void setPaperSource (PaperSource)
Sets the paper source setting to source.
void setPrinterName (const QString &)
Sets the printer name to name.
void setPrinterSelectionOption (const QString &)
Sets the printer to use option to select the printer.
void setPrintProgram (const QString &)
Sets the name of the program that should do the print job to printProg.
void setPrintRange (PrintRange range)
Sets the print range option in to be range.
void setResolution (int)
Requests that the printer prints at dpi or as near to dpi as possible.
void setWinPageSize (int winPageSize)
Sets the page size to be used by the printer under Windows to pageSize.
QList< PaperSource > supportedPaperSources () const
Returns the supported paper sizes for this printer.
QList< int > supportedResolutions () const
Returns a list of the resolutions (a list of dots-per-inch integers) that the printer says it supports.
bool supportsMultipleCopies () const
Returns true if the printer supports printing multiple copies of the same document in one job; otherwise false is returned.
int toPage () const
Returns the number of the last page in a range of pages to be printed (the "to page" setting).
int winPageSize () const
Returns the page size used by the printer under Windows.
~QPrinter ()
Destroys the printer object and frees any allocated resources.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
int metric (PaintDeviceMetric) const
Returns the metric for the given id.
void setEngines (QPrintEngine *printEngine, QPaintEngine *paintEngine)
This function is used by subclasses of QPrinter to specify custom print and paint engines (printEngine and paintEngine, respectively).
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
void init (PrinterMode mode)
Properties
QScopedPointer< QPrinterPrivate > d_ptr
Friends
class QAbstractPrintDialog
class QAbstractPrintDialogPrivate
class QPageSetupWidget
class QPrintDialogPrivate
class QPrintPreviewWidgetPrivate
class QTextDocument
Additional Inherited Members
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Variables inherited from QPaintDevice
ushort painters
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QPrinter class is a paint device that paints on a printer.
Note
This class or function is reentrant.
This device represents a series of pages of printed output, and is used in almost exactly the same way as other paint devices such as QWidget and QPixmap. A set of additional functions are provided to manage device-specific features, such as orientation and resolution, and to step through the pages in a document as it is generated.
When printing directly to a printer on Windows or Mac OS X, QPrinter uses the built-in printer drivers. On X11, QPrinter uses the Common Unix Printing System (CUPS) or the standard Unix lpr utility to send PostScript or PDF output to the printer. As an alternative, the printProgram() function can be used to specify the command or utility to use instead of the system default.
Note that setting parameters like paper size and resolution on an invalid printer is undefined. You can use QPrinter::isValid() to verify this before changing any parameters.
QPrinter supports a number of parameters, most of which can be changed by the end user through a print dialog. In general, QPrinter passes these functions onto the underlying QPrintEngine.
The most important parameters are:
setOrientation() tells QPrinter which page orientation to use.
setPaperSize() tells QPrinter what paper size to expect from the printer.
setResolution() tells QPrinter what resolution you wish the printer to provide, in dots per inch (DPI).
setFullPage() tells QPrinter whether you want to deal with the full page or just with the part the printer can draw on.
setCopyCount() tells QPrinter how many copies of the document it should print.
Many of these functions can only be called before the actual printing begins (i.e., before QPainter::begin() is called). This usually makes sense because, for example, it's not possible to change the number of copies when you are halfway through printing. There are also some settings that the user sets (through the printer dialog) and that applications are expected to obey. See QAbstractPrintDialog's documentation for more details.
When QPainter::begin() is called, the QPrinter it operates on is prepared for a new page, enabling the QPainter to be used immediately to paint the first page in a document. Once the first page has been painted, newPage() can be called to request a new blank page to paint on, or QPainter::end() can be called to finish printing. The second page and all following pages are prepared using a call to newPage() before they are painted.
The first page in a document does not need to be preceded by a call to newPage(). You only need to calling newPage() after QPainter::begin() if you need to insert a blank page at the beginning of a printed document. Similarly, calling newPage() after the last page in a document is painted will result in a trailing blank page appended to the end of the printed document.
If you want to abort the print job, abort() will try its best to stop printing. It may cancel the entire job or just part of it.
Since QPrinter can print to any QPrintEngine subclass, it is possible to extend printing support to cover new types of printing subsystem by subclassing QPrintEngine and reimplementing its interface.
See also
QPrintDialog, {Printing with Qt}
Definition at line 66 of file qprinter.h.
Enumerations
ColorMode
enum QPrinter::ColorMode
This enum type is used to indicate whether QPrinter should print in color or not.
Color print in color if available, otherwise in grayscale.
GrayScale print in grayscale, even on color printers.
Enumerator
GrayScale
Color
Definition at line 100 of file qprinter.h.
                      { GrayScale,
                        Color };
DuplexMode
enum QPrinter::DuplexMode
This enum is used to indicate whether printing will occur on one or both sides of each sheet of paper (simplex or duplex printing).
Since
4.4
DuplexNone Single sided (simplex) printing only.
DuplexAuto The printer's default setting is used to determine whether duplex printing is used.
DuplexLongSide Both sides of each sheet of paper are used for printing. The paper is turned over its longest edge before the second side is printed
DuplexShortSide Both sides of each sheet of paper are used for printing. The paper is turned over its shortest edge before the second side is printed
Enumerator
DuplexNone
DuplexAuto
DuplexLongSide
DuplexShortSide
Definition at line 139 of file qprinter.h.
                     {
         DuplexNone = 0,
         DuplexAuto,
         DuplexLongSide,
         DuplexShortSide
     };
Orientation
enum QPrinter::Orientation
This enum type (not to be confused with Orientation) is used to specify each page's orientation.
Portrait the page's height is greater than its width.
Landscape the page's width is greater than its height.
This type interacts with QPrinter::PaperSize and QPrinter::setFullPage() to determine the final size of the page available to the application.
Enumerator
Portrait
Landscape
Definition at line 78 of file qprinter.h.
 { Portrait, Landscape };
OutputFormat
enum QPrinter::OutputFormat
The OutputFormat enum is used to describe the format QPrinter should use for printing.
NativeFormat QPrinter will print output using a method defined by the platform it is running on. This mode is the default when printing directly to a printer.
PdfFormat QPrinter will generate its output as a searchable PDF file. This mode is the default when printing to a file.
PostScriptFormat QPrinter will generate its output as in the PostScript format. (This feature was introduced in Qt 4.2.)
See also
outputFormat(), setOutputFormat(), setOutputFileName()
Enumerator
NativeFormat
PdfFormat
PostScriptFormat
Definition at line 124 of file qprinter.h.
 { NativeFormat, PdfFormat, PostScriptFormat };
PageOrder
enum QPrinter::PageOrder
This enum type is used by QPrinter to tell the application program how to print.
FirstPageFirst the lowest-numbered page should be printed first.
LastPageFirst the highest-numbered page should be printed first.
Enumerator
FirstPageFirst
LastPageFirst
Definition at line 97 of file qprinter.h.
                      { FirstPageFirst,
                        LastPageFirst };
PageSize
enum QPrinter::PageSize
Use QPrinter::PaperSize instead.
A0 841 x 1189 mm
A1 594 x 841 mm
A2 420 x 594 mm
A3 297 x 420 mm
A4 210 x 297 mm, 8.26 x 11.69 inches
A5 148 x 210 mm
A6 105 x 148 mm
A7 74 x 105 mm
A8 52 x 74 mm
A9 37 x 52 mm
B0 1030 x 1456 mm
B1 728 x 1030 mm
B10 32 x 45 mm
B2 515 x 728 mm
B3 364 x 515 mm
B4 257 x 364 mm
B5 182 x 257 mm, 7.17 x 10.13 inches
B6 128 x 182 mm
B7 91 x 128 mm
B8 64 x 91 mm
B9 45 x 64 mm
C5E 163 x 229 mm
Comm10E 105 x 241 mm, U.S. Common 10 Envelope
DLE 110 x 220 mm
Executive 7.5 x 10 inches, 191 x 254 mm
Folio 210 x 330 mm
Ledger 432 x 279 mm
Legal 8.5 x 14 inches, 216 x 356 mm
Letter 8.5 x 11 inches, 216 x 279 mm
Tabloid 279 x 432 mm
Custom Unknown, or a user defined size.
NPageSize
Enumerator
A4
B5
Letter
Legal
Executive
A0
A1
A2
A3
A5
A6
A7
A8
A9
B0
B1
B10
B2
B3
B4
B6
B7
B8
B9
C5E
Comm10E
DLE
Folio
Ledger
Tabloid
Custom
NPageSize
Definition at line 87 of file qprinter.h.
                   { A4, B5, Letter, Legal, Executive,
                     A0, A1, A2, A3, A5, A6, A7, A8, A9, B0, B1,
                     B10, B2, B3, B4, B6, B7, B8, B9, C5E, Comm10E,
                     DLE, Folio, Ledger, Tabloid, Custom, NPageSize = Custom };
PaperSize
enum QPrinter::PaperSize
This enum type specifies what paper size QPrinter should use.
Since
4.4
QPrinter does not check that the paper size is available; it just uses this information, together with QPrinter::Orientation and QPrinter::setFullPage(), to determine the printable area.
The defined sizes (with setFullPage(true)) are:
A0 841 x 1189 mm
A1 594 x 841 mm
A2 420 x 594 mm
A3 297 x 420 mm
A4 210 x 297 mm, 8.26 x 11.69 inches
A5 148 x 210 mm
A6 105 x 148 mm
A7 74 x 105 mm
A8 52 x 74 mm
A9 37 x 52 mm
B0 1000 x 1414 mm
B1 707 x 1000 mm
B2 500 x 707 mm
B3 353 x 500 mm
B4 250 x 353 mm
B5 176 x 250 mm, 6.93 x 9.84 inches
B6 125 x 176 mm
B7 88 x 125 mm
B8 62 x 88 mm
B9 33 x 62 mm
B10 31 x 44 mm
C5E 163 x 229 mm
Comm10E 105 x 241 mm, U.S. Common 10 Envelope
DLE 110 x 220 mm
Executive 7.5 x 10 inches, 190.5 x 254 mm
Folio 210 x 330 mm
Ledger 431.8 x 279.4 mm
Legal 8.5 x 14 inches, 215.9 x 355.6 mm
Letter 8.5 x 11 inches, 215.9 x 279.4 mm
Tabloid 279.4 x 431.8 mm
Custom Unknown, or a user defined size.
With setFullPage(false) (the default), the metrics will be a bit smaller; how much depends on the printer in use.
NPageSize
NPaperSize
Enumerator
A4
B5
Letter
Legal
Executive
A0
A1
A2
A3
A5
A6
A7
A8
A9
B0
B1
B10
B2
B3
B4
B6
B7
B8
B9
C5E
Comm10E
DLE
Folio
Ledger
Tabloid
Custom
NPageSize
NPaperSize
Definition at line 91 of file qprinter.h.
                    { A4, B5, Letter, Legal, Executive,
                      A0, A1, A2, A3, A5, A6, A7, A8, A9, B0, B1,
                      B10, B2, B3, B4, B6, B7, B8, B9, C5E, Comm10E,
                      DLE, Folio, Ledger, Tabloid, Custom, NPageSize = Custom, NPaperSize = Custom };
PaperSource
enum QPrinter::PaperSource
This enum type specifies what paper source QPrinter is to use.
QPrinter does not check that the paper source is available; it just uses this information to try and set the paper source. Whether it will set the paper source depends on whether the printer has that particular source.
Warning
This is currently only implemented for Windows.
Auto
Cassette
Envelope
EnvelopeManual
FormSource
LargeCapacity
LargeFormat
Lower
MaxPageSource
Middle
Manual
OnlyOne
Tractor
SmallFormat
Enumerator
OnlyOne
Lower
Middle
Manual
Envelope
EnvelopeManual
Auto
Tractor
SmallFormat
LargeFormat
LargeCapacity
Cassette
FormSource
MaxPageSource
Definition at line 103 of file qprinter.h.
                      { OnlyOne,
                        Lower,
                        Middle,
                        Manual,
                        Envelope,
                        EnvelopeManual,
                        Auto,
                        Tractor,
                        SmallFormat,
                        LargeFormat,
                        LargeCapacity,
                        Cassette,
                        FormSource,
                        MaxPageSource
     };
PrinterMode
enum QPrinter::PrinterMode
This enum describes the mode the printer should work in.
It basically presets a certain resolution and working mode.
ScreenResolution Sets the resolution of the print device to the screen resolution. This has the big advantage that the results obtained when painting on the printer will match more or less exactly the visible output on the screen. It is the easiest to use, as font metrics on the screen and on the printer are the same. This is the default value. ScreenResolution will produce a lower quality output than HighResolution and should only be used for drafts.
PrinterResolution This value is deprecated. Is is equivalent to ScreenResolution on Unix and HighResolution on Windows and Mac. Due do the difference between ScreenResolution and HighResolution, use of this value may lead to non-portable printer code.
HighResolution On Windows, sets the printer resolution to that defined for the printer in use. For PostScript printing, sets the resolution of the PostScript driver to 1200 dpi.
Note
When rendering text on a QPrinter device, it is important to realize that the size of text, when specified in points, is independent of the resolution specified for the device itself. Therefore, it may be useful to specify the font size in pixels when combining text with graphics to ensure that their relative sizes are what you expect.
Enumerator
ScreenResolution
PrinterResolution
HighResolution
Definition at line 70 of file qprinter.h.
 { ScreenResolution, PrinterResolution, HighResolution };
PrinterState
enum QPrinter::PrinterState
Idle
Active
Aborted
Error
Enumerator
Idle
Active
Aborted
Error
Definition at line 119 of file qprinter.h.
                       { Idle,
                         Active,
                         Aborted,
                         Error };
PrintRange
enum QPrinter::PrintRange
Used to specify the print range selection option.
AllPages All pages should be printed.
Selection Only the selection should be printed.
PageRange The specified page range should be printed.
CurrentPage Only the current page should be printed.
See also
QAbstractPrintDialog::PrintRange
Enumerator
AllPages
Selection
PageRange
CurrentPage
Definition at line 127 of file qprinter.h.
 { AllPages, Selection, PageRange, CurrentPage };
Unit
enum QPrinter::Unit
This enum type is used to specify the measurement unit for page and paper sizes.
Since
4.4
Millimeter
Point
Inch
Pica
Didot
Cicero
DevicePixel
Note the difference between Point and DevicePixel. The Point unit is defined to be 1/72th of an inch, while the DevicePixel unit is resolution dependant and is based on the actual pixels, or dots, on the printer.
Enumerator
Millimeter
Point
Inch
Pica
Didot
Cicero
DevicePixel
Definition at line 129 of file qprinter.h.
               {
         Millimeter,
         Point,
         Inch,
         Pica,
         Didot,
         Cicero,
         DevicePixel
     };
Constructors and Destructors
QPrinter() [1/2]
QPrinter::QPrinter (PrinterMode mode = ScreenResolution) explicit
Creates a new printer object with the given mode.
Definition at line 632 of file qprinter.cpp.
     : QPaintDevice(),
       d_ptr(new QPrinterPrivate(this))
 {
     init(mode);
     QPrinterInfo defPrn(QPrinterInfo::defaultPrinter());
     if (!defPrn.isNull()) {
         setPrinterName(defPrn.printerName());
     } else if (QPrinterInfo::availablePrinters().isEmpty()
                && d_ptr->paintEngine->type() != QPaintEngine::Windows
                && d_ptr->paintEngine->type() != QPaintEngine::MacPrinter) {
         setOutputFormat(QPrinter::PdfFormat);
     }
 }
QPrinter() [2/2]
QPrinter::QPrinter (const QPrinterInfo & printer, PrinterMode mode = ScreenResolution) explicit
Creates a new printer object with the given printer and mode.
Since
4.4
Definition at line 655 of file qprinter.cpp.
     : QPaintDevice(),
       d_ptr(new QPrinterPrivate(this))
 {
     init(mode);
     setPrinterName(printer.printerName());
 }
~QPrinter()
QPrinter::~QPrinter ()
Destroys the printer object and frees any allocated resources.
If the printer is destroyed while a print job is in progress this may or may not affect the print job.
Definition at line 725 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     if (d->use_default_engine)
         delete d->printEngine;
 #ifndef QT_NO_PRINTPREVIEWWIDGET
     delete d->previewEngine;
 #endif
 }
Functions
abort()
bool QPrinter::abort ()
Aborts the current print run.
Returns true if the print run was successfully aborted and printerState() will return QPrinter::Aborted; otherwise returns false.
It is not always possible to abort a print job. For example, all the data has gone to the printer but the printer cannot or will not cancel the job when asked to.
Definition at line 1979 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     return d->printEngine->abort();
 }
actualNumCopies()
int QPrinter::actualNumCopies () const
Returns the number of copies that will be printed.
Since
4.6
The default value is 1.
This function always returns the actual value specified in the print dialog or using setNumCopies().
Use copyCount() instead.
See also
setNumCopies(), numCopies()
Definition at line 1367 of file qprinter.cpp.
 {
     return copyCount();
 }
collateCopies()
bool QPrinter::collateCopies () const
Returns true if collation is turned on when multiple copies is selected.
Since
4.1
Returns false if it is turned off when multiple copies is selected. When collating is turned off the printing of each individual page will be repeated the numCopies() amount before the next page is started. With collating turned on all pages are printed before the next copy of those pages is started.
See also
setCollateCopies()
Definition at line 1473 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::applyPrinterProperties().
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_CollateCopies).toBool();
 }
colorMode()
QPrinter::ColorMode QPrinter::colorMode () const
Returns the current color mode.
See also
setColorMode()
Definition at line 1314 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::applyPrinterProperties(), and QPrintDialogPrivate::setPrinter().
 {
     Q_D(const QPrinter);
     return QPrinter::ColorMode(d->printEngine->property(QPrintEngine::PPK_ColorMode).toInt());
 }
copyCount()
int QPrinter::copyCount () const
Returns the number of copies that will be printed.
Since
4.7
The default value is 1.
See also
setCopyCount(), supportsMultipleCopies()
Definition at line 1430 of file qprinter.cpp.
Referenced by actualNumCopies(), QPrintDialogPrivate::applyPrinterProperties(), setOutputFormat(), and QPrintDialogPrivate::setPrinter().
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_CopyCount).toInt();
 }
creator()
QString QPrinter::creator () const
Returns the name of the application that created the document.
See also
setCreator()
Definition at line 1066 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_Creator).toString();
 }
devType()
int QPrinter::devType () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 823 of file qprinter.cpp.
 {
     return QInternal::Printer;
 }
docName()
QString QPrinter::docName () const
Returns the document name.
See also
setDocName(), QPrintEngine::PrintEnginePropertyKey
Definition at line 1035 of file qprinter.cpp.
Referenced by QUnixPrintWidgetPrivate::applyPrinterProperties().
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_DocumentName).toString();
 }
doubleSidedPrinting()
bool QPrinter::doubleSidedPrinting () const
Returns true if double side printing is enabled.
Since
4.2
Currently this option is only supported on X11.
Definition at line 1695 of file qprinter.cpp.
 {
     return duplex() != DuplexNone;
 }
duplex()
QPrinter::DuplexMode QPrinter::duplex () const
Returns the current duplex mode.
Since
4.4
Currently this option is only supported on X11.
Definition at line 1727 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::applyPrinterProperties(), and doubleSidedPrinting().
 {
     Q_D(const QPrinter);
     return static_cast <DuplexMode> (d->printEngine->property(QPrintEngine::PPK_Duplex).toInt());
 }
fontEmbeddingEnabled()
bool QPrinter::fontEmbeddingEnabled () const
Returns true if font embedding is enabled.
Since
4.1
Currently this option is only supported on X11.
See also
setFontEmbeddingEnabled()
Definition at line 1642 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_FontEmbedding).toBool();
 }
fromPage()
int QPrinter::fromPage () const
Returns the number of the first page in a range of pages to be printed (the "from page" setting).
Since
4.1
Pages in a document are numbered according to the convention that the first page is page 1.
By default, this function returns a special value of 0, meaning that the "from page" setting is unset.
Note
If fromPage() and toPage() both return 0, this indicates that the whole document will be printed.
See also
setFromTo(), toPage()
Definition at line 2168 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->fromPage;
 }
fullPage()
bool QPrinter::fullPage () const
Returns true if the origin of the printer's coordinate system is at the corner of the page and false if it is at the edge of the printable area.
See setFullPage() for details and caveats.
See also
setFullPage() PaperSize
Definition at line 1542 of file qprinter.cpp.
Referenced by QTextDocument::print().
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_FullPage).toBool();
 }
getDC()
HDC QPrinter::getDC () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 2054 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->getPrinterDC();
 }
getPageMargins()
void QPrinter::getPageMargins (qreal * left, qreal * top, qreal * right, qreal * bottom, QPrinter::Unit unit) const
Returns the page margins for this printer in left, top, right, bottom.
Since
4.4
The unit of the returned margins are specified with the unit parameter.
Definition at line 1853 of file qprinter.cpp.
Referenced by QPageSetupWidget::selectPrinter(), and QPageSetupWidget::setPrinter().
 {
     Q_D(const QPrinter);
     Q_ASSERT(left && top && right && bottom);
     const qreal multiplier = qt_multiplierForUnit(unit, resolution());
     QList<QVariant> margins(d->printEngine->property(QPrintEngine::PPK_PageMargins).toList());
     *left = margins.at(0).toReal() / multiplier;
     *top = margins.at(1).toReal() / multiplier;
     *right = margins.at(2).toReal() / multiplier;
     *bottom = margins.at(3).toReal() / multiplier;
 }
init()
void QPrinter::init (PrinterMode mode) private
Definition at line 663 of file qprinter.cpp.
Referenced by QPrinter().
 {
 #if !defined(Q_WS_X11)
     if (!qApp) {
 #else
     if (!qApp || !X11) {
 #endif
         qFatal("QPrinter: Must construct a QApplication before a QPaintDevice");
         return;
     }
     Q_D(QPrinter);
     d->printerMode = mode;
     d->outputFormat = QPrinter::NativeFormat;
     d->createDefaultEngines();
 #ifndef QT_NO_PRINTPREVIEWWIDGET
     d->previewEngine = 0;
 #endif
     d->realPrintEngine = 0;
     d->realPaintEngine = 0;
 #if !defined(QT_NO_CUPS) && !defined(QT_NO_LIBRARY)
     if (QCUPSSupport::cupsVersion() >= 10200 && QCUPSSupport().currentPPD()) {
         setOutputFormat(QPrinter::PdfFormat);
         d->outputFormat = QPrinter::NativeFormat;
     }
 #endif
 }
isValid()
bool QPrinter::isValid () const
Returns true if the printer currently selected is a valid printer in the system, or a pure PDF/PostScript printer; otherwise returns false.
Since
4.4
To detect other failures check the output of QPainter::begin() or QPrinter::newPage().
    QPrinter printer;
    printer.setOutputFormat(QPrinter::PdfFormat);
    printer.setOutputFileName("/foobar/nonwritable.pdf");
    QPainter painter;
    if (! painter.begin(&printer)) { // failed to open file
        qWarning("failed to open file, is it writable?");
        return 1;
    }
    painter.drawText(10, 10, "Test");
    if (! printer.newPage()) {
        qWarning("failed in flushing page to disk, disk full?");
        return 1;
    }
    painter.drawText(10, 10, "Test 2");
    painter.end();
See also
setPrinterName()
Definition at line 895 of file qprinter.cpp.
Referenced by QTextControl::print(), and QTextDocument::print().
 {
     Q_D(const QPrinter);
 #if defined(Q_WS_X11)
     if (!qApp || !X11) {
         return false;
     }
 #endif
     return d->validPrinter;
 }
metric()
int QPrinter::metric (PaintDeviceMetric id) const protected virtual
Returns the metric for the given id.
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 1873 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->metric(id);
 }
newPage()
bool QPrinter::newPage ()
Tells the printer to eject the current page and to continue printing on a new page.
Returns true if this was successful; otherwise returns false.
Calling newPage() on an inactive QPrinter object will always fail.
Definition at line 1962 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     if (d->printEngine->printerState() != QPrinter::Active)
         return false;
     return d->printEngine->newPage();
 }
numCopies()
int QPrinter::numCopies () const
Returns the number of copies to be printed.
On Windows, Mac OS X and X11 systems that support CUPS, this will always return 1 as these operating systems can internally handle the number of copies.
On X11, this value will return the number of times the application is required to print in order to match the number specified in the printer setup dialog. This has been done since some printer drivers are not capable of buffering up the copies and in those cases the application must make an explicit call to the print code for each copy.
Use copyCount() in conjunction with supportsMultipleCopies() instead.
See also
setNumCopies(), actualNumCopies()
Definition at line 1343 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
    return d->printEngine->property(QPrintEngine::PPK_NumberOfCopies).toInt();
 }
orientation()
QPrinter::Orientation QPrinter::orientation () const
Returns the orientation setting.
This is driver-dependent, but is usually QPrinter::Portrait.
See also
setOrientation()
Definition at line 1098 of file qprinter.cpp.
Referenced by paperSize(), QPageSetupWidget::setPrinter(), and QPrintDialogPrivate::setPrinter().
 {
     Q_D(const QPrinter);
     return QPrinter::Orientation(d->printEngine->property(QPrintEngine::PPK_Orientation).toInt());
 }
outputFileName()
QString QPrinter::outputFileName () const
Returns the name of the output file.
By default, this is an empty string (indicating that the printer shouldn't print to file).
See also
QPrintEngine::PrintEnginePropertyKey
Definition at line 950 of file qprinter.cpp.
Referenced by QUnixPrintWidgetPrivate::applyPrinterProperties(), printRange(), and QPrintDialogPrivate::setPrinter().
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_OutputFileName).toString();
 }
outputFormat()
QPrinter::OutputFormat QPrinter::outputFormat () const
Returns the output format for this printer.
Since
4.1
Definition at line 813 of file qprinter.cpp.
Referenced by QUnixPrintWidgetPrivate::applyPrinterProperties(), QAbstractPageSetupDialogPrivate::setPrinter(), QPrintDialog::setVisible(), QUnixPrintWidgetPrivate::updateWidget(), and warnIfNotNative().
 {
     Q_D(const QPrinter);
     return d->outputFormat;
 }
pageOrder()
QPrinter::PageOrder QPrinter::pageOrder () const
Returns the current page order.
The default page order is FirstPageFirst.
Definition at line 1286 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::applyPrinterProperties(), and QPrintDialogPrivate::setPrinter().
 {
     Q_D(const QPrinter);
     return QPrinter::PageOrder(d->printEngine->property(QPrintEngine::PPK_PageOrder).toInt());
 }
pageRect() [1/2]
QRect QPrinter::pageRect () const
Returns the page's rectangle; this is usually smaller than the paperRect() since the page normally has margins between its borders and the paper.
The unit of the returned rectangle is DevicePixel.
See also
paperSize()
Definition at line 1800 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_PageRect).toRect();
 }
pageRect() [2/2]
QRectF QPrinter::pageRect (Unit unit) const
Returns the page's rectangle in unit; this is usually smaller than the paperRect() since the page normally has margins between its borders and the paper.
Since
4.4
See also
paperSize()
Definition at line 1745 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     int res = resolution();
     const qreal multiplier = qt_multiplierForUnit(unit, res);
     // the page rect is in device pixels
     QRect devRect(d->printEngine->property(QPrintEngine::PPK_PageRect).toRect());
     if (unit == DevicePixel)
         return devRect;
     QRectF diRect(devRect.x()*72.0/res,
                   devRect.y()*72.0/res,
                   devRect.width()*72.0/res,
                   devRect.height()*72.0/res);
     return QRectF(diRect.x()/multiplier, diRect.y()/multiplier,
                   diRect.width()/multiplier, diRect.height()/multiplier);
 }
pageSize()
QPrinter::PageSize QPrinter::pageSize () const
Returns the printer page size.
The default value is driver-dependent.
Use paperSize() instead.
Definition at line 1187 of file qprinter.cpp.
Referenced by QPageSetupWidget::_q_paperSizeChanged(), QPrintDialogPrivate::setPrinter(), and QPageSetupWidget::setupPrinter().
 {
     return paperSize();
 }
paintEngine()
QPaintEngine * QPrinter::paintEngine () const virtual
Returns the paint engine used by the printer.
Implements QPaintDevice.
Definition at line 1882 of file qprinter.cpp.
Referenced by QPrintDialog::QPrintDialog(), and setEngines().
 {
     Q_D(const QPrinter);
     return d->paintEngine;
 }
paperRect() [1/2]
QRect QPrinter::paperRect () const
Returns the paper's rectangle; this is usually larger than the pageRect().
The unit of the returned rectangle is DevicePixel.
See also
pageRect()
Definition at line 1814 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_PaperRect).toRect();
 }
paperRect() [2/2]
QRectF QPrinter::paperRect (Unit unit) const
Returns the paper's rectangle in unit; this is usually larger than the pageRect().
Since
4.4
See also
pageRect()
Definition at line 1774 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     int res = resolution();
     const qreal multiplier = qt_multiplierForUnit(unit, resolution());
     // the page rect is in device pixels
     QRect devRect(d->printEngine->property(QPrintEngine::PPK_PaperRect).toRect());
     if (unit == DevicePixel)
         return devRect;
     QRectF diRect(devRect.x()*72.0/res,
                   devRect.y()*72.0/res,
                   devRect.width()*72.0/res,
                   devRect.height()*72.0/res);
     return QRectF(diRect.x()/multiplier, diRect.y()/multiplier,
                   diRect.width()/multiplier, diRect.height()/multiplier);
 }
paperSize() [1/2]
QPrinter::PaperSize QPrinter::paperSize () const
Returns the printer paper size.
Since
4.4 The default value is driver-dependent.
See also
setPaperSize() pageRect() paperRect()
Definition at line 1140 of file qprinter.cpp.
Referenced by pageSize(), paperSize(), QPageSetupWidget::selectPdfPsPrinter(), QPageSetupWidget::selectPrinter(), and QPageSetupWidget::setPrinter().
 {
     Q_D(const QPrinter);
     return QPrinter::PaperSize(d->printEngine->property(QPrintEngine::PPK_PaperSize).toInt());
 }
paperSize() [2/2]
QSizeF QPrinter::paperSize (Unit unit) const
Returns the paper size in unit.
Since
4.4
See also
setPaperSize()
Definition at line 1243 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     int res = resolution();
     const qreal multiplier = qt_multiplierForUnit(unit, res);
     PaperSize paperType = paperSize();
     if (paperType == Custom) {
         QSizeF size = d->printEngine->property(QPrintEngine::PPK_CustomPaperSize).toSizeF();
         return QSizeF(size.width() / multiplier, size.height() / multiplier);
     }
     else {
         return qt_printerPaperSize(orientation(), paperType, unit, res);
     }
 }
paperSource()
QPrinter::PaperSource QPrinter::paperSource () const
Returns the printer's paper source.
This is Manual or a printer tray or paper cassette.
Definition at line 1604 of file qprinter.cpp.
Referenced by QPageSetupWidget::setPrinter().
 {
     Q_D(const QPrinter);
     return QPrinter::PaperSource(d->printEngine->property(QPrintEngine::PPK_PaperSource).toInt());
 }
printEngine()
QPrintEngine * QPrinter::printEngine () const
Returns the print engine used by the printer.
Since
4.1
Definition at line 1896 of file qprinter.cpp.
Referenced by QUnixPrintWidgetPrivate::setCupsProperties(), setEngines(), and QPageSetupWidget::setupPrinter().
 {
     Q_D(const QPrinter);
     return d->printEngine;
 }
printerName()
QString QPrinter::printerName () const
Returns the printer name.
This value is initially set to the name of the default printer.
See also
setPrinterName()
Definition at line 834 of file qprinter.cpp.
Referenced by QUnixPrintWidgetPrivate::applyPrinterProperties(), QPrinterInfo::QPrinterInfo(), setPrinterName(), and QUnixPrintWidgetPrivate::updateWidget().
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_PrinterName).toString();
 }
printerSelectionOption()
QString QPrinter::printerSelectionOption () const
Returns the printer options selection string.
This is useful only if the print command has been explicitly set.
The default value (an empty string) implies that the printer should be selected in a system-dependent manner.
Any other value implies that the given value should be used.
Warning
This function is not available on Windows.
See also
setPrinterSelectionOption()
Referenced by supportedPaperSources().
printerState()
QPrinter::PrinterState QPrinter::printerState () const
Returns the current state of the printer.
This may not always be accurate (for example if the printer doesn't have the capability of reporting its state to the operating system).
Definition at line 1990 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->printerState();
 }
printProgram()
QString QPrinter::printProgram () const
Returns the name of the program that sends the print output to the printer.
The default is to return an empty string; meaning that QPrinter will try to be smart in a system-dependent way. On X11 only, you can set it to something different to use a specific print program. On the other platforms, this returns an empty string.
See also
setPrintProgram(), setPrinterSelectionOption()
Definition at line 1005 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_PrinterProgram).toString();
 }
printRange()
QPrinter::PrintRange QPrinter::printRange () const
Returns the page range of the QPrinter.
Since
4.1
After the print setup dialog has been opened, this function returns the value selected by the user.
See also
setPrintRange()
Definition at line 2265 of file qprinter.cpp.
Referenced by QTextControl::print().
 {
     Q_D(const QPrinter);
     return PrintRange(d->printRange);
 }
releaseDC()
void QPrinter::releaseDC (HDC hdc) const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPaintDevice.
Definition at line 2063 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     d->printEngine->releasePrinterDC(hdc);
 }
resolution()
int QPrinter::resolution () const
Returns the current assumed resolution of the printer, as set by setResolution() or by the printer driver.
See also
setResolution()
Definition at line 1578 of file qprinter.cpp.
Referenced by getPageMargins(), pageRect(), paperRect(), paperSize(), setPageMargins(), and setPaperSize().
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_Resolution).toInt();
 }
setCollateCopies()
void QPrinter::setCollateCopies (bool collate)
Sets the default value for collation checkbox when the print dialog appears.
Since
4.1
If collate is true, it will enable setCollateCopiesEnabled(). The default value is false. This value will be changed by what the user presses in the print dialog.
See also
collateCopies()
Definition at line 1493 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setCollateCopies");
     d->printEngine->setProperty(QPrintEngine::PPK_CollateCopies, collate);
     d->addToManualSetList(QPrintEngine::PPK_CollateCopies);
 }
setColorMode()
void QPrinter::setColorMode (ColorMode newColorMode)
Sets the printer's color mode to newColorMode, which can be either Color or GrayScale.
See also
colorMode()
Definition at line 1300 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked(), and QPrintDialogPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setColorMode");
     d->printEngine->setProperty(QPrintEngine::PPK_ColorMode, newColorMode);
     d->addToManualSetList(QPrintEngine::PPK_ColorMode);
 }
setCopyCount()
void QPrinter::setCopyCount (int count)
Sets the number of copies to be printed to count.
Since
4.7
The printer driver reads this setting and prints the specified number of copies.
See also
copyCount(), supportsMultipleCopies()
Definition at line 1411 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked(), and QPrintDialogPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setCopyCount;");
     d->printEngine->setProperty(QPrintEngine::PPK_CopyCount, count);
     d->addToManualSetList(QPrintEngine::PPK_CopyCount);
 }
setCreator()
void QPrinter::setCreator (const QString & creator)
Sets the name of the application that created the document to creator.
This function is only applicable to the X11 version of Qt. If no creator name is specified, the creator will be set to "Qt" followed by some version number.
See also
creator()
Definition at line 1083 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setCreator");
     d->printEngine->setProperty(QPrintEngine::PPK_Creator, creator);
     d->addToManualSetList(QPrintEngine::PPK_Creator);
 }
setDocName()
void QPrinter::setDocName (const QString & name)
Sets the document name to name.
On X11, the document name is for example used as the default output filename in QPrintDialog. Note that the document name does not affect the file name if the printer is printing to a file. Use the setOutputFile() function for this.
See also
docName(), QPrintEngine::PrintEnginePropertyKey
Definition at line 1052 of file qprinter.cpp.
Referenced by QTextDocument::print().
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setDocName");
     d->printEngine->setProperty(QPrintEngine::PPK_DocumentName, name);
     d->addToManualSetList(QPrintEngine::PPK_DocumentName);
 }
setDoubleSidedPrinting()
void QPrinter::setDoubleSidedPrinting (bool doubleSided)
Enables double sided printing if doubleSided is true; otherwise disables it.
Since
4.2
Currently this option is only supported on X11.
Definition at line 1679 of file qprinter.cpp.
 {
     setDuplex(doubleSided ? DuplexAuto : DuplexNone);
 }
setDuplex()
void QPrinter::setDuplex (DuplexMode duplex)
Enables double sided printing based on the duplex mode.
Since
4.4
Currently this option is only supported on X11.
Definition at line 1710 of file qprinter.cpp.
Referenced by setDoubleSidedPrinting(), and QPrintDialogPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     d->printEngine->setProperty(QPrintEngine::PPK_Duplex, duplex);
     d->addToManualSetList(QPrintEngine::PPK_Duplex);
 }
setEngines()
void QPrinter::setEngines (QPrintEngine * printEngine, QPaintEngine * paintEngine) protected
This function is used by subclasses of QPrinter to specify custom print and paint engines (printEngine and paintEngine, respectively).
QPrinter does not take ownership of the engines, so you need to manage these engine instances yourself.
Note that changing the engines will reset the printer state and all its properties.
See also
printEngine() paintEngine() setOutputFormat()
Since
4.1
Definition at line 708 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     if (d->use_default_engine)
         delete d->printEngine;
     d->printEngine = printEngine;
     d->paintEngine = paintEngine;
     d->use_default_engine = false;
 }
setFontEmbeddingEnabled()
void QPrinter::setFontEmbeddingEnabled (bool enable)
Enabled or disables font embedding depending on enable.
Since
4.1
Currently this option is only supported on X11.
See also
fontEmbeddingEnabled()
Definition at line 1623 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     d->printEngine->setProperty(QPrintEngine::PPK_FontEmbedding, enable);
     d->addToManualSetList(QPrintEngine::PPK_FontEmbedding);
 }
setFromTo()
void QPrinter::setFromTo (int from, int to)
Sets the range of pages to be printed to cover the pages with numbers specified by from and to, where from corresponds to the first page in the range and to corresponds to the last.
Since
4.1
Note
Pages in a document are numbered according to the convention that the first page is page 1. However, if from and to are both set to 0, the whole document will be printed.
This function is mostly used to set a default value that the user can override in the print dialog when you call setup().
See also
fromPage(), toPage()
Definition at line 2222 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     if (from > to) {
         qWarning() << "QPrinter::setFromTo: 'from' must be less than or equal to 'to'";
         from = to;
     }
     d->fromPage = from;
     d->toPage = to;
     if (d->minPage == 0 && d->maxPage == 0) {
         d->minPage = 1;
         d->maxPage = to;
         d->options |= QAbstractPrintDialog::PrintPageRange;
     }
 }
setFullPage()
void QPrinter::setFullPage (bool fp)
If fp is true, enables support for painting over the entire page; otherwise restricts painting to the printable area reported by the device.
By default, full page printing is disabled. In this case, the origin of the QPrinter's coordinate system coincides with the top-left corner of the printable area.
If full page printing is enabled, the origin of the QPrinter's coordinate system coincides with the top-left corner of the paper itself. In this case, the device metrics will report the exact same dimensions as indicated by PaperSize. It may not be possible to print on the entire physical page because of the printer's margins, so the application must account for the margins itself.
See also
fullPage(), setPaperSize(), width(), height(), {Printing with Qt}
Definition at line 1524 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     d->printEngine->setProperty(QPrintEngine::PPK_FullPage, fp);
     d->addToManualSetList(QPrintEngine::PPK_FullPage);
 }
setNumCopies()
void QPrinter::setNumCopies (int numCopies)
Sets the number of copies to be printed to numCopies.
The printer driver reads this setting and prints the specified number of copies.
Use setCopyCount() instead.
See also
numCopies()
Definition at line 1389 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setNumCopies");
     d->printEngine->setProperty(QPrintEngine::PPK_NumberOfCopies, numCopies);
     d->addToManualSetList(QPrintEngine::PPK_NumberOfCopies);
 }
setOrientation()
void QPrinter::setOrientation (Orientation orientation)
Sets the print orientation to orientation.
The orientation can be either QPrinter::Portrait or QPrinter::Landscape.
The printer driver reads this setting and prints using the specified orientation.
On Windows, this option can be changed while printing and will take effect from the next call to newPage().
On Mac OS X, changing the orientation during a print job has no effect.
See also
orientation()
Definition at line 1122 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked(), and QPageSetupWidget::setupPrinter().
 {
     Q_D(QPrinter);
     d->printEngine->setProperty(QPrintEngine::PPK_Orientation, orientation);
     d->addToManualSetList(QPrintEngine::PPK_Orientation);
 }
setOutputFileName()
void QPrinter::setOutputFileName (const QString & fileName)
Sets the name of the output file to fileName.
Setting a null or empty name (0 or "") disables printing to a file. Setting a non-empty name enables printing to a file.
This can change the value of outputFormat(). If the file name has the suffix ".ps" then PostScript is automatically selected as output format. If the file name has the ".pdf" suffix PDF is generated. If the file name has a suffix other than ".ps" and ".pdf", the output format used is the one set with setOutputFormat().
QPrinter uses Qt's cross-platform PostScript or PDF print engines respectively. If you can produce this format natively, for example Mac OS X can generate PDF's from its print engine, set the output format back to NativeFormat.
See also
outputFileName() setOutputToFile() setOutputFormat()
Definition at line 976 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked(), printRange(), and QUnixPrintWidgetPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setOutputFileName");
     QFileInfo fi(fileName);
     if (!fi.suffix().compare(QLatin1String("ps"), Qt::CaseInsensitive))
         setOutputFormat(QPrinter::PostScriptFormat);
     else if (!fi.suffix().compare(QLatin1String("pdf"), Qt::CaseInsensitive))
         setOutputFormat(QPrinter::PdfFormat);
     else if (fileName.isEmpty())
         setOutputFormat(QPrinter::NativeFormat);
     d->printEngine->setProperty(QPrintEngine::PPK_OutputFileName, fileName);
     d->addToManualSetList(QPrintEngine::PPK_OutputFileName);
 }
setOutputFormat()
void QPrinter::setOutputFormat (OutputFormat format)
Sets the output format for this printer to format.
Since
4.1
Definition at line 765 of file qprinter.cpp.
Referenced by init(), QPrinter(), setOutputFileName(), setPrinterName(), and QUnixPrintWidgetPrivate::setupPrinter().
 {
 #ifndef QT_NO_PDF
     Q_D(QPrinter);
     if (d->validPrinter && d->outputFormat == format)
         return;
     d->outputFormat = format;
     QPrintEngine *oldPrintEngine = d->printEngine;
     const bool def_engine = d->use_default_engine;
     d->printEngine = 0;
     d->createDefaultEngines();
     if (oldPrintEngine) {
         for (int i = 0; i < d->manualSetList.size(); ++i) {
             QPrintEngine::PrintEnginePropertyKey key = d->manualSetList[i];
             QVariant prop;
             // PPK_NumberOfCopies need special treatmeant since it in most cases
             // will return 1, disregarding the actual value that was set
             if (key == QPrintEngine::PPK_NumberOfCopies)
                 prop = QVariant(copyCount());
             else
                 prop = oldPrintEngine->property(key);
             if (prop.isValid())
                 d->printEngine->setProperty(key, prop);
         }
     }
     if (def_engine)
         delete oldPrintEngine;
     if (d->outputFormat == QPrinter::PdfFormat || d->outputFormat == QPrinter::PostScriptFormat)
         d->validPrinter = true;
 #else
     Q_UNUSED(format);
 #endif
 }
setPageMargins()
void QPrinter::setPageMargins (qreal left, qreal top, qreal right, qreal bottom, QPrinter::Unit unit)
This function sets the left, top, right and bottom page margins for this printer.
Since
4.4
The unit of the margins are specified with the unit parameter.
Definition at line 1831 of file qprinter.cpp.
Referenced by QTextDocument::print(), and QPageSetupWidget::setupPrinter().
 {
     Q_D(QPrinter);
     const qreal multiplier = qt_multiplierForUnit(unit, resolution());
     QList<QVariant> margins;
     margins << (left * multiplier) << (top * multiplier)
             << (right * multiplier) << (bottom * multiplier);
     d->printEngine->setProperty(QPrintEngine::PPK_PageMargins, margins);
     d->addToManualSetList(QPrintEngine::PPK_PageMargins);
     d->hasCustomPageMargins = true;
 }
setPageOrder()
void QPrinter::setPageOrder (PageOrder pageOrder)
Sets the page order to pageOrder.
The page order can be QPrinter::FirstPageFirst or QPrinter::LastPageFirst. The application is responsible for reading the page order and printing accordingly.
This function is mostly useful for setting a default value that the user can override in the print dialog.
This function is only supported under X11.
Definition at line 1271 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked().
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setPageOrder");
     d->printEngine->setProperty(QPrintEngine::PPK_PageOrder, pageOrder);
     d->addToManualSetList(QPrintEngine::PPK_PageOrder);
 }
setPageSize()
void QPrinter::setPageSize (PageSize newPageSize)
Sets the printer page size based on newPageSize.
Use setPaperSize() instead.
Definition at line 1204 of file qprinter.cpp.
 {
     setPaperSize(newPageSize);
 }
setPaperSize() [1/2]
void QPrinter::setPaperSize (PaperSize newPaperSize)
Sets the printer paper size to newPaperSize if that size is supported.
Since
4.4
The result is undefined if newPaperSize is not supported.
The default paper size is driver-dependent.
This function is useful mostly for setting a default value that the user can override in the print dialog.
See also
paperSize() PaperSize setFullPage() setResolution() pageRect() paperRect()
Definition at line 1163 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked(), QUnixPrintWidgetPrivate::setCupsProperties(), setPageSize(), and QPageSetupWidget::setupPrinter().
 {
     Q_D(QPrinter);
     if (d->paintEngine->type() != QPaintEngine::Pdf)
         ABORT_IF_ACTIVE("QPrinter::setPaperSize");
     if (newPaperSize < 0 || newPaperSize >= NPaperSize) {
         qWarning("QPrinter::setPaperSize: Illegal paper size %d", newPaperSize);
         return;
     }
     d->printEngine->setProperty(QPrintEngine::PPK_PaperSize, newPaperSize);
     d->addToManualSetList(QPrintEngine::PPK_PaperSize);
     d->hasUserSetPageSize = true;
 }
setPaperSize() [2/2]
void QPrinter::setPaperSize (const QSizeF & paperSize, QPrinter::Unit unit)
Sets the paper size based on paperSize in unit.
Since
4.4
See also
paperSize()
Definition at line 1220 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     if (d->paintEngine->type() != QPaintEngine::Pdf)
         ABORT_IF_ACTIVE("QPrinter::setPaperSize");
     const qreal multiplier = qt_multiplierForUnit(unit, resolution());
     QSizeF size(paperSize.width() * multiplier, paperSize.height() * multiplier);
     d->printEngine->setProperty(QPrintEngine::PPK_CustomPaperSize, size);
     d->addToManualSetList(QPrintEngine::PPK_CustomPaperSize);
     d->hasUserSetPageSize = true;
 }
setPaperSource()
void QPrinter::setPaperSource (PaperSource source)
Sets the paper source setting to source.
Windows only: This option can be changed while printing and will take effect from the next call to newPage()
See also
paperSource()
Definition at line 1593 of file qprinter.cpp.
Referenced by QPageSetupWidget::setupPrinter().
 {
     Q_D(QPrinter);
     d->printEngine->setProperty(QPrintEngine::PPK_PaperSource, source);
     d->addToManualSetList(QPrintEngine::PPK_PaperSource);
 }
setPrinterName()
void QPrinter::setPrinterName (const QString & name)
Sets the printer name to name.
See also
printerName(), isValid()
Definition at line 845 of file qprinter.cpp.
Referenced by QPrinter(), and QUnixPrintWidgetPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setPrinterName");
 #if defined(Q_OS_UNIX) && !defined(QT_NO_CUPS)
     if(d->use_default_engine
         && d->outputFormat == QPrinter::NativeFormat) {
         if (QCUPSSupport::cupsVersion() >= 10200
             && QCUPSSupport::printerHasPPD(name.toLocal8Bit().constData()))
             setOutputFormat(QPrinter::PdfFormat);
         else
             setOutputFormat(QPrinter::PostScriptFormat);
         d->outputFormat = QPrinter::NativeFormat;
     }
 #endif
     QList<QPrinterInfo> prnList = QPrinterInfo::availablePrinters();
     if (name.isEmpty()) {
         d->validPrinter = d->outputFormat == QPrinter::PdfFormat || d->outputFormat == QPrinter::PostScriptFormat;
     } else {
         d->validPrinter = false;
         for (int i = 0; i < prnList.size(); ++i) {
             if (prnList[i].printerName() == name) {
                 d->validPrinter = true;
                 break;
             }
         }
     }
     d->printEngine->setProperty(QPrintEngine::PPK_PrinterName, name);
     d->addToManualSetList(QPrintEngine::PPK_PrinterName);
 }
setPrinterSelectionOption()
void QPrinter::setPrinterSelectionOption (const QString & option)
Sets the printer to use option to select the printer.
option is null by default (which implies that Qt should be smart enough to guess correctly), but it can be set to other values to use a specific printer selection option.
If the printer selection option is changed while the printer is active, the current print job may or may not be affected.
Warning
This function is not available on Windows.
See also
printerSelectionOption()
Referenced by supportedPaperSources().
setPrintProgram()
void QPrinter::setPrintProgram (const QString & printProg)
Sets the name of the program that should do the print job to printProg.
On X11, this function sets the program to call with the PostScript output. On other platforms, it has no effect.
See also
printProgram()
Definition at line 1021 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setPrintProgram");
     d->printEngine->setProperty(QPrintEngine::PPK_PrinterProgram, printProg);
     d->addToManualSetList(QPrintEngine::PPK_PrinterProgram);
 }
setPrintRange()
void QPrinter::setPrintRange (PrintRange range)
Sets the print range option in to be range.
Since
4.1
Definition at line 2247 of file qprinter.cpp.
Referenced by QPrintDialogPrivate::setupPrinter().
 {
     Q_D(QPrinter);
     d->printRange = QAbstractPrintDialog::PrintRange(range);
 }
setResolution()
void QPrinter::setResolution (int dpi)
Requests that the printer prints at dpi or as near to dpi as possible.
This setting affects the coordinate system as returned by, for example QPainter::viewport().
This function must be called before QPainter::begin() to have an effect on all platforms.
See also
resolution() setPaperSize()
Definition at line 1562 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setResolution");
     d->printEngine->setProperty(QPrintEngine::PPK_Resolution, dpi);
     d->addToManualSetList(QPrintEngine::PPK_Resolution);
 }
setWinPageSize()
void QPrinter::setWinPageSize (int pageSize)
Sets the page size to be used by the printer under Windows to pageSize.
Warning
This function is not portable so you may prefer to use setPaperSize() instead.
See also
winPageSize()
Definition at line 1912 of file qprinter.cpp.
 {
     Q_D(QPrinter);
     ABORT_IF_ACTIVE("QPrinter::setWinPageSize");
     d->printEngine->setProperty(QPrintEngine::PPK_WindowsPageSize, pageSize);
     d->addToManualSetList(QPrintEngine::PPK_WindowsPageSize);
 }
supportedPaperSources()
QList< QPrinter::PaperSource > QPrinter::supportedPaperSources () const
Returns the supported paper sizes for this printer.
The values will be either a value that matches an entry in the QPrinter::PaperSource enum or a driver spesific value. The driver spesific values are greater than the constant DMBIN_USER declared in wingdi.h.
Warning
This function is only available in windows.
Definition at line 2080 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     QVariant v = d->printEngine->property(QPrintEngine::PPK_PaperSources);
     QList<QVariant> variant_list = v.toList();
     QList<QPrinter::PaperSource> int_list;
     for (int i=0; i<variant_list.size(); ++i)
         int_list << (QPrinter::PaperSource) variant_list.at(i).toInt();
     return int_list;
 }
supportedResolutions()
QList< int > QPrinter::supportedResolutions () const
Returns a list of the resolutions (a list of dots-per-inch integers) that the printer says it supports.
For X11 where all printing is directly to postscript, this function will always return a one item list containing only the postscript resolution, i.e., 72 (72 dpi – but see PrinterMode).
Definition at line 1943 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     QList<QVariant> varlist
         = d->printEngine->property(QPrintEngine::PPK_SupportedResolutions).toList();
     QList<int> intlist;
     for (int i=0; i<varlist.size(); ++i)
         intlist << varlist.at(i).toInt();
     return intlist;
 }
supportsMultipleCopies()
bool QPrinter::supportsMultipleCopies () const
Returns true if the printer supports printing multiple copies of the same document in one job; otherwise false is returned.
Since
4.7
On most systems this function will return true. However, on X11 systems that do not support CUPS, this function will return false. That means the application has to handle the number of copies by printing the same document the required number of times.
See also
setCopyCount(), copyCount()
Definition at line 1453 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_SupportsMultipleCopies).toBool();
 }
toPage()
int QPrinter::toPage () const
Returns the number of the last page in a range of pages to be printed (the "to page" setting).
Since
4.1
Pages in a document are numbered according to the convention that the first page is page 1.
By default, this function returns a special value of 0, meaning that the "to page" setting is unset.
Note
If fromPage() and toPage() both return 0, this indicates that the whole document will be printed.
The programmer is responsible for reading this setting and printing accordingly.
See also
setFromTo(), fromPage()
Definition at line 2196 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->toPage;
 }
winPageSize()
int QPrinter::winPageSize () const
Returns the page size used by the printer under Windows.
Warning
This function is not portable so you may prefer to use paperSize() instead.
See also
setWinPageSize()
Definition at line 1928 of file qprinter.cpp.
 {
     Q_D(const QPrinter);
     return d->printEngine->property(QPrintEngine::PPK_WindowsPageSize).toInt();
 }
Friends and Related Functions
QAbstractPrintDialog
friend class QAbstractPrintDialog friend
Definition at line 301 of file qprinter.h.
QAbstractPrintDialogPrivate
friend class QAbstractPrintDialogPrivate friend
Definition at line 302 of file qprinter.h.
QPageSetupWidget
friend class QPageSetupWidget friend
Definition at line 305 of file qprinter.h.
QPrintDialogPrivate
friend class QPrintDialogPrivate friend
Definition at line 300 of file qprinter.h.
QPrintPreviewWidgetPrivate
friend class QPrintPreviewWidgetPrivate friend
Definition at line 303 of file qprinter.h.
QTextDocument
friend class QTextDocument friend
Definition at line 304 of file qprinter.h.
Properties
d_ptr
QScopedPointer<QPrinterPrivate> QPrinter::d_ptr private
Definition at line 298 of file qprinter.h.
Referenced by QPrinter().
The documentation for this class was generated from the following files:
/src/gui/painting/qprinter.h
/src/gui/painting/qprinter.cpp