Qt 4.8: QGraphicsWidget Class Reference
QGraphicsWidget Class Reference
The QGraphicsWidget class is the base class for all widget items in a QGraphicsScene.
#include <qgraphicswidget.h>
Public Types
enum { Type = 11 }
Public Types inherited from QGraphicsItem
enum { Type = 1, UserType = 65536 }
enum CacheMode { NoCache, ItemCoordinateCache, DeviceCoordinateCache }
This enum describes QGraphicsItem's cache modes.
enum GraphicsItemChange {
ItemPositionChange, ItemMatrixChange, ItemVisibleChange, ItemEnabledChange,
ItemSelectedChange, ItemParentChange, ItemChildAddedChange, ItemChildRemovedChange,
ItemTransformChange, ItemPositionHasChanged, ItemTransformHasChanged, ItemSceneChange,
ItemVisibleHasChanged, ItemEnabledHasChanged, ItemSelectedHasChanged, ItemParentHasChanged,
ItemSceneHasChanged, ItemCursorChange, ItemCursorHasChanged, ItemToolTipChange,
ItemToolTipHasChanged, ItemFlagsChange, ItemFlagsHaveChanged, ItemZValueChange,
ItemZValueHasChanged, ItemOpacityChange, ItemOpacityHasChanged, ItemScenePositionHasChanged,
ItemRotationChange, ItemRotationHasChanged, ItemScaleChange, ItemScaleHasChanged,
ItemTransformOriginPointChange, ItemTransformOriginPointHasChanged
}
This enum describes the state changes that are notified by QGraphicsItem::itemChange().
enum GraphicsItemFlag {
ItemIsMovable = 0x1, ItemIsSelectable = 0x2, ItemIsFocusable = 0x4, ItemClipsToShape = 0x8,
ItemClipsChildrenToShape = 0x10, ItemIgnoresTransformations = 0x20, ItemIgnoresParentOpacity = 0x40, ItemDoesntPropagateOpacityToChildren = 0x80,
ItemStacksBehindParent = 0x100, ItemUsesExtendedStyleOption = 0x200, ItemHasNoContents = 0x400, ItemSendsGeometryChanges = 0x800,
ItemAcceptsInputMethod = 0x1000, ItemNegativeZStacksBehindParent = 0x2000, ItemIsPanel = 0x4000, ItemIsFocusScope = 0x8000,
ItemSendsScenePositionChanges = 0x10000, ItemStopsClickFocusPropagation = 0x20000, ItemStopsFocusHandling = 0x40000
}
This enum describes different flags that you can set on an item to toggle different features in the item's behavior.
enum PanelModality { NonModal, PanelModal, SceneModal }
This enum specifies the behavior of a modal panel.
Public Slots
bool close ()
Call this function to close the widget.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void geometryChanged ()
This signal gets emitted whenever the geometry is changed in setGeometry().
void layoutChanged ()
This signal gets emitted whenever the layout of the item changes.
Signals inherited from QGraphicsObject
void childrenChanged ()
This signal gets emitted whenever the children list changes.
void enabledChanged ()
This signal gets emitted whenever the item get's enabled or disabled.
void heightChanged ()
void opacityChanged ()
This signal gets emitted whenever the opacity of the item changes.
void parentChanged ()
This signal gets emitted whenever the parent of the item changes.
void rotationChanged ()
This signal gets emitted whenever the roation of the item changes.
void scaleChanged ()
This signal is emitted when the scale of the item changes.
void visibleChanged ()
This signal gets emitted whenever the visibility of the item changes.
void widthChanged ()
void xChanged ()
This signal gets emitted whenever the x position of the item changes.
void yChanged ()
This signal gets emitted whenever the y position of the item changes.
void zChanged ()
This signal gets emitted whenever the z value of the item changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to its effective preferred size hint.
bool autoFillBackground () const
QRectF boundingRect () const
Reimplemented Function
Qt::FocusPolicy focusPolicy () const
QGraphicsWidget * focusWidget () const
If this widget, a child or descendant of this widget currently has input focus, this function will return a pointer to that widget.
QFont font () const
void getContentsMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
Gets the widget's contents margins.
void getWindowFrameMargins (qreal *left, qreal *top, qreal *right, qreal *bottom) const
Gets the widget's window frame margins.
int grabShortcut (const QKeySequence &sequence, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
bool isActiveWindow () const
Returns true if this widget's window is in the active window, or if the widget does not have a window but is in an active scene (i.e., a scene that currently has focus).
QGraphicsLayout * layout () const
Qt::LayoutDirection layoutDirection () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
Reimplemented Function
virtual void paintWindowFrame (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget=0)
This virtual function is called by QGraphicsScene to draw the window frame for windows using painter, option, and widget, in local coordinates.
QPalette palette () const
QGraphicsWidget (QGraphicsItem *parent=0, Qt::WindowFlags wFlags=0)
Constructs a QGraphicsWidget instance.
QRectF rect () const
Returns the item's local rect as a QRectF.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void resize (const QSizeF &size)
void resize (qreal w, qreal h)
This convenience function is equivalent to calling resize(QSizeF(w, h)).
void setAttribute (Qt::WidgetAttribute attribute, bool on=true)
If on is true, this function enables attribute; otherwise attribute is disabled.
void setAutoFillBackground (bool enabled)
void setContentsMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the widget's contents margins to left, top, right and bottom.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFont (const QFont &font)
void setGeometry (const QRectF &rect)
This virtual function sets the geometry of the QGraphicsLayoutItem to rect, which is in parent coordinates (e.
void setGeometry (qreal x, qreal y, qreal w, qreal h)
This convenience function is equivalent to calling setGeometry(QRectF(x, y, w, h)).
void setLayout (QGraphicsLayout *layout)
Sets the layout for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setPalette (const QPalette &palette)
void setShortcutAutoRepeat (int id, bool enabled=true)
If enabled is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enabled=true)
If enabled is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setStyle (QStyle *style)
Sets the widget's style to style.
void setWindowFlags (Qt::WindowFlags wFlags)
void setWindowFrameMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the widget's window frame margins to left, top, right and bottom.
void setWindowTitle (const QString &title)
QPainterPath shape () const
Reimplemented Function
QSizeF size () const
QStyle * style () const
Returns a pointer to the widget's style.
bool testAttribute (Qt::WidgetAttribute attribute) const
Returns true if attribute is enabled for this widget; otherwise, returns false.
int type () const
Reimplemented Function
void unsetLayoutDirection ()
void unsetWindowFrameMargins ()
Resets the window frame margins to the default value, provided by the style.
Qt::WindowFlags windowFlags () const
QRectF windowFrameGeometry () const
Returns the widget's geometry in parent coordinates including any window frame.
QRectF windowFrameRect () const
Returns the widget's local rect including any window frame.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the widgets window type.
~QGraphicsWidget ()
Destroys the QGraphicsWidget instance.
Public Functions inherited from QGraphicsObject
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the graphics object to the given gesture with specific flags.
QGraphicsObject (QGraphicsItem *parent=0)
Constructs a QGraphicsObject with parent.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the graphics object from the given gesture.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QGraphicsItem
bool acceptDrops () const
Returns true if this item can accept drag and drop events; otherwise, returns false.
Qt::MouseButtons acceptedMouseButtons () const
Returns the mouse buttons that this item accepts mouse events for.
bool acceptHoverEvents () const
Returns true if an item accepts hover events (QGraphicsSceneHoverEvent); otherwise, returns false.
bool acceptsHoverEvents () const
Call acceptHoverEvents() instead.
bool acceptTouchEvents () const
Returns true if an item accepts touch events; otherwise, returns false.
virtual void advance (int phase)
This virtual function is called twice for all items by the QGraphicsScene::advance() slot.
QRegion boundingRegion (const QTransform &itemToDeviceTransform) const
Returns the bounding region for this item.
qreal boundingRegionGranularity () const
Returns the item's bounding region granularity; a value between and including 0 and 1.
CacheMode cacheMode () const
Returns the cache mode for this item.
QList< QGraphicsItem * > childItems () const
Returns a list of this item's children.
QList< QGraphicsItem * > children () const
Use childItems() instead.
QRectF childrenBoundingRect () const
Returns the bounding rect of this item's descendants (i.e., its children, their children, etc.) in local coordinates.
void clearFocus ()
Takes keyboard input focus from the item.
QPainterPath clipPath () const
Returns this item's clip path, or an empty QPainterPath if this item is not clipped.
virtual bool collidesWithItem (const QGraphicsItem *other, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with other; otherwise returns false.
virtual bool collidesWithPath (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns true if this item collides with path.
QList< QGraphicsItem * > collidingItems (Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all items that collide with this item.
QGraphicsItem * commonAncestorItem (const QGraphicsItem *other) const
Returns the closest common ancestor item of this item and other, or 0 if either other is 0, or there is no common ancestor.
virtual bool contains (const QPointF &point) const
Returns true if this item contains point, which is in local coordinates; otherwise, false is returned.
QCursor cursor () const
Returns the current cursor shape for the item.
QVariant data (int key) const
Returns this item's custom data for the key key as a QVariant.
QTransform deviceTransform (const QTransform &viewportTransform) const
Returns this item's device transformation matrix, using viewportTransform to map from scene to device coordinates.
qreal effectiveOpacity () const
Returns this item's effective opacity, which is between 0.
void ensureVisible (const QRectF &rect=QRectF(), int xmargin=50, int ymargin=50)
If this item is part of a scene that is viewed by a QGraphicsView, this convenience function will attempt to scroll the view to ensure that rect is visible inside the view's viewport.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This convenience function is equivalent to calling ensureVisible(QRectF(x, y, w, h), xmargin, ymargin):
bool filtersChildEvents () const
Returns true if this item filters child events (i.
GraphicsItemFlags flags () const
Returns this item's flags.
QGraphicsItem * focusItem () const
If this item, a child or descendant of this item currently has input focus, this function will return a pointer to that item.
QGraphicsItem * focusProxy () const
Returns this item's focus proxy, or 0 if this item has no focus proxy.
QGraphicsItem * focusScopeItem () const
Returns this item's focus scope item.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
QGraphicsEffect * graphicsEffect () const
Returns a pointer to this item's effect if it has one; otherwise 0.
QGraphicsItemGroup * group () const
Returns a pointer to this item's item group, or 0 if this item is not member of a group.
bool handlesChildEvents () const
Returns true if this item handles child events (i.
bool hasCursor () const
Returns true if this item has a cursor set; otherwise, false is returned.
bool hasFocus () const
Returns true if this item is active, and it or its focus proxy has keyboard input focus; otherwise, returns false.
void hide ()
Hides the item.
Qt::InputMethodHints inputMethodHints () const
Returns the current input method hints of this item.
void installSceneEventFilter (QGraphicsItem *filterItem)
Installs an event filter for this item on filterItem, causing all events for this item to first pass through filterItem's sceneEventFilter() function.
bool isActive () const
Returns true if this item is active; otherwise returns false.
bool isAncestorOf (const QGraphicsItem *child) const
Returns true if this item is an ancestor of child (i.e., if this item is child's parent, or one of child's parent's ancestors).
bool isBlockedByModalPanel (QGraphicsItem **blockingPanel=0) const
Returns true if this item is blocked by a modal panel, false otherwise.
bool isClipped () const
Returns true if this item is clipped.
bool isEnabled () const
Returns true if the item is enabled; otherwise, false is returned.
bool isObscured () const
Returns true if this item's bounding rect is completely obscured by the opaque shape of any of colliding items above it (i.e., with a higher Z value than this item).
bool isObscured (const QRectF &rect) const
Returns true if rect is completely obscured by the opaque shape of any of colliding items above it (i.
bool isObscured (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling isObscured(QRectF(x, y, w, h)).
virtual bool isObscuredBy (const QGraphicsItem *item) const
Returns true if this item's bounding rect is completely obscured by the opaque shape of item.
bool isPanel () const
Returns true if the item is a panel; otherwise returns false.
bool isSelected () const
Returns true if this item is selected; otherwise, false is returned.
bool isUnderMouse () const
Returns true if this item is currently under the mouse cursor in one of the views; otherwise, false is returned.
bool isVisible () const
Returns true if the item is visible; otherwise, false is returned.
bool isVisibleTo (const QGraphicsItem *parent) const
Returns true if the item is visible to parent; otherwise, false is returned.
bool isWidget () const
Returns true if this item is a widget (i.
bool isWindow () const
Returns true if the item is a QGraphicsWidget window, otherwise returns false.
QTransform itemTransform (const QGraphicsItem *other, bool *ok=0) const
Returns a QTransform that maps coordinates from this item to other.
QPointF mapFromItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in item's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in item's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in item's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapFromItem(item, QPointF(x, y)).
QPolygonF mapFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapFromParent (const QPointF &point) const
Maps the point point, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromParent (const QPainterPath &path) const
Maps the path path, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromParent(QPointF(x, y)).
QPolygonF mapFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromItem(QRectF(x, y, w, h)).
QPointF mapFromScene (const QPointF &point) const
Maps the point point, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped coordinate.
QPolygonF mapFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapFromScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Maps the path path, which is in this item's scene's coordinate system, to this item's coordinate system, and returns the mapped path.
QPointF mapFromScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapFromScene(QPointF(x, y)).
QPolygonF mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapFromScene(QRectF(x, y, w, h)).
QRectF mapRectFromItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in item's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectFromParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's parent's coordinate system, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromParent(QRectF(x, y, w, h)).
QRectF mapRectFromScene (const QRectF &rect) const
Maps the rectangle rect, which is in scene coordinates, to this item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectFromScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectFromScene(QRectF(x, y, w, h)).
QRectF mapRectToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QRectF mapRectToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToParent(QRectF(x, y, w, h)).
QRectF mapRectToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene coordinate system, and returns the mapped rectangle as a new rectangle (i.
QRectF mapRectToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapRectToScene(QRectF(x, y, w, h)).
QPointF mapToItem (const QGraphicsItem *item, const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to item's coordinate system, and returns the mapped coordinate.
QPolygonF mapToItem (const QGraphicsItem *item, const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to item's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToItem (const QGraphicsItem *item, const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to item's coordinate system, and returns the mapped polygon.
QPainterPath mapToItem (const QGraphicsItem *item, const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to item's coordinate system, and returns the mapped path.
QPointF mapToItem (const QGraphicsItem *item, qreal x, qreal y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This convenience function is equivalent to calling mapToItem(item, QPointF(x, y)).
QPolygonF mapToItem (const QGraphicsItem *item, qreal x, qreal y, qreal w, qreal h) const
QPointF mapToParent (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped coordinate.
QPolygonF mapToParent (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToParent (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped polygon.
QPainterPath mapToParent (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to its parent's coordinate system, and returns the mapped path.
QPointF mapToParent (qreal x, qreal y) const
This convenience function is equivalent to calling mapToParent(QPointF(x, y)).
QPolygonF mapToParent (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToParent(QRectF(x, y, w, h)).
QPointF mapToScene (const QPointF &point) const
Maps the point point, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped coordinate.
QPolygonF mapToScene (const QRectF &rect) const
Maps the rectangle rect, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped rectangle as a polygon.
QPolygonF mapToScene (const QPolygonF &polygon) const
Maps the polygon polygon, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Maps the path path, which is in this item's coordinate system, to the scene's coordinate system, and returns the mapped path.
QPointF mapToScene (qreal x, qreal y) const
This convenience function is equivalent to calling mapToScene(QPointF(x, y)).
QPolygonF mapToScene (qreal x, qreal y, qreal w, qreal h) const
This convenience function is equivalent to calling mapToScene(QRectF(x, y, w, h)).
QMatrix matrix () const
Returns the item's affine transformation matrix.
void moveBy (qreal dx, qreal dy)
Moves the item by dx points horizontally, and dy point vertically.
qreal opacity () const
Returns this item's local opacity, which is between 0.
virtual QPainterPath opaqueArea () const
This virtual function returns a shape representing the area where this item is opaque.
QGraphicsItem * panel () const
Returns the item's panel, or 0 if this item does not have a panel.
PanelModality panelModality () const
Returns the modality for this item.
QGraphicsItem * parentItem () const
Returns a pointer to this item's parent item.
QGraphicsObject * parentObject () const
Returns a pointer to the item's parent, cast to a QGraphicsObject.
QGraphicsWidget * parentWidget () const
Returns a pointer to the item's parent widget.
QPointF pos () const
Returns the position of the item in parent coordinates.
QGraphicsItem (QGraphicsItem *parent=0)
Constructs a QGraphicsItem with the given parent item.
void removeSceneEventFilter (QGraphicsItem *filterItem)
Removes an event filter on this item from filterItem.
void resetMatrix ()
Use resetTransform() instead.
void resetTransform ()
Resets this item's transformation matrix to the identity matrix or all the transformation properties to their default values.
void rotate (qreal angle)
Use.
qreal rotation () const
Returns the clockwise rotation, in degrees, around the Z axis.
void scale (qreal sx, qreal sy)
Use.
qreal scale () const
Returns the scale factor of the item.
QGraphicsScene * scene () const
Returns the current scene for the item, or 0 if the item is not stored in a scene.
QRectF sceneBoundingRect () const
Returns the bounding rect of this item in scene coordinates, by combining sceneTransform() with boundingRect().
QMatrix sceneMatrix () const
Use sceneTransform() instead.
QPointF scenePos () const
Returns the item's position in scene coordinates.
QTransform sceneTransform () const
Returns this item's scene transformation matrix.
void scroll (qreal dx, qreal dy, const QRectF &rect=QRectF())
Scrolls the contents of rect by dx, dy.
void setAcceptDrops (bool on)
If on is true, this item will accept drag and drop events; otherwise, it is transparent for drag and drop events.
void setAcceptedMouseButtons (Qt::MouseButtons buttons)
Sets the mouse buttons that this item accepts mouse events for.
void setAcceptHoverEvents (bool enabled)
If enabled is true, this item will accept hover events; otherwise, it will ignore them.
void setAcceptsHoverEvents (bool enabled)
Use setAcceptHoverEvents(enabled) instead.
void setAcceptTouchEvents (bool enabled)
If enabled is true, this item will accept touch events; otherwise, it will ignore them.
void setActive (bool active)
If active is true, and the scene is active, this item's panel will be activated.
void setBoundingRegionGranularity (qreal granularity)
Sets the bounding region granularity to granularity; a value between and including 0 and 1.
void setCacheMode (CacheMode mode, const QSize &cacheSize=QSize())
Sets the item's cache mode to mode.
void setCursor (const QCursor &cursor)
Sets the current cursor shape for the item to cursor.
void setData (int key, const QVariant &value)
Sets this item's custom data for the key key to value.
void setEnabled (bool enabled)
If enabled is true, the item is enabled; otherwise, it is disabled.
void setFiltersChildEvents (bool enabled)
If enabled is true, this item is set to filter all events for all its children (i.
void setFlag (GraphicsItemFlag flag, bool enabled=true)
If enabled is true, the item flag flag is enabled; otherwise, it is disabled.
void setFlags (GraphicsItemFlags flags)
Sets the item flags to flags.
void setFocus (Qt::FocusReason focusReason=Qt::OtherFocusReason)
Gives keyboard input focus to this item.
void setFocusProxy (QGraphicsItem *item)
Sets the item's focus proxy to item.
void setGraphicsEffect (QGraphicsEffect *effect)
Sets effect as the item's effect.
void setGroup (QGraphicsItemGroup *group)
Adds this item to the item group group.
void setHandlesChildEvents (bool enabled)
If enabled is true, this item is set to handle all events for all its children (i.
void setInputMethodHints (Qt::InputMethodHints hints)
Sets the current input method hints of this item to hints.
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the item's affine transformation matrix.
void setOpacity (qreal opacity)
Sets this item's local opacity, between 0.
void setPanelModality (PanelModality panelModality)
Sets the modality for this item to panelModality.
void setParentItem (QGraphicsItem *parent)
Sets this item's parent item to newParent.
void setPos (const QPointF &pos)
Sets the position of the item to pos, which is in parent coordinates.
void setPos (qreal x, qreal y)
This convenience function is equivalent to calling setPos(QPointF(x, y)).
void setRotation (qreal angle)
Sets the clockwise rotation angle, in degrees, around the Z axis.
void setScale (qreal scale)
Sets the scale factor of the item.
void setSelected (bool selected)
If selected is true and this item is selectable, this item is selected; otherwise, it is unselected.
void setToolTip (const QString &toolTip)
Sets the item's tool tip to toolTip.
void setTransform (const QTransform &matrix, bool combine=false)
Sets the item's current transformation matrix to matrix.
void setTransformations (const QList< QGraphicsTransform *> &transformations)
Sets a list of graphics transformations (QGraphicsTransform) that currently apply to this item.
void setTransformOriginPoint (const QPointF &origin)
Sets the origin point for the transformation in item coordinates.
void setTransformOriginPoint (qreal ax, qreal ay)
Sets the origin point for the transformation in item coordinates.
void setVisible (bool visible)
If visible is true, the item is made visible.
void setX (qreal x)
Set's the x coordinate of the item's position.
void setY (qreal y)
Set's the y coordinate of the item's position.
void setZValue (qreal z)
Sets the Z-value of the item to z.
void shear (qreal sh, qreal sv)
Use.
void show ()
Shows the item.
void stackBefore (const QGraphicsItem *sibling)
Stacks this item before sibling, which must be a sibling item (i.
QGraphicsObject * toGraphicsObject ()
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
const QGraphicsObject * toGraphicsObject () const
Return the graphics item cast to a QGraphicsObject, if the class is actually a graphics object, 0 otherwise.
QString toolTip () const
Returns the item's tool tip, or an empty QString if no tool tip has been set.
QGraphicsItem * topLevelItem () const
Returns this item's top-level item.
QGraphicsWidget * topLevelWidget () const
Returns a pointer to the item's top level widget (i.
QTransform transform () const
Returns this item's transformation matrix.
QList< QGraphicsTransform * > transformations () const
Returns a list of graphics transforms that currently apply to this item.
QPointF transformOriginPoint () const
Returns the origin point for the transformation in item coordinates.
void translate (qreal dx, qreal dy)
Use setPos() or setTransformOriginPoint() instead.
void ungrabKeyboard ()
Releases the keyboard grab.
void ungrabMouse ()
Releases the mouse grab.
void unsetCursor ()
Clears the cursor from this item.
void update (const QRectF &rect=QRectF())
Schedules a redraw of the area covered by rect in this item.
void update (qreal x, qreal y, qreal width, qreal height)
This convenience function is equivalent to calling update(QRectF(x, y, width, height)).
QGraphicsWidget * window () const
Returns the item's window, or 0 if this item does not have a window.
qreal x () const
This convenience function is equivalent to calling pos().
qreal y () const
This convenience function is equivalent to calling pos().
qreal zValue () const
Returns the Z-value of the item.
virtual ~QGraphicsItem ()
Destroys the QGraphicsItem and all its children.
Public Functions inherited from QGraphicsLayoutItem
QRectF contentsRect () const
Returns the contents rect in local coordinates.
QSizeF effectiveSizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Returns the effective size hint for this QGraphicsLayoutItem.
QRectF geometry () const
Returns the item's geometry (e.
QGraphicsItem * graphicsItem () const
Returns the QGraphicsItem that this layout item represents.
bool isLayout () const
Returns true if this QGraphicsLayoutItem is a layout (e.g., is inherited by an object that arranges other QGraphicsLayoutItem objects); otherwise returns false.
qreal maximumHeight () const
Returns the maximum height.
QSizeF maximumSize () const
Returns the maximum size.
qreal maximumWidth () const
Returns the maximum width.
qreal minimumHeight () const
Returns the minimum height.
QSizeF minimumSize () const
Returns the minimum size.
qreal minimumWidth () const
Returns the minimum width.
bool ownedByLayout () const
Returns whether a layout should delete this item in its destructor.
QGraphicsLayoutItem * parentLayoutItem () const
Returns the parent of this QGraphicsLayoutItem, or 0 if there is no parent, or if the parent does not inherit from QGraphicsLayoutItem (QGraphicsLayoutItem is often used through multiple inheritance with QObject-derived classes).
qreal preferredHeight () const
Returns the preferred height.
QSizeF preferredSize () const
Returns the preferred size.
qreal preferredWidth () const
Returns the preferred width.
QGraphicsLayoutItem (QGraphicsLayoutItem *parent=0, bool isLayout=false)
Constructs the QGraphicsLayoutItem object.
void setMaximumHeight (qreal height)
Sets the maximum height to height.
void setMaximumSize (const QSizeF &size)
Sets the maximum size to size.
void setMaximumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMaximumSize(QSizeF(w, h)).
void setMaximumWidth (qreal width)
Sets the maximum width to width.
void setMinimumHeight (qreal height)
Sets the minimum height to height.
void setMinimumSize (const QSizeF &size)
Sets the minimum size to size.
void setMinimumSize (qreal w, qreal h)
This convenience function is equivalent to calling setMinimumSize(QSizeF(w, h)).
void setMinimumWidth (qreal width)
Sets the minimum width to width.
void setParentLayoutItem (QGraphicsLayoutItem *parent)
Sets the parent of this QGraphicsLayoutItem to parent.
void setPreferredHeight (qreal height)
Sets the preferred height to height.
void setPreferredSize (const QSizeF &size)
Sets the preferred size to size.
void setPreferredSize (qreal w, qreal h)
This convenience function is equivalent to calling setPreferredSize(QSizeF(w, h)).
void setPreferredWidth (qreal width)
Sets the preferred width to width.
void setSizePolicy (const QSizePolicy &policy)
Sets the size policy to policy.
void setSizePolicy (QSizePolicy::Policy hPolicy, QSizePolicy::Policy vPolicy, QSizePolicy::ControlType controlType=QSizePolicy::DefaultType)
This function is equivalent to calling setSizePolicy(QSizePolicy(hPolicy, vPolicy, controlType)).
QSizePolicy sizePolicy () const
Returns the current size policy.
virtual ~QGraphicsLayoutItem ()
Destroys the QGraphicsLayoutItem object.
Static Public Functions
static void setTabOrder (QGraphicsWidget *first, QGraphicsWidget *second)
Moves the second widget around the ring of focus widgets so that keyboard focus moves from the first widget to the second widget when the Tab key is pressed.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
virtual void changeEvent (QEvent *event)
This event handler can be reimplemented to handle state changes.
virtual void closeEvent (QCloseEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive widget close events.
bool event (QEvent *event)
Handles the event.
void focusInEvent (QFocusEvent *event)
Reimplemented Function
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget; returns false otherwise.
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
virtual void grabKeyboardEvent (QEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::GrabKeyboard events.
virtual void grabMouseEvent (QEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::GrabMouse events.
virtual void hideEvent (QHideEvent *event)
This event handler, for Hide events, is delivered after the widget has been hidden, for example, setVisible(false) has been called for the widget or one of its ancestors when the widget was previously shown.
virtual void hoverLeaveEvent (QGraphicsSceneHoverEvent *event)
Reimplemented Function
virtual void hoverMoveEvent (QGraphicsSceneHoverEvent *event)
Reimplemented Function
virtual void initStyleOption (QStyleOption *option) const
Populates a style option object for this widget based on its current state, and stores the output in option.
QVariant itemChange (GraphicsItemChange change, const QVariant &value)
QGraphicsWidget uses the base implementation of this function to catch and deliver events related to state changes in the item.
virtual void moveEvent (QGraphicsSceneMoveEvent *event)
This event handler, for GraphicsSceneMove events, is delivered after the widget has moved (e.g., its local position has changed).
virtual void polishEvent ()
This event is delivered to the item by the scene at some point after it has been constructed, but before it is shown or otherwise accessed through the scene.
virtual QVariant propertyChange (const QString &propertyName, const QVariant &value)
This virtual function is used to notify changes to any property (both dynamic properties, and registered with e.g., "size";, and value is the (proposed) new value of the property.
QGraphicsWidget (QGraphicsWidgetPrivate &, QGraphicsItem *parent, QGraphicsScene *, Qt::WindowFlags wFlags=0)
Constructs a new QGraphicsWidget, using dd as parent.
virtual void resizeEvent (QGraphicsSceneResizeEvent *event)
This event handler, for GraphicsSceneResize events, is delivered after the widget has been resized (i.e., its local size has changed).
bool sceneEvent (QEvent *event)
QGraphicsWidget's implementation of sceneEvent() simply passes event to QGraphicsWidget::event().
virtual void showEvent (QShowEvent *event)
This event handler, for Show events, is delivered before the widget has been shown, for example, setVisible(true) has been called for the widget or one of its ancestors when the widget was previously hidden.
QSizeF sizeHint (Qt::SizeHint which, const QSizeF &constraint=QSizeF()) const
Reimplemented Function
virtual void ungrabKeyboardEvent (QEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::UngrabKeyboard events.
virtual void ungrabMouseEvent (QEvent *event)
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::UngrabMouse events.
void updateGeometry ()
If this widget is currently managed by a layout, this function notifies the layout that the widget's size hints have changed and the layout may need to resize and reposition the widget accordingly.
virtual bool windowFrameEvent (QEvent *e)
This event handler, for event, receives events for the window frame if this widget is a window.
virtual Qt::WindowFrameSection windowFrameSectionAt (const QPointF &pos) const
Returns the window frame section at position pos, or Qt::NoSection if there is no window frame section at this position.
Protected Functions inherited from QGraphicsObject
QGraphicsObject (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QGraphicsItem
void addToIndex ()
Adds this item to the scene's index.
virtual void contextMenuEvent (QGraphicsSceneContextMenuEvent *event)
This event handler can be reimplemented in a subclass to process context menu events.
virtual void dragEnterEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag enter events for this item.
virtual void dragLeaveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag leave events for this item.
virtual void dragMoveEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drag move events for this item.
virtual void dropEvent (QGraphicsSceneDragDropEvent *event)
This event handler, for event event, can be reimplemented to receive drop events for this item.
virtual QVariant extension (const QVariant &variant) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual void hoverEnterEvent (QGraphicsSceneHoverEvent *event)
This event handler, for event event, can be reimplemented to receive hover enter events for this item.
virtual void inputMethodEvent (QInputMethodEvent *event)
This event handler, for event event, can be reimplemented to receive input method events for this item.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
This method is only relevant for input items.
virtual void keyPressEvent (QKeyEvent *event)
This event handler, for event event, can be reimplemented to receive key press events for this item.
virtual void keyReleaseEvent (QKeyEvent *event)
This event handler, for event event, can be reimplemented to receive key release events for this item.
virtual void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse doubleclick events for this item.
virtual void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse move events for this item.
virtual void mousePressEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse press events for this item.
virtual void mouseReleaseEvent (QGraphicsSceneMouseEvent *event)
This event handler, for event event, can be reimplemented to receive mouse release events for this item.
void prepareGeometryChange ()
Prepares the item for a geometry change.
QGraphicsItem (QGraphicsItemPrivate &dd, QGraphicsItem *parent, QGraphicsScene *scene)
void removeFromIndex ()
Removes this item from the scene's index.
virtual bool sceneEventFilter (QGraphicsItem *watched, QEvent *event)
Filters events for the item watched.
virtual void setExtension (Extension extension, const QVariant &variant)
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
virtual bool supportsExtension (Extension extension) const
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
void updateMicroFocus ()
Updates the item's micro focus.
virtual void wheelEvent (QGraphicsSceneWheelEvent *event)
This event handler, for event event, can be reimplemented to receive wheel events for this item.
Protected Functions inherited from QGraphicsLayoutItem
QGraphicsLayoutItem (QGraphicsLayoutItemPrivate &dd)
void setGraphicsItem (QGraphicsItem *item)
If the QGraphicsLayoutItem represents a QGraphicsItem, and it wants to take advantage of the automatic reparenting capabilities of QGraphicsLayout it should set this value.
void setOwnedByLayout (bool ownedByLayout)
Sets whether a layout should delete this item in its destructor or not.
Properties
bool autoFillBackground
whether the widget background is filled automatically
Qt::FocusPolicy focusPolicy
the way the widget accepts keyboard focus
QFont font
the widgets' font
QRectF geometry
the geometry of the widget
QGraphicsLayout * layout
The layout of the widget.
Qt::LayoutDirection layoutDirection
the layout direction for this widget.
QSizeF maximumSize
the maximum size of the widget
QSizeF minimumSize
the minimum size of the widget
QPalette palette
the widget's palette
QSizeF preferredSize
the preferred size of the widget
QSizeF size
the size of the widget
QSizePolicy sizePolicy
the size policy for the widget
Qt::WindowFlags windowFlags
the widget's window flags
QString windowTitle
This property holds the window title (caption).
Friends
class QApplication
class QGraphicsItem
class QGraphicsItemPrivate
class QGraphicsLayout
class QGraphicsScene
class QGraphicsScenePrivate
class QGraphicsView
class QWidget
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QGraphicsItem
enum Extension { UserExtension = 0x80000000 }
Note: This is provided as a hook to avoid future problems related to adding virtual functions.
Protected Slots inherited from QGraphicsObject
void updateMicroFocus ()
Updates the item's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QGraphicsItem
QScopedPointer< QGraphicsItemPrivate > d_ptr
Protected Variables inherited from QGraphicsLayoutItem
QScopedPointer< QGraphicsLayoutItemPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QGraphicsItem
T qgraphicsitem_cast (QGraphicsItem *item)
Detailed Description
The QGraphicsWidget class is the base class for all widget items in a QGraphicsScene.
Since
4.4
QGraphicsWidget is an extended base item that provides extra functionality over QGraphicsItem. It is similar to QWidget in many ways:
Provides a palette , a font and a style() .
Has a defined geometry().
Supports layouts with setLayout() and layout().
Supports shortcuts and actions with grabShortcut() and insertAction()
Unlike QGraphicsItem, QGraphicsWidget is not an abstract class; you can create instances of a QGraphicsWidget without having to subclass it. This approach is useful for widgets that only serve the purpose of organizing child widgets into a layout.
QGraphicsWidget can be used as a base item for your own custom item if you require advanced input focus handling, e.g., tab focus and activation, or layouts.
Since QGraphicsWidget resembles QWidget and has similar API, it is easier to port a widget from QWidget to QGraphicsWidget, instead of QGraphicsItem.
Note
QWidget-based widgets can be directly embedded into a QGraphicsScene using QGraphicsProxyWidget.
Noticeable differences between QGraphicsWidget and QWidget are:
QGraphicsWidget QWidget
Coordinates and geometry are defined with qreals (doubles or floats, depending on the platform). QWidget uses integer geometry (QPoint, QRect).
The widget is already visible by default; you do not have to call show() to display the widget. QWidget is hidden by default until you call show().
A subset of widget attributes are supported. All widget attributes are supported.
A top-level item's style defaults to QGraphicsScene::style A top-level widget's style defaults to QApplication::style
Graphics View provides a custom drag and drop framework, different from QWidget. Standard drag and drop framework.
Widget items do not support modality. Full modality support.
QGraphicsWidget supports a subset of Qt's widget attributes, (Qt::WidgetAttribute), as shown in the table below. Any attributes not listed in this table are unsupported, or otherwise unused.
Widget Attribute Usage
Qt::WA_SetLayoutDirection Set by setLayoutDirection(), cleared by unsetLayoutDirection(). You can test this attribute to check if the widget has been explicitly assigned a layoutDirection. If the attribute is not set, the layoutDirection() is inherited.
Qt::WA_RightToLeft Toggled by setLayoutDirection(). Inherited from the parent/scene. If set, the widget's layout will order horizontally arranged widgets from right to left.
Qt::WA_SetStyle Set and cleared by setStyle(). If this attribute is set, the widget has been explicitly assigned a style. If it is unset, the widget will use the scene's or the application's style.
Qt::WA_Resized Set by setGeometry() and resize().
Qt::WA_SetPalette Set by setPalette().
Qt::WA_SetFont Set by setFont().
Qt::WA_WindowPropagation Enables propagation to window widgets.
Although QGraphicsWidget inherits from both QObject and QGraphicsItem, you should use the functions provided by QGraphicsItem, not QObject, to manage the relationships between parent and child items. These functions control the stacking order of items as well as their ownership.
Note
The QObject::parent() should always return 0 for QGraphicsWidgets, but this policy is not strictly defined.
See also
QGraphicsProxyWidget, QGraphicsItem, {Widgets and Layouts}
Definition at line 69 of file qgraphicswidget.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
Type
Definition at line 161 of file qgraphicswidget.h.
          {
         Type = 11
     };
Constructors and Destructors
QGraphicsWidget() [1/2]
QGraphicsWidget::QGraphicsWidget (QGraphicsItem * parent = 0, Qt::WindowFlags wFlags = 0)
Constructs a QGraphicsWidget instance.
The optional parent argument is passed to QGraphicsItem's constructor. The optional wFlags argument specifies the widget's window flags (e.g., whether the widget should be a window, a tool, a popup, etc).
Definition at line 178 of file qgraphicswidget.cpp.
     : QGraphicsObject(*new QGraphicsWidgetPrivate, 0, 0), QGraphicsLayoutItem(0, false)
 {
     Q_D(QGraphicsWidget);
     d->init(parent, wFlags);
 }
~QGraphicsWidget()
QGraphicsWidget::~QGraphicsWidget ()
Destroys the QGraphicsWidget instance.
Definition at line 236 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
 #ifndef QT_NO_ACTION
     // Remove all actions from this widget
     for (int i = 0; i < d->actions.size(); ++i) {
         QActionPrivate *apriv = d->actions.at(i)->d_func();
         apriv->graphicsWidgets.removeAll(this);
     }
     d->actions.clear();
 #endif
     if (QGraphicsScene *scn = scene()) {
         QGraphicsScenePrivate *sceneD = scn->d_func();
         if (sceneD->tabFocusFirst == this)
             sceneD->tabFocusFirst = (d->focusNext == this ? 0 : d->focusNext);
     }
     d->focusPrev->d_func()->focusNext = d->focusNext;
     d->focusNext->d_func()->focusPrev = d->focusPrev;
     // Play it really safe
     d->focusNext = this;
     d->focusPrev = this;
     clearFocus();
     //we check if we have a layout previously
     if (d->layout) {
         QGraphicsLayout *temp = d->layout;
         foreach (QGraphicsItem * item, childItems()) {
             // In case of a custom layout which doesn't remove and delete items, we ensure that
             // the parent layout item does not point to the deleted layout. This code is here to
             // avoid regression from 4.4 to 4.5, because according to 4.5 docs it is not really needed.
             if (item->isWidget()) {
                 QGraphicsWidget *widget = static_cast<QGraphicsWidget *>(item);
                 if (widget->parentLayoutItem() == d->layout)
                     widget->setParentLayoutItem(0);
             }
         }
         d->layout = 0;
         delete temp;
     }
     // Remove this graphics widget from widgetStyles
     widgetStyles()->setStyleForWidget(this, 0);
 }
QGraphicsWidget() [2/2]
QGraphicsWidget::QGraphicsWidget (QGraphicsWidgetPrivate & dd, QGraphicsItem * parent, QGraphicsScene * scene, Qt::WindowFlags wFlags = 0) protected
Constructs a new QGraphicsWidget, using dd as parent.
Warning
This function is not part of the public interface.
Definition at line 193 of file qgraphicswidget.cpp.
     : QGraphicsObject(dd, 0, scene), QGraphicsLayoutItem(0, false)
 {
     Q_D(QGraphicsWidget);
     d->init(parent, wFlags);
 }
Functions
actions()
QList< QAction * > QGraphicsWidget::actions () const
Returns the (possibly empty) list of this widget's actions.
Since
4.5
See also
insertAction(), removeAction(), QWidget::actions(), QAction::associatedWidgets(), QAction::associatedGraphicsWidgets()
Definition at line 2177 of file qgraphicswidget.cpp.
 {
     Q_D(const QGraphicsWidget);
     return d->actions;
 }
addAction()
void QGraphicsWidget::addAction (QAction * action)
Appends the action action to this widget's list of actions.
Since
4.5
All QGraphicsWidgets have a list of QAction, however they can be represented graphically in many different ways. The default use of the QAction list (as returned by actions()) is to create a context QMenu.
A QGraphicsWidget should only have one of each action and adding an action it already has will not cause the same action to be in the widget twice.
See also
removeAction(), insertAction(), actions(), QWidget::addAction()
Definition at line 2056 of file qgraphicswidget.cpp.
 {
     insertAction(0, action);
 }
addActions()
void QGraphicsWidget::addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
Since
4.5
See also
removeAction(), QMenu, addAction(), QWidget::addActions()
Definition at line 2071 of file qgraphicswidget.cpp.
 {
     for (int i = 0; i < actions.count(); ++i)
         insertAction(0, actions.at(i));
 }
adjustSize()
void QGraphicsWidget::adjustSize ()
Adjusts the size of the widget to its effective preferred size hint.
This function is called implicitly when the item is shown for the first time.
See also
effectiveSizeHint(), Qt::MinimumSize
Definition at line 892 of file qgraphicswidget.cpp.
Referenced by itemChange().
 {
     QSizeF sz = effectiveSizeHint(Qt::PreferredSize);
     // What if sz is not valid?!
     if (sz.isValid())
         resize(sz);
 }
autoFillBackground()
bool QGraphicsWidget::autoFillBackground () const
Referenced by setPalette().
boundingRect()
QRectF QGraphicsWidget::boundingRect () const virtual
Reimplemented Function
Implements QGraphicsItem.
Definition at line 2437 of file qgraphicswidget.cpp.
 {
     return windowFrameRect();
 }
changeEvent()
void QGraphicsWidget::changeEvent (QEvent * event) protected virtual
This event handler can be reimplemented to handle state changes.
The state being changed in this event can be retrieved through event.
Change events include: QEvent::ActivationChange, QEvent::EnabledChange, QEvent::FontChange, QEvent::StyleChange, QEvent::PaletteChange, QEvent::ParentChange, QEvent::LayoutDirectionChange, and QEvent::ContentsRectChange.
Definition at line 1526 of file qgraphicswidget.cpp.
Referenced by event().
 {
     Q_D(QGraphicsWidget);
     switch (event->type()) {
     case QEvent::StyleChange:
         // ### Don't unset if the margins are explicitly set.
         unsetWindowFrameMargins();
         if (d->layout)
             d->layout->invalidate();
     case QEvent::FontChange:
         update();
         updateGeometry();
         break;
     case QEvent::PaletteChange:
         update();
         break;
     case QEvent::ParentChange:
         d->resolveFont(d->inheritedFontResolveMask);
         d->resolvePalette(d->inheritedPaletteResolveMask);
         break;
     default:
         break;
     }
 }
close
bool QGraphicsWidget::close () slot
Call this function to close the widget.
Returns true if the widget was closed; otherwise returns false. This slot will first send a QCloseEvent to the widget, which may or may not accept the event. If the event was ignored, nothing happens. If the event was accepted, it will hide() the widget.
If the widget has the Qt::WA_DeleteOnClose attribute set it will be deleted.
Definition at line 2463 of file qgraphicswidget.cpp.
Referenced by QGraphicsItem::mousePressEvent().
 {
     QCloseEvent closeEvent;
     QApplication::sendEvent(this, &closeEvent);
     if (!closeEvent.isAccepted()) {
         return false;
     }
     // hide
     if (isVisible()) {
         hide();
     }
     if (testAttribute(Qt::WA_DeleteOnClose)) {
         deleteLater();
     }
     return true;
 }
closeEvent()
void QGraphicsWidget::closeEvent (QCloseEvent * event) protected virtual
This event handler, for event, can be reimplemented in a subclass to receive widget close events.
The default implementation accepts the event.
See also
close(), QCloseEvent
Definition at line 1558 of file qgraphicswidget.cpp.
Referenced by close(), and event().
 {
     event->accept();
 }
event()
bool QGraphicsWidget::event (QEvent * event) protected virtual
Handles the event.
Reimplemented Function
QGraphicsWidget handles the following events:
Event
Usage
Polish
Delivered to the widget some time after it has been shown.
GraphicsSceneMove
Delivered to the widget after its local position has changed.
GraphicsSceneResize
Delivered to the widget after its size has changed.
Show
Delivered to the widget before it has been shown.
Hide
Delivered to the widget after it has been hidden.
PaletteChange
Delivered to the widget after its palette has changed.
FontChange
Delivered to the widget after its font has changed.
EnabledChange
Delivered to the widget after its enabled state has changed.
StyleChange
Delivered to the widget after its style has changed.
LayoutDirectionChange
Delivered to the widget after its layout direction has changed.
ContentsRectChange
Delivered to the widget after its contents margins/ contents rect has changed.
Reimplemented from QObject.
Definition at line 1432 of file qgraphicswidget.cpp.
Referenced by QGraphicsProxyWidget::event(), itemChange(), setGeometry(), and setStyle().
 {
     Q_D(QGraphicsWidget);
     // Forward the event to the layout first.
     if (d->layout)
         d->layout->widgetEvent(event);
     // Handle the event itself.
     switch (event->type()) {
     case QEvent::GraphicsSceneMove:
         moveEvent(static_cast<QGraphicsSceneMoveEvent *>(event));
         break;
     case QEvent::GraphicsSceneResize:
         resizeEvent(static_cast<QGraphicsSceneResizeEvent *>(event));
         break;
     case QEvent::Show:
         showEvent(static_cast<QShowEvent *>(event));
         break;
     case QEvent::Hide:
         hideEvent(static_cast<QHideEvent *>(event));
         break;
     case QEvent::Polish:
         polishEvent();
         d->polished = true;
         if (!d->font.isCopyOf(QApplication::font()))
             d->updateFont(d->font);
         break;
     case QEvent::WindowActivate:
     case QEvent::WindowDeactivate:
         update();
         break;
         // Taken from QWidget::event
     case QEvent::ActivationChange:
     case QEvent::EnabledChange:
     case QEvent::FontChange:
     case QEvent::StyleChange:
     case QEvent::PaletteChange:
     case QEvent::ParentChange:
     case QEvent::ContentsRectChange:
     case QEvent::LayoutDirectionChange:
         changeEvent(event);
         break;
     case QEvent::Close:
         closeEvent((QCloseEvent *)event);
         break;
     case QEvent::GrabMouse:
         grabMouseEvent(event);
         break;
     case QEvent::UngrabMouse:
         ungrabMouseEvent(event);
         break;
     case QEvent::GrabKeyboard:
         grabKeyboardEvent(event);
         break;
     case QEvent::UngrabKeyboard:
         ungrabKeyboardEvent(event);
         break;
     case QEvent::GraphicsSceneMousePress:
         if (d->hasDecoration() && windowFrameEvent(event))
             return true;
     case QEvent::GraphicsSceneMouseMove:
     case QEvent::GraphicsSceneMouseRelease:
     case QEvent::GraphicsSceneMouseDoubleClick:
         d->ensureWindowData();
         if (d->hasDecoration() && d->windowData->grabbedSection != Qt::NoSection)
             return windowFrameEvent(event);
         break;
     case QEvent::GraphicsSceneHoverEnter:
     case QEvent::GraphicsSceneHoverMove:
     case QEvent::GraphicsSceneHoverLeave:
         if (d->hasDecoration()) {
             windowFrameEvent(event);
             // Filter out hover events if they were sent to us only because of the
             // decoration (special case in QGraphicsScenePrivate::dispatchHoverEvent).
             if (!acceptsHoverEvents())
                 return true;
         }
         break;
     default:
         break;
     }
     return QObject::event(event);
 }
focusInEvent()
void QGraphicsWidget::focusInEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1566 of file qgraphicswidget.cpp.
 {
     Q_UNUSED(event);
     if (focusPolicy() != Qt::NoFocus)
         update();
 }
focusNextPrevChild()
bool QGraphicsWidget::focusNextPrevChild (bool next) protected virtual
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget; returns false otherwise.
If next is true, this function searches forward; if next is false, it searches backward.
Sometimes, you will want to reimplement this function to provide special focus handling for your widget and its subwidgets. For example, a web browser might reimplement it to move its current active link forward or backward, and call the base implementation only when it reaches the last or first link on the page.
Child widgets call focusNextPrevChild() on their parent widgets, but only the window that contains the child widgets decides where to redirect focus. By reimplementing this function for an object, you gain control of focus traversal for all child widgets.
See also
focusPolicy()
Reimplemented in QGraphicsProxyWidget.
Definition at line 1592 of file qgraphicswidget.cpp.
Referenced by QGraphicsProxyWidget::focusNextPrevChild(), and focusNextPrevChild().
 {
     Q_D(QGraphicsWidget);
     // Let the parent's focusNextPrevChild implementation decide what to do.
     QGraphicsWidget *parent = 0;
     if (!isWindow() && (parent = parentWidget()))
         return parent->focusNextPrevChild(next);
     if (!d->scene)
         return false;
     if (d->scene->focusNextPrevChild(next))
         return true;
     if (isWindow()) {
         setFocus(next ? Qt::TabFocusReason : Qt::BacktabFocusReason);
         if (hasFocus())
             return true;
     }
     return false;
 }
focusOutEvent()
void QGraphicsWidget::focusOutEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 1614 of file qgraphicswidget.cpp.
 {
     Q_UNUSED(event);
     if (focusPolicy() != Qt::NoFocus)
         update();
 }
focusPolicy()
Qt::FocusPolicy QGraphicsWidget::focusPolicy () const
Referenced by focusInEvent(), focusOutEvent(), and setWindowTitle().
focusWidget()
QGraphicsWidget * QGraphicsWidget::focusWidget () const
If this widget, a child or descendant of this widget currently has input focus, this function will return a pointer to that widget.
If no descendant widget has input focus, 0 is returned.
See also
QGraphicsItem::focusItem(), QWidget::focusWidget()
Definition at line 1920 of file qgraphicswidget.cpp.
Referenced by QGraphicsScenePrivate::addPopup(), QGraphicsProxyWidget::event(), QGraphicsProxyWidget::focusOutEvent(), and QGraphicsProxyWidget::wheelEvent().
 {
     Q_D(const QGraphicsWidget);
     if (d->subFocusItem && d->subFocusItem->d_ptr->isWidget)
         return static_cast<QGraphicsWidget *>(d->subFocusItem);
     return 0;
 }
font()
QFont QGraphicsWidget::font () const
Referenced by initStyleOption(), setStyle(), and QWidgetPrivate::updateFont().
geometryChanged
QGraphicsWidget::geometryChanged () signal
This signal gets emitted whenever the geometry is changed in setGeometry().
Referenced by setGeometry().
getContentsMargins()
void QGraphicsWidget::getContentsMargins (qreal * left, qreal * top, qreal * right, qreal * bottom) const virtual
Gets the widget's contents margins.
The margins are stored in left, top, right and bottom, as pointers to qreals. Each argument can be {omitted} by passing 0.
See also
setContentsMargins()
Reimplemented from QGraphicsLayoutItem.
Definition at line 546 of file qgraphicswidget.cpp.
 {
     Q_D(const QGraphicsWidget);
     if (left || top || right || bottom)
         d->ensureMargins();
     if (left)
         *left = d->margins[d->Left];
     if (top)
         *top = d->margins[d->Top];
     if (right)
         *right = d->margins[d->Right];
     if (bottom)
         *bottom = d->margins[d->Bottom];
 }
getWindowFrameMargins()
void QGraphicsWidget::getWindowFrameMargins (qreal * left, qreal * top, qreal * right, qreal * bottom) const
Gets the widget's window frame margins.
The margins are stored in left, top, right and bottom as pointers to qreals. Each argument can be {omitted} by passing 0.
See also
setWindowFrameMargins(), windowFrameRect()
Definition at line 601 of file qgraphicswidget.cpp.
 {
     Q_D(const QGraphicsWidget);
     if (left || top || right || bottom)
         d->ensureWindowFrameMargins();
     if (left)
         *left = d->windowFrameMargins[d->Left];
     if (top)
         *top = d->windowFrameMargins[d->Top];
     if (right)
         *right = d->windowFrameMargins[d->Right];
     if (bottom)
         *bottom = d->windowFrameMargins[d->Bottom];
 }
grabKeyboardEvent()
void QGraphicsWidget::grabKeyboardEvent (QEvent * event) protected virtual
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::GrabKeyboard events.
See also
grabKeyboard(), grabMouse()
Definition at line 1755 of file qgraphicswidget.cpp.
Referenced by event().
 {
     Q_UNUSED(event);
 }
grabMouseEvent()
void QGraphicsWidget::grabMouseEvent (QEvent * event) protected virtual
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::GrabMouse events.
See also
grabMouse(), grabKeyboard()
Reimplemented in QGraphicsProxyWidget.
Definition at line 1733 of file qgraphicswidget.cpp.
Referenced by event().
 {
     Q_UNUSED(event);
 }
grabShortcut()
int QGraphicsWidget::grabShortcut (const QKeySequence & sequence, Qt::ShortcutContext context = Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
Since
4.5
If the context is Qt::ApplicationShortcut, the shortcut applies to the application as a whole. Otherwise, it is either local to this widget, Qt::WidgetShortcut, or to the window itself, Qt::WindowShortcut. For widgets that are not part of a window (i.e., top-level widgets and their children), Qt::WindowShortcut shortcuts apply to the scene.
If the same key sequence has been grabbed by several widgets, when the key sequence occurs a QEvent::Shortcut event is sent to all the widgets to which it applies in a non-deterministic order, but with the ``ambiguous'' flag set to true.
Warning
You should not normally need to use this function; instead create QAction with the shortcut key sequences you require (if you also want equivalent menu options and toolbar buttons), or create QShortcut if you just need key sequences. Both QAction and QShortcut handle all the event filtering for you, and provide signals which are triggered when the user triggers the key sequence, so are much easier to use than this low-level function.
See also
releaseShortcut() setShortcutEnabled() QWidget::grabShortcut()
Definition at line 1959 of file qgraphicswidget.cpp.
 {
     Q_ASSERT(qApp);
     if (sequence.isEmpty())
         return 0;
     // ### setAttribute(Qt::WA_GrabbedShortcut);
     return qApp->d_func()->shortcutMap.addShortcut(this, sequence, context);
 }
hideEvent()
void QGraphicsWidget::hideEvent (QHideEvent * event) protected virtual
This event handler, for Hide events, is delivered after the widget has been hidden, for example, setVisible(false) has been called for the widget or one of its ancestors when the widget was previously shown.
You can reimplement this event handler to detect when your widget is hidden. Calling QEvent::accept() or QEvent::ignore() on event has no effect.
See also
showEvent(), QWidget::hideEvent(), ItemVisibleChange
focusNextPrevChild(true), don't lose focus when the focus widget
Reimplemented in QGraphicsProxyWidget.
Definition at line 1633 of file qgraphicswidget.cpp.
Referenced by event().
 {
     // is hidden.
     Q_UNUSED(event);
 }
hoverLeaveEvent()
void QGraphicsWidget::hoverLeaveEvent (QGraphicsSceneHoverEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Reimplemented in QGraphicsProxyWidget.
Definition at line 1722 of file qgraphicswidget.cpp.
 {
     Q_UNUSED(event);
 }
hoverMoveEvent()
void QGraphicsWidget::hoverMoveEvent (QGraphicsSceneHoverEvent * event) protected virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Reimplemented in QGraphicsProxyWidget.
Definition at line 1714 of file qgraphicswidget.cpp.
 {
     Q_UNUSED(event);
 }
initStyleOption()
void QGraphicsWidget::initStyleOption (QStyleOption * option) const protected virtual
Populates a style option object for this widget based on its current state, and stores the output in option.
The default implementation populates option with the following properties.
Style Option Property Value
state & QStyle::State_Enabled Corresponds to QGraphicsItem::isEnabled().
state & QStyle::State_HasFocus Corresponds to QGraphicsItem::hasFocus().
state & QStyle::State_MouseOver Corresponds to QGraphicsItem::isUnderMouse().
direction Corresponds to QGraphicsWidget::layoutDirection().
rect Corresponds to QGraphicsWidget::rect().toRect().
palette Corresponds to QGraphicsWidget::palette().
fontMetrics Corresponds to QFontMetrics(QGraphicsWidget::font()).
Subclasses of QGraphicsWidget should call the base implementation, and then test the type of option using qstyleoption_cast<>() or test QStyleOption::Type before storing widget-specific options.
For example:
void MyGroupBoxWidget::initStyleOption(QStyleOption *option) const
{
    QGraphicsWidget::initStyleOption(option);
    if (QStyleOptionGroupBox *box = qstyleoption_cast<QStyleOptionGroupBox *>(option)) {
        // Add group box specific state.
        box->flat = isFlat();
        ...
    }
}
See also
QStyleOption::initFrom()
Definition at line 709 of file qgraphicswidget.cpp.
Referenced by paintWindowFrame().
 {
     Q_ASSERT(option);
     option->state = QStyle::State_None;
     if (isEnabled())
         option->state |= QStyle::State_Enabled;
     if (hasFocus())
         option->state |= QStyle::State_HasFocus;
     // if (window->testAttribute(Qt::WA_KeyboardFocusChange)) // ### Window
     //     option->state |= QStyle::State_KeyboardFocusChange;
     if (isUnderMouse())
         option->state |= QStyle::State_MouseOver;
     if (QGraphicsWidget *w = window()) {
         if (w->isActiveWindow())
             option->state |= QStyle::State_Active;
     }
     if (isWindow())
         option->state |= QStyle::State_Window;
     /*
       ###
 #ifdef Q_WS_MAC
     extern bool qt_mac_can_clickThrough(const QGraphicsWidget *w); //qwidget_mac.cpp
     if (!(option->state & QStyle::State_Active) && !qt_mac_can_clickThrough(widget))
         option->state &= ~QStyle::State_Enabled;
     switch (QMacStyle::widgetSizePolicy(widget)) {
     case QMacStyle::SizeSmall:
         option->state |= QStyle::State_Small;
         break;
     case QMacStyle::SizeMini:
         option->state |= QStyle::State_Mini;
         break;
     default:
         ;
     }
 #endif
 #ifdef QT_KEYPAD_NAVIGATION
     if (widget->hasEditFocus())
         state |= QStyle::State_HasEditFocus;
 #endif
     */
     option->direction = layoutDirection();
     option->rect = rect().toRect(); // ### truncation!
     option->palette = palette();
     if (!isEnabled()) {
         option->palette.setCurrentColorGroup(QPalette::Disabled);
     } else if (isActiveWindow()) {
         option->palette.setCurrentColorGroup(QPalette::Active);
     } else {
         option->palette.setCurrentColorGroup(QPalette::Inactive);
     }
     option->fontMetrics = QFontMetrics(font());
 }
insertAction()
void QGraphicsWidget::insertAction (QAction * before, QAction * action)
Inserts the action action to this widget's list of actions, before the action before.
Since
4.5
It appends the action if before is 0 or before is not a valid action for this widget.
A QGraphicsWidget should only have one of each action.
See also
removeAction(), addAction(), QMenu, actions(), QWidget::insertActions()
Definition at line 2092 of file qgraphicswidget.cpp.
Referenced by addAction(), addActions(), and insertActions().
 {
     if (!action) {
         qWarning("QWidget::insertAction: Attempt to insert null action");
         return;
     }
     Q_D(QGraphicsWidget);
     int index = d->actions.indexOf(action);
     if (index != -1)
         d->actions.removeAt(index);
     int pos = d->actions.indexOf(before);
     if (pos < 0) {
         before = 0;
         pos = d->actions.size();
     }
     d->actions.insert(pos, action);
     if (index == -1) {
         QActionPrivate *apriv = action->d_func();
         apriv->graphicsWidgets.append(this);
     }
     QActionEvent e(QEvent::ActionAdded, action, before);
     QApplication::sendEvent(this, &e);
 }
insertActions()
void QGraphicsWidget::insertActions (QAction * before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
Since
4.5
It appends the action if before is 0 or before is not a valid action for this widget.
A QGraphicsWidget can have at most one of each action.
See also
removeAction(), QMenu, insertAction(), QWidget::insertActions()
Definition at line 2134 of file qgraphicswidget.cpp.
 {
     for (int i = 0; i < actions.count(); ++i)
         insertAction(before, actions.at(i));
 }
isActiveWindow()
bool QGraphicsWidget::isActiveWindow () const
Returns true if this widget's window is in the active window, or if the widget does not have a window but is in an active scene (i.e., a scene that currently has focus).
The active window is the window that either contains a child widget that currently has input focus, or that itself has input focus.
See also
QGraphicsScene::activeWindow(), QGraphicsScene::setActiveWindow(), isActive()
Definition at line 1845 of file qgraphicswidget.cpp.
Referenced by initStyleOption(), and paintWindowFrame().
 {
     return isActive();
 }
itemChange()
QVariant QGraphicsWidget::itemChange (GraphicsItemChange change, const QVariant & value) protected virtual
QGraphicsWidget uses the base implementation of this function to catch and deliver events related to state changes in the item.
Reimplemented Function
Because of this, it is very important that subclasses call the base implementation.
change specifies the type of change, and value is the new value.
For example, QGraphicsWidget uses ItemVisibleChange to deliver Show and Hide events, ItemPositionHasChanged to deliver Move events, and ItemParentChange both to deliver ParentChange events, and for managing the focus chain.
QGraphicsWidget enables the ItemSendsGeometryChanges flag by default in order to track position changes.
See also
QGraphicsItem::itemChange()
Reimplemented from QGraphicsItem.
Definition at line 1171 of file qgraphicswidget.cpp.
Referenced by QGraphicsProxyWidget::itemChange().
 {
     Q_D(QGraphicsWidget);
     switch (change) {
     case ItemEnabledHasChanged: {
         // Send EnabledChange after the enabled state has changed.
         QEvent event(QEvent::EnabledChange);
         QApplication::sendEvent(this, &event);
         break;
     }
     case ItemVisibleChange:
         if (value.toBool()) {
             // Send Show event before the item has been shown.
             QShowEvent event;
             QApplication::sendEvent(this, &event);
             bool resized = testAttribute(Qt::WA_Resized);
             if (!resized) {
                 adjustSize();
                 setAttribute(Qt::WA_Resized, false);
             }
         }
         break;
     case ItemVisibleHasChanged:
         if (!value.toBool()) {
             // Send Hide event after the item has been hidden.
             QHideEvent event;
             QApplication::sendEvent(this, &event);
         }
         break;
     case ItemPositionHasChanged:
         d->setGeometryFromSetPos();
         break;
     case ItemParentChange: {
         // Deliver ParentAboutToChange.
         QEvent event(QEvent::ParentAboutToChange);
         QApplication::sendEvent(this, &event);
         break;
     }
     case ItemParentHasChanged: {
         // Deliver ParentChange.
         QEvent event(QEvent::ParentChange);
         QApplication::sendEvent(this, &event);
         break;
     }
     case ItemCursorHasChanged: {
         // Deliver CursorChange.
         QEvent event(QEvent::CursorChange);
         QApplication::sendEvent(this, &event);
         break;
     }
     case ItemToolTipHasChanged: {
         // Deliver ToolTipChange.
         QEvent event(QEvent::ToolTipChange);
         QApplication::sendEvent(this, &event);
         break;
     }
     case ItemChildAddedChange: {
         QGraphicsItem *child = qVariantValue<QGraphicsItem *>(value);
         if (child->isWidget())
             static_cast<QGraphicsWidget *>(child)->d_func()->resolveLayoutDirection();
         break;
     }
     default:
         break;
     }
     return QGraphicsItem::itemChange(change, value);
 }
layout()
QGraphicsLayout* QGraphicsWidget::layout () const
Referenced by sizeHint().
layoutChanged
void QGraphicsWidget::layoutChanged () signal
This signal gets emitted whenever the layout of the item changes.
Warning
This function is not part of the public interface.
Referenced by setLayout().
layoutDirection()
Qt::LayoutDirection QGraphicsWidget::layoutDirection () const
Referenced by adjustSize(), and initStyleOption().
moveEvent()
void QGraphicsWidget::moveEvent (QGraphicsSceneMoveEvent * event) protected virtual
This event handler, for GraphicsSceneMove events, is delivered after the widget has moved (e.g., its local position has changed).
This event is only delivered when the item is moved locally. Calling setTransform() or moving any of the item's ancestors does not affect the item's local position.
You can reimplement this event handler to detect when your widget has moved. Calling QEvent::accept() or QEvent::ignore() on event has no effect.
See also
ItemPositionChange, ItemPositionHasChanged
Definition at line 1655 of file qgraphicswidget.cpp.
Referenced by event().
 {
     // ### Last position is always == current position
     Q_UNUSED(event);
 }
paint()
void QGraphicsWidget::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) virtual
Reimplemented Function
Implements QGraphicsItem.
Definition at line 2305 of file qgraphicswidget.cpp.
Referenced by _q_paintItem().
 {
     Q_UNUSED(painter);
     Q_UNUSED(option);
     Q_UNUSED(widget);
 }
paintWindowFrame()
void QGraphicsWidget::paintWindowFrame (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget = 0) virtual
This virtual function is called by QGraphicsScene to draw the window frame for windows using painter, option, and widget, in local coordinates.
The base implementation uses the current style to render the frame and title bar.
You can reimplement this function in a subclass of QGraphicsWidget to provide custom rendering of the widget's window frame.
See also
QGraphicsItem::paint()
Definition at line 2323 of file qgraphicswidget.cpp.
Referenced by _q_paintItem().
 {
     const bool fillBackground = !testAttribute(Qt::WA_OpaquePaintEvent)
                                 && !testAttribute(Qt::WA_NoSystemBackground);
     QGraphicsProxyWidget *proxy = qobject_cast<QGraphicsProxyWidget *>(this);
     const bool embeddedWidgetFillsOwnBackground = proxy && proxy->widget();
     if (rect().contains(option->exposedRect)) {
         if (fillBackground && !embeddedWidgetFillsOwnBackground)
             painter->fillRect(option->exposedRect, palette().window());
         return;
     }
     Q_D(QGraphicsWidget);
     QRect windowFrameRect = QRect(QPoint(), windowFrameGeometry().size().toSize());
     QStyleOptionTitleBar bar;
     bar.QStyleOption::operator=(*option);
     d->initStyleOptionTitleBar(&bar);   // this clear flags in bar.state
     d->ensureWindowData();
     if (d->windowData->buttonMouseOver)
         bar.state |= QStyle::State_MouseOver;
     else
         bar.state &= ~QStyle::State_MouseOver;
     if (d->windowData->buttonSunken)
         bar.state |= QStyle::State_Sunken;
     else
         bar.state &= ~QStyle::State_Sunken;
     bar.rect = windowFrameRect;
     // translate painter to make the style happy
     const QPointF styleOrigin = this->windowFrameRect().topLeft();
     painter->translate(styleOrigin);
 #ifdef Q_WS_MAC
     const QSize pixmapSize = windowFrameRect.size();
     if (pixmapSize.width() <= 0 || pixmapSize.height() <= 0)
         return;
     QPainter *realPainter = painter;
     QPixmap pm(pixmapSize);
     painter = new QPainter(&pm);
 #endif
     // Fill background
     QStyleHintReturnMask mask;
     bool setMask = style()->styleHint(QStyle::SH_WindowFrame_Mask, &bar, widget, &mask) && !mask.region.isEmpty();
     bool hasBorder = !style()->styleHint(QStyle::SH_TitleBar_NoBorder, &bar, widget);
     int frameWidth = style()->pixelMetric(QStyle::PM_MDIFrameWidth, &bar, widget);
     if (setMask) {
         painter->save();
         painter->setClipRegion(mask.region, Qt::IntersectClip);
     }
     if (fillBackground) {
         if (embeddedWidgetFillsOwnBackground) {
             // Don't fill the background twice.
             QPainterPath windowFrameBackground;
             windowFrameBackground.addRect(windowFrameRect);
             // Adjust with 0.5 to avoid border artifacts between
             // widget background and frame background.
             windowFrameBackground.addRect(rect().translated(-styleOrigin).adjusted(0.5, 0.5, -0.5, -0.5));
             painter->fillPath(windowFrameBackground, palette().window());
         } else {
             painter->fillRect(windowFrameRect, palette().window());
         }
     }
     painter->setRenderHint(QPainter::NonCosmeticDefaultPen);
     // Draw title
     int height = (int)d->titleBarHeight(bar);
     bar.rect.setHeight(height);
     if (hasBorder) // Frame is painted by PE_FrameWindow
         bar.rect.adjust(frameWidth, frameWidth, -frameWidth, 0);
     painter->save();
     painter->setFont(QApplication::font("QWorkspaceTitleBar"));
     style()->drawComplexControl(QStyle::CC_TitleBar, &bar, painter, widget);
     painter->restore();
     if (setMask)
         painter->restore();
     // Draw window frame
     QStyleOptionFrame frameOptions;
     frameOptions.QStyleOption::operator=(*option);
     initStyleOption(&frameOptions);
     if (!hasBorder)
         painter->setClipRect(windowFrameRect.adjusted(0, +height, 0, 0), Qt::IntersectClip);
     if (hasFocus()) {
         frameOptions.state |= QStyle::State_HasFocus;
     } else {
         frameOptions.state &= ~QStyle::State_HasFocus;
     }
     bool isActive = isActiveWindow();
     if (isActive) {
         frameOptions.state |= QStyle::State_Active;
     } else {
         frameOptions.state &= ~QStyle::State_Active;
     }
     frameOptions.palette.setCurrentColorGroup(isActive ? QPalette::Active : QPalette::Normal);
     frameOptions.rect = windowFrameRect;
     frameOptions.lineWidth = style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, widget);
     frameOptions.midLineWidth = 1;
     style()->drawPrimitive(QStyle::PE_FrameWindow, &frameOptions, painter, widget);
 #ifdef Q_WS_MAC
     realPainter->drawPixmap(QPoint(), pm);
     delete painter;
 #endif
 }
palette()
QPalette QGraphicsWidget::palette () const
Referenced by initStyleOption(), paintWindowFrame(), QWidgetPrivate::propagatePaletteChange(), and setFont().
polishEvent()
void QGraphicsWidget::polishEvent () protected virtual
This event is delivered to the item by the scene at some point after it has been constructed, but before it is shown or otherwise accessed through the scene.
You can use this event handler to do last-minute initializations of the widget which require the item to be fully constructed.
The base implementation does nothing.
Definition at line 1669 of file qgraphicswidget.cpp.
Referenced by event().
 {
 }
propertyChange()
QVariant QGraphicsWidget::propertyChange (const QString & propertyName, const QVariant & value) protected virtual
This virtual function is used to notify changes to any property (both dynamic properties, and registered with e.g., "size";, and value is the (proposed) new value of the property.
The function returns the new value, which may be different from value if the notification supports adjusting the property value. The base implementation simply returns value for any propertyName.
QGraphicsWidget delivers notifications for the following properties:
propertyName
Property
layoutDirection
QGraphicsWidget::layoutDirection
size
QGraphicsWidget::size
font
QGraphicsWidget::font
palette
QGraphicsWidget::palette
See also
itemChange()
Definition at line 1259 of file qgraphicswidget.cpp.
 {
     Q_UNUSED(propertyName);
     return value;
 }
rect()
QRectF QGraphicsWidget::rect () const inline
Returns the item's local rect as a QRectF.
This function is equivalent to QRectF(QPointF(), size()).
See also
setGeometry(), resize()
Definition at line 116 of file qgraphicswidget.h.
Referenced by QGraphicsProxyWidget::hoverMoveEvent(), initStyleOption(), QGraphicsItem::mousePressEvent(), QGraphicsProxyWidget::paint(), paintWindowFrame(), setGeometry(), shape(), and windowFrameRect().
 { return QRectF(QPointF(), size()); }
releaseShortcut()
void QGraphicsWidget::releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
Since
4.5
The widget will no longer receive QEvent::Shortcut events for the shortcut's key sequence (unless it has other shortcuts with the same key sequence).
Warning
You should not normally need to use this function since Qt's shortcut system removes shortcuts automatically when their parent widget is destroyed. It is best to use QAction or QShortcut to handle shortcuts, since they are easier to use than this low-level function. Note also that this is an expensive operation.
See also
grabShortcut() setShortcutEnabled() , QWidget::releaseShortcut()
Definition at line 1988 of file qgraphicswidget.cpp.
 {
     Q_ASSERT(qApp);
     if (id)
         qApp->d_func()->shortcutMap.removeShortcut(id, this, 0);
 }
removeAction()
void QGraphicsWidget::removeAction (QAction * action)
Removes the action action from this widget's list of actions.
Since
4.5
See also
insertAction(), actions(), insertAction(), QWidget::removeAction()
Definition at line 2150 of file qgraphicswidget.cpp.
Referenced by QAction::~QAction().
 {
     if (!action)
         return;
     Q_D(QGraphicsWidget);
     QActionPrivate *apriv = action->d_func();
     apriv->graphicsWidgets.removeAll(this);
     if (d->actions.removeAll(action)) {
         QActionEvent e(QEvent::ActionRemoved, action);
         QApplication::sendEvent(this, &e);
     }
 }
resize() [1/2]
void QGraphicsWidget::resize (const QSizeF & size)
Definition at line 314 of file qgraphicswidget.cpp.
Referenced by QDeclarativeLoaderPrivate::_q_updateSize(), adjustSize(), and updateGeometry().
 {
     setGeometry(QRectF(pos(), size));
 }
resize() [2/2]
void QGraphicsWidget::resize (qreal w, qreal h) inline
This convenience function is equivalent to calling resize(QSizeF(w, h)).
See also
setGeometry(), setTransform()
Definition at line 111 of file qgraphicswidget.h.
Referenced by resize().
 { resize(QSizeF(w, h)); }
resizeEvent()
void QGraphicsWidget::resizeEvent (QGraphicsSceneResizeEvent * event) protected virtual
This event handler, for GraphicsSceneResize events, is delivered after the widget has been resized (i.e., its local size has changed).
event contains both the old and the new size.
This event is only delivered when the widget is resized locally; calling setTransform() on the widget or any of its ancestors or view, does not affect the widget's local size.
You can reimplement this event handler to detect when your widget has been resized. Calling QEvent::accept() or QEvent::ignore() on event has no effect.
See also
geometry(), setGeometry()
Reimplemented in QGraphicsProxyWidget.
Definition at line 1689 of file qgraphicswidget.cpp.
Referenced by event(), and QGraphicsProxyWidget::resizeEvent().
 {
     Q_UNUSED(event);
 }
sceneEvent()
bool QGraphicsWidget::sceneEvent (QEvent * event) protected virtual
QGraphicsWidget's implementation of sceneEvent() simply passes event to QGraphicsWidget::event().
You can handle all events for your widget in event() or in any of the convenience functions; you should not have to reimplement this function in a subclass of QGraphicsWidget.
See also
QGraphicsItem::sceneEvent()
Reimplemented from QGraphicsItem.
Definition at line 1273 of file qgraphicswidget.cpp.
 {
     return QGraphicsItem::sceneEvent(event);
 }
setAttribute()
void QGraphicsWidget::setAttribute (Qt::WidgetAttribute attribute, bool on = true)
If on is true, this function enables attribute; otherwise attribute is disabled.
See the class documentation for QGraphicsWidget for a complete list of which attributes are supported, and what they are for.
See also
testAttribute(), QWidget::setAttribute()
Definition at line 2273 of file qgraphicswidget.cpp.
Referenced by itemChange(), setFont(), setGeometry(), setLayoutDirection(), setPalette(), setStyle(), unsetLayoutDirection(), and updateGeometry().
 {
     Q_D(QGraphicsWidget);
     // ### most flags require some immediate action
     // ### we might want to qWarn use of unsupported attributes
     // ### we might want to not use Qt::WidgetAttribute, but roll our own instead
     d->setAttribute(attribute, on);
 }
setAutoFillBackground()
void QGraphicsWidget::setAutoFillBackground (bool enabled)
Definition at line 1094 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     if (d->autoFillBackground != enabled) {
         d->autoFillBackground = enabled;
         update();
     }
 }
setContentsMargins()
void QGraphicsWidget::setContentsMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the widget's contents margins to left, top, right and bottom.
Contents margins are used by the assigned layout to define the placement of subwidgets and layouts. Margins are particularly useful for widgets that constrain subwidgets to only a section of its own geometry. For example, a group box with a layout will place subwidgets inside its frame, but below the title.
Changing a widget's contents margins will always trigger an update(), and any assigned layout will be activated automatically. The widget will then receive a ContentsRectChange event.
See also
getContentsMargins(), setGeometry()
Definition at line 512 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     if (!d->margins && left == 0 && top == 0 && right == 0 && bottom == 0)
         return;
     d->ensureMargins();
     if (left == d->margins[d->Left]
         && top == d->margins[d->Top]
         && right == d->margins[d->Right]
         && bottom == d->margins[d->Bottom])
         return;
     d->margins[d->Left] = left;
     d->margins[d->Top] = top;
     d->margins[d->Right] = right;
     d->margins[d->Bottom] = bottom;
     if (QGraphicsLayout *l = d->layout)
         l->invalidate();
     else
         updateGeometry();
     QEvent e(QEvent::ContentsRectChange);
     QApplication::sendEvent(this, &e);
 }
setFocusPolicy()
void QGraphicsWidget::setFocusPolicy (Qt::FocusPolicy policy)
Definition at line 1902 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     if (d->focusPolicy == policy)
         return;
     d->focusPolicy = policy;
     if (hasFocus() && policy == Qt::NoFocus)
         clearFocus();
     setFlag(ItemIsFocusable, policy != Qt::NoFocus);
 }
setFont()
void QGraphicsWidget::setFont (const QFont & font)
Definition at line 1017 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     setAttribute(Qt::WA_SetFont, font.resolve() != 0);
     QFont naturalFont = d->naturalWidgetFont();
     QFont resolvedFont = font.resolve(naturalFont);
     d->setFont_helper(resolvedFont);
 }
setGeometry() [1/2]
void QGraphicsWidget::setGeometry (const QRectF & rect) virtual
This virtual function sets the geometry of the QGraphicsLayoutItem to rect, which is in parent coordinates (e.
g., the top-left corner of rect is equivalent to the item's position in parent coordinates).
You must reimplement this function in a subclass of QGraphicsLayoutItem to receive geometry updates. The layout will call this function when it does a rearrangement.
If rect is outside of the bounds of minimumSize and maximumSize, it will be adjusted to its closest size so that it is within the legal bounds.
See also
geometry()
Reimplemented from QGraphicsLayoutItem.
Definition at line 365 of file qgraphicswidget.cpp.
Referenced by resize(), and QGraphicsProxyWidget::setGeometry().
 {
     QGraphicsWidgetPrivate *wd = QGraphicsWidget::d_func();
     QGraphicsLayoutItemPrivate *d = QGraphicsLayoutItem::d_ptr.data();
     QRectF newGeom = rect;
     QPointF oldPos = d->geom.topLeft();
     if (!wd->inSetPos) {
         setAttribute(Qt::WA_Resized);
         newGeom.setSize(rect.size().expandedTo(effectiveSizeHint(Qt::MinimumSize))
                                    .boundedTo(effectiveSizeHint(Qt::MaximumSize)));
         if (newGeom == d->geom) {
             goto relayoutChildrenAndReturn;
         }
         // setPos triggers ItemPositionChange, which can adjust position
         wd->inSetGeometry = 1;
         setPos(newGeom.topLeft());
         wd->inSetGeometry = 0;
         newGeom.moveTopLeft(pos());
         if (newGeom == d->geom) {
             goto relayoutChildrenAndReturn;
         }
          // Update and prepare to change the geometry (remove from index) if the size has changed.
         if (wd->scene) {
             if (rect.topLeft() == d->geom.topLeft()) {
                 prepareGeometryChange();
             }
         }
     }
     // Update the layout item geometry
     {
         bool moved = oldPos != pos();
         if (moved) {
             // Send move event.
             QGraphicsSceneMoveEvent event;
             event.setOldPos(oldPos);
             event.setNewPos(pos());
             QApplication::sendEvent(this, &event);
             if (wd->inSetPos) {
                 //set the new pos
                 d->geom.moveTopLeft(pos());
                 emit geometryChanged();
                 goto relayoutChildrenAndReturn;
             }
         }
         QSizeF oldSize = size();
         QGraphicsLayoutItem::setGeometry(newGeom);
         // Send resize event
         bool resized = newGeom.size() != oldSize;
         if (resized) {
             QGraphicsSceneResizeEvent re;
             re.setOldSize(oldSize);
             re.setNewSize(newGeom.size());
             if (oldSize.width() != newGeom.size().width())
                 emit widthChanged();
             if (oldSize.height() != newGeom.size().height())
                 emit heightChanged();
             QApplication::sendEvent(this, &re);
         }
     }
     emit geometryChanged();
 relayoutChildrenAndReturn:
     if (QGraphicsLayout::instantInvalidatePropagation()) {
         if (QGraphicsLayout *lay = wd->layout) {
             if (!lay->isActivated()) {
                 QEvent layoutRequest(QEvent::LayoutRequest);
                 QApplication::sendEvent(this, &layoutRequest);
             }
         }
     }
 }
setGeometry() [2/2]
void QGraphicsWidget::setGeometry (qreal x, qreal y, qreal w, qreal h) inline
This convenience function is equivalent to calling setGeometry(QRectF(x, y, w, h)).
See also
geometry(), resize()
Definition at line 249 of file qgraphicswidget.h.
 { setGeometry(QRectF(ax, ay, aw, ah)); }
setLayout()
void QGraphicsWidget::setLayout (QGraphicsLayout * layout)
Sets the layout for this widget to layout.
Any existing layout manager is deleted before the new layout is assigned. If layout is 0, the widget is left without a layout. Existing subwidgets' geometries will remain unaffected.
All widgets that are currently managed by layout or all of its sublayouts, are automatically reparented to this item. The layout is then invalidated, and the child widget geometries are adjusted according to this item's geometry() and contentsMargins(). Children who are not explicitly managed by layout remain unaffected by the layout after it has been assigned to this widget.
QGraphicsWidget takes ownership of layout.
See also
layout(), QGraphicsLinearLayout::addItem(), QGraphicsLayout::invalidate()
Definition at line 859 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     if (d->layout == l)
         return;
     d->setLayout_helper(l);
     if (!l)
         return;
     // Prevent assigning a layout that is already assigned to another widget.
     QGraphicsLayoutItem *oldParent = l->parentLayoutItem();
     if (oldParent && oldParent != this) {
         qWarning("QGraphicsWidget::setLayout: Attempting to set a layout on %s"
                  " \"%s\", when the layout already has a parent",
                  metaObject()->className(), qPrintable(objectName()));
         return;
     }
     // Install and activate the layout.
     l->setParentLayoutItem(this);
     l->d_func()->reparentChildItems(this);
     l->invalidate();
     emit layoutChanged();
 }
setLayoutDirection()
void QGraphicsWidget::setLayoutDirection (Qt::LayoutDirection direction)
Definition at line 933 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     setAttribute(Qt::WA_SetLayoutDirection, true);
     d->setLayoutDirection_helper(direction);
 }
setPalette()
void QGraphicsWidget::setPalette (const QPalette & palette)
Definition at line 1060 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     setAttribute(Qt::WA_SetPalette, palette.resolve() != 0);
     QPalette naturalPalette = d->naturalWidgetPalette();
     QPalette resolvedPalette = palette.resolve(naturalPalette);
     d->setPalette_helper(resolvedPalette);
 }
setShortcutAutoRepeat()
void QGraphicsWidget::setShortcutAutoRepeat (int id, bool enabled = true)
If enabled is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
Since
4.5
See also
grabShortcut() releaseShortcut() QWidget::setShortcutAutoRepeat()
Definition at line 2030 of file qgraphicswidget.cpp.
 {
     Q_ASSERT(qApp);
     if (id)
         qApp->d_func()->shortcutMap.setShortcutAutoRepeat(enabled, id, this, 0);
 }
setShortcutEnabled()
void QGraphicsWidget::setShortcutEnabled (int id, bool enabled = true)
If enabled is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
Since
4.5
Warning
You should not normally need to use this function since Qt's shortcut system enables/disables shortcuts automatically as widgets become hidden/visible and gain or lose focus. It is best to use QAction or QShortcut to handle shortcuts, since they are easier to use than this low-level function.
See also
grabShortcut() releaseShortcut(), QWidget::setShortcutEnabled()
Definition at line 2012 of file qgraphicswidget.cpp.
 {
     Q_ASSERT(qApp);
     if (id)
         qApp->d_func()->shortcutMap.setShortcutEnabled(enabled, id, this, 0);
 }
setStyle()
void QGraphicsWidget::setStyle (QStyle * style)
Sets the widget's style to style.
QGraphicsWidget does not take ownership of style.
If no style is assigned, or style is 0, the widget will use QGraphicsScene::style() (if this has been set). Otherwise the widget will use QApplication::style().
This function sets the Qt::WA_SetStyle attribute if style is not 0; otherwise it clears the attribute.
See also
style()
Definition at line 975 of file qgraphicswidget.cpp.
Referenced by QGraphicsProxyWidget::eventFilter().
 {
     setAttribute(Qt::WA_SetStyle, style != 0);
     widgetStyles()->setStyleForWidget(this, style);
     // Deliver StyleChange to the widget itself (doesn't propagate).
     QEvent event(QEvent::StyleChange);
     QApplication::sendEvent(this, &event);
 }
setTabOrder()
void QGraphicsWidget::setTabOrder (QGraphicsWidget * first, QGraphicsWidget * second) static
Moves the second widget around the ring of focus widgets so that keyboard focus moves from the first widget to the second widget when the Tab key is pressed.
Note that since the tab order of the second widget is changed, you should order a chain like this:
setTabOrder(a, b); // a to b
setTabOrder(b, c); // a to b to c
setTabOrder(c, d); // a to b to c to d
not like this:
// WRONG
setTabOrder(c, d); // c to d
setTabOrder(a, b); // a to b AND c to d
setTabOrder(b, c); // a to b to c, but not c to d
If first is 0, this indicates that second should be the first widget to receive input focus should the scene gain Tab focus (i.e., the user hits Tab so that focus passes into the scene). If second is 0, this indicates that first should be the first widget to gain focus if the scene gained BackTab focus.
By default, tab order is defined implicitly using widget creation order.
See also
focusPolicy, {Keyboard Focus}
Definition at line 2208 of file qgraphicswidget.cpp.
 {
     if (!first && !second) {
         qWarning("QGraphicsWidget::setTabOrder(0, 0) is undefined");
         return;
     }
     if ((first && second) && first->scene() != second->scene()) {
         qWarning("QGraphicsWidget::setTabOrder: scenes %p and %p are different",
                  first->scene(), second->scene());
         return;
     }
     QGraphicsScene *scene = first ? first->scene() : second->scene();
     if (!scene && (!first || !second)) {
         qWarning("QGraphicsWidget::setTabOrder: assigning tab order from/to the"
                  " scene requires the item to be in a scene.");
         return;
     }
     // If either first or second are 0, the scene's tabFocusFirst is updated
     // to point to the first item in the scene's focus chain. Then first or
     // second are set to point to tabFocusFirst.
     QGraphicsScenePrivate *sceneD = scene->d_func();
     if (!first) {
         sceneD->tabFocusFirst = second;
         return;
     }
     if (!second) {
         sceneD->tabFocusFirst = first->d_func()->focusNext;
         return;
     }
     // Both first and second are != 0.
     QGraphicsWidget *firstFocusNext = first->d_func()->focusNext;
     if (firstFocusNext == second) {
         // Nothing to do.
         return;
     }
     // Update the focus chain.
     QGraphicsWidget *secondFocusPrev = second->d_func()->focusPrev;
     QGraphicsWidget *secondFocusNext = second->d_func()->focusNext;
     firstFocusNext->d_func()->focusPrev = second;
     first->d_func()->focusNext = second;
     second->d_func()->focusNext = firstFocusNext;
     second->d_func()->focusPrev = first;
     secondFocusPrev->d_func()->focusNext = secondFocusNext;
     secondFocusNext->d_func()->focusPrev = secondFocusPrev;
     Q_ASSERT(first->d_func()->focusNext->d_func()->focusPrev == first);
     Q_ASSERT(first->d_func()->focusPrev->d_func()->focusNext == first);
     Q_ASSERT(second->d_func()->focusNext->d_func()->focusPrev == second);
     Q_ASSERT(second->d_func()->focusPrev->d_func()->focusNext == second);
 }
setWindowFlags()
void QGraphicsWidget::setWindowFlags (Qt::WindowFlags wFlags)
Definition at line 1806 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     if (d->windowFlags == wFlags)
         return;
     bool wasPopup = (d->windowFlags & Qt::WindowType_Mask) == Qt::Popup;
     d->adjustWindowFlags(&wFlags);
     d->windowFlags = wFlags;
     if (!d->setWindowFrameMargins)
         unsetWindowFrameMargins();
     setFlag(ItemIsPanel, d->windowFlags & Qt::Window);
     bool isPopup = (d->windowFlags & Qt::WindowType_Mask) == Qt::Popup;
     if (d->scene && isVisible() && wasPopup != isPopup) {
         // Popup state changed; update implicit mouse grab.
         if (!isPopup)
             d->scene->d_func()->removePopup(this);
         else
             d->scene->d_func()->addPopup(this);
     }
     if (d->scene && d->scene->d_func()->allItemsIgnoreHoverEvents && d->hasDecoration()) {
         d->scene->d_func()->allItemsIgnoreHoverEvents = false;
         d->scene->d_func()->enableMouseTrackingOnViews();
     }
 }
setWindowFrameMargins()
void QGraphicsWidget::setWindowFrameMargins (qreal left, qreal top, qreal right, qreal bottom)
Sets the widget's window frame margins to left, top, right and bottom.
The default frame margins are provided by the style, and they depend on the current window flags.
If you would like to draw your own window decoration, you can set your own frame margins to override the default margins.
See also
unsetWindowFrameMargins(), getWindowFrameMargins(), windowFrameRect()
Definition at line 571 of file qgraphicswidget.cpp.
Referenced by unsetWindowFrameMargins().
 {
     Q_D(QGraphicsWidget);
     if (!d->windowFrameMargins && left == 0 && top == 0 && right == 0 && bottom == 0)
         return;
     d->ensureWindowFrameMargins();
     bool unchanged =
         d->windowFrameMargins[d->Left] == left
         && d->windowFrameMargins[d->Top] == top
         && d->windowFrameMargins[d->Right] == right
         && d->windowFrameMargins[d->Bottom] == bottom;
     if (d->setWindowFrameMargins && unchanged)
         return;
     if (!unchanged)
         prepareGeometryChange();
     d->windowFrameMargins[d->Left] = left;
     d->windowFrameMargins[d->Top] = top;
     d->windowFrameMargins[d->Right] = right;
     d->windowFrameMargins[d->Bottom] = bottom;
     d->setWindowFrameMargins = true;
 }
setWindowTitle()
void QGraphicsWidget::setWindowTitle (const QString & title)
Definition at line 1862 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     d->ensureWindowData();
     d->windowData->windowTitle = title;
 }
shape()
QPainterPath QGraphicsWidget::shape () const virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 2445 of file qgraphicswidget.cpp.
 {
     QPainterPath path;
     path.addRect(rect());
     return path;
 }
showEvent()
void QGraphicsWidget::showEvent (QShowEvent * event) protected virtual
This event handler, for Show events, is delivered before the widget has been shown, for example, setVisible(true) has been called for the widget or one of its ancestors when the widget was previously hidden.
You can reimplement this event handler to detect when your widget is shown. Calling QEvent::accept() or QEvent::ignore() on event has no effect.
See also
hideEvent(), QWidget::showEvent(), ItemVisibleChange
Reimplemented in QGraphicsProxyWidget.
Definition at line 1706 of file qgraphicswidget.cpp.
Referenced by event().
 {
     Q_UNUSED(event);
 }
size()
QSizeF QGraphicsWidget::size () const
Referenced by paintWindowFrame(), setGeometry(), updateGeometry(), and ~QGraphicsWidget().
sizeHint()
QSizeF QGraphicsWidget::sizeHint (Qt::SizeHint which, const QSizeF & constraint = QSizeF()) const protected virtual
Reimplemented Function
Implements QGraphicsLayoutItem.
Definition at line 767 of file qgraphicswidget.cpp.
Referenced by QGraphicsProxyWidget::sizeHint().
 {
     Q_D(const QGraphicsWidget);
     QSizeF sh;
     if (d->layout) {
         QSizeF marginSize(0,0);
         if (d->margins) {
             marginSize = QSizeF(d->margins[d->Left] + d->margins[d->Right],
                          d->margins[d->Top] + d->margins[d->Bottom]);
         }
         sh = d->layout->effectiveSizeHint(which, constraint - marginSize);
         sh += marginSize;
     } else {
         switch (which) {
             case Qt::MinimumSize:
                 sh = QSizeF(0, 0);
                 break;
             case Qt::PreferredSize:
                 sh = QSizeF(50, 50);    //rather arbitrary
                 break;
             case Qt::MaximumSize:
                 sh = QSizeF(QWIDGETSIZE_MAX, QWIDGETSIZE_MAX);
                 break;
             default:
                 qWarning("QGraphicsWidget::sizeHint(): Don't know how to handle the value of 'which'");
                 break;
         }
     }
     return sh;
 }
style()
QStyle * QGraphicsWidget::style () const
Returns a pointer to the widget's style.
If this widget does not have any explicitly assigned style, the scene's style is returned instead. In turn, if the scene does not have any assigned style, this function returns QApplication::style().
See also
setStyle()
Definition at line 954 of file qgraphicswidget.cpp.
Referenced by QGraphicsProxyWidget::event(), paintWindowFrame(), QGraphicsWidgetStyles::setStyleForWidget(), QGraphicsAnchorLayoutPrivate::styleInfo(), and unsetWindowFrameMargins().
 {
     if (QStyle *style = widgetStyles()->styleForWidget(this))
         return style;
     // ### This is not thread-safe. QApplication::style() is not thread-safe.
     return scene() ? scene()->style() : QApplication::style();
 }
testAttribute()
bool QGraphicsWidget::testAttribute (Qt::WidgetAttribute attribute) const
Returns true if attribute is enabled for this widget; otherwise, returns false.
See also
setAttribute()
Definition at line 2288 of file qgraphicswidget.cpp.
Referenced by adjustSize(), close(), itemChange(), paintWindowFrame(), QGraphicsWidgetPrivate::setLayoutDirection_helper(), QGraphicsScene::setStyle(), QGraphicsWidgetPrivate::updateFont(), updateGeometry(), and QGraphicsWidgetPrivate::updatePalette().
 {
     Q_D(const QGraphicsWidget);
     return d->testAttribute(attribute);
 }
type()
int QGraphicsWidget::type () const virtual
Reimplemented Function
Reimplemented from QGraphicsItem.
Definition at line 2297 of file qgraphicswidget.cpp.
 {
     return Type;
 }
ungrabKeyboardEvent()
void QGraphicsWidget::ungrabKeyboardEvent (QEvent * event) protected virtual
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::UngrabKeyboard events.
See also
ungrabKeyboard(), ungrabMouse()
Definition at line 1766 of file qgraphicswidget.cpp.
Referenced by event().
 {
     Q_UNUSED(event);
 }
ungrabMouseEvent()
void QGraphicsWidget::ungrabMouseEvent (QEvent * event) protected virtual
This event handler, for event, can be reimplemented in a subclass to receive notifications for QEvent::UngrabMouse events.
See also
ungrabMouse(), ungrabKeyboard()
Reimplemented in QGraphicsProxyWidget.
Definition at line 1744 of file qgraphicswidget.cpp.
Referenced by event().
 {
     Q_UNUSED(event);
 }
unsetLayoutDirection()
void QGraphicsWidget::unsetLayoutDirection ()
Definition at line 939 of file qgraphicswidget.cpp.
 {
     Q_D(QGraphicsWidget);
     setAttribute(Qt::WA_SetLayoutDirection, false);
     d->resolveLayoutDirection();
 }
unsetWindowFrameMargins()
void QGraphicsWidget::unsetWindowFrameMargins ()
Resets the window frame margins to the default value, provided by the style.
See also
setWindowFrameMargins(), getWindowFrameMargins(), windowFrameRect()
Definition at line 621 of file qgraphicswidget.cpp.
Referenced by changeEvent(), and setWindowFlags().
 {
     Q_D(QGraphicsWidget);
     if ((d->windowFlags & Qt::Window) && (d->windowFlags & Qt::WindowType_Mask) != Qt::Popup &&
          (d->windowFlags & Qt::WindowType_Mask) != Qt::ToolTip && !(d->windowFlags & Qt::FramelessWindowHint)) {
         QStyleOptionTitleBar bar;
         d->initStyleOptionTitleBar(&bar);
         QStyle *style = this->style();
         qreal margin = style->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth);
         qreal titleBarHeight  = d->titleBarHeight(bar);
         setWindowFrameMargins(margin, titleBarHeight, margin, margin);
     } else {
         setWindowFrameMargins(0, 0, 0, 0);
     }
     d->setWindowFrameMargins = false;
 }
updateGeometry()
void QGraphicsWidget::updateGeometry () protected virtual
If this widget is currently managed by a layout, this function notifies the layout that the widget's size hints have changed and the layout may need to resize and reposition the widget accordingly.
Call this function if the widget's sizeHint() has changed.
See also
QGraphicsLayout::invalidate()
If this is the topmost widget, post a LayoutRequest event to the widget. When the event is received, it will start flowing all the way down to the leaf widgets in one go. This will make a relayout flicker-free.
Reimplemented from QGraphicsLayoutItem.
Definition at line 1112 of file qgraphicswidget.cpp.
Referenced by changeEvent(), QGraphicsProxyWidget::eventFilter(), and setContentsMargins().
 {
     QGraphicsLayoutItem::updateGeometry();
     QGraphicsLayoutItem *parentItem = parentLayoutItem();
     if (parentItem && parentItem->isLayout()) {
         if (QGraphicsLayout::instantInvalidatePropagation()) {
             static_cast<QGraphicsLayout *>(parentItem)->invalidate();
         } else {
             parentItem->updateGeometry();
         }
     } else {
         if (parentItem) {
             // This is for custom layouting
             QGraphicsWidget *parentWid = parentWidget();    //###
             if (parentWid->isVisible())
                 QApplication::postEvent(parentWid, new QEvent(QEvent::LayoutRequest));
         } else {
             if (QGraphicsLayout::instantInvalidatePropagation()) {
                 Q_D(QGraphicsWidget);
                 ++d->refCountInvokeRelayout;
                 QMetaObject::invokeMethod(this, "_q_relayout", Qt::QueuedConnection);
             }
         }
         if (!QGraphicsLayout::instantInvalidatePropagation()) {
             bool wasResized = testAttribute(Qt::WA_Resized);
             resize(size()); // this will restrict the size
             setAttribute(Qt::WA_Resized, wasResized);
         }
     }
 }
windowFlags()
Qt::WindowFlags QGraphicsWidget::windowFlags () const
Referenced by windowType().
windowFrameEvent()
bool QGraphicsWidget::windowFrameEvent (QEvent * event) protected virtual
This event handler, for event, receives events for the window frame if this widget is a window.
Its base implementation provides support for default window frame interaction such as moving, resizing, etc.
You can reimplement this handler in a subclass of QGraphicsWidget to provide your own custom window frame interaction support.
Returns true if event has been recognized and processed; otherwise, returns false.
See also
event()
Definition at line 1291 of file qgraphicswidget.cpp.
Referenced by event().
 {
     Q_D(QGraphicsWidget);
     switch (event->type()) {
     case QEvent::GraphicsSceneMousePress:
         d->windowFrameMousePressEvent(static_cast<QGraphicsSceneMouseEvent *>(event));
         break;
     case QEvent::GraphicsSceneMouseMove:
         d->ensureWindowData();
         if (d->windowData->grabbedSection != Qt::NoSection) {
             d->windowFrameMouseMoveEvent(static_cast<QGraphicsSceneMouseEvent *>(event));
             event->accept();
         }
         break;
     case QEvent::GraphicsSceneMouseRelease:
         d->windowFrameMouseReleaseEvent(static_cast<QGraphicsSceneMouseEvent *>(event));
         break;
     case QEvent::GraphicsSceneHoverMove:
         d->windowFrameHoverMoveEvent(static_cast<QGraphicsSceneHoverEvent *>(event));
         break;
     case QEvent::GraphicsSceneHoverLeave:
         d->windowFrameHoverLeaveEvent(static_cast<QGraphicsSceneHoverEvent *>(event));
         break;
     default:
         break;
     }
     return event->isAccepted();
 }
windowFrameGeometry()
QRectF QGraphicsWidget::windowFrameGeometry () const
Returns the widget's geometry in parent coordinates including any window frame.
See also
windowFrameRect(), getWindowFrameMargins(), setWindowFrameMargins()
Definition at line 644 of file qgraphicswidget.cpp.
Referenced by paintWindowFrame().
 {
     Q_D(const QGraphicsWidget);
     return d->windowFrameMargins
         ? geometry().adjusted(-d->windowFrameMargins[d->Left], -d->windowFrameMargins[d->Top],
                               d->windowFrameMargins[d->Right], d->windowFrameMargins[d->Bottom])
         : geometry();
 }
windowFrameRect()
QRectF QGraphicsWidget::windowFrameRect () const
Returns the widget's local rect including any window frame.
See also
windowFrameGeometry(), getWindowFrameMargins(), setWindowFrameMargins()
Definition at line 658 of file qgraphicswidget.cpp.
Referenced by boundingRect(), QGraphicsSceneIndexPrivate::itemCollidesWithPath(), paintWindowFrame(), and windowFrameSectionAt().
 {
     Q_D(const QGraphicsWidget);
     return d->windowFrameMargins
         ? rect().adjusted(-d->windowFrameMargins[d->Left], -d->windowFrameMargins[d->Top],
                           d->windowFrameMargins[d->Right], d->windowFrameMargins[d->Bottom])
         : rect();
 }
windowFrameSectionAt()
Qt::WindowFrameSection QGraphicsWidget::windowFrameSectionAt (const QPointF & pos) const protected virtual
Returns the window frame section at position pos, or Qt::NoSection if there is no window frame section at this position.
Since
4.4
This function is used in QGraphicsWidget's base implementation for window frame interaction.
You can reimplement this function if you want to customize how a window can be interactively moved or resized. For instance, if you only want to allow a window to be resized by the bottom right corner, you can reimplement this function to return Qt::NoSection for all sections except Qt::BottomRightSection.
See also
windowFrameEvent(), paintWindowFrame(), windowFrameGeometry()
Definition at line 1341 of file qgraphicswidget.cpp.
 {
     Q_D(const QGraphicsWidget);
     const QRectF r = windowFrameRect();
     if (!r.contains(pos))
         return Qt::NoSection;
     const qreal left = r.left();
     const qreal top = r.top();
     const qreal right = r.right();
     const qreal bottom = r.bottom();
     const qreal x = pos.x();
     const qreal y = pos.y();
     const qreal cornerMargin = 20;
     //### Not sure of this one, it should be the same value for all edges.
     const qreal windowFrameWidth = d->windowFrameMargins
         ? d->windowFrameMargins[d->Left] : 0;
     Qt::WindowFrameSection s = Qt::NoSection;
     if (x <= left + cornerMargin) {
         if (y <= top + windowFrameWidth || (x <= left + windowFrameWidth && y <= top + cornerMargin)) {
             s = Qt::TopLeftSection;
         } else if (y >= bottom - windowFrameWidth || (x <= left + windowFrameWidth && y >= bottom - windowFrameWidth)) {
             s = Qt::BottomLeftSection;
         } else if (x <= left + windowFrameWidth) {
             s = Qt::LeftSection;
         }
     } else if (x >= right - cornerMargin) {
         if (y <= top + windowFrameWidth || (x >= right - windowFrameWidth && y <= top + cornerMargin)) {
             s = Qt::TopRightSection;
         } else if (y >= bottom - windowFrameWidth || (x >= right - windowFrameWidth && y >= bottom - windowFrameWidth)) {
             s = Qt::BottomRightSection;
         } else if (x >= right - windowFrameWidth) {
             s = Qt::RightSection;
         }
     } else if (y <= top + windowFrameWidth) {
         s = Qt::TopSection;
     } else if (y >= bottom - windowFrameWidth) {
         s = Qt::BottomSection;
     }
     if (s == Qt::NoSection) {
         QRectF r1 = r;
         r1.setHeight(d->windowFrameMargins
                      ? d->windowFrameMargins[d->Top] : 0);
         if (r1.contains(pos))
             s = Qt::TitleBarArea;
     }
     return s;
 }
windowTitle()
QString QGraphicsWidget::windowTitle () const
Referenced by setWindowTitle().
windowType()
Qt::WindowType QGraphicsWidget::windowType () const
Returns the widgets window type.
See also
windowFlags(), isWindow(), isPanel()
Definition at line 1776 of file qgraphicswidget.cpp.
Referenced by _q_paintItem(), QShortcutMap::correctGraphicsWidgetContext(), and QGraphicsItemPrivate::setVisibleHelper().
 {
     return Qt::WindowType(int(windowFlags()) & Qt::WindowType_Mask);
 }
Friends and Related Functions
QApplication
friend class QApplication friend
Definition at line 246 of file qgraphicswidget.h.
QGraphicsItem
friend class QGraphicsItem friend
Definition at line 242 of file qgraphicswidget.h.
QGraphicsItemPrivate
friend class QGraphicsItemPrivate friend
Definition at line 243 of file qgraphicswidget.h.
QGraphicsLayout
friend class QGraphicsLayout friend
Definition at line 244 of file qgraphicswidget.h.
QGraphicsScene
friend class QGraphicsScene friend
Definition at line 239 of file qgraphicswidget.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 240 of file qgraphicswidget.h.
QGraphicsView
friend class QGraphicsView friend
Definition at line 241 of file qgraphicswidget.h.
QWidget
friend class QWidget friend
Definition at line 245 of file qgraphicswidget.h.
Properties
autoFillBackground
bool QGraphicsWidget::autoFillBackground private
whether the widget background is filled automatically
Since
4.7
If enabled, this property will cause Qt to fill the background of the widget before invoking the paint() method. The color used is defined by the QPalette::Window color role from the widget's palette.
In addition, Windows are always filled with QPalette::Window, unless the WA_OpaquePaintEvent or WA_NoSystemBackground attributes are set.
By default, this property is false.
See also
Qt::WA_OpaquePaintEvent, Qt::WA_NoSystemBackground,
Definition at line 85 of file qgraphicswidget.h.
Referenced by _q_paintItem().
focusPolicy
Qt::FocusPolicy QGraphicsWidget::focusPolicy private
the way the widget accepts keyboard focus
The focus policy is Qt::TabFocus if the widget accepts keyboard focus by tabbing, Qt::ClickFocus if the widget accepts focus by clicking, Qt::StrongFocus if it accepts both, and Qt::NoFocus (the default) if it does not accept focus at all.
You must enable keyboard focus for a widget if it processes keyboard events. This is normally done from the widget's constructor. For instance, the QLineEdit constructor calls setFocusPolicy(Qt::StrongFocus).
If you enable a focus policy (i.e., not Qt::NoFocus), QGraphicsWidget will automatically enable the ItemIsFocusable flag. Setting Qt::NoFocus on a widget will clear the ItemIsFocusable flag. If the widget currently has keyboard focus, the widget will automatically lose focus.
See also
focusInEvent(), focusOutEvent(), keyPressEvent(), keyReleaseEvent(), enabled
Definition at line 81 of file qgraphicswidget.h.
Referenced by QGraphicsScene::focusNextPrevChild().
font
QFont QGraphicsWidget::font private
the widgets' font
This property provides the widget's font.
QFont consists of font properties that have been explicitly defined and properties implicitly inherited from the widget's parent. Hence, font() can return a different font compared to the one set with setFont(). This scheme allows you to define single entries in a font without affecting the font's inherited entries.
When a widget's font changes, it resolves its entries against its parent widget. If the widget does not have a parent widget, it resolves its entries against the scene. The widget then sends itself a FontChange event and notifies all its descendants so that they can resolve their fonts as well.
By default, this property contains the application's default font.
See also
QApplication::font(), QGraphicsScene::font, QFont::resolve()
Definition at line 74 of file qgraphicswidget.h.
geometry
QGraphicsWidget::geometry private
the geometry of the widget
Sets the item's geometry to rect. The item's position and size are modified as a result of calling this function. The item is first moved, then resized.
A side effect of calling this function is that the widget will receive a move event and a resize event. Also, if the widget has a layout assigned, the layout will activate.
See also
geometry(), resize()
Definition at line 84 of file qgraphicswidget.h.
layout
QGraphicsLayout * QGraphicsWidget::layout private
The layout of the widget.
Returns this widget's layout, or 0 if no layout is currently managing this widget.
Any existing layout manager is deleted before the new layout is assigned. If layout is 0, the widget is left without a layout. Existing subwidgets' geometries will remain unaffected.
QGraphicsWidget takes ownership of layout.
All widgets that are currently managed by layout or all of its sublayouts, are automatically reparented to this item. The layout is then invalidated, and the child widget geometries are adjusted according to this item's geometry() and contentsMargins(). Children who are not explicitly managed by layout remain unaffected by the layout after it has been assigned to this widget.
If no layout is currently managing this widget, layout() will return 0.
See also
setLayout()
Definition at line 86 of file qgraphicswidget.h.
Referenced by QGraphicsLayoutItemPrivate::hasHeightForWidth(), and QGraphicsLayoutItemPrivate::hasWidthForHeight().
layoutDirection
Qt::LayoutDirection QGraphicsWidget::layoutDirection private
the layout direction for this widget.
This property modifies this widget's and all of its descendants' Qt::WA_RightToLeft attribute. It also sets this widget's Qt::WA_SetLayoutDirection attribute.
The widget's layout direction determines the order in which the layout manager horizontally arranges subwidgets of this widget. The default value depends on the language and locale of the application, and is typically in the same direction as words are read and written. With Qt::LeftToRight, the layout starts placing subwidgets from the left side of this widget towards the right. Qt::RightToLeft does the opposite - the layout will place widgets starting from the right edge moving towards the left.
Subwidgets inherit their layout direction from the parent. Top-level widget items inherit their layout direction from QGraphicsScene::layoutDirection. If you change a widget's layout direction by calling setLayoutDirection(), the widget will send itself a LayoutDirectionChange event, and then propagate the new layout direction to all its descendants.
See also
QWidget::layoutDirection, QApplication::layoutDirection
Definition at line 75 of file qgraphicswidget.h.
Referenced by _q_paintItem().
maximumSize
QGraphicsWidget::maximumSize private
the maximum size of the widget
See also
setMaximumSize(), maximumSize(), minimumSize, preferredSize
Definition at line 79 of file qgraphicswidget.h.
minimumSize
QGraphicsWidget::minimumSize private
the minimum size of the widget
See also
setMinimumSize(), minimumSize(), preferredSize, maximumSize
Definition at line 77 of file qgraphicswidget.h.
palette
QPalette QGraphicsWidget::palette private
the widget's palette
This property provides the widget's palette. The palette provides colors and brushes for color groups (e.g., QPalette::Button) and states (e.g., QPalette::Inactive), loosely defining the general look of the widget and its children.
QPalette consists of color groups that have been explicitly defined, and groups that are implicitly inherited from the widget's parent. Because of this, palette() can return a different palette than what has been set with setPalette(). This scheme allows you to define single entries in a palette without affecting the palette's inherited entries.
When a widget's palette changes, it resolves its entries against its parent widget, or if it doesn't have a parent widget, it resolves against the scene. It then sends itself a PaletteChange event, and notifies all its descendants so they can resolve their palettes as well.
By default, this property contains the application's default palette.
See also
QApplication::palette(), QGraphicsScene::palette, QPalette::resolve()
Definition at line 73 of file qgraphicswidget.h.
Referenced by _q_paintItem().
preferredSize
QGraphicsWidget::preferredSize private
the preferred size of the widget
See also
setPreferredSize(), preferredSize(), minimumSize, maximumSize
Definition at line 78 of file qgraphicswidget.h.
size
QSizeF QGraphicsWidget::size private
the size of the widget
Calling resize() resizes the widget to a size bounded by minimumSize() and maximumSize(). This property only affects the widget's width and height (e.g., its right and bottom edges); the widget's position and top-left corner remains unaffected.
Resizing a widget triggers the widget to immediately receive a GraphicsSceneResize event with the widget's old and new size. If the widget has a layout assigned when this event arrives, the layout will be activated and it will automatically update any child widgets's geometry.
This property does not affect any layout of the parent widget. If the widget itself is managed by a parent layout; e.g., it has a parent widget with a layout assigned, that layout will not activate.
By default, this property contains a size with zero width and height.
See also
setGeometry(), QGraphicsSceneResizeEvent, QGraphicsLayout
Definition at line 76 of file qgraphicswidget.h.
Referenced by _q_boundGeometryToSizeConstraints(), QDeclarativeLoaderPrivate::_q_updateSize(), and closestAcceptableSize().
sizePolicy
QGraphicsWidget::sizePolicy private
the size policy for the widget
See also
sizePolicy(), setSizePolicy(), QWidget::sizePolicy()
Definition at line 80 of file qgraphicswidget.h.
windowFlags
Qt::WindowFlags QGraphicsWidget::windowFlags private
the widget's window flags
Window flags are a combination of a window type (e.g., Qt::Dialog) and several flags giving hints on the behavior of the window. The behavior is platform-dependent.
By default, this property contains no window flags.
Windows are panels. If you set the Qt::Window flag, the ItemIsPanel flag will be set automatically. If you clear the Qt::Window flag, the ItemIsPanel flag is also cleared. Note that the ItemIsPanel flag can be set independently of Qt::Window.
See also
isWindow(), isPanel()
Definition at line 82 of file qgraphicswidget.h.
Referenced by _q_paintItem(), and QGraphicsItem::mousePressEvent().
windowTitle
QString QGraphicsWidget::windowTitle private
This property holds the window title (caption).
This property is only used for windows.
By default, if no title has been set, this property contains an empty string.
Definition at line 83 of file qgraphicswidget.h.
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicswidget.h
/src/gui/graphicsview/qgraphicswidget.cpp