Qt 4.8: QDeclarativeJS::Engine Class Reference
QDeclarativeJS::Engine Class Reference
#include <qdeclarativejsengine_p.h>
Public Functions
void addComment (int pos, int len, int line, int col)
QList< QDeclarativeJS::AST::SourceLocation > comments () const
Engine ()
NameId * intern (const QChar *u, int s)
Lexer * lexer () const
QSet< NameId > literals () const
NodePool * nodePool () const
void setLexer (Lexer *lexer)
void setNodePool (NodePool *nodePool)
~Engine ()
Static Public Functions
static QString toString (NameId *id)
Properties
QList< QDeclarativeJS::AST::SourceLocation > _comments
Lexer * _lexer
QSet< NameId > _literals
NodePool * _nodePool
Detailed Description
Definition at line 136 of file qdeclarativejsengine_p.h.
Constructors and Destructors
Engine()
QDeclarativeJS::Engine::Engine ()
Definition at line 174 of file qdeclarativejsengine_p.cpp.
     : _lexer(0), _nodePool(0)
 { }
~Engine()
QDeclarativeJS::Engine::~Engine ()
Definition at line 178 of file qdeclarativejsengine_p.cpp.
 { }
Functions
addComment()
void QDeclarativeJS::Engine::addComment (int pos, int len, int line, int col)
Definition at line 184 of file qdeclarativejsengine_p.cpp.
Referenced by QDeclarativeJS::Lexer::lex().
 { if (len > 0) _comments.append(QDeclarativeJS::AST::SourceLocation(pos, len, line, col)); }
comments()
QList< QDeclarativeJS::AST::SourceLocation > QDeclarativeJS::Engine::comments () const
Definition at line 187 of file qdeclarativejsengine_p.cpp.
 { return _comments; }
intern()
NameId * QDeclarativeJS::Engine::intern (const QChar * u, int s)
Definition at line 190 of file qdeclarativejsengine_p.cpp.
Referenced by QDeclarativeJS::Lexer::lex(), QDeclarativeJS::Parser::parse(), and QDeclarativeJS::Lexer::scanRegExp().
 { return const_cast<NameId *>(&*_literals.insert(NameId(u, s))); }
lexer()
Lexer * QDeclarativeJS::Engine::lexer () const
Definition at line 196 of file qdeclarativejsengine_p.cpp.
Referenced by automatic(), QDeclarativeJS::Parser::parse(), and setLexer().
 { return _lexer; }
literals()
QSet< NameId > QDeclarativeJS::Engine::literals () const
Definition at line 181 of file qdeclarativejsengine_p.cpp.
 { return _literals; }
nodePool()
NodePool * QDeclarativeJS::Engine::nodePool () const
Definition at line 202 of file qdeclarativejsengine_p.cpp.
Referenced by QDeclarativeJS::Parser::parse(), QDeclarativeJS::Parser::reparseAsQualifiedId(), and setNodePool().
 { return _nodePool; }
setLexer()
void QDeclarativeJS::Engine::setLexer (Lexer * lexer)
Definition at line 199 of file qdeclarativejsengine_p.cpp.
Referenced by QDeclarativeJS::Lexer::Lexer().
 { _lexer = lexer; }
setNodePool()
void QDeclarativeJS::Engine::setNodePool (NodePool * nodePool)
Definition at line 205 of file qdeclarativejsengine_p.cpp.
Referenced by QDeclarativeJS::NodePool::NodePool().
 { _nodePool = nodePool; }
toString()
QString QDeclarativeJS::Engine::toString (NameId * id) static
Definition at line 193 of file qdeclarativejsengine_p.cpp.
 { return id->asString(); }
Properties
_comments
QList<QDeclarativeJS::AST::SourceLocation> QDeclarativeJS::Engine::_comments private
Definition at line 141 of file qdeclarativejsengine_p.h.
Referenced by addComment(), and comments().
_lexer
Lexer* QDeclarativeJS::Engine::_lexer private
Definition at line 138 of file qdeclarativejsengine_p.h.
Referenced by lexer(), and setLexer().
_literals
QSet<NameId> QDeclarativeJS::Engine::_literals private
Definition at line 140 of file qdeclarativejsengine_p.h.
Referenced by intern(), and literals().
_nodePool
NodePool* QDeclarativeJS::Engine::_nodePool private
Definition at line 139 of file qdeclarativejsengine_p.h.
Referenced by nodePool(), and setNodePool().
The documentation for this class was generated from the following files:
/src/declarative/qml/parser/qdeclarativejsengine_p.h
/src/declarative/qml/parser/qdeclarativejsengine_p.cpp