Qt 4.8: Maemo::DBusDispatcher Class Reference
Maemo::DBusDispatcher Class Reference
DBusDispatcher is a class that can send DBUS method call messages and receive unicast signals from DBUS objects.
#include <dbusdispatcher.h>
Signals
void callReply (const QString &method, const QList< QVariant > &args, const QString &error)
void signalReceived (const QString &interface, const QString &signal, const QList< QVariant > &args)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QList< QVariant > call (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
bool callAsynchronous (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
DBusDispatcher (const QString &service, const QString &path, const QString &interface, QObject *parent=0)
DBusDispatcher (const QString &service, const QString &path, const QString &interface, const QString &signalPath, QObject *parent=0)
void emitCallReply (const QString &method, const QList< QVariant > &args, const QString &error="")
void emitSignalReceived (const QString &interface, const QString &signal, const QList< QVariant > &args)
void synchronousDispatch (int timeout_ms)
~DBusDispatcher ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void setupDBus ()
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
DBusDispatcherPrivate * d_ptr
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
DBusDispatcher is a class that can send DBUS method call messages and receive unicast signals from DBUS objects.
Definition at line 52 of file dbusdispatcher.h.
Constructors and Destructors
DBusDispatcher() [1/2]
Maemo::DBusDispatcher::DBusDispatcher (const QString & service, const QString & path, const QString & interface, QObject * parent = 0)
Definition at line 439 of file dbusdispatcher.cpp.
  : QObject(parent),
    d_ptr(new DBusDispatcherPrivate(service, path, interface, path)) {
     setupDBus();
 }
DBusDispatcher() [2/2]
Maemo::DBusDispatcher::DBusDispatcher (const QString & service, const QString & path, const QString & interface, const QString & signalPath, QObject * parent = 0)
Definition at line 448 of file dbusdispatcher.cpp.
  : QObject(parent),
    d_ptr(new DBusDispatcherPrivate(service, path, interface, signalPath)) {
     setupDBus();
 }
~DBusDispatcher()
Maemo::DBusDispatcher::~DBusDispatcher ()
Definition at line 458 of file dbusdispatcher.cpp.
 {
     if (d_ptr->connection) {
         dbus_connection_close(d_ptr->connection);
         dbus_connection_unref(d_ptr->connection);
     }
     delete d_ptr;
 }
Functions
call()
QList< QVariant > Maemo::DBusDispatcher::call (const QString & method, const QVariant & arg1 = QVariant(), const QVariant & arg2 = QVariant(), const QVariant & arg3 = QVariant(), const QVariant & arg4 = QVariant(), const QVariant & arg5 = QVariant(), const QVariant & arg6 = QVariant(), const QVariant & arg7 = QVariant(), const QVariant & arg8 = QVariant())
Definition at line 525 of file dbusdispatcher.cpp.
Referenced by Maemo::IcdPrivate::addrinfo(), callAsynchronous(), Maemo::IcdPrivate::scan(), Maemo::IcdPrivate::state(), and Maemo::IcdPrivate::statistics().
{
     DBusMessageIter dbus_iter;
     DBusMessage *message = prepareDBusCall(d_ptr->service, d_ptr->path,
                                            d_ptr->interface, method,
                                            arg1, arg2, arg3, arg4, arg5,
                                            arg6, arg7, arg8);
     DBusMessage *reply = dbus_connection_send_with_reply_and_block(
                                                     d_ptr->connection,
                                                     message, -1, NULL);
     dbus_message_unref(message);
     QList<QVariant> replylist;
     if (reply != NULL &&  dbus_message_iter_init(reply, &dbus_iter)) {
         // Read return arguments
         while (dbus_message_iter_get_arg_type (&dbus_iter) != DBUS_TYPE_INVALID) {
             replylist << getVariantFromDBusMessage(&dbus_iter);
             dbus_message_iter_next(&dbus_iter);
         }
     }
     if (reply != NULL) dbus_message_unref(reply);
     return replylist;
 }
callAsynchronous()
bool Maemo::DBusDispatcher::callAsynchronous (const QString & method, const QVariant & arg1 = QVariant(), const QVariant & arg2 = QVariant(), const QVariant & arg3 = QVariant(), const QVariant & arg4 = QVariant(), const QVariant & arg5 = QVariant(), const QVariant & arg6 = QVariant(), const QVariant & arg7 = QVariant(), const QVariant & arg8 = QVariant())
Definition at line 595 of file dbusdispatcher.cpp.
{
     DBusMessage *message = prepareDBusCall(d_ptr->service, d_ptr->path,
                                            d_ptr->interface, method,
                                            arg1, arg2, arg3, arg4, arg5,
                                            arg6, arg7, arg8);
     DBusPendingCall *call = NULL;
     dbus_bool_t ret = dbus_connection_send_with_reply(d_ptr->connection,
                                                       message, &call, -1);
     PendingCallInfo *info = new PendingCallInfo;
     info->method = method;
     info->dispatcher = this;
     info->priv = d_ptr;
     dbus_pending_call_set_notify(call, pendingCallFunction, info, freePendingCallInfo);
     d_ptr->pending_calls.append(call);
     return (bool)ret;
 }
callReply
void Maemo::DBusDispatcher::callReply (const QString & method, const QList< QVariant > & args, const QString & error) signal
Referenced by emitCallReply().
emitCallReply()
void Maemo::DBusDispatcher::emitCallReply (const QString & method, const QList< QVariant > & args, const QString & error = "")
Definition at line 626 of file dbusdispatcher.cpp.
Referenced by Maemo::pendingCallFunction().
{
     emit callReply(method, args, error); }
emitSignalReceived()
void Maemo::DBusDispatcher::emitSignalReceived (const QString & interface, const QString & signal, const QList< QVariant > & args)
Definition at line 621 of file dbusdispatcher.cpp.
{
     emit signalReceived(interface, signal, args); }
setupDBus()
void Maemo::DBusDispatcher::setupDBus () protected
Definition at line 467 of file dbusdispatcher.cpp.
Referenced by DBusDispatcher().
 {
     d_ptr->connection = dbus_bus_get_private(DBUS_BUS_SYSTEM, NULL);
     if (d_ptr->connection == NULL)
         qDebug() << "Unable to get DBUS connection!";
     else {
         d_ptr->signal_vtable.message_function = signalHandler;
     dbus_connection_set_exit_on_disconnect(d_ptr->connection, FALSE);
         dbus_connection_setup_with_g_main(d_ptr->connection, g_main_context_get_thread_default());
         dbus_connection_register_object_path(d_ptr->connection,
                                              d_ptr->signalPath.toLatin1(),
                                              &d_ptr->signal_vtable,
                                              this);
     }
 }
signalReceived
void Maemo::DBusDispatcher::signalReceived (const QString & interface, const QString & signal, const QList< QVariant > & args) signal
Referenced by emitSignalReceived().
synchronousDispatch()
void Maemo::DBusDispatcher::synchronousDispatch (int timeout_ms)
Definition at line 631 of file dbusdispatcher.cpp.
Referenced by Maemo::IcdPrivate::addrinfo(), and Maemo::IcdPrivate::state().
 {
     dbus_connection_read_write_dispatch(d_ptr->connection, timeout_ms);
 }
Properties
d_ptr
DBusDispatcherPrivate* Maemo::DBusDispatcher::d_ptr private
Definition at line 106 of file dbusdispatcher.h.
Referenced by call(), callAsynchronous(), setupDBus(), synchronousDispatch(), and ~DBusDispatcher().
The documentation for this class was generated from the following files:
/src/plugins/bearer/icd/dbusdispatcher.h
/src/plugins/bearer/icd/dbusdispatcher.cpp