Qt 4.8: QDeclarativeAbstractBinding Class Reference
QDeclarativeAbstractBinding Class Reference abstract
#include <qdeclarativebinding_p.h>
Public Types
enum DestroyMode { DisconnectBinding, KeepBindingConnected }
enum DisconnectMode { DisconnectOne, DisconnectAll }
typedef QWeakPointer< QDeclarativeAbstractBinding > Pointer
enum Type { PropertyBinding, ValueTypeProxy }
Public Functions
void addToObject (QObject *, int)
Add this binding to object.
virtual Type bindingType () const
virtual void destroy (DestroyMode mode=DisconnectBinding)
Destroy the binding.
virtual void disconnect (DisconnectMode disconnectMode)=0
virtual QString expression () const
QObject * object () const
int propertyIndex () const
QDeclarativeAbstractBinding ()
void removeFromObject ()
Remove the binding from the object.
void setEnabled (bool e)
virtual void setEnabled (bool, QDeclarativePropertyPrivate::WriteFlags)=0
void update ()
virtual void update (QDeclarativePropertyPrivate::WriteFlags)=0
Static Public Functions
static Pointer getPointer (QDeclarativeAbstractBinding *p)
Protected Functions
void clear ()
virtual ~QDeclarativeAbstractBinding ()
Private Functions
Pointer weakPointer ()
Properties
QDeclarativeAbstractBinding ** m_mePtr
QDeclarativeAbstractBinding * m_nextBinding
QObject * m_object
QDeclarativeAbstractBinding ** m_prevBinding
int m_propertyIndex
QSharedPointer< QDeclarativeAbstractBinding > m_selfPointer
Friends
class QDeclarativeComponentPrivate
class QDeclarativeData
class QDeclarativePropertyPrivate
class QDeclarativeValueTypeProxyBinding
class QDeclarativeVME
class QtSharedPointer::ExternalRefCount< QDeclarativeAbstractBinding >
Detailed Description
Definition at line 67 of file qdeclarativebinding_p.h.
Typedefs
Pointer
typedef QWeakPointer<QDeclarativeAbstractBinding> QDeclarativeAbstractBinding::Pointer
Definition at line 70 of file qdeclarativebinding_p.h.
Enumerations
DestroyMode
enum QDeclarativeAbstractBinding::DestroyMode
Enumerator
DisconnectBinding
KeepBindingConnected
Definition at line 74 of file qdeclarativebinding_p.h.
                      {
         // The binding should disconnect itself upon destroy
         DisconnectBinding,
         // The binding doesn't need to disconnect itself, but it can if it wants to.
         //
         // This is used in QDeclarativeData::destroyed() - at the point at which the bindings are
         // destroyed, the notifiers are already disconnected, so no need to disconnect each
         // binding again.
         //
         // Bindings can use this flag to speed up destruction, especially for compiled bindings
         // disconnecting a single binding might be slow.
         KeepBindingConnected
     };
DisconnectMode
enum QDeclarativeAbstractBinding::DisconnectMode
Enumerator
DisconnectOne
DisconnectAll
Definition at line 93 of file qdeclarativebinding_p.h.
{
         // Just this single binding is getting disconnected, other bindings remain connected and
         // should not be changed.
         DisconnectOne,
         // All bindings of the same object are getting disconnected. As an optimization, it is
         // therefore valid to disconnect all bindings in one go.
         DisconnectAll
     };
Type
enum QDeclarativeAbstractBinding::Type
Enumerator
PropertyBinding
ValueTypeProxy
Definition at line 107 of file qdeclarativebinding_p.h.
 { PropertyBinding, ValueTypeProxy };
Constructors and Destructors
QDeclarativeAbstractBinding()
QDeclarativeAbstractBinding::QDeclarativeAbstractBinding ()
Definition at line 60 of file qdeclarativebinding.cpp.
 : m_object(0), m_propertyIndex(-1), m_mePtr(0), m_prevBinding(0), m_nextBinding(0)
 {
 }
~QDeclarativeAbstractBinding()
QDeclarativeAbstractBinding::~QDeclarativeAbstractBinding () protected virtual
Definition at line 65 of file qdeclarativebinding.cpp.
 {
     Q_ASSERT(m_prevBinding == 0);
     Q_ASSERT(m_mePtr == 0);
 }
Functions
addToObject()
void QDeclarativeAbstractBinding::addToObject (QObject * object, int index)
Add this binding to object.
This transfers ownership of the binding to the object, marks the object's property as being bound.
However, it does not enable the binding itself or call update() on it.
Definition at line 97 of file qdeclarativebinding.cpp.
Referenced by addToObject(), QDeclarativePropertyPrivate::setBinding(), and QDeclarativePropertyPrivate::setBindingNoEnable().
 {
     Q_ASSERT(object);
     if (m_object == object && m_propertyIndex == index)
         return;
     removeFromObject();
     Q_ASSERT(!m_prevBinding);
     m_object = object;
     m_propertyIndex = index;
     QDeclarativeData *data = QDeclarativeData::get(object, true);
     if (index & 0xFF000000) {
         // Value type
         int coreIndex = index & 0xFFFFFF;
         // Find the value type proxy (if there is one)
         QDeclarativeValueTypeProxyBinding *proxy = 0;
         if (data->hasBindingBit(coreIndex)) {
             QDeclarativeAbstractBinding *b = data->bindings;
             while (b && b->propertyIndex() != coreIndex)
                 b = b->m_nextBinding;
             Q_ASSERT(b && b->bindingType() == QDeclarativeAbstractBinding::ValueTypeProxy);
             proxy = static_cast<QDeclarativeValueTypeProxyBinding *>(b);
         }
         if (!proxy) {
             proxy = new QDeclarativeValueTypeProxyBinding(object, coreIndex);
             proxy->addToObject(object, coreIndex);
         }
         m_nextBinding = proxy->m_bindings;
         if (m_nextBinding) m_nextBinding->m_prevBinding = &m_nextBinding;
         m_prevBinding = &proxy->m_bindings;
         proxy->m_bindings = this;
     } else {
         m_nextBinding = data->bindings;
         if (m_nextBinding) m_nextBinding->m_prevBinding = &m_nextBinding;
         m_prevBinding = &data->bindings;
         data->bindings = this;
         data->setBindingBit(m_object, index);
     }
 }
bindingType()
virtual Type QDeclarativeAbstractBinding::bindingType () const inline virtual
Reimplemented in QDeclarativeValueTypeProxyBinding.
Definition at line 108 of file qdeclarativebinding_p.h.
Referenced by addToObject(), QDeclarativePropertyPrivate::binding(), QDeclarativePropertyPrivate::setBinding(), and QDeclarativePropertyPrivate::setBindingNoEnable().
 { return PropertyBinding; }
clear()
void QDeclarativeAbstractBinding::clear () protected
Definition at line 187 of file qdeclarativebinding.cpp.
Referenced by destroy().
 {
     if (m_mePtr) {
         *m_mePtr = 0;
         m_mePtr = 0;
     }
 }
destroy()
void QDeclarativeAbstractBinding::destroy (DestroyMode mode = DisconnectBinding) virtual
Destroy the binding.
Use this instead of calling delete.
Bindings are free to implement their own memory management, so the delete operator is not necessarily safe. The default implementation clears the binding, removes it from the object and calls delete.
Reimplemented in QDeclarativeCompiledBindingsPrivate::Binding.
Definition at line 78 of file qdeclarativebinding.cpp.
Referenced by QDeclarativeState::apply(), QDeclarativeTransitionManager::cancel(), QDeclarativeState::changeBindingInRevertList(), QDeclarativePropertyChanges::changeExpression(), QDeclarativePropertyChanges::changeValue(), QDeclarativeData::destroyed(), QDeclarativeAnchorChanges::execute(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeState::removeAllEntriesFromRevertList(), removeBindingOnProperty(), QDeclarativeValueTypeProxyBinding::removeBindings(), QDeclarativeState::removeEntryFromRevertList(), QDeclarativeEngineDebugService::resetBinding(), QDeclarativeEngineDebugService::setBinding(), QDeclarativePropertyPrivate::setBinding(), QDeclarativePropertyPrivate::setBindingNoEnable(), QDeclarativeValueTypeScriptClass::setProperty(), QDeclarativeObjectScriptClass::setProperty(), QDeclarativePropertyPrivate::writeValueProperty(), and QDeclarativeValueTypeProxyBinding::~QDeclarativeValueTypeProxyBinding().
 {
     if (mode == DisconnectBinding)
         disconnect(QDeclarativeAbstractBinding::DisconnectOne);
     removeFromObject();
     clear();
     delete this;
 }
disconnect()
virtual void QDeclarativeAbstractBinding::disconnect (DisconnectMode disconnectMode) pure virtual
Implemented in QDeclarativeCompiledBindingsPrivate::Binding, QDeclarativeBinding, and QDeclarativeValueTypeProxyBinding.
Referenced by destroy(), and QDeclarativeData::disconnectNotifiers().
expression()
QString QDeclarativeAbstractBinding::expression () const virtual
Reimplemented in QDeclarativeBinding.
Definition at line 195 of file qdeclarativebinding.cpp.
Referenced by QDeclarativeEngineDebugService::propertyData().
 {
     return QLatin1String("<Unknown>");
 }
getPointer()
static Pointer QDeclarativeAbstractBinding::getPointer (QDeclarativeAbstractBinding * p) inline static
Definition at line 122 of file qdeclarativebinding_p.h.
Referenced by QDeclarativeState::apply(), QDeclarativeSimpleAction::operator=(), QDeclarativeSimpleAction::QDeclarativeSimpleAction(), and QDeclarativeSimpleAction::setBinding().
 { return p ? p->weakPointer() : Pointer(); }
object()
QObject * QDeclarativeAbstractBinding::object () const
Definition at line 200 of file qdeclarativebinding.cpp.
Referenced by addToObject().
 {
     return m_object;
 }
propertyIndex()
int QDeclarativeAbstractBinding::propertyIndex () const
Definition at line 205 of file qdeclarativebinding.cpp.
Referenced by addToObject(), QDeclarativePropertyPrivate::binding(), QDeclarativeValueTypeProxyBinding::binding(), QDeclarativeValueTypeProxyBinding::removeBindings(), removeFromObject(), QDeclarativePropertyPrivate::setBinding(), and QDeclarativePropertyPrivate::setBindingNoEnable().
 {
     return m_propertyIndex;
 }
removeFromObject()
void QDeclarativeAbstractBinding::removeFromObject ()
Remove the binding from the object.
Definition at line 151 of file qdeclarativebinding.cpp.
Referenced by addToObject(), destroy(), QDeclarativePropertyPrivate::setBinding(), and QDeclarativePropertyPrivate::setBindingNoEnable().
 {
     if (m_prevBinding) {
         int index = propertyIndex();
         *m_prevBinding = m_nextBinding;
         if (m_nextBinding) m_nextBinding->m_prevBinding = m_prevBinding;
         m_prevBinding = 0;
         m_nextBinding = 0;
         if (index & 0xFF000000) {
             // Value type - we don't remove the proxy from the object.  It will sit their happily
             // doing nothing until it is removed by a write, a binding change or it is reused
             // to hold more sub-bindings.
         } else if (m_object) {
             QDeclarativeData *data = QDeclarativeData::get(m_object, false);
             if (data) data->clearBindingBit(index);
         }
         m_object = 0;
         m_propertyIndex = -1;
     }
 }
setEnabled() [1/2]
void QDeclarativeAbstractBinding::setEnabled (bool e) inline
Definition at line 113 of file qdeclarativebinding_p.h.
Referenced by QDeclarativePropertyChanges::changeExpression(), QDeclarativePropertyChanges::changeValue(), QDeclarativeComponentPrivate::complete(), QDeclarativeValueTypeProxyBinding::recursiveDisable(), QDeclarativeValueTypeProxyBinding::recursiveEnable(), QDeclarativePropertyPrivate::setBinding(), setEnabled(), and QDeclarativeValueTypeProxyBinding::~QDeclarativeValueTypeProxyBinding().
 { setEnabled(e, QDeclarativePropertyPrivate::DontRemoveBinding); }
setEnabled() [2/2]
void QDeclarativeAbstractBinding::setEnabled (bool enabled, QDeclarativePropertyPrivate::WriteFlags flags) pure virtual
Implemented in QDeclarativeCompiledBindingsPrivate::Binding, QDeclarativeBinding, and QDeclarativeValueTypeProxyBinding.
Definition at line 210 of file qdeclarativebinding.cpp.
 {
     if (enabled) update(flags);
 }
update() [1/2]
void QDeclarativeAbstractBinding::update () inline
Definition at line 116 of file qdeclarativebinding_p.h.
Referenced by setEnabled(), and update().
 { update(QDeclarativePropertyPrivate::DontRemoveBinding); }
update() [2/2]
virtual void QDeclarativeAbstractBinding::update (QDeclarativePropertyPrivate::WriteFlags) pure virtual
Implemented in QDeclarativeCompiledBindingsPrivate::Binding, QDeclarativeBinding, and QDeclarativeValueTypeProxyBinding.
weakPointer()
QDeclarativeAbstractBinding::Pointer QDeclarativeAbstractBinding::weakPointer () private
Definition at line 179 of file qdeclarativebinding.cpp.
Referenced by getPointer().
 {
     if (m_selfPointer.isNull())
         m_selfPointer = QSharedPointer<QDeclarativeAbstractBinding>(this, bindingDummyDeleter);
     return m_selfPointer.toWeakRef();
 }
Friends and Related Functions
QDeclarativeComponentPrivate
friend class QDeclarativeComponentPrivate friend
Definition at line 132 of file qdeclarativebinding_p.h.
QDeclarativeData
friend class QDeclarativeData friend
Definition at line 131 of file qdeclarativebinding_p.h.
QDeclarativePropertyPrivate
friend class QDeclarativePropertyPrivate friend
Definition at line 134 of file qdeclarativebinding_p.h.
QDeclarativeValueTypeProxyBinding
friend class QDeclarativeValueTypeProxyBinding friend
Definition at line 133 of file qdeclarativebinding_p.h.
Referenced by addToObject().
QDeclarativeVME
friend class QDeclarativeVME friend
Definition at line 135 of file qdeclarativebinding_p.h.
QtSharedPointer::ExternalRefCount< QDeclarativeAbstractBinding >
friend class QtSharedPointer::ExternalRefCount< QDeclarativeAbstractBinding > friend
Definition at line 136 of file qdeclarativebinding_p.h.
Properties
m_mePtr
QDeclarativeAbstractBinding** QDeclarativeAbstractBinding::m_mePtr private
Definition at line 140 of file qdeclarativebinding_p.h.
Referenced by clear(), QDeclarativeComponentPrivate::complete(), and ~QDeclarativeAbstractBinding().
m_nextBinding
QDeclarativeAbstractBinding* QDeclarativeAbstractBinding::m_nextBinding private
Definition at line 142 of file qdeclarativebinding_p.h.
Referenced by addToObject(), QDeclarativePropertyPrivate::binding(), QDeclarativeValueTypeProxyBinding::binding(), QDeclarativeData::destroyed(), QDeclarativeData::disconnectNotifiers(), QDeclarativeValueTypeProxyBinding::recursiveDisable(), QDeclarativeValueTypeProxyBinding::recursiveEnable(), QDeclarativeValueTypeProxyBinding::removeBindings(), removeFromObject(), QDeclarativePropertyPrivate::setBinding(), and QDeclarativePropertyPrivate::setBindingNoEnable().
m_object
QObject* QDeclarativeAbstractBinding::m_object private
Definition at line 138 of file qdeclarativebinding_p.h.
Referenced by addToObject(), object(), and removeFromObject().
m_prevBinding
QDeclarativeAbstractBinding** QDeclarativeAbstractBinding::m_prevBinding private
Definition at line 141 of file qdeclarativebinding_p.h.
Referenced by addToObject(), QDeclarativeData::destroyed(), QDeclarativeValueTypeProxyBinding::removeBindings(), removeFromObject(), and ~QDeclarativeAbstractBinding().
m_propertyIndex
int QDeclarativeAbstractBinding::m_propertyIndex private
Definition at line 139 of file qdeclarativebinding_p.h.
Referenced by addToObject(), propertyIndex(), and removeFromObject().
m_selfPointer
QSharedPointer<QDeclarativeAbstractBinding> QDeclarativeAbstractBinding::m_selfPointer private
Definition at line 143 of file qdeclarativebinding_p.h.
Referenced by weakPointer().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativebinding_p.h
/src/declarative/qml/qdeclarativebinding.cpp