Qt 4.8: QTestLog Class Reference
QTestLog Class Reference
#include <qtestlog_p.h>
Public Types
enum FlushMode { NoFlush = 0, FLushOn }
enum LogMode { Plain = 0, XML, LightXML, XunitXML }
Static Public Functions
static void addBenchmarkResult (const QBenchmarkResult &result)
static void addFail (const char *msg, const char *file, int line)
static void addIgnoreMessage (QtMsgType type, const char *msg)
static void addPass (const char *msg)
static void addSkip (const char *msg, QTest::SkipMode mode, const char *file, int line)
static void addXFail (const char *msg, const char *file, int line)
static void addXPass (const char *msg, const char *file, int line)
static void enterTestFunction (const char *function)
static void info (const char *msg, const char *file, int line)
static void leaveTestFunction ()
static LogMode logMode ()
static const char * outputFileName ()
static void printUnhandledIgnoreMessages ()
static void redirectOutput (const char *fileName)
static void setFlushMode (FlushMode mode)
static void setLogMode (LogMode mode)
static void setMaxWarnings (int max)
static void setVerboseLevel (int level)
static void startLogging ()
static void startLogging (unsigned int randomSeed)
static void stopLogging ()
static int unhandledIgnoreMessages ()
static int verboseLevel ()
static void warn (const char *msg)
Private Functions
QTestLog ()
~QTestLog ()
Detailed Description
Definition at line 62 of file qtestlog_p.h.
Enumerations
FlushMode
enum QTestLog::FlushMode
Enumerator
NoFlush
FLushOn
Definition at line 66 of file qtestlog_p.h.
 { NoFlush = 0, FLushOn };
LogMode
enum QTestLog::LogMode
Enumerator
Plain
XML
LightXML
XunitXML
Definition at line 65 of file qtestlog_p.h.
 { Plain = 0, XML, LightXML, XunitXML };
Constructors and Destructors
QTestLog()
QTestLog::QTestLog () private
Definition at line 198 of file qtestlog.cpp.
 {
 }
~QTestLog()
QTestLog::~QTestLog () private
Definition at line 202 of file qtestlog.cpp.
 {
 }
Functions
addBenchmarkResult()
void QTestLog::addBenchmarkResult (const QBenchmarkResult & result) static
Definition at line 299 of file qtestlog.cpp.
Referenced by QTest::qInvokeTestMethodDataEntry().
 {
     QTEST_ASSERT(QTest::testLogger);
     QTest::testLogger->addBenchmarkResult(result);
 }
addFail()
void QTestLog::addFail (const char * msg, const char * file, int line) static
Definition at line 264 of file qtestlog.cpp.
Referenced by QTestResult::addFailure().
 {
     QTEST_ASSERT(QTest::testLogger);
     QTest::testLogger->addIncident(QAbstractTestLogger::Fail, msg, file, line);
 }
addIgnoreMessage()
void QTestLog::addIgnoreMessage (QtMsgType type, const char * msg) static
Definition at line 368 of file qtestlog.cpp.
Referenced by QTestResult::ignoreMessage().
 {
     QTest::IgnoreResultList *item = new QTest::IgnoreResultList(type, msg);
     QTest::IgnoreResultList *list = QTest::ignoreResultList;
     if (!list) {
         QTest::ignoreResultList = item;
         return;
     }
     while (list->next)
         list = list->next;
     list->next = item;
 }
addPass()
void QTestLog::addPass (const char * msg) static
Definition at line 253 of file qtestlog.cpp.
Referenced by QTestResult::finishedCurrentTestFunction().
 {
     if (QTest::printAvailableTags)
         return;
     QTEST_ASSERT(QTest::testLogger);
     QTEST_ASSERT(msg);
     QTest::testLogger->addIncident(QAbstractTestLogger::Pass, msg);
 }
addSkip()
void QTestLog::addSkip (const char * msg, QTest::SkipMode mode, const char * file, int line) static
Definition at line 289 of file qtestlog.cpp.
Referenced by QTestResult::addSkip().
 {
     QTEST_ASSERT(QTest::testLogger);
     QTEST_ASSERT(msg);
     QTEST_ASSERT(file);
     QTest::testLogger->addMessage(QAbstractTestLogger::Skip, msg, file, line);
 }
addXFail()
void QTestLog::addXFail (const char * msg, const char * file, int line) static
Definition at line 271 of file qtestlog.cpp.
Referenced by checkStatement().
 {
     QTEST_ASSERT(QTest::testLogger);
     QTEST_ASSERT(msg);
     QTEST_ASSERT(file);
     QTest::testLogger->addIncident(QAbstractTestLogger::XFail, msg, file, line);
 }
addXPass()
void QTestLog::addXPass (const char * msg, const char * file, int line) static
Definition at line 280 of file qtestlog.cpp.
Referenced by checkStatement().
 {
     QTEST_ASSERT(QTest::testLogger);
     QTEST_ASSERT(msg);
     QTEST_ASSERT(file);
     QTest::testLogger->addIncident(QAbstractTestLogger::XPass, msg, file, line);
 }
enterTestFunction()
void QTestLog::enterTestFunction (const char * function) static
Definition at line 206 of file qtestlog.cpp.
Referenced by QTestResult::setCurrentTestFunction().
 {
     if (QTest::printAvailableTags)
         return;
     QTEST_ASSERT(QTest::testLogger);
     QTEST_ASSERT(function);
     QTest::testLogger->enterTestFunction(function);
 }
info()
void QTestLog::info (const char * msg, const char * file, int line) static
Definition at line 340 of file qtestlog.cpp.
Referenced by QTestResult::compare(), QTest::qPrintMessage(), and QTestResult::verify().
 {
     QTEST_ASSERT(msg);
     if (QTest::testLogger)
         QTest::testLogger->addMessage(QAbstractTestLogger::Info, msg, file, line);
 }
leaveTestFunction()
void QTestLog::leaveTestFunction () static
Definition at line 228 of file qtestlog.cpp.
Referenced by QTestResult::finishedCurrentTestFunction(), and QTest::messageHandler().
 {
     if (QTest::printAvailableTags)
         return;
     QTEST_ASSERT(QTest::testLogger);
     QTest::IgnoreResultList::clearList(QTest::ignoreResultList);
     QTest::testLogger->leaveTestFunction();
 }
logMode()
QTestLog::LogMode QTestLog::logMode () static
Definition at line 353 of file qtestlog.cpp.
 {
     return QTest::logMode;
 }
outputFileName()
const char * QTestLog::outputFileName () static
Definition at line 389 of file qtestlog.cpp.
Referenced by QTest::outputMessage(), QAbstractTestLogger::startLogging(), and QTestBasicStreamer::startStreaming().
 {
     return QTest::outFile;
 }
printUnhandledIgnoreMessages()
void QTestLog::printUnhandledIgnoreMessages () static
Definition at line 239 of file qtestlog.cpp.
Referenced by QTestResult::finishedCurrentTestFunction().
 {
     QTEST_ASSERT(QTest::testLogger);
     char msg[1024];
     QTest::IgnoreResultList *list = QTest::ignoreResultList;
     while (list) {
         QTest::qt_snprintf(msg, 1024, "Did not receive message: \"%s\"", list->msg);
         QTest::testLogger->addMessage(QAbstractTestLogger::Info, msg);
         list = list->next;
     }
 }
redirectOutput()
void QTestLog::redirectOutput (const char * fileName) static
Definition at line 382 of file qtestlog.cpp.
Referenced by QTest::qtest_qParseArgs().
 {
     QTEST_ASSERT(fileName);
     QTest::outFile = fileName;
 }
setFlushMode()
void QTestLog::setFlushMode (FlushMode mode) static
Definition at line 399 of file qtestlog.cpp.
Referenced by QTest::qtest_qParseArgs().
 {
     QTest::flushMode = mode;
 }
setLogMode()
void QTestLog::setLogMode (LogMode mode) static
Definition at line 348 of file qtestlog.cpp.
Referenced by QTest::qtest_qParseArgs().
 {
     QTest::logMode = mode;
 }
setMaxWarnings()
void QTestLog::setMaxWarnings (int max) static
Definition at line 394 of file qtestlog.cpp.
Referenced by QTest::qtest_qParseArgs().
 {
     QTest::maxWarnings = m <= 0 ? INT_MAX : m + 2;
 }
setVerboseLevel()
void QTestLog::setVerboseLevel (int level) static
Definition at line 358 of file qtestlog.cpp.
Referenced by QTest::qtest_qParseArgs().
 {
     QTest::verbosity = level;
 }
startLogging() [1/2]
void QTestLog::startLogging () static
Definition at line 314 of file qtestlog.cpp.
Referenced by QTest::qInvokeTestMethods().
 {
     QTEST_ASSERT(!QTest::testLogger);
     QTest::initLogger();
     QTest::testLogger->startLogging();
     QTest::oldMessageHandler = qInstallMsgHandler(QTest::messageHandler);
 }
startLogging() [2/2]
void QTestLog::startLogging (unsigned int randomSeed) static
Definition at line 305 of file qtestlog.cpp.
 {
     QTEST_ASSERT(!QTest::testLogger);
     QTest::initLogger();
     QTest::testLogger->registerRandomSeed(randomSeed);
     QTest::testLogger->startLogging();
     QTest::oldMessageHandler = qInstallMsgHandler(QTest::messageHandler);
 }
stopLogging()
void QTestLog::stopLogging () static
Definition at line 322 of file qtestlog.cpp.
Referenced by QTest::messageHandler(), QTest::qExec(), and QTest::qInvokeTestMethods().
 {
     qInstallMsgHandler(QTest::oldMessageHandler);
     QTEST_ASSERT(QTest::testLogger);
     QTest::testLogger->stopLogging();
     delete QTest::testLogger;
     QTest::testLogger = 0;
 }
unhandledIgnoreMessages()
int QTestLog::unhandledIgnoreMessages () static
Definition at line 217 of file qtestlog.cpp.
Referenced by QTestResult::finishedCurrentTestFunction().
 {
     int i = 0;
     QTest::IgnoreResultList *list = QTest::ignoreResultList;
     while (list) {
         ++i;
         list = list->next;
     }
     return i;
 }
verboseLevel()
int QTestLog::verboseLevel () static
Definition at line 363 of file qtestlog.cpp.
Referenced by QPlainTestLogger::addIncident(), QPlainTestLogger::addMessage(), QTestResult::compare(), QPlainTestLogger::enterTestFunction(), QPlainTestLogger::startLogging(), QPlainTestLogger::stopLogging(), and QTestResult::verify().
 {
     return QTest::verbosity;
 }
warn()
void QTestLog::warn (const char * msg) static
Definition at line 332 of file qtestlog.cpp.
Referenced by QTest::qWarn().
 {
     QTEST_ASSERT(QTest::testLogger);
     QTEST_ASSERT(msg);
     QTest::testLogger->addMessage(QAbstractTestLogger::Warn, msg);
 }
The documentation for this class was generated from the following files:
/src/testlib/qtestlog_p.h
/src/testlib/qtestlog.cpp