Qt 4.8: QPixmapConvolutionFilter Class Reference
QPixmapConvolutionFilter Class Reference
The QPixmapConvolutionFilter class provides convolution filtering for pixmaps.
#include <qpixmapfilter_p.h>
Public Functions
QRectF boundingRectFor (const QRectF &rect) const
void draw (QPainter *painter, const QPointF &dest, const QPixmap &src, const QRectF &srcRect=QRectF()) const
QPixmapConvolutionFilter (QObject *parent=0)
Constructs a pixmap convolution filter.
void setConvolutionKernel (const qreal *matrix, int rows, int columns)
Sets convolution kernel with the given number of rows and columns.
~QPixmapConvolutionFilter ()
Destructor of pixmap convolution filter.
Public Functions inherited from QPixmapFilter
FilterType type () const
Returns the type of the filter.
virtual ~QPixmapFilter ()=0
Destroys the pixmap filter.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
int columns () const
Gets the number of columns in the convolution kernel.
const qreal * convolutionKernel () const
Gets the convolution kernel data.
int rows () const
Gets the number of rows in the convolution kernel.
Friends
class QGLPixmapConvolutionFilter
class QVGPixmapConvolutionFilter
Additional Inherited Members
Public Types inherited from QPixmapFilter
enum FilterType {
ConvolutionFilter, ColorizeFilter, DropShadowFilter, BlurFilter,
UserFilter = 1024
}
This enum describes the types of filter that can be applied to pixmaps.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QPixmapFilter
QPixmapFilter (QPixmapFilterPrivate &d, FilterType type, QObject *parent)
QPixmapFilter (FilterType type, QObject *parent)
Constructs a default QPixmapFilter with the given type.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPixmapConvolutionFilter class provides convolution filtering for pixmaps.
Since
4.5
QPixmapConvolutionFilter implements a convolution pixmap filter, which is applied when QPixmapFilter::draw() is called. A convolution filter lets you distort an image by setting the values of a matrix of qreal values called its kernel. The matrix's values are usually between -1.0 and 1.0.
Warning
This function is not part of the public interface. In convolution filtering, the pixel value is calculated from the neighboring pixels based on the weighting convolution kernel. This needs explaining to be useful.
Example:
QPixmapConvolutionFilter *myFilter = new QPixmapConvolutionFilter;
qreal kernel[] = {
     0.0,-1.0, 0.0,
    -1.0, 5.0,-1.0,
     0.0,-1.0, 0.0
    };
myFilter->setConvolutionKernel(kernel, 3, 3);
myFilter->draw(painter, QPoint(0, 0), originalPixmap);
See also
{Pixmap Filters Example}, QPixmapColorizeFilter, QPixmapDropShadowFilter
Warning
This function is not part of the public interface.
Definition at line 101 of file qpixmapfilter_p.h.
Constructors and Destructors
QPixmapConvolutionFilter()
QPixmapConvolutionFilter::QPixmapConvolutionFilter (QObject * parent = 0)
Constructs a pixmap convolution filter.
By default there is no convolution kernel.
Warning
This function is not part of the public interface.
Definition at line 241 of file qpixmapfilter.cpp.
     : QPixmapFilter(*new QPixmapConvolutionFilterPrivate, ConvolutionFilter, parent)
 {
     Q_D(QPixmapConvolutionFilter);
     d->convoluteAlpha = true;
 }
~QPixmapConvolutionFilter()
QPixmapConvolutionFilter::~QPixmapConvolutionFilter ()
Destructor of pixmap convolution filter.
Warning
This function is not part of the public interface.
Definition at line 253 of file qpixmapfilter.cpp.
 {
 }
Functions
boundingRectFor()
QRectF QPixmapConvolutionFilter::boundingRectFor (const QRectF & rect) const virtual
Warning
This function is not part of the public interface.
Reimplemented from QPixmapFilter.
Definition at line 315 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(const QPixmapConvolutionFilter);
     return rect.adjusted(-d->kernelWidth / 2, -d->kernelHeight / 2, (d->kernelWidth - 1) / 2, (d->kernelHeight - 1) / 2);
 }
columns()
int QPixmapConvolutionFilter::columns () const private
Gets the number of columns in the convolution kernel.
Warning
This function is not part of the public interface.
Definition at line 305 of file qpixmapfilter.cpp.
Referenced by QVGPixmapConvolutionFilter::draw(), QGLPixmapConvolutionFilter::processGL(), and setConvolutionKernel().
 {
     Q_D(const QPixmapConvolutionFilter);
     return d->kernelWidth;
 }
convolutionKernel()
const qreal * QPixmapConvolutionFilter::convolutionKernel () const private
Gets the convolution kernel data.
Warning
This function is not part of the public interface.
Definition at line 283 of file qpixmapfilter.cpp.
Referenced by QVGPixmapConvolutionFilter::draw().
 {
     Q_D(const QPixmapConvolutionFilter);
     return d->convolutionKernel;
 }
draw()
void QPixmapConvolutionFilter::draw (QPainter * painter, const QPointF & p, const QPixmap & src, const QRectF & srcRect = QRectF()) const virtual
Warning
This function is not part of the public interface.
Implements QPixmapFilter.
Reimplemented in QGLPixmapFilter< QPixmapConvolutionFilter >, and QVGPixmapConvolutionFilter.
Definition at line 425 of file qpixmapfilter.cpp.
Referenced by QVGPixmapConvolutionFilter::draw(), and draw().
 {
     Q_D(const QPixmapConvolutionFilter);
     if (!painter->isActive())
         return;
     if(d->kernelWidth<=0 || d->kernelHeight <= 0)
         return;
     if (src.isNull())
         return;
     QPixmapFilter *filter = painter->paintEngine() && painter->paintEngine()->isExtended() ?
         static_cast<QPaintEngineEx *>(painter->paintEngine())->pixmapFilter(type(), this) : 0;
     QPixmapConvolutionFilter *convolutionFilter = static_cast<QPixmapConvolutionFilter*>(filter);
     if (convolutionFilter) {
         convolutionFilter->setConvolutionKernel(d->convolutionKernel, d->kernelWidth, d->kernelHeight);
         convolutionFilter->d_func()->convoluteAlpha = d->convoluteAlpha;
         convolutionFilter->draw(painter, p, src, srcRect);
         return;
     }
     // falling back to raster implementation
     QImage *target = 0;
     if (painter->paintEngine()->paintDevice()->devType() == QInternal::Image) {
         target = static_cast<QImage *>(painter->paintEngine()->paintDevice());
         QTransform mat = painter->combinedTransform();
         if (mat.type() > QTransform::TxTranslate) {
             // Disabled because of transformation...
             target = 0;
         } else {
             QRasterPaintEngine *pe = static_cast<QRasterPaintEngine *>(painter->paintEngine());
             if (pe->clipType() == QRasterPaintEngine::ComplexClip)
                 // disabled because of complex clipping...
                 target = 0;
             else {
                 QRectF clip = pe->clipBoundingRect();
                 QRectF rect = boundingRectFor(srcRect.isEmpty() ? src.rect() : srcRect);
                 QTransform x = painter->deviceTransform();
                 if (!clip.contains(rect.translated(x.dx() + p.x(), x.dy() + p.y()))) {
                     target = 0;
                 }
             }
         }
     }
     if (target) {
         QTransform x = painter->deviceTransform();
         QPointF offset(x.dx(), x.dy());
         convolute(target, p+offset, src.toImage(), srcRect, QPainter::CompositionMode_SourceOver, d->convolutionKernel, d->kernelWidth, d->kernelHeight);
     } else {
         QRect srect = srcRect.isNull() ? src.rect() : srcRect.toRect();
         QRect rect = boundingRectFor(srect).toRect();
         QImage result = QImage(rect.size(), QImage::Format_ARGB32_Premultiplied);
         QPoint offset = srect.topLeft() - rect.topLeft();
         convolute(&result,
                   offset,
                   src.toImage(),
                   srect,
                   QPainter::CompositionMode_Source,
                   d->convolutionKernel,
                   d->kernelWidth,
                   d->kernelHeight);
         painter->drawImage(p - offset, result);
     }
 }
rows()
int QPixmapConvolutionFilter::rows () const private
Gets the number of rows in the convolution kernel.
Warning
This function is not part of the public interface.
Definition at line 294 of file qpixmapfilter.cpp.
Referenced by QVGPixmapConvolutionFilter::draw(), QGLPixmapConvolutionFilter::processGL(), and setConvolutionKernel().
 {
     Q_D(const QPixmapConvolutionFilter);
     return d->kernelHeight;
 }
setConvolutionKernel()
void QPixmapConvolutionFilter::setConvolutionKernel (const qreal * kernel, int rows, int columns)
Sets convolution kernel with the given number of rows and columns.
Values from kernel are copied to internal data structure.
To preserve the intensity of the pixmap, the sum of all the values in the convolution kernel should add up to 1.0. A sum greater than 1.0 produces a lighter result and a sum less than 1.0 produces a darker and transparent result.
Warning
This function is not part of the public interface.
Definition at line 268 of file qpixmapfilter.cpp.
Referenced by draw().
 {
     Q_D(QPixmapConvolutionFilter);
     delete [] d->convolutionKernel;
     d->convolutionKernel = new qreal[rows * columns];
     memcpy(d->convolutionKernel, kernel, sizeof(qreal) * rows * columns);
     d->kernelWidth = columns;
     d->kernelHeight = rows;
 }
Friends and Related Functions
QGLPixmapConvolutionFilter
friend class QGLPixmapConvolutionFilter friend
Definition at line 116 of file qpixmapfilter_p.h.
QVGPixmapConvolutionFilter
friend class QVGPixmapConvolutionFilter friend
Definition at line 117 of file qpixmapfilter_p.h.
The documentation for this class was generated from the following files:
/src/gui/image/qpixmapfilter_p.h
/src/gui/image/qpixmapfilter.cpp