Qt 4.8: QByteDataBuffer Class Reference
QByteDataBuffer Class Reference
#include <qbytedata_p.h>
Public Functions
void append (QByteDataBuffer &other)
void append (const QByteArray &bd)
qint64 bufferCount () const
qint64 byteAmount () const
bool canReadLine () const
void clear ()
char getChar ()
bool isEmpty () const
QByteArray & operator[] (int i)
void prepend (QByteArray &bd)
QByteDataBuffer ()
QByteArray read ()
QByteArray read (qint64 amount)
qint64 read (char *dst, qint64 amount)
QByteArray readAll ()
qint64 sizeNextBlock () const
~QByteDataBuffer ()
Properties
qint64 bufferCompleteSize
QList< QByteArray > buffers
Detailed Description
Definition at line 62 of file qbytedata_p.h.
Constructors and Destructors
QByteDataBuffer()
QByteDataBuffer::QByteDataBuffer () inline
Definition at line 68 of file qbytedata_p.h.
                       : bufferCompleteSize(0)
     {
     }
~QByteDataBuffer()
QByteDataBuffer::~QByteDataBuffer () inline
Definition at line 72 of file qbytedata_p.h.
     {
         clear();
     }
Functions
append() [1/2]
void QByteDataBuffer::append (QByteDataBuffer & other) inline
Definition at line 77 of file qbytedata_p.h.
Referenced by QNetworkReplyImplPrivate::_q_copyReadyRead(), QNetworkReplyImplPrivate::appendDownstreamData(), QHttpNetworkReplyPrivate::appendUncompressedReplyData(), QNetworkAccessFtpBackend::ftpReadyRead(), QHttpNetworkReplyPrivate::readBodyFast(), QNetworkAccessFileBackend::readMoreFromFile(), QHttpNetworkReplyPrivate::readReplyBodyRaw(), and QNetworkAccessHttpBackend::replyDownloadData().
     {
         if (other.isEmpty())
             return;
         buffers.append(other.buffers);
         bufferCompleteSize += other.byteAmount();
     }
append() [2/2]
void QByteDataBuffer::append (const QByteArray & bd) inline
Definition at line 87 of file qbytedata_p.h.
     {
         if (bd.isEmpty())
             return;
         buffers.append(bd);
         bufferCompleteSize += bd.size();
     }
bufferCount()
qint64 QByteDataBuffer::bufferCount () const inline
Definition at line 187 of file qbytedata_p.h.
Referenced by QHttpNetworkReplyPrivate::appendCompressedReplyData(), and QNetworkReplyImplPrivate::appendDownstreamData().
     {
         return buffers.length();
     }
byteAmount()
qint64 QByteDataBuffer::byteAmount () const inline
Definition at line 181 of file qbytedata_p.h.
Referenced by append(), isEmpty(), QNetworkReplyImplPrivate::nextDownstreamBlockSize(), read(), and readAll().
     {
         return bufferCompleteSize;
     }
canReadLine()
bool QByteDataBuffer::canReadLine () const inline
Definition at line 210 of file qbytedata_p.h.
{
         for (int i = 0; i < buffers.length(); i++)
             if (buffers.at(i).contains('\n'))
                 return true;
         return false;
     }
clear()
void QByteDataBuffer::clear () inline
Definition at line 174 of file qbytedata_p.h.
Referenced by QHttpNetworkReplyPrivate::appendCompressedReplyData(), QNetworkReplyImplPrivate::appendDownstreamData(), QHttpNetworkReplyPrivate::appendUncompressedReplyData(), QHttpNetworkReplyPrivate::eraseData(), QNetworkAccessHttpBackend::replyDownloadData(), and ~QByteDataBuffer().
     {
         buffers.clear();
         bufferCompleteSize = 0;
     }
getChar()
char QByteDataBuffer::getChar () inline
Definition at line 167 of file qbytedata_p.h.
     {
         char c;
         read(&c, 1);
         return c;
     }
isEmpty()
bool QByteDataBuffer::isEmpty () const inline
Definition at line 192 of file qbytedata_p.h.
Referenced by QHttpNetworkConnectionChannel::_q_receiveReply(), and append().
     {
         return byteAmount() == 0;
     }
operator[]()
QByteArray& QByteDataBuffer::operator[] (int i) inline
Definition at line 205 of file qbytedata_p.h.
     {
         return buffers[i];
     }
prepend()
void QByteDataBuffer::prepend (QByteArray & bd) inline
Definition at line 96 of file qbytedata_p.h.
     {
         if (bd.isEmpty())
             return;
         buffers.prepend(bd);
         bufferCompleteSize += bd.size();
     }
read() [1/3]
QByteArray QByteDataBuffer::read () inline
Definition at line 107 of file qbytedata_p.h.
Referenced by getChar(), read(), and readAll().
     {
         bufferCompleteSize -= buffers.first().size();
         return buffers.takeFirst();
     }
read() [2/3]
QByteArray QByteDataBuffer::read (qint64 amount) inline
Definition at line 122 of file qbytedata_p.h.
     {
         amount = qMin(byteAmount(), amount);
         QByteArray byteData;
         byteData.resize(amount);
         read(byteData.data(), byteData.size());
         return byteData;
     }
read() [3/3]
qint64 QByteDataBuffer::read (char * dst, qint64 amount) inline
Definition at line 133 of file qbytedata_p.h.
     {
         amount = qMin(amount, byteAmount());
         qint64 originalAmount = amount;
         char *writeDst = dst;
         while (amount > 0) {
             QByteArray first = buffers.takeFirst();
             if (amount >= first.size()) {
                 // take it completely
                 bufferCompleteSize -= first.size();
                 amount -= first.size();
                 memcpy(writeDst, first.constData(), first.size());
                 writeDst += first.size();
                 first.clear();
             } else {
                 // take a part of it & it is the last one to take
                 bufferCompleteSize -= amount;
                 memcpy(writeDst, first.constData(), amount);
                 qint64 newFirstSize = first.size() - amount;
                 QByteArray newFirstData;
                 newFirstData.resize(newFirstSize);
                 memcpy(newFirstData.data(), first.constData() + amount, newFirstSize);
                 buffers.prepend(newFirstData);
                 amount = 0;
                 first.clear();
             }
         }
         return originalAmount;
     }
readAll()
QByteArray QByteDataBuffer::readAll () inline
Definition at line 115 of file qbytedata_p.h.
     {
         return read(byteAmount());
     }
sizeNextBlock()
qint64 QByteDataBuffer::sizeNextBlock () const inline
Definition at line 197 of file qbytedata_p.h.
     {
         if(buffers.isEmpty())
             return 0;
         else
             return buffers.first().size();
     }
Properties
bufferCompleteSize
qint64 QByteDataBuffer::bufferCompleteSize private
Definition at line 66 of file qbytedata_p.h.
Referenced by byteAmount().
buffers
QList<QByteArray> QByteDataBuffer::buffers private
Definition at line 65 of file qbytedata_p.h.
Referenced by append().
The documentation for this class was generated from the following file:
/src/corelib/tools/qbytedata_p.h