Qt 4.8: QDeclarativeJS::TextWriter Class Reference
QDeclarativeJS::TextWriter Class Reference
#include <textwriter_p.h>
Classes
struct Move
struct Replace
Public Functions
void move (int pos, int length, int to)
void replace (int pos, int length, const QString &replacement)
TextWriter ()
void write (QString *s)
void write (QTextCursor *textCursor)
Private Functions
void doMove (const Move &move)
void doReplace (const Replace &replace)
bool hasMoveInto (int pos, int length)
bool hasOverlap (int pos, int length)
void write_helper ()
Properties
QTextCursor * cursor
QList< Move > moveList
QList< Replace > replaceList
QString * string
Detailed Description
Definition at line 56 of file textwriter_p.h.
Constructors and Destructors
TextWriter()
TextWriter::TextWriter ()
Definition at line 48 of file textwriter.cpp.
         :string(0), cursor(0)
 {
 }
Functions
doMove()
void TextWriter::doMove (const Move & move) private
Definition at line 149 of file textwriter.cpp.
Referenced by write_helper().
 {
     QString text;
     if (string) {
         text = string->mid(move.pos, move.length);
     } else if (cursor) {
         cursor->setPosition(move.pos);
         cursor->setPosition(move.pos + move.length, QTextCursor::KeepAnchor);
         text = cursor->selectedText();
     }
     Replace cut;
     cut.pos = move.pos;
     cut.length = move.length;
     Replace paste;
     paste.pos = move.to;
     paste.length = 0;
     paste.replacement = text;
     replaceList.append(cut);
     replaceList.append(paste);
     Replace cmd;
     while (!replaceList.isEmpty()) {
         cmd = replaceList.first();
         replaceList.removeFirst();
         doReplace(cmd);
     }
 }
doReplace()
void TextWriter::doReplace (const Replace & replace) private
Definition at line 113 of file textwriter.cpp.
Referenced by doMove(), and write_helper().
 {
     int diff = replace.replacement.size() - replace.length;
     {
         QMutableListIterator<Replace> i(replaceList);
         while (i.hasNext()) {
             Replace &c = i.next();
             if (replace.pos < c.pos)
                 c.pos += diff;
             else if (replace.pos + replace.length < c.pos + c.length)
                 c.length += diff;
         }
     }
     {
         QMutableListIterator<Move> i(moveList);
         while (i.hasNext()) {
             Move &c = i.next();
             if (replace.pos < c.pos)
                 c.pos += diff;
             else if (replace.pos + replace.length < c.pos + c.length)
                 c.length += diff;
             if (replace.pos < c.to)
                 c.to += diff;
         }
     }
     if (string) {
         string->replace(replace.pos, replace.length, replace.replacement);
     } else if (cursor) {
         cursor->setPosition(replace.pos);
         cursor->setPosition(replace.pos + replace.length, QTextCursor::KeepAnchor);
         cursor->insertText(replace.replacement);
     }
 }
hasMoveInto()
bool TextWriter::hasMoveInto (int pos, int length) private
Definition at line 79 of file textwriter.cpp.
Referenced by replace().
 {
     QListIterator<Move> i(moveList);
     while (i.hasNext()) {
         const Move &cmd = i.next();
         if (cmd.to >= pos && cmd.to < pos + length)
             return true;
     }
     return false;
 }
hasOverlap()
bool TextWriter::hasOverlap (int pos, int length) private
Definition at line 58 of file textwriter.cpp.
Referenced by move(), and replace().
 {
     {
         QListIterator<Replace> i(replaceList);
         while (i.hasNext()) {
             const Replace &cmd = i.next();
             if (overlaps(pos, length, cmd.pos, cmd.length))
                 return true;
         }
     }
     {
         QListIterator<Move> i(moveList);
         while (i.hasNext()) {
             const Move &cmd = i.next();
             if (overlaps(pos, length, cmd.pos, cmd.length))
                 return true;
         }
         return false;
     }
 }
move()
void TextWriter::move (int pos, int length, int to)
Definition at line 102 of file textwriter.cpp.
 {
     Q_ASSERT(!hasOverlap(pos, length));
     Move cmd;
     cmd.pos = pos;
     cmd.length = length;
     cmd.to = to;
     moveList += cmd;
 }
replace()
void TextWriter::replace (int pos, int length, const QString & replacement)
Definition at line 90 of file textwriter.cpp.
 {
     Q_ASSERT(!hasOverlap(pos, length));
     Q_ASSERT(!hasMoveInto(pos, length));
     Replace cmd;
     cmd.pos = pos;
     cmd.length = length;
     cmd.replacement = replacement;
     replaceList += cmd;
 }
write() [1/2]
void TextWriter::write (QString * s)
Definition at line 179 of file textwriter.cpp.
Referenced by QDeclarativeRewrite::RewriteBinding::operator()(), and QDeclarativeRewrite::RewriteBinding::rewrite().
 {
     string = s;
     write_helper();
     string = 0;
 }
write() [2/2]
void TextWriter::write (QTextCursor * textCursor)
Definition at line 186 of file textwriter.cpp.
 {
     cursor = textCursor;
     write_helper();
     cursor = 0;
 }
write_helper()
void TextWriter::write_helper () private
Definition at line 193 of file textwriter.cpp.
Referenced by write().
 {
     if (cursor)
         cursor->beginEditBlock();
     {
         Replace cmd;
         while (!replaceList.isEmpty()) {
             cmd = replaceList.first();
             replaceList.removeFirst();
             doReplace(cmd);
         }
     }
     {
         Move cmd;
         while (!moveList.isEmpty()) {
             cmd = moveList.first();
             moveList.removeFirst();
             doMove(cmd);
         }
     }
     if (cursor)
         cursor->endEditBlock();
 }
Properties
cursor
QTextCursor* QDeclarativeJS::TextWriter::cursor private
Definition at line 59 of file textwriter_p.h.
Referenced by doMove(), doReplace(), write(), and write_helper().
moveList
QList<Move> QDeclarativeJS::TextWriter::moveList private
Definition at line 75 of file textwriter_p.h.
Referenced by doReplace(), hasMoveInto(), hasOverlap(), move(), and write_helper().
replaceList
QList<Replace> QDeclarativeJS::TextWriter::replaceList private
Definition at line 67 of file textwriter_p.h.
Referenced by doMove(), doReplace(), hasOverlap(), replace(), and write_helper().
string
QString* QDeclarativeJS::TextWriter::string private
Definition at line 58 of file textwriter_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/rewriter/textwriter_p.h
/src/declarative/qml/rewriter/textwriter.cpp