Qt 4.8: QTableWidget Class Reference
QTableWidget Class Reference
The QTableWidget class provides an item-based table view with a default model.
#include <qtablewidget.h>
Public Slots
void clear ()
Removes all items in the view.
void clearContents ()
Removes all items not in the headers from the view.
void insertColumn (int column)
Inserts an empty column into the table at column.
void insertRow (int row)
Inserts an empty row into the table at row.
void removeColumn (int column)
Removes the column column and all its items from the table.
void removeRow (int row)
Removes the row row and all its items from the table.
void scrollToItem (const QTableWidgetItem *item, QAbstractItemView::ScrollHint hint=EnsureVisible)
Scrolls the view if necessary to ensure that the item is visible.
Public Slots inherited from QTableView
void hideColumn (int column)
Hide the given column.
void hideRow (int row)
Hide the given row.
void resizeColumnsToContents ()
Resizes all columns based on the size hints of the delegate used to render each item in the columns.
void resizeColumnToContents (int column)
Resizes the given column based on the size hints of the delegate used to render each item in the column.
void resizeRowsToContents ()
Resizes all rows based on the size hints of the delegate used to render each item in the rows.
void resizeRowToContents (int row)
Resizes the given row based on the size hints of the delegate used to render each item in the row.
void selectColumn (int column)
Selects the given column in the table view if the current SelectionMode and SelectionBehavior allows columns to be selected.
void selectRow (int row)
Selects the given row in the table view if the current SelectionMode and SelectionBehavior allows rows to be selected.
void setShowGrid (bool show)
void showColumn (int column)
Show the given column.
void showRow (int row)
Show the given row.
void sortByColumn (int column)
Sorts the model by the values in the given column.
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
virtual void reset ()
Reset the internal state of the view.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
virtual void selectAll ()
Selects all items in the view.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void cellActivated (int row, int column)
void cellChanged (int row, int column)
This signal is emitted whenever the data of the item in the cell specified by row and column has changed.
void cellClicked (int row, int column)
This signal is emitted whenever a cell in the table is clicked.
void cellDoubleClicked (int row, int column)
This signal is emitted whenever a cell in the table is double clicked.
void cellEntered (int row, int column)
This signal is emitted when the mouse cursor enters a cell.
void cellPressed (int row, int column)
This signal is emitted whenever a cell in the table is pressed.
void currentCellChanged (int currentRow, int currentColumn, int previousRow, int previousColumn)
This signal is emitted whenever the current cell changes.
void currentItemChanged (QTableWidgetItem *current, QTableWidgetItem *previous)
This signal is emitted whenever the current item changes.
void itemActivated (QTableWidgetItem *item)
This signal is emitted when the specified item has been activated.
void itemChanged (QTableWidgetItem *item)
This signal is emitted whenever the data of item has changed.
void itemClicked (QTableWidgetItem *item)
This signal is emitted whenever an item in the table is clicked.
void itemDoubleClicked (QTableWidgetItem *item)
This signal is emitted whenever an item in the table is double clicked.
void itemEntered (QTableWidgetItem *item)
This signal is emitted when the mouse cursor enters an item.
void itemPressed (QTableWidgetItem *item)
This signal is emitted whenever an item in the table is pressed.
void itemSelectionChanged ()
This signal is emitted whenever the selection changes.
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QWidget * cellWidget (int row, int column) const
Returns the widget displayed in the cell in the given row and column.
void closePersistentEditor (QTableWidgetItem *item)
Closes the persistent editor for item.
int column (const QTableWidgetItem *item) const
Returns the column for the item.
int columnCount () const
int currentColumn () const
Returns the column of the current item.
QTableWidgetItem * currentItem () const
Returns the current item.
int currentRow () const
Returns the row of the current item.
void editItem (QTableWidgetItem *item)
Starts editing the item if it is editable.
QList< QTableWidgetItem * > findItems (const QString &text, Qt::MatchFlags flags) const
Finds items that matches the text using the given flags.
QTableWidgetItem * horizontalHeaderItem (int column) const
Returns the horizontal header item for column, column, if one has been set; otherwise returns 0.
bool isItemSelected (const QTableWidgetItem *item) const
Returns true if the item is selected, otherwise returns false.
bool isSortingEnabled () const
QTableWidgetItem * item (int row, int column) const
Returns the item for the given row and column if one has been set; otherwise returns 0.
QTableWidgetItem * itemAt (const QPoint &p) const
Returns a pointer to the item at the given point, or returns 0 if point is not covered by an item in the table widget.
QTableWidgetItem * itemAt (int x, int y) const
Returns the item at the position equivalent to QPoint({ax}, {ay}) in the table widget's coordinate system, or returns 0 if the specified point is not covered by an item in the table widget.
const QTableWidgetItem * itemPrototype () const
Returns the item prototype used by the table.
void openPersistentEditor (QTableWidgetItem *item)
Opens an editor for the give item.
QTableWidget (QWidget *parent=0)
Creates a new table view with the given parent.
QTableWidget (int rows, int columns, QWidget *parent=0)
Creates a new table view with the given rows and columns, and with the given parent.
void removeCellWidget (int row, int column)
Removes the widget set on the cell indicated by row and column.
int row (const QTableWidgetItem *item) const
Returns the row for the item.
int rowCount () const
QList< QTableWidgetItem * > selectedItems ()
Returns a list of all selected items.
QList< QTableWidgetSelectionRange > selectedRanges () const
Returns a list of all selected ranges.
void setCellWidget (int row, int column, QWidget *widget)
Sets the given widget to be displayed in the cell in the given row and column, passing the ownership of the widget to the table.
void setColumnCount (int columns)
Sets the number of columns in this table's model to columns.
void setCurrentCell (int row, int column)
Sets the current cell to be the cell at position (row, column).
void setCurrentCell (int row, int column, QItemSelectionModel::SelectionFlags command)
Sets the current cell to be the cell at position (row, column), using the given command.
void setCurrentItem (QTableWidgetItem *item)
Sets the current item to item.
void setCurrentItem (QTableWidgetItem *item, QItemSelectionModel::SelectionFlags command)
Sets the current item to be item, using the given command.
void setHorizontalHeaderItem (int column, QTableWidgetItem *item)
Sets the horizontal header item for column column to item.
void setHorizontalHeaderLabels (const QStringList &labels)
Sets the horizontal header labels using labels.
void setItem (int row, int column, QTableWidgetItem *item)
Sets the item for the given row and column to item.
void setItemPrototype (const QTableWidgetItem *item)
Sets the item prototype for the table to the specified item.
void setItemSelected (const QTableWidgetItem *item, bool select)
Selects or deselects item depending on select.
void setRangeSelected (const QTableWidgetSelectionRange &range, bool select)
Selects or deselects the range depending on select.
void setRowCount (int rows)
Sets the number of rows in this table's model to rows.
void setSortingEnabled (bool enable)
void setVerticalHeaderItem (int row, QTableWidgetItem *item)
Sets the vertical header item for row row to item.
void setVerticalHeaderLabels (const QStringList &labels)
Sets the vertical header labels using labels.
void sortItems (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts all the rows in the table widget based on column and order.
QTableWidgetItem * takeHorizontalHeaderItem (int column)
Removes the horizontal header item at column from the header without deleting it.
QTableWidgetItem * takeItem (int row, int column)
Removes the item at row and column from the table without deleting it.
QTableWidgetItem * takeVerticalHeaderItem (int row)
Removes the vertical header item at row from the header without deleting it.
QTableWidgetItem * verticalHeaderItem (int row) const
Returns the vertical header item for row row.
int visualColumn (int logicalColumn) const
Returns the visual column of the given logicalColumn.
QRect visualItemRect (const QTableWidgetItem *item) const
Returns the rectangle on the viewport occupied by the item at item.
int visualRow (int logicalRow) const
Returns the visual row of the given logicalRow.
~QTableWidget ()
Destroys this QTableWidget.
Public Functions inherited from QTableView
void clearSpans ()
Removes all row and column spans in the table view.
int columnAt (int x) const
Returns the column in which the given x-coordinate, x, in contents coordinates is located.
int columnSpan (int row, int column) const
Returns the column span of the table element at (row, column).
int columnViewportPosition (int column) const
Returns the x-coordinate in contents coordinates of the given column.
int columnWidth (int column) const
Returns the width of the given column.
void doItemsLayout ()
Qt::PenStyle gridStyle () const
QHeaderView * horizontalHeader () const
Returns the table view's horizontal header.
QModelIndex indexAt (const QPoint &p) const
Returns the index position of the model item corresponding to the table item at position pos in contents coordinates.
bool isColumnHidden (int column) const
Returns true if the given column is hidden; otherwise returns false.
bool isCornerButtonEnabled () const
bool isRowHidden (int row) const
Returns true if the given row is hidden; otherwise returns false.
bool isSortingEnabled () const
QTableView (QWidget *parent=0)
Constructs a table view with a parent to represent the data.
int rowAt (int y) const
Returns the row in which the given y-coordinate, y, in contents coordinates is located.
int rowHeight (int row) const
Returns the height of the given row.
int rowSpan (int row, int column) const
Returns the row span of the table element at (row, column).
int rowViewportPosition (int row) const
Returns the y-coordinate in contents coordinates of the given row.
void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
Makes sure that the given item is visible in the table view, scrolling if necessary.
void setColumnHidden (int column, bool hide)
If hide is true the given column will be hidden; otherwise it will be shown.
void setColumnWidth (int column, int width)
Sets the width of the given column to be width.
void setCornerButtonEnabled (bool enable)
void setGridStyle (Qt::PenStyle style)
void setHorizontalHeader (QHeaderView *header)
Sets the widget to use for the horizontal header to header.
void setRootIndex (const QModelIndex &index)
Reimplemented Function
void setRowHeight (int row, int height)
Sets the height of the given row to be height.
void setRowHidden (int row, bool hide)
If hide is true row will be hidden, otherwise it will be shown.
void setSelectionModel (QItemSelectionModel *selectionModel)
Reimplemented Function
void setSortingEnabled (bool enable)
If enabled true enables sorting for the table and immediately trigger a call to sortByColumn() with the current sort section and order.
void setSpan (int row, int column, int rowSpan, int columnSpan)
Sets the span of the table element at (row, column) to the number of rows and columns specified by (rowSpanCount, columnSpanCount).
void setVerticalHeader (QHeaderView *header)
Sets the widget to use for the vertical header to header.
void setWordWrap (bool on)
bool showGrid () const
void sortByColumn (int column, Qt::SortOrder order)
Sorts the model by the values in the given column in the given order.
QHeaderView * verticalHeader () const
Returns the table view's vertical header.
QRect visualRect (const QModelIndex &index) const
Returns the rectangle on the viewport occupied by the given index.
bool wordWrap () const
~QTableView ()
Destroys the table view.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
virtual void keyboardSearch (const QString &search)
Moves to and selects the item best matching the string search.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void dropEvent (QDropEvent *event)
Reimplemented Function
virtual bool dropMimeData (int row, int column, const QMimeData *data, Qt::DropAction action)
Handles the data supplied by a drag and drop operation that ended with the given action in the given row and column.
bool event (QEvent *e)
Reimplemented Function
QModelIndex indexFromItem (QTableWidgetItem *item) const
Returns the QModelIndex assocated with the given item.
QTableWidgetItem * itemFromIndex (const QModelIndex &index) const
Returns a pointer to the QTableWidgetItem assocated with the given index.
QList< QTableWidgetItem * > items (const QMimeData *data) const
Returns a list of pointers to the items contained in the data object.
virtual QMimeData * mimeData (const QList< QTableWidgetItem *> items) const
Returns an object that contains a serialized description of the specified items.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of tablewidget items.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this view.
Protected Functions inherited from QTableView
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Reimplemented Function
int horizontalOffset () const
Returns the horizontal offset of the items in the table view.
void horizontalScrollbarAction (int action)
bool isIndexHidden (const QModelIndex &index) const
Reimplemented Function
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
Moves the cursor in accordance with the given cursorAction, using the information provided by the modifiers.
void paintEvent (QPaintEvent *e)
Paints the table on receipt of the given paint event event.
QTableView (QTableViewPrivate &, QWidget *parent)
void scrollContentsBy (int dx, int dy)
Scroll the contents of the table view by (dx, dy).
QModelIndexList selectedIndexes () const
Reimplemented Function
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Reimplemented Function
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
Applies the selection flags to the items in or touched by the rectangle, rect.
int sizeHintForColumn (int column) const
Returns the size hint for the given column's width or -1 if there is no model.
int sizeHintForRow (int row) const
Returns the size hint for the given row's height or -1 if there is no model.
void timerEvent (QTimerEvent *event)
Reimplemented Function
void updateGeometries ()
Reimplemented Function
int verticalOffset () const
Returns the vertical offset of the items in the table view.
void verticalScrollbarAction (int action)
QStyleOptionViewItem viewOptions () const
Reimplemented Function
QRegion visualRegionForSelection (const QItemSelection &selection) const
Returns the rectangle from the viewport of the items in the given selection.
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
void dragLeaveEvent (QDragLeaveEvent *event)
This function is called when the item being dragged leaves the view.
void dragMoveEvent (QDragMoveEvent *event)
This function is called continuously with the given event during a drag and drop operation over the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
This function is called with the given event when a key event is sent to the widget.
void mouseDoubleClickEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is double clicked inside the widget.
void mouseMoveEvent (QMouseEvent *event)
This function is called with the given event when a mouse move event is sent to the widget.
void mousePressEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is pressed while the cursor is inside the widget.
void mouseReleaseEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is released, after a mouse press event on the widget.
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
This function is called with the given event when a resize event is sent to the widget.
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
virtual void startDrag (Qt::DropActions supportedActions)
Starts a drag by calling drag->exec() using the given supportedActions.
State state () const
Returns the item view's state.
void stopAutoScroll ()
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
bool viewportEvent (QEvent *event)
This function is used to handle tool tips, and What's This? mode, if the given event is a QEvent::ToolTip,or a QEvent::WhatsThis.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
void setModel (QAbstractItemModel *model)
Properties
int columnCount
the number of columns in the table
int rowCount
the number of rows in the table
Friends
class QTableModel
Additional Inherited Members
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Slots inherited from QTableView
void columnCountChanged (int oldCount, int newCount)
This slot is called whenever columns are added or deleted.
void columnMoved (int column, int oldIndex, int newIndex)
This slot is called to change the index of the given column in the table view.
void columnResized (int column, int oldWidth, int newWidth)
This slot is called to change the width of the given column.
void rowCountChanged (int oldCount, int newCount)
This slot is called whenever rows are added or deleted.
void rowMoved (int row, int oldIndex, int newIndex)
This slot is called to change the index of the given row in the table view.
void rowResized (int row, int oldHeight, int newHeight)
This slot is called to change the height of the given row.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This slot is called when items are changed in the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarValueChanged (int value)
virtual void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
This slot is called when rows are about to be removed.
virtual void rowsInserted (const QModelIndex &parent, int start, int end)
This slot is called when rows are inserted.
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QTableWidget class provides an item-based table view with a default model.
Table widgets provide standard table display facilities for applications. The items in a QTableWidget are provided by QTableWidgetItem.
If you want a table that uses your own data model you should use QTableView rather than this class.
Table widgets can be constructed with the required numbers of rows and columns:
    tableWidget = new QTableWidget(12, 3, this);
Alternatively, tables can be constructed without a given size and resized later:
    tableWidget = new QTableWidget(this);
    tableWidget->setRowCount(10);
    tableWidget->setColumnCount(5);
Items are created ouside the table (with no parent widget) and inserted into the table with setItem():
    QTableWidgetItem *newItem = new QTableWidgetItem(tr("%1").arg(
        (row+1)*(column+1)));
    tableWidget->setItem(row, column, newItem);
If you want to enable sorting in your table widget, do so after you have populated it with items, otherwise sorting may interfere with the insertion order (see setItem() for details).
Tables can be given both horizontal and vertical headers. The simplest way to create the headers is to supply a list of strings to the setHorizontalHeaderLabels() and setVerticalHeaderLabels() functions. These will provide simple textual headers for the table's columns and rows. More sophisticated headers can be created from existing table items that are usually constructed outside the table. For example, we can construct a table item with an icon and aligned text, and use it as the header for a particular column:
    QTableWidgetItem *cubesHeaderItem = new QTableWidgetItem(tr("Cubes"));
    cubesHeaderItem->setIcon(QIcon(QPixmap(":/Images/cubed.png")));
    cubesHeaderItem->setTextAlignment(Qt::AlignVCenter);
The number of rows in the table can be found with rowCount(), and the number of columns with columnCount(). The table can be cleared with the clear() function.
Screenshot of a Windows XP style table widget
Screenshot of a Macintosh style table widget
Screenshot of a Plastique style table widget
A Windows XP Style Widget Gallery{Windows XP style} table widget. A Macintosh Style Widget Gallery{Macintosh style} table widget. A Plastique Style Widget Gallery{Plastique style} table widget.
See also
QTableWidgetItem, QTableView, {Model/View Programming}
Definition at line 220 of file qtablewidget.h.
Constructors and Destructors
QTableWidget() [1/2]
QTableWidget::QTableWidget (QWidget * parent = 0) explicit
Creates a new table view with the given parent.
Definition at line 1999 of file qtablewidget.cpp.
     : QTableView(*new QTableWidgetPrivate, parent)
 {
     Q_D(QTableWidget);
     QTableView::setModel(new QTableModel(0, 0, this));
     d->setup();
 }
QTableWidget() [2/2]
QTableWidget::QTableWidget (int rows, int columns, QWidget * parent = 0)
Creates a new table view with the given rows and columns, and with the given parent.
Definition at line 2010 of file qtablewidget.cpp.
     : QTableView(*new QTableWidgetPrivate, parent)
 {
     Q_D(QTableWidget);
     QTableView::setModel(new QTableModel(rows, columns, this));
     d->setup();
 }
~QTableWidget()
QTableWidget::~QTableWidget ()
Destroys this QTableWidget.
Definition at line 2021 of file qtablewidget.cpp.
 {
 }
Functions
cellActivated
void QTableWidget::cellActivated (int row, int column) signal
Since
4.1
This signal is emitted when the cell specified by row and column has been activated
cellChanged
void QTableWidget::cellChanged (int row, int column) signal
This signal is emitted whenever the data of the item in the cell specified by row and column has changed.
Since
4.1
cellClicked
void QTableWidget::cellClicked (int row, int column) signal
This signal is emitted whenever a cell in the table is clicked.
Since
4.1
The row and column specified is the cell that was clicked.
cellDoubleClicked
void QTableWidget::cellDoubleClicked (int row, int column) signal
This signal is emitted whenever a cell in the table is double clicked.
Since
4.1
The row and column specified is the cell that was double clicked.
cellEntered
void QTableWidget::cellEntered (int row, int column) signal
This signal is emitted when the mouse cursor enters a cell.
Since
4.1
The cell is specified by row and column.
This signal is only emitted when mouseTracking is turned on, or when a mouse button is pressed while moving into an item.
cellPressed
void QTableWidget::cellPressed (int row, int column) signal
This signal is emitted whenever a cell in the table is pressed.
Since
4.1
The row and column specified is the cell that was pressed.
cellWidget()
QWidget * QTableWidget::cellWidget (int row, int column) const
Returns the widget displayed in the cell in the given row and column.
Since
4.1
Note
The table takes ownership of the widget.
See also
setCellWidget()
Definition at line 2437 of file qtablewidget.cpp.
 {
     QModelIndex index = model()->index(row, column, QModelIndex());
     return QAbstractItemView::indexWidget(index);
 }
clear
void QTableWidget::clear () slot
Removes all items in the view.
This will also remove all selections. The table dimensions stay the same.
Definition at line 2706 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     selectionModel()->clear();
     d->tableModel()->clear();
 }
clearContents
void QTableWidget::clearContents () slot
Removes all items not in the headers from the view.
Since
4.2
This will also remove all selections. The table dimensions stay the same.
Definition at line 2723 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     selectionModel()->clear();
     d->tableModel()->clearContents();
 }
closePersistentEditor()
void QTableWidget::closePersistentEditor (QTableWidgetItem * item)
Closes the persistent editor for item.
See also
openPersistentEditor()
Definition at line 2416 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     if (!item)
         return;
     QModelIndex index = d->tableModel()->index(item);
     QAbstractItemView::closePersistentEditor(index);
 }
column()
int QTableWidget::column (const QTableWidgetItem * item) const
Returns the column for the item.
Definition at line 2083 of file qtablewidget.cpp.
Referenced by findItems().
 {
     Q_D(const QTableWidget);
     return d->tableModel()->index(item).column();
 }
columnCount()
int QTableWidget::columnCount () const
Referenced by findItems(), and setColumnCount().
currentCellChanged
void QTableWidget::currentCellChanged (int currentRow, int currentColumn, int previousRow, int previousColumn) signal
This signal is emitted whenever the current cell changes.
Since
4.1
The cell specified by previousRow and previousColumn is the cell that previously had the focus, the cell specified by currentRow and currentColumn is the new current cell.
currentColumn()
int QTableWidget::currentColumn () const
Returns the column of the current item.
See also
currentRow(), setCurrentCell()
Definition at line 2277 of file qtablewidget.cpp.
 {
     return currentIndex().column();
 }
currentItem()
QTableWidgetItem * QTableWidget::currentItem () const
Returns the current item.
See also
setCurrentItem()
Definition at line 2287 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     return d->tableModel()->item(currentIndex());
 }
currentItemChanged
void QTableWidget::currentItemChanged (QTableWidgetItem * current, QTableWidgetItem * previous) signal
This signal is emitted whenever the current item changes.
The previous item is the item that previously had the focus, current is the new current item.
currentRow()
int QTableWidget::currentRow () const
Returns the row of the current item.
See also
currentColumn(), setCurrentCell()
Definition at line 2267 of file qtablewidget.cpp.
 {
     return currentIndex().row();
 }
dropEvent()
void QTableWidget::dropEvent (QDropEvent * event) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2836 of file qtablewidget.cpp.
{
     Q_D(QTableWidget);
     if (event->source() == this && (event->dropAction() == Qt::MoveAction ||
                                     dragDropMode() == QAbstractItemView::InternalMove)) {
         QModelIndex topIndex;
         int col = -1;
         int row = -1;
         if (d->dropOn(event, &row, &col, &topIndex)) {
             QModelIndexList indexes = selectedIndexes();
             int top = INT_MAX;
             int left = INT_MAX;
             for (int i = 0; i < indexes.count(); ++i) {
                 top = qMin(indexes.at(i).row(), top);
                 left = qMin(indexes.at(i).column(), left);
             }
             QList<QTableWidgetItem *> taken;
             for (int i = 0; i < indexes.count(); ++i)
                 taken.append(takeItem(indexes.at(i).row(), indexes.at(i).column()));
             for (int i = 0; i < indexes.count(); ++i) {
                 QModelIndex index = indexes.at(i);
                 int r = index.row() - top + topIndex.row();
                 int c = index.column() - left + topIndex.column();
                 setItem(r, c, taken.takeFirst());
             }
             event->accept();
             // Don't want QAbstractItemView to delete it because it was "moved" we already did it
             event->setDropAction(Qt::CopyAction);
         }
     }
     QTableView::dropEvent(event);
 }
dropMimeData()
bool QTableWidget::dropMimeData (int row, int column, const QMimeData * data, Qt::DropAction action) protected virtual
Handles the data supplied by a drag and drop operation that ended with the given action in the given row and column.
Returns true if the data and action can be handled by the model; otherwise returns false.
See also
supportedDropActions()
Definition at line 2762 of file qtablewidget.cpp.
Referenced by QTableModel::dropMimeData().
 {
     QModelIndex idx;
 #ifndef QT_NO_DRAGANDDROP
     if (dropIndicatorPosition() == QAbstractItemView::OnItem) {
         // QAbstractTableModel::dropMimeData will overwrite on the index if row == -1 and column == -1
         idx = model()->index(row, column);
         row = -1;
         column = -1;
     }
 #endif
     return d_func()->tableModel()->QAbstractTableModel::dropMimeData(data, action , row, column, idx);
 }
editItem()
void QTableWidget::editItem (QTableWidgetItem * item)
Starts editing the item if it is editable.
Definition at line 2389 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     if (!item)
         return;
     edit(d->tableModel()->index(item));
 }
event()
bool QTableWidget::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2829 of file qtablewidget.cpp.
 {
     return QTableView::event(e);
 }
findItems()
QList< QTableWidgetItem * > QTableWidget::findItems (const QString & text, Qt::MatchFlags flags) const
Finds items that matches the text using the given flags.
Definition at line 2559 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     QModelIndexList indexes;
     for (int column = 0; column < columnCount(); ++column)
         indexes += d->model->match(model()->index(0, column, QModelIndex()),
                                      Qt::DisplayRole, text, -1, flags);
     QList<QTableWidgetItem*> items;
     for (int i = 0; i < indexes.size(); ++i)
         items.append(d->tableModel()->item(indexes.at(i)));
     return items;
 }
horizontalHeaderItem()
QTableWidgetItem * QTableWidget::horizontalHeaderItem (int column) const
Returns the horizontal header item for column, column, if one has been set; otherwise returns 0.
Definition at line 2190 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     return d->tableModel()->horizontalHeaderItem(column);
 }
indexFromItem()
QModelIndex QTableWidget::indexFromItem (QTableWidgetItem * item) const protected
Returns the QModelIndex assocated with the given item.
Definition at line 2804 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     return d->tableModel()->index(item);
 }
insertColumn
void QTableWidget::insertColumn (int column) slot
Inserts an empty column into the table at column.
Definition at line 2676 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->tableModel()->insertColumns(column);
 }
insertRow
void QTableWidget::insertRow (int row) slot
Inserts an empty row into the table at row.
Definition at line 2667 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->tableModel()->insertRows(row);
 }
isItemSelected()
bool QTableWidget::isItemSelected (const QTableWidgetItem * item) const
Returns true if the item is selected, otherwise returns false.
This function is deprecated. Use QTableWidgetItem::isSelected() instead.
Definition at line 2474 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     QModelIndex index = d->tableModel()->index(item);
     return selectionModel()->isSelected(index);
 }
isSortingEnabled()
bool QTableWidget::isSortingEnabled () const
Warning
This function is not part of the public interface.
Definition at line 2380 of file qtablewidget.cpp.
Referenced by QTableModel::setItem().
 {
     return QTableView::isSortingEnabled();
 }
item()
QTableWidgetItem * QTableWidget::item (int row, int column) const
Returns the item for the given row and column if one has been set; otherwise returns 0.
See also
setItem()
Definition at line 2096 of file qtablewidget.cpp.
Referenced by selectedItems(), setHorizontalHeaderLabels(), setVerticalHeaderLabels(), and takeItem().
 {
     Q_D(const QTableWidget);
     return d->tableModel()->item(row, column);
 }
itemActivated
void QTableWidget::itemActivated (QTableWidgetItem * item) signal
This signal is emitted when the specified item has been activated.
itemAt() [1/2]
QTableWidgetItem * QTableWidget::itemAt (const QPoint & point) const
Returns a pointer to the item at the given point, or returns 0 if point is not covered by an item in the table widget.
See also
item()
Definition at line 2599 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     return d->tableModel()->item(indexAt(p));
 }
itemAt() [2/2]
QTableWidgetItem * QTableWidget::itemAt (int ax, int ay) const inline
Returns the item at the position equivalent to QPoint({ax}, {ay}) in the table widget's coordinate system, or returns 0 if the specified point is not covered by an item in the table widget.
See also
item()
Definition at line 356 of file qtablewidget.h.
 { return itemAt(QPoint(ax, ay)); }
itemChanged
void QTableWidget::itemChanged (QTableWidgetItem * item) signal
This signal is emitted whenever the data of item has changed.
itemClicked
void QTableWidget::itemClicked (QTableWidgetItem * item) signal
This signal is emitted whenever an item in the table is clicked.
The item specified is the item that was clicked.
itemDoubleClicked
void QTableWidget::itemDoubleClicked (QTableWidgetItem * item) signal
This signal is emitted whenever an item in the table is double clicked.
The item specified is the item that was double clicked.
itemEntered
void QTableWidget::itemEntered (QTableWidgetItem * item) signal
This signal is emitted when the mouse cursor enters an item.
The item is the item entered.
This signal is only emitted when mouseTracking is turned on, or when a mouse button is pressed while moving into an item.
itemFromIndex()
QTableWidgetItem * QTableWidget::itemFromIndex (const QModelIndex & index) const protected
Returns a pointer to the QTableWidgetItem assocated with the given index.
Definition at line 2814 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     return d->tableModel()->item(index);
 }
itemPressed
void QTableWidget::itemPressed (QTableWidgetItem * item) signal
This signal is emitted whenever an item in the table is pressed.
The item specified is the item that was pressed.
itemPrototype()
const QTableWidgetItem * QTableWidget::itemPrototype () const
Returns the item prototype used by the table.
See also
setItemPrototype()
Definition at line 2639 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     return d->tableModel()->itemPrototype();
 }
items()
QList< QTableWidgetItem * > QTableWidget::items (const QMimeData * data) const protected
Returns a list of pointers to the items contained in the data object.
If the object was not created by a QTreeWidget in the same process, the list is empty.
Definition at line 2792 of file qtablewidget.cpp.
Referenced by findItems(), and selectedItems().
 {
     const QTableWidgetMimeData *twd = qobject_cast<const QTableWidgetMimeData*>(data);
     if (twd)
         return twd->items;
     return QList<QTableWidgetItem*>();
 }
itemSelectionChanged
void QTableWidget::itemSelectionChanged () signal
This signal is emitted whenever the selection changes.
See also
selectedItems() QTableWidgetItem::isSelected()
mimeData()
QMimeData * QTableWidget::mimeData (const QList< QTableWidgetItem *> items) const protected virtual
Returns an object that contains a serialized description of the specified items.
The format used to describe the items is obtained from the mimeTypes() function.
If the list of items is empty, 0 is returned rather than a serialized empty list.
Definition at line 2749 of file qtablewidget.cpp.
Referenced by QTableModel::mimeData().
 {
     return d_func()->tableModel()->internalMimeData();
 }
mimeTypes()
QStringList QTableWidget::mimeTypes () const protected virtual
Returns a list of MIME types that can be used to describe a list of tablewidget items.
See also
mimeData()
Definition at line 2736 of file qtablewidget.cpp.
Referenced by QTableModel::mimeTypes().
 {
     return d_func()->tableModel()->QAbstractTableModel::mimeTypes();
 }
openPersistentEditor()
void QTableWidget::openPersistentEditor (QTableWidgetItem * item)
Opens an editor for the give item.
The editor remains open after editing.
See also
closePersistentEditor()
Definition at line 2402 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     if (!item)
         return;
     QModelIndex index = d->tableModel()->index(item);
     QAbstractItemView::openPersistentEditor(index);
 }
removeCellWidget()
void QTableWidget::removeCellWidget (int row, int column) inline
Removes the widget set on the cell indicated by row and column.
Since
4.3
Definition at line 353 of file qtablewidget.h.
 { setCellWidget(arow, acolumn, 0); }
removeColumn
void QTableWidget::removeColumn (int column) slot
Removes the column column and all its items from the table.
Definition at line 2694 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->tableModel()->removeColumns(column);
 }
removeRow
void QTableWidget::removeRow (int row) slot
Removes the row row and all its items from the table.
Definition at line 2685 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->tableModel()->removeRows(row);
 }
row()
int QTableWidget::row (const QTableWidgetItem * item) const
Returns the row for the item.
Definition at line 2074 of file qtablewidget.cpp.
Referenced by dropEvent().
 {
     Q_D(const QTableWidget);
     return d->tableModel()->index(item).row();
 }
rowCount()
int QTableWidget::rowCount () const
Referenced by setRowCount().
scrollToItem
void QTableWidget::scrollToItem (const QTableWidgetItem * item, QAbstractItemView::ScrollHint hint = EnsureVisible) slot
Scrolls the view if necessary to ensure that the item is visible.
The hint parameter specifies more precisely where the item should be located after the operation.
Definition at line 2624 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     if (!item)
         return;
     QModelIndex index = d->tableModel()->index(const_cast<QTableWidgetItem*>(item));
     Q_ASSERT(index.isValid());
     QTableView::scrollTo(index, hint);
 }
selectedItems()
QList< QTableWidgetItem * > QTableWidget::selectedItems ()
Returns a list of all selected items.
This function returns a list of pointers to the contents of the selected cells. Use the selectedIndexes() function to retrieve the complete selection including empty cells.
See also
selectedIndexes()
Definition at line 2539 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     QModelIndexList indexes = selectionModel()->selectedIndexes();
     QList<QTableWidgetItem*> items;
     for (int i = 0; i < indexes.count(); ++i) {
         QModelIndex index = indexes.at(i);
         if (isIndexHidden(index))
             continue;
         QTableWidgetItem *item = d->tableModel()->item(index);
         if (item)
             items.append(item);
     }
     return items;
 }
selectedRanges()
QList< QTableWidgetSelectionRange > QTableWidget::selectedRanges () const
Returns a list of all selected ranges.
See also
QTableWidgetSelectionRange
Definition at line 2517 of file qtablewidget.cpp.
 {
     const QList<QItemSelectionRange> ranges = selectionModel()->selection();
     QList<QTableWidgetSelectionRange> result;
     for (int i = 0; i < ranges.count(); ++i)
         result.append(QTableWidgetSelectionRange(ranges.at(i).top(),
                                                  ranges.at(i).left(),
                                                  ranges.at(i).bottom(),
                                                  ranges.at(i).right()));
     return result;
 }
setCellWidget()
void QTableWidget::setCellWidget (int row, int column, QWidget * widget)
Sets the given widget to be displayed in the cell in the given row and column, passing the ownership of the widget to the table.
Since
4.1
If cell widget A is replaced with cell widget B, cell widget A will be deleted. For example, in the code snippet below, the QLineEdit object will be deleted.
setCellWidget(index, new QLineEdit);
...
setCellWidget(index, new QTextEdit);
See also
cellWidget()
Definition at line 2460 of file qtablewidget.cpp.
 {
     QModelIndex index = model()->index(row, column, QModelIndex());
     QAbstractItemView::setIndexWidget(index, widget);
 }
setColumnCount()
void QTableWidget::setColumnCount (int columns)
Sets the number of columns in this table's model to columns.
If this is less than columnCount(), the data in the unwanted columns is discarded.
See also
setRowCount()
Definition at line 2055 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->tableModel()->setColumnCount(columns);
 }
setCurrentCell() [1/2]
void QTableWidget::setCurrentCell (int row, int column)
Sets the current cell to be the cell at position (row, column).
Since
4.1
Depending on the current selection mode, the cell may also be selected.
See also
setCurrentItem(), currentRow(), currentColumn()
Definition at line 2337 of file qtablewidget.cpp.
 {
     setCurrentIndex(model()->index(row, column, QModelIndex()));
 }
setCurrentCell() [2/2]
void QTableWidget::setCurrentCell (int row, int column, QItemSelectionModel::SelectionFlags command)
Sets the current cell to be the cell at position (row, column), using the given command.
Since
4.4
See also
setCurrentItem(), currentRow(), currentColumn()
Definition at line 2353 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->selectionModel->setCurrentIndex(model()->index(row, column, QModelIndex()), command);
 }
setCurrentItem() [1/2]
void QTableWidget::setCurrentItem (QTableWidgetItem * item)
Sets the current item to item.
Unless the selection mode is QAbstractItemView::NoSelection, the item is also be selected.
See also
currentItem(), setCurrentCell()
Definition at line 2301 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     setCurrentIndex(d->tableModel()->index(item));
 }
setCurrentItem() [2/2]
void QTableWidget::setCurrentItem (QTableWidgetItem * item, QItemSelectionModel::SelectionFlags command)
Sets the current item to be item, using the given command.
Since
4.4
See also
currentItem(), setCurrentCell()
Definition at line 2317 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->selectionModel->setCurrentIndex(d->tableModel()->index(item), command);
 }
setHorizontalHeaderItem()
void QTableWidget::setHorizontalHeaderItem (int column, QTableWidgetItem * item)
Sets the horizontal header item for column column to item.
Definition at line 2199 of file qtablewidget.cpp.
Referenced by setHorizontalHeaderLabels().
 {
     Q_D(QTableWidget);
     if (item) {
         item->view = this;
         d->tableModel()->setHorizontalHeaderItem(column, item);
     } else {
         delete takeHorizontalHeaderItem(column);
     }
 }
setHorizontalHeaderLabels()
void QTableWidget::setHorizontalHeaderLabels (const QStringList & labels)
Sets the horizontal header labels using labels.
Definition at line 2247 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     QTableModel *model = d->tableModel();
     QTableWidgetItem *item = 0;
     for (int i = 0; i < model->columnCount() && i < labels.count(); ++i) {
         item = model->horizontalHeaderItem(i);
         if (!item) {
             item = model->createItem();
             setHorizontalHeaderItem(i, item);
         }
         item->setText(labels.at(i));
     }
 }
setItem()
void QTableWidget::setItem (int row, int column, QTableWidgetItem * item)
Sets the item for the given row and column to item.
The table takes ownership of the item.
Note that if sorting is enabled (see sortingEnabled) and column is the current sort column, the row will be moved to the sorted position determined by item.
If you want to set several items of a particular row (say, by calling setItem() in a loop), you may want to turn off sorting before doing so, and turn it back on afterwards; this will allow you to use the same row argument for all items in the same row (i.e. setItem() will not move the row).
See also
item() takeItem()
Definition at line 2120 of file qtablewidget.cpp.
Referenced by dropEvent(), QTableModel::setData(), and QTableModel::setItemData().
 {
     Q_D(QTableWidget);
     if (item) {
         if (item->view != 0) {
             qWarning("QTableWidget: cannot insert an item that is already owned by another QTableWidget");
         } else {
             item->view = this;
             d->tableModel()->setItem(row, column, item);
         }
     } else {
         delete takeItem(row, column);
     }
 }
setItemPrototype()
void QTableWidget::setItemPrototype (const QTableWidgetItem * item)
Sets the item prototype for the table to the specified item.
The table widget will use the item prototype clone function when it needs to create a new table item. For example when the user is editing in an empty cell. This is useful when you have a QTableWidgetItem subclass and want to make sure that QTableWidget creates instances of your subclass.
The table takes ownership of the prototype.
See also
itemPrototype()
Definition at line 2658 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->tableModel()->setItemPrototype(item);
 }
setItemSelected()
void QTableWidget::setItemSelected (const QTableWidgetItem * item, bool select)
Selects or deselects item depending on select.
This function is deprecated. Use QTableWidgetItem::setSelected() instead.
Definition at line 2488 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     QModelIndex index = d->tableModel()->index(item);
     selectionModel()->select(index, select ? QItemSelectionModel::Select : QItemSelectionModel::Deselect);
 }
setModel()
void QTableWidget::setModel (QAbstractItemModel * model) private virtual
Warning
This function is not part of the public interface.
Reimplemented from QTableView.
Definition at line 2823 of file qtablewidget.cpp.
 {
     Q_ASSERT(!"QTableWidget::setModel() - Changing the model of the QTableWidget is not allowed.");
 }
setRangeSelected()
void QTableWidget::setRangeSelected (const QTableWidgetSelectionRange & range, bool select)
Selects or deselects the range depending on select.
Definition at line 2498 of file qtablewidget.cpp.
 {
     if (!model()->hasIndex(range.topRow(), range.leftColumn(), rootIndex()) ||
         !model()->hasIndex(range.bottomRow(), range.rightColumn(), rootIndex()))
         return;
     QModelIndex topLeft = model()->index(range.topRow(), range.leftColumn(), rootIndex());
     QModelIndex bottomRight = model()->index(range.bottomRow(), range.rightColumn(), rootIndex());
     selectionModel()->select(QItemSelection(topLeft, bottomRight),
                              select ? QItemSelectionModel::Select : QItemSelectionModel::Deselect);
 }
setRowCount()
void QTableWidget::setRowCount (int rows)
Sets the number of rows in this table's model to rows.
If this is less than rowCount(), the data in the unwanted rows is discarded.
See also
setColumnCount()
Definition at line 2032 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->tableModel()->setRowCount(rows);
 }
setSortingEnabled()
void QTableWidget::setSortingEnabled (bool enable)
Warning
This function is not part of the public interface.
Definition at line 2372 of file qtablewidget.cpp.
 {
     QTableView::setSortingEnabled(enable);
 }
setVerticalHeaderItem()
void QTableWidget::setVerticalHeaderItem (int row, QTableWidgetItem * item)
Sets the vertical header item for row row to item.
Definition at line 2159 of file qtablewidget.cpp.
Referenced by setVerticalHeaderLabels().
 {
     Q_D(QTableWidget);
     if (item) {
         item->view = this;
         d->tableModel()->setVerticalHeaderItem(row, item);
     } else {
         delete takeVerticalHeaderItem(row);
     }
 }
setVerticalHeaderLabels()
void QTableWidget::setVerticalHeaderLabels (const QStringList & labels)
Sets the vertical header labels using labels.
Definition at line 2229 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     QTableModel *model = d->tableModel();
     QTableWidgetItem *item = 0;
     for (int i = 0; i < model->rowCount() && i < labels.count(); ++i) {
         item = model->verticalHeaderItem(i);
         if (!item) {
             item = model->createItem();
             setVerticalHeaderItem(i, item);
         }
         item->setText(labels.at(i));
     }
 }
sortItems()
void QTableWidget::sortItems (int column, Qt::SortOrder order = Qt::AscendingOrder)
Sorts all the rows in the table widget based on column and order.
Definition at line 2362 of file qtablewidget.cpp.
 {
     Q_D(QTableWidget);
     d->model->sort(column, order);
     horizontalHeader()->setSortIndicator(column, order);
 }
supportedDropActions()
Qt::DropActions QTableWidget::supportedDropActions () const protected virtual
Returns the drop actions supported by this view.
See also
Qt::DropActions
Definition at line 2781 of file qtablewidget.cpp.
Referenced by QTableModel::supportedDropActions().
 {
     return d_func()->tableModel()->QAbstractTableModel::supportedDropActions() | Qt::MoveAction;
 }
takeHorizontalHeaderItem()
QTableWidgetItem * QTableWidget::takeHorizontalHeaderItem (int column)
Removes the horizontal header item at column from the header without deleting it.
Since
4.1
Definition at line 2217 of file qtablewidget.cpp.
Referenced by setHorizontalHeaderItem().
 {
     Q_D(QTableWidget);
     QTableWidgetItem *itm = d->tableModel()->takeHorizontalHeaderItem(column);
     if (itm)
         itm->view = 0;
     return itm;
 }
takeItem()
QTableWidgetItem * QTableWidget::takeItem (int row, int column)
Removes the item at row and column from the table without deleting it.
Definition at line 2138 of file qtablewidget.cpp.
Referenced by dropEvent(), and setItem().
 {
     Q_D(QTableWidget);
     QTableWidgetItem *item = d->tableModel()->takeItem(row, column);
     if (item)
         item->view = 0;
     return item;
 }
takeVerticalHeaderItem()
QTableWidgetItem * QTableWidget::takeVerticalHeaderItem (int row)
Removes the vertical header item at row from the header without deleting it.
Since
4.1
Definition at line 2177 of file qtablewidget.cpp.
Referenced by setVerticalHeaderItem().
 {
     Q_D(QTableWidget);
     QTableWidgetItem *itm = d->tableModel()->takeVerticalHeaderItem(row);
     if (itm)
         itm->view = 0;
     return itm;
 }
verticalHeaderItem()
QTableWidgetItem * QTableWidget::verticalHeaderItem (int row) const
Returns the vertical header item for row row.
Definition at line 2150 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     return d->tableModel()->verticalHeaderItem(row);
 }
visualColumn()
int QTableWidget::visualColumn (int logicalColumn) const
Returns the visual column of the given logicalColumn.
Definition at line 2585 of file qtablewidget.cpp.
 {
     return horizontalHeader()->visualIndex(logicalColumn);
 }
visualItemRect()
QRect QTableWidget::visualItemRect (const QTableWidgetItem * item) const
Returns the rectangle on the viewport occupied by the item at item.
Definition at line 2608 of file qtablewidget.cpp.
 {
     Q_D(const QTableWidget);
     if (!item)
         return QRect();
     QModelIndex index = d->tableModel()->index(const_cast<QTableWidgetItem*>(item));
     Q_ASSERT(index.isValid());
     return visualRect(index);
 }
visualRow()
int QTableWidget::visualRow (int logicalRow) const
Returns the visual row of the given logicalRow.
Definition at line 2576 of file qtablewidget.cpp.
 {
     return verticalHeader()->visualIndex(logicalRow);
 }
Friends and Related Functions
QTableModel
friend class QTableModel friend
Definition at line 226 of file qtablewidget.h.
Referenced by QTableWidget().
Properties
columnCount
int QTableWidget::columnCount private
the number of columns in the table
Returns the number of columns.
By default, for a table constructed without row and column counts, this property contains a value of 0.
Definition at line 224 of file qtablewidget.h.
rowCount
int QTableWidget::rowCount private
the number of rows in the table
Returns the number of rows.
By default, for a table constructed without row and column counts, this property contains a value of 0.
Definition at line 223 of file qtablewidget.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtablewidget.h
/src/gui/itemviews/qtablewidget.cpp