Qt 4.8: QGroupBox Class Reference
QGroupBox Class Reference
The QGroupBox widget provides a group box frame with a title.
#include <qgroupbox.h>
Public Slots
void setChecked (bool checked)
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void clicked (bool checked=false)
This signal is emitted when the check box is activated (i.
void toggled (bool)
If the group box is checkable, this signal is emitted when the check box is toggled.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
Qt::Alignment alignment () const
bool isCheckable () const
bool isChecked () const
bool isFlat () const
QSize minimumSizeHint () const
Reimplemented Function
QGroupBox (QWidget *parent=0)
Constructs a group box widget with the given parent but with no title.
QGroupBox (const QString &title, QWidget *parent=0)
Constructs a group box with the given title and parent.
void setAlignment (int alignment)
void setCheckable (bool checkable)
void setFlat (bool flat)
void setTitle (const QString &title)
QString title () const
~QGroupBox ()
Destroys the group box.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
virtual QSize sizeHint () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *event)
Reimplemented Function
void childEvent (QChildEvent *event)
This event handler can be reimplemented in a subclass to receive child events.
bool event (QEvent *event)
Reimplemented Function
void focusInEvent (QFocusEvent *event)
Reimplemented Function
void initStyleOption (QStyleOptionGroupBox *option) const
Initialize option with the values from this QGroupBox.
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
void paintEvent (QPaintEvent *event)
Reimplemented Function
void resizeEvent (QResizeEvent *event)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
Qt::Alignment alignment
the alignment of the group box title.
bool checkable
whether the group box has a checkbox in its title
bool checked
whether the group box is checked
bool flat
whether the group box is painted flat or has a frame
QString title
the group box title text
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QGroupBox widget provides a group box frame with a title.
A group box provides a frame, a title and a keyboard shortcut, and displays various other widgets inside itself. The title is on top, the keyboard shortcut moves keyboard focus to one of the group box's child widgets.
QGroupBox also lets you set the title (normally set in the constructor) and the title's alignment . Group boxes can be checkable ; child widgets in checkable group boxes are enabled or disabled depending on whether or not the group box is checked .
You can minimize the space consumption of a group box by enabling the flat property. In most styles, enabling this property results in the removal of the left, right and bottom edges of the frame.
QGroupBox doesn't automatically lay out the child widgets (which are often or QRadioButton but can be any widgets). The following example shows how we can set up a QGroupBox with a layout:
    QGroupBox *groupBox = new QGroupBox(tr("Exclusive Radio Buttons"));
    QRadioButton *radio1 = new QRadioButton(tr("&Radio button 1"));
    QRadioButton *radio2 = new QRadioButton(tr("R&adio button 2"));
    QRadioButton *radio3 = new QRadioButton(tr("Ra&dio button 3"));
    radio1->setChecked(true);
    QVBoxLayout *vbox = new QVBoxLayout;
    vbox->addWidget(radio1);
    vbox->addWidget(radio2);
    vbox->addWidget(radio3);
    vbox->addStretch(1);
    groupBox->setLayout(vbox);
Screenshot of a Windows XP style group box
Screenshot of a Macintosh style group box
Screenshot of a Plastique style group box
A Windows XP Style Widget Gallery{Windows XP style} group box. A Macintosh Style Widget Gallery{Macintosh style} group box. A Plastique Style Widget Gallery{Plastique style} group box.
See also
QButtonGroup, {Group Box Example}
Definition at line 57 of file qgroupbox.h.
Constructors and Destructors
QGroupBox() [1/2]
QGroupBox::QGroupBox (QWidget * parent = 0) explicit
Constructs a group box widget with the given parent but with no title.
Definition at line 194 of file qgroupbox.cpp.
Referenced by mouseReleaseEvent().
     : QWidget(*new QGroupBoxPrivate, parent, 0)
 {
     Q_D(QGroupBox);
     d->init();
 }
QGroupBox() [2/2]
QGroupBox::QGroupBox (const QString & title, QWidget * parent = 0) explicit
Constructs a group box with the given title and parent.
Definition at line 205 of file qgroupbox.cpp.
     : QWidget(*new QGroupBoxPrivate, parent, 0)
 {
     Q_D(QGroupBox);
     d->init();
     setTitle(title);
 }
~QGroupBox()
QGroupBox::~QGroupBox ()
Destroys the group box.
Definition at line 217 of file qgroupbox.cpp.
 {
 }
Functions
alignment()
Qt::Alignment QGroupBox::alignment () const
Referenced by setAlignment(), and setTitle().
changeEvent()
void QGroupBox::changeEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 704 of file qgroupbox.cpp.
 {
     Q_D(QGroupBox);
     if (ev->type() == QEvent::EnabledChange) {
         if (d->checkable && isEnabled()) {
             // we are being enabled - disable children
             if (!d->checked)
                 d->_q_setChildrenEnabled(false);
         }
     } else if (ev->type() == QEvent::FontChange
 #ifdef Q_WS_MAC
                || ev->type() == QEvent::MacSizeChange
 #endif
                || ev->type() == QEvent::StyleChange) {
         d->calculateFrame();
     }
     QWidget::changeEvent(ev);
 }
childEvent()
void QGroupBox::childEvent (QChildEvent *) protected virtual
This event handler can be reimplemented in a subclass to receive child events.
The event is passed in the event parameter.
QEvent::ChildAdded and QEvent::ChildRemoved events are sent to objects when children are added or removed. In both cases you can only rely on the child being a QObject, or if isWidgetType() returns true, a QWidget. (This is because, in the ChildAdded case, the child is not yet fully constructed, and in the ChildRemoved case it might have been destructed already).
QEvent::ChildPolished events are sent to widgets when children are polished, or when polished children are added. If you receive a child polished event, the child's construction is usually completed. However, this is not guaranteed, and multiple polish events may be delivered during the execution of a widget's constructor.
For every child widget, you receive one ChildAdded event, zero or more ChildPolished events, and one ChildRemoved event.
The ChildPolished event is omitted if a child is removed immediately after it is added. If a child is polished several times during construction and destruction, you may receive several child polished events for the same child, each time with a different virtual table.
See also
event()
Reimplemented from QObject.
Definition at line 410 of file qgroupbox.cpp.
 {
     Q_D(QGroupBox);
     if (c->type() != QEvent::ChildAdded || !c->child()->isWidgetType())
         return;
     QWidget *w = (QWidget*)c->child();
     if (d->checkable) {
         if (d->checked) {
             if (!w->testAttribute(Qt::WA_ForceDisabled))
                 w->setEnabled(true);
         } else {
             if (w->isEnabled()) {
                 w->setEnabled(false);
                 w->setAttribute(Qt::WA_ForceDisabled, false);
             }
         }
     }
 }
clicked
void QGroupBox::clicked (bool checked = false) signal
This signal is emitted when the check box is activated (i.
Since
4.2
e. pressed down then released while the mouse cursor is inside the button), or when the shortcut key is typed, Notably, this signal is not emitted if you call setChecked().
If the check box is checked checked is true; it is false if the check box is unchecked.
See also
checkable, toggled(), checked
event()
bool QGroupBox::event (QEvent * e) protected virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QWidget.
Definition at line 340 of file qgroupbox.cpp.
focusInEvent()
void QGroupBox::focusInEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 485 of file qgroupbox.cpp.
 { // note no call to super
     Q_D(QGroupBox);
     if (focusPolicy() == Qt::NoFocus) {
         d->_q_fixFocus(fe->reason());
     } else {
         QWidget::focusInEvent(fe);
     }
 }
initStyleOption()
void QGroupBox::initStyleOption (QStyleOptionGroupBox * option) const protected
Initialize option with the values from this QGroupBox.
This method is useful for subclasses when they need a QStyleOptionGroupBox, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom()
Definition at line 94 of file qgroupbox.cpp.
Referenced by event(), minimumSizeHint(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and paintEvent().
 {
     if (!option)
         return;
     Q_D(const QGroupBox);
     option->initFrom(this);
     option->text = d->title;
     option->lineWidth = 1;
     option->midLineWidth = 0;
     option->textAlignment = Qt::Alignment(d->align);
     option->activeSubControls |= d->pressedControl;
     option->subControls = QStyle::SC_GroupBoxFrame;
     if (d->hover)
         option->state |= QStyle::State_MouseOver;
     else
         option->state &= ~QStyle::State_MouseOver;
     if (d->flat)
         option->features |= QStyleOptionFrameV2::Flat;
     if (d->checkable) {
         option->subControls |= QStyle::SC_GroupBoxCheckBox;
         option->state |= (d->checked ? QStyle::State_On : QStyle::State_Off);
         if ((d->pressedControl == QStyle::SC_GroupBoxCheckBox
             || d->pressedControl == QStyle::SC_GroupBoxLabel) && (d->hover || d->overCheckBox))
             option->state |= QStyle::State_Sunken;
     }
     if (!option->palette.isBrushSet(isEnabled() ? QPalette::Active :
                                     QPalette::Disabled, QPalette::WindowText))
         option->textColor = QColor(style()->styleHint(QStyle::SH_GroupBox_TextLabelColor,
                                    option, this));
     if (!d->title.isEmpty())
         option->subControls |= QStyle::SC_GroupBoxLabel;
 }
isCheckable()
bool QGroupBox::isCheckable () const
Definition at line 604 of file qgroupbox.cpp.
Referenced by QAccessibleGroupBox::actionCount(), event(), and QAccessibleGroupBox::role().
 {
     Q_D(const QGroupBox);
     return d->checkable;
 }
isChecked()
bool QGroupBox::isChecked () const
Definition at line 611 of file qgroupbox.cpp.
 {
     Q_D(const QGroupBox);
     return d->checkable && d->checked;
 }
isFlat()
bool QGroupBox::isFlat () const
Definition at line 539 of file qgroupbox.cpp.
 {
     Q_D(const QGroupBox);
     return d->flat;
 }
minimumSizeHint()
QSize QGroupBox::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 499 of file qgroupbox.cpp.
 {
     Q_D(const QGroupBox);
     QStyleOptionGroupBox option;
     initStyleOption(&option);
     QFontMetrics metrics(fontMetrics());
     int baseWidth = metrics.width(d->title) + metrics.width(QLatin1Char(' '));
     int baseHeight = metrics.height();
     if (d->checkable) {
         baseWidth += style()->pixelMetric(QStyle::PM_IndicatorWidth);
         baseWidth += style()->pixelMetric(QStyle::PM_CheckBoxLabelSpacing);
         baseHeight = qMax(baseHeight, style()->pixelMetric(QStyle::PM_IndicatorHeight));
     }
     QSize size = style()->sizeFromContents(QStyle::CT_GroupBox, &option, QSize(baseWidth, baseHeight), this);
     return size.expandedTo(QWidget::minimumSizeHint());
 }
mouseMoveEvent()
void QGroupBox::mouseMoveEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 743 of file qgroupbox.cpp.
 {
     Q_D(QGroupBox);
     QStyleOptionGroupBox box;
     initStyleOption(&box);
     QStyle::SubControl pressed = style()->hitTestComplexControl(QStyle::CC_GroupBox, &box,
                                                                 event->pos(), this);
     bool oldOverCheckBox = d->overCheckBox;
     d->overCheckBox = (pressed == QStyle::SC_GroupBoxCheckBox || pressed == QStyle::SC_GroupBoxLabel);
     if (d->checkable && (d->pressedControl == QStyle::SC_GroupBoxCheckBox || d->pressedControl == QStyle::SC_GroupBoxLabel)
         && (d->overCheckBox != oldOverCheckBox))
         update(style()->subControlRect(QStyle::CC_GroupBox, &box, QStyle::SC_GroupBoxCheckBox, this));
 }
mousePressEvent()
void QGroupBox::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 724 of file qgroupbox.cpp.
 {
     if (event->button() != Qt::LeftButton) {
         event->ignore();
         return;
     }
     Q_D(QGroupBox);
     QStyleOptionGroupBox box;
     initStyleOption(&box);
     d->pressedControl = style()->hitTestComplexControl(QStyle::CC_GroupBox, &box,
                                                        event->pos(), this);
     if (d->checkable && (d->pressedControl & (QStyle::SC_GroupBoxCheckBox | QStyle::SC_GroupBoxLabel))) {
         d->overCheckBox = true;
         update(style()->subControlRect(QStyle::CC_GroupBox, &box, QStyle::SC_GroupBoxCheckBox, this));
     }
 }
mouseReleaseEvent()
void QGroupBox::mouseReleaseEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 758 of file qgroupbox.cpp.
 {
     if (event->button() != Qt::LeftButton) {
         event->ignore();
         return;
     }
     Q_D(QGroupBox);
     if (!d->overCheckBox) {
         event->ignore();
         return;
     }
     QStyleOptionGroupBox box;
     initStyleOption(&box);
     QStyle::SubControl released = style()->hitTestComplexControl(QStyle::CC_GroupBox, &box,
                                                                  event->pos(), this);
     bool toggle = d->checkable && (released == QStyle::SC_GroupBoxLabel
                                    || released == QStyle::SC_GroupBoxCheckBox);
     d->pressedControl = QStyle::SC_None;
     d->overCheckBox = false;
     if (toggle)
         d->click();
     else if (d->checkable)
         update(style()->subControlRect(QStyle::CC_GroupBox, &box, QStyle::SC_GroupBoxCheckBox, this));
 }
paintEvent()
void QGroupBox::paintEvent (QPaintEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 331 of file qgroupbox.cpp.
 {
     QStylePainter paint(this);
     QStyleOptionGroupBox option;
     initStyleOption(&option);
     paint.drawComplexControl(QStyle::CC_GroupBox, option);
 }
resizeEvent()
void QGroupBox::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 323 of file qgroupbox.cpp.
 {
     QWidget::resizeEvent(e);
 }
setAlignment()
void QGroupBox::setAlignment (int alignment)
Definition at line 313 of file qgroupbox.cpp.
 {
     Q_D(QGroupBox);
     d->align = alignment;
     updateGeometry();
     update();
 }
setCheckable()
void QGroupBox::setCheckable (bool checkable)
Definition at line 575 of file qgroupbox.cpp.
 {
     Q_D(QGroupBox);
     bool wasCheckable = d->checkable;
     d->checkable = checkable;
     if (checkable) {
         setChecked(true);
         if (!wasCheckable) {
             setFocusPolicy(Qt::StrongFocus);
             d->_q_setChildrenEnabled(true);
             updateGeometry();
         }
     } else {
         if (wasCheckable) {
             setFocusPolicy(Qt::NoFocus);
             d->_q_setChildrenEnabled(true);
             updateGeometry();
         }
         d->_q_setChildrenEnabled(true);
     }
     if (wasCheckable != checkable) {
         d->calculateFrame();
         update();
     }
 }
setChecked
void QGroupBox::setChecked (bool checked) slot
Definition at line 664 of file qgroupbox.cpp.
Referenced by QAccessibleGroupBox::doAction(), and setCheckable().
 {
     Q_D(QGroupBox);
     if (d->checkable && b != d->checked) {
         update();
         d->checked = b;
         d->_q_setChildrenEnabled(b);
 #ifndef QT_NO_ACCESSIBILITY
         QAccessible::updateAccessibility(this, 0, QAccessible::StateChanged);
 #endif
         emit toggled(b);
     }
 }
setFlat()
void QGroupBox::setFlat (bool flat)
Definition at line 545 of file qgroupbox.cpp.
 {
     Q_D(QGroupBox);
     if (d->flat == b)
         return;
     d->flat = b;
     updateGeometry();
     update();
 }
setTitle()
void QGroupBox::setTitle (const QString & title)
Definition at line 239 of file qgroupbox.cpp.
Referenced by mouseReleaseEvent(), and QGroupBox().
 {
     Q_D(QGroupBox);
     if (d->title == title)                                // no change
         return;
     d->title = title;
 #ifndef QT_NO_SHORTCUT
     releaseShortcut(d->shortcutId);
     d->shortcutId = grabShortcut(QKeySequence::mnemonic(title));
 #endif
     d->calculateFrame();
     update();
     updateGeometry();
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::NameChanged);
 #endif
 }
title()
QString QGroupBox::title () const
Referenced by mouseReleaseEvent(), and setTitle().
toggled
void QGroupBox::toggled (bool on) signal
If the group box is checkable, this signal is emitted when the check box is toggled.
on is true if the check box is checked; otherwise it is false.
See also
checkable
Referenced by setChecked().
Properties
alignment
Qt::Alignment QGroupBox::alignment private
the alignment of the group box title.
Most styles place the title at the top of the frame. The horizontal alignment of the title can be specified using single values from the following list:
Qt::AlignLeft aligns the title text with the left-hand side of the group box.
Qt::AlignRight aligns the title text with the right-hand side of the group box.
Qt::AlignHCenter aligns the title text with the horizontal center of the group box.
The default alignment is Qt::AlignLeft.
See also
Qt::Alignment
Definition at line 62 of file qgroupbox.h.
checkable
QGroupBox::checkable private
whether the group box has a checkbox in its title
If this property is true, the group box displays its title using a checkbox in place of an ordinary label. If the checkbox is checked, the group box's children are enabled; otherwise they are disabled and inaccessible.
By default, group boxes are not checkable.
If this property is enabled for a group box, it will also be initially checked to ensure that its contents are enabled.
See also
checked
Definition at line 64 of file qgroupbox.h.
Referenced by QGroupBoxPrivate::init(), and setCheckable().
checked
QGroupBox::checked private
whether the group box is checked
If the group box is checkable, it is displayed with a check box. If the check box is checked, the group box's children are enabled; otherwise the children are disabled and are inaccessible to the user.
By default, checkable group boxes are also checked.
See also
checkable
Definition at line 65 of file qgroupbox.h.
Referenced by QGroupBoxPrivate::init().
flat
QGroupBox::flat private
whether the group box is painted flat or has a frame
A group box usually consists of a surrounding frame with a title at the top. If this property is enabled, only the top part of the frame is drawn in most styles; otherwise the whole frame is drawn.
By default, this property is disabled; i.e. group boxes are not flat unless explicitly specified.
Note: In some styles, flat and non-flat group boxes have similar representations and may not be as distinguishable as they are in other styles.
See also
title
Definition at line 63 of file qgroupbox.h.
Referenced by QGroupBoxPrivate::init().
title
QString QGroupBox::title private
the group box title text
The group box title text will have a keyboard shortcut if the title contains an ampersand ('&') followed by a letter.
g->setTitle("&User information");
In the example above, Alt+U moves the keyboard focus to the group box. See the QShortcut documentation for details (to display an actual ampersand, use '&&').
There is no default title text.
See also
alignment
Definition at line 61 of file qgroupbox.h.
Referenced by buddyString(), and QAccessibleGroupBox::relationTo().
The documentation for this class was generated from the following files:
/src/gui/widgets/qgroupbox.h
/src/gui/widgets/qgroupbox.cpp