Qt 4.8: QCUPSSupport Class Reference
QCUPSSupport Class Reference
#include <qcups_p.h>
Public Functions
const cups_dest_t * availablePrinters () const
int availablePrintersCount () const
const ppd_file_t * currentPPD () const
int currentPrinterIndex () const
int markOption (const char *name, const char *value)
QStringList options () const
QRect pageRect (const char *choice) const
const ppd_option_t * pageSizes () const
QRect paperRect (const char *choice) const
const ppd_option_t * ppdOption (const char *key) const
const cups_option_t * printerOption (const QString &key) const
int printFile (const char *printerName, const char *filename, const char *title, int num_options, cups_option_t *options)
QCUPSSupport ()
void saveOptions (QList< const ppd_option_t *> options, QList< const char *> markedOptions)
const ppd_file_t * setCurrentPrinter (int index)
QPair< int, QString > tempFd ()
QString unicodeString (const char *s)
~QCUPSSupport ()
Static Public Functions
static int cupsVersion ()
static bool isAvailable ()
static bool printerHasPPD (const char *printerName)
Private Functions
void collectMarkedOptions (QStringList &list, const ppd_group_t *group=0) const
void collectMarkedOptionsHelper (QStringList &list, const ppd_group_t *group) const
Properties
QTextCodec * codec
ppd_file_t * currPPD
int currPrinterIndex
const ppd_option_t * page_sizes
cups_dest_t * printers
int prnCount
Detailed Description
Definition at line 68 of file qcups_p.h.
Constructors and Destructors
QCUPSSupport()
QCUPSSupport::QCUPSSupport ()
Definition at line 121 of file qcups.cpp.
     :
     prnCount(0),
     printers(0),
     page_sizes(0),
     currPrinterIndex(0),
     currPPD(0)
 {
     if (!cupsLoaded)
         resolveCups();
     // getting all available printers
     if (!isAvailable())
         return;
     // Update the available printer count
     qt_cups_num_printers = prnCount = _cupsGetDests(&printers);
     for (int i = 0; i <  prnCount; ++i) {
         if (printers[i].is_default) {
             currPrinterIndex = i;
             setCurrentPrinter(i);
             break;
         }
     }
 #ifndef QT_NO_TEXTCODEC
     cups_lang_t *cupsLang = _cupsLangGet(0);
     codec = QTextCodec::codecForName(_cupsLangEncoding(cupsLang));
     if (!codec)
         codec = QTextCodec::codecForLocale();
 #endif
 }
~QCUPSSupport()
QCUPSSupport::~QCUPSSupport ()
Definition at line 155 of file qcups.cpp.
 {
      if (currPPD)
         _ppdClose(currPPD);
      if (prnCount)
          _cupsFreeDests(prnCount, printers);
 }
Functions
availablePrinters()
const cups_dest_t * QCUPSSupport::availablePrinters () const
Definition at line 168 of file qcups.cpp.
Referenced by cupsVersion(), QPdfBaseEngine::QPdfBaseEngine(), qt_getLprPrinters(), and QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate().
 {
     return printers;
 }
availablePrintersCount()
int QCUPSSupport::availablePrintersCount () const
Definition at line 163 of file qcups.cpp.
Referenced by cupsVersion(), QPdfBaseEngine::QPdfBaseEngine(), qt_getLprPrinters(), and QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate().
 {
     return prnCount;
 }
collectMarkedOptions()
void QCUPSSupport::collectMarkedOptions (QStringList & list, const ppd_group_t * group = 0) const private
Definition at line 361 of file qcups.cpp.
Referenced by cupsVersion(), and options().
 {
     if (group == 0) {
         if (!currPPD)
             return;
         for (int i = 0; i < currPPD->num_groups; ++i) {
             collectMarkedOptions(list, &currPPD->groups[i]);
             collectMarkedOptionsHelper(list, &currPPD->groups[i]);
         }
     } else {
         for (int i = 0; i < group->num_subgroups; ++i)
             collectMarkedOptionsHelper(list, &group->subgroups[i]);
     }
 }
collectMarkedOptionsHelper()
void QCUPSSupport::collectMarkedOptionsHelper (QStringList & list, const ppd_group_t * group) const private
Definition at line 376 of file qcups.cpp.
Referenced by collectMarkedOptions(), and cupsVersion().
 {
     for (int i = 0; i < group->num_options; ++i) {
         for (int j = 0; j < group->options[i].num_choices; ++j) {
             if (group->options[i].choices[j].marked == 1 && qstrcmp(group->options[i].choices[j].choice, group->options[i].defchoice) != 0)
                 list << QString::fromLocal8Bit(group->options[i].keyword) << QString::fromLocal8Bit(group->options[i].choices[j].choice);
         }
     }
 }
cupsVersion()
static int QCUPSSupport::cupsVersion () inline static
Definition at line 75 of file qcups_p.h.
Referenced by QPdfBaseEnginePrivate::closePrintDevice(), QPrinter::init(), and QPrinter::setPrinterName().
 { return isAvailable() ? CUPS_VERSION_MAJOR*10000+CUPS_VERSION_MINOR*100+CUPS_VERSION_PATCH : 0; }
currentPPD()
const ppd_file_t * QCUPSSupport::currentPPD () const
Definition at line 173 of file qcups.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_printerChanged(), cupsVersion(), QPPDOptionsModel::parseItems(), QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate(), and QPageSetupWidget::setupPrinter().
 {
     return currPPD;
 }
currentPrinterIndex()
int QCUPSSupport::currentPrinterIndex () const
Definition at line 211 of file qcups.cpp.
Referenced by cupsVersion(), and QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate().
 {
     return currPrinterIndex;
 }
isAvailable()
bool QCUPSSupport::isAvailable () static
Definition at line 216 of file qcups.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_printerChanged(), cupsVersion(), QPageSetupDialogPrivate::init(), QPdfBaseEnginePrivate::openPrintDevice(), QPdfBaseEnginePrivate::pageRect(), QPdfBaseEnginePrivate::paperRect(), printerHasPPD(), QPdfBaseEngine::property(), QCUPSSupport(), QPdfBaseEngine::QPdfBaseEngine(), qt_getLprPrinters(), QUnixPrintWidgetPrivate::QUnixPrintWidgetPrivate(), QPageSetupWidget::selectPrinter(), QPrintPropertiesDialog::selectPrinter(), QUnixPrintWidgetPrivate::setCupsProperties(), and QPageSetupWidget::setupPrinter().
 {
     if(!cupsLoaded)
         resolveCups();
     return _cupsGetDests &&
         _cupsFreeDests &&
         _cupsGetPPD &&
         _ppdOpenFile &&
         _ppdMarkDefaults &&
         _ppdClose &&
         _cupsMarkOptions &&
         _ppdMarkOption &&
         _cupsFreeOptions &&
         _cupsSetDests &&
         _cupsLangGet &&
         _cupsLangEncoding &&
         _cupsAddOption &&
         (qt_cups_num_printers > 0);
 }
markOption()
int QCUPSSupport::markOption (const char * name, const char * value)
Definition at line 264 of file qcups.cpp.
Referenced by cupsVersion(), and QPPDOptionsEditor::setModelData().
 {
     return _ppdMarkOption(currPPD, name, value);
 }
options()
QStringList QCUPSSupport::options () const
Definition at line 335 of file qcups.cpp.
Referenced by cupsVersion(), printerOption(), QUnixPrintWidgetPrivate::setCupsProperties(), setCurrentPrinter(), and QPageSetupWidget::setupPrinter().
 {
     QStringList list;
     collectMarkedOptions(list);
     return list;
 }
pageRect()
QRect QCUPSSupport::pageRect (const char * choice) const
Definition at line 321 of file qcups.cpp.
Referenced by cupsVersion(), QPageSetupWidget::selectPrinter(), QUnixPrintWidgetPrivate::setCupsProperties(), and QPageSetupWidget::setupPrinter().
 {
     if (!currPPD)
         return QRect();
     for (int i = 0; i < currPPD->num_sizes; ++i) {
         if (qstrcmp(currPPD->sizes[i].name, choice) == 0)
             return QRect(qRound(currPPD->sizes[i].left),
                          qRound(currPPD->sizes[i].length - currPPD->sizes[i].top),
                          qRound(currPPD->sizes[i].right - currPPD->sizes[i].left),
                          qRound(currPPD->sizes[i].top - currPPD->sizes[i].bottom));
     }
     return QRect();
 }
pageSizes()
const ppd_option_t * QCUPSSupport::pageSizes () const
Definition at line 259 of file qcups.cpp.
Referenced by cupsVersion(), qt_getLprPrinters(), QPageSetupWidget::selectPrinter(), and QUnixPrintWidgetPrivate::setCupsProperties().
 {
     return page_sizes;
 }
paperRect()
QRect QCUPSSupport::paperRect (const char * choice) const
Definition at line 310 of file qcups.cpp.
Referenced by QPageSetupWidget::_q_paperSizeChanged(), cupsVersion(), QPageSetupWidget::selectPrinter(), QUnixPrintWidgetPrivate::setCupsProperties(), and QPageSetupWidget::setupPrinter().
 {
     if (!currPPD)
         return QRect();
     for (int i = 0; i < currPPD->num_sizes; ++i) {
         if (qstrcmp(currPPD->sizes[i].name, choice) == 0)
             return QRect(0, 0, qRound(currPPD->sizes[i].width), qRound(currPPD->sizes[i].length));
     }
     return QRect();
 }
ppdOption()
const ppd_option_t * QCUPSSupport::ppdOption (const char * key) const
Definition at line 237 of file qcups.cpp.
Referenced by cupsVersion(), QPrintDialogPrivate::selectPrinter(), and setCurrentPrinter().
 {
     if (currPPD) {
         for (int gr = 0; gr < currPPD->num_groups; ++gr) {
             for (int opt = 0; opt < currPPD->groups[gr].num_options; ++opt) {
                 if (qstrcmp(currPPD->groups[gr].options[opt].keyword, key) == 0)
                     return &currPPD->groups[gr].options[opt];
             }
         }
     }
     return 0;
 }
printerHasPPD()
bool QCUPSSupport::printerHasPPD (const char * printerName) static
Definition at line 342 of file qcups.cpp.
Referenced by cupsVersion(), and QPrinter::setPrinterName().
 {
     if (!isAvailable())
         return false;
     const char *ppdFile = _cupsGetPPD(printerName);
     if (ppdFile)
         unlink(ppdFile);
     return (ppdFile != 0);
 }
printerOption()
const cups_option_t * QCUPSSupport::printerOption (const QString & key) const
Definition at line 250 of file qcups.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_printerChanged(), and cupsVersion().
 {
     for (int i = 0; i < printers[currPrinterIndex].num_options; ++i) {
         if (QLatin1String(printers[currPrinterIndex].options[i].name) == key)
             return &printers[currPrinterIndex].options[i];
     }
     return 0;
 }
printFile()
int QCUPSSupport::printFile (const char * printerName, const char * filename, const char * title, int num_options, cups_option_t * options)
Definition at line 394 of file qcups.cpp.
Referenced by QPdfBaseEnginePrivate::closePrintDevice(), and cupsVersion().
 {
     return _cupsPrintFile(printerName, filename, title, num_options, options);
 }
saveOptions()
void QCUPSSupport::saveOptions (QList< const ppd_option_t *> options, QList< const char *> markedOptions)
Definition at line 269 of file qcups.cpp.
Referenced by cupsVersion(), and QPrintPropertiesDialog::setupPrinter().
 {
     int oldOptionCount = printers[currPrinterIndex].num_options;
     cups_option_t* oldOptions = printers[currPrinterIndex].options;
     int newOptionCount = 0;
     cups_option_t* newOptions = 0;
     // copying old options that are not on the new list
     for (int i = 0; i < oldOptionCount; ++i) {
         bool contains = false;
         for (int j = 0; j < options.count(); ++j) {
             if (qstrcmp(options.at(j)->keyword, oldOptions[i].name) == 0) {
                 contains = true;
                 break;
             }
         }
         if (!contains) {
             newOptionCount = _cupsAddOption(oldOptions[i].name, oldOptions[i].value, newOptionCount, &newOptions);
         }
     }
     // we can release old option list
      _cupsFreeOptions(oldOptionCount, oldOptions);
     // adding marked options
     for (int i = 0; i < markedOptions.count(); ++i) {
         const char* name = markedOptions.at(i);
         ++i;
         newOptionCount = _cupsAddOption(name, markedOptions.at(i), newOptionCount, &newOptions);
     }
     // placing the new option list
     printers[currPrinterIndex].num_options = newOptionCount;
     printers[currPrinterIndex].options = newOptions;
     // saving new default values
     _cupsSetDests(prnCount, printers);
 }
setCurrentPrinter()
const ppd_file_t * QCUPSSupport::setCurrentPrinter (int index)
Definition at line 178 of file qcups.cpp.
Referenced by QUnixPrintWidgetPrivate::_q_printerChanged(), cupsVersion(), QCUPSSupport(), and qt_getLprPrinters().
 {
     Q_ASSERT(index >= 0 && index <= prnCount);
     if (index == prnCount)
         return 0;
     currPrinterIndex = index;
     if (currPPD)
         _ppdClose(currPPD);
     currPPD = 0;
     page_sizes = 0;
     const char *ppdFile = _cupsGetPPD(printers[index].name);
     if (!ppdFile)
       return 0;
     currPPD = _ppdOpenFile(ppdFile);
     unlink(ppdFile);
     // marking default options
     _ppdMarkDefaults(currPPD);
     // marking options explicitly set
     _cupsMarkOptions(currPPD, printers[currPrinterIndex].num_options, printers[currPrinterIndex].options);
     // getting pointer to page sizes
     page_sizes = ppdOption("PageSize");
     return currPPD;
 }
tempFd()
QPair< int, QString > QCUPSSupport::tempFd ()
Definition at line 386 of file qcups.cpp.
Referenced by cupsVersion(), and QPdfBaseEnginePrivate::openPrintDevice().
 {
     char filename[512];
     int fd = _cupsTempFd(filename, 512);
     return QPair<int, QString>(fd, QString::fromLocal8Bit(filename));
 }
unicodeString()
QString QCUPSSupport::unicodeString (const char * s)
Definition at line 352 of file qcups.cpp.
Referenced by cupsVersion(), and QPPDOptionsModel::data().
 {
 #ifndef QT_NO_TEXTCODEC
     return codec->toUnicode(s);
 #else
     return QLatin1String(s);
 #endif
 }
Properties
codec
QTextCodec* QCUPSSupport::codec private
Definition at line 113 of file qcups_p.h.
Referenced by QCUPSSupport(), and unicodeString().
currPPD
ppd_file_t* QCUPSSupport::currPPD private
Definition at line 111 of file qcups_p.h.
Referenced by collectMarkedOptions(), currentPPD(), markOption(), pageRect(), paperRect(), ppdOption(), setCurrentPrinter(), and ~QCUPSSupport().
currPrinterIndex
int QCUPSSupport::currPrinterIndex private
Definition at line 110 of file qcups_p.h.
Referenced by currentPrinterIndex(), printerOption(), QCUPSSupport(), saveOptions(), and setCurrentPrinter().
page_sizes
const ppd_option_t* QCUPSSupport::page_sizes private
Definition at line 109 of file qcups_p.h.
Referenced by pageSizes(), and setCurrentPrinter().
printers
cups_dest_t* QCUPSSupport::printers private
Definition at line 108 of file qcups_p.h.
Referenced by availablePrinters(), printerOption(), QCUPSSupport(), saveOptions(), setCurrentPrinter(), and ~QCUPSSupport().
prnCount
int QCUPSSupport::prnCount private
Definition at line 107 of file qcups_p.h.
Referenced by availablePrintersCount(), QCUPSSupport(), saveOptions(), setCurrentPrinter(), and ~QCUPSSupport().
The documentation for this class was generated from the following files:
/src/gui/painting/qcups_p.h
/src/gui/painting/qcups.cpp