Qt 4.8: QCompletionModel Class Reference
QCompletionModel Class Reference
#include <qcompleter_p.h>
Public Slots
void invalidate ()
void modelDestroyed ()
void rowsInserted ()
Public Slots inherited from QAbstractItemModel
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void rowsAdded ()
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
int columnCount (const QModelIndex &index=QModelIndex()) const
Returns the number of columns for the children of the given parent.
int completionCount () const
void createEngine ()
QModelIndex currentIndex (bool) const
int currentRow () const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Reimplemented Function
void filter (const QStringList &parts)
bool hasChildren (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
QModelIndex index (int row, int column, const QModelIndex &=QModelIndex()) const
Returns the index of the item in the model specified by the given row, column and parent index.
QModelIndex mapFromSource (const QModelIndex &sourceIndex) const
Reimplement this function to return the model index in the proxy model that corresponds to the sourceIndex from the source model.
QModelIndex mapToSource (const QModelIndex &proxyIndex) const
Reimplement this function to return the model index in the source model that corresponds to the proxyIndex in the proxy model.
QModelIndex parent (const QModelIndex &=QModelIndex()) const
Returns the parent of the model item with the given index.
QCompletionModel (QCompleterPrivate *c, QObject *parent)
void resetModel ()
int rowCount (const QModelIndex &index=QModelIndex()) const
Returns the number of rows under the given parent.
bool setCurrentRow (int row)
void setFiltered (bool)
void setSourceModel (QAbstractItemModel *sourceModel)
Sets the given sourceModel to be processed by the proxy model.
Public Functions inherited from QAbstractProxyModel
QModelIndex buddy (const QModelIndex &index) const
Reimplemented Function
bool canFetchMore (const QModelIndex &parent) const
Reimplemented Function
void fetchMore (const QModelIndex &parent)
Reimplemented Function
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role) const
Reimplemented Function
QMap< int, QVariant > itemData (const QModelIndex &index) const
Reimplemented Function
virtual QItemSelection mapSelectionFromSource (const QItemSelection &selection) const
Returns a proxy selection mapped from the specified sourceSelection.
virtual QItemSelection mapSelectionToSource (const QItemSelection &selection) const
Returns a source selection mapped from the specified proxySelection.
QMimeData * mimeData (const QModelIndexList &indexes) const
Reimplemented Function
QStringList mimeTypes () const
Reimplemented Function
QAbstractProxyModel (QObject *parent=0)
Constructs a proxy model with the given parent.
void revert ()
Reimplemented Function
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Reimplemented Function
bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Reimplemented Function
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Reimplemented Function
QAbstractItemModel * sourceModel () const
Returns the model that contains the data that is available through the proxy model.
QSize span (const QModelIndex &index) const
Reimplemented Function
bool submit ()
Reimplemented Function
Qt::DropActions supportedDropActions () const
Reimplemented Function
~QAbstractProxyModel ()
Destroys the proxy model.
Public Functions inherited from QAbstractItemModel
virtual bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QCompleterPrivate * c
QScopedPointer< QCompletionEngine > engine
bool showAll
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractProxyModel
QAbstractProxyModel (QAbstractProxyModelPrivate &, QObject *parent)
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 213 of file qcompleter_p.h.
Constructors and Destructors
QCompletionModel()
QCompletionModel::QCompletionModel (QCompleterPrivate * c, QObject * parent)
Definition at line 163 of file qcompleter.cpp.
     : QAbstractProxyModel(*new QCompletionModelPrivate, parent),
       c(c), showAll(false)
 {
     createEngine();
 }
Functions
columnCount()
int QCompletionModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of columns for the children of the given parent.
In most subclasses, the number of columns is independent of the parent.
For example:
int DomModel::columnCount(const QModelIndex &/*parent*/) const
{
    return 3;
}
Note
When implementing a table based model, columnCount() should return 0 when the parent is valid.
See also
rowCount()
Implements QAbstractItemModel.
Definition at line 170 of file qcompleter.cpp.
Referenced by index().
 {
     Q_D(const QCompletionModel);
     return d->model->columnCount();
 }
completionCount()
int QCompletionModel::completionCount () const
Definition at line 338 of file qcompleter.cpp.
Referenced by rowCount().
 {
     if (!engine->matchCount())
         return 0;
     engine->filterOnDemand(INT_MAX);
     return engine->matchCount();
 }
createEngine()
void QCompletionModel::createEngine ()
Definition at line 200 of file qcompleter.cpp.
Referenced by QCompletionModel().
 {
     bool sortedEngine = false;
     switch (c->sorting) {
     case QCompleter::UnsortedModel:
         sortedEngine = false;
         break;
     case QCompleter::CaseSensitivelySortedModel:
         sortedEngine = c->cs == Qt::CaseSensitive;
         break;
     case QCompleter::CaseInsensitivelySortedModel:
         sortedEngine = c->cs == Qt::CaseInsensitive;
         break;
     }
     if (sortedEngine)
         engine.reset(new QSortedModelEngine(c));
     else
         engine.reset(new QUnsortedModelEngine(c));
 }
currentIndex()
QModelIndex QCompletionModel::currentIndex (bool sourceIndex) const
Definition at line 299 of file qcompleter.cpp.
 {
     if (!engine->matchCount())
         return QModelIndex();
     int row = engine->curRow;
     if (showAll)
         row = engine->curMatch.indices[engine->curRow];
     QModelIndex idx = createIndex(row, c->column);
     if (!sourceIndex)
         return idx;
     return mapToSource(idx);
 }
currentRow()
int QCompletionModel::currentRow () const inline
Definition at line 224 of file qcompleter_p.h.
 { return engine->curRow; }
data()
QVariant QCompletionModel::data (const QModelIndex & proxyIndex, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QAbstractProxyModel.
Definition at line 387 of file qcompleter.cpp.
Referenced by QUnsortedModelEngine::buildIndices().
 {
     Q_D(const QCompletionModel);
     return d->model->data(mapToSource(index), role);
 }
filter()
void QCompletionModel::filter (const QStringList & parts)
Definition at line 411 of file qcompleter.cpp.
Referenced by QCompletionEngine::filter(), and invalidate().
 {
     Q_D(QCompletionModel);
     engine->filter(parts);
     resetModel();
     if (d->model->canFetchMore(engine->curParent))
         d->model->fetchMore(engine->curParent);
 }
hasChildren()
bool QCompletionModel::hasChildren (const QModelIndex & parent = QModelIndex()) const virtual
Reimplemented Function
Since
4.8
Reimplemented from QAbstractProxyModel.
Definition at line 372 of file qcompleter.cpp.
 {
     Q_D(const QCompletionModel);
     if (parent.isValid())
         return false;
     if (showAll)
         return d->model->hasChildren(mapToSource(parent));
     if (!engine->matchCount())
         return false;
     return true;
 }
index()
QModelIndex QCompletionModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Returns the index of the item in the model specified by the given row, column and parent index.
When reimplementing this function in a subclass, call createIndex() to generate model indexes that other components can use to refer to items in your model.
See also
createIndex()
Implements QAbstractItemModel.
Definition at line 314 of file qcompleter.cpp.
 {
     Q_D(const QCompletionModel);
     if (row < 0 || column < 0 || column >= columnCount(parent) || parent.isValid())
         return QModelIndex();
     if (!showAll) {
         if (!engine->matchCount())
             return QModelIndex();
         if (row >= engine->historyMatch.indices.count()) {
             int want = row + 1 - engine->matchCount();
             if (want > 0)
                 engine->filterOnDemand(want);
             if (row >= engine->matchCount())
                 return QModelIndex();
         }
     } else {
         if (row >= d->model->rowCount(engine->curParent))
             return QModelIndex();
     }
     return createIndex(row, column);
 }
invalidate
void QCompletionModel::invalidate () slot
Definition at line 405 of file qcompleter.cpp.
Referenced by modelDestroyed(), rowsInserted(), and setSourceModel().
 {
     engine->cache.clear();
     filter(engine->curParts);
 }
mapFromSource()
QModelIndex QCompletionModel::mapFromSource (const QModelIndex & sourceIndex) const virtual
Reimplement this function to return the model index in the proxy model that corresponds to the sourceIndex from the source model.
See also
mapToSource()
Implements QAbstractProxyModel.
Definition at line 247 of file qcompleter.cpp.
 {
     if (!idx.isValid())
         return QModelIndex();
     int row = -1;
     if (!showAll) {
         if (!engine->matchCount())
             return QModelIndex();
         QIndexMapper& rootIndices = engine->historyMatch.indices;
         if (idx.parent().isValid()) {
             if (idx.parent() != engine->curParent)
                 return QModelIndex();
         } else {
             row = rootIndices.indexOf(idx.row());
             if (row == -1 && engine->curParent.isValid())
                 return QModelIndex(); // source parent and our parent don't match
         }
         if (row == -1) {
             QIndexMapper& indices = engine->curMatch.indices;
             engine->filterOnDemand(idx.row() - indices.last());
             row = indices.indexOf(idx.row()) + rootIndices.count();
         }
         if (row == -1)
             return QModelIndex();
     } else {
         if (idx.parent() != engine->curParent)
             return QModelIndex();
         row = idx.row();
     }
     return createIndex(row, idx.column());
 }
mapToSource()
QModelIndex QCompletionModel::mapToSource (const QModelIndex & proxyIndex) const virtual
Reimplement this function to return the model index in the source model that corresponds to the proxyIndex in the proxy model.
See also
mapFromSource()
Implements QAbstractProxyModel.
Definition at line 221 of file qcompleter.cpp.
Referenced by QCompleterPrivate::_q_complete(), currentIndex(), data(), and hasChildren().
 {
     Q_D(const QCompletionModel);
     if (!index.isValid())
         return engine->curParent;
     int row;
     QModelIndex parent = engine->curParent;
     if (!showAll) {
         if (!engine->matchCount())
             return QModelIndex();
         Q_ASSERT(index.row() < engine->matchCount());
         QIndexMapper& rootIndices = engine->historyMatch.indices;
         if (index.row() < rootIndices.count()) {
             row = rootIndices[index.row()];
             parent = QModelIndex();
         } else {
             row = engine->curMatch.indices[index.row() - rootIndices.count()];
         }
     } else {
         row = index.row();
     }
     return d->model->index(row, index.column(), parent);
 }
modelDestroyed
void QCompletionModel::modelDestroyed () slot
Definition at line 393 of file qcompleter.cpp.
Referenced by setSourceModel().
 {
     QAbstractProxyModel::setSourceModel(0); // switch to static empty model
     invalidate();
 }
parent()
QModelIndex QCompletionModel::parent (const QModelIndex & index = QModelIndex()) const inline virtual
Returns the parent of the model item with the given index.
Warning
This function is not part of the public interface.
If the item has no parent, an invalid QModelIndex is returned.
A common convention used in models that expose tree data structures is that only items in the first column have children. For that case, when reimplementing this function in a subclass the column of the returned QModelIndex would be 0.
When reimplementing this function in a subclass, be careful to avoid calling QModelIndex member functions, such as QModelIndex::parent(), since indexes belonging to your model will simply call your implementation, leading to infinite recursion.
See also
createIndex()
Implements QAbstractItemModel.
Definition at line 233 of file qcompleter_p.h.
 { return QModelIndex(); }
resetModel()
void QCompletionModel::resetModel ()
Definition at line 421 of file qcompleter.cpp.
Referenced by filter(), and setFiltered().
 {
     if (rowCount() == 0) {
         reset();
         return;
     }
     emit layoutAboutToBeChanged();
     QModelIndexList piList = persistentIndexList();
     QModelIndexList empty;
     for (int i = 0; i < piList.size(); i++)
         empty.append(QModelIndex());
     changePersistentIndexList(piList, empty);
     emit layoutChanged();
 }
rowCount()
int QCompletionModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of rows under the given parent.
When the parent is valid it means that rowCount is returning the number of children of parent.
Note
When implementing a table based model, rowCount() should return 0 when the parent is valid.
See also
columnCount()
Implements QAbstractItemModel.
Definition at line 347 of file qcompleter.cpp.
Referenced by resetModel(), and QSortedModelEngine::sortOrder().
 {
     Q_D(const QCompletionModel);
     if (parent.isValid())
         return 0;
     if (showAll) {
         // Show all items below current parent, even if we have no valid matches
         if (engine->curParts.count() != 1  && !engine->matchCount()
             && !engine->curParent.isValid())
             return 0;
         return d->model->rowCount(engine->curParent);
     }
     return completionCount();
 }
rowsAdded
void QCompletionModel::rowsAdded () signal
Referenced by rowsInserted().
rowsInserted
void QCompletionModel::rowsInserted () slot
Definition at line 399 of file qcompleter.cpp.
Referenced by setSourceModel().
 {
     invalidate();
     emit rowsAdded();
 }
setCurrentRow()
bool QCompletionModel::setCurrentRow (int row)
Definition at line 284 of file qcompleter.cpp.
 {
     if (row < 0 || !engine->matchCount())
         return false;
     if (row >= engine->matchCount())
         engine->filterOnDemand(row + 1 - engine->matchCount());
     if (row >= engine->matchCount()) // invalid row
         return false;
     engine->curRow = row;
     return true;
 }
setFiltered()
void QCompletionModel::setFiltered (bool filtered)
Definition at line 364 of file qcompleter.cpp.
 {
     if (showAll == !filtered)
         return;
     showAll = !filtered;
     resetModel();
 }
setSourceModel()
void QCompletionModel::setSourceModel (QAbstractItemModel * sourceModel) virtual
Sets the given sourceModel to be processed by the proxy model.
Reimplemented from QAbstractProxyModel.
Definition at line 176 of file qcompleter.cpp.
 {
     bool hadModel = (sourceModel() != 0);
     if (hadModel)
         QObject::disconnect(sourceModel(), 0, this, 0);
     QAbstractProxyModel::setSourceModel(source);
     if (source) {
         // TODO: Optimize updates in the source model
         connect(source, SIGNAL(modelReset()), this, SLOT(invalidate()));
         connect(source, SIGNAL(destroyed()), this, SLOT(modelDestroyed()));
         connect(source, SIGNAL(layoutChanged()), this, SLOT(invalidate()));
         connect(source, SIGNAL(rowsInserted(QModelIndex,int,int)), this, SLOT(rowsInserted()));
         connect(source, SIGNAL(rowsRemoved(QModelIndex,int,int)), this, SLOT(invalidate()));
         connect(source, SIGNAL(columnsInserted(QModelIndex,int,int)), this, SLOT(invalidate()));
         connect(source, SIGNAL(columnsRemoved(QModelIndex,int,int)), this, SLOT(invalidate()));
         connect(source, SIGNAL(dataChanged(QModelIndex,QModelIndex)), this, SLOT(invalidate()));
     }
     invalidate();
 }
Properties
c
QCompleterPrivate* QCompletionModel::c
Definition at line 240 of file qcompleter_p.h.
Referenced by QUnsortedModelEngine::buildIndices(), createEngine(), currentIndex(), QCompletionEngine::filter(), QSortedModelEngine::filter(), QUnsortedModelEngine::filter(), QCompletionEngine::filterHistory(), QUnsortedModelEngine::filterOnDemand(), QSortedModelEngine::indexHint(), QCompletionEngine::lookupCache(), QCompletionEngine::matchHint(), QCompletionEngine::saveInCache(), and QSortedModelEngine::sortOrder().
engine
QScopedPointer<QCompletionEngine> QCompletionModel::engine
Definition at line 241 of file qcompleter_p.h.
Referenced by QCompleterPrivate::_q_complete(), completionCount(), createEngine(), currentIndex(), filter(), hasChildren(), index(), invalidate(), mapFromSource(), mapToSource(), rowCount(), and setCurrentRow().
showAll
bool QCompletionModel::showAll
Definition at line 242 of file qcompleter_p.h.
Referenced by QCompleterPrivate::_q_complete(), currentIndex(), QCompletionEngine::filterHistory(), hasChildren(), index(), mapFromSource(), mapToSource(), rowCount(), and setFiltered().
The documentation for this class was generated from the following files:
/src/gui/util/qcompleter_p.h
/src/gui/util/qcompleter.cpp