Qt 4.8: QDeclarativeImports Class Reference
QDeclarativeImports Class Reference
The QDeclarativeImports class encapsulates one QML document's import statements.
#include <qdeclarativeimport_p.h>
Public Functions
bool addImport (QDeclarativeImportDatabase *, const QString &uri, const QString &prefix, int vmaj, int vmin, QDeclarativeScriptParser::Import::Type importType, const QDeclarativeDirComponents &qmldircomponentsnetwork, QString *errorString)
Adds information to imports such that subsequent calls to resolveType() will resolve types qualified by prefix by considering types found at the given uri.
QUrl baseUrl () const
Returns the base URL to be used for all relative file imports added.
QDeclarativeImports & operator= (const QDeclarativeImports &)
void populateCache (QDeclarativeTypeNameCache *cache, QDeclarativeEngine *) const
QDeclarativeImports ()
QDeclarativeImports (QDeclarativeTypeLoader *)
QDeclarativeImports (const QDeclarativeImports &)
bool resolveType (const QByteArray &type, QDeclarativeType **type_return, QUrl *url_return, int *version_major, int *version_minor, QDeclarativeImportedNamespace **ns_return, QString *errorString=0) const
The given (namespace qualified) type is resolved to either.
bool resolveType (QDeclarativeImportedNamespace *, const QByteArray &type, QDeclarativeType **type_return, QUrl *url_return, int *version_major, int *version_minor) const
Searching only in the namespace ns (previously returned in a call to resolveType(), type is found and returned to either a QDeclarativeType stored at type_return, or a component located at url_return.
void setBaseUrl (const QUrl &url)
Sets the base URL to be used for all relative file imports added.
~QDeclarativeImports ()
Properties
QDeclarativeImportsPrivate * d
Friends
class QDeclarativeImportDatabase
Detailed Description
The QDeclarativeImports class encapsulates one QML document's import statements.
Warning
This function is not part of the public interface.
Definition at line 73 of file qdeclarativeimport_p.h.
Constructors and Destructors
QDeclarativeImports() [1/3]
QDeclarativeImports::QDeclarativeImports ()
Definition at line 142 of file qdeclarativeimport.cpp.
     : d(new QDeclarativeImportsPrivate(0)){
 }
QDeclarativeImports() [2/3]
QDeclarativeImports::QDeclarativeImports (QDeclarativeTypeLoader * typeLoader)
Definition at line 146 of file qdeclarativeimport.cpp.
     : d(new QDeclarativeImportsPrivate(typeLoader)){
 }
QDeclarativeImports() [3/3]
QDeclarativeImports::QDeclarativeImports (const QDeclarativeImports & copy)
Definition at line 126 of file qdeclarativeimport.cpp.
 : d(copy.d)
 {
     ++d->ref;
 }
~QDeclarativeImports()
QDeclarativeImports::~QDeclarativeImports ()
Definition at line 150 of file qdeclarativeimport.cpp.
 {
     if (--d->ref == 0)
         delete d;
 }
Functions
addImport()
bool QDeclarativeImports::addImport (QDeclarativeImportDatabase * importDb, const QString & uri, const QString & prefix, int vmaj, int vmin, QDeclarativeScriptParser::Import::Type importType, const QDeclarativeDirComponents & qmldircomponentsnetwork, QString * errorString)
Adds information to imports such that subsequent calls to resolveType() will resolve types qualified by prefix by considering types found at the given uri.
Warning
This function is not part of the public interface.
The uri is either a directory (if importType is FileImport), or a URI resolved using paths added via addImportPath() (if importType is LibraryImport).
The prefix may be empty, in which case the import location is considered for unqualified types.
The base URL must already have been set with Import::setBaseUrl().
Definition at line 827 of file qdeclarativeimport.cpp.
Referenced by QDeclarativeTypeData::resolveTypes().
 {
     if (qmlImportTrace())
         qDebug().nospace() << "QDeclarativeImports(" << qPrintable(baseUrl().toString()) << ")" << "::addImport: "
                            << uri << " " << vmaj << '.' << vmin << " "
                            << (importType==QDeclarativeScriptParser::Import::Library? "Library" : "File")
                            << " as " << prefix;
     return d->add(qmldircomponentsnetwork, uri, prefix, vmaj, vmin, importType, importDb, errorString);
 }
baseUrl()
QUrl QDeclarativeImports::baseUrl () const
Returns the base URL to be used for all relative file imports added.
Definition at line 167 of file qdeclarativeimport.cpp.
Referenced by QDeclarativeTypeData::compile(), resolveType(), and QDeclarativeTypeData::resolveTypes().
 {
     return d->base;
 }
operator=()
QDeclarativeImports & QDeclarativeImports::operator= (const QDeclarativeImports & copy)
Definition at line 133 of file qdeclarativeimport.cpp.
 {
     ++copy.d->ref;
     if (--d->ref == 0)
         delete d;
     d = copy.d;
     return *this;
 }
populateCache()
void QDeclarativeImports::populateCache (QDeclarativeTypeNameCache * cache, QDeclarativeEngine * engine) const
Definition at line 201 of file qdeclarativeimport.cpp.
Referenced by QDeclarativeCompiler::compileTree().
 {
     const QDeclarativeImportedNamespace &set = d->unqualifiedset;
     for (QHash<QString,QDeclarativeImportedNamespace* >::ConstIterator iter = d->set.begin();
          iter != d->set.end(); ++iter) {
         QDeclarativeTypeNameCache::Data *d = cache->data(iter.key());
         if (d) {
             if (!d->typeNamespace)
                 cacheForNamespace(engine, *(*iter), d->typeNamespace);
         } else {
             QDeclarativeTypeNameCache *nc = cacheForNamespace(engine, *(*iter), 0);
             cache->add(iter.key(), nc);
             nc->release();
         }
     }
     cacheForNamespace(engine, set, cache);
 }
resolveType() [1/2]
bool QDeclarativeImports::resolveType (const QByteArray & type, QDeclarativeType ** type_return, QUrl * url_return, int * vmaj, int * vmin, QDeclarativeImportedNamespace ** ns_return, QString * errorString = 0) const
The given (namespace qualified) type is resolved to either.
a QDeclarativeImportedNamespace stored at ns_return,
a QDeclarativeType stored at type_return, or
a component located at url_return.
Warning
This function is not part of the public interface.
If any return pointer is 0, the corresponding search is not done.
See also
addImport()
Definition at line 239 of file qdeclarativeimport.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeCompiler::buildProperty(), QDeclarativeCompiler::buildPropertyInNamespace(), QDeclarativeCompiler::evaluateEnum(), QDeclarativeCompiler::resolveType(), QDeclarativeTypeData::resolveTypes(), and QDeclarativeCompiler::testQualifiedEnumAssignment().
 {
     QDeclarativeImportedNamespace* ns = d->findNamespace(QString::fromUtf8(type));
     if (ns) {
         if (ns_return)
             *ns_return = ns;
         return true;
     }
     if (type_return || url_return) {
         if (d->find(type,vmaj,vmin,type_return,url_return, errorString)) {
             if (qmlImportTrace()) {
                 if (type_return && *type_return && url_return && !url_return->isEmpty())
                     qDebug().nospace() << "QDeclarativeImports(" << qPrintable(baseUrl().toString()) << ")" << "::resolveType: "
                                        << type << " => " << (*type_return)->typeName() << " " << *url_return;
                 if (type_return && *type_return)
                     qDebug().nospace() << "QDeclarativeImports(" << qPrintable(baseUrl().toString()) << ")" << "::resolveType: "
                                        << type << " => " << (*type_return)->typeName();
                 if (url_return && !url_return->isEmpty())
                     qDebug().nospace() << "QDeclarativeImports(" << qPrintable(baseUrl().toString()) << ")" << "::resolveType: "
                                        << type << " => " << *url_return;
             }
             return true;
         }
     }
     return false;
 }
resolveType() [2/2]
bool QDeclarativeImports::resolveType (QDeclarativeImportedNamespace * ns, const QByteArray & type, QDeclarativeType ** type_return, QUrl * url_return, int * vmaj, int * vmin) const
Searching only in the namespace ns (previously returned in a call to resolveType(), type is found and returned to either a QDeclarativeType stored at type_return, or a component located at url_return.
Warning
This function is not part of the public interface.
If either return pointer is 0, the corresponding search is not done.
Definition at line 281 of file qdeclarativeimport.cpp.
 {
     Q_ASSERT(d->typeLoader);
     return ns->find(d->typeLoader,type,vmaj,vmin,type_return,url_return);
 }
setBaseUrl()
void QDeclarativeImports::setBaseUrl (const QUrl & url)
Sets the base URL to be used for all relative file imports added.
Definition at line 159 of file qdeclarativeimport.cpp.
Referenced by QDeclarativeTypeData::dataReceived().
 {
     d->base = url;
 }
Friends and Related Functions
QDeclarativeImportDatabase
friend class QDeclarativeImportDatabase friend
Definition at line 104 of file qdeclarativeimport_p.h.
Properties
d
QDeclarativeImportsPrivate* QDeclarativeImports::d private
Definition at line 105 of file qdeclarativeimport_p.h.
Referenced by baseUrl(), operator=(), populateCache(), QDeclarativeImports(), resolveType(), setBaseUrl(), and ~QDeclarativeImports().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeimport_p.h
/src/declarative/qml/qdeclarativeimport.cpp