Qt 4.8: QHttpNetworkHeaderPrivate Class Reference
QHttpNetworkHeaderPrivate Class Reference
#include <qhttpnetworkheader_p.h>
Public Functions
qint64 contentLength () const
QByteArray headerField (const QByteArray &name, const QByteArray &defaultValue=QByteArray()) const
QList< QByteArray > headerFieldValues (const QByteArray &name) const
bool operator== (const QHttpNetworkHeaderPrivate &other) const
QHttpNetworkHeaderPrivate (const QUrl &newUrl=QUrl())
QHttpNetworkHeaderPrivate (const QHttpNetworkHeaderPrivate &other)
void setContentLength (qint64 length)
void setHeaderField (const QByteArray &name, const QByteArray &data)
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Variables
QList< QPair< QByteArray, QByteArray > > fields
QUrl url
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Definition at line 80 of file qhttpnetworkheader_p.h.
Constructors and Destructors
QHttpNetworkHeaderPrivate() [1/2]
QHttpNetworkHeaderPrivate::QHttpNetworkHeaderPrivate (const QUrl & newUrl = QUrl())
Definition at line 48 of file qhttpnetworkheader.cpp.
     :url(newUrl)
 {
 }
QHttpNetworkHeaderPrivate() [2/2]
QHttpNetworkHeaderPrivate::QHttpNetworkHeaderPrivate (const QHttpNetworkHeaderPrivate & other)
Definition at line 53 of file qhttpnetworkheader.cpp.
     :QSharedData(other)
 {
     url = other.url;
     fields = other.fields;
 }
Functions
contentLength()
qint64 QHttpNetworkHeaderPrivate::contentLength () const
Definition at line 60 of file qhttpnetworkheader.cpp.
Referenced by QHttpNetworkRequest::contentLength(), QHttpNetworkReplyPrivate::expectContent(), and QHttpNetworkReplyPrivate::readHeader().
 {
     bool ok = false;
     // We are not using the headerField() method here because servers might send us multiple content-length
     // headers which is crap (see QTBUG-15311). Therefore just take the first content-length header field.
     QByteArray value;
     QList<QPair<QByteArray, QByteArray> >::ConstIterator it = fields.constBegin(),
                                                         end = fields.constEnd();
     for ( ; it != end; ++it)
         if (qstricmp("content-length", it->first) == 0) {
             value = it->second;
             break;
         }
     qint64 length = value.toULongLong(&ok);
     if (ok)
         return length;
     return -1; // the header field is not set
 }
headerField()
QByteArray QHttpNetworkHeaderPrivate::headerField (const QByteArray & name, const QByteArray & defaultValue = QByteArray()) const
Definition at line 85 of file qhttpnetworkheader.cpp.
Referenced by QHttpNetworkRequest::headerField(), QHttpNetworkReplyPrivate::isGzipped(), and QHttpNetworkReplyPrivate::readHeader().
 {
     QList<QByteArray> allValues = headerFieldValues(name);
     if (allValues.isEmpty())
         return defaultValue;
     QByteArray result;
     bool first = true;
     foreach (const QByteArray &value, allValues) {
         if (!first)
             result += ", ";
         first = false;
         result += value;
     }
     return result;
 }
headerFieldValues()
QList< QByteArray > QHttpNetworkHeaderPrivate::headerFieldValues (const QByteArray & name) const
Definition at line 102 of file qhttpnetworkheader.cpp.
Referenced by QHttpNetworkReplyPrivate::authenticationMethod(), QHttpNetworkReplyPrivate::findChallenge(), and headerField().
 {
     QList<QByteArray> result;
     QList<QPair<QByteArray, QByteArray> >::ConstIterator it = fields.constBegin(),
                                                         end = fields.constEnd();
     for ( ; it != end; ++it)
         if (qstricmp(name.constData(), it->first) == 0)
             result += it->second;
     return result;
 }
operator==()
bool QHttpNetworkHeaderPrivate::operator== (const QHttpNetworkHeaderPrivate & other) const
Definition at line 126 of file qhttpnetworkheader.cpp.
Referenced by QHttpNetworkRequestPrivate::operator==().
 {
    return (url == other.url);
 }
setContentLength()
void QHttpNetworkHeaderPrivate::setContentLength (qint64 length)
Definition at line 80 of file qhttpnetworkheader.cpp.
Referenced by QHttpNetworkRequest::setContentLength().
 {
     setHeaderField("Content-Length", QByteArray::number(length));
 }
setHeaderField()
void QHttpNetworkHeaderPrivate::setHeaderField (const QByteArray & name, const QByteArray & data)
Definition at line 114 of file qhttpnetworkheader.cpp.
Referenced by setContentLength(), and QHttpNetworkRequest::setHeaderField().
 {
     QList<QPair<QByteArray, QByteArray> >::Iterator it = fields.begin();
     while (it != fields.end()) {
         if (qstricmp(name.constData(), it->first) == 0)
             it = fields.erase(it);
         else
             ++it;
     }
     fields.append(qMakePair(name, data));
 }
Properties
fields
QList<QPair<QByteArray, QByteArray> > QHttpNetworkHeaderPrivate::fields
Definition at line 84 of file qhttpnetworkheader_p.h.
Referenced by QHttpNetworkReplyPrivate::clearHttpLayerInformation(), contentLength(), QHttpNetworkRequest::header(), QHttpNetworkRequestPrivate::header(), headerFieldValues(), QHttpNetworkReplyPrivate::parseHeader(), QHttpNetworkHeaderPrivate(), QHttpNetworkReplyPrivate::removeAutoDecompressHeader(), and setHeaderField().
url
QUrl QHttpNetworkHeaderPrivate::url
Definition at line 83 of file qhttpnetworkheader_p.h.
Referenced by QHttpNetworkRequestPrivate::header(), operator==(), QHttpNetworkHeaderPrivate(), QHttpNetworkRequest::setUrl(), QHttpNetworkRequestPrivate::uri(), and QHttpNetworkRequest::url().
The documentation for this class was generated from the following files:
/src/network/access/qhttpnetworkheader_p.h
/src/network/access/qhttpnetworkheader.cpp