Qt 4.8: QScriptBreakpointData Class Reference
QScriptBreakpointData Class Reference
The QScriptBreakpointData class contains data associated with a breakpoint.
#include <qscriptbreakpointdata_p.h>
Public Functions
QString condition () const
Returns the condition of the breakpoint.
QVariant data () const
Returns custom data associated with the breakpoint.
QString fileName () const
bool hit ()
If the ignore count is 0, this function increments the hit count and returns true.
int hitCount () const
Returns the hit count of the breakpoint (the number of times the breakpoint has been triggered).
int ignoreCount () const
Returns the ignore count of the breakpoint.
bool isEnabled () const
Returns true if the breakpoint is enabled, false otherwise.
bool isSingleShot () const
Returns true if the breakpoint is single-shot, false otherwise.
bool isValid () const
int lineNumber () const
Returns the breakpoint line number.
bool operator!= (const QScriptBreakpointData &other) const
Returns true if this QScriptBreakpointData is not equal to the other data, otherwise returns false.
QScriptBreakpointData & operator= (const QScriptBreakpointData &other)
Assigns other to this QScriptBreakpointData.
bool operator== (const QScriptBreakpointData &other) const
Returns true if this QScriptBreakpointData is equal to the other data, otherwise returns false.
QScriptBreakpointData ()
Constructs an empty QScriptBreakpointData.
QScriptBreakpointData (qint64 scriptId, int lineNumber)
Constructs a QScriptBreakpointData with the given lineNumber.
QScriptBreakpointData (const QString &fileName, int lineNumber)
Constructs a QScriptBreakpointData with the given lineNumber.
QScriptBreakpointData (const QScriptBreakpointData &other)
Constructs a QScriptBreakpointData that is a copy of other.
qint64 scriptId () const
void setCondition (const QString &condition)
Sets the condition of the breakpoint.
void setData (const QVariant &data)
Sets custom data associated with the breakpoint.
void setEnabled (bool enabled)
Sets the enabled state of the breakpoint.
void setFileName (const QString &fileName)
void setIgnoreCount (int count)
Sets the ignore count of the breakpoint.
void setLineNumber (int lineNumber)
Sets the breakpoint line number to lineNumber.
void setScriptId (qint64 id)
void setSingleShot (bool singleShot)
Sets the singleShot state of the breakpoint.
~QScriptBreakpointData ()
Destroys this QScriptBreakpointData.
Properties
QScopedPointer< QScriptBreakpointDataPrivate > d_ptr
Friends
Q_AUTOTEST_EXPORT QDataStream & operator<< (QDataStream &, const QScriptBreakpointData &)
Writes the given data to the specified stream.
Q_AUTOTEST_EXPORT QDataStream & operator>> (QDataStream &, QScriptBreakpointData &)
Reads a QScriptBreakpointData from the specified stream into the given data.
Detailed Description
The QScriptBreakpointData class contains data associated with a breakpoint.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 66 of file qscriptbreakpointdata_p.h.
Constructors and Destructors
QScriptBreakpointData() [1/4]
QScriptBreakpointData::QScriptBreakpointData ()
Constructs an empty QScriptBreakpointData.
Definition at line 101 of file qscriptbreakpointdata.cpp.
     : d_ptr(new QScriptBreakpointDataPrivate)
 {
     d_ptr->init(/*lineNumber=*/-1);
 }
QScriptBreakpointData() [2/4]
QScriptBreakpointData::QScriptBreakpointData (qint64 scriptId, int lineNumber)
Constructs a QScriptBreakpointData with the given lineNumber.
Definition at line 110 of file qscriptbreakpointdata.cpp.
     : d_ptr(new QScriptBreakpointDataPrivate)
 {
     d_ptr->init(lineNumber);
     d_ptr->scriptId = scriptId;
 }
QScriptBreakpointData() [3/4]
QScriptBreakpointData::QScriptBreakpointData (const QString & fileName, int lineNumber)
Constructs a QScriptBreakpointData with the given lineNumber.
Definition at line 120 of file qscriptbreakpointdata.cpp.
     : d_ptr(new QScriptBreakpointDataPrivate)
 {
     d_ptr->init(lineNumber);
     d_ptr->fileName = fileName;
 }
QScriptBreakpointData() [4/4]
QScriptBreakpointData::QScriptBreakpointData (const QScriptBreakpointData & other)
Constructs a QScriptBreakpointData that is a copy of other.
Definition at line 130 of file qscriptbreakpointdata.cpp.
     : d_ptr(new QScriptBreakpointDataPrivate)
 {
     Q_ASSERT(other.d_ptr != 0);
     *d_ptr = *other.d_ptr;
 }
~QScriptBreakpointData()
QScriptBreakpointData::~QScriptBreakpointData ()
Destroys this QScriptBreakpointData.
Definition at line 140 of file qscriptbreakpointdata.cpp.
 {
 }
Functions
condition()
QString QScriptBreakpointData::condition () const
Returns the condition of the breakpoint.
Definition at line 280 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataToScriptValue(), QScriptBreakpointsModel::data(), QScriptDebuggerAgent::positionChange(), and setCondition().
 {
     Q_D(const QScriptBreakpointData);
     return d->condition;
 }
data()
QVariant QScriptBreakpointData::data () const
Returns custom data associated with the breakpoint.
Definition at line 298 of file qscriptbreakpointdata.cpp.
Referenced by setData().
 {
     Q_D(const QScriptBreakpointData);
     return d->data;
 }
fileName()
QString QScriptBreakpointData::fileName () const
Definition at line 167 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsAboutToBeRemoved(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsDataChanged(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsInserted(), breakpointDataToScriptValue(), QScriptBreakpointsModel::data(), QScriptBreakpointData(), QScriptDebuggerAgent::setBreakpoint(), and setFileName().
 {
     Q_D(const QScriptBreakpointData);
     return d->fileName;
 }
hit()
bool QScriptBreakpointData::hit ()
If the ignore count is 0, this function increments the hit count and returns true.
Otherwise, it decrements the ignore count and returns false.
Definition at line 256 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerAgent::positionChange().
 {
     Q_D(QScriptBreakpointData);
     if (d->ignoreCount == 0) {
         ++d->hitCount;
         return true;
     }
     --d->ignoreCount;
     return false;
 }
hitCount()
int QScriptBreakpointData::hitCount () const
Returns the hit count of the breakpoint (the number of times the breakpoint has been triggered).
Definition at line 271 of file qscriptbreakpointdata.cpp.
Referenced by QScriptBreakpointsModel::data().
 {
     Q_D(const QScriptBreakpointData);
     return d->hitCount;
 }
ignoreCount()
int QScriptBreakpointData::ignoreCount () const
Returns the ignore count of the breakpoint.
Definition at line 236 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataToScriptValue(), and QScriptBreakpointsModel::data().
 {
     Q_D(const QScriptBreakpointData);
     return d->ignoreCount;
 }
isEnabled()
bool QScriptBreakpointData::isEnabled () const
Returns true if the breakpoint is enabled, false otherwise.
Definition at line 200 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsDataChanged(), breakpointDataToScriptValue(), QScriptBreakpointsModel::data(), and QScriptDebuggerAgent::positionChange().
 {
     Q_D(const QScriptBreakpointData);
     return d->enabled;
 }
isSingleShot()
bool QScriptBreakpointData::isSingleShot () const
Returns true if the breakpoint is single-shot, false otherwise.
Definition at line 218 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataToScriptValue(), QScriptBreakpointsModel::data(), and QScriptDebuggerPrivate::debuggerEvent().
 {
     Q_D(const QScriptBreakpointData);
     return d->singleShot;
 }
isValid()
bool QScriptBreakpointData::isValid () const
Definition at line 313 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerCommandExecutor::execute(), QScriptDebuggerBackend::setBreakpoint(), and QScriptBreakpointsModel::setData().
 {
     Q_D(const QScriptBreakpointData);
     return (((d->scriptId != -1) || !d->fileName.isEmpty())
             && (d->lineNumber != -1));
 }
lineNumber()
int QScriptBreakpointData::lineNumber () const
Returns the breakpoint line number.
Definition at line 182 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsAboutToBeRemoved(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsDataChanged(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsInserted(), breakpointDataToScriptValue(), QScriptBreakpointsModel::data(), QScriptDebuggerAgent::positionChange(), and setLineNumber().
 {
     Q_D(const QScriptBreakpointData);
     return d->lineNumber;
 }
operator!=()
bool QScriptBreakpointData::operator!= (const QScriptBreakpointData & other) const
Returns true if this QScriptBreakpointData is not equal to the other data, otherwise returns false.
Definition at line 347 of file qscriptbreakpointdata.cpp.
 {
     return !(*this == other);
 }
operator=()
QScriptBreakpointData & QScriptBreakpointData::operator= (const QScriptBreakpointData & other)
Assigns other to this QScriptBreakpointData.
Definition at line 147 of file qscriptbreakpointdata.cpp.
 {
     Q_ASSERT(d_ptr != 0);
     Q_ASSERT(other.d_ptr != 0);
     *d_ptr = *other.d_ptr;
     return *this;
 }
operator==()
bool QScriptBreakpointData::operator== (const QScriptBreakpointData & other) const
Returns true if this QScriptBreakpointData is equal to the other data, otherwise returns false.
Definition at line 324 of file qscriptbreakpointdata.cpp.
 {
     Q_D(const QScriptBreakpointData);
     const QScriptBreakpointDataPrivate *od = other.d_func();
     if (d == od)
         return true;
     if (!d || !od)
         return false;
     return ((d->scriptId == od->scriptId)
             && (d->fileName == od->fileName)
             && (d->lineNumber == od->lineNumber)
             && (d->enabled == od->enabled)
             && (d->singleShot == od->singleShot)
             && (d->condition == od->condition)
             && (d->ignoreCount == od->ignoreCount)
             && (d->data == od->data)
             && (d->hitCount == od->hitCount));
 }
scriptId()
qint64 QScriptBreakpointData::scriptId () const
Definition at line 155 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsAboutToBeRemoved(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsDataChanged(), QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointsInserted(), breakpointDataToScriptValue(), QScriptBreakpointsModel::data(), QScriptBreakpointData(), and QScriptDebuggerAgent::setBreakpoint().
 {
     Q_D(const QScriptBreakpointData);
     return d->scriptId;
 }
setCondition()
void QScriptBreakpointData::setCondition (const QString & condition)
Sets the condition of the breakpoint.
Definition at line 289 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataFromScriptValue(), and QScriptBreakpointsModel::setData().
 {
     Q_D(QScriptBreakpointData);
     d->condition = condition;
 }
setData()
void QScriptBreakpointData::setData (const QVariant & data)
Sets custom data associated with the breakpoint.
Definition at line 307 of file qscriptbreakpointdata.cpp.
 {
     Q_D(QScriptBreakpointData);
     d->data = data;
 }
setEnabled()
void QScriptBreakpointData::setEnabled (bool enabled)
Sets the enabled state of the breakpoint.
Definition at line 209 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointEnableRequest(), breakpointDataFromScriptValue(), and QScriptBreakpointsModel::setData().
 {
     Q_D(QScriptBreakpointData);
     d->enabled = enabled;
 }
setFileName()
void QScriptBreakpointData::setFileName (const QString & fileName)
Definition at line 173 of file qscriptbreakpointdata.cpp.
Referenced by QScriptDebuggerCodeWidgetPrivate::_q_onBreakpointToggleRequest(), QScriptDebuggerPrivate::_q_toggleBreakpoint(), and breakpointDataFromScriptValue().
 {
     Q_D(QScriptBreakpointData);
     d->fileName = fileName;
 }
setIgnoreCount()
void QScriptBreakpointData::setIgnoreCount (int count)
Sets the ignore count of the breakpoint.
Definition at line 245 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataFromScriptValue(), and QScriptBreakpointsModel::setData().
 {
     Q_D(QScriptBreakpointData);
     d->ignoreCount = count;
 }
setLineNumber()
void QScriptBreakpointData::setLineNumber (int lineNumber)
Sets the breakpoint line number to lineNumber.
Definition at line 191 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataFromScriptValue().
 {
     Q_D(QScriptBreakpointData);
     d->lineNumber = lineNumber;
 }
setScriptId()
void QScriptBreakpointData::setScriptId (qint64 id)
Definition at line 161 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataFromScriptValue().
 {
     Q_D(QScriptBreakpointData);
     d->scriptId = id;
 }
setSingleShot()
void QScriptBreakpointData::setSingleShot (bool singleShot)
Sets the singleShot state of the breakpoint.
Definition at line 227 of file qscriptbreakpointdata.cpp.
Referenced by breakpointDataFromScriptValue(), and QScriptBreakpointsModel::setData().
 {
     Q_D(QScriptBreakpointData);
     d->singleShot = singleShot;
 }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & out, const QScriptBreakpointData & data) friend
Writes the given data to the specified stream.
Definition at line 361 of file qscriptbreakpointdata.cpp.
 {
     const QScriptBreakpointDataPrivate *d = data.d_ptr.data();
     out << d->scriptId;
     out << d->fileName;
     out << d->lineNumber;
     out << d->enabled;
     out << d->singleShot;
     out << d->ignoreCount;
     out << d->condition;
     out << d->data;
     out << d->hitCount;
     return out;
 }
operator>>
QDataStream & operator>> (QDataStream & in, QScriptBreakpointData & data) friend
Reads a QScriptBreakpointData from the specified stream into the given data.
Definition at line 386 of file qscriptbreakpointdata.cpp.
 {
     QScriptBreakpointDataPrivate *d = data.d_ptr.data();
     in >> d->scriptId;
     in >> d->fileName;
     in >> d->lineNumber;
     in >> d->enabled;
     in >> d->singleShot;
     in >> d->ignoreCount;
     in >> d->condition;
     in >> d->data;
     in >> d->hitCount;
     return in;
 }
Properties
d_ptr
QScopedPointer<QScriptBreakpointDataPrivate> QScriptBreakpointData::d_ptr private
Definition at line 117 of file qscriptbreakpointdata_p.h.
Referenced by operator<<(), operator=(), operator>>(), and QScriptBreakpointData().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptbreakpointdata_p.h
/src/scripttools/debugging/qscriptbreakpointdata.cpp