Qt 4.8: QXcbObject Class Reference
QXcbObject Class Reference
#include <qxcbobject.h>
Public Functions
xcb_atom_t atom (QXcbAtom::Atom atom) const
QXcbConnection * connection () const
QXcbObject (QXcbConnection *connection=0)
void setConnection (QXcbConnection *connection)
xcb_connection_t * xcb_connection () const
Properties
QXcbConnection * m_connection
Detailed Description
Definition at line 47 of file qxcbobject.h.
Constructors and Destructors
QXcbObject()
QXcbObject::QXcbObject (QXcbConnection * connection = 0) inline
Definition at line 50 of file qxcbobject.h.
 : m_connection(connection) {}
Functions
atom()
xcb_atom_t QXcbObject::atom (QXcbAtom::Atom atom) const inline
Definition at line 55 of file qxcbobject.h.
Referenced by QXcbWindow::handleClientMessageEvent(), QXcbScreen::QXcbScreen(), QXcbWindow::QXcbWindow(), QXcbWindow::setNetWmWindowTypes(), QXcbWindow::setWindowFlags(), and QXcbWindow::setWindowTitle().
 { return m_connection->atom(atom); }
connection()
QXcbConnection* QXcbObject::connection () const inline
Definition at line 53 of file qxcbobject.h.
Referenced by QXcbNativeInterface::displayForWidget(), QGLXContext::doneCurrent(), QXcbNativeInterface::eglDisplayForWidget(), QXcbWindowSurface::flush(), QGLXContext::getProcAddress(), QXcbWindow::glContext(), QXcbNativeInterface::graphicsDeviceForWidget(), QXcbKeyboard::handleKeyEvent(), QGLXContext::makeCurrent(), QXcbShmImage::preparePaint(), QXcbShmImage::put(), QGLXContext::QGLXContext(), QXcbShmImage::QXcbShmImage(), QXcbWindow::QXcbWindow(), QXcbWindowSurface::QXcbWindowSurface(), QXcbWindow::requestActivateWindow(), QXcbWindowSurface::resize(), setConnection(), QXcbWindow::setVisible(), QGLXContext::swapBuffers(), QXcbWindow::updateSyncRequestCounter(), and QGLXContext::~QGLXContext().
 { return m_connection; }
setConnection()
void QXcbObject::setConnection (QXcbConnection * connection) inline
Definition at line 52 of file qxcbobject.h.
Referenced by QXcbWindow::QXcbWindow(), and QXcbWindowSurface::QXcbWindowSurface().
 { m_connection = connection; }
xcb_connection()
xcb_connection_t* QXcbObject::xcb_connection () const inline
Definition at line 56 of file qxcbobject.h.
Referenced by QXcbNativeInterface::connectionForWidget(), QXcbShmImage::destroy(), QXcbWindowSurface::flush(), QXcbWindow::handleClientMessageEvent(), QXcbWindow::lower(), QXcbShmImage::put(), QXcbKeyboard::QXcbKeyboard(), QXcbScreen::QXcbScreen(), QXcbShmImage::QXcbShmImage(), QXcbWindow::QXcbWindow(), QXcbWindow::raise(), QXcbWindow::requestActivateWindow(), QXcbWindow::setGeometry(), QXcbWindow::setNetWmWindowTypes(), QXcbWindow::setParent(), QXcbWindow::setVisible(), QXcbWindow::setWindowFlags(), QXcbWindow::setWindowTitle(), QXcbWindow::updateSyncRequestCounter(), QDri2ContextPrivate::xcbConnection(), and QXcbWindow::~QXcbWindow().
 { return m_connection->xcb_connection(); }
Properties
m_connection
QXcbConnection* QXcbObject::m_connection private
Definition at line 59 of file qxcbobject.h.
Referenced by atom(), connection(), setConnection(), and xcb_connection().
The documentation for this class was generated from the following file:
/src/plugins/platforms/xcb/qxcbobject.h