Qt 4.8: QGLShader Class Reference
QGLShader Class Reference
The QGLShader class allows OpenGL shaders to be compiled.
#include <qglshaderprogram.h>
Public Types
enum ShaderTypeBit { Vertex = 0x0001, Fragment = 0x0002, Geometry = 0x0004 }
This enum specifies the type of QGLShader that is being created.
Public Functions
bool compileSourceCode (const char *source)
Sets the source code for this shader and compiles it.
bool compileSourceCode (const QByteArray &source)
Sets the source code for this shader and compiles it.
bool compileSourceCode (const QString &source)
Sets the source code for this shader and compiles it.
bool compileSourceFile (const QString &fileName)
Sets the source code for this shader to the contents of fileName and compiles it.
bool isCompiled () const
Returns true if this shader has been compiled; false otherwise.
QString log () const
Returns the errors and warnings that occurred during the last compile.
QGLShader (QGLShader::ShaderType type, QObject *parent=0)
Constructs a new QGLShader object of the specified type and attaches it to parent.
QGLShader (QGLShader::ShaderType type, const QGLContext *context, QObject *parent=0)
Constructs a new QGLShader object of the specified type and attaches it to parent.
GLuint shaderId () const
Returns the OpenGL identifier associated with this shader.
QGLShader::ShaderType shaderType () const
Returns the type of this shader.
QByteArray sourceCode () const
Returns the source code for this shader.
virtual ~QGLShader ()
Deletes this shader.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool hasOpenGLShaders (ShaderType type, const QGLContext *context=0)
Returns true if shader programs of type type are supported on this system; false otherwise.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Friends
class QGLShaderProgram
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGLShader class allows OpenGL shaders to be compiled.
Since
4.6
This class supports shaders written in the OpenGL Shading Language (GLSL) and in the OpenGL/ES Shading Language (GLSL/ES).
QGLShader and QGLShaderProgram shelter the programmer from the details of compiling and linking vertex and fragment shaders.
See also
QGLShaderProgram
Definition at line 62 of file qglshaderprogram.h.
Enumerations
ShaderTypeBit
enum QGLShader::ShaderTypeBit
This enum specifies the type of QGLShader that is being created.
Vertex Vertex shader written in the OpenGL Shading Language (GLSL).
Fragment Fragment shader written in the OpenGL Shading Language (GLSL).
Geometry Geometry shaders written in the OpenGL Shading Language (GLSL), based on the GL_EXT_geometry_shader4 extension.
Enumerator
Vertex
Fragment
Geometry
Definition at line 66 of file qglshaderprogram.h.
     {
         Vertex          = 0x0001,
         Fragment        = 0x0002,
         Geometry        = 0x0004
     };
Constructors and Destructors
QGLShader() [1/2]
QGLShader::QGLShader (QGLShader::ShaderType type, QObject * parent = 0) explicit
Constructs a new QGLShader object of the specified type and attaches it to parent.
If shader programs are not supported, QGLShaderProgram::hasOpenGLShaderPrograms() will return false.
This constructor is normally followed by a call to compileSourceCode() or compileSourceFile().
The shader will be associated with the current QGLContext.
See also
compileSourceCode(), compileSourceFile()
Definition at line 321 of file qglshaderprogram.cpp.
     : QObject(*new QGLShaderPrivate(QGLContext::currentContext(), type), parent)
 {
     Q_D(QGLShader);
     d->create();
 }
QGLShader() [2/2]
QGLShader::QGLShader (QGLShader::ShaderType type, const QGLContext * context, QObject * parent = 0)
Constructs a new QGLShader object of the specified type and attaches it to parent.
If shader programs are not supported, then QGLShaderProgram::hasOpenGLShaderPrograms() will return false.
This constructor is normally followed by a call to compileSourceCode() or compileSourceFile().
The shader will be associated with context.
See also
compileSourceCode(), compileSourceFile()
Definition at line 340 of file qglshaderprogram.cpp.
     : QObject(*new QGLShaderPrivate(context ? context : QGLContext::currentContext(), type), parent)
 {
     Q_D(QGLShader);
 #ifndef QT_NO_DEBUG
     if (context && !QGLContext::areSharing(context, QGLContext::currentContext())) {
         qWarning("QGLShader::QGLShader: \'context\' must be the current context or sharing with it.");
         return;
     }
 #endif
     d->create();
 }
~QGLShader()
QGLShader::~QGLShader () virtual
Deletes this shader.
If the shader has been attached to a QGLShaderProgram object, then the actual shader will stay around until the QGLShaderProgram is destroyed.
Definition at line 358 of file qglshaderprogram.cpp.
 {
 }
Functions
compileSourceCode() [1/3]
bool QGLShader::compileSourceCode (const char * source)
Sets the source code for this shader and compiles it.
Returns true if the source was successfully compiled, false otherwise.
See also
compileSourceFile()
Definition at line 398 of file qglshaderprogram.cpp.
Referenced by QGLShaderProgram::addShaderFromSourceCode(), compileSourceCode(), compileSourceFile(), QGLEngineSharedShaders::findProgramInCache(), QGLEngineSharedShaders::QGLEngineSharedShaders(), and QGLTextureGlyphCache::resizeTextureData().
 {
     Q_D(QGLShader);
     if (d->shaderGuard.id()) {
         QVarLengthArray<const char *, 4> src;
         QVarLengthArray<GLint, 4> srclen;
         int headerLen = 0;
         while (source && source[headerLen] == '#') {
             // Skip #version and #extension directives at the start of
             // the shader code.  We need to insert the qualifierDefines
             // and redefineHighp just after them.
             if (qstrncmp(source + headerLen, "#version", 8) != 0 &&
                     qstrncmp(source + headerLen, "#extension", 10) != 0) {
                 break;
             }
             while (source[headerLen] != '\0' && source[headerLen] != '\n')
                 ++headerLen;
             if (source[headerLen] == '\n')
                 ++headerLen;
         }
         if (headerLen > 0) {
             src.append(source);
             srclen.append(GLint(headerLen));
         }
 #ifdef QGL_DEFINE_QUALIFIERS
         src.append(qualifierDefines);
         srclen.append(GLint(sizeof(qualifierDefines) - 1));
 #endif
 #ifdef QGL_REDEFINE_HIGHP
         if (d->shaderType == Fragment) {
             src.append(redefineHighp);
             srclen.append(GLint(sizeof(redefineHighp) - 1));
         }
 #endif
         src.append(source + headerLen);
         srclen.append(GLint(qstrlen(source + headerLen)));
         glShaderSource(d->shaderGuard.id(), src.size(), src.data(), srclen.data());
         return d->compile(this);
     } else {
         return false;
     }
 }
compileSourceCode() [2/3]
bool QGLShader::compileSourceCode (const QByteArray & source)
Sets the source code for this shader and compiles it.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if the source was successfully compiled, false otherwise.
See also
compileSourceFile()
Definition at line 452 of file qglshaderprogram.cpp.
 {
     return compileSourceCode(source.constData());
 }
compileSourceCode() [3/3]
bool QGLShader::compileSourceCode (const QString & source)
Sets the source code for this shader and compiles it.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Returns true if the source was successfully compiled, false otherwise.
See also
compileSourceFile()
Definition at line 468 of file qglshaderprogram.cpp.
 {
     return compileSourceCode(source.toLatin1().constData());
 }
compileSourceFile()
bool QGLShader::compileSourceFile (const QString & fileName)
Sets the source code for this shader to the contents of fileName and compiles it.
Returns true if the file could be opened and the source compiled, false otherwise.
See also
compileSourceCode()
Definition at line 480 of file qglshaderprogram.cpp.
Referenced by QGLShaderProgram::addShaderFromSourceFile().
 {
     QFile file(fileName);
     if (!file.open(QFile::ReadOnly)) {
         qWarning() << "QGLShader: Unable to open file" << fileName;
         return false;
     }
     QByteArray contents = file.readAll();
     return compileSourceCode(contents.constData());
 }
hasOpenGLShaders()
bool QGLShader::hasOpenGLShaders (ShaderType type, const QGLContext * context = 0) static
Returns true if shader programs of type type are supported on this system; false otherwise.
The context is used to resolve the GLSL extensions. If context is null, then QGLContext::currentContext() is used.
Since
4.7
Definition at line 3477 of file qglshaderprogram.cpp.
 {
     if (!context)
         context = QGLContext::currentContext();
     if (!context)
         return false;
     if ((type & ~(Geometry | Vertex | Fragment)) || type == 0)
         return false;
     bool resolved = qt_resolve_glsl_extensions(const_cast<QGLContext *>(context));
     if (!resolved)
         return false;
     if ((type & Geometry) && !QByteArray((const char *) glGetString(GL_EXTENSIONS)).contains("GL_EXT_geometry_shader4"))
         return false;
     return true;
 }
isCompiled()
bool QGLShader::isCompiled () const
Returns true if this shader has been compiled; false otherwise.
See also
compileSourceCode(), compileSourceFile()
Definition at line 520 of file qglshaderprogram.cpp.
 {
     Q_D(const QGLShader);
     return d->compiled;
 }
log()
QString QGLShader::log () const
Returns the errors and warnings that occurred during the last compile.
See also
compileSourceCode(), compileSourceFile()
Definition at line 531 of file qglshaderprogram.cpp.
Referenced by QGLShaderProgram::addShaderFromSourceCode(), and QGLShaderProgram::addShaderFromSourceFile().
 {
     Q_D(const QGLShader);
     return d->log;
 }
shaderId()
GLuint QGLShader::shaderId () const
Returns the OpenGL identifier associated with this shader.
See also
QGLShaderProgram::programId()
Definition at line 542 of file qglshaderprogram.cpp.
 {
     Q_D(const QGLShader);
     return d->shaderGuard.id();
 }
shaderType()
QGLShader::ShaderType QGLShader::shaderType () const
Returns the type of this shader.
Definition at line 365 of file qglshaderprogram.cpp.
Referenced by QGLShaderProgramPrivate::hasShader(), and QGLShaderProgram::link().
 {
     Q_D(const QGLShader);
     return d->shaderType;
 }
sourceCode()
QByteArray QGLShader::sourceCode () const
Returns the source code for this shader.
See also
compileSourceCode()
Definition at line 497 of file qglshaderprogram.cpp.
Referenced by QGLEngineSharedShaders::findProgramInCache().
 {
     Q_D(const QGLShader);
     GLuint shader = d->shaderGuard.id();
     if (!shader)
         return QByteArray();
     GLint size = 0;
     glGetShaderiv(shader, GL_SHADER_SOURCE_LENGTH, &size);
     if (size <= 0)
         return QByteArray();
     GLint len = 0;
     char *source = new char [size];
     glGetShaderSource(shader, size, &len, source);
     QByteArray src(source);
     delete [] source;
     return src;
 }
Friends and Related Functions
QGLShaderProgram
friend class QGLShaderProgram friend
Definition at line 95 of file qglshaderprogram.h.
The documentation for this class was generated from the following files:
/src/opengl/qglshaderprogram.h
/src/opengl/qglshaderprogram.cpp