Qt 4.8: QAccessibleCalendarWidget Class Reference
QAccessibleCalendarWidget Class Reference
#include <qaccessiblewidgets.h>
Public Functions
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
int indexOfChild (const QAccessibleInterface *child) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
QVariant invokeMethodEx (QAccessible::Method method, int child, const QVariantList &params)
int navigate (RelationFlag relation, int entry, QAccessibleInterface **target) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QAccessibleCalendarWidget (QWidget *widget)
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleWidgetEx
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
bool doAction (int action, int child, const QVariantList &params)
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
QAccessibleWidgetEx (QWidget *o, Role r=Client, const QString &name=QString())
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
QString text (Text t, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleObjectEx
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleObjectEx (QObject *object)
void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Protected Functions
QCalendarWidget * calendarWidget () const
Protected Functions inherited from QAccessibleWidgetEx
void addControllingSignal (const QString &signal)
QObject * parentObject () const
void setAccelerator (const QString &accel)
void setDescription (const QString &desc)
void setHelp (const QString &help)
void setValue (const QString &value)
QWidget * widget () const
~QAccessibleWidgetEx ()
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Private Functions
QAbstractItemView * calendarView () const
QWidget * navigationBar () const
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 288 of file qaccessiblewidgets.h.
Constructors and Destructors
QAccessibleCalendarWidget()
QAccessibleCalendarWidget::QAccessibleCalendarWidget (QWidget * widget) explicit
Definition at line 930 of file qaccessiblewidgets.cpp.
     : QAccessibleWidgetEx(widget, Table)
 {
     Q_ASSERT(qobject_cast<QCalendarWidget *>(widget));
 }
Functions
calendarView()
QAbstractItemView * QAccessibleCalendarWidget::calendarView () const private
Definition at line 1018 of file qaccessiblewidgets.cpp.
Referenced by navigate(), and rect().
 {
     foreach (QObject *child, calendarWidget()->children()) {
         if (child->objectName() == QLatin1String("qt_calendar_calendarview"))
             return static_cast<QAbstractItemView *>(child);
     }
     return 0;
 }
calendarWidget()
QCalendarWidget * QAccessibleCalendarWidget::calendarWidget () const protected
Definition at line 1013 of file qaccessiblewidgets.cpp.
Referenced by calendarView(), childCount(), navigationBar(), and rect().
 {
     return static_cast<QCalendarWidget *>(object());
 }
childAt()
int QAccessibleCalendarWidget::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Reimplemented from QAccessibleWidgetEx.
Definition at line 1001 of file qaccessiblewidgets.cpp.
 {
     const QPoint globalTargetPos = QPoint(x, y);
     if (!rect(0).contains(globalTargetPos))
         return -1;
     if (rect(1).contains(globalTargetPos))
         return 1;
     if (rect(2).contains(globalTargetPos))
         return 2;
     return 0;
 }
childCount()
int QAccessibleCalendarWidget::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Reimplemented from QAccessibleWidgetEx.
Definition at line 941 of file qaccessiblewidgets.cpp.
Referenced by indexOfChild(), navigate(), and rect().
 {
    return calendarWidget()->isNavigationBarVisible() ? 2 : 1;
 }
indexOfChild()
int QAccessibleCalendarWidget::indexOfChild (const QAccessibleInterface * child) const virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Reimplemented from QAccessibleWidgetEx.
Definition at line 946 of file qaccessiblewidgets.cpp.
 {
     if (!child || !child->object() || childCount() <= 0)
         return -1;
     if (qobject_cast<QAbstractItemView *>(child->object()))
         return childCount();
     return 1;
 }
invokeMethodEx()
QVariant QAccessibleCalendarWidget::invokeMethodEx (QAccessible::Method method, int child, const QVariantList & params) virtual
Reimplemented from QAccessibleWidgetEx.
Definition at line 936 of file qaccessiblewidgets.cpp.
 {
     return QVariant();
 }
navigate()
int QAccessibleCalendarWidget::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Reimplemented from QAccessibleWidgetEx.
Definition at line 955 of file qaccessiblewidgets.cpp.
 {
     *target = 0;
     if (entry <= 0 || entry > childCount())
         return QAccessibleWidgetEx::navigate(relation, entry, target);
     QWidget *targetWidget = 0;
     switch (relation) {
     case Child:
         if (childCount() == 1) {
             targetWidget = calendarView();
         } else {
             if (entry == 1)
                 targetWidget = navigationBar();
             else
                 targetWidget = calendarView();
         }
         break;
     case Up:
         if (entry == 2)
             targetWidget = navigationBar();
         break;
     case Down:
         if (entry == 1 && childCount() == 2)
             targetWidget = calendarView();
         break;
     default:
         return QAccessibleWidgetEx::navigate(relation, entry, target);
     }
     *target = queryAccessibleInterface(targetWidget);
     return *target ? 0: -1;
 }
navigationBar()
QWidget * QAccessibleCalendarWidget::navigationBar () const private
Definition at line 1027 of file qaccessiblewidgets.cpp.
Referenced by navigate(), and rect().
 {
     foreach (QObject *child, calendarWidget()->children()) {
         if (child->objectName() == QLatin1String("qt_calendar_navigationbar"))
             return static_cast<QWidget *>(child);
     }
     return 0;
 }
rect()
QRect QAccessibleCalendarWidget::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Reimplemented from QAccessibleWidgetEx.
Definition at line 987 of file qaccessiblewidgets.cpp.
Referenced by childAt().
 {
     if (!calendarWidget()->isVisible() || child > childCount())
         return QRect();
     if (child == 0)
         return QAccessibleWidgetEx::rect(child);
     QWidget *childWidget = 0;
     if (childCount() == 2)
         childWidget = child == 1 ? navigationBar() : calendarView();
     else
         childWidget = calendarView();
     return QRect(childWidget->mapToGlobal(QPoint(0, 0)), childWidget->size());
 }
The documentation for this class was generated from the following files:
/src/plugins/accessible/widgets/qaccessiblewidgets.h
/src/plugins/accessible/widgets/qaccessiblewidgets.cpp