Qt 4.8: QDirModel Class Reference
QDirModel Class Reference
The QDirModel class provides a data model for the local filesystem.
#include <qdirmodel.h>
Public Types
enum Roles { FileIconRole = Qt::DecorationRole, FilePathRole = Qt::UserRole + 1, FileNameRole }
Public Slots
void refresh (const QModelIndex &parent=QModelIndex())
QDirModel caches file information.
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
int columnCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of columns in the parent model item.
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Returns the data for the model item index with the given role.
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action over the row in the model specified by the row and column and by the parent index.
QIcon fileIcon (const QModelIndex &index) const
Returns the icons for the item stored in the model under the given index.
QFileInfo fileInfo (const QModelIndex &index) const
Returns the file information for the specified model index.
QString fileName (const QModelIndex &index) const
Returns the name of the item stored in the model under the index given.
QString filePath (const QModelIndex &index) const
Returns the path of the item stored in the model under the index given.
QDir::Filters filter () const
Returns the filter specification for the directory model.
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index in the model.
bool hasChildren (const QModelIndex &index=QModelIndex()) const
Returns true if the parent model item has children; otherwise returns false.
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the data stored under the given role for the specified section of the header with the given orientation.
QFileIconProvider * iconProvider () const
Returns the file icon provider for this directory model.
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns the model item index for the item in the parent with the given row and column.
QModelIndex index (const QString &path, int column=0) const
Returns the model item index for the given path.
bool isDir (const QModelIndex &index) const
Returns true if the model item index represents a directory; otherwise returns false.
bool isReadOnly () const
bool lazyChildCount () const
QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains a serialized description of the specified indexes.
QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of items in the model.
QModelIndex mkdir (const QModelIndex &parent, const QString &name)
Create a directory with the name in the parent model item.
QStringList nameFilters () const
Returns a list of filters applied to the names in the model.
QModelIndex parent (const QModelIndex &child) const
Return the parent of the given child model item.
QDirModel (const QStringList &nameFilters, QDir::Filters filters, QDir::SortFlags sort, QObject *parent=0)
Constructs a new directory model with the given parent.
QDirModel (QObject *parent=0)
Constructs a directory model with the given parent.
bool remove (const QModelIndex &index)
Removes the model item index from the directory model and deletes the corresponding file from the file system, returning true if successful.
bool resolveSymlinks () const
bool rmdir (const QModelIndex &index)
Removes the directory corresponding to the model item index in the directory model and deletes the corresponding directory from the file system, returning true if successful.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of rows in the parent model item.
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the data for the model item index with the given role to the data referenced by the value.
void setFilter (QDir::Filters filters)
Sets the directory model's filter to that specified by filters.
void setIconProvider (QFileIconProvider *provider)
Sets the provider of file icons for the directory model.
void setLazyChildCount (bool enable)
void setNameFilters (const QStringList &filters)
Sets the name filters for the directory model.
void setReadOnly (bool enable)
void setResolveSymlinks (bool enable)
void setSorting (QDir::SortFlags sort)
Sets the directory model's sorting order to that specified by sort.
void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sort the model items in the column using the order given.
QDir::SortFlags sorting () const
Returns the sorting method used for the directory model.
Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
~QDirModel ()
Destroys this directory model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QDirModel (QDirModelPrivate &, QObject *parent=0)
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool lazyChildCount
Whether the directory model optimizes the hasChildren function to only check if the item is a directory.
bool readOnly
Whether the directory model allows writing to the file system.
bool resolveSymlinks
Whether the directory model should resolve symbolic links.
Friends
class QFileDialogPrivate
Additional Inherited Members
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QDirModel class provides a data model for the local filesystem.
The usage of QDirModel is not recommended anymore. The QFileSystemModel class is a more performant alternative.
This class provides access to the local filesystem, providing functions for renaming and removing files and directories, and for creating new directories. In the simplest case, it can be used with a suitable display widget as part of a browser or filer.
QDirModel keeps a cache with file information. The cache needs to be updated with refresh().
QDirModel can be accessed using the standard interface provided by QAbstractItemModel, but it also provides some convenience functions that are specific to a directory model. The fileInfo() and isDir() functions provide information about the underlying files and directories related to items in the model.
Directories can be created and removed using mkdir(), rmdir(), and the model will be automatically updated to take the changes into account.
Note
QDirModel requires an instance of a GUI application.
See also
nameFilters(), setFilter(), filter(), QListView, QTreeView, QFileSystemModel, {Dir View Example}, {Model Classes}
Definition at line 59 of file qdirmodel.h.
Enumerations
Roles
enum QDirModel::Roles
FileIconRole
FilePathRole
FileNameRole
Enumerator
FileIconRole
FilePathRole
FileNameRole
Definition at line 67 of file qdirmodel.h.
                {
         FileIconRole = Qt::DecorationRole,
         FilePathRole = Qt::UserRole + 1,
         FileNameRole
     };
Constructors and Destructors
QDirModel() [1/3]
QDirModel::QDirModel (const QStringList & nameFilters, QDir::Filters filters, QDir::SortFlags sort, QObject * parent = 0)
Constructs a new directory model with the given parent.
Only those files matching the nameFilters and the filters are included in the model. The sort order is given by the sort flags.
Definition at line 229 of file qdirmodel.cpp.
     : QAbstractItemModel(*new QDirModelPrivate, parent)
 {
     Q_D(QDirModel);
     // we always start with QDir::drives()
     d->nameFilters = nameFilters.isEmpty() ? QStringList(QLatin1String("*")) : nameFilters;
     d->filters = filters;
     d->sort = sort;
     d->root.parent = 0;
     d->root.info = QFileInfo();
     d->clear(&d->root);
 }
QDirModel() [2/3]
QDirModel::QDirModel (QObject * parent = 0) explicit
Constructs a directory model with the given parent.
Definition at line 249 of file qdirmodel.cpp.
     : QAbstractItemModel(*new QDirModelPrivate, parent)
 {
     Q_D(QDirModel);
     d->init();
 }
~QDirModel()
QDirModel::~QDirModel ()
Destroys this directory model.
Definition at line 270 of file qdirmodel.cpp.
 {
 }
QDirModel() [3/3]
QDirModel::QDirModel (QDirModelPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 259 of file qdirmodel.cpp.
     : QAbstractItemModel(dd, parent)
 {
     Q_D(QDirModel);
     d->init();
 }
Functions
columnCount()
int QDirModel::columnCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of columns in the parent model item.
Implements QAbstractItemModel.
Definition at line 355 of file qdirmodel.cpp.
Referenced by index().
 {
     if (parent.column() > 0)
         return 0;
     return 4;
 }
data()
QVariant QDirModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Returns the data for the model item index with the given role.
Implements QAbstractItemModel.
Definition at line 365 of file qdirmodel.cpp.
Referenced by QDeclarativeFolderListModel::data(), mimeData(), QDirModelPrivate::restorePersistentIndexes(), and QDirModelPrivate::savePersistentIndexes().
 {
     Q_D(const QDirModel);
     if (!d->indexValid(index))
         return QVariant();
     if (role == Qt::DisplayRole || role == Qt::EditRole) {
         switch (index.column()) {
         case 0: return d->name(index);
         case 1: return d->size(index);
         case 2: return d->type(index);
         case 3: return d->time(index);
         default:
             qWarning("data: invalid display value column %d", index.column());
             return QVariant();
         }
     }
     if (index.column() == 0) {
         if (role == FileIconRole)
             return fileIcon(index);
         if (role == FilePathRole)
             return filePath(index);
         if (role == FileNameRole)
             return fileName(index);
     }
     if (index.column() == 1 && Qt::TextAlignmentRole == role) {
         return Qt::AlignRight;
     }
     return QVariant();
 }
dropMimeData()
bool QDirModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Handles the data supplied by a drag and drop operation that ended with the given action over the row in the model specified by the row and column and by the parent index.
See also
supportedDropActions()
Reimplemented from QAbstractItemModel.
Definition at line 574 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     if (!d->indexValid(parent) || isReadOnly())
         return false;
     bool success = true;
     QString to = filePath(parent) + QDir::separator();
     QModelIndex _parent = parent;
     QList<QUrl> urls = data->urls();
     QList<QUrl>::const_iterator it = urls.constBegin();
     switch (action) {
     case Qt::CopyAction:
         for (; it != urls.constEnd(); ++it) {
             QString path = (*it).toLocalFile();
             success = QFile::copy(path, to + QFileInfo(path).fileName()) && success;
         }
         break;
     case Qt::LinkAction:
         for (; it != urls.constEnd(); ++it) {
             QString path = (*it).toLocalFile();
             success = QFile::link(path, to + QFileInfo(path).fileName()) && success;
         }
         break;
     case Qt::MoveAction:
         for (; it != urls.constEnd(); ++it) {
             QString path = (*it).toLocalFile();
             if (QFile::copy(path, to + QFileInfo(path).fileName())
                && QFile::remove(path)) {
                 QModelIndex idx=index(QFileInfo(path).path());
                 if (idx.isValid()) {
                     refresh(idx);
                     //the previous call to refresh may invalidate the _parent. so recreate a new QModelIndex
                     _parent = index(to);
                 }
             } else {
                 success = false;
             }
         }
         break;
     default:
         return false;
     }
     if (success)
         refresh(_parent);
     return success;
 }
fileIcon()
QIcon QDirModel::fileIcon (const QModelIndex & index) const
Returns the icons for the item stored in the model under the given index.
Definition at line 1139 of file qdirmodel.cpp.
Referenced by data().
 {
     Q_D(const QDirModel);
     if (!d->indexValid(index))
         return d->iconProvider->icon(QFileIconProvider::Computer);
     QDirModelPrivate::QDirNode *node = d->node(index);
     if (node->icon.isNull())
         node->icon = d->iconProvider->icon(node->info);
     return node->icon;
 }
fileInfo()
QFileInfo QDirModel::fileInfo (const QModelIndex & index) const
Returns the file information for the specified model index.
Note: If the model index represents a symbolic link in the underlying filing system, the file information returned will contain information about the symbolic link itself, regardless of whether resolveSymlinks is enabled or not.
See also
QFileInfo::symLinkTarget()
Definition at line 1161 of file qdirmodel.cpp.
Referenced by fileName(), filePath(), and flags().
 {
     Q_D(const QDirModel);
     Q_ASSERT(d->indexValid(index));
     QDirModelPrivate::QDirNode *node = d->node(index);
     return node->info;
 }
fileName()
QString QDirModel::fileName (const QModelIndex & index) const
Returns the name of the item stored in the model under the index given.
Definition at line 1121 of file qdirmodel.cpp.
Referenced by data(), and dropMimeData().
 {
     Q_D(const QDirModel);
     if (!d->indexValid(index))
         return QString();
     QFileInfo info = fileInfo(index);
     if (info.isRoot())
         return info.absoluteFilePath();
     if (d->resolveSymlinks && info.isSymLink())
         info = d->resolvedInfo(info);
     return info.fileName();
 }
filePath()
QString QDirModel::filePath (const QModelIndex & index) const
Returns the path of the item stored in the model under the index given.
Definition at line 1103 of file qdirmodel.cpp.
Referenced by data(), dropMimeData(), and mimeData().
 {
     Q_D(const QDirModel);
     if (d->indexValid(index)) {
         QFileInfo fi = fileInfo(index);
         if (d->resolveSymlinks && fi.isSymLink())
             fi = d->resolvedInfo(fi);
         return QDir::cleanPath(fi.absoluteFilePath());
     }
     return QString(); // root path
 }
filter()
QDir::Filters QDirModel::filter () const
Returns the filter specification for the directory model.
See also
QDir::Filters
Definition at line 712 of file qdirmodel.cpp.
Referenced by QDeclarativeFolderListModel::handleDataChanged(), QDeclarativeFolderListModel::setShowDirs(), QDeclarativeFolderListModel::setShowDotAndDotDot(), and QDeclarativeFolderListModel::setShowOnlyReadable().
 {
     Q_D(const QDirModel);
     return d->filters;
 }
flags()
Qt::ItemFlags QDirModel::flags (const QModelIndex & index) const virtual
Returns the item flags for the given index in the model.
See also
Qt::ItemFlags
Reimplemented from QAbstractItemModel.
Definition at line 486 of file qdirmodel.cpp.
Referenced by setData().
 {
     Q_D(const QDirModel);
     Qt::ItemFlags flags = QAbstractItemModel::flags(index);
     if (!d->indexValid(index))
         return flags;
     flags |= Qt::ItemIsDragEnabled;
     if (d->readOnly)
         return flags;
     QDirModelPrivate::QDirNode *node = d->node(index);
     if ((index.column() == 0) && node->info.isWritable()) {
         flags |= Qt::ItemIsEditable;
         if (fileInfo(index).isDir()) // is directory and is editable
             flags |= Qt::ItemIsDropEnabled;
     }
     return flags;
 }
hasChildren()
bool QDirModel::hasChildren (const QModelIndex & index = QModelIndex()) const virtual
Returns true if the parent model item has children; otherwise returns false.
Reimplemented from QAbstractItemModel.
Definition at line 465 of file qdirmodel.cpp.
 {
     Q_D(const QDirModel);
     if (parent.column() > 0)
         return false;
     if (!parent.isValid()) // the invalid index is the "My Computer" item
         return true; // the drives
     QDirModelPrivate::QDirNode *p = d->node(parent);
     Q_ASSERT(p);
     if (d->lazyChildCount) // optimization that only checks for children if the node has been populated
         return p->info.isDir();
     return p->info.isDir() && rowCount(parent) > 0;
 }
headerData()
QVariant QDirModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const virtual
Returns the data stored under the given role for the specified section of the header with the given orientation.
Reimplemented from QAbstractItemModel.
Definition at line 435 of file qdirmodel.cpp.
 {
     if (orientation == Qt::Horizontal) {
         if (role != Qt::DisplayRole)
             return QVariant();
     switch (section) {
         case 0: return tr("Name");
         case 1: return tr("Size");
         case 2: return
 #ifdef Q_OS_MAC
                        tr("Kind", "Match OS X Finder");
 #else
                        tr("Type", "All other platforms");
 #endif
         // Windows   - Type
         // OS X      - Kind
         // Konqueror - File Type
         // Nautilus  - Type
         case 3: return tr("Date Modified");
         default: return QVariant();
         }
     }
     return QAbstractItemModel::headerData(section, orientation, role);
 }
iconProvider()
QFileIconProvider * QDirModel::iconProvider () const
Returns the file icon provider for this directory model.
Definition at line 653 of file qdirmodel.cpp.
Referenced by QDirModelPrivate::type().
 {
     Q_D(const QDirModel);
     return d->iconProvider;
 }
index() [1/2]
QModelIndex QDirModel::index (int row, int column, const QModelIndex & parent = QModelIndex()) const virtual
Returns the model item index for the item in the parent with the given row and column.
Implements QAbstractItemModel.
Definition at line 281 of file qdirmodel.cpp.
Referenced by QDeclarativeFolderListModel::data(), dropMimeData(), index(), QDeclarativeFolderListModel::isFolder(), mkdir(), QDeclarativeFolderListModel::refresh(), QDirModelPrivate::savePersistentIndexes(), and QDeclarativeFolderListModel::setFolder().
 {
     Q_D(const QDirModel);
     // note that rowCount does lazy population
     if (column < 0 || column >= columnCount(parent) || row < 0 || parent.column() > 0)
         return QModelIndex();
     // make sure the list of children is up to date
     QDirModelPrivate::QDirNode *p = (d->indexValid(parent) ? d->node(parent) : &d->root);
     Q_ASSERT(p);
     if (!p->populated)
         d->populate(p); // populate without stat'ing
     if (row >= p->children.count())
         return QModelIndex();
     // now get the internal pointer for the index
     QDirModelPrivate::QDirNode *n = d->node(row, d->indexValid(parent) ? p : 0);
     Q_ASSERT(n);
     return createIndex(row, column, n);
 }
index() [2/2]
QModelIndex QDirModel::index (const QString & path, int column = 0) const
Returns the model item index for the given path.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 863 of file qdirmodel.cpp.
 {
     Q_D(const QDirModel);
     if (path.isEmpty() || path == QCoreApplication::translate("QFileDialog", "My Computer"))
         return QModelIndex();
     QString absolutePath = QDir(path).absolutePath();
 #if (defined(Q_OS_WIN) && !defined(Q_OS_WINCE)) || defined(Q_OS_SYMBIAN)
     absolutePath = absolutePath.toLower();
 #endif
 #if defined(Q_OS_WIN) && !defined(Q_OS_WINCE)
     // On Windows, "filename......." and "filename" are equivalent
     if (absolutePath.endsWith(QLatin1Char('.'))) {
         int i;
         for (i = absolutePath.count() - 1; i >= 0; --i) {
             if (absolutePath.at(i) != QLatin1Char('.'))
                 break;
         }
         absolutePath = absolutePath.left(i+1);
     }
 #endif
     QStringList pathElements = absolutePath.split(QLatin1Char('/'), QString::SkipEmptyParts);
     if ((pathElements.isEmpty() || !QFileInfo(path).exists())
 #if !defined(Q_OS_WIN) || defined(Q_OS_WINCE)
         && path != QLatin1String("/")
 #endif
         )
         return QModelIndex();
     QModelIndex idx; // start with "My Computer"
     if (!d->root.populated) // make sure the root is populated
         d->populate(&d->root);
 #if defined(Q_OS_WIN) && !defined(Q_OS_WINCE)
     if (absolutePath.startsWith(QLatin1String("//"))) { // UNC path
         QString host = pathElements.first();
         int r = 0;
         for (; r < d->root.children.count(); ++r)
             if (d->root.children.at(r).info.fileName() == host)
                 break;
         bool childAppended = false;
         if (r >= d->root.children.count() && d->allowAppendChild) {
             d->appendChild(&d->root, QLatin1String("//") + host);
             childAppended = true;
         }
         idx = index(r, 0, QModelIndex());
         pathElements.pop_front();
         if (childAppended)
             emit const_cast<QDirModel*>(this)->layoutChanged();
     } else
 #endif
 #if (defined(Q_OS_WIN) && !defined(Q_OS_WINCE)) || defined(Q_OS_SYMBIAN)
     if (pathElements.at(0).endsWith(QLatin1Char(':'))) {
         pathElements[0] += QLatin1Char('/');
     }
 #else
     // add the "/" item, since it is a valid path element on unix
     pathElements.prepend(QLatin1String("/"));
 #endif
     for (int i = 0; i < pathElements.count(); ++i) {
         Q_ASSERT(!pathElements.at(i).isEmpty());
         QString element = pathElements.at(i);
         QDirModelPrivate::QDirNode *parent = (idx.isValid() ? d->node(idx) : &d->root);
         Q_ASSERT(parent);
         if (!parent->populated)
             d->populate(parent);
         // search for the element in the child nodes first
         int row = -1;
         for (int j = parent->children.count() - 1; j >= 0; --j) {
             const QFileInfo& fi = parent->children.at(j).info;
             QString childFileName;
             childFileName = idx.isValid() ? fi.fileName() : fi.absoluteFilePath();
 #if (defined(Q_OS_WIN) && !defined(Q_OS_WINCE)) || defined(Q_OS_SYMBIAN)
             childFileName = childFileName.toLower();
 #endif
             if (childFileName == element) {
                 if (i == pathElements.count() - 1)
                     parent->children[j].stat = true;
                 row = j;
                 break;
             }
         }
         // we couldn't find the path element, we create a new node since we _know_ that the path is valid
         if (row == -1) {
 #if defined(Q_OS_WINCE)
             QString newPath;
             if (parent->info.isRoot())
                 newPath = parent->info.absoluteFilePath() + element;
             else
                 newPath = parent->info.absoluteFilePath() + QLatin1Char('/') + element;
 #else
             QString newPath = parent->info.absoluteFilePath() + QLatin1Char('/') + element;
 #endif
             if (!d->allowAppendChild || !QFileInfo(newPath).isDir())
                 return QModelIndex();
             d->appendChild(parent, newPath);
             row = parent->children.count() - 1;
             if (i == pathElements.count() - 1) // always stat children of  the last element
                 parent->children[row].stat = true;
             emit const_cast<QDirModel*>(this)->layoutChanged();
         }
         Q_ASSERT(row >= 0);
         idx = createIndex(row, 0, static_cast<void*>(&parent->children[row]));
         Q_ASSERT(idx.isValid());
     }
     if (column != 0)
         return idx.sibling(idx.row(), column);
     return idx;
 }
isDir()
bool QDirModel::isDir (const QModelIndex & index) const
Returns true if the model item index represents a directory; otherwise returns false.
Definition at line 986 of file qdirmodel.cpp.
Referenced by index(), QDeclarativeFolderListModel::isFolder(), QDirModelPrivate::node(), and QDeclarativeFolderListModel::setFolder().
 {
     Q_D(const QDirModel);
     Q_ASSERT(d->indexValid(index));
     QDirModelPrivate::QDirNode *node = d->node(index);
     return node->info.isDir();
 }
isReadOnly()
bool QDirModel::isReadOnly () const
Definition at line 788 of file qdirmodel.cpp.
Referenced by dropMimeData(), mkdir(), remove(), and rmdir().
 {
     Q_D(const QDirModel);
     return d->readOnly;
 }
lazyChildCount()
bool QDirModel::lazyChildCount () const
Referenced by setLazyChildCount().
mimeData()
QMimeData * QDirModel::mimeData (const QModelIndexList & indexes) const virtual
Returns an object that contains a serialized description of the specified indexes.
The format used to describe the items corresponding to the indexes is obtained from the mimeTypes() function.
If the list of indexes is empty, 0 is returned rather than a serialized empty list.
Reimplemented from QAbstractItemModel.
Definition at line 554 of file qdirmodel.cpp.
 {
     QList<QUrl> urls;
     QList<QModelIndex>::const_iterator it = indexes.begin();
     for (; it != indexes.end(); ++it)
         if ((*it).column() == 0)
             urls << QUrl::fromLocalFile(filePath(*it));
     QMimeData *data = new QMimeData();
     data->setUrls(urls);
     return data;
 }
mimeTypes()
QStringList QDirModel::mimeTypes () const virtual
Returns a list of MIME types that can be used to describe a list of items in the model.
Reimplemented from QAbstractItemModel.
Definition at line 540 of file qdirmodel.cpp.
 {
     return QStringList(QLatin1String("text/uri-list"));
 }
mkdir()
QModelIndex QDirModel::mkdir (const QModelIndex & parent, const QString & name)
Create a directory with the name in the parent model item.
Definition at line 998 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     if (!d->indexValid(parent) || isReadOnly())
         return QModelIndex();
     QDirModelPrivate::QDirNode *p = d->node(parent);
     QString path = p->info.absoluteFilePath();
     // For the indexOf() method to work, the new directory has to be a direct child of
     // the parent directory.
     QDir newDir(name);
     QDir dir(path);
     if (newDir.isRelative())
         newDir = QDir(path + QLatin1Char('/') + name);
     QString childName = newDir.dirName(); // Get the singular name of the directory
     newDir.cdUp();
     if (newDir.absolutePath() != dir.absolutePath() || !dir.mkdir(name))
         return QModelIndex(); // nothing happened
     refresh(parent);
     QStringList entryList = d->entryList(path);
     int r = entryList.indexOf(childName);
     QModelIndex i = index(r, 0, parent); // return an invalid index
     return i;
 }
nameFilters()
QStringList QDirModel::nameFilters () const
Returns a list of filters applied to the names in the model.
Definition at line 679 of file qdirmodel.cpp.
Referenced by QDirModelPrivate::children(), QDirModelPrivate::entryInfoList(), QDirModelPrivate::entryList(), QDirModelPrivate::init(), and QDirModel().
 {
     Q_D(const QDirModel);
     return d->nameFilters;
 }
parent()
QObject * QDirModel::parent (const QModelIndex & child) const virtual
Return the parent of the given child model item.
Warning
This function is not part of the public interface.
Implements QAbstractItemModel.
Definition at line 305 of file qdirmodel.cpp.
 {
     Q_D(const QDirModel);
     if (!d->indexValid(child))
     return QModelIndex();
     QDirModelPrivate::QDirNode *node = d->node(child);
     QDirModelPrivate::QDirNode *par = (node ? node->parent : 0);
     if (par == 0) // parent is the root node
     return QModelIndex();
     // get the parent's row
     const QVector<QDirModelPrivate::QDirNode> children =
         par->parent ? par->parent->children : d->root.children;
     Q_ASSERT(children.count() > 0);
     int row = (par - &(children.at(0)));
     Q_ASSERT(row >= 0);
     return createIndex(row, 0, par);
 }
refresh
void QDirModel::refresh (const QModelIndex & parent = QModelIndex()) slot
QDirModel caches file information.
This function updates the cache. The parent parameter is the directory from which the model is updated; the default value will update the model from root directory of the file system (the entire model).
Definition at line 829 of file qdirmodel.cpp.
Referenced by dropMimeData(), mkdir(), remove(), rmdir(), setFilter(), setNameFilters(), and setSorting().
 {
     Q_D(QDirModel);
     QDirModelPrivate::QDirNode *n = d->indexValid(parent) ? d->node(parent) : &(d->root);
     int rows = n->children.count();
     if (rows == 0) {
         emit layoutAboutToBeChanged();
         n->stat = true; // make sure that next time we read all the info
         n->populated = false;
         emit layoutChanged();
         return;
     }
     emit layoutAboutToBeChanged();
     d->savePersistentIndexes();
     d->rowsAboutToBeRemoved(parent, 0, rows - 1);
     n->stat = true; // make sure that next time we read all the info
     d->clear(n);
     d->rowsRemoved(parent, 0, rows - 1);
     d->restorePersistentIndexes();
     emit layoutChanged();
 }
remove()
bool QDirModel::remove (const QModelIndex & index)
Removes the model item index from the directory model and deletes the corresponding file from the file system, returning true if successful.
If the item cannot be removed, false is returned.
Warning
This function deletes files from the file system; it does not move them to a location where they can be recovered.
See also
rmdir()
Definition at line 1075 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     if (!d->indexValid(index) || isReadOnly())
         return false;
     QDirModelPrivate::QDirNode *n = d_func()->node(index);
     if (n->info.isDir())
         return false;
     QModelIndex par = parent(index);
     QDirModelPrivate::QDirNode *p = d_func()->node(par);
     QDir dir = p->info.dir(); // parent dir
     QString path = n->info.absoluteFilePath();
     if (!dir.remove(path))
         return false;
     refresh(par);
     return true;
 }
resolveSymlinks()
bool QDirModel::resolveSymlinks () const
Referenced by QDirModelPrivate::children(), and setResolveSymlinks().
rmdir()
bool QDirModel::rmdir (const QModelIndex & index)
Removes the directory corresponding to the model item index in the directory model and deletes the corresponding directory from the file system, returning true if successful.
If the directory cannot be removed, false is returned.
Warning
This function deletes directories from the file system; it does not move them to a location where they can be recovered.
See also
remove()
Definition at line 1040 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     if (!d->indexValid(index) || isReadOnly())
         return false;
     QDirModelPrivate::QDirNode *n = d_func()->node(index);
     if (!n->info.isDir()) {
         qWarning("rmdir: the node is not a directory");
         return false;
     }
     QModelIndex par = parent(index);
     QDirModelPrivate::QDirNode *p = d_func()->node(par);
     QDir dir = p->info.dir(); // parent dir
     QString path = n->info.absoluteFilePath();
     if (!dir.rmdir(path))
         return false;
     refresh(par);
     return true;
 }
rowCount()
int QDirModel::rowCount (const QModelIndex & parent = QModelIndex()) const virtual
Returns the number of rows in the parent model item.
Implements QAbstractItemModel.
Definition at line 331 of file qdirmodel.cpp.
Referenced by hasChildren(), QDeclarativeFolderListModel::inserted(), QDeclarativeFolderListModel::refresh(), and QDeclarativeFolderListModel::removed().
 {
     Q_D(const QDirModel);
     if (parent.column() > 0)
         return 0;
     if (!parent.isValid()) {
         if (!d->root.populated) // lazy population
             d->populate(&d->root);
         return d->root.children.count();
     }
     if (parent.model() != this)
         return 0;
     QDirModelPrivate::QDirNode *p = d->node(parent);
     if (p->info.isDir() && !p->populated) // lazy population
         d->populate(p);
     return p->children.count();
 }
setData()
bool QDirModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Sets the data for the model item index with the given role to the data referenced by the value.
Returns true if successful; otherwise returns false.
See also
Qt::ItemDataRole
Reimplemented from QAbstractItemModel.
Definition at line 406 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     if (!d->indexValid(index) || index.column() != 0
         || (flags(index) & Qt::ItemIsEditable) == 0 || role != Qt::EditRole)
         return false;
     QDirModelPrivate::QDirNode *node = d->node(index);
     QDir dir = node->info.dir();
     QString name = value.toString();
     if (dir.rename(node->info.fileName(), name)) {
         node->info = QFileInfo(dir, name);
         QModelIndex sibling = index.sibling(index.row(), 3);
         emit dataChanged(index, sibling);
         d->toBeRefreshed = index.parent();
         QMetaObject::invokeMethod(this, "_q_refresh", Qt::QueuedConnection);
         return true;
     }
     return false;
 }
setFilter()
void QDirModel::setFilter (QDir::Filters filters)
Sets the directory model's filter to that specified by filters.
Note that the filter you set should always include the QDir::AllDirs enum value, otherwise QDirModel won't be able to read the directory structure.
See also
QDir::Filters
Definition at line 694 of file qdirmodel.cpp.
Referenced by QDeclarativeFolderListModel::QDeclarativeFolderListModel(), QDeclarativeFolderListModel::setShowDirs(), QDeclarativeFolderListModel::setShowDotAndDotDot(), and QDeclarativeFolderListModel::setShowOnlyReadable().
 {
     Q_D(QDirModel);
     d->filters = filters;
     emit layoutAboutToBeChanged();
     if (d->shouldStat)
         refresh(QModelIndex());
     else
         d->invalidate();
     emit layoutChanged();
 }
setIconProvider()
void QDirModel::setIconProvider (QFileIconProvider * provider)
Sets the provider of file icons for the directory model.
Definition at line 643 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     d->iconProvider = provider;
 }
setLazyChildCount()
void QDirModel::setLazyChildCount (bool enable)
Definition at line 810 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     d->lazyChildCount = enable;
 }
setNameFilters()
void QDirModel::setNameFilters (const QStringList & filters)
Sets the name filters for the directory model.
Definition at line 663 of file qdirmodel.cpp.
Referenced by QDeclarativeFolderListModel::setNameFilters().
 {
     Q_D(QDirModel);
     d->nameFilters = filters;
     emit layoutAboutToBeChanged();
     if (d->shouldStat)
        refresh(QModelIndex());
     else
         d->invalidate();
     emit layoutChanged();
 }
setReadOnly()
void QDirModel::setReadOnly (bool enable)
Definition at line 782 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     d->readOnly = enable;
 }
setResolveSymlinks()
void QDirModel::setResolveSymlinks (bool enable)
Definition at line 757 of file qdirmodel.cpp.
 {
     Q_D(QDirModel);
     d->resolveSymlinks = enable;
 }
setSorting()
void QDirModel::setSorting (QDir::SortFlags sort)
Sets the directory model's sorting order to that specified by sort.
See also
QDir::SortFlags
Definition at line 724 of file qdirmodel.cpp.
Referenced by sort(), and QDeclarativeFolderListModelPrivate::updateSorting().
 {
     Q_D(QDirModel);
     d->sort = sort;
     emit layoutAboutToBeChanged();
     if (d->shouldStat)
         refresh(QModelIndex());
     else
         d->invalidate();
     emit layoutChanged();
 }
sort()
void QDirModel::sort (int column, Qt::SortOrder order = Qt::AscendingOrder) virtual
Sort the model items in the column using the order given.
The order is a value defined in Qt::SortOrder .
Reimplemented from QAbstractItemModel.
Definition at line 509 of file qdirmodel.cpp.
Referenced by QDirModelPrivate::entryInfoList(), QDirModelPrivate::entryList(), QDirModelPrivate::init(), QDirModel(), and setSorting().
 {
     QDir::SortFlags sort = QDir::DirsFirst | QDir::IgnoreCase;
     if (order == Qt::DescendingOrder)
         sort |= QDir::Reversed;
     switch (column) {
     case 0:
         sort |= QDir::Name;
         break;
     case 1:
         sort |= QDir::Size;
         break;
     case 2:
         sort |= QDir::Type;
         break;
     case 3:
         sort |= QDir::Time;
         break;
     default:
         break;
     }
     setSorting(sort);
 }
sorting()
QDir::SortFlags QDirModel::sorting () const
Returns the sorting method used for the directory model.
See also
QDir::SortFlags
Definition at line 741 of file qdirmodel.cpp.
 {
     Q_D(const QDirModel);
     return d->sort;
 }
supportedDropActions()
Qt::DropActions QDirModel::supportedDropActions () const virtual
Returns the drop actions supported by this model.
See also
Qt::DropActions
Reimplemented from QAbstractItemModel.
Definition at line 633 of file qdirmodel.cpp.
 {
     return Qt::CopyAction | Qt::MoveAction; // FIXME: LinkAction is not supported yet
 }
Friends and Related Functions
QFileDialogPrivate
friend class QFileDialogPrivate friend
Definition at line 146 of file qdirmodel.h.
Properties
lazyChildCount
bool QDirModel::lazyChildCount private
Whether the directory model optimizes the hasChildren function to only check if the item is a directory.
If this property is set to false, the directory model will make sure that a directory actually containes any files before reporting that it has children. Otherwise the directory model will report that an item has children if the item is a directory.
This property is false by default
Definition at line 64 of file qdirmodel.h.
readOnly
QDirModel::readOnly private
Whether the directory model allows writing to the file system.
If this property is set to false, the directory model will allow renaming, copying and deleting of files and directories.
This property is true by default
Definition at line 63 of file qdirmodel.h.
resolveSymlinks
bool QDirModel::resolveSymlinks private
Whether the directory model should resolve symbolic links.
This is only relevant on operating systems that support symbolic links.
Definition at line 62 of file qdirmodel.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qdirmodel.h
/src/gui/itemviews/qdirmodel.cpp