Qt 4.8: Maemo::Icd Class Reference
Maemo::Icd Class Reference
#include <maemo_icd.h>
Public Functions
uint addrinfo (QString &service_type, uint service_attrs, QString &service_id, QString &network_type, uint network_attrs, QByteArray &network_id, IcdAddressInfoResult &addr_result)
uint addrinfo (QList< IcdAddressInfoResult > &addr_results)
Icd (QObject *parent=0)
Icd (unsigned int timeout, QObject *parent=0)
Icd (unsigned int timeout, IcdDbusInterfaceVer ver, QObject *parent=0)
QStringList scan (icd_scan_request_flags flags, QStringList &network_types, QList< IcdScanResult > &scan_results, QString &error)
uint state (QString &service_type, uint service_attrs, QString &service_id, QString &network_type, uint network_attrs, QByteArray &network_id, IcdStateResult &state_result)
uint state (QList< IcdStateResult > &state_results)
uint statistics (QList< IcdStatisticsResult > &stats_results)
~Icd ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void icdCallReply (const QString &method, const QList< QVariant > &args, const QString &error)
void icdSignalReceived (const QString &interface, const QString &signal, const QList< QVariant > &args)
Properties
IcdPrivate * d
Friends
class IcdPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 129 of file maemo_icd.h.
Constructors and Destructors
Icd() [1/3]
Maemo::Icd::Icd (QObject * parent = 0)
Definition at line 768 of file maemo_icd.cpp.
   : QObject(parent), d(new IcdPrivate(this))
 {
 }
Icd() [2/3]
Maemo::Icd::Icd (unsigned int timeout, QObject * parent = 0)
Definition at line 773 of file maemo_icd.cpp.
   : QObject(parent), d(new IcdPrivate(timeout, this))
 {
 }
Icd() [3/3]
Maemo::Icd::Icd (unsigned int timeout, IcdDbusInterfaceVer ver, QObject * parent = 0)
Definition at line 778 of file maemo_icd.cpp.
   : QObject(parent), d(new IcdPrivate(timeout, ver, this))
 {
 }
~Icd()
Maemo::Icd::~Icd ()
Definition at line 783 of file maemo_icd.cpp.
 {
     delete d;
 }
Functions
addrinfo() [1/2]
uint Maemo::Icd::addrinfo (QString & service_type, uint service_attrs, QString & service_id, QString & network_type, uint network_attrs, QByteArray & network_id, IcdAddressInfoResult & addr_result)
Definition at line 809 of file maemo_icd.cpp.
Referenced by get_network_interface().
 {
     return d->addrinfo(service_type, service_attrs, service_id,
                network_type, network_attrs, network_id,
                addr_result);
 }
addrinfo() [2/2]
uint Maemo::Icd::addrinfo (QList< IcdAddressInfoResult > & addr_results)
Definition at line 832 of file maemo_icd.cpp.
 {
     return d->addrinfo(addr_results);
 }
icdCallReply
void Maemo::Icd::icdCallReply (const QString & method, const QList< QVariant > & args, const QString & error) private slot
Definition at line 846 of file maemo_icd.cpp.
 {
     d->callReply(method, args, error);
 }
icdSignalReceived
void Maemo::Icd::icdSignalReceived (const QString & interface, const QString & signal, const QList< QVariant > & args) private slot
Definition at line 838 of file maemo_icd.cpp.
 {
     d->signalReceived(interface, signal, args);
 }
scan()
QStringList Maemo::Icd::scan (icd_scan_request_flags flags, QStringList & network_types, QList< IcdScanResult > & scan_results, QString & error)
Definition at line 789 of file maemo_icd.cpp.
 {
     return d->scan(flags, network_types, scan_results, error);
 }
state() [1/2]
uint Maemo::Icd::state (QString & service_type, uint service_attrs, QString & service_id, QString & network_type, uint network_attrs, QByteArray & network_id, IcdStateResult & state_result)
Definition at line 798 of file maemo_icd.cpp.
Referenced by QIcdEngine::getIcdInitialState(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
 {
     return d->state(service_type, service_attrs, service_id,
             network_type, network_attrs, network_id,
             state_result);
 }
state() [2/2]
uint Maemo::Icd::state (QList< IcdStateResult > & state_results)
Definition at line 820 of file maemo_icd.cpp.
 {
     return d->state(state_results);
 }
statistics()
uint Maemo::Icd::statistics (QList< IcdStatisticsResult > & stats_results)
Definition at line 826 of file maemo_icd.cpp.
Referenced by QNetworkSessionPrivateImpl::getStatistics().
 {
     return d->statistics(stats_results);
 }
Friends and Related Functions
IcdPrivate
friend class IcdPrivate friend
Definition at line 169 of file maemo_icd.h.
Properties
d
IcdPrivate* Maemo::Icd::d private
Definition at line 168 of file maemo_icd.h.
Referenced by addrinfo(), icdCallReply(), icdSignalReceived(), scan(), state(), statistics(), and ~Icd().
The documentation for this class was generated from the following files:
/src/plugins/bearer/icd/maemo_icd.h
/src/plugins/bearer/icd/maemo_icd.cpp