Qt 4.8: QIndexMapper Class Reference
QIndexMapper Class Reference
#include <qcompleter_p.h>
Public Functions
void append (int x)
int cost () const
int count () const
int first () const
int from () const
int indexOf (int x) const
bool isEmpty () const
bool isValid () const
int last () const
int operator[] (int index) const
QIndexMapper ()
QIndexMapper (int f, int t)
QIndexMapper (QVector< int > vec)
int to () const
Properties
int f
int t
bool v
QVector< int > vector
Detailed Description
Definition at line 106 of file qcompleter_p.h.
Constructors and Destructors
QIndexMapper() [1/3]
QIndexMapper::QIndexMapper () inline
Definition at line 109 of file qcompleter_p.h.
 : v(false), f(0), t(-1) { }
QIndexMapper() [2/3]
QIndexMapper::QIndexMapper (int f, int t) inline
Definition at line 110 of file qcompleter_p.h.
 : v(false), f(f), t(t) { }
QIndexMapper() [3/3]
QIndexMapper::QIndexMapper (QVector< int > vec) inline
Definition at line 111 of file qcompleter_p.h.
 : v(true), vector(vec), f(-1), t(-1) { }
Functions
append()
void QIndexMapper::append (int x) inline
Definition at line 118 of file qcompleter_p.h.
Referenced by QUnsortedModelEngine::buildIndices(), and QCompletionEngine::filterHistory().
 { Q_ASSERT(v); vector.append(x); }
cost()
int QIndexMapper::cost () const inline
Definition at line 123 of file qcompleter_p.h.
Referenced by QCompletionEngine::saveInCache().
 { return vector.count()+2; }
count()
int QIndexMapper::count () const inline
Definition at line 113 of file qcompleter_p.h.
Referenced by QUnsortedModelEngine::buildIndices(), QUnsortedModelEngine::filter(), QCompletionModel::index(), and QCompletionModel::mapFromSource().
 { return v ? vector.count() : t - f + 1; }
first()
int QIndexMapper::first () const inline
Definition at line 119 of file qcompleter_p.h.
Referenced by QSortedModelEngine::indexHint().
 { return v ? vector.first() : f; }
from()
int QIndexMapper::from () const inline
Definition at line 121 of file qcompleter_p.h.
Referenced by QSortedModelEngine::filter().
 { Q_ASSERT(!v); return f; }
indexOf()
int QIndexMapper::indexOf (int x) const inline
Definition at line 115 of file qcompleter_p.h.
Referenced by QCompletionModel::mapFromSource().
 { return v ? vector.indexOf(x) : ((t < f) ? -1 : x - f); }
isEmpty()
bool QIndexMapper::isEmpty () const inline
Definition at line 117 of file qcompleter_p.h.
 { return v ? vector.isEmpty() : (t < f); }
isValid()
bool QIndexMapper::isValid () const inline
Definition at line 116 of file qcompleter_p.h.
Referenced by QMatchData::isValid().
 { return !isEmpty(); }
last()
int QIndexMapper::last () const inline
Definition at line 120 of file qcompleter_p.h.
Referenced by QUnsortedModelEngine::filter(), QSortedModelEngine::indexHint(), and QCompletionModel::mapFromSource().
 { return v ? vector.last() : t; }
operator[]()
int QIndexMapper::operator[] (int index) const inline
Definition at line 114 of file qcompleter_p.h.
 { return v ? vector[index] : f + index; }
to()
int QIndexMapper::to () const inline
Definition at line 122 of file qcompleter_p.h.
Referenced by QSortedModelEngine::filter().
 { Q_ASSERT(!v); return t; }
Properties
f
int QIndexMapper::f private
Definition at line 128 of file qcompleter_p.h.
t
int QIndexMapper::t private
Definition at line 128 of file qcompleter_p.h.
v
bool QIndexMapper::v private
Definition at line 126 of file qcompleter_p.h.
vector
QVector<int> QIndexMapper::vector private
Definition at line 127 of file qcompleter_p.h.
The documentation for this class was generated from the following file:
/src/gui/util/qcompleter_p.h