Qt 4.8: QConnmanManagerInterface Class Reference
QConnmanManagerInterface Class Reference
#include <qconnmanservice_linux_p.h>
Signals
void propertyChanged (const QString &, const QDBusVariant &value)
void propertyChangedContext (const QString &, const QString &, const QDBusVariant &)
void stateChanged (const QString &)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDBusObjectPath connectService (QVariantMap &map)
QDBusObjectPath createProfile (const QString &name)
bool disableTechnology (const QString &type)
bool enableTechnology (const QString &type)
QString getActiveProfile ()
QStringList getAvailableTechnologies ()
QStringList getConnectedTechnologies ()
QString getDefaultTechnology ()
QStringList getEnabledTechnologies ()
bool getOfflineMode ()
QString getPathForTechnology (const QString &tech)
QStringList getProfiles ()
QVariantMap getProperties ()
QStringList getServices ()
QString getState ()
QStringList getTechnologies ()
QDBusObjectPath lookupService (const QString &)
QDBusObjectPath path () const
QConnmanManagerInterface (QObject *parent=0)
void registerAgent (QDBusObjectPath &path)
void registerCounter (const QString &path, quint32 interval)
void releaseSession ()
bool removeProfile (QDBusObjectPath path)
bool requestScan (const QString &type)
QString requestSession (const QString &bearerName)
bool setProperty (const QString &name, const QDBusVariant &value)
void unregisterAgent (QDBusObjectPath path)
void unregisterCounter (const QString &path)
~QConnmanManagerInterface ()
Public Functions inherited from QDBusAbstractInterface
QDBusPendingCall asyncCall (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusPendingCall asyncCallWithArgumentList (const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
QDBusMessage call (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage call (QDBus::CallMode mode, const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage callWithArgumentList (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member, const char *errorSlot)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member)
This function is deprecated.
QDBusConnection connection () const
Returns the connection this interface is assocated with.
QString interface () const
Returns the name of this interface.
bool isValid () const
Returns true if this is a valid reference to a remote object.
QDBusError lastError () const
Returns the error the last operation produced, or an invalid error if the last operation did not produce an error.
QString path () const
Returns the object path that this interface is associated with.
QString service () const
Returns the name of the service this interface is associated with.
void setTimeout (int timeout)
Sets the timeout in milliseconds for all future DBus calls to timeout.
int timeout () const
Returns the current value of the timeout in milliseconds.
virtual ~QDBusAbstractInterface ()
Releases this object's resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void connectNotify (const char *signal)
Catch signal connections.
void disconnectNotify (const char *signal)
Catch signal disconnections.
QVariant getProperty (const QString &)
Protected Functions inherited from QDBusAbstractInterface
QDBusMessage internalConstCall (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args=QList< QVariant >()) const
QVariant internalPropGet (const char *propname) const
Get the value of the property propname.
void internalPropSet (const char *propname, const QVariant &value)
Set the value of the property propname to value.
QDBusAbstractInterface (const QString &service, const QString &path, const char *interface, const QDBusConnection &connection, QObject *parent)
This is the constructor called from static classes derived from QDBusAbstractInterface (i.
QDBusAbstractInterface (QDBusAbstractInterfacePrivate &, QObject *parent)
This is the constructor called from QDBusInterface::QDBusInterface.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 112 of file qconnmanservice_linux_p.h.
Constructors and Destructors
QConnmanManagerInterface()
QConnmanManagerInterface::QConnmanManagerInterface (QObject * parent = 0)
Definition at line 81 of file qconnmanservice_linux.cpp.
         : QDBusAbstractInterface(QLatin1String(CONNMAN_SERVICE),
                                  QLatin1String(CONNMAN_MANAGER_PATH),
                                  CONNMAN_MANAGER_INTERFACE,
                                  QDBusConnection::systemBus(), parent)
 {
     qDBusRegisterMetaType<ConnmanMap>();
     qDBusRegisterMetaType<ConnmanMapList>();
     qRegisterMetaType<ConnmanMapList>("ConnmanMapList");
 }
~QConnmanManagerInterface()
QConnmanManagerInterface::~QConnmanManagerInterface ()
Definition at line 92 of file qconnmanservice_linux.cpp.
 {
 }
Functions
connectNotify()
void QConnmanManagerInterface::connectNotify (const char * signal) protected virtual
Catch signal connections.
Warning
This function is not part of the public interface.
Reimplemented from QDBusAbstractInterface.
Definition at line 96 of file qconnmanservice_linux.cpp.
 {
 if (QLatin1String(signal) == SIGNAL(propertyChanged(QString,QDBusVariant))) {
         if(!connection().connect(QLatin1String(CONNMAN_SERVICE),
                                QLatin1String(CONNMAN_MANAGER_PATH),
                                QLatin1String(CONNMAN_MANAGER_INTERFACE),
                                QLatin1String("PropertyChanged"),
                                this,SIGNAL(propertyChanged(const QString &, const QDBusVariant & )))) {
             qWarning() << "PropertyCHanged not connected";
         }
     }
     if (QLatin1String(signal) == SIGNAL(stateChanged(QString))) {
         if (!connection().connect(QLatin1String(CONNMAN_SERVICE),
                                     QLatin1String(CONNMAN_MANAGER_PATH),
                                     QLatin1String(CONNMAN_MANAGER_INTERFACE),
                                     QLatin1String("StateChanged"),
                                     this,SIGNAL(stateChanged(const QString&)))) {
             qWarning() << "StateChanged not connected";
         }
     }
     if (QLatin1String(signal) == SIGNAL(propertyChangedContext(QString,QString,QDBusVariant))) {
         QConnmanDBusHelper *helper;
         helper = new QConnmanDBusHelper(this);
         dbusConnection.connect(QLatin1String(CONNMAN_SERVICE),
                                QLatin1String(CONNMAN_MANAGER_PATH),
                                QLatin1String(CONNMAN_MANAGER_INTERFACE),
                                QLatin1String("PropertyChanged"),
                                helper,SLOT(propertyChanged(QString,QDBusVariant)));
         QObject::connect(helper,SIGNAL(propertyChangedContext(const QString &,const QString &,const QDBusVariant &)),
                 this,SIGNAL(propertyChangedContext(const QString &,const QString &,const QDBusVariant &)), Qt::UniqueConnection);
     }
 }
connectService()
QDBusObjectPath QConnmanManagerInterface::connectService (QVariantMap & map)
Definition at line 218 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QDBusObjectPath > reply =  this->call(QLatin1String("ConnectService"), QVariant::fromValue(map));
     if(!reply.isValid()) {
         qDebug() << reply.error().message();
     }
     return reply;
 }
createProfile()
QDBusObjectPath QConnmanManagerInterface::createProfile (const QString & name)
Definition at line 174 of file qconnmanservice_linux.cpp.
 {
     return QDBusObjectPath();
 }
disableTechnology()
bool QConnmanManagerInterface::disableTechnology (const QString & type)
Definition at line 207 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QList<QDBusObjectPath> > reply =  this->call(QLatin1String("DisableTechnology"), QVariant::fromValue(type));
     bool ok = true;
     if(reply.error().type() == QDBusError::InvalidArgs) {
         qWarning() << reply.error().message();
         ok = false;
     }
     return ok;
 }
disconnectNotify()
void QConnmanManagerInterface::disconnectNotify (const char * signal) protected virtual
Catch signal disconnections.
Warning
This function is not part of the public interface.
Reimplemented from QDBusAbstractInterface.
Definition at line 134 of file qconnmanservice_linux.cpp.
 {
     if (QLatin1String(signal) == SIGNAL(propertyChanged(QString,QVariant))) {
     }
 }
enableTechnology()
bool QConnmanManagerInterface::enableTechnology (const QString & type)
Definition at line 196 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QList<QDBusObjectPath> > reply =  this->call(QLatin1String("EnableTechnology"), QVariant::fromValue(type));
     bool ok = true;
     if(reply.error().type() == QDBusError::InvalidArgs) {
         qWarning() << reply.error().message();
         ok = false;
     }
     return ok;
 }
getActiveProfile()
QString QConnmanManagerInterface::getActiveProfile ()
Definition at line 307 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("ActiveProfile");
     return qdbus_cast<QString>(var);
 }
getAvailableTechnologies()
QStringList QConnmanManagerInterface::getAvailableTechnologies ()
Definition at line 277 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("AvailableTechnologies");
     return qdbus_cast<QStringList>(var);
 }
getConnectedTechnologies()
QStringList QConnmanManagerInterface::getConnectedTechnologies ()
Definition at line 289 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("ConnectedTechnologies");
     return qdbus_cast<QStringList>(var);
 }
getDefaultTechnology()
QString QConnmanManagerInterface::getDefaultTechnology ()
Definition at line 295 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("DefaultTechnology");
     return qdbus_cast<QString>(var);
 }
getEnabledTechnologies()
QStringList QConnmanManagerInterface::getEnabledTechnologies ()
Definition at line 283 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("EnabledTechnologies");
     return qdbus_cast<QStringList>(var);
 }
getOfflineMode()
bool QConnmanManagerInterface::getOfflineMode ()
Definition at line 301 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("OfflineMode");
     return qdbus_cast<bool>(var);
 }
getPathForTechnology()
QString QConnmanManagerInterface::getPathForTechnology (const QString & tech)
Definition at line 355 of file qconnmanservice_linux.cpp.
 {
     foreach(const QString path, getTechnologies()) {
         if(path.contains(name)) {
             return path;
         }
     }
     return "";
 }
getProfiles()
QStringList QConnmanManagerInterface::getProfiles ()
Definition at line 313 of file qconnmanservice_linux.cpp.
 {
     QVariant var = getProperty("Profiles");
     return qdbus_cast<QStringList>(var);
 }
getProperties()
QVariantMap QConnmanManagerInterface::getProperties ()
Definition at line 153 of file qconnmanservice_linux.cpp.
Referenced by getProperty().
 {
     if(this->isValid()) {
         QDBusReply<QVariantMap > reply =  this->call(QLatin1String("GetProperties"));
         return reply.value();
     } else return QVariantMap();
 }
getProperty()
QVariant QConnmanManagerInterface::getProperty (const QString & property) protected
Definition at line 141 of file qconnmanservice_linux.cpp.
Referenced by getActiveProfile(), getAvailableTechnologies(), getConnectedTechnologies(), getDefaultTechnology(), getEnabledTechnologies(), getOfflineMode(), getProfiles(), getServices(), and getTechnologies().
 {
     QVariant var;
     QVariantMap map = getProperties();
     if (map.contains(property)) {
         var = map.value(property);
     } else {
         qDebug() << "does not contain" << property;
     }
     return var;
 }
getServices()
QStringList QConnmanManagerInterface::getServices ()
Definition at line 337 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::initialize().
 {
     QStringList list;
     QDBusReply<ConnmanMapList> replyList = this->call(QLatin1String("GetServices"));
     if (replyList.isValid()) {
         Q_FOREACH (ConnmanMap map, replyList.value()) {
             list << map.objectPath.path();
         }
     } else {
         // try for older version
         QVariant var = getProperty("Services");
         if (!var.isNull()) {
             list = qdbus_cast<QStringList>(var);
         }
     }
     return list;
 }
getState()
QString QConnmanManagerInterface::getState ()
Definition at line 161 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QString > reply =  this->call("GetState");
     return reply.value();
 }
getTechnologies()
QStringList QConnmanManagerInterface::getTechnologies ()
Definition at line 319 of file qconnmanservice_linux.cpp.
Referenced by getPathForTechnology(), and QConnmanEngine::initialize().
 {
     QStringList list;
     QDBusReply<ConnmanMapList> replyList = this->call(QLatin1String("GetTechnologies"));
     if (replyList.isValid()) {
         Q_FOREACH (ConnmanMap map, replyList.value()) {
             list << map.objectPath.path();
         }
     } else {
         // try for older version
         QVariant var = getProperty("Technologies");
         if (!var.isNull()) {
             list = qdbus_cast<QStringList>(var);
         }
     }
     return list;
 }
lookupService()
QDBusObjectPath QConnmanManagerInterface::lookupService (const QString & service)
Definition at line 266 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QDBusObjectPath > reply =  this->call(QLatin1String("LookupService"), QVariant::fromValue(service));
     if(!reply.isValid()) {
         qDebug() << reply.error().message();
     }
     return reply;
 }
path()
QDBusObjectPath QConnmanManagerInterface::path () const
Referenced by getPathForTechnology().
propertyChanged
void QConnmanManagerInterface::propertyChanged (const QString & , const QDBusVariant & value) signal
Referenced by connectNotify(), and disconnectNotify().
propertyChangedContext
void QConnmanManagerInterface::propertyChangedContext (const QString & , const QString & , const QDBusVariant &) signal
Referenced by connectNotify().
registerAgent()
void QConnmanManagerInterface::registerAgent (QDBusObjectPath & path)
Definition at line 228 of file qconnmanservice_linux.cpp.
 {
 }
registerCounter()
void QConnmanManagerInterface::registerCounter (const QString & path, quint32 interval)
Definition at line 236 of file qconnmanservice_linux.cpp.
 {   QDBusReply<QList<QDBusObjectPath> > reply =  this->call(QLatin1String("RegisterCounter"),
                                                             QVariant::fromValue(path),
                                                             QVariant::fromValue(interval));
     if(reply.error().type() == QDBusError::InvalidArgs) {
         qWarning() << reply.error().message();
     }
 }
releaseSession()
void QConnmanManagerInterface::releaseSession ()
Definition at line 260 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QList<QDBusObjectPath> > reply =  this->call(QLatin1String("ReleaseSession"));
 }
removeProfile()
bool QConnmanManagerInterface::removeProfile (QDBusObjectPath path)
Definition at line 179 of file qconnmanservice_linux.cpp.
 {
     return false;
 }
requestScan()
bool QConnmanManagerInterface::requestScan (const QString & type)
Definition at line 184 of file qconnmanservice_linux.cpp.
Referenced by QConnmanEngine::doRequestUpdate().
 {
     QDBusReply<QString> reply =  this->call(QLatin1String("RequestScan"), QVariant::fromValue(type));
     bool ok = true;
     if(reply.error().type() == QDBusError::InvalidArgs) {
         qWarning() << reply.error().message();
         ok = false;
     }
     return ok;
 }
requestSession()
QString QConnmanManagerInterface::requestSession (const QString & bearerName)
Definition at line 253 of file qconnmanservice_linux.cpp.
 {
     QDBusReply<QList<QDBusObjectPath> > reply =  this->call(QLatin1String("RequestSession"),
                                                             QVariant::fromValue(bearerName));
     return QString();
 }
setProperty()
bool QConnmanManagerInterface::setProperty (const QString & name, const QDBusVariant & value)
Definition at line 167 of file qconnmanservice_linux.cpp.
 {
     Q_UNUSED(name);
     Q_UNUSED(value);
     return false;
 }
stateChanged
void QConnmanManagerInterface::stateChanged (const QString &) signal
Referenced by connectNotify().
unregisterAgent()
void QConnmanManagerInterface::unregisterAgent (QDBusObjectPath path)
Definition at line 232 of file qconnmanservice_linux.cpp.
 {
 }
unregisterCounter()
void QConnmanManagerInterface::unregisterCounter (const QString & path)
Definition at line 245 of file qconnmanservice_linux.cpp.
 {   QDBusReply<QList<QDBusObjectPath> > reply =  this->call(QLatin1String("UnregisterCounter"),
                                                             QVariant::fromValue(path));
     if(reply.error().type() == QDBusError::InvalidArgs) {
         qWarning() << reply.error().message();
     }
 }
The documentation for this class was generated from the following files:
/src/plugins/bearer/connman/qconnmanservice_linux_p.h
/src/plugins/bearer/connman/qconnmanservice_linux.cpp