Qt 4.8: QMessageBox Class Reference
QMessageBox Class Reference
The QMessageBox class provides a modal dialog for informing the user or for asking the user a question and receiving an answer.
#include <qmessagebox.h>
Public Types
typedef StandardButton Button
Use QMessageBox::StandardButton instead.
enum ButtonRole {
InvalidRole = -1, AcceptRole, RejectRole, DestructiveRole,
ActionRole, HelpRole, YesRole, NoRole,
ResetRole, ApplyRole, NRoles
}
Combinations of these roles are as flags used to describe different aspects of their behavior.
enum Icon {
NoIcon = 0, Information = 1, Warning = 2, Critical = 3,
Question = 4
}
This enum has the following values:
enum StandardButton {
NoButton = 0x00000000, Ok = 0x00000400, Save = 0x00000800, SaveAll = 0x00001000,
Open = 0x00002000, Yes = 0x00004000, YesToAll = 0x00008000, No = 0x00010000,
NoToAll = 0x00020000, Abort = 0x00040000, Retry = 0x00080000, Ignore = 0x00100000,
Close = 0x00200000, Cancel = 0x00400000, Discard = 0x00800000, Help = 0x01000000,
Apply = 0x02000000, Reset = 0x04000000, RestoreDefaults = 0x08000000, FirstButton = Ok,
LastButton = RestoreDefaults, YesAll = YesToAll, NoAll = NoToAll, Default = 0x00000100,
Escape = 0x00000200, FlagMask = 0x00000300, ButtonMask = ~FlagMask
}
These enums describe flags for standard buttons.
Public Types inherited from QDialog
enum DialogCode { Rejected, Accepted }
The value returned by a modal dialog.
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
int exec ()
Shows the message box as a modal dialog, blocking until the user closes it.
Public Slots inherited from QDialog
virtual void accept ()
Hides the modal dialog and sets the result code to Accepted.
virtual void done (int)
Closes the dialog and sets its result code to r.
int exec ()
Shows the dialog as a modal dialog, blocking until the user closes it.
void open ()
Shows the dialog as a window modal dialog, returning immediately.
virtual void reject ()
Hides the modal dialog and sets the result code to Rejected.
void showExtension (bool)
If showIt is true, the dialog's extension is shown; otherwise the extension is hidden.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void buttonClicked (QAbstractButton *button)
This signal is emitted whenever a button is clicked inside the QMessageBox.
Signals inherited from QDialog
void accepted ()
This signal is emitted when the dialog has been accepted either by the user or by calling accept() or done() with the QDialog::Accepted argument.
void finished (int result)
This signal is emitted when the dialog's result code has been set, either by the user or by calling done(), accept(), or reject().
void rejected ()
This signal is emitted when the dialog has been rejected either by the user or by calling reject() or done() with the QDialog::Rejected argument.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addButton (QAbstractButton *button, ButtonRole role)
Adds the given button to the message box with the specified role.
QPushButton * addButton (const QString &text, ButtonRole role)
Creates a button with the given text, adds it to the message box for the specified role, and returns it.
QPushButton * addButton (StandardButton button)
Adds a standard button to the message box if it is valid to do so, and returns the push button.
QAbstractButton * button (StandardButton which) const
Returns a pointer corresponding to the standard button which, or 0 if the standard button doesn't exist in this message box.
ButtonRole buttonRole (QAbstractButton *button) const
Returns the button role for the specified button.
QList< QAbstractButton * > buttons () const
Returns a list of all the buttons that have been added to the message box.
QString buttonText (int button) const
Returns the text of the message box button button, or an empty string if the message box does not contain the button.
QAbstractButton * clickedButton () const
Returns the button that was clicked by the user, or 0 if the user hit the Esc key and no escape button was set.
QPushButton * defaultButton () const
Returns the button that should be the message box's default button.
QString detailedText () const
QAbstractButton * escapeButton () const
Returns the button that is activated when escape is pressed.
Icon icon () const
QPixmap iconPixmap () const
QString informativeText () const
void open (QObject *receiver, const char *member)
Opens the dialog and connects its finished() or buttonClicked() signal to the slot specified by receiver and member.
QMessageBox (QWidget *parent=0)
Constructs a message box with no text and no buttons.
QMessageBox (Icon icon, const QString &title, const QString &text, StandardButtons buttons=NoButton, QWidget *parent=0, Qt::WindowFlags flags=Qt::Dialog|Qt::MSWindowsFixedSizeDialogHint)
Constructs a message box with the given icon, title, text, and standard buttons.
QMessageBox (const QString &title, const QString &text, Icon icon, int button0, int button1, int button2, QWidget *parent=0, Qt::WindowFlags f=Qt::Dialog|Qt::MSWindowsFixedSizeDialogHint)
Constructs a message box with a title, a text, an icon, and up to three buttons.
void removeButton (QAbstractButton *button)
Removes button from the button box without deleting it.
void setButtonText (int button, const QString &text)
Sets the text of the message box button button to text.
void setDefaultButton (QPushButton *button)
Sets the message box's default button to button.
void setDefaultButton (StandardButton button)
Sets the message box's default button to button.
void setDetailedText (const QString &text)
void setEscapeButton (QAbstractButton *button)
Sets the button that gets activated when the Escape key is pressed to button.
void setEscapeButton (StandardButton button)
Sets the buttons that gets activated when the Escape key is pressed to button.
void setIcon (Icon)
void setIconPixmap (const QPixmap &pixmap)
void setInformativeText (const QString &text)
void setStandardButtons (StandardButtons buttons)
void setText (const QString &text)
void setTextFormat (Qt::TextFormat format)
void setVisible (bool visible)
Reimplemented Function
void setWindowModality (Qt::WindowModality windowModality)
This function shadows QWidget::setWindowModality().
void setWindowTitle (const QString &title)
This function shadows QWidget::setWindowTitle().
QSize sizeHint () const
StandardButton standardButton (QAbstractButton *button) const
Returns the standard button enum value corresponding to the given button, or NoButton if the given button isn't a standard button.
StandardButtons standardButtons () const
QString text () const
Qt::TextFormat textFormat () const
~QMessageBox ()
Destroys the message box.
Public Functions inherited from QDialog
QWidget * extension () const
Returns the dialog's extension or 0 if no extension has been defined.
bool isSizeGripEnabled () const
QSize minimumSizeHint () const
Reimplemented Function
Qt::Orientation orientation () const
Returns the dialog's extension orientation.
QDialog (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a dialog with parent parent.
int result () const
In general returns the modal dialog's result code, Accepted or Rejected.
void setExtension (QWidget *extension)
Sets the widget, extension, to be the dialog's extension, deleting any previous extension.
void setModal (bool modal)
void setOrientation (Qt::Orientation orientation)
If orientation is Qt::Horizontal, the extension will be displayed to the right of the dialog's main area.
void setResult (int r)
Sets the modal dialog's result code to i.
void setSizeGripEnabled (bool)
~QDialog ()
Destroys the QDialog, deleting all its children.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static void about (QWidget *parent, const QString &title, const QString &text)
Displays a simple about box with title title and text text.
static void aboutQt (QWidget *parent, const QString &title=QString())
Displays a simple message box about Qt, with the given title and centered over parent (if parent is not 0).
static StandardButton critical (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
Opens a critical message box with the given title and text in front of the specified parent widget.
static int critical (QWidget *parent, const QString &title, const QString &text, int button0, int button1, int button2=0)
Opens a critical message box with the given title and text.
static int critical (QWidget *parent, const QString &title, const QString &text, const QString &button0Text, const QString &button1Text=QString(), const QString &button2Text=QString(), int defaultButtonNumber=0, int escapeButtonNumber=-1)
Displays a critical error message box with the given title and text, as well as one, two, or three buttons.
static int critical (QWidget *parent, const QString &title, const QString &text, StandardButton button0, StandardButton button1)
static StandardButton information (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
Opens an information message box with the given title and text in front of the specified parent widget.
static int information (QWidget *parent, const QString &title, const QString &text, int button0, int button1=0, int button2=0)
Opens an information message box with the given title and the text.
static int information (QWidget *parent, const QString &title, const QString &text, const QString &button0Text, const QString &button1Text=QString(), const QString &button2Text=QString(), int defaultButtonNumber=0, int escapeButtonNumber=-1)
Displays an information message box with the given title and text, as well as one, two or three buttons.
static StandardButton information (QWidget *parent, const QString &title, const QString &text, StandardButton button0, StandardButton button1=NoButton)
static StandardButton question (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
Opens a question message box with the given title and text in front of the specified parent widget.
static int question (QWidget *parent, const QString &title, const QString &text, int button0, int button1=0, int button2=0)
Opens a question message box with the given title and text.
static int question (QWidget *parent, const QString &title, const QString &text, const QString &button0Text, const QString &button1Text=QString(), const QString &button2Text=QString(), int defaultButtonNumber=0, int escapeButtonNumber=-1)
Displays a question message box with the given title and text, as well as one, two or three buttons.
static int question (QWidget *parent, const QString &title, const QString &text, StandardButton button0, StandardButton button1)
static QPixmap standardIcon (Icon icon)
Returns the pixmap used for a standard icon.
static StandardButton warning (QWidget *parent, const QString &title, const QString &text, StandardButtons buttons=Ok, StandardButton defaultButton=NoButton)
Opens a warning message box with the given title and text in front of the specified parent widget.
static int warning (QWidget *parent, const QString &title, const QString &text, int button0, int button1, int button2=0)
Opens a warning message box with the given title and text.
static int warning (QWidget *parent, const QString &title, const QString &text, const QString &button0Text, const QString &button1Text=QString(), const QString &button2Text=QString(), int defaultButtonNumber=0, int escapeButtonNumber=-1)
Displays a warning message box with the given title and text, as well as one, two, or three buttons.
static int warning (QWidget *parent, const QString &title, const QString &text, StandardButton button0, StandardButton button1)
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
void changeEvent (QEvent *event)
Reimplemented Function
void closeEvent (QCloseEvent *event)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
Reimplemented Function
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void showEvent (QShowEvent *event)
Reimplemented Function
Protected Functions inherited from QDialog
void adjustPosition (QWidget *)
void contextMenuEvent (QContextMenuEvent *)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
QDialog (QDialogPrivate &, QWidget *parent, Qt::WindowFlags f=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
QString detailedText
the text to be displayed in the details area.
Icon icon
the message box's icon
QPixmap iconPixmap
the current icon
QString informativeText
the informative text that provides a fuller description for the message
StandardButtons standardButtons
collection of standard buttons in the message box
QString text
the message box text to be displayed.
Qt::TextFormat textFormat
the format of the text displayed by the message box
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QMessageBox class provides a modal dialog for informing the user or for asking the user a question and receiving an answer.
A message box displays a primary text to alert the user to a situation, an informative text to further explain the alert or to ask the user a question, and an optional detailed text to provide even more data if the user requests it. A message box can also display an icon and standard buttons for accepting a user response.
Two APIs for using QMessageBox are provided, the property-based API, and the static functions. Calling one of the static functions is the simpler approach, but it is less flexible than using the property-based API, and the result is less informative. Using the property-based API is recommended.
The Property-based API
To use the property-based API, construct an instance of QMessageBox, set the desired properties, and call exec() to show the message. The simplest configuration is to set only the message text property.
QMessageBox msgBox;
msgBox.setText("The document has been modified.");
msgBox.exec();
The user must click the OK button to dismiss the message box. The rest of the GUI is blocked until the message box is dismissed.
A better approach than just alerting the user to an event is to also ask the user what to do about it. Store the question in the informative text property, and set the standard buttons property to the set of buttons you want as the set of user responses. The buttons are specified by combining values from StandardButtons using the bitwise OR operator. The display order for the buttons is platform-dependent. For example, on Windows, Save is displayed to the left of Cancel, whereas on Mac OS, the order is reversed.
Mark one of your standard buttons to be your default button.
QMessageBox msgBox;
msgBox.setText("The document has been modified.");
msgBox.setInformativeText("Do you want to save your changes?");
msgBox.setStandardButtons(QMessageBox::Save | QMessageBox::Discard | QMessageBox::Cancel);
msgBox.setDefaultButton(QMessageBox::Save);
int ret = msgBox.exec();
This is the approach recommended in the Mac OS X Guidelines. Similar guidelines apply for the other platforms, but note the different ways the informative text is handled for different platforms.
The exec() slot returns the StandardButtons value of the button that was clicked.
switch (ret) {
  case QMessageBox::Save:
      // Save was clicked
      break;
  case QMessageBox::Discard:
      // Don't Save was clicked
      break;
  case QMessageBox::Cancel:
      // Cancel was clicked
      break;
  default:
      // should never be reached
      break;
}
To give the user more information to help him answer the question, set the detailed text property. If the detailed text property is set, the Show Details... button will be shown.
Clicking the Show Details... button displays the detailed text.
Rich Text and the Text Format Property
The detailed text property is always interpreted as plain text. The main text and informative text properties can be either plain text or rich text. These strings are interpreted according to the setting of the text format property. The default setting is auto-text.
Note that for some plain text strings containing XML meta-characters, the auto-text rich text detection test may fail causing your plain text string to be interpreted incorrectly as rich text. In these rare cases, use Qt::convertFromPlainText() to convert your plain text string to a visually equivalent rich text string, or set the text format property explicitly with setTextFormat().
Severity Levels and the Icon and Pixmap Properties
QMessageBox supports four predefined message severity levels, or message types, which really only differ in the predefined icon they each show. Specify one of the four predefined message types by setting the icon property to one of the predefined icons. The following rules are guidelines:
Question For asking a question during normal operations.
Information For reporting information about normal operations.
Warning For reporting non-critical errors.
Critical For reporting critical errors.
Predefined icons are not defined by QMessageBox, but provided by the style. The default value is No Icon. The message boxes are otherwise the same for all cases. When using a standard icon, use the one recommended in the table, or use the one recommended by the style guidelines for your platform. If none of the standard icons is right for your message box, you can use a custom icon by setting the icon pixmap property instead of setting the icon property.
In summary, to set an icon, use either setIcon() for one of the standard icons, or setIconPixmap() for a custom icon.
The Static Functions API
Building message boxes with the static functions API, although convenient, is less flexible than using the property-based API, because the static function signatures lack parameters for setting the informative text and detailed text properties. One work-around for this has been to use the title parameter as the message box main text and the text parameter as the message box informative text. Because this has the obvious drawback of making a less readable message box, platform guidelines do not recommend it. The Microsoft Windows User Interface Guidelines recommend using the application name as the window's title, which means that if you have an informative text in addition to your main text, you must concatenate it to the text parameter.
Note that the static function signatures have changed with respect to their button parameters, which are now used to set the standard buttons and the default button.
Static functions are available for creating information(), question(), warning(), and critical() message boxes.
int ret = QMessageBox::warning(this, tr("My Application"),
                               tr("The document has been modified.\n"
                                  "Do you want to save your changes?"),
                               QMessageBox::Save | QMessageBox::Discard
                               | QMessageBox::Cancel,
                               QMessageBox::Save);
The Standard Dialogs example shows how to use QMessageBox and the other built-in Qt dialogs.
Advanced Usage
If the standard buttons are not flexible enough for your message box, you can use the addButton() overload that takes a text and a ButtonRoleto to add custom buttons. The ButtonRole is used by QMessageBox to determine the ordering of the buttons on screen (which varies according to the platform). You can test the value of clickedButton() after calling exec(). For example,
QMessageBox msgBox;
QPushButton *connectButton = msgBox.addButton(tr("Connect"), QMessageBox::ActionRole);
QPushButton *abortButton = msgBox.addButton(QMessageBox::Abort);
msgBox.exec();
if (msgBox.clickedButton() == connectButton) {
    // connect
} else if (msgBox.clickedButton() == abortButton) {
    // abort
}
Default and Escape Keys
The default button (i.e., the button activated when Enter is pressed) can be specified using setDefaultButton(). If a default button is not specified, QMessageBox tries to find one based on the button roles of the buttons used in the message box.
The escape button (the button activated when Esc is pressed) can be specified using setEscapeButton(). If an escape button is not specified, QMessageBox tries to find one using these rules:
If there is only one button, it is the button activated when Esc is pressed.
If there is a Cancel button, it is the button activated when Esc is pressed.
If there is exactly one button having either the Reject role or the the No role, it is the button activated when Esc is pressed.
When an escape button can't be determined using these rules, pressing Esc has no effect.
See also
QDialogButtonBox, {fowler}{GUI Design Handbook: Message Box}, {Standard Dialogs Example}, {Application Example}
Definition at line 59 of file qmessagebox.h.
Typedefs
Button
QMessageBox::Button
Use QMessageBox::StandardButton instead.
Definition at line 133 of file qmessagebox.h.
Enumerations
ButtonRole
enum QMessageBox::ButtonRole
Combinations of these roles are as flags used to describe different aspects of their behavior.
InvalidRole The button is invalid.
AcceptRole Clicking the button causes the dialog to be accepted (e.g. OK).
RejectRole Clicking the button causes the dialog to be rejected (e.g. Cancel).
DestructiveRole Clicking the button causes a destructive change (e.g. for Discarding Changes) and closes the dialog.
ActionRole Clicking the button causes changes to the elements within the dialog.
HelpRole The button can be clicked to request help.
YesRole The button is a "Yes"-like button.
NoRole The button is a "No"-like button.
ApplyRole The button applies current changes.
ResetRole The button resets the dialog's fields to default values.
NRoles
See also
StandardButton
Enumerator
InvalidRole
AcceptRole
RejectRole
DestructiveRole
ActionRole
HelpRole
YesRole
NoRole
ResetRole
ApplyRole
NRoles
Definition at line 84 of file qmessagebox.h.
                     {
         // keep this in sync with QDialogButtonBox::ButtonRole
         InvalidRole = -1,
         AcceptRole,
         RejectRole,
         DestructiveRole,
         ActionRole,
         HelpRole,
         YesRole,
         NoRole,
         ResetRole,
         ApplyRole,
         NRoles
     };
Icon
enum QMessageBox::Icon
This enum has the following values:
NoIcon the message box does not have any icon.
Question an icon indicating that the message is asking a question.
Information an icon indicating that the message is nothing out of the ordinary.
Warning an icon indicating that the message is a warning, but can be dealt with.
Critical an icon indicating that the message represents a critical problem.
Enumerator
NoIcon
Information
Warning
Critical
Question
Definition at line 76 of file qmessagebox.h.
               {
         NoIcon = 0,
         Information = 1,
         Warning = 2,
         Critical = 3,
         Question = 4
     };
StandardButton
enum QMessageBox::StandardButton
These enums describe flags for standard buttons.
Since
4.2
Each button has a defined ButtonRole .
Ok An "OK" button defined with the AcceptRole .
Open A "Open" button defined with the AcceptRole .
Save A "Save" button defined with the AcceptRole .
Cancel A "Cancel" button defined with the RejectRole .
Close A "Close" button defined with the RejectRole .
Discard A "Discard" or "Don't Save" button, depending on the platform, defined with the DestructiveRole .
Apply An "Apply" button defined with the ApplyRole .
Reset A "Reset" button defined with the ResetRole .
RestoreDefaults A "Restore Defaults" button defined with the ResetRole .
Help A "Help" button defined with the HelpRole .
SaveAll A "Save All" button defined with the AcceptRole .
Yes A "Yes" button defined with the YesRole .
YesToAll A "Yes to All" button defined with the YesRole .
No A "No" button defined with the NoRole .
NoToAll A "No to All" button defined with the NoRole .
Abort An "Abort" button defined with the RejectRole .
Retry A "Retry" button defined with the AcceptRole .
Ignore An "Ignore" button defined with the AcceptRole .
NoButton An invalid button.
FirstButton
LastButton
The following values are obsolete:
YesAll Use YesToAll instead.
NoAll Use NoToAll instead.
Default Use the defaultButton argument of information(), warning(), etc. instead, or call setDefaultButton().
Escape Call setEscapeButton() instead.
FlagMask
ButtonMask
See also
ButtonRole, standardButtons
Enumerator
NoButton
Ok
Save
SaveAll
Open
Yes
YesToAll
No
NoToAll
Abort
Retry
Ignore
Close
Cancel
Discard
Apply
Reset
RestoreDefaults
FirstButton
LastButton
YesAll
NoAll
Default
Escape
FlagMask
ButtonMask
Definition at line 100 of file qmessagebox.h.
{
         // keep this in sync with QDialogButtonBox::StandardButton
         NoButton           = 0x00000000,
         Ok                 = 0x00000400,
         Save               = 0x00000800,
         SaveAll            = 0x00001000,
         Open               = 0x00002000,
         Yes                = 0x00004000,
         YesToAll           = 0x00008000,
         No                 = 0x00010000,
         NoToAll            = 0x00020000,
         Abort              = 0x00040000,
         Retry              = 0x00080000,
         Ignore             = 0x00100000,
         Close              = 0x00200000,
         Cancel             = 0x00400000,
         Discard            = 0x00800000,
         Help               = 0x01000000,
         Apply              = 0x02000000,
         Reset              = 0x04000000,
         RestoreDefaults    = 0x08000000,
         FirstButton        = Ok,                // internal
         LastButton         = RestoreDefaults,   // internal
         YesAll             = YesToAll,          // obsolete
         NoAll              = NoToAll,           // obsolete
         Default            = 0x00000100,        // obsolete
         Escape             = 0x00000200,        // obsolete
         FlagMask           = 0x00000300,        // obsolete
         ButtonMask         = ~FlagMask          // obsolete
     };
Constructors and Destructors
QMessageBox() [1/3]
QMessageBox::QMessageBox (QWidget * parent = 0) explicit
Constructs a message box with no text and no buttons.
parent is passed to the QDialog constructor.
On Mac OS X, if you want your message box to appear as a Qt::Sheet of its parent, set the message box's window modality to Qt::WindowModal or use open(). Otherwise, the message box will be a standard dialog.
Definition at line 776 of file qmessagebox.cpp.
Referenced by about(), aboutQt(), and setWindowModality().
     : QDialog(*new QMessageBoxPrivate, parent, Qt::MSWindowsFixedSizeDialogHint | Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint)
 {
     Q_D(QMessageBox);
     d->init();
 }
QMessageBox() [2/3]
QMessageBox::QMessageBox (Icon icon, const QString & title, const QString & text, StandardButtons buttons = NoButton, QWidget * parent = 0, Qt::WindowFlags f = Qt::Dialog | Qt::MSWindowsFixedSizeDialogHint)
Constructs a message box with the given icon, title, text, and standard buttons.
Standard or custom buttons can be added at any time using addButton(). The parent and f arguments are passed to the QDialog constructor.
The message box is an application modal dialog box.
On Mac OS X, if parent is not 0 and you want your message box to appear as a Qt::Sheet of that parent, set the message box's window modality to Qt::WindowModal (default). Otherwise, the message box will be a standard dialog.
See also
setWindowTitle(), setText(), setIcon(), setStandardButtons()
Definition at line 799 of file qmessagebox.cpp.
 : QDialog(*new QMessageBoxPrivate, parent, f | Qt::MSWindowsFixedSizeDialogHint | Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint)
 {
     Q_D(QMessageBox);
     d->init(title, text);
     setIcon(icon);
     if (buttons != NoButton)
         setStandardButtons(buttons);
 }
~QMessageBox()
QMessageBox::~QMessageBox ()
Destroys the message box.
Definition at line 814 of file qmessagebox.cpp.
 {
 }
QMessageBox() [3/3]
QMessageBox::QMessageBox (const QString & title, const QString & text, Icon icon, int button0, int button1, int button2, QWidget * parent = 0, Qt::WindowFlags f = Qt::Dialog | Qt::MSWindowsFixedSizeDialogHint)
Constructs a message box with a title, a text, an icon, and up to three buttons.
The icon must be one of the following:
QMessageBox::NoIcon
QMessageBox::Question
QMessageBox::Information
QMessageBox::Warning
QMessageBox::Critical
Each button, button0, button1 and button2, can have one of the following values:
QMessageBox::NoButton
QMessageBox::Ok
QMessageBox::Cancel
QMessageBox::Yes
QMessageBox::No
QMessageBox::Abort
QMessageBox::Retry
QMessageBox::Ignore
QMessageBox::YesAll
QMessageBox::NoAll
Use QMessageBox::NoButton for the later parameters to have fewer than three buttons in your message box. If you don't specify any buttons at all, QMessageBox will provide an Ok button.
One of the buttons can be OR-ed with the QMessageBox::Default flag to make it the default button (clicked when Enter is pressed).
One of the buttons can be OR-ed with the QMessageBox::Escape flag to make it the cancel or close button (clicked when Esc is pressed).
        QMessageBox mb("Application Name",
                       "Hardware failure.\n\nDisk error detected\nDo you want to stop?",
                       QMessageBox::Question,
                       QMessageBox::Yes | QMessageBox::Default,
                       QMessageBox::No | QMessageBox::Escape,
                       QMessageBox::NoButton);
        if (mb.exec() == QMessageBox::No) {
            // try again
The message box is an application modal dialog box.
The parent and f arguments are passed to the QDialog constructor.
See also
setWindowTitle(), setText(), setIcon()
Definition at line 2093 of file qmessagebox.cpp.
     : QDialog(*new QMessageBoxPrivate, parent,
               f /*| Qt::MSWindowsFixedSizeDialogHint #### */| Qt::WindowTitleHint | Qt::WindowSystemMenuHint | Qt::WindowCloseButtonHint)
 {
     Q_D(QMessageBox);
     d->init(title, text);
     setIcon(icon);
     d->addOldButtons(button0, button1, button2);
 }
Functions
about()
void QMessageBox::about (QWidget * parent, const QString & title, const QString & text) static
Displays a simple about box with title title and text text.
The about box's parent is parent.
about() looks for a suitable icon in four locations:
It prefers parent->icon() if that exists.
If not, it tries the top-level widget containing parent.
If that fails, it tries the active window.
As a last resort it uses the Information icon.
The about box has a single button labelled "OK". On Mac OS X, the about box is popped up as a modeless window; on other platforms, it is currently application modal.
See also
QWidget::windowIcon(), QApplication::activeWindow()
Definition at line 1773 of file qmessagebox.cpp.
 {
 #ifdef Q_WS_MAC
     static QPointer<QMessageBox> oldMsgBox;
     if (oldMsgBox && oldMsgBox->text() == text) {
         oldMsgBox->show();
         oldMsgBox->raise();
         oldMsgBox->activateWindow();
         return;
     }
 #endif
     QMessageBox *msgBox = new QMessageBox(title, text, Information, 0, 0, 0, parent
 #ifdef Q_WS_MAC
                                           , Qt::WindowTitleHint | Qt::WindowSystemMenuHint
 #endif
     );
     msgBox->setAttribute(Qt::WA_DeleteOnClose);
     QIcon icon = msgBox->windowIcon();
     QSize size = icon.actualSize(QSize(64, 64));
     msgBox->setIconPixmap(icon.pixmap(size));
     // should perhaps be a style hint
 #ifdef Q_WS_MAC
     oldMsgBox = msgBox;
 #if 0
     // ### doesn't work until close button is enabled in title bar
     msgBox->d_func()->autoAddOkButton = false;
 #else
     msgBox->d_func()->buttonBox->setCenterButtons(true);
 #endif
     msgBox->show();
 #else
     msgBox->exec();
 #endif
 }
aboutQt()
void QMessageBox::aboutQt (QWidget * parent, const QString & title = QString()) static
Displays a simple message box about Qt, with the given title and centered over parent (if parent is not 0).
The message includes the version number of Qt being used by the application.
This is useful for inclusion in the Help menu of an application, as shown in the Menus example.
QApplication provides this functionality as a slot.
On Mac OS X, the about box is popped up as a modeless window; on other platforms, it is currently application modal.
See also
QApplication::aboutQt()
Definition at line 1826 of file qmessagebox.cpp.
Referenced by QApplication::aboutQt(), and QApplicationPrivate::globalEventProcessor().
 {
 #ifdef Q_WS_MAC
     static QPointer<QMessageBox> oldMsgBox;
     if (oldMsgBox) {
         oldMsgBox->show();
         oldMsgBox->raise();
         oldMsgBox->activateWindow();
         return;
     }
 #endif
     QString translatedTextAboutQtCaption;
     translatedTextAboutQtCaption = QMessageBox::tr(
         "<h3>About Qt</h3>"
         "<p>This program uses Qt version %1.</p>"
         ).arg(QLatin1String(QT_VERSION_STR));
     QString translatedTextAboutQtText;
     translatedTextAboutQtText = QMessageBox::tr(
         "<p>Qt is a C++ toolkit for cross-platform application "
         "development.</p>"
         "<p>Qt provides single-source portability across MS&nbsp;Windows, "
         "Mac&nbsp;OS&nbsp;X, Linux, and all major commercial Unix variants. "
         "Qt is also available for embedded devices as Qt for Embedded Linux "
         "and Qt for Windows CE.</p>"
         "<p>Qt is available under three different licensing options designed "
         "to accommodate the needs of our various users.</p>"
         "<p>Qt licensed under our commercial license agreement is appropriate "
         "for development of proprietary/commercial software where you do not "
         "want to share any source code with third parties or otherwise cannot "
         "comply with the terms of the GNU LGPL version 2.1 or GNU GPL version "
         "3.0.</p>"
         "<p>Qt licensed under the GNU LGPL version 2.1 is appropriate for the "
         "development of Qt applications (proprietary or open source) provided "
         "you can comply with the terms and conditions of the GNU LGPL version "
         "2.1.</p>"
         "<p>Qt licensed under the GNU General Public License version 3.0 is "
         "appropriate for the development of Qt applications where you wish to "
         "use such applications in combination with software subject to the "
         "terms of the GNU GPL version 3.0 or where you are otherwise willing "
         "to comply with the terms of the GNU GPL version 3.0.</p>"
         "<p>Please see <a href=\"http://qt.digia.com/product/licensing\">qt.digia.com/product/licensing</a> "
         "for an overview of Qt licensing.</p>"
         "<p>Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).</p>"
         "<p>Qt is a Digia product. See <a href=\"http://qt.digia.com/\">qt.digia.com</a> "
         "for more information.</p>"
         );
     QMessageBox *msgBox = new QMessageBox(parent);
     msgBox->setAttribute(Qt::WA_DeleteOnClose);
     msgBox->setWindowTitle(title.isEmpty() ? tr("About Qt") : title);
     msgBox->setText(translatedTextAboutQtCaption);
     msgBox->setInformativeText(translatedTextAboutQtText);
     QPixmap pm(QLatin1String(":/trolltech/qmessagebox/images/qtlogo-64.png"));
     if (!pm.isNull())
         msgBox->setIconPixmap(pm);
 #if defined(Q_WS_WINCE)
     msgBox->setDefaultButton(msgBox->addButton(QMessageBox::Ok));
 #endif
     // should perhaps be a style hint
 #ifdef Q_WS_MAC
     oldMsgBox = msgBox;
 #if 0
     // ### doesn't work until close button is enabled in title bar
     msgBox->d_func()->autoAddOkButton = false;
 #else
     msgBox->d_func()->buttonBox->setCenterButtons(true);
 #endif
     msgBox->show();
 #else
     msgBox->exec();
 #endif
 }
addButton() [1/3]
void QMessageBox::addButton (QAbstractButton * button, ButtonRole role)
Adds the given button to the message box with the specified role.
Since
4.2
See also
removeButton(), button(), setStandardButtons()
Definition at line 829 of file qmessagebox.cpp.
Referenced by aboutQt(), addButton(), setButtonText(), showEvent(), showNewMessageBox(), and QMessageBoxPrivate::showOldMessageBox().
 {
     Q_D(QMessageBox);
     if (!button)
         return;
     removeButton(button);
     d->buttonBox->addButton(button, (QDialogButtonBox::ButtonRole)role);
     d->customButtonList.append(button);
     d->autoAddOkButton = false;
 }
addButton() [2/3]
QPushButton * QMessageBox::addButton (const QString & text, ButtonRole role)
Creates a button with the given text, adds it to the message box for the specified role, and returns it.
Since
4.2 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 850 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     QPushButton *pushButton = new QPushButton(text);
     addButton(pushButton, role);
     d->updateSize();
     return pushButton;
 }
addButton() [3/3]
QPushButton * QMessageBox::addButton (StandardButton button)
Adds a standard button to the message box if it is valid to do so, and returns the push button.
Since
4.2 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setStandardButtons()
Definition at line 871 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     QPushButton *pushButton = d->buttonBox->addButton((QDialogButtonBox::StandardButton)button);
     if (pushButton)
         d->autoAddOkButton = false;
     return pushButton;
 }
button()
QAbstractButton * QMessageBox::button (StandardButton which) const
Returns a pointer corresponding to the standard button which, or 0 if the standard button doesn't exist in this message box.
Since
4.2
See also
standardButtons, standardButton()
Definition at line 964 of file qmessagebox.cpp.
Referenced by QMessageBoxPrivate::findButton(), setDefaultButton(), and showNewMessageBox().
 {
     Q_D(const QMessageBox);
     return d->buttonBox->button(QDialogButtonBox::StandardButton(which));
 }
buttonClicked
void QMessageBox::buttonClicked (QAbstractButton * button) signal
This signal is emitted whenever a button is clicked inside the QMessageBox.
The button that was clicked in returned in button.
Referenced by open().
buttonRole()
QMessageBox::ButtonRole QMessageBox::buttonRole (QAbstractButton * button) const
Returns the button role for the specified button.
Since
4.5
This function returns InvalidRole if button is 0 or has not been added to the message box.
See also
buttons(), addButton()
Definition at line 1534 of file qmessagebox.cpp.
 {
     Q_D(const QMessageBox);
     return QMessageBox::ButtonRole(d->buttonBox->buttonRole(button));
 }
buttons()
QList< QAbstractButton * > QMessageBox::buttons () const
Returns a list of all the buttons that have been added to the message box.
Since
4.5
See also
buttonRole(), addButton(), removeButton()
Definition at line 1517 of file qmessagebox.cpp.
Referenced by QMessageBoxPrivate::detectEscapeButton(), and keyPressEvent().
 {
     Q_D(const QMessageBox);
     return d->buttonBox->buttons();
 }
buttonText()
QString QMessageBox::buttonText (int button) const
Returns the text of the message box button button, or an empty string if the message box does not contain the button.
Use button() and QPushButton::text() instead.
Definition at line 2484 of file qmessagebox.cpp.
 {
     Q_D(const QMessageBox);
     if (QAbstractButton *abstractButton = d->abstractButtonForId(button)) {
         return abstractButton->text();
     } else if (d->buttonBox->buttons().isEmpty() && (button == Ok || button == Old_Ok)) {
         // for compatibility with Qt 4.0/4.1
         return QDialogButtonBox::tr("OK");
     }
     return QString();
 }
changeEvent()
void QMessageBox::changeEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1375 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     switch (ev->type()) {
     case QEvent::StyleChange:
     {
         if (d->icon != NoIcon)
             setIcon(d->icon);
         Qt::TextInteractionFlags flags(style()->styleHint(QStyle::SH_MessageBox_TextInteractionFlags, 0, this));
         d->label->setTextInteractionFlags(flags);
         d->buttonBox->setCenterButtons(style()->styleHint(QStyle::SH_MessageBox_CenterButtons, 0, this));
         if (d->informativeLabel)
             d->informativeLabel->setTextInteractionFlags(flags);
         // intentional fall through
     }
     case QEvent::FontChange:
     case QEvent::ApplicationFontChange:
 #ifdef Q_WS_MAC
     {
         QFont f = font();
         f.setBold(true);
         d->label->setFont(f);
     }
 #endif
     default:
         break;
     }
     QDialog::changeEvent(ev);
 }
clickedButton()
QAbstractButton * QMessageBox::clickedButton () const
Returns the button that was clicked by the user, or 0 if the user hit the Esc key and no escape button was set.
Since
4.2
If exec() hasn't been called yet, returns 0.
Example:
QMessageBox messageBox(this);
QAbstractButton *disconnectButton =
      messageBox.addButton(tr("Disconnect"), QMessageBox::ActionRole);
...
messageBox.exec();
if (messageBox.clickedButton() == disconnectButton) {
    ...
}
See also
standardButton(), button()
Definition at line 1096 of file qmessagebox.cpp.
Referenced by showNewMessageBox().
 {
     Q_D(const QMessageBox);
     return d->clickedButton;
 }
closeEvent()
void QMessageBox::closeEvent (QCloseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 1360 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     if (!d->detectedEscapeButton) {
         e->ignore();
         return;
     }
     QDialog::closeEvent(e);
     d->clickedButton = d->detectedEscapeButton;
     setResult(d->execReturnCode(d->detectedEscapeButton));
 }
critical() [1/4]
QMessageBox::StandardButton QMessageBox::critical (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Opens a critical message box with the given title and text in front of the specified parent widget.
Since
4.2
The standard buttons are added to the message box. defaultButton specifies the button used when Enter is pressed. defaultButton must refer to a button that was given in buttons. If defaultButton is QMessageBox::NoButton, QMessageBox chooses a suitable default automatically.
Returns the identity of the standard button that was clicked. If Esc was pressed instead, the Default and Escape Keys {escape button} is returned.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
question(), warning(), information()
Definition at line 1745 of file qmessagebox.cpp.
 {
     return showNewMessageBox(parent, Critical, title, text, buttons, defaultButton);
 }
critical() [2/4]
int QMessageBox::critical (QWidget * parent, const QString & title, const QString & text, int button0, int button1, int button2 = 0) static
Opens a critical message box with the given title and text.
The dialog may have up to three buttons. Each of the button parameters, button0, button1 and button2 may be set to one of the following values:
QMessageBox::NoButton
QMessageBox::Ok
QMessageBox::Cancel
QMessageBox::Yes
QMessageBox::No
QMessageBox::Abort
QMessageBox::Retry
QMessageBox::Ignore
QMessageBox::YesAll
QMessageBox::NoAll
If you don't want all three buttons, set the last button, or last two buttons to QMessageBox::NoButton.
One button can be OR-ed with QMessageBox::Default, and one button can be OR-ed with QMessageBox::Escape.
Returns the identity (QMessageBox::Ok, or QMessageBox::No, etc.) of the button that was clicked.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
information(), question(), warning()
Definition at line 2423 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Critical, title, text,
                                                  button0, button1, button2);
 }
critical() [3/4]
int QMessageBox::critical (QWidget * parent, const QString & title, const QString & text, const QString & button0Text, const QString & button1Text = QString(), const QString & button2Text = QString(), int defaultButtonNumber = 0, int escapeButtonNumber = -1) static
Displays a critical error message box with the given title and text, as well as one, two, or three buttons.
button0Text is the text of the first button, and is optional. If button0Text is not supplied, "OK" (translated) will be used. button1Text is the text of the second button, and is optional, and button2Text is the text of the third button, and is optional. defaultButtonNumber (0, 1 or 2) is the index of the default button; pressing Return or Enter is the same as clicking the default button. It defaults to 0 (the first button). escapeButtonNumber is the index of the Escape button; pressing Escape is the same as clicking this button. It defaults to -1; supply 0, 1, or 2 to make pressing Escape equivalent to clicking the relevant button.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
information(), question(), warning()
Definition at line 2462 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Critical, title, text,
                                                    button0Text, button1Text, button2Text,
                                                    defaultButtonNumber, escapeButtonNumber);
 }
critical() [4/4]
int QMessageBox::critical (QWidget * parent, const QString & title, const QString & text, StandardButton button0, StandardButton button1) inline static
Definition at line 272 of file qmessagebox.h.
     { return critical(parent, title, text, StandardButtons(button0), button1); }
defaultButton()
QPushButton * QMessageBox::defaultButton () const
Returns the button that should be the message box's default button.
Since
4.2
Returns 0 if no default button was set.
See also
addButton(), QPushButton::setDefault()
Definition at line 1114 of file qmessagebox.cpp.
Referenced by setWindowModality(), and showNewMessageBox().
 {
     Q_D(const QMessageBox);
     return d->defaultButton;
 }
detailedText()
QString QMessageBox::detailedText () const
Referenced by setButtonText().
escapeButton()
QAbstractButton * QMessageBox::escapeButton () const
Returns the button that is activated when escape is pressed.
Since
4.2
By default, QMessageBox attempts to automatically detect an escape button as follows:
If there is only one button, it is made the escape button.
If there is a Cancel button, it is made the escape button.
On Mac OS X only, if there is exactly one button with the role QMessageBox::RejectRole, it is made the escape button.
When an escape button could not be automatically detected, pressing Esc has no effect.
See also
addButton()
Definition at line 993 of file qmessagebox.cpp.
Referenced by QMessageBoxPrivate::detectEscapeButton().
 {
     Q_D(const QMessageBox);
     return d->escapeButton;
 }
event()
bool QMessageBox::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 1315 of file qmessagebox.cpp.
 {
     bool result =QDialog::event(e);
     switch (e->type()) {
         case QEvent::LayoutRequest:
             d_func()->updateSize();
             break;
         case QEvent::LanguageChange:
             d_func()->retranslateStrings();
             break;
 #ifdef Q_WS_WINCE
         case QEvent::OkRequest:
         case QEvent::HelpRequest: {
           QString bName =
               (e->type() == QEvent::OkRequest)
               ? QApplication::translate("QMessageBox", "OK")
               : QApplication::translate("QMessageBox", "Help");
           QList<QPushButton*> list = findChildren<QPushButton*>();
           for (int i=0; i<list.size(); ++i) {
               QPushButton *pb = list.at(i);
               if (pb->text() == bName) {
                   if (pb->isEnabled())
                       pb->click();
                   return pb->isEnabled();
               }
           }
         }
 #endif
         default:
             break;
     }
     return result;
 }
exec
int QMessageBox::exec () slot
Shows the message box as a modal dialog, blocking until the user closes it.
When using a QMessageBox with standard buttons, this functions returns a StandardButton value indicating the standard button that was clicked. When using QMessageBox with custom buttons, this function returns an opaque value; use clickedButton() to determine which button was clicked.
Note
The result() function returns also StandardButton value instead of QDialog::DialogCode
Users cannot interact with any other window in the same application until they close the dialog, either by clicking a button or by using a mechanism provided by the window system.
See also
show(), result()
Referenced by about(), aboutQt(), showNewMessageBox(), and QMessageBoxPrivate::showOldMessageBox().
icon()
Icon QMessageBox::icon () const
Referenced by about(), setIcon(), setText(), and setWindowModality().
iconPixmap()
QPixmap QMessageBox::iconPixmap () const
Referenced by setIcon().
information() [1/4]
QMessageBox::StandardButton QMessageBox::information (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Opens an information message box with the given title and text in front of the specified parent widget.
Since
4.2
The standard buttons are added to the message box. defaultButton specifies the button used when Enter is pressed. defaultButton must refer to a button that was given in buttons. If defaultButton is QMessageBox::NoButton, QMessageBox chooses a suitable default automatically.
Returns the identity of the standard button that was clicked. If Esc was pressed instead, the Default and Escape Keys {escape button} is returned.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
question(), warning(), critical()
Definition at line 1638 of file qmessagebox.cpp.
Referenced by critical(), QFileSystemModel::setData(), and QCoreFuriCuri::timerEvent().
 {
     return showNewMessageBox(parent, Information, title, text, buttons,
                              defaultButton);
 }
information() [2/4]
int QMessageBox::information (QWidget * parent, const QString & title, const QString & text, int button0, int button1 = 0, int button2 = 0) static
Opens an information message box with the given title and the text.
The dialog may have up to three buttons. Each of the buttons, button0, button1 and button2 may be set to one of the following values:
QMessageBox::NoButton
QMessageBox::Ok
QMessageBox::Cancel
QMessageBox::Yes
QMessageBox::No
QMessageBox::Abort
QMessageBox::Retry
QMessageBox::Ignore
QMessageBox::YesAll
QMessageBox::NoAll
If you don't want all three buttons, set the last button, or last two buttons to QMessageBox::NoButton.
One button can be OR-ed with QMessageBox::Default, and one button can be OR-ed with QMessageBox::Escape.
Returns the identity (QMessageBox::Ok, or QMessageBox::No, etc.) of the button that was clicked.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
question(), warning(), critical()
Definition at line 2147 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Information, title, text,
                                                    button0, button1, button2);
 }
information() [3/4]
int QMessageBox::information (QWidget * parent, const QString & title, const QString & text, const QString & button0Text, const QString & button1Text = QString(), const QString & button2Text = QString(), int defaultButtonNumber = 0, int escapeButtonNumber = -1) static
Displays an information message box with the given title and text, as well as one, two or three buttons.
button0Text is the text of the first button, and is optional. If button0Text is not supplied, "OK" (translated) will be used. button1Text is the text of the second button, and is optional. button2Text is the text of the third button, and is optional. defaultButtonNumber (0, 1 or 2) is the index of the default button; pressing Return or Enter is the same as clicking the default button. It defaults to 0 (the first button). escapeButtonNumber is the index of the escape button; pressing Esc is the same as clicking this button. It defaults to -1; supply 0, 1 or 2 to make pressing Esc equivalent to clicking the relevant button.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
question(), warning(), critical()
Definition at line 2187 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Information, title, text,
                                                    button0Text, button1Text, button2Text,
                                                    defaultButtonNumber, escapeButtonNumber);
 }
information() [4/4]
int QMessageBox::information (QWidget * parent, const QString & title, const QString & text, StandardButton button0, StandardButton button1 = NoButton) inline static
Definition at line 227 of file qmessagebox.h.
     { return information(parent, title, text, StandardButtons(button0), button1); }
informativeText()
QString QMessageBox::informativeText () const
Referenced by setDetailedText().
keyPressEvent()
void QMessageBox::keyPressEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 1408 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     if (e->key() == Qt::Key_Escape
 #ifdef Q_WS_MAC
         || (e->modifiers() == Qt::ControlModifier && e->key() == Qt::Key_Period)
 #endif
         ) {
             if (d->detectedEscapeButton) {
 #ifdef Q_WS_MAC
                 d->detectedEscapeButton->animateClick();
 #else
                 d->detectedEscapeButton->click();
 #endif
             }
             return;
         }
 #if defined (Q_OS_WIN) && !defined(QT_NO_CLIPBOARD) && !defined(QT_NO_SHORTCUT)
         if (e == QKeySequence::Copy) {
             QString separator = QString::fromLatin1("---------------------------\n");
             QString textToCopy = separator;
             separator.prepend(QLatin1Char('\n'));
             textToCopy += windowTitle() + separator; // title
             textToCopy += d->label->text() + separator; // text
             if (d->informativeLabel)
                 textToCopy += d->informativeLabel->text() + separator;
             QString buttonTexts;
             QList<QAbstractButton *> buttons = d->buttonBox->buttons();
             for (int i = 0; i < buttons.count(); i++) {
                 buttonTexts += buttons[i]->text() + QLatin1String("   ");
             }
             textToCopy += buttonTexts + separator;
             QApplication::clipboard()->setText(textToCopy);
             return;
         }
 #endif //QT_NO_SHORTCUT QT_NO_CLIPBOARD Q_OS_WIN
 #ifndef QT_NO_SHORTCUT
     if (!(e->modifiers() & Qt::AltModifier)) {
         int key = e->key() & ~((int)Qt::MODIFIER_MASK|(int)Qt::UNICODE_ACCEL);
         if (key) {
             const QList<QAbstractButton *> buttons = d->buttonBox->buttons();
             for (int i = 0; i < buttons.count(); ++i) {
                 QAbstractButton *pb = buttons.at(i);
                 int acc = pb->shortcut() & ~((int)Qt::MODIFIER_MASK|(int)Qt::UNICODE_ACCEL);
                 if (acc == key) {
                     pb->animateClick();
                     return;
                 }
             }
         }
     }
 #endif
     QDialog::keyPressEvent(e);
 }
open()
void QMessageBox::open (QObject * receiver, const char * member)
Opens the dialog and connects its finished() or buttonClicked() signal to the slot specified by receiver and member.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If the slot in member has a pointer for its first parameter the connection is to buttonClicked(), otherwise the connection is to finished().
The signal will be disconnected from the slot when the dialog is closed.
Definition at line 1495 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     const char *signal = member && strchr(member, '*') ? SIGNAL(buttonClicked(QAbstractButton*))
                                                        : SIGNAL(finished(int));
     connect(this, signal, receiver, member);
     d->signalToDisconnectOnClose = signal;
     d->receiverToDisconnectOnClose = receiver;
     d->memberToDisconnectOnClose = member;
     QDialog::open();
 }
question() [1/4]
QMessageBox::StandardButton QMessageBox::question (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Opens a question message box with the given title and text in front of the specified parent widget.
Since
4.2
The standard buttons are added to the message box. defaultButton specifies the button used when Enter is pressed. defaultButton must refer to a button that was given in buttons. If defaultButton is QMessageBox::NoButton, QMessageBox chooses a suitable default automatically.
Returns the identity of the standard button that was clicked. If Esc was pressed instead, the Default and Escape Keys {escape button} is returned.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
information(), warning(), critical()
Definition at line 1675 of file qmessagebox.cpp.
Referenced by QUnixPrintWidgetPrivate::checkFields().
 {
     return showNewMessageBox(parent, Question, title, text, buttons, defaultButton);
 }
question() [2/4]
int QMessageBox::question (QWidget * parent, const QString & title, const QString & text, int button0, int button1 = 0, int button2 = 0) static
Opens a question message box with the given title and text.
The dialog may have up to three buttons. Each of the buttons, button0, button1 and button2 may be set to one of the following values:
QMessageBox::NoButton
QMessageBox::Ok
QMessageBox::Cancel
QMessageBox::Yes
QMessageBox::No
QMessageBox::Abort
QMessageBox::Retry
QMessageBox::Ignore
QMessageBox::YesAll
QMessageBox::NoAll
If you don't want all three buttons, set the last button, or last two buttons to QMessageBox::NoButton.
One button can be OR-ed with QMessageBox::Default, and one button can be OR-ed with QMessageBox::Escape.
Returns the identity (QMessageBox::Yes, or QMessageBox::No, etc.) of the button that was clicked.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
information(), warning(), critical()
Definition at line 2239 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Question, title, text,
                                                    button0, button1, button2);
 }
question() [3/4]
int QMessageBox::question (QWidget * parent, const QString & title, const QString & text, const QString & button0Text, const QString & button1Text = QString(), const QString & button2Text = QString(), int defaultButtonNumber = 0, int escapeButtonNumber = -1) static
Displays a question message box with the given title and text, as well as one, two or three buttons.
button0Text is the text of the first button, and is optional. If button0Text is not supplied, "OK" (translated) will be used. button1Text is the text of the second button, and is optional. button2Text is the text of the third button, and is optional. defaultButtonNumber (0, 1 or 2) is the index of the default button; pressing Return or Enter is the same as clicking the default button. It defaults to 0 (the first button). escapeButtonNumber is the index of the Escape button; pressing Escape is the same as clicking this button. It defaults to -1; supply 0, 1 or 2 to make pressing Escape equivalent to clicking the relevant button.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
information(), warning(), critical()
Definition at line 2278 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Question, title, text,
                                                    button0Text, button1Text, button2Text,
                                                    defaultButtonNumber, escapeButtonNumber);
 }
question() [4/4]
int QMessageBox::question (QWidget * parent, const QString & title, const QString & text, StandardButton button0, StandardButton button1) inline static
Warning
This function is not part of the public interface.
Needed for Qt 4 source compatibility
Definition at line 242 of file qmessagebox.h.
     { return question(parent, title, text, StandardButtons(button0), button1); }
removeButton()
void QMessageBox::removeButton (QAbstractButton * button)
Removes button from the button box without deleting it.
Since
4.2
See also
addButton(), setStandardButtons()
Definition at line 890 of file qmessagebox.cpp.
Referenced by addButton(), and setDetailedText().
 {
     Q_D(QMessageBox);
     d->customButtonList.removeAll(button);
     if (d->escapeButton == button)
         d->escapeButton = 0;
     if (d->defaultButton == button)
         d->defaultButton = 0;
     d->buttonBox->removeButton(button);
     d->updateSize();
 }
resizeEvent()
void QMessageBox::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 1352 of file qmessagebox.cpp.
 {
     QDialog::resizeEvent(event);
 }
setButtonText()
void QMessageBox::setButtonText (int button, const QString & text)
Sets the text of the message box button button to text.
Setting the text of a button that is not in the message box is silently ignored.
Use addButton() instead.
Definition at line 2509 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     if (QAbstractButton *abstractButton = d->abstractButtonForId(button)) {
         abstractButton->setText(text);
     } else if (d->buttonBox->buttons().isEmpty() && (button == Ok || button == Old_Ok)) {
         // for compatibility with Qt 4.0/4.1
         addButton(QMessageBox::Ok)->setText(text);
     }
 }
setDefaultButton() [1/2]
void QMessageBox::setDefaultButton (QPushButton * button)
Sets the message box's default button to button.
Since
4.2
See also
addButton(), QPushButton::setDefault()
Definition at line 1131 of file qmessagebox.cpp.
Referenced by aboutQt(), setDefaultButton(), setWindowModality(), showNewMessageBox(), and QMessageBoxPrivate::showOldMessageBox().
 {
     Q_D(QMessageBox);
     if (!d->buttonBox->buttons().contains(button))
         return;
     d->defaultButton = button;
     button->setDefault(true);
     button->setFocus();
 }
setDefaultButton() [2/2]
void QMessageBox::setDefaultButton (QMessageBox::StandardButton button)
Sets the message box's default button to button.
Since
4.3
See also
addButton(), QPushButton::setDefault()
Definition at line 1152 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     setDefaultButton(d->buttonBox->button(QDialogButtonBox::StandardButton(button)));
 }
setDetailedText()
void QMessageBox::setDetailedText (const QString & text)
Definition at line 2541 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     if (text.isEmpty()) {
         delete d->detailsText;
         d->detailsText = 0;
         removeButton(d->detailsButton);
         delete d->detailsButton;
         d->detailsButton = 0;
         return;
     }
     if (!d->detailsText) {
         d->detailsText = new QMessageBoxDetailsText(this);
         QGridLayout* grid = qobject_cast<QGridLayout*>(layout());
         if (grid)
             grid->addWidget(d->detailsText, grid->rowCount(), 0, 1, grid->columnCount());
         d->detailsText->hide();
     }
     if (!d->detailsButton)
         d->detailsButton = new DetailButton(this);
     d->detailsText->setText(text);
 }
setEscapeButton() [1/2]
void QMessageBox::setEscapeButton (QAbstractButton * button)
Sets the button that gets activated when the Escape key is pressed to button.
Since
4.2
See also
addButton(), clickedButton()
Definition at line 1010 of file qmessagebox.cpp.
Referenced by setEscapeButton(), and QMessageBoxPrivate::showOldMessageBox().
 {
     Q_D(QMessageBox);
     if (d->buttonBox->buttons().contains(button))
         d->escapeButton = button;
 }
setEscapeButton() [2/2]
void QMessageBox::setEscapeButton (QMessageBox::StandardButton button)
Sets the buttons that gets activated when the Escape key is pressed to button.
Since
4.3
See also
addButton(), clickedButton()
Definition at line 1028 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     setEscapeButton(d->buttonBox->button(QDialogButtonBox::StandardButton(button)));
 }
setIcon()
void QMessageBox::setIcon (Icon icon)
Definition at line 1245 of file qmessagebox.cpp.
Referenced by changeEvent(), QMessageBox(), and setWindowModality().
 {
     Q_D(QMessageBox);
     setIconPixmap(QMessageBoxPrivate::standardIcon((QMessageBox::Icon)icon,
                                                    this));
     d->icon = icon;
 }
setIconPixmap()
void QMessageBox::setIconPixmap (const QPixmap & pixmap)
Definition at line 1276 of file qmessagebox.cpp.
Referenced by about(), aboutQt(), and setIcon().
 {
     Q_D(QMessageBox);
     d->iconLabel->setPixmap(pixmap);
     d->updateSize();
     d->icon = NoIcon;
 }
setInformativeText()
void QMessageBox::setInformativeText (const QString & text)
Definition at line 2592 of file qmessagebox.cpp.
Referenced by aboutQt().
 {
     Q_D(QMessageBox);
     if (text.isEmpty()) {
         layout()->removeWidget(d->informativeLabel);
         delete d->informativeLabel;
         d->informativeLabel = 0;
 #ifndef Q_WS_MAC
         d->label->setContentsMargins(2, 0, 0, 0);
 #endif
         d->updateSize();
         return;
     }
     if (!d->informativeLabel) {
         QLabel *label = new QLabel(this);
         label->setObjectName(QLatin1String("qt_msgbox_informativelabel"));
         label->setTextInteractionFlags(Qt::TextInteractionFlags(style()->styleHint(QStyle::SH_MessageBox_TextInteractionFlags, 0, this)));
         label->setAlignment(Qt::AlignTop | Qt::AlignLeft);
         label->setOpenExternalLinks(true);
         label->setWordWrap(true);
 #ifndef Q_WS_MAC
         d->label->setContentsMargins(2, 0, 0, 0);
         label->setContentsMargins(2, 0, 0, 6);
         label->setIndent(9);
 #else
         label->setContentsMargins(16, 0, 0, 0);
         // apply a smaller font the information label on the mac
         label->setFont(qt_app_fonts_hash()->value("QTipLabel"));
 #endif
         label->setWordWrap(true);
         QGridLayout *grid = static_cast<QGridLayout *>(layout());
 #if defined(Q_OS_SYMBIAN) || defined(Q_WS_MAEMO_5)
         label->hide();
         QTextBrowser *textBrowser = new QTextBrowser(this);
         textBrowser->setOpenExternalLinks(true);
 #if defined(Q_OS_SYMBIAN)
         const int preferredTextColumn = (QApplication::layoutDirection() == Qt::LeftToRight) ? 0 : 1;
 #else
         const int preferredTextColumn = 1;
 #endif
         grid->addWidget(textBrowser, 1, preferredTextColumn, 1, 1);
         d->textBrowser = textBrowser;
 #else
         grid->addWidget(label, 1, 1, 1, 1);
 #endif
         d->informativeLabel = label;
     }
     d->informativeLabel->setText(text);
 #if defined(Q_OS_SYMBIAN) || defined(Q_WS_MAEMO_5)
     //We need to put the informative label inside textBrowser to enable scrolling of long texts.
     d->textBrowser->setText(d->informativeLabel->text());
 #endif
     d->updateSize();
 }
setStandardButtons()
void QMessageBox::setStandardButtons (StandardButtons buttons)
Definition at line 916 of file qmessagebox.cpp.
Referenced by QMessageBox().
 {
     Q_D(QMessageBox);
     d->buttonBox->setStandardButtons(QDialogButtonBox::StandardButtons(int(buttons)));
     QList<QAbstractButton *> buttonList = d->buttonBox->buttons();
     if (!buttonList.contains(d->escapeButton))
         d->escapeButton = 0;
     if (!buttonList.contains(d->defaultButton))
         d->defaultButton = 0;
     d->autoAddOkButton = false;
     d->updateSize();
 }
setText()
void QMessageBox::setText (const QString & text)
Definition at line 1180 of file qmessagebox.cpp.
Referenced by aboutQt().
 {
     Q_D(QMessageBox);
     d->label->setText(text);
     d->label->setWordWrap(d->label->textFormat() == Qt::RichText
         || (d->label->textFormat() == Qt::AutoText && Qt::mightBeRichText(text)));
     d->updateSize();
 }
setTextFormat()
void QMessageBox::setTextFormat (Qt::TextFormat format)
Definition at line 1303 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     d->label->setTextFormat(format);
     d->label->setWordWrap(format == Qt::RichText
                     || (format == Qt::AutoText && Qt::mightBeRichText(d->label->text())));
     d->updateSize();
 }
setVisible()
void QMessageBox::setVisible (bool visible) virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 1472 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     if (visible)
         d->hideSpecial();
     QDialog::setVisible(visible);
 }
setWindowModality()
void QMessageBox::setWindowModality (Qt::WindowModality windowModality)
This function shadows QWidget::setWindowModality().
Since
4.2
Sets the modality of the message box to windowModality.
On Mac OS X, if the modality is set to Qt::WindowModal and the message box has a parent, then the message box will be a Qt::Sheet, otherwise the message box will be a standard dialog.
Definition at line 2687 of file qmessagebox.cpp.
 {
     QDialog::setWindowModality(windowModality);
     if (parentWidget() && windowModality == Qt::WindowModal)
         setParent(parentWidget(), Qt::Sheet);
     else
         setParent(parentWidget(), Qt::Dialog);
     setDefaultButton(d_func()->defaultButton);
 }
setWindowTitle()
void QMessageBox::setWindowTitle (const QString & title)
This function shadows QWidget::setWindowTitle().
Since
4.2
Sets the title of the message box to title. On Mac OS X, the window title is ignored (as required by the Mac OS X Guidelines).
Definition at line 2662 of file qmessagebox.cpp.
Referenced by aboutQt().
 {
     // Message boxes on the mac do not have a title
 #ifndef Q_WS_MAC
     QDialog::setWindowTitle(title);
 #else
     Q_UNUSED(title);
 #endif
 }
showEvent()
void QMessageBox::showEvent (QShowEvent * event) protected virtual
Reimplemented Function
Reimplemented from QDialog.
Definition at line 1543 of file qmessagebox.cpp.
 {
     Q_D(QMessageBox);
     if (d->autoAddOkButton) {
         addButton(Ok);
 #if defined(Q_WS_WINCE)
         d->hideSpecial();
 #endif
     }
     if (d->detailsButton)
         addButton(d->detailsButton, QMessageBox::ActionRole);
     d->detectEscapeButton();
     d->updateSize();
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::Alert);
 #endif
 #ifdef Q_WS_WIN
     HMENU systemMenu = GetSystemMenu((HWND)winId(), FALSE);
     if (!d->detectedEscapeButton) {
         EnableMenuItem(systemMenu, SC_CLOSE, MF_BYCOMMAND|MF_GRAYED);
     }
     else {
         EnableMenuItem(systemMenu, SC_CLOSE, MF_BYCOMMAND|MF_ENABLED);
     }
 #endif
     QDialog::showEvent(e);
 }
sizeHint()
QSize QMessageBox::sizeHint () const virtual
Warning
This function is not part of the public interface.
Reimplemented from QDialog.
Definition at line 1905 of file qmessagebox.cpp.
 {
     // ### Qt 5: remove
     return QDialog::sizeHint();
 }
standardButton()
QMessageBox::StandardButton QMessageBox::standardButton (QAbstractButton * button) const
Returns the standard button enum value corresponding to the given button, or NoButton if the given button isn't a standard button.
Since
4.2
See also
button(), standardButtons()
Definition at line 947 of file qmessagebox.cpp.
Referenced by showNewMessageBox().
 {
     Q_D(const QMessageBox);
     return (QMessageBox::StandardButton)d->buttonBox->standardButton(button);
 }
standardButtons()
StandardButtons QMessageBox::standardButtons () const
Referenced by setStandardButtons().
standardIcon()
QPixmap QMessageBox::standardIcon (Icon icon) static
Returns the pixmap used for a standard icon.
This allows the pixmaps to be used in more complex message boxes. icon specifies the required icon, e.g. QMessageBox::Question, QMessageBox::Information, QMessageBox::Warning or QMessageBox::Critical.
Call QStyle::standardIcon() with QStyle::SP_MessageBoxInformation etc. instead.
Definition at line 2844 of file qmessagebox.cpp.
Referenced by QErrorMessage::QErrorMessage(), and setWindowModality().
 {
     return QMessageBoxPrivate::standardIcon(icon, 0);
 }
text()
QString QMessageBox::text () const
Referenced by about(), setDefaultButton(), and setWindowModality().
textFormat()
Qt::TextFormat QMessageBox::textFormat () const
Referenced by setIconPixmap().
warning() [1/4]
QMessageBox::StandardButton QMessageBox::warning (QWidget * parent, const QString & title, const QString & text, StandardButtons buttons = Ok, StandardButton defaultButton = NoButton) static
Opens a warning message box with the given title and text in front of the specified parent widget.
Since
4.2
The standard buttons are added to the message box. defaultButton specifies the button used when Enter is pressed. defaultButton must refer to a button that was given in buttons. If defaultButton is QMessageBox::NoButton, QMessageBox chooses a suitable default automatically.
Returns the identity of the standard button that was clicked. If Esc was pressed instead, the Default and Escape Keys {escape button} is returned.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
question(), information(), critical()
Definition at line 1710 of file qmessagebox.cpp.
Referenced by QFileDialogPrivate::_q_deleteCurrent(), QFileDialogPrivate::_q_goToDirectory(), QPrintDialogPrivate::_q_okClicked(), QFileDialog::accept(), QUnixPrintWidgetPrivate::checkFields(), and QPrintDialogPrivate::openWindowsPrintDialogModally().
 {
     return showNewMessageBox(parent, Warning, title, text, buttons, defaultButton);
 }
warning() [2/4]
int QMessageBox::warning (QWidget * parent, const QString & title, const QString & text, int button0, int button1, int button2 = 0) static
Opens a warning message box with the given title and text.
The dialog may have up to three buttons. Each of the button parameters, button0, button1 and button2 may be set to one of the following values:
QMessageBox::NoButton
QMessageBox::Ok
QMessageBox::Cancel
QMessageBox::Yes
QMessageBox::No
QMessageBox::Abort
QMessageBox::Retry
QMessageBox::Ignore
QMessageBox::YesAll
QMessageBox::NoAll
If you don't want all three buttons, set the last button, or last two buttons to QMessageBox::NoButton.
One button can be OR-ed with QMessageBox::Default, and one button can be OR-ed with QMessageBox::Escape.
Returns the identity (QMessageBox::Ok or QMessageBox::No or ...) of the button that was clicked.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
information(), question(), critical()
Definition at line 2331 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Warning, title, text,
                                                    button0, button1, button2);
 }
warning() [3/4]
int QMessageBox::warning (QWidget * parent, const QString & title, const QString & text, const QString & button0Text, const QString & button1Text = QString(), const QString & button2Text = QString(), int defaultButtonNumber = 0, int escapeButtonNumber = -1) static
Displays a warning message box with the given title and text, as well as one, two, or three buttons.
button0Text is the text of the first button, and is optional. If button0Text is not supplied, "OK" (translated) will be used. button1Text is the text of the second button, and is optional, and button2Text is the text of the third button, and is optional. defaultButtonNumber (0, 1 or 2) is the index of the default button; pressing Return or Enter is the same as clicking the default button. It defaults to 0 (the first button). escapeButtonNumber is the index of the Escape button; pressing Escape is the same as clicking this button. It defaults to -1; supply 0, 1, or 2 to make pressing Escape equivalent to clicking the relevant button.
The message box is an application modal dialog box.
Warning
Do not delete parent during the execution of the dialog. If you want to do this, you should create the dialog yourself using one of the QMessageBox constructors.
See also
information(), question(), critical()
Definition at line 2370 of file qmessagebox.cpp.
 {
     return QMessageBoxPrivate::showOldMessageBox(parent, Warning, title, text,
                                                    button0Text, button1Text, button2Text,
                                                    defaultButtonNumber, escapeButtonNumber);
 }
warning() [4/4]
int QMessageBox::warning (QWidget * parent, const QString & title, const QString & text, StandardButton button0, StandardButton button1) inline static
Definition at line 257 of file qmessagebox.h.
     { return warning(parent, title, text, StandardButtons(button0), button1); }
Properties
detailedText
QString QMessageBox::detailedText private
the text to be displayed in the details area.
Since
4.2
The text will be interpreted as a plain text.
By default, this property contains an empty string.
See also
QMessageBox::text, QMessageBox::informativeText
Definition at line 71 of file qmessagebox.h.
icon
QMessageBox::Icon QMessageBox::icon private
the message box's icon
The icon of the message box can be specified with one of the values:
QMessageBox::NoIcon
QMessageBox::Question
QMessageBox::Information
QMessageBox::Warning
QMessageBox::Critical
The default is QMessageBox::NoIcon.
The pixmap used to display the actual icon depends on the current GUI style. You can also set a custom pixmap for the icon by setting the icon pixmap property.
See also
iconPixmap
Definition at line 66 of file qmessagebox.h.
iconPixmap
QPixmap QMessageBox::iconPixmap private
the current icon
The icon currently used by the message box. Note that it's often hard to draw one pixmap that looks appropriate in all GUI styles; you may want to supply a different pixmap for each platform.
By default, this property is undefined.
See also
icon
Definition at line 67 of file qmessagebox.h.
informativeText
QString QMessageBox::informativeText private
the informative text that provides a fuller description for the message
Since
4.2
Infromative text can be used to expand upon the text() to give more information to the user. On the Mac, this text appears in small system font below the text(). On other platforms, it is simply appended to the existing text.
By default, this property contains an empty string.
See also
QMessageBox::text, QMessageBox::detailedText
Definition at line 73 of file qmessagebox.h.
standardButtons
QMessageBox::StandardButtons QMessageBox::standardButtons private
collection of standard buttons in the message box
Since
4.2
This property controls which standard buttons are used by the message box.
By default, this property contains no standard buttons.
See also
addButton()
Definition at line 69 of file qmessagebox.h.
text
QString QMessageBox::text private
the message box text to be displayed.
The text will be interpreted either as a plain text or as rich text, depending on the text format setting (QMessageBox::textFormat). The default setting is Qt::AutoText, i.e., the message box will try to auto-detect the format of the text.
The default value of this property is an empty string.
See also
textFormat, QMessageBox::informativeText, QMessageBox::detailedText
Definition at line 64 of file qmessagebox.h.
Referenced by about().
textFormat
Qt::TextFormat QMessageBox::textFormat private
the format of the text displayed by the message box
The current text format used by the message box. See the Qt::TextFormat enum for an explanation of the possible options.
The default format is Qt::AutoText.
See also
setText()
Definition at line 68 of file qmessagebox.h.
The documentation for this class was generated from the following files:
/src/gui/dialogs/qmessagebox.h
/src/gui/dialogs/qmessagebox.cpp