Qt 4.8: QDeclarativeGuardedContextData Class Reference
QDeclarativeGuardedContextData Class Reference
#include <qdeclarativecontext_p.h>
Public Functions
QDeclarativeContextData * contextData ()
operator QDeclarativeContextData * () const
QDeclarativeContextData * operator-> () const
QDeclarativeGuardedContextData & operator= (QDeclarativeContextData *d)
QDeclarativeGuardedContextData ()
QDeclarativeGuardedContextData (QDeclarativeContextData *)
void setContextData (QDeclarativeContextData *)
~QDeclarativeGuardedContextData ()
Private Functions
void clear ()
QDeclarativeGuardedContextData & operator= (const QDeclarativeGuardedContextData &)
QDeclarativeGuardedContextData (const QDeclarativeGuardedContextData &)
Properties
QDeclarativeContextData * m_contextData
QDeclarativeGuardedContextData * m_next
QDeclarativeGuardedContextData ** m_prev
Friends
class QDeclarativeContextData
Detailed Description
Definition at line 211 of file qdeclarativecontext_p.h.
Constructors and Destructors
QDeclarativeGuardedContextData() [1/3]
QDeclarativeGuardedContextData::QDeclarativeGuardedContextData () inline
Definition at line 238 of file qdeclarativecontext_p.h.
 : m_contextData(0), m_next(0), m_prev(0)
 {
 }
QDeclarativeGuardedContextData() [2/3]
QDeclarativeGuardedContextData::QDeclarativeGuardedContextData (QDeclarativeContextData * data) inline
Definition at line 243 of file qdeclarativecontext_p.h.
 : m_contextData(0), m_next(0), m_prev(0)
 {
     setContextData(data);
 }
~QDeclarativeGuardedContextData()
QDeclarativeGuardedContextData::~QDeclarativeGuardedContextData () inline
Definition at line 249 of file qdeclarativecontext_p.h.
 {
     clear();
 }
QDeclarativeGuardedContextData() [3/3]
QDeclarativeGuardedContextData::QDeclarativeGuardedContextData (const QDeclarativeGuardedContextData &) private
Functions
clear()
void QDeclarativeGuardedContextData::clear () inline private
Definition at line 272 of file qdeclarativecontext_p.h.
Referenced by setContextData(), and ~QDeclarativeGuardedContextData().
 {
     if (m_prev) {
         *m_prev = m_next;
         if (m_next) m_next->m_prev = m_prev;
         m_contextData = 0;
         m_next = 0;
         m_prev = 0;
     }
 }
contextData()
QDeclarativeContextData * QDeclarativeGuardedContextData::contextData () inline
Definition at line 267 of file qdeclarativecontext_p.h.
Referenced by ContextData::getContext(), and setContextData().
 {
     return m_contextData;
 }
operator QDeclarativeContextData *()
QDeclarativeGuardedContextData::operator QDeclarativeContextData * () const inline
Definition at line 222 of file qdeclarativecontext_p.h.
 { return m_contextData; }
operator->()
QDeclarativeContextData* QDeclarativeGuardedContextData::operator-> () const inline
Definition at line 223 of file qdeclarativecontext_p.h.
 { return m_contextData; }
operator=() [1/2]
QDeclarativeGuardedContextData & QDeclarativeGuardedContextData::operator= (QDeclarativeContextData * d) inline
Definition at line 284 of file qdeclarativecontext_p.h.
 {
     setContextData(d);
     return *this;
 }
operator=() [2/2]
QDeclarativeGuardedContextData& QDeclarativeGuardedContextData::operator= (const QDeclarativeGuardedContextData &) private
setContextData()
void QDeclarativeGuardedContextData::setContextData (QDeclarativeContextData * contextData) inline
Definition at line 254 of file qdeclarativecontext_p.h.
Referenced by operator=(), and QDeclarativeGuardedContextData().
 {
     clear();
     if (contextData) {
         m_contextData = contextData;
         m_next = contextData->contextGuards;
         if (m_next) m_next->m_prev = &m_next;
         m_prev = &contextData->contextGuards;
         contextData->contextGuards = this;
     }
 }
Friends and Related Functions
QDeclarativeContextData
friend class QDeclarativeContextData friend
Definition at line 229 of file qdeclarativecontext_p.h.
Properties
m_contextData
QDeclarativeContextData* QDeclarativeGuardedContextData::m_contextData private
Definition at line 233 of file qdeclarativecontext_p.h.
Referenced by clear(), contextData(), and setContextData().
m_next
QDeclarativeGuardedContextData* QDeclarativeGuardedContextData::m_next private
Definition at line 234 of file qdeclarativecontext_p.h.
Referenced by clear(), and setContextData().
m_prev
QDeclarativeGuardedContextData** QDeclarativeGuardedContextData::m_prev private
Definition at line 235 of file qdeclarativecontext_p.h.
Referenced by clear(), and setContextData().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativecontext_p.h