Qt 4.8: QPFGlyphTree Class Reference
QPFGlyphTree Class Reference
Public Functions
void dump (int indent=0)
QPFGlyph * get (glyph_t g)
bool inFont (glyph_t g) const
QPFGlyphTree (uchar *&data)
int totalChars () const
int weight () const
~QPFGlyphTree ()
Public Variables
QPFGlyph * glyph
QPFGlyphTree * less
glyph_t max
glyph_t min
QPFGlyphTree * more
Private Functions
QPFGlyphTree ()
void read (uchar *&data)
void readData (uchar *&data)
void readMetrics (uchar *&data)
void readNode (uchar *&data)
Detailed Description
Definition at line 141 of file qfontengine_qws.cpp.
Constructors and Destructors
QPFGlyphTree() [1/2]
QPFGlyphTree::QPFGlyphTree (uchar *& data) inline
Definition at line 157 of file qfontengine_qws.cpp.
     {
         read(data);
     }
~QPFGlyphTree()
QPFGlyphTree::~QPFGlyphTree () inline
Definition at line 162 of file qfontengine_qws.cpp.
     {
         // NOTE: does not delete glyph[*].metrics or .data.
         //       the caller does this (only they know who owns
         //       the data).  See clear().
         delete less;
         delete more;
         delete [] glyph;
     }
QPFGlyphTree() [2/2]
QPFGlyphTree::QPFGlyphTree () inline private
Definition at line 222 of file qfontengine_qws.cpp.
     {
     }
Functions
dump()
void QPFGlyphTree::dump (int indent = 0) inline
Definition at line 210 of file qfontengine_qws.cpp.
Referenced by dump().
     {
         for (int i=0; i<indent; i++) printf(" ");
         printf("%d..%d",min,max);
         //if ( indent == 0 )
         printf(" (total %d)",totalChars());
         printf("\n");
         if ( less ) less->dump(indent+1);
         if ( more ) more->dump(indent+1);
     }
get()
QPFGlyph* QPFGlyphTree::get (glyph_t g) inline
Definition at line 186 of file qfontengine_qws.cpp.
Referenced by get().
     {
         if ( g < min ) {
             if ( !less )
                 return 0;
             return less->get(g);
         } else if ( g > max ) {
             if ( !more )
                 return 0;
             return more->get(g);
         }
         return &glyph[g - min];
     }
inFont()
bool QPFGlyphTree::inFont (glyph_t g) const inline
Definition at line 172 of file qfontengine_qws.cpp.
Referenced by inFont().
     {
         if ( g < min ) {
             if ( !less )
                 return false;
             return less->inFont(g);
         } else if ( g > max ) {
             if ( !more )
                 return false;
             return more->inFont(g);
         }
         return true;
     }
read()
void QPFGlyphTree::read (uchar *& data) inline private
Definition at line 226 of file qfontengine_qws.cpp.
     {
         // All node data first
         readNode(data);
         // Then all non-video data
         readMetrics(data);
         // Then all video data
         readData(data);
     }
readData()
void QPFGlyphTree::readData (uchar *& data) inline private
Definition at line 275 of file qfontengine_qws.cpp.
Referenced by readData().
     {
         int n = max-min+1;
         for (int i=0; i<n; i++) {
             QSize s( glyph[i].metrics->width, glyph[i].metrics->height );
             //######### s = qt_screen->mapToDevice( s );
             uint datasize = glyph[i].metrics->linestep * s.height();
             glyph[i].data = data; data += datasize;
         }
         if ( less )
             less->readData(data);
         if ( more )
             more->readData(data);
     }
readMetrics()
void QPFGlyphTree::readMetrics (uchar *& data) inline private
Definition at line 262 of file qfontengine_qws.cpp.
Referenced by readMetrics().
     {
         int n = max-min+1;
         for (int i=0; i<n; i++) {
             glyph[i].metrics = (QPFGlyphMetrics*)data;
             data += sizeof(QPFGlyphMetrics);
         }
         if ( less )
             less->readMetrics(data);
         if ( more )
             more->readMetrics(data);
     }
readNode()
void QPFGlyphTree::readNode (uchar *& data) inline private
Definition at line 236 of file qfontengine_qws.cpp.
Referenced by readNode().
     {
         uchar rw = *data++;
         uchar cl = *data++;
         min = (rw << 8) | cl;
         rw = *data++;
         cl = *data++;
         max = (rw << 8) | cl;
         int flags = *data++;
         if ( flags & 1 )
             less = new QPFGlyphTree;
         else
             less = 0;
         if ( flags & 2 )
             more = new QPFGlyphTree;
         else
             more = 0;
         int n = max-min+1;
         glyph = new QPFGlyph[n];
         if ( less )
             less->readNode(data);
         if ( more )
             more->readNode(data);
     }
totalChars()
int QPFGlyphTree::totalChars () const inline
Definition at line 199 of file qfontengine_qws.cpp.
Referenced by totalChars().
     {
         if ( !this ) return 0;
         return max-min+1 + less->totalChars() + more->totalChars();
     }
weight()
int QPFGlyphTree::weight () const inline
Definition at line 204 of file qfontengine_qws.cpp.
Referenced by weight().
     {
         if ( !this ) return 0;
         return 1 + less->weight() + more->weight();
     }
Properties
glyph
QPFGlyph* QPFGlyphTree::glyph
Definition at line 155 of file qfontengine_qws.cpp.
less
QPFGlyphTree* QPFGlyphTree::less
Definition at line 153 of file qfontengine_qws.cpp.
max
glyph_t QPFGlyphTree::max
Definition at line 152 of file qfontengine_qws.cpp.
min
glyph_t QPFGlyphTree::min
Definition at line 152 of file qfontengine_qws.cpp.
more
QPFGlyphTree* QPFGlyphTree::more
Definition at line 154 of file qfontengine_qws.cpp.
The documentation for this class was generated from the following file:
/src/gui/text/qfontengine_qws.cpp