Qt 4.8: QPatternist::AbstractDateTime Class Reference
QPatternist::AbstractDateTime Class Reference
Base class for classes implementing values related to time, date or both.
#include <qabstractdatetime_p.h>
Classes
class CaptureTable
Acts as a mapping table for AbstractDateTime::create() and describes where certain fields in a QRegExp pattern can be found for a particular W3C XML Schema date/time type.
Public Types
enum { DefaultYear = 2000, DefaultMonth = 1, DefaultDay = 1 }
typedef QExplicitlySharedDataPointer< AbstractDateTime > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
AbstractDateTime (const QDateTime &dateTime)
QString dateToString () const
virtual Item fromValue (const QDateTime &dt) const
QString timeToString () const
const QDateTime & toDateTime () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual QString stringValue () const =0
virtual ItemType::Ptr type () const =0
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static bool isRangeValid (const QDate &date, QString &message)
static QString serializeMSeconds (const MSecondProperty msecs)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
QString zoneOffsetToString () const
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Static Protected Functions
static void copyTimeSpec (const QDateTime &from, QDateTime &to)
Makes the QDateTime::timeSpec() and QDateTime::zoneOffset() of ot * consistent to from.
static QDateTime create (AtomicValue::Ptr &errorMessage, const QString &lexicalSource, const CaptureTable &captTable)
Protected Variables
const QDateTime m_dateTime
Private Types
enum ZoneOffsetParseResult { Error, Offset, LocalTime, UTC }
Static Private Functions
static ZOTotal parseZoneOffset (ZoneOffsetParseResult &result, const QStringList &capts, const CaptureTable &captTable)
Parses the zone offset. All types use zone offsets.
static void setUtcOffset (QDateTime &result, const ZoneOffsetParseResult zoResult, const int zoOffset)
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Base class for classes implementing values related to time, date or both.
See also
XML Schema Part 2: Datatypes Second Edition, 3.2.7 dateTime
XQuery 1.0 and XPath 2.0 Data Model (XDM), 3.3.2 Dates and Times
A summary of the international standard date and time notation, Markus Kuhn
ISO 8601, From Wikipedia, the free encyclopedia
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 80 of file qabstractdatetime_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<AbstractDateTime> QPatternist::AbstractDateTime::Ptr
Definition at line 83 of file qabstractdatetime_p.h.
Enumerations
anonymous enum
anonymous enum
Enumerator
DefaultYear
DefaultMonth
DefaultDay
Definition at line 87 of file qabstractdatetime_p.h.
         {
             DefaultYear     = 2000,
             DefaultMonth    = 1,
             DefaultDay      = 1
         };
ZoneOffsetParseResult
enum QPatternist::AbstractDateTime::ZoneOffsetParseResult private
Enumerator
Error
syntax or logical error was encountered.
Offset
It's a valid offset from UTC.
LocalTime
No zone offset was specified, it's an implementation defined zone offset.
UTC
Definition at line 221 of file qabstractdatetime_p.h.
         {
             Error,
             Offset,
             LocalTime,
             UTC
         };
Constructors and Destructors
AbstractDateTime()
AbstractDateTime::AbstractDateTime (const QDateTime & dateTime)
Definition at line 55 of file qabstractdatetime.cpp.
                                                             : m_dateTime(dateTime)
 {
     Q_ASSERT(dateTime.isValid());
 }
Functions
copyTimeSpec()
void AbstractDateTime::copyTimeSpec (const QDateTime & from, QDateTime & to) static protected
Makes the QDateTime::timeSpec() and QDateTime::zoneOffset() of ot * consistent to from.
Definition at line 373 of file qabstractdatetime.cpp.
Referenced by QPatternist::Date::fromDateTime(), QPatternist::GDay::fromDateTime(), QPatternist::GYearMonth::fromDateTime(), QPatternist::GYear::fromDateTime(), QPatternist::GMonthDay::fromDateTime(), QPatternist::GMonth::fromDateTime(), and QPatternist::SchemaTime::fromDateTime().
 {
     switch(from.timeSpec())
     {
         case Qt::UTC:
         /* Fallthrough. */
         case Qt::LocalTime:
         {
             to.setTimeSpec(from.timeSpec());
             return;
         }
         case Qt::OffsetFromUTC:
         {
             to.setUtcOffset(from.utcOffset());
             Q_ASSERT(to.timeSpec() == Qt::OffsetFromUTC);
             return;
         }
     }
 }
create()
QDateTime AbstractDateTime::create (AtomicValue::Ptr & errorMessage, const QString & lexicalSource, const CaptureTable & captTable) static protected
Definition at line 64 of file qabstractdatetime.cpp.
Referenced by QPatternist::Date::fromLexical(), QPatternist::GDay::fromLexical(), QPatternist::GMonthDay::fromLexical(), QPatternist::GYearMonth::fromLexical(), QPatternist::GYear::fromLexical(), QPatternist::GMonth::fromLexical(), QPatternist::SchemaTime::fromLexical(), and QPatternist::DateTime::fromLexical().
 {
     QRegExp myExp(captTable.regExp);
     if(!myExp.exactMatch(lexicalSource))
     {
         badData(QString());
     }
     const QStringList capts(myExp.capturedTexts());
     const QString yearStr(getCapt(year));
     if(yearStr.size() > 4 && yearStr.at(0) == QLatin1Char('0'))
     {
         badData(QtXmlPatterns::tr("Year %1 is invalid because it begins with %2.")
                 .arg(formatData(yearStr)).arg(formatData("0")));
     }
     /* If the strings are empty, load default values which are
      * guranteed to pass the validness tests. */
     const QString monthStr(getCapt(month));
     const QString dayStr(getCapt(day));
     YearProperty year = yearStr.isEmpty() ? DefaultYear : yearStr.toInt();
     if(getCapt(yearSign) == QChar::fromLatin1('-'))
         year = -year;
     const MonthProperty month = monthStr.isEmpty() ? DefaultMonth : monthStr.toInt();
     const MonthProperty day = dayStr.isEmpty() ? DefaultDay : dayStr.toInt();
     if(!QDate::isValid(year, month, day))
     {
         /* Try to give an intelligent message. */
         if(day > 31 || day < 1)
         {
             badData(QtXmlPatterns::tr("Day %1 is outside the range %2..%3.")
                     .arg(formatData(QString::number(day)))
                     .arg(formatData("01"))
                     .arg(formatData("31")));
         }
         else if(month > 12 || month < -12 || month == 0)
         {
             badData(QtXmlPatterns::tr("Month %1 is outside the range %2..%3.")
                     .arg(month)
                     .arg(formatData("01"))
                     .arg(formatData("12")));
         }
         else if(QDate::isValid(DefaultYear, month, day))
         {
             /* We can't use the badData() macro here because we need a different
              * error code: FODT0001 instead of FORG0001. */
             errorMessage = ValidationError::createError(QtXmlPatterns::tr(
                                "Overflow: Can't represent date %1.")
                                .arg(formatData(QLatin1String("%1-%2-%3"))
                                     .arg(year).arg(month).arg(day)),
                                ReportContext::FODT0001);
             return QDateTime();
         }
         else
         {
             badData(QtXmlPatterns::tr("Day %1 is invalid for month %2.")
                          .arg(formatData(QString::number(day)))
                          .arg(formatData(QString::number(month))));
         }
     }
     /* Parse the zone offset. */
     ZoneOffsetParseResult zoResult;
     const ZOTotal offset = parseZoneOffset(zoResult, capts, captTable);
     if(zoResult == Error)
     {
         errorMessage = ValidationError::createError();
         /* We encountered an error, so stop processing. */
         return QDateTime();
     }
     QDate date(year, month, day);
     /* Only deal with time if time is needed. */
     if(captTable.hour == -1)
     {
         QDateTime result(date);
         setUtcOffset(result, zoResult, offset);
         return result;
     }
     else
     {
         /* Now, it's time for the time-part.
          *
          * If the strings are empty, toInt() will return 0, which
          * in all cases is valid properties. */
         const QString hourStr(getCapt(hour));
         const QString minutesStr(getCapt(minutes));
         const QString secondsStr(getCapt(seconds));
         HourProperty hour = hourStr.toInt();
         const MinuteProperty mins = minutesStr.toInt();
         const SecondProperty secs = secondsStr.toInt();
         QString msecondsStr(getSafeCapt(mseconds));
         if(!msecondsStr.isEmpty())
             msecondsStr = msecondsStr.leftJustified(3, QLatin1Char('0'), true);
         const MSecondProperty msecs = msecondsStr.toInt();
         if(hour == 24)
         {
             /* 24:00:00.00 is an invalid time for QTime, so handle it here. */
             if(mins != 0 || secs != 0 || msecs != 0)
             {
                 badData(QtXmlPatterns::tr("Time 24:%1:%2.%3 is invalid. "
                                           "Hour is 24, but minutes, seconds, "
                                           "and milliseconds are not all 0; ")
                         .arg(mins).arg(secs).arg(msecs));
             }
             else
             {
                 hour = 0;
                 date = date.addDays(1);
             }
         }
         else if(!QTime::isValid(hour, mins, secs, msecs))
         {
             badData(QtXmlPatterns::tr("Time %1:%2:%3.%4 is invalid.")
                          .arg(hour).arg(mins).arg(secs).arg(msecs));
         }
         const QTime time(hour, mins, secs, msecs);
         Q_ASSERT(time.isValid());
         QDateTime result(date, time);
         setUtcOffset(result, zoResult, offset);
         return result;
     }
 }
dateToString()
QString AbstractDateTime::dateToString () const
Returns
m_dateTime's date part converted to string. This is for example "2004-05-12" or "-2004-05-12".
Definition at line 307 of file qabstractdatetime.cpp.
Referenced by QPatternist::Date::stringValue(), and QPatternist::DateTime::stringValue().
 {
     return m_dateTime.toString(QLatin1String("yyyy-MM-dd"));
 }
fromValue()
Item AbstractDateTime::fromValue (const QDateTime & dt) const virtual
A factory function for creating instances that are of the dynamic type of this class, that represents dt.
The default implementation performs an assert() call. This function is not pure virtual because all sub-classes do not use it.
Reimplemented in QPatternist::DateTime, QPatternist::SchemaTime, and QPatternist::Date.
Definition at line 394 of file qabstractdatetime.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "Calling AbstractDateTime::fromDateTime() makes no sense.");
     return Item();
 }
isRangeValid()
bool AbstractDateTime::isRangeValid (const QDate & date, QString & message) static
Determines whether dt is a date-time that can be represented, and isn't too early or too late. If it is valid, true is returned. Otherwise, false is returned and message is set to contain a translated message for human consumption, describing the error.
Definition at line 295 of file qabstractdatetime.cpp.
Referenced by QPatternist::DateTimeDurationMathematician::calculate().
 {
     if(date.isValid())
         return true;
     else
     {
         message = QtXmlPatterns::tr("Overflow: Date can't be represented.");
         return false;
     }
 }
parseZoneOffset()
ZOTotal AbstractDateTime::parseZoneOffset (ZoneOffsetParseResult & result, const QStringList & capts, const CaptureTable & captTable) static private
Parses the zone offset. All types use zone offsets.
If result is set to Offset, the offset is returned, otherwise the return value is undefined.
The offset is in seconds.
Definition at line 200 of file qabstractdatetime.cpp.
Referenced by create().
 {
     const QString zoneOffsetSignStr(getCapt(zoneOffsetSign));
     if(zoneOffsetSignStr.isEmpty())
     {
         const QString zoneOffsetUTCStr(getCapt(zoneOffsetUTCSymbol));
         Q_ASSERT(zoneOffsetUTCStr.isEmpty() || zoneOffsetUTCStr == QLatin1String("Z"));
         if(zoneOffsetUTCStr.isEmpty())
             result = LocalTime;
         else
             result = UTC;
         return 0;
     }
     Q_ASSERT(zoneOffsetSignStr == QLatin1String("-") || zoneOffsetSignStr == QLatin1String("+"));
     const QString zoneOffsetHourStr(getCapt(zoneOffsetHour));
     Q_ASSERT(!zoneOffsetHourStr.isEmpty());
     const ZOHourProperty zoHour = zoneOffsetHourStr.toInt();
     if(zoHour > 14 || zoHour < -14)
     {
         result = Error;
         return 0;
         /*
         badZOData(QtXmlPatterns::tr("%1 it is not a valid hour property in a zone offset. "
                        "It must be less than or equal to 14.").arg(zoHour));
                        */
     }
     const QString zoneOffsetMinuteStr(getCapt(zoneOffsetMinute));
     Q_ASSERT(!zoneOffsetMinuteStr.isEmpty());
     const ZOHourProperty zoMins = zoneOffsetMinuteStr.toInt();
     if(zoHour == 14 && zoMins != 0)
     {
         /*
         badZOData(QtXmlPatterns::tr("When the hour property in a zone offset is 14, the minute property "
                        "must be 0, not %1.").arg(zoMins));
                        */
         result = Error;
         return 0;
     }
     else if(zoMins > 59 || zoMins < -59)
     {
         /*
         badZOData(QtXmlPatterns::tr("The minute property in a zone offset cannot be larger than 59. "
                        "%1 is therefore invalid.").arg(zoMins));
                        */
         result = Error;
         return 0;
     }
     if(zoHour == 0 && zoMins == 0) /* "-00:00" and "+00:00" is equal to 'Z'. */
     {
         result = UTC;
         return 0;
     }
     else
     {
         ZOTotal zoneOffset = (zoHour * 60 + zoMins) * 60;
         if(zoneOffsetSignStr == QChar::fromLatin1('-'))
             zoneOffset = -zoneOffset;
         result = Offset;
         return zoneOffset;
     }
 }
serializeMSeconds()
QString AbstractDateTime::serializeMSeconds (const MSecondProperty msecs) static
Serializes the milli seconds msecs into a string representation. For example, if msecs is 1, ".001" is returned; if msecs is 100 then is ".1" returned.
Definition at line 312 of file qabstractdatetime.cpp.
Referenced by timeToString().
 {
     QString retval;
     retval.append(QLatin1Char('.'));
     int div = 100;
     MSecondProperty msecs = mseconds;
     while(msecs > 0)
     {
         int d = msecs / div;
         retval.append(QLatin1Char(d + '0'));
         msecs = msecs % div;
         div = div / 10;
     }
     return retval;
 }
setUtcOffset()
void AbstractDateTime::setUtcOffset (QDateTime & result, const ZoneOffsetParseResult zoResult, const int zoOffset) inline static private
Definition at line 276 of file qabstractdatetime.cpp.
Referenced by create().
 {
     if(zoResult == UTC)
         result.setTimeSpec(Qt::UTC);
     else if(zoResult == LocalTime)
         result.setTimeSpec(Qt::LocalTime);
     else
     {
         Q_ASSERT(zoResult == Offset);
         result.setUtcOffset(zoOffset);
     }
 }
timeToString()
QString AbstractDateTime::timeToString () const
Returns
m_dateTime's time part converted to string. This is for example "12" or "01.023".
Definition at line 330 of file qabstractdatetime.cpp.
Referenced by QPatternist::SchemaTime::stringValue(), and QPatternist::DateTime::stringValue().
 {
     QString base(m_dateTime.toString(QLatin1String("hh:mm:ss")));
     const MSecondProperty msecs = m_dateTime.time().msec();
     if(msecs)
         base.append(serializeMSeconds(msecs));
     return base;
 }
toDateTime()
const QDateTime& QPatternist::AbstractDateTime::toDateTime () const inline
Returns
the date time this class represents, as a QDateTime.
Definition at line 97 of file qabstractdatetime_p.h.
Referenced by QPatternist::AbstractDateTimeMathematician::calculate(), QPatternist::AbstractDateTimeToGYearCaster::castFrom(), QPatternist::AbstractDateTimeToGYearMonthCaster::castFrom(), QPatternist::AbstractDateTimeToGMonthCaster::castFrom(), QPatternist::AbstractDateTimeToGMonthDayCaster::castFrom(), QPatternist::AbstractDateTimeToGDayCaster::castFrom(), QPatternist::AbstractDateTimeToDateTimeCaster::castFrom(), QPatternist::AbstractDateTimeToDateCaster::castFrom(), QPatternist::AbstractDateTimeToTimeCaster::castFrom(), QPatternist::XsdTypeChecker::checkConstrainingFacets(), QPatternist::AbstractDateTimeComparator::equals(), QPatternist::DateTimeFN::evaluateSingleton(), QPatternist::AdjustTimezone::evaluateSingleton(), QPatternist::ExtractFromDateTimeFN< TimezoneFromAbstractDateTimeFN >::evaluateSingleton(), and QPatternist::AtomicValue::toQt().
         {
             return m_dateTime;
         }
zoneOffsetToString()
QString AbstractDateTime::zoneOffsetToString () const protected
Returns
m_dateTime' zone offset converted to string, as per the the W3C XML Schema types. This is for example "Z" or "+12.00"(depending on m_dateTime).
Definition at line 341 of file qabstractdatetime.cpp.
Referenced by QPatternist::Date::stringValue(), QPatternist::GDay::stringValue(), QPatternist::GYear::stringValue(), QPatternist::GYearMonth::stringValue(), QPatternist::GMonth::stringValue(), QPatternist::GMonthDay::stringValue(), QPatternist::SchemaTime::stringValue(), and QPatternist::DateTime::stringValue().
 {
     switch(m_dateTime.timeSpec())
     {
         case Qt::LocalTime:
             return QString();
         case Qt::UTC:
             return QLatin1String("Z");
         default:
         {
             Q_ASSERT(m_dateTime.timeSpec() == Qt::OffsetFromUTC);
             const int zoneOffset = m_dateTime.utcOffset();
             Q_ASSERT(zoneOffset != 0);
             const int posZoneOffset = qAbs(zoneOffset);
             /* zoneOffset is in seconds. */
             const int hours = posZoneOffset/(60 * 60);
             const int minutes = (posZoneOffset % (60 * 60)) / 60;
             QString result;
             result.reserve(6);
             result.append(zoneOffset < 0 ? QLatin1Char('-') : QLatin1Char('+'));
             result.append(QString::number(hours).rightJustified(2, QLatin1Char('0')));
             result.append(QLatin1Char(':'));
             result.append(QString::number(minutes).rightJustified(2, QLatin1Char('0')));
             return result;
         }
     }
 }
Properties
m_dateTime
const QDateTime QPatternist::AbstractDateTime::m_dateTime protected
Definition at line 218 of file qabstractdatetime_p.h.
Referenced by dateToString(), QPatternist::GYearMonth::stringValue(), QPatternist::GDay::stringValue(), QPatternist::GYear::stringValue(), QPatternist::GMonth::stringValue(), QPatternist::GMonthDay::stringValue(), timeToString(), toDateTime(), and zoneOffsetToString().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qabstractdatetime_p.h
/src/xmlpatterns/data/qabstractdatetime.cpp