Qt 4.8: QVarLengthArray< T, Prealloc > Class Template Reference
QVarLengthArray< T, Prealloc > Class Template Reference
#include <qcontainerfwd.h>
Public Types
typedef const T * const_iterator
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef qptrdiff difference_type
typedef T * iterator
typedef value_type * pointer
typedef value_type & reference
typedef int size_type
typedef T value_type
Public Functions
void append (const T &t)
void append (const T *buf, int size)
const T & at (int idx) const
iterator begin ()
const_iterator begin () const
int capacity () const
void clear ()
const_iterator constBegin () const
const T * constData () const
const_iterator constEnd () const
int count () const
T * data ()
const T * data () const
iterator end ()
const_iterator end () const
iterator erase (iterator begin, iterator end)
iterator erase (iterator pos)
void insert (int i, const T &t)
void insert (int i, int n, const T &t)
iterator insert (iterator before, int n, const T &x)
iterator insert (iterator before, const T &x)
bool isEmpty () const
QVarLengthArray< T, Prealloc > & operator+= (const T &t)
QVarLengthArray< T, Prealloc > & operator<< (const T &t)
QVarLengthArray< T, Prealloc > & operator= (const QVarLengthArray< T, Prealloc > &other)
T & operator[] (int idx)
const T & operator[] (int idx) const
void prepend (const T &t)
QVarLengthArray (int size=0)
QVarLengthArray (const QVarLengthArray< T, Prealloc > &other)
void remove (int i)
void remove (int i, int n)
void removeLast ()
void replace (int i, const T &t)
void reserve (int size)
void resize (int size)
int size () const
T value (int i) const
T value (int i, const T &defaultValue) const
~QVarLengthArray ()
Private Functions
void realloc (int size, int alloc)
Properties
union {
char array [sizeof(qint64) *(((Prealloc
*sizeof(T))/sizeof(qint64))+1)]
qint64 q_for_alignment_1
double q_for_alignment_2
};
int a
T * ptr
int s
Friends
class QPodList< T, Prealloc >
Detailed Description
template<class T, int Prealloc>
class QVarLengthArray< T, Prealloc >
Definition at line 64 of file qcontainerfwd.h.
Typedefs
const_iterator
template<class T, int Prealloc> typedef const T* QVarLengthArray< T, Prealloc >::const_iterator
Definition at line 155 of file qvarlengtharray.h.
const_pointer
template<class T, int Prealloc> typedef const value_type* QVarLengthArray< T, Prealloc >::const_pointer
Definition at line 148 of file qvarlengtharray.h.
const_reference
template<class T, int Prealloc> typedef const value_type& QVarLengthArray< T, Prealloc >::const_reference
Definition at line 150 of file qvarlengtharray.h.
difference_type
template<class T, int Prealloc> typedef qptrdiff QVarLengthArray< T, Prealloc >::difference_type
Definition at line 151 of file qvarlengtharray.h.
iterator
template<class T, int Prealloc> typedef T* QVarLengthArray< T, Prealloc >::iterator
Definition at line 154 of file qvarlengtharray.h.
pointer
template<class T, int Prealloc> typedef value_type* QVarLengthArray< T, Prealloc >::pointer
Definition at line 147 of file qvarlengtharray.h.
reference
template<class T, int Prealloc> typedef value_type& QVarLengthArray< T, Prealloc >::reference
Definition at line 149 of file qvarlengtharray.h.
size_type
template<class T, int Prealloc> typedef int QVarLengthArray< T, Prealloc >::size_type
Definition at line 145 of file qvarlengtharray.h.
value_type
template<class T, int Prealloc> typedef T QVarLengthArray< T, Prealloc >::value_type
Definition at line 146 of file qvarlengtharray.h.
Constructors and Destructors
QVarLengthArray() [1/2]
template<class T , int Prealloc> Q_INLINE_TEMPLATE QVarLengthArray< T, Prealloc >::QVarLengthArray (int size = 0) inline explicit
Definition at line 184 of file qvarlengtharray.h.
     : s(asize) {
     if (s > Prealloc) {
         ptr = reinterpret_cast<T *>(qMalloc(s * sizeof(T)));
         Q_CHECK_PTR(ptr);
         a = s;
     } else {
         ptr = reinterpret_cast<T *>(array);
         a = Prealloc;
     }
     if (QTypeInfo<T>::isComplex) {
         T *i = ptr + s;
         while (i != ptr)
             new (--i) T;
     }
 }
QVarLengthArray() [2/2]
template<class T, int Prealloc> QVarLengthArray< T, Prealloc >::QVarLengthArray (const QVarLengthArray< T, Prealloc > & other) inline
Definition at line 68 of file qvarlengtharray.h.
         : a(Prealloc), s(0), ptr(reinterpret_cast<T *>(array))
     {
         append(other.constData(), other.size());
     }
~QVarLengthArray()
template<class T, int Prealloc> QVarLengthArray< T, Prealloc >::~QVarLengthArray () inline
Definition at line 74 of file qvarlengtharray.h.
{
         if (QTypeInfo<T>::isComplex) {
             T *i = ptr + s;
             while (i-- != ptr)
                 i->~T();
         }
         if (ptr != reinterpret_cast<T *>(array))
             qFree(ptr);
     }
Functions
append() [1/2]
template<class T, int Prealloc> void QVarLengthArray< T, Prealloc >::append (const T & t) inline
Definition at line 118 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::append(), QTriangulatingStroker::arcPoints(), QGLShader::compileSourceCode(), QVGPixmapConvolutionFilter::draw(), QPlastiqueStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QVGPaintEngine::drawPixmapFragments(), QVGPaintEngine::drawPolygon(), QPlastiqueStyle::drawPrimitive(), QODBCResult::exec(), QOCICols::execBatch(), init(), QTriangulator< T >::ComplexToSimple::insertEdgeIntoVectorIfWanted(), QMetaObject::invokeMethod(), QTextDocumentLayoutPrivate::layoutTable(), QMetaObject::newInstance(), QLocalePrivate::numberToCLocale(), QVarLengthArray< QVariant, 9 >::operator+=(), QVarLengthArray< QVariant, 9 >::operator<<(), QVarLengthArray< QVariant, 9 >::operator=(), QVGPaintEnginePrivate::painterPathToVGPath(), QDBusMetaObjectGenerator::parseMethods(), parseNumbersArray(), parsePathDataFast(), QDBusMetaObjectGenerator::parseSignals(), qDrawBorderPixmap(), QEglProperties::QEglProperties(), QVarLengthArray< QVariant, 9 >::QVarLengthArray(), QCoreApplication::removePostedEvents(), QTriangulator< T >::ComplexToSimple::removeUnwantedEdgesAndConnect(), QDeclarativeJS::Parser::reparseAsQualifiedId(), QWSRegionCommand::setData(), QEglProperties::setValue(), QTextEngine::shapeTextWithHarfbuzz(), QObjectPrivate::signalSignature(), QDBusConnectionPrivate::socketRead(), QDBusConnectionPrivate::socketWrite(), QWidgetBackingStore::sync(), toSQLTCHAR(), and QVGPaintEnginePrivate::vectorPathToVGPath().
{
         if (s == a)   // i.e. s != 0
             realloc(s, s<<1);
         const int idx = s++;
         if (QTypeInfo<T>::isComplex) {
             new (ptr + idx) T(t);
         } else {
             ptr[idx] = t;
         }
     }
append() [2/2]
template<class T, int Prealloc> Q_OUTOFLINE_TEMPLATE void QVarLengthArray< T, Prealloc >::append (const T * buf, int size)
Definition at line 210 of file qvarlengtharray.h.
 {
     Q_ASSERT(abuf);
     if (increment <= 0)
         return;
     const int asize = s + increment;
     if (asize >= a)
         realloc(s, qMax(s*2, asize));
     if (QTypeInfo<T>::isComplex) {
         // call constructor for new objects (which can throw)
         while (s < asize)
             new (ptr+(s++)) T(*abuf++);
     } else {
         qMemCopy(&ptr[s], abuf, increment * sizeof(T));
         s = asize;
     }
 }
at()
template<class T, int Prealloc> const T& QVarLengthArray< T, Prealloc >::at (int idx) const inline
Definition at line 113 of file qvarlengtharray.h.
Referenced by QFontEngineDirectWrite::canRender(), QOCICols::execBatch(), QTextLine::glyphs(), operator==(), QTriangulator< T >::ComplexToSimple::removeUnwantedEdgesAndConnect(), QWizardPrivate::updateButtonLayout(), and QVarLengthArray< QVariant, 9 >::value().
 { return operator[](idx); }
begin() [1/2]
template<class T, int Prealloc> iterator QVarLengthArray< T, Prealloc >::begin () inline
Definition at line 157 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::insert(), QVarLengthArray< QVariant, 9 >::prepend(), and QVarLengthArray< QVariant, 9 >::remove().
 { return ptr; }
begin() [2/2]
template<class T, int Prealloc> const_iterator QVarLengthArray< T, Prealloc >::begin () const inline
Definition at line 158 of file qvarlengtharray.h.
 { return ptr; }
capacity()
template<class T, int Prealloc> int QVarLengthArray< T, Prealloc >::capacity () const inline
Definition at line 102 of file qvarlengtharray.h.
Referenced by QBBSystemLocaleData::readPpsValue().
 { return a; }
clear()
template<class T, int Prealloc> void QVarLengthArray< T, Prealloc >::clear () inline
Definition at line 100 of file qvarlengtharray.h.
Referenced by QPlastiqueStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QPlastiqueStyle::drawPrimitive(), QVarLengthArray< QVariant, 9 >::operator=(), QTriangulator< T >::ComplexToSimple::removeUnwantedEdgesAndConnect(), and QDeclarativeVME::run().
 { resize(0); }
constBegin()
template<class T, int Prealloc> const_iterator QVarLengthArray< T, Prealloc >::constBegin () const inline
Definition at line 159 of file qvarlengtharray.h.
 { return ptr; }
constData()
template<class T, int Prealloc> const T* QVarLengthArray< T, Prealloc >::constData () const inline
Definition at line 144 of file qvarlengtharray.h.
Referenced by blendCursor(), QGLContext::choosePixelFormat(), QODBCDriver::cleanup(), QDeclarativePropertyPrivate::connect(), QObject::connect(), QDeclarativeNotifierEndpoint::disconnect(), QDeclarativeBoundSignal::disconnect(), QObject::disconnect(), QVGPixmapConvolutionFilter::draw(), QPlastiqueStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QX11PaintEngine::drawFreetype(), QOpenGLPaintEngine::drawLines(), drawLines(), QOpenGLPaintEngine::drawPoints(), drawPoints(), QVGPaintEngine::drawPolygon(), QOpenGLPaintEngine::drawPolygon(), QPlastiqueStyle::drawPrimitive(), QRasterPaintEngine::drawTextItem(), QDirectFBPaintEnginePrivate::drawTiledPixmap(), QODBCResult::exec(), fillRects(), fromSQLTCHAR(), QStaticTextPrivate::get(), QMetaObject::invokeMethod(), QSystemLibrary::load(), QMetaObject::newInstance(), QVarLengthArray< QVariant, 9 >::operator=(), QVGPaintEnginePrivate::painterPathToVGPath(), parsePathDataFast(), pfiToQGLFormat(), qGetStringData(), qMakeFieldInfo(), qt_find_latin1_string(), QVarLengthArray< QVariant, 9 >::QVarLengthArray(), qWarnODBCHandle(), QWSRegionCommand::setData(), QGLPixmapConvolutionFilter::setUniforms(), QLocalePrivate::stringToDouble(), QLocalePrivate::stringToLongLong(), QLocalePrivate::stringToUnsLongLong(), QSslSocketBackendPrivate::transmit(), QSystemLocalePrivate::uiLanguages(), and QVGPaintEnginePrivate::vectorPathToVGPath().
 { return ptr; }
constEnd()
template<class T, int Prealloc> const_iterator QVarLengthArray< T, Prealloc >::constEnd () const inline
Definition at line 162 of file qvarlengtharray.h.
 { return ptr + s; }
count()
template<class T, int Prealloc> int QVarLengthArray< T, Prealloc >::count () const inline
Definition at line 97 of file qvarlengtharray.h.
Referenced by QDeclarativeObjectMethodScriptClass::callMethod(), QScript::callQtMethod(), QPlastiqueStyle::drawControl(), QX11PaintEngine::drawFreetype(), QVGPaintEngine::drawPolygon(), init(), init_direct(), QTextDocumentLayoutPrivate::layoutTable(), QVGPaintEnginePrivate::painterPathToVGPath(), parsePathDataFast(), parseTransformationMatrix(), QCoreApplication::removePostedEvents(), QVGPaintEnginePrivate::vectorPathToVGPath(), QDBusMetaObjectGenerator::write(), and QMutexPool::~QMutexPool().
 { return s; }
data() [1/2]
template<class T, int Prealloc> T* QVarLengthArray< T, Prealloc >::data () inline
Definition at line 142 of file qvarlengtharray.h.
Referenced by QFontEngineDirectWrite::addGlyphsToPath(), QFontEngine::addOutlineToPath(), QPainterPath::addText(), QRawFont::advancesForGlyphIndexes(), buttonChange(), QScript::callQtMethod(), QProxyFontEngine::canRender(), QFontEngineDirectWrite::canRender(), QDir::cleanPath(), QODBCDriver::cleanup(), QGLShader::compileSourceCode(), convertARGB32_to_RGBA4444(), QWindowsLocalCodec::convertToUnicode(), QSystemLocalePrivate::currencySymbol(), QTextLine::cursorToX(), QGridLayoutRowData::distributeMultiCells(), draw_text_item_win(), QVGPaintEngine::drawCachedGlyphs(), QPainter::drawGlyphRun(), QPainterPrivate::drawGlyphs(), QOpenGLPaintEngine::drawPolygon(), QRasterPaintEngine::drawPolygon(), QPaintEngine::drawPolygon(), QPaintEngineEx::drawPolygon(), QX11PaintEngine::drawRects(), QPainter::drawText(), QGL2PaintEngineEx::drawTextItem(), QOpenGLPaintEngine::drawTextItem(), QVGPaintEngine::drawTextItem(), QDB2Result::exec(), QScript::QObjectConnectionManager::execute(), QIBaseResultPrivate::fetchArray(), QX11PaintEnginePrivate::fillPolygon_dev(), QX11PaintEnginePrivate::fillPolygon_translated(), QSystemLocalePrivate::getLocaleInfo(), QDirectFBScreen::getSurfaceDescription(), QMacInputContext::globalEventProcessor(), init(), init_direct(), QSqlQueryModelPrivate::initColOffsets(), initWritingSystems(), QTextEngine::itemize(), QString::lastIndexOf(), QStringRef::lastIndexOf(), QSystemLibrary::load(), macList(), macValue(), QFileSystemEngine::nativeAbsoluteFilePath(), QNativeSocketEnginePrivate::nativePendingDatagramSize(), QFileSystemModelPrivate::node(), QMetaObject::normalizedSignature(), QMetaObject::normalizedType(), QODBCDriver::open(), QFileSystemEngine::owner(), QDeclarativeParticlesPainter::paint(), pfiToQGLFormat(), QProcessPrivate::processStarted(), PtsToRegion(), QTest::qExec(), qGetBinaryData(), qGetStringData(), qMakeFieldInfo(), qt_format_text(), qt_merge_clip(), QTextLineItemIterator::QTextLineItemIterator(), qtKey2CocoaKey(), qtValue(), qWarnODBCHandle(), QInotifyFileSystemWatcherEngine::readFromInotify(), QConfFileSettingsPrivate::readPlistFile(), QBBSystemLocaleData::readPpsValue(), QFontEngineMac::recalcAdvances(), QProxyFontEngine::recalcAdvances(), QFontEngineDirectWrite::recalcAdvances(), registerFont(), removeGroupSeparators(), QVarLengthArray< QVariant, 9 >::replace(), QFileSystemEngine::resolveGroupName(), QFileSystemEngine::resolveUserName(), QVGCompositionHelper::setScissor(), QGridLayoutPrivate::setupLayoutData(), QTextEngine::shapeTextMac(), sm_performSaveYourself(), QProxyFontEngine::stringToCMap(), QFontEngineDirectWrite::stringToCMap(), QFontEngineXLFD::stringToCMap(), QFontEngineMacMulti::stringToCMapInternal(), QX11PaintEnginePrivate::strokePolygon_dev(), QX11PaintEnginePrivate::strokePolygon_translated(), QEglContext::swapBuffersRegion2NOK(), QSystemLocalePrivate::toCurrencyString(), QApplication::topLevelAt(), toSQLTCHAR(), QSslSocketBackendPrivate::transmit(), QSystemLocalePrivate::uiLanguages(), QVGPaintEngine::updateScissor(), QDBusMetaObjectGenerator::write(), QRfbSingleColorHextile< SRC >::write(), QRfbDualColorHextile< SRC >::write(), QRfbMultiColorHextile< SRC >::write(), and QTextLine::xToCursor().
 { return ptr; }
data() [2/2]
template<class T, int Prealloc> const T* QVarLengthArray< T, Prealloc >::data () const inline
Definition at line 143 of file qvarlengtharray.h.
 { return ptr; }
end() [1/2]
template<class T, int Prealloc> iterator QVarLengthArray< T, Prealloc >::end () inline
Definition at line 160 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::insert().
 { return ptr + s; }
end() [2/2]
template<class T, int Prealloc> const_iterator QVarLengthArray< T, Prealloc >::end () const inline
Definition at line 161 of file qvarlengtharray.h.
 { return ptr + s; }
erase() [1/2]
template<class T , int Prealloc> Q_OUTOFLINE_TEMPLATE QVarLengthArray< T, Prealloc >::iterator QVarLengthArray< T, Prealloc >::erase (iterator begin, iterator end)
Definition at line 362 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::insert(), and QVarLengthArray< QVariant, 9 >::remove().
 {
     int f = int(abegin - ptr);
     int l = int(aend - ptr);
     int n = l - f;
     if (QTypeInfo<T>::isComplex) {
         qCopy(ptr + l, ptr + s, ptr + f);
         T *i = ptr + s;
         T *b = ptr + s - n;
         while (i != b) {
             --i;
             i->~T();
         }
     } else {
         memmove(ptr + f, ptr + l, (s - l) * sizeof(T));
     }
     s -= n;
     return ptr + f;
 }
erase() [2/2]
template<class T, int Prealloc> iterator QVarLengthArray< T, Prealloc >::erase (iterator pos) inline
Definition at line 166 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::erase().
 { return erase(pos, pos+1); }
insert() [1/4]
template<class T, int Prealloc> void QVarLengthArray< T, Prealloc >::insert (int i, const T & t) inline
Definition at line 306 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::constEnd(), QVarLengthArray< QVariant, 9 >::insert(), QVarLengthArray< QVariant, 9 >::operator+=(), and QVarLengthArray< QVariant, 9 >::prepend().
 { Q_ASSERT_X(i >= 0 && i <= s, "QVarLengthArray::insert", "index out of range");
   insert(begin() + i, 1, t); }
insert() [2/4]
template<class T, int Prealloc> void QVarLengthArray< T, Prealloc >::insert (int i, int n, const T & t) inline
Definition at line 310 of file qvarlengtharray.h.
 { Q_ASSERT_X(i >= 0 && i <= s, "QVarLengthArray::insert", "index out of range");
   insert(begin() + i, n, t); }
insert() [3/4]
template<class T, int Prealloc> Q_OUTOFLINE_TEMPLATE QVarLengthArray< T, Prealloc >::iterator QVarLengthArray< T, Prealloc >::insert (iterator before, int n, const T & x)
Definition at line 335 of file qvarlengtharray.h.
 {
     int offset = int(before - ptr);
     if (n != 0) {
         resize(s + n);
         const T copy(t);
         if (QTypeInfo<T>::isStatic) {
             T *b = ptr + offset;
             T *j = ptr + s;
             T *i = j - n;
             while (i != b)
                 *--j = *--i;
             i = b + n;
             while (i != b)
                 *--i = copy;
         } else {
             T *b = ptr + offset;
             T *i = b + n;
             memmove(i, b, (s - offset - n) * sizeof(T));
             while (i != b)
                 new (--i) T(copy);
         }
     }
     return ptr + offset;
 }
insert() [4/4]
template<class T, int Prealloc> iterator QVarLengthArray< T, Prealloc >::insert (iterator before, const T & x) inline
Definition at line 164 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::insert().
 { return insert(before, 1, x); }
isEmpty()
template<class T, int Prealloc> bool QVarLengthArray< T, Prealloc >::isEmpty () const inline
Definition at line 98 of file qvarlengtharray.h.
Referenced by QTriangulatingStroker::arcPoints(), QDirectFBScreen::exposeRegion(), QMacInputContext::globalEventProcessor(), QTriangulator< T >::ComplexToSimple::insertEdgeIntoVectorIfWanted(), and QTriangulator< T >::ComplexToSimple::removeUnwantedEdgesAndConnect().
 { return (s == 0); }
operator+=()
template<class T, int Prealloc> QVarLengthArray<T, Prealloc>& QVarLengthArray< T, Prealloc >::operator+= (const T & t) inline
Definition at line 131 of file qvarlengtharray.h.
     { append(t); return *this; }
operator<<()
template<class T, int Prealloc> QVarLengthArray<T, Prealloc>& QVarLengthArray< T, Prealloc >::operator<< (const T & t) inline
Definition at line 129 of file qvarlengtharray.h.
     { append(t); return *this; }
operator=()
template<class T, int Prealloc> QVarLengthArray<T, Prealloc>& QVarLengthArray< T, Prealloc >::operator= (const QVarLengthArray< T, Prealloc > & other) inline
Definition at line 83 of file qvarlengtharray.h.
     {
         if (this != &other) {
             clear();
             append(other.constData(), other.size());
         }
         return *this;
     }
operator[]() [1/2]
template<class T, int Prealloc> T& QVarLengthArray< T, Prealloc >::operator[] (int idx) inline
Definition at line 105 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::at().
{
         Q_ASSERT(idx >= 0 && idx < s);
         return ptr[idx];
     }
operator[]() [2/2]
template<class T, int Prealloc> const T& QVarLengthArray< T, Prealloc >::operator[] (int idx) const inline
Definition at line 109 of file qvarlengtharray.h.
{
         Q_ASSERT(idx >= 0 && idx < s);
         return ptr[idx];
     }
prepend()
template<class T, int Prealloc> void QVarLengthArray< T, Prealloc >::prepend (const T & t) inline
Definition at line 322 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::operator+=().
 { insert(begin(), 1, t); }
realloc()
template<class T , int Prealloc> Q_OUTOFLINE_TEMPLATE void QVarLengthArray< T, Prealloc >::realloc (int size, int alloc) private
Definition at line 232 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::append(), QPodList< QSockNot *, 32 >::insert(), QVarLengthArray< QVariant, 9 >::removeLast(), QVarLengthArray< QVariant, 9 >::reserve(), and QVarLengthArray< QVariant, 9 >::resize().
 {
     Q_ASSERT(aalloc >= asize);
     T *oldPtr = ptr;
     int osize = s;
     const int copySize = qMin(asize, osize);
     if (aalloc != a) {
         ptr = reinterpret_cast<T *>(qMalloc(aalloc * sizeof(T)));
         Q_CHECK_PTR(ptr);
         if (ptr) {
             s = 0;
             a = aalloc;
             if (QTypeInfo<T>::isStatic) {
                 QT_TRY {
                     // copy all the old elements
                     while (s < copySize) {
                         new (ptr+s) T(*(oldPtr+s));
                         (oldPtr+s)->~T();
                         s++;
                     }
                 } QT_CATCH(...) {
                     // clean up all the old objects and then free the old ptr
                     int sClean = s;
                     while (sClean < osize)
                         (oldPtr+(sClean++))->~T();
                     if (oldPtr != reinterpret_cast<T *>(array) && oldPtr != ptr)
                         qFree(oldPtr);
                     QT_RETHROW;
                 }
             } else {
                 qMemCopy(ptr, oldPtr, copySize * sizeof(T));
             }
         } else {
             ptr = oldPtr;
             return;
         }
     }
     s = copySize;
     if (QTypeInfo<T>::isComplex) {
         // destroy remaining old objects
         while (osize > asize)
             (oldPtr+(--osize))->~T();
     }
     if (oldPtr != reinterpret_cast<T *>(array) && oldPtr != ptr)
         qFree(oldPtr);
     if (QTypeInfo<T>::isComplex) {
         // call default constructor for new objects (which can throw)
         while (s < asize)
             new (ptr+(s++)) T;
     } else {
         s = asize;
     }
 }
remove() [1/2]
template<class T , int Prealloc> void QVarLengthArray< T, Prealloc >::remove (int i) inline
Definition at line 318 of file qvarlengtharray.h.
 { Q_ASSERT_X(i >= 0 && i < s, "QVarLengthArray::remove", "index out of range");
   erase(begin() + i, begin() + i + 1); }
remove() [2/2]
template<class T , int Prealloc> void QVarLengthArray< T, Prealloc >::remove (int i, int n) inline
Definition at line 314 of file qvarlengtharray.h.
 { Q_ASSERT_X(i >= 0 && n >= 0 && i + n <= s, "QVarLengthArray::remove", "index out of range");
   erase(begin() + i, begin() + i + n); }
removeLast()
template<class T, int Prealloc> void QVarLengthArray< T, Prealloc >::removeLast () inline
Definition at line 92 of file qvarlengtharray.h.
Referenced by QTriangulator< T >::ComplexToSimple::insertEdgeIntoVectorIfWanted().
{
         Q_ASSERT(s > 0);
         realloc(s - 1, a);
     }
replace()
template<class T, int Prealloc> void QVarLengthArray< T, Prealloc >::replace (int i, const T & t) inline
Definition at line 326 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::operator+=().
 {
     Q_ASSERT_X(i >= 0 && i < s, "QVarLengthArray::replace", "index out of range");
     const T copy(t);
     data()[i] = copy;
 }
reserve()
template<class T , int Prealloc> Q_INLINE_TEMPLATE void QVarLengthArray< T, Prealloc >::reserve (int size) inline
Definition at line 206 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::capacity(), QDBusConnectionPrivate::deliverCall(), QODBCResult::exec(), and QObjectPrivate::signalSignature().
 { if (asize > a) realloc(s, asize); }
resize()
template<class T , int Prealloc> Q_INLINE_TEMPLATE void QVarLengthArray< T, Prealloc >::resize (int size) inline
Definition at line 202 of file qvarlengtharray.h.
Referenced by QTriangulatingStroker::arcPoints(), QScript::callQtMethod(), QVarLengthArray< QVariant, 9 >::clear(), QWindowsLocalCodec::convertToUnicode(), QSystemLocalePrivate::currencySymbol(), QFontEngine::getGlyphPositions(), QSystemLocalePrivate::getLocaleInfo(), QSqlQueryModelPrivate::initColOffsets(), QVarLengthArray< QVariant, 9 >::insert(), QVarLengthArray< QVariant, 9 >::isEmpty(), QTextEngine::justify(), QSystemLibrary::load(), QFileSystemEngine::nativeAbsoluteFilePath(), QNativeSocketEnginePrivate::nativePendingDatagramSize(), QFileSystemModelPrivate::node(), QFileSystemEngine::owner(), QDeclarativeParticlesPainter::paint(), PtsToRegion(), qDrawBorderPixmap(), qt_format_text(), qt_merge_clip(), qt_regionToPath(), qWarnODBCHandle(), QBBSystemLocaleData::readPpsValue(), QEglProperties::removeValue(), QFileSystemEngine::resolveGroupName(), sm_performSaveYourself(), QSystemLocalePrivate::toCurrencyString(), toSQLTCHAR(), QSslSocketBackendPrivate::transmit(), QSystemLocalePrivate::uiLanguages(), and QDBusMetaObjectGenerator::write().
 { realloc(asize, qMax(asize, a)); }
size()
template<class T, int Prealloc> int QVarLengthArray< T, Prealloc >::size () const inline
Definition at line 96 of file qvarlengtharray.h.
Referenced by QFontEngine::addOutlineToPath(), QFontEngineBox::addOutlineToPath(), QTriangulatingStroker::arcPoints(), QFontEngineBox::boundingBox(), QProxyFontEngine::canRender(), QFontEngineDirectWrite::canRender(), QODBCDriver::cleanup(), QGLShader::compileSourceCode(), QWindowsLocalCodec::convertToUnicode(), QGLTextureGlyphCache::createTextureData(), QSystemLocalePrivate::currencySymbol(), QEventDispatcherUNIXPrivate::doSelect(), QFontEngineMac::draw(), QFontEngineQPF::draw(), QFontEngineQPF1::draw(), draw_text_item_win(), QPaintEnginePrivate::drawBoxTextItem(), QRasterPaintEngine::drawCachedGlyphs(), QPlastiqueStyle::drawComplexControl(), QWindowsXPStyle::drawComplexControl(), QPlastiqueStyle::drawControl(), QX11PaintEngine::drawFreetype(), QPainterPrivate::drawGlyphs(), QVGPaintEngine::drawPixmapFragments(), QPlastiqueStyle::drawPrimitive(), QGL2PaintEngineEx::drawTextItem(), QOpenGLPaintEngine::drawTextItem(), QVGPaintEngine::drawTextItem(), QRasterPaintEngine::drawTextItem(), QPdfBaseEnginePrivate::drawTextItem(), QX11PaintEngine::drawXLFD(), QTriangulatingStroker::endCap(), QDB2Result::exec(), QODBCResult::exec(), QScript::QObjectConnectionManager::execute(), fromSQLTCHAR(), QStaticTextPrivate::get(), QFontEngine::getGlyphPositions(), QSystemLocalePrivate::getLocaleInfo(), QTextLine::glyphs(), QDBusConnectionPrivate::handleMessage(), QSqlQueryModelPrivate::initColOffsets(), QTriangulator< T >::ComplexToSimple::insertEdgeIntoVectorIfWanted(), QMetaObject::invokeMethod(), QVarLengthArray< QVariant, 9 >::isEmpty(), QTriangulatingStroker::join(), QTriangulatingStroker::moveTo(), QFileSystemEngine::nativeAbsoluteFilePath(), QNativeSocketEnginePrivate::nativePendingDatagramSize(), QMetaObject::newInstance(), QFileSystemModelPrivate::node(), QODBCDriver::open(), QVarLengthArray< QVariant, 9 >::operator=(), operator==(), QFileSystemEngine::owner(), path_for_glyphs(), PtsToRegion(), qt_merge_clip(), QVarLengthArray< QVariant, 9 >::QVarLengthArray(), qWarnODBCHandle(), QFontEngineDirectWrite::recalcAdvances(), registerFont(), QEventDispatcherUNIX::registerSocketNotifier(), QTriangulator< T >::ComplexToSimple::removeUnwantedEdgesAndConnect(), QEglProperties::removeValue(), QDeclarativeJS::Parser::reparseAsQualifiedId(), QFileSystemEngine::resolveGroupName(), QFileSystemEngine::resolveUserName(), QWSRegionCommand::setData(), QEventDispatcherUNIX::setSocketNotifierPending(), QEglProperties::setValue(), QTextEngine::shapeTextWithHarfbuzz(), sm_performSaveYourself(), QDBusConnectionPrivate::socketRead(), QDBusConnectionPrivate::socketWrite(), QWidgetBackingStore::sync(), QSystemLocalePrivate::toCurrencyString(), QSslSocketBackendPrivate::transmit(), QSystemLocalePrivate::uiLanguages(), QEventDispatcherUNIX::unregisterSocketNotifier(), QEglProperties::value(), QVarLengthArray< QVariant, 9 >::value(), and QDBusMetaObjectGenerator::write().
 { return s; }
value() [1/2]
template<class T , int Prealloc> Q_OUTOFLINE_TEMPLATE T QVarLengthArray< T, Prealloc >::value (int i) const
Definition at line 292 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::at(), and QTextEngine::justify().
 {
     if (i < 0 || i >= size()) {
         return T();
     }
     return at(i);
 }
value() [2/2]
template<class T, int Prealloc> Q_OUTOFLINE_TEMPLATE T QVarLengthArray< T, Prealloc >::value (int i, const T & defaultValue) const
Definition at line 300 of file qvarlengtharray.h.
 {
     return (i < 0 || i >= size()) ? defaultValue : at(i);
 }
Friends and Related Functions
QPodList< T, Prealloc >
template<class T, int Prealloc> friend class QPodList< T, Prealloc > friend
Definition at line 169 of file qvarlengtharray.h.
Properties
@92
union { ... }
a
template<class T, int Prealloc> int QVarLengthArray< T, Prealloc >::a private
Definition at line 172 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::append(), QVarLengthArray< QVariant, 9 >::capacity(), QDirectFBScreen::getSurfaceDescription(), QPodList< QSockNot *, 32 >::insert(), and QVarLengthArray< QVariant, 9 >::removeLast().
array
template<class T, int Prealloc> char QVarLengthArray< T, Prealloc >::array[sizeof(qint64) *(((Prealloc *sizeof(T))/sizeof(qint64))+1)]
Definition at line 177 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::QVarLengthArray(), QVarLengthArray< QVariant, 9 >::realloc(), and QVarLengthArray< QVariant, 9 >::~QVarLengthArray().
ptr
template<class T, int Prealloc> T* QVarLengthArray< T, Prealloc >::ptr private
Definition at line 174 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::append(), QVarLengthArray< QVariant, 9 >::begin(), QVarLengthArray< QVariant, 9 >::constBegin(), QVarLengthArray< QVariant, 9 >::constData(), QVarLengthArray< QVariant, 9 >::constEnd(), QVarLengthArray< QVariant, 9 >::data(), QVarLengthArray< QVariant, 9 >::end(), QPodList< QSockNot *, 32 >::insert(), QVarLengthArray< QVariant, 9 >::operator[](), QVarLengthArray< QVariant, 9 >::realloc(), QPodList< QSockNot *, 32 >::removeAll(), QPodList< QSockNot *, 32 >::removeAt(), QPodList< QSockNot *, 32 >::takeFirst(), and QVarLengthArray< QVariant, 9 >::~QVarLengthArray().
q_for_alignment_1
template<class T, int Prealloc> qint64 QVarLengthArray< T, Prealloc >::q_for_alignment_1
Definition at line 178 of file qvarlengtharray.h.
q_for_alignment_2
template<class T, int Prealloc> double QVarLengthArray< T, Prealloc >::q_for_alignment_2
Definition at line 179 of file qvarlengtharray.h.
s
template<class T, int Prealloc> int QVarLengthArray< T, Prealloc >::s private
Definition at line 173 of file qvarlengtharray.h.
Referenced by QVarLengthArray< QVariant, 9 >::append(), QVarLengthArray< QVariant, 9 >::constEnd(), QVarLengthArray< QVariant, 9 >::count(), QVarLengthArray< QVariant, 9 >::end(), QVarLengthArray< QVariant, 9 >::erase(), QPodList< QSockNot *, 32 >::insert(), QVarLengthArray< QVariant, 9 >::insert(), QVarLengthArray< QVariant, 9 >::isEmpty(), QVarLengthArray< QVariant, 9 >::operator[](), QVarLengthArray< QVariant, 9 >::QVarLengthArray(), QVarLengthArray< QVariant, 9 >::realloc(), QPodList< QSockNot *, 32 >::removeAll(), QPodList< QSockNot *, 32 >::removeAt(), QVarLengthArray< QVariant, 9 >::removeLast(), QVarLengthArray< QVariant, 9 >::size(), QPodList< QSockNot *, 32 >::takeFirst(), and QVarLengthArray< QVariant, 9 >::~QVarLengthArray().
The documentation for this class was generated from the following files:
/src/corelib/tools/qcontainerfwd.h
/src/corelib/tools/qvarlengtharray.h