Qt 4.8: QPatternist::TagValidationHandler Class Reference
QPatternist::TagValidationHandler Class Reference
Public Functions
void finalize () const
TagValidationHandler (XsdTagScope::Type tag, XsdSchemaParser *parser, const NamePool::Ptr &namePool)
void validate (XsdSchemaToken::NodeName token)
Properties
XsdStateMachine< XsdSchemaToken::NodeName > m_machine
XsdSchemaParser * m_parser
Detailed Description
A helper class that checks for the right occurrence of xml tags with the help of a DFA.
Definition at line 149 of file qxsdschemaparser.cpp.
Constructors and Destructors
TagValidationHandler()
QPatternist::TagValidationHandler::TagValidationHandler (XsdTagScope::Type tag, XsdSchemaParser * parser, const NamePool::Ptr & namePool) inline
Definition at line 152 of file qxsdschemaparser.cpp.
             : m_parser(parser), m_machine(namePool)
         {
             Q_ASSERT(m_parser->m_stateMachines.contains(tag));
             m_machine = m_parser->m_stateMachines.value(tag);
             m_machine.reset();
         }
Functions
finalize()
void QPatternist::TagValidationHandler::finalize () const inline
Definition at line 190 of file qxsdschemaparser.cpp.
Referenced by QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAnnotation(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseOpenContent(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseReferredAttributeGroup(), QPatternist::XsdSchemaParser::parseReferredGroup(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnique(), and QPatternist::XsdSchemaParser::parseWhiteSpaceFacet().
         {
             if (!m_machine.inEndState()) {
                 const QList<XsdSchemaToken::NodeName> tokens = m_machine.possibleTransitions();
                 QStringList elementNames;
                 for (int i = 0; i < tokens.count(); ++i)
                     elementNames.append(formatElement(XsdSchemaToken::toString(tokens.at(i))));
                 m_parser->error(QtXmlPatterns::tr("Child element is missing in that scope, possible child elements are: %1.")
                                                  .arg(elementNames.join(QLatin1String(", "))));
             }
         }
validate()
void QPatternist::TagValidationHandler::validate (XsdSchemaToken::NodeName token) inline
Definition at line 161 of file qxsdschemaparser.cpp.
Referenced by QPatternist::XsdSchemaParser::parseAll(), QPatternist::XsdSchemaParser::parseAlternative(), QPatternist::XsdSchemaParser::parseAnnotation(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaParser::parseAssertion(), QPatternist::XsdSchemaParser::parseChoice(), QPatternist::XsdSchemaParser::parseComplexContent(), QPatternist::XsdSchemaParser::parseComplexContentExtension(), QPatternist::XsdSchemaParser::parseComplexContentRestriction(), QPatternist::XsdSchemaParser::parseDefaultOpenContent(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseField(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseGlobalAttribute(), QPatternist::XsdSchemaParser::parseGlobalComplexType(), QPatternist::XsdSchemaParser::parseGlobalElement(), QPatternist::XsdSchemaParser::parseGlobalSimpleType(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseKey(), QPatternist::XsdSchemaParser::parseKeyRef(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseList(), QPatternist::XsdSchemaParser::parseLocalAll(), QPatternist::XsdSchemaParser::parseLocalAttribute(), QPatternist::XsdSchemaParser::parseLocalChoice(), QPatternist::XsdSchemaParser::parseLocalComplexType(), QPatternist::XsdSchemaParser::parseLocalElement(), QPatternist::XsdSchemaParser::parseLocalSequence(), QPatternist::XsdSchemaParser::parseLocalSimpleType(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseNamedAttributeGroup(), QPatternist::XsdSchemaParser::parseNamedGroup(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parseOpenContent(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseRedefine(), QPatternist::XsdSchemaParser::parseReferredAttributeGroup(), QPatternist::XsdSchemaParser::parseReferredGroup(), QPatternist::XsdSchemaParser::parseSchema(), QPatternist::XsdSchemaParser::parseSelector(), QPatternist::XsdSchemaParser::parseSequence(), QPatternist::XsdSchemaParser::parseSimpleContent(), QPatternist::XsdSchemaParser::parseSimpleContentExtension(), QPatternist::XsdSchemaParser::parseSimpleContentRestriction(), QPatternist::XsdSchemaParser::parseSimpleRestriction(), QPatternist::XsdSchemaParser::parseTotalDigitsFacet(), QPatternist::XsdSchemaParser::parseUnion(), QPatternist::XsdSchemaParser::parseUnique(), and QPatternist::XsdSchemaParser::parseWhiteSpaceFacet().
         {
             if (token == XsdSchemaToken::NoKeyword) {
                 const QList<XsdSchemaToken::NodeName> tokens = m_machine.possibleTransitions();
                 QStringList elementNames;
                 for (int i = 0; i < tokens.count(); ++i)
                     elementNames.append(formatElement(XsdSchemaToken::toString(tokens.at(i))));
                 m_parser->error(QtXmlPatterns::tr("Can not process unknown element %1, expected elements are: %2.")
                                                  .arg(formatElement(m_parser->name().toString()))
                                                  .arg(elementNames.join(QLatin1String(", "))));
                 return;
             }
             if (!m_machine.proceed(token)) {
                 const QList<XsdSchemaToken::NodeName> tokens = m_machine.possibleTransitions();
                 QStringList elementNames;
                 for (int i = 0; i < tokens.count(); ++i)
                     elementNames.append(formatElement(XsdSchemaToken::toString(tokens.at(i))));
                 m_parser->error(QtXmlPatterns::tr("Element %1 is not allowed in this scope, possible elements are: %2.")
                                                  .arg(formatElement(XsdSchemaToken::toString(token)))
                                                  .arg(elementNames.join(QLatin1String(", "))));
                 return;
             }
         }
Properties
m_machine
XsdStateMachine<XsdSchemaToken::NodeName> QPatternist::TagValidationHandler::m_machine private
Definition at line 206 of file qxsdschemaparser.cpp.
m_parser
XsdSchemaParser* QPatternist::TagValidationHandler::m_parser private
Definition at line 205 of file qxsdschemaparser.cpp.
The documentation for this class was generated from the following file:
/src/xmlpatterns/schema/qxsdschemaparser.cpp