Qt 4.8: QPatternist::DerivedString< DerivedType > Class Template Reference
QPatternist::DerivedString< DerivedType > Class Template Reference
Represents instances of derived xs:string types, such as xs:normalizedString.
#include <qderivedstring_p.h>
Public Functions
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr fromLexical (const NamePool::Ptr &np, const QString &lexical)
static AtomicValue::Ptr fromValue (const QString &value)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Private Functions
DerivedString (const QString &value)
Static Private Functions
static QString attributeNormalize (const QString &input)
Performs attribute value normalization as if input was not from a CDATA section.
static AtomicValue::Ptr error (const NamePool::Ptr &np, const QString &invalidValue)
static bool isNameChar (const QChar &ch)
This is an incomplete test for whether ch conforms to the XML 1.0 NameChar production.
static bool isValidName (const QString &input)
static bool isValidNMTOKEN (const QString &input)
static ItemType::Ptr itemType ()
Properties
const QString m_value
Additional Inherited Members
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Detailed Description
template<TypeOfDerivedString DerivedType>
class QPatternist::DerivedString< DerivedType >
Represents instances of derived xs:string types, such as xs:normalizedString.
Whitespace is a significant part for creating values from the lexical space. Of course the specification is tricky here. Here's some pointers:
From XML Schema Part 2: Datatypes Second Edition, 4.3.6 whiteSpace: "For all atomic datatypes other than string (and types derived by restriction from it) the value of whiteSpace is collapse and cannot be changed by a schema author; for string the value of whiteSpace is preserve; for any type derived by restriction from string the value of whiteSpace can be any of the three legal values." - From <a href="http://www.w3.org/TR/xmlschema-1/#d0e1654">XML Schema Part 1: Structures Second Edition, 3.1.4 White Space Normalization during Validation: "[Definition:] The normalized value of an element or attribute information item is an initial value whose white space, if any, has been normalized according to the value of the whiteSpace facet of the simple type definition used in its validation."
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 95 of file qderivedstring_p.h.
Constructors and Destructors
DerivedString()
template<TypeOfDerivedString DerivedType> QPatternist::DerivedString< DerivedType >::DerivedString (const QString & value) inline private
Definition at line 120 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::fromLexical(), and QPatternist::DerivedString< TypeToken >::fromValue().
                                                    : m_value(value)
         {
         }
Functions
attributeNormalize()
template<TypeOfDerivedString DerivedType> static QString QPatternist::DerivedString< DerivedType >::attributeNormalize (const QString & input) inline static private
Performs attribute value normalization as if input was not from a CDATA section.
Each whitespace character in input that's not a space, such as tab or new line character, is replaced with a space. This algorithm differs from QString::simplified() in that it doesn't collapse subsequent whitespace characters to a single one, or remove trailing and leading space.
See also
Extensible Markup Language (XML) 1.0 (Second Edition), 3.3.3 [E70]Attribute-Value Normalization
Definition at line 209 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::fromLexical().
         {
             QString retval(input);
             const int len = retval.length();
             const QLatin1Char space(' ');
             for(int i = 0; i < len; ++i)
             {
                 const QChar ati(retval.at(i));
                 if(ati.isSpace() && ati != space)
                     retval[i] = space;
             }
             return retval;
         }
error()
template<TypeOfDerivedString DerivedType> static AtomicValue::Ptr QPatternist::DerivedString< DerivedType >::error (const NamePool::Ptr & np, const QString & invalidValue) inline static private
Definition at line 226 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::fromLexical().
         {
             return ValidationError::createError(QString::fromLatin1("%1 is not a valid value for "
                                                                     "type %2.").arg(formatData(invalidValue))
                                                                                .arg(formatType(np, itemType())));
         }
evaluateEBV()
template<TypeOfDerivedString DerivedType> virtual bool QPatternist::DerivedString< DerivedType >::evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > & context) const inline virtual
Always fails by issuing the type error ReportContext::FORG0006. Sub-classes whose represented type do allow EBV to be extracted from, must thus re-implement this function.
Reimplemented from QPatternist::AtomicValue.
Definition at line 325 of file qderivedstring_p.h.
         {
              return m_value.length() > 0;
         }
fromLexical()
template<TypeOfDerivedString DerivedType> static AtomicValue::Ptr QPatternist::DerivedString< DerivedType >::fromLexical (const NamePool::Ptr & np, const QString & lexical) inline static
Constructs an instance from the lexical representation lexical.
Definition at line 251 of file qderivedstring_p.h.
Referenced by QPatternist::ToStringCaster< DerivedType >::castFrom(), QPatternist::AnyToDerivedStringCaster< type >::castFrom(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDouble(), QPatternist::XsdTypeChecker::checkConstrainingFacetsDuration(), QPatternist::XsdTypeChecker::checkConstrainingFacetsSignedInteger(), QPatternist::XsdTypeChecker::checkConstrainingFacetsString(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnion(), QPatternist::XsdTypeChecker::checkConstrainingFacetsUnsignedInteger(), QPatternist::FieldNode::isEqualTo(), QPatternist::XsdSchemaParser::parseEnumerationFacet(), QPatternist::XsdSchemaParser::parseMaxExclusiveFacet(), QPatternist::XsdSchemaParser::parseMaxInclusiveFacet(), QPatternist::XsdSchemaParser::parseMinExclusiveFacet(), QPatternist::XsdSchemaParser::parseMinInclusiveFacet(), QPatternist::XsdSchemaParser::parseNotation(), QPatternist::XsdSchemaParser::parsePatternFacet(), QPatternist::XsdSchemaParser::parseWhiteSpaceFacet(), QPatternist::XsdSchemaParser::validateIdAttribute(), and QPatternist::XsdTypeChecker::valuesAreEqual().
         {
             switch(DerivedType)
             {
                 case TypeString:
                     return AtomicValue::Ptr(new DerivedString(lexical));
                 case TypeNormalizedString:
                     return AtomicValue::Ptr(new DerivedString(attributeNormalize(lexical)));
                 case TypeToken:
                     return AtomicValue::Ptr(new DerivedString(lexical.simplified()));
                 case TypeLanguage:
                 {
                     const QString simplified(lexical.trimmed());
                     const QRegExp validate(QLatin1String("[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*"));
                     Q_ASSERT(validate.isValid());
                     if(validate.exactMatch(simplified))
                         return AtomicValue::Ptr(new DerivedString(lexical.simplified()));
                     else
                         return error(np, simplified);
                 }
                 case TypeNMTOKEN:
                 {
                     const QString trimmed(lexical.trimmed());
                     if(isValidNMTOKEN(trimmed))
                         return AtomicValue::Ptr(new DerivedString(trimmed));
                     else
                         return error(np, trimmed);
                 }
                 case TypeName:
                 {
                     const QString simplified(lexical.simplified());
                     if(isValidName(simplified))
                         return AtomicValue::Ptr(new DerivedString(simplified));
                     else
                         return error(np, simplified);
                 }
                 case TypeID:
                 /* Fallthrough. */
                 case TypeIDREF:
                 /* Fallthrough. */
                 case TypeENTITY:
                 /* Fallthrough. */
                 case TypeNCName:
                 {
                     /* We treat xs:ID, xs:ENTITY, xs:IDREF and xs:NCName in the exact same
                      * way, except for the type annotation.
                      *
                      * We use trimmed() instead of simplified() because it's
                      * faster and whitespace isn't allowed between
                      * non-whitespace characters anyway, for these types. */
                     const QString trimmed(lexical.trimmed());
                     if(QXmlUtils::isNCName(trimmed))
                         return AtomicValue::Ptr(new DerivedString(trimmed));
                     else
                         return error(np, trimmed);
                 }
                 default:
                 {
                     Q_ASSERT_X(false, Q_FUNC_INFO, "This line is not supposed to be reached.");
                     return AtomicValue::Ptr();
                 }
             }
         }
fromValue()
template<TypeOfDerivedString DerivedType> static AtomicValue::Ptr QPatternist::DerivedString< DerivedType >::fromValue (const QString & value) inline static
Note
This function doesn't perform any cleanup/normalizaiton of value. value must be a canonical value space of the type.
If you want cleanup to be performed and/or the lexical space checked, use fromLexical().
Definition at line 242 of file qderivedstring_p.h.
         {
             return AtomicValue::Ptr(new DerivedString(value));
         }
isNameChar()
template<TypeOfDerivedString DerivedType> static bool QPatternist::DerivedString< DerivedType >::isNameChar (const QChar & ch) inline static private
This is an incomplete test for whether ch conforms to the XML 1.0 NameChar production.
Definition at line 128 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::isValidName(), and QPatternist::DerivedString< TypeToken >::isValidNMTOKEN().
         {
             return ch.isLetter()            ||
                    ch.isDigit()             ||
                    ch == QLatin1Char('.')   ||
                    ch == QLatin1Char('-')   ||
                    ch == QLatin1Char('_')   ||
                    ch == QLatin1Char(':');
         }
isValidName()
template<TypeOfDerivedString DerivedType> static bool QPatternist::DerivedString< DerivedType >::isValidName (const QString & input) inline static private
Returns
true if input is a valid xs:Name.
See also
Extensible Markup Language (XML) 1.0 (Fourth Edition), [5] Name
Definition at line 143 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::fromLexical().
         {
             if(input.isEmpty())
                 return false;
             const QChar first(input.at(0));
             if(first.isLetter()             ||
                first == QLatin1Char('_')    ||
                first == QLatin1Char(':'))
             {
                 const int len = input.length();
                 if(len == 1)
                     return true;
                 /* Since we've checked the first character above, we start at
                  * position 1. */
                 for(int i = 1; i < len; ++i)
                 {
                     if(!isNameChar(input.at(i)))
                         return false;
                 }
                 return true;
             }
             else
                 return false;
         }
isValidNMTOKEN()
template<TypeOfDerivedString DerivedType> static bool QPatternist::DerivedString< DerivedType >::isValidNMTOKEN (const QString & input) inline static private
Returns
true if input conforms to the XML 1.0 Nmtoken product.
See also
Extensible Markup Language (XML) 1.0 (Second Edition), [7] Nmtoken
Definition at line 180 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::fromLexical().
         {
             const int len = input.length();
             if(len == 0)
                 return false;
             for(int i = 0; i < len; ++i)
             {
                 if(!isNameChar(input.at(i)))
                     return false;
             }
             return true;
         }
itemType()
template<TypeOfDerivedString DerivedType> static ItemType::Ptr QPatternist::DerivedString< DerivedType >::itemType () inline static private
Definition at line 98 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::error(), and QPatternist::DerivedString< TypeToken >::type().
         {
             switch(DerivedType)
             {
                 case TypeNormalizedString:  return BuiltinTypes::xsNormalizedString;
                 case TypeToken:             return BuiltinTypes::xsToken;
                 case TypeLanguage:          return BuiltinTypes::xsLanguage;
                 case TypeNMTOKEN:           return BuiltinTypes::xsNMTOKEN;
                 case TypeName:              return BuiltinTypes::xsName;
                 case TypeNCName:            return BuiltinTypes::xsNCName;
                 case TypeID:                return BuiltinTypes::xsID;
                 case TypeIDREF:             return BuiltinTypes::xsIDREF;
                 case TypeENTITY:            return BuiltinTypes::xsENTITY;
                 case TypeString:            return BuiltinTypes::xsString;
             }
             Q_ASSERT_X(false, Q_FUNC_INFO, "This line is not supposed to be reached.");
             return ItemType::Ptr();
         }
stringValue()
template<TypeOfDerivedString DerivedType> virtual QString QPatternist::DerivedString< DerivedType >::stringValue () const inline virtual
Implements QPatternist::AtomicValue.
Definition at line 320 of file qderivedstring_p.h.
         {
             return m_value;
         }
type()
template<TypeOfDerivedString DerivedType> virtual ItemType::Ptr QPatternist::DerivedString< DerivedType >::type () const inline virtual
Implements QPatternist::AtomicValue.
Definition at line 330 of file qderivedstring_p.h.
         {
             return itemType();
         }
Properties
m_value
template<TypeOfDerivedString DerivedType> const QString QPatternist::DerivedString< DerivedType >::m_value private
Definition at line 118 of file qderivedstring_p.h.
Referenced by QPatternist::DerivedString< TypeToken >::stringValue().
The documentation for this class was generated from the following file:
/src/xmlpatterns/data/qderivedstring_p.h