Qt 4.8: QHeaderView Class Reference
QHeaderView Class Reference
The QHeaderView class provides a header row or header column for item views.
#include <qheaderview.h>
Public Types
enum ResizeMode {
Interactive, Stretch, Fixed, ResizeToContents,
Custom = Fixed
}
The resize mode specifies the behavior of the header sections.
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
void headerDataChanged (Qt::Orientation orientation, int logicalFirst, int logicalLast)
Updates the changed header sections with the given orientation, from logicalFirst to logicalLast inclusive.
void setOffset (int offset)
Sets the header's offset to offset.
void setOffsetToLastSection ()
Sets the offset to make the last section visible.
void setOffsetToSectionPosition (int visualIndex)
Sets the offset to the start of the section at the given visualIndex.
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
virtual void selectAll ()
Selects all items in the view.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
virtual void setRootIndex (const QModelIndex &index)
Sets the root item to the item at the given index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void geometriesChanged ()
This signal is emitted when the header's geometries have changed.
void sectionAutoResize (int logicalIndex, QHeaderView::ResizeMode mode)
void sectionClicked (int logicalIndex)
This signal is emitted when a section is clicked.
void sectionCountChanged (int oldCount, int newCount)
This signal is emitted when the number of sections changes, i.
void sectionDoubleClicked (int logicalIndex)
This signal is emitted when a section is double-clicked.
void sectionEntered (int logicalIndex)
This signal is emitted when the cursor moves over the section and the left mouse button is pressed.
void sectionHandleDoubleClicked (int logicalIndex)
This signal is emitted when a section is double-clicked.
void sectionMoved (int logicalIndex, int oldVisualIndex, int newVisualIndex)
This signal is emitted when a section is moved.
void sectionPressed (int logicalIndex)
This signal is emitted when a section is pressed.
void sectionResized (int logicalIndex, int oldSize, int newSize)
This signal is emitted when a section is resized.
void sortIndicatorChanged (int logicalIndex, Qt::SortOrder order)
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool cascadingSectionResizes () const
int count () const
Returns the number of sections in the header.
Qt::Alignment defaultAlignment () const
int defaultSectionSize () const
void doItemsLayout ()
int hiddenSectionCount () const
Returns the number of sections in the header that has been hidden.
void hideSection (int logicalIndex)
Hides the section specified by logicalIndex.
bool highlightSections () const
bool isClickable () const
Returns true if the header is clickable; otherwise returns false.
bool isMovable () const
Returns true if the header can be moved by the user; otherwise returns false.
bool isSectionHidden (int logicalIndex) const
Returns true if the section specified by logicalIndex is explicitly hidden from the user; otherwise returns false.
bool isSortIndicatorShown () const
int length () const
Returns the length along the orientation of the header.
int logicalIndex (int visualIndex) const
Returns the logicalIndex for the section at the given visualIndex position, or -1 if visualIndex < 0 or visualIndex >= QHeaderView::count().
int logicalIndexAt (int position) const
Returns the section that covers the given position in the viewport.
int logicalIndexAt (int x, int y) const
Returns the logical index of the section at the given coordinate.
int logicalIndexAt (const QPoint &pos) const
Returns the logical index of the section at the position given in pos.
int minimumSectionSize () const
void moveSection (int from, int to)
Moves the section at visual index from to occupy visual index to.
int offset () const
Returns the offset of the header: this is the header's left-most (or top-most for vertical headers) visible pixel.
Qt::Orientation orientation () const
Returns the orientation of the header.
QHeaderView (Qt::Orientation orientation, QWidget *parent=0)
Creates a new generic header with the given orientation and parent.
void reset ()
Reimplemented Function
ResizeMode resizeMode (int logicalIndex) const
Returns the resize mode that applies to the section specified by the given logicalIndex.
void resizeSection (int logicalIndex, int size)
Resizes the section specified by logicalIndex to size measured in pixels.
void resizeSections (QHeaderView::ResizeMode mode)
Resizes the sections according to the given mode, ignoring the current resize mode.
bool restoreState (const QByteArray &state)
Restores the state of this header view.
QByteArray saveState () const
Saves the current state of this header view.
int sectionPosition (int logicalIndex) const
Returns the section position of the given logicalIndex, or -1 if the section is hidden.
bool sectionsHidden () const
int sectionSize (int logicalIndex) const
Returns the width (or height for vertical headers) of the given logicalIndex.
int sectionSizeHint (int logicalIndex) const
Returns a suitable size hint for the section specified by logicalIndex.
bool sectionsMoved () const
Returns true if sections in the header has been moved; otherwise returns false;.
int sectionViewportPosition (int logicalIndex) const
Returns the section viewport position of the given logicalIndex.
void setCascadingSectionResizes (bool enable)
void setClickable (bool clickable)
If clickable is true, the header will respond to single clicks.
void setDefaultAlignment (Qt::Alignment alignment)
void setDefaultSectionSize (int size)
void setHighlightSections (bool highlight)
void setMinimumSectionSize (int size)
void setModel (QAbstractItemModel *model)
Reimplemented Function
void setMovable (bool movable)
If movable is true, the header may be moved by the user; otherwise it is fixed in place.
void setResizeMode (ResizeMode mode)
Sets the constraints on how the header can be resized to those described by the given mode.
void setResizeMode (int logicalIndex, ResizeMode mode)
Sets the constraints on how the section specified by logicalIndex in the header can be resized to those described by the given mode.
void setSectionHidden (int logicalIndex, bool hide)
If hide is true the section specified by logicalIndex is hidden; otherwise the section is shown.
void setSortIndicator (int logicalIndex, Qt::SortOrder order)
Sets the sort indicator for the section specified by the given logicalIndex in the direction specified by order, and removes the sort indicator from any other section that was showing it.
void setSortIndicatorShown (bool show)
void setStretchLastSection (bool stretch)
void showSection (int logicalIndex)
Shows the section specified by logicalIndex.
QSize sizeHint () const
Returns a suitable size hint for this header.
Qt::SortOrder sortIndicatorOrder () const
Returns the order for the sort indicator.
int sortIndicatorSection () const
Returns the logical index of the section that has a sort indicator.
bool stretchLastSection () const
int stretchSectionCount () const
Returns the number of sections that are set to resize mode stretch.
void swapSections (int first, int second)
Swaps the section at visual index first with the section at visual index second.
int visualIndex (int logicalIndex) const
Returns the visual index position of the section specified by the given logicalIndex, or -1 otherwise.
int visualIndexAt (int position) const
Returns the visual index of the section that covers the given position in the viewport.
virtual ~QHeaderView ()
Destroys the header.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
virtual void keyboardSearch (const QString &search)
Moves to and selects the item best matching the string search.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
virtual void setSelectionModel (QItemSelectionModel *selectionModel)
Sets the current selection model to the given selectionModel.
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
virtual int sizeHintForColumn (int column) const
Returns the width size hint for the specified column or -1 if there is no model.
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
virtual int sizeHintForRow (int row) const
Returns the height size hint for the specified row or -1 if there is no model.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Slots
void resizeSections ()
Resizes the sections according to their size hints.
void sectionsAboutToBeRemoved (const QModelIndex &parent, int logicalFirst, int logicalLast)
This slot is called when sections are removed from the parent.
void sectionsInserted (const QModelIndex &parent, int logicalFirst, int logicalLast)
This slot is called when sections are inserted into the parent.
void updateSection (int logicalIndex)
Updates the section specified by the given logicalIndex.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarAction (int action)
virtual void horizontalScrollbarValueChanged (int value)
virtual void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
This slot is called when rows are about to be removed.
virtual void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
This slot is called when the selection is changed.
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void verticalScrollbarAction (int action)
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Functions
void currentChanged (const QModelIndex &current, const QModelIndex &old)
Reimplemented Function
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
int horizontalOffset () const
Returns the horizontal offset of the header.
QModelIndex indexAt (const QPoint &p) const
Empty implementation because the header doesn't show QModelIndex items.
void initialize ()
void initializeSections ()
void initializeSections (int start, int end)
void initStyleOption (QStyleOptionHeader *option) const
Initialize option with the values from this QHeaderView.
bool isIndexHidden (const QModelIndex &index) const
Empty implementation because the header doesn't show QModelIndex items.
void mouseDoubleClickEvent (QMouseEvent *e)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
void mousePressEvent (QMouseEvent *e)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
QModelIndex moveCursor (CursorAction, Qt::KeyboardModifiers)
Empty implementation because the header doesn't show QModelIndex items.
void paintEvent (QPaintEvent *e)
Reimplemented Function
virtual void paintSection (QPainter *painter, const QRect &rect, int logicalIndex) const
Paints the section specified by the given logicalIndex, using the given painter and rect.
QHeaderView (QHeaderViewPrivate &dd, Qt::Orientation orientation, QWidget *parent=0)
void rowsInserted (const QModelIndex &parent, int start, int end)
Empty implementation because the header doesn't show QModelIndex items.
void scrollContentsBy (int dx, int dy)
Reimplemented Function
void scrollTo (const QModelIndex &index, ScrollHint hint)
Empty implementation because the header doesn't show QModelIndex items.
virtual QSize sectionSizeFromContents (int logicalIndex) const
Returns the size of the contents of the section specified by the given logicalIndex.
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags flags)
Selects the items in the given rect according to the specified flags.
void updateGeometries ()
Reimplemented Function
int verticalOffset () const
Returns the vertical offset of the header.
bool viewportEvent (QEvent *e)
Reimplemented Function
QRect visualRect (const QModelIndex &index) const
Empty implementation because the header doesn't show QModelIndex items.
QRegion visualRegionForSelection (const QItemSelection &selection) const
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
void dragLeaveEvent (QDragLeaveEvent *event)
This function is called when the item being dragged leaves the view.
void dragMoveEvent (QDragMoveEvent *event)
This function is called continuously with the given event during a drag and drop operation over the widget.
void dropEvent (QDropEvent *event)
This function is called with the given event when a drop event occurs over the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
This function is called with the given event when a key event is sent to the widget.
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
This function is called with the given event when a resize event is sent to the widget.
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QModelIndexList selectedIndexes () const
This convenience function returns a list of all selected and non-hidden item indexes in the view.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
virtual void startDrag (Qt::DropActions supportedActions)
Starts a drag by calling drag->exec() using the given supportedActions.
State state () const
Returns the item view's state.
void stopAutoScroll ()
void timerEvent (QTimerEvent *event)
This function is called with the given event when a timer event is sent to the widget.
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
virtual QStyleOptionViewItem viewOptions () const
Returns a QStyleOptionViewItem structure populated with the view's palette, font, state, alignments etc.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool cascadingSectionResizes
whether interactive resizing will be cascaded to the following sections once the section being resized by the user has reached its minimum size
Qt::Alignment defaultAlignment
the default alignment of the text in each header section
int defaultSectionSize
the default size of the header sections before resizing.
bool highlightSections
whether the sections containing selected items are highlighted
int minimumSectionSize
the minimum size of the header sections.
bool showSortIndicator
whether the sort indicator is shown
bool stretchLastSection
whether the last visible section in the header takes up all the available space
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QHeaderView class provides a header row or header column for item views.
A QHeaderView displays the headers used in item views such as the QTableView and QTreeView classes. It takes the place of Qt3's QHeader class previously used for the same purpose, but uses the Qt's model/view architecture for consistency with the item view classes.
The QHeaderView class is one of the Model/View Classes and is part of Qt's Model/View Programming{model/view framework}.
The header gets the data for each section from the model using the QAbstractItemModel::headerData() function. You can set the data by using QAbstractItemModel::setHeaderData().
Each header has an orientation() and a number of sections, given by the count() function. A section refers to a part of the header - either a row or a column, depending on the orientation.
Sections can be moved and resized using moveSection() and resizeSection(); they can also be hidden and shown with hideSection() and showSection().
Each section of a header is described by a section ID, specified by its section(), and can be located at a particular visualIndex() in the header. A section can have a sort indicator set with setSortIndicator(); this indicates whether the items in the associated item view will be sorted in the order given by the section.
For a horizontal header the section is equivalent to a column in the model, and for a vertical header the section is equivalent to a row in the model.
Moving Header Sections
A header can be fixed in place, or made movable with setMovable(). It can be made clickable with setClickable(), and has resizing behavior in accordance with setResizeMode().
Note
Double-clicking on a header to resize a section only applies for visible rows.
A header will emit sectionMoved() if the user moves a section, sectionResized() if the user resizes a section, and sectionClicked() as well as sectionHandleDoubleClicked() in response to mouse clicks. A header will also emit sectionCountChanged() and sectionAutoResize().
You can identify a section using the logicalIndex() and logicalIndexAt() functions, or by its index position, using the visualIndex() and visualIndexAt() functions. The visual index will change if a section is moved, but the logical index will not change.
Appearance
QTableWidget and QTableView create default headers. If you want the headers to be visible, you can use QFrame::setVisible().
Not all Qt::ItemDataRole will have an effect on a QHeaderView. If you need to draw other roles, you can subclass QHeaderView and reimplement QHeaderView::paintEvent(). QHeaderView respects the following item data roles: Qt::TextAlignmentRole, Qt::DisplayRole, Qt::FontRole, Qt::DecorationRole, Qt::ForegroundRole, and Qt::BackgroundRole.
Note
Each header renders the data for each section itself, and does not rely on a delegate. As a result, calling a header's setItemDelegate() function will have no effect.
See also
{Model/View Programming}, QListView, QTableView, QTreeView
Definition at line 58 of file qheaderview.h.
Enumerations
ResizeMode
enum QHeaderView::ResizeMode
The resize mode specifies the behavior of the header sections.
It can be set on the entire header view or on individual sections using setResizeMode().
Interactive The user can resize the section. The section can also be resized programmatically using resizeSection(). The section size defaults to defaultSectionSize . (See also cascadingSectionResizes .)
Fixed The user cannot resize the section. The section can only be resized programmatically using resizeSection(). The section size defaults to defaultSectionSize .
Stretch QHeaderView will automatically resize the section to fill the available space. The size cannot be changed by the user or programmatically.
ResizeToContents QHeaderView will automatically resize the section to its optimal size based on the contents of the entire column or row. The size cannot be changed by the user or programmatically. (This value was introduced in 4.2)
The following values are obsolete:
Custom Use Fixed instead.
See also
setResizeMode() stretchLastSection minimumSectionSize
Enumerator
Interactive
Stretch
Fixed
ResizeToContents
Custom
Definition at line 72 of file qheaderview.h.
     {
         Interactive,
         Stretch,
         Fixed,
         ResizeToContents,
         Custom = Fixed
     };
Constructors and Destructors
QHeaderView() [1/2]
QHeaderView::QHeaderView (Qt::Orientation orientation, QWidget * parent = 0) explicit
Creates a new generic header with the given orientation and parent.
Definition at line 355 of file qheaderview.cpp.
     : QAbstractItemView(*new QHeaderViewPrivate, parent)
 {
     Q_D(QHeaderView);
     d->setDefaultValues(orientation);
     initialize();
 }
~QHeaderView()
QHeaderView::~QHeaderView () virtual
Destroys the header.
Definition at line 379 of file qheaderview.cpp.
 {
 }
QHeaderView() [2/2]
QHeaderView::QHeaderView (QHeaderViewPrivate & dd, Qt::Orientation orientation, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 366 of file qheaderview.cpp.
     : QAbstractItemView(dd, parent)
 {
     Q_D(QHeaderView);
     d->setDefaultValues(orientation);
     initialize();
 }
Functions
cascadingSectionResizes()
bool QHeaderView::cascadingSectionResizes () const
Referenced by setStretchLastSection().
count()
int QHeaderView::count () const
Returns the number of sections in the header.
See also
sectionCountChanged(), length()
Definition at line 1098 of file qheaderview.cpp.
Referenced by QTreeViewPrivate::adjustViewOptionsForIndex(), QTreeViewPrivate::calcLogicalIndices(), QAccessibleHeader::childCount(), QTreeView::drawRow(), headerDataChanged(), QAccessibleItemRow::logicalFromChild(), QTreeView::moveCursor(), QTableView::paintEvent(), paintEvent(), paintSection(), resizeSection(), sectionsInserted(), sectionSize(), sectionSizeHint(), QTableViewPrivate::sectionSpanEndLogical(), sectionViewportPosition(), setResizeMode(), setSectionHidden(), setSortIndicatorShown(), setStretchLastSection(), sizeHint(), QTableViewPrivate::spanContainsSection(), QTreeViewPrivate::startAndEndColumns(), QTreeViewPrivate::updateScrollBars(), visualIndexAt(), and visualRegionForSelection().
 {
     Q_D(const QHeaderView);
     //Q_ASSERT(d->sectionCount == d->headerSectionCount());
     // ### this may affect the lazy layout
     d->executePostedLayout();
     return d->sectionCount;
 }
currentChanged()
void QHeaderView::currentChanged (const QModelIndex & current, const QModelIndex & old) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2102 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     if (d->orientation == Qt::Horizontal && current.column() != old.column()) {
         if (old.isValid() && old.parent() == d->root)
             d->viewport->update(QRect(sectionViewportPosition(old.column()), 0,
                                     sectionSize(old.column()), d->viewport->height()));
         if (current.isValid() && current.parent() == d->root)
             d->viewport->update(QRect(sectionViewportPosition(current.column()), 0,
                                     sectionSize(current.column()), d->viewport->height()));
     } else if (d->orientation == Qt::Vertical && current.row() != old.row()) {
         if (old.isValid() && old.parent() == d->root)
             d->viewport->update(QRect(0, sectionViewportPosition(old.row()),
                                     d->viewport->width(), sectionSize(old.row())));
         if (current.isValid() && current.parent() == d->root)
             d->viewport->update(QRect(0, sectionViewportPosition(current.row()),
                                     d->viewport->width(), sectionSize(current.row())));
     }
 }
dataChanged()
void QHeaderView::dataChanged (const QModelIndex & topLeft, const QModelIndex & bottomRight) protected virtual
Reimplemented Function
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 2761 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     d->invalidateCachedSizeHint();
     if (d->hasAutoResizeSections()) {
         bool resizeRequired = d->globalResizeMode == ResizeToContents;
         int first = orientation() == Qt::Horizontal ? topLeft.column() : topLeft.row();
         int last = orientation() == Qt::Horizontal ? bottomRight.column() : bottomRight.row();
         for (int i = first; i <= last && !resizeRequired; ++i)
             resizeRequired = (resizeMode(i) == ResizeToContents);
         if (resizeRequired)
             d->doDelayedResizeSections();
     }
 }
defaultAlignment()
Qt::Alignment QHeaderView::defaultAlignment () const
Referenced by QHeaderViewPrivate::read(), setMinimumSectionSize(), and QHeaderViewPrivate::write().
defaultSectionSize()
int QHeaderView::defaultSectionSize () const
Referenced by QHeaderViewPrivate::read(), setCascadingSectionResizes(), QHeaderViewPrivate::setDefaultSectionSize(), and QHeaderViewPrivate::write().
doItemsLayout()
void QHeaderView::doItemsLayout () virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 1567 of file qheaderview.cpp.
 {
     initializeSections();
     QAbstractItemView::doItemsLayout();
 }
event()
bool QHeaderView::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2128 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     switch (e->type()) {
     case QEvent::HoverEnter: {
         QHoverEvent *he = static_cast<QHoverEvent*>(e);
         d->hover = logicalIndexAt(he->pos());
         if (d->hover != -1)
             updateSection(d->hover);
         break; }
     case QEvent::Leave:
     case QEvent::HoverLeave: {
         if (d->hover != -1)
             updateSection(d->hover);
         d->hover = -1;
         break; }
     case QEvent::HoverMove: {
         QHoverEvent *he = static_cast<QHoverEvent*>(e);
         int oldHover = d->hover;
         d->hover = logicalIndexAt(he->pos());
         if (d->hover != oldHover) {
             if (oldHover != -1)
                 updateSection(oldHover);
             if (d->hover != -1)
                 updateSection(d->hover);
         }
         break; }
     case QEvent::Timer: {
         QTimerEvent *te = static_cast<QTimerEvent*>(e);
         if (te->timerId() == d->delayedResize.timerId()) {
             d->delayedResize.stop();
             resizeSections();
         }
         break; }
     default:
         break;
     }
     return QAbstractItemView::event(e);
 }
geometriesChanged
void QHeaderView::geometriesChanged () signal
This signal is emitted when the header's geometries have changed.
Since
4.2
Referenced by viewportEvent().
headerDataChanged
void QHeaderView::headerDataChanged (Qt::Orientation orientation, int logicalFirst, int logicalLast) slot
Updates the changed header sections with the given orientation, from logicalFirst to logicalLast inclusive.
Definition at line 1675 of file qheaderview.cpp.
Referenced by setModel().
 {
     Q_D(QHeaderView);
     if (d->orientation != orientation)
         return;
     if (logicalFirst < 0 || logicalLast < 0 || logicalFirst >= count() || logicalLast >= count())
         return;
     d->invalidateCachedSizeHint();
     int firstVisualIndex = INT_MAX, lastVisualIndex = -1;
     for (int section = logicalFirst; section <= logicalLast; ++section) {
         const int visual = visualIndex(section);
         firstVisualIndex = qMin(firstVisualIndex, visual);
         lastVisualIndex =  qMax(lastVisualIndex,  visual);
     }
     d->executePostedResize();
     const int first = d->headerSectionPosition(firstVisualIndex),
               last = d->headerSectionPosition(lastVisualIndex)
                         + d->headerSectionSize(lastVisualIndex);
     if (orientation == Qt::Horizontal) {
         d->viewport->update(first, 0, last - first, d->viewport->height());
     } else {
         d->viewport->update(0, first, d->viewport->width(), last - first);
     }
 }
hiddenSectionCount()
int QHeaderView::hiddenSectionCount () const
Returns the number of sections in the header that has been hidden.
Since
4.1
See also
setSectionHidden(), isSectionHidden()
Definition at line 1045 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     return d->hiddenSectionSize.count();
 }
hideSection()
void QHeaderView::hideSection (int logicalIndex) inline
Hides the section specified by logicalIndex.
See also
showSection(), isSectionHidden(), hiddenSectionCount(), setSectionHidden()
Definition at line 239 of file qheaderview.h.
 { setSectionHidden(alogicalIndex, true); }
highlightSections()
bool QHeaderView::highlightSections () const
Referenced by setHighlightSections().
horizontalOffset()
int QHeaderView::horizontalOffset () const protected virtual
Returns the horizontal offset of the header.
This is 0 for vertical headers.
See also
offset()
Implements QAbstractItemView.
Definition at line 2710 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     if (d->orientation == Qt::Horizontal)
         return d->offset;
     return 0;
 }
indexAt()
QModelIndex QHeaderView::indexAt (const QPoint & p) const protected virtual
Empty implementation because the header doesn't show QModelIndex items.
Reimplemented Function
Warning
This function is not part of the public interface.
Implements QAbstractItemView.
Definition at line 2830 of file qheaderview.cpp.
 {
     return QModelIndex();
 }
initialize()
void QHeaderView::initialize () protected
Warning
This function is not part of the public interface.
Definition at line 386 of file qheaderview.cpp.
Referenced by QHeaderView().
 {
     Q_D(QHeaderView);
     setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
     setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
     setFrameStyle(NoFrame);
     setFocusPolicy(Qt::NoFocus);
     d->viewport->setMouseTracking(true);
     d->viewport->setBackgroundRole(QPalette::Button);
     d->textElideMode = Qt::ElideNone;
     delete d->itemDelegate;
 }
initializeSections() [1/2]
void QHeaderView::initializeSections () protected
Warning
This function is not part of the public interface.
Definition at line 2004 of file qheaderview.cpp.
Referenced by doItemsLayout(), reset(), setModel(), and setResizeMode().
 {
     Q_D(QHeaderView);
     const int oldCount = d->sectionCount;
     const int newCount = d->modelSectionCount();
     if (newCount <= 0) {
             d->clear();
             emit sectionCountChanged(oldCount, 0);
     } else if (newCount != oldCount) {
         const int min = qBound(0, oldCount, newCount - 1);
         initializeSections(min, newCount - 1);
         if (stretchLastSection()) // we've already gotten the size hint
             d->lastSectionSize = sectionSize(logicalIndex(d->sectionCount - 1));
         //make sure we update the hidden sections
         if (newCount < oldCount)
             d->updateHiddenSections(0, newCount-1);
     }
 }
initializeSections() [2/2]
void QHeaderView::initializeSections (int start, int end) protected
Warning
This function is not part of the public interface.
Definition at line 2028 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     Q_ASSERT(start >= 0);
     Q_ASSERT(end >= 0);
     d->invalidateCachedSizeHint();
     if (end + 1 < d->sectionCount) {
         int newCount = end + 1;
         d->removeSectionsFromSpans(newCount, d->sectionCount);
         if (!d->hiddenSectionSize.isEmpty()) {
             if (d->sectionCount - newCount > d->hiddenSectionSize.count()) {
                 for (int i = end + 1; i < d->sectionCount; ++i)
                     d->hiddenSectionSize.remove(i);
             } else {
                 QHash<int, int>::iterator it = d->hiddenSectionSize.begin();
                 while (it != d->hiddenSectionSize.end()) {
                     if (it.key() > end)
                         it = d->hiddenSectionSize.erase(it);
                     else
                         ++it;
                 }
             }
         }
     }
     int oldCount = d->sectionCount;
     d->sectionCount = end + 1;
     if (!d->logicalIndices.isEmpty()) {
         if (oldCount <= d->sectionCount) {
             d->logicalIndices.resize(d->sectionCount);
             d->visualIndices.resize(d->sectionCount);
             for (int i = oldCount; i < d->sectionCount; ++i) {
                 d->logicalIndices[i] = i;
                 d->visualIndices[i] = i;
             }
         } else {
             int j = 0;
             for (int i = 0; i < oldCount; ++i) {
                 int v = d->logicalIndices.at(i);
                 if (v < d->sectionCount) {
                     d->logicalIndices[j] = v;
                     d->visualIndices[v] = j;
                     j++;
                 }
             }
             d->logicalIndices.resize(d->sectionCount);
             d->visualIndices.resize(d->sectionCount);
         }
     }
     if (d->globalResizeMode == Stretch)
         d->stretchSections = d->sectionCount;
     else if (d->globalResizeMode == ResizeToContents)
          d->contentsSections = d->sectionCount;
     if (!d->sectionHidden.isEmpty())
         d->sectionHidden.resize(d->sectionCount);
     if (d->sectionCount > oldCount)
         d->createSectionSpan(start, end, (end - start + 1) * d->defaultSectionSize, d->globalResizeMode);
     //Q_ASSERT(d->headerLength() == d->length);
     if (d->sectionCount != oldCount)
         emit sectionCountChanged(oldCount,  d->sectionCount);
     d->viewport->update();
 }
initStyleOption()
void QHeaderView::initStyleOption (QStyleOptionHeader * option) const protected
Initialize option with the values from this QHeaderView.
This method is useful for subclasses when they need a QStyleOptionHeader, but do not want to fill in all the information themselves.
See also
QStyleOption::initFrom()
Definition at line 3046 of file qheaderview.cpp.
Referenced by paintSection(), and sectionSizeFromContents().
 {
     Q_D(const QHeaderView);
     option->initFrom(this);
     option->state = QStyle::State_None | QStyle::State_Raised;
     option->orientation = d->orientation;
     if (d->orientation == Qt::Horizontal)
         option->state |= QStyle::State_Horizontal;
     if (isEnabled())
         option->state |= QStyle::State_Enabled;
     option->section = 0;
 }
isClickable()
bool QHeaderView::isClickable () const
Returns true if the header is clickable; otherwise returns false.
A clickable header could be set up to allow the user to change the representation of the data in the view related to the header.
See also
setClickable()
Definition at line 1201 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     return d->clickableSections;
 }
isIndexHidden()
bool QHeaderView::isIndexHidden (const QModelIndex & index) const protected virtual
Empty implementation because the header doesn't show QModelIndex items.
Reimplemented Function
Warning
This function is not part of the public interface.
Implements QAbstractItemView.
Definition at line 2845 of file qheaderview.cpp.
 {
     return true; // the header view has no items, just sections
 }
isMovable()
bool QHeaderView::isMovable () const
Returns true if the header can be moved by the user; otherwise returns false.
See also
setMovable()
Definition at line 1172 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     return d->movableSections;
 }
isSectionHidden()
bool QHeaderView::isSectionHidden (int logicalIndex) const
Returns true if the section specified by logicalIndex is explicitly hidden from the user; otherwise returns false.
See also
hideSection(), showSection(), setSectionHidden(), hiddenSectionCount()
Definition at line 1024 of file qheaderview.cpp.
Referenced by QTreeViewPrivate::adjustViewOptionsForIndex(), QTreeViewPrivate::calcLogicalIndices(), QTreeViewPrivate::columnRanges(), QTableViewPrivate::isColumnHidden(), QTableViewPrivate::isRowHidden(), QAccessibleItemRow::logicalFromChild(), QTableView::paintEvent(), resizeSection(), QFileDialog::restoreState(), sectionsInserted(), sectionSize(), sectionSizeHint(), and sizeHint().
 {
     Q_D(const QHeaderView);
     d->executePostedLayout();
     if (logicalIndex >= d->sectionHidden.count() || logicalIndex < 0 || logicalIndex >= d->sectionCount)
         return false;
     int visual = visualIndex(logicalIndex);
     Q_ASSERT(visual != -1);
     return d->sectionHidden.testBit(visual);
 }
isSortIndicatorShown()
bool QHeaderView::isSortIndicatorShown () const
Definition at line 1341 of file qheaderview.cpp.
Referenced by paintSection(), and sectionSizeFromContents().
 {
     Q_D(const QHeaderView);
     return d->sortIndicatorShown;
 }
length()
int QHeaderView::length () const
Returns the length along the orientation of the header.
See also
sizeHint(), setResizeMode(), offset()
Definition at line 560 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate::clear(), QHeaderViewPrivate::createSectionSpan(), QTreeView::drawRow(), QTableView::paintEvent(), QHeaderViewPrivate::read(), QHeaderViewPrivate::removeSectionsFromSpans(), QHeaderViewPrivate::setDefaultSectionSize(), setOffsetToLastSection(), QTreeViewPrivate::updateScrollBars(), and QHeaderViewPrivate::write().
 {
     Q_D(const QHeaderView);
     d->executePostedLayout();
     d->executePostedResize();
     //Q_ASSERT(d->headerLength() == d->length);
     return d->length;
 }
logicalIndex()
int QHeaderView::logicalIndex (int visualIndex) const
Returns the logicalIndex for the section at the given visualIndex position, or -1 if visualIndex < 0 or visualIndex >= QHeaderView::count().
Note that the visualIndex is not affected by hidden sections.
See also
visualIndex(), sectionPosition()
Definition at line 1142 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate::_q_layoutAboutToBeChanged(), QHeaderViewPrivate::_q_sectionsRemoved(), QTreeViewPrivate::adjustViewOptionsForIndex(), QTreeViewPrivate::calcLogicalIndices(), QTreeViewPrivate::columnRanges(), QTreeView::drawRow(), initializeSections(), logicalIndexAt(), moveSection(), QTableView::paintEvent(), paintEvent(), paintSection(), QHeaderViewPrivate::resizeSections(), QHeaderViewPrivate::resizeSectionSpan(), QHeaderViewPrivate::sectionHandleAt(), sectionSizeFromContents(), QTableViewPrivate::sectionSpanEndLogical(), QHeaderViewPrivate::setDefaultSectionSize(), setSortIndicator(), QTableViewPrivate::spanContainsSection(), QHeaderViewPrivate::updateHiddenSections(), QTreeViewPrivate::updateScrollBars(), visualIndex(), QTreeWidget::visualItemRect(), and visualRegionForSelection().
 {
     Q_D(const QHeaderView);
     if (visualIndex < 0 || visualIndex >= d->sectionCount)
         return -1;
     return d->logicalIndex(visualIndex);
 }
logicalIndexAt() [1/3]
int QHeaderView::logicalIndexAt (int position) const
Returns the section that covers the given position in the viewport.
See also
visualIndexAt(), isSectionHidden()
Definition at line 669 of file qheaderview.cpp.
Referenced by QTreeViewPrivate::columnAt(), event(), QTreeViewPrivate::itemDecorationAt(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), QTableViewPrivate::selectColumn(), QTableViewPrivate::selectRow(), viewportEvent(), and QTreeWidget::visualItemRect().
 {
     const int visual = visualIndexAt(position);
     if (visual > -1)
         return logicalIndex(visual);
     return -1;
 }
logicalIndexAt() [2/3]
int QHeaderView::logicalIndexAt (int x, int y) const inline
Returns the logical index of the section at the given coordinate.
If the header is horizontal x will be used, otherwise y will be used to find the logical index.
Definition at line 235 of file qheaderview.h.
 { return orientation() == Qt::Horizontal ? logicalIndexAt(ax) : logicalIndexAt(ay); }
logicalIndexAt() [3/3]
int QHeaderView::logicalIndexAt (const QPoint & pos) const inline
Returns the logical index of the section at the position given in pos.
If the header is horizontal the x-coordinate will be used, otherwise the y-coordinate will be used to find the logical index.
See also
sectionPosition()
Definition at line 237 of file qheaderview.h.
 { return logicalIndexAt(apos.x(), apos.y()); }
minimumSectionSize()
int QHeaderView::minimumSectionSize () const
Referenced by mouseMoveEvent(), QHeaderViewPrivate::read(), sectionSizeHint(), setDefaultSectionSize(), and QHeaderViewPrivate::write().
mouseDoubleClickEvent()
void QHeaderView::mouseDoubleClickEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2453 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     int pos = d->orientation == Qt::Horizontal ? e->x() : e->y();
     int handle = d->sectionHandleAt(pos);
     if (handle > -1 && resizeMode(handle) == Interactive) {
         emit sectionHandleDoubleClicked(handle);
 #ifndef QT_NO_CURSOR
         Qt::CursorShape splitCursor = (d->orientation == Qt::Horizontal)
                                       ? Qt::SplitHCursor : Qt::SplitVCursor;
         if (cursor().shape() == splitCursor) {
             // signal handlers may have changed the section size
             handle = d->sectionHandleAt(pos);
             if (!(handle > -1 && resizeMode(handle) == Interactive))
                 setCursor(Qt::ArrowCursor);
         }
 #endif
     } else {
         emit sectionDoubleClicked(logicalIndexAt(e->pos()));
     }
 }
mouseMoveEvent()
void QHeaderView::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2314 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     int pos = d->orientation == Qt::Horizontal ? e->x() : e->y();
     if (pos < 0)
         return;
     if (e->buttons() == Qt::NoButton) {
 #if !defined(Q_WS_MAC)
         // Under Cocoa, when the mouse button is released, may include an extra
         // simulated mouse moved event. The state of the buttons when this event
         // is generated is already "no button" and the code below gets executed
         // just before the mouseReleaseEvent and resets the state. This prevents
         // column dragging from working. So this code is disabled under Cocoa.
         d->state = QHeaderViewPrivate::NoState;
         d->pressed = -1;
 #endif
     }
     switch (d->state) {
         case QHeaderViewPrivate::ResizeSection: {
             Q_ASSERT(d->originalSize != -1);
             if (d->cascadingResizing) {
                 int delta = d->reverse() ? d->lastPos - pos : pos - d->lastPos;
                 int visual = visualIndex(d->section);
                 d->cascadingResize(visual, d->headerSectionSize(visual) + delta);
             } else {
                 int delta = d->reverse() ? d->firstPos - pos : pos - d->firstPos;
                 resizeSection(d->section, qMax(d->originalSize + delta, minimumSectionSize()));
             }
             d->lastPos = pos;
             return;
         }
         case QHeaderViewPrivate::MoveSection: {
             if (qAbs(pos - d->firstPos) >= QApplication::startDragDistance()
                 || !d->sectionIndicator->isHidden()) {
                 int visual = visualIndexAt(pos);
                 if (visual == -1)
                     return;
                 int posThreshold = d->headerSectionPosition(visual) - d->offset + d->headerSectionSize(visual) / 2;
                 int moving = visualIndex(d->section);
                 if (visual < moving) {
                     if (pos < posThreshold)
                         d->target = d->logicalIndex(visual);
                     else
                         d->target = d->logicalIndex(visual + 1);
                 } else if (visual > moving) {
                     if (pos > posThreshold)
                         d->target = d->logicalIndex(visual);
                     else
                         d->target = d->logicalIndex(visual - 1);
                 } else {
                     d->target = d->section;
                 }
                 d->updateSectionIndicator(d->section, pos);
             }
             return;
         }
         case QHeaderViewPrivate::SelectSections: {
             int logical = logicalIndexAt(pos);
             if (logical == d->pressed)
                 return; // nothing to do
             else if (d->pressed != -1)
                 updateSection(d->pressed);
             d->pressed = logical;
             if (d->clickableSections && logical != -1) {
                 emit sectionEntered(d->pressed);
                 updateSection(d->pressed);
             }
             return;
         }
         case QHeaderViewPrivate::NoState: {
 #ifndef QT_NO_CURSOR
             int handle = d->sectionHandleAt(pos);
             bool hasCursor = testAttribute(Qt::WA_SetCursor);
             if (handle != -1 && (resizeMode(handle) == Interactive)) {
                 if (!hasCursor)
                     setCursor(d->orientation == Qt::Horizontal ? Qt::SplitHCursor : Qt::SplitVCursor);
             } else if (hasCursor) {
                 unsetCursor();
             }
 #endif
             return;
         }
         default:
             break;
     }
 }
mousePressEvent()
void QHeaderView::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2276 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     if (d->state != QHeaderViewPrivate::NoState || e->button() != Qt::LeftButton)
         return;
     int pos = d->orientation == Qt::Horizontal ? e->x() : e->y();
     int handle = d->sectionHandleAt(pos);
     d->originalSize = -1; // clear the stored original size
     if (handle == -1) {
         d->pressed = logicalIndexAt(pos);
         if (d->clickableSections)
             emit sectionPressed(d->pressed);
         if (d->movableSections) {
             d->section = d->target = d->pressed;
             if (d->section == -1)
                 return;
             d->state = QHeaderViewPrivate::MoveSection;
             d->setupSectionIndicator(d->section, pos);
         } else if (d->clickableSections && d->pressed != -1) {
             updateSection(d->pressed);
             d->state = QHeaderViewPrivate::SelectSections;
         }
     } else if (resizeMode(handle) == Interactive) {
         d->originalSize = sectionSize(handle);
         d->state = QHeaderViewPrivate::ResizeSection;
         d->section = handle;
     }
     d->firstPos = pos;
     d->lastPos = pos;
     d->clearCascadingSections();
 }
mouseReleaseEvent()
void QHeaderView::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2405 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     int pos = d->orientation == Qt::Horizontal ? e->x() : e->y();
     switch (d->state) {
     case QHeaderViewPrivate::MoveSection:
         if (!d->sectionIndicator->isHidden()) { // moving
             int from = visualIndex(d->section);
             Q_ASSERT(from != -1);
             int to = visualIndex(d->target);
             Q_ASSERT(to != -1);
             moveSection(from, to);
             d->section = d->target = -1;
             d->updateSectionIndicator(d->section, pos);
             break;
         } // not moving
     case QHeaderViewPrivate::SelectSections:
         if (!d->clickableSections) {
             int section = logicalIndexAt(pos);
             updateSection(section);
         }
         // fall through
     case QHeaderViewPrivate::NoState:
         if (d->clickableSections) {
             int section = logicalIndexAt(pos);
             if (section != -1 && section == d->pressed) {
                 d->flipSortIndicator(section);
                 emit sectionClicked(section);
             }
             if (d->pressed != -1)
                 updateSection(d->pressed);
         }
         break;
     case QHeaderViewPrivate::ResizeSection:
         d->originalSize = -1;
         d->clearCascadingSections();
         break;
     default:
         break;
     }
     d->state = QHeaderViewPrivate::NoState;
     d->pressed = -1;
 }
moveCursor()
QModelIndex QHeaderView::moveCursor (CursorAction , Qt::KeyboardModifiers) protected virtual
Empty implementation because the header doesn't show QModelIndex items.
Reimplemented Function
Warning
This function is not part of the public interface.
Implements QAbstractItemView.
Definition at line 2860 of file qheaderview.cpp.
 {
     return QModelIndex();
 }
moveSection()
void QHeaderView::moveSection (int from, int to)
Moves the section at visual index from to occupy visual index to.
See also
sectionsMoved()
Definition at line 773 of file qheaderview.cpp.
Referenced by mouseReleaseEvent().
 {
     Q_D(QHeaderView);
     d->executePostedLayout();
     if (from < 0 || from >= d->sectionCount || to < 0 || to >= d->sectionCount)
         return;
     if (from == to) {
         int logical = logicalIndex(from);
         Q_ASSERT(logical != -1);
         updateSection(logical);
         return;
     }
     if (stretchLastSection() &&  to == d->lastVisibleVisualIndex())
         d->lastSectionSize = sectionSize(from);
     //int oldHeaderLength = length(); // ### for debugging; remove later
     d->initializeIndexMapping();
     QBitArray sectionHidden = d->sectionHidden;
     int *visualIndices = d->visualIndices.data();
     int *logicalIndices = d->logicalIndices.data();
     int logical = logicalIndices[from];
     int visual = from;
     int affected_count = qAbs(to - from) + 1;
     QVarLengthArray<int> sizes(affected_count);
     QVarLengthArray<ResizeMode> modes(affected_count);
     // move sections and indices
     if (to > from) {
         sizes[to - from] = d->headerSectionSize(from);
         modes[to - from] = d->headerSectionResizeMode(from);
         while (visual < to) {
             sizes[visual - from] = d->headerSectionSize(visual + 1);
             modes[visual - from] = d->headerSectionResizeMode(visual + 1);
             if (!sectionHidden.isEmpty())
                 sectionHidden.setBit(visual, sectionHidden.testBit(visual + 1));
             visualIndices[logicalIndices[visual + 1]] = visual;
             logicalIndices[visual] = logicalIndices[visual + 1];
             ++visual;
         }
     } else {
         sizes[0] = d->headerSectionSize(from);
         modes[0] = d->headerSectionResizeMode(from);
         while (visual > to) {
             sizes[visual - to] = d->headerSectionSize(visual - 1);
             modes[visual - to] = d->headerSectionResizeMode(visual - 1);
             if (!sectionHidden.isEmpty())
                 sectionHidden.setBit(visual, sectionHidden.testBit(visual - 1));
             visualIndices[logicalIndices[visual - 1]] = visual;
             logicalIndices[visual] = logicalIndices[visual - 1];
             --visual;
         }
     }
     if (!sectionHidden.isEmpty()) {
         sectionHidden.setBit(to, d->sectionHidden.testBit(from));
         d->sectionHidden = sectionHidden;
     }
     visualIndices[logical] = to;
     logicalIndices[to] = logical;
     //Q_ASSERT(oldHeaderLength == length());
     // move sizes
     // ### check for spans of section sizes here
     if (to > from) {
         for (visual = from; visual <= to; ++visual) {
             int size = sizes[visual - from];
             ResizeMode mode = modes[visual - from];
             d->createSectionSpan(visual, visual, size, mode);
         }
     } else {
         for (visual = to; visual <= from; ++visual) {
             int size = sizes[visual - to];
             ResizeMode mode = modes[visual - to];
             d->createSectionSpan(visual, visual, size, mode);
         }
     }
     //Q_ASSERT(d->headerLength() == length());
     //Q_ASSERT(oldHeaderLength == length());
     //Q_ASSERT(d->logicalIndices.count() == d->sectionCount);
     if (d->hasAutoResizeSections())
         d->doDelayedResizeSections();
     d->viewport->update();
     emit sectionMoved(logical, from, to);
 }
offset()
int QHeaderView::offset () const
Returns the offset of the header: this is the header's left-most (or top-most for vertical headers) visible pixel.
See also
setOffset()
Definition at line 480 of file qheaderview.cpp.
Referenced by QTreeView::drawRow(), QTableView::paintEvent(), and paintEvent().
 {
     Q_D(const QHeaderView);
     return d->offset;
 }
orientation()
Qt::Orientation QHeaderView::orientation () const
Returns the orientation of the header.
See also
Qt::Orientation
Definition at line 467 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate::_q_layoutAboutToBeChanged(), QHeaderViewPrivate::_q_layoutChanged(), dataChanged(), QHeaderViewPrivate::flipSortIndicator(), QHeaderViewPrivate::isSectionSelected(), QHeaderViewPrivate::read(), QAccessibleHeader::rect(), QHeaderViewPrivate::resizeSections(), QHeaderViewPrivate::setupSectionIndicator(), QHeaderViewPrivate::updateSectionIndicator(), QHeaderViewPrivate::viewSectionSizeHint(), and QHeaderViewPrivate::write().
 {
     Q_D(const QHeaderView);
     return d->orientation;
 }
paintEvent()
void QHeaderView::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2172 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     if (count() == 0)
         return;
     QPainter painter(d->viewport);
     const QPoint offset = d->scrollDelayOffset;
     QRect translatedEventRect = e->rect();
     translatedEventRect.translate(offset);
     int start = -1;
     int end = -1;
     if (d->orientation == Qt::Horizontal) {
         start = visualIndexAt(translatedEventRect.left());
         end = visualIndexAt(translatedEventRect.right());
     } else {
         start = visualIndexAt(translatedEventRect.top());
         end = visualIndexAt(translatedEventRect.bottom());
     }
     if (d->reverse()) {
         start = (start == -1 ? count() - 1 : start);
         end = (end == -1 ? 0 : end);
     } else {
         start = (start == -1 ? 0 : start);
         end = (end == -1 ? count() - 1 : end);
     }
     int tmp = start;
     start = qMin(start, end);
     end = qMax(tmp, end);
     d->prepareSectionSelected(); // clear and resize the bit array
     QRect currentSectionRect;
     int logical;
     const int width = d->viewport->width();
     const int height = d->viewport->height();
     for (int i = start; i <= end; ++i) {
         if (d->isVisualIndexHidden(i))
             continue;
         painter.save();
         logical = logicalIndex(i);
         if (d->orientation == Qt::Horizontal) {
             currentSectionRect.setRect(sectionViewportPosition(logical), 0, sectionSize(logical), height);
         } else {
             currentSectionRect.setRect(0, sectionViewportPosition(logical), width, sectionSize(logical));
         }
         currentSectionRect.translate(offset);
         QVariant variant = d->model->headerData(logical, d->orientation,
                                                 Qt::FontRole);
         if (variant.isValid() && variant.canConvert<QFont>()) {
             QFont sectionFont = qvariant_cast<QFont>(variant);
             painter.setFont(sectionFont);
         }
         paintSection(&painter, currentSectionRect, logical);
         painter.restore();
     }
     QStyleOption opt;
     opt.init(this);
     // Paint the area beyond where there are indexes
     if (d->reverse()) {
         opt.state |= QStyle::State_Horizontal;
         if (currentSectionRect.left() > translatedEventRect.left()) {
             opt.rect = QRect(translatedEventRect.left(), 0,
                              currentSectionRect.left() - translatedEventRect.left(), height);
             style()->drawControl(QStyle::CE_HeaderEmptyArea, &opt, &painter, this);
         }
     } else if (currentSectionRect.right() < translatedEventRect.right()) {
         // paint to the right
         opt.state |= QStyle::State_Horizontal;
         opt.rect = QRect(currentSectionRect.right() + 1, 0,
                          translatedEventRect.right() - currentSectionRect.right(), height);
         style()->drawControl(QStyle::CE_HeaderEmptyArea, &opt, &painter, this);
     } else if (currentSectionRect.bottom() < translatedEventRect.bottom()) {
         // paint the bottom section
         opt.state &= ~QStyle::State_Horizontal;
         opt.rect = QRect(0, currentSectionRect.bottom() + 1,
                          width, height - currentSectionRect.bottom() - 1);
         style()->drawControl(QStyle::CE_HeaderEmptyArea, &opt, &painter, this);
     }
 #if 0
     // ### visualize section spans
     for (int a = 0, i = 0; i < d->sectionSpans.count(); ++i) {
         QColor color((i & 4 ? 255 : 0), (i & 2 ? 255 : 0), (i & 1 ? 255 : 0));
         if (d->orientation == Qt::Horizontal)
             painter.fillRect(a - d->offset, 0, d->sectionSpans.at(i).size, 4, color);
         else
             painter.fillRect(0, a - d->offset, 4, d->sectionSpans.at(i).size, color);
         a += d->sectionSpans.at(i).size;
     }
 #endif
 }
paintSection()
void QHeaderView::paintSection (QPainter * painter, const QRect & rect, int logicalIndex) const protected virtual
Paints the section specified by the given logicalIndex, using the given painter and rect.
Normally, you do not have to call this function.
Definition at line 2560 of file qheaderview.cpp.
Referenced by paintEvent().
 {
     Q_D(const QHeaderView);
     if (!rect.isValid())
         return;
     // get the state of the section
     QStyleOptionHeader opt;
     initStyleOption(&opt);
     QStyle::State state = QStyle::State_None;
     if (isEnabled())
         state |= QStyle::State_Enabled;
     if (window()->isActiveWindow())
         state |= QStyle::State_Active;
     if (d->clickableSections) {
         if (logicalIndex == d->hover)
             state |= QStyle::State_MouseOver;
         if (logicalIndex == d->pressed)
             state |= QStyle::State_Sunken;
         else if (d->highlightSelected) {
             if (d->sectionIntersectsSelection(logicalIndex))
                 state |= QStyle::State_On;
             if (d->isSectionSelected(logicalIndex))
                 state |= QStyle::State_Sunken;
         }
     }
     if (isSortIndicatorShown() && sortIndicatorSection() == logicalIndex)
         opt.sortIndicator = (sortIndicatorOrder() == Qt::AscendingOrder)
                             ? QStyleOptionHeader::SortDown : QStyleOptionHeader::SortUp;
     // setup the style options structure
     QVariant textAlignment = d->model->headerData(logicalIndex, d->orientation,
                                                   Qt::TextAlignmentRole);
     opt.rect = rect;
     opt.section = logicalIndex;
     opt.state |= state;
     opt.textAlignment = Qt::Alignment(textAlignment.isValid()
                                       ? Qt::Alignment(textAlignment.toInt())
                                       : d->defaultAlignment);
     opt.iconAlignment = Qt::AlignVCenter;
     opt.text = d->model->headerData(logicalIndex, d->orientation,
                                     Qt::DisplayRole).toString();
     if (d->textElideMode != Qt::ElideNone)
         opt.text = opt.fontMetrics.elidedText(opt.text, d->textElideMode , rect.width() - 4);
     QVariant variant = d->model->headerData(logicalIndex, d->orientation,
                                     Qt::DecorationRole);
     opt.icon = qvariant_cast<QIcon>(variant);
     if (opt.icon.isNull())
         opt.icon = qvariant_cast<QPixmap>(variant);
     QVariant foregroundBrush = d->model->headerData(logicalIndex, d->orientation,
                                                     Qt::ForegroundRole);
     if (foregroundBrush.canConvert<QBrush>())
         opt.palette.setBrush(QPalette::ButtonText, qvariant_cast<QBrush>(foregroundBrush));
     QPointF oldBO = painter->brushOrigin();
     QVariant backgroundBrush = d->model->headerData(logicalIndex, d->orientation,
                                                     Qt::BackgroundRole);
     if (backgroundBrush.canConvert<QBrush>()) {
         opt.palette.setBrush(QPalette::Button, qvariant_cast<QBrush>(backgroundBrush));
         opt.palette.setBrush(QPalette::Window, qvariant_cast<QBrush>(backgroundBrush));
         painter->setBrushOrigin(opt.rect.topLeft());
     }
     // the section position
     int visual = visualIndex(logicalIndex);
     Q_ASSERT(visual != -1);
     if (count() == 1)
         opt.position = QStyleOptionHeader::OnlyOneSection;
     else if (visual == 0)
         opt.position = QStyleOptionHeader::Beginning;
     else if (visual == count() - 1)
         opt.position = QStyleOptionHeader::End;
     else
         opt.position = QStyleOptionHeader::Middle;
     opt.orientation = d->orientation;
     // the selected position
     bool previousSelected = d->isSectionSelected(this->logicalIndex(visual - 1));
     bool nextSelected =  d->isSectionSelected(this->logicalIndex(visual + 1));
     if (previousSelected && nextSelected)
         opt.selectedPosition = QStyleOptionHeader::NextAndPreviousAreSelected;
     else if (previousSelected)
         opt.selectedPosition = QStyleOptionHeader::PreviousIsSelected;
     else if (nextSelected)
         opt.selectedPosition = QStyleOptionHeader::NextIsSelected;
     else
         opt.selectedPosition = QStyleOptionHeader::NotAdjacent;
     // draw the section
     style()->drawControl(QStyle::CE_Header, &opt, painter, this);
     painter->setBrushOrigin(oldBO);
 }
reset()
void QHeaderView::reset () virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 1662 of file qheaderview.cpp.
 {
     QAbstractItemView::reset();
     // it would be correct to call clear, but some apps rely
     // on the header keeping the sections, even after calling reset
     //d->clear();
     initializeSections();
 }
resizeMode()
QHeaderView::ResizeMode QHeaderView::resizeMode (int logicalIndex) const
Returns the resize mode that applies to the section specified by the given logicalIndex.
See also
setResizeMode()
Definition at line 1284 of file qheaderview.cpp.
Referenced by dataChanged(), mouseDoubleClickEvent(), mouseMoveEvent(), mousePressEvent(), QHeaderViewPrivate::resizeSections(), QHeaderViewPrivate::setGlobalHeaderResizeMode(), and setSortIndicator().
 {
     Q_D(const QHeaderView);
     int visual = visualIndex(logicalIndex);
     if (visual == -1)
         return Fixed; //the default value
     return d->headerSectionResizeMode(visual);
 }
resizeSection()
void QHeaderView::resizeSection (int logicalIndex, int size)
Resizes the section specified by logicalIndex to size measured in pixels.
See also
sectionResized(), resizeMode(), sectionSize()
Definition at line 927 of file qheaderview.cpp.
Referenced by QFileDialogPrivate::createWidgets(), mouseMoveEvent(), setSectionHidden(), and setStretchLastSection().
 {
     Q_D(QHeaderView);
     if (logical < 0 || logical >= count())
         return;
     if (isSectionHidden(logical)) {
         d->hiddenSectionSize.insert(logical, size);
         return;
     }
     int visual = visualIndex(logical);
     if (visual == -1)
         return;
     int oldSize = d->headerSectionSize(visual);
     if (oldSize == size)
         return;
     d->executePostedLayout();
     d->invalidateCachedSizeHint();
     if (stretchLastSection() && visual == d->lastVisibleVisualIndex())
         d->lastSectionSize = size;
     if (size != oldSize)
         d->createSectionSpan(visual, visual, size, d->headerSectionResizeMode(visual));
     if (!updatesEnabled()) {
         if (d->hasAutoResizeSections())
             d->doDelayedResizeSections();
         emit sectionResized(logical, oldSize, size);
         return;
     }
     int w = d->viewport->width();
     int h = d->viewport->height();
     int pos = sectionViewportPosition(logical);
     QRect r;
     if (d->orientation == Qt::Horizontal)
         if (isRightToLeft())
             r.setRect(0, 0, pos + size, h);
         else
             r.setRect(pos, 0, w - pos, h);
     else
         r.setRect(0, pos, w, h - pos);
     if (d->hasAutoResizeSections()) {
         d->doDelayedResizeSections();
         r = d->viewport->rect();
     }
     d->viewport->update(r.normalized());
     emit sectionResized(logical, oldSize, size);
 }
resizeSections() [1/2]
void QHeaderView::resizeSections (QHeaderView::ResizeMode mode)
Resizes the sections according to the given mode, ignoring the current resize mode.
See also
resizeMode(), sectionResized()
Definition at line 989 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     d->resizeSections(mode, true);
 }
resizeSections [2/2]
void QHeaderView::resizeSections () protected slot
Resizes the sections according to their size hints.
Normally, you do not have to call this function.
Definition at line 1732 of file qheaderview.cpp.
Referenced by event(), setSortIndicator(), setSortIndicatorShown(), setStretchLastSection(), and viewportEvent().
 {
     Q_D(QHeaderView);
     if (d->hasAutoResizeSections())
         d->resizeSections(Interactive, false); // no global resize mode
 }
restoreState()
bool QHeaderView::restoreState (const QByteArray & state)
Restores the state of this header view.
Since
4.3
This function returns true if the state was restored; otherwise returns false.
See also
saveState()
Definition at line 1634 of file qheaderview.cpp.
Referenced by QFileDialog::restoreState().
 {
     Q_D(QHeaderView);
     if (state.isEmpty())
         return false;
     QByteArray data = state;
     QDataStream stream(&data, QIODevice::ReadOnly);
     int marker;
     int ver;
     stream >> marker;
     stream >> ver;
     if (stream.status() != QDataStream::Ok
         || marker != QHeaderViewPrivate::VersionMarker
         || ver != 0) // current version is 0
         return false;
     if (d->read(stream)) {
         emit sortIndicatorChanged(d->sortIndicatorSection, d->sortIndicatorOrder );
         d->viewport->update();
         return true;
     }
     return false;
 }
rowsInserted()
void QHeaderView::rowsInserted (const QModelIndex & parent, int start, int end) protected virtual
Empty implementation because the header doesn't show QModelIndex items.
Reimplemented Function
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 2785 of file qheaderview.cpp.
Referenced by setModel().
 {
     // do nothing
 }
saveState()
QByteArray QHeaderView::saveState () const
Saves the current state of this header view.
Since
4.3
To restore the saved state, pass the return value to restoreState().
See also
restoreState()
Definition at line 1612 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     QByteArray data;
     QDataStream stream(&data, QIODevice::WriteOnly);
     stream << QHeaderViewPrivate::VersionMarker;
     stream << 0; // current version is 0
     d->write(stream);
     return data;
 }
scrollContentsBy()
void QHeaderView::scrollContentsBy (int dx, int dy) protected virtual
Reimplemented Function
Warning
This function is not part of the public interface.
Reimplemented from QAbstractScrollArea.
Definition at line 2751 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     d->scrollDirtyRegion(dx, dy);
 }
scrollTo()
void QHeaderView::scrollTo (const QModelIndex & index, ScrollHint hint) protected virtual
Empty implementation because the header doesn't show QModelIndex items.
Reimplemented Function
Warning
This function is not part of the public interface.
Implements QAbstractItemView.
Definition at line 2815 of file qheaderview.cpp.
 {
     // do nothing - the header only displays sections
 }
sectionAutoResize
void QHeaderView::sectionAutoResize (int logicalIndex, QHeaderView::ResizeMode mode) signal
sectionClicked
void QHeaderView::sectionClicked (int logicalIndex) signal
This signal is emitted when a section is clicked.
The section's logical index is specified by logicalIndex.
Note that the sectionPressed signal will also be emitted.
See also
setClickable(), sectionPressed()
Referenced by mouseReleaseEvent().
sectionCountChanged
void QHeaderView::sectionCountChanged (int oldCount, int newCount) signal
This signal is emitted when the number of sections changes, i.
e., when sections are added or deleted. The original count is specified by oldCount, and the new count by newCount.
See also
count(), length(), headerDataChanged()
Referenced by QHeaderViewPrivate::_q_layoutChanged(), initializeSections(), and sectionsInserted().
sectionDoubleClicked
void QHeaderView::sectionDoubleClicked (int logicalIndex) signal
This signal is emitted when a section is double-clicked.
The section's logical index is specified by logicalIndex.
See also
setClickable()
Referenced by mouseDoubleClickEvent().
sectionEntered
void QHeaderView::sectionEntered (int logicalIndex) signal
This signal is emitted when the cursor moves over the section and the left mouse button is pressed.
Since
4.3
The section's logical index is specified by logicalIndex.
See also
setClickable(), sectionPressed()
Referenced by mouseMoveEvent().
sectionHandleDoubleClicked
void QHeaderView::sectionHandleDoubleClicked (int logicalIndex) signal
This signal is emitted when a section is double-clicked.
The section's logical index is specified by logicalIndex.
See also
setClickable()
Referenced by mouseDoubleClickEvent().
sectionMoved
void QHeaderView::sectionMoved (int logicalIndex, int oldVisualIndex, int newVisualIndex) signal
This signal is emitted when a section is moved.
The section's logical index is specified by logicalIndex, the old index by oldVisualIndex, and the new index position by newVisualIndex.
See also
moveSection()
Referenced by moveSection(), and swapSections().
sectionPosition()
int QHeaderView::sectionPosition (int logicalIndex) const
Returns the section position of the given logicalIndex, or -1 if the section is hidden.
The position is measured in pixels from the first visible item's top-left corner to the top-left corner of the item with logicalIndex. The measurement is along the x-axis for horizontal headers and along the y-axis for vertical headers.
See also
sectionViewportPosition()
Definition at line 709 of file qheaderview.cpp.
Referenced by QTreeView::drawRow(), QAccessibleHeader::rect(), QAccessibleTable2HeaderCell::rect(), QTableViewPrivate::sectionSpanSize(), and sectionViewportPosition().
 {
     Q_D(const QHeaderView);
     int visual = visualIndex(logicalIndex);
     // in some cases users may change the selections
     // before we have a chance to do the layout
     if (visual == -1)
         return -1;
     d->executePostedResize();
     return d->headerSectionPosition(visual);
 }
sectionPressed
void QHeaderView::sectionPressed (int logicalIndex) signal
This signal is emitted when a section is pressed.
The section's logical index is specified by logicalIndex.
See also
setClickable()
Referenced by mousePressEvent().
sectionResized
void QHeaderView::sectionResized (int logicalIndex, int oldSize, int newSize) signal
This signal is emitted when a section is resized.
The section's logical number is specified by logicalIndex, the old size by oldSize, and the new size by newSize.
See also
resizeSection()
Referenced by QHeaderViewPrivate::cascadingResize(), and resizeSection().
sectionsAboutToBeRemoved
void QHeaderView::sectionsAboutToBeRemoved (const QModelIndex & parent, int logicalFirst, int logicalLast) protected slot
This slot is called when sections are removed from the parent.
logicalFirst and logicalLast signify where the sections were removed.
If only one section is removed, logicalFirst and logicalLast will be the same.
Definition at line 1852 of file qheaderview.cpp.
Referenced by setModel().
 {
     Q_UNUSED(parent);
     Q_UNUSED(logicalFirst);
     Q_UNUSED(logicalLast);
 }
sectionsHidden()
bool QHeaderView::sectionsHidden () const
Since
4.1
Returns true if sections in the header has been hidden; otherwise returns false;
See also
setSectionHidden()
Definition at line 1593 of file qheaderview.cpp.
Referenced by QAccessibleItemRow::logicalFromChild(), and QTableView::paintEvent().
 {
     Q_D(const QHeaderView);
     return !d->hiddenSectionSize.isEmpty();
 }
sectionsInserted
void QHeaderView::sectionsInserted (const QModelIndex & parent, int logicalFirst, int logicalLast) protected slot
This slot is called when sections are inserted into the parent.
logicalFirst and logicalLast indices signify where the new sections were inserted.
If only one section is inserted, logicalFirst and logicalLast will be the same.
Definition at line 1748 of file qheaderview.cpp.
Referenced by setModel().
 {
     Q_D(QHeaderView);
     if (parent != d->root)
         return; // we only handle changes in the top level
     int oldCount = d->sectionCount;
     d->invalidateCachedSizeHint();
     // add the new sections
     int insertAt = 0;
     for (int spanStart = 0; insertAt < d->sectionSpans.count() && spanStart < logicalFirst; ++insertAt)
         spanStart += d->sectionSpans.at(insertAt).count;
     int insertCount = logicalLast - logicalFirst + 1;
     d->sectionCount += insertCount;
     if (d->sectionSpans.isEmpty() || insertAt >= d->sectionSpans.count()) {
         int insertLength = d->defaultSectionSize * insertCount;
         d->length += insertLength;
         QHeaderViewPrivate::SectionSpan span(insertLength, insertCount, d->globalResizeMode);
         d->sectionSpans.append(span);
     } else if ((d->sectionSpans.at(insertAt).sectionSize() == d->defaultSectionSize)
                && d->sectionSpans.at(insertAt).resizeMode == d->globalResizeMode) {
         // add the new sections to an existing span
         int insertLength = d->sectionSpans.at(insertAt).sectionSize() * insertCount;
         d->length += insertLength;
         d->sectionSpans[insertAt].size += insertLength;
         d->sectionSpans[insertAt].count += insertCount;
     } else {
         // separate them out into their own span
         int insertLength = d->defaultSectionSize * insertCount;
         d->length += insertLength;
         QHeaderViewPrivate::SectionSpan span(insertLength, insertCount, d->globalResizeMode);
         d->sectionSpans.insert(insertAt, span);
     }
     // update sorting column
     if (d->sortIndicatorSection >= logicalFirst)
         d->sortIndicatorSection += insertCount;
     // update resize mode section counts
     if (d->globalResizeMode == Stretch)
         d->stretchSections = d->sectionCount;
     else if (d->globalResizeMode == ResizeToContents)
         d->contentsSections = d->sectionCount;
     // clear selection cache
     d->sectionSelected.clear();
     // update mapping
     if (!d->visualIndices.isEmpty() && !d->logicalIndices.isEmpty()) {
         Q_ASSERT(d->visualIndices.count() == d->logicalIndices.count());
         int mappingCount = d->visualIndices.count();
         for (int i = 0; i < mappingCount; ++i) {
             if (d->visualIndices.at(i) >= logicalFirst)
                d->visualIndices[i] += insertCount;
             if (d->logicalIndices.at(i) >= logicalFirst)
                 d->logicalIndices[i] += insertCount;
         }
         for (int j = logicalFirst; j <= logicalLast; ++j) {
             d->visualIndices.insert(j, j);
             d->logicalIndices.insert(j, j);
         }
     }
     // insert sections into sectionsHidden
     if (!d->sectionHidden.isEmpty()) {
         QBitArray sectionHidden(d->sectionHidden);
         sectionHidden.resize(sectionHidden.count() + insertCount);
         sectionHidden.fill(false, logicalFirst, logicalLast + 1);
         for (int j = logicalLast + 1; j < sectionHidden.count(); ++j)
             //here we simply copy the old sectionHidden
             sectionHidden.setBit(j, d->sectionHidden.testBit(j - insertCount));
         d->sectionHidden = sectionHidden;
     }
     // insert sections into hiddenSectionSize
     QHash<int, int> newHiddenSectionSize; // from logical index to section size
     for (int i = 0; i < logicalFirst; ++i)
         if (isSectionHidden(i))
             newHiddenSectionSize[i] = d->hiddenSectionSize[i];
     for (int j = logicalLast + 1; j < d->sectionCount; ++j)
         if (isSectionHidden(j))
             newHiddenSectionSize[j] = d->hiddenSectionSize[j - insertCount];
     d->hiddenSectionSize = newHiddenSectionSize;
     d->doDelayedResizeSections();
     emit sectionCountChanged(oldCount, count());
     // if the new sections were not updated by resizing, we need to update now
     if (!d->hasAutoResizeSections())
         d->viewport->update();
 }
sectionSize()
int QHeaderView::sectionSize (int logicalIndex) const
Returns the width (or height for vertical headers) of the given logicalIndex.
See also
length(), setResizeMode(), defaultSectionSize()
Definition at line 684 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate::cascadingResize(), currentChanged(), QTreeView::drawRow(), initializeSections(), QTreeViewPrivate::itemDecorationRect(), mousePressEvent(), moveSection(), QTableView::paintEvent(), paintEvent(), QAccessibleHeader::rect(), QAccessibleTable2HeaderCell::rect(), QHeaderViewPrivate::resizeSections(), QTableViewPrivate::sectionSpanSize(), sectionViewportPosition(), QTreeViewPrivate::updateScrollBars(), updateSection(), and visualRegionForSelection().
 {
     Q_D(const QHeaderView);
     if (isSectionHidden(logicalIndex))
         return 0;
     if (logicalIndex < 0 || logicalIndex >= count())
         return 0;
     int visual = visualIndex(logicalIndex);
     if (visual == -1)
         return 0;
     d->executePostedResize();
     return d->headerSectionSize(visual);
 }
sectionSizeFromContents()
QSize QHeaderView::sectionSizeFromContents (int logicalIndex) const protected virtual
Returns the size of the contents of the section specified by the given logicalIndex.
See also
defaultSectionSize()
Definition at line 2661 of file qheaderview.cpp.
Referenced by sectionSizeHint(), and sizeHint().
 {
     Q_D(const QHeaderView);
     Q_ASSERT(logicalIndex >= 0);
     ensurePolished();
     // use SizeHintRole
     QVariant variant = d->model->headerData(logicalIndex, d->orientation, Qt::SizeHintRole);
     if (variant.isValid())
         return qvariant_cast<QSize>(variant);
     // otherwise use the contents
     QStyleOptionHeader opt;
     initStyleOption(&opt);
     opt.section = logicalIndex;
     QVariant var = d->model->headerData(logicalIndex, d->orientation,
                                             Qt::FontRole);
     QFont fnt;
     if (var.isValid() && var.canConvert<QFont>())
         fnt = qvariant_cast<QFont>(var);
     else
         fnt = font();
     fnt.setBold(true);
     opt.fontMetrics = QFontMetrics(fnt);
     opt.text = d->model->headerData(logicalIndex, d->orientation,
                                     Qt::DisplayRole).toString();
     variant = d->model->headerData(logicalIndex, d->orientation, Qt::DecorationRole);
     opt.icon = qvariant_cast<QIcon>(variant);
     if (opt.icon.isNull())
         opt.icon = qvariant_cast<QPixmap>(variant);
     QSize size = style()->sizeFromContents(QStyle::CT_HeaderSection, &opt, QSize(), this);
     if (isSortIndicatorShown()) {
         int margin = style()->pixelMetric(QStyle::PM_HeaderMargin, &opt, this);
         if (d->orientation == Qt::Horizontal)
             size.rwidth() += size.height() + margin;
         else
             size.rheight() += size.width() + margin;
     }
     return size;
 }
sectionSizeHint()
int QHeaderView::sectionSizeHint (int logicalIndex) const
Returns a suitable size hint for the section specified by logicalIndex.
See also
sizeHint(), defaultSectionSize(), minimumSectionSize(), Qt::SizeHintRole
Definition at line 611 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     if (isSectionHidden(logicalIndex))
         return 0;
     if (logicalIndex < 0 || logicalIndex >= count())
         return -1;
     QSize size;
     QVariant value = d->model->headerData(logicalIndex, d->orientation, Qt::SizeHintRole);
     if (value.isValid())
         size = qvariant_cast<QSize>(value);
     else
         size = sectionSizeFromContents(logicalIndex);
     int hint = d->orientation == Qt::Horizontal ? size.width() : size.height();
     return qMax(minimumSectionSize(), hint);
 }
sectionsMoved()
bool QHeaderView::sectionsMoved () const
Returns true if sections in the header has been moved; otherwise returns false;.
See also
moveSection()
Definition at line 1579 of file qheaderview.cpp.
Referenced by QTreeView::drawRow(), QTableViewPrivate::selectColumn(), QTableViewPrivate::selectRow(), QTableView::setSelection(), and QTableView::visualRegionForSelection().
 {
     Q_D(const QHeaderView);
     return !d->visualIndices.isEmpty();
 }
sectionViewportPosition()
int QHeaderView::sectionViewportPosition (int logicalIndex) const
Returns the section viewport position of the given logicalIndex.
If the section is hidden, the return value is undefined.
See also
sectionPosition(), isSectionHidden()
Definition at line 729 of file qheaderview.cpp.
Referenced by currentChanged(), QTreeViewPrivate::itemDecorationRect(), paintEvent(), resizeSection(), updateSection(), and visualRegionForSelection().
 {
     Q_D(const QHeaderView);
     if (logicalIndex >= count())
         return -1;
     int position = sectionPosition(logicalIndex);
     if (position < 0)
         return position; // the section was hidden
     int offsetPosition = position - d->offset;
     if (d->reverse())
         return d->viewport->width() - (offsetPosition + sectionSize(logicalIndex));
     return offsetPosition;
 }
setCascadingSectionResizes()
void QHeaderView::setCascadingSectionResizes (bool enable)
Definition at line 1473 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     d->cascadingResizing = enable;
 }
setClickable()
void QHeaderView::setClickable (bool clickable)
If clickable is true, the header will respond to single clicks.
See also
isClickable(), sectionClicked(), sectionPressed(), setSortIndicatorShown()
Definition at line 1186 of file qheaderview.cpp.
Referenced by QTableViewPrivate::init(), QTreeWidget::QTreeWidget(), and QTreeView::setSortingEnabled().
 {
     Q_D(QHeaderView);
     d->clickableSections = clickable;
 }
setDefaultAlignment()
void QHeaderView::setDefaultAlignment (Qt::Alignment alignment)
Definition at line 1554 of file qheaderview.cpp.
Referenced by QTreeViewPrivate::initialize().
 {
     Q_D(QHeaderView);
     if (d->defaultAlignment == alignment)
         return;
     d->defaultAlignment = alignment;
     d->viewport->update();
 }
setDefaultSectionSize()
void QHeaderView::setDefaultSectionSize (int size)
Definition at line 1497 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     d->setDefaultSectionSize(size);
 }
setHighlightSections()
void QHeaderView::setHighlightSections (bool highlight)
Definition at line 1207 of file qheaderview.cpp.
Referenced by QTableViewPrivate::init().
 {
     Q_D(QHeaderView);
     d->highlightSelected = highlight;
 }
setMinimumSectionSize()
void QHeaderView::setMinimumSectionSize (int size)
Definition at line 1533 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     d->minimumSectionSize = size;
 }
setModel()
void QHeaderView::setModel (QAbstractItemModel * model) virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 402 of file qheaderview.cpp.
 {
     if (model == this->model())
         return;
     Q_D(QHeaderView);
     if (d->model && d->model != QAbstractItemModelPrivate::staticEmptyModel()) {
     if (d->orientation == Qt::Horizontal) {
         QObject::disconnect(d->model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                             this, SLOT(sectionsInserted(QModelIndex,int,int)));
         QObject::disconnect(d->model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
                             this, SLOT(sectionsAboutToBeRemoved(QModelIndex,int,int)));
         QObject::disconnect(d->model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                             this, SLOT(_q_sectionsRemoved(QModelIndex,int,int)));
     } else {
         QObject::disconnect(d->model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                             this, SLOT(sectionsInserted(QModelIndex,int,int)));
         QObject::disconnect(d->model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                             this, SLOT(sectionsAboutToBeRemoved(QModelIndex,int,int)));
         QObject::disconnect(d->model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                             this, SLOT(_q_sectionsRemoved(QModelIndex,int,int)));
     }
     QObject::disconnect(d->model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                         this, SLOT(headerDataChanged(Qt::Orientation,int,int)));
         QObject::disconnect(d->model, SIGNAL(layoutAboutToBeChanged()),
                             this, SLOT(_q_layoutAboutToBeChanged()));
     }
     if (model && model != QAbstractItemModelPrivate::staticEmptyModel()) {
         if (d->orientation == Qt::Horizontal) {
             QObject::connect(model, SIGNAL(columnsInserted(QModelIndex,int,int)),
                              this, SLOT(sectionsInserted(QModelIndex,int,int)));
             QObject::connect(model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
                 this, SLOT(sectionsAboutToBeRemoved(QModelIndex,int,int)));
             QObject::connect(model, SIGNAL(columnsRemoved(QModelIndex,int,int)),
                 this, SLOT(_q_sectionsRemoved(QModelIndex,int,int)));
         } else {
             QObject::connect(model, SIGNAL(rowsInserted(QModelIndex,int,int)),
                              this, SLOT(sectionsInserted(QModelIndex,int,int)));
             QObject::connect(model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                              this, SLOT(sectionsAboutToBeRemoved(QModelIndex,int,int)));
             QObject::connect(model, SIGNAL(rowsRemoved(QModelIndex,int,int)),
                              this, SLOT(_q_sectionsRemoved(QModelIndex,int,int)));
         }
         QObject::connect(model, SIGNAL(headerDataChanged(Qt::Orientation,int,int)),
                          this, SLOT(headerDataChanged(Qt::Orientation,int,int)));
         QObject::connect(model, SIGNAL(layoutAboutToBeChanged()),
                          this, SLOT(_q_layoutAboutToBeChanged()));
     }
     d->state = QHeaderViewPrivate::NoClear;
     QAbstractItemView::setModel(model);
     d->state = QHeaderViewPrivate::NoState;
     // Users want to set sizes and modes before the widget is shown.
     // Thus, we have to initialize when the model is set,
     // and not lazily like we do in the other views.
     initializeSections();
 }
setMovable()
void QHeaderView::setMovable (bool movable)
If movable is true, the header may be moved by the user; otherwise it is fixed in place.
See also
isMovable(), sectionMoved()
Definition at line 1158 of file qheaderview.cpp.
Referenced by QTreeViewPrivate::initialize().
 {
     Q_D(QHeaderView);
     d->movableSections = movable;
 }
setOffset
void QHeaderView::setOffset (int offset) slot
Sets the header's offset to offset.
See also
offset(), length()
Definition at line 497 of file qheaderview.cpp.
Referenced by setOffsetToLastSection(), and setOffsetToSectionPosition().
 {
     Q_D(QHeaderView);
     if (d->offset == (int)newOffset)
         return;
     int ndelta = d->offset - newOffset;
     d->offset = newOffset;
     if (d->orientation == Qt::Horizontal)
         d->viewport->scroll(isRightToLeft() ? -ndelta : ndelta, 0);
     else
         d->viewport->scroll(0, ndelta);
     if (d->state == QHeaderViewPrivate::ResizeSection) {
         QPoint cursorPos = QCursor::pos();
         if (d->orientation == Qt::Horizontal)
             QCursor::setPos(cursorPos.x() + ndelta, cursorPos.y());
         else
             QCursor::setPos(cursorPos.x(), cursorPos.y() + ndelta);
         d->firstPos += ndelta;
         d->lastPos += ndelta;
     }
 }
setOffsetToLastSection
void QHeaderView::setOffsetToLastSection () slot
Sets the offset to make the last section visible.
Since
4.2
See also
setOffset(), sectionPosition(), setOffsetToSectionPosition()
Definition at line 546 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     int size = (d->orientation == Qt::Horizontal ? viewport()->width() : viewport()->height());
     int position = length() - size;
     setOffset(position);
 }
setOffsetToSectionPosition
void QHeaderView::setOffsetToSectionPosition (int visualIndex) slot
Sets the offset to the start of the section at the given visualIndex.
Since
4.2
See also
setOffset(), sectionPosition()
Definition at line 528 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     if (visualIndex > -1 && visualIndex < d->sectionCount) {
         int position = d->headerSectionPosition(d->adjustedVisualIndex(visualIndex));
         setOffset(position);
     }
 }
setResizeMode() [1/2]
void QHeaderView::setResizeMode (ResizeMode mode)
Sets the constraints on how the header can be resized to those described by the given mode.
See also
resizeMode(), length(), sectionResized(), sectionAutoResize()
Definition at line 1226 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     initializeSections();
     d->stretchSections = (mode == Stretch ? count() : 0);
     d->contentsSections =  (mode == ResizeToContents ? count() : 0);
     d->setGlobalHeaderResizeMode(mode);
     if (d->hasAutoResizeSections())
         d->doDelayedResizeSections(); // section sizes may change as a result of the new mode
 }
setResizeMode() [2/2]
void QHeaderView::setResizeMode (int logicalIndex, ResizeMode mode)
Sets the constraints on how the section specified by logicalIndex in the header can be resized to those described by the given mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The logical index should exist at the time this function is called.
Note
This setting will be ignored for the last section if the stretchLastSection property is set to true. This is the default for the horizontal headers provided by QTreeView.
See also
setStretchLastSection()
Definition at line 1255 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     int visual = visualIndex(logicalIndex);
     Q_ASSERT(visual != -1);
     ResizeMode old = d->headerSectionResizeMode(visual);
     d->setHeaderSectionResizeMode(visual, mode);
     if (mode == Stretch && old != Stretch)
         ++d->stretchSections;
     else if (mode == ResizeToContents && old != ResizeToContents)
         ++d->contentsSections;
     else if (mode != Stretch && old == Stretch)
         --d->stretchSections;
     else if (mode != ResizeToContents && old == ResizeToContents)
         --d->contentsSections;
     if (d->hasAutoResizeSections() && d->state == QHeaderViewPrivate::NoState)
         d->doDelayedResizeSections(); // section sizes may change as a result of the new mode
 }
setSectionHidden()
void QHeaderView::setSectionHidden (int logicalIndex, bool hide)
If hide is true the section specified by logicalIndex is hidden; otherwise the section is shown.
See also
isSectionHidden(), hiddenSectionCount()
Definition at line 1058 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     if (logicalIndex < 0 || logicalIndex >= count())
         return;
     d->executePostedLayout();
     int visual = visualIndex(logicalIndex);
     Q_ASSERT(visual != -1);
     if (hide == d->isVisualIndexHidden(visual))
         return;
     if (hide) {
         int size = d->headerSectionSize(visual);
         if (!d->hasAutoResizeSections())
             resizeSection(logicalIndex, 0);
         d->hiddenSectionSize.insert(logicalIndex, size);
         if (d->sectionHidden.count() < count())
             d->sectionHidden.resize(count());
         d->sectionHidden.setBit(visual, true);
         if (d->hasAutoResizeSections())
             d->doDelayedResizeSections();
     } else {
         int size = d->hiddenSectionSize.value(logicalIndex, d->defaultSectionSize);
         d->hiddenSectionSize.remove(logicalIndex);
         if (d->hiddenSectionSize.isEmpty()) {
             d->sectionHidden.clear();
         } else {
             Q_ASSERT(visual <= d->sectionHidden.count());
             d->sectionHidden.setBit(visual, false);
         }
         resizeSection(logicalIndex, size);
     }
 }
setSelection()
void QHeaderView::setSelection (const QRect & rect, QItemSelectionModel::SelectionFlags flags) protected virtual
Selects the items in the given rect according to the specified flags.
Reimplemented Function
The base class implementation does nothing.
Implements QAbstractItemView.
Definition at line 2877 of file qheaderview.cpp.
 {
     // do nothing
 }
setSortIndicator()
void QHeaderView::setSortIndicator (int logicalIndex, Qt::SortOrder order)
Sets the sort indicator for the section specified by the given logicalIndex in the direction specified by order, and removes the sort indicator from any other section that was showing it.
logicalIndex may be -1, in which case no sort indicator will be shown and the model will return to its natural, unsorted order. Note that not all models support this and may even crash in this case.
See also
sortIndicatorSection() sortIndicatorOrder()
Definition at line 1359 of file qheaderview.cpp.
Referenced by QFileDialogTreeView::init(), QTableWidget::sortItems(), and QTreeWidget::sortItems().
 {
     Q_D(QHeaderView);
     // This is so that people can set the position of the sort indicator before the fill the model
     int old = d->sortIndicatorSection;
     d->sortIndicatorSection = logicalIndex;
     d->sortIndicatorOrder = order;
     if (logicalIndex >= d->sectionCount) {
         emit sortIndicatorChanged(logicalIndex, order);
         return; // nothing to do
     }
     if (old != logicalIndex
         && ((logicalIndex >= 0 && resizeMode(logicalIndex) == ResizeToContents)
             || old >= d->sectionCount || (old >= 0 && resizeMode(old) == ResizeToContents))) {
         resizeSections();
         d->viewport->update();
     } else {
         if (old >= 0 && old != logicalIndex)
             updateSection(old);
         if (logicalIndex >= 0)
             updateSection(logicalIndex);
     }
     emit sortIndicatorChanged(logicalIndex, order);
 }
setSortIndicatorShown()
void QHeaderView::setSortIndicatorShown (bool show)
Definition at line 1324 of file qheaderview.cpp.
Referenced by QTableView::setSortingEnabled(), and QTreeView::setSortingEnabled().
 {
     Q_D(QHeaderView);
     if (d->sortIndicatorShown == show)
         return;
     d->sortIndicatorShown = show;
     if (sortIndicatorSection() < 0 || sortIndicatorSection() > count())
         return;
     if (d->headerSectionResizeMode(sortIndicatorSection()) == ResizeToContents)
         resizeSections();
     d->viewport->update();
 }
setStretchLastSection()
void QHeaderView::setStretchLastSection (bool stretch)
Definition at line 1438 of file qheaderview.cpp.
Referenced by QFileDialogTreeView::init(), and QTreeViewPrivate::initialize().
 {
     Q_D(QHeaderView);
     d->stretchLastSection = stretch;
     if (d->state != QHeaderViewPrivate::NoState)
         return;
     if (stretch)
         resizeSections();
     else if (count())
         resizeSection(count() - 1, d->defaultSectionSize);
 }
showSection()
void QHeaderView::showSection (int logicalIndex) inline
Shows the section specified by logicalIndex.
See also
hideSection(), isSectionHidden(), hiddenSectionCount(), setSectionHidden()
Definition at line 241 of file qheaderview.h.
 { setSectionHidden(alogicalIndex, false); }
sizeHint()
QSize QHeaderView::sizeHint () const virtual
Returns a suitable size hint for this header.
See also
sectionSizeHint()
Reimplemented from QWidget.
Definition at line 575 of file qheaderview.cpp.
Referenced by QFileDialogTreeView::sizeHint().
 {
     Q_D(const QHeaderView);
     if (d->cachedSizeHint.isValid())
         return d->cachedSizeHint;
     d->cachedSizeHint = QSize(0, 0); //reinitialize the cached size hint
     const int sectionCount = count();
     // get size hint for the first n sections
     int i = 0;
     for (int checked = 0; checked < 100 && i < sectionCount; ++i) {
         if (isSectionHidden(i))
             continue;
         checked++;
         QSize hint = sectionSizeFromContents(i);
         d->cachedSizeHint = d->cachedSizeHint.expandedTo(hint);
     }
     // get size hint for the last n sections
     i = qMax(i, sectionCount - 100 );
     for (int j = sectionCount - 1, checked = 0; j >= i && checked < 100; --j) {
         if (isSectionHidden(j))
             continue;
         checked++;
         QSize hint = sectionSizeFromContents(j);
         d->cachedSizeHint = d->cachedSizeHint.expandedTo(hint);
     }
     return d->cachedSizeHint;
 }
sortIndicatorChanged
void QHeaderView::sortIndicatorChanged (int logicalIndex, Qt::SortOrder order) signal
Referenced by restoreState(), and setSortIndicator().
sortIndicatorOrder()
Qt::SortOrder QHeaderView::sortIndicatorOrder () const
Returns the order for the sort indicator.
If no section has a sort indicator the return value of this function is undefined.
See also
setSortIndicator() sortIndicatorSection()
Definition at line 1408 of file qheaderview.cpp.
Referenced by QTreeModel::executePendingSort(), QHeaderViewPrivate::flipSortIndicator(), paintSection(), QHeaderViewPrivate::read(), QTableModel::setItem(), and QHeaderViewPrivate::write().
 {
     Q_D(const QHeaderView);
     return d->sortIndicatorOrder;
 }
sortIndicatorSection()
int QHeaderView::sortIndicatorSection () const
Returns the logical index of the section that has a sort indicator.
By default this is section 0.
See also
setSortIndicator() sortIndicatorOrder() setSortIndicatorShown()
Definition at line 1395 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate::_q_sectionsRemoved(), QTreeModel::executePendingSort(), QHeaderViewPrivate::flipSortIndicator(), paintSection(), QHeaderViewPrivate::read(), QTableModel::setItem(), setSortIndicatorShown(), and QHeaderViewPrivate::write().
 {
     Q_D(const QHeaderView);
     return d->sortIndicatorSection;
 }
stretchLastSection()
bool QHeaderView::stretchLastSection () const
Referenced by initializeSections(), moveSection(), QHeaderViewPrivate::read(), resizeSection(), QHeaderViewPrivate::resizeSections(), sortIndicatorOrder(), and QHeaderViewPrivate::write().
stretchSectionCount()
int QHeaderView::stretchSectionCount () const
Returns the number of sections that are set to resize mode stretch.
Since
4.1
In views, this can be used to see if the headerview needs to resize the sections when the view's geometry changes.
See also
stretchLastSection, resizeMode()
Definition at line 1306 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     return d->stretchSections;
 }
swapSections()
void QHeaderView::swapSections (int first, int second)
Swaps the section at visual index first with the section at visual index second.
Since
4.2
See also
moveSection()
Definition at line 874 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     if (first == second)
         return;
     d->executePostedLayout();
     if (first < 0 || first >= d->sectionCount || second < 0 || second >= d->sectionCount)
         return;
     int firstSize = d->headerSectionSize(first);
     ResizeMode firstMode = d->headerSectionResizeMode(first);
     int firstLogical = d->logicalIndex(first);
     int secondSize = d->headerSectionSize(second);
     ResizeMode secondMode = d->headerSectionResizeMode(second);
     int secondLogical = d->logicalIndex(second);
     d->createSectionSpan(second, second, firstSize, firstMode);
     d->createSectionSpan(first, first, secondSize, secondMode);
     d->initializeIndexMapping();
     d->visualIndices[firstLogical] = second;
     d->logicalIndices[second] = firstLogical;
     d->visualIndices[secondLogical] = first;
     d->logicalIndices[first] = secondLogical;
     if (!d->sectionHidden.isEmpty()) {
         bool firstHidden = d->sectionHidden.testBit(first);
         bool secondHidden = d->sectionHidden.testBit(second);
         d->sectionHidden.setBit(first, secondHidden);
         d->sectionHidden.setBit(second, firstHidden);
     }
     d->viewport->update();
     emit sectionMoved(firstLogical, first, second);
     emit sectionMoved(secondLogical, second, first);
 }
updateGeometries()
void QHeaderView::updateGeometries () protected virtual
Reimplemented Function
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 2738 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     d->layoutChildren();
     if (d->hasAutoResizeSections())
         d->doDelayedResizeSections();
 }
updateSection
void QHeaderView::updateSection (int logicalIndex) protected slot
Updates the section specified by the given logicalIndex.
Warning
This function is not part of the public interface.
Since
4.2
Definition at line 1716 of file qheaderview.cpp.
Referenced by event(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), moveSection(), and setSortIndicator().
 {
     Q_D(QHeaderView);
     if (d->orientation == Qt::Horizontal)
         d->viewport->update(QRect(sectionViewportPosition(logicalIndex),
                                   0, sectionSize(logicalIndex), d->viewport->height()));
     else
         d->viewport->update(QRect(0, sectionViewportPosition(logicalIndex),
                                   d->viewport->width(), sectionSize(logicalIndex)));
 }
verticalOffset()
int QHeaderView::verticalOffset () const protected virtual
Returns the vertical offset of the header.
This is 0 for horizontal headers.
See also
offset()
Implements QAbstractItemView.
Definition at line 2725 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     if (d->orientation == Qt::Vertical)
         return d->offset;
     return 0;
 }
viewportEvent()
bool QHeaderView::viewportEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractItemView.
Definition at line 2479 of file qheaderview.cpp.
 {
     Q_D(QHeaderView);
     switch (e->type()) {
 #ifndef QT_NO_TOOLTIP
     case QEvent::ToolTip: {
         QHelpEvent *he = static_cast<QHelpEvent*>(e);
         int logical = logicalIndexAt(he->pos());
         if (logical != -1) {
             QVariant variant = d->model->headerData(logical, d->orientation, Qt::ToolTipRole);
             if (variant.isValid()) {
                 QToolTip::showText(he->globalPos(), variant.toString(), this);
                 return true;
             }
         }
         break; }
 #endif
 #ifndef QT_NO_WHATSTHIS
     case QEvent::QueryWhatsThis: {
         QHelpEvent *he = static_cast<QHelpEvent*>(e);
         int logical = logicalIndexAt(he->pos());
         if (logical != -1
             && d->model->headerData(logical, d->orientation, Qt::WhatsThisRole).isValid())
             return true;
         break; }
     case QEvent::WhatsThis: {
         QHelpEvent *he = static_cast<QHelpEvent*>(e);
         int logical = logicalIndexAt(he->pos());
         if (logical != -1) {
              QVariant whatsthis = d->model->headerData(logical, d->orientation,
                                                       Qt::WhatsThisRole);
              if (whatsthis.isValid()) {
                  QWhatsThis::showText(he->globalPos(), whatsthis.toString(), this);
                  return true;
              }
         }
         break; }
 #endif // QT_NO_WHATSTHIS
 #ifndef QT_NO_STATUSTIP
     case QEvent::StatusTip: {
         QHelpEvent *he = static_cast<QHelpEvent*>(e);
         int logical = logicalIndexAt(he->pos());
         if (logical != -1) {
             QString statustip = d->model->headerData(logical, d->orientation,
                                                     Qt::StatusTipRole).toString();
             if (!statustip.isEmpty())
                 setStatusTip(statustip);
         }
         return true; }
 #endif // QT_NO_STATUSTIP
     case QEvent::Hide:
     case QEvent::Show:
     case QEvent::FontChange:
     case QEvent::StyleChange:
         d->invalidateCachedSizeHint();
         resizeSections();
         emit geometriesChanged();
         break;
     case QEvent::ContextMenu: {
         d->state = QHeaderViewPrivate::NoState;
         d->pressed = d->section = d->target = -1;
         d->updateSectionIndicator(d->section, -1);
         break; }
     case QEvent::Wheel: {
         QAbstractScrollArea *asa = qobject_cast<QAbstractScrollArea *>(parentWidget());
         if (asa)
             return QApplication::sendEvent(asa->viewport(), e);
         break; }
     default:
         break;
     }
     return QAbstractItemView::viewportEvent(e);
 }
visualIndex()
int QHeaderView::visualIndex (int logicalIndex) const
Returns the visual index position of the section specified by the given logicalIndex, or -1 otherwise.
Hidden sections still have valid visual indexes.
See also
logicalIndex()
Definition at line 1116 of file qheaderview.cpp.
Referenced by QHeaderViewPrivate::adjustedVisualIndex(), QTreeViewPrivate::adjustViewOptionsForIndex(), QTreeViewPrivate::columnRanges(), QTreeView::drawRow(), headerDataChanged(), isSectionHidden(), mouseMoveEvent(), mouseReleaseEvent(), paintSection(), resizeMode(), resizeSection(), sectionPosition(), sectionSize(), QTableViewPrivate::sectionSpanEndLogical(), setResizeMode(), setSectionHidden(), QTableViewPrivate::spanContainsSection(), QTableWidget::visualColumn(), visualRegionForSelection(), and QTableWidget::visualRow().
 {
     Q_D(const QHeaderView);
     if (logicalIndex < 0)
         return -1;
     d->executePostedLayout();
     if (d->visualIndices.isEmpty()) { // nothing has been moved, so we have no mapping
         if (logicalIndex < d->sectionCount)
             return logicalIndex;
     } else if (logicalIndex < d->visualIndices.count()) {
         int visual = d->visualIndices.at(logicalIndex);
         Q_ASSERT(visual < d->sectionCount);
         return visual;
     }
     return -1;
 }
visualIndexAt()
int QHeaderView::visualIndexAt (int position) const
Returns the visual index of the section that covers the given position in the viewport.
See also
logicalIndexAt()
Definition at line 635 of file qheaderview.cpp.
Referenced by logicalIndexAt(), mouseMoveEvent(), QTableView::paintEvent(), paintEvent(), and QTreeViewPrivate::startAndEndColumns().
 {
     Q_D(const QHeaderView);
     int vposition = position;
     d->executePostedLayout();
     d->executePostedResize();
     const int count = d->sectionCount;
     if (count < 1)
         return -1;
     if (d->reverse())
         vposition = d->viewport->width() - vposition;
     vposition += d->offset;
     if (vposition > d->length)
         return -1;
     int visual = d->headerVisualIndexAt(vposition);
     if (visual < 0)
         return -1;
     while (d->isVisualIndexHidden(visual)){
         ++visual;
         if (visual >= count)
             return -1;
     }
     return visual;
 }
visualRect()
QRect QHeaderView::visualRect (const QModelIndex & index) const protected virtual
Empty implementation because the header doesn't show QModelIndex items.
Reimplemented Function
Warning
This function is not part of the public interface.
Implements QAbstractItemView.
Definition at line 2800 of file qheaderview.cpp.
 {
     return QRect();
 }
visualRegionForSelection()
QRegion QHeaderView::visualRegionForSelection (const QItemSelection & selection) const protected virtual
Warning
This function is not part of the public interface.
Implements QAbstractItemView.
Definition at line 2886 of file qheaderview.cpp.
 {
     Q_D(const QHeaderView);
     const int max = d->modelSectionCount();
     if (d->orientation == Qt::Horizontal) {
         int left = max;
         int right = 0;
         int rangeLeft, rangeRight;
         for (int i = 0; i < selection.count(); ++i) {
             QItemSelectionRange r = selection.at(i);
             if (r.parent().isValid() || !r.isValid())
                 continue; // we only know about toplevel items and we don't want invalid ranges
             // FIXME an item inside the range may be the leftmost or rightmost
             rangeLeft = visualIndex(r.left());
             if (rangeLeft == -1) // in some cases users may change the selections
                 continue;        // before we have a chance to do the layout
             rangeRight = visualIndex(r.right());
             if (rangeRight == -1) // in some cases users may change the selections
                 continue;         // before we have a chance to do the layout
             if (rangeLeft < left)
                 left = rangeLeft;
             if (rangeRight > right)
                 right = rangeRight;
         }
         int logicalLeft = logicalIndex(left);
         int logicalRight = logicalIndex(right);
         if (logicalLeft < 0  || logicalLeft >= count() ||
             logicalRight < 0 || logicalRight >= count())
             return QRegion();
         int leftPos = sectionViewportPosition(logicalLeft);
         int rightPos = sectionViewportPosition(logicalRight);
         rightPos += sectionSize(logicalRight);
         return QRect(leftPos, 0, rightPos - leftPos, height());
     }
     // orientation() == Qt::Vertical
     int top = max;
     int bottom = 0;
     int rangeTop, rangeBottom;
     for (int i = 0; i < selection.count(); ++i) {
         QItemSelectionRange r = selection.at(i);
         if (r.parent().isValid() || !r.isValid())
             continue; // we only know about toplevel items
         // FIXME an item inside the range may be the leftmost or rightmost
         rangeTop = visualIndex(r.top());
         if (rangeTop == -1) // in some cases users may change the selections
             continue;       // before we have a chance to do the layout
         rangeBottom = visualIndex(r.bottom());
         if (rangeBottom == -1) // in some cases users may change the selections
             continue;          // before we have a chance to do the layout
         if (rangeTop < top)
             top = rangeTop;
         if (rangeBottom > bottom)
             bottom = rangeBottom;
     }
     int logicalTop = logicalIndex(top);
     int logicalBottom = logicalIndex(bottom);
     if (logicalTop == -1 || logicalBottom == -1)
         return QRect();
     int topPos = sectionViewportPosition(logicalTop);
     int bottomPos = sectionViewportPosition(logicalBottom) + sectionSize(logicalBottom);
     return QRect(0, topPos, width(), bottomPos - topPos);
 }
Properties
cascadingSectionResizes
bool QHeaderView::cascadingSectionResizes private
whether interactive resizing will be cascaded to the following sections once the section being resized by the user has reached its minimum size
Since
4.2
This property only affects sections that have Interactive as their resize mode.
The default value is false.
See also
setResizeMode()
Definition at line 64 of file qheaderview.h.
defaultAlignment
Qt::Alignment QHeaderView::defaultAlignment private
the default alignment of the text in each header section
Since
4.1
Definition at line 67 of file qheaderview.h.
defaultSectionSize
int QHeaderView::defaultSectionSize private
the default size of the header sections before resizing.
This property only affects sections that have Interactive or Fixed as their resize mode.
See also
setResizeMode() minimumSectionSize
Definition at line 65 of file qheaderview.h.
highlightSections
bool QHeaderView::highlightSections private
whether the sections containing selected items are highlighted
By default, this property is false.
Definition at line 62 of file qheaderview.h.
minimumSectionSize
int QHeaderView::minimumSectionSize private
the minimum size of the header sections.
Since
4.2
The minimum section size is the smallest section size allowed. If the minimum section size is set to -1, QHeaderView will use the maximum of the global strut or the font metrics size.
This property is honored by all resize modes.
See also
setResizeMode() defaultSectionSize
Definition at line 66 of file qheaderview.h.
showSortIndicator
QHeaderView::showSortIndicator private
whether the sort indicator is shown
By default, this property is false.
See also
setClickable()
Definition at line 61 of file qheaderview.h.
stretchLastSection
bool QHeaderView::stretchLastSection private
whether the last visible section in the header takes up all the available space
The default value is false.
Note
The horizontal headers provided by QTreeView are configured with this property set to true, ensuring that the view does not waste any of the space assigned to it for its header. If this value is set to true, this property will override the resize mode set on the last section in the header.
See also
setResizeMode()
Definition at line 63 of file qheaderview.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qheaderview.h
/src/gui/itemviews/qheaderview.cpp