Qt 4.8: QGLBlurTextureInfo Class Reference
QGLBlurTextureInfo Class Reference
Public Functions
QImage paddedImage (int scaleLevel=0) const
QGLBlurTextureInfo (const QImage &image, GLuint tex, qreal r)
qreal radius () const
GLuint texture () const
~QGLBlurTextureInfo ()
Properties
QList< QImage > m_paddedImage
qreal m_radius
GLuint m_texture
Detailed Description
Definition at line 280 of file qglpixmapfilter.cpp.
Constructors and Destructors
QGLBlurTextureInfo()
QGLBlurTextureInfo::QGLBlurTextureInfo (const QImage & image, GLuint tex, qreal r) inline
Definition at line 283 of file qglpixmapfilter.cpp.
         : m_texture(tex)
         , m_radius(r)
     {
         m_paddedImage << image;
     }
~QGLBlurTextureInfo()
QGLBlurTextureInfo::~QGLBlurTextureInfo () inline
Definition at line 290 of file qglpixmapfilter.cpp.
     {
         glDeleteTextures(1, &m_texture);
     }
Functions
paddedImage()
QImage QGLBlurTextureInfo::paddedImage (int scaleLevel = 0) const
Definition at line 305 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 {
     for (int i = m_paddedImage.size() - 1; i <= scaleLevel; ++i)
         m_paddedImage << qt_halfScaled(m_paddedImage.at(i));
     return m_paddedImage.at(scaleLevel);
 }
radius()
qreal QGLBlurTextureInfo::radius () const inline
Definition at line 297 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 { return m_radius; }
texture()
GLuint QGLBlurTextureInfo::texture () const inline
Definition at line 296 of file qglpixmapfilter.cpp.
Referenced by QGLPixmapBlurFilter::processGL(), and QGLPixmapDropShadowFilter::processGL().
 { return m_texture; }
Properties
m_paddedImage
QList<QImage> QGLBlurTextureInfo::m_paddedImage mutable private
Definition at line 300 of file qglpixmapfilter.cpp.
m_radius
qreal QGLBlurTextureInfo::m_radius private
Definition at line 302 of file qglpixmapfilter.cpp.
m_texture
GLuint QGLBlurTextureInfo::m_texture private
Definition at line 301 of file qglpixmapfilter.cpp.
The documentation for this class was generated from the following file:
/src/opengl/qglpixmapfilter.cpp