Qt 4.8: QNativeWifiEngine Class Reference
QNativeWifiEngine Class Reference
#include <qnativewifiengine.h>
Public Functions
bool available ()
QNetworkConfigurationManager::Capabilities capabilities () const
void connectToId (const QString &id)
QNetworkSessionPrivate * createSessionBackend ()
QNetworkConfigurationPrivatePointer defaultConfiguration ()
void disconnectFromId (const QString &id)
QString getInterfaceFromId (const QString &id)
bool hasIdentifier (const QString &id)
Q_INVOKABLE void initialize ()
QNativeWifiEngine (QObject *parent=0)
Q_INVOKABLE void requestUpdate ()
bool requiresPolling () const
QNetworkSession::State sessionStateForId (const QString &id)
~QNativeWifiEngine ()
Public Functions inherited from QBearerEngineImpl
virtual quint64 bytesReceived (const QString &)
virtual quint64 bytesWritten (const QString &)
QBearerEngineImpl (QObject *parent=0)
virtual quint64 startTime (const QString &)
~QBearerEngineImpl ()
Public Functions inherited from QBearerEngine
bool configurationsInUse () const
QBearerEngine (QObject *parent=0)
virtual ~QBearerEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void closeHandle ()
void scanComplete ()
Properties
Qt::HANDLE handle
Additional Inherited Members
Public Types inherited from QBearerEngineImpl
enum ConnectionError { InterfaceLookupError = 0, ConnectError, OperationNotSupported, DisconnectionError }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QBearerEngineImpl
void connectionError (const QString &id, QBearerEngineImpl::ConnectionError error)
Signals inherited from QBearerEngine
void configurationAdded (QNetworkConfigurationPrivatePointer config)
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void configurationRemoved (QNetworkConfigurationPrivatePointer config)
void updateCompleted ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QBearerEngine
QHash< QString, QNetworkConfigurationPrivatePointer > accessPointConfigurations
QMutex mutex
QHash< QString, QNetworkConfigurationPrivatePointer > snapConfigurations
QHash< QString, QNetworkConfigurationPrivatePointer > userChoiceConfigurations
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 67 of file qnativewifiengine.h.
Constructors and Destructors
QNativeWifiEngine()
QNativeWifiEngine::QNativeWifiEngine (QObject * parent = 0)
Definition at line 93 of file qnativewifiengine.cpp.
 :   QBearerEngineImpl(parent), handle(INVALID_HANDLE_VALUE)
 {
     connect(QCoreApplication::instance(), SIGNAL(aboutToQuit()), this, SLOT(closeHandle()));
 }
~QNativeWifiEngine()
QNativeWifiEngine::~QNativeWifiEngine ()
Definition at line 99 of file qnativewifiengine.cpp.
 {
     closeHandle();
 }
Functions
available()
bool QNativeWifiEngine::available ()
Definition at line 577 of file qnativewifiengine.cpp.
Referenced by connectToId(), QNativeWifiEnginePlugin::create(), disconnectFromId(), getInterfaceFromId(), hasIdentifier(), requestUpdate(), and scanComplete().
 {
     if (handle != INVALID_HANDLE_VALUE)
         return true;
     DWORD clientVersion;
     DWORD result = local_WlanOpenHandle(1, 0, &clientVersion, &handle);
     if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         if (result != ERROR_SERVICE_NOT_ACTIVE)
             qDebug("%s: WlanOpenHandle failed with error %ld\n", __FUNCTION__, result);
 #endif
         return false;
     }
     result = local_WlanRegisterNotification(handle, WLAN_NOTIFICATION_SOURCE_ALL, true,
                                             WLAN_NOTIFICATION_CALLBACK(qNotificationCallback),
                                             this, 0, 0);
 #ifdef BEARER_MANAGEMENT_DEBUG
     if (result != ERROR_SUCCESS)
         qDebug("%s: WlanRegisterNotification failed with error %ld\n", __FUNCTION__, result);
 #endif
     return handle != INVALID_HANDLE_VALUE;
 }
capabilities()
QNetworkConfigurationManager::Capabilities QNativeWifiEngine::capabilities () const virtual
Implements QBearerEngine.
Definition at line 561 of file qnativewifiengine.cpp.
 {
     return QNetworkConfigurationManager::ForcedRoaming |
             QNetworkConfigurationManager::CanStartAndStopInterfaces;
 }
closeHandle
void QNativeWifiEngine::closeHandle () private slot
Definition at line 605 of file qnativewifiengine.cpp.
Referenced by QNativeWifiEngine(), and ~QNativeWifiEngine().
 {
     if (handle != INVALID_HANDLE_VALUE) {
         local_WlanCloseHandle(handle, 0);
         handle = INVALID_HANDLE_VALUE;
     }
 }
connectToId()
void QNativeWifiEngine::connectToId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 364 of file qnativewifiengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!available()) {
         locker.unlock();
         emit connectionError(id, InterfaceLookupError);
         return;
     }
     WLAN_INTERFACE_INFO_LIST *interfaceList;
     DWORD result = local_WlanEnumInterfaces(handle, 0, &interfaceList);
     if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: WlanEnumInterfaces failed with error %ld\n", __FUNCTION__, result);
 #endif
         locker.unlock();
         emit connectionError(id, InterfaceLookupError);
         return;
     }
     QString profile;
     for (unsigned int i = 0; i < interfaceList->dwNumberOfItems; ++i) {
         const WLAN_INTERFACE_INFO &interface = interfaceList->InterfaceInfo[i];
         WLAN_AVAILABLE_NETWORK_LIST *networkList;
         result = local_WlanGetAvailableNetworkList(handle, &interface.InterfaceGuid,
                                                    3, 0, &networkList);
         if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("%s: WlanGetAvailableNetworkList failed with error %ld\n",
                    __FUNCTION__, result);
 #endif
             continue;
         }
         for (unsigned int j = 0; j < networkList->dwNumberOfItems; ++j) {
             WLAN_AVAILABLE_NETWORK &network = networkList->Network[j];
             profile = QString::fromWCharArray(network.strProfileName);
             if (qHash(QLatin1String("WLAN:") + profile) == id.toUInt())
                 break;
             else
                 profile.clear();
         }
         local_WlanFreeMemory(networkList);
         if (!profile.isEmpty()) {
             WLAN_CONNECTION_PARAMETERS parameters;
             parameters.wlanConnectionMode = wlan_connection_mode_profile;
             parameters.strProfile = reinterpret_cast<LPCWSTR>(profile.utf16());
             parameters.pDot11Ssid = 0;
             parameters.pDesiredBssidList = 0;
             parameters.dot11BssType = dot11_BSS_type_any;
             parameters.dwFlags = 0;
             DWORD result = local_WlanConnect(handle, &interface.InterfaceGuid, &parameters, 0);
             if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
                 qDebug("%s: WlanConnect failed with error %ld\n", __FUNCTION__, result);
 #endif
                 locker.unlock();
                 emit connectionError(id, ConnectError);
                 locker.relock();
                 break;
             }
             break;
         }
     }
     local_WlanFreeMemory(interfaceList);
     if (profile.isEmpty()) {
         locker.unlock();
         emit connectionError(id, InterfaceLookupError);
     }
 }
createSessionBackend()
QNetworkSessionPrivate * QNativeWifiEngine::createSessionBackend () virtual
Implements QBearerEngine.
Definition at line 567 of file qnativewifiengine.cpp.
 {
     return new QNetworkSessionPrivateImpl;
 }
defaultConfiguration()
QNetworkConfigurationPrivatePointer QNativeWifiEngine::defaultConfiguration () virtual
Implements QBearerEngine.
Definition at line 572 of file qnativewifiengine.cpp.
 {
     return QNetworkConfigurationPrivatePointer();
 }
disconnectFromId()
void QNativeWifiEngine::disconnectFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 446 of file qnativewifiengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!available()) {
         locker.unlock();
         emit connectionError(id, InterfaceLookupError);
         return;
     }
     QString interface = getInterfaceFromId(id);
     if (interface.isEmpty()) {
         locker.unlock();
         emit connectionError(id, InterfaceLookupError);
         return;
     }
     QStringList split = interface.mid(1, interface.length() - 2).split('-');
     GUID guid;
     guid.Data1 = split.at(0).toUInt(0, 16);
     guid.Data2 = split.at(1).toUShort(0, 16);
     guid.Data3 = split.at(2).toUShort(0, 16);
     guid.Data4[0] = split.at(3).left(2).toUShort(0, 16);
     guid.Data4[1] = split.at(3).right(2).toUShort(0, 16);
     for (int i = 0; i < 6; ++i)
         guid.Data4[i + 2] = split.at(4).mid(i*2, 2).toUShort(0, 16);
     DWORD result = local_WlanDisconnect(handle, &guid, 0);
     if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: WlanDisconnect failed with error %ld\n", __FUNCTION__, result);
 #endif
         locker.unlock();
         emit connectionError(id, DisconnectionError);
         return;
     }
 }
getInterfaceFromId()
QString QNativeWifiEngine::getInterfaceFromId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 248 of file qnativewifiengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!available())
         return QString();
     // enumerate interfaces
     WLAN_INTERFACE_INFO_LIST *interfaceList;
     DWORD result = local_WlanEnumInterfaces(handle, 0, &interfaceList);
     if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: WlanEnumInterfaces failed with error %ld\n", __FUNCTION__, result);
 #endif
         return QString();
     }
     for (unsigned int i = 0; i < interfaceList->dwNumberOfItems; ++i) {
         const WLAN_INTERFACE_INFO &interface = interfaceList->InterfaceInfo[i];
         DWORD dataSize;
         WLAN_CONNECTION_ATTRIBUTES *connectionAttributes;
         result = local_WlanQueryInterface(handle, &interface.InterfaceGuid,
                                           wlan_intf_opcode_current_connection, 0, &dataSize,
                                           reinterpret_cast<PVOID *>(&connectionAttributes), 0);
         if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             if (result != ERROR_INVALID_STATE)
                 qDebug("%s: WlanQueryInterface failed with error %ld\n", __FUNCTION__, result);
 #endif
             continue;
         }
         if (qHash(QLatin1String("WLAN:") +
                   QString::fromWCharArray(connectionAttributes->strProfileName)) == id.toUInt()) {
             QString guid("{%1-%2-%3-%4%5-%6%7%8%9%10%11}");
             guid = guid.arg(interface.InterfaceGuid.Data1, 8, 16, QChar('0'));
             guid = guid.arg(interface.InterfaceGuid.Data2, 4, 16, QChar('0'));
             guid = guid.arg(interface.InterfaceGuid.Data3, 4, 16, QChar('0'));
             for (int i = 0; i < 8; ++i)
                 guid = guid.arg(interface.InterfaceGuid.Data4[i], 2, 16, QChar('0'));
             local_WlanFreeMemory(connectionAttributes);
             local_WlanFreeMemory(interfaceList);
             return guid.toUpper();
         }
         local_WlanFreeMemory(connectionAttributes);
     }
     local_WlanFreeMemory(interfaceList);
     return QString();
 }
hasIdentifier()
bool QNativeWifiEngine::hasIdentifier (const QString & id) virtual
Implements QBearerEngine.
Definition at line 306 of file qnativewifiengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!available())
         return false;
     // enumerate interfaces
     WLAN_INTERFACE_INFO_LIST *interfaceList;
     DWORD result = local_WlanEnumInterfaces(handle, 0, &interfaceList);
     if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: WlanEnumInterfaces failed with error %ld\n", __FUNCTION__, result);
 #endif
         return false;
     }
     for (unsigned int i = 0; i < interfaceList->dwNumberOfItems; ++i) {
         const WLAN_INTERFACE_INFO &interface = interfaceList->InterfaceInfo[i];
         WLAN_AVAILABLE_NETWORK_LIST *networkList;
         result = local_WlanGetAvailableNetworkList(handle, &interface.InterfaceGuid,
                                                    3, 0, &networkList);
         if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("%s: WlanGetAvailableNetworkList failed with error %ld\n",
                    __FUNCTION__, result);
 #endif
             continue;
         }
         for (unsigned int j = 0; j < networkList->dwNumberOfItems; ++j) {
             WLAN_AVAILABLE_NETWORK &network = networkList->Network[j];
             QString networkName;
             if (network.strProfileName[0] != 0) {
                 networkName = QString::fromWCharArray(network.strProfileName);
             } else {
                 networkName = QByteArray(reinterpret_cast<char *>(network.dot11Ssid.ucSSID),
                                          network.dot11Ssid.uSSIDLength);
             }
             if (qHash(QLatin1String("WLAN:") + networkName) == id.toUInt()) {
                 local_WlanFreeMemory(networkList);
                 local_WlanFreeMemory(interfaceList);
                 return true;
             }
         }
         local_WlanFreeMemory(networkList);
     }
     local_WlanFreeMemory(interfaceList);
     return false;
 }
initialize()
void QNativeWifiEngine::initialize ()
Definition at line 486 of file qnativewifiengine.cpp.
 {
     scanComplete();
 }
requestUpdate()
void QNativeWifiEngine::requestUpdate ()
Definition at line 491 of file qnativewifiengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!available()) {
         locker.unlock();
         emit updateCompleted();
         return;
     }
     // enumerate interfaces
     WLAN_INTERFACE_INFO_LIST *interfaceList;
     DWORD result = local_WlanEnumInterfaces(handle, 0, &interfaceList);
     if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: WlanEnumInterfaces failed with error %ld\n", __FUNCTION__, result);
 #endif
         locker.unlock();
         emit updateCompleted();
         return;
     }
     bool requested = false;
     for (unsigned int i = 0; i < interfaceList->dwNumberOfItems; ++i) {
         result = local_WlanScan(handle, &interfaceList->InterfaceInfo[i].InterfaceGuid, 0, 0, 0);
         if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("%s: WlanScan failed with error %ld\n", __FUNCTION__, result);
 #endif
         } else {
             requested = true;
         }
     }
     local_WlanFreeMemory(interfaceList);
     if (!requested) {
         locker.unlock();
         emit updateCompleted();
     }
 }
requiresPolling()
bool QNativeWifiEngine::requiresPolling () const virtual
Reimplemented from QBearerEngine.
Definition at line 613 of file qnativewifiengine.cpp.
 {
     // On Windows XP SP2 and SP3 only connection and disconnection notifications are available.
     // We need to poll for changes in available wireless networks.
     return true;
 }
scanComplete
void QNativeWifiEngine::scanComplete () private slot
Definition at line 104 of file qnativewifiengine.cpp.
Referenced by initialize().
 {
     QMutexLocker locker(&mutex);
     if (!available()) {
         locker.unlock();
         emit updateCompleted();
         return;
     }
     // enumerate interfaces
     WLAN_INTERFACE_INFO_LIST *interfaceList;
     DWORD result = local_WlanEnumInterfaces(handle, 0, &interfaceList);
     if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("%s: WlanEnumInterfaces failed with error %ld\n", __FUNCTION__, result);
 #endif
         locker.unlock();
         emit updateCompleted();
         return;
     }
     QStringList previous = accessPointConfigurations.keys();
     for (unsigned int i = 0; i < interfaceList->dwNumberOfItems; ++i) {
         const WLAN_INTERFACE_INFO &interface = interfaceList->InterfaceInfo[i];
         WLAN_AVAILABLE_NETWORK_LIST *networkList;
         result = local_WlanGetAvailableNetworkList(handle, &interface.InterfaceGuid,
                                                    3, 0, &networkList);
         if (result != ERROR_SUCCESS) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("%s: WlanGetAvailableNetworkList failed with error %ld\n",
                    __FUNCTION__, result);
 #endif
             continue;
         }
         QStringList seenNetworks;
         for (unsigned int j = 0; j < networkList->dwNumberOfItems; ++j) {
             WLAN_AVAILABLE_NETWORK &network = networkList->Network[j];
             QString networkName;
             if (network.strProfileName[0] != 0) {
                 networkName = QString::fromWCharArray(network.strProfileName);
             } else {
                 networkName = QByteArray(reinterpret_cast<char *>(network.dot11Ssid.ucSSID),
                                          network.dot11Ssid.uSSIDLength);
             }
             const QString id = QString::number(qHash(QLatin1String("WLAN:") + networkName));
             previous.removeAll(id);
             QNetworkConfiguration::StateFlags state = QNetworkConfiguration::Undefined;
             if (!(network.dwFlags & WLAN_AVAILABLE_NETWORK_HAS_PROFILE))
                 state = QNetworkConfiguration::Undefined;
             if (network.strProfileName[0] != 0) {
                 if (network.bNetworkConnectable) {
                     if (network.dwFlags & WLAN_AVAILABLE_NETWORK_CONNECTED)
                         state = QNetworkConfiguration::Active;
                     else
                         state = QNetworkConfiguration::Discovered;
                 } else {
                     state = QNetworkConfiguration::Defined;
                 }
             }
             if (seenNetworks.contains(networkName))
                 continue;
             else
                 seenNetworks.append(networkName);
             if (accessPointConfigurations.contains(id)) {
                 QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
                 bool changed = false;
                 ptr->mutex.lock();
                 if (!ptr->isValid) {
                     ptr->isValid = true;
                     changed = true;
                 }
                 if (ptr->name != networkName) {
                     ptr->name = networkName;
                     changed = true;
                 }
                 if (ptr->state != state) {
                     ptr->state = state;
                     changed = true;
                 }
                 ptr->mutex.unlock();
                 if (changed) {
                     locker.unlock();
                     emit configurationChanged(ptr);
                     locker.relock();
                 }
             } else {
                 QNetworkConfigurationPrivatePointer ptr(new QNetworkConfigurationPrivate);
                 ptr->name = networkName;
                 ptr->isValid = true;
                 ptr->id = id;
                 ptr->state = state;
                 ptr->type = QNetworkConfiguration::InternetAccessPoint;
                 ptr->bearerType = QNetworkConfiguration::BearerWLAN;
                 accessPointConfigurations.insert(id, ptr);
                 locker.unlock();
                 emit configurationAdded(ptr);
                 locker.relock();
             }
         }
         local_WlanFreeMemory(networkList);
     }
     local_WlanFreeMemory(interfaceList);
     while (!previous.isEmpty()) {
         QNetworkConfigurationPrivatePointer ptr =
             accessPointConfigurations.take(previous.takeFirst());
         locker.unlock();
         emit configurationRemoved(ptr);
         locker.relock();
     }
     locker.unlock();
     emit updateCompleted();
 }
sessionStateForId()
QNetworkSession::State QNativeWifiEngine::sessionStateForId (const QString & id) virtual
Implements QBearerEngineImpl.
Definition at line 535 of file qnativewifiengine.cpp.
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(id);
     if (!ptr)
         return QNetworkSession::Invalid;
     if (!ptr->isValid) {
         return QNetworkSession::Invalid;
     } else if ((ptr->state & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
         return QNetworkSession::Connected;
     } else if ((ptr->state & QNetworkConfiguration::Discovered) ==
                 QNetworkConfiguration::Discovered) {
         return QNetworkSession::Disconnected;
     } else if ((ptr->state & QNetworkConfiguration::Defined) == QNetworkConfiguration::Defined) {
         return QNetworkSession::NotAvailable;
     } else if ((ptr->state & QNetworkConfiguration::Undefined) ==
                 QNetworkConfiguration::Undefined) {
         return QNetworkSession::NotAvailable;
     }
     return QNetworkSession::Invalid;
 }
Properties
handle
Qt::HANDLE QNativeWifiEngine::handle private
Definition at line 101 of file qnativewifiengine.h.
Referenced by available(), closeHandle(), connectToId(), disconnectFromId(), getInterfaceFromId(), hasIdentifier(), requestUpdate(), and scanComplete().
The documentation for this class was generated from the following files:
/src/plugins/bearer/nativewifi/qnativewifiengine.h
/src/plugins/bearer/nativewifi/qnativewifiengine.cpp