Qt 4.8: QVGPaintEngine Class Reference
QVGPaintEngine Class Reference
#include <qpaintengine_vg_p.h>
Public Functions
bool begin (QPaintDevice *pdev)
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
void beginNativePainting ()
void brushChanged ()
void brushOriginChanged ()
void clip (const QVectorPath &path, Qt::ClipOperation op)
void clip (const QRect &rect, Qt::ClipOperation op)
void clip (const QRegion &region, Qt::ClipOperation op)
void clip (const QPainterPath &path, Qt::ClipOperation op)
void clipEnabledChanged ()
void compositionModeChanged ()
QPainterState * createState (QPainterState *orig) const
void draw (const QVectorPath &path)
bool drawCachedGlyphs (int numGlyphs, const glyph_t *glyphs, const QFont &font, QFontEngine *fontEngine, const QPointF &p, const QFixedPoint *positions)
void drawEllipse (const QRectF &r)
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
void drawEllipse (const QRect &r)
The default implementation of this function calls the floating point version of this function.
void drawImage (const QRectF &r, const QImage &pm, const QRectF &sr, Qt::ImageConversionFlags flags=Qt::AutoColor)
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
void drawImage (const QPointF &pos, const QImage &image)
void drawLines (const QLine *lines, int lineCount)
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
void drawLines (const QLineF *lines, int lineCount)
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
void drawPath (const QPainterPath &path)
The default implementation ignores the path and does nothing.
void drawPixmap (const QRectF &r, const QPixmap &pm, const QRectF &sr)
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
void drawPixmap (const QPointF &pos, const QPixmap &pm)
void drawPixmapFragments (const QPainter::PixmapFragment *drawingData, int dataCount, const QPixmap &pixmap, QFlags< QPainter::PixmapFragmentHint > hints)
void drawPoints (const QPointF *points, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPoints (const QPoint *points, int pointCount)
Draws the first pointCount points in the buffer points.
void drawPolygon (const QPointF *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawPolygon (const QPoint *points, int pointCount, PolygonDrawMode mode)
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
void drawRects (const QRect *rects, int rectCount)
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
void drawRects (const QRectF *rects, int rectCount)
Draws the first rectCount rectangles in the buffer rects.
void drawRoundedRect (const QRectF &rect, qreal xrad, qreal yrad, Qt::SizeMode mode)
void drawStaticTextItem (QStaticTextItem *staticTextItem)
void drawTextItem (const QPointF &p, const QTextItem &textItem)
This function draws the text item textItem at position p.
void drawTiledPixmap (const QRectF &r, const QPixmap &pixmap, const QPointF &s)
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
bool end ()
Reimplement this function to finish painting on the current paint device.
void endNativePainting ()
void fill (const QVectorPath &path, const QBrush &brush)
void fillRect (const QRectF &rect, const QBrush &brush)
void fillRect (const QRectF &rect, const QColor &color)
void fillRegion (const QRegion &region, const QColor &color, const QSize &surfaceSize)
void opacityChanged ()
void penChanged ()
QPixmapFilter * pixmapFilter (int type, const QPixmapFilter *prototype)
QVGPaintEngine ()
void renderHintsChanged ()
void setState (QPainterState *s)
QVGPainterState * state ()
const QVGPainterState * state () const
void stroke (const QVectorPath &path, const QPen &pen)
bool supportsTransformations (qreal, const QTransform &) const
void transformChanged ()
Type type () const
Reimplement this function to return the paint engine Type.
QVGPaintEnginePrivate * vgPrivate ()
~QVGPaintEngine ()
Public Functions inherited from QPaintEngineEx
virtual void drawPixmapFragments (const QPainter::PixmapFragment *fragments, int fragmentCount, const QPixmap &pixmap, QPainter::PixmapFragmentHints hints)
virtual void drawPixmapFragments (const QRectF *targetRects, const QRectF *sourceRects, int fragmentCount, const QPixmap &pixmap, QPainter::PixmapFragmentHints hints)
virtual uint flags () const
QPaintEngineEx ()
QPainterState * state ()
const QPainterState * state () const
virtual void sync ()
virtual void updateState (const QPaintEngineState &state)
Reimplement this function to update the state of a paint engine.
Public Functions inherited from QPaintEngine
void clearDirty (DirtyFlags df)
virtual QPoint coordinateOffset () const
Returns the offset from the painters origo to the engines origo.
void fix_neg_rect (int *x, int *y, int *w, int *h)
virtual HDC getDC () const
Empty default implementation.
bool hasFeature (PaintEngineFeatures feature) const
Returns true if the paint engine supports the specified feature; otherwise returns false.
bool isActive () const
Returns true if the paint engine is actively drawing; otherwise returns false.
bool isExtended () const
Returns true if the paint engine is a QPaintEngineEx derivative.
QPaintDevice * paintDevice () const
Returns the device that this engine is painting on, if painting is active; otherwise returns 0.
QPainter * painter () const
Returns the paint engine's painter.
QPaintEngine (PaintEngineFeatures features=0)
Creates a paint engine with the featureset specified by caps.
virtual void releaseDC (HDC hdc) const
Empty default implementation.
void setActive (bool newState)
Sets the active state of the paint engine to state.
void setDirty (DirtyFlags df)
void setPaintDevice (QPaintDevice *device)
void setSystemClip (const QRegion &baseClip)
Sets the system clip for this engine.
void setSystemRect (const QRect &rect)
Sets the target rect for drawing within the backing store.
void syncState ()
Updates all dirty states in this engine.
QRegion systemClip () const
Returns the system clip.
QRect systemRect () const
Retrieves the rect for drawing within the backing store.
bool testDirty (DirtyFlags df)
virtual ~QPaintEngine ()
Destroys the paint engine.
Protected Functions
QVGPaintEngine (QVGPaintEnginePrivate &data)
Protected Functions inherited from QPaintEngineEx
QPaintEngineEx (QPaintEngineExPrivate &data)
Protected Functions inherited from QPaintEngine
QPaintEngine (QPaintEnginePrivate &data, PaintEngineFeatures devcaps=0)
Private Functions
bool canVgWritePixels (const QImage &image) const
bool clearRect (const QRectF &rect, const QColor &color)
QRegion defaultClipRegion ()
bool isDefaultClipRect (const QRect &rect)
bool isDefaultClipRegion (const QRegion &region)
void restoreState (QPaintEngine::DirtyFlags dirty)
void updateScissor ()
Additional Inherited Members
Public Types inherited from QPaintEngineEx
enum Flags { DoNotEmulate = 0x01, IsEmulationEngine = 0x02 }
Public Types inherited from QPaintEngine
enum DirtyFlag {
DirtyPen = 0x0001, DirtyBrush = 0x0002, DirtyBrushOrigin = 0x0004, DirtyFont = 0x0008,
DirtyBackground = 0x0010, DirtyBackgroundMode = 0x0020, DirtyTransform = 0x0040, DirtyClipRegion = 0x0080,
DirtyClipPath = 0x0100, DirtyHints = 0x0200, DirtyCompositionMode = 0x0400, DirtyClipEnabled = 0x0800,
DirtyOpacity = 0x1000, AllDirty = 0xffff
}
QPaintEngine::updateState().
enum PaintEngineFeature {
PrimitiveTransform = 0x00000001, PatternTransform = 0x00000002, PixmapTransform = 0x00000004, PatternBrush = 0x00000008,
LinearGradientFill = 0x00000010, RadialGradientFill = 0x00000020, ConicalGradientFill = 0x00000040, AlphaBlend = 0x00000080,
PorterDuff = 0x00000100, PainterPaths = 0x00000200, Antialiasing = 0x00000400, BrushStroke = 0x00000800,
ConstantOpacity = 0x00001000, MaskedBrush = 0x00002000, PerspectiveTransform = 0x00004000, BlendModes = 0x00008000,
ObjectBoundingModeGradients = 0x00010000, RasterOpModes = 0x00020000, PaintOutsidePaintEvent = 0x20000000, AllFeatures = 0xffffffff
}
This enum is used to describe the features or capabilities that the paint engine has.
enum PolygonDrawMode { OddEvenMode, WindingMode, ConvexMode, PolylineMode }
enum Type {
X11, Windows, QuickDraw, CoreGraphics,
MacPrinter, QWindowSystem, PostScript, OpenGL,
Picture, SVG, Raster, Direct3D,
Pdf, OpenVG, OpenGL2, PaintBuffer,
Blitter, User = 50, MaxUser = 100
}
Protected Variables inherited from QPaintEngine
uint active: 1
QScopedPointer< QPaintEnginePrivate > d_ptr
uint extended: 1
PaintEngineFeatures gccaps
uint selfDestruct: 1
QPaintEngineState * state
Detailed Description
Definition at line 78 of file qpaintengine_vg_p.h.
Constructors and Destructors
QVGPaintEngine() [1/2]
QVGPaintEngine::QVGPaintEngine ()
Definition at line 1470 of file qpaintengine_vg.cpp.
     : QPaintEngineEx(*new QVGPaintEnginePrivate(this))
 {
 }
~QVGPaintEngine()
QVGPaintEngine::~QVGPaintEngine ()
Definition at line 1480 of file qpaintengine_vg.cpp.
 {
 }
QVGPaintEngine() [2/2]
QVGPaintEngine::QVGPaintEngine (QVGPaintEnginePrivate & data) protected
Definition at line 1475 of file qpaintengine_vg.cpp.
     : QPaintEngineEx(data)
 {
 }
Functions
begin()
bool QVGPaintEngine::begin (QPaintDevice * pdev) virtual
Reimplement this function to initialise your paint engine when painting is to start on the paint device pdev.
Return true if the initialization was successful; otherwise return false.
See also
end() isActive()
Implements QPaintEngine.
Definition at line 1539 of file qpaintengine_vg.cpp.
 {
     Q_UNUSED(pdev);
     Q_D(QVGPaintEngine);
     // Initialize the VG painting objects if we haven't done it yet.
     if (!d->penPaint)
         d->initObjects();
     // The initial clip region is the entire device area.
     QVGPainterState *s = state();
     s->clipRegion = defaultClipRegion();
     // Initialize the VG state for this paint operation.
     restoreState(QPaintEngine::AllDirty);
     d->dirty = 0;
     d->rawVG = false;
     return true;
 }
beginNativePainting()
void QVGPaintEngine::beginNativePainting () virtual
Reimplemented from QPaintEngineEx.
Definition at line 3853 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     // About to enter raw VG mode: flush pending changes and make
     // sure that all matrices are set to the current transformation.
     QVGPainterState *s = this->state();
     d->ensurePen(s->pen);
     d->ensureBrush(s->brush);
     d->ensurePathTransform();
     d->setTransform(VG_MATRIX_IMAGE_USER_TO_SURFACE, d->imageTransform);
 #if !defined(QVG_NO_DRAW_GLYPHS)
     d->setTransform(VG_MATRIX_GLYPH_USER_TO_SURFACE, d->pathTransform);
 #endif
     vgSeti(VG_SCISSORING, VG_FALSE);
     vgSeti(VG_MASKING, VG_FALSE);
     d->rawVG = true;
 }
brushChanged()
void QVGPaintEngine::brushChanged () virtual
Implements QPaintEngineEx.
Definition at line 2418 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyBrush;
     d->hasExtendedRadialGradientPen = d->needsEmulation(state()->brush);
 }
brushOriginChanged()
void QVGPaintEngine::brushOriginChanged () virtual
Implements QPaintEngineEx.
Definition at line 2426 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyBrushOrigin;
     d->brushOrigin = state()->brushOrigin;
     d->forcePenChange = true;
     d->forceBrushChange = true;
 }
canVgWritePixels()
bool QVGPaintEngine::canVgWritePixels (const QImage & image) const private
Definition at line 3303 of file qpaintengine_vg.cpp.
Referenced by drawImage().
 {
     Q_D(const QVGPaintEngine);
     // qt_vg_image_to_vg_format returns VG_sARGB_8888 as
     // fallback case if no matching VG format is found.
     // If given image format is not Format_ARGB32 and returned
     // format is VG_sARGB_8888, it means that no match was
     // found. In that case vgWritePixels cannot be used.
     // Also 1-bit formats cannot be used directly either.
     if ((image.format() != QImage::Format_ARGB32
            && qt_vg_image_to_vg_format(image.format()) == VG_sARGB_8888)
            || image.depth() == 1) {
         return false;
     }
     // vgWritePixels ignores masking, blending and xforms so we can only use it if
     // ALL of the following conditions are true:
     // - It is a simple translate, or a scale of -1 on the y-axis (inverted)
     // - The opacity is totally opaque
     // - The composition mode is "source" OR "source over" provided the image is opaque
     return ( d->imageTransform.type() <= QTransform::TxScale
             && d->imageTransform.m11() == 1.0 && qAbs(d->imageTransform.m22()) == 1.0)
             && d->opacity == 1.0f
             && (d->blendMode == VG_BLEND_SRC || (d->blendMode == VG_BLEND_SRC_OVER &&
                                                 !image.hasAlphaChannel()));
 }
clearRect()
bool QVGPaintEngine::clearRect (const QRectF & rect, const QColor & color) private
Definition at line 2564 of file qpaintengine_vg.cpp.
Referenced by fillRect().
 {
     Q_D(QVGPaintEngine);
     QVGPainterState *s = state();
     if (!s->clipEnabled || s->clipOperation == Qt::NoClip) {
         QRect r = d->transform.mapRect(rect).toRect();
         int height = paintDevice()->height();
         if (d->clearColor != color || d->clearOpacity != s->opacity) {
             VGfloat values[4];
             values[0] = color.redF();
             values[1] = color.greenF();
             values[2] = color.blueF();
             values[3] = color.alphaF() * s->opacity;
             vgSetfv(VG_CLEAR_COLOR, 4, values);
             d->clearColor = color;
             d->clearOpacity = s->opacity;
         }
         vgClear(r.x(), height - r.y() - r.height(),
                 r.width(), r.height());
         return true;
     }
     return false;
 }
clip() [1/4]
void QVGPaintEngine::clip (const QVectorPath & path, Qt::ClipOperation op) virtual
Implements QPaintEngineEx.
Definition at line 1795 of file qpaintengine_vg.cpp.
Referenced by clip(), and clipTransformIsSimple().
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyClipRegion;
     if (op == Qt::NoClip) {
         d->maskValid = false;
         d->maskIsSet = true;
         d->scissorMask = false;
         d->maskRect = QRect();
         vgSeti(VG_MASKING, VG_FALSE);
         return;
     }
     // We don't have vgRenderToMask(), so handle simple QRectF's only.
     if (path.shape() == QVectorPath::RectangleHint &&
             path.elementCount() == 4 && clipTransformIsSimple(d->transform)) {
         // Clipping region that resulted from QPainter::setClipRect(QRectF).
         // Convert it into a QRect and apply.
         const qreal *points = path.points();
         QRectF rect(points[0], points[1], points[2] - points[0],
                     points[5] - points[1]);
         clip(rect.toRect(), op);
         return;
     }
 #if !defined(QVG_NO_RENDER_TO_MASK)
     QPaintDevice *pdev = paintDevice();
     int width = pdev->width();
     int height = pdev->height();
     if (op == Qt::ReplaceClip) {
         vgMask(VG_INVALID_HANDLE, VG_CLEAR_MASK, 0, 0, width, height);
         d->maskRect = QRect();
     } else if (!d->maskValid) {
         d->ensureMask(this, width, height);
     }
     d->ensurePathTransform();
     VGPath vgpath = d->vectorPathToVGPath(path);
     switch (op) {
         case Qt::ReplaceClip:
         case Qt::UniteClip:
             vgRenderToMask(vgpath, VG_FILL_PATH, VG_UNION_MASK);
             break;
         case Qt::IntersectClip:
             vgRenderToMask(vgpath, VG_FILL_PATH, VG_INTERSECT_MASK);
             break;
         default: break;
     }
     vgDestroyPath(vgpath);
     vgSeti(VG_MASKING, VG_TRUE);
     d->maskValid = true;
     d->maskIsSet = false;
     d->scissorMask = false;
 #endif
 }
clip() [2/4]
void QVGPaintEngine::clip (const QRect & rect, Qt::ClipOperation op) virtual
Reimplemented from QPaintEngineEx.
Definition at line 1857 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyClipRegion;
     // If we have a non-simple transform, then use path-based clipping.
     if (op != Qt::NoClip && !clipTransformIsSimple(d->transform)) {
         QPaintEngineEx::clip(rect, op);
         return;
     }
     switch (op) {
         case Qt::NoClip:
         {
             d->maskValid = false;
             d->maskIsSet = true;
             d->scissorMask = false;
             d->maskRect = QRect();
             vgSeti(VG_MASKING, VG_FALSE);
         }
         break;
         case Qt::ReplaceClip:
         {
             QRect r = d->transform.mapRect(rect);
             if (isDefaultClipRect(r)) {
                 // Replacing the clip with a full-window region is the
                 // same as turning off clipping.
                 if (d->maskValid)
                     vgSeti(VG_MASKING, VG_FALSE);
                 d->maskValid = false;
                 d->maskIsSet = true;
                 d->scissorMask = false;
                 d->maskRect = QRect();
             } else {
                 // Special case: if the intersection of the system
                 // clip and "r" is a single rectangle, then use the
                 // scissor for clipping.  We try to avoid allocating a
                 // QRegion copy on the heap for the test if we can.
                 QRegion clip = d->systemClip; // Reference-counted, no alloc.
                 QRect clipRect;
                 if (clip.rectCount() == 1) {
                     clipRect = clip.boundingRect().intersected(r);
                 } else if (clip.isEmpty()) {
                     clipRect = r;
                 } else {
                     clip = clip.intersect(r);
                     if (clip.rectCount() != 1) {
                         d->maskValid = false;
                         d->maskIsSet = false;
                         d->scissorMask = false;
                         d->maskRect = QRect();
                         d->modifyMask(this, VG_FILL_MASK, r);
                         break;
                     }
                     clipRect = clip.boundingRect();
                 }
                 d->maskValid = false;
                 d->maskIsSet = false;
                 d->scissorMask = true;
                 d->maskRect = clipRect;
                 vgSeti(VG_MASKING, VG_FALSE);
                 updateScissor();
             }
         }
         break;
         case Qt::IntersectClip:
         {
             QRect r = d->transform.mapRect(rect);
             if (!d->maskValid) {
                 // Mask has not been used yet, so intersect with
                 // the previous scissor-based region in maskRect.
                 if (d->scissorMask)
                     r = r.intersect(d->maskRect);
                 if (isDefaultClipRect(r)) {
                     // The clip is the full window, so turn off clipping.
                     d->maskIsSet = true;
                     d->maskRect = QRect();
                 } else {
                     // Activate the scissor on a smaller maskRect.
                     d->maskIsSet = false;
                     d->maskRect = r;
                 }
                 d->scissorMask = true;
                 updateScissor();
             } else if (d->maskIsSet && isDefaultClipRect(r)) {
                 // Intersecting a full-window clip with a full-window
                 // region is the same as turning off clipping.
                 if (d->maskValid)
                     vgSeti(VG_MASKING, VG_FALSE);
                 d->maskValid = false;
                 d->maskIsSet = true;
                 d->scissorMask = false;
                 d->maskRect = QRect();
             } else {
                 d->modifyMask(this, VG_INTERSECT_MASK, r);
             }
         }
         break;
         case Qt::UniteClip:
         {
             // If we already have a full-window clip, then uniting a
             // region with it will do nothing.  Otherwise union.
             if (!(d->maskIsSet))
                 d->modifyMask(this, VG_UNION_MASK, d->transform.mapRect(rect));
         }
         break;
     }
 }
clip() [3/4]
void QVGPaintEngine::clip (const QRegion & region, Qt::ClipOperation op) virtual
Reimplemented from QPaintEngineEx.
Definition at line 1970 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     // Use the QRect case if the region consists of a single rectangle.
     if (region.rectCount() == 1) {
         clip(region.boundingRect(), op);
         return;
     }
     d->dirty |= QPaintEngine::DirtyClipRegion;
     // If we have a non-simple transform, then use path-based clipping.
     if (op != Qt::NoClip && !clipTransformIsSimple(d->transform)) {
         QPaintEngineEx::clip(region, op);
         return;
     }
     switch (op) {
         case Qt::NoClip:
         {
             d->maskValid = false;
             d->maskIsSet = true;
             d->scissorMask = false;
             d->maskRect = QRect();
             vgSeti(VG_MASKING, VG_FALSE);
         }
         break;
         case Qt::ReplaceClip:
         {
             QRegion r = d->transform.map(region);
             if (isDefaultClipRegion(r)) {
                 // Replacing the clip with a full-window region is the
                 // same as turning off clipping.
                 if (d->maskValid)
                     vgSeti(VG_MASKING, VG_FALSE);
                 d->maskValid = false;
                 d->maskIsSet = true;
                 d->scissorMask = false;
                 d->maskRect = QRect();
             } else {
                 // Special case: if the intersection of the system
                 // clip and the region is a single rectangle, then
                 // use the scissor for clipping.
                 QRegion clip = d->systemClip;
                 if (clip.isEmpty())
                     clip = r;
                 else
                     clip = clip.intersect(r);
                 if (clip.rectCount() == 1) {
                     d->maskValid = false;
                     d->maskIsSet = false;
                     d->scissorMask = true;
                     d->maskRect = clip.boundingRect();
                     vgSeti(VG_MASKING, VG_FALSE);
                     updateScissor();
                 } else {
                     d->maskValid = false;
                     d->maskIsSet = false;
                     d->scissorMask = false;
                     d->maskRect = QRect();
                     d->modifyMask(this, VG_FILL_MASK, r);
                 }
             }
         }
         break;
         case Qt::IntersectClip:
         {
             if (region.rectCount() != 1) {
                 // If there is more than one rectangle, then intersecting
                 // the rectangles one by one in modifyMask() will not give
                 // the desired result.  So fall back to path-based clipping.
                 QPaintEngineEx::clip(region, op);
                 return;
             }
             QRegion r = d->transform.map(region);
             if (d->maskIsSet && isDefaultClipRegion(r)) {
                 // Intersecting a full-window clip with a full-window
                 // region is the same as turning off clipping.
                 if (d->maskValid)
                     vgSeti(VG_MASKING, VG_FALSE);
                 d->maskValid = false;
                 d->maskIsSet = true;
                 d->scissorMask = false;
                 d->maskRect = QRect();
             } else {
                 d->modifyMask(this, VG_INTERSECT_MASK, r);
             }
         }
         break;
         case Qt::UniteClip:
         {
             // If we already have a full-window clip, then uniting a
             // region with it will do nothing.  Otherwise union.
             if (!(d->maskIsSet))
                 d->modifyMask(this, VG_UNION_MASK, d->transform.map(region));
         }
         break;
     }
 }
clip() [4/4]
void QVGPaintEngine::clip (const QPainterPath & path, Qt::ClipOperation op) virtual
Reimplemented from QPaintEngineEx.
Definition at line 2117 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_RENDER_TO_MASK)
     Q_D(QVGPaintEngine);
     // If the path is a simple rectangle, then use clip(QRect) instead.
     QRectF simpleRect;
     if (qt_vg_pathToRect(path, &simpleRect)) {
         clip(simpleRect.toRect(), op);
         return;
     }
     d->dirty |= QPaintEngine::DirtyClipRegion;
     if (op == Qt::NoClip) {
         d->maskValid = false;
         d->maskIsSet = true;
         d->scissorMask = false;
         d->maskRect = QRect();
         vgSeti(VG_MASKING, VG_FALSE);
         return;
     }
     QPaintDevice *pdev = paintDevice();
     int width = pdev->width();
     int height = pdev->height();
     if (op == Qt::ReplaceClip) {
         vgMask(VG_INVALID_HANDLE, VG_CLEAR_MASK, 0, 0, width, height);
         d->maskRect = QRect();
     } else if (!d->maskValid) {
         d->ensureMask(this, width, height);
     }
     d->ensurePathTransform();
     VGPath vgpath = d->painterPathToVGPath(path);
     switch (op) {
         case Qt::ReplaceClip:
         case Qt::UniteClip:
             vgRenderToMask(vgpath, VG_FILL_PATH, VG_UNION_MASK);
             break;
         case Qt::IntersectClip:
             vgRenderToMask(vgpath, VG_FILL_PATH, VG_INTERSECT_MASK);
             break;
         default: break;
     }
     vgDestroyPath(vgpath);
     vgSeti(VG_MASKING, VG_TRUE);
     d->maskValid = true;
     d->maskIsSet = false;
     d->scissorMask = false;
 #else
     QPaintEngineEx::clip(path, op);
 #endif
 }
clipEnabledChanged()
void QVGPaintEngine::clipEnabledChanged () virtual
Implements QPaintEngineEx.
Definition at line 2380 of file qpaintengine_vg.cpp.
 {
 #if defined(QVG_SCISSOR_CLIP)
     vgSeti(VG_MASKING, VG_FALSE); // disable mask fallback
     updateScissor();
 #else
     Q_D(QVGPaintEngine);
     QVGPainterState *s = state();
     d->dirty |= QPaintEngine::DirtyClipEnabled;
     if (s->clipEnabled && s->clipOperation != Qt::NoClip) {
         // Replay the entire clip stack to put the mask into the right state.
         d->maskValid = false;
         d->maskIsSet = true;
         d->scissorMask = false;
         d->maskRect = QRect();
         s->clipRegion = defaultClipRegion();
         d->replayClipOperations();
         d->transform = s->transform();
         d->updateTransform(paintDevice());
     } else {
         vgSeti(VG_MASKING, VG_FALSE);
         d->maskValid = false;
         d->maskIsSet = false;
         d->scissorMask = false;
         d->maskRect = QRect();
     }
 #endif
 }
compositionModeChanged()
void QVGPaintEngine::compositionModeChanged () virtual
Implements QPaintEngineEx.
Definition at line 2444 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyCompositionMode;
     VGint vgMode = VG_BLEND_SRC_OVER;
     switch (state()->composition_mode) {
     case QPainter::CompositionMode_SourceOver:
         vgMode = VG_BLEND_SRC_OVER;
         break;
     case QPainter::CompositionMode_DestinationOver:
         vgMode = VG_BLEND_DST_OVER;
         break;
     case QPainter::CompositionMode_Source:
         vgMode = VG_BLEND_SRC;
         break;
     case QPainter::CompositionMode_SourceIn:
         vgMode = VG_BLEND_SRC_IN;
         break;
     case QPainter::CompositionMode_DestinationIn:
         vgMode = VG_BLEND_DST_IN;
         break;
     case QPainter::CompositionMode_Plus:
         vgMode = VG_BLEND_ADDITIVE;
         break;
     case QPainter::CompositionMode_Multiply:
         vgMode = VG_BLEND_MULTIPLY;
         break;
     case QPainter::CompositionMode_Screen:
         vgMode = VG_BLEND_SCREEN;
         break;
     case QPainter::CompositionMode_Darken:
         vgMode = VG_BLEND_DARKEN;
         break;
     case QPainter::CompositionMode_Lighten:
         vgMode = VG_BLEND_LIGHTEN;
         break;
     default:
         if (d->hasAdvancedBlending) {
             switch (state()->composition_mode) {
             case QPainter::CompositionMode_Overlay:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_OVERLAY_KHR;
                 break;
             case QPainter::CompositionMode_ColorDodge:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_COLORDODGE_KHR;
                 break;
             case QPainter::CompositionMode_ColorBurn:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_COLORBURN_KHR;
                 break;
             case QPainter::CompositionMode_HardLight:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_HARDLIGHT_KHR;
                 break;
             case QPainter::CompositionMode_SoftLight:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_SOFTLIGHT_KHR;
                 break;
             case QPainter::CompositionMode_Difference:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_DIFFERENCE_KHR;
                 break;
             case QPainter::CompositionMode_Exclusion:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_EXCLUSION_KHR;
                 break;
             case QPainter::CompositionMode_SourceOut:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_SRC_OUT_KHR;
                 break;
             case QPainter::CompositionMode_DestinationOut:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_DST_OUT_KHR;
                 break;
             case QPainter::CompositionMode_SourceAtop:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_SRC_ATOP_KHR;
                 break;
             case QPainter::CompositionMode_DestinationAtop:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_DST_ATOP_KHR;
                 break;
             case QPainter::CompositionMode_Xor:
                 vgMode = QVGPaintEnginePrivate::QT_VG_BLEND_XOR_KHR;
                 break;
             default: break; // Fall back to VG_BLEND_SRC_OVER.
             }
         }
         if (vgMode == VG_BLEND_SRC_OVER)
             qWarning() << "QVGPaintEngine::compositionModeChanged unsupported mode" << state()->composition_mode;
         break;
     }
     d->setBlendMode(VGBlendMode(vgMode));
 }
createState()
QPainterState * QVGPaintEngine::createState (QPainterState * orig) const virtual
Reimplemented from QPaintEngineEx.
Definition at line 1484 of file qpaintengine_vg.cpp.
 {
     if (!orig) {
         return new QVGPainterState();
     } else {
         Q_D(const QVGPaintEngine);
         QVGPaintEnginePrivate *d2 = const_cast<QVGPaintEnginePrivate*>(d);
         QVGPainterState *origState = static_cast<QVGPainterState *>(orig);
         origState->savedDirty = d2->dirty;
         d2->dirty = 0;
         return new QVGPainterState(*origState);
     }
 }
defaultClipRegion()
QRegion QVGPaintEngine::defaultClipRegion () private
Definition at line 2349 of file qpaintengine_vg.cpp.
Referenced by begin(), clipEnabledChanged(), and clipTransformIsSimple().
 {
     // The default clip region for a paint device is the whole drawing area.
     QPaintDevice *pdev = paintDevice();
     return QRegion(0, 0, pdev->width(), pdev->height());
 }
draw()
void QVGPaintEngine::draw (const QVectorPath & path) virtual
Reimplemented from QPaintEngineEx.
Definition at line 1566 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::draw(path);
         return;
     }
     QVGPainterState *s = state();
     VGPath vgpath = d->vectorPathToVGPath(path);
     if (!path.hasWindingFill())
         d->draw(vgpath, s->pen, s->brush, VG_EVEN_ODD);
     else
         d->draw(vgpath, s->pen, s->brush, VG_NON_ZERO);
     vgDestroyPath(vgpath);
 }
drawCachedGlyphs()
bool QVGPaintEngine::drawCachedGlyphs (int numGlyphs, const glyph_t * glyphs, const QFont & font, QFontEngine * fontEngine, const QPointF & p, const QFixedPoint * positions)
Definition at line 3743 of file qpaintengine_vg.cpp.
  {
 #if !defined(QVG_NO_DRAW_GLYPHS)
     Q_D(QVGPaintEngine);
     // Find the glyph cache for this font.
     QVGFontCache::ConstIterator it = d->fontCache.constFind(fontEngine);
     QVGFontGlyphCache *glyphCache;
     if (it != d->fontCache.constEnd()) {
         glyphCache = it.value();
     } else {
 #ifdef Q_OS_SYMBIAN
         glyphCache = new QSymbianVGFontGlyphCache();
 #else
         glyphCache = new QVGFontGlyphCache();
 #endif
         if (glyphCache->font == VG_INVALID_HANDLE) {
             qWarning("QVGPaintEngine::drawTextItem: OpenVG fonts are not supported by the OpenVG engine");
             delete glyphCache;
             return false;
         }
         glyphCache->setScaleFromText(font, fontEngine);
         d->fontCache.insert(fontEngine, glyphCache);
         if (!d->fontEngineCleaner)
             d->fontEngineCleaner = new QVGFontEngineCleaner(d);
         QObject::connect(fontEngine, SIGNAL(destroyed()),
                          d->fontEngineCleaner, SLOT(fontEngineDestroyed()));
     }
     // Set the transformation to use for drawing the current glyphs.
     QTransform glyphTransform(d->pathTransform);
     if (d->transform.type() <= QTransform::TxTranslate) {
         // Prevent blurriness of unscaled, unrotated text by forcing integer coordinates.
         glyphTransform.translate(
                 floor(p.x() + glyphTransform.dx() + aliasedCoordinateDelta) - glyphTransform.dx(),
                 floor(p.y() - glyphTransform.dy() + aliasedCoordinateDelta) + glyphTransform.dy());
     } else {
         glyphTransform.translate(p.x(), p.y());
     }
 #if defined(QVG_NO_IMAGE_GLYPHS)
     glyphTransform.scale(glyphCache->scaleX, glyphCache->scaleY);
 #endif
     // Some glyph caches can create the VGImage upright
     if (glyphCache->invertedGlyphs)
         glyphTransform.scale(1, -1);
     d->setTransform(VG_MATRIX_GLYPH_USER_TO_SURFACE, glyphTransform);
     // Add the glyphs from the text item into the glyph cache.
     glyphCache->cacheGlyphs(d, fontEngine, glyphs, numGlyphs);
     // Create the array of adjustments between glyphs
     QVarLengthArray<VGfloat> adjustments_x(numGlyphs);
     QVarLengthArray<VGfloat> adjustments_y(numGlyphs);
     for (int i = 1; i < numGlyphs; ++i) {
         adjustments_x[i-1] = (positions[i].x - positions[i-1].x).round().toReal();
         adjustments_y[i-1] = (positions[i].y - positions[i-1].y).round().toReal();
     }
     // Set the glyph drawing origin.
     VGfloat origin[2];
     origin[0] = positions[0].x.round().toReal();
     origin[1] = positions[0].y.round().toReal();
     vgSetfv(VG_GLYPH_ORIGIN, 2, origin);
     // Fast anti-aliasing for paths, better for images.
 #if !defined(QVG_NO_IMAGE_GLYPHS)
     d->setImageQuality(VG_IMAGE_QUALITY_BETTER);
     d->setImageMode(VG_DRAW_IMAGE_STENCIL);
 #else
     d->setRenderingQuality(VG_RENDERING_QUALITY_FASTER);
 #endif
     // Draw the glyphs.  We need to fill with the brush associated with
     // the Qt pen, not the Qt brush.
     d->ensureBrush(state()->pen.brush());
     vgDrawGlyphs(glyphCache->font, numGlyphs, (VGuint*)glyphs,
                  adjustments_x.data(), adjustments_y.data(), VG_FILL_PATH, VG_TRUE);
     return true;
 #else
     Q_UNUSED(numGlyphs);
     Q_UNUSED(glyphs);
     Q_UNUSED(font);
     Q_UNUSED(fontEngine);
     Q_UNUSED(p);
     Q_UNUSED(positions);
     return false;
 #endif
 }
drawEllipse() [1/2]
void QVGPaintEngine::drawEllipse (const QRectF & rect) virtual
Reimplement this function to draw the largest ellipse that can be contained within rectangle rect.
The default implementation calls drawPolygon().
Reimplemented from QPaintEngineEx.
Definition at line 2851 of file qpaintengine_vg.cpp.
Referenced by drawEllipse().
 {
     // Based on the description of vguEllipse() in the OpenVG specification.
     // We don't use vguEllipse(), to avoid unnecessary library dependencies.
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawEllipse(r);
         return;
     }
     if (d->simpleTransform) {
         QVGPainterState *s = state();
         VGPath path = vgCreatePath(VG_PATH_FORMAT_STANDARD,
                                    VG_PATH_DATATYPE_F,
                                    1.0f, // scale
                                    0.0f, // bias
                                    4,    // segmentCapacityHint
                                    12,   // coordCapacityHint
                                    VG_PATH_CAPABILITY_ALL);
         static VGubyte segments[4] = {
             VG_MOVE_TO_ABS,
             VG_SCCWARC_TO_REL,
             VG_SCCWARC_TO_REL,
             VG_CLOSE_PATH
         };
         VGfloat coords[12];
         VGfloat halfwid = r.width() / 2;
         VGfloat halfht = r.height() / 2;
         coords[0]  = r.x() + r.width();
         coords[1]  = r.y() + halfht;
         coords[2]  = halfwid;
         coords[3]  = halfht;
         coords[4]  = 0.0f;
         coords[5]  = -r.width();
         coords[6]  = 0.0f;
         coords[7]  = halfwid;
         coords[8]  = halfht;
         coords[9]  = 0.0f;
         coords[10] = r.width();
         coords[11] = 0.0f;
         vgAppendPathData(path, 4, segments, coords);
         d->draw(path, s->pen, s->brush);
         vgDestroyPath(path);
     } else {
         // The projective transform version of an ellipse is difficult.
         // Generate a QVectorPath containing cubic curves and transform that.
         QPaintEngineEx::drawEllipse(r);
     }
 }
drawEllipse() [2/2]
void QVGPaintEngine::drawEllipse (const QRect & r) virtual
The default implementation of this function calls the floating point version of this function.
Reimplemented from QPaintEngineEx.
Definition at line 2900 of file qpaintengine_vg.cpp.
 {
     drawEllipse(QRectF(r));
 }
drawImage() [1/2]
void QVGPaintEngine::drawImage (const QRectF & r, const QImage & pm, const QRectF & sr, Qt::ImageConversionFlags flags = Qt::AutoColor) virtual
Reimplement this function to draw the part of the image specified by the sr rectangle in the given rectangle using the given conversion flags flags, to convert it to a pixmap.
Implements QPaintEngineEx.
Definition at line 3384 of file qpaintengine_vg.cpp.
Referenced by drawPixmap().
 {
     Q_D(QVGPaintEngine);
     if (image.isNull())
         return;
     VGImage vgImg;
     if (d->simpleTransform || d->opacity == 1.0f)
         vgImg = toVGImageSubRect(image, sr.toRect(), flags);
     else
         vgImg = toVGImageWithOpacitySubRect(image, d->opacity, sr.toRect());
     if (vgImg != VG_INVALID_HANDLE) {
         if (r.size() == sr.size()) {
             drawVGImage(d, r.topLeft(), vgImg);
         } else {
             drawVGImage(d, r, vgImg, sr.size().toSize(),
                         QRectF(QPointF(0, 0), sr.size()));
         }
     } else {
         if (canVgWritePixels(image) && (r.size() == sr.size()) && !flags) {
             // Optimization for straight blits, no blending
             int x = sr.x();
             int y = sr.y();
             int bpp = image.depth() >> 3; // bytes
             int offset = 0;
             int bpl = image.bytesPerLine();
             if (d->imageTransform.m22() < 0) {
                 // inverted
                 offset = ((y + sr.height()) * bpl) - ((image.width() - x) * bpp);
                 bpl = -bpl;
             } else {
                 offset = (y * bpl) + (x * bpp);
             }
             const uchar *bits = image.constBits() + offset;
             QPointF mapped = d->imageTransform.map(r.topLeft());
             vgWritePixels(bits, bpl, qt_vg_image_to_vg_format(image.format()),
                         mapped.x(), mapped.y() - sr.height(), r.width(), r.height());
             return;
         } else {
             // Monochrome images need to use the vgChildImage() path.
             vgImg = toVGImage(image, flags);
             if (vgImg == VG_INVALID_HANDLE)
                 drawImageTiled(d, r, image, sr);
             else
                 drawVGImage(d, r, vgImg, image.size(), sr);
         }
     }
     vgDestroyImage(vgImg);
 }
drawImage() [2/2]
void QVGPaintEngine::drawImage (const QPointF & pos, const QImage & image) virtual
Reimplemented from QPaintEngineEx.
Definition at line 3435 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     if (image.isNull())
         return;
     VGImage vgImg;
     if (canVgWritePixels(image)) {
         // Optimization for straight blits, no blending
         bool inverted = (d->imageTransform.m22() < 0);
         const uchar *bits = inverted ? image.constBits() + image.byteCount() - image.bytesPerLine() : image.constBits();
         int bpl = inverted ? -image.bytesPerLine() : image.bytesPerLine();
         QPointF mapped = d->imageTransform.map(pos);
         vgWritePixels(bits, bpl, qt_vg_image_to_vg_format(image.format()),
                              mapped.x(), mapped.y() - image.height(), image.width(), image.height());
         return;
     } else if (d->simpleTransform || d->opacity == 1.0f) {
         vgImg = toVGImage(image);
     } else {
         vgImg = toVGImageWithOpacity(image, d->opacity);
     }
     if (vgImg == VG_INVALID_HANDLE)
         drawImageTiled(d, QRectF(pos, image.size()), image);
     else
         drawVGImage(d, pos, vgImg);
     vgDestroyImage(vgImg);
 }
drawLines() [1/2]
void QVGPaintEngine::drawLines (const QLine * lines, int lineCount) virtual
The default implementation converts the first lineCount lines in lines to a QLineF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngineEx.
Definition at line 2787 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_MODIFY_PATH)
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawLines(lines, lineCount);
         return;
     }
     QVGPainterState *s = state();
     for (int i = 0; i < lineCount; ++i, ++lines) {
         VGfloat coords[4];
         if (d->simpleTransform) {
             coords[0] = lines->x1();
             coords[1] = lines->y1();
             coords[2] = lines->x2();
             coords[3] = lines->y2();
         } else {
             QPointF p1 = d->transform.map(QPointF(lines->x1(), lines->y1()));
             QPointF p2 = d->transform.map(QPointF(lines->x2(), lines->y2()));
             coords[0] = p1.x();
             coords[1] = p1.y();
             coords[2] = p2.x();
             coords[3] = p2.y();
         }
         vgModifyPathCoords(d->linePath, 0, 2, coords);
         d->stroke(d->linePath, s->pen);
     }
 #else
     QPaintEngineEx::drawLines(lines, lineCount);
 #endif
 }
drawLines() [2/2]
void QVGPaintEngine::drawLines (const QLineF * lines, int lineCount) virtual
The default implementation splits the list of lines in lines into lineCount separate calls to drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngineEx.
Definition at line 2819 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_MODIFY_PATH)
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawLines(lines, lineCount);
         return;
     }
     QVGPainterState *s = state();
     for (int i = 0; i < lineCount; ++i, ++lines) {
         VGfloat coords[4];
         if (d->simpleTransform) {
             coords[0] = lines->x1();
             coords[1] = lines->y1();
             coords[2] = lines->x2();
             coords[3] = lines->y2();
         } else {
             QPointF p1 = d->transform.map(lines->p1());
             QPointF p2 = d->transform.map(lines->p2());
             coords[0] = p1.x();
             coords[1] = p1.y();
             coords[2] = p2.x();
             coords[3] = p2.y();
         }
         vgModifyPathCoords(d->linePath, 0, 2, coords);
         d->stroke(d->linePath, s->pen);
     }
 #else
     QPaintEngineEx::drawLines(lines, lineCount);
 #endif
 }
drawPath()
void QVGPaintEngine::drawPath (const QPainterPath & path) virtual
The default implementation ignores the path and does nothing.
Reimplemented from QPaintEngineEx.
Definition at line 2905 of file qpaintengine_vg.cpp.
 {
     // Shortcut past the QPainterPath -> QVectorPath conversion,
     // converting the QPainterPath directly into a VGPath.
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawPath(path);
         return;
     }
     QVGPainterState *s = state();
     VGPath vgpath = d->painterPathToVGPath(path);
     if (path.fillRule() == Qt::OddEvenFill)
         d->draw(vgpath, s->pen, s->brush, VG_EVEN_ODD);
     else
         d->draw(vgpath, s->pen, s->brush, VG_NON_ZERO);
     vgDestroyPath(vgpath);
 }
drawPixmap() [1/2]
void QVGPaintEngine::drawPixmap (const QRectF & r, const QPixmap & pm, const QRectF & sr) virtual
Reimplement this function to draw the part of the pm specified by the sr rectangle in the given r.
Implements QPaintEngineEx.
Definition at line 3331 of file qpaintengine_vg.cpp.
 {
     QPixmapData *pd = pm.pixmapData();
     if (!pd)
         return; // null QPixmap
     if (pd->classId() == QPixmapData::OpenVGClass) {
         Q_D(QVGPaintEngine);
         QVGPixmapData *vgpd = static_cast<QVGPixmapData *>(pd);
         if (!vgpd->isValid())
             return;
         if (d->simpleTransform)
             drawVGImage(d, r, vgpd->toVGImage(), vgpd->size(), sr);
         else
             drawVGImage(d, r, vgpd->toVGImage(d->opacity), vgpd->size(), sr);
         if (vgpd->vgImage != VG_INVALID_HANDLE)
             return;
         vgpd->source.beginDataAccess();
         drawImage(r, vgpd->source.imageRef(), sr, Qt::AutoColor);
         vgpd->source.endDataAccess(true);
     } else {
         drawImage(r, *(pd->buffer()), sr, Qt::AutoColor);
     }
 }
drawPixmap() [2/2]
void QVGPaintEngine::drawPixmap (const QPointF & pos, const QPixmap & pm) virtual
Reimplemented from QPaintEngineEx.
Definition at line 3357 of file qpaintengine_vg.cpp.
 {
     QPixmapData *pd = pm.pixmapData();
     if (!pd)
         return; // null QPixmap
     if (pd->classId() == QPixmapData::OpenVGClass) {
         Q_D(QVGPaintEngine);
         QVGPixmapData *vgpd = static_cast<QVGPixmapData *>(pd);
         if (!vgpd->isValid())
             return;
         if (d->simpleTransform)
             drawVGImage(d, pos, vgpd->toVGImage());
         else
             drawVGImage(d, pos, vgpd->toVGImage(d->opacity));
         if (vgpd->vgImage != VG_INVALID_HANDLE)
             return;
         vgpd->source.beginDataAccess();
         drawImage(pos, vgpd->source.imageRef());
         vgpd->source.endDataAccess(true);
     } else {
         drawImage(pos, *(pd->buffer()));
     }
 }
drawPixmapFragments()
void QVGPaintEngine::drawPixmapFragments (const QPainter::PixmapFragment * drawingData, int dataCount, const QPixmap & pixmap, QFlags< QPainter::PixmapFragmentHint > hints)
Definition at line 3476 of file qpaintengine_vg.cpp.
 {
 #if !defined(QT_SHIVAVG)
     Q_D(QVGPaintEngine);
     // If the pixmap is not VG, or the transformation is projective,
     // then fall back to the default implementation.
     QPixmapData *pd = pixmap.pixmapData();
     if (!pd)
         return; // null QPixmap
     if (pd->classId() != QPixmapData::OpenVGClass || !d->simpleTransform) {
         QPaintEngineEx::drawPixmapFragments(drawingData, dataCount, pixmap, hints);
         return;
     }
     // Bail out if nothing to do.
     if (dataCount <= 0)
         return;
     // Bail out if we don't have a usable VGImage for the pixmap.
     QVGPixmapData *vgpd = static_cast<QVGPixmapData *>(pd);
     if (!vgpd->isValid())
         return;
     VGImage vgImg = vgpd->toVGImage();
     if (vgImg == VG_INVALID_HANDLE)
         return;
     // We cache the results of any vgChildImage() calls because the
     // same child is very likely to be used over and over in particle
     // systems.  However, performance is even better if vgChildImage()
     // isn't needed at all, so use full source rects where possible.
     QVarLengthArray<VGImage> cachedImages;
     QVarLengthArray<QRect> cachedSources;
     // Select the opacity paint object.
     if ((hints & QPainter::OpaqueHint) != 0 && d->opacity == 1.0f) {
         d->setImageMode(VG_DRAW_IMAGE_NORMAL);
     }  else {
         hints = 0;
         if (d->fillPaint != d->opacityPaint) {
             vgSetPaint(d->opacityPaint, VG_FILL_PATH);
             d->fillPaint = d->opacityPaint;
         }
     }
     for (int i = 0; i < dataCount; ++i) {
         QTransform transform(d->imageTransform);
         transform.translate(drawingData[i].x, drawingData[i].y);
         transform.rotate(drawingData[i].rotation);
         VGImage child;
         QSize imageSize = vgpd->size();
         QRectF sr(drawingData[i].sourceLeft, drawingData[i].sourceTop,
                   drawingData[i].width, drawingData[i].height);
         if (sr.topLeft().isNull() && sr.size() == imageSize) {
             child = vgImg;
         } else {
             // Look for a previous child with the same source rectangle
             // to avoid constantly calling vgChildImage()/vgDestroyImage().
             QRect src = sr.toRect();
             int j;
             for (j = 0; j < cachedSources.size(); ++j) {
                 if (cachedSources[j] == src)
                     break;
             }
             if (j < cachedSources.size()) {
                 child = cachedImages[j];
             } else {
                 child = vgChildImage
                     (vgImg, src.x(), src.y(), src.width(), src.height());
                 cachedImages.append(child);
                 cachedSources.append(src);
             }
         }
         VGfloat scaleX = drawingData[i].scaleX;
         VGfloat scaleY = drawingData[i].scaleY;
         transform.translate(-0.5 * scaleX * sr.width(),
                             -0.5 * scaleY * sr.height());
         transform.scale(scaleX, scaleY);
         d->setTransform(VG_MATRIX_IMAGE_USER_TO_SURFACE, transform);
         if ((hints & QPainter::OpaqueHint) == 0) {
             qreal opacity = d->opacity * drawingData[i].opacity;
             if (opacity != 1.0f) {
                 if (d->paintOpacity != opacity) {
                     VGfloat values[4];
                     values[0] = 1.0f;
                     values[1] = 1.0f;
                     values[2] = 1.0f;
                     values[3] = opacity;
                     d->paintOpacity = opacity;
                     vgSetParameterfv
                         (d->opacityPaint, VG_PAINT_COLOR, 4, values);
                 }
                 d->setImageMode(VG_DRAW_IMAGE_MULTIPLY);
             } else {
                 d->setImageMode(VG_DRAW_IMAGE_NORMAL);
             }
         }
         vgDrawImage(child);
     }
     // Destroy the cached child sub-images.
     for (int i = 0; i < cachedImages.size(); ++i)
         vgDestroyImage(cachedImages[i]);
 #else
     QPaintEngineEx::drawPixmapFragments(drawingData, dataCount, pixmap, hints);
 #endif
 }
drawPoints() [1/2]
void QVGPaintEngine::drawPoints (const QPointF * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
Reimplemented from QPaintEngineEx.
Definition at line 2923 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_MODIFY_PATH)
     Q_D(QVGPaintEngine);
     if (d->needsPenEmulation()) {
         QPaintEngineEx::drawPoints(points, pointCount);
         return;
     }
     // Set up a new pen if necessary.
     QPen pen = state()->pen;
     if (pen.style() == Qt::NoPen)
         return;
     if (pen.capStyle() == Qt::FlatCap)
         pen.setCapStyle(Qt::SquareCap);
     for (int i = 0; i < pointCount; ++i, ++points) {
         VGfloat coords[4];
         if (d->simpleTransform) {
             coords[0] = points->x();
             coords[1] = points->y();
             coords[2] = coords[0];
             coords[3] = coords[1];
         } else {
             QPointF p = d->transform.map(*points);
             coords[0] = p.x();
             coords[1] = p.y();
             coords[2] = coords[0];
             coords[3] = coords[1];
         }
         vgModifyPathCoords(d->linePath, 0, 2, coords);
         d->stroke(d->linePath, pen);
     }
 #else
     QPaintEngineEx::drawPoints(points, pointCount);
 #endif
 }
drawPoints() [2/2]
void QVGPaintEngine::drawPoints (const QPoint * points, int pointCount) virtual
Draws the first pointCount points in the buffer points.
The default implementation converts the first pointCount QPoints in points to QPointFs and calls the floating point version of drawPoints.
Reimplemented from QPaintEngineEx.
Definition at line 2962 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_MODIFY_PATH)
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawPoints(points, pointCount);
         return;
     }
     // Set up a new pen if necessary.
     QPen pen = state()->pen;
     if (pen.style() == Qt::NoPen)
         return;
     if (pen.capStyle() == Qt::FlatCap)
         pen.setCapStyle(Qt::SquareCap);
     for (int i = 0; i < pointCount; ++i, ++points) {
         VGfloat coords[4];
         if (d->simpleTransform) {
             coords[0] = points->x();
             coords[1] = points->y();
             coords[2] = coords[0];
             coords[3] = coords[1];
         } else {
             QPointF p = d->transform.map(QPointF(*points));
             coords[0] = p.x();
             coords[1] = p.y();
             coords[2] = coords[0];
             coords[3] = coords[1];
         }
         vgModifyPathCoords(d->linePath, 0, 2, coords);
         d->stroke(d->linePath, pen);
     }
 #else
     QPaintEngineEx::drawPoints(points, pointCount);
 #endif
 }
drawPolygon() [1/2]
void QVGPaintEngine::drawPolygon (const QPointF * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngineEx.
Definition at line 3001 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawPolygon(points, pointCount, mode);
         return;
     }
     QVGPainterState *s = state();
     VGPath path = vgCreatePath(VG_PATH_FORMAT_STANDARD,
                                VG_PATH_DATATYPE_F,
                                1.0f,             // scale
                                0.0f,             // bias
                                pointCount + 1,   // segmentCapacityHint
                                pointCount * 2,   // coordCapacityHint
                                VG_PATH_CAPABILITY_ALL);
     QVarLengthArray<VGfloat, 16> coords;
     QVarLengthArray<VGubyte, 10> segments;
     for (int i = 0; i < pointCount; ++i, ++points) {
         if (d->simpleTransform) {
             coords.append(points->x());
             coords.append(points->y());
         } else {
             QPointF temp = d->transform.map(*points);
             coords.append(temp.x());
             coords.append(temp.y());
         }
         if (i == 0)
             segments.append(VG_MOVE_TO_ABS);
         else
             segments.append(VG_LINE_TO_ABS);
     }
     if (mode != QPaintEngine::PolylineMode)
         segments.append(VG_CLOSE_PATH);
     vgAppendPathData(path, segments.count(),
                      segments.constData(), coords.constData());
     switch (mode) {
         case QPaintEngine::WindingMode:
             d->draw(path, s->pen, s->brush, VG_NON_ZERO);
             break;
         case QPaintEngine::PolylineMode:
             d->stroke(path, s->pen);
             break;
         default:
             d->draw(path, s->pen, s->brush, VG_EVEN_ODD);
             break;
     }
     vgDestroyPath(path);
 }
drawPolygon() [2/2]
void QVGPaintEngine::drawPolygon (const QPoint * points, int pointCount, PolygonDrawMode mode) virtual
Reimplement this virtual function to draw the polygon defined by the pointCount first points in points, using mode mode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Note
At least one of the drawPolygon() functions must be reimplemented.
Reimplemented from QPaintEngineEx.
Definition at line 3054 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawPolygon(points, pointCount, mode);
         return;
     }
     QVGPainterState *s = state();
     VGPath path = vgCreatePath(VG_PATH_FORMAT_STANDARD,
                                VG_PATH_DATATYPE_F,
                                1.0f,             // scale
                                0.0f,             // bias
                                pointCount + 1,   // segmentCapacityHint
                                pointCount * 2,   // coordCapacityHint
                                VG_PATH_CAPABILITY_ALL);
     QVarLengthArray<VGfloat, 16> coords;
     QVarLengthArray<VGubyte, 10> segments;
     for (int i = 0; i < pointCount; ++i, ++points) {
         if (d->simpleTransform) {
             coords.append(points->x());
             coords.append(points->y());
         } else {
             QPointF temp = d->transform.map(QPointF(*points));
             coords.append(temp.x());
             coords.append(temp.y());
         }
         if (i == 0)
             segments.append(VG_MOVE_TO_ABS);
         else
             segments.append(VG_LINE_TO_ABS);
     }
     if (mode != QPaintEngine::PolylineMode)
         segments.append(VG_CLOSE_PATH);
     vgAppendPathData(path, segments.count(),
                      segments.constData(), coords.constData());
     switch (mode) {
         case QPaintEngine::WindingMode:
             d->draw(path, s->pen, s->brush, VG_NON_ZERO);
             break;
         case QPaintEngine::PolylineMode:
             d->stroke(path, s->pen);
             break;
         default:
             d->draw(path, s->pen, s->brush, VG_EVEN_ODD);
             break;
     }
     vgDestroyPath(path);
 }
drawRects() [1/2]
void QVGPaintEngine::drawRects (const QRect * rects, int rectCount) virtual
The default implementation converts the first rectCount rectangles in the buffer rects to a QRectF and calls the floating point version of this function.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Reimplemented from QPaintEngineEx.
Definition at line 2700 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_MODIFY_PATH)
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawRects(rects, rectCount);
         return;
     }
     QVGPainterState *s = state();
     for (int i = 0; i < rectCount; ++i, ++rects) {
         VGfloat coords[8];
         if (d->simpleTransform) {
             coords[0] = rects->x();
             coords[1] = rects->y();
             coords[2] = rects->x() + rects->width();
             coords[3] = coords[1];
             coords[4] = coords[2];
             coords[5] = rects->y() + rects->height();
             coords[6] = coords[0];
             coords[7] = coords[5];
         } else {
             QPointF tl = d->transform.map(QPointF(rects->x(), rects->y()));
             QPointF tr = d->transform.map(QPointF(rects->x() + rects->width(),
                                                   rects->y()));
             QPointF bl = d->transform.map(QPointF(rects->x(),
                                                   rects->y() + rects->height()));
             QPointF br = d->transform.map(QPointF(rects->x() + rects->width(),
                                                   rects->y() + rects->height()));
             coords[0] = tl.x();
             coords[1] = tl.y();
             coords[2] = tr.x();
             coords[3] = tr.y();
             coords[4] = br.x();
             coords[5] = br.y();
             coords[6] = bl.x();
             coords[7] = bl.y();
         }
         vgModifyPathCoords(d->rectPath, 0, 4, coords);
         d->draw(d->rectPath, s->pen, s->brush);
     }
 #else
     QPaintEngineEx::drawRects(rects, rectCount);
 #endif
 }
drawRects() [2/2]
void QVGPaintEngine::drawRects (const QRectF * rects, int rectCount) virtual
Draws the first rectCount rectangles in the buffer rects.
The default implementation of this function calls drawPath() or drawPolygon() depending on the feature set of the paint engine.
Reimplemented from QPaintEngineEx.
Definition at line 2745 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_MODIFY_PATH)
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawRects(rects, rectCount);
         return;
     }
     QVGPainterState *s = state();
     for (int i = 0; i < rectCount; ++i, ++rects) {
         VGfloat coords[8];
         if (d->simpleTransform) {
             coords[0] = rects->x();
             coords[1] = rects->y();
             coords[2] = rects->x() + rects->width();
             coords[3] = coords[1];
             coords[4] = coords[2];
             coords[5] = rects->y() + rects->height();
             coords[6] = coords[0];
             coords[7] = coords[5];
         } else {
             QPointF tl = d->transform.map(rects->topLeft());
             QPointF tr = d->transform.map(rects->topRight());
             QPointF bl = d->transform.map(rects->bottomLeft());
             QPointF br = d->transform.map(rects->bottomRight());
             coords[0] = tl.x();
             coords[1] = tl.y();
             coords[2] = tr.x();
             coords[3] = tr.y();
             coords[4] = br.x();
             coords[5] = br.y();
             coords[6] = bl.x();
             coords[7] = bl.y();
         }
         vgModifyPathCoords(d->rectPath, 0, 4, coords);
         d->draw(d->rectPath, s->pen, s->brush);
     }
 #else
     QPaintEngineEx::drawRects(rects, rectCount);
 #endif
 }
drawRoundedRect()
void QVGPaintEngine::drawRoundedRect (const QRectF & rect, qreal xrad, qreal yrad, Qt::SizeMode mode) virtual
Reimplemented from QPaintEngineEx.
Definition at line 2681 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     if (d->needsEmulation()) {
         QPaintEngineEx::drawRoundedRect(rect, xrad, yrad, mode);
         return;
     }
     if (d->simpleTransform) {
         QVGPainterState *s = state();
         VGPath vgpath = d->roundedRectPath(rect, xrad, yrad, mode);
         d->draw(vgpath, s->pen, s->brush);
 #if defined(QVG_NO_MODIFY_PATH)
         vgDestroyPath(vgpath);
 #endif
     } else {
         QPaintEngineEx::drawRoundedRect(rect, xrad, yrad, mode);
     }
 }
drawStaticTextItem()
void QVGPaintEngine::drawStaticTextItem (QStaticTextItem * staticTextItem) virtual
Reimplemented from QPaintEngineEx.
Definition at line 3737 of file qpaintengine_vg.cpp.
 {
     drawCachedGlyphs(textItem->numGlyphs, textItem->glyphs, textItem->font, textItem->fontEngine(),
                      QPointF(0, 0), textItem->glyphPositions);
 }
drawTextItem()
void QVGPaintEngine::drawTextItem (const QPointF & p, const QTextItem & textItem) virtual
This function draws the text item textItem at position p.
The default implementation of this function converts the text to a QPainterPath and paints the resulting path.
Reimplemented from QPaintEngine.
Definition at line 3704 of file qpaintengine_vg.cpp.
 {
 #if !defined(QVG_NO_DRAW_GLYPHS)
     Q_D(QVGPaintEngine);
     const QTextItemInt &ti = static_cast<const QTextItemInt &>(textItem);
     // If we are not using a simple transform, then fall back
     // to the default Qt path stroking algorithm.
     if (!d->simpleTransform) {
         QPaintEngineEx::drawTextItem(p, textItem);
         return;
     }
     if (d->needsPenEmulation()) {
         QPaintEngineEx::drawTextItem(p, textItem);
         return;
     }
     // Get the glyphs and positions associated with the text item.
     QVarLengthArray<QFixedPoint> positions;
     QVarLengthArray<glyph_t> glyphs;
     QTransform matrix;
     ti.fontEngine->getGlyphPositions(ti.glyphs, matrix, ti.flags, glyphs, positions);
     if (!drawCachedGlyphs(glyphs.size(), glyphs.data(), ti.font(), ti.fontEngine, p, positions.data()))
         QPaintEngineEx::drawTextItem(p, textItem);
 #else
     // OpenGL 1.0 does not have support for VGFont and glyphs,
     // so fall back to the default Qt path stroking algorithm.
     QPaintEngineEx::drawTextItem(p, textItem);
 #endif
 }
drawTiledPixmap()
void QVGPaintEngine::drawTiledPixmap (const QRectF & rect, const QPixmap & pixmap, const QPointF & p) virtual
Reimplement this function to draw the pixmap in the given rect, starting at the given p.
The pixmap will be drawn repeatedly until the rect is filled.
Reimplemented from QPaintEngineEx.
Definition at line 3464 of file qpaintengine_vg.cpp.
Referenced by drawImage().
 {
     QBrush brush(state()->pen.color(), pixmap);
     QTransform xform = QTransform::fromTranslate(r.x() - s.x(), r.y() - s.y());
     brush.setTransform(xform);
     fillRect(r, brush);
 }
end()
bool QVGPaintEngine::end () virtual
Reimplement this function to finish painting on the current paint device.
Return true if painting was finished successfully; otherwise return false.
See also
begin() isActive()
Implements QPaintEngine.
Definition at line 1559 of file qpaintengine_vg.cpp.
 {
     vgSeti(VG_SCISSORING, VG_FALSE);
     vgSeti(VG_MASKING, VG_FALSE);
     return true;
 }
endNativePainting()
void QVGPaintEngine::endNativePainting () virtual
Reimplemented from QPaintEngineEx.
Definition at line 3872 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     // Exiting raw VG mode: force all state values to be
     // explicitly set on the VG engine to undo any changes
     // that were made by the raw VG function calls.
     QPaintEngine::DirtyFlags dirty = d->dirty;
     d->clearModes();
     d->forcePenChange = true;
     d->forceBrushChange = true;
     d->penType = (VGPaintType)0;
     d->brushType = (VGPaintType)0;
     d->clearColor = QColor();
     d->fillPaint = d->brushPaint;
     d->scissorDirty = true;
     restoreState(QPaintEngine::AllDirty);
     d->dirty = dirty;
     d->rawVG = false;
     vgSetPaint(d->penPaint, VG_STROKE_PATH);
     vgSetPaint(d->brushPaint, VG_FILL_PATH);
 }
fill()
void QVGPaintEngine::fill (const QVectorPath & path, const QBrush & brush) virtual
Implements QPaintEngineEx.
Definition at line 1584 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     if (d->needsEmulation(brush)) {
         QPainter *p = painter();
         QBrush oldBrush = p->brush();
         p->setBrush(brush);
         qt_draw_helper(p->d_ptr.data(), qt_painterPathFromVectorPath(path), QPainterPrivate::FillDraw);
         p->setBrush(oldBrush);
         return;
     }
     VGPath vgpath = d->vectorPathToVGPath(path);
     if (!path.hasWindingFill())
         d->fill(vgpath, brush, VG_EVEN_ODD);
     else
         d->fill(vgpath, brush, VG_NON_ZERO);
     vgDestroyPath(vgpath);
 }
fillRect() [1/2]
void QVGPaintEngine::fillRect (const QRectF & rect, const QBrush & brush) virtual
Reimplemented from QPaintEngineEx.
Definition at line 2588 of file qpaintengine_vg.cpp.
Referenced by drawTiledPixmap().
 {
     Q_D(QVGPaintEngine);
     if (brush.style() == Qt::NoBrush)
         return;
     // Check to see if we can use vgClear() for faster filling.
     if (brush.style() == Qt::SolidPattern && brush.isOpaque() &&
             clipTransformIsSimple(d->transform) && d->opacity == 1.0f &&
             clearRect(rect, brush.color())) {
         return;
     }
     if (d->needsEmulation(brush)) {
         QPaintEngineEx::fillRect(rect, brush);
         return;
     }
 #if !defined(QVG_NO_MODIFY_PATH)
     VGfloat coords[8];
     if (d->simpleTransform) {
         coords[0] = rect.x();
         coords[1] = rect.y();
         coords[2] = rect.x() + rect.width();
         coords[3] = coords[1];
         coords[4] = coords[2];
         coords[5] = rect.y() + rect.height();
         coords[6] = coords[0];
         coords[7] = coords[5];
     } else {
         QPointF tl = d->transform.map(rect.topLeft());
         QPointF tr = d->transform.map(rect.topRight());
         QPointF bl = d->transform.map(rect.bottomLeft());
         QPointF br = d->transform.map(rect.bottomRight());
         coords[0] = tl.x();
         coords[1] = tl.y();
         coords[2] = tr.x();
         coords[3] = tr.y();
         coords[4] = br.x();
         coords[5] = br.y();
         coords[6] = bl.x();
         coords[7] = bl.y();
     }
     vgModifyPathCoords(d->rectPath, 0, 4, coords);
     d->fill(d->rectPath, brush);
 #else
     QPaintEngineEx::fillRect(rect, brush);
 #endif
 }
fillRect() [2/2]
void QVGPaintEngine::fillRect (const QRectF & rect, const QColor & color) virtual
Reimplemented from QPaintEngineEx.
Definition at line 2639 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     // Check to see if we can use vgClear() for faster filling.
     if (clipTransformIsSimple(d->transform) && d->opacity == 1.0f && color.alpha() == 255 &&
             clearRect(rect, color)) {
         return;
     }
 #if !defined(QVG_NO_MODIFY_PATH)
     VGfloat coords[8];
     if (d->simpleTransform) {
         coords[0] = rect.x();
         coords[1] = rect.y();
         coords[2] = rect.x() + rect.width();
         coords[3] = coords[1];
         coords[4] = coords[2];
         coords[5] = rect.y() + rect.height();
         coords[6] = coords[0];
         coords[7] = coords[5];
     } else {
         QPointF tl = d->transform.map(rect.topLeft());
         QPointF tr = d->transform.map(rect.topRight());
         QPointF bl = d->transform.map(rect.bottomLeft());
         QPointF br = d->transform.map(rect.bottomRight());
         coords[0] = tl.x();
         coords[1] = tl.y();
         coords[2] = tr.x();
         coords[3] = tr.y();
         coords[4] = br.x();
         coords[5] = br.y();
         coords[6] = bl.x();
         coords[7] = bl.y();
     }
     vgModifyPathCoords(d->rectPath, 0, 4, coords);
     d->fill(d->rectPath, QBrush(color));
 #else
     QPaintEngineEx::fillRect(rect, QBrush(color));
 #endif
 }
fillRegion()
void QVGPaintEngine::fillRegion (const QRegion & region, const QColor & color, const QSize & surfaceSize)
Definition at line 3961 of file qpaintengine_vg.cpp.
Referenced by QVGWindowSurface::beginPaint(), and restoreState().
 {
     Q_D(QVGPaintEngine);
     if (d->clearColor != color || d->clearOpacity != 1.0f) {
         VGfloat values[4];
         values[0] = color.redF();
         values[1] = color.greenF();
         values[2] = color.blueF();
         values[3] = color.alphaF();
         vgSetfv(VG_CLEAR_COLOR, 4, values);
         d->clearColor = color;
         d->clearOpacity = 1.0f;
     }
     if (region.rectCount() == 1) {
         QRect r = region.boundingRect();
         vgClear(r.x(), surfaceSize.height() - r.y() - r.height(),
                 r.width(), r.height());
     } else {
         const QVector<QRect> rects = region.rects();
         for (int i = 0; i < rects.size(); ++i) {
             QRect r = rects.at(i);
             vgClear(r.x(), surfaceSize.height() - r.y() - r.height(),
                     r.width(), r.height());
         }
     }
 }
isDefaultClipRect()
bool QVGPaintEngine::isDefaultClipRect (const QRect & rect) private
Definition at line 2370 of file qpaintengine_vg.cpp.
Referenced by clip().
 {
     QPaintDevice *pdev = paintDevice();
     int width = pdev->width();
     int height = pdev->height();
     return (rect.x() == 0 && rect.y() == 0 &&
             rect.width() == width && rect.height() == height);
 }
isDefaultClipRegion()
bool QVGPaintEngine::isDefaultClipRegion (const QRegion & region) private
Definition at line 2356 of file qpaintengine_vg.cpp.
Referenced by clip(), and updateScissor().
 {
     if (region.rectCount() != 1)
         return false;
     QPaintDevice *pdev = paintDevice();
     int width = pdev->width();
     int height = pdev->height();
     QRect rect = region.boundingRect();
     return (rect.x() == 0 && rect.y() == 0 &&
             rect.width() == width && rect.height() == height);
 }
opacityChanged()
void QVGPaintEngine::opacityChanged () virtual
Implements QPaintEngineEx.
Definition at line 2435 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyOpacity;
     d->opacity = state()->opacity;
     d->forcePenChange = true;
     d->forceBrushChange = true;
 }
penChanged()
void QVGPaintEngine::penChanged () virtual
Implements QPaintEngineEx.
Definition at line 2409 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyPen;
     d->hasExtendedRadialGradientPen =
         state()->pen.style() != Qt::NoPen && d->needsEmulation(state()->pen.brush());
 }
pixmapFilter()
QPixmapFilter * QVGPaintEngine::pixmapFilter (int type, const QPixmapFilter * prototype) virtual
Reimplemented from QPaintEngineEx.
Definition at line 3894 of file qpaintengine_vg.cpp.
 {
 #if !defined(QT_SHIVAVG)
     Q_D(QVGPaintEngine);
     switch (type) {
         case QPixmapFilter::ConvolutionFilter:
             if (!d->convolutionFilter)
                 d->convolutionFilter.reset(new QVGPixmapConvolutionFilter);
             return d->convolutionFilter.data();
         case QPixmapFilter::ColorizeFilter:
             if (!d->colorizeFilter)
                 d->colorizeFilter.reset(new QVGPixmapColorizeFilter);
             return d->colorizeFilter.data();
         case QPixmapFilter::DropShadowFilter:
             if (!d->dropShadowFilter)
                 d->dropShadowFilter.reset(new QVGPixmapDropShadowFilter);
             return d->dropShadowFilter.data();
         case QPixmapFilter::BlurFilter:
             if (!d->blurFilter)
                 d->blurFilter.reset(new QVGPixmapBlurFilter);
             return d->blurFilter.data();
         default: break;
     }
 #endif
     return QPaintEngineEx::pixmapFilter(type, prototype);
 }
renderHintsChanged()
void QVGPaintEngine::renderHintsChanged () virtual
Implements QPaintEngineEx.
Definition at line 2532 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     d->dirty |= QPaintEngine::DirtyHints;
     QPainter::RenderHints hints = state()->renderHints;
     VGRenderingQuality rq =
             (hints & QPainter::Antialiasing)
                 ? VG_RENDERING_QUALITY_BETTER
                 : VG_RENDERING_QUALITY_NONANTIALIASED;
     VGImageQuality iq =
             (hints & QPainter::SmoothPixmapTransform)
                 ? VG_IMAGE_QUALITY_BETTER
                 : VG_IMAGE_QUALITY_NONANTIALIASED;
     d->setRenderingQuality(rq);
     d->setImageQuality(iq);
 }
restoreState()
void QVGPaintEngine::restoreState (QPaintEngine::DirtyFlags dirty) private
Definition at line 3921 of file qpaintengine_vg.cpp.
Referenced by begin().
 {
     Q_D(QVGPaintEngine);
     // Restore the pen, brush, and other settings.
     if ((dirty & QPaintEngine::DirtyBrushOrigin) != 0)
         brushOriginChanged();
     d->fillRule = 0;
     d->clearColor = QColor();
     if ((dirty & QPaintEngine::DirtyOpacity) != 0)
         opacityChanged();
     if ((dirty & QPaintEngine::DirtyTransform) != 0)
         transformChanged();
     if ((dirty & QPaintEngine::DirtyCompositionMode) != 0)
         compositionModeChanged();
     if ((dirty & QPaintEngine::DirtyHints) != 0)
         renderHintsChanged();
     if ((dirty & (QPaintEngine::DirtyClipRegion |
                   QPaintEngine::DirtyClipPath |
                   QPaintEngine::DirtyClipEnabled)) != 0) {
         d->maskValid = false;
         d->maskIsSet = false;
         d->scissorMask = false;
         d->maskRect = QRect();
         d->scissorDirty = true;
         clipEnabledChanged();
     }
 #if defined(QVG_SCISSOR_CLIP)
     if ((dirty & (QPaintEngine::DirtyClipRegion |
                   QPaintEngine::DirtyClipPath |
                   QPaintEngine::DirtyClipEnabled)) == 0) {
         updateScissor();
     }
 #else
     updateScissor();
 #endif
 }
setState()
void QVGPaintEngine::setState (QPainterState * s) virtual
Reimplemented from QPaintEngineEx.
Definition at line 3836 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     QPaintEngineEx::setState(s);
     QVGPainterState *ps = static_cast<QVGPainterState *>(s);
     if (ps->isNew) {
         // Newly created state object.  The call to setState()
         // will either be followed by a call to begin(), or we are
         // setting the state as part of a save().
         ps->isNew = false;
     } else {
         // This state object was set as part of a restore().
         restoreState(d->dirty);
         d->dirty = ps->savedDirty;
     }
 }
state() [1/2]
QVGPainterState* QVGPaintEngine::state () inline
Definition at line 151 of file qpaintengine_vg_p.h.
Referenced by begin(), brushChanged(), brushOriginChanged(), clearRect(), clipEnabledChanged(), clipTransformIsSimple(), compositionModeChanged(), draw(), drawEllipse(), drawLines(), drawPath(), drawPoints(), drawPolygon(), drawRects(), drawRoundedRect(), drawTiledPixmap(), opacityChanged(), penChanged(), renderHintsChanged(), transformChanged(), and updateScissor().
 { return static_cast<QVGPainterState *>(QPaintEngineEx::state()); }
state() [2/2]
const QVGPainterState* QVGPaintEngine::state () const inline
Definition at line 152 of file qpaintengine_vg_p.h.
 { return static_cast<const QVGPainterState *>(QPaintEngineEx::state()); }
stroke()
void QVGPaintEngine::stroke (const QVectorPath & path, const QPen & pen) virtual
Reimplemented from QPaintEngineEx.
Definition at line 1603 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     if (d->needsEmulation(pen.brush())) {
         QPaintEngineEx::stroke(path, pen);
         return;
     }
     VGPath vgpath = d->vectorPathToVGPath(path);
     d->stroke(vgpath, pen);
     vgDestroyPath(vgpath);
 }
supportsTransformations()
bool QVGPaintEngine::supportsTransformations (qreal , const QTransform &) const inline virtual
Reimplemented from QPaintEngineEx.
Definition at line 162 of file qpaintengine_vg_p.h.
 { return true; }
transformChanged()
void QVGPaintEngine::transformChanged () virtual
Implements QPaintEngineEx.
Definition at line 2552 of file qpaintengine_vg.cpp.
 {
     Q_D(QVGPaintEngine);
     QVGPainterState *s = state();
     d->dirty |= QPaintEngine::DirtyTransform;
     d->transform = s->transform();
     qreal oldPenScale = d->penScale;
     d->updateTransform(paintDevice());
     if (d->penScale != oldPenScale)
         d->forcePenChange = true;
 }
type()
Type QVGPaintEngine::type () const inline virtual
Reimplement this function to return the paint engine Type.
Implements QPaintEngine.
Definition at line 85 of file qpaintengine_vg_p.h.
Referenced by clipTransformIsSimple().
 { return OpenVG; }
updateScissor()
void QVGPaintEngine::updateScissor () private
Definition at line 2242 of file qpaintengine_vg.cpp.
Referenced by clip(), clipEnabledChanged(), clipTransformIsSimple(), and QVGPaintEnginePrivate::ensureMask().
 {
     Q_D(QVGPaintEngine);
     QRegion region = d->systemClip;
 #if defined(QVG_SCISSOR_CLIP)
     // Using the scissor to do clipping, so combine the systemClip
     // with the current painting clipRegion.
     if (d->maskValid) {
         vgSeti(VG_MASKING, VG_FALSE);
         d->maskValid = false;
     }
     QVGPainterState *s = state();
     if (s->clipEnabled) {
         if (region.isEmpty())
             region = s->clipRegion;
         else
             region = region.intersect(s->clipRegion);
         if (isDefaultClipRegion(region)) {
             // The scissor region is the entire drawing surface,
             // so there is no point doing any scissoring.
             vgSeti(VG_SCISSORING, VG_FALSE);
             d->scissorActive = false;
             d->scissorDirty = false;
             return;
         }
     } else
 #endif
     {
 #if !defined(QVG_SCISSOR_CLIP)
         // Combine the system clip with the simple mask rectangle.
         if (d->scissorMask) {
             if (region.isEmpty())
                 region = d->maskRect;
             else
                 region = region.intersect(d->maskRect);
             if (isDefaultClipRegion(region)) {
                 // The scissor region is the entire drawing surface,
                 // so there is no point doing any scissoring.
                 vgSeti(VG_SCISSORING, VG_FALSE);
                 d->scissorActive = false;
                 d->scissorDirty = false;
                 return;
             }
         } else
 #endif
         // Disable the scissor completely if the system clip is empty.
         if (region.isEmpty()) {
             vgSeti(VG_SCISSORING, VG_FALSE);
             d->scissorActive = false;
             d->scissorDirty = false;
             return;
         }
     }
     if (d->scissorActive && region == d->scissorRegion && !d->scissorDirty)
         return;
     QVector<QRect> rects = region.rects();
     int count = rects.count();
     if (count > d->maxScissorRects) {
 #if !defined(QVG_SCISSOR_CLIP)
          count = d->maxScissorRects;
 #else
         // Use masking
         int width = paintDevice()->width();
         int height = paintDevice()->height();
         vgMask(VG_INVALID_HANDLE, VG_CLEAR_MASK,
                    0, 0, width, height);
         for (int i = 0; i < rects.size(); ++i) {
             vgMask(VG_INVALID_HANDLE, VG_FILL_MASK,
                    rects[i].x(), height - rects[i].y() - rects[i].height(),
                    rects[i].width(), rects[i].height());
         }
         vgSeti(VG_SCISSORING, VG_FALSE);
         vgSeti(VG_MASKING, VG_TRUE);
         d->maskValid = true;
         d->maskIsSet = false;
         d->scissorMask = false;
         d->scissorActive = false;
         d->scissorDirty = false;
         d->scissorRegion = region;
         return;
 #endif
     }
     QVarLengthArray<VGint> params(count * 4);
     int height = paintDevice()->height();
     for (int i = 0; i < count; ++i) {
         params[i * 4 + 0] = rects[i].x();
         params[i * 4 + 1] = height - rects[i].y() - rects[i].height();
         params[i * 4 + 2] = rects[i].width();
         params[i * 4 + 3] = rects[i].height();
     }
     vgSetiv(VG_SCISSOR_RECTS, count * 4, params.data());
     vgSeti(VG_SCISSORING, VG_TRUE);
     d->scissorDirty = false;
     d->scissorActive = true;
     d->scissorRegion = region;
 }
vgPrivate()
QVGPaintEnginePrivate* QVGPaintEngine::vgPrivate () inline
Definition at line 159 of file qpaintengine_vg_p.h.
Referenced by qt_vg_drawVGImage(), qt_vg_drawVGImageStencil(), and QVGCompositionHelper::QVGCompositionHelper().
 { Q_D(QVGPaintEngine); return d; }
The documentation for this class was generated from the following files:
/src/openvg/qpaintengine_vg_p.h
/src/openvg/qpaintengine_vg.cpp