Qt 4.8: QDeclarativeTypeNameScriptClass Class Reference
QDeclarativeTypeNameScriptClass Class Reference
#include <qdeclarativetypenamescriptclass_p.h>
Public Types
enum TypeNameMode { IncludeEnums, ExcludeEnums }
Public Types inherited from QScriptDeclarativeClass
typedef void * Identifier
Public Functions
QScriptValue newObject (QObject *, QDeclarativeType *, TypeNameMode=IncludeEnums)
QScriptValue newObject (QObject *, QDeclarativeTypeNameCache *, TypeNameMode=IncludeEnums)
QDeclarativeTypeNameScriptClass (QDeclarativeEngine *)
~QDeclarativeTypeNameScriptClass ()
Public Functions inherited from QScriptDeclarativeClass
virtual Value call (Object *, QScriptContext *)
virtual bool compare (Object *, Object *)
QScriptContext * context () const
PersistentIdentifier createPersistentIdentifier (const QString &)
PersistentIdentifier createPersistentIdentifier (const Identifier &)
QScriptEngine * engine () const
virtual bool isQObject () const
virtual QScriptValue::PropertyFlags propertyFlags (Object *, const Identifier &)
virtual QStringList propertyNames (Object *)
QScriptDeclarativeClass (QScriptEngine *engine)
void setSupportsCall (bool)
bool startsWithUpper (const Identifier &)
bool supportsCall () const
quint32 toArrayIndex (const Identifier &, bool *ok)
virtual QObject * toQObject (Object *, bool *ok=0)
QString toString (const Identifier &)
virtual QVariant toVariant (Object *, bool *ok=0)
virtual ~QScriptDeclarativeClass ()
Protected Functions
virtual Value property (Object *, const Identifier &)
virtual QScriptClass::QueryFlags queryProperty (Object *, const Identifier &, QScriptClass::QueryFlags flags)
virtual void setProperty (Object *, const Identifier &name, const QScriptValue &)
Properties
QDeclarativeEngine * engine
quint32 enumValue
QObject * object
QDeclarativeType * type
Additional Inherited Members
Static Public Functions inherited from QScriptDeclarativeClass
static QScriptValue function (const QScriptValue &, const Identifier &)
static Value functionValue (const QScriptValue &, const Identifier &)
static QScriptValue newObject (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static Value newObjectValue (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static QScriptValue newStaticScopeObject (QScriptEngine *, int propertyCount, const QString *names, const QScriptValue *values, const QScriptValue::PropertyFlags *flags)
Creates a scope object with a fixed set of undeletable properties.
static QScriptValue newStaticScopeObject (QScriptEngine *)
Creates a static scope object that's initially empty, but to which new properties can be added.
static Object * object (const QScriptValue &)
static QScriptValue property (const QScriptValue &, const Identifier &)
static Value propertyValue (const QScriptValue &, const Identifier &)
static QScriptContext * pushCleanContext (QScriptEngine *)
Enters a new execution context and returns the associated QScriptContext object.
static QScriptValue scopeChainValue (QScriptContext *, int index)
static QScriptDeclarativeClass * scriptClass (const QScriptValue &)
Protected Variables inherited from QScriptDeclarativeClass
QScopedPointer< QScriptDeclarativeClassPrivate > d_ptr
Detailed Description
Definition at line 65 of file qdeclarativetypenamescriptclass_p.h.
Enumerations
TypeNameMode
enum QDeclarativeTypeNameScriptClass::TypeNameMode
Enumerator
IncludeEnums
ExcludeEnums
Definition at line 71 of file qdeclarativetypenamescriptclass_p.h.
 { IncludeEnums, ExcludeEnums };
Constructors and Destructors
QDeclarativeTypeNameScriptClass()
QDeclarativeTypeNameScriptClass::QDeclarativeTypeNameScriptClass (QDeclarativeEngine * bindEngine)
Definition at line 64 of file qdeclarativetypenamescriptclass.cpp.
 : QScriptDeclarativeClass(QDeclarativeEnginePrivate::getScriptEngine(bindEngine)),
   engine(bindEngine), object(0), type(0)
 {
 }
~QDeclarativeTypeNameScriptClass()
QDeclarativeTypeNameScriptClass::~QDeclarativeTypeNameScriptClass ()
Definition at line 70 of file qdeclarativetypenamescriptclass.cpp.
 {
 }
Functions
newObject() [1/2]
QScriptValue QDeclarativeTypeNameScriptClass::newObject (QObject * object, QDeclarativeType * type, TypeNameMode mode = IncludeEnums)
Definition at line 74 of file qdeclarativetypenamescriptclass.cpp.
Referenced by property(), QDeclarativeContextScriptClass::property(), and QDeclarativeObjectScriptClass::property().
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     return QScriptDeclarativeClass::newObject(scriptEngine, this, new TypeNameData(object, type, mode));
 }
newObject() [2/2]
QScriptValue QDeclarativeTypeNameScriptClass::newObject (QObject * object, QDeclarativeTypeNameCache * ns, TypeNameMode mode = IncludeEnums)
Definition at line 81 of file qdeclarativetypenamescriptclass.cpp.
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     return QScriptDeclarativeClass::newObject(scriptEngine, this, new TypeNameData(object, ns, mode));
 }
property()
QDeclarativeTypeNameScriptClass::Value QDeclarativeTypeNameScriptClass::property (Object * obj, const Identifier & name) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 142 of file qdeclarativetypenamescriptclass.cpp.
 {
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     if (type) {
         return Value(scriptEngine, newObject(((TypeNameData *)obj)->object, type, ((TypeNameData *)obj)->mode));
     } else if (object) {
         return ep->objectClass->property(object, name);
     } else {
         return Value(scriptEngine, enumValue);
     }
 }
queryProperty()
QScriptClass::QueryFlags QDeclarativeTypeNameScriptClass::queryProperty (Object * obj, const Identifier & name, QScriptClass::QueryFlags flags) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 89 of file qdeclarativetypenamescriptclass.cpp.
 {
     Q_UNUSED(flags);
     TypeNameData *data = (TypeNameData *)obj;
     object = 0;
     type = 0;
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     if (data->typeNamespace) {
         QDeclarativeTypeNameCache::Data *d = data->typeNamespace->data(name);
         if (d && d->type) {
             type = d->type;
             return QScriptClass::HandlesReadAccess;
         } else {
             return 0;
         }
     } else if (data->type) {
         if (startsWithUpper(name)) {
             QString strName = toString(name);
             // Must be an enum
             if (data->mode == IncludeEnums) {
                 // ### Optimize
                 QByteArray enumName = strName.toUtf8();
                 const QMetaObject *metaObject = data->type->baseMetaObject();
                 for (int ii = metaObject->enumeratorCount() - 1; ii >= 0; --ii) {
                     QMetaEnum e = metaObject->enumerator(ii);
                     int value = e.keyToValue(enumName.constData());
                     if (value != -1) {
                         enumValue = value;
                         return QScriptClass::HandlesReadAccess;
                     }
                 }
             }
             return 0;
         } else if (data->object) {
             // Must be an attached property
             object = qmlAttachedPropertiesObjectById(data->type->attachedPropertiesId(), data->object);
             if (!object) return 0;
             return ep->objectClass->queryProperty(object, name, flags, 0);
         }
     }
     return 0;
 }
setProperty()
void QDeclarativeTypeNameScriptClass::setProperty (Object * , const Identifier & name, const QScriptValue & v) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 155 of file qdeclarativetypenamescriptclass.cpp.
 {
     Q_ASSERT(object);
     Q_ASSERT(!type);
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     ep->objectClass->setProperty(object, n, v, context());
 }
Properties
engine
QDeclarativeEngine* QDeclarativeTypeNameScriptClass::engine private
Definition at line 83 of file qdeclarativetypenamescriptclass_p.h.
enumValue
quint32 QDeclarativeTypeNameScriptClass::enumValue private
Definition at line 86 of file qdeclarativetypenamescriptclass_p.h.
Referenced by property(), and queryProperty().
object
QObject* QDeclarativeTypeNameScriptClass::object private
Definition at line 84 of file qdeclarativetypenamescriptclass_p.h.
type
QDeclarativeType* QDeclarativeTypeNameScriptClass::type private
Definition at line 85 of file qdeclarativetypenamescriptclass_p.h.
Referenced by property(), queryProperty(), and setProperty().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativetypenamescriptclass_p.h
/src/declarative/qml/qdeclarativetypenamescriptclass.cpp