Qt 4.8: QDeclarativeComponentPrivate Class Reference
QDeclarativeComponentPrivate Class Reference
#include <qdeclarativecomponent_p.h>
Classes
struct ConstructionState
Public Functions
QDeclarativeComponentPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Functions inherited from QDeclarativeTypeData::TypeDataCallback
~TypeDataCallback ()
Static Public Functions
static QDeclarativeComponentPrivate * get (QDeclarativeComponent *c)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QDeclarativeCompiledData * cc
int count
QDeclarativeGuardedContextData creationContext
QDeclarativeEngine * engine
qreal progress
int start
ConstructionState state
QDeclarativeTypeData * typeData
QUrl url
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
QObject * beginCreate (QDeclarativeContextData *, const QBitField &)
void completeCreate ()
virtual void typeDataReady (QDeclarativeTypeData *)
virtual void typeDataProgress (QDeclarativeTypeData *, qreal)
void fromTypeData (QDeclarativeTypeData *data)
QScriptValue createObject (QObject *publicParent, const QScriptValue valuemap)
void clear ()
static QObject * begin (QDeclarativeContextData *parentContext, QDeclarativeContextData *componentCreationContext, QDeclarativeCompiledData *component, int start, int count, ConstructionState *state, QList< QDeclarativeError > *errors, const QBitField &bindings=QBitField())
static void beginDeferred (QDeclarativeEnginePrivate *enginePriv, QObject *object, ConstructionState *state)
static void complete (QDeclarativeEnginePrivate *enginePriv, ConstructionState *state)
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 77 of file qdeclarativecomponent_p.h.
Constructors and Destructors
QDeclarativeComponentPrivate()
QDeclarativeComponentPrivate::QDeclarativeComponentPrivate () inline
Definition at line 82 of file qdeclarativecomponent_p.h.
 : typeData(0), progress(0.), start(-1), count(-1), cc(0), engine(0), creationContext(0) {}
Functions
begin()
QObject * QDeclarativeComponentPrivate::begin (QDeclarativeContextData * parentContext, QDeclarativeContextData * componentCreationContext, QDeclarativeCompiledData * component, int start, int count, ConstructionState * state, QList< QDeclarativeError > * errors, const QBitField & bindings = QBitField()) static
Definition at line 887 of file qdeclarativecomponent.cpp.
Referenced by QDeclarativeCompiledData::TypeReference::createInstance().
 {
     QDeclarativeEnginePrivate *enginePriv = QDeclarativeEnginePrivate::get(parentContext->engine);
     bool isRoot = !enginePriv->inBeginCreate;
     Q_ASSERT(!isRoot || state); // Either this isn't a root component, or a state data must be provided
     Q_ASSERT((state != 0) ^ (errors != 0)); // One of state or errors (but not both) must be provided
     if (isRoot) {
         QDeclarativeDebugTrace::startRange(QDeclarativeDebugTrace::Creating);
         QDeclarativeDebugTrace::rangeData(QDeclarativeDebugTrace::Creating, component->url);
     }
     QDeclarativeContextData *ctxt = new QDeclarativeContextData;
     ctxt->isInternal = true;
     ctxt->url = component->url;
     ctxt->imports = component->importCache;
     // Nested global imports
     if (componentCreationContext && start != -1)
         ctxt->importedScripts = componentCreationContext->importedScripts;
     component->importCache->addref();
     ctxt->setParent(parentContext);
     enginePriv->inBeginCreate = true;
     QDeclarativeVME vme;
     QObject *rv = vme.run(ctxt, component, start, count, bindings);
     if (vme.isError()) {
        if(errors) *errors = vme.errors();
        else state->errors = vme.errors();
     }
     if (isRoot) {
         enginePriv->inBeginCreate = false;
         state->bindValues = enginePriv->bindValues;
         state->parserStatus = enginePriv->parserStatus;
         state->finalizedParserStatus = enginePriv->finalizedParserStatus;
         state->componentAttached = enginePriv->componentAttached;
         if (state->componentAttached)
             state->componentAttached->prev = &state->componentAttached;
         enginePriv->componentAttached = 0;
         enginePriv->bindValues.clear();
         enginePriv->parserStatus.clear();
         enginePriv->finalizedParserStatus.clear();
         state->completePending = true;
         enginePriv->inProgressCreations++;
     }
     if (enginePriv->isDebugging && rv) {
         if  (!parentContext->isInternal)
             parentContext->asQDeclarativeContextPrivate()->instances.append(rv);
         QDeclarativeEngineDebugService::instance()->objectCreated(parentContext->engine, rv);
     }
     return rv;
 }
beginCreate()
QObject * QDeclarativeComponentPrivate::beginCreate (QDeclarativeContextData * context, const QBitField & bindings)
Definition at line 856 of file qdeclarativecomponent.cpp.
 {
     Q_Q(QDeclarativeComponent);
     if (!context) {
         qWarning("QDeclarativeComponent: Cannot create a component in a null context");
         return 0;
     }
     if (!context->isValid()) {
         qWarning("QDeclarativeComponent: Cannot create a component in an invalid context");
         return 0;
     }
     if (context->engine != engine) {
         qWarning("QDeclarativeComponent: Must create component in context from the same QDeclarativeEngine");
         return 0;
     }
     if (state.completePending) {
         qWarning("QDeclarativeComponent: Cannot create new component instance before completing the previous");
         return 0;
     }
     if (!q->isReady()) {
         qWarning("QDeclarativeComponent: Component is not ready");
         return 0;
     }
     return begin(context, creationContext, cc, start, count, &state, 0, bindings);
 }
beginDeferred()
void QDeclarativeComponentPrivate::beginDeferred (QDeclarativeEnginePrivate * enginePriv, QObject * object, ConstructionState * state) static
Definition at line 953 of file qdeclarativecomponent.cpp.
Referenced by qmlExecuteDeferred().
 {
     bool isRoot = !enginePriv->inBeginCreate;
     enginePriv->inBeginCreate = true;
     QDeclarativeVME vme;
     vme.runDeferred(object);
     if (vme.isError())
         state->errors = vme.errors();
     if (isRoot) {
         enginePriv->inBeginCreate = false;
         state->bindValues = enginePriv->bindValues;
         state->parserStatus = enginePriv->parserStatus;
         state->finalizedParserStatus = enginePriv->finalizedParserStatus;
         state->componentAttached = enginePriv->componentAttached;
         if (state->componentAttached)
             state->componentAttached->prev = &state->componentAttached;
         enginePriv->componentAttached = 0;
         enginePriv->bindValues.clear();
         enginePriv->parserStatus.clear();
         enginePriv->finalizedParserStatus.clear();
         state->completePending = true;
         enginePriv->inProgressCreations++;
     }
 }
clear()
void QDeclarativeComponentPrivate::clear ()
Definition at line 292 of file qdeclarativecomponent.cpp.
 {
     if (typeData) {
         typeData->unregisterCallback(this);
         typeData->release();
         typeData = 0;
     }
     if (cc) {
         cc->release();
         cc = 0;
     }
 }
complete()
void QDeclarativeComponentPrivate::complete (QDeclarativeEnginePrivate * enginePriv, ConstructionState * state) static
Definition at line 984 of file qdeclarativecomponent.cpp.
Referenced by qmlExecuteDeferred().
 {
     if (state->completePending) {
         QT_TRY {
             for (int ii = 0; ii < state->bindValues.count(); ++ii) {
                 QDeclarativeEnginePrivate::SimpleList<QDeclarativeAbstractBinding> bv =
                     state->bindValues.at(ii);
                 for (int jj = 0; jj < bv.count; ++jj) {
                     if(bv.at(jj)) {
                         // XXX akennedy
                         bv.at(jj)->m_mePtr = 0;
                         bv.at(jj)->setEnabled(true, QDeclarativePropertyPrivate::BypassInterceptor |
                                                     QDeclarativePropertyPrivate::DontRemoveBinding);
                     }
                 }
                 QDeclarativeEnginePrivate::clear(bv);
             }
             for (int ii = 0; ii < state->parserStatus.count(); ++ii) {
                 QDeclarativeEnginePrivate::SimpleList<QDeclarativeParserStatus> ps =
                     state->parserStatus.at(ii);
                 for (int jj = ps.count - 1; jj >= 0; --jj) {
                     QDeclarativeParserStatus *status = ps.at(jj);
                     if (status && status->d) {
                         status->d = 0;
                         status->componentComplete();
                     }
                 }
                 QDeclarativeEnginePrivate::clear(ps);
             }
             for (int ii = 0; ii < state->finalizedParserStatus.count(); ++ii) {
                 QPair<QDeclarativeGuard<QObject>, int> status = state->finalizedParserStatus.at(ii);
                 QObject *obj = status.first;
                 if (obj) {
                     void *args[] = { 0 };
                     QMetaObject::metacall(obj, QMetaObject::InvokeMetaMethod,
                                           status.second, args);
                 }
             }
             //componentComplete() can register additional finalization objects
             //that are then never handled. Handle them manually here.
             if (1 == enginePriv->inProgressCreations) {
                 for (int ii = 0; ii < enginePriv->finalizedParserStatus.count(); ++ii) {
                     QPair<QDeclarativeGuard<QObject>, int> status = enginePriv->finalizedParserStatus.at(ii);
                     QObject *obj = status.first;
                     if (obj) {
                         void *args[] = { 0 };
                         QMetaObject::metacall(obj, QMetaObject::InvokeMetaMethod,
                                               status.second, args);
                     }
                 }
                 enginePriv->finalizedParserStatus.clear();
             }
             while (state->componentAttached) {
                 QDeclarativeComponentAttached *a = state->componentAttached;
                 a->rem();
                 QDeclarativeData *d = QDeclarativeData::get(a->parent());
                 Q_ASSERT(d);
                 Q_ASSERT(d->context);
                 a->add(&d->context->componentAttached);
                 emit a->completed();
             }
         } QT_CATCH(const std::exception&) {
             state->bindValues.clear();
             state->parserStatus.clear();
             state->finalizedParserStatus.clear();
             state->completePending = false;
             enginePriv->inProgressCreations--;
             QT_RETHROW;
         }
         state->bindValues.clear();
         state->parserStatus.clear();
         state->finalizedParserStatus.clear();
         state->completePending = false;
         enginePriv->inProgressCreations--;
         if (0 == enginePriv->inProgressCreations) {
             while (enginePriv->erroredBindings) {
                 enginePriv->warning(enginePriv->erroredBindings->error);
                 enginePriv->erroredBindings->removeError();
             }
         }
     }
 }
completeCreate()
void QDeclarativeComponentPrivate::completeCreate ()
Definition at line 1087 of file qdeclarativecomponent.cpp.
 {
     if (state.completePending) {
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
         complete(ep, &state);
         QDeclarativeDebugTrace::endRange(QDeclarativeDebugTrace::Creating);
     }
 }
createObject()
QScriptValue QDeclarativeComponentPrivate::createObject (QObject * publicParent, const QScriptValue valuemap)
Definition at line 733 of file qdeclarativecomponent.cpp.
 {
     Q_Q(QDeclarativeComponent);
     QDeclarativeContext* ctxt = q->creationContext();
     if(!ctxt && engine)
         ctxt = engine->rootContext();
     if (!ctxt)
         return QScriptValue(QScriptValue::NullValue);
     QObject* ret = q->beginCreate(ctxt);
     if (!ret) {
         q->completeCreate();
         return QScriptValue(QScriptValue::NullValue);
     }
     if (publicParent) {
         ret->setParent(publicParent);
         QList<QDeclarativePrivate::AutoParentFunction> functions = QDeclarativeMetaType::parentFunctions();
         bool needParent = false;
         for (int ii = 0; ii < functions.count(); ++ii) {
             QDeclarativePrivate::AutoParentResult res = functions.at(ii)(ret, publicParent);
             if (res == QDeclarativePrivate::Parented) {
                 needParent = false;
                 break;
             } else if (res == QDeclarativePrivate::IncompatibleParent) {
                 needParent = true;
             }
         }
         if (needParent)
             qWarning("QDeclarativeComponent: Created graphical object was not placed in the graphics scene.");
     }
     QDeclarativeEnginePrivate *priv = QDeclarativeEnginePrivate::get(engine);
     QDeclarativeData::get(ret, true)->setImplicitDestructible();
     QScriptValue newObject = priv->objectClass->newQObject(ret, QMetaType::QObjectStar);
     if (valuemap.isObject() && !valuemap.isArray()) {
         //Iterate through and assign properties
         QScriptValueIterator it(valuemap);
         while (it.hasNext()) {
             it.next();
             QScriptValue prop = newObject;
             QString propName = it.name();
             int index = propName.indexOf(QLatin1Char('.'));
             if (index > 0) {
                 QString subProp = propName;
                 int lastIndex = 0;
                 while (index > 0) {
                     subProp = propName.mid(lastIndex, index - lastIndex);
                     prop = prop.property(subProp);
                     lastIndex = index + 1;
                     index = propName.indexOf(QLatin1Char('.'), index + 1);
                 }
                 prop.setProperty(propName.mid(propName.lastIndexOf(QLatin1Char('.')) + 1), it.value());
             } else {
                 newObject.setProperty(propName, it.value());
             }
         }
     }
     q->completeCreate();
     return newObject;
 }
fromTypeData()
void QDeclarativeComponentPrivate::fromTypeData (QDeclarativeTypeData * data)
Definition at line 277 of file qdeclarativecomponent.cpp.
Referenced by typeDataReady().
 {
     url = data->finalUrl();
     QDeclarativeCompiledData *c = data->compiledData();
     if (!c) {
         Q_ASSERT(data->isError());
         state.errors = data->errors();
     } else {
         cc = c;
     }
     data->release();
 }
get()
static QDeclarativeComponentPrivate* QDeclarativeComponentPrivate::get (QDeclarativeComponent * c) inline static
Definition at line 126 of file qdeclarativecomponent_p.h.
Referenced by QDeclarativeEnginePrivate::createComponent(), and QDeclarativeVME::run().
{
         return static_cast<QDeclarativeComponentPrivate *>(QObjectPrivate::get(c));
     }
typeDataProgress()
void QDeclarativeComponentPrivate::typeDataProgress (QDeclarativeTypeData * , qreal p) virtual
Reimplemented from QDeclarativeTypeData::TypeDataCallback.
Definition at line 268 of file qdeclarativecomponent.cpp.
 {
     Q_Q(QDeclarativeComponent);
     progress = p;
     emit q->progressChanged(p);
 }
typeDataReady()
void QDeclarativeComponentPrivate::typeDataReady (QDeclarativeTypeData *) virtual
Reimplemented from QDeclarativeTypeData::TypeDataCallback.
Definition at line 256 of file qdeclarativecomponent.cpp.
 {
     Q_Q(QDeclarativeComponent);
     Q_ASSERT(typeData);
     fromTypeData(typeData);
     typeData = 0;
     emit q->statusChanged(q->status());
 }
Properties
cc
QDeclarativeCompiledData* QDeclarativeComponentPrivate::cc
Definition at line 98 of file qdeclarativecomponent_p.h.
Referenced by clear(), and fromTypeData().
count
int QDeclarativeComponentPrivate::count
Definition at line 97 of file qdeclarativecomponent_p.h.
Referenced by QDeclarativeContextPrivate::context_count().
creationContext
QDeclarativeGuardedContextData QDeclarativeComponentPrivate::creationContext
Definition at line 122 of file qdeclarativecomponent_p.h.
Referenced by QDeclarativeEnginePrivate::createComponent(), and QDeclarativeVME::run().
engine
QDeclarativeEngine* QDeclarativeComponentPrivate::engine
Definition at line 121 of file qdeclarativecomponent_p.h.
progress
qreal QDeclarativeComponentPrivate::progress
Definition at line 94 of file qdeclarativecomponent_p.h.
Referenced by typeDataProgress().
start
int QDeclarativeComponentPrivate::start
Definition at line 96 of file qdeclarativecomponent_p.h.
state
ConstructionState QDeclarativeComponentPrivate::state
Definition at line 109 of file qdeclarativecomponent_p.h.
Referenced by fromTypeData().
typeData
QDeclarativeTypeData* QDeclarativeComponentPrivate::typeData
Definition at line 87 of file qdeclarativecomponent_p.h.
Referenced by clear(), and typeDataReady().
url
QUrl QDeclarativeComponentPrivate::url
Definition at line 93 of file qdeclarativecomponent_p.h.
Referenced by fromTypeData().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecomponent_p.h
/src/declarative/qml/qdeclarativecomponent.cpp