Qt 4.8: QRegExpCharClass Class Reference
QRegExpCharClass Class Reference
Public Functions
void addCategories (int cats)
void addRange (ushort from, ushort to)
void addSingleton (ushort ch)
void clear ()
void dump () const
const QVector< int > & firstOccurrence () const
bool in (QChar ch) const
bool negative () const
QRegExpCharClass & operator= (const QRegExpCharClass &cc)
QRegExpCharClass ()
QRegExpCharClass (const QRegExpCharClass &cc)
void setNegative (bool negative)
Properties
int c
bool n
QVector< int > occ1
QVector< QRegExpCharClassRange > r
Detailed Description
Definition at line 1022 of file qregexp.cpp.
Constructors and Destructors
QRegExpCharClass() [1/2]
QRegExpCharClass::QRegExpCharClass ()
Definition at line 2323 of file qregexp.cpp.
     : c(0), n(false)
 {
 #ifndef QT_NO_REGEXP_OPTIM
     occ1.fill(NoOccurrence, NumBadChars);
 #endif
 }
QRegExpCharClass() [2/2]
QRegExpCharClass::QRegExpCharClass (const QRegExpCharClass & cc) inline
Definition at line 1026 of file qregexp.cpp.
 { operator=(cc); }
Functions
addCategories()
void QRegExpCharClass::addCategories (int cats)
Definition at line 2357 of file qregexp.cpp.
Referenced by QRegExpEngine::getEscape().
 {
     c |= cats;
 #ifndef QT_NO_REGEXP_OPTIM
     occ1.fill(0, NumBadChars);
 #endif
 }
addRange()
void QRegExpCharClass::addRange (ushort from, ushort to)
Definition at line 2365 of file qregexp.cpp.
Referenced by QRegExpEngine::getEscape(), and QRegExpEngine::getToken().
 {
     if (from > to)
         qSwap(from, to);
     int m = r.size();
     r.resize(m + 1);
     r[m].from = from;
     r[m].len = to - from + 1;
 #ifndef QT_NO_REGEXP_OPTIM
     int i;
     if (to - from < NumBadChars) {
         if (from % NumBadChars <= to % NumBadChars) {
             for (i = from % NumBadChars; i <= to % NumBadChars; i++)
                 occ1[i] = 0;
         } else {
             for (i = 0; i <= to % NumBadChars; i++)
                 occ1[i] = 0;
             for (i = from % NumBadChars; i < NumBadChars; i++)
                 occ1[i] = 0;
         }
     } else {
         occ1.fill(0, NumBadChars);
     }
 #endif
 }
addSingleton()
void QRegExpCharClass::addSingleton (ushort ch) inline
Definition at line 1035 of file qregexp.cpp.
Referenced by QRegExpEngine::getEscape(), and QRegExpEngine::getToken().
 { addRange(ch, ch); }
clear()
void QRegExpCharClass::clear ()
Definition at line 2342 of file qregexp.cpp.
Referenced by QRegExpEngine::getToken().
 {
     c = 0;
     r.resize(0);
     n = false;
 }
dump()
void QRegExpCharClass::dump () const
Definition at line 2415 of file qregexp.cpp.
 {
     int i;
     qDebug("    %stive character class", n ? "nega" : "posi");
 #ifndef QT_NO_REGEXP_CCLASS
     if (c != 0)
         qDebug("      categories 0x%.8x", c);
 #endif
     for (i = 0; i < r.size(); i++)
         qDebug("      0x%.4x through 0x%.4x", r[i].from, r[i].from + r[i].len - 1);
 }
firstOccurrence()
const QVector<int>& QRegExpCharClass::firstOccurrence () const inline
Definition at line 1039 of file qregexp.cpp.
Referenced by QRegExpEngine::Box::set().
 { return occ1; }
in()
bool QRegExpCharClass::in (QChar ch) const
Definition at line 2393 of file qregexp.cpp.
Referenced by QRegExpMatchState::matchHere().
 {
 #ifndef QT_NO_REGEXP_OPTIM
     if (occ1.at(BadChar(ch)) == NoOccurrence)
         return n;
 #endif
     if (c != 0 && (c & (1 << (int)ch.category())) != 0)
         return !n;
     const int uc = ch.unicode();
     int size = r.size();
     for (int i = 0; i < size; ++i) {
         const QRegExpCharClassRange &range = r.at(i);
         if (uint(uc - range.from) < uint(r.at(i).len))
             return !n;
     }
     return n;
 }
negative()
bool QRegExpCharClass::negative () const inline
Definition at line 1031 of file qregexp.cpp.
Referenced by QRegExpEngine::getEscape(), QRegExpMatchState::matchHere(), and setNegative().
 { return n; }
operator=()
QRegExpCharClass & QRegExpCharClass::operator= (const QRegExpCharClass & cc)
Definition at line 2331 of file qregexp.cpp.
 {
     c = cc.c;
     r = cc.r;
     n = cc.n;
 #ifndef QT_NO_REGEXP_OPTIM
     occ1 = cc.occ1;
 #endif
     return *this;
 }
setNegative()
void QRegExpCharClass::setNegative (bool negative)
Definition at line 2349 of file qregexp.cpp.
Referenced by QRegExpEngine::getEscape(), and QRegExpEngine::getToken().
 {
     n = negative;
 #ifndef QT_NO_REGEXP_OPTIM
     occ1.fill(0, NumBadChars);
 #endif
 }
Properties
c
int QRegExpCharClass::c private
Definition at line 1047 of file qregexp.cpp.
Referenced by addCategories(), clear(), dump(), in(), and operator=().
n
bool QRegExpCharClass::n private
Definition at line 1049 of file qregexp.cpp.
Referenced by clear(), dump(), in(), operator=(), and setNegative().
occ1
QVector<int> QRegExpCharClass::occ1 private
Definition at line 1051 of file qregexp.cpp.
Referenced by addCategories(), addRange(), in(), operator=(), QRegExpCharClass(), and setNegative().
r
QVector<QRegExpCharClassRange> QRegExpCharClass::r private
Definition at line 1048 of file qregexp.cpp.
Referenced by addRange(), clear(), dump(), in(), and operator=().
The documentation for this class was generated from the following file:
/src/corelib/tools/qregexp.cpp