Qt 4.8: QZipWriterPrivate Class Reference
QZipWriterPrivate Class Reference
Public Types
enum EntryType { Directory, File, Symlink }
Public Functions
void addEntry (EntryType type, const QString &fileName, const QByteArray &contents)
QZipWriterPrivate (QIODevice *device, bool ownDev)
Public Functions inherited from QZipPrivate
void fillFileInfo (int index, QZipReader::FileInfo &fileInfo) const
QZipPrivate (QIODevice *device, bool ownDev)
~QZipPrivate ()
Public Variables
QZipWriter::CompressionPolicy compressionPolicy
QFile::Permissions permissions
QZipWriter::Status status
Public Variables inherited from QZipPrivate
QByteArray comment
QIODevice * device
bool dirtyFileTree
QList< FileHeader > fileHeaders
bool ownDevice
uint start_of_directory
Detailed Description
Definition at line 443 of file qzip.cpp.
Enumerations
EntryType
enum QZipWriterPrivate::EntryType
Enumerator
Directory
File
Symlink
Definition at line 458 of file qzip.cpp.
 { Directory, File, Symlink };
Constructors and Destructors
QZipWriterPrivate()
QZipWriterPrivate::QZipWriterPrivate (QIODevice * device, bool ownDev) inline
Definition at line 446 of file qzip.cpp.
         : QZipPrivate(device, ownDev),
         status(QZipWriter::NoError),
         permissions(QFile::ReadOwner | QFile::WriteOwner),
         compressionPolicy(QZipWriter::AlwaysCompress)
     {
     }
Functions
addEntry()
void QZipWriterPrivate::addEntry (EntryType type, const QString & fileName, const QByteArray & contents)
Definition at line 568 of file qzip.cpp.
Referenced by QZipWriter::addDirectory(), QZipWriter::addFile(), and QZipWriter::addSymLink().
 {
 #ifndef NDEBUG
     static const char *entryTypes[] = {
         "directory",
         "file     ",
         "symlink  " };
     ZDEBUG() << "adding" << entryTypes[type] <<":" << fileName.toUtf8().data() << (type == 2 ? QByteArray(" -> " + contents).constData() : "");
 #endif
     if (! (device->isOpen() || device->open(QIODevice::WriteOnly))) {
         status = QZipWriter::FileOpenError;
         return;
     }
     device->seek(start_of_directory);
     // don't compress small files
     QZipWriter::CompressionPolicy compression = compressionPolicy;
     if (compressionPolicy == QZipWriter::AutoCompress) {
         if (contents.length() < 64)
             compression = QZipWriter::NeverCompress;
         else
             compression = QZipWriter::AlwaysCompress;
     }
     FileHeader header;
     memset(&header.h, 0, sizeof(CentralFileHeader));
     writeUInt(header.h.signature, 0x02014b50);
     writeUShort(header.h.version_needed, 0x14);
     writeUInt(header.h.uncompressed_size, contents.length());
     writeMSDosDate(header.h.last_mod_file, QDateTime::currentDateTime());
     QByteArray data = contents;
     if (compression == QZipWriter::AlwaysCompress) {
         writeUShort(header.h.compression_method, 8);
        ulong len = contents.length();
         // shamelessly copied form zlib
         len += (len >> 12) + (len >> 14) + 11;
         int res;
         do {
             data.resize(len);
             res = deflate((uchar*)data.data(), &len, (const uchar*)contents.constData(), contents.length());
             switch (res) {
             case Z_OK:
                 data.resize(len);
                 break;
             case Z_MEM_ERROR:
                 qWarning("QZip: Z_MEM_ERROR: Not enough memory to compress file, skipping");
                 data.resize(0);
                 break;
             case Z_BUF_ERROR:
                 len *= 2;
                 break;
             }
         } while (res == Z_BUF_ERROR);
     }
 // TODO add a check if data.length() > contents.length().  Then try to store the original and revert the compression method to be uncompressed
     writeUInt(header.h.compressed_size, data.length());
     uint crc_32 = ::crc32(0, 0, 0);
     crc_32 = ::crc32(crc_32, (const uchar *)contents.constData(), contents.length());
     writeUInt(header.h.crc_32, crc_32);
     header.file_name = fileName.toLocal8Bit();
     if (header.file_name.size() > 0xffff) {
         qWarning("QZip: Filename too long, chopping it to 65535 characters");
         header.file_name = header.file_name.left(0xffff);
     }
     writeUShort(header.h.file_name_length, header.file_name.length());
     //h.extra_field_length[2];
     writeUShort(header.h.version_made, 3 << 8);
     //uchar internal_file_attributes[2];
     //uchar external_file_attributes[4];
     quint32 mode = permissionsToMode(permissions);
     switch (type) {
         case File: mode |= S_IFREG; break;
         case Directory: mode |= S_IFDIR; break;
         case Symlink: mode |= S_IFLNK; break;
     }
     writeUInt(header.h.external_file_attributes, mode << 16);
     writeUInt(header.h.offset_local_header, start_of_directory);
     fileHeaders.append(header);
     LocalFileHeader h = header.h.toLocalHeader();
     device->write((const char *)&h, sizeof(LocalFileHeader));
     device->write(header.file_name);
     device->write(data);
     start_of_directory = device->pos();
     dirtyFileTree = true;
 }
Properties
compressionPolicy
QZipWriter::CompressionPolicy QZipWriterPrivate::compressionPolicy
Definition at line 456 of file qzip.cpp.
Referenced by QZipWriter::compressionPolicy(), and QZipWriter::setCompressionPolicy().
permissions
QFile::Permissions QZipWriterPrivate::permissions
Definition at line 455 of file qzip.cpp.
Referenced by QZipWriter::creationPermissions(), and QZipWriter::setCreationPermissions().
status
QZipWriter::Status QZipWriterPrivate::status
Definition at line 454 of file qzip.cpp.
Referenced by QZipWriter::addFile(), and QZipWriter::status().
The documentation for this class was generated from the following file:
/src/gui/text/qzip.cpp