Qt 4.8: QTextTableData Class Reference
QTextTableData Class Reference
Public Functions
QFixed bottomPadding (const QTextFormat &format) const
void calcRowPosition (int row)
QFixedPoint cellPosition (const QTextTableCell &cell) const
QRectF cellRect (const QTextTableCell &cell) const
QFixed cellWidth (int column, int colspan) const
QFixed leftPadding (const QTextFormat &format) const
QFixed paddingProperty (const QTextFormat &format, QTextFormat::Property property) const
QFixed rightPadding (const QTextFormat &format) const
QFixed topPadding (const QTextFormat &format) const
void updateTableSize ()
Public Functions inherited from QTextFrameData
QTextFrameData ()
Public Functions inherited from QTextFrameLayoutData
virtual ~QTextFrameLayoutData ()
Public Variables
QFixed cellPadding
QFixed cellSpacing
QVector< QFixed > cellVerticalOffsets
QMultiHash< int, QTextFrame * > childFrameMap
QVector< QFixed > columnPositions
qreal deviceScale
QFixed headerHeight
QVector< QFixed > heights
QVector< QFixed > maxWidths
QVector< QFixed > minWidths
QVector< QFixed > rowPositions
QVector< QFixed > widths
Public Variables inherited from QTextFrameData
QFixed border
QFixed bottomMargin
QFixed contentsHeight
QFixed contentsWidth
QTextLayoutStruct * currentLayoutStruct
QFixed effectiveBottomMargin
QFixed effectiveTopMargin
QList< QPointer< QTextFrame > > floats
bool layoutDirty
QFixed leftMargin
QFixed maximumWidth
QFixed minimumWidth
QFixed oldContentsWidth
QFixed padding
QFixedPoint position
QFixed rightMargin
QFixedSize size
bool sizeDirty
QFixed topMargin
Private Functions
QFixedPoint cellPosition (int row, int col) const
Detailed Description
Definition at line 161 of file qtextdocumentlayout.cpp.
Functions
bottomPadding()
QFixed QTextTableData::bottomPadding (const QTextFormat & format) const inline
Definition at line 209 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutCell(), and QTextDocumentLayoutPrivate::layoutTable().
     {
         return paddingProperty(format, QTextFormat::TableCellBottomPadding);
     }
calcRowPosition()
void QTextTableData::calcRowPosition (int row) inline
Definition at line 185 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
     {
         if (row > 0)
             rowPositions[row] = rowPositions.at(row - 1) + heights.at(row - 1) + border + cellSpacing + border;
     }
cellPosition() [1/2]
QFixedPoint QTextTableData::cellPosition (const QTextTableCell & cell) const inline
Definition at line 224 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::hitTest().
     {
         const QTextFormat fmt = cell.format();
         return cellPosition(cell.row(), cell.column()) + QFixedPoint(leftPadding(fmt), topPadding(fmt));
     }
cellPosition() [2/2]
QFixedPoint QTextTableData::cellPosition (int row, int col) const inline private
Definition at line 233 of file qtextdocumentlayout.cpp.
     { return QFixedPoint(columnPositions.at(col), rowPositions.at(row) + cellVerticalOffsets.at(col + row * widths.size())); }
cellRect()
QRectF QTextTableData::cellRect (const QTextTableCell & cell) const
Definition at line 273 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFrame(), and QTextDocumentLayoutPrivate::hitTest().
 {
     const int row = cell.row();
     const int rowSpan = cell.rowSpan();
     const int column = cell.column();
     const int colSpan = cell.columnSpan();
     return QRectF(columnPositions.at(column).toReal(),
                   rowPositions.at(row).toReal(),
                   (columnPositions.at(column + colSpan - 1) + widths.at(column + colSpan - 1) - columnPositions.at(column)).toReal(),
                   (rowPositions.at(row + rowSpan - 1) + heights.at(row + rowSpan - 1) - rowPositions.at(row)).toReal());
 }
cellWidth()
QFixed QTextTableData::cellWidth (int column, int colspan) const inline
Definition at line 181 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
     { return columnPositions.at(column + colspan - 1) + widths.at(column + colspan - 1)
              - columnPositions.at(column); }
leftPadding()
QFixed QTextTableData::leftPadding (const QTextFormat & format) const inline
Definition at line 214 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawTableCell(), and QTextDocumentLayoutPrivate::layoutTable().
     {
         return paddingProperty(format, QTextFormat::TableCellLeftPadding);
     }
paddingProperty()
QFixed QTextTableData::paddingProperty (const QTextFormat & format, QTextFormat::Property property) const inline
Definition at line 193 of file qtextdocumentlayout.cpp.
     {
         QVariant v = format.property(property);
         if (v.isNull()) {
             return cellPadding;
         } else {
             Q_ASSERT(v.userType() == QVariant::Double || v.userType() == QMetaType::Float);
             return QFixed::fromReal(v.toReal() * deviceScale);
         }
     }
rightPadding()
QFixed QTextTableData::rightPadding (const QTextFormat & format) const inline
Definition at line 219 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
     {
         return paddingProperty(format, QTextFormat::TableCellRightPadding);
     }
topPadding()
QFixed QTextTableData::topPadding (const QTextFormat & format) const inline
Definition at line 204 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawTableCell(), QTextDocumentLayoutPrivate::layoutCell(), and QTextDocumentLayoutPrivate::layoutTable().
     {
         return paddingProperty(format, QTextFormat::TableCellTopPadding);
     }
updateTableSize()
void QTextTableData::updateTableSize ()
Definition at line 261 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
 {
     const QFixed effectiveTopMargin = this->topMargin + border + padding;
     const QFixed effectiveBottomMargin = this->bottomMargin + border + padding;
     const QFixed effectiveLeftMargin = this->leftMargin + border + padding;
     const QFixed effectiveRightMargin = this->rightMargin + border + padding;
     size.height = contentsHeight == -1
                    ? rowPositions.last() + heights.last() + padding + border + cellSpacing + effectiveBottomMargin
                    : effectiveTopMargin + contentsHeight + effectiveBottomMargin;
     size.width = effectiveLeftMargin + contentsWidth + effectiveRightMargin;
 }
Properties
cellPadding
QFixed QTextTableData::cellPadding
Definition at line 164 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutFrame(), and QTextDocumentLayoutPrivate::layoutTable().
cellSpacing
QFixed QTextTableData::cellSpacing
Definition at line 164 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawTableCell(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFrame(), and QTextDocumentLayoutPrivate::layoutTable().
cellVerticalOffsets
QVector<QFixed> QTextTableData::cellVerticalOffsets
Definition at line 173 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawTableCell(), and QTextDocumentLayoutPrivate::layoutTable().
childFrameMap
QMultiHash<int, QTextFrame *> QTextTableData::childFrameMap
Definition at line 179 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawTableCell(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), and QTextDocumentLayoutPrivate::layoutTable().
columnPositions
QVector<QFixed> QTextTableData::columnPositions
Definition at line 170 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::hitTest(), and QTextDocumentLayoutPrivate::layoutTable().
deviceScale
qreal QTextTableData::deviceScale
Definition at line 165 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
headerHeight
QFixed QTextTableData::headerHeight
Definition at line 175 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawTableCell(), and QTextDocumentLayoutPrivate::layoutTable().
heights
QVector<QFixed> QTextTableData::heights
Definition at line 169 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
maxWidths
QVector<QFixed> QTextTableData::maxWidths
Definition at line 167 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
minWidths
QVector<QFixed> QTextTableData::minWidths
Definition at line 166 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
rowPositions
QVector<QFixed> QTextTableData::rowPositions
Definition at line 171 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::hitTest(), QTextDocumentLayoutPrivate::layoutCell(), and QTextDocumentLayoutPrivate::layoutTable().
widths
QVector<QFixed> QTextTableData::widths
Definition at line 168 of file qtextdocumentlayout.cpp.
Referenced by QTextDocumentLayoutPrivate::layoutTable().
The documentation for this class was generated from the following file:
/src/gui/text/qtextdocumentlayout.cpp