Qt 4.8: QItemSelectionModelPrivate Class Reference
QItemSelectionModelPrivate Class Reference
#include <qitemselectionmodel_p.h>
Public Functions
void _q_columnsAboutToBeInserted (const QModelIndex &parent, int start, int end)
Split selection ranges if columns are about to be inserted in the middle.
void _q_columnsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
void _q_layoutAboutToBeChanged ()
Split selection into individual (persistent) indexes.
void _q_layoutChanged ()
Merge the selected indexes into selection ranges again.
void _q_rowsAboutToBeInserted (const QModelIndex &parent, int start, int end)
Split selection ranges if rows are about to be inserted in the middle.
void _q_rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
QItemSelection expandSelection (const QItemSelection &selection, QItemSelectionModel::SelectionFlags command) const
void finalize ()
void initModel (QAbstractItemModel *model)
QItemSelectionModelPrivate ()
void remove (QList< QItemSelectionRange > &r)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QItemSelectionModel::SelectionFlags currentCommand
QPersistentModelIndex currentIndex
QItemSelection currentSelection
QPointer< QAbstractItemModel > model
QItemSelection ranges
QList< QPersistentModelIndex > savedPersistentCurrentIndexes
QList< QPersistentModelIndex > savedPersistentIndexes
int tableColCount
QPersistentModelIndex tableParent
int tableRowCount
bool tableSelected
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Detailed Description
Definition at line 61 of file qitemselectionmodel_p.h.
Constructors and Destructors
QItemSelectionModelPrivate()
QItemSelectionModelPrivate::QItemSelectionModelPrivate () inline
Definition at line 65 of file qitemselectionmodel_p.h.
       : model(0),
         currentCommand(QItemSelectionModel::NoUpdate),
         tableSelected(false), tableColCount(0), tableRowCount(0) {}
Functions
_q_columnsAboutToBeInserted()
void QItemSelectionModelPrivate::_q_columnsAboutToBeInserted (const QModelIndex & parent, int start, int end)
Split selection ranges if columns are about to be inserted in the middle.
Warning
This function is not part of the public interface.
Definition at line 794 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate().
 {
     Q_UNUSED(end);
     finalize();
     QList<QItemSelectionRange> split;
     QList<QItemSelectionRange>::iterator it = ranges.begin();
     for (; it != ranges.end(); ) {
         if ((*it).isValid() && (*it).parent() == parent
             && (*it).left() < start && (*it).right() >= start) {
             QModelIndex bottomMiddle = model->index((*it).bottom(), start - 1, (*it).parent());
             QItemSelectionRange left((*it).topLeft(), bottomMiddle);
             QModelIndex topMiddle = model->index((*it).top(), start, (*it).parent());
             QItemSelectionRange right(topMiddle, (*it).bottomRight());
             it = ranges.erase(it);
             split.append(left);
             split.append(right);
         } else {
             ++it;
         }
     }
     ranges += split;
 }
_q_columnsAboutToBeRemoved()
void QItemSelectionModelPrivate::_q_columnsAboutToBeRemoved (const QModelIndex & parent, int start, int end)
Warning
This function is not part of the public interface.
Definition at line 758 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate().
 {
     Q_Q(QItemSelectionModel);
     // update current index
     if (currentIndex.isValid() && parent == currentIndex.parent()
         && currentIndex.column() >= start && currentIndex.column() <= end) {
         QModelIndex old = currentIndex;
         if (start > 0) // there are columns to the left of the change
             currentIndex = model->index(old.row(), start - 1, parent);
         else if (model && end < model->columnCount() - 1) // there are columns to the right of the change
             currentIndex = model->index(old.row(), end + 1, parent);
         else // there are no columns left in the table
             currentIndex = QModelIndex();
         emit q->currentChanged(currentIndex, old);
         if (currentIndex.row() != old.row())
             emit q->currentRowChanged(currentIndex, old);
         emit q->currentColumnChanged(currentIndex, old);
     }
     // update selections
     QModelIndex tl = model->index(0, start, parent);
     QModelIndex br = model->index(model->rowCount(parent) - 1, end, parent);
     q->select(QItemSelection(tl, br), QItemSelectionModel::Deselect);
     finalize();
 }
_q_layoutAboutToBeChanged()
void QItemSelectionModelPrivate::_q_layoutAboutToBeChanged ()
Split selection into individual (persistent) indexes.
Warning
This function is not part of the public interface.
This is done in preparation for the layoutChanged() signal, where the indexes can be merged again.
Definition at line 860 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate().
 {
     savedPersistentIndexes.clear();
     savedPersistentCurrentIndexes.clear();
     // optimization for when all indexes are selected
     // (only if there is lots of items (1000) because this is not entirely correct)
     if (ranges.isEmpty() && currentSelection.count() == 1) {
         QItemSelectionRange range = currentSelection.first();
         QModelIndex parent = range.parent();
         tableRowCount = model->rowCount(parent);
         tableColCount = model->columnCount(parent);
         if (tableRowCount * tableColCount > 1000
             && range.top() == 0
             && range.left() == 0
             && range.bottom() == tableRowCount - 1
             && range.right() == tableColCount - 1) {
             tableSelected = true;
             tableParent = parent;
             return;
         }
     }
     tableSelected = false;
     QModelIndexList indexes = ranges.indexes();
     QModelIndexList::const_iterator it;
     for (it = indexes.constBegin(); it != indexes.constEnd(); ++it)
         savedPersistentIndexes.append(QPersistentModelIndex(*it));
     indexes = currentSelection.indexes();
     for (it = indexes.constBegin(); it != indexes.constEnd(); ++it)
         savedPersistentCurrentIndexes.append(QPersistentModelIndex(*it));
 }
_q_layoutChanged()
void QItemSelectionModelPrivate::_q_layoutChanged ()
Merge the selected indexes into selection ranges again.
Warning
This function is not part of the public interface.
Definition at line 956 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate().
 {
     // special case for when all indexes are selected
     if (tableSelected && tableColCount == model->columnCount(tableParent)
         && tableRowCount == model->rowCount(tableParent)) {
         ranges.clear();
         currentSelection.clear();
         int bottom = tableRowCount - 1;
         int right = tableColCount - 1;
         QModelIndex tl = model->index(0, 0, tableParent);
         QModelIndex br = model->index(bottom, right, tableParent);
         currentSelection << QItemSelectionRange(tl, br);
         tableParent = QModelIndex();
         tableSelected = false;
         return;
     }
     if (savedPersistentCurrentIndexes.isEmpty() && savedPersistentIndexes.isEmpty()) {
         // either the selection was actually empty, or we
         // didn't get the layoutAboutToBeChanged() signal
         return;
     }
     // clear the "old" selection
     ranges.clear();
     currentSelection.clear();
     // sort the "new" selection, as preparation for merging
     qStableSort(savedPersistentIndexes.begin(), savedPersistentIndexes.end());
     qStableSort(savedPersistentCurrentIndexes.begin(), savedPersistentCurrentIndexes.end());
     // update the selection by merging the individual indexes
     ranges = mergeIndexes(savedPersistentIndexes);
     currentSelection = mergeIndexes(savedPersistentCurrentIndexes);
     // release the persistent indexes
     savedPersistentIndexes.clear();
     savedPersistentCurrentIndexes.clear();
 }
_q_rowsAboutToBeInserted()
void QItemSelectionModelPrivate::_q_rowsAboutToBeInserted (const QModelIndex & parent, int start, int end)
Split selection ranges if rows are about to be inserted in the middle.
Warning
This function is not part of the public interface.
Definition at line 826 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate().
 {
     Q_UNUSED(end);
     finalize();
     QList<QItemSelectionRange> split;
     QList<QItemSelectionRange>::iterator it = ranges.begin();
     for (; it != ranges.end(); ) {
         if ((*it).isValid() && (*it).parent() == parent
             && (*it).top() < start && (*it).bottom() >= start) {
             QModelIndex middleRight = model->index(start - 1, (*it).right(), (*it).parent());
             QItemSelectionRange top((*it).topLeft(), middleRight);
             QModelIndex middleLeft = model->index(start, (*it).left(), (*it).parent());
             QItemSelectionRange bottom(middleLeft, (*it).bottomRight());
             it = ranges.erase(it);
             split.append(top);
             split.append(bottom);
         } else {
             ++it;
         }
     }
     ranges += split;
 }
_q_rowsAboutToBeRemoved()
void QItemSelectionModelPrivate::_q_rowsAboutToBeRemoved (const QModelIndex & parent, int start, int end)
Warning
This function is not part of the public interface.
Definition at line 687 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate().
 {
     Q_Q(QItemSelectionModel);
     finalize();
     // update current index
     if (currentIndex.isValid() && parent == currentIndex.parent()
         && currentIndex.row() >= start && currentIndex.row() <= end) {
         QModelIndex old = currentIndex;
         if (start > 0) // there are rows left above the change
             currentIndex = model->index(start - 1, old.column(), parent);
         else if (model && end < model->rowCount(parent) - 1) // there are rows left below the change
             currentIndex = model->index(end + 1, old.column(), parent);
         else // there are no rows left in the table
             currentIndex = QModelIndex();
         emit q->currentChanged(currentIndex, old);
         emit q->currentRowChanged(currentIndex, old);
         if (currentIndex.column() != old.column())
             emit q->currentColumnChanged(currentIndex, old);
     }
     QItemSelection deselected;
     QItemSelection newParts;
     QItemSelection::iterator it = ranges.begin();
     while (it != ranges.end()) {
         if (it->topLeft().parent() != parent) {  // Check parents until reaching root or contained in range
             QModelIndex itParent = it->topLeft().parent();
             while (itParent.isValid() && itParent.parent() != parent)
                 itParent = itParent.parent();
             if (itParent.isValid() && start <= itParent.row() && itParent.row() <= end) {
                 deselected.append(*it);
                 it = ranges.erase(it);
             } else {
                 ++it;
             }
         } else if (start <= it->bottom() && it->bottom() <= end    // Full inclusion
                    && start <= it->top() && it->top() <= end) {
             deselected.append(*it);
             it = ranges.erase(it);
         } else if (start <= it->top() && it->top() <= end) {      // Top intersection
             deselected.append(QItemSelectionRange(it->topLeft(), model->index(end, it->left(), it->parent())));
             *it = QItemSelectionRange(model->index(end + 1, it->left(), it->parent()), it->bottomRight());
             ++it;
         } else if (start <= it->bottom() && it->bottom() <= end) {    // Bottom intersection
             deselected.append(QItemSelectionRange(model->index(start, it->right(), it->parent()), it->bottomRight()));
             *it = QItemSelectionRange(it->topLeft(), model->index(start - 1, it->right(), it->parent()));
             ++it;
         } else if (it->top() < start && end < it->bottom()) { // Middle intersection
             // If the parent contains (1, 2, 3, 4, 5, 6, 7, 8) and [3, 4, 5, 6] is selected,
             // and [4, 5] is removed, we need to split [3, 4, 5, 6] into [3], [4, 5] and [6].
             // [4, 5] is appended to deselected, and [3] and [6] remain part of the selection
             // in ranges.
             const QItemSelectionRange removedRange(model->index(start, it->right(), it->parent()),
                                                     model->index(end, it->left(), it->parent()));
             deselected.append(removedRange);
             QItemSelection::split(*it, removedRange, &newParts);
             it = ranges.erase(it);
         } else
             ++it;
     }
     ranges.append(newParts);
     if (!deselected.isEmpty())
         emit q->selectionChanged(QItemSelection(), deselected);
 }
expandSelection()
QItemSelection QItemSelectionModelPrivate::expandSelection (const QItemSelection & selection, QItemSelectionModel::SelectionFlags command) const
Warning
This function is not part of the public interface.
returns a QItemSelection where all ranges have been expanded to: Rows: left: 0 and right: columnCount()-1 Columns: top: 0 and bottom: rowCount()-1
Definition at line 653 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModelPrivate().
 {
     if (selection.isEmpty() && !((command & QItemSelectionModel::Rows) ||
                                  (command & QItemSelectionModel::Columns)))
         return selection;
     QItemSelection expanded;
     if (command & QItemSelectionModel::Rows) {
         for (int i = 0; i < selection.count(); ++i) {
             QModelIndex parent = selection.at(i).parent();
             int colCount = model->columnCount(parent);
             QModelIndex tl = model->index(selection.at(i).top(), 0, parent);
             QModelIndex br = model->index(selection.at(i).bottom(), colCount - 1, parent);
             //we need to merge because the same row could have already been inserted
             expanded.merge(QItemSelection(tl, br), QItemSelectionModel::Select);
         }
     }
     if (command & QItemSelectionModel::Columns) {
         for (int i = 0; i < selection.count(); ++i) {
             QModelIndex parent = selection.at(i).parent();
             int rowCount = model->rowCount(parent);
             QModelIndex tl = model->index(0, selection.at(i).left(), parent);
             QModelIndex br = model->index(rowCount - 1, selection.at(i).right(), parent);
             //we need to merge because the same column could have already been inserted
             expanded.merge(QItemSelection(tl, br), QItemSelectionModel::Select);
         }
     }
     return expanded;
 }
finalize()
void QItemSelectionModelPrivate::finalize () inline
Definition at line 89 of file qitemselectionmodel_p.h.
     {
         ranges.merge(currentSelection, currentCommand);
         if (!currentSelection.isEmpty())  // ### perhaps this should be in QList
             currentSelection.clear();
     }
initModel()
void QItemSelectionModelPrivate::initModel (QAbstractItemModel * model)
Definition at line 625 of file qitemselectionmodel.cpp.
Referenced by QItemSelectionModel::QItemSelectionModel(), and QItemSelectionModelPrivate().
 {
     this->model = model;
     if (model) {
         Q_Q(QItemSelectionModel);
         QObject::connect(model, SIGNAL(rowsAboutToBeRemoved(QModelIndex,int,int)),
                 q, SLOT(_q_rowsAboutToBeRemoved(QModelIndex,int,int)));
         QObject::connect(model, SIGNAL(columnsAboutToBeRemoved(QModelIndex,int,int)),
                 q, SLOT(_q_columnsAboutToBeRemoved(QModelIndex,int,int)));
         QObject::connect(model, SIGNAL(rowsAboutToBeInserted(QModelIndex,int,int)),
                 q, SLOT(_q_rowsAboutToBeInserted(QModelIndex,int,int)));
         QObject::connect(model, SIGNAL(columnsAboutToBeInserted(QModelIndex,int,int)),
                 q, SLOT(_q_columnsAboutToBeInserted(QModelIndex,int,int)));
         QObject::connect(model, SIGNAL(layoutAboutToBeChanged()),
                 q, SLOT(_q_layoutAboutToBeChanged()));
         QObject::connect(model, SIGNAL(layoutChanged()),
                 q, SLOT(_q_layoutChanged()));
     }
 }
remove()
void QItemSelectionModelPrivate::remove (QList< QItemSelectionRange > & r) inline
Definition at line 82 of file qitemselectionmodel_p.h.
     {
         QList<QItemSelectionRange>::const_iterator it = r.constBegin();
         for (; it != r.constEnd(); ++it)
             ranges.removeAll(*it);
     }
Properties
currentCommand
QItemSelectionModel::SelectionFlags QItemSelectionModelPrivate::currentCommand
Definition at line 100 of file qitemselectionmodel_p.h.
Referenced by finalize().
currentIndex
QPersistentModelIndex QItemSelectionModelPrivate::currentIndex
Definition at line 99 of file qitemselectionmodel_p.h.
currentSelection
QItemSelection QItemSelectionModelPrivate::currentSelection
Definition at line 98 of file qitemselectionmodel_p.h.
Referenced by finalize().
model
QPointer<QAbstractItemModel> QItemSelectionModelPrivate::model
Definition at line 96 of file qitemselectionmodel_p.h.
Referenced by QItemSelectionModelPrivate().
ranges
QItemSelection QItemSelectionModelPrivate::ranges
Definition at line 97 of file qitemselectionmodel_p.h.
Referenced by finalize(), and remove().
savedPersistentCurrentIndexes
QList<QPersistentModelIndex> QItemSelectionModelPrivate::savedPersistentCurrentIndexes
Definition at line 102 of file qitemselectionmodel_p.h.
savedPersistentIndexes
QList<QPersistentModelIndex> QItemSelectionModelPrivate::savedPersistentIndexes
Definition at line 101 of file qitemselectionmodel_p.h.
tableColCount
int QItemSelectionModelPrivate::tableColCount
Definition at line 106 of file qitemselectionmodel_p.h.
tableParent
QPersistentModelIndex QItemSelectionModelPrivate::tableParent
Definition at line 105 of file qitemselectionmodel_p.h.
tableRowCount
int QItemSelectionModelPrivate::tableRowCount
Definition at line 106 of file qitemselectionmodel_p.h.
tableSelected
bool QItemSelectionModelPrivate::tableSelected
Definition at line 104 of file qitemselectionmodel_p.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qitemselectionmodel_p.h
/src/gui/itemviews/qitemselectionmodel.cpp