Qt 4.8: QObjectCleanupHandler Class Reference
QObjectCleanupHandler Class Reference
The QObjectCleanupHandler class watches the lifetime of multiple QObjects.
#include <qobjectcleanuphandler.h>
Public Functions
QObject * add (QObject *object)
Adds object to this cleanup handler and returns the pointer to the object.
void clear ()
Deletes all objects in this cleanup handler.
bool isEmpty () const
Returns true if this cleanup handler is empty or if all objects in this cleanup handler have been destroyed; otherwise return false.
QObjectCleanupHandler ()
Constructs an empty QObjectCleanupHandler.
void remove (QObject *object)
Removes the object from this cleanup handler.
~QObjectCleanupHandler ()
Destroys the cleanup handler.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void objectDestroyed (QObject *)
Properties
QObjectList cleanupObjects
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QObjectCleanupHandler class watches the lifetime of multiple QObjects.
A QObjectCleanupHandler is useful whenever you need to know when a number of QObject that are owned by someone else have been deleted. This is important, for example, when referencing memory in an application that has been allocated in a shared library.
To keep track of some QObject, create a QObjectCleanupHandler, and add() the objects you are interested in. If you are no longer interested in tracking a particular object, use remove() to remove it from the cleanup handler. If an object being tracked by the cleanup handler gets deleted by someone else it will automatically be removed from the cleanup handler. You can delete all the objects in the cleanup handler with clear(), or by destroying the cleanup handler. isEmpty() returns true if the QObjectCleanupHandler has no objects to keep track of.
See also
QPointer
Definition at line 53 of file qobjectcleanuphandler.h.
Constructors and Destructors
QObjectCleanupHandler()
QObjectCleanupHandler::QObjectCleanupHandler ()
Constructs an empty QObjectCleanupHandler.
Definition at line 77 of file qobjectcleanuphandler.cpp.
 {
 }
~QObjectCleanupHandler()
QObjectCleanupHandler::~QObjectCleanupHandler ()
Destroys the cleanup handler.
All objects in this cleanup handler will be deleted.
See also
clear()
Definition at line 87 of file qobjectcleanuphandler.cpp.
 {
     clear();
 }
Functions
add()
QObject * QObjectCleanupHandler::add (QObject * object)
Adds object to this cleanup handler and returns the pointer to the object.
See also
remove()
Definition at line 98 of file qobjectcleanuphandler.cpp.
 {
     if (!object)
         return 0;
     connect(object, SIGNAL(destroyed(QObject*)), this, SLOT(objectDestroyed(QObject*)));
     cleanupObjects.insert(0, object);
     return object;
 }
clear()
void QObjectCleanupHandler::clear ()
Deletes all objects in this cleanup handler.
The cleanup handler becomes empty.
See also
isEmpty()
Definition at line 140 of file qobjectcleanuphandler.cpp.
Referenced by QWSSignalHandler::clear(), and ~QObjectCleanupHandler().
 {
     while (!cleanupObjects.isEmpty())
         delete cleanupObjects.takeFirst();
 }
isEmpty()
bool QObjectCleanupHandler::isEmpty () const
Returns true if this cleanup handler is empty or if all objects in this cleanup handler have been destroyed; otherwise return false.
See also
add() remove() clear()
Definition at line 129 of file qobjectcleanuphandler.cpp.
 {
     return cleanupObjects.isEmpty();
 }
objectDestroyed
void QObjectCleanupHandler::objectDestroyed (QObject * object) private slot
Definition at line 146 of file qobjectcleanuphandler.cpp.
Referenced by add(), and remove().
 {
     remove(object);
 }
remove()
void QObjectCleanupHandler::remove (QObject * object)
Removes the object from this cleanup handler.
The object will not be destroyed.
See also
add()
Definition at line 114 of file qobjectcleanuphandler.cpp.
 {
     int index;
     if ((index = cleanupObjects.indexOf(object)) != -1) {
         cleanupObjects.removeAt(index);
         disconnect(object, SIGNAL(destroyed(QObject*)), this, SLOT(objectDestroyed(QObject*)));
     }
 }
Properties
cleanupObjects
QObjectList QObjectCleanupHandler::cleanupObjects private
Definition at line 68 of file qobjectcleanuphandler.h.
Referenced by add(), clear(), isEmpty(), and remove().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qobjectcleanuphandler.h
/src/corelib/kernel/qobjectcleanuphandler.cpp