Qt 4.8: QAccessibleWidgetEx Class Reference
QAccessibleWidgetEx Class Reference
#include <qaccessiblewidget.h>
Public Functions
QString actionText (int action, Text t, int child) const
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
int childAt (int x, int y) const
Returns the 1-based index of the child that contains the screen coordinates (x, y).
int childCount () const
Returns the number of children that belong to this object.
bool doAction (int action, int child, const QVariantList &params)
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
int indexOfChild (const QAccessibleInterface *child) const
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
QVariant invokeMethodEx (Method method, int child, const QVariantList &params)
int navigate (RelationFlag rel, int entry, QAccessibleInterface **target) const
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
QAccessibleWidgetEx (QWidget *o, Role r=Client, const QString &name=QString())
QRect rect (int child) const
Returns the geometry of the object, or of the object's child if child is not 0.
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
Role role (int child) const
Returns the role of the object, or of the object's child if child is not 0.
State state (int child) const
Returns the current state of the object, or of the object's child if child is not 0.
QString text (Text t, int child) const
Returns the value of the text property t of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleObjectEx
bool isValid () const
Returns true if all the data necessary to use this interface implementation is valid (e.
QObject * object () const
Returns a pointer to the QObject this interface implementation provides information for.
QAccessibleObjectEx (QObject *object)
void setText (Text t, int child, const QString &text)
Sets the text property t of the object, or of the object's child if child is not 0, to text.
int userActionCount (int child) const
Returns the number of custom actions of the object, or of the object's child if child is not 0.
Public Functions inherited from QAccessibleInterfaceEx
virtual QAccessible2Interface * interface_cast (QAccessible2::InterfaceType)
virtual QVariant virtual_hook (const QVariant &data)
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Protected Functions
void addControllingSignal (const QString &signal)
QObject * parentObject () const
void setAccelerator (const QString &accel)
void setDescription (const QString &desc)
void setHelp (const QString &help)
void setValue (const QString &value)
QWidget * widget () const
~QAccessibleWidgetEx ()
Protected Functions inherited from QAccessibleObjectEx
virtual ~QAccessibleObjectEx ()
Properties
QAccessibleWidgetPrivate * d
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
Definition at line 97 of file qaccessiblewidget.h.
Constructors and Destructors
QAccessibleWidgetEx()
QAccessibleWidgetEx::QAccessibleWidgetEx (QWidget * o, Role r = Client, const QString & name = QString()) explicit
Definition at line 979 of file qaccessiblewidget.cpp.
     : QAccessibleObjectEx(o)
 {
     Q_ASSERT(widget());
     d = new QAccessibleWidgetPrivate();
     d->role = role;
     d->name = name;
     d->asking = 0;
 }
~QAccessibleWidgetEx()
QAccessibleWidgetEx::~QAccessibleWidgetEx () protected
Definition at line 1016 of file qaccessiblewidget.cpp.
 { delete d; }
Functions
actionText()
QString QAccessibleWidgetEx::actionText (int action, Text t, int child) const virtual
Returns the text property t of the action action supported by the object, or of the object's child if child is not 0.
See also
text(), userActionCount()
Reimplemented from QAccessibleObjectEx.
Reimplemented in QAccessibleComboBox, QAccessibleTabBar, QAccessibleSlider, QAccessibleToolButton, and QAccessibleButton.
Definition at line 1011 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::actionText(), QAccessibleMenu::actionText(), and QAccessibleMenuBar::actionText().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::actionText(action, t, child); }
addControllingSignal()
void QAccessibleWidgetEx::addControllingSignal (const QString & signal) protected
Definition at line 1023 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::QAccessibleButton(), QAccessibleDial::QAccessibleDial(), QAccessibleDoubleSpinBox::QAccessibleDoubleSpinBox(), QAccessibleHeader::QAccessibleHeader(), QAccessibleLineEdit::QAccessibleLineEdit(), QAccessibleScrollBar::QAccessibleScrollBar(), QAccessibleSlider::QAccessibleSlider(), and QAccessibleSpinBox::QAccessibleSpinBox().
 { reinterpret_cast<QAccessibleWidget *>(this)->QAccessibleWidget::addControllingSignal(signal); }
childAt()
int QAccessibleWidgetEx::childAt (int x, int y) const virtual
Returns the 1-based index of the child that contains the screen coordinates (x, y).
This function returns 0 if the point is positioned on the object itself. If the tested point is outside the boundaries of the object this function returns -1.
This function is only relyable for visible objects (invisible object might not be laid out correctly).
All visual objects provide this information.
See also
rect()
Implements QAccessibleInterface.
Reimplemented in QAccessibleMainWindow, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleComboBox, QAccessibleMdiSubWindow, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleTextEdit, QAccessibleAbstractScrollArea, QAccessibleMenuBar, and QAccessibleMenu.
Definition at line 996 of file qaccessiblewidget.cpp.
Referenced by QAccessibleTextEdit::childAt(), and QAccessibleMdiSubWindow::childAt().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::childAt(x, y); }
childCount()
int QAccessibleWidgetEx::childCount () const virtual
Returns the number of children that belong to this object.
A child can provide accessibility information on its own (e.g. a child widget), or be a sub-element of this accessible object.
All objects provide this information.
See also
indexOfChild()
Implements QAccessibleInterface.
Reimplemented in QAccessibleMainWindow, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleComboBox, QAccessibleWorkspace, QAccessibleMdiSubWindow, QAccessibleTabBar, QAccessibleMdiArea, QAccessibleDial, QAccessibleToolBox, QAccessibleSlider, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleScrollBar, QAccessibleTextEdit, QAccessiblePlainTextEdit, QAccessibleDoubleSpinBox, QAccessibleHeader, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleAbstractSpinBox, and QAccessibleMenu.
Definition at line 989 of file qaccessiblewidget.cpp.
Referenced by QAccessibleTextEdit::QAccessibleTextEdit().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::childCount(); }
doAction()
bool QAccessibleWidgetEx::doAction (int action, int child, const QVariantList & params) virtual
Asks the object, or the object's child if child is not 0, to execute action using the parameters, params.
Returns true if the action could be executed; otherwise returns false.
action can be a predefined or a custom action.
See also
userActionCount(), actionText()
Reimplemented from QAccessibleObjectEx.
Reimplemented in QAccessibleComboBox, QAccessibleTabBar, QAccessibleToolButton, QAccessibleSpinBox, QAccessibleMenuBar, QAccessibleAbstractSpinBox, QAccessibleMenu, and QAccessibleButton.
Definition at line 1013 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::doAction(), and QAccessibleAbstractSpinBox::doAction().
 { return reinterpret_cast<QAccessibleWidget *>(this)->QAccessibleWidget::doAction(action, child, params); }
indexOfChild()
int QAccessibleWidgetEx::indexOfChild (const QAccessibleInterface * child) const virtual
Returns the 1-based index of the object child in this object's children list, or -1 if child is not a child of this object.
0 is not a possible return value.
All objects provide this information about their children.
See also
childCount()
Implements QAccessibleInterface.
Reimplemented in QAccessibleMainWindow, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleComboBox, QAccessibleWorkspace, QAccessibleMdiSubWindow, QAccessibleMdiArea, QAccessibleToolBox, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleMenuBar, QAccessibleAbstractScrollArea, and QAccessibleMenu.
Definition at line 991 of file qaccessiblewidget.cpp.
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::indexOfChild(child); }
invokeMethodEx()
QVariant QAccessibleWidgetEx::invokeMethodEx (Method method, int child, const QVariantList & params) virtual
Implements QAccessibleInterfaceEx.
Reimplemented in QAccessibleMainWindow, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleDialogButtonBox, QAccessibleWorkspace, QAccessibleMdiSubWindow, QAccessibleDial, QAccessibleMdiArea, QAccessibleToolBox, QAccessibleStackedWidget, QAccessibleLineEdit, QAccessibleTextEdit, QAccessibleAbstractSlider, QAccessibleDoubleSpinBox, QAccessibleAbstractSpinBox, and QAccessibleAbstractScrollArea.
Definition at line 1034 of file qaccessiblewidget.cpp.
Referenced by QAccessibleAbstractSpinBox::invokeMethodEx(), QAccessibleAbstractSlider::invokeMethodEx(), QAccessibleTextEdit::invokeMethodEx(), and QAccessibleLineEdit::invokeMethodEx().
 {
     if (child)
         return QVariant();
     switch (method) {
     case ListSupportedMethods: {
         QSet<QAccessible::Method> set;
         set << ListSupportedMethods << ForegroundColor << BackgroundColor;
         return QVariant::fromValue(set);
     }
     case ForegroundColor:
         return widget()->palette().color(widget()->foregroundRole());
     case BackgroundColor:
         return widget()->palette().color(widget()->backgroundRole());
     default:
         return QVariant();
     }
 }
navigate()
int QAccessibleWidgetEx::navigate (RelationFlag relation, int index, QAccessibleInterface ** iface) const virtual
Navigates from this object to an object that has a relationship relation to this object, and returns the respective object in target.
It is the caller's responsibility to delete *target after use.
If an object is found, target is set to point to the object, and the index of the child of target is returned. The return value is 0 if target itself is the requested object. target is set to null if this object is the target object (i.e. the requested object is a handled by this object).
If no object is found target is set to null, and the return value is -1.
The entry parameter has two different meanings:
Hierarchical and Logical relationships – if multiple objects with the requested relationship exist entry specifies which one to return. entry is 1-based, e.g. use 1 to get the first (and possibly only) object with the requested relationship.
The following code demonstrates how to use this function to navigate to the first child of an object:
QAccessibleInterface *child = 0;
int targetChild = object->navigate(Accessible::Child, 1, &child);
if (child) {
    // ...
    delete child;
}
Geometric relationships – the index of the child from which to start navigating in the specified direction. entry can be 0 to navigate to a sibling of this object, or non-null to navigate within contained children that don't provide their own accessible information.
Note that the Descendent value for relation is not supported.
All objects support navigation.
See also
relationTo(), childCount()
Implements QAccessibleInterface.
Reimplemented in QAccessibleMainWindow, QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleComboBox, QAccessibleWorkspace, QAccessibleTabBar, QAccessibleMdiSubWindow, QAccessibleMdiArea, QAccessibleToolBox, QAccessibleStackedWidget, QAccessibleItemView, QAccessibleGroupBox, QAccessibleDisplay, QAccessibleDoubleSpinBox, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleAbstractSpinBox, and QAccessibleMenu.
Definition at line 1000 of file qaccessiblewidget.cpp.
Referenced by QAccessibleMenu::navigate(), QAccessibleAbstractSpinBox::navigate(), QAccessibleAbstractScrollArea::navigate(), QAccessibleMenuBar::navigate(), QAccessibleDoubleSpinBox::navigate(), QAccessibleDisplay::navigate(), QAccessibleGroupBox::navigate(), QAccessibleStackedWidget::navigate(), QAccessibleToolBox::navigate(), QAccessibleMdiArea::navigate(), QAccessibleMdiSubWindow::navigate(), QAccessibleTabBar::navigate(), QAccessibleWorkspace::navigate(), QAccessibleComboBox::navigate(), QAccessibleCalendarWidget::navigate(), QAccessibleDockWidget::navigate(), and QAccessibleMainWindow::navigate().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::navigate(rel, entry, target); }
parentObject()
QObject * QAccessibleWidgetEx::parentObject () const protected
Definition at line 1020 of file qaccessiblewidget.cpp.
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::parentObject(); }
rect()
QRect QAccessibleWidgetEx::rect (int child) const virtual
Returns the geometry of the object, or of the object's child if child is not 0.
The geometry is in screen coordinates.
This function is only reliable for visible objects (invisible objects might not be laid out correctly).
All visual objects provide this information.
See also
childAt()
Reimplemented from QAccessibleObjectEx.
Reimplemented in QAccessibleDockWidget, QAccessibleCalendarWidget, QAccessibleComboBox, QAccessibleMdiSubWindow, QAccessibleTabBar, QAccessibleDial, QAccessibleSlider, QAccessibleItemView, QAccessibleScrollBar, QAccessibleTextEdit, QAccessibleDoubleSpinBox, QAccessibleHeader, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleAbstractSpinBox, and QAccessibleMenu.
Definition at line 998 of file qaccessiblewidget.cpp.
Referenced by QAccessibleMenu::rect(), QAccessibleAbstractScrollArea::rect(), QAccessibleMenuBar::rect(), QAccessibleToolButton::rect(), QAccessibleHeader::rect(), QAccessibleTextEdit::rect(), QAccessibleScrollBar::rect(), QAccessibleSlider::rect(), QAccessibleDial::rect(), QAccessibleTabBar::rect(), QAccessibleMdiSubWindow::rect(), QAccessibleComboBox::rect(), and QAccessibleCalendarWidget::rect().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::rect(child); }
relationTo()
QAccessible::Relation QAccessibleWidgetEx::relationTo (int child, const QAccessibleInterface * other, int otherChild) const virtual
Returns the relationship between this object's \a child and the \a
other object's \a otherChild.
If child is 0 the object's own relation is returned.
The returned value indicates the relation of the called object to the other object, e.g. if this object is a child of other the return value will be Child.
The return value is a combination of the bit flags in the QAccessible::Relation enumeration.
All objects provide this information.
See also
indexOfChild(), navigate()
Implements QAccessibleInterface.
Reimplemented in QAccessibleGroupBox, and QAccessibleDisplay.
Definition at line 993 of file qaccessiblewidget.cpp.
Referenced by QAccessibleDisplay::relationTo(), and QAccessibleGroupBox::relationTo().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::relationTo(child, other, otherChild); }
role()
QAccessible::Role QAccessibleWidgetEx::role (int child) const virtual
Returns the role of the object, or of the object's child if child is not 0.
The role of an object is usually static.
All accessible objects have a role.
See also
text(), state()
Implements QAccessibleInterface.
Reimplemented in QAccessibleDockWidget, QAccessibleTextBrowser, QAccessibleComboBox, QAccessibleTabBar, QAccessibleDial, QAccessibleSlider, QAccessibleScrollBar, QAccessibleItemView, QAccessibleTextEdit, QAccessibleGroupBox, QAccessibleDoubleSpinBox, QAccessibleDisplay, QAccessibleHeader, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractSpinBox, and QAccessibleMenu.
Definition at line 1005 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::actionText(), QAccessibleWidgetEx(), QAccessibleAbstractSpinBox::role(), QAccessibleToolButton::role(), QAccessibleDisplay::role(), QAccessibleDoubleSpinBox::role(), QAccessibleGroupBox::role(), QAccessibleTextEdit::role(), QAccessibleItemView::role(), and QAccessibleDial::role().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::role(child); }
setAccelerator()
void QAccessibleWidgetEx::setAccelerator (const QString & accel) protected
Definition at line 1031 of file qaccessiblewidget.cpp.
 { reinterpret_cast<QAccessibleWidget *>(this)->QAccessibleWidget::setAccelerator(accel); }
setDescription()
void QAccessibleWidgetEx::setDescription (const QString & desc) protected
Definition at line 1027 of file qaccessiblewidget.cpp.
 { reinterpret_cast<QAccessibleWidget *>(this)->QAccessibleWidget::setDescription(desc); }
setHelp()
void QAccessibleWidgetEx::setHelp (const QString & help) protected
Definition at line 1029 of file qaccessiblewidget.cpp.
 { reinterpret_cast<QAccessibleWidget *>(this)->QAccessibleWidget::setHelp(help); }
setValue()
void QAccessibleWidgetEx::setValue (const QString & value) protected
Definition at line 1025 of file qaccessiblewidget.cpp.
 { reinterpret_cast<QAccessibleWidget *>(this)->QAccessibleWidget::setValue(value); }
state()
QAccessible::State QAccessibleWidgetEx::state (int child) const virtual
Returns the current state of the object, or of the object's child if child is not 0.
The returned value is a combination of the flags in the QAccessible::StateFlag enumeration.
All accessible objects have a state.
See also
text(), role()
Implements QAccessibleInterface.
Reimplemented in QAccessibleDockWidget, QAccessibleComboBox, QAccessibleWorkspace, QAccessibleTabBar, QAccessibleMdiSubWindow, QAccessibleDial, QAccessibleMdiArea, QAccessibleToolBox, QAccessibleSlider, QAccessibleScrollBar, QAccessibleItemView, QAccessibleLineEdit, QAccessibleGroupBox, QAccessibleDoubleSpinBox, QAccessibleHeader, QAccessibleSpinBox, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractScrollArea, QAccessibleMenu, and QAccessibleButton.
Definition at line 1007 of file qaccessiblewidget.cpp.
Referenced by QAccessibleButton::state(), QAccessibleMenu::state(), QAccessibleAbstractScrollArea::state(), QAccessibleMenuBar::state(), QAccessibleSpinBox::state(), QAccessibleHeader::state(), QAccessibleDoubleSpinBox::state(), QAccessibleGroupBox::state(), QAccessibleLineEdit::state(), QAccessibleScrollBar::state(), QAccessibleSlider::state(), QAccessibleToolBox::state(), QAccessibleMdiArea::state(), QAccessibleDial::state(), QAccessibleMdiSubWindow::state(), QAccessibleTabBar::state(), QAccessibleWorkspace::state(), QAccessibleComboBox::state(), and QAccessibleDockWidget::state().
 { return (reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::state(child))
     | HasInvokeExtension; }
text()
QString QAccessibleWidgetEx::text (Text t, int child) const virtual
Returns the value of the text property t of the object, or of the object's child if child is not 0.
The Name is a string used by clients to identify, find, or announce an accessible object for the user. All objects must have a name that is unique within their container. The name can be used differently by clients, so the name should both give a short description of the object and be unique.
An accessible object's Description provides textual information about an object's visual appearance. The description is primarily used to provide greater context for vision-impaired users, but is also used for context searching or other applications. Not all objects have a description. An "OK" button would not need a description, but a tool button that shows a picture of a smiley would.
The Value of an accessible object represents visual information contained by the object, e.g. the text in a line edit. Usually, the value can be modified by the user. Not all objects have a value, e.g. static text labels don't, and some objects have a state that already is the value, e.g. toggle buttons.
The Help text provides information about the function and usage of an accessible object. Not all objects provide this information.
The Accelerator is a keyboard shortcut that activates the object's default action. A keyboard shortcut is the underlined character in the text of a menu, menu item or widget, and is either the character itself, or a combination of this character and a modifier key like Alt, Ctrl or Shift. Command controls like tool buttons also have shortcut keys and usually display them in their tooltip.
All objects provide a string for Name .
See also
role(), state()
Implements QAccessibleInterface.
Reimplemented in QAccessibleComboBox, QAccessibleTabBar, QAccessibleMdiSubWindow, QAccessibleDial, QAccessibleToolBox, QAccessibleSlider, QAccessibleItemView, QAccessibleScrollBar, QAccessibleLineEdit, QAccessibleTextEdit, QAccessibleGroupBox, QAccessibleDoubleSpinBox, QAccessibleDisplay, QAccessibleHeader, QAccessibleToolButton, QAccessibleMenuBar, QAccessibleAbstractSpinBox, QAccessibleAbstractScrollArea, QAccessibleMenu, and QAccessibleButton.
Definition at line 1003 of file qaccessiblewidget.cpp.
Referenced by QAccessibleMenu::text(), QAccessibleButton::text(), QAccessibleAbstractScrollArea::text(), QAccessibleAbstractSpinBox::text(), QAccessibleMenuBar::text(), QAccessibleHeader::text(), QAccessibleDisplay::text(), QAccessibleDoubleSpinBox::text(), QAccessibleGroupBox::text(), QAccessibleTextEdit::text(), QAccessibleLineEdit::text(), QAccessibleScrollBar::text(), QAccessibleSlider::text(), QAccessibleToolBox::text(), QAccessibleDial::text(), QAccessibleMdiSubWindow::text(), QAccessibleTabBar::text(), and QAccessibleComboBox::text().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::text(t, child); }
widget()
QWidget * QAccessibleWidgetEx::widget () const protected
Definition at line 1018 of file qaccessiblewidget.cpp.
Referenced by QAccessibleToolButton::actionCount(), QAccessibleComboBox::childAt(), QAccessibleMainWindow::childAt(), QAccessibleMdiSubWindow::childCount(), QAccessibleButton::doAction(), QAccessibleAbstractSpinBox::doAction(), QAccessibleSpinBox::doAction(), QAccessibleToolButton::doAction(), QAccessibleGroupBox::groupBox(), QAccessibleDisplay::imageDescription(), QAccessibleDisplay::imagePosition(), QAccessibleDisplay::imageSize(), QAccessibleStackedWidget::indexOfChild(), invokeMethodEx(), QAccessibleToolBox::navigate(), QAccessibleDockWidget::navigate(), QAccessiblePlainTextEdit::plainTextEdit(), QAccessibleTextEdit::QAccessibleTextEdit(), QAccessibleWidgetEx(), QAccessibleAbstractSpinBox::rect(), QAccessibleToolButton::rect(), QAccessibleTabBar::rect(), QAccessibleMdiSubWindow::rect(), QAccessibleDockWidget::rect(), removeInvisibleWidgetsFromList(), QAccessibleButton::text(), QAccessibleHeader::text(), QAccessibleDisplay::text(), QAccessibleDial::text(), and QAccessibleTextEdit::textEdit().
 { return reinterpret_cast<const QAccessibleWidget *>(this)->QAccessibleWidget::widget(); }
Properties
d
QAccessibleWidgetPrivate* QAccessibleWidgetEx::d private
Definition at line 131 of file qaccessiblewidget.h.
Referenced by QAccessibleWidgetEx(), and ~QAccessibleWidgetEx().
The documentation for this class was generated from the following files:
/src/gui/accessible/qaccessiblewidget.h
/src/gui/accessible/qaccessiblewidget.cpp