Qt 4.8: QScriptDebuggerConsoleCommandManager Class Reference
QScriptDebuggerConsoleCommandManager Class Reference
#include <qscriptdebuggerconsolecommandmanager_p.h>
Public Functions
void addCommand (QScriptDebuggerConsoleCommand *command)
Adds the given command.
void addCommandGroup (const QString &name, const QScriptDebuggerConsoleCommandGroupData &data)
Registers a command group with the given name and data.
QScriptDebuggerConsoleCommandGroupData commandGroupData (const QString &name) const
Returns data associated with the group of the given name.
QScriptDebuggerConsoleCommandGroupMap commandGroups () const
Returns all command groups.
QMap< QString, QList< QScriptDebuggerConsoleCommand * > > commands () const
Returns the commands organized into groups.
QList< QScriptDebuggerConsoleCommand * > commandsInGroup (const QString &name) const
Returns commands in the group of the given name.
QStringList completions (const QString &prefix) const
Returns the possible completions for the given prefix.
QScriptDebuggerConsoleCommand * findCommand (const QString &name) const
Returns the command with the given name if one exists, otherwise returns 0.
QScriptDebuggerConsoleCommandManager ()
~QScriptDebuggerConsoleCommandManager ()
Properties
QScopedPointer< QScriptDebuggerConsoleCommandManagerPrivate > d_ptr
Detailed Description
Since
4.5
Warning
This function is not part of the public interface.
Note
The QScriptDebuggerConsoleCommandManager manages a collection of console commands.
Definition at line 69 of file qscriptdebuggerconsolecommandmanager_p.h.
Constructors and Destructors
QScriptDebuggerConsoleCommandManager()
QScriptDebuggerConsoleCommandManager::QScriptDebuggerConsoleCommandManager ()
Definition at line 100 of file qscriptdebuggerconsolecommandmanager.cpp.
     : d_ptr(new QScriptDebuggerConsoleCommandManagerPrivate)
 {
     d_ptr->q_ptr = this;
 }
~QScriptDebuggerConsoleCommandManager()
QScriptDebuggerConsoleCommandManager::~QScriptDebuggerConsoleCommandManager ()
Definition at line 106 of file qscriptdebuggerconsolecommandmanager.cpp.
 {
 }
Functions
addCommand()
void QScriptDebuggerConsoleCommandManager::addCommand (QScriptDebuggerConsoleCommand * command)
Adds the given command.
The manager takes ownership of the command.
Definition at line 114 of file qscriptdebuggerconsolecommandmanager.cpp.
Referenced by QScriptDebuggerConsolePrivate::loadScriptedCommands().
 {
     Q_D(QScriptDebuggerConsoleCommandManager);
     Q_ASSERT(command != 0);
     if (command->name().isEmpty()) {
         qWarning("addCommand(): nameless command ignored");
         return;
     }
     if (command->group().isEmpty()) {
         qWarning("addCommand(): groupless command '%s' ignored",
                  qPrintable(command->name()));
         return;
     }
     if (findCommand(command->name()) != 0) {
         qWarning("addCommand(): duplicate command '%s' (group '%s') ignored",
                  qPrintable(command->name()), qPrintable(command->group()));
         return;
     }
     if (!d->groups.contains(command->group())) {
         qWarning("addCommand(): group '%s' for command '%s' is unknown!",
                  qPrintable(command->group()), qPrintable(command->name()));
     }
     d->commands.append(command);
 }
addCommandGroup()
void QScriptDebuggerConsoleCommandManager::addCommandGroup (const QString & name, const QScriptDebuggerConsoleCommandGroupData & data)
Registers a command group with the given name and data.
Definition at line 142 of file qscriptdebuggerconsolecommandmanager.cpp.
 {
     Q_D(QScriptDebuggerConsoleCommandManager);
     if (name.isEmpty()) {
         qWarning("addCommandGroup(): nameless group ignored");
         return;
     }
     if (d->groups.contains(name)) {
         qWarning("addCommandGroup(): group '%s' already defined",
                  qPrintable(name));
         return;
     }
     d->groups[name] = data;
 }
commandGroupData()
QScriptDebuggerConsoleCommandGroupData QScriptDebuggerConsoleCommandManager::commandGroupData (const QString & name) const
Returns data associated with the group of the given name.
Definition at line 207 of file qscriptdebuggerconsolecommandmanager.cpp.
 {
     Q_D(const QScriptDebuggerConsoleCommandManager);
     return d->groups.value(name);
 }
commandGroups()
QMap< QString, QScriptDebuggerConsoleCommandGroupData > QScriptDebuggerConsoleCommandManager::commandGroups () const
Returns all command groups.
Definition at line 216 of file qscriptdebuggerconsolecommandmanager.cpp.
 {
     Q_D(const QScriptDebuggerConsoleCommandManager);
     return d->groups;
 }
commands()
QMap< QString, QList< QScriptDebuggerConsoleCommand * > > QScriptDebuggerConsoleCommandManager::commands () const
Returns the commands organized into groups.
Definition at line 178 of file qscriptdebuggerconsolecommandmanager.cpp.
 {
     Q_D(const QScriptDebuggerConsoleCommandManager);
     QMap<QString, QList<QScriptDebuggerConsoleCommand*> > result;
     for (int i = 0; i < d->commands.size(); ++i) {
         QScriptDebuggerConsoleCommand *cmd = d->commands.at(i);
         result[cmd->group()].append(cmd);
     }
     return result;
 }
commandsInGroup()
QScriptDebuggerConsoleCommandList QScriptDebuggerConsoleCommandManager::commandsInGroup (const QString & name) const
Returns commands in the group of the given name.
Definition at line 192 of file qscriptdebuggerconsolecommandmanager.cpp.
 {
     Q_D(const QScriptDebuggerConsoleCommandManager);
     QScriptDebuggerConsoleCommandList result;
     for (int i = 0; i < d->commands.size(); ++i) {
         QScriptDebuggerConsoleCommand *cmd = d->commands.at(i);
         if (cmd->group() == name)
             result.append(cmd);
     }
     return result;
 }
completions()
QStringList QScriptDebuggerConsoleCommandManager::completions (const QString & prefix) const
Returns the possible completions for the given prefix.
Definition at line 225 of file qscriptdebuggerconsolecommandmanager.cpp.
Referenced by QScriptDebuggerConsolePrivate::createJob().
 {
     Q_D(const QScriptDebuggerConsoleCommandManager);
     QStringList result;
     for (int i = 0; i < d->commands.size(); ++i) {
         QScriptDebuggerConsoleCommand *cmd = d->commands.at(i);
         QStringList names;
         names.append(cmd->name());
 //        names += cmd->aliases();
         for (int j = 0; j < names.size(); ++j) {
             const QString &name = names.at(j);
             if ((name.length() > prefix.length()) && name.startsWith(prefix))
                 result.append(name);
         }
     }
     qStableSort(result);
     return result;
 }
findCommand()
QScriptDebuggerConsoleCommand * QScriptDebuggerConsoleCommandManager::findCommand (const QString & name) const
Returns the command with the given name if one exists, otherwise returns 0.
Definition at line 162 of file qscriptdebuggerconsolecommandmanager.cpp.
Referenced by addCommand(), and QScriptDebuggerConsolePrivate::createJob().
 {
     Q_D(const QScriptDebuggerConsoleCommandManager);
     for (int i = 0; i < d->commands.size(); ++i) {
         QScriptDebuggerConsoleCommand *cmd = d->commands.at(i);
         if (cmd->name() == name)
             return cmd;
         else if (cmd->aliases().contains(name))
             return cmd;
     }
     return 0;
 }
Properties
d_ptr
QScopedPointer<QScriptDebuggerConsoleCommandManagerPrivate> QScriptDebuggerConsoleCommandManager::d_ptr private
Definition at line 89 of file qscriptdebuggerconsolecommandmanager_p.h.
Referenced by QScriptDebuggerConsoleCommandManager().
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerconsolecommandmanager_p.h
/src/scripttools/debugging/qscriptdebuggerconsolecommandmanager.cpp