Qt 4.8: QDeclarativeTransitionPrivate Class Reference
QDeclarativeTransitionPrivate Class Reference
Public Functions
void complete ()
QDeclarativeTransitionPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QDeclarativeAbstractAnimation * animation_at (QDeclarativeListProperty< QDeclarativeAbstractAnimation > *list, int pos)
static int animation_count (QDeclarativeListProperty< QDeclarativeAbstractAnimation > *list)
static void append_animation (QDeclarativeListProperty< QDeclarativeAbstractAnimation > *list, QDeclarativeAbstractAnimation *a)
static void clear_animations (QDeclarativeListProperty< QDeclarativeAbstractAnimation > *list)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QList< QDeclarativeAbstractAnimation * > animations
QDeclarativeTransitionManager * endState
QString fromState
ParallelAnimationWrapper group
bool reversed
bool reversible
QString toState
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 113 of file qdeclarativetransition.cpp.
Constructors and Destructors
QDeclarativeTransitionPrivate()
QDeclarativeTransitionPrivate::QDeclarativeTransitionPrivate () inline
Definition at line 117 of file qdeclarativetransition.cpp.
     : fromState(QLatin1String("*")), toState(QLatin1String("*")),
       reversed(false), reversible(false), endState(0)
     {
         group.trans = this;
     }
Functions
animation_at()
QDeclarativeAbstractAnimation * QDeclarativeTransitionPrivate::animation_at (QDeclarativeListProperty< QDeclarativeAbstractAnimation > * list, int pos) static
Definition at line 156 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeTransition::setToState().
 {
     QDeclarativeTransition *q = static_cast<QDeclarativeTransition *>(list->object);
     return q->d_func()->animations.at(pos);
 }
animation_count()
int QDeclarativeTransitionPrivate::animation_count (QDeclarativeListProperty< QDeclarativeAbstractAnimation > * list) static
Definition at line 150 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeTransition::setToState().
 {
     QDeclarativeTransition *q = static_cast<QDeclarativeTransition *>(list->object);
     return q->d_func()->animations.count();
 }
append_animation()
void QDeclarativeTransitionPrivate::append_animation (QDeclarativeListProperty< QDeclarativeAbstractAnimation > * list, QDeclarativeAbstractAnimation * a) static
Definition at line 142 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeTransition::setToState().
 {
     QDeclarativeTransition *q = static_cast<QDeclarativeTransition *>(list->object);
     q->d_func()->animations.append(a);
     q->d_func()->group.addAnimation(a->qtAnimation());
     a->setDisableUserControl();
 }
clear_animations()
void QDeclarativeTransitionPrivate::clear_animations (QDeclarativeListProperty< QDeclarativeAbstractAnimation > * list) static
Definition at line 162 of file qdeclarativetransition.cpp.
Referenced by QDeclarativeTransition::setToState().
 {
     QDeclarativeTransition *q = static_cast<QDeclarativeTransition *>(list->object);
     while (q->d_func()->animations.count()) {
         QDeclarativeAbstractAnimation *firstAnim = q->d_func()->animations.at(0);
         q->d_func()->group.removeAnimation(firstAnim->qtAnimation());
         q->d_func()->animations.removeAll(firstAnim);
     }
 }
complete()
void QDeclarativeTransitionPrivate::complete () inline
Definition at line 131 of file qdeclarativetransition.cpp.
Referenced by ParallelAnimationWrapper::updateState().
     {
         endState->complete();
     }
Properties
animations
QList<QDeclarativeAbstractAnimation *> QDeclarativeTransitionPrivate::animations
Definition at line 139 of file qdeclarativetransition.cpp.
endState
QDeclarativeTransitionManager* QDeclarativeTransitionPrivate::endState
Definition at line 129 of file qdeclarativetransition.cpp.
fromState
QString QDeclarativeTransitionPrivate::fromState
Definition at line 124 of file qdeclarativetransition.cpp.
group
ParallelAnimationWrapper QDeclarativeTransitionPrivate::group
Definition at line 128 of file qdeclarativetransition.cpp.
reversed
bool QDeclarativeTransitionPrivate::reversed
Definition at line 126 of file qdeclarativetransition.cpp.
reversible
bool QDeclarativeTransitionPrivate::reversible
Definition at line 127 of file qdeclarativetransition.cpp.
toState
QString QDeclarativeTransitionPrivate::toState
Definition at line 125 of file qdeclarativetransition.cpp.
The documentation for this class was generated from the following file:
/src/declarative/util/qdeclarativetransition.cpp