Qt 4.8: QWaylandEglIntegration Class Reference
QWaylandEglIntegration Class Reference
#include <qwaylandeglintegration.h>
Public Functions
QWaylandWindow * createEglWindow (QWidget *window)
EGLDisplay eglDisplay () const
void initialize ()
struct wl_egl_display * nativeDisplay () const
QWaylandEglIntegration (struct wl_display *waylandDisplay)
~QWaylandEglIntegration ()
Public Functions inherited from QWaylandGLIntegration
QWaylandGLIntegration ()
virtual ~QWaylandGLIntegration ()
Properties
EGLDisplay mEglDisplay
struct wl_display * mWaylandDisplay
Additional Inherited Members
Static Public Functions inherited from QWaylandGLIntegration
static QWaylandGLIntegration * createGLIntegration (QWaylandDisplay *waylandDisplay)
Detailed Description
Definition at line 52 of file qwaylandeglintegration.h.
Constructors and Destructors
QWaylandEglIntegration()
QWaylandEglIntegration::QWaylandEglIntegration (struct wl_display * waylandDisplay)
Definition at line 50 of file qwaylandeglintegration.cpp.
Referenced by eglDisplay().
     : mWaylandDisplay(waylandDisplay)
 {
     qDebug() << "Using Wayland-EGL";
 }
~QWaylandEglIntegration()
QWaylandEglIntegration::~QWaylandEglIntegration ()
Definition at line 57 of file qwaylandeglintegration.cpp.
 {
     eglTerminate(mEglDisplay);
 }
Functions
createEglWindow()
QWaylandWindow * QWaylandEglIntegration::createEglWindow (QWidget * window) virtual
Implements QWaylandGLIntegration.
Definition at line 76 of file qwaylandeglintegration.cpp.
 {
     return new QWaylandEglWindow(window);
 }
eglDisplay()
EGLDisplay QWaylandEglIntegration::eglDisplay () const
Definition at line 81 of file qwaylandeglintegration.cpp.
Referenced by QWaylandEglWindow::glContext(), and QWaylandEglWindow::newSurfaceCreated().
 {
     return mEglDisplay;
 }
initialize()
void QWaylandEglIntegration::initialize () virtual
Implements QWaylandGLIntegration.
Definition at line 62 of file qwaylandeglintegration.cpp.
 {
     EGLint major,minor;
     mEglDisplay = eglGetDisplay(mWaylandDisplay);
     if (mEglDisplay == NULL) {
         qWarning("EGL not available");
     } else {
         if (!eglInitialize(mEglDisplay, &major, &minor)) {
             qWarning("failed to initialize EGL display");
             return;
         }
     }
 }
nativeDisplay()
struct wl_egl_display* QWaylandEglIntegration::nativeDisplay () const
Properties
mEglDisplay
EGLDisplay QWaylandEglIntegration::mEglDisplay private
Definition at line 67 of file qwaylandeglintegration.h.
Referenced by eglDisplay(), initialize(), and ~QWaylandEglIntegration().
mWaylandDisplay
struct wl_display* QWaylandEglIntegration::mWaylandDisplay private
Definition at line 65 of file qwaylandeglintegration.h.
Referenced by initialize().
The documentation for this class was generated from the following files:
/src/plugins/platforms/wayland/gl_integration/wayland_egl/qwaylandeglintegration.h
/src/plugins/platforms/wayland/gl_integration/wayland_egl/qwaylandeglintegration.cpp