Qt 4.8: QUnifiedTimer Class Reference
QUnifiedTimer Class Reference
#include <qabstractanimation_p.h>
Public Functions
void installAnimationDriver (QAnimationDriver *driver)
void restartAnimationTimer ()
int runningAnimationCount ()
void setConsistentTiming (bool consistent)
void setSlowdownFactor (qreal factor)
void setSlowModeEnabled (bool enabled)
void setTimingInterval (int interval)
void updateAnimationsTime ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static void ensureTimerUpdate ()
static QUnifiedTimer * instance ()
static QUnifiedTimer * instance (bool create)
static void registerAnimation (QAbstractAnimation *animation, bool isTopLevel)
static void unregisterAnimation (QAbstractAnimation *animation)
static void updateAnimationTimer ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Functions
int closestPauseAnimationTimeToFinish ()
QUnifiedTimer ()
void registerRunningAnimation (QAbstractAnimation *animation)
void unregisterRunningAnimation (QAbstractAnimation *animation)
Properties
QList< QAbstractAnimation * > animations
QList< QAbstractAnimation * > animationsToStart
QBasicTimer animationTimer
bool consistentTiming
int currentAnimationIdx
QDefaultAnimationDriver defaultDriver
QAnimationDriver * driver
bool insideTick
bool isPauseTimerActive
qint64 lastTick
int runningLeafAnimations
QList< QAbstractAnimation * > runningPauseAnimations
qreal slowdownFactor
bool slowMode
QBasicTimer startStopAnimationTimer
ElapsedTimer time
int timingInterval
Friends
class QDefaultAnimationDriver
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 144 of file qabstractanimation_p.h.
Constructors and Destructors
QUnifiedTimer()
QUnifiedTimer::QUnifiedTimer () private
Definition at line 183 of file qabstractanimation.cpp.
Referenced by instance().
                              :
     QObject(), defaultDriver(this), lastTick(0), timingInterval(DEFAULT_TIMER_INTERVAL),
     currentAnimationIdx(0), insideTick(false), consistentTiming(false), slowMode(false),
     slowdownFactor(5.0f), isPauseTimerActive(false), runningLeafAnimations(0)
 {
     time.invalidate();
     driver = &defaultDriver;
 }
Functions
closestPauseAnimationTimeToFinish()
int QUnifiedTimer::closestPauseAnimationTimeToFinish () private
Definition at line 390 of file qabstractanimation.cpp.
Referenced by restartAnimationTimer().
 {
     int closestTimeToFinish = INT_MAX;
     for (int i = 0; i < runningPauseAnimations.size(); ++i) {
         QAbstractAnimation *animation = runningPauseAnimations.at(i);
         int timeToFinish;
         if (animation->direction() == QAbstractAnimation::Forward)
             timeToFinish = animation->duration() - animation->currentLoopTime();
         else
             timeToFinish = animation->currentLoopTime();
         if (timeToFinish < closestTimeToFinish)
             closestTimeToFinish = timeToFinish;
     }
     return closestTimeToFinish;
 }
ensureTimerUpdate()
void QUnifiedTimer::ensureTimerUpdate () static
Definition at line 215 of file qabstractanimation.cpp.
Referenced by QAbstractAnimation::setDirection(), and QAbstractAnimationPrivate::setState().
 {
     QUnifiedTimer *inst = QUnifiedTimer::instance(false);
     if (inst && inst->isPauseTimerActive)
         inst->updateAnimationsTime();
 }
installAnimationDriver()
void QUnifiedTimer::installAnimationDriver (QAnimationDriver * driver)
Definition at line 408 of file qabstractanimation.cpp.
Referenced by QAnimationDriver::install().
 {
     if (driver) {
         if (driver->isRunning()) {
             qWarning("QUnifiedTimer: Cannot change animation driver while animations are running");
             return;
         }
         if (driver != &defaultDriver)
             delete driver;
     }
     driver = d;
 }
instance() [1/2]
QUnifiedTimer * QUnifiedTimer::instance () static
Definition at line 210 of file qabstractanimation.cpp.
Referenced by QAnimationDriver::advance(), ensureTimerUpdate(), QAnimationDriver::install(), registerAnimation(), QDeclarativeDebugHelper::setAnimationSlowDownFactor(), unregisterAnimation(), and updateAnimationTimer().
 {
     return instance(true);
 }
instance() [2/2]
QUnifiedTimer * QUnifiedTimer::instance (bool create) static
Definition at line 193 of file qabstractanimation.cpp.
 {
     QUnifiedTimer *inst;
 #ifndef QT_NO_THREAD
     if (create && !unifiedTimer()->hasLocalData()) {
         inst = new QUnifiedTimer;
         unifiedTimer()->setLocalData(inst);
     } else {
         inst = unifiedTimer()->localData();
     }
 #else
     static QUnifiedTimer unifiedTimer;
     inst = &unifiedTimer;
 #endif
     return inst;
 }
registerAnimation()
void QUnifiedTimer::registerAnimation (QAbstractAnimation * animation, bool isTopLevel) static
Definition at line 326 of file qabstractanimation.cpp.
Referenced by QAbstractAnimationPrivate::setState().
 {
     QUnifiedTimer *inst = instance(true); //we create the instance if needed
     inst->registerRunningAnimation(animation);
     if (isTopLevel) {
         Q_ASSERT(!QAbstractAnimationPrivate::get(animation)->hasRegisteredTimer);
         QAbstractAnimationPrivate::get(animation)->hasRegisteredTimer = true;
         inst->animationsToStart << animation;
         if (!inst->startStopAnimationTimer.isActive())
             inst->startStopAnimationTimer.start(STARTSTOP_TIMER_DELAY, inst);
     }
 }
registerRunningAnimation()
void QUnifiedTimer::registerRunningAnimation (QAbstractAnimation * animation) private
Definition at line 367 of file qabstractanimation.cpp.
Referenced by registerAnimation().
 {
     if (QAbstractAnimationPrivate::get(animation)->isGroup)
         return;
     if (QAbstractAnimationPrivate::get(animation)->isPause) {
         runningPauseAnimations << animation;
     } else
         runningLeafAnimations++;
 }
restartAnimationTimer()
void QUnifiedTimer::restartAnimationTimer ()
Definition at line 264 of file qabstractanimation.cpp.
Referenced by QAnimationDriver::advance(), timerEvent(), and updateAnimationTimer().
 {
     if (runningLeafAnimations == 0 && !runningPauseAnimations.isEmpty()) {
         int closestTimeToFinish = closestPauseAnimationTimeToFinish();
         if (closestTimeToFinish < 0) {
             qDebug() << runningPauseAnimations;
             qDebug() << closestPauseAnimationTimeToFinish();
         }
         driver->stop();
         animationTimer.start(closestTimeToFinish, this);
         isPauseTimerActive = true;
     } else if (!driver->isRunning() || isPauseTimerActive) {
         driver->start();
         isPauseTimerActive = false;
     } else if (runningLeafAnimations == 0)
         driver->stop();
 }
runningAnimationCount()
int QUnifiedTimer::runningAnimationCount () inline
Definition at line 188 of file qabstractanimation_p.h.
 { return animations.count(); }
setConsistentTiming()
void QUnifiedTimer::setConsistentTiming (bool consistent) inline
Definition at line 164 of file qabstractanimation_p.h.
 { consistentTiming = consistent; }
setSlowdownFactor()
void QUnifiedTimer::setSlowdownFactor (qreal factor) inline
Definition at line 168 of file qabstractanimation_p.h.
Referenced by QDeclarativeDebugHelper::setAnimationSlowDownFactor().
 { slowdownFactor = factor; }
setSlowModeEnabled()
void QUnifiedTimer::setSlowModeEnabled (bool enabled) inline
Definition at line 167 of file qabstractanimation_p.h.
Referenced by QDeclarativeDebugHelper::setAnimationSlowDownFactor().
 { slowMode = enabled; }
setTimingInterval()
void QUnifiedTimer::setTimingInterval (int interval)
Definition at line 282 of file qabstractanimation.cpp.
 {
     timingInterval = interval;
     if (driver->isRunning() && !isPauseTimerActive) {
         //we changed the timing interval
         driver->stop();
         driver->start();
     }
 }
timerEvent()
void QUnifiedTimer::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 294 of file qabstractanimation.cpp.
 {
     //in the case of consistent timing we make sure the orders in which events come is always the same
    //for that purpose we do as if the startstoptimer would always fire before the animation timer
     if ((consistentTiming && startStopAnimationTimer.isActive()) ||
         event->timerId() == startStopAnimationTimer.timerId()) {
         startStopAnimationTimer.stop();
         //we transfer the waiting animations into the "really running" state
         animations += animationsToStart;
         animationsToStart.clear();
         if (animations.isEmpty()) {
             animationTimer.stop();
             isPauseTimerActive = false;
             // invalidate the start reference time
             time.invalidate();
         } else {
             restartAnimationTimer();
             if (!time.isValid()) {
                 lastTick = 0;
                 time.start();
             }
         }
     }
     if (event->timerId() == animationTimer.timerId()) {
         // update current time on all top level animations
         updateAnimationsTime();
         restartAnimationTimer();
     }
 }
unregisterAnimation()
void QUnifiedTimer::unregisterAnimation (QAbstractAnimation * animation) static
Definition at line 339 of file qabstractanimation.cpp.
Referenced by QAbstractAnimationPrivate::setState(), and QAbstractAnimation::~QAbstractAnimation().
 {
     QUnifiedTimer *inst = QUnifiedTimer::instance(false);
     if (inst) {
         //at this point the unified timer should have been created
         //but it might also have been already destroyed in case the application is shutting down
         inst->unregisterRunningAnimation(animation);
         if (!QAbstractAnimationPrivate::get(animation)->hasRegisteredTimer)
             return;
         int idx = inst->animations.indexOf(animation);
         if (idx != -1) {
             inst->animations.removeAt(idx);
             // this is needed if we unregister an animation while its running
             if (idx <= inst->currentAnimationIdx)
                 --inst->currentAnimationIdx;
             if (inst->animations.isEmpty() && !inst->startStopAnimationTimer.isActive())
                 inst->startStopAnimationTimer.start(STARTSTOP_TIMER_DELAY, inst);
         } else {
             inst->animationsToStart.removeOne(animation);
         }
     }
     QAbstractAnimationPrivate::get(animation)->hasRegisteredTimer = false;
 }
unregisterRunningAnimation()
void QUnifiedTimer::unregisterRunningAnimation (QAbstractAnimation * animation) private
Definition at line 378 of file qabstractanimation.cpp.
Referenced by unregisterAnimation().
 {
     if (QAbstractAnimationPrivate::get(animation)->isGroup)
         return;
     if (QAbstractAnimationPrivate::get(animation)->isPause)
         runningPauseAnimations.removeOne(animation);
     else
         runningLeafAnimations--;
     Q_ASSERT(runningLeafAnimations >= 0);
 }
updateAnimationsTime()
void QUnifiedTimer::updateAnimationsTime ()
Definition at line 222 of file qabstractanimation.cpp.
Referenced by QAnimationDriver::advance(), ensureTimerUpdate(), and timerEvent().
 {
     //setCurrentTime can get this called again while we're the for loop. At least with pauseAnimations
     if(insideTick)
         return;
     qint64 totalElapsed = time.elapsed();
     // ignore consistentTiming in case the pause timer is active
     int delta = (consistentTiming && !isPauseTimerActive) ?
                         timingInterval : totalElapsed - lastTick;
     if (slowMode) {
         if (slowdownFactor > 0)
             delta = qRound(delta / slowdownFactor);
         else
             delta = 0;
     }
     lastTick = totalElapsed;
     //we make sure we only call update time if the time has actually changed
     //it might happen in some cases that the time doesn't change because events are delayed
     //when the CPU load is high
     if (delta) {
         insideTick = true;
         for (currentAnimationIdx = 0; currentAnimationIdx < animations.count(); ++currentAnimationIdx) {
             QAbstractAnimation *animation = animations.at(currentAnimationIdx);
             int elapsed = QAbstractAnimationPrivate::get(animation)->totalCurrentTime
                           + (animation->direction() == QAbstractAnimation::Forward ? delta : -delta);
             animation->setCurrentTime(elapsed);
         }
         insideTick = false;
         currentAnimationIdx = 0;
     }
 }
updateAnimationTimer()
void QUnifiedTimer::updateAnimationTimer () static
Definition at line 257 of file qabstractanimation.cpp.
Referenced by QAbstractAnimation::setDirection().
 {
     QUnifiedTimer *inst = QUnifiedTimer::instance(false);
     if (inst)
         inst->restartAnimationTimer();
 }
Friends and Related Functions
QDefaultAnimationDriver
friend class QDefaultAnimationDriver friend
Definition at line 194 of file qabstractanimation_p.h.
Properties
animations
QList<QAbstractAnimation*> QUnifiedTimer::animations private
Definition at line 220 of file qabstractanimation_p.h.
Referenced by timerEvent(), unregisterAnimation(), and updateAnimationsTime().
animationsToStart
QList<QAbstractAnimation*> QUnifiedTimer::animationsToStart private
Definition at line 220 of file qabstractanimation_p.h.
Referenced by registerAnimation(), timerEvent(), and unregisterAnimation().
animationTimer
QBasicTimer QUnifiedTimer::animationTimer private
Definition at line 199 of file qabstractanimation_p.h.
Referenced by restartAnimationTimer(), and timerEvent().
consistentTiming
bool QUnifiedTimer::consistentTiming private
Definition at line 209 of file qabstractanimation_p.h.
Referenced by timerEvent(), and updateAnimationsTime().
currentAnimationIdx
int QUnifiedTimer::currentAnimationIdx private
Definition at line 207 of file qabstractanimation_p.h.
Referenced by unregisterAnimation(), and updateAnimationsTime().
defaultDriver
QDefaultAnimationDriver QUnifiedTimer::defaultDriver private
Definition at line 197 of file qabstractanimation_p.h.
Referenced by installAnimationDriver(), and QUnifiedTimer().
driver
QAnimationDriver* QUnifiedTimer::driver private
Definition at line 196 of file qabstractanimation_p.h.
Referenced by installAnimationDriver(), QUnifiedTimer(), restartAnimationTimer(), and setTimingInterval().
insideTick
bool QUnifiedTimer::insideTick private
Definition at line 208 of file qabstractanimation_p.h.
Referenced by updateAnimationsTime().
isPauseTimerActive
bool QUnifiedTimer::isPauseTimerActive private
Definition at line 218 of file qabstractanimation_p.h.
Referenced by ensureTimerUpdate(), restartAnimationTimer(), setTimingInterval(), timerEvent(), and updateAnimationsTime().
lastTick
qint64 QUnifiedTimer::lastTick private
Definition at line 205 of file qabstractanimation_p.h.
Referenced by timerEvent(), and updateAnimationsTime().
runningLeafAnimations
int QUnifiedTimer::runningLeafAnimations private
Definition at line 223 of file qabstractanimation_p.h.
Referenced by registerRunningAnimation(), restartAnimationTimer(), and unregisterRunningAnimation().
runningPauseAnimations
QList<QAbstractAnimation*> QUnifiedTimer::runningPauseAnimations private
Definition at line 224 of file qabstractanimation_p.h.
Referenced by closestPauseAnimationTimeToFinish(), registerRunningAnimation(), restartAnimationTimer(), and unregisterRunningAnimation().
slowdownFactor
qreal QUnifiedTimer::slowdownFactor private
Definition at line 215 of file qabstractanimation_p.h.
Referenced by updateAnimationsTime().
slowMode
bool QUnifiedTimer::slowMode private
Definition at line 210 of file qabstractanimation_p.h.
Referenced by updateAnimationsTime().
startStopAnimationTimer
QBasicTimer QUnifiedTimer::startStopAnimationTimer private
Definition at line 201 of file qabstractanimation_p.h.
Referenced by registerAnimation(), timerEvent(), and unregisterAnimation().
time
ElapsedTimer QUnifiedTimer::time private
Definition at line 203 of file qabstractanimation_p.h.
Referenced by QUnifiedTimer(), timerEvent(), and updateAnimationsTime().
timingInterval
int QUnifiedTimer::timingInterval private
Definition at line 206 of file qabstractanimation_p.h.
Referenced by setTimingInterval(), QDefaultAnimationDriver::started(), and updateAnimationsTime().
The documentation for this class was generated from the following files:
/src/corelib/animation/qabstractanimation_p.h
/src/corelib/animation/qabstractanimation.cpp