Qt 4.8: QTextDocument Class Reference
QTextDocument Class Reference
The QTextDocument class holds formatted text that can be viewed and edited using a QTextEdit.
#include <qtextdocument.h>
Public Types
enum FindFlag { FindBackward = 0x00001, FindCaseSensitively = 0x00002, FindWholeWords = 0x00004 }
This enum describes the options available to QTextDocument's find function.
enum MetaInformation { DocumentTitle, DocumentUrl }
This enum describes the different types of meta information that can be added to a document.
enum ResourceType { HtmlResource = 1, ImageResource = 2, StyleSheetResource = 3, UserResource = 100 }
This enum describes the types of resources that can be loaded by QTextDocument's loadResource() function.
enum Stacks { UndoStack = 0x01, RedoStack = 0x02, UndoAndRedoStacks = UndoStack | RedoStack }
Public Slots
void appendUndoItem (QAbstractUndoItem *)
Appends a custom undo item to the undo stack.
void redo ()
Redoes the last editing operation on the document if redo is available.
void setModified (bool m=true)
void undo ()
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void blockCountChanged (int newBlockCount)
This signal is emitted when the total number of text blocks in the document changes.
void contentsChange (int from, int charsRemoves, int charsAdded)
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
void contentsChanged ()
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
void cursorPositionChanged (const QTextCursor &cursor)
This signal is emitted whenever the position of a cursor changed due to an editing operation.
void documentLayoutChanged ()
This signal is emitted when a new document layout is set.
void modificationChanged (bool m)
This signal is emitted whenever the content of the document changes in a way that affects the modification state.
void redoAvailable (bool)
This signal is emitted whenever redo operations become available (available is true) or unavailable (available is false).
void undoAvailable (bool)
This signal is emitted whenever undo operations become available (available is true) or unavailable (available is false).
void undoCommandAdded ()
This signal is emitted every time a new level of undo is added to the QTextDocument.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addResource (int type, const QUrl &name, const QVariant &resource)
Adds the resource resource to the resource cache, using type and name as identifiers.
void adjustSize ()
Adjusts the document to a reasonable size.
QVector< QTextFormat > allFormats () const
Returns a vector of text formats for all the formats used in the document.
int availableRedoSteps () const
Returns the number of available redo steps.
int availableUndoSteps () const
Returns the number of available undo steps.
QTextBlock begin () const
Returns the document's first text block.
int blockCount () const
QChar characterAt (int pos) const
Returns the character at position pos, or a null character if the position is out of range.
int characterCount () const
Returns the number of characters of this document.
virtual void clear ()
Clears the document.
void clearUndoRedoStacks (Stacks historyToClear=UndoAndRedoStacks)
Clears the stacks specified by stacksToClear.
QTextDocument * clone (QObject *parent=0) const
Creates a new QTextDocument that is a copy of this text document.
Qt::CursorMoveStyle defaultCursorMoveStyle () const
The default cursor movement style is used by all QTextCursor objects created from the document.
QFont defaultFont () const
QString defaultStyleSheet () const
QTextOption defaultTextOption () const
the default text option will be set on all QTextLayout in the document.
QTextDocumentPrivate * docHandle () const
So that not all classes have to be friends of each other.
QAbstractTextDocumentLayout * documentLayout () const
Returns the document layout for this document.
qreal documentMargin () const
void drawContents (QPainter *painter, const QRectF &rect=QRectF())
Draws the content of the document with painter p, clipped to rect.
QTextBlock end () const
This function returns a block to test for the end of the document while iterating over it.
QTextCursor find (const QString &subString, int from=0, FindFlags options=0) const
Finds the next occurrence of the string, subString, in the document.
QTextCursor find (const QString &subString, const QTextCursor &from, FindFlags options=0) const
Finds the next occurrence of the string, subString, in the document.
QTextCursor find (const QRegExp &expr, int from=0, FindFlags options=0) const
Finds the next occurrence, matching the regular expression, expr, in the document.
QTextCursor find (const QRegExp &expr, const QTextCursor &from, FindFlags options=0) const
Finds the next occurrence, matching the regular expression, expr, in the document.
QTextBlock findBlock (int pos) const
Returns the text block that contains the {pos}-th character.
QTextBlock findBlockByLineNumber (int blockNumber) const
Returns the text block that contains the specified lineNumber.
QTextBlock findBlockByNumber (int blockNumber) const
Returns the text block with the specified blockNumber.
QTextBlock firstBlock () const
Returns the document's first text block.
QTextFrame * frameAt (int pos) const
Returns the frame that contains the text cursor position pos.
qreal idealWidth () const
Returns the ideal width of the text document.
qreal indentWidth () const
bool isEmpty () const
Returns true if the document is empty; otherwise returns false.
bool isModified () const
bool isRedoAvailable () const
Returns true if redo is available; otherwise returns false.
bool isUndoAvailable () const
Returns true if undo is available; otherwise returns false.
bool isUndoRedoEnabled () const
QTextBlock lastBlock () const
Returns the document's last (valid) text block.
int lineCount () const
Returns the number of lines of this document (if the layout supports this).
void markContentsDirty (int from, int length)
Marks the contents specified by the given position and length as "dirty", informing the document that it needs to be laid out again.
int maximumBlockCount () const
QString metaInformation (MetaInformation info) const
Returns meta information about the document of the type specified by info.
QTextObject * object (int objectIndex) const
Returns the text object associated with the given objectIndex.
QTextObject * objectForFormat (const QTextFormat &) const
Returns the text object associated with the format f.
int pageCount () const
returns the number of pages in this document.
QSizeF pageSize () const
void print (QPrinter *printer) const
Prints the document to the given printer.
QTextDocument (QObject *parent=0)
Constructs an empty QTextDocument with the given parent.
QTextDocument (const QString &text, QObject *parent=0)
Constructs a QTextDocument containing the plain (unformatted) text specified, and with the given parent.
void redo (QTextCursor *cursor)
Redoes the last editing operation on the document if redo is available.
QVariant resource (int type, const QUrl &name) const
Returns data of the specified type from the resource with the given name.
int revision () const
Returns the document's revision (if undo is enabled).
QTextFrame * rootFrame () const
Returns the document's root frame.
void setDefaultCursorMoveStyle (Qt::CursorMoveStyle style)
Sets the default cursor movement style to the given style.
void setDefaultFont (const QFont &font)
Sets the default font to use in the document layout.
void setDefaultStyleSheet (const QString &sheet)
void setDefaultTextOption (const QTextOption &option)
Sets the default text option.
void setDocumentLayout (QAbstractTextDocumentLayout *layout)
Sets the document to use the given layout.
void setDocumentMargin (qreal margin)
void setHtml (const QString &html)
Replaces the entire contents of the document with the given HTML-formatted text in the html string.
void setIndentWidth (qreal width)
Sets the width used for text list and text block indenting.
void setMaximumBlockCount (int maximum)
void setMetaInformation (MetaInformation info, const QString &)
Sets the document's meta information of the type specified by info to the given string.
void setPageSize (const QSizeF &size)
void setPlainText (const QString &text)
Replaces the entire contents of the document with the given plain text.
void setTextWidth (qreal width)
void setUndoRedoEnabled (bool enable)
void setUseDesignMetrics (bool b)
QSizeF size () const
qreal textWidth () const
QString toHtml (const QByteArray &encoding=QByteArray()) const
Returns a string containing an HTML representation of the document.
QString toPlainText () const
Returns the plain text contained in the document.
void undo (QTextCursor *cursor)
Undoes the last editing operation on the document if undo is available.
bool useDesignMetrics () const
~QTextDocument ()
Destroys the document.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual QTextObject * createObject (const QTextFormat &f)
Creates and returns a new document object (a QTextObject), based on the given format.
virtual QVariant loadResource (int type, const QUrl &name)
Loads data of the specified type from the resource with the given name.
QTextDocument (QTextDocumentPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
int blockCount
Returns the number of text blocks in the document.
QFont defaultFont
the default font used to display the document's text
QString defaultStyleSheet
The default style sheet is applied to all newly HTML formatted text that is inserted into the document, for example using setHtml() or QTextCursor::insertHtml().
qreal documentMargin
The margin around the document.
qreal indentWidth
Returns the width used for text list and text block indenting.
int maximumBlockCount
Specifies the limit for blocks in the document.
bool modified
whether the document has been modified by the user
QSizeF pageSize
the page size that should be used for laying out the document
QSizeF size
Returns the actual size of the document.
qreal textWidth
The text width specifies the preferred width for text in the document.
bool undoRedoEnabled
whether undo/redo are enabled for this document
bool useDesignMetrics
whether the document uses design metrics of fonts to improve the accuracy of text layout
Friends
class QTextObjectPrivate
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QTextDocument class holds formatted text that can be viewed and edited using a QTextEdit.
Note
This class or function is reentrant.
QTextDocument is a container for structured rich text documents, providing support for styled text and various types of document elements, such as lists, tables, frames, and images. They can be created for use in a QTextEdit, or used independently.
Each document element is described by an associated format object. Each format object is treated as a unique object by QTextDocuments, and can be passed to objectForFormat() to obtain the document element that it is applied to.
A QTextDocument can be edited programmatically using a QTextCursor, and its contents can be examined by traversing the document structure. The entire document structure is stored as a hierarchy of document elements beneath the root frame, found with the rootFrame() function. Alternatively, if you just want to iterate over the textual contents of the document you can use begin(), end(), and findBlock() to retrieve text blocks that you can examine and iterate over.
The layout of a document is determined by the documentLayout(); you can create your own QAbstractTextDocumentLayout subclass and set it using setDocumentLayout() if you want to use your own layout logic. The document's title and other meta-information can be obtained by calling the metaInformation() function. For documents that are exposed to users through the QTextEdit class, the document title is also available via the QTextEdit::documentTitle() function.
The toPlainText() and toHtml() convenience functions allow you to retrieve the contents of the document as plain text and HTML. The document's text can be searched using the find() functions.
Undo/redo of operations performed on the document can be controlled using the setUndoRedoEnabled() function. The undo/redo system can be controlled by an editor widget through the undo() and redo() slots; the document also provides contentsChanged(), undoAvailable(), and redoAvailable() signals that inform connected editor widgets about the state of the undo/redo system. The following are the undo/redo operations of a QTextDocument:
Insertion or removal of characters. A sequence of insertions or removals within the same text block are regarded as a single undo/redo operation.
Insertion or removal of text blocks. Sequences of insertion or removals in a single operation (e.g., by selecting and then deleting text) are regarded as a single undo/redo operation.
Text character format changes.
Text block format changes.
Text block group format changes.
See also
QTextCursor, QTextEdit, Rich Text Processing, {Text Object Example}
Definition at line 109 of file qtextdocument.h.
Enumerations
FindFlag
enum QTextDocument::FindFlag
This enum describes the options available to QTextDocument's find function.
The options can be OR-ed together from the following list:
FindBackward Search backwards instead of forwards.
FindCaseSensitively By default find works case insensitive. Specifying this option changes the behaviour to a case sensitive find operation.
FindWholeWords Makes find match only complete words.
Enumerator
FindBackward
FindCaseSensitively
FindWholeWords
Definition at line 170 of file qtextdocument.h.
     {
         FindBackward        = 0x00001,
         FindCaseSensitively = 0x00002,
         FindWholeWords      = 0x00004
     };
MetaInformation
enum QTextDocument::MetaInformation
This enum describes the different types of meta information that can be added to a document.
DocumentTitle The title of the document.
DocumentUrl The url of the document. The loadResource() function uses this url as the base when loading relative resources.
See also
metaInformation(), setMetaInformation()
Enumerator
DocumentTitle
DocumentUrl
Definition at line 153 of file qtextdocument.h.
{
         DocumentTitle,
         DocumentUrl
     };
ResourceType
enum QTextDocument::ResourceType
This enum describes the types of resources that can be loaded by QTextDocument's loadResource() function.
HtmlResource The resource contains HTML.
ImageResource The resource contains image data. Currently supported data types are QVariant::Pixmap and QVariant::Image. If the corresponding variant is of type QVariant::ByteArray then Qt attempts to load the image using QImage::loadFromData. QVariant::Icon is currently not supported. The icon needs to be converted to one of the supported types first, for example using QIcon::pixmap.
StyleSheetResource The resource contains CSS.
UserResource The first available value for user defined resource types.
See also
loadResource()
Enumerator
HtmlResource
ImageResource
StyleSheetResource
UserResource
Definition at line 213 of file qtextdocument.h.
                       {
         HtmlResource  = 1,
         ImageResource = 2,
         StyleSheetResource = 3,
         UserResource  = 100
     };
Stacks
enum QTextDocument::Stacks
UndoStack The undo stack.
RedoStack The redo stack.
UndoAndRedoStacks Both the undo and redo stacks.
Enumerator
UndoStack
RedoStack
UndoAndRedoStacks
Definition at line 259 of file qtextdocument.h.
                 {
         UndoStack = 0x01,
         RedoStack = 0x02,
         UndoAndRedoStacks = UndoStack | RedoStack
     };
Constructors and Destructors
QTextDocument() [1/3]
QTextDocument::QTextDocument (QObject * parent = 0) explicit
Constructs an empty QTextDocument with the given parent.
Definition at line 343 of file qtextdocument.cpp.
Referenced by clone().
     : QObject(*new QTextDocumentPrivate, parent)
 {
     Q_D(QTextDocument);
     d->init();
 }
QTextDocument() [2/3]
QTextDocument::QTextDocument (const QString & text, QObject * parent = 0) explicit
Constructs a QTextDocument containing the plain (unformatted) text specified, and with the given parent.
Definition at line 354 of file qtextdocument.cpp.
     : QObject(*new QTextDocumentPrivate, parent)
 {
     Q_D(QTextDocument);
     d->init();
     QTextCursor(this).insertText(text);
 }
~QTextDocument()
QTextDocument::~QTextDocument ()
Destroys the document.
Definition at line 375 of file qtextdocument.cpp.
 {
 }
QTextDocument() [3/3]
QTextDocument::QTextDocument (QTextDocumentPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 365 of file qtextdocument.cpp.
     : QObject(dd, parent)
 {
     Q_D(QTextDocument);
     d->init();
 }
Functions
addResource()
void QTextDocument::addResource (int type, const QUrl & name, const QVariant & resource)
Adds the resource resource to the resource cache, using type and name as identifiers.
type should be a value from QTextDocument::ResourceType.
For example, you can add an image as a resource in order to reference it from within the document:
    document->addResource(QTextDocument::ImageResource,
        QUrl("mydata://image.png"), QVariant(image));
The image can be inserted into the document using the QTextCursor API:
    QTextImageFormat imageFormat;
    imageFormat.setName("mydata://image.png");
    cursor.insertImage(imageFormat);
Alternatively, you can insert images using the HTML img tag:
    editor->append("<img src=\"mydata://image.png\" />");
Definition at line 2108 of file qtextdocument.cpp.
Referenced by getImage(), getPixmap(), and QTextCursor::insertImage().
 {
     Q_UNUSED(type);
     Q_D(QTextDocument);
     d->resources.insert(name, resource);
 }
adjustSize()
void QTextDocument::adjustSize ()
Adjusts the document to a reasonable size.
Since
4.2
See also
idealWidth(), textWidth, size
Definition at line 880 of file qtextdocument.cpp.
Referenced by QStaticTextPrivate::paintText(), and QWhatsThat::QWhatsThat().
 {
     // Pull this private function in from qglobal.cpp
     QFont f = defaultFont();
     QFontMetrics fm(f);
     int mw =  fm.width(QLatin1Char('x')) * 80;
     int w = mw;
     setTextWidth(w);
     QSizeF size = documentLayout()->documentSize();
     if (size.width() != 0) {
         w = qt_int_sqrt((uint)(5 * size.height() * size.width() / 3));
         setTextWidth(qMin(w, mw));
         size = documentLayout()->documentSize();
         if (w*3 < 5*size.height()) {
             w = qt_int_sqrt((uint)(2 * size.height() * size.width()));
             setTextWidth(qMin(w, mw));
         }
     }
     setTextWidth(idealWidth());
 }
allFormats()
QVector< QTextFormat > QTextDocument::allFormats () const
Returns a vector of text formats for all the formats used in the document.
Definition at line 3219 of file qtextdocument.cpp.
Referenced by QTextOdfWriter::writeAll().
 {
     Q_D(const QTextDocument);
     return d->formatCollection()->formats;
 }
appendUndoItem
void QTextDocument::appendUndoItem (QAbstractUndoItem * item) slot
Appends a custom undo item to the undo stack.
Warning
This function is not part of the public interface.
Definition at line 531 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     d->appendUndoItem(item);
 }
availableRedoSteps()
int QTextDocument::availableRedoSteps () const
Returns the number of available redo steps.
Since
4.6
See also
isRedoAvailable()
Definition at line 1182 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->availableRedoSteps();
 }
availableUndoSteps()
int QTextDocument::availableUndoSteps () const
Returns the number of available undo steps.
Since
4.6
See also
isUndoAvailable()
Definition at line 1167 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->availableUndoSteps();
 }
begin()
QTextBlock QTextDocument::begin () const
Returns the document's first text block.
See also
firstBlock()
Definition at line 1685 of file qtextdocument.cpp.
Referenced by QTextHtmlExporter::emitBlock(), and qTextBlockAt().
 {
     Q_D(const QTextDocument);
     return QTextBlock(docHandle(), d->blockMap().begin().n);
 }
blockCount()
int QTextDocument::blockCount () const
Referenced by adjustSize().
blockCountChanged
QTextDocument::blockCountChanged (int newBlockCount) signal
This signal is emitted when the total number of text blocks in the document changes.
Since
4.3
The value passed in newBlockCount is the new total.
characterAt()
QChar QTextDocument::characterAt (int pos) const
Returns the character at position pos, or a null character if the position is out of range.
Since
4.5
See also
characterCount()
Definition at line 992 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     if (pos < 0 || pos >= d->length())
         return QChar();
     QTextDocumentPrivate::FragmentIterator fragIt = d->find(pos);
     const QTextFragmentData * const frag = fragIt.value();
     const int offsetInFragment = qMax(0, pos - fragIt.position());
     return d->text.at(frag->stringPosition + offsetInFragment);
 }
characterCount()
int QTextDocument::characterCount () const
Returns the number of characters of this document.
Since
4.5
See also
blockCount(), characterAt()
Definition at line 975 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->length();
 }
clear()
void QTextDocument::clear () virtual
Clears the document.
Definition at line 420 of file qtextdocument.cpp.
Referenced by QTextControlPrivate::setContent().
 {
     Q_D(QTextDocument);
     d->clear();
     d->resources.clear();
 }
clearUndoRedoStacks()
void QTextDocument::clearUndoRedoStacks (Stacks stacksToClear = UndoAndRedoStacks)
Clears the stacks specified by stacksToClear.
Since
4.7
This method clears any commands on the undo stack, the redo stack, or both (the default). If commands are cleared, the appropriate signals are emitted, QTextDocument::undoAvailable() or QTextDocument::redoAvailable().
See also
QTextDocument::undoAvailable() QTextDocument::redoAvailable()
Definition at line 493 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     d->clearUndoRedoStacks(stacksToClear, true);
 }
clone()
QTextDocument * QTextDocument::clone (QObject * parent = 0) const
Creates a new QTextDocument that is a copy of this text document.
parent is the parent of the returned text document.
Definition at line 384 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     QTextDocument *doc = new QTextDocument(parent);
     QTextCursor(doc).insertFragment(QTextDocumentFragment(this));
     doc->rootFrame()->setFrameFormat(rootFrame()->frameFormat());
     QTextDocumentPrivate *priv = doc->d_func();
     priv->title = d->title;
     priv->url = d->url;
     priv->pageSize = d->pageSize;
     priv->indentWidth = d->indentWidth;
     priv->defaultTextOption = d->defaultTextOption;
     priv->setDefaultFont(d->defaultFont());
     priv->resources = d->resources;
     priv->cachedResources.clear();
 #ifndef QT_NO_CSSPARSER
     priv->defaultStyleSheet = d->defaultStyleSheet;
     priv->parsedDefaultStyleSheet = d->parsedDefaultStyleSheet;
 #endif
     return doc;
 }
contentsChange
void QTextDocument::contentsChange (int position, int charsRemoved, int charsAdded) signal
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
Information is provided about the position of the character in the document where the change occurred, the number of characters removed (charsRemoved), and the number of characters added (charsAdded).
The signal is emitted before the document's layout manager is notified about the change. This hook allows you to implement syntax highlighting for the document.
See also
QAbstractTextDocumentLayout::documentChanged(), contentsChanged()
contentsChanged
void QTextDocument::contentsChanged () signal
This signal is emitted whenever the document's content changes; for example, when text is inserted or deleted, or when formatting is applied.
See also
contentsChange()
createObject()
QTextObject * QTextDocument::createObject (const QTextFormat & format) protected virtual
Creates and returns a new document object (a QTextObject), based on the given format.
QTextObjects will always get created through this method, so you must reimplement it if you use custom text objects inside your document.
Definition at line 1586 of file qtextdocument.cpp.
Referenced by QTextDocumentPrivate::createObject().
 {
     QTextObject *obj = 0;
     if (f.isListFormat())
         obj = new QTextList(this);
     else if (f.isTableFormat())
         obj = new QTextTable(this);
     else if (f.isFrameFormat())
         obj = new QTextFrame(this);
     return obj;
 }
cursorPositionChanged
QTextDocument::cursorPositionChanged (const QTextCursor & cursor) signal
This signal is emitted whenever the position of a cursor changed due to an editing operation.
The cursor that changed is passed in cursor. If you need a signal when the cursor is moved with the arrow keys you can use the QTextEdit::cursorPositionChanged() signal in QTextEdit.
defaultCursorMoveStyle()
Qt::CursorMoveStyle QTextDocument::defaultCursorMoveStyle () const
The default cursor movement style is used by all QTextCursor objects created from the document.
Since
4.8
The default is Qt::LogicalMoveStyle.
Definition at line 638 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->defaultCursorMoveStyle;
 }
defaultFont()
QFont QTextDocument::defaultFont () const
Referenced by adjustSize(), and setDefaultFont().
defaultStyleSheet()
QString QTextDocument::defaultStyleSheet () const
Referenced by setDefaultStyleSheet().
defaultTextOption()
QTextOption QTextDocument::defaultTextOption () const
the default text option will be set on all QTextLayout in the document.
The default text option is used on all QTextLayout objects in the document.
When QTextBlock are created, the defaultTextOption is set on their QTextLayout. This allows setting global properties for the document such as the default word wrap mode.
Since
4.3
This allows setting global properties for the document such as the default word wrap mode.
Definition at line 607 of file qtextdocument.cpp.
Referenced by QLabelPrivate::ensureTextLayouted(), QPlainTextDocumentLayout::layoutBlock(), QTextEditPrivate::updateDefaultTextOption(), and QPlainTextEditPrivate::updateDefaultTextOption().
 {
     Q_D(const QTextDocument);
     return d->defaultTextOption;
 }
docHandle()
QTextDocumentPrivate * QTextDocument::docHandle () const
So that not all classes have to be friends of each other.
Warning
This function is not part of the public interface.
..
Definition at line 3234 of file qtextdocument.cpp.
Referenced by QPlainTextEdit::anchorAt(), begin(), QTextBlockGroup::blockRemoved(), QTextHtmlExporter::emitBlock(), end(), findBlock(), findBlockByLineNumber(), findBlockByNumber(), QTextHtmlExporter::findUrlForImage(), firstBlock(), QTextCursor::insertFragment(), QTextDocumentFragment::isEmpty(), isModified(), lastBlock(), QTextDocumentFragmentPrivate::QTextDocumentFragmentPrivate(), QSyntaxHighlighterPrivate::reformatBlocks(), QAbstractTextDocumentLayoutPrivate::setDocument(), setModified(), QTextHtmlExporter::toHtml(), and QTextOdfWriter::writeAll().
 {
     Q_D(const QTextDocument);
     return const_cast<QTextDocumentPrivate *>(d);
 }
documentLayout()
QAbstractTextDocumentLayout * QTextDocument::documentLayout () const
Returns the document layout for this document.
Definition at line 1223 of file qtextdocument.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QTextControlPrivate::_q_documentLayoutChanged(), adjustSize(), QPlainTextEditPrivate::append(), QPlainTextEdit::blockBoundingRect(), boundingRectOfFloatsInSelection(), QTextEngine::docLayout(), documentSize(), drawContents(), getImageSize(), getPixmapSize(), QPlainTextEditControl::hitTest(), idealWidth(), QTextEditPrivate::init(), QPlainTextEditPrivate::init(), QWhatsThat::mouseMoveEvent(), QWhatsThat::mousePressEvent(), QWhatsThat::mouseReleaseEvent(), QAccessibleTextWidget::offsetAtPoint(), pageCount(), QTextEditPrivate::paint(), QGraphicsTextItem::paint(), QWhatsThat::paintEvent(), QPlainTextEdit::paintEvent(), QStaticTextPrivate::paintText(), QTextControl::print(), printPage(), QAccessibleTextEdit::rect(), QTextEditPrivate::relayoutDocument(), QPlainTextEditPrivate::relayoutDocument(), QTextEdit::resizeEvent(), QPlainTextEdit::setDocument(), and QPlainTextEditPrivate::verticalOffset().
 {
     Q_D(const QTextDocument);
     if (!d->lout) {
         QTextDocument *that = const_cast<QTextDocument *>(this);
         that->d_func()->setLayout(new QTextDocumentLayout(that));
     }
     return d->lout;
 }
documentLayoutChanged
QTextDocument::documentLayoutChanged () signal
This signal is emitted when a new document layout is set.
Since
4.4
See also
setDocumentLayout()
documentMargin()
qreal QTextDocument::documentMargin () const
Referenced by idealWidth().
drawContents()
void QTextDocument::drawContents (QPainter * p, const QRectF & rect = QRectF())
Draws the content of the document with painter p, clipped to rect.
Since
4.2
If rect is a null rectangle (default) then the document is painted unclipped.
Definition at line 724 of file qtextdocument.cpp.
Referenced by QSplashScreen::drawContents().
 {
     p->save();
     QAbstractTextDocumentLayout::PaintContext ctx;
     if (rect.isValid()) {
         p->setClipRect(rect);
         ctx.clip = rect;
     }
     documentLayout()->draw(p, ctx);
     p->restore();
 }
end()
QTextBlock QTextDocument::end () const
This function returns a block to test for the end of the document while iterating over it.
    for (QTextBlock it = doc->begin(); it != doc->end(); it = it.next())
        cout << it.text().toStdString() << endl;
The block returned is invalid and represents the block after the last block in the document. You can use lastBlock() to retrieve the last valid block of the document.
See also
lastBlock()
Definition at line 1703 of file qtextdocument.cpp.
Referenced by findInBlock(), and formatDifference().
 {
     return QTextBlock(docHandle(), 0);
 }
find() [1/4]
QTextCursor QTextDocument::find (const QString & subString, int position = 0, FindFlags options = 0) const
Finds the next occurrence of the string, subString, in the document.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The search starts at the given position, and proceeds forwards through the document unless specified otherwise in the search options. The options control the type of search performed.
Returns a cursor with the match selected if subString was found; otherwise returns a null cursor.
If the position is 0 (the default) the search begins from the beginning of the document; otherwise it begins at the specified position.
Definition at line 1402 of file qtextdocument.cpp.
Referenced by QLabelPrivate::ensureTextPopulated(), and find().
 {
     QRegExp expr(subString);
     expr.setPatternSyntax(QRegExp::FixedString);
     expr.setCaseSensitivity((options & QTextDocument::FindCaseSensitively) ? Qt::CaseSensitive : Qt::CaseInsensitive);
     return find(expr, from, options);
 }
find() [2/4]
QTextCursor QTextDocument::find (const QString & subString, const QTextCursor & cursor, FindFlags options = 0) const
Finds the next occurrence of the string, subString, in the document.
The search starts at the position of the given cursor, and proceeds forwards through the document unless specified otherwise in the search options. The options control the type of search performed.
Returns a cursor with the match selected if subString was found; otherwise returns a null cursor.
If the given cursor has a selection, the search begins after the selection; otherwise it begins at the cursor's position.
By default the search is case-sensitive, and can match text anywhere in the document.
Definition at line 1431 of file qtextdocument.cpp.
 {
     int pos = 0;
     if (!from.isNull()) {
         if (options & QTextDocument::FindBackward)
             pos = from.selectionStart();
         else
             pos = from.selectionEnd();
     }
     QRegExp expr(subString);
     expr.setPatternSyntax(QRegExp::FixedString);
     expr.setCaseSensitivity((options & QTextDocument::FindCaseSensitively) ? Qt::CaseSensitive : Qt::CaseInsensitive);
     return find(expr, pos, options);
 }
find() [3/4]
QTextCursor QTextDocument::find (const QRegExp & expr, int position = 0, FindFlags options = 0) const
Finds the next occurrence, matching the regular expression, expr, in the document.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The search starts at the given position, and proceeds forwards through the document unless specified otherwise in the search options. The options control the type of search performed. The FindCaseSensitively option is ignored for this overload, use QRegExp::caseSensitivity instead.
Returns a cursor with the match selected if a match was found; otherwise returns a null cursor.
If the position is 0 (the default) the search begins from the beginning of the document; otherwise it begins at the specified position.
Definition at line 1503 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     if (expr.isEmpty())
         return QTextCursor();
     int pos = from;
     //the cursor is positioned between characters, so for a backward search
     //do not include the character given in the position.
     if (options & FindBackward) {
         --pos ;
         if(pos < 0)
             return QTextCursor();
     }
     QTextCursor cursor;
     QTextBlock block = d->blocksFind(pos);
     if (!(options & FindBackward)) {
        int blockOffset = qMax(0, pos - block.position());
         while (block.isValid()) {
             if (findInBlock(block, expr, blockOffset, options, cursor))
                 return cursor;
             blockOffset = 0;
             block = block.next();
         }
     } else {
         int blockOffset = pos - block.position();
         while (block.isValid()) {
             if (findInBlock(block, expr, blockOffset, options, cursor))
                 return cursor;
             block = block.previous();
             blockOffset = block.length() - 1;
         }
     }
     return QTextCursor();
 }
find() [4/4]
QTextCursor QTextDocument::find (const QRegExp & expr, const QTextCursor & cursor, FindFlags options = 0) const
Finds the next occurrence, matching the regular expression, expr, in the document.
The search starts at the position of the given cursor, and proceeds forwards through the document unless specified otherwise in the search options. The options control the type of search performed. The FindCaseSensitively option is ignored for this overload, use QRegExp::caseSensitivity instead.
Returns a cursor with the match selected if a match was found; otherwise returns a null cursor.
If the given cursor has a selection, the search begins after the selection; otherwise it begins at the cursor's position.
By default the search is case-sensitive, and can match text anywhere in the document.
Definition at line 1564 of file qtextdocument.cpp.
 {
     int pos = 0;
     if (!from.isNull()) {
         if (options & QTextDocument::FindBackward)
             pos = from.selectionStart();
         else
             pos = from.selectionEnd();
     }
     return find(expr, pos, options);
 }
findBlock()
QTextBlock QTextDocument::findBlock (int pos) const
Returns the text block that contains the {pos}-th character.
Definition at line 1644 of file qtextdocument.cpp.
Referenced by QAccessibleTextWidget::characterRect(), QTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::documentChanged(), QPlainTextEditPrivate::ensureVisible(), and QSyntaxHighlighterPrivate::reformatBlocks().
 {
     Q_D(const QTextDocument);
     return QTextBlock(docHandle(), d->blockMap().findNode(pos));
 }
findBlockByLineNumber()
QTextBlock QTextDocument::findBlockByLineNumber (int lineNumber) const
Returns the text block that contains the specified lineNumber.
Since
4.5
See also
QTextBlock::firstLineNumber()
Definition at line 1674 of file qtextdocument.cpp.
Referenced by QPlainTextEditPrivate::setTopBlock(), and QPlainTextEditPrivate::setTopLine().
 {
     Q_D(const QTextDocument);
     return QTextBlock(docHandle(), d->blockMap().findNode(lineNumber, 2));
 }
findBlockByNumber()
QTextBlock QTextDocument::findBlockByNumber (int blockNumber) const
Returns the text block with the specified blockNumber.
Since
4.4
See also
QTextBlock::blockNumber()
Definition at line 1659 of file qtextdocument.cpp.
Referenced by QPlainTextEditControl::blockBoundingRect(), QPlainTextEditControl::firstVisibleBlock(), QScriptEdit::gotoLine(), QPlainTextEditControl::hitTest(), QPlainTextEditPrivate::setTopBlock(), and QPlainTextEditPrivate::verticalOffset().
 {
     Q_D(const QTextDocument);
     return QTextBlock(docHandle(), d->blockMap().findNode(blockNumber, 1));
 }
firstBlock()
QTextBlock QTextDocument::firstBlock () const
Returns the document's first text block.
Since
4.4
Definition at line 1715 of file qtextdocument.cpp.
Referenced by QPlainTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::layoutBlock(), and QPlainTextDocumentLayoutPrivate::relayout().
 {
     Q_D(const QTextDocument);
     return QTextBlock(docHandle(), d->blockMap().begin().n);
 }
frameAt()
QTextFrame * QTextDocument::frameAt (int pos) const
Returns the frame that contains the text cursor position pos.
Warning
This function is not part of the public interface.
Definition at line 1607 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->frameAt(pos);
 }
idealWidth()
qreal QTextDocument::idealWidth () const
Returns the ideal width of the text document.
Since
4.2
The ideal width is the actually used width of the document without optional alignments taken into account. It is always <= size().width().
See also
adjustSize(), textWidth
Definition at line 786 of file qtextdocument.cpp.
Referenced by adjustSize().
 {
     if (QTextDocumentLayout *lout = qobject_cast<QTextDocumentLayout *>(documentLayout()))
         return lout->idealWidth();
     return textWidth();
 }
indentWidth()
qreal QTextDocument::indentWidth () const
Referenced by setDocumentMargin().
isEmpty()
bool QTextDocument::isEmpty () const
Returns true if the document is empty; otherwise returns false.
Definition at line 409 of file qtextdocument.cpp.
Referenced by QPlainTextEdit::keyPressEvent(), and QTextEdit::keyPressEvent().
 {
     Q_D(const QTextDocument);
     /* because if we're empty we still have one single paragraph as
      * one single fragment */
     return d->length() <= 1;
 }
isModified()
bool QTextDocument::isModified () const
Definition at line 1818 of file qtextdocument.cpp.
 {
     return docHandle()->isModified();
 }
isRedoAvailable()
bool QTextDocument::isRedoAvailable () const
Returns true if redo is available; otherwise returns false.
See also
isUndoAvailable(), availableRedoSteps()
Definition at line 1152 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->isRedoAvailable();
 }
isUndoAvailable()
bool QTextDocument::isUndoAvailable () const
Returns true if undo is available; otherwise returns false.
See also
isRedoAvailable(), availableUndoSteps()
Definition at line 1141 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->isUndoAvailable();
 }
isUndoRedoEnabled()
bool QTextDocument::isUndoRedoEnabled () const
Definition at line 553 of file qtextdocument.cpp.
Referenced by QTextEdit::isUndoRedoEnabled(), and QTextControlPrivate::setContent().
 {
     Q_D(const QTextDocument);
     return d->isUndoRedoEnabled();
 }
lastBlock()
QTextBlock QTextDocument::lastBlock () const
Returns the document's last (valid) text block.
Since
4.4
Definition at line 1728 of file qtextdocument.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), and QPlainTextEditPrivate::append().
 {
     Q_D(const QTextDocument);
     return QTextBlock(docHandle(), d->blockMap().last().n);
 }
lineCount()
int QTextDocument::lineCount () const
Returns the number of lines of this document (if the layout supports this).
Since
4.5
Otherwise, this is identical to the number of blocks.
See also
blockCount(), characterCount()
Definition at line 959 of file qtextdocument.cpp.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QPlainTextDocumentLayout::layoutBlock(), and QDeclarativeTextPrivate::setupTextLayout().
 {
     Q_D(const QTextDocument);
     return d->blockMap().length(2);
 }
loadResource()
QVariant QTextDocument::loadResource (int type, const QUrl & name) protected virtual
Loads data of the specified type from the resource with the given name.
This function is called by the rich text engine to request data that isn't directly stored by QTextDocument, but still associated with it. For example, images are referenced indirectly by the name attribute of a QTextImageFormat object.
When called by Qt, type is one of the values of QTextDocument::ResourceType.
If the QTextDocument is a child object of a QTextEdit, QTextBrowser, or a QTextDocument itself then the default implementation tries to retrieve the data from the parent.
Reimplemented in QTextDocumentWithImageResources.
Definition at line 2131 of file qtextdocument.cpp.
Referenced by QTextDocumentWithImageResources::loadResource(), and loadResource().
 {
     Q_D(QTextDocument);
     QVariant r;
     QTextDocument *doc = qobject_cast<QTextDocument *>(parent());
     if (doc) {
         r = doc->loadResource(type, name);
     }
 #ifndef QT_NO_TEXTEDIT
     else if (QTextEdit *edit = qobject_cast<QTextEdit *>(parent())) {
         QUrl resolvedName = edit->d_func()->resolveUrl(name);
         r = edit->loadResource(type, resolvedName);
     }
 #endif
 #ifndef QT_NO_TEXTCONTROL
     else if (QTextControl *control = qobject_cast<QTextControl *>(parent())) {
         r = control->loadResource(type, name);
     }
 #endif
     // handle data: URLs
     if (r.isNull() && name.scheme().compare(QLatin1String("data"), Qt::CaseInsensitive) == 0)
         r = qDecodeDataUrl(name).second;
     // if resource was not loaded try to load it here
     if (!doc && r.isNull() && name.isRelative()) {
         QUrl currentURL = d->url;
         QUrl resourceUrl = name;
         // For the second case QUrl can merge "#someanchor" with "foo.html"
         // correctly to "foo.html#someanchor"
         if (!(currentURL.isRelative()
               || (currentURL.scheme() == QLatin1String("file")
                   && !QFileInfo(currentURL.toLocalFile()).isAbsolute()))
             || (name.hasFragment() && name.path().isEmpty())) {
             resourceUrl =  currentURL.resolved(name);
         } else {
             // this is our last resort when current url and new url are both relative
             // we try to resolve against the current working directory in the local
             // file system.
             QFileInfo fi(currentURL.toLocalFile());
             if (fi.exists()) {
                 resourceUrl =
                     QUrl::fromLocalFile(fi.absolutePath() + QDir::separator()).resolved(name);
             } else if (currentURL.isEmpty()) {
                 resourceUrl.setScheme(QLatin1String("file"));
             }
         }
         QString s = resourceUrl.toLocalFile();
         QFile f(s);
         if (!s.isEmpty() && f.open(QFile::ReadOnly)) {
             r = f.readAll();
             f.close();
         }
     }
     if (!r.isNull()) {
         if (type == ImageResource && r.type() == QVariant::ByteArray) {
             if (qApp->thread() != QThread::currentThread()) {
                 // must use images in non-GUI threads
                 QImage image;
                 image.loadFromData(r.toByteArray());
                 if (!image.isNull())
                     r = image;
             } else {
                 QPixmap pm;
                 pm.loadFromData(r.toByteArray());
                 if (!pm.isNull())
                     r = pm;
             }
         }
         d->cachedResources.insert(name, r);
     }
     return r;
 }
markContentsDirty()
void QTextDocument::markContentsDirty (int from, int length)
Marks the contents specified by the given position and length as "dirty", informing the document that it needs to be laid out again.
Definition at line 668 of file qtextdocument.cpp.
Referenced by QSyntaxHighlighterPrivate::applyFormatChanges().
 {
     Q_D(QTextDocument);
     d->documentChange(from, length);
     if (!d->inContentsChange) {
         if (d->lout) {
             d->lout->documentChanged(d->docChangeFrom, d->docChangeOldLength, d->docChangeLength);
             d->docChangeFrom = -1;
         }
     }
 }
maximumBlockCount()
int QTextDocument::maximumBlockCount () const
Referenced by isUndoRedoEnabled().
metaInformation()
QString QTextDocument::metaInformation (MetaInformation info) const
Returns meta information about the document of the type specified by info.
See also
setMetaInformation()
Definition at line 1240 of file qtextdocument.cpp.
Referenced by QTextEdit::documentTitle(), QTextControl::print(), and QTextHtmlExporter::toHtml().
 {
     Q_D(const QTextDocument);
     switch (info) {
     case DocumentTitle:
         return d->title;
     case DocumentUrl:
         return d->url;
     }
     return QString();
 }
modificationChanged
QTextDocument::modificationChanged (bool changed) signal
This signal is emitted whenever the content of the document changes in a way that affects the modification state.
If changed is true, the document has been modified; otherwise it is false.
For example, calling setModified(false) on a document and then inserting text causes the signal to get emitted. If you undo that operation, causing the document to return to its original unmodified state, the signal will get emitted again.
object()
QTextObject * QTextDocument::object (int objectIndex) const
Returns the text object associated with the given objectIndex.
Definition at line 1625 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->objectForIndex(objectIndex);
 }
objectForFormat()
QTextObject * QTextDocument::objectForFormat (const QTextFormat & f) const
Returns the text object associated with the format f.
Definition at line 1634 of file qtextdocument.cpp.
Referenced by QTextDocumentLayoutPrivate::blockIndent(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawListItem(), QTextHtmlExporter::emitFragment(), QTextBlock::textList(), and QTextOdfWriter::writeAll().
 {
     Q_D(const QTextDocument);
     return d->objectForFormat(f);
 }
pageCount()
int QTextDocument::pageCount () const
returns the number of pages in this document.
Definition at line 1764 of file qtextdocument.cpp.
 {
     return documentLayout()->pageCount();
 }
pageSize()
QSizeF QTextDocument::pageSize () const
Referenced by setPageSize().
print()
void QTextDocument::print (QPrinter * printer) const
Prints the document to the given printer.
The QPrinter must be set up before being used with this function.
This is only a convenience method to print the whole document to the printer.
If the document is already paginated through a specified height in the pageSize() property it is printed as-is.
If the document is not paginated, like for example a document used in a QTextEdit, then a temporary copy of the document is created and the copy is broken into multiple pages according to the size of the QPrinter's paperRect(). By default a 2 cm margin is set around the document contents. In addition the current page number is printed at the bottom of each page.
Note that QPrinter::Selection is not supported as print range with this function since the selection is a property of QTextCursor. If you have a QTextEdit associated with your QTextDocument then you can use QTextEdit's print() function because QTextEdit has access to the user's selection.
See also
QTextEdit::print()
Definition at line 1884 of file qtextdocument.cpp.
Referenced by QTextControl::print().
 {
     Q_D(const QTextDocument);
     if (!printer || !printer->isValid())
         return;
     if (!d->title.isEmpty())
         printer->setDocName(d->title);
     bool documentPaginated = d->pageSize.isValid() && !d->pageSize.isNull()
                              && d->pageSize.height() != INT_MAX;
     if (!documentPaginated && !printer->fullPage() && !printer->d_func()->hasCustomPageMargins)
         printer->setPageMargins(23.53, 23.53, 23.53, 23.53, QPrinter::Millimeter);
     QPainter p(printer);
     // Check that there is a valid device to print to.
     if (!p.isActive())
         return;
     const QTextDocument *doc = this;
     QScopedPointer<QTextDocument> clonedDoc;
     (void)doc->documentLayout(); // make sure that there is a layout
     QRectF body = QRectF(QPointF(0, 0), d->pageSize);
     QPointF pageNumberPos;
     if (documentPaginated) {
         qreal sourceDpiX = qt_defaultDpi();
         qreal sourceDpiY = sourceDpiX;
         QPaintDevice *dev = doc->documentLayout()->paintDevice();
         if (dev) {
             sourceDpiX = dev->logicalDpiX();
             sourceDpiY = dev->logicalDpiY();
         }
         const qreal dpiScaleX = qreal(printer->logicalDpiX()) / sourceDpiX;
         const qreal dpiScaleY = qreal(printer->logicalDpiY()) / sourceDpiY;
         // scale to dpi
         p.scale(dpiScaleX, dpiScaleY);
         QSizeF scaledPageSize = d->pageSize;
         scaledPageSize.rwidth() *= dpiScaleX;
         scaledPageSize.rheight() *= dpiScaleY;
         const QSizeF printerPageSize(printer->pageRect().size());
         // scale to page
         p.scale(printerPageSize.width() / scaledPageSize.width(),
                 printerPageSize.height() / scaledPageSize.height());
     } else {
         doc = clone(const_cast<QTextDocument *>(this));
         clonedDoc.reset(const_cast<QTextDocument *>(doc));
         for (QTextBlock srcBlock = firstBlock(), dstBlock = clonedDoc->firstBlock();
              srcBlock.isValid() && dstBlock.isValid();
              srcBlock = srcBlock.next(), dstBlock = dstBlock.next()) {
             dstBlock.layout()->setAdditionalFormats(srcBlock.layout()->additionalFormats());
         }
         QAbstractTextDocumentLayout *layout = doc->documentLayout();
         layout->setPaintDevice(p.device());
         // copy the custom object handlers
         layout->d_func()->handlers = documentLayout()->d_func()->handlers;
         int dpiy = p.device()->logicalDpiY();
         int margin = 0;
         if (printer->fullPage() && !printer->d_func()->hasCustomPageMargins) {
             // for compatibility
             margin = (int) ((2/2.54)*dpiy); // 2 cm margins
             QTextFrameFormat fmt = doc->rootFrame()->frameFormat();
             fmt.setMargin(margin);
             doc->rootFrame()->setFrameFormat(fmt);
         }
         QRectF pageRect(printer->pageRect());
         body = QRectF(0, 0, pageRect.width(), pageRect.height());
         pageNumberPos = QPointF(body.width() - margin,
                                 body.height() - margin
                                 + QFontMetrics(doc->defaultFont(), p.device()).ascent()
                                 + 5 * dpiy / 72.0);
         clonedDoc->setPageSize(body.size());
     }
     int docCopies;
     int pageCopies;
     if (printer->collateCopies() == true){
         docCopies = 1;
         pageCopies = printer->supportsMultipleCopies() ? 1 : printer->copyCount();
     } else {
         docCopies = printer->supportsMultipleCopies() ? 1 : printer->copyCount();
         pageCopies = 1;
     }
     int fromPage = printer->fromPage();
     int toPage = printer->toPage();
     bool ascending = true;
     if (fromPage == 0 && toPage == 0) {
         fromPage = 1;
         toPage = doc->pageCount();
     }
     // paranoia check
     fromPage = qMax(1, fromPage);
     toPage = qMin(doc->pageCount(), toPage);
     if (toPage < fromPage) {
         // if the user entered a page range outside the actual number
         // of printable pages, just return
         return;
     }
     if (printer->pageOrder() == QPrinter::LastPageFirst) {
         int tmp = fromPage;
         fromPage = toPage;
         toPage = tmp;
         ascending = false;
     }
     for (int i = 0; i < docCopies; ++i) {
         int page = fromPage;
         while (true) {
             for (int j = 0; j < pageCopies; ++j) {
                 if (printer->printerState() == QPrinter::Aborted
                     || printer->printerState() == QPrinter::Error)
                     return;
                 printPage(page, &p, doc, body, pageNumberPos);
                 if (j < pageCopies - 1)
                     printer->newPage();
             }
             if (page == toPage)
                 break;
             if (ascending)
                 ++page;
             else
                 --page;
             printer->newPage();
         }
         if ( i < docCopies - 1)
             printer->newPage();
     }
 }
redo() [1/2]
void QTextDocument::redo (QTextCursor * cursor)
Redoes the last editing operation on the document if redo is available.
Since
4.2
The provided cursor is positioned at the end of the location where the edition operation was redone.
Definition at line 462 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     const int pos = d->undoRedo(false);
     if (cursor && pos >= 0) {
         *cursor = QTextCursor(this);
         cursor->setPosition(pos);
     }
 }
redo [2/2]
void QTextDocument::redo () slot
Redoes the last editing operation on the document if redo is available.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 517 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     d->undoRedo(false);
 }
redoAvailable
QTextDocument::redoAvailable (bool available) signal
This signal is emitted whenever redo operations become available (available is true) or unavailable (available is false).
resource()
QVariant QTextDocument::resource (int type, const QUrl & name) const
Returns data of the specified type from the resource with the given name.
This function is called by the rich text engine to request data that isn't directly stored by QTextDocument, but still associated with it. For example, images are referenced indirectly by the name attribute of a QTextImageFormat object.
Resources are cached internally in the document. If a resource can not be found in the cache, loadResource is called to try to load the resource. loadResource should then use addResource to add the resource to the cache.
See also
QTextDocument::ResourceType
Definition at line 2078 of file qtextdocument.cpp.
Referenced by QTextHtmlParserNode::applyBackgroundImage(), getImage(), and getPixmap().
 {
     Q_D(const QTextDocument);
     QVariant r = d->resources.value(name);
     if (!r.isValid()) {
         r = d->cachedResources.value(name);
         if (!r.isValid())
             r = const_cast<QTextDocument *>(this)->loadResource(type, name);
     }
     return r;
 }
revision()
int QTextDocument::revision () const
Returns the document's revision (if undo is enabled).
Since
4.4
The revision is guaranteed to increase when a document that is not modified is edited.
See also
QTextBlock::revision(), isModified()
Definition at line 1200 of file qtextdocument.cpp.
 {
     Q_D(const QTextDocument);
     return d->revision;
 }
rootFrame()
QTextFrame * QTextDocument::rootFrame () const
Returns the document's root frame.
Definition at line 1616 of file qtextdocument.cpp.
Referenced by clone(), QTextHtmlImporter::closeTag(), QTextDocumentLayoutPrivate::drawBlock(), QTextHtmlExporter::emitFrame(), QLabelPrivate::ensureTextLayouted(), QTextDocumentLayoutPrivate::frameIteratorForYPosition(), QTextDocumentLayoutPrivate::layoutFlow(), QTextHtmlImporter::processSpecialNodes(), setDocumentMargin(), QTextHtmlExporter::toHtml(), QTextOdfWriter::writeAll(), and QTextOdfWriter::writeFrame().
 {
     Q_D(const QTextDocument);
     return d->rootFrame();
 }
setDefaultCursorMoveStyle()
void QTextDocument::setDefaultCursorMoveStyle (Qt::CursorMoveStyle style)
Sets the default cursor movement style to the given style.
Since
4.8
Definition at line 652 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     d->defaultCursorMoveStyle = style;
 }
setDefaultFont()
void QTextDocument::setDefaultFont (const QFont & font)
Sets the default font to use in the document layout.
Definition at line 1772 of file qtextdocument.cpp.
Referenced by QTextEditPrivate::init(), QPlainTextEditPrivate::init(), QStaticTextPrivate::paintText(), QTextControl::print(), QWhatsThat::QWhatsThat(), and QGraphicsTextItem::setFont().
 {
     Q_D(QTextDocument);
     d->setDefaultFont(font);
     if (d->lout)
         d->lout->documentChanged(0, 0, d->length());
 }
setDefaultStyleSheet()
void QTextDocument::setDefaultStyleSheet (const QString & sheet)
Definition at line 1023 of file qtextdocument.cpp.
Referenced by QStaticTextPrivate::paintText().
 {
     Q_D(QTextDocument);
     d->defaultStyleSheet = sheet;
     QCss::Parser parser(sheet);
     d->parsedDefaultStyleSheet = QCss::StyleSheet();
     d->parsedDefaultStyleSheet.origin = QCss::StyleSheetOrigin_UserAgent;
     parser.parse(&d->parsedDefaultStyleSheet);
 }
setDefaultTextOption()
void QTextDocument::setDefaultTextOption (const QTextOption & option)
Sets the default text option.
Since
4.3
Definition at line 621 of file qtextdocument.cpp.
Referenced by QLabelPrivate::ensureTextLayouted(), QStaticTextPrivate::paintText(), QTextEditPrivate::updateDefaultTextOption(), and QPlainTextEditPrivate::updateDefaultTextOption().
 {
     Q_D(QTextDocument);
     d->defaultTextOption = option;
     if (d->lout)
         d->lout->documentChanged(0, 0, d->length());
 }
setDocumentLayout()
void QTextDocument::setDocumentLayout (QAbstractTextDocumentLayout * layout)
Sets the document to use the given layout.
The previous layout is deleted.
See also
documentLayoutChanged()
Definition at line 1214 of file qtextdocument.cpp.
Referenced by QPlainTextEditPrivate::init(), and QPlainTextEdit::setDocument().
 {
     Q_D(QTextDocument);
     d->setLayout(layout);
 }
setDocumentMargin()
void QTextDocument::setDocumentMargin (qreal margin)
Definition at line 808 of file qtextdocument.cpp.
Referenced by QStaticTextPrivate::paintText().
 {
     Q_D(QTextDocument);
     if (d->documentMargin != margin) {
         d->documentMargin = margin;
         QTextFrame* root = rootFrame();
         QTextFrameFormat format = root->frameFormat();
         format.setMargin(margin);
         root->setFrameFormat(format);
         if (d->lout)
             d->lout->documentChanged(0, 0, d->length());
     }
 }
setHtml()
void QTextDocument::setHtml (const QString & html)
Replaces the entire contents of the document with the given HTML-formatted text in the html string.
The HTML formatting is respected as much as possible; for example, "<b>bold</b> text" will produce text where the first word has a font weight that gives it a bold appearance: "<b>bold</b> text".
Note
It is the responsibility of the caller to make sure that the text is correctly decoded when a QString containing HTML is created and passed to setHtml().
See also
setPlainText(), {Supported HTML Subset}
Definition at line 1338 of file qtextdocument.cpp.
Referenced by QSplashScreen::drawContents(), QLabelPrivate::ensureTextPopulated(), handleStringAttribute(), QStaticTextPrivate::paintText(), QWhatsThat::QWhatsThat(), QTextDocumentWithImageResources::requestFinished(), QTextControlPrivate::setContent(), QTextDocumentWithImageResources::setText(), and QAccessibleDisplay::text().
 {
     Q_D(QTextDocument);
     bool previousState = d->isUndoRedoEnabled();
     d->enableUndoRedo(false);
     d->beginEditBlock();
     d->clear();
     QTextHtmlImporter(this, html, QTextHtmlImporter::ImportToDocument).import();
     d->endEditBlock();
     d->enableUndoRedo(previousState);
 }
setIndentWidth()
void QTextDocument::setIndentWidth (qreal width)
Sets the width used for text list and text block indenting.
Since
4.4
The indent properties of QTextListFormat and QTextBlockFormat specify multiples of this value. The default indent width is 40 .
See also
indentWidth()
Definition at line 857 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     if (d->indentWidth != width) {
         d->indentWidth = width;
         if (d->lout)
             d->lout->documentChanged(0, 0, d->length());
     }
 }
setMaximumBlockCount()
void QTextDocument::setMaximumBlockCount (int maximum)
Definition at line 589 of file qtextdocument.cpp.
Referenced by QPlainTextEditPrivate::append().
 {
     Q_D(QTextDocument);
     d->maximumBlockCount = maximum;
     d->ensureMaximumBlockCount();
     setUndoRedoEnabled(false);
 }
setMetaInformation()
void QTextDocument::setMetaInformation (MetaInformation info, const QString & string)
Sets the document's meta information of the type specified by info to the given string.
See also
metaInformation()
Definition at line 1258 of file qtextdocument.cpp.
Referenced by QTextHtmlImporter::import(), QTextControl::print(), and QTextEdit::setDocumentTitle().
 {
     Q_D(QTextDocument);
     switch (info) {
     case DocumentTitle:
         d->title = string;
         break;
     case DocumentUrl:
         d->url = string;
         break;
     }
 }
setModified
void QTextDocument::setModified (bool m = true) slot
Definition at line 1823 of file qtextdocument.cpp.
Referenced by QTextControlPrivate::setContent().
 {
     docHandle()->setModified(m);
 }
setPageSize()
void QTextDocument::setPageSize (const QSizeF & size)
Definition at line 1747 of file qtextdocument.cpp.
Referenced by QTextEditPrivate::init(), QTextControl::print(), QTextEditPrivate::relayoutDocument(), and setTextWidth().
 {
     Q_D(QTextDocument);
     d->pageSize = size;
     if (d->lout)
         d->lout->documentChanged(0, 0, d->length());
 }
setPlainText()
void QTextDocument::setPlainText (const QString & text)
Replaces the entire contents of the document with the given plain text.
See also
setHtml()
Definition at line 1309 of file qtextdocument.cpp.
Referenced by QSplashScreen::drawContents(), QLabelPrivate::ensureTextPopulated(), QStaticTextPrivate::paintText(), QWhatsThat::QWhatsThat(), QTextDocumentWithImageResources::requestFinished(), QTextControlPrivate::setContent(), and QTextDocumentWithImageResources::setText().
 {
     Q_D(QTextDocument);
     bool previousState = d->isUndoRedoEnabled();
     d->enableUndoRedo(false);
     d->beginEditBlock();
     d->clear();
     QTextCursor(this).insertText(text);
     d->endEditBlock();
     d->enableUndoRedo(previousState);
 }
setTextWidth()
void QTextDocument::setTextWidth (qreal width)
Definition at line 760 of file qtextdocument.cpp.
Referenced by adjustSize(), QSplashScreen::drawContents(), QLabelPrivate::ensureTextLayouted(), QPlainTextEditPrivate::init(), and QStaticTextPrivate::paintText().
 {
     Q_D(QTextDocument);
     QSizeF sz = d->pageSize;
     sz.setWidth(width);
     sz.setHeight(-1);
     setPageSize(sz);
 }
setUndoRedoEnabled()
void QTextDocument::setUndoRedoEnabled (bool enable)
Definition at line 547 of file qtextdocument.cpp.
Referenced by QLabelPrivate::ensureTextPopulated(), QTextEditPrivate::init(), QTextControlPrivate::init(), QTextDocumentFragmentPrivate::QTextDocumentFragmentPrivate(), QWhatsThat::QWhatsThat(), QTextControlPrivate::setContent(), setMaximumBlockCount(), and QTextEdit::setUndoRedoEnabled().
 {
     Q_D(QTextDocument);
     d->enableUndoRedo(enable);
 }
setUseDesignMetrics()
void QTextDocument::setUseDesignMetrics (bool b)
Definition at line 699 of file qtextdocument.cpp.
Referenced by QTextControl::print().
 {
     Q_D(QTextDocument);
     if (b == d->defaultTextOption.useDesignMetrics())
         return;
     d->defaultTextOption.setUseDesignMetrics(b);
     if (d->lout)
         d->lout->documentChanged(0, 0, d->length());
 }
size()
QSizeF QTextDocument::size () const
Referenced by adjustSize(), setPageSize(), QDeclarativeTextPrivate::textDocumentImage(), QDeclarativeTextPrivate::textLayoutImage(), and QDeclarativeTextPrivate::updateSize().
textWidth()
qreal QTextDocument::textWidth () const
Referenced by idealWidth(), and setTextWidth().
toHtml()
QString QTextDocument::toHtml (const QByteArray & encoding = QByteArray()) const
Returns a string containing an HTML representation of the document.
The encoding parameter specifies the value for the charset attribute in the html header. For example if 'utf-8' is specified then the beginning of the generated html will look like this:
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"></head><body>...
If no encoding is specified then no such meta information is generated.
If you later on convert the returned html string into a byte array for transmission over a network or when saving to disk you should specify the encoding you're going to use for the conversion to a byte array here.
See also
{Supported HTML Subset}
Definition at line 3210 of file qtextdocument.cpp.
Referenced by QTextEdit::toHtml(), and QTextDocumentWriter::write().
 {
     return QTextHtmlExporter(this).toHtml(encoding);
 }
toPlainText()
QString QTextDocument::toPlainText () const
Returns the plain text contained in the document.
If you want formatting information use a QTextCursor instead.
See also
toHtml()
Definition at line 1277 of file qtextdocument.cpp.
Referenced by handleStringAttribute(), QAccessibleDisplay::text(), QTextDocumentFragment::toPlainText(), QTextEdit::toPlainText(), and QTextDocumentWriter::write().
 {
     Q_D(const QTextDocument);
     QString txt = d->plainText();
     QChar *uc = txt.data();
     QChar *e = uc + txt.size();
     for (; uc != e; ++uc) {
         switch (uc->unicode()) {
         case 0xfdd0: // QTextBeginningOfFrame
         case 0xfdd1: // QTextEndOfFrame
         case QChar::ParagraphSeparator:
         case QChar::LineSeparator:
             *uc = QLatin1Char('\n');
             break;
         case QChar::Nbsp:
             *uc = QLatin1Char(' ');
             break;
         default:
             ;
         }
     }
     return txt;
 }
undo() [1/2]
void QTextDocument::undo (QTextCursor * cursor)
Undoes the last editing operation on the document if undo is available.
Since
4.2
The provided cursor is positioned at the end of the location where the edition operation was undone.
See the Overview of Qt's Undo Framework documentation for details.
See also
undoAvailable(), isUndoRedoEnabled()
Definition at line 441 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     const int pos = d->undoRedo(true);
     if (cursor && pos >= 0) {
         *cursor = QTextCursor(this);
         cursor->setPosition(pos);
     }
 }
undo [2/2]
void QTextDocument::undo () slot
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 503 of file qtextdocument.cpp.
 {
     Q_D(QTextDocument);
     d->undoRedo(true);
 }
undoAvailable
QTextDocument::undoAvailable (bool available) signal
This signal is emitted whenever undo operations become available (available is true) or unavailable (available is false).
See the Overview of Qt's Undo Framework documentation for details.
See also
undo(), isUndoRedoEnabled()
undoCommandAdded
QTextDocument::undoCommandAdded () signal
This signal is emitted every time a new level of undo is added to the QTextDocument.
Since
4.4
Referenced by QTextDocumentPrivate::appendUndoItem(), and QTextDocumentPrivate::endEditBlock().
useDesignMetrics()
bool QTextDocument::useDesignMetrics () const
Referenced by setUseDesignMetrics().
Friends and Related Functions
QTextObjectPrivate
friend class QTextObjectPrivate friend
Definition at line 303 of file qtextdocument.h.
Properties
blockCount
int QTextDocument::blockCount private
Returns the number of text blocks in the document.
Since
4.2
The value of this property is undefined in documents with tables or frames.
By default, if defined, this property contains a value of 1.
See also
lineCount(), characterCount()
Definition at line 120 of file qtextdocument.h.
Referenced by QPlainTextEditPrivate::append(), QPlainTextEdit::blockBoundingRect(), QAccessibleTextEdit::childCount(), and QPlainTextDocumentLayout::documentChanged().
defaultFont
QFont QTextDocument::defaultFont private
the default font used to display the document's text
Returns the default font to be used in the document layout.
Definition at line 116 of file qtextdocument.h.
Referenced by QGraphicsTextItem::font(), QTextControl::print(), printPage(), and QTextHtmlExporter::QTextHtmlExporter().
defaultStyleSheet
QString QTextDocument::defaultStyleSheet private
The default style sheet is applied to all newly HTML formatted text that is inserted into the document, for example using setHtml() or QTextCursor::insertHtml().
Since
4.2
The style sheet needs to be compliant to CSS 2.1 syntax.
Note: Changing the default style sheet does not have any effect to the existing content of the document.
See also
{Supported HTML Subset}
Definition at line 123 of file qtextdocument.h.
documentMargin
qreal QTextDocument::documentMargin private
The margin around the document.
Since
4.5
The default is 4.
Definition at line 126 of file qtextdocument.h.
Referenced by QPlainTextEditPrivate::_q_adjustScrollbars(), QPlainTextDocumentLayout::blockBoundingRect(), QPlainTextDocumentLayout::documentChanged(), QPlainTextDocumentLayout::layoutBlock(), QPlainTextEdit::paintEvent(), QTextHtmlExporter::toHtml(), and QPlainTextEditPrivate::verticalOffset().
indentWidth
qreal QTextDocument::indentWidth private
Returns the width used for text list and text block indenting.
Since
4.4
The indent properties of QTextListFormat and QTextBlockFormat specify multiples of this value. The default indent width is 40.
Definition at line 121 of file qtextdocument.h.
Referenced by QTextDocumentLayoutPrivate::blockIndent().
maximumBlockCount
int QTextDocument::maximumBlockCount private
Specifies the limit for blocks in the document.
Since
4.2
Specifies the maximum number of blocks the document may have. If there are more blocks in the document that specified with this property blocks are removed from the beginning of the document.
A negative or zero value specifies that the document may contain an unlimited amount of blocks.
The default value is 0.
Note that setting this property will apply the limit immediately to the document contents.
Setting this property also disables the undo redo history.
This property is undefined in documents with tables or frames.
Definition at line 125 of file qtextdocument.h.
Referenced by QPlainTextEditPrivate::append().
modified
QTextDocument::modified private
whether the document has been modified by the user
By default, this property is false.
See also
modificationChanged()
Definition at line 114 of file qtextdocument.h.
pageSize
QSizeF QTextDocument::pageSize private
the page size that should be used for laying out the document
By default, for a newly-created, empty document, this property contains an undefined size.
See also
modificationChanged()
Definition at line 115 of file qtextdocument.h.
Referenced by QGraphicsTextItemPrivate::controlOffset(), QTextDocumentLayoutPrivate::drawBlock(), QTextDocumentLayoutPrivate::drawBorder(), QTextDocumentLayoutPrivate::drawFrame(), QTextDocumentLayoutPrivate::drawListItem(), QTextDocumentLayoutPrivate::layoutBlock(), QTextDocumentLayoutPrivate::layoutCell(), QTextDocumentLayoutPrivate::layoutFlow(), QTextDocumentLayoutPrivate::layoutFrame(), QTextDocumentLayoutPrivate::layoutTable(), QTextControl::print(), and QTextEdit::resizeEvent().
size
QSizeF QTextDocument::size private
Returns the actual size of the document.
Since
4.2
This is equivalent to documentLayout()->documentSize();
The size of the document can be changed either by setting a text width or setting an entire page size.
Note that the width is always >= pageSize().width().
By default, for a newly-created, empty document, this property contains a configuration-dependent size.
See also
setTextWidth(), setPageSize(), idealWidth()
Definition at line 118 of file qtextdocument.h.
Referenced by QStaticTextPrivate::paintText(), and QWhatsThat::QWhatsThat().
textWidth
qreal QTextDocument::textWidth private
The text width specifies the preferred width for text in the document.
Since
4.2
If the text (or content in general) is wider than the specified with it is broken into multiple lines and grows vertically. If the text cannot be broken into multiple lines to fit into the specified text width it will be larger and the size() and the idealWidth() property will reflect that.
If the text width is set to -1 then the text will not be broken into multiple lines unless it is enforced through an explicit line break or a new paragraph.
The default value is -1.
Setting the text width will also set the page height to -1, causing the document to grow or shrink vertically in a continuous way. If you want the document layout to break the text into multiple pages then you have to set the pageSize property instead.
See also
size(), idealWidth(), pageSize()
Definition at line 119 of file qtextdocument.h.
undoRedoEnabled
QTextDocument::undoRedoEnabled private
whether undo/redo are enabled for this document
This defaults to true. If disabled, the undo stack is cleared and no items will be added to it.
Definition at line 113 of file qtextdocument.h.
useDesignMetrics
bool QTextDocument::useDesignMetrics private
whether the document uses design metrics of fonts to improve the accuracy of text layout
Since
4.1
If this property is set to true, the layout will use design metrics. Otherwise, the metrics of the paint device as set on QAbstractTextDocumentLayout::setPaintDevice() will be used.
Using design metrics makes a layout have a width that is no longer dependent on hinting and pixel-rounding. This means that WYSIWYG text layout becomes possible because the width scales much more linearly based on paintdevice metrics than it would otherwise.
By default, this property is false.
Definition at line 117 of file qtextdocument.h.
Referenced by QTextControl::print().
The documentation for this class was generated from the following files:
/src/gui/text/qtextdocument.h
/src/gui/text/qtextdocument.cpp