Qt 4.8: QNetworkManagerSettingsConnection Class Reference
QNetworkManagerSettingsConnection Class Reference
#include <qnetworkmanagerservice.h>
Signals
void removed (const QString &path)
void updated (const QNmSettingsMap &settings)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDBusInterface * connectionInterface () const
QString getId ()
QString getMacAddress ()
QStringList getSeenBssids ()
QNmSettingsMap getSettings ()
QString getSsid ()
quint64 getTimestamp ()
NMDeviceType getType ()
QString getUuid ()
bool isAutoConnect ()
bool isValid ()
QNetworkManagerSettingsConnection (const QString &settingsService, const QString &connectionObjectPath, QObject *parent=0)
bool setConnections ()
~QNetworkManagerSettingsConnection ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QNetworkManagerSettingsConnectionPrivate * d
QNmDBusHelper * nmDBusHelper
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 362 of file qnetworkmanagerservice.h.
Constructors and Destructors
QNetworkManagerSettingsConnection()
QNetworkManagerSettingsConnection::QNetworkManagerSettingsConnection (const QString & settingsService, const QString & connectionObjectPath, QObject * parent = 0)
Definition at line 648 of file qnetworkmanagerservice.cpp.
     : QObject(parent), nmDBusHelper(0)
 {
     qDBusRegisterMetaType<QNmSettingsMap>();
     d = new QNetworkManagerSettingsConnectionPrivate();
     d->path = connectionObjectPath;
     d->service = settingsService;
     d->connectionInterface = new QDBusInterface(settingsService,
                                                 d->path,
                                                 QLatin1String(NM_DBUS_IFACE_SETTINGS_CONNECTION),
                                                 dbusConnection, parent);
     if (!d->connectionInterface->isValid()) {
         d->valid = false;
         return;
     }
     d->valid = true;
     QDBusReply< QNmSettingsMap > rep = d->connectionInterface->call(QLatin1String("GetSettings"));
     d->settingsMap = rep.value();
 }
~QNetworkManagerSettingsConnection()
QNetworkManagerSettingsConnection::~QNetworkManagerSettingsConnection ()
Definition at line 668 of file qnetworkmanagerservice.cpp.
 {
     delete d->connectionInterface;
     delete d;
 }
Functions
connectionInterface()
QDBusInterface * QNetworkManagerSettingsConnection::connectionInterface () const
Definition at line 707 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::connectionFromId(), QNetworkManagerEngine::connectToId(), QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::newConnection(), QNetworkManagerEngine::removeAccessPoint(), QNetworkManagerEngine::removeConnection(), QNetworkManagerEngine::updateAccessPoint(), and QNetworkManagerEngine::updateConnection().
 {
     return d->connectionInterface;
 }
getId()
QString QNetworkManagerSettingsConnection::getId ()
Definition at line 750 of file qnetworkmanagerservice.cpp.
 {
     return d->settingsMap.value(QLatin1String("connection")).value(QLatin1String("id")).toString();
 }
getMacAddress()
QString QNetworkManagerSettingsConnection::getMacAddress ()
Definition at line 770 of file qnetworkmanagerservice.cpp.
 {
     NMDeviceType type = getType();
     if (type == DEVICE_TYPE_802_3_ETHERNET) {
         return d->settingsMap.value(QLatin1String("802-3-ethernet"))
                              .value(QLatin1String("mac-address")).toString();
     } else if (type == DEVICE_TYPE_802_11_WIRELESS) {
         return d->settingsMap.value(QLatin1String("802-11-wireless"))
                              .value(QLatin1String("mac-address")).toString();
     } else {
         return QString();
     }
 }
getSeenBssids()
QStringList QNetworkManagerSettingsConnection::getSeenBssids ()
Definition at line 785 of file qnetworkmanagerservice.cpp.
 {
     if (getType() == DEVICE_TYPE_802_11_WIRELESS) {
         return d->settingsMap.value(QLatin1String("802-11-wireless"))
                              .value(QLatin1String("seen-bssids")).toStringList();
     } else {
         return QStringList();
     }
 }
getSettings()
QNmSettingsMap QNetworkManagerSettingsConnection::getSettings ()
Definition at line 712 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::connectToId(), and QNetworkManagerEngine::newConnection().
 {
     QDBusReply< QNmSettingsMap > rep = d->connectionInterface->call(QLatin1String("GetSettings"));
     d->settingsMap = rep.value();
     return d->settingsMap;
 }
getSsid()
QString QNetworkManagerSettingsConnection::getSsid ()
Definition at line 764 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::newAccessPoint(), QNetworkManagerEngine::removeAccessPoint(), and QNetworkManagerEngine::updateAccessPoint().
 {
     return d->settingsMap.value(QLatin1String("802-11-wireless"))
                          .value(QLatin1String("ssid")).toString();
 }
getTimestamp()
quint64 QNetworkManagerSettingsConnection::getTimestamp ()
Definition at line 744 of file qnetworkmanagerservice.cpp.
Referenced by QNetworkManagerEngine::startTime().
 {
     return d->settingsMap.value(QLatin1String("connection"))
                          .value(QLatin1String("timestamp")).toUInt();
 }
getType()
NMDeviceType QNetworkManagerSettingsConnection::getType ()
Definition at line 719 of file qnetworkmanagerservice.cpp.
Referenced by getMacAddress(), and getSeenBssids().
 {
     const QString devType =
         d->settingsMap.value(QLatin1String("connection")).value(QLatin1String("type")).toString();
     if (devType == QLatin1String("802-3-ethernet"))
         return DEVICE_TYPE_802_3_ETHERNET;
     else if (devType == QLatin1String("802-11-wireless"))
         return DEVICE_TYPE_802_11_WIRELESS;
     else
         return DEVICE_TYPE_UNKNOWN;
 }
getUuid()
QString QNetworkManagerSettingsConnection::getUuid ()
Definition at line 755 of file qnetworkmanagerservice.cpp.
 {
     const QString id = d->settingsMap.value(QLatin1String("connection"))
                                      .value(QLatin1String("uuid")).toString();
     // is no uuid, return the connection path
     return id.isEmpty() ? d->connectionInterface->path() : id;
 }
isAutoConnect()
bool QNetworkManagerSettingsConnection::isAutoConnect ()
Definition at line 732 of file qnetworkmanagerservice.cpp.
 {
     const QVariant autoConnect =
         d->settingsMap.value(QLatin1String("connection")).value(QLatin1String("autoconnect"));
     // NetworkManager default is to auto connect
     if (!autoConnect.isValid())
         return true;
     return autoConnect.toBool();
 }
isValid()
bool QNetworkManagerSettingsConnection::isValid ()
Definition at line 674 of file qnetworkmanagerservice.cpp.
Referenced by setConnections().
 {
     return d->valid;
 }
removed
void QNetworkManagerSettingsConnection::removed (const QString & path) signal
Referenced by setConnections().
setConnections()
bool QNetworkManagerSettingsConnection::setConnections ()
Definition at line 679 of file qnetworkmanagerservice.cpp.
 {
     if(!isValid() )
         return false;
     bool allOk = false;
     if(!dbusConnection.connect(d->service, d->path,
                            QLatin1String(NM_DBUS_IFACE_SETTINGS_CONNECTION), QLatin1String("Updated"),
                            this, SIGNAL(updated(QNmSettingsMap)))) {
         allOk = true;
     } else {
         QDBusError error = dbusConnection.lastError();
     }
     delete nmDBusHelper;
     nmDBusHelper = new QNmDBusHelper(this);
     connect(nmDBusHelper, SIGNAL(pathForSettingsRemoved(const QString &)),
             this,SIGNAL(removed( const QString &)));
     if (!dbusConnection.connect(d->service, d->path,
                            QLatin1String(NM_DBUS_IFACE_SETTINGS_CONNECTION), QLatin1String("Removed"),
                            nmDBusHelper, SIGNAL(slotSettingsRemoved()))) {
         allOk = true;
     }
     return allOk;
 }
updated
void QNetworkManagerSettingsConnection::updated (const QNmSettingsMap & settings) signal
Referenced by setConnections().
Properties
d
QNetworkManagerSettingsConnectionPrivate* QNetworkManagerSettingsConnection::d private
Definition at line 391 of file qnetworkmanagerservice.h.
Referenced by connectionInterface(), getId(), getMacAddress(), getSeenBssids(), getSettings(), getSsid(), getTimestamp(), getType(), getUuid(), isAutoConnect(), isValid(), QNetworkManagerSettingsConnection(), setConnections(), and ~QNetworkManagerSettingsConnection().
nmDBusHelper
QNmDBusHelper* QNetworkManagerSettingsConnection::nmDBusHelper private
Definition at line 390 of file qnetworkmanagerservice.h.
Referenced by setConnections().
The documentation for this class was generated from the following files:
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.h
/src/plugins/bearer/networkmanager/qnetworkmanagerservice.cpp