Qt 4.8: QDeclarativeXmlListModel Class Reference
QDeclarativeXmlListModel Class Reference
#include <qdeclarativexmllistmodel_p.h>
Public Types
enum Status { Null, Ready, Loading, Error }
Public Slots
void reload ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void countChanged ()
void namespaceDeclarationsChanged ()
void progressChanged (qreal progress)
void queryChanged ()
void sourceChanged ()
void statusChanged (QDeclarativeXmlListModel::Status)
void xmlChanged ()
Signals inherited from QListModelInterface
void itemsChanged (int index, int count, const QList< int > &roles)
Emit this signal when count items at index have had their roles changed.
void itemsInserted (int index, int count)
Emit this signal when count items are inserted at index.
void itemsMoved (int from, int to, int count)
Emit this signal when count items are moved from index from to index to.
void itemsRemoved (int index, int count)
Emit this signal when count items are removed at index.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void classBegin ()
Invoked after class creation, but before any properties have been set.
virtual void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
virtual int count () const
Returns the number of data entries in the model.
virtual QHash< int, QVariant > data (int index, const QList< int > &roles=(QList< int >())) const
virtual QVariant data (int index, int role) const
Returns the data at the given index for the specified roles.
Q_INVOKABLE QString errorString () const
Q_INVOKABLE QScriptValue get (int index) const
QString namespaceDeclarations () const
qreal progress () const
QDeclarativeXmlListModel (QObject *parent=0)
QString query () const
QDeclarativeListProperty< QDeclarativeXmlListModelRole > roleObjects ()
virtual QList< int > roles () const
Returns the list of roles for which the list model interface provides data.
void setNamespaceDeclarations (const QString &)
void setQuery (const QString &)
void setSource (const QUrl &)
void setXml (const QString &)
QUrl source () const
Status status () const
virtual QString toString (int role) const
Returns a string description of the specified role.
QString xml () const
~QDeclarativeXmlListModel ()
Public Functions inherited from QListModelInterface
QListModelInterface (QObject *parent=0)
Constructs a QListModelInterface with the specified parent.
virtual ~QListModelInterface ()
The destructor is virtual.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Private Slots
void dataCleared ()
void queryCompleted (const QDeclarativeXmlQueryResult &)
void queryError (void *object, const QString &error)
void requestFinished ()
void requestProgress (qint64, qint64)
Properties
int count
QString namespaceDeclarations
qreal progress
QString query
QDeclarativeListProperty< QDeclarativeXmlListModelRole > roles
QUrl source
Status status
QString xml
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QListModelInterface
QListModelInterface (QObjectPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 73 of file qdeclarativexmllistmodel_p.h.
Enumerations
Status
enum QDeclarativeXmlListModel::Status
Enumerator
Null
Ready
Loading
Error
Definition at line 115 of file qdeclarativexmllistmodel_p.h.
 { Null, Ready, Loading, Error };
Constructors and Destructors
QDeclarativeXmlListModel()
QDeclarativeXmlListModel::QDeclarativeXmlListModel (QObject * parent = 0)
Definition at line 712 of file qdeclarativexmllistmodel.cpp.
     : QListModelInterface(*(new QDeclarativeXmlListModelPrivate), parent)
 {
 }
~QDeclarativeXmlListModel()
QDeclarativeXmlListModel::~QDeclarativeXmlListModel ()
Definition at line 717 of file qdeclarativexmllistmodel.cpp.
 {
 }
Functions
classBegin()
void QDeclarativeXmlListModel::classBegin () virtual
Invoked after class creation, but before any properties have been set.
Implements QDeclarativeParserStatus.
Definition at line 1006 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(QDeclarativeXmlListModel);
     d->isComponentComplete = false;
     QDeclarativeXmlQueryEngine *queryEngine = QDeclarativeXmlQueryEngine::instance(qmlEngine(this));
     connect(queryEngine, SIGNAL(queryCompleted(QDeclarativeXmlQueryResult)),
             SLOT(queryCompleted(QDeclarativeXmlQueryResult)));
     connect(queryEngine, SIGNAL(error(void*,QString)),
             SLOT(queryError(void*,QString)));
 }
componentComplete()
void QDeclarativeXmlListModel::componentComplete () virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 1018 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(QDeclarativeXmlListModel);
     d->isComponentComplete = true;
     reload();
 }
count()
virtual int QDeclarativeXmlListModel::count () const virtual
Returns the number of data entries in the model.
Implements QListModelInterface.
Referenced by data(), dataCleared(), get(), and requestFinished().
countChanged
void QDeclarativeXmlListModel::countChanged () signal
Referenced by queryCompleted(), and requestFinished().
data() [1/2]
QHash< int, QVariant > QDeclarativeXmlListModel::data (int index, const QList< int > & roles = (QList<int>())) const virtual
Definition at line 738 of file qdeclarativexmllistmodel.cpp.
Referenced by requestFinished().
 {
     Q_D(const QDeclarativeXmlListModel);
     QHash<int, QVariant> rv;
     for (int i = 0; i < roles.size(); ++i) {
         int role = roles.at(i);
         int roleIndex = d->roles.indexOf(role);
         rv.insert(role, roleIndex == -1 ? QVariant() : d->data.value(roleIndex).value(index));
     }
     return rv;
 }
data() [2/2]
QVariant QDeclarativeXmlListModel::data (int index, int role) const virtual
Returns the data at the given index for the specified roles.
Implements QListModelInterface.
Definition at line 750 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(const QDeclarativeXmlListModel);
     int roleIndex = d->roles.indexOf(role);
     return (roleIndex == -1) ? QVariant() : d->data.value(roleIndex).value(index);
 }
dataCleared
void QDeclarativeXmlListModel::dataCleared () private slot
Definition at line 1136 of file qdeclarativexmllistmodel.cpp.
Referenced by reload(), and requestFinished().
 {
     Q_D(QDeclarativeXmlListModel);
     QDeclarativeXmlQueryResult r;
     r.queryId = XMLLISTMODEL_CLEAR_ID;
     r.size = 0;
     r.removed << qMakePair(0, count());
     r.keyRoleResultsCache = d->keyRoleResultsCache;
     queryCompleted(r);
 }
errorString()
QString QDeclarativeXmlListModel::errorString () const
Definition at line 1000 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(const QDeclarativeXmlListModel);
     return d->errorString;
 }
get()
QScriptValue QDeclarativeXmlListModel::get (int index) const
Definition at line 929 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(const QDeclarativeXmlListModel);
     QScriptEngine *sengine = QDeclarativeEnginePrivate::getScriptEngine(qmlContext(this)->engine());
     if (index < 0 || index >= count())
         return sengine->undefinedValue();
     QScriptValue sv = sengine->newObject();
     for (int i=0; i<d->roleObjects.count(); i++)
         sv.setProperty(d->roleObjects[i]->name(), sengine->toScriptValue(d->data.value(i).value(index)));
     return sv;
 }
namespaceDeclarations()
QString QDeclarativeXmlListModel::namespaceDeclarations () const
Referenced by setQuery().
namespaceDeclarationsChanged
void QDeclarativeXmlListModel::namespaceDeclarationsChanged () signal
Referenced by setNamespaceDeclarations().
progress()
qreal QDeclarativeXmlListModel::progress () const
Referenced by get().
progressChanged
void QDeclarativeXmlListModel::progressChanged (qreal progress) signal
Referenced by requestFinished(), and requestProgress().
query()
QString QDeclarativeXmlListModel::query () const
Referenced by setQuery(), and setXml().
queryChanged
void QDeclarativeXmlListModel::queryChanged () signal
Referenced by setQuery().
queryCompleted
void QDeclarativeXmlListModel::queryCompleted (const QDeclarativeXmlQueryResult & result) private slot
Definition at line 1160 of file qdeclarativexmllistmodel.cpp.
Referenced by classBegin(), and dataCleared().
 {
     Q_D(QDeclarativeXmlListModel);
     if (result.queryId != d->queryId)
         return;
     int origCount = d->size;
     bool sizeChanged = result.size != d->size;
     d->size = result.size;
     d->data = result.data;
     d->keyRoleResultsCache = result.keyRoleResultsCache;
     d->status = Ready;
     d->errorString.clear();
     d->queryId = -1;
     bool hasKeys = false;
     for (int i=0; i<d->roleObjects.count(); i++) {
         if (d->roleObjects[i]->isKey()) {
             hasKeys = true;
             break;
         }
     }
     if (!hasKeys) {
         if (!(origCount == 0 && d->size == 0)) {
             emit itemsRemoved(0, origCount);
             emit itemsInserted(0, d->size);
             emit countChanged();
         }
     } else {
         for (int i=0; i<result.removed.count(); i++)
             emit itemsRemoved(result.removed[i].first, result.removed[i].second);
         for (int i=0; i<result.inserted.count(); i++)
             emit itemsInserted(result.inserted[i].first, result.inserted[i].second);
         if (sizeChanged)
             emit countChanged();
     }
     emit statusChanged(d->status);
 }
queryError
void QDeclarativeXmlListModel::queryError (void * object, const QString & error) private slot
Definition at line 1147 of file qdeclarativexmllistmodel.cpp.
Referenced by classBegin().
 {
     // Be extra careful, object may no longer exist, it's just an ID.
     Q_D(QDeclarativeXmlListModel);
     for (int i=0; i<d->roleObjects.count(); i++) {
         if (d->roleObjects.at(i) == static_cast<QDeclarativeXmlListModelRole*>(object)) {
             qmlInfo(d->roleObjects.at(i)) << QObject::tr("invalid query: \"%1\"").arg(error);
             return;
         }
     }
     qmlInfo(this) << QObject::tr("invalid query: \"%1\"").arg(error);
 }
reload
void QDeclarativeXmlListModel::reload () slot
Definition at line 1041 of file qdeclarativexmllistmodel.cpp.
Referenced by componentComplete(), setNamespaceDeclarations(), setQuery(), setSource(), and setXml().
 {
     Q_D(QDeclarativeXmlListModel);
     if (!d->isComponentComplete)
         return;
     QDeclarativeXmlQueryEngine::instance(qmlEngine(this))->abort(d->queryId);
     d->queryId = -1;
     if (d->size < 0)
         d->size = 0;
     if (d->reply) {
         d->reply->abort();
         d->deleteReply();
     }
     if (!d->xml.isEmpty()) {
         d->queryId = QDeclarativeXmlQueryEngine::instance(qmlEngine(this))->doQuery(d->query, d->namespaces, d->xml.toUtf8(), &d->roleObjects, d->keyRoleResultsCache);
         d->notifyQueryStarted(false);
     } else if (d->src.isEmpty()) {
         d->queryId = XMLLISTMODEL_CLEAR_ID;
         d->notifyQueryStarted(false);
         QTimer::singleShot(0, this, SLOT(dataCleared()));
     } else {
         d->notifyQueryStarted(true);
         QNetworkRequest req(d->src);
         req.setRawHeader("Accept", "application/xml,*/*");
         d->reply = qmlContext(this)->engine()->networkAccessManager()->get(req);
         QObject::connect(d->reply, SIGNAL(finished()), this, SLOT(requestFinished()));
         QObject::connect(d->reply, SIGNAL(downloadProgress(qint64,qint64)),
                          this, SLOT(requestProgress(qint64,qint64)));
     }
 }
requestFinished
void QDeclarativeXmlListModel::requestFinished () private slot
Definition at line 1081 of file qdeclarativexmllistmodel.cpp.
Referenced by reload().
 {
     Q_D(QDeclarativeXmlListModel);
     d->redirectCount++;
     if (d->redirectCount < XMLLISTMODEL_MAX_REDIRECT) {
         QVariant redirect = d->reply->attribute(QNetworkRequest::RedirectionTargetAttribute);
         if (redirect.isValid()) {
             QUrl url = d->reply->url().resolved(redirect.toUrl());
             d->deleteReply();
             setSource(url);
             return;
         }
     }
     d->redirectCount = 0;
     if (d->reply->error() != QNetworkReply::NoError) {
         d->errorString = d->reply->errorString();
         d->deleteReply();
         int count = this->count();
         d->data.clear();
         d->size = 0;
         if (count > 0) {
             emit itemsRemoved(0, count);
             emit countChanged();
         }
         d->status = Error;
         d->queryId = -1;
         emit statusChanged(d->status);
     } else {
         QByteArray data = d->reply->readAll();
         if (data.isEmpty()) {
             d->queryId = XMLLISTMODEL_CLEAR_ID;
             QTimer::singleShot(0, this, SLOT(dataCleared()));
         } else {
             d->queryId = QDeclarativeXmlQueryEngine::instance(qmlEngine(this))->doQuery(d->query, d->namespaces, data, &d->roleObjects, d->keyRoleResultsCache);
         }
         d->deleteReply();
         d->progress = 1.0;
         emit progressChanged(d->progress);
     }
 }
requestProgress
void QDeclarativeXmlListModel::requestProgress (qint64 received, qint64 total) private slot
Definition at line 1127 of file qdeclarativexmllistmodel.cpp.
Referenced by reload().
 {
     Q_D(QDeclarativeXmlListModel);
     if (d->status == Loading && total > 0) {
         d->progress = qreal(received)/total;
         emit progressChanged(d->progress);
     }
 }
roleObjects()
QDeclarativeListProperty< QDeclarativeXmlListModelRole > QDeclarativeXmlListModel::roleObjects ()
Definition at line 729 of file qdeclarativexmllistmodel.cpp.
Referenced by QDeclarativeXmlListModelPrivate::append_role(), and QDeclarativeXmlListModelPrivate::clear_role().
 {
     Q_D(QDeclarativeXmlListModel);
     QDeclarativeListProperty<QDeclarativeXmlListModelRole> list(this, d->roleObjects);
     list.append = &QDeclarativeXmlListModelPrivate::append_role;
     list.clear = &QDeclarativeXmlListModelPrivate::clear_role;
     return list;
 }
roles()
virtual QList<int> QDeclarativeXmlListModel::roles () const virtual
Returns the list of roles for which the list model interface provides data.
Implements QListModelInterface.
Referenced by data().
setNamespaceDeclarations()
void QDeclarativeXmlListModel::setNamespaceDeclarations (const QString & declarations)
Definition at line 894 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(QDeclarativeXmlListModel);
     if (d->namespaces != declarations) {
         d->namespaces = declarations;
         reload();
         emit namespaceDeclarationsChanged();
     }
 }
setQuery()
void QDeclarativeXmlListModel::setQuery (const QString & query)
Definition at line 852 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(QDeclarativeXmlListModel);
     if (!query.startsWith(QLatin1Char('/'))) {
         qmlInfo(this) << QCoreApplication::translate("QDeclarativeXmlRoleList", "An XmlListModel query must start with '/' or \"//\"");
         return;
     }
     if (d->query != query) {
         d->query = query;
         reload();
         emit queryChanged();
     }
 }
setSource()
void QDeclarativeXmlListModel::setSource (const QUrl & src)
Definition at line 800 of file qdeclarativexmllistmodel.cpp.
Referenced by requestFinished().
 {
     Q_D(QDeclarativeXmlListModel);
     if (d->src != src) {
         d->src = src;
         if (d->xml.isEmpty())   // src is only used if d->xml is not set
             reload();
         emit sourceChanged();
    }
 }
setXml()
void QDeclarativeXmlListModel::setXml (const QString & xml)
Definition at line 828 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(QDeclarativeXmlListModel);
     if (d->xml != xml) {
         d->xml = xml;
         reload();
         emit xmlChanged();
     }
 }
source()
QUrl QDeclarativeXmlListModel::source () const
Referenced by toString().
sourceChanged
void QDeclarativeXmlListModel::sourceChanged () signal
Referenced by setSource().
status()
Status QDeclarativeXmlListModel::status () const
Referenced by get().
statusChanged
void QDeclarativeXmlListModel::statusChanged (QDeclarativeXmlListModel::Status) signal
Referenced by queryCompleted(), and requestFinished().
toString()
QString QDeclarativeXmlListModel::toString (int role) const virtual
Returns a string description of the specified role.
Implements QListModelInterface.
Definition at line 776 of file qdeclarativexmllistmodel.cpp.
 {
     Q_D(const QDeclarativeXmlListModel);
     int index = d->roles.indexOf(role);
     if (index == -1)
         return QString();
     return d->roleNames.at(index);
 }
xml()
QString QDeclarativeXmlListModel::xml () const
Referenced by setSource(), and setXml().
xmlChanged
void QDeclarativeXmlListModel::xmlChanged () signal
Referenced by setXml().
Properties
count
int QDeclarativeXmlListModel::count private
Definition at line 86 of file qdeclarativexmllistmodel_p.h.
namespaceDeclarations
QString QDeclarativeXmlListModel::namespaceDeclarations private
Definition at line 84 of file qdeclarativexmllistmodel_p.h.
progress
qreal QDeclarativeXmlListModel::progress private
Definition at line 80 of file qdeclarativexmllistmodel_p.h.
query
QString QDeclarativeXmlListModel::query private
Definition at line 83 of file qdeclarativexmllistmodel_p.h.
roles
QList< int > QDeclarativeXmlListModel::roles private
Definition at line 85 of file qdeclarativexmllistmodel_p.h.
Referenced by QDeclarativeXmlListModelPrivate::append_role(), and QDeclarativeXmlListModelPrivate::clear_role().
source
QUrl QDeclarativeXmlListModel::source private
Definition at line 81 of file qdeclarativexmllistmodel_p.h.
status
QDeclarativeXmlListModel::Status QDeclarativeXmlListModel::status private
Definition at line 79 of file qdeclarativexmllistmodel_p.h.
xml
QString QDeclarativeXmlListModel::xml private
Definition at line 82 of file qdeclarativexmllistmodel_p.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativexmllistmodel_p.h
/src/declarative/util/qdeclarativexmllistmodel.cpp