Qt 4.8: QPatternist::Duration Class Reference
QPatternist::Duration Class Reference
Implements the value instance of the xs:duration type.
#include <qduration_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AbstractDuration
typedef QExplicitlySharedDataPointer< AbstractDuration > Ptr
typedef qint64 Value
The amount in milli seconds.
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual DayCountProperty days () const
virtual Item fromValue (const Value val) const
virtual HourProperty hours () const
virtual MinuteProperty minutes () const
virtual MonthProperty months () const
virtual MSecondProperty mseconds () const
virtual SecondProperty seconds () const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
virtual Value value () const
virtual YearProperty years () const
Public Functions inherited from QPatternist::AbstractDuration
bool isPositive () const
bool operator== (const AbstractDuration &other) const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static Duration::Ptr fromComponents (const bool isPositive, const YearProperty years, const MonthProperty months, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds)
static Duration::Ptr fromLexical (const QString &string)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
Duration (const bool isPositive, const YearProperty years, const MonthProperty months, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds)
Protected Functions inherited from QPatternist::AbstractDuration
AbstractDuration (const bool isPos)
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Properties
const DayCountProperty m_days
const HourProperty m_hours
const MinuteProperty m_minutes
const MonthProperty m_months
const MSecondProperty m_mseconds
const SecondProperty m_seconds
const YearProperty m_years
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::AbstractDuration
static AtomicValue::Ptr create (const CaptureTable &captTable, const QString &lexical, bool *isPositive, YearProperty *years, MonthProperty *months, DayCountProperty *days, HourProperty *hours, MinuteProperty *minutes, SecondProperty *seconds, MSecondProperty *mseconds)
static QString serializeMSeconds (const MSecondProperty mseconds)
Protected Variables inherited from QPatternist::AbstractDuration
const bool m_isPositive
Detailed Description
Implements the value instance of the xs:duration type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 69 of file qduration_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::Duration::Ptr
Definition at line 72 of file qduration_p.h.
Constructors and Destructors
Duration()
Duration::Duration (const bool isPositive, const YearProperty years, const MonthProperty months, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds) protected
Definition at line 52 of file qduration.cpp.
Referenced by fromComponents(), and fromLexical().
                                                 : AbstractDuration(isPositiveP),
                                                   m_years(yearsP),
                                                   m_months(monthsP),
                                                   m_days(daysP),
                                                   m_hours(hoursP),
                                                   m_minutes(mins),
                                                   m_seconds(secs),
                                                   m_mseconds(msecs)
 {
 }
Functions
days()
DayCountProperty Duration::days () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 214 of file qduration.cpp.
Referenced by fromLexical().
 {
     return m_days;
 }
fromComponents()
Duration::Ptr Duration::fromComponents (const bool isPositive, const YearProperty years, const MonthProperty months, const DayCountProperty days, const HourProperty hours, const MinuteProperty minutes, const SecondProperty seconds, const MSecondProperty mseconds) static
Definition at line 113 of file qduration.cpp.
Referenced by QPatternist::AbstractDurationToDurationCaster::castFrom().
 {
     return Duration::Ptr(new Duration(isPositive, years, months, days,
                                       hours, minutes, seconds, mseconds));
 }
fromLexical()
Duration::Ptr Duration::fromLexical (const QString & string) static
Creates an instance from the lexical representation string.
Definition at line 70 of file qduration.cpp.
Referenced by QPatternist::StringToDurationCaster::castFrom().
 {
     static const CaptureTable captureTable(
         /* The extra paranthesis is a build fix for GCC 3.3. */
         (QRegExp(QLatin1String(
                 "^\\s*"                         /* Any preceding whitespace. */
                 "(-)?"                          /* Any minus sign. */
                 "P"                             /* Delimiter. */
                 "(?:(\\d+)Y)?"                  /* Year part. */
                 "(?:(\\d+)M)?"                  /* Month part. */
                 "(?:(\\d+)D)?"                  /* Day part. */
                 "(?:"                           /* Here starts the optional time part. */
                 "(T)"                           /* SchemaTime delimiter. */
                 "(?:(\\d+)H)?"                  /* Hour part. */
                 "(?:(\\d+)M)?"                  /* Minute part. */
                 "(?:(\\d+)(?:\\.(\\d+))?S)?"    /* Seconds & milli seconds. */
                 ")?"                            /* End of optional time part. */
                 "\\s*$"                         /* Any terminating whitespace. */))),
         /*yearP*/       2,
         /*monthP*/      3,
         /*dayP*/        4,
         /*tDelimiterP*/ 5,
         /*hourP*/       6,
         /*minutesP*/    7,
         /*secondsP*/    8,
         /*msecondsP*/   9);
     YearProperty years = 0;
     MonthProperty months = 0;
     DayCountProperty days = 0;
     HourProperty hours = 0;
     MinuteProperty minutes = 0;
     SecondProperty sec = 0;
     MSecondProperty msec = 0;
     bool isPos;
     const AtomicValue::Ptr err(create(captureTable, lexical, &isPos, &years, &months,
                                       &days, &hours, &minutes, &sec, &msec));
     return err ? err : Duration::Ptr(new Duration(isPos, years, months, days, hours,
                                                   minutes, sec, msec));
 }
fromValue()
Item Duration::fromValue (const Value val) const virtual
Always results in an assert crash. Calling this function makes no sense due to that the value space of xs:duration is not well defined.
Implements QPatternist::AbstractDuration.
Definition at line 133 of file qduration.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "Calling Duration::fromValue() makes no sense");
     return Item();
 }
hours()
HourProperty Duration::hours () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 219 of file qduration.cpp.
Referenced by fromLexical().
 {
     return m_hours;
 }
minutes()
MinuteProperty Duration::minutes () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 224 of file qduration.cpp.
Referenced by fromLexical().
 {
     return m_minutes;
 }
months()
MonthProperty Duration::months () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 209 of file qduration.cpp.
Referenced by fromLexical().
 {
     return m_months;
 }
mseconds()
MSecondProperty Duration::mseconds () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 234 of file qduration.cpp.
 {
     return m_mseconds;
 }
seconds()
SecondProperty Duration::seconds () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 229 of file qduration.cpp.
 {
     return m_seconds;
 }
stringValue()
QString Duration::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 140 of file qduration.cpp.
 {
     QString retval;
     if(!m_isPositive)
         retval.append(QLatin1Char('-'));
     retval.append(QLatin1Char('P'));
     if(m_years)
     {
         retval.append(QString::number(m_years));
         retval.append(QLatin1Char('Y'));
     }
     if(m_months)
     {
         retval.append(QString::number(m_months));
         retval.append(QLatin1Char('M'));
     }
     if(m_days)
     {
         retval.append(QString::number(m_days));
         retval.append(QLatin1Char('D'));
     }
     if(!m_hours && !m_minutes && !m_seconds && !m_seconds)
     {
         if(!m_years && !m_months && !m_days)
             return QLatin1String("PT0S");
         else
             return retval;
     }
     retval.append(QLatin1Char('T'));
     if(m_hours)
     {
         retval.append(QString::number(m_hours));
         retval.append(QLatin1Char('H'));
     }
     if(m_minutes)
     {
         retval.append(QString::number(m_minutes));
         retval.append(QLatin1Char('M'));
     }
     if(m_seconds || m_seconds)
     {
         retval.append(QString::number(m_seconds));
         if(m_mseconds)
             retval.append(serializeMSeconds(m_mseconds));
         retval.append(QLatin1Char('S'));
     }
     else if(!m_years && !m_months && !m_days && !m_hours && !m_minutes)
         retval.append(QLatin1String("0S"));
     return retval;
 }
type()
ItemType::Ptr Duration::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 239 of file qduration.cpp.
 {
     return BuiltinTypes::xsDuration;
 }
value()
AbstractDuration::Value Duration::value () const virtual
Always results in an assert crash. Calling this function makes no sense due to that the value space of xs:duration is not well defined.
Implements QPatternist::AbstractDuration.
Definition at line 126 of file qduration.cpp.
 {
     Q_ASSERT_X(false, Q_FUNC_INFO,
                "Calling Duration::value() makes no sense");
     return 0;
 }
years()
YearProperty Duration::years () const virtual
Implements QPatternist::AbstractDuration.
Definition at line 204 of file qduration.cpp.
Referenced by fromLexical().
 {
     return m_years;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 111 of file qduration_p.h.
Properties
m_days
const DayCountProperty QPatternist::Duration::m_days private
Definition at line 124 of file qduration_p.h.
Referenced by days(), and stringValue().
m_hours
const HourProperty QPatternist::Duration::m_hours private
Definition at line 125 of file qduration_p.h.
Referenced by hours(), and stringValue().
m_minutes
const MinuteProperty QPatternist::Duration::m_minutes private
Definition at line 126 of file qduration_p.h.
Referenced by minutes(), and stringValue().
m_months
const MonthProperty QPatternist::Duration::m_months private
Definition at line 123 of file qduration_p.h.
Referenced by months(), and stringValue().
m_mseconds
const MSecondProperty QPatternist::Duration::m_mseconds private
Definition at line 128 of file qduration_p.h.
Referenced by mseconds(), and stringValue().
m_seconds
const SecondProperty QPatternist::Duration::m_seconds private
Definition at line 127 of file qduration_p.h.
Referenced by seconds(), and stringValue().
m_years
const YearProperty QPatternist::Duration::m_years private
Definition at line 122 of file qduration_p.h.
Referenced by stringValue(), and years().
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qduration_p.h
/src/xmlpatterns/data/qduration.cpp