Qt 4.8: QWorkspaceChild Class Reference
QWorkspaceChild Class Reference
Public Slots
void activate ()
void internalRaise ()
void showMaximized ()
void showMinimized ()
void showNormal ()
void showShaded ()
void titleBarDoubleClicked ()
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void popupOperationMenu (const QPoint &)
void showOperationMenu ()
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void adjustToFullscreen ()
QSize baseSize () const
void doMove ()
void doResize ()
int frameWidth () const
QWidget * iconWidget () const
bool isActive () const
bool isWindowOrIconVisible () const
QSize minimumSizeHint () const
QWorkspaceChild (QWidget *window, QWorkspace *parent=0, Qt::WindowFlags flags=0)
void setActive (bool)
void show ()
QSize sizeHint () const
QWidget * windowWidget () const
~QWorkspaceChild ()
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
bool event (QEvent *)
This is the main event handler; it handles event event.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyPressEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key press events for the widget.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void mouseMoveEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse move events for the widget.
virtual void mousePressEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse press events for the widget.
virtual void mouseReleaseEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse release events for the widget.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void wheelEvent (QWheelEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive wheel events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
void updateMask ()
Properties
bool act:1
QWidget * childWidget
QPointer< QWorkspaceTitleBar > iconw
bool shademode:1
QSize shadeRestore
QSize shadeRestoreMin
QWorkspaceTitleBar * titlebar
QWidgetResizeHandler * widgetResizeHandler
QSize windowSize
Friends
class QWorkspace
class QWorkspacePrivate
class QWorkspaceTitleBar
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 900 of file qworkspace.cpp.
Constructors and Destructors
QWorkspaceChild()
QWorkspaceChild::QWorkspaceChild (QWidget * window, QWorkspace * parent = 0, Qt::WindowFlags flags = 0)
Definition at line 2511 of file qworkspace.cpp.
     : QWidget(parent,
              Qt::FramelessWindowHint | Qt::SubWindow)
 {
     setAttribute(Qt::WA_DeleteOnClose);
     setAttribute(Qt::WA_NoMousePropagation);
     setMouseTracking(true);
     act = false;
     iconw = 0;
     shademode = false;
     titlebar = 0;
     setAutoFillBackground(true);
     setBackgroundRole(QPalette::Window);
     if (window) {
         flags |= (window->windowFlags() & Qt::MSWindowsOwnDC);
         if (flags)
             window->setParent(this, flags & ~Qt::WindowType_Mask);
         else
             window->setParent(this);
     }
     if (window && (flags & (Qt::WindowTitleHint
                             | Qt::WindowSystemMenuHint
                             | Qt::WindowMinimizeButtonHint
                             | Qt::WindowMaximizeButtonHint
                             | Qt::WindowContextHelpButtonHint))) {
         titlebar = new QWorkspaceTitleBar(window, this, flags);
         connect(titlebar, SIGNAL(doActivate()),
                  this, SLOT(activate()));
         connect(titlebar, SIGNAL(doClose()),
                  window, SLOT(close()));
         connect(titlebar, SIGNAL(doMinimize()),
                  this, SLOT(showMinimized()));
         connect(titlebar, SIGNAL(doNormal()),
                  this, SLOT(showNormal()));
         connect(titlebar, SIGNAL(doMaximize()),
                  this, SLOT(showMaximized()));
         connect(titlebar, SIGNAL(popupOperationMenu(QPoint)),
                  this, SIGNAL(popupOperationMenu(QPoint)));
         connect(titlebar, SIGNAL(showOperationMenu()),
                  this, SIGNAL(showOperationMenu()));
         connect(titlebar, SIGNAL(doShade()),
                  this, SLOT(showShaded()));
         connect(titlebar, SIGNAL(doubleClicked()),
                  this, SLOT(titleBarDoubleClicked()));
     }
     setMinimumSize(128, 0);
     int fw =  style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, this);
     setContentsMargins(fw, fw, fw, fw);
     childWidget = window;
     if (!childWidget)
         return;
     setWindowTitle(childWidget->windowTitle());
     QPoint p;
     QSize s;
     QSize cs;
     bool hasBeenResized = childWidget->testAttribute(Qt::WA_Resized);
     if (!hasBeenResized)
         cs = childWidget->sizeHint().expandedTo(childWidget->minimumSizeHint()).expandedTo(childWidget->minimumSize()).boundedTo(childWidget->maximumSize());
     else
         cs = childWidget->size();
     windowSize = cs;
     int th = titlebar ? titlebar->sizeHint().height() : 0;
     if (titlebar) {
         if (!childWidget->windowIcon().isNull())
             titlebar->setWindowIcon(childWidget->windowIcon());
         if (style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar))
             th -= contentsRect().y();
         p = QPoint(contentsRect().x(),
                     th + contentsRect().y());
         s = QSize(cs.width() + 2*frameWidth(),
                    cs.height() + 2*frameWidth() + th);
     } else {
         p = QPoint(contentsRect().x(), contentsRect().y());
         s = QSize(cs.width() + 2*frameWidth(),
                    cs.height() + 2*frameWidth());
     }
     childWidget->move(p);
     resize(s);
     childWidget->installEventFilter(this);
     widgetResizeHandler = new QWidgetResizeHandler(this, window);
     widgetResizeHandler->setSizeProtection(!parent->scrollBarsEnabled());
     widgetResizeHandler->setFrameWidth(frameWidth());
     connect(widgetResizeHandler, SIGNAL(activate()),
              this, SLOT(activate()));
     if (!style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar))
         widgetResizeHandler->setExtraHeight(th + contentsRect().y() - 2*frameWidth());
     else
         widgetResizeHandler->setExtraHeight(th + contentsRect().y() - frameWidth());
     if (childWidget->minimumSize() == childWidget->maximumSize())
         widgetResizeHandler->setActive(QWidgetResizeHandler::Resize, false);
     setBaseSize(baseSize());
 }
~QWorkspaceChild()
QWorkspaceChild::~QWorkspaceChild ()
Definition at line 2619 of file qworkspace.cpp.
 {
     QWorkspace *workspace = qobject_cast<QWorkspace*>(parentWidget());
     if (iconw) {
         if (workspace)
             workspace->d_func()->removeIcon(iconw->parentWidget());
         delete iconw->parentWidget();
     }
     if (workspace) {
         workspace->d_func()->focus.removeAll(this);
         if (workspace->d_func()->active == this)
             workspace->activatePreviousWindow();
         if (workspace->d_func()->active == this)
             workspace->d_func()->activateWindow(0);
         if (workspace->d_func()->maxWindow == this) {
             workspace->d_func()->hideMaximizeControls();
             workspace->d_func()->maxWindow = 0;
         }
     }
 }
Functions
activate
void QWorkspaceChild::activate () slot
Definition at line 2718 of file qworkspace.cpp.
Referenced by eventFilter(), iconWidget(), and QWorkspaceChild().
 {
     ((QWorkspace*)parentWidget())->d_func()->activateWindow(windowWidget());
 }
adjustToFullscreen()
void QWorkspaceChild::adjustToFullscreen ()
Definition at line 3115 of file qworkspace.cpp.
Referenced by QWorkspacePrivate::maximizeWindow().
 {
     if (!childWidget)
         return;
     if(!((QWorkspace*)parentWidget())->d_func()->maxmenubar || style()->styleHint(QStyle::SH_Workspace_FillSpaceOnMaximize, 0, this)) {
         setGeometry(parentWidget()->rect());
     } else {
         int fw =  style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, this);
         bool noBorder = style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar);
         int th = titlebar ? titlebar->sizeHint().height() : 0;
         int w = parentWidget()->width() + 2*fw;
         int h = parentWidget()->height() + (noBorder ? fw : 2*fw) + th;
         w = qMax(w, childWidget->minimumWidth());
         h = qMax(h, childWidget->minimumHeight());
         setGeometry(-fw, (noBorder ? 0 : -fw) - th, w, h);
     }
     childWidget->overrideWindowState(Qt::WindowMaximized);
     overrideWindowState(Qt::WindowMaximized);
 }
baseSize()
QSize QWorkspaceChild::baseSize () const
Definition at line 2688 of file qworkspace.cpp.
Referenced by QWorkspace::cascade(), eventFilter(), minimumSizeHint(), QWorkspaceChild(), sizeHint(), and QWorkspace::tile().
 {
     int th = titlebar ? titlebar->sizeHint().height() : 0;
     if (style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar))
         th -= frameWidth();
     return QSize(2*frameWidth(), 2*frameWidth() + th);
 }
changeEvent()
void QWorkspaceChild::changeEvent (QEvent * event) protected virtual
This event handler can be reimplemented to handle state changes.
The state being changed in this event can be retrieved through the event supplied.
Change events include: QEvent::ToolBarChange, QEvent::ActivationChange, QEvent::EnabledChange, QEvent::FontChange, QEvent::StyleChange, QEvent::PaletteChange, QEvent::WindowTitleChange, QEvent::IconTextChange, QEvent::ModifiedChange, QEvent::MouseTrackingChange, QEvent::ParentChange, QEvent::WindowStateChange, QEvent::LanguageChange, QEvent::LocaleChange, QEvent::LayoutDirectionChange.
Reimplemented from QWidget.
Definition at line 2895 of file qworkspace.cpp.
 {
     if(ev->type() == QEvent::StyleChange) {
         resizeEvent(0);
         if (iconw) {
             QFrame *frame = qobject_cast<QFrame*>(iconw->parentWidget());
             Q_ASSERT(frame);
             if (!style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar)) {
                 frame->setFrameStyle(QFrame::StyledPanel | QFrame::Raised);
                 frame->resize(196+2*frame->frameWidth(), 20 + 2*frame->frameWidth());
             } else {
                 frame->resize(196, 20);
             }
         }
         updateMask();
     }
     QWidget::changeEvent(ev);
 }
childEvent()
void QWorkspaceChild::childEvent (QChildEvent *) protected virtual
This event handler can be reimplemented in a subclass to receive child events.
The event is passed in the event parameter.
QEvent::ChildAdded and QEvent::ChildRemoved events are sent to objects when children are added or removed. In both cases you can only rely on the child being a QObject, or if isWidgetType() returns true, a QWidget. (This is because, in the ChildAdded case, the child is not yet fully constructed, and in the ChildRemoved case it might have been destructed already).
QEvent::ChildPolished events are sent to widgets when children are polished, or when polished children are added. If you receive a child polished event, the child's construction is usually completed. However, this is not guaranteed, and multiple polish events may be delivered during the execution of a widget's constructor.
For every child widget, you receive one ChildAdded event, zero or more ChildPolished events, and one ChildRemoved event.
The ChildPolished event is omitted if a child is removed immediately after it is added. If a child is polished several times during construction and destruction, you may receive several child polished events for the same child, each time with a different virtual table.
See also
event()
Reimplemented from QObject.
Definition at line 2844 of file qworkspace.cpp.
 {
     if (e->type() == QEvent::ChildRemoved && e->child() == childWidget) {
         childWidget = 0;
         if (iconw) {
             ((QWorkspace*)parentWidget())->d_func()->removeIcon(iconw->parentWidget());
             delete iconw->parentWidget();
         }
         close();
     }
 }
doMove()
void QWorkspaceChild::doMove ()
Definition at line 2862 of file qworkspace.cpp.
 {
     widgetResizeHandler->doMove();
 }
doResize()
void QWorkspaceChild::doResize ()
Definition at line 2857 of file qworkspace.cpp.
 {
     widgetResizeHandler->doResize();
 }
enterEvent()
void QWorkspaceChild::enterEvent (QEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
An event is sent to the widget when the mouse cursor enters the widget.
See also
leaveEvent(), mouseMoveEvent(), event()
Reimplemented from QWidget.
Definition at line 2867 of file qworkspace.cpp.
 {
 }
eventFilter()
bool QWorkspaceChild::eventFilter (QObject * , QEvent *) protected virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 2723 of file qworkspace.cpp.
 {
     if (!isActive()
         && (e->type() == QEvent::MouseButtonPress || e->type() == QEvent::FocusIn)) {
         if (iconw) {
             ((QWorkspace*)parentWidget())->d_func()->normalizeWindow(windowWidget());
             if (iconw) {
                 ((QWorkspace*)parentWidget())->d_func()->removeIcon(iconw->parentWidget());
                 delete iconw->parentWidget();
                 iconw = 0;
             }
         }
         activate();
     }
     // for all widgets except the window, that's the only thing we
     // process, and if we have no childWidget we skip totally
     if (o != childWidget || childWidget == 0)
         return false;
     switch (e->type()) {
     case QEvent::ShowToParent:
         if (((QWorkspace*)parentWidget())->d_func()->focus.indexOf(this) < 0)
             ((QWorkspace*)parentWidget())->d_func()->focus.append(this);
         if (windowWidget() && (windowWidget()->windowFlags() & Qt::WindowStaysOnTopHint)) {
             internalRaise();
             show();
         }
         ((QWorkspace*)parentWidget())->d_func()->showWindow(windowWidget());
         break;
     case QEvent::WindowStateChange: {
         if (static_cast<QWindowStateChangeEvent*>(e)->isOverride())
             break;
         Qt::WindowStates state = windowWidget()->windowState();
         if (state & Qt::WindowMinimized) {
             ((QWorkspace*)parentWidget())->d_func()->minimizeWindow(windowWidget());
         } else if (state & Qt::WindowMaximized) {
             if (windowWidget()->maximumSize().isValid() &&
                 (windowWidget()->maximumWidth() < parentWidget()->width() ||
                  windowWidget()->maximumHeight() < parentWidget()->height())) {
                 windowWidget()->resize(windowWidget()->maximumSize());
                 windowWidget()->overrideWindowState(Qt::WindowNoState);
                 if (titlebar)
                     titlebar->update();
                 break;
             }
             if ((windowWidget()->windowFlags() & Qt::WindowMaximizeButtonHint))
                 ((QWorkspace*)parentWidget())->d_func()->maximizeWindow(windowWidget());
             else
                 ((QWorkspace*)parentWidget())->d_func()->normalizeWindow(windowWidget());
         } else {
             ((QWorkspace*)parentWidget())->d_func()->normalizeWindow(windowWidget());
             if (iconw) {
                 ((QWorkspace*)parentWidget())->d_func()->removeIcon(iconw->parentWidget());
                 delete iconw->parentWidget();
             }
         }
     } break;
     case QEvent::HideToParent:
     {
         QWidget * w = iconw;
         if (w && (w = w->parentWidget())) {
             ((QWorkspace*)parentWidget())->d_func()->removeIcon(w);
             delete w;
         }
         ((QWorkspace*)parentWidget())->d_func()->hideChild(this);
     } break;
     case QEvent::WindowIconChange:
         {
             QWorkspace* ws = (QWorkspace*)parentWidget();
             if (ws->d_func()->maxtools && ws->d_func()->maxWindow == this) {
                 int iconSize = ws->d_func()->maxtools->size().height();
                 ws->d_func()->maxtools->setPixmap(childWidget->windowIcon().pixmap(QSize(iconSize, iconSize)));
             }
         }
         // fall through
     case QEvent::WindowTitleChange:
         setWindowTitle(windowWidget()->windowTitle());
         if (titlebar)
             titlebar->update();
         if (iconw)
             iconw->update();
         break;
     case QEvent::ModifiedChange:
         setWindowModified(windowWidget()->isWindowModified());
         if (titlebar)
             titlebar->update();
         if (iconw)
             iconw->update();
         break;
     case QEvent::Resize:
         {
             QResizeEvent* re = (QResizeEvent*)e;
             if (re->size() != windowSize && !shademode) {
                 resize(re->size() + baseSize());
                 childWidget->update(); //workaround
             }
         }
         break;
     case QEvent::WindowDeactivate:
         if (titlebar && titlebar->isActive()) {
             update();
         }
         break;
     case QEvent::WindowActivate:
         if (titlebar && titlebar->isActive()) {
             update();
         }
         break;
     default:
         break;
     }
     return QWidget::eventFilter(o, e);
 }
frameWidth()
int QWorkspaceChild::frameWidth () const
Definition at line 974 of file qworkspace.cpp.
Referenced by baseSize(), QWorkspaceChild(), resizeEvent(), and showShaded().
 {
     return contentsRect().left();
 }
iconWidget()
QWidget * QWorkspaceChild::iconWidget () const
Definition at line 3010 of file qworkspace.cpp.
Referenced by QWorkspacePrivate::minimizeWindow().
 {
     if (!iconw) {
         QWorkspaceChild* that = (QWorkspaceChild*) this;
         QFrame* frame = new QFrame(that, Qt::Window);
         QVBoxLayout *vbox = new QVBoxLayout(frame);
         vbox->setMargin(0);
         QWorkspaceTitleBar *tb = new QWorkspaceTitleBar(windowWidget(), frame);
         vbox->addWidget(tb);
         tb->setObjectName(QLatin1String("_workspacechild_icon_"));
         QStyleOptionTitleBar opt;
         tb->initStyleOption(&opt);
         int th = style()->pixelMetric(QStyle::PM_TitleBarHeight, &opt, tb);
         int iconSize = style()->pixelMetric(QStyle::PM_MdiSubWindowMinimizedWidth, 0, this);
         if (!style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar)) {
             frame->setFrameStyle(QFrame::StyledPanel | QFrame::Raised);
             frame->resize(iconSize+2*frame->frameWidth(), th+2*frame->frameWidth());
         } else {
             frame->resize(iconSize, th);
         }
         that->iconw = tb;
         that->updateMask();
         iconw->setActive(isActive());
         connect(iconw, SIGNAL(doActivate()),
                  this, SLOT(activate()));
         connect(iconw, SIGNAL(doClose()),
                  windowWidget(), SLOT(close()));
         connect(iconw, SIGNAL(doNormal()),
                  this, SLOT(showNormal()));
         connect(iconw, SIGNAL(doMaximize()),
                  this, SLOT(showMaximized()));
         connect(iconw, SIGNAL(popupOperationMenu(QPoint)),
                  this, SIGNAL(popupOperationMenu(QPoint)));
         connect(iconw, SIGNAL(showOperationMenu()),
                  this, SIGNAL(showOperationMenu()));
         connect(iconw, SIGNAL(doubleClicked()),
                  this, SLOT(titleBarDoubleClicked()));
     }
     if (windowWidget()) {
         iconw->setWindowTitle(windowWidget()->windowTitle());
     }
     return iconw->parentWidget();
 }
internalRaise
void QWorkspaceChild::internalRaise () slot
Definition at line 3136 of file qworkspace.cpp.
Referenced by QWorkspace::addWindow(), QWorkspace::cascade(), eventFilter(), and QWorkspacePrivate::maximizeWindow().
 {
     QWidget *stackUnderWidget = 0;
     if (!windowWidget() || (windowWidget()->windowFlags() & Qt::WindowStaysOnTopHint) == 0) {
         QList<QWorkspaceChild *>::Iterator it(((QWorkspace*)parent())->d_func()->windows.begin());
         while (it != ((QWorkspace*)parent())->d_func()->windows.end()) {
             QWorkspaceChild* c = *it;
             ++it;
             if (c->windowWidget() &&
                 !c->windowWidget()->isHidden() &&
                 (c->windowWidget()->windowFlags() & Qt::WindowStaysOnTopHint)) {
                 if (stackUnderWidget)
                     c->stackUnder(stackUnderWidget);
                 else
                     c->raise();
                 stackUnderWidget = c;
             }
         }
     }
     if (stackUnderWidget) {
         if (iconw)
             iconw->parentWidget()->stackUnder(stackUnderWidget);
         stackUnder(stackUnderWidget);
     } else {
         if (iconw)
             iconw->parentWidget()->raise();
         raise();
     }
 }
isActive()
bool QWorkspaceChild::isActive () const
Definition at line 2966 of file qworkspace.cpp.
Referenced by eventFilter(), and iconWidget().
 {
     return act;
 }
isWindowOrIconVisible()
bool QWorkspaceChild::isWindowOrIconVisible () const
Definition at line 2976 of file qworkspace.cpp.
Referenced by QWorkspace::windowList().
 {
     return childWidget && (!isHidden()  || (iconw && !iconw->isHidden()));
 }
leaveEvent()
void QWorkspaceChild::leaveEvent (QEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
A leave event is sent to the widget when the mouse cursor leaves the widget.
See also
enterEvent(), mouseMoveEvent(), event()
Reimplemented from QWidget.
Definition at line 2871 of file qworkspace.cpp.
 {
 #ifndef QT_NO_CURSOR
     if (!widgetResizeHandler->isButtonDown())
         setCursor(Qt::ArrowCursor);
 #endif
 }
minimumSizeHint()
QSize QWorkspaceChild::minimumSizeHint () const virtual
Reimplemented from QWidget.
Definition at line 2708 of file qworkspace.cpp.
Referenced by showShaded(), and sizeHint().
 {
     if (!childWidget)
         return QWidget::minimumSizeHint() + baseSize();
     QSize s = childWidget->minimumSize();
     if (s.isEmpty())
         s = childWidget->minimumSizeHint();
     return s + baseSize();
 }
moveEvent()
void QWorkspaceChild::moveEvent (QMoveEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
When the widget receives this event, it is already at the new position.
The old position is accessible through QMoveEvent::oldPos().
See also
resizeEvent(), event(), move(), QMoveEvent
Reimplemented from QWidget.
Definition at line 2641 of file qworkspace.cpp.
 {
     ((QWorkspace*)parentWidget())->d_func()->updateWorkspace();
 }
paintEvent()
void QWorkspaceChild::paintEvent (QPaintEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive paint events passed in event.
A paint event is a request to repaint all or part of a widget. It can happen for one of the following reasons:
repaint() or update() was invoked,
the widget was obscured and has now been uncovered, or
many other reasons.
Many widgets can simply repaint their entire surface when asked to, but some slow widgets need to optimize by painting only the requested region: QPaintEvent::region(). This speed optimization does not change the result, as painting is clipped to that region during event processing. QListView and QTableView do this, for example.
Qt also tries to speed up painting by merging multiple paint events into one. When update() is called several times or the window system sends several paint events, Qt merges these events into one event with a larger region (see QRegion::united()). The repaint() function does not permit this optimization, so we suggest using update() whenever possible.
When the paint event occurs, the update region has normally been erased, so you are painting on the widget's background.
The background can be set using setBackgroundRole() and setPalette().
Since Qt 4.0, QWidget automatically double-buffers its painting, so there is no need to write double-buffering code in paintEvent() to avoid flicker.
Note for the X11 platform: It is possible to toggle global double buffering by calling qt_x11_set_global_double_buffer(). For example,
...
extern void qt_x11_set_global_double_buffer(bool);
qt_x11_set_global_double_buffer(false);
...
Note
Generally, you should refrain from calling update() or repaint() inside a paintEvent(). For example, calling update() or repaint() on children inside a paintevent() results in undefined behavior; the child may or may not get a paint event.
Warning
If you are using a custom paint engine without Qt's backingstore, Qt::WA_PaintOnScreen must be set. Otherwise, QWidget::paintEngine() will never be called; the backingstore will be used instead.
See also
event(), repaint(), update(), QPainter, QPixmap, QPaintEvent, {Analog Clock Example}
Reimplemented from QWidget.
Definition at line 2879 of file qworkspace.cpp.
 {
     QPainter p(this);
     QStyleOptionFrame opt;
     opt.rect = rect();
     opt.palette = palette();
     opt.state = QStyle::State_None;
     opt.lineWidth = style()->pixelMetric(QStyle::PM_MdiSubWindowFrameWidth, 0, this);
     opt.midLineWidth = 1;
     if (titlebar && titlebar->isActive() && isActiveWindow())
         opt.state |= QStyle::State_Active;
     style()->drawPrimitive(QStyle::PE_FrameWindow, &opt, &p, this);
 }
popupOperationMenu
void QWorkspaceChild::popupOperationMenu (const QPoint &) signal
Referenced by iconWidget(), and QWorkspaceChild().
resizeEvent()
void QWorkspaceChild::resizeEvent (QResizeEvent *) protected virtual
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
When resizeEvent() is called, the widget already has its new geometry. The old size is accessible through QResizeEvent::oldSize().
The widget will be erased and receive a paint event immediately after processing the resize event. No drawing need be (or should be) done inside this handler.
See also
moveEvent(), event(), resize(), QResizeEvent, paintEvent(), {Scribble Example}
Reimplemented from QWidget.
Definition at line 2646 of file qworkspace.cpp.
Referenced by changeEvent().
 {
     bool wasMax = isMaximized();
     QRect r = contentsRect();
     QRect cr;
     updateMask();
     if (titlebar) {
         int th = titlebar->sizeHint().height();
         QRect tbrect(0, 0, width(), th);
         if (!style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar))
             tbrect = QRect(r.x(), r.y(), r.width(), th);
         titlebar->setGeometry(tbrect);
         if (style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar))
             th -= frameWidth();
         cr = QRect(r.x(), r.y() + th + (shademode ? (frameWidth() * 3) : 0),
                     r.width(), r.height() - th);
     } else {
         cr = r;
     }
     if (!childWidget)
         return;
     bool doContentsResize = (windowSize == childWidget->size()
                              || !(childWidget->testAttribute(Qt::WA_Resized) && childWidget->testAttribute(Qt::WA_PendingResizeEvent))
                              ||childWidget->isMaximized());
     windowSize = cr.size();
     childWidget->move(cr.topLeft());
     if (doContentsResize)
         childWidget->resize(cr.size());
     ((QWorkspace*)parentWidget())->d_func()->updateWorkspace();
     if (wasMax) {
         overrideWindowState(Qt::WindowMaximized);
         childWidget->overrideWindowState(Qt::WindowMaximized);
     }
 }
setActive()
void QWorkspaceChild::setActive (bool b)
Definition at line 2914 of file qworkspace.cpp.
Referenced by QWorkspacePrivate::activateWindow().
 {
     if (!childWidget)
         return;
     bool hasFocus = isChildOf(window()->focusWidget(), this);
     if (act == b && (act == hasFocus))
         return;
     act = b;
     if (titlebar)
         titlebar->setActive(act);
     if (iconw)
         iconw->setActive(act);
     update();
     QList<QWidget*> wl = childWidget->findChildren<QWidget*>();
     if (act) {
         for (int i = 0; i < wl.size(); ++i) {
             QWidget *w = wl.at(i);
             w->removeEventFilter(this);
         }
         if (!hasFocus) {
             QWidget *lastfocusw = childWidget->focusWidget();
             if (lastfocusw && lastfocusw->focusPolicy() != Qt::NoFocus) {
                 lastfocusw->setFocus();
             } else if (childWidget->focusPolicy() != Qt::NoFocus) {
                 childWidget->setFocus();
             } else {
                 // find something, anything, that accepts focus, and use that.
                 for (int i = 0; i < wl.size(); ++i) {
                     QWidget *w = wl.at(i);
                     if(w->focusPolicy() != Qt::NoFocus) {
                         w->setFocus();
                         hasFocus = true;
                         break;
                     }
                 }
                 if (!hasFocus)
                     setFocus();
             }
         }
     } else {
         for (int i = 0; i < wl.size(); ++i) {
             QWidget *w = wl.at(i);
             w->removeEventFilter(this);
             w->installEventFilter(this);
         }
     }
 }
show()
void QWorkspaceChild::show ()
Definition at line 3170 of file qworkspace.cpp.
Referenced by eventFilter(), QWorkspacePrivate::maximizeWindow(), and QWorkspacePrivate::normalizeWindow().
 {
     if (childWidget && childWidget->isHidden())
         childWidget->show();
     QWidget::show();
 }
showMaximized
void QWorkspaceChild::showMaximized () slot
Definition at line 3062 of file qworkspace.cpp.
Referenced by iconWidget(), QWorkspaceChild(), and titleBarDoubleClicked().
 {
     windowWidget()->setWindowState(Qt::WindowMaximized | (windowWidget()->windowState() & ~Qt::WindowMinimized));
 }
showMinimized
void QWorkspaceChild::showMinimized () slot
Definition at line 3057 of file qworkspace.cpp.
Referenced by QWorkspaceChild().
 {
     windowWidget()->setWindowState(Qt::WindowMinimized | (windowWidget()->windowState() & ~Qt::WindowMaximized));
 }
showNormal
void QWorkspaceChild::showNormal () slot
Definition at line 3067 of file qworkspace.cpp.
Referenced by QWorkspace::cascade(), iconWidget(), QWorkspaceChild(), QWorkspace::tile(), and titleBarDoubleClicked().
 {
     windowWidget()->setWindowState(windowWidget()->windowState() & ~(Qt::WindowMinimized|Qt::WindowMaximized));
 }
showOperationMenu
void QWorkspaceChild::showOperationMenu () signal
Referenced by iconWidget(), and QWorkspaceChild().
showShaded
void QWorkspaceChild::showShaded () slot
Definition at line 3072 of file qworkspace.cpp.
Referenced by QWorkspace::eventFilter(), QWorkspaceChild(), and titleBarDoubleClicked().
 {
     if (!titlebar)
         return;
     ((QWorkspace*)parentWidget())->d_func()->activateWindow(windowWidget());
     QWidget* w = windowWidget();
     if (shademode) {
         w->overrideWindowState(Qt::WindowNoState);
         overrideWindowState(Qt::WindowNoState);
         shademode = false;
         resize(shadeRestore.expandedTo(minimumSizeHint()));
         setMinimumSize(shadeRestoreMin);
         style()->polish(this);
     } else {
         shadeRestore = size();
         shadeRestoreMin = minimumSize();
         setMinimumHeight(0);
         shademode = true;
         w->overrideWindowState(Qt::WindowMinimized);
         overrideWindowState(Qt::WindowMinimized);
         if (style()->styleHint(QStyle::SH_TitleBar_NoBorder, 0, titlebar))
             resize(width(), titlebar->height());
         else
             resize(width(), titlebar->height() + 2*frameWidth() + 1);
         style()->polish(this);
     }
     titlebar->update();
 }
sizeHint()
QSize QWorkspaceChild::sizeHint () const virtual
Reimplemented from QWidget.
Definition at line 2696 of file qworkspace.cpp.
 {
     if (!childWidget)
         return QWidget::sizeHint() + baseSize();
     QSize prefSize = windowWidget()->sizeHint().expandedTo(windowWidget()->minimumSizeHint());
     prefSize = prefSize.expandedTo(windowWidget()->minimumSize()).boundedTo(windowWidget()->maximumSize());
     prefSize += baseSize();
     return prefSize;
 }
titleBarDoubleClicked
void QWorkspaceChild::titleBarDoubleClicked () slot
Definition at line 3103 of file qworkspace.cpp.
Referenced by iconWidget(), and QWorkspaceChild().
 {
     if (!windowWidget())
         return;
     if (iconw)
         showNormal();
     else if (windowWidget()->windowFlags() & Qt::WindowShadeButtonHint)
             showShaded();
     else if (windowWidget()->windowFlags() & Qt::WindowMaximizeButtonHint)
         showMaximized();
 }
updateMask()
void QWorkspaceChild::updateMask () private
Definition at line 2981 of file qworkspace.cpp.
Referenced by changeEvent(), iconWidget(), and resizeEvent().
 {
     QStyleOptionTitleBar titleBarOptions;
     titleBarOptions.rect = rect();
     titleBarOptions.titleBarFlags = windowFlags();
     titleBarOptions.titleBarState = windowState();
     QStyleHintReturnMask frameMask;
     if (style()->styleHint(QStyle::SH_WindowFrame_Mask, &titleBarOptions, this, &frameMask)) {
         setMask(frameMask.region);
     } else if (!mask().isEmpty()) {
         clearMask();
     }
     if (iconw) {
         QFrame *frame = qobject_cast<QFrame *>(iconw->parentWidget());
         Q_ASSERT(frame);
         titleBarOptions.rect = frame->rect();
         titleBarOptions.titleBarFlags = frame->windowFlags();
         titleBarOptions.titleBarState = frame->windowState() | Qt::WindowMinimized;
         if (style()->styleHint(QStyle::SH_WindowFrame_Mask, &titleBarOptions, frame, &frameMask)) {
             frame->setMask(frameMask.region);
         } else if (!frame->mask().isEmpty()) {
             frame->clearMask();
         }
     }
 }
windowWidget()
QWidget * QWorkspaceChild::windowWidget () const
Definition at line 2971 of file qworkspace.cpp.
Referenced by activate(), QWorkspacePrivate::activateWindow(), QWorkspace::cascade(), QWorkspace::closeAllWindows(), eventFilter(), QWorkspacePrivate::findChild(), iconWidget(), internalRaise(), showMaximized(), showMinimized(), showNormal(), showShaded(), sizeHint(), QWorkspace::tile(), titleBarDoubleClicked(), and QWorkspace::windowList().
 {
     return childWidget;
 }
Friends and Related Functions
QWorkspace
friend class QWorkspace friend
Definition at line 905 of file qworkspace.cpp.
QWorkspacePrivate
friend class QWorkspacePrivate friend
Definition at line 904 of file qworkspace.cpp.
QWorkspaceTitleBar
friend class QWorkspaceTitleBar friend
Definition at line 906 of file qworkspace.cpp.
Referenced by iconWidget(), and QWorkspaceChild().
Properties
act
bool QWorkspaceChild::act private
Definition at line 970 of file qworkspace.cpp.
Referenced by isActive(), QWorkspaceChild(), and setActive().
childWidget
QWidget* QWorkspaceChild::childWidget private
Definition at line 963 of file qworkspace.cpp.
Referenced by adjustToFullscreen(), childEvent(), eventFilter(), isWindowOrIconVisible(), minimumSizeHint(), QWorkspacePrivate::normalizeWindow(), QWorkspaceChild(), resizeEvent(), setActive(), show(), sizeHint(), and windowWidget().
iconw
QPointer<QWorkspaceTitleBar> QWorkspaceChild::iconw private
Definition at line 966 of file qworkspace.cpp.
Referenced by changeEvent(), childEvent(), eventFilter(), iconWidget(), internalRaise(), isWindowOrIconVisible(), QWorkspacePrivate::maximizeWindow(), QWorkspacePrivate::normalizeWindow(), QWorkspaceChild(), setActive(), QWorkspace::tile(), titleBarDoubleClicked(), updateMask(), and ~QWorkspaceChild().
shademode
bool QWorkspaceChild::shademode private
Definition at line 971 of file qworkspace.cpp.
Referenced by QWorkspace::eventFilter(), eventFilter(), QWorkspaceChild(), resizeEvent(), and showShaded().
shadeRestore
QSize QWorkspaceChild::shadeRestore private
Definition at line 968 of file qworkspace.cpp.
Referenced by showShaded().
shadeRestoreMin
QSize QWorkspaceChild::shadeRestoreMin private
Definition at line 969 of file qworkspace.cpp.
Referenced by showShaded().
titlebar
QWorkspaceTitleBar* QWorkspaceChild::titlebar private
Definition at line 965 of file qworkspace.cpp.
Referenced by adjustToFullscreen(), baseSize(), changeEvent(), eventFilter(), iconWidget(), QWorkspacePrivate::maximizeWindow(), QWorkspacePrivate::minimizeWindow(), QWorkspacePrivate::normalizeWindow(), paintEvent(), QWorkspaceChild(), resizeEvent(), setActive(), showShaded(), and QWorkspace::tile().
widgetResizeHandler
QWidgetResizeHandler* QWorkspaceChild::widgetResizeHandler private
Definition at line 964 of file qworkspace.cpp.
Referenced by doMove(), doResize(), leaveEvent(), QWorkspacePrivate::maximizeWindow(), QWorkspacePrivate::minimizeWindow(), QWorkspacePrivate::normalizeWindow(), QWorkspaceChild(), and QWorkspace::setScrollBarsEnabled().
windowSize
QSize QWorkspaceChild::windowSize private
Definition at line 967 of file qworkspace.cpp.
Referenced by eventFilter(), QWorkspaceChild(), and resizeEvent().
The documentation for this class was generated from the following file:
/src/gui/widgets/qworkspace.cpp