Qt 4.8: QPatternist::XsdInstanceReader Class Reference
QPatternist::XsdInstanceReader Class Reference
XML Schema Processing
The schema instance reader.
#include <qxsdinstancereader_p.h>
Public Types
typedef QExplicitlySharedDataPointer< XsdInstanceReader > Ptr
Public Functions
XsdInstanceReader (const QAbstractXmlNodeModel *model, const XsdSchemaContext::Ptr &context)
Protected Functions
bool atEnd () const
QString attribute (const QXmlName &name) const
QXmlItem attributeItem (const QXmlName &name) const
QSet< QXmlName > attributeNames () const
QXmlName convertToQName (const QString &name) const
bool hasAttribute (const QXmlName &name) const
bool hasChildElement () const
bool hasChildText () const
bool isEndElement () const
bool isStartElement () const
QXmlItem item () const
QXmlName name () const
QVector< QXmlName > namespaceBindings (const QXmlNodeModelIndex &index) const
void readNext ()
QSourceLocation sourceLocation () const
QString text () const
Protected Variables
XsdSchemaContext::Ptr m_context
Properties
QHash< QXmlName, QXmlItem > m_cachedAttributeItems
QHash< QXmlName, QString > m_cachedAttributes
QXmlItem m_cachedItem
QSourceLocation m_cachedSourceLocation
PullBridge m_model
Detailed Description
The schema instance reader.
This class reads in a xml instance document from a QAbstractXmlNodeModel and provides a QXmlStreamReader like interface with some additional context information.
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 75 of file qxsdinstancereader_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<XsdInstanceReader> QPatternist::XsdInstanceReader::Ptr
Definition at line 78 of file qxsdinstancereader_p.h.
Constructors and Destructors
XsdInstanceReader()
XsdInstanceReader::XsdInstanceReader (const QAbstractXmlNodeModel * model, const XsdSchemaContext::Ptr & context)
Creates a new instance reader that will read the data from the given model.
Parameters
model The model the data are read from.
context The context that is used for error reporting etc.
Definition at line 48 of file qxsdinstancereader.cpp.
     : m_context(context)
     , m_model(model->iterate(model->root(QXmlNodeModelIndex()), QXmlNodeModelIndex::AxisChild))
 {
 }
Functions
atEnd()
bool XsdInstanceReader::atEnd () const protected
Returns true if the end of the document is reached, false otherwise.
Definition at line 54 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::read().
 {
     return (m_model.current() == AbstractXmlPullProvider::EndOfInput);
 }
attribute()
QString XsdInstanceReader::attribute (const QXmlName & name) const protected
Returns the attribute with the given name of the current node.
Definition at line 145 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::qNameAttribute(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::XsdValidatingInstanceReader::validateElement(), and QPatternist::XsdValidatingInstanceReader::validateElementComplexType().
 {
     Q_ASSERT(m_cachedAttributes.contains(name));
     return m_cachedAttributes.value(name);
 }
attributeItem()
QXmlItem XsdInstanceReader::attributeItem (const QXmlName & name) const protected
Returns the QXmlItem for the attribute with the given name at the current position.
Definition at line 181 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateAttribute().
 {
     return m_cachedAttributeItems.value(name);
 }
attributeNames()
QSet< QXmlName > XsdInstanceReader::attributeNames () const protected
Returns the list of attribute names of the current node.
Definition at line 152 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), and QPatternist::XsdValidatingInstanceReader::validateElementSimpleType().
 {
     return m_cachedAttributes.keys().toSet();
 }
convertToQName()
QXmlName XsdInstanceReader::convertToQName (const QString & name) const protected
Converts a qualified name into a QXmlName according to the namespace mappings of the current node.
Definition at line 118 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QPatternist::XsdValidatingInstanceReader::validate(), and QPatternist::XsdValidatingInstanceReader::validateElement().
 {
     const int pos = name.indexOf(QLatin1Char(':'));
     QXmlName::PrefixCode prefixCode = 0;
     QXmlName::NamespaceCode namespaceCode;
     QXmlName::LocalNameCode localNameCode;
     if (pos != -1) {
         prefixCode = m_context->namePool()->allocatePrefix(name.left(pos));
         namespaceCode = m_cachedItem.toNodeModelIndex().namespaceForPrefix(prefixCode);
         localNameCode = m_context->namePool()->allocateLocalName(name.mid(pos + 1));
     } else {
         prefixCode = StandardPrefixes::empty;
         namespaceCode = m_cachedItem.toNodeModelIndex().namespaceForPrefix(prefixCode);
         if (namespaceCode == -1)
             namespaceCode = StandardNamespaces::empty;
         localNameCode = m_context->namePool()->allocateLocalName(name);
     }
     return QXmlName(namespaceCode, localNameCode, prefixCode);
 }
hasAttribute()
bool XsdInstanceReader::hasAttribute (const QXmlName & name) const protected
Returns whether the current node has an attribute with the given name.
Definition at line 140 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validate(), and QPatternist::XsdValidatingInstanceReader::validateElement().
 {
     return m_cachedAttributes.contains(name);
 }
hasChildElement()
bool XsdInstanceReader::hasChildElement () const protected
Returns whether the current node has an element node among its children.
Definition at line 97 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), and QPatternist::XsdValidatingInstanceReader::validateElementSimpleType().
 {
     const QXmlNodeModelIndex index = m_model.index();
     QXmlNodeModelIndex::Iterator::Ptr it = index.model()->iterate(index, QXmlNodeModelIndex::AxisChild);
     QXmlNodeModelIndex currentIndex = it->next();
     while (!currentIndex.isNull()) {
         if (currentIndex.kind() == QXmlNodeModelIndex::Element)
             return true;
         currentIndex = it->next();
     }
     return false;
 }
hasChildText()
bool XsdInstanceReader::hasChildText () const protected
Returns whether the current node has a text node among its children.
Definition at line 81 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateElement(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), and QPatternist::XsdValidatingInstanceReader::validateElementSimpleType().
 {
     const QXmlNodeModelIndex index = m_model.index();
     QXmlNodeModelIndex::Iterator::Ptr it = index.model()->iterate(index, QXmlNodeModelIndex::AxisChild);
     QXmlNodeModelIndex currentIndex = it->next();
     while (!currentIndex.isNull()) {
         if (currentIndex.kind() == QXmlNodeModelIndex::Text)
             return true;
         currentIndex = it->next();
     }
     return false;
 }
isEndElement()
bool XsdInstanceReader::isEndElement () const protected
Returns whether the current node is an end element.
Definition at line 76 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::read().
 {
     return (m_model.current() == AbstractXmlPullProvider::EndElement);
 }
isStartElement()
bool XsdInstanceReader::isStartElement () const protected
Returns whether the current node is a start element.
Definition at line 71 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::read().
 {
     return (m_model.current() == AbstractXmlPullProvider::StartElement);
 }
item()
QXmlItem XsdInstanceReader::item () const protected
Returns the QXmlItem for the current position.
Definition at line 176 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::read(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), and QPatternist::XsdValidatingInstanceReader::validateElementSimpleType().
 {
     return m_cachedItem;
 }
name()
QXmlName XsdInstanceReader::name () const protected
Returns the name of the current node.
Definition at line 113 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdValidatingInstanceReader::read(), QPatternist::XsdValidatingInstanceReader::selectNodeSets(), QPatternist::XsdValidatingInstanceReader::validate(), and QPatternist::XsdValidatingInstanceReader::validateAttributeWildcard().
 {
     return m_model.name();
 }
namespaceBindings()
QVector< QXmlName > XsdInstanceReader::namespaceBindings (const QXmlNodeModelIndex & index) const protected
Returns the namespace bindings for the given node model index.
Definition at line 191 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), and QPatternist::XsdValidatingInstanceReader::validateElementSimpleType().
 {
     return index.namespaceBindings();
 }
readNext()
void XsdInstanceReader::readNext () protected
Reads the next node from the document.
Definition at line 59 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::read().
 {
     m_model.next();
     if (m_model.current() == AbstractXmlPullProvider::StartElement) {
         m_cachedAttributes = m_model.attributes();
         m_cachedAttributeItems = m_model.attributeItems();
         m_cachedSourceLocation = m_model.sourceLocation();
         m_cachedItem = QXmlItem(m_model.index());
     }
 }
sourceLocation()
QSourceLocation XsdInstanceReader::sourceLocation () const protected
Returns a source location object for the current position.
Definition at line 186 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::error(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QPatternist::XsdValidatingInstanceReader::validateKeyIdentityConstraint(), QPatternist::XsdValidatingInstanceReader::validateKeyRefIdentityConstraint(), and QPatternist::XsdValidatingInstanceReader::validateUniqueIdentityConstraint().
 {
     return m_cachedSourceLocation;
 }
text()
QString XsdInstanceReader::text () const protected
Returns the concatenated text of all direct child text nodes.
Definition at line 157 of file qxsdinstancereader.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), and QPatternist::XsdValidatingInstanceReader::validateElementSimpleType().
 {
     const QXmlNodeModelIndex index = m_model.index();
     QXmlNodeModelIndex::Iterator::Ptr it = index.model()->iterate(index, QXmlNodeModelIndex::AxisChild);
     QString result;
     QXmlNodeModelIndex currentIndex = it->next();
     while (!currentIndex.isNull()) {
         if (currentIndex.kind() == QXmlNodeModelIndex::Text) {
             result.append(Item(currentIndex).stringValue());
         }
         currentIndex = it->next();
     }
     return result;
 }
Properties
m_cachedAttributeItems
QHash<QXmlName, QXmlItem> QPatternist::XsdInstanceReader::m_cachedAttributeItems private
Definition at line 179 of file qxsdinstancereader_p.h.
Referenced by attributeItem(), and readNext().
m_cachedAttributes
QHash<QXmlName, QString> QPatternist::XsdInstanceReader::m_cachedAttributes private
Definition at line 178 of file qxsdinstancereader_p.h.
Referenced by attribute(), attributeNames(), hasAttribute(), and readNext().
m_cachedItem
QXmlItem QPatternist::XsdInstanceReader::m_cachedItem private
Definition at line 181 of file qxsdinstancereader_p.h.
Referenced by convertToQName(), item(), and readNext().
m_cachedSourceLocation
QSourceLocation QPatternist::XsdInstanceReader::m_cachedSourceLocation private
Definition at line 180 of file qxsdinstancereader_p.h.
Referenced by readNext(), and sourceLocation().
m_context
XsdSchemaContext::Ptr QPatternist::XsdInstanceReader::m_context protected
The shared schema context.
Definition at line 174 of file qxsdinstancereader_p.h.
Referenced by convertToQName(), QPatternist::XsdValidatingInstanceReader::error(), QPatternist::XsdValidatingInstanceReader::loadSchema(), QPatternist::XsdValidatingInstanceReader::typeByName(), QPatternist::XsdValidatingInstanceReader::validateAttribute(), QPatternist::XsdValidatingInstanceReader::validateElementComplexType(), QPatternist::XsdValidatingInstanceReader::validateElementSimpleType(), QPatternist::XsdValidatingInstanceReader::validateKeyRefIdentityConstraint(), QPatternist::XsdValidatingInstanceReader::validateUniqueIdentityConstraint(), and QPatternist::XsdValidatingInstanceReader::XsdValidatingInstanceReader().
m_model
PullBridge QPatternist::XsdInstanceReader::m_model private
Definition at line 177 of file qxsdinstancereader_p.h.
Referenced by atEnd(), hasChildElement(), hasChildText(), isEndElement(), isStartElement(), name(), readNext(), and text().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdinstancereader_p.h
/src/xmlpatterns/schema/qxsdinstancereader.cpp