Qt 4.8: QBoxLayout Class Reference
QBoxLayout Class Reference
The QBoxLayout class lines up child widgets horizontally or vertically.
#include <qboxlayout.h>
Public Types
enum Direction {
LeftToRight, RightToLeft, TopToBottom, BottomToTop,
Down = TopToBottom, Up = BottomToTop
}
This type is used to determine the direction of a box layout.
Public Types inherited from QLayout
enum SizeConstraint {
SetDefaultConstraint, SetNoConstraint, SetMinimumSize, SetFixedSize,
SetMaximumSize, SetMinAndMaxSize
}
The possible values are:
Public Functions
void addItem (QLayoutItem *)
Reimplemented Function
void addLayout (QLayout *layout, int stretch=0)
Adds layout to the end of the box, with serial stretch factor stretch.
void addSpacerItem (QSpacerItem *spacerItem)
Adds spacerItem to the end of this box layout.
void addSpacing (int size)
Adds a non-stretchable space (a QSpacerItem) with size size to the end of this box layout.
void addStretch (int stretch=0)
Adds a stretchable space (a QSpacerItem) with zero minimum size and stretch factor stretch to the end of this box layout.
void addStrut (int)
Limits the perpendicular dimension of the box (e.g.
void addWidget (QWidget *, int stretch=0, Qt::Alignment alignment=0)
Adds widget to the end of this box layout, with a stretch factor of stretch and alignment alignment.
int count () const
Reimplemented Function
Direction direction () const
Returns the direction of the box.
Qt::Orientations expandingDirections () const
Reimplemented Function
bool hasHeightForWidth () const
Reimplemented Function
int heightForWidth (int) const
Reimplemented Function
void insertLayout (int index, QLayout *layout, int stretch=0)
Inserts layout at position index, with stretch factor stretch.
void insertSpacerItem (int index, QSpacerItem *spacerItem)
Inserts spacerItem at position index, with zero minimum size and stretch factor.
void insertSpacing (int index, int size)
Inserts a non-stretchable space (a QSpacerItem) at position index, with size size.
void insertStretch (int index, int stretch=0)
Inserts a stretchable space (a QSpacerItem) at position index, with zero minimum size and stretch factor stretch.
void insertWidget (int index, QWidget *widget, int stretch=0, Qt::Alignment alignment=0)
Inserts widget at position index, with stretch factor stretch and alignment alignment.
void invalidate ()
Resets cached information.
QLayoutItem * itemAt (int) const
Reimplemented Function
QSize maximumSize () const
Reimplemented Function
int minimumHeightForWidth (int) const
Reimplemented Function
QSize minimumSize () const
Reimplemented Function
QBoxLayout (Direction, QWidget *parent=0)
Constructs a new QBoxLayout with direction dir and parent widget parent.
void setDirection (Direction)
Sets the direction of this layout to direction.
void setGeometry (const QRect &)
Reimplemented Function
void setSpacing (int spacing)
Reimplements QLayout::setSpacing().
void setStretch (int index, int stretch)
Sets the stretch factor at position index.
bool setStretchFactor (QWidget *w, int stretch)
Sets the stretch factor for widget to stretch and returns true if widget is found in this layout (not including child layouts); otherwise returns false.
bool setStretchFactor (QLayout *l, int stretch)
Sets the stretch factor for the layout layout to stretch and returns true if layout is found in this layout (not including child layouts); otherwise returns false.
QSize sizeHint () const
Reimplemented Function
int spacing () const
Reimplements QLayout::spacing().
int stretch (int index) const
Returns the stretch factor at position index.
QLayoutItem * takeAt (int)
Reimplemented Function
~QBoxLayout ()
Destroys this box layout.
Public Functions inherited from QLayout
bool activate ()
Redoes the layout for parentWidget() if necessary.
void addWidget (QWidget *w)
Adds widget w to this layout in a manner specific to the layout.
QMargins contentsMargins () const
Returns the margins used around the layout.
QRect contentsRect () const
Returns the layout's geometry() rectangle, but taking into account the contents margins.
Qt::Orientations expandingDirections () const
Returns whether this layout can make use of more space than sizeHint().
QRect geometry () const
Reimplemented Function
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
virtual int indexOf (QWidget *) const
Searches for widget widget in this layout (not including child layouts).
void invalidate ()
Reimplemented Function
bool isEmpty () const
Reimplemented Function
bool isEnabled () const
Returns true if the layout is enabled; otherwise returns false.
QLayout * layout ()
Reimplemented Function
int margin () const
QSize maximumSize () const
Returns the maximum size of this layout.
QWidget * menuBar () const
Returns the menu bar set for this layout, or 0 if no menu bar is set.
QSize minimumSize () const
Returns the minimum size of this layout.
QWidget * parentWidget () const
Returns the parent widget of this layout, or 0 if this layout is not installed on any widget.
QLayout (QWidget *parent)
Constructs a new top-level QLayout, with parent parent.
QLayout ()
Constructs a new child QLayout.
void removeItem (QLayoutItem *)
Removes the layout item item from the layout.
void removeWidget (QWidget *w)
Removes the widget widget from the layout.
bool setAlignment (QWidget *w, Qt::Alignment alignment)
Sets the alignment for widget w to alignment and returns true if w is found in this layout (not including child layouts); otherwise returns false.
bool setAlignment (QLayout *l, Qt::Alignment alignment)
Sets the alignment for the layout l to alignment and returns true if l is found in this layout (not including child layouts); otherwise returns false.
void setContentsMargins (int left, int top, int right, int bottom)
Sets the left, top, right, and bottom margins to use around the layout.
void setContentsMargins (const QMargins &margins)
Sets the margins to use around the layout.
void setEnabled (bool)
Enables this layout if enable is true, otherwise disables it.
void setMargin (int)
void setMenuBar (QWidget *w)
Tells the geometry manager to place the menu bar widget at the top of parentWidget(), outside QWidget::contentsMargins().
void setSizeConstraint (SizeConstraint)
void setSpacing (int)
SizeConstraint sizeConstraint () const
int spacing () const
int totalHeightForWidth (int w) const
Also takes contentsMargins and menu bar into account.
QSize totalMaximumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalMinimumSize () const
Also takes contentsMargins and menu bar into account.
QSize totalSizeHint () const
Also takes contentsMargins and menu bar into account.
void update ()
Updates the layout for parentWidget().
~QLayout ()
Destroys the layout, deleting all child layouts.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual QWidget * widget ()
If this item is a QWidget, it is returned as a QWidget; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Protected Functions
void insertItem (int index, QLayoutItem *)
Inserts item into this box layout at position index.
Protected Functions inherited from QLayout
void addChildLayout (QLayout *l)
This function is called from addLayout() or insertLayout() functions in subclasses to add layout l as a sub-layout.
void addChildWidget (QWidget *w)
This function is called from addWidget() functions in subclasses to add w as a managed widget of a layout.
bool adoptLayout (QLayout *layout)
QRect alignmentRect (const QRect &) const
Returns the rectangle that should be covered when the geometry of this layout is set to r, provided that this layout supports setAlignment().
void childEvent (QChildEvent *e)
Reimplemented Function
QLayout (QLayoutPrivate &d, QLayout *, QWidget *)
void widgetEvent (QEvent *)
Performs child widget layout when the parent widget is resized.
Protected Functions inherited from QObject
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QLayout
static QSize closestAcceptableSize (const QWidget *w, const QSize &s)
Returns a size that satisfies all size constraints on widget, including heightForWidth() and that is as close as possible to size.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QBoxLayout class lines up child widgets horizontally or vertically.
QBoxLayout takes the space it gets (from its parent layout or from the parentWidget()), divides it up into a row of boxes, and makes each managed widget fill one box.
Horizontal box layout with five child widgets
If the QBoxLayout's orientation is Qt::Horizontal the boxes are placed in a row, with suitable sizes. Each widget (or other box) will get at least its minimum size and at most its maximum size. Any excess space is shared according to the stretch factors (more about that below).
Vertical box layout with five child widgets
If the QBoxLayout's orientation is Qt::Vertical, the boxes are placed in a column, again with suitable sizes.
The easiest way to create a QBoxLayout is to use one of the convenience classes, e.g. QHBoxLayout (for Qt::Horizontal boxes) or QVBoxLayout (for Qt::Vertical boxes). You can also use the QBoxLayout constructor directly, specifying its direction as LeftToRight, RightToLeft, TopToBottom, or BottomToTop.
If the QBoxLayout is not the top-level layout (i.e. it is not managing all of the widget's area and children), you must add it to its parent layout before you can do anything with it. The normal way to add a layout is by calling parentLayout->addLayout().
Once you have done this, you can add boxes to the QBoxLayout using one of four functions:
addWidget() to add a widget to the QBoxLayout and set the widget's stretch factor. (The stretch factor is along the row of boxes.)
addSpacing() to create an empty box; this is one of the functions you use to create nice and spacious dialogs. See below for ways to set margins.
addStretch() to create an empty, stretchable box.
addLayout() to add a box containing another QLayout to the row and set that layout's stretch factor.
Use insertWidget(), insertSpacing(), insertStretch() or insertLayout() to insert a box at a specified position in the layout.
QBoxLayout also includes two margin widths:
setContentsMargins() sets the width of the outer border on each side of the widget. This is the width of the reserved space along each of the QBoxLayout's four sides.
setSpacing() sets the width between neighboring boxes. (You can use addSpacing() to get more space at a particular spot.)
The margin default is provided by the style. The default margin most Qt styles specify is 9 for child widgets and 11 for windows. The spacing defaults to the same as the margin width for a top-level layout, or to the same as the parent layout.
To remove a widget from a layout, call removeWidget(). Calling QWidget::hide() on a widget also effectively removes the widget from the layout until QWidget::show() is called.
You will almost always want to use QVBoxLayout and QHBoxLayout rather than QBoxLayout because of their convenient constructors.
See also
QGridLayout, QStackedLayout, {Layout Management}
Definition at line 60 of file qboxlayout.h.
Enumerations
Direction
enum QBoxLayout::Direction
This type is used to determine the direction of a box layout.
LeftToRight Horizontal from left to right.
RightToLeft Horizontal from right to left.
TopToBottom Vertical from top to bottom.
BottomToTop Vertical from bottom to top.
Down
Up
Enumerator
LeftToRight
RightToLeft
TopToBottom
BottomToTop
Down
Up
Definition at line 65 of file qboxlayout.h.
                    { LeftToRight, RightToLeft, TopToBottom, BottomToTop,
                      Down = TopToBottom, Up = BottomToTop };
Constructors and Destructors
QBoxLayout()
QBoxLayout::QBoxLayout (Direction dir, QWidget * parent = 0) explicit
Constructs a new QBoxLayout with direction dir and parent widget parent.
See also
direction()
Definition at line 558 of file qboxlayout.cpp.
Referenced by QHBoxLayout::QHBoxLayout(), and QVBoxLayout::QVBoxLayout().
     : QLayout(*new QBoxLayoutPrivate, 0, parent)
 {
     Q_D(QBoxLayout);
     d->dir = dir;
 }
~QBoxLayout()
QBoxLayout::~QBoxLayout ()
Destroys this box layout.
The layout's widgets aren't destroyed.
Definition at line 632 of file qboxlayout.cpp.
 {
     Q_D(QBoxLayout);
     d->deleteAll(); // must do it before QObject deletes children, so can't be in ~QBoxLayoutPrivate
 }
Functions
addItem()
void QBoxLayout::addItem (QLayoutItem * item) virtual
Reimplemented Function
Implements QLayout.
Definition at line 894 of file qboxlayout.cpp.
Referenced by QCalendarWidgetPrivate::createNavigationBar(), and QScriptDebuggerCodeFinderWidget::QScriptDebuggerCodeFinderWidget().
 {
     Q_D(QBoxLayout);
     QBoxLayoutItem *it = new QBoxLayoutItem(item);
     d->list.append(it);
     invalidate();
 }
addLayout()
void QBoxLayout::addLayout (QLayout * layout, int stretch = 0)
Adds layout to the end of the box, with serial stretch factor stretch.
See also
insertLayout(), addItem(), addWidget()
Definition at line 1140 of file qboxlayout.cpp.
Referenced by QColorDialogPrivate::init(), QPrintPreviewDialogPrivate::init(), QStatusBar::reformat(), and QCoreFuriCuri::timerEvent().
 {
     insertLayout(-1, layout, stretch);
 }
addSpacerItem()
void QBoxLayout::addSpacerItem (QSpacerItem * spacerItem)
Adds spacerItem to the end of this box layout.
Since
4.4
See also
addSpacing(), addStretch()
Definition at line 1104 of file qboxlayout.cpp.
 {
     insertSpacerItem(-1, spacerItem);
 }
addSpacing()
void QBoxLayout::addSpacing (int size)
Adds a non-stretchable space (a QSpacerItem) with size size to the end of this box layout.
QBoxLayout provides default margin and spacing. This function adds additional space.
See also
insertSpacing(), addItem(), QSpacerItem
Definition at line 1078 of file qboxlayout.cpp.
Referenced by QColorDialogPrivate::init(), QDialogButtonBoxPrivate::layoutButtons(), QComboBoxPrivateContainer::QComboBoxPrivateContainer(), and QStatusBar::reformat().
 {
     insertSpacing(-1, size);
 }
addStretch()
void QBoxLayout::addStretch (int stretch = 0)
Adds a stretchable space (a QSpacerItem) with zero minimum size and stretch factor stretch to the end of this box layout.
See also
insertStretch(), addItem(), QSpacerItem
Definition at line 1089 of file qboxlayout.cpp.
Referenced by QColorDialogPrivate::init(), QDialogButtonBoxPrivate::layoutButtons(), and QStatusBar::reformat().
 {
     insertStretch(-1, stretch);
 }
addStrut()
void QBoxLayout::addStrut (int size)
Limits the perpendicular dimension of the box (e.g.
height if the box is LeftToRight) to a minimum of size. Other constraints may increase the limit.
See also
addItem()
Definition at line 1152 of file qboxlayout.cpp.
Referenced by QStatusBar::reformat().
 {
     Q_D(QBoxLayout);
     QLayoutItem *b;
     if (horz(d->dir))
         b = QLayoutPrivate::createSpacerItem(this, 0, size, QSizePolicy::Fixed, QSizePolicy::Minimum);
     else
         b = QLayoutPrivate::createSpacerItem(this, size, 0, QSizePolicy::Minimum, QSizePolicy::Fixed);
     QBoxLayoutItem *it = new QBoxLayoutItem(b);
     it->magic = true;
     d->list.append(it);
     invalidate();
 }
addWidget()
void QBoxLayout::addWidget (QWidget * widget, int stretch = 0, Qt::Alignment alignment = 0)
Adds widget to the end of this box layout, with a stretch factor of stretch and alignment alignment.
The stretch factor applies only in the direction of the QBoxLayout, and is relative to the other boxes and widgets in this QBoxLayout. Widgets and boxes with higher stretch factors grow more.
If the stretch factor is 0 and nothing else in the QBoxLayout has a stretch factor greater than zero, the space is distributed according to the QWidget:sizePolicy() of each widget that's involved.
The alignment is specified by alignment. The default alignment is 0, which means that the widget fills the entire cell.
See also
insertWidget(), addItem(), addLayout(), addStretch(), addSpacing(), addStrut()
Definition at line 1129 of file qboxlayout.cpp.
Referenced by QDialogButtonBoxPrivate::addButtonsToLayout(), QPrintPropertiesDialog::addItemToOptions(), QCalendarTextNavigator::createDateLabel(), QCalendarWidgetPrivate::createNavigationBar(), QInputDialogPrivate::ensureLayout(), QScriptEdit::extraAreaMouseEvent(), QWorkspaceChild::iconWidget(), QColorDialogPrivate::init(), QFontDialogPrivate::init(), QPrintPreviewDialogPrivate::init(), QPrintPreviewWidgetPrivate::init(), QPageSetupDialogPrivate::init(), QDialogButtonBoxPrivate::layoutButtons(), QCalendarWidget::QCalendarWidget(), QComboBoxPrivateContainer::QComboBoxPrivateContainer(), QMessageBoxDetailsText::QMessageBoxDetailsText(), QPageSetupWidget::QPageSetupWidget(), QPrintPropertiesDialog::QPrintPropertiesDialog(), QScriptBreakpointsWidget::QScriptBreakpointsWidget(), QScriptDebuggerCodeFinderWidget::QScriptDebuggerCodeFinderWidget(), QScriptDebuggerCodeView::QScriptDebuggerCodeView(), QScriptDebuggerCodeWidget::QScriptDebuggerCodeWidget(), QScriptDebuggerConsoleWidget::QScriptDebuggerConsoleWidget(), QScriptDebuggerLocalsWidget::QScriptDebuggerLocalsWidget(), QScriptDebuggerScriptsWidget::QScriptDebuggerScriptsWidget(), QScriptDebuggerStackWidget::QScriptDebuggerStackWidget(), QScriptDebugOutputWidget::QScriptDebugOutputWidget(), QScriptErrorLogWidget::QScriptErrorLogWidget(), QScriptNewBreakpointWidget::QScriptNewBreakpointWidget(), QStatusBar::reformat(), QCalendarPopup::setCalendarWidget(), QScriptEngineDebugger::standardWindow(), and QCoreFuriCuri::timerEvent().
 {
     insertWidget(-1, widget, stretch, alignment);
 }
count()
int QBoxLayout::count () const virtual
Reimplemented Function
Implements QLayout.
Definition at line 769 of file qboxlayout.cpp.
Referenced by QCalendarWidgetPrivate::createNavigationBar(), QDialogButtonBoxPrivate::layoutButtons(), and QComboBoxPrivateContainer::updateTopBottomMargin().
 {
     Q_D(const QBoxLayout);
     return d->list.count();
 }
direction()
QBoxLayout::Direction QBoxLayout::direction () const
Returns the direction of the box.
addWidget() and addSpacing() work in this direction; the stretch stretches in this direction.
See also
QBoxLayout::Direction addWidget() addSpacing()
Definition at line 1308 of file qboxlayout.cpp.
Referenced by setDirection().
 {
     Q_D(const QBoxLayout);
     return d->dir;
 }
expandingDirections()
Qt::Orientations QBoxLayout::expandingDirections () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 811 of file qboxlayout.cpp.
 {
     Q_D(const QBoxLayout);
     if (d->dirty)
         const_cast<QBoxLayout*>(this)->d_func()->setupGeom();
     return d->expanding;
 }
hasHeightForWidth()
bool QBoxLayout::hasHeightForWidth () const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 717 of file qboxlayout.cpp.
Referenced by heightForWidth().
 {
     Q_D(const QBoxLayout);
     if (d->dirty)
         const_cast<QBoxLayout*>(this)->d_func()->setupGeom();
     return d->hasHfw;
 }
heightForWidth()
int QBoxLayout::heightForWidth (int w) const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 728 of file qboxlayout.cpp.
 {
     Q_D(const QBoxLayout);
     if (!hasHeightForWidth())
         return -1;
     int left, top, right, bottom;
     d->effectiveMargins(&left, &top, &right, &bottom);
     w -= left + right;
     if (w != d->hfwWidth)
         const_cast<QBoxLayout*>(this)->d_func()->calcHfw(w);
     return d->hfwHeight + top + bottom;
 }
insertItem()
void QBoxLayout::insertItem (int index, QLayoutItem * item) protected
Inserts item into this box layout at position index.
If index is negative, the item is added at the end.
See also
addItem(), insertWidget(), insertLayout(), insertStretch(), insertSpacing()
Definition at line 909 of file qboxlayout.cpp.
 {
     Q_D(QBoxLayout);
     if (index < 0)                                // append
         index = d->list.count();
     QBoxLayoutItem *it = new QBoxLayoutItem(item);
     d->list.insert(index, it);
     invalidate();
 }
insertLayout()
void QBoxLayout::insertLayout (int index, QLayout * layout, int stretch = 0)
Inserts layout at position index, with stretch factor stretch.
If index is negative, the layout is added at the end.
layout becomes a child of the box layout.
See also
addLayout(), insertItem()
Definition at line 1010 of file qboxlayout.cpp.
Referenced by addLayout().
 {
     Q_D(QBoxLayout);
     if (!adoptLayout(layout))
         return;
     if (index < 0)                                // append
         index = d->list.count();
     QBoxLayoutItem *it = new QBoxLayoutItem(layout, stretch);
     d->list.insert(index, it);
     invalidate();
 }
insertSpacerItem()
void QBoxLayout::insertSpacerItem (int index, QSpacerItem * spacerItem)
Inserts spacerItem at position index, with zero minimum size and stretch factor.
Since
4.4
If index is negative the space is added at the end.
See also
addSpacerItem(), insertStretch(), insertSpacing()
Definition at line 990 of file qboxlayout.cpp.
Referenced by addSpacerItem().
 {
     Q_D(QBoxLayout);
     if (index < 0)                                // append
         index = d->list.count();
     QBoxLayoutItem *it = new QBoxLayoutItem(spacerItem);
     it->magic = true;
     d->list.insert(index, it);
     invalidate();
 }
insertSpacing()
void QBoxLayout::insertSpacing (int index, int size)
Inserts a non-stretchable space (a QSpacerItem) at position index, with size size.
If index is negative the space is added at the end.
The box layout has default margin and spacing. This function adds additional space.
See also
addSpacing(), insertItem(), QSpacerItem
Definition at line 929 of file qboxlayout.cpp.
Referenced by addSpacing(), and QComboBoxPrivateContainer::QComboBoxPrivateContainer().
 {
     Q_D(QBoxLayout);
     if (index < 0)                                // append
         index = d->list.count();
     QLayoutItem *b;
     if (horz(d->dir))
         b = QLayoutPrivate::createSpacerItem(this, size, 0, QSizePolicy::Fixed, QSizePolicy::Minimum);
     else
         b = QLayoutPrivate::createSpacerItem(this, 0, size, QSizePolicy::Minimum, QSizePolicy::Fixed);
     QT_TRY {
         QBoxLayoutItem *it = new QBoxLayoutItem(b);
         it->magic = true;
         d->list.insert(index, it);
     } QT_CATCH(...) {
         delete b;
         QT_RETHROW;
     }
     invalidate();
 }
insertStretch()
void QBoxLayout::insertStretch (int index, int stretch = 0)
Inserts a stretchable space (a QSpacerItem) at position index, with zero minimum size and stretch factor stretch.
If index is negative the space is added at the end.
See also
addStretch(), insertItem(), QSpacerItem
Definition at line 960 of file qboxlayout.cpp.
Referenced by addStretch(), and QCalendarWidgetPrivate::createNavigationBar().
 {
     Q_D(QBoxLayout);
     if (index < 0)                                // append
         index = d->list.count();
     QLayoutItem *b;
     if (horz(d->dir))
         b = QLayoutPrivate::createSpacerItem(this, 0, 0, QSizePolicy::Expanding, QSizePolicy::Minimum);
     else
         b = QLayoutPrivate::createSpacerItem(this, 0, 0, QSizePolicy::Minimum, QSizePolicy::Expanding);
     QBoxLayoutItem *it = new QBoxLayoutItem(b, stretch);
     it->magic = true;
     d->list.insert(index, it);
     invalidate();
 }
insertWidget()
void QBoxLayout::insertWidget (int index, QWidget * widget, int stretch = 0, Qt::Alignment alignment = 0)
Inserts widget at position index, with stretch factor stretch and alignment alignment.
If index is negative, the widget is added at the end.
The stretch factor applies only in the direction of the QBoxLayout, and is relative to the other boxes and widgets in this QBoxLayout. Widgets and boxes with higher stretch factors grow more.
If the stretch factor is 0 and nothing else in the QBoxLayout has a stretch factor greater than zero, the space is distributed according to the QWidget:sizePolicy() of each widget that's involved.
The alignment is specified by alignment. The default alignment is 0, which means that the widget fills the entire cell.
See also
addWidget(), insertItem()
Definition at line 1042 of file qboxlayout.cpp.
Referenced by addWidget(), QComboBoxPrivateContainer::QComboBoxPrivateContainer(), QAbstractScrollAreaPrivate::replaceScrollBar(), and QInputDialogPrivate::setInputWidget().
 {
     Q_D(QBoxLayout);
     if (!checkWidget(this, widget))
          return;
     addChildWidget(widget);
     if (index < 0)                                // append
         index = d->list.count();
     QWidgetItem *b = QLayoutPrivate::createWidgetItem(this, widget);
     b->setAlignment(alignment);
     QBoxLayoutItem *it;
     QT_TRY{
         it = new QBoxLayoutItem(b, stretch);
     } QT_CATCH(...) {
         delete b;
         QT_RETHROW;
     }
     QT_TRY{
         d->list.insert(index, it);
     } QT_CATCH(...) {
         delete it;
         QT_RETHROW;
     }
     invalidate();
 }
invalidate()
void QBoxLayout::invalidate () virtual
Resets cached information.
Reimplemented from QLayoutItem.
Definition at line 759 of file qboxlayout.cpp.
Referenced by addItem(), addStrut(), insertItem(), insertLayout(), insertSpacerItem(), insertSpacing(), insertStretch(), insertWidget(), setDirection(), setSpacing(), setStretch(), setStretchFactor(), takeAt(), and QComboBoxPrivateContainer::updateTopBottomMargin().
 {
     Q_D(QBoxLayout);
     d->setDirty();
     QLayout::invalidate();
 }
itemAt()
QLayoutItem * QBoxLayout::itemAt (int index) const virtual
Reimplemented Function
Implements QLayout.
Definition at line 778 of file qboxlayout.cpp.
Referenced by QDialogButtonBoxPrivate::layoutButtons(), and QComboBoxPrivateContainer::updateTopBottomMargin().
 {
     Q_D(const QBoxLayout);
     return index >= 0 && index < d->list.count() ? d->list.at(index)->item : 0;
 }
maximumSize()
QSize QBoxLayout::maximumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 699 of file qboxlayout.cpp.
 {
     Q_D(const QBoxLayout);
     if (d->dirty)
         const_cast<QBoxLayout*>(this)->d_func()->setupGeom();
     QSize s = d->maxSize.boundedTo(QSize(QLAYOUTSIZE_MAX, QLAYOUTSIZE_MAX));
     if (alignment() & Qt::AlignHorizontal_Mask)
         s.setWidth(QLAYOUTSIZE_MAX);
     if (alignment() & Qt::AlignVertical_Mask)
         s.setHeight(QLAYOUTSIZE_MAX);
     return s;
 }
minimumHeightForWidth()
int QBoxLayout::minimumHeightForWidth (int w) const virtual
Reimplemented Function
Reimplemented from QLayoutItem.
Definition at line 747 of file qboxlayout.cpp.
 {
     Q_D(const QBoxLayout);
     (void) heightForWidth(w);
     int top, bottom;
     d->effectiveMargins(0, &top, 0, &bottom);
     return d->hasHfw ? (d->hfwMinHeight + top + bottom) : -1;
 }
minimumSize()
QSize QBoxLayout::minimumSize () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 688 of file qboxlayout.cpp.
 {
     Q_D(const QBoxLayout);
     if (d->dirty)
         const_cast<QBoxLayout*>(this)->d_func()->setupGeom();
     return d->minSize;
 }
setDirection()
void QBoxLayout::setDirection (Direction direction)
Sets the direction of this layout to direction.
Definition at line 1257 of file qboxlayout.cpp.
 {
     Q_D(QBoxLayout);
     if (d->dir == direction)
         return;
     if (horz(d->dir) != horz(direction)) {
         //swap around the spacers (the "magic" bits)
         //#### a bit yucky, knows too much.
         //#### probably best to add access functions to spacerItem
         //#### or even a QSpacerItem::flip()
         for (int i = 0; i < d->list.size(); ++i) {
             QBoxLayoutItem *box = d->list.at(i);
             if (box->magic) {
                 QSpacerItem *sp = box->item->spacerItem();
                 if (sp) {
                     if (sp->expandingDirections() == Qt::Orientations(0) /*No Direction*/) {
                         //spacing or strut
                         QSize s = sp->sizeHint();
                         sp->changeSize(s.height(), s.width(),
                             horz(direction) ? QSizePolicy::Fixed:QSizePolicy::Minimum,
                             horz(direction) ? QSizePolicy::Minimum:QSizePolicy::Fixed);
                     } else {
                         //stretch
                         if (horz(direction))
                             sp->changeSize(0, 0, QSizePolicy::Expanding,
                                             QSizePolicy::Minimum);
                         else
                             sp->changeSize(0, 0, QSizePolicy::Minimum,
                                             QSizePolicy::Expanding);
                     }
                 }
             }
         }
     }
     d->dir = direction;
     invalidate();
 }
setGeometry()
void QBoxLayout::setGeometry (const QRect & r) virtual
Reimplemented Function
Reimplemented from QLayout.
Definition at line 822 of file qboxlayout.cpp.
 {
     Q_D(QBoxLayout);
     if (d->dirty || r != geometry()) {
         QRect oldRect = geometry();
         QLayout::setGeometry(r);
         if (d->dirty)
             d->setupGeom();
         QRect cr = alignment() ? alignmentRect(r) : r;
         int left, top, right, bottom;
         d->effectiveMargins(&left, &top, &right, &bottom);
         QRect s(cr.x() + left, cr.y() + top,
                 cr.width() - (left + right),
                 cr.height() - (top + bottom));
         QVector<QLayoutStruct> a = d->geomArray;
         int pos = horz(d->dir) ? s.x() : s.y();
         int space = horz(d->dir) ? s.width() : s.height();
         int n = a.count();
         if (d->hasHfw && !horz(d->dir)) {
             for (int i = 0; i < n; i++) {
                 QBoxLayoutItem *box = d->list.at(i);
                 if (box->item->hasHeightForWidth()) {
                     int width = qBound(box->item->minimumSize().width(), s.width(), box->item->maximumSize().width());
                     a[i].sizeHint = a[i].minimumSize =
                                     box->item->heightForWidth(width);
                 }
             }
         }
         Direction visualDir = d->dir;
         QWidget *parent = parentWidget();
         if (parent && parent->isRightToLeft()) {
             if (d->dir == LeftToRight)
                 visualDir = RightToLeft;
             else if (d->dir == RightToLeft)
                 visualDir = LeftToRight;
         }
         qGeomCalc(a, 0, n, pos, space);
         bool reverse = (horz(visualDir)
                         ? ((r.right() > oldRect.right()) != (visualDir == RightToLeft))
                         : r.bottom() > oldRect.bottom());
         for (int j = 0; j < n; j++) {
             int i = reverse ? n-j-1 : j;
             QBoxLayoutItem *box = d->list.at(i);
             switch (visualDir) {
             case LeftToRight:
                 box->item->setGeometry(QRect(a.at(i).pos, s.y(), a.at(i).size, s.height()));
                 break;
             case RightToLeft:
                 box->item->setGeometry(QRect(s.left() + s.right() - a.at(i).pos - a.at(i).size + 1,
                                              s.y(), a.at(i).size, s.height()));
                 break;
             case TopToBottom:
                 box->item->setGeometry(QRect(s.x(), a.at(i).pos, s.width(), a.at(i).size));
                 break;
             case BottomToTop:
                 box->item->setGeometry(QRect(s.x(),
                                              s.top() + s.bottom() - a.at(i).pos - a.at(i).size + 1,
                                              s.width(), a.at(i).size));
             }
         }
     }
 }
setSpacing()
void QBoxLayout::setSpacing (int spacing)
Reimplements QLayout::setSpacing().
Sets the spacing property to spacing.
See also
QLayout::setSpacing(), spacing()
Definition at line 667 of file qboxlayout.cpp.
Referenced by QCalendarWidgetPrivate::createNavigationBar(), QBoxLayout(), QCalendarWidget::QCalendarWidget(), QComboBoxPrivateContainer::QComboBoxPrivateContainer(), QHBoxLayout::QHBoxLayout(), QScriptDebuggerCodeFinderWidget::QScriptDebuggerCodeFinderWidget(), QScriptDebuggerConsoleWidget::QScriptDebuggerConsoleWidget(), QScriptDebugOutputWidget::QScriptDebugOutputWidget(), QScriptErrorLogWidget::QScriptErrorLogWidget(), QScriptNewBreakpointWidget::QScriptNewBreakpointWidget(), QVBoxLayout::QVBoxLayout(), QStatusBar::reformat(), and QCalendarPopup::setCalendarWidget().
 {
     Q_D(QBoxLayout);
     d->spacing = spacing;
     invalidate();
 }
setStretch()
void QBoxLayout::setStretch (int index, int stretch)
Sets the stretch factor at position index.
to stretch.
Since
4.5
Definition at line 1228 of file qboxlayout.cpp.
 {
     Q_D(QBoxLayout);
     if (index >= 0 && index < d->list.size()) {
         QBoxLayoutItem *box = d->list.at(index);
         if (box->stretch != stretch) {
             box->stretch = stretch;
             invalidate();
         }
     }
 }
setStretchFactor() [1/2]
bool QBoxLayout::setStretchFactor (QWidget * widget, int stretch)
Sets the stretch factor for widget to stretch and returns true if widget is found in this layout (not including child layouts); otherwise returns false.
See also
setAlignment()
Definition at line 1180 of file qboxlayout.cpp.
 {
     Q_D(QBoxLayout);
     if (!widget)
         return false;
     for (int i = 0; i < d->list.size(); ++i) {
         QBoxLayoutItem *box = d->list.at(i);
         if (box->item->widget() == widget) {
             box->stretch = stretch;
             invalidate();
             return true;
         }
     }
     return false;
 }
setStretchFactor() [2/2]
bool QBoxLayout::setStretchFactor (QLayout * layout, int stretch)
Sets the stretch factor for the layout layout to stretch and returns true if layout is found in this layout (not including child layouts); otherwise returns false.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1206 of file qboxlayout.cpp.
 {
     Q_D(QBoxLayout);
     for (int i = 0; i < d->list.size(); ++i) {
         QBoxLayoutItem *box = d->list.at(i);
         if (box->item->layout() == layout) {
             if (box->stretch != stretch) {
                 box->stretch = stretch;
                 invalidate();
             }
             return true;
         }
     }
     return false;
 }
sizeHint()
QSize QBoxLayout::sizeHint () const virtual
Reimplemented Function
Implements QLayoutItem.
Definition at line 677 of file qboxlayout.cpp.
 {
     Q_D(const QBoxLayout);
     if (d->dirty)
         const_cast<QBoxLayout*>(this)->d_func()->setupGeom();
     return d->sizeHint;
 }
spacing()
int QBoxLayout::spacing () const
Reimplements QLayout::spacing().
If the spacing property is valid, that value is returned. Otherwise, a value for the spacing property is computed and returned. Since layout spacing in a widget is style dependent, if the parent is a widget, it queries the style for the (horizontal or vertical) spacing of the layout. Otherwise, the parent is a layout, and it queries the parent layout for the spacing().
See also
QLayout::spacing(), setSpacing()
Definition at line 649 of file qboxlayout.cpp.
Referenced by QColorDialogPrivate::init(), QBoxLayout(), QHBoxLayout::QHBoxLayout(), QVBoxLayout::QVBoxLayout(), and setSpacing().
 {
     Q_D(const QBoxLayout);
     if (d->spacing >=0) {
         return d->spacing;
     } else {
         return qSmartSpacing(this, d->dir == LeftToRight || d->dir == RightToLeft
                                            ? QStyle::PM_LayoutHorizontalSpacing
                                            : QStyle::PM_LayoutVerticalSpacing);
     }
 }
stretch()
int QBoxLayout::stretch (int index) const
Returns the stretch factor at position index.
Since
4.5
Definition at line 1246 of file qboxlayout.cpp.
Referenced by setStretch(), and setStretchFactor().
 {
     Q_D(const QBoxLayout);
     if (index >= 0 && index < d->list.size())
         return d->list.at(index)->stretch;
     return -1;
 }
takeAt()
QLayoutItem * QBoxLayout::takeAt (int index) virtual
Reimplemented Function
Implements QLayout.
Definition at line 787 of file qboxlayout.cpp.
Referenced by QDialogButtonBoxPrivate::layoutButtons().
 {
     Q_D(QBoxLayout);
     if (index < 0 || index >= d->list.count())
         return 0;
     QBoxLayoutItem *b = d->list.takeAt(index);
     QLayoutItem *item = b->item;
     b->item = 0;
     delete b;
     if (QLayout *l = item->layout()) {
         // sanity check in case the user passed something weird to QObject::setParent()
         if (l->parent() == this)
             l->setParent(0);
     }
     invalidate();
     return item;
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qboxlayout.h
/src/gui/kernel/qboxlayout.cpp