Qt 4.8: FxGridItem Class Reference
FxGridItem Class Reference
Public Functions
qreal colPos () const
bool contains (qreal x, qreal y) const
qreal endRowPos () const
FxGridItem (QDeclarativeItem *i, QDeclarativeGridView *v)
qreal rowPos () const
void setPosition (qreal col, qreal row)
~FxGridItem ()
Public Variables
QDeclarativeGridViewAttached * attached
int index
QDeclarativeItem * item
QDeclarativeGridView * view
Detailed Description
Definition at line 65 of file qdeclarativegridview.cpp.
Constructors and Destructors
FxGridItem()
FxGridItem::FxGridItem (QDeclarativeItem * i, QDeclarativeGridView * v) inline
Definition at line 68 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridViewPrivate::createHighlight(), QDeclarativeGridViewPrivate::createItem(), QDeclarativeGridViewPrivate::updateFooter(), and QDeclarativeGridViewPrivate::updateHeader().
                                                              : item(i), view(v) {
         attached = static_cast<QDeclarativeGridViewAttached*>(qmlAttachedPropertiesObject<QDeclarativeGridView>(item));
         if (attached)
             attached->setView(view);
     }
~FxGridItem()
FxGridItem::~FxGridItem () inline
Definition at line 73 of file qdeclarativegridview.cpp.
 {}
Functions
colPos()
qreal FxGridItem::colPos () const inline
Definition at line 87 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridViewPrivate::colPosAt(), QDeclarativeGridView::itemsMoved(), QDeclarativeGridViewPrivate::layout(), QDeclarativeGridViewPrivate::refill(), and QDeclarativeGridViewPrivate::snapIndex().
{
         qreal colPos = 0;
         if (view->flow() == QDeclarativeGridView::LeftToRight) {
             if (view->effectiveLayoutDirection() == Qt::RightToLeft) {
                 int colSize = view->cellWidth();
                 int columns = view->width()/colSize;
                 colPos = colSize * (columns-1) - item->x();
             } else {
                 colPos = item->x();
             }
         } else {
             colPos = item->y();
         }
         return colPos;
     }
contains()
bool FxGridItem::contains (qreal x, qreal y) const inline
Definition at line 130 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridView::indexAt().
{
         return (x >= item->x() && x < item->x() + view->cellWidth() &&
                 y >= item->y() && y < item->y() + view->cellHeight());
     }
endRowPos()
qreal FxGridItem::endRowPos () const inline
Definition at line 104 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridViewPrivate::firstVisibleItem(), QDeclarativeGridViewPrivate::positionViewAtIndex(), and QDeclarativeGridViewPrivate::updateFooter().
{
         if (view->flow() == QDeclarativeGridView::LeftToRight) {
             return item->y() + view->cellHeight() - 1;
         } else {
             if (view->effectiveLayoutDirection() == Qt::RightToLeft)
                 return -item->x() - 1;
             else
                 return item->x() + view->cellWidth() - 1;
         }
     }
rowPos()
qreal FxGridItem::rowPos () const inline
Definition at line 75 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridViewPrivate::fixup(), QDeclarativeGridView::itemsMoved(), QDeclarativeGridViewPrivate::layout(), QDeclarativeGridViewPrivate::positionViewAtIndex(), QDeclarativeGridViewPrivate::refill(), QDeclarativeGridViewPrivate::rowPosAt(), QDeclarativeGridViewPrivate::snapIndex(), and QDeclarativeGridViewPrivate::snapItemAt().
{
         qreal rowPos = 0;
         if (view->flow() == QDeclarativeGridView::LeftToRight) {
             rowPos = item->y();
         } else {
             if (view->effectiveLayoutDirection() == Qt::RightToLeft)
                 rowPos = -view->cellWidth()-item->x();
             else
                 rowPos = item->x();
         }
         return rowPos;
     }
setPosition()
void FxGridItem::setPosition (qreal col, qreal row) inline
Definition at line 114 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridView::itemsInserted(), QDeclarativeGridView::itemsMoved(), QDeclarativeGridViewPrivate::layout(), QDeclarativeGridViewPrivate::refill(), and QDeclarativeGridViewPrivate::regenerate().
{
         if (view->effectiveLayoutDirection() == Qt::RightToLeft) {
             if (view->flow() == QDeclarativeGridView::LeftToRight) {
                 int columns = view->width()/view->cellWidth();
                 item->setPos(QPointF((view->cellWidth() * (columns-1) - col), row));
             } else {
                 item->setPos(QPointF(-view->cellWidth()-row, col));
             }
         } else {
             if (view->flow() == QDeclarativeGridView::LeftToRight)
                 item->setPos(QPointF(col, row));
             else
                 item->setPos(QPointF(row, col));
         }
     }
Properties
attached
QDeclarativeGridViewAttached* FxGridItem::attached
Definition at line 137 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridView::destroyRemoved(), FxGridItem(), QDeclarativeGridView::itemsInserted(), QDeclarativeGridView::itemsRemoved(), QDeclarativeGridViewPrivate::refill(), and QDeclarativeGridViewPrivate::updateCurrent().
index
int FxGridItem::index
Definition at line 138 of file qdeclarativegridview.cpp.
Referenced by QDeclarativeGridViewPrivate::checkVisible(), QDeclarativeGridViewPrivate::createItem(), QDeclarativeGridView::destroyRemoved(), QDeclarativeGridViewPrivate::firstVisibleItem(), QDeclarativeGridViewPrivate::fixup(), QDeclarativeGridView::indexAt(), QDeclarativeGridViewPrivate::itemGeometryChanged(), QDeclarativeGridView::itemsInserted(), QDeclarativeGridView::itemsMoved(), QDeclarativeGridView::itemsRemoved(), QDeclarativeGridViewPrivate::lastVisibleIndex(), QDeclarativeGridViewPrivate::mapFromModel(), QDeclarativeGridViewPrivate::refill(), QDeclarativeGridViewPrivate::snapIndex(), QDeclarativeGridViewPrivate::snapItemAt(), and QDeclarativeGridViewPrivate::visibleItem().
item
QDeclarativeItem* FxGridItem::item
Definition at line 135 of file qdeclarativegridview.cpp.
Referenced by colPos(), contains(), QDeclarativeGridViewPrivate::createComponentItem(), QDeclarativeGridViewPrivate::createHighlight(), QDeclarativeGridViewPrivate::createItem(), endRowPos(), FxGridItem(), QDeclarativeGridView::itemsMoved(), QDeclarativeGridViewPrivate::layout(), QDeclarativeGridViewPrivate::QDeclarativeGridViewPrivate(), QDeclarativeGridViewPrivate::refill(), QDeclarativeGridViewPrivate::releaseItem(), rowPos(), setPosition(), QDeclarativeGridViewPrivate::snapItemAt(), QDeclarativeGridViewPrivate::updateCurrent(), QDeclarativeGridViewPrivate::updateFooter(), QDeclarativeGridViewPrivate::updateHeader(), QDeclarativeGridViewPrivate::updateTrackedItem(), QDeclarativeGridViewPrivate::updateUnrequestedPositions(), and QDeclarativeGridViewPrivate::visibleItem().
view
QDeclarativeGridView* FxGridItem::view
Definition at line 136 of file qdeclarativegridview.cpp.
Referenced by colPos(), contains(), endRowPos(), FxGridItem(), rowPos(), and setPosition().
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativegridview.cpp