Qt 4.8: QXmlTestLogger Class Reference
QXmlTestLogger Class Reference
#include <qxmltestlogger_p.h>
Public Types
enum XmlMode { Complete = 0, Light }
Public Types inherited from QAbstractTestLogger
enum IncidentTypes { Pass, XFail, Fail, XPass }
enum MessageTypes {
Warn, QWarning, QDebug, QSystem,
QFatal, Skip, Info
}
Public Functions
void addBenchmarkResult (const QBenchmarkResult &result)
void addIncident (IncidentTypes type, const char *description, const char *file=0, int line=0)
void addMessage (MessageTypes type, const char *message, const char *file=0, int line=0)
void enterTestFunction (const char *function)
void leaveTestFunction ()
QXmlTestLogger (XmlMode mode=Complete)
void registerRandomSeed (unsigned int seed)
void startLogging ()
void stopLogging ()
~QXmlTestLogger ()
Public Functions inherited from QAbstractTestLogger
QAbstractTestLogger ()
virtual ~QAbstractTestLogger ()
Static Public Functions
static int xmlCdata (QTestCharBuffer *dest, char const *src)
static int xmlCdata (QTestCharBuffer *dest, char const *src, size_t n)
static int xmlQuote (QTestCharBuffer *dest, char const *src)
static int xmlQuote (QTestCharBuffer *dest, char const *src, size_t n)
Static Public Functions inherited from QAbstractTestLogger
static bool isTtyOutput ()
static void outputString (const char *msg)
Properties
bool hasRandomSeed
unsigned int randomSeed
XmlMode xmlmode
Detailed Description
Definition at line 61 of file qxmltestlogger_p.h.
Enumerations
XmlMode
enum QXmlTestLogger::XmlMode
Enumerator
Complete
Light
Definition at line 64 of file qxmltestlogger_p.h.
 { Complete = 0, Light };
Constructors and Destructors
QXmlTestLogger()
QXmlTestLogger::QXmlTestLogger (XmlMode mode = Complete)
Definition at line 95 of file qxmltestlogger.cpp.
     :xmlmode(mode), randomSeed(0), hasRandomSeed(false)
 {
 }
~QXmlTestLogger()
QXmlTestLogger::~QXmlTestLogger ()
Definition at line 101 of file qxmltestlogger.cpp.
 {
 }
Functions
addBenchmarkResult()
void QXmlTestLogger::addBenchmarkResult (const QBenchmarkResult & result) virtual
Implements QAbstractTestLogger.
Definition at line 249 of file qxmltestlogger.cpp.
 {
     QTestCharBuffer buf;
     QTestCharBuffer quotedMetric;
     QTestCharBuffer quotedTag;
     xmlQuote(&quotedMetric,
         benchmarkMetricName(result.metric));
     xmlQuote(&quotedTag, result.context.tag.toAscii().constData());
     QTest::qt_asprintf(
         &buf,
         QTest::benchmarkResultFormatString(),
         quotedMetric.constData(),
         quotedTag.constData(),
         QByteArray::number(result.value).constData(),  //no 64-bit qt_snprintf support
         result.iterations);
     outputString(buf.constData());
 }
addIncident()
void QXmlTestLogger::addIncident (IncidentTypes type, const char * description, const char * file = 0, int line = 0) virtual
Implements QAbstractTestLogger.
Definition at line 218 of file qxmltestlogger.cpp.
 {
     QTestCharBuffer buf;
     const char *tag = QTestResult::currentDataTag();
     const char *gtag = QTestResult::currentGlobalDataTag();
     const char *filler = (tag && gtag) ? ":" : "";
     const bool notag = QTest::isEmpty(tag) && QTest::isEmpty(gtag);
     QTestCharBuffer quotedFile;
     QTestCharBuffer cdataGtag;
     QTestCharBuffer cdataTag;
     QTestCharBuffer cdataDescription;
     xmlQuote(&quotedFile, file);
     xmlCdata(&cdataGtag, gtag);
     xmlCdata(&cdataTag, tag);
     xmlCdata(&cdataDescription, description);
     QTest::qt_asprintf(&buf,
             QTest::incidentFormatString(QTest::isEmpty(description), notag),
             QTest::xmlIncidentType2String(type),
             quotedFile.constData(), line,
             cdataGtag.constData(),
             filler,
             cdataTag.constData(),
             cdataDescription.constData());
     outputString(buf.constData());
 }
addMessage()
void QXmlTestLogger::addMessage (MessageTypes type, const char * message, const char * file = 0, int line = 0) virtual
Implements QAbstractTestLogger.
Definition at line 269 of file qxmltestlogger.cpp.
 {
     QTestCharBuffer buf;
     const char *tag = QTestResult::currentDataTag();
     const char *gtag = QTestResult::currentGlobalDataTag();
     const char *filler = (tag && gtag) ? ":" : "";
     const bool notag = QTest::isEmpty(tag) && QTest::isEmpty(gtag);
     QTestCharBuffer quotedFile;
     QTestCharBuffer cdataGtag;
     QTestCharBuffer cdataTag;
     QTestCharBuffer cdataDescription;
     xmlQuote(&quotedFile, file);
     xmlCdata(&cdataGtag, gtag);
     xmlCdata(&cdataTag, tag);
     xmlCdata(&cdataDescription, message);
     QTest::qt_asprintf(&buf,
             QTest::messageFormatString(QTest::isEmpty(message), notag),
             QTest::xmlMessageType2String(type),
             quotedFile.constData(), line,
             cdataGtag.constData(),
             filler,
             cdataTag.constData(),
             cdataDescription.constData());
     outputString(buf.constData());
 }
enterTestFunction()
void QXmlTestLogger::enterTestFunction (const char * function) virtual
Implements QAbstractTestLogger.
Definition at line 145 of file qxmltestlogger.cpp.
 {
     QTestCharBuffer buf;
     QTestCharBuffer quotedFunction;
     xmlQuote(&quotedFunction, function);
     QTest::qt_asprintf(&buf, "<TestFunction name=\"%s\">\n", quotedFunction.constData());
     outputString(buf.constData());
 }
leaveTestFunction()
void QXmlTestLogger::leaveTestFunction () virtual
Implements QAbstractTestLogger.
Definition at line 154 of file qxmltestlogger.cpp.
 {
     outputString("</TestFunction>\n");
 }
registerRandomSeed()
void QXmlTestLogger::registerRandomSeed (unsigned int seed) virtual
Implements QAbstractTestLogger.
Definition at line 453 of file qxmltestlogger.cpp.
 {
     randomSeed = seed;
     hasRandomSeed = true;
 }
startLogging()
void QXmlTestLogger::startLogging () virtual
Reimplemented from QAbstractTestLogger.
Definition at line 105 of file qxmltestlogger.cpp.
 {
     QAbstractTestLogger::startLogging();
     QTestCharBuffer buf;
     if (xmlmode == QXmlTestLogger::Complete) {
         QTestCharBuffer quotedTc;
         xmlQuote(&quotedTc, QTestResult::currentTestObjectName());
         QTest::qt_asprintf(&buf,
                 "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n"
                 "<TestCase name=\"%s\">\n", quotedTc.constData());
         outputString(buf.constData());
     }
     if (hasRandomSeed) {
        QTest::qt_asprintf(&buf,
                 "<Environment>\n"
                 "    <QtVersion>%s</QtVersion>\n"
                 "    <QTestVersion>" QTEST_VERSION_STR "</QTestVersion>\n"
                 "    <RandomSeed>%d</RandomSeed>\n"
                 "</Environment>\n", qVersion(), randomSeed);
     } else {
        QTest::qt_asprintf(&buf,
                 "<Environment>\n"
                 "    <QtVersion>%s</QtVersion>\n"
                 "    <QTestVersion>" QTEST_VERSION_STR "</QTestVersion>\n"
                 "</Environment>\n", qVersion());
     }
     outputString(buf.constData());
 }
stopLogging()
void QXmlTestLogger::stopLogging () virtual
Reimplemented from QAbstractTestLogger.
Definition at line 136 of file qxmltestlogger.cpp.
 {
     if (xmlmode == QXmlTestLogger::Complete) {
         outputString("</TestCase>\n");
     }
     QAbstractTestLogger::stopLogging();
 }
xmlCdata() [1/2]
int QXmlTestLogger::xmlCdata (QTestCharBuffer * dest, char const * src) static
Definition at line 448 of file qxmltestlogger.cpp.
Referenced by addIncident(), addMessage(), QTestXunitStreamer::formatAttributes(), QTestLightXmlStreamer::formatStart(), and QTestXmlStreamer::formatStart().
 {
     return allocateStringFn(str, src, QXmlTestLogger::xmlCdata);
 }
xmlCdata() [2/2]
int QXmlTestLogger::xmlCdata (QTestCharBuffer * dest, char const * src, size_t n) static
Definition at line 365 of file qxmltestlogger.cpp.
 {
     if (!n) return 0;
     char *dest = destBuf->data();
     if (!src || n == 1) {
         *dest = 0;
         return 0;
     }
     static char const CDATA_END[] = "]]>";
     static char const CDATA_END_ESCAPED[] = "]]]><![CDATA[]>";
     char* begin = dest;
     char* end = dest + n;
     while (dest < end) {
         if (!*src) {
             *dest = 0;
             return (dest-begin);
         }
         if (!strncmp(src, CDATA_END, sizeof(CDATA_END)-1)) {
             if (dest + sizeof(CDATA_END_ESCAPED) < end) {
                 strcpy(dest, CDATA_END_ESCAPED);
                 src += sizeof(CDATA_END)-1;
                 dest += sizeof(CDATA_END_ESCAPED) - 1;
             }
             else {
                 *dest = 0;
                 return (dest+sizeof(CDATA_END_ESCAPED)-begin);
             }
             continue;
         }
         *dest = *src;
         ++src;
         ++dest;
     }
     // If we get here, dest was completely filled (dest == end)
     *(dest-1) = 0;
     return (dest-begin);
 }
xmlQuote() [1/2]
int QXmlTestLogger::xmlQuote (QTestCharBuffer * dest, char const * src) static
Definition at line 443 of file qxmltestlogger.cpp.
Referenced by addBenchmarkResult(), addIncident(), addMessage(), enterTestFunction(), QTestXunitStreamer::formatAttributes(), QTestLightXmlStreamer::formatBeforeAttributes(), QTestLightXmlStreamer::formatStart(), QTestXmlStreamer::formatStart(), QTestXmlStreamer::output(), and startLogging().
 {
     return allocateStringFn(str, src, QXmlTestLogger::xmlQuote);
 }
xmlQuote() [2/2]
int QXmlTestLogger::xmlQuote (QTestCharBuffer * dest, char const * src, size_t n) static
Definition at line 305 of file qxmltestlogger.cpp.
 {
     if (n == 0) return 0;
     char *dest = destBuf->data();
     *dest = 0;
     if (!src) return 0;
     char* begin = dest;
     char* end = dest + n;
     while (dest < end) {
         switch (*src) {
 #define MAP_ENTITY(chr, ent) \
             case chr:                                   \
                 if (dest + sizeof(ent) < end) {         \
                     strcpy(dest, ent);                  \
                     dest += sizeof(ent) - 1;            \
                 }                                       \
                 else {                                  \
                     *dest = 0;                          \
                     return (dest+sizeof(ent)-begin);    \
                 }                                       \
                 ++src;                                  \
                 break;
             MAP_ENTITY('>', "&gt;");
             MAP_ENTITY('<', "&lt;");
             MAP_ENTITY('\'', "&apos;");
             MAP_ENTITY('"', "&quot;");
             MAP_ENTITY('&', "&amp;");
             // not strictly necessary, but allows handling of comments without
             // having to explicitly look for `--'
             MAP_ENTITY('-', "&#x002D;");
 #undef MAP_ENTITY
             case 0:
                 *dest = 0;
                 return (dest-begin);
             default:
                 *dest = *src;
                 ++dest;
                 ++src;
                 break;
         }
     }
     // If we get here, dest was completely filled (dest == end)
     *(dest-1) = 0;
     return (dest-begin);
 }
Properties
hasRandomSeed
bool QXmlTestLogger::hasRandomSeed private
Definition at line 92 of file qxmltestlogger_p.h.
Referenced by registerRandomSeed(), and startLogging().
randomSeed
unsigned int QXmlTestLogger::randomSeed private
Definition at line 91 of file qxmltestlogger_p.h.
Referenced by registerRandomSeed(), and startLogging().
xmlmode
XmlMode QXmlTestLogger::xmlmode private
Definition at line 90 of file qxmltestlogger_p.h.
Referenced by startLogging(), and stopLogging().
The documentation for this class was generated from the following files:
/src/testlib/qxmltestlogger_p.h
/src/testlib/qxmltestlogger.cpp