Qt 4.8: QScrollArea Class Reference
QScrollArea Class Reference
The QScrollArea class provides a scrolling view onto another widget.
#include <qscrollarea.h>
Public Functions
Qt::Alignment alignment () const
void ensureVisible (int x, int y, int xmargin=50, int ymargin=50)
Scrolls the contents of the scroll area so that the point (x, y) is visible inside the region of the viewport with margins specified in pixels by xmargin and ymargin.
void ensureWidgetVisible (QWidget *childWidget, int xmargin=50, int ymargin=50)
Scrolls the contents of the scroll area so that the childWidget of QScrollArea::widget() is visible inside the viewport with margins specified in pixels by xmargin and ymargin.
bool focusNextPrevChild (bool next)
Reimplemented Function
QScrollArea (QWidget *parent=0)
Constructs an empty scroll area with the given parent.
void setAlignment (Qt::Alignment)
void setWidget (QWidget *widget)
Sets the scroll area's widget.
void setWidgetResizable (bool resizable)
QSize sizeHint () const
Reimplemented Function
QWidget * takeWidget ()
Removes the scroll area's widget, and passes ownership of the widget to the caller.
QWidget * widget () const
Returns the scroll area's widget, or 0 if there is none.
bool widgetResizable () const
~QScrollArea ()
Destroys the scroll area and its child widget.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
bool event (QEvent *)
Reimplemented Function
bool eventFilter (QObject *, QEvent *)
Reimplemented Function
QScrollArea (QScrollAreaPrivate &dd, QWidget *parent=0)
void resizeEvent (QResizeEvent *)
Reimplemented Function
void scrollContentsBy (int dx, int dy)
This virtual handler is called when the scroll bars are moved by dx, dy, and consequently the viewport's contents should be scrolled accordingly.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
virtual bool viewportEvent (QEvent *)
The main event handler for the scrolling area (the viewport() widget).
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
Qt::Alignment alignment
the alignment of the scroll area's widget
bool widgetResizable
whether the scroll area should resize the view widget
Additional Inherited Members
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QScrollArea class provides a scrolling view onto another widget.
A scroll area is used to display the contents of a child widget within a frame. If the widget exceeds the size of the frame, the view can provide scroll bars so that the entire area of the child widget can be viewed. The child widget must be specified with setWidget(). For example:
QLabel *imageLabel = new QLabel;
QImage image("happyguy.png");
imageLabel->setPixmap(QPixmap::fromImage(image));
scrollArea = new QScrollArea;
scrollArea->setBackgroundRole(QPalette::Dark);
scrollArea->setWidget(imageLabel);
The code above creates a scroll area (shown in the images below) containing an image label. When scaling the image, the scroll area can provide the necessary scroll bars:
The scroll bars appearance depends on the currently set Qt::ScrollBarPolicy . You can control the appearance of the scroll bars using the inherited functionality from QAbstractScrollArea.
For example, you can set the QAbstractScrollArea::horizontalScrollBarPolicy and QAbstractScrollArea::verticalScrollBarPolicy properties. Or if you want the scroll bars to adjust dynamically when the contents of the scroll area changes, you can use the QAbstractScrollArea::horizontalScrollBar() and QAbstractScrollArea::verticalScrollBar() functions (which enable you to access the scroll bars) and set the scroll bars' values whenever the scroll area's contents change, using the QScrollBar::setValue() function.
You can retrieve the child widget using the widget() function. The view can be made to be resizable with the setWidgetResizable() function. The alignment of the widget can be specified with setAlignment().
Two convenience functions ensureVisible() and ensureWidgetVisible() ensure a certain region of the contents is visible inside the viewport, by scrolling the contents if necessary.
Size Hints and Layouts
When using a scroll area to display the contents of a custom widget, it is important to ensure that the size hint of the child widget is set to a suitable value. If a standard QWidget is used for the child widget, it may be necessary to call QWidget::setMinimumSize() to ensure that the contents of the widget are shown correctly within the scroll area.
If a scroll area is used to display the contents of a widget that contains child widgets arranged in a layout, it is important to realize that the size policy of the layout will also determine the size of the widget. This is especially useful to know if you intend to dynamically change the contents of the layout. In such cases, setting the layout's size constraint property to one which provides constraints on the minimum and/or maximum size of the layout (e.g., QLayout::SetMinAndMaxSize) will cause the size of the scroll area to be updated whenever the contents of the layout changes.
For a complete example using the QScrollArea class, see the Image Viewer example. The example shows how to combine QLabel and QScrollArea to display an image.
See also
QAbstractScrollArea, QScrollBar, {Image Viewer Example}
Definition at line 57 of file qscrollarea.h.
Constructors and Destructors
QScrollArea() [1/2]
QScrollArea::QScrollArea (QWidget * parent = 0) explicit
Constructs an empty scroll area with the given parent.
See also
setWidget()
Definition at line 145 of file qscrollarea.cpp.
     : QAbstractScrollArea(*new QScrollAreaPrivate,parent)
 {
     Q_D(QScrollArea);
     d->viewport->setBackgroundRole(QPalette::NoRole);
     d->vbar->setSingleStep(20);
     d->hbar->setSingleStep(20);
     d->layoutChildren();
 }
~QScrollArea()
QScrollArea::~QScrollArea ()
Destroys the scroll area and its child widget.
See also
setWidget()
Definition at line 173 of file qscrollarea.cpp.
 {
 }
QScrollArea() [2/2]
QScrollArea::QScrollArea (QScrollAreaPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 158 of file qscrollarea.cpp.
     : QAbstractScrollArea(dd, parent)
 {
     Q_D(QScrollArea);
     d->viewport->setBackgroundRole(QPalette::NoRole);
     d->vbar->setSingleStep(20);
     d->hbar->setSingleStep(20);
     d->layoutChildren();
 }
Functions
alignment()
Qt::Alignment QScrollArea::alignment () const
Referenced by setAlignment(), and QScrollAreaPrivate::updateWidgetPosition().
ensureVisible()
void QScrollArea::ensureVisible (int x, int y, int xmargin = 50, int ymargin = 50)
Scrolls the contents of the scroll area so that the point (x, y) is visible inside the region of the viewport with margins specified in pixels by xmargin and ymargin.
If the specified point cannot be reached, the contents are scrolled to the nearest valid position. The default value for both margins is 50 pixels.
Definition at line 433 of file qscrollarea.cpp.
 {
     Q_D(QScrollArea);
     int logicalX = QStyle::visualPos(layoutDirection(), d->viewport->rect(), QPoint(x, y)).x();
     if (logicalX - xmargin < d->hbar->value()) {
         d->hbar->setValue(qMax(0, logicalX - xmargin));
     } else if (logicalX > d->hbar->value() + d->viewport->width() - xmargin) {
         d->hbar->setValue(qMin(logicalX - d->viewport->width() + xmargin, d->hbar->maximum()));
     }
     if (y - ymargin < d->vbar->value()) {
         d->vbar->setValue(qMax(0, y - ymargin));
     } else if (y > d->vbar->value() + d->viewport->height() - ymargin) {
         d->vbar->setValue(qMin(y - d->viewport->height() + ymargin, d->vbar->maximum()));
     }
 }
ensureWidgetVisible()
void QScrollArea::ensureWidgetVisible (QWidget * childWidget, int xmargin = 50, int ymargin = 50)
Scrolls the contents of the scroll area so that the childWidget of QScrollArea::widget() is visible inside the viewport with margins specified in pixels by xmargin and ymargin.
Since
4.2
If the specified point cannot be reached, the contents are scrolled to the nearest valid position. The default value for both margins is 50 pixels.
Definition at line 466 of file qscrollarea.cpp.
Referenced by eventFilter(), and focusNextPrevChild().
 {
     Q_D(QScrollArea);
     if (!d->widget->isAncestorOf(childWidget))
         return;
     const QRect microFocus = childWidget->inputMethodQuery(Qt::ImMicroFocus).toRect();
     const QRect defaultMicroFocus =
         childWidget->QWidget::inputMethodQuery(Qt::ImMicroFocus).toRect();
     QRect focusRect = (microFocus != defaultMicroFocus)
         ? QRect(childWidget->mapTo(d->widget, microFocus.topLeft()), microFocus.size())
         : QRect(childWidget->mapTo(d->widget, QPoint(0,0)), childWidget->size());
     const QRect visibleRect(-d->widget->pos(), d->viewport->size());
     if (visibleRect.contains(focusRect))
         return;
     focusRect.adjust(-xmargin, -ymargin, xmargin, ymargin);
     if (focusRect.width() > visibleRect.width())
         d->hbar->setValue(focusRect.center().x() - d->viewport->width() / 2);
     else if (focusRect.right() > visibleRect.right())
         d->hbar->setValue(focusRect.right() - d->viewport->width());
     else if (focusRect.left() < visibleRect.left())
         d->hbar->setValue(focusRect.left());
     if (focusRect.height() > visibleRect.height())
         d->vbar->setValue(focusRect.center().y() - d->viewport->height() / 2);
     else if (focusRect.bottom() > visibleRect.bottom())
         d->vbar->setValue(focusRect.bottom() - d->viewport->height());
     else if (focusRect.top() < visibleRect.top())
         d->vbar->setValue(focusRect.top());
 }
event()
bool QScrollArea::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 299 of file qscrollarea.cpp.
 {
     Q_D(QScrollArea);
     if (e->type() == QEvent::StyleChange || e->type() == QEvent::LayoutRequest) {
         d->updateScrollBars();
     }
 #ifdef QT_KEYPAD_NAVIGATION
     else if (QApplication::keypadNavigationEnabled()) {
         if (e->type() == QEvent::Show)
             QApplication::instance()->installEventFilter(this);
         else if (e->type() == QEvent::Hide)
             QApplication::instance()->removeEventFilter(this);
     }
 #endif
     return QAbstractScrollArea::event(e);
 }
eventFilter()
bool QScrollArea::eventFilter (QObject * o, QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 320 of file qscrollarea.cpp.
 {
     Q_D(QScrollArea);
 #ifdef QT_KEYPAD_NAVIGATION
     if (d->widget && o != d->widget && e->type() == QEvent::FocusIn
             && QApplication::keypadNavigationEnabled()) {
         if (o->isWidgetType())
             ensureWidgetVisible(static_cast<QWidget *>(o));
     }
 #endif
     if (o == d->widget && e->type() == QEvent::Resize)
         d->updateScrollBars();
     return false;
 }
focusNextPrevChild()
bool QScrollArea::focusNextPrevChild (bool next) virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 417 of file qscrollarea.cpp.
 {
     if (QWidget::focusNextPrevChild(next)) {
         if (QWidget *fw = focusWidget())
             ensureWidgetVisible(fw);
         return true;
     }
     return false;
 }
resizeEvent()
void QScrollArea::resizeEvent (QResizeEvent *) protected virtual
Reimplemented Function
em>Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 339 of file qscrollarea.cpp.
scrollContentsBy()
void QScrollArea::scrollContentsBy (int dx, int dy) protected virtual
This virtual handler is called when the scroll bars are moved by dx, dy, and consequently the viewport's contents should be scrolled accordingly.
The default implementation simply calls update() on the entire viewport(), subclasses can reimplement this handler for optimization purposes, or - like QScrollArea - to move a contents widget. The parameters dx and dy are there for convenience, so that the class knows how much should be scrolled (useful e.g. when doing pixel-shifts). You may just as well ignore these values and scroll directly to the position the scroll bars indicate.
Calling this function in order to scroll programmatically is an error, use the scroll bars instead (e.g. by calling QScrollBar::setValue() directly).
Reimplemented from QAbstractScrollArea.
Definition at line 349 of file qscrollarea.cpp.
 {
     Q_D(QScrollArea);
     if (!d->widget)
         return;
     d->updateWidgetPosition();
 }
setAlignment()
void QScrollArea::setAlignment (Qt::Alignment alignment)
Definition at line 514 of file qscrollarea.cpp.
 {
     Q_D(QScrollArea);
     d->alignment = alignment;
     if (d->widget)
         d->updateWidgetPosition();
 }
setWidget()
void QScrollArea::setWidget (QWidget * widget)
Sets the scroll area's widget.
The widget becomes a child of the scroll area, and will be destroyed when the scroll area is deleted or when a new widget is set.
The widget's autoFillBackground property will be set to true.
If the scroll area is visible when the widget is added, you must QWidget::show() it explicitly.
Note that You must add the layout of widget before you call this function; if you add it later, the widget will not be visible - regardless of when you QWidget::show() the scroll area. In this case, you can also not QWidget::show() the widget later.
See also
widget()
Definition at line 257 of file qscrollarea.cpp.
Referenced by QToolBox::insertItem().
 {
     Q_D(QScrollArea);
     if (widget == d->widget || !widget)
         return;
     delete d->widget;
     d->widget = 0;
     d->hbar->setValue(0);
     d->vbar->setValue(0);
     if (widget->parentWidget() != d->viewport)
         widget->setParent(d->viewport);
     if (!widget->testAttribute(Qt::WA_Resized))
         widget->resize(widget->sizeHint());
     d->widget = widget;
     d->widget->setAutoFillBackground(true);
     widget->installEventFilter(this);
     d->widgetSize = QSize();
     d->updateScrollBars();
     d->widget->show();
 }
setWidgetResizable()
void QScrollArea::setWidgetResizable (bool resizable)
Definition at line 381 of file qscrollarea.cpp.
Referenced by QToolBox::insertItem().
 {
     Q_D(QScrollArea);
     d->resizable = resizable;
     updateGeometry();
     d->updateScrollBars();
 }
sizeHint()
QSize QScrollArea::sizeHint () const virtual
Reimplemented Function
Reimplemented from QAbstractScrollArea.
Definition at line 392 of file qscrollarea.cpp.
 {
     Q_D(const QScrollArea);
     int f = 2 * d->frameWidth;
     QSize sz(f, f);
     int h = fontMetrics().height();
     if (d->widget) {
         if (!d->widgetSize.isValid())
             d->widgetSize = d->resizable ? d->widget->sizeHint() : d->widget->size();
         sz += d->widgetSize;
     } else {
         sz += QSize(12 * h, 8 * h);
     }
     if (d->vbarpolicy == Qt::ScrollBarAlwaysOn)
         sz.setWidth(sz.width() + d->vbar->sizeHint().width());
     if (d->hbarpolicy == Qt::ScrollBarAlwaysOn)
         sz.setHeight(sz.height() + d->hbar->sizeHint().height());
     return sz.boundedTo(QSize(36 * h, 24 * h));
 }
takeWidget()
QWidget * QScrollArea::takeWidget ()
Removes the scroll area's widget, and passes ownership of the widget to the caller.
See also
widget()
Definition at line 286 of file qscrollarea.cpp.
 {
     Q_D(QScrollArea);
     QWidget *w = d->widget;
     d->widget = 0;
     if (w)
         w->setParent(0);
     return w;
 }
widget()
QWidget * QScrollArea::widget () const
Returns the scroll area's widget, or 0 if there is none.
See also
setWidget()
Definition at line 228 of file qscrollarea.cpp.
Referenced by setWidget(), QScrollAreaPrivate::updateScrollBars(), and QScrollAreaPrivate::updateWidgetPosition().
 {
     Q_D(const QScrollArea);
     return d->widget;
 }
widgetResizable()
bool QScrollArea::widgetResizable () const
Referenced by scrollContentsBy().
Properties
alignment
Qt::Alignment QScrollArea::alignment private
the alignment of the scroll area's widget
Since
4.2
By default, the widget stays rooted to the top-left corner of the scroll area.
Definition at line 61 of file qscrollarea.h.
widgetResizable
bool QScrollArea::widgetResizable private
whether the scroll area should resize the view widget
If this property is set to false (the default), the scroll area honors the size of its widget. Regardless of this property, you can programmatically resize the widget using widget()->resize(), and the scroll area will automatically adjust itself to the new size.
If this property is set to true, the scroll area will automatically resize the widget in order to avoid scroll bars where they can be avoided, or to take advantage of extra space.
Definition at line 60 of file qscrollarea.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qscrollarea.h
/src/gui/widgets/qscrollarea.cpp