Qt 4.8: QDeclarativeError Class Reference
QDeclarativeError Class Reference
The QDeclarativeError class encapsulates a QML error.
#include <qdeclarativeerror.h>
Public Functions
int column () const
Returns the error column number.
QString description () const
Returns the error description.
bool isValid () const
Returns true if this error is valid, otherwise false.
int line () const
Returns the error line number.
QDeclarativeError & operator= (const QDeclarativeError &)
Assigns other to this error object.
QDeclarativeError ()
Creates an empty error object.
QDeclarativeError (const QDeclarativeError &)
Creates a copy of other.
void setColumn (int)
Sets the error column number.
void setDescription (const QString &)
Sets the error description.
void setLine (int)
Sets the error line number.
void setUrl (const QUrl &)
Sets the url for the file that caused this error.
QString toString () const
Returns the error as a human readable string.
QUrl url () const
Returns the url for the file that caused this error.
~QDeclarativeError ()
Properties
QDeclarativeErrorPrivate * d
Related Functions
(Note that these are not member functions.)
QDebug operator<< (QDebug debug, const QDeclarativeError &error)
Outputs a human readable version of error to debug.
Detailed Description
The QDeclarativeError class encapsulates a QML error.
Since
4.7
QDeclarativeError includes a textual description of the error, as well as location information (the file, line, and column). The toString() method creates a single-line, human-readable string containing all of this information, for example:
file:///home/user/test.qml:7:8: Invalid property assignment: double expected
You can use qDebug() or qWarning() to output errors to the console. This method will attempt to open the file indicated by the error and include additional contextual information.
file:
        y: "hello"
           ^
See also
QDeclarativeView::errors(), QDeclarativeComponent::errors()
Definition at line 56 of file qdeclarativeerror.h.
Constructors and Destructors
QDeclarativeError() [1/2]
QDeclarativeError::QDeclarativeError ()
Creates an empty error object.
Definition at line 96 of file qdeclarativeerror.cpp.
 : d(0)
 {
 }
QDeclarativeError() [2/2]
QDeclarativeError::QDeclarativeError (const QDeclarativeError & other)
Creates a copy of other.
Definition at line 104 of file qdeclarativeerror.cpp.
 : d(0)
 {
     *this = other;
 }
~QDeclarativeError()
QDeclarativeError::~QDeclarativeError ()
Warning
This function is not part of the public interface.
Definition at line 131 of file qdeclarativeerror.cpp.
 {
     delete d; d = 0;
 }
Functions
column()
int QDeclarativeError::column () const
Returns the error column number.
Definition at line 201 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject(), operator<<(), setColumn(), and toString().
 {
     if (d) return d->column;
     else return -1;
 }
description()
QString QDeclarativeError::description () const
Returns the error description.
Definition at line 165 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeCompiler::compile(), QDeclarativeEnginePrivate::createQmlObject(), QDeclarativeDirParser::errors(), QDeclarativeComponent::errorString(), QDeclarativeImportsPrivate::importExtension(), setDescription(), and toString().
 {
     if (d) return d->description;
     else return QString();
 }
isValid()
bool QDeclarativeError::isValid () const
Returns true if this error is valid, otherwise false.
Definition at line 139 of file qdeclarativeerror.cpp.
 {
     return d != 0;
 }
line()
int QDeclarativeError::line () const
Returns the error line number.
Definition at line 183 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject(), QDeclarativeComponent::errorString(), operator<<(), setLine(), and toString().
 {
     if (d) return d->line;
     else return -1;
 }
operator=()
QDeclarativeError & QDeclarativeError::operator= (const QDeclarativeError & other)
Assigns other to this error object.
Definition at line 113 of file qdeclarativeerror.cpp.
 {
     if (!other.d) {
         delete d;
         d = 0;
     } else {
         if (!d) d = new QDeclarativeErrorPrivate;
         d->url = other.d->url;
         d->description = other.d->description;
         d->line = other.d->line;
         d->column = other.d->column;
     }
     return *this;
 }
setColumn()
void QDeclarativeError::setColumn (int column)
Sets the error column number.
Definition at line 210 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeTypeData::done(), QDeclarativeCustomParser::error(), QDeclarativeExpressionPrivate::exceptionToError(), QDeclarativeScriptParser::parse(), QDeclarativeDirParser::reportError(), QDeclarativeTypeData::resolveTypes(), throwException(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     if (!d) d = new QDeclarativeErrorPrivate;
     d->column = column;
 }
setDescription()
void QDeclarativeError::setDescription (const QString & description)
Sets the error description.
Definition at line 174 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeEnginePrivate::createCache(), QDeclarativeTypeData::done(), QDeclarativeCustomParser::error(), QDeclarativeDirParser::errors(), QDeclarativeExpressionPrivate::exceptionToError(), QDeclarativeDomDocument::load(), QDeclarativeDataLoader::load(), QDeclarativeComponent::loadUrl(), QDeclarativeDataBlob::networkError(), QDeclarativeDirParser::parse(), QDeclarativeScriptParser::parse(), QDeclarativeDirParser::reportError(), QDeclarativeTypeData::resolveTypes(), throwException(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     if (!d) d = new QDeclarativeErrorPrivate;
     d->description = description;
 }
setLine()
void QDeclarativeError::setLine (int line)
Sets the error line number.
Definition at line 192 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeTypeData::done(), QDeclarativeCustomParser::error(), QDeclarativeExpressionPrivate::exceptionToError(), QDeclarativeScriptParser::parse(), QDeclarativeDirParser::reportError(), QDeclarativeTypeData::resolveTypes(), throwException(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     if (!d) d = new QDeclarativeErrorPrivate;
     d->line = line;
 }
setUrl()
void QDeclarativeError::setUrl (const QUrl & url)
Sets the url for the file that caused this error.
Definition at line 156 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeCompiler::buildObject(), QDeclarativeTypeData::done(), QDeclarativeExpressionPrivate::exceptionToError(), QDeclarativeDataLoader::load(), QDeclarativeDataBlob::networkError(), QDeclarativeScriptParser::parse(), QDeclarativeDirParser::reportError(), QDeclarativeWorkerScriptEnginePrivate::reportScriptException(), QDeclarativeTypeData::resolveTypes(), throwException(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     if (!d) d = new QDeclarativeErrorPrivate;
     d->url = url;
 }
toString()
QString QDeclarativeError::toString () const
Returns the error as a human readable string.
Definition at line 219 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject(), dumpwarning(), and operator<<().
 {
     QString rv;
     if (url().isEmpty()) {
         rv = QLatin1String("<Unknown File>");
     } else if (line() != -1) {
         rv = url().toString() + QLatin1Char(':') + QString::number(line());
         if(column() != -1)
             rv += QLatin1Char(':') + QString::number(column());
     } else {
         rv = url().toString();
     }
     rv += QLatin1String(": ") + description();
     return rv;
 }
url()
QUrl QDeclarativeError::url () const
Returns the url for the file that caused this error.
Definition at line 147 of file qdeclarativeerror.cpp.
Referenced by QDeclarativeEnginePrivate::createQmlObject(), QDeclarativeComponent::errorString(), operator<<(), setUrl(), and toString().
 {
     if (d) return d->url;
     else return QUrl();
 }
Friends and Related Functions
operator<<()
QDebug operator<< (QDebug debug, const QDeclarativeError & error) related
Outputs a human readable version of error to debug.
Definition at line 247 of file qdeclarativeerror.cpp.
 {
     debug << qPrintable(error.toString());
     QUrl url = error.url();
     if (error.line() > 0 && url.scheme() == QLatin1String("file")) {
         QString file = url.toLocalFile();
         QFile f(file);
         if (f.open(QIODevice::ReadOnly)) {
             QByteArray data = f.readAll();
             QTextStream stream(data, QIODevice::ReadOnly);
 #ifndef QT_NO_TEXTCODEC
             stream.setCodec("UTF-8");
 #endif
             const QString code = stream.readAll();
             const QStringList lines = code.split(QLatin1Char('\n'));
             if (lines.count() >= error.line()) {
                 const QString &line = lines.at(error.line() - 1);
                 debug << "\n    " << qPrintable(line);
                 if(error.column() > 0) {
                     int column = qMax(0, error.column() - 1);
                     column = qMin(column, line.length());
                     QByteArray ind;
                     ind.reserve(column);
                     for (int i = 0; i < column; ++i) {
                         const QChar ch = line.at(i);
                         if (ch.isSpace())
                             ind.append(ch.unicode());
                         else
                             ind.append(' ');
                     }
                     ind.append('^');
                     debug << "\n    " << ind.constData();
                 }
             }
         }
     }
     return debug;
 }
Properties
d
QDeclarativeErrorPrivate* QDeclarativeError::d private
Definition at line 77 of file qdeclarativeerror.h.
Referenced by column(), description(), isValid(), line(), operator=(), setColumn(), setDescription(), setLine(), setUrl(), url(), and ~QDeclarativeError().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeerror.h
/src/declarative/qml/qdeclarativeerror.cpp