Qt 4.8: QToolBarPrivate Class Reference
QToolBarPrivate Class Reference
#include <qtoolbar_p.h>
Classes
struct DragState
Public Functions
void _q_toggleView (bool b)
void _q_updateIconSize (const QSize &sz)
void _q_updateToolButtonStyle (Qt::ToolButtonStyle style)
void actionTriggered ()
void endDrag ()
void init ()
void initDrag (const QPoint &pos)
bool mouseMoveEvent (QMouseEvent *e)
bool mousePressEvent (QMouseEvent *e)
bool mouseReleaseEvent (QMouseEvent *e)
void plug (const QRect &r)
QToolBarPrivate ()
void setWindowState (bool floating, bool unplug=false, const QRect &rect=QRect())
void startDrag (bool moving=false)
void unplug (const QRect &r)
void updateWindowFlags (bool floating, bool unplug=false)
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
Qt::ToolBarAreas allowedAreas
bool explicitIconSize
bool explicitToolButtonStyle
bool floatable
QSize iconSize
QToolBarLayout * layout
bool macWindowDragging
QPoint macWindowDragPressPosition
bool movable
Qt::Orientation orientation
DragState * state
QAction * toggleViewAction
Qt::ToolButtonStyle toolButtonStyle
QBasicTimer waitForPopupTimer
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 68 of file qtoolbar_p.h.
Constructors and Destructors
QToolBarPrivate()
QToolBarPrivate::QToolBarPrivate () inline
Definition at line 73 of file qtoolbar_p.h.
         : explicitIconSize(false), explicitToolButtonStyle(false), movable(true), floatable(true),
           allowedAreas(Qt::AllToolBarAreas), orientation(Qt::Horizontal),
           toolButtonStyle(Qt::ToolButtonIconOnly),
           layout(0), state(0)
 #ifdef Q_WS_MAC
         , macWindowDragging(false)
 #endif
     { }
Functions
_q_toggleView()
void QToolBarPrivate::_q_toggleView (bool b)
Definition at line 124 of file qtoolbar.cpp.
Referenced by init(), and QToolBarPrivate().
 {
     Q_Q(QToolBar);
     if (b == q->isHidden()) {
         if (b)
             q->show();
         else
             q->close();
     }
 }
_q_updateIconSize()
void QToolBarPrivate::_q_updateIconSize (const QSize & sz)
Definition at line 135 of file qtoolbar.cpp.
Referenced by QToolBarPrivate().
 {
     Q_Q(QToolBar);
     if (!explicitIconSize) {
         // iconSize not explicitly set
         q->setIconSize(sz);
         explicitIconSize = false;
     }
 }
_q_updateToolButtonStyle()
void QToolBarPrivate::_q_updateToolButtonStyle (Qt::ToolButtonStyle style)
Definition at line 145 of file qtoolbar.cpp.
Referenced by QToolBarPrivate().
 {
     Q_Q(QToolBar);
     if (!explicitToolButtonStyle) {
         q->setToolButtonStyle(style);
         explicitToolButtonStyle = false;
     }
 }
actionTriggered()
void QToolBarPrivate::actionTriggered ()
Referenced by QToolBarPrivate().
endDrag()
void QToolBarPrivate::endDrag ()
Definition at line 245 of file qtoolbar.cpp.
Referenced by mouseReleaseEvent().
 {
     Q_Q(QToolBar);
     Q_ASSERT(state != 0);
     q->releaseMouse();
     if (state->dragging) {
         QMainWindowLayout *layout = qt_mainwindow_layout(qobject_cast<QMainWindow *>(q->parentWidget()));
         Q_ASSERT(layout != 0);
         if (!layout->plug(state->widgetItem)) {
             if (q->isFloatable()) {
                 layout->restore();
 #if defined(Q_WS_X11) || defined(Q_WS_MAC)
                 setWindowState(true); // gets rid of the X11BypassWindowManager window flag
                                       // and activates the resizer
 #endif
                 q->activateWindow();
             } else {
                 layout->revert(state->widgetItem);
             }
         }
     }
     delete state;
     state = 0;
 }
init()
void QToolBarPrivate::init ()
Definition at line 92 of file qtoolbar.cpp.
Referenced by QToolBarPrivate().
 {
     Q_Q(QToolBar);
     q->setSizePolicy(QSizePolicy(QSizePolicy::Preferred, QSizePolicy::Fixed));
     q->setBackgroundRole(QPalette::Button);
     q->setAttribute(Qt::WA_Hover);
     q->setAttribute(Qt::WA_X11NetWmWindowTypeToolBar);
     QStyle *style = q->style();
     int e = style->pixelMetric(QStyle::PM_ToolBarIconSize, 0, q);
     iconSize = QSize(e, e);
     layout = new QToolBarLayout(q);
     layout->updateMarginAndSpacing();
 #ifdef Q_WS_MAC
     if (q->parentWidget() && q->parentWidget()->isWindow()) {
         // Make sure that the window has the "toolbar" button.
         QWidget *parentWidget = q->parentWidget();
         qt_mac_updateToolBarButtonHint(parentWidget);
         reinterpret_cast<QToolBar *>(parentWidget)->d_func()->createWinId(); // Please let me create your winId...
         extern OSWindowRef qt_mac_window_for(const QWidget *); // qwidget_mac.cpp
         macWindowToolbarShow(q->parentWidget(), true);
     }
 #endif
     toggleViewAction = new QAction(q);
     toggleViewAction->setCheckable(true);
     q->setMovable(q->style()->styleHint(QStyle::SH_ToolBar_Movable, 0, q ));
     QObject::connect(toggleViewAction, SIGNAL(triggered(bool)), q, SLOT(_q_toggleView(bool)));
 }
initDrag()
void QToolBarPrivate::initDrag (const QPoint & pos)
Definition at line 194 of file qtoolbar.cpp.
Referenced by mousePressEvent().
 {
     Q_Q(QToolBar);
     if (state != 0)
         return;
     QMainWindow *win = qobject_cast<QMainWindow*>(parent);
     Q_ASSERT(win != 0);
     QMainWindowLayout *layout = qt_mainwindow_layout(win);
     Q_ASSERT(layout != 0);
     if (layout->pluggingWidget != 0) // the main window is animating a docking operation
         return;
     state = new DragState;
     state->pressPos = pos;
     state->dragging = false;
     state->moving = false;
     state->widgetItem = 0;
     if (q->isRightToLeft())
         state->pressPos = QPoint(q->width() - state->pressPos.x(), state->pressPos.y());
 }
mouseMoveEvent()
bool QToolBarPrivate::mouseMoveEvent (QMouseEvent * e)
Definition at line 325 of file qtoolbar.cpp.
 {
     Q_Q(QToolBar);
     if (!state) {
 #ifdef Q_WS_MAC
         if (!macWindowDragging)
             return false;
         QWidget *w = q->window();
         const QPoint delta = event->pos() - macWindowDragPressPosition;
         w->move(w->pos() + delta);
         return true;
 #endif
         return false;
     }
     QMainWindow *win = qobject_cast<QMainWindow*>(parent);
     if (win == 0)
         return true;
     QMainWindowLayout *layout = qt_mainwindow_layout(win);
     Q_ASSERT(layout != 0);
     if (layout->pluggingWidget == 0
         && (event->pos() - state->pressPos).manhattanLength() > QApplication::startDragDistance()) {
             const bool wasDragging = state->dragging;
             const bool moving = !q->isWindow() && (orientation == Qt::Vertical ?
                 event->x() >= 0 && event->x() < q->width() :
                 event->y() >= 0 && event->y() < q->height());
             startDrag(moving);
             if (!moving && !wasDragging) {
 #ifdef Q_OS_WIN
                 grabMouseWhileInWindow();
 #else
                 q->grabMouse();
 #endif
             }
     }
     if (state->dragging) {
         QPoint pos = event->globalPos();
         // if we are right-to-left, we move so as to keep the right edge the same distance
         // from the mouse
         if (q->isLeftToRight())
             pos -= state->pressPos;
         else
             pos += QPoint(state->pressPos.x() - q->width(), -state->pressPos.y());
         q->move(pos);
         layout->hover(state->widgetItem, event->globalPos());
     } else if (state->moving) {
         const QPoint rtl(q->width() - state->pressPos.x(), state->pressPos.y()); //for RTL
         const QPoint globalPressPos = q->mapToGlobal(q->isRightToLeft() ? rtl : state->pressPos);
         int pos = 0;
         QPoint delta = event->globalPos() - globalPressPos;
         if (orientation == Qt::Vertical) {
             pos = q->y() + delta.y();
         } else {
             if (q->isRightToLeft()) {
                 pos = win->width() - q->width() - q->x()  - delta.x();
             } else {
                 pos = q->x() + delta.x();
             }
         }
         layout->moveToolBar(q, pos);
     }
     return true;
 }
mousePressEvent()
bool QToolBarPrivate::mousePressEvent (QMouseEvent * e)
Definition at line 274 of file qtoolbar.cpp.
 {
     Q_Q(QToolBar);
     QStyleOptionToolBar opt;
     q->initStyleOption(&opt);
     if (q->style()->subElementRect(QStyle::SE_ToolBarHandle, &opt, q).contains(event->pos()) == false) {
 #ifdef Q_WS_MAC
         // When using the unified toolbar on Mac OS X the user can can click and
         // drag between toolbar contents to move the window. Make this work by
         // implementing the standard mouse-dragging code and then call
         // window->move() in mouseMoveEvent below.
         if (QMainWindow *mainWindow = qobject_cast<QMainWindow *>(parent)) {
             if (mainWindow->toolBarArea(q) == Qt::TopToolBarArea
                     && mainWindow->unifiedTitleAndToolBarOnMac()
                     && q->childAt(event->pos()) == 0) {
                 macWindowDragging = true;
                 macWindowDragPressPosition = event->pos();
                 return true;
             }
         }
 #endif
         return false;
     }
     if (event->button() != Qt::LeftButton)
         return true;
     if (!layout->movable())
         return true;
     initDrag(event->pos());
     return true;
 }
mouseReleaseEvent()
bool QToolBarPrivate::mouseReleaseEvent (QMouseEvent * e)
Definition at line 308 of file qtoolbar.cpp.
 {
     if (state != 0) {
         endDrag();
         return true;
     } else {
 #ifdef Q_WS_MAC
         if (!macWindowDragging)
             return false;
         macWindowDragging = false;
         macWindowDragPressPosition = QPoint();
         return true;
 #endif
         return false;
     }
 }
plug()
void QToolBarPrivate::plug (const QRect & r)
Definition at line 407 of file qtoolbar.cpp.
 {
     setWindowState(false, false, r);
 }
setWindowState()
void QToolBarPrivate::setWindowState (bool floating, bool unplug = false, const QRect & rect = QRect())
Definition at line 171 of file qtoolbar.cpp.
Referenced by endDrag(), plug(), startDrag(), and unplug().
 {
     Q_Q(QToolBar);
     bool visible = !q->isHidden();
     bool wasFloating = q->isFloating(); // ...is also currently using popup menus
     q->hide();
     updateWindowFlags(floating, unplug);
     if (floating != wasFloating)
         layout->checkUsePopupMenu();
     if (!rect.isNull())
         q->setGeometry(rect);
     if (visible)
         q->show();
     if (floating != wasFloating)
         emit q->topLevelChanged(floating);
 }
startDrag()
void QToolBarPrivate::startDrag (bool moving = false)
Definition at line 218 of file qtoolbar.cpp.
Referenced by mouseMoveEvent().
 {
     Q_Q(QToolBar);
     Q_ASSERT(state != 0);
     if ((moving && state->moving) || state->dragging)
         return;
     QMainWindow *win = qobject_cast<QMainWindow*>(parent);
     Q_ASSERT(win != 0);
     QMainWindowLayout *layout = qt_mainwindow_layout(win);
     Q_ASSERT(layout != 0);
     if (!moving) {
         state->widgetItem = layout->unplug(q);
 #if defined(Q_WS_MAC) && !defined(QT_MAC_USE_COCOA)
         if (q->isWindow()) {
            setWindowState(true, true); //set it to floating
         }
 #endif
         Q_ASSERT(state->widgetItem != 0);
     }
     state->dragging = !moving;
     state->moving = moving;
 }
unplug()
void QToolBarPrivate::unplug (const QRect & r)
Definition at line 398 of file qtoolbar.cpp.
 {
     Q_Q(QToolBar);
     QRect r = _r;
     r.moveTopLeft(q->mapToGlobal(QPoint(0, 0)));
     setWindowState(true, true, r);
     layout->setExpanded(false);
 }
updateWindowFlags()
void QToolBarPrivate::updateWindowFlags (bool floating, bool unplug = false)
Definition at line 154 of file qtoolbar.cpp.
Referenced by setWindowState().
 {
     Q_Q(QToolBar);
     Qt::WindowFlags flags = floating ? Qt::Tool : Qt::Widget;
     flags |= Qt::FramelessWindowHint;
     if (unplug) {
         flags |= Qt::X11BypassWindowManagerHint;
 #ifdef Q_WS_MAC
         flags |= Qt::WindowStaysOnTopHint;
 #endif
     }
     q->setWindowFlags(flags);
 }
Properties
allowedAreas
Qt::ToolBarAreas QToolBarPrivate::allowedAreas
Definition at line 93 of file qtoolbar_p.h.
explicitIconSize
bool QToolBarPrivate::explicitIconSize
Definition at line 89 of file qtoolbar_p.h.
Referenced by _q_updateIconSize().
explicitToolButtonStyle
bool QToolBarPrivate::explicitToolButtonStyle
Definition at line 90 of file qtoolbar_p.h.
Referenced by _q_updateToolButtonStyle().
floatable
bool QToolBarPrivate::floatable
Definition at line 92 of file qtoolbar_p.h.
iconSize
QSize QToolBarPrivate::iconSize
Definition at line 96 of file qtoolbar_p.h.
Referenced by init().
layout
QToolBarLayout* QToolBarPrivate::layout
Definition at line 100 of file qtoolbar_p.h.
Referenced by endDrag(), init(), initDrag(), mouseMoveEvent(), mousePressEvent(), setWindowState(), startDrag(), and unplug().
macWindowDragging
bool QToolBarPrivate::macWindowDragging
Definition at line 111 of file qtoolbar_p.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
macWindowDragPressPosition
QPoint QToolBarPrivate::macWindowDragPressPosition
Definition at line 112 of file qtoolbar_p.h.
Referenced by mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
movable
bool QToolBarPrivate::movable
Definition at line 91 of file qtoolbar_p.h.
orientation
Qt::Orientation QToolBarPrivate::orientation
Definition at line 94 of file qtoolbar_p.h.
Referenced by mouseMoveEvent().
state
DragState* QToolBarPrivate::state
Definition at line 108 of file qtoolbar_p.h.
Referenced by endDrag(), initDrag(), mouseMoveEvent(), mouseReleaseEvent(), and startDrag().
toggleViewAction
QAction* QToolBarPrivate::toggleViewAction
Definition at line 98 of file qtoolbar_p.h.
Referenced by init().
toolButtonStyle
Qt::ToolButtonStyle QToolBarPrivate::toolButtonStyle
Definition at line 95 of file qtoolbar_p.h.
waitForPopupTimer
QBasicTimer QToolBarPrivate::waitForPopupTimer
Definition at line 128 of file qtoolbar_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qtoolbar_p.h
/src/gui/widgets/qtoolbar.cpp