Qt 4.8: QDeclarativeActionEvent Class Reference
QDeclarativeActionEvent Class Reference
#include <qdeclarativestate_p.h>
Public Types
enum Reason { ActualChange, FastForward }
Public Functions
virtual bool changesBindings ()
virtual void clearBindings ()
virtual void copyOriginals (QDeclarativeActionEvent *)
virtual void execute (Reason reason=ActualChange)
virtual bool isReversable ()
virtual bool isRewindable ()
virtual bool needsCopy ()
virtual bool override (QDeclarativeActionEvent *other)
virtual void reverse (Reason reason=ActualChange)
virtual void rewind ()
virtual void saveCurrentValues ()
virtual void saveOriginals ()
virtual void saveTargetValues ()
virtual QString typeName () const
virtual ~QDeclarativeActionEvent ()
Detailed Description
Definition at line 89 of file qdeclarativestate_p.h.
Enumerations
Reason
enum QDeclarativeActionEvent::Reason
Enumerator
ActualChange
FastForward
Definition at line 95 of file qdeclarativestate_p.h.
 { ActualChange, FastForward };
Constructors and Destructors
~QDeclarativeActionEvent()
QDeclarativeActionEvent::~QDeclarativeActionEvent () virtual
Definition at line 89 of file qdeclarativestate.cpp.
 {
 }
Functions
changesBindings()
bool QDeclarativeActionEvent::changesBindings () virtual
Reimplemented in QDeclarativeAnchorChanges.
Definition at line 111 of file qdeclarativestate.cpp.
Referenced by QDeclarativeTransitionManager::transition().
 {
     return false;
 }
clearBindings()
void QDeclarativeActionEvent::clearBindings () virtual
Reimplemented in QDeclarativeAnchorChanges.
Definition at line 116 of file qdeclarativestate.cpp.
Referenced by QDeclarativeAnchorChanges::needsCopy(), and QDeclarativeTransitionManager::transition().
 {
 }
copyOriginals()
virtual void QDeclarativeActionEvent::copyOriginals (QDeclarativeActionEvent *) inline virtual
Reimplemented in QDeclarativeAnchorChanges, and QDeclarativeReplaceSignalHandler.
Definition at line 102 of file qdeclarativestate_p.h.
Referenced by QDeclarativeState::apply(), and QDeclarativeAnchorChanges::needsCopy().
 {}
execute()
void QDeclarativeActionEvent::execute (Reason reason = ActualChange) virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, QDeclarativeStateChangeScript, and QDeclarativeParentChange.
Definition at line 98 of file qdeclarativestate.cpp.
Referenced by QDeclarativeTransitionManagerPrivate::applyBindings(), QDeclarativeTransitionManager::transition(), and QDeclarativeParentAnimation::transition().
 {
 }
isReversable()
bool QDeclarativeActionEvent::isReversable () virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, and QDeclarativeParentChange.
Definition at line 102 of file qdeclarativestate.cpp.
Referenced by QDeclarativeState::apply(), and QDeclarativeTransitionManager::transition().
 {
     return false;
 }
isRewindable()
virtual bool QDeclarativeActionEvent::isRewindable () inline virtual
Definition at line 104 of file qdeclarativestate_p.h.
Referenced by QDeclarativeState::apply().
 { return isReversable(); }
needsCopy()
virtual bool QDeclarativeActionEvent::needsCopy () inline virtual
Reimplemented in QDeclarativeAnchorChanges, and QDeclarativeReplaceSignalHandler.
Definition at line 101 of file qdeclarativestate_p.h.
Referenced by QDeclarativeState::apply().
 { return false; }
override()
bool QDeclarativeActionEvent::override (QDeclarativeActionEvent * other) virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, and QDeclarativeParentChange.
Definition at line 120 of file qdeclarativestate.cpp.
Referenced by QDeclarativeState::apply().
 {
     Q_UNUSED(other);
     return false;
 }
reverse()
void QDeclarativeActionEvent::reverse (Reason reason = ActualChange) virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, and QDeclarativeParentChange.
Definition at line 107 of file qdeclarativestate.cpp.
Referenced by QDeclarativeTransitionManagerPrivate::applyBindings(), QDeclarativeTransitionManager::transition(), and QDeclarativeParentAnimation::transition().
 {
 }
rewind()
virtual void QDeclarativeActionEvent::rewind () inline virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, and QDeclarativeParentChange.
Definition at line 105 of file qdeclarativestate_p.h.
Referenced by QDeclarativeAnchorChanges::needsCopy(), and QDeclarativeTransitionManager::transition().
 {}
saveCurrentValues()
virtual void QDeclarativeActionEvent::saveCurrentValues () inline virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, and QDeclarativeParentChange.
Definition at line 106 of file qdeclarativestate_p.h.
Referenced by QDeclarativeState::apply(), and QDeclarativeAnchorChanges::needsCopy().
 {}
saveOriginals()
virtual void QDeclarativeActionEvent::saveOriginals () inline virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, and QDeclarativeParentChange.
Definition at line 100 of file qdeclarativestate_p.h.
Referenced by QDeclarativeState::apply().
 {}
saveTargetValues()
virtual void QDeclarativeActionEvent::saveTargetValues () inline virtual
Reimplemented in QDeclarativeAnchorChanges.
Definition at line 107 of file qdeclarativestate_p.h.
Referenced by QDeclarativeAnchorChanges::needsCopy(), and QDeclarativeTransitionManager::transition().
 {}
typeName()
QString QDeclarativeActionEvent::typeName () const virtual
Reimplemented in QDeclarativeAnchorChanges, QDeclarativeReplaceSignalHandler, QDeclarativeStateChangeScript, and QDeclarativeParentChange.
Definition at line 93 of file qdeclarativestate.cpp.
Referenced by QDeclarativeState::apply(), QDeclarativeParentChange::override(), QDeclarativeAnchorChanges::override(), QDeclarativeTransitionManager::transition(), QDeclarativeScriptAction::transition(), QDeclarativeParentAnimation::transition(), and QDeclarativeAnchorAnimation::transition().
 {
     return QString();
 }
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativestate_p.h
/src/declarative/util/qdeclarativestate.cpp