Qt 4.8: PvrEglScreen Class Reference
PvrEglScreen Class Reference
#include <pvreglscreen.h>
Public Functions
void blit (const QImage &img, const QPoint &topLeft, const QRegion &region)
Copies the given region in the given image to the point specified by topLeft using device coordinates.
bool chooseContext (QGLContext *context, const QGLContext *shareContext)
Initializes the context and sets up the QGLWindowSurface of the QWidget of context based on the parameters of context and based on its own requirements.
bool connect (const QString &displaySpec)
This function is called by every Qt for Embedded Linux application on startup, and must be implemented to map in the framebuffer and the accelerated drivers that the graphics card control registers.
QWSWindowSurface * createSurface (QWidget *widget) const
[1]
QWSWindowSurface * createSurface (const QString &key) const
Creates and returns a new window surface matching the given key.
void disconnect ()
This function is called by every Qt for Embedded Linux application before exiting, and must be implemented to unmap the framebuffer.
bool hasOpenGL ()
bool initDevice ()
This function is called by the Qt for Embedded Linux server to initialize the framebuffer.
PvrEglScreen (int displayId)
[0]
void setMode (int, int, int)
Implement this function to reset the framebuffer's resolution (width and height) and bit depth.
void shutdownDevice ()
This function is called by the Qt for Embedded Linux server before it calls the disconnect() function when exiting.
void solidFill (const QColor &color, const QRegion &region)
Fills the given region of the screen with the specified color.
int transformation () const
~PvrEglScreen ()
Public Functions inherited from QGLScreen
QGLScreen::Options options () const
Returns the options associated with this QGLScreen.
QGLScreen (int displayId)
QGLScreenSurfaceFunctions * surfaceFunctions () const
Returns the surface functions object for this QGLScreen.
virtual ~QGLScreen ()
Public Functions inherited from QScreen
virtual int alloc (unsigned int, unsigned int, unsigned int)
Returns the index in the screen's palette which is the closest match to the given RGB value (red, green, blue).
uchar * base () const
Returns a pointer to the beginning of the framebuffer.
virtual void blank (bool on)
Prevents the screen driver form displaying any content on the screen.
void blit (QWSWindow *bs, const QRegion &clip)
virtual uchar * cache (int)
ClassId classId () const
Returns the class identifier for the screen object.
QRgb * clut ()
Returns a pointer to the screen's color lookup table (i.
int colorCount ()
Returns the number of entries in the screen's color lookup table (i.
int depth () const
Returns the depth of the framebuffer, in bits per pixel.
int deviceHeight () const
Returns the full height of the framebuffer device in pixels.
int deviceWidth () const
Returns the physical width of the framebuffer device in pixels.
virtual void exposeRegion (QRegion r, int changing)
This function is called by the Qt for Embedded Linux server whenever a screen update is required.
QGraphicsSystem * graphicsSystem () const
virtual void haltUpdates ()
int height () const
Returns the logical height of the framebuffer in pixels.
virtual bool isInterlaced () const
Returns true if the display is interlaced (i.
virtual bool isTransformed () const
Returns true if the screen is transformed (for instance, rotated 90 degrees); otherwise returns false.
int linestep () const
Returns the length of each scanline of the framebuffer in bytes.
virtual QSize mapFromDevice (const QSize &) const
Maps the given size from the framebuffer coordinate system to the coordinate space used by the application.
virtual QPoint mapFromDevice (const QPoint &, const QSize &) const
Maps the given point from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QRect mapFromDevice (const QRect &, const QSize &) const
Maps the given rectangle from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QImage mapFromDevice (const QImage &) const
Maps the given image from the framebuffer coordinate system to the coordinate space used by the application.
virtual QRegion mapFromDevice (const QRegion &, const QSize &) const
Maps the given region from the framebuffer coordinate system to the coordinate space used by the application, passing the device's screenSize as argument.
virtual QSize mapToDevice (const QSize &) const
Maps the given size from the coordinate space used by the application to the framebuffer coordinate system.
virtual QPoint mapToDevice (const QPoint &, const QSize &) const
Maps the given point from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual QRect mapToDevice (const QRect &, const QSize &) const
Maps the given rectangle from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual QImage mapToDevice (const QImage &) const
Maps the given image from the coordinate space used by the application to the framebuffer coordinate system.
virtual QRegion mapToDevice (const QRegion &, const QSize &) const
Maps the given region from the coordinate space used by the application to the framebuffer coordinate system, passing the device's screenSize as argument.
virtual int memoryNeeded (const QString &)
QT_DEPRECATED int numCols ()
QPoint offset () const
Returns the logical offset of the screen, i.
virtual bool onCard (const unsigned char *) const
Returns true if the specified buffer is within the graphics card's memory; otherwise returns false (i.e.
virtual bool onCard (const unsigned char *, ulong &out_offset) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.If the specified buffer is within the graphics card's memory, this function stores the offset from the start of graphics card memory (in bytes), in the location specified by the offset parameter.
int physicalHeight () const
Returns the physical height of the screen in millimeters.
int physicalWidth () const
Returns the physical width of the screen in millimeters.
QImage::Format pixelFormat () const
Returns the pixel format of the screen, or QImage::Format_Invalid if the pixel format is not a supported image format.
PixelType pixelType () const
Returns the pixel storage format of the screen.
QPixmapDataFactory * pixmapDataFactory () const
virtual int pixmapDepth () const
Returns the preferred depth for pixmaps, in bits per pixel.
virtual int pixmapLinestepAlignment ()
Returns the value (in bits) to which individual scanlines of pixmaps held in the graphics card's memory, should be aligned.
virtual int pixmapOffsetAlignment ()
Returns the value (in bits) to which the start address of pixmaps held in the graphics card's memory, should be aligned.
QScreen (int display_id, ClassId classId)
Constructs a new screen driver.
QScreen (int display_id)
Constructs a new screen driver.
virtual QRegion region () const
Returns the region covered by this screen driver.
virtual void restore ()
Restores the previously saved state of the graphics card.
virtual void resumeUpdates ()
virtual void save ()
Saves the current state of the graphics card.
int screenSize () const
Returns the size of the screen in bytes.
virtual void set (unsigned int, unsigned int, unsigned int, unsigned int)
virtual void setDirty (const QRect &)
Marks the given rectangle as dirty.
void setOffset (const QPoint &p)
virtual int sharedRamSize (void *)
int subScreenIndexAt (const QPoint &p) const
Returns the index of the subscreen at the given position; returns -1 if no screen is found.
virtual QList< QScreen * > subScreens () const
virtual bool supportsDepth (int) const
Returns true if the screen supports the specified color depth; otherwise returns false.
int totalSize () const
Returns the size of the available graphics card memory (including the screen) in bytes.
virtual int transformOrientation () const
Returns the current rotation as an integer value.
virtual void uncache (uchar *)
int width () const
Returns the logical width of the framebuffer in pixels.
virtual ~QScreen ()
Destroys this screen driver.
Private Functions
void closeTty ()
void openTty ()
void sync ()
Properties
bool doGraphicsMode
int fd
int oldKdMode
const QScreen * parent
QString ttyDevice
int ttyfd
Additional Inherited Members
Public Types inherited from QGLScreen
enum Option {
NoOptions = 0, NativeWindows = 1, NativePixmaps = 2, NativeImages = 4,
Overlays = 8
}
This enum defines options that can be set on QGLScreen instances.
Public Types inherited from QScreen
enum ClassId {
LinuxFBClass, TransformedClass, VNCClass, MultiClass,
VFbClass, DirectFBClass, SvgalibClass, ProxyClass,
GLClass, IntfbClass, CustomClass = 1024
}
This enum defines the class identifiers for the known screen subclasses.
enum PixelType { NormalPixel, BGRPixel }
This enum describes the pixel storage format of the screen, i.
Static Public Functions inherited from QScreen
static QScreen * instance ()
Returns a pointer to the application's QScreen instance.
Protected Functions inherited from QGLScreen
void setOptions (QGLScreen::Options value)
Sets the options associated with this QGLScreen to value.
void setSurfaceFunctions (QGLScreenSurfaceFunctions *functions)
Sets the surface functions object for this QGLScreen to functions.
Protected Functions inherited from QScreen
void setGraphicsSystem (QGraphicsSystem *system)
void setPixelFormat (QImage::Format format)
Sets the screen's pixel format to format.
void setPixmapDataFactory (QPixmapDataFactory *factory)
Protected Variables inherited from QScreen
int d
the pixel depth
uchar * data
points to the first visible pixel in the frame buffer.
int dh
the device height
int displayId
int dw
the device width
QPoolEntry * entries
int * entryp
bool grayscale
the gray scale screen mode flag
int h
the logical height of the screen.
unsigned int * lowest
int lstep
the number of bytes representing a line in the frame buffer.
int mapsize
the total number of bytes in the frame buffer
int physHeight
the physical height of the screen in millimeters.
int physWidth
the physical width of the screen in millimeters.
PixelType pixeltype
set to BGRPixel
QRgb screenclut [256]
the color table
int screencols
the number of entries in the color table
int size
the number of bytes in the visible region of the frame buffer
int w
the logical width of the screen.
Static Protected Variables inherited from QScreen
static ClearCacheFunc clearCacheFunc = 0
Related Functions inherited from QScreen
void setTransformation (int transformation, int screenNo)
Here it is.
Detailed Description
Definition at line 64 of file pvreglscreen.h.
Constructors and Destructors
PvrEglScreen()
PvrEglScreen::PvrEglScreen (int displayId)
[0]
[0]
Definition at line 57 of file pvreglscreen.cpp.
     : QGLScreen(displayId)
 {
     setOptions(NativeWindows);
     setSupportsBlitInClients(true);
     setSurfaceFunctions(new PvrEglScreenSurfaceFunctions(this, displayId));
     fd = -1;
     ttyfd = -1;
     doGraphicsMode = true;
     oldKdMode = KD_TEXT;
     parent = 0;
     // Make sure that the EGL layer is initialized and the drivers loaded.
     EGLDisplay dpy = eglGetDisplay((EGLNativeDisplayType)EGL_DEFAULT_DISPLAY);
     if (!eglInitialize(dpy, 0, 0))
         qWarning("Could not initialize EGL display - are the drivers loaded?");
     // Make sure that screen 0 is initialized.
     pvrQwsScreenWindow(0);
 }
~PvrEglScreen()
PvrEglScreen::~PvrEglScreen ()
Definition at line 79 of file pvreglscreen.cpp.
 {
     if (fd >= 0)
         ::close(fd);
 }
Functions
blit()
void PvrEglScreen::blit (const QImage & image, const QPoint & topLeft, const QRegion & region) virtual
Copies the given region in the given image to the point specified by topLeft using device coordinates.
This function is called from the exposeRegion() function; it is not intended to be called explicitly.
Reimplement this function to make use of Adding an Accelerated Graphics Driver to Qt for Embedded Linux{accelerated hardware}. Note that this function must be reimplemented if the framebuffer format is not supported by Qt for Embedded Linux (See the Qt for Embedded Linux Display Management{Display Management} documentation for more details).
See also
exposeRegion(), solidFill(), blank()
Reimplemented from QScreen.
Definition at line 169 of file pvreglscreen.cpp.
 {
     QGLScreen::blit(img, topLeft, region);
     sync();
 }
chooseContext()
bool PvrEglScreen::chooseContext (QGLContext * context, const QGLContext * shareContext) virtual
Initializes the context and sets up the QGLWindowSurface of the QWidget of context based on the parameters of context and based on its own requirements.
Since
4.3
The format() of context needs to be updated with the actual parameters of the OpenGLES drawable that was set up.
shareContext is used in the same way as for QGLContext. It is the context with which context shares display lists and texture ids etc. The window surface must be set up so that this sharing works.
Returns true in case of success and false if it is not possible to create the necessary OpenGLES drawable/context.
Since 4.4.2, this function will be not be called if options() indicates that a native window or pixmap drawable can be created via the functions in the surfaceFunctions() object.
This function is obsolete in Qt 4.5 and higher. Use surfaceFunctions() instead.
See also
options(), surfaceFunctions()
Reimplemented from QGLScreen.
Definition at line 182 of file pvreglscreen.cpp.
Referenced by solidFill().
 {
     // We use PvrEglScreenSurfaceFunctions instead.
     Q_UNUSED(context);
     Q_UNUSED(shareContext);
     return false;
 }
closeTty()
void PvrEglScreen::closeTty () private
Definition at line 312 of file pvreglscreen.cpp.
Referenced by shutdownDevice().
 {
     if (ttyfd == -1)
         return;
     if (doGraphicsMode)
         ioctl(ttyfd, KDSETMODE, oldKdMode);
     // Blankin' screen, blinkin' cursor!
     const char termctl[] = "\033[9;15]\033[?33h\033[?25h\033[?0c";
     ::write(ttyfd, termctl, sizeof(termctl));
     ::close(ttyfd);
     ttyfd = -1;
 }
connect()
bool PvrEglScreen::connect (const QString & displaySpec) virtual
This function is called by every Qt for Embedded Linux application on startup, and must be implemented to map in the framebuffer and the accelerated drivers that the graphics card control registers.
Note that connect must be called before the initDevice() function.
Ensure that true is returned if a connection to the screen device is made. Otherwise, return false. Upon making the connection, the function should read out the parameters of the framebuffer and use them as required to set this class's protected variables.
The displaySpec argument is passed by the QWS_DISPLAY environment variable or the -display command line parameter, and has the following syntax:
[screen driver][:driver specific options][:display number]
For example, to use the mach64 driver on fb1 as display 2:
Mach64:/dev/fb1:2
See Qt for Embedded Linux Display Management for more details.
See also
disconnect(), initDevice(), {Running Qt for Embedded Linux Applications}
Implements QScreen.
Definition at line 91 of file pvreglscreen.cpp.
 {
     if (!pvrQwsDisplayOpen())
         return false;
     // Initialize the QScreen properties.
     data = (uchar *)(pvrQwsDisplay.screens[0].mapped);
     w = pvrQwsDisplay.screens[0].screenRect.width;
     h = pvrQwsDisplay.screens[0].screenRect.height;
     lstep = pvrQwsDisplay.screens[0].screenStride;
     dw = w;
     dh = h;
     size = h * lstep;
     mapsize = size;
     switch (pvrQwsDisplay.screens[0].pixelFormat) {
     case PVR2D_RGB565:
             d = 16;
             setPixelFormat(QImage::Format_RGB16);
             break;
     case PVR2D_ARGB4444:
             d = 16;
             setPixelFormat(QImage::Format_ARGB4444_Premultiplied);
             break;
     case PVR2D_ARGB8888:
             d = 32;
             setPixelFormat(QImage::Format_ARGB32_Premultiplied);
             break;
         default:
             pvrQwsDisplayClose();
             qWarning("PvrEglScreen::connect: unsupported pixel format %d", (int)(pvrQwsDisplay.screens[0].pixelFormat));
             return false;
     }
     // Handle display physical size spec.
     QStringList displayArgs = displaySpec.split(QLatin1Char(':'));
     QRegExp mmWidthRx(QLatin1String("mmWidth=?(\\d+)"));
     int dimIdxW = displayArgs.indexOf(mmWidthRx);
     QRegExp mmHeightRx(QLatin1String("mmHeight=?(\\d+)"));
     int dimIdxH = displayArgs.indexOf(mmHeightRx);
     if (dimIdxW >= 0) {
         mmWidthRx.exactMatch(displayArgs.at(dimIdxW));
         physWidth = mmWidthRx.cap(1).toInt();
         if (dimIdxH < 0)
             physHeight = dh*physWidth/dw;
     }
     if (dimIdxH >= 0) {
         mmHeightRx.exactMatch(displayArgs.at(dimIdxH));
         physHeight = mmHeightRx.cap(1).toInt();
         if (dimIdxW < 0)
             physWidth = dw*physHeight/dh;
     }
     if (dimIdxW < 0 && dimIdxH < 0) {
         const int dpi = 72;
         physWidth = qRound(dw * 25.4 / dpi);
         physHeight = qRound(dh * 25.4 / dpi);
     }
     // Find the name of the tty device to use.
     QRegExp ttyRegExp(QLatin1String("tty=(.*)"));
     if (displayArgs.indexOf(ttyRegExp) != -1)
         ttyDevice = ttyRegExp.cap(1);
     if (displayArgs.contains(QLatin1String("nographicsmodeswitch")))
         doGraphicsMode = false;
     // The screen is ready.
     return true;
 }
createSurface() [1/2]
QWSWindowSurface * PvrEglScreen::createSurface (QWidget * widget) const virtual
[1]
Reimplemented from QScreen.
Definition at line 196 of file pvreglscreen.cpp.
 {
     if (qobject_cast<QGLWidget*>(widget))
         return new PvrEglWindowSurface(widget, (PvrEglScreen *)this, displayId);
     return QScreen::createSurface(widget);
 }
createSurface() [2/2]
QWSWindowSurface * PvrEglScreen::createSurface (const QString & key) const virtual
Creates and returns a new window surface matching the given key.
Since
4.2
The server application will call this function whenever it needs to create a server side representation of a window, e.g. when copying the content of memory to the screen using the screen driver.
Note that this function must be reimplemented when adding an accelerated graphics driver. See the Adding an Accelerated Graphics Driver to Qt for Embedded Linux {Adding an Accelerated Graphics Driver} documentation for details.
See also
{Qt for Embedded Linux Architecture}
Reimplemented from QScreen.
Definition at line 204 of file pvreglscreen.cpp.
 {
     if (key == QLatin1String("PvrEgl"))
         return new PvrEglWindowSurface();
     return QScreen::createSurface(key);
 }
disconnect()
void PvrEglScreen::disconnect () virtual
This function is called by every Qt for Embedded Linux application before exiting, and must be implemented to unmap the framebuffer.
Note that a server application will call the shutdownDevice() function prior to this function.
See also
connect(), shutdownDevice(), {Running Qt for Embedded Linux Applications}
Implements QScreen.
Definition at line 159 of file pvreglscreen.cpp.
 {
     pvrQwsDisplayClose();
 }
hasOpenGL()
bool PvrEglScreen::hasOpenGL () virtual
Implements QGLScreen.
Definition at line 190 of file pvreglscreen.cpp.
 {
     return true;
 }
initDevice()
bool PvrEglScreen::initDevice () virtual
This function is called by the Qt for Embedded Linux server to initialize the framebuffer.
Note that a server application will call the connect() function prior to this function.
Implement this function to make accelerated drivers set up the graphics card. Return true to indicate success and false to indicate failure.
See also
shutdownDevice(), connect()
Implements QScreen.
Definition at line 85 of file pvreglscreen.cpp.
 {
     openTty();
     return true;
 }
openTty()
void PvrEglScreen::openTty () private
Definition at line 279 of file pvreglscreen.cpp.
Referenced by initDevice().
 {
     const char *const devs[] = {"/dev/tty0", "/dev/tty", "/dev/console", 0};
     if (ttyDevice.isEmpty()) {
         for (const char * const *dev = devs; *dev; ++dev) {
             ttyfd = ::open(*dev, O_RDWR);
             if (ttyfd != -1)
                 break;
         }
     } else {
         ttyfd = ::open(ttyDevice.toAscii().constData(), O_RDWR);
     }
     if (ttyfd == -1)
         return;
     ::fcntl(ttyfd, F_SETFD, FD_CLOEXEC);
     if (doGraphicsMode) {
         ioctl(ttyfd, KDGETMODE, &oldKdMode);
         if (oldKdMode != KD_GRAPHICS) {
             int ret = ioctl(ttyfd, KDSETMODE, KD_GRAPHICS);
             if (ret == -1)
                 doGraphicsMode = false;
         }
     }
     // No blankin' screen, no blinkin' cursor!, no cursor!
     const char termctl[] = "\033[9;0]\033[?33l\033[?25l\033[?1c";
     ::write(ttyfd, termctl, sizeof(termctl));
 }
setMode()
void PvrEglScreen::setMode (int width, int height, int depth) inline virtual
Implement this function to reset the framebuffer's resolution (width and height) and bit depth.
After the resolution has been set, existing paint engines will be invalid and the framebuffer should be completely redrawn. In a multiple-process situation, all other applications must be notified to reset their mode and update themselves accordingly.
Implements QScreen.
Definition at line 74 of file pvreglscreen.h.
 {}
shutdownDevice()
void PvrEglScreen::shutdownDevice () virtual
This function is called by the Qt for Embedded Linux server before it calls the disconnect() function when exiting.
Note that the default implementation only hides the mouse cursor; reimplement this function to do the necessary graphics card specific cleanup.
See also
initDevice(), disconnect()
Reimplemented from QScreen.
Definition at line 164 of file pvreglscreen.cpp.
 {
     closeTty();
 }
solidFill()
void PvrEglScreen::solidFill (const QColor & color, const QRegion & region) virtual
Fills the given region of the screen with the specified color.
This function is called from the exposeRegion() function; it is not intended to be called explicitly.
Reimplement this function to make use of Adding an Accelerated Graphics Driver to Qt for Embedded Linux{accelerated hardware}. Note that this function must be reimplemented if the framebuffer format is not supported by Qt for Embedded Linux (See the Qt for Embedded Linux Display Management{Display Management} documentation for more details).
See also
exposeRegion(), blit(), blank()
Reimplemented from QScreen.
Definition at line 175 of file pvreglscreen.cpp.
Referenced by PvrEglWindowSurface::setDirectRegion().
 {
     QGLScreen::solidFill(color, region);
     sync();
 }
sync()
void PvrEglScreen::sync () private
Definition at line 274 of file pvreglscreen.cpp.
Referenced by blit(), and solidFill().
 {
     // Put code here to synchronize 2D and 3D operations if necessary.
 }
transformation()
int PvrEglScreen::transformation () const
Definition at line 249 of file pvreglscreen.cpp.
Referenced by PvrEglWindowSurface::move(), PvrEglWindowSurface::PvrEglWindowSurface(), PvrEglWindowSurface::setDirectRegion(), PvrEglWindowSurface::setGeometry(), and PvrEglWindowSurface::transformRects().
 {
     // We need to search for our parent screen, which is assumed to be
     // "Transformed".  If it isn't, then there is no transformation.
     // There is no direct method to get the parent screen so we need
     // to search every screen until we find ourselves.
     if (!parent && qt_screen != this)
         parent = parentScreen(qt_screen, this);
     if (!parent)
         return 0;
     if (parent->classId() != QScreen::TransformedClass)
         return 0;
     return 90 * static_cast<const QTransformedScreen *>(parent)
                     ->transformOrientation();
 }
Properties
doGraphicsMode
bool PvrEglScreen::doGraphicsMode private
Definition at line 95 of file pvreglscreen.h.
Referenced by closeTty(), connect(), openTty(), and PvrEglScreen().
fd
int PvrEglScreen::fd private
Definition at line 92 of file pvreglscreen.h.
Referenced by PvrEglScreen(), and ~PvrEglScreen().
oldKdMode
int PvrEglScreen::oldKdMode private
Definition at line 93 of file pvreglscreen.h.
Referenced by closeTty(), openTty(), and PvrEglScreen().
parent
const QScreen* PvrEglScreen::parent mutable private
Definition at line 96 of file pvreglscreen.h.
Referenced by parentScreen(), PvrEglScreen(), and transformation().
ttyDevice
QString PvrEglScreen::ttyDevice private
Definition at line 94 of file pvreglscreen.h.
Referenced by connect(), and openTty().
ttyfd
int PvrEglScreen::ttyfd private
Definition at line 93 of file pvreglscreen.h.
Referenced by closeTty(), openTty(), and PvrEglScreen().
The documentation for this class was generated from the following files:
/src/plugins/gfxdrivers/powervr/pvreglscreen/pvreglscreen.h
/src/plugins/gfxdrivers/powervr/pvreglscreen/pvreglscreen.cpp