Qt 4.8: QPinchGesture Class Reference
QPinchGesture Class Reference
The QPinchGesture class describes a pinch gesture made by the user.
#include <qgesture.h>
Public Types
enum ChangeFlag { ScaleFactorChanged = 0x1, RotationAngleChanged = 0x2, CenterPointChanged = 0x4 }
This enum describes the changes that can occur to the properties of the gesture object.
Public Types inherited from QGesture
enum GestureCancelPolicy { CancelNone = 0, CancelAllInContext }
This enum describes how accepting a gesture can cancel other gestures automatically.
Public Functions
QPointF centerPoint () const
ChangeFlags changeFlags () const
QPointF lastCenterPoint () const
qreal lastRotationAngle () const
qreal lastScaleFactor () const
QPinchGesture (QObject *parent=0)
qreal rotationAngle () const
qreal scaleFactor () const
void setCenterPoint (const QPointF &value)
void setChangeFlags (ChangeFlags value)
void setLastCenterPoint (const QPointF &value)
void setLastRotationAngle (qreal value)
void setLastScaleFactor (qreal value)
void setRotationAngle (qreal value)
void setScaleFactor (qreal value)
void setStartCenterPoint (const QPointF &value)
void setTotalChangeFlags (ChangeFlags value)
void setTotalRotationAngle (qreal value)
void setTotalScaleFactor (qreal value)
QPointF startCenterPoint () const
ChangeFlags totalChangeFlags () const
qreal totalRotationAngle () const
qreal totalScaleFactor () const
Public Functions inherited from QGesture
GestureCancelPolicy gestureCancelPolicy () const
Qt::GestureType gestureType () const
bool hasHotSpot () const
QPointF hotSpot () const
QGesture (QObject *parent=0)
Constructs a new gesture object with the given parent.
void setGestureCancelPolicy (GestureCancelPolicy policy)
void setHotSpot (const QPointF &value)
Qt::GestureState state () const
void unsetHotSpot ()
~QGesture ()
Destroys the gesture object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
QPointF centerPoint
the current center point
ChangeFlags changeFlags
the property of the gesture that has changed in the current step
QPointF lastCenterPoint
the last position of the center point recorded for this gesture
qreal lastRotationAngle
the last reported angle covered by the gesture motion
qreal lastScaleFactor
the last scale factor recorded for this gesture
qreal rotationAngle
the angle covered by the gesture motion
qreal scaleFactor
the current scale factor
QPointF startCenterPoint
the starting position of the center point
ChangeFlags totalChangeFlags
the property of the gesture that has change
qreal totalRotationAngle
the total angle covered by the gesture
qreal totalScaleFactor
the total scale factor
Friends
class QPinchGestureRecognizer
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QGesture
QGesture (QGesturePrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPinchGesture class describes a pinch gesture made by the user.
Since
4.6
A pinch gesture is a form of touch user input in which the user typically touches two points on the input device with a thumb and finger, before moving them closer together or further apart to change the scale factor, zoom, or level of detail of the user interface.
For an overview of gesture handling in Qt and information on using gestures in your applications, see the Gestures Programming document.
Instead of repeatedly applying the same pinching gesture, the user may continue to touch the input device in one place, and apply a second touch to a new point, continuing the gesture. When this occurs, gesture events will continue to be delivered to the target object, containing an instance of QPinchGesture in the Qt::GestureUpdated state.
See also
QPanGesture, QSwipeGesture
Definition at line 136 of file qgesture.h.
Enumerations
ChangeFlag
enum QPinchGesture::ChangeFlag
This enum describes the changes that can occur to the properties of the gesture object.
ScaleFactorChanged The scale factor held by scaleFactor changed.
RotationAngleChanged The rotation angle held by rotationAngle changed.
CenterPointChanged The center point held by centerPoint changed.
See also
changeFlags, totalChangeFlags
Enumerator
ScaleFactorChanged
RotationAngleChanged
CenterPointChanged
Definition at line 143 of file qgesture.h.
                     {
         ScaleFactorChanged = 0x1,
         RotationAngleChanged = 0x2,
         CenterPointChanged = 0x4
     };
Constructors and Destructors
QPinchGesture()
QPinchGesture::QPinchGesture (QObject * parent = 0)
Warning
This function is not part of the public interface.
Definition at line 560 of file qgesture.cpp.
     : QGesture(*new QPinchGesturePrivate, parent)
 {
     d_func()->gestureType = Qt::PinchGesture;
 }
Functions
centerPoint()
QPointF QPinchGesture::centerPoint () const
Referenced by setChangeFlags().
changeFlags()
ChangeFlags QPinchGesture::changeFlags () const
Referenced by setTotalChangeFlags().
lastCenterPoint()
QPointF QPinchGesture::lastCenterPoint () const
Referenced by setChangeFlags().
lastRotationAngle()
qreal QPinchGesture::lastRotationAngle () const
Referenced by setScaleFactor().
lastScaleFactor()
qreal QPinchGesture::lastScaleFactor () const
Referenced by setCenterPoint().
rotationAngle()
qreal QPinchGesture::rotationAngle () const
Referenced by setScaleFactor().
scaleFactor()
qreal QPinchGesture::scaleFactor () const
Referenced by setCenterPoint().
setCenterPoint()
void QPinchGesture::setCenterPoint (const QPointF & value)
Definition at line 611 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->centerPoint = value;
 }
setChangeFlags()
void QPinchGesture::setChangeFlags (ChangeFlags value)
Definition at line 581 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->changeFlags = value;
 }
setLastCenterPoint()
void QPinchGesture::setLastCenterPoint (const QPointF & value)
Definition at line 606 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::reset().
 {
     d_func()->lastCenterPoint = value;
 }
setLastRotationAngle()
void QPinchGesture::setLastRotationAngle (qreal value)
Definition at line 668 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->lastRotationAngle = value;
 }
setLastScaleFactor()
void QPinchGesture::setLastScaleFactor (qreal value)
Definition at line 637 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->lastScaleFactor = value;
 }
setRotationAngle()
void QPinchGesture::setRotationAngle (qreal value)
Definition at line 673 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->rotationAngle = value;
 }
setScaleFactor()
void QPinchGesture::setScaleFactor (qreal value)
Definition at line 642 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->scaleFactor = value;
 }
setStartCenterPoint()
void QPinchGesture::setStartCenterPoint (const QPointF & value)
Definition at line 601 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->startCenterPoint = value;
 }
setTotalChangeFlags()
void QPinchGesture::setTotalChangeFlags (ChangeFlags value)
Definition at line 571 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::recognize(), and QMacPinchGestureRecognizer::reset().
 {
     d_func()->totalChangeFlags = value;
 }
setTotalRotationAngle()
void QPinchGesture::setTotalRotationAngle (qreal value)
Definition at line 663 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::reset().
 {
     d_func()->totalRotationAngle = value;
 }
setTotalScaleFactor()
void QPinchGesture::setTotalScaleFactor (qreal value)
Definition at line 632 of file qgesture.cpp.
Referenced by QMacPinchGestureRecognizer::reset().
 {
     d_func()->totalScaleFactor = value;
 }
startCenterPoint()
QPointF QPinchGesture::startCenterPoint () const
Referenced by setChangeFlags().
totalChangeFlags()
ChangeFlags QPinchGesture::totalChangeFlags () const
Referenced by QPinchGesture().
totalRotationAngle()
qreal QPinchGesture::totalRotationAngle () const
Referenced by setScaleFactor().
totalScaleFactor()
qreal QPinchGesture::totalScaleFactor () const
Referenced by setCenterPoint().
Friends and Related Functions
QPinchGestureRecognizer
friend class QPinchGestureRecognizer friend
Definition at line 195 of file qgesture.h.
Properties
centerPoint
QPointF QPinchGesture::centerPoint
the current center point
The center point is the midpoint between the two input points in the gesture.
See also
startCenterPoint, lastCenterPoint
Definition at line 163 of file qgesture.h.
changeFlags
QPinchGesture::ChangeFlags QPinchGesture::changeFlags
the property of the gesture that has changed in the current step
This property indicates which of the other properties has changed since the previous gesture event included information about this gesture. You can use this information to determine which aspect of your user interface needs to be updated.
See also
totalChangeFlags, scaleFactor, rotationAngle, centerPoint
Definition at line 151 of file qgesture.h.
Referenced by QMacPinchGestureRecognizer::recognize().
lastCenterPoint
QPointF QPinchGesture::lastCenterPoint
the last position of the center point recorded for this gesture
See also
centerPoint, startCenterPoint
Definition at line 162 of file qgesture.h.
lastRotationAngle
qreal QPinchGesture::lastRotationAngle
the last reported angle covered by the gesture motion
The last rotation angle is the angle as reported in the rotationAngle property when a previous gesture event was delivered for this gesture.
See also
rotationAngle, totalRotationAngle
Definition at line 158 of file qgesture.h.
lastScaleFactor
qreal QPinchGesture::lastScaleFactor
the last scale factor recorded for this gesture
The last scale factor contains the scale factor reported in the scaleFactor property when a previous gesture event included information about this gesture.
If no previous event was delivered with information about this gesture (i.e., this gesture object contains information about the first movement in the gesture) then this property contains zero.
See also
scaleFactor, totalScaleFactor
Definition at line 154 of file qgesture.h.
rotationAngle
qreal QPinchGesture::rotationAngle
the angle covered by the gesture motion
See also
totalRotationAngle, lastRotationAngle
Definition at line 159 of file qgesture.h.
Referenced by QMacPinchGestureRecognizer::recognize().
scaleFactor
qreal QPinchGesture::scaleFactor
the current scale factor
The scale factor measures the scale factor associated with the distance between two of the user's inputs on a touch device.
See also
totalScaleFactor, lastScaleFactor
Definition at line 155 of file qgesture.h.
Referenced by QMacPinchGestureRecognizer::recognize().
startCenterPoint
QPointF QPinchGesture::startCenterPoint
the starting position of the center point
See also
centerPoint, lastCenterPoint
Definition at line 161 of file qgesture.h.
Referenced by QMacPinchGestureRecognizer::recognize().
totalChangeFlags
QPinchGesture::ChangeFlags QPinchGesture::totalChangeFlags
the property of the gesture that has change
This property indicates which of the other properties has changed since the gesture has started. You can use this information to determine which aspect of your user interface needs to be updated.
See also
changeFlags, scaleFactor, rotationAngle, centerPoint
Definition at line 150 of file qgesture.h.
Referenced by QMacPinchGestureRecognizer::recognize().
totalRotationAngle
qreal QPinchGesture::totalRotationAngle
the total angle covered by the gesture
This total angle measures the complete angle covered by the gesture. Usually, this is equal to the value held by the rotationAngle property, except in the case where the user performs multiple rotations by removing and repositioning one of the touch points, as described above. In this case, the total angle will be the sum of the rotation angles for the multiple stages of the gesture.
See also
rotationAngle, lastRotationAngle
Definition at line 157 of file qgesture.h.
totalScaleFactor
qreal QPinchGesture::totalScaleFactor
the total scale factor
The total scale factor measures the total change in scale factor from the original value to the current scale factor.
See also
scaleFactor, lastScaleFactor
Definition at line 153 of file qgesture.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qgesture.h
/src/gui/kernel/qgesture.cpp