Qt 4.8: QGLContextGroup Class Reference
QGLContextGroup Class Reference
#include <qgl_p.h>
Public Functions
void addGuard (QGLSharedResourceGuard *guard)
const QGLContext * context () const
QGLExtensionFuncs & extensionFuncs ()
bool isSharing () const
void removeGuard (QGLSharedResourceGuard *guard)
QList< const QGLContext * > shares () const
~QGLContextGroup ()
Private Functions
QGLContextGroup (const QGLContext *context)
Properties
const QGLContext * m_context
QGLExtensionFuncs m_extensionFuncs
QGLSharedResourceGuard * m_guards
QAtomicInt m_refs
QHash< QGLContextGroupResourceBase *, void * > m_resources
QList< const QGLContext * > m_shares
Friends
class QGLContext
class QGLContextGroupResourceBase
class QGLContextPrivate
static void addShare (const QGLContext *context, const QGLContext *share)
static void removeShare (const QGLContext *context)
void cleanupResources (const QGLContext *ctx)
Detailed Description
Definition at line 246 of file qgl_p.h.
Constructors and Destructors
~QGLContextGroup()
QGLContextGroup::~QGLContextGroup ()
Definition at line 1685 of file qgl.cpp.
 {
     // Clear any remaining QGLSharedResourceGuard objects on the group.
     QGLSharedResourceGuard *guard = m_guards;
     while (guard != 0) {
         guard->m_group = 0;
         guard->m_id = 0;
         guard = guard->m_next;
     }
     qt_context_groups()->remove(this);
 }
QGLContextGroup()
QGLContextGroup::QGLContextGroup (const QGLContext * context) private
Definition at line 1679 of file qgl.cpp.
     : m_context(context), m_guards(0), m_refs(1)
 {
     qt_context_groups()->append(this);
 }
Functions
addGuard()
void QGLContextGroup::addGuard (QGLSharedResourceGuard * guard)
Definition at line 1697 of file qgl.cpp.
 {
     if (m_guards)
         m_guards->m_prev = guard;
     guard->m_next = m_guards;
     guard->m_prev = 0;
     m_guards = guard;
 }
addShare()
void QGLContextGroup::addShare (const QGLContext * context, const QGLContext * share) static
Definition at line 5846 of file qgl.cpp.
Referenced by QGLPixelBufferPrivate::common_init(), and QX11GLPixmapData::paintEngine().
{
     Q_ASSERT(context && share);
     if (context->d_ptr->group == share->d_ptr->group)
         return;
     // Make sure 'context' is not already shared with another group of contexts.
     Q_ASSERT(context->d_ptr->group->m_refs == 1);
     // Free 'context' group resources and make it use the same resources as 'share'.
     QGLContextGroup *group = share->d_ptr->group;
     delete context->d_ptr->group;
     context->d_ptr->group = group;
     group->m_refs.ref();
     // Maintain a list of all the contexts in each group of sharing contexts.
     // The list is empty if the "share" context wasn't sharing already.
     if (group->m_shares.isEmpty())
         group->m_shares.append(share);
     group->m_shares.append(context);
 }
cleanupResources()
void QGLContextGroup::cleanupResources (const QGLContext * ctx) private
Definition at line 5961 of file qgl.cpp.
 {
     // Notify all resources that a context has been deleted
     QHash<QGLContextGroupResourceBase *, void *>::ConstIterator it;
     for (it = m_resources.begin(); it != m_resources.end(); ++it)
         it.key()->contextDeleted(context);
     // If there are still shares, then no cleanup to be done yet.
     if (m_shares.size() > 1)
         return;
     // Iterate over all resources and free each in turn.
     for (it = m_resources.begin(); it != m_resources.end(); ++it)
         it.key()->cleanup(context, it.value());
 }
context()
const QGLContext* QGLContextGroup::context () const inline
Definition at line 252 of file qgl_p.h.
Referenced by QGL2PaintEngineExPrivate::drawCachedGlyphs().
 {return m_context;}
extensionFuncs()
QGLExtensionFuncs& QGLContextGroup::extensionFuncs () inline
Definition at line 251 of file qgl_p.h.
Referenced by QGLContextPrivate::extensionFuncs().
 {return m_extensionFuncs;}
isSharing()
bool QGLContextGroup::isSharing () const inline
Definition at line 253 of file qgl_p.h.
 { return m_shares.size() >= 2; }
removeGuard()
void QGLContextGroup::removeGuard (QGLSharedResourceGuard * guard)
Definition at line 1706 of file qgl.cpp.
 {
     if (guard->m_next)
         guard->m_next->m_prev = guard->m_prev;
     if (guard->m_prev)
         guard->m_prev->m_next = guard->m_next;
     else
         m_guards = guard->m_next;
 }
removeShare()
void QGLContextGroup::removeShare (const QGLContext * context) static
Definition at line 5867 of file qgl.cpp.
Referenced by QGLContext::chooseMacVisual(), QGLContext::choosePixelFormat(), qDeleteQGLContext(), QGLContext::reset(), and QGLContext::tryVisual().
{
     // Remove the context from the group.
     QGLContextGroup *group = context->d_ptr->group;
     if (group->m_shares.isEmpty())
         return;
     group->m_shares.removeAll(context);
     // Update context group representative.
     Q_ASSERT(group->m_shares.size() != 0);
     if (group->m_context == context)
         group->m_context = group->m_shares[0];
     // If there is only one context left, then make the list empty.
     if (group->m_shares.size() == 1)
         group->m_shares.clear();
 }
shares()
QList<const QGLContext *> QGLContextGroup::shares () const inline
Definition at line 254 of file qgl_p.h.
 { return m_shares; }
Friends and Related Functions
QGLContext
friend class QGLContext friend
Definition at line 274 of file qgl_p.h.
QGLContextGroupResourceBase
friend class QGLContextGroupResourceBase friend
Definition at line 276 of file qgl_p.h.
QGLContextPrivate
friend class QGLContextPrivate friend
Definition at line 275 of file qgl_p.h.
Properties
m_context
const QGLContext* QGLContextGroup::m_context private
Definition at line 266 of file qgl_p.h.
m_extensionFuncs
QGLExtensionFuncs QGLContextGroup::m_extensionFuncs private
Definition at line 265 of file qgl_p.h.
m_guards
QGLSharedResourceGuard* QGLContextGroup::m_guards private
Definition at line 269 of file qgl_p.h.
m_refs
QAtomicInt QGLContextGroup::m_refs private
Definition at line 270 of file qgl_p.h.
m_resources
QHash<QGLContextGroupResourceBase *, void *> QGLContextGroup::m_resources private
Definition at line 268 of file qgl_p.h.
m_shares
QList<const QGLContext *> QGLContextGroup::m_shares private
Definition at line 267 of file qgl_p.h.
The documentation for this class was generated from the following files:
/src/opengl/qgl_p.h
/src/opengl/qgl.cpp