Qt 4.8: QScript::QScriptMetaMethod Class Reference
QScript::QScriptMetaMethod Class Reference
Public Functions
int argumentCount () const
QScriptMetaType argumentType (int arg) const
int count () const
int firstUnresolvedIndex () const
bool fullyResolved () const
bool hasUnresolvedReturnType () const
bool isValid () const
QScriptMetaMethod ()
QScriptMetaMethod (const QVector< QScriptMetaType > &types)
QScriptMetaType returnType () const
QScriptMetaType type (int index) const
QVector< QScriptMetaType > types () const
Properties
int m_firstUnresolvedIndex
QVector< QScriptMetaType > m_types
Detailed Description
Definition at line 445 of file qscriptqobject.cpp.
Constructors and Destructors
QScriptMetaMethod() [1/2]
QScript::QScriptMetaMethod::QScriptMetaMethod () inline
Definition at line 448 of file qscriptqobject.cpp.
         { }
QScriptMetaMethod() [2/2]
QScript::QScriptMetaMethod::QScriptMetaMethod (const QVector< QScriptMetaType > & types) inline
Definition at line 450 of file qscriptqobject.cpp.
         : m_types(types), m_firstUnresolvedIndex(-1)
     {
         QVector<QScriptMetaType>::const_iterator it;
         for (it = m_types.constBegin(); it != m_types.constEnd(); ++it) {
             if ((*it).kind() == QScriptMetaType::Unresolved) {
                 m_firstUnresolvedIndex = it - m_types.constBegin();
                 break;
             }
         }
     }
Functions
argumentCount()
int QScript::QScriptMetaMethod::argumentCount () const inline
Definition at line 467 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_types.count() - 1; }
argumentType()
QScriptMetaType QScript::QScriptMetaMethod::argumentType (int arg) const inline
Definition at line 470 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_types.at(arg + 1); }
count()
int QScript::QScriptMetaMethod::count () const inline
Definition at line 482 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_types.count(); }
firstUnresolvedIndex()
int QScript::QScriptMetaMethod::firstUnresolvedIndex () const inline
Definition at line 479 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_firstUnresolvedIndex; }
fullyResolved()
bool QScript::QScriptMetaMethod::fullyResolved () const inline
Definition at line 473 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_firstUnresolvedIndex == -1; }
hasUnresolvedReturnType()
bool QScript::QScriptMetaMethod::hasUnresolvedReturnType () const inline
Definition at line 476 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return (m_firstUnresolvedIndex == 0); }
isValid()
bool QScript::QScriptMetaMethod::isValid () const inline
Definition at line 461 of file qscriptqobject.cpp.
     { return !m_types.isEmpty(); }
returnType()
QScriptMetaType QScript::QScriptMetaMethod::returnType () const inline
Definition at line 464 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_types.at(0); }
type()
QScriptMetaType QScript::QScriptMetaMethod::type (int index) const inline
Definition at line 485 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_types.at(index); }
types()
QVector<QScriptMetaType> QScript::QScriptMetaMethod::types () const inline
Definition at line 488 of file qscriptqobject.cpp.
Referenced by QScript::callQtMethod().
     { return m_types; }
Properties
m_firstUnresolvedIndex
int QScript::QScriptMetaMethod::m_firstUnresolvedIndex private
Definition at line 493 of file qscriptqobject.cpp.
m_types
QVector<QScriptMetaType> QScript::QScriptMetaMethod::m_types private
Definition at line 492 of file qscriptqobject.cpp.
The documentation for this class was generated from the following file:
/src/script/bridge/qscriptqobject.cpp