Qt 4.8: QNetworkConfigurationManagerPrivate Class Reference
QNetworkConfigurationManagerPrivate Class Reference
#include <qnetworkconfigmanager_p.h>
Public Slots
static void addPostRoutine ()
void updateConfigurations ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void configurationAdded (const QNetworkConfiguration &config)
void configurationChanged (const QNetworkConfiguration &config)
void configurationRemoved (const QNetworkConfiguration &config)
void configurationUpdateComplete ()
void onlineStateChanged (bool isOnline)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QList< QNetworkConfiguration > allConfigurations (QNetworkConfiguration::StateFlags filter) const
QNetworkConfigurationManager::Capabilities capabilities () const
void cleanup ()
QNetworkConfiguration configurationFromIdentifier (const QString &identifier) const
QNetworkConfiguration defaultConfiguration () const
void disablePolling ()
void enablePolling ()
QList< QBearerEngine * > engines () const
void initialize ()
bool isOnline () const
void performAsyncConfigurationUpdate ()
QNetworkConfigurationManagerPrivate ()
virtual ~QNetworkConfigurationManagerPrivate ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void configurationAdded (QNetworkConfigurationPrivatePointer ptr)
void configurationChanged (QNetworkConfigurationPrivatePointer ptr)
void configurationRemoved (QNetworkConfigurationPrivatePointer ptr)
void pollEngines ()
Private Functions
Q_INVOKABLE void startPolling ()
Properties
QThread * bearerThread
bool firstUpdate
int forcedPolling
QMutex mutex
QSet< QString > onlineConfigurations
QSet< QBearerEngine * > pollingEngines
QTimer * pollTimer
QList< QBearerEngine * > sessionEngines
bool updating
QSet< QBearerEngine * > updatingEngines
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 69 of file qnetworkconfigmanager_p.h.
Constructors and Destructors
QNetworkConfigurationManagerPrivate()
QNetworkConfigurationManagerPrivate::QNetworkConfigurationManagerPrivate ()
Referenced by connManager().
~QNetworkConfigurationManagerPrivate()
QNetworkConfigurationManagerPrivate::~QNetworkConfigurationManagerPrivate () virtual
Definition at line 79 of file qnetworkconfigmanager_p.cpp.
 {
     QMutexLocker locker(&mutex);
     qDeleteAll(sessionEngines);
     if (bearerThread)
         bearerThread->quit();
 }
Functions
addPostRoutine
void QNetworkConfigurationManagerPrivate::addPostRoutine () static slot
Definition at line 71 of file qnetworkconfigmanager.cpp.
Referenced by connManager().
 {
     qAddPostRoutine(connManager_cleanup);
 }
allConfigurations()
QList< QNetworkConfiguration > QNetworkConfigurationManagerPrivate::allConfigurations (QNetworkConfiguration::StateFlags filter) const
Definition at line 213 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::allConfigurations().
 {
     QList<QNetworkConfiguration> result;
     QMutexLocker locker(&mutex);
     foreach (QBearerEngine *engine, sessionEngines) {
         QHash<QString, QNetworkConfigurationPrivatePointer>::Iterator it;
         QHash<QString, QNetworkConfigurationPrivatePointer>::Iterator end;
         QMutexLocker locker(&engine->mutex);
         //find all InternetAccessPoints
         for (it = engine->accessPointConfigurations.begin(),
              end = engine->accessPointConfigurations.end(); it != end; ++it) {
             QNetworkConfigurationPrivatePointer ptr = it.value();
             QMutexLocker configLocker(&ptr->mutex);
             if ((ptr->state & filter) == filter) {
                 QNetworkConfiguration pt;
                 pt.d = ptr;
                 result << pt;
             }
         }
         //find all service networks
         for (it = engine->snapConfigurations.begin(),
              end = engine->snapConfigurations.end(); it != end; ++it) {
             QNetworkConfigurationPrivatePointer ptr = it.value();
             QMutexLocker configLocker(&ptr->mutex);
             if ((ptr->state & filter) == filter) {
                 QNetworkConfiguration pt;
                 pt.d = ptr;
                 result << pt;
             }
         }
     }
     return result;
 }
capabilities()
QNetworkConfigurationManager::Capabilities QNetworkConfigurationManagerPrivate::capabilities () const
Definition at line 288 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::capabilities().
 {
     QMutexLocker locker(&mutex);
     QNetworkConfigurationManager::Capabilities capFlags;
     foreach (QBearerEngine *engine, sessionEngines)
         capFlags |= engine->capabilities();
     return capFlags;
 }
cleanup()
void QNetworkConfigurationManagerPrivate::cleanup ()
Definition at line 88 of file qnetworkconfigmanager_p.cpp.
Referenced by connManager_cleanup().
 {
     QThread* thread = bearerThread;
     deleteLater();
     if(thread->wait(5000))
         delete thread;
 }
configurationAdded [1/2]
void QNetworkConfigurationManagerPrivate::configurationAdded (const QNetworkConfiguration & config) signal
Referenced by configurationAdded(), and updateConfigurations().
configurationAdded [2/2]
void QNetworkConfigurationManagerPrivate::configurationAdded (QNetworkConfigurationPrivatePointer ptr) private slot
Definition at line 300 of file qnetworkconfigmanager_p.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!firstUpdate) {
         QNetworkConfiguration item;
         item.d = ptr;
         emit configurationAdded(item);
     }
     ptr->mutex.lock();
     if (ptr->state == QNetworkConfiguration::Active) {
         ptr->mutex.unlock();
         onlineConfigurations.insert(ptr->id);
         if (!firstUpdate && onlineConfigurations.count() == 1)
             emit onlineStateChanged(true);
     } else {
         ptr->mutex.unlock();
     }
 }
configurationChanged [1/2]
void QNetworkConfigurationManagerPrivate::configurationChanged (const QNetworkConfiguration & config) signal
Referenced by configurationChanged(), and updateConfigurations().
configurationChanged [2/2]
void QNetworkConfigurationManagerPrivate::configurationChanged (QNetworkConfigurationPrivatePointer ptr) private slot
Definition at line 340 of file qnetworkconfigmanager_p.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!firstUpdate) {
         QNetworkConfiguration item;
         item.d = ptr;
         emit configurationChanged(item);
     }
     bool previous = !onlineConfigurations.isEmpty();
     ptr->mutex.lock();
     if (ptr->state == QNetworkConfiguration::Active)
         onlineConfigurations.insert(ptr->id);
     else
         onlineConfigurations.remove(ptr->id);
     ptr->mutex.unlock();
     bool online = !onlineConfigurations.isEmpty();
     if (!firstUpdate && online != previous)
         emit onlineStateChanged(online);
 }
configurationFromIdentifier()
QNetworkConfiguration QNetworkConfigurationManagerPrivate::configurationFromIdentifier (const QString & identifier) const
Definition at line 257 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::configurationFromIdentifier().
 {
     QNetworkConfiguration item;
     QMutexLocker locker(&mutex);
     foreach (QBearerEngine *engine, sessionEngines) {
         QMutexLocker locker(&engine->mutex);
         if (engine->accessPointConfigurations.contains(identifier))
             item.d = engine->accessPointConfigurations[identifier];
         else if (engine->snapConfigurations.contains(identifier))
             item.d = engine->snapConfigurations[identifier];
         else if (engine->userChoiceConfigurations.contains(identifier))
             item.d = engine->userChoiceConfigurations[identifier];
         else
             continue;
         return item;
     }
     return item;
 }
configurationRemoved [1/2]
void QNetworkConfigurationManagerPrivate::configurationRemoved (const QNetworkConfiguration & config) signal
Referenced by configurationRemoved(), and updateConfigurations().
configurationRemoved [2/2]
void QNetworkConfigurationManagerPrivate::configurationRemoved (QNetworkConfigurationPrivatePointer ptr) private slot
Definition at line 321 of file qnetworkconfigmanager_p.cpp.
 {
     QMutexLocker locker(&mutex);
     ptr->mutex.lock();
     ptr->isValid = false;
     ptr->mutex.unlock();
     if (!firstUpdate) {
         QNetworkConfiguration item;
         item.d = ptr;
         emit configurationRemoved(item);
     }
     onlineConfigurations.remove(ptr->id);
     if (!firstUpdate && onlineConfigurations.isEmpty())
         emit onlineStateChanged(false);
 }
configurationUpdateComplete
void QNetworkConfigurationManagerPrivate::configurationUpdateComplete () signal
Referenced by performAsyncConfigurationUpdate(), QNetworkConfigurationManager::QNetworkConfigurationManager(), and updateConfigurations().
defaultConfiguration()
QNetworkConfiguration QNetworkConfigurationManagerPrivate::defaultConfiguration () const
Definition at line 96 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::defaultConfiguration().
 {
     QMutexLocker locker(&mutex);
     foreach (QBearerEngine *engine, sessionEngines) {
         QNetworkConfigurationPrivatePointer ptr = engine->defaultConfiguration();
         if (ptr) {
             QNetworkConfiguration config;
             config.d = ptr;
             return config;
         }
     }
     // Engines don't have a default configuration.
     // Return first active snap
     QNetworkConfigurationPrivatePointer defaultConfiguration;
     foreach (QBearerEngine *engine, sessionEngines) {
         QHash<QString, QNetworkConfigurationPrivatePointer>::Iterator it;
         QHash<QString, QNetworkConfigurationPrivatePointer>::Iterator end;
         QMutexLocker locker(&engine->mutex);
         for (it = engine->snapConfigurations.begin(),
              end = engine->snapConfigurations.end(); it != end; ++it) {
             QNetworkConfigurationPrivatePointer ptr = it.value();
             QMutexLocker configLocker(&ptr->mutex);
             if ((ptr->state & QNetworkConfiguration::Active) == QNetworkConfiguration::Active) {
                 QNetworkConfiguration config;
                 config.d = ptr;
                 return config;
             } else if (!defaultConfiguration) {
                 if ((ptr->state & QNetworkConfiguration::Discovered) == QNetworkConfiguration::Discovered)
                     defaultConfiguration = ptr;
             }
         }
     }
     // No Active SNAPs return first Discovered SNAP.
     if (defaultConfiguration) {
         QNetworkConfiguration config;
         config.d = defaultConfiguration;
         return config;
     }
     /*
         No Active or Discovered SNAPs, find the perferred access point.
         The following priority order is used:
             1. Active Ethernet
             2. Active WLAN
             3. Active Other
             4. Discovered Ethernet
             5. Discovered WLAN
             6. Discovered Other
     */
     foreach (QBearerEngine *engine, sessionEngines) {
         QHash<QString, QNetworkConfigurationPrivatePointer>::Iterator it;
         QHash<QString, QNetworkConfigurationPrivatePointer>::Iterator end;
         QMutexLocker locker(&engine->mutex);
         for (it = engine->accessPointConfigurations.begin(),
              end = engine->accessPointConfigurations.end(); it != end; ++it) {
             QNetworkConfigurationPrivatePointer ptr = it.value();
             QMutexLocker configLocker(&ptr->mutex);
             QNetworkConfiguration::BearerType bearerType = ptr->bearerType;
             if ((ptr->state & QNetworkConfiguration::Discovered) == QNetworkConfiguration::Discovered) {
                 if (!defaultConfiguration) {
                     defaultConfiguration = ptr;
                 } else {
                     QMutexLocker defaultConfigLocker(&defaultConfiguration->mutex);
                     if (defaultConfiguration->state == ptr->state) {
                         switch (defaultConfiguration->bearerType) {
                         case QNetworkConfiguration::BearerEthernet:
                             // do nothing
                             break;
                         case QNetworkConfiguration::BearerWLAN:
                             // Ethernet beats WLAN
                             defaultConfiguration = ptr;
                             break;
                         default:
                             // Ethernet and WLAN beats other
                             if (bearerType == QNetworkConfiguration::BearerEthernet ||
                                 bearerType == QNetworkConfiguration::BearerWLAN) {
                                 defaultConfiguration = ptr;
                             }
                         }
                     } else {
                         // active beats discovered
                         if ((defaultConfiguration->state & QNetworkConfiguration::Active) !=
                             QNetworkConfiguration::Active) {
                             defaultConfiguration = ptr;
                         }
                     }
                 }
             }
         }
     }
     // No Active InternetAccessPoint return first Discovered InternetAccessPoint.
     if (defaultConfiguration) {
         QNetworkConfiguration config;
         config.d = defaultConfiguration;
         return config;
     }
     return QNetworkConfiguration();
 }
disablePolling()
void QNetworkConfigurationManagerPrivate::disablePolling ()
Definition at line 506 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::~QNetworkConfigurationManager().
 {
     QMutexLocker locker(&mutex);
     --forcedPolling;
 }
enablePolling()
void QNetworkConfigurationManagerPrivate::enablePolling ()
Definition at line 496 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::QNetworkConfigurationManager().
 {
     QMutexLocker locker(&mutex);
     ++forcedPolling;
     if (forcedPolling == 1)
         QMetaObject::invokeMethod(this, "startPolling");
 }
engines()
QList< QBearerEngine * > QNetworkConfigurationManagerPrivate::engines () const
Definition at line 455 of file qnetworkconfigmanager_p.cpp.
Referenced by getEngineFromId(), and QNetworkSession::QNetworkSession().
 {
     QMutexLocker locker(&mutex);
     return sessionEngines;
 }
initialize()
void QNetworkConfigurationManagerPrivate::initialize ()
Definition at line 69 of file qnetworkconfigmanager_p.cpp.
Referenced by connManager().
 {
     //Two stage construction, because we only want to do this heavyweight work for the winner of the Q_GLOBAL_STATIC race.
     bearerThread = new QThread();
     bearerThread->moveToThread(QCoreApplicationPrivate::mainThread()); // because cleanup() is called in main thread context.
     moveToThread(bearerThread);
     bearerThread->start();
     updateConfigurations();
 }
isOnline()
bool QNetworkConfigurationManagerPrivate::isOnline () const
Definition at line 281 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::isOnline().
 {
     QMutexLocker locker(&mutex);
     return !onlineConfigurations.isEmpty();
 }
onlineStateChanged
void QNetworkConfigurationManagerPrivate::onlineStateChanged (bool isOnline) signal
Referenced by configurationAdded(), configurationChanged(), and configurationRemoved().
performAsyncConfigurationUpdate()
void QNetworkConfigurationManagerPrivate::performAsyncConfigurationUpdate ()
Definition at line 438 of file qnetworkconfigmanager_p.cpp.
Referenced by QNetworkConfigurationManager::updateConfigurations().
 {
     QMutexLocker locker(&mutex);
     if (sessionEngines.isEmpty()) {
         emit configurationUpdateComplete();
         return;
     }
     updating = true;
     foreach (QBearerEngine *engine, sessionEngines) {
         updatingEngines.insert(engine);
         QMetaObject::invokeMethod(engine, "requestUpdate");
     }
 }
pollEngines
void QNetworkConfigurationManagerPrivate::pollEngines () private slot
Definition at line 484 of file qnetworkconfigmanager_p.cpp.
Referenced by startPolling().
 {
     QMutexLocker locker(&mutex);
     foreach (QBearerEngine *engine, sessionEngines) {
         if (engine->requiresPolling() && (forcedPolling || engine->configurationsInUse())) {
             pollingEngines.insert(engine);
             QMetaObject::invokeMethod(engine, "requestUpdate");
         }
     }
 }
startPolling()
void QNetworkConfigurationManagerPrivate::startPolling () private
Definition at line 462 of file qnetworkconfigmanager_p.cpp.
Referenced by updateConfigurations().
 {
     QMutexLocker locker(&mutex);
     if(!pollTimer) {
         pollTimer = new QTimer(this);
         pollTimer->setInterval(10000);
         pollTimer->setSingleShot(true);
         connect(pollTimer, SIGNAL(timeout()), this, SLOT(pollEngines()));
     }
     if(pollTimer->isActive())
         return;
     foreach (QBearerEngine *engine, sessionEngines) {
         if (engine->requiresPolling() && (forcedPolling || engine->configurationsInUse())) {
             pollTimer->start();
             break;
         }
     }
 }
updateConfigurations
void QNetworkConfigurationManagerPrivate::updateConfigurations () slot
Definition at line 365 of file qnetworkconfigmanager_p.cpp.
Referenced by initialize().
 {
     QMutexLocker locker(&mutex);
     if (firstUpdate) {
         if (qobject_cast<QBearerEngine *>(sender()))
             return;
         updating = false;
 #ifndef QT_NO_LIBRARY
         QBearerEngine *generic = 0;
         QFactoryLoader *l = loader();
         foreach (const QString &key, l->keys()) {
             QBearerEnginePlugin *plugin = qobject_cast<QBearerEnginePlugin *>(l->instance(key));
             if (plugin) {
                 QBearerEngine *engine = plugin->create(key);
                 if (!engine)
                     continue;
                 if (key == QLatin1String("generic"))
                     generic = engine;
                 else
                     sessionEngines.append(engine);
                 engine->moveToThread(bearerThread);
                 connect(engine, SIGNAL(updateCompleted()),
                         this, SLOT(updateConfigurations()),
                         Qt::QueuedConnection);
                 connect(engine, SIGNAL(configurationAdded(QNetworkConfigurationPrivatePointer)),
                         this, SLOT(configurationAdded(QNetworkConfigurationPrivatePointer)),
                         Qt::QueuedConnection);
                 connect(engine, SIGNAL(configurationRemoved(QNetworkConfigurationPrivatePointer)),
                         this, SLOT(configurationRemoved(QNetworkConfigurationPrivatePointer)),
                         Qt::QueuedConnection);
                 connect(engine, SIGNAL(configurationChanged(QNetworkConfigurationPrivatePointer)),
                         this, SLOT(configurationChanged(QNetworkConfigurationPrivatePointer)),
                         Qt::QueuedConnection);
             }
         }
         if (generic)
             sessionEngines.append(generic);
 #endif // QT_NO_LIBRARY
     }
     QBearerEngine *engine = qobject_cast<QBearerEngine *>(sender());
     if (engine && !updatingEngines.isEmpty())
         updatingEngines.remove(engine);
     if (updating && updatingEngines.isEmpty()) {
         updating = false;
         emit configurationUpdateComplete();
     }
     if (engine && !pollingEngines.isEmpty()) {
         pollingEngines.remove(engine);
         if (pollingEngines.isEmpty())
             startPolling();
     }
     if (firstUpdate) {
         firstUpdate = false;
         QList<QBearerEngine*> enginesToInitialize = sessionEngines; //shallow copy the list in case it is modified when we unlock mutex
         locker.unlock();
         foreach (QBearerEngine* engine, enginesToInitialize) {
             QMetaObject::invokeMethod(engine, "initialize", Qt::BlockingQueuedConnection);
         }
     }
 }
Properties
bearerThread
QThread* QNetworkConfigurationManagerPrivate::bearerThread private
Definition at line 117 of file qnetworkconfigmanager_p.h.
Referenced by cleanup(), initialize(), updateConfigurations(), and ~QNetworkConfigurationManagerPrivate().
firstUpdate
bool QNetworkConfigurationManagerPrivate::firstUpdate private
Definition at line 131 of file qnetworkconfigmanager_p.h.
Referenced by configurationAdded(), configurationChanged(), configurationRemoved(), and updateConfigurations().
forcedPolling
int QNetworkConfigurationManagerPrivate::forcedPolling private
Definition at line 128 of file qnetworkconfigmanager_p.h.
Referenced by disablePolling(), enablePolling(), pollEngines(), and startPolling().
mutex
QMutex QNetworkConfigurationManagerPrivate::mutex mutable private
Definition at line 120 of file qnetworkconfigmanager_p.h.
Referenced by allConfigurations(), capabilities(), configurationAdded(), configurationChanged(), configurationFromIdentifier(), configurationRemoved(), defaultConfiguration(), disablePolling(), enablePolling(), engines(), isOnline(), performAsyncConfigurationUpdate(), pollEngines(), startPolling(), updateConfigurations(), and ~QNetworkConfigurationManagerPrivate().
onlineConfigurations
QSet<QString> QNetworkConfigurationManagerPrivate::onlineConfigurations private
Definition at line 124 of file qnetworkconfigmanager_p.h.
Referenced by configurationAdded(), configurationChanged(), configurationRemoved(), and isOnline().
pollingEngines
QSet<QBearerEngine *> QNetworkConfigurationManagerPrivate::pollingEngines private
Definition at line 126 of file qnetworkconfigmanager_p.h.
Referenced by pollEngines(), and updateConfigurations().
pollTimer
QTimer* QNetworkConfigurationManagerPrivate::pollTimer private
Definition at line 116 of file qnetworkconfigmanager_p.h.
Referenced by startPolling().
sessionEngines
QList<QBearerEngine *> QNetworkConfigurationManagerPrivate::sessionEngines private
Definition at line 122 of file qnetworkconfigmanager_p.h.
Referenced by allConfigurations(), capabilities(), configurationFromIdentifier(), defaultConfiguration(), engines(), performAsyncConfigurationUpdate(), pollEngines(), startPolling(), updateConfigurations(), and ~QNetworkConfigurationManagerPrivate().
updating
bool QNetworkConfigurationManagerPrivate::updating private
Definition at line 129 of file qnetworkconfigmanager_p.h.
Referenced by performAsyncConfigurationUpdate(), and updateConfigurations().
updatingEngines
QSet<QBearerEngine *> QNetworkConfigurationManagerPrivate::updatingEngines private
Definition at line 127 of file qnetworkconfigmanager_p.h.
Referenced by performAsyncConfigurationUpdate(), and updateConfigurations().
The documentation for this class was generated from the following files:
/src/network/bearer/qnetworkconfigmanager_p.h
/src/network/bearer/qnetworkconfigmanager.cpp
/src/network/bearer/qnetworkconfigmanager_p.cpp