Qt 4.8: QPatternist::UserFunction Class Reference
QPatternist::UserFunction Class Reference
A function created with XQuery's declare function declaration.
#include <quserfunction_p.h>
Public Types
typedef QList< UserFunction::Ptr > List
typedef QExplicitlySharedDataPointer< UserFunction > Ptr
Public Functions
VariableDeclaration::List argumentDeclarations () const
const Expression::Ptr & body () const
VariableSlotID expressionSlotOffset () const
void setBody (const Expression::Ptr &newBody)
FunctionSignature::Ptr signature () const
UserFunction (const FunctionSignature::Ptr &signature, const Expression::Ptr &body, const VariableSlotID slotOffset, const VariableDeclaration::List &varDecls)
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Properties
const VariableDeclaration::List m_argumentDeclarations
Expression::Ptr m_body
const FunctionSignature::Ptr m_signature
const VariableSlotID m_slotOffset
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
A function created with XQuery's declare function declaration.
See also
UserFunctionCall
ArgumentReference
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 77 of file quserfunction_p.h.
Typedefs
List
typedef QList<UserFunction::Ptr> QPatternist::UserFunction::List
Definition at line 81 of file quserfunction_p.h.
Ptr
typedef QExplicitlySharedDataPointer<UserFunction> QPatternist::UserFunction::Ptr
Definition at line 80 of file quserfunction_p.h.
Constructors and Destructors
UserFunction()
UserFunction::UserFunction (const FunctionSignature::Ptr & signature, const Expression::Ptr & body, const VariableSlotID slotOffset, const VariableDeclaration::List & varDecls)
If slotOffset is -1, it means this function has no arguments.
Definition at line 49 of file quserfunction.cpp.
                                                                     : m_signature(sign),
                                                                         m_body(b),
                                                                         m_slotOffset(slotOffset),
                                                                         m_argumentDeclarations(varDecls)
 {
     Q_ASSERT(m_signature);
     Q_ASSERT(m_body);
     Q_ASSERT(m_slotOffset > -2);
 }
Functions
argumentDeclarations()
VariableDeclaration::List QPatternist::UserFunction::argumentDeclarations () const inline
Definition at line 119 of file quserfunction_p.h.
Referenced by QPatternist::UserFunctionCallsite::setSource().
     {
         return m_argumentDeclarations;
     }
body()
const Expression::Ptr & QPatternist::UserFunction::body () const inline
Definition at line 104 of file quserfunction_p.h.
Referenced by QPatternist::UserFunctionCallsite::setSource(), and QPatternist::UserFunctionCallsite::typeCheck().
     {
         return m_body;
     }
expressionSlotOffset()
VariableSlotID QPatternist::UserFunction::expressionSlotOffset () const inline
Definition at line 114 of file quserfunction_p.h.
Referenced by QPatternist::UserFunctionCallsite::setSource().
     {
         return m_slotOffset;
     }
setBody()
void QPatternist::UserFunction::setBody (const Expression::Ptr & newBody) inline
Definition at line 124 of file quserfunction_p.h.
     {
         m_body = newBody;
     }
signature()
FunctionSignature::Ptr QPatternist::UserFunction::signature () const inline
Definition at line 109 of file quserfunction_p.h.
Referenced by QPatternist::UserFunctionCallsite::callTargetDescription(), and QPatternist::UserFunctionCallsite::expectedOperandTypes().
     {
         return m_signature;
     }
Properties
m_argumentDeclarations
const VariableDeclaration::List QPatternist::UserFunction::m_argumentDeclarations private
Definition at line 101 of file quserfunction_p.h.
Referenced by argumentDeclarations().
m_body
Expression::Ptr QPatternist::UserFunction::m_body private
Definition at line 99 of file quserfunction_p.h.
Referenced by body(), setBody(), and UserFunction().
m_signature
const FunctionSignature::Ptr QPatternist::UserFunction::m_signature private
Definition at line 98 of file quserfunction_p.h.
Referenced by signature(), and UserFunction().
m_slotOffset
const VariableSlotID QPatternist::UserFunction::m_slotOffset private
Definition at line 100 of file quserfunction_p.h.
Referenced by expressionSlotOffset(), and UserFunction().
The documentation for this class was generated from the following files:
/src/xmlpatterns/expr/quserfunction_p.h
/src/xmlpatterns/expr/quserfunction.cpp