Qt 4.8: QGLEngineSharedShaders Class Reference
QGLEngineSharedShaders Class Reference
#include <qglengineshadermanager_p.h>
Public Types
enum SnippetName {
MainVertexShader, MainWithTexCoordsVertexShader, MainWithTexCoordsAndOpacityVertexShader, UntransformedPositionVertexShader,
PositionOnlyVertexShader, ComplexGeometryPositionOnlyVertexShader, PositionWithPatternBrushVertexShader, PositionWithLinearGradientBrushVertexShader,
PositionWithConicalGradientBrushVertexShader, PositionWithRadialGradientBrushVertexShader, PositionWithTextureBrushVertexShader, AffinePositionWithPatternBrushVertexShader,
AffinePositionWithLinearGradientBrushVertexShader, AffinePositionWithConicalGradientBrushVertexShader, AffinePositionWithRadialGradientBrushVertexShader, AffinePositionWithTextureBrushVertexShader,
MainFragmentShader_CMO, MainFragmentShader_CM, MainFragmentShader_MO, MainFragmentShader_M,
MainFragmentShader_CO, MainFragmentShader_C, MainFragmentShader_O, MainFragmentShader,
MainFragmentShader_ImageArrays, ImageSrcFragmentShader, ImageSrcWithPatternFragmentShader, NonPremultipliedImageSrcFragmentShader,
CustomImageSrcFragmentShader, SolidBrushSrcFragmentShader, TextureBrushSrcFragmentShader, TextureBrushSrcWithPatternFragmentShader,
PatternBrushSrcFragmentShader, LinearGradientBrushSrcFragmentShader, RadialGradientBrushSrcFragmentShader, ConicalGradientBrushSrcFragmentShader,
ShockingPinkSrcFragmentShader, NoMaskFragmentShader, MaskFragmentShader, RgbMaskFragmentShaderPass1,
RgbMaskFragmentShaderPass2, RgbMaskWithGammaFragmentShader, NoCompositionModeFragmentShader, MultiplyCompositionModeFragmentShader,
ScreenCompositionModeFragmentShader, OverlayCompositionModeFragmentShader, DarkenCompositionModeFragmentShader, LightenCompositionModeFragmentShader,
ColorDodgeCompositionModeFragmentShader, ColorBurnCompositionModeFragmentShader, HardLightCompositionModeFragmentShader, SoftLightCompositionModeFragmentShader,
DifferenceCompositionModeFragmentShader, ExclusionCompositionModeFragmentShader, TotalSnippetCount, InvalidSnippetName
}
Public Functions
QGLShaderProgram * blitProgram ()
void cleanupCustomStage (QGLCustomShaderStage *stage)
QGLEngineShaderProg * findProgramInCache (const QGLEngineShaderProg &prog)
QGLEngineSharedShaders (const QGLContext *context)
QGLShaderProgram * simpleProgram ()
~QGLEngineSharedShaders ()
Static Public Functions
static QGLEngineSharedShaders * shadersForContext (const QGLContext *context)
Properties
QGLShaderProgram * blitShaderProg
QList< QGLEngineShaderProg * > cachedPrograms
QGLSharedResourceGuard ctxGuard
QList< QGLShader * > shaders
QGLShaderProgram * simpleShaderProg
Static Private Attributes
static const char * qShaderSnippets [TotalSnippetCount]
Detailed Description
Definition at line 262 of file qglengineshadermanager_p.h.
Enumerations
SnippetName
enum QGLEngineSharedShaders::SnippetName
Enumerator
MainVertexShader
MainWithTexCoordsVertexShader
MainWithTexCoordsAndOpacityVertexShader
UntransformedPositionVertexShader
PositionOnlyVertexShader
ComplexGeometryPositionOnlyVertexShader
PositionWithPatternBrushVertexShader
PositionWithLinearGradientBrushVertexShader
PositionWithConicalGradientBrushVertexShader
PositionWithRadialGradientBrushVertexShader
PositionWithTextureBrushVertexShader
AffinePositionWithPatternBrushVertexShader
AffinePositionWithLinearGradientBrushVertexShader
AffinePositionWithConicalGradientBrushVertexShader
AffinePositionWithRadialGradientBrushVertexShader
AffinePositionWithTextureBrushVertexShader
MainFragmentShader_CMO
MainFragmentShader_CM
MainFragmentShader_MO
MainFragmentShader_M
MainFragmentShader_CO
MainFragmentShader_C
MainFragmentShader_O
MainFragmentShader
MainFragmentShader_ImageArrays
ImageSrcFragmentShader
ImageSrcWithPatternFragmentShader
NonPremultipliedImageSrcFragmentShader
CustomImageSrcFragmentShader
SolidBrushSrcFragmentShader
TextureBrushSrcFragmentShader
TextureBrushSrcWithPatternFragmentShader
PatternBrushSrcFragmentShader
LinearGradientBrushSrcFragmentShader
RadialGradientBrushSrcFragmentShader
ConicalGradientBrushSrcFragmentShader
ShockingPinkSrcFragmentShader
NoMaskFragmentShader
MaskFragmentShader
RgbMaskFragmentShaderPass1
RgbMaskFragmentShaderPass2
RgbMaskWithGammaFragmentShader
NoCompositionModeFragmentShader
MultiplyCompositionModeFragmentShader
ScreenCompositionModeFragmentShader
OverlayCompositionModeFragmentShader
DarkenCompositionModeFragmentShader
LightenCompositionModeFragmentShader
ColorDodgeCompositionModeFragmentShader
ColorBurnCompositionModeFragmentShader
HardLightCompositionModeFragmentShader
SoftLightCompositionModeFragmentShader
DifferenceCompositionModeFragmentShader
ExclusionCompositionModeFragmentShader
TotalSnippetCount
InvalidSnippetName
Definition at line 267 of file qglengineshadermanager_p.h.
                      {
         MainVertexShader,
         MainWithTexCoordsVertexShader,
         MainWithTexCoordsAndOpacityVertexShader,
         // UntransformedPositionVertexShader must be first in the list:
         UntransformedPositionVertexShader,
         PositionOnlyVertexShader,
         ComplexGeometryPositionOnlyVertexShader,
         PositionWithPatternBrushVertexShader,
         PositionWithLinearGradientBrushVertexShader,
         PositionWithConicalGradientBrushVertexShader,
         PositionWithRadialGradientBrushVertexShader,
         PositionWithTextureBrushVertexShader,
         AffinePositionWithPatternBrushVertexShader,
         AffinePositionWithLinearGradientBrushVertexShader,
         AffinePositionWithConicalGradientBrushVertexShader,
         AffinePositionWithRadialGradientBrushVertexShader,
         AffinePositionWithTextureBrushVertexShader,
         // MainFragmentShader_CMO must be first in the list:
         MainFragmentShader_CMO,
         MainFragmentShader_CM,
         MainFragmentShader_MO,
         MainFragmentShader_M,
         MainFragmentShader_CO,
         MainFragmentShader_C,
         MainFragmentShader_O,
         MainFragmentShader,
         MainFragmentShader_ImageArrays,
         // ImageSrcFragmentShader must be first in the list::
         ImageSrcFragmentShader,
         ImageSrcWithPatternFragmentShader,
         NonPremultipliedImageSrcFragmentShader,
         CustomImageSrcFragmentShader,
         SolidBrushSrcFragmentShader,
         TextureBrushSrcFragmentShader,
         TextureBrushSrcWithPatternFragmentShader,
         PatternBrushSrcFragmentShader,
         LinearGradientBrushSrcFragmentShader,
         RadialGradientBrushSrcFragmentShader,
         ConicalGradientBrushSrcFragmentShader,
         ShockingPinkSrcFragmentShader,
         // NoMaskFragmentShader must be first in the list:
         NoMaskFragmentShader,
         MaskFragmentShader,
         RgbMaskFragmentShaderPass1,
         RgbMaskFragmentShaderPass2,
         RgbMaskWithGammaFragmentShader,
         // NoCompositionModeFragmentShader must be first in the list:
         NoCompositionModeFragmentShader,
         MultiplyCompositionModeFragmentShader,
         ScreenCompositionModeFragmentShader,
         OverlayCompositionModeFragmentShader,
         DarkenCompositionModeFragmentShader,
         LightenCompositionModeFragmentShader,
         ColorDodgeCompositionModeFragmentShader,
         ColorBurnCompositionModeFragmentShader,
         HardLightCompositionModeFragmentShader,
         SoftLightCompositionModeFragmentShader,
         DifferenceCompositionModeFragmentShader,
         ExclusionCompositionModeFragmentShader,
         TotalSnippetCount, InvalidSnippetName
     };
Constructors and Destructors
QGLEngineSharedShaders()
QGLEngineSharedShaders::QGLEngineSharedShaders (const QGLContext * context)
Definition at line 83 of file qglengineshadermanager.cpp.
     : ctxGuard(context)
     , blitShaderProg(0)
     , simpleShaderProg(0)
 {
 /*
     Rather than having the shader source array statically initialised, it is initialised
     here instead. This is to allow new shader names to be inserted or existing names moved
     around without having to change the order of the glsl strings. It is hoped this will
     make future hard-to-find runtime bugs more obvious and generally give more solid code.
 */
     static bool snippetsPopulated = false;
     if (!snippetsPopulated) {
         const char** code = qShaderSnippets; // shortcut
         code[MainVertexShader] = qglslMainVertexShader;
         code[MainWithTexCoordsVertexShader] = qglslMainWithTexCoordsVertexShader;
         code[MainWithTexCoordsAndOpacityVertexShader] = qglslMainWithTexCoordsAndOpacityVertexShader;
         code[UntransformedPositionVertexShader] = qglslUntransformedPositionVertexShader;
         code[PositionOnlyVertexShader] = qglslPositionOnlyVertexShader;
         code[ComplexGeometryPositionOnlyVertexShader] = qglslComplexGeometryPositionOnlyVertexShader;
         code[PositionWithPatternBrushVertexShader] = qglslPositionWithPatternBrushVertexShader;
         code[PositionWithLinearGradientBrushVertexShader] = qglslPositionWithLinearGradientBrushVertexShader;
         code[PositionWithConicalGradientBrushVertexShader] = qglslPositionWithConicalGradientBrushVertexShader;
         code[PositionWithRadialGradientBrushVertexShader] = qglslPositionWithRadialGradientBrushVertexShader;
         code[PositionWithTextureBrushVertexShader] = qglslPositionWithTextureBrushVertexShader;
         code[AffinePositionWithPatternBrushVertexShader] = qglslAffinePositionWithPatternBrushVertexShader;
         code[AffinePositionWithLinearGradientBrushVertexShader] = qglslAffinePositionWithLinearGradientBrushVertexShader;
         code[AffinePositionWithConicalGradientBrushVertexShader] = qglslAffinePositionWithConicalGradientBrushVertexShader;
         code[AffinePositionWithRadialGradientBrushVertexShader] = qglslAffinePositionWithRadialGradientBrushVertexShader;
         code[AffinePositionWithTextureBrushVertexShader] = qglslAffinePositionWithTextureBrushVertexShader;
         code[MainFragmentShader_CMO] = qglslMainFragmentShader_CMO;
         code[MainFragmentShader_CM] = qglslMainFragmentShader_CM;
         code[MainFragmentShader_MO] = qglslMainFragmentShader_MO;
         code[MainFragmentShader_M] = qglslMainFragmentShader_M;
         code[MainFragmentShader_CO] = qglslMainFragmentShader_CO;
         code[MainFragmentShader_C] = qglslMainFragmentShader_C;
         code[MainFragmentShader_O] = qglslMainFragmentShader_O;
         code[MainFragmentShader] = qglslMainFragmentShader;
         code[MainFragmentShader_ImageArrays] = qglslMainFragmentShader_ImageArrays;
         code[ImageSrcFragmentShader] = qglslImageSrcFragmentShader;
         code[ImageSrcWithPatternFragmentShader] = qglslImageSrcWithPatternFragmentShader;
         code[NonPremultipliedImageSrcFragmentShader] = qglslNonPremultipliedImageSrcFragmentShader;
         code[CustomImageSrcFragmentShader] = qglslCustomSrcFragmentShader; // Calls "customShader", which must be appended
         code[SolidBrushSrcFragmentShader] = qglslSolidBrushSrcFragmentShader;
         code[TextureBrushSrcFragmentShader] = qglslTextureBrushSrcFragmentShader;
         code[TextureBrushSrcWithPatternFragmentShader] = qglslTextureBrushSrcWithPatternFragmentShader;
         code[PatternBrushSrcFragmentShader] = qglslPatternBrushSrcFragmentShader;
         code[LinearGradientBrushSrcFragmentShader] = qglslLinearGradientBrushSrcFragmentShader;
         code[RadialGradientBrushSrcFragmentShader] = qglslRadialGradientBrushSrcFragmentShader;
         code[ConicalGradientBrushSrcFragmentShader] = qglslConicalGradientBrushSrcFragmentShader;
         code[ShockingPinkSrcFragmentShader] = qglslShockingPinkSrcFragmentShader;
         code[NoMaskFragmentShader] = "";
         code[MaskFragmentShader] = qglslMaskFragmentShader;
         code[RgbMaskFragmentShaderPass1] = qglslRgbMaskFragmentShaderPass1;
         code[RgbMaskFragmentShaderPass2] = qglslRgbMaskFragmentShaderPass2;
         code[RgbMaskWithGammaFragmentShader] = ""; //###
         code[NoCompositionModeFragmentShader] = "";
         code[MultiplyCompositionModeFragmentShader] = ""; //###
         code[ScreenCompositionModeFragmentShader] = ""; //###
         code[OverlayCompositionModeFragmentShader] = ""; //###
         code[DarkenCompositionModeFragmentShader] = ""; //###
         code[LightenCompositionModeFragmentShader] = ""; //###
         code[ColorDodgeCompositionModeFragmentShader] = ""; //###
         code[ColorBurnCompositionModeFragmentShader] = ""; //###
         code[HardLightCompositionModeFragmentShader] = ""; //###
         code[SoftLightCompositionModeFragmentShader] = ""; //###
         code[DifferenceCompositionModeFragmentShader] = ""; //###
         code[ExclusionCompositionModeFragmentShader] = ""; //###
 #if defined(QT_DEBUG)
         // Check that all the elements have been filled:
         for (int i = 0; i < TotalSnippetCount; ++i) {
             if (qShaderSnippets[i] == 0) {
                 qFatal("Shader snippet for %s (#%d) is missing!",
                        snippetNameStr(SnippetName(i)).constData(), i);
             }
         }
 #endif
         snippetsPopulated = true;
     }
     QGLShader* fragShader;
     QGLShader* vertexShader;
     QByteArray vertexSource;
     QByteArray fragSource;
     // Compile up the simple shader:
     vertexSource.append(qShaderSnippets[MainVertexShader]);
     vertexSource.append(qShaderSnippets[PositionOnlyVertexShader]);
     fragSource.append(qShaderSnippets[MainFragmentShader]);
     fragSource.append(qShaderSnippets[ShockingPinkSrcFragmentShader]);
     simpleShaderProg = new QGLShaderProgram(context, 0);
     CachedShader simpleShaderCache(fragSource, vertexSource);
     bool inCache = simpleShaderCache.load(simpleShaderProg, context);
     if (!inCache) {
         vertexShader = new QGLShader(QGLShader::Vertex, context, 0);
         shaders.append(vertexShader);
         if (!vertexShader->compileSourceCode(vertexSource))
             qWarning("Vertex shader for simpleShaderProg (MainVertexShader & PositionOnlyVertexShader) failed to compile");
         fragShader = new QGLShader(QGLShader::Fragment, context, 0);
         shaders.append(fragShader);
         if (!fragShader->compileSourceCode(fragSource))
             qWarning("Fragment shader for simpleShaderProg (MainFragmentShader & ShockingPinkSrcFragmentShader) failed to compile");
         simpleShaderProg->addShader(vertexShader);
         simpleShaderProg->addShader(fragShader);
         simpleShaderProg->bindAttributeLocation("vertexCoordsArray", QT_VERTEX_COORDS_ATTR);
         simpleShaderProg->bindAttributeLocation("pmvMatrix1", QT_PMV_MATRIX_1_ATTR);
         simpleShaderProg->bindAttributeLocation("pmvMatrix2", QT_PMV_MATRIX_2_ATTR);
         simpleShaderProg->bindAttributeLocation("pmvMatrix3", QT_PMV_MATRIX_3_ATTR);
     }
     simpleShaderProg->link();
     if (simpleShaderProg->isLinked()) {
         if (!inCache)
             simpleShaderCache.store(simpleShaderProg, context);
     } else {
         qCritical() << "Errors linking simple shader:"
                     << simpleShaderProg->log();
     }
     // Compile the blit shader:
     vertexSource.clear();
     vertexSource.append(qShaderSnippets[MainWithTexCoordsVertexShader]);
     vertexSource.append(qShaderSnippets[UntransformedPositionVertexShader]);
     fragSource.clear();
     fragSource.append(qShaderSnippets[MainFragmentShader]);
     fragSource.append(qShaderSnippets[ImageSrcFragmentShader]);
     blitShaderProg = new QGLShaderProgram(context, 0);
     CachedShader blitShaderCache(fragSource, vertexSource);
     inCache = blitShaderCache.load(blitShaderProg, context);
     if (!inCache) {
         vertexShader = new QGLShader(QGLShader::Vertex, context, 0);
         shaders.append(vertexShader);
         if (!vertexShader->compileSourceCode(vertexSource))
             qWarning("Vertex shader for blitShaderProg (MainWithTexCoordsVertexShader & UntransformedPositionVertexShader) failed to compile");
         fragShader = new QGLShader(QGLShader::Fragment, context, 0);
         shaders.append(fragShader);
         if (!fragShader->compileSourceCode(fragSource))
             qWarning("Fragment shader for blitShaderProg (MainFragmentShader & ImageSrcFragmentShader) failed to compile");
         blitShaderProg->addShader(vertexShader);
         blitShaderProg->addShader(fragShader);
         blitShaderProg->bindAttributeLocation("textureCoordArray", QT_TEXTURE_COORDS_ATTR);
         blitShaderProg->bindAttributeLocation("vertexCoordsArray", QT_VERTEX_COORDS_ATTR);
     }
     blitShaderProg->link();
     if (blitShaderProg->isLinked()) {
         if (!inCache)
             blitShaderCache.store(blitShaderProg, context);
     } else {
         qCritical() << "Errors linking blit shader:"
                     << blitShaderProg->log();
     }
 #ifdef QT_GL_SHARED_SHADER_DEBUG
     qDebug(" -> QGLEngineSharedShaders() %p for thread %p.", this, QThread::currentThread());
 #endif
 }
~QGLEngineSharedShaders()
QGLEngineSharedShaders::~QGLEngineSharedShaders ()
Definition at line 267 of file qglengineshadermanager.cpp.
 {
 #ifdef QT_GL_SHARED_SHADER_DEBUG
     qDebug(" -> ~QGLEngineSharedShaders() %p for thread %p.", this, QThread::currentThread());
 #endif
     qDeleteAll(shaders);
     shaders.clear();
     qDeleteAll(cachedPrograms);
     cachedPrograms.clear();
     if (blitShaderProg) {
         delete blitShaderProg;
         blitShaderProg = 0;
     }
     if (simpleShaderProg) {
         delete simpleShaderProg;
         simpleShaderProg = 0;
     }
 }
Functions
blitProgram()
QGLShaderProgram* QGLEngineSharedShaders::blitProgram () inline
Definition at line 354 of file qglengineshadermanager_p.h.
Referenced by QGLEngineShaderManager::blitProgram(), blitTexture(), and QGLEngineShaderManager::useBlitProgram().
 { return blitShaderProg; }
cleanupCustomStage()
void QGLEngineSharedShaders::cleanupCustomStage (QGLCustomShaderStage * stage)
Definition at line 442 of file qglengineshadermanager.cpp.
 {
     // Remove any shader programs which has this as the custom shader src:
     for (int i = 0; i < cachedPrograms.size(); ++i) {
         QGLEngineShaderProg *cachedProg = cachedPrograms[i];
         if (cachedProg->customStageSource == stage->source()) {
             delete cachedProg;
             cachedPrograms.removeAt(i);
             i--;
         }
     }
 }
findProgramInCache()
QGLEngineShaderProg * QGLEngineSharedShaders::findProgramInCache (const QGLEngineShaderProg & prog)
Definition at line 299 of file qglengineshadermanager.cpp.
Referenced by QGLEngineShaderManager::useCorrectShaderProg().
 {
     for (int i = 0; i < cachedPrograms.size(); ++i) {
         QGLEngineShaderProg *cachedProg = cachedPrograms[i];
         if (*cachedProg == prog) {
             // Move the program to the top of the list as a poor-man's cache algo
             cachedPrograms.move(i, 0);
             cachedProg->program->bind();
             return cachedProg;
         }
     }
     QScopedPointer<QGLEngineShaderProg> newProg;
     do {
         QByteArray fragSource;
         // Insert the custom stage before the srcPixel shader to work around an ATI driver bug
         // where you cannot forward declare a function that takes a sampler as argument.
         if (prog.srcPixelFragShader == CustomImageSrcFragmentShader)
             fragSource.append(prog.customStageSource);
         fragSource.append(qShaderSnippets[prog.mainFragShader]);
         fragSource.append(qShaderSnippets[prog.srcPixelFragShader]);
         if (prog.compositionFragShader)
             fragSource.append(qShaderSnippets[prog.compositionFragShader]);
         if (prog.maskFragShader)
             fragSource.append(qShaderSnippets[prog.maskFragShader]);
         QByteArray vertexSource;
         vertexSource.append(qShaderSnippets[prog.mainVertexShader]);
         vertexSource.append(qShaderSnippets[prog.positionVertexShader]);
         QScopedPointer<QGLShaderProgram> shaderProgram(new QGLShaderProgram(ctxGuard.context(), 0));
         CachedShader shaderCache(fragSource, vertexSource);
         bool inCache = shaderCache.load(shaderProgram.data(), ctxGuard.context());
         if (!inCache) {
             QScopedPointer<QGLShader> fragShader(new QGLShader(QGLShader::Fragment, ctxGuard.context(), 0));
             QByteArray description;
 #if defined(QT_DEBUG)
             // Name the shader for easier debugging
             description.append("Fragment shader: main=");
             description.append(snippetNameStr(prog.mainFragShader));
             description.append(", srcPixel=");
             description.append(snippetNameStr(prog.srcPixelFragShader));
             if (prog.compositionFragShader) {
                 description.append(", composition=");
                 description.append(snippetNameStr(prog.compositionFragShader));
             }
             if (prog.maskFragShader) {
                 description.append(", mask=");
                 description.append(snippetNameStr(prog.maskFragShader));
             }
             fragShader->setObjectName(QString::fromLatin1(description));
 #endif
             if (!fragShader->compileSourceCode(fragSource)) {
                 qWarning() << "Warning:" << description << "failed to compile!";
                 break;
             }
             QScopedPointer<QGLShader> vertexShader(new QGLShader(QGLShader::Vertex, ctxGuard.context(), 0));
 #if defined(QT_DEBUG)
             // Name the shader for easier debugging
             description.clear();
             description.append("Vertex shader: main=");
             description.append(snippetNameStr(prog.mainVertexShader));
             description.append(", position=");
             description.append(snippetNameStr(prog.positionVertexShader));
             vertexShader->setObjectName(QString::fromLatin1(description));
 #endif
             if (!vertexShader->compileSourceCode(vertexSource)) {
                 qWarning() << "Warning:" << description << "failed to compile!";
                 break;
             }
             shaders.append(vertexShader.data());
             shaders.append(fragShader.data());
             shaderProgram->addShader(vertexShader.take());
             shaderProgram->addShader(fragShader.take());
             // We have to bind the vertex attribute names before the program is linked:
             shaderProgram->bindAttributeLocation("vertexCoordsArray", QT_VERTEX_COORDS_ATTR);
             if (prog.useTextureCoords)
                 shaderProgram->bindAttributeLocation("textureCoordArray", QT_TEXTURE_COORDS_ATTR);
             if (prog.useOpacityAttribute)
                 shaderProgram->bindAttributeLocation("opacityArray", QT_OPACITY_ATTR);
             if (prog.usePmvMatrixAttribute) {
                 shaderProgram->bindAttributeLocation("pmvMatrix1", QT_PMV_MATRIX_1_ATTR);
                 shaderProgram->bindAttributeLocation("pmvMatrix2", QT_PMV_MATRIX_2_ATTR);
                 shaderProgram->bindAttributeLocation("pmvMatrix3", QT_PMV_MATRIX_3_ATTR);
             }
         }
         newProg.reset(new QGLEngineShaderProg(prog));
         newProg->program = shaderProgram.take();
         newProg->program->link();
         if (newProg->program->isLinked()) {
             if (!inCache)
                 shaderCache.store(newProg->program, ctxGuard.context());
         } else {
             QLatin1String none("none");
             QLatin1String br("\n");
             QString error;
             error = QLatin1String("Shader program failed to link,");
 #if defined(QT_DEBUG)
             error += QLatin1String("\n  Shaders Used:\n");
             for (int i = 0; i < newProg->program->shaders().count(); ++i) {
                 QGLShader *shader = newProg->program->shaders().at(i);
                 error += QLatin1String("    ") + shader->objectName() + QLatin1String(": \n")
                          + QLatin1String(shader->sourceCode()) + br;
             }
 #endif
             error += QLatin1String("  Error Log:\n")
                      + QLatin1String("    ") + newProg->program->log();
             qWarning() << error;
             break;
         }
         newProg->program->bind();
         if (newProg->maskFragShader != QGLEngineSharedShaders::NoMaskFragmentShader) {
             GLuint location = newProg->program->uniformLocation("maskTexture");
             newProg->program->setUniformValue(location, QT_MASK_TEXTURE_UNIT);
         }
         if (cachedPrograms.count() > 30) {
             // The cache is full, so delete the last 5 programs in the list.
             // These programs will be least used, as a program us bumped to
             // the top of the list when it's used.
             for (int i = 0; i < 5; ++i) {
                 delete cachedPrograms.last();
                 cachedPrograms.removeLast();
             }
         }
         cachedPrograms.insert(0, newProg.data());
     } while (false);
     return newProg.take();
 }
shadersForContext()
QGLEngineSharedShaders * QGLEngineSharedShaders::shadersForContext (const QGLContext * context) static
Definition at line 71 of file qglengineshadermanager.cpp.
Referenced by blitTexture(), and QGLEngineShaderManager::QGLEngineShaderManager().
 {
     return qt_shader_storage()->shadersForThread(context);
 }
simpleProgram()
QGLShaderProgram* QGLEngineSharedShaders::simpleProgram () inline
Definition at line 353 of file qglengineshadermanager_p.h.
Referenced by QGLEngineShaderManager::currentProgram(), QGLEngineShaderManager::simpleProgram(), and QGLEngineShaderManager::useSimpleProgram().
 { return simpleShaderProg; }
Properties
blitShaderProg
QGLShaderProgram* QGLEngineSharedShaders::blitShaderProg private
Definition at line 369 of file qglengineshadermanager_p.h.
Referenced by QGLEngineSharedShaders(), and ~QGLEngineSharedShaders().
cachedPrograms
QList<QGLEngineShaderProg*> QGLEngineSharedShaders::cachedPrograms private
Definition at line 371 of file qglengineshadermanager_p.h.
Referenced by cleanupCustomStage(), findProgramInCache(), and ~QGLEngineSharedShaders().
ctxGuard
QGLSharedResourceGuard QGLEngineSharedShaders::ctxGuard private
Definition at line 368 of file qglengineshadermanager_p.h.
Referenced by findProgramInCache().
qShaderSnippets
const char * QGLEngineSharedShaders::qShaderSnippets static private
Initial value:
= {
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,0,0,
    0,0,0,0,0
}
Definition at line 374 of file qglengineshadermanager_p.h.
Referenced by findProgramInCache(), QGLEngineSharedShaders(), and shadersForContext().
shaders
QList<QGLShader *> QGLEngineSharedShaders::shaders private
Definition at line 372 of file qglengineshadermanager_p.h.
Referenced by findProgramInCache(), QGLEngineSharedShaders(), and ~QGLEngineSharedShaders().
simpleShaderProg
QGLShaderProgram* QGLEngineSharedShaders::simpleShaderProg private
Definition at line 370 of file qglengineshadermanager_p.h.
Referenced by QGLEngineSharedShaders(), and ~QGLEngineSharedShaders().
The documentation for this class was generated from the following files:
/src/opengl/gl2paintengineex/qglengineshadermanager_p.h
/src/opengl/gl2paintengineex/qglengineshadermanager.cpp