Qt 4.8: QDBusArgumentPrivate Class Reference
QDBusArgumentPrivate Class Reference
#include <qdbusargument_p.h>
Public Types
enum Direction { Marshalling, Demarshalling }
Public Functions
QDBusDemarshaller * demarshaller ()
QDBusMarshaller * marshaller ()
QDBusArgumentPrivate (int flags=0)
~QDBusArgumentPrivate ()
Static Public Functions
static bool checkRead (QDBusArgumentPrivate *d)
static bool checkReadAndDetach (QDBusArgumentPrivate *&d)
static bool checkWrite (QDBusArgumentPrivate *&d)
static QDBusArgument create (QDBusArgumentPrivate *d)
static QByteArray createSignature (int id)
static QDBusArgumentPrivate * d (QDBusArgument &q)
Public Variables
int capabilities
enum QDBusArgumentPrivate::Direction direction
DBusMessage * message
QAtomicInt ref
Detailed Description
Definition at line 71 of file qdbusargument_p.h.
Enumerations
Direction
enum QDBusArgumentPrivate::Direction
Enumerator
Marshalling
Demarshalling
Definition at line 99 of file qdbusargument_p.h.
                    {
         Marshalling,
         Demarshalling
     } direction;
Constructors and Destructors
QDBusArgumentPrivate()
QDBusArgumentPrivate::QDBusArgumentPrivate (int flags = 0) inline
Definition at line 74 of file qdbusargument_p.h.
         : message(0), ref(1), capabilities(flags)
     { }
~QDBusArgumentPrivate()
QDBusArgumentPrivate::~QDBusArgumentPrivate ()
Definition at line 63 of file qdbusargument.cpp.
Referenced by QDBusArgumentPrivate().
 {
     if (message)
         q_dbus_message_unref(message);
 }
Functions
checkRead()
bool QDBusArgumentPrivate::checkRead (QDBusArgumentPrivate * d) static
Definition at line 136 of file qdbusargument.cpp.
Referenced by QDBusArgument::asVariant(), QDBusArgument::atEnd(), checkReadAndDetach(), and QDBusArgumentPrivate().
 {
     if (!d)
         return false;
     if (d->direction == Demarshalling)
         return true;
 #ifdef QT_DEBUG
     qFatal("QDBusArgument: read from a write-only object");
 #else
     qWarning("QDBusArgument: read from a write-only object");
 #endif
     return false;
 }
checkReadAndDetach()
bool QDBusArgumentPrivate::checkReadAndDetach (QDBusArgumentPrivate *& d) static
Definition at line 152 of file qdbusargument.cpp.
Referenced by QDBusArgument::beginArray(), QDBusArgument::beginMap(), QDBusArgument::beginMapEntry(), QDBusArgument::beginStructure(), QDBusArgument::endArray(), QDBusArgument::endMap(), QDBusArgument::endMapEntry(), QDBusArgument::endStructure(), QDBusArgument::operator>>(), and QDBusArgumentPrivate().
 {
     if (!checkRead(d))
         return false;           //  don't bother
     if (d->ref == 1)
         return true;            // no need to detach
     QDBusDemarshaller *dd = new QDBusDemarshaller(d->capabilities);
     dd->message = q_dbus_message_ref(d->message);
     dd->iterator = static_cast<QDBusDemarshaller*>(d)->iterator;
     if (!d->ref.deref())
         delete d;
     d = dd;
     return true;
 }
checkWrite()
bool QDBusArgumentPrivate::checkWrite (QDBusArgumentPrivate *& d) static
Definition at line 108 of file qdbusargument.cpp.
Referenced by QDBusArgument::appendVariant(), QDBusArgument::beginArray(), QDBusArgument::beginMap(), QDBusArgument::beginMapEntry(), QDBusArgument::beginStructure(), QDBusArgument::endArray(), QDBusArgument::endMap(), QDBusArgument::endMapEntry(), QDBusArgument::endStructure(), QDBusArgument::operator<<(), and QDBusArgumentPrivate().
 {
     if (!d)
         return false;
     if (d->direction == Marshalling) {
         if (!d->marshaller()->ok)
             return false;
         if (d->message && d->ref != 1) {
             QDBusMarshaller *dd = new QDBusMarshaller(d->capabilities);
             dd->message = q_dbus_message_copy(d->message);
             q_dbus_message_iter_init_append(dd->message, &dd->iterator);
             if (!d->ref.deref())
                 delete d;
             d = dd;
         }
         return true;
     }
 #ifdef QT_DEBUG
     qFatal("QDBusArgument: write from a read-only object");
 #else
     qWarning("QDBusArgument: write from a read-only object");
 #endif
     return false;
 }
create()
static QDBusArgument QDBusArgumentPrivate::create (QDBusArgumentPrivate * d) inline static
Definition at line 87 of file qdbusargument_p.h.
Referenced by QDBusMarshaller::appendRegisteredType(), and QDBusDemarshaller::duplicate().
     {
         QDBusArgument q(d);
         return q;
     }
createSignature()
QByteArray QDBusArgumentPrivate::createSignature (int id) static
Definition at line 69 of file qdbusargument.cpp.
Referenced by QDBusArgumentPrivate(), and QDBusMetaType::typeToSignature().
 {
     if (!qdbus_loadLibDBus())
         return "";
     QByteArray signature;
     QDBusMarshaller *marshaller = new QDBusMarshaller(0);
     marshaller->ba = &signature;
     // run it
     void *null = 0;
     QVariant v(id, null);
     QDBusArgument arg(marshaller);
     QDBusMetaType::marshall(arg, v.userType(), v.constData());
     arg.d = 0;
     // delete it
     bool ok = marshaller->ok;
     delete marshaller;
     if (signature.isEmpty() || !ok || !QDBusUtil::isValidSingleSignature(QString::fromLatin1(signature))) {
         qWarning("QDBusMarshaller: type `%s' produces invalid D-BUS signature `%s' "
                  "(Did you forget to call beginStructure() ?)",
                  QVariant::typeToName( QVariant::Type(id) ),
                  signature.isEmpty() ? "<empty>" : signature.constData());
         return "";
     } else if ((signature.at(0) != DBUS_TYPE_ARRAY && signature.at(0) != DBUS_STRUCT_BEGIN_CHAR) ||
                (signature.at(0) == DBUS_TYPE_ARRAY && (signature.at(1) == DBUS_TYPE_BYTE ||
                                                        signature.at(1) == DBUS_TYPE_STRING))) {
         qWarning("QDBusMarshaller: type `%s' attempts to redefine basic D-BUS type '%s' (%s) "
                  "(Did you forget to call beginStructure() ?)",
                  QVariant::typeToName( QVariant::Type(id) ),
                  signature.constData(),
                  QVariant::typeToName( QVariant::Type(QDBusMetaType::signatureToType(signature))) );
         return "";
     }
     return signature;
 }
d()
static QDBusArgumentPrivate* QDBusArgumentPrivate::d (QDBusArgument & q) inline static
Definition at line 92 of file qdbusargument_p.h.
Referenced by QDBusMarshaller::appendVariantInternal(), QDBusMarshaller::beginCommon(), QDBusDemarshaller::beginCommon(), checkReadAndDetach(), QDBusDemarshaller::duplicate(), QDBusArgument::QDBusArgument(), and QDBusArgumentPrivate().
     { return q.d; }
demarshaller()
QDBusDemarshaller * QDBusArgumentPrivate::demarshaller () inline
Definition at line 222 of file qdbusargument_p.h.
Referenced by QDBusMarshaller::appendVariantInternal(), QDBusArgument::asVariant(), QDBusArgument::atEnd(), QDBusArgument::beginArray(), QDBusArgument::beginMap(), QDBusArgument::beginMapEntry(), QDBusArgument::beginStructure(), QDBusArgument::currentSignature(), QDBusArgument::currentType(), QDBusArgument::endArray(), QDBusArgument::endMap(), QDBusArgument::endMapEntry(), QDBusArgument::endStructure(), QDBusArgument::operator>>(), and QDBusArgumentPrivate().
 { return static_cast<QDBusDemarshaller *>(this); }
marshaller()
QDBusMarshaller * QDBusArgumentPrivate::marshaller () inline
Definition at line 219 of file qdbusargument_p.h.
Referenced by QDBusArgument::appendVariant(), QDBusArgument::beginArray(), QDBusArgument::beginMap(), QDBusArgument::beginMapEntry(), QDBusArgument::beginStructure(), checkWrite(), createSignature(), QDBusArgument::currentSignature(), QDBusArgument::endArray(), QDBusArgument::endMap(), QDBusArgument::endMapEntry(), QDBusArgument::endStructure(), QDBusArgument::operator<<(), and QDBusArgumentPrivate().
 { return static_cast<QDBusMarshaller *>(this); }
Properties
capabilities
int QDBusArgumentPrivate::capabilities
Definition at line 98 of file qdbusargument_p.h.
Referenced by QDBusMarshaller::append(), QDBusMarshaller::appendCrossMarshalling(), QDBusMarshaller::appendVariantInternal(), QDBusMarshaller::beginCommon(), QDBusDemarshaller::beginCommon(), checkReadAndDetach(), checkWrite(), QDBusDemarshaller::currentType(), QDBusDemarshaller::duplicate(), QDBusMarshaller::open(), QDBusDemarshaller::toStringListUnchecked(), QDBusDemarshaller::toVariant(), and QDBusDemarshaller::toVariantInternal().
direction
enum QDBusArgumentPrivate::Direction QDBusArgumentPrivate::direction
Referenced by checkRead(), checkWrite(), QDBusArgument::currentSignature(), QDBusArgument::currentType(), QDBusDemarshaller::QDBusDemarshaller(), and QDBusMarshaller::QDBusMarshaller().
message
DBusMessage* QDBusArgumentPrivate::message
Definition at line 96 of file qdbusargument_p.h.
Referenced by QDBusMarshaller::appendVariantInternal(), QDBusDemarshaller::beginCommon(), checkReadAndDetach(), checkWrite(), QDBusMarshaller::currentSignature(), QDBusDemarshaller::duplicate(), QDBusMessagePrivate::fromDBusMessage(), QDBusArgument::QDBusArgument(), QDBusMarshaller::QDBusMarshaller(), QDBusDemarshaller::toVariant(), and ~QDBusArgumentPrivate().
ref
QAtomicInt QDBusArgumentPrivate::ref
Definition at line 97 of file qdbusargument_p.h.
Referenced by QDBusMarshaller::appendRegisteredType(), checkReadAndDetach(), checkWrite(), QDBusArgument::QDBusArgument(), and QDBusArgument::~QDBusArgument().
The documentation for this class was generated from the following files:
/src/dbus/qdbusargument_p.h
/src/dbus/qdbusargument.cpp