Qt 4.8: QDeclarativeContextScriptClass Class Reference
QDeclarativeContextScriptClass Class Reference
#include <qdeclarativecontextscriptclass_p.h>
Public Functions
QDeclarativeContextData * contextFromValue (const QScriptValue &)
QScriptValue newContext (QDeclarativeContextData *, QObject *=0)
QScriptValue newSharedContext ()
QScriptValue newUrlContext (QDeclarativeContextData *, QObject *, const QString &)
QScriptValue newUrlContext (const QString &)
QDeclarativeContextScriptClass (QDeclarativeEngine *)
QObject * setOverrideObject (QScriptValue &, QObject *)
QUrl urlFromValue (const QScriptValue &)
~QDeclarativeContextScriptClass ()
Public Functions inherited from QScriptDeclarativeClass
virtual Value call (Object *, QScriptContext *)
virtual bool compare (Object *, Object *)
QScriptContext * context () const
PersistentIdentifier createPersistentIdentifier (const QString &)
PersistentIdentifier createPersistentIdentifier (const Identifier &)
QScriptEngine * engine () const
virtual bool isQObject () const
virtual QScriptValue::PropertyFlags propertyFlags (Object *, const Identifier &)
virtual QStringList propertyNames (Object *)
QScriptDeclarativeClass (QScriptEngine *engine)
void setSupportsCall (bool)
bool startsWithUpper (const Identifier &)
bool supportsCall () const
quint32 toArrayIndex (const Identifier &, bool *ok)
virtual QObject * toQObject (Object *, bool *ok=0)
QString toString (const Identifier &)
virtual QVariant toVariant (Object *, bool *ok=0)
virtual ~QScriptDeclarativeClass ()
Protected Functions
virtual Value property (Object *, const Identifier &)
virtual QScriptClass::QueryFlags queryProperty (Object *, const Identifier &, QScriptClass::QueryFlags flags)
virtual void setProperty (Object *, const Identifier &name, const QScriptValue &)
Private Functions
QScriptClass::QueryFlags queryProperty (QDeclarativeContextData *, QObject *scopeObject, const Identifier &, QScriptClass::QueryFlags flags, bool includeTypes)
Properties
QDeclarativeEngine * engine
QDeclarativeContextData * lastContext
QDeclarativeTypeNameCache::Data * lastData
QScriptValue lastFunction
int lastPropertyIndex
QObject * lastScopeObject
uint m_id
Additional Inherited Members
Public Types inherited from QScriptDeclarativeClass
typedef void * Identifier
Static Public Functions inherited from QScriptDeclarativeClass
static QScriptValue function (const QScriptValue &, const Identifier &)
static Value functionValue (const QScriptValue &, const Identifier &)
static QScriptValue newObject (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static Value newObjectValue (QScriptEngine *, QScriptDeclarativeClass *, Object *)
static QScriptValue newStaticScopeObject (QScriptEngine *, int propertyCount, const QString *names, const QScriptValue *values, const QScriptValue::PropertyFlags *flags)
Creates a scope object with a fixed set of undeletable properties.
static QScriptValue newStaticScopeObject (QScriptEngine *)
Creates a static scope object that's initially empty, but to which new properties can be added.
static Object * object (const QScriptValue &)
static QScriptValue property (const QScriptValue &, const Identifier &)
static Value propertyValue (const QScriptValue &, const Identifier &)
static QScriptContext * pushCleanContext (QScriptEngine *)
Enters a new execution context and returns the associated QScriptContext object.
static QScriptValue scopeChainValue (QScriptContext *, int index)
static QScriptDeclarativeClass * scriptClass (const QScriptValue &)
Protected Variables inherited from QScriptDeclarativeClass
QScopedPointer< QScriptDeclarativeClassPrivate > d_ptr
Detailed Description
Definition at line 64 of file qdeclarativecontextscriptclass_p.h.
Constructors and Destructors
QDeclarativeContextScriptClass()
QDeclarativeContextScriptClass::QDeclarativeContextScriptClass (QDeclarativeEngine * bindEngine)
Definition at line 95 of file qdeclarativecontextscriptclass.cpp.
 : QScriptDeclarativeClass(QDeclarativeEnginePrivate::getScriptEngine(bindEngine)), engine(bindEngine),
   lastScopeObject(0), lastContext(0), lastData(0), lastPropertyIndex(-1)
 {
 }
~QDeclarativeContextScriptClass()
QDeclarativeContextScriptClass::~QDeclarativeContextScriptClass ()
Definition at line 101 of file qdeclarativecontextscriptclass.cpp.
 {
 }
Functions
contextFromValue()
QDeclarativeContextData * QDeclarativeContextScriptClass::contextFromValue (const QScriptValue & v)
Definition at line 134 of file qdeclarativecontextscriptclass.cpp.
Referenced by QDeclarativeInclude::include(), QDeclarativeInclude::QDeclarativeInclude(), QDeclarativeObjectScriptClass::queryProperty(), and QDeclarativeObjectScriptClass::setProperty().
 {
     if (scriptClass(v) != this)
         return 0;
     ContextData *data = (ContextData *)object(v);
     return data->getContext(engine);
 }
newContext()
QScriptValue QDeclarativeContextScriptClass::newContext (QDeclarativeContextData * context, QObject * scopeObject = 0)
Definition at line 105 of file qdeclarativecontextscriptclass.cpp.
Referenced by QDeclarativeExpressionPrivate::evalInObjectScope(), and QDeclarativeExpressionPrivate::scriptValue().
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     return newObject(scriptEngine, this, new ContextData(context, scopeObject));
 }
newSharedContext()
QScriptValue QDeclarativeContextScriptClass::newSharedContext ()
Definition at line 127 of file qdeclarativecontextscriptclass.cpp.
Referenced by QDeclarativeExpressionPrivate::init().
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     return newObject(scriptEngine, this, new ContextData());
 }
newUrlContext() [1/2]
QScriptValue QDeclarativeContextScriptClass::newUrlContext (QDeclarativeContextData * context, QObject * scopeObject, const QString & url)
Definition at line 112 of file qdeclarativecontextscriptclass.cpp.
Referenced by QDeclarativeContextData::addImportedScript(), QDeclarativeInclude::finished(), and QDeclarativeInclude::include().
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     return newObject(scriptEngine, this, new UrlContextData(context, scopeObject, url));
 }
newUrlContext() [2/2]
QScriptValue QDeclarativeContextScriptClass::newUrlContext (const QString & url)
Definition at line 120 of file qdeclarativecontextscriptclass.cpp.
 {
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     return newObject(scriptEngine, this, new UrlContextData(url));
 }
property()
QDeclarativeContextScriptClass::Value QDeclarativeContextScriptClass::property (Object * object, const Identifier & name) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 262 of file qdeclarativecontextscriptclass.cpp.
 {
     Q_UNUSED(object);
     QDeclarativeContextData *bindContext = lastContext;
     Q_ASSERT(bindContext);
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     QScriptEngine *scriptEngine = QDeclarativeEnginePrivate::getScriptEngine(engine);
     if (lastData) {
         if (lastData->type) {
             return Value(scriptEngine, ep->typeNameClass->newObject(lastScopeObject, lastData->type));
         } else if (lastData->typeNamespace) {
             return Value(scriptEngine, ep->typeNameClass->newObject(lastScopeObject, lastData->typeNamespace));
         } else {
             int index = lastData->importedScriptIndex;
             if (index < bindContext->importedScripts.count()) {
                 return Value(scriptEngine, bindContext->importedScripts.at(index));
             } else {
                 return Value();
             }
         }
     } else if (lastScopeObject) {
         return ep->objectClass->property(lastScopeObject, name);
     } else if (lastPropertyIndex != -1) {
         QScriptValue rv;
         if (lastPropertyIndex < bindContext->idValueCount) {
             rv =  ep->objectClass->newQObject(bindContext->idValues[lastPropertyIndex].data());
             if (ep->captureProperties)
                 ep->capturedProperties << QDeclarativeEnginePrivate::CapturedProperty(&bindContext->idValues[lastPropertyIndex].bindings);
         } else {
             QDeclarativeContextPrivate *cp = bindContext->asQDeclarativeContextPrivate();
             const QVariant &value = cp->propertyValues.at(lastPropertyIndex);
             if (value.userType() == qMetaTypeId<QList<QObject*> >()) {
                 rv = ep->listClass->newList(QDeclarativeListProperty<QObject>(bindContext->asQDeclarativeContext(), (void*)lastPropertyIndex, 0, QDeclarativeContextPrivate::context_count, QDeclarativeContextPrivate::context_at), qMetaTypeId<QDeclarativeListProperty<QObject> >());
             } else {
                 rv = ep->scriptValueFromVariant(value);
             }
             if (ep->captureProperties)
                 ep->capturedProperties << QDeclarativeEnginePrivate::CapturedProperty(bindContext->asQDeclarativeContext(), -1, lastPropertyIndex + cp->notifyIndex);
         }
         return Value(scriptEngine, rv);
     } else {
         return Value(scriptEngine, lastFunction);
     }
 }
queryProperty() [1/2]
QScriptClass::QueryFlags QDeclarativeContextScriptClass::queryProperty (Object * object, const Identifier & name, QScriptClass::QueryFlags flags) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 168 of file qdeclarativecontextscriptclass.cpp.
 {
     Q_UNUSED(flags);
     lastScopeObject = 0;
     lastContext = 0;
     lastData = 0;
     lastPropertyIndex = -1;
     QDeclarativeContextData *bindContext = ((ContextData *)object)->getContext(engine);
     QObject *scopeObject = ((ContextData *)object)->getScope(engine);
     if (!bindContext)
         return 0;
     QObject *overrideObject = ((ContextData *)object)->overrideObject;
     if (overrideObject) {
         QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
         QScriptClass::QueryFlags rv =
             ep->objectClass->queryProperty(overrideObject, name, flags, bindContext,
                                            QDeclarativeObjectScriptClass::ImplicitObject |
                                            QDeclarativeObjectScriptClass::SkipAttachedProperties);
         if (rv) {
             lastScopeObject = overrideObject;
             lastContext = bindContext;
             return rv;
         }
     }
     bool includeTypes = true;
     while (bindContext) {
         QScriptClass::QueryFlags rv =
             queryProperty(bindContext, scopeObject, name, flags, includeTypes);
         scopeObject = 0; // Only applies to the first context
         includeTypes = false; // Only applies to the first context
         if (rv) return rv;
         bindContext = bindContext->parent;
     }
     return 0;
 }
queryProperty() [2/2]
QScriptClass::QueryFlags QDeclarativeContextScriptClass::queryProperty (QDeclarativeContextData * bindContext, QObject * scopeObject, const Identifier & name, QScriptClass::QueryFlags flags, bool includeTypes) private
Definition at line 211 of file qdeclarativecontextscriptclass.cpp.
 {
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     lastPropertyIndex = bindContext->propertyNames?bindContext->propertyNames->value(name):-1;
     if (lastPropertyIndex != -1) {
         lastContext = bindContext;
         return QScriptClass::HandlesReadAccess;
     }
     if (includeTypes && bindContext->imports) {
         QDeclarativeTypeNameCache::Data *data = bindContext->imports->data(name);
         if (data)  {
             lastData = data;
             lastContext = bindContext;
             lastScopeObject = scopeObject;
             return QScriptClass::HandlesReadAccess;
         }
     }
     if (scopeObject) {
         QScriptClass::QueryFlags rv =
             ep->objectClass->queryProperty(scopeObject, name, flags, bindContext,
                                            QDeclarativeObjectScriptClass::ImplicitObject | QDeclarativeObjectScriptClass::SkipAttachedProperties);
         if (rv) {
             lastScopeObject = scopeObject;
             lastContext = bindContext;
             return rv;
         }
     }
     if (bindContext->contextObject) {
         QScriptClass::QueryFlags rv =
             ep->objectClass->queryProperty(bindContext->contextObject, name, flags, bindContext,
                                            QDeclarativeObjectScriptClass::ImplicitObject | QDeclarativeObjectScriptClass::SkipAttachedProperties);
         if (rv) {
             lastScopeObject = bindContext->contextObject;
             lastContext = bindContext;
             return rv;
         }
     }
     return 0;
 }
setOverrideObject()
QObject * QDeclarativeContextScriptClass::setOverrideObject (QScriptValue & v, QObject * override)
Definition at line 156 of file qdeclarativecontextscriptclass.cpp.
Referenced by QDeclarativeQtScriptExpression::eval().
 {
     if (scriptClass(v) != this)
         return 0;
     ContextData *data = (ContextData *)object(v);
     QObject *rv = data->overrideObject;
     data->overrideObject = override;
     return rv;
 }
setProperty()
void QDeclarativeContextScriptClass::setProperty (Object * object, const Identifier & name, const QScriptValue & value) protected virtual
Reimplemented from QScriptDeclarativeClass.
Definition at line 321 of file qdeclarativecontextscriptclass.cpp.
 {
     Q_UNUSED(object);
     Q_ASSERT(lastScopeObject);
     QDeclarativeContextData *bindContext = lastContext;
     Q_ASSERT(bindContext);
     QDeclarativeEnginePrivate *ep = QDeclarativeEnginePrivate::get(engine);
     ep->objectClass->setProperty(lastScopeObject, name, value, context(), bindContext);
 }
urlFromValue()
QUrl QDeclarativeContextScriptClass::urlFromValue (const QScriptValue & v)
Definition at line 143 of file qdeclarativecontextscriptclass.cpp.
Referenced by QDeclarativeInclude::include().
 {
     if (scriptClass(v) != this)
         return QUrl();
     ContextData *data = (ContextData *)object(v);
     if (data->isUrlContext) {
         return QUrl(static_cast<UrlContextData *>(data)->url);
     } else {
         return QUrl();
     }
 }
Properties
engine
QDeclarativeEngine* QDeclarativeContextScriptClass::engine private
Definition at line 92 of file qdeclarativecontextscriptclass_p.h.
lastContext
QDeclarativeContextData* QDeclarativeContextScriptClass::lastContext private
Definition at line 95 of file qdeclarativecontextscriptclass_p.h.
Referenced by property(), queryProperty(), and setProperty().
lastData
QDeclarativeTypeNameCache::Data* QDeclarativeContextScriptClass::lastData private
Definition at line 96 of file qdeclarativecontextscriptclass_p.h.
Referenced by property(), and queryProperty().
lastFunction
QScriptValue QDeclarativeContextScriptClass::lastFunction private
Definition at line 98 of file qdeclarativecontextscriptclass_p.h.
Referenced by property().
lastPropertyIndex
int QDeclarativeContextScriptClass::lastPropertyIndex private
Definition at line 97 of file qdeclarativecontextscriptclass_p.h.
Referenced by property(), and queryProperty().
lastScopeObject
QObject* QDeclarativeContextScriptClass::lastScopeObject private
Definition at line 94 of file qdeclarativecontextscriptclass_p.h.
Referenced by property(), queryProperty(), and setProperty().
m_id
uint QDeclarativeContextScriptClass::m_id private
Definition at line 100 of file qdeclarativecontextscriptclass_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativecontextscriptclass_p.h
/src/declarative/qml/qdeclarativecontextscriptclass.cpp