Qt 4.8: QDeclarativeVMEStack< T > Class Template Reference
QDeclarativeVMEStack< T > Class Template Reference
Public Functions
const T & at (int index) const
int count () const
bool isEmpty () const
T pop ()
void push (const T &o)
QDeclarativeVMEStack ()
const T & top () const
Private Types
typedef QVarLengthArray< T, 128 > VLA
Private Types inherited from QVarLengthArray< T, 128 >
typedef const T * const_iterator
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef qptrdiff difference_type
typedef T * iterator
typedef value_type * pointer
typedef value_type & reference
typedef int size_type
typedef T value_type
Properties
int _index
Properties inherited from QVarLengthArray< T, 128 >
char array [sizeof(qint64) *(((Prealloc *sizeof(T))/sizeof(qint64))+1)]
qint64 q_for_alignment_1
double q_for_alignment_2
Additional Inherited Members
Private Functions inherited from QVarLengthArray< T, 128 >
void append (const T &t)
void append (const T *buf, int size)
const T & at (int idx) const
iterator begin ()
const_iterator begin () const
int capacity () const
void clear ()
const_iterator constBegin () const
const T * constData () const
const_iterator constEnd () const
int count () const
T * data ()
const T * data () const
iterator end ()
const_iterator end () const
iterator erase (iterator begin, iterator end)
iterator erase (iterator pos)
void insert (int i, const T &t)
void insert (int i, int n, const T &t)
iterator insert (iterator before, int n, const T &x)
iterator insert (iterator before, const T &x)
bool isEmpty () const
QVarLengthArray< T, Prealloc > & operator+= (const T &t)
QVarLengthArray< T, Prealloc > & operator<< (const T &t)
QVarLengthArray< T, Prealloc > & operator= (const QVarLengthArray< T, Prealloc > &other)
T & operator[] (int idx)
const T & operator[] (int idx) const
void prepend (const T &t)
QVarLengthArray (int size=0)
QVarLengthArray (const QVarLengthArray< T, Prealloc > &other)
void remove (int i)
void remove (int i, int n)
void removeLast ()
void replace (int i, const T &t)
void reserve (int size)
void resize (int size)
int size () const
T value (int i) const
T value (int i, const T &defaultValue) const
~QVarLengthArray ()
Detailed Description
template<typename T>
class QDeclarativeVMEStack< T >
Definition at line 79 of file qdeclarativevme.cpp.
Typedefs
VLA
template<typename T> typedef QVarLengthArray<T, 128> QDeclarativeVMEStack< T >::VLA private
Definition at line 82 of file qdeclarativevme.cpp.
Constructors and Destructors
QDeclarativeVMEStack()
template<typename T > QDeclarativeVMEStack< T >::QDeclarativeVMEStack () inline
Definition at line 1081 of file qdeclarativevme.cpp.
 : _index(-1)
 {
 }
Functions
at()
template<typename T > const T & QDeclarativeVMEStack< T >::at (int index) const inline
Definition at line 1120 of file qdeclarativevme.cpp.
Referenced by QDeclarativeVMEStack< QObject *>::top().
{
     return VLA::data()[index];
 }
count()
template<typename T > int QDeclarativeVMEStack< T >::count () const inline
Definition at line 1115 of file qdeclarativevme.cpp.
Referenced by QDeclarativeVME::run(), and QDeclarativeVME::runDeferred().
{
     return _index + 1;
 }
isEmpty()
template<typename T > bool QDeclarativeVMEStack< T >::isEmpty () const inline
Definition at line 1087 of file qdeclarativevme.cpp.
Referenced by QDeclarativeVME::run().
{
     return _index == -1;
 }
pop()
template<typename T > T QDeclarativeVMEStack< T >::pop () inline
Definition at line 1108 of file qdeclarativevme.cpp.
{
     Q_ASSERT(_index >= 0);
     --_index;
     return VLA::data()[_index + 1];
 }
push()
template<typename T> void QDeclarativeVMEStack< T >::push (const T & o) inline
Definition at line 1097 of file qdeclarativevme.cpp.
Referenced by QDeclarativeVME::run(), and QDeclarativeVME::runDeferred().
{
     _index++;
     Q_ASSERT(_index <= VLA::size());
     if (_index == VLA::size())
         VLA::append(o);
     else
         VLA::data()[_index] = o;
 }
top()
template<typename T > const T & QDeclarativeVMEStack< T >::top () const inline
Definition at line 1092 of file qdeclarativevme.cpp.
Referenced by QDeclarativeVME::run().
{
     return at(_index);
 }
Properties
_index
template<typename T> int QDeclarativeVMEStack< T >::_index private
Definition at line 83 of file qdeclarativevme.cpp.
Referenced by QDeclarativeVMEStack< QObject *>::count(), QDeclarativeVMEStack< QObject *>::isEmpty(), QDeclarativeVMEStack< QObject *>::pop(), QDeclarativeVMEStack< QObject *>::push(), and QDeclarativeVMEStack< QObject *>::top().
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativevme.cpp