Qt 4.8: QGraphicsSceneIndex Class Reference
QGraphicsSceneIndex Class Reference abstract
The QGraphicsSceneIndex class provides a base class to implement a custom indexing algorithm for discovering items in QGraphicsScene.
#include <qgraphicssceneindex_p.h>
Public Functions
virtual QList< QGraphicsItem * > estimateItems (const QPointF &point, Qt::SortOrder order) const
This virtual function return an estimation of items at position point.
virtual QList< QGraphicsItem * > estimateItems (const QRectF &rect, Qt::SortOrder order) const =0
virtual QList< QGraphicsItem * > estimateTopLevelItems (const QRectF &, Qt::SortOrder order) const
virtual QList< QGraphicsItem * > items (Qt::SortOrder order=Qt::DescendingOrder) const =0
This pure virtual function all items in the index and sort them using order.
virtual QList< QGraphicsItem * > items (const QPointF &pos, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform &deviceTransform=QTransform()) const
Returns all visible items that, depending on mode, are at the specified pos and return a list sorted using order.
virtual QList< QGraphicsItem * > items (const QRectF &rect, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform &deviceTransform=QTransform()) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns all visible items that, depending on mode, are either inside or intersect with the specified rect and return a list sorted using order.
virtual QList< QGraphicsItem * > items (const QPolygonF &polygon, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform &deviceTransform=QTransform()) const
virtual QList< QGraphicsItem * > items (const QPainterPath &path, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform &deviceTransform=QTransform()) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns all visible items that, depending on mode, are either inside or intersect with the specified path and return a list sorted using order.
QGraphicsSceneIndex (QGraphicsScene *scene=0)
Constructs an abstract scene index for a given scene.
QGraphicsScene * scene () const
Returns the scene of this index.
virtual ~QGraphicsSceneIndex ()
Destroys the scene index.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
virtual void updateSceneRect (const QRectF &rect)
Notifies the index that the scene's scene rect has changed.
Protected Functions
virtual void addItem (QGraphicsItem *item)=0
This pure virtual function inserts an item to the scene index.
virtual void clear ()
This virtual function removes all items in the scene index.
virtual void deleteItem (QGraphicsItem *item)
This method is called when an item has been deleted.
virtual void itemChange (const QGraphicsItem *item, QGraphicsItem::GraphicsItemChange, const void *const value)
This virtual function is called by QGraphicsItem to notify the index that some part of the item 's state changes.
virtual void prepareBoundingRectChange (const QGraphicsItem *item)
Notify the index for a geometry change of an item.
QGraphicsSceneIndex (QGraphicsSceneIndexPrivate &dd, QGraphicsScene *scene)
virtual void removeItem (QGraphicsItem *item)=0
This pure virtual function removes an item to the scene index.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Friends
class QGraphicsItem
class QGraphicsItemPrivate
class QGraphicsScene
class QGraphicsSceneBspTreeIndex
class QGraphicsScenePrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsSceneIndex class provides a base class to implement a custom indexing algorithm for discovering items in QGraphicsScene.
Since
4.6
Warning
This function is not part of the public interface.
The QGraphicsSceneIndex class provides a base class to implement a custom indexing algorithm for discovering items in QGraphicsScene. You need to subclass it and reimplement addItem, removeItem, estimateItems and items in order to have an functional indexing.
See also
QGraphicsScene, QGraphicsView
Definition at line 81 of file qgraphicssceneindex_p.h.
Constructors and Destructors
QGraphicsSceneIndex() [1/2]
QGraphicsSceneIndex::QGraphicsSceneIndex (QGraphicsScene * scene = 0)
Constructs an abstract scene index for a given scene.
Definition at line 373 of file qgraphicssceneindex.cpp.
 : QObject(*new QGraphicsSceneIndexPrivate(scene), scene)
 {
     d_func()->init();
 }
~QGraphicsSceneIndex()
QGraphicsSceneIndex::~QGraphicsSceneIndex () virtual
Destroys the scene index.
Definition at line 391 of file qgraphicssceneindex.cpp.
 {
 }
QGraphicsSceneIndex() [2/2]
QGraphicsSceneIndex::QGraphicsSceneIndex (QGraphicsSceneIndexPrivate & dd, QGraphicsScene * scene) protected
Warning
This function is not part of the public interface.
Definition at line 382 of file qgraphicssceneindex.cpp.
     : QObject(dd, scene)
 {
     d_func()->init();
 }
Functions
addItem()
void QGraphicsSceneIndex::addItem (QGraphicsItem * item) protected pure virtual
This pure virtual function inserts an item to the scene index.
See also
removeItem(), deleteItem()
Implemented in QGraphicsSceneBspTreeIndex, and QGraphicsSceneLinearIndex.
clear()
void QGraphicsSceneIndex::clear () protected virtual
This virtual function removes all items in the scene index.
Reimplemented in QGraphicsSceneBspTreeIndex, and QGraphicsSceneLinearIndex.
Definition at line 586 of file qgraphicssceneindex.cpp.
 {
     const QList<QGraphicsItem *> allItems = items();
     for (int i = 0 ; i < allItems.size(); ++i)
         removeItem(allItems.at(i));
 }
deleteItem()
void QGraphicsSceneIndex::deleteItem (QGraphicsItem * item) protected virtual
This method is called when an item has been deleted.
The default implementation call removeItem. Be carefull, if your implementation of removeItem use pure virtual method of QGraphicsItem like boundingRect(), then you should reimplement this method.
See also
addItem(), removeItem()
Definition at line 618 of file qgraphicssceneindex.cpp.
Referenced by QGraphicsScenePrivate::removeItemHelper().
 {
     removeItem(item);
 }
estimateItems() [1/2]
QList< QGraphicsItem * > QGraphicsSceneIndex::estimateItems (const QPointF & point, Qt::SortOrder order) const virtual
This virtual function return an estimation of items at position point.
This method return a list sorted using order.
Definition at line 544 of file qgraphicssceneindex.cpp.
 {
     return estimateItems(QRectF(point, QSize(1, 1)), order);
 }
estimateItems() [2/2]
virtual QList<QGraphicsItem *> QGraphicsSceneIndex::estimateItems (const QRectF & rect, Qt::SortOrder order) const pure virtual
Implemented in QGraphicsSceneBspTreeIndex, and QGraphicsSceneLinearIndex.
estimateTopLevelItems()
QList< QGraphicsItem * > QGraphicsSceneIndex::estimateTopLevelItems (const QRectF & rect, Qt::SortOrder order) const virtual
Reimplemented in QGraphicsSceneBspTreeIndex.
Definition at line 549 of file qgraphicssceneindex.cpp.
 {
     Q_D(const QGraphicsSceneIndex);
     Q_UNUSED(rect);
     QGraphicsScenePrivate *scened = d->scene->d_func();
     scened->ensureSortedTopLevelItems();
     if (order == Qt::DescendingOrder) {
         QList<QGraphicsItem *> sorted;
         for (int i = scened->topLevelItems.size() - 1; i >= 0; --i)
             sorted << scened->topLevelItems.at(i);
         return sorted;
     }
     return scened->topLevelItems;
 }
itemChange()
void QGraphicsSceneIndex::itemChange (const QGraphicsItem * item, QGraphicsItem::GraphicsItemChange change, const void *const value) protected virtual
This virtual function is called by QGraphicsItem to notify the index that some part of the item 's state changes.
By reimplementing this function, your can react to a change, and in some cases, (depending on change,) adjustments in the index can be made.
change is the parameter of the item that is changing. value is the value that changed; the type of the value depends on change.
The default implementation does nothing.
See also
QGraphicsItem::GraphicsItemChange
Reimplemented in QGraphicsSceneBspTreeIndex.
Definition at line 636 of file qgraphicssceneindex.cpp.
 {
     Q_UNUSED(item);
     Q_UNUSED(change);
     Q_UNUSED(value);
 }
items() [1/5]
QList< QGraphicsItem * > QGraphicsSceneIndex::items (Qt::SortOrder order = Qt::DescendingOrder) const pure virtual
This pure virtual function all items in the index and sort them using order.
Implemented in QGraphicsSceneBspTreeIndex, and QGraphicsSceneLinearIndex.
Referenced by clear().
items() [2/5]
QList< QGraphicsItem * > QGraphicsSceneIndex::items (const QPointF & pos, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform & deviceTransform = QTransform()) const virtual
Returns all visible items that, depending on mode, are at the specified pos and return a list sorted using order.
The default value for mode is Qt::IntersectsItemShape; all items whose exact shape intersects with pos are returned.
deviceTransform is the transformation apply to the view.
This method use the estimation of the index (estimateItems) and refine the list to get an exact result. If you want to implement your own refinement algorithm you can reimplement this method.
See also
estimateItems()
Definition at line 425 of file qgraphicssceneindex.cpp.
 {
     Q_D(const QGraphicsSceneIndex);
     QList<QGraphicsItem *> itemList;
     d->pointIntersector->scenePoint = pos;
     d->items_helper(QRectF(pos, QSizeF(1, 1)), d->pointIntersector, &itemList, deviceTransform, mode, order);
     return itemList;
 }
items() [3/5]
QList< QGraphicsItem * > QGraphicsSceneIndex::items (const QRectF & rect, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform & deviceTransform = QTransform()) const virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns all visible items that, depending on mode, are either inside or intersect with the specified rect and return a list sorted using order.
The default value for mode is Qt::IntersectsItemShape; all items whose exact shape intersects with or is contained by rect are returned.
deviceTransform is the transformation apply to the view.
This method use the estimation of the index (estimateItems) and refine the list to get an exact result. If you want to implement your own refinement algorithm you can reimplement this method.
See also
estimateItems()
Definition at line 458 of file qgraphicssceneindex.cpp.
 {
     Q_D(const QGraphicsSceneIndex);
     QRectF exposeRect = rect;
     _q_adjustRect(&exposeRect);
     QList<QGraphicsItem *> itemList;
     d->rectIntersector->sceneRect = rect;
     d->items_helper(exposeRect, d->rectIntersector, &itemList, deviceTransform, mode, order);
     return itemList;
 }
items() [4/5]
QList< QGraphicsItem * > QGraphicsSceneIndex::items (const QPolygonF & polygon, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform & deviceTransform = QTransform()) const virtual
Definition at line 492 of file qgraphicssceneindex.cpp.
 {
     Q_D(const QGraphicsSceneIndex);
     QList<QGraphicsItem *> itemList;
     QRectF exposeRect = polygon.boundingRect();
     _q_adjustRect(&exposeRect);
     QPainterPath path;
     path.addPolygon(polygon);
     d->pathIntersector->scenePath = path;
     d->items_helper(exposeRect, d->pathIntersector, &itemList, deviceTransform, mode, order);
     return itemList;
 }
items() [5/5]
QList< QGraphicsItem * > QGraphicsSceneIndex::items (const QPainterPath & path, Qt::ItemSelectionMode mode, Qt::SortOrder order, const QTransform & deviceTransform = QTransform()) const virtual
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns all visible items that, depending on mode, are either inside or intersect with the specified path and return a list sorted using order.
The default value for mode is Qt::IntersectsItemShape; all items whose exact shape intersects with or is contained by path are returned.
deviceTransform is the transformation apply to the view.
This method use the estimation of the index (estimateItems) and refine the list to get an exact result. If you want to implement your own refinement algorithm you can reimplement this method.
See also
estimateItems()
Definition at line 528 of file qgraphicssceneindex.cpp.
 {
     Q_D(const QGraphicsSceneIndex);
     QList<QGraphicsItem *> itemList;
     QRectF exposeRect = path.controlPointRect();
     _q_adjustRect(&exposeRect);
     d->pathIntersector->scenePath = path;
     d->items_helper(exposeRect, d->pathIntersector, &itemList, deviceTransform, mode, order);
     return itemList;
 }
prepareBoundingRectChange()
void QGraphicsSceneIndex::prepareBoundingRectChange (const QGraphicsItem * item) protected virtual
Notify the index for a geometry change of an item.
See also
QGraphicsItem::prepareGeometryChange()
Reimplemented in QGraphicsSceneBspTreeIndex.
Definition at line 648 of file qgraphicssceneindex.cpp.
Referenced by QGraphicsItem::prepareGeometryChange().
 {
     Q_UNUSED(item);
 }
removeItem()
void QGraphicsSceneIndex::removeItem (QGraphicsItem * item) protected pure virtual
This pure virtual function removes an item to the scene index.
See also
addItem(), deleteItem()
Implemented in QGraphicsSceneBspTreeIndex, and QGraphicsSceneLinearIndex.
Referenced by clear(), deleteItem(), and QGraphicsScenePrivate::removeItemHelper().
scene()
QGraphicsScene * QGraphicsSceneIndex::scene () const
Returns the scene of this index.
Definition at line 399 of file qgraphicssceneindex.cpp.
 {
     Q_D(const QGraphicsSceneIndex);
     return d->scene;
 }
updateSceneRect
void QGraphicsSceneIndex::updateSceneRect (const QRectF & rect) protected virtual slot
Notifies the index that the scene's scene rect has changed.
rect is thew new scene rect.
See also
QGraphicsScene::sceneRect()
Definition at line 578 of file qgraphicssceneindex.cpp.
 {
     Q_UNUSED(rect);
 }
Friends and Related Functions
QGraphicsItem
friend class QGraphicsItem friend
Definition at line 120 of file qgraphicssceneindex_p.h.
QGraphicsItemPrivate
friend class QGraphicsItemPrivate friend
Definition at line 121 of file qgraphicssceneindex_p.h.
QGraphicsScene
friend class QGraphicsScene friend
Definition at line 118 of file qgraphicssceneindex_p.h.
QGraphicsSceneBspTreeIndex
friend class QGraphicsSceneBspTreeIndex friend
Definition at line 122 of file qgraphicssceneindex_p.h.
QGraphicsScenePrivate
friend class QGraphicsScenePrivate friend
Definition at line 119 of file qgraphicssceneindex_p.h.
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicssceneindex_p.h
/src/gui/graphicsview/qgraphicssceneindex.cpp