Qt 4.8: QPatternist::XsdWildcard Class Reference
QPatternist::XsdWildcard Class Reference
XML Schema Processing
Represents a XSD wildcard object.
#include <qxsdwildcard_p.h>
Classes
class NamespaceConstraint
Public Types
enum ProcessContents { Strict, Lax, Skip }
typedef QExplicitlySharedDataPointer< XsdWildcard > Ptr
Public Types inherited from QPatternist::XsdTerm
typedef QExplicitlySharedDataPointer< XsdTerm > Ptr
Public Types inherited from QPatternist::NamedSchemaComponent
enum BlockingConstraint { RestrictionConstraint = 1, ExtensionConstraint = 2, SubstitutionConstraint = 4 }
typedef QExplicitlySharedDataPointer< NamedSchemaComponent > Ptr
Public Functions
virtual bool isWildcard () const
NamespaceConstraint::Ptr namespaceConstraint () const
ProcessContents processContents () const
void setNamespaceConstraint (const NamespaceConstraint::Ptr &constraint)
void setProcessContents (ProcessContents contents)
XsdWildcard ()
Public Functions inherited from QPatternist::XsdTerm
virtual bool isElement () const
virtual bool isModelGroup () const
virtual bool isReference () const
Public Functions inherited from QPatternist::NamedSchemaComponent
virtual QString displayName (const NamePool::Ptr &namePool) const
virtual QXmlName name (const NamePool::Ptr &namePool) const
NamedSchemaComponent ()
void setName (const QXmlName &name)
virtual ~NamedSchemaComponent ()
Public Functions inherited from QPatternist::SchemaComponent
SchemaComponent ()
virtual ~SchemaComponent ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::XsdAnnotated
void addAnnotation (const XsdAnnotation::Ptr &annotation)
void addAnnotations (const XsdAnnotation::List &annotations)
XsdAnnotation::List annotations () const
Static Public Functions
static QString absentNamespace ()
Properties
NamespaceConstraint::Ptr m_namespaceConstraint
ProcessContents m_processContents
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::XsdTerm
XsdTerm ()
Detailed Description
Represents a XSD wildcard object.
This class represents the wildcard object of a XML schema as described here.
It contains information from either an any object or an anyAttribute object.
See also
XML Schema API reference
Author
Tobias Koenig tobia.nosp@m.s.ko.nosp@m.enig@.nosp@m.noki.nosp@m.a.com
Definition at line 77 of file qxsdwildcard_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<XsdWildcard> QPatternist::XsdWildcard::Ptr
Definition at line 80 of file qxsdwildcard_p.h.
Enumerations
ProcessContents
enum QPatternist::XsdWildcard::ProcessContents
Describes the type of content processing of the wildcard.
Enumerator
Strict
There must be a top-level declaration for the item available, or the item must have an xsi:type, and the item must be valid as appropriate.
Lax
If the item has a uniquely determined declaration available, it must be valid with respect to that definition.
Skip
No constraints at all: the item must simply be well-formed XML.
Definition at line 148 of file qxsdwildcard_p.h.
             {
                 Strict,
                 Lax,
                 Skip
             };
Constructors and Destructors
XsdWildcard()
XsdWildcard::XsdWildcard ()
Creates a new wildcard object.
Definition at line 83 of file qxsdwildcard.cpp.
     : m_namespaceConstraint(new NamespaceConstraint())
     , m_processContents(Strict)
 {
     m_namespaceConstraint->setVariety(NamespaceConstraint::Any);
 }
Functions
absentNamespace()
QString XsdWildcard::absentNamespace () static
Defines the absent namespace that is used in wildcards.
Definition at line 48 of file qxsdwildcard.cpp.
Referenced by derivedTermValid(), QPatternist::XsdStateMachine< XsdSchemaToken::NodeName >::inputEqualsTransition(), QPatternist::XsdSchemaHelper::isValidAttributeUsesRestriction(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), termMatches(), QPatternist::XsdValidatingInstanceReader::validateAttributeWildcard(), QPatternist::XsdSchemaHelper::wildcardAllowsNamespaceName(), QPatternist::XsdSchemaHelper::wildcardIntersection(), and QPatternist::XsdSchemaHelper::wildcardUnion().
 {
     return QLatin1String("__ns_absent");
 }
isWildcard()
bool XsdWildcard::isWildcard () const virtual
Returns always true, used to avoid dynamic casts.
Reimplemented from QPatternist::XsdTerm.
Definition at line 90 of file qxsdwildcard.cpp.
 {
     return true;
 }
namespaceConstraint()
XsdWildcard::NamespaceConstraint::Ptr XsdWildcard::namespaceConstraint () const
Returns the namespace constraint of the wildcard.
Definition at line 100 of file qxsdwildcard.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaDebugger::dumpWildcard(), isValidWildcardRestriction(), QPatternist::XsdSchemaHelper::isWildcardSubset(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), setNamespaceConstraint(), termMatches(), QPatternist::XsdValidatingInstanceReader::validate(), QPatternist::XsdSchemaHelper::wildcardAllowsExpandedName(), QPatternist::XsdSchemaHelper::wildcardIntersection(), and QPatternist::XsdSchemaHelper::wildcardUnion().
 {
     return m_namespaceConstraint;
 }
processContents()
XsdWildcard::ProcessContents XsdWildcard::processContents () const
Returns the process contents of the wildcard.
Definition at line 110 of file qxsdwildcard.cpp.
Referenced by QPatternist::XsdSchemaChecker::checkElementDuplicates(), QPatternist::XsdSchemaHelper::checkWildcardProcessContents(), QPatternist::XsdSchemaDebugger::dumpWildcard(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     return m_processContents;
 }
setNamespaceConstraint()
void XsdWildcard::setNamespaceConstraint (const NamespaceConstraint::Ptr & constraint)
Sets the namespace constraint of the wildcard.
See also
Namespace Constraint Definition
Definition at line 95 of file qxsdwildcard.cpp.
 {
     m_namespaceConstraint = namespaceConstraint;
 }
setProcessContents()
void XsdWildcard::setProcessContents (ProcessContents contents)
Sets the process contents of the wildcard.
See also
Process Contents Definition
Definition at line 105 of file qxsdwildcard.cpp.
Referenced by QPatternist::XsdValidatingInstanceReader::anyType(), QPatternist::XsdSchemaParser::parseAny(), QPatternist::XsdSchemaParser::parseAnyAttribute(), QPatternist::XsdSchemaResolver::resolveAttributeInheritance(), QPatternist::XsdSchemaResolver::resolveAttributeTermReferences(), QPatternist::XsdSchemaResolver::resolveComplexContentComplexTypes(), and QPatternist::XsdValidatingInstanceReader::validate().
 {
     m_processContents = contents;
 }
Properties
m_namespaceConstraint
NamespaceConstraint::Ptr QPatternist::XsdWildcard::m_namespaceConstraint private
Definition at line 190 of file qxsdwildcard_p.h.
Referenced by namespaceConstraint(), setNamespaceConstraint(), and XsdWildcard().
m_processContents
ProcessContents QPatternist::XsdWildcard::m_processContents private
Definition at line 191 of file qxsdwildcard_p.h.
Referenced by processContents(), and setProcessContents().
The documentation for this class was generated from the following files:
/src/xmlpatterns/schema/qxsdwildcard_p.h
/src/xmlpatterns/schema/qxsdwildcard.cpp