Qt 4.8: QScriptDebuggerConsole Class Reference
QScriptDebuggerConsole Class Reference
The QScriptDebuggerConsole class provides the core functionality of a debugger console.
#include <qscriptdebuggerconsole_p.h>
Public Functions
void bumpSessionId ()
void changeHistoryAt (int index, const QString &newHistory)
Reimplemented Function
QScriptDebuggerConsoleCommandManager * commandManager () const
QString commandPrefix () const
QScriptDebuggerConsoleCommandJob * consumeInput (const QString &input, QScriptMessageHandlerInterface *messageHandler, QScriptDebuggerCommandSchedulerInterface *commandScheduler)
Consumes the given line of input.
int currentFrameIndex () const
int currentLineNumber () const
qint64 currentScriptId () const
int evaluateAction () const
bool hasIncompleteInput () const
QString historyAt (int index) const
Reimplemented Function
int historyCount () const
Reimplemented Function
QString incompleteInput () const
void loadScriptedCommands (const QString &scriptsPath, QScriptMessageHandlerInterface *messageHandler)
QScriptDebuggerConsole ()
qint64 sessionId () const
void setCurrentFrameIndex (int index)
void setCurrentLineNumber (int lineNumber)
void setCurrentScriptId (qint64 id)
void setEvaluateAction (int action)
void setIncompleteInput (const QString &input)
void showDebuggerInfoMessage (QScriptMessageHandlerInterface *messageHandler)
~QScriptDebuggerConsole ()
Public Functions inherited from QScriptDebuggerConsoleHistorianInterface
virtual ~QScriptDebuggerConsoleHistorianInterface ()
Properties
QScopedPointer< QScriptDebuggerConsolePrivate > d_ptr
Detailed Description
The QScriptDebuggerConsole class provides the core functionality of a debugger console.
Since
4.5
Warning
This function is not part of the public interface.
Definition at line 70 of file qscriptdebuggerconsole_p.h.
Constructors and Destructors
QScriptDebuggerConsole()
QScriptDebuggerConsole::QScriptDebuggerConsole ()
Definition at line 417 of file qscriptdebuggerconsole.cpp.
     : d_ptr(new QScriptDebuggerConsolePrivate(this))
 {
 }
~QScriptDebuggerConsole()
QScriptDebuggerConsole::~QScriptDebuggerConsole ()
Definition at line 422 of file qscriptdebuggerconsole.cpp.
 {
 }
Functions
bumpSessionId()
void QScriptDebuggerConsole::bumpSessionId ()
Definition at line 563 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::startInteraction().
 {
     Q_D(QScriptDebuggerConsole);
     ++d->sessionId;
 }
changeHistoryAt()
void QScriptDebuggerConsole::changeHistoryAt (int index, const QString & newHistory) virtual
Reimplemented Function
Implements QScriptDebuggerConsoleHistorianInterface.
Definition at line 602 of file qscriptdebuggerconsole.cpp.
 {
     Q_D(QScriptDebuggerConsole);
     d->commandHistory[index] = newHistory;
 }
commandManager()
QScriptDebuggerConsoleCommandManager * QScriptDebuggerConsole::commandManager () const
Definition at line 433 of file qscriptdebuggerconsole.cpp.
 {
     Q_D(const QScriptDebuggerConsole);
     return d->commandManager;
 }
commandPrefix()
QString QScriptDebuggerConsole::commandPrefix () const
Definition at line 457 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::executeConsoleCommand().
 {
     Q_D(const QScriptDebuggerConsole);
     return d->commandPrefix;
 }
consumeInput()
QScriptDebuggerConsoleCommandJob * QScriptDebuggerConsole::consumeInput (const QString & input, QScriptMessageHandlerInterface * messageHandler, QScriptDebuggerCommandSchedulerInterface * commandScheduler)
Consumes the given line of input.
If the input starts with the command prefix, it is regarded as a debugger command; otherwise the input is evaluated as a plain script.
Definition at line 468 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::_q_onLineEntered(), and QScriptDebuggerPrivate::executeConsoleCommand().
 {
     Q_D(QScriptDebuggerConsole);
     static const int maximumHistoryCount = 100;
     QString cmd;
     if (d->input.isEmpty() && input.isEmpty()) {
         if (d->commandHistory.isEmpty())
             return 0;
         cmd = d->commandHistory.first();
     } else {
         cmd = input;
     }
     if (d->input.isEmpty() && cmd.startsWith(d->commandPrefix)) {
         if (!input.isEmpty()) {
             d->commandHistory.prepend(cmd);
             if (d->commandHistory.size() > maximumHistoryCount)
                 d->commandHistory.removeLast();
         }
         cmd.remove(0, d->commandPrefix.length());
         return d->createJob(cmd, messageHandler, commandScheduler);
     }
     d->input += cmd;
     d->input += QLatin1Char('\n');
     QScriptSyntaxCheckResult check = QScriptEngine::checkSyntax(d->input);
     if (check.state() == QScriptSyntaxCheckResult::Intermediate)
         return false;
     d->input.chop(1); // remove the last \n
     cmd = QString();
     cmd.append(d->commandPrefix);
     cmd.append(QString::fromLatin1("eval "));
     cmd.append(d->input);
     d->commandHistory.prepend(cmd);
     if (d->commandHistory.size() > maximumHistoryCount)
         d->commandHistory.removeLast();
     d->input.clear();
     cmd.remove(0, d->commandPrefix.length());
     return d->createJob(cmd, messageHandler, commandScheduler);
 }
currentFrameIndex()
int QScriptDebuggerConsole::currentFrameIndex () const
Definition at line 509 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::debuggerEvent(), QScriptCompletionTask::QScriptCompletionTask(), QScriptDebuggerPrivate::showToolTip(), and QScriptDebuggerPrivate::sync().
 {
     Q_D(const QScriptDebuggerConsole);
     return d->currentFrameIndex;
 }
currentLineNumber()
int QScriptDebuggerConsole::currentLineNumber () const
Definition at line 533 of file qscriptdebuggerconsole.cpp.
 {
     Q_D(const QScriptDebuggerConsole);
     return d->currentLineNumber;
 }
currentScriptId()
qint64 QScriptDebuggerConsole::currentScriptId () const
Definition at line 521 of file qscriptdebuggerconsole.cpp.
 {
     Q_D(const QScriptDebuggerConsole);
     return d->currentScriptId;
 }
evaluateAction()
int QScriptDebuggerConsole::evaluateAction () const
Definition at line 545 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::debuggerEvent().
 {
     Q_D(const QScriptDebuggerConsole);
     return d->evaluateAction;
 }
hasIncompleteInput()
bool QScriptDebuggerConsole::hasIncompleteInput () const
Definition at line 439 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::_q_onLineEntered().
 {
     Q_D(const QScriptDebuggerConsole);
     return !d->input.isEmpty();
 }
historyAt()
QString QScriptDebuggerConsole::historyAt (int index) const virtual
Reimplemented Function
Implements QScriptDebuggerConsoleHistorianInterface.
Definition at line 593 of file qscriptdebuggerconsole.cpp.
 {
     Q_D(const QScriptDebuggerConsole);
     return d->commandHistory.value(index);
 }
historyCount()
int QScriptDebuggerConsole::historyCount () const virtual
Reimplemented Function
Implements QScriptDebuggerConsoleHistorianInterface.
Definition at line 584 of file qscriptdebuggerconsole.cpp.
 {
     Q_D(const QScriptDebuggerConsole);
     return d->commandHistory.size();
 }
incompleteInput()
QString QScriptDebuggerConsole::incompleteInput () const
Definition at line 445 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::executeConsoleCommand().
 {
     Q_D(const QScriptDebuggerConsole);
     return d->input;
 }
loadScriptedCommands()
void QScriptDebuggerConsole::loadScriptedCommands (const QString & scriptsPath, QScriptMessageHandlerInterface * messageHandler)
Definition at line 426 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::QScriptDebuggerPrivate().
 {
     Q_D(QScriptDebuggerConsole);
     d->loadScriptedCommands(scriptsPath, messageHandler);
 }
sessionId()
qint64 QScriptDebuggerConsole::sessionId () const
Definition at line 557 of file qscriptdebuggerconsole.cpp.
 {
     Q_D(const QScriptDebuggerConsole);
     return d->sessionId;
 }
setCurrentFrameIndex()
void QScriptDebuggerConsole::setCurrentFrameIndex (int index)
Definition at line 515 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::startInteraction().
 {
     Q_D(QScriptDebuggerConsole);
     d->currentFrameIndex = index;
 }
setCurrentLineNumber()
void QScriptDebuggerConsole::setCurrentLineNumber (int lineNumber)
Definition at line 539 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::startInteraction().
 {
     Q_D(QScriptDebuggerConsole);
     d->currentLineNumber = lineNumber;
 }
setCurrentScriptId()
void QScriptDebuggerConsole::setCurrentScriptId (qint64 id)
Definition at line 527 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::startInteraction().
 {
     Q_D(QScriptDebuggerConsole);
     d->currentScriptId = id;
 }
setEvaluateAction()
void QScriptDebuggerConsole::setEvaluateAction (int action)
Definition at line 551 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::debuggerEvent().
 {
     Q_D(QScriptDebuggerConsole);
     d->evaluateAction = action;
 }
setIncompleteInput()
void QScriptDebuggerConsole::setIncompleteInput (const QString & input)
Definition at line 451 of file qscriptdebuggerconsole.cpp.
Referenced by QScriptDebuggerPrivate::executeConsoleCommand().
 {
     Q_D(QScriptDebuggerConsole);
     d->input = input;
 }
showDebuggerInfoMessage()
void QScriptDebuggerConsole::showDebuggerInfoMessage (QScriptMessageHandlerInterface * messageHandler)
Definition at line 569 of file qscriptdebuggerconsole.cpp.
 {
     messageHandler->message(
         QtDebugMsg,
         QString::fromLatin1(
             "Welcome to the Qt Script debugger.\n"
             "Debugger commands start with a . (period).\n"
             "Any other input will be evaluated by the script interpreter.\n"
             "Type \".help\" for help.\n"));
 }
Properties
d_ptr
QScopedPointer<QScriptDebuggerConsolePrivate> QScriptDebuggerConsole::d_ptr private
Definition at line 113 of file qscriptdebuggerconsole_p.h.
The documentation for this class was generated from the following files:
/src/scripttools/debugging/qscriptdebuggerconsole_p.h
/src/scripttools/debugging/qscriptdebuggerconsole.cpp