Qt 4.8: QThread Class Reference
QThread Class Reference
The QThread class provides a platform-independent way to manage threads.
#include <qthread.h>
Public Types
enum Priority {
IdlePriority, LowestPriority, LowPriority, NormalPriority,
HighPriority, HighestPriority, TimeCriticalPriority, InheritPriority
}
This enum type indicates how the operating system should schedule newly created threads.
Public Slots
void quit ()
Tells the thread's event loop to exit with return code 0 (success).
void start (Priority=InheritPriority)
Begins execution of the thread by calling run().
void terminate ()
Terminates the execution of the thread.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void finished ()
This signal is emitted when the thread has finished executing.
void started ()
This signal is emitted when the thread starts executing.
void terminated ()
This signal is emitted when the thread is terminated.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void exit (int retcode=0)
Tells the thread's event loop to exit with a return code.
bool isFinished () const
Returns true if the thread is finished; otherwise returns false.
bool isRunning () const
Returns true if the thread is running; otherwise returns false.
Priority priority () const
Returns the priority for a running thread.
QThread (QObject *parent=0)
Constructs a new QThread to manage a new thread.
void setPriority (Priority priority)
This function sets the priority for a running thread.
void setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
uint stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
bool wait (unsigned long time=ULONG_MAX)
Blocks the thread until either of these conditions is met:
~QThread ()
Destroys the QThread.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QThread * currentThread ()
Returns a pointer to a QThread which manages the currently executing thread.
static Qt::HANDLE currentThreadId ()
Returns the thread handle of the currently executing thread.
static int idealThreadCount ()
Returns the ideal number of threads that can be run on the system.
static void yieldCurrentThread ()
Yields execution of the current thread to another runnable thread, if any.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
int exec ()
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
QThread (QThreadPrivate &dd, QObject *parent=0)
virtual void run ()
The starting point for the thread.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Static Protected Functions
static void msleep (unsigned long)
Forces the current thread to sleep for msecs milliseconds.
static void setTerminationEnabled (bool enabled=true)
Enables or disables termination of the current thread based on the enabled parameter.
static void sleep (unsigned long)
Forces the current thread to sleep for secs seconds.
static void usleep (unsigned long)
Forces the current thread to sleep for usecs microseconds.
Static Private Functions
static void cleanup ()
Cleans up the QThread system.
static void initialize ()
Friends
class QCoreApplication
class QThreadData
Additional Inherited Members
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QThread class provides a platform-independent way to manage threads.
A QThread object manages one thread of control within the program. QThreads begin executing in run(). By default, run() starts the event loop by calling exec() and runs a Qt event loop inside the thread.
You can use worker objects by moving them to the thread using QObject::moveToThread().
class Worker : public QObject
{
    Q_OBJECT
    QThread workerThread;
public slots:
    void doWork(const QString &parameter) {
        // ...
        emit resultReady(result);
    }
signals:
    void resultReady(const QString &result);
};
class Controller : public QObject
{
    Q_OBJECT
    QThread workerThread;
public:
    Controller() {
        Worker *worker = new Worker;
        worker->moveToThread(&workerThread);
        connect(workerThread, SIGNAL(finished()), worker, SLOT(deleteLater()));
        connect(this, SIGNAL(operate(QString)), worker, SLOT(doWork(QString)));
        connect(worker, SIGNAL(resultReady(QString)), this, SLOT(handleResults(QString)));
        workerThread.start();
    }
    ~Controller() {
        workerThread.quit();
        workerThread.wait();
    }
public slots:
    void handleResults(const QString &);
signals:
    void operate(const QString &);
};
The code inside the Worker's slot would then execute in a separate thread. However, you are free to connect the Worker's slots to any signal, from any object, in any thread. It is safe to connect signals and slots across different threads, thanks to a mechanism called queued connections.
Another way to make code run in a separate thread, is to subclass QThread and reimplement run(). For example:
class WorkerThread : public QThread
{
    Q_OBJECT
    void run() {
        QString result;
        /* expensive or blocking operation  */
        emit resultReady(result);
    }
signals:
    void resultReady(const QString &s);
};
void MyObject::startWorkInAThread()
{
    WorkerThread *workerThread = new WorkerThread(this);
    connect(workerThread, SIGNAL(resultReady(QString)), this, SLOT(handleResults(QString)));
    connect(workerThread, SIGNAL(finished()), workerThread, SLOT(deleteLater()));
    workerThread->start();
}
In that example, the thread will exit after the run function has returned. There will not be any event loop running in the thread unless you call exec().
It is important to remember that a QThread instance lives in the old thread that instantiated it, not in the new thread that calls run(). This means that all of QThread's queued slots will execute in the old thread. Thus, a developer who wishes to invoke slots in the new thread must use the worker-object approach; new slots should not be implemented directly into a subclassed QThread.
When subclassing QThread, keep in mind that the constructor executes in the old thread while run() executes in the new thread. If a member variable is accessed from both functions, then the variable is accessed from two different threads. Check that it is safe to do so.
Note
Care must be taken when interacting with objects across different threads. See Synchronizing Threads for details.
Managing threads
QThread will notifiy you via a signal when the thread is started(), finished(), and terminated(), or you can use isFinished() and isRunning() to query the state of the thread.
You can stop the thread by calling exit() or quit(). In extreme cases, you may want to forcibly terminate() an executing thread. However, doing so is dangerous and discouraged. Please read the documentation for terminate() and setTerminationEnabled() for detailed information.
From Qt 4.8 onwards, it is possible to deallocate objects that live in a thread that has just ended, by connecting the finished() signal to QObject::deleteLater().
Use wait() to block the calling thread, until the other thread has finished execution (or until a specified time has passed).
The static functions currentThreadId() and currentThread() return identifiers for the currently executing thread. The former returns a platform specific ID for the thread; the latter returns a QThread pointer.
To choose the name that your thread will be given (as identified by the command ps -L on Linux, for example), you can call setObjectName() before starting the thread. If you don't call setObjectName(), the name given to your thread will be the class name of the runtime type of your thread object (for example, "RenderThread" in the case of the Mandelbrot Example, as that is the name of the QThread subclass). Note that this is currently not available with release builds on Windows.
QThread also provides static, platform independent sleep functions: sleep(), msleep(), and usleep() allow full second, millisecond, and microsecond resolution respectively.
Note
wait() and the sleep() functions should be unnecessary in general, since Qt is an event-driven framework. Instead of wait(), consider listening for the finished() signal. Instead of the sleep() functions, consider using QTimer.
See also
{Thread Support in Qt}, QThreadStorage, {Synchronizing Threads} {Mandelbrot Example}, {Semaphores Example}, {Wait Conditions Example}
Definition at line 59 of file qthread.h.
Enumerations
Priority
enum QThread::Priority
This enum type indicates how the operating system should schedule newly created threads.
IdlePriority scheduled only when no other threads are running.
LowestPriority scheduled less often than LowPriority.
LowPriority scheduled less often than NormalPriority.
NormalPriority the default priority of the operating system.
HighPriority scheduled more often than NormalPriority.
HighestPriority scheduled more often than HighPriority.
TimeCriticalPriority scheduled as often as possible.
InheritPriority use the same priority as the creating thread. This is the default.
Enumerator
IdlePriority
LowestPriority
LowPriority
NormalPriority
HighPriority
HighestPriority
TimeCriticalPriority
InheritPriority
Definition at line 70 of file qthread.h.
                   {
         IdlePriority,
         LowestPriority,
         LowPriority,
         NormalPriority,
         HighPriority,
         HighestPriority,
         TimeCriticalPriority,
         InheritPriority
     };
Constructors and Destructors
QThread() [1/2]
QThread::QThread (QObject * parent = 0) explicit
Constructs a new QThread to manage a new thread.
The parent takes ownership of the QThread. The thread does not begin executing until start() is called.
See also
start()
Definition at line 433 of file qthread.cpp.
Referenced by priority().
     : QObject(*(new QThreadPrivate), parent)
 {
     Q_D(QThread);
     // fprintf(stderr, "QThreadData %p created for thread %p\n", d->data, this);
     d->data->thread = this;
 }
~QThread()
QThread::~QThread ()
Destroys the QThread.
Note that deleting a QThread object will not stop the execution of the thread it manages. Deleting a running QThread (i.e. isFinished() returns false) will probably result in a program crash. Wait for the finished() signal before deleting the QThread.
Definition at line 460 of file qthread.cpp.
 {
     Q_D(QThread);
     {
         QMutexLocker locker(&d->mutex);
         if (d->isInFinish) {
             locker.unlock();
             wait();
             locker.relock();
         }
         if (d->running && !d->finished && !d->data->isAdopted)
             qWarning("QThread: Destroyed while thread is still running");
         d->data->thread = 0;
     }
 }
QThread() [2/2]
QThread::QThread (QThreadPrivate & dd, QObject * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 443 of file qthread.cpp.
     : QObject(dd, parent)
 {
     Q_D(QThread);
     // fprintf(stderr, "QThreadData %p taken from private data for thread %p\n", d->data, this);
     d->data->thread = this;
 }
Functions
cleanup()
void QThread::cleanup () static private
Cleans up the QThread system.
Warning
This function is not part of the public interface.
Definition at line 661 of file qthread.cpp.
Referenced by QCoreApplication::~QCoreApplication().
 {
     qt_global_mutexpool = 0;
 }
currentThread()
QThread * QThread::currentThread () static
Returns a pointer to a QThread which manages the currently executing thread.
Definition at line 419 of file qthread.cpp.
Referenced by QDBusConnectionPrivate::activateCall(), QEventDispatcherUNIX::activateTimers(), QTextHtmlParserNode::applyBackgroundImage(), QDBusAbstractInterface::callWithArgumentList(), QCoreApplicationPrivate::checkReceiverThread(), connManager(), QDBusConnectionPrivate::deleteYourself(), QDBusConnectionPrivate::deliverCall(), QNetworkSession::disconnectNotify(), QTextImageHandler::drawObject(), elapsed(), QThreadStorageData::finish(), QDBusConnectionPrivate::handleObjectCall(), QEventDispatcherQPAPrivate::hasIntegration(), huntAndEmit(), QGLSignalProxy::instance(), QTextImageHandler::intrinsicSize(), QMetaMethod::invoke(), QRawFontPrivate::isValid(), jump(), QRawFont::loadFromData(), QTextDocument::loadResource(), QFontDatabase::loadXlfd(), QHostInfo::lookupHost(), QBBScreen::newWindowCreated(), QApplication::notify(), operator<<(), priority(), QStateMachinePrivate::processEvents(), QCoreApplicationPrivate::QCoreApplicationPrivate(), qDBusAddTimeout(), qDBusAddWatch(), qDBusIntrospectObject(), qDBusPropertyGet(), qDBusPropertyGetAll(), qDBusPropertySet(), qDBusRemoveTimeout(), qDBusRemoveWatch(), qDBusToggleWatch(), QEventDispatcherGlibPrivate::QEventDispatcherGlibPrivate(), QFontEngineX11FT::QFontEngineX11FT(), QGLEngineSharedShaders::QGLEngineSharedShaders(), qt_grab_cursor(), qt_painter_thread_test(), qt_pixmap_thread_test(), qt_set_current_thread_to_main_thread(), qt_win_display_dc(), QEventDispatcherWin32::registerEventNotifier(), QEventDispatcherGlib::registerSocketNotifier(), QEventDispatcherWin32::registerSocketNotifier(), QEventDispatcherMac::registerSocketNotifier(), QEventDispatcherUNIX::registerSocketNotifier(), QEventDispatcherGlib::registerTimer(), QEventDispatcherWin32::registerTimer(), QEventDispatcherMac::registerTimer(), QEventDispatcherUNIX::registerTimer(), QDBusAdaptorConnector::relaySlot(), QSocks5BindStore::retrieve(), QEventDispatcherQPAPrivate::runEventLoopIntegration(), QPlatformGLContextPrivate::setCurrentContext(), QEventDispatcherUNIX::setSocketNotifierPending(), QMacPrintEnginePrivate::shouldSuppressStatus(), QEventDispatcherWin32::unregisterEventNotifier(), QEventDispatcherGlib::unregisterSocketNotifier(), QEventDispatcherWin32::unregisterSocketNotifier(), QEventDispatcherMac::unregisterSocketNotifier(), QEventDispatcherUNIX::unregisterSocketNotifier(), QEventDispatcherGlib::unregisterTimer(), QEventDispatcherWin32::unregisterTimer(), QEventDispatcherMac::unregisterTimer(), QEventDispatcherUNIX::unregisterTimer(), QEventDispatcherGlib::unregisterTimers(), QEventDispatcherWin32::unregisterTimers(), QEventDispatcherMac::unregisterTimers(), QEventDispatcherUNIX::unregisterTimers(), QBBScreen::windowClosed(), QDBusConnectionPrivate::~QDBusConnectionPrivate(), and QGLEngineSharedShaders::~QGLEngineSharedShaders().
 {
     QThreadData *data = QThreadData::current();
     Q_ASSERT(data != 0);
     return data->thread;
 }
currentThreadId()
Qt::HANDLE QThread::currentThreadId () static
Returns the thread handle of the currently executing thread.
Warning
The handle returned by this function is used for internal purposes and should not be used in any application code.
On Windows, the returned value is a pseudo-handle for the current thread. It can't be used for numerical comparison. i.e., this function returns the DWORD (Windows-Thread ID) returned by the Win32 function getCurrentThreadId(), not the HANDLE (Windows-Thread HANDLE) returned by the Win32 function getCurrentThread().
Definition at line 400 of file qthread_unix.cpp.
Referenced by QHttpThreadDelegate::abortRequest(), QMetaObject::activate(), QGLContext::choosePixelFormat(), QThreadPrivate::finish(), QHttpThreadDelegate::finishedSlot(), QHttpThreadDelegate::finishedWithErrorSlot(), QHttpThreadDelegate::headerChangedSlot(), id_function(), QMutex::lock(), QReadWriteLock::lockForRead(), QReadWriteLock::lockForWrite(), QCoreApplicationPrivate::QCoreApplicationPrivate(), QEventDispatcherUNIXPrivate::QEventDispatcherUNIXPrivate(), QHttpThreadDelegate::startRequest(), QHttpThreadDelegate::startRequestSynchronously(), QHttpThreadDelegate::synchronousAuthenticationRequiredSlot(), QHttpThreadDelegate::synchronousFinishedSlot(), QHttpThreadDelegate::synchronousFinishedWithErrorSlot(), QHttpThreadDelegate::synchronousHeaderChangedSlot(), QHttpThreadDelegate::synchronousProxyAuthenticationRequiredSlot(), QMutex::tryLock(), QReadWriteLock::tryLockForRead(), QReadWriteLock::tryLockForWrite(), and QReadWriteLock::unlock().
 {
     // requires a C cast here otherwise we run into trouble on AIX
     return (Qt::HANDLE)pthread_self();
 }
exec()
int QThread::exec () protected
Enters the event loop and waits until exit() is called, returning the value that was passed to exit().
The value returned is 0 if exit() is called via quit().
This function is meant to be called from within run(). It is necessary to call this function to start event handling.
See also
quit(), exit()
Definition at line 551 of file qthread.cpp.
Referenced by QDeclarativeXmlQueryEngine::run().
 {
     Q_D(QThread);
     QMutexLocker locker(&d->mutex);
     d->data->quitNow = false;
     if (d->exited) {
         d->exited = false;
         return d->returnCode;
     }
     locker.unlock();
     QEventLoop eventLoop;
     int returnCode = eventLoop.exec();
     locker.relock();
     d->exited = false;
     d->returnCode = -1;
     return returnCode;
 }
exit()
void QThread::exit (int returnCode = 0)
Tells the thread's event loop to exit with a return code.
After calling this function, the thread leaves the event loop and returns from the call to QEventLoop::exec(). The QEventLoop::exec() function returns returnCode.
By convention, a returnCode of 0 means success, any non-zero value indicates an error.
Note that unlike the C library function of the same name, this function does return to the caller – it is event processing that stops.
No QEventLoops will be started anymore in this thread until QThread::exec() has been called again. If the eventloop in QThread::exec() is not running then the next call to QThread::exec() will also return immediately.
See also
quit() QEventLoop
Definition at line 592 of file qthread.cpp.
Referenced by quit(), QIntMouseListenThread::run(), and QIntKeyboardListenThread::run().
 {
     Q_D(QThread);
     QMutexLocker locker(&d->mutex);
     d->exited = true;
     d->returnCode = returnCode;
     d->data->quitNow = true;
     for (int i = 0; i < d->data->eventLoops.size(); ++i) {
         QEventLoop *eventLoop = d->data->eventLoops.at(i);
         eventLoop->exit(returnCode);
     }
 }
finished
bool QThread::finished () signal
This signal is emitted when the thread has finished executing.
Use isFinished() instead.
See also
started(), terminated()
Referenced by QThreadData::current(), QThreadPrivate::finish(), and QAdoptedThread::QAdoptedThread().
idealThreadCount()
int QThread::idealThreadCount () static
Returns the ideal number of threads that can be run on the system.
This is done querying the number of processor cores, both real and logical, in the system. This function returns -1 if the number of processor cores could not be detected.
Definition at line 411 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish(), and QMutex::lockInternal().
 {
     int cores = -1;
 #if defined(Q_OS_MAC) && !defined(Q_WS_QPA)
     // Mac OS X
     cores = MPProcessorsScheduled();
 #elif defined(Q_OS_HPUX)
     // HP-UX
     struct pst_dynamic psd;
     if (pstat_getdynamic(&psd, sizeof(psd), 1, 0) == -1) {
         perror("pstat_getdynamic");
         cores = -1;
     } else {
         cores = (int)psd.psd_proc_cnt;
     }
 #elif defined(Q_OS_BSD4)
     // FreeBSD, OpenBSD, NetBSD, BSD/OS
     size_t len = sizeof(cores);
     int mib[2];
     mib[0] = CTL_HW;
     mib[1] = HW_NCPU;
     if (sysctl(mib, 2, &cores, &len, NULL, 0) != 0) {
         perror("sysctl");
         cores = -1;
     }
 #elif defined(Q_OS_IRIX)
     // IRIX
     cores = (int)sysconf(_SC_NPROC_ONLN);
 #elif defined(Q_OS_INTEGRITY)
 #if (__INTEGRITY_MAJOR_VERSION >= 10)
     // Integrity V10+ does support multicore CPUs
     Value processorCount;
     if (GetProcessorCount(CurrentTask(), &processorCount) == 0)
         cores = processorCount;
     else
 #endif
     cores = 1;
 #elif defined(Q_OS_VXWORKS)
     // VxWorks
 #  if defined(QT_VXWORKS_HAS_CPUSET)
     cpuset_t cpus = vxCpuEnabledGet();
     cores = 0;
     // 128 cores should be enough for everyone ;)
     for (int i = 0; i < 128 && !CPUSET_ISZERO(cpus); ++i) {
         if (CPUSET_ISSET(cpus, i)) {
             CPUSET_CLR(cpus, i);
             cores++;
         }
     }
 #  else
     // as of aug 2008 VxWorks < 6.6 only supports one single core CPU
     cores = 1;
 #  endif
 #else
     // the rest: Linux, Solaris, AIX, Tru64
     cores = (int)sysconf(_SC_NPROCESSORS_ONLN);
 #endif
     return cores;
 }
initialize()
void QThread::initialize () static private
Definition at line 643 of file qthread.cpp.
Referenced by QCoreApplication::init().
 {
     if (qt_global_mutexpool)
         return;
     qt_global_mutexpool = QMutexPool::instance();
 #if defined (Q_OS_WIN)
     qt_create_tls();
 #endif
 }
isFinished()
bool QThread::isFinished () const
Returns true if the thread is finished; otherwise returns false.
See also
isRunning()
Definition at line 482 of file qthread.cpp.
 {
     Q_D(const QThread);
     QMutexLocker locker(&d->mutex);
     return d->finished || d->isInFinish;
 }
isRunning()
bool QThread::isRunning () const
Returns true if the thread is running; otherwise returns false.
See also
isFinished()
Definition at line 494 of file qthread.cpp.
Referenced by QKqueueFileSystemWatcherEngine::addPaths(), QWindowsPipeWriter::write(), and QDnotifySignalThread::~QDnotifySignalThread().
 {
     Q_D(const QThread);
     QMutexLocker locker(&d->mutex);
 #ifdef Q_OS_SYMBIAN
     // app shutdown on Symbian can terminate threads and invalidate their stacks without notification,
     // check the thread is still alive.
     if (d->data->symbian_thread_handle.Handle() && d->data->symbian_thread_handle.ExitType() != EExitPending)
         return false;
 #endif
     return d->running && !d->isInFinish;
 }
msleep()
void QThread::msleep (unsigned long msecs) static protected
Forces the current thread to sleep for msecs milliseconds.
See also
sleep(), usleep()
Definition at line 509 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish(), and QWindowsPipeWriter::run().
 {
     struct timeval tv;
     gettimeofday(&tv, 0);
     struct timespec ti;
     ti.tv_nsec = (tv.tv_usec + (msecs % 1000) * 1000) * 1000;
     ti.tv_sec = tv.tv_sec + (msecs / 1000) + (ti.tv_nsec / 1000000000);
     ti.tv_nsec %= 1000000000;
     thread_sleep(&ti);
 }
priority()
QThread::Priority QThread::priority () const
Returns the priority for a running thread.
Since
4.1
If the thread is not running, this function returns InheritPriority.
See also
Priority setPriority() start()
Definition at line 718 of file qthread.cpp.
Referenced by QThreadPrivate::start().
 {
     Q_D(const QThread);
     QMutexLocker locker(&d->mutex);
     // mask off the high bits that are used for flags
     return Priority(d->priority & 0xffff);
 }
quit
void QThread::quit () slot
Tells the thread's event loop to exit with return code 0 (success).
Equivalent to calling QThread::exit(0).
This function does nothing if the thread does not have an event loop.
See also
exit() QEventLoop
Definition at line 614 of file qthread.cpp.
Referenced by QNetworkAccessHttpBackend::postRequest(), QDeclarativePixmapReader::QDeclarativePixmapReader(), QDeclarativeWorkerScriptEngine::QDeclarativeWorkerScriptEngine(), QDeclarativeXmlQueryEngine::QDeclarativeXmlQueryEngine(), QDnotifySignalThread::readFromDnotify(), QInotifyFileSystemWatcherEngine::stop(), QPollingFileSystemWatcherEngine::stop(), QDnotifySignalThread::~QDnotifySignalThread(), and QNetworkConfigurationManagerPrivate::~QNetworkConfigurationManagerPrivate().
 { exit(); }
run()
void QThread::run (void) protected virtual
The starting point for the thread.
After calling start(), the newly created thread calls this function. The default implementation simply calls exec().
You can reimplement this function to facilitate advanced thread management. Returning from this method will end the execution of the thread.
See also
start() wait()
Reimplemented in QAdoptedThread, QNlaThread, QDeclarativeXmlQueryEngine, QProcessManager, QFileInfoGatherer, QIntKeyboardListenThread, QDeclarativePixmapReader, QWindowsFileSystemWatcherEngineThread, QWindowsPipeWriter, QScanThread, QPollingFileSystemWatcherEngine, QFSEventsFileSystemWatcherEngine, SelectWorker, QDnotifySignalThread, QIntMouseListenThread, QKqueueFileSystemWatcherEngine, QDeclarativeWorkerScriptEngine, QDnotifyFileSystemWatcherEngine, QInotifyFileSystemWatcherEngine, QThreadPoolThread, QDirectFbInput, and QBBScreenEventThread.
Definition at line 628 of file qthread.cpp.
Referenced by qt_adopted_thread_watcher_function(), and QThreadPrivate::start().
 {
     (void) exec();
 }
setPriority()
void QThread::setPriority (Priority priority)
This function sets the priority for a running thread.
Since
4.1
If the thread is not running, this function does nothing and returns immediately. Use start() to start a thread with a specific priority.
The priority argument can be any value in the QThread::Priority enum except for InheritPriorty.
The effect of the priority parameter is dependent on the operating system's scheduling policy. In particular, the priority will be ignored on systems that do not support thread priorities (such as on Linux, see http://linux.die.net/man/2/sched_setscheduler for more details).
See also
Priority priority() start()
Definition at line 738 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish(), and QThreadPrivate::start().
 {
     Q_D(QThread);
     QMutexLocker locker(&d->mutex);
     if (!d->running) {
         qWarning("QThread::setPriority: Cannot set priority, thread is not running");
         return;
     }
     d->priority = priority;
     // copied from start() with a few modifications:
 #ifdef QT_HAS_THREAD_PRIORITY_SCHEDULING
     int sched_policy;
     sched_param param;
     if (pthread_getschedparam(d->thread_id, &sched_policy, &param) != 0) {
         // failed to get the scheduling policy, don't bother setting
         // the priority
         qWarning("QThread::setPriority: Cannot get scheduler parameters");
         return;
     }
     int prio;
     if (!calculateUnixPriority(priority, &sched_policy, &prio)) {
         // failed to get the scheduling parameters, don't
         // bother setting the priority
         qWarning("QThread::setPriority: Cannot determine scheduler priority range");
         return;
     }
     param.sched_priority = prio;
     int status = pthread_setschedparam(d->thread_id, sched_policy, &param);
 # ifdef SCHED_IDLE
     // were we trying to set to idle priority and failed?
     if (status == -1 && sched_policy == SCHED_IDLE && errno == EINVAL) {
         // reset to lowest priority possible
         pthread_getschedparam(d->thread_id, &sched_policy, &param);
         param.sched_priority = sched_get_priority_min(sched_policy);
         pthread_setschedparam(d->thread_id, sched_policy, &param);
     }
 # else
     Q_UNUSED(status);
 # endif // SCHED_IDLE
 #endif
 }
setStackSize()
void QThread::setStackSize (uint stackSize)
Sets the maximum stack size for the thread to stackSize.
If stackSize is greater than zero, the maximum stack size is set to stackSize bytes, otherwise the maximum stack size is automatically determined by the operating system.
Warning
Most operating systems place minimum and maximum limits on thread stack sizes. The thread will fail to start if the stack size is outside these limits.
See also
stackSize()
Definition at line 519 of file qthread.cpp.
 {
     Q_D(QThread);
     QMutexLocker locker(&d->mutex);
     Q_ASSERT_X(!d->running, "QThread::setStackSize",
                "cannot change stack size while the thread is running");
     d->stackSize = stackSize;
 }
setTerminationEnabled()
void QThread::setTerminationEnabled (bool enabled = true) static protected
Enables or disables termination of the current thread based on the enabled parameter.
The thread must have been started by QThread.
When enabled is false, termination is disabled. Future calls to QThread::terminate() will return immediately without effect. Instead, the termination is deferred until termination is enabled.
When enabled is true, termination is enabled. Future calls to QThread::terminate() will terminate the thread normally. If termination has been deferred (i.e. QThread::terminate() was called with termination disabled), this function will terminate the calling thread immediately. Note that this function will not return in this case.
See also
terminate()
Definition at line 726 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish(), and qt_adopted_thread_watcher_function().
 {
     QThread *thr = currentThread();
     Q_ASSERT_X(thr != 0, "QThread::setTerminationEnabled()",
                "Current thread was not started with QThread.");
     Q_UNUSED(thr)
     pthread_setcancelstate(enabled ? PTHREAD_CANCEL_ENABLE : PTHREAD_CANCEL_DISABLE, NULL);
     if (enabled)
         pthread_testcancel();
 }
sleep()
void QThread::sleep (unsigned long secs) static protected
Forces the current thread to sleep for secs seconds.
See also
msleep(), usleep()
Definition at line 499 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish().
 {
     struct timeval tv;
     gettimeofday(&tv, 0);
     struct timespec ti;
     ti.tv_sec = tv.tv_sec + secs;
     ti.tv_nsec = (tv.tv_usec * 1000);
     thread_sleep(&ti);
 }
stackSize()
uint QThread::stackSize () const
Returns the maximum stack size for the thread (if set with setStackSize()); otherwise returns zero.
See also
setStackSize()
Definition at line 534 of file qthread.cpp.
Referenced by setStackSize().
 {
     Q_D(const QThread);
     QMutexLocker locker(&d->mutex);
     return d->stackSize;
 }
start
void QThread::start (Priority priority = InheritPriority) slot
Begins execution of the thread by calling run().
The operating system will schedule the thread according to the priority parameter. If the thread is already running, this function does nothing.
The effect of the priority parameter is dependent on the operating system's scheduling policy. In particular, the priority will be ignored on systems that do not support thread priorities (such as on Linux, see http://linux.die.net/man/2/sched_setscheduler for more details).
See also
run(), terminate()
Definition at line 583 of file qthread_unix.cpp.
Referenced by QInotifyFileSystemWatcherEngine::addPaths(), QKqueueFileSystemWatcherEngine::addPaths(), QWindowsFileSystemWatcherEngine::addPaths(), QPollingFileSystemWatcherEngine::addPaths(), QCoreWlanEngine::doRequestUpdate(), QThreadPrivate::finish(), QEventDispatcherQPAPrivate::hasIntegration(), QNetworkConfigurationManagerPrivate::initialize(), QDirectFbIntegration::initializeInput(), QProcessPrivate::pipeWriterBytesToWrite(), QNetworkAccessHttpBackend::postRequest(), QBBIntegration::QBBIntegration(), QDeclarativePixmapReader::QDeclarativePixmapReader(), QDeclarativeWorkerScriptEngine::QDeclarativeWorkerScriptEngine(), QDeclarativeXmlQueryEngine::QDeclarativeXmlQueryEngine(), QFileInfoGatherer::QFileInfoGatherer(), QIntMouseHandler::QIntMouseHandler(), QNlaEngine::QNlaEngine(), QWSIntKbPrivate::QWSIntKbPrivate(), QProcessPrivate::startDetached(), QDnotifySignalThread::startNotify(), QProcessPrivate::startProcess(), QThreadPoolPrivate::startThread(), QThreadPoolPrivate::tryStart(), and QFSEventsFileSystemWatcherEngine::warmUpFSEvents().
 {
     Q_D(QThread);
     QMutexLocker locker(&d->mutex);
     if (d->isInFinish)
         d->thread_done.wait(locker.mutex());
     if (d->running)
         return;
     d->running = true;
     d->finished = false;
     d->terminated = false;
     d->returnCode = 0;
     d->exited = false;
     pthread_attr_t attr;
     pthread_attr_init(&attr);
     pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
     d->priority = priority;
 #if defined(QT_HAS_THREAD_PRIORITY_SCHEDULING)
     switch (priority) {
     case InheritPriority:
         {
             pthread_attr_setinheritsched(&attr, PTHREAD_INHERIT_SCHED);
             break;
         }
     default:
         {
             int sched_policy;
             if (pthread_attr_getschedpolicy(&attr, &sched_policy) != 0) {
                 // failed to get the scheduling policy, don't bother
                 // setting the priority
                 qWarning("QThread::start: Cannot determine default scheduler policy");
                 break;
             }
             int prio;
             if (!calculateUnixPriority(priority, &sched_policy, &prio)) {
                 // failed to get the scheduling parameters, don't
                 // bother setting the priority
                 qWarning("QThread::start: Cannot determine scheduler priority range");
                 break;
             }
             sched_param sp;
             sp.sched_priority = prio;
             if (pthread_attr_setinheritsched(&attr, PTHREAD_EXPLICIT_SCHED) != 0
                 || pthread_attr_setschedpolicy(&attr, sched_policy) != 0
                 || pthread_attr_setschedparam(&attr, &sp) != 0) {
                 // could not set scheduling hints, fallback to inheriting them
                 // we'll try again from inside the thread
                 pthread_attr_setinheritsched(&attr, PTHREAD_INHERIT_SCHED);
                 d->priority = Priority(priority | ThreadPriorityResetFlag);
             }
             break;
         }
     }
 #endif // QT_HAS_THREAD_PRIORITY_SCHEDULING
     if (d->stackSize > 0) {
 #if defined(_POSIX_THREAD_ATTR_STACKSIZE) && (_POSIX_THREAD_ATTR_STACKSIZE-0 > 0)
         int code = pthread_attr_setstacksize(&attr, d->stackSize);
 #else
         int code = ENOSYS; // stack size not supported, automatically fail
 #endif // _POSIX_THREAD_ATTR_STACKSIZE
         if (code) {
             qWarning("QThread::start: Thread stack size error: %s",
                      qPrintable(qt_error_string(code)));
             // we failed to set the stacksize, and as the documentation states,
             // the thread will fail to run...
             d->running = false;
             d->finished = false;
             return;
         }
     }
     int code =
         pthread_create(&d->thread_id, &attr, QThreadPrivate::start, this);
     if (code == EPERM) {
         // caller does not have permission to set the scheduling
         // parameters/policy
         pthread_attr_setinheritsched(&attr, PTHREAD_INHERIT_SCHED);
         code =
             pthread_create(&d->thread_id, &attr, QThreadPrivate::start, this);
     }
     pthread_attr_destroy(&attr);
     if (code) {
         qWarning("QThread::start: Thread creation error: %s", qPrintable(qt_error_string(code)));
         d->running = false;
         d->finished = false;
         d->thread_id = 0;
     }
 }
started
void QThread::started () signal
This signal is emitted when the thread starts executing.
See also
finished(), terminated()
Referenced by qt_adopted_thread_watcher_function(), and QThreadPrivate::start().
terminate
void QThread::terminate () slot
Terminates the execution of the thread.
The thread may or may not be terminated immediately, depending on the operating system's scheduling policies. Listen for the terminated() signal, or use QThread::wait() after terminate(), to be sure.
When the thread is terminated, all threads waiting for the thread to finish will be woken up.
Warning
This function is dangerous and its use is discouraged. The thread can be terminated at any point in its code path. Threads can be terminated while modifying data. There is no chance for the thread to clean up after itself, unlock any held mutexes, etc. In short, use this function only if absolutely necessary.
Termination can be explicitly enabled or disabled by calling QThread::setTerminationEnabled(). Calling this function while termination is disabled results in the termination being deferred, until termination is re-enabled. See the documentation of QThread::setTerminationEnabled() for more information.
See also
setTerminationEnabled()
Definition at line 689 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish(), and QWindowsPipeWriter::~QWindowsPipeWriter().
 {
     Q_D(QThread);
     QMutexLocker locker(&d->mutex);
     if (!d->thread_id)
         return;
     int code = pthread_cancel(d->thread_id);
     if (code) {
         qWarning("QThread::start: Thread termination error: %s",
                  qPrintable(qt_error_string((code))));
     } else {
         d->terminated = true;
     }
 }
terminated
void QThread::terminated () signal
This signal is emitted when the thread is terminated.
See also
started(), finished()
Referenced by QThreadPrivate::finish().
usleep()
void QThread::usleep (unsigned long usecs) static protected
Forces the current thread to sleep for usecs microseconds.
See also
sleep(), msleep()
Definition at line 521 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish().
 {
     struct timeval tv;
     gettimeofday(&tv, 0);
     struct timespec ti;
     ti.tv_nsec = (tv.tv_usec + (usecs % 1000000)) * 1000;
     ti.tv_sec = tv.tv_sec + (usecs / 1000000) + (ti.tv_nsec / 1000000000);
     ti.tv_nsec %= 1000000000;
     thread_sleep(&ti);
 }
wait()
bool QThread::wait (unsigned long time = ULONG_MAX)
Blocks the thread until either of these conditions is met:
The thread associated with this QThread object has finished execution (i.
e. when it returns from run()). This function will return true if the thread has finished. It also returns true if the thread has not been started yet.
time milliseconds has elapsed. If time is ULONG_MAX (the default), then the wait will never timeout (the thread must return from run()). This function will return false if the wait timed out.
This provides similar functionality to the POSIX pthread_join() function.
See also
sleep(), terminate()
Definition at line 706 of file qthread_unix.cpp.
Referenced by QFSEventsFileSystemWatcherEngine::addPaths(), QNetworkConfigurationManagerPrivate::cleanup(), QThreadPrivate::finish(), QNetworkAccessHttpBackend::postRequest(), QScanThread::quit(), QKqueueFileSystemWatcherEngine::removePaths(), QWindowsFileSystemWatcherEngine::removePaths(), QFSEventsFileSystemWatcherEngine::removePaths(), QPollingFileSystemWatcherEngine::removePaths(), QThreadPoolPrivate::reset(), QBBScreenEventThread::shutdown(), QDeclarativePixmapReader::~QDeclarativePixmapReader(), QDeclarativeWorkerScriptEngine::~QDeclarativeWorkerScriptEngine(), QDeclarativeXmlQueryEngine::~QDeclarativeXmlQueryEngine(), QDirectFbIntegration::~QDirectFbIntegration(), QDnotifySignalThread::~QDnotifySignalThread(), QFileInfoGatherer::~QFileInfoGatherer(), QIntMousePrivate::~QIntMousePrivate(), QKqueueFileSystemWatcherEngine::~QKqueueFileSystemWatcherEngine(), QNlaThread::~QNlaThread(), ~QThread(), QWindowsFileSystemWatcherEngine::~QWindowsFileSystemWatcherEngine(), QWindowsPipeWriter::~QWindowsPipeWriter(), and QWSIntKbPrivate::~QWSIntKbPrivate().
 {
     Q_D(QThread);
     QMutexLocker locker(&d->mutex);
     if (d->thread_id == pthread_self()) {
         qWarning("QThread::wait: Thread tried to wait on itself");
         return false;
     }
     if (d->finished || !d->running)
         return true;
     while (d->running) {
         if (!d->thread_done.wait(locker.mutex(), time))
             return false;
     }
     return true;
 }
yieldCurrentThread()
void QThread::yieldCurrentThread () static
Yields execution of the current thread to another runnable thread, if any.
Note that the operating system decides to which thread to switch.
Definition at line 474 of file qthread_unix.cpp.
Referenced by QThreadPrivate::finish(), and QMutex::lockInternal().
 {
     sched_yield();
 }
Friends and Related Functions
QCoreApplication
friend class QCoreApplication friend
Definition at line 135 of file qthread.h.
QThreadData
friend class QThreadData friend
Definition at line 136 of file qthread.h.
The documentation for this class was generated from the following files:
/src/corelib/thread/qthread.h
/src/corelib/thread/qthread.cpp
/src/corelib/thread/qthread_unix.cpp
/src/corelib/thread/qthread_win.cpp