Qt 4.8: QCharRef Class Reference
QCharRef Class Reference
The QCharRef class is a helper class for QString.
#include <qstring.h>
Public Functions
QChar::Category category () const
uchar cell () const
uchar combiningClass () const
QString decomposition () const
QChar::Decomposition decompositionTag () const
int digitValue () const
QChar::Direction direction () const
bool hasMirrored () const
bool isDigit () const
bool isLetter () const
bool isLetterOrNumber ()
bool isLower () const
bool isMark () const
bool isNull () const
bool isNumber () const
bool isPrint () const
bool isPunct () const
bool isSpace () const
bool isTitleCase () const
bool isUpper () const
QChar::Joining joining () const
QChar mirroredChar () const
operator QChar () const
QCharRef & operator= (const QChar &c)
QT_ASCII_CAST_WARN QCharRef & operator= (char c)
QT_ASCII_CAST_WARN QCharRef & operator= (uchar c)
QCharRef & operator= (const QCharRef &c)
QCharRef & operator= (ushort rc)
QCharRef & operator= (short rc)
QCharRef & operator= (uint rc)
QCharRef & operator= (int rc)
uchar row () const
void setCell (uchar cell)
void setRow (uchar row)
char toAscii () const
char toLatin1 () const
QChar toLower () const
QChar toTitleCase () const
QChar toUpper () const
ushort unicode () const
ushort & unicode ()
QChar::UnicodeVersion unicodeVersion () const
Private Functions
QCharRef (QString &str, int idx)
Properties
int i
QString & s
Friends
class QString
Detailed Description
The QCharRef class is a helper class for QString.
Note
This class or function is reentrant.
Warning
This function is not part of the public interface.
When you get an object of type QCharRef, if you can assign to it, the assignment will apply to the character in the string from which you got the reference. That is its whole purpose in life. The QCharRef becomes invalid once modifications are made to the string: if you want to keep the character, copy it into a QChar.
Most of the QChar member functions also exist in QCharRef. However, they are not explicitly documented here.
See also
QString::operator[]() QString::at() QChar
Definition at line 785 of file qstring.h.
Constructors and Destructors
QCharRef()
QCharRef::QCharRef (QString & str, int idx) inline private
Definition at line 788 of file qstring.h.
         : s(str),i(idx) {}
Functions
category()
QChar::Category QCharRef::category () const inline
Definition at line 834 of file qstring.h.
 { return QChar(*this).category(); }
cell()
uchar QCharRef::cell () const inline
Definition at line 845 of file qstring.h.
 { return QChar(*this).cell(); }
combiningClass()
uchar QCharRef::combiningClass () const inline
Definition at line 841 of file qstring.h.
 { return QChar(*this).combiningClass(); }
decomposition()
QString QCharRef::decomposition () const inline
Definition at line 839 of file qstring.h.
 { return QChar(*this).decomposition(); }
decompositionTag()
QChar::Decomposition QCharRef::decompositionTag () const inline
Definition at line 840 of file qstring.h.
 { return QChar(*this).decompositionTag(); }
digitValue()
int QCharRef::digitValue () const inline
Definition at line 829 of file qstring.h.
 { return QChar(*this).digitValue(); }
direction()
QChar::Direction QCharRef::direction () const inline
Definition at line 835 of file qstring.h.
 { return QChar(*this).direction(); }
hasMirrored()
bool QCharRef::hasMirrored () const inline
Definition at line 837 of file qstring.h.
 { return QChar(*this).hasMirrored(); }
isDigit()
bool QCharRef::isDigit () const inline
Definition at line 824 of file qstring.h.
 { return QChar(*this).isDigit(); }
isLetter()
bool QCharRef::isLetter () const inline
Definition at line 821 of file qstring.h.
 { return QChar(*this).isLetter(); }
isLetterOrNumber()
bool QCharRef::isLetterOrNumber () inline
Definition at line 823 of file qstring.h.
 { return QChar(*this).isLetterOrNumber(); }
isLower()
bool QCharRef::isLower () const inline
Definition at line 825 of file qstring.h.
 { return QChar(*this).isLower(); }
isMark()
bool QCharRef::isMark () const inline
Definition at line 820 of file qstring.h.
 { return QChar(*this).isMark(); }
isNull()
bool QCharRef::isNull () const inline
Definition at line 816 of file qstring.h.
 { return QChar(*this).isNull(); }
isNumber()
bool QCharRef::isNumber () const inline
Definition at line 822 of file qstring.h.
 { return QChar(*this).isNumber(); }
isPrint()
bool QCharRef::isPrint () const inline
Definition at line 817 of file qstring.h.
 { return QChar(*this).isPrint(); }
isPunct()
bool QCharRef::isPunct () const inline
Definition at line 818 of file qstring.h.
 { return QChar(*this).isPunct(); }
isSpace()
bool QCharRef::isSpace () const inline
Definition at line 819 of file qstring.h.
 { return QChar(*this).isSpace(); }
isTitleCase()
bool QCharRef::isTitleCase () const inline
Definition at line 827 of file qstring.h.
 { return QChar(*this).isTitleCase(); }
isUpper()
bool QCharRef::isUpper () const inline
Definition at line 826 of file qstring.h.
 { return QChar(*this).isUpper(); }
joining()
QChar::Joining QCharRef::joining () const inline
Definition at line 836 of file qstring.h.
 { return QChar(*this).joining(); }
mirroredChar()
QChar QCharRef::mirroredChar () const inline
Definition at line 838 of file qstring.h.
 { return QChar(*this).mirroredChar(); }
operator QChar()
QCharRef::operator QChar () const inline
Definition at line 796 of file qstring.h.
         { return i < s.d->size ? s.d->data[i] : 0; }
operator=() [1/8]
QCharRef& QCharRef::operator= (const QChar & c) inline
Definition at line 798 of file qstring.h.
         { if (i >= s.d->size) s.expand(i); else s.detach();
           s.d->data[i] = c.unicode();  return *this; }
operator=() [2/8]
QT_ASCII_CAST_WARN QCharRef& QCharRef::operator= (char c) inline
Definition at line 804 of file qstring.h.
     { return operator=(QChar::fromAscii(c)); }
operator=() [3/8]
QT_ASCII_CAST_WARN QCharRef& QCharRef::operator= (uchar c) inline
Definition at line 806 of file qstring.h.
     { return operator=(QChar::fromAscii(c)); }
operator=() [4/8]
QCharRef& QCharRef::operator= (const QCharRef & c) inline
Definition at line 809 of file qstring.h.
Referenced by operator=().
 { return operator=(QChar(c)); }
operator=() [5/8]
QCharRef& QCharRef::operator= (ushort rc) inline
Definition at line 810 of file qstring.h.
Referenced by operator=().
 { return operator=(QChar(rc)); }
operator=() [6/8]
QCharRef& QCharRef::operator= (short rc) inline
Definition at line 811 of file qstring.h.
Referenced by operator=().
 { return operator=(QChar(rc)); }
operator=() [7/8]
QCharRef& QCharRef::operator= (uint rc) inline
Definition at line 812 of file qstring.h.
Referenced by operator=().
 { return operator=(QChar(rc)); }
operator=() [8/8]
QCharRef& QCharRef::operator= (int rc) inline
Definition at line 813 of file qstring.h.
Referenced by operator=().
 { return operator=(QChar(rc)); }
row()
uchar QCharRef::row () const inline
Definition at line 846 of file qstring.h.
 { return QChar(*this).row(); }
setCell()
void QCharRef::setCell (uchar cell) inline
Definition at line 876 of file qstring.h.
 { QChar(*this).setCell(acell); }
setRow()
void QCharRef::setRow (uchar row) inline
Definition at line 875 of file qstring.h.
 { QChar(*this).setRow(arow); }
toAscii()
char QCharRef::toAscii () const inline
Definition at line 855 of file qstring.h.
 { return QChar(*this).toAscii(); }
toLatin1()
char QCharRef::toLatin1 () const inline
Definition at line 856 of file qstring.h.
 { return QChar(*this).toLatin1(); }
toLower()
QChar QCharRef::toLower () const inline
Definition at line 830 of file qstring.h.
 { return QChar(*this).toLower(); }
toTitleCase()
QChar QCharRef::toTitleCase () const inline
Definition at line 832 of file qstring.h.
 { return QChar(*this).toTitleCase(); }
toUpper()
QChar QCharRef::toUpper () const inline
Definition at line 831 of file qstring.h.
 { return QChar(*this).toUpper(); }
unicode() [1/2]
ushort QCharRef::unicode () const inline
Definition at line 857 of file qstring.h.
 { return QChar(*this).unicode(); }
unicode() [2/2]
ushort& QCharRef::unicode () inline
Definition at line 859 of file qstring.h.
 { return s.data()[i].unicode(); }
unicodeVersion()
QChar::UnicodeVersion QCharRef::unicodeVersion () const inline
Definition at line 843 of file qstring.h.
 { return QChar(*this).unicodeVersion(); }
Friends and Related Functions
QString
friend class QString friend
Definition at line 790 of file qstring.h.
Properties
i
int QCharRef::i private
Definition at line 787 of file qstring.h.
s
QString& QCharRef::s private
Definition at line 786 of file qstring.h.
The documentation for this class was generated from the following file:
/src/corelib/tools/qstring.h