Qt 4.8: QFontJis0201Codec Class Reference
QFontJis0201Codec Class Reference
#include <qfontjpcodec.h>
Public Functions
QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
QByteArray convertFromUnicode (const QChar *uc, int len, ConverterState *) const
QTextCodec subclasses must reimplement this function.
QString convertToUnicode (const char *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
QFontJis0201Codec ()
Public Functions inherited from QTextCodec
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > _aliases ()
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
Definition at line 53 of file qfontjpcodec.h.
Constructors and Destructors
QFontJis0201Codec()
QFontJis0201Codec::QFontJis0201Codec ()
Definition at line 51 of file qfontjpcodec.cpp.
 {
 }
Functions
_aliases()
static QList<QByteArray> QFontJis0201Codec::_aliases () inline static
Definition at line 59 of file qfontjpcodec.h.
Referenced by JPTextCodecs::aliases(), aliases(), QFontJis0208Codec::aliases(), and JPTextCodecs::createForName().
 { return QList<QByteArray>(); }
_mibEnum()
int QFontJis0201Codec::_mibEnum () static
Definition at line 60 of file qfontjpcodec.cpp.
Referenced by _aliases(), QFontJis0208Codec::_aliases(), JPTextCodecs::createForMib(), mibEnum(), QFontJis0208Codec::mibEnum(), and JPTextCodecs::mibEnums().
 {
     return 15;
 }
_name()
QByteArray QFontJis0201Codec::_name () static
Definition at line 55 of file qfontjpcodec.cpp.
Referenced by JPTextCodecs::createForName(), name(), QFontJis0208Codec::name(), and JPTextCodecs::names().
 {
     return "jisx0201*-0";
 }
aliases()
QList<QByteArray> QFontJis0201Codec::aliases () const inline virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented from QTextCodec.
Definition at line 63 of file qfontjpcodec.h.
 { return _aliases(); }
convertFromUnicode()
QByteArray QFontJis0201Codec::convertFromUnicode (const QChar * input, int number, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first number of characters from the input array from Unicode to the encoding of the subclass, and returns the result in a QByteArray.
state can be 0 in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 65 of file qfontjpcodec.cpp.
Referenced by mibEnum(), and QFontJis0208Codec::mibEnum().
 {
     QByteArray rstring;
     rstring.resize(len);
     uchar *rdata = (uchar *) rstring.data();
     const QChar *sdata = uc;
     int i = 0;
     for (; i < len; ++i, ++sdata, ++rdata) {
         if (sdata->unicode() < 0x80) {
             *rdata = (uchar) sdata->unicode();
         } else if (sdata->unicode() >= 0xff61 && sdata->unicode() <= 0xff9f) {
             *rdata = (uchar) (sdata->unicode() - 0xff61 + 0xa1);
         } else {
             *rdata = 0;
         }
     }
     return rstring;
 }
convertToUnicode()
QString QFontJis0201Codec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 84 of file qfontjpcodec.cpp.
Referenced by mibEnum(), and QFontJis0208Codec::mibEnum().
 {
     return QString();
 }
mibEnum()
int QFontJis0201Codec::mibEnum () const inline virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implements QTextCodec.
Definition at line 64 of file qfontjpcodec.h.
 { return _mibEnum(); }
name()
QByteArray QFontJis0201Codec::name () const inline virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implements QTextCodec.
Definition at line 62 of file qfontjpcodec.h.
 { return _name(); }
The documentation for this class was generated from the following files:
/src/plugins/codecs/jp/qfontjpcodec.h
/src/plugins/codecs/jp/qfontjpcodec.cpp