Qt 4.8: QReadWriteLock Class Reference
QReadWriteLock Class Reference
The QReadWriteLock class provides read-write locking.
#include <qreadwritelock.h>
Public Types
enum RecursionMode { NonRecursive, Recursive }
QReadWriteLock multiple times and the mutex won't be unlocked until a corresponding number of unlock() calls have been made.
Public Functions
void lockForRead ()
Locks the lock for reading.
void lockForWrite ()
Locks the lock for writing.
QReadWriteLock ()
Constructs a QReadWriteLock object in NonRecursive mode.
QReadWriteLock (RecursionMode recursionMode)
Constructs a QReadWriteLock object in the given recursionMode.
bool tryLockForRead ()
Attempts to lock for reading.
bool tryLockForRead (int timeout)
Attempts to lock for reading.
bool tryLockForWrite ()
Attempts to lock for writing.
bool tryLockForWrite (int timeout)
Attempts to lock for writing.
void unlock ()
Unlocks the lock.
~QReadWriteLock ()
Destroys the QReadWriteLock object.
Properties
QReadWriteLockPrivate * d
Friends
class QWaitCondition
Detailed Description
The QReadWriteLock class provides read-write locking.
Note
This class or function is threadsafe.
A read-write lock is a synchronization tool for protecting resources that can be accessed for reading and writing. This type of lock is useful if you want to allow multiple threads to have simultaneous read-only access, but as soon as one thread wants to write to the resource, all other threads must be blocked until the writing is complete.
In many cases, QReadWriteLock is a direct competitor to QMutex. QReadWriteLock is a good choice if there are many concurrent reads and writing occurs infrequently.
Example:
QReadWriteLock lock;
void ReaderThread::run()
{
    ...
    lock.lockForRead();
    read_file();
    lock.unlock();
    ...
}
void WriterThread::run()
{
    ...
    lock.lockForWrite();
    write_file();
    lock.unlock();
    ...
}
To ensure that writers aren't blocked forever by readers, readers attempting to obtain a lock will not succeed if there is a blocked writer waiting for access, even if the lock is currently only accessed by other readers. Also, if the lock is accessed by a writer and another writer comes in, that writer will have priority over any readers that might also be waiting.
Like QMutex, a QReadWriteLock can be recursively locked by the same thread when constructed in QReadWriteLock::RecursionMode. In such cases, unlock() must be called the same number of times lockForWrite() or lockForRead() was called. Note that the lock type cannot be changed when trying to lock recursively, i.e. it is not possible to lock for reading in a thread that already has locked for writing (and vice versa).
See also
QReadLocker, QWriteLocker, QMutex, QSemaphore
Definition at line 58 of file qreadwritelock.h.
Enumerations
RecursionMode
enum QReadWriteLock::RecursionMode
QReadWriteLock multiple times and the mutex won't be unlocked until a corresponding number of unlock() calls have been made.
Since
4.4
Recursive In this mode, a thread can lock the same
NonRecursive In this mode, a thread may only lock a QReadWriteLock once.
See also
QReadWriteLock()
Enumerator
NonRecursive
Recursive
Definition at line 61 of file qreadwritelock.h.
 { NonRecursive, Recursive };
Constructors and Destructors
QReadWriteLock() [1/2]
QReadWriteLock::QReadWriteLock ()
Constructs a QReadWriteLock object in NonRecursive mode.
See also
lockForRead(), lockForWrite()
Definition at line 120 of file qreadwritelock.cpp.
     :d(new QReadWriteLockPrivate(NonRecursive))
 { }
QReadWriteLock() [2/2]
QReadWriteLock::QReadWriteLock (RecursionMode recursionMode)
Constructs a QReadWriteLock object in the given recursionMode.
Since
4.4
See also
lockForRead(), lockForWrite(), RecursionMode
Definition at line 134 of file qreadwritelock.cpp.
     : d(new QReadWriteLockPrivate(recursionMode))
 { }
~QReadWriteLock()
QReadWriteLock::~QReadWriteLock ()
Destroys the QReadWriteLock object.
Warning
Destroying a read-write lock that is in use may result in undefined behavior.
Definition at line 144 of file qreadwritelock.cpp.
 {
     delete d;
 }
Functions
lockForRead()
void QReadWriteLock::lockForRead ()
Locks the lock for reading.
This function will block the current thread if any thread (including the current) has locked for writing.
See also
unlock() lockForWrite() tryLockForRead()
Definition at line 156 of file qreadwritelock.cpp.
Referenced by QSqlDatabasePrivate::database(), QWaitConditionPrivate::post(), QReadLocker::relock(), and QWaitCondition::wait().
 {
     QMutexLocker lock(&d->mutex);
     Qt::HANDLE self = 0;
     if (d->recursive) {
         self = QThread::currentThreadId();
         QHash<Qt::HANDLE, int>::iterator it = d->currentReaders.find(self);
         if (it != d->currentReaders.end()) {
             ++it.value();
             ++d->accessCount;
             Q_ASSERT_X(d->accessCount > 0, "QReadWriteLock::lockForRead()",
                        "Overflow in lock counter");
             return;
         }
     }
     while (d->accessCount < 0 || d->waitingWriters) {
         ++d->waitingReaders;
         d->readerWait.wait(&d->mutex);
         --d->waitingReaders;
     }
     if (d->recursive)
         d->currentReaders.insert(self, 1);
     ++d->accessCount;
     Q_ASSERT_X(d->accessCount > 0, "QReadWriteLock::lockForRead()", "Overflow in lock counter");
 }
lockForWrite()
void QReadWriteLock::lockForWrite ()
Locks the lock for writing.
This function will block the current thread if another thread has locked for reading or writing.
See also
unlock() lockForRead() tryLockForWrite()
Definition at line 287 of file qreadwritelock.cpp.
Referenced by QWaitConditionPrivate::post(), QWriteLocker::relock(), and QWaitCondition::wait().
 {
     QMutexLocker lock(&d->mutex);
     Qt::HANDLE self = 0;
     if (d->recursive) {
         self = QThread::currentThreadId();
         if (d->currentWriter == self) {
             --d->accessCount;
             Q_ASSERT_X(d->accessCount < 0, "QReadWriteLock::lockForWrite()",
                        "Overflow in lock counter");
             return;
         }
     }
     while (d->accessCount != 0) {
         ++d->waitingWriters;
         d->writerWait.wait(&d->mutex);
         --d->waitingWriters;
     }
     if (d->recursive)
         d->currentWriter = self;
     --d->accessCount;
     Q_ASSERT_X(d->accessCount < 0, "QReadWriteLock::lockForWrite()", "Overflow in lock counter");
 }
tryLockForRead() [1/2]
bool QReadWriteLock::tryLockForRead ()
Attempts to lock for reading.
If the lock was obtained, this function returns true, otherwise it returns false instead of waiting for the lock to become available, i.e. it does not block.
The lock attempt will fail if another thread has locked for writing.
If the lock was obtained, the lock must be unlocked with unlock() before another thread can successfully lock it.
See also
unlock() lockForRead()
Definition at line 199 of file qreadwritelock.cpp.
 {
     QMutexLocker lock(&d->mutex);
     Qt::HANDLE self = 0;
     if (d->recursive) {
         self = QThread::currentThreadId();
         QHash<Qt::HANDLE, int>::iterator it = d->currentReaders.find(self);
         if (it != d->currentReaders.end()) {
             ++it.value();
             ++d->accessCount;
             Q_ASSERT_X(d->accessCount > 0, "QReadWriteLock::tryLockForRead()",
                        "Overflow in lock counter");
             return true;
         }
     }
     if (d->accessCount < 0)
         return false;
     if (d->recursive)
         d->currentReaders.insert(self, 1);
     ++d->accessCount;
     Q_ASSERT_X(d->accessCount > 0, "QReadWriteLock::tryLockForRead()", "Overflow in lock counter");
     return true;
 }
tryLockForRead() [2/2]
bool QReadWriteLock::tryLockForRead (int timeout)
Attempts to lock for reading.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function returns true if the lock was obtained; otherwise it returns false. If another thread has locked for writing, this function will wait for at most timeout milliseconds for the lock to become available.
Note: Passing a negative number as the timeout is equivalent to calling lockForRead(), i.e. this function will wait forever until lock can be locked for reading when timeout is negative.
If the lock was obtained, the lock must be unlocked with unlock() before another thread can successfully lock it.
See also
unlock() lockForRead()
Definition at line 247 of file qreadwritelock.cpp.
 {
     QMutexLocker lock(&d->mutex);
     Qt::HANDLE self = 0;
     if (d->recursive) {
         self = QThread::currentThreadId();
         QHash<Qt::HANDLE, int>::iterator it = d->currentReaders.find(self);
         if (it != d->currentReaders.end()) {
             ++it.value();
             ++d->accessCount;
             Q_ASSERT_X(d->accessCount > 0, "QReadWriteLock::tryLockForRead()",
                        "Overflow in lock counter");
             return true;
         }
     }
     while (d->accessCount < 0 || d->waitingWriters) {
         ++d->waitingReaders;
         bool success = d->readerWait.wait(&d->mutex, timeout < 0 ? ULONG_MAX : ulong(timeout));
         --d->waitingReaders;
         if (!success)
             return false;
     }
     if (d->recursive)
         d->currentReaders.insert(self, 1);
     ++d->accessCount;
     Q_ASSERT_X(d->accessCount > 0, "QReadWriteLock::tryLockForRead()", "Overflow in lock counter");
     return true;
 }
tryLockForWrite() [1/2]
bool QReadWriteLock::tryLockForWrite ()
Attempts to lock for writing.
If the lock was obtained, this function returns true; otherwise, it returns false immediately.
The lock attempt will fail if another thread has locked for reading or writing.
If the lock was obtained, the lock must be unlocked with unlock() before another thread can successfully lock it.
See also
unlock() lockForWrite()
Definition at line 327 of file qreadwritelock.cpp.
 {
     QMutexLocker lock(&d->mutex);
     Qt::HANDLE self = 0;
     if (d->recursive) {
         self = QThread::currentThreadId();
         if (d->currentWriter == self) {
             --d->accessCount;
             Q_ASSERT_X(d->accessCount < 0, "QReadWriteLock::lockForWrite()",
                        "Overflow in lock counter");
             return true;
         }
     }
     if (d->accessCount != 0)
         return false;
     if (d->recursive)
         d->currentWriter = self;
     --d->accessCount;
     Q_ASSERT_X(d->accessCount < 0, "QReadWriteLock::tryLockForWrite()",
                "Overflow in lock counter");
     return true;
 }
tryLockForWrite() [2/2]
bool QReadWriteLock::tryLockForWrite (int timeout)
Attempts to lock for writing.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
This function returns true if the lock was obtained; otherwise it returns false. If another thread has locked for reading or writing, this function will wait for at most timeout milliseconds for the lock to become available.
Note: Passing a negative number as the timeout is equivalent to calling lockForWrite(), i.e. this function will wait forever until lock can be locked for writing when timeout is negative.
If the lock was obtained, the lock must be unlocked with unlock() before another thread can successfully lock it.
See also
unlock() lockForWrite()
Definition at line 374 of file qreadwritelock.cpp.
 {
     QMutexLocker lock(&d->mutex);
     Qt::HANDLE self = 0;
     if (d->recursive) {
         self = QThread::currentThreadId();
         if (d->currentWriter == self) {
             --d->accessCount;
             Q_ASSERT_X(d->accessCount < 0, "QReadWriteLock::lockForWrite()",
                        "Overflow in lock counter");
             return true;
         }
     }
     while (d->accessCount != 0) {
         ++d->waitingWriters;
         bool success = d->writerWait.wait(&d->mutex, timeout < 0 ? ULONG_MAX : ulong(timeout));
         --d->waitingWriters;
         if (!success)
             return false;
     }
     if (d->recursive)
         d->currentWriter = self;
     --d->accessCount;
     Q_ASSERT_X(d->accessCount < 0, "QReadWriteLock::tryLockForWrite()",
                "Overflow in lock counter");
     return true;
 }
unlock()
void QReadWriteLock::unlock ()
Unlocks the lock.
Attempting to unlock a lock that is not locked is an error, and will result in program termination.
See also
lockForRead() lockForWrite() tryLockForRead() tryLockForWrite()
Definition at line 416 of file qreadwritelock.cpp.
Referenced by QSqlDatabasePrivate::database(), QWaitConditionPrivate::post(), QWSDisplay::ungrab(), QReadLocker::unlock(), QWriteLocker::unlock(), and QWaitCondition::wait().
 {
     QMutexLocker lock(&d->mutex);
     Q_ASSERT_X(d->accessCount != 0, "QReadWriteLock::unlock()", "Cannot unlock an unlocked lock");
     bool unlocked = false;
     if (d->accessCount > 0) {
         // releasing a read lock
         if (d->recursive) {
             Qt::HANDLE self = QThread::currentThreadId();
             QHash<Qt::HANDLE, int>::iterator it = d->currentReaders.find(self);
             if (it != d->currentReaders.end()) {
                 if (--it.value() <= 0)
                     d->currentReaders.erase(it);
             }
         }
         unlocked = --d->accessCount == 0;
     } else if (d->accessCount < 0 && ++d->accessCount == 0) {
         // released a write lock
         unlocked = true;
         d->currentWriter = 0;
     }
     if (unlocked) {
         if (d->waitingWriters) {
             d->writerWait.wakeOne();
         } else if (d->waitingReaders) {
             d->readerWait.wakeAll();
         }
     }
 }
Friends and Related Functions
QWaitCondition
friend class QWaitCondition friend
Definition at line 81 of file qreadwritelock.h.
Properties
d
QReadWriteLockPrivate* QReadWriteLock::d private
Definition at line 79 of file qreadwritelock.h.
Referenced by lockForRead(), lockForWrite(), QWaitConditionPrivate::post(), tryLockForRead(), tryLockForWrite(), unlock(), QWaitCondition::wait(), and ~QReadWriteLock().
The documentation for this class was generated from the following files:
/src/corelib/thread/qreadwritelock.h
/src/corelib/thread/qreadwritelock.cpp