Qt 4.8: QSyntaxHighlighter Class Reference
QSyntaxHighlighter Class Reference abstract
The QSyntaxHighlighter class allows you to define syntax highlighting rules, and in addition you can use the class to query a document's current formatting or user data.
#include <qsyntaxhighlighter.h>
Public Slots
void rehighlight ()
Reapplies the highlighting to the whole document.
void rehighlightBlock (const QTextBlock &block)
Reapplies the highlighting to the given QTextBlock block.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
QTextDocument * document () const
Returns the QTextDocument on which this syntax highlighter is installed.
QSyntaxHighlighter (QObject *parent)
Constructs a QSyntaxHighlighter with the given parent.
QSyntaxHighlighter (QTextDocument *parent)
Constructs a QSyntaxHighlighter and installs it on parent.
QSyntaxHighlighter (QTextEdit *parent)
Constructs a QSyntaxHighlighter and installs it on parent 's QTextDocument.
void setDocument (QTextDocument *doc)
Installs the syntax highlighter on the given QTextDocument doc.
virtual ~QSyntaxHighlighter ()
Destructor.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QTextBlock currentBlock () const
Returns the current text block.
int currentBlockState () const
Returns the state of the current text block.
QTextBlockUserData * currentBlockUserData () const
Returns the QTextBlockUserData object previously attached to the current text block.
QTextCharFormat format (int pos) const
Returns the format at position inside the syntax highlighter's current text block.
virtual void highlightBlock (const QString &text)=0
Highlights the given text block.
int previousBlockState () const
Returns the end state of the text block previous to the syntax highlighter's current block.
void setCurrentBlockState (int newState)
Sets the state of the current text block to newState.
void setCurrentBlockUserData (QTextBlockUserData *data)
Attaches the given data to the current text block.
void setFormat (int start, int count, const QTextCharFormat &format)
This function is applied to the syntax highlighter's current text block (i.e.
void setFormat (int start, int count, const QColor &color)
The specified color is applied to the current text block from the start position for a length of count characters.
void setFormat (int start, int count, const QFont &font)
The specified font is applied to the current text block from the start position for a length of count characters.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSyntaxHighlighter class allows you to define syntax highlighting rules, and in addition you can use the class to query a document's current formatting or user data.
Note
This class or function is reentrant.
Since
4.1
The QSyntaxHighlighter class is a base class for implementing QTextEdit syntax highlighters. A syntax highligher automatically highlights parts of the text in a QTextEdit, or more generally in a QTextDocument. Syntax highlighters are often used when the user is entering text in a specific format (for example source code) and help the user to read the text and identify syntax errors.
To provide your own syntax highlighting, you must subclass QSyntaxHighlighter and reimplement highlightBlock().
When you create an instance of your QSyntaxHighlighter subclass, pass it the QTextEdit or QTextDocument that you want the syntax highlighting to be applied to. For example:
QTextEdit *editor = new QTextEdit;
MyHighlighter *highlighter = new MyHighlighter(editor->document());
After this your highlightBlock() function will be called automatically whenever necessary. Use your highlightBlock() function to apply formatting (e.g. setting the font and color) to the text that is passed to it. QSyntaxHighlighter provides the setFormat() function which applies a given QTextCharFormat on the current text block. For example:
void MyHighlighter::highlightBlock(const QString &text)
{
    QTextCharFormat myClassFormat;
    myClassFormat.setFontWeight(QFont::Bold);
    myClassFormat.setForeground(Qt::darkMagenta);
    QString pattern = "\\bMy[A-Za-z]+\\b";
    QRegExp expression(pattern);
    int index = text.indexOf(expression);
    while (index >= 0) {
        int length = expression.matchedLength();
        setFormat(index, length, myClassFormat);
        index = text.indexOf(expression, index + length);
    }
}
Some syntaxes can have constructs that span several text blocks. For example, a C++ syntax highlighter should be able to cope with /*...*/ multiline comments. To deal with these cases it is necessary to know the end state of the previous text block (e.g. "in comment").
Inside your highlightBlock() implementation you can query the end state of the previous text block using the previousBlockState() function. After parsing the block you can save the last state using setCurrentBlockState().
The currentBlockState() and previousBlockState() functions return an int value. If no state is set, the returned value is -1. You can designate any other value to identify any given state using the setCurrentBlockState() function. Once the state is set the QTextBlock keeps that value until it is set set again or until the corresponding paragraph of text is deleted.
For example, if you're writing a simple C++ syntax highlighter, you might designate 1 to signify "in comment":
QTextCharFormat multiLineCommentFormat;
multiLineCommentFormat.setForeground(Qt::red);
QRegExp startExpression("/\\*");
QRegExp endExpression("\\*/");
setCurrentBlockState(0);
int startIndex = 0;
if (previousBlockState() != 1)
    startIndex = text.indexOf(startExpression);
while (startIndex >= 0) {
   int endIndex = text.indexOf(endExpression, startIndex);
   int commentLength;
   if (endIndex == -1) {
       setCurrentBlockState(1);
       commentLength = text.length() - startIndex;
   } else {
       commentLength = endIndex - startIndex
                       + endExpression.matchedLength();
   }
   setFormat(startIndex, commentLength, multiLineCommentFormat);
   startIndex = text.indexOf(startExpression,
                             startIndex + commentLength);
}
In the example above, we first set the current block state to 0. Then, if the previous block ended within a comment, we higlight from the beginning of the current block ({startIndex = 0}). Otherwise, we search for the given start expression. If the specified end expression cannot be found in the text block, we change the current block state by calling setCurrentBlockState(), and make sure that the rest of the block is higlighted.
In addition you can query the current formatting and user data using the format() and currentBlockUserData() functions respectively. You can also attach user data to the current text block using the setCurrentBlockUserData() function. QTextBlockUserData can be used to store custom settings. In the case of syntax highlighting, it is in particular interesting as cache storage for information that you may figure out while parsing the paragraph's text. For an example, see the setCurrentBlockUserData() documentation.
See also
QTextEdit, {Syntax Highlighter Example}
Definition at line 66 of file qsyntaxhighlighter.h.
Constructors and Destructors
QSyntaxHighlighter() [1/3]
QSyntaxHighlighter::QSyntaxHighlighter (QObject * parent)
Constructs a QSyntaxHighlighter with the given parent.
Definition at line 318 of file qsyntaxhighlighter.cpp.
     : QObject(*new QSyntaxHighlighterPrivate, parent)
 {
 }
QSyntaxHighlighter() [2/3]
QSyntaxHighlighter::QSyntaxHighlighter (QTextDocument * parent)
Constructs a QSyntaxHighlighter and installs it on parent.
The specified QTextDocument also becomes the owner of the QSyntaxHighlighter.
Definition at line 328 of file qsyntaxhighlighter.cpp.
     : QObject(*new QSyntaxHighlighterPrivate, parent)
 {
     setDocument(parent);
 }
QSyntaxHighlighter() [3/3]
QSyntaxHighlighter::QSyntaxHighlighter (QTextEdit * parent)
Constructs a QSyntaxHighlighter and installs it on parent 's QTextDocument.
The specified QTextEdit also becomes the owner of the QSyntaxHighlighter.
Definition at line 339 of file qsyntaxhighlighter.cpp.
     : QObject(*new QSyntaxHighlighterPrivate, parent)
 {
     setDocument(parent->document());
 }
~QSyntaxHighlighter()
QSyntaxHighlighter::~QSyntaxHighlighter () virtual
Destructor.
Uninstalls this syntax highlighter from the text document.
Definition at line 348 of file qsyntaxhighlighter.cpp.
 {
     setDocument(0);
 }
Functions
currentBlock()
QTextBlock QSyntaxHighlighter::currentBlock () const protected
Returns the current text block.
Since
4.4
Definition at line 676 of file qsyntaxhighlighter.cpp.
Referenced by QScriptSyntaxHighlighter::highlightBlock().
 {
     Q_D(const QSyntaxHighlighter);
     return d->currentBlock;
 }
currentBlockState()
int QSyntaxHighlighter::currentBlockState () const protected
Returns the state of the current text block.
If no value is set, the returned value is -1.
Definition at line 587 of file qsyntaxhighlighter.cpp.
 {
     Q_D(const QSyntaxHighlighter);
     if (!d->currentBlock.isValid())
         return -1;
     return d->currentBlock.userState();
 }
currentBlockUserData()
QTextBlockUserData * QSyntaxHighlighter::currentBlockUserData () const protected
Returns the QTextBlockUserData object previously attached to the current text block.
See also
QTextBlock::userData(), setCurrentBlockUserData()
Definition at line 659 of file qsyntaxhighlighter.cpp.
 {
     Q_D(const QSyntaxHighlighter);
     if (!d->currentBlock.isValid())
         return 0;
     return d->currentBlock.userData();
 }
document()
QTextDocument * QSyntaxHighlighter::document () const
Returns the QTextDocument on which this syntax highlighter is installed.
Definition at line 383 of file qsyntaxhighlighter.cpp.
Referenced by QTextBlock::operator<().
 {
     Q_D(const QSyntaxHighlighter);
     return d->doc;
 }
format()
QTextCharFormat QSyntaxHighlighter::format (int pos) const protected
Returns the format at position inside the syntax highlighter's current text block.
Definition at line 555 of file qsyntaxhighlighter.cpp.
Referenced by QScriptSyntaxHighlighter::highlightBlock(), and setFormat().
 {
     Q_D(const QSyntaxHighlighter);
     if (pos < 0 || pos >= d->formatChanges.count())
         return QTextCharFormat();
     return d->formatChanges.at(pos);
 }
highlightBlock()
void QSyntaxHighlighter::highlightBlock (const QString & text) protected pure virtual
Highlights the given text block.
This function is called when necessary by the rich text engine, i.e. on text blocks which have changed.
To provide your own syntax highlighting, you must subclass QSyntaxHighlighter and reimplement highlightBlock(). In your reimplementation you should parse the block's text and call setFormat() as often as necessary to apply any font and color changes that you require. For example:
void MyHighlighter::highlightBlock(const QString &text)
{
    QTextCharFormat myClassFormat;
    myClassFormat.setFontWeight(QFont::Bold);
    myClassFormat.setForeground(Qt::darkMagenta);
    QString pattern = "\\bMy[A-Za-z]+\\b";
    QRegExp expression(pattern);
    int index = text.indexOf(expression);
    while (index >= 0) {
        int length = expression.matchedLength();
        setFormat(index, length, myClassFormat);
        index = text.indexOf(expression, index + length);
     }
 }
Some syntaxes can have constructs that span several text blocks. For example, a C++ syntax highlighter should be able to cope with /*...*/ multiline comments. To deal with these cases it is necessary to know the end state of the previous text block (e.g. "in comment").
Inside your highlightBlock() implementation you can query the end state of the previous text block using the previousBlockState() function. After parsing the block you can save the last state using setCurrentBlockState().
The currentBlockState() and previousBlockState() functions return an int value. If no state is set, the returned value is -1. You can designate any other value to identify any given state using the setCurrentBlockState() function. Once the state is set the QTextBlock keeps that value until it is set set again or until the corresponding paragraph of text gets deleted.
For example, if you're writing a simple C++ syntax highlighter, you might designate 1 to signify "in comment". For a text block that ended in the middle of a comment you'd set 1 using setCurrentBlockState, and for other paragraphs you'd set 0. In your parsing code if the return value of previousBlockState() is 1, you would highlight the text as a C++ comment until you reached the closing */.
See also
previousBlockState(), setFormat(), setCurrentBlockState()
Implemented in QScriptSyntaxHighlighter.
previousBlockState()
int QSyntaxHighlighter::previousBlockState () const protected
Returns the end state of the text block previous to the syntax highlighter's current block.
If no value was previously set, the returned value is -1.
See also
highlightBlock(), setCurrentBlockState()
Definition at line 570 of file qsyntaxhighlighter.cpp.
Referenced by QScriptSyntaxHighlighter::highlightBlock().
 {
     Q_D(const QSyntaxHighlighter);
     if (!d->currentBlock.isValid())
         return -1;
     const QTextBlock previous = d->currentBlock.previous();
     if (!previous.isValid())
         return -1;
     return previous.userState();
 }
rehighlight
void QSyntaxHighlighter::rehighlight () slot
Reapplies the highlighting to the whole document.
Since
4.2
See also
rehighlightBlock()
Definition at line 399 of file qsyntaxhighlighter.cpp.
 {
     Q_D(QSyntaxHighlighter);
     if (!d->doc)
         return;
     QTextCursor cursor(d->doc);
     d->rehighlight(cursor, QTextCursor::End);
 }
rehighlightBlock
void QSyntaxHighlighter::rehighlightBlock (const QTextBlock & block) slot
Reapplies the highlighting to the given QTextBlock block.
Since
4.6
See also
rehighlight()
Definition at line 419 of file qsyntaxhighlighter.cpp.
 {
     Q_D(QSyntaxHighlighter);
     if (!d->doc || !block.isValid() || block.document() != d->doc)
         return;
     const bool rehighlightPending = d->rehighlightPending;
     QTextCursor cursor(block);
     d->rehighlight(cursor, QTextCursor::EndOfBlock);
     if (rehighlightPending)
         d->rehighlightPending = rehighlightPending;
 }
setCurrentBlockState()
void QSyntaxHighlighter::setCurrentBlockState (int newState) protected
Sets the state of the current text block to newState.
See also
highlightBlock()
Definition at line 601 of file qsyntaxhighlighter.cpp.
Referenced by QScriptSyntaxHighlighter::highlightBlock().
 {
     Q_D(QSyntaxHighlighter);
     if (!d->currentBlock.isValid())
         return;
     d->currentBlock.setUserState(newState);
 }
setCurrentBlockUserData()
void QSyntaxHighlighter::setCurrentBlockUserData (QTextBlockUserData * data) protected
Attaches the given data to the current text block.
The ownership is passed to the underlying text document, i.e. the provided QTextBlockUserData object will be deleted if the corresponding text block gets deleted.
QTextBlockUserData can be used to store custom settings. In the case of syntax highlighting, it is in particular interesting as cache storage for information that you may figure out while parsing the paragraph's text.
For example while parsing the text, you can keep track of parenthesis characters that you encounter ('{[(' and the like), and store their relative position and the actual QChar in a simple class derived from QTextBlockUserData:
struct ParenthesisInfo
{
    QChar char;
    int position;
};
struct BlockData : public QTextBlockUserData
{
    QVector<ParenthesisInfo> parentheses;
};
During cursor navigation in the associated editor, you can ask the current QTextBlock (retrieved using the QTextCursor::block() function) if it has a user data object set and cast it to your BlockData object. Then you can check if the current cursor position matches with a previously recorded parenthesis position, and, depending on the type of parenthesis (opening or closing), find the next opening or closing parenthesis on the same level.
In this way you can do a visual parenthesis matching and highlight from the current cursor position to the matching parenthesis. That makes it easier to spot a missing parenthesis in your code and to find where a corresponding opening/closing parenthesis is when editing parenthesis intensive code.
See also
QTextBlock::setUserData()
Definition at line 644 of file qsyntaxhighlighter.cpp.
 {
     Q_D(QSyntaxHighlighter);
     if (!d->currentBlock.isValid())
         return;
     d->currentBlock.setUserData(data);
 }
setDocument()
void QSyntaxHighlighter::setDocument (QTextDocument * doc)
Installs the syntax highlighter on the given QTextDocument doc.
A QSyntaxHighlighter can only be used with one document at a time.
Definition at line 357 of file qsyntaxhighlighter.cpp.
Referenced by QSyntaxHighlighter(), and ~QSyntaxHighlighter().
 {
     Q_D(QSyntaxHighlighter);
     if (d->doc) {
         disconnect(d->doc, SIGNAL(contentsChange(int,int,int)),
                    this, SLOT(_q_reformatBlocks(int,int,int)));
         QTextCursor cursor(d->doc);
         cursor.beginEditBlock();
         for (QTextBlock blk = d->doc->begin(); blk.isValid(); blk = blk.next())
             blk.layout()->clearAdditionalFormats();
         cursor.endEditBlock();
     }
     d->doc = doc;
     if (d->doc) {
         connect(d->doc, SIGNAL(contentsChange(int,int,int)),
                 this, SLOT(_q_reformatBlocks(int,int,int)));
         d->rehighlightPending = true;
         QTimer::singleShot(0, this, SLOT(_q_delayedRehighlight()));
     }
 }
setFormat() [1/3]
void QSyntaxHighlighter::setFormat (int start, int count, const QTextCharFormat & format) protected
This function is applied to the syntax highlighter's current text block (i.e.
the text that is passed to the highlightBlock() function).
The specified format is applied to the text from the start position for a length of count characters (if count is 0, nothing is done). The formatting properties set in format are merged at display time with the formatting information stored directly in the document, for example as previously set with QTextCursor's functions. Note that the document itself remains unmodified by the format set through this function.
See also
format(), highlightBlock()
Definition at line 493 of file qsyntaxhighlighter.cpp.
Referenced by QScriptSyntaxHighlighter::highlightBlock(), QScriptSyntaxHighlighter::highlightWord(), and setFormat().
 {
     Q_D(QSyntaxHighlighter);
     if (start < 0 || start >= d->formatChanges.count())
         return;
     const int end = qMin(start + count, d->formatChanges.count());
     for (int i = start; i < end; ++i)
         d->formatChanges[i] = format;
 }
setFormat() [2/3]
void QSyntaxHighlighter::setFormat (int start, int count, const QColor & color) protected
The specified color is applied to the current text block from the start position for a length of count characters.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The other attributes of the current text block, e.g. the font and background color, are reset to default values.
See also
format(), highlightBlock()
Definition at line 518 of file qsyntaxhighlighter.cpp.
 {
     QTextCharFormat format;
     format.setForeground(color);
     setFormat(start, count, format);
 }
setFormat() [3/3]
void QSyntaxHighlighter::setFormat (int start, int count, const QFont & font) protected
The specified font is applied to the current text block from the start position for a length of count characters.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The other attributes of the current text block, e.g. the font and background color, are reset to default values.
See also
format(), highlightBlock()
Definition at line 539 of file qsyntaxhighlighter.cpp.
 {
     QTextCharFormat format;
     format.setFont(font);
     setFormat(start, count, format);
 }
The documentation for this class was generated from the following files:
/src/gui/text/qsyntaxhighlighter.h
/src/gui/text/qsyntaxhighlighter.cpp