Qt 4.8: QGraphicsSceneHoverEvent Class Reference
QGraphicsSceneHoverEvent Class Reference
The QGraphicsSceneHoverEvent class provides hover events in the graphics view framework.
#include <qgraphicssceneevent.h>
Public Functions
QPointF lastPos () const
Returns the last recorded mouse cursor position in item coordinates.
QPointF lastScenePos () const
Returns the last recorded, the scene coordinates of the previous mouse or hover event received by the view, that created the event mouse cursor position in scene coordinates.
QPoint lastScreenPos () const
Returns the last recorded mouse cursor position in screen coordinates.
Qt::KeyboardModifiers modifiers () const
Returns the keyboard modifiers at the moment the hover event was sent.
QPointF pos () const
Returns the position of the mouse cursor in item coordinates at the moment the hover event was sent.
QGraphicsSceneHoverEvent (Type type=None)
Constructs a graphics scene hover event of the specified type.
QPointF scenePos () const
Returns the position of the mouse cursor in scene coordinates at the moment the hover event was sent.
QPoint screenPos () const
Returns the position of the mouse cursor in screen coordinates at the moment the hover event was sent.
void setLastPos (const QPointF &pos)
void setLastScenePos (const QPointF &pos)
void setLastScreenPos (const QPoint &pos)
void setModifiers (Qt::KeyboardModifiers modifiers)
Sets the modifiers for the current hover event to modifiers.
void setPos (const QPointF &pos)
Sets the position associated with the hover event to the given point in item coordinates.
void setScenePos (const QPointF &pos)
Sets the position associated with the hover event to the given point in scene coordinates.
void setScreenPos (const QPoint &pos)
Sets the position associated with the hover event to the given point in screen coordinates.
~QGraphicsSceneHoverEvent ()
Destroys the event.
Public Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (Type type)
Constructs a generic graphics scene event of the specified type.
void setWidget (QWidget *widget)
Sets the widget related to this event.
QWidget * widget () const
Returns the widget where the event originated, or 0 if the event originates from another application.
~QGraphicsSceneEvent ()
Destroys the event.
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Additional Inherited Members
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Protected Functions inherited from QGraphicsSceneEvent
QGraphicsSceneEvent (QGraphicsSceneEventPrivate &dd, Type type=None)
Constructs a generic graphics scene event.
Protected Variables inherited from QGraphicsSceneEvent
QScopedPointer< QGraphicsSceneEventPrivate > d_ptr
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Detailed Description
The QGraphicsSceneHoverEvent class provides hover events in the graphics view framework.
Since
4.2
When a QGraphicsView receives a QHoverEvent event, it translates it into QGraphicsSceneHoverEvent. The event is then forwarded to the QGraphicsScene associated with the view.
See also
QGraphicsSceneMouseEvent, QGraphicsSceneContextMenuEvent, QGraphicsSceneWheelEvent, QHoverEvent
Definition at line 195 of file qgraphicssceneevent.h.
Constructors and Destructors
QGraphicsSceneHoverEvent()
QGraphicsSceneHoverEvent::QGraphicsSceneHoverEvent (Type type = None)
Constructs a graphics scene hover event of the specified type.
Warning
This function is not part of the public interface.
Definition at line 1043 of file qgraphicssceneevent.cpp.
     : QGraphicsSceneEvent(*new QGraphicsSceneHoverEventPrivate, type)
 {
 }
~QGraphicsSceneHoverEvent()
QGraphicsSceneHoverEvent::~QGraphicsSceneHoverEvent ()
Destroys the event.
Definition at line 1051 of file qgraphicssceneevent.cpp.
 {
 }
Functions
lastPos()
QPointF QGraphicsSceneHoverEvent::lastPos () const
Returns the last recorded mouse cursor position in item coordinates.
Since
4.4
See also
lastScenePos(), lastScreenPos(), pos()
Definition at line 1149 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent().
 {
     Q_D(const QGraphicsSceneHoverEvent);
     return d->lastPos;
 }
lastScenePos()
QPointF QGraphicsSceneHoverEvent::lastScenePos () const
Returns the last recorded, the scene coordinates of the previous mouse or hover event received by the view, that created the event mouse cursor position in scene coordinates.
Since
4.4
See also
lastPos(), lastScreenPos(), scenePos()
Definition at line 1176 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsScenePrivate::sendHoverEvent().
 {
     Q_D(const QGraphicsSceneHoverEvent);
     return d->lastScenePos;
 }
lastScreenPos()
QPoint QGraphicsSceneHoverEvent::lastScreenPos () const
Returns the last recorded mouse cursor position in screen coordinates.
Since
4.4
The last recorded position is the position of the previous mouse or hover event received by the view that created the event.
See also
lastPos(), lastScenePos(), screenPos()
Definition at line 1203 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), and QGraphicsScenePrivate::sendHoverEvent().
 {
     Q_D(const QGraphicsSceneHoverEvent);
     return d->lastScreenPos;
 }
modifiers()
Qt::KeyboardModifiers QGraphicsSceneHoverEvent::modifiers () const
Returns the keyboard modifiers at the moment the hover event was sent.
Since
4.4
Definition at line 1226 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QTextControl::processEvent(), QGraphicsScenePrivate::sendHoverEvent(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), and setModifiers().
 {
     Q_D(const QGraphicsSceneHoverEvent);
     return d->modifiers;
 }
pos()
QPointF QGraphicsSceneHoverEvent::pos () const
Returns the position of the mouse cursor in item coordinates at the moment the hover event was sent.
See also
scenePos(), screenPos()
Definition at line 1061 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsProxyWidget::hoverMoveEvent(), QTextControl::processEvent(), QGraphicsItemPrivate::remapItemPos(), QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent(), setLastPos(), setLastScenePos(), setLastScreenPos(), setPos(), setScenePos(), setScreenPos(), and QGraphicsWidgetPrivate::windowFrameHoverMoveEvent().
 {
     Q_D(const QGraphicsSceneHoverEvent);
     return d->pos;
 }
scenePos()
QPointF QGraphicsSceneHoverEvent::scenePos () const
Returns the position of the mouse cursor in scene coordinates at the moment the hover event was sent.
See also
pos(), screenPos()
Definition at line 1089 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsScenePrivate::dispatchHoverEvent(), QGraphicsScene::event(), and QGraphicsScenePrivate::sendHoverEvent().
 {
     Q_D(const QGraphicsSceneHoverEvent);
     return d->scenePos;
 }
screenPos()
QPoint QGraphicsSceneHoverEvent::screenPos () const
Returns the position of the mouse cursor in screen coordinates at the moment the hover event was sent.
See also
pos(), scenePos()
Definition at line 1117 of file qgraphicssceneevent.cpp.
Referenced by cloneEvent(), QGraphicsScenePrivate::dispatchHoverEvent(), QTextControl::processEvent(), QGraphicsScenePrivate::sendHoverEvent(), and QGraphicsProxyWidgetPrivate::sendWidgetMouseEvent().
 {
     Q_D(const QGraphicsSceneHoverEvent);
     return d->screenPos;
 }
setLastPos()
void QGraphicsSceneHoverEvent::setLastPos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 1158 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), and cloneEvent().
 {
     Q_D(QGraphicsSceneHoverEvent);
     d->lastPos = pos;
 }
setLastScenePos()
void QGraphicsSceneHoverEvent::setLastScenePos (const QPointF & pos)
Warning
This function is not part of the public interface.
Definition at line 1185 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), and cloneEvent().
 {
     Q_D(QGraphicsSceneHoverEvent);
     d->lastScenePos = pos;
 }
setLastScreenPos()
void QGraphicsSceneHoverEvent::setLastScreenPos (const QPoint & pos)
Warning
This function is not part of the public interface.
Definition at line 1212 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), and cloneEvent().
 {
     Q_D(QGraphicsSceneHoverEvent);
     d->lastScreenPos = pos;
 }
setModifiers()
void QGraphicsSceneHoverEvent::setModifiers (Qt::KeyboardModifiers modifiers)
Sets the modifiers for the current hover event to modifiers.
Warning
This function is not part of the public interface.
Definition at line 1241 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), and cloneEvent().
 {
     Q_D(QGraphicsSceneHoverEvent);
     d->modifiers = modifiers;
 }
setPos()
void QGraphicsSceneHoverEvent::setPos (const QPointF & point)
Sets the position associated with the hover event to the given point in item coordinates.
Warning
This function is not part of the public interface.
Definition at line 1077 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), cloneEvent(), and QGraphicsItemPrivate::remapItemPos().
 {
     Q_D(QGraphicsSceneHoverEvent);
     d->pos = pos;
 }
setScenePos()
void QGraphicsSceneHoverEvent::setScenePos (const QPointF & point)
Sets the position associated with the hover event to the given point in scene coordinates.
Warning
This function is not part of the public interface.
Definition at line 1105 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), cloneEvent(), QGraphicsScenePrivate::enterModal(), and QGraphicsScenePrivate::leaveModal().
 {
     Q_D(QGraphicsSceneHoverEvent);
     d->scenePos = pos;
 }
setScreenPos()
void QGraphicsSceneHoverEvent::setScreenPos (const QPoint & point)
Sets the position associated with the hover event to the given point in screen coordinates.
Warning
This function is not part of the public interface.
Definition at line 1133 of file qgraphicssceneevent.cpp.
Referenced by _q_hoverFromMouseEvent(), and cloneEvent().
 {
     Q_D(QGraphicsSceneHoverEvent);
     d->screenPos = pos;
 }
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicssceneevent.h
/src/gui/graphicsview/qgraphicssceneevent.cpp