Qt 4.8: QLocalServerPrivate Class Reference
QLocalServerPrivate Class Reference
#include <qlocalserver_p.h>
Classes
struct Listener
Public Functions
void _q_onNewConnection ()
We have received a notification that we can read on the listen socket.
bool addListener ()
void closeServer ()
void init ()
bool listen (const QString &name)
QLocalServerPrivate ()
void setError (const QString &function)
void waitForNewConnection (int msec, bool *timedOut)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static bool removeServer (const QString &name)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
QWinEventNotifier * connectionEventNotifier
QAbstractSocket::SocketError error
QString errorString
HANDLE eventHandle
QString fullServerName
QList< Listener > listeners
int maxPendingConnections
QQueue< QLocalSocket * > pendingConnections
QString serverName
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 74 of file qlocalserver_p.h.
Constructors and Destructors
QLocalServerPrivate()
QLocalServerPrivate::QLocalServerPrivate () inline
Definition at line 79 of file qlocalserver_p.h.
                           :
 #if !defined(QT_LOCALSOCKET_TCP) && !defined(Q_OS_WIN)
             listenSocket(-1), socketNotifier(0),
 #endif
             maxPendingConnections(30), error(QAbstractSocket::UnknownSocketError)
     {
     }
Functions
_q_onNewConnection()
void QLocalServerPrivate::_q_onNewConnection ()
We have received a notification that we can read on the listen socket.
Warning
This function is not part of the public interface.
Accept the new socket.
Definition at line 99 of file qlocalserver_tcp.cpp.
Referenced by addListener(), init(), and QLocalServerPrivate().
 {
     Q_Q(QLocalServer);
     QTcpSocket* tcpSocket = tcpServer.nextPendingConnection();
     if (!tcpSocket) {
         qWarning("QLocalServer: no pending connection");
         return;
     }
     tcpSocket->setParent(q);
     const quintptr socketDescriptor = tcpSocket->socketDescriptor();
     q->incomingConnection(socketDescriptor);
 }
addListener()
bool QLocalServerPrivate::addListener ()
Definition at line 58 of file qlocalserver_win.cpp.
 {
     // The object must not change its address once the
     // contained OVERLAPPED struct is passed to Windows.
     listeners << Listener();
     Listener &listener = listeners.last();
     listener.handle = CreateNamedPipe(
                  (const wchar_t *)fullServerName.utf16(), // pipe name
                  PIPE_ACCESS_DUPLEX | FILE_FLAG_OVERLAPPED,       // read/write access
                  PIPE_TYPE_BYTE |          // byte type pipe
                  PIPE_READMODE_BYTE |      // byte-read mode
                  PIPE_WAIT,                // blocking mode
                  PIPE_UNLIMITED_INSTANCES, // max. instances
                  BUFSIZE,                  // output buffer size
                  BUFSIZE,                  // input buffer size
                  3000,                     // client time-out
                  NULL);
     if (listener.handle == INVALID_HANDLE_VALUE) {
         setError(QLatin1String("QLocalServerPrivate::addListener"));
         listeners.removeLast();
         return false;
     }
     memset(&listener.overlapped, 0, sizeof(listener.overlapped));
     listener.overlapped.hEvent = eventHandle;
     if (!ConnectNamedPipe(listener.handle, &listener.overlapped)) {
         switch (GetLastError()) {
         case ERROR_IO_PENDING:
             listener.connected = false;
             break;
         case ERROR_PIPE_CONNECTED:
             listener.connected = true;
             SetEvent(eventHandle);
             break;
         default:
             CloseHandle(listener.handle);
             setError(QLatin1String("QLocalServerPrivate::addListener"));
             listeners.removeLast();
             return false;
         }
     } else {
         Q_ASSERT_X(false, "QLocalServerPrivate::addListener", "The impossible happened");
         SetEvent(eventHandle);
     }
     return true;
 }
closeServer()
void QLocalServerPrivate::closeServer ()
Warning
This function is not part of the public interface.
See also
QLocalServer::closeServer()
Definition at line 81 of file qlocalserver_tcp.cpp.
Referenced by addListener(), and QLocalServerPrivate().
 {
     QSettings settings(QLatin1String("Trolltech"), QLatin1String("Qt"));
     if (fullServerName == QLatin1String("QLocalServer"))
         settings.setValue(fullServerName, QVariant());
     else
         settings.remove(fullServerName);
     tcpServer.close();
 }
init()
void QLocalServerPrivate::init ()
Definition at line 53 of file qlocalserver_tcp.cpp.
Referenced by addListener(), and QLocalServerPrivate().
 {
     Q_Q(QLocalServer);
     q->connect(&tcpServer, SIGNAL(newConnection()), SLOT(_q_onNewConnection()));
 }
listen()
bool QLocalServerPrivate::listen (const QString & name)
Definition at line 59 of file qlocalserver_tcp.cpp.
Referenced by addListener(), and QLocalServerPrivate().
 {
     if (!tcpServer.listen(QHostAddress::LocalHost))
         return false;
     const QLatin1String prefix("QLocalServer/");
     if (requestedServerName.startsWith(prefix))
         fullServerName = requestedServerName;
     else
         fullServerName = prefix + requestedServerName;
     QSettings settings(QLatin1String("Trolltech"), QLatin1String("Qt"));
     if (settings.contains(fullServerName)) {
         qWarning("QLocalServer::listen: server name is already in use.");
         tcpServer.close();
         return false;
     }
     settings.setValue(fullServerName, tcpServer.serverPort());
     return true;
 }
removeServer()
bool QLocalServerPrivate::removeServer (const QString & name) static
Definition at line 113 of file qlocalserver_tcp.cpp.
Referenced by addListener(), QLocalServerPrivate(), and QLocalServer::removeServer().
 {
     const QLatin1String prefix("QLocalServer/");
     QString serverName;
     if (name.startsWith(prefix))
         serverName = name;
     else
         serverName = prefix + name;
     QSettings settings(QLatin1String("Trolltech"), QLatin1String("Qt"));
     if (settings.contains(serverName))
         settings.remove(serverName);
     return true;
 }
setError()
void QLocalServerPrivate::setError (const QString & function)
Definition at line 234 of file qlocalserver_unix.cpp.
Referenced by addListener().
 {
     if (EAGAIN == errno)
         return;
     switch (errno) {
     case EACCES:
         errorString = QLocalServer::tr("%1: Permission denied").arg(function);
         error = QAbstractSocket::SocketAccessError;
         break;
     case ELOOP:
     case ENOENT:
     case ENAMETOOLONG:
     case EROFS:
     case ENOTDIR:
         errorString = QLocalServer::tr("%1: Name error").arg(function);
         error = QAbstractSocket::HostNotFoundError;
         break;
     case EADDRINUSE:
         errorString = QLocalServer::tr("%1: Address in use").arg(function);
         error = QAbstractSocket::AddressInUseError;
         break;
     default:
         errorString = QLocalServer::tr("%1: Unknown error %2")
                       .arg(function).arg(errno);
         error = QAbstractSocket::UnknownSocketError;
 #if defined QLOCALSERVER_DEBUG
         qWarning() << errorString << "fullServerName:" << fullServerName;
 #endif
     }
 }
waitForNewConnection()
void QLocalServerPrivate::waitForNewConnection (int msec, bool * timedOut)
Definition at line 91 of file qlocalserver_tcp.cpp.
Referenced by addListener(), and QLocalServerPrivate().
 {
     if (pendingConnections.isEmpty())
         tcpServer.waitForNewConnection(msec, timedOut);
     else if (timedOut)
         *timedOut = false;
 }
Properties
connectionEventNotifier
QWinEventNotifier* QLocalServerPrivate::connectionEventNotifier
Definition at line 110 of file qlocalserver_p.h.
Referenced by addListener().
error
QAbstractSocket::SocketError QLocalServerPrivate::error
Definition at line 123 of file qlocalserver_p.h.
Referenced by addListener(), and setError().
errorString
QString QLocalServerPrivate::errorString
Definition at line 122 of file qlocalserver_p.h.
Referenced by addListener(), and setError().
eventHandle
HANDLE QLocalServerPrivate::eventHandle
Definition at line 109 of file qlocalserver_p.h.
Referenced by addListener().
fullServerName
QString QLocalServerPrivate::fullServerName
Definition at line 119 of file qlocalserver_p.h.
Referenced by addListener(), closeServer(), listen(), and setError().
listeners
QList<Listener> QLocalServerPrivate::listeners
Definition at line 108 of file qlocalserver_p.h.
Referenced by addListener().
maxPendingConnections
int QLocalServerPrivate::maxPendingConnections
Definition at line 120 of file qlocalserver_p.h.
Referenced by addListener().
pendingConnections
QQueue<QLocalSocket*> QLocalServerPrivate::pendingConnections
Definition at line 121 of file qlocalserver_p.h.
Referenced by addListener(), and waitForNewConnection().
serverName
QString QLocalServerPrivate::serverName
Definition at line 118 of file qlocalserver_p.h.
Referenced by removeServer().
The documentation for this class was generated from the following files:
/src/network/socket/qlocalserver_p.h
/src/network/socket/qlocalserver_tcp.cpp
/src/network/socket/qlocalserver_unix.cpp
/src/network/socket/qlocalserver_win.cpp