Qt 4.8: QmlJSDebugger::LiveSelectionTool Class Reference
QmlJSDebugger::LiveSelectionTool Class Reference
#include <liveselectiontool.h>
Public Functions
void clear ()
void hoverMoveEvent (QMouseEvent *event)
void itemsAboutToRemoved (const QList< QGraphicsItem *> &)
void keyPressEvent (QKeyEvent *event)
void keyReleaseEvent (QKeyEvent *)
LiveSelectionTool (QDeclarativeViewInspector *editorView)
void mouseDoubleClickEvent (QMouseEvent *)
void mouseMoveEvent (QMouseEvent *event)
void mousePressEvent (QMouseEvent *event)
void mouseReleaseEvent (QMouseEvent *event)
void selectedItemsChanged (const QList< QGraphicsItem *> &itemList)
void selectUnderPoint (QMouseEvent *event)
void setRubberbandSelectionMode (bool value)
void setSelectOnlyContentItems (bool selectOnlyContentItems)
void wheelEvent (QWheelEvent *event)
~LiveSelectionTool ()
Public Functions inherited from QmlJSDebugger::AbstractLiveEditTool
AbstractLiveEditTool (QDeclarativeViewInspector *inspector)
QList< QGraphicsItem * > items () const
void leaveEvent (QEvent *)
QString titleForItem (QGraphicsItem *item)
bool topItemIsMovable (const QList< QGraphicsItem *> &itemList)
bool topItemIsResizeHandle (const QList< QGraphicsItem *> &itemList)
bool topSelectedItemIsMovable (const QList< QGraphicsItem *> &itemList)
void updateSelectedItems ()
virtual ~AbstractLiveEditTool ()
Public Functions inherited from QmlJSDebugger::AbstractTool
AbstractTool (AbstractViewInspector *inspector)
AbstractViewInspector * inspector () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void contextMenuElementHovered (QAction *action)
void contextMenuElementSelected ()
void repaintBoundingRects ()
Private Functions
bool alreadySelected (const QList< QGraphicsItem *> &itemList) const
void createContextMenu (const QList< QGraphicsItem *> &itemList, QPoint globalPos)
LiveSingleSelectionManipulator::SelectionType getSelectionType (Qt::KeyboardModifiers modifiers)
Properties
QList< QGraphicsItem * > m_contextMenuItemList
QTime m_mousePressTimer
LiveRubberBandSelectionManipulator m_rubberbandSelectionManipulator
bool m_rubberbandSelectionMode
QList< QWeakPointer< QGraphicsObject > > m_selectedItemList
LiveSelectionIndicator m_selectionIndicator
bool m_selectOnlyContentItems
LiveSingleSelectionManipulator m_singleSelectionManipulator
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QmlJSDebugger::AbstractLiveEditTool
static QList< QGraphicsObject * > toGraphicsObjectList (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * topMovableDeclarativeItem (const QList< QGraphicsItem *> &itemList)
static QGraphicsItem * topMovableGraphicsItem (const QList< QGraphicsItem *> &itemList)
static QDeclarativeItem * toQDeclarativeItem (QGraphicsItem *item)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QmlJSDebugger::AbstractLiveEditTool
QDeclarativeViewInspector * inspector () const
QGraphicsScene * scene () const
QDeclarativeView * view () const
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 60 of file liveselectiontool.h.
Constructors and Destructors
LiveSelectionTool()
QmlJSDebugger::LiveSelectionTool::LiveSelectionTool (QDeclarativeViewInspector * editorView)
Definition at line 62 of file liveselectiontool.cpp.
                                                                           :
     AbstractLiveEditTool(editorView),
     m_rubberbandSelectionMode(false),
     m_rubberbandSelectionManipulator(
         QDeclarativeViewInspectorPrivate::get(editorView)->manipulatorLayer, editorView),
     m_singleSelectionManipulator(editorView),
     m_selectionIndicator(editorView,
         QDeclarativeViewInspectorPrivate::get(editorView)->manipulatorLayer),
     //m_resizeIndicator(editorView->manipulatorLayer()),
     m_selectOnlyContentItems(true)
 {
 }
~LiveSelectionTool()
QmlJSDebugger::LiveSelectionTool::~LiveSelectionTool ()
Definition at line 76 of file liveselectiontool.cpp.
 {
 }
Functions
alreadySelected()
bool QmlJSDebugger::LiveSelectionTool::alreadySelected (const QList< QGraphicsItem *> & itemList) const private
Definition at line 98 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved().
 {
     QDeclarativeViewInspectorPrivate *inspectorPrivate
             = QDeclarativeViewInspectorPrivate::get(inspector());
     const QList<QGraphicsItem*> selectedItems = inspectorPrivate->selectedItems();
     if (selectedItems.isEmpty())
         return false;
     foreach (QGraphicsItem *item, itemList)
         if (selectedItems.contains(item))
             return true;
     return false;
 }
clear()
void QmlJSDebugger::LiveSelectionTool::clear (void) virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 364 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved().
 {
 #ifndef QT_NO_CURSOR
     view()->setCursor(Qt::ArrowCursor);
 #endif
     m_rubberbandSelectionManipulator.clear(),
             m_singleSelectionManipulator.clear();
     m_selectionIndicator.clear();
     //m_resizeIndicator.clear();
 }
contextMenuElementHovered
void QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered (QAction * action) private slot
Definition at line 193 of file liveselectiontool.cpp.
Referenced by createContextMenu(), and itemsAboutToRemoved().
 {
     int itemListIndex = action->data().toInt();
     if (itemListIndex >= 0 && itemListIndex < m_contextMenuItemList.length()) {
         QGraphicsObject *item = m_contextMenuItemList.at(itemListIndex)->toGraphicsObject();
         QDeclarativeViewInspectorPrivate::get(inspector())->highlight(item);
     }
 }
contextMenuElementSelected
void QmlJSDebugger::LiveSelectionTool::contextMenuElementSelected () private slot
Definition at line 177 of file liveselectiontool.cpp.
Referenced by createContextMenu(), and itemsAboutToRemoved().
 {
     QAction *senderAction = static_cast<QAction*>(sender());
     int itemListIndex = senderAction->data().toInt();
     if (itemListIndex >= 0 && itemListIndex < m_contextMenuItemList.length()) {
         QPointF updatePt(0, 0);
         QGraphicsItem *item = m_contextMenuItemList.at(itemListIndex);
         m_singleSelectionManipulator.begin(updatePt);
         m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::InvertSelection,
                                             QList<QGraphicsItem*>() << item,
                                             false);
         m_singleSelectionManipulator.end(updatePt);
     }
 }
createContextMenu()
void QmlJSDebugger::LiveSelectionTool::createContextMenu (const QList< QGraphicsItem *> & itemList, QPoint globalPos) private
Definition at line 135 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved(), and mousePressEvent().
 {
     QMenu contextMenu;
     connect(&contextMenu, SIGNAL(hovered(QAction*)),
             this, SLOT(contextMenuElementHovered(QAction*)));
     m_contextMenuItemList = itemList;
     contextMenu.addAction(tr("Items"));
     contextMenu.addSeparator();
     int shortcutKey = Qt::Key_1;
     int i = 0;
     foreach (QGraphicsItem * const item, itemList) {
         QString itemTitle = titleForItem(item);
         QAction *elementAction = contextMenu.addAction(itemTitle, this,
                                                        SLOT(contextMenuElementSelected()));
         if (inspector()->selectedItems().contains(item)) {
             QFont boldFont = elementAction->font();
             boldFont.setBold(true);
             elementAction->setFont(boldFont);
         }
         elementAction->setData(i);
         if (shortcutKey <= Qt::Key_9) {
             elementAction->setShortcut(QKeySequence(shortcutKey));
             shortcutKey++;
         }
         ++i;
     }
     // add root item separately
     //    QString itemTitle = QString(tr("%1")).arg(titleForItem(view()->currentRootItem()));
     //    contextMenu.addAction(itemTitle, this, SLOT(contextMenuElementSelected()));
     //    m_contextMenuItemList.append(view()->currentRootItem());
     contextMenu.exec(globalPos);
     m_contextMenuItemList.clear();
 }
getSelectionType()
LiveSingleSelectionManipulator::SelectionType QmlJSDebugger::LiveSelectionTool::getSelectionType (Qt::KeyboardModifiers modifiers) private
Definition at line 85 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved(), and mousePressEvent().
 {
    LiveSingleSelectionManipulator::SelectionType selectionType
             = LiveSingleSelectionManipulator::ReplaceSelection;
     if (modifiers.testFlag(Qt::ControlModifier)) {
         selectionType = LiveSingleSelectionManipulator::RemoveFromSelection;
     } else if (modifiers.testFlag(Qt::ShiftModifier)) {
         selectionType = LiveSingleSelectionManipulator::AddToSelection;
     }
     return selectionType;
 }
hoverMoveEvent()
void QmlJSDebugger::LiveSelectionTool::hoverMoveEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 234 of file liveselectiontool.cpp.
Referenced by mouseDoubleClickEvent().
 {
 // ### commented out until move tool is re-enabled
 //    QList<QGraphicsItem*> itemList = view()->items(event->pos());
 //    if (!itemList.isEmpty() && !m_rubberbandSelectionMode) {
 //
 //        foreach (QGraphicsItem *item, itemList) {
 //            if (item->type() == Constants::ResizeHandleItemType) {
 //                ResizeHandleItem* resizeHandle = ResizeHandleItem::fromGraphicsItem(item);
 //                if (resizeHandle)
 //                    view()->changeTool(Constants::ResizeToolMode);
 //                return;
 //            }
 //        }
 //        if (topSelectedItemIsMovable(itemList))
 //            view()->changeTool(Constants::MoveToolMode);
 //    }
     QDeclarativeViewInspectorPrivate *inspectorPrivate
             = QDeclarativeViewInspectorPrivate::get(inspector());
     QList<QGraphicsItem*> selectableItemList = inspectorPrivate->selectableItems(event->pos());
     if (!selectableItemList.isEmpty()) {
         QGraphicsObject *item = selectableItemList.first()->toGraphicsObject();
         if (item)
             QDeclarativeViewInspectorPrivate::get(inspector())->highlight(item);
         return;
     }
     QDeclarativeViewInspectorPrivate::get(inspector())->clearHighlight();
 }
itemsAboutToRemoved()
void QmlJSDebugger::LiveSelectionTool::itemsAboutToRemoved (const QList< QGraphicsItem *> &) inline virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 77 of file liveselectiontool.h.
 {}
keyPressEvent()
void QmlJSDebugger::LiveSelectionTool::keyPressEvent (QKeyEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 306 of file liveselectiontool.cpp.
Referenced by mouseDoubleClickEvent().
 {
     switch (event->key()) {
     case Qt::Key_Left:
     case Qt::Key_Right:
     case Qt::Key_Up:
     case Qt::Key_Down:
         // disabled for now, cannot move stuff yet.
         //view()->changeTool(Constants::MoveToolMode);
         //view()->currentTool()->keyPressEvent(event);
         break;
     }
 }
keyReleaseEvent()
void QmlJSDebugger::LiveSelectionTool::keyReleaseEvent (QKeyEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 74 of file liveselectiontool.h.
 {}
mouseDoubleClickEvent()
void QmlJSDebugger::LiveSelectionTool::mouseDoubleClickEvent (QMouseEvent *) inline virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 71 of file liveselectiontool.h.
 {}
mouseMoveEvent()
void QmlJSDebugger::LiveSelectionTool::mouseMoveEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 202 of file liveselectiontool.cpp.
 {
     if (m_singleSelectionManipulator.isActive()) {
         QPointF mouseMovementVector = m_singleSelectionManipulator.beginPoint() - event->pos();
         if ((mouseMovementVector.toPoint().manhattanLength() > Constants::DragStartDistance)
                 && (m_mousePressTimer.elapsed() > Constants::DragStartTime))
         {
             m_singleSelectionManipulator.end(event->pos());
             //view()->changeToMoveTool(m_singleSelectionManipulator.beginPoint());
             return;
         }
     } else if (m_rubberbandSelectionManipulator.isActive()) {
         QPointF mouseMovementVector = m_rubberbandSelectionManipulator.beginPoint() - event->pos();
         if ((mouseMovementVector.toPoint().manhattanLength() > Constants::DragStartDistance)
                 && (m_mousePressTimer.elapsed() > Constants::DragStartTime)) {
             m_rubberbandSelectionManipulator.update(event->pos());
             if (event->modifiers().testFlag(Qt::ControlModifier))
                 m_rubberbandSelectionManipulator.select(
                             LiveRubberBandSelectionManipulator::RemoveFromSelection);
             else if (event->modifiers().testFlag(Qt::ShiftModifier))
                 m_rubberbandSelectionManipulator.select(
                             LiveRubberBandSelectionManipulator::AddToSelection);
             else
                 m_rubberbandSelectionManipulator.select(
                             LiveRubberBandSelectionManipulator::ReplaceSelection);
         }
     }
 }
mousePressEvent()
void QmlJSDebugger::LiveSelectionTool::mousePressEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 114 of file liveselectiontool.cpp.
 {
     QDeclarativeViewInspectorPrivate *inspectorPrivate
             = QDeclarativeViewInspectorPrivate::get(inspector());
     QList<QGraphicsItem*> itemList = inspectorPrivate->selectableItems(event->pos());
     LiveSingleSelectionManipulator::SelectionType selectionType = getSelectionType(event->modifiers());
     if (event->buttons() & Qt::LeftButton) {
         m_mousePressTimer.start();
         if (m_rubberbandSelectionMode) {
             m_rubberbandSelectionManipulator.begin(event->pos());
         } else {
             m_singleSelectionManipulator.begin(event->pos());
             m_singleSelectionManipulator.select(selectionType, m_selectOnlyContentItems);
         }
     } else if (event->buttons() & Qt::RightButton) {
         createContextMenu(itemList, event->globalPos());
     }
 }
mouseReleaseEvent()
void QmlJSDebugger::LiveSelectionTool::mouseReleaseEvent (QMouseEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 266 of file liveselectiontool.cpp.
 {
     if (m_singleSelectionManipulator.isActive()) {
         m_singleSelectionManipulator.end(event->pos());
     }
     else if (m_rubberbandSelectionManipulator.isActive()) {
         QPointF mouseMovementVector = m_rubberbandSelectionManipulator.beginPoint() - event->pos();
         if (mouseMovementVector.toPoint().manhattanLength() < Constants::DragStartDistance) {
             m_singleSelectionManipulator.begin(event->pos());
             if (event->modifiers().testFlag(Qt::ControlModifier))
                 m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::RemoveFromSelection,
                                                     m_selectOnlyContentItems);
             else if (event->modifiers().testFlag(Qt::ShiftModifier))
                 m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::AddToSelection,
                                                     m_selectOnlyContentItems);
             else
                 m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::InvertSelection,
                                                     m_selectOnlyContentItems);
             m_singleSelectionManipulator.end(event->pos());
         } else {
             m_rubberbandSelectionManipulator.update(event->pos());
             if (event->modifiers().testFlag(Qt::ControlModifier))
                 m_rubberbandSelectionManipulator.select(
                             LiveRubberBandSelectionManipulator::RemoveFromSelection);
             else if (event->modifiers().testFlag(Qt::ShiftModifier))
                 m_rubberbandSelectionManipulator.select(
                             LiveRubberBandSelectionManipulator::AddToSelection);
             else
                 m_rubberbandSelectionManipulator.select(
                             LiveRubberBandSelectionManipulator::ReplaceSelection);
             m_rubberbandSelectionManipulator.end();
         }
     }
 }
repaintBoundingRects
void QmlJSDebugger::LiveSelectionTool::repaintBoundingRects () private slot
Definition at line 403 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved(), and selectedItemsChanged().
 {
     m_selectionIndicator.setItems(m_selectedItemList);
 }
selectedItemsChanged()
void QmlJSDebugger::LiveSelectionTool::selectedItemsChanged (const QList< QGraphicsItem *> & itemList) virtual
Implements QmlJSDebugger::AbstractLiveEditTool.
Definition at line 375 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved().
 {
     foreach (const QWeakPointer<QGraphicsObject> &obj, m_selectedItemList) {
         if (!obj.isNull()) {
             disconnect(obj.data(), SIGNAL(xChanged()), this, SLOT(repaintBoundingRects()));
             disconnect(obj.data(), SIGNAL(yChanged()), this, SLOT(repaintBoundingRects()));
             disconnect(obj.data(), SIGNAL(widthChanged()), this, SLOT(repaintBoundingRects()));
             disconnect(obj.data(), SIGNAL(heightChanged()), this, SLOT(repaintBoundingRects()));
             disconnect(obj.data(), SIGNAL(rotationChanged()), this, SLOT(repaintBoundingRects()));
         }
     }
     QList<QGraphicsObject*> objects = toGraphicsObjectList(itemList);
     m_selectedItemList.clear();
     foreach (QGraphicsObject *obj, objects) {
         m_selectedItemList.append(obj);
         connect(obj, SIGNAL(xChanged()), this, SLOT(repaintBoundingRects()));
         connect(obj, SIGNAL(yChanged()), this, SLOT(repaintBoundingRects()));
         connect(obj, SIGNAL(widthChanged()), this, SLOT(repaintBoundingRects()));
         connect(obj, SIGNAL(heightChanged()), this, SLOT(repaintBoundingRects()));
         connect(obj, SIGNAL(rotationChanged()), this, SLOT(repaintBoundingRects()));
     }
     m_selectionIndicator.setItems(m_selectedItemList);
     //m_resizeIndicator.setItems(toGraphicsObjectList(itemList));
 }
selectUnderPoint()
void QmlJSDebugger::LiveSelectionTool::selectUnderPoint (QMouseEvent * event)
Definition at line 408 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved().
 {
     m_singleSelectionManipulator.begin(event->pos());
     if (event->modifiers().testFlag(Qt::ControlModifier))
         m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::RemoveFromSelection,
                                             m_selectOnlyContentItems);
     else if (event->modifiers().testFlag(Qt::ShiftModifier))
         m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::AddToSelection,
                                             m_selectOnlyContentItems);
     else
         m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::InvertSelection,
                                             m_selectOnlyContentItems);
     m_singleSelectionManipulator.end(event->pos());
 }
setRubberbandSelectionMode()
void QmlJSDebugger::LiveSelectionTool::setRubberbandSelectionMode (bool value)
Definition at line 80 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved().
 {
     m_rubberbandSelectionMode = value;
 }
setSelectOnlyContentItems()
void QmlJSDebugger::LiveSelectionTool::setSelectOnlyContentItems (bool selectOnlyContentItems)
Definition at line 359 of file liveselectiontool.cpp.
Referenced by itemsAboutToRemoved().
 {
     m_selectOnlyContentItems = selectOnlyContentItems;
 }
wheelEvent()
void QmlJSDebugger::LiveSelectionTool::wheelEvent (QWheelEvent * event) virtual
Implements QmlJSDebugger::AbstractTool.
Definition at line 320 of file liveselectiontool.cpp.
Referenced by keyReleaseEvent().
 {
     if (event->orientation() == Qt::Horizontal || m_rubberbandSelectionMode)
         return;
     QDeclarativeViewInspectorPrivate *inspectorPrivate
             = QDeclarativeViewInspectorPrivate::get(inspector());
     QList<QGraphicsItem*> itemList = inspectorPrivate->selectableItems(event->pos());
     if (itemList.isEmpty())
         return;
     int selectedIdx = 0;
     if (!inspector()->selectedItems().isEmpty()) {
         selectedIdx = itemList.indexOf(inspector()->selectedItems().first());
         if (selectedIdx >= 0) {
             if (event->delta() > 0) {
                 selectedIdx++;
                 if (selectedIdx == itemList.length())
                     selectedIdx = 0;
             } else if (event->delta() < 0) {
                 selectedIdx--;
                 if (selectedIdx == -1)
                     selectedIdx = itemList.length() - 1;
             }
         } else {
             selectedIdx = 0;
         }
     }
     QPointF updatePt(0, 0);
     m_singleSelectionManipulator.begin(updatePt);
     m_singleSelectionManipulator.select(LiveSingleSelectionManipulator::ReplaceSelection,
                                         QList<QGraphicsItem*>() << itemList.at(selectedIdx),
                                         false);
     m_singleSelectionManipulator.end(updatePt);
 }
Properties
m_contextMenuItemList
QList<QGraphicsItem*> QmlJSDebugger::LiveSelectionTool::m_contextMenuItemList private
Definition at line 115 of file liveselectiontool.h.
Referenced by contextMenuElementHovered(), contextMenuElementSelected(), and createContextMenu().
m_mousePressTimer
QTime QmlJSDebugger::LiveSelectionTool::m_mousePressTimer private
Definition at line 110 of file liveselectiontool.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
m_rubberbandSelectionManipulator
LiveRubberBandSelectionManipulator QmlJSDebugger::LiveSelectionTool::m_rubberbandSelectionManipulator private
Definition at line 106 of file liveselectiontool.h.
Referenced by clear(), mouseMoveEvent(), mousePressEvent(), and mouseReleaseEvent().
m_rubberbandSelectionMode
bool QmlJSDebugger::LiveSelectionTool::m_rubberbandSelectionMode private
Definition at line 105 of file liveselectiontool.h.
Referenced by mousePressEvent(), setRubberbandSelectionMode(), and wheelEvent().
m_selectedItemList
QList<QWeakPointer<QGraphicsObject> > QmlJSDebugger::LiveSelectionTool::m_selectedItemList private
Definition at line 113 of file liveselectiontool.h.
Referenced by repaintBoundingRects(), and selectedItemsChanged().
m_selectionIndicator
LiveSelectionIndicator QmlJSDebugger::LiveSelectionTool::m_selectionIndicator private
Definition at line 108 of file liveselectiontool.h.
Referenced by clear(), repaintBoundingRects(), and selectedItemsChanged().
m_selectOnlyContentItems
bool QmlJSDebugger::LiveSelectionTool::m_selectOnlyContentItems private
Definition at line 111 of file liveselectiontool.h.
Referenced by mousePressEvent(), mouseReleaseEvent(), selectUnderPoint(), and setSelectOnlyContentItems().
m_singleSelectionManipulator
LiveSingleSelectionManipulator QmlJSDebugger::LiveSelectionTool::m_singleSelectionManipulator private
Definition at line 107 of file liveselectiontool.h.
Referenced by clear(), contextMenuElementSelected(), mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), selectUnderPoint(), and wheelEvent().
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/editor/liveselectiontool.h
/src/plugins/qmltooling/qmldbg_inspector/editor/liveselectiontool.cpp