Qt 4.8: QDeclarativeAbstractAnimation Class Reference
QDeclarativeAbstractAnimation Class Reference abstract
#include <qdeclarativeanimation_p.h>
Public Types
enum Loops { Infinite = -2 }
enum TransitionDirection { Forward, Backward }
Public Slots
void complete ()
void pause ()
void restart ()
void resume ()
void start ()
void stop ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void alwaysRunToEndChanged (bool)
void completed ()
void loopCountChanged (int)
void pausedChanged (bool)
void runningChanged (bool)
void started ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool alwaysRunToEnd () const
void classBegin ()
Invoked after class creation, but before any properties have been set.
void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
int currentTime ()
QDeclarativeAnimationGroup * group () const
bool isPaused () const
bool isRunning () const
int loops () const
QDeclarativeAbstractAnimation (QObject *parent=0)
virtual QAbstractAnimation * qtAnimation ()=0
void setAlwaysRunToEnd (bool)
void setCurrentTime (int)
void setDefaultTarget (const QDeclarativeProperty &)
void setDisableUserControl ()
void setGroup (QDeclarativeAnimationGroup *)
void setLoops (int)
void setPaused (bool)
void setRunning (bool)
virtual void transition (QDeclarativeStateActions &actions, QDeclarativeProperties &modified, TransitionDirection direction)
virtual ~QDeclarativeAbstractAnimation ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativePropertyValueSource
QDeclarativePropertyValueSource ()
Constructs a QDeclarativePropertyValueSource.
virtual ~QDeclarativePropertyValueSource ()
Destroys the value source.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Protected Functions
QDeclarativeAbstractAnimation (QDeclarativeAbstractAnimationPrivate &dd, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void componentFinalized ()
void timelineComplete ()
Private Functions
void notifyRunningChanged (bool running)
virtual void setTarget (const QDeclarativeProperty &)
Set the target property for the value source.
Properties
bool alwaysRunToEnd
int loops
bool paused
bool running
Friends
class QDeclarativeBehavior
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 66 of file qdeclarativeanimation_p.h.
Enumerations
Loops
enum QDeclarativeAbstractAnimation::Loops
Enumerator
Infinite
Definition at line 84 of file qdeclarativeanimation_p.h.
 { Infinite = -2 };
TransitionDirection
enum QDeclarativeAbstractAnimation::TransitionDirection
Enumerator
Forward
Backward
Definition at line 128 of file qdeclarativeanimation_p.h.
 { Forward, Backward };
Constructors and Destructors
QDeclarativeAbstractAnimation() [1/2]
QDeclarativeAbstractAnimation::QDeclarativeAbstractAnimation (QObject * parent = 0)
Definition at line 90 of file qdeclarativeanimation.cpp.
 : QObject(*(new QDeclarativeAbstractAnimationPrivate), parent)
 {
 }
~QDeclarativeAbstractAnimation()
QDeclarativeAbstractAnimation::~QDeclarativeAbstractAnimation () virtual
Definition at line 95 of file qdeclarativeanimation.cpp.
 {
 }
QDeclarativeAbstractAnimation() [2/2]
QDeclarativeAbstractAnimation::QDeclarativeAbstractAnimation (QDeclarativeAbstractAnimationPrivate & dd, QObject * parent) protected
Definition at line 99 of file qdeclarativeanimation.cpp.
 : QObject(dd, parent)
 {
 }
Functions
alwaysRunToEnd()
bool QDeclarativeAbstractAnimation::alwaysRunToEnd () const
Referenced by componentFinalized().
alwaysRunToEndChanged
void QDeclarativeAbstractAnimation::alwaysRunToEndChanged (bool) signal
Referenced by setAlwaysRunToEnd().
classBegin()
void QDeclarativeAbstractAnimation::classBegin () virtual
Invoked after class creation, but before any properties have been set.
Implements QDeclarativeParserStatus.
Definition at line 285 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     d->componentComplete = false;
 }
complete
void QDeclarativeAbstractAnimation::complete () slot
Definition at line 531 of file qdeclarativeanimation.cpp.
 {
     if (isRunning()) {
          qtAnimation()->setCurrentTime(qtAnimation()->duration());
     }
 }
completed
void QDeclarativeAbstractAnimation::completed () signal
Referenced by setRunning().
componentComplete()
void QDeclarativeAbstractAnimation::componentComplete () virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 291 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     d->componentComplete = true;
 }
componentFinalized
void QDeclarativeAbstractAnimation::componentFinalized () private slot
Definition at line 297 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     if (d->running) {
         d->running = false;
         setRunning(true);
     }
 }
currentTime()
int QDeclarativeAbstractAnimation::currentTime ()
Definition at line 388 of file qdeclarativeanimation.cpp.
 {
     return qtAnimation()->currentLoopTime();
 }
group()
QDeclarativeAnimationGroup * QDeclarativeAbstractAnimation::group () const
Definition at line 398 of file qdeclarativeanimation.cpp.
 {
     Q_D(const QDeclarativeAbstractAnimation);
     return d->group;
 }
isPaused()
bool QDeclarativeAbstractAnimation::isPaused () const
Definition at line 259 of file qdeclarativeanimation.cpp.
 {
     Q_D(const QDeclarativeAbstractAnimation);
     return d->paused;
 }
isRunning()
bool QDeclarativeAbstractAnimation::isRunning () const
Definition at line 141 of file qdeclarativeanimation.cpp.
Referenced by complete().
 {
     Q_D(const QDeclarativeAbstractAnimation);
     return d->running;
 }
loopCountChanged
void QDeclarativeAbstractAnimation::loopCountChanged (int) signal
Referenced by setLoops().
loops()
int QDeclarativeAbstractAnimation::loops () const
Referenced by setAlwaysRunToEnd(), and setLoops().
notifyRunningChanged()
void QDeclarativeAbstractAnimation::notifyRunningChanged (bool running) private
Definition at line 148 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     if (d->disableUserControl && d->running != running) {
         d->running = running;
         emit runningChanged(running);
     }
 }
pause
void QDeclarativeAbstractAnimation::pause () slot
Definition at line 446 of file qdeclarativeanimation.cpp.
 {
     setPaused(true);
 }
pausedChanged
void QDeclarativeAbstractAnimation::pausedChanged (bool) signal
Referenced by setPaused().
qtAnimation()
virtual QAbstractAnimation* QDeclarativeAbstractAnimation::qtAnimation () pure virtual
Implemented in QDeclarativeAnchorAnimation, QDeclarativeParentAnimation, QDeclarativeParallelAnimation, QDeclarativeSequentialAnimation, QDeclarativePropertyAnimation, QDeclarativePropertyAction, QDeclarativeScriptAction, QDeclarativePauseAnimation, QDeclarativeSpringAnimation, and QDeclarativeSmoothedAnimation.
Referenced by QDeclarativeTransitionPrivate::append_animation(), QDeclarativeAnimationGroupPrivate::append_animation(), QDeclarativeAnimationGroupPrivate::clear_animation(), QDeclarativeTransitionPrivate::clear_animations(), complete(), currentTime(), setCurrentTime(), setLoops(), setPaused(), setRunning(), and timelineComplete().
restart
void QDeclarativeAbstractAnimation::restart () slot
Definition at line 504 of file qdeclarativeanimation.cpp.
 {
     stop();
     start();
 }
resume
void QDeclarativeAbstractAnimation::resume () slot
Definition at line 461 of file qdeclarativeanimation.cpp.
 {
     setPaused(false);
 }
runningChanged
void QDeclarativeAbstractAnimation::runningChanged (bool) signal
Referenced by notifyRunningChanged(), and setRunning().
setAlwaysRunToEnd()
void QDeclarativeAbstractAnimation::setAlwaysRunToEnd (bool f)
Definition at line 331 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     if (d->alwaysRunToEnd == f)
         return;
     d->alwaysRunToEnd = f;
     emit alwaysRunToEndChanged(f);
 }
setCurrentTime()
void QDeclarativeAbstractAnimation::setCurrentTime (int time)
Definition at line 393 of file qdeclarativeanimation.cpp.
 {
     qtAnimation()->setCurrentTime(time);
 }
setDefaultTarget()
void QDeclarativeAbstractAnimation::setDefaultTarget (const QDeclarativeProperty & p)
Definition at line 552 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     d->defaultProperty = p;
 }
setDisableUserControl()
void QDeclarativeAbstractAnimation::setDisableUserControl ()
Definition at line 563 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeTransitionPrivate::append_animation().
 {
     Q_D(QDeclarativeAbstractAnimation);
     d->disableUserControl = true;
 }
setGroup()
void QDeclarativeAbstractAnimation::setGroup (QDeclarativeAnimationGroup * g)
Definition at line 404 of file qdeclarativeanimation.cpp.
Referenced by QDeclarativeAnimationGroupPrivate::append_animation(), and QDeclarativeAnimationGroupPrivate::clear_animation().
 {
     Q_D(QDeclarativeAbstractAnimation);
     if (d->group == g)
         return;
     if (d->group)
         static_cast<QDeclarativeAnimationGroupPrivate *>(d->group->d_func())->animations.removeAll(this);
     d->group = g;
     if (d->group && !static_cast<QDeclarativeAnimationGroupPrivate *>(d->group->d_func())->animations.contains(this))
         static_cast<QDeclarativeAnimationGroupPrivate *>(d->group->d_func())->animations.append(this);
     //if (g) //if removed from a group, then the group should no longer be the parent
         setParent(g);
 }
setLoops()
void QDeclarativeAbstractAnimation::setLoops (int loops)
Definition at line 373 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     if (loops < 0)
         loops = -1;
     if (loops == d->loopCount)
         return;
     d->loopCount = loops;
     qtAnimation()->setLoopCount(loops);
     emit loopCountChanged(loops);
 }
setPaused()
void QDeclarativeAbstractAnimation::setPaused (bool p)
Definition at line 265 of file qdeclarativeanimation.cpp.
Referenced by pause(), and resume().
 {
     Q_D(QDeclarativeAbstractAnimation);
     if (d->paused == p)
         return;
     if (d->group || d->disableUserControl) {
         qmlInfo(this) << "setPaused() cannot be used on non-root animation nodes.";
         return;
     }
     d->paused = p;
     if (d->paused)
         qtAnimation()->pause();
     else
         qtAnimation()->resume();
     emit pausedChanged(d->paused);
 }
setRunning()
void QDeclarativeAbstractAnimation::setRunning (bool r)
Definition at line 187 of file qdeclarativeanimation.cpp.
Referenced by componentFinalized(), setTarget(), start(), stop(), and timelineComplete().
 {
     Q_D(QDeclarativeAbstractAnimation);
     if (!d->componentComplete) {
         d->running = r;
         if (r == false)
             d->avoidPropertyValueSourceStart = true;
         else if (!d->registered) {
             d->registered = true;
             QDeclarativeEnginePrivate *engPriv = QDeclarativeEnginePrivate::get(qmlEngine(this));
             engPriv->registerFinalizedParserStatusObject(this, this->metaObject()->indexOfSlot("componentFinalized()"));
         }
         return;
     }
     if (d->running == r)
         return;
     if (d->group || d->disableUserControl) {
         qmlInfo(this) << "setRunning() cannot be used on non-root animation nodes.";
         return;
     }
     d->running = r;
     if (d->running) {
         bool supressStart = false;
         if (d->alwaysRunToEnd && d->loopCount != 1
             && qtAnimation()->state() == QAbstractAnimation::Running) {
             //we've restarted before the final loop finished; restore proper loop count
             if (d->loopCount == -1)
                 qtAnimation()->setLoopCount(d->loopCount);
             else
                 qtAnimation()->setLoopCount(qtAnimation()->currentLoop() + d->loopCount);
             supressStart = true;    //we want the animation to continue, rather than restart
         }
         if (!d->connectedTimeLine) {
             QObject::connect(qtAnimation(), SIGNAL(finished()),
                              this, SLOT(timelineComplete()));
             d->connectedTimeLine = true;
         }
         if (!supressStart)
             d->commence();
         emit started();
     } else {
         if (d->alwaysRunToEnd) {
             if (d->loopCount != 1)
                 qtAnimation()->setLoopCount(qtAnimation()->currentLoop()+1);    //finish the current loop
         } else
             qtAnimation()->stop();
         emit completed();
     }
     emit runningChanged(d->running);
 }
setTarget()
void QDeclarativeAbstractAnimation::setTarget (const QDeclarativeProperty & property) private virtual
Set the target property for the value source.
This method will be called by the QML engine when assigning a value source.
Implements QDeclarativePropertyValueSource.
Definition at line 538 of file qdeclarativeanimation.cpp.
 {
     Q_D(QDeclarativeAbstractAnimation);
     d->defaultProperty = p;
     if (!d->avoidPropertyValueSourceStart)
         setRunning(true);
 }
start
void QDeclarativeAbstractAnimation::start () slot
Definition at line 431 of file qdeclarativeanimation.cpp.
Referenced by restart().
 {
     setRunning(true);
 }
started
void QDeclarativeAbstractAnimation::started () signal
Referenced by setRunning().
stop
void QDeclarativeAbstractAnimation::stop () slot
Definition at line 489 of file qdeclarativeanimation.cpp.
Referenced by restart().
 {
     setRunning(false);
 }
timelineComplete
void QDeclarativeAbstractAnimation::timelineComplete () private slot
Definition at line 578 of file qdeclarativeanimation.cpp.
Referenced by setRunning().
 {
     Q_D(QDeclarativeAbstractAnimation);
     setRunning(false);
     if (d->alwaysRunToEnd && d->loopCount != 1) {
         //restore the proper loopCount for the next run
         qtAnimation()->setLoopCount(d->loopCount);
     }
 }
transition()
void QDeclarativeAbstractAnimation::transition (QDeclarativeStateActions & actions, QDeclarativeProperties & modified, TransitionDirection direction) virtual
Reimplemented in QDeclarativeAnchorAnimation, QDeclarativeParentAnimation, QDeclarativeParallelAnimation, QDeclarativeSequentialAnimation, QDeclarativePropertyAnimation, QDeclarativePropertyAction, QDeclarativeScriptAction, QDeclarativeSpringAnimation, and QDeclarativeSmoothedAnimation.
Definition at line 569 of file qdeclarativeanimation.cpp.
 {
     Q_UNUSED(actions);
     Q_UNUSED(modified);
     Q_UNUSED(direction);
 }
Friends and Related Functions
QDeclarativeBehavior
friend class QDeclarativeBehavior friend
Definition at line 140 of file qdeclarativeanimation_p.h.
Properties
alwaysRunToEnd
bool QDeclarativeAbstractAnimation::alwaysRunToEnd private
Definition at line 76 of file qdeclarativeanimation_p.h.
loops
int QDeclarativeAbstractAnimation::loops private
Definition at line 77 of file qdeclarativeanimation_p.h.
paused
bool QDeclarativeAbstractAnimation::paused private
Definition at line 75 of file qdeclarativeanimation_p.h.
running
bool QDeclarativeAbstractAnimation::running private
Definition at line 74 of file qdeclarativeanimation_p.h.
Referenced by QDeclarativeAbstractAnimationPrivate::commence(), and notifyRunningChanged().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeanimation_p.h
/src/declarative/util/qdeclarativeanimation.cpp