Qt 4.8: QColormap Class Reference
QColormap Class Reference
#include <qcolormap.h>
Public Types
enum Mode { Direct, Indexed, Gray }
Public Functions
const QColor colorAt (uint pixel) const
const QVector< QColor > colormap () const
int depth () const
Mode mode () const
QColormap & operator= (const QColormap &colormap)
uint pixel (const QColor &color) const
QColormap (const QColormap &colormap)
int size () const
~QColormap ()
Static Public Functions
static void cleanup ()
static HPALETTE hPal ()
static void initialize ()
static QColormap instance (int screen=-1)
Private Functions
QColormap ()
Constructs a new colormap.
Properties
QColormapPrivate * d
Detailed Description
Definition at line 59 of file qcolormap.h.
Enumerations
Mode
enum QColormap::Mode
Enumerator
Direct
Indexed
Gray
Definition at line 62 of file qcolormap.h.
 { Direct, Indexed, Gray };
Constructors and Destructors
QColormap() [1/2]
QColormap::QColormap (const QColormap & colormap)
Definition at line 77 of file qcolormap_mac.cpp.
                                               :d (colormap.d)
 { d->ref.ref(); }
~QColormap()
QColormap::~QColormap ()
Definition at line 80 of file qcolormap_mac.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
QColormap() [2/2]
QColormap::QColormap () private
Constructs a new colormap.
Warning
This function is not part of the public interface.
Definition at line 74 of file qcolormap_mac.cpp.
                      : d(new QColormapPrivate)
 {}
Functions
cleanup()
void QColormap::cleanup () static
Definition at line 63 of file qcolormap_mac.cpp.
Referenced by qt_cleanup().
 {
     delete qt_mac_global_map;
     qt_mac_global_map = 0;
 }
colorAt()
const QColor QColormap::colorAt (uint pixel) const
Definition at line 102 of file qcolormap_mac.cpp.
Referenced by qt_conv16ToRgb(), and QApplicationPrivate::setSystemPalette().
 { return QColor(pixel); }
colormap()
const QVector< QColor > QColormap::colormap () const
Definition at line 105 of file qcolormap_mac.cpp.
Referenced by hPal(), and qt_conv16ToRgb().
 { return QVector<QColor>(); }
depth()
int QColormap::depth () const
Definition at line 89 of file qcolormap_mac.cpp.
Referenced by QPixmap::defaultDepth().
 {
     return 32;
 }
hPal()
HPALETTE QColormap::hPal () static
Definition at line 190 of file qcolormap_win.cpp.
Referenced by QGLContext::choosePixelFormat(), OLEColorToQColor(), QPixmapToIPicture(), and QtWndProc().
 { return screenMap ? screenMap->hpal : 0; }
initialize()
void QColormap::initialize () static
Definition at line 58 of file qcolormap_mac.cpp.
Referenced by init_display(), and qt_init().
 {
     qt_mac_global_map = new QColormap;
 }
instance()
QColormap QColormap::instance (int screen = -1) static
Definition at line 69 of file qcolormap_mac.cpp.
Referenced by QGLContext::choosePixelFormat(), QEgl::createSurface(), QPixmap::defaultDepth(), QX11PaintEngine::drawPixmap(), QX11PixmapData::fill(), QX11PixmapData::fromImage(), QColor::invalidate(), QApplication::isEffectEnabled(), QWidgetPrivate::mapFromGlobal(), QGLOverlayWidget::paintGL(), qt_transparent_pixel(), QApplicationPrivate::setSystemPalette(), QNativeImage::systemFormat(), QX11PixmapData::toImage(), QETWidget::translateCloseEvent(), QX11PaintEngine::updateBrush(), QX11PaintEngine::updatePen(), and QETWidget::updateRegion().
 {
     return *qt_mac_global_map;
 }
mode()
QColormap::Mode QColormap::mode () const
Definition at line 86 of file qcolormap_mac.cpp.
 { return QColormap::Direct; }
operator=()
QColormap & QColormap::operator= (const QColormap & colormap)
Definition at line 108 of file qcolormap_mac.cpp.
Referenced by hPal(), and qt_conv16ToRgb().
 { qAtomicAssign(d, colormap.d); return *this; }
pixel()
uint QColormap::pixel (const QColor & color) const
Definition at line 99 of file qcolormap_mac.cpp.
Referenced by QGLContext::choosePixelFormat(), QEgl::createSurface(), QX11PaintEngine::drawPixmap(), QX11PixmapData::fromImage(), QColor::invalidate(), QGLOverlayWidget::paintGL(), qt_conv16ToRgb(), qt_transparent_pixel(), QApplicationPrivate::setSystemPalette(), QX11PaintEngine::updateBrush(), and QX11PaintEngine::updatePen().
 { return color.rgba(); }
size()
int QColormap::size () const
Definition at line 94 of file qcolormap_mac.cpp.
 {
     return -1;
 }
Properties
d
QColormapPrivate* QColormap::d private
Definition at line 90 of file qcolormap.h.
Referenced by hPal(), operator=(), QColormap(), qt_conv16ToRgb(), and ~QColormap().
The documentation for this class was generated from the following files:
/src/gui/painting/qcolormap.h
/src/gui/painting/qcolormap_mac.cpp
/src/gui/painting/qcolormap_qpa.cpp
/src/gui/painting/qcolormap_qws.cpp
/src/gui/painting/qcolormap_win.cpp
/src/gui/painting/qcolormap_x11.cpp