Qt 4.8: QCalendarDateSectionValidator Class Reference
QCalendarDateSectionValidator Class Reference abstract
Public Types
enum Section { NextSection, ThisSection, PrevSection }
Public Functions
virtual QDate applyToDate (const QDate &date) const =0
virtual Section handleKey (int key)=0
QCalendarDateSectionValidator ()
virtual void setDate (const QDate &date)=0
virtual QString text () const =0
virtual QString text (const QDate &date, int repeat) const =0
virtual ~QCalendarDateSectionValidator ()
Public Variables
QLocale m_locale
Protected Functions
QString highlightString (const QString &str, int pos) const
Detailed Description
Definition at line 75 of file qcalendarwidget.cpp.
Enumerations
Section
enum QCalendarDateSectionValidator::Section
Enumerator
NextSection
ThisSection
PrevSection
Definition at line 79 of file qcalendarwidget.cpp.
                  {
         NextSection,
         ThisSection,
         PrevSection
     };
Constructors and Destructors
QCalendarDateSectionValidator()
QCalendarDateSectionValidator::QCalendarDateSectionValidator () inline
Definition at line 85 of file qcalendarwidget.cpp.
 {}
~QCalendarDateSectionValidator()
virtual QCalendarDateSectionValidator::~QCalendarDateSectionValidator () inline virtual
Definition at line 86 of file qcalendarwidget.cpp.
 {}
Functions
applyToDate()
virtual QDate QCalendarDateSectionValidator::applyToDate (const QDate & date) const pure virtual
Implemented in QCalendarYearValidator, QCalendarMonthValidator, and QCalendarDayValidator.
Referenced by QCalendarDateValidator::applyToDate(), and ~QCalendarDateSectionValidator().
handleKey()
virtual Section QCalendarDateSectionValidator::handleKey (int key) pure virtual
Implemented in QCalendarYearValidator, QCalendarMonthValidator, and QCalendarDayValidator.
Referenced by QCalendarDateValidator::handleKeyEvent(), and ~QCalendarDateSectionValidator().
highlightString()
QString QCalendarDateSectionValidator::highlightString (const QString & str, int pos) const protected
Definition at line 100 of file qcalendarwidget.cpp.
Referenced by QCalendarDayValidator::text(), QCalendarMonthValidator::text(), and QCalendarYearValidator::text().
 {
     if (pos == 0)
         return QLatin1String("<b>") + str + QLatin1String("</b>");
     int startPos = str.length() - pos;
     return str.mid(0, startPos) + QLatin1String("<b>") + str.mid(startPos, pos) + QLatin1String("</b>");
 }
setDate()
virtual void QCalendarDateSectionValidator::setDate (const QDate & date) pure virtual
Implemented in QCalendarYearValidator, QCalendarMonthValidator, and QCalendarDayValidator.
Referenced by QCalendarDateValidator::setInitialDate(), and ~QCalendarDateSectionValidator().
text() [1/2]
virtual QString QCalendarDateSectionValidator::text () const pure virtual
Implemented in QCalendarYearValidator, QCalendarMonthValidator, and QCalendarDayValidator.
Referenced by QCalendarDateValidator::currentText(), and ~QCalendarDateSectionValidator().
text() [2/2]
virtual QString QCalendarDateSectionValidator::text (const QDate & date, int repeat) const pure virtual
Implemented in QCalendarYearValidator, QCalendarMonthValidator, and QCalendarDayValidator.
Properties
m_locale
QLocale QCalendarDateSectionValidator::m_locale
Definition at line 93 of file qcalendarwidget.cpp.
Referenced by QCalendarDateValidator::setLocale(), QCalendarDayValidator::text(), and QCalendarMonthValidator::text().
The documentation for this class was generated from the following file:
/src/gui/widgets/qcalendarwidget.cpp