Qt 4.8: QVNCServer Class Reference
QVNCServer Class Reference
#include <qscreenvnc_p.h>
Public Types
enum ClientMsg {
SetPixelFormat = 0, FixColourMapEntries = 1, SetEncodings = 2, FramebufferUpdateRequest = 3,
KeyEvent = 4, PointerEvent = 5, ClientCutText = 6, SetPixelFormat = 0,
FixColourMapEntries = 1, SetEncodings = 2, FramebufferUpdateRequest = 3, KeyEvent = 4,
PointerEvent = 5, ClientCutText = 6
}
enum ClientMsg {
SetPixelFormat = 0, FixColourMapEntries = 1, SetEncodings = 2, FramebufferUpdateRequest = 3,
KeyEvent = 4, PointerEvent = 5, ClientCutText = 6, SetPixelFormat = 0,
FixColourMapEntries = 1, SetEncodings = 2, FramebufferUpdateRequest = 3, KeyEvent = 4,
PointerEvent = 5, ClientCutText = 6
}
enum ServerMsg { FramebufferUpdate = 0, SetColourMapEntries = 1, FramebufferUpdate = 0, SetColourMapEntries = 1 }
enum ServerMsg { FramebufferUpdate = 0, SetColourMapEntries = 1, FramebufferUpdate = 0, SetColourMapEntries = 1 }
Public Functions
int clientBytesPerPixel () const
int clientBytesPerPixel () const
QTcpSocket * clientSocket () const
QTcpSocket * clientSocket () const
void convertPixels (char *dst, const char *src, int count) const
void convertPixels (char *dst, const char *src, int count) const
QVNCDirtyMap * dirtyMap () const
QVNCDirtyMap * dirtyMap () const
bool doPixelConversion () const
bool doPixelConversion () const
bool hasClientCursor () const
bool isConnected () const
bool isConnected () const
QVNCServer (QVNCScreen *screen)
QVNCServer (QVNCScreen *screen, int id)
QVNCServer (QVNCScreen *screen)
QVNCServer (QVNCScreen *screen, int id)
QVNCScreen * screen () const
QVNCScreen * screen () const
QImage screenImage () const
QImage * screenImage () const
void setCursor (QVNCCursor *c)
void setDirty ()
void setDirty ()
void setDirtyCursor ()
void setDirtyCursor ()
void setRefreshRate (int rate)
void setRefreshRate (int rate)
~QVNCServer ()
~QVNCServer ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Types
enum ClientState {
Unconnected, Protocol, Init, Connected,
Unconnected, Protocol, Init, Connected
}
enum ClientState {
Unconnected, Protocol, Init, Connected,
Unconnected, Protocol, Init, Connected
}
Private Slots
void checkUpdate ()
void checkUpdate ()
void discardClient ()
void discardClient ()
void newConnection ()
void newConnection ()
void readClient ()
void readClient ()
Private Functions
void clientCutText ()
void clientCutText ()
void frameBufferUpdateRequest ()
void frameBufferUpdateRequest ()
void init (uint port)
void init (uint port)
void keyEvent ()
void keyEvent ()
bool pixelConversionNeeded () const
bool pixelConversionNeeded () const
void pointerEvent ()
void pointerEvent ()
void setEncodings ()
void setEncodings ()
void setPixelFormat ()
void setPixelFormat ()
Properties
Qt::MouseButtons buttons
QTcpSocket * client
QVNCCursor * cursor
int cutTextPending
bool dirtyCursor
QRfbEncoder * encoder
int encodingsPending
bool handleMsg
Qt::KeyboardModifiers keymod
quint8 msgType
bool needConversion
QRfbPixelFormat pixelFormat
QVNCClientCursor * qvnc_cursor
QVNCScreen * qvnc_screen
int refreshRate
bool sameEndian
QTcpServer * serverSocket
ClientState state
uint supportCopyRect: 1
uint supportCoRRE: 1
uint supportCursor: 1
uint supportDesktopSize: 1
uint supportHextile: 1
uint supportRRE: 1
uint supportZRLE: 1
bool swapBytes
QTimer * timer
bool wantUpdate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 431 of file qscreenvnc_p.h.
Enumerations
ClientMsg [1/2]
enum QVNCServer::ClientMsg
Enumerator
SetPixelFormat
FixColourMapEntries
SetEncodings
FramebufferUpdateRequest
KeyEvent
PointerEvent
ClientCutText
SetPixelFormat
FixColourMapEntries
SetEncodings
FramebufferUpdateRequest
KeyEvent
PointerEvent
ClientCutText
Definition at line 444 of file qscreenvnc_p.h.
                    { SetPixelFormat = 0,
                      FixColourMapEntries = 1,
                      SetEncodings = 2,
                      FramebufferUpdateRequest = 3,
                      KeyEvent = 4,
                      PointerEvent = 5,
                      ClientCutText = 6 };
ClientMsg [2/2]
enum QVNCServer::ClientMsg
Enumerator
SetPixelFormat
FixColourMapEntries
SetEncodings
FramebufferUpdateRequest
KeyEvent
PointerEvent
ClientCutText
SetPixelFormat
FixColourMapEntries
SetEncodings
FramebufferUpdateRequest
KeyEvent
PointerEvent
ClientCutText
Definition at line 450 of file qvncserver.h.
                    { SetPixelFormat = 0,
                      FixColourMapEntries = 1,
                      SetEncodings = 2,
                      FramebufferUpdateRequest = 3,
                      KeyEvent = 4,
                      PointerEvent = 5,
                      ClientCutText = 6 };
ClientState [1/2]
enum QVNCServer::ClientState private
Enumerator
Unconnected
Protocol
Init
Connected
Unconnected
Protocol
Init
Connected
Definition at line 487 of file qscreenvnc_p.h.
 { Unconnected, Protocol, Init, Connected };
ClientState [2/2]
enum QVNCServer::ClientState private
Enumerator
Unconnected
Protocol
Init
Connected
Unconnected
Protocol
Init
Connected
Definition at line 494 of file qvncserver.h.
 { Unconnected, Protocol, Init, Connected };
ServerMsg [1/2]
enum QVNCServer::ServerMsg
Enumerator
FramebufferUpdate
SetColourMapEntries
FramebufferUpdate
SetColourMapEntries
Definition at line 452 of file qscreenvnc_p.h.
                    { FramebufferUpdate = 0,
                      SetColourMapEntries = 1 };
ServerMsg [2/2]
enum QVNCServer::ServerMsg
Enumerator
FramebufferUpdate
SetColourMapEntries
FramebufferUpdate
SetColourMapEntries
Definition at line 458 of file qvncserver.h.
                    { FramebufferUpdate = 0,
                      SetColourMapEntries = 1 };
Constructors and Destructors
QVNCServer() [1/4]
QVNCServer::QVNCServer (QVNCScreen * screen)
Definition at line 572 of file qscreenvnc_qws.cpp.
     : qvnc_screen(screen)
 {
     init(5900);
 }
QVNCServer() [2/4]
QVNCServer::QVNCServer (QVNCScreen * screen, int id)
Definition at line 578 of file qscreenvnc_qws.cpp.
     : qvnc_screen(screen)
 {
     init(5900 + id);
 }
~QVNCServer() [1/2]
QVNCServer::~QVNCServer ()
Definition at line 613 of file qscreenvnc_qws.cpp.
 {
     delete encoder;
     encoder = 0;
     delete client;
     client = 0;
 #ifndef QT_NO_QWS_CURSOR
     delete qvnc_cursor;
     qvnc_cursor = 0;
 #endif
 }
QVNCServer() [3/4]
QVNCServer::QVNCServer (QVNCScreen * screen)
QVNCServer() [4/4]
QVNCServer::QVNCServer (QVNCScreen * screen, int id)
~QVNCServer() [2/2]
QVNCServer::~QVNCServer ()
Functions
checkUpdate [1/2]
void QVNCServer::checkUpdate () private slot
Definition at line 2009 of file qscreenvnc_qws.cpp.
Referenced by frameBufferUpdateRequest(), init(), and QVNCDirtyMap::QVNCDirtyMap().
 {
     if (!wantUpdate)
         return;
     if (dirtyCursor) {
 #ifndef QT_NO_QWS_CURSOR
         Q_ASSERT(qvnc_cursor);
         qvnc_cursor->write();
 #endif
         dirtyCursor = false;
         wantUpdate = false;
         return;
     }
     if (dirtyMap()->numDirty > 0) {
         if (encoder)
             encoder->write();
         wantUpdate = false;
     }
 }
checkUpdate [2/2]
void QVNCServer::checkUpdate () private slot
clientBytesPerPixel() [1/2]
int QVNCServer::clientBytesPerPixel () const inline
Definition at line 457 of file qscreenvnc_p.h.
Referenced by QRfbMultiColorHextile< SRC >::read(), QVNCCursor::sendClientCursor(), QVNCClientCursor::write(), QRfbRawEncoder::write(), QRfbSingleColorHextile< SRC >::write(), QRfbDualColorHextile< SRC >::write(), and QRfbHextileEncoder< SRC >::write().
{
         return pixelFormat.bitsPerPixel / 8;
     }
clientBytesPerPixel() [2/2]
int QVNCServer::clientBytesPerPixel () const inline
Definition at line 463 of file qvncserver.h.
{
         return pixelFormat.bitsPerPixel / 8;
     }
clientCutText() [1/2]
void QVNCServer::clientCutText () private
Definition at line 1052 of file qscreenvnc_qws.cpp.
Referenced by buttonChange(), and readClient().
 {
     QRfbClientCutText ev;
     if (cutTextPending == 0 && ev.read(client)) {
         cutTextPending = ev.length;
         if (!cutTextPending)
             handleMsg = false;
     }
     if (cutTextPending && client->bytesAvailable() >= cutTextPending) {
         char *text = new char [cutTextPending+1];
         client->read(text, cutTextPending);
         delete [] text;
         cutTextPending = 0;
         handleMsg = false;
     }
 }
clientCutText() [2/2]
void QVNCServer::clientCutText () private
clientSocket() [1/2]
QTcpSocket* QVNCServer::clientSocket () const inline
Definition at line 463 of file qscreenvnc_p.h.
Referenced by QVNCCursor::clearClientCursor(), QVNCCursor::sendClientCursor(), QVNCClientCursor::write(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 { return client; }
clientSocket() [2/2]
QTcpSocket* QVNCServer::clientSocket () const inline
Definition at line 469 of file qvncserver.h.
 { return client; }
convertPixels() [1/2]
void QVNCServer::convertPixels (char * dst, const char * src, int count) const
Definition at line 1432 of file qscreenvnc_qws.cpp.
Referenced by buttonChange(), QVNCCursor::sendClientCursor(), QRfbMultiColorHextile< SRC >::setColor(), QVNCClientCursor::write(), QRfbRawEncoder::write(), QRfbSingleColorHextile< SRC >::write(), QRfbDualColorHextile< SRC >::write(), QRfbMultiColorHextile< SRC >::write(), and QRfbHextileEncoder< SRC >::write().
 {
     const int screendepth = qvnc_screen->depth();
     const bool isBgr = qvnc_screen->pixelType() == QScreen::BGRPixel;
     // cutoffs
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
     if (!swapBytes)
 #endif
     if (sameEndian) {
         if (screendepth == pixelFormat.bitsPerPixel) { // memcpy cutoffs
             switch (screendepth) {
             case 32:
                 memcpy(dst, src, count * sizeof(quint32));
                 return;
             case 16:
                 if (pixelFormat.redBits == 5
                     && pixelFormat.greenBits == 6
                     && pixelFormat.blueBits == 5)
                 {
                     memcpy(dst, src, count * sizeof(quint16));
                     return;
                 }
             }
         } else if (screendepth == 16 && pixelFormat.bitsPerPixel == 32) {
 #if defined(__i386__) // Currently fails on ARM if dst is not 4 byte aligned
             const quint32 *src32 = reinterpret_cast<const quint32*>(src);
             quint32 *dst32 = reinterpret_cast<quint32*>(dst);
             int count32 = count * sizeof(quint16) / sizeof(quint32);
             while (count32--) {
                 const quint32 s = *src32++;
                 quint32 result1;
                 quint32 result2;
                 // red
                 result1 = ((s & 0xf8000000) | ((s & 0xe0000000) >> 5)) >> 8;
                 result2 = ((s & 0x0000f800) | ((s & 0x0000e000) >> 5)) << 8;
                 // green
                 result1 |= ((s & 0x07e00000) | ((s & 0x06000000) >> 6)) >> 11;
                 result2 |= ((s & 0x000007e0) | ((s & 0x00000600) >> 6)) << 5;
                 // blue
                 result1 |= ((s & 0x001f0000) | ((s & 0x001c0000) >> 5)) >> 13;
                 result2 |= ((s & 0x0000001f) | ((s & 0x0000001c) >> 5)) << 3;
                 *dst32++ = result2;
                 *dst32++ = result1;
             }
             if (count & 0x1) {
                 const quint16 *src16 = reinterpret_cast<const quint16*>(src);
                 *dst32 = qt_conv16ToRgb(src16[count - 1]);
             }
             return;
 #endif
         }
     }
     const int bytesPerPixel = (pixelFormat.bitsPerPixel + 7) / 8;
 //    nibble = 0;
     for (int i = 0; i < count; ++i) {
         int r, g, b;
         switch (screendepth) {
 #if 0
         case 4: {
             if (!nibble) {
                 r = ((*src) & 0x0f) << 4;
             } else {
                 r = (*src) & 0xf0;
                 src++;
             }
             nibble = !nibble;
             g = b = r;
             break;
         }
 #endif
         case 8: {
             QRgb rgb = qvnc_screen->clut()[int(*src)];
             r = qRed(rgb);
             g = qGreen(rgb);
             b = qBlue(rgb);
             src++;
             break;
         }
 #ifdef QT_QWS_DEPTH_12
         case 12: {
             quint32 p = quint32(*reinterpret_cast<const qrgb444*>(src));
             r = qRed(p);
             g = qGreen(p);
             b = qBlue(p);
             src += sizeof(qrgb444);
             break;
         }
 #endif
 #ifdef QT_QWS_DEPTH_15
         case 15: {
             quint32 p = quint32(*reinterpret_cast<const qrgb555*>(src));
             r = qRed(p);
             g = qGreen(p);
             b = qBlue(p);
             src += sizeof(qrgb555);
             break;
         }
 #endif
         case 16: {
             quint16 p = *reinterpret_cast<const quint16*>(src);
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
             if (swapBytes)
                 p = ((p & 0xff) << 8) | ((p & 0xff00) >> 8);
 #endif
             r = (p >> 11) & 0x1f;
             g = (p >> 5) & 0x3f;
             b = p & 0x1f;
             r <<= 3;
             g <<= 2;
             b <<= 3;
             src += sizeof(quint16);
             break;
         }
 #ifdef QT_QWS_DEPTH_18
         case 18: {
             quint32 p = quint32(*reinterpret_cast<const qrgb666*>(src));
             r = qRed(p);
             g = qGreen(p);
             b = qBlue(p);
             src += sizeof(qrgb666);
             break;
         }
 #endif
 #ifdef QT_QWS_DEPTH_24
         case 24: {
             quint32 p = quint32(*reinterpret_cast<const qrgb888*>(src));
             r = qRed(p);
             g = qGreen(p);
             b = qBlue(p);
             src += sizeof(qrgb888);
             break;
         }
 #endif
         case 32: {
             quint32 p = *reinterpret_cast<const quint32*>(src);
             r = (p >> 16) & 0xff;
             g = (p >> 8) & 0xff;
             b = p & 0xff;
             src += sizeof(quint32);
             break;
         }
         default: {
             r = g = b = 0;
             qDebug("QVNCServer: don't support %dbpp display", screendepth);
             return;
         }
         }
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
         if (swapBytes ^ isBgr)
 #else
         if (isBgr)
 #endif
             qSwap(r, b);
         r >>= (8 - pixelFormat.redBits);
         g >>= (8 - pixelFormat.greenBits);
         b >>= (8 - pixelFormat.blueBits);
         int pixel = (r << pixelFormat.redShift) |
                     (g << pixelFormat.greenShift) |
                     (b << pixelFormat.blueShift);
         if (sameEndian || pixelFormat.bitsPerPixel == 8) {
             memcpy(dst, &pixel, bytesPerPixel); // XXX: do a simple for-loop instead?
             dst += bytesPerPixel;
             continue;
         }
         if (QSysInfo::ByteOrder == QSysInfo::BigEndian) {
             switch (pixelFormat.bitsPerPixel) {
             case 16:
                 pixel = (((pixel & 0x0000ff00) << 8)  |
                          ((pixel & 0x000000ff) << 24));
                 break;
             case 32:
                 pixel = (((pixel & 0xff000000) >> 24) |
                          ((pixel & 0x00ff0000) >> 8)  |
                          ((pixel & 0x0000ff00) << 8)  |
                          ((pixel & 0x000000ff) << 24));
                 break;
             default:
                 qDebug("Cannot handle %d bpp client", pixelFormat.bitsPerPixel);
             }
         } else { // QSysInfo::ByteOrder == QSysInfo::LittleEndian
             switch (pixelFormat.bitsPerPixel) {
             case 16:
                 pixel = (((pixel & 0xff000000) >> 8) |
                          ((pixel & 0x00ff0000) << 8));
                 break;
             case 32:
                 pixel = (((pixel & 0xff000000) >> 24) |
                          ((pixel & 0x00ff0000) >> 8)  |
                          ((pixel & 0x0000ff00) << 8)  |
                          ((pixel & 0x000000ff) << 24));
                 break;
             default:
                 qDebug("Cannot handle %d bpp client",
                        pixelFormat.bitsPerPixel);
                 break;
             }
         }
         memcpy(dst, &pixel, bytesPerPixel); // XXX: simple for-loop instead?
         dst += bytesPerPixel;
     }
 }
convertPixels() [2/2]
void QVNCServer::convertPixels (char * dst, const char * src, int count) const
dirtyMap() [1/2]
QVNCDirtyMap* QVNCServer::dirtyMap () const inline
Definition at line 462 of file qscreenvnc_p.h.
Referenced by newConnection(), setDirty(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 { return qvnc_screen->d_ptr->dirty; }
dirtyMap() [2/2]
QVNCDirtyMap* QVNCServer::dirtyMap () const inline
Definition at line 468 of file qvncserver.h.
 { return qvnc_screen->dirtyMap(); }
discardClient [1/2]
void QVNCServer::discardClient () private slot
Definition at line 2031 of file qscreenvnc_qws.cpp.
Referenced by newConnection(), QVNCDirtyMap::QVNCDirtyMap(), readClient(), and setPixelFormat().
 {
     timer->stop();
     state = Unconnected;
     delete encoder;
     encoder = 0;
 #ifndef QT_NO_QWS_CURSOR
     delete qvnc_cursor;
     qvnc_cursor = 0;
 #endif
     if (!qvnc_screen->screen() && !qvnc_screen->d_ptr->noDisablePainting && QWSServer::instance())
         QWSServer::instance()->enablePainting(false);
 }
discardClient [2/2]
void QVNCServer::discardClient () private slot
doPixelConversion() [1/2]
bool QVNCServer::doPixelConversion () const inline
Definition at line 465 of file qscreenvnc_p.h.
Referenced by QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 { return needConversion; }
doPixelConversion() [2/2]
bool QVNCServer::doPixelConversion () const inline
Definition at line 471 of file qvncserver.h.
 { return needConversion; }
frameBufferUpdateRequest() [1/2]
void QVNCServer::frameBufferUpdateRequest () private
Definition at line 1006 of file qscreenvnc_qws.cpp.
Referenced by readClient().
 {
     QRfbFrameBufferUpdateRequest ev;
     if (ev.read(client)) {
         if (!ev.incremental) {
             QRect r(ev.rect.x, ev.rect.y, ev.rect.w, ev.rect.h);
             r.translate(qvnc_screen->offset());
             qvnc_screen->d_ptr->setDirty(r, true);
         }
         wantUpdate = true;
         checkUpdate();
         handleMsg = false;
     }
 }
frameBufferUpdateRequest() [2/2]
void QVNCServer::frameBufferUpdateRequest () private
hasClientCursor()
bool QVNCServer::hasClientCursor () const inline
Definition at line 467 of file qscreenvnc_p.h.
Referenced by QVNCCursor::move(), QVNCCursor::set(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 { return qvnc_cursor != 0; }
init() [1/2]
void QVNCServer::init (uint port) private
Definition at line 584 of file qscreenvnc_qws.cpp.
Referenced by QVNCServer().
 {
     handleMsg = false;
     client = 0;
     encodingsPending = 0;
     cutTextPending = 0;
     keymod = 0;
     state = Unconnected;
     dirtyCursor = false;
     refreshRate = 25;
     timer = new QTimer(this);
     timer->setSingleShot(true);
     connect(timer, SIGNAL(timeout()), this, SLOT(checkUpdate()));
     serverSocket = new QTcpServer(this);
     if (!serverSocket->listen(QHostAddress::Any, port))
         qDebug() << "QVNCServer could not connect:" << serverSocket->errorString();
     else
         qDebug("QVNCServer created on port %d", port);
     connect(serverSocket, SIGNAL(newConnection()), this, SLOT(newConnection()));
 #ifndef QT_NO_QWS_CURSOR
     qvnc_cursor = 0;
 #endif
     encoder = 0;
 }
init() [2/2]
void QVNCServer::init (uint port) private
isConnected() [1/2]
bool QVNCServer::isConnected () const inline
Definition at line 441 of file qscreenvnc_p.h.
Referenced by QVNCScreenPrivate::QVNCScreenPrivate().
 { return state == Connected; }
isConnected() [2/2]
bool QVNCServer::isConnected () const inline
Definition at line 447 of file qvncserver.h.
 { return state == Connected; }
keyEvent() [1/2]
void QVNCServer::keyEvent () private
Definition at line 1032 of file qscreenvnc_qws.cpp.
Referenced by buttonChange(), and readClient().
 {
     QRfbKeyEvent ev;
     if (ev.read(client)) {
         if (ev.keycode == Qt::Key_Shift)
             keymod = ev.down ? keymod | Qt::ShiftModifier :
                                keymod & ~Qt::ShiftModifier;
         else if (ev.keycode == Qt::Key_Control)
             keymod = ev.down ? keymod | Qt::ControlModifier :
                                keymod & ~Qt::ControlModifier;
         else if (ev.keycode == Qt::Key_Alt)
             keymod = ev.down ? keymod | Qt::AltModifier :
                                keymod & ~Qt::AltModifier;
         if (ev.unicode || ev.keycode)
             QWSServer::sendKeyEvent(ev.unicode, ev.keycode, keymod, ev.down, false);
         handleMsg = false;
     }
 }
keyEvent() [2/2]
void QVNCServer::keyEvent () private
newConnection [1/2]
void QVNCServer::newConnection () private slot
Definition at line 633 of file qscreenvnc_qws.cpp.
Referenced by init().
 {
     if (client)
         delete client;
     client = serverSocket->nextPendingConnection();
     connect(client,SIGNAL(readyRead()),this,SLOT(readClient()));
     connect(client,SIGNAL(disconnected()),this,SLOT(discardClient()));
     handleMsg = false;
     encodingsPending = 0;
     cutTextPending = 0;
     supportHextile = false;
     wantUpdate = false;
     timer->start(1000 / refreshRate);
     dirtyMap()->reset();
     // send protocol version
     const char *proto = "RFB 003.003\n";
     client->write(proto, 12);
     state = Protocol;
     if (!qvnc_screen->screen() && !qvnc_screen->d_ptr->noDisablePainting)
         QWSServer::instance()->enablePainting(true);
 }
newConnection [2/2]
void QVNCServer::newConnection () private slot
pixelConversionNeeded() [1/2]
bool QVNCServer::pixelConversionNeeded () const private
Definition at line 1393 of file qscreenvnc_qws.cpp.
Referenced by buttonChange(), and setPixelFormat().
 {
     if (!sameEndian)
         return true;
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
     if (qvnc_screen->swapBytes())
         return true;
 #endif
     const int screendepth = qvnc_screen->depth();
     if (screendepth != pixelFormat.bitsPerPixel)
         return true;
     switch (screendepth) {
     case 32:
     case 24:
         return false;
     case 18:
         return (pixelFormat.redBits == 6
                 && pixelFormat.greenBits == 6
                 && pixelFormat.blueBits == 6);
     case 16:
         return (pixelFormat.redBits == 5
                 && pixelFormat.greenBits == 6
                 && pixelFormat.blueBits == 5);
     case 15:
         return (pixelFormat.redBits == 5
                 && pixelFormat.greenBits == 5
                 && pixelFormat.blueBits == 5);
     case 12:
         return (pixelFormat.redBits == 4
                 && pixelFormat.greenBits == 4
                 && pixelFormat.blueBits == 4);
     }
     return true;
 }
pixelConversionNeeded() [2/2]
bool QVNCServer::pixelConversionNeeded () const private
pointerEvent() [1/2]
void QVNCServer::pointerEvent () private
Definition at line 1022 of file qscreenvnc_qws.cpp.
Referenced by buttonChange(), and readClient().
 {
     QRfbPointerEvent ev;
     if (ev.read(client)) {
         const QPoint offset = qvnc_screen->offset();
         QWSServer::sendMouseEvent(offset + QPoint(ev.x, ev.y), ev.buttons);
         handleMsg = false;
     }
 }
pointerEvent() [2/2]
void QVNCServer::pointerEvent () private
readClient [1/2]
void QVNCServer::readClient () private slot
Definition at line 659 of file qscreenvnc_qws.cpp.
Referenced by newConnection().
 {
     switch (state) {
         case Protocol:
             if (client->bytesAvailable() >= 12) {
                 char proto[13];
                 client->read(proto, 12);
                 proto[12] = '\0';
                 qDebug("Client protocol version %s", proto);
                 // No authentication
                 quint32 auth = htonl(1);
                 client->write((char *) &auth, sizeof(auth));
                 state = Init;
             }
             break;
         case Init:
             if (client->bytesAvailable() >= 1) {
                 quint8 shared;
                 client->read((char *) &shared, 1);
                 // Server Init msg
                 QRfbServerInit sim;
                 QRfbPixelFormat &format = sim.format;
                 switch (qvnc_screen->depth()) {
                 case 32:
                     format.bitsPerPixel = 32;
                     format.depth = 32;
                     format.bigEndian = 0;
                     format.trueColor = true;
                     format.redBits = 8;
                     format.greenBits = 8;
                     format.blueBits = 8;
                     format.redShift = 16;
                     format.greenShift = 8;
                     format.blueShift = 0;
                     break;
                 case 24:
                     format.bitsPerPixel = 24;
                     format.depth = 24;
                     format.bigEndian = 0;
                     format.trueColor = true;
                     format.redBits = 8;
                     format.greenBits = 8;
                     format.blueBits = 8;
                     format.redShift = 16;
                     format.greenShift = 8;
                     format.blueShift = 0;
                     break;
                 case 18:
                     format.bitsPerPixel = 24;
                     format.depth = 18;
                     format.bigEndian = 0;
                     format.trueColor = true;
                     format.redBits = 6;
                     format.greenBits = 6;
                     format.blueBits = 6;
                     format.redShift = 12;
                     format.greenShift = 6;
                     format.blueShift = 0;
                     break;
                 case 16:
                     format.bitsPerPixel = 16;
                     format.depth = 16;
                     format.bigEndian = 0;
                     format.trueColor = true;
                     format.redBits = 5;
                     format.greenBits = 6;
                     format.blueBits = 5;
                     format.redShift = 11;
                     format.greenShift = 5;
                     format.blueShift = 0;
                     break;
                 case 15:
                     format.bitsPerPixel = 16;
                     format.depth = 15;
                     format.bigEndian = 0;
                     format.trueColor = true;
                     format.redBits = 5;
                     format.greenBits = 5;
                     format.blueBits = 5;
                     format.redShift = 10;
                     format.greenShift = 5;
                     format.blueShift = 0;
                     break;
                 case 12:
                     format.bitsPerPixel = 16;
                     format.depth = 12;
                     format.bigEndian = 0;
                     format.trueColor = true;
                     format.redBits = 4;
                     format.greenBits = 4;
                     format.blueBits = 4;
                     format.redShift = 8;
                     format.greenShift = 4;
                     format.blueShift = 0;
                     break;
                 case 8:
                 case 4:
                     format.bitsPerPixel = 8;
                     format.depth = 8;
                     format.bigEndian = 0;
                     format.trueColor = false;
                     format.redBits = 0;
                     format.greenBits = 0;
                     format.blueBits = 0;
                     format.redShift = 0;
                     format.greenShift = 0;
                     format.blueShift = 0;
                     break;
                 default:
                     qDebug("QVNC cannot drive depth %d", qvnc_screen->depth());
                     discardClient();
                     return;
                 }
                 sim.width = qvnc_screen->deviceWidth();
                 sim.height = qvnc_screen->deviceHeight();
                 sim.setName("Qt for Embedded Linux VNC Server");
                 sim.write(client);
                 state = Connected;
             }
             break;
         case Connected:
             do {
                 if (!handleMsg) {
                     client->read((char *)&msgType, 1);
                     handleMsg = true;
                 }
                 if (handleMsg) {
                     switch (msgType ) {
                     case SetPixelFormat:
                         setPixelFormat();
                         break;
                     case FixColourMapEntries:
                         qDebug("Not supported: FixColourMapEntries");
                         handleMsg = false;
                         break;
                     case SetEncodings:
                         setEncodings();
                         break;
                     case FramebufferUpdateRequest:
                         frameBufferUpdateRequest();
                         break;
                     case KeyEvent:
                         keyEvent();
                         break;
                     case PointerEvent:
                         pointerEvent();
                         break;
                     case ClientCutText:
                         clientCutText();
                         break;
                     default:
                         qDebug("Unknown message type: %d", (int)msgType);
                         handleMsg = false;
                     }
                 }
             } while (!handleMsg && client->bytesAvailable());
             break;
     default:
         break;
     }
 }
readClient [2/2]
void QVNCServer::readClient () private slot
screen() [1/2]
QVNCScreen* QVNCServer::screen () const inline
Definition at line 461 of file qscreenvnc_p.h.
Referenced by QRfbSingleColorHextile< SRC >::read(), QVNCScreen::swapBytes(), QVNCClientCursor::write(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 { return qvnc_screen; }
screen() [2/2]
QVNCScreen* QVNCServer::screen () const inline
Definition at line 467 of file qvncserver.h.
 { return qvnc_screen; }
screenImage() [1/2]
QImage * QVNCServer::screenImage () const inline
Definition at line 2002 of file qscreenvnc_qws.cpp.
Referenced by QVNCDirtyMap::QVNCDirtyMap(), QRfbRawEncoder::write(), and QRfbHextileEncoder< SRC >::write().
 {
     return QImage(qvnc_screen->base(), qvnc_screen->deviceWidth(),
                   qvnc_screen->deviceHeight(), qvnc_screen->linestep(),
                   qvnc_screen->pixelFormat());
 }
screenImage() [2/2]
QImage* QVNCServer::screenImage () const
setCursor()
void QVNCServer::setCursor (QVNCCursor * c) inline
Definition at line 476 of file qvncserver.h.
Referenced by QVNCScreen::QVNCScreen().
 { cursor = c; }
setDirty() [1/2]
void QVNCServer::setDirty ()
Definition at line 625 of file qscreenvnc_qws.cpp.
Referenced by QVNCScreenPrivate::QVNCScreenPrivate().
 {
     if (state == Connected && !timer->isActive() &&
         ((dirtyMap()->numDirty > 0) || dirtyCursor)) {
         timer->start();
     }
 }
setDirty() [2/2]
void QVNCServer::setDirty ()
setDirtyCursor() [1/2]
void QVNCServer::setDirtyCursor () inline
Definition at line 440 of file qscreenvnc_p.h.
Referenced by QVNCCursor::changeCursor(), QVNCClientCursor::set(), and QVNCCursor::setCursorMode().
 { dirtyCursor = true; setDirty(); }
setDirtyCursor() [2/2]
void QVNCServer::setDirtyCursor () inline
Definition at line 446 of file qvncserver.h.
 { dirtyCursor = true; setDirty(); }
setEncodings() [1/2]
void QVNCServer::setEncodings () private
Definition at line 875 of file qscreenvnc_qws.cpp.
Referenced by readClient().
 {
     QRfbSetEncodings enc;
     if (!encodingsPending && enc.read(client)) {
         encodingsPending = enc.count;
         if (!encodingsPending)
             handleMsg = false;
     }
     if (encoder) {
         delete encoder;
         encoder = 0;
     }
     enum Encodings {
         Raw = 0,
         CopyRect = 1,
         RRE = 2,
         CoRRE = 4,
         Hextile = 5,
         ZRLE = 16,
         Cursor = -239,
         DesktopSize = -223
     };
     if (encodingsPending && (unsigned)client->bytesAvailable() >=
                                 encodingsPending * sizeof(quint32)) {
         for (int i = 0; i < encodingsPending; ++i) {
             qint32 enc;
             client->read((char *)&enc, sizeof(qint32));
             enc = ntohl(enc);
 #ifdef QT_QWS_VNC_DEBUG
             qDebug("QVNCServer::setEncodings: %d", enc);
 #endif
             switch (enc) {
             case Raw:
                 if (!encoder) {
                     encoder = new QRfbRawEncoder(this);
 #ifdef QT_QWS_VNC_DEBUG
                     qDebug("QVNCServer::setEncodings: using raw");
 #endif
                 }
                break;
             case CopyRect:
                 supportCopyRect = true;
                 break;
             case RRE:
                 supportRRE = true;
                 break;
             case CoRRE:
                 supportCoRRE = true;
                 break;
             case Hextile:
                 supportHextile = true;
                 if (encoder)
                     break;
                 switch (qvnc_screen->depth()) {
 #ifdef QT_QWS_DEPTH_8
                 case 8:
                     encoder = new QRfbHextileEncoder<quint8>(this);
                     break;
 #endif
 #ifdef QT_QWS_DEPTH_12
                 case 12:
                     encoder = new QRfbHextileEncoder<qrgb444>(this);
                     break;
 #endif
 #ifdef QT_QWS_DEPTH_15
                 case 15:
                     encoder = new QRfbHextileEncoder<qrgb555>(this);
                     break;
 #endif
 #ifdef QT_QWS_DEPTH_16
                 case 16:
                     encoder = new QRfbHextileEncoder<quint16>(this);
                     break;
 #endif
 #ifdef QT_QWS_DEPTH_18
                 case 18:
                     encoder = new QRfbHextileEncoder<qrgb666>(this);
                     break;
 #endif
 #ifdef QT_QWS_DEPTH_24
                 case 24:
                     encoder = new QRfbHextileEncoder<qrgb888>(this);
                     break;
 #endif
 #ifdef QT_QWS_DEPTH_32
                 case 32:
                     encoder = new QRfbHextileEncoder<quint32>(this);
                     break;
 #endif
                 default:
                     break;
                 }
 #ifdef QT_QWS_VNC_DEBUG
                 qDebug("QVNCServer::setEncodings: using hextile");
 #endif
                 break;
             case ZRLE:
                 supportZRLE = true;
                 break;
             case Cursor:
                 supportCursor = true;
 #ifndef QT_NO_QWS_CURSOR
                 if (!qvnc_screen->screen() || qt_screencursor->isAccelerated()) {
                     delete qvnc_cursor;
                     qvnc_cursor = new QVNCClientCursor(this);
                 }
 #endif
                 break;
             case DesktopSize:
                 supportDesktopSize = true;
                 break;
             default:
                 break;
             }
         }
         handleMsg = false;
         encodingsPending = 0;
     }
     if (!encoder) {
         encoder = new QRfbRawEncoder(this);
 #ifdef QT_QWS_VNC_DEBUG
         qDebug("QVNCServer::setEncodings: fallback using raw");
 #endif
     }
 }
setEncodings() [2/2]
void QVNCServer::setEncodings () private
setPixelFormat() [1/2]
void QVNCServer::setPixelFormat () private
Definition at line 843 of file qscreenvnc_qws.cpp.
Referenced by readClient().
 {
     if (client->bytesAvailable() >= 19) {
         char buf[3];
         client->read(buf, 3); // just padding
         pixelFormat.read(client);
 #ifdef QT_QWS_VNC_DEBUG
         qDebug("Want format: %d %d %d %d %d %d %d %d %d %d",
             int(pixelFormat.bitsPerPixel),
             int(pixelFormat.depth),
             int(pixelFormat.bigEndian),
             int(pixelFormat.trueColor),
             int(pixelFormat.redBits),
             int(pixelFormat.greenBits),
             int(pixelFormat.blueBits),
             int(pixelFormat.redShift),
             int(pixelFormat.greenShift),
             int(pixelFormat.blueShift));
 #endif
         if (!pixelFormat.trueColor) {
             qDebug("Can only handle true color clients");
             discardClient();
         }
         handleMsg = false;
         sameEndian = (QSysInfo::ByteOrder == QSysInfo::BigEndian) == !!pixelFormat.bigEndian;
         needConversion = pixelConversionNeeded();
 #if Q_BYTE_ORDER == Q_BIG_ENDIAN
         swapBytes = qvnc_screen->swapBytes();
 #endif
     }
 }
setPixelFormat() [2/2]
void QVNCServer::setPixelFormat () private
setRefreshRate() [1/2]
void QVNCServer::setRefreshRate (int rate) inline
Definition at line 442 of file qscreenvnc_p.h.
Referenced by QVNCScreen::initDevice(), and QVNCScreenPrivate::QVNCScreenPrivate().
 { refreshRate = rate; }
setRefreshRate() [2/2]
void QVNCServer::setRefreshRate (int rate) inline
Definition at line 448 of file qvncserver.h.
 { refreshRate = rate; }
Properties
buttons
Qt::MouseButtons QVNCServer::buttons private
Definition at line 503 of file qvncserver.h.
client
QTcpSocket * QVNCServer::client private
Definition at line 490 of file qscreenvnc_p.h.
Referenced by clientCutText(), frameBufferUpdateRequest(), init(), keyEvent(), newConnection(), pointerEvent(), readClient(), setEncodings(), setPixelFormat(), and ~QVNCServer().
cursor
QVNCCursor* QVNCServer::cursor private
Definition at line 527 of file qvncserver.h.
cutTextPending
int QVNCServer::cutTextPending private
Definition at line 497 of file qscreenvnc_p.h.
Referenced by clientCutText(), init(), and newConnection().
dirtyCursor
bool QVNCServer::dirtyCursor private
Definition at line 511 of file qscreenvnc_p.h.
Referenced by init(), and setDirty().
encoder
QRfbEncoder * QVNCServer::encoder private
Definition at line 518 of file qscreenvnc_p.h.
Referenced by init(), QRfbSingleColorHextile< SRC >::read(), QRfbDualColorHextile< SRC >::read(), QRfbMultiColorHextile< SRC >::read(), QRfbMultiColorHextile< SRC >::setColor(), setEncodings(), QRfbSingleColorHextile< SRC >::write(), QRfbDualColorHextile< SRC >::write(), QRfbMultiColorHextile< SRC >::write(), and ~QVNCServer().
encodingsPending
int QVNCServer::encodingsPending private
Definition at line 496 of file qscreenvnc_p.h.
Referenced by init(), newConnection(), and setEncodings().
handleMsg
bool QVNCServer::handleMsg private
Definition at line 493 of file qscreenvnc_p.h.
Referenced by clientCutText(), frameBufferUpdateRequest(), init(), keyEvent(), newConnection(), pointerEvent(), readClient(), setEncodings(), and setPixelFormat().
keymod
Qt::KeyboardModifiers QVNCServer::keymod private
Definition at line 495 of file qscreenvnc_p.h.
Referenced by init(), and keyEvent().
msgType
quint8 QVNCServer::msgType private
Definition at line 492 of file qscreenvnc_p.h.
Referenced by readClient().
needConversion
bool QVNCServer::needConversion private
Definition at line 507 of file qscreenvnc_p.h.
Referenced by setPixelFormat().
pixelFormat
QRfbPixelFormat QVNCServer::pixelFormat private
Definition at line 494 of file qscreenvnc_p.h.
Referenced by convertPixels(), pixelConversionNeeded(), and setPixelFormat().
qvnc_cursor
QVNCClientCursor* QVNCServer::qvnc_cursor private
Definition at line 515 of file qscreenvnc_p.h.
Referenced by init(), setEncodings(), and ~QVNCServer().
qvnc_screen
QVNCScreen * QVNCServer::qvnc_screen private
Definition at line 513 of file qscreenvnc_p.h.
Referenced by convertPixels(), frameBufferUpdateRequest(), newConnection(), pixelConversionNeeded(), pointerEvent(), readClient(), setEncodings(), and setPixelFormat().
refreshRate
int QVNCServer::refreshRate private
Definition at line 512 of file qscreenvnc_p.h.
Referenced by init(), and newConnection().
sameEndian
bool QVNCServer::sameEndian private
Definition at line 506 of file qscreenvnc_p.h.
Referenced by convertPixels(), pixelConversionNeeded(), and setPixelFormat().
serverSocket
QTcpServer * QVNCServer::serverSocket private
Definition at line 489 of file qscreenvnc_p.h.
Referenced by init(), and newConnection().
state
ClientState QVNCServer::state private
Definition at line 491 of file qscreenvnc_p.h.
Referenced by init(), newConnection(), readClient(), and setDirty().
supportCopyRect
uint QVNCServer::supportCopyRect private
Definition at line 498 of file qscreenvnc_p.h.
Referenced by setEncodings().
supportCoRRE
uint QVNCServer::supportCoRRE private
Definition at line 500 of file qscreenvnc_p.h.
Referenced by setEncodings().
supportCursor
uint QVNCServer::supportCursor private
Definition at line 503 of file qscreenvnc_p.h.
Referenced by setEncodings().
supportDesktopSize
uint QVNCServer::supportDesktopSize private
Definition at line 504 of file qscreenvnc_p.h.
Referenced by setEncodings().
supportHextile
uint QVNCServer::supportHextile private
Definition at line 501 of file qscreenvnc_p.h.
Referenced by newConnection(), and setEncodings().
supportRRE
uint QVNCServer::supportRRE private
Definition at line 499 of file qscreenvnc_p.h.
Referenced by setEncodings().
supportZRLE
uint QVNCServer::supportZRLE private
Definition at line 502 of file qscreenvnc_p.h.
Referenced by setEncodings().
swapBytes
bool QVNCServer::swapBytes private
Definition at line 509 of file qscreenvnc_p.h.
Referenced by convertPixels(), and setPixelFormat().
timer
QTimer * QVNCServer::timer private
Definition at line 488 of file qscreenvnc_p.h.
Referenced by init(), newConnection(), and setDirty().
wantUpdate
bool QVNCServer::wantUpdate private
Definition at line 505 of file qscreenvnc_p.h.
Referenced by frameBufferUpdateRequest(), and newConnection().
The documentation for this class was generated from the following files:
/src/plugins/gfxdrivers/vnc/qscreenvnc_p.h
/src/plugins/platforms/vnc/qvncserver.h
/src/plugins/gfxdrivers/vnc/qscreenvnc_qws.cpp
/src/plugins/platforms/vnc/qvncserver.cpp