Qt 4.8: QMetaObjectBuilder Class Reference
QMetaObjectBuilder Class Reference
#include <qmetaobjectbuilder_p.h>
Public Types
enum AddMember {
ClassName = 0x00000001, SuperClass = 0x00000002, Methods = 0x00000004, Signals = 0x00000008,
Slots = 0x00000010, Constructors = 0x00000020, Properties = 0x00000040, Enumerators = 0x00000080,
ClassInfos = 0x00000100, RelatedMetaObjects = 0x00000200, StaticMetacall = 0x00000400, PublicMethods = 0x00000800,
ProtectedMethods = 0x00001000, PrivateMethods = 0x00002000, AllMembers = 0x7FFFFFFF, AllPrimaryMembers = 0x7FFFFBFC
}
This enum defines which members of QMetaObject should be copied by QMetaObjectBuilder::addMetaObject()
enum MetaObjectFlag { DynamicMetaObject = 0x01 }
typedef QMetaObjectExtraData::StaticMetacallFunction StaticMetacallFunction
Typedef for static metacall functions.
Public Functions
int addClassInfo (const QByteArray &name, const QByteArray &value)
Adds name and value as an item of class information to this class.
QMetaMethodBuilder addConstructor (const QByteArray &signature)
Adds a new constructor to this class with the specified signature.
QMetaMethodBuilder addConstructor (const QMetaMethod &prototype)
Adds a new constructor to this class that has the same information as prototype.
QMetaEnumBuilder addEnumerator (const QByteArray &name)
Adds a new enumerator to this class with the specified name.
QMetaEnumBuilder addEnumerator (const QMetaEnum &prototype)
Adds a new enumerator to this class that has the same information as prototype.
void addMetaObject (const QMetaObject *prototype, QMetaObjectBuilder::AddMembers members=AllMembers)
Adds the contents of prototype to this meta object builder.
QMetaMethodBuilder addMethod (const QByteArray &signature)
Adds a new public method to this class with the specified signature.
QMetaMethodBuilder addMethod (const QByteArray &signature, const QByteArray &returnType)
Adds a new public method to this class with the specified signature and returnType.
QMetaMethodBuilder addMethod (const QMetaMethod &prototype)
Adds a new public method to this class that has the same information as prototype.
QMetaPropertyBuilder addProperty (const QByteArray &name, const QByteArray &type, int notifierId=-1)
Adds a new readable/writable property to this class with the specified name and type.
QMetaPropertyBuilder addProperty (const QMetaProperty &prototype)
Adds a new property to this class that has the same information as prototype.
int addRelatedMetaObject (const QMetaObject *meta)
Adds meta to this class as a related meta object.
QMetaMethodBuilder addSignal (const QByteArray &signature)
Adds a new signal to this class with the specified signature.
QMetaMethodBuilder addSlot (const QByteArray &signature)
Adds a new public slot to this class with the specified signature.
int classInfoCount () const
Returns the number of items of class information in this class, exclusing the number of items of class information in the base class.
QByteArray classInfoName (int index) const
Returns the name of the item of class information at index in this class.
QByteArray classInfoValue (int index) const
Returns the value of the item of class information at index in this class.
QByteArray className () const
Returns the name of the class being constructed by this meta object builder.
QMetaMethodBuilder constructor (int index) const
Returns the constructor at index in this class.
int constructorCount () const
Returns the number of constructors in this class.
void deserialize (QDataStream &stream, const QMap< QByteArray, const QMetaObject *> &references)
Deserializes a meta object builder from stream into this meta object builder.
QMetaEnumBuilder enumerator (int index) const
Returns the enumerator at index in this class.
int enumeratorCount () const
Returns the number of enumerators in this class, excluding the number of enumerators in the base class.
MetaObjectFlags flags () const
Returns the flags of the class being constructed by this meta object builder.
int indexOfClassInfo (const QByteArray &name)
Finds an item of class information with the specified name and returns its index; otherwise returns -1.
int indexOfConstructor (const QByteArray &signature)
Finds a constructor with the specified signature and returns its index; otherwise returns -1.
int indexOfEnumerator (const QByteArray &name)
Finds an enumerator with the specified name and returns its index; otherwise returns -1.
int indexOfMethod (const QByteArray &signature)
Finds a method with the specified signature and returns its index; otherwise returns -1.
int indexOfProperty (const QByteArray &name)
Finds a property with the specified name and returns its index; otherwise returns -1.
int indexOfSignal (const QByteArray &signature)
Finds a signal with the specified signature and returns its index; otherwise returns -1.
int indexOfSlot (const QByteArray &signature)
Finds a slot with the specified signature and returns its index; otherwise returns -1.
QMetaMethodBuilder method (int index) const
Returns the method at index in this class.
int methodCount () const
Returns the number of methods in this class, excluding the number of methods in the base class.
QMetaPropertyBuilder property (int index) const
Returns the property at index in this class.
int propertyCount () const
Returns the number of properties in this class, excluding the number of properties in the base class.
QMetaObjectBuilder ()
Constructs a new QMetaObjectBuilder.
QMetaObjectBuilder (const QMetaObject *prototype, QMetaObjectBuilder::AddMembers members=AllMembers)
Constructs a new QMetaObjectBuilder which is a copy of the meta object information in prototype.
const QMetaObject * relatedMetaObject (int index) const
Returns the related meta object at index in this class.
int relatedMetaObjectCount () const
Returns the number of related meta objects that are associated with this class.
void removeClassInfo (int index)
Removes the item of class information at index from this class.
void removeConstructor (int index)
Removes the constructor at index from this class.
void removeEnumerator (int index)
Removes the enumerator at index from this class.
void removeMethod (int index)
Removes the method at index from this class.
void removeProperty (int index)
Removes the property at index from this class.
void removeRelatedMetaObject (int index)
Removes the related meta object at index from this class.
void serialize (QDataStream &stream) const
Serializes the contents of the meta object builder onto stream.
void setClassName (const QByteArray &name)
Sets the name of the class being constructed by this meta object builder.
void setFlags (MetaObjectFlags)
Sets the flags of the class being constructed by this meta object builder.
void setStaticMetacallFunction (QMetaObjectBuilder::StaticMetacallFunction value)
Sets the static metacall function to use to construct objects of this class to value.
void setSuperClass (const QMetaObject *meta)
Sets the superclass meta object of the class being constructed by this meta object builder to meta.
QMetaObjectBuilder::StaticMetacallFunction staticMetacallFunction () const
Returns the static metacall function to use to construct objects of this class.
const QMetaObject * superClass () const
Returns the superclass meta object of the class being constructed by this meta object builder.
QMetaObject * toMetaObject () const
Converts this meta object builder into a concrete QMetaObject.
QByteArray toRelocatableData (bool *=0) const
virtual ~QMetaObjectBuilder ()
Destroys this meta object builder.
Static Public Functions
static void fromRelocatableData (QMetaObject *, const QMetaObject *, const QByteArray &)
Properties
QMetaObjectBuilderPrivate * d
Friends
class QMetaEnumBuilder
class QMetaMethodBuilder
class QMetaPropertyBuilder
Detailed Description
Warning
This function is not part of the public interface.
Note
The QMetaObjectBuilder class supports building QMetaObject objects at runtime.
Definition at line 73 of file qmetaobjectbuilder_p.h.
Typedefs
StaticMetacallFunction
QMetaObjectBuilder::StaticMetacallFunction
Typedef for static metacall functions.
The three parameters are the call type value, the constructor index, and the array of parameters.
Definition at line 172 of file qmetaobjectbuilder_p.h.
Enumerations
AddMember
enum QMetaObjectBuilder::AddMember
This enum defines which members of QMetaObject should be copied by QMetaObjectBuilder::addMetaObject()
ClassName Add the class name.
SuperClass Add the super class.
Methods Add methods that aren't signals or slots.
Signals Add signals.
Slots Add slots.
Constructors Add constructors.
Properties Add properties.
Enumerators Add enumerators.
ClassInfos Add items of class information.
RelatedMetaObjects Add related meta objects.
StaticMetacall Add the static metacall function.
PublicMethods Add public methods (ignored for signals).
ProtectedMethods Add protected methods (ignored for signals).
PrivateMethods All private methods (ignored for signals).
AllMembers Add all members.
AllPrimaryMembers Add everything except the class name, super class, and static metacall function.
Enumerator
ClassName
SuperClass
Methods
Signals
Slots
Constructors
Properties
Enumerators
ClassInfos
RelatedMetaObjects
StaticMetacall
PublicMethods
ProtectedMethods
PrivateMethods
AllMembers
AllPrimaryMembers
Definition at line 76 of file qmetaobjectbuilder_p.h.
     {
         ClassName               = 0x00000001,
         SuperClass              = 0x00000002,
         Methods                 = 0x00000004,
         Signals                 = 0x00000008,
         Slots                   = 0x00000010,
         Constructors            = 0x00000020,
         Properties              = 0x00000040,
         Enumerators             = 0x00000080,
         ClassInfos              = 0x00000100,
         RelatedMetaObjects      = 0x00000200,
         StaticMetacall          = 0x00000400,
         PublicMethods           = 0x00000800,
         ProtectedMethods        = 0x00001000,
         PrivateMethods          = 0x00002000,
         AllMembers              = 0x7FFFFFFF,
         AllPrimaryMembers       = 0x7FFFFBFC
     };
MetaObjectFlag
enum QMetaObjectBuilder::MetaObjectFlag
Enumerator
DynamicMetaObject
Definition at line 97 of file qmetaobjectbuilder_p.h.
{
         DynamicMetaObject = 0x01
     };
Constructors and Destructors
QMetaObjectBuilder() [1/2]
QMetaObjectBuilder::QMetaObjectBuilder ()
Constructs a new QMetaObjectBuilder.
Definition at line 281 of file qmetaobjectbuilder.cpp.
 {
     d = new QMetaObjectBuilderPrivate();
 }
QMetaObjectBuilder() [2/2]
QMetaObjectBuilder::QMetaObjectBuilder (const QMetaObject * prototype, QMetaObjectBuilder::AddMembers members = AllMembers) explicit
Constructs a new QMetaObjectBuilder which is a copy of the meta object information in prototype.
Note: the super class contents for prototype are not copied, only the immediate class that is defined by prototype.
The members parameter indicates which members of prototype should be added. The default is AllMembers.
See also
addMetaObject()
Definition at line 298 of file qmetaobjectbuilder.cpp.
 {
     d = new QMetaObjectBuilderPrivate();
     addMetaObject(prototype, members);
 }
~QMetaObjectBuilder()
QMetaObjectBuilder::~QMetaObjectBuilder () virtual
Destroys this meta object builder.
Definition at line 307 of file qmetaobjectbuilder.cpp.
 {
     delete d;
 }
Functions
addClassInfo()
int QMetaObjectBuilder::addClassInfo (const QByteArray & name, const QByteArray & value)
Adds name and value as an item of class information to this class.
Returns the index of the new item of class information.
See also
classInfoCount(), classInfoName(), classInfoValue(), removeClassInfo()
indexOfClassInfo()
Definition at line 681 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), and clone().
 {
     int index = d->classInfoNames.size();
     d->classInfoNames += name;
     d->classInfoValues += value;
     return index;
 }
addConstructor() [1/2]
QMetaMethodBuilder QMetaObjectBuilder::addConstructor (const QByteArray & signature)
Adds a new constructor to this class with the specified signature.
Returns an object that can be used to adjust the other attributes of the constructor. The signature will be normalized before it is added to the class.
See also
constructor(), constructorCount(), removeConstructor()
indexOfConstructor()
Definition at line 558 of file qmetaobjectbuilder.cpp.
 {
     int index = d->constructors.size();
     d->constructors.append(QMetaMethodBuilderPrivate(QMetaMethod::Constructor, signature));
     return QMetaMethodBuilder(this, -(index + 1));
 }
addConstructor() [2/2]
QMetaMethodBuilder QMetaObjectBuilder::addConstructor (const QMetaMethod & prototype)
Adds a new constructor to this class that has the same information as prototype.
This is used to clone the constructors of an existing QMetaObject. Returns an object that can be used to adjust the attributes of the constructor.
This function requires that prototype be a constructor.
See also
constructor(), constructorCount(), removeConstructor()
indexOfConstructor()
Definition at line 576 of file qmetaobjectbuilder.cpp.
 {
     Q_ASSERT(prototype.methodType() == QMetaMethod::Constructor);
     QMetaMethodBuilder ctor = addConstructor(prototype.signature());
     ctor.setReturnType(prototype.typeName());
     ctor.setParameterNames(prototype.parameterNames());
     ctor.setTag(prototype.tag());
     ctor.setAccess(prototype.access());
     ctor.setAttributes(prototype.attributes());
     return ctor;
 }
addEnumerator() [1/2]
QMetaEnumBuilder QMetaObjectBuilder::addEnumerator (const QByteArray & name)
Adds a new enumerator to this class with the specified name.
Returns an object that can be used to adjust the other attributes of the enumerator.
See also
enumerator(), enumeratorCount(), removeEnumerator(),
indexOfEnumerator()
Definition at line 648 of file qmetaobjectbuilder.cpp.
 {
     int index = d->enumerators.size();
     d->enumerators.append(QMetaEnumBuilderPrivate(name));
     return QMetaEnumBuilder(this, index);
 }
addEnumerator() [2/2]
QMetaEnumBuilder QMetaObjectBuilder::addEnumerator (const QMetaEnum & prototype)
Adds a new enumerator to this class that has the same information as prototype.
This is used to clone the enumerators of an existing QMetaObject. Returns an object that can be used to adjust the attributes of the enumerator.
See also
enumerator(), enumeratorCount(), removeEnumerator(),
indexOfEnumerator()
Definition at line 664 of file qmetaobjectbuilder.cpp.
 {
     QMetaEnumBuilder en = addEnumerator(prototype.name());
     en.setIsFlag(prototype.isFlag());
     int count = prototype.keyCount();
     for (int index = 0; index < count; ++index)
         en.addKey(prototype.key(index), prototype.value(index));
     return en;
 }
addMetaObject()
void QMetaObjectBuilder::addMetaObject (const QMetaObject * prototype, QMetaObjectBuilder::AddMembers members = AllMembers)
Adds the contents of prototype to this meta object builder.
This function is useful for cloning the contents of an existing QMetaObject.
The members parameter indicates which members of prototype should be added. The default is AllMembers.
Definition at line 720 of file qmetaobjectbuilder.cpp.
Referenced by addRelatedMetaObject().
 {
     Q_ASSERT(prototype);
     int index;
     if ((members & ClassName) != 0)
         d->className = prototype->className();
     if ((members & SuperClass) != 0)
         d->superClass = prototype->superClass();
     if ((members & (Methods | Signals | Slots)) != 0) {
         for (index = prototype->methodOffset(); index < prototype->methodCount(); ++index) {
             QMetaMethod method = prototype->method(index);
             if (method.methodType() != QMetaMethod::Signal) {
                 if (method.access() == QMetaMethod::Public && (members & PublicMethods) == 0)
                     continue;
                 if (method.access() == QMetaMethod::Private && (members & PrivateMethods) == 0)
                     continue;
                 if (method.access() == QMetaMethod::Protected && (members & ProtectedMethods) == 0)
                     continue;
             }
             if (method.methodType() == QMetaMethod::Method && (members & Methods) != 0) {
                 addMethod(method);
             } else if (method.methodType() == QMetaMethod::Signal &&
                        (members & Signals) != 0) {
                 addMethod(method);
             } else if (method.methodType() == QMetaMethod::Slot &&
                        (members & Slots) != 0) {
                 addMethod(method);
             }
         }
     }
     if ((members & Constructors) != 0) {
         for (index = 0; index < prototype->constructorCount(); ++index)
             addConstructor(prototype->constructor(index));
     }
     if ((members & Properties) != 0) {
         for (index = prototype->propertyOffset(); index < prototype->propertyCount(); ++index)
             addProperty(prototype->property(index));
     }
     if ((members & Enumerators) != 0) {
         for (index = prototype->enumeratorOffset(); index < prototype->enumeratorCount(); ++index)
             addEnumerator(prototype->enumerator(index));
     }
     if ((members & ClassInfos) != 0) {
         for (index = prototype->classInfoOffset(); index < prototype->classInfoCount(); ++index) {
             QMetaClassInfo ci = prototype->classInfo(index);
             addClassInfo(ci.name(), ci.value());
         }
     }
     if ((members & RelatedMetaObjects) != 0) {
 #ifdef Q_NO_DATA_RELOCATION
         const QMetaObjectAccessor *objects = 0;
 #else
         const QMetaObject **objects;
         if (priv(prototype->d.data)->revision < 2) {
             objects = (const QMetaObject **)(prototype->d.extradata);
         } else
 #endif
         {
             const QMetaObjectExtraData *extra = (const QMetaObjectExtraData *)(prototype->d.extradata);
             if (extra)
                 objects = extra->objects;
             else
                 objects = 0;
         }
         if (objects) {
             while (*objects != 0) {
                 addRelatedMetaObject(*objects);
                 ++objects;
             }
         }
     }
     if ((members & StaticMetacall) != 0) {
         if (priv(prototype->d.data)->revision >= 6) {
             const QMetaObjectExtraData *extra =
                 (const QMetaObjectExtraData *)(prototype->d.extradata);
             if (extra && extra->static_metacall)
                 setStaticMetacallFunction(extra->static_metacall);
         }
     }
 }
addMethod() [1/3]
QMetaMethodBuilder QMetaObjectBuilder::addMethod (const QByteArray & signature)
Adds a new public method to this class with the specified signature.
Returns an object that can be used to adjust the other attributes of the method. The signature will be normalized before it is added to the class.
See also
method(), methodCount(), removeMethod(), indexOfMethod()
Definition at line 462 of file qmetaobjectbuilder.cpp.
 {
     int index = d->methods.size();
     d->methods.append(QMetaMethodBuilderPrivate(QMetaMethod::Method, signature));
     return QMetaMethodBuilder(this, index);
 }
addMethod() [2/3]
QMetaMethodBuilder QMetaObjectBuilder::addMethod (const QByteArray & signature, const QByteArray & returnType)
Adds a new public method to this class with the specified signature and returnType.
Returns an object that can be used to adjust the other attributes of the method. The signature and returnType will be normalized before they are added to the class. If returnType is empty, then it indicates that the method has void as its return type.
See also
method(), methodCount(), removeMethod(), indexOfMethod()
Definition at line 480 of file qmetaobjectbuilder.cpp.
 {
     int index = d->methods.size();
     d->methods.append(QMetaMethodBuilderPrivate
         (QMetaMethod::Method, signature, returnType));
     return QMetaMethodBuilder(this, index);
 }
addMethod() [3/3]
QMetaMethodBuilder QMetaObjectBuilder::addMethod (const QMetaMethod & prototype)
Adds a new public method to this class that has the same information as prototype.
This is used to clone the methods of an existing QMetaObject. Returns an object that can be used to adjust the attributes of the method.
This function will detect if prototype is an ordinary method, signal, slot, or constructor and act accordingly.
See also
method(), methodCount(), removeMethod(), indexOfMethod()
Definition at line 499 of file qmetaobjectbuilder.cpp.
 {
     QMetaMethodBuilder method;
     if (prototype.methodType() == QMetaMethod::Method)
         method = addMethod(prototype.signature());
     else if (prototype.methodType() == QMetaMethod::Signal)
         method = addSignal(prototype.signature());
     else if (prototype.methodType() == QMetaMethod::Slot)
         method = addSlot(prototype.signature());
     else if (prototype.methodType() == QMetaMethod::Constructor)
         method = addConstructor(prototype.signature());
     method.setReturnType(prototype.typeName());
     method.setParameterNames(prototype.parameterNames());
     method.setTag(prototype.tag());
     method.setAccess(prototype.access());
     method.setAttributes(prototype.attributes());
     return method;
 }
addProperty() [1/2]
QMetaPropertyBuilder QMetaObjectBuilder::addProperty (const QByteArray & name, const QByteArray & type, int notifierId = -1)
Adds a new readable/writable property to this class with the specified name and type.
Returns an object that can be used to adjust the other attributes of the property. The type will be normalized before it is added to the class. notifierId will be registered as the property's notify signal.
See also
property(), propertyCount(), removeProperty(), indexOfProperty()
Definition at line 598 of file qmetaobjectbuilder.cpp.
Referenced by addConstructor(), QDeclarativeCompiler::buildDynamicMeta(), clone(), QDeclarativeCompiler::compileAlias(), QDeclarativeOpenMetaObjectType::createProperty(), and QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters().
 {
     int index = d->properties.size();
     d->properties.append(QMetaPropertyBuilderPrivate(name, type, notifierId));
     return QMetaPropertyBuilder(this, index);
 }
addProperty() [2/2]
QMetaPropertyBuilder QMetaObjectBuilder::addProperty (const QMetaProperty & prototype)
Adds a new property to this class that has the same information as prototype.
This is used to clone the properties of an existing QMetaObject. Returns an object that can be used to adjust the attributes of the property.
See also
property(), propertyCount(), removeProperty(), indexOfProperty()
Definition at line 613 of file qmetaobjectbuilder.cpp.
 {
     QMetaPropertyBuilder property = addProperty(prototype.name(), prototype.typeName());
     property.setReadable(prototype.isReadable());
     property.setWritable(prototype.isWritable());
     property.setResettable(prototype.isResettable());
     property.setDesignable(prototype.isDesignable());
     property.setScriptable(prototype.isScriptable());
     property.setStored(prototype.isStored());
     property.setEditable(prototype.isEditable());
     property.setUser(prototype.isUser());
     property.setStdCppSet(prototype.hasStdCppSet());
     property.setEnumOrFlag(prototype.isEnumType());
     property.setConstant(prototype.isConstant());
     property.setFinal(prototype.isFinal());
     if (prototype.hasNotifySignal()) {
         // Find an existing method for the notify signal, or add a new one.
         QMetaMethod method = prototype.notifySignal();
         int index = indexOfMethod(method.signature());
         if (index == -1)
             index = addMethod(method).index();
         d->properties[property._index].notifySignal = index;
         d->properties[property._index].setFlag(Notify, true);
     }
     return property;
 }
addRelatedMetaObject()
int QMetaObjectBuilder::addRelatedMetaObject (const QMetaObject * meta)
Adds meta to this class as a related meta object.
Returns the index of the new related meta object entry.
Related meta objects are used when resolving the enumerated type associated with a property, where the enumerated type is in a different class from the property.
See also
relatedMetaObjectCount(), relatedMetaObject()
removeRelatedMetaObject()
Definition at line 703 of file qmetaobjectbuilder.cpp.
Referenced by addClassInfo().
 {
     Q_ASSERT(meta);
     int index = d->relatedMetaObjects.size();
     d->relatedMetaObjects.append(meta);
     return index;
 }
addSignal()
QMetaMethodBuilder QMetaObjectBuilder::addSignal (const QByteArray & signature)
Adds a new signal to this class with the specified signature.
Returns an object that can be used to adjust the other attributes of the signal. The signature will be normalized before it is added to the class.
See also
addMethod(), addSlot(), indexOfSignal()
Definition at line 541 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), QDeclarativeCompiler::compileAlias(), and QDeclarativeOpenMetaObjectType::createProperty().
 {
     int index = d->methods.size();
     d->methods.append(QMetaMethodBuilderPrivate
         (QMetaMethod::Signal, signature, QByteArray(), QMetaMethod::Protected));
     return QMetaMethodBuilder(this, index);
 }
addSlot()
QMetaMethodBuilder QMetaObjectBuilder::addSlot (const QByteArray & signature)
Adds a new public slot to this class with the specified signature.
Returns an object that can be used to adjust the other attributes of the slot. The signature will be normalized before it is added to the class.
See also
addMethod(), addSignal(), indexOfSlot()
Definition at line 526 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta().
 {
     int index = d->methods.size();
     d->methods.append(QMetaMethodBuilderPrivate(QMetaMethod::Slot, signature));
     return QMetaMethodBuilder(this, index);
 }
classInfoCount()
int QMetaObjectBuilder::classInfoCount () const
Returns the number of items of class information in this class, exclusing the number of items of class information in the base class.
See also
addClassInfo(), classInfoName(), classInfoValue(), removeClassInfo()
indexOfClassInfo()
Definition at line 433 of file qmetaobjectbuilder.cpp.
 {
     return d->classInfoNames.size();
 }
classInfoName()
QByteArray QMetaObjectBuilder::classInfoName (int index) const
Returns the name of the item of class information at index in this class.
See also
classInfoCount(), addClassInfo(), classInfoValue(), removeClassInfo()
indexOfClassInfo()
Definition at line 892 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->classInfoNames.size())
         return d->classInfoNames[index];
     else
         return QByteArray();
 }
classInfoValue()
QByteArray QMetaObjectBuilder::classInfoValue (int index) const
Returns the value of the item of class information at index in this class.
See also
classInfoCount(), addClassInfo(), classInfoName(), removeClassInfo()
indexOfClassInfo()
Definition at line 907 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->classInfoValues.size())
         return d->classInfoValues[index];
     else
         return QByteArray();
 }
className()
QByteArray QMetaObjectBuilder::className () const
Returns the name of the class being constructed by this meta object builder.
The default value is an empty QByteArray.
See also
setClassName(), superClass()
Definition at line 318 of file qmetaobjectbuilder.cpp.
 {
     return d->className;
 }
constructor()
QMetaMethodBuilder QMetaObjectBuilder::constructor (int index) const
Returns the constructor at index in this class.
See also
methodCount(), addMethod(), removeMethod(), indexOfConstructor()
Definition at line 828 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->constructors.size())
         return QMetaMethodBuilder(this, -(index + 1));
     else
         return QMetaMethodBuilder();
 }
constructorCount()
int QMetaObjectBuilder::constructorCount () const
Returns the number of constructors in this class.
See also
addConstructor(), constructor(), removeConstructor(), indexOfConstructor()
Definition at line 398 of file qmetaobjectbuilder.cpp.
 {
     return d->constructors.size();
 }
deserialize()
void QMetaObjectBuilder::deserialize (QDataStream & stream, const QMap< QByteArray, const QMetaObject *> & references)
Deserializes a meta object builder from stream into this meta object builder.
The references parameter specifies a mapping from class names to QMetaObject instances for resolving the super class name and related meta objects in the object that is deserialized. The meta object for QObject is implicitly added to references and does not need to be supplied.
The QDataStream::status() value on stream will be set to QDataStream::ReadCorruptData if the input data is corrupt. The status will be set to QDataStream::ReadPastEnd if the input was exhausted before the full meta object was read.
See also
serialize()
Definition at line 1668 of file qmetaobjectbuilder.cpp.
Referenced by resolveClassName().
 {
     QByteArray name;
     const QMetaObject *cl;
     int index;
     // Clear all members in the builder to their default states.
     d->className.clear();
     d->superClass = &QObject::staticMetaObject;
     d->classInfoNames.clear();
     d->classInfoValues.clear();
     d->methods.clear();
     d->properties.clear();
     d->enumerators.clear();
     d->constructors.clear();
     d->relatedMetaObjects.clear();
     d->staticMetacallFunction = 0;
     // Read the class and super class names.
     stream >> d->className;
     stream >> name;
     if (name.isEmpty()) {
         d->superClass = 0;
     } else if ((cl = resolveClassName(references, name)) != 0) {
         d->superClass = cl;
     } else {
         stream.setStatus(QDataStream::ReadCorruptData);
         return;
     }
     // Read the counts for each type of class member.
     int classInfoCount, methodCount, propertyCount;
     int enumeratorCount, constructorCount, relatedMetaObjectCount;
     stream >> classInfoCount;
     stream >> methodCount;
     stream >> propertyCount;
     stream >> enumeratorCount;
     stream >> constructorCount;
     stream >> relatedMetaObjectCount;
     if (classInfoCount < 0 || methodCount < 0 ||
         propertyCount < 0 || enumeratorCount < 0 ||
         constructorCount < 0 || relatedMetaObjectCount < 0) {
         stream.setStatus(QDataStream::ReadCorruptData);
         return;
     }
     // Read the items of class information.
     for (index = 0; index < classInfoCount; ++index) {
         if (stream.status() != QDataStream::Ok)
             return;
         QByteArray value;
         stream >> name;
         stream >> value;
         addClassInfo(name, value);
     }
     // Read the member methods.
     for (index = 0; index < methodCount; ++index) {
         if (stream.status() != QDataStream::Ok)
             return;
         stream >> name;
         addMethod(name);
         QMetaMethodBuilderPrivate *method = &(d->methods[index]);
         stream >> method->returnType;
         stream >> method->parameterNames;
         stream >> method->tag;
         stream >> method->attributes;
         if (method->methodType() == QMetaMethod::Constructor) {
             // Cannot add a constructor in this set of methods.
             stream.setStatus(QDataStream::ReadCorruptData);
             return;
         }
     }
     // Read the properties.
     for (index = 0; index < propertyCount; ++index) {
         if (stream.status() != QDataStream::Ok)
             return;
         QByteArray type;
         stream >> name;
         stream >> type;
         addProperty(name, type);
         QMetaPropertyBuilderPrivate *property = &(d->properties[index]);
         stream >> property->flags;
         stream >> property->notifySignal;
         if (property->notifySignal < -1 ||
             property->notifySignal >= d->methods.size()) {
             // Notify signal method index is out of range.
             stream.setStatus(QDataStream::ReadCorruptData);
             return;
         }
         if (property->notifySignal >= 0 &&
             d->methods[property->notifySignal].methodType() != QMetaMethod::Signal) {
             // Notify signal method index does not refer to a signal.
             stream.setStatus(QDataStream::ReadCorruptData);
             return;
         }
     }
     // Read the enumerators.
     for (index = 0; index < enumeratorCount; ++index) {
         if (stream.status() != QDataStream::Ok)
             return;
         stream >> name;
         addEnumerator(name);
         QMetaEnumBuilderPrivate *enumerator = &(d->enumerators[index]);
         stream >> enumerator->isFlag;
         stream >> enumerator->keys;
         stream >> enumerator->values;
         if (enumerator->keys.size() != enumerator->values.size()) {
             // Mismatch between number of keys and number of values.
             stream.setStatus(QDataStream::ReadCorruptData);
             return;
         }
     }
     // Read the constructor methods.
     for (index = 0; index < constructorCount; ++index) {
         if (stream.status() != QDataStream::Ok)
             return;
         stream >> name;
         addConstructor(name);
         QMetaMethodBuilderPrivate *method = &(d->constructors[index]);
         stream >> method->returnType;
         stream >> method->parameterNames;
         stream >> method->tag;
         stream >> method->attributes;
         if (method->methodType() != QMetaMethod::Constructor) {
             // The type must be Constructor.
             stream.setStatus(QDataStream::ReadCorruptData);
             return;
         }
     }
     // Read the related meta objects.
 #ifdef Q_NO_DATA_RELOCATION
     //### What do we do here
 #else
     for (index = 0; index < relatedMetaObjectCount; ++index) {
         if (stream.status() != QDataStream::Ok)
             return;
         stream >> name;
         cl = resolveClassName(references, name);
         if (!cl) {
             stream.setStatus(QDataStream::ReadCorruptData);
             return;
         }
         addRelatedMetaObject(cl);
     }
 #endif
     // Read the extra data block, which is reserved for future use.
     stream >> name;
 }
enumerator()
QMetaEnumBuilder QMetaObjectBuilder::enumerator (int index) const
Returns the enumerator at index in this class.
See also
enumeratorCount(), addEnumerator(), removeEnumerator()
indexOfEnumerator()
Definition at line 855 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->enumerators.size())
         return QMetaEnumBuilder(this, index);
     else
         return QMetaEnumBuilder();
 }
enumeratorCount()
int QMetaObjectBuilder::enumeratorCount () const
Returns the number of enumerators in this class, excluding the number of enumerators in the base class.
See also
addEnumerator(), enumerator(), removeEnumerator()
indexOfEnumerator()
Definition at line 421 of file qmetaobjectbuilder.cpp.
 {
     return d->enumerators.size();
 }
flags()
QMetaObjectBuilder::MetaObjectFlags QMetaObjectBuilder::flags () const
Returns the flags of the class being constructed by this meta object builder.
See also
setFlags()
Definition at line 365 of file qmetaobjectbuilder.cpp.
 {
     return (QMetaObjectBuilder::MetaObjectFlags)d->flags;
 }
fromRelocatableData()
void QMetaObjectBuilder::fromRelocatableData (QMetaObject * output, const QMetaObject * superclass, const QByteArray & data) static
Definition at line 1501 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), and QDeclarativeVME::run().
 {
     if (!output)
         return;
     const char *buf = data.constData();
     const QMetaObject *dataMo = reinterpret_cast<const QMetaObject *>(buf);
     quintptr stringdataOffset = (quintptr)dataMo->d.stringdata;
     quintptr dataOffset = (quintptr)dataMo->d.data;
     output->d.superdata = superclass;
     output->d.stringdata = buf + stringdataOffset;
     output->d.data = reinterpret_cast<const uint *>(buf + dataOffset);
 }
indexOfClassInfo()
int QMetaObjectBuilder::indexOfClassInfo (const QByteArray & name)
Finds an item of class information with the specified name and returns its index; otherwise returns -1.
See also
classInfoName(), classInfoValue(), classInfoCount(), addClassInfo()
removeClassInfo()
Definition at line 1112 of file qmetaobjectbuilder.cpp.
 {
     for (int index = 0; index < d->classInfoNames.size(); ++index) {
         if (name == d->classInfoNames[index])
             return index;
     }
     return -1;
 }
indexOfConstructor()
int QMetaObjectBuilder::indexOfConstructor (const QByteArray & signature)
Finds a constructor with the specified signature and returns its index; otherwise returns -1.
The signature will be normalized by this method.
See also
constructor(), constructorCount(), addConstructor(), removeConstructor()
Definition at line 1065 of file qmetaobjectbuilder.cpp.
 {
     QByteArray sig = QMetaObject::normalizedSignature(signature);
     for (int index = 0; index < d->constructors.size(); ++index) {
         if (sig == d->constructors[index].signature)
             return index;
     }
     return -1;
 }
indexOfEnumerator()
int QMetaObjectBuilder::indexOfEnumerator (const QByteArray & name)
Finds an enumerator with the specified name and returns its index; otherwise returns -1.
See also
enumertor(), enumeratorCount(), addEnumerator(), removeEnumerator()
Definition at line 1096 of file qmetaobjectbuilder.cpp.
 {
     for (int index = 0; index < d->enumerators.size(); ++index) {
         if (name == d->enumerators[index].name)
             return index;
     }
     return -1;
 }
indexOfMethod()
int QMetaObjectBuilder::indexOfMethod (const QByteArray & signature)
Finds a method with the specified signature and returns its index; otherwise returns -1.
The signature will be normalized by this method.
See also
method(), methodCount(), addMethod(), removeMethod()
Definition at line 1015 of file qmetaobjectbuilder.cpp.
 {
     QByteArray sig = QMetaObject::normalizedSignature(signature);
     for (int index = 0; index < d->methods.size(); ++index) {
         if (sig == d->methods[index].signature)
             return index;
     }
     return -1;
 }
indexOfProperty()
int QMetaObjectBuilder::indexOfProperty (const QByteArray & name)
Finds a property with the specified name and returns its index; otherwise returns -1.
See also
property(), propertyCount(), addProperty(), removeProperty()
Definition at line 1081 of file qmetaobjectbuilder.cpp.
 {
     for (int index = 0; index < d->properties.size(); ++index) {
         if (name == d->properties[index].name)
             return index;
     }
     return -1;
 }
indexOfSignal()
int QMetaObjectBuilder::indexOfSignal (const QByteArray & signature)
Finds a signal with the specified signature and returns its index; otherwise returns -1.
The signature will be normalized by this method.
See also
indexOfMethod(), indexOfSlot()
Definition at line 1031 of file qmetaobjectbuilder.cpp.
 {
     QByteArray sig = QMetaObject::normalizedSignature(signature);
     for (int index = 0; index < d->methods.size(); ++index) {
         if (sig == d->methods[index].signature &&
                 d->methods[index].methodType() == QMetaMethod::Signal)
             return index;
     }
     return -1;
 }
indexOfSlot()
int QMetaObjectBuilder::indexOfSlot (const QByteArray & signature)
Finds a slot with the specified signature and returns its index; otherwise returns -1.
The signature will be normalized by this method.
See also
indexOfMethod(), indexOfSignal()
Definition at line 1048 of file qmetaobjectbuilder.cpp.
 {
     QByteArray sig = QMetaObject::normalizedSignature(signature);
     for (int index = 0; index < d->methods.size(); ++index) {
         if (sig == d->methods[index].signature &&
                 d->methods[index].methodType() == QMetaMethod::Slot)
             return index;
     }
     return -1;
 }
method()
QMetaMethodBuilder QMetaObjectBuilder::method (int index) const
Returns the method at index in this class.
See also
methodCount(), addMethod(), removeMethod(), indexOfMethod()
Definition at line 815 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->methods.size())
         return QMetaMethodBuilder(this, index);
     else
         return QMetaMethodBuilder();
 }
methodCount()
int QMetaObjectBuilder::methodCount () const
Returns the number of methods in this class, excluding the number of methods in the base class.
These include signals and slots as well as normal member functions.
See also
addMethod(), method(), removeMethod(), indexOfMethod()
Definition at line 388 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), and QDeclarativeCompiler::compileAlias().
 {
     return d->methods.size();
 }
property()
QMetaPropertyBuilder QMetaObjectBuilder::property (int index) const
Returns the property at index in this class.
See also
methodCount(), addMethod(), removeMethod(), indexOfProperty()
Definition at line 841 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeOpenMetaObject::name().
 {
     if (index >= 0 && index < d->properties.size())
         return QMetaPropertyBuilder(this, index);
     else
         return QMetaPropertyBuilder();
 }
propertyCount()
int QMetaObjectBuilder::propertyCount () const
Returns the number of properties in this class, excluding the number of properties in the base class.
See also
addProperty(), property(), removeProperty(), indexOfProperty()
Definition at line 409 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeOpenMetaObjectType::createProperty().
 {
     return d->properties.size();
 }
relatedMetaObject()
const QMetaObject * QMetaObjectBuilder::relatedMetaObject (int index) const
Returns the related meta object at index in this class.
Related meta objects are used when resolving the enumerated type associated with a property, where the enumerated type is in a different class from the property.
See also
relatedMetaObjectCount(), addRelatedMetaObject()
removeRelatedMetaObject()
Definition at line 873 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->relatedMetaObjects.size())
 #ifdef Q_NO_DATA_RELOCATION
         return &((*(d->relatedMetaObjects[index]))());
 #else
         return d->relatedMetaObjects[index];
 #endif
     else
         return 0;
 }
relatedMetaObjectCount()
int QMetaObjectBuilder::relatedMetaObjectCount () const
Returns the number of related meta objects that are associated with this class.
Related meta objects are used when resolving the enumerated type associated with a property, where the enumerated type is in a different class from the property.
See also
addRelatedMetaObject(), relatedMetaObject()
removeRelatedMetaObject()
Definition at line 449 of file qmetaobjectbuilder.cpp.
 {
     return d->relatedMetaObjects.size();
 }
removeClassInfo()
void QMetaObjectBuilder::removeClassInfo (int index)
Removes the item of class information at index from this class.
The indices of all following items will be adjusted downwards by 1.
See also
classInfoCount(), addClassInfo(), classInfoName(), classInfoValue()
indexOfClassInfo()
Definition at line 983 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->classInfoNames.size()) {
         d->classInfoNames.removeAt(index);
         d->classInfoValues.removeAt(index);
     }
 }
removeConstructor()
void QMetaObjectBuilder::removeConstructor (int index)
Removes the constructor at index from this class.
The indices of all following constructors will be adjusted downwards by 1.
See also
constructorCount(), addConstructor(), constructor()
indexOfConstructor()
Definition at line 945 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->constructors.size())
         d->constructors.removeAt(index);
 }
removeEnumerator()
void QMetaObjectBuilder::removeEnumerator (int index)
Removes the enumerator at index from this class.
The indices of all following enumerators will be adjusted downwards by 1.
See also
enumertorCount(), addEnumerator(), enumerator()
indexOfEnumerator()
Definition at line 970 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->enumerators.size())
         d->enumerators.removeAt(index);
 }
removeMethod()
void QMetaObjectBuilder::removeMethod (int index)
Removes the method at index from this class.
The indices of all following methods will be adjusted downwards by 1. If the method is registered as a notify signal on a property, then the notify signal will be removed from the property.
See also
methodCount(), addMethod(), method(), indexOfMethod()
Definition at line 923 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->methods.size()) {
         d->methods.removeAt(index);
         for (int prop = 0; prop < d->properties.size(); ++prop) {
             // Adjust the indices of property notify signal references.
             if (d->properties[prop].notifySignal == index) {
                 d->properties[prop].notifySignal = -1;
                 d->properties[prop].setFlag(Notify, false);
             } else if (d->properties[prop].notifySignal > index)
                 (d->properties[prop].notifySignal)--;
         }
     }
 }
removeProperty()
void QMetaObjectBuilder::removeProperty (int index)
Removes the property at index from this class.
The indices of all following properties will be adjusted downwards by 1.
See also
propertyCount(), addProperty(), property(), indexOfProperty()
Definition at line 957 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->properties.size())
         d->properties.removeAt(index);
 }
removeRelatedMetaObject()
void QMetaObjectBuilder::removeRelatedMetaObject (int index)
Removes the related meta object at index from this class.
The indices of all following related meta objects will be adjusted downwards by 1.
Related meta objects are used when resolving the enumerated type associated with a property, where the enumerated type is in a different class from the property.
See also
relatedMetaObjectCount(), addRelatedMetaObject()
relatedMetaObject()
Definition at line 1003 of file qmetaobjectbuilder.cpp.
 {
     if (index >= 0 && index < d->relatedMetaObjects.size())
         d->relatedMetaObjects.removeAt(index);
 }
serialize()
void QMetaObjectBuilder::serialize (QDataStream & stream) const
Serializes the contents of the meta object builder onto stream.
See also
deserialize()
Definition at line 1560 of file qmetaobjectbuilder.cpp.
 {
     int index;
     // Write the class and super class names.
     stream << d->className;
     if (d->superClass)
         stream << QByteArray(d->superClass->className());
     else
         stream << QByteArray();
     // Write the counts for each type of class member.
     stream << d->classInfoNames.size();
     stream << d->methods.size();
     stream << d->properties.size();
     stream << d->enumerators.size();
     stream << d->constructors.size();
     stream << d->relatedMetaObjects.size();
     // Write the items of class information.
     for (index = 0; index < d->classInfoNames.size(); ++index) {
         stream << d->classInfoNames[index];
         stream << d->classInfoValues[index];
     }
     // Write the methods.
     for (index = 0; index < d->methods.size(); ++index) {
         const QMetaMethodBuilderPrivate *method = &(d->methods[index]);
         stream << method->signature;
         stream << method->returnType;
         stream << method->parameterNames;
         stream << method->tag;
         stream << method->attributes;
     }
     // Write the properties.
     for (index = 0; index < d->properties.size(); ++index) {
         const QMetaPropertyBuilderPrivate *property = &(d->properties[index]);
         stream << property->name;
         stream << property->type;
         stream << property->flags;
         stream << property->notifySignal;
     }
     // Write the enumerators.
     for (index = 0; index < d->enumerators.size(); ++index) {
         const QMetaEnumBuilderPrivate *enumerator = &(d->enumerators[index]);
         stream << enumerator->name;
         stream << enumerator->isFlag;
         stream << enumerator->keys;
         stream << enumerator->values;
     }
     // Write the constructors.
     for (index = 0; index < d->constructors.size(); ++index) {
         const QMetaMethodBuilderPrivate *method = &(d->constructors[index]);
         stream << method->signature;
         stream << method->returnType;
         stream << method->parameterNames;
         stream << method->tag;
         stream << method->attributes;
     }
     // Write the related meta objects.
 #ifdef Q_NO_DATA_RELOCATION
     //### What do we do here?
 #else
     for (index = 0; index < d->relatedMetaObjects.size(); ++index) {
         const QMetaObject *meta = d->relatedMetaObjects[index];
         stream << QByteArray(meta->className());
     }
 #endif
     // Add an extra empty QByteArray for additional data in future versions.
     // This should help maintain backwards compatibility, allowing older
     // versions to read newer data.
     stream << QByteArray();
 }
setClassName()
void QMetaObjectBuilder::setClassName (const QByteArray & name)
Sets the name of the class being constructed by this meta object builder.
See also
className(), setSuperClass()
Definition at line 329 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta(), and QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters().
 {
     d->className = name;
 }
setFlags()
void QMetaObjectBuilder::setFlags (MetaObjectFlags flags)
Sets the flags of the class being constructed by this meta object builder.
See also
flags()
Definition at line 376 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta().
 {
     d->flags = flags;
 }
setStaticMetacallFunction()
void QMetaObjectBuilder::setStaticMetacallFunction (QMetaObjectBuilder::StaticMetacallFunction value)
Sets the static metacall function to use to construct objects of this class to value.
The default value is null.
See also
staticMetacallFunction()
Definition at line 1548 of file qmetaobjectbuilder.cpp.
Referenced by staticMetacallFunction().
 {
     d->staticMetacallFunction = value;
 }
setSuperClass()
void QMetaObjectBuilder::setSuperClass (const QMetaObject * meta)
Sets the superclass meta object of the class being constructed by this meta object builder to meta.
The meta parameter must not be null.
See also
superClass(), setClassName()
Definition at line 353 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters().
 {
     Q_ASSERT(meta);
     d->superClass = meta;
 }
staticMetacallFunction()
QMetaObjectBuilder::StaticMetacallFunction QMetaObjectBuilder::staticMetacallFunction () const
Returns the static metacall function to use to construct objects of this class.
The default value is null.
See also
setStaticMetacallFunction()
Definition at line 1536 of file qmetaobjectbuilder.cpp.
 {
     return d->staticMetacallFunction;
 }
superClass()
const QMetaObject * QMetaObjectBuilder::superClass () const
Returns the superclass meta object of the class being constructed by this meta object builder.
The default value is the meta object for QObject.
See also
setSuperClass(), className()
Definition at line 341 of file qmetaobjectbuilder.cpp.
 {
     return d->superClass;
 }
toMetaObject()
QMetaObject * QMetaObjectBuilder::toMetaObject () const
Converts this meta object builder into a concrete QMetaObject.
The return value should be deallocated using qFree() once it is no longer needed.
The returned meta object is a snapshot of the state of the QMetaObjectBuilder. Any further modifications to the QMetaObjectBuilder will not be reflected in previous meta objects returned by this method.
Definition at line 1454 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeOpenMetaObjectType::createProperty(), QDeclarativeTypePrivate::init(), and QDeclarativeBoundSignalParameters::QDeclarativeBoundSignalParameters().
 {
     int size = buildMetaObject(d, 0, false);
     char *buf = reinterpret_cast<char *>(qMalloc(size));
     memset(buf, 0, size);
     buildMetaObject(d, buf, false);
     return reinterpret_cast<QMetaObject *>(buf);
 }
toRelocatableData()
QByteArray QMetaObjectBuilder::toRelocatableData (bool * ok = 0) const
Definition at line 1477 of file qmetaobjectbuilder.cpp.
Referenced by QDeclarativeCompiler::buildDynamicMeta().
 {
     int size = buildMetaObject(d, 0, true);
     if (size == -1) {
         if (ok) *ok = false;
         return QByteArray();
     }
     QByteArray data;
     data.resize(size);
     char *buf = data.data();
     memset(buf, 0, size);
     buildMetaObject(d, buf, true);
     if (ok) *ok = true;
     return data;
 }
Friends and Related Functions
QMetaEnumBuilder
friend class QMetaEnumBuilder friend
Definition at line 195 of file qmetaobjectbuilder_p.h.
QMetaMethodBuilder
friend class QMetaMethodBuilder friend
Definition at line 193 of file qmetaobjectbuilder_p.h.
QMetaPropertyBuilder
friend class QMetaPropertyBuilder friend
Definition at line 194 of file qmetaobjectbuilder_p.h.
Properties
d
QMetaObjectBuilderPrivate* QMetaObjectBuilder::d private
Definition at line 191 of file qmetaobjectbuilder_p.h.
The documentation for this class was generated from the following files:
/src/declarative/qml/qmetaobjectbuilder_p.h
/src/declarative/qml/qmetaobjectbuilder.cpp