Qt 4.8: QDeclarativeIntegerCache Class Reference
QDeclarativeIntegerCache Class Reference
#include <qdeclarativeintegercache_p.h>
Classes
struct Data
Public Functions
void add (const QString &, int)
int count () const
QString findId (int value) const
QDeclarativeIntegerCache (QDeclarativeEngine *)
int value (const QString &)
int value (const QScriptDeclarativeClass::Identifier &id) const
virtual ~QDeclarativeIntegerCache ()
Public Functions inherited from QDeclarativeRefCount
void addref ()
QDeclarativeRefCount ()
void release ()
virtual ~QDeclarativeRefCount ()
Public Functions inherited from QDeclarativeCleanup
QDeclarativeCleanup (QDeclarativeEngine *)
virtual ~QDeclarativeCleanup ()
Protected Functions
virtual void clear ()
Private Types
typedef QHash< QScriptDeclarativeClass::Identifier, Data * > IdentifierCache
typedef QHash< QString, Data * > StringCache
Properties
QDeclarativeEngine * engine
IdentifierCache identifierCache
StringCache stringCache
Detailed Description
Definition at line 67 of file qdeclarativeintegercache_p.h.
Typedefs
IdentifierCache
typedef QHash<QScriptDeclarativeClass::Identifier, Data *> QDeclarativeIntegerCache::IdentifierCache private
Definition at line 91 of file qdeclarativeintegercache_p.h.
StringCache
typedef QHash<QString, Data *> QDeclarativeIntegerCache::StringCache private
Definition at line 90 of file qdeclarativeintegercache_p.h.
Constructors and Destructors
QDeclarativeIntegerCache()
QDeclarativeIntegerCache::QDeclarativeIntegerCache (QDeclarativeEngine * e)
Definition at line 49 of file qdeclarativeintegercache.cpp.
 : QDeclarativeCleanup(e), engine(e)
 {
 }
~QDeclarativeIntegerCache()
QDeclarativeIntegerCache::~QDeclarativeIntegerCache () virtual
Definition at line 54 of file qdeclarativeintegercache.cpp.
 {
     clear();
 }
Functions
add()
void QDeclarativeIntegerCache::add (const QString & id, int value)
Definition at line 77 of file qdeclarativeintegercache.cpp.
Referenced by QDeclarativeCompiler::genContextCache(), and QDeclarativeContext::setContextProperty().
 {
     Q_ASSERT(!stringCache.contains(id));
     QDeclarativeEnginePrivate *enginePriv = QDeclarativeEnginePrivate::get(engine);
     // ### use contextClass
     Data *d = new Data(enginePriv->objectClass->createPersistentIdentifier(id), value);
     stringCache.insert(id, d);
     identifierCache.insert(d->identifier, d);
 }
clear()
void QDeclarativeIntegerCache::clear () protected virtual
Implements QDeclarativeCleanup.
Definition at line 59 of file qdeclarativeintegercache.cpp.
Referenced by ~QDeclarativeIntegerCache().
 {
     qDeleteAll(stringCache);
     stringCache.clear();
     identifierCache.clear();
     engine = 0;
 }
count()
int QDeclarativeIntegerCache::count () const inline
Definition at line 104 of file qdeclarativeintegercache_p.h.
Referenced by QDeclarativeContextData::setIdPropertyData().
 {
     return stringCache.count();
 }
findId()
QString QDeclarativeIntegerCache::findId (int value) const
Definition at line 67 of file qdeclarativeintegercache.cpp.
Referenced by QDeclarativeContextData::findObjectId().
 {
     for (StringCache::ConstIterator iter = stringCache.begin();
             iter != stringCache.end(); ++iter) {
         if (iter.value() && iter.value()->value == value)
             return iter.key();
     }
     return QString();
 }
value() [1/2]
int QDeclarativeIntegerCache::value (const QString & id)
Definition at line 90 of file qdeclarativeintegercache.cpp.
Referenced by add(), QDeclarativeContext::contextProperty(), QDeclarativeCompiledBindingsPrivate::findgeneric(), findId(), QDeclarativeContextScriptClass::queryProperty(), and QDeclarativeContext::setContextProperty().
 {
     Data *d = stringCache.value(id);
     return d?d->value:-1;
 }
value() [2/2]
int QDeclarativeIntegerCache::value (const QScriptDeclarativeClass::Identifier & id) const inline
Definition at line 98 of file qdeclarativeintegercache_p.h.
 {
     Data *d = identifierCache.value(id);
     return d?d->value:-1;
 }
Properties
engine
QDeclarativeEngine* QDeclarativeIntegerCache::engine private
Definition at line 95 of file qdeclarativeintegercache_p.h.
Referenced by add(), and clear().
identifierCache
IdentifierCache QDeclarativeIntegerCache::identifierCache private
Definition at line 94 of file qdeclarativeintegercache_p.h.
Referenced by add(), clear(), and value().
stringCache
StringCache QDeclarativeIntegerCache::stringCache private
Definition at line 93 of file qdeclarativeintegercache_p.h.
Referenced by add(), clear(), count(), findId(), and value().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeintegercache_p.h
/src/declarative/qml/qdeclarativeintegercache.cpp