Qt 4.8: QWindowsVistaStylePrivate Class Reference
QWindowsVistaStylePrivate Class Reference
#include <qwindowsvistastyle_p.h>
Public Functions
QWindowsVistaStylePrivate ()
void startAnimation (QWindowsVistaAnimation *)
void stopAnimation (const QWidget *)
void timerEvent ()
bool transitionsEnabled () const
QWidget * treeViewHelper ()
QWindowsVistaAnimation * widgetAnimation (const QWidget *) const
~QWindowsVistaStylePrivate ()
Public Functions inherited from QWindowsXPStylePrivate
HBITMAP buffer (int w=0, int h=0)
Returns a native buffer (DIB section) of at least the size of (x , y).
HDC bufferHDC ()
void cleanup (bool force=false)
void cleanupHandleMap ()
void drawBackground (XPThemeData &themeData)
Main theme drawing function.
void drawBackgroundDirectly (XPThemeData &themeData)
This function draws the theme parts directly to the paintengines HDC.
void drawBackgroundThruNativeBuffer (XPThemeData &themeData)
This function uses a secondary Native doublebuffer for painting parts.
bool fixAlphaChannel (const QRect &rect)
When the theme engine paints both a true alpha pixmap and a glyph into our buffer, the glyph might not contain a proper alpha value.
bool hasAlphaChannel (const QRect &rect)
Returns true if the native doublebuffer contains pixels with varying alpha value.
bool hasAnyData (const QRect &rect)
Returns true if the native doublebuffer contains a pixel which has a non-0xFF alpha value.
void init (bool force=false)
bool isTransparent (XPThemeData &themeData)
Returns true if the part contains any transparency at all.
QWindowsXPStylePrivate ()
QRegion region (XPThemeData &themeData)
void setTransparency (QWidget *widget, XPThemeData &themeData)
Sets the parts region on a window.
bool swapAlphaChannel (const QRect &rect, bool allPixels=false)
Swaps the alpha values on certain pixels: 0xFF?????? -> 0x00?????? 0x00?????? -> 0xFF?????? Used to determin the mask of a non-alpha transparent pixmap in the native doublebuffer, and swap the alphas so we may paint the image as a Premultiplied QImage with drawImage(), and obtain the mask transparency.
const QPixmap * tabBody (QWidget *widget)
Returns the pointer to a tab widgets body pixmap, scaled to the height of the screen.
~QWindowsXPStylePrivate ()
Public Functions inherited from QWindowsStylePrivate
bool altDown () const
bool hasSeenAlt (const QWidget *widget) const
QWindowsStylePrivate ()
void startAnimation (QObject *o, QProgressBar *bar)
void stopAnimation (QObject *o, QProgressBar *bar)
Public Functions inherited from QCommonStylePrivate
bool isViewItemCached (const QStyleOptionViewItemV4 &option) const
QCommonStylePrivate ()
void tabLayout (const QStyleOptionTabV3 *opt, const QWidget *widget, QRect *textRect, QRect *pixmapRect) const
void viewItemDrawText (QPainter *p, const QStyleOptionViewItemV4 *option, const QRect &rect) const
void viewItemLayout (const QStyleOptionViewItemV4 *opt, QRect *checkRect, QRect *pixmapRect, QRect *textRect, bool sizehint) const
Set sizehint to false to layout the elements inside opt->rect.
QSize viewItemSize (const QStyleOptionViewItemV4 *option, int role) const
~QCommonStylePrivate ()
Public Functions inherited from QStylePrivate
QStylePrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static bool resolveSymbols ()
Returns true if all the necessary theme engine symbols were resolved.
static bool useVista ()
Static Public Functions inherited from QWindowsXPStylePrivate
static bool isItemViewDelegateLineEdit (const QWidget *widget)
static bool resolveSymbols ()
Returns true if all the necessary theme engine symbols were resolved.
static bool useXP (bool update=false)
static HWND winId (const QWidget *widget)
This function will always return a valid window handle, and might create a limbo widget to do so.
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Properties
QList< QWindowsVistaAnimation * > animations
QBasicTimer animationTimer
QWidget * m_treeViewHelper
Additional Inherited Members
Public Types inherited from QWindowsStylePrivate
enum {
windowsItemFrame = 2, windowsSepHeight = 9, windowsItemHMargin = 3, windowsItemVMargin = 2,
windowsArrowHMargin = 6, windowsRightBorder = 15, windowsCheckMarkWidth = 12
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Public Variables inherited from QWindowsXPStylePrivate
QIcon dockClose
QIcon dockFloat
QRgb groupBoxTextColor
QRgb groupBoxTextColorDisabled
bool hasInitColors
QRgb sliderTickColor
Public Variables inherited from QWindowsStylePrivate
QColor activeCaptionColor
QColor activeGradientCaptionColor
bool alt_down
QList< QProgressBar * > animatedProgressBars
int animateStep
int animateTimer
int animationFps
QColor inactiveCaptionColor
QColor inactiveCaptionText
QColor inactiveGradientCaptionColor
int menuBarTimer
QList< const QWidget * > seenAlt
QElapsedTimer startTime
Public Variables inherited from QCommonStylePrivate
QStyleOptionViewItemV4 * cachedOption
QRect checkRect
QRect decorationRect
QRect displayRect
QIcon tabBarcloseButtonIcon
Public Variables inherited from QStylePrivate
int layoutSpacingIndex
QStyle * proxyStyle
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Static Public Variables inherited from QWindowsXPStylePrivate
static QMap< QString, HTHEME > * handleMap = 0
Detailed Description
Definition at line 194 of file qwindowsvistastyle_p.h.
Constructors and Destructors
QWindowsVistaStylePrivate()
QWindowsVistaStylePrivate::QWindowsVistaStylePrivate ()
Definition at line 2499 of file qwindowsvistastyle.cpp.
                                                      :
     QWindowsXPStylePrivate(), m_treeViewHelper(0)
 {
     resolveSymbols();
 }
~QWindowsVistaStylePrivate()
QWindowsVistaStylePrivate::~QWindowsVistaStylePrivate ()
Definition at line 2505 of file qwindowsvistastyle.cpp.
 {
     qDeleteAll(animations);
     delete m_treeViewHelper;
 }
Functions
resolveSymbols()
bool QWindowsVistaStylePrivate::resolveSymbols () static
Returns true if all the necessary theme engine symbols were resolved.
Warning
This function is not part of the public interface.
Definition at line 2585 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStylePrivate().
 {
     static bool tried = false;
     if (!tried) {
         QSystemLibrary themeLib(QLatin1String("uxtheme"));
         pSetWindowTheme         = (PtrSetWindowTheme        )themeLib.resolve("SetWindowTheme");
         pIsThemePartDefined     = (PtrIsThemePartDefined    )themeLib.resolve("IsThemePartDefined");
         pGetThemePartSize       = (PtrGetThemePartSize      )themeLib.resolve("GetThemePartSize");
         pOpenThemeData          = (PtrOpenThemeData         )themeLib.resolve("OpenThemeData");
         pCloseThemeData         = (PtrCloseThemeData        )themeLib.resolve("CloseThemeData");
         pDrawThemeBackground    = (PtrDrawThemeBackground   )themeLib.resolve("DrawThemeBackground");
         pDrawThemeBackgroundEx  = (PtrDrawThemeBackgroundEx )themeLib.resolve("DrawThemeBackgroundEx");
         pGetCurrentThemeName    = (PtrGetCurrentThemeName   )themeLib.resolve("GetCurrentThemeName");
         pGetThemeBool           = (PtrGetThemeBool          )themeLib.resolve("GetThemeBool");
         pGetThemeColor          = (PtrGetThemeColor         )themeLib.resolve("GetThemeColor");
         pGetThemeEnumValue      = (PtrGetThemeEnumValue     )themeLib.resolve("GetThemeEnumValue");
         pGetThemeFilename       = (PtrGetThemeFilename      )themeLib.resolve("GetThemeFilename");
         pGetThemeFont           = (PtrGetThemeFont          )themeLib.resolve("GetThemeFont");
         pGetThemeInt            = (PtrGetThemeInt           )themeLib.resolve("GetThemeInt");
         pGetThemeIntList        = (PtrGetThemeIntList       )themeLib.resolve("GetThemeIntList");
         pGetThemeMargins        = (PtrGetThemeMargins       )themeLib.resolve("GetThemeMargins");
         pGetThemeMetric         = (PtrGetThemeMetric        )themeLib.resolve("GetThemeMetric");
         pGetThemePartSize       = (PtrGetThemePartSize      )themeLib.resolve("GetThemePartSize");
         pGetThemePosition       = (PtrGetThemePosition      )themeLib.resolve("GetThemePosition");
         pGetThemeRect           = (PtrGetThemeRect          )themeLib.resolve("GetThemeRect");
         pGetThemeString         = (PtrGetThemeString        )themeLib.resolve("GetThemeString");
         pGetThemeTransitionDuration = (PtrGetThemeTransitionDuration)themeLib.resolve("GetThemeTransitionDuration");
         pGetThemePropertyOrigin = (PtrGetThemePropertyOrigin)themeLib.resolve("GetThemePropertyOrigin");
         tried = true;
     }
     return pGetThemeTransitionDuration != 0;
 }
startAnimation()
void QWindowsVistaStylePrivate::startAnimation (QWindowsVistaAnimation * t)
Definition at line 2544 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 {
     Q_Q(QWindowsVistaStyle);
     stopAnimation(t->widget());
     animations.append(t);
     if (animations.size() > 0 && !animationTimer.isActive()) {
         animationTimer.start(45, q);
     }
 }
stopAnimation()
void QWindowsVistaStylePrivate::stopAnimation (const QWidget * w)
Definition at line 2533 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QWindowsVistaStyle::drawPrimitive(), startAnimation(), and QWindowsVistaStyle::unpolish().
 {
     for (int i = animations.size() - 1 ; i >= 0 ; --i) {
         if (animations[i]->widget() == w) {
             QWindowsVistaAnimation *a = animations.takeAt(i);
             delete a;
             break;
         }
     }
 }
timerEvent()
void QWindowsVistaStylePrivate::timerEvent ()
Definition at line 2511 of file qwindowsvistastyle.cpp.
 {
     for (int i = animations.size() - 1 ; i >= 0 ; --i) {
         if (animations[i]->widget())
             animations[i]->widget()->update();
         if (!animations[i]->widget() ||
             !animations[i]->widget()->isVisible() ||
             animations[i]->widget()->window()->isMinimized() ||
             !animations[i]->running() ||
             !QWindowsVistaStylePrivate::useVista())
         {
             QWindowsVistaAnimation *a = animations.takeAt(i);
             delete a;
         }
     }
     if (animations.size() == 0 && animationTimer.isActive()) {
         animationTimer.stop();
     }
 }
transitionsEnabled()
bool QWindowsVistaStylePrivate::transitionsEnabled () const
Definition at line 2554 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 {
     BOOL animEnabled = false;
     if (SystemParametersInfo(SPI_GETCLIENTAREAANIMATION, 0, &animEnabled, 0))
     {
         if (animEnabled)
             return true;
     }
     return false;
 }
treeViewHelper()
QWidget * QWindowsVistaStylePrivate::treeViewHelper ()
Definition at line 2622 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStyle::drawPrimitive().
 {
     if (!m_treeViewHelper) {
         m_treeViewHelper = new QWidget(0);
         pSetWindowTheme(m_treeViewHelper->winId(), L"explorer", NULL);
     }
     return m_treeViewHelper;
 }
useVista()
bool QWindowsVistaStylePrivate::useVista () inline static
Definition at line 139 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), QWindowsVistaStyle::drawPrimitive(), QWindowsVistaStyle::hitTestComplexControl(), QWindowsVistaStyle::pixelMetric(), QWindowsVistaStyle::sizeFromContents(), QWindowsVistaStyle::standardIconImplementation(), QWindowsVistaStyle::standardPixmap(), QWindowsVistaStyle::subControlRect(), QWindowsVistaStyle::subElementRect(), and timerEvent().
 {
     return (QWindowsVistaStylePrivate::useXP() &&
             (QSysInfo::WindowsVersion >= QSysInfo::WV_VISTA &&
              (QSysInfo::WindowsVersion & QSysInfo::WV_NT_based)));
 }
widgetAnimation()
QWindowsVistaAnimation * QWindowsVistaStylePrivate::widgetAnimation (const QWidget * widget) const
Definition at line 2566 of file qwindowsvistastyle.cpp.
Referenced by QWindowsVistaStyle::drawComplexControl(), QWindowsVistaStyle::drawControl(), and QWindowsVistaStyle::drawPrimitive().
 {
     if (!widget)
         return 0;
     foreach (QWindowsVistaAnimation *a, animations) {
         if (a->widget() == widget)
             return a;
     }
     return 0;
 }
Properties
animations
QList<QWindowsVistaAnimation*> QWindowsVistaStylePrivate::animations private
Definition at line 211 of file qwindowsvistastyle_p.h.
Referenced by startAnimation(), stopAnimation(), timerEvent(), widgetAnimation(), and ~QWindowsVistaStylePrivate().
animationTimer
QBasicTimer QWindowsVistaStylePrivate::animationTimer private
Definition at line 212 of file qwindowsvistastyle_p.h.
Referenced by startAnimation(), and timerEvent().
m_treeViewHelper
QWidget* QWindowsVistaStylePrivate::m_treeViewHelper private
Definition at line 213 of file qwindowsvistastyle_p.h.
Referenced by treeViewHelper(), and ~QWindowsVistaStylePrivate().
The documentation for this class was generated from the following files:
/src/gui/styles/qwindowsvistastyle_p.h
/src/gui/styles/qwindowsvistastyle.cpp