Qt 4.8: QGraphicsTextItemPrivate Class Reference
QGraphicsTextItemPrivate Class Reference
Public Functions
void _q_ensureVisible (QRectF)
bool _q_mouseOnEdge (QGraphicsSceneMouseEvent *)
void _q_update (QRectF)
void _q_updateBoundingRect (const QSizeF &)
QPointF controlOffset () const
QGraphicsTextItemPrivate ()
void sendControlEvent (QEvent *e)
QTextControl * textControl () const
Public Variables
QRectF boundingRect
uint clickCausedFocus: 1
QTextControl * control
int pageNumber
QGraphicsTextItem * qq
bool tabChangesFocus
bool useDefaultImpl
Detailed Description
Definition at line 10403 of file qgraphicsitem.cpp.
Constructors and Destructors
QGraphicsTextItemPrivate()
QGraphicsTextItemPrivate::QGraphicsTextItemPrivate () inline
Definition at line 10406 of file qgraphicsitem.cpp.
         : control(0), pageNumber(0), useDefaultImpl(false), tabChangesFocus(false), clickCausedFocus(0)
     { }
Functions
_q_ensureVisible()
void QGraphicsTextItemPrivate::_q_ensureVisible (QRectF rect)
Warning
This function is not part of the public interface.
Definition at line 11050 of file qgraphicsitem.cpp.
 {
     if (qq->hasFocus()) {
         rect.translate(-controlOffset());
         qq->ensureVisible(rect, /*xmargin=*/0, /*ymargin=*/0);
     }
 }
_q_mouseOnEdge()
bool QGraphicsTextItemPrivate::_q_mouseOnEdge (QGraphicsSceneMouseEvent * event)
Warning
This function is not part of the public interface.
Definition at line 11091 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::mousePressEvent().
 {
     QPainterPath path;
     path.addRect(qq->boundingRect());
     QPainterPath docPath;
     const QTextFrameFormat format = control->document()->rootFrame()->frameFormat();
     docPath.addRect(
         qq->boundingRect().adjusted(
             format.leftMargin(),
             format.topMargin(),
             -format.rightMargin(),
             -format.bottomMargin()));
     return path.subtracted(docPath).contains(event->pos());
 }
_q_update()
void QGraphicsTextItemPrivate::_q_update (QRectF rect)
Warning
This function is not part of the public interface.
Definition at line 11021 of file qgraphicsitem.cpp.
 {
     if (rect.isValid()) {
         rect.translate(-controlOffset());
     } else {
         rect = boundingRect;
     }
     if (rect.intersects(boundingRect))
         qq->update(rect);
 }
_q_updateBoundingRect()
void QGraphicsTextItemPrivate::_q_updateBoundingRect (const QSizeF & size)
Warning
This function is not part of the public interface.
Definition at line 11035 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::setDocument(), and textControl().
 {
     if (!control) return; // can't happen
     const QSizeF pageSize = control->document()->pageSize();
     // paged items have a constant (page) size
     if (size == boundingRect.size() || pageSize.height() != -1)
         return;
     qq->prepareGeometryChange();
     boundingRect.setSize(size);
     qq->update();
 }
controlOffset()
QPointF QGraphicsTextItemPrivate::controlOffset () const inline
Definition at line 10413 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::inputMethodQuery(), and QGraphicsTextItem::paint().
     { return QPointF(0., pageNumber * control->document()->pageSize().height()); }
sendControlEvent()
void QGraphicsTextItemPrivate::sendControlEvent (QEvent * e) inline
Definition at line 10415 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::contextMenuEvent(), QGraphicsTextItem::dragEnterEvent(), QGraphicsTextItem::dragLeaveEvent(), QGraphicsTextItem::dragMoveEvent(), QGraphicsTextItem::dropEvent(), QGraphicsTextItem::focusInEvent(), QGraphicsTextItem::focusOutEvent(), QGraphicsTextItem::hoverEnterEvent(), QGraphicsTextItem::hoverLeaveEvent(), QGraphicsTextItem::hoverMoveEvent(), QGraphicsTextItem::inputMethodEvent(), QGraphicsTextItem::keyPressEvent(), QGraphicsTextItem::keyReleaseEvent(), QGraphicsTextItem::mouseDoubleClickEvent(), QGraphicsTextItem::mouseMoveEvent(), QGraphicsTextItem::mousePressEvent(), QGraphicsTextItem::mouseReleaseEvent(), and QGraphicsTextItem::sceneEvent().
     { if (control) control->processEvent(e, controlOffset()); }
textControl()
QTextControl * QGraphicsTextItemPrivate::textControl () const
Definition at line 11058 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::defaultTextColor(), QGraphicsTextItem::document(), QGraphicsTextItem::setDefaultTextColor(), QGraphicsTextItem::setDocument(), QGraphicsTextItem::setFont(), QGraphicsTextItem::setHtml(), QGraphicsTextItem::setOpenExternalLinks(), QGraphicsTextItem::setPlainText(), QGraphicsTextItem::setTextCursor(), QGraphicsTextItem::setTextInteractionFlags(), and QGraphicsTextItem::setTextWidth().
 {
     if (!control) {
         QGraphicsTextItem *that = const_cast<QGraphicsTextItem *>(qq);
         control = new QTextControl(that);
         control->setTextInteractionFlags(Qt::NoTextInteraction);
         QObject::connect(control, SIGNAL(updateRequest(QRectF)),
                          qq, SLOT(_q_update(QRectF)));
         QObject::connect(control, SIGNAL(documentSizeChanged(QSizeF)),
                          qq, SLOT(_q_updateBoundingRect(QSizeF)));
         QObject::connect(control, SIGNAL(visibilityRequest(QRectF)),
                          qq, SLOT(_q_ensureVisible(QRectF)));
         QObject::connect(control, SIGNAL(linkActivated(QString)),
                          qq, SIGNAL(linkActivated(QString)));
         QObject::connect(control, SIGNAL(linkHovered(QString)),
                          qq, SIGNAL(linkHovered(QString)));
         const QSizeF pgSize = control->document()->pageSize();
         if (pgSize.height() != -1) {
             qq->prepareGeometryChange();
             that->dd->boundingRect.setSize(pgSize);
             qq->update();
         } else {
             that->dd->_q_updateBoundingRect(control->size());
         }
     }
     return control;
 }
Properties
boundingRect
QRectF QGraphicsTextItemPrivate::boundingRect
Definition at line 10423 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::boundingRect(), QGraphicsTextItem::contains(), QGraphicsTextItem::paint(), QGraphicsTextItem::shape(), and textControl().
clickCausedFocus
uint QGraphicsTextItemPrivate::clickCausedFocus
Definition at line 10428 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::focusInEvent(), and QGraphicsTextItem::mouseReleaseEvent().
control
QTextControl* QGraphicsTextItemPrivate::control mutable
Definition at line 10410 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::adjustSize(), QGraphicsTextItem::font(), QGraphicsTextItem::inputMethodQuery(), QGraphicsTextItem::mousePressEvent(), QGraphicsTextItem::mouseReleaseEvent(), QGraphicsTextItem::openExternalLinks(), QGraphicsTextItem::paint(), QGraphicsTextItem::setDocument(), QGraphicsTextItem::shape(), QGraphicsTextItem::textCursor(), QGraphicsTextItem::textInteractionFlags(), QGraphicsTextItem::textWidth(), QGraphicsTextItem::toHtml(), and QGraphicsTextItem::toPlainText().
pageNumber
int QGraphicsTextItemPrivate::pageNumber
Definition at line 10424 of file qgraphicsitem.cpp.
qq
QGraphicsTextItem* QGraphicsTextItemPrivate::qq
Definition at line 10430 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::QGraphicsTextItem().
tabChangesFocus
bool QGraphicsTextItemPrivate::tabChangesFocus
Definition at line 10426 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::sceneEvent(), QGraphicsTextItem::setTabChangesFocus(), and QGraphicsTextItem::tabChangesFocus().
useDefaultImpl
bool QGraphicsTextItemPrivate::useDefaultImpl
Definition at line 10425 of file qgraphicsitem.cpp.
Referenced by QGraphicsTextItem::mouseDoubleClickEvent(), QGraphicsTextItem::mouseMoveEvent(), QGraphicsTextItem::mousePressEvent(), and QGraphicsTextItem::mouseReleaseEvent().
The documentation for this class was generated from the following file:
/src/gui/graphicsview/qgraphicsitem.cpp