Qt 4.8: QDeclarativeOpenMetaObject Class Reference
QDeclarativeOpenMetaObject Class Reference
#include <qdeclarativeopenmetaobject_p.h>
Public Functions
int count () const
bool hasValue (int) const
virtual QVariant initialValue (int)
QByteArray name (int) const
QObject * object () const
QVariant & operator[] (const QByteArray &)
QVariant & operator[] (int)
QDeclarativeOpenMetaObject (QObject *, bool=true)
QDeclarativeOpenMetaObject (QObject *, QDeclarativeOpenMetaObjectType *, bool=true)
void setCached (bool)
void setValue (const QByteArray &, const QVariant &)
void setValue (int, const QVariant &)
QDeclarativeOpenMetaObjectType * type () const
QVariant value (const QByteArray &) const
QVariant value (int) const
~QDeclarativeOpenMetaObject ()
Public Functions inherited from QAbstractDynamicMetaObject
virtual ~QAbstractDynamicMetaObject ()
Public Functions inherited from QMetaObject
QObject * cast (QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
const QObject * cast (const QObject *obj) const
Returns obj if object obj inherits from this meta-object; otherwise returns 0.
QMetaClassInfo classInfo (int index) const
Returns the meta-data for the item of class information with the given index.
int classInfoCount () const
Returns the number of items of class information in this class.
int classInfoOffset () const
Returns the class information offset for this class; i.e.
const char * className () const
Returns the class name.
QMetaMethod constructor (int index) const
Returns the meta-data for the constructor with the given index.
int constructorCount () const
Returns the number of constructors in this class.
QMetaEnum enumerator (int index) const
Returns the meta-data for the enumerator with the given index.
int enumeratorCount () const
Returns the number of enumerators in this class.
int enumeratorOffset () const
Returns the enumerator offset for this class; i.e.
int indexOfClassInfo (const char *name) const
Finds class information item name and returns its index; otherwise returns -1.
int indexOfConstructor (const char *constructor) const
Finds constructor and returns its index; otherwise returns -1.
int indexOfEnumerator (const char *name) const
Finds enumerator name and returns its index; otherwise returns -1.
int indexOfMethod (const char *method) const
Finds method and returns its index; otherwise returns -1.
int indexOfProperty (const char *name) const
Finds property name and returns its index; otherwise returns -1.
int indexOfSignal (const char *signal) const
Finds signal and returns its index; otherwise returns -1.
int indexOfSlot (const char *slot) const
Finds slot and returns its index; otherwise returns -1.
QMetaMethod method (int index) const
Returns the meta-data for the method with the given index.
int methodCount () const
Returns the number of methods known to the meta-object system in this class, including the number of properties provided by each base class.
int methodOffset () const
Returns the method offset for this class; i.e.
QObject * newInstance (QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument()) const
Constructs a new instance of this class.
QMetaProperty property (int index) const
Returns the meta-data for the property with the given index.
int propertyCount () const
Returns the number of properties in this class, including the number of properties provided by each base class.
int propertyOffset () const
Returns the property offset for this class; i.e.
int static_metacall (Call, int, void **) const
const QMetaObject * superClass () const
Returns the meta-object of the superclass, or 0 if there is no such object.
QString tr (const char *s, const char *c) const
QString tr (const char *s, const char *c, int n) const
QString trUtf8 (const char *s, const char *c) const
QString trUtf8 (const char *s, const char *c, int n) const
QMetaProperty userProperty () const
Returns the property that has the USER flag set to true.
Protected Functions
virtual int createProperty (const char *, const char *)
virtual int metaCall (QMetaObject::Call _c, int _id, void **_a)
QAbstractDynamicMetaObject * parent () const
virtual void propertyCreated (int, QMetaPropertyBuilder &)
virtual void propertyRead (int)
virtual void propertyWrite (int)
virtual void propertyWritten (int)
Properties
QDeclarativeOpenMetaObjectPrivate * d
Friends
class QDeclarativeOpenMetaObjectType
Additional Inherited Members
Public Types inherited from QMetaObject
enum Call {
InvokeMetaMethod, ReadProperty, WriteProperty, ResetProperty,
QueryPropertyDesignable, QueryPropertyScriptable, QueryPropertyStored, QueryPropertyEditable,
QueryPropertyUser, CreateInstance
}
Static Public Functions inherited from QMetaObject
static void activate (QObject *sender, int signal_index, void **argv)
static void activate (QObject *sender, int from_signal_index, int to_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int local_signal_index, void **argv)
static void activate (QObject *sender, const QMetaObject *, int from_local_signal_index, int to_local_signal_index, void **argv)
static void addGuard (QObject **ptr)
static void changeGuard (QObject **ptr, QObject *o)
static bool checkConnectArgs (const char *signal, const char *method)
Returns true if the signal and method arguments are compatible; otherwise returns false.
static bool connect (const QObject *sender, int signal_index, const QObject *receiver, int method_index, int type=0, int *types=0)
static void connectSlotsByName (QObject *o)
Searches recursively for all child objects of the given object, and connects matching signals from them to slots of object that follow the following form:
static bool disconnect (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool disconnectOne (const QObject *sender, int signal_index, const QObject *receiver, int method_index)
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
Invokes the member (a signal or a slot name) on the object obj.
static bool invokeMethod (QObject *obj, const char *member, QGenericReturnArgument ret, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, Qt::ConnectionType type, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static bool invokeMethod (QObject *obj, const char *member, QGenericArgument val0=QGenericArgument(0), QGenericArgument val1=QGenericArgument(), QGenericArgument val2=QGenericArgument(), QGenericArgument val3=QGenericArgument(), QGenericArgument val4=QGenericArgument(), QGenericArgument val5=QGenericArgument(), QGenericArgument val6=QGenericArgument(), QGenericArgument val7=QGenericArgument(), QGenericArgument val8=QGenericArgument(), QGenericArgument val9=QGenericArgument())
static int metacall (QObject *, Call, int, void **)
static QByteArray normalizedSignature (const char *method)
Normalizes the signature of the given method.
static QByteArray normalizedType (const char *type)
Normalizes a type.
static void removeGuard (QObject **ptr)
Public Variables inherited from QMetaObject
struct {
const uint * data
const void * extradata
const char * stringdata
const QMetaObject * superdata
} d
Detailed Description
Definition at line 82 of file qdeclarativeopenmetaobject_p.h.
Constructors and Destructors
QDeclarativeOpenMetaObject() [1/2]
QDeclarativeOpenMetaObject::QDeclarativeOpenMetaObject (QObject * obj, bool automatic = true)
Definition at line 178 of file qdeclarativeopenmetaobject.cpp.
 : d(new QDeclarativeOpenMetaObjectPrivate(this))
 {
     d->autoCreate = automatic;
     d->object = obj;
     d->type = new QDeclarativeOpenMetaObjectType(obj->metaObject(), 0);
     d->type->d->referers.insert(this);
     QObjectPrivate *op = QObjectPrivate::get(obj);
     d->parent = static_cast<QAbstractDynamicMetaObject *>(op->metaObject);
     *static_cast<QMetaObject *>(this) = *d->type->d->mem;
     op->metaObject = this;
 }
QDeclarativeOpenMetaObject() [2/2]
QDeclarativeOpenMetaObject::QDeclarativeOpenMetaObject (QObject * obj, QDeclarativeOpenMetaObjectType * type, bool automatic = true)
Definition at line 193 of file qdeclarativeopenmetaobject.cpp.
 : d(new QDeclarativeOpenMetaObjectPrivate(this))
 {
     d->autoCreate = automatic;
     d->object = obj;
     d->type = type;
     d->type->addref();
     d->type->d->referers.insert(this);
     QObjectPrivate *op = QObjectPrivate::get(obj);
     d->parent = static_cast<QAbstractDynamicMetaObject *>(op->metaObject);
     *static_cast<QMetaObject *>(this) = *d->type->d->mem;
     op->metaObject = this;
 }
~QDeclarativeOpenMetaObject()
QDeclarativeOpenMetaObject::~QDeclarativeOpenMetaObject ()
Definition at line 209 of file qdeclarativeopenmetaobject.cpp.
 {
     if (d->parent)
         delete d->parent;
     d->type->d->referers.remove(this);
     d->type->release();
     delete d;
 }
Functions
count()
int QDeclarativeOpenMetaObject::count () const
Definition at line 363 of file qdeclarativeopenmetaobject.cpp.
 {
     return d->type->d->names.count();
 }
createProperty()
int QDeclarativeOpenMetaObject::createProperty (const char * name, const char *) protected virtual
Reimplemented from QAbstractDynamicMetaObject.
Reimplemented in QDeclarativeVisualDataModelDataMetaObject.
Definition at line 334 of file qdeclarativeopenmetaobject.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), and setValue().
 {
     if (d->autoCreate)
         return d->type->createProperty(name);
     else
         return -1;
 }
hasValue()
bool QDeclarativeOpenMetaObject::hasValue (int id) const
Definition at line 308 of file qdeclarativeopenmetaobject.cpp.
 {
     return d->hasData(id);
 }
initialValue()
QVariant QDeclarativeOpenMetaObject::initialValue (int) virtual
Reimplemented in QDeclarativeVisualDataModelPartsMetaObject, and QDeclarativeVisualDataModelDataMetaObject.
Definition at line 358 of file qdeclarativeopenmetaobject.cpp.
 {
     return QVariant();
 }
metaCall()
int QDeclarativeOpenMetaObject::metaCall (QMetaObject::Call _c, int _id, void ** _a) protected virtual
Reimplemented from QAbstractDynamicMetaObject.
Definition at line 223 of file qdeclarativeopenmetaobject.cpp.
 {
     if (( c == QMetaObject::ReadProperty || c == QMetaObject::WriteProperty)
             && id >= d->type->d->propertyOffset) {
         int propId = id - d->type->d->propertyOffset;
         if (c == QMetaObject::ReadProperty) {
             propertyRead(propId);
             *reinterpret_cast<QVariant *>(a[0]) = d->getData(propId);
         } else if (c == QMetaObject::WriteProperty) {
             if (propId <= d->data.count() || d->data[propId].first != *reinterpret_cast<QVariant *>(a[0]))  {
                 propertyWrite(propId);
                 d->writeData(propId, *reinterpret_cast<QVariant *>(a[0]));
                 propertyWritten(propId);
                 activate(d->object, d->type->d->signalOffset + propId, 0);
             }
         }
         return -1;
     } else {
         if (d->parent)
             return d->parent->metaCall(c, id, a);
         else
             return d->object->qt_metacall(c, id, a);
     }
 }
name()
QByteArray QDeclarativeOpenMetaObject::name (int idx) const
Definition at line 368 of file qdeclarativeopenmetaobject.cpp.
Referenced by QDeclarativePropertyMapMetaObject::propertyWritten(), and ModelNodeMetaObject::propertyWritten().
 {
     Q_ASSERT(idx >= 0 && idx < d->type->d->names.count());
     return d->type->d->mob.property(idx).name();
 }
object()
QObject * QDeclarativeOpenMetaObject::object () const
Definition at line 375 of file qdeclarativeopenmetaobject.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), and QDeclarativeVisualDataModelDataMetaObject::initialValue().
 {
     return d->object;
 }
operator[]() [1/2]
QVariant & QDeclarativeOpenMetaObject::operator[] (const QByteArray & name)
Definition at line 273 of file qdeclarativeopenmetaobject.cpp.
Referenced by ModelNodeMetaObject::propertyWritten().
 {
     QHash<QByteArray, int>::ConstIterator iter = d->type->d->names.find(name);
     Q_ASSERT(iter != d->type->d->names.end());
     return d->getData(*iter);
 }
operator[]() [2/2]
QVariant & QDeclarativeOpenMetaObject::operator[] (int id)
Definition at line 281 of file qdeclarativeopenmetaobject.cpp.
 {
     return d->getData(id);
 }
parent()
QAbstractDynamicMetaObject * QDeclarativeOpenMetaObject::parent () const protected
Definition at line 248 of file qdeclarativeopenmetaobject.cpp.
 {
     return d->parent;
 }
propertyCreated()
void QDeclarativeOpenMetaObject::propertyCreated (int , QMetaPropertyBuilder &) protected virtual
Reimplemented in QDeclarativeVisualDataModelPartsMetaObject, and QDeclarativePropertyMapMetaObject.
Definition at line 354 of file qdeclarativeopenmetaobject.cpp.
 {
 }
propertyRead()
void QDeclarativeOpenMetaObject::propertyRead (int) protected virtual
Definition at line 342 of file qdeclarativeopenmetaobject.cpp.
Referenced by metaCall().
 {
 }
propertyWrite()
void QDeclarativeOpenMetaObject::propertyWrite (int) protected virtual
Definition at line 346 of file qdeclarativeopenmetaobject.cpp.
Referenced by metaCall().
 {
 }
propertyWritten()
void QDeclarativeOpenMetaObject::propertyWritten (int) protected virtual
Reimplemented in ModelNodeMetaObject, and QDeclarativePropertyMapMetaObject.
Definition at line 350 of file qdeclarativeopenmetaobject.cpp.
Referenced by metaCall().
 {
 }
setCached()
void QDeclarativeOpenMetaObject::setCached (bool c)
Definition at line 313 of file qdeclarativeopenmetaobject.cpp.
Referenced by QDeclarativeVisualDataModelData::ensureProperties(), and QDeclarativePathViewAttached::QDeclarativePathViewAttached().
 {
     if (c == d->cacheProperties || !d->type->d->engine)
         return;
     d->cacheProperties = c;
     QDeclarativeData *qmldata = QDeclarativeData::get(d->object, true);
     if (d->cacheProperties) {
         if (!d->type->d->cache)
             d->type->d->cache = new QDeclarativePropertyCache(d->type->d->engine, this);
         qmldata->propertyCache = d->type->d->cache;
         d->type->d->cache->addref();
     } else {
         if (d->type->d->cache)
             d->type->d->cache->release();
         qmldata->propertyCache = 0;
     }
 }
setValue() [1/2]
void QDeclarativeOpenMetaObject::setValue (const QByteArray & name, const QVariant & val)
Definition at line 286 of file qdeclarativeopenmetaobject.cpp.
Referenced by ModelObject::setValue(), and QDeclarativePathViewAttached::setValue().
 {
     QHash<QByteArray, int>::ConstIterator iter = d->type->d->names.find(name);
     int id = -1;
     if (iter == d->type->d->names.end()) {
         id = createProperty(name.constData(), "") - d->type->d->propertyOffset;
     } else {
         id = *iter;
     }
     if (id >= 0) {
         QVariant &dataVal = d->getData(id);
         if (dataVal == val)
             return;
         dataVal = val;
         activate(d->object, id + d->type->d->signalOffset, 0);
     }
 }
setValue() [2/2]
void QDeclarativeOpenMetaObject::setValue (int id, const QVariant & value)
Definition at line 258 of file qdeclarativeopenmetaobject.cpp.
 {
     d->writeData(id, value);
     activate(d->object, id + d->type->d->signalOffset, 0);
 }
type()
QDeclarativeOpenMetaObjectType * QDeclarativeOpenMetaObject::type () const
Definition at line 218 of file qdeclarativeopenmetaobject.cpp.
Referenced by name(), and QDeclarativeOpenMetaObject().
 {
     return d->type;
 }
value() [1/2]
QVariant QDeclarativeOpenMetaObject::value (const QByteArray & name) const
Definition at line 264 of file qdeclarativeopenmetaobject.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::initialValue(), ModelNodeMetaObject::propertyWritten(), and QDeclarativePathViewAttached::value().
 {
     QHash<QByteArray, int>::ConstIterator iter = d->type->d->names.find(name);
     if (iter == d->type->d->names.end())
         return QVariant();
     return d->getData(*iter);
 }
value() [2/2]
QVariant QDeclarativeOpenMetaObject::value (int id) const
Definition at line 253 of file qdeclarativeopenmetaobject.cpp.
 {
     return d->getData(id);
 }
Friends and Related Functions
QDeclarativeOpenMetaObjectType
friend class QDeclarativeOpenMetaObjectType friend
Definition at line 122 of file qdeclarativeopenmetaobject_p.h.
Referenced by QDeclarativeOpenMetaObject().
Properties
d
QDeclarativeOpenMetaObjectPrivate* QDeclarativeOpenMetaObject::d private
Definition at line 121 of file qdeclarativeopenmetaobject_p.h.
Referenced by count(), createProperty(), hasValue(), metaCall(), name(), object(), operator[](), parent(), QDeclarativeOpenMetaObject(), setCached(), setValue(), type(), value(), and ~QDeclarativeOpenMetaObject().
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeopenmetaobject_p.h
/src/declarative/util/qdeclarativeopenmetaobject.cpp