Qt 4.8: QGraphicsScale Class Reference
QGraphicsScale Class Reference
The QGraphicsScale class provides a scale transformation.
#include <qgraphicstransform.h>
Signals
void originChanged ()
QGraphicsScale emits this signal when its origin changes.
void scaleChanged ()
This signal is emitted whenever the xScale, yScale, or zScale of the object changes.
void xScaleChanged ()
This signal is emitted whenever the xScale property changes.
void yScaleChanged ()
This signal is emitted whenever the yScale property changes.
void zScaleChanged ()
This signal is emitted whenever the zScale property changes.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void applyTo (QMatrix4x4 *matrix) const
Reimplemented Function
QVector3D origin () const
QGraphicsScale (QObject *parent=0)
Constructs an empty QGraphicsScale object with the given parent.
void setOrigin (const QVector3D &point)
void setXScale (qreal)
void setYScale (qreal)
void setZScale (qreal)
qreal xScale () const
qreal yScale () const
qreal zScale () const
~QGraphicsScale ()
Destroys the graphics scale.
Public Functions inherited from QGraphicsTransform
QGraphicsTransform (QObject *parent=0)
Constructs a new QGraphicsTransform with the given parent.
~QGraphicsTransform ()
Destroys the graphics transform.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QVector3D origin
the origin of the scale in 3D space.
qreal xScale
the horizontal scale factor.
qreal yScale
the vertical scale factor.
qreal zScale
the depth scale factor.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QGraphicsTransform
void update ()
Notifies that this transform operation has changed its parameters in such a way that applyTo() will return a different result than before.
Protected Functions inherited from QGraphicsTransform
QGraphicsTransform (QGraphicsTransformPrivate &p, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsScale class provides a scale transformation.
Since
4.6
QGraphicsScene provides certain parameters to help control how the scale should be applied.
The origin is the point that the item is scaled from (i.e., it stays fixed relative to the parent as the rest of the item grows). By default the origin is QPointF(0, 0).
The parameters xScale, yScale, and zScale describe the scale factors to apply in horizontal, vertical, and depth directions. They can take on any value, including 0 (to collapse the item to a point) or negative value. A negative xScale value will mirror the item horizontally. A negative yScale value will flip the item vertically. A negative zScale will flip the item end for end.
See also
QGraphicsTransform, QGraphicsItem::setScale(), QTransform::scale()
Definition at line 83 of file qgraphicstransform.h.
Constructors and Destructors
QGraphicsScale()
QGraphicsScale::QGraphicsScale (QObject * parent = 0)
Constructs an empty QGraphicsScale object with the given parent.
Definition at line 218 of file qgraphicstransform.cpp.
     : QGraphicsTransform(*new QGraphicsScalePrivate, parent)
 {
 }
~QGraphicsScale()
QGraphicsScale::~QGraphicsScale ()
Destroys the graphics scale.
Definition at line 226 of file qgraphicstransform.cpp.
 {
 }
Functions
applyTo()
void QGraphicsScale::applyTo (QMatrix4x4 * matrix) const virtual
Reimplemented Function
Implements QGraphicsTransform.
Definition at line 350 of file qgraphicstransform.cpp.
 {
     Q_D(const QGraphicsScale);
     matrix->translate(d->origin);
     matrix->scale(d->xScale, d->yScale, d->zScale);
     matrix->translate(-d->origin);
 }
origin()
QVector3D QGraphicsScale::origin () const
Referenced by ~QGraphicsScale().
originChanged
QGraphicsScale::originChanged () signal
QGraphicsScale emits this signal when its origin changes.
See also
QGraphicsScale::origin
Referenced by setOrigin().
scaleChanged
QGraphicsScale::scaleChanged () signal
This signal is emitted whenever the xScale, yScale, or zScale of the object changes.
See also
QGraphicsScale::xScale, QGraphicsScale::yScale
QGraphicsScale::zScale
Referenced by setXScale(), setYScale(), and setZScale().
setOrigin()
void QGraphicsScale::setOrigin (const QVector3D & point)
Definition at line 247 of file qgraphicstransform.cpp.
 {
     Q_D(QGraphicsScale);
     if (d->origin == point)
         return;
     d->origin = point;
     update();
     emit originChanged();
 }
setXScale()
void QGraphicsScale::setXScale (qreal scale)
Definition at line 276 of file qgraphicstransform.cpp.
 {
     Q_D(QGraphicsScale);
     if (d->xScale == scale)
         return;
     d->xScale = scale;
     update();
     emit xScaleChanged();
     emit scaleChanged();
 }
setYScale()
void QGraphicsScale::setYScale (qreal scale)
Definition at line 306 of file qgraphicstransform.cpp.
 {
     Q_D(QGraphicsScale);
     if (d->yScale == scale)
         return;
     d->yScale = scale;
     update();
     emit yScaleChanged();
     emit scaleChanged();
 }
setZScale()
void QGraphicsScale::setZScale (qreal scale)
Definition at line 336 of file qgraphicstransform.cpp.
 {
     Q_D(QGraphicsScale);
     if (d->zScale == scale)
         return;
     d->zScale = scale;
     update();
     emit zScaleChanged();
     emit scaleChanged();
 }
xScale()
qreal QGraphicsScale::xScale () const
Referenced by setOrigin().
xScaleChanged
QGraphicsScale::xScaleChanged () signal
This signal is emitted whenever the xScale property changes.
Since
4.7
Referenced by setXScale().
yScale()
qreal QGraphicsScale::yScale () const
Referenced by setXScale().
yScaleChanged
QGraphicsScale::yScaleChanged () signal
This signal is emitted whenever the yScale property changes.
Since
4.7
Referenced by setYScale().
zScale()
qreal QGraphicsScale::zScale () const
Referenced by setYScale().
zScaleChanged
QGraphicsScale::zScaleChanged () signal
This signal is emitted whenever the zScale property changes.
Since
4.7
Referenced by setZScale().
Properties
origin
QVector3D QGraphicsScale::origin private
the origin of the scale in 3D space.
All scaling will be done relative to this point (i.e., this point will stay fixed, relative to the parent, when the item is scaled).
See also
xScale, yScale, zScale
Definition at line 87 of file qgraphicstransform.h.
xScale
qreal QGraphicsScale::xScale private
the horizontal scale factor.
The scale factor can be any real number; the default value is 1.0. If you set the factor to 0.0, the item will be collapsed to a single point. If you provide a negative value, the item will be mirrored horizontally around its origin.
See also
yScale, zScale, origin
Definition at line 88 of file qgraphicstransform.h.
yScale
qreal QGraphicsScale::yScale private
the vertical scale factor.
The scale factor can be any real number; the default value is 1.0. If you set the factor to 0.0, the item will be collapsed to a single point. If you provide a negative value, the item will be flipped vertically around its origin.
See also
xScale, zScale, origin
Definition at line 89 of file qgraphicstransform.h.
zScale
qreal QGraphicsScale::zScale private
the depth scale factor.
The scale factor can be any real number; the default value is 1.0. If you set the factor to 0.0, the item will be collapsed to a single point. If you provide a negative value, the item will be flipped end for end around its origin.
See also
xScale, yScale, origin
Definition at line 90 of file qgraphicstransform.h.
The documentation for this class was generated from the following files:
/src/gui/graphicsview/qgraphicstransform.h
/src/gui/graphicsview/qgraphicstransform.cpp