Qt 4.8: QDeclarativeFolderListModel Class Reference
QDeclarativeFolderListModel Class Reference
[class begin]
#include <qdeclarativefolderlistmodel.h>
Public Types
enum Roles { FileNameRole = Qt::UserRole+1, FilePathRole = Qt::UserRole+2 }
enum SortField {
Unsorted, Name, Time, Size,
Type
}
Signals
void folderChanged ()
[parserstatus]
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void classBegin ()
[isfolder]
virtual void componentComplete ()
Invoked after the root component that caused this instantiation has completed construction.
int count () const
[abslistmodel]
QVariant data (const QModelIndex &index, int role) const
Returns the data stored under the given role for the item referred to by the index.
QUrl folder () const
[count]
Q_INVOKABLE bool isFolder (int index) const
[prop funcs]
QStringList nameFilters () const
QUrl parentFolder () const
QDeclarativeFolderListModel (QObject *parent=0)
[class props]
int rowCount (const QModelIndex &parent) const
Returns the number of rows under the given parent.
void setFolder (const QUrl &folder)
void setNameFilters (const QStringList &filters)
void setShowDirs (bool)
void setShowDotAndDotDot (bool)
void setShowOnlyReadable (bool)
void setSortField (SortField field)
void setSortReversed (bool rev)
bool showDirs () const
bool showDotAndDotDot () const
bool showOnlyReadable () const
SortField sortField () const
bool sortReversed () const
~QDeclarativeFolderListModel ()
Public Functions inherited from QAbstractListModel
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QModelIndex index (int row, int column=0, const QModelIndex &parent=QModelIndex()) const
Returns the index of the data in row and column with parent.
QAbstractListModel (QObject *parent=0)
Constructs an abstract list model with the given parent.
~QAbstractListModel ()
Destroys the abstract list model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
virtual Qt::ItemFlags flags (const QModelIndex &index) const
Returns the item flags for the given index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
virtual QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Returns the data for the given role and section in the header with the specified orientation.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
virtual bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count new columns into the model before the given column.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, inserts count rows into the model before the given row.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
virtual bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count rows starting with the given row under parent parent from the model.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the role data for the item at index to value.
virtual bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the data for the given role and section in the header with the specified orientation to the value supplied.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual void sort (int column, Qt::SortOrder order=Qt::AscendingOrder)
Sorts the model by column in the given order.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QDeclarativeParserStatus
QDeclarativeParserStatus ()
virtual ~QDeclarativeParserStatus ()
Private Slots
void handleDataChanged (const QModelIndex &start, const QModelIndex &end)
void inserted (const QModelIndex &index, int start, int end)
void refresh ()
[notifier]
void removed (const QModelIndex &index, int start, int end)
Properties
int count
QDeclarativeFolderListModelPrivate * d
QUrl folder
[class begin]
QStringList nameFilters
QUrl parentFolder
bool showDirs
bool showDotAndDotDot
bool showOnlyReadable
SortField sortField
bool sortReversed
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Functions inherited from QAbstractListModel
QAbstractListModel (QAbstractItemModelPrivate &dd, QObject *parent)
Constructs an abstract list model with dd and the given parent.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
[class begin]
Definition at line 64 of file qdeclarativefolderlistmodel.h.
Enumerations
Roles
enum QDeclarativeFolderListModel::Roles
Enumerator
FileNameRole
FilePathRole
Definition at line 87 of file qdeclarativefolderlistmodel.h.
 { FileNameRole = Qt::UserRole+1, FilePathRole = Qt::UserRole+2 };
SortField
enum QDeclarativeFolderListModel::SortField
Enumerator
Unsorted
Name
Time
Size
Type
Definition at line 106 of file qdeclarativefolderlistmodel.h.
 { Unsorted, Name, Time, Size, Type };
Constructors and Destructors
QDeclarativeFolderListModel()
QDeclarativeFolderListModel::QDeclarativeFolderListModel (QObject * parent = 0)
[class props]
[abslistmodel]
Definition at line 158 of file qdeclarativefolderlistmodel.cpp.
     : QAbstractListModel(parent)
 {
     QHash<int, QByteArray> roles;
     roles[FileNameRole] = "fileName";
     roles[FilePathRole] = "filePath";
     setRoleNames(roles);
     d = new QDeclarativeFolderListModelPrivate;
     d->model.setFilter(QDir::AllDirs | QDir::Files | QDir::Drives | QDir::NoDotAndDotDot);
     connect(&d->model, SIGNAL(rowsInserted(const QModelIndex&,int,int))
             , this, SLOT(inserted(const QModelIndex&,int,int)));
     connect(&d->model, SIGNAL(rowsRemoved(const QModelIndex&,int,int))
             , this, SLOT(removed(const QModelIndex&,int,int)));
     connect(&d->model, SIGNAL(dataChanged(const QModelIndex&,const QModelIndex&))
             , this, SLOT(handleDataChanged(const QModelIndex&,const QModelIndex&)));
     connect(&d->model, SIGNAL(modelReset()), this, SLOT(refresh()));
     connect(&d->model, SIGNAL(layoutChanged()), this, SLOT(refresh()));
 }
~QDeclarativeFolderListModel()
QDeclarativeFolderListModel::~QDeclarativeFolderListModel ()
Definition at line 178 of file qdeclarativefolderlistmodel.cpp.
 {
     delete d;
 }
Functions
classBegin()
void QDeclarativeFolderListModel::classBegin () virtual
[isfolder]
[parserstatus]
Implements QDeclarativeParserStatus.
Definition at line 299 of file qdeclarativefolderlistmodel.cpp.
 {
 }
componentComplete()
void QDeclarativeFolderListModel::componentComplete () virtual
Invoked after the root component that caused this instantiation has completed construction.
At this point all static values and binding values have been assigned to the class.
Implements QDeclarativeParserStatus.
Definition at line 303 of file qdeclarativefolderlistmodel.cpp.
 {
     if (!d->folder.isValid() || d->folder.toLocalFile().isEmpty() || !QDir().exists(d->folder.toLocalFile()))
         setFolder(QUrl(QLatin1String("file://")+QDir::currentPath()));
     if (!d->folderIndex.isValid())
         QMetaObject::invokeMethod(this, "refresh", Qt::QueuedConnection);
 }
count()
int QDeclarativeFolderListModel::count () const inline
[abslistmodel]
[count]
Definition at line 94 of file qdeclarativefolderlistmodel.h.
 { return rowCount(QModelIndex()); }
data()
QVariant QDeclarativeFolderListModel::data (const QModelIndex & index, int role) const virtual
Returns the data stored under the given role for the item referred to by the index.
Note
If you do not have a value to return, return an invalid QVariant instead of returning 0.
See also
Qt::ItemDataRole, setData(), headerData()
Implements QAbstractItemModel.
Definition at line 183 of file qdeclarativefolderlistmodel.cpp.
 {
     QVariant rv;
     QModelIndex modelIndex = d->model.index(index.row(), 0, d->folderIndex);
     if (modelIndex.isValid()) {
         if (role == FileNameRole)
             rv = d->model.data(modelIndex, QDirModel::FileNameRole).toString();
         else if (role == FilePathRole)
             rv = QUrl::fromLocalFile(d->model.data(modelIndex, QDirModel::FilePathRole).toString());
     }
     return rv;
 }
folder()
QUrl QDeclarativeFolderListModel::folder () const
[count]
[prop funcs]
Referenced by count(), rowCount(), and setFolder().
folderChanged
void QDeclarativeFolderListModel::folderChanged () signal
[parserstatus]
[notifier]
Referenced by setFolder().
handleDataChanged
void QDeclarativeFolderListModel::handleDataChanged (const QModelIndex & start, const QModelIndex & end) private slot
Definition at line 420 of file qdeclarativefolderlistmodel.cpp.
Referenced by QDeclarativeFolderListModel().
 {
     if (start.parent() == d->folderIndex)
         emit dataChanged(index(start.row(),0), index(end.row(),0));
 }
inserted
void QDeclarativeFolderListModel::inserted (const QModelIndex & index, int start, int end) private slot
Definition at line 402 of file qdeclarativefolderlistmodel.cpp.
Referenced by QDeclarativeFolderListModel().
 {
     if (index == d->folderIndex) {
         emit beginInsertRows(QModelIndex(), start, end);
         d->count = d->model.rowCount(d->folderIndex);
         emit endInsertRows();
     }
 }
isFolder()
bool QDeclarativeFolderListModel::isFolder (int index) const
[prop funcs]
[isfolder]
Definition at line 375 of file qdeclarativefolderlistmodel.cpp.
 {
     if (index != -1) {
         QModelIndex idx = d->model.index(index, 0, d->folderIndex);
         if (idx.isValid())
             return d->model.isDir(idx);
     }
     return false;
 }
nameFilters()
QStringList QDeclarativeFolderListModel::nameFilters () const
Referenced by count(), and setFolder().
parentFolder()
QUrl QDeclarativeFolderListModel::parentFolder () const
Referenced by count(), and setFolder().
refresh
void QDeclarativeFolderListModel::refresh () private slot
[notifier]
[class end]
Definition at line 385 of file qdeclarativefolderlistmodel.cpp.
Referenced by QDeclarativeFolderListModel().
 {
     d->folderIndex = QModelIndex();
     if (d->count) {
         emit beginRemoveRows(QModelIndex(), 0, d->count-1);
         d->count = 0;
         emit endRemoveRows();
     }
     d->folderIndex = d->model.index(d->folder.toLocalFile());
     int newcount = d->model.rowCount(d->folderIndex);
     if (newcount) {
         emit beginInsertRows(QModelIndex(), 0, newcount-1);
         d->count = newcount;
         emit endInsertRows();
     }
 }
removed
void QDeclarativeFolderListModel::removed (const QModelIndex & index, int start, int end) private slot
Definition at line 411 of file qdeclarativefolderlistmodel.cpp.
Referenced by QDeclarativeFolderListModel().
 {
     if (index == d->folderIndex) {
         emit beginRemoveRows(QModelIndex(), start, end);
         d->count = d->model.rowCount(d->folderIndex);
         emit endRemoveRows();
     }
 }
rowCount()
int QDeclarativeFolderListModel::rowCount (const QModelIndex & parent) const virtual
Returns the number of rows under the given parent.
When the parent is valid it means that rowCount is returning the number of children of parent.
Note
When implementing a table based model, rowCount() should return 0 when the parent is valid.
See also
columnCount()
Implements QAbstractItemModel.
Definition at line 205 of file qdeclarativefolderlistmodel.cpp.
Referenced by count().
 {
     Q_UNUSED(parent);
     return d->count;
 }
setFolder()
void QDeclarativeFolderListModel::setFolder (const QUrl & folder)
Definition at line 230 of file qdeclarativefolderlistmodel.cpp.
Referenced by componentComplete(), and count().
 {
     if (folder == d->folder)
         return;
     QModelIndex index = d->model.index(folder.toLocalFile());
     if ((index.isValid() && d->model.isDir(index)) || folder.toLocalFile().isEmpty()) {
         d->folder = folder;
         QMetaObject::invokeMethod(this, "refresh", Qt::QueuedConnection);
         emit folderChanged();
     }
 }
setNameFilters()
void QDeclarativeFolderListModel::setNameFilters (const QStringList & filters)
Definition at line 293 of file qdeclarativefolderlistmodel.cpp.
Referenced by count().
 {
     d->nameFilters = filters;
     d->model.setNameFilters(d->nameFilters);
 }
setShowDirs()
void QDeclarativeFolderListModel::setShowDirs (bool on)
Definition at line 446 of file qdeclarativefolderlistmodel.cpp.
 {
     if (!(d->model.filter() & QDir::AllDirs) == !on)
         return;
     if (on)
         d->model.setFilter(d->model.filter() | QDir::AllDirs | QDir::Drives);
     else
         d->model.setFilter(d->model.filter() & ~(QDir::AllDirs | QDir::Drives));
 }
setShowDotAndDotDot()
void QDeclarativeFolderListModel::setShowDotAndDotDot (bool on)
Definition at line 474 of file qdeclarativefolderlistmodel.cpp.
 {
     if (!(d->model.filter() & QDir::NoDotAndDotDot) == on)
         return;
     if (on)
         d->model.setFilter(d->model.filter() & ~QDir::NoDotAndDotDot);
     else
         d->model.setFilter(d->model.filter() | QDir::NoDotAndDotDot);
 }
setShowOnlyReadable()
void QDeclarativeFolderListModel::setShowOnlyReadable (bool on)
Definition at line 502 of file qdeclarativefolderlistmodel.cpp.
 {
     if (!(d->model.filter() & QDir::Readable) == !on)
         return;
     if (on)
         d->model.setFilter(d->model.filter() | QDir::Readable);
     else
         d->model.setFilter(d->model.filter() & ~QDir::Readable);
 }
setSortField()
void QDeclarativeFolderListModel::setSortField (SortField field)
Definition at line 335 of file qdeclarativefolderlistmodel.cpp.
 {
     if (field != d->sortField) {
         d->sortField = field;
         d->updateSorting();
     }
 }
setSortReversed()
void QDeclarativeFolderListModel::setSortReversed (bool rev)
Definition at line 358 of file qdeclarativefolderlistmodel.cpp.
 {
     if (rev != d->sortReversed) {
         d->sortReversed = rev;
         d->updateSorting();
     }
 }
showDirs()
bool QDeclarativeFolderListModel::showDirs () const
Referenced by handleDataChanged().
showDotAndDotDot()
bool QDeclarativeFolderListModel::showDotAndDotDot () const
Referenced by setShowDirs().
showOnlyReadable()
bool QDeclarativeFolderListModel::showOnlyReadable () const
Referenced by setShowDotAndDotDot().
sortField()
SortField QDeclarativeFolderListModel::sortField () const
Referenced by componentComplete().
sortReversed()
bool QDeclarativeFolderListModel::sortReversed () const
Referenced by setSortField().
Properties
count
int QDeclarativeFolderListModel::count private
Definition at line 79 of file qdeclarativefolderlistmodel.h.
d
QDeclarativeFolderListModelPrivate* QDeclarativeFolderListModel::d private
Definition at line 145 of file qdeclarativefolderlistmodel.h.
Referenced by componentComplete(), data(), handleDataChanged(), inserted(), isFolder(), QDeclarativeFolderListModel(), refresh(), removed(), rowCount(), setFolder(), setNameFilters(), setShowDirs(), setShowDotAndDotDot(), setShowOnlyReadable(), setSortField(), setSortReversed(), and ~QDeclarativeFolderListModel().
folder
QUrl QDeclarativeFolderListModel::folder private
[class begin]
[class props]
Definition at line 71 of file qdeclarativefolderlistmodel.h.
nameFilters
QStringList QDeclarativeFolderListModel::nameFilters private
Definition at line 73 of file qdeclarativefolderlistmodel.h.
parentFolder
QUrl QDeclarativeFolderListModel::parentFolder private
Definition at line 72 of file qdeclarativefolderlistmodel.h.
showDirs
bool QDeclarativeFolderListModel::showDirs private
Definition at line 76 of file qdeclarativefolderlistmodel.h.
showDotAndDotDot
bool QDeclarativeFolderListModel::showDotAndDotDot private
Definition at line 77 of file qdeclarativefolderlistmodel.h.
showOnlyReadable
bool QDeclarativeFolderListModel::showOnlyReadable private
Definition at line 78 of file qdeclarativefolderlistmodel.h.
sortField
QDeclarativeFolderListModel::SortField QDeclarativeFolderListModel::sortField private
Definition at line 74 of file qdeclarativefolderlistmodel.h.
sortReversed
bool QDeclarativeFolderListModel::sortReversed private
Definition at line 75 of file qdeclarativefolderlistmodel.h.
The documentation for this class was generated from the following files:
/src/imports/folderlistmodel/qdeclarativefolderlistmodel.h
/src/imports/folderlistmodel/qdeclarativefolderlistmodel.cpp