Qt 4.8: QGLContextGroupResource< T > Class Template Reference
QGLContextGroupResource< T > Class Template Reference
#include <qgl_p.h>
Public Functions
T * value (const QGLContext *context)
~QGLContextGroupResource ()
Public Functions inherited from QGLContextGroupResourceBase
QGLContextGroupResourceBase ()
virtual ~QGLContextGroupResourceBase ()
void insert (const QGLContext *context, void *value)
void * value (const QGLContext *context)
void cleanup (const QGLContext *context)
void cleanup (const QGLContext *context, void *value)
virtual void contextDeleted (const QGLContext *ctx)
Protected Functions
void freeResource (void *resource)
Additional Inherited Members
Protected Variables inherited from QGLContextGroupResourceBase
QList< QGLContextGroup * > m_groups
Detailed Description
template<class T>
class QGLContextGroupResource< T >
Definition at line 761 of file qgl_p.h.
Constructors and Destructors
~QGLContextGroupResource()
template<class T> QGLContextGroupResource< T >::~QGLContextGroupResource () inline
Definition at line 764 of file qgl_p.h.
{
         for (int i = 0; i < m_groups.size(); ++i) {
             const QGLContext *context = m_groups.at(i)->context();
             T *resource = reinterpret_cast<T *>(QGLContextGroupResourceBase::value(context));
             if (resource) {
                 QGLShareContextScope scope(context);
                 delete resource;
             }
         }
     }
Functions
freeResource()
template<class T> void QGLContextGroupResource< T >::freeResource (void * resource) inline protected virtual
Implements QGLContextGroupResourceBase.
Definition at line 785 of file qgl_p.h.
{
         delete reinterpret_cast<T *>(resource);
     }
value()
template<class T> T* QGLContextGroupResource< T >::value (const QGLContext * context) inline
Definition at line 775 of file qgl_p.h.
Referenced by QGL2GradientCacheWrapper::cacheForContext(), QGLTextureGlyphCache::createTextureData(), QGLTextureGlyphCache::fillTexture(), QGLTextureGlyphCache::height(), QGLTextureGlyphCache::resizeTextureData(), QGLShaderStorage::shadersForThread(), QGLTextureGlyphCache::texture(), and QGLTextureGlyphCache::width().
{
         T *resource = reinterpret_cast<T *>(QGLContextGroupResourceBase::value(context));
         if (!resource) {
             resource = new T(context);
             insert(context, resource);
         }
         return resource;
     }
The documentation for this class was generated from the following file:
/src/opengl/qgl_p.h