Qt 4.8: QPacketProtocol Class Reference
QPacketProtocol Class Reference
The QPacketProtocol class encapsulates communicating discrete packets across fragmented IO channels, such as TCP sockets.
#include <qpacketprotocol_p.h>
Signals
void invalidPacket ()
A packet larger than the maximum allowable packet size was received.
void packetWritten ()
Emitted each time a packet is completing written to the device.
void readyRead ()
Emitted whenever a new packet is received.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void clear ()
Discard any unread packets.
QIODevice * device ()
Return the QIODevice passed to the QPacketProtocol constructor.
qint32 maximumPacketSize () const
Returns the maximum packet size allowed.
qint64 packetsAvailable () const
Returns the number of received packets yet to be read.
QPacketProtocol (QIODevice *dev, QObject *parent=0)
Construct a QPacketProtocol instance that works on dev with the specified parent.
QPacket read ()
Return the next unread packet, or an invalid QPacket instance if no packets are available.
QPacketAutoSend send ()
Returns a streamable object that is transmitted on destruction.
void send (const QPacket &)
Transmit the packet.
qint32 setMaximumPacketSize (qint32)
Sets the maximum allowable packet size to max.
bool waitForReadyRead (int msecs=3000)
This function locks until a new packet is available for reading and the QIODevice::readyRead() signal has been emitted.
virtual ~QPacketProtocol ()
Destroys the QPacketProtocol instance.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Properties
QPacketProtocolPrivate * d
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPacketProtocol class encapsulates communicating discrete packets across fragmented IO channels, such as TCP sockets.
Warning
This function is not part of the public interface.
QPacketProtocol makes it simple to send arbitrary sized data "packets" across fragmented transports such as TCP and UDP.
As transmission boundaries are not respected, sending packets over protocols like TCP frequently involves "stitching" them back together at the receiver. QPacketProtocol makes this easier by performing this task for you. Packet data sent using QPacketProtocol is prepended with a 4-byte size header allowing the receiving QPacketProtocol to buffer the packet internally until it has all been received. QPacketProtocol does not perform any sanity checking on the size or on the data, so this class should only be used in prototyping or trusted situations where DOS attacks are unlikely.
QPacketProtocol does not perform any communications itself. Instead it can operate on any QIODevice that supports the QIODevice::readyRead() signal. A logical "packet" is encapsulated by the companion QPacket class. The following example shows two ways to send data using QPacketProtocol. The transmitted data is equivalent in both.
QTcpSocket socket;
// ... connect socket ...
QPacketProtocol protocol(&socket);
// Send packet the quick way
protocol.send() << "Hello world" << 123;
// Send packet the longer way
QPacket packet;
packet << "Hello world" << 123;
protocol.send(packet);
Likewise, the following shows how to read data from QPacketProtocol, assuming that the QPacketProtocol::readyRead() signal has been emitted.
// ... QPacketProtocol::readyRead() is emitted ...
int a;
QByteArray b;
// Receive packet the quick way
protocol.read() >> a >> b;
// Receive packet the longer way
QPacket packet = protocol.read();
p >> a >> b;
See also
QPacket
Definition at line 62 of file qpacketprotocol_p.h.
Constructors and Destructors
QPacketProtocol()
QPacketProtocol::QPacketProtocol (QIODevice * dev, QObject * parent = 0) explicit
Construct a QPacketProtocol instance that works on dev with the specified parent.
Definition at line 234 of file qpacketprotocol.cpp.
 : QObject(parent), d(new QPacketProtocolPrivate(this, dev))
 {
     Q_ASSERT(dev);
 }
~QPacketProtocol()
QPacketProtocol::~QPacketProtocol () virtual
Destroys the QPacketProtocol instance.
Definition at line 243 of file qpacketprotocol.cpp.
 {
 }
Functions
clear()
void QPacketProtocol::clear ()
Discard any unread packets.
Definition at line 322 of file qpacketprotocol.cpp.
 {
     d->packets.clear();
 }
device()
QIODevice * QPacketProtocol::device ()
Return the QIODevice passed to the QPacketProtocol constructor.
Definition at line 386 of file qpacketprotocol.cpp.
 {
     return d->dev;
 }
invalidPacket
void QPacketProtocol::invalidPacket () signal
A packet larger than the maximum allowable packet size was received.
The packet will be discarded and, as it indicates corruption in the protocol, no further packets will be received.
maximumPacketSize()
qint32 QPacketProtocol::maximumPacketSize () const
Returns the maximum packet size allowed.
By default this is 2,147,483,647 bytes.
If a packet claiming to be larger than the maximum packet size is received, the QPacketProtocol::invalidPacket() signal is emitted.
See also
QPacketProtocol::setMaximumPacketSize()
Definition at line 256 of file qpacketprotocol.cpp.
 {
     return d->maxPacketSize;
 }
packetsAvailable()
qint64 QPacketProtocol::packetsAvailable () const
Returns the number of received packets yet to be read.
Definition at line 314 of file qpacketprotocol.cpp.
Referenced by QDeclarativeDebugConnectionPrivate::readyRead().
 {
     return d->packets.count();
 }
packetWritten
void QPacketProtocol::packetWritten () signal
Emitted each time a packet is completing written to the device.
This signal may be used for communications flow control.
read()
QPacket QPacketProtocol::read ()
Return the next unread packet, or an invalid QPacket instance if no packets are available.
This method does NOT block.
Definition at line 331 of file qpacketprotocol.cpp.
Referenced by QDeclarativeDebugConnectionPrivate::readyRead().
 {
     if(0 == d->packets.count())
         return QPacket();
     QPacket rv(d->packets.at(0));
     d->packets.removeFirst();
     return rv;
 }
readyRead
void QPacketProtocol::readyRead () signal
Emitted whenever a new packet is received.
Applications may use QPacketProtocol::read() to retrieve this packet.
send() [1/2]
QPacketAutoSend QPacketProtocol::send ()
Returns a streamable object that is transmitted on destruction.
For example
protocol.send() << "Hello world" << 123;
will send a packet containing "Hello world" and 123. To construct more complex packets, explicitly construct a QPacket instance.
Definition at line 283 of file qpacketprotocol.cpp.
Referenced by QDeclarativeDebugConnectionPrivate::advertisePlugins(), QDeclarativeDebugConnectionPrivate::connected(), and QPacketAutoSend::~QPacketAutoSend().
 {
     return QPacketAutoSend(this);
 }
send() [2/2]
void QPacketProtocol::send (const QPacket & packet)
Transmit the packet.
Definition at line 296 of file qpacketprotocol.cpp.
 {
     if(p.b.isEmpty())
         return; // We don't send empty packets
     qint64 sendSize = p.b.size() + sizeof(qint32);
     d->sendingPackets.append(sendSize);
     qint32 sendSize32 = sendSize;
     qint64 writeBytes = d->dev->write((char *)&sendSize32, sizeof(qint32));
     Q_ASSERT(writeBytes == sizeof(qint32));
     writeBytes = d->dev->write(p.b);
     Q_ASSERT(writeBytes == p.b.size());
 }
setMaximumPacketSize()
qint32 QPacketProtocol::setMaximumPacketSize (qint32 max)
Sets the maximum allowable packet size to max.
See also
QPacketProtocol::maximumPacketSize()
Definition at line 266 of file qpacketprotocol.cpp.
 {
     if(max > (signed)sizeof(qint32))
         d->maxPacketSize = max;
     return d->maxPacketSize;
 }
waitForReadyRead()
bool QPacketProtocol::waitForReadyRead (int msecs = 3000)
This function locks until a new packet is available for reading and the QIODevice::readyRead() signal has been emitted.
The function will timeout after msecs milliseconds; the default timeout is 30000 milliseconds.
The function returns true if the readyRead() signal is emitted and there is new data available for reading; otherwise it returns false (if an error occurred or the operation timed out).
Definition at line 365 of file qpacketprotocol.cpp.
 {
     if (!d->packets.isEmpty())
         return true;
     QElapsedTimer stopWatch;
     stopWatch.start();
     d->waitingForPacket = true;
     do {
         if (!d->dev->waitForReadyRead(msecs))
             return false;
         if (!d->waitingForPacket)
             return true;
         msecs = qt_timeout_value(msecs, stopWatch.elapsed());
     } while (true);
 }
Properties
d
QPacketProtocolPrivate* QPacketProtocol::d private
Definition at line 90 of file qpacketprotocol_p.h.
Referenced by clear(), device(), maximumPacketSize(), packetsAvailable(), read(), send(), setMaximumPacketSize(), and waitForReadyRead().
The documentation for this class was generated from the following files:
/src/declarative/debugger/qpacketprotocol_p.h
/src/declarative/debugger/qpacketprotocol.cpp