Qt 4.8: QAnimationGroupPrivate Class Reference
QAnimationGroupPrivate Class Reference
#include <qanimationgroup_p.h>
Public Functions
virtual void animationInsertedAt (int)
virtual void animationRemoved (int, QAbstractAnimation *)
void connectUncontrolledAnimation (QAbstractAnimation *anim)
void disconnectUncontrolledAnimation (QAbstractAnimation *anim)
QAnimationGroupPrivate ()
Public Functions inherited from QAbstractAnimationPrivate
QAbstractAnimationPrivate ()
void setState (QAbstractAnimation::State state)
virtual ~QAbstractAnimationPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QList< QAbstractAnimation * > animations
Public Variables inherited from QAbstractAnimationPrivate
int currentLoop
int currentTime
bool deleteWhenStopped
QAbstractAnimation::Direction direction
QAnimationGroup * group
bool hasRegisteredTimer
bool isGroup
bool isPause
int loopCount
QAbstractAnimation::State state
int totalCurrentTime
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QAbstractAnimationPrivate
static QAbstractAnimationPrivate * get (QAbstractAnimation *q)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Detailed Description
Definition at line 66 of file qanimationgroup_p.h.
Constructors and Destructors
QAnimationGroupPrivate()
QAnimationGroupPrivate::QAnimationGroupPrivate () inline
Definition at line 70 of file qanimationgroup_p.h.
     {
         isGroup = true;
     }
Functions
animationInsertedAt()
virtual void QAnimationGroupPrivate::animationInsertedAt (int) inline virtual
Reimplemented in QSequentialAnimationGroupPrivate.
Definition at line 75 of file qanimationgroup_p.h.
 { }
animationRemoved()
void QAnimationGroupPrivate::animationRemoved (int index, QAbstractAnimation *) virtual
Reimplemented in QSequentialAnimationGroupPrivate, and QParallelAnimationGroupPrivate.
Definition at line 291 of file qanimationgroup.cpp.
Referenced by animationInsertedAt(), QParallelAnimationGroupPrivate::animationRemoved(), and QSequentialAnimationGroupPrivate::animationRemoved().
 {
     Q_Q(QAnimationGroup);
     Q_UNUSED(index);
     if (animations.isEmpty()) {
         currentTime = 0;
         q->stop();
     }
 }
connectUncontrolledAnimation()
void QAnimationGroupPrivate::connectUncontrolledAnimation (QAbstractAnimation * anim) inline
Definition at line 84 of file qanimationgroup_p.h.
     {
         QObject::connect(anim, SIGNAL(finished()), q_func(), SLOT(_q_uncontrolledAnimationFinished()));
     }
disconnectUncontrolledAnimation()
void QAnimationGroupPrivate::disconnectUncontrolledAnimation (QAbstractAnimation * anim) inline
Definition at line 78 of file qanimationgroup_p.h.
     {
         //0 for the signal here because we might be called from the animation destructor
         QObject::disconnect(anim, 0, q_func(), SLOT(_q_uncontrolledAnimationFinished()));
     }
Properties
animations
QList<QAbstractAnimation *> QAnimationGroupPrivate::animations
Definition at line 89 of file qanimationgroup_p.h.
Referenced by QSequentialAnimationGroupPrivate::advanceForwards(), QSequentialAnimationGroupPrivate::animationActualTotalDuration(), QSequentialAnimationGroupPrivate::atEnd(), QSequentialAnimationGroupPrivate::indexForCurrentTime(), QSequentialAnimationGroupPrivate::restart(), and QSequentialAnimationGroupPrivate::rewindForwards().
The documentation for this class was generated from the following files:
/src/corelib/animation/qanimationgroup_p.h
/src/corelib/animation/qanimationgroup.cpp