Qt 4.8: QSqlDatabasePrivate Class Reference
QSqlDatabasePrivate Class Reference
Public Functions
void copy (const QSqlDatabasePrivate *other)
Copies the connection data from other.
void disable ()
void init (const QString &type)
Create the actual driver instance type.
QSqlDatabasePrivate (QSqlDatabase *d, QSqlDriver *dr=0)
QSqlDatabasePrivate (const QSqlDatabasePrivate &other)
~QSqlDatabasePrivate ()
Static Public Functions
static void addDatabase (const QSqlDatabase &db, const QString &name)
static void cleanConnections ()
static QSqlDatabase database (const QString &name, bool open)
static DriverDict & driverDict ()
static void invalidateDb (const QSqlDatabase &db, const QString &name, bool doWarn=true)
static void removeDatabase (const QString &name)
static QSqlDatabasePrivate * shared_null ()
Public Variables
QString connName
QString connOptions
QString dbname
QSqlDriver * driver
QString drvName
QString hname
int port
QSql::NumericalPrecisionPolicy precisionPolicy
QString pword
QSqlDatabase * q
QAtomicInt ref
QString uname
Detailed Description
Definition at line 132 of file qsqldatabase.cpp.
Constructors and Destructors
QSqlDatabasePrivate() [1/2]
QSqlDatabasePrivate::QSqlDatabasePrivate (QSqlDatabase * d, QSqlDriver * dr = 0) inline
Definition at line 135 of file qsqldatabase.cpp.
                                                             :
         q(d),
         driver(dr),
         port(-1)
     {
         ref = 1;
         precisionPolicy= QSql::LowPrecisionDouble;
     }
QSqlDatabasePrivate() [2/2]
QSqlDatabasePrivate::QSqlDatabasePrivate (const QSqlDatabasePrivate & other)
Definition at line 171 of file qsqldatabase.cpp.
 {
     ref = 1;
     q = other.q;
     dbname = other.dbname;
     uname = other.uname;
     pword = other.pword;
     hname = other.hname;
     drvName = other.drvName;
     port = other.port;
     connOptions = other.connOptions;
     driver = other.driver;
     precisionPolicy = other.precisionPolicy;
 }
~QSqlDatabasePrivate()
QSqlDatabasePrivate::~QSqlDatabasePrivate ()
Definition at line 186 of file qsqldatabase.cpp.
 {
     if (driver != shared_null()->driver)
         delete driver;
 }
Functions
addDatabase()
void QSqlDatabasePrivate::addDatabase (const QSqlDatabase & db, const QString & name) static
Definition at line 254 of file qsqldatabase.cpp.
Referenced by QSqlDatabase::addDatabase(), and QSqlDatabase::cloneDatabase().
 {
     QConnectionDict *dict = dbDict();
     Q_ASSERT(dict);
     QWriteLocker locker(&dict->lock);
     if (dict->contains(name)) {
         invalidateDb(dict->take(name), name);
         qWarning("QSqlDatabasePrivate::addDatabase: duplicate connection name '%s', old "
                  "connection removed.", name.toLocal8Bit().data());
     }
     dict->insert(name, db);
     db.d->connName = name;
 }
cleanConnections()
void QSqlDatabasePrivate::cleanConnections () static
Definition at line 192 of file qsqldatabase.cpp.
Referenced by cleanDriverDict().
 {
     QConnectionDict *dict = dbDict();
     Q_ASSERT(dict);
     QWriteLocker locker(&dict->lock);
     QConnectionDict::iterator it = dict->begin();
     while (it != dict->end()) {
         invalidateDb(it.value(), it.key(), false);
         ++it;
     }
     dict->clear();
 }
copy()
void QSqlDatabasePrivate::copy (const QSqlDatabasePrivate * other)
Copies the connection data from other.
Warning
This function is not part of the public interface.
Definition at line 294 of file qsqldatabase.cpp.
Referenced by QSqlDatabase::cloneDatabase().
 {
     q = other->q;
     dbname = other->dbname;
     uname = other->uname;
     pword = other->pword;
     hname = other->hname;
     drvName = other->drvName;
     port = other->port;
     connOptions = other->connOptions;
     precisionPolicy = other->precisionPolicy;
 }
database()
QSqlDatabase QSqlDatabasePrivate::database (const QString & name, bool open) static
Warning
This function is not part of the public interface.
Definition at line 271 of file qsqldatabase.cpp.
Referenced by QSqlDatabase::database().
 {
     const QConnectionDict *dict = dbDict();
     Q_ASSERT(dict);
     dict->lock.lockForRead();
     QSqlDatabase db = dict->value(name);
     dict->lock.unlock();
     if (db.isValid() && !db.isOpen() && open) {
         if (!db.open())
             qWarning() << "QSqlDatabasePrivate::database: unable to open database:" << db.lastError().text();
     }
     return db;
 }
disable()
void QSqlDatabasePrivate::disable ()
Definition at line 307 of file qsqldatabase.cpp.
Referenced by invalidateDb().
 {
     if (driver != shared_null()->driver) {
         delete driver;
         driver = shared_null()->driver;
     }
 }
driverDict()
DriverDict & QSqlDatabasePrivate::driverDict () static
Definition at line 215 of file qsqldatabase.cpp.
Referenced by cleanDriverDict(), QSqlDatabase::drivers(), init(), and QSqlDatabase::registerSqlDriver().
 {
     static DriverDict dict;
     if (!qDriverDictInit) {
         qDriverDictInit = true;
         qAddPostRoutine(cleanDriverDict);
     }
     return dict;
 }
init()
void QSqlDatabasePrivate::init (const QString & type)
Create the actual driver instance type.
Warning
This function is not part of the public interface.
Definition at line 762 of file qsqldatabase.cpp.
 {
     drvName = type;
     if (!driver) {
 #ifdef QT_SQL_PSQL
         if (type == QLatin1String("QPSQL") || type == QLatin1String("QPSQL7"))
             driver = new QPSQLDriver();
 #endif
 #ifdef QT_SQL_MYSQL
         if (type == QLatin1String("QMYSQL") || type == QLatin1String("QMYSQL3"))
             driver = new QMYSQLDriver();
 #endif
 #ifdef QT_SQL_ODBC
         if (type == QLatin1String("QODBC") || type == QLatin1String("QODBC3"))
             driver = new QODBCDriver();
 #endif
 #ifdef QT_SQL_OCI
         if (type == QLatin1String("QOCI") || type == QLatin1String("QOCI8"))
             driver = new QOCIDriver();
 #endif
 #ifdef QT_SQL_TDS
         if (type == QLatin1String("QTDS") || type == QLatin1String("QTDS7"))
             driver = new QTDSDriver();
 #endif
 #ifdef QT_SQL_DB2
         if (type == QLatin1String("QDB2"))
             driver = new QDB2Driver();
 #endif
 #ifdef QT_SQL_SQLITE
         if (type == QLatin1String("QSQLITE"))
             driver = new QSQLiteDriver();
 #endif
 #ifdef QT_SQL_SQLITE2
         if (type == QLatin1String("QSQLITE2"))
             driver = new QSQLite2Driver();
 #endif
 #ifdef QT_SQL_IBASE
         if (type == QLatin1String("QIBASE"))
             driver = new QIBaseDriver();
 #endif
     }
     if (!driver) {
         DriverDict dict = QSqlDatabasePrivate::driverDict();
         for (DriverDict::const_iterator it = dict.constBegin();
              it != dict.constEnd() && !driver; ++it) {
             if (type == it.key()) {
                 driver = ((QSqlDriverCreatorBase*)(*it))->createObject();
             }
         }
     }
 #ifndef QT_NO_LIBRARY
     if (!driver && loader()) {
         if (QSqlDriverFactoryInterface *factory = qobject_cast<QSqlDriverFactoryInterface*>(loader()->instance(type)))
             driver = factory->create(type);
     }
 #endif // QT_NO_LIBRARY
     if (!driver) {
         qWarning("QSqlDatabase: %s driver not loaded", type.toLatin1().data());
         qWarning("QSqlDatabase: available drivers: %s",
                         QSqlDatabase::drivers().join(QLatin1String(" ")).toLatin1().data());
         if (QCoreApplication::instance() == 0)
             qWarning("QSqlDatabase: an instance of QCoreApplication is required for loading driver plugins");
         driver = shared_null()->driver;
     }
 }
invalidateDb()
void QSqlDatabasePrivate::invalidateDb (const QSqlDatabase & db, const QString & name, bool doWarn = true) static
Definition at line 232 of file qsqldatabase.cpp.
 {
     if (db.d->ref != 1 && doWarn) {
         qWarning("QSqlDatabasePrivate::removeDatabase: connection '%s' is still in use, "
                  "all queries will cease to work.", name.toLocal8Bit().constData());
         db.d->disable();
         db.d->connName.clear();
     }
 }
removeDatabase()
void QSqlDatabasePrivate::removeDatabase (const QString & name) static
Definition at line 242 of file qsqldatabase.cpp.
Referenced by QSqlDatabase::removeDatabase().
 {
     QConnectionDict *dict = dbDict();
     Q_ASSERT(dict);
     QWriteLocker locker(&dict->lock);
     if (!dict->contains(name))
         return;
     invalidateDb(dict->take(name), name);
 }
shared_null()
QSqlDatabasePrivate * QSqlDatabasePrivate::shared_null () static
Definition at line 225 of file qsqldatabase.cpp.
Referenced by QSqlDatabase::QSqlDatabase().
 {
     static QSqlNullDriver dr;
     static QSqlDatabasePrivate n(NULL, &dr);
     return &n;
 }
Properties
connName
QString QSqlDatabasePrivate::connName
Definition at line 159 of file qsqldatabase.cpp.
Referenced by addDatabase(), and invalidateDb().
connOptions
QString QSqlDatabasePrivate::connOptions
Definition at line 158 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
dbname
QString QSqlDatabasePrivate::dbname
Definition at line 152 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
driver
QSqlDriver* QSqlDatabasePrivate::driver
Definition at line 151 of file qsqldatabase.cpp.
Referenced by QSqlDatabasePrivate().
drvName
QString QSqlDatabasePrivate::drvName
Definition at line 156 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
hname
QString QSqlDatabasePrivate::hname
Definition at line 155 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
port
int QSqlDatabasePrivate::port
Definition at line 157 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
precisionPolicy
QSql::NumericalPrecisionPolicy QSqlDatabasePrivate::precisionPolicy
Definition at line 160 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
pword
QString QSqlDatabasePrivate::pword
Definition at line 154 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
q
QSqlDatabase* QSqlDatabasePrivate::q
Definition at line 150 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
ref
QAtomicInt QSqlDatabasePrivate::ref
Definition at line 149 of file qsqldatabase.cpp.
Referenced by invalidateDb().
uname
QString QSqlDatabasePrivate::uname
Definition at line 153 of file qsqldatabase.cpp.
Referenced by copy(), and QSqlDatabasePrivate().
The documentation for this class was generated from the following file:
/src/sql/kernel/qsqldatabase.cpp