Qt 4.8: QIcdEngine Class Reference
QIcdEngine Class Reference
#include <qicdengine.h>
Signals
void iapStateChanged (const QString &iapid, uint icd_connection_state)
Signals inherited from QBearerEngine
void configurationAdded (QNetworkConfigurationPrivatePointer config)
void configurationChanged (QNetworkConfigurationPrivatePointer config)
void configurationRemoved (QNetworkConfigurationPrivatePointer config)
void updateCompleted ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addConfiguration (QString &iap_id)
void addSessionConfiguration (QNetworkConfigurationPrivatePointer ptr)
QNetworkConfigurationManager::Capabilities capabilities () const
void changedSessionConfiguration (QNetworkConfigurationPrivatePointer ptr)
void cleanup ()
QNetworkConfigurationPrivatePointer configuration (const QString &id)
QNetworkSessionPrivate * createSessionBackend ()
QNetworkConfigurationPrivatePointer defaultConfiguration ()
void deleteConfiguration (const QString &iap_id)
bool hasIdentifier (const QString &id)
Q_INVOKABLE void initialize ()
QIcdEngine (QObject *parent=0)
Q_INVOKABLE void requestUpdate ()
~QIcdEngine ()
Public Functions inherited from QBearerEngine
bool configurationsInUse () const
QBearerEngine (QObject *parent=0)
virtual bool requiresPolling () const
virtual ~QBearerEngine ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Slots
void asyncUpdateConfigurationsSlot (QDBusMessage msg)
void connectionStateSignalsSlot (QDBusMessage msg)
void finishAsyncConfigurationUpdate ()
void icdServiceOwnerChanged (const QString &serviceName, const QString &oldOwner, const QString &newOwner)
Private Functions
void cancelAsyncConfigurationUpdate ()
void doRequestUpdate (QList< Maemo::IcdScanResult > scanned=QList< Maemo::IcdScanResult >())
bool ensureDBusConnection ()
void getIcdInitialState ()
void startListeningStateSignalsForAllConnections ()
Properties
bool firstUpdate
IapMonitor * iapMonitor
QDBusInterface * m_dbusInterface
QDBusServiceWatcher * m_icdServiceWatcher
QString m_onlineIapId
bool m_scanGoingOn
QList< Maemo::IcdScanResult > m_scanResult
QTimer m_scanTimer
QStringList m_typesToBeScanned
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QBearerEngine
QHash< QString, QNetworkConfigurationPrivatePointer > accessPointConfigurations
QMutex mutex
QHash< QString, QNetworkConfigurationPrivatePointer > snapConfigurations
QHash< QString, QNetworkConfigurationPrivatePointer > userChoiceConfigurations
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 97 of file qicdengine.h.
Constructors and Destructors
QIcdEngine()
QIcdEngine::QIcdEngine (QObject * parent = 0)
QIcdEngine implementation
Definition at line 231 of file qicdengine.cpp.
 :   QBearerEngine(parent), iapMonitor(0), m_dbusInterface(0), m_icdServiceWatcher(0),
     firstUpdate(true), m_scanGoingOn(false)
 {
 }
~QIcdEngine()
QIcdEngine::~QIcdEngine ()
Definition at line 237 of file qicdengine.cpp.
 {
     cleanup();
     delete iapMonitor;
 }
Functions
addConfiguration()
void QIcdEngine::addConfiguration (QString & iap_id)
Definition at line 412 of file qicdengine.cpp.
 {
     // Note: When new IAP is created, this function gets called multiple times
     //       in a row.
     //       For example: Empty type & name for WLAN was stored into newly
     //                    created IAP data in gconf when this function gets
     //                    called for the first time.
     //                    WLAN type & name are updated into IAP data in gconf
     //                    as soon as WLAN connection is up and running.
     //                    => And this function gets called again.
     QMutexLocker locker(&mutex);
     if (!accessPointConfigurations.contains(iap_id)) {
     Maemo::IAPConf saved_iap(iap_id);
         QString iap_type = saved_iap.value("type").toString();
         QString iap_name = saved_iap.value("name").toString();
         QByteArray ssid = saved_iap.value("wlan_ssid").toByteArray();
         if (!iap_type.isEmpty() && !iap_name.isEmpty()) {
             // Check if new IAP is actually Undefined WLAN configuration
             // Note: SSID is used as an iap id for Undefined WLAN configurations
             //       => configuration must be searched using SSID
             if (!ssid.isEmpty() && accessPointConfigurations.contains(ssid)) {
                 QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.take(ssid);
                 if (ptr) {
                     ptr->mutex.lock();
                     ptr->id = iap_id;
                     toIcdConfig(ptr)->iap_type = iap_type;
                     ptr->bearerType = bearerTypeFromIapType(iap_type);
                     toIcdConfig(ptr)->network_attrs = getNetworkAttrs(true, iap_id, iap_type, QString());
                     toIcdConfig(ptr)->network_id = ssid;
                     toIcdConfig(ptr)->service_id = saved_iap.value("service_id").toString();
                     toIcdConfig(ptr)->service_type = saved_iap.value("service_type").toString();
                     if (m_onlineIapId == iap_id) {
                         ptr->state = QNetworkConfiguration::Active;
                     } else {
                         ptr->state = QNetworkConfiguration::Defined;
                     }
                     ptr->mutex.unlock();
                     accessPointConfigurations.insert(iap_id, ptr);
                     locker.unlock();
                     emit configurationChanged(ptr);
                     locker.relock();
                 }
             } else {
                 IcdNetworkConfigurationPrivate *cpPriv = new IcdNetworkConfigurationPrivate;
                 cpPriv->name = saved_iap.value("name").toString();
                 if (cpPriv->name.isEmpty())
                     cpPriv->name = iap_id;
                 cpPriv->isValid = true;
                 cpPriv->id = iap_id;
                 cpPriv->iap_type = iap_type;
                 cpPriv->bearerType = bearerTypeFromIapType(iap_type);
                 cpPriv->network_attrs = getNetworkAttrs(true, iap_id, iap_type, QString());
                 cpPriv->service_id = saved_iap.value("service_id").toString();
                 cpPriv->service_type = saved_iap.value("service_type").toString();
                 if (iap_type.startsWith(QLatin1String("WLAN"))) {
                     QByteArray ssid = saved_iap.value("wlan_ssid").toByteArray();
                     if (ssid.isEmpty()) {
                         qWarning() << "Cannot get ssid for" << iap_id;
                     }
                     cpPriv->network_id = ssid;
                 }
                 cpPriv->type = QNetworkConfiguration::InternetAccessPoint;
                 if (m_onlineIapId == iap_id) {
                     cpPriv->state = QNetworkConfiguration::Active;
                 } else {
                     cpPriv->state = QNetworkConfiguration::Defined;
                 }
                 QNetworkConfigurationPrivatePointer ptr(cpPriv);
                 accessPointConfigurations.insert(iap_id, ptr);
 #ifdef BEARER_MANAGEMENT_DEBUG
                 qDebug("IAP: %s, name: %s, added to known list", iap_id.toAscii().data(), cpPriv->name.toAscii().data());
 #endif
                 locker.unlock();
                 emit configurationAdded(ptr);
                 locker.relock();
             }
         } else {
             qWarning("IAP %s does not have \"type\" or \"name\" fields defined, skipping this IAP.", iap_id.toAscii().data());
         }
     } else {
 #ifdef BEARER_MANAGEMENT_DEBUG
     qDebug() << "IAP" << iap_id << "already in db.";
 #endif
     /* Check if the data in db changed and update configuration accordingly
      */
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(iap_id);
     if (ptr) {
         Maemo::IAPConf changed_iap(iap_id);
         QString iap_type = changed_iap.value("type").toString();
         bool update_needed = false; /* if IAP type or ssid changed, we need to change the state */
         QMutexLocker configLocker(&ptr->mutex);
         toIcdConfig(ptr)->network_attrs = getNetworkAttrs(true, iap_id, iap_type, QString());
         toIcdConfig(ptr)->service_id = changed_iap.value("service_id").toString();
         toIcdConfig(ptr)->service_type = changed_iap.value("service_type").toString();
         if (!iap_type.isEmpty()) {
             ptr->name = changed_iap.value("name").toString();
             if (ptr->name.isEmpty())
                 ptr->name = iap_id;
             ptr->isValid = true;
             if (toIcdConfig(ptr)->iap_type != iap_type) {
                 toIcdConfig(ptr)->iap_type = iap_type;
                 ptr->bearerType = bearerTypeFromIapType(iap_type);
                 update_needed = true;
             }
             if (iap_type.startsWith(QLatin1String("WLAN"))) {
                 QByteArray ssid = changed_iap.value("wlan_ssid").toByteArray();
                 if (ssid.isEmpty()) {
                     qWarning() << "Cannot get ssid for" << iap_id;
                 }
                 if (toIcdConfig(ptr)->network_id != ssid) {
                     toIcdConfig(ptr)->network_id = ssid;
                     update_needed = true;
                 }
             }
         }
         if (update_needed) {
             ptr->type = QNetworkConfiguration::InternetAccessPoint;
             if (m_onlineIapId == iap_id) {
                 if (ptr->state < QNetworkConfiguration::Active) {
                     ptr->state = QNetworkConfiguration::Active;
                     configLocker.unlock();
                     locker.unlock();
                     emit configurationChanged(ptr);
                     locker.relock();
                 }
             } else if (ptr->state < QNetworkConfiguration::Defined) {
                 ptr->state = QNetworkConfiguration::Defined;
                 configLocker.unlock();
                 locker.unlock();
                 emit configurationChanged(ptr);
                 locker.relock();
             }
         }
     } else {
         qWarning("Cannot find IAP %s from current configuration although it should be there.", iap_id.toAscii().data());
     }
     }
 }
addSessionConfiguration()
void QIcdEngine::addSessionConfiguration (QNetworkConfigurationPrivatePointer ptr) inline
Definition at line 125 of file qicdengine.h.
Referenced by QNetworkSessionPrivateImpl::stateChange(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
     {
         QMutexLocker locker(&mutex);
         accessPointConfigurations.insert(ptr->id, ptr);
         locker.unlock();
         emit configurationAdded(ptr);
     }
asyncUpdateConfigurationsSlot
void QIcdEngine::asyncUpdateConfigurationsSlot (QDBusMessage msg) private slot
Definition at line 1064 of file qicdengine.cpp.
Referenced by cancelAsyncConfigurationUpdate(), and requestUpdate().
 {
     QMutexLocker locker(&mutex);
     QList<QVariant> arguments = msg.arguments();
     uint icd_scan_status = arguments.takeFirst().toUInt();
     if (icd_scan_status == ICD_SCAN_COMPLETE) {
         m_typesToBeScanned.removeOne(arguments[6].toString());
         if (!m_typesToBeScanned.count()) {
             locker.unlock();
             finishAsyncConfigurationUpdate();
             locker.relock();
         }
     } else {
         Maemo::IcdScanResult scanResult;
         scanResult.status = icd_scan_status;
         scanResult.timestamp = arguments.takeFirst().toUInt();
         scanResult.scan.service_type = arguments.takeFirst().toString();
         scanResult.service_name = arguments.takeFirst().toString();
         scanResult.scan.service_attrs = arguments.takeFirst().toUInt();
         scanResult.scan.service_id = arguments.takeFirst().toString();
         scanResult.service_priority = arguments.takeFirst().toInt();
         scanResult.scan.network_type = arguments.takeFirst().toString();
         scanResult.network_name = arguments.takeFirst().toString();
         scanResult.scan.network_attrs = arguments.takeFirst().toUInt();
         scanResult.scan.network_id = arguments.takeFirst().toByteArray();
         scanResult.network_priority = arguments.takeFirst().toInt();
         scanResult.signal_strength = arguments.takeFirst().toInt();
         scanResult.station_id = arguments.takeFirst().toString();
         scanResult.signal_dB = arguments.takeFirst().toInt();
         m_scanResult.append(scanResult);
     }
 }
cancelAsyncConfigurationUpdate()
void QIcdEngine::cancelAsyncConfigurationUpdate () private
Definition at line 1030 of file qicdengine.cpp.
Referenced by finishAsyncConfigurationUpdate().
 {
     if (!ensureDBusConnection())
         return;
     if (!m_scanGoingOn)
         return;
     m_scanGoingOn = false;
     if (m_scanTimer.isActive())
         m_scanTimer.stop();
     m_dbusInterface->connection().disconnect(ICD_DBUS_API_INTERFACE,
                                              ICD_DBUS_API_PATH,
                                              ICD_DBUS_API_INTERFACE,
                                              ICD_DBUS_API_SCAN_SIG,
                                              this, SLOT(asyncUpdateConfigurationsSlot(QDBusMessage)));
     // Stop scanning rounds by calling ICD_DBUS_API_SCAN_CANCEL
     // <=> If ICD_DBUS_API_SCAN_CANCEL is not called, new scanning round will
     //     be started after the module scan timeout.
     m_dbusInterface->call(ICD_DBUS_API_SCAN_CANCEL);
 }
capabilities()
QNetworkConfigurationManager::Capabilities QIcdEngine::capabilities () const virtual
Implements QBearerEngine.
Definition at line 243 of file qicdengine.cpp.
 {
     return QNetworkConfigurationManager::CanStartAndStopInterfaces |
            QNetworkConfigurationManager::DataStatistics |
            QNetworkConfigurationManager::ForcedRoaming |
            QNetworkConfigurationManager::NetworkSessionRequired;
 }
changedSessionConfiguration()
void QIcdEngine::changedSessionConfiguration (QNetworkConfigurationPrivatePointer ptr) inline
Definition at line 135 of file qicdengine.h.
Referenced by QNetworkSessionPrivateImpl::stateChange(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
     {
         emit configurationChanged(ptr);
     }
cleanup()
void QIcdEngine::cleanup ()
Definition at line 1099 of file qicdengine.cpp.
Referenced by icdServiceOwnerChanged(), and ~QIcdEngine().
 {
     if (m_scanGoingOn) {
         m_scanTimer.stop();
         m_dbusInterface->call(ICD_DBUS_API_SCAN_CANCEL);
     }
     if (iapMonitor)
         iapMonitor->cleanup();
 }
configuration()
QNetworkConfigurationPrivatePointer QIcdEngine::configuration (const QString & id) inline
Definition at line 118 of file qicdengine.h.
Referenced by QNetworkSessionPrivateImpl::stateChange().
     {
         QMutexLocker locker(&mutex);
         return accessPointConfigurations.value(id);
     }
connectionStateSignalsSlot
void QIcdEngine::connectionStateSignalsSlot (QDBusMessage msg) private slot
Definition at line 881 of file qicdengine.cpp.
Referenced by startListeningStateSignalsForAllConnections().
 {
     QMutexLocker locker(&mutex);
     QList<QVariant> arguments = msg.arguments();
     if (arguments[1].toUInt() != 0 || arguments.count() < 8) {
         return;
     }
     QString iapid = arguments[5].toByteArray().data();
     uint icd_connection_state = arguments[7].toUInt();
     switch (icd_connection_state) {
     case ICD_STATE_CONNECTED:
         {
         QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(iapid);
         if (ptr) {
             QMutexLocker configLocker(&ptr->mutex);
             ptr->type = QNetworkConfiguration::InternetAccessPoint;
             if (ptr->state != QNetworkConfiguration::Active) {
                 ptr->state = QNetworkConfiguration::Active;
                 configLocker.unlock();
                 locker.unlock();
                 emit configurationChanged(ptr);
                 locker.relock();
                 m_onlineIapId = iapid;
             }
         } else {
             // This gets called when new WLAN IAP is created using Connection dialog
             // At this point Undefined WLAN configuration has SSID as iap id
             // => Because of that configuration can not be found from
             //    accessPointConfigurations using correct iap id
             m_onlineIapId = iapid;
         }
         break;
         }
     case ICD_STATE_DISCONNECTED:
         {
         QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(iapid);
         if (ptr) {
             QMutexLocker configLocker(&ptr->mutex);
             ptr->type = QNetworkConfiguration::InternetAccessPoint;
             if (ptr->state == QNetworkConfiguration::Active) {
                 ptr->state = QNetworkConfiguration::Discovered;
                 configLocker.unlock();
                 locker.unlock();
                 emit iapStateChanged(iapid, icd_connection_state);
                 emit configurationChanged(ptr);
                 locker.relock();
                 // Note: If ICD switches used IAP from one to another:
                 //       1) new IAP is reported to be online first
                 //       2) old IAP is reported to be offline then
                 // => Device can be reported to be offline only
                 //    if last known online IAP is reported to be disconnected
                 if (iapid == m_onlineIapId) {
                     // It's known that there is only one global ICD connection
                     // => Because ICD state was reported to be DISCONNECTED, Device is offline
                     m_onlineIapId.clear();
                 }
             }
         } else {
             // Disconnected IAP was not found from accessPointConfigurations
             // => Reason: Online IAP was removed which resulted ICD to disconnect
             if (iapid == m_onlineIapId) {
                 // It's known that there is only one global ICD connection
                 // => Because ICD state was reported to be DISCONNECTED, Device is offline
                 m_onlineIapId.clear();
             }
         }
         break;
         }
     default:
         break;
     }
     locker.unlock();
     emit iapStateChanged(iapid, icd_connection_state);
     locker.relock();
 }
createSessionBackend()
QNetworkSessionPrivate * QIcdEngine::createSessionBackend () virtual
Implements QBearerEngine.
Definition at line 1118 of file qicdengine.cpp.
 {
     return new QNetworkSessionPrivateImpl(this);
 }
defaultConfiguration()
QNetworkConfigurationPrivatePointer QIcdEngine::defaultConfiguration () virtual
Implements QBearerEngine.
Definition at line 818 of file qicdengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!ensureDBusConnection())
         return QNetworkConfigurationPrivatePointer();
     // Here we just return [ANY] request to icd and let the icd decide which IAP to connect.
     return userChoiceConfigurations.value(OSSO_IAP_ANY);
 }
deleteConfiguration()
void QIcdEngine::deleteConfiguration (const QString & iap_id)
Definition at line 343 of file qicdengine.cpp.
 {
     QMutexLocker locker(&mutex);
     /* Called when IAPs are deleted in db, in this case we do not scan
      * or read all the IAPs from db because it might take too much power
      * (multiple applications would need to scan and read all IAPs from db)
      */
     QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.take(iap_id);
     if (ptr) {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug() << "IAP" << iap_id << "was removed from storage.";
 #endif
         locker.unlock();
         emit configurationRemoved(ptr);
     } else {
 #ifdef BEARER_MANAGEMENT_DEBUG
         qDebug("IAP: %s, already missing from the known list", iap_id.toAscii().data());
 #endif
     }
 }
doRequestUpdate()
void QIcdEngine::doRequestUpdate (QList< Maemo::IcdScanResult > scanned = QList<Maemo::IcdScanResult>()) private
Definition at line 563 of file qicdengine.cpp.
Referenced by ensureDBusConnection(), and finishAsyncConfigurationUpdate().
 {
     /* Contains all known iap_ids from storage */
     QList<QString> knownConfigs = accessPointConfigurations.keys();
     /* Contains all known WLAN network ids (like ssid) from storage */
     QMultiHash<QByteArray, SSIDInfo* > notDiscoveredWLANConfigs;
     QList<QString> all_iaps;
     Maemo::IAPConf::getAll(all_iaps);
     foreach (const QString &iap_id, all_iaps) {
         QByteArray ssid;
         Maemo::IAPConf saved_ap(iap_id);
         bool is_temporary = saved_ap.value("temporary").toBool();
         if (is_temporary) {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug() << "IAP" << iap_id << "is temporary, skipping it.";
 #endif
             continue;
         }
         QString iap_type = saved_ap.value("type").toString();
         if (iap_type.startsWith(QLatin1String("WLAN"))) {
             ssid = saved_ap.value("wlan_ssid").toByteArray();
             if (ssid.isEmpty())
                 continue;
             QString security_method = saved_ap.value("wlan_security").toString();
             SSIDInfo *info = new SSIDInfo;
             info->iap_id = iap_id;
             info->wlan_security = security_method;
                 notDiscoveredWLANConfigs.insert(ssid, info);
         } else if (iap_type.isEmpty()) {
             continue;
         } else {
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug() << "IAP" << iap_id << "network type is" << iap_type;
 #endif
             ssid.clear();
         }
         if (!accessPointConfigurations.contains(iap_id)) {
             IcdNetworkConfigurationPrivate *cpPriv = new IcdNetworkConfigurationPrivate;
             cpPriv->name = saved_ap.value("name").toString();
             if (cpPriv->name.isEmpty()) {
                 if (!ssid.isEmpty() && ssid.size() > 0)
                     cpPriv->name = ssid.data();
                 else
                     cpPriv->name = iap_id;
             }
             cpPriv->isValid = true;
             cpPriv->id = iap_id;
             cpPriv->network_id = ssid;
             cpPriv->network_attrs = getNetworkAttrs(true, iap_id, iap_type, QString());
             cpPriv->iap_type = iap_type;
             cpPriv->bearerType = bearerTypeFromIapType(iap_type);
             cpPriv->service_id = saved_ap.value("service_id").toString();
             cpPriv->service_type = saved_ap.value("service_type").toString();
             cpPriv->type = QNetworkConfiguration::InternetAccessPoint;
             cpPriv->state = QNetworkConfiguration::Defined;
             QNetworkConfigurationPrivatePointer ptr(cpPriv);
             accessPointConfigurations.insert(iap_id, ptr);
             mutex.unlock();
             emit configurationAdded(ptr);
             mutex.lock();
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("IAP: %s, name: %s, ssid: %s, added to known list",
                    iap_id.toAscii().data(), ptr->name.toAscii().data(),
                    !ssid.isEmpty() ? ssid.data() : "-");
 #endif
         } else {
             knownConfigs.removeOne(iap_id);
 #ifdef BEARER_MANAGEMENT_DEBUG
             qDebug("IAP: %s, ssid: %s, already exists in the known list",
                    iap_id.toAscii().data(), !ssid.isEmpty() ? ssid.data() : "-");
 #endif
         }
     }
     /* This is skipped in the first update as scanned size is zero */
     if (!scanned.isEmpty()) {
         for (int i=0; i<scanned.size(); ++i) {
             const Maemo::IcdScanResult ap = scanned.at(i);
             if (ap.scan.network_attrs & ICD_NW_ATTR_IAPNAME) {
                 /* The network_id is IAP id, so the IAP is a known one */
                 QString iapid = ap.scan.network_id.data();
                 QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(iapid);
                 if (ptr) {
                     bool changed = false;
                     ptr->mutex.lock();
                     if (!ptr->isValid) {
                         ptr->isValid = true;
                         changed = true;
                     }
                     /* If this config is the current active one, we do not set it
                      * to discovered.
                      */
                     if ((ptr->state != QNetworkConfiguration::Discovered) &&
                         (ptr->state != QNetworkConfiguration::Active)) {
                         ptr->state = QNetworkConfiguration::Discovered;
                         changed = true;
                     }
                     toIcdConfig(ptr)->network_attrs = ap.scan.network_attrs;
                     toIcdConfig(ptr)->service_id = ap.scan.service_id;
                     toIcdConfig(ptr)->service_type = ap.scan.service_type;
                     toIcdConfig(ptr)->service_attrs = ap.scan.service_attrs;
 #ifdef BEARER_MANAGEMENT_DEBUG
                     qDebug("IAP: %s, ssid: %s, discovered",
                            iapid.toAscii().data(), toIcdConfig(ptr)->network_id.data());
 #endif
                     ptr->mutex.unlock();
                     if (changed) {
                         mutex.unlock();
                         emit configurationChanged(ptr);
                         mutex.lock();
                     }
                     if (!ap.scan.network_type.startsWith(QLatin1String("WLAN")))
                         continue; // not a wlan AP
                     /* Remove scanned AP from discovered WLAN configurations so that we can
                      * emit configurationRemoved signal later
                      */
                     ptr->mutex.lock();
                     QList<SSIDInfo* > known_iaps = notDiscoveredWLANConfigs.values(toIcdConfig(ptr)->network_id);
 rescan_list:
                     if (!known_iaps.isEmpty()) {
                         for (int k=0; k<known_iaps.size(); ++k) {
                             SSIDInfo *iap = known_iaps.at(k);
                             if (iap->wlan_security ==
                                 network_attrs_to_security(ap.scan.network_attrs)) {
                                 /* Remove IAP from the list */
                                 notDiscoveredWLANConfigs.remove(toIcdConfig(ptr)->network_id, iap);
 #ifdef BEARER_MANAGEMENT_DEBUG
                                 qDebug() << "Removed IAP" << iap->iap_id << "from unknown config";
 #endif
                                 known_iaps.removeAt(k);
                                 delete iap;
                                 goto rescan_list;
                             }
                         }
                     }
                     ptr->mutex.unlock();
                 }
             } else {
                 /* Non saved access point data */
                 QByteArray scanned_ssid = ap.scan.network_id;
                 if (!accessPointConfigurations.contains(scanned_ssid)) {
                     IcdNetworkConfigurationPrivate *cpPriv = new IcdNetworkConfigurationPrivate;
                     QString hrs = scanned_ssid.data();
                     cpPriv->name = ap.network_name.isEmpty() ? hrs : ap.network_name;
                     cpPriv->isValid = true;
                     cpPriv->id = scanned_ssid.data();  // Note: id is now ssid, it should be set to IAP id if the IAP is saved
                     cpPriv->network_id = scanned_ssid;
                     cpPriv->iap_type = ap.scan.network_type;
                     cpPriv->bearerType = bearerTypeFromIapType(cpPriv->iap_type);
                     cpPriv->network_attrs = ap.scan.network_attrs;
                     cpPriv->service_id = ap.scan.service_id;
                     cpPriv->service_type = ap.scan.service_type;
                     cpPriv->service_attrs = ap.scan.service_attrs;
                     cpPriv->type = QNetworkConfiguration::InternetAccessPoint;
                     cpPriv->state = QNetworkConfiguration::Undefined;
 #ifdef BEARER_MANAGEMENT_DEBUG
                     qDebug() << "IAP with network id" << cpPriv->id << "was found in the scan.";
 #endif
                     QNetworkConfigurationPrivatePointer ptr(cpPriv);
                     accessPointConfigurations.insert(ptr->id, ptr);
                     mutex.unlock();
                     emit configurationAdded(ptr);
                     mutex.lock();
                 } else {
                     knownConfigs.removeOne(scanned_ssid);
                 }
             }
         }
     }
     if (!firstUpdate) {
         // Update Defined status to all defined WLAN IAPs which
         // could not be found when access points were scanned
         QHashIterator<QByteArray, SSIDInfo* > i(notDiscoveredWLANConfigs);
         while (i.hasNext()) {
             i.next();
             SSIDInfo *iap = i.value();
             QString iap_id = iap->iap_id;
             //qDebug() << i.key() << ": " << iap_id;
             QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.value(iap_id);
             if (ptr) {
                 QMutexLocker configLocker(&ptr->mutex);
                 // WLAN AccessPoint configuration could not be Discovered
                 // => Make sure that configuration state is Defined
                 if (ptr->state > QNetworkConfiguration::Defined) {
                     ptr->state = QNetworkConfiguration::Defined;
                     configLocker.unlock();
                     mutex.unlock();
                     emit configurationChanged(ptr);
                     mutex.lock();
                 }
             }
         }
         /* Remove non existing iaps since last update */
         foreach (const QString &oldIface, knownConfigs) {
             QNetworkConfigurationPrivatePointer ptr = accessPointConfigurations.take(oldIface);
             if (ptr) {
                 mutex.unlock();
                 emit configurationRemoved(ptr);
                 mutex.lock();
                 //if we would have SNAP support we would have to remove the references
                 //from existing ServiceNetworks to the removed access point configuration
             }
         }
     }
     QMutableHashIterator<QByteArray, SSIDInfo* > i(notDiscoveredWLANConfigs);
     while (i.hasNext()) {
         i.next();
         SSIDInfo *iap = i.value();
         delete iap;
         i.remove();
     }
     if (!firstUpdate) {
         mutex.unlock();
         emit updateCompleted();
         mutex.lock();
     }
     if (firstUpdate)
         firstUpdate = false;
 }
ensureDBusConnection()
bool QIcdEngine::ensureDBusConnection () private
Definition at line 251 of file qicdengine.cpp.
Referenced by cancelAsyncConfigurationUpdate(), defaultConfiguration(), icdServiceOwnerChanged(), initialize(), and requestUpdate().
 {
     if (m_dbusInterface)
         return true;
     // Setup DBus Interface for ICD
     m_dbusInterface = new QDBusInterface(ICD_DBUS_API_INTERFACE,
                                          ICD_DBUS_API_PATH,
                                          ICD_DBUS_API_INTERFACE,
                                          QDBusConnection::systemBus(),
                                          this);
     if (!m_dbusInterface->isValid()) {
         delete m_dbusInterface;
         m_dbusInterface = 0;
         if (!m_icdServiceWatcher) {
             m_icdServiceWatcher = new QDBusServiceWatcher(ICD_DBUS_API_INTERFACE,
                                                           QDBusConnection::systemBus(),
                                                           QDBusServiceWatcher::WatchForOwnerChange,
                                                           this);
             connect(m_icdServiceWatcher, SIGNAL(serviceOwnerChanged(QString,QString,QString)),
                     this, SLOT(icdServiceOwnerChanged(QString,QString,QString)));
         }
         return false;
     }
     connect(&m_scanTimer, SIGNAL(timeout()), this, SLOT(finishAsyncConfigurationUpdate()));
     m_scanTimer.setSingleShot(true);
     /* Turn on IAP state monitoring */
     startListeningStateSignalsForAllConnections();
     /* Turn on IAP add/remove monitoring */
     iapMonitor = new IapMonitor;
     iapMonitor->setup(this);
     /* We create a default configuration which is a pseudo config */
     QNetworkConfigurationPrivate *cpPriv = new IcdNetworkConfigurationPrivate;
     cpPriv->name = "UserChoice";
     cpPriv->state = QNetworkConfiguration::Discovered;
     cpPriv->isValid = true;
     cpPriv->id = OSSO_IAP_ANY;
     cpPriv->type = QNetworkConfiguration::UserChoice;
     cpPriv->purpose = QNetworkConfiguration::UnknownPurpose;
     cpPriv->roamingSupported = false;
     QNetworkConfigurationPrivatePointer ptr(cpPriv);
     userChoiceConfigurations.insert(cpPriv->id, ptr);
     doRequestUpdate();
     getIcdInitialState();
     return true;
 }
finishAsyncConfigurationUpdate
void QIcdEngine::finishAsyncConfigurationUpdate () private slot
Definition at line 1055 of file qicdengine.cpp.
Referenced by asyncUpdateConfigurationsSlot(), and ensureDBusConnection().
 {
     QMutexLocker locker(&mutex);
     cancelAsyncConfigurationUpdate();
     doRequestUpdate(m_scanResult);
     m_scanResult.clear();
 }
getIcdInitialState()
void QIcdEngine::getIcdInitialState () private
Definition at line 839 of file qicdengine.cpp.
Referenced by ensureDBusConnection().
 {
     /* Instead of requesting ICD status asynchronously, we ask it synchronously.
      * It ensures that we always get right icd status BEFORE initialize() ends.
      * If not, initialize()  might end before we got icd status and
      * QNetworkConfigurationManager::updateConfigurations()
      * call from user might also end before receiving icd status.
      * In such case, we come up to a bug:
      * QNetworkConfigurationManagerPrivate::isOnline() will be false even
      * if we are connected.
      */
     Maemo::Icd icd;
     QList<Maemo::IcdStateResult> state_results;
     QNetworkConfigurationPrivatePointer ptr;
     if (icd.state(state_results) && !state_results.isEmpty()) {
         if (!(state_results.first().params.network_attrs == 0 &&
               state_results.first().params.network_id.isEmpty())) {
             switch (state_results.first().state) {
             case ICD_STATE_CONNECTED:
                 m_onlineIapId = state_results.first().params.network_id;
                 ptr = accessPointConfigurations.value(m_onlineIapId);
                 if (ptr) {
                     QMutexLocker configLocker(&ptr->mutex);
                     ptr->state = QNetworkConfiguration::Active;
                     configLocker.unlock();
                     mutex.unlock();
                     emit configurationChanged(ptr);
                     mutex.lock();
                 }
                 break;
             default:
                 break;
             }
         }
     }
 }
hasIdentifier()
bool QIcdEngine::hasIdentifier (const QString & id) virtual
Implements QBearerEngine.
Definition at line 1109 of file qicdengine.cpp.
Referenced by QNetworkSessionPrivateImpl::stateChange(), and QNetworkSessionPrivateImpl::syncStateWithInterface().
 {
     QMutexLocker locker(&mutex);
     return accessPointConfigurations.contains(id) ||
            snapConfigurations.contains(id) ||
            userChoiceConfigurations.contains(id);
 }
iapStateChanged
void QIcdEngine::iapStateChanged (const QString & iapid, uint icd_connection_state) signal
Referenced by connectionStateSignalsSlot().
icdServiceOwnerChanged
void QIcdEngine::icdServiceOwnerChanged (const QString & serviceName, const QString & oldOwner, const QString & newOwner) private slot
Definition at line 967 of file qicdengine.cpp.
Referenced by ensureDBusConnection().
 {
     Q_UNUSED(serviceName);
     Q_UNUSED(oldOwner);
     QMutexLocker locker(&mutex);
     if (newOwner.isEmpty()) {
         // Disconnected from ICD, remove all configurations
         cleanup();
         delete iapMonitor;
         iapMonitor = 0;
         delete m_dbusInterface;
         m_dbusInterface = 0;
         QMutableHashIterator<QString, QNetworkConfigurationPrivatePointer> i(accessPointConfigurations);
         while (i.hasNext()) {
             i.next();
             QNetworkConfigurationPrivatePointer ptr = i.value();
             i.remove();
             locker.unlock();
             emit configurationRemoved(ptr);
             locker.relock();
         }
         userChoiceConfigurations.clear();
     } else {
         // Connected to ICD ensure connection.
         ensureDBusConnection();
     }
 }
initialize()
void QIcdEngine::initialize ()
Definition at line 310 of file qicdengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!ensureDBusConnection()) {
         locker.unlock();
         emit updateCompleted();
         locker.relock();
     }
 }
requestUpdate()
void QIcdEngine::requestUpdate ()
Definition at line 1002 of file qicdengine.cpp.
 {
     QMutexLocker locker(&mutex);
     if (!ensureDBusConnection()) {
         locker.unlock();
         emit updateCompleted();
         locker.relock();
         return;
     }
     if (m_scanGoingOn)
         return;
     m_scanGoingOn = true;
     m_dbusInterface->connection().connect(ICD_DBUS_API_INTERFACE,
                                           ICD_DBUS_API_PATH,
                                           ICD_DBUS_API_INTERFACE,
                                           ICD_DBUS_API_SCAN_SIG,
                                           this, SLOT(asyncUpdateConfigurationsSlot(QDBusMessage)));
     QDBusMessage msg = m_dbusInterface->call(ICD_DBUS_API_SCAN_REQ,
                                              (uint)ICD_SCAN_REQUEST_ACTIVE);
     m_typesToBeScanned = msg.arguments()[0].value<QStringList>();
     m_scanTimer.start(ICD_SHORT_SCAN_TIMEOUT);
 }
startListeningStateSignalsForAllConnections()
void QIcdEngine::startListeningStateSignalsForAllConnections () private
Definition at line 829 of file qicdengine.cpp.
Referenced by ensureDBusConnection().
 {
     // Start listening ICD_DBUS_API_STATE_SIG signals
     m_dbusInterface->connection().connect(ICD_DBUS_API_INTERFACE,
                                           ICD_DBUS_API_PATH,
                                           ICD_DBUS_API_INTERFACE,
                                           ICD_DBUS_API_STATE_SIG,
                                           this, SLOT(connectionStateSignalsSlot(QDBusMessage)));
 }
Properties
firstUpdate
bool QIcdEngine::firstUpdate private
Definition at line 171 of file qicdengine.h.
Referenced by doRequestUpdate().
iapMonitor
IapMonitor* QIcdEngine::iapMonitor private
Definition at line 162 of file qicdengine.h.
Referenced by cleanup(), ensureDBusConnection(), icdServiceOwnerChanged(), and ~QIcdEngine().
m_dbusInterface
QDBusInterface* QIcdEngine::m_dbusInterface private
Definition at line 163 of file qicdengine.h.
Referenced by cancelAsyncConfigurationUpdate(), cleanup(), ensureDBusConnection(), icdServiceOwnerChanged(), requestUpdate(), and startListeningStateSignalsForAllConnections().
m_icdServiceWatcher
QDBusServiceWatcher* QIcdEngine::m_icdServiceWatcher private
Definition at line 169 of file qicdengine.h.
Referenced by ensureDBusConnection().
m_onlineIapId
QString QIcdEngine::m_onlineIapId private
Definition at line 165 of file qicdengine.h.
Referenced by addConfiguration(), connectionStateSignalsSlot(), and getIcdInitialState().
m_scanGoingOn
bool QIcdEngine::m_scanGoingOn private
Definition at line 172 of file qicdengine.h.
Referenced by cancelAsyncConfigurationUpdate(), cleanup(), and requestUpdate().
m_scanResult
QList<Maemo::IcdScanResult> QIcdEngine::m_scanResult private
Definition at line 167 of file qicdengine.h.
Referenced by asyncUpdateConfigurationsSlot(), and finishAsyncConfigurationUpdate().
m_scanTimer
QTimer QIcdEngine::m_scanTimer private
Definition at line 164 of file qicdengine.h.
Referenced by cancelAsyncConfigurationUpdate(), cleanup(), ensureDBusConnection(), and requestUpdate().
m_typesToBeScanned
QStringList QIcdEngine::m_typesToBeScanned private
Definition at line 166 of file qicdengine.h.
Referenced by asyncUpdateConfigurationsSlot(), and requestUpdate().
The documentation for this class was generated from the following files:
/src/plugins/bearer/icd/qicdengine.h
/src/plugins/bearer/icd/qicdengine.cpp