Qt 4.8: QPatternist::FunctionCall Class Reference
QPatternist::FunctionCall Class Reference
Base class for implementations of builtin functions.
#include <qfunctioncall_p.h>
Public Types
typedef QExplicitlySharedDataPointer< FunctionCall > Ptr
Public Types inherited from QPatternist::UnlimitedContainer
enum CardinalityComputation { ProductOfCardinality, UnionOfCardinality }
Public Types inherited from QPatternist::Expression
typedef QExplicitlySharedDataPointer< const Expression > ConstPtr
A smart pointer wrapping const Expression instances.
enum ID {
IDBooleanValue = 1, IDCountFN, IDEmptyFN, IDExistsFN,
IDExpressionSequence, IDGeneralComparison, IDIfThenClause, IDIgnorableExpression,
IDIntegerValue, IDPositionFN, IDStringValue, IDValueComparison,
IDRangeVariableReference, IDContextItem, IDUserFunctionCallsite, IDExpressionVariableReference,
IDAttributeConstructor, IDUpperCaseFN, IDLowerCaseFN, IDFirstItemPredicate,
IDEmptySequence, IDReturnOrderBy, IDLetClause, IDForClause,
IDPath, IDNamespaceConstructor, IDArgumentReference, IDGenericPredicate,
IDAxisStep, IDFloat, IDCombineNodes, IDUnresolvedVariableReference,
IDCardinalityVerifier
}
typedef QList< Expression::Ptr > List
typedef QFlags< Property > Properties
enum Property {
UseContextItem = 1, DisableElimination = 1 << 1, IsEvaluated = 1 << 2, DisableTypingDeduction = 1 << 3,
EmptynessFollowsChild = 1 << 4, RewriteToEmptyOnEmpty = 1 << 5, RequiresFocus = 1 << 6, AffectsOrderOnly = 1 << 7,
RequiresContextItem = (1 << 8) | RequiresFocus, CreatesFocusForLast = 1 << 9, LastOperandIsCollation = 1 << 10, DependsOnLocalVariable = (1 << 11) | DisableElimination,
EvaluationCacheRedundant = (1 << 12), IsNodeConstructor = 1 << 13, RequiresCurrentItem = 1 << 14
}
typedef QExplicitlySharedDataPointer< Expression > Ptr
A smart pointer wrapping mutable Expression instances.
typedef ::QAbstractXmlForwardIterator< Expression::Ptr > QAbstractXmlForwardIterator
typedef QVector< Expression::Ptr > Vector
Public Functions
virtual ExpressionVisitorResult::Ptr accept (const ExpressionVisitor::Ptr &visitor) const
virtual SequenceType::List expectedOperandTypes () const
virtual ID id () const
virtual Expression::Properties properties () const
virtual void setSignature (const FunctionSignature::Ptr &sign)
virtual FunctionSignature::Ptr signature () const
virtual SequenceType::Ptr staticType () const
virtual Expression::Ptr typeCheck (const StaticContext::Ptr &context, const SequenceType::Ptr &reqType)
Public Functions inherited from QPatternist::UnlimitedContainer
virtual bool compressOperands (const StaticContext::Ptr &)
virtual Expression::List operands () const
virtual void setOperands (const Expression::List &list)
UnlimitedContainer (const Expression::List &operands=Expression::List())
Public Functions inherited from QPatternist::Expression
virtual const SourceLocationReflection * actualReflection () const
Returns this.
virtual void announceFocusType (const ItemType::Ptr &itemType)
virtual Expression::Ptr compress (const StaticContext::Ptr &context)
Properties deepProperties () const
Computes the union of properties for this Expression and all its descending children.
virtual Properties dependencies () const
virtual QString description () const
virtual bool evaluateEBV (const DynamicContext::Ptr &context) const
virtual Item::Iterator::Ptr evaluateSequence (const DynamicContext::Ptr &context) const
virtual Item evaluateSingleton (const DynamicContext::Ptr &context) const
virtual void evaluateToSequenceReceiver (const DynamicContext::Ptr &context) const
virtual ItemType::Ptr expectedContextItemType () const
Expression ()
bool has (const Property prop) const
bool hasDependency (const Property prop) const
bool is (const ID id) const
bool isEvaluated () const
virtual ItemType::Ptr newFocusType () const
virtual QList< QExplicitlySharedDataPointer< OptimizationPass > > optimizationPasses () const
virtual PatternPriority patternPriority () const
const Expression::Ptr & rewrite (const Expression::Ptr &to, const StaticContext::Ptr &context) const
Rewrites this Expression to to, and return to.
virtual ~Expression ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< Expression >
const TCastTarget * as () const
TCastTarget * as ()
Public Functions inherited from QPatternist::SourceLocationReflection
virtual QSourceLocation sourceLocation () const
SourceLocationReflection ()
virtual ~SourceLocationReflection ()
Properties
FunctionSignature::Ptr m_signature
Additional Inherited Members
Static Public Functions inherited from QPatternist::Expression
static void rewrite (Expression::Ptr &old, const Expression::Ptr &New, const StaticContext::Ptr &context)
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::UnlimitedContainer
template<CardinalityComputation suppliedCard>
SequenceType::Ptr operandsUnionType () const
Protected Functions inherited from QPatternist::Expression
void typeCheckOperands (const StaticContext::Ptr &context)
Protected Functions inherited from QPatternist::CppCastingHelper< Expression >
CppCastingHelper ()
Protected Variables inherited from QPatternist::UnlimitedContainer
Expression::List m_operands
Detailed Description
Base class for implementations of builtin functions.
However, it doesn't handle user declared functions.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 73 of file qfunctioncall_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<FunctionCall> QPatternist::FunctionCall::Ptr
Definition at line 76 of file qfunctioncall_p.h.
Functions
accept()
ExpressionVisitorResult::Ptr FunctionCall::accept (const ExpressionVisitor::Ptr & visitor) const virtual
Implements QPatternist::Expression.
Definition at line 149 of file qfunctioncall.cpp.
 {
     return visitor->visit(this);
 }
expectedOperandTypes()
SequenceType::List FunctionCall::expectedOperandTypes () const virtual
Returns a list of Sequence Types, describing the type of each of the expression's operands. Hence, this function has a relationship to the operands() function:
- The lengths of the lists returned by expectedOperandTypes()
and operands() should always be equal in length, since one
cannot describe the type of a non-existent operand(and all
operands must have type information).
- A significant difference between the two functions is that while
the type of objects in the list returned by operands() may vary
between compilations/static context, simply because the particular
Expression is part of different XPath expressions, the
types in the list returned by expectedOperandTypes is always the same
since the function/operator signature never changes.
This function should not be confused with staticType(), which returns the static type of the expression itself, not its operands. The function call is an expression where this is clear: the type of the return value is not the same as the arguments' types. The static type of the operands supplied to the expression can be determined via the staticType() function of the instances returned by operands().
If the expression has no operands, an empty list should be returned.
Implements QPatternist::Expression.
Definition at line 57 of file qfunctioncall.cpp.
 {
     const FunctionArgument::List args(signature()->arguments());
     FunctionArgument::List::const_iterator it(args.constBegin());
     const FunctionArgument::List::const_iterator end(args.constEnd());
     // TODO reserve/resize()
     SequenceType::List result;
     for(; it != end; ++it)
         result.append((*it)->type());
     return result;
 }
id()
Expression::ID FunctionCall::id () const virtual
This property, which has no setter, returns an enum value that uniquely identifies this Expression. Patternist makes no use of C++'s dynamic_cast feature, but uses this polymorphic function instead.
Returns
always IgnorableExpression.
Reimplemented from QPatternist::Expression.
Definition at line 154 of file qfunctioncall.cpp.
 {
     Q_ASSERT(m_signature);
     return m_signature->id();
 }
properties()
Expression::Properties FunctionCall::properties () const virtual
Returns
a bitwise OR'd value of properties, describing the characteristics of the expression. These properties affects how this Expression is treated in for example type checking stages.
The default implementation returns 0. Override and let the function return a different value, if that's of interest.
An important decision when re-implementing properties() is whether to OR in the properties() of ones operands. For instance, if an operand has RequiresFocus set, that flag nost likely applies to the apparent as well, since it depends on its operand.
See also
deepProperties()
Returns
Expression::None, meaning no special properties
Reimplemented from QPatternist::Expression.
Definition at line 143 of file qfunctioncall.cpp.
Referenced by typeCheck().
 {
     Q_ASSERT(m_signature);
     return signature()->properties();
 }
setSignature()
void FunctionCall::setSignature (const FunctionSignature::Ptr & sign) virtual
Definition at line 109 of file qfunctioncall.cpp.
 {
     m_signature = sign;
 }
signature()
FunctionSignature::Ptr FunctionCall::signature () const virtual
Reimplemented in QPatternist::ErrorFN.
Definition at line 114 of file qfunctioncall.cpp.
Referenced by QPatternist::ContextNodeChecker::checkTargetNode(), expectedOperandTypes(), properties(), QPatternist::ErrorFN::signature(), staticType(), typeCheck(), QPatternist::AddingAggregate::typeCheck(), QPatternist::AvgFN::typeCheck(), and QPatternist::SumFN::typeCheck().
 {
     Q_ASSERT(m_signature); /* It really should be set. */
     return m_signature;
 }
staticType()
SequenceType::Ptr FunctionCall::staticType () const virtual
Returns
the static type of this Expression. For example, an 'and' expression have as static type xs:boolean
Implements QPatternist::Expression.
Reimplemented in QPatternist::SubsequenceFN, QPatternist::ReverseFN, QPatternist::RemoveFN, QPatternist::InsertBeforeFN, QPatternist::DistinctValuesFN, QPatternist::RootFN, QPatternist::SumFN, QPatternist::DocFN, QPatternist::AvgFN, QPatternist::Aggregator, QPatternist::TraceFN, and QPatternist::CurrentFN.
Definition at line 120 of file qfunctioncall.cpp.
Referenced by QPatternist::DistinctValuesFN::DistinctValuesFN().
 {
     Q_ASSERT(m_signature);
     if(has(EmptynessFollowsChild))
     {
         if(m_operands.isEmpty())
         {
             /* This is a function which uses the context item when having no arguments. */
             return signature()->returnType();
         }
         const Cardinality card(m_operands.first()->staticType()->cardinality());
         if(card.allowsEmpty())
             return signature()->returnType();
         else
         {
             /* Remove empty. */
             return makeGenericSequenceType(signature()->returnType()->itemType(),
                                            card & Cardinality::oneOrMore());
         }
     }
     return signature()->returnType();
 }
typeCheck()
Expression::Ptr FunctionCall::typeCheck (const StaticContext::Ptr & context, const SequenceType::Ptr & reqType) virtual
This implementation guarantees to never rewrite away this Expression, but at most rewrite it as a child of another expression(that presumably have a type checking role). It is therefore always safe to override this function and call this implementation and not worry about that this Expression becomes deleted.
Many Expressions override typeCheck() and performs optimizations, as opposed to doing it in the compress() stage. This is due to that the design of those Expressions often are tied to that certain simplifications are done at the typeCheck() stage of the compilation process or that it in some other way is related to what the typeCheck() do. Also, the earlier the AST can be simplified, the better the chances are for subsequent optimizations.
It is important that the super class's typeCheck() is called before doing any custom type checking, since the call can change the children(notably, the childrens' static types). For example, if the Expression, MyExpression in the example, does not match the required type, typeCheck returns the Expression wrapped in for example ItemVerifier, CardinalityVerifier, or both.
typeCheck() may be called many times. typeCheck() must either raise an error if this Expression is an invalid expression. Thus, it is guaranteed that an Expression is valid after typeCheck() is called.
Parameters
context supplies information, such as namespace bindings and available function signatures, that can be needed at compilation time. context is guaranteed by the caller to never null.
reqType the static type that this Expression must match when evaluated. reqType is guaranteed by the caller to never null.
Returns
an Expression that can be this Expression, or another expression, which somehow is necessary for making this Expression conforming to reqType
Reimplemented from QPatternist::Expression.
Reimplemented in QPatternist::SubsequenceFN, QPatternist::ReverseFN, QPatternist::DistinctValuesFN, QPatternist::StaticBaseURIFN, QPatternist::DefaultCollationFN, QPatternist::SumFN, QPatternist::DocFN, QPatternist::NumberFN, QPatternist::AvgFN, QPatternist::DocumentFN, QPatternist::IndexOfFN, QPatternist::AddingAggregate, QPatternist::StringFN, QPatternist::ComparingAggregator< oper, result >, QPatternist::BooleanFN, QPatternist::CountFN, QPatternist::StaticBaseUriContainer, QPatternist::IdFN, QPatternist::StaticNamespacesContainer, QPatternist::DeepEqualFN, QPatternist::FunctionAvailableFN, QPatternist::TypeAvailableFN, QPatternist::CurrentFN, and QPatternist::ResolveURIFN.
Definition at line 71 of file qfunctioncall.cpp.
Referenced by QPatternist::ResolveURIFN::typeCheck(), QPatternist::CurrentFN::typeCheck(), QPatternist::DeepEqualFN::typeCheck(), QPatternist::StaticNamespacesContainer::typeCheck(), QPatternist::StaticBaseUriContainer::typeCheck(), QPatternist::CountFN::typeCheck(), QPatternist::StringFN::typeCheck(), QPatternist::AddingAggregate::typeCheck(), QPatternist::IndexOfFN::typeCheck(), QPatternist::AvgFN::typeCheck(), QPatternist::NumberFN::typeCheck(), QPatternist::DocFN::typeCheck(), QPatternist::StaticBaseURIFN::typeCheck(), QPatternist::DistinctValuesFN::typeCheck(), QPatternist::ReverseFN::typeCheck(), and QPatternist::SubsequenceFN::typeCheck().
 {
     /* We don't cache properties() at some stages because it can be invalidated
      * by the typeCheck(). */
     const FunctionSignature::Arity maxArgs = signature()->maximumArguments();
     /* We do this before the typeCheck() such that the appropriate conversions
      * are applied to the ContextItem. */
     if(m_operands.count() < maxArgs &&
        has(UseContextItem))
     {
         m_operands.append(Expression::Ptr(new ContextItem()));
         context->wrapExpressionWith(this, m_operands.last());
     }
     const Expression::Ptr me(UnlimitedContainer::typeCheck(context, reqType));
     if(me != this)
         return me;
     const Properties props(properties());
     if(props.testFlag(RewriteToEmptyOnEmpty) &&
        *CommonSequenceTypes::Empty == *m_operands.first()->staticType()->itemType())
     {
         return EmptySequence::create(this, context);
     }
     if(props.testFlag(LastOperandIsCollation) &&
        m_operands.count() == maxArgs)
     {
         m_operands.last() = Expression::Ptr(new CollationChecker(m_operands.last()));
         context->wrapExpressionWith(this, m_operands.last());
     }
     return me;
 }
Properties
m_signature
FunctionSignature::Ptr QPatternist::FunctionCall::m_signature private
Definition at line 94 of file qfunctioncall_p.h.
Referenced by id(), properties(), setSignature(), signature(), and staticType().
The documentation for this class was generated from the following files:
/src/xmlpatterns/functions/qfunctioncall_p.h
/src/xmlpatterns/functions/qfunctioncall.cpp