Qt 4.8: QWheelEvent Class Reference
QWheelEvent Class Reference
The QWheelEvent class contains parameters that describe a wheel event.
#include <qevent.h>
Public Functions
Qt::MouseButtons buttons () const
Returns the mouse state when the event occurred.
int delta () const
Returns the distance that the wheel is rotated, in eighths of a degree.
const QPoint & globalPos () const
Returns the global position of the mouse pointer at the time of the event.
int globalX () const
Returns the global x position of the mouse cursor at the time of the event.
int globalY () const
Returns the global y position of the mouse cursor at the time of the event.
Qt::Orientation orientation () const
Returns the wheel's orientation.
const QPoint & pos () const
Returns the position of the mouse cursor relative to the widget that received the event.
QWheelEvent (const QPoint &pos, int delta, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Qt::Orientation orient=Qt::Vertical)
Constructs a wheel event object.
QWheelEvent (const QPoint &pos, const QPoint &globalPos, int delta, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Qt::Orientation orient=Qt::Vertical)
Constructs a wheel event object.
int x () const
Returns the x position of the mouse cursor, relative to the widget that received the event.
int y () const
Returns the y position of the mouse cursor, relative to the widget that received the event.
~QWheelEvent ()
Public Functions inherited from QInputEvent
Qt::KeyboardModifiers modifiers () const
Returns the keyboard modifier flags that existed immediately before the event occurred.
QInputEvent (Type type, Qt::KeyboardModifiers modifiers=Qt::NoModifier)
void setModifiers (Qt::KeyboardModifiers amodifiers)
Sets the keyboard modifiers flags for this event.
~QInputEvent ()
Public Functions inherited from QEvent
void accept ()
Sets the accept flag of the event object, the equivalent of calling setAccepted(true).
void ignore ()
Clears the accept flag parameter of the event object, the equivalent of calling setAccepted(false).
bool isAccepted () const
QEvent (Type type)
Contructs an event object of type type.
void setAccepted (bool accepted)
bool spontaneous () const
Returns true if the event originated outside the application (a system event); otherwise returns false.
Type type () const
Returns the event type.
virtual ~QEvent ()
Destroys the event.
Protected Variables
int d
QPoint g
Qt::MouseButtons mouseState
Qt::Orientation o
QPoint p
Protected Variables inherited from QInputEvent
Qt::KeyboardModifiers modState
Protected Variables inherited from QEvent
QEventPrivate * d
ushort t
Additional Inherited Members
Public Types inherited from QEvent
enum Type {
None = 0, Timer = 1, MouseButtonPress = 2, MouseButtonRelease = 3,
MouseButtonDblClick = 4, MouseMove = 5, KeyPress = 6, KeyRelease = 7,
FocusIn = 8, FocusOut = 9, Enter = 10, Leave = 11,
Paint = 12, Move = 13, Resize = 14, Create = 15,
Destroy = 16, Show = 17, Hide = 18, Close = 19,
Quit = 20, ParentChange = 21, ParentAboutToChange = 131, ThreadChange = 22,
WindowActivate = 24, WindowDeactivate = 25, ShowToParent = 26, HideToParent = 27,
Wheel = 31, WindowTitleChange = 33, WindowIconChange = 34, ApplicationWindowIconChange = 35,
ApplicationFontChange = 36, ApplicationLayoutDirectionChange = 37, ApplicationPaletteChange = 38, PaletteChange = 39,
Clipboard = 40, Speech = 42, MetaCall = 43, SockAct = 50,
WinEventAct = 132, DeferredDelete = 52, DragEnter = 60, DragMove = 61,
DragLeave = 62, Drop = 63, DragResponse = 64, ChildAdded = 68,
ChildPolished = 69, ChildRemoved = 71, ShowWindowRequest = 73, PolishRequest = 74,
Polish = 75, LayoutRequest = 76, UpdateRequest = 77, UpdateLater = 78,
EmbeddingControl = 79, ActivateControl = 80, DeactivateControl = 81, ContextMenu = 82,
InputMethod = 83, AccessibilityPrepare = 86, TabletMove = 87, LocaleChange = 88,
LanguageChange = 89, LayoutDirectionChange = 90, Style = 91, TabletPress = 92,
TabletRelease = 93, OkRequest = 94, HelpRequest = 95, IconDrag = 96,
FontChange = 97, EnabledChange = 98, ActivationChange = 99, StyleChange = 100,
IconTextChange = 101, ModifiedChange = 102, MouseTrackingChange = 109, WindowBlocked = 103,
WindowUnblocked = 104, WindowStateChange = 105, ToolTip = 110, WhatsThis = 111,
StatusTip = 112, ActionChanged = 113, ActionAdded = 114, ActionRemoved = 115,
FileOpen = 116, Shortcut = 117, ShortcutOverride = 51, WhatsThisClicked = 118,
ToolBarChange = 120, ApplicationActivate = 121, ApplicationActivated = ApplicationActivate, ApplicationDeactivate = 122,
ApplicationDeactivated = ApplicationDeactivate, QueryWhatsThis = 123, EnterWhatsThisMode = 124, LeaveWhatsThisMode = 125,
ZOrderChange = 126, HoverEnter = 127, HoverLeave = 128, HoverMove = 129,
AccessibilityHelp = 119, AccessibilityDescription = 130, AcceptDropsChange = 152, MenubarUpdated = 153,
ZeroTimerEvent = 154, GraphicsSceneMouseMove = 155, GraphicsSceneMousePress = 156, GraphicsSceneMouseRelease = 157,
GraphicsSceneMouseDoubleClick = 158, GraphicsSceneContextMenu = 159, GraphicsSceneHoverEnter = 160, GraphicsSceneHoverMove = 161,
GraphicsSceneHoverLeave = 162, GraphicsSceneHelp = 163, GraphicsSceneDragEnter = 164, GraphicsSceneDragMove = 165,
GraphicsSceneDragLeave = 166, GraphicsSceneDrop = 167, GraphicsSceneWheel = 168, KeyboardLayoutChange = 169,
DynamicPropertyChange = 170, TabletEnterProximity = 171, TabletLeaveProximity = 172, NonClientAreaMouseMove = 173,
NonClientAreaMouseButtonPress = 174, NonClientAreaMouseButtonRelease = 175, NonClientAreaMouseButtonDblClick = 176, MacSizeChange = 177,
ContentsRectChange = 178, MacGLWindowChange = 179, FutureCallOut = 180, GraphicsSceneResize = 181,
GraphicsSceneMove = 182, CursorChange = 183, ToolTipChange = 184, NetworkReplyUpdated = 185,
GrabMouse = 186, UngrabMouse = 187, GrabKeyboard = 188, UngrabKeyboard = 189,
MacGLClearDrawable = 191, StateMachineSignal = 192, StateMachineWrapped = 193, TouchBegin = 194,
TouchUpdate = 195, TouchEnd = 196, NativeGesture = 197, RequestSoftwareInputPanel = 199,
CloseSoftwareInputPanel = 200, UpdateSoftKeys = 201, WinIdChange = 203, Gesture = 198,
GestureOverride = 202, PlatformPanel = 212, User = 1000, MaxUser = 65535
}
This enum type defines the valid event types in Qt.
Static Public Functions inherited from QEvent
static int registerEventType (int hint=-1)
Registers and returns a custom event type.
Detailed Description
The QWheelEvent class contains parameters that describe a wheel event.
Wheel events are sent to the widget under the mouse cursor, but if that widget does not handle the event they are sent to the focus widget. The rotation distance is provided by delta(). The functions pos() and globalPos() return the mouse cursor's location at the time of the event.
A wheel event contains a special accept flag that indicates whether the receiver wants the event. You should call ignore() if you do not handle the wheel event; this ensures that it will be sent to the parent widget.
The QWidget::setEnabled() function can be used to enable or disable mouse and keyboard events for a widget.
The event handler QWidget::wheelEvent() receives wheel events.
See also
QMouseEvent QWidget::grabMouse()
Definition at line 139 of file qevent.h.
Constructors and Destructors
QWheelEvent() [1/2]
QWheelEvent::QWheelEvent (const QPoint & pos, int delta, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Qt::Orientation orient = Qt::Vertical)
Constructs a wheel event object.
The position, pos, is the location of the mouse cursor within the widget. The globalPos() is initialized to QCursor::pos() which is usually, but not always, correct. Use the other constructor if you need to specify the global position explicitly.
The buttons describe the state of the mouse buttons at the time of the event, delta contains the rotation distance, modifiers holds the keyboard modifier flags at the time of the event, and orient holds the wheel's orientation.
See also
pos() delta() state()
Definition at line 607 of file qevent.cpp.
Referenced by QWheelEvent(), and ~QWheelEvent().
     : QInputEvent(Wheel, modifiers), p(pos), d(delta), mouseState(buttons), o(orient)
 {
     g = QCursor::pos();
 }
QWheelEvent() [2/2]
QWheelEvent::QWheelEvent (const QPoint & pos, const QPoint & globalPos, int delta, Qt::MouseButtons buttons, Qt::KeyboardModifiers modifiers, Qt::Orientation orient = Qt::Vertical)
Constructs a wheel event object.
The pos provides the location of the mouse cursor within the widget. The position in global coordinates is specified by globalPos. delta contains the rotation distance, modifiers holds the keyboard modifier flags at the time of the event, and orient holds the wheel's orientation.
See also
pos() globalPos() delta() state()
Definition at line 646 of file qevent.cpp.
     : QInputEvent(Wheel, modifiers), p(pos), g(globalPos), d(delta), mouseState(buttons), o(orient)
 {}
~QWheelEvent()
QWheelEvent::~QWheelEvent ()
Warning
This function is not part of the public interface.
Definition at line 618 of file qevent.cpp.
 {
 }
Functions
buttons()
Qt::MouseButtons QWheelEvent::buttons () const inline
Returns the mouse state when the event occurred.
Definition at line 158 of file qevent.h.
Referenced by QApplication::notify(), and QGraphicsView::wheelEvent().
 { return mouseState; }
delta()
int QWheelEvent::delta () const inline
Returns the distance that the wheel is rotated, in eighths of a degree.
A positive value indicates that the wheel was rotated forwards away from the user; a negative value indicates that the wheel was rotated backwards toward the user.
Most mouse types work in steps of 15 degrees, in which case the delta value is a multiple of 120; i.e., 120 units * 1/8 = 15 degrees.
However, some mice have finer-resolution wheels and send delta values that are less than 120 units (less than 15 degrees). To support this possibility, you can either cumulatively add the delta values from events until the value of 120 is reached, then scroll the widget, or you can partially scroll the widget in response to each wheel event.
Example:
void MyWidget::wheelEvent(QWheelEvent *event)
{
    int numDegrees = event->delta() / 8;
    int numSteps = numDegrees / 15;
    if (event->orientation() == Qt::Horizontal) {
        scrollHorizontally(numSteps);
    } else {
        scrollVertically(numSteps);
    }
    event->accept();
}
Definition at line 150 of file qevent.h.
Referenced by QScrollBar::event(), QApplication::notify(), QTriangulator< T >::ComplexToSimple::Event::operator<(), QWheelEvent(), QmlJSDebugger::ZoomTool::wheelEvent(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), QAbstractSlider::wheelEvent(), QMenu::wheelEvent(), QComboBox::wheelEvent(), QGraphicsView::wheelEvent(), QTextEdit::wheelEvent(), and ~QWheelEvent().
 { return d; }
globalPos()
const QPoint & QWheelEvent::globalPos () const inline
Returns the global position of the mouse pointer at the time of the event.
This is important on asynchronous window systems such as X11; whenever you move your widgets around in response to mouse events, globalPos() can differ a lot from the current cursor position returned by QCursor::pos().
See also
globalX() globalY()
Definition at line 152 of file qevent.h.
Referenced by QApplication::notify(), and QGraphicsView::wheelEvent().
 { return g; }
globalX()
int QWheelEvent::globalX () const inline
Returns the global x position of the mouse cursor at the time of the event.
See also
globalY() globalPos()
Definition at line 155 of file qevent.h.
 { return g.x(); }
globalY()
int QWheelEvent::globalY () const inline
Returns the global y position of the mouse cursor at the time of the event.
See also
globalX() globalPos()
Definition at line 156 of file qevent.h.
 { return g.y(); }
orientation()
Qt::Orientation QWheelEvent::orientation () const inline
Returns the wheel's orientation.
Definition at line 159 of file qevent.h.
Referenced by QScrollBar::event(), QApplication::notify(), QmlJSDebugger::ZoomTool::wheelEvent(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), QAbstractSlider::wheelEvent(), and QGraphicsView::wheelEvent().
 { return o; }
pos()
const QPoint & QWheelEvent::pos () const inline
Returns the position of the mouse cursor relative to the widget that received the event.
If you move your widgets around in response to mouse events, use globalPos() instead of this function.
See also
x() y() globalPos()
Definition at line 151 of file qevent.h.
Referenced by QApplication::notify(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), QMenu::wheelEvent(), and QGraphicsView::wheelEvent().
 { return p; }
x()
int QWheelEvent::x () const inline
Returns the x position of the mouse cursor, relative to the widget that received the event.
See also
y() pos()
Definition at line 153 of file qevent.h.
 { return p.x(); }
y()
int QWheelEvent::y () const inline
Returns the y position of the mouse cursor, relative to the widget that received the event.
See also
x() pos()
Definition at line 154 of file qevent.h.
 { return p.y(); }
Properties
d
int QWheelEvent::d protected
Definition at line 172 of file qevent.h.
Referenced by QWheelEvent(), and ~QWheelEvent().
g
QPoint QWheelEvent::g protected
Definition at line 171 of file qevent.h.
Referenced by QWheelEvent(), and ~QWheelEvent().
mouseState
Qt::MouseButtons QWheelEvent::mouseState protected
Definition at line 173 of file qevent.h.
Referenced by QWheelEvent(), and ~QWheelEvent().
o
Qt::Orientation QWheelEvent::o protected
Definition at line 174 of file qevent.h.
Referenced by QWheelEvent(), and ~QWheelEvent().
p
QPoint QWheelEvent::p protected
Definition at line 170 of file qevent.h.
Referenced by QWheelEvent(), and ~QWheelEvent().
The documentation for this class was generated from the following files:
/src/gui/kernel/qevent.h
/src/gui/kernel/qevent.cpp