Qt 4.8: QBig5Codec Class Reference
QBig5Codec Class Reference
#include <qbig5codec.h>
Public Functions
QList< QByteArray > aliases () const
Subclasses can return a number of aliases for the codec in question.
QByteArray convertFromUnicode (const QChar *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
QString convertToUnicode (const char *, int, ConverterState *) const
QTextCodec subclasses must reimplement this function.
int mibEnum () const
Subclasses of QTextCodec must reimplement this function.
QByteArray name () const
QTextCodec subclasses must reimplement this function.
Public Functions inherited from QTextCodec
bool canEncode (QChar) const
Returns true if the Unicode character ch can be fully encoded with this codec; otherwise returns false.
bool canEncode (const QString &) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.s contains the string being tested for encode-ability.
QByteArray fromUnicode (const QString &uc) const
Converts str from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QByteArray fromUnicode (const QChar *in, int length, ConverterState *state=0) const
Converts the first number of characters from the input array from Unicode to the encoding of this codec, and returns the result in a QByteArray.
QTextDecoder * makeDecoder () const
Creates a QTextDecoder which stores enough state to decode chunks of char * data to create chunks of Unicode data.
QTextDecoder * makeDecoder (ConversionFlags flags) const
QTextEncoder * makeEncoder () const
Creates a QTextEncoder which stores enough state to encode chunks of Unicode data as char * data.
QTextEncoder * makeEncoder (ConversionFlags flags) const
QString toUnicode (const QByteArray &) const
Converts a from the encoding of this codec to Unicode, and returns the result in a QString.
QString toUnicode (const char *chars) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.chars contains the source characters.
QString toUnicode (const char *in, int length, ConverterState *state=0) const
Converts the first size characters from the input from the encoding of this codec to Unicode, and returns the result in a QString.
Static Public Functions
static QList< QByteArray > _aliases ()
static int _mibEnum ()
static QByteArray _name ()
Static Public Functions inherited from QTextCodec
static QList< QByteArray > availableCodecs ()
Returns the list of all available codecs, by name.
static QList< int > availableMibs ()
Returns the list of MIBs for all available codecs.
static QTextCodec * codecForCStrings ()
Returns the codec used by QString to convert to and from const char * and QByteArrays.
static QTextCodec * codecForHtml (const QByteArray &ba)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForHtml (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet of HTML in the given byte array, ba, by checking the BOM (Byte Order Mark) and the content-type meta header and returns a QTextCodec instance that is capable of decoding the html to unicode.
static QTextCodec * codecForLocale ()
Returns a pointer to the codec most suitable for this locale.
static QTextCodec * codecForMib (int mib)
Returns the QTextCodec which matches the MIBenum mib.
static QTextCodec * codecForName (const QByteArray &name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForName (const char *name)
Searches all installed QTextCodec objects and returns the one which best matches name; the match is case-insensitive.
static QTextCodec * codecForTr ()
Returns the codec used by QObject::tr() on its argument.
static QTextCodec * codecForUtfText (const QByteArray &ba)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static QTextCodec * codecForUtfText (const QByteArray &ba, QTextCodec *defaultCodec)
Tries to detect the encoding of the provided snippet ba by using the BOM (Byte Order Mark) and returns a QTextCodec instance that is capable of decoding the text to unicode.
static void setCodecForCStrings (QTextCodec *c)
static void setCodecForLocale (QTextCodec *c)
Set the codec to c; this will be returned by codecForLocale().
static void setCodecForTr (QTextCodec *c)
Additional Inherited Members
Public Types inherited from QTextCodec
enum ConversionFlag { DefaultConversion, ConvertInvalidToNull = 0x80000000, IgnoreHeader = 0x1, FreeFunction = 0x2 }
Protected Functions inherited from QTextCodec
QTextCodec ()
Constructs a QTextCodec, and gives it the highest precedence.
virtual ~QTextCodec ()
Destroys the QTextCodec.
Detailed Description
Definition at line 56 of file qbig5codec.h.
Functions
_aliases()
QList< QByteArray > QBig5Codec::_aliases () static
Definition at line 1813 of file qbig5codec.cpp.
Referenced by TWTextCodecs::aliases(), aliases(), QBig5hkscsCodec::aliases(), QFontBig5Codec::aliases(), QFontBig5hkscsCodec::aliases(), and TWTextCodecs::createForName().
 {
     QList<QByteArray> aliases;
     aliases += "Big5-ETen";
     aliases += "CP950";
     return aliases;
 }
_mibEnum()
int QBig5Codec::_mibEnum () static
Definition at line 60 of file qbig5codec.cpp.
Referenced by QBig5hkscsCodec::_aliases(), QFontBig5Codec::_aliases(), QFontBig5hkscsCodec::_aliases(), TWTextCodecs::createForMib(), mibEnum(), QBig5hkscsCodec::mibEnum(), QFontBig5Codec::mibEnum(), QFontBig5hkscsCodec::mibEnum(), and TWTextCodecs::mibEnums().
 {
     return 2026;
 }
_name()
QByteArray QBig5Codec::_name () static
Definition at line 65 of file qbig5codec.cpp.
Referenced by TWTextCodecs::createForName(), name(), QBig5hkscsCodec::name(), QFontBig5Codec::name(), QFontBig5hkscsCodec::name(), and TWTextCodecs::names().
 {
     return "Big5";
 }
aliases()
QList<QByteArray> QBig5Codec::aliases () const inline virtual
Subclasses can return a number of aliases for the codec in question.
Standard aliases for codecs can be found in the IANA character-sets encoding file.
Reimplemented from QTextCodec.
Definition at line 63 of file qbig5codec.h.
Referenced by _aliases().
 { return _aliases(); }
convertFromUnicode()
QByteArray QBig5Codec::convertFromUnicode (const QChar * input, int number, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first number of characters from the input array from Unicode to the encoding of the subclass, and returns the result in a QByteArray.
state can be 0 in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 1776 of file qbig5codec.cpp.
Referenced by mibEnum(), QBig5hkscsCodec::mibEnum(), QFontBig5Codec::mibEnum(), and QFontBig5hkscsCodec::mibEnum().
 {
     char replacement = '?';
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = 0;
     }
     int invalid = 0;
     int rlen = 2*len + 1;
     QByteArray rstr;
     rstr.resize(rlen);
     uchar* cursor = (uchar*)rstr.data();
     for (int i=0; i<len; i++) {
         ushort ch = uc[i].unicode();
         uchar c[2];
         if (ch < 0x80) {
             // ASCII
             *cursor++ = ch;
         } else if (qt_UnicodeToBig5(ch, c) == 2 && c[0] >= 0xa1 && c[0] <= 0xf9) {
             *cursor++ = c[0];
             *cursor++ = c[1];
         } else {
             *cursor++ = replacement;
             ++invalid;
         }
     }
     rstr.resize(cursor - (uchar*)rstr.constData());
     if (state) {
         state->invalidChars += invalid;
     }
     return rstr;
 }
convertToUnicode()
QString QBig5Codec::convertToUnicode (const char * chars, int len, ConverterState * state) const virtual
QTextCodec subclasses must reimplement this function.
Converts the first len characters of chars from the encoding of the subclass to Unicode, and returns the result in a QString.
state can be 0, in which case the conversion is stateless and default conversion rules should be used. If state is not 0, the codec should save the state after the conversion in state, and adjust the remainingChars and invalidChars members of the struct.
Implements QTextCodec.
Definition at line 1713 of file qbig5codec.cpp.
Referenced by mibEnum(), QBig5hkscsCodec::mibEnum(), QFontBig5Codec::mibEnum(), and QFontBig5hkscsCodec::mibEnum().
 {
     QChar replacement = QChar::ReplacementCharacter;
     uchar buf[2] = {0};
     int nbuf = 0;
     if (state) {
         if (state->flags & ConvertInvalidToNull)
             replacement = QChar::Null;
         nbuf = state->remainingChars;
         buf[0] = state->state_data[0];
         buf[1] = state->state_data[1];
     }
     int invalid = 0;
     //qDebug("QBig5Codec::toUnicode(const char* chars = \"%s\", int len = %d)", chars, len);
     QString result;
     for (int i=0; i<len; i++) {
         uchar ch = chars[i];
         switch (nbuf) {
         case 0:
             if (IsLatin(ch)) {
                 // ASCII
                 result += QLatin1Char(ch);
             } else if (IsFirstByte(ch)) {
                 // Big5-ETen
                 buf[0] = ch;
                 nbuf = 1;
             } else {
                 // Invalid
                 result += replacement;
                 ++invalid;
             }
             break;
         case 1:
             if (IsSecondByte(ch)) {
                 // Big5-ETen
                 uint u;
                 buf[1] = ch;
                 if (qt_Big5ToUnicode(buf, &u) == 2)
                     result += QValidChar(u);
                 else {
                     // Error
                     result += replacement;
                     ++invalid;
                 }
             } else {
                 // Error
                 result += replacement;
                 ++invalid;
             }
             nbuf = 0;
             break;
         }
     }
     if (state) {
         state->remainingChars = nbuf;
         state->state_data[0] = buf[0];
         state->state_data[1] = buf[1];
         state->invalidChars += invalid;
     }
     return result;
 }
mibEnum()
int QBig5Codec::mibEnum () const inline virtual
Subclasses of QTextCodec must reimplement this function.
It returns the MIBenum (see IANA character-sets encoding file for more information). It is important that each QTextCodec subclass returns the correct unique value for this function.
Implements QTextCodec.
Definition at line 64 of file qbig5codec.h.
 { return _mibEnum(); }
name()
QByteArray QBig5Codec::name () const inline virtual
QTextCodec subclasses must reimplement this function.
It returns the name of the encoding supported by the subclass.
If the codec is registered as a character set in the IANA character-sets encoding file this method should return the preferred mime name for the codec if defined, otherwise its name.
Implements QTextCodec.
Definition at line 62 of file qbig5codec.h.
 { return _name(); }
The documentation for this class was generated from the following files:
/src/plugins/codecs/tw/qbig5codec.h
/src/plugins/codecs/tw/qbig5codec.cpp