Qt 4.8: QIconTheme Class Reference
QIconTheme Class Reference
#include <qiconloader_p.h>
Public Functions
QString contentDir ()
bool isValid ()
QList< QIconDirInfo > keyList ()
QStringList parents ()
QIconTheme (const QString &name)
QIconTheme ()
Properties
QString m_contentDir
QList< QIconDirInfo > m_keyList
QStringList m_parents
bool m_valid
Detailed Description
Definition at line 139 of file qiconloader_p.h.
Constructors and Destructors
QIconTheme() [1/2]
QIconTheme::QIconTheme (const QString & name)
Definition at line 160 of file qiconloader.cpp.
         : m_valid(false)
 {
     QFile themeIndex;
     QList <QIconDirInfo> keyList;
     QStringList iconDirs = QIcon::themeSearchPaths();
     for ( int i = 0 ; i < iconDirs.size() ; ++i) {
         QDir iconDir(iconDirs[i]);
         QString themeDir = iconDir.path() + QLatin1Char('/') + themeName;
         themeIndex.setFileName(themeDir + QLatin1String("/index.theme"));
         if (themeIndex.exists()) {
             m_contentDir = themeDir;
             m_valid = true;
             break;
         }
     }
 #ifndef QT_NO_SETTINGS
     if (themeIndex.exists()) {
         const QSettings indexReader(themeIndex.fileName(), QSettings::IniFormat);
         QStringListIterator keyIterator(indexReader.allKeys());
         while (keyIterator.hasNext()) {
             const QString key = keyIterator.next();
             if (key.endsWith(QLatin1String("/Size"))) {
                 // Note the QSettings ini-format does not accept
                 // slashes in key names, hence we have to cheat
                 if (int size = indexReader.value(key).toInt()) {
                     QString directoryKey = key.left(key.size() - 5);
                     QIconDirInfo dirInfo(directoryKey);
                     dirInfo.size = size;
                     QString type = indexReader.value(directoryKey +
                                                      QLatin1String("/Type")
                                                      ).toString();
                     if (type == QLatin1String("Fixed"))
                         dirInfo.type = QIconDirInfo::Fixed;
                     else if (type == QLatin1String("Scalable"))
                         dirInfo.type = QIconDirInfo::Scalable;
                     else
                         dirInfo.type = QIconDirInfo::Threshold;
                     dirInfo.threshold = indexReader.value(directoryKey +
                                                         QLatin1String("/Threshold"),
                                                         2).toInt();
                     dirInfo.minSize = indexReader.value(directoryKey +
                                                          QLatin1String("/MinSize"),
                                                          size).toInt();
                     dirInfo.maxSize = indexReader.value(directoryKey +
                                                         QLatin1String("/MaxSize"),
                                                         size).toInt();
                     m_keyList.append(dirInfo);
                 }
             }
         }
         // Parent themes provide fallbacks for missing icons
         m_parents = indexReader.value(
                 QLatin1String("Icon Theme/Inherits")).toStringList();
         // Ensure a default platform fallback for all themes
         if (m_parents.isEmpty())
             m_parents.append(fallbackTheme());
         // Ensure that all themes fall back to hicolor
         if (!m_parents.contains(QLatin1String("hicolor")))
             m_parents.append(QLatin1String("hicolor"));
     }
 #endif //QT_NO_SETTINGS
 }
QIconTheme() [2/2]
QIconTheme::QIconTheme () inline
Definition at line 143 of file qiconloader_p.h.
Referenced by QIconLoader::findIconHelper().
 : m_valid(false) {}
Functions
contentDir()
QString QIconTheme::contentDir () inline
Definition at line 146 of file qiconloader_p.h.
Referenced by QIconLoader::findIconHelper().
 { return m_contentDir; }
isValid()
bool QIconTheme::isValid () inline
Definition at line 147 of file qiconloader_p.h.
Referenced by QIconLoader::findIconHelper().
 { return m_valid; }
keyList()
QList<QIconDirInfo> QIconTheme::keyList () inline
Definition at line 145 of file qiconloader_p.h.
Referenced by QIconLoader::findIconHelper(), and QIconTheme().
 { return m_keyList; }
parents()
QStringList QIconTheme::parents () inline
Definition at line 144 of file qiconloader_p.h.
Referenced by QIconLoader::findIconHelper().
 { return m_parents; }
Properties
m_contentDir
QString QIconTheme::m_contentDir private
Definition at line 150 of file qiconloader_p.h.
Referenced by QIconTheme().
m_keyList
QList<QIconDirInfo> QIconTheme::m_keyList private
Definition at line 151 of file qiconloader_p.h.
Referenced by QIconTheme().
m_parents
QStringList QIconTheme::m_parents private
Definition at line 152 of file qiconloader_p.h.
Referenced by QIconTheme().
m_valid
bool QIconTheme::m_valid private
Definition at line 153 of file qiconloader_p.h.
Referenced by QIconTheme().
The documentation for this class was generated from the following files:
/src/gui/image/qiconloader_p.h
/src/gui/image/qiconloader.cpp