Qt 4.8: QAccessibleWidget Class Reference
QAccessibleWidget Class Reference
The QAccessibleWidget class implements the QAccessibleInterface for QWidgets.
#include <qaccessiblewidget.h>
Public Functions
QString actionText (int action, Text t, int child) const
Reimplemented Function
int childAt (int x, int y) const
Reimplemented Function
int childCount () const
Reimplemented Function
bool doAction (int action, int child, const QVariantList &params)
Reimplemented Function
int indexOfChild (const QAccessibleInterface *child) const
Reimplemented Function
int navigate (RelationFlag rel, int entry, QAccessibleInterface **target) const
Reimplemented Function
QAccessibleWidget (QWidget *o, Role r=Client, const QString &name=QString())
Creates a QAccessibleWidget object for widget w.
QRect rect (int child) const
Reimplemented Function
Relation relationTo (int child, const QAccessibleInterface *other, int otherChild) const
Reimplemented Function
Role role (int child) const
Reimplemented Function
State state (int child) const
Reimplemented Function
QString text (Text t, int child) const
Reimplemented Function
int userActionCount (int child) const
Reimplemented Function
Public Functions inherited from QAccessibleObject
bool isValid () const
Reimplemented Function
QObject * object () const
Reimplemented Function
QAccessibleObject (QObject *object)
Creates a QAccessibleObject for object.
void setText (Text t, int child, const QString &text)
Reimplemented Function
Public Functions inherited from QAccessibleInterface
QAccessibleActionInterface * actionInterface ()
QColor backgroundColor ()
QAccessibleEditableTextInterface * editableTextInterface ()
QColor foregroundColor ()
QAccessibleImageInterface * imageInterface ()
QVariant invokeMethod (Method method, int child=0, const QVariantList &params=QVariantList())
Invokes a method on child with the given parameters params and returns the result of the operation as QVariant.
QSet< Method > supportedMethods ()
Returns a QSet of QAccessible::Method that are supported by this accessible interface.
QAccessibleTable2Interface * table2Interface ()
QAccessibleTableInterface * tableInterface ()
QAccessibleTextInterface * textInterface ()
QAccessibleValueInterface * valueInterface ()
virtual ~QAccessibleInterface ()
Destroys the object.
Protected Functions
void addControllingSignal (const QString &signal)
Registers signal as a controlling signal.
QObject * parentObject () const
Returns the associated widget's parent object, which is either the parent widget, or qApp for top-level widgets.
void setAccelerator (const QString &accel)
Sets the accelerator of this interface implementation to accel.
void setDescription (const QString &desc)
Sets the description of this interface implementation to desc.
void setHelp (const QString &help)
Sets the help of this interface implementation to help.
void setValue (const QString &value)
Sets the value of this interface implementation to value.
QWidget * widget () const
Returns the associated widget.
~QAccessibleWidget ()
Destroys this object.
Protected Functions inherited from QAccessibleObject
virtual ~QAccessibleObject ()
Destroys the QAccessibleObject.
Properties
QAccessibleWidgetPrivate * d
Friends
class QAccessibleWidgetEx
Additional Inherited Members
Public Types inherited from QAccessible
enum Action {
DefaultAction = 0, Press = -1, FirstStandardAction = Press, SetFocus = -2,
Increase = -3, Decrease = -4, Accept = -5, Cancel = -6,
Select = -7, ClearSelection = -8, RemoveSelection = -9, ExtendSelection = -10,
AddToSelection = -11, LastStandardAction = AddToSelection
}
This enum describes the possible types of action that can occur.
enum Event {
SoundPlayed = 0x0001, Alert = 0x0002, ForegroundChanged = 0x0003, MenuStart = 0x0004,
MenuEnd = 0x0005, PopupMenuStart = 0x0006, PopupMenuEnd = 0x0007, ContextHelpStart = 0x000C,
ContextHelpEnd = 0x000D, DragDropStart = 0x000E, DragDropEnd = 0x000F, DialogStart = 0x0010,
DialogEnd = 0x0011, ScrollingStart = 0x0012, ScrollingEnd = 0x0013, MenuCommand = 0x0018,
ActionChanged = 0x0101, ActiveDescendantChanged = 0x0102, AttributeChanged = 0x0103, DocumentContentChanged = 0x0104,
DocumentLoadComplete = 0x0105, DocumentLoadStopped = 0x0106, DocumentReload = 0x0107, HyperlinkEndIndexChanged = 0x0108,
HyperlinkNumberOfAnchorsChanged = 0x0109, HyperlinkSelectedLinkChanged = 0x010A, HypertextLinkActivated = 0x010B, HypertextLinkSelected = 0x010C,
HyperlinkStartIndexChanged = 0x010D, HypertextChanged = 0x010E, HypertextNLinksChanged = 0x010F, ObjectAttributeChanged = 0x0110,
PageChanged = 0x0111, SectionChanged = 0x0112, TableCaptionChanged = 0x0113, TableColumnDescriptionChanged = 0x0114,
TableColumnHeaderChanged = 0x0115, TableModelChanged = 0x0116, TableRowDescriptionChanged = 0x0117, TableRowHeaderChanged = 0x0118,
TableSummaryChanged = 0x0119, TextAttributeChanged = 0x011A, TextCaretMoved = 0x011B, TextColumnChanged = 0x011D,
TextInserted = 0x011E, TextRemoved = 0x011F, TextUpdated = 0x0120, TextSelectionChanged = 0x0121,
VisibleDataChanged = 0x0122, ObjectCreated = 0x8000, ObjectDestroyed = 0x8001, ObjectShow = 0x8002,
ObjectHide = 0x8003, ObjectReorder = 0x8004, Focus = 0x8005, Selection = 0x8006,
SelectionAdd = 0x8007, SelectionRemove = 0x8008, SelectionWithin = 0x8009, StateChanged = 0x800A,
LocationChanged = 0x800B, NameChanged = 0x800C, DescriptionChanged = 0x800D, ValueChanged = 0x800E,
ParentChanged = 0x800F, HelpChanged = 0x80A0, DefaultActionChanged = 0x80B0, AcceleratorChanged = 0x80C0
}
This enum type defines accessible event types.
typedef QAccessibleInterface *(* InterfaceFactory) (const QString &key, QObject *)
This is a typedef for a pointer to a function with the following signature:
enum Method {
ListSupportedMethods = 0, SetCursorPosition = 1, GetCursorPosition = 2, ForegroundColor = 3,
BackgroundColor = 4
}
This enum describes the possible types of methods that can be invoked on an accessible object.
enum RelationFlag {
Unrelated = 0x00000000, Self = 0x00000001, Ancestor = 0x00000002, Child = 0x00000004,
Descendent = 0x00000008, Sibling = 0x00000010, HierarchyMask = 0x000000ff, Up = 0x00000100,
Down = 0x00000200, Left = 0x00000400, Right = 0x00000800, Covers = 0x00001000,
Covered = 0x00002000, GeometryMask = 0x0000ff00, FocusChild = 0x00010000, Label = 0x00020000,
Labelled = 0x00040000, Controller = 0x00080000, Controlled = 0x00100000, LogicalMask = 0x00ff0000
}
This enum type defines bit flags that can be combined to indicate the relationship between two accessible objects.
enum Role {
NoRole = 0x00000000, TitleBar = 0x00000001, MenuBar = 0x00000002, ScrollBar = 0x00000003,
Grip = 0x00000004, Sound = 0x00000005, Cursor = 0x00000006, Caret = 0x00000007,
AlertMessage = 0x00000008, Window = 0x00000009, Client = 0x0000000A, PopupMenu = 0x0000000B,
MenuItem = 0x0000000C, ToolTip = 0x0000000D, Application = 0x0000000E, Document = 0x0000000F,
Pane = 0x00000010, Chart = 0x00000011, Dialog = 0x00000012, Border = 0x00000013,
Grouping = 0x00000014, Separator = 0x00000015, ToolBar = 0x00000016, StatusBar = 0x00000017,
Table = 0x00000018, ColumnHeader = 0x00000019, RowHeader = 0x0000001A, Column = 0x0000001B,
Row = 0x0000001C, Cell = 0x0000001D, Link = 0x0000001E, HelpBalloon = 0x0000001F,
Assistant = 0x00000020, List = 0x00000021, ListItem = 0x00000022, Tree = 0x00000023,
TreeItem = 0x00000024, PageTab = 0x00000025, PropertyPage = 0x00000026, Indicator = 0x00000027,
Graphic = 0x00000028, StaticText = 0x00000029, EditableText = 0x0000002A, PushButton = 0x0000002B,
CheckBox = 0x0000002C, RadioButton = 0x0000002D, ComboBox = 0x0000002E, ProgressBar = 0x00000030,
Dial = 0x00000031, HotkeyField = 0x00000032, Slider = 0x00000033, SpinBox = 0x00000034,
Canvas = 0x00000035, Animation = 0x00000036, Equation = 0x00000037, ButtonDropDown = 0x00000038,
ButtonMenu = 0x00000039, ButtonDropGrid = 0x0000003A, Whitespace = 0x0000003B, PageTabList = 0x0000003C,
Clock = 0x0000003D, Splitter = 0x0000003E, LayeredPane = 0x0000003F, Terminal = 0x00000040,
Desktop = 0x00000041, UserRole = 0x0000ffff
}
This enum defines the role of an accessible object.
typedef void(* RootObjectHandler) (QObject *)
A function pointer type.
enum StateFlag {
Normal = 0x00000000, Unavailable = 0x00000001, Selected = 0x00000002, Focused = 0x00000004,
Pressed = 0x00000008, Checked = 0x00000010, Mixed = 0x00000020, ReadOnly = 0x00000040,
HotTracked = 0x00000080, DefaultButton = 0x00000100, Expanded = 0x00000200, Collapsed = 0x00000400,
Busy = 0x00000800, Marqueed = 0x00002000, Animated = 0x00004000, Invisible = 0x00008000,
Offscreen = 0x00010000, Sizeable = 0x00020000, Movable = 0x00040000, SelfVoicing = 0x00080000,
Focusable = 0x00100000, Selectable = 0x00200000, Linked = 0x00400000, Traversed = 0x00800000,
MultiSelectable = 0x01000000, ExtSelectable = 0x02000000, Protected = 0x20000000, HasPopup = 0x40000000,
Modal = 0x80000000, HasInvokeExtension = 0x10000000
}
This enum type defines bit flags that can be combined to indicate the state of an accessible object.
enum Text {
Name = 0, Description, Value, Help,
Accelerator, UserText = 0x0000ffff
}
This enum specifies string information that an accessible object returns.
typedef void(* UpdateHandler) (QObject *, int who, Event reason)
A function pointer type.
Static Public Functions inherited from QAccessible
static void cleanup ()
static void initialize ()
static void installFactory (InterfaceFactory)
Installs the InterfaceFactory factory.
static RootObjectHandler installRootObjectHandler (RootObjectHandler)
Installs the given handler as the function to be used by setRootObject(), and returns the previously installed handler.
static UpdateHandler installUpdateHandler (UpdateHandler)
Installs the given handler as the function to be used by updateAccessibility(), and returns the previously installed handler.
static bool isActive ()
Returns true if an accessibility implementation has been requested during the runtime of the application; otherwise returns false.
static QAccessibleInterface * queryAccessibleInterface (QObject *)
If a QAccessibleInterface implementation exists for the given object, this function returns a pointer to the implementation; otherwise it returns 0.
static void removeFactory (InterfaceFactory)
Removes factory from the list of installed InterfaceFactories.
static void setRootObject (QObject *)
Sets the root accessible object of this application to object.
static void updateAccessibility (QObject *, int who, Event reason)
Notifies accessibility clients about a change in object's accessibility information.
Detailed Description
The QAccessibleWidget class implements the QAccessibleInterface for QWidgets.
This class is convenient to use as a base class for custom implementations of QAccessibleInterfaces that provide information about widget objects.
The class provides functions to retrieve the parentObject() (the widget's parent widget), and the associated widget(). Controlling signals can be added with addControllingSignal(), and setters are provided for various aspects of the interface implementation, for example setValue(), setDescription(), setAccelerator(), and setHelp().
See also
QAccessible, QAccessibleObject
Definition at line 57 of file qaccessiblewidget.h.
Constructors and Destructors
QAccessibleWidget()
QAccessibleWidget::QAccessibleWidget (QWidget * w, Role role = Client, const QString & name = QString()) explicit
Creates a QAccessibleWidget object for widget w.
role and name are optional parameters that set the object's role and name properties.
Definition at line 199 of file qaccessiblewidget.cpp.
 : QAccessibleObject(w)
 {
     Q_ASSERT(widget());
     d = new QAccessibleWidgetPrivate();
     d->role = role;
     d->name = name;
     d->asking = 0;
 }
~QAccessibleWidget()
QAccessibleWidget::~QAccessibleWidget () protected
Destroys this object.
Definition at line 212 of file qaccessiblewidget.cpp.
 {
     delete d;
 }
Functions
actionText()
QString QAccessibleWidget::actionText (int action, Text t, int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleObject.
Definition at line 878 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::actionText().
 {
     if (action == DefaultAction)
         action = SetFocus;
     if (action > 0 && !child) {
         QAction *act = widget()->actions().value(action - 1);
         if (act) {
             switch (t) {
             case Name:
                 return act->text();
             case Description:
                 return act->toolTip();
 #ifndef QT_NO_SHORTCUT
             case Accelerator:
                 return act->shortcut().toString();
 #endif
             default:
                 break;
             }
         }
     }
     return QAccessibleObject::actionText(action, t, child);
 }
addControllingSignal()
void QAccessibleWidget::addControllingSignal (const QString & signal) protected
Registers signal as a controlling signal.
An object is a Controller to any other object connected to a controlling signal.
Definition at line 307 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::addControllingSignal().
 {
     QByteArray s = QMetaObject::normalizedSignature(signal.toAscii());
     if (object()->metaObject()->indexOfSignal(s) < 0)
         qWarning("Signal %s unknown in %s", s.constData(), object()->metaObject()->className());
     d->primarySignals << QLatin1String(s);
 }
childAt()
int QAccessibleWidget::childAt (int x, int y) const virtual
Reimplemented Function
Implements QAccessibleInterface.
Reimplemented in QAccessibleWidgetStack.
Definition at line 238 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::childAt().
 {
     QWidget *w = widget();
     if (!w->isVisible())
         return -1;
     QPoint gp = w->mapToGlobal(QPoint(0, 0));
     if (!QRect(gp.x(), gp.y(), w->width(), w->height()).contains(x, y))
         return -1;
     QWidgetList list = childWidgets(w);
     int ccount = childCount();
     // a complex child
     if (list.size() < ccount) {
         for (int i = 1; i <= ccount; ++i) {
             if (rect(i).contains(x, y))
                 return i;
         }
         return 0;
     }
     QPoint rp = w->mapFromGlobal(QPoint(x, y));
     for (int i = 0; i<list.size(); ++i) {
         QWidget *child = list.at(i);
         if (!child->isWindow() && !child->isHidden() && child->geometry().contains(rp)) {
             return i + 1;
         }
     }
     return 0;
 }
childCount()
int QAccessibleWidget::childCount () const virtual
Reimplemented Function
Implements QAccessibleInterface.
Reimplemented in QAccessibleWidgetStack.
Definition at line 795 of file qaccessiblewidget.cpp.
Referenced by childAt(), QAccessibleWidgetEx::childCount(), and navigate().
 {
     QWidgetList cl = childWidgets(widget());
     return cl.size();
 }
doAction()
bool QAccessibleWidget::doAction (int action, int child, const QVariantList & params) virtual
Reimplemented Function
Reimplemented from QAccessibleObject.
Definition at line 905 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::doAction().
 {
     if (action == SetFocus || action == DefaultAction) {
         if (child || !widget()->isEnabled())
             return false;
         if ((widget()->focusPolicy() == Qt::NoFocus) && (!widget()->isWindow()))
             return false;
         if (!widget()->isWindow())
             widget()->setFocus();
         widget()->activateWindow();
         return true;
     } else if (action > 0) {
         if (QAction *act = widget()->actions().value(action - 1)) {
             act->trigger();
             return true;
         }
     }
     return QAccessibleObject::doAction(action, child, params);
 }
indexOfChild()
int QAccessibleWidget::indexOfChild (const QAccessibleInterface * child) const virtual
Reimplemented Function
Implements QAccessibleInterface.
Reimplemented in QAccessibleWidgetStack.
Definition at line 802 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::indexOfChild().
 {
     QWidgetList cl = childWidgets(widget());
     int index = cl.indexOf(qobject_cast<QWidget *>(child->object()));
     if (index != -1)
         ++index;
     return index;
 }
navigate()
int QAccessibleWidget::navigate (RelationFlag rel, int entry, QAccessibleInterface ** target) const virtual
Reimplemented Function
Implements QAccessibleInterface.
Reimplemented in QAccessibleWidgetStack.
Definition at line 470 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::navigate(), and QAccessibleWidgetStack::navigate().
 {
     if (!target)
         return -1;
     *target = 0;
     QObject *targetObject = 0;
     QWidgetList childList = childWidgets(widget());
     bool complexWidget = childList.size() < childCount();
     switch (relation) {
     // Hierarchical
     case Self:
         targetObject = object();
         break;
     case Child:
         if (complexWidget) {
             if (entry > 0 && entry <= childCount())
                 return entry;
             return -1;
         }else {
             if (entry > 0 && childList.size() >= entry)
                 targetObject = childList.at(entry - 1);
         }
         break;
     case Ancestor:
         {
             if (entry <= 0)
                 return -1;
             targetObject = widget()->parentWidget();
             int i;
             for (i = entry; i > 1 && targetObject; --i)
                 targetObject = targetObject->parent();
             if (!targetObject && i == 1)
                 targetObject = qApp;
         }
         break;
     case Sibling:
         {
             QAccessibleInterface *iface = QAccessible::queryAccessibleInterface(parentObject());
             if (!iface)
                 return -1;
             iface->navigate(Child, entry, target);
             delete iface;
             if (*target)
                 return 0;
         }
         break;
     // Geometrical
     case QAccessible::Left:
         if (complexWidget && entry) {
             if (entry < 2 || widget()->height() > widget()->width() + 20) // looks vertical
                 return -1;
             return entry - 1;
         }
         // fall through
     case QAccessible::Right:
         if (complexWidget && entry) {
             if (entry >= childCount() || widget()->height() > widget()->width() + 20) // looks vertical
                 return -1;
             return entry + 1;
         }
         // fall through
     case QAccessible::Up:
         if (complexWidget && entry) {
             if (entry < 2 || widget()->width() > widget()->height() + 20) // looks horizontal
                 return - 1;
             return entry - 1;
         }
         // fall through
     case QAccessible::Down:
         if (complexWidget && entry) {
             if (entry >= childCount() || widget()->width() > widget()->height()  + 20) // looks horizontal
                 return - 1;
             return entry + 1;
         } else {
             QAccessibleInterface *pIface = QAccessible::queryAccessibleInterface(parentObject());
             if (!pIface)
                 return -1;
             QRect startg = rect(0);
             QPoint startc = startg.center();
             QAccessibleInterface *candidate = 0;
             int mindist = 100000;
             int sibCount = pIface->childCount();
             for (int i = 0; i < sibCount; ++i) {
                 QAccessibleInterface *sibling = 0;
                 pIface->navigate(Child, i+1, &sibling);
                 Q_ASSERT(sibling);
                 if ((relationTo(0, sibling, 0) & Self) || (sibling->state(0) & QAccessible::Invisible)) {
                     //ignore ourself and invisible siblings
                     delete sibling;
                     continue;
                 }
                 QRect sibg = sibling->rect(0);
                 QPoint sibc = sibg.center();
                 QPoint sibp;
                 QPoint startp;
                 QPoint distp;
                 switch (relation) {
                 case QAccessible::Left:
                     startp = QPoint(startg.left(), startg.top() + startg.height() / 2);
                     sibp = QPoint(sibg.right(), sibg.top() + sibg.height() / 2);
                     if (QPoint(sibc - startc).x() >= 0) {
                         delete sibling;
                         continue;
                     }
                     distp = sibp - startp;
                     break;
                 case QAccessible::Right:
                     startp = QPoint(startg.right(), startg.top() + startg.height() / 2);
                     sibp = QPoint(sibg.left(), sibg.top() + sibg.height() / 2);
                     if (QPoint(sibc - startc).x() <= 0) {
                         delete sibling;
                         continue;
                     }
                     distp = sibp - startp;
                     break;
                 case QAccessible::Up:
                     startp = QPoint(startg.left() + startg.width() / 2, startg.top());
                     sibp = QPoint(sibg.left() + sibg.width() / 2, sibg.bottom());
                     if (QPoint(sibc - startc).y() >= 0) {
                         delete sibling;
                         continue;
                     }
                     distp = sibp - startp;
                     break;
                 case QAccessible::Down:
                     startp = QPoint(startg.left() + startg.width() / 2, startg.bottom());
                     sibp = QPoint(sibg.left() + sibg.width() / 2, sibg.top());
                     if (QPoint(sibc - startc).y() <= 0) {
                         delete sibling;
                         continue;
                     }
                     distp = sibp - startp;
                     break;
         default:
             break;
                 }
                 int dist = (int)qSqrt((qreal)distp.x() * distp.x() + distp.y() * distp.y());
                 if (dist < mindist) {
                     delete candidate;
                     candidate = sibling;
                     mindist = dist;
                 } else {
                     delete sibling;
                 }
             }
             delete pIface;
             *target = candidate;
             if (*target)
                 return 0;
         }
         break;
     case Covers:
         if (entry > 0) {
             QAccessibleInterface *pIface = QAccessible::queryAccessibleInterface(parentObject());
             if (!pIface)
                 return -1;
             QRect r = rect(0);
             int sibCount = pIface->childCount();
             QAccessibleInterface *sibling = 0;
             for (int i = pIface->indexOfChild(this) + 1; i <= sibCount && entry; ++i) {
                 pIface->navigate(Child, i, &sibling);
                 if (!sibling || (sibling->state(0) & Invisible)) {
                     delete sibling;
                     sibling = 0;
                     continue;
                 }
                 if (sibling->rect(0).intersects(r))
                     --entry;
                 if (!entry)
                     break;
                 delete sibling;
                 sibling = 0;
             }
             delete pIface;
             *target = sibling;
             if (*target)
                 return 0;
         }
         break;
     case Covered:
         if (entry > 0) {
             QAccessibleInterface *pIface = QAccessible::queryAccessibleInterface(parentObject());
             if (!pIface)
                 return -1;
             QRect r = rect(0);
             int index = pIface->indexOfChild(this);
             QAccessibleInterface *sibling = 0;
             for (int i = 1; i < index && entry; ++i) {
                 pIface->navigate(Child, i, &sibling);
                 Q_ASSERT(sibling);
                 if (!sibling || (sibling->state(0) & Invisible)) {
                     delete sibling;
                     sibling = 0;
                     continue;
                 }
                 if (sibling->rect(0).intersects(r))
                     --entry;
                 if (!entry)
                     break;
                 delete sibling;
                 sibling = 0;
             }
             delete pIface;
             *target = sibling;
             if (*target)
                 return 0;
         }
         break;
     // Logical
     case FocusChild:
         {
             if (widget()->hasFocus()) {
                 targetObject = object();
                 break;
             }
             QWidget *fw = widget()->focusWidget();
             if (!fw)
                 return -1;
             if (isAncestor(widget(), fw) || fw == widget())
                 targetObject = fw;
             /* ###
             QWidget *parent = fw;
             while (parent && !targetObject) {
                 parent = parent->parentWidget();
                 if (parent == widget())
                     targetObject = fw;
             }
             */
         }
         break;
     case Label:
         if (entry > 0) {
             QAccessibleInterface *pIface = QAccessible::queryAccessibleInterface(parentObject());
             if (!pIface)
                 return -1;
             // first check for all siblings that are labels to us
             // ideally we would go through all objects and check, but that
             // will be too expensive
             int sibCount = pIface->childCount();
             QAccessibleInterface *candidate = 0;
             for (int i = 0; i < sibCount && entry; ++i) {
                 const int childId = pIface->navigate(Child, i+1, &candidate);
                 Q_ASSERT(childId >= 0);
                 if (childId > 0)
                     candidate = pIface;
                 if (candidate->relationTo(childId, this, 0) & Label)
                     --entry;
                 if (!entry)
                     break;
                 if (candidate != pIface)
                     delete candidate;
                 candidate = 0;
             }
             if (!candidate) {
                 if (pIface->relationTo(0, this, 0) & Label)
                     --entry;
                 if (!entry)
                     candidate = pIface;
             }
             if (pIface != candidate)
                 delete pIface;
             *target = candidate;
             if (*target)
                 return 0;
         }
         break;
     case Labelled: // only implemented in subclasses
         break;
     case Controller:
         if (entry > 0) {
             // check all senders we are connected to,
             // and figure out which one are controllers to us
             QACConnectionObject *connectionObject = (QACConnectionObject*)object();
             QObjectList allSenders = connectionObject->senderList();
             QObjectList senders;
             for (int s = 0; s < allSenders.size(); ++s) {
                 QObject *sender = allSenders.at(s);
                 QAccessibleInterface *candidate = QAccessible::queryAccessibleInterface(sender);
                 if (!candidate)
                     continue;
                 if (candidate->relationTo(0, this, 0)&Controller)
                     senders << sender;
                 delete candidate;
             }
             if (entry <= senders.size())
                 targetObject = senders.at(entry-1);
         }
         break;
     case Controlled:
         if (entry > 0) {
             QObjectList allReceivers;
             QACConnectionObject *connectionObject = (QACConnectionObject*)object();
             for (int sig = 0; sig < d->primarySignals.count(); ++sig) {
                 QObjectList receivers = connectionObject->receiverList(d->primarySignals.at(sig).toAscii());
                 allReceivers += receivers;
             }
             if (entry <= allReceivers.size())
                 targetObject = allReceivers.at(entry-1);
         }
         break;
     default:
         break;
     }
     *target = QAccessible::queryAccessibleInterface(targetObject);
     return *target ? 0 : -1;
 }
parentObject()
QObject * QAccessibleWidget::parentObject () const protected
Returns the associated widget's parent object, which is either the parent widget, or qApp for top-level widgets.
Definition at line 229 of file qaccessiblewidget.cpp.
Referenced by navigate(), and QAccessibleWidgetEx::parentObject().
 {
     QObject *parent = object()->parent();
     if (!parent)
         parent = qApp;
     return parent;
 }
rect()
QRect QAccessibleWidget::rect (int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleObject.
Definition at line 270 of file qaccessiblewidget.cpp.
Referenced by childAt(), Q3AccessibleTextEdit::itemRect(), navigate(), QAccessibleWidgetEx::rect(), and relationTo().
 {
     if (child) {
         qWarning("QAccessibleWidget::rect: This implementation does not support subelements! "
                  "(ID %d unknown for %s)", child, widget()->metaObject()->className());
     }
     QWidget *w = widget();
     if (!w->isVisible())
         return QRect();
     QPoint wpos = w->mapToGlobal(QPoint(0, 0));
     return QRect(wpos.x(), wpos.y(), w->width(), w->height());
 }
relationTo()
QAccessible::Relation QAccessibleWidget::relationTo (int child, const QAccessibleInterface * other, int otherChild) const virtual
Reimplemented Function
Implements QAccessibleInterface.
Definition at line 379 of file qaccessiblewidget.cpp.
Referenced by navigate(), and QAccessibleWidgetEx::relationTo().
 {
     Relation relation = Unrelated;
     if (d->asking == this) // recursive call
         return relation;
     QObject *o = other ? other->object() : 0;
     if (!o)
         return relation;
     QWidget *focus = widget()->focusWidget();
     if (object() == focus && isAncestor(o, focus))
         relation |= FocusChild;
     QACConnectionObject *connectionObject = (QACConnectionObject*)object();
     for (int sig = 0; sig < d->primarySignals.count(); ++sig) {
         if (connectionObject->isSender(o, d->primarySignals.at(sig).toAscii())) {
             relation |= Controller;
             break;
         }
     }
     // test for passive relationships.
     // d->asking protects from endless recursion.
     d->asking = this;
     int inverse = other->relationTo(otherChild, this, child);
     d->asking = 0;
     if (inverse & Controller)
         relation |= Controlled;
     if (inverse & Label)
         relation |= Labelled;
     if(o == object()) {
         if (child && !otherChild)
             return relation | Child;
         if (!child && otherChild)
             return relation | Ancestor;
         if (!child && !otherChild)
             return relation | Self;
     }
     QObject *parent = object()->parent();
     if (o == parent)
         return relation | Child;
     if (o->parent() == parent) {
         relation |= Sibling;
         QAccessibleInterface *sibIface = QAccessible::queryAccessibleInterface(o);
         Q_ASSERT(sibIface);
         QRect wg = rect(0);
         QRect sg = sibIface->rect(0);
         if (wg.intersects(sg)) {
             QAccessibleInterface *pIface = 0;
             sibIface->navigate(Ancestor, 1, &pIface);
             if (pIface && !((sibIface->state(0) | state(0)) & Invisible)) {
                 int wi = pIface->indexOfChild(this);
                 int si = pIface->indexOfChild(sibIface);
                 if (wi > si)
                     relation |= QAccessible::Covers;
                 else
                     relation |= QAccessible::Covered;
             }
             delete pIface;
         } else {
             QPoint wc = wg.center();
             QPoint sc = sg.center();
             if (wc.x() < sc.x())
                 relation |= QAccessible::Left;
             else if(wc.x() > sc.x())
                 relation |= QAccessible::Right;
             if (wc.y() < sc.y())
                 relation |= QAccessible::Up;
             else if (wc.y() > sc.y())
                 relation |= QAccessible::Down;
         }
         delete sibIface;
         return relation;
     }
     if (isAncestor(o, object()))
         return relation | Descendent;
     if (isAncestor(object(), o))
         return relation | Ancestor;
     return relation;
 }
role()
QAccessible::Role QAccessibleWidget::role (int child) const virtual
Reimplemented Function
Implements QAccessibleInterface.
Reimplemented in QAccessibleListBox, Q3AccessibleTextEdit, QAccessibleIconView, and QAccessibleListView.
Definition at line 932 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidget(), QAccessibleListView::role(), QAccessibleIconView::role(), QAccessibleWidgetEx::role(), Q3AccessibleTextEdit::role(), and QAccessibleListBox::role().
 {
     if (!child)
         return d->role;
     QWidgetList childList = childWidgets(widget());
     if (childList.count() > 0 && child <= childList.count()) {
         QWidget *targetWidget = childList.at(child - 1);
         QAccessibleInterface *iface = QAccessible::queryAccessibleInterface(targetWidget);
         if (iface) {
             QAccessible::Role role = iface->role(0);
             delete iface;
             return role;
         }
     }
     return NoRole;
 }
setAccelerator()
void QAccessibleWidget::setAccelerator (const QString & accel) protected
Sets the accelerator of this interface implementation to accel.
The default implementation of text() returns the set value for the Accelerator text.
Note that the object wrapped by this interface is not modified.
Definition at line 362 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::setAccelerator().
 {
     d->accelerator = accel;
 }
setDescription()
void QAccessibleWidget::setDescription (const QString & desc) protected
Sets the description of this interface implementation to desc.
The default implementation of text() returns the set value for the Description text.
Note that the object wrapped by this interface is not modified.
Definition at line 336 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetStack::QAccessibleWidgetStack(), and QAccessibleWidgetEx::setDescription().
 {
     d->description = desc;
 }
setHelp()
void QAccessibleWidget::setHelp (const QString & help) protected
Sets the help of this interface implementation to help.
The default implementation of text() returns the set value for the Help text.
Note that the object wrapped by this interface is not modified.
Definition at line 349 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::setHelp().
 {
     d->help = help;
 }
setValue()
void QAccessibleWidget::setValue (const QString & value) protected
Sets the value of this interface implementation to value.
The default implementation of text() returns the set value for the Value text.
Note that the object wrapped by this interface is not modified.
Definition at line 323 of file qaccessiblewidget.cpp.
Referenced by QAccessibleWidgetEx::setValue().
 {
     d->value = value;
 }
state()
QAccessible::State QAccessibleWidget::state (int child) const virtual
Reimplemented Function
Implements QAccessibleInterface.
Reimplemented in QAccessibleListBox, QAccessibleIconView, and QAccessibleListView.
Definition at line 952 of file qaccessiblewidget.cpp.
Referenced by relationTo(), QAccessibleListView::state(), QAccessibleIconView::state(), QAccessibleWidgetEx::state(), and QAccessibleListBox::state().
 {
     if (child)
         return Normal;
     QAccessible::State state = Normal;
     QWidget *w = widget();
     if (w->testAttribute(Qt::WA_WState_Visible) == false)
         state |= Invisible;
     if (w->focusPolicy() != Qt::NoFocus)
         state |= Focusable;
     if (w->hasFocus())
         state |= Focused;
     if (!w->isEnabled())
         state |= Unavailable;
     if (w->isWindow()) {
         if (w->windowFlags() & Qt::WindowSystemMenuHint)
             state |= Movable;
         if (w->minimumSize() != w->maximumSize())
             state |= Sizeable;
     }
     return state;
 }
text()
QString QAccessibleWidget::text (Text t, int child) const virtual
Reimplemented Function
Implements QAccessibleInterface.
Reimplemented in QAccessibleListBox, Q3AccessibleTextEdit, QAccessibleIconView, and QAccessibleListView.
Definition at line 815 of file qaccessiblewidget.cpp.
Referenced by QAccessibleListView::text(), QAccessibleIconView::text(), QAccessibleWidgetEx::text(), Q3AccessibleTextEdit::text(), and QAccessibleListBox::text().
 {
     QString str;
     switch (t) {
     case Name:
         if (!d->name.isEmpty()) {
             str = d->name;
         } else if (!widget()->accessibleName().isEmpty()) {
             str = widget()->accessibleName();
         } else if (!child && widget()->isWindow()) {
             if (widget()->isMinimized())
                 str = qt_setWindowTitle_helperHelper(widget()->windowIconText(), widget());
             else
                 str = qt_setWindowTitle_helperHelper(widget()->windowTitle(), widget());
         } else {
             str = qt_accStripAmp(buddyString(widget()));
         }
         break;
     case Description:
         if (!d->description.isEmpty())
             str = d->description;
         else if (!widget()->accessibleDescription().isEmpty())
             str = widget()->accessibleDescription();
 #ifndef QT_NO_TOOLTIP
         else
             str = widget()->toolTip();
 #endif
         break;
     case Help:
         if (!d->help.isEmpty())
             str = d->help;
 #ifndef QT_NO_WHATSTHIS
         else
             str = widget()->whatsThis();
 #endif
         break;
     case Accelerator:
         if (!d->accelerator.isEmpty())
             str = d->accelerator;
         else
             str = qt_accHotKey(buddyString(widget()));
         break;
     case Value:
         str = d->value;
         break;
     default:
         break;
     }
     return str;
 }
userActionCount()
int QAccessibleWidget::userActionCount (int child) const virtual
Reimplemented Function
Reimplemented from QAccessibleObject.
Definition at line 870 of file qaccessiblewidget.cpp.
 {
     if (child)
         return 0;
     return widget()->actions().count();
 }
widget()
QWidget * QAccessibleWidget::widget () const protected
Returns the associated widget.
Definition at line 220 of file qaccessiblewidget.cpp.
Referenced by actionText(), childAt(), childCount(), doAction(), QAccessibleIconView::iconView(), indexOfChild(), QAccessibleListBox::listBox(), QAccessibleListView::listView(), navigate(), Q3AccessibleTextEdit::Q3AccessibleTextEdit(), QAccessibleIconView::QAccessibleIconView(), QAccessibleListBox::QAccessibleListBox(), QAccessibleWidget(), rect(), relationTo(), role(), state(), text(), Q3AccessibleTextEdit::textEdit(), userActionCount(), and QAccessibleWidgetEx::widget().
 {
     return qobject_cast<QWidget*>(object());
 }
Friends and Related Functions
QAccessibleWidgetEx
friend class QAccessibleWidgetEx friend
Definition at line 92 of file qaccessiblewidget.h.
Properties
d
QAccessibleWidgetPrivate* QAccessibleWidget::d private
Definition at line 93 of file qaccessiblewidget.h.
Referenced by addControllingSignal(), navigate(), QAccessibleWidget(), relationTo(), role(), setAccelerator(), setDescription(), setHelp(), setValue(), text(), and ~QAccessibleWidget().
The documentation for this class was generated from the following files:
/src/gui/accessible/qaccessiblewidget.h
/src/gui/accessible/qaccessiblewidget.cpp