Qt 4.8: QScript::FunctionWrapper Class Reference
QScript::FunctionWrapper Class Reference
#include <qscriptfunction_p.h>
Classes
struct Data
Public Functions
virtual const JSC::ClassInfo * classInfo () const
QScriptEngine::FunctionSignature function () const
FunctionWrapper (JSC::ExecState *, int length, const JSC::Identifier &, QScriptEngine::FunctionSignature)
~FunctionWrapper ()
Static Public Variables
static const JSC::ClassInfo info = { "QtNativeFunctionWrapper", &PrototypeFunction::info, 0, 0 }
Private Functions
virtual JSC::ConstructType getConstructData (JSC::ConstructData &)
Static Private Functions
static JSC::JSValue JSC_HOST_CALL proxyCall (JSC::ExecState *, JSC::JSObject *, JSC::JSValue, const JSC::ArgList &)
static JSC::JSObject * proxyConstruct (JSC::ExecState *, JSC::JSObject *, const JSC::ArgList &)
Properties
Data * data
Detailed Description
Definition at line 49 of file qscriptfunction_p.h.
Constructors and Destructors
FunctionWrapper()
QScript::FunctionWrapper::FunctionWrapper (JSC::ExecState * exec, int length, const JSC::Identifier & name, QScriptEngine::FunctionSignature function)
Definition at line 52 of file qscriptfunction.cpp.
     : JSC::PrototypeFunction(exec, length, name, proxyCall),
       data(new Data())
 {
     data->function = function;
 }
~FunctionWrapper()
QScript::FunctionWrapper::~FunctionWrapper ()
Definition at line 60 of file qscriptfunction.cpp.
 {
     delete data;
 }
Functions
classInfo()
virtual const JSC::ClassInfo* QScript::FunctionWrapper::classInfo () const inline virtual
Definition at line 62 of file qscriptfunction_p.h.
 { return &info; }
function()
QScriptEngine::FunctionSignature QScript::FunctionWrapper::function () const inline
Definition at line 65 of file qscriptfunction_p.h.
     { return data->function; }
getConstructData()
JSC::ConstructType QScript::FunctionWrapper::getConstructData (JSC::ConstructData & consData) private virtual
Definition at line 65 of file qscriptfunction.cpp.
Referenced by QScript::FunctionWithArgWrapper::arg(), and function().
 {
     consData.native.function = proxyConstruct;
     consData.native.function.doNotCallDebuggerFunctionExit();
     return JSC::ConstructTypeHost;
 }
proxyCall()
JSC::JSValue QScript::FunctionWrapper::proxyCall (JSC::ExecState * exec, JSC::JSObject * callee, JSC::JSValue thisObject, const JSC::ArgList & args) static private
Definition at line 72 of file qscriptfunction.cpp.
Referenced by QScript::FunctionWithArgWrapper::arg(), and function().
 {
     FunctionWrapper *self = static_cast<FunctionWrapper*>(callee);
     QScriptEnginePrivate *eng_p = QScript::scriptEngineFromExec(exec);
     JSC::ExecState *oldFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, thisObject, args, callee);
     QScriptContext *ctx = eng_p->contextForFrame(eng_p->currentFrame);
     QScriptValue result = self->data->function(ctx, QScriptEnginePrivate::get(eng_p));
     if (!result.isValid())
         result = QScriptValue(QScriptValue::UndefinedValue);
     eng_p->popContext();
     eng_p->currentFrame = oldFrame;
     return eng_p->scriptValueToJSCValue(result);
 }
proxyConstruct()
JSC::JSObject * QScript::FunctionWrapper::proxyConstruct (JSC::ExecState * exec, JSC::JSObject * callee, const JSC::ArgList & args) static private
Definition at line 92 of file qscriptfunction.cpp.
Referenced by QScript::FunctionWithArgWrapper::arg(), function(), and getConstructData().
 {
     FunctionWrapper *self = static_cast<FunctionWrapper*>(callee);
     QScriptEnginePrivate *eng_p = QScript::scriptEngineFromExec(exec);
     JSC::ExecState *oldFrame = eng_p->currentFrame;
     eng_p->pushContext(exec, JSC::JSValue(), args, callee, true);
     QScriptContext *ctx = eng_p->contextForFrame(eng_p->currentFrame);
     QScriptValue result = self->data->function(ctx, QScriptEnginePrivate::get(eng_p));
     if (JSC::Debugger* debugger = eng_p->originalGlobalObject()->debugger())
         debugger->functionExit(QScriptValuePrivate::get(result)->jscValue, -1);
     if (!result.isObject())
         result = ctx->thisObject();
     eng_p->popContext();
     eng_p->currentFrame = oldFrame;
     return JSC::asObject(eng_p->scriptValueToJSCValue(result));
 }
Properties
data
Data* QScript::FunctionWrapper::data private
Definition at line 77 of file qscriptfunction_p.h.
Referenced by QScript::FunctionWithArgWrapper::arg(), function(), QScript::FunctionWithArgWrapper::function(), FunctionWrapper(), and ~FunctionWrapper().
info
const JSC::ClassInfo QScript::FunctionWrapper::info = { "QtNativeFunctionWrapper", &PrototypeFunction::info, 0, 0 } static
Definition at line 63 of file qscriptfunction_p.h.
Referenced by classInfo(), QScript::FunctionWithArgWrapper::classInfo(), and QScript::QMetaObjectWrapperObject::execute().
The documentation for this class was generated from the following files:
/src/script/bridge/qscriptfunction_p.h
/src/script/bridge/qscriptfunction.cpp