Qt 4.8: QTextTablePrivate Class Reference
QTextTablePrivate Class Reference
#include <qtexttable_p.h>
Public Functions
int findCellIndex (int fragment) const
void fragmentAdded (const QChar &type, uint fragment)
void fragmentRemoved (const QChar &type, uint fragment)
QTextTablePrivate (QTextDocument *document)
void update () const
/fn void QTextTablePrivate::update() const
~QTextTablePrivate ()
Public Functions inherited from QTextFramePrivate
QTextFramePrivate (QTextDocument *doc)
void remove_me ()
Public Functions inherited from QTextObjectPrivate
QTextObjectPrivate (QTextDocument *doc)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QTextTable * createTable (QTextDocumentPrivate *, int pos, int rows, int cols, const QTextTableFormat &tableFormat)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool blockFragmentUpdates
QVector< int > cellIndices
QList< int > cells
bool dirty
int * grid
int nCols
int nRows
Public Variables inherited from QTextFramePrivate
QList< QTextFrame * > childFrames
uint fragment_end
uint fragment_start
QTextFrameLayoutData * layoutData
QTextFrame * parentFrame
Public Variables inherited from QTextObjectPrivate
int objectIndex
QTextDocumentPrivate * pieceTable
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 61 of file qtexttable_p.h.
Constructors and Destructors
QTextTablePrivate()
QTextTablePrivate::QTextTablePrivate (QTextDocument * document) inline
Definition at line 65 of file qtexttable_p.h.
 : QTextFramePrivate(document), grid(0), nRows(0), nCols(0), dirty(true), blockFragmentUpdates(false) {}
~QTextTablePrivate()
QTextTablePrivate::~QTextTablePrivate ()
Definition at line 357 of file qtexttable.cpp.
Referenced by QTextTablePrivate().
 {
     if (grid)
         free(grid);
 }
Functions
createTable()
QTextTable * QTextTablePrivate::createTable (QTextDocumentPrivate * pieceTable, int pos, int rows, int cols, const QTextTableFormat & tableFormat) static
Definition at line 364 of file qtexttable.cpp.
Referenced by QTextCursor::insertTable(), and QTextTablePrivate().
 {
     QTextTableFormat fmt = tableFormat;
     fmt.setColumns(cols);
     QTextTable *table = qobject_cast<QTextTable *>(pieceTable->createObject(fmt));
     Q_ASSERT(table);
     pieceTable->beginEditBlock();
 //     qDebug("---> createTable: rows=%d, cols=%d at %d", rows, cols, pos);
     // add block after table
     QTextCharFormat charFmt;
     charFmt.setObjectIndex(table->objectIndex());
     charFmt.setObjectType(QTextFormat::TableCellObject);
     int charIdx = pieceTable->formatCollection()->indexForFormat(charFmt);
     int cellIdx = pieceTable->formatCollection()->indexForFormat(QTextBlockFormat());
     QTextTablePrivate *d = table->d_func();
     d->blockFragmentUpdates = true;
     d->fragment_start = pieceTable->insertBlock(QTextBeginningOfFrame, pos, cellIdx, charIdx);
     d->cells.append(d->fragment_start);
     ++pos;
     for (int i = 1; i < rows*cols; ++i) {
         d->cells.append(pieceTable->insertBlock(QTextBeginningOfFrame, pos, cellIdx, charIdx));
 //      qDebug("      addCell at %d", pos);
         ++pos;
     }
     d->fragment_end = pieceTable->insertBlock(QTextEndOfFrame, pos, cellIdx, charIdx);
 //  qDebug("      addEOR at %d", pos);
     ++pos;
     d->blockFragmentUpdates = false;
     d->dirty = true;
     pieceTable->endEditBlock();
     return table;
 }
findCellIndex()
int QTextTablePrivate::findCellIndex (int fragment) const
Definition at line 426 of file qtexttable.cpp.
Referenced by QTextTableCell::column(), QTextTablePrivate(), and QTextTableCell::row().
 {
     QFragmentFindHelper helper(pieceTable->fragmentMap().position(fragment),
                               pieceTable->fragmentMap());
     QList<int>::ConstIterator it = qBinaryFind(cells.begin(), cells.end(), helper);
     if (it == cells.end())
         return -1;
     return it - cells.begin();
 }
fragmentAdded()
void QTextTablePrivate::fragmentAdded (const QChar & type, uint fragment) virtual
Reimplemented from QTextFramePrivate.
Definition at line 436 of file qtexttable.cpp.
Referenced by QTextTablePrivate().
 {
     dirty = true;
     if (blockFragmentUpdates)
         return;
     if (type == QTextBeginningOfFrame) {
         Q_ASSERT(cells.indexOf(fragment) == -1);
         const uint pos = pieceTable->fragmentMap().position(fragment);
         QFragmentFindHelper helper(pos, pieceTable->fragmentMap());
         QList<int>::Iterator it = qLowerBound(cells.begin(), cells.end(), helper);
         cells.insert(it, fragment);
         if (!fragment_start || pos < pieceTable->fragmentMap().position(fragment_start))
             fragment_start = fragment;
         return;
     }
     QTextFramePrivate::fragmentAdded(type, fragment);
 }
fragmentRemoved()
void QTextTablePrivate::fragmentRemoved (const QChar & type, uint fragment) virtual
Reimplemented from QTextFramePrivate.
Definition at line 454 of file qtexttable.cpp.
Referenced by QTextTablePrivate().
 {
     dirty = true;
     if (blockFragmentUpdates)
         return;
     if (type == QTextBeginningOfFrame) {
         Q_ASSERT(cells.indexOf(fragment) != -1);
         cells.removeAll(fragment);
         if (fragment_start == fragment && cells.size()) {
             fragment_start = cells.at(0);
         }
         if (fragment_start != fragment)
             return;
     }
     QTextFramePrivate::fragmentRemoved(type, fragment);
 }
update()
void QTextTablePrivate::update () const
/fn void QTextTablePrivate::update() const
This function is usually called when the table is "dirty". It seems to update all kind of table information.
Definition at line 478 of file qtexttable.cpp.
Referenced by QTextTableCell::column(), QTextTablePrivate(), and QTextTableCell::row().
 {
     Q_Q(const QTextTable);
     nCols = q->format().columns();
     nRows = (cells.size() + nCols-1)/nCols;
 //     qDebug(">>>> QTextTablePrivate::update, nRows=%d, nCols=%d", nRows, nCols);
     grid = q_check_ptr((int *)realloc(grid, nRows*nCols*sizeof(int)));
     memset(grid, 0, nRows*nCols*sizeof(int));
     QTextDocumentPrivate *p = pieceTable;
     QTextFormatCollection *c = p->formatCollection();
     cellIndices.resize(cells.size());
     int cell = 0;
     for (int i = 0; i < cells.size(); ++i) {
         int fragment = cells.at(i);
         QTextCharFormat fmt = c->charFormat(QTextDocumentPrivate::FragmentIterator(&p->fragmentMap(), fragment)->format);
         int rowspan = fmt.tableCellRowSpan();
         int colspan = fmt.tableCellColumnSpan();
         // skip taken cells
         while (cell < nRows*nCols && grid[cell])
             ++cell;
         int r = cell/nCols;
         int c = cell%nCols;
         cellIndices[i] = cell;
         if (r + rowspan > nRows) {
             grid = q_check_ptr((int *)realloc(grid, sizeof(int)*(r + rowspan)*nCols));
             memset(grid + (nRows*nCols), 0, sizeof(int)*(r+rowspan-nRows)*nCols);
             nRows = r + rowspan;
         }
         Q_ASSERT(c + colspan <= nCols);
         for (int ii = 0; ii < rowspan; ++ii) {
             for (int jj = 0; jj < colspan; ++jj) {
                 Q_ASSERT(grid[(r+ii)*nCols + c+jj] == 0);
                 grid[(r+ii)*nCols + c+jj] = fragment;
 //              qDebug("    setting cell %d span=%d/%d at %d/%d", fragment, rowspan, colspan, r+ii, c+jj);
             }
         }
     }
 //     qDebug("<<<< end: nRows=%d, nCols=%d", nRows, nCols);
     dirty = false;
 }
Properties
blockFragmentUpdates
bool QTextTablePrivate::blockFragmentUpdates
Definition at line 84 of file qtexttable_p.h.
Referenced by createTable().
cellIndices
QVector<int> QTextTablePrivate::cellIndices mutable
Definition at line 79 of file qtexttable_p.h.
Referenced by QTextTableCell::column(), and QTextTableCell::row().
cells
QList<int> QTextTablePrivate::cells
Definition at line 76 of file qtexttable_p.h.
Referenced by createTable(), and QTextTableCell::lastPosition().
dirty
bool QTextTablePrivate::dirty mutable
Definition at line 83 of file qtexttable_p.h.
Referenced by QTextTableCell::column(), createTable(), and QTextTableCell::row().
grid
int* QTextTablePrivate::grid mutable
Definition at line 80 of file qtexttable_p.h.
nCols
int QTextTablePrivate::nCols mutable
Definition at line 82 of file qtexttable_p.h.
Referenced by QTextTableCell::column(), and QTextTableCell::row().
nRows
int QTextTablePrivate::nRows mutable
Definition at line 81 of file qtexttable_p.h.
The documentation for this class was generated from the following files:
/src/gui/text/qtexttable_p.h
/src/gui/text/qtexttable.cpp