Qt 4.8: QDragManager Class Reference
QDragManager Class Reference
#include <qdnd_p.h>
Public Functions
void cancel (bool deleteSource=true)
QWidget * currentTarget ()
Qt::DropAction defaultAction (Qt::DropActions possibleActions, Qt::KeyboardModifiers modifiers) const
Qt::DropAction drag (QDrag *)
QPixmap dragCursor (Qt::DropAction action) const
QDragPrivate * dragPrivate () const
void drop ()
void emitActionChanged (Qt::DropAction newAction)
bool hasCustomDragCursors () const
void move (const QPoint &)
void setCurrentTarget (QWidget *target, bool dropped=false)
QWidget * source () const
void updateCursor ()
void updatePixmap ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDragPrivate * dragPrivate (QDrag *drag)
static QDragManager * self ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
bool beingCancelled
QDropData * dropData
QEventLoop * eventLoop
QDrag * object
bool restoreCursor
bool willDrop
QPixmap xdndMimeTransferedPixmap [2]
int xdndMimeTransferedPixmapIndex
Private Functions
bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
QDragManager ()
void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
~QDragManager ()
Properties
Qt::DropAction currentActionForOverrideCursor
QWidget * currentDropTarget
Static Private Attributes
static QDragManager * instance = 0
Friends
class QApplication
class QDrag
class QDragMoveEvent
class QDropEvent
class QWidgetPrivate
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 206 of file qdnd_p.h.
Constructors and Destructors
QDragManager()
QDragManager::QDragManager () private
Definition at line 132 of file qdnd.cpp.
Referenced by self().
     : QObject(qApp)
 {
     Q_ASSERT(!instance);
 #ifdef Q_WS_QWS
     currentActionForOverrideCursor = Qt::IgnoreAction;
 #endif
     object = 0;
     beingCancelled = false;
     restoreCursor = false;
     willDrop = false;
     eventLoop = 0;
     dropData = new QDropData();
     currentDropTarget = 0;
 #ifdef Q_WS_X11
     xdndMimeTransferedPixmapIndex = 0;
 #endif
 }
~QDragManager()
QDragManager::~QDragManager () private
Definition at line 153 of file qdnd.cpp.
 {
 #ifndef QT_NO_CURSOR
     if (restoreCursor)
         QApplication::restoreOverrideCursor();
 #endif
     instance = 0;
     delete dropData;
 }
Functions
cancel()
void QDragManager::cancel (bool deleteSource = true)
Definition at line 272 of file qdnd_mac.mm.
Referenced by QOleDropTarget::Drop(), and QDrag::~QDrag().
 {
     if(object) {
         beingCancelled = true;
         object = 0;
     }
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::DragDropEnd);
 #endif
 }
currentTarget()
QWidget * QDragManager::currentTarget ()
Definition at line 273 of file qdnd.cpp.
Referenced by make_widget_eventUPP(), and QApplication::notify().
 {
     return currentDropTarget;
 }
defaultAction()
Qt::DropAction QDragManager::defaultAction (Qt::DropActions possibleActions, Qt::KeyboardModifiers modifiers) const
Definition at line 194 of file qdnd.cpp.
Referenced by QDropEvent::QDropEvent(), and qt_mac_dnd_update_action().
 {
 #ifdef QDND_DEBUG
     qDebug("QDragManager::defaultAction(Qt::DropActions possibleActions)");
     qDebug("keyboard modifiers : %s", KeyboardModifiersToString(modifiers).latin1());
 #endif
     QDragPrivate *d = dragPrivate();
     Qt::DropAction defaultAction = d ? d->defaultDropAction : Qt::IgnoreAction;
     if (defaultAction == Qt::IgnoreAction) {
         //This means that the drag was initiated by QDrag::start and we need to
         //preserve the old behavior
 #ifdef Q_WS_MAC
         defaultAction = Qt::MoveAction;
 #else
         defaultAction = Qt::CopyAction;
 #endif
     }
 #ifdef Q_WS_MAC
     if (modifiers & Qt::ControlModifier && modifiers & Qt::AltModifier)
         defaultAction = Qt::LinkAction;
     else if (modifiers & Qt::AltModifier)
         defaultAction = Qt::CopyAction;
     else if (modifiers & Qt::ControlModifier)
         defaultAction = Qt::MoveAction;
 #else
     if (modifiers & Qt::ControlModifier && modifiers & Qt::ShiftModifier)
         defaultAction = Qt::LinkAction;
     else if (modifiers & Qt::ControlModifier)
         defaultAction = Qt::CopyAction;
     else if (modifiers & Qt::ShiftModifier)
         defaultAction = Qt::MoveAction;
     else if (modifiers & Qt::AltModifier)
         defaultAction = Qt::LinkAction;
 #endif
     // if the object is set take the list of possibles from it
     if (object)
         possibleActions = object->d_func()->possible_actions;
 #ifdef QDND_DEBUG
     qDebug("possible actions : %s", dragActionsToString(possibleActions).latin1());
 #endif
     // Check if the action determined is allowed
     if (!(possibleActions & defaultAction)) {
         if (possibleActions & Qt::CopyAction)
             defaultAction = Qt::CopyAction;
         else if (possibleActions & Qt::MoveAction)
             defaultAction = Qt::MoveAction;
         else if (possibleActions & Qt::LinkAction)
             defaultAction = Qt::LinkAction;
         else
             defaultAction = Qt::IgnoreAction;
     }
 #ifdef QDND_DEBUG
     qDebug("default action : %s", dragActionsToString(defaultAction).latin1());
 #endif
     return defaultAction;
 }
drag()
Qt::DropAction QDragManager::drag (QDrag * o)
Definition at line 530 of file qdnd_mac.mm.
Referenced by QX11Data::dndEnable(), QOleDropTarget::Drop(), QDrag::exec(), and QDrag::start().
 {
     if(qt_mac_in_drag) {     //just make sure..
         qWarning("Qt: Internal error: WH0A, unexpected condition reached");
         return Qt::IgnoreAction;
     }
     if(object == o)
         return Qt::IgnoreAction;
     /* At the moment it seems clear that Mac OS X does not want to drag with a non-left button
        so we just bail early to prevent it */
     if(!(GetCurrentEventButtonState() & kEventMouseButtonPrimary))
         return Qt::IgnoreAction;
     if(object) {
         dragPrivate()->source->removeEventFilter(this);
         cancel();
         beingCancelled = false;
     }
     object = o;
     dragPrivate()->target = 0;
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::DragDropStart);
 #endif
     //setup the data
     QMacPasteboard dragBoard(QMacPasteboardMime::MIME_DND);
     dragBoard.setMimeData(dragPrivate()->data);
     //create the drag
     OSErr result;
     DragRef dragRef;
     if((result = NewDragWithPasteboard(dragBoard.pasteBoard(), &dragRef)))
         return Qt::IgnoreAction;
     //setup the actions
     DragActions possibleActions = qt_mac_dnd_map_qt_actions(dragPrivate()->possible_actions);
     SetDragAllowableActions(dragRef, //local
                             possibleActions,
                             true);
     SetDragAllowableActions(dragRef, //remote (same as local)
                             possibleActions,
                             false);
     QPoint hotspot;
     QPixmap pix = dragPrivate()->pixmap;
     if(pix.isNull()) {
         if(dragPrivate()->data->hasText() || dragPrivate()->data->hasUrls()) {
             //get the string
             QString s = dragPrivate()->data->hasText() ? dragPrivate()->data->text()
                                                 : dragPrivate()->data->urls().first().toString();
             if(s.length() > 26)
                 s = s.left(23) + QChar(0x2026);
             if(!s.isEmpty()) {
                 //draw it
                 QFont f(qApp->font());
                 f.setPointSize(12);
                 QFontMetrics fm(f);
                 const int width = fm.width(s);
                 const int height = fm.height();
                 if(width > 0 && height > 0) {
                     QPixmap tmp(width, height);
                     QPainter p(&tmp);
                     p.fillRect(0, 0, tmp.width(), tmp.height(), Qt::color0);
                     p.setPen(Qt::color1);
                     p.setFont(f);
                     p.drawText(0, fm.ascent(), s);
                     p.end();
                     //save it
                     pix = tmp;
                     hotspot = QPoint(tmp.width() / 2, tmp.height() / 2);
                 }
             }
         } else {
             pix = QPixmap(default_pm);
             hotspot = QPoint(default_pm_hotx, default_pm_hoty);
         }
     } else {
         hotspot = dragPrivate()->hotspot;
     }
     //so we must fake an event
     EventRecord fakeEvent;
     GetGlobalMouse(&(fakeEvent.where));
     fakeEvent.message = 0;
     fakeEvent.what = mouseDown;
     fakeEvent.when = EventTimeToTicks(GetCurrentEventTime());
     fakeEvent.modifiers = GetCurrentKeyModifiers();
     if(GetCurrentEventButtonState() & 2)
         fakeEvent.modifiers |= controlKey;
     //find the hotspot in relation to the pixmap
     Point boundsPoint;
     boundsPoint.h = fakeEvent.where.h - hotspot.x();
     boundsPoint.v = fakeEvent.where.v - hotspot.y();
     Rect boundsRect;
     SetRect(&boundsRect, boundsPoint.h, boundsPoint.v, boundsPoint.h + pix.width(), boundsPoint.v + pix.height());
     //set the drag image
     QRegion dragRegion(boundsPoint.h, boundsPoint.v, pix.width(), pix.height()), pixRegion;
     if(!pix.isNull()) {
         HIPoint hipoint = { -hotspot.x(), -hotspot.y() };
         CGImageRef img = (CGImageRef)pix.macCGHandle();
         SetDragImageWithCGImage(dragRef, img, &hipoint, 0);
         CGImageRelease(img);
     }
     SetDragItemBounds(dragRef, (ItemReference)1 , &boundsRect);
     { //do the drag
         qt_mac_in_drag = true;
         qt_mac_dnd_update_action(dragRef);
         result = TrackDrag(dragRef, &fakeEvent, QMacSmartQuickDrawRegion(dragRegion.toQDRgn()));
         qt_mac_in_drag = false;
     }
     object = 0;
     if(result == noErr) {
         // Check if the receiver points us to
         // a file location. If so, we need to do
         // the file copy/move ourselves:
         QCFType<CFURLRef> pasteLocation = 0;
         PasteboardCopyPasteLocation(dragBoard.pasteBoard(), &pasteLocation);
         if (pasteLocation){
             Qt::DropAction action = o->d_func()->defaultDropAction;
             if (action == Qt::IgnoreAction){
                 if (o->d_func()->possible_actions & Qt::MoveAction)
                     action = Qt::MoveAction;
                 else if (o->d_func()->possible_actions & Qt::CopyAction)
                     action = Qt::CopyAction;
             }
             bool atleastOne = false;
             QList<QUrl> urls = o->mimeData()->urls();
             for (int i = 0; i < urls.size(); ++i){
                 QUrl fromUrl = urls.at(i);
                 QString filename = QFileInfo(fromUrl.path()).fileName();
                 QUrl toUrl(QCFString::toQString(CFURLGetString(pasteLocation)) + filename);
                 if (action == Qt::MoveAction){
                     if (QFile::rename(fromUrl.path(), toUrl.path()))
                         atleastOne = true;
                 } else if (action == Qt::CopyAction){
                     if (QFile::copy(fromUrl.path(), toUrl.path()))
                         atleastOne = true;
                 }
             }
             if (atleastOne){
                 DisposeDrag(dragRef);
                 o->setMimeData(0);
                 o->deleteLater();
                 return action;
             }
         }
         DragActions ret = kDragActionNothing;
         GetDragDropAction(dragRef, &ret);
         DisposeDrag(dragRef); //cleanup
         o->setMimeData(0);
         o->deleteLater();
         return qt_mac_dnd_map_mac_default_action(ret);
     }
     DisposeDrag(dragRef); //cleanup
     return Qt::IgnoreAction;
 }
dragCursor()
QPixmap QDragManager::dragCursor (Qt::DropAction action) const
Definition at line 170 of file qdnd.cpp.
Referenced by QOleDropSource::createCursors().
 {
     QDragPrivate * d = dragPrivate();
     if (d && d->customCursors.contains(action))
         return d->customCursors[action];
     else if (action == Qt::MoveAction)
         return QApplicationPrivate::instance()->getPixmapCursor(Qt::DragMoveCursor);
     else if (action == Qt::CopyAction)
         return QApplicationPrivate::instance()->getPixmapCursor(Qt::DragCopyCursor);
     else if (action == Qt::LinkAction)
         return QApplicationPrivate::instance()->getPixmapCursor(Qt::DragLinkCursor);
 #ifdef Q_WS_WIN
     else if (action == Qt::IgnoreAction)
         return QApplicationPrivate::instance()->getPixmapCursor(Qt::ForbiddenCursor);
 #endif
     return QPixmap();
 }
dragPrivate() [1/2]
QDragPrivate* QDragManager::dragPrivate () const inline
Definition at line 231 of file qdnd_p.h.
Referenced by defaultAction(), dragCursor(), QOleDropTarget::DragOver(), QOleDropTarget::Drop(), handle_xdnd_position(), hasCustomDragCursors(), qt_mac_mouse_inside_answer_rect(), qt_xdnd_send_leave(), QOleDropTarget::sendDragEnterEvent(), QX11Data::xdndHandleDrop(), QX11Data::xdndHandleSelectionRequest(), and xdndObtainData().
 { return object ? object->d_func() : 0; }
dragPrivate() [2/2]
static QDragPrivate* QDragManager::dragPrivate (QDrag * drag) inline static
Definition at line 232 of file qdnd_p.h.
 { return drag ? drag->d_func() : 0; }
drop()
void QDragManager::drop ()
Definition at line 287 of file qdnd_mac.mm.
Referenced by QOleDropTarget::Drop(), and findRealWindow().
 {
 }
emitActionChanged()
void QDragManager::emitActionChanged (Qt::DropAction newAction) inline
Definition at line 253 of file qdnd_p.h.
Referenced by QOleDropSource::GiveFeedback(), handle_xdnd_status(), qt_mac_dnd_update_action(), and qt_xdnd_send_leave().
 { if (object) emit object->actionChanged(newAction); }
eventFilter()
bool QDragManager::eventFilter (QObject * , QEvent *) private virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 263 of file qdnd_mac.mm.
Referenced by QOleDropTarget::Drop().
 {
     return false;
 }
hasCustomDragCursors()
bool QDragManager::hasCustomDragCursors () const
Definition at line 188 of file qdnd.cpp.
Referenced by QOleDropSource::createCursors().
 {
     QDragPrivate * d = dragPrivate();
     return d && !d->customCursors.isEmpty();
 }
move()
void QDragManager::move (const QPoint & globalPos)
Definition at line 283 of file qdnd_mac.mm.
Referenced by QOleDropTarget::Drop(), and findRealWindow().
 {
 }
self()
QDragManager * QDragManager::self () static
Definition at line 163 of file qdnd.cpp.
Referenced by QOleDropSource::createCursors(), QOleDropTarget::DragEnter(), QOleDropTarget::DragLeave(), QOleDropTarget::DragOver(), QOleDropTarget::Drop(), QStyledItemDelegate::eventFilter(), QItemDelegate::eventFilter(), QDrag::exec(), QOleDropSource::GiveFeedback(), handle_xdnd_position(), handle_xdnd_status(), make_widget_eventUPP(), QX11Data::motifdndHandle(), QApplication::notify(), QDropEvent::QDropEvent(), qt_mac_dnd_update_action(), qt_mac_mouse_inside_answer_rect(), qt_mac_update_widget_position(), qt_xdnd_send_leave(), restartXdndDropExpiryTimer(), QOleDropTarget::sendDragEnterEvent(), QDropEvent::source(), QDrag::start(), QX11Data::xdndHandleBadwindow(), QX11Data::xdndHandleDrop(), QX11Data::xdndHandleFinished(), QX11Data::xdndHandleSelectionRequest(), QX11Data::xdndMimeDataForAtom(), xdndObtainData(), QApplication::~QApplication(), and QDrag::~QDrag().
 {
     if (!instance && !QApplication::closingDown())
         instance = new QDragManager;
     return instance;
 }
setCurrentTarget()
void QDragManager::setCurrentTarget (QWidget * target, bool dropped = false)
Definition at line 260 of file qdnd.cpp.
Referenced by QApplication::notify().
 {
     if (currentDropTarget == target)
         return;
     currentDropTarget = target;
     if (!dropped && object) {
         object->d_func()->target = target;
         emit object->targetChanged(target);
     }
 }
source()
QWidget* QDragManager::source () const inline
Definition at line 230 of file qdnd_p.h.
Referenced by QOleDropTarget::DragOver(), QOleDropTarget::Drop(), QOleDropTarget::sendDragEnterEvent(), and QDropEvent::source().
 { return object ? object->d_func()->source : 0; }
timerEvent()
void QDragManager::timerEvent (QTimerEvent * event) private virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 259 of file qdnd_mac.mm.
Referenced by QOleDropTarget::Drop().
 {
 }
updateCursor()
void QDragManager::updateCursor ()
Definition at line 268 of file qdnd_mac.mm.
Referenced by handle_xdnd_status(), and qt_xdnd_send_leave().
 {
 }
updatePixmap()
void QDragManager::updatePixmap ()
Definition at line 696 of file qdnd_mac.mm.
Referenced by QOleDropTarget::Drop().
 {
 }
Friends and Related Functions
QApplication
friend class QApplication friend
Definition at line 215 of file qdnd_p.h.
QDrag
friend class QDrag friend
Definition at line 212 of file qdnd_p.h.
QDragMoveEvent
friend class QDragMoveEvent friend
Definition at line 213 of file qdnd_p.h.
QDropEvent
friend class QDropEvent friend
Definition at line 214 of file qdnd_p.h.
QWidgetPrivate
friend class QWidgetPrivate friend
Definition at line 217 of file qdnd_p.h.
Properties
beingCancelled
bool QDragManager::beingCancelled
Definition at line 242 of file qdnd_p.h.
Referenced by QDragManager().
currentActionForOverrideCursor
Qt::DropAction QDragManager::currentActionForOverrideCursor private
Definition at line 265 of file qdnd_p.h.
Referenced by QDragManager().
currentDropTarget
QWidget* QDragManager::currentDropTarget private
Definition at line 272 of file qdnd_p.h.
Referenced by currentTarget(), QDragManager(), and setCurrentTarget().
dropData
QDropData* QDragManager::dropData
Definition at line 251 of file qdnd_p.h.
Referenced by QOleDropTarget::DragEnter(), QOleDropTarget::DragLeave(), QOleDropTarget::DragOver(), QOleDropTarget::Drop(), handle_xdnd_position(), QX11Data::motifdndHandle(), QDragManager(), qt_mac_mouse_inside_answer_rect(), QOleDropTarget::sendDragEnterEvent(), and ~QDragManager().
eventLoop
QEventLoop* QDragManager::eventLoop
Definition at line 245 of file qdnd_p.h.
Referenced by QDragManager().
instance
QDragManager * QDragManager::instance = 0 static private
Definition at line 274 of file qdnd_p.h.
Referenced by QDragManager(), self(), and ~QDragManager().
object
QDrag* QDragManager::object
Definition at line 238 of file qdnd_p.h.
Referenced by QOleDropSource::createCursors(), handle_xdnd_position(), qt_mac_mouse_inside_answer_rect(), qt_mac_update_widget_position(), QX11Data::xdndHandleBadwindow(), QX11Data::xdndHandleFinished(), QX11Data::xdndHandleSelectionRequest(), xdndObtainData(), and QDrag::~QDrag().
restoreCursor
bool QDragManager::restoreCursor
Definition at line 243 of file qdnd_p.h.
Referenced by QDragManager(), and ~QDragManager().
willDrop
bool QDragManager::willDrop
Definition at line 244 of file qdnd_p.h.
Referenced by handle_xdnd_status(), QDragManager(), and qt_xdnd_send_leave().
xdndMimeTransferedPixmap
QPixmap QDragManager::xdndMimeTransferedPixmap[2]
Definition at line 259 of file qdnd_p.h.
Referenced by QX11Data::xdndMimeDataForAtom().
xdndMimeTransferedPixmapIndex
int QDragManager::xdndMimeTransferedPixmapIndex
Definition at line 260 of file qdnd_p.h.
Referenced by QDragManager(), and QX11Data::xdndMimeDataForAtom().
The documentation for this class was generated from the following files:
/src/gui/kernel/qdnd_p.h
/src/gui/kernel/qdnd.cpp
/src/gui/kernel/qdnd_mac.mm
/src/gui/kernel/qdnd_qws.cpp
/src/gui/kernel/qdnd_win.cpp
/src/gui/kernel/qdnd_x11.cpp