Qt 4.8: QTextBrowserPrivate Class Reference
QTextBrowserPrivate Class Reference
Classes
struct HistoryEntry
Public Functions
void _q_activateAnchor (const QString &href)
void _q_documentModified ()
void _q_highlightLink (const QString &href)
HistoryEntry createHistoryEntry () const
QString findFile (const QUrl &name) const
HistoryEntry history (int i) const
void init ()
QTextBrowserPrivate ()
virtual QUrl resolveUrl (const QUrl &url) const
QUrl resolveUrl (const QString &url) const
void restoreHistoryEntry (const HistoryEntry entry)
void setSource (const QUrl &url)
Public Functions inherited from QTextEditPrivate
void _q_adjustScrollbars ()
void _q_currentCharFormatChanged (const QTextCharFormat &format)
void _q_ensureVisible (const QRectF &rect)
void _q_repaintContents (const QRectF &contentsRect)
void createAutoBulletList ()
int horizontalOffset () const
void init (const QString &html=QString())
QPoint mapToContents (const QPoint &point) const
void pageUpDown (QTextCursor::MoveOperation op, QTextCursor::MoveMode moveMode)
void paint (QPainter *p, QPaintEvent *e)
QTextEditPrivate ()
void relayoutDocument ()
void sendControlEvent (QEvent *e)
void updateDefaultTextOption ()
int verticalOffset () const
Public Functions inherited from QAbstractScrollAreaPrivate
void _q_hslide (int)
void _q_showOrHideScrollBars ()
void _q_vslide (int)
virtual QPoint contentsOffset () const
void init ()
void layoutChildren ()
QAbstractScrollAreaPrivate ()
void replaceScrollBar (QScrollBar *scrollBar, Qt::Orientation orientation)
virtual void scrollBarPolicyChanged (Qt::Orientation, Qt::ScrollBarPolicy)
void setSingleFingerPanEnabled (bool on=true)
bool viewportEvent (QEvent *event)
Public Functions inherited from QFramePrivate
void init ()
QFramePrivate ()
void updateFrameWidth ()
Updated the frameWidth parameter.
void updateStyledFrameWidths ()
Updates the frame widths from the style.
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QUrl currentURL
bool forceLoadOnSourceChange
QStack< HistoryEntry > forwardStack
QUrl home
QCursor oldCursor
bool openExternalLinks
bool openLinks
QStringList searchPaths
QStack< HistoryEntry > stack
bool textOrSourceChanged
Public Variables inherited from QTextEditPrivate
QString anchorToScrollToWhenVisible
QTextEdit::AutoFormatting autoFormatting
QPoint autoScrollDragPos
QBasicTimer autoScrollTimer
uint clickCausedFocus: 1
QTextControl * control
uint ignoreAutomaticScrollbarAdjustment: 1
uint inDrag: 1
QTextEdit::LineWrapMode lineWrap
int lineWrapColumnOrWidth
uint preferRichText: 1
uint showCursorOnInitialShow: 1
bool tabChangesFocus
Qt::TextFormat textFormat
QTextOption::WrapMode wordWrap
Public Variables inherited from QAbstractScrollAreaPrivate
int bottom
QRect cornerPaintingRect
QWidget * cornerWidget
QScrollBar * hbar
Qt::ScrollBarPolicy hbarpolicy
int left
QRect reverseCornerPaintingRect
int right
QAbstractScrollAreaScrollBarContainer * scrollBarContainers [Qt::Vertical+1]
bool singleFingerPanEnabled
int top
QScrollBar * vbar
Qt::ScrollBarPolicy vbarpolicy
QWidget * viewport
QScopedPointer< QObject > viewportFilter
int xoffset
int yoffset
Public Variables inherited from QFramePrivate
short bottomFrameWidth
int frameStyle
short frameWidth
QRect frect
short leftFrameWidth
short lineWidth
short midLineWidth
short rightFrameWidth
short topFrameWidth
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 63 of file qtextbrowser.cpp.
Constructors and Destructors
QTextBrowserPrivate()
QTextBrowserPrivate::QTextBrowserPrivate () inline
Definition at line 67 of file qtextbrowser.cpp.
         : textOrSourceChanged(false), forceLoadOnSourceChange(false), openExternalLinks(false),
           openLinks(true)
 #ifdef QT_KEYPAD_NAVIGATION
         , lastKeypadScrollValue(-1)
 #endif
     {}
Functions
_q_activateAnchor()
void QTextBrowserPrivate::_q_activateAnchor (const QString & href)
Definition at line 198 of file qtextbrowser.cpp.
Referenced by _q_documentModified(), and init().
 {
     if (href.isEmpty())
         return;
     Q_Q(QTextBrowser);
 #ifndef QT_NO_CURSOR
     viewport->setCursor(oldCursor);
 #endif
     const QUrl url = resolveUrl(href);
     if (!openLinks) {
         emit q->anchorClicked(url);
         return;
     }
     textOrSourceChanged = false;
 #ifndef QT_NO_DESKTOPSERVICES
     if ((openExternalLinks
          && url.scheme() != QLatin1String("file")
          && url.scheme() != QLatin1String("qrc")
          && !url.isRelative())
         || (url.isRelative() && !currentURL.isRelative()
             && currentURL.scheme() != QLatin1String("file")
             && currentURL.scheme() != QLatin1String("qrc"))) {
         QDesktopServices::openUrl(url);
         return;
     }
 #endif
     emit q->anchorClicked(url);
     if (textOrSourceChanged)
         return;
     q->setSource(url);
 }
_q_documentModified()
void QTextBrowserPrivate::_q_documentModified () inline
Definition at line 128 of file qtextbrowser.cpp.
Referenced by init().
     {
         textOrSourceChanged = true;
         forceLoadOnSourceChange = !currentURL.path().isEmpty();
     }
_q_highlightLink()
void QTextBrowserPrivate::_q_highlightLink (const QString & href)
Definition at line 238 of file qtextbrowser.cpp.
Referenced by _q_documentModified(), and init().
 {
     Q_Q(QTextBrowser);
     if (anchor.isEmpty()) {
 #ifndef QT_NO_CURSOR
         if (viewport->cursor().shape() != Qt::PointingHandCursor)
             oldCursor = viewport->cursor();
         viewport->setCursor(oldCursor);
 #endif
         emit q->highlighted(QUrl());
         emit q->highlighted(QString());
     } else {
 #ifndef QT_NO_CURSOR
         viewport->setCursor(Qt::PointingHandCursor);
 #endif
         const QUrl url = resolveUrl(anchor);
         emit q->highlighted(url);
         // convenience to ease connecting to QStatusBar::showMessage(const QString &)
         emit q->highlighted(url.toString());
     }
 }
createHistoryEntry()
QTextBrowserPrivate::HistoryEntry QTextBrowserPrivate::createHistoryEntry () const
Definition at line 537 of file qtextbrowser.cpp.
Referenced by history().
 {
     HistoryEntry entry;
     entry.url = q_func()->source();
     entry.title = q_func()->documentTitle();
     entry.hpos = hbar->value();
     entry.vpos = vbar->value();
     const QTextCursor cursor = control->textCursor();
     if (control->cursorIsFocusIndicator()
         && cursor.hasSelection()) {
         entry.focusIndicatorPosition = cursor.position();
         entry.focusIndicatorAnchor = cursor.anchor();
     }
     return entry;
 }
findFile()
QString QTextBrowserPrivate::findFile (const QUrl & name) const
Definition at line 151 of file qtextbrowser.cpp.
 {
     QString fileName;
     if (name.scheme() == QLatin1String("qrc"))
         fileName = QLatin1String(":/") + name.path();
     else
         fileName = name.toLocalFile();
     if (QFileInfo(fileName).isAbsolute())
         return fileName;
     foreach (QString path, searchPaths) {
         if (!path.endsWith(QLatin1Char('/')))
             path.append(QLatin1Char('/'));
         path.append(fileName);
         if (QFileInfo(path).isReadable())
             return path;
     }
     return fileName;
 }
history()
HistoryEntry QTextBrowserPrivate::history (int i) const inline
Definition at line 88 of file qtextbrowser.cpp.
     {
         if (i <= 0)
             if (-i < stack.count())
                 return stack[stack.count()+i-1];
             else
                 return HistoryEntry();
         else
             if (i <= forwardStack.count())
                 return forwardStack[forwardStack.count()-i];
             else
                 return HistoryEntry();
     }
init()
void QTextBrowserPrivate::init ()
Definition at line 659 of file qtextbrowser.cpp.
Referenced by QTextBrowserPrivate().
 {
     Q_Q(QTextBrowser);
     control->setTextInteractionFlags(Qt::TextBrowserInteraction);
 #ifndef QT_NO_CURSOR
     viewport->setCursor(oldCursor);
 #endif
     q->setUndoRedoEnabled(false);
     viewport->setMouseTracking(true);
     QObject::connect(q->document(), SIGNAL(contentsChanged()), q, SLOT(_q_documentModified()));
     QObject::connect(control, SIGNAL(linkActivated(QString)),
                      q, SLOT(_q_activateAnchor(QString)));
     QObject::connect(control, SIGNAL(linkHovered(QString)),
                      q, SLOT(_q_highlightLink(QString)));
 }
resolveUrl() [1/2]
QUrl QTextBrowserPrivate::resolveUrl (const QUrl & url) const virtual
Reimplemented from QTextEditPrivate.
Definition at line 173 of file qtextbrowser.cpp.
Referenced by _q_activateAnchor(), _q_documentModified(), _q_highlightLink(), resolveUrl(), restoreHistoryEntry(), and setSource().
 {
     if (!url.isRelative())
         return url;
     // For the second case QUrl can merge "#someanchor" with "foo.html"
     // correctly to "foo.html#someanchor"
     if (!(currentURL.isRelative()
           || (currentURL.scheme() == QLatin1String("file")
               && !QFileInfo(currentURL.toLocalFile()).isAbsolute()))
           || (url.hasFragment() && url.path().isEmpty())) {
         return currentURL.resolved(url);
     }
     // this is our last resort when current url and new url are both relative
     // we try to resolve against the current working directory in the local
     // file system.
     QFileInfo fi(currentURL.toLocalFile());
     if (fi.exists()) {
         return QUrl::fromLocalFile(fi.absolutePath() + QDir::separator()).resolved(url);
     }
     return url;
 }
resolveUrl() [2/2]
QUrl QTextBrowserPrivate::resolveUrl (const QString & url) const inline
Definition at line 141 of file qtextbrowser.cpp.
     { return resolveUrl(QUrl::fromEncoded(url.toUtf8())); }
restoreHistoryEntry()
void QTextBrowserPrivate::restoreHistoryEntry (const HistoryEntry entry)
Definition at line 555 of file qtextbrowser.cpp.
Referenced by history().
 {
     setSource(entry.url);
     hbar->setValue(entry.hpos);
     vbar->setValue(entry.vpos);
     if (entry.focusIndicatorAnchor != -1 && entry.focusIndicatorPosition != -1) {
         QTextCursor cursor(control->document());
         cursor.setPosition(entry.focusIndicatorAnchor);
         cursor.setPosition(entry.focusIndicatorPosition, QTextCursor::KeepAnchor);
         control->setTextCursor(cursor);
         control->setCursorIsFocusIndicator(true);
     }
 #ifdef QT_KEYPAD_NAVIGATION
     lastKeypadScrollValue = vbar->value();
     prevFocus = control->textCursor();
     Q_Q(QTextBrowser);
     const QString href = prevFocus.charFormat().anchorHref();
     QUrl url = resolveUrl(href);
     emit q->highlighted(url);
     emit q->highlighted(url.toString());
 #endif
 }
setSource()
void QTextBrowserPrivate::setSource (const QUrl & url)
Definition at line 261 of file qtextbrowser.cpp.
Referenced by _q_documentModified(), and restoreHistoryEntry().
 {
     Q_Q(QTextBrowser);
 #ifndef QT_NO_CURSOR
     if (q->isVisible())
         QApplication::setOverrideCursor(Qt::WaitCursor);
 #endif
     textOrSourceChanged = true;
     QString txt;
     bool doSetText = false;
     QUrl currentUrlWithoutFragment = currentURL;
     currentUrlWithoutFragment.setFragment(QString());
     QUrl newUrlWithoutFragment = currentURL.resolved(url);
     newUrlWithoutFragment.setFragment(QString());
     if (url.isValid()
         && (newUrlWithoutFragment != currentUrlWithoutFragment || forceLoadOnSourceChange)) {
         QVariant data = q->loadResource(QTextDocument::HtmlResource, resolveUrl(url));
         if (data.type() == QVariant::String) {
             txt = data.toString();
         } else if (data.type() == QVariant::ByteArray) {
 #ifndef QT_NO_TEXTCODEC
             QByteArray ba = data.toByteArray();
             QTextCodec *codec = Qt::codecForHtml(ba);
             txt = codec->toUnicode(ba);
 #else
         txt = data.toString();
 #endif
         }
         if (txt.isEmpty())
             qWarning("QTextBrowser: No document for %s", url.toString().toLatin1().constData());
         if (q->isVisible()) {
             QString firstTag = txt.left(txt.indexOf(QLatin1Char('>')) + 1);
             if (firstTag.startsWith(QLatin1String("<qt")) && firstTag.contains(QLatin1String("type")) && firstTag.contains(QLatin1String("detail"))) {
 #ifndef QT_NO_CURSOR
                 QApplication::restoreOverrideCursor();
 #endif
 #ifndef QT_NO_WHATSTHIS
                 QWhatsThis::showText(QCursor::pos(), txt, q);
 #endif
                 return;
             }
         }
         currentURL = resolveUrl(url);
         doSetText = true;
     }
     if (!home.isValid())
         home = url;
     if (doSetText) {
 #ifndef QT_NO_TEXTHTMLPARSER
         q->QTextEdit::setHtml(txt);
         q->document()->setMetaInformation(QTextDocument::DocumentUrl, currentURL.toString());
 #else
         q->QTextEdit::setPlainText(txt);
 #endif
 #ifdef QT_KEYPAD_NAVIGATION
         prevFocus.movePosition(QTextCursor::Start);
 #endif
     }
     forceLoadOnSourceChange = false;
     if (!url.fragment().isEmpty()) {
         q->scrollToAnchor(url.fragment());
     } else {
         hbar->setValue(0);
         vbar->setValue(0);
     }
 #ifdef QT_KEYPAD_NAVIGATION
     lastKeypadScrollValue = vbar->value();
     emit q->highlighted(QUrl());
     emit q->highlighted(QString());
 #endif
 #ifndef QT_NO_CURSOR
     if (q->isVisible())
         QApplication::restoreOverrideCursor();
 #endif
     emit q->sourceChanged(url);
 }
Properties
currentURL
QUrl QTextBrowserPrivate::currentURL
Definition at line 109 of file qtextbrowser.cpp.
Referenced by _q_activateAnchor(), resolveUrl(), and setSource().
forceLoadOnSourceChange
bool QTextBrowserPrivate::forceLoadOnSourceChange
Definition at line 117 of file qtextbrowser.cpp.
Referenced by setSource().
forwardStack
QStack<HistoryEntry> QTextBrowserPrivate::forwardStack
Definition at line 107 of file qtextbrowser.cpp.
Referenced by history().
home
QUrl QTextBrowserPrivate::home
Definition at line 108 of file qtextbrowser.cpp.
Referenced by setSource().
oldCursor
QCursor QTextBrowserPrivate::oldCursor
Definition at line 123 of file qtextbrowser.cpp.
Referenced by _q_activateAnchor(), _q_highlightLink(), and init().
openExternalLinks
bool QTextBrowserPrivate::openExternalLinks
Definition at line 119 of file qtextbrowser.cpp.
Referenced by _q_activateAnchor().
openLinks
bool QTextBrowserPrivate::openLinks
Definition at line 120 of file qtextbrowser.cpp.
Referenced by _q_activateAnchor().
searchPaths
QStringList QTextBrowserPrivate::searchPaths
Definition at line 111 of file qtextbrowser.cpp.
Referenced by findFile().
stack
QStack<HistoryEntry> QTextBrowserPrivate::stack
Definition at line 106 of file qtextbrowser.cpp.
Referenced by history().
textOrSourceChanged
bool QTextBrowserPrivate::textOrSourceChanged
Definition at line 116 of file qtextbrowser.cpp.
Referenced by _q_activateAnchor(), and setSource().
The documentation for this class was generated from the following file:
/src/gui/widgets/qtextbrowser.cpp