Qt 4.8: QCommandLinkButtonPrivate Class Reference
QCommandLinkButtonPrivate Class Reference
Public Functions
int bottomMargin () const
QFont descriptionFont () const
int descriptionHeight (int width) const
int descriptionOffset () const
QRect descriptionRect () const
void init ()
int leftMargin () const
QColor mergedColors (const QColor &a, const QColor &b, int value) const
QCommandLinkButtonPrivate ()
int rightMargin () const
int textOffset () const
QFont titleFont () const
QRect titleRect () const
qreal titleSize () const
int topMargin () const
bool usingVistaStyle () const
Public Functions inherited from QPushButtonPrivate
void _q_popupPressed ()
QPoint adjustedMenuPosition ()
QDialog * dialogParent () const
bool hitButton (const QPoint &pos)
void init ()
QPushButtonPrivate ()
void resetLayoutItemMargins ()
Public Functions inherited from QAbstractButtonPrivate
void click ()
void emitClicked ()
void emitPressed ()
void emitReleased ()
void fixFocusPolicy ()
void init ()
void moveFocus (int key)
void notifyChecked ()
QAbstractButtonPrivate (QSizePolicy::ControlType type=QSizePolicy::DefaultType)
QList< QAbstractButton * > queryButtonList () const
QAbstractButton * queryCheckedButton () const
void refresh ()
Public Functions inherited from QWidgetPrivate
void _q_showIfNotHidden ()
virtual void aboutToDestroy ()
void activateChildLayoutsRecursively ()
QSize adjustedSize () const
void adjustQuitOnCloseAttribute ()
QInputContext * assignedInputContext () const
QPainter * beginSharedPainter ()
QWidget * childAt_helper (const QPoint &, bool) const
QWidget * childAtRecursiveHelper (const QPoint &p, bool, bool includeFrame=false) const
QRect clipRect () const
QRegion clipRegion () const
void clipToEffectiveMask (QRegion &region) const
bool close_helper (CloseMode mode)
void create_sys (WId window, bool initializeWindow, bool destroyOldWindow)
QWindowSurface * createDefaultWindowSurface ()
QWindowSurface * createDefaultWindowSurface_sys ()
void createExtra ()
Creates the widget extra data.
void createRecursively ()
void createSysExtra ()
void createTLExtra ()
void createTLSysExtra ()
void createWinId (WId id=0)
void deactivateWidgetCleanup ()
void deleteExtra ()
Deletes the widget extra data.
void deleteSysExtra ()
void deleteTLSysExtra ()
void drawWidget (QPaintDevice *pdev, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter=0, QWidgetBackingStore *backingStore=0)
QWidget * effectiveFocusWidget ()
QRect effectiveRectFor (const QRect &rect) const
bool endSharedPainter ()
void enforceNativeChildren ()
QWExtra * extraData () const
QRect frameStrut () const
void getLayoutItemMargins (int *left, int *top, int *right, int *bottom) const
const QRegion & getOpaqueChildren () const
void handleSoftwareInputPanel (Qt::MouseButton button, bool clickCausedFocus)
virtual bool hasHeightForWidth () const
void hide_helper ()
void hide_sys ()
Platform-specific part of QWidget::hide().
void hideChildren (bool spontaneous)
void inheritStyle ()
void init (QWidget *desktopWidget, Qt::WindowFlags f)
QInputContext * inputContext () const
void invalidateBuffer (const QRegion &)
Invalidates the rgn (in widget's coordinates) of the backing store, i.e.
void invalidateBuffer (const QRect &)
This function is equivalent to calling invalidateBuffer(QRegion(rect), ...), but is more efficient as it eliminates QRegion operations/allocations and can use the rect more precisely for additional cut-offs.
void invalidateBuffer_resizeHelper (const QPoint &oldPos, const QSize &oldSize)
Invalidates the buffer when the widget is resized.
void invalidateGraphicsEffectsRecursively ()
bool isAboutToShow () const
bool isBackgroundInherited () const
bool isOverlapped (const QRect &) const
void lower_sys ()
QPoint mapFromGlobal (const QPoint &pos) const
QPoint mapToGlobal (const QPoint &pos) const
QWidgetBackingStore * maybeBackingStore () const
QTLWExtra * maybeTopData () const
void moveRect (const QRect &, int dx, int dy)
bool nativeChildrenForced () const
QFont naturalWidgetFont (uint inheritedMask) const
QPalette naturalWidgetPalette (uint inheritedMask) const
Returns the palette that the widget w inherits from its ancestors and QApplication::palette.
void paintBackground (QPainter *, const QRegion &, int flags=DrawAsRoot) const
bool paintOnScreen () const
void paintSiblingsRecursive (QPaintDevice *pdev, const QObjectList &children, int index, const QRegion &rgn, const QPoint &offset, int flags, QPainter *sharedPainter, QWidgetBackingStore *backingStore)
bool pointInsideRectAndMask (const QPoint &) const
QRegion prepareToRender (const QRegion &region, QWidget::RenderFlags renderFlags)
void propagatePaletteChange ()
Propagate this widget's palette to all children, except style sheet widgets, and windows that don't enable window propagation (palettes don't normally propagate to windows).
QWidgetPrivate (int version=QObjectPrivateVersion)
void raise_sys ()
QPaintDevice * redirected (QPoint *offset) const
void registerDropSite (bool)
void render (QPaintDevice *target, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags, bool readyToRender)
void render_helper (QPainter *painter, const QPoint &targetOffset, const QRegion &sourceRegion, QWidget::RenderFlags renderFlags)
void repaint_sys (const QRegion &rgn)
void reparentFocusWidgets (QWidget *oldtlw)
void resolveFont ()
Determine which font is implicitly imposed on this widget by its ancestors and QApplication::font, resolve this against its own font (attributes from the implicit font are copied over).
void resolveLayoutDirection ()
void resolveLocale ()
void resolvePalette ()
Determine which palette is inherited from this widget's ancestors and QApplication::palette, resolve this against this widget's palette (attributes from the inherited palette are copied over this widget's palette).
void restoreRedirected ()
void scroll_sys (int dx, int dy)
void scroll_sys (int dx, int dy, const QRect &r)
void scrollChildren (int dx, int dy)
void scrollRect (const QRect &, int dx, int dy)
void sendPendingMoveAndResizeEvents (bool recursive=false, bool disableUpdates=false)
void sendStartupMessage (const char *message) const
Platform-specific part of QWidget::show().
void setConstraints_sys ()
void setCursor_sys (const QCursor &cursor)
void setDirtyOpaqueRegion ()
void setEnabled_helper (bool)
void setFocus_sys ()
void setFont_helper (const QFont &font)
void setGeometry_sys (int, int, int, int, bool)
void setLayoutDirection_helper (Qt::LayoutDirection)
void setLayoutItemMargins (int left, int top, int right, int bottom)
void setLayoutItemMargins (QStyle::SubElement element, const QStyleOption *opt=0)
void setLocale_helper (const QLocale &l, bool forceUpdate=false)
void setMask_sys (const QRegion &)
bool setMaximumSize_helper (int &maxw, int &maxh)
bool setMinimumSize_helper (int &minw, int &minh)
void setModal_sys ()
void setNetWmWindowTypes ()
void setOpaque (bool opaque)
void setPalette_helper (const QPalette &)
void setParent_sys (QWidget *parent, Qt::WindowFlags)
void setRedirected (QPaintDevice *replacement, const QPoint &offset)
void setSharedPainter (QPainter *painter)
void setStyle_helper (QStyle *newStyle, bool propagate, bool metalHack=false)
void setUpdatesEnabled_helper (bool)
void setWindowFilePath_helper (const QString &filePath)
void setWindowIcon_helper ()
void setWindowIcon_sys (bool forceReset=false)
void setWindowIconText_helper (const QString &cap)
void setWindowIconText_sys (const QString &cap)
void setWindowOpacity_sys (qreal opacity)
void setWindowRole ()
void setWindowTitle_helper (const QString &cap)
void setWindowTitle_sys (const QString &cap)
void setWinId (WId)
QPainter * sharedPainter () const
void show_helper ()
void show_recursive ()
Makes the widget visible in the isVisible() meaning of the word.
void show_sys ()
Platform-specific part of QWidget::show().
void showChildren (bool spontaneous)
void stackUnder_sys (QWidget *)
void subtractOpaqueChildren (QRegion &rgn, const QRect &clipRect) const
void subtractOpaqueSiblings (QRegion &source, bool *hasDirtySiblingsAbove=0, bool alsoNonOpaque=false) const
void syncBackingStore ()
void syncBackingStore (const QRegion &region)
QTLWExtra * topData () const
void unsetCursor_sys ()
void updateFont (const QFont &)
Assign font to this widget, and propagate it to all children, except style sheet widgets (handled differently) and windows that don't enable window propagation.
void updateFrameStrut ()
Computes the frame rectangle when needed.
void updateGeometry_helper (bool forceUpdate)
void updateIsOpaque ()
void updateIsTranslucent ()
void updateSystemBackground ()
void updateX11AcceptFocus ()
void x11UpdateIsOpaque ()
~QWidgetPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
QColor currentColor
QString description
Public Variables inherited from QPushButtonPrivate
uint autoDefault: 2
uint defaultButton: 1
uint flat: 1
uint lastAutoDefault: 1
QPointer< QMenu > menu
uint menuOpen: 1
Public Variables inherited from QAbstractButtonPrivate
QBasicTimer animateTimer
uint autoExclusive:1
uint autoRepeat:1
int autoRepeatDelay
int autoRepeatInterval
uint blockRefresh:1
uint checkable:1
uint checked:1
QSizePolicy::ControlType controlType
uint down:1
QButtonGroup * group
QIcon icon
QSize iconSize
uint pressed: 1
QBasicTimer repeatTimer
QKeySequence shortcut
int shortcutId
QSize sizeHint
QString text
Public Variables inherited from QWidgetPrivate
QString accessibleDescription
QString accessibleName
QList< QAction * > actions
QPalette::ColorRole bg_role: 8
signed char bottomLayoutItemMargin
short bottommargin
QWidgetData data
QRegion dirty
uint dirtyOpaqueChildren: 1
QWExtra * extra
QPaintEngine * extraPaintEngine
QPalette::ColorRole fg_role: 8
QWidget * focus_child
QWidget * focus_next
QWidget * focus_prev
QMap< Qt::GestureType, Qt::GestureFlags > gestureContext
QGraphicsEffect * graphicsEffect
Qt::HANDLE hd
uint high_attributes [4]
QPointer< QInputContext > ic
Qt::InputMethodHints imHints
uint inDirtyList: 1
uint inheritedFontResolveMask
uint inheritedPaletteResolveMask
uint inheritsInputMethodHints: 1
uint inSetParent: 1
uint isGLWidget: 1
uint isMoved: 1
uint isOpaque: 1
uint isScrolled: 1
QLayout * layout
signed char leftLayoutItemMargin
short leftmargin
QLocale locale
QRegion * needsFlush
QRegion opaqueChildren
Qt::HANDLE picture
const QMetaObject * polished
QPaintDevice * redirectDev
QPoint redirectOffset
signed char rightLayoutItemMargin
short rightmargin
QSizePolicy size_policy
QString statusTip
QString toolTip
signed char topLayoutItemMargin
short topmargin
uint usesDoubleBufferedGLContext: 1
QString whatsThis
QWidgetItemV2 * widgetItem
QX11Info xinfo
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QPushButtonPrivate
enum AutoDefaultValue { Off = 0, On = 1, Auto = 2 }
Public Types inherited from QWidgetPrivate
enum CloseMode { CloseNoEvent, CloseWithEvent, CloseWithSpontaneousEvent }
enum Direction { DirectionNorth = 0x01, DirectionEast = 0x10, DirectionSouth = 0x02, DirectionWest = 0x20 }
enum DrawWidgetFlags {
DrawAsRoot = 0x01, DrawPaintOnScreen = 0x02, DrawRecursive = 0x04, DrawInvisible = 0x08,
DontSubtractOpaqueChildren = 0x10, DontSetCompositionMode = 0x20, DontDrawOpaqueChildren = 0x40, DontDrawNativeChildren = 0x80
}
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QPushButtonPrivate
static QPushButtonPrivate * get (QPushButton *b)
Static Public Functions inherited from QWidgetPrivate
static void adjustFlags (Qt::WindowFlags &flags, QWidget *w=0)
static QGraphicsProxyWidget * nearestGraphicsProxyWidget (const QWidget *origin)
Finds the nearest widget embedded in a graphics proxy widget along the chain formed by this widget and its ancestors.
static int pointToRect (const QPoint &p, const QRect &r)
static QRect screenGeometry (const QWidget *widget)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Static Public Variables inherited from QWidgetPrivate
static QWidgetSet * allWidgets = 0
static int instanceCounter = 0
static QWidget * keyboardGrabber = 0
static QWidgetMapper * mapper = 0
static int maxInstances = 0
static QWidget * mouseGrabber = 0
Detailed Description
Definition at line 104 of file qcommandlinkbutton.cpp.
Constructors and Destructors
QCommandLinkButtonPrivate()
QCommandLinkButtonPrivate::QCommandLinkButtonPrivate () inline
Definition at line 109 of file qcommandlinkbutton.cpp.
         : QPushButtonPrivate(){}
Functions
bottomMargin()
int QCommandLinkButtonPrivate::bottomMargin () const inline
Definition at line 130 of file qcommandlinkbutton.cpp.
Referenced by descriptionRect().
 { return 10; }
descriptionFont()
QFont QCommandLinkButtonPrivate::descriptionFont () const
Definition at line 168 of file qcommandlinkbutton.cpp.
Referenced by descriptionHeight(), and QCommandLinkButtonPrivate().
 {
     Q_Q(const QCommandLinkButton);
     QFont font = q->font();
     font.setPointSizeF(9.0);
     // Note the font will be resolved against
     // QPainters font, so we need to restore the mask
     int resolve_mask = font.resolve_mask;
     QFont modifiedFont = q->font().resolve(font);
     modifiedFont.detach();
     modifiedFont.resolve_mask = resolve_mask;
     return modifiedFont;
 }
descriptionHeight()
int QCommandLinkButtonPrivate::descriptionHeight (int width) const
Definition at line 242 of file qcommandlinkbutton.cpp.
Referenced by QCommandLinkButtonPrivate().
 {
     // Calc width of actual paragraph
     int lineWidth = widgetWidth - textOffset() - rightMargin();
     qreal descriptionheight = 0;
     if (!description.isEmpty()) {
         QTextLayout layout(description);
         layout.setFont(descriptionFont());
         layout.beginLayout();
         while (true) {
             QTextLine line = layout.createLine();
             if (!line.isValid())
                 break;
             line.setLineWidth(lineWidth);
             line.setPosition(QPointF(0, descriptionheight));
             descriptionheight += line.height();
         }
         layout.endLayout();
     }
     return qCeil(descriptionheight);
 }
descriptionOffset()
int QCommandLinkButtonPrivate::descriptionOffset () const
Definition at line 210 of file qcommandlinkbutton.cpp.
Referenced by descriptionRect(), and QCommandLinkButtonPrivate().
 {
     QFontMetrics fm(titleFont());
     return topMargin() + fm.height();
 }
descriptionRect()
QRect QCommandLinkButtonPrivate::descriptionRect () const
Definition at line 197 of file qcommandlinkbutton.cpp.
Referenced by QCommandLinkButtonPrivate().
 {
     Q_Q(const QCommandLinkButton);
     return q->rect().adjusted(textOffset(), descriptionOffset(),
                               -rightMargin(), -bottomMargin());
 }
init()
void QCommandLinkButtonPrivate::init ()
Definition at line 225 of file qcommandlinkbutton.cpp.
Referenced by QCommandLinkButtonPrivate().
 {
     Q_Q(QCommandLinkButton);
     QPushButtonPrivate::init();
     q->setAttribute(Qt::WA_Hover);
     QSizePolicy policy(QSizePolicy::Preferred, QSizePolicy::Preferred, QSizePolicy::PushButton);
     policy.setHeightForWidth(true);
     q->setSizePolicy(policy);
     q->setIconSize(QSize(20, 20));
     QStyleOptionButton opt;
     q->initStyleOption(&opt);
     q->setIcon(q->style()->standardIcon(QStyle::SP_CommandLink, &opt));
 }
leftMargin()
int QCommandLinkButtonPrivate::leftMargin () const inline
Definition at line 128 of file qcommandlinkbutton.cpp.
Referenced by textOffset().
 { return 7; }
mergedColors()
QColor QCommandLinkButtonPrivate::mergedColors (const QColor & a, const QColor & b, int value = 50) const
Definition at line 137 of file qcommandlinkbutton.cpp.
Referenced by QCommandLinkButtonPrivate().
 {
     Q_ASSERT(value >= 0);
     Q_ASSERT(value <= 255);
     QColor tmp = a;
     tmp.setRed((tmp.red() * value) / 255 + (b.red() * (255 - value)) / 255);
     tmp.setGreen((tmp.green() * value) / 255 + (b.green() * (255 - value)) / 255);
     tmp.setBlue((tmp.blue() * value) / 255 + (b.blue() * (255 - value)) / 255);
     return tmp;
 }
rightMargin()
int QCommandLinkButtonPrivate::rightMargin () const inline
Definition at line 129 of file qcommandlinkbutton.cpp.
Referenced by descriptionHeight(), descriptionRect(), and titleRect().
 { return 4; }
textOffset()
int QCommandLinkButtonPrivate::textOffset () const
Definition at line 204 of file qcommandlinkbutton.cpp.
Referenced by descriptionHeight(), descriptionRect(), QCommandLinkButtonPrivate(), and titleRect().
 {
     Q_Q(const QCommandLinkButton);
     return q->icon().actualSize(q->iconSize()).width() + leftMargin() + 6;
 }
titleFont()
QFont QCommandLinkButtonPrivate::titleFont () const
Definition at line 148 of file qcommandlinkbutton.cpp.
Referenced by descriptionOffset(), QCommandLinkButtonPrivate(), and titleRect().
 {
     Q_Q(const QCommandLinkButton);
     QFont font = q->font();
     if (usingVistaStyle()) {
         font.setPointSizeF(12.0);
     } else {
         font.setBold(true);
         font.setPointSizeF(9.0);
     }
     // Note the font will be resolved against
     // QPainters font, so we need to restore the mask
     int resolve_mask = font.resolve_mask;
     QFont modifiedFont = q->font().resolve(font);
     modifiedFont.detach();
     modifiedFont.resolve_mask = resolve_mask;
     return modifiedFont;
 }
titleRect()
QRect QCommandLinkButtonPrivate::titleRect () const
Definition at line 183 of file qcommandlinkbutton.cpp.
Referenced by QCommandLinkButtonPrivate().
 {
     Q_Q(const QCommandLinkButton);
     QRect r = q->rect().adjusted(textOffset(), topMargin(), -rightMargin(), 0);
     if (description.isEmpty())
     {
         QFontMetrics fm(titleFont());
         r.setTop(r.top() + qMax(0, (q->icon().actualSize(q->iconSize()).height()
                  - fm.height()) / 2));
     }
     return r;
 }
titleSize()
qreal QCommandLinkButtonPrivate::titleSize () const
Referenced by QCommandLinkButtonPrivate().
topMargin()
int QCommandLinkButtonPrivate::topMargin () const inline
Definition at line 127 of file qcommandlinkbutton.cpp.
Referenced by descriptionOffset(), and titleRect().
 { return 10; }
usingVistaStyle()
bool QCommandLinkButtonPrivate::usingVistaStyle () const
Definition at line 216 of file qcommandlinkbutton.cpp.
Referenced by QCommandLinkButtonPrivate(), and titleFont().
 {
     Q_Q(const QCommandLinkButton);
     //### This is a hack to detect if we are indeed running Vista style themed and not in classic
     // When we add api to query for this, we should change this implementation to use it.
     return q->style()->inherits("QWindowsVistaStyle")
         && !q->style()->pixelMetric(QStyle::PM_ButtonShiftHorizontal);
 }
Properties
currentColor
QColor QCommandLinkButtonPrivate::currentColor
Definition at line 133 of file qcommandlinkbutton.cpp.
description
QString QCommandLinkButtonPrivate::description
Definition at line 132 of file qcommandlinkbutton.cpp.
Referenced by descriptionHeight(), and titleRect().
The documentation for this class was generated from the following file:
/src/gui/widgets/qcommandlinkbutton.cpp