Qt 4.8: QDirModelPrivate Class Reference
QDirModelPrivate Class Reference
Classes
struct QDirNode
struct SavedPersistent
Public Functions
void _q_refresh ()
void appendChild (QDirModelPrivate::QDirNode *parent, const QString &path) const
QVector< QDirNode > children (QDirNode *parent, bool stat) const
void clear (QDirNode *parent) const
QFileInfoList entryInfoList (const QString &path) const
QStringList entryList (const QString &path) const
void init ()
void invalidate ()
QString name (const QModelIndex &index) const
QDirNode * node (int row, QDirNode *parent) const
QDirNode * node (const QModelIndex &index) const
void populate (QDirNode *parent) const
QDirModelPrivate ()
void restorePersistentIndexes ()
void savePersistentIndexes ()
QString size (const QModelIndex &index) const
QString time (const QModelIndex &index) const
QString type (const QModelIndex &index) const
Public Functions inherited from QAbstractItemModelPrivate
bool allowMove (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
Returns whether a move operation is valid.
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void columnsInserted (const QModelIndex &parent, int first, int last)
void columnsRemoved (const QModelIndex &parent, int first, int last)
QModelIndex createIndex (int row, int column, void *data=0) const
QModelIndex createIndex (int row, int column, int id) const
bool indexValid (const QModelIndex &index) const
void invalidatePersistentIndex (const QModelIndex &index)
void invalidatePersistentIndexes ()
void itemsAboutToBeMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation)
void itemsMoved (const QModelIndex &srcParent, int srcFirst, int srcLast, const QModelIndex &destinationParent, int destinationChild, Qt::Orientation orientation)
void movePersistentIndexes (QVector< QPersistentModelIndexData *> indexes, int change, const QModelIndex &parent, Qt::Orientation orientation)
Moves persistent indexes indexes by amount change.
QAbstractItemModelPrivate ()
void removePersistentIndexData (QPersistentModelIndexData *data)
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
void rowsInserted (const QModelIndex &parent, int first, int last)
void rowsRemoved (const QModelIndex &parent, int first, int last)
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Static Public Functions
static QFileInfo resolvedInfo (QFileInfo info)
Static Public Functions inherited from QAbstractItemModelPrivate
static const QHash< int, QByteArray > & defaultRoleNames ()
static QAbstractItemModel * staticEmptyModel ()
static bool variantLessThan (const QVariant &v1, const QVariant &v2)
This function is used by our Q{Tree,Widget,Table}WidgetModel classes to sort.
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Public Variables
bool allowAppendChild
QFileIconProvider defaultProvider
QDir::Filters filters
QFileIconProvider * iconProvider
bool lazyChildCount
QStringList nameFilters
bool readOnly
bool resolveSymlinks
QDirNode root
QList< SavedPersistent > savedPersistent
bool shouldStat
QDir::SortFlags sort
QPersistentModelIndex toBeRefreshed
Public Variables inherited from QAbstractItemModelPrivate
QStack< Change > changes
struct QAbstractItemModelPrivate::Persistent persistent
QHash< int, QByteArray > roleNames
Qt::DropActions supportedDragActions
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Detailed Description
Definition at line 69 of file qdirmodel.cpp.
Constructors and Destructors
QDirModelPrivate()
QDirModelPrivate::QDirModelPrivate () inline
Definition at line 86 of file qdirmodel.cpp.
         : resolveSymlinks(true),
           readOnly(true),
           lazyChildCount(false),
           allowAppendChild(true),
           iconProvider(&defaultProvider),
           shouldStat(true) // ### This is set to false by QFileDialog
     { }
Functions
_q_refresh()
void QDirModelPrivate::_q_refresh ()
Definition at line 1250 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     Q_Q(QDirModel);
     q->refresh(toBeRefreshed);
     toBeRefreshed = QModelIndex();
 }
appendChild()
void QDirModelPrivate::appendChild (QDirModelPrivate::QDirNode * parent, const QString & path) const
Definition at line 1374 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     QDirModelPrivate::QDirNode node;
     node.populated = false;
     node.stat = shouldStat;
     node.parent = (parent == &root ? 0 : parent);
     node.info = QFileInfo(path);
     node.info.setCaching(true);
     // The following append(node) may reallocate the vector, thus
     // we need to update the pointers to the childnodes parent.
     QDirModelPrivate *that = const_cast<QDirModelPrivate *>(this);
     that->savePersistentIndexes();
     parent->children.append(node);
     for (int i = 0; i < parent->children.count(); ++i) {
         QDirNode *childNode = &parent->children[i];
         for (int j = 0; j < childNode->children.count(); ++j)
             childNode->children[j].parent = childNode;
     }
     that->restorePersistentIndexes();
 }
children()
QVector< QDirModelPrivate::QDirNode > QDirModelPrivate::children (QDirNode * parent, bool stat) const
Definition at line 1213 of file qdirmodel.cpp.
 {
     Q_ASSERT(parent);
     QFileInfoList infoList;
     if (parent == &root) {
         parent = 0;
         infoList = QDir::drives();
     } else if (parent->info.isDir()) {
         //resolve directory links only if requested.
         if (parent->info.isSymLink() && resolveSymlinks) {
             QString link = parent->info.symLinkTarget();
             if (link.size() > 1 && link.at(link.size() - 1) == QDir::separator())
                 link.chop(1);
             if (stat)
                 infoList = entryInfoList(link);
             else
                 infoList = QDir(link).entryInfoList(nameFilters, QDir::AllEntries | QDir::System);
         } else {
             if (stat)
                 infoList = entryInfoList(parent->info.absoluteFilePath());
             else
                 infoList = QDir(parent->info.absoluteFilePath()).entryInfoList(nameFilters, QDir::AllEntries | QDir::System);
         }
     }
     QVector<QDirNode> nodes(infoList.count());
     for (int i = 0; i < infoList.count(); ++i) {
         QDirNode &node = nodes[i];
         node.parent = parent;
         node.info = infoList.at(i);
         node.populated = false;
         node.stat = shouldStat;
     }
     return nodes;
 }
clear()
void QDirModelPrivate::clear (QDirNode * parent) const inline
Definition at line 166 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
      Q_ASSERT(parent);
      parent->children.clear();
      parent->populated = false;
 }
entryInfoList()
QFileInfoList QDirModelPrivate::entryInfoList (const QString & path) const
Definition at line 1295 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     const QDir dir(path);
     return dir.entryInfoList(nameFilters, filters, sort);
 }
entryList()
QStringList QDirModelPrivate::entryList (const QString & path) const
Definition at line 1301 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     const QDir dir(path);
     return dir.entryList(nameFilters, filters, sort);
 }
init()
void QDirModelPrivate::init ()
Definition at line 1179 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     Q_Q(QDirModel);
     filters = QDir::AllEntries | QDir::NoDotAndDotDot;
     sort = QDir::Name;
     nameFilters << QLatin1String("*");
     root.parent = 0;
     root.info = QFileInfo();
     clear(&root);
     QHash<int, QByteArray> roles = q->roleNames();
     roles.insertMulti(QDirModel::FileIconRole, "fileIcon"); // == Qt::decoration
     roles.insert(QDirModel::FilePathRole, "filePath");
     roles.insert(QDirModel::FileNameRole, "fileName");
     q->setRoleNames(roles);
 }
invalidate()
void QDirModelPrivate::invalidate ()
Definition at line 173 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     QStack<const QDirNode*> nodes;
     nodes.push(&root);
     while (!nodes.empty()) {
         const QDirNode *current = nodes.pop();
         current->stat = false;
         const QVector<QDirNode> children = current->children;
         for (int i = 0; i < children.count(); ++i)
             nodes.push(&children.at(i));
     }
 }
name()
QString QDirModelPrivate::name (const QModelIndex & index) const
Definition at line 1307 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     const QDirNode *n = node(index);
     const QFileInfo info = n->info;
     if (info.isRoot()) {
         QString name = info.absoluteFilePath();
 #if defined(Q_OS_WIN) && !defined(Q_OS_WINCE)
         if (name.startsWith(QLatin1Char('/'))) // UNC host
             return info.fileName();
 #endif
 #if (defined(Q_OS_WIN) && !defined(Q_OS_WINCE)) || defined(Q_OS_SYMBIAN)
         if (name.endsWith(QLatin1Char('/')))
             name.chop(1);
 #endif
         return name;
     }
     return info.fileName();
 }
node() [1/2]
QDirModelPrivate::QDirNode * QDirModelPrivate::node (int row, QDirNode * parent) const
Definition at line 1195 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     if (row < 0)
     return 0;
     bool isDir = !parent || parent->info.isDir();
     QDirNode *p = (parent ? parent : &root);
     if (isDir && !p->populated)
         populate(p); // will also resolve symlinks
     if (row >= p->children.count()) {
         qWarning("node: the row does not exist");
         return 0;
     }
     return const_cast<QDirNode*>(&p->children.at(row));
 }
node() [2/2]
QDirModelPrivate::QDirNode * QDirModelPrivate::node (const QModelIndex & index) const inline
Definition at line 151 of file qdirmodel.cpp.
 {
     QDirModelPrivate::QDirNode *n =
         static_cast<QDirModelPrivate::QDirNode*>(index.internalPointer());
     Q_ASSERT(n);
     return n;
 }
populate()
void QDirModelPrivate::populate (QDirNode * parent) const inline
Definition at line 159 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     Q_ASSERT(parent);
     parent->children = children(parent, parent->stat);
     parent->populated = true;
 }
resolvedInfo()
QFileInfo QDirModelPrivate::resolvedInfo (QFileInfo info) static
Definition at line 1396 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
 #ifdef Q_OS_WIN
     // On windows, we cannot create a shortcut to a shortcut.
     return QFileInfo(info.symLinkTarget());
 #else
     QStringList paths;
     do {
         QFileInfo link(info.symLinkTarget());
         if (link.isRelative())
             info.setFile(info.absolutePath(), link.filePath());
         else
             info = link;
         if (paths.contains(info.absoluteFilePath()))
             return QFileInfo();
         paths.append(info.absoluteFilePath());
     } while (info.isSymLink());
     return info;
 #endif
 }
restorePersistentIndexes()
void QDirModelPrivate::restorePersistentIndexes ()
Definition at line 1272 of file qdirmodel.cpp.
Referenced by appendChild(), and QDirModelPrivate().
 {
     Q_Q(QDirModel);
     bool allow = allowAppendChild;
     allowAppendChild = false;
     for (int i = 0; i < savedPersistent.count(); ++i) {
         QPersistentModelIndexData *data = savedPersistent.at(i).data;
         QString path = savedPersistent.at(i).path;
         int column = savedPersistent.at(i).column;
         QModelIndex idx = q->index(path, column);
         if (idx != data->index || data->model == 0) {
             //data->model may be equal to 0 if the model is getting destroyed
             persistent.indexes.remove(data->index);
             data->index = idx;
             data->model = q;
             if (idx.isValid())
                 persistent.indexes.insert(idx, data);
         }
     }
     savedPersistent.clear();
     allowAppendChild = allow;
 }
savePersistentIndexes()
void QDirModelPrivate::savePersistentIndexes ()
Definition at line 1257 of file qdirmodel.cpp.
Referenced by appendChild(), and QDirModelPrivate().
 {
     Q_Q(QDirModel);
     savedPersistent.clear();
     foreach (QPersistentModelIndexData *data, persistent.indexes) {
         SavedPersistent saved;
         QModelIndex index = data->index;
         saved.path = q->filePath(index);
         saved.column = index.column();
         saved.data = data;
         saved.index = index;
         savedPersistent.append(saved);
     }
 }
size()
QString QDirModelPrivate::size (const QModelIndex & index) const
Definition at line 1326 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     const QDirNode *n = node(index);
     if (n->info.isDir()) {
 #ifdef Q_OS_MAC
         return QLatin1String("--");
 #else
         return QLatin1String("");
 #endif
     // Windows   - ""
     // OS X      - "--"
     // Konqueror - "4 KB"
     // Nautilus  - "9 items" (the number of children)
     }
     // According to the Si standard KB is 1000 bytes, KiB is 1024
     // but on windows sizes are calulated by dividing by 1024 so we do what they do.
     const quint64 kb = 1024;
     const quint64 mb = 1024 * kb;
     const quint64 gb = 1024 * mb;
     const quint64 tb = 1024 * gb;
     quint64 bytes = n->info.size();
     if (bytes >= tb)
         return QFileSystemModel::tr("%1 TB").arg(QLocale().toString(qreal(bytes) / tb, 'f', 3));
     if (bytes >= gb)
         return QFileSystemModel::tr("%1 GB").arg(QLocale().toString(qreal(bytes) / gb, 'f', 2));
     if (bytes >= mb)
         return QFileSystemModel::tr("%1 MB").arg(QLocale().toString(qreal(bytes) / mb, 'f', 1));
     if (bytes >= kb)
         return QFileSystemModel::tr("%1 KB").arg(QLocale().toString(bytes / kb));
     return QFileSystemModel::tr("%1 byte(s)").arg(QLocale().toString(bytes));
 }
time()
QString QDirModelPrivate::time (const QModelIndex & index) const
Definition at line 1364 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
 #ifndef QT_NO_DATESTRING
     return node(index)->info.lastModified().toString(Qt::LocalDate);
 #else
     Q_UNUSED(index);
     return QString();
 #endif
 }
type()
QString QDirModelPrivate::type (const QModelIndex & index) const
Definition at line 1359 of file qdirmodel.cpp.
Referenced by QDirModelPrivate().
 {
     return iconProvider->type(node(index)->info);
 }
Properties
allowAppendChild
bool QDirModelPrivate::allowAppendChild
Definition at line 125 of file qdirmodel.cpp.
defaultProvider
QFileIconProvider QDirModelPrivate::defaultProvider
Definition at line 132 of file qdirmodel.cpp.
filters
QDir::Filters QDirModelPrivate::filters
Definition at line 127 of file qdirmodel.cpp.
iconProvider
QFileIconProvider* QDirModelPrivate::iconProvider
Definition at line 131 of file qdirmodel.cpp.
lazyChildCount
bool QDirModelPrivate::lazyChildCount
Definition at line 124 of file qdirmodel.cpp.
nameFilters
QStringList QDirModelPrivate::nameFilters
Definition at line 129 of file qdirmodel.cpp.
readOnly
bool QDirModelPrivate::readOnly
Definition at line 123 of file qdirmodel.cpp.
resolveSymlinks
bool QDirModelPrivate::resolveSymlinks
Definition at line 122 of file qdirmodel.cpp.
root
QDirNode QDirModelPrivate::root mutable
Definition at line 121 of file qdirmodel.cpp.
Referenced by invalidate().
savedPersistent
QList<SavedPersistent> QDirModelPrivate::savedPersistent
Definition at line 140 of file qdirmodel.cpp.
shouldStat
bool QDirModelPrivate::shouldStat
Definition at line 143 of file qdirmodel.cpp.
Referenced by qt_setDirModelShouldNotStat().
sort
QDir::SortFlags QDirModelPrivate::sort
Definition at line 128 of file qdirmodel.cpp.
toBeRefreshed
QPersistentModelIndex QDirModelPrivate::toBeRefreshed
Definition at line 141 of file qdirmodel.cpp.
The documentation for this class was generated from the following file:
/src/gui/itemviews/qdirmodel.cpp