Qt 4.8: QDomDocumentPrivate Class Reference
QDomDocumentPrivate Class Reference
Public Functions
void clear ()
QDomNodePrivate * cloneNode (bool deep=true)
QDomAttrPrivate * createAttribute (const QString &name)
QDomAttrPrivate * createAttributeNS (const QString &nsURI, const QString &qName)
QDomCDATASectionPrivate * createCDATASection (const QString &data)
QDomCommentPrivate * createComment (const QString &data)
QDomDocumentFragmentPrivate * createDocumentFragment ()
QDomElementPrivate * createElement (const QString &tagName)
QDomElementPrivate * createElementNS (const QString &nsURI, const QString &qName)
QDomEntityReferencePrivate * createEntityReference (const QString &name)
QDomProcessingInstructionPrivate * createProcessingInstruction (const QString &target, const QString &data)
QDomTextPrivate * createTextNode (const QString &data)
QDomDocumentTypePrivate * doctype ()
QDomElementPrivate * documentElement ()
QDomImplementationPrivate * implementation ()
QDomNodePrivate * importNode (const QDomNodePrivate *importedNode, bool deep)
bool isDocument () const
QDomNode::NodeType nodeType () const
QDomDocumentPrivate ()
QDomDocumentPrivate (const QString &name)
QDomDocumentPrivate (QDomDocumentTypePrivate *dt)
QDomDocumentPrivate (QDomDocumentPrivate *n, bool deep)
void saveDocument (QTextStream &stream, const int indent, QDomNode::EncodingPolicy encUsed) const
bool setContent (QXmlInputSource *source, bool namespaceProcessing, QString *errorMsg, int *errorLine, int *errorColumn)
bool setContent (QXmlInputSource *source, QXmlReader *reader, QString *errorMsg, int *errorLine, int *errorColumn)
~QDomDocumentPrivate ()
Public Functions inherited from QDomNodePrivate
virtual QDomNodePrivate * appendChild (QDomNodePrivate *newChild)
virtual QDomNodePrivate * insertAfter (QDomNodePrivate *newChild, QDomNodePrivate *refChild)
virtual QDomNodePrivate * insertBefore (QDomNodePrivate *newChild, QDomNodePrivate *refChild)
virtual bool isAttr () const
virtual bool isCDATASection () const
virtual bool isCharacterData () const
virtual bool isComment () const
virtual bool isDocumentFragment () const
virtual bool isDocumentType () const
virtual bool isElement () const
virtual bool isEntity () const
virtual bool isEntityReference () const
virtual bool isNotation () const
virtual bool isProcessingInstruction () const
virtual bool isText () const
QDomNodePrivate * namedItem (const QString &name)
QString nodeName () const
QString nodeValue () const
virtual void normalize ()
QDomDocumentPrivate * ownerDocument ()
QDomNodePrivate * parent () const
QDomNodePrivate (QDomDocumentPrivate *, QDomNodePrivate *parent=0)
QDomNodePrivate (QDomNodePrivate *n, bool deep)
virtual QDomNodePrivate * removeChild (QDomNodePrivate *oldChild)
virtual QDomNodePrivate * replaceChild (QDomNodePrivate *newChild, QDomNodePrivate *oldChild)
virtual void save (QTextStream &, int, int) const
void setLocation (int lineNumber, int columnNumber)
virtual void setNodeValue (const QString &v)
void setNoParent ()
void setOwnerDocument (QDomDocumentPrivate *doc)
void setParent (QDomNodePrivate *p)
virtual ~QDomNodePrivate ()
Public Variables
QExplicitlySharedDataPointer< QDomImplementationPrivate > impl
long nodeListTime
QExplicitlySharedDataPointer< QDomDocumentTypePrivate > type
Public Variables inherited from QDomNodePrivate
int columnNumber
bool createdWithDom1Interface: 1
QDomNodePrivate * first
bool hasParent: 1
QDomNodePrivate * last
int lineNumber
QString name
QString namespaceURI
QDomNodePrivate * next
QDomNodePrivate * ownerNode
QString prefix
QDomNodePrivate * prev
QAtomicInt ref
QString value
Detailed Description
Definition at line 504 of file qdom.cpp.
Constructors and Destructors
QDomDocumentPrivate() [1/4]
QDomDocumentPrivate::QDomDocumentPrivate ()
Definition at line 6302 of file qdom.cpp.
     : QDomNodePrivate(0),
       impl(new QDomImplementationPrivate),
       nodeListTime(1)
 {
     type = new QDomDocumentTypePrivate(this, this);
     type->ref.deref();
     name = QLatin1String("#document");
 }
QDomDocumentPrivate() [2/4]
QDomDocumentPrivate::QDomDocumentPrivate (const QString & name)
Definition at line 6313 of file qdom.cpp.
     : QDomNodePrivate(0),
       impl(new QDomImplementationPrivate),
       nodeListTime(1)
 {
     type = new QDomDocumentTypePrivate(this, this);
     type->ref.deref();
     type->name = aname;
     name = QLatin1String("#document");
 }
QDomDocumentPrivate() [3/4]
QDomDocumentPrivate::QDomDocumentPrivate (QDomDocumentTypePrivate * dt)
Definition at line 6325 of file qdom.cpp.
     : QDomNodePrivate(0),
       impl(new QDomImplementationPrivate),
       nodeListTime(1)
 {
     if (dt != 0) {
         type = dt;
     } else {
         type = new QDomDocumentTypePrivate(this, this);
         type->ref.deref();
     }
     name = QLatin1String("#document");
 }
QDomDocumentPrivate() [4/4]
QDomDocumentPrivate::QDomDocumentPrivate (QDomDocumentPrivate * n, bool deep)
Definition at line 6340 of file qdom.cpp.
     : QDomNodePrivate(n, deep),
       impl(n->impl->clone()),
       nodeListTime(1)
 {
     type = static_cast<QDomDocumentTypePrivate*>(n->type->cloneNode());
     type->setParent(this);
 }
~QDomDocumentPrivate()
QDomDocumentPrivate::~QDomDocumentPrivate ()
Definition at line 6349 of file qdom.cpp.
 {
 }
Functions
clear()
void QDomDocumentPrivate::clear (void) virtual
Reimplemented from QDomNodePrivate.
Definition at line 6353 of file qdom.cpp.
 {
     impl.reset();
     type.reset();
     QDomNodePrivate::clear();
 }
cloneNode()
QDomNodePrivate * QDomDocumentPrivate::cloneNode (bool deep = true) virtual
Reimplemented from QDomNodePrivate.
Definition at line 6404 of file qdom.cpp.
 {
     QDomNodePrivate *p = new QDomDocumentPrivate(this, deep);
     // We are not interested in this node
     p->ref.deref();
     return p;
 }
createAttribute()
QDomAttrPrivate * QDomDocumentPrivate::createAttribute (const QString & name)
Definition at line 6504 of file qdom.cpp.
 {
     bool ok;
     QString fixedName = fixedXmlName(aname, &ok);
     if (!ok)
         return 0;
     QDomAttrPrivate *a = new QDomAttrPrivate(this, 0, fixedName);
     a->ref.deref();
     return a;
 }
createAttributeNS()
QDomAttrPrivate * QDomDocumentPrivate::createAttributeNS (const QString & nsURI, const QString & qName)
Definition at line 6516 of file qdom.cpp.
 {
     bool ok;
     QString fixedName = fixedXmlName(qName, &ok, true);
     if (!ok)
         return 0;
     QDomAttrPrivate *a = new QDomAttrPrivate(this, 0, nsURI, fixedName);
     a->ref.deref();
     return a;
 }
createCDATASection()
QDomCDATASectionPrivate * QDomDocumentPrivate::createCDATASection (const QString & data)
Definition at line 6476 of file qdom.cpp.
Referenced by QDomHandler::characters().
 {
     bool ok;
     QString fixedData = fixedCDataSection(data, &ok);
     if (!ok)
         return 0;
     QDomCDATASectionPrivate *c = new QDomCDATASectionPrivate(this, 0, fixedData);
     c->ref.deref();
     return c;
 }
createComment()
QDomCommentPrivate * QDomDocumentPrivate::createComment (const QString & data)
Definition at line 6464 of file qdom.cpp.
Referenced by QDomHandler::comment().
 {
     bool ok;
     QString fixedData = fixedComment(data, &ok);
     if (!ok)
         return 0;
     QDomCommentPrivate *c = new QDomCommentPrivate(this, 0, fixedData);
     c->ref.deref();
     return c;
 }
createDocumentFragment()
QDomDocumentFragmentPrivate * QDomDocumentPrivate::createDocumentFragment ()
Definition at line 6445 of file qdom.cpp.
 {
     QDomDocumentFragmentPrivate *f = new QDomDocumentFragmentPrivate(this, (QDomNodePrivate*)0);
     f->ref.deref();
     return f;
 }
createElement()
QDomElementPrivate * QDomDocumentPrivate::createElement (const QString & tagName)
Definition at line 6421 of file qdom.cpp.
Referenced by QDomHandler::startElement().
 {
     bool ok;
     QString fixedName = fixedXmlName(tagName, &ok);
     if (!ok)
         return 0;
     QDomElementPrivate *e = new QDomElementPrivate(this, 0, fixedName);
     e->ref.deref();
     return e;
 }
createElementNS()
QDomElementPrivate * QDomDocumentPrivate::createElementNS (const QString & nsURI, const QString & qName)
Definition at line 6433 of file qdom.cpp.
Referenced by QDomHandler::startElement().
 {
     bool ok;
     QString fixedName = fixedXmlName(qName, &ok, true);
     if (!ok)
         return 0;
     QDomElementPrivate *e = new QDomElementPrivate(this, 0, nsURI, fixedName);
     e->ref.deref();
     return e;
 }
createEntityReference()
QDomEntityReferencePrivate * QDomDocumentPrivate::createEntityReference (const QString & name)
Definition at line 6528 of file qdom.cpp.
Referenced by QDomHandler::characters(), and QDomHandler::skippedEntity().
 {
     bool ok;
     QString fixedName = fixedXmlName(aname, &ok);
     if (!ok)
         return 0;
     QDomEntityReferencePrivate *e = new QDomEntityReferencePrivate(this, 0, fixedName);
     e->ref.deref();
     return e;
 }
createProcessingInstruction()
QDomProcessingInstructionPrivate * QDomDocumentPrivate::createProcessingInstruction (const QString & target, const QString & data)
Definition at line 6488 of file qdom.cpp.
Referenced by QDomHandler::processingInstruction().
 {
     bool ok;
     QString fixedData = fixedPIData(data, &ok);
     if (!ok)
         return 0;
     // [17] PITarget ::= Name - (('X' | 'x') ('M' | 'm') ('L' | 'l'))
     QString fixedTarget = fixedXmlName(target, &ok);
     if (!ok)
         return 0;
     QDomProcessingInstructionPrivate *p = new QDomProcessingInstructionPrivate(this, 0, fixedTarget, fixedData);
     p->ref.deref();
     return p;
 }
createTextNode()
QDomTextPrivate * QDomDocumentPrivate::createTextNode (const QString & data)
Definition at line 6452 of file qdom.cpp.
Referenced by QDomHandler::characters().
 {
     bool ok;
     QString fixedData = fixedCharData(data, &ok);
     if (!ok)
         return 0;
     QDomTextPrivate *t = new QDomTextPrivate(this, 0, fixedData);
     t->ref.deref();
     return t;
 }
doctype()
QDomDocumentTypePrivate* QDomDocumentPrivate::doctype () inline
Definition at line 517 of file qdom.cpp.
Referenced by QDomHandler::characters(), QDomHandler::notationDecl(), QDomHandler::startDTD(), and QDomHandler::unparsedEntityDecl().
 { return type.data(); }
documentElement()
QDomElementPrivate * QDomDocumentPrivate::documentElement ()
Definition at line 6412 of file qdom.cpp.
 {
     QDomNodePrivate *p = first;
     while (p && !p->isElement())
         p = p->next;
     return static_cast<QDomElementPrivate *>(p);
 }
implementation()
QDomImplementationPrivate* QDomDocumentPrivate::implementation () inline
Definition at line 518 of file qdom.cpp.
 { return impl.data(); }
importNode()
QDomNodePrivate * QDomDocumentPrivate::importNode (const QDomNodePrivate * importedNode, bool deep)
Definition at line 6540 of file qdom.cpp.
 {
     QDomNodePrivate *node = 0;
     switch (importedNode->nodeType()) {
         case QDomNode::AttributeNode:
             node = new QDomAttrPrivate((QDomAttrPrivate*)importedNode, true);
             break;
         case QDomNode::DocumentFragmentNode:
             node = new QDomDocumentFragmentPrivate((QDomDocumentFragmentPrivate*)importedNode, deep);
             break;
         case QDomNode::ElementNode:
             node = new QDomElementPrivate((QDomElementPrivate*)importedNode, deep);
             break;
         case QDomNode::EntityNode:
             node = new QDomEntityPrivate((QDomEntityPrivate*)importedNode, deep);
             break;
         case QDomNode::EntityReferenceNode:
             node = new QDomEntityReferencePrivate((QDomEntityReferencePrivate*)importedNode, false);
             break;
         case QDomNode::NotationNode:
             node = new QDomNotationPrivate((QDomNotationPrivate*)importedNode, deep);
             break;
         case QDomNode::ProcessingInstructionNode:
             node = new QDomProcessingInstructionPrivate((QDomProcessingInstructionPrivate*)importedNode, deep);
             break;
         case QDomNode::TextNode:
             node = new QDomTextPrivate((QDomTextPrivate*)importedNode, deep);
             break;
         case QDomNode::CDATASectionNode:
             node = new QDomCDATASectionPrivate((QDomCDATASectionPrivate*)importedNode, deep);
             break;
         case QDomNode::CommentNode:
             node = new QDomCommentPrivate((QDomCommentPrivate*)importedNode, deep);
             break;
         default:
             break;
     }
     if (node) {
         node->setOwnerDocument(this);
         // The QDomNode constructor increases the refcount, so deref first to
         // keep refcount balanced.
         node->ref.deref();
     }
     return node;
 }
isDocument()
bool QDomDocumentPrivate::isDocument () const inline virtual
Reimplemented from QDomNodePrivate.
Definition at line 537 of file qdom.cpp.
 { return true; }
nodeType()
QDomNode::NodeType QDomDocumentPrivate::nodeType () const inline virtual
Reimplemented from QDomNodePrivate.
Definition at line 538 of file qdom.cpp.
 { return QDomNode::DocumentNode; }
saveDocument()
void QDomDocumentPrivate::saveDocument (QTextStream & stream, const int indent, QDomNode::EncodingPolicy encUsed) const
Definition at line 6586 of file qdom.cpp.
 {
     const QDomNodePrivate* n = first;
     if(encUsed == QDomNode::EncodingFromDocument) {
 #ifndef QT_NO_TEXTCODEC
         const QDomNodePrivate* n = first;
         QTextCodec *codec = 0;
         if (n && n->isProcessingInstruction() && n->nodeName() == QLatin1String("xml")) {
             // we have an XML declaration
             QString data = n->nodeValue();
             QRegExp encoding(QString::fromLatin1("encoding\\s*=\\s*((\"([^\"]*)\")|('([^']*)'))"));
             encoding.indexIn(data);
             QString enc = encoding.cap(3);
             if (enc.isEmpty())
                 enc = encoding.cap(5);
             if (!enc.isEmpty())
                 codec = QTextCodec::codecForName(enc.toLatin1().data());
         }
         if (!codec)
             codec = QTextCodec::codecForName("UTF-8");
         if (codec)
             s.setCodec(codec);
 #endif
         bool doc = false;
         while (n) {
             if (!doc && !(n->isProcessingInstruction() && n->nodeName() == QLatin1String("xml"))) {
                 // save doctype after XML declaration
                 type->save(s, 0, indent);
                 doc = true;
             }
             n->save(s, 0, indent);
             n = n->next;
         }
     }
     else {
         // Write out the XML declaration.
 #ifdef QT_NO_TEXTCODEC
         const QLatin1String codecName("iso-8859-1");
 #else
         const QTextCodec *const codec = s.codec();
         Q_ASSERT_X(codec, "QDomNode::save()", "A codec must be specified in the text stream.");
         const QByteArray codecName = codec->name();
 #endif
         s << "<?xml version=\"1.0\" encoding=\""
           << codecName
           << "\"?>\n";
         //  Skip the first processing instruction by name "xml", if any such exists.
         const QDomNodePrivate* startNode = n;
         // First, we try to find the PI and sets the startNode to the one appearing after it.
         while (n) {
             if(n->isProcessingInstruction() && n->nodeName() == QLatin1String("xml")) {
                 startNode = n->next;
                 break;
             }
             else
                 n = n->next;
         }
         // Now we serialize all the nodes after the faked XML declaration(the PI).
         while(startNode) {
             startNode->save(s, 0, indent);
             startNode = startNode->next;
         }
     }
 }
setContent() [1/2]
bool QDomDocumentPrivate::setContent (QXmlInputSource * source, bool namespaceProcessing, QString * errorMsg, int * errorLine, int * errorColumn)
Definition at line 6367 of file qdom.cpp.
 {
     QXmlSimpleReader reader;
     initializeReader(reader, namespaceProcessing);
     return setContent(source, &reader, errorMsg, errorLine, errorColumn);
 }
setContent() [2/2]
bool QDomDocumentPrivate::setContent (QXmlInputSource * source, QXmlReader * reader, QString * errorMsg, int * errorLine, int * errorColumn)
Definition at line 6374 of file qdom.cpp.
 {
     clear();
     impl = new QDomImplementationPrivate;
     type = new QDomDocumentTypePrivate(this, this);
     type->ref.deref();
     bool namespaceProcessing = reader->feature(QLatin1String("http://xml.org/sax/features/namespaces"))
         && !reader->feature(QLatin1String("http://xml.org/sax/features/namespace-prefixes"));
     QDomHandler hnd(this, namespaceProcessing);
     reader->setContentHandler(&hnd);
     reader->setErrorHandler(&hnd);
     reader->setLexicalHandler(&hnd);
     reader->setDeclHandler(&hnd);
     reader->setDTDHandler(&hnd);
     if (!reader->parse(source)) {
         if (errorMsg)
             *errorMsg = hnd.errorMsg;
         if (errorLine)
             *errorLine = hnd.errorLine;
         if (errorColumn)
             *errorColumn = hnd.errorColumn;
         return false;
     }
     return true;
 }
Properties
impl
QExplicitlySharedDataPointer<QDomImplementationPrivate> QDomDocumentPrivate::impl
Definition at line 542 of file qdom.cpp.
nodeListTime
long QDomDocumentPrivate::nodeListTime
Definition at line 574 of file qdom.cpp.
Referenced by QDomNodeListPrivate::createList(), QDomNodePrivate::insertAfter(), QDomNodePrivate::insertBefore(), QDomNodeListPrivate::item(), QDomNodeListPrivate::length(), QDomNodePrivate::removeChild(), and QDomNodePrivate::replaceChild().
type
QExplicitlySharedDataPointer<QDomDocumentTypePrivate> QDomDocumentPrivate::type
Definition at line 543 of file qdom.cpp.
The documentation for this class was generated from the following file:
/src/xml/dom/qdom.cpp