Qt 4.8: QMargins Class Reference
QMargins Class Reference
The QMargins class defines the four margins of a rectangle.
#include <qmargins.h>
Public Functions
int bottom () const
Returns the bottom margin.
bool isNull () const
Returns true if all margins are is 0; otherwise returns false.
int left () const
Returns the left margin.
QMargins ()
Constructs a margins object with all margins set to 0.
QMargins (int left, int top, int right, int bottom)
Constructs margins with the given left, top, right, bottom.
int right () const
Returns the right margin.
void setBottom (int bottom)
Sets the bottom margin to bottom.
void setLeft (int left)
Sets the left margin to left.
void setRight (int right)
Sets the right margin to right.
void setTop (int top)
Sets the Top margin to Top.
int top () const
Returns the top margin.
Properties
int m_bottom
int m_left
int m_right
int m_top
Friends
bool operator!= (const QMargins &, const QMargins &)
Returns true if m1 and m2 are different; otherwise returns false.
bool operator== (const QMargins &, const QMargins &)
Returns true if m1 and m2 are equal; otherwise returns false.
Detailed Description
The QMargins class defines the four margins of a rectangle.
Since
4.6
QMargin defines a set of four margins; left, top, right and bottom, that describe the size of the borders surrounding a rectangle.
The isNull() function returns true only if all margins are set to zero.
QMargin objects can be streamed as well as compared.
Definition at line 53 of file qmargins.h.
Constructors and Destructors
QMargins() [1/2]
QMargins::QMargins () inline
Constructs a margins object with all margins set to 0.
See also
isNull()
Definition at line 87 of file qmargins.h.
 { m_top = m_bottom = m_left = m_right = 0; }
QMargins() [2/2]
QMargins::QMargins (int left, int top, int right, int bottom) inline
Constructs margins with the given left, top, right, bottom.
See also
setLeft(), setRight(), setTop(), setBottom()
Definition at line 90 of file qmargins.h.
     : m_left(aleft), m_top(atop), m_right(aright), m_bottom(abottom) {}
Functions
bottom()
int QMargins::bottom () const inline
Returns the bottom margin.
Definition at line 105 of file qmargins.h.
Referenced by operator<<(), qDrawBorderPixmap(), QLayout::setContentsMargins(), QWidget::setContentsMargins(), QLineEdit::setTextMargins(), and QAbstractScrollArea::setViewportMargins().
 { return m_bottom; }
isNull()
bool QMargins::isNull () const inline
Returns true if all margins are is 0; otherwise returns false.
Definition at line 93 of file qmargins.h.
 { return m_left==0 && m_top==0 && m_right==0 && m_bottom==0; }
left()
int QMargins::left () const inline
Returns the left margin.
See also
setLeft()
Definition at line 96 of file qmargins.h.
Referenced by operator<<(), qDrawBorderPixmap(), QLayout::setContentsMargins(), QWidget::setContentsMargins(), QLineEdit::setTextMargins(), and QAbstractScrollArea::setViewportMargins().
 { return m_left; }
right()
int QMargins::right () const inline
Returns the right margin.
Definition at line 102 of file qmargins.h.
Referenced by operator<<(), qDrawBorderPixmap(), QLayout::setContentsMargins(), QWidget::setContentsMargins(), QLineEdit::setTextMargins(), and QAbstractScrollArea::setViewportMargins().
 { return m_right; }
setBottom()
void QMargins::setBottom (int bottom) inline
Sets the bottom margin to bottom.
Definition at line 118 of file qmargins.h.
 { m_bottom = abottom; }
setLeft()
void QMargins::setLeft (int left) inline
Sets the left margin to left.
Definition at line 109 of file qmargins.h.
 { m_left = aleft; }
setRight()
void QMargins::setRight (int right) inline
Sets the right margin to right.
Definition at line 115 of file qmargins.h.
 { m_right = aright; }
setTop()
void QMargins::setTop (int top) inline
Sets the Top margin to Top.
Definition at line 112 of file qmargins.h.
 { m_top = atop; }
top()
int QMargins::top () const inline
Returns the top margin.
See also
setTop()
Definition at line 99 of file qmargins.h.
Referenced by operator<<(), qDrawBorderPixmap(), QLayout::setContentsMargins(), QWidget::setContentsMargins(), QLineEdit::setTextMargins(), and QAbstractScrollArea::setViewportMargins().
 { return m_top; }
Friends and Related Functions
operator!=
bool operator!= (const QMargins & m1, const QMargins & m2) friend
Returns true if m1 and m2 are different; otherwise returns false.
Definition at line 130 of file qmargins.h.
 {
     return
             m1.m_left != m2.m_left ||
             m1.m_top != m2.m_top ||
             m1.m_right != m2.m_right ||
             m1.m_bottom != m2.m_bottom;
 }
operator==
bool operator== (const QMargins & m1, const QMargins & m2) friend
Returns true if m1 and m2 are equal; otherwise returns false.
Definition at line 121 of file qmargins.h.
 {
     return
             m1.m_left == m2.m_left &&
             m1.m_top == m2.m_top &&
             m1.m_right == m2.m_right &&
             m1.m_bottom == m2.m_bottom;
 }
Properties
m_bottom
int QMargins::m_bottom private
Definition at line 75 of file qmargins.h.
Referenced by bottom(), isNull(), operator!=(), operator==(), QMargins(), and setBottom().
m_left
int QMargins::m_left private
Definition at line 72 of file qmargins.h.
Referenced by isNull(), left(), operator!=(), operator==(), QMargins(), and setLeft().
m_right
int QMargins::m_right private
Definition at line 74 of file qmargins.h.
Referenced by isNull(), operator!=(), operator==(), QMargins(), right(), and setRight().
m_top
int QMargins::m_top private
Definition at line 73 of file qmargins.h.
Referenced by isNull(), operator!=(), operator==(), QMargins(), setTop(), and top().
The documentation for this class was generated from the following files:
/src/corelib/tools/qmargins.h
/src/corelib/tools/qmargins.cpp