Qt 4.8: QIconLoaderEngine Class Reference
QIconLoaderEngine Class Reference
#include <qiconloader_p.h>
Public Functions
QSize actualSize (const QSize &size, QIcon::Mode mode, QIcon::State state)
Returns the actual size of the icon the engine provides for the requested size, mode and state.
QIconEngineV2 * clone () const
Returns a clone of this icon engine.
void paint (QPainter *painter, const QRect &rect, QIcon::Mode mode, QIcon::State state)
Uses the given painter to paint the icon with the required mode and state into the rectangle rect.
QPixmap pixmap (const QSize &size, QIcon::Mode mode, QIcon::State state)
Returns the icon as a pixmap with the required size, mode, and state.
QIconLoaderEngine (const QString &iconName=QString())
bool read (QDataStream &in)
Reads icon engine contents from the QDataStream in.
bool write (QDataStream &out) const
Writes the contents of this engine to the QDataStream out.
~QIconLoaderEngine ()
Public Functions inherited from QIconEngineV2
QList< QSize > availableSizes (QIcon::Mode mode=QIcon::Normal, QIcon::State state=QIcon::Off)
Returns sizes of all images that are contained in the engine for the specific mode and state.
QString iconName ()
Returns the name used to create the engine, if available.
Public Functions inherited from QIconEngine
virtual void addFile (const QString &fileName, const QSize &size, QIcon::Mode mode, QIcon::State state)
Called by QIcon::addFile().
virtual void addPixmap (const QPixmap &pixmap, QIcon::Mode mode, QIcon::State state)
Called by QIcon::addPixmap().
virtual ~QIconEngine ()
Destroys the icon engine.
Private Functions
void ensureLoaded ()
QIconLoaderEngineEntry * entryForSize (const QSize &size)
bool hasIcon () const
QString key () const
Returns a key that identifies this icon engine.
QIconLoaderEngine (const QIconLoaderEngine &other)
void virtual_hook (int id, void *data)
Additional method to allow extending QIconEngineV2 without adding new virtual methods (and without breaking binary compatibility).
Properties
QThemeIconEntries m_entries
QString m_iconName
uint m_key
Friends
class QIconLoader
Additional Inherited Members
Public Types inherited from QIconEngineV2
enum IconEngineHook { AvailableSizesHook = 1, IconNameHook }
These enum values are used for virtual_hook() to allow additional queries to icon engine without breaking binary compatibility.
Detailed Description
Definition at line 112 of file qiconloader_p.h.
Constructors and Destructors
QIconLoaderEngine() [1/2]
QIconLoaderEngine::QIconLoaderEngine (const QString & iconName = QString())
Definition at line 312 of file qiconloader.cpp.
Referenced by clone().
         : m_iconName(iconName), m_key(0)
 {
 }
~QIconLoaderEngine()
QIconLoaderEngine::~QIconLoaderEngine ()
Definition at line 317 of file qiconloader.cpp.
 {
     while (!m_entries.isEmpty())
         delete m_entries.takeLast();
     Q_ASSERT(m_entries.size() == 0);
 }
QIconLoaderEngine() [2/2]
QIconLoaderEngine::QIconLoaderEngine (const QIconLoaderEngine & other) private
Definition at line 324 of file qiconloader.cpp.
         : QIconEngineV2(other),
         m_iconName(other.m_iconName),
         m_key(0)
 {
 }
Functions
actualSize()
QSize QIconLoaderEngine::actualSize (const QSize & size, QIcon::Mode mode, QIcon::State state) virtual
Returns the actual size of the icon the engine provides for the requested size, mode and state.
The default implementation returns the given size.
Reimplemented from QIconEngine.
Definition at line 465 of file qiconloader.cpp.
Referenced by PixmapEntry::pixmap().
 {
     ensureLoaded();
     QIconLoaderEngineEntry *entry = entryForSize(size);
     if (entry) {
         const QIconDirInfo &dir = entry->dir;
         if (dir.type == QIconDirInfo::Scalable)
             return size;
         else {
             int result = qMin<int>(dir.size, qMin(size.width(), size.height()));
             return QSize(result, result);
         }
     }
     return QIconEngineV2::actualSize(size, mode, state);
 }
clone()
QIconEngineV2 * QIconLoaderEngine::clone () const virtual
Returns a clone of this icon engine.
Reimplemented from QIconEngineV2.
Definition at line 331 of file qiconloader.cpp.
 {
     return new QIconLoaderEngine(*this);
 }
ensureLoaded()
void QIconLoaderEngine::ensureLoaded () private
Definition at line 353 of file qiconloader.cpp.
Referenced by actualSize(), pixmap(), and virtual_hook().
 {
     iconLoaderInstance()->ensureInitialized();
     if (!(iconLoaderInstance()->themeKey() == m_key)) {
         while (!m_entries.isEmpty())
             delete m_entries.takeLast();
         Q_ASSERT(m_entries.size() == 0);
         m_entries = iconLoaderInstance()->loadIcon(m_iconName);
         m_key = iconLoaderInstance()->themeKey();
     }
 }
entryForSize()
QIconLoaderEngineEntry * QIconLoaderEngine::entryForSize (const QSize & size) private
Definition at line 430 of file qiconloader.cpp.
Referenced by actualSize(), and pixmap().
 {
     int iconsize = qMin(size.width(), size.height());
     // Note that m_entries are sorted so that png-files
     // come first
     // Search for exact matches first
     for (int i = 0; i < m_entries.count(); ++i) {
         QIconLoaderEngineEntry *entry = m_entries.at(i);
         if (directoryMatchesSize(entry->dir, iconsize)) {
             return entry;
         }
     }
     // Find the minimum distance icon
     int minimalSize = INT_MAX;
     QIconLoaderEngineEntry *closestMatch = 0;
     for (int i = 0; i < m_entries.count(); ++i) {
         QIconLoaderEngineEntry *entry = m_entries.at(i);
         int distance = directorySizeDistance(entry->dir, iconsize);
         if (distance < minimalSize) {
             minimalSize  = distance;
             closestMatch = entry;
         }
     }
     return closestMatch;
 }
hasIcon()
bool QIconLoaderEngine::hasIcon () const private
Definition at line 347 of file qiconloader.cpp.
 {
     return !(m_entries.isEmpty());
 }
key()
QString QIconLoaderEngine::key () const private virtual
Returns a key that identifies this icon engine.
Reimplemented from QIconEngineV2.
Definition at line 533 of file qiconloader.cpp.
Referenced by PixmapEntry::pixmap().
 {
     return QLatin1String("QIconLoaderEngine");
 }
paint()
void QIconLoaderEngine::paint (QPainter * painter, const QRect & rect, QIcon::Mode mode, QIcon::State state) virtual
Uses the given painter to paint the icon with the required mode and state into the rectangle rect.
Implements QIconEngine.
Definition at line 369 of file qiconloader.cpp.
 {
     QSize pixmapSize = rect.size();
 #if defined(Q_WS_MAC)
     pixmapSize *= qt_mac_get_scalefactor();
 #endif
     painter->drawPixmap(rect, pixmap(pixmapSize, mode, state));
 }
pixmap()
QPixmap QIconLoaderEngine::pixmap (const QSize & size, QIcon::Mode mode, QIcon::State state) virtual
Returns the icon as a pixmap with the required size, mode, and state.
The default implementation creates a new pixmap and calls paint() to fill it.
Reimplemented from QIconEngine.
Definition at line 521 of file qiconloader.cpp.
Referenced by paint().
 {
     ensureLoaded();
     QIconLoaderEngineEntry *entry = entryForSize(size);
     if (entry)
         return entry->pixmap(size, mode, state);
     return QPixmap();
 }
read()
bool QIconLoaderEngine::read (QDataStream & in) virtual
Reads icon engine contents from the QDataStream in.
Returns true if the contents were read; otherwise returns false.
QIconEngineV2's default implementation always return false.
Reimplemented from QIconEngineV2.
Definition at line 336 of file qiconloader.cpp.
{
     in >> m_iconName;
     return true;
 }
virtual_hook()
void QIconLoaderEngine::virtual_hook (int id, void * data) private virtual
Additional method to allow extending QIconEngineV2 without adding new virtual methods (and without breaking binary compatibility).
Since
4.5
The actual action and format of data depends on id argument which is in fact a constant from IconEngineHook enum.
See also
IconEngineHook
Reimplemented from QIconEngineV2.
Definition at line 538 of file qiconloader.cpp.
 {
     ensureLoaded();
     switch (id) {
     case QIconEngineV2::AvailableSizesHook:
         {
             QIconEngineV2::AvailableSizesArgument &arg
                     = *reinterpret_cast<QIconEngineV2::AvailableSizesArgument*>(data);
             const QList<QIconDirInfo> directoryKey = iconLoaderInstance()->theme().keyList();
             arg.sizes.clear();
             // Gets all sizes from the DirectoryInfo entries
             for (int i = 0 ; i < m_entries.size() ; ++i) {
                 int size = m_entries.at(i)->dir.size;
                 arg.sizes.append(QSize(size, size));
             }
         }
         break;
     case QIconEngineV2::IconNameHook:
         {
             QString &name = *reinterpret_cast<QString*>(data);
             name = m_iconName;
         }
         break;
     default:
         QIconEngineV2::virtual_hook(id, data);
     }
 }
write()
bool QIconLoaderEngine::write (QDataStream & out) const virtual
Writes the contents of this engine to the QDataStream out.
Returns true if the contents were written; otherwise returns false.
QIconEngineV2's default implementation always return false.
Reimplemented from QIconEngineV2.
Definition at line 341 of file qiconloader.cpp.
 {
     out << m_iconName;
     return true;
 }
Friends and Related Functions
QIconLoader
friend class QIconLoader friend
Definition at line 136 of file qiconloader_p.h.
Properties
m_entries
QThemeIconEntries QIconLoaderEngine::m_entries private
Definition at line 132 of file qiconloader_p.h.
Referenced by ensureLoaded(), entryForSize(), hasIcon(), virtual_hook(), and ~QIconLoaderEngine().
m_iconName
QString QIconLoaderEngine::m_iconName private
Definition at line 133 of file qiconloader_p.h.
Referenced by ensureLoaded(), read(), virtual_hook(), and write().
m_key
uint QIconLoaderEngine::m_key private
Definition at line 134 of file qiconloader_p.h.
Referenced by ensureLoaded().
The documentation for this class was generated from the following files:
/src/gui/image/qiconloader_p.h
/src/gui/image/qiconloader.cpp