Qt 4.8: QRingBuffer< T > Class Template Reference
QRingBuffer< T > Class Template Reference
#include <qringbuffer_p.h>
Public Functions
void append (const QByteArray &qba)
bool canReadLine () const
void chop (int bytes)
void clear ()
const T & dequeue ()
void enqueue (const T &x)
void free (int bytes)
int getChar ()
const T & head () const
int indexOf (char c) const
int indexOf (char c, int maxLength) const
bool isEmpty () const
bool isEmpty () const
int nextDataBlockSize () const
QByteArray peek (int maxLength) const
void putChar (char c)
QRingBuffer (int growth=4096)
QRingBuffer ()
int read (char *data, int maxLength)
QByteArray read (int maxLength)
QByteArray read ()
QByteArray readAll ()
int readLine (char *data, int maxLength)
const char * readPointer () const
const char * readPointerAtPosition (qint64 pos, qint64 &length) const
bool reallocate (int capacity)
char * reserve (int bytes)
int size () const
int skip (int length)
void truncate (int pos)
void ungetChar (char c)
~QRingBuffer ()
Properties
int basicBlockSize
QList< QByteArray > buffers
int bufferSize
int head
T * m_array
int m_capacity
int m_head
int m_size
int tail
int tailBuffer
Detailed Description
template<class T>
class QRingBuffer< T >
Definition at line 61 of file qringbuffer_p.h.
Constructors and Destructors
QRingBuffer() [1/2]
template<class T > QRingBuffer< T >::QRingBuffer (int growth = 4096) inline
Definition at line 64 of file qringbuffer_p.h.
                                           : basicBlockSize(growth) {
         buffers << QByteArray();
         clear();
     }
QRingBuffer() [2/2]
template<class T > QRingBuffer< T >::QRingBuffer () inline
Definition at line 1246 of file qtriangulator.cpp.
 : m_array(0), m_head(0), m_size(0), m_capacity(0) { }
~QRingBuffer()
template<class T > QRingBuffer< T >::~QRingBuffer () inline
Definition at line 1247 of file qtriangulator.cpp.
 {if (m_array) delete[] m_array;}
Functions
append()
template<class T > void QRingBuffer< T >::append (const QByteArray & qba) inline
Definition at line 382 of file qringbuffer_p.h.
Referenced by QNetworkReplyImplPrivate::setup().
{
         buffers[tailBuffer].resize(tail);
         buffers << qba;
         ++tailBuffer;
         tail = qba.length();
         bufferSize += qba.length();
     }
canReadLine()
template<class T > bool QRingBuffer< T >::canReadLine () const inline
Definition at line 437 of file qringbuffer_p.h.
Referenced by QProcess::canReadLine().
{
         return indexOf('\n') != -1;
     }
chop()
template<class T > void QRingBuffer< T >::chop (int bytes) inline
Definition at line 197 of file qringbuffer_p.h.
Referenced by QNetworkReplyImplPrivate::_q_bufferOutgoingData(), QAbstractSocketPrivate::readFromSocket(), and QRingBuffer< T >::truncate().
{
         bufferSize -= bytes;
         if (bufferSize < 0)
             bufferSize = 0;
         for (;;) {
             // special case: head and tail are in the same buffer
             if (tailBuffer == 0) {
                 tail -= bytes;
                 if (tail <= head)
                     tail = head = 0;
                 return;
             }
             if (bytes <= tail) {
                 tail -= bytes;
                 return;
             }
             bytes -= tail;
             buffers.removeAt(tailBuffer);
             --tailBuffer;
             tail = buffers.at(tailBuffer).size();
         }
         if (isEmpty())
             clear(); // try to minify/squeeze us
     }
clear()
template<class T > void QRingBuffer< T >::clear () inline
Definition at line 260 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::chop(), QSslSocketPrivate::createPlainSocket(), QRingBuffer< T >::free(), QSslSocketPrivate::init(), and QRingBuffer< T >::QRingBuffer().
{
         buffers.erase(buffers.begin() + 1, buffers.end());
         buffers[0].resize(0);
         buffers[0].squeeze();
         head = tail = 0;
         tailBuffer = 0;
         bufferSize = 0;
     }
dequeue()
template<class T > const T & QRingBuffer< T >::dequeue () inline
Definition at line 1285 of file qtriangulator.cpp.
 {
     Q_ASSERT(m_size > 0);
     Q_ASSERT(m_array);
     Q_ASSERT(m_capacity >= m_size);
     int index = m_head;
     if (++m_head >= m_capacity)
         m_head -= m_capacity;
     --m_size;
     return m_array[index];
 }
enqueue()
template<class T > void QRingBuffer< T >::enqueue (const T & x) inline
Definition at line 1298 of file qtriangulator.cpp.
 {
     if (m_size == m_capacity)
         reallocate(qMax(2 * m_capacity, 64));
     int index = m_head + m_size;
     if (index >= m_capacity)
         index -= m_capacity;
     m_array[index] = x;
     ++m_size;
 }
free()
template<class T > void QRingBuffer< T >::free (int bytes) inline
Definition at line 123 of file qringbuffer_p.h.
Referenced by _qfile_writeData(), QAbstractSocketPrivate::flush(), QRingBuffer< T >::getChar(), QRingBuffer< T >::read(), QProcess::readData(), QRingBuffer< T >::readLine(), and QSslSocketBackendPrivate::transmit().
{
         bufferSize -= bytes;
         if (bufferSize < 0)
             bufferSize = 0;
         for (;;) {
             int nextBlockSize = nextDataBlockSize();
             if (bytes < nextBlockSize) {
                 head += bytes;
                 if (head == tail && tailBuffer == 0)
                     head = tail = 0;
                 break;
             }
             bytes -= nextBlockSize;
             if (buffers.count() == 1) {
                 if (buffers.at(0).size() != basicBlockSize)
                     buffers[0].resize(basicBlockSize);
                 head = tail = 0;
                 tailBuffer = 0;
                 break;
             }
             buffers.removeAt(0);
             --tailBuffer;
             head = 0;
         }
         if (isEmpty())
             clear(); // try to minify/squeeze us
     }
getChar()
template<class T > int QRingBuffer< T >::getChar () inline
Definition at line 231 of file qringbuffer_p.h.
Referenced by QProcess::readData().
{
         if (isEmpty())
             return -1;
         char c = *readPointer();
         free(1);
         return int(uchar(c));
     }
head()
template<class T > const T& QRingBuffer< T >::head () const inline
Definition at line 1249 of file qtriangulator.cpp.
Referenced by QRingBuffer< T >::chop(), QRingBuffer< T >::clear(), QRingBuffer< T >::free(), QRingBuffer< T >::indexOf(), QRingBuffer< T >::nextDataBlockSize(), QRingBuffer< T >::peek(), QRingBuffer< T >::read(), QRingBuffer< T >::readPointer(), QRingBuffer< T >::readPointerAtPosition(), and QRingBuffer< T >::ungetChar().
 {Q_ASSERT(m_size > 0); return m_array[m_head];}
indexOf() [1/2]
template<class T > int QRingBuffer< T >::indexOf (char c) const inline
Definition at line 270 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::canReadLine(), and QRingBuffer< T >::readLine().
{
         int index = 0;
         for (int i = 0; i < buffers.size(); ++i) {
             int start = 0;
             int end = buffers.at(i).size();
             if (i == 0)
                 start = head;
             if (i == tailBuffer)
                 end = tail;
             const char *ptr = buffers.at(i).data() + start;
             for (int j = start; j < end; ++j) {
                 if (*ptr++ == c)
                     return index;
                 ++index;
             }
         }
         return -1;
     }
indexOf() [2/2]
template<class T > int QRingBuffer< T >::indexOf (char c, int maxLength) const inline
Definition at line 290 of file qringbuffer_p.h.
{
         int index = 0;
         int remain = qMin(size(), maxLength);
         for (int i = 0; remain && i < buffers.size(); ++i) {
             int start = 0;
             int end = buffers.at(i).size();
             if (i == 0)
                 start = head;
             if (i == tailBuffer)
                 end = tail;
             if (remain < end - start) {
                 end = start + remain;
                 remain = 0;
             } else {
                 remain -= end - start;
             }
             const char *ptr = buffers.at(i).data() + start;
             for (int j = start; j < end; ++j) {
                 if (*ptr++ == c)
                     return index;
                 ++index;
             }
         }
         return -1;
     }
isEmpty() [1/2]
template<class T > bool QRingBuffer< T >::isEmpty () const inline
Definition at line 227 of file qringbuffer_p.h.
Referenced by QSslSocketPrivate::_q_bytesWrittenSlot(), QSslSocketPrivate::_q_flushWriteBuffer(), QProcess::atEnd(), QAbstractSocketPrivate::canWriteNotification(), QRingBuffer< T >::chop(), QAbstractSocketPrivate::flush(), QRingBuffer< T >::free(), QRingBuffer< T >::getChar(), QProcessPrivate::pipeWriterBytesToWrite(), qt_terminateApp(), QProcess::readData(), and QSslSocketBackendPrivate::transmit().
{
         return tailBuffer == 0 && tail == 0;
     }
isEmpty() [2/2]
template<class T > bool QRingBuffer< T >::isEmpty () const inline
Definition at line 1252 of file qtriangulator.cpp.
 {return m_size == 0;}
nextDataBlockSize()
template<class T > int QRingBuffer< T >::nextDataBlockSize () const inline
Definition at line 69 of file qringbuffer_p.h.
Referenced by _qfile_writeData(), QAbstractSocketPrivate::flush(), QRingBuffer< T >::free(), QRingBuffer< T >::read(), QProcess::readData(), QRingBuffer< T >::readLine(), QRingBuffer< T >::readPointerAtPosition(), and QSslSocketBackendPrivate::transmit().
{
         return (tailBuffer == 0 ? tail : buffers.first().size()) - head;
     }
peek()
template<class T > QByteArray QRingBuffer< T >::peek (int maxLength) const inline
Definition at line 390 of file qringbuffer_p.h.
{
         int bytesToRead = qMin(size(), maxLength);
         if(maxLength <= 0)
             return QByteArray();
         QByteArray ret;
         ret.resize(bytesToRead);
         int readSoFar = 0;
         for (int i = 0; readSoFar < bytesToRead && i < buffers.size(); ++i) {
             int start = 0;
             int end = buffers.at(i).size();
             if (i == 0)
                 start = head;
             if (i == tailBuffer)
                 end = tail;
             const int len = qMin(ret.size()-readSoFar, end-start);
             memcpy(ret.data()+readSoFar, buffers.at(i).constData()+start, len);
             readSoFar += len;
         }
         Q_ASSERT(readSoFar == ret.size());
         return ret;
     }
putChar()
template<class T > void QRingBuffer< T >::putChar (char c) inline
Definition at line 239 of file qringbuffer_p.h.
{
         char *ptr = reserve(1);
         *ptr = c;
     }
read() [1/3]
template<class T > int QRingBuffer< T >::read (char * data, int maxLength) inline
Definition at line 317 of file qringbuffer_p.h.
{
         int bytesToRead = qMin(size(), maxLength);
         int readSoFar = 0;
         while (readSoFar < bytesToRead) {
             const char *ptr = readPointer();
             int bytesToReadFromThisBlock = qMin(bytesToRead - readSoFar, nextDataBlockSize());
             if (data)
                 memcpy(data + readSoFar, ptr, bytesToReadFromThisBlock);
             readSoFar += bytesToReadFromThisBlock;
             free(bytesToReadFromThisBlock);
         }
         return readSoFar;
     }
read() [2/3]
template<class T > QByteArray QRingBuffer< T >::read (int maxLength) inline
Definition at line 331 of file qringbuffer_p.h.
{
         QByteArray tmp;
         tmp.resize(qMin(maxLength, size()));
         read(tmp.data(), tmp.size());
         return tmp;
     }
read() [3/3]
template<class T > QByteArray QRingBuffer< T >::read () inline
Definition at line 343 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::read(), QRingBuffer< T >::readAll(), QRingBuffer< T >::readLine(), and QRingBuffer< T >::skip().
{
         if (bufferSize == 0)
             return QByteArray();
         // multiple buffers, just take the first one
         if (head == 0 && tailBuffer != 0) {
             QByteArray qba = buffers.takeFirst();
             --tailBuffer;
             bufferSize -= qba.length();
             return qba;
         }
         // one buffer with good value for head. Just take it.
         if (head == 0 && tailBuffer == 0) {
             QByteArray qba = buffers.takeFirst();
             qba.resize(tail);
             buffers << QByteArray();
             bufferSize = 0;
             tail = 0;
             return qba;
         }
         // Bad case: We have to memcpy.
         // We can avoid by initializing the QRingBuffer with basicBlockSize of 0
         // and only using this read() function.
         QByteArray qba(readPointer(), nextDataBlockSize());
         buffers.removeFirst();
         head = 0;
         if (tailBuffer == 0) {
             buffers << QByteArray();
             tail = 0;
         } else {
             --tailBuffer;
         }
         bufferSize -= qba.length();
         return qba;
     }
readAll()
template<class T > QByteArray QRingBuffer< T >::readAll () inline
Definition at line 338 of file qringbuffer_p.h.
{
         return read(size());
     }
readLine()
template<class T > int QRingBuffer< T >::readLine (char * data, int maxLength) inline
Definition at line 416 of file qringbuffer_p.h.
{
         int index = indexOf('\n');
         if (index == -1)
             return read(data, maxLength);
         if (maxLength <= 0)
             return -1;
         int readSoFar = 0;
         while (readSoFar < index + 1 && readSoFar < maxLength - 1) {
             int bytesToRead = qMin((index + 1) - readSoFar, nextDataBlockSize());
             bytesToRead = qMin(bytesToRead, (maxLength - 1) - readSoFar);
             memcpy(data + readSoFar, readPointer(), bytesToRead);
             readSoFar += bytesToRead;
             free(bytesToRead);
         }
         // Terminate it.
         data[readSoFar] = '\0';
         return readSoFar;
     }
readPointer()
template<class T > const char* QRingBuffer< T >::readPointer () const inline
Definition at line 73 of file qringbuffer_p.h.
Referenced by _qfile_writeData(), QAbstractSocketPrivate::flush(), QRingBuffer< T >::getChar(), QRingBuffer< T >::read(), QProcess::readData(), QRingBuffer< T >::readLine(), and QSslSocketBackendPrivate::transmit().
{
         return buffers.isEmpty() ? 0 : (buffers.first().constData() + head);
     }
readPointerAtPosition()
template<class T > const char* QRingBuffer< T >::readPointerAtPosition (qint64 pos, qint64 & length) const inline
Definition at line 80 of file qringbuffer_p.h.
Referenced by QNonContiguousByteDeviceRingBufferImpl::readPointer().
{
         if (buffers.isEmpty()) {
             length = 0;
             return 0;
         }
         if (pos >= bufferSize) {
             length = 0;
             return 0;
         }
         // special case: it is in the first buffer
         int nextDataBlockSizeValue = nextDataBlockSize();
         if (pos - head < nextDataBlockSizeValue) {
             length = nextDataBlockSizeValue - pos;
             return buffers.at(0).constData() + head + pos;
         }
         // special case: we only had one buffer and tried to read over it
         if (buffers.length() == 1) {
             length = 0;
             return 0;
         }
         // skip the first
         pos -= nextDataBlockSizeValue;
         // normal case: it is somewhere in the second to the-one-before-the-tailBuffer
         for (int i = 1; i < tailBuffer; i++) {
             if (pos >= buffers[i].size()) {
                 pos -= buffers[i].size();
                 continue;
             }
             length = buffers[i].length() - pos;
             return buffers[i].constData() + pos;
         }
         // it is in the tail buffer
         length = tail - pos;
         return buffers[tailBuffer].constData() + pos;
     }
reallocate()
template<class T > bool QRingBuffer< T >::reallocate (int capacity)
Definition at line 1261 of file qtriangulator.cpp.
 {
     T *oldArray = m_array;
     m_array = new T[capacity];
     if (m_array) {
         if (oldArray) {
             if (m_head + m_size > m_capacity) {
                 memcpy(m_array, oldArray + m_head, (m_capacity - m_head) * sizeof(T));
                 memcpy(m_array + (m_capacity - m_head), oldArray, (m_head + m_size - m_capacity) * sizeof(T));
             } else {
                 memcpy(m_array, oldArray + m_head, m_size * sizeof(T));
             }
             delete[] oldArray;
         }
         m_capacity = capacity;
         m_head = 0;
         return true;
     } else {
         m_array = oldArray;
         return false;
     }
 }
reserve()
template<class T > char* QRingBuffer< T >::reserve (int bytes) inline
Definition at line 155 of file qringbuffer_p.h.
Referenced by QNetworkReplyImplPrivate::_q_bufferOutgoingData(), QHttpPrivate::_q_slotReadyRead(), QRingBuffer< T >::putChar(), QAbstractSocketPrivate::readFromSocket(), QLocalSocketPrivate::startAsyncRead(), and QSslSocketBackendPrivate::transmit().
{
         // if this is a fresh empty QRingBuffer
         if (bufferSize == 0) {
             buffers[0].resize(qMax(basicBlockSize, bytes));
             bufferSize += bytes;
             tail = bytes;
             return buffers[tailBuffer].data();
         }
         bufferSize += bytes;
         // if there is already enough space, simply return.
         if (tail + bytes <= buffers.at(tailBuffer).size()) {
             char *writePtr = buffers[tailBuffer].data() + tail;
             tail += bytes;
             return writePtr;
         }
         // if our buffer isn't half full yet, simply resize it.
         if (tail < buffers.at(tailBuffer).size() / 2) {
             buffers[tailBuffer].resize(tail + bytes);
             char *writePtr = buffers[tailBuffer].data() + tail;
             tail += bytes;
             return writePtr;
         }
         // shrink this buffer to its current size
         buffers[tailBuffer].resize(tail);
         // create a new QByteArray with the right size
         buffers << QByteArray();
         ++tailBuffer;
         buffers[tailBuffer].resize(qMax(basicBlockSize, bytes));
         tail = bytes;
         return buffers[tailBuffer].data();
     }
size()
template<class T > int QRingBuffer< T >::size () const inline
Definition at line 256 of file qringbuffer_p.h.
Referenced by QProcess::bytesAvailable(), QAbstractSocketPrivate::canReadNotification(), QAbstractSocketPrivate::canWriteNotification(), QRingBuffer< T >::indexOf(), QRingBuffer< T >::peek(), QRingBuffer< T >::read(), QRingBuffer< T >::readAll(), QProcess::readData(), QAbstractSocketPrivate::readFromSocket(), QRingBuffer< T >::readPointerAtPosition(), QNetworkReplyImplPrivate::setup(), QNonContiguousByteDeviceRingBufferImpl::size(), QLocalSocketPrivate::startAsyncRead(), QSslSocketBackendPrivate::transmit(), and QRingBuffer< T >::truncate().
{
         return bufferSize;
     }
skip()
template<class T > int QRingBuffer< T >::skip (int length) inline
Definition at line 412 of file qringbuffer_p.h.
{
         return read(0, length);
     }
truncate()
template<class T > void QRingBuffer< T >::truncate (int pos) inline
Definition at line 192 of file qringbuffer_p.h.
Referenced by QLocalSocketPrivate::completeAsyncRead().
{
         if (pos < size())
             chop(size() - pos);
     }
ungetChar()
template<class T > void QRingBuffer< T >::ungetChar (char c) inline
Definition at line 244 of file qringbuffer_p.h.
{
         --head;
         if (head < 0) {
             buffers.prepend(QByteArray());
             buffers[0].resize(basicBlockSize);
             head = basicBlockSize - 1;
             ++tailBuffer;
         }
         buffers[0][head] = c;
         ++bufferSize;
     }
Properties
basicBlockSize
template<class T > int QRingBuffer< T >::basicBlockSize private
Definition at line 445 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::free(), QRingBuffer< T >::reserve(), and QRingBuffer< T >::ungetChar().
buffers
template<class T > QList<QByteArray> QRingBuffer< T >::buffers private
Definition at line 442 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::append(), QRingBuffer< T >::chop(), QRingBuffer< T >::clear(), QRingBuffer< T >::free(), QRingBuffer< T >::indexOf(), QRingBuffer< T >::nextDataBlockSize(), QRingBuffer< T >::peek(), QRingBuffer< T >::QRingBuffer(), QRingBuffer< T >::read(), QRingBuffer< T >::readPointer(), QRingBuffer< T >::readPointerAtPosition(), QRingBuffer< T >::reserve(), and QRingBuffer< T >::ungetChar().
bufferSize
template<class T > int QRingBuffer< T >::bufferSize private
Definition at line 446 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::append(), QRingBuffer< T >::chop(), QRingBuffer< T >::clear(), QRingBuffer< T >::free(), QRingBuffer< T >::read(), QRingBuffer< T >::readPointerAtPosition(), QRingBuffer< T >::reserve(), QRingBuffer< T >::size(), and QRingBuffer< T >::ungetChar().
head
template<class T > int QRingBuffer< T >::head private
Definition at line 443 of file qringbuffer_p.h.
m_array
template<class T > T* QRingBuffer< T >::m_array private
Definition at line 1254 of file qtriangulator.cpp.
m_capacity
template<class T > int QRingBuffer< T >::m_capacity private
Definition at line 1257 of file qtriangulator.cpp.
m_head
template<class T > int QRingBuffer< T >::m_head private
Definition at line 1255 of file qtriangulator.cpp.
m_size
template<class T > int QRingBuffer< T >::m_size private
Definition at line 1256 of file qtriangulator.cpp.
tail
template<class T > int QRingBuffer< T >::tail private
Definition at line 443 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::append(), QRingBuffer< T >::chop(), QRingBuffer< T >::clear(), QRingBuffer< T >::free(), QRingBuffer< T >::indexOf(), QRingBuffer< T >::isEmpty(), QRingBuffer< T >::nextDataBlockSize(), QRingBuffer< T >::peek(), QRingBuffer< T >::read(), QRingBuffer< T >::readPointerAtPosition(), and QRingBuffer< T >::reserve().
tailBuffer
template<class T > int QRingBuffer< T >::tailBuffer private
Definition at line 444 of file qringbuffer_p.h.
Referenced by QRingBuffer< T >::append(), QRingBuffer< T >::chop(), QRingBuffer< T >::clear(), QRingBuffer< T >::free(), QRingBuffer< T >::indexOf(), QRingBuffer< T >::isEmpty(), QRingBuffer< T >::nextDataBlockSize(), QRingBuffer< T >::peek(), QRingBuffer< T >::read(), QRingBuffer< T >::readPointerAtPosition(), QRingBuffer< T >::reserve(), and QRingBuffer< T >::ungetChar().
The documentation for this class was generated from the following files:
/src/corelib/tools/qringbuffer_p.h
/src/opengl/gl2paintengineex/qtriangulator.cpp