Qt 4.8: QMenu Class Reference
QMenu Class Reference
The QMenu class provides a menu widget for use in menu bars, context menus, and other popup menus.
#include <qmenu.h>
Signals
void aboutToHide ()
This signal is emitted just before the menu is hidden from the user.
void aboutToShow ()
This signal is emitted just before the menu is shown to the user.
void hovered (QAction *action)
This signal is emitted when a menu action is highlighted; action is the action that caused the signal to be emitted.
void triggered (QAction *action)
This signal is emitted when an action in this menu is triggered.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QAction * actionAt (const QPoint &) const
Returns the item at pt; returns 0 if there is no item there.
QRect actionGeometry (QAction *) const
Returns the geometry of action act.
QAction * activeAction () const
Returns the currently highlighted action, or 0 if no action is currently highlighted.
QAction * addAction (const QString &text)
This convenience function creates a new action with text.
QAction * addAction (const QIcon &icon, const QString &text)
This convenience function creates a new action with an icon and some text.
QAction * addAction (const QString &text, const QObject *receiver, const char *member, const QKeySequence &shortcut=0)
This convenience function creates a new action with the text text and an optional shortcut shortcut.
QAction * addAction (const QIcon &icon, const QString &text, const QObject *receiver, const char *member, const QKeySequence &shortcut=0)
This convenience function creates a new action with an icon and some text and an optional shortcut shortcut.
QAction * addMenu (QMenu *menu)
This convenience function adds menu as a submenu to this menu.
QMenu * addMenu (const QString &title)
Appends a new QMenu with title to the menu.
QMenu * addMenu (const QIcon &icon, const QString &title)
Appends a new QMenu with icon and title to the menu.
QAction * addSeparator ()
This convenience function creates a new separator action, i.e.
void clear ()
Removes all the menu's actions.
QAction * defaultAction () const
Returns the current default action.
QAction * exec ()
Executes this menu synchronously.
QAction * exec (const QPoint &pos, QAction *at=0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Executes this menu synchronously.
void hideTearOffMenu ()
This function will forcibly hide the torn off menu making it disappear from the users desktop.
QIcon icon () const
QAction * insertMenu (QAction *before, QMenu *menu)
This convenience function inserts menu before action before and returns the menus menuAction().
QAction * insertSeparator (QAction *before)
This convenience function creates a new separator action, i.e.
bool isEmpty () const
Returns true if there are no visible actions inserted into the menu, false otherwise.
bool isTearOffEnabled () const
bool isTearOffMenuVisible () const
When a menu is torn off a second menu is shown to display the menu contents in a new window.
OSMenuRef macMenu (OSMenuRef merge=0)
QAction * menuAction () const
Returns the action associated with this menu.
void popup (const QPoint &pos, QAction *at=0)
Displays the menu so that the action atAction will be at the specified global position p.
QMenu (QWidget *parent=0)
Constructs a menu with parent parent.
QMenu (const QString &title, QWidget *parent=0)
Constructs a menu with a title and a parent.
bool separatorsCollapsible () const
void setActiveAction (QAction *act)
Sets the currently highlighted action to act.
void setDefaultAction (QAction *)
This sets the default action to act.
void setIcon (const QIcon &icon)
void setNoReplayFor (QWidget *widget)
void setSeparatorsCollapsible (bool collapse)
void setTearOffEnabled (bool)
void setTitle (const QString &title)
QSize sizeHint () const
Reimplemented Function
QString title () const
HMENU wceMenu ()
This function will return the HMENU used to create the native Windows CE menu bar bindings.
~QMenu ()
Destroys the menu.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
virtual QVariant inputMethodQuery (Qt::InputMethodQuery) const
This method is only relevant for input widgets.
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
virtual QSize minimumSizeHint () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Static Public Functions
static QAction * exec (QList< QAction *> actions, const QPoint &pos, QAction *at=0)
Executes a menu synchronously.
static QAction * exec (QList< QAction *> actions, const QPoint &pos, QAction *at, QWidget *parent)
Executes a menu synchronously.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions
void actionEvent (QActionEvent *)
Reimplemented Function
void changeEvent (QEvent *)
Reimplemented Function
int columnCount () const
If a menu does not fit on the screen it lays itself out so that it does fit.
void enterEvent (QEvent *)
Reimplemented Function
bool event (QEvent *)
Reimplemented Function
bool focusNextPrevChild (bool next)
Reimplemented Function
void hideEvent (QHideEvent *)
Reimplemented Function
void initStyleOption (QStyleOptionMenuItem *option, const QAction *action) const
Initialize option with the values from this menu and information from action.
void keyPressEvent (QKeyEvent *)
Reimplemented Function
void leaveEvent (QEvent *)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *)
Reimplemented Function
void mousePressEvent (QMouseEvent *)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *)
Reimplemented Function
void paintEvent (QPaintEvent *)
Reimplemented Function
QMenu (QMenuPrivate &dd, QWidget *parent=0)
void timerEvent (QTimerEvent *)
Reimplemented Function
QAction * wceCommands (uint command)
This function sends native Windows CE commands to Qt menus.
void wheelEvent (QWheelEvent *)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
virtual void contextMenuEvent (QContextMenuEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive widget context menu events.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void focusInEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus received) for the widget.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual void focusOutEvent (QFocusEvent *)
This event handler can be reimplemented in a subclass to receive keyboard focus events (focus lost) for the widget.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive widget resize events which are passed in the event parameter.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Slots
void internalDelayedPopup ()
void internalSetSloppyAction ()
Properties
QIcon icon
The icon of the menu.
bool separatorsCollapsible
whether consecutive separators should be collapsed
bool tearOffEnabled
whether the menu supports being torn off
QString title
The title of the menu.
Friends
class Q3PopupMenu
class QAction
class QComboBox
class QMenuBar
class QMenuBarPrivate
bool qt_mac_activate_action (OSMenuRef, uint, QAction::ActionEvent, bool)
void qt_mac_emit_menuSignals (QMenu *, bool)
void qt_mac_menu_emit_hovered (QMenu *menu, QAction *action)
OSStatus qt_mac_menu_event (EventHandlerCallRef, EventRef, void *)
void qt_mac_trayicon_activate_action (QMenu *, QAction *action)
bool qt_mac_watchingAboutToShow (QMenu *)
class QToolButtonPrivate
class QTornOffMenu
Additional Inherited Members
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QMenu class provides a menu widget for use in menu bars, context menus, and other popup menus.
A menu widget is a selection menu. It can be either a pull-down menu in a menu bar or a standalone context menu. Pull-down menus are shown by the menu bar when the user clicks on the respective item or presses the specified shortcut key. Use QMenuBar::addMenu() to insert a menu into a menu bar. Context menus are usually invoked by some special keyboard key or by right-clicking. They can be executed either asynchronously with popup() or synchronously with exec(). Menus can also be invoked in response to button presses; these are just like context menus except for how they are invoked.
Fig. A menu shown in Plastique Style Widget Gallery{Plastique widget style}, Windows XP Style Widget Gallery{Windows XP widget style}, and Macintosh Style Widget Gallery{Macintosh widget style}.
Actions
A menu consists of a list of action items. Actions are added with the addAction(), addActions() and insertAction() functions. An action is represented vertically and rendered by QStyle. In addition, actions can have a text label, an optional icon drawn on the very left side, and shortcut key sequence such as "Ctrl+X".
The existing actions held by a menu can be found with actions().
There are four kinds of action items: separators, actions that show a submenu, widgets, and actions that perform an action. Separators are inserted with addSeparator(), submenus with addMenu(), and all other items are considered action items.
When inserting action items you usually specify a receiver and a slot. The receiver will be notifed whenever the item is triggered(). In addition, QMenu provides two signals, activated() and highlighted(), which signal the QAction that was triggered from the menu.
You clear a menu with clear() and remove individual action items with removeAction().
A QMenu can also provide a tear-off menu. A tear-off menu is a top-level window that contains a copy of the menu. This makes it possible for the user to "tear off" frequently used menus and position them in a convenient place on the screen. If you want this functionality for a particular menu, insert a tear-off handle with setTearOffEnabled(). When using tear-off menus, bear in mind that the concept isn't typically used on Microsoft Windows so some users may not be familiar with it. Consider using a QToolBar instead.
Widgets can be inserted into menus with the QWidgetAction class. Instances of this class are used to hold widgets, and are inserted into menus with the addAction() overload that takes a QAction.
Conversely, actions can be added to widgets with the addAction(), addActions() and insertAction() functions.
Warning
To make QMenu visible on the screen, exec() or popup() should be used instead of show().
QMenu on Qt for Windows CE
If a menu is integrated into the native menubar on Windows Mobile we do not support the signals: aboutToHide (), aboutToShow () and hovered (). It is not possible to display an icon in a native menu on Windows Mobile.
QMenu on Mac OS X with Qt build against Cocoa
QMenu can be inserted only once in a menu/menubar. Subsequent insertions will have no effect or will result in a disabled menu item.
See the Menus example for an example of how to use QMenuBar and QMenu in your application.
Important inherited functions: addAction(), removeAction(), clear(), addSeparator(), and addMenu().
See also
QMenuBar, {fowler}{GUI Design Handbook: Menu, Drop-Down and Pop-Up}, {Application Example}, {Menus Example}, {Recent Files Example}
Definition at line 72 of file qmenu.h.
Constructors and Destructors
QMenu() [1/3]
QMenu::QMenu (QWidget * parent = 0) explicit
Constructs a menu with parent parent.
Although a popup menu is always a top-level widget, if a parent is passed the popup menu will be deleted when that parent is destroyed (as with any other QObject).
Definition at line 1386 of file qmenu.cpp.
Referenced by addMenu().
     : QWidget(*new QMenuPrivate, parent, Qt::Popup)
 {
     Q_D(QMenu);
     d->init();
 }
QMenu() [2/3]
QMenu::QMenu (const QString & title, QWidget * parent = 0) explicit
Constructs a menu with a title and a parent.
Although a popup menu is always a top-level widget, if a parent is passed the popup menu will be deleted when that parent is destroyed (as with any other QObject).
See also
title
Definition at line 1402 of file qmenu.cpp.
     : QWidget(*new QMenuPrivate, parent, Qt::Popup)
 {
     Q_D(QMenu);
     d->init();
     d->menuAction->setText(title);
 }
~QMenu()
QMenu::~QMenu ()
Destroys the menu.
Definition at line 1422 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (!d->widgetItems.isEmpty()) {  // avoid detach on shared null hash
         QHash<QAction *, QWidget *>::iterator it = d->widgetItems.begin();
         for (; it != d->widgetItems.end(); ++it) {
             if (QWidget *widget = it.value()) {
                 QWidgetAction *action = static_cast<QWidgetAction *>(it.key());
                 action->releaseWidget(widget);
                 *it = 0;
             }
         }
     }
     if (d->eventLoop)
         d->eventLoop->exit();
     hideTearOffMenu();
 }
QMenu() [3/3]
QMenu::QMenu (QMenuPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 1412 of file qmenu.cpp.
     : QWidget(dd, parent, Qt::Popup)
 {
     Q_D(QMenu);
     d->init();
 }
Functions
aboutToHide
void QMenu::aboutToHide () signal
This signal is emitted just before the menu is hidden from the user.
Since
4.2
See also
aboutToShow(), hide()
Referenced by hideEvent().
aboutToShow
void QMenu::aboutToShow () signal
This signal is emitted just before the menu is shown to the user.
See also
aboutToHide(), show()
Referenced by popup().
actionAt()
QAction * QMenu::actionAt (const QPoint & pt) const
Returns the item at pt; returns 0 if there is no item there.
Definition at line 1787 of file qmenu.cpp.
Referenced by QAccessibleMenu::childAt().
 {
     if (QAction *ret = d_func()->actionAt(pt))
         return ret;
     return 0;
 }
actionEvent()
void QMenu::actionEvent (QActionEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2969 of file qmenu.cpp.
Referenced by QTornOffMenu::actionEvent().
 {
     Q_D(QMenu);
     d->itemsDirty = 1;
     setAttribute(Qt::WA_Resized, false);
     if (d->tornPopup)
         d->tornPopup->syncWithMenu(this, e);
     if (e->type() == QEvent::ActionAdded) {
         if(!d->tornoff) {
             connect(e->action(), SIGNAL(triggered()), this, SLOT(_q_actionTriggered()));
             connect(e->action(), SIGNAL(hovered()), this, SLOT(_q_actionHovered()));
         }
         if (QWidgetAction *wa = qobject_cast<QWidgetAction *>(e->action())) {
             QWidget *widget = wa->requestWidget(this);
             if (widget)
                 d->widgetItems.insert(wa, widget);
         }
     } else if (e->type() == QEvent::ActionRemoved) {
         e->action()->disconnect(this);
         if (e->action() == d->currentAction)
             d->currentAction = 0;
         if (QWidgetAction *wa = qobject_cast<QWidgetAction *>(e->action())) {
             if (QWidget *widget = d->widgetItems.value(wa))
                 wa->releaseWidget(widget);
         }
         d->widgetItems.remove(e->action());
     }
 #ifdef Q_WS_MAC
     if (d->mac_menu) {
         if (e->type() == QEvent::ActionAdded)
             d->mac_menu->addAction(e->action(), d->mac_menu->findAction(e->before()), d);
         else if (e->type() == QEvent::ActionRemoved)
             d->mac_menu->removeAction(e->action());
         else if (e->type() == QEvent::ActionChanged)
             d->mac_menu->syncAction(e->action());
     }
 #endif
 #if defined(Q_WS_WINCE) && !defined(QT_NO_MENUBAR)
     if (!d->wce_menu)
         d->wce_menu = new QMenuPrivate::QWceMenuPrivate;
     if (e->type() == QEvent::ActionAdded)
         d->wce_menu->addAction(e->action(), d->wce_menu->findAction(e->before()));
     else if (e->type() == QEvent::ActionRemoved)
         d->wce_menu->removeAction(e->action());
     else if (e->type() == QEvent::ActionChanged)
         d->wce_menu->syncAction(e->action());
 #endif
 #ifdef Q_WS_S60
     if (!d->symbian_menu)
         d->symbian_menu = new QMenuPrivate::QSymbianMenuPrivate;
     if (e->type() == QEvent::ActionAdded)
         d->symbian_menu->addAction(e->action(), d->symbian_menu->findAction(e->before()));
     else if (e->type() == QEvent::ActionRemoved)
         d->symbian_menu->removeAction(e->action());
     else if (e->type() == QEvent::ActionChanged)
         d->symbian_menu->syncAction(e->action());
 #endif
     if (isVisible()) {
         d->updateActionRects();
         resize(sizeHint());
         update();
     }
 }
actionGeometry()
QRect QMenu::actionGeometry (QAction * act) const
Returns the geometry of action act.
Definition at line 1797 of file qmenu.cpp.
Referenced by QAccessibleMenu::rect().
 {
     return d_func()->actionRect(act);
 }
activeAction()
QAction * QMenu::activeAction () const
Returns the currently highlighted action, or 0 if no action is currently highlighted.
Definition at line 1720 of file qmenu.cpp.
Referenced by QMenuPrivate::hideMenu(), and QAccessibleMenu::state().
 {
     return d_func()->currentAction;
 }
addAction() [1/4]
QAction * QMenu::addAction (const QString & text)
This convenience function creates a new action with text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The function adds the newly created action to the menu's list of actions, and returns it.
See also
QWidget::addAction()
Definition at line 1453 of file qmenu.cpp.
Referenced by QFileDialogPrivate::_q_showContextMenu(), addAction(), addMenu(), addSeparator(), QMdiSubWindowPrivate::addToSystemMenu(), QDecoration::buildSysMenu(), QmlJSDebugger::ToolBarColorBox::contextMenuEvent(), QScrollBar::contextMenuEvent(), QDialog::contextMenuEvent(), QAbstractSpinBox::contextMenuEvent(), QmlJSDebugger::LiveSelectionTool::createContextMenu(), QCalendarWidgetPrivate::createNavigationBar(), QMainWindow::createPopupMenu(), QTextControl::createStandardContextMenu(), QLineEdit::createStandardContextMenu(), QScriptDebugger::createStandardMenu(), QScriptEdit::extraAreaMouseEvent(), QToolBarLayout::layoutActions(), menuItemEntry(), QmlJSDebugger::ZoomTool::mousePressEvent(), QToolButtonPrivate::popupTimerDone(), QmlJSDebugger::QmlToolBar::QmlToolBar(), QMultiInputContext::QMultiInputContext(), QTornOffMenu::QTornOffMenu(), QUnicodeControlCharacterMenu::QUnicodeControlCharacterMenu(), setSeparatorsCollapsible(), and QScriptEngineDebugger::standardWindow().
 {
     QAction *ret = new QAction(text, this);
     addAction(ret);
     return ret;
 }
addAction() [2/4]
QAction * QMenu::addAction (const QIcon & icon, const QString & text)
This convenience function creates a new action with an icon and some text.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The function adds the newly created action to the menu's list of actions, and returns it.
See also
QWidget::addAction()
Definition at line 1472 of file qmenu.cpp.
 {
     QAction *ret = new QAction(icon, text, this);
     addAction(ret);
     return ret;
 }
addAction() [3/4]
QAction * QMenu::addAction (const QString & text, const QObject * receiver, const char * member, const QKeySequence & shortcut = 0)
This convenience function creates a new action with the text text and an optional shortcut shortcut.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The action's triggered() signal is connected to the receiver's member slot. The function adds the newly created action to the menu's list of actions and returns it.
See also
QWidget::addAction()
Definition at line 1493 of file qmenu.cpp.
 {
     QAction *action = new QAction(text, this);
 #ifdef QT_NO_SHORTCUT
     Q_UNUSED(shortcut);
 #else
     action->setShortcut(shortcut);
 #endif
     QObject::connect(action, SIGNAL(triggered(bool)), receiver, member);
     addAction(action);
     return action;
 }
addAction() [4/4]
QAction * QMenu::addAction (const QIcon & icon, const QString & text, const QObject * receiver, const char * member, const QKeySequence & shortcut = 0)
This convenience function creates a new action with an icon and some text and an optional shortcut shortcut.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The action's triggered() signal is connected to the member slot of the receiver object. The function adds the newly created action to the menu's list of actions, and returns it.
See also
QWidget::addAction()
Definition at line 1520 of file qmenu.cpp.
 {
     QAction *action = new QAction(icon, text, this);
 #ifdef QT_NO_SHORTCUT
     Q_UNUSED(shortcut);
 #else
     action->setShortcut(shortcut);
 #endif
     QObject::connect(action, SIGNAL(triggered(bool)), receiver, member);
     addAction(action);
     return action;
 }
addMenu() [1/3]
QAction * QMenu::addMenu (QMenu * menu)
This convenience function adds menu as a submenu to this menu.
It returns menu's menuAction(). This menu does not take ownership of menu.
See also
QWidget::addAction() QMenu::menuAction()
Definition at line 1541 of file qmenu.cpp.
Referenced by QTextControl::createStandardContextMenu(), QLineEdit::createStandardContextMenu(), and menuItemEntry().
 {
     QAction *action = menu->menuAction();
     addAction(action);
     return action;
 }
addMenu() [2/3]
QMenu * QMenu::addMenu (const QString & title)
Appends a new QMenu with title to the menu.
The menu takes ownership of the menu. Returns the new menu.
See also
QWidget::addAction() QMenu::menuAction()
Definition at line 1554 of file qmenu.cpp.
 {
     QMenu *menu = new QMenu(title, this);
     addAction(menu->menuAction());
     return menu;
 }
addMenu() [3/3]
QMenu * QMenu::addMenu (const QIcon & icon, const QString & title)
Appends a new QMenu with icon and title to the menu.
The menu takes ownership of the menu. Returns the new menu.
See also
QWidget::addAction() QMenu::menuAction()
Definition at line 1567 of file qmenu.cpp.
 {
     QMenu *menu = new QMenu(title, this);
     menu->setIcon(icon);
     addAction(menu->menuAction());
     return menu;
 }
addSeparator()
QAction * QMenu::addSeparator ()
This convenience function creates a new separator action, i.e.
an action with QAction::isSeparator() returning true, and adds the new action to this menu's list of actions. It returns the newly created action.
See also
QWidget::addAction()
Definition at line 1583 of file qmenu.cpp.
Referenced by QFileDialogPrivate::_q_showContextMenu(), QDecoration::buildSysMenu(), QScrollBar::contextMenuEvent(), QAbstractSpinBox::contextMenuEvent(), QmlJSDebugger::LiveSelectionTool::createContextMenu(), QMainWindow::createPopupMenu(), QTextControl::createStandardContextMenu(), QLineEdit::createStandardContextMenu(), QScriptDebugger::createStandardMenu(), QMdiSubWindowPrivate::createSystemMenu(), QScriptEdit::extraAreaMouseEvent(), menuItemEntry(), QmlJSDebugger::ZoomTool::mousePressEvent(), and QScriptEngineDebugger::standardWindow().
 {
     QAction *action = new QAction(this);
     action->setSeparator(true);
     addAction(action);
     return action;
 }
changeEvent()
void QMenu::changeEvent (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2414 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (e->type() == QEvent::StyleChange || e->type() == QEvent::FontChange ||
         e->type() == QEvent::LayoutDirectionChange) {
         d->itemsDirty = 1;
         setMouseTracking(style()->styleHint(QStyle::SH_Menu_MouseTracking, 0, this));
         if (isVisible())
             resize(sizeHint());
         if (!style()->styleHint(QStyle::SH_Menu_Scrollable, 0, this)) {
             delete d->scroll;
             d->scroll = 0;
         } else if (!d->scroll) {
             d->scroll = new QMenuPrivate::QMenuScroller;
             d->scroll->scrollFlags = QMenuPrivate::QMenuScroller::ScrollNone;
         }
     } else if (e->type() == QEvent::EnabledChange) {
         if (d->tornPopup) // torn-off menu
             d->tornPopup->setEnabled(isEnabled());
         d->menuAction->setEnabled(isEnabled());
 #if defined(Q_WS_MAC) && !defined(QT_MAC_USE_COCOA)
         if (d->mac_menu)
             d->setMacMenuEnabled(isEnabled());
 #endif
     }
     QWidget::changeEvent(e);
 }
clear()
void QMenu::clear ()
Removes all the menu's actions.
Actions owned by the menu and not shown in any other widget are deleted.
See also
removeAction()
Definition at line 1755 of file qmenu.cpp.
Referenced by QToolBarLayout::layoutActions(), and QMenuBarPrivate::updateGeometries().
 {
     QList<QAction*> acts = actions();
     for(int i = 0; i < acts.size(); i++) {
 #ifdef QT_SOFTKEYS_ENABLED
         Q_D(QMenu);
         // Lets not touch to our internal softkey actions
         if(acts[i] == d->selectAction || acts[i] == d->cancelAction)
             continue;
 #endif
         removeAction(acts[i]);
         if (acts[i]->parent() == this && acts[i]->d_func()->widgets.isEmpty())
             delete acts[i];
     }
 }
columnCount()
int QMenu::columnCount () const protected
If a menu does not fit on the screen it lays itself out so that it does fit.
It is style dependent what layout means (for example, on Windows it will use multiple columns).
This functions returns the number of columns necessary.
Definition at line 1779 of file qmenu.cpp.
 {
     return d_func()->ncols;
 }
defaultAction()
QAction * QMenu::defaultAction () const
Returns the current default action.
See also
setDefaultAction()
Definition at line 1637 of file qmenu.cpp.
 {
     return d_func()->defaultAction;
 }
enterEvent()
void QMenu::enterEvent (QEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2925 of file qmenu.cpp.
 {
     d_func()->motions = -1; // force us to ignore the generate mouse move in mouseMoveEvent()
 }
event()
bool QMenu::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2447 of file qmenu.cpp.
 {
     Q_D(QMenu);
     switch (e->type()) {
     case QEvent::Polish:
         d->updateLayoutDirection();
         break;
     case QEvent::ShortcutOverride: {
             QKeyEvent *kev = static_cast<QKeyEvent*>(e);
             if (kev->key() == Qt::Key_Up || kev->key() == Qt::Key_Down
                 || kev->key() == Qt::Key_Left || kev->key() == Qt::Key_Right
                 || kev->key() == Qt::Key_Enter || kev->key() == Qt::Key_Return
                 || kev->key() == Qt::Key_Escape) {
                 e->accept();
                 return true;
             }
         }
         break;
     case QEvent::KeyPress: {
         QKeyEvent *ke = (QKeyEvent*)e;
         if (ke->key() == Qt::Key_Tab || ke->key() == Qt::Key_Backtab) {
             keyPressEvent(ke);
             return true;
         }
     } break;
     case QEvent::ContextMenu:
         if(d->menuDelayTimer.isActive()) {
             d->menuDelayTimer.stop();
             internalDelayedPopup();
         }
         break;
     case QEvent::Resize: {
         QStyleHintReturnMask menuMask;
         QStyleOption option;
         option.initFrom(this);
         if (style()->styleHint(QStyle::SH_Menu_Mask, &option, this, &menuMask)) {
             setMask(menuMask.region);
         }
         d->itemsDirty = 1;
         d->updateActionRects();
         break; }
     case QEvent::Show:
         d->mouseDown = 0;
         d->updateActionRects();
         if (d->currentAction)
             d->popupAction(d->currentAction, 0, false);
         break;
 #ifndef QT_NO_WHATSTHIS
     case QEvent::QueryWhatsThis:
         e->setAccepted(d->whatsThis.size());
         if (QAction *action = d->actionAt(static_cast<QHelpEvent*>(e)->pos())) {
             if (action->whatsThis().size() || action->menu())
                 e->accept();
         }
         return true;
 #endif
 #ifdef QT_SOFTKEYS_ENABLED
     case QEvent::LanguageChange: {
         d->selectAction->setText(QSoftKeyManager::standardSoftKeyText(QSoftKeyManager::SelectSoftKey));
         d->cancelAction->setText(QSoftKeyManager::standardSoftKeyText(QSoftKeyManager::CancelSoftKey));
         }
         break;
 #endif
     default:
         break;
     }
     return QWidget::event(e);
 }
exec() [1/4]
QAction * QMenu::exec ()
Executes this menu synchronously.
This is equivalent to exec(pos()).
This returns the triggered QAction in either the popup menu or one of its submenus, or 0 if no item was triggered (normally because the user pressed Esc).
In most situations you'll want to specify the position yourself, for example, the current mouse position:
exec(QCursor::pos());
or aligned to a widget:
exec(somewidget.mapToGlobal(QPoint(0,0)));
or in reaction to a QMouseEvent *e:
exec(e->globalPos());
Definition at line 2101 of file qmenu.cpp.
Referenced by QPushButtonPrivate::_q_popupPressed(), QFileDialogPrivate::_q_showContextMenu(), QmlJSDebugger::ToolBarColorBox::contextMenuEvent(), QScrollBar::contextMenuEvent(), QDialog::contextMenuEvent(), QAbstractSpinBox::contextMenuEvent(), QMdiAreaTabBar::contextMenuEvent(), QmlJSDebugger::LiveSelectionTool::createContextMenu(), QWidget::event(), exec(), QScriptEdit::extraAreaMouseEvent(), QmlJSDebugger::ZoomTool::mousePressEvent(), QToolButtonPrivate::popupTimerDone(), and QSidebar::showContextMenu().
 {
     return exec(pos());
 }
exec() [2/4]
QAction * QMenu::exec (const QPoint & p, QAction * action = 0)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Executes this menu synchronously.
Pops up the menu so that the action action will be at the specified global position p. To translate a widget's local coordinates into global coordinates, use QWidget::mapToGlobal().
This returns the triggered QAction in either the popup menu or one of its submenus, or 0 if no item was triggered (normally because the user pressed Esc).
Note that all signals are emitted as usual. If you connect a QAction to a slot and call the menu's exec(), you get the result both via the signal-slot connection and in the return value of exec().
Common usage is to position the menu at the current mouse position:
exec(QCursor::pos());
or aligned to a widget:
exec(somewidget.mapToGlobal(QPoint(0, 0)));
or in reaction to a QMouseEvent *e:
exec(e->globalPos());
When positioning a menu with exec() or popup(), bear in mind that you cannot rely on the menu's current size(). For performance reasons, the menu adapts its size only when necessary. So in many cases, the size before and after the show is different. Instead, use sizeHint() which calculates the proper size depending on the menu's current contents.
See also
popup(), QWidget::mapToGlobal()
Definition at line 2142 of file qmenu.cpp.
 {
     Q_D(QMenu);
     createWinId();
     QEventLoop eventLoop;
     d->eventLoop = &eventLoop;
     popup(p, action);
     QPointer<QObject> guard = this;
     (void) eventLoop.exec();
     if (guard.isNull())
         return 0;
     action = d->syncAction;
     d->syncAction = 0;
     d->eventLoop = 0;
     return action;
 }
exec() [3/4]
QAction * QMenu::exec (QList< QAction *> actions, const QPoint & pos, QAction * at = 0) static
Executes a menu synchronously.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The menu's actions are specified by the list of actions. The menu will pop up so that the specified action, at, appears at global position pos. If at is not specified then the menu appears at position pos.
The function returns the triggered QAction in either the popup menu or one of its submenus, or 0 if no item was triggered (normally because the user pressed Esc).
This is equivalent to:
QMenu menu;
QAction *at = actions[0]; // Assumes actions is not empty
foreach (QAction *a, actions)
    menu.addAction(a);
menu.exec(pos, at);
See also
popup(), QWidget::mapToGlobal()
Definition at line 2215 of file qmenu.cpp.
 {
     // ### Qt 5: merge
     return exec(actions, pos, at, 0);
 }
exec() [4/4]
QAction * QMenu::exec (QList< QAction *> actions, const QPoint & pos, QAction * at, QWidget * parent) static
Executes a menu synchronously.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The menu's actions are specified by the list of actions. The menu will pop up so that the specified action, at, appears at global position pos. If at is not specified then the menu appears at position pos. parent is the menu's parent widget; specifying the parent will provide context when pos alone is not enough to decide where the menu should go (e.g., with multiple desktops or when the parent is embedded in QGraphicsView).
The function returns the triggered QAction in either the popup menu or one of its submenus, or 0 if no item was triggered (normally because the user pressed Esc).
This is equivalent to:
QMenu menu;
QAction *at = actions[0]; // Assumes actions is not empty
foreach (QAction *a, actions)
    menu.addAction(a);
menu.exec(pos, at);
See also
popup(), QWidget::mapToGlobal()
Definition at line 2186 of file qmenu.cpp.
 {
     QMenu menu(parent);
     menu.addActions(actions);
     return menu.exec(pos, at);
 }
focusNextPrevChild()
bool QMenu::focusNextPrevChild (bool next) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2519 of file qmenu.cpp.
 {
     setFocus();
     QKeyEvent ev(QEvent::KeyPress, next ? Qt::Key_Tab : Qt::Key_Backtab, Qt::NoModifier);
     keyPressEvent(&ev);
     return true;
 }
hideEvent()
void QMenu::hideEvent (QHideEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2224 of file qmenu.cpp.
 {
     Q_D(QMenu);
     emit aboutToHide();
     if (d->eventLoop)
         d->eventLoop->exit();
     d->setCurrentAction(0);
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::PopupMenuEnd);
 #endif
 #ifndef QT_NO_MENUBAR
     if (QMenuBar *mb = qobject_cast<QMenuBar*>(d->causedPopup.widget))
         mb->d_func()->setCurrentAction(0);
 #endif
     d->mouseDown = 0;
     d->hasHadMouse = false;
     d->causedPopup.widget = 0;
     d->causedPopup.action = 0;
     if (d->scroll)
         d->scroll->scrollTimer.stop(); //make sure the timer stops
 }
hideTearOffMenu()
void QMenu::hideTearOffMenu ()
This function will forcibly hide the torn off menu making it disappear from the users desktop.
See also
isTearOffMenuVisible() isTearOffEnabled()
Definition at line 1697 of file qmenu.cpp.
Referenced by setTearOffEnabled(), and ~QMenu().
 {
     if (QWidget *w = d_func()->tornPopup)
         w->close();
 }
hovered
void QMenu::hovered (QAction * action) signal
This signal is emitted when a menu action is highlighted; action is the action that caused the signal to be emitted.
Often this is used to update status information.
See also
triggered(), QAction::hovered()
Referenced by actionEvent().
icon()
QIcon QMenu::icon () const
Referenced by setSeparatorsCollapsible(), and setTitle().
initStyleOption()
void QMenu::initStyleOption (QStyleOptionMenuItem * option, const QAction * action) const protected
Initialize option with the values from this menu and information from action.
This method is useful for subclasses when they need a QStyleOptionMenuItem, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom() QMenuBar::initStyleOption()
Definition at line 1222 of file qmenu.cpp.
Referenced by paintEvent().
 {
     if (!option || !action)
         return;
     Q_D(const QMenu);
     option->initFrom(this);
     option->palette = palette();
     option->state = QStyle::State_None;
     if (window()->isActiveWindow())
         option->state |= QStyle::State_Active;
     if (isEnabled() && action->isEnabled()
             && (!action->menu() || action->menu()->isEnabled()))
         option->state |= QStyle::State_Enabled;
     else
         option->palette.setCurrentColorGroup(QPalette::Disabled);
     option->font = action->font().resolve(font());
     option->fontMetrics = QFontMetrics(option->font);
     if (d->currentAction && d->currentAction == action && !d->currentAction->isSeparator()) {
         option->state |= QStyle::State_Selected
                      | (d->mouseDown ? QStyle::State_Sunken : QStyle::State_None);
     }
     option->menuHasCheckableItems = d->hasCheckableItems;
     if (!action->isCheckable()) {
         option->checkType = QStyleOptionMenuItem::NotCheckable;
     } else {
         option->checkType = (action->actionGroup() && action->actionGroup()->isExclusive())
                             ? QStyleOptionMenuItem::Exclusive : QStyleOptionMenuItem::NonExclusive;
         option->checked = action->isChecked();
     }
     if (action->menu())
         option->menuItemType = QStyleOptionMenuItem::SubMenu;
     else if (action->isSeparator())
         option->menuItemType = QStyleOptionMenuItem::Separator;
     else if (d->defaultAction == action)
         option->menuItemType = QStyleOptionMenuItem::DefaultItem;
     else
         option->menuItemType = QStyleOptionMenuItem::Normal;
     if (action->isIconVisibleInMenu())
         option->icon = action->icon();
     QString textAndAccel = action->text();
 #ifndef QT_NO_SHORTCUT
     if (textAndAccel.indexOf(QLatin1Char('\t')) == -1) {
         QKeySequence seq = action->shortcut();
         if (!seq.isEmpty())
             textAndAccel += QLatin1Char('\t') + QString(seq);
     }
 #endif
     option->text = textAndAccel;
     option->tabWidth = d->tabWidth;
     option->maxIconWidth = d->maxIconWidth;
     option->menuRect = rect();
 }
insertMenu()
QAction * QMenu::insertMenu (QAction * before, QMenu * menu)
This convenience function inserts menu before action before and returns the menus menuAction().
See also
QWidget::insertAction(), addMenu()
Definition at line 1597 of file qmenu.cpp.
 {
     QAction *action = menu->menuAction();
     insertAction(before, action);
     return action;
 }
insertSeparator()
QAction * QMenu::insertSeparator (QAction * before)
This convenience function creates a new separator action, i.e.
an action with QAction::isSeparator() returning true. The function inserts the newly created action into this menu's list of actions before action before and returns it.
See also
QWidget::insertAction(), addSeparator()
Definition at line 1612 of file qmenu.cpp.
Referenced by setSeparatorsCollapsible().
 {
     QAction *action = new QAction(this);
     action->setSeparator(true);
     insertAction(before, action);
     return action;
 }
internalDelayedPopup
void QMenu::internalDelayedPopup () private slot
Warning
This function is not part of the public interface.
Definition at line 3048 of file qmenu.cpp.
Referenced by event(), and timerEvent().
 {
     Q_D(QMenu);
     //hide the current item
     if (QMenu *menu = d->activeMenu) {
         d->activeMenu = 0;
         d->hideMenu(menu);
     }
     if (!d->currentAction || !d->currentAction->isEnabled() || !d->currentAction->menu() ||
         !d->currentAction->menu()->isEnabled() || d->currentAction->menu()->isVisible())
         return;
     //setup
     d->activeMenu = d->currentAction->menu();
     d->activeMenu->d_func()->causedPopup.widget = this;
     d->activeMenu->d_func()->causedPopup.action = d->currentAction;
     int subMenuOffset = style()->pixelMetric(QStyle::PM_SubMenuOverlap, 0, this);
     const QRect actionRect(d->actionRect(d->currentAction));
     const QSize menuSize(d->activeMenu->sizeHint());
     const QPoint rightPos(mapToGlobal(QPoint(actionRect.right() + subMenuOffset + 1, actionRect.top())));
     QPoint pos(rightPos);
     //calc sloppy focus buffer
     if (style()->styleHint(QStyle::SH_Menu_SloppySubMenus, 0, this)) {
         QPoint cur = QCursor::pos();
         if (actionRect.contains(mapFromGlobal(cur))) {
             QPoint pts[4];
             pts[0] = QPoint(cur.x(), cur.y() - 2);
             pts[3] = QPoint(cur.x(), cur.y() + 2);
             if (pos.x() >= cur.x())        {
                 pts[1] = QPoint(geometry().right(), pos.y());
                 pts[2] = QPoint(geometry().right(), pos.y() + menuSize.height());
             } else {
                 pts[1] = QPoint(pos.x() + menuSize.width(), pos.y());
                 pts[2] = QPoint(pos.x() + menuSize.width(), pos.y() + menuSize.height());
             }
             QPolygon points(4);
             for(int i = 0; i < 4; i++)
                 points.setPoint(i, mapFromGlobal(pts[i]));
             d->sloppyRegion = QRegion(points);
         }
     }
     //do the popup
     d->activeMenu->popup(pos);
 }
internalSetSloppyAction
void QMenu::internalSetSloppyAction () private slot
Warning
This function is not part of the public interface.
Definition at line 3039 of file qmenu.cpp.
Referenced by timerEvent().
 {
     if (d_func()->sloppyAction)
         d_func()->setCurrentAction(d_func()->sloppyAction, 0);
 }
isEmpty()
bool QMenu::isEmpty () const
Returns true if there are no visible actions inserted into the menu, false otherwise.
Since
4.2
See also
QWidget::actions()
Definition at line 1737 of file qmenu.cpp.
Referenced by QMainWindow::contextMenuEvent(), and QLineEdit::createStandardContextMenu().
 {
     bool ret = true;
     for(int i = 0; ret && i < actions().count(); ++i) {
         const QAction *action = actions().at(i);
         if (!action->isSeparator() && action->isVisible()) {
             ret = false;
         }
     }
     return ret;
 }
isTearOffEnabled()
bool QMenu::isTearOffEnabled () const
Definition at line 1672 of file qmenu.cpp.
 {
     return d_func()->tearoff;
 }
isTearOffMenuVisible()
bool QMenu::isTearOffMenuVisible () const
When a menu is torn off a second menu is shown to display the menu contents in a new window.
When the menu is in this mode and the menu is visible returns true; otherwise false.
See also
hideTearOffMenu() isTearOffEnabled()
Definition at line 1684 of file qmenu.cpp.
 {
     if (d_func()->tornPopup)
         return d_func()->tornPopup->isVisible();
     return false;
 }
keyPressEvent()
void QMenu::keyPressEvent (QKeyEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2530 of file qmenu.cpp.
Referenced by event(), and focusNextPrevChild().
 {
     Q_D(QMenu);
     d->updateActionRects();
     int key = e->key();
     if (isRightToLeft()) {  // in reverse mode open/close key for submenues are reversed
         if (key == Qt::Key_Left)
             key = Qt::Key_Right;
         else if (key == Qt::Key_Right)
             key = Qt::Key_Left;
     }
 #ifndef Q_WS_MAC
     if (key == Qt::Key_Tab) //means down
         key = Qt::Key_Down;
     if (key == Qt::Key_Backtab) //means up
         key = Qt::Key_Up;
 #endif
     bool key_consumed = false;
     switch(key) {
     case Qt::Key_Home:
         key_consumed = true;
         if (d->scroll)
             d->scrollMenu(QMenuPrivate::QMenuScroller::ScrollTop, true);
         break;
     case Qt::Key_End:
         key_consumed = true;
         if (d->scroll)
             d->scrollMenu(QMenuPrivate::QMenuScroller::ScrollBottom, true);
         break;
     case Qt::Key_PageUp:
         key_consumed = true;
         if (d->currentAction && d->scroll) {
             if(d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollUp)
                 d->scrollMenu(QMenuPrivate::QMenuScroller::ScrollUp, true, true);
             else
                 d->scrollMenu(QMenuPrivate::QMenuScroller::ScrollTop, true);
         }
         break;
     case Qt::Key_PageDown:
         key_consumed = true;
         if (d->currentAction && d->scroll) {
             if(d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollDown)
                 d->scrollMenu(QMenuPrivate::QMenuScroller::ScrollDown, true, true);
             else
                 d->scrollMenu(QMenuPrivate::QMenuScroller::ScrollBottom, true);
         }
         break;
     case Qt::Key_Up:
     case Qt::Key_Down: {
         key_consumed = true;
         QAction *nextAction = 0;
         QMenuPrivate::QMenuScroller::ScrollLocation scroll_loc = QMenuPrivate::QMenuScroller::ScrollStay;
         if (!d->currentAction) {
             if(key == Qt::Key_Down) {
                 for(int i = 0; i < d->actions.count(); ++i) {
                     QAction *act = d->actions.at(i);
                     if (d->actionRects.at(i).isNull())
                         continue;
                     if (!act->isSeparator() &&
                         (style()->styleHint(QStyle::SH_Menu_AllowActiveAndDisabled, 0, this)
                          || act->isEnabled())) {
                         nextAction = act;
                         break;
                     }
                 }
             } else {
                 for(int i = d->actions.count()-1; i >= 0; --i) {
                     QAction *act = d->actions.at(i);
                     if (d->actionRects.at(i).isNull())
                         continue;
                     if (!act->isSeparator() &&
                         (style()->styleHint(QStyle::SH_Menu_AllowActiveAndDisabled, 0, this)
                          || act->isEnabled())) {
                         nextAction = act;
                         break;
                     }
                 }
             }
         } else {
             for(int i = 0, y = 0; !nextAction && i < d->actions.count(); i++) {
                 QAction *act = d->actions.at(i);
                 if (act == d->currentAction) {
                     if (key == Qt::Key_Up) {
                         for(int next_i = i-1; true; next_i--) {
                             if (next_i == -1) {
                                 if(!style()->styleHint(QStyle::SH_Menu_SelectionWrap, 0, this))
                                     break;
                                 if (d->scroll)
                                     scroll_loc = QMenuPrivate::QMenuScroller::ScrollBottom;
                                 next_i = d->actionRects.count()-1;
                             }
                             QAction *next = d->actions.at(next_i);
                             if (next == d->currentAction)
                                 break;
                             if (d->actionRects.at(next_i).isNull())
                                 continue;
                             if (next->isSeparator() ||
                                (!next->isEnabled() &&
                                 !style()->styleHint(QStyle::SH_Menu_AllowActiveAndDisabled, 0, this)))
                                 continue;
                             nextAction = next;
                             if (d->scroll && (d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollUp)) {
                                 int topVisible = d->scrollerHeight();
                                 if (d->tearoff)
                                     topVisible += style()->pixelMetric(QStyle::PM_MenuTearoffHeight, 0, this);
                                 if (((y + d->scroll->scrollOffset) - topVisible) <= d->actionRects.at(next_i).height())
                                     scroll_loc = QMenuPrivate::QMenuScroller::ScrollTop;
                             }
                             break;
                         }
                         if (!nextAction && d->tearoff)
                             d->tearoffHighlighted = 1;
                     } else {
                         y += d->actionRects.at(i).height();
                         for(int next_i = i+1; true; next_i++) {
                             if (next_i == d->actionRects.count()) {
                                 if(!style()->styleHint(QStyle::SH_Menu_SelectionWrap, 0, this))
                                     break;
                                 if (d->scroll)
                                     scroll_loc = QMenuPrivate::QMenuScroller::ScrollTop;
                                 next_i = 0;
                             }
                             QAction *next = d->actions.at(next_i);
                             if (next == d->currentAction)
                                 break;
                             if (d->actionRects.at(next_i).isNull())
                                 continue;
                             if (next->isSeparator() ||
                                (!next->isEnabled() &&
                                 !style()->styleHint(QStyle::SH_Menu_AllowActiveAndDisabled, 0, this)))
                                 continue;
                             nextAction = next;
                             if (d->scroll && (d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollDown)) {
                                 int bottomVisible = height() - d->scrollerHeight();
                                 if (d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollUp)
                                     bottomVisible -= d->scrollerHeight();
                                 if (d->tearoff)
                                     bottomVisible -= style()->pixelMetric(QStyle::PM_MenuTearoffHeight, 0, this);
                                 if ((y + d->scroll->scrollOffset + d->actionRects.at(next_i).height()) > bottomVisible)
                                     scroll_loc = QMenuPrivate::QMenuScroller::ScrollBottom;
                             }
                             break;
                         }
                     }
                     break;
                 }
                 y += d->actionRects.at(i).height();
             }
         }
         if (nextAction) {
             if (d->scroll && scroll_loc != QMenuPrivate::QMenuScroller::ScrollStay) {
                 d->scroll->scrollTimer.stop();
                 d->scrollMenu(nextAction, scroll_loc);
             }
             d->setCurrentAction(nextAction, /*popup*/-1, QMenuPrivate::SelectedFromKeyboard);
         }
         break; }
     case Qt::Key_Right:
         if (d->currentAction && d->currentAction->isEnabled() && d->currentAction->menu()) {
             d->popupAction(d->currentAction, 0, true);
             key_consumed = true;
             break;
         }
         //FALL THROUGH
     case Qt::Key_Left: {
         if (d->currentAction && !d->scroll) {
             QAction *nextAction = 0;
             if (key == Qt::Key_Left) {
                 QRect actionR = d->actionRect(d->currentAction);
                 for(int x = actionR.left()-1; !nextAction && x >= 0; x--)
                     nextAction = d->actionAt(QPoint(x, actionR.center().y()));
             } else {
                 QRect actionR = d->actionRect(d->currentAction);
                 for(int x = actionR.right()+1; !nextAction && x < width(); x++)
                     nextAction = d->actionAt(QPoint(x, actionR.center().y()));
             }
             if (nextAction) {
                 d->setCurrentAction(nextAction, /*popup*/-1, QMenuPrivate::SelectedFromKeyboard);
                 key_consumed = true;
             }
         }
         if (!key_consumed && key == Qt::Key_Left && qobject_cast<QMenu*>(d->causedPopup.widget)) {
             QPointer<QWidget> caused = d->causedPopup.widget;
             d->hideMenu(this);
             if (caused)
                 caused->setFocus();
             key_consumed = true;
         }
         break; }
     case Qt::Key_Alt:
         if (d->tornoff)
             break;
         key_consumed = true;
         if (style()->styleHint(QStyle::SH_MenuBar_AltKeyNavigation, 0, this))
         {
             d->hideMenu(this);
 #ifndef QT_NO_MENUBAR
             if (QMenuBar *mb = qobject_cast<QMenuBar*>(QApplication::focusWidget())) {
                 mb->d_func()->setKeyboardMode(false);
             }
 #endif
         }
         break;
     case Qt::Key_Escape:
 #ifdef QT_KEYPAD_NAVIGATION
     case Qt::Key_Back:
 #endif
         key_consumed = true;
         if (d->tornoff) {
             close();
             return;
         }
         {
             QPointer<QWidget> caused = d->causedPopup.widget;
             d->hideMenu(this); // hide after getting causedPopup
 #ifndef QT_NO_MENUBAR
             if (QMenuBar *mb = qobject_cast<QMenuBar*>(caused)) {
                 mb->d_func()->setCurrentAction(d->menuAction);
                 mb->d_func()->setKeyboardMode(true);
             }
 #endif
         }
         break;
     case Qt::Key_Space:
         if (!style()->styleHint(QStyle::SH_Menu_SpaceActivatesItem, 0, this))
             break;
         // for motif, fall through
 #ifdef QT_KEYPAD_NAVIGATION
     case Qt::Key_Select:
 #endif
     case Qt::Key_Return:
     case Qt::Key_Enter: {
         if (!d->currentAction) {
             d->setFirstActionActive();
             key_consumed = true;
             break;
         }
         d->setSyncAction();
         if (d->currentAction->menu())
             d->popupAction(d->currentAction, 0, true);
         else
             d->activateAction(d->currentAction, QAction::Trigger);
         key_consumed = true;
         break; }
 #ifndef QT_NO_WHATSTHIS
     case Qt::Key_F1:
         if (!d->currentAction || d->currentAction->whatsThis().isNull())
             break;
         QWhatsThis::enterWhatsThisMode();
         d->activateAction(d->currentAction, QAction::Trigger);
         return;
 #endif
     default:
         key_consumed = false;
     }
     if (!key_consumed) {                                // send to menu bar
         if ((!e->modifiers() || e->modifiers() == Qt::AltModifier || e->modifiers() == Qt::ShiftModifier) &&
            e->text().length()==1) {
             bool activateAction = false;
             QAction *nextAction = 0;
             if (style()->styleHint(QStyle::SH_Menu_KeyboardSearch, 0, this) && !e->modifiers()) {
                 int best_match_count = 0;
                 d->searchBufferTimer.start(2000, this);
                 d->searchBuffer += e->text();
                 for(int i = 0; i < d->actions.size(); ++i) {
                     int match_count = 0;
                     if (d->actionRects.at(i).isNull())
                         continue;
                     QAction *act = d->actions.at(i);
                     const QString act_text = act->text();
                     for(int c = 0; c < d->searchBuffer.size(); ++c) {
                         if(act_text.indexOf(d->searchBuffer.at(c), 0, Qt::CaseInsensitive) != -1)
                             ++match_count;
                     }
                     if(match_count > best_match_count) {
                         best_match_count = match_count;
                         nextAction = act;
                     }
                 }
             }
 #ifndef QT_NO_SHORTCUT
             else {
                 int clashCount = 0;
                 QAction *first = 0, *currentSelected = 0, *firstAfterCurrent = 0;
                 QChar c = e->text().at(0).toUpper();
                 for(int i = 0; i < d->actions.size(); ++i) {
                     if (d->actionRects.at(i).isNull())
                         continue;
                     QAction *act = d->actions.at(i);
                     QKeySequence sequence = QKeySequence::mnemonic(act->text());
                     int key = sequence[0] & 0xffff;
                     if (key == c.unicode()) {
                         clashCount++;
                         if (!first)
                             first = act;
                         if (act == d->currentAction)
                             currentSelected = act;
                         else if (!firstAfterCurrent && currentSelected)
                             firstAfterCurrent = act;
                     }
                 }
                 if (clashCount == 1)
                     activateAction = true;
                 if (clashCount >= 1) {
                     if (clashCount == 1 || !currentSelected || !firstAfterCurrent)
                         nextAction = first;
                     else
                         nextAction = firstAfterCurrent;
                 }
             }
 #endif
             if (nextAction) {
                 key_consumed = true;
                 if(d->scroll)
                     d->scrollMenu(nextAction, QMenuPrivate::QMenuScroller::ScrollCenter, false);
                 d->setCurrentAction(nextAction, 0, QMenuPrivate::SelectedFromElsewhere, true);
                 if (!nextAction->menu() && activateAction) {
                     d->setSyncAction();
                     d->activateAction(nextAction, QAction::Trigger);
                 }
             }
         }
         if (!key_consumed) {
 #ifndef QT_NO_MENUBAR
             if (QMenuBar *mb = qobject_cast<QMenuBar*>(d->topCausedWidget())) {
                 QAction *oldAct = mb->d_func()->currentAction;
                 QApplication::sendEvent(mb, e);
                 if (mb->d_func()->currentAction != oldAct)
                     key_consumed = true;
             }
 #endif
         }
 #ifdef Q_OS_WIN32
         if (key_consumed && (e->key() == Qt::Key_Control || e->key() == Qt::Key_Shift || e->key() == Qt::Key_Meta))
             QApplication::beep();
 #endif // Q_OS_WIN32
     }
     if (key_consumed)
         e->accept();
     else
         e->ignore();
 }
leaveEvent()
void QMenu::leaveEvent (QEvent *) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2933 of file qmenu.cpp.
 {
     Q_D(QMenu);
     d->sloppyAction = 0;
     if (!d->sloppyRegion.isEmpty())
         d->sloppyRegion = QRegion();
     if (!d->activeMenu && d->currentAction)
         setActiveAction(0);
 }
macMenu()
OSMenuRef QMenu::macMenu (OSMenuRef merge = 0)
Warning
This function is not part of the public interface.
This function will return the OSMenuRef used to create the native menu bar bindings.
If Qt is built against Carbon, the OSMenuRef is a MenuRef that can be used with Carbon's Menu Manager API.
If Qt is built against Cocoa, the OSMenuRef is a NSMenu pointer.
Warning
This function is not portable.
See also
QMenuBar::macMenu()
Definition at line 1610 of file qmenu_mac.mm.
Referenced by actualMenuItemVisibility(), qt_mac_set_dock_menu(), QMenuBarPrivate::QMacMenuBarPrivate::syncAction(), and QMenuPrivate::QMacMenuPrivate::syncAction().
 { return d_func()->macMenu(merge); }
menuAction()
QAction * QMenu::menuAction () const
Returns the action associated with this menu.
Definition at line 711 of file qmenu.cpp.
Referenced by QMultiInputContext::actions(), QMenuBar::addMenu(), addMenu(), QMenuBar::defaultAction(), QMenuBar::insertMenu(), insertMenu(), QToolButton::setMenu(), setSeparatorsCollapsible(), and waitForPopup().
 {
     return d_func()->menuAction;
 }
mouseMoveEvent()
void QMenu::mouseMoveEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2887 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (!isVisible() || d->aboutToHide || d->mouseEventTaken(e))
         return;
     d->motions++;
     if (d->motions == 0) // ignore first mouse move event (see enterEvent())
         return;
     d->hasHadMouse = d->hasHadMouse || rect().contains(e->pos());
     QAction *action = d->actionAt(e->pos());
     if (!action || action->isSeparator()) {
         if (d->hasHadMouse
             && d->sloppyDelayTimer == 0 // Keep things as they are while we're moving to the submenu
             && (!d->currentAction || (action && action->isSeparator())
                 || !(d->currentAction->menu() && d->currentAction->menu()->isVisible())))
             d->setCurrentAction(0);
         return;
     } else if(e->buttons()) {
         d->mouseDown = this;
     }
     if (d->sloppyRegion.contains(e->pos())) {
         if (d->sloppyAction != action && d->sloppyDelayTimer != 0) {
             killTimer(d->sloppyDelayTimer);
             d->sloppyDelayTimer = 0;
         }
         if (d->sloppyDelayTimer == 0) {
             d->sloppyAction = action;
             d->sloppyDelayTimer = startTimer(style()->styleHint(QStyle::SH_Menu_SubMenuPopupDelay, 0, this)*6);
         }
     } else if (action != d->currentAction) {
         d->setCurrentAction(action, style()->styleHint(QStyle::SH_Menu_SubMenuPopupDelay, 0, this));
     }
 }
mousePressEvent()
void QMenu::mousePressEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2360 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (d->aboutToHide || d->mouseEventTaken(e))
         return;
     if (!rect().contains(e->pos())) {
          if (d->noReplayFor
              && QRect(d->noReplayFor->mapToGlobal(QPoint()), d->noReplayFor->size()).contains(e->globalPos()))
              setAttribute(Qt::WA_NoMouseReplay);
          if (d->eventLoop) // synchronous operation
              d->syncAction = 0;
         d->hideUpToMenuBar();
         return;
     }
     d->mouseDown = this;
     QAction *action = d->actionAt(e->pos());
     d->setCurrentAction(action, 20);
     update();
 }
mouseReleaseEvent()
void QMenu::mouseReleaseEvent (QMouseEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2384 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (d->aboutToHide || d->mouseEventTaken(e))
         return;
     if(d->mouseDown != this) {
         d->mouseDown = 0;
         return;
     }
     d->mouseDown = 0;
     d->setSyncAction();
     QAction *action = d->actionAt(e->pos());
     if (action && action == d->currentAction) {
         if (!action->menu()){
 #if defined(Q_WS_WIN)
             //On Windows only context menus can be activated with the right button
             if (e->button() == Qt::LeftButton || d->topCausedWidget() == 0)
 #endif
                 d->activateAction(action, QAction::Trigger);
         }
     } else if (d->hasMouseMoved(e->globalPos())) {
         d->hideUpToMenuBar();
     }
 }
paintEvent()
void QMenu::paintEvent (QPaintEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2249 of file qmenu.cpp.
 {
     Q_D(QMenu);
     d->updateActionRects();
     QPainter p(this);
     QRegion emptyArea = QRegion(rect());
     QStyleOptionMenuItem menuOpt;
     menuOpt.initFrom(this);
     menuOpt.state = QStyle::State_None;
     menuOpt.checkType = QStyleOptionMenuItem::NotCheckable;
     menuOpt.maxIconWidth = 0;
     menuOpt.tabWidth = 0;
     style()->drawPrimitive(QStyle::PE_PanelMenu, &menuOpt, &p, this);
     //draw the items that need updating..
     for (int i = 0; i < d->actions.count(); ++i) {
         QAction *action = d->actions.at(i);
         QRect adjustedActionRect = d->actionRects.at(i);
         if (!e->rect().intersects(adjustedActionRect)
             || d->widgetItems.value(action))
            continue;
         //set the clip region to be extra safe (and adjust for the scrollers)
         QRegion adjustedActionReg(adjustedActionRect);
         emptyArea -= adjustedActionReg;
         p.setClipRegion(adjustedActionReg);
         QStyleOptionMenuItem opt;
         initStyleOption(&opt, action);
         opt.rect = adjustedActionRect;
         style()->drawControl(QStyle::CE_MenuItem, &opt, &p, this);
     }
     const int fw = style()->pixelMetric(QStyle::PM_MenuPanelWidth, 0, this);
     //draw the scroller regions..
     if (d->scroll) {
         menuOpt.menuItemType = QStyleOptionMenuItem::Scroller;
         menuOpt.state |= QStyle::State_Enabled;
         if (d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollUp) {
             menuOpt.rect.setRect(fw, fw, width() - (fw * 2), d->scrollerHeight());
             emptyArea -= QRegion(menuOpt.rect);
             p.setClipRect(menuOpt.rect);
             style()->drawControl(QStyle::CE_MenuScroller, &menuOpt, &p, this);
         }
         if (d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollDown) {
             menuOpt.rect.setRect(fw, height() - d->scrollerHeight() - fw, width() - (fw * 2),
                                      d->scrollerHeight());
             emptyArea -= QRegion(menuOpt.rect);
             menuOpt.state |= QStyle::State_DownArrow;
             p.setClipRect(menuOpt.rect);
             style()->drawControl(QStyle::CE_MenuScroller, &menuOpt, &p, this);
         }
     }
     //paint the tear off..
     if (d->tearoff) {
         menuOpt.menuItemType = QStyleOptionMenuItem::TearOff;
         menuOpt.rect.setRect(fw, fw, width() - (fw * 2),
                              style()->pixelMetric(QStyle::PM_MenuTearoffHeight, 0, this));
         if (d->scroll && d->scroll->scrollFlags & QMenuPrivate::QMenuScroller::ScrollUp)
             menuOpt.rect.translate(0, d->scrollerHeight());
         emptyArea -= QRegion(menuOpt.rect);
         p.setClipRect(menuOpt.rect);
         menuOpt.state = QStyle::State_None;
         if (d->tearoffHighlighted)
             menuOpt.state |= QStyle::State_Selected;
         style()->drawControl(QStyle::CE_MenuTearoff, &menuOpt, &p, this);
     }
     //draw border
     if (fw) {
         QRegion borderReg;
         borderReg += QRect(0, 0, fw, height()); //left
         borderReg += QRect(width()-fw, 0, fw, height()); //right
         borderReg += QRect(0, 0, width(), fw); //top
         borderReg += QRect(0, height()-fw, width(), fw); //bottom
         p.setClipRegion(borderReg);
         emptyArea -= borderReg;
         QStyleOptionFrame frame;
         frame.rect = rect();
         frame.palette = palette();
         frame.state = QStyle::State_None;
         frame.lineWidth = style()->pixelMetric(QStyle::PM_MenuPanelWidth);
         frame.midLineWidth = 0;
         style()->drawPrimitive(QStyle::PE_FrameMenu, &frame, &p, this);
     }
     //finally the rest of the space
     p.setClipRegion(emptyArea);
     menuOpt.state = QStyle::State_None;
     menuOpt.menuItemType = QStyleOptionMenuItem::EmptyArea;
     menuOpt.checkType = QStyleOptionMenuItem::NotCheckable;
     menuOpt.rect = rect();
     menuOpt.menuRect = rect();
     style()->drawControl(QStyle::CE_MenuEmptyArea, &menuOpt, &p, this);
 }
popup()
void QMenu::popup (const QPoint & p, QAction * atAction = 0)
Displays the menu so that the action atAction will be at the specified global position p.
Use popup() on the relevant QAction instead.
To translate a widget's local coordinates into global coordinates, use QWidget::mapToGlobal().
When positioning a menu with exec() or popup(), bear in mind that you cannot rely on the menu's current size(). For performance reasons, the menu adapts its size only when necessary, so in many cases, the size before and after the show is different. Instead, use sizeHint() which calculates the proper size depending on the menu's current contents.
See also
QWidget::mapToGlobal(), exec()
Definition at line 1847 of file qmenu.cpp.
Referenced by QMessageBoxDetailsText::TextEdit::contextMenuEvent(), QLabel::contextMenuEvent(), QTextControlPrivate::contextMenuEvent(), QMainWindow::contextMenuEvent(), exec(), QSystemTrayIconSys::mousePressEvent(), setSeparatorsCollapsible(), and QSystemTrayIconSys::winEvent().
 {
     Q_D(QMenu);
 #ifndef Q_OS_SYMBIAN
     if (d->scroll) { // reset scroll state from last popup
         if (d->scroll->scrollOffset)
             d->itemsDirty = 1; // sizeHint will be incorrect if there is previous scroll
         d->scroll->scrollOffset = 0;
         d->scroll->scrollFlags = QMenuPrivate::QMenuScroller::ScrollNone;
     }
 #endif
     d->tearoffHighlighted = 0;
     d->motions = 0;
     d->doChildEffects = true;
     d->updateLayoutDirection();
 #ifndef QT_NO_MENUBAR
     // if this menu is part of a chain attached to a QMenuBar, set the
     // _NET_WM_WINDOW_TYPE_DROPDOWN_MENU X11 window type
     setAttribute(Qt::WA_X11NetWmWindowTypeDropDownMenu, qobject_cast<QMenuBar *>(d->topCausedWidget()) != 0);
 #endif
     ensurePolished(); // Get the right font
     emit aboutToShow();
     const bool actionListChanged = d->itemsDirty;
     d->updateActionRects();
     QPoint pos;
     QPushButton *causedButton = qobject_cast<QPushButton*>(d->causedPopup.widget);
     if (actionListChanged && causedButton)
         pos = QPushButtonPrivate::get(causedButton)->adjustedMenuPosition();
     else
         pos = p;
     QSize size = sizeHint();
     QRect screen;
 #ifndef QT_NO_GRAPHICSVIEW
     bool isEmbedded = !bypassGraphicsProxyWidget(this) && d->nearestGraphicsProxyWidget(this);
     if (isEmbedded)
         screen = d->popupGeometry(this);
     else
 #endif
     screen = d->popupGeometry(QApplication::desktop()->screenNumber(p));
     const int desktopFrame = style()->pixelMetric(QStyle::PM_MenuDesktopFrameWidth, 0, this);
     bool adjustToDesktop = !window()->testAttribute(Qt::WA_DontShowOnScreen);
     if (!d->scroll) {
         // if the screens have very different geometries and the menu is too big, we have to recalculate
         if (size.height() > screen.height() || size.width() > screen.width()) {
             size = d->adjustMenuSizeForScreen(screen);
             adjustToDesktop = true;
         }
         // Layout is not right, we might be able to save horizontal space
         if (d->ncols >1 && size.height() < screen.height()) {
             size = d->adjustMenuSizeForScreen(screen);
             adjustToDesktop = true;
         }
     }
 #ifdef QT_KEYPAD_NAVIGATION
     if (!atAction && QApplication::keypadNavigationEnabled()) {
         // Try to have one item activated
         if (d->defaultAction && d->defaultAction->isEnabled()) {
             atAction = d->defaultAction;
             // TODO: This works for first level menus, not yet sub menus
         } else {
             foreach (QAction *action, d->actions)
                 if (action->isEnabled()) {
                     atAction = action;
                     break;
                 }
         }
         d->currentAction = atAction;
     }
 #endif
     if (d->ncols > 1) {
         pos.setY(screen.top() + desktopFrame);
     } else if (atAction) {
         for (int i = 0, above_height = 0; i < d->actions.count(); i++) {
             QAction *action = d->actions.at(i);
             if (action == atAction) {
                 int newY = pos.y() - above_height;
                 if (d->scroll && newY < desktopFrame) {
                     d->scroll->scrollFlags = d->scroll->scrollFlags
                                              | QMenuPrivate::QMenuScroller::ScrollUp;
                     d->scroll->scrollOffset = newY;
                     newY = desktopFrame;
                 }
                 pos.setY(newY);
                 if (d->scroll && d->scroll->scrollFlags != QMenuPrivate::QMenuScroller::ScrollNone
                     && !style()->styleHint(QStyle::SH_Menu_FillScreenWithScroll, 0, this)) {
                     int below_height = above_height + d->scroll->scrollOffset;
                     for (int i2 = i; i2 < d->actionRects.count(); i2++)
                         below_height += d->actionRects.at(i2).height();
                     size.setHeight(below_height);
                 }
                 break;
             } else {
                 above_height += d->actionRects.at(i).height();
             }
         }
     }
     QPoint mouse = QCursor::pos();
     d->mousePopupPos = mouse;
     const bool snapToMouse = !d->causedPopup.widget && (QRect(p.x() - 3, p.y() - 3, 6, 6).contains(mouse));
     const QSize menuSize(sizeHint());
     if (adjustToDesktop) {
         // handle popup falling "off screen"
         if (isRightToLeft()) {
             if (snapToMouse) // position flowing left from the mouse
                 pos.setX(mouse.x() - size.width());
 #ifndef QT_NO_MENUBAR
             // if in a menubar, it should be right-aligned
             if (qobject_cast<QMenuBar*>(d->causedPopup.widget))
                 pos.rx() -= size.width();
 #endif //QT_NO_MENUBAR
             if (pos.x() < screen.left() + desktopFrame)
                 pos.setX(qMax(p.x(), screen.left() + desktopFrame));
             if (pos.x() + size.width() - 1 > screen.right() - desktopFrame)
                 pos.setX(qMax(p.x() - size.width(), screen.right() - desktopFrame - size.width() + 1));
         } else {
             if (pos.x() + size.width() - 1 > screen.right() - desktopFrame)
                 pos.setX(screen.right() - desktopFrame - size.width() + 1);
             if (pos.x() < screen.left() + desktopFrame)
                 pos.setX(screen.left() + desktopFrame);
         }
         if (pos.y() + size.height() - 1 > screen.bottom() - desktopFrame) {
             if(snapToMouse)
                 pos.setY(qMin(mouse.y() - (size.height() + desktopFrame), screen.bottom()-desktopFrame-size.height()+1));
             else
                 pos.setY(qMax(p.y() - (size.height() + desktopFrame), screen.bottom()-desktopFrame-size.height()+1));
         } else if (pos.y() < screen.top() + desktopFrame) {
             pos.setY(screen.top() + desktopFrame);
         }
         if (pos.y() < screen.top() + desktopFrame)
             pos.setY(screen.top() + desktopFrame);
         if (pos.y() + menuSize.height() - 1 > screen.bottom() - desktopFrame) {
             if (d->scroll) {
                 d->scroll->scrollFlags |= uint(QMenuPrivate::QMenuScroller::ScrollDown);
                 int y = qMax(screen.y(),pos.y());
                 size.setHeight(screen.bottom() - (desktopFrame * 2) - y);
             } else {
                 // Too big for screen, bias to see bottom of menu (for some reason)
                 pos.setY(screen.bottom() - size.height() + 1);
             }
         }
     }
     const int subMenuOffset = style()->pixelMetric(QStyle::PM_SubMenuOverlap, 0, this);
     QMenu *caused = qobject_cast<QMenu*>(d_func()->causedPopup.widget);
     if (caused && caused->geometry().width() + menuSize.width() + subMenuOffset < screen.width()) {
         QRect parentActionRect(caused->d_func()->actionRect(caused->d_func()->currentAction));
         const QPoint actionTopLeft = caused->mapToGlobal(parentActionRect.topLeft());
         parentActionRect.moveTopLeft(actionTopLeft);
         if (isRightToLeft()) {
             if ((pos.x() + menuSize.width() > parentActionRect.left() - subMenuOffset)
                 && (pos.x() < parentActionRect.right()))
             {
                 pos.rx() = parentActionRect.left() - menuSize.width();
                 if (pos.x() < screen.x())
                     pos.rx() = parentActionRect.right();
                 if (pos.x() + menuSize.width() > screen.x() + screen.width())
                     pos.rx() = screen.x();
             }
         } else {
             if ((pos.x() < parentActionRect.right() + subMenuOffset)
                 && (pos.x() + menuSize.width() > parentActionRect.left()))
             {
                 pos.rx() = parentActionRect.right();
                 if (pos.x() + menuSize.width() > screen.x() + screen.width())
                     pos.rx() = parentActionRect.left() - menuSize.width();
                 if (pos.x() < screen.x())
                     pos.rx() = screen.x() + screen.width() - menuSize.width();
             }
         }
     }
     setGeometry(QRect(pos, size));
 #ifndef QT_NO_EFFECTS
     int hGuess = isRightToLeft() ? QEffects::LeftScroll : QEffects::RightScroll;
     int vGuess = QEffects::DownScroll;
     if (isRightToLeft()) {
         if ((snapToMouse && (pos.x() + size.width() / 2 > mouse.x())) ||
            (qobject_cast<QMenu*>(d->causedPopup.widget) && pos.x() + size.width() / 2 > d->causedPopup.widget->x()))
             hGuess = QEffects::RightScroll;
     } else {
         if ((snapToMouse && (pos.x() + size.width() / 2 < mouse.x())) ||
            (qobject_cast<QMenu*>(d->causedPopup.widget) && pos.x() + size.width() / 2 < d->causedPopup.widget->x()))
             hGuess = QEffects::LeftScroll;
     }
 #ifndef QT_NO_MENUBAR
     if ((snapToMouse && (pos.y() + size.height() / 2 < mouse.y())) ||
        (qobject_cast<QMenuBar*>(d->causedPopup.widget) &&
         pos.y() + size.width() / 2 < d->causedPopup.widget->mapToGlobal(d->causedPopup.widget->pos()).y()))
        vGuess = QEffects::UpScroll;
 #endif
     if (QApplication::isEffectEnabled(Qt::UI_AnimateMenu)) {
         bool doChildEffects = true;
 #ifndef QT_NO_MENUBAR
         if (QMenuBar *mb = qobject_cast<QMenuBar*>(d->causedPopup.widget)) {
             doChildEffects = mb->d_func()->doChildEffects;
             mb->d_func()->doChildEffects = false;
         } else
 #endif
         if (QMenu *m = qobject_cast<QMenu*>(d->causedPopup.widget)) {
             doChildEffects = m->d_func()->doChildEffects;
             m->d_func()->doChildEffects = false;
         }
         if (doChildEffects) {
             if (QApplication::isEffectEnabled(Qt::UI_FadeMenu))
                 qFadeEffect(this);
             else if (d->causedPopup.widget)
                 qScrollEffect(this, qobject_cast<QMenu*>(d->causedPopup.widget) ? hGuess : vGuess);
             else
                 qScrollEffect(this, hGuess | vGuess);
         } else {
             // kill any running effect
             qFadeEffect(0);
             qScrollEffect(0);
             show();
         }
     } else
 #endif
     {
         show();
     }
 #ifndef QT_NO_ACCESSIBILITY
     QAccessible::updateAccessibility(this, 0, QAccessible::PopupMenuStart);
 #endif
 }
separatorsCollapsible()
bool QMenu::separatorsCollapsible () const
Referenced by setNoReplayFor().
setActiveAction()
void QMenu::setActiveAction (QAction * act)
Sets the currently highlighted action to act.
Definition at line 1707 of file qmenu.cpp.
Referenced by QAccessibleMenu::doAction(), QMenuPrivate::hideMenu(), and leaveEvent().
 {
     Q_D(QMenu);
     d->setCurrentAction(act, 0);
     if (d->scroll)
         d->scrollMenu(act, QMenuPrivate::QMenuScroller::ScrollCenter);
 }
setDefaultAction()
void QMenu::setDefaultAction (QAction * act)
This sets the default action to act.
The default action may have a visual cue, depending on the current QStyle. A default action usually indicates what will happen by default when a drop occurs.
See also
defaultAction()
Definition at line 1627 of file qmenu.cpp.
 {
     d_func()->defaultAction = act;
 }
setIcon()
void QMenu::setIcon (const QIcon & icon)
Definition at line 754 of file qmenu.cpp.
Referenced by QMenuBar::addMenu(), and addMenu().
 {
     d_func()->menuAction->setIcon(icon);
 }
setNoReplayFor()
void QMenu::setNoReplayFor (QWidget * noReplayFor)
Warning
This function is not part of the public interface.
Definition at line 3164 of file qmenu.cpp.
Referenced by QPushButtonPrivate::_q_popupPressed(), and QToolButtonPrivate::popupTimerDone().
 {
 #ifdef Q_WS_WIN
     d_func()->noReplayFor = noReplayFor;
 #else
     Q_UNUSED(noReplayFor);
 #endif
 }
setSeparatorsCollapsible()
void QMenu::setSeparatorsCollapsible (bool collapse)
Definition at line 3194 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (d->collapsibleSeparators == collapse)
         return;
     d->collapsibleSeparators = collapse;
     d->itemsDirty = 1;
     if (isVisible()) {
         d->updateActionRects();
         update();
     }
 #ifdef Q_WS_MAC
     if (d->mac_menu)
         d->syncSeparatorsCollapsible(collapse);
 #endif
 }
setTearOffEnabled()
void QMenu::setTearOffEnabled (bool b)
Definition at line 1658 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (d->tearoff == b)
         return;
     if (!b)
         hideTearOffMenu();
     d->tearoff = b;
     d->itemsDirty = true;
     if (isVisible())
         resize(sizeHint());
 }
setTitle()
void QMenu::setTitle (const QString & title)
Definition at line 732 of file qmenu.cpp.
Referenced by QScriptDebugger::createStandardMenu(), menuItemEntry(), and QUnicodeControlCharacterMenu::QUnicodeControlCharacterMenu().
 {
     d_func()->menuAction->setText(text);
 }
sizeHint()
QSize QMenu::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1805 of file qmenu.cpp.
Referenced by QWorkspacePrivate::_q_showOperationMenu(), QTornOffMenu::actionEvent(), actionEvent(), QPushButtonPrivate::adjustedMenuPosition(), changeEvent(), popup(), QToolButtonPrivate::popupTimerDone(), and setTearOffEnabled().
 {
     Q_D(const QMenu);
     d->updateActionRects();
     QSize s;
     for (int i = 0; i < d->actionRects.count(); ++i) {
         const QRect &rect = d->actionRects.at(i);
         if (rect.isNull())
             continue;
         if (rect.bottom() >= s.height())
             s.setHeight(rect.y() + rect.height());
         if (rect.right() >= s.width())
             s.setWidth(rect.x() + rect.width());
     }
     // Note that the action rects calculated above already include
     // the top and left margins, so we only need to add margins for
     // the bottom and right.
     QStyleOption opt(0);
     opt.init(this);
     const int fw = style()->pixelMetric(QStyle::PM_MenuPanelWidth, &opt, this);
     s.rwidth() += style()->pixelMetric(QStyle::PM_MenuHMargin, &opt, this) + fw + d->rightmargin;
     s.rheight() += style()->pixelMetric(QStyle::PM_MenuVMargin, &opt, this) + fw + d->bottommargin;
     return style()->sizeFromContents(QStyle::CT_Menu, &opt,
                                     s.expandedTo(QApplication::globalStrut()), this);
 }
timerEvent()
void QMenu::timerEvent (QTimerEvent * e) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 2947 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (d->scroll && d->scroll->scrollTimer.timerId() == e->timerId()) {
         d->scrollMenu((QMenuPrivate::QMenuScroller::ScrollDirection)d->scroll->scrollDirection);
         if (d->scroll->scrollFlags == QMenuPrivate::QMenuScroller::ScrollNone)
             d->scroll->scrollTimer.stop();
     } else if(d->menuDelayTimer.timerId() == e->timerId()) {
         d->menuDelayTimer.stop();
         internalDelayedPopup();
     } else if (d->sloppyDelayTimer == e->timerId()) {
         killTimer(d->sloppyDelayTimer);
         d->sloppyDelayTimer = 0;
         internalSetSloppyAction();
     } else if(d->searchBufferTimer.timerId() == e->timerId()) {
         d->searchBuffer.clear();
     }
 }
title()
QString QMenu::title () const
Referenced by menuAction().
triggered
void QMenu::triggered (QAction * action) signal
This signal is emitted when an action in this menu is triggered.
action is the action that caused the signal to be emitted.
Normally, you connect each menu action's QAction::triggered() signal to its own custom slot, but sometimes you will want to connect several actions to a single slot, for example, when you have a group of closely related actions, such as "left justify", "center", "right justify".
Note
This signal is emitted for the main parent menu in a hierarchy. Hence, only the parent menu needs to be connected to a slot; sub-menus need not be connected.
See also
hovered(), QAction::triggered()
Referenced by actionEvent(), and addAction().
wceCommands()
QAction * QMenu::wceCommands (uint command) protected
This function sends native Windows CE commands to Qt menus.
Warning
This function is not part of the public interface.
Definition at line 297 of file qmenu_wince.cpp.
Referenced by QMenuPrivate::wceCommands(), and QMenuBarPrivate::wceEmitSignals().
 {
     Q_D(QMenu);
     return d->wceCommands(command);
 }
wceMenu()
HMENU QMenu::wceMenu ()
This function will return the HMENU used to create the native Windows CE menu bar bindings.
Warning
This function is not part of the public interface.
Definition at line 478 of file qmenu_wince.cpp.
Referenced by qt_wce_insert_action().
 {
     return d_func()->wceMenu();
 }
wheelEvent()
void QMenu::wheelEvent (QWheelEvent * e) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 2348 of file qmenu.cpp.
 {
     Q_D(QMenu);
     if (d->scroll && rect().contains(e->pos()))
         d->scrollMenu(e->delta() > 0 ?
                       QMenuPrivate::QMenuScroller::ScrollUp : QMenuPrivate::QMenuScroller::ScrollDown);
 }
Friends and Related Functions
Q3PopupMenu
friend class Q3PopupMenu friend
Definition at line 413 of file qmenu.h.
QAction
friend class QAction friend
Definition at line 415 of file qmenu.h.
Referenced by addAction(), addSeparator(), QMenuPrivate::init(), insertSeparator(), and setSeparatorsCollapsible().
QComboBox
friend class QComboBox friend
Definition at line 414 of file qmenu.h.
QMenuBar
friend class QMenuBar friend
Definition at line 410 of file qmenu.h.
QMenuBarPrivate
friend class QMenuBarPrivate friend
Definition at line 411 of file qmenu.h.
qt_mac_activate_action
bool qt_mac_activate_action (OSMenuRef menu, uint command, QAction::ActionEvent action_e, bool by_accel) friend
Definition at line 209 of file qmenu_mac.mm.
 {
     //fire event
     QMacMenuAction *action = 0;
     if (GetMenuCommandProperty(menu, command, kMenuCreatorQt, kMenuPropertyQAction, sizeof(action), 0, &action) != noErr) {
         QMenuMergeList *list = 0;
         GetMenuItemProperty(menu, 0, kMenuCreatorQt, kMenuPropertyMergeList,
                             sizeof(list), 0, &list);
         if (!list && qt_mac_current_menubar.qmenubar && qt_mac_current_menubar.qmenubar->isNativeMenuBar()) {
             MenuRef apple_menu = qt_mac_current_menubar.qmenubar->d_func()->mac_menubar->apple_menu;
             GetMenuItemProperty(apple_menu, 0, kMenuCreatorQt, kMenuPropertyMergeList, sizeof(list), 0, &list);
             if (list)
                 menu = apple_menu;
         }
         if (list) {
             for(int i = 0; i < list->size(); ++i) {
                 QMenuMergeItem item = list->at(i);
                 if (item.command == command && item.action) {
                     action = item.action;
                     break;
                 }
             }
         }
         if (!action)
             return false;
     }
     if (action_e == QAction::Trigger && by_accel && action->ignore_accel) //no, not a real accel (ie tab)
         return false;
     // Unhighlight the highlighted menu item before triggering the action to
     // prevent items from staying highlighted while a modal dialog is shown.
     // This also fixed the problem that parentless modal dialogs leave
     // the menu item highlighted (since the menu bar is cleared for these types of dialogs).
     if (action_e == QAction::Trigger)
         HiliteMenu(0);
     action->action->activate(action_e);
     //now walk up firing for each "caused" widget (like in the platform independent menu)
     QWidget *caused = 0;
     if (action_e == QAction::Hover && GetMenuItemProperty(menu, 0, kMenuCreatorQt, kMenuPropertyCausedQWidget, sizeof(caused), 0, &caused) == noErr) {
         MenuRef caused_menu = 0;
         if (QMenu *qmenu2 = qobject_cast<QMenu*>(caused))
             caused_menu = qmenu2->macMenu();
         else if (QMenuBar *qmenubar2 = qobject_cast<QMenuBar*>(caused))
             caused_menu = qmenubar2->macMenu();
         else
             caused_menu = 0;
         while(caused_menu) {
             //fire
             QWidget *widget = 0;
             GetMenuItemProperty(caused_menu, 0, kMenuCreatorQt, kMenuPropertyQWidget, sizeof(widget), 0, &widget);
             if (QMenu *qmenu = qobject_cast<QMenu*>(widget)) {
                 action->action->showStatusText(widget);
                 emit qmenu->hovered(action->action);
             } else if (QMenuBar *qmenubar = qobject_cast<QMenuBar*>(widget)) {
                 action->action->showStatusText(widget);
                 emit qmenubar->hovered(action->action);
                 break; //nothing more..
             }
             //walk up
             if (GetMenuItemProperty(caused_menu, 0, kMenuCreatorQt, kMenuPropertyCausedQWidget,
                                     sizeof(caused), 0, &caused) != noErr)
                 break;
             if (QMenu *qmenu2 = qobject_cast<QMenu*>(caused))
                 caused_menu = qmenu2->macMenu();
             else if (QMenuBar *qmenubar2 = qobject_cast<QMenuBar*>(caused))
                 caused_menu = qmenubar2->macMenu();
             else
                 caused_menu = 0;
         }
     }
     return true;
 }
qt_mac_emit_menuSignals
void qt_mac_emit_menuSignals (QMenu * , bool) friend
qt_mac_menu_emit_hovered
void qt_mac_menu_emit_hovered (QMenu * menu, QAction * action) friend
qt_mac_menu_event
OSStatus qt_mac_menu_event (EventHandlerCallRef er, EventRef event, void *) friend
Definition at line 397 of file qmenu_mac.mm.
 {
     QScopedLoopLevelCounter loopLevelCounter(QApplicationPrivate::instance()->threadData);
     bool handled_event = true;
     UInt32 ekind = GetEventKind(event), eclass = GetEventClass(event);
     switch(eclass) {
     case kEventClassCommand:
         if (ekind == kEventCommandProcess) {
             UInt32 context;
             GetEventParameter(event, kEventParamMenuContext, typeUInt32,
                               0, sizeof(context), 0, &context);
             HICommand cmd;
             GetEventParameter(event, kEventParamDirectObject, typeHICommand,
                               0, sizeof(cmd), 0, &cmd);
             if (!mac_keyboard_grabber && (context & kMenuContextKeyMatching)) {
                 QMacMenuAction *action = 0;
                 if (GetMenuCommandProperty(cmd.menu.menuRef, cmd.commandID, kMenuCreatorQt,
                                           kMenuPropertyQAction, sizeof(action), 0, &action) == noErr) {
                     QWidget *widget = 0;
                     if (qApp->activePopupWidget())
                         widget = (qApp->activePopupWidget()->focusWidget() ?
                                   qApp->activePopupWidget()->focusWidget() : qApp->activePopupWidget());
                     else if (QApplicationPrivate::focus_widget)
                         widget = QApplicationPrivate::focus_widget;
                     if (widget) {
                         int key = action->action->shortcut();
                         QKeyEvent accel_ev(QEvent::ShortcutOverride, (key & (~Qt::KeyboardModifierMask)),
                                            Qt::KeyboardModifiers(key & Qt::KeyboardModifierMask));
                         accel_ev.ignore();
                         qt_sendSpontaneousEvent(widget, &accel_ev);
                         if (accel_ev.isAccepted()) {
                             handled_event = false;
                             break;
                         }
                     }
                 }
             }
             handled_event = qt_mac_activate_action(cmd.menu.menuRef, cmd.commandID,
                                                    QAction::Trigger, context & kMenuContextKeyMatching);
         }
         break;
     case kEventClassMenu: {
         MenuRef menu;
         GetEventParameter(event, kEventParamDirectObject, typeMenuRef, NULL, sizeof(menu), NULL, &menu);
         if (ekind == kEventMenuMatchKey) {
             // Don't activate any actions if we are showing a native modal dialog,
             // the key events should go to the dialog in this case.
             if (QApplicationPrivate::native_modal_dialog_active)
                 return menuItemNotFoundErr;
              handled_event = false;
         } else if (ekind == kEventMenuTargetItem) {
             MenuCommand command;
             GetEventParameter(event, kEventParamMenuCommand, typeMenuCommand,
                               0, sizeof(command), 0, &command);
             handled_event = qt_mac_activate_action(menu, command, QAction::Hover, false);
         } else if (ekind == kEventMenuOpening || ekind == kEventMenuClosed) {
             qt_mac_menus_open_count += (ekind == kEventMenuOpening) ? 1 : -1;
             MenuRef mr;
             GetEventParameter(event, kEventParamDirectObject, typeMenuRef,
                               0, sizeof(mr), 0, &mr);
             QWidget *widget = 0;
             if (GetMenuItemProperty(mr, 0, kMenuCreatorQt, kMenuPropertyQWidget, sizeof(widget), 0, &widget) == noErr) {
                 if (QMenu *qmenu = qobject_cast<QMenu*>(widget)) {
                     handled_event = true;
                     if (ekind == kEventMenuOpening) {
                         emit qmenu->aboutToShow();
                         int merged = 0;
                         const QMenuPrivate::QMacMenuPrivate *mac_menu = qmenu->d_func()->mac_menu;
                         const int ActionItemsCount = mac_menu->actionItems.size();
                         for(int i = 0; i < ActionItemsCount; ++i) {
                             QMacMenuAction *action = mac_menu->actionItems.at(i);
                             if (action->action->isSeparator()) {
                                 bool hide = false;
                                 if(!action->action->isVisible()) {
                                     hide = true;
                                 } else if (merged && merged == i) {
                                     hide = true;
                                 } else {
                                     for(int l = i+1; l < mac_menu->actionItems.size(); ++l) {
                                         QMacMenuAction *action = mac_menu->actionItems.at(l);
                                         if (action->merged) {
                                             hide = true;
                                         } else if (action->action->isSeparator()) {
                                             if (hide)
                                                 break;
                                         } else if (!action->merged) {
                                             hide = false;
                                             break;
                                         }
                                     }
                                 }
                                 const int index = qt_mac_menu_find_action(mr, action);
                                 if (hide) {
                                     ++merged;
                                     ChangeMenuItemAttributes(mr, index, kMenuItemAttrHidden, 0);
                                 } else {
                                     ChangeMenuItemAttributes(mr, index, 0, kMenuItemAttrHidden);
                                 }
                             } else if (action->merged) {
                                 ++merged;
                             }
                         }
                     } else {
                         emit qmenu->aboutToHide();
                     }
                 }
             }
         } else {
             handled_event = false;
         }
         break; }
     default:
         handled_event = false;
         break;
     }
     if (!handled_event) //let the event go through
         return CallNextEventHandler(er, event);
     return noErr; //we eat the event
 }
qt_mac_trayicon_activate_action
void qt_mac_trayicon_activate_action (QMenu * , QAction * action) friend
qt_mac_watchingAboutToShow
bool qt_mac_watchingAboutToShow (QMenu * menu) friend
Definition at line 119 of file qmenu_mac.mm.
 {
     return menu && menu->receivers(SIGNAL(aboutToShow()));
 }
QToolButtonPrivate
friend class QToolButtonPrivate friend
Definition at line 416 of file qmenu.h.
QTornOffMenu
friend class QTornOffMenu friend
Definition at line 412 of file qmenu.h.
Properties
icon
QIcon QMenu::icon private
The icon of the menu.
This is equivalent to the QAction::icon property of the menuAction().
By default, if no icon is explicitly set, this property contains a null icon.
Definition at line 80 of file qmenu.h.
separatorsCollapsible
bool QMenu::separatorsCollapsible private
whether consecutive separators should be collapsed
Since
4.2
This property specifies whether consecutive separators in the menu should be visually collapsed to a single one. Separators at the beginning or the end of the menu are also hidden.
By default, this property is true.
Definition at line 81 of file qmenu.h.
tearOffEnabled
QMenu::tearOffEnabled private
whether the menu supports being torn off
When true, the menu contains a special tear-off item (often shown as a dashed line at the top of the menu) that creates a copy of the menu when it is triggered.
This "torn-off" copy lives in a separate window. It contains the same menu items as the original menu, with the exception of the tear-off handle.
By default, this property is false.
Definition at line 78 of file qmenu.h.
title
QString QMenu::title private
The title of the menu.
This is equivalent to the QAction::text property of the menuAction().
By default, this property contains an empty string.
Definition at line 79 of file qmenu.h.
Referenced by QAccessibleMenuItem::text().
The documentation for this class was generated from the following files:
/src/gui/widgets/qmenu.h
/src/gui/widgets/qmenu.cpp
/src/gui/widgets/qmenu_mac.mm
/src/gui/widgets/qmenu_wince.cpp