Qt 4.8: QDeclarativeParser::Variant Class Reference
QDeclarativeParser::Variant Class Reference
#include <qdeclarativeparser_p.h>
Public Types
enum Type {
Invalid, Boolean, Number, String,
Script
}
Public Functions
QDeclarativeJS::AST::Node * asAST () const
bool asBoolean () const
double asNumber () const
QString asScript () const
QString asString () const
QStringList asStringList () const
bool isBoolean () const
bool isNumber () const
bool isScript () const
bool isString () const
bool isStringList () const
Variant & operator= (const Variant &)
Type type () const
Variant ()
Variant (const Variant &)
Variant (bool)
Variant (double, const QString &asWritten=QString())
Variant (const QString &)
Variant (const QString &, QDeclarativeJS::AST::Node *)
Properties
union {
bool b
double d
QDeclarativeJS::AST::Node * n
};
QString s
Type t
Detailed Description
Definition at line 240 of file qdeclarativeparser_p.h.
Enumerations
Type
enum QDeclarativeParser::Variant::Type
Enumerator
Invalid
Boolean
Number
String
Script
Definition at line 243 of file qdeclarativeparser_p.h.
                   {
             Invalid,
             Boolean,
             Number,
             String,
             Script
         };
Constructors and Destructors
Variant() [1/6]
QDeclarativeParser::Variant::Variant ()
Definition at line 264 of file qdeclarativeparser.cpp.
 : t(Invalid) {}
Variant() [2/6]
QDeclarativeParser::Variant::Variant (const Variant & o)
Definition at line 267 of file qdeclarativeparser.cpp.
 : t(o.t), d(o.d), s(o.s)
 {
 }
Variant() [3/6]
QDeclarativeParser::Variant::Variant (bool v)
Definition at line 272 of file qdeclarativeparser.cpp.
 : t(Boolean), b(v)
 {
 }
Variant() [4/6]
QDeclarativeParser::Variant::Variant (double v, const QString & asWritten = QString())
Definition at line 277 of file qdeclarativeparser.cpp.
 : t(Number), d(v), s(asWritten)
 {
 }
Variant() [5/6]
QDeclarativeParser::Variant::Variant (const QString & v)
Definition at line 282 of file qdeclarativeparser.cpp.
 : t(String), s(v)
 {
 }
Variant() [6/6]
QDeclarativeParser::Variant::Variant (const QString & v, QDeclarativeJS::AST::Node * n)
Definition at line 287 of file qdeclarativeparser.cpp.
 : t(Script), n(n), s(v)
 {
 }
Functions
asAST()
QDeclarativeJS::AST::Node * QDeclarativeParser::Variant::asAST () const
Definition at line 383 of file qdeclarativeparser.cpp.
Referenced by QDeclarativeBindingCompiler::compile(), and QDeclarativeCompiler::completeComponentBuild().
 {
     if (type() == Script)
         return n;
     else
         return 0;
 }
asBoolean()
bool QDeclarativeParser::Variant::asBoolean () const
Definition at line 305 of file qdeclarativeparser.cpp.
Referenced by QDeclarativePropertyChangesParser::compile(), QDeclarativeListModelParser::compileProperty(), and QDeclarativeCompiler::genLiteralAssignment().
 {
     return b;
 }
asNumber()
double QDeclarativeParser::Variant::asNumber () const
Definition at line 315 of file qdeclarativeparser.cpp.
Referenced by QDeclarativePropertyChangesParser::compile(), QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::genLiteralAssignment(), and QDeclarativeCompiler::testLiteralAssignment().
 {
     return d;
 }
asScript()
QString QDeclarativeParser::Variant::asScript () const
Definition at line 363 of file qdeclarativeparser.cpp.
Referenced by QDeclarativeDomValueBinding::binding(), QDeclarativeGestureAreaParser::compile(), QDeclarativeConnectionsParser::compile(), QDeclarativePropertyChangesParser::compile(), QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::completeComponentBuild(), and QDeclarativeCompiler::genObjectBody().
 {
     switch(type()) {
     default:
     case Invalid:
         return QString();
     case Boolean:
         return b?QLatin1String("true"):QLatin1String("false");
     case Number:
         if (s.isEmpty())
             return QString::number(d);
         else
             return s;
     case String:
         return escapedString(s);
     case Script:
         return s;
     }
 }
asString()
QString QDeclarativeParser::Variant::asString () const
Definition at line 310 of file qdeclarativeparser.cpp.
Referenced by asStringList(), QDeclarativePropertyChangesParser::compile(), QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::genLiteralAssignment(), QDeclarativeCompiler::testLiteralAssignment(), and QDeclarativeCompiler::testQualifiedEnumAssignment().
 {
     return s;
 }
asStringList()
QStringList QDeclarativeParser::Variant::asStringList () const
Definition at line 416 of file qdeclarativeparser.cpp.
 {
     QStringList rv;
     if (isString()) {
         rv << asString();
         return rv;
     }
     AST::ArrayLiteral *array = AST::cast<AST::ArrayLiteral *>(n);
     if (!array)
         return rv;
     AST::ElementList *elements = array->elements;
     while (elements) {
         AST::StringLiteral *string = AST::cast<AST::StringLiteral *>(elements->expression);
         if (!string)
             return QStringList();
         rv.append(string->value->asString());
         elements = elements->next;
     }
     return  rv;
 }
isBoolean()
bool QDeclarativeParser::Variant::isBoolean () const inline
Definition at line 261 of file qdeclarativeparser_p.h.
Referenced by QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::genLiteralAssignment(), and QDeclarativeCompiler::testLiteralAssignment().
 { return type() == Boolean; }
isNumber()
bool QDeclarativeParser::Variant::isNumber () const inline
Definition at line 262 of file qdeclarativeparser_p.h.
Referenced by QDeclarativeListModelParser::compileProperty(), QDeclarativeCompiler::genLiteralAssignment(), and QDeclarativeCompiler::testLiteralAssignment().
 { return type() == Number; }
isScript()
bool QDeclarativeParser::Variant::isScript () const inline
Definition at line 264 of file qdeclarativeparser_p.h.
Referenced by QDeclarativeCompiler::buildListProperty(), QDeclarativeCompiler::buildPropertyLiteralAssignment(), QDeclarativeCompiler::buildValueTypeProperty(), QDeclarativeGestureAreaParser::compile(), QDeclarativeConnectionsParser::compile(), QDeclarativePropertyChangesParser::compile(), and QDeclarativeListModelParser::compileProperty().
 { return type() == Script; }
isString()
bool QDeclarativeParser::Variant::isString () const inline
Definition at line 263 of file qdeclarativeparser_p.h.
Referenced by asStringList(), QDeclarativeListModelParser::compileProperty(), isStringList(), and QDeclarativeCompiler::testLiteralAssignment().
 { return type() == String; }
isStringList()
bool QDeclarativeParser::Variant::isStringList () const
Definition at line 391 of file qdeclarativeparser.cpp.
 {
     if (isString())
         return true;
     if (type() != Script || !n)
         return false;
     AST::ArrayLiteral *array = AST::cast<AST::ArrayLiteral *>(n);
     if (!array)
         return false;
     AST::ElementList *elements = array->elements;
     while (elements) {
         if (!AST::cast<AST::StringLiteral *>(elements->expression))
             return false;
         elements = elements->next;
     }
     return true;
 }
operator=()
QDeclarativeParser::Variant & QDeclarativeParser::Variant::operator= (const Variant & o)
Definition at line 292 of file qdeclarativeparser.cpp.
 {
     t = o.t;
     d = o.d;
     s = o.s;
     return *this;
 }
type()
QDeclarativeParser::Variant::Type QDeclarativeParser::Variant::type () const
Definition at line 300 of file qdeclarativeparser.cpp.
Referenced by asAST(), asScript(), QDeclarativePropertyChangesParser::compile(), QDeclarativeListModelParser::compileProperty(), and isStringList().
 {
     return t;
 }
Properties
@148
union { ... }
b
bool QDeclarativeParser::Variant::b
Definition at line 277 of file qdeclarativeparser_p.h.
Referenced by asBoolean(), and asScript().
d
double QDeclarativeParser::Variant::d
Definition at line 278 of file qdeclarativeparser_p.h.
Referenced by asNumber(), asScript(), and operator=().
n
QDeclarativeJS::AST::Node* QDeclarativeParser::Variant::n
Definition at line 279 of file qdeclarativeparser_p.h.
Referenced by asAST(), asStringList(), and isStringList().
s
QString QDeclarativeParser::Variant::s private
Definition at line 281 of file qdeclarativeparser_p.h.
Referenced by asScript(), asString(), and operator=().
t
Type QDeclarativeParser::Variant::t private
Definition at line 275 of file qdeclarativeparser_p.h.
Referenced by operator=(), and type().
The documentation for this class was generated from the following files:
/src/declarative/qml/qdeclarativeparser_p.h
/src/declarative/qml/qdeclarativeparser.cpp