Qt 4.8: QPictureIO Class Reference
QPictureIO Class Reference
The QPictureIO class contains parameters for loading and saving pictures.
#include <qpicture.h>
Public Functions
QString description () const
Returns the picture description string.
QString fileName () const
Returns the file name currently set.
const char * format () const
Returns the picture format string or 0 if no format has been explicitly set.
float gamma () const
Returns the gamma value at which the picture will be viewed.
QIODevice * ioDevice () const
Returns the IO device currently set.
const char * parameters () const
Returns the picture's parameters string.
const QPicture & picture () const
Returns the picture currently set.
QPictureIO ()
Constructs a QPictureIO object with all parameters set to zero.
QPictureIO (QIODevice *ioDevice, const char *format)
Constructs a QPictureIO object with the I/O device ioDevice and a format tag.
QPictureIO (const QString &fileName, const char *format)
Constructs a QPictureIO object with the file name fileName and a format tag.
int quality () const
Returns the quality of the written picture, related to the compression ratio.
bool read ()
Reads an picture into memory and returns true if the picture was successfully read; otherwise returns false.
void setDescription (const QString &)
Sets the picture description string for picture handlers that support picture descriptions to description.
void setFileName (const QString &)
Sets the name of the file to read or write an picture from to fileName.
void setFormat (const char *)
Sets the picture format to format for the picture to be read or written.
void setGamma (float)
Sets the gamma value at which the picture will be viewed to gamma.
void setIODevice (QIODevice *)
Sets the IO device to be used for reading or writing an picture.
void setParameters (const char *)
Sets the picture's parameter string to parameters.
void setPicture (const QPicture &)
Sets the picture to picture.
void setQuality (int)
Sets the quality of the written picture to q, related to the compression ratio.
void setStatus (int)
Sets the picture IO status to status.
int status () const
Returns the picture's IO status.
bool write ()
Writes an picture to an IO device and returns true if the picture was successfully written; otherwise returns false.
~QPictureIO ()
Destroys the object and all related data.
Static Public Functions
static void defineIOHandler (const char *format, const char *header, const char *flags, picture_io_handler read_picture, picture_io_handler write_picture)
Defines a picture I/O handler for the picture format called format, which is recognized using the regular expression defined in header, read using readPicture and written using writePicture.
static QList< QByteArray > inputFormats ()
Returns a sorted list of picture formats that are supported for picture input.
static QList< QByteArray > outputFormats ()
Returns a sorted list of picture formats that are supported for picture output.
static QByteArray pictureFormat (const QString &fileName)
Returns a string that specifies the picture format of the file fileName, or null if the file cannot be read or if the format is not recognized.
static QByteArray pictureFormat (QIODevice *)
Returns a string that specifies the picture format of the picture read from IO device d, or 0 if the device cannot be read or if the format is not recognized.
Private Functions
void init ()
Contains initialization common to all QPictureIO constructors.
Properties
QPictureIOData * d
Detailed Description
The QPictureIO class contains parameters for loading and saving pictures.
QPictureIO contains a QIODevice object that is used for picture data I/O. The programmer can install new picture file formats in addition to those that Qt provides.
You don't normally need to use this class; QPicture::load(), QPicture::save().
See also
QPicture QPixmap QFile
Definition at line 136 of file qpicture.h.
Constructors and Destructors
QPictureIO() [1/3]
QPictureIO::QPictureIO ()
Constructs a QPictureIO object with all parameters set to zero.
Definition at line 1401 of file qpicture.cpp.
 {
     init();
 }
QPictureIO() [2/3]
QPictureIO::QPictureIO (QIODevice * ioDevice, const char * format)
Constructs a QPictureIO object with the I/O device ioDevice and a format tag.
Definition at line 1411 of file qpicture.cpp.
 {
     init();
     d->iodev = ioDevice;
     d->frmt = format;
 }
QPictureIO() [3/3]
QPictureIO::QPictureIO (const QString & fileName, const char * format)
Constructs a QPictureIO object with the file name fileName and a format tag.
Definition at line 1423 of file qpicture.cpp.
 {
     init();
     d->frmt = format;
     d->fname = fileName;
 }
~QPictureIO()
QPictureIO::~QPictureIO ()
Destroys the object and all related data.
Definition at line 1448 of file qpicture.cpp.
 {
     if (d->parameters)
         delete [] (char*)d->parameters;
     delete d;
 }
Functions
defineIOHandler()
void QPictureIO::defineIOHandler (const char * format, const char * header, const char * flags, picture_io_handler readPicture, picture_io_handler writePicture) static
Defines a picture I/O handler for the picture format called format, which is recognized using the regular expression defined in header, read using readPicture and written using writePicture.
flags is a string of single-character flags for this format. The only flag defined currently is T (upper case), so the only legal value for flags are "T" and the empty string. The "T" flag means that the picture file is a text file, and Qt should treat all newline conventions as equivalent. (XPM files and some PPM files are text files for example.)
format is used to select a handler to write a QPicture; header is used to select a handler to read an picture file.
If readPicture is a null pointer, the QPictureIO will not be able to read pictures in format. If writePicture is a null pointer, the QPictureIO will not be able to write pictures in format. If both are null, the QPictureIO object is valid but useless.
Example:
void readSVG(QPictureIO *picture)
{
    // read the picture using the picture->ioDevice()
}
void writeSVG(QPictureIO *picture)
{
    // write the picture using the picture->ioDevice()
}
    // add the SVG picture handler
    // ...
Before the regular expression test, all the 0 bytes in the file header are converted to 1 bytes. This is done because when Qt was ASCII-based, QRegExp could not handle 0 bytes in strings.
The regexp is only applied on the first 14 bytes of the file.
(Note that if one handlerIO supports writing a format and another supports reading it, Qt supports both reading and writing. If two handlers support the same operation, Qt chooses one arbitrarily.)
Definition at line 1578 of file qpicture.cpp.
 {
     qt_init_picture_handlers();
     if (QPHList *list = pictureHandlers()) {
         QPictureHandler *p;
         p = new QPictureHandler(format, header, QByteArray(flags), readPicture, writePicture);
         list->prepend(p);
     }
 }
description()
QString QPictureIO::description () const
Returns the picture description string.
See also
setDescription()
Definition at line 1638 of file qpicture.cpp.
 { return d->descr; }
fileName()
QString QPictureIO::fileName () const
Returns the file name currently set.
See also
setFileName()
Definition at line 1630 of file qpicture.cpp.
 { return d->fname; }
format()
const char * QPictureIO::format () const
Returns the picture format string or 0 if no format has been explicitly set.
Definition at line 1616 of file qpicture.cpp.
 { return d->frmt; }
gamma()
float QPictureIO::gamma () const
Returns the gamma value at which the picture will be viewed.
See also
setGamma()
Definition at line 1783 of file qpicture.cpp.
 {
     return d->gamma;
 }
init()
void QPictureIO::init () private
Contains initialization common to all QPictureIO constructors.
Definition at line 1434 of file qpicture.cpp.
 {
     d = new QPictureIOData();
     d->parameters = 0;
     d->quality = -1; // default quality of the current format
     d->gamma=0.0f;
     d->iostat = 0;
     d->iodev  = 0;
 }
inputFormats()
QList< QByteArray > QPictureIO::inputFormats () static
Returns a sorted list of picture formats that are supported for picture input.
Definition at line 1876 of file qpicture.cpp.
Referenced by QPicture::inputFormatList(), and QPicture::inputFormats().
 {
     QList<QByteArray> result;
     qt_init_picture_handlers();
     qt_init_picture_plugins();
     if (QPHList *list = pictureHandlers()) {
         for (int i = 0; i < list->size(); ++i) {
             QPictureHandler *p = list->at(i);
             if (p->read_picture && !p->obsolete  && !result.contains(p->format))
                 result.append(p->format);
         }
     }
     qSort(result);
     return result;
 }
ioDevice()
QIODevice * QPictureIO::ioDevice () const
Returns the IO device currently set.
See also
setIODevice()
Definition at line 1623 of file qpicture.cpp.
 { return d->iodev; }
outputFormats()
QList< QByteArray > QPictureIO::outputFormats () static
Returns a sorted list of picture formats that are supported for picture output.
Definition at line 1899 of file qpicture.cpp.
Referenced by QPicture::outputFormatList(), and QPicture::outputFormats().
 {
     qt_init_picture_handlers();
     qt_init_picture_plugins();
     QList<QByteArray> result;
     if (QPHList *list = pictureHandlers()) {
         for (int i = 0; i < list->size(); ++i) {
             QPictureHandler *p = list->at(i);
             if (p->write_picture && !p->obsolete && !result.contains(p->format))
                 result.append(p->format);
         }
     }
     return result;
 }
parameters()
const char * QPictureIO::parameters () const
Returns the picture's parameters string.
See also
setParameters()
Definition at line 1739 of file qpicture.cpp.
 {
     return d->parameters;
 }
picture()
const QPicture & QPictureIO::picture () const
Returns the picture currently set.
See also
setPicture()
Definition at line 1602 of file qpicture.cpp.
Referenced by QPicture::load(), and QPicture::save().
 { return d->pi; }
pictureFormat() [1/2]
QByteArray QPictureIO::pictureFormat (const QString & fileName) static
Returns a string that specifies the picture format of the file fileName, or null if the file cannot be read or if the format is not recognized.
Definition at line 1808 of file qpicture.cpp.
Referenced by QPicture::pictureFormat().
 {
     QFile file(fileName);
     QByteArray format;
     if (!file.open(QIODevice::ReadOnly))
         return format;
     format = pictureFormat(&file);
     file.close();
     return format;
 }
pictureFormat() [2/2]
QByteArray QPictureIO::pictureFormat (QIODevice * d) static
Returns a string that specifies the picture format of the picture read from IO device d, or 0 if the device cannot be read or if the format is not recognized.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Make sure that d is at the right position in the device (for example, at the beginning of the file).
See also
QIODevice::at()
Definition at line 1835 of file qpicture.cpp.
 {
     // if you change this change the documentation for defineIOHandler()
     const int buflen = 14;
     char buf[buflen];
     char buf2[buflen];
     qt_init_picture_handlers();
     qt_init_picture_plugins();
     int pos = d->pos();                      // save position
     int rdlen = d->read(buf, buflen);        // read a few bytes
     QByteArray format;
     if (rdlen != buflen)
         return format;
     memcpy(buf2, buf, buflen);
     for (int n = 0; n < rdlen; n++)
         if (buf[n] == '\0')
             buf[n] = '\001';
     if (rdlen > 0) {
         buf[rdlen - 1] = '\0';
         QString bufStr = QString::fromLatin1(buf);
         if (QPHList *list = pictureHandlers()) {
             for (int i = 0; i < list->size(); ++i) {
                 if (list->at(i)->header.indexIn(bufStr) != -1) { // try match with headers
                     format = list->at(i)->format;
                     break;
                 }
             }
         }
     }
     d->seek(pos);                                // restore position
     return format;
 }
quality()
int QPictureIO::quality () const
Returns the quality of the written picture, related to the compression ratio.
See also
setQuality() QPicture::save()
Definition at line 1712 of file qpicture.cpp.
 {
     return d->quality;
 }
read()
bool QPictureIO::read ()
Reads an picture into memory and returns true if the picture was successfully read; otherwise returns false.
Before reading an picture you must set an IO device or a file name. If both an IO device and a file name have been set, the IO device will be used.
Setting the picture file format string is optional.
Note that this function does not set the format used to read the picture. If you need that information, use the pictureFormat() static functions.
Example:
        QPictureIO iio;
        QPixmap  pixmap;
        iio.setFileName("vegeburger.pic");
        if (iio.read()) {        // OK
            QPicture picture = iio.picture();
            QPainter painter(&pixmap);
            painter.drawPicture(0, 0, picture);
        }
See also
setIODevice() setFileName() setFormat() write() QPixmap::load()
Definition at line 1937 of file qpicture.cpp.
Referenced by QPicture::load().
 {
     QFile           file;
     const char          *picture_format;
     QPictureHandler *h;
     if (d->iodev) {                                // read from io device
         // ok, already open
     } else if (!d->fname.isEmpty()) {                // read from file
         file.setFileName(d->fname);
         if (!file.open(QIODevice::ReadOnly))
             return false;                        // cannot open file
         d->iodev = &file;
     } else {                                        // no file name or io device
         return false;
     }
     if (d->frmt.isEmpty()) {
         // Try to guess format
         picture_format = pictureFormat(d->iodev);        // get picture format
         if (!picture_format) {
             if (file.isOpen()) {                        // unknown format
                 file.close();
                 d->iodev = 0;
             }
             return false;
         }
     } else {
         picture_format = d->frmt;
     }
     h = get_picture_handler(picture_format);
     if (file.isOpen()) {
 #if !defined(Q_OS_UNIX)
         if (h && h->text_mode) {                // reopen in translated mode
             file.close();
             file.open(QIODevice::ReadOnly | QIODevice::Text);
         }
         else
 #endif
             file.seek(0);                        // position to start
     }
     d->iostat = 1;                                        // assume error
     if (h && h->read_picture)
         (*h->read_picture)(this);
     if (file.isOpen()) {                        // picture was read using file
         file.close();
         d->iodev = 0;
     }
     return d->iostat == 0;                                // picture successfully read?
 }
setDescription()
void QPictureIO::setDescription (const QString & description)
Sets the picture description string for picture handlers that support picture descriptions to description.
Currently, no picture format supported by Qt uses the description string.
Definition at line 1796 of file qpicture.cpp.
 {
     d->descr = description;
 }
setFileName()
void QPictureIO::setFileName (const QString & fileName)
Sets the name of the file to read or write an picture from to fileName.
See also
setIODevice()
Definition at line 1701 of file qpicture.cpp.
 {
     d->fname = fileName;
 }
setFormat()
void QPictureIO::setFormat (const char * format)
Sets the picture format to format for the picture to be read or written.
It is necessary to specify a format before writing an picture, but it is not necessary to specify a format before reading an picture.
If no format has been set, Qt guesses the picture format before reading it. If a format is set the picture will only be read if it has that format.
See also
read() write() format()
Definition at line 1674 of file qpicture.cpp.
 {
     d->frmt = format;
 }
setGamma()
void QPictureIO::setGamma (float gamma)
Sets the gamma value at which the picture will be viewed to gamma.
If the picture format stores a gamma value for which the picture is intended to be used, then this setting will be used to modify the picture. Setting to 0.0 will disable gamma correction (i.e. any specification in the file will be ignored).
The default value is 0.0.
See also
gamma()
Definition at line 1773 of file qpicture.cpp.
 {
     d->gamma=gamma;
 }
setIODevice()
void QPictureIO::setIODevice (QIODevice * ioDevice)
Sets the IO device to be used for reading or writing an picture.
Setting the IO device allows pictures to be read/written to any block-oriented QIODevice.
If ioDevice is not null, this IO device will override file name settings.
See also
setFileName()
Definition at line 1690 of file qpicture.cpp.
 {
     d->iodev = ioDevice;
 }
setParameters()
void QPictureIO::setParameters (const char * parameters)
Sets the picture's parameter string to parameters.
This is for picture handlers that require special parameters.
Although the current picture formats supported by Qt ignore the parameters string, it may be used in future extensions or by contributions (for example, JPEG).
See also
parameters()
Definition at line 1755 of file qpicture.cpp.
 {
     if (d->parameters)
         delete [] (char*)d->parameters;
     d->parameters = qstrdup(parameters);
 }
setPicture()
void QPictureIO::setPicture (const QPicture & picture)
Sets the picture to picture.
See also
picture()
Definition at line 1645 of file qpicture.cpp.
 {
     d->pi = picture;
 }
setQuality()
void QPictureIO::setQuality (int q)
Sets the quality of the written picture to q, related to the compression ratio.
q must be in the range -1..100. Specify 0 to obtain small compressed files, 100 for large uncompressed files. (-1 signifies the default compression.)
See also
quality() QPicture::save()
Definition at line 1728 of file qpicture.cpp.
 {
     d->quality = q;
 }
setStatus()
void QPictureIO::setStatus (int status)
Sets the picture IO status to status.
A non-zero value indicates an error, whereas 0 means that the IO operation was successful.
See also
status()
Definition at line 1656 of file qpicture.cpp.
 {
     d->iostat = status;
 }
status()
int QPictureIO::status () const
Returns the picture's IO status.
A non-zero value indicates an error, whereas 0 means that the IO operation was successful.
See also
setStatus()
Definition at line 1610 of file qpicture.cpp.
 { return d->iostat; }
write()
bool QPictureIO::write ()
Writes an picture to an IO device and returns true if the picture was successfully written; otherwise returns false.
Before writing an picture you must set an IO device or a file name. If both an IO device and a file name have been set, the IO device will be used.
The picture will be written using the specified picture format.
Example:
        QPictureIO iio;
        QPicture   picture;
        QPainter painter(&picture);
        painter.drawPixmap(0, 0, pixmap);
        iio.setPicture(picture);
        iio.setFileName("vegeburger.pic");
        iio.setFormat("PIC");
        if (iio.write())
            return true; // returned true if written successfully
See also
setIODevice() setFileName() setFormat() read() QPixmap::save()
Definition at line 2006 of file qpicture.cpp.
Referenced by QPicture::save().
 {
     if (d->frmt.isEmpty())
         return false;
     QPictureHandler *h = get_picture_handler(d->frmt);
     if (!h || !h->write_picture) {
         qWarning("QPictureIO::write: No such picture format handler: %s",
                  format());
         return false;
     }
     QFile file;
     if (!d->iodev && !d->fname.isEmpty()) {
         file.setFileName(d->fname);
         bool translate = h->text_mode==QPictureHandler::TranslateInOut;
         QIODevice::OpenMode fmode = translate ? QIODevice::WriteOnly | QIODevice::Text : QIODevice::OpenMode(QIODevice::WriteOnly);
         if (!file.open(fmode))                // couldn't create file
             return false;
         d->iodev = &file;
     }
     d->iostat = 1;
     (*h->write_picture)(this);
     if (file.isOpen()) {                        // picture was written using file
         file.close();
         d->iodev = 0;
     }
     return d->iostat == 0;                                // picture successfully written?
 }
Properties
d
QPictureIOData* QPictureIO::d private
Definition at line 183 of file qpicture.h.
The documentation for this class was generated from the following files:
/src/gui/image/qpicture.h
/src/gui/image/qpicture.cpp