Qt 4.8: QBlittable Class Reference
QBlittable Class Reference abstract
#include <qblittable_p.h>
Public Types
enum Capability {
SolidRectCapability = 0x0001, SourcePixmapCapability = 0x0002, SourceOverPixmapCapability = 0x0004, SourceOverScaledPixmapCapability = 0x0008,
AlphaFillRectCapability = 0x0010, OpacityPixmapCapability = 0x0020, OutlineCapability = 0x0001000
}
Public Functions
virtual void alphaFillRect (const QRectF &rect, const QColor &color, QPainter::CompositionMode cmode)
Capabilities capabilities () const
virtual void drawPixmap (const QRectF &rect, const QPixmap &pixmap, const QRectF &subrect)=0
virtual void drawPixmapOpacity (const QRectF &rect, const QPixmap &pixmap, const QRectF &subrect, QPainter::CompositionMode cmode, qreal opacity)
virtual void fillRect (const QRectF &rect, const QColor &color)=0
bool isLocked () const
QImage * lock ()
Q_DECLARE_FLAGS (Capabilities, Capability)
QBlittable (const QSize &size, Capabilities caps)
QSize size () const
void unlock ()
virtual ~QBlittable ()
Protected Functions
virtual QImage * doLock ()=0
virtual void doUnlock ()=0
Protected Variables
QBlittablePrivate * d_ptr
Private Functions
Q_DECLARE_PRIVATE (QBlittable)
Detailed Description
Definition at line 55 of file qblittable_p.h.
Enumerations
Capability
enum QBlittable::Capability
Enumerator
SolidRectCapability
SourcePixmapCapability
SourceOverPixmapCapability
SourceOverScaledPixmapCapability
AlphaFillRectCapability
OpacityPixmapCapability
OutlineCapability
Definition at line 59 of file qblittable_p.h.
                     {
         SolidRectCapability             = 0x0001,
         SourcePixmapCapability          = 0x0002,
         SourceOverPixmapCapability      = 0x0004,
         SourceOverScaledPixmapCapability = 0x0008,
         AlphaFillRectCapability         = 0x0010,
         OpacityPixmapCapability         = 0x0020,
         // Internal ones
         OutlineCapability               = 0x0001000,
     };
Constructors and Destructors
QBlittable()
QBlittable::QBlittable (const QSize & size, Capabilities caps)
Definition at line 60 of file qblittable.cpp.
     : d_ptr(new QBlittablePrivate(size,caps))
 {
 }
~QBlittable()
QBlittable::~QBlittable () virtual
Definition at line 65 of file qblittable.cpp.
 {
     delete d_ptr;
 }
Functions
alphaFillRect()
virtual void QBlittable::alphaFillRect (const QRectF & rect, const QColor & color, QPainter::CompositionMode cmode) inline virtual
Reimplemented in QDirectFbBlitter.
Definition at line 81 of file qblittable_p.h.
Referenced by QBlittablePixmapData::fill().
{
         Q_UNUSED(rect);
         Q_UNUSED(color);
         Q_UNUSED(cmode);
         qWarning("Please implement alphaFillRect function in your platform or remove AlphaFillRectCapability from it");
     }
capabilities()
QBlittable::Capabilities QBlittable::capabilities () const
Definition at line 71 of file qblittable.cpp.
Referenced by QBlittablePixmapData::fill().
 {
     Q_D(const QBlittable);
     return d->caps;
 }
doLock()
virtual QImage* QBlittable::doLock () protected pure virtual
Implemented in QDirectFbBlitter.
Referenced by lock().
doUnlock()
virtual void QBlittable::doUnlock () protected pure virtual
Implemented in QDirectFbBlitter.
Referenced by unlock().
drawPixmap()
virtual void QBlittable::drawPixmap (const QRectF & rect, const QPixmap & pixmap, const QRectF & subrect) pure virtual
Implemented in QDirectFbBlitter.
drawPixmapOpacity()
virtual void QBlittable::drawPixmapOpacity (const QRectF & rect, const QPixmap & pixmap, const QRectF & subrect, QPainter::CompositionMode cmode, qreal opacity) inline virtual
Reimplemented in QDirectFbBlitter.
Definition at line 87 of file qblittable_p.h.
{
         Q_UNUSED(rect);
         Q_UNUSED(pixmap);
         Q_UNUSED(subrect);
         Q_UNUSED(cmode);
         Q_UNUSED(opacity);
         qWarning("Please implement drawPixmapOpacity function in your platform or remove OpacityPixmapCapability from it");
     }
fillRect()
virtual void QBlittable::fillRect (const QRectF & rect, const QColor & color) pure virtual
Implemented in QDirectFbBlitter.
Referenced by QBlittablePixmapData::fill().
isLocked()
bool QBlittable::isLocked () const
Definition at line 83 of file qblittable.cpp.
 {
     Q_D(const QBlittable);
     return d->locked;
 }
lock()
QImage * QBlittable::lock ()
Definition at line 89 of file qblittable.cpp.
Referenced by QBlittablePixmapData::buffer(), QBlittablePixmapData::fill(), QBlittablePixmapData::hasAlphaChannel(), and QBlittablePixmapData::toImage().
 {
     Q_D(QBlittable);
     if (!d->locked) {
         d->cachedImg = doLock();
         d->locked = true;
     }
     return d->cachedImg;
 }
Q_DECLARE_FLAGS()
QBlittable::Q_DECLARE_FLAGS (Capabilities , Capability)
Q_DECLARE_PRIVATE()
QBlittable::Q_DECLARE_PRIVATE (QBlittable) private
size()
QSize QBlittable::size () const
Definition at line 77 of file qblittable.cpp.
Referenced by QDirectFbBlitter::doLock(), and QBlittablePixmapData::setBlittable().
 {
     Q_D(const QBlittable);
     return d->m_size;
 }
unlock()
void QBlittable::unlock ()
Definition at line 100 of file qblittable.cpp.
Referenced by QDirectFbBlitter::drawPixmapOpacity(), QBlittablePixmapData::fill(), QDirectFbWindowSurface::flush(), QDirectFbWindowSurface::scroll(), and QDirectFbBlitter::~QDirectFbBlitter().
 {
     Q_D(QBlittable);
     if (d->locked) {
         doUnlock();
         d->locked = false;
     }
 }
Properties
d_ptr
QBlittablePrivate* QBlittable::d_ptr protected
Definition at line 105 of file qblittable_p.h.
Referenced by ~QBlittable().
The documentation for this class was generated from the following files:
/src/gui/painting/qblittable_p.h
/src/gui/painting/qblittable.cpp