Qt 4.8: QMap< Key, T >::const_iterator Class Reference
QMap< Key, T >::const_iterator Class Reference
The QMap::const_iterator class provides an STL-style const iterator for QMap and QMultiMap.
#include <qmap.h>
Public Types
typedef qptrdiff difference_type
typedef std::bidirectional_iterator_tag iterator_category
A synonym for {std::bidirectional_iterator_tag} indicating this iterator is a bidirectional iterator.
typedef const T * pointer
typedef const T & reference
typedef T value_type
Public Functions
const_iterator ()
Constructs an uninitialized iterator.
const_iterator (QMapData::Node *node)
const_iterator (const iterator &o)
Constructs a copy of other.
const Key & key () const
Returns the current item's key.
operator QMapData::Node * () const
bool operator!= (const const_iterator &o) const
Returns true if other points to a different item than this iterator; otherwise returns false.
const T & operator* () const
Returns the current item's value.
const_iterator operator+ (int j) const
Returns an iterator to the item at j positions forward from this iterator.
const_iterator & operator++ ()
The prefix ++ operator (++i) advances the iterator to the next item in the map and returns an iterator to the new current item.
const_iterator operator++ (int)
The postfix ++ operator (i++) advances the iterator to the next item in the map and returns an iterator to the previously current item.
const_iterator & operator+= (int j)
Advances the iterator by j items.
const_iterator operator- (int j) const
Returns an iterator to the item at j positions backward from this iterator.
const_iterator & operator-- ()
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
const_iterator operator-- (int)
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
const_iterator & operator-= (int j)
Makes the iterator go back by j items.
const T * operator-> () const
Returns a pointer to the current item's value.
bool operator== (const const_iterator &o) const
Returns true if other points to the same item as this iterator; otherwise returns false.
const T & value () const
Returns the current item's value.
Private Functions
operator bool () const
Properties
QMapData::Node * i
Friends
class iterator
Detailed Description
template<class Key, class T>
class QMap< Key, T >::const_iterator
The QMap::const_iterator class provides an STL-style const iterator for QMap and QMultiMap.
QMap features both STL-style iterators and Java-style iterators. The STL-style iterators are more low-level and more cumbersome to use; on the other hand, they are slightly faster and, for developers who already know STL, have the advantage of familiarity.
QMap<Key, T>::const_iterator allows you to iterate over a QMap (or a QMultiMap). If you want to modify the QMap as you iterate over it, you must use QMap::iterator instead. It is generally good practice to use QMap::const_iterator on a non-const QMap as well, unless you need to change the QMap through the iterator. Const iterators are slightly faster, and can improve code readability.
The default QMap::const_iterator constructor creates an uninitialized iterator. You must initialize it using a QMap function like QMap::constBegin(), QMap::constEnd(), or QMap::find() before you can start iterating. Here's a typical loop that prints all the (key, value) pairs stored in a map:
QMap<QString, int> map;
map.insert("January", 1);
map.insert("February", 2);
...
map.insert("December", 12);
QMap<QString, int>::const_iterator i;
for (i = map.constBegin(); i != map.constEnd(); ++i)
    cout << i.key() << ": " << i.value() << endl;
Unlike QHash, which stores its items in an arbitrary order, QMap stores its items ordered by key. Items that share the same key (because they were inserted using QMap::insertMulti()) will appear consecutively, from the most recently to the least recently inserted value.
Multiple iterators can be used on the same map. If you add items to the map, existing iterators will remain valid. If you remove items from the map, iterators that point to the removed items will become dangling iterators.
See also
QMap::iterator, QMapIterator
Definition at line 301 of file qmap.h.
Typedefs
difference_type
template<class Key, class T> QMap< Key, T >::const_iterator::difference_type
Warning
This function is not part of the public interface.
Definition at line 308 of file qmap.h.
iterator_category
template<class Key, class T> QMap< Key, T >::const_iterator::iterator_category
A synonym for {std::bidirectional_iterator_tag} indicating this iterator is a bidirectional iterator.
Definition at line 307 of file qmap.h.
pointer
template<class Key, class T> QMap< Key, T >::const_iterator::pointer
Warning
This function is not part of the public interface.
Definition at line 310 of file qmap.h.
reference
template<class Key, class T> QMap< Key, T >::const_iterator::reference
Warning
This function is not part of the public interface.
Definition at line 311 of file qmap.h.
value_type
template<class Key, class T> QMap< Key, T >::const_iterator::value_type
Warning
This function is not part of the public interface.
Definition at line 309 of file qmap.h.
Constructors and Destructors
const_iterator() [1/3]
template<class Key, class T> QMap< Key, T >::const_iterator::const_iterator () inline
Constructs an uninitialized iterator.
Functions like key(), value(), and operator++() must not be called on an uninitialized iterator. Use operator=() to assign a value to it before using it.
See also
QMap::constBegin() QMap::constEnd()
Definition at line 315 of file qmap.h.
 : i(0) { }
const_iterator() [2/3]
template<class Key, class T> QMap< Key, T >::const_iterator::const_iterator (QMapData::Node * node) inline
Warning
This function is not part of the public interface.
Definition at line 316 of file qmap.h.
 : i(node) { }
const_iterator() [3/3]
template<class Key, class T> QMap< Key, T >::const_iterator::const_iterator (const iterator & o) inline
Constructs a copy of other.
Definition at line 320 of file qmap.h.
         { i = o.i; }
Functions
key()
template<class Key, class T> const Key & QMap< Key, T >::const_iterator::key () const inline
Returns the current item's key.
See also
value()
Definition at line 324 of file qmap.h.
Referenced by QMultiMap< QString, Method >::count(), QMultiMap< QString, Method >::find(), QScriptDebuggerScriptsModel::indexFromScriptId(), QWizardPage::nextId(), operator<<(), QIBaseDriver::qHandleEventNotification(), QStandardItemPrivate::setItemData(), QSpanCollection::spansInRect(), and QConfFileSettingsPrivate::writeIniFile().
 { return concrete(i)->key; }
operator bool()
template<class Key, class T> QMap< Key, T >::const_iterator::operator bool () const inline private
Definition at line 367 of file qmap.h.
 { return false; }
operator QMapData::Node *()
template<class Key, class T> QMap< Key, T >::const_iterator::operator QMapData::Node * () const inline
Warning
This function is not part of the public interface.
Definition at line 314 of file qmap.h.
 { return i; }
operator!=()
template<class Key, class T> bool QMap< Key, T >::const_iterator::operator!= (const const_iterator & other) const inline
Returns true if other points to a different item than this iterator; otherwise returns false.
See also
operator==()
Definition at line 332 of file qmap.h.
 { return i != o.i; }
operator*()
template<class Key, class T> const T & QMap< Key, T >::const_iterator::operator* () const inline
Returns the current item's value.
Same as value().
See also
key()
Definition at line 329 of file qmap.h.
 { return concrete(i)->value; }
operator+()
template<class Key, class T> QMap::const_iterator QMap< Key, T >::const_iterator::operator+ (int j) const inline
Returns an iterator to the item at j positions forward from this iterator.
(If j is negative, the iterator goes backward.)
This operation can be slow for large j values.
See also
operator-()
Definition at line 352 of file qmap.h.
         { const_iterator r = *this; if (j > 0) while (j--) ++r; else while (j++) --r; return r; }
operator++() [1/2]
template<class Key, class T> QMap::const_iterator QMap< Key, T >::const_iterator::operator++ () inline
The prefix ++ operator (++i) advances the iterator to the next item in the map and returns an iterator to the new current item.
Calling this function on QMap::end() leads to undefined results.
See also
operator--()
Definition at line 334 of file qmap.h.
{
             i = i->forward[0];
             return *this;
         }
operator++() [2/2]
template<class Key, class T> QMap::const_iterator QMap< Key, T >::const_iterator::operator++ (int) inline
The postfix ++ operator (i++) advances the iterator to the next item in the map and returns an iterator to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 338 of file qmap.h.
{
             const_iterator r = *this;
             i = i->forward[0];
             return r;
         }
operator+=()
template<class Key, class T> QMap::const_iterator & QMap< Key, T >::const_iterator::operator+= (int j) inline
Advances the iterator by j items.
(If j is negative, the iterator goes backward.)
This operation can be slow for large j values.
See also
operator-=(), operator+()
Definition at line 355 of file qmap.h.
 { return *this = *this + j; }
operator-()
template<class Key, class T> QMap::const_iterator QMap< Key, T >::const_iterator::operator- (int j) const inline
Returns an iterator to the item at j positions backward from this iterator.
(If j is negative, the iterator goes forward.)
This operation can be slow for large j values.
See also
operator+()
Definition at line 354 of file qmap.h.
 { return operator+(-j); }
operator--() [1/2]
template<class Key, class T> QMap::const_iterator & QMap< Key, T >::const_iterator::operator-- () inline
The prefix – operator (–i) makes the preceding item current and returns an iterator pointing to the new current item.
Calling this function on QMap::begin() leads to undefined results.
See also
operator++()
Definition at line 343 of file qmap.h.
{
             i = i->backward;
             return *this;
         }
operator--() [2/2]
template<class Key, class T> QMap::const_iterator QMap< Key, T >::const_iterator::operator-- (int) inline
The postfix – operator (i–) makes the preceding item current and returns an iterator pointing to the previously current item.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 347 of file qmap.h.
{
             const_iterator r = *this;
             i = i->backward;
             return r;
         }
operator-=()
template<class Key, class T> QMap::const_iterator & QMap< Key, T >::const_iterator::operator-= (int j) inline
Makes the iterator go back by j items.
(If j is negative, the iterator goes forward.)
This operation can be slow for large j values.
See also
operator+=(), operator-()
Definition at line 356 of file qmap.h.
 { return *this = *this - j; }
operator->()
template<class Key, class T> const T * QMap< Key, T >::const_iterator::operator-> () const inline
Returns a pointer to the current item's value.
See also
value()
Definition at line 330 of file qmap.h.
 { return &concrete(i)->value; }
operator==()
template<class Key, class T> bool QMap< Key, T >::const_iterator::operator== (const const_iterator & other) const inline
Returns true if other points to the same item as this iterator; otherwise returns false.
See also
operator!=()
Definition at line 331 of file qmap.h.
 { return i == o.i; }
value()
template<class Key, class T> const T & QMap< Key, T >::const_iterator::value () const inline
Returns the current item's value.
See also
key(), operator*()
Definition at line 325 of file qmap.h.
Referenced by QIBaseDriver::close(), QMultiMap< QString, Method >::count(), QNetworkDiskCache::expire(), QGestureManager::filterEventThroughContexts(), QMultiMap< QString, Method >::find(), QFontCache::findEngineData(), QScriptDebuggerScriptsModelPrivate::findScriptNode(), QScriptDebuggerScriptsModel::indexFromScriptId(), QWizardPage::nextId(), operator<<(), QIBaseDriver::qHandleEventNotification(), QScriptDebuggerScriptsModel::resolveScript(), QScriptDebuggerScriptsModel::scripts(), QStandardItemPrivate::setItemData(), QFontCache::timerEvent(), QSpanCollection::updateRemovedColumns(), QConfFileSettingsPrivate::writeIniFile(), and QFontCache::~QFontCache().
 { return concrete(i)->value; }
Friends and Related Functions
iterator
template<class Key, class T> friend class iterator friend
Definition at line 303 of file qmap.h.
Properties
i
template<class Key, class T> QMapData::Node* QMap< Key, T >::const_iterator::i private
Definition at line 304 of file qmap.h.
Referenced by QMap< Key, T >::iterator::operator!=(), QMap< Key, T >::const_iterator::operator!=(), QMap< Key, T >::iterator::operator==(), and QMap< Key, T >::const_iterator::operator==().
The documentation for this class was generated from the following files:
/src/corelib/tools/qmap.h
/src/corelib/tools/qmap.cpp