Qt 4.8: QNetworkInterface Class Reference
QNetworkInterface Class Reference
The QNetworkInterface class provides a listing of the host's IP addresses and network interfaces.
#include <qnetworkinterface.h>
Public Types
enum InterfaceFlag {
IsUp = 0x1, IsRunning = 0x2, CanBroadcast = 0x4, IsLoopBack = 0x8,
IsPointToPoint = 0x10, CanMulticast = 0x20
}
Specifies the flags associated with this network interface.
Public Functions
QList< QNetworkAddressEntry > addressEntries () const
Returns the list of IP addresses that this interface possesses along with their associated netmasks and broadcast addresses.
InterfaceFlags flags () const
Returns the flags associated with this network interface.
QString hardwareAddress () const
Returns the low-level hardware address for this interface.
QString humanReadableName () const
Returns the human-readable name of this network interface on Windows, such as "Local Area Connection", if the name could be determined.
int index () const
Returns the interface system index, if known.
bool isValid () const
Returns true if this QNetworkInterface object contains valid information about a network interface.
QString name () const
Returns the name of this network interface.
QNetworkInterface & operator= (const QNetworkInterface &other)
Copies the contents of the QNetworkInterface object contained in other into this one.
QNetworkInterface ()
Constructs an empty network interface object.
QNetworkInterface (const QNetworkInterface &other)
Creates a copy of the QNetworkInterface object contained in other.
~QNetworkInterface ()
Frees the resources associated with the QNetworkInterface object.
Static Public Functions
static QList< QHostAddress > allAddresses ()
This convenience function returns all IP addresses found on the host machine.
static QList< QNetworkInterface > allInterfaces ()
Returns a listing of all the network interfaces found on the host machine.
static QNetworkInterface interfaceFromIndex (int index)
Returns a QNetworkInterface object for the interface whose internal ID is index.
static QNetworkInterface interfaceFromName (const QString &name)
Returns a QNetworkInterface object for the interface named name.
Properties
QSharedDataPointer< QNetworkInterfacePrivate > d
Friends
class QNetworkInterfacePrivate
Detailed Description
The QNetworkInterface class provides a listing of the host's IP addresses and network interfaces.
Since
4.2
Note
This class or function is reentrant.
QNetworkInterface represents one network interface attached to the host where the program is being run. Each network interface may contain zero or more IP addresses, each of which is optionally associated with a netmask and/or a broadcast address. The list of such trios can be obtained with addressEntries(). Alternatively, when the netmask or the broadcast addresses aren't necessary, use the allAddresses() convenience function to obtain just the IP addresses.
QNetworkInterface also reports the interface's hardware address with hardwareAddress().
Not all operating systems support reporting all features. Only the IPv4 addresses are guaranteed to be listed by this class in all platforms. In particular, IPv6 address listing is only supported on Windows XP and more recent versions, Linux, MacOS X and the BSDs.
See also
QNetworkAddressEntry
Definition at line 87 of file qnetworkinterface.h.
Enumerations
InterfaceFlag
enum QNetworkInterface::InterfaceFlag
Specifies the flags associated with this network interface.
The possible values are:
IsUp the network interface is active
IsRunning the network interface has resources allocated
CanBroadcast the network interface works in broadcast mode
IsLoopBack the network interface is a loopback interface: that is, it's a virtual interface whose destination is the host computer itself
IsPointToPoint the network interface is a point-to-point interface: that is, there is one, single other address that can be directly reached by it.
CanMulticast the network interface supports multicasting
Note that one network interface cannot be both broadcast-based and point-to-point.
Enumerator
IsUp
IsRunning
CanBroadcast
IsLoopBack
IsPointToPoint
CanMulticast
Definition at line 90 of file qnetworkinterface.h.
{
         IsUp = 0x1,
         IsRunning = 0x2,
         CanBroadcast = 0x4,
         IsLoopBack = 0x8,
         IsPointToPoint = 0x10,
         CanMulticast = 0x20
     };
Constructors and Destructors
QNetworkInterface() [1/2]
QNetworkInterface::QNetworkInterface ()
Constructs an empty network interface object.
Definition at line 404 of file qnetworkinterface.cpp.
     : d(0)
 {
 }
QNetworkInterface() [2/2]
QNetworkInterface::QNetworkInterface (const QNetworkInterface & other)
Creates a copy of the QNetworkInterface object contained in other.
Definition at line 420 of file qnetworkinterface.cpp.
     : d(other.d)
 {
 }
~QNetworkInterface()
QNetworkInterface::~QNetworkInterface ()
Frees the resources associated with the QNetworkInterface object.
Definition at line 412 of file qnetworkinterface.cpp.
 {
 }
Functions
addressEntries()
QList< QNetworkAddressEntry > QNetworkInterface::addressEntries () const
Returns the list of IP addresses that this interface possesses along with their associated netmasks and broadcast addresses.
If the netmask or broadcast address information is not necessary, you can call the allAddresses() function to obtain just the IP addresses.
Definition at line 524 of file qnetworkinterface.cpp.
Referenced by isBypassed(), multicastMembershipHelper(), QNativeSocketEnginePrivate::nativeMulticastInterface(), QNativeSocketEnginePrivate::nativeSetMulticastInterface(), and operator<<().
 {
     return d ? d->addressEntries : QList<QNetworkAddressEntry>();
 }
allAddresses()
QList< QHostAddress > QNetworkInterface::allAddresses () static
This convenience function returns all IP addresses found on the host machine.
It is equivalent to calling addressEntries() on all the objects returned by allInterfaces() to obtain lists of QHostAddress objects then calling QHostAddress::ip() on each of these.
Definition at line 583 of file qnetworkinterface.cpp.
 {
     QList<QSharedDataPointer<QNetworkInterfacePrivate> > privs = manager()->allInterfaces();
     QList<QHostAddress> result;
     foreach (const QSharedDataPointer<QNetworkInterfacePrivate> &p, privs) {
         foreach (const QNetworkAddressEntry &entry, p->addressEntries)
             result += entry.ip();
     }
     return result;
 }
allInterfaces()
QList< QNetworkInterface > QNetworkInterface::allInterfaces () static
Returns a listing of all the network interfaces found on the host machine.
Definition at line 564 of file qnetworkinterface.cpp.
Referenced by QGenericEngine::doRequestUpdate(), isBypassed(), multicastMembershipHelper(), and QNativeSocketEnginePrivate::nativeMulticastInterface().
 {
     QList<QSharedDataPointer<QNetworkInterfacePrivate> > privs = manager()->allInterfaces();
     QList<QNetworkInterface> result;
     foreach (const QSharedDataPointer<QNetworkInterfacePrivate> &p, privs) {
         QNetworkInterface item;
         item.d = p;
         result << item;
     }
     return result;
 }
flags()
QNetworkInterface::InterfaceFlags QNetworkInterface::flags () const
Returns the flags associated with this network interface.
Definition at line 497 of file qnetworkinterface.cpp.
Referenced by multicastMembershipHelper(), and operator<<().
 {
     return d ? d->flags : InterfaceFlags(0);
 }
hardwareAddress()
QString QNetworkInterface::hardwareAddress () const
Returns the low-level hardware address for this interface.
On Ethernet interfaces, this will be a MAC address in string representation, separated by colons.
Other interface types may have other types of hardware addresses. Implementations should not depend on this function returning a valid MAC address.
Definition at line 511 of file qnetworkinterface.cpp.
Referenced by operator<<().
 {
     return d ? d->hardwareAddress : QString();
 }
humanReadableName()
QString QNetworkInterface::humanReadableName () const
Returns the human-readable name of this network interface on Windows, such as "Local Area Connection", if the name could be determined.
Since
4.5
If it couldn't, this function returns the same as name(). The human-readable name is a name that the user can modify in the Windows Control Panel, so it may change during the execution of the program.
On Unix, this function currently always returns the same as name(), since Unix systems don't store a configuration for human-readable names.
Definition at line 489 of file qnetworkinterface.cpp.
 {
     return d ? !d->friendlyName.isEmpty() ? d->friendlyName : name() : QString();
 }
index()
int QNetworkInterface::index () const
Returns the interface system index, if known.
Since
4.5 This is an integer assigned by the operating system to identify this interface and it generally doesn't change. It matches the scope ID field in IPv6 addresses.
If the index isn't known, this function returns 0.
Definition at line 456 of file qnetworkinterface.cpp.
Referenced by multicastMembershipHelper(), and QNativeSocketEnginePrivate::nativeSetMulticastInterface().
 {
     return d ? d->index : 0;
 }
interfaceFromIndex()
QNetworkInterface QNetworkInterface::interfaceFromIndex (int index) static
Returns a QNetworkInterface object for the interface whose internal ID is index.
Network interfaces have a unique identifier called the "interface index" to distinguish it from other interfaces on the system. Often, this value is assigned progressively and interfaces being removed and then added again get a different value every time.
This index is also found in the IPv6 address' scope ID field.
Definition at line 553 of file qnetworkinterface.cpp.
Referenced by multicastMembershipHelper(), and QNativeSocketEnginePrivate::nativeMulticastInterface().
 {
     QNetworkInterface result;
     result.d = manager()->interfaceFromIndex(index);
     return result;
 }
interfaceFromName()
QNetworkInterface QNetworkInterface::interfaceFromName (const QString & name) static
Returns a QNetworkInterface object for the interface named name.
If no such interface exists, this function returns an invalid QNetworkInterface object.
See also
name(), isValid()
Definition at line 536 of file qnetworkinterface.cpp.
Referenced by QNetworkSessionPrivateImpl::currentInterface(), and QNetworkSessionManagerPrivate::forceSessionClose().
 {
     QNetworkInterface result;
     result.d = manager()->interfaceFromName(name);
     return result;
 }
isValid()
bool QNetworkInterface::isValid () const
Returns true if this QNetworkInterface object contains valid information about a network interface.
Definition at line 439 of file qnetworkinterface.cpp.
Referenced by multicastMembershipHelper(), and QNativeSocketEnginePrivate::nativeSetMulticastInterface().
 {
     return !name().isEmpty();
 }
name()
QString QNetworkInterface::name () const
Returns the name of this network interface.
On Unix systems, this is a string containing the type of the interface and optionally a sequence number, such as "eth0", "lo" or "pcn0". On Windows, it's an internal ID that cannot be changed by the user.
Definition at line 467 of file qnetworkinterface.cpp.
Referenced by humanReadableName(), isValid(), and operator<<().
 {
     return d ? d->name : QString();
 }
operator=()
QNetworkInterface & QNetworkInterface::operator= (const QNetworkInterface & other)
Copies the contents of the QNetworkInterface object contained in other into this one.
Definition at line 429 of file qnetworkinterface.cpp.
 {
     d = other.d;
     return *this;
 }
Friends and Related Functions
QNetworkInterfacePrivate
friend class QNetworkInterfacePrivate friend
Definition at line 120 of file qnetworkinterface.h.
Properties
d
QSharedDataPointer<QNetworkInterfacePrivate> QNetworkInterface::d private
Definition at line 121 of file qnetworkinterface.h.
Referenced by addressEntries(), allInterfaces(), flags(), hardwareAddress(), humanReadableName(), index(), interfaceFromIndex(), interfaceFromName(), name(), and operator=().
The documentation for this class was generated from the following files:
/src/network/kernel/qnetworkinterface.h
/src/network/kernel/qnetworkinterface.cpp