Qt 4.8: QPatternist::DerivedInteger< DerivedType > Class Template Reference
QPatternist::DerivedInteger< DerivedType > Class Template Reference
Represents instances of derived xs:integer types, such as xs:byte.
#include <qderivedinteger_p.h>
Public Functions
virtual Numeric::Ptr abs () const
virtual Numeric::Ptr ceiling () const
bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const
virtual Numeric::Ptr floor () const
virtual bool isInf () const
virtual bool isNaN () const
virtual bool isSigned () const
Returns true if this value is signed. If false is returned, the value is unsigned.
virtual Numeric::Ptr round () const
virtual Numeric::Ptr roundHalfToEven (const xsInteger) const
StorageType storedValue () const
virtual QString stringValue () const
virtual xsDecimal toDecimal () const
virtual xsDouble toDouble () const
virtual xsFloat toFloat () const
virtual xsInteger toInteger () const
virtual Item toNegated () const
virtual qulonglong toUnsignedInteger () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static AtomicValue::Ptr fromLexical (const NamePool::Ptr &np, const QString &strNumeric)
static AtomicValue::Ptr fromValue (const NamePool::Ptr &np, const TemporaryStorageType num)
static AtomicValue::Ptr fromValueUnchecked (const TemporaryStorageType num)
static ItemType::Ptr itemType ()
Static Public Functions inherited from QPatternist::Numeric
static AtomicValue::Ptr fromLexical (const QString &number)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Private Types
typedef DerivedIntegerDetails< DerivedType >::StorageType StorageType
typedef DerivedIntegerDetails< DerivedType >::TemporaryStorageType TemporaryStorageType
Private Functions
DerivedInteger (const StorageType num)
Static Private Functions
template<typename A , typename B >
static bool largerOrEqual (const A &a, const B &b)
template<typename A , typename B >
static bool lessThan (const A &a, const B &b)
Properties
const StorageType m_value
Static Private Attributes
static const DerivedIntegerLimitsUsage limitsUsage = DerivedIntegerDetails<DerivedType>::limitsUsage
static const StorageType maxInclusive = DerivedIntegerDetails<DerivedType>::maxInclusive
static const StorageType minInclusive = DerivedIntegerDetails<DerivedType>::minInclusive
Related Functions
(Note that these are not member functions.)
enum DerivedIntegerLimitsUsage
Additional Inherited Members
Public Types inherited from QPatternist::Numeric
typedef QExplicitlySharedDataPointer< Numeric > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Variables inherited from QSharedData
QAtomicInt ref
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Static Protected Functions inherited from QPatternist::Numeric
static xsDouble roundFloat (const xsDouble val)
Implements fn:round() for types implemented with floating point.
Detailed Description
template<TypeOfDerivedInteger DerivedType>
class QPatternist::DerivedInteger< DerivedType >
Represents instances of derived xs:integer types, such as xs:byte.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 83 of file qderivedinteger_p.h.
Typedefs
StorageType
template<TypeOfDerivedInteger DerivedType> typedef DerivedIntegerDetails<DerivedType>::StorageType QPatternist::DerivedInteger< DerivedType >::StorageType private
Definition at line 332 of file qderivedinteger_p.h.
TemporaryStorageType
template<TypeOfDerivedInteger DerivedType> typedef DerivedIntegerDetails<DerivedType>::TemporaryStorageType QPatternist::DerivedInteger< DerivedType >::TemporaryStorageType private
Definition at line 333 of file qderivedinteger_p.h.
Constructors and Destructors
DerivedInteger()
template<TypeOfDerivedInteger DerivedType> QPatternist::DerivedInteger< DerivedType >::DerivedInteger (const StorageType num) inline private
Definition at line 341 of file qderivedinteger_p.h.
                                                      : m_value(num)
         {
         }
Functions
abs()
template<TypeOfDerivedInteger DerivedType> virtual Numeric::Ptr QPatternist::DerivedInteger< DerivedType >::abs () const inline virtual
Performs the algorithm specified for the function fn:abs on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.1 fn:abs
Implements QPatternist::Numeric.
Definition at line 533 of file qderivedinteger_p.h.
         {
             /* We unconditionally create an Integer even if we're a positive
              * value, because one part of this is the type change to
              * xs:integer.
              *
              * We've manually inlined qAbs() and invoke xsInteger's
              * constructor. The reason being that we other gets truncation down
              * to StorageType. See for instance XQTS test case absint1args-1. */
             return Numeric::Ptr(static_cast<Numeric *>(const_cast<AtomicValue *>(Integer::fromValue(largerOrEqual(m_value, 0) ? xsInteger(m_value) : -xsInteger(m_value)).asAtomicValue())));
         }
ceiling()
template<TypeOfDerivedInteger DerivedType> virtual Numeric::Ptr QPatternist::DerivedInteger< DerivedType >::ceiling () const inline virtual
Performs the algorithm specified for the function fn:ceiling on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.2 fn:ceiling
Implements QPatternist::Numeric.
Definition at line 528 of file qderivedinteger_p.h.
         {
             return Numeric::Ptr(static_cast<Numeric *>(const_cast<AtomicValue *>(Integer::fromValue(m_value).asAtomicValue())));
         }
evaluateEBV()
template<TypeOfDerivedInteger DerivedType> bool QPatternist::DerivedInteger< DerivedType >::evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &) const inline virtual
Determines the Effective Boolean Value of this number.
Returns
false if the number is 0, otherwise true.
Reimplemented from QPatternist::AtomicValue.
Definition at line 477 of file qderivedinteger_p.h.
         {
             return m_value != 0;
         }
floor()
template<TypeOfDerivedInteger DerivedType> virtual Numeric::Ptr QPatternist::DerivedInteger< DerivedType >::floor () const inline virtual
Performs the algorithm specified for the function fn:floor on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.3 fn:floor
Implements QPatternist::Numeric.
Definition at line 523 of file qderivedinteger_p.h.
         {
             return Numeric::Ptr(static_cast<Numeric *>(const_cast<AtomicValue *>(Integer::fromValue(m_value).asAtomicValue())));
         }
fromLexical()
template<TypeOfDerivedInteger DerivedType> static AtomicValue::Ptr QPatternist::DerivedInteger< DerivedType >::fromLexical (const NamePool::Ptr & np, const QString & strNumeric) inline static
Constructs an instance from the lexical representation strNumeric.
Definition at line 430 of file qderivedinteger_p.h.
Referenced by QPatternist::StringToDerivedIntegerCaster< type >::castFrom(), QPatternist::XsdSchemaParser::parseFractionDigitsFacet(), QPatternist::XsdSchemaParser::parseLengthFacet(), QPatternist::XsdSchemaParser::parseMaxLengthFacet(), QPatternist::XsdSchemaParser::parseMinLengthFacet(), QPatternist::XsdSchemaParser::parseMinMaxConstraint(), and QPatternist::XsdSchemaParser::parseTotalDigitsFacet().
         {
             bool conversionOk = false;
             TemporaryStorageType num;
             /* Depending on the type, we need to call different conversion
              * functions on QString. */
             switch(DerivedType)
             {
                 case TypeUnsignedLong:
                 {
                     /* Qt decides to flag '-' as invalid, so remove it before. */
                     if(strNumeric.contains(QLatin1Char('-')))
                     {
                         num = QString(strNumeric).remove(QLatin1Char('-')).toULongLong(&conversionOk);
                         if(num != 0)
                             conversionOk = false;
                     }
                     else
                         num = strNumeric.toULongLong(&conversionOk);
                     break;
                 }
                 default:
                 {
                     num = strNumeric.toLongLong(&conversionOk);
                     break;
                 }
             }
             if(conversionOk)
                 return fromValue(np, num);
             else
                 return ValidationError::createError();
         }
fromValue()
template<TypeOfDerivedInteger DerivedType> static AtomicValue::Ptr QPatternist::DerivedInteger< DerivedType >::fromValue (const NamePool::Ptr & np, const TemporaryStorageType num) inline static
Definition at line 392 of file qderivedinteger_p.h.
Referenced by QPatternist::BooleanToDerivedIntegerCaster< type >::castFrom().
         {
             /* If we use minInclusive when calling lessThan(), we for some
              * reason get a linker error with GCC. Using this temporary
              * variable solves it. */
             const StorageType minimum = minInclusive;
             if((limitsUsage & LimitUpwards) &&
                num > maxInclusive)
             {
                 return ValidationError::createError(QtXmlPatterns::tr(
                     "Value %1 of type %2 exceeds maximum (%3).")
                     .arg(QPatternist::formatData(static_cast<xsInteger>(num)))
                     .arg(formatType(np, itemType()))
                     .arg(QPatternist::formatData(static_cast<xsInteger>(maxInclusive))));
             }
             else if((limitsUsage & LimitDownwards) &&
                     lessThan(num, minimum))
             {
                 return ValidationError::createError(QtXmlPatterns::tr(
                     "Value %1 of type %2 is below minimum (%3).")
                     .arg(QPatternist::formatData(static_cast<xsInteger>(num)))
                     .arg(formatType(np, itemType()))
                     .arg(QPatternist::formatData(static_cast<xsInteger>(minInclusive))));
             }
             else
                 return AtomicValue::Ptr(new DerivedInteger(num));
         }
fromValueUnchecked()
template<TypeOfDerivedInteger DerivedType> static AtomicValue::Ptr QPatternist::DerivedInteger< DerivedType >::fromValueUnchecked (const TemporaryStorageType num) inline static
Definition at line 421 of file qderivedinteger_p.h.
Referenced by QPatternist::AtomicValue::toXDM().
         {
             return AtomicValue::Ptr(new DerivedInteger(num));
         }
isInf()
template<TypeOfDerivedInteger DerivedType> virtual bool QPatternist::DerivedInteger< DerivedType >::isInf () const inline virtual
Returns
always false, xs:DerivedInteger doesn't have infinity in its value space.
Implements QPatternist::Numeric.
Definition at line 558 of file qderivedinteger_p.h.
         {
             return false;
         }
isNaN()
template<TypeOfDerivedInteger DerivedType> virtual bool QPatternist::DerivedInteger< DerivedType >::isNaN () const inline virtual
Returns
always false, xs:DerivedInteger doesn't have not-a-number in its value space.
Implements QPatternist::Numeric.
Definition at line 549 of file qderivedinteger_p.h.
         {
             return false;
         }
isSigned()
template<TypeOfDerivedInteger DerivedType> virtual bool QPatternist::DerivedInteger< DerivedType >::isSigned () const inline virtual
Returns true if this value is signed. If false is returned, the value is unsigned.
For float and decimal values, xs:double, xs:float and xs:decimal, the code asserts and behavior is undefined.
Implements QPatternist::Numeric.
Definition at line 568 of file qderivedinteger_p.h.
         {
             switch(DerivedType)
             {
                 /* Fallthrough all these. */
                 case TypeByte:
                 case TypeInt:
                 case TypeLong:
                 case TypeNegativeInteger:
                 case TypeNonNegativeInteger:
                 case TypeNonPositiveInteger:
                 case TypePositiveInteger:
                 case TypeShort:
                     return true;
                 /* Fallthrough all these. */
                 case TypeUnsignedByte:
                 case TypeUnsignedInt:
                 case TypeUnsignedLong:
                 case TypeUnsignedShort:
                     return false;
             }
             return false;
         }
itemType()
template<TypeOfDerivedInteger DerivedType> static ItemType::Ptr QPatternist::DerivedInteger< DerivedType >::itemType () inline static
Definition at line 370 of file qderivedinteger_p.h.
Referenced by QPatternist::NumericToDerivedIntegerCaster< type >::castFrom().
         {
             switch(DerivedType)
             {
                 case TypeByte:                  return BuiltinTypes::xsByte;
                 case TypeInt:                   return BuiltinTypes::xsInt;
                 case TypeLong:                  return BuiltinTypes::xsLong;
                 case TypeNegativeInteger:       return BuiltinTypes::xsNegativeInteger;
                 case TypeNonNegativeInteger:    return BuiltinTypes::xsNonNegativeInteger;
                 case TypeNonPositiveInteger:    return BuiltinTypes::xsNonPositiveInteger;
                 case TypePositiveInteger:       return BuiltinTypes::xsPositiveInteger;
                 case TypeShort:                 return BuiltinTypes::xsShort;
                 case TypeUnsignedByte:          return BuiltinTypes::xsUnsignedByte;
                 case TypeUnsignedInt:           return BuiltinTypes::xsUnsignedInt;
                 case TypeUnsignedLong:          return BuiltinTypes::xsUnsignedLong;
                 case TypeUnsignedShort:         return BuiltinTypes::xsUnsignedShort;
             }
             Q_ASSERT(false);
             return ItemType::Ptr();
         }
largerOrEqual()
template<TypeOfDerivedInteger DerivedType> template<typename A , typename B > static bool QPatternist::DerivedInteger< DerivedType >::largerOrEqual (const A & a, const B & b) inline static private
This function exists for the same reason that lessThan() do.
Definition at line 363 of file qderivedinteger_p.h.
         {
             return qint64(a) >= b;
         }
lessThan()
template<TypeOfDerivedInteger DerivedType> template<typename A , typename B > static bool QPatternist::DerivedInteger< DerivedType >::lessThan (const A & a, const B & b) inline static private
By refactoring out the simple comparison below into a template function, we avoid the warning "warning: comparison of unsigned expression < 0 is always false" with gcc when the class is instantiated with TypeUnsignedLong. The warning is a false positive since we check wehther LimitUpwards is set before instantiating.
This template function exists for no other reason.
Definition at line 354 of file qderivedinteger_p.h.
         {
             return a < b;
         }
round()
template<TypeOfDerivedInteger DerivedType> virtual Numeric::Ptr QPatternist::DerivedInteger< DerivedType >::round () const inline virtual
Performs the algorithm specified for the function fn:round on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.4 fn:round
Implements QPatternist::Numeric.
Definition at line 512 of file qderivedinteger_p.h.
         {
             /* xs:integerS never have a mantissa. */
             return Numeric::Ptr(static_cast<Numeric *>(const_cast<AtomicValue *>(Integer::fromValue(m_value).asAtomicValue())));
         }
roundHalfToEven()
template<TypeOfDerivedInteger DerivedType> virtual Numeric::Ptr QPatternist::DerivedInteger< DerivedType >::roundHalfToEven (const xsInteger scale) const inline virtual
Performs rounding as defined for the fn:round-half-to-even on this Numeric, and whose result is returned.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 6.4.5 fn:round-half-to-even
Implements QPatternist::Numeric.
Definition at line 518 of file qderivedinteger_p.h.
         {
             return Numeric::Ptr(static_cast<Numeric *>(const_cast<AtomicValue *>(Integer::fromValue(m_value).asAtomicValue())));
         }
storedValue()
template<TypeOfDerivedInteger DerivedType> StorageType QPatternist::DerivedInteger< DerivedType >::storedValue () const inline
Definition at line 467 of file qderivedinteger_p.h.
Referenced by QPatternist::XsdSchemaParser::parseMinMaxConstraint(), and QPatternist::AtomicValue::toQt().
         {
             return m_value;
         }
stringValue()
template<TypeOfDerivedInteger DerivedType> virtual QString QPatternist::DerivedInteger< DerivedType >::stringValue () const inline virtual
Implements QPatternist::AtomicValue.
Definition at line 482 of file qderivedinteger_p.h.
         {
             return QString::number(m_value);
         }
toDecimal()
template<TypeOfDerivedInteger DerivedType> virtual xsDecimal QPatternist::DerivedInteger< DerivedType >::toDecimal () const inline virtual
Returns
the particular number's value as a native representation of the type xs:decimal. This can be considered that the value is cast to xs:decimal.
Implements QPatternist::Numeric.
Definition at line 507 of file qderivedinteger_p.h.
         {
             return static_cast<xsDecimal>(m_value);
         }
toDouble()
template<TypeOfDerivedInteger DerivedType> virtual xsDouble QPatternist::DerivedInteger< DerivedType >::toDouble () const inline virtual
Returns
the particular number's value as a native representation of the type xs:double. This can be considered that the value is cast to xs:double.
Implements QPatternist::Numeric.
Definition at line 492 of file qderivedinteger_p.h.
         {
             return static_cast<xsDouble>(m_value);
         }
toFloat()
template<TypeOfDerivedInteger DerivedType> virtual xsFloat QPatternist::DerivedInteger< DerivedType >::toFloat () const inline virtual
Returns
the particular number's value as a native representation of the type xs:float. This can be considered that the value is cast to xs:float.
Implements QPatternist::Numeric.
Definition at line 502 of file qderivedinteger_p.h.
         {
             return static_cast<xsFloat>(m_value);
         }
toInteger()
template<TypeOfDerivedInteger DerivedType> virtual xsInteger QPatternist::DerivedInteger< DerivedType >::toInteger () const inline virtual
Returns
the particular number's value as a native representation of the type xs:integer. This can be considered that the value is cast to xs:integer.
Implements QPatternist::Numeric.
Definition at line 497 of file qderivedinteger_p.h.
         {
             return m_value;
         }
toNegated()
template<TypeOfDerivedInteger DerivedType> virtual Item QPatternist::DerivedInteger< DerivedType >::toNegated () const inline virtual
Unary minus.
Implements QPatternist::Numeric.
Definition at line 563 of file qderivedinteger_p.h.
         {
             return Integer::fromValue(-xsInteger(m_value));
         }
toUnsignedInteger()
template<TypeOfDerivedInteger DerivedType> virtual qulonglong QPatternist::DerivedInteger< DerivedType >::toUnsignedInteger () const inline virtual
Returns
the number as an unsigned integer. If the value is not unsigned, the code asserts and behavior is undefined.
Implements QPatternist::Numeric.
Definition at line 592 of file qderivedinteger_p.h.
         {
             switch(DerivedType)
             {
                 /* Fallthrough all these. */
                 case TypeByte:
                 case TypeInt:
                 case TypeLong:
                 case TypeNegativeInteger:
                 case TypeNonNegativeInteger:
                 case TypeNonPositiveInteger:
                 case TypePositiveInteger:
                 case TypeShort:
                     Q_ASSERT_X(false, Q_FUNC_INFO,
                                "It makes no sense to call this function, see Numeric::toUnsignedInteger().");
                 /* Fallthrough all these. */
                 case TypeUnsignedByte:
                 case TypeUnsignedInt:
                 case TypeUnsignedLong:
                 case TypeUnsignedShort:
                     return m_value;
             }
             return 0;
         }
type()
template<TypeOfDerivedInteger DerivedType> virtual ItemType::Ptr QPatternist::DerivedInteger< DerivedType >::type () const inline virtual
Implements QPatternist::AtomicValue.
Definition at line 487 of file qderivedinteger_p.h.
         {
             return itemType();
         }
Friends and Related Functions
DerivedIntegerLimitsUsage
template<TypeOfDerivedInteger DerivedType> enum DerivedIntegerLimitsUsage related
Definition at line 69 of file qderivedinteger_p.h.
     {
         None            = 1,
         LimitUpwards    = 2,
         LimitDownwards  = 4,
         LimitBoth       = LimitUpwards | LimitDownwards
     };
Properties
limitsUsage
template<TypeOfDerivedInteger DerivedType> const DerivedIntegerLimitsUsage QPatternist::DerivedInteger< DerivedType >::limitsUsage = DerivedIntegerDetails<DerivedType>::limitsUsage static private
Definition at line 337 of file qderivedinteger_p.h.
m_value
template<TypeOfDerivedInteger DerivedType> const StorageType QPatternist::DerivedInteger< DerivedType >::m_value private
Definition at line 339 of file qderivedinteger_p.h.
maxInclusive
template<TypeOfDerivedInteger DerivedType> const StorageType QPatternist::DerivedInteger< DerivedType >::maxInclusive = DerivedIntegerDetails<DerivedType>::maxInclusive static private
Definition at line 335 of file qderivedinteger_p.h.
minInclusive
template<TypeOfDerivedInteger DerivedType> const StorageType QPatternist::DerivedInteger< DerivedType >::minInclusive = DerivedIntegerDetails<DerivedType>::minInclusive static private
Definition at line 336 of file qderivedinteger_p.h.
The documentation for this class was generated from the following file:
/src/xmlpatterns/data/qderivedinteger_p.h