Qt 4.8: QDB2Driver Class Reference
QDB2Driver Class Reference
#include <qsql_db2.h>
Public Functions
bool beginTransaction ()
This function is called to begin a transaction.
void close ()
Derived classes must reimplement this pure virtual function in order to close the database connection.
bool commitTransaction ()
This function is called to commit a transaction.
QSqlResult * createResult () const
Creates an empty SQL result on the database.
QString escapeIdentifier (const QString &identifier, IdentifierType type) const
Returns the identifier escaped according to the database rules.
QString formatValue (const QSqlField &field, bool trimStrings) const
Returns a string representation of the field value for the database.
QVariant handle () const
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
bool hasFeature (DriverFeature) const
Returns true if the driver supports feature feature; otherwise returns false.
bool open (const QString &db, const QString &user, const QString &password, const QString &host, int port, const QString &connOpts)
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
QSqlIndex primaryIndex (const QString &tablename) const
Returns the primary index for table tableName.
QDB2Driver (QObject *parent=0)
QDB2Driver (Qt::HANDLE env, Qt::HANDLE con, QObject *parent=0)
QSqlRecord record (const QString &tableName) const
Returns a QSqlRecord populated with the names of the fields in table tableName.
bool rollbackTransaction ()
This function is called to rollback a transaction.
QStringList tables (QSql::TableType type) const
Returns a list of the names of the tables in the database.
~QDB2Driver ()
Public Functions inherited from QSqlDriver
bool isIdentifierEscaped (const QString &identifier, IdentifierType type) const
Returns whether identifier is escaped according to the database rules.
virtual bool isOpen () const
Returns true if the database connection is open; otherwise returns false.
bool isOpenError () const
Returns true if the there was an error opening the database connection; otherwise returns false.
QSqlError lastError () const
Returns a QSqlError object which contains information about the last error that occurred on the database.
QSql::NumericalPrecisionPolicy numericalPrecisionPolicy () const
Returns the current default precision policy for the database connection.
QSqlDriver (QObject *parent=0)
Constructs a new driver with the given parent.
void setNumericalPrecisionPolicy (QSql::NumericalPrecisionPolicy precisionPolicy)
Sets the default numerical precision policy used by queries created by this driver to precisionPolicy.
virtual QString sqlStatement (StatementType type, const QString &tableName, const QSqlRecord &rec, bool preparedStatement) const
Returns a SQL statement of type type for the table tableName with the values from rec.
QString stripDelimiters (const QString &identifier, IdentifierType type) const
Returns the identifier with the leading and trailing delimiters removed, identifier can either be a table name or field name, dependent on type.
QStringList subscribedToNotifications () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotification (const QString &name)
This function is called to subscribe to event notifications from the database.
bool unsubscribeFromNotification (const QString &name)
This function is called to unsubscribe from event notifications from the database.
~QSqlDriver ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
bool setAutoCommit (bool autoCommit)
Properties
QDB2DriverPrivate * d
Additional Inherited Members
Public Types inherited from QSqlDriver
enum DriverFeature {
Transactions, QuerySize, BLOB, Unicode,
PreparedQueries, NamedPlaceholders, PositionalPlaceholders, LastInsertId,
BatchOperations, SimpleLocking, LowPrecisionNumbers, EventNotifications,
FinishQuery, MultipleResultSets
}
This enum contains a list of features a driver might support.
enum IdentifierType { FieldName, TableName }
This enum contains a list of SQL identifier types.
enum StatementType {
WhereStatement, SelectStatement, UpdateStatement, InsertStatement,
DeleteStatement
}
This enum contains a list of SQL statement (or clause) types the driver can create.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QSqlDriver
void notification (const QString &name)
This signal is emitted when the database posts an event notification that the driver subscribes to.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QSqlDriver
bool isIdentifierEscapedImplementation (const QString &identifier, IdentifierType type) const
This slot returns whether identifier is escaped according to the database rules.
QString stripDelimitersImplementation (const QString &identifier, IdentifierType type) const
This slot returns identifier with the leading and trailing delimiters removed, identifier can either be a tablename or field name, dependent on type.
QStringList subscribedToNotificationsImplementation () const
Returns a list of the names of the event notifications that are currently subscribed to.
bool subscribeToNotificationImplementation (const QString &name)
This slot is called to subscribe to event notifications from the database.
bool unsubscribeFromNotificationImplementation (const QString &name)
This slot is called to unsubscribe from event notifications from the database.
Protected Functions inherited from QSqlDriver
virtual void setLastError (const QSqlError &e)
This function is used to set the value of the last error, error, that occurred on the database.
virtual void setOpen (bool o)
This function sets the open state of the database to open.
virtual void setOpenError (bool e)
This function sets the open error state of the database to error.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 89 of file qsql_db2.h.
Constructors and Destructors
QDB2Driver() [1/2]
QDB2Driver::QDB2Driver (QObject * parent = 0) explicit
Definition at line 1138 of file qsql_db2.cpp.
     : QSqlDriver(parent)
 {
     d = new QDB2DriverPrivate;
 }
QDB2Driver() [2/2]
QDB2Driver::QDB2Driver (Qt::HANDLE env, Qt::HANDLE con, QObject * parent = 0)
Definition at line 1144 of file qsql_db2.cpp.
     : QSqlDriver(parent)
 {
     d = new QDB2DriverPrivate;
     d->hEnv = (SQLHANDLE)env;
     d->hDbc = (SQLHANDLE)con;
     if (env && con) {
         setOpen(true);
         setOpenError(false);
     }
 }
~QDB2Driver()
QDB2Driver::~QDB2Driver ()
Definition at line 1156 of file qsql_db2.cpp.
 {
     close();
     delete d;
 }
Functions
beginTransaction()
bool QDB2Driver::beginTransaction () virtual
This function is called to begin a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
commitTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 1532 of file qsql_db2.cpp.
 {
     if (!isOpen()) {
         qWarning("QDB2Driver::beginTransaction: Database not open");
         return false;
     }
     return setAutoCommit(false);
 }
close()
void QDB2Driver::close () virtual
Derived classes must reimplement this pure virtual function in order to close the database connection.
Return true on success, false on failure.
See also
open(), setOpen()
Implements QSqlDriver.
Definition at line 1265 of file qsql_db2.cpp.
Referenced by open(), and ~QDB2Driver().
 {
     SQLRETURN r;
     if (d->hDbc) {
         // Open statements/descriptors handles are automatically cleaned up by SQLDisconnect
         if (isOpen()) {
             r = SQLDisconnect(d->hDbc);
             if (r != SQL_SUCCESS)
                 qSqlWarning(QLatin1String("QDB2Driver::close: Unable to disconnect datasource"), d);
         }
         r = SQLFreeHandle(SQL_HANDLE_DBC, d->hDbc);
         if (r != SQL_SUCCESS)
             qSqlWarning(QLatin1String("QDB2Driver::close: Unable to free connection handle"), d);
         d->hDbc = 0;
     }
     if (d->hEnv) {
         r = SQLFreeHandle(SQL_HANDLE_ENV, d->hEnv);
         if (r != SQL_SUCCESS)
             qSqlWarning(QLatin1String("QDB2Driver::close: Unable to free environment handle"), d);
         d->hEnv = 0;
     }
     setOpen(false);
     setOpenError(false);
 }
commitTransaction()
bool QDB2Driver::commitTransaction () virtual
This function is called to commit a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), rollbackTransaction()
Reimplemented from QSqlDriver.
Definition at line 1541 of file qsql_db2.cpp.
 {
     if (!isOpen()) {
         qWarning("QDB2Driver::commitTransaction: Database not open");
         return false;
     }
     SQLRETURN r = SQLEndTran(SQL_HANDLE_DBC,
                               d->hDbc,
                               SQL_COMMIT);
     if (r != SQL_SUCCESS) {
         setLastError(qMakeError(tr("Unable to commit transaction"),
                      QSqlError::TransactionError, d));
         return false;
     }
     return setAutoCommit(true);
 }
createResult()
QSqlResult * QDB2Driver::createResult () const virtual
Creates an empty SQL result on the database.
Derived classes must reimplement this function and return a QSqlResult object appropriate for their database to the caller.
Implements QSqlDriver.
Definition at line 1291 of file qsql_db2.cpp.
 {
     return new QDB2Result(this, d);
 }
escapeIdentifier()
QString QDB2Driver::escapeIdentifier (const QString & identifier, IdentifierType type) const virtual
Returns the identifier escaped according to the database rules.
identifier can either be a table name or field name, dependent on type.
The default implementation does nothing.
See also
isIdentifierEscaped()
Reimplemented from QSqlDriver.
Definition at line 1638 of file qsql_db2.cpp.
 {
     QString res = identifier;
     if(!identifier.isEmpty() && !identifier.startsWith(QLatin1Char('"')) && !identifier.endsWith(QLatin1Char('"')) ) {
         res.replace(QLatin1Char('"'), QLatin1String("\"\""));
         res.prepend(QLatin1Char('"')).append(QLatin1Char('"'));
         res.replace(QLatin1Char('.'), QLatin1String("\".\""));
     }
     return res;
 }
formatValue()
QString QDB2Driver::formatValue (const QSqlField & field, bool trimStrings) const virtual
Returns a string representation of the field value for the database.
Use the other formatValue() overload instead.
This is used, for example, when constructing INSERT and UPDATE statements.
The default implementation returns the value formatted as a string according to the following rules:
If field is character data, the value is returned enclosed in single quotation marks, which is appropriate for many SQL databases. Any embedded single-quote characters are escaped (replaced with two single-quote characters). If trimStrings is true (the default is false), all trailing whitespace is trimmed from the field.
If field is date/time data, the value is formatted in ISO format and enclosed in single quotation marks. If the date/time data is invalid, "NULL" is returned.
If field is bytearray data, and the driver can edit binary fields, the value is formatted as a hexadecimal string.
For any other field type, toString() is called on its value and the result of this is returned.
See also
QVariant::toString()
Reimplemented from QSqlDriver.
Definition at line 1590 of file qsql_db2.cpp.
 {
     if (field.isNull())
         return QLatin1String("NULL");
     switch (field.type()) {
         case QVariant::DateTime: {
             // Use an escape sequence for the datetime fields
             if (field.value().toDateTime().isValid()) {
                 QDate dt = field.value().toDateTime().date();
                 QTime tm = field.value().toDateTime().time();
                 // Dateformat has to be "yyyy-MM-dd hh:mm:ss", with leading zeroes if month or day < 10
                 return QLatin1Char('\'') + QString::number(dt.year()) + QLatin1Char('-')
                        + QString::number(dt.month()) + QLatin1Char('-')
                        + QString::number(dt.day()) + QLatin1Char('-')
                        + QString::number(tm.hour()) + QLatin1Char('.')
                        + QString::number(tm.minute()).rightJustified(2, QLatin1Char('0'), true)
                        + QLatin1Char('.')
                        + QString::number(tm.second()).rightJustified(2, QLatin1Char('0'), true)
                        + QLatin1Char('.')
                        + QString::number(tm.msec() * 1000).rightJustified(6, QLatin1Char('0'), true)
                        + QLatin1Char('\'');
                 } else {
                     return QLatin1String("NULL");
                 }
         }
         case QVariant::ByteArray: {
             QByteArray ba = field.value().toByteArray();
             QString res = QString::fromLatin1("BLOB(X'");
             static const char hexchars[] = "0123456789abcdef";
             for (int i = 0; i < ba.size(); ++i) {
                 uchar s = (uchar) ba[i];
                 res += QLatin1Char(hexchars[s >> 4]);
                 res += QLatin1Char(hexchars[s & 0x0f]);
             }
             res += QLatin1String("')");
             return res;
         }
         default:
             return QSqlDriver::formatValue(field, trimStrings);
     }
 }
handle()
QVariant QDB2Driver::handle () const virtual
Returns the low-level database handle wrapped in a QVariant or an invalid variant if there is no handle.
Warning
Use this with uttermost care and only if you know what you're doing.
The handle returned here can become a stale pointer if the connection is modified (for example, if you close the connection).
The handle can be NULL if the connection is not open yet.
The handle returned here is database-dependent, you should query the type name of the variant before accessing it.
This example retrieves the handle for a connection to sqlite:
QSqlDatabase db = ...;
QVariant v = db.driver()->handle();
if (v.isValid() && qstrcmp(v.typeName(), "sqlite3*") == 0) {
    // v.data() returns a pointer to the handle
    sqlite3 *handle = *static_cast<sqlite3 **>(v.data());
    if (handle != 0) { // check that it is not NULL
        ...
    }
}
This snippet returns the handle for PostgreSQL or MySQL:
if (qstrcmp(v.typeName(), "PGconn*") == 0) {
    PGconn *handle = *static_cast<PGconn **>(v.data());
    if (handle != 0) ...
}
if (qstrcmp(v.typeName(), "MYSQL*") == 0) {
    MYSQL *handle = *static_cast<MYSQL **>(v.data());
    if (handle != 0) ...
}
See also
QSqlResult::handle()
Reimplemented from QSqlDriver.
Definition at line 1633 of file qsql_db2.cpp.
 {
     return QVariant(qRegisterMetaType<SQLHANDLE>("SQLHANDLE"), &d->hDbc);
 }
hasFeature()
bool QDB2Driver::hasFeature (DriverFeature feature) const virtual
Returns true if the driver supports feature feature; otherwise returns false.
Note that some databases need to be open() before this can be determined.
See also
DriverFeature
Implements QSqlDriver.
Definition at line 1508 of file qsql_db2.cpp.
 {
     switch (f) {
         case QuerySize:
         case NamedPlaceholders:
         case BatchOperations:
         case LastInsertId:
         case SimpleLocking:
         case EventNotifications:
             return false;
         case BLOB:
         case Transactions:
         case MultipleResultSets:
         case PreparedQueries:
         case PositionalPlaceholders:
         case LowPrecisionNumbers:
         case FinishQuery:
             return true;
         case Unicode:
             return true;
     }
     return false;
 }
open()
bool QDB2Driver::open (const QString & db, const QString & user, const QString & password, const QString & host, int port, const QString & options) virtual
Derived classes must reimplement this pure virtual function to open a database connection on database db, using user name user, password password, host host, port port and connection options options.
The function must return true on success and false on failure.
See also
setOpen()
Implements QSqlDriver.
Definition at line 1162 of file qsql_db2.cpp.
 {
     if (isOpen())
       close();
     SQLRETURN r;
     r = SQLAllocHandle(SQL_HANDLE_ENV,
                         SQL_NULL_HANDLE,
                         &d->hEnv);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         qSqlWarning(QLatin1String("QDB2Driver::open: Unable to allocate environment"), d);
         setOpenError(true);
         return false;
     }
     r = SQLAllocHandle(SQL_HANDLE_DBC,
                         d->hEnv,
                         &d->hDbc);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         qSqlWarning(QLatin1String("QDB2Driver::open: Unable to allocate connection"), d);
         setOpenError(true);
         return false;
     }
     QString protocol;
     // Set connection attributes
     const QStringList opts(connOpts.split(QLatin1Char(';'), QString::SkipEmptyParts));
     for (int i = 0; i < opts.count(); ++i) {
         const QString tmp(opts.at(i));
         int idx;
         if ((idx = tmp.indexOf(QLatin1Char('='))) == -1) {
             qWarning("QDB2Driver::open: Illegal connect option value '%s'",
                      tmp.toLocal8Bit().constData());
             continue;
         }
         const QString opt(tmp.left(idx));
         const QString val(tmp.mid(idx + 1).simplified());
         SQLUINTEGER v = 0;
         r = SQL_SUCCESS;
         if (opt == QLatin1String("SQL_ATTR_ACCESS_MODE")) {
             if (val == QLatin1String("SQL_MODE_READ_ONLY")) {
                 v = SQL_MODE_READ_ONLY;
             } else if (val == QLatin1String("SQL_MODE_READ_WRITE")) {
                 v = SQL_MODE_READ_WRITE;
             } else {
                 qWarning("QDB2Driver::open: Unknown option value '%s'",
                          tmp.toLocal8Bit().constData());
                 continue;
             }
             r = SQLSetConnectAttr(d->hDbc, SQL_ATTR_ACCESS_MODE, (SQLPOINTER) v, 0);
         } else if (opt == QLatin1String("SQL_ATTR_LOGIN_TIMEOUT")) {
             v = val.toUInt();
             r = SQLSetConnectAttr(d->hDbc, SQL_ATTR_LOGIN_TIMEOUT, (SQLPOINTER) v, 0);
         } else if (opt.compare(QLatin1String("PROTOCOL"), Qt::CaseInsensitive) == 0) {
                         protocol = tmp;
         }
         else {
             qWarning("QDB2Driver::open: Unknown connection attribute '%s'",
                       tmp.toLocal8Bit().constData());
         }
         if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO)
             qSqlWarning(QString::fromLatin1("QDB2Driver::open: "
                            "Unable to set connection attribute '%1'").arg(opt), d);
     }
     if (protocol.isEmpty())
         protocol = QLatin1String("PROTOCOL=TCPIP");
     if (port < 0 )
         port = 50000;
     QString connQStr;
     connQStr =  protocol + QLatin1String(";DATABASE=") + db + QLatin1String(";HOSTNAME=") + host
         + QLatin1String(";PORT=") + QString::number(port) + QLatin1String(";UID=") + user
         + QLatin1String(";PWD=") + password;
     SQLTCHAR connOut[SQL_MAX_OPTION_STRING_LENGTH];
     SQLSMALLINT cb;
     r = SQLDriverConnect(d->hDbc,
                           NULL,
                           qToTChar(connQStr),
                           (SQLSMALLINT) connQStr.length(),
                           connOut,
                           SQL_MAX_OPTION_STRING_LENGTH,
                           &cb,
                           SQL_DRIVER_NOPROMPT);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         setLastError(qMakeError(tr("Unable to connect"),
                                 QSqlError::ConnectionError, d));
         setOpenError(true);
         return false;
     }
     d->user = user;
     setOpen(true);
     setOpenError(false);
     return true;
 }
primaryIndex()
QSqlIndex QDB2Driver::primaryIndex (const QString & tableName) const virtual
Returns the primary index for table tableName.
Returns an empty QSqlIndex if the table doesn't have a primary index. The default implementation returns an empty index.
Reimplemented from QSqlDriver.
Definition at line 1440 of file qsql_db2.cpp.
 {
     QSqlIndex index(tablename);
     if (!isOpen())
         return index;
     QSqlRecord rec = record(tablename);
     SQLHANDLE hStmt;
     SQLRETURN r = SQLAllocHandle(SQL_HANDLE_STMT,
                                   d->hDbc,
                                   &hStmt);
     if (r != SQL_SUCCESS) {
         qSqlWarning(QLatin1String("QDB2Driver::primaryIndex: Unable to list primary key"), d);
         return index;
     }
     QString catalog, schema, table;
     qSplitTableQualifier(tablename, &catalog, &schema, &table);
     if (isIdentifierEscaped(catalog, QSqlDriver::TableName))
         catalog = stripDelimiters(catalog, QSqlDriver::TableName);
     else
         catalog = catalog.toUpper();
     if (isIdentifierEscaped(schema, QSqlDriver::TableName))
         schema = stripDelimiters(schema, QSqlDriver::TableName);
     else
         schema = schema.toUpper();
     if (isIdentifierEscaped(table, QSqlDriver::TableName))
         table = stripDelimiters(table, QSqlDriver::TableName);
     else
         table = table.toUpper();
     r = SQLSetStmtAttr(hStmt,
                         SQL_ATTR_CURSOR_TYPE,
                         (SQLPOINTER)SQL_CURSOR_FORWARD_ONLY,
                         SQL_IS_UINTEGER);
     r = SQLPrimaryKeys(hStmt,
                         NULL,
                         0,
                         qToTChar(schema),
                         schema.length(),
                         qToTChar(table),
                         table.length());
     r = SQLFetchScroll(hStmt,
                         SQL_FETCH_NEXT,
                         0);
     bool isNull;
     QString cName, idxName;
     // Store all fields in a StringList because the driver can't detail fields in this FETCH loop
     while (r == SQL_SUCCESS) {
         cName = qGetStringData(hStmt, 3, -1, isNull); // column name
         idxName = qGetStringData(hStmt, 5, -1, isNull); // pk index name
         index.append(rec.field(cName));
         index.setName(idxName);
         r = SQLFetchScroll(hStmt,
                             SQL_FETCH_NEXT,
                             0);
     }
     r = SQLFreeHandle(SQL_HANDLE_STMT, hStmt);
     if (r!= SQL_SUCCESS)
         qSqlWarning(QLatin1String("QDB2Driver: Unable to free statement handle ")
                     + QString::number(r), d);
     return index;
 }
record()
QSqlRecord QDB2Driver::record (const QString & tableName) const virtual
Returns a QSqlRecord populated with the names of the fields in table tableName.
Use query.
If no such table exists, an empty record is returned. The default implementation returns an empty record.
record() instead.
Reimplemented from QSqlDriver.
Definition at line 1296 of file qsql_db2.cpp.
Referenced by primaryIndex().
 {
     QSqlRecord fil;
     if (!isOpen())
         return fil;
     SQLHANDLE hStmt;
     QString catalog, schema, table;
     qSplitTableQualifier(tableName, &catalog, &schema, &table);
     if (schema.isEmpty())
         schema = d->user;
     if (isIdentifierEscaped(catalog, QSqlDriver::TableName))
         catalog = stripDelimiters(catalog, QSqlDriver::TableName);
     else
         catalog = catalog.toUpper();
     if (isIdentifierEscaped(schema, QSqlDriver::TableName))
         schema = stripDelimiters(schema, QSqlDriver::TableName);
     else
         schema = schema.toUpper();
     if (isIdentifierEscaped(table, QSqlDriver::TableName))
         table = stripDelimiters(table, QSqlDriver::TableName);
     else
         table = table.toUpper();
     SQLRETURN r = SQLAllocHandle(SQL_HANDLE_STMT,
                                   d->hDbc,
                                   &hStmt);
     if (r != SQL_SUCCESS) {
         qSqlWarning(QLatin1String("QDB2Driver::record: Unable to allocate handle"), d);
         return fil;
     }
     r = SQLSetStmtAttr(hStmt,
                         SQL_ATTR_CURSOR_TYPE,
                         (SQLPOINTER) SQL_CURSOR_FORWARD_ONLY,
                         SQL_IS_UINTEGER);
     //Aside: szSchemaName and szTableName parameters of SQLColumns
     //are case sensitive search patterns, so no escaping is used.
     r =  SQLColumns(hStmt,
                      NULL,
                      0,
                      qToTChar(schema),
                      schema.length(),
                      qToTChar(table),
                      table.length(),
                      NULL,
                      0);
     if (r != SQL_SUCCESS)
         qSqlWarning(QLatin1String("QDB2Driver::record: Unable to execute column list"), d);
     r = SQLFetchScroll(hStmt,
                         SQL_FETCH_NEXT,
                         0);
     while (r == SQL_SUCCESS) {
         fil.append(qMakeFieldInfo(hStmt));
         r = SQLFetchScroll(hStmt,
                             SQL_FETCH_NEXT,
                             0);
     }
     r = SQLFreeHandle(SQL_HANDLE_STMT, hStmt);
     if (r != SQL_SUCCESS)
         qSqlWarning(QLatin1String("QDB2Driver: Unable to free statement handle ")
                     + QString::number(r), d);
     return fil;
 }
rollbackTransaction()
bool QDB2Driver::rollbackTransaction () virtual
This function is called to rollback a transaction.
If successful, return true, otherwise return false. The default implementation does nothing and returns false.
See also
beginTransaction(), commitTransaction()
Reimplemented from QSqlDriver.
Definition at line 1558 of file qsql_db2.cpp.
 {
     if (!isOpen()) {
         qWarning("QDB2Driver::rollbackTransaction: Database not open");
         return false;
     }
     SQLRETURN r = SQLEndTran(SQL_HANDLE_DBC,
                               d->hDbc,
                               SQL_ROLLBACK);
     if (r != SQL_SUCCESS) {
         setLastError(qMakeError(tr("Unable to rollback transaction"),
                                 QSqlError::TransactionError, d));
         return false;
     }
     return setAutoCommit(true);
 }
setAutoCommit()
bool QDB2Driver::setAutoCommit (bool autoCommit) private
Definition at line 1575 of file qsql_db2.cpp.
Referenced by beginTransaction(), commitTransaction(), and rollbackTransaction().
 {
     SQLUINTEGER ac = autoCommit ? SQL_AUTOCOMMIT_ON : SQL_AUTOCOMMIT_OFF;
     SQLRETURN r  = SQLSetConnectAttr(d->hDbc,
                                       SQL_ATTR_AUTOCOMMIT,
                                       (SQLPOINTER)ac,
                                       sizeof(ac));
     if (r != SQL_SUCCESS) {
         setLastError(qMakeError(tr("Unable to set autocommit"),
                                 QSqlError::TransactionError, d));
         return false;
     }
     return true;
 }
tables()
QStringList QDB2Driver::tables (QSql::TableType tableType) const virtual
Returns a list of the names of the tables in the database.
The default implementation returns an empty list.
The tableType argument describes what types of tables should be returned. Due to binary compatibility, the string contains the value of the enum QSql::TableTypes as text. An empty string should be treated as QSql::Tables for backward compatibility.
Reimplemented from QSqlDriver.
Definition at line 1369 of file qsql_db2.cpp.
 {
     QStringList tl;
     if (!isOpen())
         return tl;
     SQLHANDLE hStmt;
     SQLRETURN r = SQLAllocHandle(SQL_HANDLE_STMT,
                                   d->hDbc,
                                   &hStmt);
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO) {
         qSqlWarning(QLatin1String("QDB2Driver::tables: Unable to allocate handle"), d);
         return tl;
     }
     r = SQLSetStmtAttr(hStmt,
                         SQL_ATTR_CURSOR_TYPE,
                         (SQLPOINTER)SQL_CURSOR_FORWARD_ONLY,
                         SQL_IS_UINTEGER);
     QString tableType;
     if (type & QSql::Tables)
         tableType += QLatin1String("TABLE,");
     if (type & QSql::Views)
         tableType += QLatin1String("VIEW,");
     if (type & QSql::SystemTables)
         tableType += QLatin1String("SYSTEM TABLE,");
     if (tableType.isEmpty())
         return tl;
     tableType.chop(1);
     r = SQLTables(hStmt,
                    NULL,
                    0,
                    NULL,
                    0,
                    NULL,
                    0,
                    qToTChar(tableType),
                    tableType.length());
     if (r != SQL_SUCCESS && r != SQL_SUCCESS_WITH_INFO)
         qSqlWarning(QLatin1String("QDB2Driver::tables: Unable to execute table list"), d);
     r = SQLFetchScroll(hStmt,
                         SQL_FETCH_NEXT,
                         0);
     while (r == SQL_SUCCESS) {
         bool isNull;
         QString fieldVal = qGetStringData(hStmt, 2, -1, isNull);
         QString userVal = qGetStringData(hStmt, 1, -1, isNull);
         QString user = d->user;
         if ( isIdentifierEscaped(user, QSqlDriver::TableName))
             user = stripDelimiters(user, QSqlDriver::TableName);
         else
             user = user.toUpper();
         if (userVal != user)
             fieldVal = userVal + QLatin1Char('.') + fieldVal;
         tl.append(fieldVal);
         r = SQLFetchScroll(hStmt,
                             SQL_FETCH_NEXT,
                             0);
     }
     r = SQLFreeHandle(SQL_HANDLE_STMT, hStmt);
     if (r != SQL_SUCCESS)
         qSqlWarning(QLatin1String("QDB2Driver::tables: Unable to free statement handle ")
                     + QString::number(r), d);
     return tl;
 }
Properties
d
QDB2DriverPrivate* QDB2Driver::d private
Definition at line 117 of file qsql_db2.h.
Referenced by close(), commitTransaction(), createResult(), handle(), open(), primaryIndex(), QDB2Driver(), record(), rollbackTransaction(), setAutoCommit(), tables(), and ~QDB2Driver().
The documentation for this class was generated from the following files:
/src/sql/drivers/db2/qsql_db2.h
/src/sql/drivers/db2/qsql_db2.cpp