Qt 4.8: QSqlRelationalTableModel Class Reference
QSqlRelationalTableModel Class Reference
The QSqlRelationalTableModel class provides an editable data model for a single database table, with foreign key support.
#include <qsqlrelationaltablemodel.h>
Public Types
enum JoinMode { InnerJoin, LeftJoin }
This enum specifies the type of mode to use when joining two tables.
Public Types inherited from QSqlTableModel
enum EditStrategy { OnFieldChange, OnRowChange, OnManualSubmit }
This enum type describes which strategy to choose when editing values in the database.
Public Slots
void revertRow (int row)
Reimplemented Function
Public Slots inherited from QSqlTableModel
void revert ()
This reimplemented slot is called by the item delegates when the user canceled editing the current row.
void revertAll ()
Reverts all pending changes.
bool submit ()
This reimplemented slot is called by the item delegates when the user stopped editing the current row.
bool submitAll ()
Submits all pending changes and returns true on success.
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void clear ()
Reimplemented Function
QVariant data (const QModelIndex &item, int role=Qt::DisplayRole) const
Reimplemented Function
QSqlRelationalTableModel (QObject *parent=0, QSqlDatabase db=QSqlDatabase())
Creates an empty QSqlRelationalTableModel and sets the parent to parent and the database connection to db.
QSqlRelation relation (int column) const
Returns the relation for the column column, or an invalid relation if no relation is set.
virtual QSqlTableModel * relationModel (int column) const
Returns a QSqlTableModel object for accessing the table for which column is a foreign key, or 0 if there is no relation for the given column.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Reimplemented Function
bool select ()
Reimplemented Function
bool setData (const QModelIndex &item, const QVariant &value, int role=Qt::EditRole)
Sets the data for the role in the item with the specified index to the value given.
void setJoinMode (QSqlRelationalTableModel::JoinMode joinMode)
Sets the SQL join mode to the value given by joinMode to show or hide rows with NULL foreign keys.
virtual void setRelation (int column, const QSqlRelation &relation)
Lets the specified column be a foreign index specified by relation.
void setTable (const QString &tableName)
Reimplemented Function
virtual ~QSqlRelationalTableModel ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QSqlTableModel
void clear ()
Reimplemented Function
QVariant data (const QModelIndex &idx, int role=Qt::DisplayRole) const
Reimplemented Function
QSqlDatabase database () const
Returns a pointer to the used QSqlDatabase or 0 if no database was set.
EditStrategy editStrategy () const
Returns the current edit strategy.
int fieldIndex (const QString &fieldName) const
Returns the index of the field fieldName, or -1 if no corresponding field exists in the model.
QString filter () const
Returns the currently set filter.
Qt::ItemFlags flags (const QModelIndex &index) const
Reimplemented Function
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const
Reimplemented Function
bool insertRecord (int row, const QSqlRecord &record)
Inserts the record after row.
bool insertRows (int row, int count, const QModelIndex &parent=QModelIndex())
Inserts count empty rows at position row.
bool isDirty (const QModelIndex &index) const
Returns true if the value at the index index is dirty, otherwise false.
QSqlIndex primaryKey () const
Returns the primary key for the current table, or an empty QSqlIndex if the table is not set or has no primary key.
QSqlTableModel (QObject *parent=0, QSqlDatabase db=QSqlDatabase())
Creates an empty QSqlTableModel and sets the parent to parent and the database connection to db.
bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Removes count columns from the parent model, starting at index column.
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
Removes count rows starting at row.
virtual void revertRow (int row)
Reverts all changes for the specified row.
int rowCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
bool setData (const QModelIndex &index, const QVariant &value, int role=Qt::EditRole)
Sets the data for the item index for the role role to value.
virtual void setEditStrategy (EditStrategy strategy)
Sets the strategy for editing values in the database to strategy.
virtual void setFilter (const QString &filter)
Sets the current filter to filter.
bool setRecord (int row, const QSqlRecord &record)
Sets the values at the specified row to the values of record.
virtual void setSort (int column, Qt::SortOrder order)
Sets the sort order for column to order.
void sort (int column, Qt::SortOrder order)
Sorts the data by column with the sort order order.
QString tableName () const
Returns the name of the currently selected table.
virtual ~QSqlTableModel ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QSqlQueryModel
bool canFetchMore (const QModelIndex &parent=QModelIndex()) const
Returns true if it is possible to read more rows from the database.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Reimplemented Function
void fetchMore (const QModelIndex &parent=QModelIndex())
Fetches more rows from a database.
bool insertColumns (int column, int count, const QModelIndex &parent=QModelIndex())
Inserts count columns into the model at position column.
QSqlError lastError () const
Returns information about the last error that occurred on the database.
QSqlQueryModel (QObject *parent=0)
Creates an empty QSqlQueryModel with the given parent.
QSqlQuery query () const
Returns the QSqlQuery associated with this model.
QSqlRecord record (int row) const
Returns the record containing information about the fields of the current query.
QSqlRecord record () const
Returns an empty record containing information about the fields of the current query.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role=Qt::EditRole)
Sets the caption for a horizontal header for the specified role to value.
void setQuery (const QSqlQuery &query)
Resets the model and sets the data provider to be the given query.
void setQuery (const QString &query, const QSqlDatabase &db=QSqlDatabase())
Executes the query query for the given database connection db.
virtual ~QSqlQueryModel ()
Destroys the object and frees any allocated resources.
Public Functions inherited from QAbstractTableModel
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Reimplemented Function
QModelIndex index (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns the index of the data in row and column with parent.
QAbstractTableModel (QObject *parent=0)
Constructs an abstract table model for the given parent.
~QAbstractTableModel ()
Destroys the abstract table model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
virtual QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool insertRowIntoTable (const QSqlRecord &values)
Reimplemented Function
QString orderByClause () const
Reimplemented Function
QString selectStatement () const
Reimplemented Function
bool updateRowInTable (int row, const QSqlRecord &values)
Reimplemented Function
Protected Functions inherited from QSqlTableModel
virtual bool deleteRowFromTable (int row)
Deletes the given row from the currently active database table.
QModelIndex indexInQuery (const QModelIndex &item) const
Returns the index of the value in the database result set for the given item in the model.
QSqlTableModel (QSqlTableModelPrivate &dd, QObject *parent=0, QSqlDatabase db=QSqlDatabase())
void setPrimaryKey (const QSqlIndex &key)
Protected method that allows subclasses to set the primary key to key.
void setQuery (const QSqlQuery &query)
This function simply calls QSqlQueryModel::setQuery(query).
Protected Functions inherited from QSqlQueryModel
QModelIndex indexInQuery (const QModelIndex &item) const
Returns the index of the value in the database result set for the given item in the model.
QSqlQueryModel (QSqlQueryModelPrivate &dd, QObject *parent=0)
virtual void queryChange ()
This virtual function is called whenever the query changes.
void setLastError (const QSqlError &error)
Protected function which allows derived classes to set the value of the last error that occurred on the database to error.
Protected Functions inherited from QAbstractTableModel
QAbstractTableModel (QAbstractItemModelPrivate &dd, QObject *parent)
Constructs an abstract table model with dd and the given parent.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Signals inherited from QSqlTableModel
void beforeDelete (int row)
This signal is emitted by deleteRowFromTable() before the row is deleted from the currently active database table.
void beforeInsert (QSqlRecord &record)
This signal is emitted by insertRowIntoTable() before a new row is inserted into the currently active database table.
void beforeUpdate (int row, QSqlRecord &record)
This signal is emitted by updateRowInTable() before the row is updated in the currently active database table with the values from record.
void primeInsert (int row, QSqlRecord &record)
This signal is emitted by insertRows(), when an insertion is initiated in the given row of the currently active database table.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSqlRelationalTableModel class provides an editable data model for a single database table, with foreign key support.
Attention
Module: QtSql
QSqlRelationalTableModel acts like QSqlTableModel, but allows columns to be set as foreign keys into other database tables.
The screenshot on the left shows a plain QSqlTableModel in a QTableView. Foreign keys (city and country) aren't resolved to human-readable values. The screenshot on the right shows a QSqlRelationalTableModel, with foreign keys resolved into human-readable text strings.
The following code snippet shows how the QSqlRelationalTableModel was set up:
    model->setTable("employee");
    model->setRelation(2, QSqlRelation("city", "id", "name"));
    model->setRelation(3, QSqlRelation("country", "id", "name"));
The setRelation() function calls establish a relationship between two tables. The first call specifies that column 2 in table employee is a foreign key that maps with field id of table city, and that the view should present the city's name field to the user. The second call does something similar with column 3.
If you use a read-write QSqlRelationalTableModel, you probably want to use QSqlRelationalDelegate on the view. Unlike the default delegate, QSqlRelationalDelegate provides a combobox for fields that are foreign keys into other tables. To use the class, simply call QAbstractItemView::setItemDelegate() on the view with an instance of QSqlRelationalDelegate:
    QTableView *view = new QTableView;
    view->setModel(model);
    view->setItemDelegate(new QSqlRelationalDelegate(view));
The sql/relationaltablemodel example illustrates how to use QSqlRelationalTableModel in conjunction with QSqlRelationalDelegate to provide tables with foreign key support.
Notes:
The table must have a primary key declared.
The table's primary key may not contain a relation to another table.
If a relational table contains keys that refer to non-existent rows in the referenced table, the rows containing the invalid keys will not be exposed through the model. The user or the database is responsible for keeping referential integrity.
If a relation's display column name is also used as a column name in the main table, or if it is used as display column name in more than one relation it will be aliased. The alias is is the relation's table name and display column name joined by an underscore (e.g. tablename_columnname). All occurrences of the duplicate display column name are aliased when duplication is detected, but no aliasing is done to the column names in the main table. The aliasing doesn't affect QSqlRelation, so QSqlRelation::displayColumn() will return the original display column name, but QSqlRecord::fieldName() will return aliases.
When using setData() the role should always be Qt::EditRole, and when using data() the role should always be Qt::DisplayRole.
See also
QSqlRelation, QSqlRelationalDelegate, {Relational Table Model Example}
Definition at line 74 of file qsqlrelationaltablemodel.h.
Enumerations
JoinMode
enum QSqlRelationalTableModel::JoinMode
This enum specifies the type of mode to use when joining two tables.
Since
4.8
InnerJoin Inner join mode, return rows when there is at least one match in both tables.
LeftJoin Left join mode, returns all rows from the left table (table_name1), even if there are no matches in the right table (table_name2).
See also
QSqlRelationalTableModel::setJoinMode()
Enumerator
InnerJoin
LeftJoin
Definition at line 79 of file qsqlrelationaltablemodel.h.
                   {
         InnerJoin,
         LeftJoin
     };
Constructors and Destructors
QSqlRelationalTableModel()
QSqlRelationalTableModel::QSqlRelationalTableModel (QObject * parent = 0, QSqlDatabase db = QSqlDatabase()) explicit
Creates an empty QSqlRelationalTableModel and sets the parent to parent and the database connection to db.
If db is not valid, the default database connection will be used.
Definition at line 438 of file qsqlrelationaltablemodel.cpp.
     : QSqlTableModel(*new QSqlRelationalTableModelPrivate, parent, db)
 {
 }
~QSqlRelationalTableModel()
QSqlRelationalTableModel::~QSqlRelationalTableModel () virtual
Destroys the object and frees any allocated resources.
Definition at line 446 of file qsqlrelationaltablemodel.cpp.
 {
 }
Functions
clear()
void QSqlRelationalTableModel::clear (void) virtual
Reimplemented Function
Reimplemented from QSqlQueryModel.
Definition at line 728 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     d->clearChanges();
     d->relations.clear();
     QSqlTableModel::clear();
 }
data()
QVariant QSqlRelationalTableModel::data (const QModelIndex & item, int role = Qt::DisplayRole) const virtual
Reimplemented Function
Reimplemented from QSqlQueryModel.
Definition at line 453 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(const QSqlRelationalTableModel);
     if (role == Qt::DisplayRole && index.column() >= 0 && index.column() < d->relations.count() &&
             d->relations.value(index.column()).isValid()) {
         QRelation &relation = d->relations[index.column()];
         if (!relation.isDictionaryInitialized())
             relation.populateDictionary();
         //only perform a dictionary lookup for the display value
         //when the value at index has been changed or added.
         //At an unmodified index, the underlying model will
         //already have the correct display value.
         QVariant v;
         switch (d->strategy) {
             case OnFieldChange:
                 break;
             case OnRowChange:
                 if ((index.row() == d->editIndex || index.row() == d->insertIndex)
                     && d->editBuffer.isGenerated(index.column()))
                     v = d->editBuffer.value(index.column());
                 break;
             case OnManualSubmit:
                 const QSqlTableModelPrivate::ModifiedRow row = d->cache.value(index.row());
                 if (row.op != QSqlTableModelPrivate::None && row.rec.isGenerated(index.column()))
                     v = row.rec.value(index.column());
                 break;
         }
         if (v.isValid())
             return relation.dictionary[v.toString()];
     }
     return QSqlTableModel::data(index, role);
 }
insertRowIntoTable()
bool QSqlRelationalTableModel::insertRowIntoTable (const QSqlRecord & values) protected virtual
Reimplemented Function
Reimplemented from QSqlTableModel.
Definition at line 828 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     QSqlRecord rec = values;
     d->translateFieldNames(0, rec);
     return QSqlTableModel::insertRowIntoTable(rec);
 }
orderByClause()
QString QSqlRelationalTableModel::orderByClause () const protected virtual
Reimplemented Function
Reimplemented from QSqlTableModel.
Definition at line 841 of file qsqlrelationaltablemodel.cpp.
Referenced by selectStatement().
 {
     Q_D(const QSqlRelationalTableModel);
     const QSqlRelation rel = d->relations.value(d->sortColumn).rel;
     if (!rel.isValid())
         return QSqlTableModel::orderByClause();
     QString s = QLatin1String("ORDER BY ");
     s.append(d->relationField(QLatin1String("relTblAl_") + QString::number(d->sortColumn),
                     rel.displayColumn()));
     s += d->sortOrder == Qt::AscendingOrder ? QLatin1String(" ASC") : QLatin1String(" DESC");
     return s;
 }
relation()
QSqlRelation QSqlRelationalTableModel::relation (int column) const
Returns the relation for the column column, or an invalid relation if no relation is set.
See also
setRelation(), QSqlRelation::isValid()
Definition at line 552 of file qsqlrelationaltablemodel.cpp.
Referenced by data(), relationModel(), selectStatement(), and setData().
 {
     Q_D(const QSqlRelationalTableModel);
     return d->relations.value(column).rel;
 }
relationModel()
QSqlTableModel * QSqlRelationalTableModel::relationModel (int column) const virtual
Returns a QSqlTableModel object for accessing the table for which column is a foreign key, or 0 if there is no relation for the given column.
The returned object is owned by the QSqlRelationalTableModel.
See also
setRelation(), relation()
Definition at line 702 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(const QSqlRelationalTableModel);
     if ( column < 0 || column >= d->relations.count())
         return 0;
     QRelation &relation = const_cast<QSqlRelationalTableModelPrivate *>(d)->relations[column];
     if (!relation.isValid())
         return 0;
     if (!relation.model)
         relation.populateModel();
     return relation.model;
 }
removeColumns()
bool QSqlRelationalTableModel::removeColumns (int column, int count, const QModelIndex & parent = QModelIndex()) virtual
Reimplemented Function
Reimplemented from QSqlQueryModel.
Definition at line 859 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     if (parent.isValid() || column < 0 || column + count > d->rec.count())
         return false;
     for (int i = 0; i < count; ++i) {
         d->baseRec.remove(column);
         if (d->relations.count() > column)
             d->relations.remove(column);
     }
     return QSqlTableModel::removeColumns(column, count, parent);
 }
revertRow
void QSqlRelationalTableModel::revertRow (int row) slot
Reimplemented Function
Definition at line 720 of file qsqlrelationaltablemodel.cpp.
 {
     QSqlTableModel::revertRow(row);
 }
select()
bool QSqlRelationalTableModel::select () virtual
Reimplemented Function
Reimplemented from QSqlTableModel.
Definition at line 776 of file qsqlrelationaltablemodel.cpp.
 {
     return QSqlTableModel::select();
 }
selectStatement()
QString QSqlRelationalTableModel::selectStatement () const protected virtual
Reimplemented Function
Reimplemented from QSqlTableModel.
Definition at line 571 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(const QSqlRelationalTableModel);
     QString query;
     if (tableName().isEmpty())
         return query;
     if (d->relations.isEmpty())
         return QSqlTableModel::selectStatement();
     QString tList;
     QString fList;
     QString where;
     QSqlRecord rec = d->baseRec;
     QStringList tables;
     const QRelation nullRelation;
     // Count how many times each field name occurs in the record
     QHash<QString, int> fieldNames;
     QStringList fieldList;
     for (int i = 0; i < rec.count(); ++i) {
         QSqlRelation relation = d->relations.value(i, nullRelation).rel;
         QString name;
         if (relation.isValid())
         {
             // Count the display column name, not the original foreign key
             name = relation.displayColumn();
             if (d->db.driver()->isIdentifierEscaped(name, QSqlDriver::FieldName))
                 name = d->db.driver()->stripDelimiters(name, QSqlDriver::FieldName);
             QSqlRecord rec = database().record(relation.tableName());
             for (int i = 0; i < rec.count(); ++i) {
                 if (name.compare(rec.fieldName(i), Qt::CaseInsensitive) == 0) {
                     name = rec.fieldName(i);
                     break;
                 }
             }
         }
         else
             name = rec.fieldName(i);
         fieldNames.insert(name, fieldNames.value(name, 0) + 1);
         fieldList.append(name);
     }
     for (int i = 0; i < rec.count(); ++i) {
         QSqlRelation relation = d->relations.value(i, nullRelation).rel;
         if (relation.isValid()) {
             QString relTableAlias = QString::fromLatin1("relTblAl_%1").arg(i);
             if (!fList.isEmpty())
                 fList.append(QLatin1String(", "));
             fList.append(d->relationField(relTableAlias,relation.displayColumn()));
             // If there are duplicate field names they must be aliased
             if (fieldNames.value(fieldList[i]) > 1) {
                 QString relTableName = relation.tableName().section(QChar::fromLatin1('.'), -1, -1);
                 if (d->db.driver()->isIdentifierEscaped(relTableName, QSqlDriver::TableName))
                     relTableName = d->db.driver()->stripDelimiters(relTableName, QSqlDriver::TableName);
                 QString displayColumn = relation.displayColumn();
                 if (d->db.driver()->isIdentifierEscaped(displayColumn, QSqlDriver::FieldName))
                     displayColumn = d->db.driver()->stripDelimiters(displayColumn, QSqlDriver::FieldName);
                 fList.append(QString::fromLatin1(" AS %1_%2_%3").arg(relTableName).arg(displayColumn).arg(fieldNames.value(fieldList[i])));
                 fieldNames.insert(fieldList[i], fieldNames.value(fieldList[i])-1);
             }
             if (d->joinMode == QSqlRelationalTableModel::InnerJoin) {
                 // this needs fixing!! the below if is borken.
                 // Use LeftJoin mode if you want correct behavior
                 tables.append(relation.tableName().append(QLatin1Char(' ')).append(relTableAlias));
                 if(!where.isEmpty())
                     where.append(QLatin1String(" AND "));
                 where.append(d->relationField(tableName(), d->db.driver()->escapeIdentifier(rec.fieldName(i), QSqlDriver::FieldName)));
                 where.append(QLatin1String(" = "));
                 where.append(d->relationField(relTableAlias, relation.indexColumn()));
             } else {
                 tables.append(QLatin1String(" LEFT JOIN"));
                 tables.append(relation.tableName().append(QLatin1Char(' ')).append(relTableAlias));
                 tables.append(QLatin1String("ON"));
                 QString clause;
                 clause.append(d->relationField(tableName(), d->db.driver()->escapeIdentifier(rec.fieldName(i), QSqlDriver::FieldName)));
                 clause.append(QLatin1String(" = "));
                 clause.append(d->relationField(relTableAlias, relation.indexColumn()));
                 tables.append(clause);
             }
         } else {
             if (!fList.isEmpty())
                 fList.append(QLatin1String(", "));
             fList.append(d->relationField(tableName(), d->db.driver()->escapeIdentifier(rec.fieldName(i), QSqlDriver::FieldName)));
         }
     }
     if (d->joinMode == QSqlRelationalTableModel::InnerJoin && !tables.isEmpty()) {
         tList.append(tables.join(QLatin1String(", ")));
         if(!tList.isEmpty())
             tList.prepend(QLatin1String(", "));
     } else
         tList.append(tables.join(QLatin1String(" ")));
     if (fList.isEmpty())
         return query;
     tList.prepend(tableName());
     query.append(QLatin1String("SELECT "));
     query.append(fList).append(QLatin1String(" FROM ")).append(tList);
     if (d->joinMode == QSqlRelationalTableModel::InnerJoin) {
         qAppendWhereClause(query, where, filter());
     } else if (!filter().isEmpty()) {
         query.append(QLatin1String(" WHERE ("));
         query.append(filter());
         query.append(QLatin1String(")"));
     }
     QString orderBy = orderByClause();
     if (!orderBy.isEmpty())
         query.append(QLatin1Char(' ')).append(orderBy);
     return query;
 }
setData()
bool QSqlRelationalTableModel::setData (const QModelIndex & index, const QVariant & value, int role = Qt::EditRole) virtual
Sets the data for the role in the item with the specified index to the value given.
Depending on the edit strategy, the value might be applied to the database at once, or it may be cached in the model.
Returns true if the value could be set, or false on error (for example, if index is out of bounds).
For relational columns, value must be the index, not the display value. The index must also exist in the referenced table, otherwise the function returns false.
See also
editStrategy(), data(), submit(), revertRow()
Reimplemented from QAbstractItemModel.
Definition at line 503 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     if ( role == Qt::EditRole && index.column() > 0 && index.column() < d->relations.count()
             && d->relations.value(index.column()).isValid()) {
         QRelation &relation = d->relations[index.column()];
         if (!relation.isDictionaryInitialized())
             relation.populateDictionary();
         if (!relation.dictionary.contains(value.toString()))
             return false;
     }
     return QSqlTableModel::setData(index, value, role);
 }
setJoinMode()
void QSqlRelationalTableModel::setJoinMode (QSqlRelationalTableModel::JoinMode joinMode)
Sets the SQL join mode to the value given by joinMode to show or hide rows with NULL foreign keys.
Since
4.8
In InnerJoin mode (the default) these rows will not be shown; use the LeftJoin mode if you want to show them.
See also
QSqlRelationalTableModel::JoinMode
Definition at line 768 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     d->joinMode = joinMode;
 }
setRelation()
void QSqlRelationalTableModel::setRelation (int column, const QSqlRelation & relation) virtual
Lets the specified column be a foreign index specified by relation.
Example:
    model->setTable("employee");
    model->setRelation(2, QSqlRelation("city", "id", "name"));
The setRelation() call specifies that column 2 in table employee is a foreign key that maps with field id of table city, and that the view should present the city's name field to the user.
Note: The table's primary key may not contain a relation to another table.
See also
relation()
Definition at line 536 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     if (column < 0)
         return;
     if (d->relations.size() <= column)
         d->relations.resize(column + 1);
     d->relations[column].init(this, relation);
 }
setTable()
void QSqlRelationalTableModel::setTable (const QString & tableName) virtual
Reimplemented Function
Reimplemented from QSqlTableModel.
Definition at line 784 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     // memorize the table before applying the relations
     d->baseRec = d->db.record(table);
     QSqlTableModel::setTable(table);
 }
updateRowInTable()
bool QSqlRelationalTableModel::updateRowInTable (int row, const QSqlRecord & values) protected virtual
Reimplemented Function
Reimplemented from QSqlTableModel.
Definition at line 815 of file qsqlrelationaltablemodel.cpp.
 {
     Q_D(QSqlRelationalTableModel);
     QSqlRecord rec = values;
     d->translateFieldNames(row, rec);
     return QSqlTableModel::updateRowInTable(row, rec);
 }
The documentation for this class was generated from the following files:
/src/sql/models/qsqlrelationaltablemodel.h
/src/sql/models/qsqlrelationaltablemodel.cpp