Qt 4.8: QPixmapFilter Class Reference
QPixmapFilter Class Reference abstract
The QPixmapFilter class provides the basic functionality for pixmap filter classes.
#include <qpixmapfilter_p.h>
Public Types
enum FilterType {
ConvolutionFilter, ColorizeFilter, DropShadowFilter, BlurFilter,
UserFilter = 1024
}
This enum describes the types of filter that can be applied to pixmaps.
Public Functions
virtual QRectF boundingRectFor (const QRectF &rect) const
Returns the bounding rectangle that is affected by the pixmap filter if the filter is applied to the specified rect.
virtual void draw (QPainter *painter, const QPointF &p, const QPixmap &src, const QRectF &srcRect=QRectF()) const =0
Uses painter to draw filtered result of src at the point specified by p.
FilterType type () const
Returns the type of the filter.
virtual ~QPixmapFilter ()=0
Destroys the pixmap filter.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
QPixmapFilter (QPixmapFilterPrivate &d, FilterType type, QObject *parent)
QPixmapFilter (FilterType type, QObject *parent)
Constructs a default QPixmapFilter with the given type.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QPixmapFilter class provides the basic functionality for pixmap filter classes.
Pixmap filter can be for example colorize or blur.
Since
4.5
QPixmapFilter is the base class for every pixmap filter. QPixmapFilter is an abstract class and cannot itself be instantiated. It provides a standard interface for filter processing.
Warning
This function is not part of the public interface.
Definition at line 72 of file qpixmapfilter_p.h.
Enumerations
FilterType
enum QPixmapFilter::FilterType
This enum describes the types of filter that can be applied to pixmaps.
Warning
This function is not part of the public interface.
ConvolutionFilter A filter that is used to calculate the convolution of the image with a kernel. See QPixmapConvolutionFilter for more information.
ColorizeFilter A filter that is used to change the overall color of an image. See QPixmapColorizeFilter for more information.
DropShadowFilter A filter that is used to add a drop shadow to an image. See QPixmapDropShadowFilter for more information.
BlurFilter A filter that is used to blur an image using a simple blur radius. See QPixmapBlurFilter for more information.
UserFilter The first filter type that can be used for application-specific purposes.
Enumerator
ConvolutionFilter
ColorizeFilter
DropShadowFilter
BlurFilter
UserFilter
Definition at line 79 of file qpixmapfilter_p.h.
                     {
         ConvolutionFilter,
         ColorizeFilter,
         DropShadowFilter,
         BlurFilter,
         UserFilter = 1024
     };
Constructors and Destructors
~QPixmapFilter()
QPixmapFilter::~QPixmapFilter () pure virtual
Destroys the pixmap filter.
Warning
This function is not part of the public interface.
Definition at line 147 of file qpixmapfilter.cpp.
 {
 }
QPixmapFilter() [1/2]
QPixmapFilter::QPixmapFilter (QPixmapFilterPrivate & d, QPixmapFilter::FilterType type, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 135 of file qpixmapfilter.cpp.
     : QObject(d, parent)
 {
     d_func()->type = type;
 }
QPixmapFilter() [2/2]
QPixmapFilter::QPixmapFilter (FilterType type, QObject * parent) protected
Constructs a default QPixmapFilter with the given type.
This constructor should be used when subclassing QPixmapFilter to create custom user filters.
Warning
This function is not part of the public interface.
Definition at line 124 of file qpixmapfilter.cpp.
     : QObject(*new QPixmapFilterPrivate, parent)
 {
     d_func()->type = type;
 }
Functions
boundingRectFor()
QRectF QPixmapFilter::boundingRectFor (const QRectF & rect) const virtual
Returns the bounding rectangle that is affected by the pixmap filter if the filter is applied to the specified rect.
Warning
This function is not part of the public interface.
Reimplemented in QPixmapDropShadowFilter, QPixmapBlurFilter, and QPixmapConvolutionFilter.
Definition at line 169 of file qpixmapfilter.cpp.
 {
     return rect;
 }
draw()
void QPixmapFilter::draw (QPainter * painter, const QPointF & p, const QPixmap & src, const QRectF & srcRect = QRectF()) const pure virtual
Uses painter to draw filtered result of src at the point specified by p.
If srcRect is specified the it will be used as a source rectangle to only draw a part of the source.
draw() will affect the area which boundingRectFor() returns.
Warning
This function is not part of the public interface.
Implemented in QPixmapDropShadowFilter, QPixmapColorizeFilter, QPixmapBlurFilter, QPixmapConvolutionFilter, QVGPixmapBlurFilter, QVGPixmapDropShadowFilter, QGLPixmapFilter< QPixmapDropShadowFilter >, QGLPixmapFilter< QPixmapConvolutionFilter >, QGLPixmapFilter< QPixmapColorizeFilter >, QGLPixmapFilter< QPixmapBlurFilter >, QVGPixmapColorizeFilter, and QVGPixmapConvolutionFilter.
type()
QPixmapFilter::FilterType QPixmapFilter::type () const
Returns the type of the filter.
All standard pixmap filter classes are associated with a unique value.
Warning
This function is not part of the public interface.
Definition at line 157 of file qpixmapfilter.cpp.
Referenced by QPixmapConvolutionFilter::draw(), QPixmapBlurFilter::draw(), QPixmapColorizeFilter::draw(), QPixmapDropShadowFilter::draw(), and QPixmapFilter().
 {
     Q_D(const QPixmapFilter);
     return d->type;
 }
The documentation for this class was generated from the following files:
/src/gui/image/qpixmapfilter_p.h
/src/gui/image/qpixmapfilter.cpp