Qt 4.8: QDeclarativeView Class Reference
QDeclarativeView Class Reference
The QDeclarativeView class provides a widget for displaying a Qt Declarative user interface.
#include <qdeclarativeview.h>
Public Types
enum ResizeMode { SizeViewToRootObject, SizeRootObjectToView }
This enum specifies how to resize the view.
enum Status { Null, Ready, Loading, Error }
Specifies the loading status of the QDeclarativeView.
Public Types inherited from QGraphicsView
enum CacheModeFlag { CacheNone = 0x0, CacheBackground = 0x1 }
This enum describes the flags that you can set for a QGraphicsView's cache mode.
enum DragMode { NoDrag, ScrollHandDrag, RubberBandDrag }
This enum describes the default action for the view when pressing and dragging the mouse over the viewport.
enum OptimizationFlag { DontClipPainter = 0x1, DontSavePainterState = 0x2, DontAdjustForAntialiasing = 0x4, IndirectPainting = 0x8 }
This enum describes flags that you can enable to improve rendering performance in QGraphicsView.
enum ViewportAnchor { NoAnchor, AnchorViewCenter, AnchorUnderMouse }
This enums describe the possible anchors that QGraphicsView can use when the user resizes the view or when the view is transformed.
enum ViewportUpdateMode {
FullViewportUpdate, MinimalViewportUpdate, SmartViewportUpdate, NoViewportUpdate,
BoundingRectViewportUpdate
}
This enum describes how QGraphicsView updates its viewport when the scene contents change or are exposed.
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Signals
void sceneResized (QSize size)
This signal is emitted when the view is resized to size.
void statusChanged (QDeclarativeView::Status)
This signal is emitted when the component's current status changes.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDeclarativeEngine * engine () const
Returns a pointer to the QDeclarativeEngine used for instantiating QML Components.
QList< QDeclarativeError > errors () const
Return the list of errors that occurred during the last compile or create operation.
QSize initialSize () const
Returns the initial size of the root object.
QDeclarativeView (QWidget *parent=0)
Constructs a QDeclarativeView with the given parent.
QDeclarativeView (const QUrl &source, QWidget *parent=0)
Constructs a QDeclarativeView with the given QML source and parent.
ResizeMode resizeMode () const
QDeclarativeContext * rootContext () const
This function returns the root of the context hierarchy.
QGraphicsObject * rootObject () const
Returns the view's root QGraphicsObject {item}.
void setResizeMode (ResizeMode)
void setSource (const QUrl &)
Sets the source to the url, loads the QML component and instantiates it.
QSize sizeHint () const
Preferred size follows the root object geometry.
QUrl source () const
Status status () const
virtual ~QDeclarativeView ()
Destroys the view.
Public Functions inherited from QGraphicsView
Qt::Alignment alignment () const
QBrush backgroundBrush () const
CacheMode cacheMode () const
void centerOn (const QPointF &pos)
Scrolls the contents of the viewport to ensure that the scene coordinate pos, is centered in the view.
void centerOn (qreal x, qreal y)
This function is provided for convenience.
void centerOn (const QGraphicsItem *item)
Scrolls the contents of the viewport to ensure that item is centered in the view.
DragMode dragMode () const
void ensureVisible (const QRectF &rect, int xmargin=50, int ymargin=50)
Scrolls the contents of the viewport so that the scene rectangle rect is visible, with margins specified in pixels by xmargin and ymargin.
void ensureVisible (qreal x, qreal y, qreal w, qreal h, int xmargin=50, int ymargin=50)
This function is provided for convenience.
void ensureVisible (const QGraphicsItem *item, int xmargin=50, int ymargin=50)
Scrolls the contents of the viewport so that the center of item item is visible, with margins specified in pixels by xmargin and ymargin.
void fitInView (const QRectF &rect, Qt::AspectRatioMode aspectRadioMode=Qt::IgnoreAspectRatio)
Scales the view matrix and scrolls the scroll bars to ensure that the scene rectangle rect fits inside the viewport.
void fitInView (qreal x, qreal y, qreal w, qreal h, Qt::AspectRatioMode aspectRadioMode=Qt::IgnoreAspectRatio)
void fitInView (const QGraphicsItem *item, Qt::AspectRatioMode aspectRadioMode=Qt::IgnoreAspectRatio)
Ensures that item fits tightly inside the view, scaling the view according to aspectRatioMode.
QBrush foregroundBrush () const
QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
bool isInteractive () const
bool isTransformed () const
Returns true if the view is transformed (i.
QGraphicsItem * itemAt (const QPoint &pos) const
Returns the item at position pos, which is in viewport coordinates.
QGraphicsItem * itemAt (int x, int y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This function is provided for convenience.
QList< QGraphicsItem * > items () const
Returns a list of all the items in the associated scene, in descending stacking order (i.e., the first item in the returned list is the uppermost item).
QList< QGraphicsItem * > items (const QPoint &pos) const
Returns a list of all the items at the position pos in the view.
QList< QGraphicsItem * > items (int x, int y) const
This function is provided for convenience.
QList< QGraphicsItem * > items (const QRect &rect, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with rect.
QList< QGraphicsItem * > items (int x, int y, int w, int h, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
QList< QGraphicsItem * > items (const QPolygon &polygon, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with polygon.
QList< QGraphicsItem * > items (const QPainterPath &path, Qt::ItemSelectionMode mode=Qt::IntersectsItemShape) const
Returns a list of all the items that, depending on mode, are either contained by or intersect with path.
QPoint mapFromScene (const QPointF &point) const
Returns the scene coordinate point to viewport coordinates.
QPolygon mapFromScene (const QRectF &rect) const
Returns the scene rectangle rect to a viewport coordinate polygon.
QPolygon mapFromScene (const QPolygonF &polygon) const
Returns the scene coordinate polygon polygon to a viewport coordinate polygon.
QPainterPath mapFromScene (const QPainterPath &path) const
Returns the scene coordinate painter path path to a viewport coordinate painter path.
QPoint mapFromScene (qreal x, qreal y) const
This function is provided for convenience.
QPolygon mapFromScene (qreal x, qreal y, qreal w, qreal h) const
This function is provided for convenience.
QPointF mapToScene (const QPoint &point) const
Returns the viewport coordinate point mapped to scene coordinates.
QPolygonF mapToScene (const QRect &rect) const
Returns the viewport rectangle rect mapped to a scene coordinate polygon.
QPolygonF mapToScene (const QPolygon &polygon) const
Returns the viewport polygon polygon mapped to a scene coordinate polygon.
QPainterPath mapToScene (const QPainterPath &path) const
Returns the viewport painter path path mapped to a scene coordinate painter path.
QPointF mapToScene (int x, int y) const
This function is provided for convenience.
QPolygonF mapToScene (int x, int y, int w, int h) const
This function is provided for convenience.
QMatrix matrix () const
Returns the current transformation matrix for the view.
OptimizationFlags optimizationFlags () const
QGraphicsView (QWidget *parent=0)
Constructs a QGraphicsView.
QGraphicsView (QGraphicsScene *scene, QWidget *parent=0)
Constructs a QGraphicsView and sets the visualized scene to scene.
void render (QPainter *painter, const QRectF &target=QRectF(), const QRect &source=QRect(), Qt::AspectRatioMode aspectRatioMode=Qt::KeepAspectRatio)
Renders the source rect, which is in view coordinates, from the scene into target, which is in paint device coordinates, using painter.
QPainter::RenderHints renderHints () const
void resetCachedContent ()
Resets any cached content.
void resetMatrix ()
Resets the view transformation matrix to the identity matrix.
void resetTransform ()
Resets the view transformation to the identity matrix.
ViewportAnchor resizeAnchor () const
void rotate (qreal angle)
Rotates the current view transformation angle degrees clockwise.
Qt::ItemSelectionMode rubberBandSelectionMode () const
void scale (qreal sx, qreal sy)
Scales the current view transformation by (sx, sy).
QGraphicsScene * scene () const
Returns a pointer to the scene that is currently visualized in the view.
QRectF sceneRect () const
void setAlignment (Qt::Alignment alignment)
void setBackgroundBrush (const QBrush &brush)
void setCacheMode (CacheMode mode)
void setDragMode (DragMode mode)
void setForegroundBrush (const QBrush &brush)
void setInteractive (bool allowed)
void setMatrix (const QMatrix &matrix, bool combine=false)
Sets the view's current transformation matrix to matrix.
void setOptimizationFlag (OptimizationFlag flag, bool enabled=true)
Enables flag if enabled is true; otherwise disables flag.
void setOptimizationFlags (OptimizationFlags flags)
void setRenderHint (QPainter::RenderHint hint, bool enabled=true)
If enabled is true, the render hint hint is enabled; otherwise it is disabled.
void setRenderHints (QPainter::RenderHints hints)
void setResizeAnchor (ViewportAnchor anchor)
void setRubberBandSelectionMode (Qt::ItemSelectionMode mode)
void setScene (QGraphicsScene *scene)
Sets the current scene to scene.
void setSceneRect (const QRectF &rect)
void setSceneRect (qreal x, qreal y, qreal w, qreal h)
void setTransform (const QTransform &matrix, bool combine=false)
Sets the view's current transformation matrix to matrix.
void setTransformationAnchor (ViewportAnchor anchor)
void setViewportUpdateMode (ViewportUpdateMode mode)
void shear (qreal sh, qreal sv)
Shears the current view transformation by (sh, sv).
QSize sizeHint () const
Reimplemented Function
QTransform transform () const
Returns the current transformation matrix for the view.
ViewportAnchor transformationAnchor () const
void translate (qreal dx, qreal dy)
Translates the current view transformation by (dx, dy).
QTransform viewportTransform () const
Returns a matrix that maps viewport coordinates to scene coordinates.
ViewportUpdateMode viewportUpdateMode () const
~QGraphicsView ()
Destructs the QGraphicsView object.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
virtual bool eventFilter (QObject *watched, QEvent *e)
virtual void paintEvent (QPaintEvent *event)
virtual void resizeEvent (QResizeEvent *)
This function handles the QResizeEvent {resize event} e.
virtual void setRootObject (QObject *obj)
virtual void timerEvent (QTimerEvent *)
If the QTimerEvent {timer event} e is this view's resize timer, sceneResized() is emitted.
Protected Functions inherited from QGraphicsView
void contextMenuEvent (QContextMenuEvent *event)
Reimplemented Function
void dragEnterEvent (QDragEnterEvent *event)
Reimplemented Function
void dragLeaveEvent (QDragLeaveEvent *event)
Reimplemented Function
void dragMoveEvent (QDragMoveEvent *event)
Reimplemented Function
virtual void drawBackground (QPainter *painter, const QRectF &rect)
Draws the background of the scene using painter, before any items and the foreground are drawn.
virtual void drawForeground (QPainter *painter, const QRectF &rect)
Draws the foreground of the scene using painter, after the background and all items are drawn.
virtual void drawItems (QPainter *painter, int numItems, QGraphicsItem *items[], const QStyleOptionGraphicsItem options[])
Draws the items items in the scene using painter, after the background and before the foreground are drawn.
void dropEvent (QDropEvent *event)
Reimplemented Function
bool event (QEvent *event)
Reimplemented Function
void focusInEvent (QFocusEvent *event)
Reimplemented Function
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
Reimplemented Function
void keyReleaseEvent (QKeyEvent *event)
Reimplemented Function
void mouseDoubleClickEvent (QMouseEvent *event)
Reimplemented Function
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
void paintEvent (QPaintEvent *event)
Reimplemented Function
QGraphicsView (QGraphicsViewPrivate &, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void scrollContentsBy (int dx, int dy)
Reimplemented Function
void showEvent (QShowEvent *event)
Reimplemented Function
bool viewportEvent (QEvent *event)
Reimplemented Function
void wheelEvent (QWheelEvent *event)
Reimplemented Function
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Slots
void continueExecute ()
Properties
ResizeMode resizeMode
whether the view should resize the canvas contents
QUrl source
The URL of the source of the QML component.
Status status
The component's current status.
Additional Inherited Members
Public Slots inherited from QGraphicsView
void invalidateScene (const QRectF &rect=QRectF(), QGraphicsScene::SceneLayers layers=QGraphicsScene::AllLayers)
Invalidates and schedules a redraw of layers inside rect.
void updateScene (const QList< QRectF > &rects)
Schedules an update of the scene rectangles rects.
void updateSceneRect (const QRectF &rect)
Notifies QGraphicsView that the scene's scene rect has changed.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QGraphicsView
void setupViewport (QWidget *widget)
This slot is called by QAbstractScrollArea after setViewport() has been called.
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QDeclarativeView class provides a widget for displaying a Qt Declarative user interface.
Since
4.7
QDeclarativeItem objects can be placed on a standard QGraphicsScene and displayed with QGraphicsView. QDeclarativeView is a QGraphicsView subclass provided as a convenience for displaying QML files, and connecting between QML and C++ Qt objects.
QDeclarativeView provides:
Management of QDeclarativeComponent loading and object creation
Initialization of QGraphicsView for optimal performance with QML using these settings:
QGraphicsView::setOptimizationFlags(QGraphicsView::DontSavePainterState)
QGraphicsView::setViewportUpdateMode(QGraphicsView::BoundingRectViewportUpdate)
QGraphicsScene::setItemIndexMethod(QGraphicsScene::NoIndex)
Initialization of QGraphicsView for QML key handling using these settings:
QGraphicsView::viewport()->setFocusPolicy(Qt::NoFocus)
QGraphicsView::setFocusPolicy(Qt::StrongFocus)
QGraphicsScene::setStickyFocus(true)
Typical usage:
QDeclarativeView *view = new QDeclarativeView;
view->setSource(QUrl::fromLocalFile("myqmlfile.qml"));
view->show();
Since QDeclarativeView is a QWidget-based class, it can be used to display QML interfaces within QWidget-based GUI applications that do not use the Graphics View framework.
To receive errors related to loading and executing QML with QDeclarativeView, you can connect to the statusChanged() signal and monitor for QDeclarativeView::Error. The errors are available via QDeclarativeView::errors().
If you're using your own QGraphicsScene-based scene with QDeclarativeView, remember to enable scene's sticky focus mode and to set itemIndexMethod to QGraphicsScene::NoIndex.
See also
{Integrating QML Code with Existing Qt UI Code}, {Using QML Bindings in C++ Applications}
Definition at line 64 of file qdeclarativeview.h.
Enumerations
ResizeMode
enum QDeclarativeView::ResizeMode
This enum specifies how to resize the view.
SizeViewToRootObject The view resizes with the root item in the QML.
SizeRootObjectToView The view will automatically resize the root item to the size of the view.
Enumerator
SizeViewToRootObject
SizeRootObjectToView
Definition at line 84 of file qdeclarativeview.h.
 { SizeViewToRootObject, SizeRootObjectToView };
Status
enum QDeclarativeView::Status
Specifies the loading status of the QDeclarativeView.
Null This QDeclarativeView has no source set.
Ready This QDeclarativeView has loaded and created the QML component.
Loading This QDeclarativeView is loading network data.
Error One or more errors has occurred. Call errors() to retrieve a list of errors.
Enumerator
Null
Ready
Loading
Error
Definition at line 88 of file qdeclarativeview.h.
 { Null, Ready, Loading, Error };
Constructors and Destructors
QDeclarativeView() [1/2]
QDeclarativeView::QDeclarativeView (QWidget * parent = 0) explicit
Constructs a QDeclarativeView with the given parent.
Definition at line 265 of file qdeclarativeview.cpp.
     : QGraphicsView(*(new QDeclarativeViewPrivate), parent)
 {
     Q_D(QDeclarativeView);
     setSizePolicy(QSizePolicy::Preferred,QSizePolicy::Preferred);
     d->init();
 }
QDeclarativeView() [2/2]
QDeclarativeView::QDeclarativeView (const QUrl & source, QWidget * parent = 0)
Constructs a QDeclarativeView with the given QML source and parent.
Definition at line 278 of file qdeclarativeview.cpp.
     : QGraphicsView(*(new QDeclarativeViewPrivate), parent)
 {
     Q_D(QDeclarativeView);
     setSizePolicy(QSizePolicy::Preferred,QSizePolicy::Preferred);
     d->init();
     setSource(source);
 }
~QDeclarativeView()
QDeclarativeView::~QDeclarativeView () virtual
Destroys the view.
Definition at line 319 of file qdeclarativeview.cpp.
 {
     QDeclarativeInspectorService::instance()->removeView(this);
 }
Functions
continueExecute
void QDeclarativeView::continueExecute () private slot
Warning
This function is not part of the public interface.
Definition at line 562 of file qdeclarativeview.cpp.
 {
     Q_D(QDeclarativeView);
     disconnect(d->component, SIGNAL(statusChanged(QDeclarativeComponent::Status)), this, SLOT(continueExecute()));
     if (d->component->isError()) {
         QList<QDeclarativeError> errorList = d->component->errors();
         foreach (const QDeclarativeError &error, errorList) {
             qWarning() << error;
         }
         emit statusChanged(status());
         return;
     }
     QObject *obj = d->component->create();
     if(d->component->isError()) {
         QList<QDeclarativeError> errorList = d->component->errors();
         foreach (const QDeclarativeError &error, errorList) {
             qWarning() << error;
         }
         emit statusChanged(status());
         return;
     }
     setRootObject(obj);
     emit statusChanged(status());
 }
engine()
QDeclarativeEngine * QDeclarativeView::engine () const
Returns a pointer to the QDeclarativeEngine used for instantiating QML Components.
Definition at line 369 of file qdeclarativeview.cpp.
Referenced by QmlApplicationViewer::addImportPath(), QDeclarativeViewPrivate::init(), main(), and QmlApplicationViewer::QmlApplicationViewer().
 {
     Q_D(const QDeclarativeView);
     return d->engine;
 }
errors()
QList< QDeclarativeError > QDeclarativeView::errors () const
Return the list of errors that occurred during the last compile or create operation.
When the status is not Error, an empty list is returned.
Definition at line 434 of file qdeclarativeview.cpp.
 {
     Q_D(const QDeclarativeView);
     if (d->component)
         return d->component->errors();
     return QList<QDeclarativeError>();
 }
eventFilter()
bool QDeclarativeView::eventFilter (QObject * watched, QEvent * e) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Definition at line 659 of file qdeclarativeview.cpp.
 {
     Q_D(QDeclarativeView);
     if (watched == d->root && d->resizeMode == SizeViewToRootObject) {
         if (d->graphicsWidgetRoot) {
             if (e->type() == QEvent::GraphicsSceneResize) {
                 d->updateSize();
             }
         }
     }
     return QGraphicsView::eventFilter(watched, e);
 }
initialSize()
QSize QDeclarativeView::initialSize () const
Returns the initial size of the root object.
Definition at line 693 of file qdeclarativeview.cpp.
 {
     Q_D(const QDeclarativeView);
     return d->initialSize;
 }
paintEvent()
void QDeclarativeView::paintEvent (QPaintEvent * event) protected virtual
Warning
This function is not part of the public interface.
Reimplemented from QWidget.
Definition at line 736 of file qdeclarativeview.cpp.
 {
     Q_D(QDeclarativeView);
     QDeclarativeDebugTrace::addEvent(QDeclarativeDebugTrace::FramePaint);
     QDeclarativeDebugTrace::startRange(QDeclarativeDebugTrace::Painting);
     int time = 0;
     if (frameRateDebug())
         time = d->frameTimer.restart();
     QGraphicsView::paintEvent(event);
     QDeclarativeDebugTrace::endRange(QDeclarativeDebugTrace::Painting);
     if (frameRateDebug())
         qDebug() << "paintEvent:" << d->frameTimer.elapsed() << "time since last frame:" << time;
 #if QT_SHOW_DECLARATIVEVIEW_FPS
     static QTime timer;
     static int frames;
     if (frames == 0) {
         timer.start();
     } else if (timer.elapsed() > 5000) {
         qreal avgtime = timer.elapsed() / (qreal) frames;
         qDebug("Average time per frame: %f ms (%i fps)", avgtime, int(1000 / avgtime));
         timer.start();
         frames = 0;
     }
     ++frames;
     scene()->update();
 #endif
 }
resizeEvent()
void QDeclarativeView::resizeEvent (QResizeEvent * e) protected virtual
This function handles the QResizeEvent {resize event} e.
Warning
This function is not part of the public interface.
Reimplemented from QWidget.
Definition at line 716 of file qdeclarativeview.cpp.
 {
     Q_D(QDeclarativeView);
     if (d->resizeMode == SizeRootObjectToView) {
         d->updateSize();
     }
     if (d->declarativeItemRoot) {
         setSceneRect(QRectF(0, 0, d->declarativeItemRoot->width(), d->declarativeItemRoot->height()));
     } else if (d->root) {
         setSceneRect(d->root->boundingRect());
     } else {
         setSceneRect(rect());
     }
     emit sceneResized(e->size());
     QGraphicsView::resizeEvent(e);
 }
resizeMode()
ResizeMode QDeclarativeView::resizeMode () const
Referenced by QDeclarativeViewPrivate::initResize(), QDeclarativeViewPrivate::rootObjectSize(), and QDeclarativeViewPrivate::updateSize().
rootContext()
QDeclarativeContext * QDeclarativeView::rootContext () const
This function returns the root of the context hierarchy.
Each QML component is instantiated in a QDeclarativeContext. QDeclarativeContext's are essential for passing data to QML components. In QML, contexts are arranged hierarchically and this hierarchy is managed by the QDeclarativeEngine.
Definition at line 382 of file qdeclarativeview.cpp.
 {
     Q_D(const QDeclarativeView);
     return d->engine->rootContext();
 }
rootObject()
QGraphicsObject * QDeclarativeView::rootObject () const
Returns the view's root QGraphicsObject {item}.
Definition at line 702 of file qdeclarativeview.cpp.
 {
     Q_D(const QDeclarativeView);
     return d->root;
 }
sceneResized
void QDeclarativeView::sceneResized (QSize size) signal
This signal is emitted when the view is resized to size.
Referenced by resizeEvent().
setResizeMode()
void QDeclarativeView::setResizeMode (ResizeMode mode)
Definition at line 460 of file qdeclarativeview.cpp.
Referenced by QmlApplicationViewer::QmlApplicationViewer().
 {
     Q_D(QDeclarativeView);
     if (d->resizeMode == mode)
         return;
     if (d->declarativeItemRoot) {
         if (d->resizeMode == SizeViewToRootObject) {
             QDeclarativeItemPrivate *p =
                 static_cast<QDeclarativeItemPrivate *>(QGraphicsItemPrivate::get(d->declarativeItemRoot));
             p->removeItemChangeListener(d, QDeclarativeItemPrivate::Geometry);
         }
     } else if (d->graphicsWidgetRoot) {
          if (d->resizeMode == QDeclarativeView::SizeViewToRootObject) {
              d->graphicsWidgetRoot->removeEventFilter(this);
          }
     }
     d->resizeMode = mode;
     if (d->root) {
         d->initResize();
     }
 }
setRootObject()
void QDeclarativeView::setRootObject (QObject * obj) protected virtual
Warning
This function is not part of the public interface.
Definition at line 594 of file qdeclarativeview.cpp.
Referenced by continueExecute().
 {
     Q_D(QDeclarativeView);
     if (d->root == obj || !scene())
         return;
     if (QDeclarativeItem *declarativeItem = qobject_cast<QDeclarativeItem *>(obj)) {
         scene()->addItem(declarativeItem);
         d->root = declarativeItem;
         d->declarativeItemRoot = declarativeItem;
     } else if (QGraphicsObject *graphicsObject = qobject_cast<QGraphicsObject *>(obj)) {
         scene()->addItem(graphicsObject);
         d->root = graphicsObject;
         if (graphicsObject->isWidget()) {
             d->graphicsWidgetRoot = static_cast<QGraphicsWidget*>(graphicsObject);
         } else {
             qWarning() << "QDeclarativeView::resizeMode is not honored for components of type QGraphicsObject";
         }
     } else if (obj) {
         qWarning() << "QDeclarativeView only supports loading of root objects that derive from QGraphicsObject";
         if (QWidget* widget  = qobject_cast<QWidget *>(obj)) {
             window()->setAttribute(Qt::WA_OpaquePaintEvent, false);
             window()->setAttribute(Qt::WA_NoSystemBackground, false);
             if (layout() && layout()->count()) {
                 // Hide the QGraphicsView in GV mode.
                 QLayoutItem *item = layout()->itemAt(0);
                 if (item->widget())
                     item->widget()->hide();
             }
             widget->setParent(this);
             if (isVisible()) {
                 widget->setVisible(true);
             }
             resize(widget->size());
         }
     }
     if (d->root) {
         d->initialSize = d->rootObjectSize();
         if (d->initialSize != size()) {
             if (!(parentWidget() && parentWidget()->layout())) {
                 resize(d->initialSize);
             }
         }
         d->initResize();
     }
 }
setSource()
void QDeclarativeView::setSource (const QUrl & url)
Sets the source to the url, loads the QML component and instantiates it.
Ensure that the URL provided is full and correct, in particular, use QUrl::fromLocalFile() when loading a file from the local filesystem.
Calling this methods multiple times with the same url will result in the QML being reloaded.
Definition at line 347 of file qdeclarativeview.cpp.
Referenced by QDeclarativeView(), and QmlApplicationViewer::setMainQmlFile().
 {
     Q_D(QDeclarativeView);
     d->source = url;
     d->execute();
 }
sizeHint()
QSize QDeclarativeView::sizeHint () const virtual
Preferred size follows the root object geometry.
Warning
This function is not part of the public interface.
Reimplemented from QWidget.
Definition at line 679 of file qdeclarativeview.cpp.
 {
     Q_D(const QDeclarativeView);
     QSize rootObjectSize = d->rootObjectSize();
     if (rootObjectSize.isEmpty()) {
         return size();
     } else {
         return rootObjectSize;
     }
 }
source()
QUrl QDeclarativeView::source () const
Referenced by setSource().
status()
Status QDeclarativeView::status () const
Referenced by continueExecute(), and rootContext().
statusChanged
void QDeclarativeView::statusChanged (QDeclarativeView::Status status) signal
This signal is emitted when the component's current status changes.
Referenced by continueExecute().
timerEvent()
void QDeclarativeView::timerEvent (QTimerEvent * e) protected virtual
If the QTimerEvent {timer event} e is this view's resize timer, sceneResized() is emitted.
Warning
This function is not part of the public interface.
Reimplemented from QObject.
Definition at line 649 of file qdeclarativeview.cpp.
 {
     Q_D(QDeclarativeView);
     if (!e || e->timerId() == d->resizetimer.timerId()) {
         d->updateSize();
         d->resizetimer.stop();
     }
 }
Properties
resizeMode
QDeclarativeView::ResizeMode QDeclarativeView::resizeMode private
whether the view should resize the canvas contents
If this property is set to SizeViewToRootObject (the default), the view resizes with the root item in the QML.
If this property is set to SizeRootObjectToView, the view will automatically resize the root item.
Regardless of this property, the sizeHint of the view is the initial size of the root item. Note though that since QML may load dynamically, that size may change.
Definition at line 67 of file qdeclarativeview.h.
source
QUrl QDeclarativeView::source private
The URL of the source of the QML component.
Returns the source URL, if set.
Changing this property causes the QML component to be reloaded.
Ensure that the URL provided is full and correct, in particular, use QUrl::fromLocalFile() when loading a file from the local filesystem.
See also
{Network Transparency}{Loading Resources in QML}
setSource()
Definition at line 69 of file qdeclarativeview.h.
status
QDeclarativeView::Status QDeclarativeView::status private
The component's current status.
Definition at line 68 of file qdeclarativeview.h.
The documentation for this class was generated from the following files:
/src/declarative/util/qdeclarativeview.h
/src/declarative/util/qdeclarativeview.cpp