Qt 4.8: QScriptStringPrivate Class Reference
QScriptStringPrivate Class Reference
#include <qscriptstring_p.h>
Public Types
enum AllocationType { StackAllocated, HeapAllocated }
Public Functions
void detachFromEngine ()
QScriptStringPrivate (QScriptEnginePrivate *engine, const JSC::Identifier &id, AllocationType type)
~QScriptStringPrivate ()
Static Public Functions
static QScriptStringPrivate * get (const QScriptString &q)
static void init (QScriptString &q, QScriptStringPrivate *d)
static bool isValid (const QScriptString &q)
Public Variables
QScriptEnginePrivate * engine
JSC::Identifier identifier
QScriptStringPrivate * next
QScriptStringPrivate * prev
QBasicAtomicInt ref
AllocationType type
Detailed Description
Definition at line 45 of file qscriptstring_p.h.
Enumerations
AllocationType
enum QScriptStringPrivate::AllocationType
Enumerator
StackAllocated
HeapAllocated
Definition at line 48 of file qscriptstring_p.h.
{
         StackAllocated,
         HeapAllocated
     };
Constructors and Destructors
QScriptStringPrivate()
QScriptStringPrivate::QScriptStringPrivate (QScriptEnginePrivate * engine, const JSC::Identifier & id, AllocationType type) inline
Definition at line 74 of file qscriptstring_p.h.
     : engine(e), identifier(id), type(tp), prev(0), next(0)
 {
     ref = 0;
 }
~QScriptStringPrivate()
QScriptStringPrivate::~QScriptStringPrivate () inline
Definition at line 81 of file qscriptstring_p.h.
 {
 }
Functions
detachFromEngine()
void QScriptStringPrivate::detachFromEngine () inline
Definition at line 95 of file qscriptstring_p.h.
Referenced by QScriptEnginePrivate::detachAllRegisteredScriptStrings().
 {
     engine = 0;
     identifier = JSC::Identifier();
 }
get()
QScriptStringPrivate * QScriptStringPrivate::get (const QScriptString & q) inline static
Definition at line 90 of file qscriptstring_p.h.
Referenced by qHash().
 {
     return const_cast<QScriptStringPrivate*>(q.d_func());
 }
init()
void QScriptStringPrivate::init (QScriptString & q, QScriptStringPrivate * d) inline static
Definition at line 85 of file qscriptstring_p.h.
Referenced by QScript::ClassObjectDelegate::deleteProperty(), QScript::ClassObjectDelegate::getOwnPropertyDescriptor(), QScript::ClassObjectDelegate::getOwnPropertySlot(), QScript::ClassObjectDelegate::put(), and QScriptEnginePrivate::toStringHandle().
 {
     q.d_ptr = d;
 }
isValid()
bool QScriptStringPrivate::isValid (const QScriptString & q) inline static
Definition at line 101 of file qscriptstring_p.h.
Referenced by QScriptString::isValid(), QScriptValue::property(), QScriptValue::propertyFlags(), and QScriptValue::setProperty().
 {
     return (q.d_ptr && q.d_ptr->engine);
 }
Properties
engine
QScriptEnginePrivate* QScriptStringPrivate::engine
Definition at line 65 of file qscriptstring_p.h.
Referenced by detachFromEngine(), and isValid().
identifier
JSC::Identifier QScriptStringPrivate::identifier
Definition at line 66 of file qscriptstring_p.h.
Referenced by detachFromEngine(), QScriptValue::property(), QScriptValue::propertyFlags(), qHash(), and QScriptValue::setProperty().
next
QScriptStringPrivate* QScriptStringPrivate::next
Definition at line 71 of file qscriptstring_p.h.
Referenced by QScriptEnginePrivate::detachAllRegisteredScriptStrings(), QScriptEnginePrivate::registerScriptString(), and QScriptEnginePrivate::unregisterScriptString().
prev
QScriptStringPrivate* QScriptStringPrivate::prev
Definition at line 70 of file qscriptstring_p.h.
Referenced by QScriptEnginePrivate::detachAllRegisteredScriptStrings(), QScriptEnginePrivate::registerScriptString(), and QScriptEnginePrivate::unregisterScriptString().
ref
QBasicAtomicInt QScriptStringPrivate::ref
Definition at line 64 of file qscriptstring_p.h.
Referenced by QScriptStringPrivate().
type
AllocationType QScriptStringPrivate::type
Definition at line 67 of file qscriptstring_p.h.
Referenced by QScriptEnginePrivate::registerScriptString(), and QScriptEnginePrivate::unregisterScriptString().
The documentation for this class was generated from the following file:
/src/script/api/qscriptstring_p.h