Qt 4.8: QScriptString Class Reference
QScriptString Class Reference
The QScriptString class acts as a handle to "interned" strings in a QScriptEngine.
#include <qscriptstring.h>
Public Functions
bool isValid () const
Returns true if this QScriptString is valid; otherwise returns false.
operator QString () const
Returns the string that this QScriptString represents, or a null string if this QScriptString is not valid.
bool operator!= (const QScriptString &other) const
Returns true if this QScriptString is not equal to other; otherwise returns false.
QScriptString & operator= (const QScriptString &other)
Assigns the other value to this QScriptString.
bool operator== (const QScriptString &other) const
Returns true if this QScriptString is equal to other; otherwise returns false.
QScriptString ()
Constructs an invalid QScriptString.
QScriptString (const QScriptString &other)
Constructs a new QScriptString that is a copy of other.
quint32 toArrayIndex (bool *ok=0) const
QString toString () const
Returns the string that this QScriptString represents, or a null string if this QScriptString is not valid.
~QScriptString ()
Destroys this QScriptString.
Properties
QExplicitlySharedDataPointer< QScriptStringPrivate > d_ptr
Friends
class QScriptValue
Detailed Description
The QScriptString class acts as a handle to "interned" strings in a QScriptEngine.
Since
4.4
QScriptString can be used to achieve faster (repeated) property getting/setting, and comparison of property names, of script objects.
To get a QScriptString representation of a string, pass the string to QScriptEngine::toStringHandle(). The typical usage pattern is to register one or more pre-defined strings when setting up your script environment, then subsequently use the relevant QScriptString as argument to e.g. QScriptValue::property().
Call the toString() function to obtain the string that a QScriptString represents.
Call the toArrayIndex() function to convert a QScriptString to an array index. This is useful when using QScriptClass to implement array-like objects.
Definition at line 38 of file qscriptstring.h.
Constructors and Destructors
QScriptString() [1/2]
QScriptString::QScriptString ()
Constructs an invalid QScriptString.
Definition at line 65 of file qscriptstring.cpp.
     : d_ptr(0)
 {
 }
QScriptString() [2/2]
QScriptString::QScriptString (const QScriptString & other)
Constructs a new QScriptString that is a copy of other.
Definition at line 73 of file qscriptstring.cpp.
     : d_ptr(other.d_ptr)
 {
     if (d_func() && (d_func()->type == QScriptStringPrivate::StackAllocated)) {
         Q_ASSERT(d_func()->ref != 1);
         d_ptr.detach();
         d_func()->ref = 1;
         d_func()->type = QScriptStringPrivate::HeapAllocated;
         d_func()->engine->registerScriptString(d_func());
     }
 }
~QScriptString()
QScriptString::~QScriptString ()
Destroys this QScriptString.
Definition at line 88 of file qscriptstring.cpp.
 {
     Q_D(QScriptString);
     if (d) {
         switch (d->type) {
         case QScriptStringPrivate::StackAllocated:
             Q_ASSERT(d->ref == 1);
             d->ref.ref(); // avoid deletion
             break;
         case QScriptStringPrivate::HeapAllocated:
             if (d->engine && (d->ref == 1)) {
                 // Make sure the identifier is removed from the correct engine.
                 QScript::APIShim shim(d->engine);
                 d->identifier = JSC::Identifier();
                 d->engine->unregisterScriptString(d);
             }
             break;
         }
     }
 }
Functions
isValid()
bool QScriptString::isValid () const
Returns true if this QScriptString is valid; otherwise returns false.
Definition at line 133 of file qscriptstring.cpp.
 {
     return QScriptStringPrivate::isValid(*this);
 }
operator QString()
QScriptString::operator QString () const
Returns the string that this QScriptString represents, or a null string if this QScriptString is not valid.
See also
toString()
Definition at line 204 of file qscriptstring.cpp.
 {
     return toString();
 }
operator!=()
bool QScriptString::operator!= (const QScriptString & other) const
Returns true if this QScriptString is not equal to other; otherwise returns false.
Definition at line 154 of file qscriptstring.cpp.
 {
     return !operator==(other);
 }
operator=()
QScriptString & QScriptString::operator= (const QScriptString & other)
Assigns the other value to this QScriptString.
Definition at line 112 of file qscriptstring.cpp.
 {
     if (d_func() && d_func()->engine && (d_func()->ref == 1) && (d_func()->type == QScriptStringPrivate::HeapAllocated)) {
         // current d_ptr will be deleted at the assignment below, so unregister it first
         d_func()->engine->unregisterScriptString(d_func());
     }
     d_ptr = other.d_ptr;
     if (d_func() && (d_func()->type == QScriptStringPrivate::StackAllocated)) {
         Q_ASSERT(d_func()->ref != 1);
         d_ptr.detach();
         d_func()->ref = 1;
         d_func()->type = QScriptStringPrivate::HeapAllocated;
         d_func()->engine->registerScriptString(d_func());
     }
     return *this;
 }
operator==()
bool QScriptString::operator== (const QScriptString & other) const
Returns true if this QScriptString is equal to other; otherwise returns false.
Definition at line 142 of file qscriptstring.cpp.
Referenced by operator!=().
 {
     Q_D(const QScriptString);
     if (!d || !other.d_func())
         return d == other.d_func();
     return d->identifier == other.d_func()->identifier;
 }
toArrayIndex()
quint32 QScriptString::toArrayIndex (bool * ok = 0) const
Since
4.6
Attempts to convert this QScriptString to a QtScript array index, and returns the result.
If a conversion error occurs, *{ok} is set to false; otherwise {ok} is set to true.
Definition at line 168 of file qscriptstring.cpp.
 {
     Q_D(const QScriptString);
     if (!d) {
         if (ok)
             *ok = false;
         return -1;
     }
     bool tmp;
     bool *okok = ok ? ok : &tmp;
     quint32 result = d->identifier.toArrayIndex(okok);
     if (!*okok)
         result = -1;
     return result;
 }
toString()
QString QScriptString::toString () const
Returns the string that this QScriptString represents, or a null string if this QScriptString is not valid.
See also
isValid()
Definition at line 190 of file qscriptstring.cpp.
Referenced by QScript::ClassObjectDelegate::getOwnPropertyNames(), operator QString(), NamedNodeMapClass::queryProperty(), NodeListClass::queryProperty(), QDeclarativeGlobalScriptClass::setProperty(), and QScriptValue::setProperty().
 {
     Q_D(const QScriptString);
     if (!d || !d->engine)
         return QString();
     return d->identifier.ustring();
 }
Friends and Related Functions
QScriptValue
friend class QScriptValue friend
Definition at line 59 of file qscriptstring.h.
Properties
d_ptr
QExplicitlySharedDataPointer<QScriptStringPrivate> QScriptString::d_ptr private
Definition at line 58 of file qscriptstring.h.
Referenced by QScriptStringPrivate::init(), QScriptStringPrivate::isValid(), operator=(), QScriptValue::property(), QScriptValue::propertyFlags(), QScriptString(), and QScriptValue::setProperty().
The documentation for this class was generated from the following files:
/src/script/api/qscriptstring.h
/src/script/api/qscriptstring.cpp