Qt 4.8: QLineControl Class Reference
QLineControl Class Reference
#include <qlinecontrol_p.h>
Classes
struct Command
struct MaskInputData
Public Types
enum DrawFlags { DrawText = 0x01, DrawSelections = 0x02, DrawCursor = 0x04, DrawAll = DrawText | DrawSelections | DrawCursor }
Signals
void accepted ()
void cursorPositionChanged (int, int)
void displayTextChanged (const QString &)
void editingFinished ()
void resetInputContext ()
void selectionChanged ()
void textChanged (const QString &)
void textEdited (const QString &)
void updateMicroFocus ()
void updateNeeded (const QRect &)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool allSelected () const
int ascent () const
void backspace ()
Handles the behavior for the backspace key or function.
QString cancelText () const
void clear ()
Clears the line control text.
void clearUndo ()
void complete (int key)
QCompleter * completer () const
bool composeMode () const
void copy (QClipboard::Mode mode=QClipboard::Clipboard) const
Copies the currently selected text into the clipboard using the given mode.
int cursor () const
int cursorBlinkPeriod () const
void cursorForward (bool mark, int steps)
Qt::CursorMoveStyle cursorMoveStyle () const
int cursorPosition () const
QRect cursorRect () const
Returns the bounds of the current cursor, as defined as a between characters cursor.
qreal cursorToX (int cursor) const
qreal cursorToX () const
int cursorWidth () const
void cursorWordBackward (bool mark)
void cursorWordForward (bool mark)
void del ()
Handles the behavior for the delete key or function.
void deselect ()
QString displayText () const
void draw (QPainter *, const QPoint &, const QRect &, int flags=DrawAll)
Draws the display text for the line control using the given painter, clip, and offset.
uint echoMode () const
int end () const
void end (bool mark)
bool fixup ()
Fixes the current text so that it is valid given any set validators.
bool hasAcceptableInput () const
bool hasSelectedText () const
int height () const
void home (bool mark)
QString inputMask () const
bool inSelection (int x) const
void insert (const QString &)
Inserts the given newText at the current cursor position.
bool isModified () const
bool isReadOnly () const
bool isRedoAvailable () const
bool isUndoAvailable () const
Qt::LayoutDirection layoutDirection () const
int maxLength () const
void moveCursor (int pos, bool mark=false)
Moves the cursor to the given position pos.
qreal naturalTextWidth () const
int nextMaskBlank (int pos)
const QPalette & palette () const
QChar passwordCharacter () const
bool passwordEchoEditing () const
void paste (QClipboard::Mode mode=QClipboard::Clipboard)
Inserts the text stored in the application clipboard into the line control.
QString preeditAreaText () const
int preeditCursor () const
int prevMaskBlank (int pos)
bool processEvent (QEvent *ev)
void processInputMethodEvent (QInputMethodEvent *event)
void processKeyEvent (QKeyEvent *ev)
void processMouseEvent (QMouseEvent *ev)
QLineControl (const QString &txt=QString())
void redo ()
void removeSelection ()
void resetCursorBlinkTimer ()
void selectAll ()
QString selectedText () const
int selectionEnd () const
int selectionStart () const
void selectWordAtPos (int)
Sets the selection to cover the word at the given cursor position.
void setCancelText (const QString &text)
void setCompleter (const QCompleter *c)
void setCursorBlinkPeriod (int msec)
void setCursorMoveStyle (Qt::CursorMoveStyle style)
void setCursorPosition (int pos)
void setCursorWidth (int value)
void setEchoMode (uint mode)
void setFont (const QFont &font)
void setInputMask (const QString &mask)
void setLayoutDirection (Qt::LayoutDirection direction)
void setMaxLength (int maxLength)
void setModified (bool modified)
void setPalette (const QPalette &p)
void setPasswordCharacter (const QChar &character)
void setPreeditArea (int cursor, const QString &text)
void setReadOnly (bool enable)
void setSelection (int start, int length)
Sets length characters from the given start position as selected.
void setText (const QString &txt)
void setValidator (const QValidator *v)
int start () const
QString text () const
QString textAfterSelection () const
QString textBeforeSelection () const
void undo ()
void updatePasswordEchoEditing (bool editing)
Sets the password echo editing to editing.
const QValidator * validator () const
int width () const
int xToPos (int x, QTextLine::CursorPosition=QTextLine::CursorBetweenCharacters) const
Returns the cursor position of the given x pixel value in relation to the displayed text.
~QLineControl ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual void timerEvent (QTimerEvent *event)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Types
enum CommandType {
Separator, Insert, Remove, Delete,
RemoveSelection, DeleteSelection, SetSelection
}
Private Slots
void _q_clipboardChanged ()
void _q_deleteSelected ()
Private Functions
void addCommand (const Command &cmd)
Adds the given command to the undo history of the line control.
bool advanceToEnabledItem (int dir)
void cancelPasswordEchoTimer ()
QString clearString (uint pos, uint len) const
Returns a "cleared" string with only separators and blank chars.
void emitCursorPositionChanged ()
If the current cursor position differs from the last emitted cursor position, emits cursorPositionChanged().
int findInMask (int pos, bool forward, bool findSeparator, QChar searchChar=QChar()) const
bool finishChange (int validateFromState=-1, bool update=false, bool edited=true)
Completes a change to the line control text.
bool hasAcceptableInput (const QString &text) const
Returns true if the given text str is valid for any validator or input mask set for the line control.
void init (const QString &txt)
Initializes the line control with a starting text value of txt.
void internalDelete (bool wasBackspace=false)
Also adds the appropriate commands into the undo history.
void internalDeselect ()
void internalInsert (const QString &s)
Inserts the given string s into the line control.
void internalRedo ()
void internalRemove (int pos)
void internalSetText (const QString &txt, int pos=-1, bool edited=true)
An internal function for setting the text of the line control.
void internalUndo (int until=-1)
bool isValidInput (QChar key, QChar mask) const
QString maskString (uint pos, const QString &str, bool clear=false) const
Applies the inputMask on str starting from position pos in the mask.
void parseInputMask (const QString &maskFields)
Parses the input mask specified by maskFields to generate the mask data used to handle input masks.
void removeSelectedText ()
Also adds the appropriate commands into the undo history.
void separate ()
QString stripString (const QString &str) const
Strips blank parts of the input in a QLineControl when an inputMask is set, separators are still included.
void updateDisplayText (bool forceUpdate=false)
Properties
int m_ascent
QChar m_blank
int m_blinkPeriod
uint m_blinkStatus: 1
int m_blinkTimer
QString m_cancelText
QPointer< QCompleter > m_completer
int m_cursor
int m_cursorWidth
int m_deleteAllTimer
uint m_dragEnabled: 1
uint m_echoMode: 2
uint m_hideCursor: 1
QVector< Command > m_history
QString m_inputMask
int m_lastCursorPos
Qt::LayoutDirection m_layoutDirection
MaskInputData * m_maskData
int m_maxLength
int m_modifiedState
QPalette m_palette
QChar m_passwordCharacter
bool m_passwordEchoEditing
int m_preeditCursor
uint m_readOnly: 1
uint m_selDirty: 1
int m_selend
int m_selstart
uint m_separator: 1
QString m_text
uint m_textDirty: 1
QTextLayout m_textLayout
QList< int > m_transactions
QPoint m_tripleClick
int m_tripleClickTimer
int m_undoState
QPointer< QValidator > m_validator
uint m_validInput: 1
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 77 of file qlinecontrol_p.h.
Enumerations
CommandType
enum QLineControl::CommandType private
Enumerator
Separator
Insert
Remove
Delete
RemoveSelection
DeleteSelection
SetSelection
Definition at line 401 of file qlinecontrol_p.h.
 { Separator, Insert, Remove, Delete, RemoveSelection, DeleteSelection, SetSelection };
DrawFlags
enum QLineControl::DrawFlags
Enumerator
DrawText
DrawSelections
DrawCursor
DrawAll
Definition at line 323 of file qlinecontrol_p.h.
                    {
         DrawText = 0x01,
         DrawSelections = 0x02,
         DrawCursor = 0x04,
         DrawAll = DrawText | DrawSelections | DrawCursor
     };
Constructors and Destructors
QLineControl()
QLineControl::QLineControl (const QString & txt = QString()) inline
Definition at line 82 of file qlinecontrol_p.h.
         : m_cursor(0), m_preeditCursor(0), m_cursorWidth(0), m_layoutDirection(Qt::LayoutDirectionAuto),
         m_hideCursor(false), m_separator(0), m_readOnly(0),
         m_dragEnabled(0), m_echoMode(0), m_textDirty(0), m_selDirty(0),
         m_validInput(1), m_blinkStatus(0), m_blinkPeriod(0), m_blinkTimer(0), m_deleteAllTimer(0),
         m_ascent(0), m_maxLength(32767), m_lastCursorPos(-1),
         m_tripleClickTimer(0), m_maskData(0), m_modifiedState(0), m_undoState(0),
         m_selstart(0), m_selend(0), m_passwordEchoEditing(false)
 #ifdef QT_GUI_PASSWORD_ECHO_DELAY
         , m_passwordEchoTimer(0)
 #endif
     {
         init(txt);
     }
~QLineControl()
QLineControl::~QLineControl () inline
Definition at line 97 of file qlinecontrol_p.h.
     {
         delete [] m_maskData;
     }
Functions
_q_clipboardChanged
void QLineControl::_q_clipboardChanged () private slot
Definition at line 330 of file qlinecontrol.cpp.
Referenced by copy().
 {
 }
_q_deleteSelected
void QLineControl::_q_deleteSelected () private slot
Definition at line 334 of file qlinecontrol.cpp.
 {
     if (!hasSelectedText())
         return;
     int priorState = m_undoState;
     emit resetInputContext();
     removeSelectedText();
     separate();
     finishChange(priorState);
 }
accepted
void QLineControl::accepted () signal
Referenced by processKeyEvent().
addCommand()
void QLineControl::addCommand (const Command & cmd) private
Adds the given command to the undo history of the line control.
Warning
This function is not part of the public interface.
Does not apply the command.
Definition at line 778 of file qlinecontrol.cpp.
Referenced by internalDelete(), internalInsert(), and removeSelectedText().
 {
     if (m_separator && m_undoState && m_history[m_undoState - 1].type != Separator) {
         m_history.resize(m_undoState + 2);
         m_history[m_undoState++] = Command(Separator, m_cursor, 0, m_selstart, m_selend);
     } else {
         m_history.resize(m_undoState + 1);
     }
     m_separator = false;
     m_history[m_undoState++] = cmd;
 }
advanceToEnabledItem()
bool QLineControl::advanceToEnabledItem (int dir) private
Definition at line 1408 of file qlinecontrol.cpp.
Referenced by complete().
 {
     int start = m_completer->currentRow();
     if (start == -1)
         return false;
     int i = start + dir;
     if (dir == 0) dir = 1;
     do {
         if (!m_completer->setCurrentRow(i)) {
             if (!m_completer->wrapAround())
                 break;
             i = i > 0 ? 0 : m_completer->completionCount() - 1;
         } else {
             QModelIndex currentIndex = m_completer->currentIndex();
             if (m_completer->completionModel()->flags(currentIndex) & Qt::ItemIsEnabled)
                 return true;
             i += dir;
         }
     } while (i != start);
     m_completer->setCurrentRow(start); // restore
     return false;
 }
allSelected()
bool QLineControl::allSelected () const inline
Definition at line 123 of file qlinecontrol_p.h.
 { return !m_text.isEmpty() && m_selstart == 0 && m_selend == (int)m_text.length(); }
ascent()
int QLineControl::ascent () const inline
Definition at line 128 of file qlinecontrol_p.h.
 { return m_ascent; }
backspace()
void QLineControl::backspace ()
Handles the behavior for the backspace key or function.
Warning
This function is not part of the public interface.
Removes the current selection if there is a selection, otherwise removes the character prior to the cursor position.
See also
del()
Definition at line 204 of file qlinecontrol.cpp.
Referenced by processEvent(), and processKeyEvent().
 {
     int priorState = m_undoState;
     if (hasSelectedText()) {
         removeSelectedText();
     } else if (m_cursor) {
             --m_cursor;
             if (m_maskData)
                 m_cursor = prevMaskBlank(m_cursor);
             if (m_cursor > 0 && m_text.at(m_cursor).isLowSurrogate()) {
                 // second half of a surrogate, check if we have the first half as well,
                 // if yes delete both at once
                 if (m_text.at(m_cursor - 1).isHighSurrogate()) {
                     internalDelete(true);
                     --m_cursor;
                 }
             }
             internalDelete(true);
     }
     finishChange(priorState);
 }
cancelPasswordEchoTimer()
void QLineControl::cancelPasswordEchoTimer () inline private
Definition at line 437 of file qlinecontrol_p.h.
Referenced by internalDelete(), internalSetText(), internalUndo(), removeSelectedText(), and updatePasswordEchoEditing().
     {
 #ifdef QT_GUI_PASSWORD_ECHO_DELAY
         if (m_passwordEchoTimer != 0) {
             killTimer(m_passwordEchoTimer);
             m_passwordEchoTimer = 0;
         }
 #endif
     }
cancelText()
QString QLineControl::cancelText () const inline
Definition at line 317 of file qlinecontrol_p.h.
 { return m_cancelText; }
clear()
void QLineControl::clear ()
Clears the line control text.
Warning
This function is not part of the public interface.
Definition at line 277 of file qlinecontrol.cpp.
Referenced by internalUndo(), processKeyEvent(), and timerEvent().
 {
     int priorState = m_undoState;
     m_selstart = 0;
     m_selend = m_text.length();
     removeSelectedText();
     separate();
     finishChange(priorState, /*update*/false, /*edited*/false);
 }
clearString()
QString QLineControl::clearString (uint pos, uint len) const private
Returns a "cleared" string with only separators and blank chars.
Warning
This function is not part of the public interface.
Calling this when no inputMask is set is undefined.
Definition at line 1220 of file qlinecontrol.cpp.
Referenced by internalDelete(), internalSetText(), maskString(), and removeSelectedText().
 {
     if (pos >= (uint)m_maxLength)
         return QString();
     QString s;
     int end = qMin((uint)m_maxLength, pos + len);
     for (int i = pos; i < end; ++i)
         if (m_maskData[i].separator)
             s += m_maskData[i].maskChar;
         else
             s += m_blank;
     return s;
 }
clearUndo()
void QLineControl::clearUndo () inline
Definition at line 118 of file qlinecontrol_p.h.
 { m_history.clear(); m_modifiedState = m_undoState = 0; }
complete()
void QLineControl::complete (int key)
Definition at line 1432 of file qlinecontrol.cpp.
Referenced by QLineEditPrivate::_q_textEdited(), and processKeyEvent().
 {
     if (!m_completer || isReadOnly() || echoMode() != QLineEdit::Normal)
         return;
     QString text = this->text();
     if (m_completer->completionMode() == QCompleter::InlineCompletion) {
         if (key == Qt::Key_Backspace)
             return;
         int n = 0;
         if (key == Qt::Key_Up || key == Qt::Key_Down) {
             if (textAfterSelection().length())
                 return;
             QString prefix = hasSelectedText() ? textBeforeSelection()
                 : text;
             if (text.compare(m_completer->currentCompletion(), m_completer->caseSensitivity()) != 0
                 || prefix.compare(m_completer->completionPrefix(), m_completer->caseSensitivity()) != 0) {
                 m_completer->setCompletionPrefix(prefix);
             } else {
                 n = (key == Qt::Key_Up) ? -1 : +1;
             }
         } else {
             m_completer->setCompletionPrefix(text);
         }
         if (!advanceToEnabledItem(n))
             return;
     } else {
 #ifndef QT_KEYPAD_NAVIGATION
         if (text.isEmpty()) {
             m_completer->popup()->hide();
             return;
         }
 #endif
         m_completer->setCompletionPrefix(text);
     }
     m_completer->complete();
 }
completer()
QCompleter* QLineControl::completer () const inline
Definition at line 251 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::_q_completionHighlighted(), and QLineEditPrivate::_q_textEdited().
 { return m_completer; }
composeMode()
bool QLineControl::composeMode () const inline
Definition at line 273 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::sendMouseEventToInputContext().
 { return !m_textLayout.preeditAreaText().isEmpty(); }
copy()
void QLineControl::copy (QClipboard::Mode mode = QClipboard::Clipboard) const
Copies the currently selected text into the clipboard using the given mode.
Warning
This function is not part of the public interface.
Note
If the echo mode is set to a mode other than Normal then copy will not work. This is to prevent using copy as a method of bypassing password features of the line control.
Definition at line 158 of file qlinecontrol.cpp.
Referenced by processKeyEvent(), and processMouseEvent().
 {
     QString t = selectedText();
     if (!t.isEmpty() && m_echoMode == QLineEdit::Normal) {
         disconnect(QApplication::clipboard(), SIGNAL(selectionChanged()), this, 0);
         QApplication::clipboard()->setText(t, mode);
         connect(QApplication::clipboard(), SIGNAL(selectionChanged()),
                    this, SLOT(_q_clipboardChanged()));
     }
 }
cursor()
int QLineControl::cursor () const inline
Definition at line 162 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::_q_completionHighlighted(), draw(), processKeyEvent(), processMouseEvent(), QLineEditPrivate::sendMouseEventToInputContext(), and updateDisplayText().
 { return m_cursor; }
cursorBlinkPeriod()
int QLineControl::cursorBlinkPeriod () const inline
Definition at line 313 of file qlinecontrol_p.h.
 { return m_blinkPeriod; }
cursorForward()
void QLineControl::cursorForward (bool mark, int steps) inline
Definition at line 172 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
     {
         int c = m_cursor;
         if (steps > 0) {
             while (steps--)
                 c = cursorMoveStyle() == Qt::VisualMoveStyle ? m_textLayout.rightCursorPosition(c)
                                                              : m_textLayout.nextCursorPosition(c);
         } else if (steps < 0) {
             while (steps++)
                 c = cursorMoveStyle() == Qt::VisualMoveStyle ? m_textLayout.leftCursorPosition(c)
                                                              : m_textLayout.previousCursorPosition(c);
         }
         moveCursor(c, mark);
     }
cursorMoveStyle()
Qt::CursorMoveStyle QLineControl::cursorMoveStyle () const inline
Definition at line 168 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { return m_textLayout.cursorMoveStyle(); }
cursorPosition()
int QLineControl::cursorPosition () const inline
Definition at line 257 of file qlinecontrol_p.h.
 { return m_cursor; }
cursorPositionChanged
void QLineControl::cursorPositionChanged (int , int) signal
Referenced by emitCursorPositionChanged(), and processInputMethodEvent().
cursorRect()
QRect QLineControl::cursorRect () const
Returns the bounds of the current cursor, as defined as a between characters cursor.
Warning
This function is not part of the public interface.
Definition at line 403 of file qlinecontrol.cpp.
Referenced by QLineEditPrivate::cursorRect(), setCursorBlinkPeriod(), and timerEvent().
 {
     QTextLine l = m_textLayout.lineAt(0);
     int c = m_cursor;
     if (m_preeditCursor != -1)
         c += m_preeditCursor;
     int cix = qRound(l.cursorToX(c));
     int w = m_cursorWidth;
     int ch = l.height() + 1;
     return QRect(cix-5, 0, w+9, ch);
 }
cursorToX() [1/2]
qreal QLineControl::cursorToX (int cursor) const inline
Definition at line 196 of file qlinecontrol_p.h.
 { return m_textLayout.lineAt(0).cursorToX(cursor); }
cursorToX() [2/2]
qreal QLineControl::cursorToX () const inline
Definition at line 197 of file qlinecontrol_p.h.
     {
         int cursor = m_cursor;
         if (m_preeditCursor != -1)
             cursor += m_preeditCursor;
         return cursorToX(cursor);
     }
cursorWidth()
int QLineControl::cursorWidth () const inline
Definition at line 165 of file qlinecontrol_p.h.
 { return m_cursorWidth; }
cursorWordBackward()
void QLineControl::cursorWordBackward (bool mark) inline
Definition at line 188 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { moveCursor(m_textLayout.previousCursorPosition(m_cursor, QTextLayout::SkipWords), mark); }
cursorWordForward()
void QLineControl::cursorWordForward (bool mark) inline
Definition at line 187 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { moveCursor(m_textLayout.nextCursorPosition(m_cursor, QTextLayout::SkipWords), mark); }
del()
void QLineControl::del ()
Handles the behavior for the delete key or function.
Warning
This function is not part of the public interface.
Removes the current selection if there is a selection, otherwise removes the character after the cursor position.
See also
del()
Definition at line 238 of file qlinecontrol.cpp.
Referenced by processKeyEvent().
 {
     int priorState = m_undoState;
     if (hasSelectedText()) {
         removeSelectedText();
     } else {
         int n = m_textLayout.nextCursorPosition(m_cursor) - m_cursor;
         while (n--)
             internalDelete();
     }
     finishChange(priorState);
 }
deselect()
void QLineControl::deselect () inline
Definition at line 218 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::_q_handleWindowActivate(), and processMouseEvent().
 { internalDeselect(); finishChange(); }
displayText()
QString QLineControl::displayText () const inline
Definition at line 214 of file qlinecontrol_p.h.
 { return m_textLayout.text(); }
displayTextChanged
void QLineControl::displayTextChanged (const QString &) signal
Referenced by updateDisplayText().
draw()
void QLineControl::draw (QPainter * painter, const QPoint & offset, const QRect & clip, int flags = DrawAll)
Draws the display text for the line control using the given painter, clip, and offset.
Warning
This function is not part of the public interface.
Which aspects of the display text are drawn is specified by the given flags.
If the flags contain DrawSelections, then the selection or input mask backgrounds and foregrounds will be applied before drawing the text.
If the flags contain DrawCursor a cursor of the current cursorWidth() will be drawn after drawing the text.
The display text will only be drawn if the flags contain DrawText
Definition at line 608 of file qlinecontrol.cpp.
 {
     QVector<QTextLayout::FormatRange> selections;
     if (flags & DrawSelections) {
         QTextLayout::FormatRange o;
         if (m_selstart < m_selend) {
             o.start = m_selstart;
             o.length = m_selend - m_selstart;
             o.format.setBackground(m_palette.brush(QPalette::Highlight));
             o.format.setForeground(m_palette.brush(QPalette::HighlightedText));
         } else {
             // mask selection
             if(!m_blinkPeriod || m_blinkStatus){
                 o.start = m_cursor;
                 o.length = 1;
                 o.format.setBackground(m_palette.brush(QPalette::Text));
                 o.format.setForeground(m_palette.brush(QPalette::Window));
             }
         }
         selections.append(o);
     }
     if (flags & DrawText)
         m_textLayout.draw(painter, offset, selections, clip);
     if (flags & DrawCursor){
         int cursor = m_cursor;
         if (m_preeditCursor != -1)
             cursor += m_preeditCursor;
         if (!m_hideCursor && (!m_blinkPeriod || m_blinkStatus))
             m_textLayout.drawCursor(painter, offset, cursor, m_cursorWidth);
     }
 }
echoMode()
uint QLineControl::echoMode () const inline
Definition at line 227 of file qlinecontrol_p.h.
Referenced by complete(), processInputMethodEvent(), and processKeyEvent().
 { return m_echoMode; }
editingFinished
void QLineControl::editingFinished () signal
Referenced by processKeyEvent().
emitCursorPositionChanged()
void QLineControl::emitCursorPositionChanged () private
If the current cursor position differs from the last emitted cursor position, emits cursorPositionChanged().
Warning
This function is not part of the public interface.
Definition at line 1393 of file qlinecontrol.cpp.
Referenced by finishChange(), internalRedo(), internalUndo(), moveCursor(), processInputMethodEvent(), and setSelection().
 {
     if (m_cursor != m_lastCursorPos) {
         const int oldLast = m_lastCursorPos;
         m_lastCursorPos = m_cursor;
         cursorPositionChanged(oldLast, m_cursor);
 #ifndef QT_NO_ACCESSIBILITY
         QAccessible::updateAccessibility(parent(), 0, QAccessible::TextCaretMoved);
 #endif
     }
 }
end() [1/2]
int QLineControl::end () const inline
Definition at line 155 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::_q_completionHighlighted(), clearString(), findInMask(), processKeyEvent(), selectWordAtPos(), and stripString().
 { return m_text.length(); }
end() [2/2]
void QLineControl::end (bool mark) inline
Definition at line 191 of file qlinecontrol_p.h.
 { moveCursor(text().length(), mark); }
findInMask()
int QLineControl::findInMask (int pos, bool forward, bool findSeparator, QChar searchChar = QChar()) const private
Warning
This function is not part of the public interface. searches forward/backward in m_maskData for either a separator or a m_blank
Definition at line 1266 of file qlinecontrol.cpp.
Referenced by maskString().
 {
     if (pos >= m_maxLength || pos < 0)
         return -1;
     int end = forward ? m_maxLength : -1;
     int step = forward ? 1 : -1;
     int i = pos;
     while (i != end) {
         if (findSeparator) {
             if (m_maskData[i].separator && m_maskData[i].maskChar == searchChar)
                 return i;
         } else {
             if (!m_maskData[i].separator) {
                 if (searchChar.isNull())
                     return i;
                 else if (isValidInput(searchChar, m_maskData[i].maskChar))
                     return i;
             }
         }
         i += step;
     }
     return -1;
 }
finishChange()
bool QLineControl::finishChange (int validateFromState = -1, bool update = false, bool edited = true) private
Completes a change to the line control text.
Warning
This function is not part of the public interface.
If the change is not valid will undo the line control state back to the given validateFromState.
If edited is true and the change is valid, will emit textEdited() in addition to textChanged(). Otherwise only emits textChanged() on a valid change.
The update value is currently unused.
Definition at line 681 of file qlinecontrol.cpp.
Referenced by _q_deleteSelected(), backspace(), clear(), del(), insert(), internalSetText(), and processInputMethodEvent().
 {
     Q_UNUSED(update)
     if (m_textDirty) {
         // do validation
         bool wasValidInput = m_validInput;
         m_validInput = true;
 #ifndef QT_NO_VALIDATOR
         if (m_validator) {
             m_validInput = false;
             QString textCopy = m_text;
             int cursorCopy = m_cursor;
             m_validInput = (m_validator->validate(textCopy, cursorCopy) != QValidator::Invalid);
             if (m_validInput) {
                 if (m_text != textCopy) {
                     internalSetText(textCopy, cursorCopy);
                     return true;
                 }
                 m_cursor = cursorCopy;
             }
         }
 #endif
         if (validateFromState >= 0 && wasValidInput && !m_validInput) {
             if (m_transactions.count())
                 return false;
             internalUndo(validateFromState);
             m_history.resize(m_undoState);
             if (m_modifiedState > m_undoState)
                 m_modifiedState = -1;
             m_validInput = true;
             m_textDirty = false;
         }
         updateDisplayText();
         if (m_textDirty) {
             m_textDirty = false;
             QString actualText = text();
             if (edited)
                 emit textEdited(actualText);
             emit textChanged(actualText);
         }
     }
     if (m_selDirty) {
         m_selDirty = false;
         emit selectionChanged();
     }
     if (m_cursor == m_lastCursorPos)
         updateMicroFocus();
     emitCursorPositionChanged();
     return true;
 }
fixup()
bool QLineControl::fixup ()
Fixes the current text so that it is valid given any set validators.
Warning
This function is not part of the public interface.
Returns true if the text was changed. Otherwise returns false.
Definition at line 426 of file qlinecontrol.cpp.
Referenced by processKeyEvent().
 {
 #ifndef QT_NO_VALIDATOR
     if (m_validator) {
         QString textCopy = m_text;
         int cursorCopy = m_cursor;
         m_validator->fixup(textCopy);
         if (m_validator->validate(textCopy, cursorCopy) == QValidator::Acceptable) {
             if (textCopy != m_text || cursorCopy != m_cursor)
                 internalSetText(textCopy, cursorCopy);
             return true;
         }
     }
 #endif
     return false;
 }
hasAcceptableInput() [1/2]
bool QLineControl::hasAcceptableInput () const inline
Definition at line 260 of file qlinecontrol_p.h.
Referenced by hasAcceptableInput(), and processKeyEvent().
 { return hasAcceptableInput(m_text); }
hasAcceptableInput() [2/2]
bool QLineControl::hasAcceptableInput (const QString & str) const private
Returns true if the given text str is valid for any validator or input mask set for the line control.
Warning
This function is not part of the public interface.
Otherwise returns false
Definition at line 1103 of file qlinecontrol.cpp.
 {
 #ifndef QT_NO_VALIDATOR
     QString textCopy = str;
     int cursorCopy = m_cursor;
     if (m_validator && m_validator->validate(textCopy, cursorCopy)
         != QValidator::Acceptable)
         return false;
 #endif
     if (!m_maskData)
         return true;
     if (str.length() != m_maxLength)
         return false;
     for (int i=0; i < m_maxLength; ++i) {
         if (m_maskData[i].separator) {
             if (str.at(i) != m_maskData[i].maskChar)
                 return false;
         } else {
             if (!isValidInput(str.at(i), m_maskData[i].maskChar))
                 return false;
         }
     }
     return true;
 }
hasSelectedText()
bool QLineControl::hasSelectedText () const inline
Definition at line 124 of file qlinecontrol_p.h.
Referenced by _q_deleteSelected(), QLineEditPrivate::_q_handleWindowActivate(), QLineEditPrivate::_q_selectionChanged(), backspace(), complete(), del(), internalDelete(), internalInsert(), paste(), and processKeyEvent().
 { return !m_text.isEmpty() && m_selend > m_selstart; }
height()
int QLineControl::height () const inline
Definition at line 127 of file qlinecontrol_p.h.
 { return qRound(m_textLayout.lineAt(0).height()) + 1; }
home()
void QLineControl::home (bool mark) inline
Definition at line 190 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { moveCursor(0, mark); }
init()
void QLineControl::init (const QString & txt) private
Initializes the line control with a starting text value of txt.
Warning
This function is not part of the public interface.
Definition at line 354 of file qlinecontrol.cpp.
 {
     m_text = txt;
     updateDisplayText();
     m_cursor = m_text.length();
 }
inputMask()
QString QLineControl::inputMask () const inline
Definition at line 263 of file qlinecontrol_p.h.
Referenced by setCursorBlinkPeriod(), QLineEditPrivate::setCursorVisible(), and timerEvent().
 { return m_maskData ? m_inputMask + QLatin1Char(';') + m_blank : QString(); }
inSelection()
bool QLineControl::inSelection (int x) const inline
Definition at line 139 of file qlinecontrol_p.h.
     {
         if (m_selstart >= m_selend)
             return false;
         int pos = xToPos(x, QTextLine::CursorOnCharacter);
         return pos >= m_selstart && pos < m_selend;
     }
insert()
void QLineControl::insert (const QString & newText)
Inserts the given newText at the current cursor position.
Warning
This function is not part of the public interface.
If there is any selected text it is removed prior to insertion of the new text.
Definition at line 261 of file qlinecontrol.cpp.
Referenced by paste(), processKeyEvent(), and processMouseEvent().
 {
     int priorState = m_undoState;
     removeSelectedText();
     internalInsert(newText);
     finishChange(priorState);
 }
internalDelete()
void QLineControl::internalDelete (bool wasBackspace = false) private
Also adds the appropriate commands into the undo history.
Warning
This function is not part of the public interface.
deletes a single character from the current text. If wasBackspace, the character prior to the cursor is removed. Otherwise the character after the cursor is removed.
This function does not call finishChange(), and may leave the text in an invalid state.
Definition at line 849 of file qlinecontrol.cpp.
Referenced by backspace(), and del().
 {
     if (m_cursor < (int) m_text.length()) {
         cancelPasswordEchoTimer();
         if (hasSelectedText())
             addCommand(Command(SetSelection, m_cursor, 0, m_selstart, m_selend));
         addCommand(Command((CommandType)((m_maskData ? 2 : 0) + (wasBackspace ? Remove : Delete)),
                    m_cursor, m_text.at(m_cursor), -1, -1));
         if (m_maskData) {
             m_text.replace(m_cursor, 1, clearString(m_cursor, 1));
             addCommand(Command(Insert, m_cursor, m_text.at(m_cursor), -1, -1));
         } else {
             m_text.remove(m_cursor, 1);
         }
         m_textDirty = true;
     }
 }
internalDeselect()
void QLineControl::internalDeselect () inline private
Definition at line 343 of file qlinecontrol_p.h.
Referenced by internalRedo(), internalSetText(), internalUndo(), moveCursor(), and removeSelectedText().
     {
         m_selDirty |= (m_selend > m_selstart);
         m_selstart = m_selend = 0;
     }
internalInsert()
void QLineControl::internalInsert (const QString & s) private
Inserts the given string s into the line control.
Warning
This function is not part of the public interface.
Also adds the appropriate commands into the undo history. This function does not call finishChange(), and may leave the text in an invalid state.
Definition at line 803 of file qlinecontrol.cpp.
Referenced by insert(), and processInputMethodEvent().
 {
 #ifdef QT_GUI_PASSWORD_ECHO_DELAY
     if (m_echoMode == QLineEdit::Password) {
         if (m_passwordEchoTimer != 0)
             killTimer(m_passwordEchoTimer);
         m_passwordEchoTimer = startTimer(qt_passwordEchoDelay);
     }
 #endif
     if (hasSelectedText())
         addCommand(Command(SetSelection, m_cursor, 0, m_selstart, m_selend));
     if (m_maskData) {
         QString ms = maskString(m_cursor, s);
         for (int i = 0; i < (int) ms.length(); ++i) {
             addCommand (Command(DeleteSelection, m_cursor + i, m_text.at(m_cursor + i), -1, -1));
             addCommand(Command(Insert, m_cursor + i, ms.at(i), -1, -1));
         }
         m_text.replace(m_cursor, ms.length(), ms);
         m_cursor += ms.length();
         m_cursor = nextMaskBlank(m_cursor);
         m_textDirty = true;
     } else {
         int remaining = m_maxLength - m_text.length();
         if (remaining != 0) {
             m_text.insert(m_cursor, s.left(remaining));
             for (int i = 0; i < (int) s.left(remaining).length(); ++i)
                addCommand(Command(Insert, m_cursor++, s.at(i), -1, -1));
             m_textDirty = true;
         }
     }
 }
internalRedo()
void QLineControl::internalRedo () private
Definition at line 1341 of file qlinecontrol.cpp.
 {
     if (!isRedoAvailable())
         return;
     internalDeselect();
     while (m_undoState < (int)m_history.size()) {
         Command& cmd = m_history[m_undoState++];
         switch (cmd.type) {
         case Insert:
             m_text.insert(cmd.pos, cmd.uc);
             m_cursor = cmd.pos + 1;
             break;
         case SetSelection:
             m_selstart = cmd.selStart;
             m_selend = cmd.selEnd;
             m_cursor = cmd.pos;
             break;
         case Remove:
         case Delete:
         case RemoveSelection:
         case DeleteSelection:
             m_text.remove(cmd.pos, 1);
             m_selstart = cmd.selStart;
             m_selend = cmd.selEnd;
             m_cursor = cmd.pos;
             break;
         case Separator:
             m_selstart = cmd.selStart;
             m_selend = cmd.selEnd;
             m_cursor = cmd.pos;
             break;
         }
         if (m_undoState < (int)m_history.size()) {
             Command& next = m_history[m_undoState];
             if (next.type != cmd.type && cmd.type < RemoveSelection && next.type != Separator
                  && (next.type < RemoveSelection || cmd.type == Separator))
                 break;
         }
     }
     m_textDirty = true;
     emitCursorPositionChanged();
 }
internalRemove()
void QLineControl::internalRemove (int pos) private
internalSetText()
void QLineControl::internalSetText (const QString & txt, int pos = -1, bool edited = true) private
An internal function for setting the text of the line control.
Warning
This function is not part of the public interface.
Definition at line 742 of file qlinecontrol.cpp.
Referenced by finishChange(), fixup(), and parseInputMask().
 {
     cancelPasswordEchoTimer();
     internalDeselect();
     emit resetInputContext();
     QString oldText = m_text;
     if (m_maskData) {
         m_text = maskString(0, txt, true);
         m_text += clearString(m_text.length(), m_maxLength - m_text.length());
     } else {
         m_text = txt.isEmpty() ? txt : txt.left(m_maxLength);
     }
     m_history.clear();
     m_modifiedState =  m_undoState = 0;
     m_cursor = (pos < 0 || pos > m_text.length()) ? m_text.length() : pos;
     m_textDirty = (oldText != m_text);
     bool changed = finishChange(-1, true, edited);
 #ifndef QT_NO_ACCESSIBILITY
     if (changed)
         QAccessible::updateAccessibility(parent(), 0, QAccessible::TextUpdated);
 #else
     Q_UNUSED(changed);
 #endif
 }
internalUndo()
void QLineControl::internalUndo (int until = -1) private
Definition at line 1292 of file qlinecontrol.cpp.
Referenced by finishChange().
 {
     if (!isUndoAvailable())
         return;
     cancelPasswordEchoTimer();
     internalDeselect();
     // Undo works only for clearing the line when in any of password the modes
     if (m_echoMode != QLineEdit::Normal) {
         clear();
         return;
     }
     while (m_undoState && m_undoState > until) {
         Command& cmd = m_history[--m_undoState];
         switch (cmd.type) {
         case Insert:
             m_text.remove(cmd.pos, 1);
             m_cursor = cmd.pos;
             break;
         case SetSelection:
             m_selstart = cmd.selStart;
             m_selend = cmd.selEnd;
             m_cursor = cmd.pos;
             break;
         case Remove:
         case RemoveSelection:
             m_text.insert(cmd.pos, cmd.uc);
             m_cursor = cmd.pos + 1;
             break;
         case Delete:
         case DeleteSelection:
             m_text.insert(cmd.pos, cmd.uc);
             m_cursor = cmd.pos;
             break;
         case Separator:
             continue;
         }
         if (until < 0 && m_undoState) {
             Command& next = m_history[m_undoState-1];
             if (next.type != cmd.type && next.type < RemoveSelection
                  && (cmd.type < RemoveSelection || next.type == Separator))
                 break;
         }
     }
     m_textDirty = true;
     emitCursorPositionChanged();
 }
isModified()
bool QLineControl::isModified () const inline
Definition at line 120 of file qlinecontrol_p.h.
 { return m_modifiedState != m_undoState; }
isReadOnly()
bool QLineControl::isReadOnly () const inline
Definition at line 205 of file qlinecontrol_p.h.
Referenced by complete(), QLineEditPrivate::drag(), processEvent(), processKeyEvent(), processMouseEvent(), and QLineEditPrivate::shouldEnableInputMethod().
 { return m_readOnly; }
isRedoAvailable()
bool QLineControl::isRedoAvailable () const
Definition at line 2005 of file qlinecontrol.cpp.
Referenced by internalRedo().
 {
     // Same as with undo. Disabled for password modes.
     return !m_readOnly
             && m_echoMode == QLineEdit::Normal
             && m_undoState < m_history.size();
 }
isUndoAvailable()
bool QLineControl::isUndoAvailable () const
Definition at line 1997 of file qlinecontrol.cpp.
Referenced by internalUndo().
 {
     // For security reasons undo is not available in any password mode (NoEcho included)
     // with the exception that the user can clear the password with undo.
     return !m_readOnly && m_undoState
             && (m_echoMode == QLineEdit::Normal || m_history[m_undoState - 1].type == QLineControl::Insert);
 }
isValidInput()
bool QLineControl::isValidInput (QChar key, QChar mask) const private
Warning
This function is not part of the public interface.
checks if the key is valid compared to the inputMask
Definition at line 1023 of file qlinecontrol.cpp.
Referenced by findInMask(), hasAcceptableInput(), and maskString().
 {
     switch (mask.unicode()) {
     case 'A':
         if (key.isLetter())
             return true;
         break;
     case 'a':
         if (key.isLetter() || key == m_blank)
             return true;
         break;
     case 'N':
         if (key.isLetterOrNumber())
             return true;
         break;
     case 'n':
         if (key.isLetterOrNumber() || key == m_blank)
             return true;
         break;
     case 'X':
         if (key.isPrint())
             return true;
         break;
     case 'x':
         if (key.isPrint() || key == m_blank)
             return true;
         break;
     case '9':
         if (key.isNumber())
             return true;
         break;
     case '0':
         if (key.isNumber() || key == m_blank)
             return true;
         break;
     case 'D':
         if (key.isNumber() && key.digitValue() > 0)
             return true;
         break;
     case 'd':
         if ((key.isNumber() && key.digitValue() > 0) || key == m_blank)
             return true;
         break;
     case '#':
         if (key.isNumber() || key == QLatin1Char('+') || key == QLatin1Char('-') || key == m_blank)
             return true;
         break;
     case 'B':
         if (key == QLatin1Char('0') || key == QLatin1Char('1'))
             return true;
         break;
     case 'b':
         if (key == QLatin1Char('0') || key == QLatin1Char('1') || key == m_blank)
             return true;
         break;
     case 'H':
         if (key.isNumber() || (key >= QLatin1Char('a') && key <= QLatin1Char('f')) || (key >= QLatin1Char('A') && key <= QLatin1Char('F')))
             return true;
         break;
     case 'h':
         if (key.isNumber() || (key >= QLatin1Char('a') && key <= QLatin1Char('f')) || (key >= QLatin1Char('A') && key <= QLatin1Char('F')) || key == m_blank)
             return true;
         break;
     default:
         break;
     }
     return false;
 }
layoutDirection()
Qt::LayoutDirection QLineControl::layoutDirection () const inline
Definition at line 291 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
{
         if (m_layoutDirection == Qt::LayoutDirectionAuto) {
             if (m_text.isEmpty())
                 return QApplication::keyboardInputDirection();
             return m_text.isRightToLeft() ? Qt::RightToLeft : Qt::LeftToRight;
         }
         return m_layoutDirection;
     }
maskString()
QString QLineControl::maskString (uint pos, const QString & str, bool clear = false) const private
Applies the inputMask on str starting from position pos in the mask.
Warning
This function is not part of the public interface.
clear specifies from where characters should be gotten when a separator is met in str - true means that blanks will be used, false that previous input is used. Calling this when no inputMask is set is undefined.
Definition at line 1142 of file qlinecontrol.cpp.
Referenced by internalInsert(), and internalSetText().
 {
     if (pos >= (uint)m_maxLength)
         return QString::fromLatin1("");
     QString fill;
     fill = clear ? clearString(0, m_maxLength) : m_text;
     int strIndex = 0;
     QString s = QString::fromLatin1("");
     int i = pos;
     while (i < m_maxLength) {
         if (strIndex < str.length()) {
             if (m_maskData[i].separator) {
                 s += m_maskData[i].maskChar;
                 if (str[(int)strIndex] == m_maskData[i].maskChar)
                     strIndex++;
                 ++i;
             } else {
                 if (isValidInput(str[(int)strIndex], m_maskData[i].maskChar)) {
                     switch (m_maskData[i].caseMode) {
                     case MaskInputData::Upper:
                         s += str[(int)strIndex].toUpper();
                         break;
                     case MaskInputData::Lower:
                         s += str[(int)strIndex].toLower();
                         break;
                     default:
                         s += str[(int)strIndex];
                     }
                     ++i;
                 } else {
                     // search for separator first
                     int n = findInMask(i, true, true, str[(int)strIndex]);
                     if (n != -1) {
                         if (str.length() != 1 || i == 0 || (i > 0 && (!m_maskData[i-1].separator || m_maskData[i-1].maskChar != str[(int)strIndex]))) {
                             s += fill.mid(i, n-i+1);
                             i = n + 1; // update i to find + 1
                         }
                     } else {
                         // search for valid m_blank if not
                         n = findInMask(i, true, false, str[(int)strIndex]);
                         if (n != -1) {
                             s += fill.mid(i, n-i);
                             switch (m_maskData[n].caseMode) {
                             case MaskInputData::Upper:
                                 s += str[(int)strIndex].toUpper();
                                 break;
                             case MaskInputData::Lower:
                                 s += str[(int)strIndex].toLower();
                                 break;
                             default:
                                 s += str[(int)strIndex];
                             }
                             i = n + 1; // updates i to find + 1
                         }
                     }
                 }
                 ++strIndex;
             }
         } else
             break;
     }
     return s;
 }
maxLength()
int QLineControl::maxLength () const inline
Definition at line 236 of file qlinecontrol_p.h.
 { return m_maxLength; }
moveCursor()
void QLineControl::moveCursor (int pos, bool mark = false)
Moves the cursor to the given position pos.
Warning
This function is not part of the public interface.
If mark is true will adjust the currently selected text.
Definition at line 452 of file qlinecontrol.cpp.
Referenced by QLineEditPrivate::_q_completionHighlighted(), processKeyEvent(), processMouseEvent(), and selectWordAtPos().
 {
     if (pos != m_cursor) {
         separate();
         if (m_maskData)
             pos = pos > m_cursor ? nextMaskBlank(pos) : prevMaskBlank(pos);
     }
     if (mark) {
         int anchor;
         if (m_selend > m_selstart && m_cursor == m_selstart)
             anchor = m_selend;
         else if (m_selend > m_selstart && m_cursor == m_selend)
             anchor = m_selstart;
         else
             anchor = m_cursor;
         m_selstart = qMin(anchor, pos);
         m_selend = qMax(anchor, pos);
         updateDisplayText();
     } else {
         internalDeselect();
     }
     m_cursor = pos;
     if (mark || m_selDirty) {
         m_selDirty = false;
         emit selectionChanged();
     }
     emitCursorPositionChanged();
 }
naturalTextWidth()
qreal QLineControl::naturalTextWidth () const inline
Definition at line 129 of file qlinecontrol_p.h.
 { return m_textLayout.lineAt(0).naturalTextWidth(); }
nextMaskBlank()
int QLineControl::nextMaskBlank (int pos) inline
Definition at line 102 of file qlinecontrol_p.h.
Referenced by internalInsert(), and moveCursor().
     {
         int c = findInMask(pos, true, false);
         m_separator |= (c != pos);
         return (c != -1 ?  c : m_maxLength);
     }
palette()
const QPalette& QLineControl::palette () const inline
Definition at line 320 of file qlinecontrol_p.h.
 { return m_palette; }
parseInputMask()
void QLineControl::parseInputMask (const QString & maskFields) private
Parses the input mask specified by maskFields to generate the mask data used to handle input masks.
Warning
This function is not part of the public interface.
Definition at line 920 of file qlinecontrol.cpp.
 {
     int delimiter = maskFields.indexOf(QLatin1Char(';'));
     if (maskFields.isEmpty() || delimiter == 0) {
         if (m_maskData) {
             delete [] m_maskData;
             m_maskData = 0;
             m_maxLength = 32767;
             internalSetText(QString());
         }
         return;
     }
     if (delimiter == -1) {
         m_blank = QLatin1Char(' ');
         m_inputMask = maskFields;
     } else {
         m_inputMask = maskFields.left(delimiter);
         m_blank = (delimiter + 1 < maskFields.length()) ? maskFields[delimiter + 1] : QLatin1Char(' ');
     }
     // calculate m_maxLength / m_maskData length
     m_maxLength = 0;
     QChar c = 0;
     for (int i=0; i<m_inputMask.length(); i++) {
         c = m_inputMask.at(i);
         if (i > 0 && m_inputMask.at(i-1) == QLatin1Char('\\')) {
             m_maxLength++;
             continue;
         }
         if (c != QLatin1Char('\\') && c != QLatin1Char('!') &&
              c != QLatin1Char('<') && c != QLatin1Char('>') &&
              c != QLatin1Char('{') && c != QLatin1Char('}') &&
              c != QLatin1Char('[') && c != QLatin1Char(']'))
             m_maxLength++;
     }
     delete [] m_maskData;
     m_maskData = new MaskInputData[m_maxLength];
     MaskInputData::Casemode m = MaskInputData::NoCaseMode;
     c = 0;
     bool s;
     bool escape = false;
     int index = 0;
     for (int i = 0; i < m_inputMask.length(); i++) {
         c = m_inputMask.at(i);
         if (escape) {
             s = true;
             m_maskData[index].maskChar = c;
             m_maskData[index].separator = s;
             m_maskData[index].caseMode = m;
             index++;
             escape = false;
         } else if (c == QLatin1Char('<')) {
                 m = MaskInputData::Lower;
         } else if (c == QLatin1Char('>')) {
             m = MaskInputData::Upper;
         } else if (c == QLatin1Char('!')) {
             m = MaskInputData::NoCaseMode;
         } else if (c != QLatin1Char('{') && c != QLatin1Char('}') && c != QLatin1Char('[') && c != QLatin1Char(']')) {
             switch (c.unicode()) {
             case 'A':
             case 'a':
             case 'N':
             case 'n':
             case 'X':
             case 'x':
             case '9':
             case '0':
             case 'D':
             case 'd':
             case '#':
             case 'H':
             case 'h':
             case 'B':
             case 'b':
                 s = false;
                 break;
             case '\\':
                 escape = true;
             default:
                 s = true;
                 break;
             }
             if (!escape) {
                 m_maskData[index].maskChar = c;
                 m_maskData[index].separator = s;
                 m_maskData[index].caseMode = m;
                 index++;
             }
         }
     }
     internalSetText(m_text);
 }
passwordCharacter()
QChar QLineControl::passwordCharacter () const inline
Definition at line 288 of file qlinecontrol_p.h.
 { return m_passwordCharacter; }
passwordEchoEditing()
bool QLineControl::passwordEchoEditing () const inline
Definition at line 280 of file qlinecontrol_p.h.
Referenced by processInputMethodEvent(), and processKeyEvent().
{
 #ifdef QT_GUI_PASSWORD_ECHO_DELAY
         if (m_passwordEchoTimer != 0)
             return true;
 #endif
         return m_passwordEchoEditing ;
     }
paste()
void QLineControl::paste (QClipboard::Mode clipboardMode = QClipboard::Clipboard)
Inserts the text stored in the application clipboard into the line control.
Warning
This function is not part of the public interface.
See also
insert()
Definition at line 180 of file qlinecontrol.cpp.
Referenced by processKeyEvent().
 {
     QString clip = QApplication::clipboard()->text(clipboardMode);
     if (!clip.isEmpty() || hasSelectedText()) {
         separate(); //make it a separate undo/redo command
         insert(clip);
         separate();
     }
 }
preeditAreaText()
QString QLineControl::preeditAreaText () const inline
Definition at line 277 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::_q_selectionChanged(), processInputMethodEvent(), and QLineEditPrivate::sendMouseEventToInputContext().
 { return m_textLayout.preeditAreaText(); }
preeditCursor()
int QLineControl::preeditCursor () const inline
Definition at line 163 of file qlinecontrol_p.h.
 { return m_preeditCursor; }
prevMaskBlank()
int QLineControl::prevMaskBlank (int pos) inline
Definition at line 109 of file qlinecontrol_p.h.
Referenced by backspace(), and moveCursor().
     {
         int c = findInMask(pos, false, false);
         m_separator |= (c != pos);
         return (c != -1 ? c : 0);
     }
processEvent()
bool QLineControl::processEvent (QEvent * ev)
Definition at line 1520 of file qlinecontrol.cpp.
 {
 #ifdef QT_KEYPAD_NAVIGATION
     if (QApplication::keypadNavigationEnabled()) {
         if ((ev->type() == QEvent::KeyPress) || (ev->type() == QEvent::KeyRelease)) {
             QKeyEvent *ke = (QKeyEvent *)ev;
             if (ke->key() == Qt::Key_Back) {
                 if (ke->isAutoRepeat()) {
                     // Swallow it. We don't want back keys running amok.
                     ke->accept();
                     return true;
                 }
                 if ((ev->type() == QEvent::KeyRelease)
                     && !isReadOnly()
                     && m_deleteAllTimer) {
                     killTimer(m_deleteAllTimer);
                     m_deleteAllTimer = 0;
                     backspace();
                     ke->accept();
                     return true;
                 }
             }
         }
     }
 #endif
     switch(ev->type()){
 #ifndef QT_NO_GRAPHICSVIEW
         case QEvent::GraphicsSceneMouseDoubleClick:
         case QEvent::GraphicsSceneMouseMove:
         case QEvent::GraphicsSceneMouseRelease:
         case QEvent::GraphicsSceneMousePress:{
                QGraphicsSceneMouseEvent *gvEv = static_cast<QGraphicsSceneMouseEvent*>(ev);
                QMouseEvent mouse(ev->type(),
                     gvEv->pos().toPoint(), gvEv->button(), gvEv->buttons(), gvEv->modifiers());
                processMouseEvent(&mouse); break;
         }
 #endif
         case QEvent::MouseButtonPress:
         case QEvent::MouseButtonRelease:
         case QEvent::MouseButtonDblClick:
         case QEvent::MouseMove:
             processMouseEvent(static_cast<QMouseEvent*>(ev)); break;
         case QEvent::KeyPress:
         case QEvent::KeyRelease:
             processKeyEvent(static_cast<QKeyEvent*>(ev)); break;
         case QEvent::InputMethod:
             processInputMethodEvent(static_cast<QInputMethodEvent*>(ev)); break;
 #ifndef QT_NO_SHORTCUT
         case QEvent::ShortcutOverride:{
             if (isReadOnly())
                 return false;
             QKeyEvent* ke = static_cast<QKeyEvent*>(ev);
             if (ke == QKeySequence::Copy
                 || ke == QKeySequence::Paste
                 || ke == QKeySequence::Cut
                 || ke == QKeySequence::Redo
                 || ke == QKeySequence::Undo
                 || ke == QKeySequence::MoveToNextWord
                 || ke == QKeySequence::MoveToPreviousWord
                 || ke == QKeySequence::MoveToStartOfDocument
                 || ke == QKeySequence::MoveToEndOfDocument
                 || ke == QKeySequence::SelectNextWord
                 || ke == QKeySequence::SelectPreviousWord
                 || ke == QKeySequence::SelectStartOfLine
                 || ke == QKeySequence::SelectEndOfLine
                 || ke == QKeySequence::SelectStartOfBlock
                 || ke == QKeySequence::SelectEndOfBlock
                 || ke == QKeySequence::SelectStartOfDocument
                 || ke == QKeySequence::SelectAll
                 || ke == QKeySequence::SelectEndOfDocument) {
                 ke->accept();
             } else if (ke->modifiers() == Qt::NoModifier || ke->modifiers() == Qt::ShiftModifier
                        || ke->modifiers() == Qt::KeypadModifier) {
                 if (ke->key() < Qt::Key_Escape) {
                     ke->accept();
                 } else {
                     switch (ke->key()) {
                     case Qt::Key_Delete:
                     case Qt::Key_Home:
                     case Qt::Key_End:
                     case Qt::Key_Backspace:
                     case Qt::Key_Left:
                     case Qt::Key_Right:
                         ke->accept();
                     default:
                         break;
                     }
                 }
             }
         }
 #endif
         default:
             return false;
     }
     return true;
 }
processInputMethodEvent()
void QLineControl::processInputMethodEvent (QInputMethodEvent * event)
Warning
This function is not part of the public interface.
Applies the given input method event event to the text of the line control
Definition at line 487 of file qlinecontrol.cpp.
Referenced by processEvent().
 {
     int priorState = 0;
     int originalSelectionStart = m_selstart;
     int originalSelectionEnd = m_selend;
     bool isGettingInput = !event->commitString().isEmpty()
             || event->preeditString() != preeditAreaText()
             || event->replacementLength() > 0;
     bool cursorPositionChanged = false;
     bool selectionChange = false;
     if (isGettingInput) {
         // If any text is being input, remove selected text.
         priorState = m_undoState;
         if (echoMode() == QLineEdit::PasswordEchoOnEdit && !passwordEchoEditing()) {
             updatePasswordEchoEditing(true);
             m_selstart = 0;
             m_selend = m_text.length();
         }
         removeSelectedText();
     }
     int c = m_cursor; // cursor position after insertion of commit string
     if (event->replacementStart() <= 0)
         c += event->commitString().length() - qMin(-event->replacementStart(), event->replacementLength());
     m_cursor += event->replacementStart();
     if (m_cursor < 0)
         m_cursor = 0;
     // insert commit string
     if (event->replacementLength()) {
         m_selstart = m_cursor;
         m_selend = m_selstart + event->replacementLength();
         removeSelectedText();
     }
     if (!event->commitString().isEmpty()) {
         internalInsert(event->commitString());
         cursorPositionChanged = true;
     }
     m_cursor = qBound(0, c, m_text.length());
     for (int i = 0; i < event->attributes().size(); ++i) {
         const QInputMethodEvent::Attribute &a = event->attributes().at(i);
         if (a.type == QInputMethodEvent::Selection) {
             m_cursor = qBound(0, a.start + a.length, m_text.length());
             if (a.length) {
                 m_selstart = qMax(0, qMin(a.start, m_text.length()));
                 m_selend = m_cursor;
                 if (m_selend < m_selstart) {
                     qSwap(m_selstart, m_selend);
                 }
                 selectionChange = true;
             } else {
                 m_selstart = m_selend = 0;
             }
             cursorPositionChanged = true;
         }
     }
 #ifndef QT_NO_IM
     setPreeditArea(m_cursor, event->preeditString());
 #endif //QT_NO_IM
     const int oldPreeditCursor = m_preeditCursor;
     m_preeditCursor = event->preeditString().length();
     m_hideCursor = false;
     QList<QTextLayout::FormatRange> formats;
     for (int i = 0; i < event->attributes().size(); ++i) {
         const QInputMethodEvent::Attribute &a = event->attributes().at(i);
         if (a.type == QInputMethodEvent::Cursor) {
             m_preeditCursor = a.start;
             m_hideCursor = !a.length;
         } else if (a.type == QInputMethodEvent::TextFormat) {
             QTextCharFormat f = qvariant_cast<QTextFormat>(a.value).toCharFormat();
             if (f.isValid()) {
                 if (f.background().color().alphaF() == 1 && f.background().style() == Qt::SolidPattern) {
                     f.setForeground(f.background().color());
                     f.setBackground(Qt::transparent);
                     f.setUnderlineStyle(QTextCharFormat::SingleUnderline);
                     f.setFontUnderline(true);
                 }
                 QTextLayout::FormatRange o;
                 o.start = a.start + m_cursor;
                 o.length = a.length;
                 o.format = f;
                 formats.append(o);
             }
         }
     }
     m_textLayout.setAdditionalFormats(formats);
     updateDisplayText(/*force*/ true);
     if (originalSelectionStart != m_selstart || originalSelectionEnd != m_selend)
         emit selectionChanged();
     if (cursorPositionChanged)
         emitCursorPositionChanged();
     else if (m_preeditCursor != oldPreeditCursor)
         emit updateMicroFocus();
     if (isGettingInput)
         finishChange(priorState);
     if (selectionChange)
         emit selectionChanged();
 }
processKeyEvent()
void QLineControl::processKeyEvent (QKeyEvent * ev)
Definition at line 1671 of file qlinecontrol.cpp.
Referenced by processEvent().
 {
     bool inlineCompletionAccepted = false;
 #ifndef QT_NO_COMPLETER
     if (m_completer) {
         QCompleter::CompletionMode completionMode = m_completer->completionMode();
         if ((completionMode == QCompleter::PopupCompletion
              || completionMode == QCompleter::UnfilteredPopupCompletion)
             && m_completer->popup()
             && m_completer->popup()->isVisible()) {
             // The following keys are forwarded by the completer to the widget
             // Ignoring the events lets the completer provide suitable default behavior
             switch (event->key()) {
             case Qt::Key_Escape:
                 event->ignore();
                 return;
             case Qt::Key_Enter:
             case Qt::Key_Return:
             case Qt::Key_F4:
 #ifdef QT_KEYPAD_NAVIGATION
             case Qt::Key_Select:
                 if (!QApplication::keypadNavigationEnabled())
                     break;
 #endif
                 m_completer->popup()->hide(); // just hide. will end up propagating to parent
             default:
                 break; // normal key processing
             }
         } else if (completionMode == QCompleter::InlineCompletion) {
             switch (event->key()) {
             case Qt::Key_Enter:
             case Qt::Key_Return:
             case Qt::Key_F4:
 #ifdef QT_KEYPAD_NAVIGATION
             case Qt::Key_Select:
                 if (!QApplication::keypadNavigationEnabled())
                     break;
 #endif
                 if (!m_completer->currentCompletion().isEmpty() && hasSelectedText()
                     && textAfterSelection().isEmpty()) {
                     setText(m_completer->currentCompletion());
                     inlineCompletionAccepted = true;
                 }
             default:
                 break; // normal key processing
             }
         }
     }
 #endif // QT_NO_COMPLETER
     if (event->key() == Qt::Key_Enter || event->key() == Qt::Key_Return) {
         if (hasAcceptableInput() || fixup()) {
             emit accepted();
             emit editingFinished();
         }
         if (inlineCompletionAccepted)
             event->accept();
         else
             event->ignore();
         return;
     }
     if (echoMode() == QLineEdit::PasswordEchoOnEdit
         && !passwordEchoEditing()
         && !isReadOnly()
         && !event->text().isEmpty()
 #ifdef QT_KEYPAD_NAVIGATION
         && event->key() != Qt::Key_Select
         && event->key() != Qt::Key_Up
         && event->key() != Qt::Key_Down
         && event->key() != Qt::Key_Back
 #endif
         && !(event->modifiers() & Qt::ControlModifier)) {
         // Clear the edit and reset to normal echo mode while editing; the
         // echo mode switches back when the edit loses focus
         // ### resets current content.  dubious code; you can
         // navigate with keys up, down, back, and select(?), but if you press
         // "left" or "right" it clears?
         updatePasswordEchoEditing(true);
         clear();
     }
     bool unknown = false;
     bool visual = cursorMoveStyle() == Qt::VisualMoveStyle;
     if (false) {
     }
 #ifndef QT_NO_SHORTCUT
     else if (event == QKeySequence::Undo) {
         if (!isReadOnly())
             undo();
     }
     else if (event == QKeySequence::Redo) {
         if (!isReadOnly())
             redo();
     }
     else if (event == QKeySequence::SelectAll) {
         selectAll();
     }
 #ifndef QT_NO_CLIPBOARD
     else if (event == QKeySequence::Copy) {
         copy();
     }
     else if (event == QKeySequence::Paste) {
         if (!isReadOnly()) {
             QClipboard::Mode mode = QClipboard::Clipboard;
 #ifdef Q_WS_X11
             if (event->modifiers() == (Qt::CTRL | Qt::SHIFT) && event->key() == Qt::Key_Insert)
                 mode = QClipboard::Selection;
 #endif
             paste(mode);
         }
     }
     else if (event == QKeySequence::Cut) {
         if (!isReadOnly()) {
             copy();
             del();
         }
     }
     else if (event == QKeySequence::DeleteEndOfLine) {
         if (!isReadOnly()) {
             setSelection(cursor(), end());
             copy();
             del();
         }
     }
 #endif //QT_NO_CLIPBOARD
     else if (event == QKeySequence::MoveToStartOfLine || event == QKeySequence::MoveToStartOfBlock) {
         home(0);
     }
     else if (event == QKeySequence::MoveToEndOfLine || event == QKeySequence::MoveToEndOfBlock) {
         end(0);
     }
     else if (event == QKeySequence::SelectStartOfLine || event == QKeySequence::SelectStartOfBlock) {
         home(1);
     }
     else if (event == QKeySequence::SelectEndOfLine || event == QKeySequence::SelectEndOfBlock) {
         end(1);
     }
     else if (event == QKeySequence::MoveToNextChar) {
 #if !defined(Q_WS_WIN) || defined(QT_NO_COMPLETER)
         if (hasSelectedText()) {
 #else
         if (hasSelectedText() && m_completer
             && m_completer->completionMode() == QCompleter::InlineCompletion) {
 #endif
             moveCursor(selectionEnd(), false);
         } else {
             cursorForward(0, visual ? 1 : (layoutDirection() == Qt::LeftToRight ? 1 : -1));
         }
     }
     else if (event == QKeySequence::SelectNextChar) {
         cursorForward(1, visual ? 1 : (layoutDirection() == Qt::LeftToRight ? 1 : -1));
     }
     else if (event == QKeySequence::MoveToPreviousChar) {
 #if !defined(Q_WS_WIN) || defined(QT_NO_COMPLETER)
         if (hasSelectedText()) {
 #else
         if (hasSelectedText() && m_completer
             && m_completer->completionMode() == QCompleter::InlineCompletion) {
 #endif
             moveCursor(selectionStart(), false);
         } else {
             cursorForward(0, visual ? -1 : (layoutDirection() == Qt::LeftToRight ? -1 : 1));
         }
     }
     else if (event == QKeySequence::SelectPreviousChar) {
         cursorForward(1, visual ? -1 : (layoutDirection() == Qt::LeftToRight ? -1 : 1));
     }
     else if (event == QKeySequence::MoveToNextWord) {
         if (echoMode() == QLineEdit::Normal)
             layoutDirection() == Qt::LeftToRight ? cursorWordForward(0) : cursorWordBackward(0);
         else
             layoutDirection() == Qt::LeftToRight ? end(0) : home(0);
     }
     else if (event == QKeySequence::MoveToPreviousWord) {
         if (echoMode() == QLineEdit::Normal)
             layoutDirection() == Qt::LeftToRight ? cursorWordBackward(0) : cursorWordForward(0);
         else if (!isReadOnly()) {
             layoutDirection() == Qt::LeftToRight ? home(0) : end(0);
         }
     }
     else if (event == QKeySequence::SelectNextWord) {
         if (echoMode() == QLineEdit::Normal)
             layoutDirection() == Qt::LeftToRight ? cursorWordForward(1) : cursorWordBackward(1);
         else
             layoutDirection() == Qt::LeftToRight ? end(1) : home(1);
     }
     else if (event == QKeySequence::SelectPreviousWord) {
         if (echoMode() == QLineEdit::Normal)
             layoutDirection() == Qt::LeftToRight ? cursorWordBackward(1) : cursorWordForward(1);
         else
             layoutDirection() == Qt::LeftToRight ? home(1) : end(1);
     }
     else if (event == QKeySequence::Delete) {
         if (!isReadOnly())
             del();
     }
     else if (event == QKeySequence::DeleteEndOfWord) {
         if (!isReadOnly()) {
             cursorWordForward(true);
             del();
         }
     }
     else if (event == QKeySequence::DeleteStartOfWord) {
         if (!isReadOnly()) {
             cursorWordBackward(true);
             del();
         }
     }
 #endif // QT_NO_SHORTCUT
     else {
         bool handled = false;
 #ifdef Q_WS_MAC
         if (event->key() == Qt::Key_Up || event->key() == Qt::Key_Down) {
             Qt::KeyboardModifiers myModifiers = (event->modifiers() & ~Qt::KeypadModifier);
             if (myModifiers & Qt::ShiftModifier) {
                 if (myModifiers == (Qt::ControlModifier|Qt::ShiftModifier)
                         || myModifiers == (Qt::AltModifier|Qt::ShiftModifier)
                         || myModifiers == Qt::ShiftModifier) {
                     event->key() == Qt::Key_Up ? home(1) : end(1);
                 }
             } else {
                 if ((myModifiers == Qt::ControlModifier
                      || myModifiers == Qt::AltModifier
                      || myModifiers == Qt::NoModifier)) {
                     event->key() == Qt::Key_Up ? home(0) : end(0);
                 }
             }
             handled = true;
         }
 #endif
         if (event->modifiers() & Qt::ControlModifier) {
             switch (event->key()) {
             case Qt::Key_Backspace:
                 if (!isReadOnly()) {
                     cursorWordBackward(true);
                     del();
                 }
                 break;
 #ifndef QT_NO_COMPLETER
             case Qt::Key_Up:
             case Qt::Key_Down:
                 complete(event->key());
                 break;
 #endif
 #if defined(Q_WS_X11)
             case Qt::Key_E:
                 end(0);
                 break;
             case Qt::Key_U:
                 if (!isReadOnly()) {
                     setSelection(0, text().size());
 #ifndef QT_NO_CLIPBOARD
                     copy();
 #endif
                     del();
                 }
             break;
 #endif
             default:
                 if (!handled)
                     unknown = true;
             }
         } else { // ### check for *no* modifier
             switch (event->key()) {
             case Qt::Key_Backspace:
                 if (!isReadOnly()) {
                     backspace();
 #ifndef QT_NO_COMPLETER
                     complete(Qt::Key_Backspace);
 #endif
                 }
                 break;
 #ifdef QT_KEYPAD_NAVIGATION
             case Qt::Key_Back:
                 if (QApplication::keypadNavigationEnabled() && !event->isAutoRepeat()
                     && !isReadOnly()) {
                     if (text().length() == 0) {
                         setText(m_cancelText);
                         if (passwordEchoEditing())
                             updatePasswordEchoEditing(false);
                         emit editFocusChange(false);
                     } else if (!m_deleteAllTimer) {
                         m_deleteAllTimer = startTimer(750);
                     }
                 } else {
                     unknown = true;
                 }
                 break;
 #endif
             default:
                 if (!handled)
                     unknown = true;
             }
         }
     }
     if (event->key() == Qt::Key_Direction_L || event->key() == Qt::Key_Direction_R) {
         setLayoutDirection((event->key() == Qt::Key_Direction_L) ? Qt::LeftToRight : Qt::RightToLeft);
         unknown = false;
     }
     if (unknown && !isReadOnly()) {
         QString t = event->text();
         if (!t.isEmpty() && t.at(0).isPrint()) {
             insert(t);
 #ifndef QT_NO_COMPLETER
             complete(event->key());
 #endif
             event->accept();
             return;
         }
     }
     if (unknown)
         event->ignore();
     else
         event->accept();
 }
processMouseEvent()
void QLineControl::processMouseEvent (QMouseEvent * ev)
Definition at line 1617 of file qlinecontrol.cpp.
Referenced by processEvent().
 {
     switch (ev->type()) {
         case QEvent::GraphicsSceneMousePress:
         case QEvent::MouseButtonPress:{
             if (m_tripleClickTimer
                 && (ev->pos() - m_tripleClick).manhattanLength()
                     < QApplication::startDragDistance()) {
                 selectAll();
                 return;
             }
             if (ev->button() == Qt::RightButton)
                 return;
             bool mark = ev->modifiers() & Qt::ShiftModifier;
             int cursor = xToPos(ev->pos().x());
             moveCursor(cursor, mark);
             break;
         }
         case QEvent::GraphicsSceneMouseDoubleClick:
         case QEvent::MouseButtonDblClick:
             if (ev->button() == Qt::LeftButton) {
                 selectWordAtPos(xToPos(ev->pos().x()));
                 if (m_tripleClickTimer)
                     killTimer(m_tripleClickTimer);
                 m_tripleClickTimer = startTimer(QApplication::doubleClickInterval());
                 m_tripleClick = ev->pos();
             }
             break;
         case QEvent::GraphicsSceneMouseRelease:
         case QEvent::MouseButtonRelease:
 #ifndef QT_NO_CLIPBOARD
             if (QApplication::clipboard()->supportsSelection()) {
                 if (ev->button() == Qt::LeftButton) {
                     copy(QClipboard::Selection);
                 } else if (!isReadOnly() && ev->button() == Qt::MidButton) {
                     deselect();
                     insert(QApplication::clipboard()->text(QClipboard::Selection));
                 }
             }
 #endif
             break;
         case QEvent::GraphicsSceneMouseMove:
         case QEvent::MouseMove:
             if (ev->buttons() & Qt::LeftButton) {
                 moveCursor(xToPos(ev->pos().x()), true);
             }
             break;
         default:
             break;
     }
 }
redo()
void QLineControl::redo () inline
Definition at line 224 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { internalRedo(); finishChange(); }
removeSelectedText()
void QLineControl::removeSelectedText () private
Also adds the appropriate commands into the undo history.
Warning
This function is not part of the public interface.
removes the currently selected text from the line control.
This function does not call finishChange(), and may leave the text in an invalid state.
Definition at line 879 of file qlinecontrol.cpp.
Referenced by _q_deleteSelected(), backspace(), clear(), del(), insert(), and processInputMethodEvent().
 {
     if (m_selstart < m_selend && m_selend <= (int) m_text.length()) {
         cancelPasswordEchoTimer();
         separate();
         int i ;
         addCommand(Command(SetSelection, m_cursor, 0, m_selstart, m_selend));
         if (m_selstart <= m_cursor && m_cursor < m_selend) {
             // cursor is within the selection. Split up the commands
             // to be able to restore the correct cursor position
             for (i = m_cursor; i >= m_selstart; --i)
                 addCommand (Command(DeleteSelection, i, m_text.at(i), -1, 1));
             for (i = m_selend - 1; i > m_cursor; --i)
                 addCommand (Command(DeleteSelection, i - m_cursor + m_selstart - 1, m_text.at(i), -1, -1));
         } else {
             for (i = m_selend-1; i >= m_selstart; --i)
                 addCommand (Command(RemoveSelection, i, m_text.at(i), -1, -1));
         }
         if (m_maskData) {
             m_text.replace(m_selstart, m_selend - m_selstart,  clearString(m_selstart, m_selend - m_selstart));
             for (int i = 0; i < m_selend - m_selstart; ++i)
                 addCommand(Command(Insert, m_selstart + i, m_text.at(m_selstart + i), -1, -1));
         } else {
             m_text.remove(m_selstart, m_selend - m_selstart);
         }
         if (m_cursor > m_selstart)
             m_cursor -= qMin(m_cursor, m_selend) - m_selstart;
         internalDeselect();
         m_textDirty = true;
     }
 }
removeSelection()
void QLineControl::removeSelection () inline
Definition at line 147 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::drag().
     {
         int priorState = m_undoState;
         removeSelectedText();
         finishChange(priorState);
     }
resetCursorBlinkTimer()
void QLineControl::resetCursorBlinkTimer ()
Definition at line 1490 of file qlinecontrol.cpp.
 {
     if (m_blinkPeriod == 0 || m_blinkTimer == 0)
         return;
     killTimer(m_blinkTimer);
     m_blinkTimer = startTimer(m_blinkPeriod / 2);
     m_blinkStatus = 1;
 }
resetInputContext
void QLineControl::resetInputContext () signal
Referenced by _q_deleteSelected(), and internalSetText().
selectAll()
void QLineControl::selectAll () inline
Definition at line 219 of file qlinecontrol_p.h.
Referenced by processKeyEvent(), and processMouseEvent().
 { m_selstart = m_selend = m_cursor = 0; moveCursor(m_text.length(), true); }
selectedText()
QString QLineControl::selectedText () const inline
Definition at line 133 of file qlinecontrol_p.h.
Referenced by copy(), and QLineEditPrivate::drag().
 { return hasSelectedText() ? m_text.mid(m_selstart, m_selend - m_selstart) : QString(); }
selectionChanged
void QLineControl::selectionChanged () signal
Referenced by copy(), finishChange(), moveCursor(), processInputMethodEvent(), and setSelection().
selectionEnd()
int QLineControl::selectionEnd () const inline
Definition at line 138 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { return hasSelectedText() ? m_selend : -1; }
selectionStart()
int QLineControl::selectionStart () const inline
Definition at line 137 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { return hasSelectedText() ? m_selstart : -1; }
selectWordAtPos()
void QLineControl::selectWordAtPos (int cursor)
Sets the selection to cover the word at the given cursor position.
Warning
This function is not part of the public interface.
The word boundaries are defined by the behavior of QTextLayout::SkipWords cursor mode.
Definition at line 652 of file qlinecontrol.cpp.
Referenced by processMouseEvent().
 {
     int next = cursor + 1;
     if(next > end())
         --next;
     int c = m_textLayout.previousCursorPosition(next, QTextLayout::SkipWords);
     moveCursor(c, false);
     // ## text layout should support end of words.
     int end = m_textLayout.nextCursorPosition(c, QTextLayout::SkipWords);
     while (end > cursor && m_text[end-1].isSpace())
         --end;
     moveCursor(end, true);
 }
separate()
void QLineControl::separate () inline private
Definition at line 414 of file qlinecontrol_p.h.
Referenced by _q_deleteSelected(), clear(), moveCursor(), paste(), and removeSelectedText().
 { m_separator = true; }
setCancelText()
void QLineControl::setCancelText (const QString & text) inline
Definition at line 318 of file qlinecontrol_p.h.
 { m_cancelText = text; }
setCompleter()
void QLineControl::setCompleter (const QCompleter * c) inline
Definition at line 253 of file qlinecontrol_p.h.
 { m_completer = const_cast<QCompleter*>(c); }
setCursorBlinkPeriod()
void QLineControl::setCursorBlinkPeriod (int msec)
Definition at line 1472 of file qlinecontrol.cpp.
 {
     if (msec == m_blinkPeriod)
         return;
     if (m_blinkTimer) {
         killTimer(m_blinkTimer);
     }
     if (msec) {
         m_blinkTimer = startTimer(msec / 2);
         m_blinkStatus = 1;
     } else {
         m_blinkTimer = 0;
         if (m_blinkStatus == 1)
             emit updateNeeded(inputMask().isEmpty() ? cursorRect() : QRect());
     }
     m_blinkPeriod = msec;
 }
setCursorMoveStyle()
void QLineControl::setCursorMoveStyle (Qt::CursorMoveStyle style) inline
Definition at line 169 of file qlinecontrol_p.h.
 { m_textLayout.setCursorMoveStyle(style); }
setCursorPosition()
void QLineControl::setCursorPosition (int pos) inline
Definition at line 258 of file qlinecontrol_p.h.
 { if (pos <= m_text.length()) moveCursor(qMax(0, pos)); }
setCursorWidth()
void QLineControl::setCursorWidth (int value) inline
Definition at line 166 of file qlinecontrol_p.h.
 { m_cursorWidth = value; }
setEchoMode()
void QLineControl::setEchoMode (uint mode) inline
Definition at line 228 of file qlinecontrol_p.h.
     {
         cancelPasswordEchoTimer();
         m_echoMode = mode;
         m_passwordEchoEditing = false;
         updateDisplayText();
     }
setFont()
void QLineControl::setFont (const QFont & font) inline
Definition at line 307 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::init().
 { m_textLayout.setFont(font); updateDisplayText(); }
setInputMask()
void QLineControl::setInputMask (const QString & mask) inline
Definition at line 264 of file qlinecontrol_p.h.
     {
         parseInputMask(mask);
         if (m_maskData)
             moveCursor(nextMaskBlank(0));
     }
setLayoutDirection()
void QLineControl::setLayoutDirection (Qt::LayoutDirection direction) inline
Definition at line 299 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
     {
         if (direction != m_layoutDirection) {
             m_layoutDirection = direction;
             updateDisplayText();
         }
     }
setMaxLength()
void QLineControl::setMaxLength (int maxLength) inline
Definition at line 237 of file qlinecontrol_p.h.
     {
         if (m_maskData)
             return;
         m_maxLength = maxLength;
         setText(m_text);
     }
setModified()
void QLineControl::setModified (bool modified) inline
Definition at line 121 of file qlinecontrol_p.h.
 { m_modifiedState = modified ? -1 : m_undoState; }
setPalette()
void QLineControl::setPalette (const QPalette & p) inline
Definition at line 321 of file qlinecontrol_p.h.
 { m_palette = p; }
setPasswordCharacter()
void QLineControl::setPasswordCharacter (const QChar & character) inline
Definition at line 289 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::init().
 { m_passwordCharacter = character; updateDisplayText(); }
setPreeditArea()
void QLineControl::setPreeditArea (int cursor, const QString & text) inline
Definition at line 274 of file qlinecontrol_p.h.
Referenced by processInputMethodEvent().
 { m_textLayout.setPreeditArea(cursor, text); }
setReadOnly()
void QLineControl::setReadOnly (bool enable) inline
Definition at line 206 of file qlinecontrol_p.h.
 { m_readOnly = enable; }
setSelection()
void QLineControl::setSelection (int start, int length)
Sets length characters from the given start position as selected.
Warning
This function is not part of the public interface.
The given start position must be within the current text for the line control. If length characters cannot be selected, then the selection will extend to the end of the current text.
Definition at line 298 of file qlinecontrol.cpp.
Referenced by processKeyEvent().
 {
     if(start < 0 || start > (int)m_text.length()){
         qWarning("QLineControl::setSelection: Invalid start position");
         return;
     }
     if (length > 0) {
         if (start == m_selstart && start + length == m_selend && m_cursor == m_selend)
             return;
         m_selstart = start;
         m_selend = qMin(start + length, (int)m_text.length());
         m_cursor = m_selend;
     } else if (length < 0){
         if (start == m_selend && start + length == m_selstart && m_cursor == m_selstart)
             return;
         m_selstart = qMax(start + length, 0);
         m_selend = start;
         m_cursor = m_selstart;
     } else if (m_selstart != m_selend) {
         m_selstart = 0;
         m_selend = 0;
         m_cursor = start;
     } else {
         m_cursor = start;
         emitCursorPositionChanged();
         return;
     }
     emit selectionChanged();
     emitCursorPositionChanged();
 }
setText()
void QLineControl::setText (const QString & txt) inline
Definition at line 213 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { internalSetText(txt, -1, false); }
setValidator()
void QLineControl::setValidator (const QValidator * v) inline
Definition at line 247 of file qlinecontrol_p.h.
 { m_validator = const_cast<QValidator*>(v); }
start()
int QLineControl::start () const inline
Definition at line 154 of file qlinecontrol_p.h.
Referenced by advanceToEnabledItem(), and setSelection().
 { return 0; }
stripString()
QString QLineControl::stripString (const QString & str) const private
Strips blank parts of the input in a QLineControl when an inputMask is set, separators are still included.
Warning
This function is not part of the public interface.
Typically "127.0__.0__.1__" becomes "127.0.0.1".
Definition at line 1245 of file qlinecontrol.cpp.
 {
     if (!m_maskData)
         return str;
     QString s;
     int end = qMin(m_maxLength, (int)str.length());
     for (int i = 0; i < end; ++i)
         if (m_maskData[i].separator)
             s += m_maskData[i].maskChar;
         else
             if (str[i] != m_blank)
                 s += str[i];
     return s;
 }
text()
QString QLineControl::text () const inline
Definition at line 208 of file qlinecontrol_p.h.
Referenced by QLineEditPrivate::_q_completionHighlighted(), complete(), finishChange(), processKeyEvent(), and processMouseEvent().
     {
         QString res = m_maskData ? stripString(m_text) : m_text;
         return (res.isNull() ? QString::fromLatin1("") : res);
     }
textAfterSelection()
QString QLineControl::textAfterSelection () const inline
Definition at line 135 of file qlinecontrol_p.h.
Referenced by complete(), and processKeyEvent().
 { return hasSelectedText() ? m_text.mid(m_selend) : QString(); }
textBeforeSelection()
QString QLineControl::textBeforeSelection () const inline
Definition at line 134 of file qlinecontrol_p.h.
Referenced by complete().
 { return hasSelectedText() ? m_text.left(m_selstart) : QString(); }
textChanged
void QLineControl::textChanged (const QString &) signal
Referenced by finishChange().
textEdited
void QLineControl::textEdited (const QString &) signal
Referenced by finishChange().
timerEvent()
void QLineControl::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 1499 of file qlinecontrol.cpp.
 {
     if (event->timerId() == m_blinkTimer) {
         m_blinkStatus = !m_blinkStatus;
         emit updateNeeded(inputMask().isEmpty() ? cursorRect() : QRect());
     } else if (event->timerId() == m_deleteAllTimer) {
         killTimer(m_deleteAllTimer);
         m_deleteAllTimer = 0;
         clear();
     } else if (event->timerId() == m_tripleClickTimer) {
         killTimer(m_tripleClickTimer);
         m_tripleClickTimer = 0;
 #ifdef QT_GUI_PASSWORD_ECHO_DELAY
     } else if (event->timerId() == m_passwordEchoTimer) {
         killTimer(m_passwordEchoTimer);
         m_passwordEchoTimer = 0;
         updateDisplayText();
 #endif
     }
 }
undo()
void QLineControl::undo () inline
Definition at line 223 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
 { internalUndo(); finishChange(-1, true); }
updateDisplayText()
void QLineControl::updateDisplayText (bool forceUpdate = false) private
Warning
This function is not part of the public interface.
Updates the display text based of the current edit text If the text has changed will emit displayTextChanged()
Definition at line 87 of file qlinecontrol.cpp.
Referenced by finishChange(), init(), moveCursor(), processInputMethodEvent(), timerEvent(), and updatePasswordEchoEditing().
 {
     QString orig = m_textLayout.text();
     QString str;
     if (m_echoMode == QLineEdit::NoEcho)
         str = QString::fromLatin1("");
     else
         str = m_text;
     if (m_echoMode == QLineEdit::Password) {
         str.fill(m_passwordCharacter);
 #ifdef QT_GUI_PASSWORD_ECHO_DELAY
         if (m_passwordEchoTimer != 0 && m_cursor > 0 && m_cursor <= m_text.length()) {
             int cursor = m_cursor - 1;
             QChar uc = m_text.at(cursor);
             str[cursor] = uc;
             if (cursor > 0 && uc.unicode() >= 0xdc00 && uc.unicode() < 0xe000) {
                 // second half of a surrogate, check if we have the first half as well,
                 // if yes restore both at once
                 uc = m_text.at(cursor - 1);
                 if (uc.unicode() >= 0xd800 && uc.unicode() < 0xdc00)
                     str[cursor - 1] = uc;
             }
         }
 #endif
     } else if (m_echoMode == QLineEdit::PasswordEchoOnEdit && !m_passwordEchoEditing) {
         str.fill(m_passwordCharacter);
     }
     // replace certain non-printable characters with spaces (to avoid
     // drawing boxes when using fonts that don't have glyphs for such
     // characters)
     QChar* uc = str.data();
     for (int i = 0; i < (int)str.length(); ++i) {
         if ((uc[i] < 0x20 && uc[i] != 0x09)
             || uc[i] == QChar::LineSeparator
             || uc[i] == QChar::ParagraphSeparator
             || uc[i] == QChar::ObjectReplacementCharacter)
             uc[i] = QChar(0x0020);
     }
     m_textLayout.setText(str);
     QTextOption option;
     option.setTextDirection(m_layoutDirection);
     option.setFlags(QTextOption::IncludeTrailingSpaces);
     m_textLayout.setTextOption(option);
     m_textLayout.beginLayout();
     QTextLine l = m_textLayout.createLine();
     m_textLayout.endLayout();
     m_ascent = qRound(l.ascent());
     if (str != orig || forceUpdate)
         emit displayTextChanged(str);
 }
updateMicroFocus
void QLineControl::updateMicroFocus () signal
Referenced by finishChange(), and processInputMethodEvent().
updateNeeded
void QLineControl::updateNeeded (const QRect &) signal
Referenced by setCursorBlinkPeriod(), and timerEvent().
updatePasswordEchoEditing()
void QLineControl::updatePasswordEchoEditing (bool editing)
Sets the password echo editing to editing.
Warning
This function is not part of the public interface.
If password echo editing is true, then the text of the password is displayed even if the echo mode is set to QLineEdit::PasswordEchoOnEdit. Password echoing editing does not affect other echo modes.
Definition at line 372 of file qlinecontrol.cpp.
Referenced by processInputMethodEvent(), processKeyEvent(), and QLineEditPrivate::updatePasswordEchoEditing().
 {
     cancelPasswordEchoTimer();
     m_passwordEchoEditing = editing;
     updateDisplayText();
 }
validator()
const QValidator* QLineControl::validator () const inline
Definition at line 246 of file qlinecontrol_p.h.
 { return m_validator; }
width()
int QLineControl::width () const inline
Definition at line 126 of file qlinecontrol_p.h.
 { return qRound(m_textLayout.lineAt(0).width()) + 1; }
xToPos()
int QLineControl::xToPos (int x, QTextLine::CursorPosition betweenOrOn = QTextLine::CursorBetweenCharacters) const
Returns the cursor position of the given x pixel value in relation to the displayed text.
Warning
This function is not part of the public interface.
The given betweenOrOn specified what kind of cursor position is requested.
Definition at line 389 of file qlinecontrol.cpp.
Referenced by processMouseEvent(), and QLineEditPrivate::xToPos().
 {
     return m_textLayout.lineAt(0).xToCursor(x, betweenOrOn);
 }
Properties
m_ascent
int QLineControl::m_ascent private
Definition at line 370 of file qlinecontrol_p.h.
Referenced by updateDisplayText().
m_blank
QChar QLineControl::m_blank private
Definition at line 397 of file qlinecontrol_p.h.
Referenced by clearString(), isValidInput(), parseInputMask(), and stripString().
m_blinkPeriod
int QLineControl::m_blinkPeriod private
Definition at line 367 of file qlinecontrol_p.h.
Referenced by draw(), resetCursorBlinkTimer(), and setCursorBlinkPeriod().
m_blinkStatus
uint QLineControl::m_blinkStatus private
Definition at line 366 of file qlinecontrol_p.h.
Referenced by draw(), resetCursorBlinkTimer(), setCursorBlinkPeriod(), and timerEvent().
m_blinkTimer
int QLineControl::m_blinkTimer private
Definition at line 368 of file qlinecontrol_p.h.
Referenced by resetCursorBlinkTimer(), setCursorBlinkPeriod(), and timerEvent().
m_cancelText
QString QLineControl::m_cancelText private
Definition at line 376 of file qlinecontrol_p.h.
Referenced by processKeyEvent().
m_completer
QPointer<QCompleter> QLineControl::m_completer private
Definition at line 385 of file qlinecontrol_p.h.
Referenced by advanceToEnabledItem(), complete(), and processKeyEvent().
m_cursor
int QLineControl::m_cursor private
Definition at line 354 of file qlinecontrol_p.h.
Referenced by addCommand(), backspace(), cursorRect(), del(), draw(), emitCursorPositionChanged(), finishChange(), fixup(), hasAcceptableInput(), init(), internalDelete(), internalInsert(), internalRedo(), internalSetText(), internalUndo(), moveCursor(), processInputMethodEvent(), removeSelectedText(), setSelection(), and updateDisplayText().
m_cursorWidth
int QLineControl::m_cursorWidth private
Definition at line 356 of file qlinecontrol_p.h.
Referenced by cursorRect(), and draw().
m_deleteAllTimer
int QLineControl::m_deleteAllTimer private
Definition at line 369 of file qlinecontrol_p.h.
Referenced by processEvent(), processKeyEvent(), and timerEvent().
m_dragEnabled
uint QLineControl::m_dragEnabled private
Definition at line 361 of file qlinecontrol_p.h.
m_echoMode
uint QLineControl::m_echoMode private
Definition at line 362 of file qlinecontrol_p.h.
Referenced by copy(), internalInsert(), internalUndo(), isRedoAvailable(), isUndoAvailable(), and updateDisplayText().
m_hideCursor
uint QLineControl::m_hideCursor private
Definition at line 358 of file qlinecontrol_p.h.
Referenced by draw(), and processInputMethodEvent().
m_history
QVector<Command> QLineControl::m_history private
Definition at line 411 of file qlinecontrol_p.h.
Referenced by addCommand(), finishChange(), internalRedo(), internalSetText(), internalUndo(), isRedoAvailable(), and isUndoAvailable().
m_inputMask
QString QLineControl::m_inputMask private
Definition at line 396 of file qlinecontrol_p.h.
Referenced by parseInputMask().
m_lastCursorPos
int QLineControl::m_lastCursorPos private
Definition at line 372 of file qlinecontrol_p.h.
Referenced by emitCursorPositionChanged(), and finishChange().
m_layoutDirection
Qt::LayoutDirection QLineControl::m_layoutDirection private
Definition at line 357 of file qlinecontrol_p.h.
Referenced by updateDisplayText().
m_maskData
MaskInputData* QLineControl::m_maskData private
Definition at line 398 of file qlinecontrol_p.h.
Referenced by backspace(), clearString(), findInMask(), hasAcceptableInput(), internalDelete(), internalInsert(), internalSetText(), maskString(), moveCursor(), parseInputMask(), removeSelectedText(), and stripString().
m_maxLength
int QLineControl::m_maxLength private
Definition at line 371 of file qlinecontrol_p.h.
Referenced by clearString(), findInMask(), hasAcceptableInput(), internalInsert(), internalSetText(), maskString(), parseInputMask(), and stripString().
m_modifiedState
int QLineControl::m_modifiedState private
Definition at line 409 of file qlinecontrol_p.h.
Referenced by finishChange(), and internalSetText().
m_palette
QPalette QLineControl::m_palette private
Definition at line 353 of file qlinecontrol_p.h.
Referenced by draw().
m_passwordCharacter
QChar QLineControl::m_passwordCharacter private
Definition at line 433 of file qlinecontrol_p.h.
Referenced by updateDisplayText().
m_passwordEchoEditing
bool QLineControl::m_passwordEchoEditing private
Definition at line 432 of file qlinecontrol_p.h.
Referenced by updateDisplayText(), and updatePasswordEchoEditing().
m_preeditCursor
int QLineControl::m_preeditCursor private
Definition at line 355 of file qlinecontrol_p.h.
Referenced by cursorRect(), draw(), and processInputMethodEvent().
m_readOnly
uint QLineControl::m_readOnly private
Definition at line 360 of file qlinecontrol_p.h.
Referenced by isRedoAvailable(), and isUndoAvailable().
m_selDirty
uint QLineControl::m_selDirty private
Definition at line 364 of file qlinecontrol_p.h.
Referenced by finishChange(), and moveCursor().
m_selend
int QLineControl::m_selend private
Definition at line 418 of file qlinecontrol_p.h.
Referenced by addCommand(), clear(), draw(), internalDelete(), internalInsert(), internalRedo(), internalUndo(), moveCursor(), processInputMethodEvent(), removeSelectedText(), and setSelection().
m_selstart
int QLineControl::m_selstart private
Definition at line 417 of file qlinecontrol_p.h.
Referenced by addCommand(), clear(), draw(), internalDelete(), internalInsert(), internalRedo(), internalUndo(), moveCursor(), processInputMethodEvent(), removeSelectedText(), and setSelection().
m_separator
uint QLineControl::m_separator private
Definition at line 359 of file qlinecontrol_p.h.
Referenced by addCommand().
m_text
QString QLineControl::m_text private
Definition at line 352 of file qlinecontrol_p.h.
Referenced by backspace(), clear(), finishChange(), fixup(), init(), internalDelete(), internalInsert(), internalRedo(), internalSetText(), internalUndo(), maskString(), parseInputMask(), processInputMethodEvent(), removeSelectedText(), selectWordAtPos(), setSelection(), and updateDisplayText().
m_textDirty
uint QLineControl::m_textDirty private
Definition at line 363 of file qlinecontrol_p.h.
Referenced by finishChange(), internalDelete(), internalInsert(), internalRedo(), internalSetText(), internalUndo(), and removeSelectedText().
m_textLayout
QTextLayout QLineControl::m_textLayout private
Definition at line 430 of file qlinecontrol_p.h.
Referenced by cursorRect(), del(), draw(), processInputMethodEvent(), selectWordAtPos(), updateDisplayText(), and xToPos().
m_transactions
QList<int> QLineControl::m_transactions private
Definition at line 373 of file qlinecontrol_p.h.
Referenced by finishChange().
m_tripleClick
QPoint QLineControl::m_tripleClick private
Definition at line 374 of file qlinecontrol_p.h.
Referenced by processMouseEvent().
m_tripleClickTimer
int QLineControl::m_tripleClickTimer private
Definition at line 375 of file qlinecontrol_p.h.
Referenced by processMouseEvent(), and timerEvent().
m_undoState
int QLineControl::m_undoState private
Definition at line 410 of file qlinecontrol_p.h.
Referenced by _q_deleteSelected(), addCommand(), backspace(), clear(), del(), finishChange(), insert(), internalRedo(), internalSetText(), internalUndo(), isRedoAvailable(), isUndoAvailable(), and processInputMethodEvent().
m_validator
QPointer<QValidator> QLineControl::m_validator private
Definition at line 383 of file qlinecontrol_p.h.
Referenced by finishChange(), fixup(), and hasAcceptableInput().
m_validInput
uint QLineControl::m_validInput private
Definition at line 365 of file qlinecontrol_p.h.
Referenced by finishChange().
The documentation for this class was generated from the following files:
/src/gui/widgets/qlinecontrol_p.h
/src/gui/widgets/qlinecontrol.cpp