Qt 4.8: QSettingsGroup Class Reference
QSettingsGroup Class Reference
#include <qsettings_p.h>
Public Functions
int arraySizeGuess () const
bool isArray () const
QString name () const
QSettingsGroup ()
QSettingsGroup (const QString &s)
QSettingsGroup (const QString &s, bool guessArraySize)
void setArrayIndex (int i)
QString toString () const
Public Variables
int maxNum
int num
QString str
Detailed Description
Definition at line 117 of file qsettings_p.h.
Constructors and Destructors
QSettingsGroup() [1/3]
QSettingsGroup::QSettingsGroup () inline
Definition at line 120 of file qsettings_p.h.
         : num(-1), maxNum(-1) {}
QSettingsGroup() [2/3]
QSettingsGroup::QSettingsGroup (const QString & s) inline
Definition at line 122 of file qsettings_p.h.
         : str(s), num(-1), maxNum(-1) {}
QSettingsGroup() [3/3]
QSettingsGroup::QSettingsGroup (const QString & s, bool guessArraySize) inline
Definition at line 124 of file qsettings_p.h.
         : str(s), num(0), maxNum(guessArraySize ? 0 : -1) {}
Functions
arraySizeGuess()
int QSettingsGroup::arraySizeGuess () const inline
Definition at line 130 of file qsettings_p.h.
Referenced by QSettings::endArray().
 { return maxNum; }
isArray()
bool QSettingsGroup::isArray () const inline
Definition at line 129 of file qsettings_p.h.
Referenced by QSettings::endArray(), and QSettings::endGroup().
 { return num != -1; }
name()
QString QSettingsGroup::name () const inline
Definition at line 127 of file qsettings_p.h.
Referenced by QSettingsPrivate::beginGroupOrArray(), and QSettings::endArray().
 { return str; }
setArrayIndex()
void QSettingsGroup::setArrayIndex (int i) inline
Definition at line 131 of file qsettings_p.h.
Referenced by QSettings::setArrayIndex().
     { num = i + 1; if (maxNum != -1 && num > maxNum) maxNum = num; }
toString()
QString QSettingsGroup::toString () const inline
Definition at line 139 of file qsettings_p.h.
Referenced by QSettings::endArray(), QSettings::endGroup(), and QSettings::setArrayIndex().
 {
     QString result;
     result = str;
     if (num > 0) {
         result += QLatin1Char('/');
         result += QString::number(num);
     }
     return result;
 }
Properties
maxNum
int QSettingsGroup::maxNum
Definition at line 136 of file qsettings_p.h.
num
int QSettingsGroup::num
Definition at line 135 of file qsettings_p.h.
str
QString QSettingsGroup::str
Definition at line 134 of file qsettings_p.h.
The documentation for this class was generated from the following file:
/src/corelib/io/qsettings_p.h