Qt 4.8: QPatternist::ResourceLoader Class Reference
QPatternist::ResourceLoader Class Reference
Responsible for handling requests for opening files and node collections.
#include <qresourceloader_p.h>
Public Types
typedef QExplicitlySharedDataPointer< ResourceLoader > Ptr
enum Usage { MayUse, WillUse }
Public Functions
virtual SequenceType::Ptr announceCollection (const QUrl &uri)
May be called by the compilation framework at compile time to report that an node collection referenced by uri will be loaded at runtime.
virtual SequenceType::Ptr announceDocument (const QUrl &uri, const Usage usageHint)
May be called by the compilation framework at compile time to report that an XML document referenced by uri will be loaded at runtime.
virtual ItemType::Ptr announceUnparsedText (const QUrl &uri)
May be called by the compilation framework at compile time to report that an unparsed text(plain text) file referenced by uri will be loaded at runtime.
virtual void clear (const QUrl &uri)
Asks to unload uri from its document pool, such that a subsequent request will require a new read.
virtual bool isDocumentAvailable (const QUrl &uri)
Calls to this function are generated by calls to the fn:doc-available() function.
virtual bool isUnparsedTextAvailable (const QUrl &uri, const QString &encoding)
Calls to this function are generated by calls to the fn:unparsed-text-available() function.
virtual Item::Iterator::Ptr openCollection (const QUrl &uri)
Calls to this function are generated by calls to the fn:collection() function.
virtual Item openDocument (const QUrl &uri, const ReportContext::Ptr &context)
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
virtual Item openUnparsedText (const QUrl &uri, const QString &encoding, const ReportContext::Ptr &context, const SourceLocationReflection *const where)
Calls to this function are generated by calls to the fn:unparsed-text() function.
ResourceLoader ()
virtual ~ResourceLoader ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Detailed Description
Responsible for handling requests for opening files and node collections.
ResourceLoader is a callback used for opening files, requested via the functions fn:document() and fn:unparsed-text(); and node collections, requested via fn:collection(). Patternist uses the ResourceLoader at compile time, via StaticContext::resourceLoader(), and at runtime, via DynamicContext::resourceLoader().
The ResourceLoader takes care of loading "external resources" in a way specific to the data model Patternist is using. For example, perhaps the opening of documents should pass a security policy, or a collection should map to nodes in a virtual filesystem or a database.
From Patternist's perspective, the ResourceLoader provides two things:
At compile time, it calls announceDocument(), announceCollection() and announceUnparsedText() if it knows the URIs at compile time in order to retrieve the static types of the data the URIs maps to. This is used for more efficiently compiling the query and to better report errors at compile time.
To open document and node collections at runtime.
From the user's or the data model's perspective, the ResourceLoader most notably provides a hint to what resources a query will load at runtime, and therefore provides an opportunity to prepare in advance for that. For example, between the compile and runtime stage, the ResourceLoader sub-class can be asked to pre-load documents in an asynchronous and simultaneous way, such that the runtime stage is faster and doesn't freeze a graphical interface.
The announce functions are not guaranteed to be called. The loading functions can be called with an URI that an announce function hasn't been called with.
The default implementations of ResourceLoader's virtual functions all signals that no resources can be loaded. This means ResourceLoader must be sub-classed, in order to be able to load resources.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 106 of file qresourceloader_p.h.
Typedefs
Ptr
typedef QExplicitlySharedDataPointer<ResourceLoader> QPatternist::ResourceLoader::Ptr
Definition at line 128 of file qresourceloader_p.h.
Enumerations
Usage
enum QPatternist::ResourceLoader::Usage
Enumerator
MayUse
Communicates that the URI may be used during query evaluation. For example, zero times or very many times.
Typically this hint is given when the URI is available at compile-time, but it is used inside a conditional statement whose branching cannot be determined at compile time.
WillUse
Communicates that the URI will always be used at query evaluation.
Definition at line 109 of file qresourceloader_p.h.
         {
             MayUse,
             WillUse
         };
Constructors and Destructors
ResourceLoader()
QPatternist::ResourceLoader::ResourceLoader () inline
Definition at line 129 of file qresourceloader_p.h.
 {}
~ResourceLoader()
ResourceLoader::~ResourceLoader () virtual
Definition at line 51 of file qresourceloader.cpp.
 {
 }
Functions
announceCollection()
SequenceType::Ptr ResourceLoader::announceCollection (const QUrl & uri) virtual
May be called by the compilation framework at compile time to report that an node collection referenced by uri will be loaded at runtime.
This function can be called an arbitrary amount of times for the same URI. How many times it is called for a URI has no meaning(beyond the first call, that is). For what queries the compilation framework can determine what always will be loaded is generally undefined. It depends on factors such as how simple the query is what information that is statically available and subsequently what optimizations that can apply.
Calls to this function are generated by calls to the fn:collection() function.
Note
This function is responsible for execution stability. Subsequent calls to this function with the same URI should result in QXmlNodeModelIndex instances that have the same identity. However, in some cases this stability is not of interest, see the specification for details.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
null if the ResourceLoader can determine at this stage that no document referenced by uri will ever be possible to load.
The appropriate sequence type if loading uri succeeds at runtime. This must be CommonSequenceTypes::zeroOrMoreNodes or a sequence type that is a sub type of it.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.6 fn:collection
Reimplemented in QPatternist::ResourceDelegator.
Definition at line 121 of file qresourceloader.cpp.
Referenced by QPatternist::ResourceDelegator::announceCollection().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     return SequenceType::Ptr();
 }
announceDocument()
SequenceType::Ptr ResourceLoader::announceDocument (const QUrl & uri, const Usage usageHint) virtual
May be called by the compilation framework at compile time to report that an XML document referenced by uri will be loaded at runtime.
This function can be called an arbitrary amount of times for the same URI, but different usageHint values. How many times it is called for a URI has no meaning(beyond the first call, that is). For what queries the compilation framework can determine what always will be loaded is generally undefined. It depends on factors such as the complexity of the query, what information that is statically available and subsequently what optimizations that can be applied.
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
usageHint A hint to how the URI will be used.
Returns
null if the ResourceLoader can determine at this stage that no document referenced by uri will ever be possible to load.
The appropriate sequence type if loading uri succeeds at runtime. This must be CommonSequenceTypes::zeroOrOneDocument, CommonSequenceTypes::exactlyOneDocument or a sequence type that is a sub type of it.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.4 fn:doc
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Reimplemented in QPatternist::AccelTreeResourceLoader, and QPatternist::ResourceDelegator.
Definition at line 97 of file qresourceloader.cpp.
Referenced by QPatternist::ResourceDelegator::announceDocument(), and QPatternist::DocFN::typeCheck().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     return SequenceType::Ptr();
 }
announceUnparsedText()
ItemType::Ptr ResourceLoader::announceUnparsedText (const QUrl & uri) virtual
May be called by the compilation framework at compile time to report that an unparsed text(plain text) file referenced by uri will be loaded at runtime.
This function can be called an arbitrary amount of times for the same URI. How many times it is called for a URI has no meaning(beyond the first call, that is). For what queries the compilation framework can determine what always will be loaded is generally undefined. It depends on factors such as how simple the query is what information that is statically available and subsequently what optimizations that can apply.
Calls to this function are generated by calls to the fn:unparsed-text() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Returns
null if no unparsed file can be loaded for uri
The item type that the value loaded by uri will be an instance of. This is typically xs:string
Reimplemented in QPatternist::ResourceDelegator.
Definition at line 65 of file qresourceloader.cpp.
Referenced by QPatternist::ResourceDelegator::announceUnparsedText().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     return ItemType::Ptr();
 }
clear()
void ResourceLoader::clear (const QUrl & uri) virtual
Asks to unload uri from its document pool, such that a subsequent request will require a new read.
The default implementation does nothing.
Reimplemented in QPatternist::AccelTreeResourceLoader.
Definition at line 129 of file qresourceloader.cpp.
 {
     Q_UNUSED(uri);
 }
isDocumentAvailable()
bool ResourceLoader::isDocumentAvailable (const QUrl & uri) virtual
Calls to this function are generated by calls to the fn:doc-available() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
true if calling openDocument() while passing uri will successfully load the document.
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.5 fn:doc-available
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Reimplemented in QPatternist::AccelTreeResourceLoader, and QPatternist::ResourceDelegator.
Definition at line 105 of file qresourceloader.cpp.
Referenced by QPatternist::DocAvailableFN::evaluateEBV(), and QPatternist::ResourceDelegator::isDocumentAvailable().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     return false;
 }
isUnparsedTextAvailable()
bool ResourceLoader::isUnparsedTextAvailable (const QUrl & uri, const QString & encoding) virtual
Calls to this function are generated by calls to the fn:unparsed-text-available() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
Returns
true if calling openUnparsedText() while passing uri will successfully load the document.
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Reimplemented in QPatternist::AccelTreeResourceLoader, and QPatternist::ResourceDelegator.
Definition at line 55 of file qresourceloader.cpp.
Referenced by QPatternist::UnparsedTextAvailableFN::evaluateEBV(), and QPatternist::ResourceDelegator::isUnparsedTextAvailable().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     Q_UNUSED(encoding);
     return false;
 }
openCollection()
Item::Iterator::Ptr ResourceLoader::openCollection (const QUrl & uri) virtual
Calls to this function are generated by calls to the fn:collection() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
See also
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.6 fn:collection
Returns
null if no node collection can be loaded for uri
An QAbstractXmlForwardIterator representing the content identified by uri. Remember that the content of the QAbstractXmlForwardIterator must match the sequence type returned by announceCollection()
Reimplemented in QPatternist::ResourceDelegator.
Definition at line 113 of file qresourceloader.cpp.
Referenced by QPatternist::ResourceDelegator::openCollection().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     return Item::Iterator::Ptr();
 }
openDocument()
Item ResourceLoader::openDocument (const QUrl & uri, const ReportContext::Ptr & context) virtual
Calls to this function are generated by calls to the fn:document() or fn:doc() function.
Note
This function is responsible for execution stability. Subsequent calls to this function with the same URI should result in QXmlNodeModelIndex instances that have the same identity. However, in some cases this stability is not of interest, see the specification for details.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
See also
QXmlNodeModelIndex::identity()
XQuery 1.0 and XPath 2.0 Functions and Operators, 15.5.4 fn:doc
XSL Transformations (XSLT) Version 2.0, 16.1 Multiple Source Documents
Returns
null if no document can be loaded for uri
A QXmlNodeModelIndex representing the document identified by uri. Remember that the QXmlNodeModelIndex must match the sequence type returned by announceDocument()
Reimplemented in QPatternist::AccelTreeResourceLoader, and QPatternist::ResourceDelegator.
Definition at line 87 of file qresourceloader.cpp.
Referenced by QPatternist::DocFN::evaluateSingleton(), and QPatternist::ResourceDelegator::openDocument().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     Q_UNUSED(context); /* Needed when compiling in release mode. */
     return Item();
 }
openUnparsedText()
Item ResourceLoader::openUnparsedText (const QUrl & uri, const QString & encoding, const ReportContext::Ptr & context, const SourceLocationReflection *const where) virtual
Calls to this function are generated by calls to the fn:unparsed-text() function.
Parameters
uri A URI identifying the resource to retrieve. The URI is guaranteed to be valid(QUrl::isValid() returns true) and to be absolute(QUrl::isRelative() returns false).
encoding the encoding to use. If empty, the user hasn't expressed any encoding to use.
See also
XSL Transformations (XSLT) Version 2.0, 16.2 Reading Text Files
Returns
null if no unparsed file can be loaded for uri
An xs:string value(or subtype) containing the content of the file identified by uri as text. Remember that its type must match the sequence type returned by announceUnparsedText()
Reimplemented in QPatternist::AccelTreeResourceLoader, and QPatternist::ResourceDelegator.
Definition at line 73 of file qresourceloader.cpp.
Referenced by QPatternist::UnparsedTextFN::evaluateSingleton(), and QPatternist::ResourceDelegator::openUnparsedText().
 {
     Q_ASSERT(uri.isValid());
     Q_ASSERT(!uri.isRelative());
     Q_UNUSED(uri); /* Needed when compiling in release mode. */
     Q_UNUSED(encoding);
     Q_UNUSED(context);
     Q_UNUSED(where);
     return Item();
 }
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qresourceloader_p.h
/src/xmlpatterns/data/qresourceloader.cpp