Qt 4.8: QMultiInputContext Class Reference
QMultiInputContext Class Reference
#include <qmultiinputcontext.h>
Public Functions
QList< QAction * > actions ()
This is a preliminary interface for Qt 4.
bool filterEvent (const QEvent *event)
This function can be reimplemented in a subclass to filter input events.
QWidget * focusWidget () const
QFont font () const
Returns the font of the current input widget.
QString identifierName ()
This function must be implemented in any subclasses to return the identifier name of the input method.
bool isComposing () const
This function indicates whether InputMethodStart event had been sent to the current focus widget.
QString language ()
This function must be implemented in any subclasses to return a language code (e.
void mouseHandler (int x, QMouseEvent *event)
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
QMultiInputContext ()
void reset ()
This function can be reimplemented in a subclass to reset the state of the input method.
void setFocusWidget (QWidget *w)
Sets the widget that has an input focus for this input context.
QInputContext * slave ()
const QInputContext * slave () const
void update ()
This virtual function is called when a state in the focus widget has changed.
void widgetDestroyed (QWidget *w)
This virtual function is called when the specified widget is destroyed.
bool x11FilterEvent (QWidget *keywidget, XEvent *event)
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
~QMultiInputContext ()
Public Functions inherited from QInputContext
QWidget * focusWidget () const
Returns the widget that has an input focus for this input context.
QInputContext (QObject *parent=0)
Constructs an input context with the given parent.
void sendEvent (const QInputMethodEvent &event)
Sends an input method event specified by event to the current focus widget.
QTextFormat standardFormat (StandardFormat s) const
Returns a QTextFormat object that specifies the format for component s.
virtual ~QInputContext ()
Destroys the input context.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Slots
void changeSlave (QAction *)
Properties
int current
QStringList keys
QMenu * menu
QAction * separator
QList< QInputContext * > slaves
void * unused
Additional Inherited Members
Public Types inherited from QInputContext
enum StandardFormat { PreeditFormat, SelectionFormat }
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 71 of file qmultiinputcontext.h.
Constructors and Destructors
QMultiInputContext()
QMultiInputContext::QMultiInputContext ()
Definition at line 68 of file qmultiinputcontext.cpp.
     : QInputContext(), current(-1)
 {
     keys = QInputContextFactory::keys();
     for (int i = keys.size()-1; i >= 0; --i)
         if (keys.at(i).contains(QLatin1String("imsw")))
             keys.removeAt(i);
     QString def = QLatin1String(getenv("QT4_IM_MODULE"));
     if (def.isEmpty())
         def = QLatin1String(getenv("QT_IM_MODULE"));
     if (def.isEmpty()) {
         QSettings settings(QSettings::UserScope, QLatin1String("Trolltech"));
         settings.beginGroup(QLatin1String("Qt"));
         def = settings.value(QLatin1String("DefaultInputMethod"), QLatin1String("xim")).toString();
     }
     current = keys.indexOf(def);
     if (current < 0)
         current = 0;
     menu = new QMenu(tr("Select IM"));
     separator = new QAction(this);
     separator->setSeparator(true);
     QActionGroup *group = new QActionGroup(this);
     for (int i = 0; i < keys.size(); ++i) {
         slaves.append(0);
         const QString key = keys.at(i);
         QAction *a = menu->addAction(QInputContextFactory::displayName(key));
         a->setData(key);
         a->setCheckable(true);
         group->addAction(a);
         if (i == current) {
             slaves.replace(current, QInputContextFactory::create(key, this));
             a->setChecked(true);
         }
     }
     connect(group, SIGNAL(triggered(QAction*)), this, SLOT(changeSlave(QAction*)));
 }
~QMultiInputContext()
QMultiInputContext::~QMultiInputContext ()
Definition at line 108 of file qmultiinputcontext.cpp.
 {
     delete menu;
 }
Functions
actions()
QList< QAction * > QMultiInputContext::actions () virtual
This is a preliminary interface for Qt 4.
Reimplemented from QInputContext.
Definition at line 184 of file qmultiinputcontext.cpp.
 {
     QList<QAction *> a = slave()->actions();
     a.append(separator);
     a.append(menu->menuAction());
     return a;
 }
changeSlave
void QMultiInputContext::changeSlave (QAction * a) protected slot
Definition at line 192 of file qmultiinputcontext.cpp.
Referenced by QMultiInputContext(), and slave().
 {
     for (int i = 0; i < slaves.size(); ++i) {
         if (keys.at(i) == a->data().toString()) {
             if (slaves.at(i) == 0)
                 slaves.replace(i, QInputContextFactory::create(keys.at(i), this));
             QInputContext *qic = slaves.at(current);
             QWidget *oldWidget = qic->focusWidget();
             qic->reset();
             qic->setFocusWidget(0);
             current = i;
             qic = slaves.at(current);
             qic->setFocusWidget(oldWidget);
             return;
         }
     }
 }
filterEvent()
bool QMultiInputContext::filterEvent (const QEvent * event) virtual
This function can be reimplemented in a subclass to filter input events.
Return true if the event has been consumed. Otherwise, the unfiltered event will be forwarded to widgets as ordinary way. Although the input events have accept() and ignore() methods, leave it untouched.
event is currently restricted to events of these types:
CloseSoftwareInputPanel
KeyPress
KeyRelease
MouseButtonDblClick
MouseButtonPress
MouseButtonRelease
MouseMove
RequestSoftwareInputPanel
But some input method related events such as QWheelEvent or QTabletEvent may be added in future.
The filtering opportunity is always given to the input context as soon as possible. It has to be taken place before any other key event consumers such as eventfilters and accelerators because some input methods require quite various key combination and sequences. It often conflicts with accelerators and so on, so we must give the input context the filtering opportunity first to ensure all input methods work properly regardless of application design.
Ordinary input methods require discrete key events to work properly, so Qt's key compression is always disabled for any input contexts.
See also
QKeyEvent, x11FilterEvent()
Reimplemented from QInputContext.
Definition at line 133 of file qmultiinputcontext.cpp.
 {
     return (slave()) ? slave()->filterEvent(event) : false;
 }
focusWidget()
QWidget * QMultiInputContext::focusWidget () const
Definition at line 168 of file qmultiinputcontext.cpp.
 {
     return QInputContext::focusWidget();
 }
font()
QFont QMultiInputContext::font () const virtual
Returns the font of the current input widget.
Reimplemented from QInputContext.
Definition at line 156 of file qmultiinputcontext.cpp.
 {
     return (slave()) ? slave()->font() : QInputContext::font();
 }
identifierName()
QString QMultiInputContext::identifierName () virtual
This function must be implemented in any subclasses to return the identifier name of the input method.
Return value is the name to identify and specify input methods for the input method switching mechanism and so on. The name has to be consistent with QInputContextPlugin::keys(). The name has to consist of ASCII characters only.
There are two different names with different responsibility in the input method domain. This function returns one of them. Another name is called 'display name' that stands for the name for endusers appeared in a menu and so on.
See also
QInputContextPlugin::keys(), QInputContextPlugin::displayName()
Implements QInputContext.
Definition at line 114 of file qmultiinputcontext.cpp.
 {
     return (slave()) ? slave()->identifierName() : QLatin1String("");
 }
isComposing()
bool QMultiInputContext::isComposing () const virtual
This function indicates whether InputMethodStart event had been sent to the current focus widget.
It is ensured that an input context can send InputMethodCompose or InputMethodEnd event safely if this function returned true.
The state is automatically being tracked through sendEvent().
See also
sendEvent()
Implements QInputContext.
Definition at line 179 of file qmultiinputcontext.cpp.
 {
     return (slave()) ? slave()->isComposing() : false;
 }
language()
QString QMultiInputContext::language () virtual
This function must be implemented in any subclasses to return a language code (e.
g. "zh_CN", "zh_TW", "zh_HK", "ja", "ko", ...) of the input context. If the input context can handle multiple languages, return the currently used one. The name has to be consistent with QInputContextPlugin::language().
This information will be used by language tagging feature in QInputMethodEvent. It is required to distinguish unified han characters correctly. It enables proper font and character code handling. Suppose CJK-awared multilingual web browser (that automatically modifies fonts in CJK-mixed text) and XML editor (that automatically inserts lang attr).
Implements QInputContext.
Definition at line 119 of file qmultiinputcontext.cpp.
 {
     return (slave()) ? slave()->language() : QLatin1String("");
 }
mouseHandler()
void QMultiInputContext::mouseHandler (int x, QMouseEvent * event) virtual
This function can be reimplemented in a subclass to handle mouse press, release, double-click, and move events within the preedit text.
You can use the function to implement mouse-oriented user interface such as text selection or popup menu for candidate selection.
The x parameter is the offset within the string that was sent with the InputMethodCompose event. The alteration boundary of x is ensured as character boundary of preedit string accurately.
The event parameter is the event that was sent to the editor widget. The event type is QEvent::MouseButtonPress, QEvent::MouseButtonRelease, QEvent::MouseButtonDblClick or QEvent::MouseMove. The event's button and state indicate the kind of operation that was performed.
Reimplemented from QInputContext.
Definition at line 150 of file qmultiinputcontext.cpp.
 {
     if (slave())
     slave()->mouseHandler(x, event);
 }
reset()
void QMultiInputContext::reset () virtual
This function can be reimplemented in a subclass to reset the state of the input method.
This function is called by several widgets to reset input state. For example, a text widget call this function before inserting a text to make widget ready to accept a text.
Default implementation is sufficient for simple input method. You can override this function to reset external input method engines in complex input method. In the case, call QInputContext::reset() to ensure proper termination of inputting.
In a reimplementation of reset(), you must not send any QInputMethodEvent containing preedit text. You can only commit string and attributes; otherwise, you risk breaking input state consistency.
Implements QInputContext.
Definition at line 138 of file qmultiinputcontext.cpp.
 {
     if (slave())
     slave()->reset();
 }
setFocusWidget()
void QMultiInputContext::setFocusWidget (QWidget * widget) virtual
Sets the widget that has an input focus for this input context.
Warning
Ordinary input methods must not call this function directly.
See also
focusWidget()
Reimplemented from QInputContext.
Definition at line 161 of file qmultiinputcontext.cpp.
 {
     QInputContext::setFocusWidget(w);
     if (slave())
     slave()->setFocusWidget(w);
 }
slave() [1/2]
QInputContext* QMultiInputContext::slave () inline
Definition at line 99 of file qmultiinputcontext.h.
Referenced by actions(), filterEvent(), font(), identifierName(), isComposing(), language(), mouseHandler(), reset(), setFocusWidget(), update(), widgetDestroyed(), and x11FilterEvent().
 { return slaves.at(current); }
slave() [2/2]
const QInputContext* QMultiInputContext::slave () const inline
Definition at line 100 of file qmultiinputcontext.h.
 { return slaves.at(current); }
update()
void QMultiInputContext::update (void) virtual
This virtual function is called when a state in the focus widget has changed.
QInputContext can then use QWidget::inputMethodQuery() to query the new state of the widget.
Reimplemented from QInputContext.
Definition at line 144 of file qmultiinputcontext.cpp.
 {
     if (slave())
     slave()->update();
 }
widgetDestroyed()
void QMultiInputContext::widgetDestroyed (QWidget * widget) virtual
This virtual function is called when the specified widget is destroyed.
The widget is a widget on which this input context is installed.
Reimplemented from QInputContext.
Definition at line 173 of file qmultiinputcontext.cpp.
 {
     if (slave())
     slave()->widgetDestroyed(w);
 }
x11FilterEvent()
bool QMultiInputContext::x11FilterEvent (QWidget * keywidget, XEvent * event) virtual
This function may be overridden only if input method is depending on X11 and you need raw XEvent.
Otherwise, this function must not.
This function is designed to filter raw key events for XIM, but other input methods may use this to implement some special features such as distinguishing Shift_L and Shift_R.
Return true if the event has been consumed. Otherwise, the unfiltered event will be translated into QEvent and forwarded to filterEvent(). Filtering at both x11FilterEvent() and filterEvent() in single input method is allowed.
keywidget is a client widget into which a text is inputted. event is inputted XEvent.
See also
filterEvent()
Reimplemented from QInputContext.
Definition at line 126 of file qmultiinputcontext.cpp.
 {
     return (slave()) ? slave()->x11FilterEvent(keywidget, event) : false;
 }
Properties
current
int QMultiInputContext::current private
Definition at line 106 of file qmultiinputcontext.h.
Referenced by changeSlave(), QMultiInputContext(), and slave().
keys
QStringList QMultiInputContext::keys private
Definition at line 110 of file qmultiinputcontext.h.
Referenced by changeSlave(), and QMultiInputContext().
menu
QMenu* QMultiInputContext::menu private
Definition at line 108 of file qmultiinputcontext.h.
Referenced by actions(), QMultiInputContext(), and ~QMultiInputContext().
separator
QAction* QMultiInputContext::separator private
Definition at line 109 of file qmultiinputcontext.h.
Referenced by actions(), and QMultiInputContext().
slaves
QList<QInputContext *> QMultiInputContext::slaves private
Definition at line 107 of file qmultiinputcontext.h.
Referenced by changeSlave(), QMultiInputContext(), and slave().
unused
void* QMultiInputContext::unused private
Definition at line 105 of file qmultiinputcontext.h.
The documentation for this class was generated from the following files:
/src/plugins/inputmethods/imsw-multi/qmultiinputcontext.h
/src/plugins/inputmethods/imsw-multi/qmultiinputcontext.cpp