Qt 4.8: QDeclarativeGuard< T > Class Template Reference
QDeclarativeGuard< T > Class Template Reference
#include <qdeclarativeguard_p.h>
Public Functions
T * data () const
bool isNull () const
T * object () const
operator T* () const
T & operator* () const
T * operator-> () const
QDeclarativeGuard< T > & operator= (const QDeclarativeGuard< T > &o)
QDeclarativeGuard< T > & operator= (T *)
QDeclarativeGuard ()
QDeclarativeGuard (T *)
QDeclarativeGuard (const QDeclarativeGuard< T > &)
void setObject (T *g)
virtual ~QDeclarativeGuard ()
Protected Functions
virtual void objectDestroyed (T *)
Friends
class QDeclarativeData
Additional Inherited Members
Private Functions inherited from QDeclarativeGuardImpl
void addGuard ()
QDeclarativeGuardImpl ()
QDeclarativeGuardImpl (QObject *)
QDeclarativeGuardImpl (const QDeclarativeGuardImpl &)
void remGuard ()
~QDeclarativeGuardImpl ()
Properties inherited from QDeclarativeGuardImpl
QDeclarativeGuardImpl * next
QObject * o
QDeclarativeGuardImpl ** prev
Detailed Description
template<class T>
class QDeclarativeGuard< T >
Definition at line 80 of file qdeclarativeguard_p.h.
Constructors and Destructors
QDeclarativeGuard() [1/3]
template<class T > QDeclarativeGuard< T >::QDeclarativeGuard () inline
Definition at line 159 of file qdeclarativeguard_p.h.
 {
 }
QDeclarativeGuard() [2/3]
template<class T> QDeclarativeGuard< T >::QDeclarativeGuard (T * g) inline
Definition at line 164 of file qdeclarativeguard_p.h.
 : QDeclarativeGuardImpl(g)
 {
 }
QDeclarativeGuard() [3/3]
template<class T> QDeclarativeGuard< T >::QDeclarativeGuard (const QDeclarativeGuard< T > & g) inline
Definition at line 170 of file qdeclarativeguard_p.h.
 : QDeclarativeGuardImpl(g)
 {
 }
~QDeclarativeGuard()
template<class T > QDeclarativeGuard< T >::~QDeclarativeGuard () inline virtual
Definition at line 176 of file qdeclarativeguard_p.h.
 {
 }
Functions
data()
template<class T> T* QDeclarativeGuard< T >::data () const inline
Definition at line 104 of file qdeclarativeguard_p.h.
Referenced by QDeclarativeVMEMetaObject::aliasTarget(), QDeclarativeVMEMetaObject::connectAlias(), QDeclarativeContext::contextProperty(), ContextData::getScope(), QDeclarativeVMEMetaObject::metaCall(), QDeclarativeContextScriptClass::property(), QDeclarativeCompiledBindingsPrivate::run(), and QDeclarativeObjectScriptClass::toQObject().
         { return static_cast<T*>(const_cast<QObject*>(o)); }
isNull()
template<class T> bool QDeclarativeGuard< T >::isNull () const inline
Definition at line 95 of file qdeclarativeguard_p.h.
         { return !o; }
object()
template<class T > T * QDeclarativeGuard< T >::object () const inline
Definition at line 195 of file qdeclarativeguard_p.h.
Referenced by QDeclarativeGuard< QDeclarativeTransition >::operator=().
 {
     return static_cast<T *>(o);
 };
objectDestroyed()
template<class T> virtual void QDeclarativeGuard< T >::objectDestroyed (T *) inline protected virtual
Reimplemented in QDeclarativeStatePrivate::OperationGuard, QDeclarativeContextData::ContextGuard, QDeclarativeBoundSignal::ScopeGuard, and QDeclarativePackagePrivate::DataGuard.
Definition at line 108 of file qdeclarativeguard_p.h.
 {}
operator T*()
template<class T> QDeclarativeGuard< T >::operator T* () const inline
Definition at line 102 of file qdeclarativeguard_p.h.
         { return static_cast<T*>(const_cast<QObject*>(o)); }
operator*()
template<class T> T& QDeclarativeGuard< T >::operator* () const inline
Definition at line 100 of file qdeclarativeguard_p.h.
         { return *static_cast<T*>(const_cast<QObject*>(o)); }
operator->()
template<class T> T* QDeclarativeGuard< T >::operator-> () const inline
Definition at line 98 of file qdeclarativeguard_p.h.
         { return static_cast<T*>(const_cast<QObject*>(o)); }
operator=() [1/2]
template<class T> QDeclarativeGuard< T > & QDeclarativeGuard< T >::operator= (const QDeclarativeGuard< T > & o) inline
Definition at line 181 of file qdeclarativeguard_p.h.
Referenced by QDeclarativeContextData::ContextGuard::operator=().
 {
     setObject(g.object());
     return *this;
 }
operator=() [2/2]
template<class T> QDeclarativeGuard< T > & QDeclarativeGuard< T >::operator= (T * g) inline
Definition at line 188 of file qdeclarativeguard_p.h.
 {
     setObject(g);
     return *this;
 }
setObject()
template<class T> void QDeclarativeGuard< T >::setObject (T * g) inline
Definition at line 201 of file qdeclarativeguard_p.h.
Referenced by QDeclarativeGuard< QDeclarativeTransition >::operator=().
 {
     if (g != o) {
         if (prev) remGuard();
         o = g;
         if (o) addGuard();
     }
 }
Friends and Related Functions
QDeclarativeData
template<class T> friend class QDeclarativeData friend
Definition at line 82 of file qdeclarativeguard_p.h.
The documentation for this class was generated from the following file:
/src/declarative/qml/qdeclarativeguard_p.h