Qt 4.8: QCalendarTextNavigator Class Reference
QCalendarTextNavigator Class Reference
#include <qcalendartextnavigator_p.h>
Signals
void dateChanged (const QDate &date)
void editingFinished ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QDate date () const
int dateEditAcceptDelay () const
bool eventFilter (QObject *o, QEvent *e)
Filters events if this object has been installed as an event filter for the watched object.
QCalendarTextNavigator (QObject *parent=0)
void setDate (const QDate &date)
void setDateEditAcceptDelay (int delay)
void setWidget (QWidget *widget)
void timerEvent (QTimerEvent *e)
This event handler can be reimplemented in a subclass to receive timer events for the object.
QWidget * widget () const
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Private Functions
void applyDate ()
void createDateLabel ()
void removeDateLabel ()
void updateDateLabel ()
Properties
QBasicTimer m_acceptTimer
QDate m_date
QFrame * m_dateFrame
QLabel * m_dateText
QCalendarDateValidator * m_dateValidator
int m_editDelay
QWidget * m_widget
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 68 of file qcalendartextnavigator_p.h.
Constructors and Destructors
QCalendarTextNavigator()
QCalendarTextNavigator::QCalendarTextNavigator (QObject * parent = 0) inline
Definition at line 72 of file qcalendartextnavigator_p.h.
         : QObject(parent), m_dateText(0), m_dateFrame(0), m_dateValidator(0), m_widget(0), m_editDelay(1500), m_date(QDate::currentDate()) { }
Functions
applyDate()
void QCalendarTextNavigator::applyDate () private
Definition at line 717 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     QDate date = m_dateValidator->currentDate();
     if (m_date == date)
         return;
     m_date = date;
     emit dateChanged(date);
 }
createDateLabel()
void QCalendarTextNavigator::createDateLabel () private
Definition at line 727 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     if (m_dateFrame)
         return;
     m_dateFrame = new QFrame(m_widget);
     QVBoxLayout *vl = new QVBoxLayout;
     m_dateText = new QLabel;
     vl->addWidget(m_dateText);
     m_dateFrame->setLayout(vl);
     m_dateFrame->setFrameShadow(QFrame::Plain);
     m_dateFrame->setFrameShape(QFrame::Box);
     m_dateValidator = new QCalendarDateValidator();
     m_dateValidator->setLocale(m_widget->locale());
     m_dateValidator->setFormat(m_widget->locale().dateFormat(QLocale::ShortFormat));
     m_dateValidator->setInitialDate(m_date);
     m_dateFrame->setAutoFillBackground(true);
     m_dateFrame->setBackgroundRole(QPalette::Window);
 }
date()
QDate QCalendarTextNavigator::date () const
Definition at line 684 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     return m_date;
 }
dateChanged
void QCalendarTextNavigator::dateChanged (const QDate & date) signal
Referenced by QCalendarTextNavigator().
dateEditAcceptDelay()
int QCalendarTextNavigator::dateEditAcceptDelay () const
Definition at line 803 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     return m_editDelay;
 }
editingFinished
void QCalendarTextNavigator::editingFinished () signal
Referenced by QCalendarTextNavigator().
eventFilter()
bool QCalendarTextNavigator::eventFilter (QObject * , QEvent *) virtual
Filters events if this object has been installed as an event filter for the watched object.
In your reimplementation of this function, if you want to filter the event out, i.e. stop it being handled further, return true; otherwise return false.
Example:
class MainWindow : public QMainWindow
{
public:
    MainWindow();
protected:
    bool eventFilter(QObject *obj, QEvent *ev);
private:
    QTextEdit *textEdit;
};
MainWindow::MainWindow()
{
    textEdit = new QTextEdit;
    setCentralWidget(textEdit);
    textEdit->installEventFilter(this);
}
bool MainWindow::eventFilter(QObject *obj, QEvent *event)
{
    if (obj == textEdit) {
        if (event->type() == QEvent::KeyPress) {
            QKeyEvent *keyEvent = static_cast<QKeyEvent*>(event);
            qDebug() << "Ate key press" << keyEvent->key();
            return true;
        } else {
            return false;
        }
    } else {
        // pass the event on to the parent class
        return QMainWindow::eventFilter(obj, event);
    }
}
Notice in the example above that unhandled events are passed to the base class's eventFilter() function, since the base class might have reimplemented eventFilter() for its own internal purposes.
Warning
If you delete the receiver object in this function, be sure to return true. Otherwise, Qt will forward the event to the deleted object and the program might crash.
See also
installEventFilter()
Reimplemented from QObject.
Definition at line 760 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     if (m_widget) {
         if (e->type() == QEvent::KeyPress || e->type() == QEvent::KeyRelease) {
             QKeyEvent* ke = (QKeyEvent*)e;
             if ((ke->text().length() > 0 && ke->text()[0].isPrint()) || m_dateFrame) {
                 if (ke->key() == Qt::Key_Return || ke->key() == Qt::Key_Enter || ke->key() == Qt::Key_Select) {
                     applyDate();
                     emit editingFinished();
                     removeDateLabel();
                 } else if (ke->key() == Qt::Key_Escape) {
                     removeDateLabel();
                 } else if (e->type() == QEvent::KeyPress) {
                     createDateLabel();
                     m_dateValidator->handleKeyEvent(ke);
                     updateDateLabel();
                 }
                 ke->accept();
                 return true;
             }
             // If we are navigating let the user finish his date in old locate.
             // If we change our mind and want it to update immediately simply uncomment below
             /*
         } else if (e->type() == QEvent::LocaleChange) {
             if (m_dateValidator) {
                 m_dateValidator->setLocale(m_widget->locale());
                 m_dateValidator->setFormat(m_widget->locale().dateFormat(QLocale::ShortFormat));
                 updateDateLabel();
             }
             */
         }
     }
     return QObject::eventFilter(o,e);
 }
removeDateLabel()
void QCalendarTextNavigator::removeDateLabel () private
Definition at line 747 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     if (!m_dateFrame)
         return;
     m_acceptTimer.stop();
     m_dateFrame->hide();
     m_dateFrame->deleteLater();
     delete m_dateValidator;
     m_dateFrame = 0;
     m_dateText = 0;
     m_dateValidator = 0;
 }
setDate()
void QCalendarTextNavigator::setDate (const QDate & date)
Definition at line 689 of file qcalendarwidget.cpp.
Referenced by QCalendarWidgetPrivate::_q_slotChangeDate(), and QCalendarTextNavigator().
 {
     m_date = date;
 }
setDateEditAcceptDelay()
void QCalendarTextNavigator::setDateEditAcceptDelay (int delay)
Definition at line 808 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     m_editDelay = delay;
 }
setWidget()
void QCalendarTextNavigator::setWidget (QWidget * widget)
Definition at line 679 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator(), and QCalendarWidgetPrivate::setNavigatorEnabled().
 {
     m_widget = widget;
 }
timerEvent()
void QCalendarTextNavigator::timerEvent (QTimerEvent * event) virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 795 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     if (e->timerId() == m_acceptTimer.timerId()) {
         applyDate();
         removeDateLabel();
     }
 }
updateDateLabel()
void QCalendarTextNavigator::updateDateLabel () private
Definition at line 694 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator().
 {
     if (!m_widget)
         return;
     m_acceptTimer.start(m_editDelay, this);
     m_dateText->setText(m_dateValidator->currentText());
     QSize s = m_dateFrame->sizeHint();
     QRect r = m_widget->geometry(); // later, just the table section
     QRect newRect((r.width() - s.width()) / 2, (r.height() - s.height()) / 2, s.width(), s.height());
     m_dateFrame->setGeometry(newRect);
     // need to set palette after geometry update as phonestyle sets transparency
     // effect in move event.
     QPalette p = m_dateFrame->palette();
     p.setBrush(QPalette::Window, m_dateFrame->window()->palette().brush(QPalette::Window));
     m_dateFrame->setPalette(p);
     m_dateFrame->raise();
     m_dateFrame->show();
 }
widget()
QWidget * QCalendarTextNavigator::widget () const
Definition at line 674 of file qcalendarwidget.cpp.
Referenced by QCalendarTextNavigator(), and QCalendarWidgetPrivate::setNavigatorEnabled().
 {
     return m_widget;
 }
Properties
m_acceptTimer
QBasicTimer QCalendarTextNavigator::m_acceptTimer private
Definition at line 99 of file qcalendartextnavigator_p.h.
m_date
QDate QCalendarTextNavigator::m_date private
Definition at line 104 of file qcalendartextnavigator_p.h.
m_dateFrame
QFrame* QCalendarTextNavigator::m_dateFrame private
Definition at line 98 of file qcalendartextnavigator_p.h.
m_dateText
QLabel* QCalendarTextNavigator::m_dateText private
Definition at line 97 of file qcalendartextnavigator_p.h.
m_dateValidator
QCalendarDateValidator* QCalendarTextNavigator::m_dateValidator private
Definition at line 100 of file qcalendartextnavigator_p.h.
m_editDelay
int QCalendarTextNavigator::m_editDelay private
Definition at line 102 of file qcalendartextnavigator_p.h.
m_widget
QWidget* QCalendarTextNavigator::m_widget private
Definition at line 101 of file qcalendartextnavigator_p.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qcalendartextnavigator_p.h
/src/gui/widgets/qcalendarwidget.cpp