Qt 4.8: QSoftKeyManager Class Reference
QSoftKeyManager Class Reference
#include <qsoftkeymanager_p.h>
Public Types
enum StandardSoftKey {
OkSoftKey, SelectSoftKey, DoneSoftKey, MenuSoftKey,
CancelSoftKey
}
Static Public Functions
static QAction * createAction (StandardSoftKey standardKey, QWidget *actionWidget)
static QAction * createKeyedAction (StandardSoftKey standardKey, Qt::Key key, QWidget *actionWidget)
Creates a QAction and registers the 'triggered' signal to send the given key event to actionWidget as a convenience.
static bool isForceEnabledInSofkeys (QAction *action)
static void setForceEnabledInSoftkeys (QAction *action)
static QString standardSoftKeyText (StandardSoftKey standardKey)
static void updateSoftKeys ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
bool event (QEvent *e)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Slots
void cleanupHash (QObject *obj)
void sendKeyEvent ()
Private Functions
bool appendSoftkeys (const QWidget &source, int level)
bool handleUpdateSoftKeys ()
QSoftKeyManager ()
QWidget * softkeySource (QWidget *previousSource, bool &recursiveMerging)
Static Private Functions
static QSoftKeyManager * instance ()
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 66 of file qsoftkeymanager_p.h.
Enumerations
StandardSoftKey
enum QSoftKeyManager::StandardSoftKey
Enumerator
OkSoftKey
SelectSoftKey
DoneSoftKey
MenuSoftKey
CancelSoftKey
Definition at line 73 of file qsoftkeymanager_p.h.
{
         OkSoftKey,
         SelectSoftKey,
         DoneSoftKey,
         MenuSoftKey,
         CancelSoftKey
     };
Constructors and Destructors
QSoftKeyManager()
QSoftKeyManager::QSoftKeyManager () private
Definition at line 93 of file qsoftkeymanager.cpp.
                                  :
 #ifdef Q_WS_S60
     QObject(*(new QSoftKeyManagerPrivateS60), 0)
 #else
     QObject(*(new QSoftKeyManagerPrivate), 0)
 #endif
 {
 }
Functions
appendSoftkeys()
bool QSoftKeyManager::appendSoftkeys (const QWidget & source, int level) private
Definition at line 216 of file qsoftkeymanager.cpp.
Referenced by handleUpdateSoftKeys().
 {
     Q_D(QSoftKeyManager);
     bool ret = false;
     foreach(QAction *action, source.actions()) {
         if (action->softKeyRole() != QAction::NoSoftKey
             && (action->isVisible() || isForceEnabledInSofkeys(action))) {
             d->requestedSoftKeyActions.insert(level, action);
             ret = true;
         }
     }
     return ret;
 }
cleanupHash
void QSoftKeyManager::cleanupHash (QObject * obj) private slot
Definition at line 177 of file qsoftkeymanager.cpp.
Referenced by createAction(), and createKeyedAction().
 {
     Q_D(QSoftKeyManager);
     // Can't use qobject_cast in destroyed() signal handler as that'll return NULL,
     // so use static_cast instead. Since the pointer is only used as a hash key, it is safe.
     QAction *action = static_cast<QAction *>(obj);
     d->keyedActions.remove(action);
 #if defined(Q_WS_S60) && !defined(SYMBIAN_VERSION_9_4) && !defined(SYMBIAN_VERSION_9_3) && !defined(SYMBIAN_VERSION_9_2)
     d->softKeyCommandActions.remove(action);
 #endif
 }
createAction()
QAction * QSoftKeyManager::createAction (StandardSoftKey standardKey, QWidget * actionWidget) static
Definition at line 102 of file qsoftkeymanager.cpp.
Referenced by createKeyedAction(), and QMenuBarPrivate::handleReparent().
 {
     QAction *action = new QAction(standardSoftKeyText(standardKey), actionWidget);
 #if defined(Q_WS_S60) && !defined(SYMBIAN_VERSION_9_4) && !defined(SYMBIAN_VERSION_9_3) && !defined(SYMBIAN_VERSION_9_2)
     int key = 0;
     switch (standardKey) {
     case OkSoftKey:
         key = EAknSoftkeyOk;
         break;
     case SelectSoftKey:
         key = EAknSoftkeySelect;
         break;
     case DoneSoftKey:
         key = EAknSoftkeyDone;
         break;
     case MenuSoftKey:
         key = EAknSoftkeyOptions;
         break;
     case CancelSoftKey:
         key = EAknSoftkeyCancel;
         break;
     default:
         break;
     };
     if (key != 0) {
         QSoftKeyManager::instance()->d_func()->softKeyCommandActions.insert(action, key);
         connect(action, SIGNAL(destroyed(QObject*)), QSoftKeyManager::instance(), SLOT(cleanupHash(QObject*)));
     }
 #endif
     QAction::SoftKeyRole softKeyRole = QAction::NoSoftKey;
     switch (standardKey) {
     case MenuSoftKey: // FALL-THROUGH
         QActionPrivate::get(action)->menuActionSoftkeys = true;
     case OkSoftKey:
     case SelectSoftKey:
     case DoneSoftKey:
         softKeyRole = QAction::PositiveSoftKey;
         break;
     case CancelSoftKey:
         softKeyRole = QAction::NegativeSoftKey;
         break;
     }
     action->setSoftKeyRole(softKeyRole);
     action->setVisible(false);
     setForceEnabledInSoftkeys(action);
     return action;
 }
createKeyedAction()
QAction * QSoftKeyManager::createKeyedAction (StandardSoftKey standardKey, Qt::Key key, QWidget * actionWidget) static
Creates a QAction and registers the 'triggered' signal to send the given key event to actionWidget as a convenience.
Warning
This function is not part of the public interface.
Definition at line 159 of file qsoftkeymanager.cpp.
Referenced by QAbstractItemViewPrivate::init(), QMenuPrivate::init(), and QComboBoxPrivateContainer::setItemView().
 {
 #ifndef QT_NO_ACTION
     QScopedPointer<QAction> action(createAction(standardKey, actionWidget));
     connect(action.data(), SIGNAL(triggered()), QSoftKeyManager::instance(), SLOT(sendKeyEvent()));
 #if defined(Q_WS_S60) && !defined(SYMBIAN_VERSION_9_4) && !defined(SYMBIAN_VERSION_9_3) && !defined(SYMBIAN_VERSION_9_2)
     // Don't connect destroyed slot if is was already connected in createAction
     if (!(QSoftKeyManager::instance()->d_func()->softKeyCommandActions.contains(action.data())))
 #endif
     connect(action.data(), SIGNAL(destroyed(QObject*)), QSoftKeyManager::instance(), SLOT(cleanupHash(QObject*)));
     QSoftKeyManager::instance()->d_func()->keyedActions.insert(action.data(), key);
     return action.take();
 #endif //QT_NO_ACTION
 }
event()
bool QSoftKeyManager::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Definition at line 314 of file qsoftkeymanager.cpp.
Referenced by updateSoftKeys().
 {
 #ifndef QT_NO_ACTION
     if (e->type() == QEvent::UpdateSoftKeys)
         return handleUpdateSoftKeys();
 #endif //QT_NO_ACTION
     return false;
 }
handleUpdateSoftKeys()
bool QSoftKeyManager::handleUpdateSoftKeys () private
Definition at line 285 of file qsoftkeymanager.cpp.
Referenced by event().
 {
     Q_D(QSoftKeyManager);
     int level = 0;
     d->requestedSoftKeyActions.clear();
     bool recursiveMerging = false;
     QWidget *source = softkeySource(NULL, recursiveMerging);
     d->initialSoftKeySource = source;
     while (source) {
         if (appendSoftkeys(*source, level))
             ++level;
         source = softkeySource(source, recursiveMerging);
     }
     d->updateSoftKeys_sys();
     d->pendingUpdate = false;
     return true;
 }
instance()
QSoftKeyManager * QSoftKeyManager::instance () static private
Definition at line 85 of file qsoftkeymanager.cpp.
Referenced by createAction(), createKeyedAction(), event(), and updateSoftKeys().
 {
     if (!QSoftKeyManagerPrivate::self)
         QSoftKeyManagerPrivate::self.reset(new QSoftKeyManager);
     return QSoftKeyManagerPrivate::self.data();
 }
isForceEnabledInSofkeys()
bool QSoftKeyManager::isForceEnabledInSofkeys (QAction * action) static
Definition at line 309 of file qsoftkeymanager.cpp.
Referenced by appendSoftkeys().
 {
     return QActionPrivate::get(action)->forceEnabledInSoftkeys;
 }
sendKeyEvent
void QSoftKeyManager::sendKeyEvent () private slot
Definition at line 189 of file qsoftkeymanager.cpp.
Referenced by createKeyedAction().
 {
     Q_D(QSoftKeyManager);
     QAction *action = qobject_cast<QAction*>(sender());
     if (!action)
         return;
     Qt::Key keyToSend = d->keyedActions.value(action, Qt::Key_unknown);
     if (keyToSend != Qt::Key_unknown)
         QApplication::postEvent(action->parentWidget(),
                                 new QKeyEvent(QEvent::KeyPress, keyToSend, Qt::NoModifier));
 }
setForceEnabledInSoftkeys()
void QSoftKeyManager::setForceEnabledInSoftkeys (QAction * action) static
Definition at line 304 of file qsoftkeymanager.cpp.
Referenced by createAction().
 {
     QActionPrivate::get(action)->forceEnabledInSoftkeys = true;
 }
softkeySource()
QWidget * QSoftKeyManager::softkeySource (QWidget * previousSource, bool & recursiveMerging) private
Definition at line 241 of file qsoftkeymanager.cpp.
Referenced by handleUpdateSoftKeys().
 {
     Q_D(QSoftKeyManager);
     QWidget *source = NULL;
     if (!previousSource) {
         // Initial source is primarily focuswidget and secondarily activeWindow
         QWidget *focus = QApplication::focusWidget();
         QWidget *popup = QApplication::activePopupWidget();
         if (popup) {
             if (isChildOf(focus, popup))
                 source = focus;
             else
                 source = popup;
         }
         if (!source) {
             QWidget *modal = QApplication::activeModalWidget();
             if (modal) {
                 if (isChildOf(focus, modal))
                     source = focus;
                 else
                     source = modal;
             }
         }
         if (!source) {
             source = focus;
             if (!source)
                 source = QApplication::activeWindow();
         }
     } else {
         // Softkey merging is based on four criterias
         // 1. Implicit merging is used whenever focus widget does not specify any softkeys
         bool implicitMerging = d->requestedSoftKeyActions.isEmpty();
         // 2. Explicit merging with parent is used whenever WA_MergeSoftkeys widget attribute is set
         bool explicitMerging = previousSource->testAttribute(Qt::WA_MergeSoftkeys);
         // 3. Explicit merging with all parents
         recursiveMerging |= previousSource->testAttribute(Qt::WA_MergeSoftkeysRecursively);
         // 4. Implicit and explicit merging always stops at window boundary
         bool merging = (implicitMerging || explicitMerging || recursiveMerging) && !previousSource->isWindow();
         source = merging ? previousSource->parentWidget() : NULL;
     }
     return source;
 }
standardSoftKeyText()
QString QSoftKeyManager::standardSoftKeyText (StandardSoftKey standardKey) static
Definition at line 59 of file qsoftkeymanager.cpp.
Referenced by QMenuBar::changeEvent(), QComboBoxPrivateContainer::changeEvent(), createAction(), QMenu::event(), and QAbstractItemView::event().
 {
     QString softKeyText;
     switch (standardKey) {
     case OkSoftKey:
         softKeyText = QSoftKeyManager::tr("OK");
         break;
     case SelectSoftKey:
         softKeyText = QSoftKeyManager::tr("Select");
         break;
     case DoneSoftKey:
         softKeyText = QSoftKeyManager::tr("Done");
         break;
     case MenuSoftKey:
         softKeyText = QSoftKeyManager::tr("Options");
         break;
     case CancelSoftKey:
         softKeyText = QSoftKeyManager::tr("Cancel");
         break;
     default:
         break;
     };
     return softKeyText;
 }
updateSoftKeys()
void QSoftKeyManager::updateSoftKeys () static
Definition at line 204 of file qsoftkeymanager.cpp.
Referenced by QWidget::event().
 {
 #ifdef Q_WS_S60
     // Do not adjust softkeys if application is not the topmost one
     if (S60->wsSession().GetFocusWindowGroup() != S60->windowGroup().WindowGroupId())
         return;
 #endif
     QSoftKeyManager::instance()->d_func()->pendingUpdate = true;
     QEvent *event = new QEvent(QEvent::UpdateSoftKeys);
     QApplication::postEvent(QSoftKeyManager::instance(), event);
 }
The documentation for this class was generated from the following files:
/src/gui/kernel/qsoftkeymanager_p.h
/src/gui/kernel/qsoftkeymanager.cpp