Qt 4.8: QPatternist::DateTime Class Reference
QPatternist::DateTime Class Reference
Implements the value instance of the xs:dateTime type.
#include <qschemadatetime_p.h>
Public Types
typedef AtomicValue::Ptr Ptr
Public Types inherited from QPatternist::AbstractDateTime
enum { DefaultYear = 2000, DefaultMonth = 1, DefaultDay = 1 }
typedef QExplicitlySharedDataPointer< AbstractDateTime > Ptr
Public Types inherited from QPatternist::AtomicValue
typedef QList< AtomicValue::Ptr > List
typedef QExplicitlySharedDataPointer< AtomicValue > Ptr
Public Functions
virtual Item fromValue (const QDateTime &dt) const
virtual QString stringValue () const
virtual ItemType::Ptr type () const
Public Functions inherited from QPatternist::AbstractDateTime
AbstractDateTime (const QDateTime &dateTime)
QString dateToString () const
QString timeToString () const
const QDateTime & toDateTime () const
Public Functions inherited from QPatternist::AtomicValue
virtual bool evaluateEBV (const QExplicitlySharedDataPointer< DynamicContext > &context) const
virtual bool hasError () const
virtual ~AtomicValue ()
Public Functions inherited from QSharedData
QSharedData ()
Constructs a QSharedData object with a reference count of 0.
QSharedData (const QSharedData &)
Constructs a QSharedData object with reference count 0.
Public Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
const TCastTarget * as () const
TCastTarget * as ()
Static Public Functions
static DateTime::Ptr fromDateTime (const QDateTime &dt)
static DateTime::Ptr fromLexical (const QString &string)
Static Public Functions inherited from QPatternist::AbstractDateTime
static bool isRangeValid (const QDate &date, QString &message)
static QString serializeMSeconds (const MSecondProperty msecs)
Static Public Functions inherited from QPatternist::AtomicValue
static ItemType::Ptr qtToXDMType (const QXmlItem &item)
static QVariant toQt (const AtomicValue *const value)
static QVariant toQt (const AtomicValue::Ptr &value)
static Item toXDM (const QVariant &value)
Protected Functions
DateTime (const QDateTime &dateTime)
Protected Functions inherited from QPatternist::AbstractDateTime
QString zoneOffsetToString () const
Protected Functions inherited from QPatternist::AtomicValue
AtomicValue ()
Protected Functions inherited from QPatternist::CppCastingHelper< AtomicValue >
CppCastingHelper ()
Friends
class CommonValues
Additional Inherited Members
Public Variables inherited from QSharedData
QAtomicInt ref
Static Protected Functions inherited from QPatternist::AbstractDateTime
static void copyTimeSpec (const QDateTime &from, QDateTime &to)
Makes the QDateTime::timeSpec() and QDateTime::zoneOffset() of ot * consistent to from.
static QDateTime create (AtomicValue::Ptr &errorMessage, const QString &lexicalSource, const CaptureTable &captTable)
Protected Variables inherited from QPatternist::AbstractDateTime
const QDateTime m_dateTime
Detailed Description
Implements the value instance of the xs:dateTime type.
Author
Frans Englich frans.nosp@m..eng.nosp@m.lich@.nosp@m.noki.nosp@m.a.com
Definition at line 76 of file qschemadatetime_p.h.
Typedefs
Ptr
typedef AtomicValue::Ptr QPatternist::DateTime::Ptr
Definition at line 79 of file qschemadatetime_p.h.
Constructors and Destructors
DateTime()
DateTime::DateTime (const QDateTime & dateTime) protected
Definition at line 51 of file qschemadatetime.cpp.
Referenced by fromDateTime(), and fromLexical().
                                             : AbstractDateTime(dateTime)
 {
 }
Functions
fromDateTime()
DateTime::Ptr DateTime::fromDateTime (const QDateTime & dt) static
Definition at line 95 of file qschemadatetime.cpp.
Referenced by QPatternist::AbstractDateTimeToDateTimeCaster::castFrom(), QPatternist::AdjustDateTimeToTimezoneFN::createValue(), QPatternist::DateTimeFN::evaluateSingleton(), QPatternist::CurrentDateTimeFN::evaluateSingleton(), fromValue(), and QPatternist::AtomicValue::toXDM().
 {
     Q_ASSERT(dt.isValid());
     return DateTime::Ptr(new DateTime(dt));
 }
fromLexical()
DateTime::Ptr DateTime::fromLexical (const QString & string) static
Creates an instance from the lexical representation string.
Definition at line 55 of file qschemadatetime.cpp.
Referenced by QPatternist::StringToDateTimeCaster::castFrom().
 {
     static const CaptureTable captureTable( // STATIC DATA
         /* The extra paranthesis is a build fix for GCC 3.3. */
         (QRegExp(QLatin1String(
                 "^\\s*"                                     /* Any preceding whitespace. */
                 "(-?)"                                      /* Any preceding minus. */
                 "(\\d{4,})"                                 /* The year part. */
                 "-"                                         /* Delimiter. */
                 "(\\d{2})"                                  /* The month part. */
                 "-"                                         /* Delimiter. */
                 "(\\d{2})"                                  /* The day part. */
                 "T"                                         /* Delimiter. */
                 "(\\d{2})"                                  /* Hour part */
                 ":"                                         /* Delimiter. */
                 "(\\d{2})"                                  /* Minutes part */
                 ":"                                         /* Delimiter. */
                 "(\\d{2,})"                                 /* Seconds part. */
                 "(?:\\.(\\d+))?"                            /* Milli seconds part. */
                 "(?:(\\+|-)(\\d{2}):(\\d{2})|(Z))?"         /* The zone offset, "+08:24". */
                 "\\s*$"                                     /* Any whitespace at the end. */))),
         /*zoneOffsetSignP*/         9,
         /*zoneOffsetHourP*/         10,
         /*zoneOffsetMinuteP*/       11,
         /*zoneOffsetUTCSymbolP*/    12,
         /*yearP*/                   2,
         /*monthP*/                  3,
         /*dayP*/                    4,
         /*hourP*/                   5,
         /*minutesP*/                6,
         /*secondsP*/                7,
         /*msecondsP*/               8,
         /*yearSignP*/               1);
     AtomicValue::Ptr err;
     const QDateTime retval(create(err, lexical, captureTable));
     return err ? err : DateTime::Ptr(new DateTime(retval));
 }
fromValue()
Item DateTime::fromValue (const QDateTime & dt) const virtual
A factory function for creating instances that are of the dynamic type of this class, that represents dt.
The default implementation performs an assert() call. This function is not pure virtual because all sub-classes do not use it.
Reimplemented from QPatternist::AbstractDateTime.
Definition at line 101 of file qschemadatetime.cpp.
 {
     Q_ASSERT(dt.isValid());
     return fromDateTime(dt);
 }
stringValue()
QString DateTime::stringValue () const virtual
Implements QPatternist::AtomicValue.
Definition at line 107 of file qschemadatetime.cpp.
 {
     return dateToString() + QLatin1Char('T') + timeToString() + zoneOffsetToString();
 }
type()
ItemType::Ptr DateTime::type () const virtual
Implements QPatternist::AtomicValue.
Definition at line 112 of file qschemadatetime.cpp.
 {
     return BuiltinTypes::xsDateTime;
 }
Friends and Related Functions
CommonValues
friend class CommonValues friend
Definition at line 91 of file qschemadatetime_p.h.
The documentation for this class was generated from the following files:
/src/xmlpatterns/data/qschemadatetime_p.h
/src/xmlpatterns/data/qschemadatetime.cpp