Qt 4.8: QAbstractSpinBox Class Reference
QAbstractSpinBox Class Reference
The QAbstractSpinBox class provides a spinbox and a line edit to display values.
#include <qabstractspinbox.h>
Public Types
enum ButtonSymbols { UpDownArrows, PlusMinus, NoButtons }
This enum type describes the symbols that can be displayed on the buttons in a spin box.
enum CorrectionMode { CorrectToPreviousValue, CorrectToNearestValue }
This enum type describes the mode the spinbox will use to correct an QValidator::Intermediate value if editing finishes.
enum StepEnabledFlag { StepNone = 0x00, StepUpEnabled = 0x01, StepDownEnabled = 0x02 }
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Public Slots
virtual void clear ()
Clears the lineedit of all text but prefix and suffix.
void selectAll ()
Selects all the text in the spinbox except the prefix and suffix.
void stepDown ()
Steps down by one linestep Calling this slot is analogous to calling stepBy(-1);.
void stepUp ()
Steps up by one linestep Calling this slot is analogous to calling stepBy(1);.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void editingFinished ()
This signal is emitted editing is finished.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
Qt::Alignment alignment () const
ButtonSymbols buttonSymbols () const
CorrectionMode correctionMode () const
bool event (QEvent *event)
Reimplemented Function
virtual void fixup (QString &input) const
This virtual function is called by the QAbstractSpinBox if the input is not validated to QValidator::Acceptable when Return is pressed or interpretText() is called.
bool hasAcceptableInput () const
bool hasFrame () const
QVariant inputMethodQuery (Qt::InputMethodQuery) const
Reimplemented Function
void interpretText ()
This function interprets the text of the spin box.
bool isAccelerated () const
bool isReadOnly () const
bool keyboardTracking () const
QSize minimumSizeHint () const
Reimplemented Function
QAbstractSpinBox (QWidget *parent=0)
Constructs an abstract spinbox with the given parent with default wrapping , and alignment properties.
void setAccelerated (bool on)
void setAlignment (Qt::Alignment flag)
void setButtonSymbols (ButtonSymbols bs)
void setCorrectionMode (CorrectionMode cm)
void setFrame (bool)
void setKeyboardTracking (bool kt)
void setReadOnly (bool r)
void setSpecialValueText (const QString &txt)
void setWrapping (bool w)
QSize sizeHint () const
Reimplemented Function
QString specialValueText () const
virtual void stepBy (int steps)
Virtual function that is called whenever the user triggers a step.
QString text () const
virtual QValidator::State validate (QString &input, int &pos) const
This virtual function is called by the QAbstractSpinBox to determine whether input is valid.
bool wrapping () const
~QAbstractSpinBox ()
Called when the QAbstractSpinBox is destroyed.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
void changeEvent (QEvent *event)
Reimplemented Function
void closeEvent (QCloseEvent *event)
Reimplemented Function
void contextMenuEvent (QContextMenuEvent *event)
Reimplemented Function
void focusInEvent (QFocusEvent *event)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
Reimplemented Function
void hideEvent (QHideEvent *event)
Reimplemented Function
void initStyleOption (QStyleOptionSpinBox *option) const
Initialize option with the values from this QSpinBox.
void keyPressEvent (QKeyEvent *event)
This function handles keyboard input.
void keyReleaseEvent (QKeyEvent *event)
Reimplemented Function
QLineEdit * lineEdit () const
This function returns a pointer to the line edit of the spin box.
void mouseMoveEvent (QMouseEvent *event)
Reimplemented Function
void mousePressEvent (QMouseEvent *event)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *event)
Reimplemented Function
void paintEvent (QPaintEvent *event)
Reimplemented Function
QAbstractSpinBox (QAbstractSpinBoxPrivate &dd, QWidget *parent=0)
void resizeEvent (QResizeEvent *event)
Reimplemented Function
void setLineEdit (QLineEdit *edit)
Sets the line edit of the spinbox to be lineEdit instead of the current line edit widget.
void showEvent (QShowEvent *event)
Reimplemented Function
virtual StepEnabled stepEnabled () const
Virtual function that determines whether stepping up and down is legal at any given time.
void timerEvent (QTimerEvent *event)
Reimplemented Function
void wheelEvent (QWheelEvent *event)
Reimplemented Function
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void dragEnterEvent (QDragEnterEvent *)
This event handler is called when a drag is in progress and the mouse enters this widget.
virtual void dragLeaveEvent (QDragLeaveEvent *)
This event handler is called when a drag is in progress and the mouse leaves this widget.
virtual void dragMoveEvent (QDragMoveEvent *)
This event handler is called if a drag is in progress, and when any of the following conditions occur: the cursor enters this widget, the cursor moves within this widget, or a modifier key is pressed on the keyboard while this widget has the focus.
virtual void dropEvent (QDropEvent *)
This event handler is called when the drag is dropped on this widget.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
virtual bool focusNextPrevChild (bool next)
Finds a new widget to give the keyboard focus to, as appropriate for Tab and Shift+Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void inputMethodEvent (QInputMethodEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive Input Method composition events.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void mouseDoubleClickEvent (QMouseEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive mouse double click events for the widget.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Properties
bool accelerated
whether the spin box will accelerate the frequency of the steps when pressing the step Up/Down buttons.
bool acceptableInput
whether the input satisfies the current validation
Qt::Alignment alignment
the alignment of the spin box
ButtonSymbols buttonSymbols
the current button symbol mode
CorrectionMode correctionMode
the mode to correct an QValidator::Intermediate value if editing finishes
bool frame
whether the spin box draws itself with a frame
bool keyboardTracking
whether keyboard tracking is enabled for the spinbox.
bool readOnly
whether the spin box is read only.
QString specialValueText
the special-value text
QString text
the spin box's text, including any prefix and suffix
bool wrapping
whether the spin box is circular.
Additional Inherited Members
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QAbstractSpinBox class provides a spinbox and a line edit to display values.
The class is designed as a common super class for widgets like QSpinBox, QDoubleSpinBox and QDateTimeEdit
Here are the main properties of the class:
text : The text that is displayed in the QAbstractSpinBox.
alignment : The alignment of the text in the QAbstractSpinBox.
wrapping : Whether the QAbstractSpinBox wraps from the minimum value to the maximum value and vica versa.
QAbstractSpinBox provides a virtual stepBy() function that is called whenever the user triggers a step. This function takes an integer value to signify how many steps were taken. E.g. Pressing Qt::Key_Down will trigger a call to stepBy(-1).
QAbstractSpinBox also provide a virtual function stepEnabled() to determine whether stepping up/down is allowed at any point. This function returns a bitset of StepEnabled.
See also
QAbstractSlider, QSpinBox, QDoubleSpinBox, QDateTimeEdit, {Spin Boxes Example}
Definition at line 61 of file qabstractspinbox.h.
Enumerations
ButtonSymbols
enum QAbstractSpinBox::ButtonSymbols
This enum type describes the symbols that can be displayed on the buttons in a spin box.
UpDownArrows Little arrows in the classic style.
PlusMinus + and - symbols.
NoButtons Don't display buttons.
See also
QAbstractSpinBox::buttonSymbols
Enumerator
UpDownArrows
PlusMinus
NoButtons
Definition at line 86 of file qabstractspinbox.h.
 { UpDownArrows, PlusMinus, NoButtons };
CorrectionMode
enum QAbstractSpinBox::CorrectionMode
This enum type describes the mode the spinbox will use to correct an QValidator::Intermediate value if editing finishes.
CorrectToPreviousValue The spinbox will revert to the last valid value.
CorrectToNearestValue The spinbox will revert to the nearest valid value.
See also
correctionMode
Enumerator
CorrectToPreviousValue
CorrectToNearestValue
Definition at line 91 of file qabstractspinbox.h.
 { CorrectToPreviousValue, CorrectToNearestValue };
StepEnabledFlag
enum QAbstractSpinBox::StepEnabledFlag
StepNone
StepUpEnabled
StepDownEnabled
Enumerator
StepNone
StepUpEnabled
StepDownEnabled
Definition at line 82 of file qabstractspinbox.h.
                          { StepNone = 0x00, StepUpEnabled = 0x01,
                            StepDownEnabled = 0x02 };
Constructors and Destructors
QAbstractSpinBox() [1/2]
QAbstractSpinBox::QAbstractSpinBox (QWidget * parent = 0) explicit
Constructs an abstract spinbox with the given parent with default wrapping , and alignment properties.
Definition at line 144 of file qabstractspinbox.cpp.
Referenced by QSpinBox::QSpinBox().
     : QWidget(*new QAbstractSpinBoxPrivate, parent, 0)
 {
     Q_D(QAbstractSpinBox);
     d->init();
 }
~QAbstractSpinBox()
QAbstractSpinBox::~QAbstractSpinBox ()
Called when the QAbstractSpinBox is destroyed.
Definition at line 165 of file qabstractspinbox.cpp.
 {
 }
QAbstractSpinBox() [2/2]
QAbstractSpinBox::QAbstractSpinBox (QAbstractSpinBoxPrivate & dd, QWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 154 of file qabstractspinbox.cpp.
     : QWidget(dd, parent, 0)
 {
     Q_D(QAbstractSpinBox);
     d->init();
 }
Functions
alignment()
Qt::Alignment QAbstractSpinBox::alignment () const
Referenced by hasAcceptableInput().
buttonSymbols()
ButtonSymbols QAbstractSpinBox::buttonSymbols () const
Referenced by setButtonSymbols(), and ~QAbstractSpinBox().
changeEvent()
void QAbstractSpinBox::changeEvent (QEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 825 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     switch (event->type()) {
         case QEvent::StyleChange:
             d->spinClickTimerInterval = style()->styleHint(QStyle::SH_SpinBox_ClickAutoRepeatRate, 0, this);
             d->spinClickThresholdTimerInterval =
                 style()->styleHint(QStyle::SH_SpinBox_ClickAutoRepeatThreshold, 0, this);
             d->reset();
             d->updateEditFieldGeometry();
             break;
         case QEvent::EnabledChange:
             if (!isEnabled()) {
                 d->reset();
             }
             break;
         case QEvent::ActivationChange:
             if (!isActiveWindow()){
                 d->reset();
                 if (d->pendingEmit) // pendingEmit can be true even if it hasn't changed.
                     d->interpret(EmitIfChanged); // E.g. 10 to 10.0
             }
             break;
         default:
             break;
     }
     QWidget::changeEvent(event);
 }
clear
void QAbstractSpinBox::clear () virtual slot
Clears the lineedit of all text but prefix and suffix.
Reimplemented in QDateTimeEdit.
Definition at line 550 of file qabstractspinbox.cpp.
Referenced by keyPressEvent().
 {
     Q_D(QAbstractSpinBox);
     d->edit->setText(d->prefix + d->suffix);
     d->edit->setCursorPosition(d->prefix.size());
     d->cleared = true;
 }
closeEvent()
void QAbstractSpinBox::closeEvent (QCloseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1188 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->reset();
     if (d->pendingEmit)
         d->interpret(EmitIfChanged);
     QWidget::closeEvent(event);
 }
contextMenuEvent()
void QAbstractSpinBox::contextMenuEvent (QContextMenuEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1295 of file qabstractspinbox.cpp.
 {
 #ifdef QT_NO_CONTEXTMENU
     Q_UNUSED(event);
 #else
     Q_D(QAbstractSpinBox);
     QPointer<QMenu> menu = d->edit->createStandardContextMenu();
     if (!menu)
         return;
     d->reset();
     QAction *selAll = new QAction(tr("&Select All"), menu);
     menu->insertAction(d->edit->d_func()->selectAllAction,
                       selAll);
     menu->removeAction(d->edit->d_func()->selectAllAction);
     menu->addSeparator();
     const uint se = stepEnabled();
     QAction *up = menu->addAction(tr("&Step up"));
     up->setEnabled(se & StepUpEnabled);
     QAction *down = menu->addAction(tr("Step &down"));
     down->setEnabled(se & StepDownEnabled);
     menu->addSeparator();
     const QPointer<QAbstractSpinBox> that = this;
     const QPoint pos = (event->reason() == QContextMenuEvent::Mouse)
         ? event->globalPos() : mapToGlobal(QPoint(event->pos().x(), 0)) + QPoint(width() / 2, height() / 2);
     const QAction *action = menu->exec(pos);
     delete static_cast<QMenu *>(menu);
     if (that && action) {
         if (action == up) {
             stepBy(1);
         } else if (action == down) {
             stepBy(-1);
         } else if (action == selAll) {
             selectAll();
         }
     }
     event->accept();
 #endif // QT_NO_CONTEXTMENU
 }
correctionMode()
CorrectionMode QAbstractSpinBox::correctionMode () const
Referenced by setCorrectionMode().
editingFinished
void QAbstractSpinBox::editingFinished () signal
This signal is emitted editing is finished.
This happens when the spinbox loses focus and when enter is pressed.
Referenced by event(), focusOutEvent(), QLineEditPrivate::init(), keyPressEvent(), QDateTimeEdit::keyPressEvent(), QInputDialogDoubleSpinBox::QInputDialogDoubleSpinBox(), and QInputDialogSpinBox::QInputDialogSpinBox().
event()
bool QAbstractSpinBox::event (QEvent * event) virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QDateTimeEdit, and QSpinBox.
Definition at line 762 of file qabstractspinbox.cpp.
Referenced by QSpinBox::event(), and QDateTimeEdit::event().
 {
     Q_D(QAbstractSpinBox);
     switch (event->type()) {
     case QEvent::FontChange:
     case QEvent::StyleChange:
         d->cachedSizeHint = d->cachedMinimumSizeHint = QSize();
         break;
     case QEvent::ApplicationLayoutDirectionChange:
     case QEvent::LayoutDirectionChange:
         d->updateEditFieldGeometry();
         break;
     case QEvent::HoverEnter:
     case QEvent::HoverLeave:
     case QEvent::HoverMove:
         if (const QHoverEvent *he = static_cast<const QHoverEvent *>(event))
             d->updateHoverControl(he->pos());
         break;
     case QEvent::ShortcutOverride:
         if (d->edit->event(event))
             return true;
         break;
 #ifdef QT_KEYPAD_NAVIGATION
     case QEvent::EnterEditFocus:
     case QEvent::LeaveEditFocus:
         if (QApplication::keypadNavigationEnabled()) {
             const bool b = d->edit->event(event);
             d->edit->setSelection(d->edit->displayText().size() - d->suffix.size(),0);
             if (event->type() == QEvent::LeaveEditFocus)
                 emit editingFinished();
             if (b)
                 return true;
         }
         break;
 #endif
     case QEvent::InputMethod:
         return d->edit->event(event);
     default:
         break;
     }
     return QWidget::event(event);
 }
fixup()
void QAbstractSpinBox::fixup (QString & input) const virtual
This virtual function is called by the QAbstractSpinBox if the input is not validated to QValidator::Acceptable when Return is pressed or interpretText() is called.
It will try to change the text so it is valid. Reimplemented in the various subclasses.
Reimplemented in QDateTimeEdit, QDoubleSpinBox, and QSpinBox.
Definition at line 613 of file qabstractspinbox.cpp.
Referenced by QSpinBoxValidator::fixup().
 {
 }
focusInEvent()
void QAbstractSpinBox::focusInEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QDateTimeEdit.
Definition at line 1150 of file qabstractspinbox.cpp.
Referenced by QDateTimeEdit::focusInEvent().
 {
     Q_D(QAbstractSpinBox);
     d->edit->event(event);
     if (event->reason() == Qt::TabFocusReason || event->reason() == Qt::BacktabFocusReason) {
         selectAll();
     }
     QWidget::focusInEvent(event);
 }
focusOutEvent()
void QAbstractSpinBox::focusOutEvent (QFocusEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1165 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     if (d->pendingEmit)
         d->interpret(EmitIfChanged);
     d->reset();
     d->edit->event(event);
     d->updateEdit();
     QWidget::focusOutEvent(event);
 #ifdef QT_KEYPAD_NAVIGATION
     // editingFinished() is already emitted on LeaveEditFocus
     if (!QApplication::keypadNavigationEnabled())
 #endif
     emit editingFinished();
 }
hasAcceptableInput()
bool QAbstractSpinBox::hasAcceptableInput () const
Definition at line 492 of file qabstractspinbox.cpp.
Referenced by QInputDialogSpinBox::keyPressEvent(), QInputDialogDoubleSpinBox::keyPressEvent(), QInputDialogSpinBox::notifyTextChanged(), QInputDialogDoubleSpinBox::notifyTextChanged(), and QInputDialogPrivate::setInputWidget().
 {
     Q_D(const QAbstractSpinBox);
     return d->edit->hasAcceptableInput();
 }
hasFrame()
bool QAbstractSpinBox::hasFrame () const
Definition at line 397 of file qabstractspinbox.cpp.
 {
     Q_D(const QAbstractSpinBox);
     return d->frame;
 }
hideEvent()
void QAbstractSpinBox::hideEvent (QHideEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1202 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->reset();
     if (d->pendingEmit)
         d->interpret(EmitIfChanged);
     QWidget::hideEvent(event);
 }
initStyleOption()
void QAbstractSpinBox::initStyleOption (QStyleOptionSpinBox * option) const protected
Initialize option with the values from this QSpinBox.
This method is useful for subclasses when they need a QStyleOptionSpinBox, but don't want to fill in all the information themselves.
See also
QStyleOption::initFrom()
Definition at line 1706 of file qabstractspinbox.cpp.
Referenced by QDateTimeEdit::initStyleOption(), minimumSizeHint(), paintEvent(), and sizeHint().
 {
     if (!option)
         return;
     Q_D(const QAbstractSpinBox);
     option->initFrom(this);
     option->activeSubControls = QStyle::SC_None;
     option->buttonSymbols = d->buttonSymbols;
     option->subControls = QStyle::SC_SpinBoxFrame | QStyle::SC_SpinBoxEditField;
     if (d->buttonSymbols != QAbstractSpinBox::NoButtons) {
         option->subControls |= QStyle::SC_SpinBoxUp | QStyle::SC_SpinBoxDown;
         if (d->buttonState & Up) {
             option->activeSubControls = QStyle::SC_SpinBoxUp;
         } else if (d->buttonState & Down) {
             option->activeSubControls = QStyle::SC_SpinBoxDown;
         }
     }
     if (d->buttonState) {
         option->state |= QStyle::State_Sunken;
     } else {
         option->activeSubControls = d->hoverControl;
     }
     option->stepEnabled = style()->styleHint(QStyle::SH_SpinControls_DisableOnBounds)
                       ? stepEnabled()
                       : (QAbstractSpinBox::StepDownEnabled|QAbstractSpinBox::StepUpEnabled);
     option->frame = d->frame;
     if (d->readOnly)
         option->state |= QStyle::State_ReadOnly;
 }
inputMethodQuery()
QVariant QAbstractSpinBox::inputMethodQuery (Qt::InputMethodQuery query) const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 752 of file qabstractspinbox.cpp.
 {
     Q_D(const QAbstractSpinBox);
     return d->edit->inputMethodQuery(query);
 }
interpretText()
void QAbstractSpinBox::interpretText ()
This function interprets the text of the spin box.
If the value has changed since last interpretation it will emit signals.
Definition at line 740 of file qabstractspinbox.cpp.
Referenced by QPrintDialogPrivate::_q_okClicked().
 {
     Q_D(QAbstractSpinBox);
     d->interpret(EmitIfChanged);
 }
isAccelerated()
bool QAbstractSpinBox::isAccelerated () const
Definition at line 431 of file qabstractspinbox.cpp.
 {
     Q_D(const QAbstractSpinBox);
     return d->accelerate;
 }
isReadOnly()
bool QAbstractSpinBox::isReadOnly () const
Definition at line 337 of file qabstractspinbox.cpp.
Referenced by keyPressEvent().
 {
     Q_D(const QAbstractSpinBox);
     return d->readOnly;
 }
keyboardTracking()
bool QAbstractSpinBox::keyboardTracking () const
Referenced by setReadOnly().
keyPressEvent()
void QAbstractSpinBox::keyPressEvent (QKeyEvent * event) protected virtual
This function handles keyboard input.
Reimplemented Function
The following keys are handled specifically:
Enter/Return This will reinterpret the text and emit a signal even if the value has not changed since last time a signal was emitted.
Up This will invoke stepBy(1)
Down This will invoke stepBy(-1)
Page up This will invoke stepBy(10)
Page down This will invoke stepBy(-10)
Reimplemented from QWidget.
Reimplemented in QDateTimeEdit.
Definition at line 987 of file qabstractspinbox.cpp.
Referenced by QInputDialogSpinBox::keyPressEvent(), QInputDialogDoubleSpinBox::keyPressEvent(), and QDateTimeEdit::keyPressEvent().
 {
     Q_D(QAbstractSpinBox);
     if (!event->text().isEmpty() && d->edit->cursorPosition() < d->prefix.size())
         d->edit->setCursorPosition(d->prefix.size());
     int steps = 1;
     bool isPgUpOrDown = false;
     switch (event->key()) {
     case Qt::Key_PageUp:
     case Qt::Key_PageDown:
         steps *= 10;
         isPgUpOrDown = true;
     case Qt::Key_Up:
     case Qt::Key_Down: {
 #ifdef QT_KEYPAD_NAVIGATION
         if (QApplication::keypadNavigationEnabled()) {
             // Reserve up/down for nav - use left/right for edit.
             if (!hasEditFocus() && (event->key() == Qt::Key_Up
                                     || event->key() == Qt::Key_Down)) {
                 event->ignore();
                 return;
             }
         }
 #endif
         event->accept();
         const bool up = (event->key() == Qt::Key_PageUp || event->key() == Qt::Key_Up);
         if (!(stepEnabled() & (up ? StepUpEnabled : StepDownEnabled)))
             return;
         if (!up)
             steps *= -1;
         if (style()->styleHint(QStyle::SH_SpinBox_AnimateButton, 0, this)) {
             d->buttonState = (Keyboard | (up ? Up : Down));
         }
         if (d->spinClickTimerId == -1)
             stepBy(steps);
         if(event->isAutoRepeat() && !isPgUpOrDown) {
             if(d->spinClickThresholdTimerId == -1 && d->spinClickTimerId == -1) {
                 d->updateState(up, true);
             }
         }
 #ifndef QT_NO_ACCESSIBILITY
         QAccessible::updateAccessibility(this, 0, QAccessible::ValueChanged);
 #endif
         return;
     }
 #ifdef QT_KEYPAD_NAVIGATION
     case Qt::Key_Left:
     case Qt::Key_Right:
         if (QApplication::keypadNavigationEnabled() && !hasEditFocus()) {
             event->ignore();
             return;
         }
         break;
     case Qt::Key_Back:
         if (QApplication::keypadNavigationEnabled() && !hasEditFocus()) {
             event->ignore();
             return;
         }
         break;
 #endif
     case Qt::Key_Enter:
     case Qt::Key_Return:
         d->edit->d_func()->control->clearUndo();
         d->interpret(d->keyboardTracking ? AlwaysEmit : EmitIfChanged);
         selectAll();
         event->ignore();
         emit editingFinished();
         return;
 #ifdef QT_KEYPAD_NAVIGATION
     case Qt::Key_Select:
         if (QApplication::keypadNavigationEnabled()) {
             // Toggles between left/right moving cursor and inc/dec.
             setEditFocus(!hasEditFocus());
         }
         return;
 #endif
 #ifdef Q_WS_X11 // only X11
     case Qt::Key_U:
         if (event->modifiers() & Qt::ControlModifier) {
             event->accept();
             if (!isReadOnly())
                 clear();
             return;
         }
         break;
 #endif
     case Qt::Key_End:
     case Qt::Key_Home:
         if (event->modifiers() & Qt::ShiftModifier) {
             int currentPos = d->edit->cursorPosition();
             const QString text = d->edit->displayText();
             if (event->key() == Qt::Key_End) {
                 if ((currentPos == 0 && !d->prefix.isEmpty()) || text.size() - d->suffix.size() <= currentPos) {
                     break; // let lineedit handle this
                 } else {
                     d->edit->setSelection(currentPos, text.size() - d->suffix.size() - currentPos);
                 }
             } else {
                 if ((currentPos == text.size() && !d->suffix.isEmpty()) || currentPos <= d->prefix.size()) {
                     break; // let lineedit handle this
                 } else {
                     d->edit->setSelection(currentPos, d->prefix.size() - currentPos);
                 }
             }
             event->accept();
             return;
         }
         break;
     default:
 #ifndef QT_NO_SHORTCUT
         if (event == QKeySequence::SelectAll) {
             selectAll();
             event->accept();
             return;
         }
 #endif
         break;
     }
     d->edit->event(event);
     if (!isVisible())
         d->ignoreUpdateEdit = true;
 }
keyReleaseEvent()
void QAbstractSpinBox::keyReleaseEvent (QKeyEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1121 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     if (d->buttonState & Keyboard && !event->isAutoRepeat())  {
         d->reset();
     } else {
         d->edit->event(event);
     }
 }
lineEdit()
QLineEdit * QAbstractSpinBox::lineEdit () const protected
This function returns a pointer to the line edit of the spin box.
Definition at line 679 of file qabstractspinbox.cpp.
Referenced by QInputDialogDoubleSpinBox::QInputDialogDoubleSpinBox(), QInputDialogSpinBox::QInputDialogSpinBox(), setButtonSymbols(), and setLineEdit().
 {
     Q_D(const QAbstractSpinBox);
     return d->edit;
 }
minimumSizeHint()
QSize QAbstractSpinBox::minimumSizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 918 of file qabstractspinbox.cpp.
 {
     Q_D(const QAbstractSpinBox);
     if (d->cachedMinimumSizeHint.isEmpty()) {
         ensurePolished();
         const QFontMetrics fm(fontMetrics());
         int h = d->edit->minimumSizeHint().height();
         int w = fm.width(QLatin1String("1000"));
         w += 2; // cursor blinking space
         QStyleOptionSpinBox opt;
         initStyleOption(&opt);
         QSize hint(w, h);
         QSize extra(35, 6);
         opt.rect.setSize(hint + extra);
         extra += hint - style()->subControlRect(QStyle::CC_SpinBox, &opt,
                                                 QStyle::SC_SpinBoxEditField, this).size();
         // get closer to final result by repeating the calculation
         opt.rect.setSize(hint + extra);
         extra += hint - style()->subControlRect(QStyle::CC_SpinBox, &opt,
                                                 QStyle::SC_SpinBoxEditField, this).size();
         hint += extra;
         opt.rect = rect();
         d->cachedMinimumSizeHint = style()->sizeFromContents(QStyle::CT_SpinBox, &opt, hint, this)
                                    .expandedTo(QApplication::globalStrut());
     }
     return d->cachedMinimumSizeHint;
 }
mouseMoveEvent()
void QAbstractSpinBox::mouseMoveEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1342 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->updateHoverControl(event->pos());
     // If we have a timer ID, update the state
     if (d->spinClickTimerId != -1 && d->buttonSymbols != NoButtons) {
         const StepEnabled se = stepEnabled();
         if ((se & StepUpEnabled) && d->hoverControl == QStyle::SC_SpinBoxUp)
             d->updateState(true);
         else if ((se & StepDownEnabled) && d->hoverControl == QStyle::SC_SpinBoxDown)
             d->updateState(false);
         else
             d->reset();
         event->accept();
     }
 }
mousePressEvent()
void QAbstractSpinBox::mousePressEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QDateTimeEdit.
Definition at line 1365 of file qabstractspinbox.cpp.
Referenced by QInputDialogSpinBox::mousePressEvent(), QInputDialogDoubleSpinBox::mousePressEvent(), and QDateTimeEdit::mousePressEvent().
 {
     Q_D(QAbstractSpinBox);
     if (event->button() != Qt::LeftButton || d->buttonState != None) {
         return;
     }
     d->updateHoverControl(event->pos());
     event->accept();
     const StepEnabled se = (d->buttonSymbols == NoButtons) ? StepEnabled(StepNone) : stepEnabled();
     if ((se & StepUpEnabled) && d->hoverControl == QStyle::SC_SpinBoxUp) {
         d->updateState(true);
     } else if ((se & StepDownEnabled) && d->hoverControl == QStyle::SC_SpinBoxDown) {
         d->updateState(false);
     } else {
         event->ignore();
     }
 }
mouseReleaseEvent()
void QAbstractSpinBox::mouseReleaseEvent (QMouseEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 1389 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     if ((d->buttonState & Mouse) != 0)
         d->reset();
     event->accept();
 }
paintEvent()
void QAbstractSpinBox::paintEvent (QPaintEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QDateTimeEdit.
Definition at line 954 of file qabstractspinbox.cpp.
Referenced by QDateTimeEdit::paintEvent().
 {
     QStyleOptionSpinBox opt;
     initStyleOption(&opt);
     QStylePainter p(this);
     p.drawComplexControl(QStyle::CC_SpinBox, opt);
 }
resizeEvent()
void QAbstractSpinBox::resizeEvent (QResizeEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 859 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     QWidget::resizeEvent(event);
     d->updateEditFieldGeometry();
     update();
 }
selectAll
void QAbstractSpinBox::selectAll () slot
Selects all the text in the spinbox except the prefix and suffix.
Definition at line 533 of file qabstractspinbox.cpp.
Referenced by QCalendarWidgetPrivate::_q_yearClicked(), contextMenuEvent(), focusInEvent(), keyPressEvent(), QDateTimeEdit::keyPressEvent(), and stepBy().
 {
     Q_D(QAbstractSpinBox);
     if (!d->specialValue()) {
         const int tmp = d->edit->displayText().size() - d->suffix.size();
         d->edit->setSelection(tmp, -(tmp - d->prefix.size()));
     } else {
         d->edit->selectAll();
     }
 }
setAccelerated()
void QAbstractSpinBox::setAccelerated (bool on)
Definition at line 425 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->accelerate = accelerate;
 }
setAlignment()
void QAbstractSpinBox::setAlignment (Qt::Alignment flag)
Definition at line 522 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->edit->setAlignment(flag);
 }
setButtonSymbols()
void QAbstractSpinBox::setButtonSymbols (ButtonSymbols bs)
Definition at line 211 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     if (d->buttonSymbols != buttonSymbols) {
         d->buttonSymbols = buttonSymbols;
         d->updateEditFieldGeometry();
         update();
     }
 }
setCorrectionMode()
void QAbstractSpinBox::setCorrectionMode (CorrectionMode cm)
Definition at line 468 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->correctionMode = correctionMode;
 }
setFrame()
void QAbstractSpinBox::setFrame (bool enable)
Definition at line 404 of file qabstractspinbox.cpp.
Referenced by QDefaultItemEditorFactory::createEditor(), and QCalendarWidgetPrivate::createNavigationBar().
 {
     Q_D(QAbstractSpinBox);
     d->frame = enable;
     update();
     d->updateEditFieldGeometry();
 }
setKeyboardTracking()
void QAbstractSpinBox::setKeyboardTracking (bool kt)
Definition at line 380 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->keyboardTracking = enable;
 }
setLineEdit()
void QAbstractSpinBox::setLineEdit (QLineEdit * lineEdit) protected
Sets the line edit of the spinbox to be lineEdit instead of the current line edit widget.
lineEdit can not be 0.
QAbstractSpinBox takes ownership of the new lineEdit
If QLineEdit::validator() for the lineEdit returns 0, the internal validator of the spinbox will be set on the line edit.
Definition at line 699 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     if (!lineEdit) {
         Q_ASSERT(lineEdit);
         return;
     }
     delete d->edit;
     d->edit = lineEdit;
     if (!d->edit->validator())
         d->edit->setValidator(d->validator);
     if (d->edit->parent() != this)
         d->edit->setParent(this);
     d->edit->setFrame(false);
     d->edit->setFocusProxy(this);
     d->edit->setAcceptDrops(false);
     if (d->type != QVariant::Invalid) {
         connect(d->edit, SIGNAL(textChanged(QString)),
                 this, SLOT(_q_editorTextChanged(QString)));
         connect(d->edit, SIGNAL(cursorPositionChanged(int,int)),
                 this, SLOT(_q_editorCursorPositionChanged(int,int)));
     }
     d->updateEditFieldGeometry();
     d->edit->setContextMenuPolicy(Qt::NoContextMenu);
     if (isVisible())
         d->edit->show();
     if (isVisible())
         d->updateEdit();
 }
setReadOnly()
void QAbstractSpinBox::setReadOnly (bool r)
Definition at line 343 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->readOnly = enable;
     d->edit->setReadOnly(enable);
     update();
 }
setSpecialValueText()
void QAbstractSpinBox::setSpecialValueText (const QString & txt)
Definition at line 280 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->specialValueText = specialValueText;
     d->cachedSizeHint = QSize(); // minimumSizeHint doesn't care about specialValueText
     d->clearCache();
     d->updateEdit();
 }
setWrapping()
void QAbstractSpinBox::setWrapping (bool w)
Definition at line 313 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->wrapping = wrapping;
 }
showEvent()
void QAbstractSpinBox::showEvent (QShowEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Definition at line 809 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     d->reset();
     if (d->ignoreUpdateEdit) {
         d->ignoreUpdateEdit = false;
     } else {
         d->updateEdit();
     }
 }
sizeHint()
QSize QAbstractSpinBox::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QDateTimeEdit.
Definition at line 872 of file qabstractspinbox.cpp.
Referenced by QCalendarWidgetPrivate::_q_yearClicked().
 {
     Q_D(const QAbstractSpinBox);
     if (d->cachedSizeHint.isEmpty()) {
         ensurePolished();
         const QFontMetrics fm(fontMetrics());
         int h = d->edit->sizeHint().height();
         int w = 0;
         QString s;
         s = d->prefix + d->textFromValue(d->minimum) + d->suffix + QLatin1Char(' ');
         s.truncate(18);
         w = qMax(w, fm.width(s));
         s = d->prefix + d->textFromValue(d->maximum) + d->suffix + QLatin1Char(' ');
         s.truncate(18);
         w = qMax(w, fm.width(s));
         if (d->specialValueText.size()) {
             s = d->specialValueText;
             w = qMax(w, fm.width(s));
         }
         w += 2; // cursor blinking space
         QStyleOptionSpinBox opt;
         initStyleOption(&opt);
         QSize hint(w, h);
         QSize extra(35, 6);
         opt.rect.setSize(hint + extra);
         extra += hint - style()->subControlRect(QStyle::CC_SpinBox, &opt,
                                                 QStyle::SC_SpinBoxEditField, this).size();
         // get closer to final result by repeating the calculation
         opt.rect.setSize(hint + extra);
         extra += hint - style()->subControlRect(QStyle::CC_SpinBox, &opt,
                                                 QStyle::SC_SpinBoxEditField, this).size();
         hint += extra;
         opt.rect = rect();
         d->cachedSizeHint = style()->sizeFromContents(QStyle::CT_SpinBox, &opt, hint, this)
                             .expandedTo(QApplication::globalStrut());
     }
     return d->cachedSizeHint;
 }
specialValueText()
QString QAbstractSpinBox::specialValueText () const
Referenced by setButtonSymbols(), and setSpecialValueText().
stepBy()
void QAbstractSpinBox::stepBy (int steps) virtual
Virtual function that is called whenever the user triggers a step.
The steps parameter indicates how many steps were taken, e.g. Pressing Qt::Key_Down will trigger a call to stepBy(-1), whereas pressing Qt::Key_Prior will trigger a call to stepBy(10).
If you subclass QAbstractSpinBox you must reimplement this function. Note that this function is called even if the resulting value will be outside the bounds of minimum and maximum. It's this function's job to handle these situations.
Reimplemented in QDateTimeEdit.
Definition at line 651 of file qabstractspinbox.cpp.
Referenced by contextMenuEvent(), keyPressEvent(), stepDown(), stepUp(), timerEvent(), and wheelEvent().
 {
     Q_D(QAbstractSpinBox);
     const QVariant old = d->value;
     QString tmp = d->edit->displayText();
     int cursorPos = d->edit->cursorPosition();
     bool dontstep = false;
     EmitPolicy e = EmitIfChanged;
     if (d->pendingEmit) {
         dontstep = validate(tmp, cursorPos) != QValidator::Acceptable;
         d->cleared = false;
         d->interpret(NeverEmit);
         if (d->value != old)
             e = AlwaysEmit;
     }
     if (!dontstep) {
         d->setValue(d->bound(d->value + (d->singleStep * steps), old, steps), e);
     } else if (e == AlwaysEmit) {
         d->emitSignals(e, old);
     }
     selectAll();
 }
stepDown
void QAbstractSpinBox::stepDown () slot
Steps down by one linestep Calling this slot is analogous to calling stepBy(-1);.
See also
stepBy(), stepUp()
Definition at line 634 of file qabstractspinbox.cpp.
Referenced by QAccessibleAbstractSpinBox::doAction(), and QAccessibleSpinBox::doAction().
 {
     stepBy(-1);
 }
stepEnabled()
QAbstractSpinBox::StepEnabled QAbstractSpinBox::stepEnabled () const protected virtual
Virtual function that determines whether stepping up and down is legal at any given time.
The up arrow will be painted as disabled unless (stepEnabled() & StepUpEnabled) != 0.
The default implementation will return (StepUpEnabled| StepDownEnabled) if wrapping is turned on. Else it will return StepDownEnabled if value is > minimum() or'ed with StepUpEnabled if value < maximum().
If you subclass QAbstractSpinBox you will need to reimplement this function.
See also
QSpinBox::minimum(), QSpinBox::maximum(), wrapping()
Reimplemented in QDateTimeEdit.
Definition at line 577 of file qabstractspinbox.cpp.
Referenced by contextMenuEvent(), keyPressEvent(), mouseMoveEvent(), mousePressEvent(), timerEvent(), and wheelEvent().
 {
     Q_D(const QAbstractSpinBox);
     if (d->readOnly || d->type == QVariant::Invalid)
         return StepNone;
     if (d->wrapping)
         return StepEnabled(StepUpEnabled | StepDownEnabled);
     StepEnabled ret = StepNone;
     if (d->variantCompare(d->value, d->maximum) < 0) {
         ret |= StepUpEnabled;
     }
     if (d->variantCompare(d->value, d->minimum) > 0) {
         ret |= StepDownEnabled;
     }
     return ret;
 }
stepUp
void QAbstractSpinBox::stepUp () slot
Steps up by one linestep Calling this slot is analogous to calling stepBy(1);.
See also
stepBy(), stepDown()
Definition at line 623 of file qabstractspinbox.cpp.
Referenced by QAccessibleAbstractSpinBox::doAction(), and QAccessibleSpinBox::doAction().
 {
     stepBy(1);
 }
text()
QString QAbstractSpinBox::text () const
Referenced by QCalendarWidgetPrivate::_q_yearEditingFinished(), QDateTimeEdit::dateTimeFromText(), keyPressEvent(), setButtonSymbols(), QSpinBox::valueFromText(), and QDoubleSpinBox::valueFromText().
timerEvent()
void QAbstractSpinBox::timerEvent (QTimerEvent * event) protected virtual
Reimplemented Function
Reimplemented from QObject.
Definition at line 1246 of file qabstractspinbox.cpp.
 {
     Q_D(QAbstractSpinBox);
     bool doStep = false;
     if (event->timerId() == d->spinClickThresholdTimerId) {
         killTimer(d->spinClickThresholdTimerId);
         d->spinClickThresholdTimerId = -1;
         d->effectiveSpinRepeatRate = d->buttonState & Keyboard
                                      ? getKeyboardAutoRepeatRate()
                                      : d->spinClickTimerInterval;
         d->spinClickTimerId = startTimer(d->effectiveSpinRepeatRate);
         doStep = true;
     } else if (event->timerId() == d->spinClickTimerId) {
         if (d->accelerate) {
             d->acceleration = d->acceleration + (int)(d->effectiveSpinRepeatRate * 0.05);
             if (d->effectiveSpinRepeatRate - d->acceleration >= 10) {
                 killTimer(d->spinClickTimerId);
                 d->spinClickTimerId = startTimer(d->effectiveSpinRepeatRate - d->acceleration);
             }
         }
         doStep = true;
     }
     if (doStep) {
         const StepEnabled st = stepEnabled();
         if (d->buttonState & Up) {
             if (!(st & StepUpEnabled)) {
                 d->reset();
             } else {
                 stepBy(1);
             }
         } else if (d->buttonState & Down) {
             if (!(st & StepDownEnabled)) {
                 d->reset();
             } else {
                 stepBy(-1);
             }
         }
         return;
     }
     QWidget::timerEvent(event);
     return;
 }
validate()
QValidator::State QAbstractSpinBox::validate (QString & input, int & pos) const virtual
This virtual function is called by the QAbstractSpinBox to determine whether input is valid.
The pos parameter indicates the position in the string. Reimplemented in the various subclasses.
Reimplemented in QDateTimeEdit, QDoubleSpinBox, and QSpinBox.
Definition at line 601 of file qabstractspinbox.cpp.
Referenced by stepBy(), and QSpinBoxValidator::validate().
 {
     return QValidator::Acceptable;
 }
wheelEvent()
void QAbstractSpinBox::wheelEvent (QWheelEvent * event) protected virtual
Reimplemented Function
Reimplemented from QWidget.
Reimplemented in QDateTimeEdit.
Definition at line 1137 of file qabstractspinbox.cpp.
Referenced by QDateTimeEdit::wheelEvent().
 {
     const int steps = (event->delta() > 0 ? 1 : -1);
     if (stepEnabled() & (steps > 0 ? StepUpEnabled : StepDownEnabled))
         stepBy(event->modifiers() & Qt::ControlModifier ? steps * 10 : steps);
     event->accept();
 }
wrapping()
bool QAbstractSpinBox::wrapping () const
Referenced by setSpecialValueText(), and setWrapping().
Properties
accelerated
QAbstractSpinBox::accelerated private
whether the spin box will accelerate the frequency of the steps when pressing the step Up/Down buttons.
Since
4.2
If enabled the spin box will increase/decrease the value faster the longer you hold the button down.
Definition at line 74 of file qabstractspinbox.h.
acceptableInput
QAbstractSpinBox::acceptableInput private
whether the input satisfies the current validation
Since
4.2
See also
validate(), fixup(), correctionMode
Definition at line 76 of file qabstractspinbox.h.
alignment
Qt::Alignment QAbstractSpinBox::alignment private
the alignment of the spin box
Possible Values are Qt::AlignLeft, Qt::AlignRight, and Qt::AlignHCenter.
By default, the alignment is Qt::AlignLeft
Attempting to set the alignment to an illegal flag combination does nothing.
See also
Qt::Alignment
Definition at line 69 of file qabstractspinbox.h.
buttonSymbols
QAbstractSpinBox::ButtonSymbols QAbstractSpinBox::buttonSymbols private
the current button symbol mode
The possible values can be either UpDownArrows or PlusMinus. The default is UpDownArrows.
Note that some styles might render PlusMinus and UpDownArrows identically.
See also
ButtonSymbols
Definition at line 71 of file qabstractspinbox.h.
correctionMode
QAbstractSpinBox::CorrectionMode QAbstractSpinBox::correctionMode private
the mode to correct an QValidator::Intermediate value if editing finishes
Since
4.2
The default mode is QAbstractSpinBox::CorrectToPreviousValue.
See also
acceptableInput, validate(), fixup()
Definition at line 75 of file qabstractspinbox.h.
frame
QAbstractSpinBox::frame private
whether the spin box draws itself with a frame
If enabled (the default) the spin box draws itself inside a frame, otherwise the spin box draws itself without any frame.
Definition at line 68 of file qabstractspinbox.h.
keyboardTracking
bool QAbstractSpinBox::keyboardTracking private
whether keyboard tracking is enabled for the spinbox.
Since
4.3
If keyboard tracking is enabled (the default), the spinbox emits the valueChanged() signal while the new value is being entered from the keyboard.
E.g. when the user enters the value 600 by typing 6, 0, and 0, the spinbox emits 3 signals with the values 6, 60, and 600 respectively.
If keyboard tracking is disabled, the spinbox doesn't emit the valueChanged() signal while typing. It emits the signal later, when the return key is pressed, when keyboard focus is lost, or when other spinbox functionality is used, e.g. pressing an arrow key.
Definition at line 77 of file qabstractspinbox.h.
readOnly
QAbstractSpinBox::readOnly private
whether the spin box is read only.
In read-only mode, the user can still copy the text to the clipboard, or drag and drop the text; but cannot edit it.
The QLineEdit in the QAbstractSpinBox does not show a cursor in read-only mode.
See also
QLineEdit::readOnly
Definition at line 70 of file qabstractspinbox.h.
specialValueText
QString QAbstractSpinBox::specialValueText private
the special-value text
If set, the spin box will display this text instead of a numeric value whenever the current value is equal to minimum(). Typical use is to indicate that this choice has a special (default) meaning.
For example, if your spin box allows the user to choose a scale factor (or zoom level) for displaying an image, and your application is able to automatically choose one that will enable the image to fit completely within the display window, you can set up the spin box like this:
    QSpinBox *zoomSpinBox = new QSpinBox;
    zoomSpinBox->setRange(0, 1000);
    zoomSpinBox->setSingleStep(10);
    zoomSpinBox->setSuffix("%");
    zoomSpinBox->setSpecialValueText(tr("Automatic"));
    zoomSpinBox->setValue(100);
The user will then be able to choose a scale from 1% to 1000% or select "Auto" to leave it up to the application to choose. Your code must then interpret the spin box value of 0 as a request from the user to scale the image to fit inside the window.
All values are displayed with the prefix and suffix (if set), except for the special value, which only shows the special value text. This special text is passed in the QSpinBox::valueChanged() signal that passes a QString.
To turn off the special-value text display, call this function with an empty string. The default is no special-value text, i.e. the numeric value is shown as usual.
If no special-value text is set, specialValueText() returns an empty string.
Definition at line 72 of file qabstractspinbox.h.
text
QString QAbstractSpinBox::text private
the spin box's text, including any prefix and suffix
There is no default text.
Definition at line 73 of file qabstractspinbox.h.
Referenced by QAccessibleAbstractSpinBox::text().
wrapping
bool QAbstractSpinBox::wrapping private
whether the spin box is circular.
If wrapping is true stepping up from maximum() value will take you to the minimum() value and vica versa. Wrapping only make sense if you have minimum() and maximum() values set.
QSpinBox *spinBox = new QSpinBox(this);
spinBox->setRange(0, 100);
spinBox->setWrapping(true);
spinBox->setValue(100);
spinBox->stepBy(1);
// value is 0
See also
QSpinBox::minimum(), QSpinBox::maximum()
Definition at line 67 of file qabstractspinbox.h.
The documentation for this class was generated from the following files:
/src/gui/widgets/qabstractspinbox.h
/src/gui/widgets/qabstractspinbox.cpp