Qt 4.8: QGraphicsBlurEffect Class Reference
QGraphicsBlurEffect Class Reference
The QGraphicsBlurEffect class provides a blur effect.
#include <qgraphicseffect.h>
Public Types
enum BlurHint { PerformanceHint = 0x00, QualityHint = 0x01, AnimationHint = 0x02 }
This enum describes the possible hints that can be used to control how blur effects are applied.
Public Types inherited from QGraphicsEffect
enum ChangeFlag { SourceAttached = 0x1, SourceDetached = 0x2, SourceBoundingRectChanged = 0x4, SourceInvalidated = 0x8 }
This enum describes what has changed in QGraphicsEffectSource.
enum PixmapPadMode { NoPad, PadToTransparentBorder, PadToEffectiveBoundingRect }
This enum describes how the pixmap returned from sourcePixmap should be padded.
Public Slots
void setBlurHints (BlurHints hints)
void setBlurRadius (qreal blurRadius)
Public Slots inherited from QGraphicsEffect
void setEnabled (bool enable)
void update ()
Schedules a redraw of the effect.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void blurHintsChanged (BlurHints hints)
This signal is emitted whenever the effect's blur hints changes.
void blurRadiusChanged (qreal blurRadius)
This signal is emitted whenever the effect's blur radius changes.
Signals inherited from QGraphicsEffect
void enabledChanged (bool enabled)
This signal is emitted whenever the effect is enabled or disabled.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
BlurHints blurHints () const
qreal blurRadius () const
QRectF boundingRectFor (const QRectF &rect) const
Reimplemented Function
QGraphicsBlurEffect (QObject *parent=0)
Constructs a new QGraphicsBlurEffect instance.
~QGraphicsBlurEffect ()
Destroys the effect.
Public Functions inherited from QGraphicsEffect
QRectF boundingRect () const
Returns the effective bounding rectangle for this effect, i.e., the bounding rectangle of the source in device coordinates, adjusted by any margins applied by the effect itself.
bool isEnabled () const
QGraphicsEffect (QObject *parent=0)
Constructs a new QGraphicsEffect instance having the specified parent.
QGraphicsEffectSource * source () const
Returns a pointer to the source, which provides extra context information that can be useful for the effect.
virtual ~QGraphicsEffect ()
Removes the effect from the source, and destroys the graphics effect.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void draw (QPainter *painter)
Reimplemented Function
Protected Functions inherited from QGraphicsEffect
void drawSource (QPainter *painter)
Draws the source directly using the given painter.
QGraphicsEffect (QGraphicsEffectPrivate &d, QObject *parent=0)
QRectF sourceBoundingRect (Qt::CoordinateSystem system=Qt::LogicalCoordinates) const
Returns the bounding rectangle of the source mapped to the given system.
virtual void sourceChanged (ChangeFlags flags)
This virtual function is called by QGraphicsEffect to notify the effect that the source has changed.
bool sourceIsPixmap () const
Returns true if the source effectively is a pixmap, e.g., a QGraphicsPixmapItem.
QPixmap sourcePixmap (Qt::CoordinateSystem system=Qt::LogicalCoordinates, QPoint *offset=0, PixmapPadMode mode=PadToEffectiveBoundingRect) const
Returns a pixmap with the source painted into it.
void updateBoundingRect ()
This function notifies the effect framework when the effect's bounding rectangle has changed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
BlurHints blurHints
the blur hint of the effect.
qreal blurRadius
the blur radius of the effect.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QGraphicsBlurEffect class provides a blur effect.
Since
4.6
A blur effect blurs the source. This effect is useful for reducing details, such as when the source loses focus and you want to draw attention to other elements. The level of detail can be modified using the setBlurRadius() function. Use setBlurHints() to choose the blur hints.
By default, the blur radius is 5 pixels. The blur radius is specified in device coordinates.
See also
QGraphicsDropShadowEffect, QGraphicsColorizeEffect, QGraphicsOpacityEffect
Definition at line 159 of file qgraphicseffect.h.
Enumerations
BlurHint
enum QGraphicsBlurEffect::BlurHint
This enum describes the possible hints that can be used to control how blur effects are applied.
Since
4.6
The hints might not have an effect in all the paint engines.
PerformanceHint Indicates that rendering performance is the most important factor, at the potential cost of lower quality.
QualityHint Indicates that rendering quality is the most important factor, at the potential cost of lower performance.
AnimationHint Indicates that the blur radius is going to be animated, hinting that the implementation can keep a cache of blurred verisons of the source. Do not use this hint if the source is going to be dynamically changing.
See also
blurHints(), setBlurHints()
Enumerator
PerformanceHint
QualityHint
AnimationHint
Definition at line 166 of file qgraphicseffect.h.
                   {
         PerformanceHint = 0x00,
         QualityHint = 0x01,
         AnimationHint = 0x02
     };
Constructors and Destructors
QGraphicsBlurEffect()
QGraphicsBlurEffect::QGraphicsBlurEffect (QObject * parent = 0)
Constructs a new QGraphicsBlurEffect instance.
The parent parameter is passed to QGraphicsEffect's constructor.
Definition at line 802 of file qgraphicseffect.cpp.
     : QGraphicsEffect(*new QGraphicsBlurEffectPrivate, parent)
 {
     Q_D(QGraphicsBlurEffect);
     d->filter->setBlurHints(QGraphicsBlurEffect::PerformanceHint);
 }
~QGraphicsBlurEffect()
QGraphicsBlurEffect::~QGraphicsBlurEffect ()
Destroys the effect.
Definition at line 812 of file qgraphicseffect.cpp.
 {
 }
Functions
blurHints()
BlurHints QGraphicsBlurEffect::blurHints () const
Referenced by setBlurRadius().
blurHintsChanged
void QGraphicsBlurEffect::blurHintsChanged (BlurHints hints) signal
This signal is emitted whenever the effect's blur hints changes.
The hints parameter holds the effect's new blur hints.
Referenced by setBlurHints().
blurRadius()
qreal QGraphicsBlurEffect::blurRadius () const
Referenced by ~QGraphicsBlurEffect().
blurRadiusChanged
void QGraphicsBlurEffect::blurRadiusChanged (qreal radius) signal
This signal is emitted whenever the effect's blur radius changes.
The radius parameter holds the effect's new blur radius.
Referenced by setBlurRadius().
boundingRectFor()
QRectF QGraphicsBlurEffect::boundingRectFor (const QRectF & rect) const virtual
Reimplemented Function
Reimplemented from QGraphicsEffect.
Definition at line 900 of file qgraphicseffect.cpp.
 {
     Q_D(const QGraphicsBlurEffect);
     return d->filter->boundingRectFor(rect);
 }
draw()
void QGraphicsBlurEffect::draw (QPainter * painter) protected virtual
Reimplemented Function
Implements QGraphicsEffect.
Definition at line 909 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsBlurEffect);
     if (d->filter->radius() < 1) {
         drawSource(painter);
         return;
     }
     PixmapPadMode mode = PadToEffectiveBoundingRect;
     if (painter->paintEngine()->type() == QPaintEngine::OpenGL2)
         mode = NoPad;
     QPoint offset;
     QPixmap pixmap = sourcePixmap(Qt::LogicalCoordinates, &offset, mode);
     if (pixmap.isNull())
         return;
     d->filter->draw(painter, offset, pixmap);
 }
setBlurHints
void QGraphicsBlurEffect::setBlurHints (BlurHints hints) slot
Definition at line 877 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsBlurEffect);
     if (d->filter->blurHints() == hints)
         return;
     d->filter->setBlurHints(hints);
     emit blurHintsChanged(hints);
 }
setBlurRadius
void QGraphicsBlurEffect::setBlurRadius (qreal blurRadius) slot
Definition at line 837 of file qgraphicseffect.cpp.
 {
     Q_D(QGraphicsBlurEffect);
     if (qFuzzyCompare(d->filter->radius(), radius))
         return;
     d->filter->setRadius(radius);
     updateBoundingRect();
     emit blurRadiusChanged(radius);
 }
Properties
blurHints
QGraphicsBlurEffect::BlurHints QGraphicsBlurEffect::blurHints private
the blur hint of the effect.
Use the PerformanceHint hint to say that you want a faster blur, the QualityHint hint to say that you prefer a higher quality blur, or the AnimationHint when you want to animate the blur radius.
By default, the blur hint is PerformanceHint.
Definition at line 164 of file qgraphicseffect.h.
blurRadius
qreal QGraphicsBlurEffect::blurRadius private
the blur radius of the effect.
Using a smaller radius results in a sharper appearance, whereas a bigger radius results in a more blurred appearance.
By default, the blur radius is 5 pixels.
The radius is given in device coordinates, meaning it is unaffected by scale.
Definition at line 163 of file qgraphicseffect.h.
The documentation for this class was generated from the following files:
/src/gui/effects/qgraphicseffect.h
/src/gui/effects/qgraphicseffect.cpp