Qt 4.8: QStringRef Class Reference
QStringRef Class Reference
The QStringRef class provides a thin wrapper around QString substrings.
#include <qstring.h>
Public Functions
QStringRef appendTo (QString *string) const
Appends the string reference to string, and returns a new reference to the combined string data.
const QChar at (int i) const
Returns the character at the given index position in the string reference.
void clear ()
Clears the contents of the string reference by making it null and empty.
int compare (const QString &s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int compare (const QStringRef &s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
int compare (QLatin1String s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
const QChar * constData () const
Same as unicode().
QBool contains (const QString &str, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
Returns true if this string reference contains an occurrence of the string str; otherwise returns false.
QBool contains (QChar ch, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
QBool contains (QLatin1String str, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
QBool contains (const QStringRef &str, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
int count () const
Returns the number of characters referred to by the string reference.
int count (const QString &s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
Returns the number of (potentially overlapping) occurrences of the string str in this string reference.
int count (QChar c, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
int count (const QStringRef &s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
const QChar * data () const
Same as unicode().
bool endsWith (const QString &s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
Returns true if the string reference ends with str; otherwise returns false.
bool endsWith (QLatin1String s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
bool endsWith (QChar c, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
bool endsWith (const QStringRef &c, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
int indexOf (const QString &str, int from=0, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
Returns the index position of the first occurrence of the string str in this string reference, searching forward from index position from.
int indexOf (QChar ch, int from=0, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
int indexOf (QLatin1String str, int from=0, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
Returns the index position of the first occurrence of the string str in this string reference, searching forward from index position from.
int indexOf (const QStringRef &str, int from=0, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
bool isEmpty () const
Returns true if the string reference has no characters; otherwise returns false.
bool isNull () const
Returns true if string() returns a null pointer or a pointer to a null string; otherwise returns true.
int lastIndexOf (const QString &str, int from=-1, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
Returns the index position of the last occurrence of the string str in this string reference, searching backward from index position from.
int lastIndexOf (QChar ch, int from=-1, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
int lastIndexOf (QLatin1String str, int from=-1, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
int lastIndexOf (const QStringRef &str, int from=-1, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
int length () const
Returns the number of characters referred to by the string reference.
int localeAwareCompare (const QString &s) const
Compares this string with the other string and returns an integer less than, equal to, or greater than zero if this string is less than, equal to, or greater than the other string.
int localeAwareCompare (const QStringRef &s) const
Compares this string with the other string and returns an integer less than, equal to, or greater than zero if this string is less than, equal to, or greater than the other string.
QStringRef & operator= (const QStringRef &other)
Assigns the other string reference to this string reference, and returns the result.
QStringRef & operator= (const QString *string)
Constructs a string reference to the given string and assigns it to this string reference, returning the result.
int position () const
Returns the starting position in the referenced string that is referred to by the string reference.
QStringRef ()
Constructs an empty string reference.
QStringRef (const QString *string, int position, int size)
Constructs a string reference to the range of characters in the given string specified by the starting position and length in characters.
QStringRef (const QString *string)
Constructs a string reference to the given string.
QStringRef (const QStringRef &other)
Constructs a copy of the other string reference.
int size () const
Returns the number of characters referred to by the string reference.
bool startsWith (const QString &s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
Returns true if the string reference starts with str; otherwise returns false.
bool startsWith (QLatin1String s, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
bool startsWith (QChar c, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
bool startsWith (const QStringRef &c, Qt::CaseSensitivity cs=Qt::CaseSensitive) const
const QString * string () const
Returns a pointer to the string referred to by the string reference, or 0 if it does not reference a string.
QByteArray toAscii () const Q_REQUIRED_RESULT
Returns an 8-bit representation of the string as a QByteArray.
QByteArray toLatin1 () const Q_REQUIRED_RESULT
Returns a Latin-1 representation of the string as a QByteArray.
QByteArray toLocal8Bit () const Q_REQUIRED_RESULT
Returns the local 8-bit representation of the string as a QByteArray.
QString toString () const
Returns a copy of the string reference as a QString object.
QVector< uint > toUcs4 () const Q_REQUIRED_RESULT
Returns a UCS-4/UTF-32 representation of the string as a QVector<uint>.
QByteArray toUtf8 () const Q_REQUIRED_RESULT
Returns a UTF-8 representation of the string as a QByteArray.
const QChar * unicode () const
Returns a Unicode representation of the string reference.
~QStringRef ()
Destroys the string reference.
Static Public Functions
static int compare (const QStringRef &s1, const QString &s2, Qt::CaseSensitivity=Qt::CaseSensitive)
Compares the string s1 with the string s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
static int compare (const QStringRef &s1, const QStringRef &s2, Qt::CaseSensitivity=Qt::CaseSensitive)
Compares the string s1 with the string s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
static int compare (const QStringRef &s1, QLatin1String s2, Qt::CaseSensitivity cs=Qt::CaseSensitive)
Compares the string s1 with the string s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
static int localeAwareCompare (const QStringRef &s1, const QString &s2)
Compares s1 with s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
static int localeAwareCompare (const QStringRef &s1, const QStringRef &s2)
Compares s1 with s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
Properties
int m_position
int m_size
const QString * m_string
Related Functions
(Note that these are not member functions.)
bool operator< (const QStringRef &s1, const QStringRef &s2)
Returns true if string reference s1 is lexically less than string reference s2; otherwise returns false.
bool operator<= (const QStringRef &s1, const QStringRef &s2)
bool operator== (const QStringRef &s1, const QStringRef &s2)
Returns true if string reference s1 is lexically equal to string reference s2; otherwise returns false.
bool operator== (const QString &s1, const QStringRef &s2)
Returns true if string s1 is lexically equal to string reference s2; otherwise returns false.
bool operator== (const QLatin1String &s1, const QStringRef &s2)
Returns true if string s1 is lexically equal to string reference s2; otherwise returns false.
bool operator> (const QStringRef &s1, const QStringRef &s2)
bool operator>= (const QStringRef &s1, const QStringRef &s2)
Detailed Description
The QStringRef class provides a thin wrapper around QString substrings.
Since
4.3
Note
This class or function is reentrant.
QStringRef provides a read-only subset of the QString API.
A string reference explicitly references a portion of a string() with a given size(), starting at a specific position(). Calling toString() returns a copy of the data as a real QString instance.
This class is designed to improve the performance of substring handling when manipulating substrings obtained from existing QString instances. QStringRef avoids the memory allocation and reference counting overhead of a standard QString by simply referencing a part of the original string. This can prove to be advantageous in low level code, such as that used in a parser, at the expense of potentially more complex code.
For most users, there are no semantic benefits to using QStringRef instead of QString since QStringRef requires attention to be paid to memory management issues, potentially making code more complex to write and maintain.
Warning
A QStringRef is only valid as long as the referenced string exists. If the original string is deleted, the string reference points to an invalid memory location.
We suggest that you only use this class in stable code where profiling has clearly identified that performance improvements can be made by replacing standard string operations with the optimized substring handling provided by this class.
See also
{Implicitly Shared Classes}
Definition at line 1099 of file qstring.h.
Constructors and Destructors
QStringRef() [1/4]
QStringRef::QStringRef () inline
Constructs an empty string reference.
Definition at line 1104 of file qstring.h.
 :m_string(0), m_position(0), m_size(0){}
QStringRef() [2/4]
QStringRef::QStringRef (const QString * string, int position, int length) inline
Constructs a string reference to the range of characters in the given string specified by the starting position and length in characters.
Warning
This function exists to improve performance as much as possible, and performs no bounds checking. For program correctness, position and length must describe a valid substring of string.
This means that the starting position must be positive or 0 and smaller than string's length, and length must be positive or 0 but smaller than the string's length minus the starting position; i.e, 0 <= position < string->length() and 0 <= length <= string->length() - position must both be satisfied.
Definition at line 1196 of file qstring.h.
         :m_string(aString), m_position(aPosition), m_size(aSize){}
QStringRef() [3/4]
QStringRef::QStringRef (const QString * string) inline
Constructs a string reference to the given string.
Definition at line 1199 of file qstring.h.
     :m_string(aString), m_position(0), m_size(aString?aString->size() : 0){}
QStringRef() [4/4]
QStringRef::QStringRef (const QStringRef & other) inline
Constructs a copy of the other string reference.
Definition at line 1107 of file qstring.h.
         :m_string(other.m_string), m_position(other.m_position), m_size(other.m_size)
         {}
~QStringRef()
QStringRef::~QStringRef () inline
Destroys the string reference.
Since this class is only used to refer to string data, and does not take ownership of it, no memory is freed when instances are destroyed.
Definition at line 1111 of file qstring.h.
 {}
Functions
appendTo()
QStringRef QStringRef::appendTo (QString * string) const
Appends the string reference to string, and returns a new reference to the combined string data.
Definition at line 8828 of file qstring.cpp.
Referenced by QString::append(), and QXmlStreamWriterPrivate::write().
 {
     if (!string)
         return QStringRef();
     int pos = string->size();
     string->insert(pos, unicode(), size());
     return QStringRef(string, pos, size());
 }
at()
const QChar QStringRef::at (int position) const inline
Returns the character at the given index position in the string reference.
The position must be a valid index position in the string (i.e., 0 <= position < size()).
Definition at line 1174 of file qstring.h.
Referenced by QPatternist::CompressedWhitespace::compress(), createSvgGlyph(), QXmlUtils::isNCName(), QString::lastIndexOf(), lastIndexOf(), QDateTimeParser::parse(), QDeclarativeStyledTextPrivate::parseCloseTag(), parseCoreNode(), parseFont(), QDeclarativeStyledTextPrivate::parseFontAttributes(), QDeclarativeStyledTextPrivate::parseTag(), QSvgAttributes::QSvgAttributes(), and resolveColor().
         { Q_ASSERT(uint(i) < uint(size())); return m_string->at(i + m_position); }
clear()
void QStringRef::clear () inline
Clears the contents of the string reference by making it null and empty.
See also
isEmpty(), isNull()
Definition at line 1167 of file qstring.h.
Referenced by QXmlStreamReaderPrivate::EntityDeclaration::clear(), QXmlStreamWriterPrivate::findNamespace(), QXmlStreamReaderPrivate::parse(), QXmlStreamReaderPrivate::resolveTag(), and QXmlStreamWriter::writeDefaultNamespace().
 { m_string = 0; m_position = m_size = 0; }
compare() [1/6]
int QStringRef::compare (const QString & other, Qt::CaseSensitivity cs = Qt::CaseSensitive) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Compares this string with the other string and returns an integer less than, equal to, or greater than zero if this string is less than, equal to, or greater than the other string.
If cs is Qt::CaseSensitive, the comparison is case sensitive; otherwise the comparison is case insensitive.
Equivalent to {compare(*this, other, cs)}.
See also
QString::compare()
Definition at line 1249 of file qstring.h.
 { return QString::compare_helper(constData(), length(), s.constData(), s.length(), cs); }
compare() [2/6]
int QStringRef::compare (const QStringRef & other, Qt::CaseSensitivity cs = Qt::CaseSensitive) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Compares this string with the other string and returns an integer less than, equal to, or greater than zero if this string is less than, equal to, or greater than the other string.
If cs is Qt::CaseSensitive, the comparison is case sensitive; otherwise the comparison is case insensitive.
Equivalent to {compare(*this, other, cs)}.
See also
QString::compare()
Definition at line 1251 of file qstring.h.
 { return QString::compare_helper(constData(), length(), s.constData(), s.length(), cs); }
compare() [3/6]
int QStringRef::compare (QLatin1String other, Qt::CaseSensitivity cs = Qt::CaseSensitive) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.5
Compares this string with the other string and returns an integer less than, equal to, or greater than zero if this string is less than, equal to, or greater than the other string.
If cs is Qt::CaseSensitive, the comparison is case sensitive; otherwise the comparison is case insensitive.
Equivalent to {compare(*this, other, cs)}.
See also
QString::compare()
Definition at line 1253 of file qstring.h.
 { return QString::compare_helper(constData(), length(), s, cs); }
compare() [4/6]
int QStringRef::compare (const QStringRef & s1, const QString & s2, Qt::CaseSensitivity cs = Qt::CaseSensitive) inline static
Compares the string s1 with the string s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
Since
4.5
If cs is Qt::CaseSensitive, the comparison is case sensitive; otherwise the comparison is case insensitive.
Definition at line 1255 of file qstring.h.
 { return QString::compare_helper(s1.constData(), s1.length(), s2.constData(), s2.length(), cs); }
compare() [5/6]
int QStringRef::compare (const QStringRef & s1, const QStringRef & s2, Qt::CaseSensitivity cs = Qt::CaseSensitive) inline static
Compares the string s1 with the string s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If cs is Qt::CaseSensitive, the comparison is case sensitive; otherwise the comparison is case insensitive.
Definition at line 1257 of file qstring.h.
 { return QString::compare_helper(s1.constData(), s1.length(), s2.constData(), s2.length(), cs); }
compare() [6/6]
int QStringRef::compare (const QStringRef & s1, QLatin1String s2, Qt::CaseSensitivity cs = Qt::CaseSensitive) inline static
Compares the string s1 with the string s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If cs is Qt::CaseSensitive, the comparison is case sensitive; otherwise the comparison is case insensitive.
Definition at line 1259 of file qstring.h.
 { return QString::compare_helper(s1.constData(), s1.length(), s2, cs); }
constData()
const QChar * QStringRef::constData () const inline
Same as unicode().
Definition at line 1159 of file qstring.h.
Referenced by QConcatenable< QStringRef >::appendTo(), QXmlStreamReaderPrivate::checkPublicLiteral(), QString::compare(), compare(), QString::localeAwareCompare(), localeAwareCompare(), operator<(), parsePathDataFast(), parseTransformationMatrix(), resolveColor(), toDouble(), XsdSchemaToken::toToken(), QPatternist::XSLTTokenLookup::toToken(), and QXmlStreamWriterPrivate::write().
 {  return unicode(); }
contains() [1/4]
QBool QStringRef::contains (const QString & str, Qt::CaseSensitivity cs = Qt::CaseSensitive) const inline
Returns true if this string reference contains an occurrence of the string str; otherwise returns false.
Since
4.8
If cs is Qt::CaseSensitive (default), the search is case sensitive; otherwise the search is case insensitive.
See also
indexOf(), count()
Definition at line 1275 of file qstring.h.
 { return QBool(indexOf(s, 0, cs) != -1); }
contains() [2/4]
QBool QStringRef::contains (QChar ch, Qt::CaseSensitivity cs = Qt::CaseSensitive) const inline
Definition at line 1279 of file qstring.h.
 { return QBool(indexOf(c, 0, cs) != -1); }
contains() [3/4]
QBool QStringRef::contains (QLatin1String str, Qt::CaseSensitivity cs = Qt::CaseSensitive) const inline
Definition at line 1277 of file qstring.h.
 { return QBool(indexOf(s, 0, cs) != -1); }
contains() [4/4]
QBool QStringRef::contains (const QStringRef & str, Qt::CaseSensitivity cs = Qt::CaseSensitive) const inline
Definition at line 1281 of file qstring.h.
 { return QBool(indexOf(s, 0, cs) != -1); }
count() [1/4]
int QStringRef::count () const inline
Returns the number of characters referred to by the string reference.
Equivalent to size() and length().
See also
position(), string()
Definition at line 1115 of file qstring.h.
 { return m_size; }
count() [2/4]
int QStringRef::count (const QString & str, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Returns the number of (potentially overlapping) occurrences of the string str in this string reference.
Since
4.8
If cs is Qt::CaseSensitive (default), the search is case sensitive; otherwise the search is case insensitive.
See also
QString::count(), contains(), indexOf()
Definition at line 9350 of file qstring.cpp.
 {
     return qt_string_count(unicode(), size(), str.unicode(), str.size(), cs);
 }
count() [3/4]
int QStringRef::count (QChar c, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9370 of file qstring.cpp.
 {
     return qt_string_count(unicode(), size(), ch, cs);
 }
count() [4/4]
int QStringRef::count (const QStringRef & s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9390 of file qstring.cpp.
 {
     return qt_string_count(unicode(), size(), str.unicode(), str.size(), cs);
 }
data()
const QChar * QStringRef::data () const inline
Same as unicode().
Definition at line 1158 of file qstring.h.
 { return unicode(); }
endsWith() [1/4]
bool QStringRef::endsWith (const QString & str, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Returns true if the string reference ends with str; otherwise returns false.
Since
4.8
If cs is Qt::CaseSensitive (default), the search is case sensitive; otherwise the search is case insensitive.
See also
QString::endsWith(), startsWith()
Definition at line 9476 of file qstring.cpp.
 {
     return qt_ends_with(isNull() ? 0 : unicode(), size(),
                         str.isNull() ? 0 : str.unicode(), str.size(), cs);
 }
endsWith() [2/4]
bool QStringRef::endsWith (QLatin1String s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9515 of file qstring.cpp.
 {
     return qt_ends_with(isNull() ? 0 : unicode(), size(), str, cs);
 }
endsWith() [3/4]
bool QStringRef::endsWith (QChar c, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9497 of file qstring.cpp.
 {
     if (!isEmpty()) {
         const ushort *data = reinterpret_cast<const ushort*>(unicode());
         const int size = length();
         return (cs == Qt::CaseSensitive
                 ? data[size - 1] == ch
                 : foldCase(data[size - 1]) == foldCase(ch.unicode()));
     } else {
         return false;
     }
 }
endsWith() [4/4]
bool QStringRef::endsWith (const QStringRef & c, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9525 of file qstring.cpp.
 {
     return qt_ends_with(isNull() ? 0 : unicode(), size(),
                         str.isNull() ? 0 : str.unicode(), str.size(), cs);
 }
indexOf() [1/4]
int QStringRef::indexOf (const QString & str, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Returns the index position of the first occurrence of the string str in this string reference, searching forward from index position from.
Since
4.8
Returns -1 if str is not found.
If cs is Qt::CaseSensitive (default), the search is case sensitive; otherwise the search is case insensitive.
If from is -1, the search starts at the last character; if it is -2, at the next to last character and so on.
See also
QString::indexOf(), lastIndexOf(), contains(), count()
Definition at line 9132 of file qstring.cpp.
Referenced by contains().
 {
     return qFindString(unicode(), length(), from, str.unicode(), str.length(), cs);
 }
indexOf() [2/4]
int QStringRef::indexOf (QChar ch, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9150 of file qstring.cpp.
 {
     return findChar(unicode(), length(), ch, from, cs);
 }
indexOf() [3/4]
int QStringRef::indexOf (QLatin1String str, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Returns the index position of the first occurrence of the string str in this string reference, searching forward from index position from.
Since
4.8
Returns -1 if str is not found.
If cs is Qt::CaseSensitive (default), the search is case sensitive; otherwise the search is case insensitive.
If from is -1, the search starts at the last character; if it is -2, at the next to last character and so on.
See also
QString::indexOf(), lastIndexOf(), contains(), count()
Definition at line 9173 of file qstring.cpp.
 {
     return qt_find_latin1_string(unicode(), size(), str, from, cs);
 }
indexOf() [4/4]
int QStringRef::indexOf (const QStringRef & str, int from = 0, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9195 of file qstring.cpp.
 {
     return qFindString(unicode(), size(), from, str.unicode(), str.size(), cs);
 }
isEmpty()
bool QStringRef::isEmpty () const inline
Returns true if the string reference has no characters; otherwise returns false.
A string reference is empty if its size is zero.
See also
size()
Definition at line 1169 of file qstring.h.
Referenced by QPatternist::AccelTreeBuilder< true >::characters(), QPatternist::CompressedWhitespace::compress(), constructColor(), createSolidColorNode(), createSvgGlyph(), QXmlStreamWriterPrivate::findNamespace(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::insideStylesheetModule(), QXmlUtils::isNCName(), QXmlStreamReaderPrivate::namespaceForPrefix(), operator==(), QXmlStreamReaderPrivate::parse(), QDeclarativeStyledTextPrivate::parseAttribute(), parseBaseGradient(), parseBrush(), parseCompOp(), parseCoreNode(), parseFont(), QDeclarativeStyledTextPrivate::parseFontAttributes(), parseOpacity(), parseOthers(), parsePen(), parseServerList(), parseStopNode(), parseTransform(), parseTransformationMatrix(), parseVisibility(), QSvgAttributes::QSvgAttributes(), resolveColor(), QXmlStreamReaderPrivate::resolveTag(), QXmlStreamReaderPrivate::startDocument(), trimRef(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QPatternist::AccelTreeBuilder< true >::whitespaceOnly(), QXmlStreamWriter::writeAttribute(), QXmlStreamWriter::writeEndElement(), and QXmlStreamWriterPrivate::writeNamespaceDeclaration().
 { return m_size == 0; }
isNull()
bool QStringRef::isNull () const inline
Returns true if string() returns a null pointer or a pointer to a null string; otherwise returns true.
See also
size()
Definition at line 1170 of file qstring.h.
Referenced by QString::endsWith(), endsWith(), QPatternist::XSLTTokenizer::handleValidationAttributes(), QXmlStreamReaderPrivate::parse(), QXmlStreamReaderPrivate::resolveTag(), QString::startsWith(), and startsWith().
 { return m_string == 0 || m_string->isNull(); }
lastIndexOf() [1/4]
int QStringRef::lastIndexOf (const QString & str, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Returns the index position of the last occurrence of the string str in this string reference, searching backward from index position from.
Since
4.8
If from is -1 (default), the search starts at the last character; if from is -2, at the next to last character and so on. Returns -1 if str is not found.
If cs is Qt::CaseSensitive (default), the search is case sensitive; otherwise the search is case insensitive.
See also
QString::lastIndexOf(), indexOf(), contains(), count()
Definition at line 9217 of file qstring.cpp.
 {
     const int sl = str.size();
     if (sl == 1)
         return lastIndexOf(str.at(0), from, cs);
     const int l = size();;
     if (from < 0)
         from += l;
     int delta = l - sl;
     if (from == l && sl == 0)
         return from;
     if (from < 0 || from >= l || delta < 0)
         return -1;
     if (from > delta)
         from = delta;
     return lastIndexOfHelper(reinterpret_cast<const ushort*>(unicode()), from,
                              reinterpret_cast<const ushort*>(str.unicode()), str.size(), cs);
 }
lastIndexOf() [2/4]
int QStringRef::lastIndexOf (QChar ch, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9250 of file qstring.cpp.
 {
     return qt_last_index_of(unicode(), size(), ch, from, cs);
 }
lastIndexOf() [3/4]
int QStringRef::lastIndexOf (QLatin1String str, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9273 of file qstring.cpp.
 {
     const int sl = qstrlen(str.latin1());
     if (sl == 1)
         return lastIndexOf(QLatin1Char(str.latin1()[0]), from, cs);
     const int l = size();
     if (from < 0)
         from += l;
     int delta = l - sl;
     if (from == l && sl == 0)
         return from;
     if (from < 0 || from >= l || delta < 0)
         return -1;
     if (from > delta)
         from = delta;
     QVarLengthArray<ushort> s(sl);
     for (int i = 0; i < sl; ++i)
         s[i] = str.latin1()[i];
     return lastIndexOfHelper(reinterpret_cast<const ushort*>(unicode()), from, s.data(), sl, cs);
 }
lastIndexOf() [4/4]
int QStringRef::lastIndexOf (const QStringRef & str, int from = -1, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9315 of file qstring.cpp.
 {
     const int sl = str.size();
     if (sl == 1)
         return lastIndexOf(str.at(0), from, cs);
     const int l = size();
     if (from < 0)
         from += l;
     int delta = l - sl;
     if (from == l && sl == 0)
         return from;
     if (from < 0 || from >= l || delta < 0)
         return -1;
     if (from > delta)
         from = delta;
     return lastIndexOfHelper(reinterpret_cast<const ushort*>(unicode()), from,
                              reinterpret_cast<const ushort*>(str.unicode()),
                              str.size(), cs);
 }
length()
int QStringRef::length () const inline
Returns the number of characters referred to by the string reference.
Equivalent to size() and count().
See also
position(), string()
Definition at line 1116 of file qstring.h.
Referenced by QConcatenable< QStringRef >::appendTo(), QString::compare(), compare(), QPatternist::CompressedWhitespace::compress(), QString::indexOf(), QString::localeAwareCompare(), localeAwareCompare(), operator<(), parseBrush(), parsePen(), parseTransformationMatrix(), QSvgAttributes::QSvgAttributes(), resolveColor(), toDouble(), XsdSchemaToken::toToken(), QPatternist::XSLTTokenLookup::toToken(), and trimRef().
 { return m_size; }
localeAwareCompare() [1/4]
int QStringRef::localeAwareCompare (const QString & other) const inline
Compares this string with the other string and returns an integer less than, equal to, or greater than zero if this string is less than, equal to, or greater than the other string.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The comparison is performed in a locale- and also platform-dependent manner. Use this function to present sorted lists of strings to the user.
Definition at line 1266 of file qstring.h.
 { return QString::localeAwareCompare_helper(constData(), length(), s.constData(), s.length()); }
localeAwareCompare() [2/4]
int QStringRef::localeAwareCompare (const QStringRef & other) const inline
Compares this string with the other string and returns an integer less than, equal to, or greater than zero if this string is less than, equal to, or greater than the other string.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The comparison is performed in a locale- and also platform-dependent manner. Use this function to present sorted lists of strings to the user.
Definition at line 1268 of file qstring.h.
 { return QString::localeAwareCompare_helper(constData(), length(), s.constData(), s.length()); }
localeAwareCompare() [3/4]
int QStringRef::localeAwareCompare (const QStringRef & s1, const QString & s2) inline static
Compares s1 with s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
Since
4.5
The comparison is performed in a locale- and also platform-dependent manner. Use this function to present sorted lists of strings to the user.
On Mac OS X, this function compares according the "Order for sorted lists" setting in the International prefereces panel.
See also
compare(), QTextCodec::locale()
Definition at line 1270 of file qstring.h.
 { return QString::localeAwareCompare_helper(s1.constData(), s1.length(), s2.constData(), s2.length()); }
localeAwareCompare() [4/4]
int QStringRef::localeAwareCompare (const QStringRef & s1, const QStringRef & s2) inline static
Compares s1 with s2 and returns an integer less than, equal to, or greater than zero if s1 is less than, equal to, or greater than s2.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The comparison is performed in a locale- and also platform-dependent manner. Use this function to present sorted lists of strings to the user.
Definition at line 1272 of file qstring.h.
 { return QString::localeAwareCompare_helper(s1.constData(), s1.length(), s2.constData(), s2.length()); }
operator=() [1/2]
QStringRef & QStringRef::operator= (const QStringRef & other) inline
Assigns the other string reference to this string reference, and returns the result.
Definition at line 1118 of file qstring.h.
{
         m_string = other.m_string; m_position = other.m_position;
         m_size = other.m_size; return *this;
     }
operator=() [2/2]
QStringRef & QStringRef::operator= (const QString * string) inline
Constructs a string reference to the given string and assigns it to this string reference, returning the result.
Definition at line 1193 of file qstring.h.
 { m_string = aString; m_position = 0; m_size = aString?aString->size():0; return *this; }
position()
int QStringRef::position () const inline
Returns the starting position in the referenced string that is referred to by the string reference.
See also
size(), string()
Definition at line 1113 of file qstring.h.
Referenced by parseBrush(), parsePen(), QSvgAttributes::QSvgAttributes(), resolveColor(), and trimRef().
 { return m_position; }
size()
int QStringRef::size () const inline
Returns the number of characters referred to by the string reference.
Equivalent to length() and count().
See also
position(), string()
Definition at line 1114 of file qstring.h.
Referenced by QXmlStreamPrivateTagStack::addToStringStorage(), QString::append(), QConcatenable< QStringRef >::appendTo(), QXmlStreamReaderPrivate::checkPublicLiteral(), QString::count(), count(), QString::endsWith(), endsWith(), indexOf(), QXmlUtils::isNCName(), QString::lastIndexOf(), lastIndexOf(), operator==(), parsePathDataFast(), qHash(), QConcatenable< QStringRef >::size(), QString::startsWith(), startsWith(), and QXmlStreamWriterPrivate::write().
 { return m_size; }
startsWith() [1/4]
bool QStringRef::startsWith (const QString & str, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Returns true if the string reference starts with str; otherwise returns false.
Since
4.8
If cs is Qt::CaseSensitive (default), the search is case sensitive; otherwise the search is case insensitive.
See also
QString::startsWith(), endsWith()
Definition at line 9409 of file qstring.cpp.
 {
     return qt_starts_with(isNull() ? 0 : unicode(), size(),
                           str.isNull() ? 0 : str.unicode(), str.size(), cs);
 }
startsWith() [2/4]
bool QStringRef::startsWith (QLatin1String s, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9420 of file qstring.cpp.
 {
     return qt_starts_with(isNull() ? 0 : unicode(), size(), str, cs);
 }
startsWith() [3/4]
bool QStringRef::startsWith (QChar c, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9451 of file qstring.cpp.
 {
     if (!isEmpty()) {
         const ushort *data = reinterpret_cast<const ushort*>(unicode());
         return (cs == Qt::CaseSensitive
                 ? data[0] == ch
                 : foldCase(data[0]) == foldCase(ch.unicode()));
     } else {
         return false;
     }
 }
startsWith() [4/4]
bool QStringRef::startsWith (const QStringRef & c, Qt::CaseSensitivity cs = Qt::CaseSensitive) const
Definition at line 9430 of file qstring.cpp.
 {
     return qt_starts_with(isNull() ? 0 : unicode(), size(),
                           str.isNull() ? 0 : str.unicode(), str.size(), cs);
 }
string()
const QString * QStringRef::string () const inline
Returns a pointer to the string referred to by the string reference, or 0 if it does not reference a string.
See also
unicode()
Definition at line 1112 of file qstring.h.
Referenced by QString::append(), parseBrush(), parsePen(), QSvgAttributes::QSvgAttributes(), resolveColor(), and trimRef().
 { return m_string; }
toAscii()
QByteArray QStringRef::toAscii () const
Returns an 8-bit representation of the string as a QByteArray.
Since
4.8
If a codec has been set using QTextCodec::setCodecForCStrings(), it is used to convert Unicode to 8-bit char; otherwise this function does the same as toLatin1().
Note that, despite the name, this function does not necessarily return an US-ASCII (ANSI X3.4-1986) string and its result may not be US-ASCII compatible.
See also
toLatin1(), toUtf8(), toLocal8Bit(), QTextCodec
Definition at line 9810 of file qstring.cpp.
 {
 #ifndef QT_NO_TEXTCODEC
     if (QString::codecForCStrings)
         return QString::codecForCStrings->fromUnicode(unicode(), length());
 #endif // QT_NO_TEXTCODEC
     return toLatin1();
 }
toLatin1()
QByteArray QStringRef::toLatin1 () const
Returns a Latin-1 representation of the string as a QByteArray.
Since
4.8
The returned byte array is undefined if the string contains non-Latin1 characters. Those characters may be suppressed or replaced with a question mark.
See also
toAscii(), toUtf8(), toLocal8Bit(), QTextCodec
Definition at line 9788 of file qstring.cpp.
Referenced by QXmlStreamReaderPrivate::startDocument(), and QXmlStreamWriterPrivate::write().
 {
     return toLatin1_helper(unicode(), length());
 }
toLocal8Bit()
QByteArray QStringRef::toLocal8Bit () const
Returns the local 8-bit representation of the string as a QByteArray.
Since
4.8
The returned byte array is undefined if the string contains characters not supported by the local 8-bit encoding.
QTextCodec::codecForLocale() is used to perform the conversion from Unicode. If the locale encoding could not be determined, this function does the same as toLatin1().
If this string contains any characters that cannot be encoded in the locale, the returned byte array is undefined. Those characters may be suppressed or replaced by another.
See also
toAscii(), toLatin1(), toUtf8(), QTextCodec
Definition at line 9839 of file qstring.cpp.
 {
 #ifndef QT_NO_TEXTCODEC
     if (QTextCodec::codecForLocale())
         return QTextCodec::codecForLocale()->fromUnicode(unicode(), length());
 #endif // QT_NO_TEXTCODEC
     return toLatin1();
 }
toString()
QString QStringRef::toString () const
Returns a copy of the string reference as a QString object.
If the string reference is not a complete reference of the string (meaning that position() is 0 and size() equals string()->size()), this function will allocate a new string to return.
See also
string()
Definition at line 8653 of file qstring.cpp.
Referenced by QXmlSerializer::attribute(), QPatternist::AccelTreeBuilder< true >::attribute(), QXmlFormatter::characters(), QXmlSerializer::characters(), QSvgHandler::characters(), QPatternist::ColoringMessageHandler::colorifyDescription(), createCircleNode(), createEllipseNode(), createFontNode(), createImageNode(), createLinearGradientNode(), createLineNode(), createPolygonNode(), createPolylineNode(), createRadialGradientNode(), createRectNode(), createSvgNode(), createTextAreaNode(), createTextNode(), createUseNode(), QDeclarativeXMLHttpRequest::findTextCodec(), QPatternist::formatKeyword(), QPatternist::XSLTTokenizer::handleXSLTVersion(), QPatternist::XSLTTokenizer::insideSequenceConstructor(), QPatternist::XSLTTokenizer::insideTemplate(), Document::load(), QXmlStreamReaderPrivate::namespaceForPrefix(), QDeclarativeInfo::operator<<(), QDebug::operator<<(), QScriptXmlParser::parse(), QSvgHandler::parse(), QXmlStreamReaderPrivate::parse(), parseAnimateColorNode(), parseAnimateTransformNode(), parseBaseGradient(), parseCompOp(), parseCoreNode(), parseFont(), QDeclarativeStyledTextPrivate::parseFontAttributes(), parseFontFaceNameNode(), parseFontFaceNode(), parseOpacity(), parseOthers(), parsePen(), parseServerList(), parseStopNode(), parseStyleNode(), QSvgAttributes::QSvgAttributes(), QPatternist::XSLTTokenizer::queueNamespaceDeclarations(), QPatternist::XSLTTokenizer::queueSelectOrSequenceConstructor(), QPatternist::XSLTTokenizer::queueSimpleContentConstructor(), QPatternist::XSLTTokenizer::queueSorting(), QPatternist::XSLTTokenizer::queueVariableDeclaration(), QPatternist::XSLTTokenizer::readAlternativeAttribute(), QPatternist::XSLTTokenizer::readElementText(), QPatternist::XSLTTokenizer::readToggleAttribute(), QXmlStreamReaderPrivate::resolveCharRef(), resolveColor(), QPatternist::NamespaceSupport::setPrefixes(), someId(), QXmlStreamReaderPrivate::startDocument(), QPatternist::AccelTreeResourceLoader::streamToReceiver(), tokenUntil(), QPatternist::TagValidationHandler::validate(), QPatternist::MaintainingReader< XSLTTokenLookup >::validateElement(), QAbstractXmlReceiver::whitespaceOnly(), QPatternist::AccelTreeBuilder< true >::whitespaceOnly(), QPatternist::QAbstractXmlReceiver::whitespaceOnly(), QXmlStreamWriter::writeAttribute(), and QXmlStreamWriter::writeCurrentToken().
{
     if (!m_string)
         return QString();
     if (m_size && m_position == 0 && m_size == m_string->size())
         return *m_string;
     return QString(m_string->unicode() + m_position, m_size);
 }
toUcs4()
QVector< uint > QStringRef::toUcs4 () const
Returns a UCS-4/UTF-32 representation of the string as a QVector<uint>.
Since
4.8
UCS-4 is a Unicode codec and is lossless. All characters from this string can be encoded in UCS-4.
See also
toAscii(), toLatin1(), toLocal8Bit(), QTextCodec
Definition at line 9890 of file qstring.cpp.
 {
     QVector<uint> v(length());
     uint *a = v.data();
     int len = toUcs4_helper<uint>(reinterpret_cast<const unsigned short *>(unicode()), length(), a);
     v.resize(len);
     return v;
 }
toUtf8()
QByteArray QStringRef::toUtf8 () const
Returns a UTF-8 representation of the string as a QByteArray.
Since
4.8
UTF-8 is a Unicode codec and can represent all characters in a Unicode string like QString.
However, in the Unicode range, there are certain codepoints that are not considered characters. The Unicode standard reserves the last two codepoints in each Unicode Plane (U+FFFE, U+FFFF, U+1FFFE, U+1FFFF, U+2FFFE, etc.), as well as 16 codepoints in the range U+FDD0..U+FDDF, inclusive, as non-characters. If any of those appear in the string, they may be discarded and will not appear in the UTF-8 representation, or they may be replaced by one or more replacement characters.
See also
toAscii(), toLatin1(), toLocal8Bit(), QTextCodec
Definition at line 9869 of file qstring.cpp.
 {
     if (isNull())
         return QByteArray();
     return QUtf8::convertFromUnicode(constData(), length(), 0);
 }
unicode()
const QChar * QStringRef::unicode () const inline
Returns a Unicode representation of the string reference.
Since the data stems directly from the referenced string, it is not null-terminated unless the string reference includes the string's null terminator.
See also
string()
Definition at line 1153 of file qstring.h.
Referenced by QXmlStreamPrivateTagStack::addToStringStorage(), QString::append(), QString::count(), count(), QString::endsWith(), endsWith(), QString::indexOf(), indexOf(), QString::lastIndexOf(), lastIndexOf(), operator==(), qHash(), resolveColor(), QString::startsWith(), and startsWith().
{
         if (!m_string)
             return reinterpret_cast<const QChar *>(QString::shared_null.data);
         return m_string->unicode() + m_position;
     }
Friends and Related Functions
operator<()
bool operator< (const QStringRef & s1, const QStringRef & s2) related
Returns true if string reference s1 is lexically less than string reference s2; otherwise returns false.
The comparison is based exclusively on the numeric Unicode values of the characters and is very fast, but is not what a human would expect. Consider sorting user-interface strings using the QString::localeAwareCompare() function.
Definition at line 8727 of file qstring.cpp.
Referenced by operator!=().
 {
     return ucstrcmp(s1.constData(), s1.length(), s2.constData(), s2.length()) < 0;
 }
operator<=()
bool operator<= (const QStringRef & s1, const QStringRef & s2) related
Returns true if string reference s1 is lexically less than or equal to string reference s2; otherwise returns false.
The comparison is based exclusively on the numeric Unicode values of the characters and is very fast, but is not what a human would expect. Consider sorting user-interface strings using the QString::localeAwareCompare() function.
Definition at line 1223 of file qstring.h.
 { return !(s1 > s2); }
operator==() [1/3]
bool operator== (const QStringRef & s1, const QStringRef & s2) related
Returns true if string reference s1 is lexically equal to string reference s2; otherwise returns false.
Definition at line 8670 of file qstring.cpp.
Referenced by operator!=(), and QStringRef().
 { return (s1.size() == s2.size() &&
           qMemEquals((const ushort *)s1.unicode(), (const ushort *)s2.unicode(), s1.size()));
 }
operator==() [2/3]
bool operator== (const QString & s1, const QStringRef & s2) related
Returns true if string s1 is lexically equal to string reference s2; otherwise returns false.
Definition at line 8683 of file qstring.cpp.
 { return (s1.size() == s2.size() &&
           qMemEquals((const ushort *)s1.unicode(), (const ushort *)s2.unicode(), s1.size()));
 }
operator==() [3/3]
bool operator== (const QLatin1String & s1, const QStringRef & s2) related
Returns true if string s1 is lexically equal to string reference s2; otherwise returns false.
Definition at line 8696 of file qstring.cpp.
 {
     const ushort *uc = reinterpret_cast<const ushort *>(s2.unicode());
     const ushort *e = uc + s2.size();
     const uchar *c = reinterpret_cast<const uchar *>(s1.latin1());
     if (!c)
         return s2.isEmpty();
     while (*c) {
         if (uc == e || *uc != *c)
             return false;
         ++uc;
         ++c;
     }
     return (uc == e);
 }
operator>()
bool operator> (const QStringRef & s1, const QStringRef & s2) related
Returns true if string reference s1 is lexically greater than string reference s2; otherwise returns false.
The comparison is based exclusively on the numeric Unicode values of the characters and is very fast, but is not what a human would expect. Consider sorting user-interface strings using the QString::localeAwareCompare() function.
Definition at line 1221 of file qstring.h.
 { return s2 < s1; }
operator>=()
bool operator>= (const QStringRef & s1, const QStringRef & s2) related
Returns true if string reference s1 is lexically greater than or equal to string reference s2; otherwise returns false.
The comparison is based exclusively on the numeric Unicode values of the characters and is very fast, but is not what a human would expect. Consider sorting user-interface strings using the QString::localeAwareCompare() function.
Definition at line 1225 of file qstring.h.
 { return !(s1 < s2); }
Properties
m_position
int QStringRef::m_position private
Definition at line 1101 of file qstring.h.
Referenced by operator=().
m_size
int QStringRef::m_size private
Definition at line 1102 of file qstring.h.
Referenced by operator=().
m_string
const QString* QStringRef::m_string private
Definition at line 1100 of file qstring.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
/src/corelib/tools/qstring.h
/src/corelib/tools/qstring.cpp