Qt 4.8: QSocketNotifier Class Reference
QSocketNotifier Class Reference
The QSocketNotifier class provides support for monitoring activity on a file descriptor.
#include <qsocketnotifier.h>
Public Types
enum Type { Read, Write, Exception }
This enum describes the various types of events that a socket notifier can recognize.
Public Slots
void setEnabled (bool)
If enable is true, the notifier is enabled; otherwise the notifier is disabled.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void activated (int socket)
This signal is emitted whenever the socket notifier is enabled and a socket event corresponding to its Type{type} occurs.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
bool isEnabled () const
Returns true if the notifier is enabled; otherwise returns false.
QSocketNotifier (int socket, Type, QObject *parent=0)
Constructs a socket notifier with the given parent.
int socket () const
Returns the socket identifier specified to the constructor.
Type type () const
Returns the socket event type specified to the constructor.
~QSocketNotifier ()
Destroys this socket notifier.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Properties
bool snenabled
Type sntype
int sockfd
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QSocketNotifier class provides support for monitoring activity on a file descriptor.
The QSocketNotifier makes it possible to integrate Qt's event loop with other event loops based on file descriptors. For example, the CORBA Framework uses it to process CORBA events. File descriptor action is detected in Qt's main event loop (QCoreApplication::exec()).
Once you have opened a device using a low-level (usually platform-specific) API, you can create a socket notifier to monitor the file descriptor. The socket notifier is enabled by default, i.e. it emits the activated() signal whenever a socket event corresponding to its type occurs. Connect the activated() signal to the slot you want to be called when an event corresponding to your socket notifier's type occurs.
There are three types of socket notifiers: read, write, and exception. The type is described by the Type enum, and must be specified when constructing the socket notifier. After construction it can be determined using the type() function. Note that if you need to monitor both reads and writes for the same file descriptor, you must create two socket notifiers. Note also that it is not possible to install two socket notifiers of the same type (Read , Write , Exception) on the same socket.
The setEnabled() function allows you to disable as well as enable the socket notifier. It is generally advisable to explicitly enable or disable the socket notifier, especially for write notifiers. A disabled notifier ignores socket events (the same effect as not creating the socket notifier). Use the isEnabled() function to determine the notifier's current status.
Finally, you can use the socket() function to retrieve the socket identifier. Although the class is called QSocketNotifier, it is normally used for other types of devices than sockets. QTcpSocket and QUdpSocket provide notification through signals, so there is normally no need to use a QSocketNotifier on them.
Notes for Windows Users
The socket passed to QSocketNotifier will become non-blocking, even if it was created as a blocking socket. The activated() signal is sometimes triggered by high general activity on the host, even if there is nothing to read. A subsequent read from the socket can then fail, the error indicating that there is no data available (e.g., WSAEWOULDBLOCK). This is an operating system limitation, and not a bug in QSocketNotifier.
To ensure that the socket notifier handles read notifications correctly, follow these steps when you receive a notification:
Disable the notifier.
Read data from the socket.
Re-enable the notifier if you are interested in more data (such as after having written a new command to a remote server).
To ensure that the socket notifier handles write notifications correctly, follow these steps when you receive a notification:
Disable the notifier.
Write as much data as you can (before EWOULDBLOCK is returned).
Re-enable notifier if you have more data to write.
Further information: On Windows, Qt always disables the notifier after getting a notification, and only re-enables it if more data is expected. For example, if data is read from the socket and it can be used to read more, or if reading or writing is not possible because the socket would block, in which case it is necessary to wait before attempting to read or write again.
See also
QFile, QProcess, QTcpSocket, QUdpSocket
Definition at line 53 of file qsocketnotifier.h.
Enumerations
Type
enum QSocketNotifier::Type
This enum describes the various types of events that a socket notifier can recognize.
The type must be specified when constructing the socket notifier.
Note that if you need to monitor both reads and writes for the same file descriptor, you must create two socket notifiers. Note also that it is not possible to install two socket notifiers of the same type (Read, Write, Exception) on the same socket.
Read There is data to be read.
Write Data can be written.
Exception An exception has occurred. We recommend against using this.
See also
QSocketNotifier(), type()
Enumerator
Read
Write
Exception
Definition at line 59 of file qsocketnotifier.h.
 { Read, Write, Exception };
Constructors and Destructors
QSocketNotifier()
QSocketNotifier::QSocketNotifier (int socket, Type type, QObject * parent = 0)
Constructs a socket notifier with the given parent.
It enables the socket, and watches for events of the given type.
It is generally advisable to explicitly enable or disable the socket notifier, especially for write notifiers.
Note for Windows users: The socket passed to QSocketNotifier will become non-blocking, even if it was created as a blocking socket.
See also
setEnabled(), isEnabled()
Definition at line 177 of file qsocketnotifier.cpp.
     : QObject(parent)
 {
     sockfd = socket;
     sntype = type;
     snenabled = true;
     Q_D(QObject);
     if (socket < 0)
         qWarning("QSocketNotifier: Invalid socket specified");
     else if (!d->threadData->eventDispatcher)
         qWarning("QSocketNotifier: Can only be used with threads started with QThread");
     else
         d->threadData->eventDispatcher->registerSocketNotifier(this);
 }
~QSocketNotifier()
QSocketNotifier::~QSocketNotifier ()
Destroys this socket notifier.
Definition at line 231 of file qsocketnotifier.cpp.
 {
     setEnabled(false);
 }
Functions
activated
void QSocketNotifier::activated (int socket) signal
This signal is emitted whenever the socket notifier is enabled and a socket event corresponding to its Type{type} occurs.
The socket identifier is passed in the socket parameter.
See also
type(), socket()
Referenced by event().
event()
bool QSocketNotifier::event (QEvent * e) protected virtual
This virtual function receives events to an object and should return true if the event e was recognized and processed.
The event() function can be reimplemented to customize the behavior of an object.
See also
installEventFilter(), timerEvent(), QApplication::sendEvent(), QApplication::postEvent(), QWidget::event()
Reimplemented from QObject.
Reimplemented in QExceptionNotifier, QWriteNotifier, and QReadNotifier.
Definition at line 321 of file qsocketnotifier.cpp.
Referenced by QReadNotifier::event(), QWriteNotifier::event(), and QExceptionNotifier::event().
 {
     // Emits the activated() signal when a QEvent::SockAct is
     // received.
     if (e->type() == QEvent::ThreadChange) {
         if (snenabled) {
             QMetaObject::invokeMethod(this, "setEnabled", Qt::QueuedConnection,
                                       Q_ARG(bool, snenabled));
             setEnabled(false);
         }
     }
     QObject::event(e);                        // will activate filters
     if (e->type() == QEvent::SockAct) {
         emit activated(sockfd);
         return true;
     }
     return false;
 }
isEnabled()
bool QSocketNotifier::isEnabled () const inline
Returns true if the notifier is enabled; otherwise returns false.
See also
setEnabled()
Definition at line 70 of file qsocketnotifier.h.
Referenced by QDirectFBMouseHandlerPrivate::setEnabled().
 { return snenabled; }
setEnabled
void QSocketNotifier::setEnabled (bool enable) slot
If enable is true, the notifier is enabled; otherwise the notifier is disabled.
The notifier is enabled by default, i.e. it emits the activated() signal whenever a socket event corresponding to its type occurs. If it is disabled, it ignores socket events (the same effect as not creating the socket notifier).
Write notifiers should normally be disabled immediately after the activated() signal has been emitted
See also
isEnabled(), activated()em>Reimplemented Function
Definition at line 301 of file qsocketnotifier.cpp.
Referenced by QUnixSocket::abort(), QUnixSocketServer::close(), QUnixSocket::connect(), QProcessPrivate::createChannel(), QEventDispatcherUNIXPrivate::doSelect(), QWSLinuxInputMousePrivate::enable(), event(), QUnixSocketServer::listen(), qDBusRealAddWatch(), QUnixSocket::read(), QUnixSocket::readData(), QVFbMouseHandler::resume(), QQnxMouseHandler::resume(), QDirectFBKeyboardHandlerPrivate::resume(), QWSTslibMouseHandlerPrivate::resume(), QWSLinuxTPMouseHandlerPrivate::resume(), QWSPcMouseHandlerPrivate::resume(), QDirectFBMouseHandlerPrivate::setEnabled(), QUnixSocket::setSocketDescriptor(), socketNotifierSourceCheck(), QVFbMouseHandler::suspend(), QQnxMouseHandler::suspend(), QDirectFBKeyboardHandlerPrivate::suspend(), QWSTslibMouseHandlerPrivate::suspend(), QWSLinuxTPMouseHandlerPrivate::suspend(), QWSPcMouseHandlerPrivate::suspend(), QUnixSocket::write(), and ~QSocketNotifier().
socket()
int QSocketNotifier::socket () const inline
Returns the socket identifier specified to the constructor.
See also
type()
Definition at line 67 of file qsocketnotifier.h.
Referenced by QSocketNotifier(), QDirectFBKeyboardHandlerPrivate::readKeyboardData(), QDirectFBMouseHandlerPrivate::readMouseData(), QEventDispatcherBlackberry::registerSocketNotifier(), QEventDispatcherGlib::registerSocketNotifier(), QEventDispatcherWin32::registerSocketNotifier(), QEventDispatcherMac::registerSocketNotifier(), QEventDispatcherUNIX::registerSocketNotifier(), QEventDispatcherUNIX::setSocketNotifierPending(), QEventDispatcherBlackberry::unregisterSocketNotifier(), QEventDispatcherGlib::unregisterSocketNotifier(), QEventDispatcherWin32::unregisterSocketNotifier(), QEventDispatcherMac::unregisterSocketNotifier(), and QEventDispatcherUNIX::unregisterSocketNotifier().
 { return sockfd; }
type()
Type QSocketNotifier::type () const inline
Returns the socket event type specified to the constructor.
See also
socket()
Definition at line 68 of file qsocketnotifier.h.
Referenced by QSocketNotifier(), QEventDispatcherBlackberry::registerSocketNotifier(), QEventDispatcherGlib::registerSocketNotifier(), QEventDispatcherWin32::registerSocketNotifier(), QEventDispatcherMac::registerSocketNotifier(), QEventDispatcherUNIX::registerSocketNotifier(), QEventDispatcherUNIX::setSocketNotifierPending(), socketNotifierSourceCheck(), QEventDispatcherWin32::unregisterSocketNotifier(), QEventDispatcherMac::unregisterSocketNotifier(), and QEventDispatcherUNIX::unregisterSocketNotifier().
 { return sntype; }
Properties
snenabled
bool QSocketNotifier::snenabled private
Definition at line 86 of file qsocketnotifier.h.
Referenced by event(), QSocketNotifier(), and setEnabled().
sntype
Type QSocketNotifier::sntype private
Definition at line 85 of file qsocketnotifier.h.
Referenced by QSocketNotifier().
sockfd
int QSocketNotifier::sockfd private
Definition at line 84 of file qsocketnotifier.h.
Referenced by event(), QSocketNotifier(), and setEnabled().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qsocketnotifier.h
/src/corelib/kernel/qsocketnotifier.cpp