Qt 4.8: QDeclarativeItemKeyFilter Class Reference
QDeclarativeItemKeyFilter Class Reference
#include <qdeclarativeitem_p.h>
Public Functions
virtual void componentComplete ()
virtual void inputMethodEvent (QInputMethodEvent *event, bool post)
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
virtual void keyPressed (QKeyEvent *event, bool post)
virtual void keyReleased (QKeyEvent *event, bool post)
QDeclarativeItemKeyFilter (QDeclarativeItem *=0)
virtual ~QDeclarativeItemKeyFilter ()
Public Variables
bool m_processPost
Properties
QDeclarativeItemKeyFilter * m_next
Detailed Description
Definition at line 356 of file qdeclarativeitem_p.h.
Constructors and Destructors
QDeclarativeItemKeyFilter()
QDeclarativeItemKeyFilter::QDeclarativeItemKeyFilter (QDeclarativeItem * item = 0)
Definition at line 412 of file qdeclarativeitem.cpp.
 : m_processPost(false), m_next(0)
 {
     QDeclarativeItemPrivate *p =
         item?static_cast<QDeclarativeItemPrivate *>(QGraphicsItemPrivate::get(item)):0;
     if (p) {
         m_next = p->keyHandler;
         p->keyHandler = this;
     }
 }
~QDeclarativeItemKeyFilter()
QDeclarativeItemKeyFilter::~QDeclarativeItemKeyFilter () virtual
Definition at line 423 of file qdeclarativeitem.cpp.
 {
 }
Functions
componentComplete()
void QDeclarativeItemKeyFilter::componentComplete () virtual
Reimplemented in QDeclarativeKeysAttached.
Definition at line 448 of file qdeclarativeitem.cpp.
Referenced by componentComplete().
 {
     if (m_next) m_next->componentComplete();
 }
inputMethodEvent()
void QDeclarativeItemKeyFilter::inputMethodEvent (QInputMethodEvent * event, bool post) virtual
Reimplemented in QDeclarativeKeysAttached.
Definition at line 437 of file qdeclarativeitem.cpp.
Referenced by inputMethodEvent(), and QDeclarativeKeysAttached::inputMethodEvent().
 {
     if (m_next) m_next->inputMethodEvent(event, post);
 }
inputMethodQuery()
QVariant QDeclarativeItemKeyFilter::inputMethodQuery (Qt::InputMethodQuery query) const virtual
Reimplemented in QDeclarativeKeysAttached.
Definition at line 442 of file qdeclarativeitem.cpp.
Referenced by inputMethodQuery(), and QDeclarativeKeysAttached::inputMethodQuery().
 {
     if (m_next) return m_next->inputMethodQuery(query);
     return QVariant();
 }
keyPressed()
void QDeclarativeItemKeyFilter::keyPressed (QKeyEvent * event, bool post) virtual
Reimplemented in QDeclarativeKeysAttached, and QDeclarativeKeyNavigationAttached.
Definition at line 427 of file qdeclarativeitem.cpp.
Referenced by keyPressed(), QDeclarativeKeyNavigationAttached::keyPressed(), and QDeclarativeKeysAttached::keyPressed().
 {
     if (m_next) m_next->keyPressed(event, post);
 }
keyReleased()
void QDeclarativeItemKeyFilter::keyReleased (QKeyEvent * event, bool post) virtual
Reimplemented in QDeclarativeKeysAttached, and QDeclarativeKeyNavigationAttached.
Definition at line 432 of file qdeclarativeitem.cpp.
Referenced by keyReleased(), QDeclarativeKeyNavigationAttached::keyReleased(), and QDeclarativeKeysAttached::keyReleased().
 {
     if (m_next) m_next->keyReleased(event, post);
 }
Properties
m_next
QDeclarativeItemKeyFilter* QDeclarativeItemKeyFilter::m_next private
Definition at line 371 of file qdeclarativeitem_p.h.
Referenced by componentComplete(), inputMethodEvent(), inputMethodQuery(), keyPressed(), keyReleased(), and QDeclarativeItemKeyFilter().
m_processPost
bool QDeclarativeItemKeyFilter::m_processPost
Definition at line 368 of file qdeclarativeitem_p.h.
Referenced by QDeclarativeKeysAttached::inputMethodEvent(), QDeclarativeKeyNavigationAttached::keyPressed(), QDeclarativeKeysAttached::keyPressed(), QDeclarativeKeyNavigationAttached::keyReleased(), QDeclarativeKeysAttached::keyReleased(), QDeclarativeKeyNavigationAttached::QDeclarativeKeyNavigationAttached(), QDeclarativeKeysAttached::QDeclarativeKeysAttached(), QDeclarativeKeyNavigationAttached::setBacktab(), QDeclarativeKeyNavigationAttached::setPriority(), QDeclarativeKeysAttached::setPriority(), and QDeclarativeKeysAttached::~QDeclarativeKeysAttached().
The documentation for this class was generated from the following files:
/src/declarative/graphicsitems/qdeclarativeitem_p.h
/src/declarative/graphicsitems/qdeclarativeitem.cpp