Qt 4.8: QTiffHandler Class Reference
QTiffHandler Class Reference
#include <qtiffhandler_p.h>
Public Types
enum Compression { NoCompression = 0, LzwCompression = 1 }
Public Types inherited from QImageIOHandler
enum ImageOption {
Size, ClipRect, Description, ScaledClipRect,
ScaledSize, CompressionRatio, Gamma, Quality,
Name, SubType, IncrementalReading, Endianness,
Animation, BackgroundColor, ImageFormat
}
This enum describes the different options supported by QImageIOHandler.
Public Functions
bool canRead () const
Returns true if an image can be read from the device (i.
QByteArray name () const
Use format() instead.
QVariant option (ImageOption option) const
Returns the value assigned to option as a QVariant.
QTiffHandler ()
bool read (QImage *image)
Read an image from the device, and stores it in image.
void setOption (ImageOption option, const QVariant &value)
Sets the option option with the value value.
bool supportsOption (ImageOption option) const
Returns true if the QImageIOHandler supports the option option; otherwise returns false.
bool write (const QImage &image)
Writes the image image to the assigned device.
Public Functions inherited from QImageIOHandler
virtual int currentImageNumber () const
For image formats that support animation, this function returns the sequence number of the current image in the animation.
virtual QRect currentImageRect () const
Returns the rect of the current image.
QIODevice * device () const
Returns the device currently assigned to the QImageIOHandler.
QByteArray format () const
Returns the format that is currently assigned to QImageIOHandler.
virtual int imageCount () const
For image formats that support animation, this function returns the number of images in the animation.
virtual bool jumpToImage (int imageNumber)
For image formats that support animation, this function jumps to the image whose sequence number is imageNumber.
virtual bool jumpToNextImage ()
For image formats that support animation, this function jumps to the next image.
virtual int loopCount () const
For image formats that support animation, this function returns the number of times the animation should loop.
virtual int nextImageDelay () const
For image formats that support animation, this function returns the number of milliseconds to wait until reading the next image.
QImageIOHandler ()
Constructs a QImageIOHandler object.
void setDevice (QIODevice *device)
Sets the device of the QImageIOHandler to device.
void setFormat (const QByteArray &format)
Sets the format of the QImageIOHandler to format.
void setFormat (const QByteArray &format) const
Sets the format of the QImageIOHandler to format.
virtual ~QImageIOHandler ()
Destructs the QImageIOHandler object.
Static Public Functions
static bool canRead (QIODevice *device)
Private Functions
void convert32BitOrder (void *buffer, int width)
void convert32BitOrderBigEndian (void *buffer, int width)
Properties
int compression
Additional Inherited Members
Protected Functions inherited from QImageIOHandler
QImageIOHandler (QImageIOHandlerPrivate &dd)
Constructs a QImageIOHandler object, using the private member dd.
Protected Variables inherited from QImageIOHandler
QScopedPointer< QImageIOHandlerPrivate > d_ptr
Detailed Description
Definition at line 49 of file qtiffhandler_p.h.
Enumerations
Compression
enum QTiffHandler::Compression
Enumerator
NoCompression
LzwCompression
Definition at line 66 of file qtiffhandler_p.h.
                      {
         NoCompression = 0,
         LzwCompression = 1
     };
Constructors and Destructors
QTiffHandler()
QTiffHandler::QTiffHandler ()
Definition at line 138 of file qtiffhandler.cpp.
                            : QImageIOHandler()
 {
     compression = NoCompression;
 }
Functions
canRead() [1/2]
bool QTiffHandler::canRead () const virtual
Returns true if an image can be read from the device (i.
e., the image format is supported, the device can be read from and the initial header information suggests that the image can be read); otherwise returns false.
When reimplementing canRead(), make sure that the I/O device (device()) is left in its original state (e.g., by using peek() rather than read()).
See also
read(), QIODevice::peek()
Implements QImageIOHandler.
Definition at line 143 of file qtiffhandler.cpp.
Referenced by QTiffPlugin::capabilities(), createReadHandlerHelper(), option(), and read().
 {
     if (canRead(device())) {
         setFormat("tiff");
         return true;
     }
     return false;
 }
canRead() [2/2]
bool QTiffHandler::canRead (QIODevice * device) static
Definition at line 152 of file qtiffhandler.cpp.
 {
     if (!device) {
         qWarning("QTiffHandler::canRead() called with no device");
         return false;
     }
     // current implementation uses TIFFClientOpen which needs to be
     // able to seek, so sequential devices are not supported
     int pos = device->pos();
     if (pos != 0)
         device->seek(0);  // need the magic from the beginning
     QByteArray header = device->peek(4);
     if (pos != 0)
         device->seek(pos);  // put it back where we found it
     return header == QByteArray::fromRawData("\x49\x49\x2A\x00", 4)
            || header == QByteArray::fromRawData("\x4D\x4D\x00\x2A", 4);
 }
convert32BitOrder()
void QTiffHandler::convert32BitOrder (void * buffer, int width) private
Definition at line 650 of file qtiffhandler.cpp.
Referenced by read(), and write().
 {
     uint32 *target = reinterpret_cast<uint32 *>(buffer);
     for (int32 x=0; x<width; ++x) {
         uint32 p = target[x];
         // convert between ARGB and ABGR
         target[x] = (p & 0xff000000)
                     | ((p & 0x00ff0000) >> 16)
                     | (p & 0x0000ff00)
                     | ((p & 0x000000ff) << 16);
     }
 }
convert32BitOrderBigEndian()
void QTiffHandler::convert32BitOrderBigEndian (void * buffer, int width) private
Definition at line 663 of file qtiffhandler.cpp.
Referenced by write().
 {
     uint32 *target = reinterpret_cast<uint32 *>(buffer);
     for (int32 x=0; x<width; ++x) {
         uint32 p = target[x];
         target[x] = (p & 0xff000000) >> 24
                     | (p & 0x00ff0000) << 8
                     | (p & 0x0000ff00) << 8
                     | (p & 0x000000ff) << 8;
     }
 }
name()
QByteArray QTiffHandler::name () const virtual
Use format() instead.
Reimplemented from QImageIOHandler.
Definition at line 597 of file qtiffhandler.cpp.
 {
     return "tiff";
 }
option()
QVariant QTiffHandler::option (ImageOption option) const virtual
Returns the value assigned to option as a QVariant.
The type of the value depends on the option. For example, option(Size) returns a QSize variant.
See also
setOption(), supportsOption()
Reimplemented from QImageIOHandler.
Definition at line 602 of file qtiffhandler.cpp.
 {
     if (option == Size && canRead()) {
         QSize imageSize;
         qint64 pos = device()->pos();
         TIFF *tiff = TIFFClientOpen("foo",
                                     "r",
                                     const_cast<QTiffHandler*>(this),
                                     qtiffReadProc,
                                     qtiffWriteProc,
                                     qtiffSeekProc,
                                     qtiffCloseProc,
                                     qtiffSizeProc,
                                     qtiffMapProc,
                                     qtiffUnmapProc);
         if (tiff) {
             uint32 width = 0;
             uint32 height = 0;
             TIFFGetField(tiff, TIFFTAG_IMAGEWIDTH, &width);
             TIFFGetField(tiff, TIFFTAG_IMAGELENGTH, &height);
             imageSize = QSize(width, height);
             TIFFClose(tiff);
         }
         device()->seek(pos);
         if (imageSize.isValid())
             return imageSize;
     } else if (option == CompressionRatio) {
         return compression;
     } else if (option == ImageFormat) {
         return QImage::Format_ARGB32;
     }
     return QVariant();
 }
read()
bool QTiffHandler::read (QImage * image) virtual
Read an image from the device, and stores it in image.
Returns true if the image is successfully read; otherwise returns false.
For image formats that support incremental loading, and for animation formats, the image handler can assume that image points to the previous frame.
See also
canRead()
Implements QImageIOHandler.
Definition at line 172 of file qtiffhandler.cpp.
 {
     if (!canRead())
         return false;
     TIFF *const tiff = TIFFClientOpen("foo",
                                       "r",
                                       this,
                                       qtiffReadProc,
                                       qtiffWriteProc,
                                       qtiffSeekProc,
                                       qtiffCloseProc,
                                       qtiffSizeProc,
                                       qtiffMapProc,
                                       qtiffUnmapProc);
     if (!tiff) {
         return false;
     }
     uint32 width;
     uint32 height;
     uint16 photometric;
     if (!TIFFGetField(tiff, TIFFTAG_IMAGEWIDTH, &width)
         || !TIFFGetField(tiff, TIFFTAG_IMAGELENGTH, &height)
         || !TIFFGetField(tiff, TIFFTAG_PHOTOMETRIC, &photometric)) {
         TIFFClose(tiff);
         return false;
     }
     // BitsPerSample defaults to 1 according to the TIFF spec.
     uint16 bitPerSample;
     if (!TIFFGetField(tiff, TIFFTAG_BITSPERSAMPLE, &bitPerSample))
         bitPerSample = 1;
     uint16 samplesPerPixel; // they may be e.g. grayscale with 2 samples per pixel
     if (!TIFFGetField(tiff, TIFFTAG_SAMPLESPERPIXEL, &samplesPerPixel))
         samplesPerPixel = 1;
     bool grayscale = photometric == PHOTOMETRIC_MINISBLACK || photometric == PHOTOMETRIC_MINISWHITE;
     if (grayscale && bitPerSample == 1 && samplesPerPixel == 1) {
         if (image->size() != QSize(width, height) || image->format() != QImage::Format_Mono)
             *image = QImage(width, height, QImage::Format_Mono);
         QVector<QRgb> colortable(2);
         if (photometric == PHOTOMETRIC_MINISBLACK) {
             colortable[0] = 0xff000000;
             colortable[1] = 0xffffffff;
         } else {
             colortable[0] = 0xffffffff;
             colortable[1] = 0xff000000;
         }
         image->setColorTable(colortable);
         if (!image->isNull()) {
             for (uint32 y=0; y<height; ++y) {
                 if (TIFFReadScanline(tiff, image->scanLine(y), y, 0) < 0) {
                     TIFFClose(tiff);
                     return false;
                 }
             }
         }
     } else {
         if ((grayscale || photometric == PHOTOMETRIC_PALETTE) && bitPerSample == 8 && samplesPerPixel == 1) {
             if (image->size() != QSize(width, height) || image->format() != QImage::Format_Indexed8)
                 *image = QImage(width, height, QImage::Format_Indexed8);
             if (!image->isNull()) {
                 const uint16 tableSize = 256;
                 QVector<QRgb> qtColorTable(tableSize);
                 if (grayscale) {
                     for (int i = 0; i<tableSize; ++i) {
                         const int c = (photometric == PHOTOMETRIC_MINISBLACK) ? i : (255 - i);
                         qtColorTable[i] = qRgb(c, c, c);
                     }
                 } else {
                     // create the color table
                     uint16 *redTable = 0;
                     uint16 *greenTable = 0;
                     uint16 *blueTable = 0;
                     if (!TIFFGetField(tiff, TIFFTAG_COLORMAP, &redTable, &greenTable, &blueTable)) {
                         TIFFClose(tiff);
                         return false;
                     }
                     if (!redTable || !greenTable || !blueTable) {
                         TIFFClose(tiff);
                         return false;
                     }
                     for (int i = 0; i<tableSize ;++i) {
                         const int red = redTable[i] / 257;
                         const int green = greenTable[i] / 257;
                         const int blue = blueTable[i] / 257;
                         qtColorTable[i] = qRgb(red, green, blue);
                     }
                 }
                 image->setColorTable(qtColorTable);
                 for (uint32 y=0; y<height; ++y) {
                     if (TIFFReadScanline(tiff, image->scanLine(y), y, 0) < 0) {
                         TIFFClose(tiff);
                         return false;
                     }
                 }
                 // free redTable, greenTable and greenTable done by libtiff
             }
         } else {
             if (image->size() != QSize(width, height) || image->format() != QImage::Format_ARGB32)
                 *image = QImage(width, height, QImage::Format_ARGB32);
             if (!image->isNull()) {
                 const int stopOnError = 1;
                 if (TIFFReadRGBAImageOriented(tiff, width, height, reinterpret_cast<uint32 *>(image->bits()), ORIENTATION_TOPLEFT, stopOnError)) {
                     for (uint32 y=0; y<height; ++y)
                         convert32BitOrder(image->scanLine(y), width);
                 } else {
                     TIFFClose(tiff);
                     return false;
                 }
             }
         }
     }
     if (image->isNull()) {
         TIFFClose(tiff);
         return false;
     }
     float resX = 0;
     float resY = 0;
     uint16 resUnit;
     if (!TIFFGetField(tiff, TIFFTAG_RESOLUTIONUNIT, &resUnit))
         resUnit = RESUNIT_INCH;
     if (TIFFGetField(tiff, TIFFTAG_XRESOLUTION, &resX)
         && TIFFGetField(tiff, TIFFTAG_YRESOLUTION, &resY)) {
         switch(resUnit) {
         case RESUNIT_CENTIMETER:
             image->setDotsPerMeterX(qRound(resX * 100));
             image->setDotsPerMeterY(qRound(resY * 100));
             break;
         case RESUNIT_INCH:
             image->setDotsPerMeterX(qRound(resX * (100 / 2.54)));
             image->setDotsPerMeterY(qRound(resY * (100 / 2.54)));
             break;
         default:
             // do nothing as defaults have already
             // been set within the QImage class
             break;
         }
     }
     // rotate the image if the orientation is defined in the file
     uint16 orientationTag;
     if (TIFFGetField(tiff, TIFFTAG_ORIENTATION, &orientationTag)) {
         if (image->format() == QImage::Format_ARGB32) {
             // TIFFReadRGBAImageOriented() flip the image but does not rotate them
             switch (orientationTag) {
             case 5:
                 rotate_right_mirror_horizontal(image);
                 break;
             case 6:
                 rotate_right_mirror_vertical(image);
                 break;
             case 7:
                 rotate_right_mirror_horizontal(image);
                 break;
             case 8:
                 rotate_right_mirror_vertical(image);
                 break;
             }
         } else {
             switch (orientationTag) {
             case 1: // default orientation
                 break;
             case 2: // mirror horizontal
                 *image = image->mirrored(true, false);
                 break;
             case 3: // mirror both
                 *image = image->mirrored(true, true);
                 break;
             case 4: // mirror vertical
                 *image = image->mirrored(false, true);
                 break;
             case 5: // rotate right mirror horizontal
                 {
                     QMatrix transformation;
                     transformation.rotate(90);
                     *image = image->transformed(transformation);
                     *image = image->mirrored(true, false);
                     break;
                 }
             case 6: // rotate right
                 {
                     QMatrix transformation;
                     transformation.rotate(90);
                     *image = image->transformed(transformation);
                     break;
                 }
             case 7: // rotate right, mirror vertical
                 {
                     QMatrix transformation;
                     transformation.rotate(90);
                     *image = image->transformed(transformation);
                     *image = image->mirrored(false, true);
                     break;
                 }
             case 8: // rotate left
                 {
                     QMatrix transformation;
                     transformation.rotate(270);
                     *image = image->transformed(transformation);
                     break;
                 }
             }
         }
     }
     TIFFClose(tiff);
     return true;
 }
setOption()
void QTiffHandler::setOption (ImageOption option, const QVariant & value) virtual
Sets the option option with the value value.
See also
option(), ImageOption
Reimplemented from QImageIOHandler.
Definition at line 637 of file qtiffhandler.cpp.
 {
     if (option == CompressionRatio && value.type() == QVariant::Int)
         compression = value.toInt();
 }
supportsOption()
bool QTiffHandler::supportsOption (ImageOption option) const virtual
Returns true if the QImageIOHandler supports the option option; otherwise returns false.
For example, if the QImageIOHandler supports the Size option, supportsOption(Size) must return true.
See also
setOption(), option()
Reimplemented from QImageIOHandler.
Definition at line 643 of file qtiffhandler.cpp.
 {
     return option == CompressionRatio
             || option == Size
             || option == ImageFormat;
 }
write()
bool QTiffHandler::write (const QImage & image) virtual
Writes the image image to the assigned device.
Returns true on success; otherwise returns false.
The default implementation does nothing, and simply returns false.
Reimplemented from QImageIOHandler.
Definition at line 405 of file qtiffhandler.cpp.
Referenced by qtiffWriteProc().
 {
     if (!device()->isWritable())
         return false;
     TIFF *const tiff = TIFFClientOpen("foo",
                                       "w",
                                       this,
                                       qtiffReadProc,
                                       qtiffWriteProc,
                                       qtiffSeekProc,
                                       qtiffCloseProc,
                                       qtiffSizeProc,
                                       qtiffMapProc,
                                       qtiffUnmapProc);
     if (!tiff)
         return false;
     const int width = image.width();
     const int height = image.height();
     if (!TIFFSetField(tiff, TIFFTAG_IMAGEWIDTH, width)
         || !TIFFSetField(tiff, TIFFTAG_IMAGELENGTH, height)
         || !TIFFSetField(tiff, TIFFTAG_PLANARCONFIG, PLANARCONFIG_CONTIG)) {
         TIFFClose(tiff);
         return false;
     }
     // set the resolution
     bool  resolutionSet = false;
     const int dotPerMeterX = image.dotsPerMeterX();
     const int dotPerMeterY = image.dotsPerMeterY();
     if ((dotPerMeterX % 100) == 0
         && (dotPerMeterY % 100) == 0) {
         resolutionSet = TIFFSetField(tiff, TIFFTAG_RESOLUTIONUNIT, RESUNIT_CENTIMETER)
                         && TIFFSetField(tiff, TIFFTAG_XRESOLUTION, dotPerMeterX/100.0)
                         && TIFFSetField(tiff, TIFFTAG_YRESOLUTION, dotPerMeterY/100.0);
     } else {
         resolutionSet = TIFFSetField(tiff, TIFFTAG_RESOLUTIONUNIT, RESUNIT_INCH)
                         && TIFFSetField(tiff, TIFFTAG_XRESOLUTION, static_cast<float>(image.logicalDpiX()))
                         && TIFFSetField(tiff, TIFFTAG_YRESOLUTION, static_cast<float>(image.logicalDpiY()));
     }
     if (!resolutionSet) {
         TIFFClose(tiff);
         return false;
     }
     // configure image depth
     const QImage::Format format = image.format();
     if (format == QImage::Format_Mono || format == QImage::Format_MonoLSB) {
         uint16 photometric = PHOTOMETRIC_MINISBLACK;
         if (image.colorTable().at(0) == 0xffffffff)
             photometric = PHOTOMETRIC_MINISWHITE;
         if (!TIFFSetField(tiff, TIFFTAG_PHOTOMETRIC, photometric)
             || !TIFFSetField(tiff, TIFFTAG_COMPRESSION, compression == NoCompression ? COMPRESSION_NONE : COMPRESSION_CCITTRLE)
             || !TIFFSetField(tiff, TIFFTAG_BITSPERSAMPLE, 1)) {
             TIFFClose(tiff);
             return false;
         }
         // try to do the conversion in chunks no greater than 16 MB
         int chunks = (width * height / (1024 * 1024 * 16)) + 1;
         int chunkHeight = qMax(height / chunks, 1);
         int y = 0;
         while (y < height) {
             QImage chunk = image.copy(0, y, width, qMin(chunkHeight, height - y)).convertToFormat(QImage::Format_Mono);
             int chunkStart = y;
             int chunkEnd = y + chunk.height();
             while (y < chunkEnd) {
                 if (TIFFWriteScanline(tiff, reinterpret_cast<uint32 *>(chunk.scanLine(y - chunkStart)), y) != 1) {
                     TIFFClose(tiff);
                     return false;
                 }
                 ++y;
             }
         }
         TIFFClose(tiff);
     } else if (format == QImage::Format_Indexed8) {
         const QVector<QRgb> colorTable = image.colorTable();
         bool isGrayscale = checkGrayscale(colorTable);
         if (isGrayscale) {
             uint16 photometric = PHOTOMETRIC_MINISBLACK;
             if (image.colorTable().at(0) == 0xffffffff)
                 photometric = PHOTOMETRIC_MINISWHITE;
             if (!TIFFSetField(tiff, TIFFTAG_PHOTOMETRIC, photometric)
                     || !TIFFSetField(tiff, TIFFTAG_COMPRESSION, compression == NoCompression ? COMPRESSION_NONE : COMPRESSION_PACKBITS)
                     || !TIFFSetField(tiff, TIFFTAG_BITSPERSAMPLE, 8)) {
                 TIFFClose(tiff);
                 return false;
             }
         } else {
             if (!TIFFSetField(tiff, TIFFTAG_PHOTOMETRIC, PHOTOMETRIC_PALETTE)
                     || !TIFFSetField(tiff, TIFFTAG_COMPRESSION, compression == NoCompression ? COMPRESSION_NONE : COMPRESSION_PACKBITS)
                     || !TIFFSetField(tiff, TIFFTAG_BITSPERSAMPLE, 8)) {
                 TIFFClose(tiff);
                 return false;
             }
             // allocate the color tables
             uint16 *redTable = static_cast<uint16 *>(qMalloc(256 * sizeof(uint16)));
             uint16 *greenTable = static_cast<uint16 *>(qMalloc(256 * sizeof(uint16)));
             uint16 *blueTable = static_cast<uint16 *>(qMalloc(256 * sizeof(uint16)));
             if (!redTable || !greenTable || !blueTable) {
                 qFree(redTable);
                 qFree(greenTable);
                 qFree(blueTable);
                 TIFFClose(tiff);
                 return false;
             }
             // set the color table
             const int tableSize = colorTable.size();
             Q_ASSERT(tableSize <= 256);
             for (int i = 0; i<tableSize; ++i) {
                 const QRgb color = colorTable.at(i);
                 redTable[i] = qRed(color) * 257;
                 greenTable[i] = qGreen(color) * 257;
                 blueTable[i] = qBlue(color) * 257;
             }
             const bool setColorTableSuccess = TIFFSetField(tiff, TIFFTAG_COLORMAP, redTable, greenTable, blueTable);
             qFree(redTable);
             qFree(greenTable);
             qFree(blueTable);
             if (!setColorTableSuccess) {
                 TIFFClose(tiff);
                 return false;
             }
         }
         // try to do the conversion in chunks no greater than 16 MB
         int chunks = (width * height/ (1024 * 1024 * 16)) + 1;
         int chunkHeight = qMax(height / chunks, 1);
         int y = 0;
         while (y < height) {
             QImage chunk = image.copy(0, y, width, qMin(chunkHeight, height - y));
             int chunkStart = y;
             int chunkEnd = y + chunk.height();
             while (y < chunkEnd) {
                 if (TIFFWriteScanline(tiff, reinterpret_cast<uint32 *>(chunk.scanLine(y - chunkStart)), y) != 1) {
                     TIFFClose(tiff);
                     return false;
                 }
                 ++y;
             }
         }
         TIFFClose(tiff);
     } else {
         if (!TIFFSetField(tiff, TIFFTAG_PHOTOMETRIC, PHOTOMETRIC_RGB)
             || !TIFFSetField(tiff, TIFFTAG_COMPRESSION, compression == NoCompression ? COMPRESSION_NONE : COMPRESSION_LZW)
             || !TIFFSetField(tiff, TIFFTAG_SAMPLESPERPIXEL, 4)
             || !TIFFSetField(tiff, TIFFTAG_BITSPERSAMPLE, 8)) {
             TIFFClose(tiff);
             return false;
         }
         // try to do the ARGB32 conversion in chunks no greater than 16 MB
         int chunks = (width * height * 4 / (1024 * 1024 * 16)) + 1;
         int chunkHeight = qMax(height / chunks, 1);
         int y = 0;
         while (y < height) {
             QImage chunk = image.copy(0, y, width, qMin(chunkHeight, height - y)).convertToFormat(QImage::Format_ARGB32);
             int chunkStart = y;
             int chunkEnd = y + chunk.height();
             while (y < chunkEnd) {
                 if (QSysInfo::ByteOrder == QSysInfo::LittleEndian)
                     convert32BitOrder(chunk.scanLine(y - chunkStart), width);
                 else
                     convert32BitOrderBigEndian(chunk.scanLine(y - chunkStart), width);
                 if (TIFFWriteScanline(tiff, reinterpret_cast<uint32 *>(chunk.scanLine(y - chunkStart)), y) != 1) {
                     TIFFClose(tiff);
                     return false;
                 }
                 ++y;
             }
         }
         TIFFClose(tiff);
     }
     return true;
 }
Properties
compression
int QTiffHandler::compression private
Definition at line 73 of file qtiffhandler_p.h.
Referenced by option(), QTiffHandler(), setOption(), and write().
The documentation for this class was generated from the following files:
/src/gui/image/qtiffhandler_p.h
/src/gui/image/qtiffhandler.cpp