Qt 4.8: QOfonoPrimaryDataContextInterface Class Reference
QOfonoPrimaryDataContextInterface Class Reference
#include <qofonoservice_linux_p.h>
Public Functions
QString getAddress ()
QString getApName ()
QString getInterface ()
QString getName ()
QVariantMap getProperties ()
QVariantMap getSettings ()
QString getType ()
bool isActive ()
QOfonoPrimaryDataContextInterface (const QString &dbusPathName, QObject *parent=0)
bool setActive (bool on)
bool setApn (const QString &name)
~QOfonoPrimaryDataContextInterface ()
Public Functions inherited from QDBusAbstractInterface
QDBusPendingCall asyncCall (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusPendingCall asyncCallWithArgumentList (const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
QDBusMessage call (const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage call (QDBus::CallMode mode, const QString &method, const QVariant &arg1=QVariant(), const QVariant &arg2=QVariant(), const QVariant &arg3=QVariant(), const QVariant &arg4=QVariant(), const QVariant &arg5=QVariant(), const QVariant &arg6=QVariant(), const QVariant &arg7=QVariant(), const QVariant &arg8=QVariant())
Calls the method method on this interface and passes the parameters to this function to the method.
QDBusMessage callWithArgumentList (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member, const char *errorSlot)
Places a call to the remote method specified by method on this interface, using args as arguments.
bool callWithCallback (const QString &method, const QList< QVariant > &args, QObject *receiver, const char *member)
This function is deprecated.
QDBusConnection connection () const
Returns the connection this interface is assocated with.
QString interface () const
Returns the name of this interface.
bool isValid () const
Returns true if this is a valid reference to a remote object.
QDBusError lastError () const
Returns the error the last operation produced, or an invalid error if the last operation did not produce an error.
QString path () const
Returns the object path that this interface is associated with.
QString service () const
Returns the name of the service this interface is associated with.
void setTimeout (int timeout)
Sets the timeout in milliseconds for all future DBus calls to timeout.
int timeout () const
Returns the current value of the timeout in milliseconds.
virtual ~QDBusAbstractInterface ()
Releases this object's resources.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
void connectNotify (const char *signal)
Catch signal connections.
void disconnectNotify (const char *signal)
Catch signal disconnections.
QVariant getProperty (const QString &)
bool setProp (const QString &, const QVariant &var)
Protected Functions inherited from QDBusAbstractInterface
QDBusMessage internalConstCall (QDBus::CallMode mode, const QString &method, const QList< QVariant > &args=QList< QVariant >()) const
QVariant internalPropGet (const char *propname) const
Get the value of the property propname.
void internalPropSet (const char *propname, const QVariant &value)
Set the value of the property propname to value.
QDBusAbstractInterface (const QString &service, const QString &path, const char *interface, const QDBusConnection &connection, QObject *parent)
This is the constructor called from static classes derived from QDBusAbstractInterface (i.
QDBusAbstractInterface (QDBusAbstractInterfacePrivate &, QObject *parent)
This is the constructor called from QDBusInterface::QDBusInterface.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 284 of file qofonoservice_linux_p.h.
Constructors and Destructors
QOfonoPrimaryDataContextInterface()
QOfonoPrimaryDataContextInterface::QOfonoPrimaryDataContextInterface (const QString & dbusPathName, QObject * parent = 0)
Definition at line 751 of file qofonoservice_linux.cpp.
     : QDBusAbstractInterface(QLatin1String(OFONO_SERVICE),
                              dbusPathName,
                              OFONO_DATA_CONTEXT_INTERFACE,
                              QDBusConnection::systemBus(), parent)
 {
 }
~QOfonoPrimaryDataContextInterface()
QOfonoPrimaryDataContextInterface::~QOfonoPrimaryDataContextInterface ()
Definition at line 759 of file qofonoservice_linux.cpp.
 {
 }
Functions
connectNotify()
void QOfonoPrimaryDataContextInterface::connectNotify (const char * signal) protected virtual
Catch signal connections.
Warning
This function is not part of the public interface.
Reimplemented from QDBusAbstractInterface.
Definition at line 817 of file qofonoservice_linux.cpp.
 {
 if (QLatin1String(signal) == SIGNAL(propertyChanged(QString,QDBusVariant))) {
         if (!connection().connect(QLatin1String(OFONO_SERVICE),
                                this->path(),
                                QLatin1String(OFONO_DATA_CONTEXT_INTERFACE),
                                QLatin1String("PropertyChanged"),
                                this,SIGNAL(propertyChanged(const QString &, const QDBusVariant & )))) {
             qWarning() << "PropertyCHanged not connected";
         }
     }
     if (QLatin1String(signal) == SIGNAL(propertyChangedContext(QString,QString,QDBusVariant))) {
         QOfonoDBusHelper *helper;
         helper = new QOfonoDBusHelper(this);
         dbusConnection.connect(QLatin1String(OFONO_SERVICE),
                                this->path(),
                                QLatin1String(OFONO_DATA_CONTEXT_INTERFACE),
                                QLatin1String("PropertyChanged"),
                                helper,SLOT(propertyChanged(QString,QDBusVariant)));
         QObject::connect(helper,SIGNAL(propertyChangedContext(const QString &,const QString &,const QDBusVariant &)),
                 this,SIGNAL(propertyChangedContext(const QString &,const QString &,const QDBusVariant &)), Qt::UniqueConnection);
     }
 }
disconnectNotify()
void QOfonoPrimaryDataContextInterface::disconnectNotify (const char * signal) protected virtual
Catch signal disconnections.
Warning
This function is not part of the public interface.
Reimplemented from QDBusAbstractInterface.
Definition at line 845 of file qofonoservice_linux.cpp.
 {
     if (QLatin1String(signal) == SIGNAL(propertyChanged(QString,QVariant))) {
     }
 }
getAddress()
QString QOfonoPrimaryDataContextInterface::getAddress ()
Definition at line 799 of file qofonoservice_linux.cpp.
 {
     QVariant var = getProperty("Address");
     return qdbus_cast<QString>(var);
 }
getApName()
QString QOfonoPrimaryDataContextInterface::getApName ()
Definition at line 769 of file qofonoservice_linux.cpp.
 {
     QVariant var = getProperty("AccessPointName");
     return qdbus_cast<QString>(var);
 }
getInterface()
QString QOfonoPrimaryDataContextInterface::getInterface ()
Definition at line 793 of file qofonoservice_linux.cpp.
 {
     QVariant var = getProperty("Interface");
     return qdbus_cast<QString>(var);
 }
getName()
QString QOfonoPrimaryDataContextInterface::getName ()
Definition at line 781 of file qofonoservice_linux.cpp.
 {
     QVariant var = getProperty("Name");
     return qdbus_cast<QString>(var);
 }
getProperties()
QVariantMap QOfonoPrimaryDataContextInterface::getProperties ()
Definition at line 864 of file qofonoservice_linux.cpp.
Referenced by getProperty().
 {
     QDBusReply<QVariantMap > reply =  this->call(QLatin1String("GetProperties"));
     return reply.value();
 }
getProperty()
QVariant QOfonoPrimaryDataContextInterface::getProperty (const QString & property) protected
Definition at line 852 of file qofonoservice_linux.cpp.
Referenced by getAddress(), getApName(), getInterface(), getName(), getSettings(), getType(), and isActive().
 {
     QVariant var;
     QVariantMap map = getProperties();
     if (map.contains(property)) {
         var = map.value(property);
     } else {
         qDebug() << Q_FUNC_INFO << "does not contain" << property;
     }
     return var;
 }
getSettings()
QVariantMap QOfonoPrimaryDataContextInterface::getSettings ()
Definition at line 787 of file qofonoservice_linux.cpp.
 {
     QVariant var = getProperty("Settings");
     return qdbus_cast<QVariantMap>(var);
 }
getType()
QString QOfonoPrimaryDataContextInterface::getType ()
Definition at line 775 of file qofonoservice_linux.cpp.
 {
     QVariant var = getProperty("Type");
     return qdbus_cast<QString>(var);
 }
isActive()
bool QOfonoPrimaryDataContextInterface::isActive ()
Definition at line 763 of file qofonoservice_linux.cpp.
 {
     QVariant var = getProperty("Active");
     return qdbus_cast<bool>(var);
 }
setActive()
bool QOfonoPrimaryDataContextInterface::setActive (bool on)
Definition at line 805 of file qofonoservice_linux.cpp.
Referenced by QConnmanEngine::connectToId(), and QConnmanEngine::disconnectFromId().
 {
 //    this->setProperty("Active", QVariant(on));
     return setProp("Active", qVariantFromValue(on));
 }
setApn()
bool QOfonoPrimaryDataContextInterface::setApn (const QString & name)
Definition at line 812 of file qofonoservice_linux.cpp.
 {
     return setProp("AccessPointName", QVariant::fromValue(name));
 }
setProp()
bool QOfonoPrimaryDataContextInterface::setProp (const QString & property, const QVariant & var) protected
Definition at line 870 of file qofonoservice_linux.cpp.
Referenced by setActive(), and setApn().
 {
     QList<QVariant> args;
     args << qVariantFromValue(property) << qVariantFromValue(QDBusVariant(var));
     QDBusMessage reply = this->callWithArgumentList(QDBus::AutoDetect,
                                                     QLatin1String("SetProperty"),
                                                     args);
     bool ok = true;
     if (reply.type() != QDBusMessage::ReplyMessage) {
         qWarning() << reply.errorMessage();
         ok = false;
     }
     qWarning() << reply.errorMessage();
     return ok;
 }
The documentation for this class was generated from the following files:
/src/plugins/bearer/connman/qofonoservice_linux_p.h
/src/plugins/bearer/connman/qofonoservice_linux.cpp