Qt 4.8: QHttpHeader Class Reference
QHttpHeader Class Reference abstract
The QHttpHeader class contains header information for HTTP.
#include <qhttp.h>
Public Functions
void addValue (const QString &key, const QString &value)
Adds a new entry with the key and value.
QStringList allValues (const QString &key) const
Returns all the entries with the given key.
uint contentLength () const
Returns the value of the special HTTP header field content-length.
QString contentType () const
Returns the value of the special HTTP header field content-type.
bool hasContentLength () const
Returns true if the header has an entry for the special HTTP header field content-length; otherwise returns false.
bool hasContentType () const
Returns true if the header has an entry for the special HTTP header field content-type; otherwise returns false.
bool hasKey (const QString &key) const
Returns true if the HTTP header has an entry with the given key; otherwise returns false.
bool isValid () const
Returns true if the HTTP header is valid; otherwise returns false.
QStringList keys () const
Returns a list of the keys in the HTTP header.
virtual int majorVersion () const =0
Returns the major protocol-version of the HTTP header.
virtual int minorVersion () const =0
Returns the minor protocol-version of the HTTP header.
QHttpHeader & operator= (const QHttpHeader &h)
Assigns h and returns a reference to this http header.
QHttpHeader ()
Constructs an empty HTTP header.
QHttpHeader (const QHttpHeader &header)
Constructs a copy of header.
QHttpHeader (const QString &str)
Constructs a HTTP header for str.
void removeAllValues (const QString &key)
Removes all the entries with the key key from the HTTP header.
void removeValue (const QString &key)
Removes the entry with the key key from the HTTP header.
void setContentLength (int len)
Sets the value of the special HTTP header field content-length to len.
void setContentType (const QString &type)
Sets the value of the special HTTP header field content-type to type.
void setValue (const QString &key, const QString &value)
Sets the value of the entry with the key to value.
void setValues (const QList< QPair< QString, QString > > &values)
Sets the header entries to be the list of key value pairs in values.
virtual QString toString () const
Returns a string representation of the HTTP header.
QString value (const QString &key) const
Returns the first value for the entry with the given key.
QList< QPair< QString, QString > > values () const
Returns all the entries in the header.
virtual ~QHttpHeader ()
Destructor.
Protected Functions
bool parse (const QString &str)
Parses the HTTP header string str for header fields and adds the keys/values it finds.
virtual bool parseLine (const QString &line, int number)
Parses the single HTTP header line line which has the format key, colon, space, value, and adds key/value to the headers.
QHttpHeader (QHttpHeaderPrivate &dd, const QString &str=QString())
QHttpHeader (QHttpHeaderPrivate &dd, const QHttpHeader &header)
void setValid (bool)
Protected Variables
QScopedPointer< QHttpHeaderPrivate > d_ptr
Detailed Description
The QHttpHeader class contains header information for HTTP.
Attention
Module: QtNetwork
In most cases you should use the more specialized derivatives of this class, QHttpResponseHeader and QHttpRequestHeader, rather than directly using QHttpHeader.
QHttpHeader provides the HTTP header fields. A HTTP header field consists of a name followed by a colon, a single space, and the field value. (See RFC 1945.) Field names are case-insensitive. A typical header field looks like this:
content-type: text/html
In the API the header field name is called the "key" and the content is called the "value". You can get and set a header field's value by using its key with value() and setValue(), e.g.
header.setValue("content-type", "text/html");
QString contentType = header.value("content-type");
Some fields are so common that getters and setters are provided for them as a convenient alternative to using value() and setValue() , e.g. contentLength() and contentType(), setContentLength() and setContentType().
Each header key has a single value associated with it. If you set the value for a key which already exists the previous value will be discarded.
See also
QHttpRequestHeader QHttpResponseHeader
Definition at line 69 of file qhttp.h.
Constructors and Destructors
QHttpHeader() [1/5]
QHttpHeader::QHttpHeader ()
Constructs an empty HTTP header.
Definition at line 578 of file qhttp.cpp.
     : d_ptr(new QHttpHeaderPrivate)
 {
     Q_D(QHttpHeader);
     d->q_ptr = this;
     d->valid = true;
 }
QHttpHeader() [2/5]
QHttpHeader::QHttpHeader (const QHttpHeader & header)
Constructs a copy of header.
Definition at line 589 of file qhttp.cpp.
     : d_ptr(new QHttpHeaderPrivate)
 {
     Q_D(QHttpHeader);
     d->q_ptr = this;
     d->valid = header.d_func()->valid;
     d->values = header.d_func()->values;
 }
QHttpHeader() [3/5]
QHttpHeader::QHttpHeader (const QString & str)
Constructs a HTTP header for str.
This constructor parses the string str for header fields and adds this information. The str should consist of one or more "\r\n" delimited lines; each of these lines should have the format key, colon, space, value.
Definition at line 606 of file qhttp.cpp.
     : d_ptr(new QHttpHeaderPrivate)
 {
     Q_D(QHttpHeader);
     d->q_ptr = this;
     d->valid = true;
     parse(str);
 }
~QHttpHeader()
QHttpHeader::~QHttpHeader () virtual
Destructor.
Definition at line 640 of file qhttp.cpp.
 {
 }
QHttpHeader() [4/5]
QHttpHeader::QHttpHeader (QHttpHeaderPrivate & dd, const QString & str = QString()) protected
Warning
This function is not part of the public interface.
Definition at line 617 of file qhttp.cpp.
     : d_ptr(&dd)
 {
     Q_D(QHttpHeader);
     d->q_ptr = this;
     d->valid = true;
     if (!str.isEmpty())
         parse(str);
 }
QHttpHeader() [5/5]
QHttpHeader::QHttpHeader (QHttpHeaderPrivate & dd, const QHttpHeader & header) protected
Warning
This function is not part of the public interface.
Definition at line 629 of file qhttp.cpp.
     : d_ptr(&dd)
 {
     Q_D(QHttpHeader);
     d->q_ptr = this;
     d->valid = header.d_func()->valid;
     d->values = header.d_func()->values;
 }
Functions
addValue()
void QHttpHeader::addValue (const QString & key, const QString & value)
Adds a new entry with the key and value.
Definition at line 843 of file qhttp.cpp.
Referenced by parseLine(), and setValue().
 {
     Q_D(QHttpHeader);
     d->values.append(qMakePair(key, value));
 }
allValues()
QStringList QHttpHeader::allValues (const QString & key) const
Returns all the entries with the given key.
If no entry has this key, an empty string list is returned.
Definition at line 749 of file qhttp.cpp.
 {
     Q_D(const QHttpHeader);
     QString lowercaseKey = key.toLower();
     QStringList valueList;
     QList<QPair<QString, QString> >::ConstIterator it = d->values.constBegin();
     while (it != d->values.constEnd()) {
         if ((*it).first.toLower() == lowercaseKey)
             valueList.append((*it).second);
         ++it;
     }
     return valueList;
 }
contentLength()
uint QHttpHeader::contentLength () const
Returns the value of the special HTTP header field content-length.
See also
setContentLength() hasContentLength()
Definition at line 956 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotClosed(), and QHttpPrivate::_q_slotReadyRead().
 {
     return value(QLatin1String("content-length")).toUInt();
 }
contentType()
QString QHttpHeader::contentType () const
Returns the value of the special HTTP header field content-type.
See also
setContentType() hasContentType()
Definition at line 988 of file qhttp.cpp.
 {
     QString type = value(QLatin1String("content-type"));
     if (type.isEmpty())
         return QString();
     int pos = type.indexOf(QLatin1Char(';'));
     if (pos == -1)
         return type;
     return type.left(pos).trimmed();
 }
hasContentLength()
bool QHttpHeader::hasContentLength () const
Returns true if the header has an entry for the special HTTP header field content-length; otherwise returns false.
See also
contentLength() setContentLength()
Definition at line 945 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead().
 {
     return hasKey(QLatin1String("content-length"));
 }
hasContentType()
bool QHttpHeader::hasContentType () const
Returns true if the header has an entry for the special HTTP header field content-type; otherwise returns false.
See also
contentType() setContentType()
Definition at line 978 of file qhttp.cpp.
 {
     return hasKey(QLatin1String("content-type"));
 }
hasKey()
bool QHttpHeader::hasKey (const QString & key) const
Returns true if the HTTP header has an entry with the given key; otherwise returns false.
See also
value() setValue() keys()
Definition at line 792 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotClosed(), QHttpPrivate::_q_slotReadyRead(), hasContentLength(), and hasContentType().
 {
     Q_D(const QHttpHeader);
     QString lowercaseKey = key.toLower();
     QList<QPair<QString, QString> >::ConstIterator it = d->values.constBegin();
     while (it != d->values.constEnd()) {
         if ((*it).first.toLower() == lowercaseKey)
             return true;
         ++it;
     }
     return false;
 }
isValid()
bool QHttpHeader::isValid () const
Returns true if the HTTP header is valid; otherwise returns false.
A QHttpHeader is invalid if it was created by parsing a malformed string.
Definition at line 660 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotReadyRead(), and toString().
 {
     Q_D(const QHttpHeader);
     return d->valid;
 }
keys()
QStringList QHttpHeader::keys () const
Returns a list of the keys in the HTTP header.
See also
hasKey()
Definition at line 768 of file qhttp.cpp.
 {
     Q_D(const QHttpHeader);
     QStringList keyList;
     QSet<QString> seenKeys;
     QList<QPair<QString, QString> >::ConstIterator it = d->values.constBegin();
     while (it != d->values.constEnd()) {
         const QString &key = (*it).first;
         QString lowercaseKey = key.toLower();
         if (!seenKeys.contains(lowercaseKey)) {
             keyList.append(key);
             seenKeys.insert(lowercaseKey);
         }
         ++it;
     }
     return keyList;
 }
majorVersion()
int QHttpHeader::majorVersion () const pure virtual
Returns the major protocol-version of the HTTP header.
Implemented in QHttpRequestHeader, and QHttpResponseHeader.
minorVersion()
int QHttpHeader::minorVersion () const pure virtual
Returns the minor protocol-version of the HTTP header.
Implemented in QHttpRequestHeader, and QHttpResponseHeader.
operator=()
QHttpHeader & QHttpHeader::operator= (const QHttpHeader & h)
Assigns h and returns a reference to this http header.
Definition at line 647 of file qhttp.cpp.
Referenced by QHttpResponseHeader::operator=(), and QHttpRequestHeader::operator=().
 {
     Q_D(QHttpHeader);
     d->values = h.d_func()->values;
     d->valid = h.d_func()->valid;
     return *this;
 }
parse()
bool QHttpHeader::parse (const QString & str) protected
Parses the HTTP header string str for header fields and adds the keys/values it finds.
Warning
This function is not part of the public interface. If the string is not parsed successfully the QHttpHeader becomes invalid.
Returns true if str was successfully parsed; otherwise returns false.
See also
toString()
Definition at line 678 of file qhttp.cpp.
Referenced by QHttpHeader(), QHttpRequestHeader::QHttpRequestHeader(), and QHttpResponseHeader::QHttpResponseHeader().
 {
     Q_D(QHttpHeader);
     QStringList lst;
     int pos = str.indexOf(QLatin1Char('\n'));
     if (pos > 0 && str.at(pos - 1) == QLatin1Char('\r'))
         lst = str.trimmed().split(QLatin1String("\r\n"));
     else
         lst = str.trimmed().split(QLatin1String("\n"));
     lst.removeAll(QString()); // No empties
     if (lst.isEmpty())
         return true;
     QStringList lines;
     QStringList::Iterator it = lst.begin();
     for (; it != lst.end(); ++it) {
         if (!(*it).isEmpty()) {
             if ((*it)[0].isSpace()) {
                 if (!lines.isEmpty()) {
                     lines.last() += QLatin1Char(' ');
                     lines.last() += (*it).trimmed();
                 }
             } else {
                 lines.append((*it));
             }
         }
     }
     int number = 0;
     it = lines.begin();
     for (; it != lines.end(); ++it) {
         if (!parseLine(*it, number++)) {
             d->valid = false;
             return false;
         }
     }
     return true;
 }
parseLine()
bool QHttpHeader::parseLine (const QString & line, int number) protected virtual
Parses the single HTTP header line line which has the format key, colon, space, value, and adds key/value to the headers.
Warning
This function is not part of the public interface. The linenumber is number. Returns true if the line was successfully parsed and the key/value added; otherwise returns false.
See also
parse()
Reimplemented in QHttpRequestHeader, and QHttpResponseHeader.
Definition at line 905 of file qhttp.cpp.
Referenced by parse(), QHttpResponseHeader::parseLine(), and QHttpRequestHeader::parseLine().
 {
     int i = line.indexOf(QLatin1Char(':'));
     if (i == -1)
         return false;
     addValue(line.left(i).trimmed(), line.mid(i + 1).trimmed());
     return true;
 }
removeAllValues()
void QHttpHeader::removeAllValues (const QString & key)
Removes all the entries with the key key from the HTTP header.
Definition at line 880 of file qhttp.cpp.
 {
     Q_D(QHttpHeader);
     QString lowercaseKey = key.toLower();
     QList<QPair<QString, QString> >::Iterator it = d->values.begin();
     while (it != d->values.end()) {
         if ((*it).first.toLower() == lowercaseKey) {
             it = d->values.erase(it);
             continue;
         }
         ++it;
     }
 }
removeValue()
void QHttpHeader::removeValue (const QString & key)
Removes the entry with the key key from the HTTP header.
See also
value() setValue()
Definition at line 863 of file qhttp.cpp.
 {
     Q_D(QHttpHeader);
     QString lowercaseKey = key.toLower();
     QList<QPair<QString, QString> >::Iterator it = d->values.begin();
     while (it != d->values.end()) {
         if ((*it).first.toLower() == lowercaseKey) {
             d->values.erase(it);
             return;
         }
         ++it;
     }
 }
setContentLength()
void QHttpHeader::setContentLength (int len)
Sets the value of the special HTTP header field content-length to len.
See also
contentLength() hasContentLength()
Definition at line 967 of file qhttp.cpp.
 {
     setValue(QLatin1String("content-length"), QString::number(len));
 }
setContentType()
void QHttpHeader::setContentType (const QString & type)
Sets the value of the special HTTP header field content-type to type.
See also
contentType() hasContentType()
Definition at line 1007 of file qhttp.cpp.
 {
     setValue(QLatin1String("content-type"), type);
 }
setValid()
void QHttpHeader::setValid (bool v) protected
Warning
This function is not part of the public interface.
Definition at line 720 of file qhttp.cpp.
Referenced by QHttpRequestHeader::QHttpRequestHeader(), QHttpResponseHeader::QHttpResponseHeader(), QHttpRequestHeader::setRequest(), and QHttpResponseHeader::setStatusLine().
 {
     Q_D(QHttpHeader);
     d->valid = v;
 }
setValue()
void QHttpHeader::setValue (const QString & key, const QString & value)
Sets the value of the entry with the key to value.
If no entry with key exists, a new entry with the given key and value is created. If an entry with the key already exists, the first value is discarded and replaced with the given value.
See also
value() hasKey() removeValue()
Definition at line 815 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QHttp::get(), QHttp::head(), QHttp::post(), setContentLength(), setContentType(), and QHttpPGHRequest::start().
 {
     Q_D(QHttpHeader);
     QString lowercaseKey = key.toLower();
     QList<QPair<QString, QString> >::Iterator it = d->values.begin();
     while (it != d->values.end()) {
         if ((*it).first.toLower() == lowercaseKey) {
             (*it).second = value;
             return;
         }
         ++it;
     }
     // not found so add
     addValue(key, value);
 }
setValues()
void QHttpHeader::setValues (const QList< QPair< QString, QString > > & values)
Sets the header entries to be the list of key value pairs in values.
Definition at line 834 of file qhttp.cpp.
 {
     Q_D(QHttpHeader);
     d->values = values;
 }
toString()
QString QHttpHeader::toString () const virtual
Returns a string representation of the HTTP header.
The string is suitable for use by the constructor that takes a QString. It consists of lines with the format: key, colon, space, value, "\r\n".
Reimplemented in QHttpRequestHeader, and QHttpResponseHeader.
Definition at line 923 of file qhttp.cpp.
Referenced by QHttpResponseHeader::toString(), and QHttpRequestHeader::toString().
 {
     Q_D(const QHttpHeader);
     if (!isValid())
         return QLatin1String("");
     QString ret = QLatin1String("");
     QList<QPair<QString, QString> >::ConstIterator it = d->values.constBegin();
     while (it != d->values.constEnd()) {
         ret += (*it).first + QLatin1String(": ") + (*it).second + QLatin1String("\r\n");
         ++it;
     }
     return ret;
 }
value()
QString QHttpHeader::value (const QString & key) const
Returns the first value for the entry with the given key.
If no entry has this key, an empty string is returned.
See also
setValue() removeValue() hasKey() keys()
Definition at line 732 of file qhttp.cpp.
Referenced by QHttpPrivate::_q_slotConnected(), QHttpPrivate::_q_slotReadyRead(), contentLength(), contentType(), setValue(), and QHttpSocketEngine::slotSocketReadNotification().
 {
     Q_D(const QHttpHeader);
     QString lowercaseKey = key.toLower();
     QList<QPair<QString, QString> >::ConstIterator it = d->values.constBegin();
     while (it != d->values.constEnd()) {
         if ((*it).first.toLower() == lowercaseKey)
             return (*it).second;
         ++it;
     }
     return QString();
 }
values()
QList< QPair< QString, QString > > QHttpHeader::values () const
Returns all the entries in the header.
Definition at line 852 of file qhttp.cpp.
Referenced by operator=(), QAuthenticatorPrivate::parseHttpResponse(), QHttpHeader(), and setValues().
 {
     Q_D(const QHttpHeader);
     return d->values;
 }
Properties
d_ptr
QScopedPointer<QHttpHeaderPrivate> QHttpHeader::d_ptr protected
Definition at line 112 of file qhttp.h.
The documentation for this class was generated from the following files:
/src/network/access/qhttp.h
/src/network/access/qhttp.cpp