Qt 4.8: QJSDebuggerAgent Class Reference
QJSDebuggerAgent Class Reference
#include <qjsdebuggeragent_p.h>
Signals
void stopped (bool becauseOfException, const QString &exception)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QList< JSAgentStackData > backtrace ()
void contextPop ()
Reimplemented Function
void contextPush ()
Reimplemented Function
void continueExecution ()
void exceptionCatch (qint64 scriptId, const QScriptValue &exception)
Reimplemented Function
void exceptionThrow (qint64 scriptId, const QScriptValue &exception, bool hasHandler)
Reimplemented Function
JSAgentWatchData executeExpression (const QString &expr)
QList< JSAgentWatchData > expandObjectById (quint64 objectId)
QVariant extension (Extension extension, const QVariant &argument=QVariant())
This virtual function can be reimplemented in a QScriptEngineAgent subclass to provide support for extensions.
void functionEntry (qint64 scriptId)
Reimplemented Function
void functionExit (qint64 scriptId, const QScriptValue &returnValue)
Reimplemented Function
bool isInitialized () const
Indicates whether the agent got the list of breakpoints.
QList< JSAgentWatchData > locals ()
QList< JSAgentWatchData > localsAtFrame (int frameId)
void positionChange (qint64 scriptId, int lineNumber, int columnNumber)
Reimplemented Function
QJSDebuggerAgent (QScriptEngine *engine, QObject *parent=0)
Constructs a new agent for the given engine.
QJSDebuggerAgent (QDeclarativeEngine *engine, QObject *parent=0)
void scriptLoad (qint64 id, const QString &program, const QString &fileName, int baseLineNumber)
Reimplemented Function
void scriptUnload (qint64 id)
Reimplemented Function
void setBreakpoints (const JSAgentBreakpoints &)
void setCoverageEnabled (bool enabled)
void setProperty (qint64 objectId, const QString &property, const QString &value)
void setWatchExpressions (const QStringList &)
void stepInto ()
void stepOut ()
void stepOver ()
bool supportsExtension (Extension extension) const
Returns true if the QScriptEngineAgent supports the given extension; otherwise, false is returned.
QList< JSAgentWatchData > watches ()
~QJSDebuggerAgent ()
Destroys this QJSDebuggerAgent.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QScriptEngineAgent
QScriptEngine * engine () const
Returns the QScriptEngine that this agent is associated with.
QScriptEngineAgent (QScriptEngine *engine)
Constructs a QScriptEngineAgent object for the given engine.
virtual ~QScriptEngineAgent ()
Destroys this QScriptEngineAgent.
Properties
QJSDebuggerAgentPrivate * d
Friends
class QJSDebuggerAgentPrivate
Additional Inherited Members
Public Types inherited from QScriptEngineAgent
enum Extension { DebuggerInvocationRequest }
This enum specifies the possible extensions to a QScriptEngineAgent.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QScriptEngineAgent
QScriptEngineAgent (QScriptEngineAgentPrivate &dd, QScriptEngine *engine)
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QScriptEngineAgent
QScopedPointer< QScriptEngineAgentPrivate > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 161 of file qjsdebuggeragent_p.h.
Constructors and Destructors
QJSDebuggerAgent() [1/2]
QJSDebuggerAgent::QJSDebuggerAgent (QScriptEngine * engine, QObject * parent = 0)
Constructs a new agent for the given engine.
The agent will report debugging-related events (e.g. step completion) to the given backend.
Definition at line 233 of file qjsdebuggeragent.cpp.
     : QObject(parent)
     , QScriptEngineAgent(engine)
     , d(new QJSDebuggerAgentPrivate(this))
 {
     QJSDebuggerAgent::engine()->setAgent(this);
 }
QJSDebuggerAgent() [2/2]
QJSDebuggerAgent::QJSDebuggerAgent (QDeclarativeEngine * engine, QObject * parent = 0)
Definition at line 241 of file qjsdebuggeragent.cpp.
     : QObject(parent)
     , QScriptEngineAgent(QDeclarativeDebugHelper::getScriptEngine(engine))
     , d(new QJSDebuggerAgentPrivate(this))
 {
     QJSDebuggerAgent::engine()->setAgent(this);
 }
~QJSDebuggerAgent()
QJSDebuggerAgent::~QJSDebuggerAgent ()
Destroys this QJSDebuggerAgent.
Definition at line 252 of file qjsdebuggeragent.cpp.
 {
     engine()->setAgent(0);
     delete d;
 }
Functions
backtrace()
QList< JSAgentStackData > QJSDebuggerAgent::backtrace ()
Definition at line 357 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::executionStopped().
 {
     SetupExecEnv execEnv(d);
     QList<JSAgentStackData> backtrace;
     for (QScriptContext *ctx = engine()->currentContext(); ctx; ctx = ctx->parentContext()) {
         QScriptContextInfo info(ctx);
         JSAgentStackData frame;
         frame.functionName = info.functionName().toUtf8();
         if (frame.functionName.isEmpty()) {
             if (ctx->parentContext()) {
                 switch (info.functionType()) {
                 case QScriptContextInfo::ScriptFunction:
                     frame.functionName = "<anonymous>";
                     break;
                 case QScriptContextInfo::NativeFunction:
                     frame.functionName = "<native>";
                     break;
                 case QScriptContextInfo::QtFunction:
                 case QScriptContextInfo::QtPropertyFunction:
                     frame.functionName = "<native slot>";
                     break;
                 }
             } else {
                 frame.functionName = "<global>";
             }
         }
         frame.lineNumber = info.lineNumber();
         // if the line number is unknown, fallback to the function line number
         if (frame.lineNumber == -1)
             frame.lineNumber = info.functionStartLineNumber();
         frame.fileUrl = info.fileName().toUtf8();
         backtrace.append(frame);
     }
     return backtrace;
 }
contextPop()
void QJSDebuggerAgent::contextPop () virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 458 of file qjsdebuggeragent.cpp.
 {
 }
contextPush()
void QJSDebuggerAgent::contextPush () virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 451 of file qjsdebuggeragent.cpp.
 {
 }
continueExecution()
void QJSDebuggerAgent::continueExecution ()
Definition at line 309 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     d->state = NoState;
     d->continueExec();
 }
exceptionCatch()
void QJSDebuggerAgent::exceptionCatch (qint64 scriptId, const QScriptValue & exception) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 576 of file qjsdebuggeragent.cpp.
 {
     Q_UNUSED(scriptId);
     Q_UNUSED(exception);
 }
exceptionThrow()
void QJSDebuggerAgent::exceptionThrow (qint64 scriptId, const QScriptValue & exception, bool hasHandler) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 559 of file qjsdebuggeragent.cpp.
 {
     Q_UNUSED(scriptId);
     Q_UNUSED(exception);
     Q_UNUSED(hasHandler);
 //    qDebug() << Q_FUNC_INFO << exception.toString() << hasHandler;
 #if 0 //sometimes, we get exceptions that we should just ignore.
     if (!hasHandler && state != StoppedState)
         stopped(true, exception);
 #endif
 }
executeExpression()
JSAgentWatchData QJSDebuggerAgent::executeExpression (const QString & expr)
Definition at line 315 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     SetupExecEnv execEnv(d);
     JSAgentWatchData data = fromScriptValue(expr, engine()->evaluate(expr));
     d->knownObjectIds << data.objectId;
     return data;
 }
expandObjectById()
QList< JSAgentWatchData > QJSDebuggerAgent::expandObjectById (quint64 objectId)
Definition at line 324 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     SetupExecEnv execEnv(d);
     QScriptValue v;
     if (d->knownObjectIds.contains(objectId))
         v = engine()->objectById(objectId);
     QList<JSAgentWatchData> result = expandObject(v);
     d->recordKnownObjects(result);
     return result;
 }
extension()
QVariant QJSDebuggerAgent::extension (Extension extension, const QVariant & argument = QVariant()) virtual
This virtual function can be reimplemented in a QScriptEngineAgent subclass to provide support for extensions.
The optional argument can be provided as input to the extension; the result must be returned in the form of a QVariant. You can call supportsExtension() to check if an extension is supported by the QScriptEngineAgent. By default, no extensions are supported, and this function returns an invalid QVariant.
If you implement the DebuggerInvocationRequest extension, Qt Script will call this function when a debugger statement is encountered in a script. The argument is a QVariantList containing three items: The first item is the scriptId (a qint64), the second item is the line number (an int), and the third item is the column number (an int).
See also
supportsExtension()
Reimplemented from QScriptEngineAgent.
Definition at line 587 of file qjsdebuggeragent.cpp.
 {
     if (extension == QScriptEngineAgent::DebuggerInvocationRequest) {
         d->stopped();
         return QVariant();
     }
     return QScriptEngineAgent::extension(extension, argument);
 }
functionEntry()
void QJSDebuggerAgent::functionEntry (qint64 scriptId) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 465 of file qjsdebuggeragent.cpp.
 {
     d->stepDepth++;
     if (d->coverageEnabled) {
         JSAgentCoverageData rd = {"COVERAGE", QJSDebugService::instance()->m_timer.elapsed(), (int)CoverageFuncEntry,
             scriptId, QString(), QString(), 0, 0, 0, QString()};
         QJSDebugService::instance()->processMessage(rd);
         QJSDebugService::instance()->m_timer.restart();
     }
 }
functionExit()
void QJSDebuggerAgent::functionExit (qint64 scriptId, const QScriptValue & returnValue) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 480 of file qjsdebuggeragent.cpp.
 {
     d->stepDepth--;
     if (d->coverageEnabled) {
         JSAgentCoverageData rd = {"COVERAGE", QJSDebugService::instance()->m_timer.elapsed(), (int)CoverageFuncExit,
             scriptId, QString(), QString(), 0, 0, 0, returnValue.toString()};
         QJSDebugService::instance()->processMessage(rd);
     }
 }
isInitialized()
bool QJSDebuggerAgent::isInitialized () const
Indicates whether the agent got the list of breakpoints.
Definition at line 261 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::addEngine().
 {
     return d->isInitialized;
 }
locals()
QList< JSAgentWatchData > QJSDebuggerAgent::locals ()
Definition at line 337 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::executionStopped().
 {
     SetupExecEnv execEnv(d);
     return d->getLocals(engine()->currentContext());
 }
localsAtFrame()
QList< JSAgentWatchData > QJSDebuggerAgent::localsAtFrame (int frameId)
Definition at line 343 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     SetupExecEnv execEnv(d);
     int deep = 0;
     QScriptContext *ctx = engine()->currentContext();
     while (ctx && deep < frameId) {
         ctx = ctx->parentContext();
         deep++;
     }
     return d->getLocals(ctx);
 }
positionChange()
void QJSDebuggerAgent::positionChange (qint64 scriptId, int lineNumber, int columnNumber) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 494 of file qjsdebuggeragent.cpp.
 {
     d->positionChange(scriptId, lineNumber, columnNumber);
     if (d->coverageEnabled) {
         JSAgentCoverageData rd = {"COVERAGE", QJSDebugService::instance()->m_timer.elapsed(), (int)CoveragePosChange,
             scriptId, QString(), QString(), 0, lineNumber, columnNumber, QString()};
         QJSDebugService::instance()->processMessage(rd);
     }
 }
scriptLoad()
void QJSDebuggerAgent::scriptLoad (qint64 id, const QString & program, const QString & fileName, int baseLineNumber) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 427 of file qjsdebuggeragent.cpp.
 {
     d->filenames.insert(id, fileName);
     if (d->coverageEnabled) {
         JSAgentCoverageData rd = {"COVERAGE", QJSDebugService::instance()->m_timer.elapsed(), (int)CoverageScriptLoad,
             id, program, fileName, baseLineNumber,
             0, 0, QString()};
         QJSDebugService::instance()->processMessage(rd);
     }
 }
scriptUnload()
void QJSDebuggerAgent::scriptUnload (qint64 id) virtual
Reimplemented Function
Reimplemented from QScriptEngineAgent.
Definition at line 443 of file qjsdebuggeragent.cpp.
 {
     d->filenames.remove(id);
 }
setBreakpoints()
void QJSDebuggerAgent::setBreakpoints (const JSAgentBreakpoints & breakpoints)
Definition at line 272 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     d->breakpoints = breakpoints;
     d->fileNameToBreakpoints.clear();
     foreach (const JSAgentBreakpointData &bp, breakpoints)
         d->fileNameToBreakpoints.insertMulti(fileName(QString::fromUtf8(bp.fileUrl)), bp);
     d->isInitialized = true;
 }
setCoverageEnabled()
void QJSDebuggerAgent::setCoverageEnabled (bool enabled)
Definition at line 266 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     d->isInitialized = true;
     d->coverageEnabled = enabled;
 }
setProperty()
void QJSDebuggerAgent::setProperty (qint64 objectId, const QString & property, const QString & value)
Definition at line 409 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     SetupExecEnv execEnv(d);
     if (d->knownObjectIds.contains(objectId)) {
         QScriptValue object = engine()->objectById(objectId);
         if (object.isObject()) {
             QScriptValue result = engine()->evaluate(value);
             object.setProperty(property, result);
         }
     }
 }
setWatchExpressions()
void QJSDebuggerAgent::setWatchExpressions (const QStringList & watchExpressions)
Definition at line 283 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     d->watchExpressions = watchExpressions;
 }
stepInto()
void QJSDebuggerAgent::stepInto ()
Definition at line 295 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     d->stepDepth = 0;
     d->state = SteppingIntoState;
     d->continueExec();
 }
stepOut()
void QJSDebuggerAgent::stepOut ()
Definition at line 302 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     d->stepDepth = 0;
     d->state = SteppingOutState;
     d->continueExec();
 }
stepOver()
void QJSDebuggerAgent::stepOver ()
Definition at line 288 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::messageReceived().
 {
     d->stepDepth = 0;
     d->state = SteppingOverState;
     d->continueExec();
 }
stopped
void QJSDebuggerAgent::stopped (bool becauseOfException, const QString & exception) signal
Referenced by exceptionThrow(), and QJSDebuggerAgentPrivate::positionChange().
supportsExtension()
bool QJSDebuggerAgent::supportsExtension (Extension extension) const virtual
Returns true if the QScriptEngineAgent supports the given extension; otherwise, false is returned.
By default, no extensions are supported.
See also
extension()
Reimplemented from QScriptEngineAgent.
Definition at line 582 of file qjsdebuggeragent.cpp.
 {
     return extension == QScriptEngineAgent::DebuggerInvocationRequest;
 }
watches()
QList< JSAgentWatchData > QJSDebuggerAgent::watches ()
Definition at line 398 of file qjsdebuggeragent.cpp.
Referenced by QJSDebugService::executionStopped().
 {
     SetupExecEnv execEnv(d);
     QList<JSAgentWatchData> watches;
     foreach (const QString &expr, d->watchExpressions)
         watches << fromScriptValue(expr, engine()->evaluate(expr));
     d->recordKnownObjects(watches);
     return watches;
 }
Friends and Related Functions
QJSDebuggerAgentPrivate
friend class QJSDebuggerAgentPrivate friend
Definition at line 221 of file qjsdebuggeragent_p.h.
Properties
d
QJSDebuggerAgentPrivate* QJSDebuggerAgent::d private
Definition at line 222 of file qjsdebuggeragent_p.h.
Referenced by backtrace(), continueExecution(), executeExpression(), expandObjectById(), extension(), functionEntry(), functionExit(), isInitialized(), locals(), localsAtFrame(), positionChange(), scriptLoad(), scriptUnload(), setBreakpoints(), setCoverageEnabled(), setProperty(), setWatchExpressions(), stepInto(), stepOut(), stepOver(), watches(), and ~QJSDebuggerAgent().
The documentation for this class was generated from the following files:
/src/declarative/debugger/qjsdebuggeragent_p.h
/src/declarative/debugger/qjsdebuggeragent.cpp