Qt 4.8: QThreadStorage< T > Class Template Reference
QThreadStorage< T > Class Template Reference
The QThreadStorage class provides per-thread data storage.
#include <qthreadstorage.h>
Public Functions
bool hasLocalData () const
If T is a pointer type, returns true if the calling thread has non-zero data available.
T & localData ()
Returns a reference to the data that was set by the calling thread.
T localData () const
Returns a copy of the data that was set by the calling thread.
QThreadStorage ()
Constructs a new per-thread data storage object.
void setLocalData (T t)
Sets the local data for the calling thread to data.
~QThreadStorage ()
Destroys the per-thread data storage object.
Static Private Functions
static void deleteData (void *x)
Properties
QThreadStorageData d
Detailed Description
template<class T>
class QThreadStorage< T >
The QThreadStorage class provides per-thread data storage.
Note
This class or function is threadsafe.
QThreadStorage is a template class that provides per-thread data storage.
The setLocalData() function stores a single thread-specific value for the calling thread. The data can be accessed later using localData().
The hasLocalData() function allows the programmer to determine if data has previously been set using the setLocalData() function. This is also useful for lazy initializiation.
If T is a pointer type, QThreadStorage takes ownership of the data (which must be created on the heap with new) and deletes it when the thread exits, either normally or via termination.
For example, the following code uses QThreadStorage to store a single cache for each thread that calls the cacheObject() and removeFromCache() functions. The cache is automatically deleted when the calling thread exits.
QThreadStorage<QCache<QString, SomeClass> > caches;
void cacheObject(const QString &key, SomeClass *object)
{
    caches.localData().insert(key, object);
}
void removeFromCache(const QString &key)
{
    if (!caches.hasLocalData())
        return;
    caches.localData().remove(key);
}
Caveats
The QThreadStorage destructor does not delete per-thread data. QThreadStorage only deletes per-thread data when the thread exits or when setLocalData() is called multiple times.
QThreadStorage can be used to store data for the main() thread. QThreadStorage deletes all data set for the main() thread when QApplication is destroyed, regardless of whether or not the main() thread has actually finished.
See also
QThread
Definition at line 132 of file qthreadstorage.h.
Constructors and Destructors
QThreadStorage()
template<class T> QThreadStorage< T >::QThreadStorage () inline
Constructs a new per-thread data storage object.
Definition at line 143 of file qthreadstorage.h.
 : d(deleteData) { }
~QThreadStorage()
template<class T> QThreadStorage< T >::~QThreadStorage () inline
Destroys the per-thread data storage object.
Note: The per-thread data stored is not deleted. Any data left in QThreadStorage is leaked. Make sure that all threads using QThreadStorage have exited before deleting the QThreadStorage.
See also
hasLocalData()
Definition at line 144 of file qthreadstorage.h.
 { }
Functions
deleteData()
template<class T> static void QThreadStorage< T >::deleteData (void * x) inline static private
Definition at line 139 of file qthreadstorage.h.
     { qThreadStorage_deleteData(x, reinterpret_cast<T*>(0)); }
hasLocalData()
template<class T> bool QThreadStorage< T >::hasLocalData () const inline
If T is a pointer type, returns true if the calling thread has non-zero data available.
If T is a value type, returns whether the data has already been constructed by calling setLocalData or localData.
See also
localData()
Definition at line 146 of file qthreadstorage.h.
Referenced by QFontCache::cleanup(), QUuid::createUuid(), and QHttpThreadDelegate::startRequest().
     { return d.get() != 0; }
localData() [1/2]
template<class T> T & QThreadStorage< T >::localData () inline
Returns a reference to the data that was set by the calling thread.
If no data has been set, this will create a default constructed instance of type T.
See also
hasLocalData()
Definition at line 149 of file qthreadstorage.h.
Referenced by QIconvCodec::convertFromUnicode(), QPlatformGLContext::currentContext(), QPlatformGLContextPrivate::setCurrentContext(), QGLShaderStorage::shadersForThread(), sharedNetworkSessionManager(), QHttpThreadDelegate::startRequest(), and QHttpThreadDelegate::startRequestSynchronously().
     { return qThreadStorage_localData(d, reinterpret_cast<T*>(0)); }
localData() [2/2]
template<class T> const T QThreadStorage< T >::localData () const inline
Returns a copy of the data that was set by the calling thread.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
hasLocalData()
Definition at line 151 of file qthreadstorage.h.
     { return qThreadStorage_localData_const(d, reinterpret_cast<T*>(0)); }
setLocalData()
template<class T> void QThreadStorage< T >::setLocalData (T data) inline
Sets the local data for the calling thread to data.
It can be accessed later using the localData() functions.
If T is a pointer type, QThreadStorage takes ownership of the data and deletes it automatically either when the thread exits (either normally or via termination) or when setLocalData() is called again.
See also
localData(), hasLocalData()
Definition at line 154 of file qthreadstorage.h.
Referenced by QFontCache::cleanup(), QUuid::createUuid(), QPlatformGLContextPrivate::setCurrentContext(), sharedNetworkSessionManager(), QHttpThreadDelegate::startRequest(), and QHttpThreadDelegate::startRequestSynchronously().
     { qThreadStorage_setLocalData(d, &t); }
Properties
d
template<class T> QThreadStorageData QThreadStorage< T >::d private
Definition at line 135 of file qthreadstorage.h.
The documentation for this class was generated from the following files:
/src/corelib/thread/qthreadstorage.h
/src/corelib/thread/qthreadstorage.cpp