Qt 4.8: QmlJSDebugger::QDeclarativeViewInspectorPrivate Class Reference
QmlJSDebugger::QDeclarativeViewInspectorPrivate Class Reference
#include <qdeclarativeviewinspector_p.h>
Public Slots
void _q_onStatusChanged (QDeclarativeView::Status status)
void _q_removeFromSelection (QObject *)
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Public Functions
void changeToColorPickerTool ()
void changeToMarqueeSelectTool ()
void changeToSelectTool ()
void changeToSingleSelectTool ()
void changeToZoomTool ()
void clearEditorItems ()
void clearHighlight ()
QList< QGraphicsItem * > filterForSelection (QList< QGraphicsItem *> &itemlist) const
void highlight (const QList< QGraphicsObject *> &item)
void highlight (QGraphicsObject *item)
QDeclarativeViewInspectorPrivate (QDeclarativeViewInspector *)
QList< QGraphicsItem * > selectableItems (const QPoint &pos) const
QList< QGraphicsItem * > selectableItems (const QPointF &scenePos) const
QList< QGraphicsItem * > selectableItems (const QRectF &sceneRect, Qt::ItemSelectionMode selectionMode) const
QList< QGraphicsItem * > selectedItems () const
void setSelectedItems (const QList< QGraphicsItem *> &items)
void setSelectedItemsForTools (const QList< QGraphicsItem *> &items)
void setViewport (QWidget *widget)
~QDeclarativeViewInspectorPrivate ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QDeclarativeViewInspectorPrivate * get (QDeclarativeViewInspector *v)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Public Variables
BoundingRectHighlighter * boundingRectHighlighter
ColorPickerTool * colorPickerTool
QList< QWeakPointer< QGraphicsObject > > currentSelection
LiveLayerItem * manipulatorLayer
QDeclarativeViewInspector * q
LiveSelectionTool * selectionTool
QDeclarativeView * view
QWeakPointer< QWidget > viewport
ZoomTool * zoomTool
Additional Inherited Members
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 62 of file qdeclarativeviewinspector_p.h.
Constructors and Destructors
QDeclarativeViewInspectorPrivate()
QmlJSDebugger::QDeclarativeViewInspectorPrivate::QDeclarativeViewInspectorPrivate (QDeclarativeViewInspector * q)
Definition at line 58 of file qdeclarativeviewinspector.cpp.
                                                                                                :
     q(q)
 {
 }
~QDeclarativeViewInspectorPrivate()
QmlJSDebugger::QDeclarativeViewInspectorPrivate::~QDeclarativeViewInspectorPrivate ()
Definition at line 63 of file qdeclarativeviewinspector.cpp.
 {
 }
Functions
_q_onStatusChanged
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::_q_onStatusChanged (QDeclarativeView::Status status) slot
Definition at line 408 of file qdeclarativeviewinspector.cpp.
Referenced by highlight().
 {
     if (status == QDeclarativeView::Ready)
         q->sendReloaded();
 }
_q_removeFromSelection
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::_q_removeFromSelection (QObject * obj) slot
Definition at line 218 of file qdeclarativeviewinspector.cpp.
Referenced by highlight().
 {
     QList<QGraphicsItem*> items = selectedItems();
     if (QGraphicsItem *item = qobject_cast<QGraphicsObject*>(obj))
         items.removeOne(item);
     setSelectedItems(items);
 }
changeToColorPickerTool()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::changeToColorPickerTool ()
Definition at line 376 of file qdeclarativeviewinspector.cpp.
Referenced by highlight().
 {
     if (q->currentTool() == colorPickerTool)
         return;
     q->currentTool()->clear();
     q->setCurrentTool(colorPickerTool);
     q->currentTool()->clear();
     emit q->colorPickerActivated();
     q->sendCurrentTool(Constants::ColorPickerMode);
 }
changeToMarqueeSelectTool()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::changeToMarqueeSelectTool ()
Definition at line 357 of file qdeclarativeviewinspector.cpp.
Referenced by highlight().
 {
     changeToSelectTool();
     selectionTool->setRubberbandSelectionMode(true);
     emit q->marqueeSelectToolActivated();
     q->sendCurrentTool(Constants::MarqueeSelectionToolMode);
 }
changeToSelectTool()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::changeToSelectTool ()
Definition at line 346 of file qdeclarativeviewinspector.cpp.
 {
     if (q->currentTool() == selectionTool)
         return;
     q->currentTool()->clear();
     q->setCurrentTool(selectionTool);
     q->currentTool()->clear();
     q->currentTool()->updateSelectedItems();
 }
changeToSingleSelectTool()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::changeToSingleSelectTool ()
Definition at line 336 of file qdeclarativeviewinspector.cpp.
Referenced by highlight().
 {
     selectionTool->setRubberbandSelectionMode(false);
     changeToSelectTool();
     emit q->selectToolActivated();
     q->sendCurrentTool(Constants::SelectionToolMode);
 }
changeToZoomTool()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::changeToZoomTool ()
Definition at line 366 of file qdeclarativeviewinspector.cpp.
Referenced by highlight().
 {
     q->currentTool()->clear();
     q->setCurrentTool(zoomTool);
     q->currentTool()->clear();
     emit q->zoomToolActivated();
     q->sendCurrentTool(Constants::ZoomMode);
 }
clearEditorItems()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::clearEditorItems ()
Definition at line 167 of file qdeclarativeviewinspector.cpp.
 {
     clearHighlight();
     setSelectedItems(QList<QGraphicsItem*>());
 }
clearHighlight()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::clearHighlight ()
Definition at line 292 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::hoverMoveEvent().
 {
     boundingRectHighlighter->clear();
 }
filterForSelection()
QList< QGraphicsItem * > QmlJSDebugger::QDeclarativeViewInspectorPrivate::filterForSelection (QList< QGraphicsItem *> & itemlist) const
Definition at line 397 of file qdeclarativeviewinspector.cpp.
 {
     foreach (QGraphicsItem *item, itemlist) {
         if (isEditorItem(item))
             itemlist.removeOne(item);
     }
     return itemlist;
 }
get()
static QDeclarativeViewInspectorPrivate* QmlJSDebugger::QDeclarativeViewInspectorPrivate::get (QDeclarativeViewInspector * v) inline static
Definition at line 112 of file qdeclarativeviewinspector_p.h.
Referenced by QmlJSDebugger::LiveSelectionTool::alreadySelected(), QmlJSDebugger::LiveSingleSelectionManipulator::begin(), QmlJSDebugger::LiveRubberBandSelectionManipulator::begin(), QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered(), QmlJSDebugger::LiveSelectionTool::hoverMoveEvent(), QmlJSDebugger::LiveSelectionTool::mousePressEvent(), QmlJSDebugger::LiveSingleSelectionManipulator::select(), QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), QmlJSDebugger::LiveSelectionTool::wheelEvent(), and QmlJSDebugger::ZoomTool::ZoomTool().
 { return v->d_func(); }
highlight() [1/2]
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::highlight (const QList< QGraphicsObject *> & item)
Definition at line 297 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::contextMenuElementHovered(), highlight(), and QmlJSDebugger::LiveSelectionTool::hoverMoveEvent().
 {
     if (items.isEmpty())
         return;
     QList<QGraphicsObject*> objectList;
     foreach (QGraphicsItem *item, items) {
         QGraphicsItem *child = item;
         if (child) {
             QGraphicsObject *childObject = child->toGraphicsObject();
             if (childObject)
                 objectList << childObject;
         }
     }
     boundingRectHighlighter->highlight(objectList);
 }
highlight() [2/2]
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::highlight (QGraphicsObject * item) inline
Definition at line 98 of file qdeclarativeviewinspector_p.h.
     { highlight(QList<QGraphicsObject*>() << item); }
selectableItems() [1/3]
QList< QGraphicsItem * > QmlJSDebugger::QDeclarativeViewInspectorPrivate::selectableItems (const QPoint & pos) const
Definition at line 323 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::LiveRubberBandSelectionManipulator::begin(), QmlJSDebugger::LiveSelectionTool::hoverMoveEvent(), QmlJSDebugger::LiveSelectionTool::mousePressEvent(), QmlJSDebugger::LiveSingleSelectionManipulator::select(), QmlJSDebugger::LiveRubberBandSelectionManipulator::select(), and QmlJSDebugger::LiveSelectionTool::wheelEvent().
 {
     QList<QGraphicsItem*> itemlist = view->items(pos);
     return filterForSelection(itemlist);
 }
selectableItems() [2/3]
QList< QGraphicsItem * > QmlJSDebugger::QDeclarativeViewInspectorPrivate::selectableItems (const QPointF & scenePos) const
Definition at line 316 of file qdeclarativeviewinspector.cpp.
 {
     QList<QGraphicsItem*> itemlist = view->scene()->items(scenePos);
     return filterForSelection(itemlist);
 }
selectableItems() [3/3]
QList< QGraphicsItem * > QmlJSDebugger::QDeclarativeViewInspectorPrivate::selectableItems (const QRectF & sceneRect, Qt::ItemSelectionMode selectionMode) const
Definition at line 329 of file qdeclarativeviewinspector.cpp.
 {
     QList<QGraphicsItem*> itemlist = view->scene()->items(sceneRect, selectionMode);
     return filterForSelection(itemlist);
 }
selectedItems()
QList< QGraphicsItem * > QmlJSDebugger::QDeclarativeViewInspectorPrivate::selectedItems () const
Definition at line 266 of file qdeclarativeviewinspector.cpp.
Referenced by QmlJSDebugger::LiveSelectionTool::alreadySelected(), and QmlJSDebugger::LiveSingleSelectionManipulator::begin().
 {
     QList<QGraphicsItem *> selection;
     foreach (const QWeakPointer<QGraphicsObject> &selectedObject, currentSelection) {
         if (selectedObject.data())
             selection << selectedObject.data();
     }
     return selection;
 }
setSelectedItems()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::setSelectedItems (const QList< QGraphicsItem *> & items)
Definition at line 251 of file qdeclarativeviewinspector.cpp.
 {
     QList<QWeakPointer<QGraphicsObject> > oldList = currentSelection;
     setSelectedItemsForTools(items);
     if (oldList != currentSelection) {
         QList<QObject*> objectList;
         foreach (const QWeakPointer<QGraphicsObject> &graphicsObject, currentSelection) {
             if (graphicsObject)
                 objectList << graphicsObject.data();
         }
         q->sendCurrentObjects(objectList);
     }
 }
setSelectedItemsForTools()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::setSelectedItemsForTools (const QList< QGraphicsItem *> & items)
Definition at line 226 of file qdeclarativeviewinspector.cpp.
 {
     foreach (const QWeakPointer<QGraphicsObject> &obj, currentSelection) {
         if (QGraphicsItem *item = obj.data()) {
             if (!items.contains(item)) {
                 QObject::disconnect(obj.data(), SIGNAL(destroyed(QObject*)),
                                     this, SLOT(_q_removeFromSelection(QObject*)));
                 currentSelection.removeOne(obj);
             }
         }
     }
     foreach (QGraphicsItem *item, items) {
         if (QGraphicsObject *obj = item->toGraphicsObject()) {
             if (!currentSelection.contains(obj)) {
                 QObject::connect(obj, SIGNAL(destroyed(QObject*)),
                                  this, SLOT(_q_removeFromSelection(QObject*)));
                 currentSelection.append(obj);
             }
         }
     }
     q->currentTool()->updateSelectedItems();
 }
setViewport()
void QmlJSDebugger::QDeclarativeViewInspectorPrivate::setViewport (QWidget * widget)
Definition at line 151 of file qdeclarativeviewinspector.cpp.
 {
     if (viewport.data() == widget)
         return;
     if (viewport)
         viewport.data()->removeEventFilter(q);
     viewport = widget;
     if (viewport) {
         // make sure we get mouse move events
         viewport.data()->setMouseTracking(true);
         viewport.data()->installEventFilter(q);
     }
 }
Properties
boundingRectHighlighter
BoundingRectHighlighter* QmlJSDebugger::QDeclarativeViewInspectorPrivate::boundingRectHighlighter
Definition at line 80 of file qdeclarativeviewinspector_p.h.
colorPickerTool
ColorPickerTool* QmlJSDebugger::QDeclarativeViewInspectorPrivate::colorPickerTool
Definition at line 77 of file qdeclarativeviewinspector_p.h.
currentSelection
QList<QWeakPointer<QGraphicsObject> > QmlJSDebugger::QDeclarativeViewInspectorPrivate::currentSelection
Definition at line 73 of file qdeclarativeviewinspector_p.h.
manipulatorLayer
LiveLayerItem* QmlJSDebugger::QDeclarativeViewInspectorPrivate::manipulatorLayer
Definition at line 78 of file qdeclarativeviewinspector_p.h.
Referenced by QmlJSDebugger::ZoomTool::ZoomTool().
q
QDeclarativeViewInspector* QmlJSDebugger::QDeclarativeViewInspectorPrivate::q
Definition at line 70 of file qdeclarativeviewinspector_p.h.
selectionTool
LiveSelectionTool* QmlJSDebugger::QDeclarativeViewInspectorPrivate::selectionTool
Definition at line 75 of file qdeclarativeviewinspector_p.h.
view
QDeclarativeView* QmlJSDebugger::QDeclarativeViewInspectorPrivate::view
Definition at line 69 of file qdeclarativeviewinspector_p.h.
viewport
QWeakPointer<QWidget> QmlJSDebugger::QDeclarativeViewInspectorPrivate::viewport
Definition at line 71 of file qdeclarativeviewinspector_p.h.
zoomTool
ZoomTool* QmlJSDebugger::QDeclarativeViewInspectorPrivate::zoomTool
Definition at line 76 of file qdeclarativeviewinspector_p.h.
The documentation for this class was generated from the following files:
/src/plugins/qmltooling/qmldbg_inspector/qdeclarativeviewinspector_p.h
/src/plugins/qmltooling/qmldbg_inspector/qdeclarativeviewinspector.cpp