Qt 4.8: QScript::SyntaxChecker Class Reference
QScript::SyntaxChecker Class Reference
#include <qscriptsyntaxchecker_p.h>
Classes
struct Result
Public Types
enum State { Error, Intermediate, Valid }
Public Functions
Result checkSyntax (const QString &code)
SyntaxChecker ()
~SyntaxChecker ()
Protected Functions
bool automatic (QScript::Lexer *lexer, int token) const
void reallocateStack ()
Protected Variables
int stack_size
int * state_stack
int tos
Additional Inherited Members
Protected Types inherited from QScriptGrammar
enum {
EOF_SYMBOL = 0, T_AND = 1, T_AND_AND = 2, T_AND_EQ = 3,
T_AUTOMATIC_SEMICOLON = 62, T_BREAK = 4, T_CASE = 5, T_CATCH = 6,
T_COLON = 7, T_COMMA = 8, T_CONST = 81, T_CONTINUE = 9,
T_DEBUGGER = 82, T_DEFAULT = 10, T_DELETE = 11, T_DIVIDE_ = 12,
T_DIVIDE_EQ = 13, T_DO = 14, T_DOT = 15, T_ELSE = 16,
T_EQ = 17, T_EQ_EQ = 18, T_EQ_EQ_EQ = 19, T_FALSE = 80,
T_FINALLY = 20, T_FOR = 21, T_FUNCTION = 22, T_GE = 23,
T_GT = 24, T_GT_GT = 25, T_GT_GT_EQ = 26, T_GT_GT_GT = 27,
T_GT_GT_GT_EQ = 28, T_IDENTIFIER = 29, T_IF = 30, T_IN = 31,
T_INSTANCEOF = 32, T_LBRACE = 33, T_LBRACKET = 34, T_LE = 35,
T_LPAREN = 36, T_LT = 37, T_LT_LT = 38, T_LT_LT_EQ = 39,
T_MINUS = 40, T_MINUS_EQ = 41, T_MINUS_MINUS = 42, T_NEW = 43,
T_NOT = 44, T_NOT_EQ = 45, T_NOT_EQ_EQ = 46, T_NULL = 78,
T_NUMERIC_LITERAL = 47, T_OR = 48, T_OR_EQ = 49, T_OR_OR = 50,
T_PLUS = 51, T_PLUS_EQ = 52, T_PLUS_PLUS = 53, T_QUESTION = 54,
T_RBRACE = 55, T_RBRACKET = 56, T_REMAINDER = 57, T_REMAINDER_EQ = 58,
T_RESERVED_WORD = 83, T_RETURN = 59, T_RPAREN = 60, T_SEMICOLON = 61,
T_STAR = 63, T_STAR_EQ = 64, T_STRING_LITERAL = 65, T_SWITCH = 66,
T_THIS = 67, T_THROW = 68, T_TILDE = 69, T_TRUE = 79,
T_TRY = 70, T_TYPEOF = 71, T_VAR = 72, T_VOID = 73,
T_WHILE = 74, T_WITH = 75, T_XOR = 76, T_XOR_EQ = 77,
ACCEPT_STATE = 237, RULE_COUNT = 269, STATE_COUNT = 468, TERMINAL_COUNT = 84,
NON_TERMINAL_COUNT = 88, GOTO_INDEX_OFFSET = 468, GOTO_INFO_OFFSET = 1562, GOTO_CHECK_OFFSET = 1562
}
Static Protected Functions inherited from QScriptGrammar
static int nt_action (int state, int nt)
static int t_action (int state, int token)
Static Protected Variables inherited from QScriptGrammar
static const short action_check []
static const short action_default []
static const short action_index []
static const short action_info []
static const short goto_default []
static const short lhs []
static const short rhs []
static const int rule_index []
static const int rule_info []
static const char *const spell []
Detailed Description
Definition at line 48 of file qscriptsyntaxchecker_p.h.
Enumerations
State
enum QScript::SyntaxChecker::State
Enumerator
Error
Intermediate
Valid
Definition at line 51 of file qscriptsyntaxchecker_p.h.
                {
         Error,
         Intermediate,
         Valid,
     };
Constructors and Destructors
SyntaxChecker()
QScript::SyntaxChecker::SyntaxChecker ()
Definition at line 34 of file qscriptsyntaxchecker.cpp.
                             :
     tos(0),
     stack_size(0),
     state_stack(0)
 {
 }
~SyntaxChecker()
QScript::SyntaxChecker::~SyntaxChecker ()
Definition at line 41 of file qscriptsyntaxchecker.cpp.
 {
     if (stack_size) {
         qFree(state_stack);
     }
 }
Functions
automatic()
bool QScript::SyntaxChecker::automatic (QScript::Lexer * lexer, int token) const protected
Definition at line 48 of file qscriptsyntaxchecker.cpp.
Referenced by checkSyntax().
 {
     return token == T_RBRACE || token == 0 || lexer->prevTerminator();
 }
checkSyntax()
SyntaxChecker::Result QScript::SyntaxChecker::checkSyntax (const QString & code)
Definition at line 53 of file qscriptsyntaxchecker.cpp.
Referenced by QScriptEnginePrivate::canEvaluate(), and QScriptEnginePrivate::checkSyntax().
 {
   const int INITIAL_STATE = 0;
   QScript::Lexer lexer (/*engine=*/ 0);
   lexer.setCode(code, /*lineNo*/ 1);
   int yytoken = -1;
   int saved_yytoken = -1;
   QString error_message;
   int error_lineno = -1;
   int error_column = -1;
   State checkerState = Valid;
   reallocateStack();
   tos = 0;
   state_stack[++tos] = INITIAL_STATE;
   while (true)
     {
       const int state = state_stack [tos];
       if (yytoken == -1 && - TERMINAL_COUNT != action_index [state])
         {
           if (saved_yytoken == -1)
             yytoken = lexer.lex();
           else
             {
               yytoken = saved_yytoken;
               saved_yytoken = -1;
             }
         }
       int act = t_action (state, yytoken);
       if (act == ACCEPT_STATE) {
           if (lexer.error() == QScript::Lexer::UnclosedComment)
               checkerState = Intermediate;
           else
               checkerState = Valid;
           break;
       } else if (act > 0) {
           if (++tos == stack_size)
             reallocateStack();
           state_stack [tos] = act;
           yytoken = -1;
         }
       else if (act < 0)
         {
           int r = - act - 1;
           tos -= rhs [r];
           act = state_stack [tos++];
           if ((r == Q_SCRIPT_REGEXPLITERAL_RULE1)
               || (r == Q_SCRIPT_REGEXPLITERAL_RULE2)) {
               // Skip the rest of the RegExp literal
               bool rx = lexer.scanRegExp();
               if (!rx) {
                   checkerState = Intermediate;
                   break;
               }
           }
           state_stack [tos] = nt_action (act, lhs [r] - TERMINAL_COUNT);
         }
       else
         {
           if (saved_yytoken == -1 && automatic (&lexer, yytoken) && t_action (state, T_AUTOMATIC_SEMICOLON) > 0)
             {
               saved_yytoken = yytoken;
               yytoken = T_SEMICOLON;
               continue;
             }
           else if ((state == INITIAL_STATE) && (yytoken == 0)) {
               // accept empty input
               yytoken = T_SEMICOLON;
               continue;
           }
           int ers = state;
           int shifts = 0;
           int reduces = 0;
           int expected_tokens [3];
           for (int tk = 0; tk < TERMINAL_COUNT; ++tk)
             {
               int k = t_action (ers, tk);
               if (! k)
                 continue;
               else if (k < 0)
                 ++reduces;
               else if (spell [tk])
                 {
                   if (shifts < 3)
                     expected_tokens [shifts] = tk;
                   ++shifts;
                 }
             }
           error_message.clear ();
           if (shifts && shifts < 3)
             {
               bool first = true;
               for (int s = 0; s < shifts; ++s)
                 {
                   if (first)
                     error_message += QLatin1String ("Expected ");
                   else
                     error_message += QLatin1String (", ");
                   first = false;
                   error_message += QLatin1Char('`');
                   error_message += QLatin1String (spell [expected_tokens [s]]);
                   error_message += QLatin1Char('\'');
                 }
             }
           if (error_message.isEmpty())
               error_message = lexer.errorMessage();
           error_lineno = lexer.startLineNo();
           error_column = lexer.startColumnNo();
           checkerState = Error;
           break;
         }
     }
   if (checkerState == Error) {
       if (lexer.error() == QScript::Lexer::UnclosedComment)
           checkerState = Intermediate;
       else if (yytoken == 0)
           checkerState = Intermediate;
   }
   return Result(checkerState, error_lineno, error_column, error_message);
 }
reallocateStack()
void QScript::SyntaxChecker::reallocateStack () inline protected
Definition at line 82 of file qscriptsyntaxchecker_p.h.
Referenced by checkSyntax().
 {
     if (! stack_size)
         stack_size = 128;
     else
         stack_size <<= 1;
     state_stack = reinterpret_cast<int*> (qRealloc(state_stack, stack_size * sizeof(int)));
 }
Properties
stack_size
int QScript::SyntaxChecker::stack_size protected
Definition at line 78 of file qscriptsyntaxchecker_p.h.
Referenced by checkSyntax(), reallocateStack(), and ~SyntaxChecker().
state_stack
int* QScript::SyntaxChecker::state_stack protected
Definition at line 79 of file qscriptsyntaxchecker_p.h.
Referenced by checkSyntax(), reallocateStack(), and ~SyntaxChecker().
tos
int QScript::SyntaxChecker::tos protected
Definition at line 77 of file qscriptsyntaxchecker_p.h.
Referenced by checkSyntax().
The documentation for this class was generated from the following files:
/src/script/parser/qscriptsyntaxchecker_p.h
/src/script/parser/qscriptsyntaxchecker.cpp