Qt 4.8: QTreeModel Class Reference
QTreeModel Class Reference
#include <qtreewidget_p.h>
Classes
struct SkipSorting
Public Functions
void clear ()
Removes all items in the model.
int columnCount (const QModelIndex &parent=QModelIndex()) const
Returns the number of columns in the item referred to by the given index.
QModelIndex createIndexFromItem (int row, int col, QTreeWidgetItem *item) const
QVariant data (const QModelIndex &index, int role=Qt::DisplayRole) const
Returns the data corresponding to the given model index and role.
bool dropMimeData (const QMimeData *data, Qt::DropAction action, int row, int column, const QModelIndex &parent)
Handles the data supplied by a drag and drop operation that ended with the given action.
void ensureSorted (int column, Qt::SortOrder order, int start, int end, const QModelIndex &parent)
Qt::ItemFlags flags (const QModelIndex &index) const
Returns the flags for the item referred to the given index.
bool hasChildren (const QModelIndex &parent) const
Returns true if parent has any children; otherwise returns false.
QVariant headerData (int section, Qt::Orientation orientation, int role) const
Returns the header data corresponding to the given header section, orientation and data role.
QModelIndex index (const QTreeWidgetItem *item, int column) const
Returns the model index that refers to the tree view item and column.
QModelIndex index (int row, int column, const QModelIndex &parent) const
Returns the model index with the given row, column and parent.
bool insertColumns (int column, int count, const QModelIndex &)
bool insertRows (int row, int count, const QModelIndex &)
QMimeData * internalMimeData () const
QTreeWidgetItem * item (const QModelIndex &index) const
Returns the tree view item corresponding to the index given.
void itemChanged (QTreeWidgetItem *item)
QMap< int, QVariant > itemData (const QModelIndex &index) const
Returns a map with values for all predefined roles in the model for the item at the given index.
QMimeData * mimeData (const QModelIndexList &indexes) const
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of model indexes.
QModelIndex parent (const QModelIndex &child) const
Returns the parent model index of the index given as the child.
QTreeModel (int columns=0, QTreeWidget *parent=0)
Constructs a tree model with a parent object and the given number of columns.
bool removeRows (int row, int count, const QModelIndex &parent=QModelIndex())
int rowCount (const QModelIndex &parent) const
Returns the number of rows in the parent model index.
void setColumnCount (int columns)
Sets the number of columns in the tree model.
bool setData (const QModelIndex &index, const QVariant &value, int role)
Sets the data for the item specified by the index and role to that referred to by the value.
bool setHeaderData (int section, Qt::Orientation orientation, const QVariant &value, int role)
Sets the header data for the item specified by the header section, orientation and data role to the given value.
void sort (int column, Qt::SortOrder order)
Sorts the entire tree in the model in the given order, by the values in the given column.
Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this model.
QTreeWidget * view () const
~QTreeModel ()
Destroys this tree model.
Public Functions inherited from QAbstractItemModel
virtual QModelIndex buddy (const QModelIndex &index) const
Returns a model index for the buddy of the item represented by index.
virtual bool canFetchMore (const QModelIndex &parent) const
Returns true if there is more data available for parent; otherwise returns false.
virtual void fetchMore (const QModelIndex &parent)
Fetches any available data for the items with the parent specified by the parent index.
bool hasIndex (int row, int column, const QModelIndex &parent=QModelIndex()) const
Returns true if the model returns a valid QModelIndex for row and column with parent, otherwise returns false.
bool insertColumn (int column, const QModelIndex &parent=QModelIndex())
Inserts a single column before the given column in the child items of the parent specified.
bool insertRow (int row, const QModelIndex &parent=QModelIndex())
Inserts a single row before the given row in the child items of the parent specified.
virtual QModelIndexList match (const QModelIndex &start, int role, const QVariant &value, int hits=1, Qt::MatchFlags flags=Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)) const
Returns a list of indexes for the items in the column of the start index where data stored under the given role matches the specified value.
QAbstractItemModel (QObject *parent=0)
Constructs an abstract item model with the given parent.
bool removeColumn (int column, const QModelIndex &parent=QModelIndex())
Removes the given column from the child items of the parent specified.
virtual bool removeColumns (int column, int count, const QModelIndex &parent=QModelIndex())
On models that support this, removes count columns starting with the given column under parent parent from the model.
bool removeRow (int row, const QModelIndex &parent=QModelIndex())
Removes the given row from the child items of the parent specified.
const QHash< int, QByteArray > & roleNames () const
Returns the model's role names.
virtual bool setItemData (const QModelIndex &index, const QMap< int, QVariant > &roles)
Sets the role data for the item at index to the associated value in roles, for every Qt::ItemDataRole.
void setSupportedDragActions (Qt::DropActions)
Sets the supported drag actions for the items in the model.
QModelIndex sibling (int row, int column, const QModelIndex &idx) const
Returns the sibling at row and column for the item at index, or an invalid QModelIndex if there is no sibling at that location.
virtual QSize span (const QModelIndex &index) const
Returns the row and column span of the item represented by index.
Qt::DropActions supportedDragActions () const
Returns the actions supported by the data in this model.
virtual ~QAbstractItemModel ()
Destroys the abstract item model.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static bool itemGreaterThan (const QPair< QTreeWidgetItem *, int > &left, const QPair< QTreeWidgetItem *, int > &right)
Returns true if the value of the left item is greater than the value of the right item.
static bool itemLessThan (const QPair< QTreeWidgetItem *, int > &left, const QPair< QTreeWidgetItem *, int > &right)
Returns true if the value of the left item is less than the value of the right item.
static QList< QTreeWidgetItem * >::iterator sortedInsertionIterator (const QList< QTreeWidgetItem *>::iterator &begin, const QList< QTreeWidgetItem *>::iterator &end, Qt::SortOrder order, QTreeWidgetItem *item)
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
void beginInsertItems (QTreeWidgetItem *parent, int row, int count)
void beginRemoveItems (QTreeWidgetItem *parent, int row, int count)
void emitDataChanged (QTreeWidgetItem *item, int column)
Emits the dataChanged() signal for the given item.
void endInsertItems ()
void endRemoveItems ()
QTreeModel (QTreeModelPrivate &, QTreeWidget *parent=0)
void sortItems (QList< QTreeWidgetItem *> *items, int column, Qt::SortOrder order)
void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QAbstractItemModel
void beginInsertColumns (const QModelIndex &parent, int first, int last)
Begins a column insertion operation.
void beginInsertRows (const QModelIndex &parent, int first, int last)
Begins a row insertion operation.
bool beginMoveColumns (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationColumn)
Begins a column move operation.
bool beginMoveRows (const QModelIndex &sourceParent, int sourceFirst, int sourceLast, const QModelIndex &destinationParent, int destinationRow)
Begins a row move operation.
void beginRemoveColumns (const QModelIndex &parent, int first, int last)
Begins a column removal operation.
void beginRemoveRows (const QModelIndex &parent, int first, int last)
Begins a row removal operation.
void beginResetModel ()
Begins a model reset operation.
void changePersistentIndex (const QModelIndex &from, const QModelIndex &to)
Changes the QPersistentModelIndex that is equal to the given from model index to the given to model index.
void changePersistentIndexList (const QModelIndexList &from, const QModelIndexList &to)
Changes the QPersistentModelIndexes that is equal to the indexes in the given from model index list to the given to model index list.
QModelIndex createIndex (int row, int column, void *data=0) const
Creates a model index for the given row and column with the internal pointer ptr.
QModelIndex createIndex (int row, int column, int id) const
Use QModelIndex QAbstractItemModel::createIndex(int row, int column, quint32 id) instead.
QModelIndex createIndex (int row, int column, quint32 id) const
Creates a model index for the given row and column with the internal identifier, id.
bool decodeData (int row, int column, const QModelIndex &parent, QDataStream &stream)
void encodeData (const QModelIndexList &indexes, QDataStream &stream) const
void endInsertColumns ()
Ends a column insertion operation.
void endInsertRows ()
Ends a row insertion operation.
void endMoveColumns ()
Ends a column move operation.
void endMoveRows ()
Ends a row move operation.
void endRemoveColumns ()
Ends a column removal operation.
void endRemoveRows ()
Ends a row removal operation.
void endResetModel ()
Completes a model reset operation.
QModelIndexList persistentIndexList () const
Returns the list of indexes stored as persistent indexes in the model.
QAbstractItemModel (QAbstractItemModelPrivate &dd, QObject *parent=0)
void reset ()
Resets the model to its original state in any attached views.
void setRoleNames (const QHash< int, QByteArray > &roleNames)
Sets the model's role names to roleNames.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Private Functions
bool executePendingSort () const
bool isChanging () const
Properties
QModelIndexList cachedIndexes
QTreeWidgetItem * headerItem
QList< QTreeWidgetItemIterator * > iterators
QTreeWidgetItem * rootItem
bool skipPendingSort
QBasicTimer sortPendingTimer
Friends
class QTreeWidget
class QTreeWidgetItem
class QTreeWidgetItemIterator
class QTreeWidgetItemIteratorPrivate
class QTreeWidgetItemPrivate
class QTreeWidgetPrivate
struct SkipSorting
Additional Inherited Members
Public Slots inherited from QAbstractItemModel
virtual void revert ()
Lets the model know that it should discard cached information.
virtual bool submit ()
Lets the model know that it should submit cached information to permanent storage.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QAbstractItemModel
void columnsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are inserted into the model.
void columnsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationColumn)
This signal is emitted just before columns are moved within the model.
void columnsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before columns are removed from the model.
void columnsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been inserted into the model.
void columnsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int column)
This signal is emitted after columns have been moved within the model.
void columnsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after columns have been removed from the model.
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
This signal is emitted whenever the data in an existing item changes.
void headerDataChanged (Qt::Orientation orientation, int first, int last)
This signal is emitted whenever a header is changed.
void layoutAboutToBeChanged ()
This signal is emitted just before the layout of a model is changed.
void layoutChanged ()
This signal is emitted whenever the layout of items exposed by the model has changed; for example, when the model has been sorted.
void modelAboutToBeReset ()
This signal is emitted when reset() is called, before the model's internal state (e.
void modelReset ()
This signal is emitted when reset() is called, after the model's internal state (e.
void rowsAboutToBeInserted (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are inserted into the model.
void rowsAboutToBeMoved (const QModelIndex &sourceParent, int sourceStart, int sourceEnd, const QModelIndex &destinationParent, int destinationRow)
This signal is emitted just before rows are moved within the model.
void rowsAboutToBeRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted just before rows are removed from the model.
void rowsInserted (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been inserted into the model.
void rowsMoved (const QModelIndex &parent, int start, int end, const QModelIndex &destination, int row)
This signal is emitted after rows have been moved within the model.
void rowsRemoved (const QModelIndex &parent, int first, int last)
This signal is emitted after rows have been removed from the model.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Slots inherited from QAbstractItemModel
void resetInternalData ()
This slot is called just after the internal data of a model is cleared while it is being reset.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 71 of file qtreewidget_p.h.
Constructors and Destructors
QTreeModel() [1/2]
QTreeModel::QTreeModel (int columns = 0, QTreeWidget * parent = 0) explicit
Constructs a tree model with a parent object and the given number of columns.
Warning
This function is not part of the public interface.
Definition at line 124 of file qtreewidget.cpp.
Referenced by createIndexFromItem().
     : QAbstractItemModel(parent), rootItem(new QTreeWidgetItem),
       headerItem(new QTreeWidgetItem), skipPendingSort(false)
 {
     rootItem->view = parent;
     rootItem->itemFlags = Qt::ItemIsDropEnabled;
     headerItem->view = parent;
     setColumnCount(columns);
 }
~QTreeModel()
QTreeModel::~QTreeModel ()
Destroys this tree model.
Warning
This function is not part of the public interface.
Definition at line 157 of file qtreewidget.cpp.
 {
     clear();
     delete headerItem;
     rootItem->view = 0;
     delete rootItem;
 }
QTreeModel() [2/2]
QTreeModel::QTreeModel (QTreeModelPrivate & dd, QTreeWidget * parent = 0) protected
Warning
This function is not part of the public interface.
Definition at line 139 of file qtreewidget.cpp.
     : QAbstractItemModel(dd, parent), rootItem(new QTreeWidgetItem),
       headerItem(new QTreeWidgetItem), skipPendingSort(false)
 {
     rootItem->view = parent;
     rootItem->itemFlags = Qt::ItemIsDropEnabled;
     headerItem->view = parent;
 }
Functions
beginInsertItems()
void QTreeModel::beginInsertItems (QTreeWidgetItem * parent, int row, int count) protected
Definition at line 862 of file qtreewidget.cpp.
Referenced by createIndexFromItem(), and QTreeWidgetItem::insertChildren().
 {
     QModelIndex par = index(parent, 0);
     beginInsertRows(par, row, row + count - 1);
 }
beginRemoveItems()
void QTreeModel::beginRemoveItems (QTreeWidgetItem * parent, int row, int count) protected
Definition at line 873 of file qtreewidget.cpp.
Referenced by createIndexFromItem(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::takeChildren(), and QTreeWidgetItem::~QTreeWidgetItem().
 {
     Q_ASSERT(row >= 0);
     Q_ASSERT(count > 0);
     beginRemoveRows(index(parent, 0), row, row + count - 1);
     if (!parent)
         parent = rootItem;
     // now update the iterators
     for (int i = 0; i < iterators.count(); ++i) {
         for (int j = 0; j < count; j++) {
             QTreeWidgetItem *c = parent->child(row + j);
             iterators[i]->d_func()->ensureValidIterator(c);
         }
     }
 }
clear()
void QTreeModel::clear ()
Removes all items in the model.
Warning
This function is not part of the public interface.
Definition at line 174 of file qtreewidget.cpp.
Referenced by view(), and ~QTreeModel().
 {
     SkipSorting skipSorting(this);
     for (int i = 0; i < rootItem->childCount(); ++i) {
         QTreeWidgetItem *item = rootItem->children.at(i);
         item->par = 0;
         item->view = 0;
         delete item;
     }
     rootItem->children.clear();
     sortPendingTimer.stop();
     reset();
 }
columnCount()
int QTreeModel::columnCount (const QModelIndex & index = QModelIndex()) const virtual
Returns the number of columns in the item referred to by the given index.
Warning
This function is not part of the public interface. Reimplemented Function
Implements QAbstractItemModel.
Definition at line 363 of file qtreewidget.cpp.
Referenced by emitDataChanged(), ensureSorted(), index(), insertColumns(), setColumnCount(), setHeaderData(), sort(), sortItems(), and view().
 {
     Q_UNUSED(index);
     if (!headerItem)
         return 0;
     return headerItem->columnCount();
 }
createIndexFromItem()
QModelIndex QTreeModel::createIndexFromItem (int row, int col, QTreeWidgetItem * item) const inline
Definition at line 138 of file qtreewidget_p.h.
     { return createIndex(row, col, item); }
data()
QVariant QTreeModel::data (const QModelIndex & index, int role = Qt::DisplayRole) const virtual
Returns the data corresponding to the given model index and role.
Warning
This function is not part of the public interface. Reimplemented Function
Implements QAbstractItemModel.
Definition at line 401 of file qtreewidget.cpp.
Referenced by view().
 {
     if (!index.isValid())
         return QVariant();
     QTreeWidgetItem *itm = item(index);
     if (itm)
         return itm->data(index.column(), role);
     return QVariant();
 }
dropMimeData()
bool QTreeModel::dropMimeData (const QMimeData * data, Qt::DropAction action, int row, int column, const QModelIndex & parent) virtual
Handles the data supplied by a drag and drop operation that ended with the given action.
Returns true if the data and action can be handled by the model; otherwise returns false.
The specified row, column and parent indicate the location of an item in the model where the operation ended. It is the responsibility of the model to complete the action at the correct location.
For instance, a drop action on an item in a QTreeView can result in new items either being inserted as children of the item specified by row, column, and parent, or as siblings of the item.
When row and column are -1 it means that the dropped data should be considered as dropped directly on parent. Usually this will mean appending the data as child items of parent. If row and column are greater than or equal zero, it means that the drop occurred just before the specified row and column in the specified parent.
See also
supportedDropActions(), {Using drag and drop with item views}
Reimplemented from QAbstractItemModel.
Definition at line 800 of file qtreewidget.cpp.
Referenced by view().
 {
     if (row == -1 && column == -1)
         row = rowCount(parent); // append
     return view()->dropMimeData(item(parent), row, data, action);
 }
emitDataChanged()
void QTreeModel::emitDataChanged (QTreeWidgetItem * item, int column) protected
Emits the dataChanged() signal for the given item.
Warning
This function is not part of the public interface.
if column is -1 then all columns have changed
Definition at line 836 of file qtreewidget.cpp.
Referenced by createIndexFromItem(), and QTreeWidgetItem::setData().
 {
     if (signalsBlocked())
         return;
     if (headerItem == item && column < item->columnCount()) {
         if (column == -1)
             emit headerDataChanged(Qt::Horizontal, 0, columnCount() - 1);
         else
             emit headerDataChanged(Qt::Horizontal, column, column);
         return;
     }
     SkipSorting skipSorting(this); //This is a little bit wrong, but not doing it would kill performence
     QModelIndex bottomRight, topLeft;
     if (column == -1) {
         topLeft = index(item, 0);
         bottomRight = createIndex(topLeft.row(), columnCount() - 1, item);
     } else {
         topLeft = index(item, column);
         bottomRight = topLeft;
     }
     emit dataChanged(topLeft, bottomRight);
 }
endInsertItems()
void QTreeModel::endInsertItems () protected
Definition at line 868 of file qtreewidget.cpp.
Referenced by createIndexFromItem(), and QTreeWidgetItem::insertChildren().
 {
     endInsertRows();
 }
endRemoveItems()
void QTreeModel::endRemoveItems () protected
Definition at line 889 of file qtreewidget.cpp.
Referenced by createIndexFromItem(), QTreeWidgetItem::takeChildren(), and QTreeWidgetItem::~QTreeWidgetItem().
 {
     endRemoveRows();
 }
ensureSorted()
void QTreeModel::ensureSorted (int column, Qt::SortOrder order, int start, int end, const QModelIndex & parent)
Warning
This function is not part of the public interface.
Definition at line 641 of file qtreewidget.cpp.
Referenced by view().
 {
     if (isChanging())
         return;
     sortPendingTimer.stop();
     if (column < 0 || column >= columnCount())
         return;
     SkipSorting skipSorting(this);
     QTreeWidgetItem *itm = item(parent);
     if (!itm)
         itm = rootItem;
     QList<QTreeWidgetItem*> lst = itm->children;
     int count = end - start + 1;
     QVector < QPair<QTreeWidgetItem*,int> > sorting(count);
     for (int i = 0; i < count; ++i) {
         sorting[i].first = lst.at(start + i);
         sorting[i].second = start + i;
     }
     LessThan compare = (order == Qt::AscendingOrder ? &itemLessThan : &itemGreaterThan);
     qStableSort(sorting.begin(), sorting.end(), compare);
     QModelIndexList oldPersistentIndexes;
     QModelIndexList newPersistentIndexes;
     QList<QTreeWidgetItem*>::iterator lit = lst.begin();
     bool changed = false;
     for (int i = 0; i < count; ++i) {
         int oldRow = sorting.at(i).second;
         QTreeWidgetItem *item = lst.takeAt(oldRow);
         lit = sortedInsertionIterator(lit, lst.end(), order, item);
         int newRow = qMax(lit - lst.begin(), 0);
         if ((newRow < oldRow) && !(*item < *lst.at(oldRow - 1)) && !(*lst.at(oldRow - 1) < *item ))
             newRow = oldRow;
         lit = lst.insert(lit, item);
         if (newRow != oldRow) {
             // we are going to change the persistent indexes, so we need to prepare
             if (!changed) { // this will only happen once
                 changed = true;
                 emit layoutAboutToBeChanged(); // the selection model needs to know
                 oldPersistentIndexes = persistentIndexList();
                 newPersistentIndexes = oldPersistentIndexes;
             }
             for (int j = i + 1; j < count; ++j) {
                 int otherRow = sorting.at(j).second;
                 if (oldRow < otherRow && newRow >= otherRow)
                     --sorting[j].second;
                 else if (oldRow > otherRow && newRow <= otherRow)
                     ++sorting[j].second;
             }
             for (int k = 0; k < newPersistentIndexes.count(); ++k) {
                 QModelIndex pi = newPersistentIndexes.at(k);
                 if (pi.parent() != parent)
                     continue;
                 int oldPersistentRow = pi.row();
                 int newPersistentRow = oldPersistentRow;
                 if (oldPersistentRow == oldRow)
                     newPersistentRow = newRow;
                 else if (oldRow < oldPersistentRow && newRow >= oldPersistentRow)
                     newPersistentRow = oldPersistentRow - 1;
                 else if (oldRow > oldPersistentRow && newRow <= oldPersistentRow)
                     newPersistentRow = oldPersistentRow + 1;
                 if (newPersistentRow != oldPersistentRow)
                     newPersistentIndexes[k] = createIndex(newPersistentRow,
                                                           pi.column(), pi.internalPointer());
             }
         }
     }
     if (changed) {
         itm->children = lst;
         changePersistentIndexList(oldPersistentIndexes, newPersistentIndexes);
         emit layoutChanged();
     }
 }
executePendingSort()
bool QTreeModel::executePendingSort () const inline private
Definition at line 203 of file qtreewidget_p.h.
Referenced by index(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::takeChildren(), and timerEvent().
 {
     if (!skipPendingSort && sortPendingTimer.isActive() && !isChanging()) {
         sortPendingTimer.stop();
         int column = view()->header()->sortIndicatorSection();
         Qt::SortOrder order = view()->header()->sortIndicatorOrder();
         QTreeModel *that = const_cast<QTreeModel*>(this);
         that->sort(column, order);
         return true;
     }
     return false;
 }
flags()
Qt::ItemFlags QTreeModel::flags (const QModelIndex & index) const virtual
Returns the flags for the item referred to the given index.
Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 607 of file qtreewidget.cpp.
Referenced by view().
 {
     if (!index.isValid())
         return rootItem->flags();
     QTreeWidgetItem *itm = item(index);
     Q_ASSERT(itm);
     return itm->flags();
 }
hasChildren()
bool QTreeModel::hasChildren (const QModelIndex & parent) const virtual
Returns true if parent has any children; otherwise returns false.
Use rowCount() on the parent to find out the number of children.
See also
parent() index()
Reimplemented from QAbstractItemModel.
Definition at line 371 of file qtreewidget.cpp.
Referenced by view().
 {
     if (!parent.isValid())
         return (rootItem->childCount() > 0);
     QTreeWidgetItem *itm = item(parent);
     if (!itm)
         return false;
     switch (itm->d->policy) {
     case QTreeWidgetItem::ShowIndicator:
         return true;
     case QTreeWidgetItem::DontShowIndicator:
         return false;
     case QTreeWidgetItem::DontShowIndicatorWhenChildless:
         return (itm->childCount() > 0);
     }
     return false;
 }
headerData()
QVariant QTreeModel::headerData (int section, Qt::Orientation orientation, int role) const virtual
Returns the header data corresponding to the given header section, orientation and data role.
Warning
This function is not part of the public interface. Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 562 of file qtreewidget.cpp.
Referenced by view().
 {
     if (orientation != Qt::Horizontal)
         return QVariant();
     if (headerItem)
         return headerItem->data(section, role);
     if (role == Qt::DisplayRole)
         return QString::number(section + 1);
     return QVariant();
 }
index() [1/2]
QModelIndex QTreeModel::index (const QTreeWidgetItem * item, int column) const
Returns the model index that refers to the tree view item and column.
Warning
This function is not part of the public interface.
Definition at line 253 of file qtreewidget.cpp.
Referenced by beginInsertItems(), beginRemoveItems(), emitDataChanged(), QTreeWidgetPrivate::item(), itemChanged(), parent(), and view().
 {
     executePendingSort();
     if (!item || (item == rootItem))
         return QModelIndex();
     const QTreeWidgetItem *par = item->parent();
     QTreeWidgetItem *itm = const_cast<QTreeWidgetItem*>(item);
     if (!par)
         par = rootItem;
     int row;
     int guess = item->d->rowGuess;
     if (guess >= 0
         && par->children.count() > guess
         && par->children.at(guess) == itm) {
         row = guess;
     } else {
         row = par->children.lastIndexOf(itm);
         itm->d->rowGuess = row;
     }
     return createIndex(row, column, itm);
 }
index() [2/2]
QModelIndex QTreeModel::index (int row, int column, const QModelIndex & parent) const virtual
Returns the model index with the given row, column and parent.
Warning
This function is not part of the public interface. Reimplemented Function
Implements QAbstractItemModel.
Definition at line 287 of file qtreewidget.cpp.
 {
     executePendingSort();
     int c = columnCount(parent);
     if (row < 0 || column < 0 || column >= c)
         return QModelIndex();
     QTreeWidgetItem *parentItem = parent.isValid() ? item(parent) : rootItem;
     if (parentItem && row < parentItem->childCount()) {
         QTreeWidgetItem *itm = parentItem->child(row);
         if (itm)
             return createIndex(row, column, itm);
         return QModelIndex();
     }
     return QModelIndex();
 }
insertColumns()
bool QTreeModel::insertColumns (int column, int count, const QModelIndex & parent) virtual
Warning
This function is not part of the public interface. Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 491 of file qtreewidget.cpp.
Referenced by view().
 {
     SkipSorting skipSorting(this);
     if (count < 1 || column < 0 || column > columnCount(parent) || parent.column() > 0 || !headerItem)
         return false;
     beginInsertColumns(parent, column, column + count - 1);
     int oldCount = columnCount(parent);
     column = qBound(0, column, oldCount);
     headerItem->values.resize(oldCount + count);
     for (int i = oldCount; i < oldCount + count; ++i) {
         headerItem->values[i].append(QWidgetItemData(Qt::DisplayRole, QString::number(i + 1)));
         headerItem->d->display.append(QString::number(i + 1));
     }
     QStack<QTreeWidgetItem*> itemstack;
     itemstack.push(0);
     while (!itemstack.isEmpty()) {
         QTreeWidgetItem *par = itemstack.pop();
         QList<QTreeWidgetItem*> children = par ? par->children : rootItem->children;
         for (int row = 0; row < children.count(); ++row) {
             QTreeWidgetItem *child = children.at(row);
             if (child->children.count())
                 itemstack.push(child);
             child->values.insert(column, count, QVector<QWidgetItemData>());
         }
     }
     endInsertColumns();
     return true;
 }
insertRows()
bool QTreeModel::insertRows (int row, int count, const QModelIndex & parent) virtual
Warning
This function is not part of the public interface. Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 465 of file qtreewidget.cpp.
Referenced by view().
 {
     SkipSorting skipSorting(this);
     if (count < 1 || row < 0 || row > rowCount(parent) || parent.column() > 0)
         return false;
     beginInsertRows(parent, row, row + count - 1);
     QTreeWidgetItem *par = item(parent);
     while (count > 0) {
         QTreeWidgetItem *item = new QTreeWidgetItem();
         item->view = view();
         item->par = par;
         if (par)
             par->children.insert(row++, item);
         else
             rootItem->children.insert(row++, item);
         --count;
     }
     endInsertRows();
     return true;
 }
internalMimeData()
QMimeData * QTreeModel::internalMimeData () const
Definition at line 779 of file qtreewidget.cpp.
Referenced by view().
 {
     return QAbstractItemModel::mimeData(cachedIndexes);
 }
isChanging()
bool QTreeModel::isChanging () const private
Definition at line 821 of file qtreewidget.cpp.
Referenced by ensureSorted(), executePendingSort(), QTreeWidgetItem::sortChildren(), and sortItems().
 {
     Q_D(const QTreeModel);
     return !d->changes.isEmpty();
 }
item()
QTreeWidgetItem * QTreeModel::item (const QModelIndex & index) const
Returns the tree view item corresponding to the index given.
Warning
This function is not part of the public interface.
See also
QModelIndex
Definition at line 236 of file qtreewidget.cpp.
Referenced by QTreeWidgetPrivate::_q_selectionChanged(), clear(), data(), dropMimeData(), emitDataChanged(), ensureSorted(), flags(), hasChildren(), index(), insertRows(), itemData(), mimeData(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), QTreeWidgetItemPrivate::QTreeWidgetItemPrivate(), removeRows(), rowCount(), setData(), sortItems(), and view().
 {
     if (!index.isValid())
         return 0;
     return static_cast<QTreeWidgetItem*>(index.internalPointer());
 }
itemChanged()
void QTreeModel::itemChanged (QTreeWidgetItem * item)
Definition at line 813 of file qtreewidget.cpp.
Referenced by view().
 {
     SkipSorting skipSorting(this); //this is kind of wrong, but not doing this would kill performence
     QModelIndex left = index(item, 0);
     QModelIndex right = index(item, item->columnCount() - 1);
     emit dataChanged(left, right);
 }
itemData()
QMap< int, QVariant > QTreeModel::itemData (const QModelIndex & index) const virtual
Returns a map with values for all predefined roles in the model for the item at the given index.
Reimplement this function if you want to extend the default behavior of this function to include custom roles in the map.
See also
Qt::ItemDataRole, data()
Reimplemented from QAbstractItemModel.
Definition at line 436 of file qtreewidget.cpp.
Referenced by view().
 {
     QMap<int, QVariant> roles;
     QTreeWidgetItem *itm = item(index);
     if (itm) {
         int column = index.column();
         if (column < itm->values.count()) {
             for (int i = 0; i < itm->values.at(column).count(); ++i) {
                 roles.insert(itm->values.at(column).at(i).role,
                              itm->values.at(column).at(i).value);
             }
         }
         // the two special cases
         QVariant displayValue = itm->data(column, Qt::DisplayRole);
         if (displayValue.isValid())
             roles.insert(Qt::DisplayRole, displayValue);
         QVariant checkValue = itm->data(column, Qt::CheckStateRole);
         if (checkValue.isValid())
             roles.insert(Qt::CheckStateRole, checkValue);
     }
     return roles;
 }
itemGreaterThan()
bool QTreeModel::itemGreaterThan (const QPair< QTreeWidgetItem *, int > & left, const QPair< QTreeWidgetItem *, int > & right) static
Returns true if the value of the left item is greater than the value of the right item.
Warning
This function is not part of the public interface.
Used by the sorting functions.
Definition at line 755 of file qtreewidget.cpp.
Referenced by ensureSorted(), sortItems(), and view().
 {
     return *(right.first) < *(left.first);
 }
itemLessThan()
bool QTreeModel::itemLessThan (const QPair< QTreeWidgetItem *, int > & left, const QPair< QTreeWidgetItem *, int > & right) static
Returns true if the value of the left item is less than the value of the right item.
Warning
This function is not part of the public interface.
Used by the sorting functions.
Definition at line 737 of file qtreewidget.cpp.
Referenced by ensureSorted(), sortItems(), and view().
 {
     return *(left.first) < *(right.first);
 }
mimeData()
QMimeData * QTreeModel::mimeData (const QModelIndexList & indexes) const virtual
Returns an object that contains serialized items of data corresponding to the list of indexes specified.
The formats used to describe the encoded data is obtained from the mimeTypes() function.
If the list of indexes is empty, or there are no supported MIME types, 0 is returned rather than a serialized empty list.
See also
mimeTypes(), dropMimeData()
Reimplemented from QAbstractItemModel.
Definition at line 784 of file qtreewidget.cpp.
Referenced by view().
 {
     QList<QTreeWidgetItem*> items;
     for (int i = 0; i < indexes.count(); ++i) {
         if (indexes.at(i).column() == 0) // only one item per row
             items << item(indexes.at(i));
     }
     // cachedIndexes is a little hack to avoid copying from QModelIndexList to
     // QList<QTreeWidgetItem*> and back again in the view
     cachedIndexes = indexes;
     QMimeData *mimeData = view()->mimeData(items);
     cachedIndexes.clear();
     return mimeData;
 }
mimeTypes()
QStringList QTreeModel::mimeTypes () const virtual
Returns a list of MIME types that can be used to describe a list of model indexes.
See also
mimeData()
Reimplemented from QAbstractItemModel.
Definition at line 774 of file qtreewidget.cpp.
Referenced by view().
 {
     return view()->mimeTypes();
 }
parent()
QModelIndex QTreeModel::parent (const QModelIndex & child) const virtual
Returns the parent model index of the index given as the child.
Warning
This function is not part of the public interface. Reimplemented Function
Implements QAbstractItemModel.
Definition at line 317 of file qtreewidget.cpp.
 {
     SkipSorting skipSorting(this); //The reason we don't sort here is that this might be called from a valid QPersistentModelIndex
                                    //We don't want it to become suddenly invalid
     if (!child.isValid())
         return QModelIndex();
     QTreeWidgetItem *itm = static_cast<QTreeWidgetItem *>(child.internalPointer());
     if (!itm || itm == rootItem)
         return QModelIndex();
     QTreeWidgetItem *parent = itm->parent();
     return index(parent, 0);
 }
removeRows()
bool QTreeModel::removeRows (int row, int count, const QModelIndex & parent = QModelIndex()) virtual
Warning
This function is not part of the public interface. Reimplemented Function
Reimplemented from QAbstractItemModel.
Definition at line 528 of file qtreewidget.cpp.
Referenced by view().
{
     if (count < 1 || row < 0 || (row + count) > rowCount(parent))
         return false;
     beginRemoveRows(parent, row, row + count - 1);
     bool blockSignal = signalsBlocked();
     blockSignals(true);
     QTreeWidgetItem *itm = item(parent);
     for (int i = row + count - 1; i >= row; --i) {
         QTreeWidgetItem *child = itm ? itm->takeChild(i) : rootItem->children.takeAt(i);
         Q_ASSERT(child);
         child->view = 0;
         delete child;
         child = 0;
     }
     blockSignals(blockSignal);
     endRemoveRows();
     return true;
 }
rowCount()
int QTreeModel::rowCount (const QModelIndex & parent) const virtual
Returns the number of rows in the parent model index.
Warning
This function is not part of the public interface. Reimplemented Function
Implements QAbstractItemModel.
Definition at line 341 of file qtreewidget.cpp.
Referenced by dropMimeData(), insertRows(), removeRows(), and view().
 {
     if (!parent.isValid())
         return rootItem->childCount();
     QTreeWidgetItem *parentItem = item(parent);
     if (parentItem)
         return parentItem->childCount();
     return 0;
 }
setColumnCount()
void QTreeModel::setColumnCount (int columns)
Sets the number of columns in the tree model.
Warning
This function is not part of the public interface.
Definition at line 197 of file qtreewidget.cpp.
Referenced by QTreeModel(), QTreeWidgetItem::setData(), and view().
 {
     SkipSorting skipSorting(this);
     if (columns < 0)
         return;
     if (!headerItem) {
         headerItem = new QTreeWidgetItem();
         headerItem->view = view();
     }
     int count = columnCount();
     if (count == columns)
         return;
     if (columns < count) {
         beginRemoveColumns(QModelIndex(), columns, count - 1);
         headerItem->values.resize(columns);
         endRemoveColumns();
     } else {
         beginInsertColumns(QModelIndex(), count, columns - 1);
         headerItem->values.resize(columns);
         for (int i = count; i < columns; ++i) {// insert data without emitting the dataChanged signal
             headerItem->values[i].append(QWidgetItemData(Qt::DisplayRole, QString::number(i + 1)));
             headerItem->d->display.append(QString::number(i + 1));
         }
         endInsertColumns();
     }
 }
setData()
bool QTreeModel::setData (const QModelIndex & index, const QVariant & value, int role) virtual
Sets the data for the item specified by the index and role to that referred to by the value.
Warning
This function is not part of the public interface. Reimplemented Function
Returns true if successful; otherwise returns false.
Reimplemented from QAbstractItemModel.
Definition at line 424 of file qtreewidget.cpp.
Referenced by view().
 {
     if (!index.isValid())
         return false;
     QTreeWidgetItem *itm = item(index);
     if (itm) {
         itm->setData(index.column(), role, value);
         return true;
     }
     return false;
 }
setHeaderData()
bool QTreeModel::setHeaderData (int section, Qt::Orientation orientation, const QVariant & value, int role) virtual
Sets the header data for the item specified by the header section, orientation and data role to the given value.
Warning
This function is not part of the public interface. Reimplemented Function
Returns true if successful; otherwise returns false.
Reimplemented from QAbstractItemModel.
Definition at line 587 of file qtreewidget.cpp.
Referenced by view().
 {
     if (section < 0 || orientation != Qt::Horizontal || !headerItem || section >= columnCount())
         return false;
     headerItem->setData(section, role, value);
     return true;
 }
sort()
void QTreeModel::sort (int column, Qt::SortOrder order) virtual
Sorts the entire tree in the model in the given order, by the values in the given column.
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemModel.
Definition at line 626 of file qtreewidget.cpp.
Referenced by executePendingSort(), and view().
 {
     SkipSorting skipSorting(this);
     sortPendingTimer.stop();
     if (column < 0 || column >= columnCount())
         return;
     //layoutAboutToBeChanged and layoutChanged will be called by sortChildren
     rootItem->sortChildren(column, order, true);
 }
sortedInsertionIterator()
QList< QTreeWidgetItem * >::iterator QTreeModel::sortedInsertionIterator (const QList< QTreeWidgetItem *>::iterator & begin, const QList< QTreeWidgetItem *>::iterator & end, Qt::SortOrder order, QTreeWidgetItem * item) static
Warning
This function is not part of the public interface.
Definition at line 764 of file qtreewidget.cpp.
Referenced by ensureSorted(), and view().
 {
     if (order == Qt::AscendingOrder)
         return qLowerBound(begin, end, item, QTreeModelLessThan());
     return qLowerBound(begin, end, item, QTreeModelGreaterThan());
 }
sortItems()
void QTreeModel::sortItems (QList< QTreeWidgetItem *> * items, int column, Qt::SortOrder order) protected
Definition at line 894 of file qtreewidget.cpp.
Referenced by createIndexFromItem(), and QTreeWidgetItemPrivate::sortChildren().
 {
     // see QTreeViewItem::operator<
     Q_UNUSED(column);
     if (isChanging())
         return;
     // store the original order of indexes
     QVector< QPair<QTreeWidgetItem*,int> > sorting(items->count());
     for (int i = 0; i < sorting.count(); ++i) {
         sorting[i].first = items->at(i);
         sorting[i].second = i;
     }
     // do the sorting
     LessThan compare = (order == Qt::AscendingOrder ? &itemLessThan : &itemGreaterThan);
     qStableSort(sorting.begin(), sorting.end(), compare);
     QModelIndexList fromList;
     QModelIndexList toList;
     int colCount = columnCount();
     for (int r = 0; r < sorting.count(); ++r) {
         int oldRow = sorting.at(r).second;
         if (oldRow == r)
             continue;
         QTreeWidgetItem *item = sorting.at(r).first;
         items->replace(r, item);
         for (int c = 0; c < colCount; ++c) {
             QModelIndex from = createIndex(oldRow, c, item);
             if (static_cast<QAbstractItemModelPrivate *>(d_ptr.data())->persistent.indexes.contains(from)) {
                 QModelIndex to = createIndex(r, c, item);
                 fromList << from;
                 toList << to;
             }
         }
     }
     changePersistentIndexList(fromList, toList);
 }
supportedDropActions()
Qt::DropActions QTreeModel::supportedDropActions () const virtual
Returns the drop actions supported by this model.
Since
4.2
The default implementation returns Qt::CopyAction. Reimplement this function if you wish to support additional actions. You must also reimplement the dropMimeData() function to handle the additional operations.
See also
dropMimeData(), Qt::DropActions, {Using drag and drop with item views}
Reimplemented from QAbstractItemModel.
Definition at line 808 of file qtreewidget.cpp.
Referenced by view().
 {
     return view()->supportedDropActions();
 }
timerEvent()
void QTreeModel::timerEvent (QTimerEvent * event) protected virtual
This event handler can be reimplemented in a subclass to receive timer events for the object.
QTimer provides a higher-level interface to the timer functionality, and also more general information about timers. The timer event is passed in the event parameter.
See also
startTimer(), killTimer(), event()
Reimplemented from QObject.
Definition at line 933 of file qtreewidget.cpp.
Referenced by createIndexFromItem().
 {
     if (ev->timerId() == sortPendingTimer.timerId()) {
         executePendingSort();
     } else {
         QAbstractItemModel::timerEvent(ev);
     }
 }
view()
QTreeWidget* QTreeModel::view () const inline
Definition at line 85 of file qtreewidget_p.h.
Referenced by dropMimeData(), executePendingSort(), insertRows(), mimeData(), mimeTypes(), setColumnCount(), and supportedDropActions().
         { return qobject_cast<QTreeWidget*>(QObject::parent()); }
Friends and Related Functions
QTreeWidget
friend class QTreeWidget friend
Definition at line 74 of file qtreewidget_p.h.
QTreeWidgetItem
friend class QTreeWidgetItem friend
Definition at line 76 of file qtreewidget_p.h.
Referenced by insertRows(), and setColumnCount().
QTreeWidgetItemIterator
friend class QTreeWidgetItemIterator friend
Definition at line 78 of file qtreewidget_p.h.
QTreeWidgetItemIteratorPrivate
friend class QTreeWidgetItemIteratorPrivate friend
Definition at line 79 of file qtreewidget_p.h.
Referenced by QTreeWidgetItemIterator::QTreeWidgetItemIterator().
QTreeWidgetItemPrivate
friend class QTreeWidgetItemPrivate friend
Definition at line 77 of file qtreewidget_p.h.
QTreeWidgetPrivate
friend class QTreeWidgetPrivate friend
Definition at line 75 of file qtreewidget_p.h.
SkipSorting
friend struct SkipSorting friend
Definition at line 175 of file qtreewidget_p.h.
Properties
cachedIndexes
QModelIndexList QTreeModel::cachedIndexes mutable private
Definition at line 155 of file qtreewidget_p.h.
Referenced by internalMimeData(), and mimeData().
headerItem
QTreeWidgetItem* QTreeModel::headerItem private
Definition at line 153 of file qtreewidget_p.h.
Referenced by columnCount(), emitDataChanged(), headerData(), insertColumns(), QTreeModel(), QTreeWidgetItem::QTreeWidgetItem(), setColumnCount(), QTreeWidgetItem::setData(), setHeaderData(), ~QTreeModel(), and QTreeWidgetItem::~QTreeWidgetItem().
iterators
QList<QTreeWidgetItemIterator*> QTreeModel::iterators private
Definition at line 156 of file qtreewidget_p.h.
Referenced by beginRemoveItems(), and QTreeWidgetItemIterator::QTreeWidgetItemIterator().
rootItem
QTreeWidgetItem* QTreeModel::rootItem private
Definition at line 152 of file qtreewidget_p.h.
Referenced by beginRemoveItems(), clear(), ensureSorted(), flags(), hasChildren(), index(), QTreeWidgetItem::insertChildren(), insertColumns(), insertRows(), parent(), QTreeModel(), QTreeWidgetItem::QTreeWidgetItem(), QTreeWidgetItemIterator::QTreeWidgetItemIterator(), removeRows(), rowCount(), sort(), ~QTreeModel(), and QTreeWidgetItem::~QTreeWidgetItem().
skipPendingSort
bool QTreeModel::skipPendingSort mutable private
Definition at line 159 of file qtreewidget_p.h.
Referenced by executePendingSort(), QTreeModel::SkipSorting::SkipSorting(), QTreeWidgetItem::takeChild(), QTreeWidgetItem::~QTreeWidgetItem(), and QTreeModel::SkipSorting::~SkipSorting().
sortPendingTimer
QBasicTimer QTreeModel::sortPendingTimer mutable private
Definition at line 158 of file qtreewidget_p.h.
Referenced by clear(), ensureSorted(), executePendingSort(), sort(), and timerEvent().
The documentation for this class was generated from the following files:
/src/gui/itemviews/qtreewidget_p.h
/src/gui/itemviews/qtreewidget.cpp