Qt 4.8: QUrl Class Reference
QUrl Class Reference
The QUrl class provides a convenient interface for working with URLs.
#include <qurl.h>
Public Types
typedef QUrlPrivate * DataPtr
enum FormattingOption {
None = 0x0, RemoveScheme = 0x1, RemovePassword = 0x2, RemoveUserInfo = RemovePassword | 0x4,
RemovePort = 0x8, RemoveAuthority = RemoveUserInfo | RemovePort | 0x10, RemovePath = 0x20, RemoveQuery = 0x40,
RemoveFragment = 0x80, StripTrailingSlash = 0x10000
}
The formatting options define how the URL is formatted when written out as text.
enum ParsingMode { TolerantMode, StrictMode }
The parsing mode controls the way QUrl parses strings.
Public Functions
void addEncodedQueryItem (const QByteArray &key, const QByteArray &value)
Inserts the pair key = value into the query string of the URL.
void addQueryItem (const QString &key, const QString &value)
Inserts the pair key = value into the query string of the URL.
QList< QByteArray > allEncodedQueryItemValues (const QByteArray &key) const
Returns the a list of query string values whose key is equal to key from the URL.
QStringList allQueryItemValues (const QString &key) const
Returns the a list of query string values whose key is equal to key from the URL.
QString authority () const
Returns the authority of the URL if it is defined; otherwise an empty string is returned.
void clear ()
Resets the content of the QUrl.
DataPtr & data_ptr ()
void detach ()
Forces a detach.
QByteArray encodedFragment () const
Returns the fragment of the URL if it is defined; otherwise an empty string is returned.
QByteArray encodedHost () const
Returns the host part of the URL if it is defined; otherwise an empty string is returned.
QByteArray encodedPassword () const
Returns the password of the URL if it is defined; otherwise an empty string is returned.
QByteArray encodedPath () const
Returns the path of the URL if it is defined; otherwise an empty string is returned.
QByteArray encodedQuery () const
Returns the query string of the URL in percent encoded form.
QList< QPair< QByteArray, QByteArray > > encodedQueryItems () const
Returns the query string of the URL, as a map of encoded keys and values.
QByteArray encodedQueryItemValue (const QByteArray &key) const
Returns the first query string value whose key is equal to key from the URL.
QByteArray encodedUserName () const
Returns the user name of the URL if it is defined; otherwise an empty string is returned.
QString errorString () const
Returns a text string that explains why an URL is invalid in the case being; otherwise returns an empty string.
QString fragment () const
Returns the fragment of the URL.
bool hasEncodedQueryItem (const QByteArray &key) const
Returns true if there is a query string pair whose key is equal to key from the URL.
bool hasFragment () const
Returns true if this URL contains a fragment (i.
bool hasQuery () const
Returns true if this URL contains a Query (i.
bool hasQueryItem (const QString &key) const
Returns true if there is a query string pair whose key is equal to key from the URL.
QString host () const
Returns the host of the URL if it is defined; otherwise an empty string is returned.
bool isDetached () const
bool isEmpty () const
Returns true if the URL has no data; otherwise returns false.
bool isLocalFile () const
Returns true if this URL is pointing to a local file path.
bool isParentOf (const QUrl &url) const
Returns true if this URL is a parent of childUrl.
bool isRelative () const
Returns true if the URL is relative; otherwise returns false.
bool isValid () const
Returns true if the URL is valid; otherwise returns false.
bool operator!= (const QUrl &url) const
Returns true if this URL and the given url are not equal; otherwise returns false.
bool operator< (const QUrl &url) const
Returns true if this URL is "less than" the given url.
QUrl & operator= (const QUrl &copy)
Assigns the specified url to this object.
QUrl & operator= (const QString &url)
Assigns the specified url to this object.
bool operator== (const QUrl &url) const
Returns true if this URL and the given url are equal; otherwise returns false.
QString password () const
Returns the password of the URL if it is defined; otherwise an empty string is returned.
QString path () const
Returns the path of the URL.
int port () const
Returns the port of the URL, or -1 if the port is unspecified.
int port (int defaultPort) const
Returns the port of the URL, or defaultPort if the port is unspecified.
QList< QPair< QString, QString > > queryItems () const
Returns the query string of the URL, as a map of keys and values.
QString queryItemValue (const QString &key) const
Returns the first query string value whose key is equal to key from the URL.
char queryPairDelimiter () const
Returns the character used to delimit between key-value pairs in the query string of the URL.
char queryValueDelimiter () const
Returns the character used to delimit between keys and values in the query string of the URL.
QUrl ()
Constructs an empty QUrl object.
QUrl (const QString &url)
Constructs a URL by parsing url.
QUrl (const QString &url, ParsingMode mode)
Parses the url using the parser mode parsingMode.
QUrl (const QUrl &copy)
Constructs a copy of other.
void removeAllEncodedQueryItems (const QByteArray &key)
Removes all the query string pairs whose key is equal to key from the URL.
void removeAllQueryItems (const QString &key)
Removes all the query string pairs whose key is equal to key from the URL.
void removeEncodedQueryItem (const QByteArray &key)
Removes the first query string pair whose key is equal to key from the URL.
void removeQueryItem (const QString &key)
Removes the first query string pair whose key is equal to key from the URL.
QUrl resolved (const QUrl &relative) const
Returns the result of the merge of this URL with relative.
QString scheme () const
Returns the scheme of the URL.
void setAuthority (const QString &authority)
Sets the authority of the URL to authority.
void setEncodedFragment (const QByteArray &fragment)
Sets the URL's fragment to the percent-encoded fragment.
void setEncodedHost (const QByteArray &host)
Sets the URL's host to the ACE- or percent-encoded host.
void setEncodedPassword (const QByteArray &password)
Sets the URL's password to the percent-encoded password.
void setEncodedPath (const QByteArray &path)
Sets the URL's path to the percent-encoded path.
void setEncodedQuery (const QByteArray &query)
Sets the query string of the URL to query.
void setEncodedQueryItems (const QList< QPair< QByteArray, QByteArray > > &query)
Sets the query string of the URL to the encoded version of query.
void setEncodedUrl (const QByteArray &url)
Constructs a URL by parsing the contents of encodedUrl.
void setEncodedUrl (const QByteArray &url, ParsingMode mode)
Constructs a URL by parsing the contents of encodedUrl using the given parsingMode.
void setEncodedUserName (const QByteArray &userName)
Sets the URL's user name to the percent-encoded userName.
void setFragment (const QString &fragment)
Sets the fragment of the URL to fragment.
void setHost (const QString &host)
Sets the host of the URL to host.
void setPassword (const QString &password)
Sets the URL's password to password.
void setPath (const QString &path)
Sets the path of the URL to path.
void setPort (int port)
Sets the port of the URL to port.
void setQueryDelimiters (char valueDelimiter, char pairDelimiter)
Sets the characters used for delimiting between keys and values, and between key-value pairs in the URL's query string.
void setQueryItems (const QList< QPair< QString, QString > > &query)
Sets the query string of the URL to an encoded version of query.
void setScheme (const QString &scheme)
Sets the scheme of the URL to scheme.
void setUrl (const QString &url)
Constructs a URL by parsing the contents of url.
void setUrl (const QString &url, ParsingMode mode)
Parses url using the parsing mode parsingMode.
void setUserInfo (const QString &userInfo)
Sets the user info of the URL to userInfo.
void setUserName (const QString &userName)
Sets the URL's user name to userName.
void swap (QUrl &other)
Swaps URL other with this URL.
QByteArray toEncoded (FormattingOptions options=None) const
Returns the encoded representation of the URL if it's valid; otherwise an empty QByteArray is returned.
QString toLocalFile () const
Returns the path of this URL formatted as a local file path.
QString topLevelDomain () const
Returns the TLD (Top-Level Domain) of the URL, (e.
QString toString (FormattingOptions options=None) const
Returns the human-displayable string representation of the URL.
QString userInfo () const
Returns the user info of the URL, or an empty string if the user info is undefined.
QString userName () const
Returns the user name of the URL if it is defined; otherwise an empty string is returned.
~QUrl ()
Destructor; called immediately before the object is deleted.
Static Public Functions
static QString fromAce (const QByteArray &)
Returns the Unicode form of the given domain name domain, which is encoded in the ASCII Compatible Encoding (ACE).
static QUrl fromEncoded (const QByteArray &url)
Parses input and returns the corresponding QUrl.
static QUrl fromEncoded (const QByteArray &url, ParsingMode mode)
Parses the URL using parsingMode.
static QUrl fromLocalFile (const QString &localfile)
Returns a QUrl representation of localFile, interpreted as a local file.
static QString fromPercentEncoding (const QByteArray &)
Returns a decoded copy of input.
static QString fromPunycode (const QByteArray &)
Returns the Punycode decoded representation of pc.
static QUrl fromUserInput (const QString &userInput)
Returns a valid URL from a user supplied userInput string if one can be deducted.
static QStringList idnWhitelist ()
Returns the current whitelist of top-level domains that are allowed to have non-ASCII characters in their compositions.
static void setIdnWhitelist (const QStringList &)
Sets the whitelist of Top-Level Domains (TLDs) that are allowed to have non-ASCII characters in domains to the value of list.
static QByteArray toAce (const QString &)
Returns the ASCII Compatible Encoding of the given domain name domain.
static QByteArray toPercentEncoding (const QString &, const QByteArray &exclude=QByteArray(), const QByteArray &include=QByteArray())
Returns an encoded copy of input.
static QByteArray toPunycode (const QString &)
Returns a uc in Punycode encoding.
Private Functions
void detach (QMutexLocker &locker)
Forces a detach.
Properties
QUrlPrivate * d
Related Functions
(Note that these are not member functions.)
QDataStream & operator<< (QDataStream &out, const QUrl &url)
Writes url url to the stream out and returns a reference to the stream.
QDataStream & operator>> (QDataStream &in, QUrl &url)
Reads a url into url from the stream in and returns a reference to the stream.
uint qHash (const QUrl &url)
Detailed Description
The QUrl class provides a convenient interface for working with URLs.
Note
This class or function is reentrant.
It can parse and construct URLs in both encoded and unencoded form. QUrl also has support for internationalized domain names (IDNs).
The most common way to use QUrl is to initialize it via the constructor by passing a QString. Otherwise, setUrl() and setEncodedUrl() can also be used.
URLs can be represented in two forms: encoded or unencoded. The unencoded representation is suitable for showing to users, but the encoded representation is typically what you would send to a web server. For example, the unencoded URL "http://b\uuml\c{}hler.example.com/List of applicants.xml" would be sent to the server as "http://xn--bhler-kva.example.com/List%20of%20applicants.xml", and this can be verified by calling the toEncoded() function.
A URL can also be constructed piece by piece by calling setScheme(), setUserName(), setPassword(), setHost(), setPort(), setPath(), setEncodedQuery() and setFragment(). Some convenience functions are also available: setAuthority() sets the user name, password, host and port. setUserInfo() sets the user name and password at once.
Call isValid() to check if the URL is valid. This can be done at any point during the constructing of a URL.
Constructing a query is particularly convenient through the use of setQueryItems(), addQueryItem() and removeQueryItem(). Use setQueryDelimiters() to customize the delimiters used for generating the query string.
For the convenience of generating encoded URL strings or query strings, there are two static functions called fromPercentEncoding() and toPercentEncoding() which deal with percent encoding and decoding of QStrings.
Calling isRelative() will tell whether or not the URL is relative. A relative URL can be resolved by passing it as argument to resolved(), which returns an absolute URL. isParentOf() is used for determining whether one URL is a parent of another.
fromLocalFile() constructs a QUrl by parsing a local file path. toLocalFile() converts a URL to a local file path.
The human readable representation of the URL is fetched with toString(). This representation is appropriate for displaying a URL to a user in unencoded form. The encoded form however, as returned by toEncoded(), is for internal use, passing to web servers, mail clients and so on.
QUrl conforms to the URI specification from RFC 3986 (Uniform Resource Identifier: Generic Syntax), and includes scheme extensions from RFC 1738 (Uniform Resource Locators). Case folding rules in QUrl conform to RFC 3491 (Nameprep: A Stringprep Profile for Internationalized Domain Names (IDN)).
Character Conversions
Follow these rules to avoid erroneous character conversion when dealing with URLs and strings:
When creating an QString to contain a URL from a QByteArray or a char*, always use QString::fromUtf8().
Favor the use of QUrl::fromEncoded() and QUrl::toEncoded() instead of QUrl(string) and QUrl::toString() when converting a QUrl to or from a string.
See also
QUrlInfo
Definition at line 61 of file qurl.h.
Typedefs
DataPtr
QUrl::DataPtr
Warning
This function is not part of the public interface.
Definition at line 281 of file qurl.h.
Enumerations
FormattingOption
enum QUrl::FormattingOption
The formatting options define how the URL is formatted when written out as text.
None The format of the URL is unchanged.
RemoveScheme The scheme is removed from the URL.
RemovePassword Any password in the URL is removed.
RemoveUserInfo Any user information in the URL is removed.
RemovePort Any specified port is removed from the URL.
RemoveAuthority
RemovePath The URL's path is removed, leaving only the scheme, host address, and port (if present).
RemoveQuery The query part of the URL (following a '?' character) is removed.
RemoveFragment
StripTrailingSlash The trailing slash is removed if one is present.
Note that the case folding rules in RFC 3491{Nameprep}, which QUrl conforms to, require host names to always be converted to lower case, regardless of the Qt::FormattingOptions used.
Enumerator
None
RemoveScheme
RemovePassword
RemoveUserInfo
RemovePort
RemoveAuthority
RemovePath
RemoveQuery
RemoveFragment
StripTrailingSlash
Definition at line 70 of file qurl.h.
{
         None = 0x0,
         RemoveScheme = 0x1,
         RemovePassword = 0x2,
         RemoveUserInfo = RemovePassword | 0x4,
         RemovePort = 0x8,
         RemoveAuthority = RemoveUserInfo | RemovePort | 0x10,
         RemovePath = 0x20,
         RemoveQuery = 0x40,
         RemoveFragment = 0x80,
         // 0x100: private: normalized
         StripTrailingSlash = 0x10000
     };
ParsingMode
enum QUrl::ParsingMode
The parsing mode controls the way QUrl parses strings.
TolerantMode QUrl will try to correct some common errors in URLs. This mode is useful when processing URLs entered by users.
StrictMode Only valid URLs are accepted. This mode is useful for general URL validation.
In TolerantMode, the parser corrects the following invalid input:
Spaces and "%20": If an encoded URL contains a space, this will be replaced with "%20". If a decoded URL contains "%20", this will be replaced with a single space before the URL is parsed.
Single "%" characters: Any occurrences of a percent character "%" not followed by exactly two hexadecimal characters (e.g., "13% coverage.html") will be replaced by "%25".
Reserved and unreserved characters: An encoded URL should only contain a few characters as literals; all other characters should be percent-encoded. In TolerantMode, these characters will be automatically percent-encoded where they are not allowed: space / double-quote / "<" / ">" / "[" / "\" / "]" / "^" / "`" / "{" / "|" / "}"
Enumerator
TolerantMode
StrictMode
Definition at line 64 of file qurl.h.
                      {
         TolerantMode,
         StrictMode
     };
Constructors and Destructors
QUrl() [1/4]
QUrl::QUrl ()
Constructs an empty QUrl object.
Definition at line 4272 of file qurl.cpp.
Referenced by fromUserInput().
            : d(0)
 {
 }
QUrl() [2/4]
QUrl::QUrl (const QString & url)
Constructs a URL by parsing url.
url is assumed to be in human readable representation, with no percent encoding. QUrl will automatically percent encode all characters that are not allowed in a URL. The default parsing mode is TolerantMode.
Example:
QUrl url("http://www.example.com/List of holidays.xml");
// url.toEncoded() == "http://www.example.com/List%20of%20holidays.xml"
To construct a URL from an encoded string, call fromEncoded():
QUrl url = QUrl::fromEncoded("http://qt.nokia.com/List%20of%20holidays.xml");
See also
setUrl(), setEncodedUrl(), fromEncoded(), TolerantMode
Definition at line 4242 of file qurl.cpp.
                              : d(0)
 {
     if (!url.isEmpty())
         setUrl(url);
 }
QUrl() [3/4]
QUrl::QUrl (const QString & url, ParsingMode parsingMode)
Parses the url using the parser mode parsingMode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The default parsing mode is TolerantMode.
See also
setUrl()
Definition at line 4259 of file qurl.cpp.
                                                       : d(0)
 {
     if (!url.isEmpty())
         setUrl(url, parsingMode);
     else {
         d = new QUrlPrivate;
         d->parsingMode = parsingMode;
     }
 }
QUrl() [4/4]
QUrl::QUrl (const QUrl & copy)
Constructs a copy of other.
Definition at line 4279 of file qurl.cpp.
                             : d(other.d)
 {
     if (d)
         d->ref.ref();
 }
~QUrl()
QUrl::~QUrl ()
Destructor; called immediately before the object is deleted.
Definition at line 4288 of file qurl.cpp.
 {
     if (d && !d->ref.deref())
         delete d;
 }
Functions
addEncodedQueryItem()
void QUrl::addEncodedQueryItem (const QByteArray & key, const QByteArray & value)
Inserts the pair key = value into the query string of the URL.
Since
4.4
Note: this function does not verify that either key or value are properly encoded. It is the caller's responsibility to ensure that the query delimiters are properly encoded, if any.
See also
addQueryItem(), setQueryDelimiters()
Definition at line 5279 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     if (!d->query.isEmpty())
         d->query += d->pairDelimiter;
     d->query += key;
     d->query += d->valueDelimiter;
     d->query += value;
     d->hasQuery = !d->query.isEmpty();
 }
addQueryItem()
void QUrl::addQueryItem (const QString & key, const QString & value)
Inserts the pair key = value into the query string of the URL.
The key/value pair is encoded before it is added to the query. The pair is converted into separate strings internally. The key and value is first encoded into UTF-8 and then delimited by the character returned by valueDelimiter(). Each key/value pair is delimited by the character returned by pairDelimiter().
Note
This method does not encode spaces (ASCII 0x20) as plus (+) signs, like HTML forms do. If you need that kind of encoding, you must encode the value yourself and use QUrl::addEncodedQueryItem.
See also
addEncodedQueryItem()
Definition at line 5240 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     char alsoEncode[3];
     alsoEncode[0] = d->valueDelimiter;
     alsoEncode[1] = d->pairDelimiter;
     alsoEncode[2] = 0;
     if (!d->query.isEmpty())
         d->query += d->pairDelimiter;
     // query = *( pchar / "/" / "?" )
     d->query += toPercentEncodingHelper(key, queryExcludeChars, alsoEncode);
     d->query += d->valueDelimiter;
     // query = *( pchar / "/" / "?" )
     d->query += toPercentEncodingHelper(value, queryExcludeChars, alsoEncode);
     d->hasQuery = !d->query.isEmpty();
 }
allEncodedQueryItemValues()
QList< QByteArray > QUrl::allEncodedQueryItemValues (const QByteArray & key) const
Returns the a list of query string values whose key is equal to key from the URL.
Since
4.4
Note: if the encoded key does not match the encoded version of the query, this function will not work. That is, if the encoded query of this URL is "search=Qt%20Rules", calling this function with key = "%73earch" will return an empty list.
See also
allQueryItemValues(), queryItemValue(), encodedQueryItemValue()
Definition at line 5516 of file qurl.cpp.
 {
     if (!d) return QList<QByteArray>();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     QList<QByteArray> values;
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         if (key == QByteArray::fromRawData(query + pos, valuedelim - pos))
             values += valuedelim < end ?
                       QByteArray(query + valuedelim + 1, end - valuedelim - 1)
                       : QByteArray();
         pos = end + 1;
     }
     return values;
 }
allQueryItemValues()
QStringList QUrl::allQueryItemValues (const QString & key) const
Returns the a list of query string values whose key is equal to key from the URL.
Note
This method does not decode spaces plus (+) signs as spaces (ASCII 0x20), like HTML forms do. If you need that kind of decoding, you must use QUrl::allEncodedQueryItemValues and decode the data yourself.
See also
queryItemValue()
Definition at line 5474 of file qurl.cpp.
 {
     if (!d) return QStringList();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     QByteArray encodedKey = toPercentEncoding(key, queryExcludeChars);
     QStringList values;
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         if (encodedKey == QByteArray::fromRawData(query + pos, valuedelim - pos)) {
             QByteArray v(query + valuedelim + 1, end - valuedelim - 1);
             values += valuedelim < end ?
                       fromPercentEncodingMutable(&v)
                       : QString();
         }
         pos = end + 1;
     }
     return values;
 }
authority()
QString QUrl::authority () const
Returns the authority of the URL if it is defined; otherwise an empty string is returned.
See also
setAuthority()
Definition at line 4592 of file qurl.cpp.
Referenced by QNetworkAccessFileBackendFactory::create(), isParentOf(), and QDeclarativeEnginePrivate::urlToLocalFileOrQrc().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->authority();
 }
clear()
void QUrl::clear ()
Resets the content of the QUrl.
After calling this function, the QUrl is equal to one that has been constructed with the default empty constructor.
Definition at line 4340 of file qurl.cpp.
Referenced by operator=().
 {
     if (d && !d->ref.deref())
         delete d;
     d = 0;
 }
data_ptr()
DataPtr & QUrl::data_ptr () inline
Warning
This function is not part of the public interface.
Definition at line 282 of file qurl.h.
 { return d; }
detach() [1/2]
void QUrl::detach ()
Forces a detach.
Warning
This function is not part of the public interface.
Definition at line 6313 of file qurl.cpp.
Referenced by addEncodedQueryItem(), addQueryItem(), removeAllEncodedQueryItems(), removeEncodedQueryItem(), setAuthority(), setEncodedFragment(), setEncodedPassword(), setEncodedPath(), setEncodedQuery(), setEncodedQueryItems(), setEncodedUrl(), setEncodedUserName(), setFragment(), setHost(), setPassword(), setPath(), setPort(), setQueryDelimiters(), setQueryItems(), setScheme(), setUrl(), setUserInfo(), and setUserName().
 {
     if (!d) {
         d = new QUrlPrivate;
     } else {
         // Public method, so it must lock first.
         QMutexLocker lock(&d->mutex);
         detach(lock);
     }
 }
detach() [2/2]
void QUrl::detach (QMutexLocker & locker) private
Forces a detach.
Warning
This function is not part of the public interface.
Unlocks locker once the detaching is done.
It's ok to access private members afterwards, without lock, since after detaching we have our private copy of the d pointer, that no other QUrl instance can know about yet.
Definition at line 6336 of file qurl.cpp.
 {
     Q_ASSERT(d); // we have a locker, so we have a d pointer
     // Ensure that we hold the mutex until after making our private copy,
     // so that another thread cannot deref + delete d meanwhile.
     // So this is a modified version of qAtomicDetach(d)
     if (d->ref == 1) {
         locker.unlock();
         return;
     }
     QUrlPrivate * x = d;
     d = new QUrlPrivate(*x);
     locker.unlock();
     if (!x->ref.deref())
         delete x;
 }
encodedFragment()
QByteArray QUrl::encodedFragment () const
Returns the fragment of the URL if it is defined; otherwise an empty string is returned.
Since
4.4
The returned value will have its non-ASCII and other control characters percent-encoded, as in toEncoded().
See also
setEncodedFragment(), toEncoded()
Definition at line 5753 of file qurl.cpp.
Referenced by QUrlPrivate::fragmentImpl().
 {
     if (!d) return QByteArray();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     d->ensureEncodedParts();
     return d->encodedFragment;
 }
encodedHost()
QByteArray QUrl::encodedHost () const
Returns the host part of the URL if it is defined; otherwise an empty string is returned.
Since
4.4
Note: encodedHost() does not return percent-encoded hostnames. Instead, the ACE-encoded (bare ASCII in Punycode encoding) form will be returned for any non-ASCII hostname.
This function is equivalent to calling QUrl::toAce() on the return value of host().
See also
setEncodedHost()
Definition at line 4884 of file qurl.cpp.
 {
     // should we cache this in d->encodedHost?
     return QUrl::toAce(host());
 }
encodedPassword()
QByteArray QUrl::encodedPassword () const
Returns the password of the URL if it is defined; otherwise an empty string is returned.
Since
4.4
The returned value will have its non-ASCII and other control characters percent-encoded, as in toEncoded().
See also
setEncodedPassword(), toEncoded()
Definition at line 4805 of file qurl.cpp.
 {
     if (!d) return QByteArray();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     d->ensureEncodedParts();
     return d->encodedPassword;
 }
encodedPath()
QByteArray QUrl::encodedPath () const
Returns the path of the URL if it is defined; otherwise an empty string is returned.
Since
4.4
The returned value will have its non-ASCII and other control characters percent-encoded, as in toEncoded().
See also
setEncodedPath(), toEncoded()
Definition at line 5038 of file qurl.cpp.
 {
     if (!d) return QByteArray();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     d->ensureEncodedParts();
     return d->encodedPath;
 }
encodedQuery()
QByteArray QUrl::encodedQuery () const
Returns the query string of the URL in percent encoded form.
Definition at line 5643 of file qurl.cpp.
Referenced by QHttpNetworkRequestPrivate::header().
 {
     if (!d) return QByteArray();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->query;
 }
encodedQueryItems()
QList< QPair< QByteArray, QByteArray > > QUrl::encodedQueryItems () const
Returns the query string of the URL, as a map of encoded keys and values.
Since
4.4
See also
setEncodedQueryItems(), setQueryItems(), setEncodedQuery()
Definition at line 5342 of file qurl.cpp.
 {
     if (!d) return QList<QPair<QByteArray, QByteArray> >();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     QList<QPair<QByteArray, QByteArray> > itemMap;
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         if (valuedelim < end)
             itemMap += qMakePair(QByteArray(query + pos, valuedelim - pos),
                                  QByteArray(query + valuedelim + 1, end - valuedelim - 1));
         else
             itemMap += qMakePair(QByteArray(query + pos, valuedelim - pos), QByteArray());
         pos = end + 1;
     }
     return itemMap;
 }
encodedQueryItemValue()
QByteArray QUrl::encodedQueryItemValue (const QByteArray & key) const
Returns the first query string value whose key is equal to key from the URL.
Since
4.4
Note: if the encoded key does not match the encoded version of the query, this function will not work. That is, if the encoded query of this URL is "search=Qt%20Rules", calling this function with key = "%73earch" will return an empty string.
See also
queryItemValue(), allQueryItemValues()
Definition at line 5445 of file qurl.cpp.
Referenced by queryItemValue().
 {
     if (!d) return QByteArray();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         if (key == QByteArray::fromRawData(query + pos, valuedelim - pos))
             return valuedelim < end ?
                 QByteArray(query + valuedelim + 1, end - valuedelim - 1) : QByteArray();
         pos = end + 1;
     }
     return QByteArray();
 }
encodedUserName()
QByteArray QUrl::encodedUserName () const
Returns the user name of the URL if it is defined; otherwise an empty string is returned.
Since
4.4
The returned value will have its non-ASCII and other control characters percent-encoded, as in toEncoded().
See also
setEncodedUserName()
Definition at line 4719 of file qurl.cpp.
 {
     if (!d) return QByteArray();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     d->ensureEncodedParts();
     return d->encodedUserName;
 }
errorString()
QString QUrl::errorString () const
Returns a text string that explains why an URL is invalid in the case being; otherwise returns an empty string.
Since
4.2
Definition at line 6800 of file qurl.cpp.
 {
     if (!d)
         return QLatin1String(QT_TRANSLATE_NOOP(QUrl, "Invalid URL \"\": ")); // XXX not a good message, but the one an empty URL produces
     QMutexLocker lock(&d->mutex);
     return d->createErrorString();
 }
fragment()
QString QUrl::fragment () const
Returns the fragment of the URL.
See also
setFragment()
Definition at line 5687 of file qurl.cpp.
Referenced by QPatternist::ReportContext::codeFromURI(), QUrlPrivate::fragmentImpl(), QPatternist::ColoringMessageHandler::handleMessage(), setEncodedFragment(), setFragment(), and QTextBrowserPrivate::setSource().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->fragmentImpl();
 }
fromAce()
QString QUrl::fromAce (const QByteArray & domain) static
Returns the Unicode form of the given domain name domain, which is encoded in the ASCII Compatible Encoding (ACE).
Since
4.2
The result of this function is considered equivalent to domain.
If the value in domain cannot be encoded, it will be converted to QString and returned.
The ASCII Compatible Encoding (ACE) is defined by RFC 3490, RFC 3491 and RFC 3492. It is part of the Internationalizing Domain Names in Applications (IDNA) specification, which allows for domain names (like "example.com") to be written using international characters.
Definition at line 6134 of file qurl.cpp.
Referenced by interfaceListing(), QHostInfo::localDomainName(), and QNetworkCookiePrivate::parseSetCookieHeaderLine().
 {
     return qt_ACE_do(QString::fromLatin1(domain), NormalizeAce);
 }
fromEncoded() [1/2]
QUrl QUrl::fromEncoded (const QByteArray & input) static
Parses input and returns the corresponding QUrl.
input is assumed to be in encoded form, containing only ASCII characters.
The URL is parsed using TolerantMode.
See also
toEncoded(), setUrl()
Definition at line 5964 of file qurl.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QNetworkAccessHttpBackend::checkForRedirect(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), fromUserInput(), getImage(), getPixmap(), operator>>(), parseHeaderValue(), qmlxmlhttprequest_open(), QTextBrowserPrivate::resolveUrl(), QMimeDataPrivate::retrieveTypedData(), and QTextOdfWriter::writeInlineCharacter().
 {
     QUrl tmp;
     tmp.setEncodedUrl(input, TolerantMode);
     return tmp;
 }
fromEncoded() [2/2]
QUrl QUrl::fromEncoded (const QByteArray & input, ParsingMode parsingMode) static
Parses the URL using parsingMode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
toEncoded(), setUrl()
Definition at line 5981 of file qurl.cpp.
 {
     QUrl tmp;
     tmp.setEncodedUrl(input, parsingMode);
     return tmp;
 }
fromLocalFile()
QUrl QUrl::fromLocalFile (const QString & localFile) static
Returns a QUrl representation of localFile, interpreted as a local file.
This function accepts paths separated by slashes as well as the native separator for this platform.
This function also accepts paths with a doubled leading slash (or backslash) to indicate a remote file, as in "//servername/path/to/file.txt". Note that only certain platforms can actually open this file using QFile::open().
See also
toLocalFile(), isLocalFile(), QDir::toNativeSeparators()
Definition at line 6374 of file qurl.cpp.
Referenced by QFileDialogPrivate::_q_pathChanged(), QDeclarativeImportsPrivate::add(), QUrlModel::addUrls(), QDeclarativeEngine::baseUrl(), QWindowsMimeURI::convertToMime(), QmlJSDebugger::AbstractViewInspector::createQmlObject(), QFileDialogPrivate::createWidgets(), QDeclarativeFolderListModel::data(), fromUserInput(), QGtkStylePrivate::getFilesystemIcon(), QTextDocument::loadResource(), QDirModel::mimeData(), QFileSystemModel::mimeData(), QPatternist::XPathHelper::normalizeQueryURI(), QDeclarativeComponent::QDeclarativeComponent(), QFileOpenEvent::QFileOpenEvent(), QDeclarativeTypeLoader::qmlDirParser(), registerComponent(), resolveScheme(), QTextBrowserPrivate::resolveUrl(), QDeclarativeFolderListModel::setFolder(), QFileDialogComboBox::setHistory(), QmlApplicationViewer::setMainQmlFile(), and QFileDialogComboBox::showPopup().
 {
     QUrl url;
     url.setScheme(QLatin1String("file"));
     QString deslashified = QDir::fromNativeSeparators(localFile);
     // magic for drives on windows
     if (deslashified.length() > 1 && deslashified.at(1) == QLatin1Char(':') && deslashified.at(0) != QLatin1Char('/')) {
         url.setPath(QLatin1Char('/') + deslashified);
     // magic for shared drive on windows
     } else if (deslashified.startsWith(QLatin1String("//"))) {
         int indexOfPath = deslashified.indexOf(QLatin1Char('/'), 2);
         url.setHost(deslashified.mid(2, indexOfPath - 2));
         if (indexOfPath > 2)
             url.setPath(deslashified.right(deslashified.length() - indexOfPath));
     } else {
         url.setPath(deslashified);
     }
     return url;
 }
fromPercentEncoding()
QString QUrl::fromPercentEncoding (const QByteArray & input) static
Returns a decoded copy of input.
input is first decoded from percent encoding, then converted from UTF-8 to unicode.
Definition at line 5992 of file qurl.cpp.
Referenced by QNetworkCookiePrivate::parseSetCookieHeaderLine(), swap(), and toString().
 {
     return fromPercentEncodingHelper(input);
 }
fromPunycode()
QString QUrl::fromPunycode (const QByteArray & pc) static
Returns the Punycode decoded representation of pc.
Punycode is a Unicode encoding used for internationalized domain names, as defined in RFC3492. If you want to convert a domain from its ASCII-compatible encoding to the Unicode representation, use fromAce().
Definition at line 6044 of file qurl.cpp.
Referenced by qt_ACE_do().
 {
     uint n = initial_n;
     uint i = 0;
     uint bias = initial_bias;
     // strip any ACE prefix
     int start = pc.startsWith("xn--") ? 4 : 0;
     if (!start)
         return QString::fromLatin1(pc);
     // find the last delimiter character '-' in the input array. copy
     // all data before this delimiter directly to the output array.
     int delimiterPos = pc.lastIndexOf(0x2d);
     QString output = delimiterPos < 4 ?
                      QString() : QString::fromLatin1(pc.constData() + start, delimiterPos - start);
     // if a delimiter was found, skip to the position after it;
     // otherwise start at the front of the input string. everything
     // before the delimiter is assumed to be basic code points.
     uint cnt = delimiterPos + 1;
     // loop through the rest of the input string, inserting non-basic
     // characters into output as we go.
     while (cnt < (uint) pc.size()) {
         uint oldi = i;
         uint w = 1;
         // find the next index for inserting a non-basic character.
         for (uint k = base; cnt < (uint) pc.size(); k += base) {
             // grab a character from the punycode input and find its
             // delta digit (each digit code is part of the
             // variable-length integer delta)
             uint digit = pc.at(cnt++);
             if (digit - 48 < 10) digit -= 22;
             else if (digit - 65 < 26) digit -= 65;
             else if (digit - 97 < 26) digit -= 97;
             else digit = base;
             // reject out of range digits
             if (digit >= base || digit > (Q_MAXINT - i) / w)
                 return QLatin1String("");
             i += (digit * w);
             // detect threshold to stop reading delta digits
             uint t;
             if (k <= bias) t = tmin;
             else if (k >= bias + tmax) t = tmax;
             else t = k - bias;
             if (digit < t) break;
             w *= (base - t);
         }
         // find new bias and calculate the next non-basic code
         // character.
         bias = adapt(i - oldi, output.length() + 1, oldi == 0);
         n += i / (output.length() + 1);
         // allow the deltas to wrap around
         i %= (output.length() + 1);
         // insert the character n at position i
         output.insert((uint) i, QChar((ushort) n));
         ++i;
     }
     return output;
 }
fromUserInput()
QUrl QUrl::fromUserInput (const QString & userInput) static
Returns a valid URL from a user supplied userInput string if one can be deducted.
In the case that is not possible, an invalid QUrl() is returned.
Since
4.6
Most applications that can browse the web, allow the user to input a URL in the form of a plain string. This string can be manually typed into a location bar, obtained from the clipboard, or passed in via command line arguments.
When the string is not already a valid URL, a best guess is performed, making various web related assumptions.
In the case the string corresponds to a valid file path on the system, a file:// URL is constructed, using QUrl::fromLocalFile().
If that is not the case, an attempt is made to turn the string into a http:// or ftp:// URL. The latter in the case the string starts with 'ftp'. The result is then passed through QUrl's tolerant parser, and in the case or success, a valid QUrl is returned, or else a QUrl().
:
Examples:
qt.nokia.com becomes http://qt.nokia.com
ftp.qt.nokia.com becomes ftp://ftp.qt.nokia.com
hostname becomes http://hostname
/home/user/test.html becomes file:///home/user/test.html
Definition at line 6878 of file qurl.cpp.
 {
     QString trimmedString = userInput.trimmed();
     // Check first for files, since on Windows drive letters can be interpretted as schemes
     if (QDir::isAbsolutePath(trimmedString))
         return QUrl::fromLocalFile(trimmedString);
     QUrl url = QUrl::fromEncoded(trimmedString.toUtf8(), QUrl::TolerantMode);
     QUrl urlPrepended = QUrl::fromEncoded("http://" + trimmedString.toUtf8(), QUrl::TolerantMode);
     // Check the most common case of a valid url with a scheme
     // We check if the port would be valid by adding the scheme to handle the case host:port
     // where the host would be interpretted as the scheme
     if (url.isValid()
         && !url.scheme().isEmpty()
         && urlPrepended.port() == -1)
         return url;
     // Else, try the prepended one and adjust the scheme from the host name
     if (urlPrepended.isValid() && (!urlPrepended.host().isEmpty() || !urlPrepended.path().isEmpty()))
     {
         int dotIndex = trimmedString.indexOf(QLatin1Char('.'));
         const QString hostscheme = trimmedString.left(dotIndex).toLower();
         if (hostscheme == QLatin1String("ftp"))
             urlPrepended.setScheme(QLatin1String("ftp"));
         return urlPrepended;
     }
     return QUrl();
 }
hasEncodedQueryItem()
bool QUrl::hasEncodedQueryItem (const QByteArray & key) const
Returns true if there is a query string pair whose key is equal to key from the URL.
Since
4.4
Note: if the encoded key does not match the encoded version of the query, this function will return false. That is, if the encoded query of this URL is "search=Qt%20Rules", calling this function with key = "%73earch" will return false.
See also
hasQueryItem()
Definition at line 5394 of file qurl.cpp.
Referenced by hasQueryItem().
 {
     if (!d) return false;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         if (key == QByteArray::fromRawData(query + pos, valuedelim - pos))
             return true;
         pos = end + 1;
     }
     return false;
 }
hasFragment()
bool QUrl::hasFragment () const
Returns true if this URL contains a fragment (i.
Since
4.2
e., if # was seen on it).
\sa fragment(), setFragment()
Definition at line 5773 of file qurl.cpp.
Referenced by QTextDocument::loadResource(), and QTextBrowserPrivate::resolveUrl().
 {
     if (!d) return false;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->hasFragment;
 }
hasQuery()
bool QUrl::hasQuery () const
Returns true if this URL contains a Query (i.
Since
4.2
e., if ? was seen on it).
\sa hasQueryItem(), encodedQuery()
Definition at line 5058 of file qurl.cpp.
Referenced by QHttpNetworkRequestPrivate::header().
 {
     if (!d) return false;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->hasQuery;
 }
hasQueryItem()
bool QUrl::hasQueryItem (const QString & key) const
Returns true if there is a query string pair whose key is equal to key from the URL.
See also
hasEncodedQueryItem()
Definition at line 5372 of file qurl.cpp.
 {
     if (!d) return false;
     return hasEncodedQueryItem(toPercentEncoding(key, queryExcludeChars));
 }
host()
QString QUrl::host () const
Returns the host of the URL if it is defined; otherwise an empty string is returned.
Definition at line 4837 of file qurl.cpp.
Referenced by QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), QNetworkCookieJar::cookiesForUrl(), encodedHost(), QDeclarativeEnginePrivate::getImageFromProvider(), QDeclarativeEnginePrivate::getImageProviderType(), QDeclarativeEnginePrivate::getPixmapFromProvider(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), QNetworkProxyQuery::peerHostName(), QGlobalNetworkProxy::proxyForQuery(), qDecodeDataUrl(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QNetworkCookieJar::setCookiesFromUrl(), setHost(), QNetworkAccessBackend::start(), QHttpThreadDelegate::startRequest(), and topLevelDomain().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     QString result = d->canonicalHost();
     if (result.startsWith(QLatin1Char('[')))
         return result.mid(1, result.length() - 2);
     return result;
 }
idnWhitelist()
QStringList QUrl::idnWhitelist () static
Returns the current whitelist of top-level domains that are allowed to have non-ASCII characters in their compositions.
Since
4.2
See setIdnWhitelist() for the rationale of this list.
Definition at line 6175 of file qurl.cpp.
 {
     if (user_idn_whitelist)
         return *user_idn_whitelist;
     QStringList list;
     unsigned int i = 0;
     while (i < sizeof(idn_whitelist)/sizeof(const char *)) {
         list << QLatin1String(idn_whitelist[i]);
         ++i;
     }
     return list;
 }
isDetached()
bool QUrl::isDetached () const
Warning
This function is not part of the public interface.
Definition at line 6356 of file qurl.cpp.
 {
     return !d || d->ref == 1;
 }
isEmpty()
bool QUrl::isEmpty () const
Returns true if the URL has no data; otherwise returns false.
Definition at line 4317 of file qurl.cpp.
Referenced by QNetworkAccessManagerPrivate::authenticationRequired(), QDeclarativeContext::baseUrl(), QDeclarativeConnections::connectSignals(), QNetworkAccessFileBackendFactory::create(), QDeclarativeBinding::createBinding(), QHttpNetworkConnectionChannel::ensureConnection(), QDeclarativeInclude::include(), QDeclarativeDataLoader::load(), QTextDocument::loadResource(), QDeclarativeComponent::loadUrl(), QPatternist::XPathHelper::normalizeQueryURI(), operator==(), QPatternist::AccelTree::printStats(), QDeclarativeContextData::resolvedUrl(), QDeclarativeImports::resolveType(), QXmlQuery::setFocus(), QXmlQuery::setQuery(), QDeclarativeImageBase::setSource(), QDeclarativeBorderImage::setSource(), QDeclarativeParticles::setSource(), toLocalFile(), toUrl(), QDeclarativeBinding::update(), QDeclarativePropertyPrivate::write(), QPatternist::XQueryTokenizer::XQueryTokenizer(), and QDeclarativeInfo::~QDeclarativeInfo().
 {
     if (!d) return true;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed))
         return d->encodedOriginal.isEmpty();
     else
         return d->scheme.isEmpty()   // no encodedScheme
         && d->userName.isEmpty() && d->encodedUserName.isEmpty()
         && d->password.isEmpty() && d->encodedPassword.isEmpty()
         && d->host.isEmpty()   // no encodedHost
         && d->port == -1
         && d->path.isEmpty() && d->encodedPath.isEmpty()
         && d->query.isEmpty()
         && d->fragment.isEmpty() && d->encodedFragment.isEmpty();
 }
isLocalFile()
bool QUrl::isLocalFile () const
Returns true if this URL is pointing to a local file path.
Since
4.8 A URL is a local file path if the scheme is "file".
Note that this function considers URLs with hostnames to be local file paths, even if the eventual file path cannot be opened with QFile::open().
See also
fromLocalFile(), toLocalFile()
Definition at line 6453 of file qurl.cpp.
Referenced by QNetworkAccessFileBackendFactory::create(), QNetworkAccessManager::createRequest(), and toLocalFile().
 {
     if (!d) return false;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     if (d->scheme.compare(QLatin1String("file"), Qt::CaseInsensitive) != 0)
         return false;   // not file
     return true;
 }
isParentOf()
bool QUrl::isParentOf (const QUrl & childUrl) const
Returns true if this URL is a parent of childUrl.
childUrl is a child of this URL if the two URLs share the same scheme and authority, and this URL's path is a parent of the path of childUrl.
Definition at line 6469 of file qurl.cpp.
 {
     QString childPath = childUrl.path();
     if (!d)
         return ((childUrl.scheme().isEmpty())
             && (childUrl.authority().isEmpty())
             && childPath.length() > 0 && childPath.at(0) == QLatin1Char('/'));
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     lock.unlock();
     QString ourPath = path();
     return ((childUrl.scheme().isEmpty() || scheme() == childUrl.scheme())
             && (childUrl.authority().isEmpty() || authority() == childUrl.authority())
             &&  childPath.startsWith(ourPath)
             && ((ourPath.endsWith(QLatin1Char('/')) && childPath.length() > ourPath.length())
                 || (!ourPath.endsWith(QLatin1Char('/'))
                     && childPath.length() > ourPath.length() && childPath.at(ourPath.length()) == QLatin1Char('/'))));
 }
isRelative()
bool QUrl::isRelative () const
Returns true if the URL is relative; otherwise returns false.
A URL is relative if its scheme is undefined; this function is therefore equivalent to calling scheme().isEmpty().
Definition at line 5880 of file qurl.cpp.
Referenced by QTextBrowserPrivate::_q_activateAnchor(), QDeclarativeImportDatabase::addImportPath(), QDeclarativeImportDatabase::addPluginPath(), QPatternist::ResourceLoader::announceCollection(), QPatternist::AccelTreeResourceLoader::announceDocument(), QPatternist::ResourceLoader::announceDocument(), QPatternist::ResourceLoader::announceUnparsedText(), QPatternist::GenericStaticContext::baseURI(), QDeclarativeEnginePrivate::createQmlObject(), QPatternist::DocAvailableFN::evaluateEBV(), QPatternist::DocFN::evaluateSingleton(), QPatternist::GenericStaticContext::GenericStaticContext(), QDeclarativeTypeLoader::get(), QDeclarativeTypeLoader::getQmldir(), QDeclarativeTypeLoader::getScript(), QDeclarativeInclude::include(), QPatternist::ResourceLoader::isDocumentAvailable(), QPatternist::ResourceLoader::isUnparsedTextAvailable(), QTextDocument::loadResource(), QDeclarativeComponent::loadUrl(), navigatorInvoke(), QPatternist::XPathHelper::normalizeQueryURI(), QPatternist::ResourceLoader::openCollection(), QPatternist::ResourceLoader::openDocument(), QPatternist::ResourceLoader::openUnparsedText(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseRedefine(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), qmlxmlhttprequest_open(), registerComponent(), QPatternist::resolveAndCheckCollation(), QDeclarativeContextData::resolvedUrl(), QPatternist::ReportContext::resolveURI(), QTextBrowserPrivate::resolveUrl(), QPatternist::GenericStaticContext::setBaseURI(), QDeclarativeParticles::setSource(), QPatternist::StaticBaseURIContext::StaticBaseURIContext(), swap(), toUrl(), QPatternist::XsdValidatingInstanceReader::validate(), QDeclarativePropertyPrivate::write(), and QPatternist::yyparse().
 {
     if (!d) return true;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->scheme.isEmpty();
 }
isValid()
bool QUrl::isValid () const
Returns true if the URL is valid; otherwise returns false.
The URL is run through a conformance test. Every part of the URL must conform to the standard encoding rules of the URI standard for the URL to be reported as valid.
bool checkUrl(const QUrl &url) {
    if (!url.isValid()) {
        qDebug(QString("Invalid URL: %1").arg(url.toString()));
        return false;
    }
    return true;
}
Definition at line 4303 of file qurl.cpp.
Referenced by QUrlModel::addUrls(), QPatternist::ResourceLoader::announceCollection(), QPatternist::AccelTreeResourceLoader::announceDocument(), QPatternist::ResourceLoader::announceDocument(), QPatternist::ResourceLoader::announceUnparsedText(), QNetworkDiskCachePrivate::cacheFileName(), QNetworkAccessHttpBackend::checkForRedirect(), QDeclarativeFolderListModel::componentComplete(), QPatternist::ExpressionFactory::createExpression(), QDeclarativeEnginePrivate::createQmlObject(), QNetworkDiskCache::data(), QDeclarativeWorkerScript::engine(), QPatternist::DocFN::evaluateSingleton(), fromUserInput(), QPatternist::ResourceLoader::isDocumentAvailable(), QSourceLocation::isNull(), QPatternist::ResourceLoader::isUnparsedTextAvailable(), launchWebBrowser(), QPatternist::AccelTreeResourceLoader::load(), lsOpen(), navigatorInvoke(), QPatternist::XPathHelper::normalizeQueryURI(), QPatternist::ResourceLoader::openCollection(), openDocument(), QPatternist::ResourceLoader::openDocument(), QPatternist::ResourceLoader::openUnparsedText(), parseHeaderValue(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseRedefine(), QNetworkDiskCache::prepare(), QDeclarativeContextData::resolvedUrl(), QPatternist::AccelTreeResourceLoader::retrieveDocument(), QXmlQuery::setFocus(), QFileDialogComboBox::setHistory(), QXmlQuery::setQuery(), QTextBrowser::setSource(), QTextBrowserPrivate::setSource(), QFileDialogComboBox::showPopup(), QPatternist::StaticBaseURIContext::StaticBaseURIContext(), QNetworkProxyFactory::systemProxyForQuery(), QPatternist::Tokenizer::Tokenizer(), QPatternist::XsdValidatingInstanceReader::validate(), and QPatternist::XQueryTokenizer::XQueryTokenizer().
 {
     if (!d) return false;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Validated)) d->validate();
     return d->isValid && d->isHostValid;
 }
operator!=()
bool QUrl::operator!= (const QUrl & url) const
Returns true if this URL and the given url are not equal; otherwise returns false.
Definition at line 6256 of file qurl.cpp.
 {
     return !(*this == url);
 }
operator<()
bool QUrl::operator< (const QUrl & url) const
Returns true if this URL is "less than" the given url.
Warning
This function is not part of the public interface.
This provides a means of ordering URLs.
Definition at line 6228 of file qurl.cpp.
 {
     QOrderedMutexLocker(d ? &d->mutex : 0, url.d ? &url.d->mutex : 0);
     if (!d) return url.d ? QByteArray() < url.d->normalized() : false;
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     if (!url.d) return d->normalized() < QByteArray();
     if (!QURL_HASFLAG(url.d->stateFlags, QUrlPrivate::Parsed)) url.d->parse();
     return d->normalized() < url.d->normalized();
 }
operator=() [1/2]
QUrl & QUrl::operator= (const QUrl & copy)
Assigns the specified url to this object.
Definition at line 6264 of file qurl.cpp.
 {
     if (!d) {
         if (url.d) {
             url.d->ref.ref();
             d = url.d;
         }
     } else {
         if (url.d)
             qAtomicAssign(d, url.d);
         else
             clear();
     }
     return *this;
 }
operator=() [2/2]
QUrl & QUrl::operator= (const QString & url)
Assigns the specified url to this object.
Definition at line 6283 of file qurl.cpp.
 {
     if (url.isEmpty()) {
         clear();
     } else {
         QUrl tmp(url);
         if (!d) d = new QUrlPrivate;
         qAtomicAssign(d, tmp.d);
     }
     return *this;
 }
operator==()
bool QUrl::operator== (const QUrl & url) const
Returns true if this URL and the given url are equal; otherwise returns false.
Definition at line 6242 of file qurl.cpp.
 {
     if (!d) return url.isEmpty();
     if (!url.d) return isEmpty();
     QOrderedMutexLocker(&d->mutex, &url.d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     if (!QURL_HASFLAG(url.d->stateFlags, QUrlPrivate::Parsed)) url.d->parse();
     return d->normalized() == url.d->normalized();
 }
password()
QString QUrl::password () const
Returns the password of the URL if it is defined; otherwise an empty string is returned.
See also
setPassword()
Definition at line 4754 of file qurl.cpp.
Referenced by QNetworkAccessManagerPrivate::authenticationRequired(), QNetworkAccessAuthenticationManager::fetchCachedCredentials(), QNetworkAccessFtpBackend::open(), QHttpNetworkConnectionChannel::sendRequest(), setEncodedPassword(), and setPassword().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     d->userInfo();              // causes the unencoded form to be set
     return d->password;
 }
path()
QString QUrl::path () const
Returns the path of the URL.
See also
setPath()
Definition at line 4977 of file qurl.cpp.
Referenced by QTextBrowserPrivate::_q_documentModified(), QDeclarativeCompiler::buildDynamicMeta(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), QNetworkCookieJar::cookiesForUrl(), QDragManager::drag(), QNetworkAccessAuthenticationManager::fetchCachedCredentials(), QTextBrowserPrivate::findFile(), QNetworkAccessFtpBackend::ftpDone(), isParentOf(), QTextDocument::loadResource(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QUrlInfo::QUrlInfo(), readImage(), QSidebar::removeEntry(), QTextBrowserPrivate::resolveUrl(), QNetworkCookieJar::setCookiesFromUrl(), setEncodedPath(), QDeclarativeFolderListModel::setFolder(), setPath(), QUrlModel::setUrl(), toLocalFile(), toString(), QHttpNetworkRequestPrivate::uri(), and QDeclarativeEnginePrivate::urlToLocalFileOrQrc().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     if (d->path.isNull()) {
         QUrlPrivate *that = const_cast<QUrlPrivate *>(d);
         that->path = fromPercentEncodingHelper(d->encodedPath);
     }
     return d->path;
 }
port() [1/2]
int QUrl::port () const
Returns the port of the URL, or -1 if the port is unspecified.
Definition at line 4916 of file qurl.cpp.
Referenced by makeCacheKey(), QNetworkAccessFtpBackend::open(), QNetworkProxyQuery::peerPort(), QHttpNetworkConnectionPrivate::prepareRequest(), setPort(), and QHttpThreadDelegate::startRequest().
 {
     if (!d) return -1;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Validated)) d->validate();
     return d->port;
 }
port() [2/2]
int QUrl::port (int defaultPort) const
Returns the port of the URL, or defaultPort if the port is unspecified.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.1
Example:
QFtp ftp;
ftp.connectToHost(url.host(), url.port(21));
Definition at line 4939 of file qurl.cpp.
 {
     if (!d) return defaultPort;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->port == -1 ? defaultPort : d->port;
 }
queryItems()
QList< QPair< QString, QString > > QUrl::queryItems () const
Returns the query string of the URL, as a map of keys and values.
Note
This method does not decode spaces plus (+) signs as spaces (ASCII 0x20), like HTML forms do. If you need that kind of decoding, you must use QUrl::encodedQueryItems and decode the data yourself.
See also
setQueryItems(), setEncodedQuery()
Definition at line 5305 of file qurl.cpp.
 {
     if (!d) return QList<QPair<QString, QString> >();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     QList<QPair<QString, QString> > itemMap;
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         QByteArray q(query + pos, valuedelim - pos);
         if (valuedelim < end) {
             QByteArray v(query + valuedelim + 1, end - valuedelim - 1);
             itemMap += qMakePair(fromPercentEncodingMutable(&q),
                                  fromPercentEncodingMutable(&v));
         } else {
             itemMap += qMakePair(fromPercentEncodingMutable(&q), QString());
         }
         pos = end + 1;
     }
     return itemMap;
 }
queryItemValue()
QString QUrl::queryItemValue (const QString & key) const
Returns the first query string value whose key is equal to key from the URL.
Note
This method does not decode spaces plus (+) signs as spaces (ASCII 0x20), like HTML forms do. If you need that kind of decoding, you must use QUrl::encodedQueryItemValue and decode the data yourself.
See also
allQueryItemValues()
Definition at line 5422 of file qurl.cpp.
 {
     if (!d) return QString();
     QByteArray tmp = encodedQueryItemValue(toPercentEncoding(key, queryExcludeChars));
     return fromPercentEncodingMutable(&tmp);
 }
queryPairDelimiter()
char QUrl::queryPairDelimiter () const
Returns the character used to delimit between key-value pairs in the query string of the URL.
Definition at line 5103 of file qurl.cpp.
 {
     if (!d) return '&';
     return d->pairDelimiter;
 }
queryValueDelimiter()
char QUrl::queryValueDelimiter () const
Returns the character used to delimit between keys and values in the query string of the URL.
Definition at line 5113 of file qurl.cpp.
 {
     if (!d) return '=';
     return d->valueDelimiter;
 }
removeAllEncodedQueryItems()
void QUrl::removeAllEncodedQueryItems (const QByteArray & key)
Removes all the query string pairs whose key is equal to key from the URL.
Since
4.4
Note: if the encoded key does not match the encoded version of the query, this function will not work. That is, if the encoded query of this URL is "search=Qt%20Rules", calling this function with key = "%73earch" will do nothing.
See also
removeQueryItem()
Definition at line 5617 of file qurl.cpp.
Referenced by removeAllQueryItems().
 {
     if (!d) return;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         if (key == QByteArray::fromRawData(query + pos, valuedelim - pos)) {
             if (end < d->query.size())
                 ++end; // remove additional '%'
             d->query.remove(pos, end - pos);
             query = d->query.constData(); //required if remove detach;
         } else {
             pos = end + 1;
         }
     }
 }
removeAllQueryItems()
void QUrl::removeAllQueryItems (const QString & key)
Removes all the query string pairs whose key is equal to key from the URL.
See also
removeQueryItem()
Definition at line 5595 of file qurl.cpp.
 {
     if (!d) return;
     removeAllEncodedQueryItems(toPercentEncoding(key, queryExcludeChars));
 }
removeEncodedQueryItem()
void QUrl::removeEncodedQueryItem (const QByteArray & key)
Removes the first query string pair whose key is equal to key from the URL.
Since
4.4
Note: if the encoded key does not match the encoded version of the query, this function will not work. That is, if the encoded query of this URL is "search=Qt%20Rules", calling this function with key = "%73earch" will do nothing.
See also
removeQueryItem(), removeAllQueryItems()
Definition at line 5567 of file qurl.cpp.
Referenced by removeQueryItem().
 {
     if (!d) return;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     int pos = 0;
     const char *query = d->query.constData();
     while (pos < d->query.size()) {
         int valuedelim, end;
         d->queryItem(pos, &valuedelim, &end);
         if (key == QByteArray::fromRawData(query + pos, valuedelim - pos)) {
             if (end < d->query.size())
                 ++end; // remove additional '%'
             d->query.remove(pos, end - pos);
             return;
         }
         pos = end + 1;
     }
 }
removeQueryItem()
void QUrl::removeQueryItem (const QString & key)
Removes the first query string pair whose key is equal to key from the URL.
See also
removeAllQueryItems()
Definition at line 5545 of file qurl.cpp.
 {
     if (!d) return;
     removeEncodedQueryItem(toPercentEncoding(key, queryExcludeChars));
 }
resolved()
QUrl QUrl::resolved (const QUrl & relative) const
Returns the result of the merge of this URL with relative.
This URL is used as a base to convert relative to an absolute URL.
If relative is not a relative URL, this function will return relative directly. Otherwise, the paths of the two URLs are merged, and the new URL returned has the scheme and authority of the base URL, but with the merged path, as in the following example:
QUrl baseUrl("http://qt.nokia.com/support");
QUrl relativeUrl("../products/solutions");
qDebug(baseUrl.resolved(relativeUrl).toString());
// prints "http://qt.nokia.com/products/solutions"
Calling resolved() with ".." returns a QUrl whose directory is one level higher than the original. Similarly, calling resolved() with "../.." removes two levels from the path. If relative is "/", the path becomes "/".
See also
isRelative()
Definition at line 5819 of file qurl.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QDeclarativeImportsPrivate::add(), QPatternist::AccelTree::baseUri(), QDeclarativeTypeData::dataReceived(), QDeclarativeImportsPrivate::find(), QDeclarativeImportedNamespace::find_helper(), QDeclarativeInclude::finished(), QDeclarativeXMLHttpRequest::finished(), QDeclarativeCompiler::genLiteralAssignment(), QDeclarativeInclude::include(), QTextDocument::loadResource(), QDeclarativeDataLoader::networkReplyFinished(), QDeclarativePixmapReader::networkRequestDone(), QPatternist::XsdSchemaParser::parseImport(), QPatternist::XsdSchemaParser::parseInclude(), QPatternist::XsdSchemaParser::parseRedefine(), QDeclarativeFontObject::replyFinished(), QDeclarativeScriptEngine::resolvedUrl(), QDeclarativeContextData::resolvedUrl(), QDeclarativeTypeData::resolveTypes(), QPatternist::AnyURI::resolveURI(), QPatternist::ReportContext::resolveURI(), QTextBrowserPrivate::resolveUrl(), QTextBrowserPrivate::setSource(), toUrl(), QPatternist::StaticBaseURIStore::typeCheck(), QPatternist::XsdValidatingInstanceReader::validate(), QDeclarativeInclude::worker_include(), and QPatternist::yyparse().
 {
     if (!d) return relative;
     if (!relative.d) return *this;
     QOrderedMutexLocker locker(&d->mutex, &relative.d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     if (!QURL_HASFLAG(relative.d->stateFlags, QUrlPrivate::Parsed))
         relative.d->parse();
     d->ensureEncodedParts();
     relative.d->ensureEncodedParts();
     QUrl t;
     // be non strict and allow scheme in relative url
     if (!relative.d->scheme.isEmpty() && relative.d->scheme != d->scheme) {
         t = relative;
         // t.detach(locker) would unlock, so bypass it
         qAtomicDetach(t.d);
     } else {
         if (!relative.d->authority().isEmpty()) {
             t = relative;
             qAtomicDetach(t.d);
         } else {
             t.d = new QUrlPrivate;
             if (relative.d->encodedPath.isEmpty()) {
                 t.d->encodedPath = d->encodedPath;
                 t.d->query = relative.d->hasQuery ? relative.d->query : d->query;
             } else {
                 t.d->encodedPath = relative.d->encodedPath.at(0) == '/'
                                        ? relative.d->encodedPath
                                        : d->mergePaths(relative.d->encodedPath);
                 t.d->query = relative.d->query;
             }
             t.d->hasQuery = !t.d->query.isNull();
             t.d->encodedUserName = d->encodedUserName;
             t.d->encodedPassword = d->encodedPassword;
             t.d->host = d->host;
             t.d->port = d->port;
         }
         t.setScheme(d->scheme);
     }
     t.setFragment(relative.d->fragmentImpl());
     removeDotsFromPath(&t.d->encodedPath);
     t.d->path.clear();
 #if defined(QURL_DEBUG)
     qDebug("QUrl(\"%s\").resolved(\"%s\") = \"%s\"",
            d->toEncoded().constData(),
            relative.d->toEncoded().constData(),
            t.toEncoded().constData());
 #endif
     return t;
 }
scheme()
QString QUrl::scheme () const
Returns the scheme of the URL.
If an empty string is returned, this means the scheme is undefined and the URL is then relative.
See also
setScheme(), isRelative()
Definition at line 4550 of file qurl.cpp.
Referenced by QTextBrowserPrivate::_q_activateAnchor(), QNetworkReplyImplPrivate::_q_startOperation(), QDeclarativeImportDatabase::addImportPath(), QDeclarativeImportDatabase::addPluginPath(), QUrlModel::addUrls(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QNetworkCookieJar::cookiesForUrl(), QNetworkAccessFileBackendFactory::create(), QNetworkAccessFtpBackendFactory::create(), QNetworkAccessHttpBackendFactory::create(), createPixmapDataSync(), QNetworkAccessManager::createRequest(), QTextBrowserPrivate::findFile(), QDeclarativeXMLHttpRequest::finished(), fromUserInput(), QWindowsSystemProxy::init(), isParentOf(), launchWebBrowser(), QDeclarativePixmap::load(), QTextDocument::loadResource(), QDeclarativeComponent::loadUrl(), lsOpen(), makeCacheKey(), QNetworkAccessFileBackend::open(), QDesktopServices::openUrl(), parseHeaderValue(), QNetworkAccessHttpBackend::postRequest(), QDeclarativePixmapReader::processJob(), QNetworkProxyQuery::protocolTag(), proxyAuthenticationKey(), qDecodeDataUrl(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), registerComponent(), resolveScheme(), QTextBrowserPrivate::resolveUrl(), setScheme(), QNetworkProxyFactory::systemProxyForQuery(), toLocalFile(), and QDeclarativeEnginePrivate::urlToLocalFileOrQrc().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->scheme;
 }
setAuthority()
void QUrl::setAuthority (const QString & authority)
Sets the authority of the URL to authority.
The authority of a URL is the combination of user info, a host name and a port. All of these elements are optional; an empty authority is therefore valid.
The user info and host are separated by a '@', and the host and port are separated by a ':'. If the user info is empty, the '@' must be omitted; although a stray ':' is permitted if the port is empty.
The following example shows a valid authority string:
Definition at line 4575 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized | QUrlPrivate::HostCanonicalized);
     d->setAuthority(authority);
 }
setEncodedFragment()
void QUrl::setEncodedFragment (const QByteArray & fragment)
Sets the URL's fragment to the percent-encoded fragment.
Since
4.4
The fragment is the last part of the URL, represented by a '#' followed by a string of characters. It is typically used in HTTP for referring to a certain link or point on a page:
The fragment is sometimes also referred to as the URL "reference".
Passing an argument of QByteArray() (a null QByteArray) will unset the fragment. Passing an argument of QByteArray("") (an empty but not null QByteArray) will set the fragment to an empty string (as if the original URL had a lone "#").
See also
setFragment(), encodedFragment()
Definition at line 5727 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->encodedFragment = fragment;
     d->hasFragment = !fragment.isNull();
     d->fragment.clear();
 }
setEncodedHost()
void QUrl::setEncodedHost (const QByteArray & host)
Sets the URL's host to the ACE- or percent-encoded host.
Since
4.4
The host is part of the user info element in the authority of the URL, as described in setAuthority().
See also
setHost(), encodedHost(), setAuthority(), fromAce()
Definition at line 4861 of file qurl.cpp.
 {
     setHost(fromPercentEncodingHelper(host));
 }
setEncodedPassword()
void QUrl::setEncodedPassword (const QByteArray & password)
Sets the URL's password to the percent-encoded password.
Since
4.4
The password is part of the user info element in the authority of the URL, as described in setUserInfo().
Note: this function does not verify that password is properly encoded. It is the caller's responsibility to ensure that the any delimiters (such as colons or slashes) are properly encoded.
See also
setPassword(), encodedPassword(), setUserInfo()
Definition at line 4780 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->encodedPassword = password;
     d->password.clear();
 }
setEncodedPath()
void QUrl::setEncodedPath (const QByteArray & path)
Sets the URL's path to the percent-encoded path.
Since
4.4
The path is the part of the URL that comes after the authority but before the query string.
For non-hierarchical schemes, the path will be everything following the scheme declaration, as in the following example:
Note: this function does not verify that path is properly encoded. It is the caller's responsibility to ensure that the any delimiters (such as '?' and '#') are properly encoded.
See also
setPath(), encodedPath(), setUserInfo()
Definition at line 5013 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->encodedPath = path;
     d->path.clear();
 }
setEncodedQuery()
void QUrl::setEncodedQuery (const QByteArray & query)
Sets the query string of the URL to query.
The string is inserted as-is, and no further encoding is performed when calling toEncoded().
This function is useful if you need to pass a query string that does not fit into the key-value pattern, or that uses a different scheme for encoding special characters than what is suggested by QUrl.
Passing a value of QByteArray() to query (a null QByteArray) unsets the query completely. However, passing a value of QByteArray("") will set the query to an empty value, as if the original URL had a lone "?".
See also
encodedQuery(), hasQuery()
Definition at line 5136 of file qurl.cpp.
Referenced by makeCacheKey().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->query = query;
     d->hasQuery = !query.isNull();
 }
setEncodedQueryItems()
void QUrl::setEncodedQueryItems (const QList< QPair< QByteArray, QByteArray > > & query)
Sets the query string of the URL to the encoded version of query.
Since
4.4
The contents of query are converted to a string internally, each pair delimited by the character returned by pairDelimiter(), and the key and value are delimited by valueDelimiter().
Note: this function does not verify that the key-value pairs are properly encoded. It is the caller's responsibility to ensure that the query delimiters are properly encoded, if any.
See also
setQueryDelimiters(), encodedQueryItems(), setQueryItems()
Definition at line 5205 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QByteArray queryTmp;
     for (int i = 0; i < query.size(); i++) {
         if (i) queryTmp += d->pairDelimiter;
         queryTmp += query.at(i).first;
         queryTmp += d->valueDelimiter;
         queryTmp += query.at(i).second;
     }
     d->query = queryTmp;
     d->hasQuery = !query.isEmpty();
 }
setEncodedUrl() [1/2]
void QUrl::setEncodedUrl (const QByteArray & encodedUrl)
Constructs a URL by parsing the contents of encodedUrl.
encodedUrl is assumed to be a URL string in percent encoded form, containing only ASCII characters.
Use isValid() to determine if a valid URL was constructed.
See also
setUrl()
Definition at line 4429 of file qurl.cpp.
Referenced by fromEncoded().
 {
     setEncodedUrl(encodedUrl, TolerantMode);
 }
setEncodedUrl() [2/2]
void QUrl::setEncodedUrl (const QByteArray & url, ParsingMode mode)
Constructs a URL by parsing the contents of encodedUrl using the given parsingMode.
Definition at line 4449 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     detach(lock);
     d->clear();
     d->setEncodedUrl(encodedUrl, parsingMode);
 }
setEncodedUserName()
void QUrl::setEncodedUserName (const QByteArray & userName)
Sets the URL's user name to the percent-encoded userName.
Since
4.4
The userName is part of the user info element in the authority of the URL, as described in setUserInfo().
Note: this function does not verify that userName is properly encoded. It is the caller's responsibility to ensure that the any delimiters (such as colons or slashes) are properly encoded.
See also
setUserName(), encodedUserName(), setUserInfo()
Definition at line 4694 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->encodedUserName = userName;
     d->userName.clear();
 }
setFragment()
void QUrl::setFragment (const QString & fragment)
Sets the fragment of the URL to fragment.
The fragment is the last part of the URL, represented by a '#' followed by a string of characters. It is typically used in HTTP for referring to a certain link or point on a page:
The fragment is sometimes also referred to as the URL "reference".
Passing an argument of QString() (a null QString) will unset the fragment. Passing an argument of QString("") (an empty but not null QString) will set the fragment to an empty string (as if the original URL had a lone "#").
See also
fragment(), hasFragment()
Definition at line 5669 of file qurl.cpp.
Referenced by authenticationKey(), QPatternist::ReportContext::codeFromURI(), proxyAuthenticationKey(), qmlxmlhttprequest_open(), resolved(), QTextBrowserPrivate::setSource(), QNetworkCacheMetaData::setUrl(), and QNetworkDiskCachePrivate::uniqueFileName().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->fragment = fragment;
     d->hasFragment = !fragment.isNull();
     d->encodedFragment.clear();
 }
setHost()
void QUrl::setHost (const QString & host)
Sets the host of the URL to host.
The host is part of the authority.
See also
host(), setAuthority()
Definition at line 4821 of file qurl.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), fromLocalFile(), makeCacheKey(), QNetworkAccessFileBackend::open(), proxyAuthenticationKey(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), setEncodedHost(), QNetworkProxyQuery::setPeerHostName(), and QNetworkProxyFactory::systemProxyForQuery().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     d->isHostValid = true;
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized | QUrlPrivate::HostCanonicalized);
     d->host = host;
 }
setIdnWhitelist()
void QUrl::setIdnWhitelist (const QStringList & list) static
Sets the whitelist of Top-Level Domains (TLDs) that are allowed to have non-ASCII characters in domains to the value of list.
Since
4.2
Note that if you call this function, you need to do so before you start any threads that might access idnWhitelist().
Qt has comes a default list that contains the Internet top-level domains that have published support for Internationalized Domain Names (IDNs) and rules to guarantee that no deception can happen between similarly-looking characters (such as the Latin lowercase letter 'a' and the Cyrillic equivalent, which in most fonts are visually identical).
This list is periodically maintained, as registrars publish new rules.
This function is provided for those who need to manipulate the list, in order to add or remove a TLD. It is not recommended to change its value for purposes other than testing, as it may expose users to security risks.
Definition at line 6212 of file qurl.cpp.
 {
     if (!user_idn_whitelist)
         user_idn_whitelist = new QStringList;
     *user_idn_whitelist = list;
 }
setPassword()
void QUrl::setPassword (const QString & password)
Sets the URL's password to password.
The password is part of the user info element in the authority of the URL, as described in setUserInfo().
See also
password(), setUserInfo()
Definition at line 4736 of file qurl.cpp.
Referenced by qmlxmlhttprequest_open(), QNetworkCacheMetaData::setUrl(), and QNetworkDiskCachePrivate::uniqueFileName().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->password = password;
     d->encodedPassword.clear();
 }
setPath()
void QUrl::setPath (const QString & path)
Sets the path of the URL to path.
The path is the part of the URL that comes after the authority but before the query string.
For non-hierarchical schemes, the path will be everything following the scheme declaration, as in the following example:
See also
path()
Definition at line 4960 of file qurl.cpp.
Referenced by QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QMacPasteboardMimeFileUri::convertToMime(), QMacPasteboardMimeUrl::convertToMime(), fromLocalFile(), isParentOf(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), and QNetworkReplyFileImpl::QNetworkReplyFileImpl().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->path = path;
     d->encodedPath.clear();
 }
setPort()
void QUrl::setPort (int port)
Sets the port of the URL to port.
The port is part of the authority of the URL, as described in setAuthority().
port must be between 0 and 65535 inclusive. Setting the port to -1 indicates that the port is unspecified.
Definition at line 4897 of file qurl.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), makeCacheKey(), proxyAuthenticationKey(), QNetworkProxyQuery::setPeerPort(), and QHttpThreadDelegate::startRequest().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     if (port < -1 || port > 65535) {
         qWarning("QUrl::setPort: Out of range");
         port = -1;
     }
     d->port = port;
 }
setQueryDelimiters()
void QUrl::setQueryDelimiters (char valueDelimiter, char pairDelimiter)
Sets the characters used for delimiting between keys and values, and between key-value pairs in the URL's query string.
The default value delimiter is '=' and the default pair delimiter is '&'.
valueDelimiter will be used for separating keys from values, and pairDelimiter will be used to separate key-value pairs. Any occurrences of these delimiting characters in the encoded representation of the keys and values of the query string are percent encoded.
If valueDelimiter is set to '-' and pairDelimiter is '/', the above query string would instead be represented like this:
http://www.example.com/cgi-bin/drawgraph.cgi?type-pie/color-green
Calling this function does not change the delimiters of the current query string. It only affects queryItems(), setQueryItems() and addQueryItems().
Definition at line 5089 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     detach(lock);
     d->valueDelimiter = valueDelimiter;
     d->pairDelimiter = pairDelimiter;
 }
setQueryItems()
void QUrl::setQueryItems (const QList< QPair< QString, QString > > & query)
Sets the query string of the URL to an encoded version of query.
The contents of query are converted to a string internally, each pair delimited by the character returned by pairDelimiter(), and the key and value are delimited by valueDelimiter().
Note
This method does not encode spaces (ASCII 0x20) as plus (+) signs, like HTML forms do. If you need that kind of encoding, you must encode the value yourself and use QUrl::setEncodedQueryItems.
See also
setQueryDelimiters(), queryItems(), setEncodedQueryItems()
Definition at line 5161 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     char alsoEncode[3];
     alsoEncode[0] = d->valueDelimiter;
     alsoEncode[1] = d->pairDelimiter;
     alsoEncode[2] = 0;
     QByteArray queryTmp;
     for (int i = 0; i < query.size(); i++) {
         if (i) queryTmp += d->pairDelimiter;
         // query = *( pchar / "/" / "?" )
         queryTmp += toPercentEncodingHelper(query.at(i).first, queryExcludeChars, alsoEncode);
         queryTmp += d->valueDelimiter;
         // query = *( pchar / "/" / "?" )
         queryTmp += toPercentEncodingHelper(query.at(i).second, queryExcludeChars, alsoEncode);
     }
     d->query = queryTmp;
     d->hasQuery = !query.isEmpty();
 }
setScheme()
void QUrl::setScheme (const QString & scheme)
Sets the scheme of the URL to scheme.
As a scheme can only contain ASCII characters, no conversion or encoding is done on the input.
The scheme describes the type (or protocol) of the URL. It's represented by one or more ASCII characters at the start the URL, and is followed by a ':'. The following example shows a URL where the scheme is "ftp":
The scheme can also be empty, in which case the URL is interpreted as relative.
See also
scheme(), isRelative()
Definition at line 4533 of file qurl.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), fromLocalFile(), QWindowsSystemProxy::init(), QTextDocument::loadResource(), makeCacheKey(), proxyAuthenticationKey(), resolved(), QNetworkProxyQuery::setProtocolTag(), and QNetworkProxyFactory::systemProxyForQuery().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->scheme = scheme;
 }
setUrl() [1/2]
void QUrl::setUrl (const QString & url)
Constructs a URL by parsing the contents of url.
url is assumed to be in unicode format, with no percent encoding.
Calling isValid() will tell whether or not a valid URL was constructed.
See also
setEncodedUrl()
Definition at line 4358 of file qurl.cpp.
Referenced by QUrl().
 {
     setUrl(url, TolerantMode);
 }
setUrl() [2/2]
void QUrl::setUrl (const QString & url, ParsingMode parsingMode)
Parses url using the parsing mode parsingMode.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
See also
setEncodedUrl()
Definition at line 4373 of file qurl.cpp.
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     detach(lock);
     d->clear();
     // escape all reserved characters and delimiters
     // reserved      = gen-delims / sub-delims
     if (parsingMode != TolerantMode) {
         d->setEncodedUrl(toPercentEncodingHelper(url, ABNF_reserved), parsingMode);
         return;
     }
     // Tolerant preprocessing
     QString tmp = url;
     // Allow %20 in the QString variant
     tmp.replace(QLatin1String("%20"), QLatin1String(" "));
     // Percent-encode unsafe ASCII characters after host part
     int start = tmp.indexOf(QLatin1String("//"));
     if (start != -1) {
         // Has host part, find delimiter
         start += 2; // skip "//"
         const char delims[] = "/#?";
         const char *d = delims;
         int hostEnd = -1;
         while (*d && (hostEnd = tmp.indexOf(QLatin1Char(*d), start)) == -1)
             ++d;
         start = (hostEnd == -1) ? -1 : hostEnd + 1;
     } else {
         start = 0; // Has no host part
     }
     QByteArray encodedUrl;
     if (start != -1) {
         QString hostPart = tmp.left(start);
         QString otherPart = tmp.mid(start);
         encodedUrl = toPercentEncodingHelper(hostPart, ":/?#[]@!$&'()*+,;=")
                    + toPercentEncodingHelper(otherPart, ":/?#@!$&'()*+,;=");
     } else {
         encodedUrl = toPercentEncodingHelper(tmp, ABNF_reserved);
     }
     d->setEncodedUrl(encodedUrl, StrictMode);
 }
setUserInfo()
void QUrl::setUserInfo (const QString & userInfo)
Sets the user info of the URL to userInfo.
The user info is an optional part of the authority of the URL, as described in setAuthority().
The user info consists of a user name and optionally a password, separated by a ':'. If the password is empty, the colon must be omitted. The following example shows a valid user info string:
See also
userInfo(), setUserName(), setPassword(), setAuthority()
Definition at line 4615 of file qurl.cpp.
Referenced by QNetworkAccessFtpBackend::ftpDone(), and QHttpNetworkConnectionChannel::sendRequest().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->setUserInfo(userInfo.trimmed());
 }
setUserName()
void QUrl::setUserName (const QString & userName)
Sets the URL's user name to userName.
The userName is part of the user info element in the authority of the URL, as described in setUserInfo().
See also
setEncodedUserName(), userName(), setUserInfo()
Definition at line 4648 of file qurl.cpp.
Referenced by QNetworkAccessAuthenticationManager::cacheCredentials(), QNetworkAccessFtpBackend::ftpDone(), makeCacheKey(), proxyAuthenticationKey(), and qmlxmlhttprequest_open().
 {
     if (!d) d = new QUrlPrivate;
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     detach(lock);
     QURL_UNSETFLAG(d->stateFlags, QUrlPrivate::Validated | QUrlPrivate::Normalized);
     d->userName = userName;
     d->encodedUserName.clear();
 }
swap()
void QUrl::swap (QUrl & other) inline
Swaps URL other with this URL.
Since
4.8
This operation is very fast and never fails.
Definition at line 104 of file qurl.h.
 { qSwap(d, other.d); }
toAce()
QByteArray QUrl::toAce (const QString & domain) static
Returns the ASCII Compatible Encoding of the given domain name domain.
Since
4.2
The result of this function is considered equivalent to domain.
The ASCII-Compatible Encoding (ACE) is defined by RFC 3490, RFC 3491 and RFC 3492. It is part of the Internationalizing Domain Names in Applications (IDNA) specification, which allows for domain names (like "example.com") to be written using international characters.
This function return an empty QByteArra if domain is not a valid hostname. Note, in particular, that IPv6 literals are not valid domain names.
Definition at line 6158 of file qurl.cpp.
Referenced by encodedHost(), QHostInfoAgent::fromName(), QSslSocketBackendPrivate::initSslContext(), QNetworkCookiePrivate::parseSetCookieHeaderLine(), QHttpNetworkConnectionPrivate::prepareRequest(), qt_socks5_set_host_name_and_port(), QHttpSocketEngine::slotSocketConnected(), QUrlPrivate::toEncoded(), QNetworkCookie::toRawForm(), and translateWSAError().
 {
     QString result = qt_ACE_do(domain, ToAceOnly);
     return result.toLatin1();
 }
toEncoded()
QByteArray QUrl::toEncoded (FormattingOptions options = None) const
Returns the encoded representation of the URL if it's valid; otherwise an empty QByteArray is returned.
The output can be customized by passing flags with options.
The user info, path and fragment are all converted to UTF-8, and all non-ASCII characters are then percent encoded. The host name is encoded using Punycode.
Definition at line 5949 of file qurl.cpp.
Referenced by QHttpPrivate::_q_slotSendRequest(), authenticationKey(), QMacPasteboardMimeFileUri::convertFromMime(), QMacPasteboardMimeUrl::convertFromMime(), QHttpThreadDelegate::finishedSlot(), QPatternist::ColoringMessageHandler::handleMessage(), headerValue(), launch(), launchWebBrowser(), lsOpen(), macQueryInternal(), makeCacheKey(), operator<<(), proxyAuthenticationKey(), qDecodeDataUrl(), qHash(), QNetworkReplyDataImpl::QNetworkReplyDataImpl(), resolved(), QMimeDataPrivate::retrieveTypedData(), QHttpThreadDelegate::synchronousFinishedSlot(), QNetworkProxyFactory::systemProxyForQuery(), QTest::toString(), QNetworkDiskCachePrivate::uniqueFileName(), and QHttpNetworkRequestPrivate::uri().
 {
     if (!d) return QByteArray();
     QMutexLocker lock(&d->mutex);
     return d->toEncoded(options);
 }
toLocalFile()
QString QUrl::toLocalFile () const
Returns the path of this URL formatted as a local file path.
The path returned will use forward slashes, even if it was originally created from one with backslashes.
If this URL contains a non-empty hostname, it will be encoded in the returned value in the form found on SMB networks (for example, "//servername/path/to/file.txt").
If this is a relative URL, in Qt 4.x this function returns the path to maintain backward compatability. This will change from 5.0 onwards. Then the path is returned only for URLs where the scheme is "file", and for all other URLs an empty string is returned.
See also
fromLocalFile(), isLocalFile()
Definition at line 6412 of file qurl.cpp.
Referenced by QFileDialogPrivate::_q_goToDirectory(), QFileDialogPrivate::_q_goToUrl(), QUrlModel::addUrls(), QWindowsMimeURI::canConvertFromMime(), QUrlModel::canDrop(), QUrlModel::changed(), QDeclarativeFolderListModel::componentComplete(), QWindowsMimeURI::convertFromMime(), QTextBrowserPrivate::findFile(), QTextDocument::loadResource(), QNetworkAccessFileBackend::open(), openDocument(), QFileOpenEvent::QFileOpenEvent(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QDeclarativeFolderListModel::refresh(), QTextBrowserPrivate::resolveUrl(), QUrlModel::setData(), QDeclarativeFolderListModel::setFolder(), QUrlModel::setUrl(), and QDeclarativeEnginePrivate::urlToLocalFileOrQrc().
 {
     if (!d) return QString();
     // the call to isLocalFile() also ensures that we're parsed
     if (!isLocalFile() && !scheme().isEmpty())
         return QString();
     QString tmp;
     QString ourPath = path();
     QMutexLocker lock(&d->mutex); // for d->host
     // magic for shared drive on windows
     if (!d->host.isEmpty()) {
         tmp = QLatin1String("//") + d->host + (ourPath.length() > 0 && ourPath.at(0) != QLatin1Char('/')
                                                ? QLatin1Char('/') + ourPath :  ourPath);
     } else {
         tmp = ourPath;
         // magic for drives on windows
         if (ourPath.length() > 2 && ourPath.at(0) == QLatin1Char('/') && ourPath.at(2) == QLatin1Char(':'))
             tmp.remove(0, 1);
     }
     return tmp;
 }
toPercentEncoding()
QByteArray QUrl::toPercentEncoding (const QString & input, const QByteArray & exclude = QByteArray(), const QByteArray & include = QByteArray()) static
Returns an encoded copy of input.
input is first converted to UTF-8, and all ASCII-characters that are not in the unreserved group are percent encoded. To prevent characters from being percent encoded pass them to exclude. To force characters to be percent encoded pass them to include.
Unreserved is defined as: ALPHA / DIGIT / "-" / "." / "_" / "~"
QByteArray ba = QUrl::toPercentEncoding("{a fishy string?}", "{}", "s");
qDebug(ba.constData());
// prints "{a fi%73hy %73tring%3F}"
Definition at line 6009 of file qurl.cpp.
Referenced by allQueryItemValues(), QPatternist::EncodeString::evaluateSingleton(), hasQueryItem(), queryItemValue(), removeAllQueryItems(), removeQueryItem(), swap(), and QNetworkCookie::toRawForm().
 {
     return toPercentEncodingHelper(input, exclude.constData(), include.constData());
 }
topLevelDomain()
QString QUrl::topLevelDomain () const
Returns the TLD (Top-Level Domain) of the URL, (e.
Since
4.8
g. .co.uk, .net). Note that the return value is prefixed with a '.' unless the URL does not contain a valid TLD, in which case the function returns an empty string.
Definition at line 5794 of file qurl.cpp.
 {
     return qTopLevelDomain(host());
 }
toPunycode()
QByteArray QUrl::toPunycode (const QString & uc) static
Returns a uc in Punycode encoding.
Punycode is a Unicode encoding used for internationalized domain names, as defined in RFC3492. If you want to convert a domain name from Unicode to its ASCII-compatible representation, use toAce().
Definition at line 6025 of file qurl.cpp.
 {
     QString output;
     toPunycodeHelper(uc.constData(), uc.size(), &output);
     return output.toLatin1();
 }
toString()
QString QUrl::toString (FormattingOptions options = None) const
Returns the human-displayable string representation of the URL.
The output can be customized by passing flags with options.
See also
FormattingOptions, toEncoded()
Definition at line 5896 of file qurl.cpp.
Referenced by QTextBrowserPrivate::_q_highlightLink(), QDeclarativeImportsPrivate::add(), QPatternist::ReportContext::codeFromURI(), QDeclarativeTypeData::compile(), QDeclarativeCompiler::compileTree(), QDeclarativeConnections::connectSignals(), QWindowsMimeURI::convertFromMime(), QNetworkAccessFileBackendFactory::create(), createPixmapDataSync(), QDeclarativeEnginePrivate::createQmlObject(), QPatternist::URILoader::createRequest(), QDeclarativeTypeData::done(), QDeclarativeCompiler::dumpStats(), QDeclarativeComponent::errorString(), QDeclarativeImportedNamespace::find(), QTextHtmlExporter::findUrlForImage(), QDeclarativeInclude::finished(), QDeclarativeXMLHttpRequest::finished(), QTextBrowser::focusNextPrevChild(), QPatternist::formatResourcePath(), QPatternist::formatURI(), QPatternist::AtomicString::fromValue(), QPatternist::AnyURI::fromValue(), getImage(), QDeclarativeEnginePrivate::getImageFromProvider(), getPixmap(), QDeclarativeEnginePrivate::getPixmapFromProvider(), QDeclarativeInclude::include(), QWindowsSystemProxy::init(), launchWebBrowser(), QPatternist::NetworkAccessDelegator::managerFor(), QDeclarativeVMEMetaObject::method(), navigatorInvoke(), QNetworkAccessFileBackend::open(), QNetworkAccessFtpBackend::open(), openDocument(), operator<<(), QDeclarativeScriptParser::parse(), QPatternist::AccelTree::printStats(), QDeclarativePixmapReader::processJob(), QDeclarativeWorkerScriptEnginePrivate::processLoad(), QSourceLocation::qHash(), QNetworkReplyFileImpl::QNetworkReplyFileImpl(), QDeclarativeDebugTrace::rangeDataImpl(), QDeclarativeDebugTrace::rangeLocationImpl(), readImage(), registerComponent(), QDeclarativeXMLHttpRequest::requestFromUrl(), QPatternist::resolveAndCheckCollation(), QDeclarativeScriptEngine::resolvedUrl(), resolveScheme(), QPatternist::AnyURI::resolveURI(), QTextBrowserPrivate::restoreHistoryEntry(), QDeclarativeEngineDebugService::setMethodBody(), QTextBrowserPrivate::setSource(), statusCodeFromHttp(), QNetworkProxyFactory::systemProxyForQuery(), QDeclarativeError::toString(), QPatternist::AtomicValue::toXDM(), and QPatternist::DefaultCollationFN::typeCheck().
 {
     if (!d) return QString();
     QString ourPath = path();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     QString url;
     if (!(options & QUrl::RemoveScheme) && !d->scheme.isEmpty())
         url += d->scheme + QLatin1Char(':');
     if ((options & QUrl::RemoveAuthority) != QUrl::RemoveAuthority) {
         bool doFileScheme = d->scheme == QLatin1String("file") && ourPath.startsWith(QLatin1Char('/'));
         QString tmp = d->authority(options);
         if (!tmp.isNull() || doFileScheme) {
             if (doFileScheme && !ourPath.startsWith(QLatin1Char('/')))
                 url += QLatin1Char('/');
             url += QLatin1String("//");
             url += tmp;
         }
     }
     if (!(options & QUrl::RemovePath)) {
         // check if we need to insert a slash
         if ((options & QUrl::RemoveAuthority) != QUrl::RemoveAuthority
             && !d->authority(options).isEmpty() && !ourPath.isEmpty() && ourPath.at(0) != QLatin1Char('/'))
             url += QLatin1Char('/');
         url += ourPath;
         // check if we need to remove trailing slashes
         while ((options & StripTrailingSlash) && url.endsWith(QLatin1Char('/')))
             url.chop(1);
     }
     if (!(options & QUrl::RemoveQuery) && d->hasQuery) {
         url += QLatin1Char('?');
         url += fromPercentEncoding(d->query);
     }
     if (!(options & QUrl::RemoveFragment) && d->hasFragment) {
         url += QLatin1Char('#');
         url += d->fragmentImpl();
     }
     return url;
 }
userInfo()
QString QUrl::userInfo () const
Returns the user info of the URL, or an empty string if the user info is undefined.
Definition at line 4631 of file qurl.cpp.
Referenced by QHttpNetworkConnectionPrivate::fillPipeline(), and QHttpNetworkConnectionChannel::sendRequest().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     return d->userInfo();
 }
userName()
QString QUrl::userName () const
Returns the user name of the URL if it is defined; otherwise an empty string is returned.
See also
setUserName(), encodedUserName()
Definition at line 4667 of file qurl.cpp.
Referenced by QNetworkAccessManagerPrivate::authenticationRequired(), QNetworkAccessAuthenticationManager::cacheCredentials(), QNetworkAccessFtpBackend::open(), QHttpNetworkConnectionChannel::sendRequest(), setEncodedUserName(), and setUserName().
 {
     if (!d) return QString();
     QMutexLocker lock(&d->mutex);
     if (!QURL_HASFLAG(d->stateFlags, QUrlPrivate::Parsed)) d->parse();
     d->userInfo();              // causes the unencoded form to be set
     return d->userName;
 }
Friends and Related Functions
operator<<()
QDataStream & operator<< (QDataStream & out, const QUrl & url) related
Writes url url to the stream out and returns a reference to the stream.
See also
Format of the QDataStream operators
Definition at line 6757 of file qurl.cpp.
Referenced by operator<<().
 {
     QByteArray u = url.toEncoded();
     out << u;
     return out;
 }
operator>>()
QDataStream & operator>> (QDataStream & in, QUrl & url) related
Reads a url into url from the stream in and returns a reference to the stream.
See also
Format of the QDataStream operators
Definition at line 6774 of file qurl.cpp.
 {
     QByteArray u;
     in >> u;
     url = QUrl::fromEncoded(u);
     return in;
 }
qHash()
uint qHash (const QUrl & url) related
Since
4.7
Computes a hash key from the normalized version of url.
Definition at line 285 of file qurl.h.
Referenced by containsTLDEntry(), getLock(), and qHash().
 {
     return qHash(url.toEncoded(QUrl::FormattingOption(0x100)));
 }
Properties
d
QUrlPrivate* QUrl::d private
Definition at line 279 of file qurl.h.
Referenced by addEncodedQueryItem(), addQueryItem(), allEncodedQueryItemValues(), allQueryItemValues(), authority(), clear(), detach(), encodedFragment(), encodedPassword(), encodedPath(), encodedQuery(), encodedQueryItems(), encodedQueryItemValue(), encodedUserName(), errorString(), fragment(), hasEncodedQueryItem(), hasFragment(), hasQuery(), hasQueryItem(), host(), isDetached(), isEmpty(), isLocalFile(), isParentOf(), isRelative(), isValid(), operator<(), operator=(), operator==(), password(), path(), port(), queryItems(), queryItemValue(), queryPairDelimiter(), queryValueDelimiter(), QUrl(), removeAllEncodedQueryItems(), removeAllQueryItems(), removeEncodedQueryItem(), removeQueryItem(), resolved(), scheme(), setAuthority(), setEncodedFragment(), setEncodedPassword(), setEncodedPath(), setEncodedQuery(), setEncodedQueryItems(), setEncodedUrl(), setEncodedUserName(), setFragment(), setHost(), setPassword(), setPath(), setPort(), setQueryDelimiters(), setQueryItems(), setScheme(), setUrl(), setUserInfo(), setUserName(), swap(), toEncoded(), toLocalFile(), toString(), userInfo(), userName(), and ~QUrl().
The documentation for this class was generated from the following files:
/src/corelib/io/qurl.h
/src/corelib/io/qurl.cpp