Qt 4.8: QDockWidgetItem Class Reference
QDockWidgetItem Class Reference
#include <qdockwidget_p.h>
Public Functions
QSize maximumSize () const
Reimplemented Function
QSize minimumSize () const
Reimplemented Function
QDockWidgetItem (QDockWidget *dockWidget)
QSize sizeHint () const
Reimplemented Function
Public Functions inherited from QWidgetItem
Qt::Orientations expandingDirections () const
Reimplemented Function
QRect geometry () const
Reimplemented Function
bool hasHeightForWidth () const
Reimplemented Function
int heightForWidth (int) const
Reimplemented Function
bool isEmpty () const
Returns true if the widget is hidden; otherwise returns false.
QWidgetItem (QWidget *w)
Creates an item containing the given widget.
void setGeometry (const QRect &)
Reimplemented Function
virtual QWidget * widget ()
Returns the widget managed by this item.
Public Functions inherited from QLayoutItem
Qt::Alignment alignment () const
Returns the alignment of this item.
QSizePolicy::ControlTypes controlTypes () const
Returns the control type(s) for the layout item.
virtual void invalidate ()
Invalidates any cached information in this layout item.
virtual QLayout * layout ()
If this item is a QLayout, it is returned as a QLayout; otherwise 0 is returned.
virtual int minimumHeightForWidth (int) const
Returns the minimum height this widget needs for the given width, w.
QLayoutItem (Qt::Alignment alignment=0)
Constructs a layout item with an alignment.
void setAlignment (Qt::Alignment a)
Sets the alignment of this item to alignment.
virtual QSpacerItem * spacerItem ()
If this item is a QSpacerItem, it is returned as a QSpacerItem; otherwise 0 is returned.
virtual ~QLayoutItem ()
Destroys the QLayoutItem.
Private Functions
QLayoutItem * dockWidgetChildItem () const
QDockWidgetLayout * dockWidgetLayout () const
Additional Inherited Members
Protected Variables inherited from QWidgetItem
QWidget * wid
Protected Variables inherited from QLayoutItem
Qt::Alignment align
Detailed Description
Definition at line 175 of file qdockwidget_p.h.
Constructors and Destructors
QDockWidgetItem()
QDockWidgetItem::QDockWidgetItem (QDockWidget * dockWidget)
Definition at line 542 of file qdockwidget.cpp.
Referenced by QDockWidgetPrivate::startDrag().
     : QWidgetItem(dockWidget)
 {
 }
Functions
dockWidgetChildItem()
QLayoutItem * QDockWidgetItem::dockWidgetChildItem () const inline private
Definition at line 188 of file qdockwidget_p.h.
Referenced by maximumSize(), minimumSize(), and sizeHint().
 {
     if (QDockWidgetLayout *layout = dockWidgetLayout())
         return layout->itemForRole(QDockWidgetLayout::Content);
     return 0;
 }
dockWidgetLayout()
QDockWidgetLayout * QDockWidgetItem::dockWidgetLayout () const inline private
Definition at line 195 of file qdockwidget_p.h.
Referenced by maximumSize(), minimumSize(), and sizeHint().
 {
     QWidget *w = const_cast<QDockWidgetItem*>(this)->widget();
     if (w != 0)
         return qobject_cast<QDockWidgetLayout*>(w->layout());
     return 0;
 }
maximumSize()
QSize QDockWidgetItem::maximumSize () const virtual
Reimplemented Function
Reimplemented from QWidgetItem.
Definition at line 555 of file qdockwidget.cpp.
 {
     if (QLayoutItem *item = dockWidgetChildItem()) {
         return dockWidgetLayout()->sizeFromContent(item->maximumSize(), false);
     } else {
         return QSize(QWIDGETSIZE_MAX, QWIDGETSIZE_MAX);
     }
 }
minimumSize()
QSize QDockWidgetItem::minimumSize () const virtual
Reimplemented Function
Reimplemented from QWidgetItem.
Definition at line 547 of file qdockwidget.cpp.
 {
     QSize widgetMin(0, 0);
     if (QLayoutItem *item = dockWidgetChildItem())
         widgetMin = item->minimumSize();
     return dockWidgetLayout()->sizeFromContent(widgetMin, false);
 }
sizeHint()
QSize QDockWidgetItem::sizeHint () const virtual
Reimplemented Function
Reimplemented from QWidgetItem.
Definition at line 565 of file qdockwidget.cpp.
 {
     if (QLayoutItem *item = dockWidgetChildItem()) {
          return dockWidgetLayout()->sizeFromContent(item->sizeHint(), false);
     } else {
         return QWidgetItem::sizeHint();
     }
 }
The documentation for this class was generated from the following files:
/src/gui/widgets/qdockwidget_p.h
/src/gui/widgets/qdockwidget.cpp