Qt 4.8: QMimeData Class Reference
QMimeData Class Reference
The QMimeData class provides a container for data that records information about its MIME type.
#include <qmimedata.h>
Public Functions
void clear ()
Removes all the MIME type and data entries in the object.
QVariant colorData () const
Returns a color if the data stored in the object represents a color (MIME type application/x-color); otherwise returns a null variant.
QByteArray data (const QString &mimetype) const
Returns the data stored in the object in the format described by the MIME type specified by mimeType.
virtual QStringList formats () const
Returns a list of formats supported by the object.
bool hasColor () const
Returns true if the object can return a color (MIME type application/x-color); otherwise returns false.
virtual bool hasFormat (const QString &mimetype) const
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
bool hasHtml () const
Returns true if the object can return HTML (MIME type text/html); otherwise returns false.
bool hasImage () const
Returns true if the object can return an image; otherwise returns false.
bool hasText () const
Returns true if the object can return plain text (MIME type text/plain); otherwise returns false.
bool hasUrls () const
Returns true if the object can return a list of urls; otherwise returns false.
QString html () const
Returns a string if the data stored in the object is HTML (MIME type text/html); otherwise returns an empty string.
QVariant imageData () const
Returns a QVariant storing a QImage if the object can return an image; otherwise returns a null variant.
QMimeData ()
Constructs a new MIME data object with no data in it.
void removeFormat (const QString &mimetype)
Removes the data entry for mimeType in the object.
void setColorData (const QVariant &color)
Sets the color data in the object to the given color.
void setData (const QString &mimetype, const QByteArray &data)
Sets the data associated with the MIME type given by mimeType to the specified data.
void setHtml (const QString &html)
Sets html as the HTML (MIME type text/html) used to represent the data.
void setImageData (const QVariant &image)
Sets the data in the object to the given image.
void setText (const QString &text)
Sets text as the plain text (MIME type text/plain) used to represent the data.
void setUrls (const QList< QUrl > &urls)
Sets the URLs stored in the MIME data object to those specified by urls.
QString text () const
Returns a plain text (MIME type text/plain) representation of the data.
QList< QUrl > urls () const
Returns a list of URLs contained within the MIME data object.
~QMimeData ()
Destroys the MIME data object.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Protected Functions
virtual QVariant retrieveData (const QString &mimetype, QVariant::Type preferredType) const
Returns a variant with the given type containing data for the MIME type specified by mimeType.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QMimeData class provides a container for data that records information about its MIME type.
QMimeData is used to describe information that can be stored in the clipboard, and transferred via the drag and drop mechanism. QMimeData objects associate the data that they hold with the corresponding MIME types to ensure that information can be safely transferred between applications, and copied around within the same application.
QMimeData objects are usually created using new and supplied to QDrag or QClipboard objects. This is to enable Qt to manage the memory that they use.
A single QMimeData object can store the same data using several different formats at the same time. The formats() function returns a list of the available formats in order of preference. The data() function returns the raw data associated with a MIME type, and setData() allows you to set the data for a MIME type.
For the most common MIME types, QMimeData provides convenience functions to access the data:
Tester Getter Setter MIME Types
hasText() text() setText() text/plain
hasHtml() html() setHtml() text/html
hasUrls() urls() setUrls() text/uri-list
hasImage() imageData() setImageData() image/ *
hasColor() colorData() setColorData() application/x-color
For example, if your write a widget that accepts URL drags, you would end up writing code like this:
void MyWidget::dragEnterEvent(QDragEnterEvent *event)
{
    if (event->mimeData()->hasUrls())
        event->acceptProposedAction();
}
void MyWidget::dropEvent(QDropEvent *event)
{
    if (event->mimeData()->hasUrls()) {
        foreach (QUrl url, event->mimeData()->urls()) {
            ...
        }
    }
}
There are three approaches for storing custom data in a QMimeData object:
Custom data can be stored directly in a QMimeData object as a QByteArray using setData(). For example:
QByteArray csvData = ...;
QMimeData *mimeData = new QMimeData;
mimeData->setData("text/csv", csvData);
We can subclass QMimeData and reimplement hasFormat(), formats(), and retrieveData().
If the drag and drop operation occurs within a single application, we can subclass QMimeData and add extra data in it, and use a qobject_cast() in the receiver's drop event handler. For example:
void MyWidget::dropEvent(QDropEvent *event)
{
    const MyMimeData *myData =
            qobject_cast<const MyMimeData *>(event->mimeData());
    if (myData) {
        // access myData's data directly (not through QMimeData's API)
    }
}
Platform-Specific MIME Types
On Windows, formats() will also return custom formats available in the MIME data, using the x-qt-windows-mime subtype to indicate that they represent data in non-standard formats. The formats will take the following form:
application/x-qt-windows-mime;value="<custom type>"
The following are examples of custom MIME types:
application/x-qt-windows-mime;value="FileGroupDescriptor"
application/x-qt-windows-mime;value="FileContents"
The value declaration of each format describes the way in which the data is encoded.
On Windows, the MIME format does not always map directly to the clipboard formats. Qt provides QWindowsMime to map clipboard formats to open-standard MIME formats. Similarly, the QMacPasteboardMime maps MIME to Mac flavors.
See also
QClipboard, QDragEnterEvent, QDragMoveEvent, QDropEvent, QDrag, QWindowsMime, QMacPasteboardMime, {Drag and Drop}
Definition at line 57 of file qmimedata.h.
Constructors and Destructors
QMimeData()
QMimeData::QMimeData ()
Constructs a new MIME data object with no data in it.
Definition at line 291 of file qmimedata.cpp.
Referenced by QtCeGetClipboard().
     : QObject(*new QMimeDataPrivate, 0)
 {
 }
~QMimeData()
QMimeData::~QMimeData ()
Destroys the MIME data object.
Definition at line 299 of file qmimedata.cpp.
 {
 }
Functions
clear()
void QMimeData::clear ()
Removes all the MIME type and data entries in the object.
Definition at line 613 of file qmimedata.cpp.
Referenced by QWaylandMimeData::clearAll(), QBBClipboard::mimeData(), QListModel::mimeData(), QTableModel::mimeData(), QClipboardData::QClipboardData(), QInternalMimeData::retrieveData(), QBBClipboard::setMimeData(), and QTableModel::tableIndex().
 {
     Q_D(QMimeData);
     d->dataList.clear();
 }
colorData()
QVariant QMimeData::colorData () const
Returns a color if the data stored in the object represents a color (MIME type application/x-color); otherwise returns a null variant.
A QVariant is used because QMimeData belongs to the QtCore library, whereas QColor belongs to QtGui . To convert the QVariant to a QColor, simply use qvariant_cast(). For example:
if (event->mimeData()->hasColor()) {
    QColor color = qvariant_cast<QColor>(event->mimeData()->colorData());
    ...
}
See also
hasColor(), setColorData(), data()
Definition at line 489 of file qmimedata.cpp.
Referenced by QColorWell::dragEnterEvent(), QColorShowLabel::dragEnterEvent(), QColorWell::dragMoveEvent(), QColorWell::dropEvent(), QColorShowLabel::dropEvent(), and QInternalMimeData::renderDataHelper().
 {
     Q_D(const QMimeData);
     return d->retrieveTypedData(QLatin1String("application/x-color"), QVariant::Color);
 }
data()
QByteArray QMimeData::data (const QString & mimetype) const
Returns the data stored in the object in the format described by the MIME type specified by mimeType.
Definition at line 524 of file qmimedata.cpp.
Referenced by QAbstractItemModel::dropMimeData(), QAbstractTableModel::dropMimeData(), QAbstractListModel::dropMimeData(), QStandardItemModel::dropMimeData(), QClipboardWatcher::empty(), QDropEvent::encodedData(), html(), QTableModel::index(), QTextControl::insertFromMimeData(), isProcessBeingDebugged(), QXlibMime::mimeConvertToFormat(), QtCeGetClipboard(), QtCeSetClipboard(), QInternalMimeData::renderDataHelper(), QInternalMimeData::retrieveData(), QBBClipboard::MimeData::retrieveData(), QCocoaDropData::retrieveData_sys(), QBBClipboard::setMimeData(), QMacPasteboard::setMimeData(), text(), QClipboard::text(), urls(), QX11Data::xdndHandleDrop(), and xdndObtainData().
 {
     Q_D(const QMimeData);
     QVariant data = d->retrieveTypedData(mimeType, QVariant::ByteArray);
     return data.toByteArray();
 }
formats()
QStringList QMimeData::formats () const virtual
Returns a list of formats supported by the object.
This is a list of MIME types for which the object can return suitable data. The formats in the list are in a priority order.
For the most common types of data, you can call the higher-level functions hasText(), hasHtml(), hasUrls(), hasImage(), and hasColor() instead.
See also
hasFormat(), setData(), data()
Reimplemented in QMacPasteboardMimeSource, QTextEditMimeData, QBBClipboard::MimeData, QInternalMimeData, and QMimeSourceWrapper.
Definition at line 579 of file qmimedata.cpp.
Referenced by QBuiltInMimes::canConvertFromMime(), QUrlModel::canDrop(), QUrlModel::dropMimeData(), QDropEvent::format(), QTextEditMimeData::formats(), QBuiltInMimes::formatsForMime(), QInternalMimeData::formatsHelper(), hasFormat(), QDropEvent::provides(), QWaylandSelection::QWaylandSelection(), QBBClipboard::MimeData::releaseOwnership(), QBBClipboard::setMimeData(), QMacPasteboard::setMimeData(), and QClipboard::text().
 {
     Q_D(const QMimeData);
     QStringList list;
     for (int i=0; i<d->dataList.size(); i++)
         list += d->dataList.at(i).format;
     return list;
 }
hasColor()
bool QMimeData::hasColor () const
Returns true if the object can return a color (MIME type application/x-color); otherwise returns false.
See also
setColorData(), colorData(), hasFormat()
Definition at line 515 of file qmimedata.cpp.
 {
     return hasFormat(QLatin1String("application/x-color"));
 }
hasFormat()
bool QMimeData::hasFormat (const QString & mimeType) const virtual
Returns true if the object can return data for the MIME type specified by mimeType; otherwise returns false.
For the most common types of data, you can call the higher-level functions hasText(), hasHtml(), hasUrls(), hasImage(), and hasColor() instead.
See also
formats(), setData(), data()
Reimplemented in QBBClipboard::MimeData, QInternalMimeData, and QMimeSourceWrapper.
Definition at line 563 of file qmimedata.cpp.
Referenced by QWindowsMimeURI::canConvertFromMime(), QAbstractItemViewPrivate::canDecode(), QTextControl::canInsertFromMimeData(), QLineEdit::dragMoveEvent(), QAbstractItemModel::dropMimeData(), QAbstractTableModel::dropMimeData(), QAbstractListModel::dropMimeData(), QStandardItemModel::dropMimeData(), hasColor(), QInternalMimeData::hasFormatHelper(), hasHtml(), hasImage(), hasText(), hasUrls(), QTextControl::insertFromMimeData(), and xdndObtainData().
 {
     return formats().contains(mimeType);
 }
hasHtml()
bool QMimeData::hasHtml () const
Returns true if the object can return HTML (MIME type text/html); otherwise returns false.
See also
setHtml(), html(), hasFormat()
Definition at line 425 of file qmimedata.cpp.
Referenced by QTextControl::canInsertFromMimeData(), and QTextControl::insertFromMimeData().
 {
     return hasFormat(QLatin1String("text/html"));
 }
hasImage()
bool QMimeData::hasImage () const
Returns true if the object can return an image; otherwise returns false.
See also
setImageData(), imageData(), hasFormat()
Definition at line 471 of file qmimedata.cpp.
Referenced by QWindowsMimeImage::canConvertFromMime(), QWindowsMimeImage::convertFromMime(), QWindowsMimeImage::formatsForMime(), QInternalMimeData::hasFormatHelper(), QXlibMime::mimeDataForAtom(), QInternalMimeData::renderDataHelper(), QX11Data::xdndHandleDrop(), QX11Data::xdndMimeDataForAtom(), and xdndObtainData().
 {
     return hasFormat(QLatin1String("application/x-qt-image"));
 }
hasText()
bool QMimeData::hasText () const
Returns true if the object can return plain text (MIME type text/plain); otherwise returns false.
See also
setText(), text(), hasHtml(), hasFormat()
Definition at line 389 of file qmimedata.cpp.
Referenced by QWindowsMimeText::canConvertFromMime(), QTextControl::canInsertFromMimeData(), QWindowsMimeText::formatsForMime(), and QtCeSetClipboard().
 {
     return hasFormat(QLatin1String("text/plain"));
 }
hasUrls()
bool QMimeData::hasUrls () const
Returns true if the object can return a list of urls; otherwise returns false.
URLs correspond to the MIME type text/uri-list.
See also
setUrls(), urls(), hasFormat()
Definition at line 352 of file qmimedata.cpp.
 {
     return hasFormat(QLatin1String("text/uri-list"));
 }
html()
QString QMimeData::html () const
Returns a string if the data stored in the object is HTML (MIME type text/html); otherwise returns an empty string.
See also
hasHtml(), setData()
Definition at line 400 of file qmimedata.cpp.
Referenced by QWindowsMimeHtml::canConvertFromMime(), QWindowsMimeHtml::convertFromMime(), QBuiltInMimes::convertFromMime(), QWindowsMimeHtml::formatsForMime(), and QTextControl::insertFromMimeData().
 {
     Q_D(const QMimeData);
     QVariant data = d->retrieveTypedData(QLatin1String("text/html"), QVariant::String);
     return data.toString();
 }
imageData()
QVariant QMimeData::imageData () const
Returns a QVariant storing a QImage if the object can return an image; otherwise returns a null variant.
A QVariant is used because QMimeData belongs to the QtCore library, whereas QImage belongs to QtGui . To convert the QVariant to a QImage, simply use qvariant_cast(). For example:
if (event->mimeData()->hasImage()) {
    QImage image = qvariant_cast<QImage>(event->mimeData()->imageData());
    ...
}
See also
hasImage()
Definition at line 442 of file qmimedata.cpp.
Referenced by QWindowsMimeImage::canConvertFromMime(), QWindowsMimeImage::convertFromMime(), QWindowsMimeImage::formatsForMime(), QClipboard::image(), QClipboard::pixmap(), QInternalMimeData::renderDataHelper(), QX11Data::xdndMimeDataForAtom(), and xdndObtainData().
 {
     Q_D(const QMimeData);
     return d->retrieveTypedData(QLatin1String("application/x-qt-image"), QVariant::Image);
 }
removeFormat()
void QMimeData::removeFormat (const QString & mimeType)
Removes the data entry for mimeType in the object.
Since
4.4
Definition at line 627 of file qmimedata.cpp.
 {
     Q_D(QMimeData);
     d->removeData(mimeType);
 }
retrieveData()
QVariant QMimeData::retrieveData (const QString & mimeType, QVariant::Type type) const protected virtual
Returns a variant with the given type containing data for the MIME type specified by mimeType.
If the object does not support the MIME type or variant type given, a null variant is returned instead.
This function is called by the general data() getter and by the convenience getters (text(), html(), urls(), imageData(), and colorData()). You can reimplement it if you want to store your data using a custom data structure (instead of a QByteArray, which is what setData() provides). You would then also need to reimplement hasFormat() and formats().
See also
data()
Reimplemented in QMacPasteboardMimeSource, QTextEditMimeData, QBBClipboard::MimeData, QInternalMimeData, and QMimeSourceWrapper.
Definition at line 603 of file qmimedata.cpp.
Referenced by QInternalMimeData::retrieveData(), QBBClipboard::MimeData::retrieveData(), and QTextEditMimeData::retrieveData().
 {
     Q_UNUSED(type);
     Q_D(const QMimeData);
     return d->getData(mimeType);
 }
setColorData()
void QMimeData::setColorData (const QVariant & color)
Sets the color data in the object to the given color.
Colors correspond to the MIME type application/x-color.
See also
hasColor(), setData()
Definition at line 502 of file qmimedata.cpp.
Referenced by QColorWell::mouseMoveEvent(), and QColorShowLabel::mouseMoveEvent().
 {
     Q_D(QMimeData);
     d->setData(QLatin1String("application/x-color"), color);
 }
setData()
void QMimeData::setData (const QString & mimeType, const QByteArray & data)
Sets the data associated with the MIME type given by mimeType to the specified data.
For the most common types of data, you can call the higher-level functions setText(), setHtml(), setUrls(), setImageData(), and setColorData() instead.
Note that if you want to use a custom data type in an item view drag and drop operation, you must register it as a Qt meta type, using the Q_DECLARE_METATYPE() macro, and implement stream operators for it. The stream operators must then be registered with the qRegisterMetaTypeStreamOperators() function.
See also
hasFormat(), QMetaType, qRegisterMetaTypeStreamOperators()
Definition at line 547 of file qmimedata.cpp.
Referenced by QTableModel::index(), QAbstractItemModel::mimeData(), QStandardItemModel::mimeData(), QInternalMimeData::retrieveData(), and QTextEditMimeData::setup().
 {
     Q_D(QMimeData);
     d->setData(mimeType, QVariant(data));
 }
setHtml()
void QMimeData::setHtml (const QString & html)
Sets html as the HTML (MIME type text/html) used to represent the data.
See also
hasHtml(), setText(), setData()
Definition at line 413 of file qmimedata.cpp.
 {
     Q_D(QMimeData);
     d->setData(QLatin1String("text/html"), html);
 }
setImageData()
void QMimeData::setImageData (const QVariant & image)
Sets the data in the object to the given image.
A QVariant is used because QMimeData belongs to the QtCore library, whereas QImage belongs to QtGui . The conversion from QImage to QVariant is implicit. For example:
mimeData->setImageData(QImage("beautifulfjord.png"));
See also
hasImage(), setData()
Definition at line 459 of file qmimedata.cpp.
Referenced by QClipboard::setImage(), and QClipboard::setPixmap().
 {
     Q_D(QMimeData);
     d->setData(QLatin1String("application/x-qt-image"), image);
 }
setText()
void QMimeData::setText (const QString & text)
Sets text as the plain text (MIME type text/plain) used to represent the data.
See also
hasText(), setHtml(), setData()
Definition at line 377 of file qmimedata.cpp.
Referenced by QTextControlPrivate::_q_copyLink(), clipboardData(), QLineEditPrivate::drag(), QmlJSDebugger::ToolBarColorBox::mouseMoveEvent(), QtCeGetClipboard(), QClipboard::setText(), and QTextEditMimeData::setup().
 {
     Q_D(QMimeData);
     d->setData(QLatin1String("text/plain"), text);
 }
setUrls()
void QMimeData::setUrls (const QList< QUrl > & urls)
Sets the URLs stored in the MIME data object to those specified by urls.
URLs correspond to the MIME type text/uri-list.
See also
hasUrls(), setData()
Definition at line 334 of file qmimedata.cpp.
Referenced by QUrlModel::mimeData(), QDirModel::mimeData(), and QFileSystemModel::mimeData().
 {
     Q_D(QMimeData);
     QList<QVariant> list;
     for (int i = 0; i < urls.size(); ++i)
         list.append(urls.at(i));
     d->setData(QLatin1String("text/uri-list"), list);
 }
text()
QString QMimeData::text () const
Returns a plain text (MIME type text/plain) representation of the data.
See also
hasText(), html(), data()
Definition at line 364 of file qmimedata.cpp.
Referenced by QTextControl::canInsertFromMimeData(), clipboardData(), QWindowsMimeText::convertFromMime(), QLineEdit::dropEvent(), QTextControl::insertFromMimeData(), QtCeSetClipboard(), and QClipboard::text().
 {
     Q_D(const QMimeData);
     QVariant data = d->retrieveTypedData(QLatin1String("text/plain"), QVariant::String);
     return data.toString();
 }
urls()
QList< QUrl > QMimeData::urls () const
Returns a list of URLs contained within the MIME data object.
URLs correspond to the MIME type text/uri-list.
See also
hasUrls(), data()
Definition at line 310 of file qmimedata.cpp.
Referenced by QWindowsMimeURI::canConvertFromMime(), QWindowsMimeURI::convertFromMime(), QDragManager::drag(), QUrlModel::dropMimeData(), QDirModel::dropMimeData(), QFileSystemModel::dropMimeData(), and QMacPasteboard::setMimeData().
 {
     Q_D(const QMimeData);
     QVariant data = d->retrieveTypedData(QLatin1String("text/uri-list"), QVariant::List);
     QList<QUrl> urls;
     if (data.type() == QVariant::Url)
         urls.append(data.toUrl());
     else if (data.type() == QVariant::List) {
         QList<QVariant> list = data.toList();
         for (int i = 0; i < list.size(); ++i) {
             if (list.at(i).type() == QVariant::Url)
                 urls.append(list.at(i).toUrl());
         }
     }
     return urls;
 }
The documentation for this class was generated from the following files:
/src/corelib/kernel/qmimedata.h
/src/corelib/kernel/qmimedata.cpp