Qt 4.8: QXmlQuery Class Reference
QXmlQuery Class Reference
The QXmlQuery class performs XQueries on XML data, or on non-XML data modeled to look like XML.
#include <qxmlquery.h>
Public Types
enum QueryLanguage {
XQuery10 = 1, XSLT20 = 2, XmlSchema11IdentityConstraintSelector = 1024, XmlSchema11IdentityConstraintField = 2048,
XPath20 = 4096
}
Specifies whether you want QXmlQuery to interpret the input to setQuery() as an XQuery or as an XSLT stylesheet.
Public Functions
void bindVariable (const QXmlName &name, const QXmlItem &value)
Binds the variable name to the value so that $name can be used from within the query to refer to the value.
void bindVariable (const QString &localName, const QXmlItem &value)
This function constructs a QXmlName from localName using the query's QXmlNamePool {namespace}.
void bindVariable (const QXmlName &name, QIODevice *)
Binds the variable name to the device so that $name can be used from within the query to refer to the device.
void bindVariable (const QString &localName, QIODevice *)
If localName is a valid QXmlName::isNCName() {NCName}, this function is equivalent to the following snippet.
void bindVariable (const QXmlName &name, const QXmlQuery &query)
Binds the result of the query query, to a variable by name name.
void bindVariable (const QString &localName, const QXmlQuery &query)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Has the same behavior and effects as the function being overloaded, but takes the variable name localName as a QString.
void evaluateTo (QXmlResultItems *result) const
Starts the evaluation and makes it available in result.
bool evaluateTo (QAbstractXmlReceiver *callback) const
Evaluates this query and sends the result as a sequence of callbacks to the QAbstractXmlReceiver {receiver} callback.
bool evaluateTo (QStringList *target) const
Attempts to evaluate the query and returns the results in the target QStringList {string list}.
bool evaluateTo (QIODevice *target) const
Evaluates the query or stylesheet, and writes the output to target.
bool evaluateTo (QString *output) const
Evaluates the query, and serializes the output as XML to output.
QXmlName initialTemplateName () const
Returns the name of the XSL-T stylesheet template that the processor will call first when running an XSL-T stylesheet.
bool isValid () const
Returns true if this query is valid.
QAbstractMessageHandler * messageHandler () const
Returns the message handler that handles compile and runtime messages for this QXmlQuery.
QXmlNamePool namePool () const
Returns the name pool used by this QXmlQuery for constructing QXmlName {names}.
QNetworkAccessManager * networkAccessManager () const
Returns the network manager, or 0 if it has not been set.
QXmlQuery & operator= (const QXmlQuery &other)
Assigns other to this QXmlQuery instance.
QueryLanguage queryLanguage () const
Returns a value indicating what this QXmlQuery is being used for.
QXmlQuery ()
Constructs an invalid, empty query that cannot be used until setQuery() is called.
QXmlQuery (const QXmlQuery &other)
Constructs a QXmlQuery that is a copy of other.
QXmlQuery (const QXmlNamePool &np)
Constructs a query that will use np as its name pool.
QXmlQuery (QueryLanguage queryLanguage, const QXmlNamePool &np=QXmlNamePool())
Constructs a query that will be used to run Xqueries or XSL-T stylesheets, depending on the value of queryLanguage.
void setFocus (const QXmlItem &item)
Sets the focus to item.
bool setFocus (const QUrl &documentURI)
Sets the focus to be the document located at documentURI and returns true.
bool setFocus (QIODevice *document)
Sets the focus to be the document read from the QIODevice and returns true.
bool setFocus (const QString &focus)
This function behaves identically to calling the setFocus() overload with a QIODevice whose content is focus encoded as UTF-8.
void setInitialTemplateName (const QXmlName &name)
Sets the name of the initial template.
void setInitialTemplateName (const QString &name)
Sets the name of the initial template to localName, which must be a valid local name.
void setMessageHandler (QAbstractMessageHandler *messageHandler)
Changes the QAbstractMessageHandler {message handler} for this QXmlQuery to aMessageHandler.
void setNetworkAccessManager (QNetworkAccessManager *newManager)
Sets the network manager to newManager.
void setQuery (const QString &sourceCode, const QUrl &documentURI=QUrl())
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. The behavior and requirements of this function are the same as for setQuery(QIODevice*, const QUrl&), after the XQuery has been read from the IO device into a string.
void setQuery (QIODevice *sourceCode, const QUrl &documentURI=QUrl())
Sets this QXmlQuery to an XQuery read from the sourceCode device.
void setQuery (const QUrl &queryURI, const QUrl &baseURI=QUrl())
Sets this QXmlQuery to the XQuery read from the queryURI.
void setUriResolver (const QAbstractUriResolver *resolver)
Sets the URI resolver to resolver.
const QAbstractUriResolver * uriResolver () const
Returns the query's URI resolver.
~QXmlQuery ()
Destroys this QXmlQuery.
Properties
QXmlQueryPrivate * d
Friends
class QPatternist::VariableLoader
class QPatternist::XsdSchemaParser
class QPatternist::XsdValidatingInstanceReader
class QPatternistSDK::TestCase
class QXmlName
class QXmlSerializer
template<typename TInputType >
bool setFocusHelper (QXmlQuery *const queryInstance, const TInputType &focusValue)
Related Functions
(Note that these are not member functions.)
typedef QFlags< QXmlQuery::QueryLanguage > QueryLanguages
Detailed Description
The QXmlQuery class performs XQueries on XML data, or on non-XML data modeled to look like XML.
Note
This class or function is reentrant.
Since
4.4
The QXmlQuery class compiles and executes queries written in the http://www.w3.org/TR/xquery/ {XQuery language}. QXmlQuery is typically used to query XML data, but it can also query non-XML data that has been modeled to look like XML.
Using QXmlQuery to query XML data, as in the snippet below, is simple because it can use the built-in QAbstractXmlNodeModel {XML data model} as its delegate to the underlying query engine for traversing the data. The built-in data model is specified in http://www.w3.org/TR/xpath-datamodel/ {XQuery 1.0 and XPath 2.0 Data Model}.
QXmlQuery query;
query.setQuery("doc('index.html')/html/body/p[1]");
QXmlSerializer serializer(query, myOutputDevice);
query.evaluateTo(&serializer);
The example uses QXmlQuery to match the first paragraph of an XML document and then QXmlSerializer {output the result} to a device as XML.
Using QXmlQuery to query {non-XML} data requires writing a subclass of QAbstractXmlNodeModel to use as a replacement for the built-in XML data model. The custom data model will be able to traverse the non-XML data as required by the QAbstractXmlNodeModel interface. An instance of this custom data model then becomes the delegate used by the query engine to traverse the non-XML data. For an example of how to use QXmlQuery to query non-XML data, see the documentation for QAbstractXmlNodeModel.
Running XQueries
To run a query set up with QXmlQuery, call one of the evaluation functions.
evaluateTo(QAbstractXmlReceiver *) is called with a pointer to an XML QAbstractXmlReceiver {receiver}, which receives the query results as a sequence of callbacks. The receiver callback class is like the callback class used for translating the output of a SAX parser. QXmlSerializer, for example, is a receiver callback class for translating the sequence of callbacks for output as unformatted XML text.
evaluateTo(QXmlResultItems *) is called with a pointer to an iterator for an empty sequence of query QXmlResultItems {result items}. The Java-like iterator allows the query results to be accessed sequentially.
evaluateTo(QStringList *) is like evaluateTo(QXmlResultItems *), but the query must evaluate to a sequence of strings.
Running XPath Expressions
The XPath language is a subset of the XQuery language, so running an XPath expression is the same as running an XQuery query. Pass the XPath expression to QXmlQuery using setQuery().
Running XSLT stylesheets
Running an XSLT stylesheet is like running an XQuery, except that when you construct your QXmlQuery, you must pass QXmlQuery::XSLT20 to tell QXmlQuery to interpret whatever it gets from setQuery() as an XSLT stylesheet instead of as an XQuery. You must also set the input document by calling setFocus().
    QXmlQuery query(QXmlQuery::XSLT20);
    query.setFocus(QUrl("myInput.xml"));
    query.setQuery(QUrl("myStylesheet.xsl"));
    query.evaluateTo(out);
Note
Currently, setFocus() must be called before setQuery() when using XSLT.
Another way to run an XSLT stylesheet is to use the xmlpatterns command line utility.
xmlpatterns myStylesheet.xsl myInput.xml
Note
For the current release, XSLT support should be considered experimental. See section message handler XSLT conformance for details.
Stylesheet parameters are bound using bindVariable().
Binding A Query To A Starting Node
When a query is run on XML data, as in the snippet above, the doc() function returns the node in the built-in data model where the query evaluation will begin. But when a query is run on a custom node model containing non-XML data, one of the bindVariable() functions must be called to bind a variable name to a starting node in the custom model. A $variable reference is used in the XQuery text to access the starting node in the custom model. It is not necessary to declare the variable name external in the query. See the example in the documentation for QAbstractXmlNodeModel.
Reentrancy and Thread Safety
QXmlQuery is reentrant but not thread-safe. It is safe to use the QxmlQuery copy constructor to create a copy of a query and run the same query multiple times. Behind the scenes, QXmlQuery will reuse resources such as opened files and compiled queries to the extent possible. But it is not safe to use the same instance of QXmlQuery in multiple threads.
Error Handling
Errors can occur during query evaluation. Examples include type errors and file loading errors. When an error occurs:
The error message is sent to the messageHandler().
QXmlResultItems::hasError() will return true, or evaluateTo() will return false;
The results of the evaluation are undefined.
Resource Management
When a query runs, it parses documents, allocating internal data structures to hold them, and it may load other resources over the network. It reuses these allocated resources when possible, to avoid having to reload and reparse them.
When setQuery() is called, the query text is compiled into an internal data structure and optimized. The optimized form can then be reused for multiple evaluations of the query. Since the compile-and-optimize process can be expensive, repeating it for the same query should be avoided by using a separate instance of QXmlQuery for each query text.
Once a document has been parsed, its internal representation is maintained in the QXmlQuery instance and shared among multiple QXmlQuery instances.
An instance of QCoreApplication must exist before QXmlQuery can be used.
Event Handling
When QXmlQuery accesses resources (e.g., calling fn:doc() to load a file, or accessing a device via a bound variable), the event loop is used, which means events will be processed. To avoid processing events when QXmlQuery accesses resources, create your QXmlQuery instance in a separate thread.
Definition at line 79 of file qxmlquery.h.
Enumerations
QueryLanguage
enum QXmlQuery::QueryLanguage
Specifies whether you want QXmlQuery to interpret the input to setQuery() as an XQuery or as an XSLT stylesheet.
Since
4.5
XQuery10 XQuery 1.0.
XSLT20 XSLT 2.0
XmlSchema11IdentityConstraintSelector The selector, the restricted XPath pattern found in W3C XML Schema 1.1 for uniqueness contraints. Apart from restricting the syntax, the type check stage for the expression assumes a sequence of nodes to be the focus.
XmlSchema11IdentityConstraintField The field, the restricted XPath pattern found in W3C XML Schema 1.1 for uniqueness contraints. Apart from restricting the syntax, the type check stage for the expression assumes a sequence of nodes to be the focus.
XPath20 Signifies XPath 2.0. Has no effect in the public API, it's used internally. As With XmlSchema11IdentityConstraintSelector and XmlSchema11IdentityConstraintField, the type check stage for the expression assumes a sequence of nodes to be the focus.
See also
setQuery()
Enumerator
XQuery10
XSLT20
XmlSchema11IdentityConstraintSelector
XmlSchema11IdentityConstraintField
XPath20
Definition at line 82 of file qxmlquery.h.
     {
         XQuery10                                = 1,
         XSLT20                                  = 2,
         XmlSchema11IdentityConstraintSelector   = 1024,
         XmlSchema11IdentityConstraintField      = 2048,
         XPath20                                 = 4096
     };
Constructors and Destructors
QXmlQuery() [1/4]
QXmlQuery::QXmlQuery ()
Constructs an invalid, empty query that cannot be used until setQuery() is called.
Note
This constructor must not be used if you intend to use this QXmlQuery to process XSL-T stylesheets. The other constructor must be used in that case.
Definition at line 261 of file qxmlquery.cpp.
                      : d(new QXmlQueryPrivate())
 {
 }
QXmlQuery() [2/4]
QXmlQuery::QXmlQuery (const QXmlQuery & other)
Constructs a QXmlQuery that is a copy of other.
The new instance will share resources with the existing query to the extent possible.
Definition at line 270 of file qxmlquery.cpp.
                                            : d(new QXmlQueryPrivate(*other.d))
 {
     /* First we have invoked QXmlQueryPrivate's synthesized copy constructor.
      * Keep this section in sync with QXmlQuery::operator=(). */
     d->detach();
 }
QXmlQuery() [3/4]
QXmlQuery::QXmlQuery (const QXmlNamePool & np)
Constructs a query that will use np as its name pool.
The query cannot be evaluated until setQuery() has been called.
Definition at line 281 of file qxmlquery.cpp.
                                            : d(new QXmlQueryPrivate(np))
 {
 }
QXmlQuery() [4/4]
QXmlQuery::QXmlQuery (QueryLanguage queryLanguage, const QXmlNamePool & np = QXmlNamePool())
Constructs a query that will be used to run Xqueries or XSL-T stylesheets, depending on the value of queryLanguage.
It will use np as its name pool.
Note
If your QXmlQuery will process XSL-T stylesheets, this constructor must be used. The default constructor can only create instances of QXmlQuery for running XQueries.
The XSL-T support in this release is considered experimental. See the 2.0 {XSLT conformance} for details.
Since
4.5
See also
queryLanguage()
Definition at line 301 of file qxmlquery.cpp.
                                              : d(new QXmlQueryPrivate(np))
 {
     d->queryLanguage = queryLanguage;
 }
~QXmlQuery()
QXmlQuery::~QXmlQuery ()
Destroys this QXmlQuery.
Definition at line 310 of file qxmlquery.cpp.
 {
     delete d;
 }
Functions
bindVariable() [1/6]
void QXmlQuery::bindVariable (const QXmlName & name, const QXmlItem & value)
Binds the variable name to the value so that $name can be used from within the query to refer to the value.
name must not be null. {name}.isNull() must return false. If name has already been bound by a previous bindVariable() call, its previous binding will be overridden.
If {value} is null so that {value}.isNull() returns true, and {name} already has a binding, the effect is to remove the existing binding for {name}.
To bind a value of type QString or QUrl, wrap the value in a QVariant such that QXmlItem's QVariant constructor is called.
All strings processed by the query must be valid XQuery strings, which means they must contain only XML 1.0 characters. However, this requirement is not checked. If the query processes an invalid string, the behavior is undefined.
See also
QVariant::isValid(), {QtXDM}{How QVariant maps to XQuery's Data Model}, QXmlItem::isNull()
Definition at line 528 of file qxmlquery.cpp.
Referenced by bindVariable(), QDeclarativeXmlQueryEngine::doQueryJob(), and QDeclarativeXmlQueryEngine::doSubQueryJob().
 {
     if(name.isNull())
     {
         qWarning("The variable name cannot be null.");
         return;
     }
     const QPatternist::VariableLoader::Ptr vl(d->variableLoader());
     const QVariant variant(QVariant::fromValue(value));
     /* If the type of the variable changed(as opposed to only the value),
      * we will have to recompile. */
     if(vl->invalidationRequired(name, variant) || value.isNull())
         d->recompileRequired();
     vl->addBinding(name, variant);
 }
bindVariable() [2/6]
void QXmlQuery::bindVariable (const QString & localName, const QXmlItem & value)
This function constructs a QXmlName from localName using the query's QXmlNamePool {namespace}.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The function then behaves as the overloaded function. It is equivalent to the following snippet.
    QXmlNamePool namePool(query.namePool());
    query.bindVariable(QXmlName(namePool, localName), value);
Definition at line 559 of file qxmlquery.cpp.
 {
     bindVariable(QXmlName(d->namePool, localName), value);
 }
bindVariable() [3/6]
void QXmlQuery::bindVariable (const QXmlName & name, QIODevice * device)
Binds the variable name to the device so that $name can be used from within the query to refer to the device.
The QIODevice device is exposed to the query as a URI of type xs:anyURI, which can be passed to the fn:doc() function to be read. E.g., this function can be used to pass an XML document in memory to fn:doc.
    QByteArray myDocument;
    QBuffer buffer(&myDocument); // This is a QIODevice.
    buffer.open(QIODevice::ReadOnly);
    QXmlQuery query;
    query.bindVariable("myDocument", &buffer);
    query.setQuery("doc($myDocument)");
The caller must ensure that device has been opened with at least QIODevice::ReadOnly prior to this binding. Otherwise, behavior is undefined.
If the query will access an XML document contained in a QString, use a QBuffer as shown in the following snippet. Suppose myQString contains <document>content</document>
    QBuffer device;
    device.setData(myQString.toUtf8());
    device.open(QIODevice::ReadOnly);
    QXmlQuery query;
    query.bindVariable("inputDocument", &device);
    query.setQuery("doc($inputDocument)/query[theDocument]");
name must not be null. {name}.isNull() must return false. If name has already been bound, its previous binding will be overridden. The URI that name evaluates to is arbitrary and may change.
If the type of the variable binding changes (e.g., if a previous binding by the same name was a QVariant, or if there was no previous binding), isValid() will return false, and recompilation of the query text is required. To recompile the query, call setQuery(). For this reason, bindVariable() should be called before setQuery(), if possible.
Note
device must not be deleted while this QXmlQuery exists.
Definition at line 598 of file qxmlquery.cpp.
 {
     if(device && !device->isReadable())
     {
         qWarning("A null, or readable QIODevice must be passed.");
         return;
     }
     if(name.isNull())
     {
         qWarning("The variable name cannot be null.");
         return;
     }
     const QPatternist::VariableLoader::Ptr vl(d->variableLoader());
     if(device)
     {
         const QVariant variant(QVariant::fromValue(device));
         if(vl->invalidationRequired(name, variant))
             d->recompileRequired();
         vl->addBinding(name, variant);
         /* We need to tell the resource loader to discard its document, because
          * the underlying QIODevice has changed, but the variable name is the
          * same which means that the URI is the same, and hence the resource
          * loader will return the document for the old QIODevice.
          */
         d->resourceLoader()->clear(QUrl(QLatin1String("tag:trolltech.com,2007:QtXmlPatterns:QIODeviceVariable:") + d->namePool.d->stringForLocalName(name.localName())));
     }
     else
     {
         vl->removeBinding(name);
         d->recompileRequired();
     }
 }
bindVariable() [4/6]
void QXmlQuery::bindVariable (const QString & localName, QIODevice * device)
If localName is a valid QXmlName::isNCName() {NCName}, this function is equivalent to the following snippet.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
    QXmlNamePool namePool(query.namePool());
    query.bindVariable(QXmlName(namePool, localName), device);
A QXmlName is constructed from localName, and is passed to the appropriate overload along with device.
See also
QXmlName::isNCName()
Definition at line 653 of file qxmlquery.cpp.
 {
     bindVariable(QXmlName(d->namePool, localName), device);
 }
bindVariable() [5/6]
void QXmlQuery::bindVariable (const QXmlName & name, const QXmlQuery & query)
Binds the result of the query query, to a variable by name name.
Evaluation of query will be commenced when this function is called.
If query is invalid, behavior is undefined. query will be copied.
Since
4.5
See also
isValid()
Definition at line 1197 of file qxmlquery.cpp.
 {
     Q_ASSERT_X(query.isValid(), Q_FUNC_INFO, "The query being bound must be valid.");
     const QPatternist::VariableLoader::Ptr vl(d->variableLoader());
     const QVariant variant(QVariant::fromValue(query));
     if(vl->invalidationRequired(name, variant))
         d->recompileRequired();
     vl->addBinding(name, variant);
 }
bindVariable() [6/6]
void QXmlQuery::bindVariable (const QString & localName, const QXmlQuery & query)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Has the same behavior and effects as the function being overloaded, but takes the variable name localName as a QString.
query is used as in the overloaded function.
Since
4.5
Definition at line 1219 of file qxmlquery.cpp.
 {
     return bindVariable(QXmlName(d->namePool, localName), query);
 }
evaluateTo() [1/5]
void QXmlQuery::evaluateTo (QXmlResultItems * result) const
Starts the evaluation and makes it available in result.
If result is null, the behavior is undefined. The evaluation takes place incrementally (lazy evaluation), as the caller uses QXmlResultItems::next() to get the next result.
See also
QXmlResultItems::next()
Definition at line 815 of file qxmlquery.cpp.
Referenced by QDeclarativeXmlQueryEngine::doQueryJob(), QDeclarativeXmlQueryEngine::doSubQueryJob(), evaluateTo(), QDeclarativeXmlQueryEngine::getValuesOfKeyRoles(), and QPatternist::XsdValidatingInstanceReader::selectNodeSets().
 {
     if(!result)
     {
         qWarning("A null pointer cannot be passed.");
         return;
     }
     if(isValid())
     {
         try
         {
             /*
              * We don't have the d->expression() calls and
              * d->dynamicContext() calls in the same order as seen in
              * QXmlQuery::evaluateTo(), and the reason to why
              * that isn't a problem, is that we call isValid().
              */
             const QPatternist::DynamicContext::Ptr dynContext(d->dynamicContext());
             result->d_ptr->setDynamicContext(dynContext);
             result->d_ptr->iterator = d->expression()->evaluateSequence(dynContext);
         }
         catch(const QPatternist::Exception)
         {
             result->d_ptr->iterator = QPatternist::CommonValues::emptyIterator;
             result->d_ptr->hasError = true;
         }
     }
     else
     {
         result->d_ptr->iterator= QPatternist::CommonValues::emptyIterator;
         result->d_ptr->hasError = true;
     }
 }
evaluateTo() [2/5]
bool QXmlQuery::evaluateTo (QAbstractXmlReceiver * callback) const
Evaluates this query and sends the result as a sequence of callbacks to the QAbstractXmlReceiver {receiver} callback.
QXmlQuery does not take ownership of callback.
If an error occurs during the evaluation, error messages are sent to messageHandler() and false is returned.
If this query isValid() {is invalid}, false is returned and the behavior is undefined. If callback is null, behavior is undefined.
See also
QAbstractXmlReceiver, isValid()
Definition at line 672 of file qxmlquery.cpp.
 {
     if(!callback)
     {
         qWarning("A non-null callback must be passed.");
         return false;
     }
     if(isValid())
     {
         try
         {
             /*
              * This order is significant. expression() might cause
              * query recompilation, and as part of that it recreates
              * the static context. However, if we create the dynamic
              * context before the query recompilation has been
              * triggered, it will use the old static context, and
              * hence old source locations.
              */
             const QPatternist::Expression::Ptr expr(d->expression());
             const QPatternist::DynamicContext::Ptr dynContext(d->dynamicContext(callback));
             callback->startOfSequence();
             expr->evaluateToSequenceReceiver(dynContext);
             callback->endOfSequence();
             return true;
         }
         catch(const QPatternist::Exception)
         {
             return false;
         }
     }
     else
         return false;
 }
evaluateTo() [3/5]
bool QXmlQuery::evaluateTo (QStringList * target) const
Attempts to evaluate the query and returns the results in the target QStringList {string list}.
If the query isValid() {is valid} and the evaluation succeeds, true is returned. Otherwise, false is returned and the contents of target are undefined.
The query must evaluate to a sequence of xs:string values. If the query does not evaluate to a sequence of strings, the values can often be converted by adding a call to string() at the end of the XQuery.
If target is null, the behavior is undefined.
Definition at line 723 of file qxmlquery.cpp.
 {
     if(!target)
     {
         qWarning("A non-null callback must be passed.");
         return false;
     }
     if(isValid())
     {
         try
         {
             /*
              * This order is significant. expression() might cause
              * query recompilation, and as part of that it recreates
              * the static context. However, if we create the dynamic
              * context before the query recompilation has been
              * triggered, it will use the old static context, and
              * hence old source locations.
              */
             const QPatternist::Expression::Ptr expr(d->expression());
             if(!expr)
                 return false;
             QPatternist::DynamicContext::Ptr dynContext(d->dynamicContext());
             if(!QPatternist::BuiltinTypes::xsString->xdtTypeMatches(expr->staticType()->itemType()))
                 return false;
             const QPatternist::Item::Iterator::Ptr it(expr->evaluateSequence(dynContext));
             QPatternist::Item next(it->next());
             while(!next.isNull())
             {
                 target->append(next.stringValue());
                 next = it->next();
             }
             return true;
         }
         catch(const QPatternist::Exception)
         {
             return false;
         }
     }
     else
         return false;
 }
evaluateTo() [4/5]
bool QXmlQuery::evaluateTo (QIODevice * target) const
Evaluates the query or stylesheet, and writes the output to target.
QXmlSerializer is used to write the output to target. In a future release, it is expected that this function will be changed to respect serialization options set in the stylesheet.
If an error occurs during the evaluation, error messages are sent to messageHandler() and false is returned.
If target is null, or is not opened in at least QIODevice::WriteOnly mode, the behavior is undefined. QXmlQuery does not take ownership of target.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 789 of file qxmlquery.cpp.
 {
     if(!target)
     {
         qWarning("The pointer to the device cannot be null.");
         return false;
     }
     if(!target->isWritable())
     {
         qWarning("The device must be writable.");
         return false;
     }
     QXmlSerializer serializer(*this, target);
     return evaluateTo(&serializer);
 }
evaluateTo() [5/5]
bool QXmlQuery::evaluateTo (QString * output) const
Evaluates the query, and serializes the output as XML to output.
If an error occurs during the evaluation, error messages are sent to messageHandler(), the content of output is undefined and false is returned, otherwise true is returned.
If output is null behavior is undefined. QXmlQuery does not take ownership of output.
Internally, the class QXmlFormatter is used for this.
Since
4.5
Definition at line 863 of file qxmlquery.cpp.
 {
     Q_ASSERT_X(output, Q_FUNC_INFO,
                "The input cannot be null");
     QBuffer outputDevice;
     outputDevice.open(QIODevice::ReadWrite);
     QXmlFormatter formatter(*this, &outputDevice);
     const bool success = evaluateTo(&formatter);
     outputDevice.close();
     *output = QString::fromUtf8(outputDevice.data().constData());
     return success;
 }
initialTemplateName()
QXmlName QXmlQuery::initialTemplateName () const
Returns the name of the XSL-T stylesheet template that the processor will call first when running an XSL-T stylesheet.
This function only applies when using QXmlQuery to process XSL-T stylesheets. By default, no initial template is set. In that case, a default constructed QXmlName is returned.
Since
4.5
Definition at line 1159 of file qxmlquery.cpp.
 {
     return d->initialTemplateName;
 }
isValid()
bool QXmlQuery::isValid () const
Returns true if this query is valid.
Examples of invalid queries are ones that contain syntax errors or that have not had setQuery() called for them yet.
Definition at line 885 of file qxmlquery.cpp.
Referenced by bindVariable(), QDeclarativeXmlQueryEngine::doSubQueryJob(), evaluateTo(), and QPatternist::XsdSchemaParser::readXPathAttribute().
 {
     return d->isValid();
 }
messageHandler()
QAbstractMessageHandler * QXmlQuery::messageHandler () const
Returns the message handler that handles compile and runtime messages for this QXmlQuery.
Definition at line 380 of file qxmlquery.cpp.
 {
     return d->messageHandler;
 }
namePool()
QXmlNamePool QXmlQuery::namePool () const
Returns the name pool used by this QXmlQuery for constructing QXmlName {names}.
There is no setter for the name pool, because mixing name pools causes errors due to name confusion.
Definition at line 933 of file qxmlquery.cpp.
 {
     return d->namePool;
 }
networkAccessManager()
QNetworkAccessManager * QXmlQuery::networkAccessManager () const
Returns the network manager, or 0 if it has not been set.
See also
setNetworkAccessManager()
Since
4.5
Definition at line 1182 of file qxmlquery.cpp.
 {
     return d->m_networkAccessDelegator->m_genericManager;
 }
operator=()
QXmlQuery & QXmlQuery::operator= (const QXmlQuery & other)
Assigns other to this QXmlQuery instance.
Definition at line 318 of file qxmlquery.cpp.
 {
     /* Keep this section in sync with QXmlQuery::QXmlQuery(const QXmlQuery &).
      */
     if(d != other.d)
     {
         *d = *other.d;
         d->detach();
     }
     return *this;
 }
queryLanguage()
QXmlQuery::QueryLanguage QXmlQuery::queryLanguage () const
Returns a value indicating what this QXmlQuery is being used for.
The default is QXmlQuery::XQuery10, which means the QXmlQuery is being used for running XQuery and XPath queries. QXmlQuery::XSLT20 can also be returned, which indicates the QXmlQuery is for running XSL-T spreadsheets.
Since
4.5
Definition at line 1093 of file qxmlquery.cpp.
Referenced by QXmlQuery().
 {
     return d->queryLanguage;
 }
setFocus() [1/4]
void QXmlQuery::setFocus (const QXmlItem & item)
Sets the focus to item.
The focus is the set of items that the context item expression and path expressions navigate from. For example, in the expression p/span, the element that p evaluates to is the focus for the following expression, span.
The focus can be accessed using the context item expression, i.e., dot (".").
By default, the focus is not set and is undefined. It will therefore result in a dynamic error, XPDY0002, if the focus is attempted to be accessed. The focus must be set before the query is set with setQuery().
There is no behavior defined for setting an item which is null.
Definition at line 955 of file qxmlquery.cpp.
 {
     d->contextItem = item;
 }
setFocus() [2/4]
bool QXmlQuery::setFocus (const QUrl & documentURI)
Sets the focus to be the document located at documentURI and returns true.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
If documentURI cannot be loaded, false is returned. It is undefined at what time the document may be loaded. When loading the document, the message handler and URI resolver set on this QXmlQuery are used.
If documentURI is empty or is not a valid URI, the behavior of this function is undefined.
Definition at line 1025 of file qxmlquery.cpp.
 {
     Q_ASSERT_X(documentURI.isValid() && !documentURI.isEmpty(),
                Q_FUNC_INFO,
                "The URI passed must be valid.");
     return setFocusHelper(this, QVariant(documentURI));
 }
setFocus() [3/4]
bool QXmlQuery::setFocus (QIODevice * document)
Sets the focus to be the document read from the QIODevice and returns true.
If document cannot be loaded, false is returned.
QXmlQuery does not take ownership of document. The user guarantees that a document is available from the document device and that the document is not empty. The device must be opened in at least read-only mode. document must stay in scope as long as the current query is active.
Since
4.5 This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Definition at line 1048 of file qxmlquery.cpp.
 {
     if(!document)
     {
         qWarning("A null QIODevice pointer cannot be passed.");
         return false;
     }
     if(!document->isReadable())
     {
         qWarning("The device must be readable.");
         return false;
     }
     return setFocusHelper(this, document);
 }
setFocus() [4/4]
bool QXmlQuery::setFocus (const QString & focus)
This function behaves identically to calling the setFocus() overload with a QIODevice whose content is focus encoded as UTF-8.
That is, focus is treated as if it contained an XML document.
Returns the same result as the overload.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
Since
4.6
Definition at line 1075 of file qxmlquery.cpp.
 {
     QBuffer device;
     device.setData(focus.toUtf8());
     device.open(QIODevice::ReadOnly);
     return setFocusHelper(this, &device);
 }
setInitialTemplateName() [1/2]
void QXmlQuery::setInitialTemplateName (const QXmlName & name)
Sets the name of the initial template.
The initial template is the one the processor calls first, instead of attempting to match a template to the context node (if any). If an initial template is not set, the standard order of template invocation will be used.
This function only applies when using QXmlQuery to process XSL-T stylesheets. The name becomes part of the compiled stylesheet. Therefore, this function must be called before calling setQuery().
If the stylesheet has no template named name, the processor will use the standard order of template invocation.
Since
4.5
See also
initialTemplateName()
Definition at line 1114 of file qxmlquery.cpp.
Referenced by setInitialTemplateName().
 {
     d->initialTemplateName = name;
 }
setInitialTemplateName() [2/2]
void QXmlQuery::setInitialTemplateName (const QString & localName)
Sets the name of the initial template to localName, which must be a valid local name.
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.
The initial template is the one the processor calls first, instead of attempting to match a template to the context node (if any). If an initial template is not set, the standard order of template invocation will be used.
This function only applies when using QXmlQuery to process XSL-T stylesheets. The name becomes part of the compiled stylesheet. Therefore, this function must be called before calling setQuery().
If localName is not a valid local name, the effect is undefined. If the stylesheet has no template named localName, the processor will use the standard order of template invocation.
Since
4.5
See also
initialTemplateName()
Definition at line 1142 of file qxmlquery.cpp.
 {
     Q_ASSERT_X(QXmlName::isNCName(localName),
                Q_FUNC_INFO,
                "The name passed must be a valid NCName.");
     setInitialTemplateName(QXmlName(d->namePool, localName));
 }
setMessageHandler()
void QXmlQuery::setMessageHandler (QAbstractMessageHandler * aMessageHandler)
Changes the QAbstractMessageHandler {message handler} for this QXmlQuery to aMessageHandler.
The query sends all compile and runtime messages to this message handler. QXmlQuery does not take ownership of aMessageHandler.
Normally, the default message handler is sufficient. It writes compile and runtime messages to stderr. The default message handler includes color codes if stderr can render colors.
Note that changing the message handler after the query has been compiled has no effect, i.e. the query uses the same message handler at runtime that it uses at compile time.
When QXmlQuery calls QAbstractMessageHandler::message(), the arguments are as follows:
message() argument Semantics
QtMsgType type Only QtWarningMsg and QtFatalMsg are used. The former identifies a compile or runtime warning, while the latter identifies a dynamic or static error.
const QString & description An XHTML document which is the actual message. It is translated into the current language.
const QUrl &identifier Identifies the error with a URI, where the fragment is the error code, and the rest of the URI is the error namespace.
const QSourceLocation & sourceLocation Identifies where the error occurred.
Definition at line 371 of file qxmlquery.cpp.
 {
     d->messageHandler = aMessageHandler;
 }
setNetworkAccessManager()
void QXmlQuery::setNetworkAccessManager (QNetworkAccessManager * newManager)
Sets the network manager to newManager.
QXmlQuery does not take ownership of newManager.
See also
networkAccessManager()
Since
4.5
Definition at line 1171 of file qxmlquery.cpp.
 {
     d->m_networkAccessDelegator->m_genericManager = newManager;
 }
setQuery() [1/3]
void QXmlQuery::setQuery (const QString & sourceCode, const QUrl & documentURI = QUrl())
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts. The behavior and requirements of this function are the same as for setQuery(QIODevice*, const QUrl&), after the XQuery has been read from the IO device into a string.
Because sourceCode is already a Unicode string, detection of its encoding is unnecessary.
Definition at line 441 of file qxmlquery.cpp.
Referenced by QDeclarativeXmlQueryEngine::doQueryJob(), QDeclarativeXmlQueryEngine::doSubQueryJob(), QDeclarativeXmlQueryEngine::getValuesOfKeyRoles(), QPatternist::XsdSchemaParser::readXPathAttribute(), and setQuery().
 {
     Q_ASSERT_X(documentURI.isEmpty() || documentURI.isValid(), Q_FUNC_INFO,
                "The document URI must be valid.");
     QByteArray query(sourceCode.toUtf8());
     QBuffer buffer(&query);
     buffer.open(QIODevice::ReadOnly);
     setQuery(&buffer, documentURI);
 }
setQuery() [2/3]
void QXmlQuery::setQuery (QIODevice * sourceCode, const QUrl & documentURI = QUrl())
Sets this QXmlQuery to an XQuery read from the sourceCode device.
The device must have been opened with at least QIODevice::ReadOnly.
documentURI represents the query obtained from the sourceCode device. It is the base URI of the static context, as defined in the http://www.w3.org/TR/xquery/ {XQuery language}. It is used internally to resolve relative URIs that appear in the query, and for message reporting. documentURI can be empty. If it is empty, the application file path is used. If it is not empty, it may be either relative or absolute. If it is relative, it is resolved itself against the QCoreApplication::applicationFilePath() {application file path} before it is used. If documentURI is neither a valid URI nor empty, the result is undefined.
If the query contains a static error (e.g. syntax error), an error message is sent to the messageHandler(), and isValid() will return false.
Variables must be bound before setQuery() is called.
The encoding of the XQuery in sourceCode is detected internally using the rules for setting and detecting encoding of XQuery files, which are explained in the http://www.w3.org/TR/xquery/ {XQuery language}.
If sourceCode is null or not readable, or if documentURI is not a valid URI, behavior is undefined.
See also
isValid()
Definition at line 416 of file qxmlquery.cpp.
 {
     if(!sourceCode)
     {
         qWarning("A null QIODevice pointer cannot be passed.");
         return;
     }
     if(!sourceCode->isReadable())
     {
         qWarning("The device must be readable.");
         return;
     }
     d->queryURI = QPatternist::XPathHelper::normalizeQueryURI(documentURI);
     d->expression(sourceCode);
 }
setQuery() [3/3]
void QXmlQuery::setQuery (const QUrl & queryURI, const QUrl & baseURI = QUrl())
Sets this QXmlQuery to the XQuery read from the queryURI.
Use isValid() after calling this function. If an error occurred reading queryURI, e.g., the query does not exist, cannot be read, or is invalid, isValid() will return false.
The supported URI schemes are the same as those in the XQuery function fn:doc, except that queryURI can be the object of a variable binding.
baseURI is the Base URI of the static context, as defined in the http://www.w3.org/TR/xquery/ {XQuery language}. It is used internally to resolve relative URIs that appear in the query, and for message reporting. If baseURI is empty, queryURI is used. Otherwise, baseURI is used, and it is resolved against the QCoreApplication::applicationFilePath() {application file path} if it is relative.
If queryURI is empty or invalid, or if baseURI is invalid, the behavior of this function is undefined.
Definition at line 473 of file qxmlquery.cpp.
 {
     Q_ASSERT_X(queryURI.isValid(), Q_FUNC_INFO, "The passed URI must be valid.");
     const QUrl canonicalURI(QPatternist::XPathHelper::normalizeQueryURI(queryURI));
     Q_ASSERT(canonicalURI.isValid());
     Q_ASSERT(!canonicalURI.isRelative());
     Q_ASSERT(baseURI.isValid() || baseURI.isEmpty());
     d->queryURI = QPatternist::XPathHelper::normalizeQueryURI(baseURI.isEmpty() ? queryURI : baseURI);
     QPatternist::AutoPtr<QIODevice> result;
     try
     {
         result.reset(QPatternist::AccelTreeResourceLoader::load(canonicalURI, d->m_networkAccessDelegator,
                                                                 d->staticContext()));
     }
     catch(const QPatternist::Exception)
     {
         /* We do nothing, result will be 0. */
     }
     if(result)
     {
         setQuery(result.data(), d->queryURI);
         result->close();
     }
     else
         d->recompileRequired();
 }
setUriResolver()
void QXmlQuery::setUriResolver (const QAbstractUriResolver * resolver)
Sets the URI resolver to resolver.
QXmlQuery does not take ownership of resolver.
See also
uriResolver()
Definition at line 896 of file qxmlquery.cpp.
 {
     d->uriResolver = resolver;
 }
uriResolver()
const QAbstractUriResolver * QXmlQuery::uriResolver () const
Returns the query's URI resolver.
If no URI resolver has been set, QtXmlPatterns will use the URIs in queries as they are.
The URI resolver provides a level of abstraction, or polymorphic URIs. A resolver can rewrite logical URIs to physical ones, or it can translate obsolete or invalid URIs to valid ones.
QtXmlPatterns calls the URI resolver for all URIs it encounters, except for namespaces. Specifically, all builtin functions that deal with URIs (fn:doc(), and fn:doc-available()).
In the case of fn:doc(), the absolute URI is the base URI in the static context (which most likely is the location of the query). Rather than use the URI the user specified, the return value of QAbstractUriResolver::resolve() will be used.
When QtXmlPatterns calls QAbstractUriResolver::resolve() the absolute URI is the URI mandated by the XQuery language, and the relative URI is the URI specified by the user.
See also
setUriResolver()
Definition at line 924 of file qxmlquery.cpp.
 {
     return d->uriResolver;
 }
Friends and Related Functions
QPatternist::VariableLoader
friend class QPatternist::VariableLoader friend
Definition at line 146 of file qxmlquery.h.
QPatternist::XsdSchemaParser
friend class QPatternist::XsdSchemaParser friend
Definition at line 144 of file qxmlquery.h.
QPatternist::XsdValidatingInstanceReader
friend class QPatternist::XsdValidatingInstanceReader friend
Definition at line 145 of file qxmlquery.h.
QPatternistSDK::TestCase
friend class QPatternistSDK::TestCase friend
Definition at line 143 of file qxmlquery.h.
QueryLanguages
typedef QFlags<QXmlQuery::QueryLanguage> QueryLanguages related
Warning
This function is not part of the public interface.
Definition at line 245 of file qquerytransformparser.cpp.
QXmlName
friend class QXmlName friend
Definition at line 141 of file qxmlquery.h.
Referenced by bindVariable(), and setInitialTemplateName().
QXmlSerializer
friend class QXmlSerializer friend
Definition at line 142 of file qxmlquery.h.
setFocusHelper
template<typename TInputType > bool setFocusHelper (QXmlQuery *const queryInstance, const TInputType & focusValue) friend
This function should be a private member function of QXmlQuery, but we don't dare that due to our weird compilers.
Warning
This function is not part of the public interface.
Definition at line 967 of file qxmlquery.cpp.
Referenced by setFocus().
 {
     /* We call resourceLoader(), so we have ensured that we have a resourceLoader
      * that we will share in our copy. */
     queryInstance->d->resourceLoader();
     QXmlQuery focusQuery(*queryInstance);
     /* Now we use the same, so we own the loaded document. */
     focusQuery.d->m_resourceLoader = queryInstance->d->m_resourceLoader;
     /* The copy constructor doesn't allow us to copy an existing QXmlQuery and
      * changing the language at the same time so we need to use private API. */
     focusQuery.d->queryLanguage = QXmlQuery::XQuery10;
     Q_ASSERT(focusQuery.queryLanguage() == QXmlQuery::XQuery10);
     focusQuery.bindVariable(QChar::fromLatin1('u'), focusValue);
     focusQuery.setQuery(QLatin1String("doc($u)"));
     Q_ASSERT(focusQuery.isValid());
     QXmlResultItems focusResult;
     queryInstance->d->m_resourceLoader = focusQuery.d->m_resourceLoader;
     focusQuery.evaluateTo(&focusResult);
     const QXmlItem focusItem(focusResult.next());
     if(focusItem.isNull() || focusResult.hasError())
     {
         /* The previous focus must be cleared in error situations.
          * Otherwise the query may be left in an inconsistent state. */
         queryInstance->setFocus(QXmlItem());
         return false;
     }
     else
     {
         queryInstance->setFocus(focusItem);
         return true;
     }
 }
Properties
d
QXmlQueryPrivate* QXmlQuery::d private
Definition at line 149 of file qxmlquery.h.
Referenced by QPatternist::VariableLoader::announceExternalVariable(), bindVariable(), QPatternist::VariableLoader::evaluateSequence(), evaluateTo(), initialTemplateName(), isValid(), messageHandler(), namePool(), networkAccessManager(), operator=(), queryLanguage(), QXmlQuery(), QPatternist::XsdSchemaParser::readXPathAttribute(), setFocus(), setInitialTemplateName(), setMessageHandler(), setNetworkAccessManager(), setQuery(), setUriResolver(), uriResolver(), and ~QXmlQuery().
The documentation for this class was generated from the following files:
/src/xmlpatterns/api/qxmlquery.h
/src/xmlpatterns/parser/qquerytransformparser.cpp
/src/xmlpatterns/api/qxmlquery.cpp