Qt 4.8: QSpanBuffer Class Reference
QSpanBuffer Class Reference
Public Functions
void addSpan (int x, unsigned int len, int y, unsigned char coverage)
QSpanBuffer (ProcessSpans blend, void *data, const QRect &clipRect)
~QSpanBuffer ()
Private Functions
void flushSpans ()
Properties
ProcessSpans m_blend
QRect m_clipRect
void * m_data
int m_spanCount
QT_FT_Span m_spans [SPAN_BUFFER_SIZE]
Detailed Description
Definition at line 74 of file qrasterizer.cpp.
Constructors and Destructors
QSpanBuffer()
QSpanBuffer::QSpanBuffer (ProcessSpans blend, void * data, const QRect & clipRect) inline
Definition at line 76 of file qrasterizer.cpp.
         : m_spanCount(0)
         , m_blend(blend)
         , m_data(data)
         , m_clipRect(clipRect)
     {
     }
~QSpanBuffer()
QSpanBuffer::~QSpanBuffer () inline
Definition at line 84 of file qrasterizer.cpp.
     {
         flushSpans();
     }
Functions
addSpan()
void QSpanBuffer::addSpan (int x, unsigned int len, int y, unsigned char coverage) inline
Definition at line 89 of file qrasterizer.cpp.
Referenced by QScanConverter::emitNode(), qScanConvert(), and QRasterizer::rasterizeLine().
     {
         if (!coverage || !len)
             return;
         Q_ASSERT(y >= m_clipRect.top());
         Q_ASSERT(y <= m_clipRect.bottom());
         Q_ASSERT(x >= m_clipRect.left());
         Q_ASSERT(x + int(len) - 1 <= m_clipRect.right());
         m_spans[m_spanCount].x = x;
         m_spans[m_spanCount].len = len;
         m_spans[m_spanCount].y = y;
         m_spans[m_spanCount].coverage = coverage;
         if (++m_spanCount == SPAN_BUFFER_SIZE)
             flushSpans();
     }
flushSpans()
void QSpanBuffer::flushSpans () inline private
Definition at line 109 of file qrasterizer.cpp.
Referenced by addSpan(), and ~QSpanBuffer().
     {
         m_blend(m_spanCount, m_spans, m_data);
         m_spanCount = 0;
     }
Properties
m_blend
ProcessSpans QSpanBuffer::m_blend private
Definition at line 118 of file qrasterizer.cpp.
Referenced by flushSpans().
m_clipRect
QRect QSpanBuffer::m_clipRect private
Definition at line 121 of file qrasterizer.cpp.
Referenced by addSpan().
m_data
void* QSpanBuffer::m_data private
Definition at line 119 of file qrasterizer.cpp.
Referenced by flushSpans().
m_spanCount
int QSpanBuffer::m_spanCount private
Definition at line 116 of file qrasterizer.cpp.
Referenced by addSpan(), and flushSpans().
m_spans
QT_FT_Span QSpanBuffer::m_spans[SPAN_BUFFER_SIZE] private
Definition at line 115 of file qrasterizer.cpp.
Referenced by addSpan(), and flushSpans().
The documentation for this class was generated from the following file:
/src/gui/painting/qrasterizer.cpp