Qt 4.8: ModelIndexIterator Class Reference
ModelIndexIterator Class Reference
Public Functions
QModelIndex current () const
bool isHidden () const
ModelIndexIterator (QAbstractItemView *view, const QModelIndex &start=QModelIndex())
bool next (int count=1)
Properties
QListView * list
QModelIndex m_current
QAbstractItemView * m_view
QTableView * table
QTreeView * tree
Detailed Description
Definition at line 710 of file complexwidgets.cpp.
Constructors and Destructors
ModelIndexIterator()
ModelIndexIterator::ModelIndexIterator (QAbstractItemView * view, const QModelIndex & start = QModelIndex()) inline
Definition at line 713 of file complexwidgets.cpp.
                                                                                           : m_view(view)
     {
 #ifndef QT_NO_LISTVIEW
         list = qobject_cast<QListView*>(m_view);
 #endif
 #ifndef QT_NO_TREEVIEW
         tree = qobject_cast<QTreeView*>(m_view);
 #endif
 #ifndef QT_NO_TABLEVIEW
         table = qobject_cast<QTableView*>(m_view);
 #endif
         if (start.isValid()) {
             m_current = start;
         } else if (m_view && m_view->model()) {
             m_current = view->rootIndex().isValid() ?
                         view->rootIndex().child(0,0) : view->model()->index(0, 0);
         }
     }
Functions
current()
QModelIndex ModelIndexIterator::current () const inline
Definition at line 787 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::childIndex().
{
         return m_current;
     }
isHidden()
bool ModelIndexIterator::isHidden () const inline
Definition at line 769 of file complexwidgets.cpp.
{
         if (false) {
 #ifndef QT_NO_LISTVIEW
         } else if (list) {
             return list->isRowHidden(m_current.row());
 #endif
 #ifndef QT_NO_TREEVIEW
         } else if (tree) {
             return tree->isRowHidden(m_current.row(), m_current.parent());
 #endif
 #ifndef QT_NO_TABLEVIEW
         } else if (table) {
             return table->isRowHidden(m_current.row());
 #endif
         }
         return false;
     }
next()
bool ModelIndexIterator::next (int count = 1) inline
Definition at line 732 of file complexwidgets.cpp.
Referenced by QAccessibleItemView::childCount(), and QAccessibleItemView::childIndex().
{
         for (int i = 0; i < count; ++i) {
             do {
                 if (m_current.isValid()) {
                     const QAbstractItemModel *m = m_current.model();
 #ifndef QT_NO_TREEVIEW
                     if (tree && m_current.model()->hasChildren(m_current) && tree->isExpanded(m_current)) {
                         m_current = m_current.child(0, 0);
                     } else
 #endif
                     {
                         int row = m_current.row();
                         QModelIndex par = m_current.parent();
                         // Go up to the parent if we reach the end of the rows
                         // If m_curent becomses invalid, stop going up.
                         while (row + 1 >= m->rowCount(par)) {
                             m_current = par;
                             if (m_current.isValid()) {
                                 row = m_current.row();
                                 par = m_current.parent();
                             } else {
                                 row = 0;
                                 par = QModelIndex();
                                 break;
                             }
                         }
                         if (m_current.isValid())
                             m_current = m_current.sibling(row + 1, 0);
                     }
                 }
             } while (isHidden());
         }
         return m_current.isValid();
     }
Properties
list
QListView* ModelIndexIterator::list private
Definition at line 799 of file complexwidgets.cpp.
m_current
QModelIndex ModelIndexIterator::m_current private
Definition at line 792 of file complexwidgets.cpp.
m_view
QAbstractItemView* ModelIndexIterator::m_view private
Definition at line 793 of file complexwidgets.cpp.
table
QTableView* ModelIndexIterator::table private
Definition at line 802 of file complexwidgets.cpp.
tree
QTreeView* ModelIndexIterator::tree private
Definition at line 796 of file complexwidgets.cpp.
The documentation for this class was generated from the following file:
/src/plugins/accessible/widgets/complexwidgets.cpp