Qt 4.8: ShaderEffect Class Reference
ShaderEffect Class Reference
#include <shadereffect.h>
Public Functions
void addRenderTarget (ShaderEffectSource *target)
void removeRenderTarget (ShaderEffectSource *target)
ShaderEffect (QObject *parent=0)
~ShaderEffect ()
Public Functions inherited from QGraphicsEffect
QRectF boundingRect () const
Returns the effective bounding rectangle for this effect, i.e., the bounding rectangle of the source in device coordinates, adjusted by any margins applied by the effect itself.
virtual QRectF boundingRectFor (const QRectF &sourceRect) const
Returns the effective bounding rectangle for this effect, given the provided rect in the device coordinates.
bool isEnabled () const
QGraphicsEffect (QObject *parent=0)
Constructs a new QGraphicsEffect instance having the specified parent.
QGraphicsEffectSource * source () const
Returns a pointer to the source, which provides extra context information that can be useful for the effect.
virtual ~QGraphicsEffect ()
Removes the effect from the source, and destroys the graphics effect.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
bool m_changed: 1
QVector< ShaderEffectSource * > m_renderTargets
Protected Functions
virtual void draw (QPainter *painter)
This pure virtual function draws the effect and is called whenever the source needs to be drawn.
virtual void sourceChanged (ChangeFlags flags)
This virtual function is called by QGraphicsEffect to notify the effect that the source has changed.
Protected Functions inherited from QGraphicsEffect
void drawSource (QPainter *painter)
Draws the source directly using the given painter.
QGraphicsEffect (QGraphicsEffectPrivate &d, QObject *parent=0)
QRectF sourceBoundingRect (Qt::CoordinateSystem system=Qt::LogicalCoordinates) const
Returns the bounding rectangle of the source mapped to the given system.
bool sourceIsPixmap () const
Returns true if the source effectively is a pixmap, e.g., a QGraphicsPixmapItem.
QPixmap sourcePixmap (Qt::CoordinateSystem system=Qt::LogicalCoordinates, QPoint *offset=0, PixmapPadMode mode=PadToEffectiveBoundingRect) const
Returns a pixmap with the source painted into it.
void updateBoundingRect ()
This function notifies the effect framework when the effect's bounding rectangle has changed.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Private Functions
bool hideOriginal () const
void prepareBufferedDraw (QPainter *painter)
void updateRenderTargets ()
Additional Inherited Members
Public Types inherited from QGraphicsEffect
enum ChangeFlag { SourceAttached = 0x1, SourceDetached = 0x2, SourceBoundingRectChanged = 0x4, SourceInvalidated = 0x8 }
This enum describes what has changed in QGraphicsEffectSource.
enum PixmapPadMode { NoPad, PadToTransparentBorder, PadToEffectiveBoundingRect }
This enum describes how the pixmap returned from sourcePixmap should be padded.
Public Slots inherited from QGraphicsEffect
void setEnabled (bool enable)
void update ()
Schedules a redraw of the effect.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QGraphicsEffect
void enabledChanged (bool enabled)
This signal is emitted whenever the effect is enabled or disabled.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 53 of file shadereffect.h.
Constructors and Destructors
ShaderEffect()
ShaderEffect::ShaderEffect (QObject * parent = 0)
Definition at line 52 of file shadereffect.cpp.
     : QGraphicsEffect(parent)
     , m_changed(true)
 {
 }
~ShaderEffect()
ShaderEffect::~ShaderEffect ()
Definition at line 58 of file shadereffect.cpp.
 {
 }
Functions
addRenderTarget()
void ShaderEffect::addRenderTarget (ShaderEffectSource * target)
Definition at line 169 of file shadereffect.cpp.
Referenced by ShaderEffectSource::attachSourceItem().
 {
     if (!m_renderTargets.contains(target))
         m_renderTargets.append(target);
 }
draw()
void ShaderEffect::draw (QPainter * painter) protected virtual
This pure virtual function draws the effect and is called whenever the source needs to be drawn.
Reimplement this function in a QGraphicsEffect subclass to provide the effect's drawing implementation, using painter.
For example:
MyGraphicsEffect::draw(QPainter *painter)
{
    ...
    QPoint offset;
    if (sourceIsPixmap()) {
        // No point in drawing in device coordinates (pixmap will be scaled anyways).
        const QPixmap pixmap = sourcePixmap(Qt::LogicalCoordinates, &offset);
        ...
        painter->drawPixmap(offset, pixmap);
    } else {
        // Draw pixmap in device coordinates to avoid pixmap scaling;
        const QPixmap pixmap = sourcePixmap(Qt::DeviceCoordinates, &offset);
        painter->setWorldTransform(QTransform());
        ...
        painter->drawPixmap(offset, pixmap);
    }
    ...
}
This function should not be called explicitly by the user, since it is meant for reimplementation purposes only.
Implements QGraphicsEffect.
Definition at line 79 of file shadereffect.cpp.
 {
     const QGLContext *context = QGLContext::currentContext();
     prepareBufferedDraw(painter);
     if (context) {
         updateRenderTargets();
     }
     if (!context || m_renderTargets.count() == 0 || !hideOriginal())
         drawSource(painter);
 }
hideOriginal()
bool ShaderEffect::hideOriginal () const private
Definition at line 184 of file shadereffect.cpp.
Referenced by draw().
 {
     if (m_renderTargets.count() == 0)
         return false;
     // Just like scenegraph version, if there is even one source that says "hide original" we hide it.
     int count = m_renderTargets.count();
     for (int i = 0; i < count; i++) {
         if (m_renderTargets[i]->hideSource())
             return true;
     }
     return false;
 }
prepareBufferedDraw()
void ShaderEffect::prepareBufferedDraw (QPainter * painter) private
Definition at line 62 of file shadereffect.cpp.
Referenced by draw().
 {
 #ifndef QT_NO_DYNAMIC_CAST
     // This workaround needed because QGraphicsEffect seems to always utilize default painters worldtransform
     // instead of the active painters worldtransform.
     const ShaderEffectBuffer *effectBuffer = dynamic_cast<ShaderEffectBuffer*> (painter->device());
     if (effectBuffer) {
         savedWorldTransform = painter->worldTransform() * savedWorldTransform;
         painter->setWorldTransform(savedWorldTransform);
     } else {
         savedWorldTransform = painter->worldTransform();
     }
 #else
     Q_UNUSED(painter);
 #endif
 }
removeRenderTarget()
void ShaderEffect::removeRenderTarget (ShaderEffectSource * target)
Definition at line 175 of file shadereffect.cpp.
Referenced by ShaderEffectSource::detachSourceItem().
 {
     int index = m_renderTargets.indexOf(target);
     if (index >= 0)
         m_renderTargets.remove(index);
     else
         qWarning() << "ShaderEffect::removeRenderTarget - did not find target.";
 }
sourceChanged()
void ShaderEffect::sourceChanged (ChangeFlags flags) protected virtual
This virtual function is called by QGraphicsEffect to notify the effect that the source has changed.
If the effect applies any cache, then this cache must be purged in order to reflect the new appearance of the source.
The flags describes what has changed.
Reimplemented from QGraphicsEffect.
Definition at line 163 of file shadereffect.cpp.
 {
     Q_UNUSED(flags);
     m_changed = true;
 }
updateRenderTargets()
void ShaderEffect::updateRenderTargets () private
Definition at line 93 of file shadereffect.cpp.
Referenced by draw().
 {
     if (!m_changed)
         return;
     m_changed = false;
     int count = m_renderTargets.count();
     for (int i = 0; i < count; i++) {
         if (m_renderTargets[i]->isLive() || m_renderTargets[i]->isDirtyTexture()) {
             m_renderTargets[i]->updateBackbuffer();
             ShaderEffectBuffer* target = m_renderTargets[i]->fbo();
             if (target && target->isValid() && target->width() > 0 && target->height() > 0) {
                 QPainter p(target);
                 p.setCompositionMode(QPainter::CompositionMode_Clear);
                 p.fillRect(QRect(QPoint(0, 0), target->size()), Qt::transparent);
                 p.setCompositionMode(QPainter::CompositionMode_SourceOver);
                 QRectF sourceRect = m_renderTargets[i]->sourceRect();
                 QSize textureSize = m_renderTargets[i]->textureSize();
                 qreal yflip = m_renderTargets[i]->isMirrored() ? -1.0 : 1.0; // flip y to match scenegraph, it also flips texturecoordinates
                 qreal xscale = 1.0;
                 qreal yscale = 1.0 * yflip;
                 qreal leftMargin = 0.0;
                 qreal rightMargin = 0.0;
                 qreal topMargin = 0.0;
                 qreal bottomMargin = 0.0;
                 qreal width = m_renderTargets[i]->sourceItem()->width();
                 qreal height = m_renderTargets[i]->sourceItem()->height();
                 if (!sourceRect.isEmpty()) {
                     leftMargin = -sourceRect.left();
                     rightMargin = sourceRect.right() - width;
                     topMargin = -sourceRect.top();
                     bottomMargin = sourceRect.bottom() - height;
                 }
                 if ((width + leftMargin + rightMargin) > 0 && (height + topMargin + bottomMargin) > 0) {
                     if (!textureSize.isEmpty()) {
                         qreal textureWidth = textureSize.width();
                         qreal textureHeight = textureSize.height();
                         xscale = width / (width + leftMargin + rightMargin);
                         yscale = height / (height + topMargin + bottomMargin);
                         p.translate(textureWidth / 2, textureHeight / 2);
                         p.scale(xscale, yscale * yflip);
                         p.translate(-textureWidth / 2, -textureHeight / 2);
                         p.scale(textureWidth / width, textureHeight / height);
                     } else {
                         xscale = width / (width + leftMargin + rightMargin);
                         yscale = height / (height + topMargin + bottomMargin);
                         p.translate(width / 2, height / 2);
                         p.scale(xscale, yscale * yflip);
                         p.translate(-width / 2, -height / 2);
                     }
                 }
                 drawSource(&p);
                 p.end();
                 m_renderTargets[i]->markSceneGraphDirty();
             }
         }
     }
 }
Properties
m_changed
bool ShaderEffect::m_changed
Definition at line 74 of file shadereffect.h.
Referenced by ShaderEffectSource::markSourceItemDirty(), sourceChanged(), and updateRenderTargets().
m_renderTargets
QVector<ShaderEffectSource*> ShaderEffect::m_renderTargets
Definition at line 73 of file shadereffect.h.
Referenced by addRenderTarget(), draw(), hideOriginal(), removeRenderTarget(), and updateRenderTargets().
The documentation for this class was generated from the following files:
/src/imports/shaders/shadereffect.h
/src/imports/shaders/shadereffect.cpp