Qt 4.8: QPaintBuffer Class Reference
QPaintBuffer Class Reference
#include <qpaintbuffer_p.h>
Public Functions
void beginNewFrame ()
QRectF boundingRect () const
QString commandDescription (int command) const
virtual int devType () const
void draw (QPainter *painter, int frame=0) const
int frameEndIndex (int frame) const
int frameStartIndex (int frame) const
bool isEmpty () const
virtual int metric (PaintDeviceMetric m) const
int numFrames () const
QPaintBuffer & operator= (const QPaintBuffer &other)
virtual QPaintEngine * paintEngine () const
int processCommands (QPainter *painter, int begin, int end) const
QPaintBuffer ()
QPaintBuffer (const QPaintBuffer &other)
void setBoundingRect (const QRectF &rect)
~QPaintBuffer ()
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
virtual HDC getDC () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
virtual void releaseDC (HDC hdc) const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Properties
QPaintBufferPrivate * d_ptr
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &stream, const QPaintBuffer &buffer)
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &stream, QPaintBuffer &buffer)
class QOpenGLReplayer
class QPainterReplayer
Additional Inherited Members
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Protected Variables inherited from QPaintDevice
ushort painters
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
Definition at line 67 of file qpaintbuffer_p.h.
Constructors and Destructors
QPaintBuffer() [1/2]
QPaintBuffer::QPaintBuffer ()
Definition at line 171 of file qpaintbuffer.cpp.
     : d_ptr(new QPaintBufferPrivate)
 {
 }
QPaintBuffer() [2/2]
QPaintBuffer::QPaintBuffer (const QPaintBuffer & other)
Definition at line 182 of file qpaintbuffer.cpp.
     : QPaintDevice(), d_ptr(other.d_ptr)
 {
     d_ptr->ref.ref();
 }
~QPaintBuffer()
QPaintBuffer::~QPaintBuffer ()
Definition at line 176 of file qpaintbuffer.cpp.
 {
     if (!d_ptr->ref.deref())
         delete d_ptr;
 }
Functions
beginNewFrame()
void QPaintBuffer::beginNewFrame ()
Definition at line 1392 of file qpaintbuffer.cpp.
Referenced by QTraceWindowSurface::beginPaint().
 {
     if (!d_ptr->commands.isEmpty())
         d_ptr->frames << d_ptr->commands.size();
 }
boundingRect()
QRectF QPaintBuffer::boundingRect () const
Definition at line 558 of file qpaintbuffer.cpp.
 {
     return d_ptr->boundingRect;
 }
commandDescription()
QString QPaintBuffer::commandDescription (int command) const
Definition at line 315 of file qpaintbuffer.cpp.
 {
     QString desc;
     QDebug debug(&desc);
     const QPaintBufferCommand &cmd = d_ptr->commands.at(command);
     switch (cmd.id) {
     case QPaintBufferPrivate::Cmd_Save: {
         debug << "Cmd_Save";
         break; }
     case QPaintBufferPrivate::Cmd_Restore: {
         debug << "Cmd_Restore";
         break; }
     case QPaintBufferPrivate::Cmd_SetBrush: {
         QBrush brush = qvariant_cast<QBrush>(d_ptr->variants.at(cmd.offset));
         debug << "Cmd_SetBrush: " << brush;
         break; }
     case QPaintBufferPrivate::Cmd_SetBrushOrigin: {
         debug << "Cmd_SetBrushOrigin: " << d_ptr->variants.at(cmd.offset).toPointF();
         break; }
     case QPaintBufferPrivate::Cmd_SetCompositionMode: {
         QPainter::CompositionMode mode = (QPainter::CompositionMode) cmd.extra;
         debug << "ExCmd_SetCompositionMode, mode: " << mode;
         break; }
     case QPaintBufferPrivate::Cmd_SetOpacity: {
         debug << "ExCmd_SetOpacity: " << d_ptr->variants.at(cmd.offset).toDouble();
         break; }
     case QPaintBufferPrivate::Cmd_DrawVectorPath: {
         debug << "ExCmd_DrawVectorPath: size: " << cmd.size
 //                 << ", hints:" << d->ints[cmd.offset2+cmd.size]
                  << "pts/elms:" << cmd.offset << cmd.offset2;
         break; }
     case QPaintBufferPrivate::Cmd_StrokeVectorPath: {
         QPen pen = qvariant_cast<QPen>(d_ptr->variants.at(cmd.extra));
         debug << "ExCmd_StrokeVectorPath: size: " << cmd.size
 //                 << ", hints:" << d->ints[cmd.offset2+cmd.size]
                  << "pts/elms:" << cmd.offset << cmd.offset2 << pen;
         break; }
     case QPaintBufferPrivate::Cmd_FillVectorPath: {
         QBrush brush = qvariant_cast<QBrush>(d_ptr->variants.at(cmd.extra));
         debug << "ExCmd_FillVectorPath: size: " << cmd.size
 //                 << ", hints:" << d->ints[cmd.offset2+cmd.size]
                  << "pts/elms:" << cmd.offset << cmd.offset2 << brush;
         break; }
     case QPaintBufferPrivate::Cmd_FillRectBrush: {
         QBrush brush = qvariant_cast<QBrush>(d_ptr->variants.at(cmd.extra));
         QRectF *rect = (QRectF *)(d_ptr->floats.constData() + cmd.offset);
         debug << "ExCmd_FillRectBrush, offset: " << cmd.offset << " rect: " << *rect << " brush: " << brush;
         break; }
     case QPaintBufferPrivate::Cmd_FillRectColor: {
         QColor color = qvariant_cast<QColor>(d_ptr->variants.at(cmd.extra));
         QRectF *rect = (QRectF *)(d_ptr->floats.constData() + cmd.offset);
         debug << "ExCmd_FillRectBrush, offset: " << cmd.offset << " rect: " << *rect << " color: " << color;
         break; }
     case QPaintBufferPrivate::Cmd_DrawPolygonF: {
         debug << "ExCmd_DrawPolygonF, offset: " << cmd.offset << " size: " << cmd.size
                  << " mode: " << cmd.extra
                  << d_ptr->floats.at(cmd.offset)
                  << d_ptr->floats.at(cmd.offset+1);
         break; }
     case QPaintBufferPrivate::Cmd_DrawPolygonI: {
         debug << "ExCmd_DrawPolygonI, offset: " << cmd.offset << " size: " << cmd.size
                  << " mode: " << cmd.extra
                  << d_ptr->ints.at(cmd.offset)
                  << d_ptr->ints.at(cmd.offset+1);
         break; }
     case QPaintBufferPrivate::Cmd_DrawEllipseF: {
         debug << "ExCmd_DrawEllipseF, offset: " << cmd.offset;
         break; }
     case QPaintBufferPrivate::Cmd_DrawLineF: {
         debug << "ExCmd_DrawLineF, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawLineI: {
         debug << "ExCmd_DrawLineI, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawPointsF: {
         debug << "ExCmd_DrawPointsF, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawPointsI: {
         debug << "ExCmd_DrawPointsI, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawPolylineF: {
         debug << "ExCmd_DrawPolylineF, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawPolylineI: {
         debug << "ExCmd_DrawPolylineI, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawRectF: {
         debug << "ExCmd_DrawRectF, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawRectI: {
         debug << "ExCmd_DrawRectI, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_SetClipEnabled: {
         bool clipEnabled = d_ptr->variants.at(cmd.offset).toBool();
         debug << "ExCmd_SetClipEnabled:" << clipEnabled;
         break; }
     case QPaintBufferPrivate::Cmd_ClipVectorPath: {
         QVectorPathCmd path(d_ptr, cmd);
         debug << "ExCmd_ClipVectorPath:" << path().elementCount();
         break; }
     case QPaintBufferPrivate::Cmd_ClipRect: {
         QRect rect(QPoint(d_ptr->ints.at(cmd.offset), d_ptr->ints.at(cmd.offset + 1)),
                    QPoint(d_ptr->ints.at(cmd.offset + 2), d_ptr->ints.at(cmd.offset + 3)));
         debug << "ExCmd_ClipRect:" << rect << cmd.extra;
         break; }
     case QPaintBufferPrivate::Cmd_ClipRegion: {
         QRegion region(d_ptr->variants.at(cmd.offset).value<QRegion>());
         debug << "ExCmd_ClipRegion:" << region.boundingRect() << cmd.extra;
         break; }
     case QPaintBufferPrivate::Cmd_SetPen: {
         QPen pen = qvariant_cast<QPen>(d_ptr->variants.at(cmd.offset));
         debug << "Cmd_SetPen: " << pen;
         break; }
     case QPaintBufferPrivate::Cmd_SetTransform: {
         QTransform xform = qvariant_cast<QTransform>(d_ptr->variants.at(cmd.offset));
         debug << "Cmd_SetTransform, offset: " << cmd.offset << xform;
         break; }
     case QPaintBufferPrivate::Cmd_SetRenderHints: {
         debug << "Cmd_SetRenderHints, hints: " << cmd.extra;
         break; }
     case QPaintBufferPrivate::Cmd_SetBackgroundMode: {
         debug << "Cmd_SetBackgroundMode: " << cmd.extra;
         break; }
     case QPaintBufferPrivate::Cmd_DrawConvexPolygonF: {
         debug << "Cmd_DrawConvexPolygonF, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawConvexPolygonI: {
         debug << "Cmd_DrawConvexPolygonI, offset: " << cmd.offset << " size: " << cmd.size;
         break; }
     case QPaintBufferPrivate::Cmd_DrawEllipseI: {
         debug << "Cmd_DrawEllipseI, offset: " << cmd.offset;
         break; }
     case QPaintBufferPrivate::Cmd_DrawPixmapRect: {
         QPixmap pm(d_ptr->variants.at(cmd.offset).value<QPixmap>());
         QRectF r(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1),
                  d_ptr->floats.at(cmd.extra+2), d_ptr->floats.at(cmd.extra+3));
         QRectF sr(d_ptr->floats.at(cmd.extra+4), d_ptr->floats.at(cmd.extra+5),
                   d_ptr->floats.at(cmd.extra+6), d_ptr->floats.at(cmd.extra+7));
         debug << "Cmd_DrawPixmapRect:" << r << sr << pm.size();
         break; }
     case QPaintBufferPrivate::Cmd_DrawPixmapPos: {
         QPixmap pm(d_ptr->variants.at(cmd.offset).value<QPixmap>());
         QPointF pos(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1));
         debug << "Cmd_DrawPixmapPos:" << pos << pm.size();
         break; }
     case QPaintBufferPrivate::Cmd_DrawTiledPixmap: {
         QPixmap pm(d_ptr->variants.at(cmd.offset).value<QPixmap>());
         QRectF r(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1),
                  d_ptr->floats.at(cmd.extra+2), d_ptr->floats.at(cmd.extra+3));
         QPointF offset(d_ptr->floats.at(cmd.extra+4), d_ptr->floats.at(cmd.extra+5));
         debug << "Cmd_DrawTiledPixmap:" << r << offset << pm.size();
         break; }
     case QPaintBufferPrivate::Cmd_DrawImageRect: {
         QImage image(d_ptr->variants.at(cmd.offset).value<QImage>());
         QRectF r(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1),
                  d_ptr->floats.at(cmd.extra+2), d_ptr->floats.at(cmd.extra+3));
         QRectF sr(d_ptr->floats.at(cmd.extra+4), d_ptr->floats.at(cmd.extra+5),
                   d_ptr->floats.at(cmd.extra+6), d_ptr->floats.at(cmd.extra+7));
         debug << "Cmd_DrawImageRect:" << r << sr << image.size();
         break; }
     case QPaintBufferPrivate::Cmd_DrawImagePos: {
         QImage image(d_ptr->variants.at(cmd.offset).value<QImage>());
         QPointF pos(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1));
         debug << "Cmd_DrawImagePos:" << pos << image.size();
         break; }
     case QPaintBufferPrivate::Cmd_DrawText: {
         QPointF pos(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1));
         QList<QVariant> variants(d_ptr->variants.at(cmd.offset).value<QList<QVariant> >());
         QFont font(variants.at(0).value<QFont>());
         QString text(variants.at(1).value<QString>());
         debug << "Cmd_DrawText:" << pos << text << font.family();
         break; }
     case QPaintBufferPrivate::Cmd_DrawTextItem: {
         QPointF pos(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1));
         QTextItemIntCopy *tiCopy = reinterpret_cast<QTextItemIntCopy *>(qvariant_cast<void *>(d_ptr->variants.at(cmd.offset)));
         QTextItemInt &ti = (*tiCopy)();
         QString text(ti.text());
         debug << "Cmd_DrawTextItem:" << pos << " " << text;
         break; }
     case QPaintBufferPrivate::Cmd_SystemStateChanged: {
         QRegion systemClip(d_ptr->variants.at(cmd.offset).value<QRegion>());
         debug << "Cmd_SystemStateChanged:" << systemClip;
         break; }
     case QPaintBufferPrivate::Cmd_Translate: {
         QPointF delta(d_ptr->floats.at(cmd.extra), d_ptr->floats.at(cmd.extra+1));
         debug << "Cmd_Translate:" << delta;
         break; }
     case QPaintBufferPrivate::Cmd_DrawStaticText: {
         debug << "Cmd_DrawStaticText";
         break; }
     }
     return desc;
 }
devType()
int QPaintBuffer::devType () const virtual
Reimplemented from QPaintDevice.
Definition at line 222 of file qpaintbuffer.cpp.
 {
     return QInternal::PaintBuffer;
 }
draw()
void QPaintBuffer::draw (QPainter * painter, int frame = 0) const
Definition at line 246 of file qpaintbuffer.cpp.
Referenced by QTraceWindowSurface::endPaint().
 {
 #ifdef QPAINTBUFFER_DEBUG_DRAW
     qDebug() << "QPaintBuffer::draw() --------------------------------";
     Q_D(const QPaintBuffer);
     printf("Float buffer:");
     for (int i=0; i<d->floats.size(); i++) {
         if ((i % 10) == 0) {
             printf("\n%4d-%4d: ", i, i+9);
         }
         printf("%4.2f  ", d->floats[i]);
     }
     printf("\n");
     printf("Int Buffer:");
     for (int i=0; i<d->ints.size(); i++) {
         if ((i % 10) == 0) {
             printf("\n%4d-%4d: ", i, i+10);
         }
         printf("%5d", d->ints[i]);
     }
     printf("\n");
 #endif
     processCommands(painter, frameStartIndex(frame), frameEndIndex(frame));
 #ifdef QPAINTBUFFER_DEBUG_DRAW
     qDebug() << "QPaintBuffer::draw() -------------------------------- DONE!";
 #endif
 }
frameEndIndex()
int QPaintBuffer::frameEndIndex (int frame) const
Definition at line 283 of file qpaintbuffer.cpp.
Referenced by draw().
 {
     return (frame == d_ptr->frames.size()) ? d_ptr->commands.size() : d_ptr->frames.at(frame);
 }
frameStartIndex()
int QPaintBuffer::frameStartIndex (int frame) const
Definition at line 278 of file qpaintbuffer.cpp.
Referenced by draw().
 {
     return (frame == 0) ? 0 : d_ptr->frames.at(frame - 1);
 }
isEmpty()
bool QPaintBuffer::isEmpty () const
Definition at line 239 of file qpaintbuffer.cpp.
 {
     return d_ptr->commands.isEmpty();
 }
metric()
int QPaintBuffer::metric (PaintDeviceMetric m) const virtual
Reimplemented from QPaintDevice.
Definition at line 197 of file qpaintbuffer.cpp.
 {
     int val = 0;
     switch (metric) {
     case PdmWidth:
         val = qCeil(d_ptr->boundingRect.width());
         break;
     case PdmHeight:
         val = qCeil(d_ptr->boundingRect.height());
         break;
     case PdmDpiX:
     case PdmPhysicalDpiX:
         val = qt_defaultDpiX();
         break;
     case PdmDpiY:
     case PdmPhysicalDpiY:
         val = qt_defaultDpiY();
         break;
     default:
         val = QPaintDevice::metric(metric);
     }
     return val;
 }
numFrames()
int QPaintBuffer::numFrames () const
Definition at line 1398 of file qpaintbuffer.cpp.
Referenced by QTraceWindowSurface::endPaint().
 {
     return d_ptr->frames.size() + 1;
 }
operator=()
QPaintBuffer & QPaintBuffer::operator= (const QPaintBuffer & other)
Definition at line 227 of file qpaintbuffer.cpp.
 {
     if (other.d_ptr != d_ptr) {
         QPaintBufferPrivate *data = other.d_ptr;
         data->ref.ref();
         if (d_ptr->ref.deref())
             delete d_ptr;
         d_ptr = data;
     }
     return *this;
 }
paintEngine()
QPaintEngine * QPaintBuffer::paintEngine () const virtual
Implements QPaintDevice.
Definition at line 188 of file qpaintbuffer.cpp.
 {
     QPaintBufferPrivate *d = const_cast<QPaintBuffer *>(this)->d_ptr;
     if (!d->engine)
         d->engine = new QPaintBufferEngine(d);
     return d->engine;
 }
processCommands()
int QPaintBuffer::processCommands (QPainter * painter, int begin, int end) const
Definition at line 288 of file qpaintbuffer.cpp.
Referenced by draw().
 {
     if (!painter || !painter->isActive())
         return 0;
     QPaintEngineEx *xengine = painter->paintEngine()->isExtended()
                               ? (QPaintEngineEx *) painter->paintEngine() : 0;
     if (xengine) {
         QPaintEngineExReplayer player;
         player.processCommands(*this, painter, begin, end);
     } else {
         QPainterReplayer player;
         player.processCommands(*this, painter, begin, end);
     }
     int depth = 0;
     for (int i = begin; i < end; ++i) {
         const QPaintBufferCommand &cmd = d_ptr->commands.at(i);
         if (cmd.id == QPaintBufferPrivate::Cmd_Save)
             ++depth;
         else if (cmd.id == QPaintBufferPrivate::Cmd_Restore)
             --depth;
     }
     return depth;
 }
setBoundingRect()
void QPaintBuffer::setBoundingRect (const QRectF & rect)
Definition at line 563 of file qpaintbuffer.cpp.
Referenced by QTraceWindowSurface::paintDevice().
 {
     d_ptr->boundingRect = rect;
     d_ptr->calculateBoundingRect = false;
 }
Friends and Related Functions
operator<<
Q_GUI_EXPORT QDataStream& operator<< (QDataStream & stream, const QPaintBuffer & buffer) friend
Definition at line 2181 of file qpaintbuffer.cpp.
 {
     QHash<qint64, uint> pixmapKeys;
     QHash<qint64, uint> imageKeys;
     QHash<qint64, QPixmap> pixmaps;
     QHash<qint64, QImage> images;
     QVector<QVariant> variants = buffer.d_ptr->variants;
     for (int i = 0; i < variants.size(); ++i) {
         const QVariant &v = variants.at(i);
         if (v.type() == QVariant::Image) {
             const QImage image(v.value<QImage>());
             QPaintBufferCacheEntryV2 entry;
             entry.flags.type = QPaintBufferCacheEntryV2::ImageKey;
             QHash<qint64, uint>::iterator it = imageKeys.find(image.cacheKey());
             if (it != imageKeys.end()) {
                 entry.flags.key = *it;
             } else {
                 imageKeys[image.cacheKey()] = entry.flags.key = images.size();
                 images[images.size()] = image;
             }
             variants[i] = QVariant::fromValue(entry);
         } else if (v.type() == QVariant::Pixmap) {
             const QPixmap pixmap(v.value<QPixmap>());
             QPaintBufferCacheEntryV2 entry;
             entry.flags.type = QPaintBufferCacheEntryV2::PixmapKey;
             QHash<qint64, uint>::iterator it = pixmapKeys.find(pixmap.cacheKey());
             if (it != pixmapKeys.end()) {
                 entry.flags.key = *it;
             } else {
                 pixmapKeys[pixmap.cacheKey()] = entry.flags.key = pixmaps.size();
                 pixmaps[pixmaps.size()] = pixmap;
             }
             variants[i] = QVariant::fromValue(entry);
         }
     }
     stream << pixmaps;
     stream << images;
     stream << buffer.d_ptr->ints;
     stream << buffer.d_ptr->floats;
     stream << variants;
     stream << buffer.d_ptr->commands;
     stream << buffer.d_ptr->boundingRect;
     stream << buffer.d_ptr->frames;
     return stream;
 }
operator>>
Q_GUI_EXPORT QDataStream& operator>> (QDataStream & stream, QPaintBuffer & buffer) friend
Definition at line 2238 of file qpaintbuffer.cpp.
 {
     QHash<qint64, QPixmap> pixmaps;
     QHash<qint64, QImage> images;
     stream >> pixmaps;
     stream >> images;
     stream >> buffer.d_ptr->ints;
     stream >> buffer.d_ptr->floats;
     stream >> buffer.d_ptr->variants;
     stream >> buffer.d_ptr->commands;
     stream >> buffer.d_ptr->boundingRect;
     stream >> buffer.d_ptr->frames;
     QVector<QVariant> &variants = buffer.d_ptr->variants;
     for (int i = 0; i < variants.size(); ++i) {
         const QVariant &v = variants.at(i);
         if (v.canConvert<QPaintBufferCacheEntry>()) {
             QPaintBufferCacheEntry entry = v.value<QPaintBufferCacheEntry>();
             if (entry.type == QVariant::Image)
                 variants[i] = QVariant(images.value(entry.cacheKey));
             else
                 variants[i] = QVariant(pixmaps.value(entry.cacheKey));
         } else if (v.canConvert<QPaintBufferCacheEntryV2>()) {
             QPaintBufferCacheEntryV2 entry = v.value<QPaintBufferCacheEntryV2>();
             if (entry.flags.type == QPaintBufferCacheEntryV2::ImageKey)
                 variants[i] = QVariant(images.value(entry.flags.key));
             else if (entry.flags.type == QPaintBufferCacheEntryV2::PixmapKey)
                 variants[i] = QVariant(pixmaps.value(entry.flags.key));
             else
                 qWarning() << "operator<<(QDataStream &stream, QPaintBuffer &buffer): unrecognized cache entry type:" << entry.flags.type;
         }
     }
     return stream;
 }
QOpenGLReplayer
friend class QOpenGLReplayer friend
Definition at line 100 of file qpaintbuffer_p.h.
QPainterReplayer
friend class QPainterReplayer friend
Definition at line 99 of file qpaintbuffer_p.h.
Properties
d_ptr
QPaintBufferPrivate* QPaintBuffer::d_ptr private
Definition at line 105 of file qpaintbuffer_p.h.
Referenced by boundingRect(), commandDescription(), frameEndIndex(), frameStartIndex(), isEmpty(), metric(), operator=(), operator>>(), paintEngine(), processCommands(), QPainterReplayer::processCommands(), QPaintBuffer(), setBoundingRect(), and ~QPaintBuffer().
The documentation for this class was generated from the following files:
/src/gui/painting/qpaintbuffer_p.h
/src/gui/painting/qpaintbuffer.cpp