Qt 4.8: QSqlField Class Reference
QSqlField Class Reference
The QSqlField class manipulates the fields in SQL database tables and views.
#include <qsqlfield.h>
Public Types
enum RequiredStatus { Unknown = -1, Optional = 0, Required = 1 }
Specifies whether the field is required or optional.
Public Functions
void clear ()
Clears the value of the field and sets it to NULL.
QVariant defaultValue () const
Returns the field's default value (which may be NULL).
bool isAutoValue () const
Returns true if the value is auto-generated by the database, for example auto-increment primary key values.
bool isGenerated () const
Returns true if the field is generated; otherwise returns false.
bool isNull () const
Returns true if the field's value is NULL; otherwise returns false.
bool isReadOnly () const
Returns true if the field's value is read-only; otherwise returns false.
bool isValid () const
Returns true if the field's variant type is valid; otherwise returns false.
int length () const
Returns the field's length.
QString name () const
Returns the name of the field.
bool operator!= (const QSqlField &other) const
Returns true if the field is unequal to other; otherwise returns false.
QSqlField & operator= (const QSqlField &other)
Sets the field equal to other.
bool operator== (const QSqlField &other) const
Returns true if the field is equal to other; otherwise returns false.
int precision () const
Returns the field's precision; this is only meaningful for numeric types.
QSqlField (const QString &fieldName=QString(), QVariant::Type type=QVariant::Invalid)
Constructs an empty field called fieldName of variant type type.
QSqlField (const QSqlField &other)
Constructs a copy of other.
RequiredStatus requiredStatus () const
Returns true if this is a required field; otherwise returns false.
void setAutoValue (bool autoVal)
Marks the field as an auto-generated value if autoVal is true.
void setDefaultValue (const QVariant &value)
Sets the default value used for this field to value.
void setGenerated (bool gen)
Sets the generated state.
void setLength (int fieldLength)
Sets the field's length to fieldLength.
void setName (const QString &name)
Sets the name of the field to name.
void setPrecision (int precision)
Sets the field's precision.
void setReadOnly (bool readOnly)
Sets the read only flag of the field's value to readOnly.
void setRequired (bool required)
Sets the required status of this field to Required if required is true; otherwise sets it to Optional .
void setRequiredStatus (RequiredStatus status)
Sets the required status of this field to required.
void setSqlType (int type)
void setType (QVariant::Type type)
Set's the field's variant type to type.
void setValue (const QVariant &value)
Sets the value of the field to value.
QVariant::Type type () const
Returns the field's type as stored in the database.
int typeID () const
Returns the type ID for the field.
QVariant value () const
Returns the value of the field as a QVariant.
~QSqlField ()
Destroys the object and frees any allocated resources.
Private Functions
void detach ()
Properties
QSqlFieldPrivate * d
QVariant val
Detailed Description
The QSqlField class manipulates the fields in SQL database tables and views.
Attention
Module: QtSql
QSqlField represents the characteristics of a single column in a database table or view, such as the data type and column name. A field also contains the value of the database column, which can be viewed or changed.
Field data values are stored as QVariants. Using an incompatible type is not permitted. For example:
    QSqlField field("age", QVariant::Int);
    field.setValue(QPixmap());  // WRONG
However, the field will attempt to cast certain data types to the field data type where possible:
    QSqlField field("age", QVariant::Int);
    field.setValue(QString("123"));  // casts QString to int
QSqlField objects are rarely created explicitly in application code. They are usually accessed indirectly through QSqlRecord that already contain a list of fields. For example:
    QSqlQuery query;
...
    QSqlRecord record = query.record();
    QSqlField field = record.field("country");
A QSqlField object can provide some meta-data about the field, for example, its name(), variant type(), length(), precision(), defaultValue(), typeID(), and its requiredStatus(), isGenerated() and isReadOnly(). The field's data can be checked to see if it isNull(), and its value() retrieved. When editing the data can be set with setValue() or set to NULL with clear().
See also
QSqlRecord
Definition at line 56 of file qsqlfield.h.
Enumerations
RequiredStatus
enum QSqlField::RequiredStatus
Specifies whether the field is required or optional.
Required The field must be specified when inserting records.
Optional The fields doesn't have to be specified when inserting records.
Unknown The database driver couldn't determine whether the field is required or optional.
See also
requiredStatus()
Enumerator
Unknown
Optional
Required
Definition at line 59 of file qsqlfield.h.
 { Unknown = -1, Optional = 0, Required = 1 };
Constructors and Destructors
QSqlField() [1/2]
QSqlField::QSqlField (const QString & fieldName = QString(), QVariant::Type type = QVariant::Invalid)
Constructs an empty field called fieldName of variant type type.
See also
setRequiredStatus() setLength() setPrecision() setDefaultValue() setGenerated() setReadOnly()
Definition at line 168 of file qsqlfield.cpp.
 {
     d = new QSqlFieldPrivate(fieldName, type);
     val = QVariant(type);
 }
QSqlField() [2/2]
QSqlField::QSqlField (const QSqlField & other)
Constructs a copy of other.
Definition at line 178 of file qsqlfield.cpp.
 {
     d = other.d;
     d->ref.ref();
     val = other.val;
 }
~QSqlField()
QSqlField::~QSqlField ()
Destroys the object and frees any allocated resources.
Definition at line 219 of file qsqlfield.cpp.
 {
     if (!d->ref.deref())
         delete d;
 }
Functions
clear()
void QSqlField::clear (void)
Clears the value of the field and sets it to NULL.
If the field is read-only, nothing happens.
See also
setValue() isReadOnly() requiredStatus()
Definition at line 334 of file qsqlfield.cpp.
Referenced by QSqlResult::exec(), and qCreateParamString().
 {
     if (isReadOnly())
         return;
     val = QVariant(type());
 }
defaultValue()
QVariant QSqlField::defaultValue () const
Returns the field's default value (which may be NULL).
See also
setDefaultValue() type() requiredStatus() length() precision() isGenerated()
Definition at line 481 of file qsqlfield.cpp.
Referenced by operator<<().
 {
     return d->def;
 }
detach()
void QSqlField::detach () private
Warning
This function is not part of the public interface.
Definition at line 433 of file qsqlfield.cpp.
 {
     qAtomicDetach(d);
 }
isAutoValue()
bool QSqlField::isAutoValue () const
Returns true if the value is auto-generated by the database, for example auto-increment primary key values.
See also
setAutoValue()
Definition at line 564 of file qsqlfield.cpp.
 {
     return d->autoval;
 }
isGenerated()
bool QSqlField::isGenerated () const
Returns true if the field is generated; otherwise returns false.
See also
setGenerated() type() requiredStatus() length() precision() defaultValue()
Definition at line 508 of file qsqlfield.cpp.
Referenced by operator<<().
 {
     return d->gen;
 }
isNull()
bool QSqlField::isNull () const
Returns true if the field's value is NULL; otherwise returns false.
See also
value()
Definition at line 428 of file qsqlfield.cpp.
Referenced by QDB2Driver::formatValue(), QSqlDriver::formatValue(), QTDSDriver::formatValue(), QMYSQLDriver::formatValue(), QODBCDriver::formatValue(), and QPSQLDriver::formatValue().
 { return val.isNull(); }
isReadOnly()
bool QSqlField::isReadOnly () const
Returns true if the field's value is read-only; otherwise returns false.
See also
setReadOnly() type() requiredStatus() length() precision() defaultValue() isGenerated()
Definition at line 419 of file qsqlfield.cpp.
 { return d->ro; }
isValid()
bool QSqlField::isValid () const
Returns true if the field's variant type is valid; otherwise returns false.
Definition at line 517 of file qsqlfield.cpp.
Referenced by QDB2Result::data(), and QSqlTableModel::orderByClause().
 {
     return d->type != QVariant::Invalid;
 }
length()
int QSqlField::length () const
Returns the field's length.
If the returned value is negative, it means that the information is not available from the database.
See also
setLength() type() requiredStatus() precision() defaultValue() isGenerated()
Definition at line 457 of file qsqlfield.cpp.
Referenced by QDB2Result::data(), QODBCResult::data(), and operator<<().
 {
     return d->len;
 }
name()
QString QSqlField::name () const
Returns the name of the field.
See also
setName()
Definition at line 380 of file qsqlfield.cpp.
Referenced by QSqlRecordPrivate::createField(), QSqlIndex::createField(), operator<<(), and QSqlTableModel::orderByClause().
 {
     return d->nm;
 }
operator!=()
bool QSqlField::operator!= (const QSqlField & other) const inline
Returns true if the field is unequal to other; otherwise returns false.
Definition at line 67 of file qsqlfield.h.
 { return !operator==(other); }
operator=()
QSqlField & QSqlField::operator= (const QSqlField & other)
Sets the field equal to other.
Definition at line 189 of file qsqlfield.cpp.
 {
     qAtomicAssign(d, other.d);
     val = other.val;
     return *this;
 }
operator==()
bool QSqlField::operator== (const QSqlField & other) const
Returns true if the field is equal to other; otherwise returns false.
Definition at line 209 of file qsqlfield.cpp.
 {
     return ((d == other.d || *d == *other.d)
             && val == other.val);
 }
precision()
int QSqlField::precision () const
Returns the field's precision; this is only meaningful for numeric types.
If the returned value is negative, it means that the information is not available from the database.
See also
setPrecision() type() requiredStatus() length() defaultValue() isGenerated()
Definition at line 471 of file qsqlfield.cpp.
Referenced by operator<<().
 {
     return d->prec;
 }
requiredStatus()
QSqlField::RequiredStatus QSqlField::requiredStatus () const
Returns true if this is a required field; otherwise returns false.
An INSERT will fail if a required field does not have a value.
See also
setRequiredStatus() type() length() precision() defaultValue() isGenerated()
Definition at line 444 of file qsqlfield.cpp.
Referenced by operator<<().
 {
     return d->req;
 }
setAutoValue()
void QSqlField::setAutoValue (bool autoVal)
Marks the field as an auto-generated value if autoVal is true.
See also
isAutoValue()
Definition at line 575 of file qsqlfield.cpp.
Referenced by qExtractSecurityPolicyFromString(), qGetTableInfo(), and qToField().
 {
     detach();
     d->autoval = autoVal;
 }
setDefaultValue()
void QSqlField::setDefaultValue (const QVariant & value)
Sets the default value used for this field to value.
See also
defaultValue() value() setType() setRequiredStatus() setLength() setPrecision() setGenerated() setReadOnly()
Definition at line 276 of file qsqlfield.cpp.
Referenced by QPSQLDriver::record().
 {
     detach();
     d->def = value;
 }
setGenerated()
void QSqlField::setGenerated (bool gen)
Sets the generated state.
If gen is false, no SQL will be generated for this field; otherwise, Qt classes such as QSqlQueryModel and QSqlTableModel will generate SQL for this field.
See also
isGenerated() setType() setRequiredStatus() setLength() setPrecision() setDefaultValue() setReadOnly()
Definition at line 299 of file qsqlfield.cpp.
Referenced by QSqlQueryModel::insertColumns().
 {
     detach();
     d->gen = gen;
 }
setLength()
void QSqlField::setLength (int fieldLength)
Sets the field's length to fieldLength.
For strings this is the maximum number of characters the string can hold; the meaning varies for other types.
See also
length() setType() setRequiredStatus() setPrecision() setDefaultValue() setGenerated() setReadOnly()
Definition at line 254 of file qsqlfield.cpp.
Referenced by qFromOraInf(), qMakeFieldInfo(), qToField(), QIBaseResult::record(), QPSQLResult::record(), QIBaseDriver::record(), QTDSDriver::record(), QPSQLDriver::record(), and QTDSResult::reset().
 {
     detach();
     d->len = fieldLength;
 }
setName()
void QSqlField::setName (const QString & name)
Sets the name of the field to name.
See also
name()
Definition at line 347 of file qsqlfield.cpp.
Referenced by QPSQLResult::record().
 {
     detach();
     d->nm = name;
 }
setPrecision()
void QSqlField::setPrecision (int precision)
Sets the field's precision.
This only affects numeric fields.
See also
precision() setType() setRequiredStatus() setLength() setDefaultValue() setGenerated() setReadOnly()
Definition at line 265 of file qsqlfield.cpp.
Referenced by qFromOraInf(), qMakeFieldInfo(), qToField(), QPSQLResult::record(), QTDSDriver::record(), and QPSQLDriver::record().
 {
     detach();
     d->prec = precision;
 }
setReadOnly()
void QSqlField::setReadOnly (bool readOnly)
Sets the read only flag of the field's value to readOnly.
A read-only field cannot have its value set with setValue() and cannot be cleared to NULL with clear().
Definition at line 358 of file qsqlfield.cpp.
Referenced by QSqlQueryModel::insertColumns().
 {
     detach();
     d->ro = readOnly;
 }
setRequired()
void QSqlField::setRequired (bool required) inline
Sets the required status of this field to Required if required is true; otherwise sets it to Optional .
See also
setRequiredStatus(), requiredStatus()
Definition at line 84 of file qsqlfield.h.
Referenced by qFromOraInf(), qMakeFieldInfo(), qToField(), QOCIDriver::record(), and QPSQLDriver::record().
     { setRequiredStatus(required ? Required : Optional); }
setRequiredStatus()
void QSqlField::setRequiredStatus (RequiredStatus required)
Sets the required status of this field to required.
See also
requiredStatus() setType() setLength() setPrecision() setDefaultValue() setGenerated() setReadOnly()
Definition at line 230 of file qsqlfield.cpp.
 {
     detach();
     d->req = required;
 }
setSqlType()
void QSqlField::setSqlType (int type)
Warning
This function is not part of the public interface.
Definition at line 285 of file qsqlfield.cpp.
Referenced by QSQLiteResultPrivate::initColumns(), qFromOraInf(), qMakeFieldInfo(), qToField(), QPSQLResult::record(), QTDSDriver::record(), QPSQLDriver::record(), and QTDSResult::reset().
 {
     detach();
     d->tp = type;
 }
setType()
void QSqlField::setType (QVariant::Type type)
Set's the field's variant type to type.
See also
type() setRequiredStatus() setLength() setPrecision() setDefaultValue() setGenerated() setReadOnly()
Definition at line 404 of file qsqlfield.cpp.
Referenced by qCreateParamString(), and QPSQLResult::record().
 {
     detach();
     d->type = type;
     if (!val.isValid())
         val = QVariant(type);
 }
setValue()
void QSqlField::setValue (const QVariant & value)
Sets the value of the field to value.
If the field is read-only (isReadOnly() returns true), nothing happens.
If the data type of value differs from the field's current data type, an attempt is made to cast it to the proper type. This preserves the data type of the field in the case of assignment, e.g. a QString to an integer data type.
To set the value to NULL, use clear().
See also
value() isReadOnly() defaultValue()
Definition at line 320 of file qsqlfield.cpp.
Referenced by QSqlResult::exec(), and qCreateParamString().
 {
     if (isReadOnly())
         return;
     val = value;
 }
type()
QVariant::Type QSqlField::type () const
Returns the field's type as stored in the database.
Note that the actual value might have a different type, Numerical values that are too large to store in a long int or double are usually stored as strings to prevent precision loss.
See also
setType()
Definition at line 394 of file qsqlfield.cpp.
Referenced by QDB2Result::data(), QODBCResult::data(), QDB2Driver::formatValue(), QSqlDriver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QTDSDriver::formatValue(), QMYSQLDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), QTDSResult::gotoNext(), operator<<(), and QSQLite2Driver::primaryIndex().
 {
     return d->type;
 }
typeID()
int QSqlField::typeID () const
Returns the type ID for the field.
Warning
This function is not part of the public interface.
If the returned value is negative, it means that the information is not available from the database.
Definition at line 497 of file qsqlfield.cpp.
Referenced by operator<<().
 {
     return d->tp;
 }
value()
QVariant QSqlField::value () const inline
Returns the value of the field as a QVariant.
Use isNull() to check if the field's value is NULL.
Definition at line 71 of file qsqlfield.h.
Referenced by QDB2Driver::formatValue(), QSqlDriver::formatValue(), QIBaseDriver::formatValue(), QOCIDriver::formatValue(), QTDSDriver::formatValue(), QMYSQLDriver::formatValue(), QODBCDriver::formatValue(), QPSQLDriver::formatValue(), and QRelation::populateDictionary().
     { return val; }
Properties
d
QSqlFieldPrivate* QSqlField::d private
Definition at line 108 of file qsqlfield.h.
Referenced by operator=(), operator==(), and QSqlField().
val
QVariant QSqlField::val private
Definition at line 107 of file qsqlfield.h.
Referenced by operator=(), operator==(), and QSqlField().
The documentation for this class was generated from the following files:
/src/sql/kernel/qsqlfield.h
/src/sql/kernel/qsqlfield.cpp