Qt 4.8: QNmDBusHelper Class Reference
QNmDBusHelper Class Reference
#include <qnmdbushelper.h>
Public Slots
void deviceStateChanged (quint32)
void slotAccessPointAdded (QDBusObjectPath)
void slotAccessPointRemoved (QDBusObjectPath)
void slotPropertiesChanged (QMap< QString, QVariant >)
void slotSettingsRemoved ()
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void pathForAccessPointAdded (const QString &, QDBusObjectPath)
void pathForAccessPointRemoved (const QString &, QDBusObjectPath)
void pathForPropertiesChanged (const QString &, QMap< QString, QVariant >)
void pathForSettingsRemoved (const QString &)
void pathForStateChanged (const QString &, quint32)
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
QNmDBusHelper (QObject *parent=0)
~QNmDBusHelper ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Additional Inherited Members
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Functions inherited from QDBusContext
bool calledFromDBus () const
Returns true if we are processing a D-Bus call.
QDBusConnection connection () const
Returns the connection from which this call was received.
bool isDelayedReply () const
Returns true if this call will have a delayed reply.
const QDBusMessage & message () const
Returns the message that generated this call.
QDBusContext ()
Constructs an empty QDBusContext.
void sendErrorReply (const QString &name, const QString &msg=QString()) const
Sends an error name as a reply to the caller.
void sendErrorReply (QDBusError::ErrorType type, const QString &msg=QString()) const
Sends an error type as a reply to the caller.
void setDelayedReply (bool enable) const
Sets whether this call will have a delayed reply or not.
~QDBusContext ()
An empty destructor.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 53 of file qnmdbushelper.h.
Constructors and Destructors
QNmDBusHelper()
QNmDBusHelper::QNmDBusHelper (QObject * parent = 0)
Definition at line 59 of file qnmdbushelper.cpp.
         : QObject(parent)
 {
 }
~QNmDBusHelper()
QNmDBusHelper::~QNmDBusHelper ()
Definition at line 64 of file qnmdbushelper.cpp.
 {
 }
Functions
deviceStateChanged
void QNmDBusHelper::deviceStateChanged (quint32 state) slot
Definition at line 68 of file qnmdbushelper.cpp.
  {
     QDBusMessage msg = this->message();
     if(state == NM_DEVICE_STATE_ACTIVATED
        || state == NM_DEVICE_STATE_DISCONNECTED
        || state == NM_DEVICE_STATE_UNAVAILABLE
        || state == NM_DEVICE_STATE_FAILED) {
         emit pathForStateChanged(msg.path(), state);
     }
  }
pathForAccessPointAdded
void QNmDBusHelper::pathForAccessPointAdded (const QString & , QDBusObjectPath) signal
Referenced by slotAccessPointAdded().
pathForAccessPointRemoved
void QNmDBusHelper::pathForAccessPointRemoved (const QString & , QDBusObjectPath) signal
Referenced by slotAccessPointRemoved().
pathForPropertiesChanged
void QNmDBusHelper::pathForPropertiesChanged (const QString & , QMap< QString, QVariant >) signal
Referenced by slotPropertiesChanged().
pathForSettingsRemoved
void QNmDBusHelper::pathForSettingsRemoved (const QString &) signal
Referenced by slotSettingsRemoved().
pathForStateChanged
void QNmDBusHelper::pathForStateChanged (const QString & , quint32) signal
Referenced by deviceStateChanged().
slotAccessPointAdded
void QNmDBusHelper::slotAccessPointAdded (QDBusObjectPath path) slot
Definition at line 79 of file qnmdbushelper.cpp.
 {
     if(path.path().length() > 2) {
         QDBusMessage msg = this->message();
         emit pathForAccessPointAdded(msg.path(), path);
     }
 }
slotAccessPointRemoved
void QNmDBusHelper::slotAccessPointRemoved (QDBusObjectPath path) slot
Definition at line 87 of file qnmdbushelper.cpp.
 {
     if(path.path().length() > 2) {
         QDBusMessage msg = this->message();
         emit pathForAccessPointRemoved(msg.path(), path);
     }
 }
slotPropertiesChanged
void QNmDBusHelper::slotPropertiesChanged (QMap< QString, QVariant > map) slot
Definition at line 95 of file qnmdbushelper.cpp.
 {
     QDBusMessage msg = this->message();
     QMapIterator<QString, QVariant> i(map);
     while (i.hasNext()) {
         i.next();
         if( i.key() == "State") { //state only applies to device interfaces
             quint32 state = i.value().toUInt();
             if( state == NM_DEVICE_STATE_ACTIVATED
                 || state == NM_DEVICE_STATE_DISCONNECTED
                 || state == NM_DEVICE_STATE_UNAVAILABLE
                 || state == NM_DEVICE_STATE_FAILED) {
                 emit  pathForPropertiesChanged( msg.path(), map);
             }
         } else if( i.key() == "ActiveAccessPoint") {
             emit pathForPropertiesChanged(msg.path(), map);
             //            qWarning()  << __PRETTY_FUNCTION__ << i.key() << ": " << i.value().value<QDBusObjectPath>().path();
             //      } else if( i.key() == "Strength")
             //            qWarning()  << __PRETTY_FUNCTION__ << i.key() << ": " << i.value().toUInt();
             //   else
             //            qWarning()  << __PRETTY_FUNCTION__ << i.key() << ": " << i.value();
         } else if (i.key() == "ActiveConnections") {
             emit pathForPropertiesChanged(msg.path(), map);
         }
     }
 }
slotSettingsRemoved
void QNmDBusHelper::slotSettingsRemoved () slot
Definition at line 122 of file qnmdbushelper.cpp.
 {
     QDBusMessage msg = this->message();
     emit pathForSettingsRemoved(msg.path());
 }
The documentation for this class was generated from the following files:
/src/plugins/bearer/networkmanager/qnmdbushelper.h
/src/plugins/bearer/networkmanager/qnmdbushelper.cpp