Qt 4.8: QAElement Class Reference
QAElement Class Reference
#include <qaccessible_mac_p.h>
Public Functions
AXUIElementRef element () const
int id () const
bool isValid () const
HIObjectRef object () const
void operator= (const QAElement &other)
bool operator== (const QAElement &other) const
QAElement ()
QAElement (AXUIElementRef elementRef)
QAElement (const QAElement &element)
QAElement (HIObjectRef, int child)
~QAElement ()
Properties
AXUIElementRef elementRef
Detailed Description
Definition at line 373 of file qaccessible_mac_p.h.
Constructors and Destructors
QAElement() [1/4]
QAElement::QAElement ()
Definition at line 484 of file qaccessible_mac.mm.
Referenced by QStandardInterfaceFactory::element(), QMultipleHIObjectFactory::element(), QItemViewInterfaceFactory::element(), QAccessibleHierarchyManager::lookup(), navigateAncestors(), and QAccessibleHierarchyManager::registerInterface().
 :elementRef(0)
 {}
QAElement() [2/4]
QAElement::QAElement (AXUIElementRef elementRef) explicit
Definition at line 488 of file qaccessible_mac.mm.
 :elementRef(elementRef)
 {
     if (elementRef != 0) {
         CFRetain(elementRef);
         CFRetain(object());
     }
 }
QAElement() [3/4]
QAElement::QAElement (const QAElement & element)
Definition at line 497 of file qaccessible_mac.mm.
 :elementRef(element.elementRef)
 {
     if (elementRef != 0) {
         CFRetain(elementRef);
         CFRetain(object());
     }
 }
QAElement() [4/4]
QAElement::QAElement (HIObjectRef object, int child)
Definition at line 506 of file qaccessible_mac.mm.
 {
 #ifndef QT_MAC_USE_COCOA
     if (object == 0) {
         elementRef = 0; // Create invalid QAElement.
     } else {
         elementRef = AXUIElementCreateWithHIObjectAndIdentifier(object, child);
         CFRetain(object);
     }
 #else
     Q_UNUSED(object);
     Q_UNUSED(child);
 #endif
 }
~QAElement()
QAElement::~QAElement ()
Definition at line 521 of file qaccessible_mac.mm.
 {
     if (elementRef != 0) {
         CFRelease(object());
         CFRelease(elementRef);
     }
 }
Functions
element()
AXUIElementRef QAElement::element () const inline
Definition at line 402 of file qaccessible_mac_p.h.
Referenced by accessibilityEventHandler(), getAccessibleObjectParameter(), getChildAtPoint(), handleChildrenAttribute(), handleParentAttribute(), handleScrollBarAttribute(), QAccessibleHierarchyManager::lookup(), lookup(), navigateAncestors(), setAttributeValue(), and QAccessible::updateAccessibility().
     {
         return elementRef;
     }
id()
int QAElement::id () const inline
Definition at line 391 of file qaccessible_mac_p.h.
Referenced by QAccessibleHierarchyManager::lookup(), and qHash().
     {
         UInt64 theId;
 #ifndef QT_MAC_USE_COCOA
         AXUIElementGetIdentifier(elementRef, &theId);
 #else
         theId = 0;
 #endif
         return theId;
     }
isValid()
bool QAElement::isValid () const inline
Definition at line 407 of file qaccessible_mac_p.h.
Referenced by getChildAtPoint(), handleContentsAttribute(), handleParentAttribute(), handleScrollBarAttribute(), lookup(), navigateAncestors(), setAttributeValue(), and QAccessible::updateAccessibility().
     {
         return (elementRef != 0);
     }
object()
HIObjectRef QAElement::object () const inline
Definition at line 382 of file qaccessible_mac_p.h.
Referenced by isEmbeddedTabBar(), isItInteresting(), isStandaloneTabBar(), isTabWidget(), macRole(), qHash(), QAccessible::setRootObject(), and QAccessible::updateAccessibility().
     {
 #ifndef Q_WS_MAC64
         return AXUIElementGetHIObject(elementRef);
 #else
         return 0;
 #endif
     }
operator=()
void QAElement::operator= (const QAElement & other)
Definition at line 529 of file qaccessible_mac.mm.
 {
     if (*this == other)
         return;
     if (elementRef != 0) {
         CFRelease(object());
         CFRelease(elementRef);
     }
     elementRef = other.elementRef;
     if (elementRef != 0) {
         CFRetain(elementRef);
         CFRetain(object());
     }
 }
operator==()
bool QAElement::operator== (const QAElement & other) const
Definition at line 547 of file qaccessible_mac.mm.
 {
     if (elementRef == 0 || other.elementRef == 0)
         return (elementRef == other.elementRef);
     return CFEqual(elementRef, other.elementRef);
 }
Properties
elementRef
AXUIElementRef QAElement::elementRef private
Definition at line 415 of file qaccessible_mac_p.h.
Referenced by getChildAtPoint(), handleParentAttribute(), handleScrollBarAttribute(), navigateAncestors(), operator=(), operator==(), QAElement(), and ~QAElement().
The documentation for this class was generated from the following files:
/src/gui/accessible/qaccessible_mac_p.h
/src/gui/accessible/qaccessible_mac.mm