Qt 4.8: QDeclarativeVisualDataModelData Class Reference
QDeclarativeVisualDataModelData Class Reference
Signals
void indexChanged ()
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void ensureProperties ()
bool hasValue (int id) const
int index () const
int modelDataPropertyId () const
int propForRole (int) const
QDeclarativeVisualDataModelData (int index, QDeclarativeVisualDataModel *model)
void setIndex (int index)
void setValue (int, const QVariant &)
~QDeclarativeVisualDataModelData ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Variables
int index
Properties
int m_index
QDeclarativeVisualDataModelDataMetaObject * m_meta
QDeclarativeGuard< QDeclarativeVisualDataModel > m_model
Friends
class QDeclarativeVisualDataModelDataMetaObject
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 432 of file qdeclarativevisualitemmodel.cpp.
Constructors and Destructors
QDeclarativeVisualDataModelData()
QDeclarativeVisualDataModelData::QDeclarativeVisualDataModelData (int index, QDeclarativeVisualDataModel * model)
Definition at line 554 of file qdeclarativevisualitemmodel.cpp.
 : m_index(index), m_model(model),
 m_meta(new QDeclarativeVisualDataModelDataMetaObject(this, QDeclarativeVisualDataModelPrivate::get(model)->m_delegateDataType))
 {
     ensureProperties();
 }
~QDeclarativeVisualDataModelData()
QDeclarativeVisualDataModelData::~QDeclarativeVisualDataModelData ()
Definition at line 562 of file qdeclarativevisualitemmodel.cpp.
 {
 }
Functions
ensureProperties()
void QDeclarativeVisualDataModelData::ensureProperties ()
Definition at line 566 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelData().
 {
     QDeclarativeVisualDataModelPrivate *modelPriv = QDeclarativeVisualDataModelPrivate::get(m_model);
     if (modelPriv->m_metaDataCacheable) {
         if (!modelPriv->m_metaDataCreated)
             modelPriv->createMetaData();
         if (modelPriv->m_metaDataCreated)
             m_meta->setCached(true);
     }
 }
hasValue()
bool QDeclarativeVisualDataModelData::hasValue (int id) const inline
Definition at line 450 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModel::_q_itemsChanged().
{
         return m_meta->hasValue(id);
     }
index()
int QDeclarativeVisualDataModelData::index () const
Referenced by ensureProperties(), and setIndex().
indexChanged
void QDeclarativeVisualDataModelData::indexChanged () signal
Referenced by setIndex().
modelDataPropertyId()
int QDeclarativeVisualDataModelData::modelDataPropertyId () const inline
Definition at line 444 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModel::_q_itemsChanged().
{
         QDeclarativeVisualDataModelPrivate *model = QDeclarativeVisualDataModelPrivate::get(m_model);
         return model->m_modelDataPropId;
     }
propForRole()
int QDeclarativeVisualDataModelData::propForRole (int id) const
Definition at line 466 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModel::_q_itemsChanged().
 {
     QDeclarativeVisualDataModelPrivate *model = QDeclarativeVisualDataModelPrivate::get(m_model);
     QHash<int,int>::const_iterator it = model->m_roleToPropId.find(id);
     if (it != model->m_roleToPropId.end())
         return *it;
     return -1;
 }
setIndex()
void QDeclarativeVisualDataModelData::setIndex (int index)
Definition at line 583 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModel::_q_itemsInserted(), QDeclarativeVisualDataModel::_q_itemsMoved(), and QDeclarativeVisualDataModel::_q_itemsRemoved().
 {
     m_index = index;
     emit indexChanged();
 }
setValue()
void QDeclarativeVisualDataModelData::setValue (int id, const QVariant & val)
Definition at line 476 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModel::_q_itemsChanged().
 {
     m_meta->setValue(id, val);
 }
Friends and Related Functions
QDeclarativeVisualDataModelDataMetaObject
friend class QDeclarativeVisualDataModelDataMetaObject friend
Definition at line 460 of file qdeclarativevisualitemmodel.cpp.
Properties
index
int QDeclarativeVisualDataModelData::index
Definition at line 439 of file qdeclarativevisualitemmodel.cpp.
m_index
int QDeclarativeVisualDataModelData::m_index private
Definition at line 461 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), ensureProperties(), QDeclarativeVisualDataModelDataMetaObject::initialValue(), and setIndex().
m_meta
QDeclarativeVisualDataModelDataMetaObject* QDeclarativeVisualDataModelData::m_meta private
Definition at line 463 of file qdeclarativevisualitemmodel.cpp.
Referenced by ensureProperties().
m_model
QDeclarativeGuard<QDeclarativeVisualDataModel> QDeclarativeVisualDataModelData::m_model private
Definition at line 462 of file qdeclarativevisualitemmodel.cpp.
Referenced by QDeclarativeVisualDataModelDataMetaObject::createProperty(), ensureProperties(), and QDeclarativeVisualDataModelDataMetaObject::initialValue().
The documentation for this class was generated from the following file:
/src/declarative/graphicsitems/qdeclarativevisualitemmodel.cpp