Qt 4.8: QIconLoader Class Reference
QIconLoader Class Reference
#include <qiconloader_p.h>
Public Functions
QIconDirInfo dirInfo (int dirindex)
void ensureInitialized ()
void invalidateKey ()
QThemeIconEntries loadIcon (const QString &iconName) const
QIconLoader ()
void setThemeName (const QString &themeName)
void setThemeSearchPath (const QStringList &searchPaths)
QIconTheme theme ()
uint themeKey () const
QString themeName () const
QStringList themeSearchPaths () const
void updateSystemTheme ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QIconLoader * instance ()
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Private Functions
QThemeIconEntries findIconHelper (const QString &themeName, const QString &iconName, QStringList &visited) const
Properties
QStringList m_iconDirs
bool m_initialized
bool m_supportsSvg
QString m_systemTheme
uint m_themeKey
QString m_userTheme
QHash< QString, QIconTheme > themeList
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 156 of file qiconloader_p.h.
Constructors and Destructors
QIconLoader()
QIconLoader::QIconLoader ()
Definition at line 89 of file qiconloader.cpp.
                          :
         m_themeKey(1), m_supportsSvg(false), m_initialized(false)
 {
 }
Functions
dirInfo()
QIconDirInfo QIconLoader::dirInfo (int dirindex)
ensureInitialized()
void QIconLoader::ensureInitialized ()
Definition at line 96 of file qiconloader.cpp.
 {
     if (!m_initialized) {
         m_initialized = true;
         Q_ASSERT(qApp);
         m_systemTheme = qt_guiPlatformPlugin()->systemIconThemeName();
         if (m_systemTheme.isEmpty())
             m_systemTheme = fallbackTheme();
 #ifndef QT_NO_LIBRARY
         QFactoryLoader iconFactoryLoader(QIconEngineFactoryInterfaceV2_iid,
                                          QLatin1String("/iconengines"),
                                          Qt::CaseInsensitive);
         if (iconFactoryLoader.keys().contains(QLatin1String("svg")))
             m_supportsSvg = true;
 #endif //QT_NO_LIBRARY
     }
 }
findIconHelper()
QThemeIconEntries QIconLoader::findIconHelper (const QString & themeName, const QString & iconName, QStringList & visited) const private
Definition at line 233 of file qiconloader.cpp.
 {
     QThemeIconEntries entries;
     Q_ASSERT(!themeName.isEmpty());
     QPixmap pixmap;
     // Used to protect against potential recursions
     visited << themeName;
     QIconTheme theme = themeList.value(themeName);
     if (!theme.isValid()) {
         theme = QIconTheme(themeName);
         if (!theme.isValid())
             theme = QIconTheme(fallbackTheme());
         themeList.insert(themeName, theme);
     }
     QString contentDir = theme.contentDir() + QLatin1Char('/');
     QList<QIconDirInfo> subDirs = theme.keyList();
     const QString svgext(QLatin1String(".svg"));
     const QString pngext(QLatin1String(".png"));
     // Add all relevant files
     for (int i = 0; i < subDirs.size() ; ++i) {
         const QIconDirInfo &dirInfo = subDirs.at(i);
         QString subdir = dirInfo.path;
         QDir currentDir(contentDir + subdir);
         if (currentDir.exists(iconName + pngext)) {
             PixmapEntry *iconEntry = new PixmapEntry;
             iconEntry->dir = dirInfo;
             iconEntry->filename = currentDir.filePath(iconName + pngext);
             // Notice we ensure that pixmap entries always come before
             // scalable to preserve search order afterwards
             entries.prepend(iconEntry);
         } else if (m_supportsSvg &&
             currentDir.exists(iconName + svgext)) {
             ScalableEntry *iconEntry = new ScalableEntry;
             iconEntry->dir = dirInfo;
             iconEntry->filename = currentDir.filePath(iconName + svgext);
             entries.append(iconEntry);
         }
     }
     if (entries.isEmpty()) {
         const QStringList parents = theme.parents();
         // Search recursively through inherited themes
         for (int i = 0 ; i < parents.size() ; ++i) {
             const QString parentTheme = parents.at(i).trimmed();
             if (!visited.contains(parentTheme)) // guard against recursion
                 entries = findIconHelper(parentTheme, iconName, visited);
             if (!entries.isEmpty()) // success
                 break;
         }
     }
     return entries;
 }
instance()
QIconLoader * QIconLoader::instance () static
Definition at line 116 of file qiconloader.cpp.
Referenced by QIcon::setThemeName(), QIcon::setThemeSearchPaths(), QIcon::themeName(), QIcon::themeSearchPaths(), and QGtkStyleUpdateScheduler::updateTheme().
 {
    return iconLoaderInstance();
 }
invalidateKey()
void QIconLoader::invalidateKey () inline
Definition at line 171 of file qiconloader_p.h.
Referenced by setThemeName(), setThemeSearchPath(), and updateSystemTheme().
 { m_themeKey++; }
loadIcon()
QThemeIconEntries QIconLoader::loadIcon (const QString & iconName) const
Definition at line 298 of file qiconloader.cpp.
 {
     if (!themeName().isEmpty()) {
         QStringList visited;
         return findIconHelper(themeName(), name, visited);
     }
     return QThemeIconEntries();
 }
setThemeName()
void QIconLoader::setThemeName (const QString & themeName)
Definition at line 137 of file qiconloader.cpp.
Referenced by QIcon::setThemeName().
 {
     m_userTheme = themeName;
     invalidateKey();
 }
setThemeSearchPath()
void QIconLoader::setThemeSearchPath (const QStringList & searchPaths)
Definition at line 143 of file qiconloader.cpp.
Referenced by QIcon::setThemeSearchPaths().
 {
     m_iconDirs = searchPaths;
     themeList.clear();
     invalidateKey();
 }
theme()
QIconTheme QIconLoader::theme () inline
Definition at line 165 of file qiconloader_p.h.
Referenced by updateSystemTheme().
 { return themeList.value(themeName()); }
themeKey()
uint QIconLoader::themeKey () const inline
Definition at line 161 of file qiconloader_p.h.
 { return m_themeKey; }
themeName()
QString QIconLoader::themeName () const inline
Definition at line 163 of file qiconloader_p.h.
Referenced by setThemeName(), and QIcon::themeName().
 { return m_userTheme.isEmpty() ? m_systemTheme : m_userTheme; }
themeSearchPaths()
QStringList QIconLoader::themeSearchPaths () const
Definition at line 150 of file qiconloader.cpp.
Referenced by QIcon::themeSearchPaths().
 {
     if (m_iconDirs.isEmpty()) {
         m_iconDirs = qt_guiPlatformPlugin()->iconThemeSearchPaths();
         // Always add resource directory as search path
         m_iconDirs.append(QLatin1String(":/icons"));
     }
     return m_iconDirs;
 }
updateSystemTheme()
void QIconLoader::updateSystemTheme ()
Definition at line 123 of file qiconloader.cpp.
Referenced by QGtkStyleUpdateScheduler::updateTheme().
 {
     // Only change if this is not explicitly set by the user
     if (m_userTheme.isEmpty()) {
         QString theme = qt_guiPlatformPlugin()->systemIconThemeName();
         if (theme.isEmpty())
             theme = fallbackTheme();
         if (theme != m_systemTheme) {
             m_systemTheme = theme;
             invalidateKey();
         }
     }
 }
Properties
m_iconDirs
QStringList QIconLoader::m_iconDirs mutable private
Definition at line 184 of file qiconloader_p.h.
Referenced by setThemeSearchPath(), and themeSearchPaths().
m_initialized
bool QIconLoader::m_initialized private
Definition at line 180 of file qiconloader_p.h.
Referenced by ensureInitialized().
m_supportsSvg
bool QIconLoader::m_supportsSvg private
Definition at line 179 of file qiconloader_p.h.
Referenced by ensureInitialized().
m_systemTheme
QString QIconLoader::m_systemTheme mutable private
Definition at line 183 of file qiconloader_p.h.
Referenced by ensureInitialized(), and updateSystemTheme().
m_themeKey
uint QIconLoader::m_themeKey private
Definition at line 178 of file qiconloader_p.h.
m_userTheme
QString QIconLoader::m_userTheme mutable private
Definition at line 182 of file qiconloader_p.h.
Referenced by setThemeName(), and updateSystemTheme().
themeList
QHash<QString, QIconTheme> QIconLoader::themeList mutable private
Definition at line 185 of file qiconloader_p.h.
Referenced by setThemeSearchPath().
The documentation for this class was generated from the following files:
/src/gui/image/qiconloader_p.h
/src/gui/image/qiconloader.cpp