Qt 4.8: QSizePolicy Class Reference
QSizePolicy Class Reference
#include <qsizepolicy.h>
Public Types
enum ControlType {
DefaultType = 0x00000001, ButtonBox = 0x00000002, CheckBox = 0x00000004, ComboBox = 0x00000008,
Frame = 0x00000010, GroupBox = 0x00000020, Label = 0x00000040, Line = 0x00000080,
LineEdit = 0x00000100, PushButton = 0x00000200, RadioButton = 0x00000400, Slider = 0x00000800,
SpinBox = 0x00001000, TabWidget = 0x00002000, ToolButton = 0x00004000
}
enum Policy {
Fixed = 0, Minimum = GrowFlag, Maximum = ShrinkFlag, Preferred = GrowFlag | ShrinkFlag,
MinimumExpanding = GrowFlag | ExpandFlag, Expanding = GrowFlag | ShrinkFlag | ExpandFlag, Ignored = ShrinkFlag | GrowFlag | IgnoreFlag
}
enum PolicyFlag { GrowFlag = 1, ExpandFlag = 2, ShrinkFlag = 4, IgnoreFlag = 8 }
Public Functions
ControlType controlType () const
Qt::Orientations expandingDirections () const
bool hasHeightForWidth () const
bool hasWidthForHeight () const
Policy horizontalPolicy () const
int horizontalStretch () const
operator QVariant () const
Returns a QVariant storing this QSizePolicy.
bool operator!= (const QSizePolicy &s) const
bool operator== (const QSizePolicy &s) const
QSizePolicy ()
QSizePolicy (Policy horizontal, Policy vertical)
QSizePolicy (Policy horizontal, Policy vertical, ControlType type)
void setControlType (ControlType type)
void setHeightForWidth (bool b)
void setHorizontalPolicy (Policy d)
void setHorizontalStretch (uchar stretchFactor)
void setVerticalPolicy (Policy d)
void setVerticalStretch (uchar stretchFactor)
void setWidthForHeight (bool b)
void transpose ()
Policy verticalPolicy () const
int verticalStretch () const
Private Types
enum SizePolicyMasks {
HSize = 4, HMask = 0x0f, VMask = HMask << HSize, CTShift = 9,
CTSize = 5, CTMask = ((0x1 << CTSize) - 1) << CTShift, WFHShift = CTShift + CTSize, UnusedShift = WFHShift + 1,
UnusedSize = 1
}
Private Functions
QSizePolicy (int i)
Properties
quint32 data
Friends
Q_GUI_EXPORT QDataStream & operator<< (QDataStream &, const QSizePolicy &)
Writes the size policy to the data stream stream.
Q_GUI_EXPORT QDataStream & operator>> (QDataStream &, QSizePolicy &)
Reads the size policy from the data stream stream.
Detailed Description
Definition at line 55 of file qsizepolicy.h.
Enumerations
ControlType
enum QSizePolicy::ControlType
Enumerator
DefaultType
ButtonBox
CheckBox
ComboBox
Frame
GroupBox
Label
Line
LineEdit
PushButton
RadioButton
Slider
SpinBox
TabWidget
ToolButton
Definition at line 91 of file qsizepolicy.h.
                      {
         DefaultType      = 0x00000001,
         ButtonBox        = 0x00000002,
         CheckBox         = 0x00000004,
         ComboBox         = 0x00000008,
         Frame            = 0x00000010,
         GroupBox         = 0x00000020,
         Label            = 0x00000040,
         Line             = 0x00000080,
         LineEdit         = 0x00000100,
         PushButton       = 0x00000200,
         RadioButton      = 0x00000400,
         Slider           = 0x00000800,
         SpinBox          = 0x00001000,
         TabWidget        = 0x00002000,
         ToolButton       = 0x00004000
     };
Policy
enum QSizePolicy::Policy
Enumerator
Fixed
Minimum
Maximum
Preferred
MinimumExpanding
Expanding
Ignored
Definition at line 81 of file qsizepolicy.h.
                 {
         Fixed = 0,
         Minimum = GrowFlag,
         Maximum = ShrinkFlag,
         Preferred = GrowFlag | ShrinkFlag,
         MinimumExpanding = GrowFlag | ExpandFlag,
         Expanding = GrowFlag | ShrinkFlag | ExpandFlag,
         Ignored = ShrinkFlag | GrowFlag | IgnoreFlag
     };
PolicyFlag
enum QSizePolicy::PolicyFlag
Enumerator
GrowFlag
ExpandFlag
ShrinkFlag
IgnoreFlag
Definition at line 74 of file qsizepolicy.h.
                     {
         GrowFlag = 1,
         ExpandFlag = 2,
         ShrinkFlag = 4,
         IgnoreFlag = 8
     };
SizePolicyMasks
enum QSizePolicy::SizePolicyMasks private
Enumerator
HSize
HMask
VMask
CTShift
CTSize
CTMask
WFHShift
UnusedShift
UnusedSize
Definition at line 61 of file qsizepolicy.h.
{
         HSize = 4,
         HMask = 0x0f,
         VMask = HMask << HSize,
         CTShift = 9,
         CTSize = 5,
         CTMask = ((0x1 << CTSize) - 1) << CTShift,
         WFHShift = CTShift + CTSize,
         UnusedShift = WFHShift + 1,
         UnusedSize = 1
     };
Constructors and Destructors
QSizePolicy() [1/4]
QSizePolicy::QSizePolicy () inline
Definition at line 110 of file qsizepolicy.h.
 : data(0) { }
QSizePolicy() [2/4]
QSizePolicy::QSizePolicy (Policy horizontal, Policy vertical) inline
Definition at line 113 of file qsizepolicy.h.
         : data(horizontal | (vertical << HSize)) { }
QSizePolicy() [3/4]
QSizePolicy::QSizePolicy (Policy horizontal, Policy vertical, ControlType type) inline
Definition at line 115 of file qsizepolicy.h.
         : data(horizontal | (vertical << HSize)) { setControlType(type); }
QSizePolicy() [4/4]
QSizePolicy::QSizePolicy (int i) inline private
Definition at line 202 of file qsizepolicy.h.
 : data(i) { }
Functions
controlType()
QSizePolicy::ControlType QSizePolicy::controlType () const
Definition at line 1670 of file qlayout.cpp.
Referenced by QLayoutItem::controlTypes(), QGridLayoutItem::controlTypes(), and QMacStyle::pixelMetric().
 {
     return QSizePolicy::ControlType(0x1 << ((data & CTMask) >> CTShift));
 }
expandingDirections()
Qt::Orientations QSizePolicy::expandingDirections () const inline
Definition at line 126 of file qsizepolicy.h.
{
         Qt::Orientations result;
         if (verticalPolicy() & ExpandFlag)
             result |= Qt::Vertical;
         if (horizontalPolicy() & ExpandFlag)
             result |= Qt::Horizontal;
         return result;
     }
hasHeightForWidth()
bool QSizePolicy::hasHeightForWidth () const inline
Definition at line 136 of file qsizepolicy.h.
Referenced by QTabWidgetPrivate::hasHeightForWidth(), and QScrollAreaPrivate::updateScrollBars().
 { return data & (1 << 2*HSize); }
hasWidthForHeight()
bool QSizePolicy::hasWidthForHeight () const inline
Definition at line 138 of file qsizepolicy.h.
 { return data & (1 << (WFHShift)); }
horizontalPolicy()
Policy QSizePolicy::horizontalPolicy () const inline
Definition at line 118 of file qsizepolicy.h.
Referenced by pick(), qSmartMaxSize(), qSmartMinSize(), QToolBarAreaLayoutItem::realSizeHint(), QWidgetItem::setGeometry(), QStackedLayout::sizeHint(), QToolBarLayout::updateGeomArray(), and QAxServerBase::updateGeometry().
 { return static_cast<Policy>(data & HMask); }
horizontalStretch()
int QSizePolicy::horizontalStretch () const inline
Definition at line 144 of file qsizepolicy.h.
Referenced by QSplitterPrivate::doResize(), QSplitterPrivate::findWidget(), QSplitterLayoutStruct::getWidgetSize(), QBoxLayoutItem::hStretch(), and QToolBarLayout::updateGeomArray().
 { return data >> 24; }
operator QVariant()
QSizePolicy::operator QVariant () const
Returns a QVariant storing this QSizePolicy.
Definition at line 80 of file qlayoutitem.cpp.
 {
     return QVariant(QVariant::SizePolicy, this);
 }
operator!=()
bool QSizePolicy::operator!= (const QSizePolicy & s) const inline
Definition at line 141 of file qsizepolicy.h.
 { return data != s.data; }
operator==()
bool QSizePolicy::operator== (const QSizePolicy & s) const inline
Definition at line 140 of file qsizepolicy.h.
 { return data == s.data; }
setControlType()
void QSizePolicy::setControlType (ControlType type)
Definition at line 1644 of file qlayout.cpp.
 {
     /*
         The control type is a flag type, with values 0x1, 0x2, 0x4, 0x8, 0x10,
         etc. In memory, we pack it onto the available bits (CTSize) in
         setControlType(), and unpack it here.
         Example:
             0x00000001 maps to 0x00000000
             0x00000002 maps to 0x00000200
             0x00000004 maps to 0x00000400
             0x00000008 maps to 0x00000600
             etc.
     */
     int i = 0;
     while (true) {
         if (type & (0x1 << i)) {
             data = (data & ~CTMask) | (i << CTShift);
             return;
         }
         ++i;
     }
 }
setHeightForWidth()
void QSizePolicy::setHeightForWidth (bool b) inline
Definition at line 135 of file qsizepolicy.h.
Referenced by QCommandLinkButtonPrivate::init(), QLabelPrivate::updateLabel(), and QMessageBoxPrivate::updateSize().
 { data = b ? (data | (1 << 2*HSize)) : (data & ~(1 << 2*HSize));  }
setHorizontalPolicy()
void QSizePolicy::setHorizontalPolicy (Policy d) inline
Definition at line 122 of file qsizepolicy.h.
Referenced by QAbstractScrollAreaScrollBarContainer::addWidget().
 { data = (data & ~HMask) | d; }
setHorizontalStretch()
void QSizePolicy::setHorizontalStretch (uchar stretchFactor) inline
Definition at line 146 of file qsizepolicy.h.
Referenced by QSplitterPrivate::findWidget(), and QSplitter::setStretchFactor().
 { data = (data&0x00ffffff) | (uint(stretchFactor)<<24); }
setVerticalPolicy()
void QSizePolicy::setVerticalPolicy (Policy d) inline
Definition at line 123 of file qsizepolicy.h.
Referenced by QAbstractScrollAreaScrollBarContainer::addWidget().
 { data = (data & ~(HMask << HSize)) | (d << HSize); }
setVerticalStretch()
void QSizePolicy::setVerticalStretch (uchar stretchFactor) inline
Definition at line 147 of file qsizepolicy.h.
Referenced by QSplitterPrivate::findWidget(), and QSplitter::setStretchFactor().
 { data = (data&0xff00ffff) | (uint(stretchFactor)<<16); }
setWidthForHeight()
void QSizePolicy::setWidthForHeight (bool b) inline
Definition at line 137 of file qsizepolicy.h.
 { data = b ? (data | (1 << (WFHShift))) : (data & ~(1 << (WFHShift)));  }
transpose()
void QSizePolicy::transpose () inline
Definition at line 229 of file qsizepolicy.h.
Referenced by QProgressBarPrivate::init(), QSliderPrivate::init(), QSplitterPrivate::init(), QScrollBarPrivate::init(), QDialogButtonBoxPrivate::initLayout(), QSplitter::setOrientation(), QProgressBar::setOrientation(), and QAbstractSlider::setOrientation().
{
     Policy hData = horizontalPolicy();
     Policy vData = verticalPolicy();
     uchar hStretch = uchar(horizontalStretch());
     uchar vStretch = uchar(verticalStretch());
     setHorizontalPolicy(vData);
     setVerticalPolicy(hData);
     setHorizontalStretch(vStretch);
     setVerticalStretch(hStretch);
 }
verticalPolicy()
Policy QSizePolicy::verticalPolicy () const inline
Definition at line 119 of file qsizepolicy.h.
Referenced by pick(), qSmartMaxSize(), qSmartMinSize(), QToolBarAreaLayoutItem::realSizeHint(), QWidgetItem::setGeometry(), QWidget::show(), QStackedLayout::sizeHint(), and QAxServerBase::updateGeometry().
 { return static_cast<Policy>((data & VMask) >> HSize); }
verticalStretch()
int QSizePolicy::verticalStretch () const inline
Definition at line 145 of file qsizepolicy.h.
Referenced by QSplitterPrivate::doResize(), QSplitterPrivate::findWidget(), QSplitterLayoutStruct::getWidgetSize(), QToolBarLayout::updateGeomArray(), QBoxLayoutItem::vStretch(), and QFormLayoutItem::vStretch().
 { return (data >> 16) & 0xff; }
Friends and Related Functions
operator<<
QDataStream & operator<< (QDataStream & stream, const QSizePolicy & policy) friend
Writes the size policy to the data stream stream.
Since
4.2
See also
Format of the QDataStream operators
Definition at line 1687 of file qlayout.cpp.
 {
     return stream << policy.data;
 }
operator>>
QDataStream & operator>> (QDataStream & stream, QSizePolicy & policy) friend
Reads the size policy from the data stream stream.
Since
4.2
See also
Format of the QDataStream operators
Definition at line 1703 of file qlayout.cpp.
 {
     return stream >> policy.data;
 }
Properties
data
quint32 QSizePolicy::data private
Definition at line 204 of file qsizepolicy.h.
Referenced by operator!=(), and operator==().
The documentation for this class was generated from the following files:
/src/gui/kernel/qsizepolicy.h
/src/gui/kernel/qlayout.cpp
/src/gui/kernel/qlayoutitem.cpp