Qt 4.8: QSslCertificate Class Reference
QSslCertificate Class Reference
The QSslCertificate class provides a convenient API for an X509 certificate.
#include <qsslcertificate.h>
Public Types
enum SubjectInfo {
Organization, CommonName, LocalityName, OrganizationalUnitName,
CountryName, StateOrProvinceName
}
Describes keys that you can pass to QSslCertificate::issuerInfo() or QSslCertificate::subjectInfo() to get information about the certificate issuer or subject.
Public Functions
QMultiMap< QSsl::AlternateNameEntryType, QString > alternateSubjectNames () const
Returns the list of alternative subject names for this certificate.
void clear ()
Clears the contents of this certificate, making it a null certificate.
QByteArray digest (QCryptographicHash::Algorithm algorithm=QCryptographicHash::Md5) const
Returns a cryptographic digest of this certificate.
QDateTime effectiveDate () const
Returns the date-time that the certificate becomes valid, or an empty QDateTime if this is a null certificate.
QDateTime expiryDate () const
Returns the date-time that the certificate expires, or an empty QDateTime if this is a null certificate.
Qt::HANDLE handle () const
Returns a pointer to the native certificate handle, if there is one, or a null pointer otherwise.
bool isNull () const
Returns true if this is a null certificate (i.e., a certificate with no contents); otherwise returns false.
QString issuerInfo (SubjectInfo info) const
Returns the issuer information for the subject from the certificate, or an empty string if there is no information for subject in the certificate.
QString issuerInfo (const QByteArray &tag) const
Returns the issuer information for tag from the certificate, or an empty string if there is no information for tag in the certificate.
bool isValid () const
Returns true if this certificate is valid; otherwise returns false.
bool operator!= (const QSslCertificate &other) const
Returns true if this certificate is not the same as other; otherwise returns false.
QSslCertificate & operator= (const QSslCertificate &other)
Copies the contents of other into this certificate, making the two certificates identical.
bool operator== (const QSslCertificate &other) const
Returns true if this certificate is the same as other; otherwise returns false.
QSslKey publicKey () const
Returns the certificate subject's public key.
QSslCertificate (QIODevice *device, QSsl::EncodingFormat format=QSsl::Pem)
Constructs a QSslCertificate by reading format encoded data from device and using the first certificate found.
QSslCertificate (const QByteArray &encoded=QByteArray(), QSsl::EncodingFormat format=QSsl::Pem)
Constructs a QSslCertificate by parsing the format encoded data and using the first available certificate found.
QSslCertificate (const QSslCertificate &other)
Constructs an identical copy of other.
QByteArray serialNumber () const
Returns the certificate's serial number string in decimal format.
QString subjectInfo (SubjectInfo info) const
Returns the information for the subject, or an empty string if there is no information for subject in the certificate.
QString subjectInfo (const QByteArray &tag) const
Returns the subject information for tag, or an empty string if there is no information for tag in the certificate.
QByteArray toDer () const
Returns this certificate converted to a DER (binary) encoded representation.
QByteArray toPem () const
Returns this certificate converted to a PEM (Base64) encoded representation.
QByteArray version () const
Returns the certificate's version string.
~QSslCertificate ()
Destroys the QSslCertificate.
Static Public Functions
static QList< QSslCertificate > fromData (const QByteArray &data, QSsl::EncodingFormat format=QSsl::Pem)
Searches for and parses all certificates in data that are encoded in the specified format and returns them in a list of certificates.
static QList< QSslCertificate > fromDevice (QIODevice *device, QSsl::EncodingFormat format=QSsl::Pem)
Searches for and parses all certificates in device that are encoded in the specified format and returns them in a list of certificates.
static QList< QSslCertificate > fromPath (const QString &path, QSsl::EncodingFormat format=QSsl::Pem, QRegExp::PatternSyntax syntax=QRegExp::FixedString)
Searches all files in the path for certificates encoded in the specified format and returns them in a list.
Properties
QExplicitlySharedDataPointer< QSslCertificatePrivate > d
Friends
class QSslCertificatePrivate
class QSslSocketBackendPrivate
Detailed Description
The QSslCertificate class provides a convenient API for an X509 certificate.
Since
4.3
Note
This class or function is reentrant.
Attention
Module: QtNetwork
QSslCertificate stores an X509 certificate, and is commonly used to verify the identity and store information about the local host, a remotely connected peer, or a trusted third party Certificate Authority.
There are many ways to construct a QSslCertificate. The most common way is to call QSslSocket::peerCertificate(), which returns a QSslCertificate object, or QSslSocket::peerCertificateChain(), which returns a list of them. You can also load certificates from a DER (binary) or PEM (Base64) encoded bundle, typically stored as one or more local files, or in a Qt Resource.
You can call isNull() to check if your certificate is null. By default, QSslCertificate constructs a null certificate. To check if the certificate is valid, call isValid(). A null certificate is invalid, but an invalid certificate is not necessarily null. If you want to reset all contents in a certificate, call clear().
After loading a certificate, you can find information about the certificate, its subject, and its issuer, by calling one of the many accessor functions, including version(), serialNumber(), issuerInfo() and subjectInfo(). You can call effectiveDate() and expiryDate() to check when the certificate starts being effective and when it expires. The publicKey() function returns the certificate subject's public key as a QSslKey. You can call issuerInfo() or subjectInfo() to get detailed information about the certificate issuer and its subject.
Internally, QSslCertificate is stored as an X509 structure. You can access this handle by calling handle(), but the results are likely to not be portable.
See also
QSslSocket, QSslKey, QSslCipher, QSslError
Definition at line 70 of file qsslcertificate.h.
Enumerations
SubjectInfo
enum QSslCertificate::SubjectInfo
Describes keys that you can pass to QSslCertificate::issuerInfo() or QSslCertificate::subjectInfo() to get information about the certificate issuer or subject.
Organization "O" The name of the organization.
CommonName "CN" The common name; most often this is used to store the host name.
LocalityName "L" The locality.
OrganizationalUnitName "OU" The organizational unit name.
CountryName "C" The country.
StateOrProvinceName "ST" The state or province.
Enumerator
Organization
CommonName
LocalityName
OrganizationalUnitName
CountryName
StateOrProvinceName
Definition at line 73 of file qsslcertificate.h.
                      {
         Organization,
         CommonName,
         LocalityName,
         OrganizationalUnitName,
         CountryName,
         StateOrProvinceName
     };
Constructors and Destructors
QSslCertificate() [1/3]
QSslCertificate::QSslCertificate (QIODevice * device, QSsl::EncodingFormat format = QSsl::Pem)
Constructs a QSslCertificate by reading format encoded data from device and using the first certificate found.
You can later call isNull() to see if device contained a certificate, and if this certificate was loaded successfully.
Definition at line 146 of file qsslcertificate.cpp.
     : d(new QSslCertificatePrivate)
 {
     QSslSocketPrivate::ensureInitialized();
     if (device)
         d->init(device->readAll(), format);
 }
QSslCertificate() [2/3]
QSslCertificate::QSslCertificate (const QByteArray & data = QByteArray(), QSsl::EncodingFormat format = QSsl::Pem)
Constructs a QSslCertificate by parsing the format encoded data and using the first available certificate found.
You can later call isNull() to see if data contained a certificate, and if this certificate was loaded successfully.
Definition at line 160 of file qsslcertificate.cpp.
     : d(new QSslCertificatePrivate)
 {
     QSslSocketPrivate::ensureInitialized();
     d->init(data, format);
 }
QSslCertificate() [3/3]
QSslCertificate::QSslCertificate (const QSslCertificate & other)
Constructs an identical copy of other.
Definition at line 170 of file qsslcertificate.cpp.
                                                              : d(other.d)
 {
 }
~QSslCertificate()
QSslCertificate::~QSslCertificate ()
Destroys the QSslCertificate.
Definition at line 177 of file qsslcertificate.cpp.
 {
 }
Functions
alternateSubjectNames()
QMultiMap< QSsl::AlternateNameEntryType, QString > QSslCertificate::alternateSubjectNames () const
Returns the list of alternative subject names for this certificate.
The alternate subject names typically contain host names, optionally with wildcards, that are valid for this certificate.
These names are tested against the connected peer's host name, if either the subject information for CommonName doesn't define a valid host name, or the subject info name doesn't match the peer's host name.
See also
subjectInfo()
Definition at line 420 of file qsslcertificate.cpp.
Referenced by operator<<(), and QSslSocketBackendPrivate::startHandshake().
 {
     QMultiMap<QSsl::AlternateNameEntryType, QString> result;
     if (!d->x509)
         return result;
     STACK_OF(GENERAL_NAME) *altNames = (STACK_OF(GENERAL_NAME)*)q_X509_get_ext_d2i(d->x509, NID_subject_alt_name, 0, 0);
     if (altNames) {
         for (int i = 0; i < q_sk_GENERAL_NAME_num(altNames); ++i) {
             const GENERAL_NAME *genName = q_sk_GENERAL_NAME_value(altNames, i);
             if (genName->type != GEN_DNS && genName->type != GEN_EMAIL)
                 continue;
             int len = q_ASN1_STRING_length(genName->d.ia5);
             if (len < 0 || len >= 8192) {
                 // broken name
                 continue;
             }
             const char *altNameStr = reinterpret_cast<const char *>(q_ASN1_STRING_data(genName->d.ia5));
             const QString altName = QString::fromLatin1(altNameStr, len);
             if (genName->type == GEN_DNS)
                 result.insert(QSsl::DnsEntry, altName);
             else if (genName->type == GEN_EMAIL)
                 result.insert(QSsl::EmailEntry, altName);
         }
         q_sk_pop_free((STACK*)altNames, reinterpret_cast<void(*)(void*)>(q_sk_free));
     }
     return result;
 }
clear()
void QSslCertificate::clear ()
Clears the contents of this certificate, making it a null certificate.
See also
isNull()
Definition at line 254 of file qsslcertificate.cpp.
Referenced by QSslSocketPrivate::createPlainSocket(), and QSslSocketPrivate::init().
 {
     if (isNull())
         return;
     d = new QSslCertificatePrivate;
 }
digest()
QByteArray QSslCertificate::digest (QCryptographicHash::Algorithm algorithm = QCryptographicHash::Md5) const
Returns a cryptographic digest of this certificate.
By default, an MD5 digest will be generated, but you can also specify a custom algorithm.
Definition at line 307 of file qsslcertificate.cpp.
Referenced by operator<<().
 {
     return QCryptographicHash::hash(toDer(), algorithm);
 }
effectiveDate()
QDateTime QSslCertificate::effectiveDate () const
Returns the date-time that the certificate becomes valid, or an empty QDateTime if this is a null certificate.
See also
expiryDate()
Definition at line 460 of file qsslcertificate.cpp.
Referenced by operator<<().
 {
     return d->notValidBefore;
 }
expiryDate()
QDateTime QSslCertificate::expiryDate () const
Returns the date-time that the certificate expires, or an empty QDateTime if this is a null certificate.
See also
effectiveDate()
Definition at line 471 of file qsslcertificate.cpp.
Referenced by operator<<().
 {
     return d->notValidAfter;
 }
fromData()
QList< QSslCertificate > QSslCertificate::fromData (const QByteArray & data, QSsl::EncodingFormat format = QSsl::Pem) static
Searches for and parses all certificates in data that are encoded in the specified format and returns them in a list of certificates.
See also
fromDevice()
Definition at line 632 of file qsslcertificate.cpp.
Referenced by fromDevice(), fromPath(), and QSslSocketPrivate::systemCaCertificates().
 {
     return (format == QSsl::Pem)
         ? QSslCertificatePrivate::certificatesFromPem(data)
         : QSslCertificatePrivate::certificatesFromDer(data);
 }
fromDevice()
QList< QSslCertificate > QSslCertificate::fromDevice (QIODevice * device, QSsl::EncodingFormat format = QSsl::Pem) static
Searches for and parses all certificates in device that are encoded in the specified format and returns them in a list of certificates.
See also
fromData()
Definition at line 616 of file qsslcertificate.cpp.
 {
     if (!device) {
         qWarning("QSslCertificate::fromDevice: cannot read from a null device");
         return QList<QSslCertificate>();
     }
     return fromData(device->readAll(), format);
 }
fromPath()
QList< QSslCertificate > QSslCertificate::fromPath (const QString & path, QSsl::EncodingFormat format = QSsl::Pem, QRegExp::PatternSyntax syntax = QRegExp::FixedString) static
Searches all files in the path for certificates encoded in the specified format and returns them in a list.
must be a file or a pattern matching one or more files, as specified by syntax.
Example:
foreach (const QSslCertificate &cert, QSslCertificate::fromPath("C:/ssl/certificate.*.pem", QSsl::Pem,
                                                         QRegExp::Wildcard)) {
    qDebug() << cert.issuerInfo(QSslCertificate::Organization);
}
See also
fromData()
Definition at line 558 of file qsslcertificate.cpp.
Referenced by QSslSocket::addCaCertificates(), QSslSocketPrivate::addDefaultCaCertificates(), and QSslSocketPrivate::systemCaCertificates().
 {
     // $, (,), *, +, ., ?, [, ,], ^, {, | and }.
     int pos = -1;
     if (syntax == QRegExp::Wildcard)
         pos = path.indexOf(QRegExp(QLatin1String("[^\\][\\*\\?\\[\\]]")));
     else if (syntax != QRegExp::FixedString)
         pos = path.indexOf(QRegExp(QLatin1String("[^\\][\\$\\(\\)\\*\\+\\.\\?\\[\\]\\^\\{\\}\\|]")));
     QString pathPrefix = path.left(pos); // == path if pos < 0
     if (pos != -1)
         pathPrefix = pathPrefix.left(pathPrefix.lastIndexOf(QLatin1Char('/')));
     // Special case - if the prefix ends up being nothing, use "." instead and
     // chop off the first two characters from the glob'ed paths.
     int startIndex = 0;
     if (pathPrefix.trimmed().isEmpty()) {
         if(path.startsWith(QLatin1Char('/'))) {
             pathPrefix = path.left(path.indexOf(QRegExp(QLatin1String("[\\*\\?\\[]"))));
             pathPrefix = path.left(path.lastIndexOf(QLatin1Char('/')));
         } else {
             startIndex = 2;
             pathPrefix = QLatin1String(".");
         }
     }
     // The path is a file.
     if (pos == -1 && QFileInfo(pathPrefix).isFile()) {
         QFile file(pathPrefix);
         if (file.open(QIODevice::ReadOnly | QIODevice::Text))
             return QSslCertificate::fromData(file.readAll(),format);
         return QList<QSslCertificate>();
     }
     // The path can be a file or directory.
     QList<QSslCertificate> certs;
     QRegExp pattern(path, Qt::CaseSensitive, syntax);
     QDirIterator it(pathPrefix, QDir::Files, QDirIterator::FollowSymlinks | QDirIterator::Subdirectories);
     while (it.hasNext()) {
         QString filePath = startIndex == 0 ? it.next() : it.next().mid(startIndex);
         if (!pattern.exactMatch(filePath))
             continue;
         QFile file(filePath);
         if (file.open(QIODevice::ReadOnly | QIODevice::Text))
             certs += QSslCertificate::fromData(file.readAll(),format);
     }
     return certs;
 }
handle()
Qt::HANDLE QSslCertificate::handle () const
Returns a pointer to the native certificate handle, if there is one, or a null pointer otherwise.
You can use this handle, together with the native API, to access extended information about the certificate.
Warning
Use of this function has a high probability of being non-portable, and its return value may vary from platform to platform or change from minor release to minor release.
Definition at line 487 of file qsslcertificate.cpp.
Referenced by QSslSocketBackendPrivate::initSslContext().
 {
     return Qt::HANDLE(d->x509);
 }
isNull()
bool QSslCertificate::isNull () const
Returns true if this is a null certificate (i.e., a certificate with no contents); otherwise returns false.
By default, QSslCertificate constructs a null certificate.
See also
isValid(), clear()
Definition at line 224 of file qsslcertificate.cpp.
Referenced by clear(), QSslSocketBackendPrivate::initSslContext(), QSslConfiguration::isNull(), QSslSocketBackendPrivate::startHandshake(), and QSslSocketPrivate::systemCaCertificates().
 {
     return d->null;
 }
issuerInfo() [1/2]
QString QSslCertificate::issuerInfo (SubjectInfo subject) const
Returns the issuer information for the subject from the certificate, or an empty string if there is no information for subject in the certificate.
See also
subjectInfo()
Definition at line 338 of file qsslcertificate.cpp.
Referenced by QSslCertificatePrivate::isBlacklisted(), operator<<(), and QSslSocketPrivate::systemCaCertificates().
 {
     QMutexLocker lock(QMutexPool::globalInstanceGet(d.data()));
     // lazy init
     if (d->issuerInfo.isEmpty() && d->x509)
         d->issuerInfo =
                 _q_mapFromX509Name(q_X509_get_issuer_name(d->x509));
     return d->issuerInfo.value(_q_SubjectInfoToString(info));
 }
issuerInfo() [2/2]
QString QSslCertificate::issuerInfo (const QByteArray & tag) const
Returns the issuer information for tag from the certificate, or an empty string if there is no information for tag in the certificate.
See also
subjectInfo()
Definition at line 356 of file qsslcertificate.cpp.
 {
     QMutexLocker lock(QMutexPool::globalInstanceGet(d.data()));
     // lazy init
     if (d->issuerInfo.isEmpty() && d->x509)
         d->issuerInfo =
                 _q_mapFromX509Name(q_X509_get_issuer_name(d->x509));
     return d->issuerInfo.value(QString::fromLatin1(tag));
 }
isValid()
bool QSslCertificate::isValid () const
Returns true if this certificate is valid; otherwise returns false.
Note: Currently, this function checks that the current data-time is within the date-time range during which the certificate is considered valid, and checks that the certificate is not in a blacklist of fraudulent certificates.
See also
isNull()
Definition at line 240 of file qsslcertificate.cpp.
Referenced by QSslSocketBackendPrivate::initSslContext().
 {
     const QDateTime currentTime = QDateTime::currentDateTime();
     return currentTime >= d->notValidBefore &&
             currentTime <= d->notValidAfter &&
             ! QSslCertificatePrivate::isBlacklisted(*this);
 }
operator!=()
bool QSslCertificate::operator!= (const QSslCertificate & other) const inline
Returns true if this certificate is not the same as other; otherwise returns false.
Definition at line 89 of file qsslcertificate.h.
 { return !operator==(other); }
operator=()
QSslCertificate & QSslCertificate::operator= (const QSslCertificate & other)
Copies the contents of other into this certificate, making the two certificates identical.
Definition at line 185 of file qsslcertificate.cpp.
 {
     d = other.d;
     return *this;
 }
operator==()
bool QSslCertificate::operator== (const QSslCertificate & other) const
Returns true if this certificate is the same as other; otherwise returns false.
Definition at line 195 of file qsslcertificate.cpp.
 {
     if (d == other.d)
         return true;
     if (d->null && other.d->null)
         return true;
     if (d->x509 && other.d->x509)
         return q_X509_cmp(d->x509, other.d->x509) == 0;
     return false;
 }
publicKey()
QSslKey QSslCertificate::publicKey () const
Returns the certificate subject's public key.
Definition at line 495 of file qsslcertificate.cpp.
 {
     if (!d->x509)
         return QSslKey();
     QSslKey key;
     key.d->type = QSsl::PublicKey;
     X509_PUBKEY *xkey = d->x509->cert_info->key;
     EVP_PKEY *pkey = q_X509_PUBKEY_get(xkey);
     Q_ASSERT(pkey);
     if (q_EVP_PKEY_type(pkey->type) == EVP_PKEY_RSA) {
         key.d->rsa = q_EVP_PKEY_get1_RSA(pkey);
         key.d->algorithm = QSsl::Rsa;
         key.d->isNull = false;
     } else if (q_EVP_PKEY_type(pkey->type) == EVP_PKEY_DSA) {
         key.d->dsa = q_EVP_PKEY_get1_DSA(pkey);
         key.d->algorithm = QSsl::Dsa;
         key.d->isNull = false;
     } else if (q_EVP_PKEY_type(pkey->type) == EVP_PKEY_DH) {
         // DH unsupported
     } else {
         // error?
     }
     q_EVP_PKEY_free(pkey);
     return key;
 }
serialNumber()
QByteArray QSslCertificate::serialNumber () const
Returns the certificate's serial number string in decimal format.
In case the serial number cannot be converted to decimal format (i.e. if it is bigger than 4294967295, which means it does not fit into 4 bytes), its hexadecimal version is returned.
Definition at line 280 of file qsslcertificate.cpp.
Referenced by QSslCertificatePrivate::isBlacklisted(), and operator<<().
 {
     QMutexLocker lock(QMutexPool::globalInstanceGet(d.data()));
     if (d->serialNumberString.isEmpty() && d->x509) {
         ASN1_INTEGER *serialNumber = d->x509->cert_info->serialNumber;
         // if we cannot convert to a long, just output the hexadecimal number
         if (serialNumber->length > 4) {
             QByteArray hexString;
             hexString.reserve(serialNumber->length * 3);
             for (int a = 0; a < serialNumber->length; ++a) {
                 hexString += QByteArray::number(serialNumber->data[a], 16).rightJustified(2, '0');
                 hexString += ':';
             }
             hexString.chop(1);
             d->serialNumberString = hexString;
         } else {
             d->serialNumberString = QByteArray::number(qlonglong(q_ASN1_INTEGER_get(serialNumber)));
         }
     }
     return d->serialNumberString;
 }
subjectInfo() [1/2]
QString QSslCertificate::subjectInfo (SubjectInfo subject) const
Returns the information for the subject, or an empty string if there is no information for subject in the certificate.
See also
issuerInfo()
Definition at line 379 of file qsslcertificate.cpp.
Referenced by QSslCertificatePrivate::isBlacklisted(), operator<<(), and QSslSocketBackendPrivate::startHandshake().
 {
     QMutexLocker lock(QMutexPool::globalInstanceGet(d.data()));
     // lazy init
     if (d->subjectInfo.isEmpty() && d->x509)
         d->subjectInfo =
                 _q_mapFromX509Name(q_X509_get_subject_name(d->x509));
     return d->subjectInfo.value(_q_SubjectInfoToString(info));
 }
subjectInfo() [2/2]
QString QSslCertificate::subjectInfo (const QByteArray & tag) const
Returns the subject information for tag, or an empty string if there is no information for tag in the certificate.
See also
issuerInfo()
Definition at line 396 of file qsslcertificate.cpp.
 {
     QMutexLocker lock(QMutexPool::globalInstanceGet(d.data()));
     // lazy init
     if (d->subjectInfo.isEmpty() && d->x509)
         d->subjectInfo =
                 _q_mapFromX509Name(q_X509_get_subject_name(d->x509));
     return d->subjectInfo.value(QString::fromLatin1(tag));
 }
toDer()
QByteArray QSslCertificate::toDer () const
Returns this certificate converted to a DER (binary) encoded representation.
Definition at line 540 of file qsslcertificate.cpp.
Referenced by digest().
 {
     if (!d->x509)
         return QByteArray();
     return d->QByteArray_from_X509(d->x509, QSsl::Der);
 }
toPem()
QByteArray QSslCertificate::toPem () const
Returns this certificate converted to a PEM (Base64) encoded representation.
Definition at line 529 of file qsslcertificate.cpp.
 {
     if (!d->x509)
         return QByteArray();
     return d->QByteArray_from_X509(d->x509, QSsl::Pem);
 }
version()
QByteArray QSslCertificate::version () const
Returns the certificate's version string.
Definition at line 264 of file qsslcertificate.cpp.
Referenced by operator<<().
 {
     QMutexLocker lock(QMutexPool::globalInstanceGet(d.data()));
     if (d->versionString.isEmpty() && d->x509)
         d->versionString =
             QByteArray::number(qlonglong(q_ASN1_INTEGER_get(d->x509->cert_info->version)) + 1);
     return d->versionString;
 }
Friends and Related Functions
QSslCertificatePrivate
friend class QSslCertificatePrivate friend
Definition at line 123 of file qsslcertificate.h.
Referenced by clear().
QSslSocketBackendPrivate
friend class QSslSocketBackendPrivate friend
Definition at line 124 of file qsslcertificate.h.
Properties
d
QExplicitlySharedDataPointer<QSslCertificatePrivate> QSslCertificate::d private
Definition at line 122 of file qsslcertificate.h.
Referenced by alternateSubjectNames(), clear(), effectiveDate(), expiryDate(), handle(), QSslCertificatePrivate::init(), isNull(), issuerInfo(), isValid(), operator=(), operator==(), publicKey(), QSslCertificate(), QSslCertificatePrivate::QSslCertificate_from_X509(), serialNumber(), subjectInfo(), toDer(), toPem(), and version().
The documentation for this class was generated from the following files:
/src/network/ssl/qsslcertificate.h
/src/network/ssl/qsslcertificate.cpp