Qt 4.8: QKeyMapperPrivate Class Reference
QKeyMapperPrivate Class Reference
#include <qkeymapper_p.h>
Public Functions
void clearMappings ()
void clearRecordedKeys ()
void deleteLayouts ()
bool isADeadKey (unsigned int vk_key, unsigned int modifiers)
QList< int > possibleKeys (QKeyEvent *e)
QKeyMapperPrivate ()
bool translateKeyEvent (QWidget *receiver, const MSG &msg, bool grab)
void updateKeyMap (const MSG &msg)
void updatePossibleKeyCodes (unsigned char *kbdBuffer, quint32 scancode, quint32 vk_key)
~QKeyMapperPrivate ()
Public Functions inherited from QObjectPrivate
void _q_reregisterTimers (void *pointer)
void addConnection (int signal, Connection *c)
void cleanConnectionLists ()
void connectNotify (const char *signal)
void deleteChildren ()
void disconnectNotify (const char *signal)
bool isSender (const QObject *receiver, const char *signal) const
bool isSignalConnected (uint signalIdx) const
Returns true if the signal with index signal_index from object sender is connected.
void moveToThread_helper ()
QObjectPrivate (int version=QObjectPrivateVersion)
QObjectList receiverList (const char *signal) const
QObjectList senderList () const
void setParent_helper (QObject *)
void setThreadData_helper (QThreadData *currentData, QThreadData *targetData)
int signalIndex (const char *signalName) const
Returns the signal index used in the internal connectionLists vector.
virtual ~QObjectPrivate ()
Public Functions inherited from QObjectData
virtual ~QObjectData ()=0
Public Variables
Qt::LayoutDirection keyboardInputDirection
QLocale keyboardInputLocale
KeyboardLayoutItem * keyLayout [256]
Public Variables inherited from QObjectPrivate
union {
QObject * currentChildBeingDeleted
QAbstractDeclarativeData * declarativeData
};
quint32 connectedSignals [2]
QObjectConnectionListVector * connectionLists
Sender * currentSender
QList< QPointer< QObject > > eventFilters
ExtraData * extraData
QString objectName
Connection * senders
QAtomicPointer< QtSharedPointer::ExternalRefCountData > sharedRefcount
QThreadData * threadData
void * unused
Public Variables inherited from QObjectData
uint blockSig: 1
QObjectList children
uint hasGuards: 1
uint inEventHandler: 1
uint inThreadChangeEvent: 1
uint isWidget: 1
QMetaObject * metaObject
uint ownObjectName: 1
QObject * parent
uint pendTimer: 1
int postedEvents
QObject * q_ptr
uint receiveChildEvents: 1
uint sendChildEvents: 1
uint unused: 22
uint wasDeleted: 1
Additional Inherited Members
Public Types inherited from QObjectPrivate
typedef void(* StaticMetaCallFunction) (QObject *, QMetaObject::Call, int, void **)
Static Public Functions inherited from QObjectPrivate
static void clearGuards (QObject *)
static QObjectPrivate * get (QObject *o)
static void resetCurrentSender (QObject *receiver, Sender *currentSender, Sender *previousSender)
static Sender * setCurrentSender (QObject *receiver, Sender *sender)
static void signalSignature (const QMetaMethod &signal, QVarLengthArray< char > *result)
Detailed Description
Definition at line 145 of file qkeymapper_p.h.
Constructors and Destructors
QKeyMapperPrivate()
QKeyMapperPrivate::QKeyMapperPrivate ()
Definition at line 592 of file qkeymapper_mac.cpp.
Referenced by qt_XTranslateKey().
 {
     memset(keyLayout, 0, sizeof(keyLayout));
     keyboard_layout_format.unicode = 0;
 #ifdef Q_OS_MAC32
     keyboard_mode = NullMode;
 #else
     currentInputSource = 0;
 #endif
 }
~QKeyMapperPrivate()
QKeyMapperPrivate::~QKeyMapperPrivate ()
Definition at line 603 of file qkeymapper_mac.cpp.
Referenced by qt_XTranslateKey().
 {
     deleteLayouts();
 }
Functions
clearMappings()
void QKeyMapperPrivate::clearMappings ()
Definition at line 696 of file qkeymapper_mac.cpp.
 {
     deleteLayouts();
     updateKeyboard();
 }
clearRecordedKeys()
void QKeyMapperPrivate::clearRecordedKeys ()
Definition at line 651 of file qkeymapper_win.cpp.
 {
     key_recorder.clearKeys();
 }
deleteLayouts()
void QKeyMapperPrivate::deleteLayouts ()
Definition at line 684 of file qkeymapper_mac.cpp.
 {
     keyboard_mode = NullMode;
     for (int i = 0; i < 255; ++i) {
         if (keyLayout[i]) {
             delete keyLayout[i];
             keyLayout[i] = 0;
         }
     }
 }
isADeadKey()
bool QKeyMapperPrivate::isADeadKey (unsigned int vk_key, unsigned int modifiers)
Definition at line 760 of file qkeymapper_win.cpp.
 {
     if (keyLayout && (vk_key < 256) && keyLayout[vk_key]) {
         for(register int i = 0; i < 9; ++i) {
             if (uint(ModsTbl[i]) == modifiers)
                 return bool(keyLayout[vk_key]->deadkeys & 1<<i);
         }
     }
     return false;
 }
possibleKeys()
QList< int > QKeyMapperPrivate::possibleKeys (QKeyEvent * e)
Definition at line 703 of file qkeymapper_mac.cpp.
Referenced by isADeadKey(), and qt_XTranslateKey().
 {
     QList<int> ret;
     KeyboardLayoutItem *kbItem = keyLayout[e->nativeVirtualKey()];
     if (!kbItem) // Key is not in any keyboard layout (e.g. eisu-key on Japanese keyboard)
         return ret;
     int baseKey = kbItem->qtKey[0];
     Qt::KeyboardModifiers keyMods = e->modifiers();
     ret << int(baseKey + keyMods); // The base key is _always_ valid, of course
     for (int i = 1; i < 8; ++i) {
         Qt::KeyboardModifiers neededMods = ModsTbl[i];
         int key = kbItem->qtKey[i];
         if (key && key != baseKey && ((keyMods & neededMods) == neededMods))
             ret << int(key + (keyMods & ~neededMods));
     }
     return ret;
 }
translateKeyEvent()
bool QKeyMapperPrivate::translateKeyEvent (QWidget * receiver, const MSG & msg, bool grab)
Definition at line 725 of file qkeymapper_mac.cpp.
Referenced by QMacInputContext::globalEventProcessor(), QApplicationPrivate::globalEventProcessor(), isADeadKey(), qt_dispatchKeyEvent(), qt_keyrelease_scanner(), QtWndProc(), and QApplication::x11ProcessEvent().
 {
     Q_ASSERT(GetEventClass(event) == kEventClassKeyboard);
     bool handled_event=true;
     UInt32 ekind = GetEventKind(event);
     // unfortunately modifiers changed event looks quite different, so I have a separate
     // code path
     if (ekind == kEventRawKeyModifiersChanged) {
         //figure out changed modifiers, wish Apple would just send a delta
         UInt32 modifiers = 0;
         GetEventParameter(event, kEventParamKeyModifiers, typeUInt32, 0,
                           sizeof(modifiers), 0, &modifiers);
         qt_mac_send_modifiers_changed(modifiers, widget);
         return true;
     }
 #ifndef QT_NO_IM
     QInputContext *currentContext = qApp->inputContext();
     if (currentContext && currentContext->isComposing()) {
         if (ekind == kEventRawKeyDown) {
             QMacInputContext *context = qobject_cast<QMacInputContext*>(currentContext);
             if (context)
                 context->setLastKeydownEvent(event);
         }
         return false;
     }
     // Once we process the key down , we don't need to send the saved event again from
     // kEventTextInputUnicodeForKeyEvent, so clear it.
     if (currentContext && ekind == kEventRawKeyDown) {
         QMacInputContext *context = qobject_cast<QMacInputContext*>(currentContext);
         if (context)
             context->setLastKeydownEvent(0);
     }
 #endif
     //get modifiers
     Qt::KeyboardModifiers modifiers;
     int qtKey;
     QChar ourChar;
     if (translateKeyEventInternal(er, event, &qtKey, &ourChar, &modifiers,
                                   &handled_event) == false)
         return handled_event;
     QString text(ourChar);
     /* This is actually wrong - but unfortunately it is the best that can be
        done for now because of the Control/Meta mapping problems */
     if (modifiers & (Qt::ControlModifier | Qt::MetaModifier)
         && !qApp->testAttribute(Qt::AA_MacDontSwapCtrlAndMeta)) {
         text = QString();
     }
     if (widget) {
 #ifndef QT_MAC_USE_COCOA
         Q_UNUSED(info);
         // Try not to call "other" event handlers if we have a popup,
         // However, if the key has text
         // then we should pass it along because otherwise then people
         // can use input method stuff.
         if (!qApp->activePopupWidget()
                 || (qApp->activePopupWidget() && !text.isEmpty())) {
             //Find out if someone else wants the event, namely
             //is it of use to text services? If so we won't bother
             //with a QKeyEvent.
             qt_mac_eat_unicode_key = false;
             if (er)
                 CallNextEventHandler(er, event);
             extern bool qt_mac_menubar_is_open();
             if (qt_mac_eat_unicode_key || qt_mac_menubar_is_open()) {
                 return true;
             }
         }
 #endif
         // Try to compress key events.
         if (!text.isEmpty() && widget->testAttribute(Qt::WA_KeyCompression)) {
             EventTime lastTime = GetEventTime(event);
             for (;;) {
                 EventRef releaseEvent = FindSpecificEventInQueue(GetMainEventQueue(),
                                                                  qt_KeyEventComparatorProc,
                                                                  (void*)kEventRawKeyUp);
                 if (!releaseEvent)
                     break;
                 const EventTime releaseTime = GetEventTime(releaseEvent);
                 if (releaseTime < lastTime)
                     break;
                 lastTime = releaseTime;
                 EventRef pressEvent = FindSpecificEventInQueue(GetMainEventQueue(),
                                                                qt_KeyEventComparatorProc,
                                                                (void*)kEventRawKeyDown);
                 if (!pressEvent)
                     break;
                 const EventTime pressTime = GetEventTime(pressEvent);
                 if (pressTime < lastTime)
                     break;
                 lastTime = pressTime;
                 Qt::KeyboardModifiers compressMod;
                 int compressQtKey = 0;
                 QChar compressChar;
                 if (translateKeyEventInternal(er, pressEvent,
                                               &compressQtKey, &compressChar, &compressMod, 0)
                     == false) {
                     break;
                 }
                 // Copied from qapplication_x11.cpp (change both).
                 bool stopCompression =
                     // 1) misc keys
                     (compressQtKey >= Qt::Key_Escape && compressQtKey <= Qt::Key_SysReq)
                     // 2) cursor movement
                     || (compressQtKey >= Qt::Key_Home && compressQtKey <= Qt::Key_PageDown)
                     // 3) extra keys
                     || (compressQtKey >= Qt::Key_Super_L && compressQtKey <= Qt::Key_Direction_R)
                     // 4) something that a) doesn't translate to text or b) translates
                     //    to newline text
                     || (compressQtKey == 0)
                     || (compressChar == QLatin1Char('\n'))
                     || (compressQtKey == Qt::Key_unknown);
                 if (compressMod == modifiers && !compressChar.isNull() && !stopCompression) {
 #ifdef DEBUG_KEY_BINDINGS
                     qDebug("compressing away %c", compressChar.toLatin1());
 #endif
                     text += compressChar;
                     // Clean up
                     RemoveEventFromQueue(GetMainEventQueue(), releaseEvent);
                     RemoveEventFromQueue(GetMainEventQueue(), pressEvent);
                 } else {
 #ifdef DEBUG_KEY_BINDINGS
                     qDebug("stoping compression..");
 #endif
                     break;
                 }
             }
         }
         // There is no way to get the scan code from carbon. But we cannot use the value 0, since
         // it indicates that the event originates from somewhere else than the keyboard
         UInt32 macScanCode = 1;
         UInt32 macVirtualKey = 0;
         GetEventParameter(event, kEventParamKeyCode, typeUInt32, 0, sizeof(macVirtualKey), 0, &macVirtualKey);
         UInt32 macModifiers = 0;
         GetEventParameter(event, kEventParamKeyModifiers, typeUInt32, 0,
                           sizeof(macModifiers), 0, &macModifiers);
 #ifdef QT_MAC_USE_COCOA
         // The unicode characters in the range 0xF700-0xF747 are reserved
         // by Mac OS X for transient use as keyboard function keys. We
         // wont send 'text' for such key events. This is done to match
         // behavior on other platforms.
         unsigned int *unicodeKey = (unsigned int*)info;
         if (*unicodeKey >= 0xf700 && *unicodeKey <= 0xf747)
             text = QString();
         bool isAccepted;
 #endif
         handled_event = QKeyMapper::sendKeyEvent(widget, grab,
                                                  (ekind == kEventRawKeyUp) ? QEvent::KeyRelease : QEvent::KeyPress,
                                                  qtKey, modifiers, text, ekind == kEventRawKeyRepeat, 0,
                                                  macScanCode, macVirtualKey, macModifiers
 #ifdef QT_MAC_USE_COCOA
                                                  ,&isAccepted
 #endif
                                                  );
 #ifdef QT_MAC_USE_COCOA
         *unicodeKey = (unsigned int)isAccepted;
 #endif
     }
     return handled_event;
 }
updateKeyMap()
void QKeyMapperPrivate::updateKeyMap (const MSG & msg)
Definition at line 895 of file qkeymapper_mac.cpp.
Referenced by QApplicationPrivate::globalEventProcessor(), qt_dispatchKeyEvent(), QtWndProc(), and setKbdState().
 {
     UInt32 macVirtualKey = 0;
     GetEventParameter(event, kEventParamKeyCode, typeUInt32, 0, sizeof(macVirtualKey), 0, &macVirtualKey);
     if (updateKeyboard())
        QKeyMapper::changeKeyboard();
     else if (keyLayout[macVirtualKey])
         return;
     UniCharCount buffer_size = 10;
     UniChar buffer[buffer_size];
     keyLayout[macVirtualKey] = new KeyboardLayoutItem;
     for (int i = 0; i < 16; ++i) {
         UniCharCount out_buffer_size = 0;
         keyLayout[macVirtualKey]->qtKey[i] = 0;
 #ifdef Q_WS_MAC32
         if (keyboard_mode == UnicodeMode) {
 #endif
             const UInt32 keyModifier = ((qt_mac_get_mac_modifiers(ModsTbl[i]) >> 8) & 0xFF);
             OSStatus err = UCKeyTranslate(keyboard_layout_format.unicode, macVirtualKey, kUCKeyActionDown, keyModifier,
                                           keyboard_kind, 0, &keyboard_dead, buffer_size, &out_buffer_size, buffer);
             if (err == noErr && out_buffer_size) {
                 const QChar unicode(buffer[0]);
                 int qtkey = qt_mac_get_key(keyModifier, unicode, macVirtualKey);
                 if (qtkey == Qt::Key_unknown)
                     qtkey = unicode.unicode();
                 keyLayout[macVirtualKey]->qtKey[i] = qtkey;
             }
 #ifndef Q_WS_MAC32
             else {
                 const QChar unicode(*((UniChar *)unicodeKey));
                 int qtkey = qt_mac_get_key(keyModifier, unicode, macVirtualKey);
                 if (qtkey == Qt::Key_unknown)
                     qtkey = unicode.unicode();
                 keyLayout[macVirtualKey]->qtKey[i] = qtkey;
             }
 #endif
 #ifdef Q_WS_MAC32
         } else {
             const UInt32 keyModifier = (qt_mac_get_mac_modifiers(ModsTbl[i]));
             uchar translatedChar = KeyTranslate(keyboard_layout_format.other, keyModifier | macVirtualKey, &keyboard_dead);
             if (translatedChar) {
                 static QTextCodec *c = 0;
                 if (!c)
                     c = QTextCodec::codecForName("Apple Roman");
                 const QChar unicode(c->toUnicode((const char *)&translatedChar, 1).at(0));
                 int qtkey = qt_mac_get_key(keyModifier, unicode, macVirtualKey);
                 if (qtkey == Qt::Key_unknown)
                     qtkey = unicode.unicode();
                 keyLayout[macVirtualKey]->qtKey[i] = qtkey;
             }
         }
 #endif
     }
 #ifdef DEBUG_KEY_MAPS
     qDebug("updateKeyMap for virtual key = 0x%02x!", (uint)macVirtualKey);
     for (int i = 0; i < 16; ++i) {
         qDebug("    [%d] (%d,0x%02x,'%c')", i,
                keyLayout[macVirtualKey]->qtKey[i],
                keyLayout[macVirtualKey]->qtKey[i],
                keyLayout[macVirtualKey]->qtKey[i]);
     }
 #endif
 }
updatePossibleKeyCodes()
void QKeyMapperPrivate::updatePossibleKeyCodes (unsigned char * kbdBuffer, quint32 scancode, quint32 vk_key)
Definition at line 675 of file qkeymapper_win.cpp.
 {
     if (!vk_key || (keyLayout[vk_key] && !keyLayout[vk_key]->dirty))
         return;
     if (!keyLayout[vk_key])
         keyLayout[vk_key] = new KeyboardLayoutItem;
     // Copy keyboard state, so we can modify and query output for each possible permutation
     unsigned char buffer[256];
     memcpy(buffer, kbdBuffer, sizeof(buffer));
     // Always 0, as Windows doesn't treat these as modifiers;
     buffer[VK_LWIN    ] = 0;
     buffer[VK_RWIN    ] = 0;
     buffer[VK_CAPITAL ] = 0;
     buffer[VK_NUMLOCK ] = 0;
     buffer[VK_SCROLL  ] = 0;
     // Always 0, since we'll only change the other versions
     buffer[VK_RSHIFT  ] = 0;
     buffer[VK_RCONTROL] = 0;
     buffer[VK_LMENU   ] = 0; // Use right Alt, since left Ctrl + right Alt is considered AltGraph
     bool isDeadKey = false;
     keyLayout[vk_key]->deadkeys = 0;
     keyLayout[vk_key]->dirty = false;
     setKbdState(buffer, false, false, false);
     keyLayout[vk_key]->qtKey[0] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x01 : 0;
     setKbdState(buffer, true, false, false);
     keyLayout[vk_key]->qtKey[1] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x02 : 0;
     setKbdState(buffer, false, true, false);
     keyLayout[vk_key]->qtKey[2] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x04 : 0;
     setKbdState(buffer, true, true, false);
     keyLayout[vk_key]->qtKey[3] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x08 : 0;
     setKbdState(buffer, false, false, true);
     keyLayout[vk_key]->qtKey[4] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x10 : 0;
     setKbdState(buffer, true, false, true);
     keyLayout[vk_key]->qtKey[5] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x20 : 0;
     setKbdState(buffer, false, true, true);
     keyLayout[vk_key]->qtKey[6] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x40 : 0;
     setKbdState(buffer, true, true, true);
     keyLayout[vk_key]->qtKey[7] = toKeyOrUnicode(vk_key, scancode, buffer, &isDeadKey);
     keyLayout[vk_key]->deadkeys |= isDeadKey ? 0x80 : 0;
     // Add a fall back key for layouts which don't do composition and show non-latin1 characters
     int fallbackKey = winceKeyBend(vk_key);
     if (!fallbackKey || fallbackKey == Qt::Key_unknown) {
         fallbackKey = 0;
         if (vk_key != keyLayout[vk_key]->qtKey[0] && vk_key < 0x5B && vk_key > 0x2F)
             fallbackKey = vk_key;
     }
     keyLayout[vk_key]->qtKey[8] = fallbackKey;
     // If this vk_key makes a dead key with any combination of modifiers
     if (keyLayout[vk_key]->deadkeys) {
         // Push a Space, then the original key through the low-level ToAscii functions.
         // We do this because these functions (ToAscii / ToUnicode) will alter the internal state of
         // the keyboard driver By doing the following, we set the keyboard driver state back to what
         // it was before we wrecked it with the code above.
         // We need to push the space with an empty keystate map, since the driver checks the map for
         // transitions in modifiers, so this helps us capture all possible deadkeys.
         unsigned char emptyBuffer[256];
         memset(emptyBuffer, 0, sizeof(emptyBuffer));
         ::ToAscii(VK_SPACE, 0, emptyBuffer, reinterpret_cast<LPWORD>(&buffer), 0);
         ::ToAscii(vk_key, scancode, kbdBuffer, reinterpret_cast<LPWORD>(&buffer), 0);
     }
 #ifdef DEBUG_KEYMAPPER
     qDebug("updatePossibleKeyCodes for virtual key = 0x%02x!", vk_key);
     for (int i = 0; i < 9; ++i) {
         qDebug("    [%d] (%d,0x%02x,'%c')  %s", i,
                keyLayout[vk_key]->qtKey[i],
                keyLayout[vk_key]->qtKey[i],
                keyLayout[vk_key]->qtKey[i] ? keyLayout[vk_key]->qtKey[i] : 0x03,
                keyLayout[vk_key]->deadkeys & (1<<i) ? "deadkey" : "");
     }
 #endif // DEBUG_KEYMAPPER
 }
Properties
keyboardInputDirection
Qt::LayoutDirection QKeyMapperPrivate::keyboardInputDirection
Definition at line 156 of file qkeymapper_p.h.
Referenced by QApplication::keyboardInputDirection().
keyboardInputLocale
QLocale QKeyMapperPrivate::keyboardInputLocale
Definition at line 155 of file qkeymapper_p.h.
Referenced by QApplication::keyboardInputLocale().
keyLayout
KeyboardLayoutItem* QKeyMapperPrivate::keyLayout[256]
Definition at line 166 of file qkeymapper_p.h.
The documentation for this class was generated from the following files:
/src/gui/kernel/qkeymapper_p.h
/src/gui/kernel/qkeymapper_mac.cpp
/src/gui/kernel/qkeymapper_qws.cpp
/src/gui/kernel/qkeymapper_win.cpp
/src/gui/kernel/qkeymapper_x11.cpp