Qt 4.8: QAbstractEventDispatcher Class Reference
QAbstractEventDispatcher Class Reference abstract
The QAbstractEventDispatcher class provides an interface to manage Qt's event queue.
#include <qabstracteventdispatcher.h>
Public Types
typedef bool(* EventFilter) (void *message)
Typedef for a function with the signature.
typedef QPair< int, int > TimerInfo
Typedef for QPair<int, int>.
Signals
void aboutToBlock ()
This signal is emitted before the event loop calls a function that could block.
void awake ()
This signal is emitted after the event loop returns from a function that could block.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
virtual void closingDown ()
bool filterEvent (void *message)
Sends message through the event filter that was set by setEventFilter().
virtual void flush ()=0
Flushes the event queue.
virtual bool hasPendingEvents ()=0
Returns true if there is an event waiting; otherwise returns false.
virtual void interrupt ()=0
Interrupts event dispatching; i.
virtual bool processEvents (QEventLoop::ProcessEventsFlags flags)=0
Processes pending events that match flags until there are no more events to process.
QAbstractEventDispatcher (QObject *parent=0)
Constructs a new event dispatcher with the given parent.
virtual QList< TimerInfo > registeredTimers (QObject *object) const =0
Returns a list of registered timers for object.
virtual void registerSocketNotifier (QSocketNotifier *notifier)=0
Registers notifier with the event loop.
int registerTimer (int interval, QObject *object)
Registers a timer with the specified interval for the given object.
virtual void registerTimer (int timerId, int interval, QObject *object)=0
Register a timer with the specified timerId and interval for the given object.
EventFilter setEventFilter (EventFilter filter)
Replaces the event filter function for this QAbstractEventDispatcher with filter and returns the replaced event filter function.
virtual void startingUp ()
virtual void unregisterSocketNotifier (QSocketNotifier *notifier)=0
Unregisters notifier from the event dispatcher.
virtual bool unregisterTimer (int timerId)=0
Unregisters the timer with the given timerId.
virtual bool unregisterTimers (QObject *object)=0
Unregisters all the timers associated with the given object.
virtual void wakeUp ()=0
Wakes up the event loop.
~QAbstractEventDispatcher ()
Destroys the event dispatcher.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Functions
static QAbstractEventDispatcher * instance (QThread *thread=0)
Returns a pointer to the event dispatcher object for the specified thread.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions
QAbstractEventDispatcher (QAbstractEventDispatcherPrivate &, QObject *parent)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
The QAbstractEventDispatcher class provides an interface to manage Qt's event queue.
An event dispatcher receives events from the window system and other sources. It then sends them to the QCoreApplication or QApplication instance for processing and delivery. QAbstractEventDispatcher provides fine-grained control over event delivery.
For simple control of event processing use QCoreApplication::processEvents().
For finer control of the application's event loop, call instance() and call functions on the QAbstractEventDispatcher object that is returned. If you want to use your own instance of QAbstractEventDispatcher or of a QAbstractEventDispatcher subclass, you must create your instance before you create the QApplication object.
The main event loop is started by calling QCoreApplication::exec(), and stopped by calling QCoreApplication::exit(). Local event loops can be created using QEventLoop.
Programs that perform long operations can call processEvents() with a bitwise OR combination of various QEventLoop::ProcessEventsFlag values to control which events should be delivered.
QAbstractEventDispatcher also allows the integration of an external event loop with the Qt event loop. For example, the Motif Extension includes a reimplementation of QAbstractEventDispatcher that merges Qt and Motif events together.
See also
QEventLoop, QCoreApplication
Definition at line 58 of file qabstracteventdispatcher.h.
Typedefs
EventFilter
QAbstractEventDispatcher::EventFilter
Typedef for a function with the signature.
bool myEventFilter(void *message);
Note that the type of the message is platform dependent. The following table shows the {message}'s type on Windows, Mac, X11 and BlackBerry. You can do a static cast to these types.
Platform type
Windows MSG
X11 XEvent
Mac NSEvent
BlackBerry bps_event_t
See also
setEventFilter(), filterEvent()
Definition at line 90 of file qabstracteventdispatcher.h.
TimerInfo
QAbstractEventDispatcher::TimerInfo
Typedef for QPair<int, int>.
The first component of the pair is the timer ID; the second component is the interval.
See also
registeredTimers()
Definition at line 64 of file qabstracteventdispatcher.h.
Constructors and Destructors
QAbstractEventDispatcher() [1/2]
QAbstractEventDispatcher::QAbstractEventDispatcher (QObject * parent = 0) explicit
Constructs a new event dispatcher with the given parent.
Definition at line 281 of file qabstracteventdispatcher.cpp.
     : QObject(*new QAbstractEventDispatcherPrivate, parent)
 {
     Q_D(QAbstractEventDispatcher);
     d->init();
 }
~QAbstractEventDispatcher()
QAbstractEventDispatcher::~QAbstractEventDispatcher ()
Destroys the event dispatcher.
Definition at line 302 of file qabstracteventdispatcher.cpp.
 { }
QAbstractEventDispatcher() [2/2]
QAbstractEventDispatcher::QAbstractEventDispatcher (QAbstractEventDispatcherPrivate & dd, QObject * parent) protected
Warning
This function is not part of the public interface.
Definition at line 291 of file qabstracteventdispatcher.cpp.
     : QObject(dd, parent)
 {
     Q_D(QAbstractEventDispatcher);
     d->init();
 }
Functions
aboutToBlock
void QAbstractEventDispatcher::aboutToBlock () signal
This signal is emitted before the event loop calls a function that could block.
See also
awake()
Referenced by QEventDispatcherGlib::processEvents(), QEventDispatcherUNIX::processEvents(), QEventDispatcherBlackberry::select(), and QEventDispatcherMacPrivate::waitingObserverCallback().
awake
void QAbstractEventDispatcher::awake () signal
This signal is emitted after the event loop returns from a function that could block.
See also
wakeUp() aboutToBlock()
Referenced by QEventDispatcherGlib::processEvents(), QEventDispatcherWin32::processEvents(), QEventDispatcherUNIX::processEvents(), QEventDispatcherBlackberry::select(), and QEventDispatcherMacPrivate::waitingObserverCallback().
closingDown()
void QAbstractEventDispatcher::closingDown () virtual
Warning
This function is not part of the public interface.
Reimplemented in QEventDispatcherWin32, QEventDispatcherQWS, and QEventDispatcherX11.
Definition at line 466 of file qabstracteventdispatcher.cpp.
Referenced by QThreadPrivate::finish(), and QCoreApplication::~QCoreApplication().
 { }
filterEvent()
bool QAbstractEventDispatcher::filterEvent (void * message)
Sends message through the event filter that was set by setEventFilter().
If no event filter has been set, this function returns false; otherwise, this function returns the result of the event filter function.
Subclasses of QAbstractEventDispatcher must call this function for all messages received from the system to ensure compatibility with any extensions that may be used in the application.
Note that the type of message is platform dependent. See QAbstractEventDispatcher::EventFilter for details.
See also
setEventFilter()
Definition at line 560 of file qabstracteventdispatcher.cpp.
Referenced by QX11Data::clipboardWaitForEvent(), QX11Data::dndEnable(), QEventDispatcherX11::processEvents(), QEventDispatcherQWS::processEvents(), QEventDispatcherQPA::processEvents(), qwsEventSourceDispatch(), QEventDispatcherBlackberry::select(), userEventSourceDispatch(), and x11EventSourceDispatch().
 {
     Q_D(QAbstractEventDispatcher);
     if (d->event_filter) {
         // Raise the loopLevel so that deleteLater() calls in or triggered
         // by event_filter() will be processed from the main event loop.
         QScopedLoopLevelCounter loopLevelCounter(d->threadData);
         return d->event_filter(message);
     }
     return false;
 }
flush()
void QAbstractEventDispatcher::flush () pure virtual
Flushes the event queue.
This normally returns almost immediately. Does nothing on platforms other than X11.
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, QEventDispatcherGlib, QEventDispatcherQPA, QEventDispatcherQWS, QEventDispatcherX11, QGuiEventDispatcherGlib, and QEventDispatcherBlackberryQPA.
hasPendingEvents()
bool QAbstractEventDispatcher::hasPendingEvents () pure virtual
Returns true if there is an event waiting; otherwise returns false.
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, QEventDispatcherGlib, QEventDispatcherQPA, QEventDispatcherQWS, QEventDispatcherX11, and QEventDispatcherBlackberryQPA.
Referenced by QCoreApplication::hasPendingEvents().
instance()
QAbstractEventDispatcher * QAbstractEventDispatcher::instance (QThread * thread = 0) static
Returns a pointer to the event dispatcher object for the specified thread.
If thread is zero, the current thread is used. If no event dispatcher exists for the specified thread, this function returns 0.
Note: If Qt is built without thread support, the thread argument is ignored.
Definition at line 314 of file qabstracteventdispatcher.cpp.
Referenced by QAxWidget::clear(), QX11Data::clipboardWaitForEvent(), QAxWidget::createHostWindow(), QClassFactory::CreateInstanceHelper(), QX11Data::dndEnable(), QEventDispatcherMac::flush(), QCoreApplication::hasPendingEvents(), QBBEngine::initialize(), QHostInfo::lookupHost(), QBBIntegration::QBBIntegration(), qt_GetMessageHook(), qt_x11_wait_for_window_manager(), QWaylandDisplay::QWaylandDisplay(), QXcbConnection::QXcbConnection(), QNSOpenSavePanelDelegate::runApplicationModalPanel, QWidgetPrivate::show_sys(), QBenchmarkEvent::start(), QBasicTimer::stop(), QBenchmarkEvent::stop(), QETWidget::translateMouseEvent(), QBBEngine::~QBBEngine(), and QEventDispatcherMac::~QEventDispatcherMac().
 {
     QThreadData *data = thread ? QThreadData::get2(thread) : QThreadData::current();
     return data->eventDispatcher;
 }
interrupt()
void QAbstractEventDispatcher::interrupt () pure virtual
Interrupts event dispatching; i.
e. the event dispatcher will return from processEvents() as soon as possible.
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, and QEventDispatcherGlib.
Referenced by QEventDispatcherMac::flush(), QNSOpenSavePanelDelegate::runApplicationModalPanel, QWidgetPrivate::show_sys(), and QEventDispatcherMac::~QEventDispatcherMac().
processEvents()
bool QAbstractEventDispatcher::processEvents (QEventLoop::ProcessEventsFlags flags) pure virtual
Processes pending events that match flags until there are no more events to process.
Returns true if an event was processed; otherwise returns false.
This function is especially useful if you have a long running operation and want to show its progress without allowing user input; i.e. by using the QEventLoop::ExcludeUserInputEvents flag.
If the QEventLoop::WaitForMoreEvents flag is set in flags, the behavior of this function is as follows:
If events are available, this function returns after processing them.
If no events are available, this function will wait until more are available and return after processing newly available events.
If the QEventLoop::WaitForMoreEvents flag is not set in flags, and no events are available, this function will return immediately.
Note: This function does not process events continuously; it returns after all available events are processed.
See also
hasPendingEvents()
Implemented in QGuiEventDispatcherWin32, QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, QEventDispatcherGlib, QPAEventDispatcherGlib, QWSEventDispatcherGlib, QEventDispatcherQPA, QEventDispatcherQWS, QEventDispatcherX11, QGuiEventDispatcherGlib, and QEventDispatcherBlackberryQPA.
Referenced by QX11Data::clipboardWaitForEvent(), and QCoreApplication::processEvents().
registeredTimers()
QList< TimerInfo > QAbstractEventDispatcher::registeredTimers (QObject * object) const pure virtual
Returns a list of registered timers for object.
The timer ID is the first member in each pair; the interval is the second.
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, and QEventDispatcherGlib.
Referenced by QObject::event().
registerSocketNotifier()
void QAbstractEventDispatcher::registerSocketNotifier (QSocketNotifier * notifier) pure virtual
Registers notifier with the event loop.
Subclasses must implement this method to tie a socket notifier into another event loop.
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, QEventDispatcherGlib, QEventDispatcherQPA, and QEventDispatcherBlackberry.
registerTimer() [1/2]
int QAbstractEventDispatcher::registerTimer (int interval, QObject * object)
Registers a timer with the specified interval for the given object.
Definition at line 387 of file qabstracteventdispatcher.cpp.
Referenced by QObject::startTimer().
 {
     int id = QAbstractEventDispatcherPrivate::allocateTimerId();
     registerTimer(id, interval, object);
     return id;
 }
registerTimer() [2/2]
void QAbstractEventDispatcher::registerTimer (int timerId, int interval, QObject * object) pure virtual
Register a timer with the specified timerId and interval for the given object.
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, and QEventDispatcherGlib.
setEventFilter()
QAbstractEventDispatcher::EventFilter QAbstractEventDispatcher::setEventFilter (EventFilter filter)
Replaces the event filter function for this QAbstractEventDispatcher with filter and returns the replaced event filter function.
Only the current event filter function is called. If you want to use both filter functions, save the replaced EventFilter in a place where yours can call it.
The event filter function set here is called for all messages taken from the system event loop before the event is dispatched to the respective target, including the messages not meant for Qt objects.
The event filter function should return true if the message should be filtered, (i.e. stopped). It should return false to allow processing the message to continue.
By default, no event filter function is set (i.e., this function returns a null EventFilter the first time it is called).
Definition at line 536 of file qabstracteventdispatcher.cpp.
Referenced by QAxWidget::clear(), QAxWidget::createHostWindow(), QClassFactory::CreateInstanceHelper(), QBBEngine::initialize(), QBenchmarkEvent::start(), QBenchmarkEvent::stop(), and QBBEngine::~QBBEngine().
 {
     Q_D(QAbstractEventDispatcher);
     EventFilter oldFilter = d->event_filter;
     d->event_filter = filter;
     return oldFilter;
 }
startingUp()
void QAbstractEventDispatcher::startingUp () virtual
Warning
This function is not part of the public interface.
Reimplemented in QEventDispatcherWin32, QEventDispatcherQWS, QEventDispatcherX11, QWSEventDispatcherGlib, and QGuiEventDispatcherGlib.
Definition at line 462 of file qabstracteventdispatcher.cpp.
Referenced by QThreadPrivate::createEventDispatcher(), QCoreApplication::QCoreApplication(), and qt_adopted_thread_watcher_function().
 { }
unregisterSocketNotifier()
void QAbstractEventDispatcher::unregisterSocketNotifier (QSocketNotifier * notifier) pure virtual
Unregisters notifier from the event dispatcher.
Subclasses must reimplement this method to tie a socket notifier into another event loop. Reimplementations must call the base implementation.
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, QEventDispatcherGlib, QEventDispatcherQPA, and QEventDispatcherBlackberry.
unregisterTimer()
bool QAbstractEventDispatcher::unregisterTimer (int timerId) pure virtual
Unregisters the timer with the given timerId.
Returns true if successful; otherwise returns false.
See also
registerTimer(), unregisterTimers()
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, and QEventDispatcherGlib.
Referenced by QObject::killTimer(), and QBasicTimer::stop().
unregisterTimers()
bool QAbstractEventDispatcher::unregisterTimers (QObject * object) pure virtual
Unregisters all the timers associated with the given object.
Returns true if all timers were successful removed; otherwise returns false.
See also
unregisterTimer(), registeredTimers()
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, and QEventDispatcherGlib.
Referenced by QObject::event(), and QObjectPrivate::~QObjectPrivate().
wakeUp()
void QAbstractEventDispatcher::wakeUp () pure virtual
Wakes up the event loop.
Note
This class or function is threadsafe.
See also
awake()
Implemented in QEventDispatcherUNIX, QEventDispatcherMac, QEventDispatcherWin32, QEventDispatcherGlib, and QEventDispatcherBlackberry.
Referenced by QWindowSystemInterfacePrivate::queueWindowSystemEvent(), QCoreApplicationPrivate::sendPostedEvents(), and QObjectPrivate::setThreadData_helper().
The documentation for this class was generated from the following files:
/src/corelib/kernel/qabstracteventdispatcher.h
/src/corelib/kernel/qabstracteventdispatcher.cpp