Qt 4.8: CachedShader Class Reference
CachedShader Class Reference
#include <qglshadercache_p.h>
Public Functions
CachedShader (const QByteArray &, const QByteArray &)
bool isCached ()
bool load (QGLShaderProgram *, const QGLContext *)
bool store (QGLShaderProgram *, const QGLContext *)
Detailed Description
Definition at line 71 of file qglshadercache_p.h.
Constructors and Destructors
CachedShader()
CachedShader::CachedShader (const QByteArray & , const QByteArray &) inline
Definition at line 74 of file qglshadercache_p.h.
     {}
Functions
isCached()
bool CachedShader::isCached () inline
Definition at line 77 of file qglshadercache_p.h.
     {
         return false;
     }
load()
bool CachedShader::load (QGLShaderProgram * , const QGLContext *) inline
Definition at line 82 of file qglshadercache_p.h.
Referenced by QGLEngineSharedShaders::findProgramInCache(), and QGLEngineSharedShaders::QGLEngineSharedShaders().
     {
         return false;
     }
store()
bool CachedShader::store (QGLShaderProgram * , const QGLContext *) inline
Definition at line 87 of file qglshadercache_p.h.
Referenced by QGLEngineSharedShaders::findProgramInCache(), and QGLEngineSharedShaders::QGLEngineSharedShaders().
     {
         return false;
     }
The documentation for this class was generated from the following file:
/src/opengl/gl2paintengineex/qglshadercache_p.h