Qt 4.8: QBlittablePixmapData Class Reference
QBlittablePixmapData Class Reference abstract
#include <qpixmap_blitter_p.h>
Public Functions
QBlittable * blittable () const
QImage * buffer ()
virtual QBlittable * createBlittable (const QSize &size, bool alpha) const =0
void fill (const QColor &color)
void fromImage (const QImage &image, Qt::ImageConversionFlags flags)
bool hasAlphaChannel () const
void markRasterOverlay (const QRectF &)
void markRasterOverlay (const QPointF &, const QTextItem &)
void markRasterOverlay (const QVectorPath &)
void markRasterOverlay (const QPainterPath &)
void markRasterOverlay (const QRect *rects, int rectCount)
void markRasterOverlay (const QRectF *rects, int rectCount)
void markRasterOverlay (const QPointF *points, int pointCount)
void markRasterOverlay (const QPoint *points, int pointCount)
int metric (QPaintDevice::PaintDeviceMetric metric) const
QPaintEngine * paintEngine () const
QBlittablePixmapData ()
void resize (int width, int height)
void setBlittable (QBlittable *blittable)
QImage toImage () const
void unmarkRasterOverlay (const QRectF &)
~QBlittablePixmapData ()
Public Functions inherited from QPixmapData
virtual QPixmap alphaChannel () const
qint64 cacheKey () const
ClassId classId () const
int colorCount () const
virtual void copy (const QPixmapData *data, const QRect &rect)
virtual QPixmapData * createCompatiblePixmapData () const
int depth () const
virtual bool fromData (const uchar *buffer, uint len, const char *format, Qt::ImageConversionFlags flags)
virtual bool fromFile (const QString &filename, const char *format, Qt::ImageConversionFlags flags)
virtual void fromImageReader (QImageReader *imageReader, Qt::ImageConversionFlags flags)
int height () const
bool isNull () const
virtual QBitmap mask () const
QT_DEPRECATED int numColors () const
PixelType pixelType () const
QPixmapData (PixelType pixelType, int classId)
virtual QPixmapData * runtimeData () const
virtual bool scroll (int dx, int dy, const QRect &rect)
int serialNumber () const
virtual void setAlphaChannel (const QPixmap &alphaChannel)
virtual void setMask (const QBitmap &mask)
virtual QImage toImage (const QRect &rect) const
virtual QPixmap transformed (const QTransform &matrix, Qt::TransformationMode mode) const
int width () const
virtual ~QPixmapData ()
Protected Variables
bool m_alpha
QScopedPointer< QBlittable > m_blittable
QScopedPointer< QBlitterPaintEngine > m_engine
Protected Variables inherited from QPixmapData
int d
int h
bool is_null
int w
Additional Inherited Members
Public Types inherited from QPixmapData
enum ClassId {
RasterClass, X11Class, MacClass, DirectFBClass,
OpenGLClass, OpenVGClass, RuntimeClass, BlitterClass,
CustomClass = 1024
}
enum PixelType { PixmapType, BitmapType }
Static Public Functions inherited from QPixmapData
static QPixmapData * create (int w, int h, PixelType type)
Protected Functions inherited from QPixmapData
void setSerialNumber (int serNo)
Detailed Description
Definition at line 51 of file qpixmap_blitter_p.h.
Constructors and Destructors
QBlittablePixmapData()
QBlittablePixmapData::QBlittablePixmapData ()
Definition at line 59 of file qpixmap_blitter.cpp.
     : QPixmapData(QPixmapData::PixmapType,BlitterClass)
     , m_alpha(false)
 #ifdef QT_BLITTER_RASTEROVERLAY
     ,m_rasterOverlay(0), m_unmergedCopy(0)
 #endif //QT_BLITTER_RASTEROVERLAY
 {
     setSerialNumber(++global_ser_no);
 }
~QBlittablePixmapData()
QBlittablePixmapData::~QBlittablePixmapData ()
Definition at line 69 of file qpixmap_blitter.cpp.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
     delete m_rasterOverlay;
     delete m_unmergedCopy;
 #endif //QT_BLITTER_RASTEROVERLAY
 }
Functions
blittable()
QBlittable * QBlittablePixmapData::blittable () const
Definition at line 77 of file qpixmap_blitter.cpp.
Referenced by buffer(), QDirectFbConvenience::dfbSurfaceForPlatformPixmap(), QDirectFbBlitter::drawPixmapOpacity(), fill(), QDirectFbWindowSurface::flush(), hasAlphaChannel(), QDirectFbWindowSurface::scroll(), and toImage().
 {
     if (!m_blittable) {
         QBlittablePixmapData *that = const_cast<QBlittablePixmapData *>(this);
         that->m_blittable.reset(this->createBlittable(QSize(w,h), m_alpha));
     }
     return m_blittable.data();
 }
buffer()
QImage * QBlittablePixmapData::buffer () virtual
Reimplemented from QPixmapData.
Definition at line 179 of file qpixmap_blitter.cpp.
Referenced by fromImage(), and paintEngine().
 {
     return blittable()->lock();
 }
createBlittable()
virtual QBlittable* QBlittablePixmapData::createBlittable (const QSize & size, bool alpha) const pure virtual
Implemented in QDirectFbBlitterPlatformPixmap.
Referenced by blittable().
fill()
void QBlittablePixmapData::fill (const QColor & color) virtual
Implements QPixmapData.
Definition at line 134 of file qpixmap_blitter.cpp.
 {
     if (blittable()->capabilities() & QBlittable::AlphaFillRectCapability) {
         blittable()->unlock();
         blittable()->alphaFillRect(QRectF(0,0,w,h),color,QPainter::CompositionMode_Source);
     } else if (color.alpha() == 255 && blittable()->capabilities() & QBlittable::SolidRectCapability) {
         blittable()->unlock();
         blittable()->fillRect(QRectF(0,0,w,h),color);
     } else {
         // Need to be backed with an alpha channel now. It would be nice
         // if we could just change the format, e.g. when going from
         // RGB32 -> ARGB8888.
         if (color.alpha() != 255 && !hasAlphaChannel()) {
             m_blittable.reset(0);
             m_engine.reset(0);
             m_alpha = true;
         }
         uint pixel;
         switch (blittable()->lock()->format()) {
         case QImage::Format_ARGB32_Premultiplied:
             pixel = PREMUL(color.rgba());
             break;
         case QImage::Format_ARGB8565_Premultiplied:
             pixel = qargb8565(color.rgba()).rawValue();
             break;
         case QImage::Format_ARGB8555_Premultiplied:
             pixel = qargb8555(color.rgba()).rawValue();
             break;
         case QImage::Format_ARGB6666_Premultiplied:
             pixel = qargb6666(color.rgba()).rawValue();
             break;
         case QImage::Format_ARGB4444_Premultiplied:
             pixel = qargb4444(color.rgba()).rawValue();
             break;
         default:
             pixel = color.rgba();
             break;
         }
         //so premultiplied formats are supported and ARGB32 and RGB32
         blittable()->lock()->fill(pixel);
     }
 }
fromImage()
void QBlittablePixmapData::fromImage (const QImage & image, Qt::ImageConversionFlags flags) virtual
Implements QPixmapData.
Definition at line 194 of file qpixmap_blitter.cpp.
 {
     m_alpha = image.hasAlphaChannel();
     resize(image.width(),image.height());
     markRasterOverlay(QRect(0,0,w,h));
     QImage *thisImg = buffer();
     QImage correctFormatPic = image;
     if (correctFormatPic.format() != thisImg->format())
         correctFormatPic = correctFormatPic.convertToFormat(thisImg->format(), flags);
     uchar *mem = thisImg->bits();
     const uchar *bits = correctFormatPic.bits();
     int bytesCopied = 0;
     while (bytesCopied < correctFormatPic.byteCount()) {
         memcpy(mem,bits,correctFormatPic.bytesPerLine());
         mem += thisImg->bytesPerLine();
         bits += correctFormatPic.bytesPerLine();
         bytesCopied+=correctFormatPic.bytesPerLine();
     }
 }
hasAlphaChannel()
bool QBlittablePixmapData::hasAlphaChannel () const virtual
Implements QPixmapData.
Definition at line 189 of file qpixmap_blitter.cpp.
Referenced by fill().
 {
     return blittable()->lock()->hasAlphaChannel();
 }
markRasterOverlay() [1/8]
void QBlittablePixmapData::markRasterOverlay (const QRectF & rect) inline
Definition at line 105 of file qpixmap_blitter_p.h.
Referenced by fromImage().
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
     markRasterOverlayImpl(rect);
 #else
    Q_UNUSED(rect)
 #endif
 }
markRasterOverlay() [2/8]
void QBlittablePixmapData::markRasterOverlay (const QPointF & pos, const QTextItem & ti) inline
Definition at line 123 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
     QFontMetricsF fm(ti.font());
     QRectF rect = fm.tightBoundingRect(ti.text());
     rect.moveBottomLeft(pos);
     markRasterOverlay(rect);
 #else
     Q_UNUSED(pos)
     Q_UNUSED(ti)
 #endif
 }
markRasterOverlay() [3/8]
void QBlittablePixmapData::markRasterOverlay (const QVectorPath & path) inline
Definition at line 114 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
     markRasterOverlayImpl(path.convertToPainterPath().boundingRect());
 #else
     Q_UNUSED(path)
 #endif
 }
markRasterOverlay() [4/8]
void QBlittablePixmapData::markRasterOverlay (const QPainterPath & path) inline
Definition at line 179 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
 #error "not ported yet"
 #else
     Q_UNUSED(path);
 #endif
 }
markRasterOverlay() [5/8]
void QBlittablePixmapData::markRasterOverlay (const QRect * rects, int rectCount) inline
Definition at line 136 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
     for (int i = 0; i < rectCount; i++) {
         markRasterOverlay(rects[i]);
     }
 #else
     Q_UNUSED(rects)
     Q_UNUSED(rectCount)
 #endif
 }
markRasterOverlay() [6/8]
void QBlittablePixmapData::markRasterOverlay (const QRectF * rects, int rectCount) inline
Definition at line 147 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
     for (int i = 0; i < rectCount; i++) {
         markRasterOverlay(rects[i]);
     }
 #else
     Q_UNUSED(rects)
     Q_UNUSED(rectCount)
 #endif
 }
markRasterOverlay() [7/8]
void QBlittablePixmapData::markRasterOverlay (const QPointF * points, int pointCount) inline
Definition at line 159 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
 #error "not ported yet"
 #else
     Q_UNUSED(points);
     Q_UNUSED(pointCount);
 #endif
 }
markRasterOverlay() [8/8]
void QBlittablePixmapData::markRasterOverlay (const QPoint * points, int pointCount) inline
Definition at line 169 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
 #error "not ported yet"
 #else
     Q_UNUSED(points);
     Q_UNUSED(pointCount);
 #endif
 }
metric()
int QBlittablePixmapData::metric (QPaintDevice::PaintDeviceMetric metric) const virtual
Implements QPixmapData.
Definition at line 107 of file qpixmap_blitter.cpp.
 {
     switch (metric) {
     case QPaintDevice::PdmWidth:
         return w;
     case QPaintDevice::PdmHeight:
         return h;
     case QPaintDevice::PdmWidthMM:
         return qRound(w * 25.4 / qt_defaultDpiX());
     case QPaintDevice::PdmHeightMM:
         return qRound(h * 25.4 / qt_defaultDpiY());
     case QPaintDevice::PdmDepth:
         return 32;
     case QPaintDevice::PdmDpiX: // fall-through
     case QPaintDevice::PdmPhysicalDpiX:
         return qt_defaultDpiX();
     case QPaintDevice::PdmDpiY: // fall-through
     case QPaintDevice::PdmPhysicalDpiY:
         return qt_defaultDpiY();
     default:
         qWarning("QRasterPixmapData::metric(): Unhandled metric type %d", metric);
         break;
     }
     return 0;
 }
paintEngine()
QPaintEngine * QBlittablePixmapData::paintEngine () const virtual
Implements QPixmapData.
Definition at line 217 of file qpixmap_blitter.cpp.
 {
     if (!m_engine) {
         QBlittablePixmapData *that = const_cast<QBlittablePixmapData *>(this);
         that->m_engine.reset(new QBlitterPaintEngine(that));
     }
     return m_engine.data();
 }
resize()
void QBlittablePixmapData::resize (int width, int height) virtual
Implements QPixmapData.
Definition at line 93 of file qpixmap_blitter.cpp.
Referenced by fromImage(), and setBlittable().
 {
     m_blittable.reset(0);
     m_engine.reset(0);
 #ifdef Q_WS_QPA
     d = QApplicationPrivate::platformIntegration()->screens().at(0)->depth();
 #endif
     w = width;
     h = height;
     is_null = (w <= 0 || h <= 0);
     setSerialNumber(++global_ser_no);
 }
setBlittable()
void QBlittablePixmapData::setBlittable (QBlittable * blittable)
Definition at line 87 of file qpixmap_blitter.cpp.
Referenced by QDirectFbWindowSurface::resize().
 {
     resize(blittable->size().width(),blittable->size().height());
     m_blittable.reset(blittable);
 }
toImage()
QImage QBlittablePixmapData::toImage () const virtual
Implements QPixmapData.
Definition at line 184 of file qpixmap_blitter.cpp.
 {
     return blittable()->lock()->copy();
 }
unmarkRasterOverlay()
void QBlittablePixmapData::unmarkRasterOverlay (const QRectF & rect) inline
Definition at line 188 of file qpixmap_blitter_p.h.
 {
 #ifdef QT_BLITTER_RASTEROVERLAY
     unmarkRasterOverlayImpl(rect);
 #else
     Q_UNUSED(rect)
 #endif
 }
Properties
m_alpha
bool QBlittablePixmapData::m_alpha protected
Definition at line 91 of file qpixmap_blitter_p.h.
Referenced by blittable(), fill(), and fromImage().
m_blittable
QScopedPointer<QBlittable> QBlittablePixmapData::m_blittable protected
Definition at line 90 of file qpixmap_blitter_p.h.
Referenced by blittable(), fill(), resize(), and setBlittable().
m_engine
QScopedPointer<QBlitterPaintEngine> QBlittablePixmapData::m_engine protected
Definition at line 89 of file qpixmap_blitter_p.h.
Referenced by fill(), paintEngine(), and resize().
The documentation for this class was generated from the following files:
/src/gui/image/qpixmap_blitter_p.h
/src/gui/image/qpixmap_blitter.cpp