Qt 4.8: QFontDatabase Class Reference
QFontDatabase Class Reference
The QFontDatabase class provides information about the fonts available in the underlying window system.
#include <qfontdatabase.h>
Public Types
enum WritingSystem {
Any, Latin, Greek, Cyrillic,
Armenian, Hebrew, Arabic, Syriac,
Thaana, Devanagari, Bengali, Gurmukhi,
Gujarati, Oriya, Tamil, Telugu,
Kannada, Malayalam, Sinhala, Thai,
Lao, Tibetan, Myanmar, Georgian,
Khmer, SimplifiedChinese, TraditionalChinese, Japanese,
Korean, Vietnamese, Symbol, Other = Symbol,
Ogham, Runic, Nko, WritingSystemsCount
}
Public Functions
bool bold (const QString &family, const QString &style) const
Returns true if the font that has family family and style style is bold; otherwise returns false.
QStringList families (WritingSystem writingSystem=Any) const
Returns a sorted list of the available font families which support the writingSystem.
QFont font (const QString &family, const QString &style, int pointSize) const
Returns a QFont object that has family family, style style and point size pointSize.
bool hasFamily (const QString &family) const
bool isBitmapScalable (const QString &family, const QString &style=QString()) const
Returns true if the font that has family family and style style is a scalable bitmap font; otherwise returns false.
bool isFixedPitch (const QString &family, const QString &style=QString()) const
Returns true if the font that has family family and style style is fixed pitch; otherwise returns false.
bool isScalable (const QString &family, const QString &style=QString()) const
Returns true if the font that has family family and style style is scalable; otherwise returns false.
bool isSmoothlyScalable (const QString &family, const QString &style=QString()) const
Returns true if the font that has family family and style style is smoothly scalable; otherwise returns false.
bool italic (const QString &family, const QString &style) const
Returns true if the font that has family family and style style is italic; otherwise returns false.
QList< int > pointSizes (const QString &family, const QString &style=QString())
Returns a list of the point sizes available for the font with the given family and style.
QFontDatabase ()
Creates a font database object.
QList< int > smoothSizes (const QString &family, const QString &style)
Returns the point sizes of a font with the given family and style that will look attractive.
QStringList styles (const QString &family) const
Returns a list of the styles available for the font family family.
QString styleString (const QFont &font)
Returns a string that describes the style of the font.
QString styleString (const QFontInfo &fontInfo)
Returns a string that describes the style of the fontInfo.
int weight (const QString &family, const QString &style) const
Returns the weight of the font that has family family and style style.
QList< WritingSystem > writingSystems () const
Returns a sorted list of the available writing systems.
QList< WritingSystem > writingSystems (const QString &family) const
Returns a sorted list of the writing systems supported by a given font family.
Static Public Functions
static int addApplicationFont (const QString &fileName)
Loads the font from the file specified by fileName and makes it available to the application.
static int addApplicationFontFromData (const QByteArray &fontData)
Loads the font from binary data specified by fontData and makes it available to the application.
static QStringList applicationFontFamilies (int id)
Returns a list of font families for the given application font identified by id.
static bool removeAllApplicationFonts ()
Removes all application-local fonts previously added using addApplicationFont() and addApplicationFontFromData().
static bool removeApplicationFont (int id)
Removes the previously loaded application font identified by id.
static QList< int > standardSizes ()
Returns a list of standard font sizes.
static bool supportsThreadedFontRendering ()
Returns true if font rendering is supported outside the GUI thread, false otherwise.
static QString writingSystemName (WritingSystem writingSystem)
Returns the names the writingSystem (e.g.
static QString writingSystemSample (WritingSystem writingSystem)
Returns a string with sample characters from writingSystem.
Static Private Functions
static void createDatabase ()
static QFontEngine * findFont (int script, const QFontPrivate *fp, const QFontDef &request)
static void load (const QFontPrivate *d, int script)
Loads a QFontEngine for the specified script that matches the QFontDef request member variable.
static QFontEngine * loadXlfd (int screen, int script, const QFontDef &request, int force_encoding_id=-1)
static void parseFontName (const QString &name, QString &foundry, QString &family)
static QString resolveFontFamilyAlias (const QString &family)
Properties
QFontDatabasePrivate * d
Friends
struct QFontDef
class QFontDialog
class QFontDialogPrivate
class QFontEngineMultiQPA
class QFontEngineMultiQWS
class QFontEngineMultiS60
class QFontEngineMultiXLFD
class QFontPrivate
Detailed Description
The QFontDatabase class provides information about the fonts available in the underlying window system.
Note
This class or function is threadsafe.
The most common uses of this class are to query the database for the list of font families() and for the pointSizes() and styles() that are available for each family. An alternative to pointSizes() is smoothSizes() which returns the sizes at which a given family and style will look attractive.
If the font family is available from two or more foundries the foundry name is included in the family name; for example: "Helvetica [Adobe]" and "Helvetica [Cronyx]". When you specify a family, you can either use the old hyphenated "foundry-family" format or the bracketed "family [foundry]" format; for example: "Cronyx-Helvetica" or "Helvetica [Cronyx]". If the family has a foundry it is always returned using the bracketed format, as is the case with the value returned by families().
The font() function returns a QFont given a family, style and point size.
A family and style combination can be checked to see if it is italic() or bold(), and to retrieve its weight(). Similarly we can call isBitmapScalable(), isSmoothlyScalable(), isScalable() and isFixedPitch().
Use the styleString() to obtain a text version of a style.
The QFontDatabase class also supports some static functions, for example, standardSizes(). You can retrieve the description of a writing system using writingSystemName(), and a sample of characters in a writing system with writingSystemSample().
Example:
    QFontDatabase database;
    QTreeWidget fontTree;
    fontTree.setColumnCount(2);
    fontTree.setHeaderLabels(QStringList() << "Font" << "Smooth Sizes");
    foreach (const QString &family, database.families()) {
        QTreeWidgetItem *familyItem = new QTreeWidgetItem(&fontTree);
        familyItem->setText(0, family);
        foreach (const QString &style, database.styles(family)) {
            QTreeWidgetItem *styleItem = new QTreeWidgetItem(familyItem);
            styleItem->setText(0, style);
            QString sizes;
            foreach (int points, database.smoothSizes(family, style))
                sizes += QString::number(points) + " ";
            styleItem->setText(1, sizes.trimmed());
        }
    }
This example gets the list of font families, the list of styles for each family, and the point sizes that are available for each combination of family and style, displaying this information in a tree view.
See also
QFont, QFontInfo, QFontMetrics, QFontComboBox, {Character Map Example}
Definition at line 66 of file qfontdatabase.h.
Enumerations
WritingSystem
enum QFontDatabase::WritingSystem
Any
Latin
Greek
Cyrillic
Armenian
Hebrew
Arabic
Syriac
Thaana
Devanagari
Bengali
Gurmukhi
Gujarati
Oriya
Tamil
Telugu
Kannada
Malayalam
Sinhala
Thai
Lao
Tibetan
Myanmar
Georgian
Khmer
SimplifiedChinese
TraditionalChinese
Japanese
Korean
Vietnamese
Symbol
Other (the same as Symbol)
Ogham
Runic
Nko
WritingSystemsCount
Enumerator
Any
Latin
Greek
Cyrillic
Armenian
Hebrew
Arabic
Syriac
Thaana
Devanagari
Bengali
Gurmukhi
Gujarati
Oriya
Tamil
Telugu
Kannada
Malayalam
Sinhala
Thai
Lao
Tibetan
Myanmar
Georgian
Khmer
SimplifiedChinese
TraditionalChinese
Japanese
Korean
Vietnamese
Symbol
Other
Ogham
Runic
Nko
WritingSystemsCount
Definition at line 73 of file qfontdatabase.h.
{
         Any,
         Latin,
         Greek,
         Cyrillic,
         Armenian,
         Hebrew,
         Arabic,
         Syriac,
         Thaana,
         Devanagari,
         Bengali,
         Gurmukhi,
         Gujarati,
         Oriya,
         Tamil,
         Telugu,
         Kannada,
         Malayalam,
         Sinhala,
         Thai,
         Lao,
         Tibetan,
         Myanmar,
         Georgian,
         Khmer,
         SimplifiedChinese,
         TraditionalChinese,
         Japanese,
         Korean,
         Vietnamese,
         Symbol,
         Other = Symbol,
         Ogham,
         Runic,
         Nko,
         WritingSystemsCount
     };
Constructors and Destructors
QFontDatabase()
QFontDatabase::QFontDatabase ()
Creates a font database object.
Definition at line 1606 of file qfontdatabase.cpp.
 {
     QMutexLocker locker(fontDatabaseMutex());
     createDatabase();
     d = privateDb();
 }
Functions
addApplicationFont()
int QFontDatabase::addApplicationFont (const QString & fileName) static
Loads the font from the file specified by fileName and makes it available to the application.
Since
4.2
An ID is returned that can be used to remove the font again with removeApplicationFont() or to retrieve the list of family names contained in the font.
The function returns -1 if the font could not be loaded.
Currently only TrueType fonts, TrueType font collections, and OpenType fonts are supported.
Note
Adding application fonts on Unix/X11 platforms without fontconfig is currently not supported.
On Symbian, the font family names get truncated to a length of 20 characters.
See also
addApplicationFontFromData(), applicationFontFamilies(), removeApplicationFont()
Definition at line 2659 of file qfontdatabase.cpp.
Referenced by QDeclarativeFontLoader::setSource().
 {
     QByteArray data;
     QFile f(fileName);
     if (!(f.fileEngine()->fileFlags(QAbstractFileEngine::FlagsMask) & QAbstractFileEngine::LocalDiskFlag)) {
         if (!f.open(QIODevice::ReadOnly))
             return -1;
         data = f.readAll();
     }
     QMutexLocker locker(fontDatabaseMutex());
     return privateDb()->addAppFont(data, fileName);
 }
addApplicationFontFromData()
int QFontDatabase::addApplicationFontFromData (const QByteArray & fontData) static
Loads the font from binary data specified by fontData and makes it available to the application.
Since
4.2
An ID is returned that can be used to remove the font again with removeApplicationFont() or to retrieve the list of family names contained in the font.
The function returns -1 if the font could not be loaded.
Currently only TrueType fonts and TrueType font collections are supported.
Note: Adding application fonts on Unix/X11 platforms without fontconfig is currently not supported.
Note
On Symbian, the font family names get truncated to a length of 20 characters.
See also
addApplicationFont(), applicationFontFamilies(), removeApplicationFont()
Definition at line 2694 of file qfontdatabase.cpp.
Referenced by QDeclarativeFontObject::replyFinished().
 {
     QMutexLocker locker(fontDatabaseMutex());
     return privateDb()->addAppFont(fontData, QString() /* fileName */);
 }
applicationFontFamilies()
QStringList QFontDatabase::applicationFontFamilies (int id) static
Returns a list of font families for the given application font identified by id.
Since
4.2
See also
addApplicationFont(), addApplicationFontFromData()
Definition at line 2711 of file qfontdatabase.cpp.
Referenced by QDeclarativeFontObject::replyFinished(), and QDeclarativeFontLoader::setSource().
 {
     QMutexLocker locker(fontDatabaseMutex());
     return privateDb()->applicationFonts.value(id).families;
 }
bold()
bool QFontDatabase::bold (const QString & family, const QString & style) const
Returns true if the font that has family family and style style is bold; otherwise returns false.
See also
italic(), weight()
Definition at line 2172 of file qfontdatabase.cpp.
 {
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontFoundry allStyles(foundryName);
     QtFontFamily *f = d->family(familyName);
     if (!f) return false;
     for (int j = 0; j < f->count; j++) {
         QtFontFoundry *foundry = f->foundries[j];
         if (foundryName.isEmpty() ||
             foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             for (int k = 0; k < foundry->count; k++)
                 allStyles.style(foundry->styles[k]->key, foundry->styles[k]->styleName, true);
         }
     }
     QtFontStyle::Key styleKey(style);
     QtFontStyle *s = allStyles.style(styleKey, style);
     return s && s->key.weight >= QFont::Bold;
 }
createDatabase()
void QFontDatabase::createDatabase () static private
Definition at line 2590 of file qfontdatabase.cpp.
 { initializeDb(); }
families()
QStringList QFontDatabase::families (WritingSystem writingSystem = Any) const
Returns a sorted list of the available font families which support the writingSystem.
If a family exists in several foundries, the returned name for that font is in the form "family [foundry]". Examples: "Times [Adobe]", "Times [Cronyx]", "Palatino".
See also
writingSystems()
Definition at line 1731 of file qfontdatabase.cpp.
Referenced by QFontComboBoxPrivate::_q_updateModel(), QDeclarativeEnginePrivate::fontFamilies(), and loadEngine().
 {
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)();
 #ifdef Q_WS_X11
     if (writingSystem != Any)
         checkSymbolFonts();
 #endif
     QStringList flist;
     for (int i = 0; i < d->count; i++) {
         QtFontFamily *f = d->families[i];
         if (f->count == 0)
             continue;
         if (writingSystem != Any && (f->writingSystems[writingSystem] != QtFontFamily::Supported))
             continue;
         if (f->count == 1) {
             flist.append(f->name);
         } else {
             for (int j = 0; j < f->count; j++) {
                 QString str = f->name;
                 QString foundry = f->foundries[j]->name;
                 if (!foundry.isEmpty()) {
                     str += QLatin1String(" [");
                     str += foundry;
                     str += QLatin1Char(']');
                 }
                 flist.append(str);
             }
         }
     }
     return flist;
 }
findFont()
QFontEngine * QFontDatabase::findFont (int script, const QFontPrivate * fp, const QFontDef & request) static private
Warning
This function is not part of the public interface.
Definition at line 255 of file qfontdatabase_qpa.cpp.
Referenced by QFontEngineMultiQPA::loadEngine(), QFontEngineMultiQWS::loadEngine(), and registerFont().
 {
     QMutexLocker locker(fontDatabaseMutex());
     const int force_encoding_id = -1;
     if (!privateDb()->count)
         initializeDb();
     QFontEngine *engine;
     QFontCache::Key key(request, script);
     engine = QFontCache::instance()->findEngine(key);
     if (engine) {
         qDebug() << "Cache hit level 1";
         return engine;
     }
     QString family_name, foundry_name;
     parseFontName(request.family, foundry_name, family_name);
     if (qt_enable_test_font && request.family == QLatin1String("__Qt__Box__Engine__")) {
         engine =new QTestFontEngine(request.pixelSize);
         engine->fontDef = request;
     }
     QtFontDesc desc;
     match(script, request, family_name, foundry_name, force_encoding_id, &desc);
     if (desc.family != 0 && desc.foundry != 0 && desc.style != 0) {
         engine = loadEngine(script, request, desc.family, desc.foundry, desc.style, desc.size);
     } else {
         FM_DEBUG("  NO MATCH FOUND\n");
     }
     if (engine) {
         initFontDef(desc, request, &engine->fontDef);
         if (fp) {
             QFontDef def = request;
             if (def.family.isEmpty()) {
                 def.family = fp->request.family;
                 def.family = def.family.left(def.family.indexOf(QLatin1Char(',')));
             }
         }
     }
     if (!engine) {
         if (!request.family.isEmpty()) {
             QStringList fallbacks = fallbackFamilies(request.family,QFont::Style(request.style),QFont::StyleHint(request.styleHint),QUnicodeTables::Script(script));
             for (int i = 0; i < fallbacks.size(); i++) {
                 QFontDef def = request;
                 def.family = fallbacks.at(i);
                 QFontCache::Key key(def,script);
                 engine = QFontCache::instance()->findEngine(key);
                 if (!engine) {
                     QtFontDesc desc;
                     match(script, def, def.family, QLatin1String(""), 0, &desc);
                     if (desc.family == 0 && desc.foundry == 0 && desc.style == 0) {
                         continue;
                     }
                     engine = loadEngine(script, def, desc.family, desc.foundry, desc.style, desc.size);
                     if (engine) {
                         initFontDef(desc, def, &engine->fontDef);
                         break;
                     }
                 }
             }
         }
         if (!engine)
             engine = new QFontEngineBox(request.pixelSize);
         FM_DEBUG("returning box engine");
     }
     if (fp && fp->dpi > 0) {
         engine->fontDef.pointSize = qreal(double((engine->fontDef.pixelSize * 72) / fp->dpi));
     } else {
         engine->fontDef.pointSize = request.pointSize;
     }
     return engine;
 }
font()
QFont QFontDatabase::font (const QString & family, const QString & style, int pointSize) const
Returns a QFont object that has family family, style style and point size pointSize.
If no matching font could be created, a QFont object that uses the application's default font is returned.
Definition at line 2008 of file qfontdatabase.cpp.
Referenced by getFamiliesAndSignatures(), qfontForCocoaFont(), registerFont(), and resolveFontFamilyAlias().
 {
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontFoundry allStyles(foundryName);
     QtFontFamily *f = d->family(familyName);
     if (!f) return QApplication::font();
     for (int j = 0; j < f->count; j++) {
         QtFontFoundry *foundry = f->foundries[j];
         if (foundryName.isEmpty() || foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             for (int k = 0; k < foundry->count; k++)
                 allStyles.style(foundry->styles[k]->key, foundry->styles[k]->styleName, true);
         }
     }
     QtFontStyle::Key styleKey(style);
     QtFontStyle *s = bestStyle(&allStyles, styleKey, style);
     if (!s) // no styles found?
         return QApplication::font();
     QFont fnt(family, pointSize, s->key.weight);
     fnt.setStyle((QFont::Style)s->key.style);
     if (!s->styleName.isEmpty())
         fnt.setStyleName(s->styleName);
     return fnt;
 }
hasFamily()
bool QFontDatabase::hasFamily (const QString & family) const
Warning
This function is not part of the public interface.
Definition at line 2238 of file qfontdatabase.cpp.
 {
     QString parsedFamily, foundry;
     parseFontName(family, foundry, parsedFamily);
     const QString familyAlias = resolveFontFamilyAlias(parsedFamily);
     return families().contains(familyAlias, Qt::CaseInsensitive);
 }
isBitmapScalable()
bool QFontDatabase::isBitmapScalable (const QString & family, const QString & style = QString()) const
Returns true if the font that has family family and style style is a scalable bitmap font; otherwise returns false.
Scaling a bitmap font usually produces an unattractive hardly readable result, because the pixels of the font are scaled. If you need to scale a bitmap font it is better to scale it to one of the fixed sizes returned by smoothSizes().
See also
isScalable(), isSmoothlyScalable()
Definition at line 1842 of file qfontdatabase.cpp.
 {
     bool bitmapScalable = false;
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontStyle::Key styleKey(style);
     QtFontFamily *f = d->family(familyName);
     if (!f) return bitmapScalable;
     for (int j = 0; j < f->count; j++) {
         QtFontFoundry *foundry = f->foundries[j];
         if (foundryName.isEmpty() || foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             for (int k = 0; k < foundry->count; k++)
                 if ((style.isEmpty() ||
                      foundry->styles[k]->styleName == style ||
                      foundry->styles[k]->key == styleKey)
                     && foundry->styles[k]->bitmapScalable && !foundry->styles[k]->smoothScalable) {
                     bitmapScalable = true;
                     goto end;
                 }
         }
     }
  end:
     return bitmapScalable;
 }
isFixedPitch()
bool QFontDatabase::isFixedPitch (const QString & family, const QString & style = QString()) const
Returns true if the font that has family family and style style is fixed pitch; otherwise returns false.
Definition at line 1813 of file qfontdatabase.cpp.
Referenced by QFontComboBoxPrivate::_q_updateModel().
 {
     Q_UNUSED(style);
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontFamily *f = d->family(familyName);
 #if !defined(QWS) && defined(Q_OS_MAC)
     qt_mac_get_fixed_pitch(f);
 #endif
     return (f && f->fixedPitch);
 }
isScalable()
bool QFontDatabase::isScalable (const QString & family, const QString & style = QString()) const
Returns true if the font that has family family and style style is scalable; otherwise returns false.
See also
isBitmapScalable(), isSmoothlyScalable()
Definition at line 1921 of file qfontdatabase.cpp.
 {
     QMutexLocker locker(fontDatabaseMutex());
     if (isSmoothlyScalable(family, style))
         return true;
     return isBitmapScalable(family, style);
 }
isSmoothlyScalable()
bool QFontDatabase::isSmoothlyScalable (const QString & family, const QString & style = QString()) const
Returns true if the font that has family family and style style is smoothly scalable; otherwise returns false.
If this function returns true, it's safe to scale this font to any size, and the result will always look attractive.
See also
isScalable(), isBitmapScalable()
Definition at line 1884 of file qfontdatabase.cpp.
Referenced by QFontComboBoxPrivate::_q_updateModel(), and QFontFamilyDelegate::paint().
 {
     bool smoothScalable = false;
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontStyle::Key styleKey(style);
     QtFontFamily *f = d->family(familyName);
     if (!f) return smoothScalable;
     for (int j = 0; j < f->count; j++) {
         QtFontFoundry *foundry = f->foundries[j];
         if (foundryName.isEmpty() || foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             for (int k = 0; k < foundry->count; k++)
                 if ((style.isEmpty() ||
                      foundry->styles[k]->styleName == style ||
                      foundry->styles[k]->key == styleKey) && foundry->styles[k]->smoothScalable) {
                     smoothScalable = true;
                     goto end;
                 }
         }
     }
  end:
     return smoothScalable;
 }
italic()
bool QFontDatabase::italic (const QString & family, const QString & style) const
Returns true if the font that has family family and style style is italic; otherwise returns false.
See also
weight(), bold()
Definition at line 2139 of file qfontdatabase.cpp.
 {
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontFoundry allStyles(foundryName);
     QtFontFamily *f = d->family(familyName);
     if (!f) return false;
     for (int j = 0; j < f->count; j++) {
         QtFontFoundry *foundry = f->foundries[j];
         if (foundryName.isEmpty() || foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             for (int k = 0; k < foundry->count; k++)
                 allStyles.style(foundry->styles[k]->key, foundry->styles[k]->styleName, true);
         }
     }
     QtFontStyle::Key styleKey(style);
     QtFontStyle *s = allStyles.style(styleKey, style);
     return s && s->key.style == QFont::StyleItalic;
 }
load()
void QFontDatabase::load (const QFontPrivate * d, int script) static private
Loads a QFontEngine for the specified script that matches the QFontDef request member variable.
Warning
This function is not part of the public interface.
Definition at line 366 of file qfontdatabase_mac.cpp.
Referenced by QFontPrivate::engineForScript(), findFont(), loadWin(), loadXlfd(), and registerFont().
 {
     // sanity checks
     if(!qApp)
         qWarning("QFont: Must construct a QApplication before a QFont");
     Q_ASSERT(script >= 0 && script < QUnicodeTables::ScriptCount);
     Q_UNUSED(script);
     QFontDef req = d->request;
     req.pixelSize = qt_mac_pixelsize(req, d->dpi);
     // set the point size to 0 to get better caching
     req.pointSize = 0;
     QFontCache::Key key = QFontCache::Key(req, QUnicodeTables::Common, d->screen);
     if(!(d->engineData = QFontCache::instance()->findEngineData(key))) {
         d->engineData = new QFontEngineData;
         QFontCache::instance()->insertEngineData(key, d->engineData);
     } else {
         d->engineData->ref.ref();
     }
     if(d->engineData->engine) // already loaded
         return;
     // set it to the actual pointsize, so QFontInfo will do the right thing
     req.pointSize = qRound(qt_mac_pointsize(d->request, d->dpi));
     QFontEngine *e = QFontCache::instance()->findEngine(key);
     if(!e && qt_enable_test_font && req.family == QLatin1String("__Qt__Box__Engine__")) {
         e = new QTestFontEngine(req.pixelSize);
         e->fontDef = req;
     }
     if(e) {
         e->ref.ref();
         d->engineData->engine = e;
         return; // the font info and fontdef should already be filled
     }
     QFontEngine *engine = NULL;
 #if defined(QT_MAC_USE_COCOA)
     // Shortcut to get the font directly without going through the font database
     if (!req.family.isEmpty() && !req.styleName.isEmpty()) {
         QCFString expectedFamily = QCFString(req.family);
         QCFString expectedStyle = QCFString(req.styleName);
         QCFType<CFMutableDictionaryRef> attributes = CFDictionaryCreateMutable(NULL, 0,
             &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
         CFDictionaryAddValue(attributes, kCTFontFamilyNameAttribute, expectedFamily);
         CFDictionaryAddValue(attributes, kCTFontStyleNameAttribute, expectedStyle);
         QCFType<CTFontDescriptorRef> descriptor = CTFontDescriptorCreateWithAttributes(attributes);
         CGAffineTransform transform = qt_transform_from_fontdef(req);
         QCFType<CTFontRef> ctFont = CTFontCreateWithFontDescriptor(descriptor, req.pixelSize, &transform);
         if (ctFont) {
             QCFString familyName = CTFontCopyFamilyName(ctFont);
             // Only accept the font if the family name is exactly the same as we specified
             if (CFEqual(expectedFamily, familyName)) {
                 engine = new QCoreTextFontEngineMulti(ctFont, req, d->kerning);
             }
         }
     }
 #endif
     if (!engine)
         engine = loadFromDatabase(req, d);
     if (engine) {
         d->engineData->engine = engine;
         engine->ref.ref();
         QFontCache::instance()->insertEngine(key, engine);
     }
 }
loadXlfd()
QFontEngine * QFontDatabase::loadXlfd (int screen, int script, const QFontDef & request, int force_encoding_id = -1) static private
Definition at line 1797 of file qfontdatabase_x11.cpp.
Referenced by QFontEngineMultiXLFD::loadEngine().
 {
     QMutexLocker locker(fontDatabaseMutex());
     QtFontDesc desc;
     FM_DEBUG() << "---> loadXlfd: request is" << request.family;
     QStringList families_and_foundries = familyList(request);
     const char *stylehint = styleHint(request);
     if (stylehint)
         families_and_foundries << QString::fromLatin1(stylehint);
     families_and_foundries << QString();
     FM_DEBUG() << "loadXlfd: list is" << families_and_foundries;
     for (int i = 0; i < families_and_foundries.size(); ++i) {
         QString family, foundry;
         QT_PREPEND_NAMESPACE(parseFontName)(families_and_foundries.at(i), foundry, family);
         FM_DEBUG("loadXlfd: >>>>>>>>>>>>>>trying to match '%s' encoding=%d", family.toLatin1().data(), force_encoding_id);
         QT_PREPEND_NAMESPACE(match)(script, request, family, foundry, force_encoding_id, &desc, QList<int>(), true);
         if (desc.family)
             break;
     }
     QFontEngine *fe = 0;
     if (force_encoding_id != -1
         || (request.styleStrategy & QFont::NoFontMerging)
         || (desc.family && desc.family->writingSystems[QFontDatabase::Symbol] & QtFontFamily::Supported)) {
         if (desc.family) {
             int px = desc.size->pixelSize;
             if (desc.style->smoothScalable && px == SMOOTH_SCALABLE)
                 px = request.pixelSize;
             else if (desc.style->bitmapScalable && px == 0)
                 px = request.pixelSize;
             QByteArray xlfd("-");
             xlfd += desc.foundry->name.isEmpty() ? QByteArray("*") : desc.foundry->name.toLatin1();
             xlfd += '-';
             xlfd += desc.family->name.isEmpty() ? QByteArray("*") : desc.family->name.toLatin1();
             xlfd += '-';
             xlfd += desc.style->weightName ? desc.style->weightName : "*";
             xlfd += '-';
             xlfd += (desc.style->key.style == QFont::StyleItalic
                      ? 'i'
                      : (desc.style->key.style == QFont::StyleOblique ? 'o' : 'r'));
             xlfd += '-';
             xlfd += desc.style->setwidthName ? desc.style->setwidthName : "*";
             // ### handle add-style
             xlfd += "-*-";
             xlfd += QByteArray::number(px);
             xlfd += '-';
             xlfd += QByteArray::number(desc.encoding->xpoint);
             xlfd += '-';
             xlfd += QByteArray::number(desc.encoding->xres);
             xlfd += '-';
             xlfd += QByteArray::number(desc.encoding->yres);
             xlfd += '-';
             xlfd += desc.encoding->pitch;
             xlfd += '-';
             xlfd += QByteArray::number(desc.encoding->avgwidth);
             xlfd += '-';
             xlfd += xlfd_for_id(desc.encoding->encoding);
             FM_DEBUG("    using XLFD: %s\n", xlfd.data());
             const int mib = xlfd_encoding[desc.encoding->encoding].mib;
             XFontStruct *xfs;
             if ((xfs = XLoadQueryFont(QX11Info::display(), xlfd))) {
                 fe = new QFontEngineXLFD(xfs, xlfd, mib);
                 const int dpi = QX11Info::appDpiY();
                 if (!qt_fillFontDef(xfs, &fe->fontDef, dpi, &desc)
                     && !qt_fillFontDef(xlfd, &fe->fontDef, dpi, &desc)) {
                     initFontDef(desc, request, &fe->fontDef);
                 }
             }
         }
         if (!fe) {
             fe = new QFontEngineBox(request.pixelSize);
             fe->fontDef = QFontDef();
         }
     } else {
         QList<int> encodings;
         if (desc.encoding) {
             if (desc.encoding->encoding >= 0)
                 encodings.append(int(desc.encoding->encoding));
         }
         if (desc.size) {
             // append all other encodings for the matched font
             for (int i = 0; i < desc.size->count; ++i) {
                 QtFontEncoding *e = desc.size->encodings + i;
                 if (e == desc.encoding || e->encoding < 0)
                     continue;
                 encodings.append(int(e->encoding));
             }
         }
         // fill in the missing encodings
         const XlfdEncoding *enc = xlfd_encoding;
         for (; enc->name; ++enc) {
             if (!encodings.contains(enc->id) && enc->id >= 0) {
                 encodings.append(enc->id);
             }
         }
 #if defined(FONT_MATCH_DEBUG)
         FM_DEBUG("    using MultiXLFD, encodings:");
         for (int i = 0; i < encodings.size(); ++i) {
             const int id = encodings.at(i);
             FM_DEBUG("      %2d: %s", xlfd_encoding[id].id, xlfd_encoding[id].name);
         }
 #endif
         fe = new QFontEngineMultiXLFD(request, encodings, screen);
     }
     return fe;
 }
parseFontName()
void QFontDatabase::parseFontName (const QString & name, QString & foundry, QString & family) static private
Definition at line 2585 of file qfontdatabase.cpp.
Referenced by QFontDef::exactMatch(), findFont(), and QFontDialogPrivate::updateFamilies().
 {
     QT_PREPEND_NAMESPACE(parseFontName)(name, foundry, family);
 }
pointSizes()
QList< int > QFontDatabase::pointSizes (const QString & family, const QString & style = QString())
Returns a list of the point sizes available for the font with the given family and style.
The list may be empty.
See also
smoothSizes(), standardSizes()
Definition at line 1941 of file qfontdatabase.cpp.
 {
 #if defined(Q_WS_WIN)
     // windows and macosx are always smoothly scalable
     Q_UNUSED(family);
     Q_UNUSED(styleName);
     return standardSizes();
 #else
     bool smoothScalable = false;
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontStyle::Key styleKey(styleName);
     QList<int> sizes;
     QtFontFamily *fam = d->family(familyName);
     if (!fam) return sizes;
 #ifdef Q_WS_X11
     int dpi = QX11Info::appDpiY();
 #else
     const int dpi = qt_defaultDpiY(); // embedded
 #endif
     for (int j = 0; j < fam->count; j++) {
         QtFontFoundry *foundry = fam->foundries[j];
         if (foundryName.isEmpty() || foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             QtFontStyle *style = foundry->style(styleKey, styleName);
             if (!style) continue;
             if (style->smoothScalable) {
                 smoothScalable = true;
                 goto end;
             }
             for (int l = 0; l < style->count; l++) {
                 const QtFontSize *size = style->pixelSizes + l;
                 if (size->pixelSize != 0 && size->pixelSize != USHRT_MAX) {
                     const uint pointSize = qRound(size->pixelSize * qreal(72.0) / dpi);
                     if (! sizes.contains(pointSize))
                         sizes.append(pointSize);
                 }
             }
         }
     }
  end:
     if (smoothScalable)
         return standardSizes();
     qSort(sizes);
     return sizes;
 #endif
 }
removeAllApplicationFonts()
bool QFontDatabase::removeAllApplicationFonts () static
Removes all application-local fonts previously added using addApplicationFont() and addApplicationFontFromData().
Since
4.2
Returns true if unloading of the fonts succeeded; otherwise returns false.
See also
removeApplicationFont(), addApplicationFont(), addApplicationFontFromData()
Definition at line 530 of file qfontdatabase_mac.cpp.
Referenced by registerFont().
 {
     QMutexLocker locker(fontDatabaseMutex());
     QFontDatabasePrivate *db = privateDb();
     for(int i = 0; i < db->applicationFonts.count(); ++i) {
         if(!removeApplicationFont(i))
             return false;
     }
     return true;
 }
removeApplicationFont()
bool QFontDatabase::removeApplicationFont (int id) static
Removes the previously loaded application font identified by id.
Since
4.2
Returns true if unloading of the font succeeded; otherwise returns false.
See also
removeAllApplicationFonts(), addApplicationFont(), addApplicationFontFromData()
Definition at line 511 of file qfontdatabase_mac.cpp.
Referenced by registerFont(), and removeAllApplicationFonts().
 {
     QMutexLocker locker(fontDatabaseMutex());
     QFontDatabasePrivate *db = privateDb();
     if(handle < 0 || handle >= db->applicationFonts.count())
         return false;
     OSStatus e = ATSFontDeactivate(db->applicationFonts.at(handle).handle,
                                    /*iRefCon=*/0, kATSOptionFlagsDefault);
     if(e != noErr)
         return false;
     db->applicationFonts[handle] = QFontDatabasePrivate::ApplicationFont();
     db->invalidate();
     return true;
 }
resolveFontFamilyAlias()
QString QFontDatabase::resolveFontFamilyAlias (const QString & family) static private
Definition at line 547 of file qfontdatabase_mac.cpp.
Referenced by QFontDef::exactMatch(), qt_fontdatabase_mutex(), and registerFont().
 {
     QCFString expectedFamily = QCFString(family);
     QCFType<CFMutableDictionaryRef> attributes = CFDictionaryCreateMutable(NULL, 0,
         &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
     CFDictionaryAddValue(attributes, kCTFontFamilyNameAttribute, expectedFamily);
     QCFType<CTFontDescriptorRef> descriptor = CTFontDescriptorCreateWithAttributes(attributes);
     QCFType<CFMutableSetRef> mandatoryAttributes = CFSetCreateMutable(NULL, 0, &kCFTypeSetCallBacks);
     CFSetAddValue(mandatoryAttributes, kCTFontFamilyNameAttribute);
     QCFType<CTFontRef> font = CTFontCreateWithFontDescriptor(descriptor, 0.0, NULL);
     QCFType<CTFontDescriptorRef> matched = CTFontDescriptorCreateMatchingFontDescriptor(descriptor, mandatoryAttributes);
     if (!matched)
         return family;
     QCFString familyName = (CFStringRef) CTFontDescriptorCopyLocalizedAttribute(matched, kCTFontFamilyNameAttribute, NULL);
     return familyName;
 }
smoothSizes()
QList< int > QFontDatabase::smoothSizes (const QString & family, const QString & style)
Returns the point sizes of a font with the given family and style that will look attractive.
The list may be empty. For non-scalable fonts and bitmap scalable fonts, this function is equivalent to pointSizes().
See also
pointSizes(), standardSizes()
Definition at line 2056 of file qfontdatabase.cpp.
 {
 #ifdef Q_WS_WIN
     Q_UNUSED(family);
     Q_UNUSED(styleName);
     return QFontDatabase::standardSizes();
 #else
     bool smoothScalable = false;
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontStyle::Key styleKey(styleName);
     QList<int> sizes;
     QtFontFamily *fam = d->family(familyName);
     if (!fam)
         return sizes;
 #ifdef Q_WS_X11
     int dpi = QX11Info::appDpiY();
 #else
     const int dpi = qt_defaultDpiY(); // embedded
 #endif
     for (int j = 0; j < fam->count; j++) {
         QtFontFoundry *foundry = fam->foundries[j];
         if (foundryName.isEmpty() || foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             QtFontStyle *style = foundry->style(styleKey, styleName);
             if (!style) continue;
             if (style->smoothScalable) {
                 smoothScalable = true;
                 goto end;
             }
             for (int l = 0; l < style->count; l++) {
                 const QtFontSize *size = style->pixelSizes + l;
                 if (size->pixelSize != 0 && size->pixelSize != USHRT_MAX) {
                     const uint pointSize = qRound(size->pixelSize * qreal(72.0) / dpi);
                     if (! sizes.contains(pointSize))
                         sizes.append(pointSize);
                 }
             }
         }
     }
  end:
     if (smoothScalable)
         return QFontDatabase::standardSizes();
     qSort(sizes);
     return sizes;
 #endif
 }
standardSizes()
QList< int > QFontDatabase::standardSizes () static
Returns a list of standard font sizes.
See also
smoothSizes(), pointSizes()
Definition at line 2122 of file qfontdatabase.cpp.
Referenced by smoothSizes().
 {
     QList<int> ret;
     static const unsigned short standard[] =
         { 6, 7, 8, 9, 10, 11, 12, 14, 16, 18, 20, 22, 24, 26, 28, 36, 48, 72, 0 };
     const unsigned short *sizes = standard;
     while (*sizes) ret << *sizes++;
     return ret;
 }
styles()
QStringList QFontDatabase::styles (const QString & family) const
Returns a list of the styles available for the font family family.
Some example styles: "Light", "Light Italic", "Bold", "Oblique", "Demi". The list may be empty.
See also
families()
Definition at line 1773 of file qfontdatabase.cpp.
 {
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QStringList l;
     QtFontFamily *f = d->family(familyName);
     if (!f)
         return l;
     QtFontFoundry allStyles(foundryName);
     for (int j = 0; j < f->count; j++) {
         QtFontFoundry *foundry = f->foundries[j];
         if (foundryName.isEmpty() || foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             for (int k = 0; k < foundry->count; k++) {
                 QtFontStyle::Key ke(foundry->styles[k]->key);
                 ke.stretch = 0;
                 allStyles.style(ke, foundry->styles[k]->styleName, true);
             }
         }
     }
     for (int i = 0; i < allStyles.count; i++) {
         l.append(allStyles.styles[i]->styleName.isEmpty() ?
                  styleStringHelper(allStyles.styles[i]->key.weight,
                                    (QFont::Style)allStyles.styles[i]->key.style) :
                  allStyles.styles[i]->styleName);
     }
     return l;
 }
styleString() [1/2]
QString QFontDatabase::styleString (const QFont & font)
Returns a string that describes the style of the font.
For example, "Bold Italic", "Bold", "Italic" or "Normal". An empty string may be returned.
Definition at line 1531 of file qfontdatabase.cpp.
 {
     return font.styleName().isEmpty() ? styleStringHelper(font.weight(), font.style())
                                       : font.styleName();
 }
styleString() [2/2]
QString QFontDatabase::styleString (const QFontInfo & fontInfo)
Returns a string that describes the style of the fontInfo.
For example, "Bold Italic", "Bold", "Italic" or "Normal". An empty string may be returned.
Definition at line 1542 of file qfontdatabase.cpp.
 {
     return fontInfo.styleName().isEmpty() ? styleStringHelper(fontInfo.weight(), fontInfo.style())
                                           : fontInfo.styleName();
 }
supportsThreadedFontRendering()
bool QFontDatabase::supportsThreadedFontRendering () static
Returns true if font rendering is supported outside the GUI thread, false otherwise.
Since
4.4
In other words, a return value of false means that all QPainter::drawText() calls outside the GUI thread will not produce readable output.
See also
{Thread-Support in Qt Modules::Painting In Threads}{Painting In Threads}
Definition at line 542 of file qfontdatabase_mac.cpp.
Referenced by QPainter::drawTextItem(), and registerFont().
 {
     return true;
 }
weight()
int QFontDatabase::weight (const QString & family, const QString & style) const
Returns the weight of the font that has family family and style style.
If there is no such family and style combination, returns -1.
See also
italic(), bold()
Definition at line 2208 of file qfontdatabase.cpp.
 {
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)(familyName);
     QtFontFoundry allStyles(foundryName);
     QtFontFamily *f = d->family(familyName);
     if (!f) return -1;
     for (int j = 0; j < f->count; j++) {
         QtFontFoundry *foundry = f->foundries[j];
         if (foundryName.isEmpty() ||
             foundry->name.compare(foundryName, Qt::CaseInsensitive) == 0) {
             for (int k = 0; k < foundry->count; k++)
                 allStyles.style(foundry->styles[k]->key, foundry->styles[k]->styleName, true);
         }
     }
     QtFontStyle::Key styleKey(style);
     QtFontStyle *s = allStyles.style(styleKey, style);
     return s ? s->key.weight : -1;
 }
writingSystemName()
QString QFontDatabase::writingSystemName (WritingSystem writingSystem) static
Returns the names the writingSystem (e.g.
for displaying to the user in a dialog).
Definition at line 2251 of file qfontdatabase.cpp.
Referenced by QFontDialogPrivate::init(), initializeDb(), and initWritingSystems().
 {
     const char *name = 0;
     switch (writingSystem) {
     case Any:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Any");
         break;
     case Latin:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Latin");
         break;
     case Greek:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Greek");
         break;
     case Cyrillic:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Cyrillic");
         break;
     case Armenian:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Armenian");
         break;
     case Hebrew:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Hebrew");
         break;
     case Arabic:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Arabic");
         break;
     case Syriac:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Syriac");
         break;
     case Thaana:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Thaana");
         break;
     case Devanagari:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Devanagari");
         break;
     case Bengali:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Bengali");
         break;
     case Gurmukhi:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Gurmukhi");
         break;
     case Gujarati:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Gujarati");
         break;
     case Oriya:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Oriya");
         break;
     case Tamil:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Tamil");
         break;
     case Telugu:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Telugu");
         break;
     case Kannada:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Kannada");
         break;
     case Malayalam:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Malayalam");
         break;
     case Sinhala:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Sinhala");
         break;
     case Thai:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Thai");
         break;
     case Lao:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Lao");
         break;
     case Tibetan:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Tibetan");
         break;
     case Myanmar:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Myanmar");
         break;
     case Georgian:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Georgian");
         break;
     case Khmer:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Khmer");
         break;
     case SimplifiedChinese:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Simplified Chinese");
         break;
     case TraditionalChinese:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Traditional Chinese");
         break;
     case Japanese:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Japanese");
         break;
     case Korean:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Korean");
         break;
     case Vietnamese:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Vietnamese");
         break;
     case Symbol:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Symbol");
         break;
     case Ogham:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Ogham");
         break;
     case Runic:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "Runic");
         break;
     case Nko:
         name = QT_TRANSLATE_NOOP("QFontDatabase", "N'Ko");
         break;
     default:
         Q_ASSERT_X(false, "QFontDatabase::writingSystemName", "invalid 'writingSystem' parameter");
         break;
     }
     return QApplication::translate("QFontDatabase", name);
 }
writingSystems() [1/2]
QList< QFontDatabase::WritingSystem > QFontDatabase::writingSystems () const
Returns a sorted list of the available writing systems.
This is list generated from information about all installed fonts on the system.
See also
families()
Definition at line 1662 of file qfontdatabase.cpp.
Referenced by writingSystemForFont().
 {
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)();
 #ifdef Q_WS_X11
     checkSymbolFonts();
 #endif
     QList<WritingSystem> list;
     for (int i = 0; i < d->count; ++i) {
         QtFontFamily *family = d->families[i];
         if (family->count == 0)
             continue;
         for (int x = Latin; x < WritingSystemsCount; ++x) {
             const WritingSystem writingSystem = WritingSystem(x);
             if (!(family->writingSystems[writingSystem] & QtFontFamily::Supported))
                 continue;
             if (!list.contains(writingSystem))
                 list.append(writingSystem);
         }
     }
     qSort(list);
     return list;
 }
writingSystems() [2/2]
QList< QFontDatabase::WritingSystem > QFontDatabase::writingSystems (const QString & family) const
Returns a sorted list of the writing systems supported by a given font family.
See also
families()
Definition at line 1695 of file qfontdatabase.cpp.
 {
     QString familyName, foundryName;
     parseFontName(family, foundryName, familyName);
     QMutexLocker locker(fontDatabaseMutex());
     QT_PREPEND_NAMESPACE(load)();
 #ifdef Q_WS_X11
     checkSymbolFonts(familyName);
 #endif
     QList<WritingSystem> list;
     QtFontFamily *f = d->family(familyName);
     if (!f || f->count == 0)
         return list;
     for (int x = Latin; x < WritingSystemsCount; ++x) {
         const WritingSystem writingSystem = WritingSystem(x);
         if (f->writingSystems[writingSystem] & QtFontFamily::Supported)
             list.append(writingSystem);
     }
     return list;
 }
writingSystemSample()
QString QFontDatabase::writingSystemSample (WritingSystem writingSystem) static
Returns a string with sample characters from writingSystem.
Definition at line 2368 of file qfontdatabase.cpp.
Referenced by QRawFont::fromFont(), and QFontFamilyDelegate::paint().
 {
     QString sample;
     switch (writingSystem) {
     case Any:
     case Symbol:
         // show only ascii characters
         sample += QLatin1String("AaBbzZ");
         break;
     case Latin:
         // This is cheating... we only show latin-1 characters so that we don't
         // end up loading lots of fonts - at least on X11...
         sample = QLatin1String("Aa");
         sample += QChar(0x00C3);
         sample += QChar(0x00E1);
         sample += QLatin1String("Zz");
         break;
     case Greek:
         sample += QChar(0x0393);
         sample += QChar(0x03B1);
         sample += QChar(0x03A9);
         sample += QChar(0x03C9);
         break;
     case Cyrillic:
         sample += QChar(0x0414);
         sample += QChar(0x0434);
         sample += QChar(0x0436);
         sample += QChar(0x044f);
         break;
     case Armenian:
         sample += QChar(0x053f);
         sample += QChar(0x054f);
         sample += QChar(0x056f);
         sample += QChar(0x057f);
         break;
     case Hebrew:
         sample += QChar(0x05D0);
         sample += QChar(0x05D1);
         sample += QChar(0x05D2);
         sample += QChar(0x05D3);
         break;
     case Arabic:
         sample += QChar(0x0628);
         sample += QChar(0x0629);
         sample += QChar(0x062A);
         sample += QChar(0x063A);
         break;
     case Syriac:
         sample += QChar(0x0715);
         sample += QChar(0x0725);
         sample += QChar(0x0716);
         sample += QChar(0x0726);
         break;
     case Thaana:
         sample += QChar(0x0784);
         sample += QChar(0x0794);
         sample += QChar(0x078c);
         sample += QChar(0x078d);
         break;
     case Devanagari:
         sample += QChar(0x0905);
         sample += QChar(0x0915);
         sample += QChar(0x0925);
         sample += QChar(0x0935);
         break;
     case Bengali:
         sample += QChar(0x0986);
         sample += QChar(0x0996);
         sample += QChar(0x09a6);
         sample += QChar(0x09b6);
         break;
     case Gurmukhi:
         sample += QChar(0x0a05);
         sample += QChar(0x0a15);
         sample += QChar(0x0a25);
         sample += QChar(0x0a35);
         break;
     case Gujarati:
         sample += QChar(0x0a85);
         sample += QChar(0x0a95);
         sample += QChar(0x0aa5);
         sample += QChar(0x0ab5);
         break;
     case Oriya:
         sample += QChar(0x0b06);
         sample += QChar(0x0b16);
         sample += QChar(0x0b2b);
         sample += QChar(0x0b36);
         break;
     case Tamil:
         sample += QChar(0x0b89);
         sample += QChar(0x0b99);
         sample += QChar(0x0ba9);
         sample += QChar(0x0bb9);
         break;
     case Telugu:
         sample += QChar(0x0c05);
         sample += QChar(0x0c15);
         sample += QChar(0x0c25);
         sample += QChar(0x0c35);
         break;
     case Kannada:
         sample += QChar(0x0c85);
         sample += QChar(0x0c95);
         sample += QChar(0x0ca5);
         sample += QChar(0x0cb5);
         break;
     case Malayalam:
         sample += QChar(0x0d05);
         sample += QChar(0x0d15);
         sample += QChar(0x0d25);
         sample += QChar(0x0d35);
         break;
     case Sinhala:
         sample += QChar(0x0d90);
         sample += QChar(0x0da0);
         sample += QChar(0x0db0);
         sample += QChar(0x0dc0);
         break;
     case Thai:
         sample += QChar(0x0e02);
         sample += QChar(0x0e12);
         sample += QChar(0x0e22);
         sample += QChar(0x0e32);
         break;
     case Lao:
         sample += QChar(0x0e8d);
         sample += QChar(0x0e9d);
         sample += QChar(0x0ead);
         sample += QChar(0x0ebd);
         break;
     case Tibetan:
         sample += QChar(0x0f00);
         sample += QChar(0x0f01);
         sample += QChar(0x0f02);
         sample += QChar(0x0f03);
         break;
     case Myanmar:
         sample += QChar(0x1000);
         sample += QChar(0x1001);
         sample += QChar(0x1002);
         sample += QChar(0x1003);
         break;
     case Georgian:
         sample += QChar(0x10a0);
         sample += QChar(0x10b0);
         sample += QChar(0x10c0);
         sample += QChar(0x10d0);
         break;
     case Khmer:
         sample += QChar(0x1780);
         sample += QChar(0x1790);
         sample += QChar(0x17b0);
         sample += QChar(0x17c0);
         break;
     case SimplifiedChinese:
         sample += QChar(0x4e2d);
         sample += QChar(0x6587);
         sample += QChar(0x8303);
         sample += QChar(0x4f8b);
         break;
     case TraditionalChinese:
         sample += QChar(0x4e2d);
         sample += QChar(0x6587);
         sample += QChar(0x7bc4);
         sample += QChar(0x4f8b);
         break;
     case Japanese:
         sample += QChar(0x30b5);
         sample += QChar(0x30f3);
         sample += QChar(0x30d7);
         sample += QChar(0x30eb);
         sample += QChar(0x3067);
         sample += QChar(0x3059);
         break;
     case Korean:
         sample += QChar(0xac00);
         sample += QChar(0xac11);
         sample += QChar(0xac1a);
         sample += QChar(0xac2f);
         break;
     case Vietnamese:
     {
         static const char vietnameseUtf8[] = {
             char(0xef), char(0xbb), char(0xbf), char(0xe1), char(0xbb), char(0x97),
             char(0xe1), char(0xbb), char(0x99),
             char(0xe1), char(0xbb), char(0x91),
             char(0xe1), char(0xbb), char(0x93),
         };
         sample += QString::fromUtf8(vietnameseUtf8, sizeof(vietnameseUtf8));
         break;
     }
     case Ogham:
         sample += QChar(0x1681);
         sample += QChar(0x1682);
         sample += QChar(0x1683);
         sample += QChar(0x1684);
         break;
     case Runic:
         sample += QChar(0x16a0);
         sample += QChar(0x16a1);
         sample += QChar(0x16a2);
         sample += QChar(0x16a3);
         break;
     case Nko:
         sample += QChar(0x7ca);
         sample += QChar(0x7cb);
         sample += QChar(0x7cc);
         sample += QChar(0x7cd);
         break;
     default:
         break;
     }
     return sample;
 }
Friends and Related Functions
QFontDef
friend struct QFontDef friend
Definition at line 166 of file qfontdatabase.h.
Referenced by loadWin().
QFontDialog
friend class QFontDialog friend
Definition at line 168 of file qfontdatabase.h.
QFontDialogPrivate
friend class QFontDialogPrivate friend
Definition at line 169 of file qfontdatabase.h.
QFontEngineMultiQPA
friend class QFontEngineMultiQPA friend
Definition at line 173 of file qfontdatabase.h.
QFontEngineMultiQWS
friend class QFontEngineMultiQWS friend
Definition at line 171 of file qfontdatabase.h.
QFontEngineMultiS60
friend class QFontEngineMultiS60 friend
Definition at line 172 of file qfontdatabase.h.
QFontEngineMultiXLFD
friend class QFontEngineMultiXLFD friend
Definition at line 170 of file qfontdatabase.h.
QFontPrivate
friend class QFontPrivate friend
Definition at line 167 of file qfontdatabase.h.
Properties
d
QFontDatabasePrivate* QFontDatabase::d private
Definition at line 175 of file qfontdatabase.h.
Referenced by findFont().
The documentation for this class was generated from the following files:
/src/gui/text/qfontdatabase.h
/src/gui/text/qfontdatabase.cpp
/src/gui/text/qfontdatabase_mac.cpp
/src/gui/text/qfontdatabase_qpa.cpp
/src/gui/text/qfontdatabase_qws.cpp
/src/gui/text/qfontdatabase_win.cpp
/src/gui/text/qfontdatabase_x11.cpp