Qt 4.8: QListWidget Class Reference
QListWidget Class Reference
The QListWidget class provides an item-based list widget.
#include <qlistwidget.h>
Public Slots
void clear ()
Removes all items and selections in the view.
void scrollToItem (const QListWidgetItem *item, QAbstractItemView::ScrollHint hint=EnsureVisible)
Scrolls the view if necessary to ensure that the item is visible.
Public Slots inherited from QAbstractItemView
void clearSelection ()
Deselects all selected items.
void edit (const QModelIndex &index)
Starts editing the item corresponding to the given index if it is editable.
void scrollToBottom ()
Scrolls the view to the bottom.
void scrollToTop ()
Scrolls the view to the top.
virtual void selectAll ()
Selects all items in the view.
void setCurrentIndex (const QModelIndex &index)
Sets the current item to be the item at index.
void update (const QModelIndex &index)
Updates the area occupied by the given index.
Public Slots inherited from QWidget
bool close ()
Closes this widget.
void hide ()
Hides the widget.
void lower ()
Lowers the widget to the bottom of the parent widget's stack.
void raise ()
Raises this widget to the top of the parent widget's stack.
void repaint ()
Repaints the widget directly by calling paintEvent() immediately, unless updates are disabled or the widget is hidden.
void setDisabled (bool)
Disables widget input events if disable is true; otherwise enables input events.
void setEnabled (bool)
void setFocus ()
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setHidden (bool hidden)
Convenience function, equivalent to setVisible(!hidden).
QT_MOC_COMPAT void setShown (bool shown)
Use setVisible(shown) instead.
void setStyleSheet (const QString &styleSheet)
virtual void setVisible (bool visible)
void setWindowModified (bool)
void setWindowTitle (const QString &)
void show ()
Shows the widget and its child widgets.
void showFullScreen ()
Shows the widget in full-screen mode.
void showMaximized ()
Shows the widget maximized.
void showMinimized ()
Shows the widget minimized, as an icon.
void showNormal ()
Restores the widget after it has been maximized or minimized.
void update ()
Updates the widget unless updates are disabled or the widget is hidden.
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals
void currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous)
This signal is emitted whenever the current item changes.
void currentRowChanged (int currentRow)
This signal is emitted whenever the current item changes.
void currentTextChanged (const QString &currentText)
This signal is emitted whenever the current item changes.
void itemActivated (QListWidgetItem *item)
This signal is emitted when the item is activated.
void itemChanged (QListWidgetItem *item)
This signal is emitted whenever the data of item has changed.
void itemClicked (QListWidgetItem *item)
This signal is emitted with the specified item when a mouse button is clicked on an item in the widget.
void itemDoubleClicked (QListWidgetItem *item)
This signal is emitted with the specified item when a mouse button is double clicked on an item in the widget.
void itemEntered (QListWidgetItem *item)
This signal is emitted when the mouse cursor enters an item.
void itemPressed (QListWidgetItem *item)
This signal is emitted with the specified item when a mouse button is pressed on an item in the widget.
void itemSelectionChanged ()
This signal is emitted whenever the selection changes.
Signals inherited from QListView
void indexesMoved (const QModelIndexList &indexes)
This signal is emitted when the specified indexes are moved in the view.
Signals inherited from QAbstractItemView
void activated (const QModelIndex &index)
This signal is emitted when the item specified by index is activated by the user.
void clicked (const QModelIndex &index)
This signal is emitted when a mouse button is clicked.
void doubleClicked (const QModelIndex &index)
This signal is emitted when a mouse button is double-clicked.
void entered (const QModelIndex &index)
This signal is emitted when the mouse cursor enters the item specified by index.
void pressed (const QModelIndex &index)
This signal is emitted when a mouse button is pressed.
void viewportEntered ()
This signal is emitted when the mouse cursor enters the viewport.
Signals inherited from QWidget
void customContextMenuRequested (const QPoint &pos)
This signal is emitted when the widget's contextMenuPolicy is Qt::CustomContextMenu, and the user has requested a context menu on the widget.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Public Functions
void addItem (const QString &label)
Inserts an item with the text label at the end of the list widget.
void addItem (QListWidgetItem *item)
Inserts the item at the end of the list widget.
void addItems (const QStringList &labels)
Inserts items with the text labels at the end of the list widget.
void closePersistentEditor (QListWidgetItem *item)
Closes the persistent editor for the given item.
int count () const
QListWidgetItem * currentItem () const
Returns the current item.
int currentRow () const
void dropEvent (QDropEvent *event)
Reimplemented Function
void editItem (QListWidgetItem *item)
Starts editing the item if it is editable.
QList< QListWidgetItem * > findItems (const QString &text, Qt::MatchFlags flags) const
Finds items with the text that matches the string text using the given flags.
void insertItem (int row, QListWidgetItem *item)
Inserts the item at the position in the list given by row.
void insertItem (int row, const QString &label)
Inserts an item with the text label in the list widget at the position given by row.
void insertItems (int row, const QStringList &labels)
Inserts items from the list of labels into the list, starting at the given row.
bool isItemHidden (const QListWidgetItem *item) const
Returns true if the item is explicitly hidden; otherwise returns false.
bool isItemSelected (const QListWidgetItem *item) const
Returns true if item is selected; otherwise returns false.
bool isSortingEnabled () const
QListWidgetItem * item (int row) const
Returns the item that occupies the given row in the list if one has been set; otherwise returns 0.
QListWidgetItem * itemAt (const QPoint &p) const
Returns a pointer to the item at the coordinates p.
QListWidgetItem * itemAt (int x, int y) const
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns a pointer to the item at the coordinates (x, y).
QWidget * itemWidget (QListWidgetItem *item) const
Returns the widget displayed in the given item.
void openPersistentEditor (QListWidgetItem *item)
Opens an editor for the given item.
QListWidget (QWidget *parent=0)
Constructs an empty QListWidget with the given parent.
void removeItemWidget (QListWidgetItem *item)
int row (const QListWidgetItem *item) const
Returns the row containing the given item.
QList< QListWidgetItem * > selectedItems () const
Returns a list of all selected items in the list widget.
void setCurrentItem (QListWidgetItem *item)
Sets the current item to item.
void setCurrentItem (QListWidgetItem *item, QItemSelectionModel::SelectionFlags command)
Set the current item to item, using the given command.
void setCurrentRow (int row)
void setCurrentRow (int row, QItemSelectionModel::SelectionFlags command)
void setItemHidden (const QListWidgetItem *item, bool hide)
If hide is true, the item will be hidden; otherwise it will be shown.
void setItemSelected (const QListWidgetItem *item, bool select)
Selects or deselects the given item depending on whether select is true of false.
void setItemWidget (QListWidgetItem *item, QWidget *widget)
Sets the widget to be displayed in the give item.
void setSortingEnabled (bool enable)
void sortItems (Qt::SortOrder order=Qt::AscendingOrder)
Sorts all the items in the list widget according to the specified order.
QListWidgetItem * takeItem (int row)
Removes and returns the item from the given row in the list widget; otherwise returns 0.
QRect visualItemRect (const QListWidgetItem *item) const
Returns the rectangle on the viewport occupied by the item at item.
~QListWidget ()
Destroys the list widget and all its items.
Public Functions inherited from QListView
int batchSize () const
void clearPropertyFlags ()
Clears the QListView-specific property flags.
void doItemsLayout ()
Layout the items according to the flow and wrapping properties.
Flow flow () const
QSize gridSize () const
QModelIndex indexAt (const QPoint &p) const
Reimplemented Function
bool isRowHidden (int row) const
Returns true if the row is hidden; otherwise returns false.
bool isSelectionRectVisible () const
bool isWrapping () const
LayoutMode layoutMode () const
int modelColumn () const
Movement movement () const
QListView (QWidget *parent=0)
Creates a new QListView with the given parent to view a model.
void reset ()
ResizeMode resizeMode () const
void scrollTo (const QModelIndex &index, ScrollHint hint=EnsureVisible)
Reimplemented Function
void setBatchSize (int batchSize)
void setFlow (Flow flow)
void setGridSize (const QSize &size)
void setLayoutMode (LayoutMode mode)
void setModelColumn (int column)
void setMovement (Movement movement)
void setResizeMode (ResizeMode mode)
void setRootIndex (const QModelIndex &index)
void setRowHidden (int row, bool hide)
If hide is true, the given row will be hidden; otherwise the row will be shown.
void setSelectionRectVisible (bool show)
void setSpacing (int space)
void setUniformItemSizes (bool enable)
void setViewMode (ViewMode mode)
void setWordWrap (bool on)
void setWrapping (bool enable)
int spacing () const
bool uniformItemSizes () const
ViewMode viewMode () const
QRect visualRect (const QModelIndex &index) const
Reimplemented Function
bool wordWrap () const
~QListView ()
Destroys the view.
Public Functions inherited from QAbstractItemView
bool alternatingRowColors () const
int autoScrollMargin () const
void closePersistentEditor (const QModelIndex &index)
Closes the persistent editor for the item at the given index.
QModelIndex currentIndex () const
Returns the model index of the current item.
Qt::DropAction defaultDropAction () const
DragDropMode dragDropMode () const
bool dragDropOverwriteMode () const
bool dragEnabled () const
EditTriggers editTriggers () const
bool hasAutoScroll () const
ScrollMode horizontalScrollMode () const
QSize iconSize () const
QWidget * indexWidget (const QModelIndex &index) const
Returns the widget for the item at the given index.
virtual QVariant inputMethodQuery (Qt::InputMethodQuery query) const
Reimplemented Function
QAbstractItemDelegate * itemDelegate () const
Returns the item delegate used by this view and model.
QAbstractItemDelegate * itemDelegate (const QModelIndex &index) const
Returns the item delegate used by this view and model for the given index.
QAbstractItemDelegate * itemDelegateForColumn (int column) const
Returns the item delegate used by this view and model for the given column.
QAbstractItemDelegate * itemDelegateForRow (int row) const
Returns the item delegate used by this view and model for the given row, or 0 if no delegate has been assigned.
virtual void keyboardSearch (const QString &search)
Moves to and selects the item best matching the string search.
QAbstractItemModel * model () const
Returns the model that this view is presenting.
void openPersistentEditor (const QModelIndex &index)
Opens a persistent editor on the item at the given index.
QAbstractItemView (QWidget *parent=0)
Constructs an abstract item view with the given parent.
QModelIndex rootIndex () const
Returns the model index of the model's root item.
QAbstractItemView::SelectionBehavior selectionBehavior () const
QAbstractItemView::SelectionMode selectionMode () const
QItemSelectionModel * selectionModel () const
Returns the current selection model.
void setAlternatingRowColors (bool enable)
void setAutoScroll (bool enable)
void setAutoScrollMargin (int margin)
void setDefaultDropAction (Qt::DropAction dropAction)
void setDragDropMode (DragDropMode behavior)
void setDragDropOverwriteMode (bool overwrite)
void setDragEnabled (bool enable)
void setDropIndicatorShown (bool enable)
void setEditTriggers (EditTriggers triggers)
void setHorizontalScrollMode (ScrollMode mode)
void setIconSize (const QSize &size)
void setIndexWidget (const QModelIndex &index, QWidget *widget)
Sets the given widget on the item at the given index, passing the ownership of the widget to the viewport.
void setItemDelegate (QAbstractItemDelegate *delegate)
Sets the item delegate for this view and its model to delegate.
void setItemDelegateForColumn (int column, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given column.
void setItemDelegateForRow (int row, QAbstractItemDelegate *delegate)
Sets the given item delegate used by this view and model for the given row.
void setSelectionBehavior (QAbstractItemView::SelectionBehavior behavior)
void setSelectionMode (QAbstractItemView::SelectionMode mode)
virtual void setSelectionModel (QItemSelectionModel *selectionModel)
Sets the current selection model to the given selectionModel.
void setTabKeyNavigation (bool enable)
void setTextElideMode (Qt::TextElideMode mode)
void setVerticalScrollMode (ScrollMode mode)
bool showDropIndicator () const
virtual int sizeHintForColumn (int column) const
Returns the width size hint for the specified column or -1 if there is no model.
QSize sizeHintForIndex (const QModelIndex &index) const
Returns the size hint for the item with the specified index or an invalid size for invalid indexes.
virtual int sizeHintForRow (int row) const
Returns the height size hint for the specified row or -1 if there is no model.
bool tabKeyNavigation () const
Qt::TextElideMode textElideMode () const
ScrollMode verticalScrollMode () const
~QAbstractItemView ()
Destroys the view.
Public Functions inherited from QAbstractScrollArea
void addScrollBarWidget (QWidget *widget, Qt::Alignment alignment)
Adds widget as a scroll bar widget in the location specified by alignment.
QWidget * cornerWidget () const
Returns the widget in the corner between the two scroll bars.
QScrollBar * horizontalScrollBar () const
Returns the horizontal scroll bar.
Qt::ScrollBarPolicy horizontalScrollBarPolicy () const
QSize maximumViewportSize () const
Returns the size of the viewport as if the scroll bars had no valid scrolling range.
QSize minimumSizeHint () const
Reimplemented Function
QAbstractScrollArea (QWidget *parent=0)
Constructs a viewport.
QWidgetList scrollBarWidgets (Qt::Alignment alignment)
Returns a list of the currently set scroll bar widgets.
void setCornerWidget (QWidget *widget)
Sets the widget in the corner between the two scroll bars to be widget.
void setHorizontalScrollBar (QScrollBar *scrollbar)
Replaces the existing horizontal scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setHorizontalScrollBarPolicy (Qt::ScrollBarPolicy)
void setVerticalScrollBar (QScrollBar *scrollbar)
Replaces the existing vertical scroll bar with scrollBar, and sets all the former scroll bar's slider properties on the new scroll bar.
void setVerticalScrollBarPolicy (Qt::ScrollBarPolicy)
void setViewport (QWidget *widget)
Sets the viewport to be the given widget.
QSize sizeHint () const
Reimplemented Function
QScrollBar * verticalScrollBar () const
Returns the vertical scroll bar.
Qt::ScrollBarPolicy verticalScrollBarPolicy () const
QWidget * viewport () const
Returns the viewport widget.
~QAbstractScrollArea ()
Destroys the viewport.
Public Functions inherited from QFrame
QRect frameRect () const
Shadow frameShadow () const
Shape frameShape () const
int frameStyle () const
Returns the frame style.
int frameWidth () const
int lineWidth () const
int midLineWidth () const
QFrame (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a frame widget with frame style NoFrame and a 1-pixel frame width.
void setFrameRect (const QRect &)
em>Reimplemented Function
void setFrameShadow (Shadow)
void setFrameShape (Shape)
void setFrameStyle (int)
Sets the frame style to style.
void setLineWidth (int)
void setMidLineWidth (int)
QSize sizeHint () const
em>Reimplemented Function
~QFrame ()
Destroys the frame.
Public Functions inherited from QWidget
bool acceptDrops () const
QString accessibleDescription () const
QString accessibleName () const
QList< QAction * > actions () const
Returns the (possibly empty) list of this widget's actions.
void activateWindow ()
Sets the top-level widget containing this widget to be the active window.
void addAction (QAction *action)
Appends the action action to this widget's list of actions.
void addActions (QList< QAction *> actions)
Appends the actions actions to this widget's list of actions.
void adjustSize ()
Adjusts the size of the widget to fit its contents.
bool autoFillBackground () const
QPalette::ColorRole backgroundRole () const
Returns the background role of the widget.
QSize baseSize () const
QWidget * childAt (int x, int y) const
Returns the visible child widget at the position ({x}, {y}) in the widget's coordinate system.
QWidget * childAt (const QPoint &p) const
Returns the visible child widget at point p in the widget's own coordinate system.
QRect childrenRect () const
QRegion childrenRegion () const
void clearFocus ()
Takes keyboard input focus from the widget.
void clearMask ()
Removes any mask set by setMask().
QMargins contentsMargins () const
The contentsMargins function returns the widget's contents margins.
QRect contentsRect () const
Returns the area inside the widget's margins.
Qt::ContextMenuPolicy contextMenuPolicy () const
void createWinId ()
QCursor cursor () const
int devType () const
WId effectiveWinId () const
Returns the effective window system identifier of the widget, i.
void ensurePolished () const
Ensures that the widget has been polished by QStyle (i.e., has a proper font and palette).
Qt::FocusPolicy focusPolicy () const
QWidget * focusProxy () const
Returns the focus proxy, or 0 if there is no focus proxy.
QWidget * focusWidget () const
Returns the last child of this widget that setFocus had been called on.
const QFont & font () const
QFontInfo fontInfo () const
Returns the font info for the widget's current font.
QFontMetrics fontMetrics () const
Returns the font metrics for the widget's current font.
QPalette::ColorRole foregroundRole () const
Returns the foreground role.
QRect frameGeometry () const
QSize frameSize () const
const QRect & geometry () const
void getContentsMargins (int *left, int *top, int *right, int *bottom) const
Returns the widget's contents margins for left, top, right, and bottom.
HDC getDC () const
Returns the window system handle of the widget, for low-level access.
void grabGesture (Qt::GestureType type, Qt::GestureFlags flags=Qt::GestureFlags())
Subscribes the widget to a given gesture with specific flags.
void grabKeyboard ()
Grabs the keyboard input.
void grabMouse ()
Grabs the mouse input.
void grabMouse (const QCursor &)
int grabShortcut (const QKeySequence &key, Qt::ShortcutContext context=Qt::WindowShortcut)
Adds a shortcut to Qt's shortcut system that watches for the given key sequence in the given context.
QGraphicsEffect * graphicsEffect () const
The graphicsEffect function returns a pointer to the widget's graphics effect.
QGraphicsProxyWidget * graphicsProxyWidget () const
Returns the proxy widget for the corresponding embedded widget in a graphics view; otherwise returns 0.
bool hasFocus () const
bool hasMouseTracking () const
int height () const
virtual int heightForWidth (int) const
Returns the preferred height for this widget, given the width w.
QInputContext * inputContext ()
This function returns the QInputContext for this widget.
Qt::InputMethodHints inputMethodHints () const
void insertAction (QAction *before, QAction *action)
Inserts the action action to this widget's list of actions, before the action before.
void insertActions (QAction *before, QList< QAction *> actions)
Inserts the actions actions to this widget's list of actions, before the action before.
WId internalWinId () const
Returns the window system identifier of the widget, or 0 if the widget is not created yet.
bool isActiveWindow () const
bool isAncestorOf (const QWidget *child) const
Returns true if this widget is a parent, (or grandparent and so on to any level), of the given child, and both widgets are within the same window; otherwise returns false.
bool isEnabled () const
bool isEnabledTo (QWidget *) const
Returns true if this widget would become enabled if ancestor is enabled; otherwise returns false.
bool isEnabledToTLW () const
This function is deprecated.
bool isFullScreen () const
bool isHidden () const
Returns true if the widget is hidden, otherwise returns false.
bool isLeftToRight () const
bool isMaximized () const
bool isMinimized () const
bool isModal () const
bool isRightToLeft () const
bool isTopLevel () const
Use isWindow() instead.
bool isVisible () const
bool isVisibleTo (QWidget *) const
Returns true if this widget would become visible if ancestor is shown; otherwise returns false.
bool isWindow () const
Returns true if the widget is an independent window, otherwise returns false.
bool isWindowModified () const
QLayout * layout () const
Returns the layout manager that is installed on this widget, or 0 if no layout manager is installed.
Qt::LayoutDirection layoutDirection () const
QLocale locale () const
Qt::HANDLE macCGHandle () const
Returns the CoreGraphics handle of the widget.
Qt::HANDLE macQDHandle () const
Returns the QuickDraw handle of the widget.
QPoint mapFrom (QWidget *, const QPoint &) const
Translates the widget coordinate pos from the coordinate system of parent to this widget's coordinate system.
QPoint mapFromGlobal (const QPoint &) const
Translates the global screen coordinate pos to widget coordinates.
QPoint mapFromParent (const QPoint &) const
Translates the parent widget coordinate pos to widget coordinates.
QPoint mapTo (QWidget *, const QPoint &) const
Translates the widget coordinate pos to the coordinate system of parent.
QPoint mapToGlobal (const QPoint &) const
Translates the widget coordinate pos to global screen coordinates.
QPoint mapToParent (const QPoint &) const
Translates the widget coordinate pos to a coordinate in the parent widget.
QRegion mask () const
Returns the mask currently set on a widget.
int maximumHeight () const
QSize maximumSize () const
int maximumWidth () const
int minimumHeight () const
QSize minimumSize () const
int minimumWidth () const
void move (int x, int y)
This corresponds to move(QPoint(x, y)).
void move (const QPoint &)
QWidget * nativeParentWidget () const
Returns the native parent for this widget, i.
QWidget * nextInFocusChain () const
Returns the next widget in this widget's focus chain.
QRect normalGeometry () const
void overrideWindowFlags (Qt::WindowFlags type)
Sets the window flags for the widget to flags, without telling the window system.
void overrideWindowState (Qt::WindowStates state)
QPaintEngine * paintEngine () const
Returns the widget's paint engine.
const QPalette & palette () const
QWidget * parentWidget () const
Returns the parent of this widget, or 0 if it does not have any parent widget.
QPoint pos () const
QWidget * previousInFocusChain () const
The previousInFocusChain function returns the previous widget in this widget's focus chain.
QWidget (QWidget *parent=0, Qt::WindowFlags f=0)
Constructs a widget which is a child of parent, with widget flags set to f.
QRect rect () const
void releaseDC (HDC) const
Releases the HDC hdc acquired by a previous call to getDC().
void releaseKeyboard ()
Releases the keyboard grab.
void releaseMouse ()
Releases the mouse grab.
void releaseShortcut (int id)
Removes the shortcut with the given id from Qt's shortcut system.
void removeAction (QAction *action)
Removes the action action from this widget's list of actions.
void render (QPaintDevice *target, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the sourceRegion of this widget into the target using renderFlags to determine how to render.
void render (QPainter *painter, const QPoint &targetOffset=QPoint(), const QRegion &sourceRegion=QRegion(), RenderFlags renderFlags=RenderFlags(DrawWindowBackground|DrawChildren))
Renders the widget into the painter's QPainter::device().
void repaint (int x, int y, int w, int h)
This version repaints a rectangle (x, y, w, h) inside the widget.
void repaint (const QRect &)
This version repaints a rectangle rect inside the widget.
void repaint (const QRegion &)
This version repaints a region rgn inside the widget.
void resize (int w, int h)
This corresponds to resize(QSize(w, h)).
void resize (const QSize &)
bool restoreGeometry (const QByteArray &geometry)
Restores the geometry and state top-level widgets stored in the byte array geometry.
QByteArray saveGeometry () const
Saves the current geometry and state for top-level widgets.
void scroll (int dx, int dy)
Scrolls the widget including its children dx pixels to the right and dy downward.
void scroll (int dx, int dy, const QRect &)
This version only scrolls r and does not move the children of the widget.
void setAcceptDrops (bool on)
void setAccessibleDescription (const QString &description)
void setAccessibleName (const QString &name)
void setAttribute (Qt::WidgetAttribute, bool on=true)
Sets the attribute attribute on this widget if on is true; otherwise clears the attribute.
void setAutoFillBackground (bool enabled)
void setBackgroundRole (QPalette::ColorRole)
Sets the background role of the widget to role.
void setBaseSize (const QSize &)
void setBaseSize (int basew, int baseh)
This corresponds to setBaseSize(QSize(basew, baseh)).
void setContentsMargins (int left, int top, int right, int bottom)
Sets the margins around the contents of the widget to have the sizes left, top, right, and bottom.
void setContentsMargins (const QMargins &margins)
The setContentsMargins function sets the margins around the widget's contents.
void setContextMenuPolicy (Qt::ContextMenuPolicy policy)
void setCursor (const QCursor &)
void setFixedHeight (int h)
Sets both the minimum and maximum heights of the widget to h without changing the widths.
void setFixedSize (const QSize &)
Sets both the minimum and maximum sizes of the widget to s, thereby preventing it from ever growing or shrinking.
void setFixedSize (int w, int h)
Sets the width of the widget to w and the height to h.
void setFixedWidth (int w)
Sets both the minimum and maximum width of the widget to w without changing the heights.
void setFocus (Qt::FocusReason reason)
Gives the keyboard input focus to this widget (or its focus proxy) if this widget or one of its parents is the active window.
void setFocusPolicy (Qt::FocusPolicy policy)
void setFocusProxy (QWidget *)
Sets the widget's focus proxy to widget w.
void setFont (const QFont &)
Use the single-argument overload instead.
void setForegroundRole (QPalette::ColorRole)
Sets the foreground role of the widget to role.
void setGeometry (int x, int y, int w, int h)
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.This corresponds to setGeometry(QRect(x, y, w, h)).
void setGeometry (const QRect &)
void setGraphicsEffect (QGraphicsEffect *effect)
The setGraphicsEffect function is for setting the widget's graphics effect.
void setInputContext (QInputContext *)
This function sets the input context context on this widget.
void setInputMethodHints (Qt::InputMethodHints hints)
void setLayout (QLayout *)
Sets the layout manager for this widget to layout.
void setLayoutDirection (Qt::LayoutDirection direction)
void setLocale (const QLocale &locale)
void setMask (const QBitmap &)
Causes only the pixels of the widget for which bitmap has a corresponding 1 bit to be visible.
void setMask (const QRegion &)
Causes only the parts of the widget which overlap region to be visible.
void setMaximumHeight (int maxh)
void setMaximumSize (const QSize &)
void setMaximumSize (int maxw, int maxh)
This function corresponds to setMaximumSize(QSize(maxw, maxh)).
void setMaximumWidth (int maxw)
void setMinimumHeight (int minh)
void setMinimumSize (const QSize &)
void setMinimumSize (int minw, int minh)
This function corresponds to setMinimumSize(QSize(minw, minh)).
void setMinimumWidth (int minw)
void setMouseTracking (bool enable)
void setPalette (const QPalette &)
Use the single-argument overload instead.
void setParent (QWidget *parent)
Sets the parent of the widget to parent, and resets the window flags.
void setParent (QWidget *parent, Qt::WindowFlags f)
This function also takes widget flags, f as an argument.
void setShortcutAutoRepeat (int id, bool enable=true)
If enable is true, auto repeat of the shortcut with the given id is enabled; otherwise it is disabled.
void setShortcutEnabled (int id, bool enable=true)
If enable is true, the shortcut with the given id is enabled; otherwise the shortcut is disabled.
void setSizeIncrement (const QSize &)
void setSizeIncrement (int w, int h)
Sets the x (width) size increment to w and the y (height) size increment to h.
void setSizePolicy (QSizePolicy)
void setSizePolicy (QSizePolicy::Policy horizontal, QSizePolicy::Policy vertical)
Sets the size policy of the widget to horizontal and vertical, with standard stretch and no height-for-width.
void setStatusTip (const QString &)
void setStyle (QStyle *)
Sets the widget's GUI style to style.
void setToolTip (const QString &)
void setUpdatesEnabled (bool enable)
void setupUi (QWidget *widget)
Sets up the user interface for the specified widget.
void setWhatsThis (const QString &)
void setWindowFilePath (const QString &filePath)
void setWindowFlags (Qt::WindowFlags type)
void setWindowIcon (const QIcon &icon)
void setWindowIconText (const QString &)
void setWindowModality (Qt::WindowModality windowModality)
void setWindowOpacity (qreal level)
void setWindowRole (const QString &)
Sets the window's role to role.
void setWindowState (Qt::WindowStates state)
Sets the window state to windowState.
void setWindowSurface (QWindowSurface *surface)
Sets the window surface to be the surface specified.
QSize size () const
QSize sizeIncrement () const
QSizePolicy sizePolicy () const
void stackUnder (QWidget *)
Places the widget under w in the parent widget's stack.
QString statusTip () const
QStyle * style () const
QString styleSheet () const
bool testAttribute (Qt::WidgetAttribute) const
Returns true if attribute attribute is set on this widget; otherwise returns false.
QString toolTip () const
QWidget * topLevelWidget () const
bool underMouse () const
Returns true if the widget is under the mouse cursor; otherwise returns false.
void ungrabGesture (Qt::GestureType type)
Unsubscribes the widget from a given gesture type.
void unsetCursor ()
void unsetLayoutDirection ()
void unsetLocale ()
void update (int x, int y, int w, int h)
This version updates a rectangle (x, y, w, h) inside the widget.
void update (const QRect &)
This version updates a rectangle rect inside the widget.
void update (const QRegion &)
This version repaints a region rgn inside the widget.
void updateGeometry ()
Notifies the layout system that this widget has changed and may need to change geometry.
bool updatesEnabled () const
QRegion visibleRegion () const
Returns the unobscured region where paint events can occur.
QString whatsThis () const
int width () const
QWidget * window () const
Returns the window for this widget, i.e.
QString windowFilePath () const
Qt::WindowFlags windowFlags () const
Window flags are a combination of a type (e.
QIcon windowIcon () const
QString windowIconText () const
Qt::WindowModality windowModality () const
qreal windowOpacity () const
QString windowRole () const
Returns the window's role, or an empty string.
Qt::WindowStates windowState () const
Returns the current window state.
QWindowSurface * windowSurface () const
Returns the QWindowSurface this widget will be drawn into.
QString windowTitle () const
Qt::WindowType windowType () const
Returns the window type of this widget.
WId winId () const
Returns the window system identifier of the widget.
int x () const
const QX11Info & x11Info () const
Returns information about the configuration of the X display used to display the widget.
Qt::HANDLE x11PictureHandle () const
Returns the X11 Picture handle of the widget for XRender support.
int y () const
~QWidget ()
Destroys the widget.
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Public Functions inherited from QPaintDevice
int colorCount () const
int depth () const
int height () const
int heightMM () const
int logicalDpiX () const
int logicalDpiY () const
QT_DEPRECATED int numColors () const
bool paintingActive () const
int physicalDpiX () const
int physicalDpiY () const
int width () const
int widthMM () const
virtual ~QPaintDevice ()
Protected Functions
virtual bool dropMimeData (int index, const QMimeData *data, Qt::DropAction action)
Handles data supplied by an external drag and drop operation that ended with the given action in the given index.
bool event (QEvent *e)
Reimplemented Function
QModelIndex indexFromItem (QListWidgetItem *item) const
Returns the QModelIndex assocated with the given item.
QListWidgetItem * itemFromIndex (const QModelIndex &index) const
Returns a pointer to the QListWidgetItem assocated with the given index.
QList< QListWidgetItem * > items (const QMimeData *data) const
Returns a list of pointers to the items contained in the data object.
virtual QMimeData * mimeData (const QList< QListWidgetItem *> items) const
Returns an object that contains a serialized description of the specified items.
virtual QStringList mimeTypes () const
Returns a list of MIME types that can be used to describe a list of listwidget items.
virtual Qt::DropActions supportedDropActions () const
Returns the drop actions supported by this view.
Protected Functions inherited from QListView
QSize contentsSize () const
void currentChanged (const QModelIndex &current, const QModelIndex &previous)
Reimplemented Function
void dataChanged (const QModelIndex &topLeft, const QModelIndex &bottomRight)
Reimplemented Function
void dragLeaveEvent (QDragLeaveEvent *e)
Reimplemented Function
void dragMoveEvent (QDragMoveEvent *e)
Reimplemented Function
int horizontalOffset () const
Reimplemented Function
void internalDrag (Qt::DropActions supportedActions)
Called whenever the user starts dragging items and the items are movable, enabling internal dragging and dropping of items.
void internalDrop (QDropEvent *e)
Called whenever items from the view is dropped on the viewport.
bool isIndexHidden (const QModelIndex &index) const
Reimplemented Function
void mouseMoveEvent (QMouseEvent *e)
Reimplemented Function
void mouseReleaseEvent (QMouseEvent *e)
Reimplemented Function
QModelIndex moveCursor (CursorAction cursorAction, Qt::KeyboardModifiers modifiers)
Reimplemented Function
void paintEvent (QPaintEvent *e)
Reimplemented Function
QListView (QListViewPrivate &, QWidget *parent=0)
QRect rectForIndex (const QModelIndex &index) const
Returns the rectangle of the item at position index in the model.
void resizeContents (int width, int height)
Resize the internal contents to width and height and set the scroll bar ranges accordingly.
void resizeEvent (QResizeEvent *e)
Reimplemented Function
void rowsAboutToBeRemoved (const QModelIndex &parent, int start, int end)
Reimplemented Function
void rowsInserted (const QModelIndex &parent, int start, int end)
Reimplemented Function
void scrollContentsBy (int dx, int dy)
Scroll the view contents by dx and dy.
QModelIndexList selectedIndexes () const
Reimplemented Function
void selectionChanged (const QItemSelection &selected, const QItemSelection &deselected)
Reimplemented Function
void setPositionForIndex (const QPoint &position, const QModelIndex &index)
Sets the contents position of the item at index in the model to the given position.
void setSelection (const QRect &rect, QItemSelectionModel::SelectionFlags command)
Reimplemented Function
void startDrag (Qt::DropActions supportedActions)
Reimplemented Function
void timerEvent (QTimerEvent *e)
Reimplemented Function
void updateGeometries ()
Reimplemented Function
int verticalOffset () const
Reimplemented Function
QStyleOptionViewItem viewOptions () const
Reimplemented Function
QRegion visualRegionForSelection (const QItemSelection &selection) const
Since 4.
Protected Functions inherited from QAbstractItemView
QPoint dirtyRegionOffset () const
Returns the offset of the dirty regions in the view.
void doAutoScroll ()
void dragEnterEvent (QDragEnterEvent *event)
This function is called with the given event when a drag and drop operation enters the widget.
DropIndicatorPosition dropIndicatorPosition () const
Returns the position of the drop indicator in relation to the closest item.
virtual bool edit (const QModelIndex &index, EditTrigger trigger, QEvent *event)
Starts editing the item at index, creating an editor if necessary, and returns true if the view's State is now EditingState; otherwise returns false.
void executeDelayedItemsLayout ()
Executes the scheduled layouts without waiting for the event processing to begin.
void focusInEvent (QFocusEvent *event)
This function is called with the given event when the widget obtains the focus.
bool focusNextPrevChild (bool next)
Reimplemented Function
void focusOutEvent (QFocusEvent *event)
This function is called with the given event when the widget looses the focus.
int horizontalStepsPerItem () const
Returns the horizontal scroll bar's steps per item.
void inputMethodEvent (QInputMethodEvent *event)
Reimplemented Function
void keyPressEvent (QKeyEvent *event)
This function is called with the given event when a key event is sent to the widget.
void mouseDoubleClickEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is double clicked inside the widget.
void mousePressEvent (QMouseEvent *event)
This function is called with the given event when a mouse button is pressed while the cursor is inside the widget.
QAbstractItemView (QAbstractItemViewPrivate &, QWidget *parent=0)
void scheduleDelayedItemsLayout ()
Schedules a layout of the items in the view to be executed when the event processing starts.
void scrollDirtyRegion (int dx, int dy)
Prepares the view for scrolling by ({dx},{dy}) pixels by moving the dirty regions in the opposite direction.
virtual QItemSelectionModel::SelectionFlags selectionCommand (const QModelIndex &index, const QEvent *event=0) const
Returns the SelectionFlags to be used when updating a selection with to include the index specified.
void setDirtyRegion (const QRegion &region)
Marks the given region as dirty and schedules it to be updated.
void setHorizontalStepsPerItem (int steps)
Sets the horizontal scroll bar's steps per item to steps.
void setState (State state)
Sets the item view's state to the given state.
void setVerticalStepsPerItem (int steps)
Sets the vertical scroll bar's steps per item to steps.
void startAutoScroll ()
State state () const
Returns the item view's state.
void stopAutoScroll ()
int verticalStepsPerItem () const
Returns the vertical scroll bar's steps per item.
bool viewportEvent (QEvent *event)
This function is used to handle tool tips, and What's This? mode, if the given event is a QEvent::ToolTip,or a QEvent::WhatsThis.
Protected Functions inherited from QAbstractScrollArea
void contextMenuEvent (QContextMenuEvent *)
This event handler can be reimplemented in a subclass to receive context menu events for the viewport() widget.
void dragEnterEvent (QDragEnterEvent *)
This event handler can be reimplemented in a subclass to receive drag enter events (passed in event), for the viewport() widget.
void dragLeaveEvent (QDragLeaveEvent *)
This event handler can be reimplemented in a subclass to receive drag leave events (passed in event), for the viewport() widget.
void dragMoveEvent (QDragMoveEvent *)
This event handler can be reimplemented in a subclass to receive drag move events (passed in event), for the viewport() widget.
void dropEvent (QDropEvent *)
This event handler can be reimplemented in a subclass to receive drop events (passed in event), for the viewport() widget.
bool event (QEvent *)
Reimplemented Function
void keyPressEvent (QKeyEvent *)
This function is called with key event e when key presses occur.
void mouseDoubleClickEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse double click events for the viewport() widget.
void mouseMoveEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse move events for the viewport() widget.
void mousePressEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse press events for the viewport() widget.
void mouseReleaseEvent (QMouseEvent *)
This event handler can be reimplemented in a subclass to receive mouse release events for the viewport() widget.
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events (passed in event), for the viewport() widget.
QAbstractScrollArea (QAbstractScrollAreaPrivate &dd, QWidget *parent=0)
Creates a new QAbstractScrollAreaPrivate, dd with the given parent.
void resizeEvent (QResizeEvent *)
This event handler can be reimplemented in a subclass to receive resize events (passed in event), for the viewport() widget.
void setViewportMargins (int left, int top, int right, int bottom)
Sets the margins around the scrolling area to left, top, right and bottom.
void setViewportMargins (const QMargins &margins)
Sets margins around the scrolling area.
void wheelEvent (QWheelEvent *)
This event handler can be reimplemented in a subclass to receive wheel events for the viewport() widget.
Protected Functions inherited from QFrame
void changeEvent (QEvent *)
This event handler can be reimplemented to handle state changes.
void drawFrame (QPainter *)
em>Reimplemented Function
bool event (QEvent *e)
Reimplemented Function
void paintEvent (QPaintEvent *)
This event handler can be reimplemented in a subclass to receive paint events passed in event.
QFrame (QFramePrivate &dd, QWidget *parent=0, Qt::WindowFlags f=0)
Protected Functions inherited from QWidget
virtual void actionEvent (QActionEvent *)
This event handler is called with the given event whenever the widget's actions are changed.
virtual void closeEvent (QCloseEvent *)
This event handler is called with the given event when Qt receives a window close request for a top-level widget from the window system.
void create (WId=0, bool initializeWindow=true, bool destroyOldWindow=true)
Creates a new widget window if window is 0, otherwise sets the widget's window to window.
void destroy (bool destroyWindow=true, bool destroySubWindows=true)
Frees up window system resources.
virtual void enabledChange (bool)
virtual void enterEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget enter events which are passed in the event parameter.
bool focusNextChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Tab, and returns true if it can find a new widget, or false if it can't.
bool focusPreviousChild ()
Finds a new widget to give the keyboard focus to, as appropriate for Shift+Tab, and returns true if it can find a new widget, or false if it can't.
virtual void fontChange (const QFont &)
virtual void hideEvent (QHideEvent *)
This event handler can be reimplemented in a subclass to receive widget hide events.
virtual void keyReleaseEvent (QKeyEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive key release events for the widget.
virtual void languageChange ()
virtual void leaveEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive widget leave events which are passed in the event parameter.
virtual bool macEvent (EventHandlerCallRef, EventRef)
This special event handler can be reimplemented in a subclass to receive native Macintosh events.
int metric (PaintDeviceMetric) const
Internal implementation of the virtual QPaintDevice::metric() function.
virtual void moveEvent (QMoveEvent *)
This event handler can be reimplemented in a subclass to receive widget move events which are passed in the event parameter.
virtual void paletteChange (const QPalette &)
QWidget (QWidgetPrivate &d, QWidget *parent, Qt::WindowFlags f)
virtual bool qwsEvent (QWSEvent *)
This special event handler can be reimplemented in a subclass to receive native Qt for Embedded Linux events which are passed in the event parameter.
void resetInputContext ()
This function can be called on the widget that currently has focus to reset the input method operating on it.
virtual void showEvent (QShowEvent *)
This event handler can be reimplemented in a subclass to receive widget show events which are passed in the event parameter.
virtual void styleChange (QStyle &)
virtual void tabletEvent (QTabletEvent *)
This event handler, for event event, can be reimplemented in a subclass to receive tablet events for the widget.
virtual void windowActivationChange (bool)
virtual bool winEvent (MSG *message, long *result)
This special event handler can be reimplemented in a subclass to receive native Windows events which are passed in the message parameter.
virtual bool x11Event (XEvent *)
This special event handler can be reimplemented in a subclass to receive native X11 events passed in the event parameter.
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
Protected Functions inherited from QPaintDevice
QPaintDevice ()
Private Functions
void setModel (QAbstractItemModel *model)
Qt::SortOrder sortOrder () const
Properties
int count
the number of items in the list including any hidden items.
int currentRow
the row of the current item.
bool sortingEnabled
whether sorting is enabled
Friends
class QListModel
class QListWidgetItem
Additional Inherited Members
Public Types inherited from QListView
enum Flow { LeftToRight, TopToBottom }
enum LayoutMode { SinglePass, Batched }
enum Movement { Static, Free, Snap }
enum ResizeMode { Fixed, Adjust }
enum ViewMode { ListMode, IconMode }
Public Types inherited from QAbstractItemView
enum DragDropMode {
NoDragDrop, DragOnly, DropOnly, DragDrop,
InternalMove
}
Describes the various drag and drop events the view can act upon.
enum EditTrigger {
NoEditTriggers = 0, CurrentChanged = 1, DoubleClicked = 2, SelectedClicked = 4,
EditKeyPressed = 8, AnyKeyPressed = 16, AllEditTriggers = 31
}
This enum describes actions which will initiate item editing.
enum ScrollHint { EnsureVisible, PositionAtTop, PositionAtBottom, PositionAtCenter }
enum ScrollMode { ScrollPerItem, ScrollPerPixel }
enum SelectionBehavior { SelectItems, SelectRows, SelectColumns }
enum SelectionMode {
NoSelection, SingleSelection, MultiSelection, ExtendedSelection,
ContiguousSelection
}
This enum indicates how the view responds to user selections:
Public Types inherited from QFrame
enum Shadow { Plain = 0x0010, Raised = 0x0020, Sunken = 0x0030 }
This enum type defines the types of shadow that are used to give a 3D effect to frames.
enum Shape {
NoFrame = 0, Box = 0x0001, Panel = 0x0002, WinPanel = 0x0003,
HLine = 0x0004, VLine = 0x0005, StyledPanel = 0x0006
}
This enum type defines the shapes of frame available.
enum StyleMask { Shadow_Mask = 0x00f0, Shape_Mask = 0x000f }
This enum defines two constants that can be used to extract the two components of frameStyle():
Public Types inherited from QWidget
enum RenderFlag { DrawWindowBackground = 0x1, DrawChildren = 0x2, IgnoreMask = 0x4 }
This enum describes how to render the widget when calling QWidget::render().
Public Types inherited from QPaintDevice
enum PaintDeviceMetric {
PdmWidth = 1, PdmHeight, PdmWidthMM, PdmHeightMM,
PdmNumColors, PdmDepth, PdmDpiX, PdmDpiY,
PdmPhysicalDpiX, PdmPhysicalDpiY
}
Static Public Functions inherited from QWidget
static QWidget * find (WId)
Returns a pointer to the widget with window identifer/handle id.
static QWidget * keyboardGrabber ()
Returns the widget that is currently grabbing the keyboard input.
static QWidget * mouseGrabber ()
Returns the widget that is currently grabbing the mouse input.
static void setTabOrder (QWidget *, QWidget *)
Puts the second widget after the first widget in the focus order.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Static Public Functions inherited from QPaintDevice
static QWSDisplay * qwsDisplay ()
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Protected Types inherited from QAbstractItemView
enum CursorAction {
MoveUp, MoveDown, MoveLeft, MoveRight,
MoveHome, MoveEnd, MovePageUp, MovePageDown,
MoveNext, MovePrevious
}
This enum describes the different ways to navigate between items,.
enum DropIndicatorPosition { OnItem, AboveItem, BelowItem, OnViewport }
This enum indicates the position of the drop indicator in relation to the index at the current mouse position:
enum State {
NoState, DraggingState, DragSelectingState, EditingState,
ExpandingState, CollapsingState, AnimatingState
}
Describes the different states the view can be in.
Protected Slots inherited from QAbstractItemView
virtual void closeEditor (QWidget *editor, QAbstractItemDelegate::EndEditHint hint)
Closes the given editor, and releases it.
virtual void commitData (QWidget *editor)
Commit the data in the editor to the model.
virtual void editorDestroyed (QObject *editor)
This function is called when the given editor has been destroyed.
virtual void horizontalScrollbarAction (int action)
virtual void horizontalScrollbarValueChanged (int value)
virtual void updateEditorData ()
Updates the data shown in the open editor widgets in the view.
virtual void updateEditorGeometries ()
Updates the geometry of the open editor widgets in the view.
virtual void verticalScrollbarAction (int action)
virtual void verticalScrollbarValueChanged (int value)
Protected Slots inherited from QAbstractScrollArea
void setupViewport (QWidget *viewport)
This slot is called by QAbstractScrollArea after setViewport(viewport) has been called.
Protected Slots inherited from QWidget
void updateMicroFocus ()
Updates the widget's micro focus.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Protected Variables inherited from QPaintDevice
ushort painters
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QWidget
QWidgetList
WId
Platform dependent window identifier.
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Related Functions inherited from QPaintDevice
const Q_GUI_EXPORT QX11Info * qt_x11Info (const QPaintDevice *pd)
Returns the QX11Info structure for the pd paint device.
Detailed Description
The QListWidget class provides an item-based list widget.
QListWidget is a convenience class that provides a list view similar to the one supplied by QListView, but with a classic item-based interface for adding and removing items. QListWidget uses an internal model to manage each QListWidgetItem in the list.
For a more flexible list view widget, use the QListView class with a standard model.
List widgets are constructed in the same way as other widgets:
    QListWidget *listWidget = new QListWidget(this);
The selectionMode() of a list widget determines how many of the items in the list can be selected at the same time, and whether complex selections of items can be created. This can be set with the setSelectionMode() function.
There are two ways to add items to the list: they can be constructed with the list widget as their parent widget, or they can be constructed with no parent widget and added to the list later. If a list widget already exists when the items are constructed, the first method is easier to use:
    new QListWidgetItem(tr("Oak"), listWidget);
    new QListWidgetItem(tr("Fir"), listWidget);
    new QListWidgetItem(tr("Pine"), listWidget);
If you need to insert a new item into the list at a particular position, then it should be constructed without a parent widget. The insertItem() function should then be used to place it within the list. The list widget will take ownership of the item.
    QListWidgetItem *newItem = new QListWidgetItem;
    newItem->setText(itemText);
    listWidget->insertItem(row, newItem);
For multiple items, insertItems() can be used instead. The number of items in the list is found with the count() function. To remove items from the list, use takeItem().
The current item in the list can be found with currentItem(), and changed with setCurrentItem(). The user can also change the current item by navigating with the keyboard or clicking on a different item. When the current item changes, the currentItemChanged() signal is emitted with the new current item and the item that was previously current.
Screenshot of a Windows XP style list widget
Screenshot of a Macintosh style table widget
Screenshot of a Plastique style table widget
A Windows XP Style Widget Gallery{Windows XP style} list widget. A Macintosh Style Widget Gallery{Macintosh style} list widget. A Plastique Style Widget Gallery{Plastique style} list widget.
See also
QListWidgetItem, QListView, QTreeView, {Model/View Programming}, {Config Dialog Example}
Definition at line 202 of file qlistwidget.h.
Constructors and Destructors
QListWidget()
QListWidget::QListWidget (QWidget * parent = 0) explicit
Constructs an empty QListWidget with the given parent.
Definition at line 1458 of file qlistwidget.cpp.
     : QListView(*new QListWidgetPrivate(), parent)
 {
     Q_D(QListWidget);
     d->setup();
 }
~QListWidget()
QListWidget::~QListWidget ()
Destroys the list widget and all its items.
Definition at line 1469 of file qlistwidget.cpp.
 {
 }
Functions
addItem() [1/2]
void QListWidget::addItem (const QString & label) inline
Inserts an item with the text label at the end of the list widget.
Definition at line 220 of file qlistwidget.h.
 { insertItem(count(), label); }
addItem() [2/2]
void QListWidget::addItem (QListWidgetItem * item) inline
Inserts the item at the end of the list widget.
Warning
A QListWidgetItem can only be added to a QListWidget once. Adding the same QListWidgetItem multiple times to a QListWidget will result in undefined behavior.
See also
insertItem()
Definition at line 311 of file qlistwidget.h.
 { insertItem(count(), aitem); }
addItems()
void QListWidget::addItems (const QStringList & labels) inline
Inserts items with the text labels at the end of the list widget.
See also
insertItems()
Definition at line 222 of file qlistwidget.h.
 { insertItems(count(), labels); }
clear
void QListWidget::clear () slot
Removes all items and selections in the view.
Warning
All items will be permanently deleted.
Definition at line 1903 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     selectionModel()->clear();
     d->listModel()->clear();
 }
closePersistentEditor()
void QListWidget::closePersistentEditor (QListWidgetItem * item)
Closes the persistent editor for the given item.
See also
openPersistentEditor()
Definition at line 1748 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     QModelIndex index = d->listModel()->index(item);
     QAbstractItemView::closePersistentEditor(index);
 }
count()
int QListWidget::count () const
Referenced by dropEvent(), and takeItem().
currentItem()
QListWidgetItem * QListWidget::currentItem () const
Returns the current item.
Definition at line 1575 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     return d->listModel()->at(currentIndex().row());
 }
currentItemChanged
void QListWidget::currentItemChanged (QListWidgetItem * current, QListWidgetItem * previous) signal
This signal is emitted whenever the current item changes.
previous is the item that previously had the focus; current is the new current item.
currentRow()
int QListWidget::currentRow () const
Referenced by setCurrentItem().
currentRowChanged
void QListWidget::currentRowChanged (int currentRow) signal
This signal is emitted whenever the current item changes.
currentRow is the row of the current item. If there is no current item, the currentRow is -1.
currentTextChanged
void QListWidget::currentTextChanged (const QString & currentText) signal
This signal is emitted whenever the current item changes.
currentText is the text data in the current item. If there is no current item, the currentText is invalid.
dropEvent()
void QListWidget::dropEvent (QDropEvent * event) virtual
Reimplemented Function
Reimplemented from QListView.
Definition at line 1957 of file qlistwidget.cpp.
{
     Q_D(QListWidget);
     if (event->source() == this && d->movement != Static) {
         QListView::dropEvent(event);
         return;
     }
     if (event->source() == this && (event->dropAction() == Qt::MoveAction ||
                                     dragDropMode() == QAbstractItemView::InternalMove)) {
         QModelIndex topIndex;
         int col = -1;
         int row = -1;
         if (d->dropOn(event, &row, &col, &topIndex)) {
             QList<QModelIndex> selIndexes = selectedIndexes();
             QList<QPersistentModelIndex> persIndexes;
             for (int i = 0; i < selIndexes.count(); i++)
                 persIndexes.append(selIndexes.at(i));
             if (persIndexes.contains(topIndex))
                 return;
             qSort(persIndexes); // The dropped items will remain in the same visual order.
             QPersistentModelIndex dropRow = model()->index(row, col, topIndex);
             int r = row == -1 ? count() : (dropRow.row() >= 0 ? dropRow.row() : row);
             for (int i = 0; i < persIndexes.count(); ++i) {
                 const QPersistentModelIndex &pIndex = persIndexes.at(i);
                 d->listModel()->move(pIndex.row(), r);
                 r = pIndex.row() + 1;   // Dropped items are inserted contiguously and in the right order.
             }
             event->accept();
             // Don't want QAbstractItemView to delete it because it was "moved" we already did it
             event->setDropAction(Qt::CopyAction);
         }
     }
     QListView::dropEvent(event);
 }
dropMimeData()
bool QListWidget::dropMimeData (int index, const QMimeData * data, Qt::DropAction action) protected virtual
Handles data supplied by an external drag and drop operation that ended with the given action in the given index.
Returns true if data and action can be handled by the model; otherwise returns false.
See also
supportedDropActions()
Definition at line 1942 of file qlistwidget.cpp.
Referenced by QListModel::dropMimeData().
 {
     QModelIndex idx;
     int row = index;
     int column = 0;
     if (dropIndicatorPosition() == QAbstractItemView::OnItem) {
         // QAbstractListModel::dropMimeData will overwrite on the index if row == -1 and column == -1
         idx = model()->index(row, column);
         row = -1;
         column = -1;
     }
     return d_func()->listModel()->QAbstractListModel::dropMimeData(data, action , row, column, idx);
 }
editItem()
void QListWidget::editItem (QListWidgetItem * item)
Starts editing the item if it is editable.
Definition at line 1724 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     edit(d->listModel()->index(item));
 }
event()
bool QListWidget::event (QEvent * e) protected virtual
Reimplemented Function
Reimplemented from QListView.
Definition at line 2055 of file qlistwidget.cpp.
 {
     return QListView::event(e);
 }
findItems()
QList< QListWidgetItem * > QListWidget::findItems (const QString & text, Qt::MatchFlags flags) const
Finds items with the text that matches the string text using the given flags.
Definition at line 1850 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     QModelIndexList indexes = d->listModel()->match(model()->index(0, 0, QModelIndex()),
                                                 Qt::DisplayRole, text, -1, flags);
     QList<QListWidgetItem*> items;
     for (int i = 0; i < indexes.size(); ++i)
         items.append(d->listModel()->at(indexes.at(i).row()));
     return items;
 }
indexFromItem()
QModelIndex QListWidget::indexFromItem (QListWidgetItem * item) const protected
Returns the QModelIndex assocated with the given item.
Definition at line 2026 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     return d->listModel()->index(item);
 }
insertItem() [1/2]
void QListWidget::insertItem (int row, QListWidgetItem * item)
Inserts the item at the position in the list given by row.
See also
addItem()
Definition at line 1507 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     if (item && !item->view)
         d->listModel()->insert(row, item);
 }
insertItem() [2/2]
void QListWidget::insertItem (int row, const QString & label)
Inserts an item with the text label in the list widget at the position given by row.
See also
addItem()
Definition at line 1521 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     d->listModel()->insert(row, new QListWidgetItem(label));
 }
insertItems()
void QListWidget::insertItems (int row, const QStringList & labels)
Inserts items from the list of labels into the list, starting at the given row.
See also
insertItem(), addItem()
Definition at line 1534 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     d->listModel()->insert(row, labels);
 }
isItemHidden()
bool QListWidget::isItemHidden (const QListWidgetItem * item) const
Returns true if the item is explicitly hidden; otherwise returns false.
This function is deprecated. Use QListWidgetItem::isHidden() instead.
Definition at line 1868 of file qlistwidget.cpp.
 {
     return isRowHidden(row(item));
 }
isItemSelected()
bool QListWidget::isItemSelected (const QListWidgetItem * item) const
Returns true if item is selected; otherwise returns false.
This function is deprecated. Use QListWidgetItem::isSelected() instead.
Definition at line 1799 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     QModelIndex index = d->listModel()->index(const_cast<QListWidgetItem*>(item));
     return selectionModel()->isSelected(index);
 }
isSortingEnabled()
bool QListWidget::isSortingEnabled () const
Definition at line 1705 of file qlistwidget.cpp.
Referenced by QListModel::insert().
 {
     Q_D(const QListWidget);
     return d->sortingEnabled;
 }
item()
QListWidgetItem * QListWidget::item (int row) const
Returns the item that occupies the given row in the list if one has been set; otherwise returns 0.
See also
row()
Definition at line 1480 of file qlistwidget.cpp.
Referenced by QListWidgetItem::setFont().
 {
     Q_D(const QListWidget);
     if (row < 0 || row >= d->model->rowCount())
         return 0;
     return d->listModel()->at(row);
 }
itemActivated
void QListWidget::itemActivated (QListWidgetItem * item) signal
This signal is emitted when the item is activated.
The item is activated when the user clicks or double clicks on it, depending on the system configuration. It is also activated when the user presses the activation key (on Windows and X11 this is the Return key, on Mac OS X it is Ctrl+0).
itemAt() [1/2]
QListWidgetItem * QListWidget::itemAt (const QPoint & p) const
Returns a pointer to the item at the coordinates p.
The coordinates are relative to the list widget's QAbstractScrollArea::viewport().
Definition at line 1648 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     return d->listModel()->at(indexAt(p).row());
 }
itemAt() [2/2]
QListWidgetItem * QListWidget::itemAt (int x, int y) const inline
This is an overloaded member function, provided for convenience. It differs from the above function only in what argument(s) it accepts.Returns a pointer to the item at the coordinates (x, y).
The coordinates are relative to the list widget's QAbstractScrollArea::viewport().
Definition at line 314 of file qlistwidget.h.
 { return itemAt(QPoint(ax, ay)); }
itemChanged
void QListWidget::itemChanged (QListWidgetItem * item) signal
This signal is emitted whenever the data of item has changed.
itemClicked
void QListWidget::itemClicked (QListWidgetItem * item) signal
This signal is emitted with the specified item when a mouse button is clicked on an item in the widget.
See also
itemPressed(), itemDoubleClicked()
itemDoubleClicked
void QListWidget::itemDoubleClicked (QListWidgetItem * item) signal
This signal is emitted with the specified item when a mouse button is double clicked on an item in the widget.
See also
itemClicked(), itemPressed()
itemEntered
void QListWidget::itemEntered (QListWidgetItem * item) signal
This signal is emitted when the mouse cursor enters an item.
The item is the item entered. This signal is only emitted when mouseTracking is turned on, or when a mouse button is pressed while moving into an item.
See also
QWidget::setMouseTracking()
itemFromIndex()
QListWidgetItem * QListWidget::itemFromIndex (const QModelIndex & index) const protected
Returns a pointer to the QListWidgetItem assocated with the given index.
Definition at line 2036 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     if (d->isIndexValid(index))
         return d->listModel()->at(index.row());
     return 0;
 }
itemPressed
void QListWidget::itemPressed (QListWidgetItem * item) signal
This signal is emitted with the specified item when a mouse button is pressed on an item in the widget.
See also
itemClicked(), itemDoubleClicked()
items()
QList< QListWidgetItem * > QListWidget::items (const QMimeData * data) const protected
Returns a list of pointers to the items contained in the data object.
If the object was not created by a QListWidget in the same process, the list is empty.
Definition at line 2014 of file qlistwidget.cpp.
Referenced by findItems(), and selectedItems().
 {
     const QListWidgetMimeData *lwd = qobject_cast<const QListWidgetMimeData*>(data);
     if (lwd)
         return lwd->items;
     return QList<QListWidgetItem*>();
 }
itemSelectionChanged
void QListWidget::itemSelectionChanged () signal
This signal is emitted whenever the selection changes.
See also
selectedItems(), QListWidgetItem::isSelected(), currentItemChanged()
itemWidget()
QWidget * QListWidget::itemWidget (QListWidgetItem * item) const
Returns the widget displayed in the given item.
Since
4.1
Definition at line 1763 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     QModelIndex index = d->listModel()->index(item);
     return QAbstractItemView::indexWidget(index);
 }
mimeData()
QMimeData * QListWidget::mimeData (const QList< QListWidgetItem *> items) const protected virtual
Returns an object that contains a serialized description of the specified items.
The format used to describe the items is obtained from the mimeTypes() function.
If the list of items is empty, 0 is returned instead of a serialized empty list.
Definition at line 1929 of file qlistwidget.cpp.
Referenced by QListModel::mimeData().
 {
     return d_func()->listModel()->internalMimeData();
 }
mimeTypes()
QStringList QListWidget::mimeTypes () const protected virtual
Returns a list of MIME types that can be used to describe a list of listwidget items.
See also
mimeData()
Definition at line 1916 of file qlistwidget.cpp.
Referenced by QListModel::mimeTypes().
 {
     return d_func()->listModel()->QAbstractListModel::mimeTypes();
 }
openPersistentEditor()
void QListWidget::openPersistentEditor (QListWidgetItem * item)
Opens an editor for the given item.
The editor remains open after editing.
See also
closePersistentEditor()
Definition at line 1736 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     QModelIndex index = d->listModel()->index(item);
     QAbstractItemView::openPersistentEditor(index);
 }
removeItemWidget()
void QListWidget::removeItemWidget (QListWidgetItem * item) inline
Since
4.3
Removes the widget set on the given item.
Definition at line 308 of file qlistwidget.h.
 { setItemWidget(aItem, 0); }
row()
int QListWidget::row (const QListWidgetItem * item) const
Returns the row containing the given item.
See also
item()
Definition at line 1494 of file qlistwidget.cpp.
Referenced by currentItem(), dropEvent(), dropMimeData(), isItemHidden(), itemAt(), setCurrentItem(), and setItemHidden().
 {
     Q_D(const QListWidget);
     return d->listModel()->index(const_cast<QListWidgetItem*>(item)).row();
 }
scrollToItem
void QListWidget::scrollToItem (const QListWidgetItem * item, QAbstractItemView::ScrollHint hint = EnsureVisible) slot
Scrolls the view if necessary to ensure that the item is visible.
hint specifies where the item should be located after the operation.
Definition at line 1891 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     QModelIndex index = d->listModel()->index(const_cast<QListWidgetItem*>(item));
     QListView::scrollTo(index, hint);
 }
selectedItems()
QList< QListWidgetItem * > QListWidget::selectedItems () const
Returns a list of all selected items in the list widget.
Definition at line 1835 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     QModelIndexList indexes = selectionModel()->selectedIndexes();
     QList<QListWidgetItem*> items;
     for (int i = 0; i < indexes.count(); ++i)
         items.append(d->listModel()->at(indexes.at(i).row()));
     return items;
 }
setCurrentItem() [1/2]
void QListWidget::setCurrentItem (QListWidgetItem * item)
Sets the current item to item.
Unless the selection mode is QAbstractItemView::NoSelection, the item is also be selected.
Definition at line 1588 of file qlistwidget.cpp.
 {
     setCurrentRow(row(item));
 }
setCurrentItem() [2/2]
void QListWidget::setCurrentItem (QListWidgetItem * item, QItemSelectionModel::SelectionFlags command)
Set the current item to item, using the given command.
Since
4.4
Definition at line 1600 of file qlistwidget.cpp.
 {
     setCurrentRow(row(item), command);
 }
setCurrentRow() [1/2]
void QListWidget::setCurrentRow (int row)
Definition at line 1620 of file qlistwidget.cpp.
Referenced by setCurrentItem().
 {
     Q_D(QListWidget);
     QModelIndex index = d->listModel()->index(row);
     if (d->selectionMode == SingleSelection)
         selectionModel()->setCurrentIndex(index, QItemSelectionModel::ClearAndSelect);
     else if (d->selectionMode == NoSelection)
         selectionModel()->setCurrentIndex(index, QItemSelectionModel::NoUpdate);
     else
         selectionModel()->setCurrentIndex(index, QItemSelectionModel::SelectCurrent);
 }
setCurrentRow() [2/2]
void QListWidget::setCurrentRow (int row, QItemSelectionModel::SelectionFlags command)
Since
4.4
Sets the current row to be the given row, using the given command,
Definition at line 1637 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     d->selectionModel->setCurrentIndex(d->listModel()->index(row), command);
 }
setItemHidden()
void QListWidget::setItemHidden (const QListWidgetItem * item, bool hide)
If hide is true, the item will be hidden; otherwise it will be shown.
This function is deprecated. Use QListWidgetItem::setHidden() instead.
Definition at line 1880 of file qlistwidget.cpp.
 {
     setRowHidden(row(item), hide);
 }
setItemSelected()
void QListWidget::setItemSelected (const QListWidgetItem * item, bool select)
Selects or deselects the given item depending on whether select is true of false.
This function is deprecated. Use QListWidgetItem::setSelected() instead.
Definition at line 1814 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     QModelIndex index = d->listModel()->index(const_cast<QListWidgetItem*>(item));
     if (d->selectionMode == SingleSelection) {
         selectionModel()->select(index, select
                                  ? QItemSelectionModel::ClearAndSelect
                                  : QItemSelectionModel::Deselect);
     } else if (d->selectionMode != NoSelection) {
         selectionModel()->select(index, select
                                  ? QItemSelectionModel::Select
                                  : QItemSelectionModel::Deselect);
     }
 }
setItemWidget()
void QListWidget::setItemWidget (QListWidgetItem * item, QWidget * widget)
Sets the widget to be displayed in the give item.
Since
4.1
This function should only be used to display static content in the place of a list widget item. If you want to display custom dynamic content or implement a custom editor widget, use QListView and subclass QItemDelegate instead.
See also
{Delegate Classes}
Definition at line 1785 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     QModelIndex index = d->listModel()->index(item);
     QAbstractItemView::setIndexWidget(index, widget);
 }
setModel()
void QListWidget::setModel (QAbstractItemModel * model) private virtual
Warning
This function is not part of the public interface.
Reimplemented from QAbstractItemView.
Definition at line 2047 of file qlistwidget.cpp.
 {
     Q_ASSERT(!"QListWidget::setModel() - Changing the model of the QListWidget is not allowed.");
 }
setSortingEnabled()
void QListWidget::setSortingEnabled (bool enable)
Definition at line 1699 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     d->sortingEnabled = enable;
 }
sortItems()
void QListWidget::sortItems (Qt::SortOrder order = Qt::AscendingOrder)
Sorts all the items in the list widget according to the specified order.
Definition at line 1679 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     d->sortOrder = order;
     d->listModel()->sort(0, order);
 }
sortOrder()
Qt::SortOrder QListWidget::sortOrder () const private
Warning
This function is not part of the public interface.
Definition at line 1714 of file qlistwidget.cpp.
Referenced by QListModel::insert().
 {
     Q_D(const QListWidget);
     return d->sortOrder;
 }
supportedDropActions()
Qt::DropActions QListWidget::supportedDropActions () const protected virtual
Returns the drop actions supported by this view.
See also
Qt::DropActions
Definition at line 2002 of file qlistwidget.cpp.
Referenced by QListModel::supportedDropActions().
 {
     Q_D(const QListWidget);
     return d->listModel()->QAbstractListModel::supportedDropActions() | Qt::MoveAction;
 }
takeItem()
QListWidgetItem * QListWidget::takeItem (int row)
Removes and returns the item from the given row in the list widget; otherwise returns 0.
Items removed from a list widget will not be managed by Qt, and will need to be deleted manually.
See also
insertItem(), addItem()
Definition at line 1550 of file qlistwidget.cpp.
 {
     Q_D(QListWidget);
     if (row < 0 || row >= d->model->rowCount())
         return 0;
     return d->listModel()->take(row);
 }
visualItemRect()
QRect QListWidget::visualItemRect (const QListWidgetItem * item) const
Returns the rectangle on the viewport occupied by the item at item.
Definition at line 1669 of file qlistwidget.cpp.
 {
     Q_D(const QListWidget);
     QModelIndex index = d->listModel()->index(const_cast<QListWidgetItem*>(item));
     return visualRect(index);
 }
Friends and Related Functions
QListModel
friend class QListModel friend
Definition at line 210 of file qlistwidget.h.
QListWidgetItem
friend class QListWidgetItem friend
Definition at line 209 of file qlistwidget.h.
Referenced by insertItem().
Properties
count
int QListWidget::count private
the number of items in the list including any hidden items.
Definition at line 205 of file qlistwidget.h.
currentRow
int QListWidget::currentRow private
the row of the current item.
Depending on the current selection mode, the row may also be selected.
Definition at line 206 of file qlistwidget.h.
sortingEnabled
QListWidget::sortingEnabled private
whether sorting is enabled
Since
4.2
If this property is true, sorting is enabled for the list; if the property is false, sorting is not enabled.
The default value is false.
Definition at line 207 of file qlistwidget.h.
The documentation for this class was generated from the following files:
/src/gui/itemviews/qlistwidget.h
/src/gui/itemviews/qlistwidget.cpp