Qt 4.8: QDataBuffer< Type > Class Template Reference
QDataBuffer< Type > Class Template Reference
#include <qdatabuffer_p.h>
Public Functions
void add (const Type &t)
Type & at (int i)
const Type & at (int i) const
Type * data () const
Type & first ()
const Type & first () const
bool isEmpty () const
Type & last ()
const Type & last () const
QDataBuffer & operator<< (const Type &t)
void pop_back ()
QDataBuffer (int res)
void reserve (int size)
void reset ()
void resize (int size)
void shrink (int size)
int size () const
void swap (QDataBuffer< Type > &other)
~QDataBuffer ()
Properties
Type * buffer
int capacity
int siz
Detailed Description
template<typename Type>
class QDataBuffer< Type >
Definition at line 60 of file qdatabuffer_p.h.
Constructors and Destructors
QDataBuffer()
template<typename Type> QDataBuffer< Type >::QDataBuffer (int res) inline
Definition at line 63 of file qdatabuffer_p.h.
     {
         capacity = res;
         if (res)
             buffer = (Type*) qMalloc(capacity * sizeof(Type));
         else
             buffer = 0;
         siz = 0;
     }
~QDataBuffer()
template<typename Type> QDataBuffer< Type >::~QDataBuffer () inline
Definition at line 73 of file qdatabuffer_p.h.
     {
         if (buffer)
             qFree(buffer);
     }
Functions
add()
template<typename Type> void QDataBuffer< Type >::add (const Type & t) inline
Definition at line 93 of file qdatabuffer_p.h.
Referenced by QGL2PEXVertexArray::addCentroid(), QGL2PEXVertexArray::addClosingLine(), QGL2PEXVertexArray::addPath(), QPolygonClipper< qt_float_point, qt_float_point, float >::clipPolygon(), QTriangulatingStroker::emitLineSegment(), QTriangulatingStroker::endCap(), QTriangulatingStroker::endCapOrJoinClosed(), QIntersectionFinder::hasIntersections(), QTriangulatingStroker::join(), QOutlineMapper::lineTo(), QGL2PEXVertexArray::lineToArray(), QTriangulatingStroker::moveTo(), QDataBuffer< GLfloat >::operator<<(), and QOpenGLPaintEnginePrivate::updateDepthClip().
{
         reserve(siz + 1);
         buffer[siz] = t;
         ++siz;
     }
at() [1/2]
template<typename Type> Type& QDataBuffer< Type >::at (int i) inline
Definition at line 86 of file qdatabuffer_p.h.
Referenced by QGL2PEXVertexArray::addClosingLine(), QPolygonClipper< qt_float_point, qt_float_point, float >::clipPolygon(), QOutlineMapper::closeSubpath(), QTriangulatingStroker::endCap(), QTriangulatingStroker::endCapOrJoinClosed(), QOutlineMapper::endOutline(), QWingedEdge::insert(), QTriangulatingStroker::join(), QPathSegments::lineAt(), QPathSegments::mergePoints(), QTriangulator< T >::SimpleToMonotone::monotoneDecomposition(), QTriangulatingStroker::moveTo(), QSubpathForwardIterator::next(), QSubpathBackwardIterator::next(), QSubpathFlatIterator::next(), QTriangulator< T >::ComplexToSimple::Event::operator<(), and QPathSegments::pointAt().
 { Q_ASSERT(i >= 0 && i < siz); return buffer[i]; }
at() [2/2]
template<typename Type> const Type& QDataBuffer< Type >::at (int i) const inline
Definition at line 87 of file qdatabuffer_p.h.
 { Q_ASSERT(i >= 0 && i < siz); return buffer[i]; }
data()
template<typename Type> Type* QDataBuffer< Type >::data () const inline
Definition at line 84 of file qdatabuffer_p.h.
Referenced by QPolygonClipper< qt_float_point, qt_float_point, float >::clipPolygon(), QOutlineMapper::convertElements(), QOutlineMapper::convertPath(), QOutlineMapper::elementTypes(), QOutlineMapper::endOutline(), QGL2PaintEngineExPrivate::transferMode(), and QTriangulatingStroker::vertices().
 { return buffer; }
first() [1/2]
template<typename Type> Type& QDataBuffer< Type >::first () inline
Definition at line 90 of file qdatabuffer_p.h.
 { Q_ASSERT(!isEmpty()); return buffer[0]; }
first() [2/2]
template<typename Type> const Type& QDataBuffer< Type >::first () const inline
Definition at line 91 of file qdatabuffer_p.h.
 { Q_ASSERT(!isEmpty()); return buffer[0]; }
isEmpty()
template<typename Type> bool QDataBuffer< Type >::isEmpty () const inline
Definition at line 81 of file qdatabuffer_p.h.
Referenced by QDataBuffer< GLfloat >::first(), QWingedEdge::insert(), QDataBuffer< GLfloat >::last(), and QTriangulator< T >::ComplexToSimple::Event::operator<().
 { return siz==0; }
last() [1/2]
template<typename Type> Type& QDataBuffer< Type >::last () inline
Definition at line 88 of file qdatabuffer_p.h.
Referenced by QGL2PEXVertexArray::addClosingLine(), QWingedEdge::insert(), and QTriangulator< T >::SimpleToMonotone::monotoneDecomposition().
 { Q_ASSERT(!isEmpty()); return buffer[siz-1]; }
last() [2/2]
template<typename Type> const Type& QDataBuffer< Type >::last () const inline
Definition at line 89 of file qdatabuffer_p.h.
 { Q_ASSERT(!isEmpty()); return buffer[siz-1]; }
operator<<()
template<typename Type> QDataBuffer& QDataBuffer< Type >::operator<< (const Type & t) inline
Definition at line 135 of file qdatabuffer_p.h.
 { add(t); return *this; }
pop_back()
template<typename Type> void QDataBuffer< Type >::pop_back () inline
Definition at line 99 of file qdatabuffer_p.h.
{
         Q_ASSERT(siz > 0);
         --siz;
     }
reserve()
template<typename Type> void QDataBuffer< Type >::reserve (int size) inline
Definition at line 109 of file qdatabuffer_p.h.
Referenced by QDataBuffer< GLfloat >::add(), QDashedStrokeProcessor::process(), and QDataBuffer< GLfloat >::resize().
{
         if (size > capacity) {
             if (capacity == 0)
                 capacity = 1;
             while (capacity < size)
                 capacity *= 2;
             buffer = (Type*) qRealloc(buffer, capacity * sizeof(Type));
         }
     }
reset()
template<typename Type> void QDataBuffer< Type >::reset () inline
Definition at line 79 of file qdatabuffer_p.h.
Referenced by QOutlineMapper::beginOutline(), QGL2PEXVertexArray::clear(), QPolygonClipper< qt_float_point, qt_float_point, float >::clipPolygon(), QTriangulator< T >::MonotoneToTriangles::decompose(), QWingedEdge::intersectAndAdd(), QTriangulatingStroker::process(), and QDashedStrokeProcessor::process().
 { siz = 0; }
resize()
template<typename Type> void QDataBuffer< Type >::resize (int size) inline
Definition at line 104 of file qdatabuffer_p.h.
Referenced by QOutlineMapper::convertPath(), QTriangulatingStroker::moveTo(), QTriangulator< T >::ComplexToSimple::removeUnusedPoints(), and QTriangulator< T >::SimpleToMonotone::removeZeroLengthEdges().
{
         reserve(size);
         siz = size;
     }
shrink()
template<typename Type> void QDataBuffer< Type >::shrink (int size) inline
Definition at line 119 of file qdatabuffer_p.h.
{
         capacity = size;
         if (size)
             buffer = (Type*) qRealloc(buffer, capacity * sizeof(Type));
         else {
             qFree(buffer);
             buffer = 0;
         }
     }
size()
template<typename Type> int QDataBuffer< Type >::size () const inline
Definition at line 83 of file qdatabuffer_p.h.
Referenced by QWingedEdge::addEdge(), QGL2PEXVertexArray::addPath(), QPathSegments::addPoint(), QPolygonClipper< qt_float_point, qt_float_point, float >::clipPolygon(), QOutlineMapper::closeSubpath(), QOutlineMapper::convertElements(), QTriangulator< T >::MonotoneToTriangles::decompose(), QOutlineMapper::elementTypes(), QTriangulatingStroker::endCap(), QTriangulatingStroker::endCapOrJoinClosed(), QOutlineMapper::endOutline(), QSubpathForwardIterator::hasNext(), QSubpathFlatIterator::hasNext(), QWingedEdge::insert(), QTriangulatingStroker::join(), QPathSegments::mergePoints(), QTriangulator< T >::SimpleToMonotone::monotoneDecomposition(), QTriangulatingStroker::moveTo(), QOutlineMapper::moveTo(), QSubpathBackwardIterator::next(), QTriangulator< T >::ComplexToSimple::Event::operator<(), QPathSegments::points(), QDataBuffer< GLfloat >::resize(), QDataBuffer< GLfloat >::shrink(), and QTriangulatingStroker::vertexCount().
 { return siz; }
swap()
template<typename Type> void QDataBuffer< Type >::swap (QDataBuffer< Type > & other) inline
Definition at line 129 of file qdatabuffer_p.h.
{
         qSwap(capacity, other.capacity);
         qSwap(siz, other.siz);
         qSwap(buffer, other.buffer);
     }
Properties
buffer
template<typename Type> Type* QDataBuffer< Type >::buffer private
Definition at line 140 of file qdatabuffer_p.h.
Referenced by QDataBuffer< GLfloat >::add(), QDataBuffer< GLfloat >::at(), QDataBuffer< GLfloat >::data(), QDataBuffer< GLfloat >::first(), QDataBuffer< GLfloat >::last(), QDataBuffer< GLfloat >::QDataBuffer(), QDataBuffer< GLfloat >::reserve(), QDataBuffer< GLfloat >::shrink(), QDataBuffer< GLfloat >::swap(), and QDataBuffer< GLfloat >::~QDataBuffer().
capacity
template<typename Type> int QDataBuffer< Type >::capacity private
Definition at line 138 of file qdatabuffer_p.h.
Referenced by QDataBuffer< GLfloat >::QDataBuffer(), QDataBuffer< GLfloat >::reserve(), QDataBuffer< GLfloat >::shrink(), and QDataBuffer< GLfloat >::swap().
siz
template<typename Type> int QDataBuffer< Type >::siz private
Definition at line 139 of file qdatabuffer_p.h.
Referenced by QDataBuffer< GLfloat >::add(), QDataBuffer< GLfloat >::at(), QDataBuffer< GLfloat >::isEmpty(), QDataBuffer< GLfloat >::last(), QDataBuffer< GLfloat >::pop_back(), QDataBuffer< GLfloat >::QDataBuffer(), QDataBuffer< GLfloat >::reset(), QDataBuffer< GLfloat >::resize(), QDataBuffer< GLfloat >::size(), and QDataBuffer< GLfloat >::swap().
The documentation for this class was generated from the following file:
/src/gui/painting/qdatabuffer_p.h