Qt 4.8: QScript::QObjectConnectionManager Class Reference
QScript::QObjectConnectionManager Class Reference
Public Functions
bool addSignalHandler (QObject *sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot, JSC::JSValue senderWrapper, Qt::ConnectionType type)
void execute (int slotIndex, void **argv)
void mark (JSC::MarkStack &)
virtual const QMetaObject * metaObject () const
Returns a pointer to the meta-object of this object.
QObjectConnectionManager (QScriptEnginePrivate *engine)
virtual int qt_metacall (QMetaObject::Call, int, void **argv)
virtual void * qt_metacast (const char *)
bool removeSignalHandler (QObject *sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot)
~QObjectConnectionManager ()
Public Functions inherited from QObject
bool blockSignals (bool b)
If block is true, signals emitted by this object are blocked (i.e., emitting a signal will not invoke anything connected to it).
const QObjectList & children () const
Returns a list of child objects.
bool connect (const QObject *sender, const char *signal, const char *member, Qt::ConnectionType type=Qt::AutoConnection) const
bool disconnect (const char *signal=0, const QObject *receiver=0, const char *member=0)
bool disconnect (const QObject *receiver, const char *member=0)
void dumpObjectInfo ()
Dumps information about signal connections, etc.
void dumpObjectTree ()
Dumps a tree of children to the debug output.
QList< QByteArray > dynamicPropertyNames () const
Returns the names of all properties that were dynamically added to the object using setProperty().
virtual bool event (QEvent *)
This virtual function receives events to an object and should return true if the event e was recognized and processed.
virtual bool eventFilter (QObject *, QEvent *)
Filters events if this object has been installed as an event filter for the watched object.
template<typename T >
T findChild (const QString &aName=QString()) const
Returns the child of this object that can be cast into type T and that is called name, or 0 if there is no such object.
template<typename T >
QList< T > findChildren (const QString &aName=QString()) const
Returns all children of this object with the given name that can be cast to type T, or an empty list if there are no such objects.
template<typename T >
QList< T > findChildren (const QRegExp &re) const
bool inherits (const char *classname) const
Returns true if this object is an instance of a class that inherits className or a QObject subclass that inherits className; otherwise returns false.
void installEventFilter (QObject *)
Installs an event filter filterObj on this object.
bool isWidgetType () const
Returns true if the object is a widget; otherwise returns false.
void killTimer (int id)
Kills the timer with timer identifier, id.
void moveToThread (QThread *thread)
Changes the thread affinity for this object and its children.
QString objectName () const
QObject * parent () const
Returns a pointer to the parent object.
QVariant property (const char *name) const
Returns the value of the object's name property.
Q_INVOKABLE QObject (QObject *parent=0)
Constructs an object with parent object parent.
void removeEventFilter (QObject *)
Removes an event filter object obj from this object.
void setObjectName (const QString &name)
void setParent (QObject *)
Makes the object a child of parent.
bool setProperty (const char *name, const QVariant &value)
Sets the value of the object's name property to value.
void setUserData (uint id, QObjectUserData *data)
bool signalsBlocked () const
Returns true if signals are blocked; otherwise returns false.
int startTimer (int interval)
Starts a timer and returns a timer identifier, or returns zero if it could not start a timer.
QThread * thread () const
Returns the thread in which the object lives.
QObjectUserData * userData (uint id) const
virtual ~QObject ()
Destroys the object, deleting all its child objects.
Static Public Variables
static const QMetaObject staticMetaObject
Static Public Variables inherited from QObject
static const QMetaObject staticMetaObject
This variable stores the meta-object for the class.
Properties
QVector< QVector< QObjectConnection > > connections
QScriptEnginePrivate * engine
int slotCounter
Additional Inherited Members
Public Slots inherited from QObject
void deleteLater ()
Schedules this object for deletion.
Signals inherited from QObject
void destroyed (QObject *=0)
This signal is emitted immediately before the object obj is destroyed, and can not be blocked.
Static Public Functions inherited from QObject
static bool connect (const QObject *sender, const char *signal, const QObject *receiver, const char *member, Qt::ConnectionType=Qt::AutoConnection)
Creates a connection of the given type from the signal in the sender object to the method in the receiver object.
static bool connect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &method, Qt::ConnectionType type=Qt::AutoConnection)
static bool disconnect (const QObject *sender, const char *signal, const QObject *receiver, const char *member)
Disconnects signal in object sender from method in object receiver.
static bool disconnect (const QObject *sender, const QMetaMethod &signal, const QObject *receiver, const QMetaMethod &member)
static uint registerUserData ()
static QString tr (const char *sourceText, const char *comment=0, int n=-1)
static QString trUtf8 (const char *sourceText, const char *comment=0, int n=-1)
Protected Functions inherited from QObject
virtual void childEvent (QChildEvent *)
This event handler can be reimplemented in a subclass to receive child events.
virtual void connectNotify (const char *signal)
This virtual function is called when something has been connected to signal in this object.
virtual void customEvent (QEvent *)
This event handler can be reimplemented in a subclass to receive custom events.
virtual void disconnectNotify (const char *signal)
This virtual function is called when something has been disconnected from signal in this object.
QObject (QObjectPrivate &dd, QObject *parent=0)
int receivers (const char *signal) const
Returns the number of receivers connected to the signal.
QObject * sender () const
Returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns 0.
int senderSignalIndex () const
virtual void timerEvent (QTimerEvent *)
This event handler can be reimplemented in a subclass to receive timer events for the object.
Protected Variables inherited from QObject
QScopedPointer< QObjectData > d_ptr
Static Protected Variables inherited from QObject
static const QMetaObject staticQtMetaObject
Related Functions inherited from QObject
T qFindChildqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QString &name)()
QList< T > qFindChildrenqFindChildren (const QObject *obj, const QRegExp &regExp)()
T * qobject_cast (QObject *object)
QObjectList
void * qt_find_obj_child (QObject *parent, const char *type, const QString &name)
Returns a pointer to the object named name that inherits type and with a given parent.
Detailed Description
Definition at line 122 of file qscriptqobject.cpp.
Constructors and Destructors
QObjectConnectionManager()
QScript::QObjectConnectionManager::QObjectConnectionManager (QScriptEnginePrivate * engine)
Definition at line 2186 of file qscriptqobject.cpp.
     : engine(eng), slotCounter(0)
 {
 }
~QObjectConnectionManager()
QScript::QObjectConnectionManager::~QObjectConnectionManager ()
Definition at line 2191 of file qscriptqobject.cpp.
 {
 }
Functions
addSignalHandler()
bool QScript::QObjectConnectionManager::addSignalHandler (QObject * sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot, JSC::JSValue senderWrapper, Qt::ConnectionType type)
Definition at line 2204 of file qscriptqobject.cpp.
Referenced by QScript::QObjectData::addSignalHandler().
 {
     if (connections.size() <= signalIndex)
         connections.resize(signalIndex+1);
     QVector<QObjectConnection> &cs = connections[signalIndex];
     int absSlotIndex = slotCounter + metaObject()->methodOffset();
     bool ok = QMetaObject::connect(sender, signalIndex, this, absSlotIndex, type);
     if (ok) {
         cs.append(QObjectConnection(slotCounter++, receiver, function, senderWrapper));
         QMetaMethod signal = sender->metaObject()->method(signalIndex);
         QByteArray signalString;
         signalString.append('2'); // signal code
         signalString.append(signal.signature());
         static_cast<QObjectNotifyCaller*>(sender)->callConnectNotify(signalString);
     }
     return ok;
 }
execute()
void QScript::QObjectConnectionManager::execute (int slotIndex, void ** argv)
Definition at line 2081 of file qscriptqobject.cpp.
 {
     JSC::JSValue receiver;
     JSC::JSValue slot;
     JSC::JSValue senderWrapper;
     int signalIndex = -1;
     QScript::APIShim shim(engine);
     for (int i = 0; i < connections.size(); ++i) {
         const QVector<QObjectConnection> &cs = connections.at(i);
         for (int j = 0; j < cs.size(); ++j) {
             const QObjectConnection &c = cs.at(j);
             if (c.slotIndex == slotIndex) {
                 receiver = c.receiver;
                 slot = c.slot;
                 senderWrapper = c.senderWrapper;
                 signalIndex = i;
                 break;
             }
         }
     }
     if (!slot) {
         // This connection no longer exists (can happen if the signal is
         // emitted from another thread and the call gets queued, but the
         // connection is removed before the QMetaCallEvent gets processed).
         return;
     }
     Q_ASSERT(slot.isObject());
     if (engine->isCollecting()) {
         qWarning("QtScript: can't execute signal handler during GC");
         // we can't do a script function call during GC,
         // so we're forced to ignore this signal
         return;
     }
 #if 0
     QScriptFunction *fun = engine->convertToNativeFunction(slot);
     if (fun == 0) {
         // the signal handler has been GC'ed. This can only happen when
         // a QObject is owned by the engine, the engine is destroyed, and
         // there is a script function connected to the destroyed() signal
         Q_ASSERT(signalIndex <= 1); // destroyed(QObject*)
         return;
     }
 #endif
     const QMetaObject *meta = sender()->metaObject();
     const QMetaMethod method = meta->method(signalIndex);
     QList<QByteArray> parameterTypes = method.parameterTypes();
     int argc = parameterTypes.count();
     JSC::ExecState *exec = engine->currentFrame;
     QVarLengthArray<JSC::JSValue, 8> argsVector(argc);
     for (int i = 0; i < argc; ++i) {
         JSC::JSValue actual;
         void *arg = argv[i + 1];
         QByteArray typeName = parameterTypes.at(i);
         int argType = QMetaType::type(parameterTypes.at(i));
         if (!argType) {
             qWarning("QScriptEngine: Unable to handle unregistered datatype '%s' "
                         "when invoking handler of signal %s::%s",
                         typeName.constData(), meta->className(), method.signature());
             actual = JSC::jsUndefined();
         } else if (argType == QMetaType::QVariant) {
             actual = QScriptEnginePrivate::jscValueFromVariant(exec, *reinterpret_cast<QVariant*>(arg));
         } else {
             actual = QScriptEnginePrivate::create(exec, argType, arg);
         }
         argsVector[i] = actual;
     }
     JSC::ArgList jscArgs(argsVector.data(), argsVector.size());
     JSC::JSValue senderObject;
     if (senderWrapper && senderWrapper.inherits(&QScriptObject::info)) // ### check if it's actually a QObject wrapper
         senderObject = senderWrapper;
     else {
         QScriptEngine::QObjectWrapOptions opt = QScriptEngine::PreferExistingWrapperObject;
         senderObject = engine->newQObject(sender(), QScriptEngine::QtOwnership, opt);
     }
     JSC::JSValue thisObject;
     if (receiver && receiver.isObject())
         thisObject = receiver;
     else
         thisObject = engine->globalObject();
     JSC::CallData callData;
     JSC::CallType callType = slot.getCallData(callData);
     if (exec->hadException())
         exec->clearException(); // ### otherwise JSC asserts
     JSC::call(exec, slot, callType, callData, thisObject, jscArgs);
     if (exec->hadException()) {
         if (slot.inherits(&QtFunction::info) && !static_cast<QtFunction*>(JSC::asObject(slot))->qobject()) {
             // The function threw an error because the target QObject has been deleted.
             // The connections list is stale; remove the signal handler and ignore the exception.
             removeSignalHandler(sender(), signalIndex, receiver, slot);
             exec->clearException();
         } else {
             engine->emitSignalHandlerException();
         }
     }
 }
mark()
void QScript::QObjectConnectionManager::mark (JSC::MarkStack & markStack)
Definition at line 2195 of file qscriptqobject.cpp.
Referenced by QScript::QObjectData::mark().
 {
     for (int i = 0; i < connections.size(); ++i) {
         QVector<QObjectConnection> &cs = connections[i];
         for (int j = 0; j < cs.size(); ++j)
             cs[j].mark(markStack);
     }
 }
metaObject()
const QMetaObject * QScript::QObjectConnectionManager::metaObject () const virtual
Returns a pointer to the meta-object of this object.
A meta-object contains information about a class that inherits QObject, e.g. class name, superclass name, properties, signals and slots. Every QObject subclass that contains the Q_OBJECT macro will have a meta-object.
The meta-object information is required by the signal/slot connection mechanism and the property system. The inherits() function also makes use of the meta-object.
If you have no pointer to an actual object instance but still want to access the meta-object of a class, you can use staticMetaObject .
Example:
QObject *obj = new QPushButton;
obj->metaObject()->className();             // returns "QPushButton"
QPushButton::staticMetaObject.className();  // returns "QPushButton"
See also
staticMetaObject
Reimplemented from QObject.
Definition at line 2056 of file qscriptqobject.cpp.
Referenced by addSignalHandler(), and removeSignalHandler().
 {
     return &staticMetaObject;
 }
qt_metacall()
int QScript::QObjectConnectionManager::qt_metacall (QMetaObject::Call _c, int _id, void ** argv) virtual
Definition at line 2069 of file qscriptqobject.cpp.
 {
     _id = QObject::qt_metacall(_c, _id, _a);
     if (_id < 0)
         return _id;
     if (_c == QMetaObject::InvokeMetaMethod) {
         execute(_id, _a);
         _id -= slotCounter;
     }
     return _id;
 }
qt_metacast()
void * QScript::QObjectConnectionManager::qt_metacast (const char * _clname) virtual
Definition at line 2061 of file qscriptqobject.cpp.
 {
     if (!_clname) return 0;
     if (!strcmp(_clname, qt_meta_stringdata_QObjectConnectionManager))
         return static_cast<void*>(const_cast<QObjectConnectionManager*>(this));
     return QObject::qt_metacast(_clname);
 }
removeSignalHandler()
bool QScript::QObjectConnectionManager::removeSignalHandler (QObject * sender, int signalIndex, JSC::JSValue receiver, JSC::JSValue slot)
Definition at line 2225 of file qscriptqobject.cpp.
Referenced by QScript::QObjectData::removeSignalHandler().
 {
     if (connections.size() <= signalIndex)
         return false;
     QVector<QObjectConnection> &cs = connections[signalIndex];
     for (int i = 0; i < cs.size(); ++i) {
         const QObjectConnection &c = cs.at(i);
         if (c.hasTarget(receiver, slot)) {
             int absSlotIndex = c.slotIndex + metaObject()->methodOffset();
             bool ok = QMetaObject::disconnect(sender, signalIndex, this, absSlotIndex);
             if (ok) {
                 cs.remove(i);
                 QMetaMethod signal = sender->metaObject()->method(signalIndex);
                 QByteArray signalString;
                 signalString.append('2'); // signal code
                 signalString.append(signal.signature());
                 static_cast<QScript::QObjectNotifyCaller*>(sender)->callDisconnectNotify(signalString);
             }
             return ok;
         }
     }
     return false;
 }
Properties
connections
QVector<QVector<QObjectConnection> > QScript::QObjectConnectionManager::connections private
Definition at line 149 of file qscriptqobject.cpp.
Referenced by addSignalHandler(), mark(), and removeSignalHandler().
engine
QScriptEnginePrivate* QScript::QObjectConnectionManager::engine private
Definition at line 147 of file qscriptqobject.cpp.
slotCounter
int QScript::QObjectConnectionManager::slotCounter private
Definition at line 148 of file qscriptqobject.cpp.
Referenced by addSignalHandler().
staticMetaObject
const QMetaObject QScript::QObjectConnectionManager::staticMetaObject static
Initial value:
= {
    { &QObject::staticMetaObject, qt_meta_stringdata_QObjectConnectionManager,
      qt_meta_data_QObjectConnectionManager, 0 }
}
Definition at line 137 of file qscriptqobject.cpp.
The documentation for this class was generated from the following file:
/src/script/bridge/qscriptqobject.cpp